### ISSUE TITLE
GLMAT does not run in serial mode

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10019]
Marcos,
I ran across this while testing the pressure solvers.  I often need to run cases in serial for quick tests on my laptop.  So, I need all the solvers to work in serial.  There is something amiss with the `fds/Verification/Species/mass_balance_reac.fds` case, which uses the GLMAT solver.  It runs fine with 8 meshes in parallel, but gives a Numerical Instability when run in serial.

**Comment by marcosvanella** [comment]
I'll have a look.
________________________________

**Comment by marcosvanella** [comment]
Randy, try the case again. Should be fixed with PR #10024.

**Comment by rmcdermo** [comment]
Working now.  Thanks!
