### ISSUE TITLE
impi.dlls fail

### ISSUE THREAD

**Issue by Flo-23** [firemodels/fds#10029]
Bonjour,

 je me permet de vous contacter car il me manque les fichier impi.dlls lors de l'installation de la version actuelle de FDS. J'ai un pc sous window 10 et je suis administrateur sur le pc et  j'en suis le seul utilisateur. 

Bien cordialement

**Comment by emanuelegissi** [comment]
Puisque les utilisateurs de FDS viennent de cent différents pays du monde,
la langue utilisée pour toutes les discussions est l'anglais. N'oubliez pas
que l'équipe de FDS est américaine.
Cordialement,
Emanuele

**Comment by Flo-23** [comment]
Hello

I allow myself to contact you because I am missing the impi.dlls files when installing the current version of FDS. I have a pc under window 10 I am an administrator on the pc and I am the only user. I restarted the pc after installation, the FDS command prompt is not displayed, I also tried the reinstallation

Best regards

**Comment by mcgratta** [comment]
In any language, this can be confusing. As we say in English, "it's all Greek to me!"

This issue arises from time to time. Let me find another discussion thread that addresses it.

**Comment by mcgratta** [comment]
https://github.com/firemodels/fds/issues/9868

Does this help?

**Comment by Flo-23** [comment]
I have the same problem

thank you

**Comment by gforney** [comment]
Ill take another look when i get back

**Comment by Flo-23** [comment]
I manage to get fds to work by typing fdsinit in the command prompt, thank you for your help

**Comment by mcgratta** [comment]
The latest release of FDS includes a provision for dealing with the Home edition of Windows.
