### ISSUE TITLE
DSC signal appears to be incorrect

### ISSUE THREAD

**Issue by mckinnonm** [firemodels/fds#10031]
Hello all,

I'm running the latest release on a linux OS and noticed the DSC signal for my material is about 5 times higher than expected. I ran the sample file on an older release (maybe 6.7.3) and got different DSC results from the sample input file. A quick hand calc confirmed for me that the older release has the correct DSC signal value. It doesn't appear to be the incorrect units for the heating rate and all the other signals (e.g. Total MLR, MCC, etc.) appear to be identical between the two releases. I've included a sample input file to verify.

Thanks,

Mark

[test398.txt](https://github.com/firemodels/fds/files/7529348/test398.txt)

**Comment by mckinnonm** [comment]
I tried the same input file with previous releases and it looks like I get the same results with 6.7.5 as I got with 6.7.6, but the results with 6.7.4 are consistent with my expectation.

**Comment by mcgratta** [comment]
You're right. I few revs ago we made a few subtle changes to the numerical approximation of the convective heat flux at a solid boundary. In a TGA analysis, the gas and surface temperatures are very close, thus this redefinition had an impact. Should work now.
