### ISSUE TITLE
Inlet pressure loss

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#10065]
Hi,

I created a simple FDS model of an inlet to check the pressure distribution with different mesh resolutions, but I got some unexpected results.

![Untitled](https://user-images.githubusercontent.com/15084725/142888822-f4ff64b7-30a8-46b9-b639-83e25b07028e.png)

I placed an extractor (1m/s) at the end of the duct and I monitored the pressure. I expected a total pressure drop of about 0.3 Pa at the contraction section assuming that the loss coefficient is 0.5. However, when I plot the static and the total pressure distribution along the duct and in the open zone I saw that the total pressure remains almost unchanged. 

![sum](https://user-images.githubusercontent.com/15084725/142888986-77b7a308-1b53-42ed-975a-7f1af7054340.png)

I obtained these results using different mesh resolutions:
mesh 1: 4 elements across the duct
mesh 2: 8 elements across the duct
mesh 3: 16 elements across the duct
mesh 4: 32 elements across the duct
mesh 5: 48 elements across the duct
However, I don't see many differences in the outcome of the simulation.

In attachment there is an input file, I tried to use the same set up as in the validation case Backward_Facing_Step.
[input.fds.txt](https://github.com/firemodels/fds/files/7582327/input.fds.txt)

Now I don't know if I'm missing something in my input file, in the refinement level of the mesh or in the physics behind the case.

Thanks in advance for any feedback.

 Matteo

P.S. I tried also to reverse the flow modelling an outlet and I then get a loss coefficient of 1.

**Comment by rmcdermo** [comment]
@mpachera If the mesh resolution is uniform, try this with GLMAT.  But with FFT, make sure your pressure and velocity tolerances are achieving the same levels (check the .out file)

**Comment by mcgratta** [comment]
I ran a simpler version of your case. A plot of pressure along the centerline is shown. I do not  understand where your two sets of curves above come from.
```
&HEAD CHID='CFD_base001'/
&TIME T_END=100.0/

&MESH IJK=40, 4, 4, XB=-10.0,0.0,-0.5,0.5,-0.5,0.5 /
&MESH IJK=20,16,16, XB=  0.0,5.0,-2.0,2.0,-2.0,2.0 /

&VENT ID='Vent01', SURF_ID='Vel_out', XB=-10.0,-10.0,-0.5,0.5,-0.5,0.5 /
&SURF ID='Vel_out', VEL=1, COLOR='RED', TAU_V=-20 /

&VENT SURF_ID='OPEN', XB=5.0,5.0,-2.0, 2.0,-2.0, 2.0 /
&VENT SURF_ID='OPEN', XB=0.0,5.0, 2.0, 2.0,-2.0, 2.0 /
&VENT SURF_ID='OPEN', XB=0.0,5.0,-2.0,-2.0,-2.0, 2.0 /
&VENT SURF_ID='OPEN', XB=0.0,5.0,-2.0, 2.0, 2.0, 2.0 /
&VENT SURF_ID='OPEN', XB=0.0,5.0,-2.0, 2.0,-2.0,-2.0 /

&DEVC XB = -9.875 , 4.875 ,  0.001, 0.001 ,  0.001 , 0.001 , POINTS=60, QUANTITY='PRESSURE',   ID='pres', STATISTICS_START=50 /
&DEVC XB = -9.875 , 4.875 ,  0.001, 0.001 ,  0.001 , 0.001 , POINTS=60, QUANTITY='U-VELOCITY', ID='velo', STATISTICS_START=50, HIDE_COORDINATES=T /

&SLCF PBY=0.001, QUANTITY='VELOCITY', VECTOR=T/
&SLCF PBY=0.001, QUANTITY='PRESSURE', CELL_CENTERED=T/

&TAIL /
```

![image](https://user-images.githubusercontent.com/11333911/142901429-6efde605-9085-4b80-bf3b-58bd28f9f3b7.png)

**Comment by mpachera** [comment]
@rmcdermo I checked the out files for the different calculations and I made few plots containing iteration number, pressure error and velocity error.

![iter](https://user-images.githubusercontent.com/15084725/142932174-9138443d-45b5-4631-a9f9-8959ea96818a.png)

![error_vel](https://user-images.githubusercontent.com/15084725/142932192-5bbec3f9-cbdf-4479-9588-7e4bb0fe6fdb.png)

![error_pres](https://user-images.githubusercontent.com/15084725/142932202-da93d8e3-bc60-4210-8281-aa46e11120dd.png)

I can try the other solver, but do you have any suggestion on which mesh to use it. I tried few times for other problems but it often freezes when I start the initialization. 

@mcgratta in my graph the solid line is the total pressure and the dashed line is the static pressure. I used the devices in the original input to compute the two pressures possibly without taking non-uniform flows into account

**Comment by rmcdermo** [comment]
@mpachera I misunderstood your original post.  I don't really understand the problem.  Are you concerned about total versus static pressure?

**Comment by mcgratta** [comment]
I would expect p+rho*u^2/2 to be relatively constant. Is that what you mean by "total pressure"?

**Comment by mpachera** [comment]
Yes, I calculate the total pressure along the duct as sum of the static pressure P and the kinetic pressure rho*2^2/2. I monitor the total pressure as measure of the fluid's energy to depict possible energy dissipation. If the total pressure remains constant then there are no losses. 

![image](https://user-images.githubusercontent.com/15084725/142984402-22c42192-3015-49a5-83a1-198bf8e9f18d.png)

I expected the total pressure to drop at the inlet section because of the sudden reduction of cross section. In literature I found that the pressure loss coefficient for such configuration should be 0.5, leading to a total pressure loss of about 0.3 Pa. Therefore I expected my total pressure to be around -0.3 Pa and my static pressure around -0.9 Pa.

![image](https://user-images.githubusercontent.com/15084725/142982688-6b1caa21-965c-4366-8a6d-622cf5f9bc94.png)

Above you can see a qualitative image of the detachment of the flow at the inlet creating the recirculation zones that are dissipating energy.

I expected that with a rather coarse the recirculation zone would be contained in one cell so FDS would miss the loss of energy, but refining the mesh I expected the recirculation zone to be depicted by FDS. Do you think there shouldn't be any energy loss due to the inlet?

**Comment by rmcdermo** [comment]
@mpachera If you want FDS to capture the vena contracta I think you need much higher grid resolution, something like 20 cells within each recirc zone.  And given that the vena is maybe 20% of the area, you may need something like 200 cells across the duct.  This is the reason we use HVAC for ducts: resolving these losses is very costly.  If you really must see them, you need to keep refining your grid until you actually see mean recirc zones (look at mean contours in Smokeview).  If you don't seem them, you have not resolved them.

**Comment by mpachera** [comment]
thanks @rmcdermo  for the answer, I actually wanted to use this simple setup to get an idea of the minimum number of cells I need to simulate an inlet getting the right losses. I can't often model this with the HVAC routine because I have entrances to my domain (doors, tunnel portals) which resemble this configuration.

I can try to run something more refined in a 2D like configuration as done in the validation case of the Backward_Facing_Step, can I use 20 elements as you did in your case in the Y direction?

**Comment by rmcdermo** [comment]
@mpachera in the backward step case, you will see that we do not get the recirculating zone right until we have about 16 cells across the height of the step.  The vena is similar, but harder to capture, I suspect.

I really do not think you can expect to model duct element pressure losses explicitly in a practical scenario.  But it is not clear why this would matter if you are specifying the flow rate.

Anyway, I do not see this as a bug.  I think FDS is behaving correctly.

**Comment by mpachera** [comment]
I'm not saying FDS is behaving wrong or there's a bug, just I would like understand better how to model this specific case and possibly avoid mistakes. I created other similar cases for the calculation of pressure losses and there I saw FDS is giving good predictions when compared to values from in the literature. 

In this case I set a fixed volume flow, but I created this case as it's easy to debug and I have a reference value that I can use for comparison. A practical example where I would like to see my pressure losses at the inlet is a tunnel equipped with jet fans. The longitudinal velocity is the result of the calculation and the higher the pressure losses in the tunnel the lower the velocity. If I miss my pressure loss at the inlet I possibly overestimate the longitudinal velocity. 

I created a new test case with a similar setup but a finer mesh, I placed a mirror on the symmetry plane and 2 periodic boundaries to reduce the model's size. I'll let you know when I have some results.

![image](https://user-images.githubusercontent.com/15084725/143029959-3e5ef6e3-7467-4030-b570-e4ac5f5cf06f.png)

**Comment by rmcdermo** [comment]
Hi Matteo,
Using symmetry planes is not good practice in LES.  You should no draw strong conclusions from this case.  Anyway, see what you find.  But if it is possible to know the volume flow rate, that will always be your best option.  I have to sign off now for holiday.  Good luck.

**Comment by mpachera** [comment]
Hi,

I have some preliminary results which I got from the lighter setup.

The two pictures below show the longitudinal velocity (u-vel) obtained with 2 different meshes: 
40 elements across half of the duct (80 in total)
![image](https://user-images.githubusercontent.com/15084725/143398612-1063403a-4e7d-4c8d-bb1f-e03ec484deaa.png)
80 elements across half of the duct (160 in total)
![image](https://user-images.githubusercontent.com/15084725/143398568-bec1191e-bcc2-417b-9f1b-06a88569cdcc.png)

As suggested by Randy there with more than 20 elements in the recirculation zone this is depicted by FDS and this has a visible effect on the pressure along the duct.

![image](https://user-images.githubusercontent.com/15084725/143400012-9837b88b-8e1c-41e9-9734-f3c908cd1f88.png)

I didn't expect to get the pressure loss coefficient of 0.5 which was in my mind but I know the model has some strong assumptions (mirror BC on the symmetry plane ).

Now I would like to see how to implement this finding into  practical problems:

Considering a practical problem where I have a tunnel 10 m wide, if I need around 160 elements to span the tunnel cross section then my mesh size is 0.0625 m which is way finer than what I saw around for such problem. 

One solution I will try to investigate is to place a local refined zone near to portal and keep a coarser mesh for the rest of the domain. If you are interested I can post here some results otherwise I can close the issue. 

If you have any suggestion please let me know.

Thanks as always for the support,

Matteo

**Comment by rmcdermo** [comment]
@mpachera This is one reason that folks have used hybrid CFD and 1D models for tunnels.  If you know the loss factor for an element in a 1D duct (in this case the step) then you can apply HVAC across that section for the loss.  To me, this is the only practical way.

**Comment by mpachera** [comment]
I agree with you, but from the works I saw in literature people commonly use a full 3D approach, possibly because of the issues of the previous FDS version with the coupled 1D-3D approach. To me it's good to know that this is a limitation so I can find an alternative solution.
