### ISSUE TITLE
WARNING: Maximum density, 13.444 kg/m3, clipped in mesh 1.

### ISSUE THREAD

**Issue by Jinghui88** [firemodels/fds#10066]
Dear FDS developer,

Recently, I am learning FDS and try to establish a fire model for developing my FDS skills. However, I encountered two issues when I used FDS (version 6.7.7). If I may, I would like to present the following questions: 
1. I have built a simple fire model in a compartment with a hollow layer ceiling. FDS model is shown as attachment and bellowing
[fire-model.txt](https://github.com/firemodels/fds/files/7583907/fire-model.txt)
 As a result, it returned the following warning followed by a simulation crash due to numerical instability (the maximum velocity and pressure errors in the .out file are ~10E9): WARNING: Maximum density, 13.444 kg/m3, clipped in mesh 1. (T=1780s)
![image](https://user-images.githubusercontent.com/94866419/142924145-f78e996c-21f8-4922-9f14-fe25fb7bbc0f.png)

2. I have changed the hollow layer in ceiling to another material (Rockwool), it could run well. But after the calculation, the average indoor temperature cannot fall to ambient temperature (25°C). No matter how long I set the calculation end time, the average indoor temperature is stable at 50 °C and won’t drop, as shown in bellowing figure.
![image](https://user-images.githubusercontent.com/94866419/142924122-28c9c76a-94c9-4e0a-bf5c-887569988223.png)

I haven’t found yet someone with same issues on web or any topic explaining how to solve it correctly. I can’t figure out why the fire scenarios return such a high value of gas density and average indoor temperature would not drop to ambient temperature. 

I read the FDS user guide chapter 6.7 and tried using the “&CLIP MAXIMUM_DENSITY=20.0/” as well as “&CLIP MINIMUM_DENSITY=0.001/”just to see any of these would solve with problem1, but unfortunately, no luck still.

Any suggestions would be greatly appreciated. Thanks for your time. 

Best wishes, 
Jinghui

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs. Questions on using FDS should be posted to the discussion forum: https://groups.google.com/g/fds-smv.

**Comment by mcgratta** [comment]
I told him to post it here. I'll take it.

**Comment by drjfloyd** [comment]
One issue is MATL reactions for gypsum that are making CaSO4 as a SPEC rather than as a MATL. When gypboard is heated it just gives off water vapor. The calcium is not vaporized.

**Comment by drjfloyd** [comment]
Also I think the gypsum reaction should be two consecutive and not two parallel reactions:

It should be:
gypsum -> hemi + water vapor -> anhydrite + water vapor

and not:
gypsum -> hemi + anhydrite + water vapor

**Comment by mcgratta** [comment]
Another issue is that you have the CEILING-GP sheet gasifying into water vapor and other gases at around 120 C. That fills up the void space beneath the wood ceiling leading to the high density warning.

You may need to take a big step back here. You need to understand what your pyrolysis models are doing (by running simple small-scale simulations) before building a compartment model. Otherwise, these odd results will be difficult to interpret.

**Comment by Jinghui88** [comment]
> The issue tracker is for reporting bugs. Questions on using FDS should be posted to the discussion forum: https://groups.google.com/g/fds-smv.

Thank you very much, I will do that.

**Comment by Jinghui88** [comment]
> Also I think the gypsum reaction should be two consecutive and not two parallel reactions:
> 
> It should be: gypsum -> hemi + water vapor -> anhydrite + water vapor
> 
> and not: gypsum -> hemi + anhydrite + water vapor

Thank you for your helpful suggestion. I will go back to figure out the pyrolysis reaction of gypsum and set the priority of the pyrolysis reaction. It might be the key solution to problem 1.

**Comment by Jinghui88** [comment]
> 



> Another issue is that you have the CEILING-GP sheet gasifying into water vapor and other gases at around 120 C. That fills up the void space beneath the wood ceiling leading to the high density warning.
> 
> You may need to take a big step back here. You need to understand what your pyrolysis models are doing (by running simple small-scale simulations) before building a compartment model. Otherwise, these odd results will be difficult to interpret.

Thank you for your advice. I will rebuild a small-scale model to figure out the cause of the high-density warning.
