### ISSUE TITLE
FDS 7 GEOM object ignored in solution

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#10073]
This model is a test of a GEOM object in FDS 7. The model was made by importing an ifc file and converting to a GEOM object. In the FDS solution, the GEOM object is ignored. Testing with an earlier version of FDS 7 did recognize the GEOM object.

 Fire Dynamics Simulator

 Current Date     : November 16, 2021  15:08:31
 Revision         : FDS6.7.6-877-g5759a97b4-nightly
 Revision Date    : Sun Nov 14 11:13:46 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Tue 11/16/2021  08:03 AM

The model has a fire under the roof. As shown in the results plot, the FDS solution ignores the GEOM object and the smoke flows through the roof.

[HelloRoof_fds.zip](https://github.com/firemodels/fds/files/7597510/HelloRoof_fds.zip)
[HelloRoof geom_png.zip](https://github.com/firemodels/fds/files/7597516/HelloRoof.geom_png.zip)
[HelloRoof smoke_png.zip](https://github.com/firemodels/fds/files/7597519/HelloRoof.smoke_png.zip)

**Comment by dvswenson** [comment]
![HelloRoof geom](https://user-images.githubusercontent.com/13338306/143282672-89167731-0adc-4b3c-80d5-ed9eed93c322.png)
![HelloRoof smoke](https://user-images.githubusercontent.com/13338306/143282683-d09935df-4ec8-488f-8c64-2fbb74591f3b.png)

**Comment by marcosvanella** [comment]
Thank you Dan. What is the thickness of the roof respect to the grid?

**Comment by dvswenson** [comment]
The roof thickness is 0.2 m and the mesh size is 0.2 m. I refined the mesh to 0.1 m and am running again to see if this makes a difference.

**Comment by dvswenson** [comment]
The model ran correctly when I changed the mesh size to 0.1 m
![HelloRoof_refined](https://user-images.githubusercontent.com/13338306/145243169-b8145cf9-2f09-4a3e-a07f-bb732fca4441.png)
.

**Comment by marcosvanella** [comment]
I'm, picking up a numerical instability with this case and latest code. Happens right where the roof edge touches a grid line. If I move the roof half a cell in x I see the same issue in a lower Y plane. If I move it 0.4 of a cell size in X the case runs. I'm investigating, cell blocking is working as intended (no smoke crossing trough the roof).
<img width="1336" alt="Screenshot 2023-04-13 at 11 32 20 AM" src="https://user-images.githubusercontent.com/7450069/231811050-4a42aafc-8795-4b2a-96c4-5c118605281a.png">

**Comment by marcosvanella** [comment]
Case runs correctly after PR #11722.
