### ISSUE TITLE
FDS 7 Numerical Instability for Cylinder

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#10072]
This model tests a GEOM object in FDS 7. The model was made by importing a CAD stl file (attached) and converting to GEOM. I ran this model using the following FDS version:

 Fire Dynamics Simulator

 Current Date     : November 24, 2021  10:29:19
 Revision         : FDS6.7.6-877-g5759a97b4-nightly
 Revision Date    : Sun Nov 14 11:13:46 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Tue 11/16/2021  08:03 AM

The solution stopped at 0.48 seconds with a numerical instability.
[cylinder_stl.zip](https://github.com/firemodels/fds/files/7597360/cylinder_stl.zip)
![cylinder_stl](https://user-images.githubusercontent.com/13338306/143279993-d35eab09-613a-4a02-92b5-03c76fe12ef9.png)
[cylinder_stl_fds.zip](https://github.com/firemodels/fds/files/7597379/cylinder_stl_fds.zip)

**Comment by marcosvanella** [comment]
Thank you Dan, we'll have a look.

**Comment by marcosvanella** [comment]
Working.
<img width="1201" alt="Screenshot 2023-04-12 at 4 51 22 PM" src="https://user-images.githubusercontent.com/7450069/231582252-d94178e6-eb84-4fac-bd52-da6212979099.png">
