### ISSUE TITLE
Bug in 'MASS FLUX WALL' output

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10083]
The following cases broke when I changed code logic to set `STORE_SPECIES_FLUX` automatically when the output `MASS FLUX WALL` is specified. These broken cases do not and did not specify `STORE_SPECIES_FLUX=T`, in which case the calculation of mass fluxes at the wall was done the old, less accurate way. Now the cases are run using the more accurate flux terms, but something is not quite right.
```
Matlab Warning: mass error = 0.0072207 in mass_flux_wall_yindex
Matlab Warning: mass error = 0.0072662 in mass_flux_wall_zindex
Matlab Warning: mass error = 2.4004 in mass_balance_reac for species PROPANE
Matlab Warning: mass error = 0.0025557 in mass_balance_reac for species CARBON DIOXIDE
Matlab Warning: mass error = 0.0049836 in mass_balance_reac for species SOOT
```

**Comment by rmcdermo** [comment]
This seems to be fixed with PR #10092
