### ISSUE TITLE
NaN, Infinity and negative measurements from AST devices in FDS 6.7.7

### ISSUE THREAD

**Issue by joktimo** [firemodels/fds#10101]
I have noticed that since FDS 6.7.7 Adiabatic Surface Temperature devices have started showing NaN, Infinity and negative values in DEVC results.

Here is a simple test model that demonstrates this problem:
![AST_NaN_v6_s0000](https://user-images.githubusercontent.com/91564126/144752466-4e79991a-8fea-47d8-90af-25b12fe92c79.png)
[AST_NaN_v6.txt](https://github.com/firemodels/fds/files/7656283/AST_NaN_v6.txt)
[AST_NaN_v6_devc.csv](https://github.com/firemodels/fds/files/7656284/AST_NaN_v6_devc.csv)

The model has 3200 AST devices and results show 12 NaN values, 10 Infinity values, and 11 negative temperature values. All of them are measured during early timesteps, but the locations seem quite random.

Here are some examples:
![AST_NaN_v6_devc](https://user-images.githubusercontent.com/91564126/144753209-1b55e2c3-5fb3-417c-9533-277553e7d69c.png)

There is likely some interaction with the surface since all the incorrect measurements are from devices that lie on a defined steel surface. Devices on INERT surface work correctly.

This problem has not existed in previous FDS versions.

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I do not get the NaNs with the latest source code. Are you using the Intel Fortran compiler with an Intel CPU, or something different?

**Comment by joktimo** [comment]
This was run using official FDS6.7.7-0 build with Intel MPI Library 2021.4 and with Intel CPU. But I also tried running it with an AMD system and with two other Intel systems and all of them resulted in similar NaN measurements.

I also tried the latest nightly build FDS6.7.7-143 and the problem still exists for me.

**Comment by mcgratta** [comment]
I will run it again with this
```
 Fire Dynamics Simulator

 Current Date     : December  7, 2021  08:55:45
 Revision         : FDS6.7.7-145-g0470bfdcd-master
 Revision Date    : Mon Dec 6 15:13:45 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Dec 07, 2021 08:44:41

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.4 for Linux* OS
```

Can you also try running the debug version (impi_intel_linux_64_db). If there is an NaN, the debug version should stop and give you a line number in the .err file. I tried this too but did not get a fault.

**Comment by mcgratta** [comment]
I checked the code. Here is where we compute AST:
```
   CASE(23) ! ADIABATIC SURFACE TEMPERATURE
      LTMP = 0._EB
      ATMP = 0._EB
      CTMP = 0._EB
      IF (PRESENT(OPT_WALL_INDEX) .OR. PRESENT(OPT_CFACE_INDEX)) THEN
         DO NN = 1,N_LAGRANGIAN_CLASSES
            LPC => LAGRANGIAN_PARTICLE_CLASS(NN)
            IF (LPC%LIQUID_DROPLET) THEN
               CTMP = CTMP + BP%LP_CPUA(LPC%ARRAY_INDEX)
               ATMP = ATMP + ABS(BP%LP_CPUA(LPC%ARRAY_INDEX))
               LTMP = LTMP + ABS(BP%LP_CPUA(LPC%ARRAY_INDEX))*BP%LP_TEMP(LPC%ARRAY_INDEX)
            ENDIF
         ENDDO
      ENDIF
      LTMP = LTMP / (ATMP + TWO_EPSILON_EB)
      H_W_EFF = CTMP / (ONE_D%TMP_F-LTMP+TWO_EPSILON_EB)
      H_W_EFF = MIN(10000._EB,MAX(0._EB,H_W_EFF));
      IF (ONE_D%HEAT_TRANS_COEF>0._EB) THEN
         AAA = ONE_D%EMISSIVITY*SIGMA
         BBB = ONE_D%HEAT_TRANS_COEF + H_W_EFF
         CCC = -ONE_D%Q_RAD_IN - ONE_D%HEAT_TRANS_COEF*TMP(BC%IIG,BC%JJG,BC%KKG) - H_W_EFF*LTMP
         ALP = (SR3*SQRT(MAX(0._EB,27._EB*AAA**2*BBB**4-256._EB*AAA**3*CCC**3))+9._EB*AAA*BBB**2)**ONTH
         BET = FTTOT*CCC
         GAM = EIONTH*AAA
         MMM = SQRT(BET/ALP + ALP/GAM)
         SOLID_PHASE_OUTPUT = 0.5_EB*(-MMM+SQRT(MAX(0._EB,2._EB*BBB/(AAA*MMM)-MMM**2))) - TMPM
      ELSE
         SOLID_PHASE_OUTPUT = (ONE_D%Q_RAD_IN/(ONE_D%EMISSIVITY*SIGMA))**0.25 - TMPM
      ENDIF
```
Notice that when dividing we add a small number to the denominator, and when taking square roots we ensure no negative arguments. I can't see where an NaN would come from. That is why it is important to run in debug mode and see if you can trap it. Thanks.

**Comment by mcgratta** [comment]
Ah -- I just got an NaN. Now I have something to hunt for.

**Comment by mcgratta** [comment]
The NaNs appear when I compile in release mode, with full optimization, or even with partial optimization. These types of errors are often related to floating point precision. For fully optimized code, there are time-saving shortcuts that are taken to increase speed. I'll see if I can find where the NaN actually appears.

**Comment by mcgratta** [comment]
This appears to involve the compiler option `-fltconsistency`. Its default value is F, and we only invoke it in debug mode. When I ran optimized code with this flag, the NaNs do not appear.

**Comment by mcgratta** [comment]
I found a few more holes in the computation of AST. One divide by zero and one square root of a tiny negative number. The AST calc is an analytical solution of a fourth order polynomial, so any inexact arithmetic can lead to a numerical error. Up to now, our debug compilation used the option `-fltconsistency` but our release did not. So we did not trap this error when doing our nightly build tests. From now on we will not use the `-fltconsistency` option so that our debug and release versions use the same floating point arithmetic.

Try your case with the latest source. Also, I nominated you for the coveted Boris Stock award for this and your other bug report.

[Boris Award](https://github.com/firemodels/fds/wiki/Boris-Stock-Award-Recipients)

**Comment by joktimo** [comment]
I tried running this case and my other test models with the latest source and did not encounter any NaN or Inf values.

So thanks for the fix, and thanks for the nomination!

**Comment by mcgratta** [comment]
Glad it worked.

**Comment by joktimo** [comment]
I may have been a bit too hasty.

I checked the results for NaN, Inf and negative values, but when I looked the actual numerical values there are still a lot measurements that don't make sense. Actually much more incorrect measurements than before. This time though they are unrealistically high. But all of them still exists during the same time points.

[AST_NaN_v6_devc.csv](https://github.com/firemodels/fds/files/7671725/AST_NaN_v6_devc.csv)

This figure shows 255 first devices from FDS 6.7.7-0 official release:
![AST_NaN_v6-0](https://user-images.githubusercontent.com/91564126/145109702-7f00adee-0ba4-476b-bc48-156ddf504dc9.png)

And this figure shows the same thing with the latest source:
![AST_NaN_v6-1](https://user-images.githubusercontent.com/91564126/145109760-d9f33f5c-2903-4906-852f-6c10d1b2d4bf.png)

So perhaps NaN values were just a symptom from something else?

**Comment by mcgratta** [comment]
Wow, you really want that award ;)

Are these values supposed to be 20 C at the start of the simulation? I wonder if this is a zero divided by zero problem.

**Comment by joktimo** [comment]
:D

Yes everything should start as 20 °C and remain as 20 °C.

I tried to see more clearly what happens early in the simulation so I reduced DT to 0.001, and the incorrect measurements are still found strictly during time steps 2 and 3 (if 0s is time step 0) only. 

![AST_NaN_v6-1s](https://user-images.githubusercontent.com/91564126/145114818-325cfeaf-dad4-4d61-95bb-53b9cb005a9e.png)

In previous simulations they were as well found during time steps 2 and 3 but at time points 0.15-0.35 s.

Bizarre.

**Comment by drjfloyd** [comment]
It looks like you are using the quartic function to explicitly solve the 4th order polynomial.  The wiki page for that mentions some special cases and how one should select the correct root. Are these points spots where we hit one of those cases?

https://en.wikipedia.org/wiki/Quartic_function#Special_cases_of_the_formula

**Comment by drjfloyd** [comment]
Should this line:
IF (ONE_D%HEAT_TRANS_COEF>0._EB) THEN

be:
IF (ONE_D%HEAT_TRANS_COEF+H_W_EFF>0._EB) THEN

**Comment by mcgratta** [comment]
Maybe, but in this case, H_W_EFF=0.

>

**Comment by mcgratta** [comment]
I've whittled the case down to this
```
&HEAD CHID='AST'/
&TIME T_END=1.0/

&MESH IJK=100,50,10, XB=-5.0,5.0,-2.5,2.5,0.0,1.0/

&DEVC ID='AST_STEEL_06', QUANTITY='ADIABATIC SURFACE TEMPERATURE', XYZ=-4.45,-1.45,0.5, IOR=3/

&MATL ID='steel',
      SPECIFIC_HEAT=1,
      CONDUCTIVITY=50,
      DENSITY=7850.0,
      EMISSIVITY=0.7/

&SURF ID='Steel_3mm',
      HEAT_TRANSFER_COEFFICIENT=35.0,
      EMISSIVITY=0.7,
      MATL_ID='steel',
      THICKNESS(1)=3.0E-3/

&OBST ID='STEEL', XB=-4.5,-0.5,-2.0,2.0,0.4,0.5, SURF_ID='Steel_3mm'/

&TAIL /
```

**Comment by joktimo** [comment]
I ran the simpilified case. Here are the results:
```
s,C
Time,"AST_STEEL_06"
 0.0000000E+000, 1.9989277E+001
 1.5811388E-001, 1.9999574E+001
 3.1622777E-001, 3.2120980E+004
 4.7434165E-001, 3.2120980E+004
 6.3245553E-001, 1.9999986E+001
 7.9056942E-001, 1.9999988E+001
 9.4868330E-001, 2.0000001E+001
 1.0000000E+000, 2.0000002E+001
```

[AST.zip](https://github.com/firemodels/fds/files/7676896/AST.zip)

**Comment by mcgratta** [comment]
Yes, that case was a smaller test case to more easily debug the case. Re-compile with my latest commit. I think I went too far by adding these `TWO_EPSILONs` (very small numbers to some denominators).

**Comment by joktimo** [comment]
I recompiled and ran my original model (since it has a lot more devices). 

There are still some incorrect measurements, but it works much better than yesterday. The amplitudes for the incorrect temperatures are lower and they are found less frequently. Now 164 devices out of 1600 had temperature measurements above 21°C or below 19 °C; yesterday this was 776 out of 1600.

No NaN or Inf values were found.

Here are the results: 
![AST_NaN_v6-3](https://user-images.githubusercontent.com/91564126/145283570-1fd5352e-862a-4271-bdbb-cec653c47510.png)
[AST_NaN_v6_devc.csv](https://github.com/firemodels/fds/files/7678870/AST_NaN_v6_devc.csv)

**Comment by mcgratta** [comment]
What is the maximum error?

>

**Comment by joktimo** [comment]
Maximum value is 5982 °C and minimum -173 °C. Yesterday it was max: 58106 °C  min: 19.98 °C.

But I also noticed that the error has correlation with the size of the time step. With DT=0.001s almost all devices produced incorrect values, and with DT=1s only about 20 devices produced incorrect values.
[AST_NaN_v6_devc,DT=0.001.csv](https://github.com/firemodels/fds/files/7679108/AST_NaN_v6_devc.DT.0.001.csv)
[AST_NaN_v6_devc,DT=1.csv](https://github.com/firemodels/fds/files/7679111/AST_NaN_v6_devc.DT.1.csv)

**Comment by mcgratta** [comment]
OK, let me carve out some more time tomorrow to look more closely at this.

>

**Comment by drjfloyd** [comment]
It looks like this is happening because ONE_D%EMISSIVITY * SIGMA * TMP(BC%IIG,BC%JJG,BC%KKG) ~ ONE_D%Q_RAD_IN. At that point it may be that precision errors cause the exact solution to blow up.  In this case we don't need to do the solution, we know if the incoming radiative flux is the same as the incident flux based on the gas temperature that the AST should just be the gas temperature.  We could just have after the CASE statement like:

IF (ONE_D%Q_RAD_IN-ONE_D%EMISSIVITY * SIGMA * TMP(BC%IIG,BC%JJG,BC%KKG) < some small number) THEN
   SOLID_PHASE_OUTPUT = TMP(BC%IIG,BC%JJG,BC%KKG)  - TMPM
   RETURN
ENDIF

**Comment by mcgratta** [comment]
I implement Jason's suggestion and things appear to work nicely. Note that much of the code change in the last commit is designed to reduce work in calculating the effect of liquid evaporation on the surface.

**Comment by joktimo** [comment]
Great!

I recompiled and most of my test models now produced only valid measurements (including AST_NaN_v6.fds), but I have one earlier model with a bit more complex geometry and with 5664 devices. About 3% of its devices still produced measurements outside 18-22 °C range.
![AST_NaN-Inf_v1_s0001](https://user-images.githubusercontent.com/91564126/145484578-40037426-3b11-4b80-96f2-b77070ceee05.png)
[AST_NaN-Inf_v1.txt](https://github.com/firemodels/fds/files/7688829/AST_NaN-Inf_v1.txt)
[AST_NaN-Inf_v1_devc.csv](https://github.com/firemodels/fds/files/7688857/AST_NaN-Inf_v1_devc.csv)

Here are min and max measurements from each device from AST_NaN-Inf_v1.fds:
![AST_NaN-Inf_v1-1](https://user-images.githubusercontent.com/91564126/145486439-030db5fb-f403-4caa-9a56-f7e733417df1.png)

**Comment by drjfloyd** [comment]
We may need to slightly increase the screening value. I'll take a look.

**Comment by drjfloyd** [comment]
slightly different formulation for the T_AST solution and a check for a very small heat transfer coefficient (if h is near zero just return the radiation temperature).

Plot shows the minimum temperature sorted from lowest to highest. About 2 % are off more than 2 degrees but none are more than 4 degrees. The temperature anomalies go away after a couple of timesteps.

![image](https://user-images.githubusercontent.com/12799217/145500171-223861cb-613d-4f54-85d0-30e3feabaee8.png)

**Comment by mcgratta** [comment]
I would rather test different tolerance values (0.005 +) rather than change
the method. The current method in FDS is based on a paper in Fire Tech that
specifically addressed the heat flux equation as opposed to just a general
4th order polynomial.

>

**Comment by drjfloyd** [comment]
The issue reappeared multiple orders of magnitude above the 0.005 tolerance. The method in FDS is some variant of Ferrari's method. The formulation I put in avoids the need to add TWO_EPSILON_EB to anything.

**Comment by drjfloyd** [comment]
The Fire Tech paper is just someone typing in the AST 4th order polynomial into Wolfram Alpha and taking whatever WA outputs.  WA is basically Mathematica with some natural language processing for people who don't know the Mathematica syntax. I am sure Mathematica just has some rule in it that if someone types in a 4th order poly to invoke one of the solution methods. Then Mathematica will run its simplify logic on the result which does not always return the best formulation. I just went straight to a solution method and dropped terms that were zero because they involved the coefficients for x^3 or x^2.

**Comment by mcgratta** [comment]
There's only one term with TWO_EPS because of the possibility that MMM
might be zero

MMM = SQRT(MAX(0._EB,BET/ALP + ALP/GAM))

Why not just add an if statement here similar to what you are doing with
RRR? I'm sure it's basically the same issue.

**Comment by drjfloyd** [comment]
The IF I have for RRR is explicit in Ferrari's method.  I can't do the same for the Fire Tech Paper output from Wolfram Alpha, what would I replace BET/ALP+ALP/GAM with when it is zero?

**Comment by drjfloyd** [comment]
Reverted method change and kept the added check on h. Seems to be working OK.

**Comment by mcgratta** [comment]
Good -- I like that paper because it provides a nice explanation of finding
the right root of the 4th order polynomial.

OK, Timo -- try and break it.

>

**Comment by joktimo** [comment]
I recompiled and in most of my test models the temperatures remained between 19.98 and 20.00.

There is still something going on with [AST_NaN-Inf_v1.fds](https://github.com/firemodels/fds/files/7688829/AST_NaN-Inf_v1.txt) where the minimum temperature was approx 16.5 °C. But those values were recorded on step 0 and by the step 4  ~20 °C was reached.

![AST_NaN-Inf_v1-1](https://user-images.githubusercontent.com/91564126/145631748-4f1280d9-f7e3-4f58-85b0-35556b62f8da.png)
![AST_NaN-Inf_v1-2](https://user-images.githubusercontent.com/91564126/145632656-f4618973-d80d-4521-9ab0-4541cdd47658.png)
[AST_NaN-Inf_v1_devc.csv](https://github.com/firemodels/fds/files/7695066/AST_NaN-Inf_v1_devc.csv)

So I'm willing to call this a success!

Perhaps I should at some point also test this with actual fire simulations and compare to previous results.

**Comment by mcgratta** [comment]
Yes, I think this is success. I would hope that for non-trivial conditions
the AST should work properly. I did not realize that the most difficult
regime for the solution is ambient conditions. We never tested it here.

>

**Comment by drjfloyd** [comment]
At the start there are slight errors (~mK) in the temperature of the incident radiation. The values for h, when it isn't fixed on the SURF, are also very small since there is no flow. In the exact solution approach we are taking powers and roots of combinations of the coefficients for the 4th order polynomial for the AST where those combinations get very close to zero. I think we are just seeing effects of the fact that numbers in a computer have a limited precision. We could probably get some improvement by increasing the values where we just use the temperature of the incident radiation, but at some point that will start to effect AST cases we care about.

**Comment by mcgratta** [comment]
I think we should leave it for now. If this pops up again, we'll have a better idea of what to do.
