### ISSUE TITLE
Velocities computed beneath terrain

### ISSUE THREAD

**Issue by asbova17** [firemodels/fds#10117]
Wind speeds are being computed below a 2D sloped terrain from a file generated by Qgis2FDS.  It appears that the cells below the terrain are not being treated as solid. I'm don't know if this is an issue with the terrain file or if I'm missing a parameter in the input file or if it's something else. I've uploaded a stripped-down version of the input file and the bingeom file. The velocity slice limits and vector lengths will need to be adjusted for visualization in Smokeview -- there are spurious high velocities that skew the scale.

Thanks for your help!

<img width="1639" alt="Screen Shot 2021-12-10 at 9 12 46 AM" src="https://user-images.githubusercontent.com/60200922/145614446-97643c70-477e-4fb1-aa60-bfc48c6747a9.png">
[Archive.zip](https://github.com/firemodels/fds/files/7694406/Archive.zip)

**Comment by marcosvanella** [comment]
Thank you Tony. We'll have a look.

**Comment by asbova17** [comment]
Hello! No pressure (and no pun intended), but are there any developments on this issue? Cheers!

**Comment by rmcdermo** [comment]
No, for the time being we need to use OBST for terrain.  LEVEL SET now works with OBST.  This will have to be the direction until we sort out the stability issues with GEOM.

**Comment by rmcdermo** [comment]
Note that the latest [qgis2fds](https://github.com/firetools/qgis2fds) outputs OBST.  Give that a try and let me know if you have a problem getting to it.  I can get on a call and walk you through it.

**Comment by asbova17** [comment]
Ok - I'll give the latest qgis2fds a try. Thank you both!

**Comment by rmcdermo** [comment]
Be on the look out for a checkbox that will force the export of OBST instead of GEOM lines.  Don't hesitate to email me to help if you have any problem.

**Comment by gforney** [comment]
fyi: coincidently I"ve been working with kevin to improve terrain visualization for a case he is working on with terrain built with OBSTs .  remove unwanted holes in terrain (smokeview side effect of having multiple layers of meshes), make agl slice distance accurate, reduce depth buffer thrashing  (allow slice to be closer to terrain without visual artifacts).  haven't looked at terrain vector slices yet.  new smokeview should be in tomorrows nightly build.  or you can build it yourself it after updating smv repo .  this is a work in progress so if you do try it, let me know if you see any problems

**Comment by marcosvanella** [comment]
Hi Tony, we've been putting a lot of effort into this. There are issues with the way we update the solution close to the geometry, stemming from a change we made default back last summer. For the time being use the OBST terrain feature from qgis2fds, and we'll let you know when the geometry terrain algorithm can be exercised.

**Comment by rmcdermo** [comment]
Is there an input file for this case?  I'd like to run it with the latest code to see the status.  Thanks

**Comment by marcosvanella** [comment]
In Blaze:
/home2/smokevis2/mnv/Firemodels_fork/fds/Bova/Archive.zip

Thanks

**Comment by marcosvanella** [comment]
Velocities under geometry are not computed under unstructured projection, face values are zero. They are set to zero. some of the nonzero vectors seen in the following pic are related to node interpolation.
<img width="1000" alt="Screenshot 2023-04-20 at 2 51 55 PM" src="https://user-images.githubusercontent.com/7450069/233461088-42794d6c-3230-44a4-ad34-8e084622579b.png">
