### ISSUE TITLE
Array bounds error for BOUNDARY_ONE_D

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#10112]
The attached case is based on the water ice verification case. It it is a closed hot box with an ice cube in it. The MATL uses PART_ID to produce water drops as it melts. The case runs up until it tries to access element 1001 of BOUNDARY_ONE_D which gives an array bounds error. 

[water_ice_water.txt](https://github.com/firemodels/fds/files/7688377/water_ice_water.txt)

**Comment by mcgratta** [comment]
Are you running in debug mode? I didn't get the error in dv mode.

>

**Comment by drjfloyd** [comment]
Yes in debug

**Comment by drjfloyd** [comment]
I got distracted for a few minutes between typing the issue and committing the source so possible you didn't grab the udpate.

**Comment by mcgratta** [comment]
OK, just got it.

>

**Comment by mcgratta** [comment]
Optimized build didn't catch it.

>

**Comment by mcgratta** [comment]
Should be fixed. With the new boundary stuff, we have to be careful when calling `ALLOCATE_STORAGE` because if it is here that the `MESHES(NM)%BOUNDARY_XXXX` arrays are sometimes reallocated. If they are (as in this case), the pointer, say, `BOUNDARY_ONE_D`, must be reset.

**Comment by drjfloyd** [comment]
Thanks.
