### ISSUE TITLE
Corner wall

### ISSUE THREAD

**Issue by Flo-23** [firemodels/fds#10111]
Hi, 
How Can i make a corner wall with FDS 😅
![IMG_20211209_212103](https://user-images.githubusercontent.com/66320084/145469824-6b9326e8-ed8e-4c36-9d90-1309d32bed50.jpg)

Best regard

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs or requesting new features. General questions on using FDS should be posted to the discussion forum (https://groups.google.com/g/fds-smv). Before posting questions please take the time to read the FDS documentation and study the many examples provided when FDS is installed.
