### ISSUE TITLE
Floating overflow in WALE

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10136]
```
 Job TITLE        : HVAC mass transport convergence
 Job ID string    : HVAC_mass_transport_conv_0020

 Time Step:      1, Simulation Time:      0.03 s
 Time Step:      2, Simulation Time:      0.05 s
 Time Step:      3, Simulation Time:      0.08 s
 Time Step:      4, Simulation Time:      0.10 s
 Time Step:      5, Simulation Time:      0.12 s
 Time Step:      6, Simulation Time:      0.15 s
 Time Step:      7, Simulation Time:      0.17 s
forrtl: error (72): floating overflow
Image              PC                Routine            Line        Source
fds_impi_intel_li  000000000C20659B  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B1944DBE630  Unknown               Unknown  Unknown
fds_impi_intel_li  00000000007F66EF  turbulence_mp_wal        1160  turb.f90
fds_impi_intel_li  0000000002ABD071  velo_mp_compute_v         396  velo.f90
fds_impi_intel_li  0000000003DE48E0  MAIN__                    553  main.f90
fds_impi_intel_li  000000000040B822  Unknown               Unknown  Unknown
libc-2.17.so       00002B194759F555  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  000000000040B729  Unknown               Unknown  Unknown
srun: error: burn028: task 0: Aborted (core dumped)
srun: Terminating job step 208811.0
```

**Comment by mcgratta** [comment]
Also, my latest run of the verification cases show
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mcgratta/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mcgratta/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



130 | HVAC | fan_test | end | vflow1 | -0.049825 | vflow1 | -0.048088 | Volume Flow (mÂ³/s) | Relative Error | 3.49E-02 | 2.00E-02 | Out of Tolerance | FDS_Verification_Guide/SCRIPT_FIGURES/fan_test_Volume_Flow
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
130 | HVAC | fan_test | end | vflow2 | 0.049825 | vflow2 | 0.048083 | Volume Flow (mÂ³/s) | Relative Error | 3.50E-02 | 2.00E-02 | Out of Tolerance | FDS_Verification_Guide/SCRIPT_FIGURES/fan_test_Volume_Flow



</body>

</html>

**Comment by rmcdermo** [comment]
This is related to the changes to use a high value of NU at the HVAC surf.  I reverted this change.  I'm closing this issue, as the original issue suffices to work this case.
