### ISSUE TITLE
Output file CHID_devc_ctrl_log.csv written out too often

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10157]
Could the logic for creating the device-control log file be tightened so that it only is created when there are devices or controls that can change state.

```
IF (N_DEVC > 0 .OR. N_CTRL > 0) THEN
   LU_DEVC_CTRL = GET_FILE_NUMBER()
   FN_DEVC_CTRL = TRIM(CHID)//'_devc_ctrl_log.csv'
ENDIF
```

**Comment by drjfloyd** [comment]
Yes, we could set a flag during input processing that is true if a DEVC has a SETPOINT given, a logical CTRL is used, or a math CTRL has SETPOINT given.

**Comment by drjfloyd** [comment]
done

**Comment by mcgratta** [comment]
Great, thanks.
