### ISSUE TITLE
No HRR or RHRR in .out

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#10178]
The .out file no longer writes the HRR or RHRR.  Here is the .out from couch.fds using the current source:

       Time Step      50   December 28, 2021  12:00:43
       Step Size:    0.659E-01 s, Total Time:       4.15 s
       Pressure Iterations: 1
       Maximum Velocity Error:  0.12E-01 on Mesh 1 at (16,8,11)
       Maximum Pressure Error:  0.82E+00 on Mesh 1 at (15,8,15)
       ---------------------------------------------------------------
       Max CFL number:  0.80E+00 at (15,8,13)
       Max divergence:  0.48E+00 at (16,8,7)
       Min divergence: -0.11E+00 at (15,8,14)
       Max VN number:   0.36E+00 at (15,8,21)
       No. of Lagrangian Particles:  3
 
       Time Step      60   December 28, 2021  12:00:43

**Comment by mcgratta** [comment]
OK, this is trickier than I thought.
