### ISSUE TITLE
fds2ascii failure for large file count

### ISSUE THREAD

**Issue by BTemp1282020** [firemodels/fds#10196]
Hello,

I encountered an error when using the fds2ascii utility when dealing with 120 processors and 180 written time-steps.  The existing code returns 0 files despite the presence of over 21000 valid output files.

Upon investigating, there is one simple code issue and one "odd-ball" issue.

Resolution:
The simple issue is easily resolved by setting "FILE_DIM" to >100000 (near line 27)
The more troublesome issue (the seemingly random introduction of leading white-space when large numbers of files are present) is resolved by:
adding "PL3D_FILE(I)=TRIM(ADJUSTL(PL3D_FILE(I)))" after "READ(11,'(A)') PL3D_FILE(I)" near line 288
then, for the sake of readability, modifying the display line to "write(6,'(I6,3X,A,A,I4,A,F5.0)') [...]"

Those changes resolved the error on my system.

If you could please incorporate those changes into the repo so that others will not have this issue, it would be appreciated.

**Comment by mcgratta** [comment]
Can you submit a pull request?

**Comment by BTemp1282020** [comment]
I have no experience with using the developer side of github, unfortunately.  Is it an involved process?

**Comment by mcgratta** [comment]
Depends. How did you get the fds2ascii files? Did you clone the fds
repository?

**Comment by gforney** [comment]
Can you upload 2 source files. 1. Original file before you made the change. 2. Modified file. We can look at incorporating it into the repo.

**Comment by BTemp1282020** [comment]
I had downloaded a copy rather than doing a clone operation.

The original and modified files are attached (txt extension added to facilitate upload).  The modified file also includes a call to print the iomesg when the file is not found, but I am not sure if that is something you want to keep.
[fds2ascii.f90.txt](https://github.com/firemodels/fds/files/7822242/fds2ascii.f90.txt)
[fds2ascii.f90.orig.txt](https://github.com/firemodels/fds/files/7822243/fds2ascii.f90.orig.txt)
.

**Comment by mcgratta** [comment]
I incorporated your comments and did some general clean-up. Please check that the new version works. Thanks.

**Comment by BTemp1282020** [comment]
I can confirm that it runs correctly for pl3d on 21600 files.  Thanks for making the changes.  And thanks for removing the batch commands since they didn't work anyway (unfortunately).
