### ISSUE TITLE
3D slices of scalars in a terrain simulation cause a segmentation fault in Smokeview

### ISSUE THREAD

**Issue by asbova17** [firemodels/fds#10210]
Hello-
In a terrain simulation (see attached zip), a 3D slice file of velocity works correctly in Smokeview, but a 3D slice of soot concentration or pressure causes a segmentation fault. All 3D scalar slices work if the same simulation is run without terrain, however.

I'm not sure if the problem is in FDS or Smokeview (or both). I'm using one of the newer daily builds (FDS6.7.7-413_SMV6.7.18-189) on a Mac Pro desktop, but this happens in earlier versions of FDS and Smokeview, too. 

The attached file has 10 meshes but is coarse and runs quickly. The terrain and image files should be in the same directory as the input file. 

Thanks!

[Archive.zip](https://github.com/firemodels/fds/files/7841109/Archive.zip)

**Comment by gforney** [comment]
I'll take a look.

**Comment by gforney** [comment]
can you send me the &SLCF line for the velocity that is working for you

**Comment by asbova17** [comment]
This worked: 
&SLCF XB=-4175.0,825.0,-2800.0,2200.0,780.0,4780.0, QUANTITY='VELOCITY', VECTOR=T/

**Comment by gforney** [comment]
try adding VECTOR=T to your &SLCF line . this should cause fds to output the slice file as a structured slice file instead of a geometry slice file.  unfortunately 3D geometry slices are not implemented in FDS or smokeview now.

**Comment by asbova17** [comment]
That works. Thanks Glenn!
