### ISSUE TITLE
Issue with PATH OBSCURATION on multi meshes

### ISSUE THREAD

**Issue by kriboe90** [firemodels/fds#10225]
Hi everyone,

I am running into an issue when calculating PATH OBSCURATION with line DEVC crossing multiple meshes. 
When the x or y position of the endpoint of a line DEVC is lower than the start point and the line DEVC crosses multiple meshes, the result of PATH OBSCURATION is different to a single mesh simulation. Crossing X = 0 / Y = 0  or not also seems to make a difference.

I have summarized the issue in a simple example.

I have set a constant smoke density within the domain, similar to the beam detector validation case.

Delta X / Y / Z corresponds to the position of the end point in relation to the start point of the line DEVC.

![Path_obscuration](https://user-images.githubusercontent.com/73885850/149128439-61bc5753-ce78-4273-b8cb-3491572feca2.jpg)

Calculating the TRANSMISSION for line DEVC with the same coordinates works as expected. Therefore, it seems to me that the distance measurement is wrong for Multi Meshes.

![Transmission](https://user-images.githubusercontent.com/73885850/149128461-550dd10a-ab2a-415f-8ed1-b3a86ebf43f3.jpg)

I am running FDS with the following configuration:

 Current Date     : January 12, 2022  09:25:27
 Revision         : FDS6.7.7-0-gfe0d4ef38-release
 Revision Date    : Thu Nov 18 17:10:22 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Nov 19, 2021  08:14:42

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

Those are the cases I ran:

[issue_01_single_x_positive.fds.txt](https://github.com/firemodels/fds/files/7853861/issue_01_single_x_positive.fds.txt)

[issue_01_single_x_negative.fds.txt](https://github.com/firemodels/fds/files/7853872/issue_01_single_x_negative.fds.txt)

[issue_01_multi_x_positive.fds.txt](https://github.com/firemodels/fds/files/7853851/issue_01_multi_x_positive.fds.txt)

[issue_01_multi_x_negative.fds.txt](https://github.com/firemodels/fds/files/7853852/issue_01_multi_x_negative.fds.txt)

Thank you very much in advance!

Greetings,

Kristian

**Comment by drjfloyd** [comment]
Something is wrong in setting up  the subdevices. I put in debug to write SDV%MESH, SDV%N_PATH and SDV%I/J/K_PATH in read.f90.  For the issue_01_multi_x_negative case the first device is only writing path data for mesh 2 even though this device goes through four meshes.

**Comment by drjfloyd** [comment]
It may be this line at 12005.  This is before we check for meshes and in this case the XB is not ordered as expected for using XF and XS. 
         IF (QUANTITY/='PATH OBSCURATION' .AND. QUANTITY/='TRANSMISSION') CALL CHECK_XB(XB)

**Comment by mcgratta** [comment]
OK, this is a bit tricky. I'll take a look.

**Comment by mcgratta** [comment]
I'm not sure why `PATH OBSCURATION` and `TRANSMISSION` were singled out. In any case, removing the special treatment seems to solve the issue. As a work-around until the next release, make sure your Delta's are positive. In the next release, FDS would make the necessary adjustment.

**Comment by drjfloyd** [comment]
PATH OBSCURATION and TRANSMISSION both use line from (x1,y1,z1) to (x2,y2,z2).  If z2 is less than z1, CHECK_XB will flip z1 and z2.  It looks like CHECK_XB is done before we assign XB to device variable which means this would change the path to be a line from (x1,y1,z2) to (x2,y2,z1) which would not be the same.

**Comment by mcgratta** [comment]
OK, maybe this was why we singled these quantities out. Let me think some more.

**Comment by drjfloyd** [comment]
We could define XB_TEMP = XB, then CALL CHECK_XB(XB), and then after doing the check for being in the mesh if it is one of those two quantities set XB = XB_TEMP.

**Comment by mcgratta** [comment]
This is ugly, but I think it works.
```
            IF (XB(1)==XB(2) .AND. (XB(1)> M%XF .OR. XB(2)< M%XS)) OVERLAPPING_X = .FALSE.
            IF (XB(1)/=XB(2) .AND. ((XB(1)>=M%XF.AND.XB(2)>=M%XF) .OR. (XB(1)<=M%XS.AND.XB(2)<=M%XS))) OVERLAPPING_X = .FALSE.
            IF (XB(3)==XB(4) .AND. (XB(3)> M%YF .OR. XB(4)< M%YS)) OVERLAPPING_Y = .FALSE.
            IF (XB(3)/=XB(4) .AND. ((XB(3)>=M%YF.AND.XB(4)>=M%YF) .OR. (XB(3)<=M%YS.AND.XB(4)<=M%YS))) OVERLAPPING_Y = .FALSE.
            IF (XB(5)==XB(6) .AND. (XB(5)> M%ZF .OR. XB(6)< M%ZS)) OVERLAPPING_Z = .FALSE.
            IF (XB(5)/=XB(6) .AND. ((XB(5)>=M%ZF.AND.XB(6)>=M%ZF) .OR. (XB(5)<=M%ZS.AND.XB(6)<=M%ZS))) OVERLAPPING_Z = .FALSE.
```

**Comment by kriboe90** [comment]
Thank you for resolving the issue!
As a workaround I calculated the distances by myself and determined `PATH OBSCURATION` from `TRANSMISSION` via post processing.

**Comment by mcgratta** [comment]
Great, thanks for reporting this problem.

**Comment by gjaeger** [comment]
> Great, thanks for reporting this problem.

@mcgratta A new nominee for the [Boris Stock Award](https://github.com/firemodels/fds/wiki/Boris-Stock-Award-Recipients) 2022? ;-)

**Comment by mcgratta** [comment]
Will do. Good suggestion. That means we need to choose the 2021 winner.
