### ISSUE TITLE
Temperature inside the solid wall?

### ISSUE THREAD

**Issue by RNstu08** [firemodels/fds#10247]
Hello Everyone,

I would like to know how the temperature is transmitted through a wall and how we measure the temperature inside the wall.

We have a case where two rooms are separated by a wall (COMBUSTIBLE) and have only one common door without any windows or mechanical ventilation. The fire started in room 1, and we would like to understand its effects on the other part of the room. We are interested in measuring the temperature inside the wall and the surface temperature as well.

I had used different measuring techniques that are available on FDS, such as 
                                                                                1. Wall temperature
                                                                                2. Inside wall temperature
                                                                                3. Adiabatic surface temperature
                                                                                4. Thermocouples

Only the adiabatic surface temperature shows some deflection for IOR = 2 on the graph, while the other devices didn't work at all.

I would be happy if someone shed light on these topics. If required, I will share the FDS input file.

Thank you everyone in advance.

**Comment by rmcdermo** [comment]
This question should be posted to the [discussion forum](https://groups.google.com/g/fds-smv)
