### ISSUE TITLE
HT3D OBST causes seg fault

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10251]
[pyro_L1_28839.fds.txt](https://github.com/firemodels/fds/files/7914654/pyro_L1_28839.fds.txt)
This case fails at 200 s when an HT3D OBST is created. The failure is due to a divide by zero at several locations along mesh boundaries. The divide by zero occurs in wall.f90
```
         ! face value of temperature
         IF (ATMOSPHERIC_INTERPOLATION) THEN
            ONE_D%TMP_F = (TMP(II,JJ,KK)*DZ(KKG) + TMP(IIG,JJG,KKG)*DZ(KK)) / (DZ(KK)+DZ(KKG))
            ONE_D%ZZ_F(1:N_TOTAL_SCALARS) = (ZZP(II,JJ,KK,1:N_TOTAL_SCALARS)*DZ(KKG) + ZZP(IIG,JJG,KKG,1:N_TOTAL_SCALARS)*DZ(KK)) &
                                          / (DZ(KK)+DZ(KKG))
            ZZ_GET(1:N_TRACKED_SPECIES) = ONE_D%ZZ_F(1:N_TRACKED_SPECIES)
            CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_GET,RSUM_F)
            ONE_D%RHO_F = PBAR_F/(RSUM_F*ONE_D%TMP_F)
         ELSE
            ONE_D%ZZ_F(1:N_TOTAL_SCALARS) = MAX(0._EB,MIN(1._EB,RHO_ZZ_F(1:N_TOTAL_SCALARS)/ONE_D%RHO_F))
            ZZ_GET(1:N_TRACKED_SPECIES) = ONE_D%ZZ_F(1:N_TRACKED_SPECIES)
            CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_GET,RSUM_F)
            ONE_D%TMP_F = PBAR_F/(RSUM_F*ONE_D%RHO_F)    <--- RSUM_F goes to zero at 200 s
         ENDIF
```
`RSUM_F` goes to zero because `RHO_ZZ_F` is all zero and `ZZ_F` is all zero at mesh boundary cells. But these cells are not touching the HT3D OBST, so there is no clear cause for the problem other than somehow HT3D is involved. 

Work-around for the moment is to not use HT3D in this case. Given that the conductivity of the PMMA stick is relatively low and the heating is relatively uniform, there is no real advantage to 3D heat transfer and conduction. In face, with only 2 cells spanning the obstruction, 3D heat transfer is less accurate than 1D, in this case.

**Comment by mcgratta** [comment]
This is what the case looks like when I remove the HT3D attribute.
https://user-images.githubusercontent.com/11333911/150554208-8ee17b31-f52c-4496-b568-a184276b4e0c.mp4

**Comment by mcgratta** [comment]
[pyro_L1_28839_f.fds.txt](https://github.com/firemodels/fds/files/7916792/pyro_L1_28839_f.fds.txt)
This simpler version of the case fails in a few minutes. There are 20 meshes -- I cut off the remaining 12. In 5 s, a PMMA stick is introduced suddenly within a heated cylinder. The PMMA temperatures jumps up to 350 C in a few hundredths of a second. Lots of fuel gas is generated. 

There may not be anything wrong with the MPI calls, which was my first thought, or the surface of initialization of the PMMA slab, which was my second thought. I think the problem, at least with this version of the case, is the HT3D algorithm being used with a 2 cell thick OBST, which is not appropriate. The stick heats up unrealistically fast.

**Comment by rmcdermo** [comment]
This input file runs with the latest code.  The only change I made was to add `CHECK_HT=T`.  I'm going to make this default for HT3D.

[test.fds.txt](https://github.com/firemodels/fds/files/7979826/test.fds.txt)

**Comment by mcgratta** [comment]
That makes sense. I'll close.
