### ISSUE TITLE
Heat balance with heat exhaust

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10277]
I believe this is rather an output visualisation than a bug. But it would be useful if you could help me make a heat balance. 

The setup is a small room with a burner and a small OPENing. 
The second file is identical except a VENT is added to extract smoke. 
![image](https://user-images.githubusercontent.com/26166281/151128092-5870371e-567c-4c68-b524-c21bc0eea3dd.png)

My questions are below. Thank you.:

- Q_TOTAL converges to 0 in the Run1, while Run2 it does not. Is this normal?
- HRR = Q_RADI + Q_CONV+Q_CONV in Run 1. For Run 2 I cannot make a sum that equals to HRR. 
-- Run 2 average steady-state values:  
--- HRR: 250 kW
--- Q_RADI: 80 kW
--- Q_CONV: 81 kW
--- Q_COND: 19 kW
--- Device at the exhaust (HEAT FLOW): 155 kW

[Run1.fds.txt](https://github.com/firemodels/fds/files/7939934/Run1.fds.txt)
[Run2.fds.txt](https://github.com/firemodels/fds/files/7939936/Run2.fds.txt)

[Run1_hrr.csv](https://github.com/firemodels/fds/files/7940169/Run1_hrr.csv)
[Run2_hrr.csv](https://github.com/firemodels/fds/files/7940182/Run2_hrr.csv)
[Run2_devc.csv](https://github.com/firemodels/fds/files/7940183/Run2_devc.csv)

![image](https://user-images.githubusercontent.com/26166281/151131549-c5fe6c94-1313-47f0-a481-bc02b10a763e.png)

![image](https://user-images.githubusercontent.com/26166281/151127472-7422545d-2aea-46f5-a77f-b00f93b782e3.png)

**Comment by rmcdermo** [comment]
Here is the result from running `Run2.fds`:
```
[rmcdermo@burn Issue_10277]$ fds_dv Run2.fds 
MPI startup(): Warning: I_MPI_PMI_LIBRARY will be ignored since the hydra process manager was found

 Starting FDS ...

 MPI Process      0 started on burn.el.nist.gov

 Reading FDS input file ...

WARNING: SPEC REAC_FUEL is not listed and has been assigned the properties of nitrogen.

ERROR: DEVC QUANTITY HEAT FLOW not found (CHID: Q_TOTAL_exhaustON)

ERROR: FDS was improperly set-up - FDS stopped (CHID: Q_TOTAL_exhaustON)
```

1. @mcgratta This case highlights a bug that was has been introduced from the default SPEC stuff.  The user has specified a formula for the fuel, so this should work fine.

2. @Er9y714 Are you using only the _hrr file in your budget?  Follow the `fds/Verification/Energy_Budget/energy_budget_cold_walls.fds` case.  HEAT FLOW is deprecated.  "FLOW" quantities are not tight enough to do energy budgets.  You need to use a wall flux and integrate over the area.

We can leave this open until Kevin fixes the REAC_FUEL issue.

**Comment by drjfloyd** [comment]
In the SPEC routine, the MW from the fuel gets used, the specific heat will be based on GAMMA, but the Lennard-Jones parameters will use the values for N2, so the warning is correct. But should there be a custom warning indicating which properties of N2 are being used?

**Comment by rmcdermo** [comment]
Well, I jumped to a conclusion without studying the case in more depth.  Actually, I think this should be reported to Thunderhead.  Why on Earth do they not just use FUEL='METHANE'?

**Comment by rmcdermo** [comment]
Oh, now I see... "FDS5 Validation".

**Comment by rmcdermo** [comment]
@Er9y714 I'm seeing what you are seeing.  We will work on it and let you know.

![Run2_energy_budget](https://user-images.githubusercontent.com/4418497/151212468-17b4d67c-2bd8-4604-81a0-14b5f6ed26bb.png)

**Comment by rmcdermo** [comment]
The balance works with v6.7.0.  I'll do a bisect.

**Comment by rmcdermo** [comment]
```
f18d544e01d6a7d50b7c1b24ce13a1f9ee5e4e58 is the first bad commit
commit f18d544e01d6a7d50b7c1b24ce13a1f9ee5e4e58
Author: Kevin McGrattan <mcgratta@gmail.com>
Date:   Fri Jan 11 12:39:20 2019 -0500

    FDS Source: Issue #7040. Fix outgoing BC at heated wall
```

I halved the resolution and time of the case, it runs fast.

**Comment by mcgratta** [comment]
2019?? Too early to blame Covid. I'll take a look.

**Comment by mcgratta** [comment]
This energy imbalance is due to a change I made in 2019. At that time, there was a bug report regarding the thermal boundary conditions on a wall with a very small leak. To fix it, I changed the boundary condition, but this caused the energy imbalance that we have now. This is a plot of the Q_ENTH and Q_TOTAL after the fix.
![image](https://user-images.githubusercontent.com/11333911/151239082-b20d20a7-97df-4211-a754-97deff487562.png)

**Comment by Er9y714** [comment]
It looks great! Thank you for prompt response and solution!

My responses and questions:

- > @Er9y714 Are you using only the _hrr file in your budget? 

Yes, I only checked _hrr.csv file.

.


- > In the SPEC routine, the MW from the fuel gets used, the specific heat will be based on GAMMA, but the Lennard-Jones parameters will use the values for N2, so the warning is correct. But should there be a custom warning indicating which properties of N2 are being used?

For information, the same warning is given in the User Guide as well. 

 
![image](https://user-images.githubusercontent.com/26166281/151316684-705f4cc7-cbb2-49e3-ac46-ae9e4b74ae43.png)


.
- > HEAT FLOW is deprecated. "FLOW" quantities are not tight enough to do energy budgets. You need to use a wall flux and integrate over the area.

I think you are referring to the method [here ](https://groups.google.com/g/fds-smv/c/JPs0MWMJm3U/m/pLG_7bwkCwAJ)to measure the flux on the wall. Is that correct?
 However I understand from the post that `ENTHALPY FLUX WALL` will be available in the next release of FDS. 

.

> Well, I jumped to a conclusion without studying the case in more depth. Actually, I think this should be reported to Thunderhead. Why on Earth do they not just use FUEL='METHANE'?

I will inform them about this issue unless you already did. 
.

- > This energy imbalance is due to a change I made in 2019. At that time, there was a bug report regarding the thermal boundary conditions on a wall with a very small leak. To fix it, I changed the boundary condition, but this caused the energy imbalance that we have now. This is a plot of the Q_ENTH and Q_TOTAL after the fix.

Perfect! Thank you for your time.

**Comment by bwklein** [comment]
What does `FUEL='REAC_FUEL'` mean in this context? https://github.com/firemodels/fds/blob/master/Validation/Bittern_Sprinkler_Experiments/FDS_Input_Files/BITTERN_1.fds

Would the MW of that fuel and all other properties be replaced with those of Nitrogen?

**Comment by rmcdermo** [comment]
The MW would be based on the formula, but the fluid properties would be based on N2.

**Comment by bwklein** [comment]
Is there any matching based on formula C1H4 for the predefined fuels, or is it required to specify `FUEL='METHANE'` to get all of the built-in properties to apply to the species/reaction?

**Comment by mcgratta** [comment]
No, if you provide a FORMULA, FDS will use it to get a MW, but that's all.

**Comment by bwklein** [comment]
OK, and last remaining question what does `FUEL='REAC_FUEL'` mean to FDS?

**Comment by mcgratta** [comment]
Nothing, apparently.  I see no mention of 'REAC_FUEL' in the code.

BTW, I misspoke about FORMULA -- it also provides the atom count when the SPECies is used in a reaction.

**Comment by bwklein** [comment]
BTW, if you want to use a predefined species in FDS for defining a Reaction in PyroSim, there is a way to do that without using anything from the built-in library of Reactions.  Here is a video showing the difference.  https://youtu.be/mSk0K-weX1c
Also, I now stand corrected as I mention in the video my response to the highlighted bit in section 14.1.3 above.  You do not need to specify MW for the species, the MW is defined by the formula and will not be replaced with the MW of Nitrogen.  I think the highlighted section is incorrect.

**Comment by bwklein** [comment]
> Nothing, apparently. I see no mention of 'REAC_FUEL' in the code.

It is odd, we use it often in PyroSim for Simple Chemistry fuels and I see it used in the Bittern Validation input files too.  Is it just a placeholder for the FUEL parameter that could be anything?  It seems now that when `FUEL='REAC_FUEL'` is used, that means that the liquid properties of Nitrogen will be used for that reaction species.

**Comment by mcgratta** [comment]
The ID on the REAC line is usually not important. In fact, if you specify an ID but not FUEL, then FUEL=ID.

**Comment by mcgratta** [comment]
The Bittern cases were contributed by a user. I should have looked closer. I'll fix them.

**Comment by mcgratta** [comment]
The Bittern cases look like this
```
&REAC ID='POLYURETHANE',
      FUEL='REAC_FUEL',
      C=1.0,
      H=1.8,
      O=0.35,
      N=0.06,
      SOOT_YIELD=0.227,
      HEAT_OF_COMBUSTION=21900,
      RADIATIVE_FRACTION=0.46/
```
FDS in this case just uses the C, H, O, and N directly.

**Comment by bwklein** [comment]
> FDS in this case just uses the C, H, O, and N directly.

And to be clear the 'liquid' properties of this reaction fuel will be based on Nitrogen.

**Comment by mcgratta** [comment]
```
   CASE DEFAULT
      CP = -1._EB
      H_L = -1._EB
      H_V = -1._EB
      T_REF = -1._EB
      DENSITY=-1._EB
      T_MELT = -1._EB
      T_BOIL = -1._EB
END SELECT

END SUBROUTINE JANAF_TABLE_LIQUID
```
An unlisted fuel is not assumed to have liquid properties. I think FDS would throw an error if the user did not provide them.

**Comment by bwklein** [comment]
> An unlisted fuel is not assumed to have liquid properties.

Sorry, I meant to say 'fluid' properties, not liquid.

**Comment by mcgratta** [comment]
If you provide values of C, H, O, and N or if you provide a FORMULA, FDS will compute a molecular weight, and assume specific heat is given by 
```
 CP = (R0/MW)*GAMMA/(GAMMA-1._EB)
```
where GAMMA=1.4, the default ratio of c_p/c_v. Specific enthalpy would just be CP*T. Pr=0.71, heat of formation=0, and Leonard-Jones values for N2. The LJ parameters really only matter when doing a DNS calc. For a typical FDS calc, CP  and MW are the most important.
