### ISSUE TITLE
READ ERROR in CHID_evac.eff

### ISSUE THREAD

**Issue by MartinK416** [firemodels/fds#10278]
Ich habe das Problem, dass beim Start meiner Evac-Berechnung dieser Fehler in der Eingabeaufforderung erscheint. Jetzt schaue ich in den Ordner und finde keine CHID_evac.eff -Datei. Kann mir zufällig jemand weiterhelfen?

**Comment by gjaeger** [comment]
Without a minimal example indicating the version used, I find it difficult to respond to this "issue".

@MartinK416 Is this a bug or rather an application problem? Would you like to share your application example with a short input file and prompt output in the [disscussion group](https://groups.google.com/g/fds-smv)?
