### ISSUE TITLE
FDS Installation on MacOS

### ISSUE THREAD

**Issue by JackG07** [firemodels/fds#10307]
Im having some problems running fds version 6.7.6 on MacOS Big Sur (11.2.3). I was told by my lecturer to download an earlier version of fds, which is why im not choosing the latest version. Ive gone through the installation steps and added the lines of code:

source /Applications/FDS/FDS6/bin/FDS6VARS.sh
source /Applications/FDS/FDS6/bin/SMV6VARS.sh

to my .bash_profile file, but when I try and run fds it still wont work, and will just tell me "command not found: fds"

I have a second bash file, .bash_sessions, but my lecturer told me this was a folder so did not need any lines of code. The following are the lines of code i have in my .bash_profile, when typing "nano .bash_profile" is this correct?

source /Applications/FDS/FDS6/bin/FDS6VARS.sh
source /Applications/FDS/FDS6/bin/SMV6VARS.sh

# unlimit stack for OSX
ulimit -s 65532

I have seen other posts about adding the lines to the .zsh files, but i only have .zsh_history and .zsh_sessions, so i dont think it is appropriate for either. Any help would be greatly appreciated as im quite stumped. Thanks a lot.

**Comment by JackG07** [comment]
The "unlimit stack for OSX" is written as "# unlimit stack for OSX" , its not meant to be bold and large

**Comment by marcosvanella** [comment]
did you open a new window and try executing fds?

**Comment by parsipal** [comment]
I'm using macOS too.
My setup in .bash_profile  is:

```
#---------------------------------- 
# Setup FDS and SMV 
export PATH=/Applications/FDS/FDS6/bin:$PATH
export PATH=/Applications/FDS/FDS6/smvbin:$PATH
export PATH=/Applications/FDS/FDS6/bin/openmpi_64/bin:$PATH
export OPAL_PREFIX=/Applications/FDS/FDS6/bin/openmpi_64

#  set OMP_NUM_THREADS to max of 4 and "Total Number of Cores" obtained from running
#  system_profiler SPHardwareDataType
#  unlimit stack for OSX
export OMP_NUM_THREADS=4
ulimit -s 65532

# Alias  SMOKEVIEW 
alias smv='/Applications/FDS/FDS6/smvbin/smokeview'
#----------------------------------
```
Then, close Terminal windows and open a new windows or type " source .bash_profile"

**Comment by gforney** [comment]
also make sure your shell is bash and not zsh
type echo $SHELL in a command window to confirm

**Comment by marcosvanella** [comment]
@parsipal that also works. The scripts FDS6VARS.sh and SMV6VARS.sh will add the executable paths in similar manner.

**Comment by JackG07** [comment]
Thank you all for the responses, so ive copied the script above into my bash profile but it still isnt working. Getting the error:

zsh: command not found: fds

It may be that my shell is zsh not bash? How do i change this?

Thanks a lot

**Comment by JackG07** [comment]
when i type:

echo $SHELL

it says:

/bin/zsh

**Comment by gforney** [comment]
Google: how change shell from zsh to bash

chsh -s /bin/bash

**Comment by JackG07** [comment]
Thanks a lot, FDS is now being recognised.

My examples are not running, i get this error:

Jacks-MacBook-Air-5:Fires jackgrahamslaw$ fds box_burn_away1.fds

 Starting FDS ...

 MPI Process      0 started on Jacks-MacBook-Air-5.local

 Reading FDS input file ...

forrtl: Permission denied
forrtl: severe (9): permission to access file denied, unit 11, file /Applications/FDS/FDS6/Examples/Fires/box_burn_away1.sinfo
Image              PC                Routine            Line        Source             
fds                000000010785E3D2  for__io_return        Unknown  Unknown
fds                0000000107882CB9  for_open              Unknown  Unknown
fds                00000001014FD4B2  dump_mp_write_smo     Unknown  Unknown
fds                000000010169970B  MAIN__                Unknown  Unknown
fds                0000000100F3D42E  main                  Unknown  Unknown

Why would this be? Thank you

**Comment by gforney** [comment]
Copy the input file to somewhere in your home directory. You don't "own"
the directory where fds was installed.  Type ls -l and you will see the
owner of the files

**Comment by Stven-Frank** [comment]
look at this video.
[https://www.youtube.com/watch?v=7gHW2_jSK28&t=67s](url)

**Comment by marcosvanella** [comment]
Closing. @JackG07 try the latest bundle and if you have issues get back in touch.

**Comment by akshithmandala** [comment]
How can I download the FDS6.7.7_SMV6.7.18 for MacBook Air M1 chip. It is troubleshooting a lot. Can any one help me for installing the software in my Mac?

**Comment by rmcdermo** [comment]
You can run the macOS bundle on M1.  Follow instructions here.  If these do not work, please let us know where you get stuck.

https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-under-macOS
