### ISSUE TITLE
ERROR: Numerical Instability - FDS stopped (Minimum density cliped)

### ISSUE THREAD

**Issue by TankyJeff** [firemodels/fds#10308]
I had a couple of cases with simple wind (without wind there won't be any issue) that displayed the following message whilst trying to run them. 
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
 Time Step:    423, Simulation Time:      1.82 s

ERROR: Numerical Instability - FDS stopped (CHID: NRCC_Zefeng_Huang1_1)
Please advice on how to solve them as this error doesn't always occur with slightly varied construction geometry. The corresponding case files are also attached below.
[FDS 1.txt](https://github.com/firemodels/fds/files/8030139/FDS.1.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
What version of FDS are you using?

**Comment by mcgratta** [comment]
The case is running for me with the latest source code. This may be an error that we have already fixed. You can do one of two things:

1. Install the [latest test version of FDS](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC)
2. Do not use V0 on the WIND line. All that this does is initialize the flow to 3.6 m/s, but does not sustain it. To sustain the wind, you use SPEED and DIRECTION. However, in this case, this is a really bad way to create a wind. You are not allowing the wind field to form naturally. It is not surprising that the calculation failed.

**Comment by TankyJeff** [comment]
Ok, I was running it on an HPC server with FDS version 6.7.7. And I would apply your second suggestion. Thank you for your assistance. If any more problems pop up, I would post it again in the form.
