### ISSUE TITLE
porous_media, error message

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#10310]
Morning All,

Section 17.4.8 of the Users Guide states, "Note that the LENGTH of the cylinder which is normally required on the SURF line is computed automatically..."

When I run the file, I get the following error message.

ERROR: SURF LIGAMENT needs a LENGTH (CHID: porous_media)

Thanks

Dave

**Comment by drjfloyd** [comment]
Can you provide a simple test case with your specific SURF input.

**Comment by Dave-McGill** [comment]
Sorry, I should have been clearer. I'm referring to fds6\Examples\Sprinklers and Sprays\porous_media.fds.

**Comment by mcgratta** [comment]
This test case is run every night. What version of FDS do you have?

**Comment by Dave-McGill** [comment]
6.7.7

**Comment by mcgratta** [comment]
I wonder if this is a Windows vs linux thing. I assume you are running the case as is?

**Comment by Dave-McGill** [comment]
If I add a value of length, then it runs.

&SURF ID='LIGAMENT', HEAT_TRANSFER_COEFFICIENT=10.0, MATL_ID(1,1)='ALUMINUM ALLOY', MATL_MASS_FRACTION(1,1)=1.0, THICKNESS(1)=7.3E-5, GEOMETRY='CYLINDRICAL', LENGTH=0.01, INNER_RADIUS=0.0/

**Comment by Dave-McGill** [comment]
What happens if you run it on Windows?

**Comment by mcgratta** [comment]
It runs, but I am using a nightly build
![image](https://user-images.githubusercontent.com/11333911/153234310-9ac8caaa-adf9-44ad-858b-e4d8695aeb37.png)

**Comment by mcgratta** [comment]
Can you show me a screen shot of what you see when you run the file as is with the latest official release.

**Comment by Dave-McGill** [comment]
I'm running it through PyroSim (OK, so I'm not a hardcore purist); but pointing to the FDS executable. Here's the log file.

ENV:  {PATH=C:\Program Files\PyroSim 2021\fds;C:\Program Files\PyroSim 2021\fds\mpi;C:\Program Files\firemodels\FDS6\bin;C:\Windows;C:\Windows\system32, OMP_STACKSIZE=16M, OMP_NUM_THREADS=1, I_MPI_WAIT_MODE=1}
CMD:  "C:\Program Files\PyroSim 2021\fds\runfds.exe" mpiexec.exe -localonly -n 3 "C:\Program Files\firemodels\FDS6\bin\fds.exe" porous_media.fds
WDIR: C:\temp\porous_media

 Starting FDS ...

 MPI Process      0 started on FireModel1
 MPI Process      1 started on FireModel1
 MPI Process      2 started on FireModel1

 Reading FDS input file ...


ERROR: SURF LIGAMENT needs a LENGTH (CHID: porous_media)

ERROR: FDS was improperly set-up - FDS stopped (CHID: porous_media)
[runfds.exe] subprocess exit: 0

**Comment by Dave-McGill** [comment]
I used the cmd prompt with the file that was passed through PyroSim, and got the same error. I used it with the file from the Examples folder, and it worked fine.

So, it's something in how PyroSim processes the file. I'll pass this onto them.

Sorry for the bother.

**Comment by mcgratta** [comment]
Are you sure you are running the latest version of FDS. I just downloaded the latest official release for Windows and I see
![image](https://user-images.githubusercontent.com/11333911/153237937-45c85885-60e4-45d1-8e3e-8e81912dcd95.png)
