### ISSUE TITLE
BlenderFDS MESH+MULT verification case crashes 

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#10312]
Hi, I am currently working on the BlenderFDS MESH+MULT import verification cases.
The following attached (simple) case contains an array of small MESHes with various types of MULT multiplicators:

[mesh_mult.fds.txt](https://github.com/firemodels/fds/files/8040349/mesh_mult.fds.txt)

All MESH+MULT couples works correctly when put in separate files.

But when I put all MESH+MULT couples in the same case (as attached) the case crashes with:

Starting FDS ...
MPI Process      0 started on shibax
Reading FDS input file ...
forrtl: Too many open files
forrtl: severe (603): too many open files

If I remove the last two MESHes ('mesh_32', 'mesh_33'), the case works correctly.
I do not need to keep all of them in the same case, but imho this crash seems interesting enough.

I am running this case on LInux with the latest FDS nightly:

 Fire Dynamics Simulator
 Current Date     : February 10, 2022  11:32:59
 Revision         : FDS6.7.7-612-g867757872-nightly
 Revision Date    : Sat Feb 5 20:48:25 2022 -0500
 Compiler         : ifort version 2021.5.0
 Compilation Date : Feb 09, 2022 08:09:06
 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1
 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.4 for Linux* OS

Thank you

**Comment by emanuelegissi** [comment]
In addition, my ulimit seems already correctly set:
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 63257
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 63257
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
How many meshes do you have? And does the case fail if you run with that many MPI processes?

**Comment by emanuelegissi** [comment]
This is just a verification case, it has no other practical application.
I am running it in a single process.
If I remove the last two MESHes, the calculation is almost immediate.

Il giorno gio 10 feb 2022 alle ore 14:55 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by mcgratta** [comment]
open files (-n) 1024

I think we're hitting the upper limit of open files in Fortran. This case has 329 meshes all loaded onto one MPI process. Each mesh has some default files that get opened. I can try trimming to see if I can stay within the limit. One can increase this limit at run time.

**Comment by mcgratta** [comment]
Try it now. FDS opens 3 "smoke3d" files per mesh, even when they are  not necessary. It no longer does this.

**Comment by emanuelegissi** [comment]
Ok, I am going to test it today. Thanks

Il giorno gio 10 feb 2022 alle ore 17:30 Kevin McGrattan <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
I tested the nightly FDS6.7.7-629_SMV6.7.18-442_tst_lnx.sh
It works ok. Thank you.
Closing
