### ISSUE TITLE
FDS-SMV wont install on my laptop

### ISSUE THREAD

**Issue by mketchen** [firemodels/fds#10318]
I am able to download the program on my laptop and view it in my downloads folder. Everytime I try to complete the instaallation and finsh the instructions on the black coding screen, it closes out the window and I cant view anything on my desk top. I am using a MSI laptop, on the most current version of Windows as of 2-11-22.

**Comment by mcgratta** [comment]
Do you see an icon called CMDfds? What happens if you type "fds_local" at the command prompt?

**Comment by gforney** [comment]
make sure you have admin rights.  to verify
1.  open a command window
2.  type 
net user mketchen

assuming mketchen is your user name on your PC.  You should see a bunch of output with a line something like

Local Group Memberships   *Administrators

**Comment by mketchen** [comment]
I do not see a CMDfds icon at all. And if i try to type fds_local, it reprompts me with the same yes, no question that I get when i open the window initially.

**Comment by gforney** [comment]
what do you see when you type 'net user mketchen' in a command window
