### ISSUE TITLE
&WIND abnormally high wind...

### ISSUE THREAD

**Issue by gmsafir** [firemodels/fds#10314]
Hi, I simulate an exterior wind field, using &WIND with neutral stability, on a complex terrain.
The wind field start to get abnormally high values after 4s.

Here is the zipped param file: [test_b1_deb_deadmat_final_wind.zip](https://github.com/firemodels/fds/files/8048454/test_b1_deb_deadmat_final_wind.zip)

Any idea?

BGBG

**Comment by ericvmueller** [comment]
What version of FDS are you using? `RAMP_SPEED_T` is now used instead of `RAMP_SPEED` to control the temporal variation of wind (see section 18.1.3 of the user guide).
It also looks like you are using the ramp to increase the wind speed dramatically after 4s. Are you really trying to capture such an increase?
`

**Comment by gmsafir** [comment]
I use version 6.7.5

**Comment by gmsafir** [comment]
I don't get your point about the wind speed ramp: it is designed to be: 10% of 20m/s btw 3. and 4.5s, growing to 100% of 20m/s from 4.5 to 6.5s, then keeping at 100% btw 6.5 and 19s, then decreasing to 10%, etc.

**Comment by ericvmueller** [comment]
That is an order of magnitude increase over a couple of seconds. I'm just not sure if the current approach has been demonstrated to be stable for such a gust. Can you specify what you mean by abnormally high values and if you observe them somewhere specific within the domain?

**Comment by rmcdermo** [comment]
You probably need to set a tighter velocity tolerance.  I'm testing now.

**Comment by rmcdermo** [comment]
The case seems to be running fine with the latest source, you can get a copy of the executable from the link to the test builds on the [FDS Release Notes](https://github.com/firemodels/fds/releases) wiki page.  Note, as Eric mentioned, you need to change `RAMP_SPEED` to `RAMP_SPEED_T`.  Also, add a `PRES` line,
```
&PRES VELOCITY_TOLERANCE=1.E-3, MAX_PRESSURE_ITERATIONS=100/
```

Lastly, I would not use MO profiles here.  They are useful for stationary boundary layers on flat terrain.  FDS references the bottom of the profile to a single z value and so it is not useful (and probably harmful) to use it with sloped terrain.  Just add several vertical line `DEVC` (using `POINTS=...`) and record the profiles and then look at them to make sure they make sense.

**Comment by rmcdermo** [comment]
Note, you probably don't need the latest source.  Just add the `PRES` line mentioned above and get rid of MO.

**Comment by gmsafir** [comment]
Thanks a lot Randy for your tests and solution

**Comment by rmcdermo** [comment]
Did this work for you?  Or do we need to keep this open?

**Comment by gmsafir** [comment]
Yes and no:
- yes = it works getting rid of MO (with or without PRES),
- no = does not work when MO is present (with or without PRES).  
  
The problem really comes from MO.
I understand that MO is for stationary atmospheric boundary layer over flat terrain, and here we are unstationary (due to the speed ramp) and in complex terrain.
But would there be an alternative way to the extremely simplifying assumption of a constant-z-profile of wind, nudged over the entire domain (100mx100m) ?

**Comment by mcgratta** [comment]
I am looking at that now. The problem with the current FDS User's Guide regarding wind is that it is not clear which parameters are inputs and which are outputs. In theory, we should be able to specify the pressure gradient force and Coriolis force, some measure of surface roughness, ground/air temperature, and then compute (not input) parameters like the Obukhov length.

**Comment by rmcdermo** [comment]
At the moment, there is not.  Firstly, we do not "nudge" anymore.  That method proved to be very unstable and inaccurate.

The upstream wind field is specified on the boundary.  You can still specify a ramp for the z profile, but if you have terrain, you can see how ambiguous this becomes.  It seems much safer to me to move your boundaries farther away and let the wind develop rather naturally.  This can be done with rather coarse grids to make it more computationally feasible.

One thing that I think we do need to work out is that as the wind changes direction, the upstream boundary area may change, and this means the volume flow is not necessarily consistent on the inflow and outflow wind fields.  But trying to come up with a simple way to implement this seems difficult.  It seems to me that we are often rather cavalier about what we mean when we specify a wind speed.  When you have terrain this becomes ambiguous.

**Comment by gmsafir** [comment]
I thought that &WIND, meant to be used for the next FDS versions, was nudging ?? and the  "wall of wind" (&VENT... vel, vel_t...) was equivalent to "upsteam wind field specified on the boundary" and was no more maintained in future versions? I am not correct then?

**Comment by rmcdermo** [comment]
@gmsafir No, you are not correct.  Nudging (MEAN_FORCING) we discovered produced unstable spurious fluctuations on outflow boundaries, and this method had to be abandoned.   See latest guides accurately describe what is done now at wind boundaries.  This is also mentioned in the [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes) for version 6.7.6.

**Comment by gmsafir** [comment]
I read comparatively FDS UG 6.7.5 and 6.7.6 to understand the changes: I see that 2 sub-sections disappeared, namely the "Shielding Indoor Volumes" (BLOCK_WIND) and the "Mean Forcing concept".

Please could you help me clarify my understanding on the following samples ? (I assume that I am in complex terrain)

If I first put &WIND SPEED=5.0, DIRECTION=225.0 in my data file, I understand that I thereby prescribe a constant ambient wind (constant z-profile and constant time-profile). 
Does it mean that in each 'atmospheric' single cell of the domain, the prognostic fire-generated wind (i.e. solved from the equations with the thermal source) will somehow be driven/relaxed towards the prescribed ambient wind? Or is the wind averaged spatially over all single cells and this average value is driven/relaxed towards the prescribed ambient wind ? Or are they not mixed every time and then the ambient wind prescription is just an initial condition in each single cell of domain ?
Is it the case if I put all &VENT (PBX=PBY=...,PBZ=..) to the value 'OPEN' ? Or does the "mixing" require special &SURF or &VENT values?

Now if I put &WIND SPEED=5.0, DIRECTION=225.0, L=1E6., Z_0=0.03  in my data file: I thereby prescribe a constant time-profile and MO neutral z-profile (I understand that Z_REF=2m by default when not specified).
Same questions as above: how is the mixing peformed, if any?
I somehow get from your previous answers that this case cannot be handled properly on complex terrain, in link with the reference Z=0, but I can't figure preciously why.

**Comment by mcgratta** [comment]
If you specify only SPEED and DIRECTION, FDS will specify this velocity at upstream boundaries. If you add M-O parameters, FDS will try to force the velocity and temperature profiles from the ground, or the lowest part of your domain. Thus, do not use M-O parameters for non-flat terrain.

**Comment by gmsafir** [comment]
ok, that is clear. A very last precision, please: what is then the difference btw &WIND SPEED= DIRECTION=... and imposing &VENT VEL,VEL_T=...? (choosing the upstream VENTs)

**Comment by rmcdermo** [comment]
There is a subtle difference in the way the pressure boundaries are handled.  In the WIND case we follow the boundary condition described in Sec. 4.3.3 Open Boundary Conditions (Wind) in the Tech Guide.

**Comment by gmsafir** [comment]
ok, now everything is clear

**Comment by rmcdermo** [comment]
Please do not post copyrighted material to the Issue page.  You will need to repost your question with just the link or reference.  Thanks

**Comment by gmsafir** [comment]
As expressed earlier by Kevin "In theory, we should be able to specify the pressure gradient force and Coriolis force, some measure of surface roughness, ground/air temperature, and then compute (not input) parameters like the Obukhov length.".

Two comments:

If I understand well the GEOSTROPHIC_WIND could be used to indirectly specify the pressure gradient ?
I am not sure that specifying the air temperature in complex terrain will be easy: probably it would need also to be computed, not input.
I am thinking about this paper concerning an atmospheric LES model called EULAG developed at NCAR, that is able to reproduce atmospheric boundary layers in complex terrains at any type of atmospheric grid scales - see equations (2), (3), (4):
https://www.sciencedirect.com/science/article/abs/pii/S004579300700206X#!

Note: the buoyancy term (gTheta'/Theta0) in the wind equation is important (don't know if it is already included in FDS?).

**Comment by rmcdermo** [comment]
Yes, it is included.  Please read the FDS Tech Guide.

**Comment by gmsafir** [comment]
Thanks, I will try the prognostic way of atmospheric boundary layers

**Comment by rmcdermo** [comment]
OK, are we good to close this then?

**Comment by gmsafir** [comment]
indeed
