### ISSUE TITLE
Time of arrival output for level set fire sims

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#10324]
There’s a need for time of arrival (TOA) files for (at least) the level set model. 
An example (from WFDS) is attached which shows the location of the fire front every 20 s (the straight vertical red lines are ATV ignition tracks). 
In WFDS, I initialized the TOA to -1. When the level set value, at a given cell, exceeds a threshold, and TOA=-1, then TOA is set to the current simulation time.

TOA needs to be included in the restart too.

<img width="403" alt="TOA_example" src="https://user-images.githubusercontent.com/12721870/154120893-ad0a8b7b-5894-4019-9dd5-aa356199aebd.png">

**Comment by mcgratta** [comment]
I added 'TIME OF ARRIVAL' as a slice output, i.e.
```
&SLCF AGL_SLICE=2, QUANTITY='TIME OF ARRIVAL' /
```
Try it and let me know if it works.

**Comment by ruddymell** [comment]
Thanks for implementing this quickly.
TOA output seems fine.
Restart does not appear to be working (with or without TOA output): a restart run repeats the original simulation instead of continuing it.

**Comment by mcgratta** [comment]
Can you describe what you did to restart the case?

**Comment by ruddymell** [comment]
I used input_LS1_restart_1st.txt to run out to 60 s and dump a restart file. Then used input_LS1_restart_2nd.txt to run the restart case. 
The restart run shows the first run (out to 60 s) then starts a new, identical, run.

[input_LS1_restart_1st.txt](https://github.com/firemodels/fds/files/8084328/input_LS1_restart_1st.txt)
[input_LS1_restart_2nd.txt](https://github.com/firemodels/fds/files/8084329/input_LS1_restart_2nd.txt)

**Comment by mcgratta** [comment]
Sorry, I recently moved the reading of restart files ahead of the level set initialization. It should work now. Test it.

**Comment by ruddymell** [comment]
Test case works now. Thanks.
