### ISSUE TITLE
Output A and E in TGA_ANALYSIS mode

### ISSUE THREAD

**Issue by shostikk** [firemodels/fds#10322]
Simulations with TGA_ANALYSIS = .TRUE. usually start with REFERENCE_TEMPERATURE etc (first order), but if user wants to see the resulting A and E, and continue by specifying / modifying them directly, it would be convenient to see the calculated values from somewhere. 

Normally, FDS writes A and E in .out file, under MATERIAL definitions. But TGA_ANALYSIS -mode does not produce .out file. Finding A and E requires removing TGA_ANALYSIS = .TRUE. -line, and making sure the file runs otherwise. Unnecessary steps in the process.

How about writing A and E directly to LU_ERR before the 'STOP: FDS performed.... ' -line?

**Comment by rmcdermo** [comment]
Probably better to just move the LU_OUT to after the TGA_ANALYSIS.  I like seeing the .out file.

**Comment by mcgratta** [comment]
Check that it works. I tested on one case and everything seems OK.

**Comment by shostikk** [comment]
Tested too. Seems to work. Thank you!
