### ISSUE TITLE
FDS Installation on MAC OS

### ISSUE THREAD

**Issue by aboatxng** [firemodels/fds#10336]
Hi I am trying to download FDS6.7.7 on Mac OS 12.2.1

I can do the first part of the installation process, however when I get to the last few parts I struggle to understand what I should do.

"At the end of the installation you will be given suggestions (based where you installed FDS) on how to update your startup file so that the fds command may be run from the command line. Open ~/.bash_profile or ~/.zshrc (if you use the Z shell) and add the following (in this order):

source /Applications/FDS/FDS6/bin/FDS6VARS.sh 
source /Applications/FDS/FDS6/bin/SMV6VARS.sh

#  set OMP_NUM_THREADS to max of 4 and "Total Number of Cores" obtained from running
#  system_profiler SPHardwareDataType
export OMP_NUM_THREADS=4

# unlimit stack for OSX
ulimit -s 65532.    

Can anyone please give me a step by step tutorial on how finish the installation.

**Comment by marcosvanella** [comment]
copy to clipboard those lines:

source /Applications/FDS/FDS6/bin/FDS6VARS.sh
source /Applications/FDS/FDS6/bin/SMV6VARS.sh
export OMP_NUM_THREADS=4
ulimit -s 65532

In your command window:
> vi ~/.bash_profile
Hit the key "i"

paste those lines (cmd+v).

Hit ESC.
Type ":wq" and Enter

Open another command window. Type fds to see if you have it in your path.

**Comment by aboatxng** [comment]
Thanks for the quick response I followed your instructions and typed fds in a separate window and this is what I got. 

Fire Dynamics Simulator

 Current Date     : February 18, 2022  17:40:02
 Revision         : FDS6.7.7-0-gfe0d4ef38-release
 Revision Date    : Thu Nov 18 17:10:22 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Nov 19, 2021  08:14:42

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Open MPI v4.1.0, package: Open MPI gforney@bevo.el.nist.gov Distribution, ident: 4.1.0, repo rev: v4.1.0, Dec 18, 2020
 Consult FDS Users Guide Chapter, Running FDS, for further instructions.

**Comment by rmcdermo** [comment]
Yep, that means it's working.  Now you need an input file to actually run a case.  Please read the user guide.

**Comment by rmcdermo** [comment]
Please post further questions to the discussion forum.

**Comment by aboatxng** [comment]
So does this mean I can run a simulation from the terminal application?

**Comment by rmcdermo** [comment]
Yes

**Comment by aboatxng** [comment]
thank you very much for your help
