### ISSUE TITLE
gnu linux workflow action no longer compiler

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10338]
@marcfehling Looks like there is some problem with the [latest gnu linux compile](https://github.com/firemodels/fds/actions/runs/1867010127).  Could you please take a look at this.  Perhaps we do not need to grab the latest open-mpi.

**Comment by marcfehling** [comment]
Thanks for letting me know! I can reproduce the issue on my fork as well.

Looks like a dependency of `openmpi-bin` is not available in the ubuntu package repository at the moment.

I'll try to add the suggested `apt-get update` and see if it works.
