### ISSUE TITLE
No PLT3D output on INSTABILITY_STOP

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10356]
The attached case is a modification of the `obst_activation_uscarc_inseparable.fds` case that Susan added to test the updates to ScaRC for add/remove OBST.   The case fails, which is a different issue.  But upon failure I noticed that the usual PLT3D output was not generated, so you don't see where things blowup in Smokeview.

The case fails at about 5 s with MPI and immediately in serial.

[obst_activation_2.fds.txt](https://github.com/firemodels/fds/files/8179469/obst_activation_2.fds.txt)

We must be exiting main before calling `DUMP_MESH_OUTPUTS`.   I printed `STOP_STATUS` in `DUMP_MESH_OUTPUTS` as shown below, and, as you can see, we never see a `STOP_STATUS==1`.

```
print *,STOP_STATUS
IF (T>=PL3D_CLOCK(PL3D_COUNTER(NM)) .OR. STOP_STATUS==INSTABILITY_STOP) THEN
   CALL DUMP_SLCF(T,DT,NM,1)
   DO WHILE(PL3D_COUNTER(NM)<SIZE(PL3D_CLOCK)-1)
      PL3D_COUNTER(NM) = PL3D_COUNTER(NM) + 1
      IF (PL3D_CLOCK(PL3D_COUNTER(NM))>=T) EXIT
   ENDDO
ENDIF
```

The results of the case compiled with this code are:
```
 Job ID string    : obst_activation_2

           0
           0
           0
           0
           0
           0
           0
           0
 Time Step:      1, Simulation Time:      0.09 s
           0
           0
           0
           0
 Time Step:      2, Simulation Time:      0.09 s

ERROR: Numerical Instability - FDS stopped (CHID: obst_activation_2)
```

**Comment by mcgratta** [comment]
When FDS detects an instability, it sets `STOP_STATUS=INSTABILITY_STOP` and completes the time step, including a dump of a Plot3d file. But there was a call to `STOP_CHECK` after the call to the SCARC solver. This routine detects the `INSTABILITY_STOP` and shuts down the run before the Plot3D file gets dumped.

**Comment by rmcdermo** [comment]
Okay, thanks, that fixed it.
