### ISSUE TITLE
How to use geom to model inclined tunnels

### ISSUE THREAD

**Issue by xun21** [firemodels/fds#10361]
How to use the geom command to model inclined tunnels？
and I don't know how to use geom command
,please help help me

**Comment by rmcdermo** [comment]
GEOM is not generally supported with the current version of FDS (v6.7.7).

Also, questions like these should be directed to the [FDS discussion forum](https://groups.google.com/g/fds-smv)

**Comment by Leungxunjing321** [comment]
Does the latest version also work?

> GEOM is not generally supported with the current version of FDS (v6.7.7).
> 
> Also, questions like these should be directed to the [FDS discussion forum](https://groups.google.com/g/fds-smv)

thank u, and Does the latest version also work?

**Comment by rmcdermo** [comment]
It is in development.  You might be something to run.  But it is not validated and should not be used for a real-world project.
