### ISSUE TITLE
About the replacement function of SAWTOOTH=.FALSE. statement command

### ISSUE THREAD

**Issue by xun21** [firemodels/fds#10363]
In the sixth edition, the SAWTOOTH=.FALSE. statement command has been deleted, and which command can be used to eliminate the "jagged" boundary produced by the inclined tunnel. Can you give a statement for a similar case of inclined , or the complete statement to achieve the purpose?

**Comment by rmcdermo** [comment]
This question should be submitted to the [FDS discussion forum](https://groups.google.com/g/fds-smv)
