### ISSUE TITLE
How to install the Linux version of the FDS code on google colab

### ISSUE THREAD

**Issue by AliZebardastinik** [firemodels/fds#10370]
I am currently using FDS code for simulation and I need high processing power to do so. That's why I want to install the Linux version of the FDS code on google colab. But I have a problem. Please guide me to install the FDS code completely on google colab and also start the simulation.

**Comment by rmcdermo** [comment]
This question should be posted to the [FDS discussion group](https://groups.google.com/g/fds-smv)
