### ISSUE TITLE
About the operation error of the fifth version of fds：fds.exe - System error, code execution cannot continue because impi.dll could not be found. Reinstalling the program may resolve this issue.

### ISSUE THREAD

**Issue by xun21** [firemodels/fds#10379]
About the running error of the fifth version of fds, but I can run the sixth version, the fifth version will pop up: fds.exe-system error
       Code execution cannot continue because impi.dll could not be found. Reinstalling the program may resolve this issue.
What should I do to fix this error?
In addition, since I want to use the fifth version of the inclined shaft tunnel to use the sawtooth=.false. command to smooth the "staircase" condition, if the sixth version is used to smooth the inclined shaft tunnel, what should I do? What kind of commands are processed?
please let me know, thanks

**Comment by gforney** [comment]
Use the cmdfds conmand shell or type fdsinit first

**Comment by xunxun321** [comment]
I did as you said, but still the same doesn't work

**Comment by gforney** [comment]
Are you using fds_local.bat to run your case? Look at fds issue 9128 and the fds users guide

**Comment by rmcdermo** [comment]
This question should be handled in the [fds discussion forum](https://groups.google.com/g/fds-smv)
