### ISSUE TITLE
Warning on FUEL

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#10387]
With the current source,  Revision  : FDS6.7.7-739-g7f8989edc-master
A warning is in the .out file is isuued when the FUEL species in &REAC is not one of the previously defined options

For example, the warning below occurs fo the Verification case pine_needles.fds 
WARNING: SPEC CELLULOSE is not listed and has been assigned the properties of nitrogen.

**Comment by drjfloyd** [comment]
It has always been the case that any properties not defined on SPEC are assumed to be those of N2.  For a FUEL on REAC the MW based on C,H,O,N is used and the specific heat is defined assuming gamma=1.4 and the MW. Kevin added this warning message a short time ago to try and make sure users are aware of this.
