### ISSUE TITLE
Running FDS parallel jobs in a cluster?

### ISSUE THREAD

**Issue by RNstu08** [firemodels/fds#10385]
Hello everyone.

I am currently cross-verifying the performance of the simulation on the cluster to determine important parameters such as the number of nodes, ntasks, cpu_per_task, ntasks_per_cpu, etc. I am not sure whether all of these parameters need to be described in the slurm script or only some. Hence, I have commented out these parameters in this script. 
Here is an example of the slurm script that I used for the Test1.fds case. And I noticed that the processor load is almost idling over a long period of time for the single node that I am using. Hence, overkilling the cluster time. (See cluster_performance.png for an example.)
![cluster_performance](https://user-images.githubusercontent.com/97069157/157877006-aff39004-ddc8-43ff-82bc-a9f4ecf26652.png)

Here are the cluster details (see image cluster_data.png). I am running a very simple case where the domain is divided into 4 meshes (to find appropriate parameters for a parallel run).
![cluster_data](https://user-images.githubusercontent.com/97069157/157877029-5f9b5ed2-720b-4332-b201-ab136bcbcec4.PNG)

My question is,
How to efficiently use the cluster by decreasing the overall simulation time?
How to determine and set the parameters? What are their dependencies on the number of meshes?

I have also read the FDS user guide and the information available on this link. https://cloudhpc.cloud/2022/01/28/fds-scalability/ 

#!/bin/bash
#SBATCH --time=UNLIMITED
#SBATCH --nodes=1
#SBATCH --partition=hpc-128G
#SBATCH --job-name=REF_4_M22
#SBATCH --mem-per-cpu=65536

##SBATCH --ntasks=4
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=4

### Output files
#SBATCH --error=/home/%u/case_1/REF_4/new_domain_SLURM/M21/1/job.%J.err
#SBATCH --output=/home/%u/case_1/REF_4/new_domain_SLURM/M21/1/job.%J.out

lsc_FDSFile="$HOME/case_1/REF_4/new_domain_SLURM/M21/Test1.fds"
lsc_FDSOutputPath="$HOME/case_1/REF_4/new_domain_SLURM/M21/1/FDS_v677"
lsc_FDSChunks=256
if ! [[ -d "${lsc_FDSOutputPath}" ]]; then
    mkdir -p "${lsc_FDSOutputPath}"
fi
cd "${lsc_FDSOutputPath}"
export OMP_NUM_THREADS=${lsc_FDSChunks}

module load gcc/10.1.0
module load openmpi/4.1.2
module load fds/6.7.7
mpirun -np ${SLURM_JOB_NUM_NODES} fds_mpi_gnu_linux_64 "${lsc_FDSFile}"
exit

Any help is much appreciated.

**Comment by gforney** [comment]
the issue tracker is for posting bugs or making feature requests.  please post this on the fds user forum
