### ISSUE TITLE
how to run fds 6.7 

### ISSUE THREAD

**Issue by AliZebardastinik** [firemodels/fds#10389]
Hello friends

I am going to simulate the following code

&MESH ID='Left', IJK=12,72,36, XB=-2.0,0.0,-6.0,6.0,0.0,6.0, MPI_PROCESS=0, N_THREADS=1 /
&MESH ID='Mesh-a', IJK=90,60,30, XB=0.0,15.0,-5.0,5.0,0.0,5.0, MPI_PROCESS=0, N_THREADS=1 /
&MESH ID='Mesh-b', IJK=114,120,60, XB=15.0,24.5,-5.0,5.0,0.0,5.0, MPI_PROCESS=1, N_THREADS=2 /
&MESH ID='Mesh-c', IJK=114,60,30, XB=24.5,43.5,-5.0,5.0,0.0,5.0, MPI_PROCESS=2, N_THREADS=2 /
&MESH ID='Mesh-d', IJK=102,120,60, XB=43.5,52.0,-5.0,5.0,0.0,5.0, MPI_PROCESS=3, N_THREADS=2 /
&MESH ID='Shaft Mesh', IJK=24,24,12, XB=49.0,51.0,-1.0,1.0,5.0,6.0, MPI_PROCESS=3, N_THREADS=2 /
&MESH ID='Mesh-e', IJK=108,60,30, XB=52.0,70.0,-5.0,5.0,0.0,5.0, MPI_PROCESS=4, N_THREADS=1/
&MESH ID='Right', IJK=12,72,36, XB=70.0,72.0,-6.0,6.0,0.0,6.0, MPI_PROCESS=4 , N_THREADS=1/

But when I run the following command in Windows, It starts simulating with one thread while I want the number of threads to be different.

fds_local -p 5 job.fds

please guide me

Thankful
![1](https://user-images.githubusercontent.com/100993669/158807027-b799b2c6-8db3-48f1-a398-3d2b214f601b.JPG)

**Comment by rmcdermo** [comment]
A question like this should be posted to the [FDS discussion forum](https://groups.google.com/g/fds-smv) *after* you have read the user guide.
