### ISSUE TITLE
long startup time 

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#10407]
There a some users of the level set approach that are looking into its use for training purposes. This can include real time interactions with the model, requiring modification of the input file and restart of the simulation. Recently they have switched from WFDS to FDS and are finding the start up time to be much, potentially prohibitively, longer. For example, based on an input file generated by qgis2fds running LS1 for a 5 km x 5 km domain, 25 m resolution, 1200s simulated time, I get the following for the duration, in seconds, of startup and time stepping

                                         startup          time stepping
FDS using OBST              30                 51
FDS using GEOM             66                 61
WFDS using OBST             5                 25

I've included GEOM just for comparison. This case is somewhat large for a test case, but is something we'd like to be able to handle eventually. With increased spatial resolution, the startup time increases faster than linearly (not shown here). 

Because there's such a large difference between FDS and WFDS, perhaps there are some unneeded variables that are allocated and initialized in FDS? 
Also, for LS1 the 3D terrain is not  needed, except for visualization purposes. 

The link to the input  file (8 MB) for FDS with OBST is
https://drive.google.com/file/d/1FG18j532oEIlQqTtJ_JpToXmy_Sk9o10/view?usp=sharing

**Comment by mcgratta** [comment]
Update and recompile. Things should be faster now. There are two time-consuming things in the start-up. One is assignment of wall boundary conditions, and the second is the search for pressure zones. I eliminated the latter when a level set calc is invoked.

**Comment by ruddymell** [comment]
There's about a 35% reduction in the startup time using OBST for terrain, so it's still taking a long time both for interactive use via restart and compared to wfds.

**Comment by drjfloyd** [comment]
wfds is a decade old now and there have been many 100s of bugs and issues with FDS fixed in that time. Some of those issues have required more global arrays and/or more work to be done initialization. 

By removing pressure zone search from level set have we effectively prohibited any future use of FDS where a level set fire spreads into a building?

**Comment by ruddymell** [comment]
Yes, I include the wfds timings as a reference. It may be that too much change is required for FDS (even with the simplest level set implementation) to be used in the manner described: interactively.  Issue #9856 (particle memory requirements) raises a similar question regarding just how far FDS can go in a new direction without significant code changes.

**Comment by mcgratta** [comment]
Try it again.

**Comment by mcgratta** [comment]
Also, when you try it, add `VERBOSE=T` to the `MISC` line. It will give you timings of the start-up sequence.

**Comment by ruddymell** [comment]
There's now about a 75% reduction in the startup time compared to the original timing. 
Most of the startup time is in INITIALIZE_MESH_VARIABLES_1, with an increasing proportion as the grid resolution increases (95% for the finest grid (6 m) and 50% for the coarsest grid (25m)).
For the coarsest grid, the startup time is 9s, which seems to be getting close to a working solution.
I've asked the person who requested the speedup to test it on their system. I'm not sure what spatial resolution they intend to work with.
