### ISSUE TITLE
Condensation of non Pre-defined species

### ISSUE THREAD

**Issue by Rhodehamei** [firemodels/fds#10402]
Hello, I am trying to model the condensation of custom species. However, when I have a custom species defined, FDS crashes on start of the model. This is the error that I receive when using FDS 6.7.7, "forrtl: severe (157): Program Exception - access violation"

I did some investigating using the examples provided with FDS titled “Condensation_1” and the source code. Condenstaton_1.fds runs without error when the species water vapor is pre-defined as an aerosol. However, if I create a new species with the exact same parameters of water vapor from the source code I get a crash on start.

To summarize, I am using the test example “Condensation_1”, only changing the parameters of the water vapor species. The pre-defined species runs while the custom species does not. This is a bug.
[condensation_1.txt](https://github.com/firemodels/fds/files/8323972/condensation_1.txt)

 

Pre-Defined Water Vapor

&SPEC ID='WATER VAPOR',AEROSOL=.TRUE.,MEAN_DIAMETER=1.E-5,MASS_FRACTION_0=0.01/

 

Custom Water Vapor with values pulled from the source code

&SPEC ID='WATER VAPOR', FORMULA='H2O', AEROSOL=T, BETA_LIQUID=0.000889, CONDUCTIVITY_LIQUID=0.609, DENSITY_LIQUID=1000, ENTHALPY_OF_FORMATION=-241.8, EPSILONKLJ=809.1, HEAT_OF_VAPORIZATION=2500.793, H_V_REFERENCE_TEMPERATURE=0, MELTING_TEMPERATURE=273.15, SIGMALJ=2.641, REFERENCE_ENTHALPY=-13975.84107, PR_GAS=1.0, VAPORIZATION_TEMPERATURE=100, VISCOSITY_LIQUID=0.00089, RAMP_CP='CP_WATER', RAMP_CP_L='CP_L_WATER', RAMP_G_F='GIB_WATER', MEAN_DIAMETER=1.E-5, MASS_FRACTION_0=0.01/

 

&RAMP ID='CP_WATER', T=0.0, F=1.859175679/

&RAMP ID='CP_WATER', T=50, F=1.871314303/

&RAMP ID='CP_WATER', T=75, F=1.879895469/

&RAMP ID='CP_WATER', T=250, F=1.968797253/

&RAMP ID='CP_WATER', T=500, F=2.131046385/

&RAMP ID='CP_WATER', T=726, F=2.291271085/

 

&RAMP ID='CP_L_WATER', T=0.0, F=4.22950259/

&RAMP ID='CP_L_WATER', T=50, F=4.180439739/

&RAMP ID='CP_L_WATER', T=75, F=4.191232228/

&RAMP ID='CP_L_WATER', T=250, F=4.85961911/

&RAMP ID='CP_L_WATER', T=500, F=110.227182/

&RAMP ID='GIB_WATER', T=0.0, F=-[229.4463297](tel:(229)%20446-3297)/

&RAMP ID='GIB_WATER', T=50, F=-[226.9213501](tel:(226)%20921-3501)/

&RAMP ID='GIB_WATER', T=75, F=-[225.6541253](tel:(225)%20654-1253)/

&RAMP ID='GIB_WATER', T=250, F=-[216.6971733](tel:(216)%20697-1733)/

&RAMP ID='GIB_WATER', T=500, F=-[203.6502762](tel:(203)%20650-2762)/

**Comment by drjfloyd** [comment]
Thanks for opening this as an issue.

The error message is resulting from FDS trying to access an unallocated array for the heat of vaporization as a function of temperature. This means the input processing logic is not quite right for this. Should be a fairly simple fix.

**Comment by drjfloyd** [comment]
This should be fixed now in the current source. If you can compile yourself you can try compiling the latest source. If not, then (assuming today's source updates pass Firebot) you can access the nightly builds tomorrow morning here: https://drive.google.com/drive/u/0/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC
