### ISSUE TITLE
HVAC Jet Fan with louver gives only axial flow at outlet

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#10406]
I am testing an HVAC jet fan where the inlet and outlet vents cover only a single cell. The outlet uses a louver 
(UVW=5.7735000E-001,5.7735000E-001,5.7735000E-001). 

When the flow is calculated, there is only an axial velocity and the side velocities appear to be zero. If I use an outlet vent that covers nine cells, then the side velocities are calculated.

Can someone explain more clearly how the velocities are assigned to the HVAC outlet cells? 

Thank you,
Dan Swenson
Thunderhead Engineering

![hvac_single cell](https://user-images.githubusercontent.com/13338306/159761010-27d8c05f-cde6-4f75-bd47-e7aa59d368fd.png)
![only x velocity at outlet](https://user-images.githubusercontent.com/13338306/159761098-4c515b67-2861-469c-bb65-0dd49e47ee6f.png)
![hvac_nine_cell_outlet](https://user-images.githubusercontent.com/13338306/159761117-cd545da7-21d1-42c8-9fd8-1353aa27edc9.png)
![grid cell velocities](https://user-images.githubusercontent.com/13338306/159761134-fe58f05f-859f-4f6b-9f89-3a746401cb13.png)
[hvac_1div.zip](https://github.com/firemodels/fds/files/8335258/hvac_1div.zip)
[hvac_3div.zip](https://github.com/firemodels/fds/files/8335259/hvac_3div.zip)

**Comment by drjfloyd** [comment]
Velocities are stored at cell faces. With only a single cell for your duct you don't have any internal cell edges within the vent area where the tangential flow can be applied.

**Comment by dvswenson** [comment]
Thank you, that explains it.
