### ISSUE TITLE
Shrinking veg

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#10401]
By default FDS invokes shrinking and swelling of all materials. 
For vegetation we'd like to have the capability of no swelling for any material and shrinking only during char oxidation. 
When 
ALLOW_SWELLING=T for all materials and 
ALLOW_SHRINKING = T only for char
the thickness of the particle remains constant at it's original value. 
If ALLOW_SHRINKING for ash is changed to T (with or without char shrinking enabled) the thickness decreases - even though ash is not consumed. 
An image is attached with the thickness versus time from FDS with the default conditions, shrinking enabled for char only, and shrinking enabled for ash only. 
This is for a single cell of vegetation subjected to a heat flux from a hot wall. There's no gas combustion and no gravity. 
![Plot_shrinking](https://user-images.githubusercontent.com/12721870/159369367-8c56e8c9-0c6a-425e-ae4f-99286d0ba5ad.png)
[input_shrinkissue_FDS.txt](https://github.com/firemodels/fds/files/8319438/input_shrinkissue_FDS.txt)

**Comment by ericvmueller** [comment]
Just a thought: one way to alter the behavior could be through the density on the `MATL` lines.
If 20% of the dry vegetation becomes char, but it does not shrink, then the density of the char should be 0.2*514 = 103 kg/m3. The attached plot has default shrinking for all, just the density of char modified.

But I'm not sure about the behavior of the `ALLOW_SHRINKING` flag. I thought it was either all true, or if any component is set to false then there is no shrinking at all ...which doesn't seem like what you've found. I guess Kevin can speak to that.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/13366803/159381168-248ae040-bd42-494b-966f-b082c1bdb76b.png">

**Comment by mcgratta** [comment]
If `ALLOW_SHRINKING=F` for any material component whose density is greater than zero, then shrinking is prevented for the node. Thus, we cannot select certain material components to shrink or not shrink. This means that Eric's suggestion is best -- set the char density appropriately to ensure that the particle does not shrink as cellulose is converted to char.

As for ASH, could you post a case that indicates that the particle still shrinks even when it is all ASH.

**Comment by ruddymell** [comment]
I haven't found shrinking when there's only ash.

I've a attached a better input file. As with the earlier input file, there's only one cell with vegetation, no gas phase combustion, zero gravity, and heating by a hot wall. I've added a wind blowing upward to keep a steady supply of oxygen, resulting in smoother degradation. 

If I understand correctly, there are inconsistent results. Setting ALLOW_SHRINKING=F for any material should prevent shrinking for all materials.  However, using the attached input file with zero moisture and ALLOW_SHRINKING=F for only the dry foliage material (so, no specification for ALLOW_SHRINKING for char and ash materials) FDS does compute shrinking during char oxidation (see Shrink Veg Only figure).

There's also nonphysical behavior when moisture is present. The mass of dry vegetation (total mass - moisture mass - char mass - ash mass) increases during degradation (see figure with 100% moisture, this is the case in the attached input file). Also, there is shrinkage during drying. We'd like to have the option to have shrinkage only during char oxidation.

Both cases described above have the density for char set equal to the char fraction times the dry veg density, as suggested by Eric. This seems to work fine for the 0% moisture case and results in the correct thickness.
[input_shrinkissue2_FDS.txt](https://github.com/firemodels/fds/files/8354052/input_shrinkissue2_FDS.txt)
![Plot_ShnkFonly0M](https://user-images.githubusercontent.com/12721870/160208574-28e60266-7404-4afb-b652-6f6c95f1509f.png)
![Plot_ShkAll100M](https://user-images.githubusercontent.com/12721870/160208589-751970f3-cfda-4d96-86b1-a84cc07bfc07.png)

**Comment by mcgratta** [comment]
`ALLOW_SHRINKING` is invoked in only on place, in wall.f90:
```
      ! If there is any non-shrinking material, the material matrix will remain, and no shrinking is allowed

      MATERIAL_LOOP1b: DO N=1,SF%N_MATL
         IF (ONE_D%MATL_COMP(N)%RHO(I)<=TWO_EPSILON_EB) CYCLE MATERIAL_LOOP1b
         ML  => MATERIAL(SF%MATL_INDEX(N))
         IF (.NOT. ML%ALLOW_SHRINKING) THEN
            REGRID_FACTOR(I) = MAX(REGRID_FACTOR(I),1._EB)
            EXIT MATERIAL_LOOP1b
         ENDIF
      ENDDO MATERIAL_LOOP1b
```
I suspect that when the density of dry vegetation goes to zero, its attribute of `ALLOW_SHRINKING` is no longer applied to the remaining char and ash.

**Comment by ericvmueller** [comment]
I'm not sure where this stands since I was away. But a workaround to the shrinking with moisture is to directly define the `MOISTURE` material with `ALLOW_SHRINKING = F`, and specify the initial mass fraction, rather than using the `MOISTURE_FRACTION` option on `SURF`. This way there is no shrinking allowed until the moisture is gone, then the behavior of the other materials takes over.

As for the mass gain, it appears to be a discrepancy with outputs. If I understand, you are inferring the dry mass from the integral of `MPUV`, and then subtracting the other masses which are output as integrals of `SURFACE DENSITY`. If you output dry mass as a `SURFACE DENSITY` too, there is no mass gain (shown below).
I haven't managed to figure out why the two methods for outputting mass are giving slightly different answers, but I'll let you know if I do.


<img width="325" alt="image" src="https://user-images.githubusercontent.com/13366803/161292157-25a3c229-622c-4c87-8587-71f1b61a9722.png">

**Comment by ericvmueller** [comment]
It looks like `MPUV` output uses `LP%MASS`, which uses the initial `SF%THICKNESS` not the particle-specific radius which can shrink (line 2181 of wall.f90).
On the other hand, the `SURFACE INTEGRAL` output is computed with `ONE_D%AREA`, which is updated as the particle shrinks (line 2094 of wall.f90).

Can you check me on that, @mcgratta? Maybe we need to update how `LP%MASS` is calculated?

**Comment by mcgratta** [comment]
I think LP%MASS is OK. The SF%THICKNESS you see in the expression for it is cancelled out because SF%THICKNESS appears in the denominator of the SURFACE_DENSITY expression.

**Comment by ericvmueller** [comment]
Ah yup, my mistake. My other guess is that `UPDATE_PARTICLES`, where the value for `MPUV` is stored, is called before `WALL_BC`, where the density is updated. So the outputs are offset by a time step and combining them in a calculation (as shown in the graph above) leads to a slight discrepancy.

**Comment by mcgratta** [comment]
What's the status of this issue?

**Comment by ericvmueller** [comment]
My advice is to use `SURFACE_DENSITY` integrals for all mass outputs: both `MATL` specific and total mass. Then there is no chance of getting erroneous values by combining `MPUV` and `SURFACE_DENSITY`. Perhaps we can look at making `MPUV` specific to liquid particles, and then save some memory on vegetation simulations (issue #9856) ...but in the context of this issue I don't think there is anything we need to do.

As far as the original concern about the shrinking behavior ...do the available methods of playing with `ALLOW_SHRINKING` and `DENSITY` values allow you to get the behavior you want, @ruddymell? If so, I think we can close this.

**Comment by ruddymell** [comment]
I think we can close this.
