### ISSUE TITLE
Numerical instability error on a small partial warehouse simulation

### ISSUE THREAD

**Issue by fr-evtech** [firemodels/fds#10416]
Good morning, 
I'm relatively new in the FDS world with just 3 small/medium projects and english is not my native language, so I apologize in advance if the issue could be easily solved and I didn't manage to find it online (user guide, Google group, Github).
I'm currently using Pyrosim to aid me with the coding part of the simulation, which makes use of FDS version 6.7.6.

The simulation I'm currently having issues with is a small part of my first large project, a 30x90x15 m3 warehouse filled cardboard boxes with wooden furniture inside; the reason I opted to try this small scale experiment is to avoid simulation errors as soon as I'll launch the complete one.

As you can see in one of the images attached, the simulation stops because of a numerical instability which I'm quite unsure how to avoid; searching online I found the cause may be high pressure,, small time steps, meshes and so on. Can someone give me an hint? 
Thanks in advance. 

I attach some files, hoping they possibly could be of any help in understanding the problem.
[burner_fastrampup_newHRR_NOSPK.txt](https://github.com/firemodels/fds/files/8379532/burner_fastrampup_newHRR_NOSPK.txt)
[burner_fastrampup_newHRR_NOSPK.out.txt](https://github.com/firemodels/fds/files/8379589/burner_fastrampup_newHRR_NOSPK.out.txt)

![image](https://user-images.githubusercontent.com/102656126/160809453-dcc96142-4173-4984-8517-b49d5d808179.png)
![image](https://user-images.githubusercontent.com/102656126/160809547-d13eb071-1cad-4ab4-b05d-3ea58d35e969.png)

**Comment by mcgratta** [comment]
I am running the case with the latest version of the source code. I suggest that you do the same. Sometimes errors like this get fixed in the latest version. Also, for the case that failed, open Smokeview and load the Plot3D file and toggle through the domain to find where the instability occurs. Sometimes that is a clue to the problem.

**Comment by mcgratta** [comment]
This may or may not be the cause of the instability, but you should change it anyway -- your meshing. When you use multiple meshes, there is some unavoidable numerical error that occurs at the interface between two meshes. In your case, the total area of you mesh interfaces is 261 m2. If you were to stack 6 meshes on top of each other, the interface area would be 124 m2. That is something you should do and see if it fixes the instability.

**Comment by fr-evtech** [comment]
Hello Kevin,
thank you for your time. Unfortunately I'm only familiar with pyrosim and its in-built "result" module, so I'll need more time to understand how smokeview works in the first place, before searching for the instability in the plot3d.
In the meanwhile, I'm going to search if it's possible to make pyrosim work with the latest release of the code, since you mentioned it's not giving you any problem: instead, the one I started 4h ago (after changing the ramp-up time for the HRRPUA) now requires an infinite amount of time already, and the time step is already decreased to 0.3s.

Thanks for the tip about the meshes, I never thought of something like that. May I ask you, how would you deal with something  as big as the whole warehouse? The code is not ready to be launched yet since I'm still testing "small"...

[C1.fds.txt](https://github.com/firemodels/fds/files/8382665/C1.fds.txt)
![image](https://user-images.githubusercontent.com/102656126/160891970-58eade4e-d746-4d0a-a22a-b6fa4ae0bbbd.png)

**Comment by mcgratta** [comment]
The PyroSim viewer should read the Plot3D file as well. Also, I said that I am now running the case. I did not say that I do not have the problem. I will not know until the job crashes or ends.

**Comment by mcgratta** [comment]
Your original case is still running. It is at 630 s now. This is with the latest source code. Try it with the latest release, and also try changing your mesh configuration.

**Comment by fr-evtech** [comment]
I'm currently running it with the mesh configuration you suggested, without cutting the boxes in half obviously, I reached 120s at the moment and the time step is still acceptable.
Regarding the previous message, I opened the .smvv in pyrosim result and the .smv in smokeview but both of them doesn't show any data history in Plot3D (only the last second of simulation), probably because I didn't flag the option in pyrosim

![image](https://user-images.githubusercontent.com/102656126/161060905-b791e76c-c0cf-4408-9965-945a732f149a.png)

I fixed that in the current simulation. Also tried to fetch the FED data since it was flaggable in the menu, but got the error at the start of the simulation since FED is linked to device only (which is quite unfortunate).

![image](https://user-images.githubusercontent.com/102656126/161062266-8662efa1-0e1c-47a3-95ee-5070250bbd3e.png)

Will keep you updated on the outcome.

**Comment by mcgratta** [comment]
FDS automatically dumps a Plot3D file(s) at the last time when a numerical instability occurs. I can't say whether PyroSim recognizes this or not.

**Comment by fr-evtech** [comment]
![image](https://user-images.githubusercontent.com/102656126/161069513-739bcb23-b2f8-48e7-8108-7b6e4940275c.png)

Is this what you were referring to? I really don't know where that high T is coming from though...

**Comment by mcgratta** [comment]
Use the "v" key to show velocity vectors. Then use the arrow keys to move the plane back and forth. Then Show/Hide --> Geometry --> Obstacles --> Hidden to make the boxes invisible.

**Comment by fr-evtech** [comment]
![image](https://user-images.githubusercontent.com/102656126/161079586-1ff5f1a6-7d0b-4315-ba93-d598539f3843.png)

done. in the meanwhile the simulation failed again.

**Comment by rmcdermo** [comment]
Try adding
```
&MISC CHECK_HT=T/
```
You have a low temperature set on the surface of the burner.  This enhances heat transfer and there is a time step constraint that needs to be obeyed for stability.  Even though this may reduce dt slightly, this is much better than an instability or other spurious oscillation that inevitably causes even smaller time steps.

**Comment by fr-evtech** [comment]
Do you mean the surface temperature (0°C)? You are right, but I really don't know what other value should I insert, so I left the default one. Anyway, I added the line you suggested in Misc, is "T" enough or ".TRUE." is needed?

**Comment by rmcdermo** [comment]
For a NAMELIST input file, "T" or ".TRUE." both work.

0 C is not the default, 20 C is.  You do not need to set it.  This is not guaranteed to be the problem, but I often see this crop up with devilish instabilities.

**Comment by fr-evtech** [comment]
![image](https://user-images.githubusercontent.com/102656126/161088721-0daf756e-0df9-48c7-b705-9a83e8d6247d.png)
I swear I didn't touch it, should I change it? I admit the fixed temperature, whatever it may be, is physically impossible. 
Thanks for the clarification and the help!

**Comment by rmcdermo** [comment]
Pyrosim should not be changing TMP_FRONT by default.  The default is 20 C for the surface.

@bryanwklein Please double check this.

Attached is a boundary file for 'WALL TEMPERATURE' for `fds/Verification/Fires/simple_test.fds` where no TMP_FRONT is specified on the SURF line.

<img width="752" alt="Screen Shot 2022-03-31 at 11 40 03 AM" src="https://user-images.githubusercontent.com/4418497/161095085-449a386b-d943-4062-8b38-7de2b71ec126.png">

**Comment by fr-evtech** [comment]
You are actually right, I created a brand new file and the default T of a burner surface is 300°C. I honestly don't recall changing it, but facts say otherwise. 
I launched a new simulation on a different server with all the changes in place, will keep you updated.
Thanks again.

**Comment by rmcdermo** [comment]
300 C?  If you don't touch it, it should be 20 C.

**Comment by fr-evtech** [comment]
I tried again, and I actually figured out what happened:

-if you create a new BURNER surface, the default T is 300°C;

![image](https://user-images.githubusercontent.com/102656126/161101337-ce9fafae-5324-4f74-98ab-3d6870d4f20d.png)

-if you create a new HEATER surface, the default T is TMPA as you said;

![image](https://user-images.githubusercontent.com/102656126/161099900-76aed944-2782-4e51-bbfc-c0c2adda6447.png)

Point is, I originally created a heater surface during the initial stage of my project, then I decided to switch to a burner, and this change automatically caused this:

![image](https://user-images.githubusercontent.com/102656126/161101161-ab95b1b9-fd03-4835-80ea-30b0f4f87676.png)

**Comment by rmcdermo** [comment]
Interesting... well, this is a Pyrosim thing, not an FDS default.  Not that I disagree a higher temperature would occur, which should reduce the heat transfer.  Regardless, `CHECK_HT=T` should account for any necessary time step changes.

**Comment by fr-evtech** [comment]
I can somewhat feel the change, 5s of progress and 48min of elaboration...it hasn't ever been so slow, so far.
Let's hope for the best.

**Comment by mcgratta** [comment]
Did you change your meshing strategy and did you upgrade to the latest version of FDS?

**Comment by fr-evtech** [comment]
About the mesh, yes: 5 meshes, different height (to keep the separation surface away from the boxes).
About the FDS version, no. I will try tomorrow to manually overwrite the original pyrosim files with the ones of the new version, and check if the software works anyway. If so, perfect, otherwise I will simply launch the .fds file with the latest version, outside of pyrosim.
The reason I'm still trying with that is the integrated result output (.smvv), which is kinda better for presentations purpose.

**Comment by mcgratta** [comment]
So you are sticking with a potentially buggy code for presentation purposes? Check with Thunderhead, but there should be a way to integrate a new FDS executable into an existing version of PyroSim.

**Comment by drjfloyd** [comment]
File->Preferences->FDS and change the folder to the FDS executable you wish to use.

**Comment by bwklein** [comment]
You can modify the version of FDS that PyroSim uses. 
https://support.thunderheadeng.com/docs/pyrosim/2021-4/user-manual/#_using_a_different_fds_executable 

As for the starting value of 300 C for burner surfaces. We only do this if the user starts with the surface type 'Burner'. 
https://support.thunderheadeng.com/docs/pyrosim/2021-4/user-manual/#_thermal

If you change from another type to Burner, it looks like we set the value to 0 C on the Thermal tab, I will see why that decision was made and if there is a better approach when changing surface types.

**Comment by bwklein** [comment]
I will note that installing the FDS package from NIST over a PyroSim installation could potentially mess up all of the MPI services and settings that we configure for FDS.  So while it is possible to upgrade, it is not without potential consequences in how the PyroSim data model is rendered to namelist parameters, system environment variable changes, background services, dependent runtime libraries, etc.

**Comment by drjfloyd** [comment]
You can also just export the FDS file and then run FDS from a prompt which should invoke the NIST installed version.

**Comment by fr-evtech** [comment]
Thanks all for your replies. 

> You can also just export the FDS file and then run FDS from a prompt which should invoke the NIST installed version.

That is my "trump card", and will only opt for that if everything else fails. The reason is we don't just need to fetch the variables values from the simulation, but also a good visual representation which pyrosim result and its .smvv file offers.

> File->Preferences->FDS and change the folder to the FDS executable you wish to use.

> You can modify the version of FDS that PyroSim uses. https://support.thunderheadeng.com/docs/pyrosim/2021-4/user-manual/#_using_a_different_fds_executable
> 
> As for the starting value of 300 C for burner surfaces. We only do this if the user starts with the surface type 'Burner'. https://support.thunderheadeng.com/docs/pyrosim/2021-4/user-manual/#_thermal
> 
> If you change from another type to Burner, it looks like we set the value to 0 C on the Thermal tab, I will see why that decision was made and if there is a better approach when changing surface types.

This is what I was looking for, which of course is a better solution instead of manually overwrite the files.

A quick update on the simulation launched yesterday, with revised meshes, burner T and check_ht=T/: the time step is pretty much constant (0,2s), progress 100s out of 1800, time elapsed 17h. I don't think it's going to end soon.

**Comment by mcgratta** [comment]
The `burner_fastramp` case that you attached in your original post ran successfully for me in 5.4 days using the latest source code. I did not change the input file. My advice to you is to use the latest version and change your meshing strategy. Make sure that you do not accidently assign a low temperature to the solids. `CHECK_HT=T` may or may not matter. I suggest you try running without it.

**Comment by fr-evtech** [comment]
On my side the same simulation with updated mesh strategy, a fixed T=300°C on the burner surface and the check_ht=t is still running:
![image](https://user-images.githubusercontent.com/102656126/161779920-911cd0ac-11a7-44d4-b83a-258fd7c9f116.png)

I'm about to kill it since it's really really slow, taking into account the total time interval is only 600s, and launch the one you mentioned.
One question, do you confirm it is advisable to keep the mesh border away from solid object and to not divide them through them? Thinking about the boxes...

**Comment by mcgratta** [comment]
My case ran much faster:
```
 Time Step:  39000, Simulation Time:    423.78 s
 Time Step:  39100, Simulation Time:    424.41 s
 Time Step:  39200, Simulation Time:    425.09 s
 Time Step:  39300, Simulation Time:    425.72 s
 Time Step:  39400, Simulation Time:    426.38 s
 Time Step:  39500, Simulation Time:    427.02 s
 Time Step:  39600, Simulation Time:    427.67 s
 Time Step:  39700, Simulation Time:    428.32 s
```
Try the simulation without `CHECK_HT`.

**Comment by fr-evtech** [comment]
Yep, I supposed it was the reason. Any advice about the other question? Just to be sure the current mesh layout is the best I can fit, even though the number of cells isn't constant (=different elaboration time for every CPU).

**Comment by mcgratta** [comment]
Just try it with an equal partition of meshes. I cannot say for sure which way is better. I typically just divide the domain uniformly using the MULT feature.

**Comment by fr-evtech** [comment]
Got it, thanks.

**Comment by fr-evtech** [comment]
Good morning, unfortunately the simulation failed just a few minutes ago, but this time the issue is different:

![image](https://user-images.githubusercontent.com/102656126/162733914-a28d4a23-e9d5-449a-b68b-470219252e09.png)

Good news, the previous problem regarding numerical instability appear to be solved, thanks to the new mesh configuration and the updated version of FDS, and the time steps remain constant.

**Comment by mcgratta** [comment]
This error message indicates that there was a failure in an MPI exchange related to the pressure solver. This might be caused by something wrong in FDS or something wrong with your cluster, like a temporary glitch on one particular node. How many cores are you using, and what is the size of each mesh?

**Comment by fr-evtech** [comment]
![image](https://user-images.githubusercontent.com/102656126/162749566-692e017d-7af3-4dbd-b15c-3cb671cc5dcc.png)

I was using a core for each mesh, and the meshes are equal to each other.

**Comment by mcgratta** [comment]
OK, could you post the input file of the case that failed. I will run it. You should also run it again. If the case fails at the exact same point, it is probably an FDS problem. If it does not, it might be a computer hiccup.

**Comment by fr-evtech** [comment]
Ok I was planning to do it anyway, since I need to fix some minor outputs and remove some of them I don't need anymore.. As soon as I'm done with the changes I'll upload it here, thanks. By the way, the file I ran is the same one you already did yourself, so it may have been a PC performance issue.

**Comment by mcgratta** [comment]
Are you running the case on a single Windows computer?

**Comment by fr-evtech** [comment]
Currently yes. As I mentioned at the beginning, this simulation is just a small part of a large project, therefore I'm running it on my personal machine. The whole project is going to be run on a cloud server service instead, like we did for all the previous ones.

**Comment by fr-evtech** [comment]
Hi all, my boss allowed me to run the simulation on the cloud service we usually use, and it worked like a charm.
Changing meshes and fds version did the trick apparently, thanks for pointing it out.
I know I'm still a newbie in this world, but I'm looking forward to improve.
Thanks again for your help!

**Comment by mcgratta** [comment]
Good to hear and thanks for reaching out. As you can imagine the size and scope of these calculations are ever increasing and we need these real examples to make the software more robust. I will close this issue, but feel free to open a new one should other problems arise.
