### ISSUE TITLE
Apparent issue with UGLMAT and CYLINDRICAL with mesh division in X (radial)

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10427]
The attached case gives incorrect results if there is a mesh subdivision in x (radial direction).  Probably need to fix for ULMAT as well.

[test.fds.txt](https://github.com/firemodels/fds/files/8413026/test.fds.txt)

**Comment by marcosvanella** [comment]
Update your repo and try again.

**Comment by rmcdermo** [comment]
Seems to be working great.  Thanks!
