### ISSUE TITLE
Particle-Gas Momentum Transfer

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10433]
This issue is related to this [Discussion thread](https://groups.google.com/g/fds-smv/c/KBfvoxH51gM).

In the following case, solid droplets of density 1000 kg/m3 and diameter of 1 mm are dropped from rest at a rate of 190 particles per second. In Smokeview, the velocity vectors of the air point upwards instead of down; that is, the expected downward dragging of air is upwards instead.
```
&HEAD CHID='particle_momentum_transfer' /
&MESH IJK=21,21,100, XB=-0.2,0.2,-0.2,0.2,0,2 /
&TIME T_END=10, DT=0.005 /
&MISC NOISE=.FALSE. /
&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&RADI RADIATION=.FALSE./
&MATL ID='stuff', DENSITY=1000, SPECIFIC_HEAT=1., CONDUCTIVITY=0.1 /
&SURF ID='ball', MATL_ID='stuff', GEOMETRY='SPHERICAL', THICKNESS=0.0005 /
&PART ID='DROPLET', SURF_ID='ball', SAMPLING_FACTOR=1 /
&INIT N_PARTICLES=1, XYZ=0.0,0.0,1.91, UVW=0.0,0.0,0.0, MASS_PER_TIME=1.0E-04, DT_INSERT=0.005, PART_ID='DROPLET' /
&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=T /
&DEVC ID='mass', QUANTITY='MPUA', PART_ID='DROPLET', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=-0.2,0.2,-0.2,0.2,0.0,0.1 /
&TAIL /
```

**Comment by mcgratta** [comment]
I just committed the fix. The trick to understanding it is to recognize that if there is no drag on the particles, there should be no momentum transfer to the gas via `LP%ACCEL_Z`.

**Comment by ericvmueller** [comment]
Nice. Should it also be `DT_P` instead of `DT` to account for possible subdivision of time steps?

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
Yup. `DT_P` is appropriate within the big particle loop.

**Comment by rmcdermo** [comment]
Neither terminal_velocity nor flat_fire seem to be upset by the change.  But I suggest we add this new example as another verification case.
