### ISSUE TITLE
MLR in _hrr file not output for VEL-based SURF

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10441]
Just noticed that if we use, say, `VEL=-0.1, MASS_FRACTION=1`, on a `SURF` line for fuel we do not get MLR output in the _hrr file.  Here is an example.  I dialed back to 6.7.7 and seems to be there as well.  I'm in the middle of modifying the _hrr file, so I'll work on this.

[test.fds.txt](https://github.com/firemodels/fds/files/8454075/test.fds.txt)

**Comment by mcgratta** [comment]
You want to populate `ONE_D%M_DOT_G_PP_ACTUAL(N)` at boundary cells with VEL and MASS_FRACTION.
```
WALL_LOOP2: DO IW=1,N_EXTERNAL_WALL_CELLS+N_INTERNAL_WALL_CELLS
   WC => WALL(IW)
   IF (WC%BOUNDARY_TYPE/=SOLID_BOUNDARY) CYCLE WALL_LOOP2
   ONE_D => BOUNDARY_ONE_D(WC%OD_INDEX)
   DO N=1,N_TRACKED_SPECIES
      M_DOT(N,NM) = M_DOT(N,NM) + ONE_D%M_DOT_G_PP_ACTUAL(N)*ONE_D%AREA*ONE_D%AREA_ADJUST
   ENDDO
ENDDO WALL_LOOP2
```

**Comment by rmcdermo** [comment]
This should be fixe with PR #10443
