### ISSUE TITLE
Temperature decreases when coupling pyrolysis with internal heat

### ISSUE THREAD

**Issue by JenSpille** [firemodels/fds#10449]
Hi everyone,

I am performing simulations on electrical cable fires and ran into an issue when coupling pyrolysis and an internal heat source. 

I tried to simplify the problem using the attached input file. A cable is represented as particle with three layers (Jacket, Insulation and Copper). Jacket and Insulation are  materials with pyrolyis reactions. The cable is heated by a constant internal heat source of 10000 kW/m³ placed in the copper layer. 

When we take a look onto the temperatures in the middle of each layer, we can see that the temperatures decrease after 440 s. This leads to a very small mass loss rate.

![image](https://user-images.githubusercontent.com/47566821/162681490-8283475e-dccb-4ae4-9334-0f9a6b5465d2.png)
![image](https://user-images.githubusercontent.com/47566821/162682256-78e963af-32d6-42c9-a067-d8987f282ac1.png)

Running the file with FDS version 6.6, the temperatures constantly increase and the peak of mass loss rate is higher by a factor of 3. 

![image](https://user-images.githubusercontent.com/47566821/162682061-1b2950b9-a255-4557-8d7e-dc178892adb7.png)

![image](https://user-images.githubusercontent.com/47566821/162682103-42acc369-0a6f-4850-9e19-27c53b0efdfd.png)

I took a look on several older version of the code and found that in wall.f90

IF (SF%SPECIFIED_HEAT_SOURCE) THEN
   DO I=1,NWP
      Q_S(I) = Q_S(I)+SF%INTERNAL_HEAT_SOURCE(**LAYER_INDEX(I)**)
   ENDDO
ENDIF

was changed to

IF (SF%SPECIFIED_HEAT_SOURCE) THEN
   DO I=1,NWP
      Q_S(I) = Q_S(I)+SF%INTERNAL_HEAT_SOURCE(**SF%LAYER_INDEX(I)**)
   ENDDO
ENDIF

in version 6.7.4.

I am not familiar with FORTRAN., but after I changed to the previous formulation, the issue is fixed.
[testcase_internal_heat_pyrolysis.fds.txt](https://github.com/firemodels/fds/files/8461708/testcase_internal_heat_pyrolysis.fds.txt)

**Comment by drjfloyd** [comment]
Good catch. This should be LAYER_INDEX which accounts for wall nodes disappearing due to pyrolysis rather than SF%LAYER_INDEX which is the initial definition of a wall cell.

**Comment by drjfloyd** [comment]
This should be fixed now. Since it seems like you can compile yourself, you can pull the new source.

There were a couple of other spots where we were using SF%LAYER_INDEX where we shouldn't have been that are also fixed.

**Comment by JenSpille** [comment]
> There were a couple of other spots where we were using SF%LAYER_INDEX where we shouldn't have been that are also fixed.

Thanks for your quick reply. I just compiled the fds-master using Intel compiler and did some test cases. So far it works fine for me. So I think we could close this issue.
