### ISSUE TITLE
Pressure iteration stalls at door opening

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10456]
@mcgratta See if you have any luck with this.  It is a simple compartment with a door that opens midway through the simulation.  The pressure error stalls out at about 1e-4 with the devc activation.   The error is 1e-10 if you just have an OPEN door without removal of the obstruction.  This behavior happens with thin or 1 cell thick OBST.

Might have something to do with flow reversal.

Might have something to do with location of `CALL CREATE_OR_REMOVE_OBSTRUCTIONS`.  I moved this to the top of PREDICTOR and this resolved the initial error (viewed with PRESSURE POISSON RESIDUAL) but ultimately did not resolve the issue of the iteration stalling out.

[opening.fds.txt](https://github.com/firemodels/fds/files/8476444/opening.fds.txt)

**Comment by mcgratta** [comment]
Should be fixed. Double check it. It was related to flow reversal and inconsistent boundary values for H and P.

**Comment by rmcdermo** [comment]
Looks great on all my test cases.  Thanks!
