### ISSUE TITLE
Integrated quantities over multiple meshes gives inconsistent results 

### ISSUE THREAD

**Issue by uporersith** [firemodels/fds#10473]
Using FDS version 6.7.7

Setup an XB plane to measure 'MASS FRACTION' with and without SPATIAL_STATISTIC, see the last six DEVC lines of the attached file.

Ran 3 cases with 1, 2 and 4 meshes, just subdividing the domain.

I expect all three cases to give the same 'MASS FRACTION' values no matter how many meshes there are. instead, I get different values depending on how many meshes the domain has been subdivided into.

I tested using a block as well to see how the DEVC deals with OBSTS in the DEVC plane, and I get wildly different results.  (see line 20 of the attached file) 

a summary of my results is attached as the xlsx file.

[surf_mass_part_specified_summary.xlsx](https://github.com/firemodels/fds/files/8496174/surf_mass_part_specified_summary.xlsx)

[surf_mass_part_specified.txt](https://github.com/firemodels/fds/files/8496137/surf_mass_part_specified.txt)

**Comment by rmcdermo** [comment]
The main issue with this case seems to be that the second set of DEVC are specified by a plane with XB.  If XYZ=0,0,2.5 is used then the results look much better.  See attached.  I still do not see machine precision similarity between the two cases, even I use:

```
&MISC NOISE=F/
&PRES SOLVER='UGLMAT'/
&RADI RADIATION=F/
```

Looking at the .out files, the only difference I see is that in the 4 mesh case, the center point of the DEVC has been shifted, presumably to move it off the mesh boundary.  This seems to be causing slight differences in the output.

[devc_values.pdf](https://github.com/firemodels/fds/files/8496730/devc_values.pdf)

**Comment by mcgratta** [comment]
I see the same thing. If I integrate each species over the entire domain, the results are very close. When the particle is placed at the boundary, FDS has to choose to move it into the nearest cell. In this case, each neighboring cell is equally close, and when the mesh boundary is to the left or right, FDS moves the particle the other way. So I don't see any problems here. Keep in mind that multiple mesh cases will not be exactly the same as single mesh. But in this case, things are fairly close.
