### ISSUE TITLE
To download the FDS version 5.5.2.

### ISSUE THREAD

**Issue by andeferson** [firemodels/fds#10470]
Dear,
I used to perform fire simulations in a previous version of FDS (5.5.2), however my computer was damaged, such version cannot be found at the website to download anymore and my FDS code are not totally compatible with the current ones.
Please, would it be possible to make the download link available (or, if necessary, a file that I could compile) in order to reinstall in another computer?
Thank you in advance.

Best Regards,

**Comment by rmcdermo** [comment]
https://github.com/firemodels/fds/releases/tag/Git
