### ISSUE TITLE
Solid-phase devices reposition issue

### ISSUE THREAD

**Issue by fr-evtech** [firemodels/fds#10485]
Hi all,
sorry to trouble you again (so soon).
I ran into an error as soon as I launched the simulation for the whole big project, tried to solve it at least 4-5 times without success, so I decided to replicate it on a small scale so you can look over it easily.

Apparently FDS cannot determine which boundary cell to assign the reposition of some solid-phase devices, I know (google is my friend)  that it's a quite common error and the solution is very well explained in paragraph 19.1 of the FDS User's Guide; still, I didn't manage to make it work.

As you can see in the following image, I put the solid-phase devices very very close (5 cm away) to the racks vertical supports to check the wall temperature reached during the fire.

![image](https://user-images.githubusercontent.com/102656126/164229201-d235c795-cc04-4d18-9230-cd5eb0900fd9.png)

The single cell sizes are 0.2x0.2x0.2 m, and the devices aren't near the meshes' border.
If I run it, FDS fails to locate the closest surface to the devices n. 4 and 8, just the two of them; BUT, if I modify the position of the aforementioned devices and put them directly ON the obstruction surface, the simulation runs without issues.
May I ask what is it that I'm missing?
In the end I replaced the solid phase devices with the gas phase ones and I'll settle for the temperature instead of the wall temperature, because modifying the position of all the 100+ devices one-by-one would be an high time consuming (not to mention trial and error) process, but I still would like to understand what is wrong for future projects.

[test_small_solid_devc.txt](https://github.com/firemodels/fds/files/8521413/test_small_solid_devc.txt)

Thanks in advance to anyone who will use his time to help me!

**Comment by mcgratta** [comment]
Here is the geometry you input, looking in the -x direction

![image](https://user-images.githubusercontent.com/11333911/164248938-d4b2a783-b90a-487c-8334-dfe211cea17f.png)

and here is how FDS "snaps" the geometry to the grid:

![image (1)](https://user-images.githubusercontent.com/11333911/164249192-9dd7012a-20dd-4306-86e0-1dbeea556ff8.png)

The green dots represent devices 4 and 8:

&DEVC ID='SOLID04', QUANTITY='WALL TEMPERATURE', XYZ=6.75,2.35,0.75, IOR=-1/
&DEVC ID='SOLID08', QUANTITY='WALL TEMPERATURE', XYZ=6.75,2.35,1.95,
IOR=-1/'

The fact that I can see these dots means that even in the original geometry
your devices were not oriented with a solid surface.

**Comment by mcgratta** [comment]
Thunderhead -- it would be a nice feature, if it's not there already, to
check that solid surface devices are properly pointing at solid surfaces,
even when the obstructions are snapped to the grid. FDS cannot figure this
out until it has read and processed all the obstructions and devices.

**Comment by mcgratta** [comment]
Also, it would be nice, if it's not there already, to include an isometric
view option to more easily identify where various devices are located.

**Comment by fr-evtech** [comment]
Good day Kevin,
thanks for your reply, unfortunately I can't see the images you posted in the first comment, hence why I didn't understand what I did wrong, is it related to IOR? I checked that value at least 3 times...

**Comment by mcgratta** [comment]
Can you see them now?

**Comment by fr-evtech** [comment]
Yes, thanks. I clearly see the issue know, the vertical support is literally not there anymore. I suppose for some reason FDS snapped  the supports of the right rack in the next cell, in the +x direction, while the ones of the left racks are in the correct place. Is there a way to force the software snapping, or the only solution is to use a finer mesh?

**Comment by mcgratta** [comment]
Finer mesh if you want to input the obstructions as is. Or you can modify your obstructions to fit the existing coarse mesh.

**Comment by drjfloyd** [comment]
In Pyrosim you can toggle a view that shows the FDS geometry by selecting Preview FDS Blocks in the menu bar.  

![image](https://user-images.githubusercontent.com/12799217/164259251-62c881a6-5f9b-433c-bf5d-b7548feb2ae0.png)

You can also just run FDS setting the end time to 0 (T_END=0 on &TIME or the End Time in Analysis->Simulation Parameters in Pyrosim). When you do this FDS just writes out the Smokeview file. Even for a very large case this only takes a few seconds, and then you can look to see how OBST and DEVC have snapped to the grid. At that point as Kevin notes you can either change the mesh or modify the OBST.

**Comment by fr-evtech** [comment]
Thanks for the tip Jason. 
By the way, the second solution is something you can easily implement in a small scenario, but in a bigger one, where I often opt to use a coarser mesh as I get away from the burner like in the image below, it's a quite long process.

![image](https://user-images.githubusercontent.com/102656126/164265167-35e3e351-3202-4b09-80a4-f3ab01b6bf12.png)

At the same time using a finer mesh results in longer computing times, which is the opposite I'm trying to achieve increasing the cells size while getting away from the fire.
I suppose there isn't a quick wordaround, well at least now a know what caused the problem.
Thanks.

**Comment by mcgratta** [comment]
Why don't you just add this line
```
&BNDF QUANTITY='WALL TEMPERATURE' /
```
This will show you graphically what the temperature is.

**Comment by fr-evtech** [comment]
I did that already, but the rack designer asked for a value as accurate as possible so I decided to also put a device in the spots where he wanted to gather information from. I will try to manually calculate the heat transfer from the T obtained through the gas phase devices.
