### ISSUE TITLE
Boundary condition problem when using INTERNAL_HEAT_SOURCE in FDS6.7.7

### ISSUE THREAD

**Issue by gf901103** [firemodels/fds#10497]
Hello Everyone,
I am simulating the overloaded thin wire under high current by using the function of INTERNAL_HEAT_SOURCE in &SURF line in FDS 6.7.7. 
I found that the thermal boundary condition of the layered solid surface becomes different with previous version FDS6.7.0. After applying the internal heat on the inner layer (core wire), the outer layer (polymer insulation) is in pyrolysis until it is used up. After the outer layer disappeared, the exposed surface should be the inner layer, and the temperature should rise continuously. This process is fine in FDS6.7.0. However, in FDS6.7.7, the internal heat source stoped after the outer layer was used up. 
I attached the example of the input file (_IntHeat.fds_), and the simulation results (2 figures) of solid and gas temp on the surface of the solid calcualted by FDS6.7.0 and FDS6.7.7. 
[IntHeat.fds.txt](https://github.com/firemodels/fds/files/8554140/IntHeat.fds.txt)
![Temp-t(FDS6 7 7)](https://user-images.githubusercontent.com/67189851/165082006-28b84f06-1727-4c6a-84d7-03e482e5c612.jpg)
![Temp-t(FDS6 7 0)](https://user-images.githubusercontent.com/67189851/165082021-27ba5902-d039-4af8-aacb-42a03259d13f.jpg)

I have made some trials for troubleshooting. I guess in the FDS 6.7.7, the INTERNAL_HEAT_SOURCE in &SURF line Mismatched with the corresponding layer after the outer layer burnt away. My hypothesis is like the following schematic.
![image](https://user-images.githubusercontent.com/67189851/165082678-6885ece2-a90b-42c1-86c3-f1447613de3e.png)
When I revise the &SURF line by adding an additional ultra thin-layer with same INTERNAL_HEAT_SOURCE between the original two layers, it seems to be working as I expected. The revised input file is attached as well (_IntHeat_R.fds_).
[IntHeat_R.fds.txt](https://github.com/firemodels/fds/files/8554281/IntHeat_R.fds.txt)

Could you helps to check this issue?
Thanks in advance for your suggestions!
Best regards,
Feng

**Comment by drjfloyd** [comment]
I think we recently fixed this bug. In https://github.com/firemodels/fds/commit/a813b19dea4d17aa1d069f6b1544e11a6104a5c9 we fixed a bug where we weren't always pointing to the correct layer for INTERNAL_HEAT_SOURCE when layers disappear.  I'll check.

**Comment by drjfloyd** [comment]
Looks like it has been fixed.  If you want, you can try using the latest nightly build of FDS: https://drive.google.com/drive/u/0/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC

Note that in the next release of FDS the PCR option for MATL has been removed. So you will need to change your melt reaction to use REFERENCE_TEMPERATURE and PYROLYSIS_RANGE.  Set REFERENCE_TEMPERATURE to the melting temperature. For a phase change reaction, something around 5 K should be good for PYROLYSIS_RANGE. 

&MATL ID='PE',
      SPECIFIC_HEAT=2.3,
      CONDUCTIVITY=0.34,
      DENSITY=920.0,
      EMISSIVITY=0.3,
      N_REACTIONS=1,
      HEAT_OF_REACTION=140,
      MATL_ID(1,1)='moltenPE',
      NU_MATL(1,1)=1.0,
      REFERENCE_TEMPERATURE=120.0,
     PYROLYSIS_RANGE=5./

**Comment by gf901103** [comment]
Hello Jason,
Thank you very much for your prompt response!
It helps a lot! I will try the lasted version according to your suggestion!
