### ISSUE TITLE
Boolean input on MISC line not detected

### ISSUE THREAD

**Issue by azr3475** [firemodels/fds#10504]
Hi there,
I have an issue with boolean variables on the misc-line. They somehow are not detected by FDS. For example:
&MISC VISIBILITY_FACTOR = 8, MAXIMUM_VISIBILITY = 30, BNDF_DEFAULT= F/		
The first two variables are detected correctly, but boundary files are still created. Even worst, when I change 'F' to any random string, no error whatsoever is given. This looks very much like a bug.

**Comment by azr3475** [comment]
FYI, i have:  Revision         : FDS6.7.7-0-gfe0d4ef38-release
 Revision Date    : Thu Nov 18 17:10:22 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Fri 11/19/2021  08:57 AM

**Comment by rmcdermo** [comment]
Please submit a minimal working example that we can test.

**Comment by azr3475** [comment]
[model.txt](https://github.com/firemodels/fds/files/8563638/model.txt)

**Comment by mcgratta** [comment]
I am running this case on a linux computer. When I run this case, I do not see any boundary files (.bf) files created. When I change 
```
BNDF_DEFAULT=GRED
```
I get an error. Before I try this on a Windows computer, remove all the tab stops from your file. They are all over the place, and my guess is that they are corrupting the input lines.

**Comment by azr3475** [comment]
Hi Kevin, The tab stops come from the fact that i create my files in Excel and then copy them to notepad. I've worked this way for years, so it shouldn't be a problem, but I will check.

**Comment by mcgratta** [comment]
"I've worked this way for years, so it shouldn't be a problem..."

Spend a day with me and I'll disabuse you of this notion. I'll check your file on my Windows computer, but regardless of what I find, you should not introduce any spurious characters into your input file. You cannot assume that Excel, FDS, Notepad, or any other software you use is not going to change some imperceptible convention like a tab stop or line ending character.

**Comment by azr3475** [comment]
Thanks. I removed the tabstops, but it does not seem to make any difference (see attachement, with a little more simplifications).
[model.txt](https://github.com/firemodels/fds/files/8564052/model.txt)

**Comment by mcgratta** [comment]
I am running the case now on my Windows computer. I think you are referring to files with the suffix `.bnd`. These are not boundary files. They are "bounds" files used be Smokeview to determine the range of values with which to establish a color bar. `BNDF_DEFAULT=F` tells FDS to tell Smokeview not to color solid surfaces by default. Since you have no `BNDF` lines and no `.bf` output files, this input parameter is moot.

Also, when I change `F` to a random character string, I get an error and the execution stops.

**Comment by azr3475** [comment]
You were right concerning my confusion between BND and BNDF files. Concerning the random string, it seems to be my string was not random enough. I typed e.g. BNDF_DEFAULT=Tsdsds, which does not give an error, but BNDF_DEFAULT=X does give an error. So it seems only the first character is detected and the rest is neglected, which makes sense for a boolean... :S. So in the end a matter of confusion.. but thanks for your time.
