### ISSUE TITLE
Default value for LOSS parameter on HVAC

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10505]
The `LOSS `parameter default value is given as `1` in the **Localized Leakage** chapter but `0` in the **table 22.11**. 
Thanks.

![image](https://user-images.githubusercontent.com/26166281/165303533-c5e08cff-efd6-4e33-b1d8-9e64eeaa2e74.png)

![image](https://user-images.githubusercontent.com/26166281/165303657-3b32fab5-d0fb-44c3-b17b-1c9ec42e0b33.png)

**Comment by drjfloyd** [comment]
The manual is correct.

For a duct or node associated with an HVAC system, the default loss is 0.  FDS does not make any assumptions on what the losses are for an HVAC system. 

Leakage is different. Leakage uses the HVAC solver as it is the same fundamental equation, but the standard process via which one measures leakage assumes a loss of 1. For leakage you can chose to override this and specify your own loss - DISCHARGE_COEFFIICENT for ZONE leakage or LOSS for localized leakage (i.e., &HVAC TYPE_ID='LEAK').

**Comment by Er9y714** [comment]
Thank you very much for the clarification !
