### ISSUE TITLE
Burning duration seems too short

### ISSUE THREAD

**Issue by ChrisDagenais** [firemodels/fds#10511]
I am trying to replicate the cone calorimeter to validate input properties for FDS modeling. I am using RAMP values for the HRR matching that of actual cone tests, as well as the CONE_HEAT_FLUX function. I tried 2 scenarios and obtained quite different results.
1) use BURN_AWAY='TRUE' and BULK_DENSITY=540
2) use BURN_AWAY='FALSE' and BULK_DENSITY=540
In both scenarios, the SURF thickness is set to 0.025 (25 mm) and the OBST has also a thickness of 0.025 (in Z direction).
In Scenario 1, once a given cell/mesh is consumed (density * mesh volume), the HRR goes back up as if it would see a fresh new cell/mesh (seems to redo the RAMP values for the subsequent meshes) It burns for slightly more than 1800 s, which seem correct when compared to test data (except for the various peaks).

In Scenario 2, the HRR follows the same initial trend as Scenario 1, but decays/stops shortly after the time where the 1st meshes were consumed in Scenario 1.

I would have expected Scenario 2 to follow the RAMP values until the full thickness of 0.025 is consumed, but apparently not.

Based on recommendations obtained on the Google forum, I then tried simulating the specimen using a simple VENT rather than an OBST. I however get the exact same results as Scenario 2.

When calculating the mass loss from the MLR_REAC_FUEL, only 29 g seems burned while the specimen is set to be 25 mm thick and 100 x 100 area (volume of 0.00025 m3). Density of MATL is set to 540 kg/m3 so that would translate to a total potential mass of 135 g. The 29 g represents about only 21%. I would expect a longer burning duration and that all mass be consumed given the radiant heat is never stopped (similar to Scenario 1 where cells are being consumed one by one). I understand that this approach will not captured the 2nd peak in HRR towards the end of a typical cone calorimeter test. I am quite comfortable with this.

I am attaching the FDS file (in TXT). I understand that modeling the actual conical shape significantly increases the computational time...but graphically/visually more interesting for students!
[ConeCal_Debug.txt](https://github.com/firemodels/fds/files/8565459/ConeCal_Debug.txt)

Thanks.

**Comment by mcgratta** [comment]
You are mixing up too many different modes of operation here. On the one hand you want solid fuel to burn away, but on the other you have just specified a HRRPUA. I suggest you look at the [FAA Polymer cases](https://github.com/firemodels/fds/tree/master/Validation/FAA_Polymers/FDS_Input_Files) to better understand how to simulate a cone calorimeter.

**Comment by ChrisDagenais** [comment]
Thanks I will review the FAA document.
I initially tried to use the burn away but then again, this is not needed. Which is why I think not using it would be best and therefore using HRRPUA seemed correct. But why is a given SURF does not burn entirely?

**Comment by mcgratta** [comment]
In your case, you have VENTs and OBSTs piled on top of each other, and that is not how FDS works. Typically you give kinetic parameters on the MATL line and  THICKNESS on the SURF line, and then FDS computes the heat transfer and solid phase reactions. When you use HRRPUA, that is a completely different way of doing things. It is like you have just put a gas burner on top of the stack. Often these different modes of operation do not work well together.

**Comment by ChrisDagenais** [comment]
I realize that typically the kinetic should be assigned in the MATL properties. In this simplified case here, I am following the approach that Thunderhead Engineering is promoting (and widely used out there) where an item is represented with given HRRPUA on its surfaces.
When attempting to validate my model, I did tried only assigning the HRRPUA to the SURF of my OBST (no VENT). I also tried assining the HRRPUA to a VENT (no more OBST). I got the same results. The HRR goes down by itself.
If I do a parallel analogy using a VENT to represent a burner, that VENT provides a given HRR indefinitely, unless a specific RAMP value sets it down to 0 at a given time.
The issue I have now is that when doing the same method (assign a HRRPUA to a VENT or SURF), why is my "burner" stopping after a while? I have not set a RAMP value to turn it down, so it's suppose to keep emitting HRR.

**Comment by mcgratta** [comment]
I suggest you create a simple version of the case. Remove the cone completely and just add EXTERNAL_FLUX=65 to the SURF line that defines the specimen. Use a grid resolution of 1 cm. It is difficult for me to diagnose your problem with such a big case that takes a long time to run.

**Comment by mcgratta** [comment]
The problem here is that you have put the VENT called 'SpecimenSurface' on top of the OBST called 'SpecimanVolume', The OBST is then given a SURF_ID of 'Insulation'. FDS is taking the mass of the insulation rather than the wood to calculate the burn time. This is not the only problem, but it explains why the burning stops. 

My advice is to either use the specified burning model or a pyrolysis model. When the two are combined, you can get strange results.
