### ISSUE TITLE
2D cylindrical vs. 3D radiation different time behavior

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#10522]
The two attached cases are a domain with open sides. One case is 3D and the other is 2D cylindrical. The 3D case is 1/4 symmetry; there is no flow. At the top is a 1000 C hot ring. Two devices measure radiative flux: one device is at the bottom center looking up (V devices in the plot) and the other is at the top pointing radially outward (R devices in the plot).  As seen in the plot, the end values of the 2D and 3D cases are similar. I don't expect an exact match.  However, the time dependence is very different. The 3D case immediately shows the steady-state results. The 2D case takes 4 s for the radial and 10 s for the vertical gauge which are ~100 and 300 time steps.

![image](https://user-images.githubusercontent.com/12799217/165768823-2b01e6eb-32c3-486e-a59d-126526b62c5d.png)

[3d_test.txt](https://github.com/firemodels/fds/files/8583371/3d_test.txt)
[2d_test.txt](https://github.com/firemodels/fds/files/8583372/2d_test.txt)

**Comment by mcgratta** [comment]
We run a full pressure solve in the first time step, which would explain the 3D results. Not sure about the 2D. I'll check.

**Comment by drjfloyd** [comment]
That could be part of.  I did just try setting TIME_STEP_INCREMENT=1 and ANGLE_INCREMENT=1 which should force everything to update in a timestep. It still took 10 to 30 timesteps to reach steady state.

**Comment by mcgratta** [comment]
Setting `CYLINDRICAL=F' removes the ramp up, but I need to figure out what is different about cylindrical.

**Comment by mcgratta** [comment]
I'm stumped. It is clearly related to the CYLINDRICAL geometry, but I don't understand why that would cause the ramp up. I'll ask SImo.

**Comment by shostikk** [comment]
Yes, cylindrical solver copies intensities from angle to angle, and nay cause this.  Would require iterations to avoid, similar to reflective boundaries.

Never seen effect this strong.  High NRA will suffer more than low.

**Comment by rmcdermo** [comment]
Can we add the iterations as an option?  I'm trying to run a cup burner case in 2D cylindrical and predict heptane MLR.  I'm off by a factor of more than 2.

**Comment by mcgratta** [comment]
There are already two parameters that might help. `INITIAL_RADIATION_ITERATIONS` and `RADIATION_ITERATIONS`.

**Comment by drjfloyd** [comment]
RADIATION_ITERATIONS does help with this.  The NRA=1000 I had put in to reduce any effect of the number of angles when comparing 2D and 3D.  With the default 100 angles and a few iterations the number of timesteps needed drops down to 15.

**Comment by rmcdermo** [comment]
Jason, thanks for this.  But can you please clarify the recommended inputs for the 2D CYLINDRICAL caes?

NRA=1000
RADIATION_ITERATIONS=?

**Comment by mcgratta** [comment]
In general, 2D simulations require less angles because you are only spanning the vertical angles. If you want to compare with a 3D simulation with the default 100 angles, I suspect you need about 20. 100 should be plenty.

**Comment by drjfloyd** [comment]
Good point Kevin.

Randy, 

With NRA=1000 for the 2D case it took 316 iterations.  RADIATION_ITERATIONS=2 was 154 iterations.

With the default 64 angles for 2D it was 40 for R_I=1, 16 for RI=2, and 8 for RI=3. Going from R_I=1 to R_I=3 a little more than doubled the cost of the radiation solver.

**Comment by shostikk** [comment]
Thanks Jason, very nice to see the ITERATIONS can mitigate this problem.
I assume we can close this.
