### ISSUE TITLE
Unstable tunnel runs - multi-mesh with preconditioner and internal obstructions

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#10535]
Problems with multiple meshes on a tunnel simulation, preconditioner, etc.

In short – if there are internal obstacles to map out a tunnel cross sectional profile (e.g., arched), then the model goes unstable for a case with no fire present. Some specifics provided below by way of an example and some results.

Ran this on FDS6.7.7-0-gfe0d4ef38-release and have also tested on the most recent nightly release (FDS6.7.7-933-gaa3296d1b-nightly) with no difference. The grid change in X goes from 0.3 to 0.6 m (which is a big jump, but it is usually ok or at least stable) at the mesh interface in question (x=439) but given this works ok for models with no internal profile obstructions, I am not sure this is really the problem. Any thoughts as to what is going on here?

Here are some results, etc. Start with a basic model, just a long box, no obstructions except for a couple of small internal objects:

&HEAD CHID='z-generic',TITLE='generic' /

&SLCF PBY = 0.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /

&SLCF PBY = 0.0, QUANTITY='PRESSURE' /

&TIME T_BEGIN = 0.0, T_END=1200.0 /

&PRES TUNNEL_PRECONDITIONER=.TRUE. /

&MATL ID            = 'CONCRETE'

      SPECIFIC_HEAT = 1.20   

      DENSITY       = 2000.0

      EMISSIVITY    = 0.9

      CONDUCTIVITY  = 1.2 /

&SURF ID          = 'TUNNEL_WALL'

      MATL_ID     = 'CONCRETE'

      TEXTURE_MAP = 'wallfinish.jpg'     

      BACKING     = 'INSULATED'

      THICKNESS   = 0.6

      DEFAULT     = .TRUE. /

&SURF ID          = 'CAR'

      COLOR       = 'ORCHID'

       MATL_ID    = 'CONCRETE'

      TEXTURE_MAP = 'wallfinish.jpg'     

      BACKING     = 'INSULATED'

      THICKNESS   = 0.6 /

&MESH IJK=230,59,23,XB=0,138,-8.7,9,0,6.9, MPI_PROCESS=0 /

&MESH IJK=237,59,23,XB=138,280.2,-8.7,9,0,6.9, MPI_PROCESS=1 /

&MESH IJK=270,59,23,XB=280.2,361.2,-8.7,9,0,6.9, MPI_PROCESS=2 /

&MESH IJK=262,59,23,XB=361.2,439.8,-8.7,9,0,6.9, MPI_PROCESS=3 /

&MESH IJK=267,59,23,XB=439.8,600.0,-8.7,9,0,6.9, MPI_PROCESS=4 /

&OBST XB=288.6,293.1,0.6,2.4,0.6,2.1,RGB=403,842,813,SURF_ID='CAR' / 215

&OBST XB=300,306,-1.8,1.8,0.0,0.3,SURF_ID = 'CAR' /

&SURF ID='SP1',VEL=-3.0008,RAMP_V='VENTR_SP1'/

&VENT XB=0, 0,-8.7,9,0,6.9,SURF_ID='SP1' /

&RAMP ID='VENTR_SP1',T=0,F=1.0/                           

&RAMP ID='VENTR_SP1',T=30,F=1.0 /

&RAMP ID='VENTR_SP1',T=90,F=0.98 /

&RAMP ID='VENTR_SP1',T=3600,F=0.98 /

&VENT XB=600.0, 600.0,-8.7,9,0,6.9,SURF_ID='OPEN' /

Model runs ok, velocity field downstream of the obstructions (placed at around x=300) at the interface between grids at x = 439.8 per Fig 1 (grid goes from 0.3 m in x to 0.6 m in x here, doing this to keep cell counts to something manageable and refine the grid in area of interest). See Fig 1 attached.

 

Now, include obstructions are included to map out a circular arch as follows, see Fig 2 attached and lines below.

&OBST XB=0, 600.0,-8.7,-7.8,0,0.9, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,-8.7,-8.1,0.9,2.7, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,-8.7,-8.4,2.7,4.8, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,-8.7,-8.4,4.8,5.7, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,-8.7,-7.5,5.7,6, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,-8.7,-7.2,6,6.3, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,-8.7,-6.6,6.3,6.9, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,7.8,9,0,1.5, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,8.1,9,1.5,2.7, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,8.1,9,2.7,3.9, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,8.7,9,3.9,5.7, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,7.8,9,5.7,6, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,7.2,9,6,6.3, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

&OBST XB=0, 600.0,6.9,9,6.3,6.9, SURF_ID='TUNNEL_WALL', EVACUATION=.FALSE. /

Resultant velocity field downstream of the obstructions, at around x = 439.8 as per Fig 3 attached.

The model did not go unstable, but based on the contour of velocity above, the solution is clearly non-physical and would likely go unstable.

I tested several different settings here, such as removal of the preconditioner, and other more stringent converge criteria for the Poisson solver but no major change in behavior (if anything, when tolerances were made tighter the simulation went unstable sooner):

&PRES TUNNEL_PRECONDITIONER=.TRUE., VELOCITY_TOLERANCE=0.01, MAX_PRESSURE_ITERATIONS=50, SUSPEND_PRESSURE_ITERATIONS=.FALSE., CHECK_POISSON=.TRUE.

![Fig1](https://user-images.githubusercontent.com/15055988/165955520-a498d775-5273-4f2b-b4b5-c3d1145c07c2.png)
![Fig2](https://user-images.githubusercontent.com/15055988/165955537-ab70713a-a640-4384-bd51-500fa8462df7.png)
![Fig3](https://user-images.githubusercontent.com/15055988/165955556-127dade1-0ade-4e61-90f6-86cfaf16f44f.png)

It is a strange issue - weird things at the interface, which I admit is a big jump in x grid resolution and not great (but sometimes necessary to keep things at a manageable run time). But the fact that removing the perimeter OBSTs makes the problem go away is what caused me concern. Tweaking settings like turning off tunnel preconditioner or keeping pressure iterations at 25 has helped, but this is a bit weird too because it is in the opposite direction of what should help.

**Comment by mcgratta** [comment]
I haven't found the root cause of the instability, but I did try running the case with the tunnels walls converted into thin obstructions. That is, there is a hollow plenum at the sides of the tunnel with air flowing through at the same velocity as the main tunnel. This jibes with the idea of solving a 1-D pressure equation. I am now trying this idea with an actual fire.

**Comment by mcgratta** [comment]
I put a fire in the tunnel with thin, curved walls and it seems to be running OK. This is not a perfect solution, but might get you by until a more permanent fix can be found.

**Comment by mattbilson76** [comment]
We had a run a fire model on something like the setup I provided above. Those models were also going unstable. The grid interface seems to be the issue - when I move the 0.3 m to 0.6 m interface then the behavior moves to that location. I will try it a bit on some different grids to see what happens.

**Comment by mcgratta** [comment]
Did you try the thin tunnel walls?

**Comment by mattbilson76** [comment]
I ran with thin walls, and the run seemed to go ok. I made the walls very simple though and there was no flow through the space. What's the idea here/why should this work as opposed to solid obstructions?

I also ran a case with solid obstructions and preconditioner turned off, and this seemed to work, which was counter to what I would have expected.

**Comment by mcgratta** [comment]
The preconditioner is based on the assumption that the flow is nearly one dimensional and uniform across the cross section of the tunnel. We average lateral data and calculate a 1D flow. With the thin walls, we still have a flow over the entire cross section. With solid walls, we are somewhat violating the basic premise of the 1D average.
