### ISSUE TITLE
Ctrl and Obst creation

### ISSUE THREAD

**Issue by MSalisbury** [firemodels/fds#10536]
I had great success with adding and removing blockages back in FDS 6.7.5 using pressure differential sensors :)

Something new in the subsequent versions isn't removing the obstruction from the domain correctly in my view.   Oddly smokeview shows it being removed, but the pressure tells otherwise...

The examples below is simply a door being opened when pressure differential across the door 'pulls' it open.  (i have heavy simplified this case, but it worked before with the actual door swings).

Would be great if you could please compare the results between the case below using current and previous (FDS 6.7.5) and let me know if its just me or something has changed in the source.  

Cheers

Matt 

&TIME T_END=100.0/
&DUMP COLUMN_DUMP_LIMIT=.TRUE., DT_SL3D=0.25/

&MESH ID='Lift Lobby Stair', IJK=12,18,10, XB=0.0,3.0,0.0,4.68,0.0,2.5/
&MESH ID='Corridor', IJK=12,6,10, XB=0.0,3.0,-1.5,0.0,0.0,2.5/

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1/

&SURF ID='Extract',
      RGB=255,51,153,
      VOLUME_FLOW=4.5,
      TAU_V=-5.0/

&OBST ID='Swing_01Closed', XB=1.0,2.0,0.0,0.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_01'/ 
&OBST ID='Obstruction', XB=0.0,1.0,0.0,0.26,0.0,2.5/ 
&OBST ID='Obstruction', XB=2.0,3.0,0.0,0.26,0.0,2.5/ 
&OBST ID='Obstruction', XB=1.0,2.0,0.0,0.26,2.0,2.5/ 

&VENT ID='Mesh Vent: Corridor [ZMIN]', SURF_ID='OPEN', XB=0.0,3.0,-1.5,0.0,0.0,0.0/ 
&VENT ID='ExtractFan', SURF_ID='Extract', XB=3.0,3.0,3.4,4.4,2.0,2.5, RGB=182,240,94/ 

&SLCF QUANTITY='PRESSURE', PBZ=1.5/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=1.5/

&DEVC ID='Temperature_MEAN', QUANTITY='TEMPERATURE', SPATIAL_STATISTIC='MEAN', XB=1.25,2.125,3.15,3.65,1.5,1.7/
&DEVC ID='Visibility_MEAN', QUANTITY='VISIBILITY', SPATIAL_STATISTIC='MEAN', XB=1.25,2.125,3.15,3.65,1.5,1.7/
&DEVC ID='PressureExtractSide_MEAN', QUANTITY='PRESSURE', SPATIAL_STATISTIC='MEAN', XB=0.75,1.25,0.78,1.56,1.0,2.0/
&DEVC ID='PressureSupplySide_MEAN', QUANTITY='PRESSURE', SPATIAL_STATISTIC='MEAN', XB=1.75,2.25,-0.75,-0.25,1.0,2.0/

&CTRL ID='Pa_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='PressureSupplySide_MEAN','PressureExtractSide_MEAN', SETPOINT = 0, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=1,  LATCH=.FALSE. /
&CTRL ID='Pa_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='PressureSupplySide_MEAN','PressureExtractSide_MEAN', SETPOINT = 10, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_01',FUNCTION_TYPE='ALL',INPUT_ID='Pa_Lower','Pa_Upper',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&TAIL /

**Comment by drjfloyd** [comment]
I'll take a look

**Comment by drjfloyd** [comment]
It looks like it is working as it should with FDS 6.7.7.  At t=0 the the pressure is just slightly negative so Pa _Lower evaluates to F which means the initial state is kept and the output is F. Pa_Upper is less than 10 which means the function evaluates to T which means the initial state is flipped and the output is T.  Pa_L is F and PA_U is T so DW_01 evaluates to F which means its output is F and the door keeps its original state of F.  Immediately the fan causes a pressure drop which puts the dP between 0 and 10. Now Pa_Lower evaluates to T which means the initial state flips to T. Pa_Upper is still less than 10 so it keeps its T.  Now DW_01 is T and the door closes. Quickly the pressure rises above 10 Pa.  Pa_Upper now evaluates to F and the initial state is kept making the output F.  With PA_L=T and PA_U=F, DW_01 goes back to F and the door opens.  The pressure now drops (there is an assumed pressure relaxation time in FDS) and at some point the dP drops below 10 but above 0. The door closes again.  Pressure spikes back up, the door opens. The cycle keeps repeating. 

![image](https://user-images.githubusercontent.com/12799217/166073644-7034ba6f-406d-4549-a99c-f6613e25c6b9.png)

What is the behavior you are looking to have?

**Comment by MSalisbury** [comment]
Hi Jason, many thanks for looking at this and yes looks like my error.  I tried to simplify some old input files and for whatever reason i couldnt get it to work.   Anyway i went back to my original code and yes it works.  See below 'simple' example ;).

Many thanks for all your work on FDS and response.   Its much appreciated.

Kind regards

Matt.


-------------User Section (not generated by PyroSim)-------------

&DEVC ID='TIME', QUANTITY='TIME', XYZ=6,11,2, SETPOINT=0.0/

'Corridor door 0.0 / Door Not Available, i.e. door OFF (door in Open position)
&RAMP ID='FFAccess_RAMP', T=0, F=1.0/ Door Available, i.e. door ON (door in closed position)
&RAMP ID='FFAccess_RAMP', T=120, F=1.0/
&RAMP ID='FFAccess_RAMP', T=121, F=0.0/
&RAMP ID='FFAccess_RAMP', T=180, F=0.0/
&RAMP ID='FFAccess_RAMP', T=181, F=1.0/
&RAMP ID='FFAccess_RAMP', T=460, F=1.0/
&RAMP ID='FFAccess_RAMP', T=461, F=1.0/
&RAMP ID='FFAccess_RAMP', T=600, F=1.0/
&RAMP ID='FFAccess_RAMP', T=601, F=0.0/
&RAMP ID='FFAccess_RAMP', T=611, F=0.0/
&RAMP ID='FFAccess_RAMP', T=612, F=0.0/
&RAMP ID='FFAccess_RAMP', T=925, F=0.0/
&RAMP ID='FFAccess_RAMP', T=926, F=0.0/

&CTRL ID='FFAccess', FUNCTION_TYPE='CUSTOM', RAMP_ID='FFAccess_RAMP', LATCH=.FALSE., INPUT_ID='TIME'/

		Door Area	1.6	m2	
Door	Angle	N (BS 8300‑2:2018 )	Pa (N/m2)	FDS Pa differential	
1	6.44	30		0	
2	15.30	30		4	
3	23.17	30		6	
4	32.65	30	18.75	8	
5	42.94	22.5		10	
6	51.45	22.5		12	
7	60.25	22.5	14.06	14	
8	66.40	15	9.38	18	More than 60deg therefore not relevant to BS 8300
9	76.28	15	9.38	20	
10	84.14	15	9.38	22	
11	90.45	15	9.38	24	


Door swing (DW)
&CTRL ID='Pa_DS_01_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -10000, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1,  LATCH=.FALSE.  /
&CTRL ID='Pa_DS_01_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -4, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE.  /
&CTRL ID='DW_01',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_01_Lower','Pa_DS_01_Upper', 'FFAccess' INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_02_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -4, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_02_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -6, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_02',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_02_Lower','Pa_DS_02_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_03_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -6, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_03_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -8, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_03',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_03_Lower','Pa_DS_03_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_04_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -8, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_04_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -10, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_04',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_04_Lower','Pa_DS_04_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_05_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -10, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_05_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -12, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_05',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_05_Lower','Pa_DS_05_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_06_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -12, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_06_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -14, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_06',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_06_Lower','Pa_DS_06_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_07_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -14, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_07_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -16, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_07',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_07_Lower','Pa_DS_07_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_08_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -16, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_08_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -18, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_08',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_08_Lower','Pa_DS_08_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_09_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -18, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_09_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -20, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_09',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_09_Lower','Pa_DS_09_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_10_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -20, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_10_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -22, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_10',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_10_Lower','Pa_DS_10_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_11_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -22, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_11_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -24, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_11',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_11_Lower','Pa_DS_11_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /

&CTRL ID='Pa_DS_12_Lower', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -24, INITIAL_STATE=.FALSE.,TRIP_DIRECTION=-1,  LATCH=.FALSE. /
&CTRL ID='Pa_DS_12_Upper', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN', SETPOINT = -10000, INITIAL_STATE=.TRUE.,TRIP_DIRECTION=-1, LATCH=.FALSE. /
&CTRL ID='DW_12',FUNCTION_TYPE='ALL',INPUT_ID='Pa_DS_12_Lower','Pa_DS_12_Upper', 'FFAccess',INITIAL_STATE=.FALSE., LATCH=.FALSE. /




--------------------PyroSim-generated Section--------------------

&HEAD CHID='NIST_Ctrl_FAULT_2', TITLE='Design Fire with door response'/
&TIME T_END=1200.0/
&DUMP COLUMN_DUMP_LIMIT=.TRUE., DT_SL3D=0.25/

&MESH ID='MESH', IJK=30,20,28, XB=5.0,8.0,8.0,10.0,0.0,2.8/
&MESH ID='MESH01', IJK=30,16,28, XB=5.0,8.0,10.0,11.6,0.0,2.8/


&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1/

&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      DEFAULT=.TRUE.,
      ADIABATIC=.TRUE./
&SURF ID='Extract',
      RGB=255,51,153,
      VOLUME_FLOW=5.5,
      TAU_V=-5.0/

&OBST ID='Swing_12Open', XB=7.021047,7.121047,9.973029,10.873029,-3.38618E-15,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_12'/ 
&OBST ID='Swing_01Closed', XB=6.121047,7.121047,9.973029,10.073029,1.665335E-16,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_01'/ 
&OBST ID='Obstruction', XB=5.0,8.0,9.9,10.0,0.0,2.8/ 
&OBST ID='Swing_11', XB=7.0,7.1,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_11'/ 
&OBST ID='Swing_11', XB=6.9,7.0,10.6,10.9,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_11'/ 
&OBST ID='Swing_11', XB=7.0,7.1,10.0,10.6,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_11'/ 
&OBST ID='Swing_10', XB=7.0,7.1,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_10'/ 
&OBST ID='Swing_10', XB=6.8,6.9,10.7,10.9,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_10'/ 
&OBST ID='Swing_10', XB=6.8,7.0,10.6,10.7,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_10'/ 
&OBST ID='Swing_10', XB=6.9,7.0,10.3,10.6,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_10'/ 
&OBST ID='Swing_10', XB=7.0,7.1,10.0,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_10'/ 
&OBST ID='Swing_09', XB=7.0,7.1,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_09', XB=6.7,6.8,10.7,10.8,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_09', XB=6.7,6.9,10.6,10.7,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_09', XB=6.8,6.9,10.4,10.6,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_09', XB=6.9,7.0,10.2,10.4,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_09', XB=6.9,7.1,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_09', XB=7.0,7.1,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_09'/ 
&OBST ID='Swing_08', XB=7.0,7.1,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_08', XB=6.6,6.7,10.6,10.8,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_08', XB=6.7,6.8,10.5,10.6,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_08', XB=6.7,6.9,10.4,10.5,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_08', XB=6.8,6.9,10.3,10.4,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_08', XB=6.9,7.0,10.1,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_08', XB=7.0,7.1,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_08'/ 
&OBST ID='Swing_07', XB=7.0,7.1,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=6.5,6.6,10.6,10.7,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=6.6,6.7,10.5,10.6,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=6.6,6.8,10.4,10.5,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=6.7,6.8,10.3,10.4,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=6.8,6.9,10.2,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=6.9,7.0,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_07', XB=7.0,7.1,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_07'/ 
&OBST ID='Swing_06', XB=6.4,6.5,10.5,10.6,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_06'/ 
&OBST ID='Swing_06', XB=6.5,6.6,10.4,10.5,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_06'/ 
&OBST ID='Swing_06', XB=6.6,6.8,10.3,10.4,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_06'/ 
&OBST ID='Swing_06', XB=6.7,6.9,10.2,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_06'/ 
&OBST ID='Swing_06', XB=6.8,7.0,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_06'/ 
&OBST ID='Swing_06', XB=6.9,7.1,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_06'/ 
&OBST ID='Swing_05', XB=6.3,6.4,10.4,10.5,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_05'/ 
&OBST ID='Swing_05', XB=6.4,6.6,10.3,10.4,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_05'/ 
&OBST ID='Swing_05', XB=6.6,6.8,10.2,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_05'/ 
&OBST ID='Swing_05', XB=6.7,6.9,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_05'/ 
&OBST ID='Swing_05', XB=6.9,7.1,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_05'/ 
&OBST ID='Swing_04', XB=6.2,6.4,10.3,10.4,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_04'/ 
&OBST ID='Swing_04', XB=6.3,6.6,10.2,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_04'/ 
&OBST ID='Swing_04', XB=6.6,6.9,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_04'/ 
&OBST ID='Swing_04', XB=6.8,7.1,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_04'/ 
&OBST ID='Swing_03', XB=6.9,7.0,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_03'/ 
&OBST ID='Swing_03', XB=6.1,6.3,10.2,10.3,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_03'/ 
&OBST ID='Swing_03', XB=6.3,6.7,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_03'/ 
&OBST ID='Swing_03', XB=6.7,7.0,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_03'/ 
&OBST ID='Swing_02', XB=6.8,7.0,10.0,10.0,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_02'/ 
&OBST ID='Swing_02', XB=6.1,6.3,10.1,10.2,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_02'/ 
&OBST ID='Swing_02', XB=6.3,7.0,10.0,10.1,0.0,2.0, RGB=204,255,204, PERMIT_HOLE=.FALSE., SURF_ID='INERT', CTRL_ID='DW_02'/ 

&HOLE ID='StairDoor', XB=6.1,6.996521,9.7,10.666418,-0.01,2.0/ 

&VENT ID='AOV Inlet', SURF_ID='OPEN', XB=5.862431,7.362431,7.970345,8.970345,2.8,2.8/ 
&VENT ID='Extract', SURF_ID='Extract', XB=5.2,6.15,10.85,11.4,2.8,2.8/ 

&BNDF QUANTITY='GAS TEMPERATURE'/
&BNDF QUANTITY='NET HEAT FLUX'/
&BNDF QUANTITY='RADIATIVE HEAT FLUX'/
&BNDF QUANTITY='WALL TEMPERATURE'/

&ISOF QUANTITY='TEMPERATURE', VALUE=60.0,100.0/
&ISOF QUANTITY='VISIBILITY', VALUE=5.0,10.0/
&ISOF QUANTITY='PRESSURE', VALUE=5.0,25.0,50.0/
&ISOF QUANTITY='VELOCITY', VALUE=5.0/

&SLCF QUANTITY='PRESSURE', PBZ=1.5/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., CELL_CENTERED=.TRUE., PBZ=1.5/

&DEVC ID='Pressure Lobby_MEAN', QUANTITY='PRESSURE', SPATIAL_STATISTIC='MEAN', XB=5.2,6.325,10.7,11.2,1.0,2.0, SMOOTHING_FACTOR=0.5/
&DEVC ID='Pressure Stair_MEAN', QUANTITY='PRESSURE', SPATIAL_STATISTIC='MEAN', XB=6.35,6.725,9.15,9.775,1.0,2.0, SMOOTHING_FACTOR=0.5/


&TAIL /

**Comment by drjfloyd** [comment]
Since your pressure intervals are the same width, here is another approach that I think should work and would reduce somewhat the number of control functions. Delta P is computed once. For DW 01 if delta P is less than 4 the door is closed. For DW 02, substract 2 from the delta P and then use a CUSTOM control where values between 0 and 2 are true. So if delta P is between 2 and 4, the input to the CUSTOM is between 0 and 2.  For DW 02, subtract 4, and so on up until DW 12 where we just care that the pressure is larger than 24.  This goes form 36 to 23 control functions plus a short ramp.

&RAMP ID='Interval',T=-1,F=-1/
&RAMP ID='Interval',T=1,F=1/
&RAMP ID='Interval',T=3,F=-1/

&CTRL ID='delta P', FUNCTION_TYPE='SUBTRACT', INPUT_ID='Pressure Lobby_MEAN','Pressure Stair_MEAN'/

&CTRL ID='DW 01',FUNCTION_TYPE='SUM',INPUT_ID='delta P','CONSTANT',CONSTANT=0,SETPOINT=4,TRIP_DIRECTION=-1/

&CTRL ID='delta P 2',FUNCTION_TYPE='SUBTRACT',INPUT_ID='delta P','CONSTANT',CONSTANT=2/
&CTRL ID='DW 02',FUNCTION_TYPE='CUSTOM',RAMP_ID='Interval',INPUT_ID='delta P 2',INITIAL_STATE=F/

&CTRL ID='delta P 3',FUNCTION_TYPE='SUBTRACT',INPUT_ID='delta P','CONSTANT',CONSTANT=4/
&CTRL ID='DW 03',FUNCTION_TYPE='CUSTOM',RAMP_ID='Interval',INPUT_ID='delta P 3',INITIAL_STATE=F/

.....

&CTRL ID='DW 12',FUNCTION_TYPE='SUM',INPUT_ID='delta P','CONSTANT',CONSTANT=0,SETPOINT=24/

**Comment by MSalisbury** [comment]
Thanks Jason.  That’s clear.  I’ll give that a try.

Cheers

Matt.

Matt Salisbury
BEng CEng MIFireE MSFPE
fire engineer – director
Salisburyfire Ltd.

m. 07718 646 241
Email: ***@***.******@***.***>
www.salisburyfire.co.uk<http://www.salisburyfire.co.uk/>
***@***.***

**Comment by MSalisbury** [comment]
Thanks again Jason.  Just reviewing now.  I’ll let you know outcome.

Cheers

Matt.

Matt Salisbury
BEng CEng MIFireE MSFPE
fire engineer – director
Salisburyfire Ltd.

m. 07718 646 241
Email: ***@***.******@***.***>
www.salisburyfire.co.uk<http://www.salisburyfire.co.uk/>
***@***.***
