### ISSUE TITLE
Bulk Density and Combustible Mass Issue

### ISSUE THREAD

**Issue by jutrasi** [firemodels/fds#10544]
Hi,
I am running into an issue with the Bulk_Density parameter and the amount of combustible mass that is determined. I have reproduced my issue using the box_burn_away1.fds example case and looking at the methane mass in the mass output file . The only changes made were to the bulk density, surface thickness, and run time. As per the user guide, if bulk density is prescribed it should override all other ways that combustible mass is determined. This appears not always to be the case. I ran a set of cases which is summarized below.
 
![image](https://user-images.githubusercontent.com/41330584/166504345-9601363a-999c-4d96-a5fb-73dc6754801d.png)

It seems that if the bulk density-based mass is less than the minimum value of either the surface density-based mass or the Matl density* volume-based mass, the bulk density mass is used. However, if the bulk density-based mass is greater, the combustible mass is somewhere in between those values. I believe this could be a bug unless bulk density was only intended to work for cases where the bulk density is less than the two other calculated mass values. Thank you for your help.

**Comment by drjfloyd** [comment]
Each wall cell has its own independent mass loss calculation.  For a given wall cell the mass loss for that wall cell cannot exceed the mass specified via the SURF.  Once you have pyrolyzed the available mass for a wall cell based on the SURF, there is no more mass available for that cell to be put into the domain. BULK_DENSITY is there to account for the fact that a grid cell may have more than one exposed wall cell that is burning. In this case, if both wall cells were allowed to emit the entire amount of mass specified on SURF, they could emit more mass than is actually present in the OBST.  To have a case where you can never reach the BULK_DENSITY, I think implies that the SURF isn't appropriately defined.

**Comment by jutrasi** [comment]
Thanks for the quick reply and the clarification. It seems like I was attempting to use BULK_DENSITY in a way that it wasn’t intended.  In my original case, I was using BULK _DENSITY as a way to compensate for a complex fuel package arrangement involving a series of thin materials. My thought was I could get the benefit of the thinner material for heat transfer/ignition reasons and then use BULK_DENSITY to determine the total mass that is being consumed. Knowing that this was not its intended use, I will take a different approach.
