### ISSUE TITLE
Numerical instability (Min density clip) - boundary fuel model + GEOM terrain

### ISSUE THREAD

**Issue by FlatbushWombiez** [firemodels/fds#10568]
Hi,

(Originally posted in Google Discussion Group)

I'm getting numerical instability at time step 261 in this case using the boundary fuel model. The terrain and input file are generated using qgis2fds and edited with blender2fds. The location of the instability is showing a large velocity value and is around a vortex. 
![Screenshot 2022-05-09 212552](https://user-images.githubusercontent.com/105246937/167497866-63be36d3-3c00-428a-bf59-da41996f64ad.png)

I've tried extending the z height of the domain as the soot was reaching the top of the domain. I've also changed the CLIP_DT_RESTRICTIONS_MAX using values from 0 to 20. Baroclinic vorticity has been disabled as it was leading to large errors in the pressure. The velocity tolerance is increased to 1m/s as the pressure solver was being maxed out at 100 iterations. 

I have previously attempted to run this simulation using a level set calculation and also experienced minimum density clipping. I would prefer to use a boundary fuel model as it is more physical anyway.
[updated.txt](https://github.com/firemodels/fds/files/8655429/updated.txt)

**Comment by FlatbushWombiez** [comment]
https://drive.google.com/drive/folders/1DTUOE5EcthKmPZ-oCCWa_P09-TG2PEzI?usp=sharing

Google drive with terrain file.

**Comment by FlatbushWombiez** [comment]
Also attempted to run with the UGLMAT solver to see if that helped. Still getting the same instability.

**Comment by marcosvanella** [comment]
Hi Kareem I'm running your case with and without ignition to see if this issue is related to issues  #9819 #10117. We are reformulating the treatment of geometries to deal with these numerical instabilities. For the time being, export and run your case in OBST mode. See the thread #9819 on how to export the terrain as obstacles within qgis2fds.

**Comment by FlatbushWombiez** [comment]
Thank you for your help.

I have run the simulation with OBST however due to the very steep terrain the resolution of the OBSTs is not sufficient to accurately represent the flow field (it becomes steps instead of sloping terrain). The vorticity is what would like to examine further and even with a 3m grid resolution (~10 million cells), I'm unable to accomplish this with OBSTs.

**Comment by marcosvanella** [comment]
What is the size of the obstacles you get?

**Comment by FlatbushWombiez** [comment]
Same as mesh resolution so 3m. Perhaps also limited by the digital elevation model resolution from QGIS which is also 3m (at maximum settings).

**Comment by emanuelegissi** [comment]
The next qgis2fds release is going to support DEM interpolation. So you can
reduce the size of your obstacles.

Here are the instructions if you want to test the development version:
https://github.com/firetools/qgis2fds/wiki/Installing#install-a-live-development-version

**Comment by FlatbushWombiez** [comment]
Thank you, Emanuel.

I've regenerated the case with a 1m resolution with DEM interpolation. Looks much better, will give it a run now.

**Comment by emanuelegissi** [comment]
Great!

**Comment by marcosvanella** [comment]
Changed the meshes to a 4 by 3 mesh problem (45x40x110 cells each), same resolution. Not seeing instability with latest source after 1K steps. Closing.
<img width="955" alt="Screenshot 2023-04-20 at 3 02 04 PM" src="https://user-images.githubusercontent.com/7450069/233464579-58546d89-7bd7-4dd9-bf9a-3dbf2ec4f1b3.png">
