### ISSUE TITLE
SMV Results looking weird

### ISSUE THREAD

**Issue by t-paw** [firemodels/fds#10564]
Hi all, I have a case where the model successfully completes the simulation using FDS 6.7.7.
Model was being initiated in the cloud using restart function on a non-regular instance. 
Non-regular instances will reboot the machines at random times where if there is any simulation running, it will be re-initiated at the last saved restart file. 

Problem encountered, SMV results downloaded seems to be 'broken'. Refer screenshots. 
<img width="845" alt="Capture 1" src="https://user-images.githubusercontent.com/105222990/167434935-a48fad79-f714-4bb9-b500-86058545b24a.PNG">
![Capture 5](https://user-images.githubusercontent.com/105222990/167436084-a0709001-946d-4227-bdda-467320904942.jpg)

Opening using Pyrosim Result Viewer, the soot density loads with some irregular view. Slice files could not be loaded. Every time the slice file is being loaded, Pyrosim automatically closes. 

Opening using Smokeview, the soot density loads with some irregular view. Slice files could be loaded but seems to be 'broken'. Every time the slice file is being unloaded, Smokeview automatically closes. 

Have anyone encountered issues like this?

Simplified input file, 
[FS_L10_E187_1MW_FF_Debug.txt](https://github.com/firemodels/fds/files/8652649/FS_L10_E187_1MW_FF_Debug.txt)

**Comment by mcgratta** [comment]
```
ERROR: CONTROL stair door does not exist (CHID: FS_L10_E187_1MW_FF)
```

**Comment by t-paw** [comment]
Apologies, I have accidentally deleted the control inputs. 

You may use this one instead:
[FS_L10_E187_1MW_FF_Debug_2.txt](https://github.com/firemodels/fds/files/8652913/FS_L10_E187_1MW_FF_Debug_2.txt)

**Comment by mcgratta** [comment]
At what time did you restart the case?

**Comment by t-paw** [comment]
Restart file intervals at 40s.

**Case initiated at May  6, 2022  15:24:23
Time Step:      1, Simulation Time:      0.02 s**

...continues until

 -> simulation in progress ... wait please [Sat May  7 15:15:43 UTC 2022]
 Time Step:  47100, Simulation Time:    273.66 s
 Time Step:  47200, Simulation Time:    274.18 s
    -> simulation in progress ... wait please [Sat May  7 15:26:29 UTC 2022]
   -> instance status: status: TERMINATED
   -> grep script end:
   -> duration: 1444 m 54 s
   -> date: Sat May  7 15:28:21 UTC 2022
   -> instance restart [n. 1]

...restarts 1 time...
...from last restart file at 240s...

**Current Date     : May  7, 2022  15:34:02
Time Step:  40700, Simulation Time:    240.16 s**

...continues until

Time Step:  71238, Simulation Time:    400.00 s

**STOP: FDS completed successfully (CHID: FS_L10_E187_1MW_FF)**
   -> instance status: status: RUNNING
   -> grep script end:   END.txt
   -> duration: 901 m 48 s
   -> date: Sun May  8 06:34:47 UTC 2022

**Comment by mcgratta** [comment]
I ran the case until 291 s. I stopped it, and then restarted. I have not seen odd behavior in the Smokeview renderings. I suggest two courses of action:

1. Run the case again and see if the strange behavior is repeatable.
2. Download the latest test version of FDS from [here](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC).

**Comment by t-paw** [comment]
Okay, thank you for the update Kevin.
