### ISSUE TITLE
Complex geometry simulation fails running- forrtl: severe (157): Program Exception - access violation

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#10569]
As part of a summer internship, my goal is to import complex geometries from BlenderFDS to FDS. In this example case, I chose to take a part of a drug stores, in which a fire sets up from a cylinder. The case may be weird but it is only a training case, the objective is to master the process on a "simple geometry". 

[drug.txt](https://github.com/firemodels/fds/files/8661946/drug.txt)

There are multiple obstacles in this geometry, imported as GEOM and not OBST because they are slightly inclined compared to the coordinate system. I have already tried to simulate the cylinder in fire in a smaller environnement, and it worked properly. The behaviour of the smoke in the duct is not important, the objective is to observe the smoke density in the building. I have separed the whole domain in 4 meshes running on 3 cores, with a more precise mesh around the duct. 

![domains](https://user-images.githubusercontent.com/94290527/167639507-5e58a49a-00f8-467c-9b08-8f8029f45f08.PNG)
![geometry_mesh](https://user-images.githubusercontent.com/94290527/167639510-78eb26bb-e87e-414a-ac00-98ef5bb0067f.PNG)

My problem is that when the geometry becomes too much complex, and the .fds file becomes to heavy, FDS is unable to start the simulation. I have tried many changes in order to simplify the geometry file, but it fails everytime with the following error : 
forrtl: severe (157): Program Exception - access violation 

![cmd](https://user-images.githubusercontent.com/94290527/167639541-f078fa8c-dc1e-4d78-8169-edbcff4e3384.PNG)

I'd be glad if someone has encountered the same problem and knows how to solve it, thank you for your time !

PS : I did not know if I should talk about it in a FDS or a BlenderFDS Github so sorry if I am not at the right place.

**Comment by ghost** [comment]
Here are my specs : 

Intel Xeon CPU E3-1230 v6 @ 3.50GHz
64 Go RAM
Running on Windows 10 Pro

**Comment by mcgratta** [comment]
We'll take a look at this. Note that the complex geometry is still a work in progress, but these bugs help things along.

**Comment by ghost** [comment]
Appreciate, do not hesitate to ask for more information.

**Comment by marcosvanella** [comment]
Hi Vianey, I'm testing the case in one of our clusters. I would split your domain in more meshes. You have one mesh with 3 million cells. As a rule of thumb you want to keep you meshes on the order of 300K cells. Try a case with same meshes and half the cells in each direction and post it back here.

**Comment by rmcdermo** [comment]
Also, there should be an option in BlenderFDS to export the geometry as a binary file, which can then be read by FDS using something like:

```
&GEOM ..., BINARY_FILE='mygeom.bingeom' /
```

This might help if you are getting stuck in the read routine.

**Comment by ghost** [comment]
Thanks for the advice @marcosvanella, I tried with these meshing dimensions : 

```
! MESH Cell Size: 0.200 m, 0.200 m, 0.100 m | Qty: 160000 | Aspect: 2.0 | Poisson: Yes
&MESH ID='1_Domaine_burner' IJK=100,40,40
      XB=42.500000,62.500000,-32.000000,-24.000000,0.000000,3.980000
      MPI_PROCESS=0 /

! MESH Cell Size: 0.200 m, 0.200 m, 0.100 m | Qty: 120000 | Aspect: 2.0 | Poisson: Yes
&MESH ID='2_Domaine_vac' IJK=25,120,40
      XB=52.500000,57.500000,-24.000000,0.000000,0.000000,3.980000 MPI_PROCESS=1 /

! MESH Cell Size: 0.200 m, 0.200 m, 0.100 m | Qty: 120000 | Aspect: 2.0 | Poisson: Yes
&MESH ID='3_Domaine_est' IJK=25,120,40
      XB=57.500000,62.500000,-24.000000,0.000000,0.000000,3.980000 MPI_PROCESS=2 /

! MESH Cell Size: 0.200 m, 0.200 m, 0.100 m | Qty: 240000 | Aspect: 2.0 | Poisson: Yes
&MESH ID='4_Domaine_ouest' IJK=50,120,40
      XB=42.500000,52.500000,-24.000000,0.000000,0.000000,3.980000 MPI_PROCESS=2 /
```

However, I still have the same error... 

![cmd](https://user-images.githubusercontent.com/94290527/167663889-684da772-e79b-4943-ac15-0058b80ffd58.PNG)

**Comment by ghost** [comment]
Nice move @rmcdermo, it reduced the .fds from 30 Ko to 4, and it is much more readable, thank you. However, I encounter the same error as I have just posted.

**Comment by emanuelegissi** [comment]
If you need any help on the BlenderFDS side, I'm available. 🤗
Emanuele

**Comment by marcosvanella** [comment]
Vianey, can you compile FDS? If not latest bundles are here:
[https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC%3Fusp%3Dsharing&data=05%7C01%7Cmarcos.vanella%40nist.gov%7C926ed96ce83140db7ba508da2ebcaadd%7C2ab5d82fd8fa4797a93e054655c61dec%7C1%7C0%7C637873685112249022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FLvb%2BN3t7U8iLLNa7mLDO5EZ6VVQRrLhzLP5M%2BoyDuI%3D&reserved=0)

Either make this HVAC pipe geometry an OBST or make the OBin obstacles geometries in Blender and assign directly their SURF IDs. We don't support geoms on top of obsts at the moment, I'll add a temporary stop flag.
![Screen Shot 2022-05-10 at 12 26 51 PM](https://user-images.githubusercontent.com/7450069/167679194-3c3530ab-c926-4068-b8f7-59c70df6514a.png)

Try that and let me know.

**Comment by ghost** [comment]
Thank you Marcos. Is there an advantage to run FDS on Linux ?

I ran this simulation with shelfs and duct as OBST and not GEOM, and it worked well (I stopped it after 2 sec).

![contours](https://user-images.githubusercontent.com/94290527/167798092-8e7455ed-97a6-404c-9c72-60add5230229.PNG)

But my goal is to be able to run a simulation in a more complex environnement. So as a training, I would like to keep these obstacles as GEOM. Though, I can not fix a VENT to a GEOM, so OBin has to stay an OBST. I also tried to add a vent properties to a GEOM like this : 

`&GEOM ID='VENT' SURF_ID='IN' BINARY_FILE='VENT.bingeom' /`
`&SURF ID='IN' VOLUME_FLOW=1, COLOR='GREEN' /`

But nothing happened, it was like an inert obstacle.

Appreciate your involvement everyone thank you.

**Comment by ghost** [comment]
In order for you to see what is my objective, here is a screenshot of the whole domain I have to simulate a fire in : 
![migros](https://user-images.githubusercontent.com/94290527/167823328-6d928c39-9ff3-4fcf-84a8-0d17e0c28fb1.PNG)
In red, the part of the domain I am working on actually with a simple 4 cores processor.

As you can see, the south part of the drugs store is not "alligned" with the coordinate system, so I am forced to use GEOM for  ducts & shelfs at this place. Maybe I am heading in the wrong direction with the GEOM option. If someone has a better idea, do not hesitate to suggest it.

**Comment by marcosvanella** [comment]
Hi Vianey, there are several boundary conditions that still need to be implemented for geometries. VOLUME_FLOW is one of them and we'll work on that. Try setting VEL=1 (or VOL_FLOW/AREA_VENT) instead to check you get air flow. 
About the size of your problem and using Linux, seems to me you will need dozens of meshes for the level of resolution you need and to run with the same number of MPI processes you will need to use a cluster, which will most probably be a linux cluster. I would suggest increase the size of your problem incrementally and run it making sure things are fine. If you run into issues with GEOM report back after running the problem with the geometries made OBSTS (you can voxelize them in the preprocessor, even if non-aligned) and making sure everything else is fine. 
Complex geometry is in a fluid state and we are currently making fundamental changes on how we treat things.

**Comment by ghost** [comment]
Hi, VEL doesn't seem to work properly on GEOM. I have speeds around 1500 m/s randomly distributed close to the GEOM, even though I make the mesh very thin around it. Moreover, as `SURF_IDS` or `SURF_ID6` seem to have no sense for a GEOM, I am unable to enable the vent on only one face.

The MULT function does not work either with GEOM.

Since I chose binary files for GEOM, the reading does not fail anymore. The only OBST I kept is the duct while using a VENT. But if I manage to set-up the GEOM vent properly, I could make the duct GEOM again.
By the way, an OBST "under" a GEOM does not work but a GEOM "under" an OBST works fine.

Indeed, I guess it will be processed on a 500 cores cluster or something like that. I'll check with my team to switch over WSL.

Voxelize complex geometry could be a solution for ducts, as I could attach an OBST/VENT to it. But for other obstacles, either it makes a weird geometry in FDS, or the sum of voxels becomes to heavy for Blender to work properly.

I will run a complete simulation this night, making everything GEOM except the duct, and I'll keep you updated tomorrow. Thanks !

**Comment by marcosvanella** [comment]
Hi Vianey, as I said, there are several unimplemented features for geometries. About the high speeds you see, they are probably related to issues that led to the algorithm changes we are currently working on. Please post the case you have so I can also have a look.

**Comment by emanuelegissi** [comment]
> the sum of voxels becomes to heavy for Blender to work properly.

Well, I take it as the chance to improve the algorithm then ;-)
I once draw a full size passenger ship in BlenderFDS...
If you can share your geometry I'm glad to take a look at it.

Emanuele

**Comment by ghost** [comment]
Hi Marcos & Emanuele. Thanks for your feedbacks. 

The simulation with GEOM was supposed to run during the French night but it crashed at about 8 seconds, everything was working fine though and the few seconds seem accurate.

![crash](https://user-images.githubusercontent.com/94290527/168056336-b0e283f4-8598-48c6-a5a3-0cff0d824de0.PNG)
![8s](https://user-images.githubusercontent.com/94290527/168056960-c9cf1653-8e36-4baf-9cda-e33b9251fe43.PNG)

Everything here is GEOM except the duct.
I guess that I'll stay on simple OBST when it's quite aligned to the coordinate system, and voxelized OBST when the inclination becomes too important. 

Here is the whole folder of the simulation. 

[Drugs_store.zip](https://github.com/firemodels/fds/files/8678908/Drugs_store.zip)

@emanuelegissi did you use GEOM obstacles for your ship ?

**Comment by marcosvanella** [comment]
Thank you Vianey, I'll run the case here. Are you using the latest nightly FDS build? I put the link to these on a previous email.

**Comment by ghost** [comment]
Not yet, I will check with my team today for going on WSL and use the latest FDS build.

**Comment by ghost** [comment]
Last build downloaded and FDS runs on WSL now. Will try some simulations for the night and keep you up to date.

**Comment by ghost** [comment]
Hello everyone.

With the latest nightly build, the simulation works properly. Thank you for your help. Do not hesitate to contact me for any news about the GEOM feature.

**Comment by marcosvanella** [comment]
Thank you Vianey.
