### ISSUE TITLE
Emissivity for particles

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#10573]
Here is a simple case with two different emissivities (0.5 and 1) applied to two independent particles, both with the same surface temperature and size.
The emission from the particles is different, as expected, but the radiation received by a target is the same. It seems like the emissivity is not being applied when adding the particle contribution in the radiation solver.

[particle_emissivity.txt](https://github.com/firemodels/fds/files/8664872/particle_emissivity.txt)
.

**Comment by mcgratta** [comment]
I made changes and then reverted. 

I am looking at your test case. Are you sure that the two particles are identical except for emissivity? Can you create an example that uses surface temperature rather than internal heat source.

**Comment by ericvmueller** [comment]
Do you have a suggestion for setting the surface temperature with an emissivity defined? I can't set TMP_FRONT on the surface _and_ specify material properties. Thats why I ended up using an internal heat source to get matching surface temperatures.

**Comment by mcgratta** [comment]
Take a look at `Radiation/hot_spheres.fds`. It's an example of a sphere that is hot, but has not material properties.

**Comment by ericvmueller** [comment]
ah okay, I was setting emissivity via the MATL rather than SURF. I will update the example to try this way.

**Comment by ericvmueller** [comment]
Here it is with a surface temperature. I get the same issue of different fluxes from the particles, but the same flux received at the target.

[particle_emissivity.txt](https://github.com/firemodels/fds/files/8681107/particle_emissivity.txt)

**Comment by mcgratta** [comment]
Good, I see the problem now. I think I have a solution, but need to check all the verification cases.

**Comment by shostikk** [comment]
I'm shocked. Is it so we have never realized we assume black particles on these lines of radi.f90

         AREA_VOLUME_RATIO = 0.25_EB*LP%PWT*ONE_D%AREA*RDX(IID)*RRN(IID)*RDY(JJD)*RDZ(KKD)
         KAPPA_PART(IID,JJD,KKD) = KAPPA_PART(IID,JJD,KKD) + AREA_VOLUME_RATIO
         KFST4_PART(IID,JJD,KKD) = KFST4_PART(IID,JJD,KKD) + FOUR_SIGMA*AREA_VOLUME_RATIO*ONE_D%TMP_F**4

**Comment by mcgratta** [comment]
Apparently. I think the fix is
```
AREA_VOLUME_RATIO = 0.25_EB*LP%PWT*ONE_D%AREA*RDX(IID)*RRN(IID)*RDY(JJD)*RDZ(KKD)*ONE_D%EMISSIVITY
```
I'm testing this now.

**Comment by mcgratta** [comment]
If I am right, then we were half right before. We accounted for `EMISSIVITY` for `Q_RAD_IN` and `Q_RAD_OUT` but we neglected it in the actual transport equation.

**Comment by shostikk** [comment]
Technically, emissivity < 1 means that particle reflects part of the energy, i.e. reflected fraction should be redistributed. Similar to scattering. 

But I think simply reducing the absorption can be sufficient at this point. It simply reduces absorption. Non-absorbed part maintains direction, and energy is conserved.

**Comment by mcgratta** [comment]
Yes, I agree. I'm going to close.
