### ISSUE TITLE
FDS-EVAC parallel execution

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#10574]
I am sharing this file with you as I encountered an issue when launching it in parallel on FDS 6.7.7 version. This is the situation:

1. if you execute it in serial everything works ok

1. if you execute it in parallel using any number of MPI cores you get the following error message:

` FDS+Evac: EVACUATION INITIALIZATION.`
`ERROR: The number of MPI processes, 4, exceeds the number of fire meshes + 1, 1 (CHID: college01_evac)`

By the way, it is weird that you can "bypass" this error. If you execute the analysis in serial until iterations start, then press CTRL+C to hardly stop it, you can now execyte the FDS+EVAC INITIALIZATION with no issue using MPI (I guess because this initialization is now no more executed).

[college01.fds.txt](https://github.com/firemodels/fds/files/8668286/college01.fds.txt)

**Comment by mcgratta** [comment]
This is a good example of why we decided to remove Evac from FDS. It was becoming much too difficult to accommodate both the physics-based and pedestrian calculations. 

I will leave the issue open in case someone has a work-around for 6.7.7, the last version of FDS with Evac.
