### ISSUE TITLE
Numerical instability (Minimum density clip)

### ISSUE THREAD

**Issue by t-paw** [firemodels/fds#10588]
Hi all, 

I have a case where i faced a numerical instability giving an error message as below going into 78s of the simulation.
<img width="314" alt="FF instability error message" src="https://user-images.githubusercontent.com/105222990/168273239-1226bf80-4a80-4fe7-ac8e-0caa8d2aed14.PNG">
The case is for a residential unit (concrete surface) with 
corridors (concrete surface) 
staircase (inert surface)
smoke shafts (adiabatic surface) will be utilized (exhaust and supply, modelled using HVAC vents with constant working capacity). Localized leakages are also implemented along the corridor (vent surfaces adiabatic)

I am not sure what went wrong with the model, could not identify any irregular pressure and velocity distribution. 

The input file: 
[E299_Instability.txt](https://github.com/firemodels/fds/files/8686631/E299_Instability.txt)

**Comment by KingCZE** [comment]
Hi, I had this issue too. When I used the LES solver `&MISC SIMULATION_MODE='LES'` and `CHECK_HT=.TRUE.` (this one probably not needed), the issue was solved. I know it is not a solution for the cuase, just a workaround. 

What is the number of iterations done in these timesteps (in the .out file)? It is possible that with the loose conditions of VLES together with some high velocities, it reaches the maximum number of iterations and keeps diverting from the real solution (keeps accumulating the error)? 

I hope somebody will give more insight (for now, LES instead of the default VLES does the job).

**Comment by t-paw** [comment]
> Hi, I had this issue too. When I used the LES solver `&MISC SIMULATION_MODE='LES'` and `CHECK_HT=.TRUE.` (this one probably not needed), the issue was solved. I know it is not a solution for the cuase, just a workaround.
> 
> What is the number of iterations done in these timesteps (in the .out file)? It is possible that with the loose conditions of VLES and some high velocities, it reaches the maximum number of iterations and keeps diverting from the real solution (keeps accumulating the error)?
> 
> I hope somebody will give more insight (for now, LES instead of the default VLES does the job).

Hi King, I have not tried implementing the above suggestions. Will be worth a try. 

Also, you may refer to the output file below. The iterations seems to be running fine. 
[FS_L02_E299_1MW_FF.log](https://github.com/firemodels/fds/files/8687101/FS_L02_E299_1MW_FF.log)

**Comment by rmcdermo** [comment]
> I hope somebody will give more insight (for now, LES instead of the default VLES does the job).

@KingCZE Have you read the section in the user guide on "Numerical Stability Parameters".  LES sets `CFL_VELOCITY_NORM=1` and setting `CHECK_HT=T` basically add a Von Neumann constraint for the energy equation, which we ignore by default.  Please let me know if this is not clear.

**Comment by KingCZE** [comment]
> 

Hi, it is clear to me. That's why I suggest him to LES instead of VLES as it has the CFL norm, which should prevent the numerical instability if it is associated with these.

**Comment by KingCZE** [comment]
> > Hi, I had this issue too. When I used the LES solver `&MISC SIMULATION_MODE='LES'` and `CHECK_HT=.TRUE.` (this one probably not needed), the issue was solved. I know it is not a solution for the cuase, just a workaround.
> > What is the number of iterations done in these timesteps (in the .out file)? It is possible that with the loose conditions of VLES and some high velocities, it reaches the maximum number of iterations and keeps diverting from the real solution (keeps accumulating the error)?
> > I hope somebody will give more insight (for now, LES instead of the default VLES does the job).
> 
> Hi King, I have not tried implementing the above suggestions. Will be worth a try.
> 
> Also, you may refer to the output file below. The iterations seems to be running fine. [FS_L02_E299_1MW_FF.log](https://github.com/firemodels/fds/files/8687101/FS_L02_E299_1MW_FF.log)

Please upload FS_L02_E299_1MW_FF.out.

**Comment by t-paw** [comment]
> > > Hi, I had this issue too. When I used the LES solver `&MISC SIMULATION_MODE='LES'` and `CHECK_HT=.TRUE.` (this one probably not needed), the issue was solved. I know it is not a solution for the cuase, just a workaround.
> > > What is the number of iterations done in these timesteps (in the .out file)? It is possible that with the loose conditions of VLES and some high velocities, it reaches the maximum number of iterations and keeps diverting from the real solution (keeps accumulating the error)?
> > > I hope somebody will give more insight (for now, LES instead of the default VLES does the job).
> > 
> > 
> > Hi King, I have not tried implementing the above suggestions. Will be worth a try.
> > Also, you may refer to the output file below. The iterations seems to be running fine. [FS_L02_E299_1MW_FF.log](https://github.com/firemodels/fds/files/8687101/FS_L02_E299_1MW_FF.log)
> 
> Please upload FS_L02_E299_1MW_FF.out.
Hi, I am not too sure which output you are referring to. Apologies. 
However, I am uploading the HRR & STEPS output here (.csv file & .PNG). It seems that there is one irregular curve which I do not know what is that. 

[FS_L02_E299_1MW_FF_hrr.csv](https://github.com/firemodels/fds/files/8688151/FS_L02_E299_1MW_FF_hrr.csv)
![FS_L02_E299_1MW_FF_hrr csv](https://user-images.githubusercontent.com/105222990/168292566-7aff8daf-90b4-4576-9d59-d01dceba6a60.png)

[FS_L02_E299_1MW_FF_steps.csv](https://github.com/firemodels/fds/files/8688158/FS_L02_E299_1MW_FF_steps.csv)
![FS_L02_E299_1MW_FF_steps csv](https://user-images.githubusercontent.com/105222990/168292433-9a63a638-9c90-4eb0-bb2e-a816e4771352.png)

**Comment by t-paw** [comment]
> > > Hi, I had this issue too. When I used the LES solver `&MISC SIMULATION_MODE='LES'` and `CHECK_HT=.TRUE.` (this one probably not needed), the issue was solved. I know it is not a solution for the cuase, just a workaround.
> > > What is the number of iterations done in these timesteps (in the .out file)? It is possible that with the loose conditions of VLES and some high velocities, it reaches the maximum number of iterations and keeps diverting from the real solution (keeps accumulating the error)?
> > > I hope somebody will give more insight (for now, LES instead of the default VLES does the job).
> > 
> > 
> > Hi King, I have not tried implementing the above suggestions. Will be worth a try.
> > Also, you may refer to the output file below. The iterations seems to be running fine. [FS_L02_E299_1MW_FF.log](https://github.com/firemodels/fds/files/8687101/FS_L02_E299_1MW_FF.log)
> 
> Please upload FS_L02_E299_1MW_FF.out.

Hi, my bad. 
Output file below.
[E299_Output.txt](https://github.com/firemodels/fds/files/8688227/E299_Output.txt)

**Comment by mcgratta** [comment]
I am running the case now. Keep your eye on the regions of the domain that are sealed off from other regions. There are four of these regions, and their pressures are tracked in the _hrr.csv. Sometimes numerical instabilities are linked to spurious ventilation patterns involving sealed regions.

**Comment by t-paw** [comment]
> I am running the case now. Keep your eye on the regions of the domain that are sealed off from other regions. There are four of these regions, and their pressures are tracked in the _hrr.csv. Sometimes numerical instabilities are linked to spurious ventilation patterns involving sealed regions.

Hi Kevin, 
Checking from the curve,there seems to be a region where the pressure is irregular. That will be Zone 4. 
Is there a way that I could pinpoint where this zone corresponds to? 
![FS_L02_E299_1MW_FF_hrr csv](https://user-images.githubusercontent.com/105222990/168301603-041083a8-46ec-4423-adec-6b736a9e954b.png)

**Comment by mcgratta** [comment]
Yes, add slices like this
&SLCF PBY=...., QUANTITY='PRESSURE ZONE', CELL_CENTERED=T /
You only need to run the simulation for a short time to see it.

**Comment by t-paw** [comment]
> Yes, add slices like this &SLCF PBY=...., QUANTITY='PRESSURE ZONE', CELL_CENTERED=T / You only need to run the simulation for a short time to see it.

Hi Kevin, thank you for the guide. 
I have tried the above. It can be noticed that zone 4 corresponds to the supply shaft in green. 
<img width="594" alt="debug_pressure zone" src="https://user-images.githubusercontent.com/105222990/168307474-785acf95-68fd-4e97-b75f-fcafc8dc7b0c.PNG">

However, I could not see what is wrong with that shaft unfortunately. Apologies.

**Comment by mcgratta** [comment]
Look at the Plot3D output in Smokeview at the time the instability occurs. Do you see where the instability develops?

**Comment by drjfloyd** [comment]
&VENT ID='supply in', SURF_ID='HVAC', XB=71.7,72.1,84.1,85.1,16.0,16.0

This appears to be removing air a volume with no other inlets. The green shaft from 16 to the top of the domain looks to be solid.  Did you mean to put a hole or leakage at the top of the shaft to connect it to the OPEN boundary?

**Comment by t-paw** [comment]
> Look at the Plot3D output in Smokeview at the time the instability occurs. Do you see where the instability develops?
My bad. I do not have a pressure 3D output. Will practice to include 3D uutput next time for debugging purposes.

**Comment by t-paw** [comment]
> Look at the Plot3D output in Smokeview at the time the instability occurs. Do you see where the instability develops?

Hi Kevin, my bad. I do not have a 3D output for pressure. Will include it in next time for easier debugging purposes. Thank you.

**Comment by t-paw** [comment]
> &VENT ID='supply in', SURF_ID='HVAC', XB=71.7,72.1,84.1,85.1,16.0,16.0
> 
> This appears to be removing air a volume with no other inlets. The green shaft from 16 to the top of the domain looks to be solid. Did you mean to put a hole or leakage at the top of the shaft to connect it to the OPEN boundary?

Hi Jason, thank you for helping out.
The green shaft is hollow in the middle where the domain is an OPEN boundary at the top. The solid piece of obstruction from z 15.8m to z 16m is there just for the 'supply in' vent to be sited. The solid piece of obstruction is a adiabatic surface.

**Comment by drjfloyd** [comment]
Your hole at z=49 isn't over the shaft. It is over the stairs. The top of the shaft is solid at z=49.  Your supply vent is removing air from the shaft volume between z=16 and z=49 but there is no way for air to enter to replace what is being removed.

**Comment by t-paw** [comment]
> Your hole at z=49 isn't over the shaft. It is over the stairs. The top of the shaft is solid at z=49. Your supply vent is removing air from the shaft volume between z=16 and z=49 but there is no way for air to enter to replace what is being removed.

My my... I did not realize that is happening! Such a silly mistake to make!
I am really sorry for taking up everyone's time and effort to assist in this issue.

**Comment by BingBingBing11** [comment]
Hi, @mcgratta @drjfloyd 

I have recently encountered the same error message and I think this thread could potentially be the most applicable. 
I have also noticed a max velocity&pressure error for mesh 3

Things I have tried: 
- adding a slice of pressure and velocity through the door opening and smoke exhaust, both showed airflow
- changing smoke exhaust from a block to a vent (thin)
- checking pressure reading in hrr excel file, a spike in pressure (in both positive and negative direction) occurred around 280 seconds, I imagine was due to the doors opened by controls

and reran the simulation, the warning message of minimum density still occurs, but the simulation has not come to a stop yet. 

In case the input and output files might help:

[input.txt](https://github.com/firemodels/fds/files/8796596/input.txt)
[output.txt](https://github.com/firemodels/fds/files/8796599/output.txt)

**Comment by mcgratta** [comment]
We will look at the case. In the meantime, could you try the latest version.

**Comment by BingBingBing11** [comment]
> We will look at the case. In the meantime, could you try the latest version.
I have proceeded with this input, and currently at 200+ seconds. 
[DesignFire1.txt](https://github.com/firemodels/fds/files/8796848/DesignFire1.txt)

![image](https://user-images.githubusercontent.com/101373678/170951853-48bdb19f-f10d-4590-8b47-60da565d34bf.png)

**Comment by mcgratta** [comment]
`HEAT_OF_COMBUSTION=2.0E+5`

What is the rationale for this?

**Comment by BingBingBing11** [comment]
> `HEAT_OF_COMBUSTION=2.0E+5`
> 
> What is the rationale for this?

Hi Kevin, 

Thanks for your response, and good pick up on that one.
The reaction setting was copied over from a previous project, and as the design fire was defined in the Surfaces setting, I did not pay much attention to the reaction. 
I have not change the setting to Specify release per unit mass oxygen = 1.31E4 (default value) 
And now rerun the simulation. 

Over the past few days, I also identified that my make up air(roller doors) were opening up later than the ventilation. I have change to opening up make up air first, though that did not solve the issue and the simulation ends around the same time (270 sec)

Thank you

**Comment by BingBingBing11** [comment]
> `HEAT_OF_COMBUSTION=2.0E+5`
> 
> What is the rationale for this?

Hi Kevin, 

I have looked into this. The design was based on the reference" Swedish design guide for CFD models(link attached)"
https://files.thunderheadeng.com/femtc/2014_d1-10-rosberg-paper.pdf
![image](https://user-images.githubusercontent.com/101373678/171346619-ea65e56e-4822-459d-9733-d653d086bf28.png)

**Comment by rmcdermo** [comment]
20 MJ/kg = 20 x 10^6 = 20 000 e3 = 2.0e4 kJ/kg (not e5).

**Comment by BingBingBing11** [comment]
> 20 MJ/kg = 20 x 10^6 = 20 000 e3 = 2.0e4 kJ/kg (not e5).

Thank you for the pick up, that is an oversight indeed
