### ISSUE TITLE
FDS 6.7.4, 6.7.5, 6.7.7 install with error "Invalid class". Hope the helping!

### ISSUE THREAD

**Issue by Fireman114** [firemodels/fds#10595]
![ScreenShot_20220513220452](https://user-images.githubusercontent.com/105516718/168376803-868b0ab3-3409-4491-90f7-fae2192a55d8.png)

**Comment by Fireman114** [comment]
My laptop - HP. 
Windows 10 Pro - 64 bit. 
RAM 8 Gb.

**Comment by gforney** [comment]
when I googled your error messages the power shell came up.  to make sure you are using the command shell click on the start menu and type com . you should see "command prompt App" come up. select this app then cd into directory where you put the fds installer and try again

**Comment by Fireman114** [comment]
Sorry! I don't understand how "then cd..." is supposed to do! Do you use Ultraviewer? Can you help me install this FDS program? I am in dire need of it for my PhD thesis. Looking forward to your help!

**Comment by mcgratta** [comment]
Describe exactly the steps you took to install the program.

**Comment by Fireman114** [comment]
> Describe exactly the steps you took to install the program.

1 - Download the FDS file to my laptop;
2 - Use winzip to extract the file and the cmd window automatically appears with the question as shown in the attached image above.
3 - I typed the answer "yes", then I got the error messages as shown in the image above.

**Comment by mcgratta** [comment]
Do you have admin rights to the computer? That is, are you allowed to install software on it?

**Comment by Fireman114** [comment]
> Do you have admin rights to the computer? That is, are you allowed to install software on it?

Of course, this is my personal laptop and I ran the file with admin rights.

**Comment by mcgratta** [comment]
Do you have an unusual configuration of network drives or disks? That is,
are you programs installed on the C drive in "Program FIles"?

**Comment by gforney** [comment]
Dont use WinZip to extract the file.  The installer is an application ,an executable file.  Type the name of the installer in a command shell or double click on the file if you see it in a window

**Comment by Fireman114** [comment]
> Do you have an unusual configuration of network drives or disks? That is, are you programs installed on the C drive in "Program FIles"?
> […](#)
> Message ID: ***@***.***>

![ScreenShot_20220516143425](https://user-images.githubusercontent.com/105516718/168584156-155ffa14-427c-4ad8-80d9-0d4b2a4716d5.png)
I don't have an unusual configuration of network drives or disks. Every program installed on the C drive in "Program FIles".

**Comment by Fireman114** [comment]
Yes, I double click on the file in a window and this is result.
![ScreenShot_20220516143425](https://user-images.githubusercontent.com/105516718/168584729-40820076-4e5f-49f1-896f-0a9b20570117.png)

**Comment by Fireman114** [comment]
![ScreenShot_20220516145845](https://user-images.githubusercontent.com/105516718/168587906-0d7132ab-5b60-45cc-a9d9-4b98426455b6.png)
When I opened the application file of FDS in the C drive, I got a message like this.

**Comment by gforney** [comment]
type fdsinit first, then type fds (or open the CMDfds command shell and type fds if you see it on the desktop)

**Comment by Fireman114** [comment]
> type fdsinit first, then type fds (or open the CMDfds command shell and type fds if you see it on the desktop)

Thanks! I typed "fdsinit" and opened it, but the file doesn't work.

**Comment by gforney** [comment]
You dont need to use winzip. Just type the name of the fds installer in the
command window or double click on in file
