### ISSUE TITLE
Problem with Askervein Hill case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10601]
```
Askervein_TU03A_16m.err:ERROR: DEVC null must have coordinates, even if it is not a point quantity (CHID: Askervein_TU03A_16m)
```
I cannot figure this out. There are many devices, and many commented out.

**Comment by rmcdermo** [comment]
I pushed up typo fixes to the DEVC lines.  Try the case now.  It seg faults in this block
```
      ! Determine the bounds, XB, for an interpolated gas device

      IF (SPATIAL_STATISTIC=='INTERPOLATION') THEN
         CALL SEARCH_OTHER_MESHES(XYZ(1),XYZ(2),XYZ(3),NM,IIG,JJG,KKG,XI,YJ,ZK)
         IF (IIG>0 .AND. JJG>0 .AND. KKG>0) THEN
            M => MESHES(NM)
            XB(1) = M%X(NINT(XI)) - 0.5_EB*M%DX(IIG)
            XB(2) = M%X(NINT(XI)) + 0.5_EB*M%DX(IIG)
            XB(3) = M%Y(NINT(YJ)) - 0.5_EB*M%DY(JJG)
            XB(4) = M%Y(NINT(YJ)) + 0.5_EB*M%DY(JJG)
            XB(5) = M%Z(NINT(ZK)) - 0.5_EB*M%DZ(KKG)
            XB(6) = M%Z(NINT(ZK)) + 0.5_EB*M%DZ(KKG)
         ELSE
            XB = 0._EB
         ENDIF
      ENDIF
```

**Comment by emanuelegissi** [comment]
(it's BlenderFDS verification that keeps complaining on that)

**Comment by rmcdermo** [comment]
The case runs without `IS_TERRAIN`.  I though we got rid of the need for this, no?  What would its purpose be?

**Comment by gforney** [comment]
I believe that IS_TERRAIN was originally put in to distinguish between blockages forming terrain and other blockges that were a part of the simulation that were not terrain.

**Comment by emanuelegissi** [comment]
Well, it's an open surface. IS_TERRAIN should prevent the checks related to
open geometries

**Comment by mcgratta** [comment]
I fixed the bug reading in the `INTERPOLATION` device. I also fixed spellings of `V-VELOCITY` and `W-VELOCITY`. The u and v are capitalized. The case now runs but stops with a numerical instability after a few time steps.

**Comment by rmcdermo** [comment]
@emanuelegissi IS_TERRAIN=T is set on the GEOM line in [cad/Askervein_hill/Askervein.geom](https://github.com/firemodels/cad/blob/master/Askervein_Hill/Askervein.geom), which then gets translated to a GEOM_TYPE=TERRAIN_GEOM_TYPE=2 in the binary file.

Is there something that we need to do for your verification case?  I am not understanding your comment.  Thanks

**Comment by emanuelegissi** [comment]
Shouldn't you add also IS_TERRAIN=T to:
&GEOM ID='terrain', SURF_ID='terrain',
BINARY_FILE='../../../../cad/Askervein_Hill/Askervein_5m.bingeom' /
?

**Comment by emanuelegissi** [comment]
Yes, you are right, sorry I had forgotten about that 2 that gets saved in
the bingeom.

So if I understand correctly, the IS_TERRAIN=T is only useful when
translating VERTS and FACES to the bingeom file, right? (I have to update
BlenderFDS checks)

**Comment by rmcdermo** [comment]
@emanuelegissi Sorry but I cannot dive back into this right now.  It will take me some time to understand the terrain stuff again.  Ping me again if I don't get back to you in a couple weeks.

**Comment by emanuelegissi** [comment]
@rmcdermo no problem I fixed the issue in BlenderFDS. It should work now. While importing, that "2" in the bingeom file eventually sets the IS_TERRAIN=T

**Comment by marcosvanella** [comment]
Askervein Hill runs.
