### ISSUE TITLE
Non-conservation of Mass in Pyrolysis Model

### ISSUE THREAD

**Issue by Stven-Frank** [firemodels/fds#10616]
I am going to simulate a wood crib fire in an open space. After the simulation, the combustible mass is about 1500g. However, simulation consumes 2700g fuel for 157s. It is obvious to go against the mass conservation equation. The results and input file are below. What is the wrong? Or I make a great mistake? Please point out.
![屏幕截图 2022-05-16 203709](https://user-images.githubusercontent.com/101112442/169045235-0b9ac61a-c922-43d9-b352-d82f3ad13f91.png)
![屏幕截图 2022-05-16 203728](https://user-images.githubusercontent.com/101112442/169045242-117ec569-fdd7-4c99-99d0-2a2b6014a3d0.png)
![1111](https://user-images.githubusercontent.com/101112442/169045427-b0c9a792-06e2-48cb-8763-3b01ad13de5f.png)

Stven Frank

**Comment by drjfloyd** [comment]
Try setting BULK_DENSITY on the OBST line.  Every wall cell has its own independent solution, so if multiple cells on an OBST are burning you can get more mass than expected. BULK_DENSITY tells FDS how much mass is actually present.

Also it helps us if you attach an actual file rather than an image of your FDS input.  You just have  to change the extension to .txt to attach it.

**Comment by Stven-Frank** [comment]
The input file is in the attachment. As for setting BULK_DENSITY on the OBST line, it is simulating in PC.
[Check_Wang.txt](https://github.com/firemodels/fds/files/8737673/Check_Wang.txt)

**Comment by Stven-Frank** [comment]
Adding BULK_DENSITY to the OBST line, the result haven.t changed. It's non-conservation of mass.

**Comment by drjfloyd** [comment]
What BULK_DENSITY did you set and did you also add BURNAWAY to the SURF?

**Comment by drjfloyd** [comment]
You have also defined your wood as being made of 13 cm diameter spheres.  The actual sticks making up the wood are ~3 cm in cross section. With BULK_DENSITY and BURNAWAY set this shouldn't have an impact on the mass but it will effect the burning rate as a sphere whose radius is changing over time will have a different temperature profile than a slab and a 13 cm thick item will have a different temperature profile than a 3 cm thick item.

**Comment by Stven-Frank** [comment]
> What BULK_DENSITY did you set and did you also add BURNAWAY to the SURF?

Only setting BULK_DENSITY  to the OBST line. The parameter of BURNAWAY does  not add to SURF. You mean, I need to set BURNAWAY  to SURF line.

**Comment by Stven-Frank** [comment]
> What BULK_DENSITY did you set and did you also add BURNAWAY to the SURF?

Only setting BULK_DENSITY  to the OBST line. The parameter of BURNAWAY does  not add to SURF. You mean, I need to set BURNAWAY  to SURF line.

**Comment by Stven-Frank** [comment]
> You have also defined your wood as being made of 13 cm diameter spheres. The actual sticks making up the wood are ~3 cm in cross section. With BULK_DENSITY and BURNAWAY set this shouldn't have an impact on the mass but it will effect the burning rate as a sphere whose radius is changing over time will have a different temperature profile than a slab and a 13 cm thick item will have a different temperature profile than a 3 cm thick item.

Thanks for your specific answer. I will try it again.

**Comment by Stven-Frank** [comment]
Hello Dr.Floyd! Changing the thickness of wood SURF and setting BUlK_DENSITY do not work. It is still Non-conservation of Mass.  The results and input file are below.
![123](https://user-images.githubusercontent.com/101112442/170269572-274f42bf-fcf5-42cf-b96f-bed46cb35858.png)
[CWang.txt](https://github.com/firemodels/fds/files/8771392/CWang.txt)

**Comment by drjfloyd** [comment]
I ran your case with FDS 6.7.7 (FDS 6.7.8 was released while this was running but I don't expect that results would change). I modified the MESH lines slightly to reduce to size of the domain so this would run faster. The grid spacing and cell boundaries was preserved so this should have no impact on the mass injected into the gas by the solid phase pyrolysis. 

&MESH   ID='M-1'	   XB=1.468,2.008,-0.048,0.492,0,0.72       IJK=30,30,40,MULT_ID = 'mesh-1' /
&MULT ID='mesh-1', DX=0.54, I_UPPER =1, DZ=0.72,K_UPPER =1/

You have 10 copies of the first and third OBST at 0.10170 kg per copy and 15 of the second at 0.02086 kg. This gives a total mass of 2.34621 kg.  When I run the case the wood burns by 170 s with an integrated mass loss rate of 2.34625 or an error of 0.001 %. 

![image](https://user-images.githubusercontent.com/12799217/170339685-ff433dc8-3cc9-4561-aa1a-8e7b6480ecb4.png)

As an additional note you have both NU_MATL and NU_SPEC equal to 0.8 meaning that for every kg of wood you are telling FDS to make 1.6 kg of pyrolysis products. I suspect you may have intended NU_MATL to be 0.2 which would be a reasonable char yield. I did not fix this when I ran the case.
