### ISSUE TITLE
Difficulties with BNDF_FACE(IOR)

### ISSUE THREAD

**Issue by TristanHehnen** [firemodels/fds#10621]
Hi,

I seem to misunderstand how the `BNDF_FACE(IOR)` parameter works. I would like to record the `BNDF` for the top face (z+) of the `OBST` , this is my input:

```
&OBST ID            = 'SampleHolder',
      SURF_ID       = 'INERT',
      BNDF_OBST     = T,
      BNDF_FACE(3),
      CELL_CENTERED = T,
      XB=-0.075,1.075,-0.1625,0.1625,-0.022,0.00  /
```

FDS raises an error with this `OBST` and does not start. Could you please point me to what I'm missing here?

Best, 
Tristan

**Comment by mcgratta** [comment]
`CELL_CENTERED` is not an `OBST` parameter. Also, `BNDF_FACE` is a logical parameter and must be set to `T` or `F`.

**Comment by TristanHehnen** [comment]
Thanks, the one with the  `Cell_CENTERED` I just realised as well...  :D

Okay, I didn't realise that this was a logical parameter.
Thank you very much!
