### ISSUE TITLE
Compiling on Fugaku supercomputer

### ISSUE THREAD

**Issue by gf901103** [firemodels/fds#10632]
Hi there,
I am trying to run FDS on the Supercomputer Fugaku (Japan), but I am new in the field of compiling.
The compute node (CPU: A64FX (ARM)) of this supercomputer only allows (1)Fujitsu compiler, (2)Combination of GNU Compiler Collection and Fujitsu MPI,(3) LLVM. 
Can any of the current FDS compiling methods be used for above situation?
I have tried to used CNU compiler, but failed. The gfortran version is **GNU Fortran (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)**.  
When I used **mpifort** command, it always output a error "mpifort: cannot execute binary file: exec format error".
I feel confused about it. I would appreciated it if you can give me any suggesstions.

**Comment by marcosvanella** [comment]
All FDS bundles are compiled with intel compilers which work with x86 architectures. Unless Fujitsu provides a translator to ARM instruction sets, they will not work. Similar issue is happening with the new M1 macs. Your best bet is probably to compile the code with a gnu target (assuming the machine is a linux system, i.e. fds/Build/ompi_gnu_linux). For that you will need a gnu fortran compiler version 9 or above I think. Some new intrinsic functions used in the source code require latest versions of the gnu compiler.
________________________________
From: Feng Guo ***@***.***>
Sent: Monday, May 23, 2022 09:03 AM
To: firemodels/fds ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [firemodels/fds] Compiling on Fugaku supercomputer (Issue #10632)


Hi there,
I am trying to run FDS on the Supercomputer Fugaku (Japan), but I am new in the field of compiling.
The compute node (CPU: A64FX (ARM)) of this supercomputer only allows (1)Fujitsu compiler, (2)Combination of GNU Compiler Collection and Fujitsu MPI,(3) LLVM.
Can any of the current FDS compiling methods be used for above situation?
I have tried to used CNU compiler, but failed. The gfortran version is GNU Fortran (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1).
When I used mpifort command, it always output a error "mpifort: cannot execute binary file: exec format error".
I feel confused about it. I would appreciated it if you can give me any suggesstions.

**Comment by marcosvanella** [comment]
You will also need openmpi compiled with said gnu compiler.
________________________________

**Comment by rmcdermo** [comment]
@gforney Since Marcos is tied up with the upcoming meeting, can you please help.  Thanks

**Comment by gforney** [comment]
looks like the mpifort compiler is not compatible with hardware it is running on.  this is the kind of message you get when this happens "mpifort: cannot execute binary file: exec format error". you should contact the system administrators on your system to find out why you are getting this error.

after that is resolved, I would first try to build the test_mpi program we have in the fds repo at fds/Utilities/test_mpi .  this will be simpler to build than fds

another approach is to build openmpi yourself. you'll need a more recent version of gfortran though than 8.4.  most recent version of gfortran is 11.2 (that I could find).  we use 9.4 (we need this for some more modern constructs fds uses)

1. download link for openmpi: : https://www.open-mpi.org/software/ompi/v4.1/
2.  wiki page on building openmpi on an Ubuntu linux system:
3.  https://github.com/firemodels/fds/wiki/Compiling-FDS-with-GNU-Fortran-in-Ubuntu-Linux

**Comment by gf901103** [comment]
Thank you for the prompt response! @marcosvanella @rmcdermo @gforney . 
I have checked that the gfortran 11.2 is available in the Fugaku supercomputer. I found the openmpi should be install in the local directroy due the account permissions. After successfully installing the openmpi using the new path (in the local account directory) rather than the dedault one ( /shared/openmpi_64 ), the exec format error disappeared.

However, when I build ompi_gnu_linux, the following new error message appeared, do you know what does it mean?
Should I change something in the **makefile** ?

Building ompi_gnu_linux
mpifort -c -m64 -O2 -std=f2018 -frecursive -ffpe-summary=none -fall-intrinsics -cpp -DGITHASH_PP=\"FDS6.7.7-1215-g01e4c6b0f-master\" -DGITDATE_PP=\""Mon May 23 10:15:23 2022 -0400\"" -DBUILDDATE_PP=\""May 24, 2022  01:00:26\"" -DCOMPVER_PP=\""Gnu gfortran 8.4.1"\" -DWITH_MKL -/opt/intel/oneapi/mkl/2022.0.2/include  -fopenmp ../../Source/func.f90
**f951: Error:** BACK argument to  **minloc**  intrinsic not yet implemented
make: *** [../makefile:135: func.o] Error 1

**Comment by drjfloyd** [comment]
You need to use gfortran 11.2 or newer and your compiler string says "Gnu fortran 8.4.1"

**Comment by gf901103** [comment]
Thanks, Jason! I have changed the gfortran version to 10.3.1. The above error message disappeared, but new error message came as below. Is it directroy problem of toolchain? 

Building ompi_gnu_linux
mpifort -O2 -std=f2018 -frecursive -ffpe-summary=none -fall-intrinsics -cpp -DGITHASH_PP=\"FDS6.7.7-1215-g01e4c6b0f-master\" -DGITDATE_PP=\""Mon May 23 10:15:23 2022 -0400\"" -DBUILDDATE_PP=\""May 24, 2022  16:23:57\"" -DCOMPVER_PP=\""Gnu gfortran 10.3.1"\" -DWITH_MKL -I/opt/intel/oneapi/mkl/2022.0.2/include -fallow-argument-mismatch -fopenmp -o fds_ompi_gnu_linux prec.o cons.o devc.o type.o data.o mesh.o func.o gsmv.o smvv.o rcal.o turb.o soot.o pois.o geom.o ccib.o radi.o part.o vege.o ctrl.o hvac.o mass.o wall.o fire.o velo.o scrc.o pres.o init.o dump.o read.o divg.o main.o -Wl,--start-group /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_gf_lp64.a /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_gnu_thread.a /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.a /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_blacs_openmpi_lp64.a -Wl,--end-group -lgomp -lpthread -lm -ldl
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: devc.o: Relocations in generic ELF (EM: 62)
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: devc.o: Relocations in generic ELF (EM: 62)
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: devc.o: Relocations in generic ELF (EM: 62)
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: devc.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [../makefile:326: ompi_gnu_linux] Error 1

**Comment by rmcdermo** [comment]
Try without MKL (disable it in the makefile) and see what you get.

**Comment by drjfloyd** [comment]
Also make sure you did full build after changing versions (deleting all .o and .mod files before compiling).

**Comment by gf901103** [comment]
Thanks ! I have deleted all .o and .mod files before compiling this time.  
I also disable the MKL in the makefile. But some new error appeared as below:

/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libopen-pal.a when searching for -lopen-pal
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lopen-pal
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lhwloc
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lucp
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -luct
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lucm
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lucs
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -losmcomp
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -libverbs
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lrdmacm
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -levent_core
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -levent_pthreads
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lz
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lnl-3
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lnl-route-3
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -llustreapi
collect2: error: ld returned 1 exit status
make: *** [../makefile:171: ompi_gnu_linux] Error 1

**Comment by marcosvanella** [comment]
Can you paste the link line here? Also did you compile openmpi in your user directory with gcc 10.3.1?

**Comment by rmcdermo** [comment]
Did you build openmpi with gnu 10.3.1?  I think you will need to do this.

**Comment by gf901103** [comment]
Building ompi_gnu_linux
mpifort -O2 -std=f2018 -frecursive -ffpe-summary=none -fall-intrinsics -cpp -DGITHASH_PP=\"FDS6.7.7-1223-g903f95881-master\" -DGITDATE_PP=\""Mon May 23 22:02:59 2022 -0400\"" -DBUILDDATE_PP=\""May 24, 2022  21:35:53\"" -DCOMPVER_PP=\""Gnu gfortran 10.3.1"\" -DWITH_MKL -I/opt/intel/oneapi/mkl/2022.0.2/include -fallow-argument-mismatch -fopenmp -o fds_ompi_gnu_linux prec.o cons.o devc.o type.o data.o mesh.o func.o gsmv.o smvv.o rcal.o turb.o soot.o pois.o geom.o ccib.o radi.o part.o vege.o ctrl.o hvac.o mass.o wall.o fire.o velo.o scrc.o pres.o init.o dump.o read.o divg.o main.o
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libmpi_usempif08.a when searching for -lmpi_usempif08
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lmpi_usempif08
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libmpi_usempi_ignore_tkr.a when searching for -lmpi_usempi_ignore_tkr
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lmpi_usempi_ignore_tkr
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libmpi_mpifh.a when searching for -lmpi_mpifh
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lmpi_mpifh
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libmpi.a when searching for -lmpi
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lmpi
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libopen-rte.a when searching for -lopen-rte
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lopen-rte
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /vol0003/mdt0/data/hp220186/openmpi_64/lib/libopen-pal.a when searching for -lopen-pal
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lopen-pal
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lhwloc
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lucp
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -luct
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lucm
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lucs
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -losmcomp
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -libverbs
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lrdmacm
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -levent_core
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -levent_pthreads
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lz
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lnl-3
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lnl-route-3
/vol0004/apps/oss/gcc-arm-10.3.1/lib/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -llustreapi
collect2: error: ld returned 1 exit status
make: *** [../makefile:171: ompi_gnu_linux] Error 1

**Comment by gf901103** [comment]
Sorry for the lack of info, All the lines are pasted above. Yes, it was made by gcc10.3.1. And I have built openmpi according to the instruction: https://github.com/firemodels/fds/wiki/Compiling-FDS-with-GNU-Fortran-in-Ubuntu-Linux

**Comment by gf901103** [comment]
The location of openmpi are not in the root directory. Following is verifying of mpifort, Do you think the directroy cause above issue?

login5$ mpifort --version
GNU Fortran (GCC) 10.3.1 20210621
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

login5$ mpifort --showme
gfortran -I/vol0003/mdt0/data/hp220186/openmpi_64/include -pthread -I/vol0003/mdt0/data/hp220186/openmpi_64/lib -L/vol0003/mdt0/data/hp220186/openmpi_64/lib -Wl,-rpath -Wl,/vol0003/mdt0/data/hp220186/openmpi_64/lib -Wl,--enable-new-dtags -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lopen-rte -lopen-pal -lhwloc -lucp -luct -lucm -lucs -losmcomp -libverbs -lrdmacm -ldl -levent_core -levent_pthreads -lz -lnl-3 -lnl-route-3 -lrt -llustreapi -lutil -lm

**Comment by marcosvanella** [comment]
go to the Build/makefile and in the target

ompi_gnu_linux : FFLAGS = -m64 -O2 -std=f2018 -frecursive -ffpe-summary=none -fall-intrinsics $(GITINFOGNU) $(GNU_COMPINFO) **$(FFLAGSMKL_GNU_OPENMPI)** $(GFORTRAN_OPTIONS)
ompi_gnu_linux : LFLAGSMKL = **$(LFLAGSMKL_GNU_OPENMPI)**
ompi_gnu_linux : FCOMPL = mpifort
ompi_gnu_linux : FOPENMPFLAGS = -fopenmp
ompi_gnu_linux : obj = fds_ompi_gnu_linux
ompi_gnu_linux : setup $(obj_mpi)
        $(FCOMPL) $(FFLAGS) $(FOPENMPFLAGS) -o $(obj) $(obj_mpi) $(LFLAGSMKL)

Delete the flags in boldtype.  rm *.o *.mod, compile again report back.  For some reason the script is picking up a oneapi library in your system. I'm interested in this, please ask your IT person if there is a version of impi, ifort for this machine? Why is oneapi in there?

**Comment by gf901103** [comment]
Thank you @marcosvanella . I tried following your response. Similar error massage. I attached in txt file. But this time, there is no oneapi library.

[Err Message.txt](https://github.com/firemodels/fds/files/8762963/Err.Message.txt)

**Comment by marcosvanella** [comment]
Ok, at this point your best bet is to ask the IT person to install openmpi from source in the system with gcc 10.3 compilers and all required dependencies, and test that the mpi library works in the cluster.

**Comment by gf901103** [comment]
> Ok, at this point your best bet is to ask the IT person to install openmpi from source in the system with gcc 10.3 compilers and all required dependencies, and test that the mpi library works in the cluster.

Okay. Got it! I will report if there is any further progress after inquiring IT person. Thanks!

**Comment by gf901103** [comment]
Hello, I have inquired to the IT person of Fugaku Supercomputer. The problem solved, and some details are as below:
1. In default environment, Fugaku has login node (x86_64) and compute node (CPU: A64FX (ARM)).  We cannot compile or execute FDS on the compute nodes, because all FDS bundles are compiled with intel compilers which work with x86 architectures.
2. However, We can use the Pre/Post environment to execute FDS which was compiled in the login node. In this environment, SLURM Workload Manager has been installed as a job scheduler. Users can submit both types (batch and interactive) of jobs via the login nodes by SLURM commands.
3. The Pre/Post environment consist of two types of servers (GPU and large memory nodes) equipped with Intel CPUs . [For one GPU node: Intel Xeon Gold 6240 (2.60GHz/18core), Equipped with 2] [For a large memory node: Intel Xeon Platinum 8280L (2.70GHz/28core), Equipped with 4 ]
Just for the reference.
Thank all of your the discussions!

**Comment by rmcdermo** [comment]
I understand why you cannot use the bundles on the ARM nodes.  But I don't understand why you would not be able to compile.  Marcos was able to compile and run FDS on the new mac M1 chips using GNU.

It seems to me that if you are not running on the ARM nodes, you are not taking advantage of Fugaku (am I not understanding something?).  I would be very interested to see how well FDS scales on this machine.  If you can run the MPI scaling tests, this would be very interesting.  Thanks.

**Comment by gf901103** [comment]
Hi, Randy. 
So far, the IT person suggested me to not use compute nodes. And he said that I do not need to compile FDS by myself.
As you said, if I can use ARM nodes for FDS, we may see the potential of Fugaku for large scale simulation. 
I am also interested in it. Currently, I am running the MPI scaling tests in the Pre/Post environment for small scale jobs. I will contact the IT person again to ask how to run/ compile FDS on ARM nodes. 
Could you suggest a proper model for model for the MPI scaling tests? I may try to test it when I am free. Thanks !
I will report if I get further progress.

**Comment by rmcdermo** [comment]
The tests we typically use are [here](https://github.com/firemodels/fds/tree/master/Validation/MPI_Scaling_Tests).  Kevin scaled FDS up to 10,000 cores on Titan at Oak Ridge National Labs in the USA.  We might need to increase the size of the serial job, but would be interesting to see if we could get to 100,000 cores on Fugaku.

These exercises are useful in a couple of ways.  First, they often identify bottlenecks in our code that don't show up as readily on smaller jobs.  Second, we are trying to make a case for improved research computing resources here at NIST, and I think showing the potential for large scale computations on Fugaku would help with this.  Thanks

**Comment by gf901103** [comment]
So far, my jobs are very small, I haven't run multi-node jobs yet.
If I remember correctly, for a small resource group in Fugaku, maximum nodes can be used are 384, with 48 threads of each node. Does it mean 18432 cores can be utilized? If so, the I think runing on ARM compute nodes seems promising.

**Comment by rmcdermo** [comment]
OK, well maybe you can't get to 100k right away.  Probably you need a special proposal for such simulations.  But this is the point of the machine, so I think these proposals get through pretty easily.  But getting up to 18k cores would also be good.  Whether the 48 threads are real cores or not, I am not sure.  I think you do not want hyperthreading.

**Comment by gf901103** [comment]
Yes, Periodic Calls of Proposals using Fugaku can provide larger resource. As shown in the image attached. 
BTW, I think it is 48 real cores, according to the website. https://www.r-ccs.riken.jp/en/fugaku/about/
![Fugaku Resource group](https://user-images.githubusercontent.com/67189851/171013153-2b60e303-2ad1-4369-b512-b86c1ea0ec34.png)

**Comment by gf901103** [comment]
A follow up report for this issue:
I have consulted with the IT person of Fugaku. In Fugaku, FDS 6.7.7 was compiled in this machine now, the environment is also installed in the spack. For the latest version of FDS, we can compile it as following ways:
1. Create a new folder for "mpi_fugaku" including "make_fds.sh" under fds/Build directory.
2. Add some commands for Fujitsu compiler in the "makefile", edited by sakakura. (Line 50 and Line 317)

GITINFOFUGAKU=-cpp $(GITINFO_BASE) -DBUILDDATE_PP=\""$(BUILD_DATE)\""  #edit sakakura

#*** Fugaku Compilers *** #edit sakakura
#mpi_fugaku : FFLAGS = -Nalloc_assign -Nquickdbg=inf_detail -O0  $(GITINFOFUGAKU) $(FFLAGSMKL_GNU_OPENMPI) $(GFORTRAN_OPTIONS) -Nlst=t
mpi_fugaku : FFLAGS = -Nalloc_assign -O3  $(GITINFOFUGAKU) $(FFLAGSMKL_GNU_OPENMPI) $(GFORTRAN_OPTIONS) -Nlst=t
mpi_fugaku : LFLAGSMKL = $(LFLAGSMKL_GNU_OPENMPI)
mpi_fugaku : FCOMPL = mpifrtpx
#mpi_fugaku : FOPENMPFLAGS = -Kopenmp,fp_precision
mpi_fugaku : FOPENMPFLAGS = -Kopenmp,eval,fp_contract,fp_relaxed,fz,ilfunc,mfunc,omitfp,nosimd
mpi_fugaku : obj = fds_mpi_fugaku_03_fast_nosimdpacked_nosimd
mpi_fugaku : setup $(obj_mpi)
	$(FCOMPL) $(FFLAGS) $(FOPENMPFLAGS) -o $(obj) $(obj_mpi) -SSL2BLAMP

3. In all the source codes (*.f90): Change "IMPLICIT NONE (TYPE,EXTERNAL)" to "IMPLICIT NONE"
4. Setting the environment installed in Fugaku: 

$ . /vol0004/apps/oss/spack/share/spack/setup-env.sh
$ spack load /nphnrhl #gcc@11.2.0%gcc@8.4.1 arch=linux-rhel8-a64fx

5. Execute make_fds.sh under /fds/Build/mpi_fugaku
6. Compiling to success.

Before submitting the job to Fugaku Compute Node, set FDS environment:
$ . /vol0004/apps/oss/spack/share/spack/setup-env.sh
$ spack load fds

So far, this is what I learned, Just for reference. Now I can run the FDS 6.7.8 on Fugaku very well. But the performance should be checked later.

**Comment by rmcdermo** [comment]
Well done!  Please keep us posted on your results.  Thanks

**Comment by mcgratta** [comment]
Do you have the latest Gnu Fortran compiler? You should not need to change the IMPLICIT statements in the source code if you use a compiler that adheres to the 2018 Fortran standard.

**Comment by gf901103** [comment]
Hi, Kevin. According to the Fugaku user guide, the compiler for compute node is **Combination of GNU Compiler Collection and Fujitsu MPI**. It shows that the version of GNU Fortran (GCC) is "8.4.1 or 11.2.0". 
When I compile fds without changing IMPLICIT, the compilation was terminated and the related error messages occurred.
I guess it may caused by the default compiler of this machine, and I have no other choice of the compiler.

**Comment by mcgratta** [comment]
I suggest you ask that GNU Fortran 9 be installed.

**Comment by gf901103** [comment]
Hi, Kevin, I have asked the IT person of Fugaku, unluckily, the GNU Fortran 9 is not installed. The orginal response is as below:
```
As stated in the document you indicated, GNU Fortran ver.9 is not installedon Fugaku. 
According to the following pages, both 8.4.1 and 11.2.0 may support the Fortran 2018 standard.
(We assume the situation is similar, although the versions are slightly different.) 
https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gfortran/Fortran-2018-status.html#Fortran-2018-status
https://gcc.gnu.org/onlinedocs/gcc-11.3.0/gfortran/Fortran-2018-status.html#Fortran-2018-status
However, we cannot answer this further as it is a question about GNU and not specific to the Fugaku.
```
In addition, I have conducted some scale testing using the files [here](https://github.com/firemodels/fds/tree/master/Validation/MPI_Scaling_Tests/FDS_Input_Files). The result is like the figure below. Just for your reference.
![MPI_Scale_Test_Fugaku](https://user-images.githubusercontent.com/67189851/173787031-92ed2207-a80d-40aa-96ac-76ed8daf48ba.jpg)

**Comment by marcosvanella** [comment]
Hi Feng, GNU 11.2 should compile the source code without issues. Try loading that version with your MPI lib flavor.On Jun 15, 2022 4:57 AM, Feng Guo ***@***.***> wrote:
Hi, Kevin, I have asked the IT person of Fugaku, unluckily, the GNU Fortran 9 is not installed. The orginal response is as below:
As stated in the document you indicated, GNU Fortran ver.9 is not installedon Fugaku. 
According to the following pages, both 8.4.1 and 11.2.0 may support the Fortran 2018 standard.
(We assume the situation is similar, although the versions are slightly different.) 
https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gfortran/Fortran-2018-status.html#Fortran-2018-status
https://gcc.gnu.org/onlinedocs/gcc-11.3.0/gfortran/Fortran-2018-status.html#Fortran-2018-status
However, we cannot answer this further as it is a question about GNU and not specific to the Fugaku.

In addition, I have conducted some scale testing using the files here. The result is like the figure below. Just for your reference.

**Comment by mcgratta** [comment]
There is nothing special about Gnu 9. Try using 11. If the code compiles with 11, you should not have to change the source code.

**Comment by gf901103** [comment]
Okay, I see. Thank you guys!
