### ISSUE TITLE
Running a FDS Job on Linux-Cluster with multiple Nodes

### ISSUE THREAD

**Issue by ASpallek** [firemodels/fds#10643]
Hello there,
I would like to run a FDS Simulation with 10 nodes on a Linux cluster. I have already divided the mesh into 10 parts in my FDS Codes because I planned that every Node “solves” one mesh. 
Now every time I start the shell-script the simulation runs but on only one node.
The cluster uses a SLRUM job scheduler and every node has got 64Gb RAM.  

When I submitted the Job, I get the following Output:

SLURM_JOB_NAME = startMPI2.sh
SLURM_JOB_USER = skalspal
SLURM_JOB_ID = 179671
SLURM_JOB_NUM_NODES = 1
SLURM_JOB_NODELIST = node330

 Starting FDS ...

 MPI Process      0 started on node330
 MPI Process      1 started on node330
 MPI Process      7 started on node330
 MPI Process      3 started on node330
 MPI Process      4 started on node330
 MPI Process      5 started on node330
 MPI Process      9 started on node330
 MPI Process      8 started on node330
 MPI Process      2 started on node330
 MPI Process      6 started on node330

 Reading FDS input file ...

 Fire Dynamics Simulator

 Current Date     : May 25, 2022  14:53:41
 Revision         : FDS6.7.7-0-gfe0d4ef38-release
 Revision Date    : Thu Nov 18 17:10:22 2021 -0500
 Compiler         : Intel ifort 2021.4.0
 Compilation Date : Nov 19, 2021 08:15:06

 MPI Enabled;    Number of MPI Processes:      10
 OpenMP Enabled; Number of OpenMP Threads:     48

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2019 Update 8 for Linux* OS

 Job TITLE        : Fire Column
 Job ID string    : Fire at Column

 Time Step:      1, Simulation Time:      0.03 s
 Time Step:      2, Simulation Time:      0.06 s
 .........

... and here my shell-script:

#!/bin/bash
export MODULEPATH=/mnt/lxfs/scratch/skalspal/FDS/bin/modules:$MODULEPATH
module load FDS6
#SBATCH --job-name=radi_column.fds
#SBATCH -o radi_column.log
#SBATCH --time=00-00:01:00
#SBATCH --mem=60G
#SBATCH --workdir=/mnt/lxfs/scratch/skalspal/Simulation/Stuetze/
#SBATCH --nodes=10
#SBATCH --ntasks=10
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=48
#SBATCH --ntasks-per-core=1
export OMP_NUM_THREADS=48
export NUM_CORES=480
export I_MPI_PIN_DOMAIN=omp
export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=0
cd /mnt/lxfs/scratch/skalspal/Simulation/Stuetze
mpiexec -n 10 /mnt/lxfs/scratch/skalspal/FDS/bin/fds radi_column.fds

Does anyone have an idea what is going wrong?
Many thanks and kind regards,
Alex

**Comment by rmcdermo** [comment]
I think you need `#SBATCH --ntasks-per-node=10`

This assumes you have 10 cores on a node.  If you only have, say, 8 cores per node, then you could set `--ntasks-per-node=5` or something like that.

**Comment by rmcdermo** [comment]
Also, change `export OMP_NUM_THREADS=1`

**Comment by rmcdermo** [comment]
Here is an example of one of our SLURM scripts for running a 4-mesh case.

```
#!/bin/bash
# /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Utilities/Scripts/qfds.sh -p 4 -n 4  dancing_eddies_default.fds
#SBATCH -J dancing_eddies_default
#SBATCH -e /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pressure_Solver/dancing_eddies_default.err
#SBATCH -o /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pressure_Solver/dancing_eddies_default.log
#SBATCH --partition=batch
#SBATCH --ntasks=4
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=99-99:99:99

export MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/local/Modules/modulefiles
module purge
module load git/218 null modules psm libfabric/1.10.1
export OMP_NUM_THREADS=1
export I_MPI_DEBUG=5
export I_MPI_FABRICS=shm

cd /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pressure_Solver
echo
echo `date`
echo "    Input file: dancing_eddies_default.fds"
echo "     Directory: `pwd`"
echo "          Host: `hostname`"
echo "----------------" >> /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pressure_Solver/dancing_eddies_default.qlog
echo "started running at `date`" >> /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pressure_Solver/dancing_eddies_default.qlog
srun -N 1 -n 4 --ntasks-per-node 4 /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Build/impi_intel_linux/fds_impi_intel_linux dancing_eddies_default.fds 
echo "finished running at `date`" >> /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Pressure_Solver/dancing_eddies_default.qlog
```

**Comment by rmcdermo** [comment]
Is this working now?

**Comment by ASpallek** [comment]
First, thanks for your quick answer! I changed the Lines `export OMP_NUM_THREADS` and `ntasks-per-node` but that doesn’t work for me. 
Tomorrow I’m at the office again and I will try your Example-Script.
I’ll report tomorrow.

**Comment by gforney** [comment]
if you have the fds repo, run the script qfds.sh located in fds/Utilities/Scripts .  You can use it to generate an example slurm script.  If your case has 10 meshes and your case is named casename.fds use

qfds.sh -p 10 -v casename.fds

the 'v' option doesn't run the script it just outputs the slurm script to stdout

**Comment by ASpallek** [comment]
Thank you very much! With the script qfds.sh and some minor changes, the job is now running on 10 nodes. 
The job is queued and I will let you know if the simulation also starts right.

**Comment by ASpallek** [comment]
UPDATE: This Script works for me! 

#!/bin/bash
###qfds.sh -p 10 -o 48  /mnt/lxfs/scratch/skalspal/Simulation/Stuetze/radi_column.fds
#SBATCH -J FDS_Column
#SBATCH -e /mnt/lxfs/scratch/skalspal/radi_column.err
#SBATCH -o /mnt/lxfs/scratch/skalspal/radi_column.log
#SBATCH --ntasks=10
#SBATCH --nodes=10
#SBATCH --cpus-per-task=48
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks-per-core=1
#SBATCH --mem=60G
#SBATCH --time=00-00:10:00
export MODULEPATH=/opt/env-switcher/share/env-switcher:/opt/modules/oscar-modulefiles:/mnt/lxfs/scratch/skalspal/FDS/bin/modules:/opt/modulefiles/applications:/opt/modulefiles/compiler:/opt/modulefiles/mpi:/opt/modulefiles/tools:/opt/modulefiles/intel-oneapi:/opt/modules/version:/opt/modules/Modules/3.2.6/modulefiles:/opt/modules/modulefiles:
module purge
module load oscar-modules/1.0.5 FDS6
export OMP_NUM_THREADS=48
export I_MPI_DEBUG=5
export I_MPI_PIN_DOMAIN=omp
cd /mnt/lxfs/scratch/skalspal/Simulation/Stuetze/
echo
echo `date`
echo "    Input file: /mnt/lxfs/scratch/skalspal/Simulation/Stuetze/radi_column.fds"
echo "     Directory: `pwd`"
echo "          Host: `hostname`"
echo "----------------" >> /mnt/lxfs/scratch/skalspal/radi_column.qlog
echo "started running at `date`" >> /mnt/lxfs/scratch/skalspal/radi_column.qlog
mpirun -n 10 /mnt/lxfs/scratch/skalspal/FDS/bin/fds /mnt/lxfs/scratch/skalspal/Simulation/Stuetze/radi_column.fds
echo "finished running at `date`" >> /mnt/lxfs/scratch/skalspal//mnt/lxfs/scratch/skalspal/Simulation/Stuetze/radi_column.qlog

Thank you very much for your help!

**Comment by rmcdermo** [comment]
Ok thanks for reporting back.  Please close the issue if all is working.
