### ISSUE TITLE
Bug in colouring Smokeview particles

### ISSUE THREAD

**Issue by mspearpoint** [firemodels/fds#10646]
If I create two particle classes with different colours then when I try to view the two types, the colours only works for one of them. I went back to version 6.4.4 (somewhat at random) and the colouring works as expected. Happy to share an example case if that helps but here is a snippet from my Smokeview input:

CLASS_OF_PARTICLES
Exit 1  % % agent_class1
0.20000      0.00000      0.20000
0

PROP
 agent_class1
  1
 evacuationz_agent_1
  3
 R=255
 G=0
 B=0

CLASS_OF_PARTICLES
Exit 2  % % agent_class2
0.20000      0.00000      0.20000
0

PROP
 agent_class2
  1
 evacuationz_agent_2
  3
 R=0
 G=0
 B=255

Sorry, first time I have posted an issue here so I might not be doing it the correct way :(

**Comment by rmcdermo** [comment]
@mspearpoint Thanks for the report.  Perfectly executed!  We'll take a look

**Comment by rmcdermo** [comment]
Ahhh... yes, I see now... this looks to be EVAC-related.  We've deprecated support for EVAC (long story).  I will ask Gregor to see if he can figure this out.

**Comment by rmcdermo** [comment]
Well, if you are trying to hack the smv file, we'll probably need your FDS input file to get started.  Please post whatever you used for 6.4.4 (append ".txt" to the end of it so it will upload to GitHub).

**Comment by mspearpoint** [comment]
[objects.txt](https://github.com/firemodels/fds/files/8772695/objects.txt)
[smokeview.prt5.txt](https://github.com/firemodels/fds/files/8772696/smokeview.prt5.txt)
[smokeview.smv.txt](https://github.com/firemodels/fds/files/8772697/smokeview.smv.txt)

Yes I am 'hacking' the files to create an animation for my evacuation model - I did this quite a few years back and it worked as I wanted but now I think there is a bug. It might be me that has messed up though. Anyway - see attached.

**Comment by gforney** [comment]
I'm seeing black particles with both 6.4.4 and the latest smokeview ie the same behavior.  what did you do in 6.4.4 to see what you wanted?

**Comment by mspearpoint** [comment]
To change the colours I go through the menus Show/Hide > particles > Draw > evacuationz_agent_1 which should then redraw the particle as a 'body shape' with a coloured shirt. Then do the same to modify evacuationz_agent_2 which should have a different colour shirt (i.e. red vrs blue). This works fine in older versions (my colleague used 6.7.15) but when I download 6.7.18 this process did not work and all of the shirts were the same colour.

**Comment by gforney** [comment]
![particle_settings](https://user-images.githubusercontent.com/12403014/170356619-7ae71700-dd3e-41ee-8dfc-74bb9be78949.png)

a while ago I added an option to smokeview to speed up loading of particle files. this is what caused the problem with your case.  to turn off this option, 

1. open particle bounds dialog box (select Dialogs>File/Data/Coloring menu item)
2. select Particle then Settings tab
3. uncheck "Fast loading" checkbox
I'll modify smokeview so that smokeview does not use this option when loading evacuation files

**Comment by mspearpoint** [comment]
Thanks - it is not really an evacuation file per se, it is a combination of the zone model output functionality coupled with a way to animate agent movement using the particle capability. However, am I right in thinking you have just updated the software to 6.7.19 as I have just downloaded this and it seems to be working fine now without having to change the fast loading setting.

**Comment by gforney** [comment]
perhaps a bug I forgot I fixed then.  let me know if problem arises again
