### ISSUE TITLE
impi_intel_linux_openmp_db gives error in simple case with latest intel ifx compiler

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#10647]
Set the env var:
export INTEL_IFORT=ifx

and compile the impi_intel_linux_openmp_db target.

Set OMP_NUM_THREADS=1

Run the following case:

&HEAD CHID='test', TITLE='test' /
&MESH IJK=64,1,64, XB=0.0,6.283185307179586,-1.0,1.0,0.0,6.283185307179586 /
&MISC SIMULATION_MODE='DNS' /
&TAIL /

I get the following (only with this target and ifx):

 Job TITLE        : test
 Job ID string    : test

forrtl: severe (151): allocatable array is already allocated
Image              PC                Routine            Line        Source             
fds_impi_intel_li  0000000007C600BE  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000000EFF4BA  divgdivergence_pa         836  divg.f90
libiomp5.so        00002ACD9ECCE893  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002ACD9EC42429  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002ACD9EBFE425  __kmpc_fork_call      Unknown  Unknown
fds_impi_intel_li  0000000000EEC2DB  enthalpy_advectio         835  divg.f90
fds_impi_intel_li  0000000000EE7CF4  divergence_part_1         618  divg.f90
fds_impi_intel_li  0000000000F0BC29  fds                       424  main.f90
fds_impi_intel_li  000000000040B722  Unknown               Unknown  Unknown
libc-2.17.so       00002ACDA1B88505  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  000000000040B629  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
This little program demonstrates the problem
```
PROGRAM OPENMP_TEST

!$ USE OMP_LIB
IMPLICIT NONE (TYPE,EXTERNAL)

INTEGER :: OPENMP_AVAILABLE_THREADS,N
REAL, ALLOCATABLE, DIMENSION(:) :: A

!$OMP PARALLEL
!$OMP MASTER
!$ OPENMP_AVAILABLE_THREADS = OMP_GET_NUM_THREADS()
!$OMP END MASTER
!$OMP BARRIER
!$OMP END PARALLEL

WRITE(0,*) 'OPENMP_AVAILABLE_THREADS=',OPENMP_AVAILABLE_THREADS

N = 4

!$OMP PARALLEL PRIVATE(A)
ALLOCATE(A(N))
DEALLOCATE(A)
!$OMP END PARALLEL

ALLOCATE(A(N))  ! Comment these 2 lines and the program will run successfully
DEALLOCATE(A)

!$OMP PARALLEL PRIVATE(A)
ALLOCATE(A(N))
DEALLOCATE(A)
!$OMP END PARALLEL

END PROGRAM OPENMP_TEST
```
Compile the program
```
ifx -qopenmp -liomp5 -o openmp_test openmp_test.f90
```
I put in a support ticket with Intel.

**Comment by mcgratta** [comment]
Intel acknowledged the bug and is working on it.

**Comment by mcgratta** [comment]
This is still a bug in 
```
ifx (IFORT) 2022.2.1 20221020
```
