### ISSUE TITLE
FDS 6.7.8 Unassigned SPEC variables

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#10649]
Based on Jason's comment in this [post](https://groups.google.com/g/fds-smv/c/O5BlOPDJGkA/m/l6cWqSxgAQAJ):

> In your case, you should not ignore that warning. Please read the user's guide discussion on the default method via which FDS defines the specific heat of a user defined species when no user defined specific heat is provided.

Now I have tried to understand the method based on sections 15.1.1 and 15.1.2.

For this fuel
```
&REAC FUEL = 'MY FUEL'
FORMULA = 'C3H8O3N4'
HEAT_OF_COMBUSTION = 46124. /
```

I get the following warning

```
WARNING: SPEC MY FUEL is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.
```

Section 15.1.2 says
> For reactions with species that are not included in Table 14.1, there are several options to ensure that all of the enthalpies of formation are specified.
> Option 1: Specify Enthalpy of Formation
> Option 2: Specify Heat of Combustion
> Option 3: Use of EPUMO2

I don't understand why I get this warning when I use option 2.

For the verification case [energy_budget_adiabatic_two_fuels.fds](https://github.com/firemodels/fds/blob/master/Verification/Energy_Budget/energy_budget_adiabatic_two_fuels.fds) I get a similar warning:

```
WARNING: SPEC POLYURETHANE is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.
WARNING: SPEC WOOD is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.
```

Where is my mistake?

**Comment by drjfloyd** [comment]
This is only a warning, and this warning is written any time your input includes a species not in the predefined list. If you have defined all required species parameters or if the default behavior is acceptable, then you can ignore he warning.

A gas SPEC needs a SPECIFIC_HEAT, CONDUCITIVTY, VISCOSITY, DIFFUSIVITY, and a ENTHAKPY_OF_FORMATION.  The three options you list only define the last property. The others are still undefined, and FDS will default to SPECIFIC_HEAT being defined assuming GAMMA=1.4 and the others computed using the MW based on the REAC plus the NITROGEN Lennard-Jones potential parameters.

**Comment by gjaeger** [comment]
@drjfloyd Thanks. I understood the description in the User's Guide that only my last property must be defined. I didn't connect the warning with all properties.
The only question that remains beyond this issue is which behavior is acceptable and which is not. When can I ignore the warning? ;-)

**Comment by drjfloyd** [comment]
I cannot tell you what is or is not acceptable for your specific usage of FDS. 

If you are doing DNS, you really should use the real properties. Otherwise you might want to consider how much of the species is present in the domain. For example, in many simulations fuel concentrations are low everywhere except perhaps right at the burner. You might decide it is acceptable for there to be some possible error at the burner surface. With the exception that having a bad specific heat from using the gamma=1.4 assumption can result in issues with the extinction model. Though that is not likely if you keep the fuel MW low.

**Comment by gjaeger** [comment]
> I cannot tell you what is or is not acceptable for your specific usage of FDS.
I don't expect this either. Your notes are helpful. A wonderful task.
