### ISSUE TITLE
Reactant Combustion Problems

### ISSUE THREAD

**Issue by xun21** [firemodels/fds#10658]
Hi 
 everyone, I have a problem that when I define diesel as the reactant to burn, I can run it in FDS version 6, but I can't run it in FDS version 5. What is the reason? attach my code,Is there something wrong with my code?
many thanks!!

&REAC ID='Diesel fuel; solarium',
      FYI='This is.A. Prediction of dangerous fire factors in a room: Textbook.',
      FUEL='REAC_FUEL',
      C=12,
      H=23,
      SOOT_H_FRACTION=0.0,
      CO_YIELD=0.122,
      SOOT_YIELD=0.071/

**Comment by rmcdermo** [comment]
REAC line parameters are not backward compatible.

**Comment by xun21** [comment]
Hi Sir What does that mean? Can you tell me in detail?

**Comment by rmcdermo** [comment]
The reaction schemes in FDS 6 are different than those used in FDS 5.  The input file parameters are different.  Please use the latest code.

**Comment by xun21** [comment]
Thank you for your explanation. I checked the relevant information, but I don't know how to define the reactant in fds5. Can you elaborate on how to define it in fds5? thank you .

**Comment by rmcdermo** [comment]
No.  Please use the latest code.
