### ISSUE TITLE
fds 6.7.8 crashes with fds_local on windows 64 for an immersed boundary case

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#10668]
When using **fds_local -o 1 example_5.fds** FDS crashes. Just using **fds example_5.fds**  works.

The error message is given below and an example file is attached. 

The problem only appears on a windows pc. The mac os or a linux system do not show the same problem.

 Starting FDS ...

 MPI Process      0 started on BYG-A201-BPHU

 Reading FDS input file ...

 Fire Dynamics Simulator

 Current Date     : June 10, 2022  11:06:08
 Revision         : FDS6.7.8-0-gfbf3e11ee-release
 Revision Date    : Tue May 24 18:07:45 2022 -0400
 Compiler         : Intel ifort 2021.5.0
 Compilation Date : Wed 05/25/2022  11:40 AM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.4 for Windows* OS

 Job TITLE        : Test specified mass flux bc on sphere and mass conservation.
 Job ID string    : Example_5

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
impi.dll           00007FFF178ACB65  Unknown               Unknown  Unknown
impi.dll           00007FFF178B3A43  Unknown               Unknown  Unknown
impi.dll           00007FFF17B06506  Unknown               Unknown  Unknown

[Example_5.txt](https://github.com/firemodels/fds/files/8877495/Example_5.txt)

**Comment by marcosvanella** [comment]
Thank you Bjarne we'll have a look. 
Glenn, can you run the case in your windows machine to reproduce the error? Thanks.

**Comment by mcgratta** [comment]
I'll test it on my computer.

**Comment by mcgratta** [comment]
This appears to be a problem with the `fds_local` script. I can run the job successfully like this
```
mpiexec -n 1 -localonly fds Example_5.fds
```
For the moment, use this command instead of `fds_local`.

**Comment by gforney** [comment]
using the -c option, the command
fds_local -o 1 -c Example_5.fds
generates the following
mpiexec -localonly -n 1    -env I_MPI_FABRICS=shm fds Example_5.fds

if I run the above line after removing -env I_MPI_FABRICS=shm , it works.  kevin, do we need the I_MPI_FABRICS entry?

**Comment by gforney** [comment]
also, if I run using the following (which is what fds_local generates)
mpiexec -localonly -n 1 -env I_MPI_FABRICS=shm fds Example_5.fds
I get the same error 

Job ID string    : Example_5

forrtl: severe (157): Program Exception - **access violation**
Image              PC                Routine            Line        Source
impi.dll           00007FF8EF7E1711  Unknown               Unknown  Unknown

**Comment by marcosvanella** [comment]
Noted the same, yet the problem only shows up when invoking the mkl cluster solver. I'll test this in an isolated piece of code. Might need help with the windows compiling.On Jun 13, 2022 9:44 PM, gforney ***@***.***> wrote:
also, if I run using the following (which is what fds_local generates)
mpiexec -localonly -n 1 -env I_MPI_FABRICS=shm fds Example_5.fds
I get the same error
Job ID string    : Example_5
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
impi.dll           00007FF8EF7E1711  Unknown               Unknown  Unknown

**Comment by gforney** [comment]
Also I was concerned I did not include the correct Intel files in the bundle but I see the same problem when using fds I built (rather than fds from bunde) and mpiexec from the oneapi I installed.

**Comment by mcgratta** [comment]
I don't think we need the I_MPI_FABRICS setting. The -localonly option indicates that the job is to run on one computer and I assume that the fabric is set appropriately.

**Comment by gforney** [comment]
I will take it out when -localonly is used

**Comment by gforney** [comment]
try you case with nightly bundle
https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing

**Comment by bphusted** [comment]
I tried the nightly build. FDS no longer crashes, but there seems to be a problem with the parameter -o
Regardless of what I set it to, - it seems to use 4 openmp thread each time. Please see below, I asked for two openmp, but got four.

C:\Users\bphu\Documents\summer_school_2022\Examples_Marcos>fds_local -o 2 Example_5.fds

 Starting FDS ...

 MPI Process      0 started on BYG-A201-BPHU

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : June 14, 2022  19:58:05
 Revision         : FDS6.7.8-48-g8cfd1be80-nightly
 Revision Date    : Sun Jun 12 09:18:52 2022 -0400
 Compiler         :
 Compilation Date : Tue 06/14/2022  11:50 AM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.4 for Windows* OS


 Job TITLE        : Test specified mass flux bc on sphere and mass conservation.
 Job ID string    : Example_5

 Time Step:      1, Simulation Time:     0.002 s

**Comment by gforney** [comment]
I'll take a look

**Comment by mcgratta** [comment]
I have the same problem. The -o option does not give me the right number of OpenMP threads.

**Comment by mcgratta** [comment]
The -o option is ignored, and whatever OMP_NUM_THREADS has been set is used.

**Comment by gforney** [comment]
I set the default number of threads to OMP_NUM_THREADS  after -o was parsed rather than before.  I'll generate another nightly bundle with the fix

**Comment by gforney** [comment]
I had typo in the variable used to specify the number of openmp threads , bundle at link below should work now.  let me know if you still see a problem.  thanks for pointing out the problems
https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing

**Comment by bphusted** [comment]
Thanks. I have tested it, - also with different combinations with -p and -o and I did not find any problems, so the case can be closed
