### ISSUE TITLE
FDS6.7.6 SMV6.7.16 HRR curve for burning material

### ISSUE THREAD

**Issue by nadir0707** [firemodels/fds#10672]
Hi all
I m working on simlation using a pool fire and materials ,where i need a curve for burning materials only ,is that possibole in FDS ? becaus the curve that is given after the calculation is taking the HRR of pool fire in considuration( totale HRR) ,how can i get only HRR for burning materials (materials that got ignited and burned)?
waiting for your reply
thank you

**Comment by rmcdermo** [comment]
Please post this question to the discussion forum.  Thanks

**Comment by nadir0707** [comment]
done thank you
