### ISSUE TITLE
DEVC QUANTITY MASS FLOW - SPEC n-heptane errors on WINDOWS (FDS 6.7.8)

### ISSUE THREAD

**Issue by AzadHmz** [firemodels/fds#10673]
Hello,
I have been trying to run a model on FDS 6.7.8 on windows (the model which I run it on FDS 6.7.7 with no problem), but I receive these errors (attached). I have also attached the file.

[room_fire.txt](https://github.com/firemodels/fds/files/8892564/room_fire.txt)
![error1](https://user-images.githubusercontent.com/84109790/173394562-a7fc4eb0-e8de-410f-af21-42d4b3a60a9a.JPG)

**Comment by drjfloyd** [comment]
This is a post best submitted to the forum. But first the error message has told you exactly what the problem is.  This is discussed in the release notes Wiki (https://github.com/firemodels/fds/wiki/FDS-Release-Notes) and in the User's Guide..
