### ISSUE TITLE
FDS6.7.6 SMV6.7.16 HRR curve for burning material

### ISSUE THREAD

**Issue by nadir0707** [firemodels/fds#10674]
Hi all
I m working on simulation using a pool fire and materials ,where i need a curve for burning materials only, is that possibole in FDS ? becaus the curve that is given after the calculation is taking the HRR of pool fire in considuration(total HRR) ,how can i get only HRR for burning materials? (a curve for materials that ignited and burned).
waiting for your reply
thank you

**Comment by drjfloyd** [comment]
You already posted this and were told to submit this to the discussion forum: https://groups.google.com/g/fds-smv

**Comment by nadir0707** [comment]
Ok mb i didnt get it at first time. I ll try.
thanks

Le lun. 13 juin 2022 à 19:38, Jason Floyd ***@***.***> a
écrit :
