### ISSUE TITLE
GEOM initialization error

### ISSUE THREAD

**Issue by gdicr** [firemodels/fds#10706]
Running a case with flow vanes created with GEOM. 

Input file initializes and runs in 6.7.6 but gives error in 6.7.8

Error code from debug in 6.7.8:
forrtl: severe (408): fort: (3): Subscript #1 of the array AREA_UNKZ_LOC has value -11 which is less than the lower bound of 1

Image              PC                Routine            Line        Source             
fds_impi_intel_li  000000000A72010F  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000001A5557A  cc_scalars_ibmcci        6408  ccib.f90
fds_impi_intel_li  0000000001A42EC2  cc_scalars_ibm_mp        6279  ccib.f90
fds_impi_intel_li  0000000003F8A2BC  MAIN__                    284  main.f90
fds_impi_intel_li  000000000040A222  Unknown               Unknown  Unknown
libc-2.17.so       00002B83BF065555  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  000000000040A129  Unknown               Unknown  Unknown
srun: error: blaze001: task 0: Exited with exit code 152
srun: Terminating job step 3889154.0

Here's the input file:
[cv_vaned_30ndeg.txt](https://github.com/firemodels/fds/files/8969069/cv_vaned_30ndeg.txt)

**Comment by marcosvanella** [comment]
Thank you, we'll have a look.

**Comment by rmcdermo** [comment]
I don't know that this was every supported.  But thin vanes are not supported currently.

Generally, GEOM is not supported.  It is in alpha testing at the level of the verification tests in our repository.

<img width="752" alt="Screen Shot 2022-06-23 at 1 09 43 PM" src="https://user-images.githubusercontent.com/4418497/175356168-61ee9e82-4610-4254-900c-a9964e2b7040.png">

**Comment by marcosvanella** [comment]
Hi Giovanni, we don't support zero thickness geometries at the moment (never have). You need a continuity of cells inside the geometry volume for the pressure and stress computation to work, and avoid flow penetration. I'll have a look at the error you are seeing.
