### ISSUE TITLE
Temperature error with GEOM and UGLMAT/ULMAT with NOISE or STRATIFICATION

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10707]
The attached is a simple 1 mesh case using UGLMAT and only works if both NOISE and STRATIFICATION are False.

[test.fds.txt](https://github.com/firemodels/fds/files/8970787/test.fds.txt)

**Comment by rmcdermo** [comment]
<img width="752" alt="Screen Shot 2022-06-23 at 4 39 13 PM" src="https://user-images.githubusercontent.com/4418497/175395416-6b0234d7-c05f-4021-aa1f-f11735bae77f.png">

**Comment by marcosvanella** [comment]
Looking at the stratification part (no noise) it seems what is driving the flow is the gravity terms GZ(I)+RRHO*(0.5*(RHO_0(K)+RHO_0(K+1))*GZ(I) (etc.) not being zero in VELOCITY_FLUX. I note this even setting CCVOL_LINK=0. 

I see something similar with mesh refinement boundaries where a flow field starts developing from quiescent conditions. See attached case. 
[test_2.fds.txt](https://github.com/firemodels/fds/files/8995063/test_2.fds.txt)

**Comment by rmcdermo** [comment]
Does this happen if you explicitly set the atmospheric interpolation.

**Comment by rmcdermo** [comment]
The stratification issue seems to be solved.  I'll close this one.  (We have other issues, but I'll post to a different thread)
