### ISSUE TITLE
ERROR on newer FDS versions

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#10716]
Dear everyone,

I am trying to simulate a flashover in a living room to reproduce this video : https://www.youtube.com/watch?v=BtMmymOxdjc&t=182s

![image](https://user-images.githubusercontent.com/94290527/176455756-9dffe009-591f-4b4d-af60-6a736265c1bc.png)

For the reaction, I used polyurethane. However, depending on which FDS version I use, I encounter an error :

- **FDS6.7.7-0-gfe0d4ef38-release**, works fine

- **FDS6.7.8-0-gfbf3e11ee-release** 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/94290527/176457763-f8bbf9b6-30b4-4e6d-881c-f35439ceecf6.png)

- **FDS6.7.8-95-gedef58a27-nightly**
![image](https://user-images.githubusercontent.com/94290527/176458623-ac4bccc9-6c08-46e1-bf13-2f5218868b52.png)

Here is my txt :
[flashover.txt](https://github.com/firemodels/fds/files/9011398/flashover.txt)
 
These simulation were run on multiple computers, using both windows and linux, and always gave same errors no matter the OS or the computer. I also used the same folder / fds file for each simulation.

Do not hesitate to contact me for more information.

**Comment by marcosvanella** [comment]
Hi Vianey, comment all GEOM lines and run the case. If it runs, write all objects as OBSTS and test again. If it runs we know the issue is related to geometries. We are doing major changes in how geometries work,  I recommend to use OBSTS for the time being.

**Comment by ghost** [comment]
Hi, thanks for your help ! Indeed, it runs fine without GEOM (FDS6.7.8-95-gedef58a27-nightly) . However, the warning is still here.

![image](https://user-images.githubusercontent.com/94290527/176621593-ae01c164-a201-4723-b66d-39a8efd0c44b.png)

By the way, as it runs fine on an older FDS version, should I consider that it runs something "innapropriate" or is it fine ?

**Comment by mcgratta** [comment]
This warning is new, but it pertains to all previous versions. It simply means that FDS assumes the properties of nitrogen except for the specified formula and molecular weight, which it can infer from the formula.

**Comment by marcosvanella** [comment]
Hi Vianey, 6.7.7 had it's own issues on geometries, and that is the reason we are changing the formulation. If you want to help us understand the instability in this case try making the case as simple as possible such that it still shows the issue. Post the input file and binaries in a tarball and we'll run it here.

**Comment by ghost** [comment]
Hi, here is a simplified version with the sofa only. I encounter the same error as previously for the FDS6.7.8-95-gedef58a27-nightly version.

[flasherror.zip](https://github.com/firemodels/fds/files/9027639/flasherror.zip)

Thank you very much.

**Comment by marcosvanella** [comment]
Thank you Vianey, we'll have a look.

**Comment by drjfloyd** [comment]
Marcos, the simplified case in flasherror.zip starts timestepping now.

**Comment by marcosvanella** [comment]
Yes, the case has run over 2K steps in burn so far. Closing.
<img width="638" alt="Screenshot 2023-04-13 at 3 55 28 PM" src="https://user-images.githubusercontent.com/7450069/231869005-7d9d1e44-124c-4cf1-9e4e-4ae85c3a7914.png">
