### ISSUE TITLE
Atom error trying to reproduce 2 step reaction scheme from .out file info

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10715]
I took this dummy case that generates the lumped species and reaction stoichiometry for the N_REACTION=2 case for methane,

[methane.fds.txt](https://github.com/firemodels/fds/files/9004257/methane.fds.txt)

Then I tried to recreate the scheme manually by specifying lumped species and using the molar stoichiometric coefficients from the .out file.

[lumped_2reac.fds.txt](https://github.com/firemodels/fds/files/9004280/lumped_2reac.fds.txt)

I get an atom error of 1 O atom.  I went into dump and unformatted the output to increase the number of digits, but I still get the error.  If I am doing something wrong, please let me know.  In my mind, it should be pretty easy to do this manually from copying the lists in the .out file.  I'm not sure this one is just a matter of increasing precision (though we should do that if necessary).  My suspicion is that we have an error in how we write things to the .out file, but I have not found it yet.

**Comment by rmcdermo** [comment]
I simplified down to one reaction.  I set the CO_YIELD=MW_CO/MW_CH4, so that all the C goes to CO, as in the 2 step scheme.  The good news is that this FDS case gives the same information in the .out file as the first reaction in the 2 step scheme.  But when I try to create the 1 reac equivalent manually, I get the same 1 O atom error (plus a small amount of C).

[lumped_1reac.fds.txt](https://github.com/firemodels/fds/files/9005070/lumped_1reac.fds.txt)

[methane_CO_YIELD.fds.txt](https://github.com/firemodels/fds/files/9005072/methane_CO_YIELD.fds.txt)

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
In your PRODUCTS you have CO2 twice. Looks like SPEC_ID(4) should be CARBON MONOXIDE.

**Comment by rmcdermo** [comment]
Ugh.  Thanks!  Sorry for the hassle.  Works great.

**Comment by drjfloyd** [comment]
Those can be the hardest errors to see.
