### ISSUE TITLE
RADIATIVE_FRACTION as global constant

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10732]
The coding for the variable RADIATIVE_FRACTION has gotten confusing.  There are now two versions, one that is read on the REAC line and populates RN%CHI_R and one that is a global constant in cons, and I think read on the INIT line and used in init.f90.  (about line 279 of init.f90)

```
IF (N_REACTIONS>0) THEN
   M%CHI_R = MAX(0._EB,RADIATIVE_FRACTION*EVALUATE_RAMP(T_BEGIN,REACTION(1)%RAMP_CHI_R_INDEX))
ELSE
   M%CHI_R = MAX(0._EB,RADIATIVE_FRACTION)
ENDIF
```

I have a feeling this is a holdover from before we had the different REAC and INIT variants.  It looks to me like this RADIATIVE_FRACTION will be set by the INIT default (which is 0).

Is this coded the way we want it?  I would prefer that RADIATIVE_FRACTION just be an input parameter and that RN%CHI_R and IN%CHI_R should be used outside of read.90 to transfer the radiative fraction to M%CHI_R, which is finally used in radi.

**Comment by drjfloyd** [comment]
The RADIATIVE_FRACTION on INIT was a recent addition to support the HEAF work. HRRPUV on INIT is not tied to any REAC. It is just a volumetric heat source. It needed a method of being able to specify how much of  that HRRPUV was convective and how much was radiative that wasn't tied to a REAC. That way you could have an R_F for INIT that differed from the global R_F set on COMB.

**Comment by drjfloyd** [comment]
The RADIATIVE_FRACTION in read_init does not set the variable in cons.f90.  In read_init RADIATIVE_REACTION is defined locally which means  the global variable is not used.

**Comment by rmcdermo** [comment]
Where is it set locally?  I can't find that.

**Comment by rmcdermo** [comment]
It seems to me that the RADIATIVE_FRACTION on INIT should go into IN%CHI_R and that should then go directly to M%CHI_R for the appropriate region.  I'm not seeing a need for the RADIATIVE_FRACTION defined in cons.  And I think this is getting confusing keeping it separated from the input parameters in read.

**Comment by mcgratta** [comment]
RAD_FRAC in cons.f90 might be used because RAD_FRAC can be set on the COMB or REAC or multiple REAC lines. I think the RAD_FRAC in cons.f90 was to hold a value set on another line. That being said, we can probably do this better. Let me take a look .

**Comment by mcgratta** [comment]
Now `RADIATIVE_FRACTION` is defined within the `READ` module. It can be set on `COMB` or `REAC` or `INIT`.
