### ISSUE TITLE
Wake reduction for droplets

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10745]
These parameters are not documented. Is this supposed to be a replacement for `WAKE_REDUCTION`?
```
/PART/PRIMARY_BREAKUP_DRAG_REDUCTION_FACTOR
/PART/PRIMARY_BREAKUP_LENGTH
```

**Comment by rmcdermo** [comment]
The PRIMARY_BREAKUP parameters have been documented with PR #10879
