### ISSUE TITLE
Unable to install FDS 6.7.9, SMV 6.7.21 in centOS based server

### ISSUE THREAD

**Issue by Sagar-Singhal** [firemodels/fds#10746]
I am trying to install FDS in centOS based server. I am following the instructions given on Installation Instruction sheet:-
https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-on-a-Linux-Cluster

While testing the installation by typing fds. I am getting the error (Image attached).
'GLIBC_2.14' not found (required by fds)
I don't have access to install GLIBC using sudo commands.
I have checked with our administration, they will not be able to provide support for this old server.
Can you please suggest any other method to install fds correctly? 

Thanks,
Sagar

**Comment by Sagar-Singhal** [comment]
![error_msg](https://user-images.githubusercontent.com/97778655/177775706-72497e36-891b-4aff-8975-e36b0a10df45.png)

**Comment by mcgratta** [comment]
We'll take a look at this. Worse comes to worse you might need to checkout the fds GitHub repository and compile the code yourself.

**Comment by gforney** [comment]
Which version of centos do you have?

**Comment by mcgratta** [comment]
We build on

centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by gforney** [comment]
type
cat /etc/redhat-release

**Comment by Sagar-Singhal** [comment]
CentOS release 6.2 (Final)

**Comment by mcgratta** [comment]
We cannot support something that old with a compiled executable. You need to compile FDS yourself.

**Comment by Sagar-Singhal** [comment]
Ok Thanks.

**Comment by Sagar-Singhal** [comment]
How to compile FDS in CentOS 6.2? Is there any guide available.

**Comment by mcgratta** [comment]
We have some basic information [here](https://github.com/firemodels/fds/wiki/FDS-Compilation), but we assume that you have properly configured your cluster to compile and run a Fortran program that uses MPI. There are too many different configurations for us to provide detailed instructions.

**Comment by gforney** [comment]
don't know if the Intel Oneapi compilers support Centos 6.2.  You could try installing them .  if Centos 6.2 is supported then you can build FDS using these compilers.  The oneapi installers should tell you pretty quickly whether they can be installed or not.

if oneapi is not supported then it is much more difficult.  you would have to install gfortran version 9 or later (dont know if tha is available on 6.2) , download the openmpi source and build the openmpi library.

an easier solution I think would be ot update your OS to a more recent version

**Comment by drjfloyd** [comment]
Looks like needs Centos 7
https://www.intel.com/content/www/us/en/developer/articles/system-requirements/intel-oneapi-base-toolkit-system-requirements.html

**Comment by liu-shaobo** [comment]
download and Install glib-2.14 or higher from gnu.

**Comment by johodges** [comment]
I went through this process on a centos6 cluster earlier this year. It was not trivial, but it is possible. If you do decide to go this route, you essentially have to build the full auto make and ld toolkit from source before you can get the right version of glibc on centos6. You will also need to compile multiple versions of gcc/gfortran to work your way up to the latest. Once you get the dependencies built, you can run the recompiled fds versions and build the latest source on centos6 using the gnu compiler.  

Don't waste your time on this unless you do not have other options and you have a lot of familiarity with building packages from source. As suggested above, upgrading to a newer centos is a much better option.
