### ISSUE TITLE
HVAC input parameters are not documented

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10744]
What is the status of these inputs?
```
/HVAC/QFAN_BETA
/HVAC/SURF_ID
```

**Comment by drjfloyd** [comment]
Working on them.

Have an overhaul of the HVAC routine in the works that will get QFAN_BETA out of beta plus addressing some other issues related to HVAC_MASS_TRANSPORT.  It is mostly done. Have  the coding finished (I think). Am running the HVAC verification cases now and will need to wrap up some manual updates.

SURF_ID is an input to support duct heat transfer but needed to clean up the QFAN and H_M_T stuff first.

**Comment by mcgratta** [comment]
Good thanks. I'll keep the issue open. I'm trying to sort out all these undocumented inputs long before a release of 7. Also, if you think you need to change any HVAC parameter names, now might be the time.

**Comment by drjfloyd** [comment]
Closing this. I removed SURF_ID from master for now and just have it in my branch for duct heat transfer. The other inputs are now defined.
