### ISSUE TITLE
weird behavior of fire propagation on vegetation with newer FDS version...

### ISSUE THREAD

**Issue by gmsafir** [firemodels/fds#10750]
Dear all,

I run the same configuration with FDS6.7.5 and FDS6.7.8, and get a very weird unrealisatic result with the newer version (fire auto-extinguishes progressily), while the behavior is realistic for the older one (fire is well sustained).
Could you please investigate on this problem ?
[fire_propag.zip](https://github.com/firemodels/fds/files/9083818/fire_propag.zip)

**Comment by ericvmueller** [comment]
I can take a look

**Comment by gmsafir** [comment]
thanks Eric

**Comment by ericvmueller** [comment]
There have been many changes between these versions, but running a bisect points to 1fbac2df02c655d0d72c238b863d4a6bd31643cf as the source of the difference. This commit fixed issue #10573, where the particle emissivity was not accounted for in the radiation transport solver but was included in the solid phase solution. You can see that if I run 6.7.8 but revert that specific commit, the HRR is much closer to the older solution. 

While version 6.7.5 gives an answer that is more in line with what you are expecting, this change fixed an inconsistency in the formulation and you should use version 6.7.8 or later. As you know, there are many parameters involved here, so you may need to test others to understand why the fire is decaying over time.

![image](https://user-images.githubusercontent.com/13366803/178330567-d03a01af-1b61-44bd-a5a7-5666bf8834a0.png)

**Comment by gmsafir** [comment]
Eric, reading the changes performed in 1fbac2d, I thought naively that taking EMISSIVITY=1 (in MATL and SURF) would make the situation equivalent to your curve '6.7.8 revert 1fbac2d' but it is not. What other changes did I miss?

**Comment by ericvmueller** [comment]
The difference is that in your original simulations the material `EMISSIVITY` was the default value (0.9). However, from the perspective of the radiation solver it was effectively 1. So more energy was being added to the radiation transport than was being emitted from the hot particles. There is no way to mimic this by tweaking `EMISSIVITY` in 6.7.8.

You could try to confirm this by doing the opposite. If you set `EMISSIVITY` to 1 in your 6.7.5 simulation, then there shouldn't be any energy imbalance and you should get the same result as 6.7.8 (also with `EMISSIVITY` of 1).

**Comment by gmsafir** [comment]
Eric, I tested 6.7.5 with EMISSIVITY=1, and I am very close to other 6.7.5 results, not to the 6.7.8 results.

The param file is this precise one for the 5 simulations:
[fire_propag_lab1_modif.fds.txt](https://github.com/firemodels/fds/files/9094323/fire_propag_lab1_modif.fds.txt)


Here are the simulations that I run:
- 903176 - sim1: run 6.7.5, no emissivity specified
- 903658 - sim2: run 6.7.8, emissivity=1 (matl only)
- 903700 - sim3: run 6.7.8, emissivity=1 (matl & surf)
- 903948 - sim4: run 6.7.5, emissivity=0.9
- 903999 - sim5: run 6.7.5, emissivity=1

The results are shown to be grouped by version. So I suspect that the change 1fbac2d does not have a big impact in the comparison btw 6.7.5 and 6.7.8:
![compa_675_678](https://user-images.githubusercontent.com/99477211/178522777-813ce375-58f4-45cb-924e-0817b484754d.PNG)

**Comment by ericvmueller** [comment]
Because the revert command only undid the changes associated with 1fbac2d, we can attribute the changes in the plot I posted to that specific commit.

In the attached file, it doesn't look like you modified the ignitor particles. In order to replicate the emitted flux from these particles in your 6.7.5 case, you should set `EMISSIVITY` to 1 on the associated `SURF` in your 6.7.8 case. I have not seen how this affects the long term decay because I am still running a test, but this at least ensures we are comparing the same strength of ignition.

**Comment by gmsafir** [comment]
ok, now indeed (with EMISSIVITY=1 for the ignitor particles), the 6.7.8 ressembles the 6.7.5. Thanks for the clarification, Eric

**Comment by gmsafir** [comment]
now the first 10s of simulation are clear, with version 6.7.8 with EMISSIVITY=1 being equivalent to 6.7.5. However, what still remains is the collapse of the fire front after 40-50s, with or without EMISSIVITY=1 in version 6.7.8. I tester 6.7.7 which exhibits the same collapse as 6.7.8. Could you please help me locate what is causing this collapse ?

Here below is the time step 73.5s for version 6.7.7:
![v6 7 7_ts73 5s](https://user-images.githubusercontent.com/99477211/178715680-56af5ed4-5284-489a-8583-6c5acd4579fa.PNG)

**Comment by ericvmueller** [comment]
I am running some tests but it may take a while because of the amount of simulation time required for the decay to become clear. Have you tried any lower resolution runs and found the same difference in fire stability between different versions?

**Comment by gmsafir** [comment]
Thx Eric, you are right: it takes a while too go until it exhibits the decay! No I did not test yet if the problem exists at lower resolution.

**Comment by gmsafir** [comment]
Hi Eric, any news about the long runs?

**Comment by ericvmueller** [comment]
Yes - I think I have identified an inconsistency which was fixed after version 6.7.6 and which leads to the decay you observe. I'm just trying to confirm this and will let you know.

**Comment by ericvmueller** [comment]
The difference first occurred after 28c76819e19c6e87961a01fdad8a4dd3eae5da3d, and can be traced to this section of the code, which determines the drag on the fluid:
https://github.com/firemodels/fds/blob/e9c1511cf1ac21e22f9546f61d1e95fa25336ed8/Source/part.f90#L2550-L2551

Prior to that commit, the contribution from the mass flux from particles was not stored properly. If I revert just that one change from the commit (back to the wrong version), the fire sustains as shown in the plot. So you were getting the right answer for the wrong reason, but this implies you should examine the drag on the fuel bed.

You have a drag coefficient of 0.375 which seems low. If I remove this and allow the default, Reynolds-dependent coefficient, I get a sustained fire with 6.7.8. It might also be worth looking at how particles do or don't shrink as they are consumed, and how this can impact the entrainment to the trailing edge of the fire.

Unless we can identify some error with FDS, you should use the newest release.

![image](https://user-images.githubusercontent.com/13366803/180035522-87ac8561-7075-4438-9ff2-1e58ed994260.png)

**Comment by mcgratta** [comment]
Wow, I'm nominating this for a Boris award.

**Comment by gmsafir** [comment]
Hi Eric! Thanks for the nice finding! Yes, without imposing Cdrag, it perfectly propages with 6.7.8!
Our nomination for the Boris award will then be shared with you.

**Comment by gmsafir** [comment]
Eric, is it possible to ask FDS to output the drag coefficient that is Reynolds-dependent in FDS? (to see the difference with our "too low" value of 0.375)

**Comment by rmcdermo** [comment]
You can add 'PARTICLE DRAG COEFFICIENT' to QUANTITIES on the PART line.  Then C_d will be visible in Smokeview.

**Comment by ericvmueller** [comment]
I'm glad to hear it is working now! I'll go ahead and close this issue
