### ISSUE TITLE
HVAC timing function broken

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#10756]
[test.txt](https://github.com/firemodels/fds/files/9093780/test.txt)
The changes made recently to HVAC seemed to have broken the attached test case. This is a tunnel with 15 fans, all of which are controlled by RAMPs. When I ran a more complicated version of this last night, only the last fan activated. I wonder if there is some over-writing of timing parameters. When I tested just a single fan, things worked. There's something about the multiple fans. Maybe not 15, but more than one.

**Comment by drjfloyd** [comment]
I can recreate the problem with a simpler case. Some issue in transferring the HVAC solver results to array that allows MPI to pass the boundary condition.

**Comment by drjfloyd** [comment]
should be fixed now.

**Comment by mcgratta** [comment]
Thanks. I'll retry my cases.

**Comment by mcgratta** [comment]
Yup, things look OK. Thanks
