### ISSUE TITLE
Model sensitivity to FMC jumps at FMC~=2.0

### ISSUE THREAD

**Issue by amarcozzi** [firemodels/fds#10770]
I've been running FDS simulations of burning saplings examining the effect of FMC on vegetative mass loss. In the new version FDS 6.7.9, I observe a substantial change in model behavior with FMC values at around 2.0 when comparing simulation results to observed data. The sensitivity of the model to FMC at 200% is not observed in FDS version 6.7.7. I wonder if the changes discussed in  #10610 contributed to this change in model behavior.

I've attached two figures to this issue. The first shows cumulative mass loss over a range of FMC values in FDS 6.7.9, and the second shows the same for FDS 6.7.7. I have not yet performed a more fine-grained analysis of FMC values, but I wanted to bring this to the attention of the FDS community before diving into it more. I have also attached the input files and devc csv files associated with each simulation.

Thank you,
Anthony

![fmc_comparison_6_7_7](https://user-images.githubusercontent.com/13575005/178797681-c4a9538c-4775-46a6-9de5-2e5d1124063f.png)
![fmc_comparison_6_7_9](https://user-images.githubusercontent.com/13575005/178797683-0603a9de-7a0d-44b6-b997-45a501d4a20e.png)

[fmc_analysis.zip](https://github.com/firemodels/fds/files/9104686/fmc_analysis.zip)

**Comment by ericvmueller** [comment]
will take a look

**Comment by ericvmueller** [comment]
@mcgratta this appears to be a result of: https://github.com/firemodels/fds/blob/b44d21c6f876cac60592de6a3be5c9ac0fc2b5d3/Source/read.f90#L6689

so the adjustment to solid density isn't applied if the `MOISTURE_FRACTION` is greater than 2 (in the case the nominal wood density is half the water density).
In the attached example, if you modify the `MOISTURE_FRACTION` around 2 you will see the `PWT` suddenly jump to compensate for this.

Thanks for pointing this out, Anthony!

[moisture_fraction.txt](https://github.com/firemodels/fds/files/9105699/moisture_fraction.txt)

**Comment by ericvmueller** [comment]
There is also an issue that if you have multiple `SURF`s referencing the same `MATL` the adjustment to `MATERIAL(NNN)%RHO_S` is stored and then re-adjusted for each successive `SURF`.

In this example, the two particle classes should be identical, but you can see that the the `PWT` values are not.

[moisture_fraction_2part.txt](https://github.com/firemodels/fds/files/9105759/moisture_fraction_2part.txt)

**Comment by mcgratta** [comment]
If the `MOISTURE_FRACTION` is greater than 2, we cannot maintain the same volume unless we change the moisture density as well as the dry wood density. Is this what we want to do?

**Comment by rmcdermo** [comment]
Eric,
I'd like to chat about this.  I don't want to get into the situation where we have unphysical densities.  From what I can tell, we have several densities at play.

1. The material dry density.  This is obtained from drying the material, grinding it up into a fine powder, compressing it and weighing it.
2. The material dry bulk density.  This is the material density from 1 expanded to fill whatever volume you want, and this then defines a void fraction.
3. The density of water.  This is 1000 kg/m3.  Full stop.  It cannot be compressed.
4. The wet material bulk density.  This density cannot be higher than 1 + 3 times their respective volume fractions.

And perhaps there is a 5th, the vegetation bulk density, where you take a shrub that roughly fits into a cubic meter and weigh it and get a number.  And this could be wet or dry.  This density needs to be formulated as a summation over the individual particles divided by the bulk volume.

So, I think I've identified 6 densities that are all different numbers.  Can we see if we can clarify this and come up with a formulation that does not allow for material density that goes above 1 with water defined by 3.  Thanks

**Comment by ericvmueller** [comment]
yup - I agree with what you are saying here. I think what is confusing is that the densities most typically known are 2 and 3. I think to get 1 for something with cellular structure without a gas pycnometer etc. So the inputs in current cases are a combination of bulk density for 'wood' and pure material density for water, which is not consistent.

I think, from the model perspective, it could make sense to scale the water density to a bulk value, based on the FMC. From the user perspective, we need to be clear if/how the input of `DENSITY` takes on a different meaning for these porous materials. 
...I don't know that this really gives you an answer yet, but yes let's figure this out.

**Comment by mcgratta** [comment]
The above change addresses the issue of multiple `SURF` lines using the same `MATL` line and changing the material density each time.

**Comment by ericvmueller** [comment]
Looks good - the second example I posted gives consistent results for the two particle classes now. Thanks!

**Comment by mcgratta** [comment]
As for the first issue, I added an ERROR statement for the time being. If the `MOISTURE_FRACTION` is so large that moisture would have to displace all of the dry vegetation, an ERROR statement is produced.
