### ISSUE TITLE
Inconsistent dry MASS_PER_VOLUME and integrated MPUV output

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10784]
Kevin,
Have a look at this case.

[test.fds.txt](https://github.com/firemodels/fds/files/9115678/test.fds.txt)

The moisture content is set to 0.  I compute the total particle mass should be

> pi*.0762^2 * 1.2192 * 5.489 = 0.122

But the _devc file is giving 0.155, which is off by 27%, a bit too much as this scales up.

It seems that I increase the volume of the CYLINDER the relative error goes down.   But I don't see why this total mass would not be exact.

**Comment by mcgratta** [comment]
Should be fixed by this [PR](https://github.com/firemodels/fds/pull/10786)

**Comment by rmcdermo** [comment]
Works.  Thanks!
