### ISSUE TITLE
Smokeview clipping plane feature request

### ISSUE THREAD

**Issue by firemist** [firemodels/fds#10794]
It would be helpful to be able to specify clipping planes directly from the main view with shortcut keys rather than having to bring up the clipping plane box and find the exact coordinate for the plane. This request is not to replace the clipping plane box, but rather to provide a quick access to setting up (or toggling) a clipping plane visually from the main screen. 

As you'll see it described below, a great key combination would have been the unshifted or shifted 'c'/'C' key. However, the 'c' key is already heavily overloaded in Smokeview. With that in mind and that ALT-c brings up the clipping dialog box, 'c' might be defined as ctrl-alt-c and 'C' might be defined as shft-alt-c.

Here's how I envision it working (using 'c' and 'C', whatever keys might eventually be used):

1. These actions would only apply (work/execute) when one or more grid planes are active; otherwise, no action occurs.
2. The action would apply to the most recently "active" grid plane. That is, the one that most recently either moved or was turned on.
3. When one of the trigger keys is detected:
  a. If clipping is off, turn it on
    1) If "Clipping disabled", select "Clip blockages and data"; otherwise, no change to clip type
    2) If 'c' is depressed, turn on lower clipping for that plane
      a) Set the associated lower value to the value of the most recently active grid plane (x,y,z)
      b) Check the lower clip checkbox associated with that plane
    3) if 'C' is depressed, turn on upper clipping for that plane
      a) Set the associated upper value to the value of the most recently active grid plane (x,y,z)
      b) Check the upper clip checkbox associated with that plane
  b. If clipping is on for that plane and that direction (lower or upper), toggle that clipping plane off (uncheck clip box)

The anticipated benefit of these actions is to provide a single shortcut key that allows you to toggle clipping associated with the most recently active grid plane. It provides direct visual feedback between knowing exactly where the cut will occur in the given scene and addresses directionality of that cut.

Thank you for considering this feature request.

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
try windows smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

when our Linux cluster comes back up I'll push changes to central repo and post a linux and osx version

1. to turn on command line plane clipping press 'M' key
2. use 'W' key to toggle through clipping modes (none, clip blockages and data, clip blockages, clip data)
3. use x/y/z key to toggle lower clipping planes (turn on/off)
4. use X/Y/Z keys to toggle upper clipping planes
5. use cursor, page up/down keys to move lower clipping planes
6. use SHIFT cursor, page up/down keys to move upper clipping planes

this help info is displayed as a reminder when you press the M key to turn on command line clipping.  Not a lot of good choices with keyboard short cut letters so we'll have to live with W and M

**Comment by gforney** [comment]
Also, these keys are overloaded so while command line clipping is on, grid
display is off

**Comment by firemist** [comment]
I apologize as I'm on travel and it's difficult for me to test things right now. However, I did download the latest version and had some difficulties. Here's my description of what I observed, but I was not able to create a cohesive model, in my mind, of what was happening. So, please allow me to provide you with this feedback and then from there maybe you can see if there's an issue or I will have to perform more complete testing.

Firstly, I want to say that what did work looked great and that's what I was looking at doing.

Secondly, I was testing with a multi-mesh model (5 meshes) and I don't know with what you tested, but maybe that's some of the problem here as the clipping plane hit various mesh boundaries. This is not a big, monolithic rectilinear model broken up into sections for computing convenience. There are various meshes separating spaces with long almost tunnel-like connections between them, if that helps you visualize this domain.

Thirdly, here's my testing feedback:

1. I tried turning on the clipping planes and the lower planes seemed to work.
2. As I tried to implement upper planes, that's where there seemed to be trouble.
3. After asserting the lower clipping plane (miniscule axis letter) I then tried to move to establish an upper clipping plane, but that's where the problem seemed to be.
4. As I hit the majuscule axis letter it, a plane would appear to jump to the upper limit, but moving it down did not seem to work or the clipping plane did not seem to be asserted.
5. The z-plane actions seemed to also be making changes to the rotational setup
6. Part of this, I think, is not knowing exactly which plane has focus for movement, etc. I don't know if there's a way to highlight it, such as using a color, brightness, or thickening the line of the plane that has focus. In other words, if I'm going to press a movement key (left, right, rear, front, pg-up, pg-dn), which clipping plane will it affect.
7. Text from command window:

![image](https://user-images.githubusercontent.com/25644607/180052649-911d204a-ad2b-4af4-982b-24e5218feeca.png)

I will try to do some more testing or post if there's another version to test. I also realized when using this mode you really need to have the command window visible so that you can see what's switching on and off during processing.

Thanks very much for working on this. I think it will be very helpful as it gets resolved.

**Comment by gforney** [comment]
I will take a look at and test some more

**Comment by gforney** [comment]
try smokeview posted here. 
I fixed a bug in the PAGE UP key.  I also
changed the cursor, page up/down key behavior so that it will turn on plane clipping for the plane that is being moved.  ie 
moving left/right cursor turns on lower x plane clipping
moving SHIFT left/right cursor turns on upper x plane clipping
moving up/down cursor turns on lower y plane clipping
moving SHIFT up/down cursor turns on upper y plane clipping
moving page up/down key turns on lower z plane clipping
moving SHIFT page up/down key turns on upper z plane clipping
pressing 'M' key now sets clipping mode to blockages and data in addition to turning on command line clipping mode

I'm still working on it but it should behave better now 

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by gforney** [comment]
As before you can turn off clipping by pressing x,y,z for lower x,y,z
clipping planes oe X,Y,Z for upper x,y,z clipping planes

**Comment by gforney** [comment]
do my changes address your issue?

**Comment by gforney** [comment]
haven't heard anything.  I"m closing the issue.  you can reopen if there is still a problem

**Comment by firemist** [comment]
- I apologize as I had to go on the road to two weeks to sites and testing and could not get this downloaded.
- In any event, it works very well and is what I hoped it would be.
- Thanks very much for doing this -- it's a great help and I think will be very helpful to other users as well. The visual feedback makes it much easier to find and select the correct clipping plane location.
- I don't see any problems right now, but will let you know if I come across anything.
- Thanks again! (Again, I apologize for the delay in getting back to you.)

**Comment by gforney** [comment]
No problem. Thanks for reporting back.
