### ISSUE TITLE
ribbed_channel cases have bulk velocity off by > 1%

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#10804]
Related to what we have been seeing in firebot and PR#10799. Might want to revisit these. 
A bisect shows that first off Ub for ribbed_channel_20.fds is for commit 5d1e9f (March 3). Bulk velocity for the case was under 1% in May, but is at Ub=6.29 with latest source.

**Comment by rmcdermo** [comment]
Should be fixed with PR #10866
