### ISSUE TITLE
another weird behavior of fire propagation on vegetation with newer FDS version...

### ISSUE THREAD

**Issue by gmsafir** [firemodels/fds#10815]
Dear all, I am running the classic tree fire from Ruddy Mell in both versions 6.7.5 and 6.7.8. The 6.7.5 exhibits a classical behavior coherent with Ruddy's publication, while the 6.7.8 exhibits no fire propagation to the tree.

Any idea on the reason?
[0_Calcul.fds.txt](https://github.com/firemodels/fds/files/9187897/0_Calcul.fds.txt)

**Comment by ericvmueller** [comment]
Have you tried running the cases as they appear in the validation suite?
https://github.com/firemodels/fds/tree/master/Validation/NIST_Douglas_Firs/FDS_Input_Files

If you check the validation guide, these were successfully run with version 6.7.8

**Comment by gmsafir** [comment]
Thx Eric for this suggestion to start from some case that works, because by making difference  with my not working parameter file, step by step merging the 2 cases, I found the solution. The problem points (again - see previous issue) to the needs in 6.7.8 to add EMISSIVITY=1 in the burner definition!
Adding just this feature in my not working parameter file makes it work properly with 6.7.8!

**Comment by ericvmueller** [comment]
Glad to hear it, and thanks for reporting back with the result!
