### ISSUE TITLE
Modelled water mist behaviour does not match experimental data

### ISSUE THREAD

**Issue by Firekat4** [firemodels/fds#10816]
[Simple_cone_0_35_500k.fds.txt](https://github.com/firemodels/fds/files/9189752/Simple_cone_0_35_500k.fds.txt)

&SPEC ID='WATER VAPOR'/

&PART ID='Water mist constant',
      SPEC_ID='WATER VAPOR',
      DIAMETER=36.0,
      MONODISPERSE=.TRUE.,
      QUANTITIES='PARTICLE VELOCITY',
      AGE=60.0

&PROP ID='Generic Commercial Link_Simple cone',
      QUANTITY='SPRINKLER LINK TEMPERATURE',
      ACTIVATION_TEMPERATURE=68.33,
      PART_ID='Water mist constant',
      PARTICLES_PER_SECOND=500000,
      FLOW_RATE=3.99,
      PARTICLE_VELOCITY=85.0,
      SPRAY_ANGLE=0.1,35.0/

Hi,

I intended to model a water mist cone at 35 degrees spray angle, with a flow rate of 3.99l/min, initial droplet velocity of 85m/s and a droplet size of 36 microns. The experimental data shows a clear cone of 35 degrees. In FDS this is shown as a narrow jet directed straight down. 
I have also created a spray table with a multi orifice nozzle and this created the same issue.
I have tried varying spray angles with similar results.
The problem improves with droplet size and shows the correct cone by 500 microns, but then the offset increases dramatically, where the default of 0.05m is maintained. I can provide all of these FDS models if required.

Katharine Skinner

<img width="263" alt="image" src="https://user-images.githubusercontent.com/110036179/181007432-489b00d1-317e-4185-a468-69701d943475.png">

**Comment by drjfloyd** [comment]
You have a 10 cm grid and the default OFFSET is 10 cm.  All of your droplets are being injected into a handful of grid cells. A 36 micron droplet is going to very quickly transfer all of its momentum to the gas, probably within that first grid cell. A 500 micron droplet is going to taken an order of magnitude more time.  You probably need a much finer grid near the nozzle to resolve the spray pattern with such small droplets.  I suggest you create a simple test case where you just model a small region around the sprinkler and run it for finer and finer grid sizes.

**Comment by drjfloyd** [comment]
No further responses from OP. Closing.
