### ISSUE TITLE
mass integration of moving particles

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#10817]
In the attached example, a group of particles is transported up and out of the domain. Using a device to track the total mass within the domain works fine when there is one mesh, but if the particles transit a mesh boundary there seems to be a problem. You can see in the graph that the mass briefly drops to zero at the time the particles cross this boundary. The result is the same whether integrating `MPUV` or `SURFACE DENSITY`.

This can be problematic when tracking vegetation mass within a volume that crosses multiple meshes and allowing the vegetation to create firebrands.

![image](https://user-images.githubusercontent.com/13366803/181038879-6720bb33-79be-44f2-90bb-b0bf5d003521.png)

[flying_mass.fds.txt](https://github.com/firemodels/fds/files/9190848/flying_mass.fds.txt)

**Comment by mcgratta** [comment]
Nasty bug, as usual. I fixed it, but I have to run all the verification cases before pushing it up.

**Comment by ericvmueller** [comment]
Great - thanks!

**Comment by mcgratta** [comment]
Give it a try now. Note that you should not use `INIT_ID` on the DEVC lines in this case. `INIT_ID` should only refer to a `INIT` line with a single particle.

**Comment by ericvmueller** [comment]
Thanks! Will check it out when I’m back on Monday. And thanks for the heads-up, I wasn’t sure of the proper use of INIT_ID vs PART_ID in this context

**Comment by ericvmueller** [comment]
Thanks! Will check it out when I’m back on Monday. And thanks for the heads-up, I wasn’t sure of the proper use of INIT_ID vs PART_ID in this context

**Comment by mcgratta** [comment]
You'll now get an error statement of you  do.

**Comment by ericvmueller** [comment]
So the original example I posted now works ...but I think there is another issue. 
In this second example there are two particle classes, both of which turn into `EMBER` particles and fly upward. If there is no `ID` provided on the `INIT` lines, then it seems like the particle classes get confused as they pass into a different mesh (shown as the mass spikes in the plot below.) 

If an `ID` is provided on the `INIT` line then it appears to work fine ...so it is easy enough to work around, but a potential pitfall. For example, the current douglas fir inputs don't have `INIT` id's specified.

![image](https://user-images.githubusercontent.com/13366803/182219458-8ca9eb6f-a0d2-456f-8cc4-5832a2fe4a48.png)

[flying_mass_2.fds.txt](https://github.com/firemodels/fds/files/9236459/flying_mass_2.fds.txt)

**Comment by mcgratta** [comment]
You really want that Boris...

I'll fix.

**Comment by mcgratta** [comment]
Try it now.

**Comment by ericvmueller** [comment]
Yup, looks good. Thanks!
