### ISSUE TITLE
Fine mesh decreased the accuracy

### ISSUE THREAD

**Issue by RNstu08** [firemodels/fds#10823]
Hello All,

I have prepared two meshes (coarse and fine mesh). The only difference between these is the refinement of the meshes and the number of blocks.
In coarse mesh, a mesh of 9 cm was used uniformly across the room, and the domain was divided into 5 blocks.
Unlike fine mesh, the 4.5 cm mesh was used uniformly throughout the room, and the domain was divided into 9 blocks.
The results obtained from coarse mesh are higher. whereas the results from the fine mesh were found to be lower in values than those of the coarse mesh.
For reference, I have compared three different results. Heat release rates and temperatures at three different locations. As can be seen in the figures, it is clear that as I refined the mesh (i.e., fine mesh), the results tended to decrease from the coarse mesh results.
This seems to be going the reverse way. Normally, fine mesh resolution should produce better results, but in this case, the opposite is true.
I have also attached the fds files for both the meshes. Would you please explain the reasons or is there anything one should consider while refining the meshes?
Any help is much appreciated.
![HRR](https://user-images.githubusercontent.com/97069157/181201690-8a527bad-4a05-4c0e-9093-01aa24e58ef8.png)
![Plate thermometer](https://user-images.githubusercontent.com/97069157/181201693-e7b2dc2a-a052-4e8c-910c-1edb6e458957.png)
![Temperature](https://user-images.githubusercontent.com/97069157/181201694-62849977-4013-418f-b11a-6d88d042988b.png)
[FDS_files.zip](https://github.com/firemodels/fds/files/9196559/FDS_files.zip)

**Comment by Er9y714** [comment]
There is only two meshes to compare. They are called Coarse and Fine but actually, one is only coarser to the other one, one is finer to the other one. In fact, `fine `might be still to coarse for the calculation. Therefore I would suggest to run a finer version of the `fine ` and see if the results converge and the selected mesh can be deemed as _refined well enough_.

Radiation might be one of the reasons this is caused by. You might try increasing the number of rays. See `9.2 Radiation inside a Box (radiation_box)` in Verification Guide.

**Comment by RNstu08** [comment]
@Er9y714 Yes, that is right. The attached zip file has two fds files (Coarse and Fine.fds). As I mentioned earlier, the coarse.fds (238,650 cells) has 5 mesh blocks in the computational domain. Here, the mesh resolution is 9 cm, which is equal to the minimum dimension of the cribs used.
And fine.fds (1,155,510 cells) has 9 mesh blocks and the mesh resolution was kept at 4.5 cm throughout the room, which is half of the minimum dimension of the cribs used. It should be able to resolve the fire more accurately.

**Comment by drjfloyd** [comment]
A finer mesh doesn't automatically give you a higher heat release rate.  As noted by Er9y714, two resolutions do not make a grid study. There is nothing here to indicate a likely issue with FDS.

**Comment by RNstu08** [comment]
@drjfloyd I was advised by the @bwklein to send the files to the issue tracker, as improving the mesh resolution, in general, should yield better results. However, here it is not the case. It has also happened to me in another calculation as well. Since it is recurring I thought of asking for suggestions or inputs from the community here. I am not performing any grid study in this case.

**Comment by drjfloyd** [comment]
Neither the coarse mesh line nor the fine mesh lines in the plots are data from an experiment. So how do you know now which is "better"? All you have shown here is that a finer mesh has different results.

**Comment by RNstu08** [comment]
@drjfloyd I have now added the experimental data to it.
![Plate thermometer](https://user-images.githubusercontent.com/97069157/181271335-54fdda31-f486-42f1-86bd-77ce4abbbe6e.png)
![Temperature](https://user-images.githubusercontent.com/97069157/181271343-9af57804-27c6-4f26-a519-1f007066a6a6.png)

**Comment by drjfloyd** [comment]
What is the error in your material properties? Did you measure properties for the exact material burned in the test (i.e. using samples of the exact same material) or just pull properties from some other source?

What is the total expanded uncertainty in your experimental data?

You are trying to predict the burning rate. This is an area of active research. You need to do more than just plot the results of an FDS simulation against test data to establish there is an issue.

**Comment by RNstu08** [comment]
Material properties are taken from eh experimental paper. Constant values are used here.

What kind of uncertainties one should consider?

How can one approach these things?

**Comment by drjfloyd** [comment]
Every single value you have typed on the MATL line has an uncertainty associated with it. These should have been reported by the paper. The assumption of constant values also adds uncertainty. 

Have you verified that your MATL properties actually result in FDS being able to reasonably predict the result of a TGA and cone test for this specific material? 

Youe fine and coarse heat release rates differ by about 10 %. This is likely well within the uncertainty of your MATL properties.

**Comment by RNstu08** [comment]
Currently obtaining TGA / cone data in order to use them in the future. But, for the one I have already mentioned, it was not performed.

Even though the difference, is around 10-16%, the results look better with a coarser mesh configuration. That was my original question. In another example where we tried to predict burning rate, I carried out 5 different mesh comparisons, and the results were the same, coarser mesh yielded better results.

**Comment by drjfloyd** [comment]
Again you don't actually know that the results are better just that comparing curve in the absence of uncertainty makes it look better. The material properties you have put into your input file are with a near 100 % guarantee not the true properties of the material. You need to be in the frame of mind that every piece of data from the experiment has an uncertainty associated with it. For the purpose of comparing with FDS, the temperature data has the intrinsic uncertainty associated with the thermocouple plus the expanded uncertainty associated with how you have chosen your inputs for FDS.

**Comment by RNstu08** [comment]
I understand the point you are making.
But, how can we comprehend the results from these two meshes, where coarse mesh with a dimension equal to the minimum dimension of the crib used (i.e., 9 cm) bears better results than the fine mesh with a dimension of 4.5 cm.
The pyrolysis reaction is one of the reasons for these differences. There could be other reasons besides the ones already mentioned, such as uncertainties in the material data and constant material properties. What would be the other reasons?

**Comment by drjfloyd** [comment]
The material properties you have used are not the true properties. It might very well be that this particular set of properties in real life would result in a smaller fire. If that were the case, then the coarse result would actually be worse. You don't know what bias your assumed properties introduce, and as a result you really can't state on the basis of a single experiment that one grid resolution is better.

You probably have at least 10-15 % expanded uncertainties in the temperatures.  This would mean for the PY1 measurement of 1000 C that is really the range of 700/800 to 1200/1300 at 95 % confidence. This range would overlap both grid resolutions.

This is also a single test. How repeatable are these results? It could be that the fine grid result is a better representation of the mean over a large number of test.

**Comment by RNstu08** [comment]
The properties (rho, Cp, K, thermal inertia, moisture) used in the FDS files were measured in the experiments for the same material. Aren't these the true properties?

**Comment by drjfloyd** [comment]
Every measurement you make has an error associated with it.

Density is a weight measured by a scale divided by a volume measured either with using a tape measure/caliper or by volume displacement. Both of these have errors that propagate when you compute density.

Cp, k, and thermal inertia are not things that you can measure directly. For these you have some test apparatus where you apply a heat flux and measure a temperature and apply a model to derive the Cp and k. That input flux has an error, that temperature will have an error, and that model used to derive the values has an error.

**Comment by RNstu08** [comment]
Thank you for your valuable inuts.
