### ISSUE TITLE
Early activation of VENT

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10824]
The attached input text below has a VENT and an OBSTruction. Vent should activate at 5 seconds. Obstruction should **de**activate at 10 seconds. However Vent activates at T=0. If I remove the first two lines of the &RAMP, then it works fine. 

The input file is generated via Pyrosim. That is why the RAMP is created in this manner. 

Could you please have a look? 

Run files:
[test.zip](https://github.com/firemodels/fds/files/9196964/test.zip)

FDS v6.7.9

```
&HEAD CHID='test'/ 
&TIME T_END=100.0/ 
&DUMP DT_SLCF=0.1/ 
 
&MESH ID='Mesh01', IJK=5,5,5, XB=0.0,1.0,0.0,1.0,0.0,1.0/ 
  
&RAMP ID='Obst_Exhaust_RAMP', T=-0.25, F=-1.0/ 
&RAMP ID='Obst_Exhaust_RAMP', T=0.25, F=1.0/
&RAMP ID='Obst_Exhaust_RAMP', T=9.75, F=1.0/ 
&RAMP ID='Obst_Exhaust_RAMP', T=10.25, F=-1.0/ 

&CTRL ID='Obst_Exhaust', FUNCTION_TYPE='CUSTOM', RAMP_ID='Obst_Exhaust_RAMP', LATCH=.FALSE., INPUT_ID='TIME'/ 

&DEVC ID='Exhausttimer', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=5.0/ 

&DEVC ID='TIME', QUANTITY='TIME', XYZ=0.0,0.0,0.0/ 
 
 
 
&SURF ID='Exhaust',       RGB=206,0,37,       VOLUME_FLOW=5.0/ 
 
&OBST ID='OBST_Exhaust', XB=0.6,1.0,0.0,1.0,0.0,1.0  CTRL_ID='Obst_Exhaust'/ 
 
&VENT ID='Exhaust', SURF_ID='Exhaust', XB=0.6,0.6,0.1,0.7,0.0,0.8, DEVC_ID='Exhausttimer'/ 
 
&VENT ID='open', SURF_ID='OPEN', XB=0.0,0.0,0.0,1.0,0,1.0/ 
 
&DEVC ID='vel', QUANTITY='VELOCITY', XYZ=0.5,0.5,0.5/ 
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=0.5/ 
  
&TAIL / 
```

**Comment by drjfloyd** [comment]
When I run this and look at the slice file in smokeview I see that the OBST is off at t=0 which is correct as it isn't until the first timestep that the RAMP becomes positive. The VENT isn't shown in smokeview until 5 s. The OBST disappears at 10 s. This is echoed in the devc_ctrl_log file.   However, the flow for the VENT starts as soon as the OBST appears, but at 5 s the flow goes to zero and then ramps up again. This all suggests the control functions are behaving correctly in terms of the logical state they have. The issue appears to be how the wall cells for the OBST are initialized when it is created. It seems you have a work around in just having the OBST present from the start.

**Comment by drjfloyd** [comment]
The DEVC and CTRL on a VENT control the ramping for temperature, species, and velocity. Your SURF just has VOLUME_FLOW which means it is using the default 1 s TANH ramp. What is happening is the OBST is created at the start. The OBST then looks for any VENTs attached to it and finds the Exhaust. It then sets the normal velocity using the VOLUME_FLOW. The actual velocity used at ay time during the simulation is this value times the output of the ramp. This process of finding a VENT should also be picking up the fact that the VENT isn't on when the OBST is created. This would result in the TANH evaluating to 0 making the normal velocity 0. It doesn't seem to be doing that, which means flow is starting when the OBST is added. Later when the VENT is turned on, the TANH is reset to this new on time and the ramping up of the flow begins again. I think the PROCESS_VENT block in INIT_WALL_CELL needs a check on the control status of the vent before setting ONE_D%T_IGN. Something like:

   IF (VT%CTRL_INDEX > 0) THEN
      IF (.NOT. CONTROL(VT%CTRL_INDEX)%CURRENT_STATE) T_ACTIVATE=1E10_EB
   ENDIF
   IF (VT%DEVC_INDEX > 0) THEN
      IF (.NOT. DEVICE(VT%DEVC_INDEX)%CURRENT_STATE) T_ACTIVATE=1E10_EB
   ENDIF

This fixes this case and I have pushed it up.

**Comment by Er9y714** [comment]
Thank you very much. On my side, I do not have any other questions and I am closing the issue if it is okay.

**Comment by Jawquin** [comment]
I received the following error in PyroSim:

"This model is not connected to an ambient pressure boundary condition... simulations may fail due to numerical instability. Add OPEN vents or ambient HVAC nodes to resolve the issue."

Although I have defined open surfaces in the model, this error still appears. I also tested another model that includes open areas, but the same warning occurs when I try to run the simulation.

Could you please help me understand what might be causing this?

Best regards,

**Comment by drjfloyd** [comment]
For pyrosim issues contact Thunderhead Engeering
