### ISSUE TITLE
Mass loss in FDS vs. Cone Calorimeter

### ISSUE THREAD

**Issue by ChrisDagenais** [firemodels/fds#10833]
Here is the FDS file for your review (in txt format).
This issues is linked to the question I made on the forum (https://groups.google.com/g/fds-smv/c/mq1E96ebYSo).

Thanks,
Christian
[DF_50kWm2_50Kmin.txt](https://github.com/firemodels/fds/files/9214203/DF_50kWm2_50Kmin.txt)

**Comment by mcgratta** [comment]
```
      N_S=3.31,
      A=9.57E22,
      E=1.36E5/
```
How confident are you with these values? I substituted 
```
      REFERENCE_TEMPERATURE=100
```
and now I do not see the initial drop in surface density. My guess is that you are evaporating all the water in the first step. Look at your value of A. Does that look right to you?

**Comment by ChrisDagenais** [comment]
Thank you Kevin for the quick follow-up.
The kinetic values for the water evaporation are taken from a similar study (https://onlinelibrary.wiley.com/doi/full/10.1002/fam.2947).
When using these values and plug them in a TGA model in FDS, the first reaction between 20 and 100 C provides quite a good fit (see pic attached).
![TGA_FDS_vs_Test](https://user-images.githubusercontent.com/104454450/181645701-1abb407f-3f4b-47f4-8640-d6fc89c29986.png)

May I ask what you changed in the code lines (i.e., REFERENCE_TEMPERATURE=100)?
Where and what have you changed for this single line?
I will redo my models and see if this new change fits better vs. using the parameters from the study.

Thanks again.
Christian

**Comment by drjfloyd** [comment]
For the late time surface density vs. thickness question in the forum: You only have ALLOW_SHRINKING and ALLOW_SWELLING set for the pure wood.  One the wood fully converts to char in a wall node, those inputs no longer have an effect (see the end of 11.5.3 in the User's Guide). Your wood is 553 kg/m3 and 35 % goes to char which is 195 kg/m3.  Your char density is 96 kg/m3.  So as a node in the wall converts all its wood to char it will swell and then shrink again as the char reaction takes place.

**Comment by mcgratta** [comment]
Have you seen this in the latest FDS User's Guide? We changed the reaction expression to conform with other pyrolysis models.

![image](https://user-images.githubusercontent.com/11333911/181776099-cd1f636b-2819-4b0b-afae-b0638ee64351.png)

**Comment by ChrisDagenais** [comment]
Thanks you guys for your help. You provide an awesome support!
I modified the 1st reaction using simplier parameters (ref temp, heating rate and pyrolysis range). The TGA plots is a bit less accurate, but still reasonable. I also no longer get the drop after the 1st time step when doing the cone model.

**Comment by mcgratta** [comment]
I modified your specified value of A following the guidance above. The results are similar to what you showed me. I find that first-order reaction kinetics are fine for most materials, at least from a fire modeling point of view. Carefully tuned reaction parameters might work well for the material on which they are based, but do not necessarily provide better results for new materials. Simpler is (usually) better.
