### ISSUE TITLE
OBSTruction will not disappear in plot3d

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10835]
The script below involves an OBSTrcution and it deactivates at 3 seconds. It is disappearing when SLCF is loaded but not plot3D file. Is that on purpose or is there any way to enable obstructions to disappear according to their state in plot3D?

Thank you.

SMV 6.7.19

```

&HEAD CHID='1'/
&TIME T_END=10.0/
&DUMP  DT_PL3D=1.0, DT_SLCF=1.0, NFRAMES=10, WRITE_XYZ=.TRUE./

&MESH ID='Mesh01', IJK=5,5,5, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&DEVC ID='TIMER->OUT', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=3.0, INITIAL_STATE=.TRUE./


&OBST ID='Obstruction', XB=0.6,0.8,0.4,0.6,0.0,1.0, DEVC_ID='TIMER->OUT'/ 

&VENT ID='Vent', SURF_ID='OPEN', XB=0,0,0,1.0,0,1/ 

&SLCF QUANTITY='TEMPERATURE', PBX=0.486261/


&TAIL /

```

**Comment by mcgratta** [comment]
I've never noticed this before. The .smv has the time that the OBST is removed. Glenn will take a look at it.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
try smokeview posted here.  note, blockages disappear at about 3.5 s not 3 probably first time step after 3 s. so the first plot3d file with hidden blockages is at 4.11 s .  let me know if you still see tthe problem.  thanks for the catch.  I'll push my changes up to the central repo after they pass smokebot

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharinghttps://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by Er9y714** [comment]
Perfect. It works! Thank you Glenn.
