### ISSUE TITLE
Extreme runtime with use of screens

### ISSUE THREAD

**Issue by lars1488** [firemodels/fds#10856]
Hello all,

I'm trying to run two different simulations where I want to use a screen as 1: a porous ceiling (I know the screen is not actually meant for this), and 2: a screen façade. 
When running the simulations without the screens, they run fine (I've disabled the particle cloud and left everything else the same). But when I enable the particle cloud, the runtime explodes and the simulation practically doesn't run anymore. It doesn't crash, but the expected runtime goes up to multiple decades.

I've created a very small test model and it does exactly the same. I've attached this file. 
Hopfully someone can help me on this issue. 

Thanks in advance.
[Test_ screen_T9_0,05.docx](https://github.com/firemodels/fds/files/9269361/Test_.screen_T9_0.05.docx)

**Comment by mcgratta** [comment]
When you invoke `DRAG_LAW='SCREEN'`, FDS limits the time step to avoid numerical instabilities. You can relax this constraint by setting `PARTICLE_CFL_MAX` to a value greater than 1 on the `MISC` line. If you raise this value too high, you will see numerical instability near the screen.

**Comment by mcgratta** [comment]
Your `ORIENTATION` is not correct. It should be 1,0,0. I changed this and I set `PARTICLE_CFL_MAX=5`. Try this and experiment with the value.

**Comment by lars1488** [comment]
Hi Kevin, 
Thanks for your reply. 

Unfortunately this doesn't seem to help. 
I've set the PARTICLE_CFL_MAX to 5 and 10, but it has now ran 13 of 30 seconds in over 1,5 hours (The simulation without the particle cloud ran 30 seconds in about 3 minutes). I've now set the PARTICLE_CFL_MAX to 50 (I don't think this is a reasonable value) and although it does look like it runs a little bit faster, it still doesn't really seem to work (now 0.86 seconds in over 6 minutes).

Hopefully you can help me further on this.
Thanks

[Test_ screen_T10_0,05.docx](https://github.com/firemodels/fds/files/9284435/Test_.screen_T10_0.05.docx)

**Comment by drjfloyd** [comment]
The screen drag formula is for window screens. It computes that drag force through the thickness of the screen and then adjusts it for the grid size. A typical window screen is something like 20 squares per inch. With 40 % porosity that makes the wire diameter ~0.2 mm.  You have set the size of your screen to 1 cm. So your inputs have a factor of 50 difference in the adjustment. This is probably what is causing the issue. You are probably winding up with an unrealistic pressure drop.

**Comment by drjfloyd** [comment]
If I go and set your THICKNESS to 0.0005 mm (a fairly large wire for a window screen) and run on windows with four cores it is running at about one second of simulation time per minute of real time.

**Comment by lars1488** [comment]
This seems to work. Even with the PARTICLE_CFL_MAX back to default. 
The wire diameter was supposed to be 1 mm instead of 1 cm.

Thanks!

**Comment by drjfloyd** [comment]
Thanks for letting us know. I am going to close the issue.
