### ISSUE TITLE
ZONE problem with a small hole between MESHes

### ISSUE THREAD

**Issue by mst-lyubimov** [firemodels/fds#10874]
Consider two MESH with different cell sizes. There is a wall where the grids meet.
An error occurs when there is a hole in the wall between two meshes with a size smaller than the smaller cell size.
ERROR: ZONE 2 meets ZONE 1 at the boundary of MESH 2 and MESH 1
The error occurs in FDS 6.7.7 – 6.7.9
Probably, the reason is: Bypassing cells with automatic numbering of zones, the "worm" cannot crawl from a grid with a larger cell size into a grid with a smaller one. Further, starting the calculation of the model, the cells are bypassed according to a different rule and the “worm” crawls from a small cell into a large one and detects a conflict.

A simplest example that generates the error:

&HEAD CHID='test' TITLE='Example' /
&TIME T_END=30/
&MESH IJK=20,20,8 XB=2,5,2,5,0,2 /
&MESH IJK=10,10,4 XB=2,5,2,5,2,4 /
&OBST XB = 2,5,2,2.75,1.75,2/
&OBST XB = 2,5,3,5,1.75,2/
&OBST XB = 2,2.75,2.75,3,1.75,2/
&OBST XB = 3,5,2.75,3,1.75,2/
&TAIL /

In the first picture below, we are looking from a grid with a large cell and Smokeview does not show the hole. In the bottom picture, we are looking from a grid with a small cell and the hole is visible. Perhaps this illustration is somehow similar to the problem under discussion.
![image](https://user-images.githubusercontent.com/84854006/183675340-838de3a3-4eca-4b0d-9dbb-d1b7a9c88175.png)
![image](https://user-images.githubusercontent.com/84854006/183675376-c3f7a7cd-f887-4897-bdce-a8793c740602.png)

**Comment by mcgratta** [comment]
The problem appears to be that the hole is not resolved on the upper coarse mesh. Thus mesh 2 closes the hole whereas mesh 1 leaves it open. I don't see this as a problem. FDS is telling you that the hole is not well designed for the two abutting meshes.

**Comment by mst-lyubimov** [comment]
We agree with your answer, but there are doubts that FDS responds to this problem in the best way.
Automatic zone marking, which appeared since version 6.7.7, in our opinion, creates difficulties with the interpretation of errors associated with zones. The locations and numbers of zones remain a mystery if the calculation fails at the very beginning. That is, it is very difficult to understand what exactly is wrong.
Most often, FDS user does not mark and number zones manually, and the zone collision message looks discouraging. In particular, it is very difficult to guess that the cause of the error is some hole, which turned out to be between the zones. Especially if we are dealing with a large project.
It seems that in this case the error message should contain more information about where the zones touched. Another option is to ignore this error as minor if possible.
We spent a lot of time to find and understand the cause of the error in our large project, despite the fact that we have a lot of experience with zones. The simplest project above is just an artificial example. We can assume that, based on the current error message, most users would simply never realize what was going on. There is no obvious error in the project geometry. Just a wall and a window. We did not mark any zones manually. FDS itself marked some zones and itself gave an error that it marked them incorrectly. This looks very strange!
It seems that FDS can solve this contradiction within itself and mark the zones in such a way as to satisfy its own requirements.

**Comment by mcgratta** [comment]
In this case, two different processes on potentially two different computers are parsing the input file. These two processes do not know what the other is doing unless the information is explicitly communicated via MPI. Each process reads the obstruction information and snaps the boundaries to the grid. There is no "smart" logic to detect this kind of problem. That kind of logic is typically built into a graphical user interface like PyroSim or Blender. There are only 3 of us here at NIST who maintain the FDS source code and 1 for Smokeview, with a very small number of others who help from time to time. We have made the decision to focus on the core solver and leave the "front end" graphical user interface to other organizations. 

If you have a suggestion as to how to easily detect these issues, we'd be happy to listen. You have outlined the problem well, but the solution is more difficult. The solution is going to potentially require much more code to "check" the appropriateness of the multi-mesh, multi-grid geometry. Such a check should be done before FDS ever reads the input file. FDS can only do so much to catch these issues when the job has been farmed out to multiple, semi-autonomous processes.

**Comment by bwklein** [comment]
PyroSim detects Holes too close to MESH boundaries and asks the user if they want to extend the hole through the adjacent mesh boundaries.

**Comment by mcgratta** [comment]
Thanks, Bryan. We had several issues related to the interface between coarse and fine meshes. The problem is that when obstructions snap to the respective grids, it is possible that one mesh has an opening to the other, but not vice versa. Usually these glitches are detected when the pressure zones are automatically determined, but the error statement often shrouds the real problem.
