### ISSUE TITLE
MPI timeout error message

### ISSUE THREAD

**Issue by kyj1120** [firemodels/fds#10872]
Good afternoon,

I am receiving this error message.

The case was running on a single workstation with windows 10, FDS version 6.7.7.

![timeout cmd](https://user-images.githubusercontent.com/110900207/183623064-7d60a269-b34a-4942-af3a-3b5c3ac42589.PNG)

can anyone suggest a fix for this?

**Comment by mcgratta** [comment]
This error statement indicates that something went wrong with an exchange of data from one process to another. Some things to try:

1. If you are running the case with multiple processes sharing the same core, try running with one process per core. 
2. Run the case again and see if it fails at the same place. If so, is there something special happening then, like sprinkler activation, door opening/closing?
3. Post the input file and I can try it with the latest version of FDS. We routinely fix bugs that might cause this. You can try the new version too.
