### ISSUE TITLE
FUEL Species in data.f90

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#10886]
I was looking through data.f90 to help us identify which built in species in FDS where known fuels.
I see that for some species there is a `FUEL = .TRUE.` in the CASE block.

I was going down the list and noticed that `ETHANOL` ( https://github.com/firemodels/fds/blob/master/Source/data.f90#L2362 ) does not have FUEL set to TRUE and that got me wondering if it should be or if there is more to the FUEL parameter than I was assuming it to be.

Some of the others that made me wonder are species like:   

- Hydrogen
- Hydrogen Atom
- N-PENTANE

Should they also have `FUEL = .TRUE.`?

**Comment by mcgratta** [comment]
It appears that FUEL is not used for the gases, only for the liquids. There is some special provision for getting radiation properties for liquid fuel droplets. I'll see if I can clean some of this up.

**Comment by mcgratta** [comment]
This all has something to do with radiative properties of liquid droplets. FUEL may not be the best name for this variable.

**Comment by mcgratta** [comment]
Jason -- why is `ETHANOL` not listed as a fuel, but `METHANOL` is?

**Comment by drjfloyd** [comment]
Just an oversight at the time.

**Comment by drjfloyd** [comment]
I suggest we hold a bit on doing any variable name changes here.  

We have fuel in the calls for both liquid and gas props, since this is just being used for liquids we don't need it in gas. There are also some other bits that need adjusting in these routines in support of current work on multiple simple reactions.

I have fixed the missing FUEL entries as part of getting the multiple simple working.

**Comment by drjfloyd** [comment]
I think this can be closed.  I am moving the liquid properties to be with the gas properties in prop.f90. While doing so I looked to make sure FUEL was set for organic liquid fuels.  I think FUEL is an OK name for this as it is indicating that the liquid should use the fuel and not water properties when doing the MIE calculation in radi.90.
