### ISSUE TITLE
Does FDS support OpenBlAS

### ISSUE THREAD

**Issue by liu-shaobo** [firemodels/fds#10881]
Hi, I use AMD ZEN2, MKL is not friendly to AMD support.

**Comment by mcgratta** [comment]
Given that I do not know what OpenBIAS is, probably not. However, FDS is written in standard Fortran 2018. It uses standard MPI and OpenMP libraries. You should be able to compile it with any Fortran compiler that is up to date (Intel, Gnu, PG). We do know that the latest Apple chips do not run our compiled executables, but that is because we use Intel Fortran and libs. You should be able to compile it with an alternative.

**Comment by marcosvanella** [comment]
@liu-shaobo It does not. Note Intel OneAPI libraries are now distributed for free (intelmpi, compilers, MKL, etc), and the intel builds will run in AMD machines as well.  As far as I know, performance issues of intel compilers in AMD machines from the past have been addressed.
Also, MKL is currently only used in some alternative Poisson solvers. You should be able to compile and run FDS with default pressure solver without any problems without having MKL installed.

**Comment by liu-shaobo** [comment]
> Given that I do not know what OpenBIAS is, probably not. However, FDS is written in standard Fortran 2018. It uses standard MPI and OpenMP libraries. You should be able to compile it with any Fortran compiler that is up to date (Intel, Gnu, PG). We do know that the latest Apple chips do not run our compiled executables, but that is because we use Intel Fortran and libs. You should be able to compile it with an alternative.

Both OpenBLAS and MKL are open source implementations of BLAS and LAPACK.

**Comment by liu-shaobo** [comment]
> @liu-shaobo It does not. Note Intel OneAPI libraries are now distributed for free (intelmpi, compilers, MKL, etc), and the intel builds will run in AMD machines as well. As far as I know, performance issues of intel compilers in AMD machines from the past have been addressed. Also, MKL is currently only used in some alternative Poisson solvers. You should be able to compile and run FDS with default pressure solver without any problems without having MKL installed.

thinks, may I ask what version of mkl is used in FDS6.7.9_SMV6.7.21_rls_lnx.sh?
Poisson solvers？calculation uses a Poisson solver based on Fast Fourier Transforms in the y and z directions？

**Comment by mcgratta** [comment]
By default, FDS does not use MKL. It is an optional solver for very specific applications.  Version 2022.0 is used in the latest FDS build.

**Comment by liu-shaobo** [comment]
good，thanks.
