### ISSUE TITLE
Fan curve with disappearing OBSTruction

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10884]
I was working on the fan curve to obtain a certain curve, which I have not achieved yet. Meanwhile I observed a behaviour I could not understand. Could you please have a look?

There are two runs below. The difference is the second file has an obstruction that appears and disappears again. The resulting flow rate is quite different. In the second run with obstruction, the fan flow rate grows much slower. 

As a secondary question:
the fan curve I want to obtain; 
Extract fan, ramping up in 1 seconds, say 3 m3/s flow rate between 0 and -200 Pa. 0 m3/s for pressure difference larger than -200 Pa. 

Thank you.

Run 1

```

&HEAD CHID='1'/
&TIME T_END=260.0/
&DUMP DT_DEVC=0.01, DT_SLCF=0.1, NFRAMES=520/

&MESH ID='Mesh01', IJK=4,10,10, XB=0.6,1.0,0.0,1.0,0.0,1.0/

 

 
&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.725,0.675,0.485302/

&DEVC ID='FLOW', QUANTITY='U-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=0.8,0.8,0.0,1.0,0.0,1.0/ 


 

&VENT ID='fan', SURF_ID='HVAC', XB=0.6,0.6,0.0,1.0,0,1.0/ 
&VENT ID='open', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 

&HVAC ID='inlet', TYPE_ID='NODE', DUCT_ID='duct', AMBIENT=.TRUE., XYZ=0.6,0.0,0.0/
&HVAC ID='duct', TYPE_ID='DUCT', AREA=1.0, PERIMETER=4.0, FAN_ID='Fan01', LOSS=1.0E-4,1.0E-4, NODE_ID='outlet','inlet', REVERSE=.TRUE., ROUGHNESS=0.0, LENGTH=0.707107/

&HVAC ID='outlet', TYPE_ID='NODE', DUCT_ID='duct', VENT_ID='fan'/
&HVAC ID='Fan01', TYPE_ID='FAN', TAU_FAN=1.0E-4, RAMP_ID='Fan01_RAMP_ID'/

&RAMP ID='Fan01_RAMP_ID', T=-10.0, F=0.0/
&RAMP ID='Fan01_RAMP_ID', T=-9.9, F=-15.0/
&RAMP ID='Fan01_RAMP_ID', T=0.0, F=-16.0/

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=0.495512/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBY=0.5/


&TAIL /

```

File 2:

```

&HEAD CHID='2'/
&TIME T_END=260.0/
&DUMP DT_DEVC=0.01, DT_SLCF=0.1, NFRAMES=520/

&MESH ID='Mesh01', IJK=4,10,10, XB=0.6,1.0,0.0,1.0,0.0,1.0/

&RAMP ID='Control01_RAMP', T=49.75, F=-1.0/
&RAMP ID='Control01_RAMP', T=50.25, F=1.0/
&RAMP ID='Control01_RAMP', T=59.75, F=1.0/
&RAMP ID='Control01_RAMP', T=60.25, F=-1.0/

&CTRL ID='Control01', FUNCTION_TYPE='CUSTOM', RAMP_ID='Control01_RAMP', LATCH=.FALSE., INPUT_ID='TIME'/
&DEVC ID='TIME', QUANTITY='TIME', XYZ=0.6,0.0,0.0/
&OBST ID='Obstruction', XB=0.8,1.0,0,1.0,0.0,1.0, CTRL_ID='Control01'/ 


&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.725,0.675,0.485302/
&DEVC ID='FLOW', QUANTITY='U-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=0.8,0.8,0.0,1.0,0.0,1.0/


&VENT ID='fan', SURF_ID='HVAC', XB=0.6,0.6,0.0,1.0,0,1.0/ 
&VENT ID='open', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 

&HVAC ID='inlet', TYPE_ID='NODE', DUCT_ID='duct', AMBIENT=.TRUE., XYZ=0.6,0.0,0.0/
&HVAC ID='duct', TYPE_ID='DUCT', AREA=1.0, PERIMETER=4.0, FAN_ID='Fan01', LOSS=1.0E-4,1.0E-4, NODE_ID='outlet','inlet', REVERSE=.TRUE., ROUGHNESS=0.0, LENGTH=0.707107/

&HVAC ID='outlet', TYPE_ID='NODE', DUCT_ID='duct', VENT_ID='fan'/
&HVAC ID='Fan01', TYPE_ID='FAN', TAU_FAN=1.0E-4, RAMP_ID='Fan01_RAMP_ID'/

&RAMP ID='Fan01_RAMP_ID', T=-10.0, F=0.0/
&RAMP ID='Fan01_RAMP_ID', T=-9.9, F=-15.0/
&RAMP ID='Fan01_RAMP_ID', T=0.0, F=-16.0/

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=0.495512/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBY=0.5/


&TAIL /

```

![image](https://user-images.githubusercontent.com/26166281/185099667-8e0a992d-d1f6-4a3e-8ab7-ba8eaef1c41f.png)

**Comment by Er9y714** [comment]
I just have noticed it was run in v6.7.8. 

I will run in 6.7.9 and report it.

**Comment by Er9y714** [comment]
I have run in 6.7.9 and results did not change. 

![image](https://user-images.githubusercontent.com/26166281/185101814-baeb27bc-4a2d-4083-9d70-dae08ca768bc.png)

**Comment by mcgratta** [comment]
I do not understand what you are trying to do here:
```
&HVAC ID='outlet', TYPE_ID='NODE', DUCT_ID='duct', VENT_ID='fan'/
&HVAC ID='Fan01', TYPE_ID='FAN', TAU_FAN=1.0E-4, RAMP_ID='Fan01_RAMP_ID'/

&RAMP ID='Fan01_RAMP_ID', T=-10.0, F=0.0/
&RAMP ID='Fan01_RAMP_ID', T=-9.9, F=-15.0/
&RAMP ID='Fan01_RAMP_ID', T=0.0, F=-16.0/
```
If I am interpreting this correctly, you are saying that the flan flow rate should be -9.9 m³/s at -15 Pa, and 0 m³/s at -16 Pa. This doesn't seem like a good idea to make the velocity change this much based on only a 1 Pa pressure difference.

**Comment by Er9y714** [comment]
I understand. I also realized what I aim to model is not possible to do with only a fan curve. Let's ignore the fan curve and leave it out of the discussion/issue, if possible.

**Comment by Er9y714** [comment]
And, if the fan curve is the source of the issue, I understand. I would take it as a user input error and close the issue.

**Comment by mcgratta** [comment]
I do not understand what the issue is yet. I am still just trying to figure out what you are doing. Post a new input file, only one, that does not work properly.

**Comment by Er9y714** [comment]
Okay, let me try if I can reproduce a simpler input. Thank you

**Comment by Er9y714** [comment]
I tried to simplify the fan curve. First of all, is this curve a sensible one? 

&RAMP ID='Fan01_RAMP_ID', T=-10.0, F=0.0/
&RAMP ID='Fan01_RAMP_ID', T=-9.9, F=-50.0/

**Comment by Er9y714** [comment]
I have replaced the curve with the example in the FDS User guide(12.2.4 HVAC Fan Parameters). 

My question is why the fan flow rate ramps up quickly in the first calculation and takes time in the second calculation. Note that obstruction appears at 50 s and disappear at 60 s. 
 
![image](https://user-images.githubusercontent.com/26166281/185182532-691fcca7-e56d-4eca-83f6-44fcedfb7d4f.png)


No obstruction:
```

&HEAD CHID='1'/
&TIME T_END=260.0/
&DUMP DT_DEVC=0.01, DT_SLCF=0.1, NFRAMES=520/
&MESH ID='Mesh01', IJK=4,10,10, XB=0.6,1.0,0.0,1.0,0.0,1.0/
 
&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.725,0.675,0.485302/
&DEVC ID='FLOW', QUANTITY='U-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=0.8,0.8,0.0,1.0,0.0,1.0/ 

&VENT ID='fan', SURF_ID='HVAC', XB=0.6,0.6,0.0,1.0,0,1.0/ 
&VENT ID='open', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 

&HVAC ID='inlet', TYPE_ID='NODE', DUCT_ID='duct', AMBIENT=.TRUE., XYZ=0.6,0.0,0.0/
&HVAC ID='duct', TYPE_ID='DUCT', AREA=1.0, PERIMETER=4.0, FAN_ID='Fan01', LOSS=1.0E-4,1.0E-4, NODE_ID='outlet','inlet', REVERSE=.TRUE., ROUGHNESS=0.0, LENGTH=0.707107/

&HVAC ID='outlet', TYPE_ID='NODE', DUCT_ID='duct', VENT_ID='fan'/
&HVAC ID='Fan01', TYPE_ID='FAN',  RAMP_ID='fan curve'/

&RAMP ID='fan curve',T=-10.00,F= 1000/
&RAMP ID='fan curve',T= -7.75,F= 800/
&RAMP ID='fan curve',T= -4.47,F= 600/
&RAMP ID='fan curve',T= 4.47,F= 400/
&RAMP ID='fan curve',T= 7.75,F= 200/
&RAMP ID='fan curve',T= 10.00,F= 0/
&RAMP ID='fan curve',T= 11.83,F= -200/
&RAMP ID='fan curve',T= 13.42,F= -400/
&RAMP ID='fan curve',T= 14.83,F= -600/
&RAMP ID='fan curve',T= 16.12,F= -800/
&RAMP ID='fan curve',T= 17.32,F=-1000/

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=0.495512/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBY=0.5/

&TAIL /

```

Obstruction is added:

```
&HEAD CHID='2'/
&TIME T_END=260.0/
&DUMP DT_DEVC=0.01, DT_SLCF=0.1, NFRAMES=520/

&MESH ID='Mesh01', IJK=4,10,10, XB=0.6,1.0,0.0,1.0,0.0,1.0/

&RAMP ID='Control01_RAMP', T=49.75, F=-1.0/
&RAMP ID='Control01_RAMP', T=50.25, F=1.0/
&RAMP ID='Control01_RAMP', T=59.75, F=1.0/
&RAMP ID='Control01_RAMP', T=60.25, F=-1.0/

&CTRL ID='Control01', FUNCTION_TYPE='CUSTOM', RAMP_ID='Control01_RAMP', LATCH=.FALSE., INPUT_ID='TIME'/
&DEVC ID='pressure', QUANTITY='PRESSURE', XYZ=0.725,0.675,0.485302/
&DEVC ID='FLOW', QUANTITY='U-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=0.8,0.8,0.0,1.0,0.0,1.0/
&DEVC ID='TIME', QUANTITY='TIME', XYZ=0.6,0.0,0.0/

&OBST ID='Obstruction', XB=0.8,1.0,0,1.0,0.0,1.0, CTRL_ID='Control01'/ 

&VENT ID='fan', SURF_ID='HVAC', XB=0.6,0.6,0.0,1.0,0,1.0/ 
&VENT ID='open', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 

&HVAC ID='inlet', TYPE_ID='NODE', DUCT_ID='duct', AMBIENT=.TRUE., XYZ=0.6,0.0,0.0/
&HVAC ID='duct', TYPE_ID='DUCT', AREA=1.0, PERIMETER=4.0, FAN_ID='Fan01', LOSS=1.0E-4,1.0E-4, NODE_ID='outlet','inlet', REVERSE=.TRUE., ROUGHNESS=0.0, LENGTH=0.707107/

&HVAC ID='outlet', TYPE_ID='NODE', DUCT_ID='duct', VENT_ID='fan'/
&HVAC ID='Fan01', TYPE_ID='FAN',   RAMP_ID='fan curve'/
 
&RAMP ID='fan curve',T=-10.00,F= 1000/
&RAMP ID='fan curve',T= -7.75,F= 800/
&RAMP ID='fan curve',T= -4.47,F= 600/
&RAMP ID='fan curve',T= 4.47,F= 400/
&RAMP ID='fan curve',T= 7.75,F= 200/
&RAMP ID='fan curve',T= 10.00,F= 0/
&RAMP ID='fan curve',T= 11.83,F= -200/
&RAMP ID='fan curve',T= 13.42,F= -400/
&RAMP ID='fan curve',T= 14.83,F= -600/
&RAMP ID='fan curve',T= 16.12,F= -800/
&RAMP ID='fan curve',T= 17.32,F=-1000/

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=0.495512/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBY=0.5/

&TAIL /
```

**Comment by mcgratta** [comment]
I think what is happening is that each time the obstruction disappears, a pressure zone is opened. This includes time t=0 because the obstruction actually disappears at time t=0. When a zone opens, the air flow in and out of the zone is limited to reduce the sudden change in pressure that occurs when a solid object simply disappears in a single time step. I'll ask Jason to chime in if this is not the case.

**Comment by drjfloyd** [comment]
I added DEVC_ID to the &HVAC line with the fan to turn the fan on at 10 s. This removes the t=0 OBST difference. There is still a difference in the fan flow with the fan delayed. It may be there is a bug in the HVAC solver noticing the zone change for the vent resulting in an error in the extrapolated pressure calculation.  I can look in more detail when I am back from vacation.

**Comment by Er9y714** [comment]
Thank you for your time. Since you mentioned vacation, I have to say this is not an urgent need for me. It is a type of issue that a work-around can be used.

**Comment by drjfloyd** [comment]
The logic for checking which zone a duct node is in wasn't correct. It was not properly using the CONNECTED_ZONES array. This bug has been since we first added HVAC to FDS. Good find!  Adding to the 2022 Boris Stock Award nominee list. 

Should be fixed in https://github.com/firemodels/fds/commit/7f2c7ecdac853e7f1a0975d6f27b607c65662523

**Comment by Er9y714** [comment]
Amazing! Thank you for solving the issue and and for the nomination.
