### ISSUE TITLE
Missing case of not allowed MESH alignment for FDS UG (currently §6.3.4)

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#10890]
IMHO, the `Figure 6.2: Rules governing the alignment of meshes` of the UG is missing the (not allowed) case where the coarse cell is completely covered by finer cells, but these fine cells are from two different meshes.
See the 4th case of the attached example.
![3dview-sidebar-mesh-alignment](https://user-images.githubusercontent.com/11455203/186133333-9fd06694-927a-43e2-afce-0f3a01c60c11.png)

And the "This is not allowed because each large cell must be completely covered by small ones." label should be replaced by:
"This is not allowed because each large cell must be completely covered by small ones **of the same mesh**".

I can prepare a pull request if you agree with this.

**Comment by emanuelegissi** [comment]
@rmcdermo sorry for coming back to that ;-)
I should add that if the constraints shown in 3rd and 4th postion were to be relaxed, aligning `MESH`es in complex cases would be *much* easier.

**Comment by rmcdermo** [comment]
Hi Ema,
Yes, I remember the discussion :).  But consider the other new Issue that just got posted ( #10889 ).  It is already painful to make these coarse-fine mesh interfaces work robustly for all possible scenarios.  As I've mentioned, for load balancing, using MULT is usually a much better solution than the Tetris approach.

I will add your suggested case to the UG.  Thanks

**Comment by mcgratta** [comment]
Yes, certainly add the fourth case and the word change. However, the second and third cases would be very difficult to make work. The main reason is the alignment of continuity of the pressure fields.

**Comment by emanuelegissi** [comment]
1) Yes, I understand, I asked just in case you had a silver bullet I did not know about, before improving again the BlenderFDS alignment algorithm.

2) I am preparing a pull request.

**Comment by rmcdermo** [comment]
OK, thanks.  I was in the middle of trying to figure out how to make the graph :)  If you have it done, that would be helpful.

**Comment by emanuelegissi** [comment]
Would these pictures and labels be ok with you?

[Test_MESH_align_00.pdf](https://github.com/firemodels/fds/files/9416537/Test_MESH_align_00.pdf)

**Comment by emanuelegissi** [comment]
(It is on the second page of the pdf.)
I had to change the line thickness to better show two different meshes.

**Comment by rmcdermo** [comment]
It looks good to me.  Thanks!

**Comment by emanuelegissi** [comment]
I sent a pull request #10895

**Comment by rmcdermo** [comment]
Got it.  Thanks!
