### ISSUE TITLE
Multiple RESTART file

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#10906]
Hi there, this is not really an issue but more a possible request of development. FDS allows to just save "one" restart file which represents the latest time step reached using DT_RESTART.

Other CFD software save multiple RESTART files and they use a "PURGE" option to allow the user to decide how many of these should be left on the storage.

For example:

DT_RESTART=250 , PURGE_RESTART=2
this creates a restart file every 250 seconds and leaves the latest two restart files on the storage (deleting the older ones)

DT_RESTART=250, PURGE_RESTART=0
this creates a restart file every 250 seconds and leaves all restart files on the storage

This, I think, is a relatively small modification but it can be quite helpful if someone wants to restart the CFD analysis from a step before the last one.

**Comment by mcgratta** [comment]
This sort of thing has thing has been suggested several times. The RESTART feature is fragile, as you would expect when you think about dumping 10s of gigabytes of huge arrays into multiple files and then reading them back in. It's a real headache. The biggest issue is the control features. Getting everything back to the exact same "state" as it was before stopping the job always causes bugs. I really don't want to add even more complexity. If someone is really keen on restarting from multiple past times, I suggest that they write a script that moves restart files to individual directories after they are written.

**Comment by rupole1185** [comment]
Allright. Thanks for the explanation!
