### ISSUE TITLE
Mass conservation fail

### ISSUE THREAD

**Issue by RNstu08** [firemodels/fds#10917]
Hello all,

I have some problems associated with mass conservation while modelling in FDS using both prescribed HRRPUA (M1) on the surface and using Arrhenius constants (M2).

I have performed multiple examples; it is always either less than the mass used in the simulation or more than the one used. It is never the same or in the close proximity of the mass used, even though all the objects were burnt fully.

As advised by Kevin to submit an issue tracker, I have performed three examples. Of which one was the example from the FDS database (Examples/Fires/burnaway). For reference, I named this folder Foam, while the folder names of the other two examples are Crib and Crib_Large. (All the files are attached, which include the FDS file and the output data). I have also calculated the original mass used and obtained mass from the FDS using excel (example_error_calculation.xlsx).

For the foam case, M2 was used. The total mass used was 2.56 kg, but the obtained mass of methane was 1636.85 kg. For the crib case, both M1 and M2 were used. The total mass used was 19.84 kg but the obtained MLR was 52.46 kg (M1) and 60.96 kg (M2). For the crib_large case, M2 was used. The total mass used was 198.48 kg, but the obtained MLR was 4.08 kg.

Should they all obtain the same MLR from the FDS as mentioned on the obstruction line?

[Files.zip](https://github.com/firemodels/fds/files/9469192/Files.zip)

**Comment by drjfloyd** [comment]
The value in the mass.csv file is not kg/s it is kg.  Summing the column is not the mass that is produced. The mass that is produced is the last row in the mass.csv.  In your Foam_error_calculation.xlsx the value in the last row is 2.56 which is the expected value.

**Comment by RNstu08** [comment]
What does the MLR indicate?
Isn't it the mass loss rate at every time step?
If it is the mass loss rate at every time step then summing it should give the total mass loss throughout the simulation time. Am I right?

**Comment by drjfloyd** [comment]
The spreadsheet titled Foam_error_calculation.xlsx in the folder Foam contains data from the mass.csv file in columns A-C not the hrr.csv file. In the mass.csv file the numbers are the total mass present in the domain at that time.

In the hrr.csv, the MLR does mean mass loss rate; however, summing the column is only correct if the timesteps between points is 1 s otherwise you need to pick your favorite numerical integration scheme and use the timestep size.

**Comment by RNstu08** [comment]
I have not set MASS_FILE=T for the other two examples. However, the timestep is 1 sec between the points, which means the summing of the MLR from the hrr.csv should be able to give the total mass loss. But it seems to be showing varying results. It would be helpful if you could please look into any single case of the error. I have added the burner surface as an addition to the remaining cases.

**Comment by drjfloyd** [comment]
What is the problem with M1?

You only have one fuel species. That species is coming out of the burner and from the wood crib. The burner is 0.6 x 0.6 x 2104.6 = 758 kW. The heat of combustion of your fuel is 17500 kJ/kg which means the burner is injecting 0.043 kg/s. Over 1000 s that is 43 kg. The mass of the wood crib is 23 kg. The sum of the MLR column is 52 kg.  52 < 43 + 23.
