### ISSUE TITLE
Problems with fds5 co

### ISSUE THREAD

**Issue by xun21** [firemodels/fds#10915]
Hello everbody I'm using FDS5 for a fire simulation, using n-heptane as the fuel, and specifying a yield of 0.006 for co and 0.015 for smoke, when I run, I get errors 1 and 2, for 2 errors, I also Changed the case, sorry, but also wrong! I hope you can tell me, what should I do to not make mistakes? In addition, I can run these statements normally in fds6 and get the corresponding values.
When I deleted the statement of 1, the error 2 appeared again:
1、&DEVC ID='Mass', QUANTITY='MASS FRACTION', SPEC_ID='CARBON MONOXIDE', XYZ=40.0,6.1,10.0/
2、&DEVC ID='wet co01', QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON MONOXIDE', XYZ=39.0,5.05,10.0/
2、&DEVC ID='dry co02', QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON MONOXIDE', XYZ=39.5,5.05,10.0,DRY=.TRUE./
Problems that arise:
1、ERROR: Output QUANTITY MASS FRACTION requires a SPEC_ID
2、ERROR: Output QUANTITY VOLUME FRACTION requires a SPEC_ID

**Comment by mcgratta** [comment]
Use the latest version of FDS and then we can provide support. FDS 5 is over 10 years old.
