### ISSUE TITLE
another weird behavior of fire propagation on vegetation ...

### ISSUE THREAD

**Issue by gmsafir** [firemodels/fds#10926]
hi,

a lot of problems was solved after correction by @ericvmueller from constant Cdrag=0.375 to Reynolds-dependent Cdrag in the closed issue https://github.com/firemodels/fds/issues/10750
However, we got recently another problem raised in a simple case of a fire in an excelsior bed forced by a constant wind.
Unrealistically, the fire at the edges of the bed (in contact with the metal table) are progressing more rapidly than the fire in the center of the bed.
This is less the case when reintroducing a constant Cdrag=2.8.
We thought that a possible explanation is in the wind that is very strong at the edges, while the wind in the fuel bed is very very low. We thought to employ a BURN_AWAY, for the wind to penetrate the burnt zone in the fuelbed, but this option does not apply to particles.

Any idea about the way to solve this problem?

[excelsior_bed_wind_drag_Re.fds.txt](https://github.com/firemodels/fds/files/9528030/excelsior_bed_wind_drag_Re.fds.txt)
[excelsior_bed_wind_drag2_8.fds.txt](https://github.com/firemodels/fds/files/9528031/excelsior_bed_wind_drag2_8.fds.txt)

**Comment by rmcdermo** [comment]
Eric, please have a look to see if there is an issue.

However... @gmsafir I suspect that you are just in the weeds of vegetation modeling research.  I do not want to use an Issue for this.  This question would be better suited for the discussion forum if there is not a bug.

**Comment by gmsafir** [comment]
Sorry, you can close the issue, I repost it in the FDS Google Group

**Comment by ericvmueller** [comment]
I can take a look and post any suggestions if you post in the discussion forum ...but at first glance yes this is related to the various complexities with modeling the scenario and not a specific bug.
