### ISSUE TITLE
Numerical instability using F.D.S 6.7.9

### ISSUE THREAD

**Issue by SamuelColtGroup** [firemodels/fds#10931]
I'm currently working on the smoke control system for a building.

I have noticed when upgrading from FDS 6.7.5 to FDS 6.7.9 some projects that worked in the past now no longer work.

The current project that I'm working crashes a couple of seconds after the extract surface begins to operate.

I have attached the FDS and output file of the 6.7.5 model (revision 02) and my latest 6.7.9 model (revision 07a). images also included within the zip file.

I did notice when running a test 10,000 cell model it was crashing due to an open vent being 1 cell in size. Increasing the vent or decreasing the cell fixed the issue but on this larger project those solutions aren't helping.

Kind regards,
Samuel

[SamuelColt Numerical Instability FDS 6.7.9.zip](https://github.com/firemodels/fds/files/9557693/SamuelColt.Numerical.Instability.FDS.6.7.9.zip)

**Comment by rmcdermo** [comment]
Thanks, we'll take a look.

**Comment by mcgratta** [comment]
I am running the case now.

**Comment by mcgratta** [comment]
The case has run to about 70 s and is now running slowly with a very small time step. In the .out file, I see this
```
       Mesh    9
       Max CFL number:  0.91E+00 at (1,7,1)
       Max divergence:  0.17E+00 at (1,7,1)
       Min divergence: -0.66E-02 at (1,13,2)
       Max VN number:   0.16E+00 at (3,7,1)
```
This means that the highest CFL number occurs in cell 1,7,1 of mesh 9, which is right where you have this little OPEN vent on the floor. This means that you have a very fast flow coming through this little hole, and this has reduced to the time step to a point where the calculation is crawling. It might fail, or might not, but in any case, you should not add these little holes. I would use either local or compartment leakage throughout the structure.

**Comment by SamuelColtGroup** [comment]
Thank you, simulation is now working as expected.
