### ISSUE TITLE
Models completing on FDS Version 6.7.6, but not on Version 6.7.8

### ISSUE THREAD

**Issue by jameschampion20** [firemodels/fds#10930]
Hi All,

When trying to run the two attached models on FDS Version 6.7.8, I got numerical instability errors and the models didn't complete. The pressures and velocities just before the simulation stopped were very high (see also attached screenshots). When reverting back to FDS Version 6.7.6, both models completed fine with no issues. Do you know why this is? Do you think running the two models on FDS Version 6.7.9 would help the situation? 

Many thanks for your help,

James

![RS-F1-R4_0173_Velocity](https://user-images.githubusercontent.com/68464009/189851842-4782ea7b-7a2e-4807-a6aa-00794a7ed61c.jpeg)
![RS-F1-R4_0173_Pressure](https://user-images.githubusercontent.com/68464009/189851850-9b6800b9-0674-49f1-8ad5-5f77c4383b07.jpeg)
[RS-F1-R4.txt](https://github.com/firemodels/fds/files/9555027/RS-F1-R4.txt)
[RS-F3-R4.txt](https://github.com/firemodels/fds/files/9555029/RS-F3-R4.txt)

**Comment by mcgratta** [comment]
Do both cases fail at about the same time?

**Comment by jameschampion20** [comment]
Hi Kevin,

Thank you for your response. F1 failed at 173s; F3 failed at 243s. Please see the two .OUT files attached. 
[RS-F1-R4-OUT.txt](https://github.com/firemodels/fds/files/9557607/RS-F1-R4-OUT.txt)

[RS-F3-R4-OUT.txt](https://github.com/firemodels/fds/files/9557568/RS-F3-R4-OUT.txt)

**Comment by mcgratta** [comment]
I'm running F1.

**Comment by mcgratta** [comment]
I get the same instability as you with the latest code. It is related to the sprinkler activation, but I have not pinned it down yet.

**Comment by mcgratta** [comment]
I believe the problem is that you are specifying ADIABATIC walls. This is not a good idea physically or numerically. What is the reasoning behind it? In this case, the water droplets hit this wall and FDS cannot maintain a perfectly zero-flux boundary condition. Always give your wall a non-zero thermal conductivity.

**Comment by drjfloyd** [comment]
I'll fix this in part.  If the wall is adiabatic we shouldn't be using the drop solution with wall heat transfer.

**Comment by drjfloyd** [comment]
Actually there is a potential problem I think anytime there is a specified heat flux and droplets given the way we have constructed the METHOD_OF_HEAT_TRANSFER block in CALCULATE_TEMP_F. We may want to issue a warning message if an input file has specified heat fluxes and droplets (no issue if drops can't reach the surface). In part the only safe thing may be to not allow droplet heat transfer if there is a net flux surface.

**Comment by mcgratta** [comment]
Yes, ADIABATIC is just NET_HEAT_FLUX=0. Before making this an ERROR, we should check existing verification cases.

**Comment by drjfloyd** [comment]
I don't think it should be an error, just a warning. I could see someone trying to model something like a LIFT test with water spray where no spray is pointed at the radiant panel. In this case it would be fine to have both.

**Comment by jameschampion20** [comment]
Hi Kevin and Jason,

Many thanks for your responses. 

I will remove ADIABATIC walls from my future models, especially when sprinklers are included in the models. 

James
