### ISSUE TITLE
Gaseous fuel products from pyrolysis spread and exit from the computational domain?

### ISSUE THREAD

**Issue by AlbertoPrevedello** [firemodels/fds#10934]
Hi everyone,

I am running an FDS file with a fire of several pallets, a great storage of paper. The total RHR available is more than 2000MW. The total surface of the aforementioned storage is more than 500m2 (total number of Grid Cells 1080000, physical dimensions 24x36x10m).

In the FDS file I used a "Simple Pyrolysis Model" (11.4 FDS User's Guide) with a specific HHRPUA [kW/m2], one for surface ("&SURF") named Burner and one for surface ("&SURF") named Paper.

Also, in the FDS file I used a "Single-Step, Mixing-Controlled Combustion", with reaction characteristics as follow:

&REAC ID='Carta',
             FORMULA='C6H10O5',
             CO_YIELD=0.004,
             SOOT_YIELD=0.015,
            RADIATIVE_FRACTION=0.35, /

and "Mass Fraction Transformation Matrix to Convert Species Mixtures (Columns) to Primitive Species (Rows)" extract from "CHID.out" as follow:

                                                       AIR                  Carta        PRODUCTS
   Carta                                   0.000000            1.000000           0.000000
   NITROGEN                          0.760861            0.000000           0.632995
   OXYGEN                              0.230510            0.000000           0.000000
   CARBON DIOXIDE               0.000590            0.000000          0.263970
   CARBON MONOXIDE          0.000000            0.000000           0.000672
   WATER VAPOR                    0.008039             0.000000          0.099841
   SOOT                                  0.000000              0.000000          0.002521
   HYDROGEN                        0.000000              0.000000          0.000000

The ventilation consists to window and doors, the former broke up at 300°C before the 10th minute, and the latter open by fire figther at 20th minute.

The model suffers a low availability of Oxigen within the storage area. I suppose that the total of paper material gets to autoignition Temperature, and than all the paper material produce gaseous fuel due to pyrolisys which doesn’t burn due to the absence of Oxigen.

**The gaseous fuel products from pyrolysis spread and exit from the internal area (paper storage) and from the computational domain. Is that plausible?**

This idea comes from the following considerations:
- the MLR_FUEL from CHID.hrr.csv, multiplied for the Heat of Combustion value (16090kJ/kg) is vastly major then HRR of computational domain;
- the inlet of oxigen, measured whit a proper device ("QUANTITY='MASS FLOW',   SPEC_ID='OXYGEN'"), multiplied for the Heat of Combustion value for oxygen (13600kJ/kgO2) is vastly minor of the RHR value of the computational domain;
- the RHR value measured within the internal area (paper storage) is equal to the value of the  previous point and is vastly minor of the RHR value of the computational domain.

Thanks

Alberto

**Comment by rmcdermo** [comment]
Alberto,
Please submit your question to the [discussion forum](https://groups.google.com/g/fds-smv).  The Issues site is for reporting bugs.  Thanks
