### ISSUE TITLE
Problem with particle ENTHALPY from PDPA

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10949]
For the `particle_heating_convection.fds` verification case, I am not getting the same enthalpy change if I use INIT (which seems to be correct) and the PDPA (as is done with droplets).

[particle_heating_convection.fds.txt](https://github.com/firemodels/fds/files/9606164/particle_heating_convection.fds.txt)

<img width="1021" alt="Screen Shot 2022-09-20 at 5 29 47 AM" src="https://user-images.githubusercontent.com/4418497/191222301-6b747a1d-85fa-46ec-bde8-bf9034d62221.png">

**Comment by drjfloyd** [comment]
If I remove RELATIVE=T, the DEVC with INIT gives the correct value. PDA is less by exactly a factor of 8.  There is an 2^3 factor being applied somewhere in PDPA.

**Comment by rmcdermo** [comment]
OK, INIT seems to work with RELATIVE=T, as well.  Either way, yes, the factor of 8 is right there:
```
IF (PY%PDPA_NORMALIZE) THEN
  DV%PDPA_DENUM = DV%PDPA_DENUM + FOTHPI*(2._EB*PY%PDPA_RADIUS)**3
ELSE
  DV%PDPA_DENUM = 8._EB
ENDIF
```
In the user guide, it says that setting `PDPA_NORMALIZE=F` is equivalent to setting V=1 in f2(phi).  I don't see where there is a 2^3 in the numerator that needs canceling out for ENTHALPY.

**Comment by rmcdermo** [comment]
This seems to be working now PR #10954
