### ISSUE TITLE
INIT high TEMPERATURE with ADIABATIC walls not maintaining energy

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#10945]
Try this simple case with and without RADIATION.  With RADIATION=T the temperature drops to 1000 C in the first couple times steps.

```
&HEAD CHID='test'/
&MESH IJK=10,10,10, XB=0.0,0.1,0.0,0.1,0.0,0.1/
&TIME T_END=120./
&MISC STRATIFICATION=F, NOISE=F /
&CLIP MINIMUM_DENSITY=0.01 /
&RADI RADIATION=F/
&INIT XB=0.0,0.1,0.0,0.1,0.0,0.1, TEMPERATURE=2000./
&SURF ID='adiabatic wall', ADIABATIC=T, DEFAULT=T, COLOR='GRAY'/
&SLCF QUANTITY='TEMPERATURE',PBY=0.05,CELL_CENTERED=T/
&TAIL/
```

**Comment by drjfloyd** [comment]
Try increasing INITIAL_RADIATION_ITERATIONS. The t=0 iterations start with the walls at TMPA and the default value of 3 may not be enough. In the first iteration the walls see a radiative flux that is going to be much closer to the flux for 20 than the flux for 2000 since the box is fairly transparent to radiation.

For example if I increase to 10 the solution winds up at 1200 C. If I keep the iterations at 3 but add 1 % soot to make the box much more opaque I get 1550 C.

**Comment by rmcdermo** [comment]
Jason figured out that 2000 initial radiation iterations will work.  For this case, that is doable---startup time is not too bad.

It seems like we should be able to set TMP_FRONT as an initial guess to reduce the number of iterations needed for to achieve the correct equilibrium.  I have not figured out why that does not work yet.

**Comment by drjfloyd** [comment]
The culprit appears to be that UII is initialized to TMPA and the case is using INIT to set a high temperature. So in radi.f90 the expression for IL is starting off with a UII that is way too low and apparently it takes a lot of iterations to get UII to build up to where it needs to be.

**Comment by rmcdermo** [comment]
Yep.  If I set TMPA=2000, then no need for a high number of initial radiation iterations.

**Comment by rmcdermo** [comment]
Despite initializing UII in PR #10947 , maintaining an adiabatic boundary condition with both convection and radiation at play has proven difficult.  I want to leave this issue open until and see if we can tighten this up.  It makes development of verification cases very hard if we cannot rely on this boundary condition to be robust.  I suspect that some level of iteration of the radiation field with inclusion of WALL_BC (as is done at initialization) will be required.

**Comment by mcgratta** [comment]
I added `TMP_FRONT_INITIAL` for this case which sets the initial wall temperature to 2000. Also, the radiation solver is called before the wall BCs in the initialization phase.
```
&HEAD CHID='test'/
&MESH IJK=10,10,10, XB=0.0,0.1,0.0,0.1,0.0,0.1/
&TIME T_END=0.1/
&MISC STRATIFICATION=F, NOISE=F /
&CLIP MINIMUM_DENSITY=0.01 /
&RADI RADIATION=T/
&INIT XB=0.0,0.1,0.0,0.1,0.0,0.1, TEMPERATURE=2000./
&SURF ID='adiabatic wall', ADIABATIC=T, DEFAULT=T, COLOR='GRAY',TMP_FRONT_INITIAL=2000/
&SLCF QUANTITY='TEMPERATURE',PBY=0.05,CELL_CENTERED=T/
&SLCF QUANTITY='INTEGRATED INTENSITY',PBY=0.05,CELL_CENTERED=T/
&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=T/
&BNDF QUANTITY='INCIDENT HEAT FLUX', CELL_CENTERED=T/
&BNDF QUANTITY='TOTAL HEAT FLUX', CELL_CENTERED=T/
&TAIL/
```

**Comment by rmcdermo** [comment]
Looks good, thanks.  Test case works well now.
