### ISSUE TITLE
The window pops up and disappears

### ISSUE THREAD

**Issue by Robinsonsfi** [firemodels/fds#10961]
Hello,
I have a problem with FDS 6.7.9, SMV 6.7.21. After installation when i use CMDfds and open some fds file. Computer ask to chose aplication to open, when i chose fds (C:\Program Files\firemodels\fds.exe - the next window pops for 1 second and disappear and it does nothing. 

It is also with firewall off and on.

**Comment by gforney** [comment]
You also need to type the input file you are running. Take a look at the
fds users guide

**Comment by Robinsonsfi** [comment]
I did that. When I type the input file in CMDfds (from Examples) then Computer ask to chose aplication to open it, and I chose fds (C:\Program Files\firemodels\fds.exe - the next window pops for 1 second and disappear and it does nothing.

**Comment by gforney** [comment]
Souns like you only typed
casename.fds
Type
fds casename.fds
or
fds_local casename.fds

Also make sure you rebooted after installation

**Comment by Robinsonsfi** [comment]
Thank you very much, It was late and I jumbled with guide.
