### ISSUE TITLE
KILL function not writing restart

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#10973]
Reported in the forum: https://groups.google.com/g/fds-smv/c/Bl4bZAKLr3M

[test.txt](https://github.com/firemodels/fds/files/9698464/test.txt)

**Comment by drjfloyd** [comment]
Should be fixed now.

**Comment by drjfloyd** [comment]
never mind this wasn't a bug will undo and explain in the forum and tweak text in the guide.

**Comment by rmcdermo** [comment]
Jason,
Please double check that your suggested fix works.  I tried that and it seemed it did not produce a .restart file for me.  Thanks

**Comment by drjfloyd** [comment]
The issue was the manual needed updating to reflect changes we made to the KILL and RESTART at some point in the past.

**Comment by rmcdermo** [comment]
Yes, but your suggestion to the user does not work.  Try this.  It does not produce a restart file.
```
&HEAD CHID='test' TITLE='Test project' FYI='Generated with Fenix+ 3 Ultimate 3.1.2 https://mst.software'/
&TIME T_END=30/

&MESH IJK=24,24,12 XB=-3,3,-2,4,0,3 /
&VENT XB=-3,-3,-2,4,0,3 SURF_ID='OPEN'/
&VENT XB=3,3,-2,4,0,3 SURF_ID='OPEN'/
&VENT XB=-3,3,-2,-2,0,3 SURF_ID='OPEN'/
&VENT XB=-3,3,4,4,0,3 SURF_ID='OPEN'/

&REAC FUEL = 'METHANE' /

&OBST XB=-1,0.0,1,2,0,0.5 RGB=255,235,205/

&SURF ID='1' HRRPUA=1000 COLOR='RED'/
&VENT XB=-1,0,1,2,0.5,0.5 SURF_ID='1' /

&DEVC ID='temp', QUANTITY='TEMPERATURE', SETPOINT=200., XYZ=0,2,2.5 /
&CTRL ID='restart', FUNCTION_TYPE='RESTART', INPUT_ID='temp' /
&CTRL ID='kill', FUNCTION_TYPE='KILL', INPUT_ID='temp' /

&TAIL /
```

**Comment by drjfloyd** [comment]
I guess I must have failed to delete the restart file before testing after reverting the fix.
