### ISSUE TITLE
FDS mesh sizing help

### ISSUE THREAD

**Issue by NTamoafo** [firemodels/fds#10980]
Hello, 

I am simulating an object that has its thickness larger than that of a unit cell mesh. I am not able to make my mesh smaller due to the computational time. Is there a way to allow FDS to predict the mesh size needed for a simulation to be effective? This is a solid phase. Will FDS still simulate it accurately if the mesh is thicker than the object thickness?

**Comment by drjfloyd** [comment]
This is a question best posed in the discussion forum: https://groups.google.com/g/fds-smv
