### ISSUE TITLE
Bug: Thin obstacles with 'void' and 'insulated' surfaces remove heat from ambient domain

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#10982]
The following test case was run in FDS 6.7.9:

![Test_Case_HeatTransfer_2](https://user-images.githubusercontent.com/114649229/194322501-896125bf-e943-4884-92ab-af4deda48a81.png)

(FDS input file: [Test_Case_HeatTransfer.txt](https://github.com/firemodels/fds/files/9725652/Test_Case_HeatTransfer.txt))

- There are four individual cases in the domain, each case separated from the other by a center wall with an inert surface:   
Case 1: Obstacle with a thickness of 1 block.
Case 2 to 4: Thin obstacle (i.e. zero block thickness).
- All four cases use the exact same material, with the only difference being the "BACKING" properties.
Case 1 & 2: ```BACKING='INSULATED'```.
Case 3: ```BACKING='VOID'```.
Case 4: ```BACKING='EXPOSED'```.
- Each case is equipped with the following temperature devices:
1: 0.1 m below Z_min of the obstacle.
2: 0.05 m above Z_max of the obstacle.
3: 0.35 m above Z_max of the obstacle.
- All fires are of equal dimension (1m²) and use the exact same HRRPUA (300 kW/m²).
- Except for the bottom of the domain, there are open vents in all planes.

Running the FDS case yields the following results:

![Test_Case_Layer_1](https://user-images.githubusercontent.com/114649229/194338812-94030c9b-3376-4115-8256-497327d6b7aa.png)

![Test_Case_Layer_2](https://user-images.githubusercontent.com/114649229/194338885-f76d7986-4486-4e37-a9ae-99d3b006ca00.png)

![Test_Case_Layer_3](https://user-images.githubusercontent.com/114649229/194338983-b7300583-e268-4285-80fe-faf07504f11a.png)

- Case 1 exhibits zero temperature increase above Z_max, as expected from ```'INSULATED'```.
- Case 2 and 3 exhibit significant temperature drops above Z_Max, which is entirely unexpected for both ```'INSULATED'``` and ```'VOID'```.
- Case 4 exhibits a temperature increase above Z_max, as expected from ```'EXPOSED'```.

&nbsp;

The results of cases 2 and 3 are completely implausible, because:
- Case 1 and 2 should produce the same results. To the heat transportation solver, both should represent an obstacle with a material thickness of 6 mm insulated against any heat loss. Yet, in case 2, heat is actively removed from the domain around the obstacle despite there being no sensible reason for this (e.g. a huge temperature gradient in the surface).
- Case 3 should not develop any temperature gradient either as, per the FDS 6.7.9 user guide, section 11.3.3, ```BACKING='VOID'``` means that the surface simply backs up against ambient.
- Case 4 demonstrates that zero thickness obstacles are not necessarily the source of the issue, as the heat transfer through the obstacle works.

For these reasons, I'm filing this as a bug.

Another contributing factor is that the behavior in case 2 is a cause for density-related simulation instability and crashes when insulated, thin walled obstacles enclose a pressure zone.

&nbsp;

Running the case with ```HT3D=T``` and ```&MISC CHECK_HT=T /``` produces plausible results, but increases the required computation time by several magnitudes, which is unfeasible when computing resources and time is very limited (i.e. always).

One may as well not measure temperatures in the same cell as a thin obstacle, but this just isn't feasible in a lot of cases and the effect is experienced in the neighboring cell as well. Making the cell size smaller is also not an option for the increase in computation time.

Instead, wouldn't it make sense to simply prevent the temperature around thin, insulated and void-backed obstacles to ever decrease below T_amb (or a user-defined minimum value) to avoid these kind of issues?

**Comment by drjfloyd** [comment]
A fire impinging directly on a thin obstruction is going to be challenging for the default pressure solver to enforce the no-flux condition with the default tolerance settings. Suggest you try running with tighter tolerances

&PRES VELOCITY_TOLERANCE=0.001,MAX_PRESSURE_ITERATIONS=50/

or try running with the ULMAT solver.  

"Instead, wouldn't it make sense to simply prevent the temperature around thin, insulated and void-backed obstacles to ever decrease below T_amb (or a user-defined minimum value) to avoid these kind of issues?"

Clipping is generally not a good approach. Done routinely, it can lead to many other issues with conserving mass and energy.

**Comment by FireResearch-BK** [comment]
> A fire impinging directly on a thin obstruction is going to be challenging for the default pressure solver to enforce the no-flux condition with the default tolerance settings. Suggest you try running with tighter tolerances
> 
> &PRES VELOCITY_TOLERANCE=0.001,MAX_PRESSURE_ITERATIONS=50/

Yes, that worked with reasonable accuracy.

&nbsp;

> or try running with the ULMAT solver.

That's even better in terms of accuracy, but a test-run of a vastly more complex case with ULMAT in relation to #10968 increased computation time by as factor of greater than 10, which makes it not much of an option.

&nbsp;

> Clipping is generally not a good approach. Done routinely, it can lead to many other issues with conserving mass and energy.

What would be an alternative approach to solve the issue?
Native implementation of tighter pressure velocity tolerances for the solver?

And it might be good to have a warning regarding this behavior with ```'INSULATED'``` and ```'VOID'```, as well as a suggestion to use tighter velocity tolerances and a different pressure solvers, in the User Guide (section 11.3.3).

**Comment by marcosvanella** [comment]
"_That's even better in terms of accuracy, but a test-run of a vastly more complex case with ULMAT in relation to #10968  increased computation time by as factor of greater than 10, which is, frankly, unreasonable._"

What size (number of cells) are the meshes in this more complex case?

**Comment by drjfloyd** [comment]
I think in this case the INSULATED and VOID are a red herring.  They aren't the cause of the issue. The issue is the need for better pressure tolerance in your particular case. There is undoubtedly flow error for the thin EXPOSED surface; however, you are also conducting heat which means you don't readily see any temperature anomaly due the flow error.

Setting default convergence parameters is a tricky balance. Too tight and there will be complaints from user's about how long their runs are suddenly taking. Too loose and there will be complaints about strange behavior or instabilities. I'm not sure we are at a point where the balance is in favor of tightening the default behavior. Looking at the guide I think we could use some more discussion in the 10.2.2 Thin Obstructions that points people to the pressure solver error discussion. Also, we may want to change the section heading for 9.1 Accuracy of the Pressure Solver on Multiple Meshes to just Accuracy of the Pressure Solver since the discussion is related to both mesh boundaries and solid boundaries.

**Comment by FireResearch-BK** [comment]
> What size (number of cells) are the meshes in this more complex case?

411000, split into two meshes, so nothing particularly fancy.

&nbsp;

@drjfloyd 

Thanks for the documentation update.

I'd still like to know if something can be done on a solver-level by default. Something like querying surface backing types and the associated obstacle dimensions upon FDS input file parsing and then automatically applying tighter default velocity tolerances (and displaying an associated warning in the console or output file) to increase simulation stability.
Because as it is now, I don't think that many people will ever stumble upon the new paragraph in the User Guide, yet still work on cases in which the pressure solver behavior for INSULATED and VOID causes stability issues.

**Comment by marcosvanella** [comment]
"411000, split into two meshes, so nothing particularly fancy."

ULMAT uses the Intel MKL pardiso solver to do an exact LL^T factorization of the Poisson discretization matrix per mesh. This L matrix does contain substantially more non-zeros than the original Poisson matrix (the percenteage of non-zeros increasing with the matrix size), and the solution involves a forward-backward substitution on it. The cost of this solve at the core of the solver has poor scaling with the number of unknowns on the mesh, compared with the fast trigonometric mesh solver in the default pressure solver.
If possible, I suggest to split the meshes such that you have about 40^3 cells per mesh, set solver to ULMAT and do not set a VELOCITY_TOLERANCE on the &PRES line. Velocity errors will only be present in interpolated boundaries between meshes, fine obstructions will have a zero velocity error.
________________________________

**Comment by FireResearch-BK** [comment]
> If possible, I suggest to split the meshes such that you have about 40^3 cells per mesh, set solver to ULMAT and do not set a VELOCITY_TOLERANCE on the &PRES line. Velocity errors will only be present in interpolated boundaries between meshes, fine obstructions will have a zero velocity error.

For my problematic case, 64000 cells per mesh means ~7 FDS processes in total instead of 2. This poses a bit of a problem regarding availability of CPUs (physical or virtual).

I changed the surfaces of complex, problematic case to ```BACKING=EXPOSED``` (from ```INSULATED```) and had it run over the weekend in two varieties. Variety one is still running, but variety two already crashed. The only difference between these two is ambient temperature. _Sigh._

**Comment by mcgratta** [comment]
You can run 7 meshes on 2 MPI processes. Use `MPI_PROCESS` on the `MESH` line.

**Comment by FireResearch-BK** [comment]
Wouldn't 2 MPI processes for 7 meshes be just as slow than 7 MPI processes running on 2 cores (by manipulation of process core assignment)?

&nbsp;

After coarsening the mesh by a factor of 1.5 in every dimension, the problem case completed, but the accuracy of the results suffered a lot more compared to the original mesh than expected.

&nbsp;

Back to topic:

Does the FDS input file parser detect zero thickness obstacles?

If yes, it may help printing a warning message notifying about the risk of instability during the parsing process if the following conditions are fulfilled:
- a zero thickness obstacle was detected in the input file
- said obstacle has a surface using ```VOID``` or ```INSULATED``` as backing
- said obstacle does not have ``` THICKEN=T``` set
- ```&PRES VELOCITY_TOLERANCE``` and ```&PRES MAX_PRESSURE_ITERATIONS``` or ```&MISC THICKEN_OBSTRUCTIONS=T``` are not defined in the input file

Something like:
> WARNING: Zero thickness obstacle using void or insulated backing detected. Tighten pressure velocity tolerance and increase the maximum pressure solver iterations or force thicken obstacles to avoid premature pressure solver instability.

Until there is a pressure-solver level solution to the backing issue, such a warning may just encourage users to rework their input files again before wasting time by having the simulation crash hours, days or weeks later.

**Comment by marcosvanella** [comment]
_Wouldn't 2 MPI processes for 7 meshes be just as slow than 7 MPI processes running on 2 cores (by manipulation of process core assignment)?_

It would depend on how much the potential gains in the single mesh pressure solution offsets the overhead of having more meshes (extra calculations and comm in mesh boundaries, pressure iterations, etc.). It's a good question, let us know if you try it.

**Comment by drjfloyd** [comment]
7 copies of FDS running on 2 cores means every time you change mesh, you have to first unload the current copy of FDS from the CPU cache and then load the copy of FDS running the new mesh. You will also have all the communication required to pass data back and forth between the different processes.

With 7 meshes on 2 core you would have some meshes on one core and the rest on the other core. Here you would not have to swap out copies of FDS and you only need to pass data where a mesh on one core neighbors a mesh on the other core. For mesh boundaries being run on the same core there is no communication needed since the meshes are part of the same process and the memory they use can be directly accessed.  

Which is faster would probably come down to how well balanced the 7 on 2 is. If the 7 meshes can be divided into two groups of roughly similar total cell count, I would expect the 7 on 2 to be noticeably faster.  

As I stated earlier, I don't think that the VOID or INSULATION is the root cause of the problem. The root cause is leakage through the thin surface. The VOID or INSULATION in this case is probably happenstance, i.e., that in your particular geometry those surfaces get you to an instability but it is likely there are cases where this also happens for a heat conducting surface.

**Comment by mcgratta** [comment]
I made a slight change to the way thin obstructions are treated. You can try you case again with these [builds](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC).

**Comment by FireResearch-BK** [comment]
I finally got around retesting the case with 6.7.9-933 and the changes and things look much better now. 
The slight drop in temperature at 5 cm above the obstacle is probably due to pressure solver tax at close proximity to obstacles.

(Apologies for the differences in coloring.)

![grafik](https://user-images.githubusercontent.com/114649229/204842829-a8fbe6dc-2aee-4ef6-b262-d3267734d3a6.png)

![grafik](https://user-images.githubusercontent.com/114649229/204842890-caf0fb0d-6065-4737-bd8f-2fcdf55e9860.png)

![grafik](https://user-images.githubusercontent.com/114649229/204842972-095d3624-513c-459b-9e0e-9a8316d20b43.png)

**Comment by mcgratta** [comment]
Great, thanks for checking it out.
