### ISSUE TITLE
VENT not attaching on zero thickness

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#10991]
Hi, 

There are two run files below. Both have a zero thickness OBSTruction. In the first one a VENT is applied via the SURF_ID. The second run file however has a separate VENT object that is applied to the same location. 

FDS runs the first file but not the second file. In the second (with VENT) I get an error saying " VENT 1 must be attached to a solid obstruction". 

I see an inconsistency and I am curious if all is working properly. 

Thank you.

FDS v6.7.9

```
&HEAD CHID='2'/
&TIME T_END=10.0/

&MESH ID='Mesh01', IJK=5,5,5, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&SURF ID='Surface01',      COLOR='RED'/

&OBST ID='Obstruction', XB=0.0,0.6,0.4,0.4,0.0,1.0, SURF_ID6='INERT','INERT','INERT','Surface01','INERT','INERT'/ 

&TAIL /
```

```

&HEAD CHID='2'/
&TIME T_END=10.0/
&MESH ID='Mesh01', IJK=5,5,5, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&SURF ID='Surface01',      COLOR='RED'/

&OBST ID='Obstruction', XB=0.0,0.6,0.4,0.4,0.0,1.0, SURF_ID6='INERT','INERT','INERT','Surface01','INERT','INERT'/ 

&VENT ID='Vent', SURF_ID='INERT', XB=0.0,0.6,0.4,0.4,0.0,1.0, IOR=2, RGB=240,0,0/ 

&TAIL /
```

**Comment by FireResearch-BK** [comment]
I ran into something like this before.
FDS tends to move obstacles to the closest cell boundary, but not necessarily the associated vents, thereby separating vent from obstruction and producing this error. So I had to make sure that both vent and obstacle end up on the same cell boundary.

**Comment by Er9y714** [comment]
@FireResearch-BK I understand your example case.  However, in this case the OBSTrcution is at the cell boundary already.

**Comment by mcgratta** [comment]
I'll look into this more closely, but I think the logic for assigning VENTs to OBSTs may not consider thin OBSTs. Let me look.

**Comment by mcgratta** [comment]
The ERROR message was outdated. I removed it.

**Comment by Er9y714** [comment]
Thank you very much.
