### ISSUE TITLE
DEVC - Volume flow at boundary 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11046]
I would like to report an observation and suggest an addition/remark to the User guide 21.10.9 Volume Flow - Volume Flow at a Boundary.

If the volume flow measurement at a boundary device is not positioned exactly at a boundary location (positioned with a small offset):
1. It does not snap to the nearest surface. (does not measure the flow).
2. However, if IOR input is added, then it works and measures.

I suggest adding a warning/recommendation of using IOR for this device in the User Guide.

Thank you for your support. 

The fds file below demonstrates that by comparing two devices with an 0.01 m offset, one with IOR, one without. 

```

&HEAD CHID='vol_flow'/
&TIME T_END=10.0/
&DUMP  DT_DEVC=1.0, DT_SLCF=1.0/

&MESH ID='Mesh01', IJK=12,13,28, XB=2.4,3.6,1.5,2.8,29.2,32.0/


&DEVC ID='Exhaust_Vol_flow_boundary1', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=2.91,2.91,2.4,2.7,29.2,31.6/

&DEVC ID='Exhaust_Vol_flow_boundary2', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=2.91,2.91,1.7,2.0,29.2,31.6, IOR=1/

&SURF ID='Exhaust',
      RGB=26,128,26,
      VOLUME_FLOW=5/

&OBST ID='wall', XB=2.4,2.9,1.5,2.8,29.2,32.0/ 
&OBST ID='wall', XB=2.9,3.6,2.1,2.2,29.2,32.0/ 

&VENT ID='Extract1', SURF_ID='Exhaust', XB=2.9,2.9,2.4,2.7,29.2,31.6/ 
&VENT ID='Vent', SURF_ID='OPEN', XB=3.6,3.6,1.5,2.8,29.2,32.0/ 
&VENT ID='Extract2', SURF_ID='Exhaust', XB=2.9,2.9,1.7,2.0,29.2,31.6/ 

/SLCF QUANTITY='VELOCITY', PBZ=30.6/
/DEVC ID='Exhaust_Vol_flow_gas1', QUANTITY='U-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=3.31,3.31,2.2,2.8,29.2,32.0/
/DEVC ID='Exhaust_Vol_flow_gas2', QUANTITY='U-VELOCITY', SPATIAL_STATISTIC='AREA INTEGRAL', XB=3.3,3.3,1.5,2.1,29.2,32.0/

&TAIL /

```

**Comment by mcgratta** [comment]
Thanks. I added some text to the User's Guide. For surface integrals, one should make XB a volume that encloses all possible surfaces that are summed.

**Comment by Er9y714** [comment]
Thank you @mcgratta !
