### ISSUE TITLE
An OBSTruction is added at boundary near proximity of other mesh

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11045]
Hi,

I would like to share an occurrence that takes place near the boundary. 

When an obstruction is placed at the finer mesh, at a distance to the coarse mesh of 0.5 times the cell size of the coarse mesh, the coarse mesh generates this zero thickness obstruction at the boundary. 

Then I recalled this [issue](https://github.com/firemodels/fds/issues/5770), but I think MESH_ID input on OBST line is not valid anymore since I receive error when trying to run on FDS. Could you please confirm if this is still valid and if it is still the right way of solving this issue?

Thank you for checking the case. 

&HEAD CHID='test'/
&TIME T_END=10.0/
&MESH ID='Mesh01', IJK=5,5,5, XB=0.0,1.0,0.0,1.0,0.0,1.0/
&MESH ID='Mesh02', IJK=4,10,10, XB=0.0,0.4,-1.0,0.0,0.0,1.0/
&MESH ID='Mesh03', IJK=6,9,10, XB=0.4,1.0,-1.0,-0.1,0.0,1.0/

&OBST ID='Obstruction', XB=0.6,0.8,-0.2,-0.1,0.0,1.0/ 
&OBST ID='Obstruction', XB=0.0,0.2,-0.2,-0.1,0,1.0/ 

&VENT ID='Vent', SURF_ID='OPEN', XB=0.4,1.0,0.0,0.0,0.0,1.0/ 

&TAIL /

![image](https://user-images.githubusercontent.com/26166281/197470370-a0a50f84-0312-4e99-9fe5-a84d86a16c8d.png)

![image](https://user-images.githubusercontent.com/26166281/197470282-b1b9e734-2a56-49fc-b4fd-6590931310b6.png)

**Comment by mcgratta** [comment]
I fixed the issue. The code logic looks for all OBSTs that are within one half a grid cell of the current mesh, but it does not check to see if there is a gap between the current mesh and some other mesh. It is not unusual for users to change the MESH bounds but retain the complete geometry. In such cases, we do not want to reject these near OBSTs. The added logic distinguishes OBSTs that might be in another mesh from OBSTs that are just out of bounds.

**Comment by Er9y714** [comment]
Thank you @mcgratta !
