### ISSUE TITLE
Heat transfer and conservation of energy

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11055]
Consider this case:
```
&HEAD CHID='ht1d_beam_heating' /
&MESH IJK=20,4,10, XB=0.0,2.0,0.3,0.7,0.0,1.0 /
&TIME T_END=3600, DT=0.05 /
&RADI RADIATION=F /
&OBST XB=0.10,1.90,0.49,0.51,0.24,0.76, SURF_ID='STEEL SLAB' /
&INIT XB=0.00,2.00,0.30,0.70,0.00,1.00, TEMPERATURE=800 /
&SURF ID='STEEL SLAB', MATL_ID='STEEL', COLOR='BLACK', THICKNESS=0.02 /
&SURF ID='WALL', COLOR='GRAY', ADIABATIC=T, DEFAULT=T /
&MATL ID='STEEL', DENSITY=7500, SPECIFIC_HEAT=0.5, CONDUCTIVITY=50 /
&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=T /
&DEVC ID='temp', QUANTITY='TEMPERATURE', SPATIAL_STATISTIC='MEAN', XB=0.0,2.0,0.3,0.7,0.0,1.0 /
&DEVC ID='wall temp', QUANTITY='WALL TEMPERATURE', SPATIAL_STATISTIC='MEAN', XB=0.05,1.95,0.35,0.65,0.05,0.95 /
&DEVC ID='E', QUANTITY='INTERNAL ENERGY', SPATIAL_STATISTIC='VOLUME INTEGRAL', XB=0.0,2.0,0.3,0.7,0.0,1.0, RELATIVE=T /
&TAIL /
```
It is a steel slab inside a hot, sealed chamber, no radiation, adiabatic walls. Run it and you'll see that the change in internal energy of the gas is within a percent of the energy absorbed by the steel, c rho V delta T, or about 162 kJ. The volume is the snapped volume of the slab (0.0216 m³), not the actual volume, which is less. So we are not adjusting for the change in area of the solid faces. As a first attempt to fix, I changed this line in divg.f90
```
   ! Q_LEAK accounts for enthalpy moving through leakage paths
   DP(IIG,JJG,KKG) = DP(IIG,JJG,KKG) - ( ONE_D%Q_CON_F*ONE_D%RDN - WC%Q_LEAK ) * ONE_D%AREA_ADJUST
```
I added the area-adjust factor. But this makes very little difference in the energy balance. I'm wondering if I'm missing something obvious or is this related to recent changes in solid enthalpy.

Don't make any permanent changes to the code because I need to make this work in 3D. That's how I got on to this topic in the first place. But we should sort out the 1D problem first before complicating further.

**Comment by drjfloyd** [comment]
I don't think AREA_ADJUST should apply to Q_LEAK.  Q_LEAK already accounts for the actual area of a vent.

In HVAC_BC we have these lines

MFT = -DUCTNODE(ONE_D%NODE_INDEX)%DIR(1)*DUCT_MF(DU)/NODE_AREA_EX(ONE_D%NODE_INDEX)
.....
Q_LEAK = -MFT*(H_D-H_G)*ONE_D%RDN

NODE_AREA_EX is the total area of the VENT in the FDS domain. 

I don't think recent changes would have impacted this. There is no reaction for the MATL so there shouldn't have been any adjustment of the ML%H array. With no reactions there is no renoding and the temperature extraction would not have been used.

I'll take a look and see what I can find.

**Comment by drjfloyd** [comment]
Looking at the source, the default OB%SHAPE is 'null' which gives SHAPE_TYPE=-1. With this it looks like AREA_ADJUST=1 in init.f90. 

If you did have the AREA_ADJUST working, the mass for heat transfer wouldn't be the volume times the density. For 1D heat transfer, the mass is the surface area times the thickness times the density. OBST volume doesn't play a role in the solid enthalpy. Volume only matters for 1D pyrolysis if a bulk density is set and there it just sets the maximum mass that can be pyrolyzed. Heat transfer is still based on the surface area and thickness.

I took your case and changed the background to be MW=28 with cp=1.  Without making your AREA_ADJUST change, I calculate the equilibrium temperature to be 21.718 C.  I upped the time to 4 hours to give more time for complete convergence. The gas temperature was 21.733 C and the wall temperature 21.718 C. This gives energy changes of 140.35 kJ for the solid and 139.19 kJ for the gas, a difference of 1.16 kJ. However, the temperature difference of 0.014 C is 1.17 kJ in terms of the solid. The error is almost all that we still haven't quite reached equilibrium. The wall has a lot of mass. A little temperature change is a lot of energy compared to the same temperature change in the gas.

**Comment by mcgratta** [comment]
I checked that `AREA_ADJUST` is working. In this example, it is 0.8667. My thought is that by adding this to the line in divg.f90, I would be reducing the convective heat transfer from air to steel by 14 %. The 1-D heat transfer calculation would proceed normally. I'm just reducing the amount of energy transferred.

**Comment by mcgratta** [comment]
140 kJ is appropriate for the actual steel volume, so let me check what you've done. Maybe my calcs were off.

**Comment by drjfloyd** [comment]
Here is my calc:

I added these lines to make computing the exact solution easier:
&MISC STRATIFICATION = F/
&SPEC ID='S1',MW=28,SPECIFIC_HEAT=1/

The gas volume is 0.8 m^3. The density at 800 C is 0.3180 making the initial internal energy:

U = 0.8 x 0.3180 x (800+273.15) - 101325*0.8/1000 = 191.92 kJ.
There are 9.0847 moles of gas

Without the AREA_ADJUST, the steel volume is 1.8 x 0.6 * 0.02 = 0.0216 m3 (thin surface with EXPOSED so the steel volume for heat transfer is the area times the thickness. If the backside was INSULATED, then the volume would be twice this). This makes the initial steel enthalpy:

0.0216 x 7500 x 0.5 x 293.15 = 23745.15 kJ

Total energy is 23937.07 kJ

We need a temperature T such that

0.0216 x 7500 x 0.5 x T + 0.8 x 0.3180 x T- 9.0847 x 8.314472 x T/1000 = 23937.07

T = 294.868 K or 21.718 C

**Comment by mcgratta** [comment]
Yes, I get that. What I am trying to do is get this to work for the actual steel volume of 0.01872 m³.

**Comment by drjfloyd** [comment]
I ran the case below after adding ONE_D%AREA_ADJUST to the Q_CON_F term.  The expected end state is 21.9820 degrees.  At 7200 s the gas temperature was 22.05 C and the wall temperature was 21.98 C. The gas dropped 139.2 kJ and wall gained 139.1 kJ based on the actual volume of 0.01872 m3.

I then commented out the &SPEC line and ran it again. Since cp of air gets higher with temperature, I would expect a slightly higher end temperature. The result was gas 22.38 C and -161.9 kJ, and the wall 22.31 C and 162.1 kJ.

&HEAD CHID='ht1d' /
&MESH IJK=20,4,10, XB=0.0,2.0,0.3,0.7,0.0,1.0 /
&TIME T_END=7200, DT=0.05 /
&RADI RADIATION=F /
&MISC STRATIFICATION=F/
&SPEC ID='S1',MW=28,SPECIFIC_HEAT=1,BACKGROUND=T/
&OBST XB=0.10,1.90,0.49,0.51,0.24,0.76, SURF_ID='STEEL SLAB' /
&INIT XB=0.00,2.00,0.30,0.70,0.00,1.00, TEMPERATURE=800 /
&SURF ID='STEEL SLAB', MATL_ID='STEEL', COLOR='BLACK', THICKNESS=0.02,HEAT_TRANSFER_COEFFICIENT=20,HEAT_TRANSFER_COEFFICIENT_BACK=20 /
&SURF ID='WALL', COLOR='GRAY', ADIABATIC=T, DEFAULT=T /
&MATL ID='STEEL', DENSITY=7500, SPECIFIC_HEAT=0.5, CONDUCTIVITY=50 /
&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=T /
&DEVC ID='temp', QUANTITY='TEMPERATURE', SPATIAL_STATISTIC='MEAN', XB=0.0,2.0,0.3,0.7,0.0,1.0 /
&DEVC ID='wall temp', QUANTITY='WALL TEMPERATURE', SPATIAL_STATISTIC='MEAN', XB=0.05,1.95,0.35,0.65,0.05,0.95 /
&DEVC ID='URel', QUANTITY='INTERNAL ENERGY', SPATIAL_STATISTIC='VOLUME INTEGRAL', XB=0.0,2.0,0.3,0.7,0.0,1.0, RELATIVE=T /

**Comment by mcgratta** [comment]
When you say the Q_CON_F term, do you mean the line I cited in divg.f90,
without the Q_LEAK being altered?

**Comment by drjfloyd** [comment]
I did this:

   DP(IIG,JJG,KKG) = DP(IIG,JJG,KKG) - ( ONE_D%Q_CON_F*ONE_D%RDN*ONE_D%AREA_ADJUST - WC%Q_LEAK )

**Comment by mcgratta** [comment]
Yes, that's what I thought. Can you think of a reason not to commit this? We probably have to do something similar for radiation.

**Comment by drjfloyd** [comment]
I think it makes sense to commit. I don't know that we can do the same for radiation we are physically blocking an entire cell face. If we adjusted the area then I think we would no longer conserve radiant energy.

**Comment by mcgratta** [comment]
OK, I'll commit and work up some verification cases. I'm doing something similar in 3D, but now the web has flanges, and all are zero cells thick. Then I add insulation. That gets tricky because the assembly might become one cell thick and the volumes and surface areas are confusing.
