### ISSUE TITLE
Numerical instability when adding DEVC for flame height calculations

### ISSUE THREAD

**Issue by ahsadeghi** [firemodels/fds#11072]
Hello,
I get numerical instability when I add the following lines to the input file for calculating flame height.

&DEVC XB=0.099,0.099,0.1,0.1,0.066,0.784, QUANTITY='HRRPUL', POINTS=50, Z_ID='z', ID='qdot', STATISTICS_START=0.0 /
&CTRL ID='pct', FUNCTION_TYPE='PERCENTILE', INPUT_ID='qdot', PERCENTILE=0.97 /
&DEVC ID='L_F', XYZ=0,0,0, QUANTITY='CONTROL VALUE', CTRL_ID='pct', UNITS='m' /

Please see the input file below for examinations.
[model_20220906.txt](https://github.com/firemodels/fds/files/9895822/model_20220906.txt)

Your supports are highly appreciated. Thank your for your considerations.

BR,
Hosein

**Comment by mcgratta** [comment]
At what point in the simulation does the instability occur?

**Comment by ahsadeghi** [comment]
at t=2.95 s

**Comment by mcgratta** [comment]
The case seems to be running OK for me. Try removing this line
```
 CLIP CLIP_DT_RESTRICTIONS_MAX=0 /
```
I do not think you need it. If the case still fails, try using the [latest test version](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC).

**Comment by ahsadeghi** [comment]
Thank you. I still get the error. Did you run the case with [this version](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC) ? I need the source files to compile but the link only contains the executable files. Are they on the [git page](https://github.com/firemodels/fds)?

**Comment by mcgratta** [comment]
I am running FDS6.7.9-736 on a linux cluster. If you want to compile yourself, checkout the fds repo from GitHub. There are some [compiling instructions here](https://github.com/firemodels/fds/wiki). Your job is still running on my cluster. It has progressed 28 s.

**Comment by ahsadeghi** [comment]
Thank you.

**Comment by ahsadeghi** [comment]
Dear Kevin,
I have downloaded the latest version from [git](https://github.com/firemodels/fds) and compiled it, but I still get numerical instability. This time at t=3.01 s.
Did you mean that I can run [this version](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC) on cluster without compilation?

**Comment by mcgratta** [comment]
Show me this from the .err or .out file for the case that you ran that
failed. What OS are you using?

 Fire Dynamics Simulator

 Current Date     : November  2, 2022  09:54:56
 Revision         : FDS6.7.9-736-g04a8de4-master
 Revision Date    : Wed Oct 26 21:15:52 2022 -0400
 Compiler         : ifort version 19.1.2.254
 Compilation Date : Oct 27, 2022 12:16:37

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS

**Comment by ahsadeghi** [comment]
Please see below. It seems mine is version 571.


Fire Dynamics Simulator

 Current Date     : November  2, 2022  12:12:02
 Revision         : FDS6.7.9-571-gca5a4ae65-dirty-master
 Revision Date    : Thu Oct 6 19:08:18 2022 +0100
 Compiler         : 
 Compilation Date : Nov 02, 2022  10:55:31

 MPI Enabled;    Number of MPI Processes:      18
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v4.1.1, package: Open MPI er_hpc_build@erc-hpc-comp002 Distribution, ident: 4.1.1, repo rev: v4.1.1, Apr 24, 2021

**Comment by mcgratta** [comment]
What is your compiler and OS? Why is your source code "dirty"?

**Comment by ahsadeghi** [comment]
I used this compiler on our cluster:  openmpi/4.1.1-gcc-9.4.0-ucx  (I don't know exactly the name) with gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
I compiled with ompi_gnu_linux/make_fds.sh
the OS is Linux
I don't know what does "dirty" mean here?!

**Comment by mcgratta** [comment]
Did you alter the source code? That is what "dirty" means.

**Comment by ahsadeghi** [comment]
No I just downloaded fds-master from GitHub and compiled. (copied to firemodels/fds folder)

**Comment by mcgratta** [comment]
If you comment out these lines
```
&DEVC XB=0.099,0.099,0.1,0.1,0.066,0.784, QUANTITY='HRRPUL', POINTS=50, Z_ID='z', ID='qdot', STATISTICS_START=0.0 /
&CTRL ID='pct', FUNCTION_TYPE='PERCENTILE', INPUT_ID='qdot', PERCENTILE=0.97 /
&DEVC ID='L_F', XYZ=0,0,0, QUANTITY='CONTROL VALUE', CTRL_ID='pct', UNITS='m' /
```
does the simulation succeed?

**Comment by ahsadeghi** [comment]
yes

**Comment by mcgratta** [comment]
Well, I cannot reproduce this error using the Intel oneAPI base and HPC toolkits. I can only advise that you should not use those lines. I have no idea why they would cause the simulation to fail, but there are a number of things that I do not understand about how you are cloning repositories, compiling, and running the code. You may want to compile the code in debug (db) mode and run it and see if you get an error message that might point out where the problem lies. Otherwise, comment out those lines.

**Comment by ahsadeghi** [comment]
Thank you.

**Comment by ahsadeghi** [comment]
I compiled in the db mode and I got the following error after a while:
...
mpifort -c -m64 -O0 -std=f2018 -ggdb -Wall -Werror -Wunused-parameter -Wcharacter-truncation -Wno-targe                                              t-lifetime -fcheck=all -fbacktrace -ffpe-trap=invalid,zero,overflow -frecursive -ffpe-summary=none -fal                                              l-intrinsics -fbounds-check -cpp -DGITHASH_PP=\"FDS6.7.9-571-gca5a4ae65-dirty-master\" -DGITDATE_PP=\""                                              Thu Oct 6 19:08:18 2022 +0100\"" -DBUILDDATE_PP=\""Nov 02, 2022  17:31:28\"" -DCOMPVER_PP=\"\"   -fopen                                              mp ../../Source/divg.f90
gfortran: fatal error: Killed signal terminated program f951
compilation terminated.
make: *** [../makefile:135: dump.o] Error 1
make: *** Waiting for unfinished jobs....


What can I understand from this?

**Comment by marcosvanella** [comment]
Hosein, what hardware and operating system are you compiling on? Are you compiling interactively in a cluster?
From what I gather online seems your system run out of memory while compiling.

**Comment by mcgratta** [comment]
This is what I see
```
mpifort -c -m64 -O0 -std=f2018 -ggdb -Wall -Werror -Wunused-parameter -Wcharacter-truncation -Wno-target-lifetime -fcheck=all -fbacktrace -ffpe-trap=invalid,zero,overflow -frecursive -ffpe-summary=none -fall-intrinsics -fbounds-check -cpp -DGITHASH_PP=\"FDS6.7.9-757-gab82b12-master\" -DGITDATE_PP=\""Wed Nov 2 12:36:35 2022 -0400\"" -DBUILDDATE_PP=\""Nov 02, 2022  14:42:24\"" -DCOMPVER_PP=\""Gnu gfortran 9.3.1"\" -DWITH_MKL -I/opt/intel/oneapi/mkl/2022.2.0/include  -fopenmp ../../Source/divg.f90
```
It is not worth trying to figure out what is wrong with your compiler. 

Are you sure that you cannot use the pre-compiled version of FDS that you download? I am suspicious that your system might be missing important libraries or you are using some older version of the Fortran compiler.

**Comment by ahsadeghi** [comment]
Dear Marcos- Thank you. I think you were correct, finally I could run it without error and I got the fds_ompi_gnu_linux_db file.

Dear Kevin- I could install the [pre-compiled version ](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC), and I try to run with the following bash file


#!/bin/bash -l
#SBATCH --ntasks=18
#SBATCH --nodes=1
#SBATCH --job-name=LCO_max_35
#SBATCH --output=openmpi.out.%j
module load openmpi
mpirun /scratch/prj/nmes_fire_modelling/pre_compiled_FDS/FDS/FDS6/bin/fds /scratch/users/k21140758/LCO_max/model_20220906_04_LCO_max_36_01/model_20220906.fds


where the path _/scratch/prj/nmes_fire_modelling/pre_compiled_FDS/FDS/FDS6/bin/fds_ is for the exe file and _/scratch/users/k21140758/LCO_max/model_20220906_04_LCO_max_36_01/model_20220906.fds_ is for the input file. 

But I get the following error:



 Fire Dynamics Simulator

 Current Date     : November  2, 2022  21:51:38
 Revision         : FDS6.7.9-748-gfa5cee4f0-nightly
 Revision Date    : Mon Oct 31 13:51:24 2022 -0400
 Compiler         : ifort version 2021.7.0
 Compilation Date : Nov 02, 2022 08:33:31

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Linux* OS


 Job TITLE        : 
 Job ID string    : model_20220906

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 9 with PID 1289295 on node erc-hpc-comp018 exited on signal 9 (Killed).
--------------------------------------------------------------------------
slurmstepd-erc-hpc-comp018: error: Detected 1 oom-kill event(s) in StepId=973502.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.





Am I doing wrong in the bash file?



Hosein

**Comment by mcgratta** [comment]
MPI Enabled; Number of MPI Processes: 1

This means that FDS has started, but it thinks that there is only one MPI process.  We use slurm like this
```
#!/bin/bash
#SBATCH -J junk
#SBATCH -e <wdir>/junk.err
#SBATCH -o <wdir>/junk.log
#SBATCH --partition=batch
#SBATCH --ntasks=18
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=99-99:99:99

cd <wdir>
srun -N 1 -n 18 --ntasks-per-node 18 <path to executable> junk.fds
```

**Comment by marcosvanella** [comment]
Also, why do you load the openmpi module in your script? The linux bundle (and FDS) have been compiled with Intelmpi. You want to use the Intel mpirun distributed with the bundle.
Try replacing
module load openmpi
with
source /scratch/prj/nmes_fire_modelling/pre_compiled_FDS/FDS/FDS6/bin/FDS6VARS.sh
in your submission script., or take out the load openmpi and add the source line in your ~/.bashrc file.

**Comment by ahsadeghi** [comment]
Thank you so much.
