### ISSUE TITLE
possible fds slowdown

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#11075]
over the last week or so I've noticed smokebot taking a lot longer to run.  It usually takes about an hour.  The time increased to 2 hours then over the last couple of days it is taking 4 to 5 hours.  The main culprit is the the Verification/WUI/levelset2.fds case  . Don't think it is a cluster issue.  Wanted to start an issue so this doesn't fall through the cracks.  I"ll see if I can narrow it down to a commit and also see if I can duplicate problem on the burn cluster

**Comment by mcgratta** [comment]
I added this line
```
&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=T /
```
to the file and notice a lot of "noise" at the mesh boundary. Two possibilities --- GEOM or the stretched grid or both.

**Comment by marcosvanella** [comment]
@gforney, PR #11086 should address this issue. I restored the Verification/WUI/levelset2.fds to it's original form. Check that smokebot runs correctly and close the issue.
Thanks.

**Comment by gforney** [comment]
back to normal. thanks.
