### ISSUE TITLE
Add spark ignitor feature

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11088]
As we have been discussing, let's add the capability to locate a "spark" using a particle.  Take whatever cell the particle occupies and create an AIT_EXCLUSION_ZONE for that cell.  So, we want these COMB and INIT lines to be equivalent.

```
&MESH IJK=10,10,10, XB=0,1,0,1,0,1/
&COMB AIT_EXCLUSTION_ZONE=0.4,0.5,0.4,0.5,0.4,0.5/
&INIT XYZ=0.45,0.45,0.45, PART_ID='RESERVED IGNITOR ID'/
```

Also, the ignitor should be capable of a time ramp.

**Comment by mcgratta** [comment]
OK, I set this up so that a "spark" is invoked by a DEVC line with a QUANTITY='TIME' and SETPOINT. So it works much like a sprinkler or other device such that we can control these things appropriately. I have to check some things, but seems to be working.

**Comment by mcgratta** [comment]
I am now implementing the SPARK feature and doing some overhaul on AIT and AIT_EXCLUSOIN_ZONE. Let me know if you are doing extensive work in these areas.

**Comment by mcgratta** [comment]
I added the SPARK using a DEVC and PROP line, like you would do a smoke detector or sprinkler. That gives us control over timing and positioning.
