### ISSUE TITLE
Heat conduction in thin obstructions

### ISSUE THREAD

**Issue by ASpallek** [firemodels/fds#11082]
Hello there,
Is there already a possibility of heat conduction between thin obstructions e.g. steel beams like HEA400?
Or will this only come with the new beta next year?

In a simple case, I created the beam from three separate thin obstructions and I would like to get conduction from the lower flank to the web.

![Beam](https://user-images.githubusercontent.com/106251977/199670429-c6034a85-4288-44f2-a4e1-79e74814b7e1.png)

best regards
Alex

**Comment by drjfloyd** [comment]
This is not currently possible, but it is under active development. See here for features being worked on for FDS 7: https://github.com/firemodels/fds/wiki/FDS-Release-Notes
