### ISSUE TITLE
Excessive communication time for level set 1

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11097]
Kevin, as discussed here is a case where the meshing is somewhat complex to eventually handle more detailed computations, but I'd like to start simple with `LEVEL_SET_MODE=1`. The CPU output shows between 60-80% of time spent in COMM which seems excessive since the gas-phase quantities do not need to be updated. 

[SSFP_LS1.txt](https://github.com/firemodels/fds/files/9972984/SSFP_LS1.txt)

**Comment by mcgratta** [comment]
I commented out a lot of the MPI calls. Try it now.

**Comment by ericvmueller** [comment]
Thanks! I ran with 598fd92 and COMM still makes up 70-80% of the time, but the overall computational time is reduced by nearly 80% so there is a big improvement there. The fact that the mesh exchanges still dominate may be unavoidable with the configuration I have.

**Comment by mcgratta** [comment]
This is what I get

![image](https://user-images.githubusercontent.com/11333911/200934166-5c976594-b9de-4569-954c-21eb6bfa9d84.png)

**Comment by ericvmueller** [comment]
Okay - the extra time was cluster related. I get the same now. Thanks!
