### ISSUE TITLE
Numerical instability in a simple project without enclosed volume

### ISSUE THREAD

**Issue by mst-lyubimov** [firemodels/fds#11095]
In the proposed simple project, numerical instability occurs at the 5th second.
Could you please suggest why the error occurs and how it could have been predicted before the simulation started.
[test.txt](https://github.com/firemodels/fds/files/9969921/test.txt)

**Comment by drjfloyd** [comment]
You have a portion of your burning wall with only one grid cell between the burning surface and the edge of the domain at Y=17 m. Try extending your domain

**Comment by mst-parkhachev** [comment]
@drjfloyd Thanks for the help!
Previously, I did not know that the burning surface should not be located close to the boundary of the domain. Is this information available in the user manual? Maybe I missed it, but I don't know which chapter to look in.

Could you explain in more detail why the error occurs even though the domain boundary is open? Does this constraint only apply to the boundary of a domain, or also to the boundary of two meshes? If I add another mesh to the problem area, the error disappears.

Could you state the constraint as precisely as possible? What mutual position of the burning surface and the boundary of the domain (or mesh?) should not be allowed when building a project? Is two cells distance safe enough?

**Comment by mcgratta** [comment]
It is assumed that the pressure at an open boundary is ambient, but that is really not true if there is a fire very close. To compute a better approximation of pressure, add another mesh or more cells to move the open boundary away.

**Comment by mst-parkhachev** [comment]
Can we be sure that two cells distance between the burning surface and the open boundary will always be sufficient to solve such a problem?

**Comment by mcgratta** [comment]
No. CFD doesn't work like that. Suppose your fire is an oil well blowout? For any scenario you should monitor gas velocity and pressure and decide where it is appropriate to put on OPEN boundary.

**Comment by drjfloyd** [comment]
No further updates from OP since Nov 2022, closing the issue.
