### ISSUE TITLE
Change background slices color in FDS smoke view file

### ISSUE THREAD

**Issue by Duy-Doan** [firemodels/fds#11093]
Hi All, i'm using Pyrosim, the model run without any errors, but the background color slice view for soot visibility turning red and i don't know how to change it, that color look pretty dangerous if we show them to the presentation, while the slice temp look very well in blue color. Could you help me how to solve this problem? ( My VIS slice bound data set min 0m to max 30m, Temp SLice set min 25 to max 60)

**Comment by drjfloyd** [comment]
If you are using smokeview to view results right click in the smokeview window and select show/hide -> color -> colorbar type -> flip
If you are using the pyrosim viewer please contact Thunderhead Engineering for support with their product
