### ISSUE TITLE
Potentially broken calculation of convective heat transfer coefficient using default model

### ISSUE THREAD

**Issue by bran-jnw** [firemodels/fds#11103]
A recent change in FDS has affected the calculated heat transfer coefficient when using the default model. Case is just a simple hot plate with blowing wind upwards (0.5 m/s) and measuring h along the center line:
![image](https://user-images.githubusercontent.com/10062546/201374204-6fb89f67-8d2c-4d21-acb5-28415f4e6d04.png)

In FDS 6.7.6 the output looks like this:
![image](https://user-images.githubusercontent.com/10062546/201371826-0a854af4-a3c6-4b82-8dfb-3f9f0eec4e55.png)

While in FDS 6.7.9 it looks like this:
![image](https://user-images.githubusercontent.com/10062546/201371633-9c432b2e-9638-4d38-90f9-efb1aa37d6e0.png)

Guessing that either NUSSELT_FORCED (updated in NATURAL_CONVECTION_MODEL) or NUSSELT_FREE (updated in FORCED_CONVECTION_MODEL) has been affected (lowered) and that the max returned value in MAX(NUSSELT_FORCED,NUSSELT_FREE,2._EB*CONV_LENGTH/DN)*K_G/CONV_LENGTH is no longer (as often) based on numbers coming from the convection subroutines (which would explain the graph looking like it is hitting a ceiling value).

**Comment by mcgratta** [comment]
Post the input file.

**Comment by bran-jnw** [comment]
Had to put it in a zip file for Github, but here it is.
[standard_conv_20cm.zip](https://github.com/firemodels/fds/files/9991461/standard_conv_20cm.zip)

**Comment by mcgratta** [comment]
I suspect that the issue has to do with a change in the correlation that we use. Newer versions of Incropera and deWitt recommend a slightly different forced convection Nusselt number. Note the subtraction of 871 in the formula in the FDS User's Guide:

![image](https://user-images.githubusercontent.com/11333911/201387532-7282a020-7cd8-479b-9fc8-bb6702243a09.png)
![image](https://user-images.githubusercontent.com/11333911/201387614-c20ca14c-7c91-45bd-a1aa-2c0061aa3316.png)

That extra term of 871 roughly cuts the HTC in half in your case. I cannot say which is right or wrong, the old form or the new. For this kind of thing, we run all the validation cases and see if there is something that really looks off. The convective heat transfer coefficient usually is a minor player, so it is hard to know its effect.

**Comment by bran-jnw** [comment]
Thanks, that could explain it, it was just a bit jarring to see when comparing to the LOGWALL model (with VISCOUS WALL UNITS in the order of 300-1200); before they were in the same ballpark but now the default model is closer to 25% of the LOGWALL model. 

FDS 6.7.9 (figure showing default model using 10 and 20 cm mesh, and LOGWALL using the same grid sizes, also showing specified heat transfer coefficient):
![image](https://user-images.githubusercontent.com/10062546/201402530-60919978-6655-4f9b-b7f5-f023e0be32a9.png)

This is what is looked like before in FDS 6.7.6 (axises are flipped here compared to other figure, these are old student assignments so could not change them):
![image](https://user-images.githubusercontent.com/10062546/201402628-e9fc5bc5-3485-4684-9333-c11939261eae.png)

I will look a bit more into it since cranking up the velocity to 10 m/s (and therefore Re) yields "better" yet choppy results:
![image](https://user-images.githubusercontent.com/10062546/201403398-69a52315-c905-4ec6-8590-072923e10f34.png)

**Comment by mcgratta** [comment]
I'll have another look at I&D. Maybe we're not in the right Re number range, or we're at the cusp of two regimes.

**Comment by bran-jnw** [comment]
Just took another quick look at this, I think confusion similar to mine could be avoided if:

- The documentation for changing C0, C1, C2, n and m was added back in the manual (seems to be gone in the latest manual but was present before).
- Make it clear that the standard forced convection constants are based on a critical Re of 5*10^5 and that the resulting h is the average of the laminar and turbulent region along the entire "plate" (L).
- As per default values, it might make more sense to use the old values (i.e. set C2 to 0) as that assumes that the laminar initial region is negligible compared to the turbulent flow regions, which I think might be a more common case, but this is just a guess/opinion. The way that it is set now it constantly is assumed that we are at the beginning of a starting flow instead of assuming that we were in the fully turbulent region in the older version.
- Might also be good to recalculate C2 if CONVECTION_LENGTH_SCALE is changed by the user as that can change the integration done to arrive at C2=871, but this could also be done by the user as long as it is clear where the number comes from.

**Comment by mcgratta** [comment]
We restored the custom C0, C1, and C2 in the current source code. They are called `NUSSELT_C0`, `NUSSELT_C1`, and `NUSSELT_C2`. 

Good idea about C2. My motivation was to follow the conventional formulae as much as possible, but you are right. This might not appropriate for us.

**Comment by rmcdermo** [comment]
I've updated the source to the local turbulent correlation in Incropera and Dewitt.  See PR #11122 

I'm adding some validation cases.  Let's leave this open until that is finished.

**Comment by rmcdermo** [comment]
I've added FDS comparisons to various correlations for forced and natural convection to the verification guide.  The results look reasonable with the latest code. PRs #11194 #11200 #11201
