### ISSUE TITLE
forrtl: severe (157): Program Exception - access violation

### ISSUE THREAD

**Issue by FireDynamo** [firemodels/fds#11110]
The following error is occurring while attempting to run an FDS test case - 

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source             
fds.exe            00007FF734867DE6  Unknown               Unknown  Unknown
fds.exe            00007FF7349ADAAE  Unknown               Unknown  Unknown
fds.exe            00007FF73475C502  Unknown               Unknown  Unknown
fds.exe            00007FF7347287FE  Unknown               Unknown  Unknown
fds.exe            00007FF7350CA8E4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE8CD67034  Unknown               Unknown  Unknown
ntdll.dll          00007FFE8D2026A1  Unknown               Unknown  Unknown

It is unclear what the issue is as the identical test case is working under a separate scenario. If replying to this Gmail account fds.questions@gmail.com with your email address, it will be possible to provide a direct contact to offer the source file.

Thank you.

[Scenario_5A.zip](https://github.com/firemodels/fds/files/10007246/Scenario_5A.zip)

**Comment by mcgratta** [comment]
I do not see an input file for this case.

**Comment by FireDynamo** [comment]
I have updated the comment above with the input file included.

**Comment by mcgratta** [comment]
Jason -- run this case with the new source. It produces an input error. This error is not related to the problem identified in the post. It's just a good example of a complicated input file.

**Comment by drjfloyd** [comment]
I see the error. SOOT is redefined in the input file and my guess is the new source is not picking up that the definition didn't redefine the enthalpy.

**Comment by FireDynamo** [comment]
Drs. Floyd and McGrattan, you are both correct. I did review the reactant and product information and there are a few unviable elements as it currently standards. I'll work on resolving these. 

As pertains to the original error on this thread, the following test cases should return the previously mentioned error. 

Note: Scenario 4A and 4B are nearly identical, the main difference being speeds applied at vents. With this said, Scenario 4B is running, whereas, Scenarios 2 and 4A are not.

My apologies for the original confusion.

[Scenario_4B.zip](https://github.com/firemodels/fds/files/10007666/Scenario_4B.zip)
[Scenario_4A.zip](https://github.com/firemodels/fds/files/10007667/Scenario_4A.zip)
[Scenario_2.zip](https://github.com/firemodels/fds/files/10007668/Scenario_2.zip)

**Comment by drjfloyd** [comment]
There was a stale pointer reference that this case hit. Should be fixed

**Comment by FireDynamo** [comment]
Thank you, Jason

**Comment by mcgratta** [comment]
The case Scenario_5A.fds is running with this version:
```
 Fire Dynamics Simulator

 Current Date     : November 14, 2022  17:54:25
 Revision         : FDS6.7.9-901-g80c808369-three_d
 Revision Date    : Thu Nov 10 13:44:33 2022 -0500
 Compiler         : ifort version 2021.7.0
 Compilation Date : Nov 10, 2022 14:16:22

 MPI Enabled;    Number of MPI Processes:      24
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS
```
After addressing the problem Jason identified, is the case now working for you?

**Comment by FireDynamo** [comment]
Hi, thanks for the follow up,

The first issue with Scenario #5B is ok. There were duplicate SOOT entries, one viable and the other requiring redefinition. I've left it be for now as the correctly defined SOOT entry is working just fine.

Regarding the second issue, the stale pointer reference. I haven't had the opportunity to download the most recent FDS build as mine dates back to June and the update was only made last night. Where am I able to download the most recent build to see if the revisions to the source code fixed the issues seen with Scenarios 2, #A and 4B?

Fire Dynamics Simulator

 Current Date     : November 15, 2022  15:46:41
 Revision         : FDS6.7.9-0-gec52dee42-release
 Revision Date    : Sun Jun 26 14:36:40 2022 -0400
 Compiler         : 
 **Compilation Date : Tue 06/28/2022  11:11 PM**

 MPI Enabled;    Number of MPI Processes:       5
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Windows* OS


 Job TITLE        : 
 Job ID string    : Scenario_2

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source             
fds.exe            00007FF779EF7DE6  Unknown               Unknown  Unknown
fds.exe            00007FF77A03DAAE  Unknown               Unknown  Unknown
fds.exe            00007FF779DEC502  Unknown               Unknown  Unknown
fds.exe            00007FF779DB87FE  Unknown               Unknown  Unknown
fds.exe            00007FF77A75A8E4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE844A7034  Unknown               Unknown  Unknown
ntdll.dll          00007FFE862626A1  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 2033108 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 2285424 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 2287196 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 2290156 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
[runfds.exe] subprocess exit: -1


 Job TITLE        : 
 Job ID string    : Scenario_4A

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source             
fds.exe            00007FF779EF7DED  Unknown               Unknown  Unknown
fds.exe            00007FF77A03DAAE  Unknown               Unknown  Unknown
fds.exe            00007FF779DEC502  Unknown               Unknown  Unknown
fds.exe            00007FF779DB87FE  Unknown               Unknown  Unknown
fds.exe            00007FF77A75A8E4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE844A7034  Unknown               Unknown  Unknown
ntdll.dll          00007FFE862626A1  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 2292376 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 2283876 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 2291388 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 2255180 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 2291584 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 6 PID 2293108 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 7 PID 2292924 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 8 PID 2291356 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
[runfds.exe] subprocess exit: -1


Job TITLE        : 
 Job ID string    : Scenario_4B

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source             
fds.exe            00007FF779EF7DE6  Unknown               Unknown  Unknown
fds.exe            00007FF77A03DAAE  Unknown               Unknown  Unknown
fds.exe            00007FF779DEC502  Unknown               Unknown  Unknown
fds.exe            00007FF779DB87FE  Unknown               Unknown  Unknown
fds.exe            00007FF77A75A8E4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE844A7034  Unknown               Unknown  Unknown
ntdll.dll          00007FFE862626A1  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 2281136 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 2291024 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 2286396 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 2283888 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 2290564 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 6 PID 2288808 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 7 PID 2292212 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 8 PID 2292244 RUNNING AT D20US-L0062JF8
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
[runfds.exe] subprocess exit: -1

**Comment by mcgratta** [comment]
Each night FDS is tested and if it passes, we put test bundles [here](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC). 

I am confused now with all the different cases (5A, 2B, etc). If there is something that is still causing a problem, post that input file. Just post one input file and tell us what the problem is. Also, no need to cut and paste all this "BSD TERMINATION" stuff. This just says that something failed and the job's processes are being shut down. It doesn't help us debug.

**Comment by FireDynamo** [comment]
Hi, Kevin,

Jason's changes to the source code yesterday evening resolved the errors in Scenarios 2, 4A, and 4B provided in the thread above, Note my apology for any confusion as well :).

https://github.com/firemodels/fds/commit/726106e193e127cdf3dc4cd49485bd954d1471a4
https://github.com/firemodels/fds/issues/11110#issuecomment-1314513031

I'll close the comment thread.

Thank you.
