### ISSUE TITLE
AMPUA Surface Integral over empty cells results in crash

### ISSUE THREAD

**Issue by Rhodehamei** [firemodels/fds#11127]
If you have a device with the quantity AMPUA and with the statistic surface integral, it will cause the crash "forrtl: severe (157): Program Exception - access violation" when no surfaces are within the device volume. 

I have attached bucket_test_1 from the examples folder with the device adjusted so that the device only contains empty cells. This causes a crash when I run it on FDS 6.7.9.

[bucket_test_1.txt](https://github.com/firemodels/fds/files/10025296/bucket_test_1.txt)

**Comment by mcgratta** [comment]
This was a null pointer problem. Hopefully it is fixed. Let me know if you have trouble when the volume is not empty. Thanks.
