### ISSUE TITLE
CHECK_MESH_ALIGNMENT

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11128]
Hi,

I wanted to test the mesh alignment check feature but I get an error. Is this how it is intended to be used? Thanks

&HEAD CHID='Checkmesh'/
&TIME T_END=0.0/ 

&MESH ID='Mesh01', IJK=10,10,15, XB=0.0,2.0,0.2,2.2,0.0,3.0 CHECK_MESH_ALIGNMENT=.TRUE./
&MESH ID='Mesh02', IJK=10,10,15, XB=2.0,4.0,0.2,2.2,0.0,3.0  /

&TAIL /

![image](https://user-images.githubusercontent.com/26166281/202287711-42db390c-8524-4236-abfa-1508c6aa8658.png)

**Comment by rmcdermo** [comment]
I'll take a look, thanks

**Comment by rmcdermo** [comment]
Kevin, looks like this is related to clock output.  Dies at Line 2936 in dump.f90 in dv mode.

**Comment by mcgratta** [comment]
I fixed it. FDS had not reached the part of the set up routines where it allocated a certain array that was then accesses. As a work-around, set T_END to a small number to force FDS to do one time step.
