### ISSUE TITLE
Flow Field

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11139]
Hi,

I wanted to setup a sample flow field case in FDS v6.7.9 and followed the User Guide. But there are some differences between the guide and the actual run. 

FDS currently generates files with numbers appended. However the numbers do not have leading zeros. For that reason PER_MESH=T does not function properly because it appends numbers with leading zeros (001, 002, ...)

CHID_uvw_t0_m1.csv
CHID_uvw_t0_m2.csv
CHID_uvw_t0_m3.csv 
...
CHID_uvw_t1_m1.csv
CHID_uvw_t1_m2.csv
CHID_uvw_t1_m3.csv
... 

**It should be :**

CHID_uvw_t0_m001.csv
CHID_uvw_t0_m002.csv
CHID_uvw_t0_m003.csv 
...
CHID_uvw_t1_m001.csv
CHID_uvw_t1_m002.csv
CHID_uvw_t1_m003.csv
...

Thank you for your support.

**Comment by mcgratta** [comment]
Randy -- I suggest that we make the `PER_MESH` option the only option and then either keep or remove the extra zeros. Probably better to remove them. I think we went through the code changing `I3.3` to `I0` but we missed this.

**Comment by rmcdermo** [comment]
@Er9y714 Please do me a favor and upload a zip with the files you want to be able to read in (and the input file).  Thanks

**Comment by Er9y714** [comment]
@rmcdermo Of course. I will prepare them by the weekend. Thanks.

**Comment by rmcdermo** [comment]
Hopefully this is fixed with PR #11141 , but I'd like a good test case, so thanks for sending your files when you get time.

**Comment by Er9y714** [comment]
@rmcdermo 

I have attached an .fds file and the .csv  files to be read in. 

Please also update the user guide. 'uvw' string should be added to the input file because FDS outputs a file name of CHID_**uvw**_tN_mM.csv:


&CSVF UVWFILE='CHID_**uvw**_t001_m', PER_MESH=T /


![image](https://user-images.githubusercontent.com/26166281/202740042-69e9b56f-d29d-48c2-848d-ff48fd907c00.png)


[velocity_field.zip](https://github.com/firemodels/fds/files/10042532/velocity_field.zip)


I hope this covers what you were expecting. Let me know if you need further support. 

Edit: I updated the attached file.

**Comment by rmcdermo** [comment]
Should be fixed.  Please test when you get a chance.

**Comment by Er9y714** [comment]
Thank you very much for the fix. 


> Should be fixed. Please test when you get a chance.

Sorry, I am not able to compile the FDS yet. But I will close the issue.
