### ISSUE TITLE
'&CSVF' and '&DUMP DT_UVW' use different number format

### ISSUE THREAD

**Issue by FraFabi** [firemodels/fds#11158]
Hi,

using `&DUMP DT_UVW=600 /` as stated in the User's Guide will output UVW-Files with the following naming:
```
CHID_uvw_t0_m1.csv
CHID_uvw_t0_m2.csv
...
CHID_uvw_t0_m10.csv
```
The CSVF namelist however expects the mesh numbers to have two leading zeroes when using `PER_MESH=T` - like this:

```
CHID_uvw_t0_m001.csv
CHID_uvw_t0_m002.csv
...
CHID_uvw_t0_m010.csv
```

That means, that UVW-files generated using `DT_UVW` can not be interpreted by the CSVF namelist automatically, unless the user renames them manually or using a seperate script.

**Comment by FraFabi** [comment]
Sorry, I just saw that this is a duplicate of #11139.

**Comment by drjfloyd** [comment]
FraFabi,  since this is, as you noted, a duplicate issue I will close this one.
