### ISSUE TITLE
FDS Crashes when using a PART emitter with only 1 species defined in the input file

### ISSUE THREAD

**Issue by uporersith** [firemodels/fds#11157]
Current Date     : November 24, 2022  23:27:29
 Revision         : FDS6.7.9-0-gec52dee42-release
 Revision Date    : Sun Jun 26 14:36:40 2022 -0400
 Compiler         :
 Compilation Date : Tue 06/28/2022  11:11 PM

I edited the surf_mass_part_specified.fds (section 17.4.7 of the users manual) to make these changes:

deleted all the SPEC ID lines and replaced them with only these two lines:

&SPEC ID='LJ AIR', BACKGROUND=T/
&SPEC ID='EXH_GAS', COPY_LUMPED=T, SPEC_ID='LJ AIR'/

I modifed the plate emitter to only emit EXH_GAS. i deleted all the other emitters

I modifed the DEVC='Air mass' to track exh_gas.

I expect the file to run, instead I get "access violation"
see below:
-----------------------------------------------------------------
Starting FDS ...

 MPI Process      0 started 
 Reading FDS input file ...

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds.exe            00007FF6AE72B1A8  Unknown               Unknown  Unknown
fds.exe            00007FF6AE72CA9D  Unknown               Unknown  Unknown
fds.exe            00007FF6AE72DE39  Unknown               Unknown  Unknown
fds.exe            00007FF6B571F5A3  Unknown               Unknown  Unknown
fds.exe            00007FF6B56D05F1  Unknown               Unknown  Unknown
fds.exe            00007FF6B52BAC4A  Unknown               Unknown  Unknown
fds.exe            00007FF6B52887FE  Unknown               Unknown  Unknown
fds.exe            00007FF6B5C2A8E4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFAE22F74B4  Unknown               Unknown  Unknown
ntdll.dll          00007FFAE2B026A1  Unknown               Unknown  Unknown
Press any key to continue . . .
--------------------------------------------------------------------------

I attached the modified input file. 
[surf_mass_part_specified-1.txt](https://github.com/firemodels/fds/files/10088623/surf_mass_part_specified-1.txt)

**Comment by drjfloyd** [comment]
Something is going wrong with the COPY_LUMPED species. We are in the midst of an overhaul of how species and reactions are initialized. This is working with the current source. As a work around you can define EXH_GAS explicitly using the Lennard-Jones values from the User's Guide (which are used for conductivity, viscosity, and diffusivity) and the MW and a specific heat ramp from a .out file where just the LJ AIR species is present.

&SPEC ID='EXH_GAS', MW=28.85476,RAMP_CP='LJ CP',EPSILONKLJ=78.6,SIGMALJ=3.711,ENTHALPY_OF_FORMATION=0/
&RAMP ID='LJ CP',T=293,F=1.01/
&RAMP ID='LJ CP',T=500,F=1.04/
&RAMP ID='LJ CP',T=1000,F=1.15/
&RAMP ID='LJ CP',T=1500,F=1.22/

**Comment by uporersith** [comment]
Thanks drjfloyd, I also found that in addition to the COPY_LUMPED, If I specified a dummy species (define a SPEC ID, but never use it) it also seems to work. My goal was to try to optimize run times by minimizing the number of tracked species, so I'm not sure if it affects run time doing it this way or your recommended way.

**Comment by drjfloyd** [comment]
If you have defined the dummy species as a tracked (lumped) species (i.e. you did not set LUMPED_COMPONENT_ONLY=T), then FDS will solve a transport equation for it. The cost in going from two to three tracked species will be noticeable but not painfully so. Likely < 10 % increase in run time.

If it does have LUMPED_COMPONENT_ONLY=T, then there will be a very slight increase (as a guess << 1 %)  in run time as there are a few functions that need primitive species data.
