### ISSUE TITLE
Fire extinguishing system with Argon

### ISSUE THREAD

**Issue by BarbaraPitto** [firemodels/fds#11169]
Good morning,
I am trying to simulate with FDS the intervention of a fire extinguishing system that uses Argon.
I modeled some nozzles and used a particle type "Argon", the nozzle has a RAMP to simulate the beginning of the intervention (60s after smoke detection) and its end when the amount of gas provided is over.
I'm currently using twice the amount of Argon determined by the dimensionig of the plant, so I expect the fire to be extinguished, but it doesn't happen: i see the HRR reaching almost zero, but then afterwards the fire starts again. 
The amount of Argon spread in the rooms should have taken out all the oxygen so I can't guess why a fire starts again: furthermore it's not the first solid that burns again but it's a different one in the nearby room.
Can anyone tell me what the problem is or if i'm doing something wrong?
i'm using FDS through a software (Namirial CPI WIN FSE) and the version is 6.7.7
Thank you very much, have a nice day!
[ext Argon.docx](https://github.com/firemodels/fds/files/10111806/ext.Argon.docx)
![HRR](https://user-images.githubusercontent.com/118295085/204496767-71f2e3ac-d0b0-4742-acca-9f2c68328cdb.JPG)

**Comment by drjfloyd** [comment]
This input is injecting liquid droplets of ARGON that must evaporate:

&PART ID = 'Argon',
       AGE=10000.000,
       QUANTITIES='PARTICLE AGE',
       SPEC_ID = 'ARGON',
       DIAMETER=500.000,
       MONODISPERSE=.TRUE./

I expect the real world system going to be tanks of compressed gas. Rather than a nozzle injecting liquid particles, put STATIC particles in with a SURF_ID that injects ARGON. Look at the isentropic verification inputs in the Example\Pressure_Effects folder.

When your system operates you close all the openings making a sealed space and the pressure in this sealed space is spiking up to over an atmosphere of pressure which will also result in increased temperature due to pressure work. This means you are not displacing any oxygen, just adding argon. You should provide a relief vent.

Propane with Argon has a minimum extinguishing concentration of 37.5 volume percent or 45 mass percent. If I put in slice files of ARGON, you have regions where the ARGON mass fraction is below 45 percent which will allow for combustion to continue. 

Your two fuel surfaces have RAMPs that emit fuel for 1500 s. Once a fuel surface starts emitting fuel, it will keep following that ramp. The E_COEFFIICENT parameter only applies to sprinkler droplets.

At 364 s you open a vent to the outside. This will let oxygen in. You have no AUTO_IGNITION_TEMPERATURE so any accumulated fuel will be able to ignite and burn.

**Comment by BarbaraPitto** [comment]
Good morning,
thank you for your answer. Yes, in the real world there are going to be tanks of compressed gas.
I modeled a SURF_ID with argon particles, and the system seems to work better. Please note i started modeling a surface of 1 square meter only to be sure of the quantity, clearly it is not a good simulation of the reality.
The vent that opened at 364s is a window, i assigned to each window a device to measure temperature in order to simulate the glass breaking. 
In the new model the action of Argon works better and the temperatures are not high enough to break the glasses.
I attach the new model "ext Argon 2".

As you correctly suggest, after the injection of Argon we have to provide a relief vent. In order to do so I modeled a SURF_ID that makes the air extraction, with a calculed volume flow, and some openings in the ceiling that simulate the air vent that compensate the air extraction.
This model stops for numerical instability at 278s precisely in the moment when the relief vent starts its action.
I attach te model named "ext Argon+VENT"

The numerical instability already happened in previous simulations, i thought that using SURF_ID instead of nozzle would have improved the stability. I also thought it was due to the version I was using (before that i used a 6.4)
It happens also if in the model, instead of putting SURF and openings to simulate the vent, i open the existing windows. 
The instability always happens when, after the end of the Argon injection, something changes in the amount of oxygen or air.

Do you have any suggestion? Is there something i should model better?

Many thanks, have a nice day!

[ext Argon 2.docx](https://github.com/firemodels/fds/files/10140794/ext.Argon.2.docx)
[ext Argon+VENT.docx](https://github.com/firemodels/fds/files/10140827/ext.Argon%2BVENT.docx)

**Comment by drjfloyd** [comment]
Then once you have implemented a reasonable amount of leakage you should monitor the pressure. At ~0.25 - 0.5 psi of over pressure you start to blow out windows and at ~1-2 psi you will start to damage structure. Pressure relief needs to be present before the discharge. One thing you should do is add leakage to your model. Reasonable leakage for the building may be enough to limit the pressure rise. If not then you may need to add a pressure relief vent. (A vent that operates based on pressure). 

Why have you set LIMITING_DT_RATIO=0.01?  This is 100 times the default value and is probably too high. FDS adjusts the timestep to maintain stability and if it can't reduce it below this limit it will stop.

**Comment by BarbaraPitto** [comment]
Good morning and thank you for the hints
i honestly don't know what happened to LIMITING_DT_RATIO, I set it to the default value and the model stability increased
we are now trying to run models with a reasonable leakage and at the same time designing the air extraction
in order to do so we are calculating on a denser grid so it takes longer to run the model
I will inform you if there are interesting news
thank you again, have a nice day

**Comment by BarbaraPitto** [comment]
Good morning,

we added a leak in the structure (an opening in the lower part of one of the walls) and we are now using a denser calculation mesh. the model stability has surely improved.
in this simulation the air and smoke extraction activates 5 minutes after the end of Argon injection. During this time we see that temperatures have decreased and there is no heat release in the system, i think we can assume that the fire is over.
when the air extraction (modeled with a SURF_ID) activates we notice an increase in HRR and an increase in temperatures. 
the simulation is still running so i can't tell if it's a temporary "peak" and temperatures will decrease afterwards or if there's still something we can model better.

Thanks again, have a nice day!
[ext Argon+Vent.2.docx](https://github.com/firemodels/fds/files/10393164/ext.Argon%2BVent.2.docx)

**Comment by drjfloyd** [comment]
See my first response: "At 364 s you open a vent to the outside. This will let oxygen in. You have no AUTO_IGNITION_TEMPERATURE so any accumulated fuel will be able to ignite and burn."

You still have no AUTO_IGNITION_TEMPERATURE, so the moment you start pulling in ambient air it will let the fuel burn once the local O2 and T pass the extinction test.

At this point I do not see that any bug exists in FDS and I am closing this as an issue. Futher discussion should be in the discussion forum
