### ISSUE TITLE
FDS5.5.3 does not work

### ISSUE THREAD

**Issue by xun21** [firemodels/fds#11171]
hi!
I installed FDS5.5.3 on the win10 64 bit computer and added environment variables to the computer, but I still cannot run this version. 
DOS window will pop up: 'fds5' is not an internal or external command, nor is it a runnable program or batch file.
How can I solve this problem? thank you！！！

**Comment by mcgratta** [comment]
We do not support this old version. It is over 10 years old.

**Comment by xun21** [comment]
Sir, if I want to run the FDS 5.5.3 version, what should I do? Please let me know.thank u

**Comment by gforney** [comment]
as with any program you want to run on your PC make sure the directory this program is in your PATH variable .  type echo %PATH% you should see the fds bin directory.  also reboot your PC.  sometimes a reboot is necessary for the PATH variable to be updated.  sorry but other than that we can't support a program that is over 10 years old

**Comment by gforney** [comment]
you could also copy the fds executable into the directory containing your input file
