### ISSUE TITLE
combustion model

### ISSUE THREAD

**Issue by nadir0707** [firemodels/fds#11172]
hello everyone
I have a question about the combustion model used by default, it was stated in the technical reference guide FDS 6.7.6, that FDS uses EDC when it is a diffusion flame and the kinetics are fast compared with the mixing, where the combustion model is based on the mixing-Limited when its mixed reaction and more complicated (CO and soot formation).
so my question is :
1) the FDS is not based on mixture fraction in the general approach anymore?
2) in my case :

&REAC FUEL                   = 'Epoxy'
      FYI                    = 'C_1 H_1.3 O_0.2, NFPA Handbook, Babrauskas'
      SOOT_YIELD             = 0.01
      CO_YIELD               = 0.25
      C                      = 1
      H                      = 1.3
      O                      = 0.2 /

&SURF ID='fire' , HRRPUA=1800 , RAMP_Q='q1'/

since I imposed (soot and co) then the combustion model used based on mixing-Limited or the EDC since the fuel and the air are not mixed? thank you in advance 
best regards

**Comment by mcgratta** [comment]
This question should be directed to the Discussion Forum. The Issue Tracker is for bug reports.
