### ISSUE TITLE
Initiation issue VCRUNTIME140.dll was not found

### ISSUE THREAD

**Issue by msofranzen** [firemodels/fds#11187]
I'm trying to initiate an fds run from the fds command shell using the fds_local command, but I'm receiving the message "the code execution cannot proceed because VCRUNTIME140.dll was not found."

I'm using the latest FDS version available (6.7.9). This PC is running Windows 10. I've tried reinstalling the program, but no luck. I've used this method before on previous versions with success. Is there something I'm doing incorrectly?

![image](https://user-images.githubusercontent.com/119541750/204915818-20562ace-40cb-4573-819b-af6052f26af8.png)
![Capture](https://user-images.githubusercontent.com/119541750/204916833-694cdb16-b608-4b1b-b84b-49c5abc3f17d.PNG)

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/204921175-e8067cdd-e4ec-4400-a714-a8bf7afe088f.png)
That file is in my C:\Windows\System32 folder. Can you find it?

**Comment by msofranzen** [comment]
I found it elsewhere, but not in system32

![image](https://user-images.githubusercontent.com/119541750/204922743-7ebd6887-4c32-40ab-b595-9ecd81d6225d.png)

**Comment by mcgratta** [comment]
This appears to be a common Windows 10 issue. I saw a number of sites that talked about installing or repairing MS Visual Studio. You could try that.

**Comment by msofranzen** [comment]
Thank you, I will try that

**Comment by msofranzen** [comment]
Reinstalling Visual C++ Redistributable For Visual Studio 2015 fixed the issue. Thank you for your help!

**Comment by mcgratta** [comment]
Thanks for letting us know. I do not think that one needs to install VS, but in your case I do not know another solution.

**Comment by gforney** [comment]
if there is still a problem you can reopen the issue
