### ISSUE TITLE
Input Fire Curve In Pyrosim (FDS)

### ISSUE THREAD

**Issue by nevertrustenvironment** [firemodels/fds#11188]
Hi Everyone!.
Is it possible to input Fire curve in Pyrosim (FDS)?
Such as Cellulosic curve, Hydrocarbon curve, Modified Hydrocarbon curve, RABT ZTV curves and RWS (Rijkswaterstaat) curve?
Thank you in advance!. 
![fire curve](https://user-images.githubusercontent.com/68212891/205007701-37927a21-c13d-44e4-8951-ffc165d7b2b3.JPG)

**Comment by Er9y714** [comment]
I believe this is not an "issue" and should be posted to the discussion forum. https://groups.google.com/g/fds-smv

However, I m sure it must have been asked before. So please do a search before you post. Thanks.

**Comment by drjfloyd** [comment]
Questions on using Pyrosim should be directed to Pyrosim technical support at Thunderhead Engineering. This isssue tracker and the forum does not provide support for Pyrosim. You may also wish to look at the Pyrosim User's Guide.
