### ISSUE TITLE
Error with fds_local in win11

### ISSUE THREAD

**Issue by Factral** [firemodels/fds#11195]
im trying to run this script

```
&HEAD CHID='sample', TITLE='sample' /

&MESH XB=0, 3, 0, 4, 0, 3, IJK= 30, 40, 30 /

&TIME T_END=60. /

&VENT XB= 1, 2, 4, 4, 0, 2, SURF_ID='OPEN' / door
&VENT XB= 3, 3, 2, 3, 1, 2, SURF_ID='OPEN' / window

&REAC FUEL = 'PROPANE'

&OBST XB= 1, 2, 1.5, 2.5, 0, 0.5, COLOR='RED', SURF_ID='fire1' /

&SURF ID='fire1', HRRPUA=250 /

&DEVC ID='T air 1', XYZ=1, 2, 2.8, QUANTITY='TEMPERATURE' /
&SLCF PBY = 2, QUANTITY='TEMPERATURE'/

&TAIL /
```

but i get this

![imagen](https://user-images.githubusercontent.com/74687828/205461025-4c1d0f1d-56a4-46f8-9e62-6a274b29545e.png)

how can i fix?

**Comment by mcgratta** [comment]
Are you running this in the CMDfds prompt?

**Comment by Factral** [comment]
in the installation the CMDfds shortcut was not created

but before that capture I ran fdsinit which is what CMDfds does

![imagen](https://user-images.githubusercontent.com/74687828/205461824-e446a1e5-fceb-4f4e-b067-939997048591.png)

**Comment by Factral** [comment]
fixed installing vc_redist.x64.exe in https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
