### ISSUE TITLE
Invoking two-reaction simple chemistry changes HEAT_OF_COMBUSTION

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#11199]
This is a fairly specific use-case. The issue arrives at step (2):
(1) Start with simple chemistry and a specified fuel composition:
`&REAC  FUEL='FUEL', C=1.0,H=1.700,O=0.45,N=0.05,
CO_YIELD = 0.00,
SOOT_YIELD = 0.100,
/  ! zero CO_YIELD is default
`
FDS automatically adjusts the heat of formation of this fuel to achieve Energy Per Mass O2, EPUMO2=13100 [kJ/kg_O2].
In the example given, this works as follows:
Molecular mass of FUEL = 21.624 [kg_fuel/kmol_fuel]
Heat of combustion = 19708.0 [kJ/kg_fuel]
Stoichiometric ratio O2/fuel = 1.016667 [kmol_O2/kmol_fuel]
hence EPUMO2 = 19708.0 * 21.624 / (1.016667*31.9988) [kJ/kg_O2] = 13100 [kJ/kg_O2].

(2) Change to two-reaction simple chemistry by adding:
`&COMB N_SIMPLE_CHEMISTRY_REACTIONS=2 /
`
The reported Total Heat of Combustion now changes (in FDS6.7.9), to 21867.5 [kJ/kg_fuel]. The molecular mass of FUEL, and the total stoichiometric ratio O2/fuel for the combined reactions are unchanged, so the total EPUMO2 is now around 14535 [kJ/kg_O2].

The issue, as I see it, is that the default EPUMO2 is being applied to the first reaction only (using the partial heat of combustion, and the partial oxygen stoichiometric ratio of reaction1 alone): heat of reaction1 is 10116.39 [kJ/kg_fuel], stoichiometric ratio O2/fuel of reaction1 = 0.521869 [kmol_O2/kmol_fuel]. Extra heat of combustion then arrives from reaction2.

I think the intended/expected behavior is that the default EPUMO2 should apply to the combined reactions, and the total heat of combustion should match the single-reaction result. In the source code, read.f90, SUBROUTINE PROC_REAC_2, inside HOC_IF, the IF(SIMPLE_CHEMISTRY) sections need to be different if N_SIMPLE_CHEMISTRY_REACTIONS==2. The case I've presented is on the ELSE branch of HOC_IF. In the other branch, when the user specifies HEAT_OF_COMBUSTION (rather than HOC_COMPLETE), it is possible no changes are required, because the specified value presumably applies to reaction1 alone.

The current workaround for me is to specify HOC_COMPLETE=19708.0 in the &REAC line.

I've attached some .fds cases and the corresponding .out reports, all with .txt added.
Thanks for your efforts.

[two-reaction.out.txt](https://github.com/firemodels/fds/files/10167020/two-reaction.out.txt)
[one-reaction.fds.txt](https://github.com/firemodels/fds/files/10167021/one-reaction.fds.txt)
[one-reaction.out.txt](https://github.com/firemodels/fds/files/10167022/one-reaction.out.txt)
[two-reaction.fds.txt](https://github.com/firemodels/fds/files/10167023/two-reaction.fds.txt)

**Comment by drjfloyd** [comment]
Your interpretation is correct.  Under well ventilated conditions, the one-step and two-step models should result in the same heat release rate. The same total heat of combustion for one-step and two-step should result when EPUMO2 is used. 

It looks like you have identified a solution for the current release. I can't think of an eaier one.

We recently made a source change to allow for multiple-simple chemistry reactions in the next release which meant reworking PROC_REAC_2. This is working correctly in the current source. Both one and two-step give the same total heat of combustion.

**Comment by obscureed** [comment]
Thanks for your prompt reply. It seems to me that if this is a bug, it's under control: the "wrong" behavior is reported clearly, and is not outlandishly wrong anyway (in the current case, for example); it is not relevant for future versions; and there is a workaround. It is interesting that it does not show up in any verification cases, but maybe the entire matrix of combinations of settings is too large to contemplate full coverage? Anyway, I'll close this now -- thanks again.

**Comment by rmcdermo** [comment]
@obscureed You are correct that this should have a verification case.  I'm going to reopen so make sure this is done before calling this complete.  Thanks

**Comment by drjfloyd** [comment]
Verifcation case was successful in firebot.
