### ISSUE TITLE
Minimum Density Error

### ISSUE THREAD

**Issue by Fahad1710124** [firemodels/fds#11197]
Hi, 
I am running a 20 dwelling fire spread simulation with wind speed 5.6 m/s at 70°. I tried to run the simulation twice and it crashed showing a numerical instability warning. I have simulated the same fire spread experiment with 2 and 4 dwellings successfully. But the 20 dwellings model started showing the minimum density warning after 87s of simulation time. And the simulation finally stopped after 96.05s displaying the following error message: 
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
 Time Step:  40000, Simulation Time:     95.66 s
 Time Step:  40100, Simulation Time:     95.84 s
 Time Step:  40200, Simulation Time:     96.00 s
 Time Step:  40232, Simulation Time:     96.05 s

ERROR: Numerical Instability - FDS stopped (CHID: 25_11_22_20_Shelters_Fire_Spread_2m_Module)
[runfds.exe] subprocess exit: 0
I have attached the FDS input file here.
[25_11_22_20_Shelters_Fire_Spread.txt](https://github.com/firemodels/fds/files/10155651/25_11_22_20_Shelters_Fire_Spread.txt)

**Comment by mcgratta** [comment]
I started this case an hour ago, but it has progressed only a short amount of time. This is a very poor way to assess the effect of wind no structures. There is no volume around the shelters in which the wind would naturally form. In any case, I will run to see if there is an obvious problem. You should rethink what you are doing.

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/206039479-2acf315d-496c-4cb0-970c-7cba70cb38c5.png)
You are imposing a 5.6 m/s wind directly on the side of an enclosure.  I suggest that you provide several 10s of meters around and over the enclosures.  You cannot impose a wind directly on obstructions.
