### ISSUE TITLE
Gas phase DEVC in solid (OBST)

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11202]
This is a bit gray area question. A gas phase device is not intended to work in the solid, so I do not know what it should print when an OBSTruction appears and covers the device. I am reporting this occurrence only for information. On the other hand, it may lead to a simple fix. 

Thank you,

So the example file has two VENTs and an OBSTruction. Both vents have dynamic pressure. When the OBSTruction appears and covers the device, device value prints an incorrect value. 

```

&HEAD CHID='untitled2'/
&TIME T_END=15.0/
&DUMP DT_DEVC=1.0/

&MESH ID='Mesh01', IJK=5,6,6, XB=0.0,0.5,2.2,2.8,0.0,0.6/

&RAMP ID='CTRL_1_RAMP', T=-5.25, F=1.0/
&RAMP ID='CTRL_1_RAMP', T=-4.75, F=-1.0/
&RAMP ID='CTRL_1_RAMP', T=4.75, F=-1.0/
&RAMP ID='CTRL_1_RAMP', T=5.25, F=1.0/
&RAMP ID='CTRL_1_RAMP', T=9.75, F=1.0/
&RAMP ID='CTRL_1_RAMP', T=10.25, F=-1.0/
&CTRL ID='CTRL_1', FUNCTION_TYPE='CUSTOM', RAMP_ID='CTRL_1_RAMP', LATCH=.FALSE., INPUT_ID='TIME'/
&DEVC ID='P', QUANTITY='PRESSURE', XYZ=0.25,2.45,0.3, ORIENTATION=0.0,0.0,1.0/
&DEVC ID='TIME', QUANTITY='TIME', XYZ=0.0,2.2,0.0/
 


&OBST ID='wall', XB=0.0,0.5,2.2,2.6,0.0,0.6, CTRL_ID='CTRL_1'/ 

&VENT ID='OPEN-15Pa', SURF_ID='OPEN', XB=0.0,0.5,2.2,2.2,0,0.604406, IOR=2, DYNAMIC_PRESSURE=-15.0/ 
&VENT ID='OPEN-200Pa', SURF_ID='OPEN', XB=0.0,0.5,2.8,2.8,0,0.604406, DYNAMIC_PRESSURE=-200.0/ 

&SLCF QUANTITY='PRESSURE', PBZ=0.319511/


&TAIL /

```

![image](https://user-images.githubusercontent.com/26166281/206152474-dd55d082-0fc1-4bd0-80da-92b292f69f8e.png)

![image](https://user-images.githubusercontent.com/26166281/206152157-735aa827-58b0-436d-b0b6-2b1041057f52.png)

**Comment by mcgratta** [comment]
The PRESSURE within a solid cell is meaningless because it is not a gas. What do you suggest we do with these devices?

**Comment by Er9y714** [comment]
I agree with you. However I do not have a good suggestion either. If it prints "0" during these invalid periods, "0" is also a value that can be misinterpreted. If it prints "N/A" or a similar text, it may be an issue for plots and postprocessing. 

Printing a meaningless value (+250 Pa) seemed interesting to me and wanted to report for information. 

I will close the issue in that case. Thanks for your response.

**Comment by mcgratta** [comment]
250 Pa is meaningless physically, but it has meaning numerically in that FDS sets the pressure inside the obstruction so as to force the normal component of velocity to be zero at the solid boundary. So we sometimes use these internal pressure values for diagnostic purposes, but they have no meaningful physical interpretation. If we were to "check" for these blocked pressures before print out, that would just cost us CPU time.

**Comment by Er9y714** [comment]
It makes sense. Thanks for sharing the logic behind.

I totally understand the situation. Any "check" is an extra work and will only slow down the calculation.
