### ISSUE TITLE
Problem during a simulation with a large number of sprinklers

### ISSUE THREAD

**Issue by jsterckm** [firemodels/fds#11224]
Dear all,

We are currently facing calculation issues while using sprinklers. Unfortunately, the .fds file cannot be shared, however, here are the main features of our calculation :

-fds version : 6.7.6 (MPI enabled with INTEL 2021.3 and openMP set to 1)
-2 million grid cells over 40 MPI processes
-495 sprinkler devices (almost uniformly distributed in the domain) with 4 different flow rates, triggered at 5 s mark
-Maximum particles = 100 000 (&DUMP)
-Age = 2 (&PART ID)
-Chamber volume of 1 300 m3

There is no fire whatsoever in the room, only the sprinklers activated at 5s. After 450 s of simulation, calculation would shut down with the following message in the .err file :

WARNING Delta TMP_G. Mesh: 38 Particle: 232
WARNING TMP_G_N < TMP_D_N. Mesh: 38 Particle: 232
WARNING Delta TMP_G. Mesh: 33 Particle: 63
WARNING TMP_G_N < TMP_D_N. Mesh: 33 Particle: 63
[rose-smp01:3447848:0:3447848] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x150b81c33140)

Does that pertain to any known fds 6.7.6 issue or does it have to do with our computing cluster ?

Any help would be appreciated.

Kind Regards

**Comment by mcgratta** [comment]
Have you tried running with the latest release? That is the first thing that I would do. It is nearly impossible to diagnose the problem based on what you have written.

**Comment by drjfloyd** [comment]
Can you share the inputs associated with defining the sprinklers (SPEC, PART, and PROP)?

**Comment by jsterckm** [comment]
Thank you for answering. We will get a try with the latest version of the code. Meanwhile, here are the different inputs associated to the sprinklers : 

&SPEC ID='SPRINKLER WATER VAPOR', SPEC_ID='WATER VAPOR'/

&PROP ID = 'Arrosage_2' , FLOW_RATE = 2.2 , OFFSET = 0.1 , PARTICLE_VELOCITY = 10 , SPRAY_ANGLE = 0. , 90. , PART_ID = 'water_drops_400' /
&PROP ID = 'Arrosage_16' , FLOW_RATE = 16 , OFFSET = 0.1 , PARTICLE_VELOCITY = 10 , SPRAY_ANGLE = 0. , 90. , PART_ID = 'water_drops_400' /
&PROP ID = 'Arrosage_20' , FLOW_RATE = 20 , OFFSET = 0.1 , PARTICLE_VELOCITY = 10 , SPRAY_ANGLE = 0. , 90. , PART_ID = 'water_drops_400' /
&PROP ID = 'Arrosage_60' , FLOW_RATE = 60 , OFFSET = 0.1 , PARTICLE_VELOCITY = 10 , SPRAY_ANGLE = 0. , 90. , PART_ID = 'water_drops_400' /

&PART ID = 'water_drops_400' , SPEC_ID = 'SPRINKLER WATER VAPOR' , SAMPLING_FACTOR = 10 , QUANTITIES = 'PARTICLE DIAMETER' , DIAMETER = 400., AGE=2.0 /

**Comment by drjfloyd** [comment]
Thanks for the inputs. What is your grid size? OFFSET=0.1 means FDS is injecting the droplets on the surface of an 0.1 m radius sphere centered on the XYZ of sprinkler. If your grid is larger than the sphere diameter, then all the drops will be injected into one cell which could be an issue. Other than that, I don't notice anything in the sprinkler inputs.

**Comment by jsterckm** [comment]
Our grid size is precisely 0.1m, do you think this can lead to problems? Thank you

**Comment by drjfloyd** [comment]
Grid size and OFFSET probably isn't an issue.  With a grid size of 0.1 m, if the XYZ was in the center of a grid cell (far as possible from a grid boundary), with a 90 degree cone angle you would be placing drops into 17 cells (the eight to the sides and the nine below).

**Comment by mcgratta** [comment]
I suggest that you take your input file and strip out everything except the sprinkler system. Run the case. If the problem persists, send us that input file.

**Comment by mcgratta** [comment]
Has there been any progress on this issue?

**Comment by jsterckm** [comment]
Hello,
We finally successed to end our simulation with the last version of FDS. Thus, we are curious to know if you bring corrections concerning particles between v6.7.6 and v6.7.9 of the code?
Thank you

**Comment by mcgratta** [comment]
There is nothing in the [Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes) that identifies a specific fix, however it is not unusual for some other improvement in algorithms to have unintended consequences, for better or worse. This seems to be for the better. I'll close the issue.
