### ISSUE TITLE
Negative mass fraction problem

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11235]
The following input file:
[complex.txt](https://github.com/firemodels/fds/files/10231970/complex.txt)
produces a negative value of Z, leading to a negative value of T and a seg fault.

**Comment by rmcdermo** [comment]
I made a modification to the CHECK_MASS_DENSITY routine that tries to address this issue.  At the end of the routine we are trying to absorb any errors into the "most abundant species".  This is usually something like N2 occupying 79% of the composition space.  But in this case there are small densities with several of the species concentrations at equal levels.  The new strategy looks again at which species is most abundant after the initial correction.  If the same spec is still most abundant then our initial stategy was a good one.  If the most abundant species has changed, then it might be a better idea to renormalize the mass fractions, which is what we are trying now.  PR #11237 implements this approach.  The attached test case runs to completion.

**Comment by mcgratta** [comment]
I simplified the correction in PR [#11240](https://github.com/firemodels/fds/pull/11240). We can revert if it causes problems.

**Comment by drjfloyd** [comment]
We had done it that way since in most cases the most adundant is air and if not air then products. By absorbing into one of those we don't create or destroy fuel and avoid issues with people not getting the HRR they input.

**Comment by rmcdermo** [comment]
Kevin,
I do recall this being an issue at some point but we probably were not diligent about trapping it as a verification case.  I worry we are whacking the mole here.  I vote for the way I had it, which uses the most abundant species by default.  Maybe you could get rid of some of the extra clips I was doing to be ultra-safe.  Or maybe there are better ways to code it.

**Comment by mcgratta** [comment]
Looks like firebot has spoken. I will revert

**Comment by mcgratta** [comment]
This iteration checks to see that the largest rho_Z receives the mass deficit and also does not go below zero.

**Comment by rmcdermo** [comment]
Kevin,
I think we still need to chat.  This version omits the case that I trapped where we *do* want to renormalize because there is not a clear "most abundant" species.  I'm sure this will probably pass firebot, but I still would vote for the previous implementation.

**Comment by rmcdermo** [comment]
The problem that I noticed working on the case in this Issue is that we get to the loop where we need to correct `RHO_ZZ(I,J,K,N)`, but at that point all the `RHO_ZZ` are nearly the same, and the sum is enough larger than `RHO` to put
```
RHO_ZZ(I,J,K,N) = RHO(I,J,K) - (SUM(RHO_ZZ(I,J,K,1:N)) - RHO_ZZ(I,J,K,N)) < 0
```

Suppose `RHO=0.01` and `RHO_ZZ = [0.004 0.004 0.004 0.004 0.004]`.  Then we get,
```
RHO_ZZ(I,J,K,N) = RHO(I,J,K) - (SUM(RHO_ZZ(I,J,K,1:N)) - RHO_ZZ(I,J,K,N)) = -0.006
```
But in my mind, the better solution here is renormalize instead of setting one of the components to zero and then renormalizing anyway.  So, I don't see the benefit in setting `RHO_ZZ(I,J,K,N)=0`... it should be set back to its original value.

**Comment by mcgratta** [comment]
I agree, that makes sense. So should we test if RHO_ZZ(N) drops below zero (say using a dummy variable), and if so, renormalize? If the dummy doesn't fall below zero, set RHO_ZZ(N) equal to the dummy variable.

**Comment by rmcdermo** [comment]
I could live with that compromise.  My version catches another subtle problem, but it requires a few more flops for the extra test of the most abundant species.

**Comment by mcgratta** [comment]
I made the change and found some other fat to trim. For cases where no clipping occurs, we were still going through the entire 3D arrays adding zero to each entry. But check it and make sure I haven't let something slip through the cracks. This should save us far more than what we're adding in.

**Comment by rmcdermo** [comment]
I think this should be good.  Nice work.  Thanks.  Let's let firebot chew on it, then close.

**Comment by mcgratta** [comment]
firebot is happy, I'll close.
