### ISSUE TITLE
How I can learn as a beginner fire and smoke simulation

### ISSUE THREAD

**Issue by Zaid7070** [firemodels/fds#11232]
Hello 

I am new to the Fire simulation field, I want to learn how to be a professional in FDS, especially in simulation car park fire, smoke, ventilation, and jet fans.

If anyone can give me advice or sources or keys to help me on my learning trip I will be very thankful. 

I made a model for a fire in a hotel carpark but I don't know why it gave an instability error after many many trials searching also gave the same and after 40 h simulations each trial, I lost hope for it, I didn't ask here or share it because I feel like I have many mistakes so I am not sure if it is worthy by my many mistakes, anyway it is attached if anyone wants to take a look and am very apricates for your time.
[thankyou.zip](https://github.com/firemodels/fds/files/10227743/thankyou.zip)

**Comment by mcgratta** [comment]
Your geometry is unnecessarily complicated. Your mesh is much too large for a single computer and these calculations probably take far too long to run. You have assigned no material properties to anything -- just colors. 

You should greatly simplify the geometry and then run the HVAC system without a fire to ensure that the results are reasonable. You should also split the mesh and run the case using multiple computers. Otherwise, the runs will take too long.

**Comment by Zaid7070** [comment]
Thank you a lot 

I am sorry but it was my first project and my knowledge is very lean in this field and am trying to improve it but I need to know from where or the useful sources.

I will :

1.try to simplify the geometry , (re-drawing the building ).
2. run the HVAC system without a fire/ but I didn't understand why? I mean why when I run without fire it will give me ensurance, what fire effect to let me not sure from my results ? 
3.  I have only one computer but I was trying to let the building mesh very big and only the small meshes for fans, to decrease the running time , but it didn't work because the meshes are not in the same ratio. I was trying for weeks on my first project with many hours but I will try more to make it alive.

Thank you a lot. 
If you can advise me how to be better in this field I will be thankful.

**Comment by drjfloyd** [comment]
Before attempting to use FDS for a real world projects where people's lives will depend upon your knowledege and ability you should first ensure that you have a strong foundation in thermal fluids, fire dyanmics, and fire safety. FDS should not be used as a black box.  Learning FDS takes time. SFPE offers a class in using FDS and various colleges and univerisities also offer coursework.

**Comment by Zaid7070** [comment]
Thank you a lot @drjfloyd 

I will do my best, I Find this field complicated but also enjoyable.

**Comment by mcgratta** [comment]
[carpark_100.txt](https://github.com/firemodels/fds/files/10241238/carpark_100.txt)
I ran your case using 100 meshes in about 4 hours. The input file is attached as a text document. The problem you are having is related to a known bug. Your domain has small empty void spaces that can cause problems. You should download the latest test version of FDS [here](https://github.com/firemodels/fds/wiki/FDS-Test-Bundles)

If you want to run cases like this, you cannot use just one computer. That takes far too long. You should get access to compute cluster.

**Comment by Zaid7070** [comment]
@mcgratta 
@drjfloyd 
Thank you a lot, the problem has been solved  I made an edit on my geometry the Z level of the floor was = 0 while the columns on it started from nearly zero ( example 1*10^-5 m ) so it was a small volume between. 

I hope I will have your professionalism one day at  FDS 

But it had many clouds of smoke and became dark and people died there, I hope I will solve this also, maybe I insert wrong car fire inputs.
