### ISSUE TITLE
possible inconsistency in new HT3D

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11247]
I made a simple case of an 0.8 m x 0.8 m x 0.01 m plate on a 5 cm grid. rho=1000, c=1, and k=1000.  I put an 0.2 m x 0.2 m radiant panel 0.4 m away which give a peak flux of ~5 kW/m2 at the center.  

I ran three variants of the case with CELL_SIZE=0.05, 0.01, and 0.005.  In a full blown 3D model, I would expect that as I reduce cell size that the temperature at the center of the plate should assymptotically increase. Here at 0.05 the center is 56.3, at 0.01 it is 46.3, and at 0.005 it is 60.3. 

I had devices to measure the net flux on the front and back of the plate and the plate enthalpy.  I didn't measure on the side since this is a thin obstruction; however, the total side area side is 3 % the area of the back and cooler overall than the back. The back loss was ~3 % of the front incident so at most the sides are ~0.1 %. 

For the 0.05 case the enthalpy increased 72.85 and the net wall was 72.82 for a difference of 0.03 
For the 0.005 case the values were 72.85 and 72.76 for a difference of 0.09
For the 0.01 case the values were 72.90 and 72.57 for a difference of 0.33.

Not accounting for the sides can't be more than about 0.07 so the 0.01 case error of 0.33 is much more than execpted. The 0.05 and 0.005 cases have an error that appears to be just mostly not including the sides.

![plate_100_p05p005_1000](https://user-images.githubusercontent.com/12799217/208168088-bc5f271a-7e65-4d20-b9b3-4594681ebc65.png)
![plate_100_p05p05_1000](https://user-images.githubusercontent.com/12799217/208168091-ed109a44-8d3d-42cc-a177-51e5c9a0dc13.png)
![plate_100_p05p01_1000](https://user-images.githubusercontent.com/12799217/208168092-3b910f2b-7f79-404b-92ea-e50e3066d06d.png)
[plate_100_p05p01.txt](https://github.com/firemodels/fds/files/10248284/plate_100_p05p01.txt)
[plate_100_p05p005.txt](https://github.com/firemodels/fds/files/10248285/plate_100_p05p005.txt)
[plate_100_p05p05.txt](https://github.com/firemodels/fds/files/10248286/plate_100_p05p05.txt)

**Comment by mcgratta** [comment]
I am coming to the conclusion that varying the grid resolution does not improve accuracy unless the gas phase grid is refined. The reason is this --- say we solve the 1-D equation in the x direction with a really fine nodalization. This fine profile is then averaged over the coarsely noded y and z directions. 

The exception to this rule is where we have a bar of steel coated with insulation and we choose to do the heat transfer in 1-D for the insulation and 3-D for the steel. In that case, we are free to use the traditional 1-D fine, non-uniform noding for the insulation but uniform gas mesh for the steel.

**Comment by drjfloyd** [comment]
If I had a thin plate where I wanted multiple cells in depth on the plate but also use HT3D, can you assign multiple SURF to the OBST? One SURF to the plate faces with a small CELL_SIZE and a second to plate edges with the gas cell CELL_SIZE?

**Comment by mcgratta** [comment]
You can do this, but the coarse edge cell solution wipes out the fine face cell solution. There might be a way to preserve the fine temperature profile, but I have not implemented something like that.

**Comment by mcgratta** [comment]
I've finally had some time to return to this issue. I think I have figured out how to invoke HT3D but still retain a steep gradient of temperature near the surface of an object with relatively low thermal conductivity. I'll test your case.

**Comment by mcgratta** [comment]
I ran these cases again with the latest version of my test branch. The errors are 0.18%, 0.33%, and 0.18% for `CELL_SIZE` of 5 cm, 1 cm, and 5 mm. The 1 cm case is still the worst, but I'm not sure why.

**Comment by mcgratta** [comment]
I reran these cases, and the error in all three is now about 0.4%.
