### ISSUE TITLE
HT3D fails with MPI

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11248]
The attached HT3D case runs on a single process but dies with 4 cores at 3066 of main.f90. If I change the SURF to not be HT3D it runs with 4 cores.

[plate_100_p01p01.txt](https://github.com/firemodels/fds/files/10249091/plate_100_p01p01.txt)

**Comment by mcgratta** [comment]
This case ran successfully for me using 4 MPI processes. Were you  trying to run this with OpenMP; that is, one process and 4 threads? In any event, I have noticed running multiple mesh HT3D cases using one MPI process.

**Comment by drjfloyd** [comment]
First ran compiled in the folder impi_intel_win. It died but there we dont get a specific line number so then compiled in impi_intel_win_dv and it gave the line number 3066 in main.  I'll try a clean build again with the current source and see what happens.

**Comment by drjfloyd** [comment]
Recompiled with
Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000

Still failing at 3066 of main.f90. If I change to a 1D surface, it runs.  

This is what I see:

 Fire Dynamics Simulator

 Current Date     : December 17, 2022  18:11:11
 Revision         : FDS6.7.9-1258-g11bd61a3a-master
 Revision Date    : Sat Dec 17 13:36:54 2022 -0500
 Compiler         : Intel ifort 2021.7.1
 Compilation Date : Sat 12/17/2022  05:59 PM

 MPI Enabled;    Number of MPI Processes:       4
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Windows* OS


 Job TITLE        :
 Job ID string    : plate_100_p01p01

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds_impi_intel_wi  00007FF7A6339BC2  COMP_OPERATORS_mp         581  func.f90
fds_impi_intel_wi  00007FF7A6338D60  MEMORY_FUNCTIONS_        1795  func.f90
fds_impi_intel_wi  00007FF7A633AED9  MEMORY_FUNCTIONS_        1476  func.f90
fds_impi_intel_wi  00007FF7A682399E  FDS_ip_MESH_EXCHA        3066  main.f90
fds_impi_intel_wi  00007FF7A680FFCF  FDS_ip_INITIALIZE        2275  main.f90
fds_impi_intel_wi  00007FF7A67F96DA  MAIN__                    265  main.f90
fds_impi_intel_wi  00007FF7ADB6E84E  Unknown               Unknown  Unknown
fds_impi_intel_wi  00007FF7ADBE1834  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE8E3C74B4  Unknown               Unknown  Unknown
ntdll.dll          00007FFE8E5026A1  Unknown               Unknown  Unknown
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds_impi_intel_wi  00007FF7A6339BC2  COMP_OPERATORS_mp         581  func.f90
fds_impi_intel_wi  00007FF7A6338E41  MEMORY_FUNCTIONS_        1798  func.f90
fds_impi_intel_wi  00007FF7A633AED9  MEMORY_FUNCTIONS_        1476  func.f90
fds_impi_intel_wi  00007FF7A682399E  FDS_ip_MESH_EXCHA        3066  main.f90
fds_impi_intel_wi  00007FF7A680FFCF  FDS_ip_INITIALIZE        2275  main.f90
fds_impi_intel_wi  00007FF7A67F96DA  MAIN__                    265  main.f90
fds_impi_intel_wi  00007FF7ADB6E84E  Unknown               Unknown  Unknown
fds_impi_intel_wi  00007FF7ADBE1834  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE8E3C74B4  Unknown               Unknown  Unknown
ntdll.dll          00007FFE8E5026A1  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
It is not failing for me on burn or blaze. I'll try on Windows.
```

 Starting FDS ...

 MPI Process      0 started on blaze019
 MPI Process      1 started on blaze019
 MPI Process      2 started on blaze019
 MPI Process      3 started on blaze019

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : December 18, 2022  13:28:09
 Revision         : FDS6.7.9-1258-g11bd61a3a-master
 Revision Date    : Sat Dec 17 13:36:54 2022 -0500
 Compiler         : ifort version 2021.7.1
 Compilation Date : Dec 18, 2022 13:22:48

 MPI Enabled;    Number of MPI Processes:       4
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS


 Job TITLE        :
 Job ID string    : plate_100_blaze

 Time Step:      1, Simulation Time:      0.02 s
 Time Step:      2, Simulation Time:      0.03 s
 Time Step:      3, Simulation Time:      0.05 s
 Time Step:      4, Simulation Time:      0.06 s
 Time Step:      5, Simulation Time:      0.08 s
 Time Step:      6, Simulation Time:      0.10 s
```

**Comment by mcgratta** [comment]
OK, I hit it.

**Comment by mcgratta** [comment]
This appears to be a Heisenbug; that is, the location of the error changes when I add print statements. I'm going to work on some other bugs in HT3D and hope I catch this one as well.

**Comment by drjfloyd** [comment]
Case is running now.
