### ISSUE TITLE
Numerical Instability Problem

### ISSUE THREAD

**Issue by Fahad1710124** [firemodels/fds#11253]
I am working on a 20 Dwellings Burning simulation with wind velocity 6 m/s and 180 degree direction. There were 5 rows with 4 shelter in each row. And 4 ignition source was placed in the 1st 4 shelters in the front row. At first the simulation would run for some time and stop giving a minimum density error. I posted about the issue a few days earlier. I extended the mesh boundary so that the wind can develop properly. But still I am unable to complete the simulation. The simulation ran about 75s of simulation time and stopped showing a numerical instability problem. I tried to find the cause and added 3 pressure slices and 1 velocity slice. And I observe that a vortex was created in a shelter in the front row.  I don't know for sure if the vortex is the reason for the numerical instability but after the vortex the simulation gave an error message and stopped. It would be great if anyone can help me find the solution of this problem. 

WARNING: Minimum density,    0.111 kg/m3, clipped in Mesh 4
 Time Step:  12900, Simulation Time:     76.04 s
 Time Step:  13000, Simulation Time:     76.39 s
WARNING: Minimum density,    0.111 kg/m3, clipped in Mesh 4
 Time Step:  13100, Simulation Time:     76.64 s
 Time Step:  13200, Simulation Time:     76.66 s
 Time Step:  13300, Simulation Time:     76.71 s
 Time Step:  13400, Simulation Time:     76.87 s
 Time Step:  13434, Simulation Time:     76.95 s

ERROR: Numerical Instability - FDS stopped (CHID: No_Cladding(extended_bou)17_12_22_20_Shelters_Fire)
[runfds.exe] subprocess exit: 0

![Vortex](https://user-images.githubusercontent.com/119877488/208313729-2f7bd3d4-83da-48a5-ae2b-444ae0f4158d.PNG)

[20 Shelter Burning Model.txt](https://github.com/firemodels/fds/files/10254238/20.Shelter.Burning.Model.txt)

**Comment by Fahad1710124** [comment]
This is a screen record showing the generation of the vortex at the last moment inside the shelter.

**Comment by mcgratta** [comment]
See discussion [here](https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox/FMfcgzGrbcCBBMNbpXqHgzDPKHlKzlKh)
