### ISSUE TITLE
Grid resolution and mesh independence analysis

### ISSUE THREAD

**Issue by tmc8** [firemodels/fds#11269]
There is a statement in FDS USER GUIDE that grid resolution is better to be controlled between 4 and 16. Will that be necessary to carry out mesh independence analysis over 16？Especially smaller mesh/grid leads to numerical instability.
The characteristics diameter of fire is 36m, so if the mesh size less than 2m, the grid resolution will be over 16.
![mmexport1671587401200](https://user-images.githubusercontent.com/117368921/208801543-81c304d7-16d6-441b-8b42-1811570fa2a0.png)

**Comment by drjfloyd** [comment]
Nowhere in the current guide do we make this statement. The current guide states (emphasis added):

"The FDS Validation Guide [5] contains a table of the values of D*=dx used in the simulation of the validation
experiments. The table is near the end of the chapter that describes all the experiments. These values
range over two orders of magnitude and were chosen based on a grid resolution study and the particular
attributes of the given fire scenario. **It would be inappropriate to take any of these values as an “acceptable”
minimum.**"

This is not a bug report and discussions on the proper use of FDS should be done in the forum.
