### ISSUE TITLE
Actions fail with openmpi gnu linux

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11273]
@marcfehling Can you please take a look at this.  I don't understand what is failing.  Thanks

https://github.com/firemodels/fds/actions/runs/3751550068/jobs/6374221472

**Comment by marcfehling** [comment]
The warning I see is this one:
```
../../Source/geom.f90:19078:25:

19078 | SUBROUTINE GET_GEOM_INDEX(GEOM_ID, GEOM_INDEX)
      |                         ^
Error: ‘get_geom_index’ defined but not used [-Werror=unused-function]
f951: all warnings being treated as errors
make: *** [../makefile:135: geom.o] Error 1
```
Looks like you don't use `GET_GEOM_INDEX` anywhere in FDS anymore after your latest patch. So you can safely remove it.

**Comment by rmcdermo** [comment]
Doh!  I did not expand the the error flag to see all the messages.  Thanks

**Comment by rmcdermo** [comment]
OK, seems happy now.  Thanks Marc!
