### ISSUE TITLE
CSV files

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#11284]
If I add sep=, on top of the CSV files with a text editor, I can click the CSV fil (or double click) and it will open excel and all number will be imported in separate cells (Office 365). Without the sep=, the CVS files are read as text strings – so I have to open excel and import the files via Data – From text/CSV – and so on.
Would it be possible to have a line inn FDS – something like this : &EXCEL CVS= ‘sep=,’ so the users can decide if they want the sep=, line on top of the file or not? 
![SEPARATE](https://user-images.githubusercontent.com/40716592/209431976-f4009793-89a7-44e0-a75e-656e5e908249.JPG)

**Comment by mcgratta** [comment]
Will this work:

In Excel, select Options --> Advanced --> Editing Options 

and then uncheck "Use system separators" and replace with your own.

**Comment by fidran** [comment]
I think this is a language issue. I have been able to do this on one computer with an English version of W10.  On those with Norwegian language I have not succeeded – even if I change language to English. If I am the only one struggle with this, I can write a small program that add this line.

**Comment by mcgratta** [comment]
I would prefer that FDS not add this line because when we restart cases it would add to the difficulty of starting the .csv files from the appropriate point. I am going to post a general note to the FDS forum to see if others have a solution to this issue.

**Comment by mcgratta** [comment]
I will close this case. There appear to be several techniques that one can use to solve this problem without having to change the format of the FDS output file.

**Comment by fidran** [comment]
That is ok, I have made a script that add this line to the cvs files. I have spent too much time to figure out a solution in excel/windows10.

 

FinnD

 

Fra: Kevin McGrattan ***@***.***> 
Sendt: mandag 2. januar 2023 17:34
Til: firemodels/fds ***@***.***>
Kopi: fidran ***@***.***>; State change ***@***.***>
Emne: Re: [firemodels/fds] CSV files (Issue #11284)

 

I will close this case. There appear to be several techniques that one can use to solve this problem without having to change the format of the FDS output file.
