### ISSUE TITLE
Installation cases in Verification Guide can cause confusion

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11291]
The yellow highlighted file in the Expected Results File column is generated by a Matlab script. This might be confusing to someone trying to run the installation cases

![image](https://user-images.githubusercontent.com/11333911/210388932-d7c00177-16fa-4b31-9ed7-7d25981e9c19.png)

Also: the file name for the ‘Arrhenius_2order_1step’ also contains an error as well, on GitHub the file is listed as “reactionrate_ Arrhenius_2order_1step_soln.csv”:

**Comment by mcgratta** [comment]
Jason -- was there a particular reason for choosing this case? If not, I suggest we remove it and only leave cases that do not require one to run Matlab.

**Comment by drjfloyd** [comment]
Nuclear quality assurance requires verification for software installation to make sure that all libraries are properly installed and that the code functions correctly on a specific computer (this second goes back to the days of mainframes where there could be differences in floating point operations and memory usage (COMMON BLOCK issues) where results might not be the quite the same between mainframes). An aspect of ensuring the code is functioning properly is that the test suite should have good coverage of the software. The two cases are there to test the two primary paths through the combustion routine (fast chemistry and Arrhenius chemistry).

**Comment by mcgratta** [comment]
Yes, but is this specific case needed? Otherwise, I'd prefer to use cases that do not require running Matlab.

**Comment by drjfloyd** [comment]
The analytic solutions for these cases aren't going to change and the size of the csv files createad by matlab are not any bigger than the matlab scripts being called. We could just commit the analytic solution csv files and get rid of the matlab script. This would save a little time in generating plots.

**Comment by mcgratta** [comment]
I think we want to preserve those matlab scripts in the repo, but I agree we could just commit the results.

**Comment by rmcdermo** [comment]
Agreed.  I like to keep the scripts around for traceability of the "exact" csv files.  Thanks

**Comment by drjfloyd** [comment]
should be fixed. committed files and then just removed EDC_species.m from the verification script but did not delete it.
