### ISSUE TITLE
NSTEPS 0 in radf.txt interface file

### ISSUE THREAD

**Issue by tgernay** [firemodels/fds#11311]
Hello,
I am encountering an issue with FDS 6.7.9 related to the interface file "radf.txt" created with the &RADF command (application is for FDS-SAFIR interface). For an input file attached (below), the number of steps and times are not properly reported in the radf.txt file, it reads:

NSTEPS
   0

TIMES

NP

With previous versions of FDS the same fds input file led to non-zero values for NSTEPS and correctly reported the times in the radft.txt file.

It also seems that the format for the line &DUMP may have changed.
Former versions of FDS accepted: &DUMP T_RADF_BEGIN=0., T_RADF_END=1200., DT_RADF=10.
With FDS 6.7.9 it seems T_RADF_BEGIN and T_RADF_END are not accepted any more. It led to "ERROR: problem with DUMP line"

Thank you very much.
Thomas

Input file
[column.txt](https://github.com/firemodels/fds/files/10374096/column.txt)

**Comment by mcgratta** [comment]
This is a bug. We made all the output timing flags consistent, which broke this one. I'll fix.

**Comment by mcgratta** [comment]
Fixed. I removed T_RADF_BEGIN and T_RADF_END because now you can either do DT_RADF=... or you can specify explicit time points for output.

**Comment by tgernay** [comment]
Thank you so much for the very swift resolution, it is greatly appreciated.
Kind regards
Thomas
