### ISSUE TITLE
Endless loop of WARNING statements from droplet routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11320]
I am running `UL_NFPRF_P-5.fds` and the .err file is growing to hundreds of millions of lines, each one like these:
```
WARNING Delta TMP_G. Mesh: 1 Particle Tag: 2218406
WARNING TMP_G_N < TMP_D_N. Mesh: 1 Particle: 1
WARNING Delta TMP_G. Mesh: 1 Particle Tag: 2218406
WARNING TMP_G_N < TMP_D_N. Mesh: 1 Particle: 1
WARNING Delta TMP_G. Mesh: 1 Particle Tag: 2218406
WARNING TMP_G_N < TMP_D_N. Mesh: 1 Particle: 1
WARNING Delta TMP_G. Mesh: 1 Particle Tag: 2218406
```
It appears to be the same particle in some endless loop. There are 5 cases like this; the other four ran OK (I think) with an earlier version (FDS6.7.9-1300-gbeeb4d8). The latest case is running with FDS6.7.9-1381-g34dcb26. I'm going to dig deeper, but have you done anything lately with particles?

**Comment by drjfloyd** [comment]
I haven't really done anything in the evaporation in a while. 

Both warnings mean that someting is amiss with drop solution and FDS has reduced the subtimestep as far is it is allowed. The Delta TMP_G is that the gas temperature is changing to much over a subtimestep and TMP_G_N is that the new gas tempearture has decreased below the new drop temperature, i.e. we have transferred too much heat from the gas to the drop. 

One thing we could (and probably should) do is only write any of the warnings only once per perticle per call to the evap routine and not every sub timestep.  We could allocate an integer array for all the particles in a mesh at the start and for each warning set a bit in the integer value when we write for a specific particle. Then before writing the warning fora particle check if the bit for that warning has been set.

**Comment by mcgratta** [comment]
I'll certainly do that, but I'd like to figure out how this one rogue particle caused such a fuss. When looking at the .out file, I see that Mesh 1 only sees this one droplet for a brief period. No other droplets enter Mesh 1.

**Comment by drjfloyd** [comment]
Let me know if you see something I need to fix.

Where each WARNING is written you could do

IF (.NOT, BIT(x,MESSAGE_WRITTEN(IP)))  THEN
  WRITE warning message
  CALL SETBIT(x,MESSAGE_WRITTEN(IP))
ENDIF

where x is the number if the warning. Then just allocate and deallocate MESSAGE_WRITTEN (setting to 0 when allocated) as an INTEGER at the start and end of the evap routine.

**Comment by mcgratta** [comment]
I think I'll rerun the case, commenting out the warnings and tracking that particular particle in mesh 1. Mesh 1 is far from the fire and should be relatively cold. Not sure why it would cause trouble.

**Comment by mcgratta** [comment]
I added this printout
```
               ! Update gas temperature

               CALL INTERPOLATE1D_UNIFORM(LBOUND(SS%C_P_L_BAR,1),SS%C_P_L_BAR,TMP_DROP_NEW,H_L)
               H_NEW = H_G_OLD + (H_D_OLD - M_DROP*TMP_DROP_NEW*H_L + Q_CON_WALL + Q_RAD)*WGT
               TMP_G_I = TMP_G
               TMP_G_NEW = TMP_G
               CALL GET_TEMPERATURE(TMP_G_NEW,H_NEW/M_GAS_NEW,ZZ_GET2)
               IF (TMP_G_NEW < 0._EB) THEN
                  DT_SUBSTEP = DT_SUBSTEP * 0.5_EB
                  CYCLE TIME_ITERATION_LOOP
               ENDIF

               ! Limit gas temperature change

if (nm==1) write(0,'(i8,9e12.4)') lp%tag,bc%x,bc%y,bc%z,tmp_g_new-tmpm,tmp_g-tmpm,m_drop,wgt,tmp_drop_new-tmpm,tmp_drop-tmpm
```
and the rogue particle dumps
```
 Time Step:  15000, Simulation Time:    169.26 s
 Time Step:  15100, Simulation Time:    169.98 s
 2218406  0.7459E+01  0.7497E+01  0.8152E+01 -0.1635E+03  0.2936E+02  0.5691E-10  0.6093E+04  0.0000E+00  0.2234E+02
 2218406  0.7459E+01  0.7497E+01  0.8152E+01 -0.2358E+03 -0.1635E+03  0.5691E-10  0.6093E+04  0.0000E+00  0.0000E+00
 2218406  0.7459E+01  0.7497E+01  0.8152E+01 -0.2709E+03 -0.2358E+03  0.5691E-10  0.6093E+04  0.0000E+00  0.0000E+00
```
I should have focused exclusively on 2218406 from the moment of its creation, but it seems from the millions of lines of printout that this droplet generates gas temps (TMP_G_NEW) that are close to absolute zero but just slightly above. Thus, it doesn't get trapped by the `IF (TMP_G_NEW < 0._EB) THEN...` statement. I would think that if the new gas temp goes below absolute zero than something is very wrong and the droplet should be thrown out. Can you think of a reason how the gas temperature could get so low? The droplet is about 50 microns and the weighting factor seems OK. This droplet is all by itself in a relatively cold region of the domain.

**Comment by drjfloyd** [comment]
That does look odd. 50 um is a fairly small droplet. I wonder if we have some kind of SPACING issue with the order of operations for some formula involving droplet mass?

**Comment by mcgratta** [comment]
I'm running the case again, this time printing out that single droplet since its creation. Unfortunately takes about a day, and there's no way to shorten the case and still catch this one-in-a-million droplet.

**Comment by mcgratta** [comment]
I ran the case again to see when the droplet goes off the rails
```
write(0,'(9e12.4)') bc%x,bc%y,bc%z,tmp_g_new-tmpm,tmp_g-tmpm,m_drop,wgt,tmp_drop_new-tmpm,tmp_drop-tmpm

 0.7504E+01  0.7535E+01  0.8161E+01  0.2780E+02  0.2781E+02  0.5756E-10  0.6093E+04  0.2205E+02  0.2212E+02
  0.7494E+01  0.7527E+01  0.8159E+01  0.2861E+02  0.2861E+02  0.5740E-10  0.6093E+04  0.2232E+02  0.2205E+02
  0.7484E+01  0.7519E+01  0.8157E+01  0.2850E+02  0.2850E+02  0.5722E-10  0.6093E+04  0.2240E+02  0.2232E+02
  0.7476E+01  0.7512E+01  0.8156E+01  0.2840E+02  0.2840E+02  0.5706E-10  0.6093E+04  0.2239E+02  0.2240E+02
  0.7468E+01  0.7505E+01  0.8154E+01  0.2831E+02  0.2831E+02  0.5691E-10  0.6093E+04  0.2234E+02  0.2239E+02
  0.7459E+01  0.7497E+01  0.8152E+01 -0.1635E+03  0.2936E+02  0.5691E-10  0.6093E+04  0.0000E+00  0.2234E+02
WARNING Delta TMP_G. Mesh: 1 Particle Tag: 2218406
WARNING TMP_G_N < TMP_D_N. Mesh: 1 Particle: 1
  0.7459E+01  0.7497E+01  0.8152E+01 -0.2358E+03 -0.1635E+03  0.5691E-10  0.6093E+04  0.0000E+00  0.0000E+00
  0.7459E+01  0.7497E+01  0.8152E+01 -0.2709E+03 -0.2358E+03  0.5691E-10  0.6093E+04  0.0000E+00  0.0000E+00
  0.7459E+01  0.7497E+01  0.8152E+01 -0.2712E+03 -0.2591E+03  0.5691E-10  0.6093E+04  0.0000E+00  0.0000E+00
  0.7459E+01  0.7497E+01  0.8152E+01 -0.2705E+03 -0.2591E+03  0.5691E-10  0.6093E+04  0.0000E+00  0.0000E+00
```
This still might not tell us everything, but it looks like TMP_G_NEW goes awry.

**Comment by mcgratta** [comment]
The immediate issue is solved.
