### ISSUE TITLE
REQ1 timed out for MPI Process - Help

### ISSUE THREAD

**Issue by JordanBrown13** [firemodels/fds#11322]
Hi, 

I've been having an ongoing issue with a few of our modelling computers as of lately when running a sprinkler model. The model runs fine up until the sprinklers are activated and an error is thrown on the CMD window. The time of crashing seems to be random but within 100 or so seconds of sprinkler activation. 

The output file has no error message. 

**Could someone explain what this message means?** I can't seem to find any information myself on the subject or lack the knowledge to do so. 

![Sprink-005 Crash Log](https://user-images.githubusercontent.com/122388666/211879283-797cd8b6-f0b2-4961-830a-681edf2b6525.PNG)

Here is the full input parameters. ( it was from a restarted simulation that had the same crash previously)
![Capture](https://user-images.githubusercontent.com/122388666/211879236-5290d50e-9073-4734-882c-57725c29950e.PNG)

Computer Specs: 
- AMD Ryzen 9 7950X 16 core
- 64 GB RAM

Thanks, Jordan.

**Comment by mcgratta** [comment]
Post your input file

**Comment by JordanBrown13** [comment]
Here is the .fds file as a text file. 
-redacted

Thanks

**Comment by mcgratta** [comment]
I am running the case

**Comment by JordanBrown13** [comment]
Thank-you

**Comment by JordanBrown13** [comment]
Do you know what that error message typically means? I am not very familiar with the terminology in the error message

**Comment by mcgratta** [comment]
REQ1 is short for "Request 1" which is a name that FDS gives to an array of data that is passed from one process to another. The time out means that the communication is taking longer than its default of 30 s. This means that the MPI communication is taking too long, probably due to all the droplets.

**Comment by JordanBrown13** [comment]
is there a typical workaround people use? Besides altering the sprinklers I suppose.

**Comment by mcgratta** [comment]
If you have hundreds of thousands of droplets in one mesh, you could assign an AGE to make them leave the domain after a certain amount of time. 

You can use less droplets per sprinkler per second.

You could use more meshes and more MPI processes on a compute cluster. 

You can extend the time FDS waits for before timing out, like MPI_TIMEOUT=1800.

I won't know if any of these work before finishing your case, but these are things to think about.

**Comment by JordanBrown13** [comment]
I see, thank-you for the information

**Comment by JordanBrown13** [comment]
I have been running the case on a more powerful computer without issue.  An AMD Ryzen Threadripper 3970X 32 Core processor and 128 GB RAM. 
So it seems it was a hardware limitation related to the sprinkler particles. The run has gotten far past the point of where it would normally crash on our other modelling computers.
