### ISSUE TITLE
Q_RAD_OUT

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11328]
Set Q_RAD_OUT in wall.f90 either where TMP_FRONT is applied or at the end of 1DHT (for non-internal flux surfaces) instead of radi.f90.

**Comment by mcgratta** [comment]
Would we expect the Q_RAD_OUT computed in radi.f90 to be different than that computed at the end of HT1D? If not, I suggest we leave radi.f90 alone so that we do not mess up non-thermally-thick cases.

**Comment by drjfloyd** [comment]
radi

`Q_RAD_OUT = SIGMA*EMISSIVITY*TMP_F**4 where TMP_F is the value after doing 1DHT.`

wall (Tech Ref Eq. L.8)
`Q_RAD_OUT = SIGMA*EMISSIVITY*(TMP_FRONT_OLD**4 + 2*TMP_FRONT_OLD**3*(TMP_FRONT_NEW-TMP_FRONT_OLD)`

So if E=1, TMP_F_OLD=473, TMP_F_NEW=477 we would have
Q_RAD_OUT wall = 2866
Q_RAD_OUT radi = 2935

**Comment by drjfloyd** [comment]
For non-thermally thick cases we can just update in wall.f90 after we determine TMP_F and not need to compute in radi at all.

**Comment by mcgratta** [comment]
But don't you want the Q_RAD_OUT from wall.f90 to be exactly what is used in the Crank-Nicolson scheme?

**Comment by drjfloyd** [comment]
For thermally thick we update in 1DHT either via the internal flux model or via the crank if there isn't internal flux.
For non thermally thick we update after we get the new TMP_F (i.e., TMP_FRONT and RAMP_T, ADIABATIC, etc.)

**Comment by drjfloyd** [comment]
Firebot passed with the changes, so closing this as done.
