### ISSUE TITLE
Clean up char oxidation verification plots

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11355]
Looks like the end time got changed on these.  Also plot on lower right looks weird, can't distinguish the exact from model result.

<img width="1065" alt="Screen Shot 2023-01-19 at 12 29 21 PM" src="https://user-images.githubusercontent.com/4418497/213517714-79c653d6-1ad2-431f-9a3a-6f444f494f5e.png">

**Comment by mcgratta** [comment]
Should be better. Wait for next firebot to check.

**Comment by rmcdermo** [comment]
Plot bounds look better.  The high surface temperature is concerning.  Would @ericvmueller 's method fix this?

Eric, can you apply your idea to this case and see what happens?  If we get a reasonable temperature, to me that is enough to code up your approach to the main branch.  Thanks

<img width="1087" alt="Screen Shot 2023-01-23 at 10 41 53 AM" src="https://user-images.githubusercontent.com/4418497/214082453-9d885392-9596-4015-bcc0-a7fb0e73e08c.png">

**Comment by ericvmueller** [comment]
Okay, I will take a look.

**Comment by ericvmueller** [comment]
Here's how it looks with the alternative, mass transport based method. It becomes diffusion-controlled and so the reaction takes place at a lower temperature and takes longer to complete. I'm sure there is more work needed to verify the best coefficients, but the temperature at least seems more realistic.

![image](https://user-images.githubusercontent.com/13366803/214146373-71c1a177-eb27-4c3d-be6b-55c85c8454e5.png)

**Comment by mcgratta** [comment]
I agree. I would expect the charring to be slow.

**Comment by gmsafir** [comment]
@ericvmueller : is this more realistic version of lower charOx temperatures already available in recent commits on GIThub?

**Comment by ericvmueller** [comment]
Not yet. It should come after updates related to the enthalpy are merged (#11326) and once we settle on the best way to transition away from the previous model. I will update this issue with relevant commits so you can keep tabs.

**Comment by drjfloyd** [comment]
Need to wrap up tech guide edits for this but I do have code and verification cases. I could push that up now and continue working on the tech guide.

**Comment by gmsafir** [comment]
Possible? That would be wonderful!!!

**Comment by ericvmueller** [comment]
Cleaned-up figures now generated with changes in eadfc5a8081e331cf94a8f567a80044c334bef31.
