### ISSUE TITLE
ERROR: Numerical Instability - FDS stopped (Minimum density clipped)

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#11362]
I have a run with modelling the movement of methane in the presence of wind, and I end up with the following error.

WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
 Time Step:    218, Simulation Time:     22.18 s
ERROR: Numerical Instability - FDS stopped

I am not sure how the density of air or methane falls beyond 0.2 kg/m^3 for the temperature range being used here, and I don't know how to solve this problem. My FDS version is 'FDS6.7.9-0-gec52dee42-release'
[test_fds.txt](https://github.com/firemodels/fds/files/10465670/test_fds.txt)

Any input or help is kindly appreciated

**Comment by rmcdermo** [comment]
Thanks.  We'll take a look.

**Comment by rmcdermo** [comment]
What boundary conditions are you actually trying to apply?  This input file is a sealed domain.  See below.  Is this just a mistake in trying to simplify the case?  Or did you only get the error when your VENTS were not correctly placed on your mesh boundaries?

<img width="2131" alt="Screen Shot 2023-01-23 at 10 21 26 AM" src="https://user-images.githubusercontent.com/4418497/214077994-6051428b-2add-4a63-9c0c-a79cf3c161e7.png">

**Comment by rakyuv** [comment]
Thank you @rmcdermo for your answer. I am simulating the methane emission from a point source open to atmosphere, and so my boundary conditions are periodic in the horizontal direction and open on the top of the simulation, with ground at the bottom. In the file I have attached already, I have the boundary conditions at the domain boundary as :
 
&VENT PBX=0, SURF_ID ='PERIODIC' /
&VENT PBX=11000, SURF_ID ='PERIODIC' /
&VENT PBY=0, SURF_ID ='PERIODIC' /
&VENT PBY=11000, SURF_ID ='PERIODIC' /
&VENT PBZ=2180, SURF_ID ='OPEN' /

&VENT XB=5499,5501,5499,5501,0,0, SURF_ID='METHANE BLOWER' /

I never had any error while placing these vents in the simulation. However I don't understand what you mean by sealed domain. I am under the impression that having a periodic domain extends the boundary to infinity. If having an OPEN boundary condition is what is required for all sides, you could change all the vent to OPEN boundary condition except for the PBZ=0, and run the simulation. You could let me know how to get rid of the error.

Thank you for your help, and I will wait for your answer

**Comment by rmcdermo** [comment]
The VENTS you have placed here do not align with the MESH boundaries.  This is why you see the tan color at the external boundaries in Smokeview.  This is telling you that you have solid walls there.  PERIODIC or OPEN bcs will be invisible.

**Comment by rakyuv** [comment]
I understand what you mean. Yes, I had a larger domain before, and while I ran, I got the 'Minimum density error' at the interior mesh. So I removed the external details of the flow and kept only the interior mesh. I forgot to adjust the boundary condition for the new computational domain, while I had sent it to you. My apologies. 
I have attached the corrected input file. You could run the present version and tell me if you find the same error

[test_fds.txt](https://github.com/firemodels/fds/files/10481471/test_fds.txt)

I will wait for your answer. Thank you @rmcdermo

**Comment by rmcdermo** [comment]
OK, will do, thanks

**Comment by rmcdermo** [comment]
With the latest source, the case ran past the point where yours failed.  You can try the latest bundle [here](https://github.com/firemodels/fds/wiki/FDS-Test-Bundles).  There have been lots of changes in prep for v7 release, so not sure what is helping.  But give this a try and let us know.  Thanks

**Comment by rakyuv** [comment]
Thank you @rmcdermo ! I ran the same and it went without any errors.
