### ISSUE TITLE
Clarify energy_budget_dns plot

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11389]
I wanted to see if we could reduce the time for `energy_budget_dns`.  Here is what the plots look like in the verification guide.  I don't recall adding the plot at the left.  Seems something is amiss with it, the convective and diffusive flows do not show up against the expected.  If this plot were not there, it appears we could shorten the run time to 2 seconds.

<img width="1320" alt="Screen Shot 2023-01-26 at 11 23 01 AM" src="https://user-images.githubusercontent.com/4418497/214891358-094550b1-b899-4a58-97e0-dd7d2e330d77.png">

**Comment by mcgratta** [comment]
I eliminated the left plot. I don't recall doing this, but if I did, I probably would have fixed the black and red points based on the current results only to show that they are opposite and of equal absolute value. The right plot is sufficient to test the case.
