### ISSUE TITLE
Stitching SLCF3D from multiple meshes to a single file

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#11388]
Previously, I did find a way to reading the SLCF3D (.sf format) files using pyfdsTools (https://github.com/johodges/pyfdstools), when I was testing with just 1 mesh. Right now, I have more than different 30 meshes dividing the domain in all three directions differently. I was wondering if someone had some experience with saving the SLCF3D files from different meshes in a single file with all the meshes stitched in the correct order ?

**Comment by rmcdermo** [comment]
@rakyuv Please use the GitHub Issues page only for reporting bugs or feature requests.  All other questions or discussions should be posted to the [FDS Discussion Forum](https://groups.google.com/g/fds-smv?pli=1).
