### ISSUE TITLE
screen drag 2

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11393]
### Discussed in https://github.com/firemodels/fds/discussions/11392

<div type='discussions-op-text'>

<sup>Originally posted by **ShehabGamrah** January 27, 2023</sup>
Hey I have used the fds code for verification case screen_drag_2 and imported into pyrosim and didn't get the values as stated in the csv file.</div>

**Comment by drjfloyd** [comment]
@shehabgamrah

What do you mean by "didn't get the values as stated in the csv file?" Are they very different or just slightly different? The values in the file are from an analytic solution of the pressure drop equation being used for a screen. FDS results will have some numerical error associated with them and some time-variance so out verification test has an error band that it allows (you can see what error is tolerated in the table at the end of the FDS Verification Guide). As long as your values are within that tolerance, then there is no issue.

If your values are very far off, then we need to determine if this is a FDS issue or a Pyrosim issue. I suspect it might be an error in Pyrosim parsing the input file as this case has reliably passed our nightly verification testing for quite some time now. When you run FDS through Pyrosim, Pyrosim writes a new .fds file. If you compare the two files the should be the same (other than Pyrosim may write numbers to a different precision or write inputs in a different order).  

If you look at the two files and they appear to be the same, attach the Pyrosim .fds file to this issue and also indicate what version of fds you are using.

**Comment by ShehabGamrah** [comment]
Oh the values were close to the csv file the difference was 1pa. I thought the values used were of a cfd simulation not an analytical solution. One question. If you wanted to use this screen model to a car park case where there is a louvre with a free area of 50%. would this screen model be an accurate representation of the louvre with blocked free area, and does the thickness and cloud particle dimensions have an impact on the solution
Thanks.

**Comment by drjfloyd** [comment]
The screen drag equations are meant for window screens. You can with some effort get the screen drag inputs to give a similar pressure drop to a louver, but in most I woud not model a louvre with particles.

If the louver is mechanical exhaust where you are not modeling the entire exhaust system, then you can just use a VENT with the exhaust flow rate. If the louver is passive or you are modeling the entire exhaust system, then I'd use HVAC. Here you would make an HVAC VENT that is the actual area of the louver. For a passive louver (just an opening in a wall) you would set the duct AREA to the louver free area. The flow loss due to the louver can be assigned to either the HVAC node for the louver or the duct. For a large, passive louver (like a large floor-to-ceiling opening) I might assign multiple VENTs to the area to allow for the possilbility of bi-directional flow.  

Since this isn't an actual bug, I will close the issue. For further discussion, if needed, on modeing louvers please use the discussion forum (https://groups.google.com/g/fds-smv).

**Comment by Er9y714** [comment]
> The screen drag equations are meant for window screens. You can with some effort get the screen drag inputs to give a similar pressure drop to a louver, but in most I woud not model a louvre with particles.
> 
> If the louver is mechanical exhaust where you are not modeling the entire exhaust system, then you can just use a VENT with the exhaust flow rate. If the louver is passive or you are modeling the entire exhaust system, then I'd use HVAC. Here you would make an HVAC VENT that is the actual area of the louver. For a passive louver (just an opening in a wall) you would set the duct AREA to the louver free area. The flow loss due to the louver can be assigned to either the HVAC node for the louver or the duct. For a large, passive louver (like a large floor-to-ceiling opening) I might assign multiple VENTs to the area to allow for the possilbility of bi-directional flow.
> 
> Since this isn't an actual bug, I will close the issue. For further discussion, if needed, on modeing louvers please use the discussion forum (https://groups.google.com/g/fds-smv).

For a very large ceiling opening (e.g. 400+ m2) I find modelling an &INIT region with particles is simpler than applying thousands of VENTs. In terms of accuracy of CFD calculation, would you still recommend using HVAC solution (with VENTs) for large surfaces?


Thanks.

**Comment by drjfloyd** [comment]
The particles don't form a solid surface.  Heat and mass still diffuse through in the gas phase.  If you have a ceiling where a fraction of it is perforated panels such that flow velocities by the mechanical system are large compared to at ceiling velocities, then this effect should not be large. The only case we have that uses particles this way is in the FM datacenter cases where only some of the ceiling had perforated tiles and air change rates were ~100 ACH.   If you have a large ceiling where the entire ceiling is perforated and velocities through the perforation are low, I don't know that the particles and screen drag will give as good an approximation of the flow as HVAC would.

**Comment by Er9y714** [comment]
I understand. My example was actually a large hall and there are louvres on the roof as a smoke extraction vents (natual ventilation). Due to high smoke temperature at the roof level (60 C at 14 m high) velocities reach to 1 m/s. At a small scale fds model I get correct pressure difference at given drag settings (analytical equation of drag in user guide) . 

In fds v6.7.8 i had to reduce the cfl_particle to 0.4 to get correct pressure drop whereas v6.7.9 default settings is working correctly already. 

All in all, it seems to work well for my case. But I will keep in mind about warning for low velocities. 
Thank you.
