### ISSUE TITLE
TAU_Q definition issue

### ISSUE THREAD

**Issue by ellon-b** [firemodels/fds#11424]
In the User Guide, section 13.1 "Time-Dependent Functions", it is defined:

> The parameters TAU_Q, TAU_T, and TAU_V indicate that the heat release rate (HRRPUA); surface temperature (TMP_FRONT); and/or normal velocity (VEL, VOLUME_FLOW), or MASS_FLUX_TOTAL are to ramp up to their prescribed values in TAU seconds and remain
there.

However, the $Q_0 \cdot tanh(\frac{t}{\tau})$ will be $0.76159 \cdot Q_0$ when $t=\tau$. I verified this also when inspecting the MLR_FUEL of a SURF where HRRPUA is applied. Since the $tanh$ function asymptotically approaches 1, I believe it should use a larger value, maybe $Q_0 \cdot tanh(\frac{3\cdot t}{\tau})$. Can you see if this make sense?
Thank you.

**Comment by mcgratta** [comment]
We should say something like "... are to ramp up to their prescribed values in approximately TAU seconds ..."

**Comment by drjfloyd** [comment]
IF TAU is negative it isn't approximate, we do ramp up in TAU seconds,.  Maybe just delete that phrase as we give the formulas.

**Comment by mcgratta** [comment]
Hopefully this clarifies things.

**Comment by ellon-b** [comment]
I don't see a reason to keep the difference of 24% in time and call it approximate. In my view it hides something that can be easily more consistent to the t-squared case. This can avoid confusion when verifying results, which was my case. In any case, if you remove the sentence "ramp up in TAU seconds" everywhere and then just reference the equations would be more clear.
