### ISSUE TITLE
Possibly broken MLR output with AREA_MULTIPLIER.

### ISSUE THREAD

**Issue by tstopi** [firemodels/fds#11422]
It seems that if a surface has AREA_MULTIPLIER>1 , the MLR output in _hrr.csv file is too high by a factor of AREA_MULTIPLIER, i.e. the area multiplier gets applied twice. This pertains to ads version 6.7.9, but appears with the latest source code also.

The following version of the box_burn_away1 demonstrates this  issue. Applying AREA_MULTIPLIER =2 to the SURF_LINE increases the MLR_METHANE output by a factor of 4. 

&HEAD CHID='box_burn_away1_area_multiplier', TITLE='Test BURN_AWAY feature' / 

The FOAM box is evaporated away by the high thermal radiation
from HOT surfaces. The mass of the box is 0.4^3 m3 * 20 kg/m3 = 1.28 kg.
This should be compared to the final value of fuel density volume integral, 
computed by the first DEVC.

```
&MESH IJK=10,10,10 XB=-0.3,0.7,-0.4,0.6,0.0,1.0, MULT_ID='mesh' /
&MULT ID='mesh', DX=1.0, DY=1.0, I_UPPER=1, J_UPPER=1 /

&TIME T_END=30. DT = 0.01/

&SPEC ID='METHANE' /

&MATL ID                   = 'FOAM'
      HEAT_OF_REACTION     = 800.
      CONDUCTIVITY         = 0.2
      SPECIFIC_HEAT        = 1.0
      DENSITY              = 20.
      NU_SPEC              = 1.
      SPEC_ID              = 'METHANE'
      REFERENCE_TEMPERATURE= 200. /

&SURF ID                   = 'FOAM SLAB'
      COLOR                = 'TOMATO 3'
      MATL_ID              = 'FOAM'
      THICKNESS            = 0.1
      BURN_AWAY            = .TRUE.
      BACKING              = 'EXPOSED' 
      AREA_MULTIPLIER=2/

&OBST XB=0.30,0.70,0.30,0.70,0.30,0.70, SURF_ID='FOAM SLAB', BULK_DENSITY=20. /

&SURF ID='HOT', TMP_FRONT=1100., COLOR='RED' /

&VENT PBX=-0.3, SURF_ID='HOT' /
&VENT PBX= 1.7, SURF_ID='HOT' /
&VENT PBY=-0.4, SURF_ID='HOT' /
&VENT PBY= 1.6, SURF_ID='HOT' /
&VENT PBZ= 0.0, SURF_ID='HOT' /
&VENT PBZ= 1.0, SURF_ID='HOT' /

&BNDF QUANTITY='WALL TEMPERATURE' /
&BNDF QUANTITY='MASS FLUX', SPEC_ID='METHANE' /

&SLCF PBZ=0.5, QUANTITY='TEMPERATURE', CELL_CENTERED=T /
&SLCF PBZ=0.5, QUANTITY='DENSITY', CELL_CENTERED=T /
&SLCF PBZ=0.5, QUANTITY='MASS FRACTION', SPEC_ID='METHANE', CELL_CENTERED=T /

&DEVC XB=-0.3,1.7,-0.4,1.6,0,1, QUANTITY='DENSITY', SPEC_ID='METHANE', STATISTICS='VOLUME INTEGRAL', ID='Mass fuel' /
```

&TAIL /

The  issue seems to be that AREA_ADJUST is applied twice. The offending lines in dump.f90 read. 
! Determine mass loss rate of tracked gas species from solid wall cells

```
WALL_LOOP2: DO IW=1,N_EXTERNAL_WALL_CELLS+N_INTERNAL_WALL_CELLS
   WC => WALL(IW)
   IF (WC%BOUNDARY_TYPE/=SOLID_BOUNDARY) CYCLE WALL_LOOP2
   BC => BOUNDARY_COORD(WC%BC_INDEX)
   ONE_D => BOUNDARY_ONE_D(WC%OD_INDEX)
   AREA_F = ONE_D%AREA
   IF (TWO_D)       AREA_F = AREA_F/DY(BC%JJG)
   IF (CYLINDRICAL) AREA_F = AREA_F*2._EB*PI
   DO N=1,N_TRACKED_SPECIES
      M_DOT(N,NM) = M_DOT(N,NM) + ONE_D%M_DOT_G_PP_ADJUST(N)*AREA_F*ONE_D%AREA_ADJUST
   ENDDO
ENDDO WALL_LOOP2

```

**Comment by mcgratta** [comment]
Randy, in 
[dump..f90, line 9566](https://github.com/firemodels/fds/commit/8c4a5ffdd30ceef7c94cb68d690fb5ac78c9d8d0)
why does  `ONE_D%M_DOT_G_PP_ACTUAL(N)` change to  `ONE_D%M_DOT_G_PP_ADJUST(N)`. It appears that this can lead to double counting.

**Comment by rmcdermo** [comment]
I don't remember off hand.  Change it back and see if firebot complains.

**Comment by mcgratta** [comment]
I removed the AREA_ADJUST from the mass loss rate expression. It should have been factored in already.

**Comment by mcgratta** [comment]
firebot passed, so my change did not break anything. 

Topi -- check that the code now works as you expect. When I run your case, I see twice as much gas produced due to the addition of AREA_MULTIPLIER=2.

**Comment by tstopi** [comment]
The code seems. to behave as expected.  I think this issue can be closed.
