### ISSUE TITLE
Suggestion: Display case title in Command window

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#11433]
As of 6.7.9, FDS only displays "FDS" in the title bar of the Command window when run on Windows, so when running multiple cases in parallel, a case can only be identified by scrolling to the beginning in its command window.
To enable case identification at a quick glance, Windows' Batch script supports the "TITLE" command to define a custom title for a particular window.

Therefore, I suggest adding ```TITLE FDS (%casename%)``` to line 85 or so (above ```%ECHO% mpiexec -localonly [...]```) in bin\fds_local.bat. This sets the window title just before calling mpiexec.exe and will display the path to the case in the Command window title bar.

**Comment by mcgratta** [comment]
OK, we will take a look.

**Comment by gforney** [comment]
good idea.  I set the title to the command line used to run the case. thought extra info would also be useful.  the case name will be at the end of the command line.  this change will show up in our nightly builds next time our vv script, firebot passes

https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing

**Comment by FireResearch-BK** [comment]
Thanks for the feedback.

I assume that the build date is indicated as part of the archive's filename?
(The most recent build as of today dates from February 7th.)

**Comment by drjfloyd** [comment]
Yes that is correct.  We have had a couple of days of not passing firebot (https://pages.nist.gov/fds-smv/firebot_status.html). Not unusual for a code change fixing one thing to wind up breaking something else which is why we have firebot.

**Comment by FireResearch-BK** [comment]
Thanks. I just wanted to make sure that I didn't miss the build.

**Comment by gforney** [comment]
update fds_local should be in nightly bundles now

**Comment by FireResearch-BK** [comment]
Yes, it is and the updated fds_local works. Thank you for the implementation!
