### ISSUE TITLE
renderdoubleonce

### ISSUE THREAD

**Issue by ShehabGamrah** [firemodels/fds#11436]
when I use renderonce in the script the image is saved with correct file name, however with renderdoubleonce I get an automatic file name. smokeview version 6.7.5

**Comment by gforney** [comment]
do you see the same problem with the latest smokeview, 6.7.21 ?

you can install it using following link
https://pages.nist.gov/fds-smv/downloads.html

**Comment by ShehabGamrah** [comment]
thanks, will try with this version

**Comment by gforney** [comment]
I've reproduced the problem with the latest smokeview.  I'll fix it

**Comment by ShehabGamrah** [comment]
Thanks

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by gforney** [comment]
did it fix the problem for you?

**Comment by ShehabGamrah** [comment]
Thanks, yes it fixed it.
