### ISSUE TITLE
lower limit to Nusselt number for particles

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11442]
Looking at the Nusselt number for a particle... it seems to be bound at a lower limit of 2. This works for a sphere but the natural convection models we have for cylinders suggest lower values are possible (Eq. 11.3 in the User's Guide). This simple case demonstrates that. 

I would suggest that maybe we don't use the last argument in the MAX function for particles ...then the cylinder can go as low as the natural convection correlation allows.
https://github.com/firemodels/fds/blob/ed7c962bababaf863d77e8261e1f4da0ef2aa9fd/Source/wall.f90#L3166

Also, unrelated but my calculation of Nu from `CTRL` functions doesn't seem to work because the `QUANTITY` of `CONDUCTIVITY` is giving some strange values ...not the value of `K_G` used in the function above. But maybe I'm not using that output quantity correctly.

[cylinder_particle_convection.txt](https://github.com/firemodels/fds/files/10710991/cylinder_particle_convection.txt)

**Comment by mcgratta** [comment]
OK, use the statement
```
IF (PRESENT(PARTICLE_INDEX_IN)) THEN
   HEAT_TRANSFER_COEFFICIENT = MAX(NUSSELT_FORCED,NUSSELT_FREE)*K_G/CONV_LENGTH 
ELSE
   HEAT_TRANSFER_COEFFICIENT = MAX(NUSSELT_FORCED,NUSSELT_FREE,2._EB*CONV_LENGTH/DN)*K_G/CONV_LENGTH 
ENDIF
```
Be careful, though, because I vaguely recall running into trouble when h was allowed to be zero or very close to it. In other words, that max bound was added for a reason, but I don't recall if it was related to particles.
