### ISSUE TITLE
Different results with identical FDS file? 

### ISSUE THREAD

**Issue by JordanBrown13** [firemodels/fds#11440]
Hi, 
I ran a model on one of our modelling computers and the results were extremely odd. As a test, I ran it on a different computer and the results are completely different and more of what is expected. 

I am wondering how this occurred and if its a potential bug. 
**What could cause this? Hardware related?** Some sort of hiccup happened somewhere... Has anyone had something similar happen? 

The model is very simple. A vent is ejecting hot gas into a tunnel with a ventilation system. 

I have attached a temperature slice picture of the two runs.  First photo is the first run and second is the re-run. These are at the same time step. 
![image](https://user-images.githubusercontent.com/122388666/218163963-3344e9d2-6f44-4e62-ad4d-eae7b58f3b5d.png)
![image](https://user-images.githubusercontent.com/122388666/218163976-1f9ab0a9-8988-4a4d-b6b1-10b806f01b3e.png)

**Comment by marcosvanella** [comment]
I assume you used the same FDS version in the two computers. Look at the mean value of the quantity, not a single snapshot. In turbulence simulations changes in instantaneous solution over long runs will almost inevitably be seen for different systems.

**Comment by JordanBrown13** [comment]
Yes, same FDS versions. 

The vent temperatures between the two throughout the entire run time are completely different. In the first run, the hot gas plume never develops fully as it does in the second. Its almost as if the whole vent is not being used somehow.

**Comment by marcosvanella** [comment]
@JordanBrown13 Post the input file. What hardware and OS do these two machines have?

**Comment by JordanBrown13** [comment]
Computer that had the issue
-AMD Ryzen 9 7950X 16 Core
-64 GB RAM
-Windows 11 Pro

Computer without the issue
-AMD Ryzen threadripper 3970C 32 Core
-128 GB RAM
-Windows 11 Pro

Here is a simplified version of the FDS file. As I cannot share the real one due to an NDA. 
[024-PlumeTest1.txt](https://github.com/firemodels/fds/files/10710377/024-PlumeTest1.txt)

**Comment by marcosvanella** [comment]
Can you run the simple case you posted in both computers and verify you still see the issue? I'll run the case here.
Thanks.

**Comment by JordanBrown13** [comment]
Will do, thanks

**Comment by JordanBrown13** [comment]
Just ran the simplified case for a few seconds of run time on both computers. The temperature slices are much like the photos I posted.  Very different plume temperature.

**Comment by JordanBrown13** [comment]
![image](https://user-images.githubusercontent.com/122388666/218180959-d0ddaf65-6f2f-4a12-8def-3b13e51d6978.png)

This is how it looks for the duration of the run time when I run it on the computer giving me troubles. 

24 seconds of run time

**Comment by marcosvanella** [comment]
I see your exhaust is a 2x2 cell vent: &VENT ID='Vertical Tailpipe Exhaust', SURF_ID='Grinder Exhaust', XB=6.4,6.5,59.9,60.0,3.9,3.9/
At what time did you check your temperature slices? This has run for 2sec here. I'm running this on an intel cluster.
________________________________

**Comment by JordanBrown13** [comment]
![image](https://user-images.githubusercontent.com/122388666/218182091-d8d942da-17f9-4f8f-a774-e71f198ce8c3.png)
This is at 2 seconds run time

**Comment by marcosvanella** [comment]
This is what I see at 1.8 seconds with latest source code FDS-5.7.9-1591. I don't have a snapshot at 2sec. Looks similar.
What version of FDS are you running?

<img width="930" alt="Screen Shot 2023-02-10 at 2 45 07 PM" src="https://user-images.githubusercontent.com/7450069/218184103-5d23ad0f-33d2-4bff-ae50-9a4d6959f3c4.png">

**Comment by JordanBrown13** [comment]
Oh my bad.. It seems I am using FDS version 6.7.5 on one and 6.7.9 on the other. I misread the version earlier. 

This photo is from the computer using 6.7.5 
![image](https://user-images.githubusercontent.com/122388666/218185851-86d1d277-2feb-4d9b-a4c9-1ca8127e9b1d.png)


This is from 6.7.9
![image](https://user-images.githubusercontent.com/122388666/218185904-96572fc2-7b53-42cd-8e33-0fefa9ac206f.png)

**Comment by JordanBrown13** [comment]
A very large difference. Was there some major changes between the two updates?

**Comment by marcosvanella** [comment]
This is where the (green) vent is sitting from the front. It is not symmetric respect to the chimney. Not sure thats what you want, but the effect is a lopsided plume.
<img width="1695" alt="Screen Shot 2023-02-10 at 2 59 05 PM" src="https://user-images.githubusercontent.com/7450069/218186420-1a261a1b-bdce-45b0-bfe6-0d41b6232b31.png">

There have been several changes. See them here https://github.com/firemodels/fds/wiki/FDS-Release-Notes

**Comment by JordanBrown13** [comment]
Yes the chimney obstruction is arbitrary in this case.

**Comment by rmcdermo** [comment]
From [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes), in 6.7.8,

"
The treatment stress and vorticity at external "corner edges" has changed. This change was made to fix issues with specified tangential velocity components applied at vents. This change may result is noticeable differences in the flow field near vent outlets for coarse calculations.
"

With just 2 cells across the chimney, you are likely being affected by this change.

**Comment by JordanBrown13** [comment]
Great thanks for the help. 
This is such a mess lol. I guess I have some re-runs to start.

**Comment by marcosvanella** [comment]
Ok, I'm closing this.
