### ISSUE TITLE
Some meshes gets ignored

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#11452]
Hi,

I am trying to implement a FDS simulation with domain divided into 3x3 meshes (thus 9 meshes in total). However when I try to visualise the meshes, I only see 5 meshes being created. I am not sure what happens to the remaining 4 meshes. 

I am attaching the FDS input file here
[test_fds.txt](https://github.com/firemodels/fds/files/10785189/test_fds.txt)

When I visualise with Smokeview, I get this result
![Capture d’écran 2023-02-20 à 15 17 04](https://user-images.githubusercontent.com/38204789/220131519-dcbe3569-49b1-487a-9e39-57d1d0278874.png)

Could you please tell me where I am going wrong with the meshes ?

Thanks in advance

**Comment by drjfloyd** [comment]
You are missing the / at the end of all the MESH lines.

**Comment by rakyuv** [comment]
Thank you @drjfloyd. My bad
