### ISSUE TITLE
Is the &AGL_SLICE working for quantities other than level set value? (Level set mode 4)

### ISSUE THREAD

**Issue by alfredelhaddad** [firemodels/fds#11453]
I am working with a large terrain level set based simulation. Fire spread is working great according to the &SLCF AGL_SLICE=1. QUANTITY='LEVEL SET VALUE'. But I see many examples including temperature or visibility as other AGL slices while the output of these slices on SMV is always the initial value and constant.

![image](https://user-images.githubusercontent.com/125048092/220140954-82245872-aca2-431b-ac8c-239b42675241.png)

I have searched everywhere for documentation about the level set method in FDS but it is minimal. Does anyone know if it is possible to output terrain temperature or any other quantity?

So that you know, I am working with the OBST exported terrain from QGIS using qgis2fds.

**Comment by mcgratta** [comment]
What level of level set calculation are you doing? There are four options?

**Comment by alfredelhaddad** [comment]
> What level of level set calculation are you doing? There are four options?

I'm using level set 4. Sorry for not including it.

In case it is important info also: I divided the mesh into multiple (16 and 32) and running it with OpenMPI.
Also, I assume this method does not involve any interaction between the fire and atmosphere so regular slices for temperature or visibility shouldn't include any change right?

It would be good to know which outputs I can get from this model. Until now from my research I concluded that only the slice with LEVEL_SET_VALUE is helpful to determine the fire spread. And the 3D soot (smoke) I could also load. But it is weird to find temperature slices with AGL_SLICE in example codes, run it, and find no result. I can upload the input file if needed too, but it's a bit slow to run it all.

**Comment by mcgratta** [comment]
Level 4 means that fuel gas is created and combusted when the level set value increases above zero. So FDS is simulating the actual fire. If you assign the ground thermal properties, it will heat up. You can visualize this with 
```
&BNDF QUANTITY='WALL TEMPERATURE' /
```
However, be warned that the rendering of the fire is very crude, and the ground temperatures may be much less than what you would expect because they are averaged over the very large grid cell.

**Comment by alfredelhaddad** [comment]
Thanks for the swift replies Kevin, I will try adding this line and report back after.

**Comment by alfredelhaddad** [comment]
I still get 32 degrees maximum with both AGL_SLICE for temperature and with the BNDF wall temperature, because my ambient temperature is set to 30 degrees. As you told me the temperatures are averaged, I assume they are averaged over the entire obstacle, so an obstacle that is 100 meters high would surely be colder on most of its volume compared to the surface.

So I tried to project all the mountains to the surface and make the obstacles thinner than the grid, the temperatures are still maximum 32 degrees. Also what about the AGL_SLICE for VISIBILITY?

![image](https://user-images.githubusercontent.com/125048092/220158339-c7d72616-ac41-46a4-99f3-6656f9a2bb22.png)

Is there a working example where AGL_SLICE is used as intended so I can replicate what I need to replicate? For more info, the obstacles are 30 x 30 meters in x and y and of variable heights before I tried to flatten them to 10m height. And my mesh is 30m cubic cell size.

**Comment by mcgratta** [comment]
I think you are misinterpreting the level set concept. With a 30 by 30 m mesh, you cannot expect anything sensible in terms of near surface temperature or visibility. This is meant only for tracking the fire over a large domain. There are no working examples of what you want because we do not think it is appropriate to use these kinds of outputs with level set.

**Comment by alfredelhaddad** [comment]
Thank you for the clarifications.
