### ISSUE TITLE
Insulated cube with fixed pressure 

### ISSUE THREAD

**Issue by mohammedbenali12** [firemodels/fds#11469]
I am modeling a 0.4 MPa fixed pressure insulated bucket, the surface of the bucket is made of stainless steel, the inside of the bucket is filled with air.
My goal is to specify the pressure of the cube and measure the same quantity inside the cube and see how it evolves.
The problem I am having is to define the cube pressure.
Can you help me to solve this [probleme.]

This is my Input:

&HEAD CHID='c1_p_fija', TITLE='cubo aislado a un presion fijo' / 

&MESH IJK=10,10,10, XB=-2.5,2.5,-2.5,2.5,0.0,2.5 / 

&TIME T_END=1200.0 / 
&MISC TMPA =20./

&SPEC ID ='AIR',BACKGROUND = T/ 
&SURF ID='Interior_de_cubo', SPEC_ID='AIR',MASS_FLUX(1)=0.1 /

&MATL ID= 'stainless steel',
      DENSITY=7850.,
      CONDUCTIVITY=48.,
      SPECIFIC_HEAT=0.85
      BACKING='INSULATED'/

&SURF ID ='STEEL',RGB=105,105,105, 
      MATL_ID(1,1)='stainless steel',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.01/

&PROP ID='AI',INITIAL_TEMPERATURE=20.,OPERATING_PRESSURE= 4.0/

&OBST XB = -1.0,1.0,-1.0,1.0, 0.0,1.0,SURF_IDS='STEEL','STEEL','Interior_de_cubo',PROP_ID='AI'/

&DEVC ID='Pres 1', XYZ=0.0,0.0,0.5, QUANTITY='PRESSURE' /
&DEVC ID='Pres 2', XYZ=0.0,0.0,1.0, QUANTITY='PRESSURE' /
&DEVC ID='Pres 3', XYZ=0.0,0.0,1.5, QUANTITY='PRESSURE' /

&SLCF PBY=0.0, QUANTITY='PRESSURE' ,CELL_CENTERED=T/

&TAIL /

**Comment by rmcdermo** [comment]
This should be posted to the [discussion forum](https://groups.google.com/g/fds-smv).  Thanks
