### ISSUE TITLE
Influence of mesh size on temperature

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11470]
### Discussed in https://github.com/firemodels/fds/discussions/11468

<div type='discussions-op-text'>

<sup>Originally posted by **CFDzhou** February 22, 2023</sup>
Wow, did the Google discussion group move here. 

Well, let me talk about a confusing thing I've come across. 
I've recently been using FDS to calculate a 1m diameter pool fire for heptane, mass_flux is 0.067kg/m2*S as measured by someone else's experiment. 

first I used a 2cm grid in order to debug my input file so that the calculation would be a bit faster. I output the temperature along the central axis of the pool and I found that the temperature trend obtained with the 2cm grid matched the experiment well. 

I then set the grid to 1cm for accuracy, referring to the grid size of the FDS validation file. I found that at this point my temperatures were very different from the experimental ones. It is well known that the Mass_flux of the oil pool is very sensitive to the grid and at a 2cm grid the Mass_flux did not reach my preset value. at a 1cm grid , the Mass_flux reached my preset value. However, the results were not as accurate as with the coarse mesh. I then used the 1m methanol pool fire example and found that the temperature trend was the same for the 1cm grid and the 2cm grid, even though the Mass_flux burned differently when it was stable.

I'm curious as to why there is this discrepancy, is there some other factor that affects it?

</div>

**Comment by rmcdermo** [comment]
We need the input files.  If you are not using LES at this level of resolution, I would not expect convergence.

**Comment by drjfloyd** [comment]
This was converted from a discussion, I noted there to add the input files here.

**Comment by drjfloyd** [comment]
Input file from discussion thread attached.  

@CFDzhou: you mentioned the you had run these with 6.3.0. That is now an 8-yr old version of FDS. It is possible this is the problem. Please run with the latest version of FDS and report back if you still have a problem. I looked at the input file. Your domain boundary is only a couple of grid cells away from the edge of the burner. Plume width increases at a rate of ~10 % of the height above the fire. I'd recommend making the domain wider so the plume width is resolved.



[heptane_1m_96_1cm.txt](https://github.com/firemodels/fds/files/10823636/heptane_1m_96_1cm.txt)

**Comment by ZQJ269** [comment]
Thanks for your enlightening comments, I'll give it a try.
