### ISSUE TITLE
Unable to specify custom species with ramped liquid cp

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11488]
I was running through some testing of the condensation features in FDS and noticed an issue in read.f90. The current code base has two checks for whether a user defines SPECIFIC_HEAT_LIQUID. The second check works as expected (either SPECIFIC_HEAT_LIQUID or RAMP_CP_L must be defined). However the first check fails if SPECIFIC_HEAT_LIQUID is not found regardless of whether RAMP_CP_L is defined.

The attached input file demonstrates the issue with a custom water vapor species. Issue is fixed in the linked pull request. https://github.com/firemodels/fds/pull/11487

[wall_cond_h2o_c.txt](https://github.com/firemodels/fds/files/10851415/wall_cond_h2o_c.txt)

**Comment by drjfloyd** [comment]
Thanks Jonathan. I commented on your PR https://github.com/firemodels/fds/pull/11487. Not sure the fix is what we want in all cases (though no doubt it fixes this problem).

**Comment by drjfloyd** [comment]
Fixed. Thanks for helping out Jonathan.
