### ISSUE TITLE
A issue about fds2ascii

### ISSUE THREAD

**Issue by KeepKeepUp** [firemodels/fds#11486]
About fds2ascii.exe ,i want to know the frequecy of getting slcf file after compiling fds.because i want to get the data of average repeatedly , but when i enter the fds2ascii at second time,the data of the slcf file getting by the fds2ascii all change to the zero except the coordinate value.Or is there something wrong with what I'm doing to generate the data

[data102test.txt](https://github.com/firemodels/fds/files/10850650/data102test.txt)

**Comment by rmcdermo** [comment]
This does not demonstrate a bug, which is what the Issue tracker is for.  Please post your question to the discussion forum, but please provide more description of what you are doing and what the problem is.   We need a working example to help.  It is difficult to speculate at what you are doing wrong just from your output.

**Comment by KeepKeepUp** [comment]
this is my demo.  i want to get the mass fraction repeatedly. After following the manual,the data of the file become the zero just like file named‘data102test.txt’ mentioned earlier.
[Uploading methaneleak.txt…]()

**Comment by KeepKeepUp** [comment]
about mass fraction  just like the average value of 10s-12s and 12s-14s ,and so on

**Comment by rmcdermo** [comment]
"After following the manual" does not give me much to go on.  And you still have not uploaded an FDS input file for me to work with.

**Comment by KeepKeepUp** [comment]
i have uploaded an fds input file for you named'methaneleak.txt' mentioned earlier, because the web do not support the '.fds' file type.

**Comment by rmcdermo** [comment]
That is just a link to this thread.  Please try again.

**Comment by KeepKeepUp** [comment]
You mean that i can write multithreaded scripts from fds files to generate data multiple times.

**Comment by KeepKeepUp** [comment]
[methaneleak.md](https://github.com/firemodels/fds/files/10856980/methaneleak.md)

here it is the fds file.

**Comment by KeepKeepUp** [comment]
I'm sorry that the yesterday's file has not been successfully uploaded.

**Comment by KeepKeepUp** [comment]
![trouble](https://user-images.githubusercontent.com/90950584/222049031-4aab4a06-310b-4899-99f8-e024e145295e.png)
when i use fds2ascii,follow the manual to get data124test.txt and data146test.txt , the file named 'data124test.txt' is generated for the first time,and the file named 'data146test.txt'  is generated for the second time. Just like the screenshot named 'trouble.png',   all data in the file named 'data146test.txt'  are changed to the zero except the coordinate value.
