### ISSUE TITLE
ERROR: DEVC QUANTITY HEAT FLUX

### ISSUE THREAD

**Issue by bdjamel** [firemodels/fds#11482]
ERROR: DEVC QUANTITY HEAT FLUX not found (CHID: industrial_fire)

 DEVICE Activation Times

   1  smoke1                                                      No Activation
   2  smoke2                                                      No Activation
   3  smoke3                                                      No Activation
   4  smoke4                                                      No Activation
   5  smoke5                                                      No Activation
   6  heat_1                                                      No Activation
   7  heat_2                                                      No Activation
   8  heat_3                                                      No Activation
   9  heat_4                                                      No Activation
  10  heat_5                                                      No Activation
  11  TM                                                          No Activation
  12  HF                                                          No Activation

ERROR: FDS was improperly set-up - FDS stopped (CHID: industrial_fire)

**Comment by drjfloyd** [comment]
The error message tells you what the problem is. There is no QUANTITY='HEAT FLUX'.  Read the chapter on outputs in the User's Guide and look at the tables of permissible values for QUANTITY.
