### ISSUE TITLE
A issue about fds2ascii

### ISSUE THREAD

**Issue by KeepKeepUp** [firemodels/fds#11494]
I'm sorry to bother you, This question puzzled me for a long time.
Just like the #11486 issue,  i use the fds2ascii to get the slcf data, the same fds file, after compiling,I can only get the time average file once.When I tried to use fds2ascii again to get the second file, everything in the file was zero except the coordinate values.Even though I immediately did a second compilation, trying to compile once to get a second file with time averages, the data in the file was still zero.
So, I would like to ask if there is a problem with the file I wrote (maybe there is a special attribute value setting that I am not aware of to generate slcf average data multiple times) or if fds2ascii only generates a numeric file about time average once in a short time.
Thank you very much and look forward to your answers.

**Comment by rmcdermo** [comment]
I don't really know how to debug fds2ascii cases.  I prefer to use either Matlab or Python scripts to parse the slice files.  Are you handy with either of those? 

https://github.com/firemodels/fds/blob/master/Utilities/Matlab/scripts/slread.m

**Comment by KeepKeepUp** [comment]
You are really patient！Let me look at both of them. Thank you very much for your help.

**Comment by KeepKeepUp** [comment]
> I don't really know how to debug fds2ascii cases. I prefer to use either Matlab or Python scripts to parse the slice files. Are you handy with either of those?
> 
> https://github.com/firemodels/fds/blob/master/Utilities/Matlab/scripts/slread.m

Hello professor, after reading python scripting language parsing, I still do not understand the place, for example,the *args, *kwargs in the function of slread represent what, after browsing the code feeling and the process of parsing data is not  same
 withfds2ascii ; I'd like to know your understanding of parsing slcf data using a scripting language, such as the parsing process.
How to parse the data has puzzled me for a long time.I am looking forward to your reply.

**Comment by rmcdermo** [comment]
Thanks, but I'm not a professor.  The difficulty is that slcf files are binary files.  So, do a google search on "reading binary files with python" and you will have plenty to study.

**Comment by KeepKeepUp** [comment]
thanks!

**Comment by drjfloyd** [comment]
Jonathan Hodges as a git repo with some python tools for reading FDS outputs. I have not use them so I can't answer questions about them but the repo may have what you need or at least help point you in the right direction: https://github.com/johodges/pyfdstools
