### ISSUE TITLE
Char contribution to total HRR

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11497]
Jason, looking at the storage of the char energy release for output in the HRR file: 

https://github.com/firemodels/fds/blob/e52fd3aea57ae7bd2b2fdda09eca8f056ee8a60b/Source/wall.f90#L3009

It seems like the two NU terms should cancel out, so does it make sense to just compute `RHO_DOT*H_R`? The reason I'm asking is that I'm hoping to remove `NU_O2_CHAR` as a redundant input since this value should now be available from `NU_GAS_P`.

Also, in previous versions we had:
`Q_DOT_O2_PPP = Q_DOT_O2_PPP + ...`
I guess the summation would only come into play on the off chance of two oxidation reactions but maybe worth keeping?

**Comment by drjfloyd** [comment]
Good catch that I mistakenly deleted the summation.

NU_GAS_P(O2_INDEX,J) is based on the SPECIES_MIXTUREs.  In these WUI cases, the product SPEC_ID seen on the MATL line is generally not being defined in a manner consistent with the experimental value for NU_O2_CHAR (the measured value impies the char is neither carbon nor the original wood and the approaches to defining pyrolysis generally either use the wood fuel products or carbon dioxide as the ouptut of the char reaction).  This is why before we had references to O2_INDEX or SPECIES_MIXTURE(1) which is AIR. I don't know that we want to get rid of it. This Q_DOT_O2_PPP is used to report out the HRR for char oxidation in the hrr.csv file. Do we have a verification case that tests this? If not we should make one and see if we are getting the correct value or not.

**Comment by ericvmueller** [comment]
But isn't the choice of NU_SPEC on the MATL dictated by the desired mass stoichiometric coefficient for oxygen? So, if not tracking primitive species, a value of NU_SPEC = 7.17 for Air implies NU_GAS_P(O2_INDEX,J) = 1.65. The user shouldn't then specify a number other than 1.65 for NU_O2_CHAR on the MATL line, if they want to be consistent ...so the parameter seems redundant. 

I will take a look at the char_oxidation verification cases and maybe this can be demonstrated with what we already have.

**Comment by drjfloyd** [comment]
The char reaction rate is a function of NU_O2_CHAR.  If this isn't the experimental value, the reaction rate will not be correct. The NU_O2 implied by the SPEC used on MATL are unlikely to be the experimental value as the typical practice in these cases seems to be to either have WOOD PRODUCTS or CARBON DIOXIDE as the produced SPEC_ID on the MATL input and neither of these will be a NU_O2 that matches the experimental value. If you want to allow fds inputs where the MATL reaction and invovled SPEC does not  comport to the experimetnally measured values, then we need to keep NU_O2_CHAR.

               REACTION_RATE = REACTION_RATE * RHO(IIG,JJG,KKG)*Y_O2*(4._EB/LENGTH_SCALE) * &
                               (1._EB+ML%BETA_CHAR(J)*SQRT(RE_L))/(ML%NU_O2_CHAR(J))

For the Q_DOT_O2_PPP, the question is are we getting the correct value in the hrr file? If we are, then we shouldn't change it.

**Comment by ericvmueller** [comment]
I'm still not sure where we are applying different values from those obtained experimentally. What is the justification for using NU_SPEC = 7.17 for Air in our examples if not to match the experimental value of 1.65 for the primitive component of oxygen (in this case, NU_GAS_P(O2_INDEX,J))? Sorry, I might just be being dense.

**Comment by drjfloyd** [comment]
There is a dependence on how you define the MATL reaction. In the input file you refer to, the NUs for the gases were developed to have the same NU_GAS_P(O2_INDEX) as NU_O2_CHAR. But that might not be what happens. If as a user you were to instead focus on the idea that char oxidation is making CO2 -- if the CO2 contains 1 kg of C from the char, then the O2 is 2.67 kg which on a per kg basis of char would make the NU for O2 2.67. In this case we would want to keep the NU_O2_CHAR input so the reaction rate was correct.

**Comment by ericvmueller** [comment]
In this case wouldn't you then specify NU_SPEC = 11.61 for Air and then get the desired value of NU_GAS_P(O2_INDEX,J) = 2.67? Which could then be used in the reaction rate instead of the additional input of NU_O2_CHAR (which is what I'm hoping to do in the model that will replace the one you have referenced).

**Comment by drjfloyd** [comment]
If we want to force user's to define the NU_SPEC such that they get the correct NU_O2_CHAR, then yes. Right now the inputs give the flexiblity for the user to give the correct NU_O2_CHAR on the MATL line but not have to ensure that the NU_SPEC and SPEC_ID gives the same value. We can certainly decide that we ge rid of NU_O2_CHAR and leave it up to users to specify MATL NU_SPEC that give the correct NU_O2_CHAR, but you can be pretty much guaranteed that some users will not do that correctly and we will see issues and discussion threads about why am I not getting the correct reaction rate.

**Comment by drjfloyd** [comment]
Also giving NU_O2_CHAR is what invokes that specific reaction rate model.  If we got rid of this we would need some other input to invoke the reaction rate model.

**Comment by ericvmueller** [comment]
Okay, I think I get what you are saying now. I just wonder if we want to allow this inconsistency - where the reaction rate depends on a certain consumption of oxygen but the actual exchange of species does not need to obey this. Of course, the lumped approach is already bending the truth so I'm not sure where we draw the line.

As far as invocation, this is also part of my proposed change to the reaction rate model. I added a flag to the MATL line which hopefully makes it more obvious that a special model is being used.

**Comment by drjfloyd** [comment]
This is a recurring theme that keeps cropping up in development -- how much do we try to make things easy for users, and how much do we make them do the work to develop inputs? 

If we wanted to get rid of NU_O2_CHAR (and we do like to get rid of redundant inputs), I think we would need a really good example in the guide about how to compute the NU_SPEC by using the O2 mass fraction in AIR as reported in the .out file.

If we don't care about there being a little error in the target NU_O2_CHAR and the actual, we could give the simple rule to set NU_SPEC for AIR to NU_O2_CHAR/0.23  [the approximate O2 mass fraction].  Y_O2_INFTY=0.2323 in dry air and that drops as you add water vapor from HUMIDITY. On a really hot and humid day it could drop close to 0.22, and using 0.23 would mean the actual NU_O2_CHAR would be 1.59 rather than 1.65 (~4 % error).

**Comment by ericvmueller** [comment]
Here's the relevant text in the User Guide ...most of it already exists but I'm tweaking things a bit as I add the description of the 'new' model. If you have edits you can let me know or just modify it once I do a pull request.

![image](https://user-images.githubusercontent.com/13366803/222766778-35fbfe85-0d55-48d0-bbec-e5c311a862bc.png)

**Comment by drjfloyd** [comment]
In 19.3 it can't actually be CO2 on the right hand side if NU_O2_CHAR is 1.65. NU_O2 for C->CO2 is 2.7 (32 g O2 / 12 g C = 2.7 g/g).  Maybe some statement in the text explaining that CO2 is an approximation / surrogate?

**Comment by ericvmueller** [comment]
I think the current form depends on the idea expressed later on:
![image](https://user-images.githubusercontent.com/13366803/222770136-f46b80e9-8fa3-4725-84e0-c0d1f157c106.png)

...that 'char' is not pure C (we can always debate that). But I can add text to say what the values would be for a reaction of pure C were assumed instead.

**Comment by drjfloyd** [comment]
Maybe in the text below 19.1 - 19.3 where we are defining variables we could have an in-text definition for Char that gives the formula in 19.23. This makes it clear early on that char may be more than just carbon.

**Comment by ericvmueller** [comment]
Okay, sounds good - I'll add something

**Comment by ericvmueller** [comment]
Added the clarification to the text and `NU_O2_CHAR` is now removed. So addressing the original topic, the HRR contribution from char oxidation is just stored as `RHO_DOT*H_R`.
