### ISSUE TITLE
Boundary faces not getting computed under compartment floor. 

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#11490]
From Keyvan Naj in google groups.

&HEAD CHID='Tank_v3', TITLE = 'Beispiel' /
&TIME T_END = 642 /
&MISC TMPA = 20 /

&MESH ID='domain1a', IJK=50,40,80,  XB=-0.500,4.500,  -4.000,0.000,  -0.500,7.500/ 10cm cell
&MESH ID='domain1b', IJK=50,40,80,  XB=-0.500,4.500,   0.000,4.000,  -0.500,7.500/
&MESH ID='domain2a', IJK=50,40,80,  XB=4.500,9.5,     -4.000,0.000,  -0.500,7.500/
&MESH ID='domain2b', IJK=50,40,80,  XB=4.500,9.5,      0.000,4.000,  -0.500,7.500/
&MESH ID='domain3a', IJK=50,40,80,  XB=9.5,14.5,      -4.000,0.000,  -0.500,7.500/
&MESH ID='domain3b', IJK=50,40,80,  XB=9.5,14.5,       0.000,4.000,  -0.500,7.500/
&MESH ID='domain4a', IJK=50,40,80,  XB=14.500,19.5,   -4.000,0.000,  -0.500,7.500/
&MESH ID='domain4b', IJK=50,40,80,  XB=14.500,19.5,    0.000,4.000,  -0.500,7.500/
&MESH ID='domain5a', IJK=50,40,80,  XB=19.5,24.5,     -4.000,0.000,  -0.500,7.500/
&MESH ID='domain5b', IJK=50,40,80,  XB=19.5,24.5,      0.000,4.000,  -0.500,7.500/

&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='OPEN' /

&GEOM ID='body', SURF_ID='INERT','OPEN', BINARY_FILE='Cylinder.bingeom' /

HOLE ID='inlet', XB=-0.1100,0.1100,-1.000,1.000,0.500,1.500,  /

&REAC FUEL = 'ETHANOL',
      CO_YIELD = 0.001,
      SOOT_YIELD = 0.008 /

&SURF ID = 'ETHANOL POOL',
      COLOR = 'RED',
      HRRPUA = 405, /
      RAMP_Q = 'ramp' /

&VENT ID='brandflaeche', SURF_ID='ETHANOL POOL', COLOR='RED', XB =12,12.5, -0.2,0.3, 1.5,1.5, /
&MATL ID='ALUMINUM_ALLOY', DENSITY=2690., EMISSIVITY=0.9, CONDUCTIVITY=218., SPECIFIC_HEAT=0.9 /
&SURF ID='aluminum', MATL_ID='ALUMINUM_ALLOY', THICKNESS=0.05, COLOR='SILVER', BACKING='VOID' /
&OBST ID='brandherd', XB= 12,12.5, -0.2,0.3, 1,1.5,  SURF_ID='aluminum' /

&TAIL /

**Comment by drjfloyd** [comment]
Marcos,

I started this case on blaze and it is timestepping now. The fire is now burning inside the tank which seemed to be the issue reported in the forum.

**Comment by marcosvanella** [comment]
Yes, I run this in burn and went all the way to the end. There was a numerical instability for the case before. Thank you Jason, closing.
<img width="916" alt="Screenshot 2023-04-13 at 1 56 31 PM" src="https://user-images.githubusercontent.com/7450069/231844483-6d6305ab-f759-47fc-a33e-81e8b9dd2dbc.png">
