### ISSUE TITLE
Error in summation of NU for MATL

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11502]
In testing this [Douglas Fir validation case](https://github.com/firemodels/fds/blob/master/Validation/NIST_Douglas_Firs/FDS_Input_Files/tree_2_m_49_pc.fds), I get the following:
`ERROR: Sum of NU inputs sum to more than 1 for MATL CHAR (CHID: tree_2_m_49_pc_cat)`

I checked the discrepancy and it is on the order of 9E-16 so maybe the tolerance for this test needs to be relaxed?

**Comment by mcgratta** [comment]
Or perhaps a WARNING. The solid phase NUs sometimes serve as ad hoc models of things we cannot directly model, like spalling or ablation.

**Comment by drjfloyd** [comment]
Spalling or ablation not being modeled is mass that is lost to the ether. FDS accepts that. We just make some assumptions in terms of balancing the kinetics (assume the missing mass has equivalent cp(T) to the virgin MATL). I couldn't think of a use case where one would create mass out of nothing. A tolerance is a good idea, I should have done that.

**Comment by drjfloyd** [comment]
added a tolerance limiting to sum > 1.001.  1 g error out of 1 kg original material won't have any significant impact on enthalpy and I think be easy enough for people to deal with when defining NUs.

**Comment by ericvmueller** [comment]
Looks to be working now - thanks!
