### ISSUE TITLE
SMV - unload slice 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11500]
Hi,

I would like to report a low priority issue with SMV v6.7.21. I hope the steps below are clear. 

Thank you,

Reproducing steps:
1. load all temp slices
![image](https://user-images.githubusercontent.com/26166281/222677666-15549285-da64-4741-bf37-de8515fba17a.png)

Result:
![image](https://user-images.githubusercontent.com/26166281/222677730-b130956f-3896-4021-bde4-8327eb354567.png)

2. unload only Y temp slice
![image](https://user-images.githubusercontent.com/26166281/222677775-32447b8b-542c-426d-9024-62346c58314b.png)

Result: 
No data is visualized.
![image](https://user-images.githubusercontent.com/26166281/222677827-a2743cd4-bc12-437c-9e25-1980226e0c84.png)

 
```

&HEAD CHID='untitled'/
&TIME T_END=10.0/
&DUMP DT_SLCF=5.0/

&MESH ID='Mesh01', IJK=5,5,5, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&SURF ID='hot',
      RGB=255,102,0,
      TMP_FRONT=500.0/

&VENT ID='open', SURF_ID='OPEN', XB=0.0,1.0,1.0,1.0,0.0,1.0/ 
&VENT ID='hot', SURF_ID='hot', XB=0.0,1.0,3.330669E-16,1.0,0.0,0.0/ 

&SLCF QUANTITY='TEMPERATURE', ID='Slice', PBZ=0.5/
&SLCF QUANTITY='TEMPERATURE', ID='Slice01', PBY=0.5/


&TAIL /
```

**Comment by gforney** [comment]
Ill take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by Er9y714** [comment]
Hi Glenn,
Thank you for working on it. I confirm that the issue is resolved. Thank you very much,

I have a question about a visual detail. I see a grid at the cell boundaries. Is this intentional?

![image](https://user-images.githubusercontent.com/26166281/223358236-04dc4c29-4239-4def-ac8b-d590bf7c1be9.png)


![image](https://user-images.githubusercontent.com/26166281/223358298-c887c5b1-4ad0-4fb4-aa56-91fce4d00844.png)

**Comment by gforney** [comment]
assuming this is the problem, a work around until I fix this.

under region, click on solid .  see if outline is checked .  if checked, uncheck.  in smokeview I am running, smokeview is getting confused about what is solid and what is gas

**Comment by Er9y714** [comment]
> assuming this is the problem, a work around until I fix this.
> 
> under region, click on solid . see if outline is checked . if checked, uncheck. in smokeview I am running, smokeview is getting confused about what is solid and what is gas

This worked. Thank you!
![image](https://user-images.githubusercontent.com/26166281/223477564-d7838904-94a3-4a40-a6e3-03f14d98dfa0.png)

**Comment by gforney** [comment]
try smokeview posted at link below.  we are in the middle of changing how we post test bundles.  let me know if you have trouble downloading.  
https://github.com/gforney/night_bundle/releases/tag/TEST_BUNDLES
