### ISSUE TITLE
Remote desktop potentially causing FDS and CMD shell to stop/crash

### ISSUE THREAD

**Issue by JordanBrown13** [firemodels/fds#11508]
I have been having some issues with the FDS command prompt not responding for some time now. As well as models suddenly stopping with no error message in the OUT file. I have brought it up here before, but I have yet to solve my issue. 

First, this seems to occur when logging into a modeling computer via remote desktop. If I start a file on a remote desktop, the CMD window will act as normal. When I remote in to that computer some time later, the CMD window will almost 100% of the time be in a 'not responding' state. 

Secondly, I frequently monitor models which require opening the OUT file and inspecting it (instead of opening smoke view or pyrosim). I was told by an experienced coworker that this may actually be causing the issue as FDS will try to write to the OUT file while it is open therefore, causing a conflict/issue somewhere. 

**Are there documented issues related to FDS 6.7.9, windows 11, and remote desktop? or can opening the OUT file while a model is running cause an issue?** 

Thanks for the help.

**Comment by gforney** [comment]
try copying the .out file to another file then examine the copied file instead

**Comment by JordanBrown13** [comment]
I will copy the OUT file to inspect it from now on incase it causes issue. 

However, I have been able to reproduce the FDS CMD window crash by remoting into the computer with an ongoing FDS simulation. 

I start a simulation on a remote computer, disconnect from the remote connection, then reconnect and the window will go into "Not Responding" with the simulation still running in the background.

**Comment by JordanBrown13** [comment]
CMD crashing issue seems to be fixed from latest Windows update. (FDS 6.7.9)
