### ISSUE TITLE
ERROR: Numerical Instability - FDS stopped

### ISSUE THREAD

**Issue by kihila** [firemodels/fds#11510]
I have so many times error like this, how to fix it? please help cause its important for my final project. thanks!

ERROR RUNNING displayed like this
![image](https://user-images.githubusercontent.com/127167622/223305260-26661385-112f-4151-b40d-fabe29c4ffab.png)

Please advice on how to solve them
[API L0.zip](https://github.com/firemodels/fds/files/10904880/API.L0.zip)
I use PyroSim 2022.3.1208 version
Thank You

**Comment by Er9y714** [comment]
- The file you attached is Pyrosim. You should attach FDS file. 
- Have you checked User guide 4.2 Common Error Statements > Numerical instability. 

There are many obstructions that do not align with the mesh. 
This one especially is overlapping the burner object. You should fix the model and make sure the obstructions align with the mesh.

![image](https://user-images.githubusercontent.com/26166281/223359676-687ad718-a644-421d-a351-b631500ea429.png)

**Comment by kihila** [comment]
I'm so sorry this FDS file 
[MODEL.zip](https://github.com/firemodels/fds/files/10907922/MODEL.zip)

I will try to fix the object and re-run, thank you very much for the advice

**Comment by mcgratta** [comment]
I am running the case now.

**Comment by kihila** [comment]
> 

Thanks for your time, I will wait for the good news.

**Comment by mcgratta** [comment]
The case is running beyond the point of failure with the latest test version of FDS. You can get it [here](https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC). The problem is related to the 10 sealed regions that you have in the domain. We fixed some problems related to these regions a few months ago. Let me know if the new version works. for you.

**Comment by mcgratta** [comment]
I spoke too soon. The case failed for me with the new code. Wait until I figure out what is wrong.

**Comment by mcgratta** [comment]
There are some odd inputs. First, why have you specified a wind
```
&WIND SPEED=1.88, DIRECTION=135.0/
```
but you have only opened the bottom of the domain? By default, FDS assumes that all other boundaries are solid/closed. Even if you want to model a wind, your domain is too small. The wind cannot develop naturally in such a small domain.  

Fix these issues and then let me know if things improve.

**Comment by kihila** [comment]
1. I use wind speed and wind direction from local area data
2.  I will fix the boundaries and let you know the results soon

**Comment by kihila** [comment]
Hello
I'm done with this simulations, some of which i fixed
1. a mass whose shape is not parallel to the mesh
2. the mesh sizes are too different even though it says "pass." And the last one I think is the most careless
3. I reversed defining the mesh that should be open or closed
thanks for the help and suggestions, it means a lot for me.
