### ISSUE TITLE
Error: memory allocation fail

### ISSUE THREAD

**Issue by Csabesz90** [firemodels/fds#11515]
Hi there!
I'm currently trying to run a case which i already completed in an older version with fds (maybe 2 years ago). I made only one change in my current case, i re-distributed the mesh (old - 2770000 cell (25x25 cells and 50x50 cells; current - 2695680 (only 50x50 cells)). I tried in parallel and cluster mode to run the case ended up with the same result, the following: "ERROR: Memory allocation failed for CONNECTED_ZONES in the routine INIT". In my computer i've got 64GB memory. Still can't figure out the problem after many attempts. Can you help me to solve this problem?
Thank you for your answer in advanced.

Kind regards,
Csaba Sallai
fire safety engineer

**Comment by mcgratta** [comment]
I rarely see this error. Can you post your input file.

**Comment by Csabesz90** [comment]
> I rarely see this error. Can you post your input file.

Attached the FDS file below
[PICK__NCS.txt](https://github.com/firemodels/fds/files/10954214/PICK__NCS.txt)

**Comment by mcgratta** [comment]
You have over 100,000 lines of input. My guess is that you computer ran out of RAM, as the message implies. When I run the case with the latest test version, I get errors like this
```
ERROR: AcDbBlockReference - 2FAA1 is embedded within AcDbBlockReference - 1EC61 (MPI Process: 30, CHID: PICK_NCS)
ERROR: AcDbBlockReference - 22CC1F is embedded within AcDbBlockReference - 145DFB (MPI Process:  5, CHID: PICK_NCS)
ERROR: AcDbBlockReference - 22CBE1 is embedded within AcDbBlockReference - 145DBD (MPI Process:  6, CHID: PICK_NCS)
```
These errors are a new "feature" of FDS. It detects when one obstruction is completely embedded within another. There are many errors in your file. We have found that these complicated input files are impossible to debug when people report problems. Often, the geometry is shifted onto the mesh and unexpected problems arise. My suggestion to you is to simplify this case. I cannot imagine why one would need 100,000 lines to describe even a complex fire scenario. At the very least, eliminate redundant obstructions. These are probably obstructions that are very small that blend in with nearby obstructions.
