### ISSUE TITLE
OpenMP disabled

### ISSUE THREAD

**Issue by okiiw** [firemodels/fds#11514]
Why is OpenMP enabled when I run it on my laptop. But Disabled on my personal computer? If I use the command "fds_local -p 1 -o 16 CHID.fds" to force the use of 16 cores, will it work?

**Comment by okiiw** [comment]
sorry I think it must like :"fds_local -p 1 -o 16 file name.fds"

**Comment by mcgratta** [comment]
If you run the fds_local command with the -o option, OpenMP should work. The initial printout on the screen should indicate the number of cores you have asked for. Let me know if that does not work.

**Comment by okiiw** [comment]
Yes, it worked. But it seems that my CPU performance is old and can't reach 100% utilization.

**Comment by mcgratta** [comment]
We generally do not recommend using OpenMP with any more than just a few cores. In your case, you are probably better off splitting the mesh into 16 equally sized sub-meshes and running with MPI.

**Comment by okiiw** [comment]
Ohhh, thank you so much. But use MPI is possible for single computer?

**Comment by mcgratta** [comment]
Yes. If this is a Windows OS, look at the Task Manager:

![image](https://user-images.githubusercontent.com/11333911/224333524-62221341-69e4-40b3-814f-766d062d8703.png)

Look at the number of cores you have. Cores, not hyperthreads or things like that. You should limit your MPI processes to the number of cores you have. Open up the Resource Manager and you'll see something like this

![image](https://user-images.githubusercontent.com/11333911/224334127-c57c5d29-7551-4baa-ab7c-5d1342521cd9.png)

Monitor this while your job runs.

**Comment by okiiw** [comment]
Oh, I see, thank you so much!

**Comment by okiiw** [comment]
Sorry for bother you again, is that using the MPI process, as you mention above, which is sprit to several meshes and type “,MPI_PROCESS=0” (1,2,3….) on the &MESH code?

**Comment by mcgratta** [comment]
I do not understand what you are asking. If the number of meshes is equal to the number of MPI processes that you request with the -p option, you do not need to add MPI_PROCESS to the input file. However, if you have more meshes than you have MPI processes, then you must assign the processes mesh by mesh using MPI_PROCESS.

**Comment by okiiw** [comment]
OK, I will try it. Thanks！
