### ISSUE TITLE
GEOM testing

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#11512]
I have created some 3d objects to test FDS-GEOM, Blender and BlenderFDS. Some cases work other cases give error messages. 
TREX (enclosed) runs if I use Mesh with grid size 50x50x50cm. If I set it to 25x25x25cm it runs into numerical instability after 1.19 sec (nightly bundle from Mars04 and official FDS 6.9.0 release give same results). From the picture Mesh 25x25x25cm you can see that there is a high velocity component on the tail at 1.19s that might cause the problem ? 
Is this an FDS issue, or is it Blender, BlederFDS (or me) ?
[trex.zip](https://github.com/firemodels/fds/files/10909552/trex.zip)

**Comment by rmcdermo** [comment]
Probably and FDS issue.  We are finishing up algorithm changes to handle the complex geometry.  I'll tag this as v7-beta.

**Comment by marcosvanella** [comment]
Hi @fidran, thank you for taking the time to test this feature. I reproduced the issue with latest source. Seems the instability happens in a very small cell or face in the back of the raptor. see pic.
<img width="1308" alt="Screen Shot 2023-03-07 at 10 13 55 AM" src="https://user-images.githubusercontent.com/7450069/223467677-6354424e-1ab0-4131-999c-84172939adb3.png">

When I change the position of the animal in the mesh using a move line:
&GEOM ID='Raptor_LowPoly', SURF_ID='TREX', BINARY_FILE='trex.bingeom', MOVE_ID='MyMOVE' /
&MOVE ID='MyMOVE', DZ=-.1 /
I don't get the instability. This is probably related to momentum transport and similar to another issue #11490 discussed here
[https://groups.google.com/d/msgid/fds-smv/623157d0-171c-4445-8301-ef5b4c81d81cn%40googlegroups.com](https://groups.google.com/d/msgid/fds-smv/623157d0-171c-4445-8301-ef5b4c81d81cn%40googlegroups.com?utm_medium=email&utm_source=footer).

We'll study this further.

**Comment by marcosvanella** [comment]
@fidran the case worked for me with latest source. We should have the latest in a new test bundle **tomorrow** here:  
https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST

**Comment by marcosvanella** [comment]
Closing, reopen if needed.
