### ISSUE TITLE
Installation test - Species - reactionrate_EDC_1step_CH4_nonmix

### ISSUE THREAD

**Issue by pfml** [firemodels/fds#11519]
Trying to run the FDS installation test suite as in table B.1.of FDS Verification Guide.
Got strange results with reactionrate_EDC_1step_CH4_nonmix.fds : compared with https://github.com/firemodels/fds/tree/master/Verification/Species/reactionrate_EDC_1step_CH4_nonmix_spec.csv
it seems the O2 and CH4 columns are switched.

In FDS output, O2 is exhausted, and there is a small excess of CH4. Figure10.8 of the Verification guide is consistent with these results.
In the verification file on GitHub, CH4 is exhausted, and there is some O2 remaining

**Comment by rmcdermo** [comment]
I found something amiss with the header of the "expected" csv file in Species.  Fix committed here PR #11523 

However, something else is odd.  A very recent plot I have from the verification guide looks like this:

<img width="611" alt="Screen Shot 2023-03-10 at 4 53 38 PM" src="https://user-images.githubusercontent.com/4418497/224435841-9029ed98-bb23-4d4f-b2ad-d60e6b7a10be.png">

When I plot this case now, I'm getting the following:

![Screen Shot 2023-03-10 at 4 54 16 PM](https://user-images.githubusercontent.com/4418497/224435920-9ed941db-073c-4861-89a6-c79fb52e8c5f.png)

This second plot is matching the "expected" pretty well.  But the plot above to me looks cleaner... I am not sure what is going on... no time to investigate this now, but will work on it this weekend.

**Comment by rmcdermo** [comment]
Oh, my bad... the second plot is in Fig 10.8 of the recent guide, where the species are not premixed.

**Comment by rmcdermo** [comment]
Actually, also needed to fix the dataplot config file for this, see PR #11524
