### ISSUE TITLE
Particle drag for individual particle classes

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11546]
Following #11545 it is no longer possible to separate the output of drag contributions from different particle types. This can be useful in something like vegetation where we might want to explore the drag of foliage vs branches, etc.

**Comment by mcgratta** [comment]
I restored the LP%ACCEL_X variables and output as before. Check it. Also, look at the User's Guide table listing the particle output and then compare it with the section called "Coloring Particles...". Make sure all particle output is in the table.

**Comment by ericvmueller** [comment]
Yup - looks correct in the guide and the output is the same as it was when re-running a case I had before the change. Thanks!
