### ISSUE TITLE
Warning: Maximum density

### ISSUE THREAD

**Issue by Nitram795** [firemodels/fds#11542]
Hello,
I am a FDS user. The version I use is FDS6.7.7. I need to simulate a hall open on all sides. My fire location is in a very small fire room, which gets more and more openings to the hall over the simulation time. My problem is that FDS always shows a density increase at 590.72 s and then stops the calculation. My MESH limits are open. I can't explain this to myself. I have calculated this fire several times in much more closed geometries. Can you perhaps help me in this regard or am I in the wrong place?

You can find the input file used here. Unfortunately only as ".txt" because no ".fds" file can be uploaded here.

[Position 1.txt](https://github.com/firemodels/fds/files/10977193/Position.1.txt)

**Comment by mcgratta** [comment]
I will run the case.

**Comment by mcgratta** [comment]
You have 228 sealed cavities in your domain. That means that gases can build up inside of one of them and eventually stop the calculation. We have made efforts to fix this and I am running the case with the latest test version. You can try this as well.

**Comment by Nitram795** [comment]
Thank you very much! Is there a quick method to find these cavities or even just close them directly without having to go through the geometry extensively?

**Comment by mcgratta** [comment]
In the test version, there is a parameter called `MINIMUM_ZONE_VOLUME` that fills cavities less than a specified volume. If this number is large, all cavities are filled. The new version also writes this to the .out file. You may want to look carefully at how you have constructed your geometry. A single cell cavity can cause density problems because if its walls pyrolyze, it can fill up with gas with no means of exhaust. There is also some numerical error related to pressure that can cause trouble. The latest version attempts to fix some of these problems, but it is not perfect. It is better to design the geometry to avoid unwanted void spaces.
```
 Pressure Zone Information

   1 Volume: 1.5909E-02 m³, Cells: 1, Mesh: 1, Indices: (28,26,34)
   2 Volume: 3.1818E-02 m³, Cells: 2, Mesh: 2, Indices: (12,35,26)
   3 Volume: 4.7727E-02 m³, Cells: 3, Mesh: 2, Indices: (25,32,29)
   4 Volume: 1.5909E-02 m³, Cells: 1, Mesh: 2, Indices: (20,63,36)
   5 Volume: 1.5909E-02 m³, Cells: 1, Mesh: 2, Indices: (16,16,37)
   6 Volume: 1.4318E-01 m³, Cells: 9, Mesh: 2, Indices: (27,16,37)
   7 Volume: 3.6591E-01 m³, Cells: 23, Mesh: 4, Indices: (10,26,34)
   8 Volume: 3.1818E-02 m³, Cells: 2, Mesh: 3, Indices: (10,74,38)
   9 Volume: 7.9545E-02 m³, Cells: 5, Mesh: 4, Indices: (18,2,18)
   10 Volume: 4.7727E-02 m³, Cells: 3, Mesh: 4, Indices: (18,3,21)
   11 Volume: 4.7727E-02 m³, Cells: 3, Mesh: 4, Indices: (18,43,21)
   12 Volume: 3.1818E-02 m³, Cells: 2, Mesh: 4, Indices: (18,39,22)
   13 Volume: 1.5909E-02 m³, Cells: 1, Mesh: 4, Indices: (18,40,21)
   14 Volume: 1.5909E-02 m³, Cells: 1, Mesh: 4, Indices: (18,4,22)
...
```

**Comment by Nitram795** [comment]
Thank you very much!

**Comment by mcgratta** [comment]
Your case is still running for me with the latest test version of FDS. It is at 1337 s. Try the [new version](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST) and let me know if it works for you.

**Comment by mcgratta** [comment]
The case ran 5700 s and then ended with a numerical instability. There appear to be problems where there are small void spaces. Either fill them in, or tell FDS to ignore them (`NO_PRESSURE_ZONES=T` on the `MISC` line).

**Comment by mcgratta** [comment]
I just noticed something else in your input file. `ADIABATIC=T`. Do not use this boundary condition. It is meant for diagnostic tests, not actual cases. No surface is truly adiabatic, and this assumption can lead to many different kinds of numerical issues.
