### ISSUE TITLE
Explain scatterplots for Theobald Hose Streams

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11566]
The scatterplots for Theobald Hose Streams could use an explanation about the size of the dots and definition of range, height, etc.

**Comment by rmcdermo** [comment]
I added a bit more explanation.  See if you think it is enough.  The key table of parameters is [here](https://github.com/firemodels/exp/blob/master/Theobald_Hose_Stream/theobald_effect_1981_fds.csv) in the exp repo.  This was put together by Trettel back a long time ago and I am admittedly not very familiar with all of it.

**Comment by mcgratta** [comment]
Seems OK. I made a few edits. Thanks
