### ISSUE TITLE
FDS / WARNING: Maximum density,    2.663 kg/m3, clipped in Mesh 1

### ISSUE THREAD

**Issue by Soomin0101** [firemodels/fds#11570]
Dear developers,

I’m encountering an issue in FDS version 6.7.9 

I made an fds file and ran the simulation, but it is impossible to proceed further because of an error in the flow mode. Help me.

The content of the error is WARNING: Maximum density,    2.663 kg/m3, clipped in Mesh 1

If you need it, I will attach the fds file as well.

Thanks to everyone who will reply to this message.

**Comment by mcgratta** [comment]
Run the case with the latest test version. If it fails, I'll take a look at it. Follow links on the Download page to the test version.

**Comment by Soomin0101** [comment]
hello! developer!

I already run this case with latest version 

![image](https://user-images.githubusercontent.com/128450938/227839183-bed21183-cb7d-4d85-9c8c-0346ab344422.png)

Is this right? 

I'm so confused....

I already try to run fds file five times but all simulation conclusion have a same error.

So can I attached my fds file that you can see my file and find error?

**Comment by drjfloyd** [comment]
Kevin meant the test bundle which will be the next version of FDS whene released. Your issue likely stems from sealed volumes in your domain without leakage to the outside.  The test bundle is here: https://github.com/firemodels/test_bundles/releases

To attach an fds file to the issue tracker you will need to change the extension to .txt.  Github only allows a small number of file types to be attached to posts.

**Comment by mcgratta** [comment]
I am closing the issue. If the test version of FDS fails, reopen the issue or start a new one.
