### ISSUE TITLE
Low density MATL causes temperature issue

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11572]
In the attached case the TGA curve sees a spike in temperature once the MATL reaches ~500 C. If the densities are increased from their current 23 and 13 the odd temperature behavior goes away. 

[PIR.txt](https://github.com/firemodels/fds/files/11027016/PIR.txt)

**Comment by drjfloyd** [comment]
Did some more simplifying of the original case and appears to be something to do with the ABSORPTION_COEFFICIENT.  Without that input present the TGA temperature stays a linear ramp.

[PIR.txt](https://github.com/firemodels/fds/files/11027105/PIR.txt)

**Comment by drjfloyd** [comment]
One issues is when we do TGA we set the SF%TMP_GAS_FRONT and immeadiately call the 1D heat transfer. This means we have a surface whose Q_RAD_IN is based on TMPA and whose convective flux is based on TMP_GAS_FRONT. This case had a MATL ABSORPTION_COEFFICEINT set so we were going into the two flux routine and using the Q_RAD_IN for TMPA but computing Q_RAD_OUT for the two surfaces based on the node temperature. I think for TGA we should just force radiation to be false and stop SF%INTERNAL_RADATION from being turned on. In a TGA test the MATL is in a cup and the heat transfer is primarily conductive through the walls of the cup.  The high HTC and small sample size should be enough and this will also mean these cases run faster by not intializing the radiation model.

This case also failed when ASSUMED_GAS_TEMPERATURE was used (so once can get other diagnostics from the material). I'll look into this as well.

**Comment by mcgratta** [comment]
I agree. TGA is designed to use a tiny sample with very small thickness. In depth radiation makes no sense.

**Comment by drjfloyd** [comment]
Fixed.
