### ISSUE TITLE
Spatial statistic when PART_ID is set

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11587]
In the attached case, the convective flux is integrated over the surface of all particles within a region. It should be zero, because the heat transfer coefficient of the particles is fixed at zero. However, because the `XB` for the device integration contains some wall cells, this is not the case.

It can be fixed by just offsetting the `XB` slightly from the walls, but that is not always an ideal solution. I suggest adding a statement that bypasses `WALL_CELL_LOOP`
https://github.com/firemodels/fds/blob/5c793f055aec78b5642aa12f9257bd540cba0919/Source/dump.f90#L6167
and `CFACE_LOOP`
https://github.com/firemodels/fds/blob/5c793f055aec78b5642aa12f9257bd540cba0919/Source/dump.f90#L6200
if `DV%PART_CLASS_INDEX==0` 
...the assumption being that if you set `PART_ID` for a device you only want to include particles. It would also save unnecessary looping.

[spatial_stat_part.txt](https://github.com/firemodels/fds/files/11052347/spatial_stat_part.txt)

**Comment by mcgratta** [comment]
Yes, that makes sense.

**Comment by ericvmueller** [comment]
My change overlooked particles sticking to a surface - will take another look at it.

**Comment by ericvmueller** [comment]
Because of outputs like `AMPUA` which use a `PART_ID` but are associated with solid boundaries, the logic is more complex than this simple change. Unless this comes up as an issue more, the best approach is probably to just be cautious when defining `XB` to integrate over particles only.
