### ISSUE TITLE
MINIMUM_ZONE_VOLUME gives forrtl:severe error

### ISSUE THREAD

**Issue by IFAB-AS** [firemodels/fds#11592]
Hi all,
we tested the new function ``MINIMUM_ZONE_VOLUME`` which can be set on the MISC line (zones smaller than x m³ will be blocked and not considered for PRESSURE ZONES). We tried this for a model of a rail vehicle. The model is an imported *.dae file and prepared in PyroSim for FDS.
If we start the file without ``&MISC MINIMUM_ZONE_VOLUME=1/`` it runs, if we use the file with the line or some other value for the volume, FDS crashes at the start with ``forrtl: severe (157): Program Exception - access violation`` (tested with FDS 6.7.9-1634). 
[Rail-vehicle.txt](https://github.com/firemodels/fds/files/11061149/Rail-vehicle.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
There was a bug in the routine to re-index the pressure zones after removing some. In your case, there were over 400 zones, which reduced to 21. We should have a new test version out next week.

**Comment by mcgratta** [comment]
I new [test version](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST) is here. Could you try it and see if it fixes the problem.

**Comment by IFAB-AS** [comment]
I tested the new version with several models and it seems to work now.

**Comment by mcgratta** [comment]
Great. Thanks for pointing out this problem.
