### ISSUE TITLE
UGLMAT fails with blocked domain

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#11609]
The case below fails with a cryptic error message
GET_H_MATRIX_LUDCMP CLUSTER_SOLVER Sym Factor: The following ERROR was detected:    -1.

If the OBST is swapped it runs. The issue seems to be UGLMAT doesn't want to initialize if the entire mesh is filled with OBST. This is something that could occur in practice if one is using MULT to define meshes and the domain has large regions that are blocked off. 

&HEAD CHID='ulgmat_test'/

&MESH IJK=10,1,10,XB=0,1,0,0.1,0,1,MULT_ID='M1'/
&MULT ID='M1',DX=1,DZ=1,I_UPPER=1,K_UPPER=1/

&RADI RADIATION=F/

&TIME T_END=1/

&PRES SOLVER='UGLMAT', MAX_PRESSURE_ITERATIONS=1/

&OBST XB=0.0,1.1,0.0,0.1,0.0,1.1/
!&OBST XB=0.0,0.8,0.0,0.1,0.0,0.8/

**Comment by marcosvanella** [comment]
We'll have a look.

**Comment by rmcdermo** [comment]
OK, this case runs in serial but dies using MPI.

**Comment by rmcdermo** [comment]
@drjfloyd If you need this for an actual case, note that ULMAT seems to be working, if that helps.

**Comment by marcosvanella** [comment]
Probably related to the global matrix rows assignment to each process. There is a process that gets 0 rows if its mesh is completely blocked. I'm looking into it.

**Comment by drjfloyd** [comment]
Once I figured out what the problem was I changed my case to use to MULT lines so I could skip the blocked mesh. So I have a work around while a solution in general is found.

**Comment by marcosvanella** [comment]
Jason, do a repo update and try the case. 
I added some code to handle the situation of an MPI process not having pressure unknowns in UGLMAT.

**Comment by drjfloyd** [comment]
Case works now when I run with 4 MPI processes (one per mesh). It runs in < 1 s.  If I run as 1 process, it seems to hang. I'd expect it would just take 4 times as long, but after a minute there is still no timestepping. ULMAT works fine either way.

**Comment by marcosvanella** [comment]
Interesting, are you running the 4 mesh case with one MPI process? Is this in blaze? This is what I get with one MPI process (takes 0.06s) in my Mac:

$ mpirun -n 1 /Users/mnv/Documents/FIREMODELS_FORK/fds/Build/ompi_gnu_osx_dv/fds_ompi_gnu_osx_dv test.fds

 Starting FDS ...

 MPI Process      0 started on excess.el.nist.gov

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : March 30, 2023  14:54:26
 Revision         : FDS6.7.9-1958-g0413b44-master
 Revision Date    : Thu Mar 30 11:21:18 2023 -0400
 Compiler         : Gnu gfortran GCC
 Compilation Date : Mar 30, 2023  11:52:43

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Open MPI v4.1.5, package: Open MPI brew@Monterey Distribution, ident: 4.1.5, repo rev: v4.1.5, Feb 23, 2023

 Job TITLE        : 
 Job ID string    : test

 Time Step:      1, Simulation Time:      0.11 s
 Time Step:      2, Simulation Time:      0.23 s
 Time Step:      3, Simulation Time:      0.34 s
 Time Step:      4, Simulation Time:      0.45 s
 Time Step:      5, Simulation Time:      0.56 s
 Time Step:      6, Simulation Time:      0.68 s
 Time Step:      7, Simulation Time:      0.79 s
 Time Step:      8, Simulation Time:      0.90 s
 Time Step:      9, Simulation Time:      1.00 s

STOP: FDS completed successfully (CHID: test)

**Comment by drjfloyd** [comment]
One MPI process on my PC. I was running with _dv since that compiles fast. I compile the fully optimized version and see if that stalls.

**Comment by marcosvanella** [comment]
Well, I tried the case with the optimized gfortran target and get this:

 Starting FDS ...

 MPI Process      0 started on excess.el.nist.gov

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : March 30, 2023  15:06:43
 Revision         : FDS6.7.9-1958-g0413b44-master
 Revision Date    : Thu Mar 30 11:21:18 2023 -0400
 Compiler         : Gnu gfortran GCC
 Compilation Date : Mar 30, 2023  15:01:24

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Open MPI v4.1.5, package: Open MPI ***@***.*** Distribution, ident: 4.1.5, repo rev: v4.1.5, Feb 23, 2023

 Job TITLE        :
 Job ID string    : test

WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 1
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 3
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 3
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 4
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 4
 Time Step:      1, Simulation Time:      0.07 s
 Time Step:      2, Simulation Time:      0.14 s
 Time Step:      3, Simulation Time:      0.22 s
 Time Step:      4, Simulation Time:      0.31 s
 Time Step:      5, Simulation Time:      0.41 s
 Time Step:      6, Simulation Time:      0.51 s
 Time Step:      7, Simulation Time:      0.63 s
 Time Step:      8, Simulation Time:      0.74 s
 Time Step:      9, Simulation Time:      0.85 s
 Time Step:     10, Simulation Time:      0.97 s
 Time Step:     11, Simulation Time:      1.00 s

STOP: FDS completed successfully (CHID: test)

I also get these warnings with default Poisson solver, so might be unrelated. I have to study this further.

________________________________

**Comment by drjfloyd** [comment]
I don't even get it to start timestepping. It runs fine for me on one process with either the default pressure solver or ULMAT. I don't see the clipping warnings.

C:\Projects\FDS_test>\github\fds\Build\impi_intel_win\fds_impi_intel_win.exe uglmat_test.fds

 Starting FDS ...

 MPI Process      0 started on RTP0922PW03G7X0

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : March 30, 2023  15:15:46
 Revision         : FDS6.7.9-1958-g0413b44-dirty-master
 Revision Date    : Thu Mar 30 11:21:18 2023 -0400
 Compiler         : Intel ifort 2021.7.1
 Compilation Date : Thu 03/30/2023  03:03 PM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Windows* OS


 Job TITLE        :
 Job ID string    : ulgmat_test

**Comment by marcosvanella** [comment]
Ok, something is up with the windows version. It runs in blaze with intel, and in the Mac with gfortran, both optimized or not. I'll try to reproduce this in a windows machine. 
Just for testing, try executing fds with mpiexec -n 1 ... to make sure that also stalls. Thanks!

**Comment by drjfloyd** [comment]
mpiexec -n 1 stalls as well.

**Comment by marcosvanella** [comment]
I built a Windows 10 VM and put Visual Studio, OneAPI basic, HPC, git, etc. I compiled fds with the latest ifort 2021.9.0 all db, dv, and optimized win versions. I can't get the run to stall with one process in this uglmat_test case or partition.fds from issue #8782. 
I note I have to allow network connections for windows defender every first time I execute a new version of fds. I just clicked "Allow".  I'm not very familiar with windows, haven't used it in 15 years. 
I would suggest to install the latest OneAPI v2023 (ifort, impi 2021.9) if you don't have it and try the case.

C:\Users\mnv\Documents\Firemodels_fork\fds\Issues\UGLMAT>C:\Users\mnv\Documents\Firemodels_fork\fds\Build\impi_intel_win_dv\fds_impi_intel_win_dv.exe uglmat_test.fds

 Starting FDS ...

 MPI Process      0 started on VANELLAMARC947C

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : April 12, 2023  14:33:06
 Revision         : FDS6.7.9-2069-g8df9421-master
 Revision Date    : Wed Apr 12 12:39:40 2023 -0400
 Compiler         : Intel ifort 2021.9.0
 Compilation Date : Wed 04/12/2023  02:26 PM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.9 for Windows* OS


 Job TITLE        :
 Job ID string    : ulgmat_test

 Time Step:      1, Simulation Time:      0.11 s
 Time Step:      2, Simulation Time:      0.23 s
 Time Step:      3, Simulation Time:      0.34 s
 Time Step:      4, Simulation Time:      0.45 s
 Time Step:      5, Simulation Time:      0.56 s
 Time Step:      6, Simulation Time:      0.68 s
 Time Step:      7, Simulation Time:      0.79 s
 Time Step:      8, Simulation Time:      0.90 s
 Time Step:      9, Simulation Time:      1.00 s

STOP: FDS completed successfully (CHID: ulgmat_test)

**Comment by drjfloyd** [comment]
I'll try that. I have .7 for my ifort instead of .9.

**Comment by drjfloyd** [comment]
I recompiled and tried both debug and release. With a single process I still hang for UGLMAT and GLMAT but not ULMAT.  With more than one process it starts up immeadiately.  ULMAT works either way. As this seems to be some strange windows issue, maybe we just need a release note item that mentions this issue?

**Comment by gforney** [comment]
the case runs on my PC - I ran with FDS6.7.9-2080-gdc50845-master
