### ISSUE TITLE
forrtl: severe (157): Program Exception - access violation

### ISSUE THREAD

**Issue by DOGzym** [firemodels/fds#11604]
I'm new in FDS using and I've learnt a lot from the FDS community in Github. Now I have to handle a problem without other methods except seeking for your help. I would appreciate it if you can give me advice.

In my simulation, there's a PMMA board and it's set to pyroyze and generate MMA. MMA is also set to burn.The pyrolyze is under the influence of high temperature ambient wind, high temperature radiation source and a tiny heat source(as a spark).

Firstly, every time the simulation stopped at the same time because of numerical instability. I guess the problem is, possibly, that I don't set time step. But when I set time step as:
DT = 0.001
LOCK_TIME_STEP = .TRUE. /
the simulation failed because:  forrtl: severe (157): Program Exception - access violation 
I don't know how to solve the problem. By the way, how can I improve the accuracy of my pyrolysis model and burning model? Where should I modify in my simulation?
Any Help would be much appreciated!
[m.txt](https://github.com/firemodels/fds/files/11086977/m.txt)

**Comment by mcgratta** [comment]
I'll take a look, but in general, never lock the time step. If the CFL condition is violated, the simulation will become unstable and probably end in a seg fault.

**Comment by mcgratta** [comment]
It was as I suspected. The CFL condition was violated and the various computed quantities took on unphysical values leading to a failure in one of the subroutines. Do not lock the time step.

**Comment by DOGzym** [comment]
Thanks a lot for your advice. But in my previous simulation, that I didn't set time step, it ran unsuccessfully because of numerical instability (only when I set tiny mesh size. If I set rough mesh size, the simulation ran smoothly, but the output is not what I want). 
So, in this case, in order to avoid numerical instability, what should I do?
Appreciate for your patience!

**Comment by DOGzym** [comment]
I deleted time point locking order and tried again, still it stopped at the same time point (about 2.2s) because of numerical instability, I don't know how to solve this problem. 
Please check my input file. Thanks a lot!

**Comment by mcgratta** [comment]
```
BOILING_TEMPERATURE = 250
```
means that FDS is treating the sample as a liquid. Is that what you want?

Your resolution is 1 mm. You probably should set `SIMULATION_MODE='DNS'` on the `MISC` line.

I would also try running the case at half resolution just to get started, if you have not already.

Also, I prefer not to use `BURN_AWAY` in this kind of application, although the instability was probably not caused by it.

**Comment by DOGzym** [comment]
I'd appreciate a lot if you can run the case when you are convenient!

I saw a case in a previous article using BOILING_TEMPERATURE in MMA burning model. But in my opinion, MMA burning model is in gas phase condition. I don't know why the article used BOILING_TEMPERATURE in MMA burning model.

I'm using your methods for solving numerical instability, again thanks for your advice!

**Comment by mcgratta** [comment]
The COMBUSTION of MMA vapor is a gas phase phenomena. But `BOILING_TEMPERATURE` on the `MATL`  means that FDS is going to treat the PYROLYSIS of PMMA as if it were a liquid. This is not necessarily wrong, but I have never tried this at DNS resolution.

**Comment by mcgratta** [comment]
One other thing -- use cubic grid cells. That might help with the instability. 1 mm resolution, DNS.

**Comment by DOGzym** [comment]
Thanks a lot for your advice! now I'm running a new simulation and I've not found numerical instability yet. But I want to figure out wrong area in early simulation, so I tried to open plot3D file, but I couldn't find it in smokeview. 
How can I get an operatable plot3D file?

**Comment by mcgratta** [comment]
My version of your input file that I started yesterday is still running. It is up to 4.16 s. I suggest you break up the mesh and run this case in parallel. If you still have trouble, first try the latest test version of FDS, and second look at the last Plot3D file to determine a possible cause. Reopen the issue or start a new one if problems persist.
