### ISSUE TITLE
REAC Unbalanced stoichiometry in FDS 6.7.9-1935

### ISSUE THREAD

**Issue by IFAB-AS** [firemodels/fds#11605]
Hello.
I attached a file for a reaction (everything else is removed) which did work in FDS 6.7.9-1700 (4 weeks ago?) and is not working in the current version anymore (FDS 6.7.9-1935, this week). Were there some changes in the treatment of the SPECs or REAC or is something else causing the issue?
[REAC.txt](https://github.com/firemodels/fds/files/11099061/REAC.txt)

**Comment by drjfloyd** [comment]
We changed the definition of soot (see the FDS Release Notes Wiki) to be just C.  Two options are you can recompute the lumped species and nus to account for this or if you want to just use the existing file add FORMULA='C0.9H0.1' to your SOOT SPEC.

**Comment by IFAB-AS** [comment]
Using the additional FORMULA='C0.1H0.9' works for us, as we would need to recalculate several other REACS as well otherwise.
