### ISSUE TITLE
Insuffcient error information to troubleshoot pressure zone mesh boundary issue

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#11602]
I have a case with an imported, complex CAD model and 9 meshes that I'm trying to run with 6.7.9-933. The meshes are set up like this:

![Issue](https://user-images.githubusercontent.com/114649229/227916648-84816e1d-15d5-4d56-8a04-1b10aea83c7f.png)

Mesh 1 and 2 are 0.2 x 0.2 x 0.2 m (169, 48, 32 cells X,Y,Z each)
Mesh 3 is 0.4 x 0.4 x 0.2 m (169, 25, 32 cells X, Y, Z) and exactly next to meshes 1 and 2.
Mesh 4 is 0.4 x 0.4 x 0.2 m (169, 49, 22 cells X, Y, Z) and covers meshes 1, 2 and 3
Mesh 6 is 0.4 x 0.4 x 0.2 m (89, 49, 75 cells X, Y, Z) and borders meshes 2, 3 and 4.

There are no holes at the mesh boundaries or manual flow paths between the meshes.

FDS refuses to start, displaying the errors below (abridged, each message is repeated at least two dozen times):

```
ERROR: ZONE ** meets ZONE  0 at the boundary of MESH    2 and MESH    6
...
ERROR: ZONE ** meets ZONE ** at the boundary of MESH    6 and MESH    3
ERROR: ZONE ** meets ZONE  0 at the boundary of MESH    2 and MESH    6
...
ERROR: ZONE ** meets ZONE ** at the boundary of MESH    6 and MESH    4
```

The issue does not occur if...
...mesh 6 is disabled.
...the boundary area between mesh 2 and mesh 6 is blocked with an obstacle.

Troubleshooting this issue is complicated by:
- the error message only handling two-digit zone indices (i.e. up to 99). The case has ~700 zones according to the HRR output file.
- the case not generating output for a PRESSURE ZONE 3D slice for analysis in Smokeview.

So my request is, of course next to the error not occurring in the first place, to have FDS provide more specific information to facilitate troubleshooting.

(I am aware of other mentions of the error message like https://github.com/firemodels/fds/issues/10874 or https://github.com/firemodels/fds/issues/10889 or https://groups.google.com/g/fds-smv/c/eDgUzYKucFY/m/HBEGGP-6AwAJ or https://groups.google.com/g/fds-smv/c/zSBPpqVxoEw or https://groups.google.com/g/fds-smv/c/svQoGTyOopM )

I'm going to try to come up with a test case.

**Comment by mcgratta** [comment]
I will take a look.

**Comment by mcgratta** [comment]
Just post the MESH lines.

**Comment by FireResearch-BK** [comment]
Found the culprit (object too close to a mesh boundary). Here is the case stripped to the bare necessities to reproduce the issue (in 6.7.9-933).

[TestCase.txt](https://github.com/firemodels/fds/files/11079205/TestCase.txt)

If the boundary of meshes 2,3,4 and 6 are moved by 0.4 m along +X (i.e. 1 and 2 cells respectively), both the test and original case run.

So this looks like an instance of https://github.com/firemodels/fds/issues/10889.

It would help if FDS printed out something akin to "Check for thin obstacles at boundaries between meshes of different grid resolution" when this error occurs.

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/227961607-fdb27391-f62b-4894-a432-efbb224075c1.png)
This is the problem, I think. This is a view from the top. I need to dig into it more. The latest test version fixes the problem of overflowing digits, but the request to have a 3D slice in Smokeview showing pressure zones is much harder. This kind of error is detected very early in the simulation, before output is setup for Smokeview. As best, Smokeview can render an image like I've shown.

The larger issue is that these CAD files render thin plates rather than whole solids. When a "hollow" obstruction crosses a mesh boundary and the grid spacing changes, the pressure zone gets corrupted. Think of a ventilation duct that is no longer properly resolved on the coarse grid.

**Comment by FireResearch-BK** [comment]
Thanks for the explanation.

Since the issue was resolved by moving the mesh boundaries a bit, I think a clearly worded error message akin to my suggestion above (as well as a sentence or two in the User Guide) could provide a stopgap solution until an actual fix materializes.

**Comment by drjfloyd** [comment]
We know at least one IJK value in each MESH.  We could add the IJKs to the error message. With the pair of mesh number and IJK you would at least know where to look.

```
            IF (WC%BOUNDARY_TYPE==INTERPOLATED_BOUNDARY .AND. M%PRESSURE_ZONE(IIG,JJG,KKG)>=0 .AND. &
               OM%PRESSURE_ZONE(IIO,JJO,KKO)>=0 .AND. M%PRESSURE_ZONE(IIG,JJG,KKG)/=OM%PRESSURE_ZONE(IIO,JJO,KKO)) THEN
               WRITE(LU_ERR,'(A,I0,A,I0,A,I0,A,I0)') 'ERROR: ZONE ',OM%PRESSURE_ZONE(IIO,JJO,KKO),' meets ZONE ',&
                  M%PRESSURE_ZONE(IIG,JJG,KKG),' at the boundary of MESH ',NOM,' and MESH ',NM
               STOP_STATUS = SETUP_STOP
               EXIT MESH_LOOP
            ENDIF
```

**Comment by mcgratta** [comment]
OK, I'll try that.

**Comment by mcgratta** [comment]
This is what the message is now
```
ERROR: ZONE 8 meets ZONE 0 at the boundary of MESH 2 (168,21,10) and MESH 6 (1,11,10)
```

**Comment by mcgratta** [comment]
The message tells you exactly where the mismatch occurs.
