### ISSUE TITLE
Large FDS case segfaults on Ubuntu 22.10

### ISSUE THREAD

**Issue by FireResearch-BK** [firemodels/fds#11619]
I am trying to run a large case (~4.5 million cells in total split into 7 meshes) on a self-compiled FDS 6.7.9-933 release on Ubuntu 22.10, but it always segfaults before the first time step. 
The FDS installation itself is not the issue because a smaller case runs just fine.
Running the case in the latest official 6.7.9 release fails with the same error.

```
Starting FDS ...

 MPI Process      2 started on Laptop
 MPI Process      4 started on Laptop
 MPI Process      1 started on Laptop
 MPI Process      3 started on Laptop
 MPI Process      0 started on Laptop
 MPI Process      6 started on Laptop
 MPI Process      5 started on Laptop

 Reading FDS input file ...

 Fire Dynamics Simulator

 Current Date     : March 30, 2023  17:49:11
 Revision         : FDS6.7.9-933-g58f255f58-HEAD
 Revision Date    : Fri Nov 25 16:12:02 2022 -0500
 Compiler         : ifort version 2021.8.0
 Compilation Date : Mär 29, 2023 14:09:13

 MPI Enabled;    Number of MPI Processes:       7
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Linux* OS


 Job TITLE        : My_job
 Job ID string    : Some Title

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libc.so.6          00007FB6D0E3BCF0  Unknown               Unknown  Unknown
fds                0000000006E0D74F  Unknown               Unknown  Unknown
fds                0000000006DF9A77  Unknown               Unknown  Unknown
fds                0000000006ABAE9F  Unknown               Unknown  Unknown
fds                000000000040791D  Unknown               Unknown  Unknown
libc.so.6          00007FB6D0E23510  Unknown               Unknown  Unknown
libc.so.6          00007FB6D0E235C9  __libc_start_main     Unknown  Unknown
fds                0000000000407835  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 4697 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 4698 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 4700 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 4701 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 4702 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 6 PID 4703 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
```

As I need some flexibility to run cases with different FDS releases without having to dive into .bashrc, I am using this bash script for startup that also handles the environment variables:
```
#! /bin/bash
#
# Set FDS version and FDS root directory
#
fdsver=6.7.9-933
fdsfolder=/mnt/CFD-DiskFDS/FDS_$fdsver/bin
#
#
# Set environment variables and paths
#
impihome=$fdsfolder/INTEL
export PATH=$fdsfolder:$PATH
export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
export FI_PROVIDER_PATH=$impihome/prov
export LD_LIBRARY_PATH=$impihome/lib:$LD_LIBRARY_PATH
export PATH=$impihome/bin:$PATH
#
# Find every FDS file in the current folder, determine the number of meshes in it and launch it with the corresponding process and thread configuration
#
echo " "
#
for i in *.fds; do
	# Count number of meshes in FDS input file
	num_meshes=$(grep -o "&MESH ID=" "$i" | wc -l)
	if [[ num_meshes -gt 1 ]]; then
		num_processes=$num_meshes
		num_threads=1
		echo "Found $num_meshes meshes in FDS file, launching FDS with $num_processes MPI processes without OpenMP for optimum performance."
		echo " "
		mpirun -np $num_processes $fdsfolder/fds $PWD/$i
		
	fi
	if [[ num_meshes -eq 1 ]]; then
		echo "Found $num_meshes mesh in FDS file, launching FDS with OpenMP for optimum performance."
		echo " "
		$fdsfolder/fds_openmp $PWD/$i
	fi	
done
```

I have added this to my .bashrc:
```
# MPI Library:
export MPIDIST=/shared/openmpi_64
export PATH=$MPIDIST/bin:$PATH
export LD_LIBRARY_PATH=$MPIDIST/lib:$LD_LIBRARY_PATH
# Unlimited stack size
ulimit -s unlimited
```

The stack size mod is correctly applied on startup:
```
$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 125758
max locked memory           (kbytes, -l) 4033928
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 125758
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

For reference, this is the mesh setup I'm using:
```
&MESH ID='Mesh1', IJK=158,98,43, XB=118.5,150.1,-9.6,10.0,4.6,13.2/
&MESH ID='Mesh2', IJK=39,164,48, XB=120.3,128.1,10.0,42.8,3.6,13.2/
&MESH ID='Mesh3, IJK=296,98,22, XB=27.7,86.9,-9.6,10.0,4.6,9.0/
&MESH ID='Mesh4', IJK=158,98,43, XB=86.9,118.5,-9.6,10.0,4.6,13.2/
&MESH ID='Mesh5', IJK=215,98,32, XB=107.1,150.1,-9.6,10.0,-1.8,4.6/
&MESH ID='Mesh6', IJK=397,50,32, XB=27.7,107.1,0.0,10.0,-1.8,4.6/
&MESH ID='Mesh7', IJK=397,48,32, XB=27.7,107.1,-9.6,0.0,-1.8,4.6/
```

The machine has a Ryzen 4800H (8+8 cores plus SMT/HT) and 32 GB PC3200 RAM. I've seem RAM usage climb to 16 GB before the crash. There is also more than enough space available on the NVMe SSD.
The exact same case starts just fine on a much older Windows 10 machine (i7 3770, 24 GB RAM).

I think the Laptop is running out of memory somewhere, but I have no idea where.

One thing I have tried so far is ```ulimit -n 4096```, but this did not improve matters. ```ulimit -l unlimited``` is not permitted and does not work from .bashrc either.

I'm trying to start the case with OpenMP at the moment, but the initialization will probably take all night.

**Comment by FireResearch-BK** [comment]
OpenMP also segfaulted:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libc.so.6          00007FF8A043BCF0  Unknown               Unknown  Unknown
fds_openmp         00000000074E1016  Unknown               Unknown  Unknown
fds_openmp         00000000074CD1C7  Unknown               Unknown  Unknown
fds_openmp         000000000718A025  Unknown               Unknown  Unknown
fds_openmp         0000000000408D1D  Unknown               Unknown  Unknown
libc.so.6          00007FF8A0423510  Unknown               Unknown  Unknown
libc.so.6          00007FF8A04235C9  __libc_start_main     Unknown  Unknown
fds_openmp         0000000000408C35  Unknown               Unknown  Unknown
```

**Comment by drjfloyd** [comment]
If you are self-compiling, can you try compiling and running the case with the debug version? That version will give specific line numbers and varaibles where the error is.

**Comment by mcgratta** [comment]
Post the case and I will try to run it here.

**Comment by FireResearch-BK** [comment]
This is the case broken down to its core. Just meshes and ambient vents. No fire, no obstacle. It crashes each and every time I try to run it in Ubuntu.

[Test.txt](https://github.com/firemodels/fds/files/11139442/Test.txt)


Here's the output of a FDS 6.7.9-933 debug build:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libc.so.6          00007FF60E63BCF0  Unknown               Unknown  Unknown
fds_db             0000000002719FEB  radcompute_radiat        4521  radi.f90
fds_db             0000000002681FF4  rad_mp_compute_ra        3478  radi.f90
fds_db             0000000003FBFF98  MAIN__                    405  main.f90
fds_db             0000000000407A1D  Unknown               Unknown  Unknown
libc.so.6          00007FF60E623510  Unknown               Unknown  Unknown
libc.so.6          00007FF60E6235C9  __libc_start_main     Unknown  Unknown
fds_db             0000000000407935  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 24375 RUNNING AT Laptop
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

[etc]
```

\
A case with ~1.5 million cells worked just fine.

**Comment by mcgratta** [comment]
I am running the case now. Does the failure occur at the start of the simulaiton?

**Comment by mcgratta** [comment]
The case is running for me with the latest test version
```
 Fire Dynamics Simulator

 Current Date     : April  3, 2023  11:25:04
 Revision         : FDS6.7.9-1964-g0ace501-master
 Revision Date    : Fri Mar 31 12:59:54 2023 -0400
 Compiler         : ifort version 2021.7.1
 Compilation Date : Mar 31, 2023 16:23:06

 MPI Enabled;    Number of MPI Processes:       7
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS
```

Segmentation faults are common. They occur when, for example, an unallocated array is used, or an allocated array get overshot. In any case, try the latest test version.

**Comment by FireResearch-BK** [comment]
> I am running the case now. Does the failure occur at the start of the simulation?

Yes, during parsing of the input fire before the first timestep.


> Segmentation faults are common. They occur when, for example, an unallocated array is used, or an allocated array get overshot. In any case, try the latest test version.

Unless the latest commit has a fix for https://github.com/firemodels/fds/issues/11608, I'm sadly bound to 6.7.9-933.

**Comment by mcgratta** [comment]
I'll look at #11608.

**Comment by mcgratta** [comment]
I fixed #11608. There should be a new test version tomorrow.

**Comment by mcgratta** [comment]
I get an error with the latest debug version
```
 Job ID string    : Test

forrtl: severe (408): fort: (2): Subscript #1 of the array WA has value 8 which is greater than the upper bound of 7

Image              PC                Routine            Line        Source
fds_impi_intel_li  0000000000AF6A2C  pois_mp_vradbg_          4460  pois.f90
fds_impi_intel_li  0000000000A6E1AB  pois_mp_vrftb1_          3890  pois.f90
fds_impi_intel_li  0000000000A6B498  pois_mp_vrfftb_          3813  pois.f90
fds_impi_intel_li  00000000009A6648  pois_mp_vscosf_          2032  pois.f90
fds_impi_intel_li  000000000098FC5D  pois_mp_fsh26s_          1462  pois.f90
fds_impi_intel_li  00000000009811EA  pois_mp_fsh03s_          1098  pois.f90
fds_impi_intel_li  000000000097FD66  pois_mp_fsh02s_          1013  pois.f90
fds_impi_intel_li  00000000009720EC  pois_mp_s3cfss_           559  pois.f90
fds_impi_intel_li  0000000000970BCB  pois_mp_h3czss_           426  pois.f90
fds_impi_intel_li  000000000329B2A3  pres_mp_pressure_         369  pres.f90
fds_impi_intel_li  0000000004013CBB  fds_IP_pressure_i        1418  main.f90
```
This is the pressure solver during initialization. I'll dig into it.

**Comment by mcgratta** [comment]
The reason why we emphasize mesh dimensions that are multiples of 2, 3, and 5 is because the pressure solver used fast Fourier transforms, which don't like big primes
```
&MESH ID='1', IJK=158,98,43, XB=118.5,150.1,-9.6,10.0,4.6,13.2/
&MESH ID='2', IJK=39,164,48, XB=120.3,128.1,10.0,42.8,3.6,13.2/
&MESH ID='3', IJK=296,98,22, XB=27.7,86.9,-9.6,10.0,4.6,9.0/
&MESH ID='4', IJK=158,98,43, XB=86.9,118.5,-9.6,10.0,4.6,13.2/
&MESH ID='5', IJK=215,98,32, XB=107.1,150.1,-9.6,10.0,-1.8,4.6/
&MESH ID='6', IJK=397,50,32, XB=27.7,107.1,0.0,10.0,-1.8,4.6/
&MESH ID='7', IJK=397,48,32, XB=27.7,107.1,-9.6,0.0,-1.8,4.6/
```
The dimensions in the y and z direction are the ones to watch. I don't like 43 or 164=41x4

**Comment by FireResearch-BK** [comment]
I have given up and installed Windows 11 on the laptop (the Ubuntu partition still exists though). The test case starts and runs normally on FDS 6.7.9-933.

As the root issue is not solved yet (I'd like some feedback from other Ubuntu or Linux users if this is something inherent or particular to Ubuntu 22.10), I'd like to leave this issue open.

&nbsp;

> The reason why we emphasize mesh dimensions that are multiples of 2, 3, and 5 is because the pressure solver used fast Fourier transforms, which don't like big primes
> 
> ```
> &MESH ID='1', IJK=158,98,43, XB=118.5,150.1,-9.6,10.0,4.6,13.2/
> &MESH ID='2', IJK=39,164,48, XB=120.3,128.1,10.0,42.8,3.6,13.2/
> &MESH ID='3', IJK=296,98,22, XB=27.7,86.9,-9.6,10.0,4.6,9.0/
> &MESH ID='4', IJK=158,98,43, XB=86.9,118.5,-9.6,10.0,4.6,13.2/
> &MESH ID='5', IJK=215,98,32, XB=107.1,150.1,-9.6,10.0,-1.8,4.6/
> &MESH ID='6', IJK=397,50,32, XB=27.7,107.1,0.0,10.0,-1.8,4.6/
> &MESH ID='7', IJK=397,48,32, XB=27.7,107.1,-9.6,0.0,-1.8,4.6/
> ```
> 
> The dimensions in the y and z direction are the ones to watch. I don't like 43 or 164=41x4

How great is the performance penalty?

**Comment by mcgratta** [comment]
The penalty for not using multiples of small prime numbers is not large, and most FDS users choose whatever dimensions that they want. However, on rare occasions, like this one, the pressure solver has a minor glitch in which an array is overshot by 1 value. Sometimes the release compilation of the code just ignores this, but the debug version does not. It is also possible that the compilation under linux behaves a bit differently under Windows. I do not understand well enough what effect the OS has on the execution of the program. I also did not write that pressure solver, and I cannot "fix" this issue directly in the code. My typical way of dealing with it is to use different mesh dimensions that involve multiples of small primes.

**Comment by FireResearch-BK** [comment]
Both the original and the barebone test case still segfault with FDS 6.8.0 and Ubuntu 22.10.

**Comment by rmcdermo** [comment]
These are massive meshes.  Is the handling memory potentially an issue?

**Comment by FireResearch-BK** [comment]
> These are massive meshes. Is the handling memory potentially an issue?

Most likely, yes. But what is odd is that the issue does not occur on Windows.


@mcgratta 
If you're still running your CentOS-based cluster, can you please post the output of ```ulimit -a```?
I'd like to check if there's a difference to what Ubuntu provides.

**Comment by mcgratta** [comment]
As shown above
```
 Job ID string    : Test

forrtl: severe (408): fort: (2): Subscript #1 of the array WA has value 8 which is greater than the upper bound of 7

Image              PC                Routine            Line        Source
fds_impi_intel_li  0000000000AF6A2C  pois_mp_vradbg_          4460  pois.f90
fds_impi_intel_li  0000000000A6E1AB  pois_mp_vrftb1_          3890  pois.f90
fds_impi_intel_li  0000000000A6B498  pois_mp_vrfftb_          3813  pois.f90
fds_impi_intel_li  00000000009A6648  pois_mp_vscosf_          2032  pois.f90
fds_impi_intel_li  000000000098FC5D  pois_mp_fsh26s_          1462  pois.f90
fds_impi_intel_li  00000000009811EA  pois_mp_fsh03s_          1098  pois.f90
fds_impi_intel_li  000000000097FD66  pois_mp_fsh02s_          1013  pois.f90
fds_impi_intel_li  00000000009720EC  pois_mp_s3cfss_           559  pois.f90
fds_impi_intel_li  0000000000970BCB  pois_mp_h3czss_           426  pois.f90
fds_impi_intel_li  000000000329B2A3  pres_mp_pressure_         369  pres.f90
fds_impi_intel_li  0000000004013CBB  fds_IP_pressure_i        1418  main.f90
```
We did not write the pressure solver. But I know that the calculation is fast because a fast Fourier transform is used to speed up the solution of the linear system of equations. FFTs are based on dividing the array bounds by 2. When the array bounds are large primes, this "divide and conquer" algorithm is not as efficient, and in this case causes an array over-shoot. But this is not a problem of running out of RAM.

**Comment by mcgratta** [comment]
```
[mcgratta@burn Test]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 255041
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by FireResearch-BK** [comment]
The most striking difference I'm seeing is ```max locked memory (kbytes, -l) unlimited```. I've managed to set this to "unlimited" on Ubuntu as well with [these instructions](https://stackoverflow.com/a/55294367), but while the limit is correctly applied, the test case still segfaults.

The mystery persists...

**Comment by mcgratta** [comment]
This block of code in pois.f90
```
DO  J=2,IP
  IS = (J-2)*IDO
  DO  K=1,L1
    IDIJ = IS
    DO  I=3,IDO,2
      IDIJ = IDIJ+2
      DO  M=1,MP
        C1(M,I-1,K,J) = WA(IDIJ-1)*CH(M,I-1,K,J)-WA(IDIJ)* CH(M,I,K,J)   <---- Problem line
        C1(M,I,K,J) = WA(IDIJ-1)*CH(M,I,K,J)+WA(IDIJ)* CH(M,I-1,K,J)
      END DO
    END DO
  END DO
END DO
143 RETURN
END SUBROUTINE VRADBG
```
is the source of the error. The index `IDIJ` of the array `WA` is larger than the size of the array. This is probably ignored when the code is compiled with optimizations, or it might be trapped depending on the various things related to the OS. In any event, I do not know enough about this routine to fix it. But I do know that this mesh
```
&MESH ID='3', IJK=296,98,22, XB=27.7,86.9,-9.6,10.0,4.6,9.0/
```
was causing the problem. When I ran this single mesh
```
&MESH IJK=296,96,24, XB=27.7,86.9,-9.6,10.0,4.6,9.0 /
```
I did not get the error. 96 and 24 are better values than 98 and 22 for the FFT. The first dimension, 296, is not the problem because the pressure solver does not do an FFT in this dimension. 

So my suggestion to you is to redo your meshes using "better" numbers for the second and third dimension. "Better" numbers are those that can be factored into relatively small primes. I cannot give you a precise definition of what I mean by small primes, however. 2, 3, 5 are best.

**Comment by FireResearch-BK** [comment]
Would @marcosvanella be able to help with the pressure solver?

Regardless of the performance penalty incurred by "bad" mesh dimensions, the impact of this bug is entirely dependent upon the grace of the operating system to work around or ignore it. It's lucky that at least two of the tested four OS do so since trying to balance meshes for a minimal number of cells, an amount of meshes that is suitable for the available number of CPUs, good mesh boundary cell alignment and for mesh boundaries not cutting through too many pressure zones, all while under a fixed grid size contraint, is already very challenging. Adding a small prime number constraint for the J and K dimensions into the mix to make the case run in the first place...well, I dare not to think about it.

Assuming the bug is not feaible to fix, would it at least be possible to implement an analysis of the J and K dimensions of the mesh lines for your suggested small primes (2,3,5) during the parsing of the FDS input file and print out a warning to the console if the default FFT solver is used and the J and K dimensions are not "good"?
Something like: "WARNING: [I/J] cell count of mesh [n] is not composed of small primes (2,3,5). This may cause a FFT pressure solver performance penalty or simulation crash."
This may at least help give users a hint as to why their simulation refuses to start, making troubleshooting easier.

**Comment by mcgratta** [comment]
There are alternative pressure solvers in FDS. But they only work in limited cases. In your case, your meshes are too large and the other pressure solvers would require too much memory. The other solvers are also slower, in most cases. 

I can look into a better diagnostic. Typically we find that our warning messages are ignored, but I'll see. These kinds of errors in the pressure solver are fairly rare, and we do that most people do not conform to the 2-3-5 rule.

**Comment by marcosvanella** [comment]
Hi @FireResearch-BK, unfortunately trying to fix this issue would require me to learn the implementation of CrayFISHPACK which is the library of solvers in pois.f90, and I don't have the time now. Note this library dates from the 80s and I doubt there is any support from it currently.

**Comment by mcgratta** [comment]
I just pushed up a fix that prevents the seg fault, at least on my Centos cluster in debug mode. Try recompiling and run the case again. The fix was to allocate more space to an array, although it is not clear how much more is needed. So more work needs to be done. But at least let's see if it fixes your problem.

**Comment by FireResearch-BK** [comment]
Thanks. I'll test your fix once I have the opportunity.

**Comment by FireResearch-BK** [comment]
I finally had an opportunityto run the test case with 6.8.0-172, but it still segfaults with the same error.
As I have no time to dive into this any further, I will stick to FDS on Windows from now on for productivity's sake.

In any case, thanks for all the help so far.

**Comment by mcgratta** [comment]
OK. I'll try running the simple case again and see if I can find a fix. Sometimes a small difference in how the OS or compiler handles the numerics or optimization makes the difference. We try to remove these vulnerabilities.

**Comment by mcgratta** [comment]
I cannot reproduce the error with ifort version 2021.7.1. I compiled in both non and fully optimized mode.

**Comment by marcosvanella** [comment]
I run the case with gcc 14 (clang) and OpenMPI 4.1.5 in the Mac, both optimized and debug targets, and dont get the segfault. Interestingly I see this in optimized mode but not in dv,db modes:
```
 Fire Dynamics Simulator

 Current Date     : June  8, 2023  17:33:58
 Revision         : FDS-6.8.0-235-ge6eeefa-dirty-master
 Revision Date    : Thu Jun 8 15:11:53 2023 -0400
 Compiler         : Gnu gfortran GCC
 Compilation Date : Jun 08, 2023  17:29:58

 MPI Enabled;    Number of MPI Processes:       7
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Open MPI v4.1.5, package: Open MPI brew@Monterey Distribution, ident: 4.1.5, repo rev: v4.1.5, Feb 23, 2023

 Job TITLE        : Test
 Job ID string    : Test

WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 2
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 7
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 7
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 6
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 6
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 3
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 3
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 4
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 4
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 1
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 5
WARNING: Maximum density,   12.788 kg/m3, clipped in Mesh 5
 Time Step:      1, Simulation Time:      0.05 s
 Time Step:      2, Simulation Time:      0.10 s
```
I'll setup an Ubuntu VM to see ir we can reproduce what you see.

**Comment by marcosvanella** [comment]
@FireResearch-BK just to be sure, you are still seeing the line 4460 of pois.f90 segfault in your Ubuntu runs for Test.txt?

**Comment by FireResearch-BK** [comment]
> @FireResearch-BK just to be sure, you are still seeing the line 4460 of pois.f90 segfault in your Ubuntu runs for Test.txt?

I can't remember, sorry. The last time I just saw that it segfaulted again and that was it. 
The Ubuntu installation on the device also does not exist anymore due to a lack of time for testing, debugging and maintenance.

If need be, I can continue testing privately on Arch Linux, which also exhibits the segfault (see https://github.com/firemodels/fds/issues/11619#issuecomment-1494545521).

**Comment by marcosvanella** [comment]
I tried running the case in an Ubuntu 22.04 LTS virtual machine with gcc 11 and OpenMPI compile for the system with this confmake.sh for openmpi 4.1.5:
```
#!/bin/bash
./configure --prefix /opt/openmpi415_oneapi22u3 \
  CC=gcc CXX=g++ F77=gfortran FC=gfortran \
  --enable-static --disable-shared | tee CONFIGURE.out
make -j 2
```
As I have 4 processors I oversubcribed the mpirun for 7 meshes with:
`
mpirun --oversubscribe -n 7 $FDSDIR/Build/ompi_gnu_linux/fds_ompi_gnu_linux Test.fds
`
I cannot reproduce the error. Also, I did not get the different behavior seen on the Mac with optimized gnu and openmpi, probably an artifact of the optimization in different versions of the compiler.

**Comment by mcgratta** [comment]
OK, I will close the issue. If something like this reoccurs, we can start a new issue. This one has become quite complex.

**Comment by marcosvanella** [comment]
Ok, I'll just add that I had 16GB Ram assigned to the VM, probably lower than what @FireResearch-BK is using.

**Comment by FireResearch-BK** [comment]
> Ok, I'll just add that I had 16GB Ram assigned to the VM, probably lower than what @FireResearch-BK is using.

Yes, as my laptop has 32 GB.

I also did not use any special flags or other modifications for compiling, I just ran the FDS build script.

**Comment by marcosvanella** [comment]
@FireResearch-BK yes, I used the make_fds.sh scripts in ompi_gnu_linux and ompi_gnu_linux_db targets to build fds.  I also used latest source. Also, I wasn't clear : the confmake.sh I posted is to compile openmpi.
