### ISSUE TITLE
the simulation does not start 

### ISSUE THREAD

**Issue by ghaimaroua** [firemodels/fds#11626]
hi im student and it is my first time in using fds i have some issue please help me 
i use FDS6.7.9 on windows 11 
i use Pyrosim and fds  for the simulation and i got this message and the simulation does not work 

C:\Users\ghais\Desktop\please>fds_local -p 1 -o 16 last.fds

 Starting FDS ...

 MPI Process      0 started on Administrator

 Reading FDS input file ...

WARNING: SPEC REAC_FUEL is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.

 Fire Dynamics Simulator

 Current Date     : April  3, 2023  01:14:13
 Revision         : FDS6.7.9-0-gec52dee42-release
 Revision Date    : Sun Jun 26 14:36:40 2022 -0400
 Compiler         :
 Compilation Date : Tue 06/28/2022  11:17 PM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:     16

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Windows* OS

 Job TITLE        :
 Job ID string    : last
thank you so much

**Comment by rmcdermo** [comment]
You have not demonstrated an error.  The warning just says you are using a fuel that is not in the list of pre-defined.  It is ok, it will just not have the thermophysical properties of the actual material.

This should be posted to the Discussions page.  I think there should be a way to bounce it over there... I'll try.
