### ISSUE TITLE
Moving Particle Odd Interaction with Boundary

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11628]
I was testing the moving particle feature as part of the FED analysis the other day. I noticed an odd interaction when the particle reaches the boundary of the domain. In the attached file, 2 particles follow the same path for the first 10 seconds. The first particle rests at the x-boundary for an additional 10 seconds; however, particle 2 moves away from the boundary back to its original position. The particle which rests on the x-boundary is moved to x,y,z = 0,0,0 instead of resting at 0,2,1.8 position which was defined in the input file and was the behavior I was expecting. The second particle stays in the y=2, z=1.8 plane after reaching the boundary and moving back towards its initial position.
[particle_position_issue.txt](https://github.com/firemodels/fds/files/11139337/particle_position_issue.txt)

**Comment by mcgratta** [comment]
This is one of those less than/less than or equal to things. If you stop the occupant 1 cm away from the wall, things work. I'm hesitant to try to fix this because it will probably do more harm than good.

**Comment by johodges** [comment]
That makes sense, and I agree with not making a change in behavior.
