### ISSUE TITLE
Error while submitting jobscript to PBS scheduler (cellranger vdj pipeline)

### ISSUE THREAD

**Issue by Ktek28** [firemodels/fds#11624]
Hello,

Below is pasted my jobscript to be submitted to run cellranger vdj pipeline on my fasta sample files.

1 #!/bin/bash 2 #PBS -N RED_aregvdj 3 #PBS -q serial 4 #PBS -l nodes=1:ppn=24 5 #PBS -l walltime=03:00:00 6 #PBS -l pmem=3300mb 7 #PBS -m abe

 8  cd /home/tek05139/beegfs/PBS_O_WORKDIR/

 9  source '/software/cellranger-7.0.1/sourceme.bash'
10  source '/software/cellranger-7.0.1/sourceme.csh'
11  mpiexec -np 24 /software/cellranger-7.0.1/cellranger

12  cellranger vdj --id=red_aregvdj --fastqs=/home/tek05139/beegfs/DZ_081222/outs/fastq_path/AACGCHJM5 --reference=/home/tek05139/beegfs/refdata-cellranger-vdj-GRCm38-alts-ensembl-7.0.0 --sample=1_RED  --localcores=24 --localmem=64
After submitting the job, it runs for few minutes and returns the following error. I do not understand why. Can anyone please help :)

software/cellranger-7.0.1/sourceme.csh: line 6: syntax error near unexpected token (' /software/cellranger-7.0.1/sourceme.csh: line 6:set SOURCE=($_)'

Open MPI does not support recursive calls of mpiexec

I tried adding '_' to my source command after getting this error, but i nevertheless continue getting these errors. As far as I can get, there are two separate errors to be dealt with here. one is to be done with the syntax and the other for the mpiexec

Any help would be highly appreciated

**Comment by drjfloyd** [comment]
This is fds issue tracker. Neither cellrange nor fasta are part of this repository. I think you may have posted to the wrong project.

**Comment by Ktek28** [comment]
i am so sorry, i will remove it
