### ISSUE TITLE
USFS_Deep_Fuel_Beds all fail with numerical instability

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11631]
All of the validation cases within USFS_Deep_Fuel_Beds fail very early with a numerical instability. I looked at case 99, and the problem arises just below the tilted obstruction.

**Comment by marcosvanella** [comment]
I relaxed the size of small cells to be blocked. Do an Update and try these. Case 99 has run for 10sec in blaze for me.

**Comment by marcosvanella** [comment]
BTW something doesn't look right with burn99, the trees are getting inside the tilted ramp
<img width="636" alt="Screenshot 2023-04-07 at 5 01 20 PM" src="https://user-images.githubusercontent.com/7450069/230678717-6328e981-4382-4c5c-81ac-f9c2722d7149.png">

**Comment by rmcdermo** [comment]
Yeah, I noticed the same with another case.  I'm investigating.  Someone must have changed how particle are initialized.

**Comment by rmcdermo** [comment]
This seems to be fixed with PR #11653 .  Will reopen if we see more issues.

**Comment by rmcdermo** [comment]
We are not out of the woods with this case.  The cases now start and get through the initial ramp up of the fire.  Then, as the fire is dying out, the case goes unstable.

<img width="877" alt="Screenshot 2023-04-10 at 9 49 14 AM" src="https://user-images.githubusercontent.com/4418497/230914654-36e599fa-fcbb-46a0-ab6c-e9fdb1c23c56.png">

**Comment by rmcdermo** [comment]
The case is in:
```
fds/Validation/USFS_Deep_Fuel_Beds/FDS_Input_Files/burn37_30D_36S_30L.fds
```

**Comment by rmcdermo** [comment]
`/home/rmcdermo/GitHub/FireModels_rmcdermo/fds/Validation/USFS_Deep_Fuel_Beds/Current_Results`

**Comment by marcosvanella** [comment]
@rmcdermo do an update and try the case again.

**Comment by rmcdermo** [comment]
This case seems to be working fine.
