### ISSUE TITLE
Smv cannot represent the rest except for a 3d smoke view.

### ISSUE THREAD

**Issue by Soomin0101** [firemodels/fds#11658]
Dear developers

I have a Issuses in smokeview file.

Smv cannot represent the rest except for a 3d smoke view.

I also useed pyrosim result programe that I can see the result of slice.

But It was not working. 

So please hlp me to fix this problems.

-fds/ smv program is NIST's latest fds/smv program.

**Comment by mcgratta** [comment]
I do not understand what you are trying to say.
