### ISSUE TITLE
Temperature problem

### ISSUE THREAD

**Issue by Brian9924** [firemodels/fds#11655]
Hello, everyone! I would like to ask an issue that in a full size shaft fire, why the temperature will drop below 0℃ with 0.2m size of mesh. 

![1681098892356](https://user-images.githubusercontent.com/120773534/230822621-2b0d4f19-556e-4998-bb05-7976fc3a8df6.jpg)
![1](https://user-images.githubusercontent.com/120773534/230822312-a1f073b3-de9d-48a1-8ef1-dc3f850eee1e.png)
![2](https://user-images.githubusercontent.com/120773534/230822316-a8f07321-3608-4e95-a732-645aca586378.png)
![3](https://user-images.githubusercontent.com/120773534/230822323-6752b395-3a2f-436e-abe8-c0ee2acab648.png)
![0 2m](https://user-images.githubusercontent.com/120773534/230822378-07940fba-5ae4-4fef-95d5-037395ae92de.jpg)
![0 25m](https://user-images.githubusercontent.com/120773534/230822383-eb94d23f-bb9f-4c17-82c9-594a2599f7db.jpg)

**Comment by rmcdermo** [comment]
We need an input file.

**Comment by rmcdermo** [comment]
Just getting time to look at this.  First, you really have too many cells for one or two meshes.  Even in the 2 mesh case, I have been running for 20 minutes and have not produced a single time step yet.  This case needs parallel processing.

But the issue you are seeing is most likely related to the use of 2 meshes in the 0.2 m case.  Add this line to your input file and try the case again.

&PRES VELOCITY_TOLERANCE=1.E-6, MAX_PRESSURE_ITERATIONS=100/

Let me know if this solves the problem.

**Comment by Brian9924** [comment]
Thank you for your suggestion, I will give it a go.

**Comment by Brian9924** [comment]
Dear Mr. McDermott @rmcdermo , I have added the code which you have mentioned  to input file. And I divided eight meshes again. But it seems that only Mesh 01(MPI 0) outputs the results. The results of other meshes are invariant. How can I solve this problem？ THANK YOU！
![image](https://user-images.githubusercontent.com/120773534/231396739-9b642a27-2d0f-45d5-bfb9-1b96b6e670b3.png)
![image](https://user-images.githubusercontent.com/120773534/231397453-518ca792-55e7-45cf-992d-79d94b6f985c.png)
![image](https://user-images.githubusercontent.com/120773534/231397969-12adea61-64bb-42a1-9b35-7b0cd2ab1cf1.png)
![image](https://user-images.githubusercontent.com/120773534/231398084-b52a7255-2bdc-4d2e-a7fe-8d70eced7229.png)
![image](https://user-images.githubusercontent.com/120773534/231397557-6fb181b6-26ed-4a60-9048-cea3ea603e44.png)

**Comment by Brian9924** [comment]
Thank you for your patience.
Maybe I use MPI and OpenMP incorrectly? It is seen that there is not any information interaction between Mesh01 and other meshes.
![1681304010572](https://user-images.githubusercontent.com/120773534/231463388-1d8b429c-7ff0-4063-803a-cdd34bf06a9c.jpg)
![image](https://user-images.githubusercontent.com/120773534/231461744-3b7c59cc-7154-43b2-af91-b58cca795757.png)
[0_2_hrr.csv](https://github.com/firemodels/fds/files/11211660/0_2_hrr.csv)
[0_2_steps.csv](https://github.com/firemodels/fds/files/11211661/0_2_steps.csv)
[0_2_devc.csv](https://github.com/firemodels/fds/files/11211662/0_2_devc.csv)
