### ISSUE TITLE
Temperature problem

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#11677]
### Discussed in https://github.com/firemodels/fds/discussions/11666

<div type='discussions-op-text'>

<sup>Originally posted by **Brian9924** April  9, 2023</sup>
Hello, everyone! I would like to ask an issue that in a full size shaft fire, why the temperature will drop below 0℃ with 0.2m size of mesh. 

![1681098892356](https://user-images.githubusercontent.com/120773534/230822621-2b0d4f19-556e-4998-bb05-7976fc3a8df6.jpg)
![1](https://user-images.githubusercontent.com/120773534/230822312-a1f073b3-de9d-48a1-8ef1-dc3f850eee1e.png)
![2](https://user-images.githubusercontent.com/120773534/230822316-a8f07321-3608-4e95-a732-645aca586378.png)
![3](https://user-images.githubusercontent.com/120773534/230822323-6752b395-3a2f-436e-abe8-c0ee2acab648.png)
![0 2m](https://user-images.githubusercontent.com/120773534/230822378-07940fba-5ae4-4fef-95d5-037395ae92de.jpg)
![0 25m](https://user-images.githubusercontent.com/120773534/230822383-eb94d23f-bb9f-4c17-82c9-594a2599f7db.jpg)
</div>

**Comment by rmcdermo** [comment]
Sometimes things don't migrate over from Discussions.  This is what I wrote there.

Well, maybe I spoke too soon. There is something odd going on at the mesh boundary. There is clearly a blockage there that I suspect you don't want. I'm sending this back over the @mcgratta .

The case is located here: /home/rmcdermo/Issues/Issue_11655 The input file is test_8mesh.fds.

**Comment by mcgratta** [comment]
I carved out a much smaller domain around the vertical shaft, and divided it into 7 meshes as you had it.
![image](https://user-images.githubusercontent.com/11333911/231582957-68cd8f3d-c9fb-4dbd-ae0f-c61c1f7e0ce0.png)
The problem here is that the shaft is blocked. The HOLE that originally punched through all the floor slabs has been broken up:
```
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,5.55112E-17,9.4/
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,9.4,19.4/
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,19.4,29.4/
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,29.4,39.4/
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,39.4,49.4/
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,49.4,59.4/
&HOLE ID='Hole', XB=2230.0,2230.8,-1628.6,-1627.0,59.4,75.8/
```
This leaves a thin obstruction at the mesh boundaries.

**Comment by mcgratta** [comment]
https://user-images.githubusercontent.com/11333911/231594205-def5ec9c-78c0-4682-94e9-082404eb9e88.mp4

This is the smoke fighting against the downdraft. I'll run this small case out with the tighter pressure tolerance.

**Comment by mcgratta** [comment]
[test_shaft.txt](https://github.com/firemodels/fds/files/11223416/test_shaft.txt)

I've attached a test case which just involves the fire and vertical shaft. In future, if you are simulating a fire in a large building, you can test things using a reduced volume but the same grid resolution. Just remember to put OPEN boundaries at the x and y boundaries. You can use the MB notation for this.

This case demonstrates that you need to tighten the tolerance for velocity errors at solid boundaries. The chapter on Pressure in the User's Guide can explain further.
