### ISSUE TITLE
Fill a region with smoke as an initial condition

### ISSUE THREAD

**Issue by SaiSantosh1824** [firemodels/fds#11749]
Dear All,

I am relatively new to Pyrosim. Kindly help me figure out how to fill a region with smoke as an initial conditions and then use induction fans to clear the region. Upon searching the internet, I came across an expired link (https://www2.thunderheadeng.com/2015/04/modeling-jet-fans-fds-part-3-applications/) which provides a tutorial file to do the same. 

It would be really helpful if some one has a copy of the file or if someone can elaborate this methodology.

Thank you!!!

**Comment by mcgratta** [comment]
The Issue Tracker is not the right place for this kind of requiest.
