### ISSUE TITLE
New INIT_OVERLAP feature breaks tree cases

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11745]
This line
```
LOGICAL :: INIT_OVERLAP1(N_INIT,N_INIT),INIT_OVERLAP2(N_INIT,N_INIT) !=.FALSE.
```
in init.f90 breaks wildfire cases (`CROWN_FIRES/Pike1_pre_13ms.fds`, for example). These cases have something like 37,000 INIT lines, making this array ginormous. The code fails in many spectacular ways that are hard to pin down.

**Comment by drjfloyd** [comment]
I'll pass this along to Jonathan.

**Comment by mcgratta** [comment]
No time. I want to get these cases done. Is this feature really necessary?

**Comment by drjfloyd** [comment]
I am going to be out of pocket the rest of the day.

Previously, if you had an INIT line that set temperature and then had an INIT line that set a particle, when the particle INIT was processed it would reset the temperature to ambient. This fix was 1) preventing a particle only init from overwriting gas phase variables, and 2) checking for overlapping gas phases inits and writing a WARNIING.

**Comment by mcgratta** [comment]
OK, I'll see if I can work it.

**Comment by johodges** [comment]
That array is required if we want to tell the user which two init regions are overlapping. If we just want to warn that there is an overlap we won't need that array and shouldn't run into memory issues.

**Comment by mcgratta** [comment]
Yes, I'll fix it.

**Comment by johodges** [comment]
I have a fix in place if you want me to do a PR.

**Comment by mcgratta** [comment]
No, I will fix it.
