### ISSUE TITLE
OpenMP in FDS >=6.7.8

### ISSUE THREAD

**Issue by sacunningham** [firemodels/fds#11771]
I see in the release notes for FDS 6.7.8 the following note.

> There are now two executables distributed in the bundle. One is optimized for a single thread (about 20 % faster) and should be used for MPI calculations without OpenMP. The second executable, appended with _openmp, includes OpenMP compile directives and should be used for multi-thread calculations.

For all versions newer than 6.7.8 the install scripts found on the [releases page](https://github.com/firemodels/fds/releases) seem to be the single thread version.  When running FDS I'm getting an OpenMP Disabled message in the standard out where I would normally see my OMP thread count.  Where can I find the OpenMP versions?

**Comment by mcgratta** [comment]
What operating system are you using?

**Comment by sacunningham** [comment]
Both Windows and Linux.  See screenshots below

![linux_screencapture](https://user-images.githubusercontent.com/10402481/233725011-7168fb45-b88a-499a-b6b6-b92d0409ecb7.png)

![windows_screencapture](https://user-images.githubusercontent.com/10402481/233725090-1483a92a-a92e-4b82-a9b6-936488eddf3a.png)

**Comment by mcgratta** [comment]
`fds` is the name of the non-OpenMP executable. `fds_openmp` is the name of the OpenMP-enabled executable.

**Comment by sacunningham** [comment]
Understood. I misinterpreted the release note.  6.7.8 introduced a new command named fds_openmp.  I was looking for a separate installer for the executable.  I'm getting the expected behavior now, Thank You.
