### ISSUE TITLE
problem of DEVC of the HEAT FLUX

### ISSUE THREAD

**Issue by DOGzym** [firemodels/fds#11773]
I want to get the data of radiant heat flux. however, I checked FDS User Guide, and I couldn't find how to just output radiant heat flux data solely. 

Except the Quantity 'Gauge Heat FLUX', are there any other kinds of Quantity I can use to output heat flux?

I'd appreciate it a lot if you can give me some help.

**Comment by mcgratta** [comment]
This is more appropriate for the Discussion Forum. However, the FDS User's Guide has a section in which it details these various heat flux outputs.

**Comment by DOGzym** [comment]
Thanks a lot for your reply. I find them in FDS User's Guide 21.10.12.
