### ISSUE TITLE
Incorrect surface and bulk density with boundary fuel model for vegetation

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#11770]
With the boundary fuel model for vegetation it appears that the surface density (kg/m^2) is incorrect (as shown in Smokeview) and the SF%LAYER_DENSITY is incorrect in wall.f90.

See the comments at the top of the attached simplified input file.

[input_loading_test_BFM.txt](https://github.com/firemodels/fds/files/11289012/input_loading_test_BFM.txt)

**Comment by ericvmueller** [comment]
If you check the .out file you can see the breakdown of the components for the surface. `AIR` is implicitly added based on the `MASS_PER_VOLUME` and other material components. When you don't specify a `MATL_ID` on the `SURFACE DENSITY` output you are getting the combination of air, moisture, and dry vegetation (the LAYER_DENSITY is also this combination).

So if you want to track the fuel loading, you can use:
`&BNDF QUANTITY='SURFACE DENSITY', MATL_ID='DRY GRASS' /`
and get 0.2 kg/m2

**Comment by ruddymell** [comment]
Got it. Thanks Eric
