### ISSUE TITLE
TIMER device output

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11772]
Hi,

I would like to request a feature.
User guide says TIME quantity is not output. When I set OUTPUT to .TRUE. it still does not output. Would it be possible for user to overwrite this?
Thanks.

18.2
`  If the DEVC QUANTITY=’TIME’, then OUTPUT is set to F automatically.`

**Comment by mcgratta** [comment]
Can you use the first column of the `_devc.csv` file for the `TIME`?

**Comment by mcgratta** [comment]
Can you post a very simple input file that shows what you are trying to do?

**Comment by Er9y714** [comment]
There are two supply vents in the model. Both have the same curve, they ramp up from T=0 and T=5 linearly. 
The first vent is linked to regular time, the second is linked to Timer2 (additional timer).
When the obstruction that both vents are attached disappears between 30 and 40 s, the first vent starts ramping up again, whereas the second vent follows the original ramp and does not ramp up. 

Because of this difference I needed an external TIME device for certain control logics. 



![image](https://user-images.githubusercontent.com/26166281/234026515-353a4c72-9508-48f4-9be5-1b01e87e2607.png)

Pyrosim file
[timer2.zip](https://github.com/firemodels/fds/files/11311444/timer2.zip)

```
&HEAD CHID='timer2'/
&TIME T_END=70.0/
&DUMP DT_DEVC=0.1, DT_SLCF=1.0/

&MESH ID='Mesh01', IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&RAMP ID='CTRL_obst_RAMP', T=-5.25, F=-1.0/
&RAMP ID='CTRL_obst_RAMP', T=-4.75, F=1.0/
&RAMP ID='CTRL_obst_RAMP', T=29.75, F=1.0/
&RAMP ID='CTRL_obst_RAMP', T=30.25, F=-1.0/
&RAMP ID='CTRL_obst_RAMP', T=39.75, F=-1.0/
&RAMP ID='CTRL_obst_RAMP', T=40.25, F=1.0/
&CTRL ID='CTRL_obst', FUNCTION_TYPE='CUSTOM', RAMP_ID='CTRL_obst_RAMP', LATCH=.FALSE., INPUT_ID='TIME'/
&DEVC ID='Supply1_vol', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=0.0,0.4,0.1,0.1,0.0,1.0/
&DEVC ID='Supply2_vol', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=0.6,1.0,0.1,0.1,0.0,1.0/
&DEVC ID='Timer2', QUANTITY='TIME', XYZ=0.5,0.5,0.5/
&DEVC ID='TIME', QUANTITY='TIME', XYZ=0.0,0.0,0.0/

&SURF ID='supply',
      RGB=26,204,26,
      VEL=-1.0,
      RAMP_V='supply_RAMP_V'/
&RAMP ID='supply_RAMP_V', T=0.0, F=0.0/
&RAMP ID='supply_RAMP_V', T=5.0, F=1.0/
&SURF ID='supply2',
      RGB=26,47,97,
      VEL=-1.0,
      RAMP_V='supply2_RAMP_V'/
&RAMP ID='supply2_RAMP_V', T=0.0, F=0.0, DEVC_ID='Timer2'/
&RAMP ID='supply2_RAMP_V', T=5.0, F=1.0/

&OBST ID='Obstruction', XB=0.0,1.0,0.0,0.1,0.0,1.0, CTRL_ID='CTRL_obst'/ 

&VENT ID='open', SURF_ID='OPEN', XB=0.0,1.0,1.0,1.0,0.0,1.0/ 
&VENT ID='supply1_Timer', SURF_ID='supply', XB=0.0,0.4,0.1,0.1,0.0,1.0/ 
&VENT ID='supply2_Timer2', SURF_ID='supply2', XB=0.6,1.0,0.1,0.1,0.0,1.0/ 

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice', PBZ=0.5/


&TAIL /
```

**Comment by johodges** [comment]
what version of FDS are you using? setting OUTPUT=.TRUE. on a timer line works for me in 6.8

**Comment by Er9y714** [comment]
I forgot to say, I use 6.7.9

**Comment by mcgratta** [comment]
```
      ! Don't print out clocks

      IF (QUANTITY=='TIME' .AND. NO_UPDATE_DEVC_ID=='null' .AND. NO_UPDATE_CTRL_ID=='null' ) OUTPUT = .FALSE.
```
FDS disregards the `OUTPUT` flag if the `QUANTITY` is `TIME`. What I am trying to figure out is why you need multiple `DEVC`s with `TIME`. Both produce the same result.

**Comment by Er9y714** [comment]
I tested the same case with FDS 6.8.0 and OUTPUT=.TRUE. on the DEVC line however I still do not see the output in device file. 

> what version of FDS are you using? setting OUTPUT=.TRUE. on a timer line works for me in 6.8

**Comment by johodges** [comment]
In the cone scaling analysis I like to freeze the time at ignition and output that. In your case you can use the NO_UPDATE_DEVC_ID to force FDS to output it, and just don't apply a set point to the target device. Update your two devices to:

&DEVC ID='Timer2', QUANTITY='TIME', XYZ=0.5,0.5,0.5, OUTPUT=.TRUE., NO_UPDATE_DEVC_ID='TIME', /
&DEVC ID='TIME', QUANTITY='TIME', XYZ=0.0,0.0,0.0, /

That will force Timer2 to be stored in the devc.

**Comment by Er9y714** [comment]
> 

That works 👍  Thanks!
