### ISSUE TITLE
Error: Problem with WIND Line

### ISSUE THREAD

**Issue by ranhuan22** [firemodels/fds#11789]
Hello,

I tried to simulate the wind profile, however, it shows "ERROR: Problem with WIND line".

Could you help me to check the wind profile input?

&HEAD CHID='17C25'/
&TIME T_END=200.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25, SMOKE3D=.FALSE./
&MISC TMPA=17.0, SIMULATION_MODE='LES'/
&WIND SPEED=1., RAMP_SPEED_Z='spd', RAMP_DIRECTION_Z='dir' /

&RAMP ID='dir', Z=   0, F=180 /
&RAMP ID='dir', Z=   0.6, F=180 /

&RAMP ID='spd', Z=   0, F=1.0 /
&RAMP ID='spd', Z= 0.2, F=1.5 /
&RAMP ID='spd', Z= 0.6, F=1.8 /

&MESH ID='Model-01-02-01-01-01-01-01', IJK=80,20,20, XB=-0.1,0.1,-0.15,-0.1,0.0,0.05/
&MESH ID='Model-01-02-01-01-01-01-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.15,-0.1,0.05,0.1/
&MESH ID='Model-01-02-01-01-01-01-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.15,-0.1,0.1,0.15/
&MESH ID='Model-01-02-01-01-01-01-02-02-02', IJK=80,20,20, XB=-0.1,0.1,-0.15,-0.1,0.15,0.2/
&MESH ID='Model-01-02-01-01-01-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.1,-0.05,0.0,0.05/
&MESH ID='Model-01-02-01-01-01-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.1,-0.05,0.05,0.1/
&MESH ID='Model-01-02-01-01-01-02-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.1,-0.05,0.1,0.15/
&MESH ID='Model-01-02-01-01-01-02-02-02-02', IJK=80,20,20, XB=-0.1,0.1,-0.1,-0.05,0.15,0.2/
&MESH ID='Model-01-02-01-01-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.05,-1.686151E-15,0.0,0.05/
&MESH ID='Model-01-02-01-01-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.05,-1.686151E-15,0.05,0.1/
&MESH ID='Model-01-02-01-01-02-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-0.05,-1.686151E-15,0.1,0.15/
&MESH ID='Model-01-02-01-01-02-02-02-02', IJK=80,20,20, XB=-0.1,0.1,-0.05,-1.686151E-15,0.15,0.2/
&MESH ID='Model-01-02-01-02-01', IJK=80,20,20, XB=-0.1,0.1,-1.665335E-15,0.05,0.0,0.05/
&MESH ID='Model-01-02-01-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-1.665335E-15,0.05,0.05,0.1/
&MESH ID='Model-01-02-01-02-02-02-01', IJK=80,20,20, XB=-0.1,0.1,-1.665335E-15,0.05,0.1,0.15/
&MESH ID='Model-01-02-01-02-02-02-02', IJK=80,20,20, XB=-0.1,0.1,-1.665335E-15,0.05,0.15,0.2/
&MESH ID='left-01-01-01', IJK=20,20,40, XB=0.1,0.2,-0.15,-0.05,0.0,0.2/
&MESH ID='left-01-01-02', IJK=20,20,40, XB=0.1,0.2,-0.05,0.05,0.0,0.2/
&MESH ID='top-01', IJK=40,40,20, XB=-0.1,0.1,-0.15,0.05,0.2,0.3/
&MESH ID='right-01-02-01', IJK=20,20,40, XB=-0.2,-0.1,-0.15,-0.05,0.0,0.2/
&MESH ID='right-01-02-02', IJK=20,20,40, XB=-0.2,-0.1,-0.05,0.05,0.0,0.2/
&MESH ID='Front-02-01-01-02', IJK=40,10,40, XB=-0.1,0.1,-0.2,-0.15,0.0,0.2/
&MESH ID='Back-01-01-01-02', IJK=40,10,40, XB=-0.1,0.1,0.05,0.1,0.0,0.2/
&MESH ID='Front-02-01-01-01', IJK=45,5,20, XB=-0.55,-0.1,-0.2,-0.15,0.0,0.2/
&MESH ID='Front-02-01-02', IJK=45,5,20, XB=0.1,0.55,-0.2,-0.15,0.0,0.2/
&MESH ID='Back-01-01-01-01', IJK=45,5,20, XB=-0.55,-0.1,0.05,0.1,0.0,0.2/
&MESH ID='Back-01-01-02', IJK=45,5,20, XB=0.1,0.55,0.05,0.1,0.0,0.2/
&MESH ID='Front-01-01', IJK=55,15,30, XB=-0.55,0.55,-0.6,-0.3,0.0,0.6/
&MESH ID='Front-01-02-01-01', IJK=110,5,30, XB=-0.55,0.55,-0.3,-0.25,0.0,0.3/
&MESH ID='Front-01-02-01-02', IJK=110,5,30, XB=-0.55,0.55,-0.25,-0.2,0.0,0.3/
&MESH ID='Front-01-02-02-01', IJK=110,5,30, XB=-0.55,0.55,-0.3,-0.25,0.3,0.6/
&MESH ID='Front-01-02-02-02', IJK=110,5,30, XB=-0.55,0.55,-0.25,-0.2,0.3,0.6/
&MESH ID='left-01-02', IJK=35,20,20, XB=0.2,0.55,-0.15,0.05,0.0,0.2/
&MESH ID='left-02', IJK=45,20,40, XB=0.1,0.55,-0.15,0.05,0.2,0.6/
&MESH ID='top-02', IJK=20,20,30, XB=-0.1,0.1,-0.15,0.05,0.3,0.6/
&MESH ID='right-01-01', IJK=35,20,20, XB=-0.55,-0.2,-0.15,0.05,0.0,0.2/
&MESH ID='right-02', IJK=45,20,40, XB=-0.55,-0.1,-0.15,0.05,0.2,0.6/
&MESH ID='Back-02-01-01-01', IJK=110,5,30, XB=-0.55,0.55,0.1,0.15,0.0,0.3/
&MESH ID='Back-02-01-01-02', IJK=110,5,30, XB=-0.55,0.55,0.15,0.2,0.0,0.3/
&MESH ID='Back-02-01-02-01', IJK=110,5,30, XB=-0.55,0.55,0.1,0.15,0.3,0.6/
&MESH ID='Back-02-01-02-02', IJK=110,5,30, XB=-0.55,0.55,0.15,0.2,0.3,0.6/
&MESH ID='Back-02-02-01-01', IJK=55,15,30, XB=-0.55,0.55,0.2,0.5,0.0,0.6/
&MESH ID='Back-02-02-01-02', IJK=55,15,30, XB=-0.55,0.55,0.5,0.8,0.0,0.6/
&MESH ID='Back-02-02-02-01-01', IJK=55,10,30, XB=-0.55,0.55,0.8,1.0,0.0,0.6/
&MESH ID='Back-02-02-02-01-02', IJK=55,10,30, XB=-0.55,0.55,1.0,1.2,0.0,0.6/
&MESH ID='Back-02-02-02-02', IJK=55,15,30, XB=-0.55,0.55,1.2,1.5,0.0,0.6/
&MESH ID='Front-02-02-01-01-merged', IJK=110,5,40, XB=-0.55,0.55,-0.2,-0.15,0.2,0.6/
&MESH ID='Back-01-02-01-01-merged', IJK=110,5,40, XB=-0.55,0.55,0.05,0.1,0.2,0.6/

&SURF ID='Heater',
      RGB=255,20,15,
      TMP_FRONT=17.0/

&OBST ID='Obstruction', XB=-0.05,0.05,-0.1,0.0,0.0,0.1, SURF_ID6='INERT','INERT','INERT','Heater','INERT','INERT'/ 

&VENT ID='Mesh Vent: Mesh [XMAX]', SURF_ID='OPEN', XB=0.55,0.55,-0.6,1.5,0.0,0.6/ 
&VENT ID='Mesh Vent: Mesh [XMIN]', SURF_ID='OPEN', XB=-0.55,-0.55,-0.6,1.5,0.0,0.6/ 
&VENT ID='Mesh Vent: Mesh [YMAX]', SURF_ID='OPEN', XB=-0.55,0.55,1.5,1.5,0.0,0.6/ 
&VENT ID='Mesh Vent: Mesh [YMIN]', SURF_ID='OPEN', XB=-0.55,0.55,-0.6,-0.6,0.0,0.6/ 
&VENT ID='Mesh Vent: Mesh [ZMAX]', SURF_ID='OPEN', XB=-0.55,0.55,-0.6,1.5,0.6,0.6/ 
&VENT ID='Mesh Vent: Mesh [ZMIN]', SURF_ID='INERT', XB=-0.55,0.55,-0.6,1.5,0.0,0.0/ 

&SLCF QUANTITY='TEMPERATURE', ID='X = 0.0 m: Temperature', PBX=0.0/
&SLCF QUANTITY='VISCOSITY', ID='X = 0.0 m: Viscosity', PBX=0.0/
&SLCF QUANTITY='PRESSURE', ID='X = 0.0 m: Pressure', PBX=0.0/
&SLCF QUANTITY='U-VELOCITY', ID='X = 0.0 m: U-Velocity', PBX=0.0/
&SLCF QUANTITY='V-VELOCITY', ID='X = 0.0 m: V-Velocity', PBX=0.0/
&SLCF QUANTITY='W-VELOCITY', ID='X = 0.0 m: W-Velocity', PBX=0.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='X = 0.0 m: Velocity', PBX=0.0/

&DEVC ID='W-Velocity_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.1,0.1,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.1,0.1,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.1,0.1,0.0,0.6, POINTS=61/
&DEVC ID='Temperature_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.1,0.1,0.0,0.6, POINTS=61/
&DEVC ID='Pressure_STEADY STATE', QUANTITY='PRESSURE', XBP=0.0,0.0,0.1,0.1,0.0,0.6, POINTS=61/
&DEVC ID='Viscosity_STEADY STATE', QUANTITY='VISCOSITY', XBP=0.0,0.0,0.1,0.1,0.0,0.6, POINTS=61/
&DEVC ID='Viscosity01_STEADY STATE', QUANTITY='VISCOSITY', XBP=0.0,0.0,0.01,0.01,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity01_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.01,0.01,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity01_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.01,0.01,0.0,0.6, POINTS=61/
&DEVC ID='Temperature01_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.01,0.01,0.0,0.6, POINTS=61/
&DEVC ID='Pressure01_STEADY STATE', QUANTITY='PRESSURE', XBP=0.0,0.0,0.01,0.01,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity01_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.01,0.01,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity02_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.02,0.02,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity02_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.02,0.02,0.0,0.6, POINTS=61/
&DEVC ID='Temperature02_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.02,0.02,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity02_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.02,0.02,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity03_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.03,0.03,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity03_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.03,0.03,0.0,0.6, POINTS=61/
&DEVC ID='Temperature03_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.03,0.03,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity03_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.03,0.03,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity09_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.09,0.09,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity09_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.09,0.09,0.0,0.6, POINTS=61/
&DEVC ID='Temperature09_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.09,0.09,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity09_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.09,0.09,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity05_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.05,0.05,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity05_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.05,0.05,0.0,0.6, POINTS=61/
&DEVC ID='Temperature05_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.05,0.05,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity05_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.05,0.05,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity12_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.12,0.12,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity12_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.12,0.12,0.0,0.6, POINTS=61/
&DEVC ID='Temperature12_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.12,0.12,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity12_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.12,0.12,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity07_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.07,0.07,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity07_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.07,0.07,0.0,0.6, POINTS=61/
&DEVC ID='Temperature07_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.07,0.07,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity07_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.07,0.07,0.0,0.6, POINTS=61/
&DEVC ID='U-Velocity15_STEADY STATE', QUANTITY='U-VELOCITY', XBP=0.0,0.0,0.15,0.15,0.0,0.6, POINTS=61/
&DEVC ID='V-Velocity15_STEADY STATE', QUANTITY='V-VELOCITY', XBP=0.0,0.0,0.15,0.15,0.0,0.6, POINTS=61/
&DEVC ID='Temperature15_STEADY STATE', QUANTITY='TEMPERATURE', XBP=0.0,0.0,0.15,0.15,0.0,0.6, POINTS=61/
&DEVC ID='W-Velocity15_STEADY STATE', QUANTITY='W-VELOCITY', XBP=0.0,0.0,0.15,0.15,0.0,0.6, POINTS=61/
&DEVC ID='Wind profile_STEADY STATE', QUANTITY='VELOCITY', XBP=0.0,0.0,-0.55,-0.55,0.0,0.6, POINTS=61/

&TAIL /

**Comment by ericvmueller** [comment]
What version are you using? Running with the latest release (6.8.0) it appears to start without any error.

![image](https://user-images.githubusercontent.com/13366803/235553613-aaff43df-8e25-4bc6-88c8-970de4b96f76.png)

**Comment by ranhuan22** [comment]
Thank you so much. 

I was using the version 6.7.1 in the cluster. Is there any revision in this version?

Also, I will try the new version.

**Comment by ericvmueller** [comment]
`RAMP_SPEED_Z` and `RAMP_DIRECTION_Z` were added after version 6.7.7, so the best thing is to use the newest version. 

If you can’t for some reason you could try:
`&WIND U0=0., V0=1., RAMP_V0_Z='spd'/`
…but ever since version 6.7.7, U0 and V0 only set initial conditions and do not drive the flow at the boundaries, as is described in the guide. So keep that in mind if/when you update

**Comment by ranhuan22** [comment]
Hello, Eric

Great! Thank you for the information.

Now I understand what happened in the Version 6.7.1. I tried both in Version 6.7.1 (U0 V0) and version 6.8.0 (RAMP_SPEED_Z).

Both of them are working well! Now I can validate the FDS through our wind tunnel tests.

Thank you so much!
