### ISSUE TITLE
Backing condition for GEOM

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11781]
In looking at the case discussed here: 
https://github.com/firemodels/fds/discussions/11768
the heat transfers to the other side of this canyon in an unexpected way. 

![image](https://user-images.githubusercontent.com/13366803/235226098-d9ec0ba4-9a3f-4ea2-b20e-6e07e57dbecf.png)

BACKING='VOID' needs to be set to avoid the cell taking back face conditions for heat transfer from the other side of the geometry. I think this is different from the behavior one would expect from OBST, so maybe we need a warning or some logic to handle surfaces with a prescribed THICKNESS much less than the geometry thickness.

The current behavior also depends on meshing and whether the original heat source is in the same mesh.

[canyon.txt](https://github.com/firemodels/fds/files/11356345/canyon.txt)

**Comment by marcosvanella** [comment]
Thanks Eric.

**Comment by marcosvanella** [comment]
Eric, try the case and close the issue if working. Thanks.

**Comment by ericvmueller** [comment]
Okay will do

**Comment by ericvmueller** [comment]
Looks good now without having to specify the `BACKING`. Thanks Marcos!


![image](https://github.com/firemodels/fds/assets/13366803/a06c9d2f-dbec-4ce8-86d1-491ff2d2af10)
