### ISSUE TITLE
Low frequency flow oscillations in simple case.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#11814]
Hello,

I was making a simple test case to demonstrate some basic features of FDS, and found that in the 'steady-state' there were flow oscillations that repeat every 20 seconds or so during the simulation.

![restart_test_velo](https://github.com/firemodels/fds/assets/12104446/223931c8-8ee2-40f8-8c29-e334644ee39c)

This also impacts the temperature field, as the pulsing effect moves the heat past the device with a similar frequency.

![restart_test_temp](https://github.com/firemodels/fds/assets/12104446/4a3b3560-e6c7-463c-b6a7-bf89352b8a14)

The time steps in the simulation seem fairly constant.

![restart_test_steps](https://github.com/firemodels/fds/assets/12104446/8fbd696d-a500-4e95-8f14-3625c9e90fc0)

Is this something in the solver, or something I should change in the pressure solver parameters?

Here is the FDS file I was using.

[restart_test.zip](https://github.com/firemodels/fds/files/11446471/restart_test.zip)

**Comment by drjfloyd** [comment]
Did you attach the correct file? The file you attached has T_END=0.001.

**Comment by drjfloyd** [comment]
The file you attached is very low resolution. Flow is driven by pressure. Pressure inside the domain rises and flow can go out the openings. With so few grid cells I suspect you overshoot pressure and just set up a ringing solution where pressure rises, flow increases, pressure drops, flow decreases, etc. You don't have grid cells over the vents to allow for much of any spatial change in the flow at the OPEN vents. I'd guess the periodicity is some function of the supply flow, box volume, and outflow area.  I suspect that as you increase resolution this behavior will change.

**Comment by bwklein** [comment]
That all makes sense, and yes it is the correct file, I was showing
something else about set up runs and forgot to change the T_END back to
1000.

I expect this also has to do with 2 separate open vents for outgoing flows
from the supply surface.

I think I expected a constant supply to eventually stabilize the outflow
and the oscillating to diminish over time.

I'll play with some variables and see what changes.

Thank you for taking a look.

- Bryan
