### ISSUE TITLE
DEVC flagged as out of mesh when center of WHOLE_DOMAIN not within a mesh

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11820]
read.f90 sets the XYZ of a DEVC flagged with DB to the center point of the extents of all meshes. If this center point is not contained within a mesh due to holes in the center of the domain, the device is thrown out by FDS and issues a warning. I put in PR https://github.com/firemodels/fds/pull/11819 to skip the mesh check for devices with DB/='null'. See attached input file for example case that issues a warning which is fixed by the PR.
[test_case_2.txt](https://github.com/firemodels/fds/files/11455846/test_case_2.txt)

**Comment by rmcdermo** [comment]
@johodges Can we close this?  Firebot passed last night with PR #11819
