### ISSUE TITLE
Instability for Tunnel with no OPEN boundary.

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#11831]
Here we use the tunnel preconditioner on a very slim tunnel with 4 meshes and get a numerical instability after the 1st timestep. It seems to be related to not having an OPEN boundary (but an hvac connection to the open atmosphere). If I comment all vent/hvac lines and uncomment the open end VENT:

`&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=1600.0,1600.0,0.0,1.75,0.0,2.75/`

the code runs with the preconditioner. 
Might be that the 1D discretization matrix is undetermined (single zero eigenvalue, undetermined constant in the solution). One way to deal with this is: set the mean of the RHS to zero, make one of the unknowns 0, solve for the rest and then compute and subrtract the mean of the solution (zero mean of the soln).

```
&HEAD CHID='test'/
&TIME T_END=3600.0/
&RADI RADIATION=.FALSE./
&PRES TUNNEL_PRECONDITIONER=T/

&MESH ID='MESH1', IJK=1600,7,11, XB=0.0,400.0,0.0,1.75,0.0,2.75, MPI_PROCESS=0/
&MESH ID='MESH2', IJK=1600,7,11, XB=400.0,800.0,0.0,1.75,0.0,2.75, MPI_PROCESS=1/
&MESH ID='MESH3', IJK=1600,7,11, XB=800.0,1200.0,0.0,1.75,0.0,2.75, MPI_PROCESS=2/
&MESH ID='MESH4', IJK=1600,7,11, XB=1200.0,1600.0,0.0,1.75,0.0,2.75, MPI_PROCESS=3/

#&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=1600.0,1600.0,0.0,1.75,0.0,2.75/

## Hvac to Ambient in tunnel end.
&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='HVAC', XB=1600.0,1600.0,0.0,1.75,0.0,2.75/
&HVAC ID='INSIDE1',TYPE_ID='NODE',DUCT_ID='OVERPRESSURE1',VENT_ID='Mesh Vent: MESH [XMAX]'/
&HVAC ID='OUTSIDE1',TYPE_ID='NODE',DUCT_ID='OVERPRESSURE1',XYZ=1,1,25,AMBIENT=.TRUE./
&HVAC ID='OVERPRESSURE1',TYPE_ID='DUCT',NODE_ID='INSIDE1','OUTSIDE1',AREA=0.5,LENGTH=25.0,ROUGHNESS=0.01/

&TAIL /
```

**Comment by mcgratta** [comment]
I fixed the problem of having two Neumann boundaries in the tunnel. But I now get a numerical instability after approximately 4 s due to something related to pressure in the tunnel and the duct getting out of sync. This occurs even if I use one mesh, so I think it is more than just the multiple mesh pressure issue. This is the case I am considering:
```
&HEAD CHID='test'/
&TIME T_END=10.0/
&RADI RADIATION=.FALSE./
&PRES TUNNEL_PRECONDITIONER=T/

&MESH ID='MESH1', IJK=1600,7,11, XB=0.0,400.0,0.0,1.75,0.0,2.75, MPI_PROCESS=0/
&MESH ID='MESH2', IJK=1600,7,11, XB=400.0,800.0,0.0,1.75,0.0,2.75, MPI_PROCESS=1/
&MESH ID='MESH3', IJK=1600,7,11, XB=800.0,1200.0,0.0,1.75,0.0,2.75, MPI_PROCESS=2/
&MESH ID='MESH4', IJK=1600,7,11, XB=1200.0,1600.0,0.0,1.75,0.0,2.75, MPI_PROCESS=3/

## Hvac to Ambient in tunnel end.
&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='HVAC', XB=1600.0,1600.0,0.0,1.75,0.0,2.75/
&HVAC ID='INSIDE1',TYPE_ID='NODE',DUCT_ID='OVERPRESSURE1',VENT_ID='Mesh Vent: MESH [XMAX]'/
&HVAC ID='OUTSIDE1',TYPE_ID='NODE',DUCT_ID='OVERPRESSURE1',XYZ=1,1,25,AMBIENT=.TRUE./
&HVAC ID='OVERPRESSURE1',TYPE_ID='DUCT',NODE_ID='INSIDE1','OUTSIDE1',AREA=0.5,LENGTH=25.0,ROUGHNESS=0.01/

&DEVC ID='p1', QUANTITY='NODE PRESSURE', NODE_ID='INSIDE1' /
&DEVC ID='p2', QUANTITY='NODE PRESSURE', NODE_ID='OUTSIDE1' /
&DEVC ID='Vdot', QUANTITY='DUCT MASS FLOW', DUCT_ID='OVERPRESSURE1' /

&TAIL /
```

**Comment by mcgratta** [comment]
I think the problem is the the HVAC machinery takes its node pressure (`INSIDE1`) from the FDS pressure field. But in this case, all pressure BCs are Neumann, and the solution of the FDS gas phase pressure equation is unique up to a constant. The pressure solver (Crayfishpak) sets the constant such that the average value of $H=u^2/2+p/rho$ is zero. Thus, the pressure field for the FDS solver does not account for the HVAC node locations. That is because only $\nabla H$ matters in the FDS gas phase solution.

Jason, can you confirm (or deny) my logic.

**Comment by drjfloyd** [comment]
The HVAC pressure solver and the Crayfishpak solver are not directly coupled. HVAC uses the pressure solution from Crayfishpak and determines the duct velocities which then define the VENT velocities used in the next pressure solution. In cases where the HVAC VENT is very large there can be bad feedback. The HVAC solver was developed around the idea that it represents an HVAC system in a building where the inlets and outlets are a small fraction of the wall of a room they are in. It was not developed with the intent of supporting 3D to 1D for a tunnel. People have tried to use it that way, but it has not always been successful. In this case if I set HVAC_PRES_RELAX=0.5 on MISC it runs to completion (Interestingly if I turn off the preconditioner, it also runs to completion.). HVAC_PRES_RELAX smooths the pressure at an HVAC VENT and in this case helps dampen the feed back between HVAC and the pressure solver.
