### ISSUE TITLE
Logical function seems not disabling particles ignitor

### ISSUE THREAD

**Issue by PatricioValdes** [firemodels/fds#11833]
Hi FDS users and developers,

I am trying to disable ignitor particles after 7 seconds of starting the simulation, but if I check a temperature profile after 60 seconds and even after sprinklers discharge, the particles seems to still be active with a temperature thats allows the reignition of the material.

I have tried by disabling the particles in function of a sprinkler activated, time, and nothing seems to work. I hope you can give a look to the FDS file and maybe give me a help.

In the attached screen shot you can see that at 75 seconds of the simulations and even after sprinklers discharge, the particles still have a temperature higher than 250°C.

thanks
![Screenshot 2023-05-16 003636](https://github.com/firemodels/fds/assets/133715805/42507ee1-e0f8-4c2c-8014-dd673d170ae5)

[ES-05-A.fds.txt](https://github.com/firemodels/fds/files/11482421/ES-05-A.fds.txt)

**Comment by drjfloyd** [comment]
DEVC_ID or CTRL_ID on &PART are used to define when particles are emitted from a SURF.  If you just want the particles to be around for 7 s, you can set AGE=7 on &PART.  AGE defines the lifetime of a particle from when it is created.
