### ISSUE TITLE
FDS can't see my VENTS or stops at reading phase

### ISSUE THREAD

**Issue by FabiaSchirinzi** [firemodels/fds#11840]
I have a problem with the software, it keeps giving me the error that it can't find my inlet and outlet VENTS. Then, trying to change some parameters, sometimes the software stops at the reading stage. After inserting IOR in the VENTS (inserting it instead of UVW), FDS is blocked in the phase of:
"Reading FDS input file...". 

Looking at the geometry, FDS inserts my vents, so I can't understand why it isn't working.

**Comment by FabiaSchirinzi** [comment]
Thank you for your help. I applied almost everything (I would like to fill the holes with a different material that I have to decide), but, when I start the simulation, the programme gives me "ERROR: numerical instability", without even starting the time steps. How is it possible that, unlike you, it doesn't work with me?

[Uploading TEXT2BIS.txt…]()

**Comment by drjfloyd** [comment]
Are you running the current release (6.8.0)?

**Comment by FabiaSchirinzi** [comment]
I am using 6.7.6
Do I have to download the last release?

**Comment by drjfloyd** [comment]
Yes. Please download the last release.

**Comment by FabiaSchirinzi** [comment]
It works, thank you so much!
