### ISSUE TITLE
Heat Flux Device not working

### ISSUE THREAD

**Issue by MasterJLM** [firemodels/fds#11843]
Hello,

in continuation to this thread...

https://groups.google.com/g/fds-smv/c/8W4iK2g5HPM

I 'm opening this issue as I believe something is not right. Per the last recommendation in the above thread, playing with the orientation of the particle did not help. There were devices affected by this (e.g. some higher FED values, expected) but the device measuring the 'Radiative Heat Flux Gas' (RHFG) persists on reporting zero only throughout the simulation (apart from a very short time period at the beginning).

Attached is my case (note, this is only made for test purposes and getting familiar with FED measurements) where an occupant is traveling from a point far from the fire appraches, gets in the fire room, walks a bit and then gets out to a staircase. During the entire path, &DEVC of RHFG remains at zero.

In addition, the &DEVC called 'RAD-dt' reports back a fixed value of 0.012531328 which is not expected. The calculation is performed using equation 63.43 of SFPE HB, 5th edition and depended on the RHFG DEVC (the graph below is of this equation).

![image](https://github.com/firemodels/fds/assets/40736171/2b5cc2bc-fa2f-4a4a-86c8-5edc4a73b724)

![image](https://github.com/firemodels/fds/assets/40736171/a2e9019c-da54-4765-bec6-ff33b8e13af5)

[Condo.txt](https://github.com/firemodels/fds/files/11524053/Condo.txt)

Any help on this deeply appreciated.

D D

**Comment by MasterJLM** [comment]
Sorry, I forgot to mention, this is on v6.8.0.

**Comment by drjfloyd** [comment]
One issue is in the beginning the particle is in ambient conditions; however, there is always a little numerical error in the solver. If you look at the devc file you will see the RHF goes ever so slightly negative (-1E-7 kW/m2). Raising a negative value to a fractional power gives a complex result which results in a N/A value being stored in the real number. This is giving the weird constant behavior at the start.  Change the CTRL sequence to this instead. This will keep the RHF always positive. The CONSTANT is small enough that the time in minutes is a huge number and won't screw up the integration.

&CTRL ID='RAD_Step0', FUNCTION_TYPE='MAX', INPUT_ID='RHF','CONSTANT', CONSTANT=0.0001 /
&CTRL ID='RAD_Step1', FUNCTION_TYPE='POWER', INPUT_ID='RAD-Step0','CONSTANT', CONSTANT=1.3334 /

But that doesn't solve everything. Will need to spend some more time with this.

**Comment by drjfloyd** [comment]
@mcgratta 

The following simple case defines two PART with the same SURF_ID and opposite ORIENTATION. One of each are placed in the same location in a box with a fire. Four DEVC are defined: two with RADIATIVE HEAT FLUX and tied to the PART INIT lines, and two with RADIATIVE HEAT FLUX GAS that use the same XYZ and ORIENTATION as the particles. I would expect that the two pairs of devices be the same but the PART versions have zero heat flux.

&HEAD CHID='part_hf'/

&MESH XB=0,2,0,2,0,2,IJK=20,20,20,/

&TIME T_END=1/

&SURF ID='FIRE',HRRPUA=1000,COLOR='RED'/
&REAC FUEL='PROPANE',SOOT_YIELD=0.05/

&VENT XB=0.6,1.4,0.6,1.4,0.0,0.0,SURF_ID='FIRE'/

&SURF ID='PART',GEOMETRY='SPHERICAL',THICKNESS=0.01/

&PART ID='P1',SURF_ID='PART',STATIC=T,ORIENTATION=0,-1,0,STATIC=T/
&PART ID='P2',SURF_ID='PART',STATIC=T,ORIENTATION=0, 1,0,STATIC=T/

&INIT ID='P1', XYZ=1,1.8,1,PART_ID='P1',N_PARTICLES=1/
&INIT ID='P2', XYZ=1,1.8,1,PART_ID='P2',N_PARTICLES=1/

&DEVC QUANTITY='RADIATIVE HEAT FLUX',INIT_ID='P1',ID='RHFP1'/
&DEVC QUANTITY='RADIATIVE HEAT FLUX',INIT_ID='P2',ID='RHFP2'/

&DEVC QUANTITY='RADIATIVE HEAT FLUX GAS',XYZ=1,1.8,1,ORIENTATION=0,-1,0,ID='RHFG1'/
&DEVC QUANTITY='RADIATIVE HEAT FLUX GAS',XYZ=1,1.8,1,ORIENTATION=0, 1,0,ID='RHFG2'/

**Comment by mcgratta** [comment]
Short answer is that the particles need to be made of something and have a MATL_ID. I suspect because they are not THERMALLY_THICK they are being excluded from some loop. I'll have to dig in more and see if this is something we want to fix. Without the "_GAS" attribute in the name, or thermally-thick, there is no need to compute a heat flux to these particles.

**Comment by drjfloyd** [comment]
If I change the DEVC with INIT_ID to RADIATIVE HEAT FLUX GAS, I get a non-zero result but it doesn't match the last two.

If I had a solid wall cell with just TMP_FRONT and not thermaly thick, I could still measure a heat flux to it. I think if we had a solid particle with a surface area, that one should also be able to see its heat flux. We use hot particles for ignitors and we should be able to measure the convective and radiative heat they are adding to the domain.

In the orignal case, the particle is representing a person's head as they move about the domain where the goal is to see if the heat flux exceeds an FED. I think this is something we should be able to do.

**Comment by drjfloyd** [comment]
@MasterJLM 

Try these lines.  The radiative flux doesn't depend on the surface size. Making the particle small means it won't be acting as a heat sink. The high density, conductivity, specific heat, and thickness make the particle thermally thick so it invokes the logic to compute the incident radiaiton but won't actually heat the particle up.

&MATL ID='MY MAT',DENSITY=10000,CONDUCTIVITY=1000,SPECIFIC_HEAT=1000,EMISSIVITY=1/
&SURF ID='OCCUPANT', LENGTH=0.001, THICKNESS(1:1)= 1, WIDTH=0.001, MATL_ID='MY MAT'  /

**Comment by MasterJLM** [comment]
Guys, deeply appreciated all recommendations and comments on this.

Jason, I tried with the lines of your last post. Unfortunately, I keep seeing the RHF Gas DEVC stuck to zero no matter how close to the fire the particle comes. Also, at the nearest point the orientation is set towards the fire. Are you getting different results?

Using a common DEVC of RHF Gas with a fixed XYZ seems to be working well, reporting positive values. How come this DEVC can measure non-zero values where it is not related to any size and any material properties? My guesses are, there must be an issue between the moving particle or/and the (re)initialization (INIT) on each step and the DEVC RHF Gas.

**Comment by drjfloyd** [comment]
RHF Gas with XYZ invokes logic that creates a special class of particles that triggers a storing of the radiative flux in the radiation solver. In the specific set of inputs you have, there isn't a logical path in the code that results in a heat flux being stored for the particle. 

I've attached the version of your input that I have run with 6.8.0 on my lapotp. This adds the changed SURF+MATL and the additional CTRL function mentioned earlier. Otherwise it is the same file (other than changing to four meshes as my laptop doesn't have 16 P-cores).  

![image](https://github.com/firemodels/fds/assets/12799217/7e453939-0e57-4862-9193-1bb355bb766e)

[Condo.fds.txt](https://github.com/firemodels/fds/files/11525649/Condo.fds.txt)

**Comment by MasterJLM** [comment]
Thanks Doc, appreciated. I was trying as

&DEVC ID='RHF', QUANTITY='RADIATIVE HEAT FLUX GAS', INIT_ID='Occupant 1' /
not as
&DEVC ID='RHF', QUANTITY='RADIATIVE HEAT FLUX', INIT_ID='Occupant 1' /

I though the particle is not like obstruction or end of domain. Now is seems to be working measuring other than zero.

I thank you both for taking the time.

**Comment by drjfloyd** [comment]
Reopening, as I think we need the ability to get a heat flux to a solid particle with a TMP_FRONT.

**Comment by drjfloyd** [comment]
That does not really represent a human body.  Your "body" is starting off at ambient temperature, rather than normal body temperature. It lacks the an internal heat source to maintain that temperature in ambient conditions. It does not account for blood perfusion that moves heat from exposed to unexposed areas. There is no evaporative cooling or other homeostasis responses for trying to maintain skin temperature.

**Comment by MasterJLM** [comment]
nor is the human body a monolith taking down the path of minecraft. Your comments are well understood, I just though a bit of a better heat exchange would be somewhat better, maybe not... I don't think I can go any further than that.
Thanks again for the recommendations.
