### ISSUE TITLE
Numerical Instability after 20s of simulation

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#11856]
Hi, 

I am attaching the FDS config file for my simulation. It stops at around 20s stating
WARNING: Maximum density,    2.663 kg/m3, clipped in Mesh 1

Could you please tell me what the problem is, in the simulation ?

Thanks in advance 
[methane_emission_fds.txt](https://github.com/firemodels/fds/files/11575641/methane_emission_fds.txt)

**Comment by drjfloyd** [comment]
My guess is it is this:

CONVECTIVE_HEAT_FLUX=-35.525452

Removing 35 kW/m2 at the ground is going to drop temperatures quickly to very low values.

**Comment by mcgratta** [comment]
In my test run of your case, the OBST is too small for the grid.

**Comment by rakyuv** [comment]
Thank you @drjfloyd and @mcgratta for your inputs. I didn't realise that the OBST was too small for the grid. I have increased it now. I get the same error as before at the same time-step. 

You are right that changing the CONVECTIVE_HEAT_FLUX makes the simulation run longer without crashing. 
But I had computed the convective_heat_flux using the Equation 18.19 . I will recheck the values and will keep you posted

**Comment by drjfloyd** [comment]
A cooling flux of -35 kW/m2 might be appropriate if you had a pool of LNG on the ground and were predicting the cooling of the ground; however, you do not have that in your simulation.  You are injecting room temperature gas and you are not predicting the cooling of the ground. A fixed cooling heat flux will keep cooling the gas in the grid cells above the ground. In reality if you had a pool of LNG you would quickly wind up with a fixed temperature sitting near the boiling point of LNG and you would not be able to sustain such rapid cooling.

**Comment by mcgratta** [comment]
Agreed. Are you sure you really want 0.035 kW/m² ? That is, did you calculate 35 W/m² ?

**Comment by rakyuv** [comment]
I understand that this convective heat flux seems unreasonable for the simulation that I'm currently running.

**Comment by rakyuv** [comment]
An update on the above. I had multiplied the obukhov length in the numerator, instead of dividing it in the denominator in the equation 18.19. My apologies for the wrong value above.

The correct computed value of convective heat flux is -0.06 kW/m^2. Does it seem unreasonable on a stable atmospheric boundary layer ?

**Comment by drjfloyd** [comment]
0.06 kW/m2 is not an unreasonable number. That would suggest a flux from single digit temperature difference between the ground and the gas. 

On SURF, a heat flux input is positive if you are heating the gas and negative if you are cooling the gas. -0.06 kW/m2 means you are removing heat from the gas. Is this what you are intending?

**Comment by rakyuv** [comment]
Thank you @drjfloyd for your answer. In the simulation the ground temperature is about 294.35 K, and the temperature at 2m is around 293.83 K. And the atmospheric boundary layer is highly stable, which is also indicated by the positive value of Obukhov Length (L). 

Thus, I can assume that I am heating the gas, with ground being warmer than the surrounding air. The reason I have negative sign is because the Obukhov length is positive, and according to Equation 18.19,  the convective heat flux becomes negative.

Could you please tell me if this is correct ?

**Comment by mcgratta** [comment]
Just try it. It is difficult to know exactly what you are doing. Run some verification cases to ensure that things are working the way you want.
