### ISSUE TITLE
Error message when modeling methanol liquid

### ISSUE THREAD

**Issue by JinZhao2023** [firemodels/fds#11861]
Hi, I am trying to model liquid spray. The calculation was fine when I
model water or benzene liquid spray. But when I try to model methanol spray. I got the following message. Will you please help me to have a look what
went wrong with methanol calculation?
 
forrtl: severe (157): Program Exception - access violation
Image PC Routine Line Source

fds_openmp.exe 00007FF675BB9CCF Unknown Unknown Unknown
fds_openmp.exe 00007FF675BAC80F Unknown Unknown Unknown
fds_openmp.exe 00007FF6753F2E52 Unknown Unknown Unknown
fds_openmp.exe 00007FF6753AFEEE Unknown Unknown Unknown
fds_openmp.exe 00007FF675D25AA0 Unknown Unknown Unknown
KERNEL32.DLL 00007FF8E1DE7614 Unknown Unknown Unknown
ntdll.dll 00007FF8E3C026A1 Unknown Unknown Unknown
[runfds.exe] subprocess exit: 157ch(url)

My input is below:
test3.fds
Generated by PyroSim - Version 2023.1.0524
May 28, 2023, 10:23:32 PM

&HEAD CHID='test3'/
&TIME T_END=250.0/
&DUMP COLUMN_DUMP_LIMIT=.TRUE., DT_PL3D=0.1, DT_RESTART=300.0, DT_SL3D=0.25, WRITE_XYZ=.TRUE./
&MISC TMPA=25.0, POROUS_FLOOR=.FALSE., PARTICLE_CFL=.TRUE./

&MESH ID='Mesh51', IJK=34,83,200, XB=-7.4,4.2,-22.4,14.6,0.0,40.0, TRNX_ID='trnx', TRNY_ID='trny'/
&TRNX ID='trnx', CC=-1.941176, PC=-1.0/ Mesh51
&TRNX ID='trnx', CC=1.470588, PC=1.0/ Mesh51
&TRNY ID='trny', CC=-17.050602, PC=-12.8/ Mesh51
&TRNY ID='trny', CC=-5.014458, PC=-2.0/ Mesh51
&TRNY ID='trny', CC=4.346988, PC=2.2/ Mesh51
&TRNY ID='trny', CC=11.033735, PC=8.2/ Mesh51

&SPEC ID='METHANOL'/

&PART ID='Particle01',
      SPEC_ID='METHANOL',
      DIAMETER=88.0,
      MONODISPERSE=.TRUE.,
      AGE=60.0,
      DENSE_VOLUME_FRACTION=0.0/

&PROP ID='SprayMod01',
      PART_ID='Particle01',
      OFFSET=0.0,
      FLOW_RATE=17.0,
      FLOW_TAU=1.0,
      PARTICLE_VELOCITY=42.8,
      SPRAY_ANGLE=1.0,1.0/
&DEVC ID='SPRK', PROP_ID='SprayMod01', XYZ=0.0,0.0,1.0, ORIENTATION=0.0,0.0,1.0, QUANTITY='TIME', SETPOINT=0.1/

&MATL ID='Material01',
      SPECIFIC_HEAT=1.0,
      CONDUCTIVITY=0.8,
      DENSITY=1000.0,
      EMISSIVITY=0.85/

&OBST ID='pipe', XB=-0.2,0.2,-0.2,0.2,0.0,1.0, SURF_ID='INERT'/ 

&VENT ID='open0', SURF_ID='OPEN', XB=-7.4,-7.4,-22.4,14.6,0.0,40.0, COLOR='INVISIBLE'/ 
&VENT ID='open', SURF_ID='OPEN', XB=4.2,4.2,-22.4,14.6,0.0,40.0, COLOR='INVISIBLE'/ 
&VENT ID='open01', SURF_ID='OPEN', XB=-7.4,4.2,-22.4,14.6,40.0,40.0, COLOR='INVISIBLE'/ 
&VENT ID='open02', SURF_ID='OPEN', XB=-7.4,4.2,-22.4,-22.4,0.0,40.0, COLOR='INVISIBLE'/ 
&VENT ID='open03', SURF_ID='OPEN', XB=-7.4,4.2,14.6,14.6,0.0,40.0, COLOR='INVISIBLE'/ 

&BNDF QUANTITY='AMPUA', PART_ID='Particle01'/
&BNDF QUANTITY='CPUA', PART_ID='Particle01'/
&BNDF QUANTITY='MPUA', PART_ID='Particle01'/
&BNDF QUANTITY='BACK WALL TEMPERATURE'/
&BNDF QUANTITY='DEPOSITION VELOCITY'/
&BNDF QUANTITY='WALL TEMPERATURE'/

&TAIL /

**Comment by mcgratta** [comment]
The species `METHANOL` is not included in the database of gases and liquids. Therefore, you have to provide
```
&SPEC ID='METHANOL', DENSITY_LIQUID=..., SPECIFIC_HEAT_LIQUID=..., MELTING_TEMPERATURE=..., VAPORIZATION_TEMPERATURE=..., HEAT_OF_VAPORIZATION=... /
```
Also, the values for `SPRAY_ANGLE` cannot be the same.

Also, you have a `&RADI` line with no entries.

**Comment by mcgratta** [comment]
Jason, after fixing the obvious problems, the case still failed with
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libpthread-2.17.s  00002B2BF89F7630  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000000855114  dump_mp_initializ        2724  dump.f90
fds_impi_intel_li  0000000000870C12  dump_mp_initializ         542  dump.f90
fds_impi_intel_li  000000000092E66B  MAIN__                    468  main.f90
fds_impi_intel_li  0000000000409B1D  Unknown               Unknown  Unknown
```
meaning the `C_P_L_BAR` was not allocated because this if statement is false
```
   LIQUID_IF: IF (CP_TEMP > 0._EB .OR. SS%TMP_MELT >= 0._EB .OR. SS%TMP_V > 0._EB .OR. SS%DENSITY_LIQUID > 0._EB .OR. &
      SS%SPECIFIC_HEAT_LIQUID > 0._EB .OR. SS%RAMP_CP_L_INDEX > 0) THEN
```
When I added a `DENSITY_LIQUID` to the `SPEC` line for `MWTHANOL`, then I was prompted to add the other properties. I'm not sure exactly how to construct the `ERROR` statement for the original case where nothing is specified. Is there a way to detect that this `SPEC` is being used for droplet evaporation and it needs these liquid properties. I could dig into more, but if you can think of an easy catch, that would prevent to set fault.

**Comment by drjfloyd** [comment]
It should have picked up the predefined liquid props for METHANOL. I'll look into it.

**Comment by drjfloyd** [comment]
When revamping the species data structures I didn't transfer over one set of liquid properties: METHANOL. That is an easy fix, I'll just copy the data from the old source.  

I'll look into the error message.

**Comment by drjfloyd** [comment]
I'll have a fix up before firebot runs again. Have an afternoon obligation to head off to.

**Comment by drjfloyd** [comment]
The next test version will have METHANOL liquid properties in it. If you update your FDS to that and fix the angle issue Kevin identified, your case should run.

**Comment by JinZhao2023** [comment]
Thanks for all the help. I think the same error also incurs to several other pre-defined species. I tested ethanol and, n-decane, both with will give out same error message.

**Comment by mcgratta** [comment]
Did you try the test version of FDS?

**Comment by drjfloyd** [comment]
If I change METHANOL to ETHANOL in your input and run with the current test version, it starts to timestep.
