### ISSUE TITLE
INIT region MASS_PER_VOLUME  -  OBSTructions in the INIT region

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11864]
Referring to  **Periodic Insertion of Particles within a Specified Volume** section in User Guide. 

Using both MASS_PER_TIME and MASS_PER_VOLUME introduce the required species into the specified INIT region. If the INIT region is partly filled with OBSTruction, the total mass introduced by INIT input is maintained by squeezing the total amount into the available gas cells.  

My question is: MASS_PER_VOLUME is simply a density. But it is based on the INIT volume not the existing gas cells. Is it possible to introduce species based on the existing gas cells so that the observed density will not change even there are some obstructions in the INIT region? If this is not possible at the moment, can it be added as a feature?

Thank you.

**Comment by mcgratta** [comment]
Anything is possible, but my worry is that this might lead to confusion. Currently, one specifies a `MASS_PER_VOLUME` and a rectangular volume defined by `XB`. I believe that FDS adds the right amount of mass to the specified volume. The adjustment of these values based on rectangular and non-rectangular obstructions would be somewhat difficult. Is this something you really think is important for which there is no work-around?

**Comment by Er9y714** [comment]
I understand. There is a workaround. If I calculate the gas volume, then I can enter the required mass amount. I was only checking if there is any alternative to that. 

My confusion came from the "volume". I was trying this INIT in a car park with lots of columns and fans (obstructions). Verification failed. Then I realized it was XB instead of gas volume (took a while).

If you are not in favor of adding this feature then of course I would not insist. I prefer a stable and simple solution instead of a complex but confusing one. 

Thank you for confirming the XB detail.

**Comment by mcgratta** [comment]
I think at the very least we can add this to the User's Guide, to emphasize that. `MASS_PER_VOLUME` is often referred to as a "bulk density" because it means that average mass of stuff in a specified volume.
