### ISSUE TITLE
Striation in GEOM boundary output near mesh boundary

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11876]
There is an odd artifact in the boundary output near mesh boundaries when a GEOM crosses it in the updated Lattimer_Tilted_Wall validation cases (fds\Validation\Lattimer_Tilted_Wall\FDS_Input_Files). The results I am showing below are from the 50kW case with 0 degree, 11 degree, and 35 degree rotations.
![image](https://github.com/firemodels/fds/assets/17127980/79e8718c-f766-4330-99e6-5d2fe12e3ea3)

The artifact still shows up when I read the data manually and visualize in an external software. See below for the 0 degree case.
![image](https://github.com/firemodels/fds/assets/17127980/074ccb4e-1973-4702-a6cc-f694840eb6e9)

**Comment by marcosvanella** [comment]
Thanks Jon, I'll try it.

**Comment by marcosvanella** [comment]
I see this with latest fds and smv sources, both node and cell centered BNDFs. I'll investigate further.
 
<img width="971" alt="Screenshot 2023-06-02 at 10 57 12 AM" src="https://github.com/firemodels/fds/assets/7450069/fe055295-f06e-4198-8976-7a72b2017310">

**Comment by marcosvanella** [comment]
Should be fixed with PR  #11883.

**Comment by johodges** [comment]
Accidentally commented on the PR instead of here. I'll run these tomorrow with the nightly build.

**Comment by marcosvanella** [comment]
This is fixed.
