### ISSUE TITLE
Smokeview not recognizing boundary data when all solids are GEOM

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11875]
The geom boundary data in the attached case does not show up as available for visualization in smokeview when both the sample and the panel are defined as GEOM in the nightly build on windows. It looks like the data is output correctly, I can still parse it manually and visualize with another software package. When I convert the sample to an OBST the boundary data shows up correctly in smokeview for both the GEOM and OBST boundary outputs.

[radiant_panel_plywood_geom_rot_cc.txt](https://github.com/firemodels/fds/files/11635517/radiant_panel_plywood_geom_rot_cc.txt)

[radiant_panel_plywood_obst_rot_cc.txt](https://github.com/firemodels/fds/files/11635533/radiant_panel_plywood_obst_rot_cc.txt)

**Comment by gforney** [comment]
I"m out of town next week.  I"ll look at it when I get back.

**Comment by marcosvanella** [comment]
I'll try it on my virtual machine.

**Comment by gforney** [comment]
attached are the boundary file entries I see in the load menu with last night's nightly bundle smokeview.  what were you expecting? 

![bndf_menus](https://github.com/firemodels/fds/assets/12403014/9f764b86-d2ab-40c1-b2e6-6e43c41484f1)

**Comment by gforney** [comment]
You posted issue about the same time  last nights bundle was built. I fixed a similar bug recently. Maybe your smokeview was from a bundle the night before, before the fix showed up . Check the smokeview version you are using against version displayed at website . Maybe we'll get lucky :-)

**Comment by johodges** [comment]
Sorry for the delay, just getting back to this. I loaded nightly build 227 and was able to visualize the boundary files from GEOM and OBST correctly. We can close this out now.
