### ISSUE TITLE
Can FDS do batch processing of multiple FDS files to speed up simulation efficiency? Thanks!

### ISSUE THREAD

**Issue by chenlinjie1213** [firemodels/fds#11886]
Greetings, I would like to ask if FDS can do batch simulations of multiple .fds files? Many thanks to you.

**Comment by mcgratta** [comment]
FDS reads a single input file and performs the simulation. You can write a .bat file in DOS or a .sh script in linux to arrange for multiple simulations to be performed all at once or one following the other.  Do you know how to write scripts in DOS or with linux shell scripts?

**Comment by drjfloyd** [comment]
If you are on a Windows system and all your input files are in the same directory, then all you should need is a .bat file that has:

call fds_local -p x -o y file1.fds
call fds_local -p x -o y file2.fds
...
call fds_local -p x -o y fileN.fds

where file1 - fileN are the names of your input files and x and y are whatever MPI or OpenMP processes you want following the instructions for using fds_local. Then you can just run the bat file from within the CMDfds window. 

The upside of this is it is easy. The downside is that it runs all the simulations one at a time and it won't take advantage of extra cores to run more than one case at a time.

If you want to do that in Windows, it can be done but you will have to figure out the details. In https://github.com/firemodels/fds/tree/master/Verification/scripts are two scripts called Run_FDS_Cases (one .bat for Windows command shells and one .sh for Linux). Each script invokes a number of other scripts and ultimately they run all the FDS cases listed in https://github.com/firemodels/fds/blob/master/Verification/FDS_Cases.sh. These scripts are designed around running the Verification suite and presume a certain directory structure based on the fds git repository; however, you could use these as a starting point for making your own scripts. The Windows  scripts contain logic burried in them to allow you to have more than one FDS case run at a time.
