### ISSUE TITLE
Inlet velocity with intersecting GEOMs

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#11901]
This example is a tunnel with a velocity inlet at the lower x bound and open at the upper x bound. The bottom surface is a GEOM which splits the first row of cells in half. In the first mesh the inlet is on a GEOM and something strange is occurring at the intersection of the two GEOMs. 
![image](https://github.com/firemodels/fds/assets/13366803/3ca90566-2e49-4509-be15-cb712f930df7)

In the second mesh the inlet is a typical VENT on the boundary, and the flow is uniform and normal to the surface as expected.
![image](https://github.com/firemodels/fds/assets/13366803/e1561cb5-a86a-4dc7-b03d-ecde907be35e)

Also, if the GEOM on the bottom surface is grid-aligned or splits the cells with a smaller volume, this issue does not appear.

[geom_inlet.txt](https://github.com/firemodels/fds/files/11739781/geom_inlet.txt)

**Comment by marcosvanella** [comment]
Thanks Eric.

**Comment by marcosvanella** [comment]
This case is working correctly with latest changes. Thanks Eric.
