### ISSUE TITLE
parallel process memory access violation

### ISSUE THREAD

**Issue by tague-carlyon** [firemodels/fds#11918]
[serverrack45simp.txt](https://github.com/firemodels/fds/files/11772202/serverrack45simp.txt)

when running the command "fds_local -p 4 serverrack45simp.fds"

there is a memory access violation.

**Comment by mcgratta** [comment]
This case ran successfully on our linux cluster, but with a more recent build. This case failed on a Windows PC. I'll update the version and try it again.

**Comment by tague-carlyon** [comment]
There is still an access violation when run on fds version FDS-6.8.0-310-g1aee177-master

**Comment by tague-carlyon** [comment]
when running FDS-6.8.0-316-g67623da-master in debug mode the error it printed out was:

forrtl: severe (408): fort: (11): Subscript #1 of the array CFACE has value -11 which is less than the lower bound of 0

Image              PC                Routine            Line        Source
fds.exe            00007FF6CD526886  CC_SCALARSCC_DIVE       10242  ccib.f90
fds.exe            00007FF6CD3D59DA  CC_SCALARS_mp_CC_        8615  ccib.f90
fds.exe            00007FF6CF24481E  DIVG_mp_DIVERGENC         721  divg.f90
fds.exe            00007FF6CF2CDC02  MAIN__                    434  main.f90
fds.exe            00007FF6D66F9F2B  Unknown               Unknown  Unknown
fds.exe            00007FF6D676D0C4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF8D8367614  Unknown               Unknown  Unknown
ntdll.dll          00007FF8D94E26A1  Unknown               Unknown  Unknown

**Comment by marcosvanella** [comment]
Thanks Tague, I'll look at this.On Jun 16, 2023 3:00 PM, Tague Carlyon ***@***.***> wrote:
when running FDS-6.8.0-316-g67623da-master in debug mode the error it printed out was:
forrtl: severe (408): fort: (11): Subscript #1 of the array CFACE has value -11 which is less than the lower bound of 0
Image              PC                Routine            Line        Source
fds.exe            00007FF6CD526886  CC_SCALARSCC_DIVE       10242  ccib.f90
fds.exe            00007FF6CD3D59DA  CC_SCALARS_mp_CC_        8615  ccib.f90
fds.exe            00007FF6CF24481E  DIVG_mp_DIVERGENC         721  divg.f90
fds.exe            00007FF6CF2CDC02  MAIN__                    434  main.f90
fds.exe            00007FF6D66F9F2B  Unknown               Unknown  Unknown
fds.exe            00007FF6D676D0C4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF8D8367614  Unknown               Unknown  Unknown
ntdll.dll          00007FF8D94E26A1  Unknown               Unknown  Unknown

**Comment by tague-carlyon** [comment]
[geomtest.txt](https://github.com/firemodels/fds/files/11803716/geomtest.txt)

New file that seperates the geometry for ease of diagnosis.

**Comment by tague-carlyon** [comment]
[serverrack45simp.txt](https://github.com/firemodels/fds/files/11849899/serverrack45simp.txt)

new situation that gets a memory access violation. I have tried refining the mesh to the point where it takes an hour to initiate to no avail.

**Comment by marcosvanella** [comment]
Thanks Tague, I'll take a look.

**Comment by marcosvanella** [comment]
Tague, I fixed several issues in FDS and these cases are running now. Test them with latest source on the Windows side and let me know. Thanks.

**Comment by marcosvanella** [comment]
Thank you Tague, good job.
