### ISSUE TITLE
GEOM cases with ompi compilation

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11917]
I was looking to compile the latest FDS on our cluster. We typically use the ompi_gnu_linux build. I am running into an issue running GEOM cases with this environment. The error is below. My understanding is MKL is an intel specific library and required for the ULMAT solver. Is it possible to run GEOM cases in an ompi environment or are we limited to impi at this time? I am working on swapping to impi for our cluster but wanted to document the issue for discussion.

Error: MKL Library compile flag was not defined for ULMAT as pressure solver.

**Comment by mcgratta** [comment]
Can this be done in the make_fds.sh script?

**Comment by marcosvanella** [comment]
The path to MKL will depend where it was installed. It can be done in the startup file like we do with oneApi libs.On Jun 16, 2023 3:45 PM, Kevin McGrattan ***@***.***> wrote:
Can this be done in the make_fds.sh script?

**Comment by johodges** [comment]
Thanks Marcos, I am able to compile with ompi now. It looks like we'll need intel compilers available on the machine even if compiling with the ompi for the foreseeable future.
