### ISSUE TITLE
Visualize GCF edges in SMV

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11925]
Is it possible to visualize the full edges of a GEOM mesh in SMV? When I show the grid on the immersed boundary many of the cells are shown as being rectangular. However, the raw data is stored out as triangles. I noticed when visualizing the geometry in another software that most of the time the triangles are just along the diagonal of the square, but that is not always the case.
![smv_gcf](https://github.com/firemodels/fds/assets/17127980/7c670509-9eee-4922-988a-1ecdb0f785e3)

![raw_triangles](https://github.com/firemodels/fds/assets/17127980/5dcb154a-e7dd-453b-a9b3-90c890bad0eb)

**Comment by marcosvanella** [comment]
Jon, got to Files/data/Coloring in Dialogs. Select Slice -> Settings -> outline type : click on "triangle".
________________________________
From: johodges ***@***.***>
Sent: Friday, June 23, 2023 08:30 AM
To: firemodels/fds ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [firemodels/fds] Visualize GCF edges in SMV (Issue #11925)


Is it possible to visualize the full edges of a GEOM mesh in SMV? When I show the grid on the immersed boundary many of the cells are shown as being rectangular. However, the raw data is stored out as triangles. I noticed when visualizing the geometry in another software that most of the time the triangles are just along the diagonal of the square, but that is not always the case.
[smv_gcf]<https://user-images.githubusercontent.com/17127980/248266655-7c670509-9eee-4922-988a-1ecdb0f785e3.PNG>

[raw_triangles]<https://user-images.githubusercontent.com/17127980/248267423-5dcb154a-e7dd-453b-a9b3-90c890bad0eb.PNG>

**Comment by johodges** [comment]
Thanks that worked!
