### ISSUE TITLE
HT3D consistency between versions (6.7.7, 6.8.0)

### ISSUE THREAD

**Issue by jstebbi** [firemodels/fds#11927]
It was requested that I make an issue about the inconsistency between WALL TEMP results between FDS versions 6.7.7 and 6.8.0.

**Background:** I ran two simulations on the FDS-6.8.0-159-gc988ccf 2023-May-23, one with HT3D on the Candle "Container" SURF and one on the "Candle Bulk" SURF.  CELL SIZE set to one mesh (.0025).  Everything else being the same as code I shared below (see attachment).

**For HT3D on Candle "Bulk" in 6.8.0:**
![CandleComputeFDS2_0 - Container rim temp](https://github.com/firemodels/fds/assets/93282682/6b9dc721-b406-4c04-9cf1-16be63930942)
![CandleComputeFDS2_0 - 120min averages](https://github.com/firemodels/fds/assets/93282682/82df423e-6ddb-43d7-bb7d-cbc3a1f70752)
Approx 42h 14m to run.

**For HT3D on Candle "Container" in 6.8.0:**
![CandleComputeFDS2_1 - Container rim temp](https://github.com/firemodels/fds/assets/93282682/24c89d6c-58ed-4b64-a602-e789c2fc50da)
![CandleComputeFDS2_1 - 120min averages](https://github.com/firemodels/fds/assets/93282682/9233ab4c-119b-4af7-b25c-7690e6b91330)
Took approximately 56h 28m to run.

**Compare that to HT3D on BOTH "Bulk" and "Container" in 6.7.7:**
![MetaAromaticAROMA140_4_4 - Container rim temp](https://github.com/firemodels/fds/assets/93282682/321dd0b7-29ca-4645-9e8d-7065a0d5098e)
![MetaAromaticAROMA140_4_4 - 120min averages](https://github.com/firemodels/fds/assets/93282682/3152c6c2-53a3-4f49-91cf-a33e1cdbae4f)
At time 38h 7m.

**For HT3D on Candle "Container" ONLY in 6.7.7:**
![CandleComputeFDS2_1_3 - Container rim temp](https://github.com/firemodels/fds/assets/93282682/0a5e72f0-9702-4760-b7c6-9ebbbb45e49a)
![CandleComputeFDS2_1_3 - 120min averages](https://github.com/firemodels/fds/assets/93282682/d2890f2a-d42a-4200-838e-e03599dd0de4)

At time 44h 24m.
*Note that in 6.7.7 HT3D only works with Thickness assigned to SURF ID and with every OBST line container SURF ID having "HT3D=.TRUE." included.

**(Note) 1D Heat Transfer on same model in 6.8.0 full release:**
![MetaAromaticAROMA140_11_0 - Container rim temp](https://github.com/firemodels/fds/assets/93282682/de728d79-6d69-4313-9de6-39d0e9a0507a)
![MetaAromaticAROMA140_11_0 - 120min averages](https://github.com/firemodels/fds/assets/93282682/421e9f45-65a5-4837-8aad-48f47e68b87b)

Seems without HT3D on the candle container that the heat isn't making it to the sidewall.  I will add that the model I have made in FDS 6.7.7 has predicted pretty closely the Rim and Wall max temperatures in a single simulation from live candle burn tests.

[CandleComputeFDS1_2_MetaExample.txt](https://github.com/firemodels/fds/files/11851444/CandleComputeFDS1_2_MetaExample.txt)

**Comment by mcgratta** [comment]
The newer version of the 3D solver is still a work in progress. It might take some time for me to build in all the capabilities to test this case. You may want to stay with the older version for now.

**Comment by mcgratta** [comment]
I have made improvements in the 3D solver over the past few months. A new version can be found [here](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST). I ran your original case with the new code. This is what the temperatures look like:

![image](https://github.com/firemodels/fds/assets/11333911/bef9513e-e003-4a9a-a1e2-cd5998091205)

These may be different than those from before, but that is to be expected because the grid is fairly coarse. You might want to test a case that runs in less time to determine if the temperatures converge for a geometry like this.

**Comment by jstebbi** [comment]
Thanks for the update.

When you say temperatures converge, do you mean doing a grid refinement
study on a finer mesh (and shorter time) and seeing if you get similar
temperatures as the more coarse mesh?

I will test this build with my cases asap.

**Comment by mcgratta** [comment]
When you first started using the 3D feature, it was limited to one internal node per grid cell, where the grid cell was just like the gas phase grid cell, only inside the solid. For an insulating material like wax, this is not enough spatial resolution to capture that steep gradient in temperature just below the surface of the solid. By grid convergence, I mean the grid inside the solid. Currently, your CELL_SIZE is the size of the gas phase grid.

**Comment by jstebbi** [comment]
Ok.  I see.  I can change CELL_SIZE for each OBST to a smaller size than
overall mesh?

**Comment by mcgratta** [comment]
Yes, which should capture the gradient better.

**Comment by jstebbi** [comment]
Thanks for the explanation.  This is really helpful.  I was trying to
capture the taper of the actual candle holder but it doesn’t do so well
with the large cell size.  I think maybe a cylinder could be a reasonable
approximation so I will try running that.
