### ISSUE TITLE
Boundary Files break when using burn away and restarts

### ISSUE THREAD

**Issue by Rhodehamei** [firemodels/fds#11921]
I have created a simple case where using boundary outputs with burn away and the restart file causes an issue when the data is read in Smokeview. I used the box_burn_away_1.fds as the base for the example. This was run on FDS 6.8.0.
A single obstruction was placed centered between 4 meshes. The model was run for 15 seconds where a restart was dumped and a kill command terminates the run. Then the model is restarted. When a single obstruction line is used the boundary data has no issues. When the obstruction is broken up into sections with each obstruction ending on a mesh boundary the boundary data does not work when the model is restarted. See the images below for the error. The model on the left of the images is when it is broken into 4 obstructions.

![image](https://github.com/firemodels/fds/assets/102156515/1a2237c9-02f6-4519-a1d4-8805db51d4b3)
Some of the meshes fail to display boundary data after 15 seconds.
![image](https://github.com/firemodels/fds/assets/102156515/4a28681a-9092-4c24-ad37-633aabd20db6)

![image](https://github.com/firemodels/fds/assets/102156515/c974ae82-5bb5-422b-a0ba-ebe97482452c)

[Burn_Away_Test.txt](https://github.com/firemodels/fds/files/11804585/Burn_Away_Test.txt)

**Comment by mcgratta** [comment]
This is a bug. I'll post a fix soon.

**Comment by mcgratta** [comment]
This bug has been fixed. If you want to test it, you can download a nightly build.
