### ISSUE TITLE
Setting User-Defined Solid Cell Size in SURF, for 1D Heat Transfer

### ISSUE THREAD

**Issue by TristanHehnen** [firemodels/fds#11929]
Hi!

I've got issues with setting a solid cell size directly for a multilayer `SURF` with 1D heat transfer. In "8.3.8 Solid Phase Numerical Gridding Issues" the command is listed as `CELL_SIZE(NL)`, which I understood as providing the option to define individual solid cell sizes per layer. 
However, FDS seems to only work with `CELL_SIZE` without specifying the layer, thus setting the cell size equally for all layers. This is a bit unfortunate, because we would like to provide higher resolution for a pyrolysing layer and lower resolution for an inert layer.

As an example, I've tried:
```
THICKNESS(1:2) = 0.05, 0.2,
CELL_SIZE(1:2) = 0.0025, 0.02,
```

```
THICKNESS(1:2) = 0.05, 0.2,
CELL_SIZE(1) = 0.0025,
CELL_SIZE(2) = 0.02,
```

What am I missing here?
I'm on `FDS-6.8.0-124-g6542893-master`.

Best,
Tristan

**Comment by mcgratta** [comment]
`CELL_SIZE` is a parameter that we added for 3D heat transfer. It was originally intended to make all the cells in the solid the same size. I suggest you not use this parameter for 1D heat transfer. You can use `CELL_SIZE_FACTOR` and `STRETCH_FACTOR(:)` to control the noding within the solid. However, `CELL_SIZE_FACTOR` applies to all layers. This is not necessary. I will make this parameter an array so that you can control the size and stretching of the nodes in each layer.

**Comment by TristanHehnen** [comment]
Hm, okay.

Would it be possible to have the `CELL_SIZE` work in the 1D case as well?
Recently we experienced the issue that we could not reach convergence for a pyrolysing layer with decreasing `CELL_SIZE_FACTOR`. The issue is that I didn't change the `N_LAYER_CELLS_MAX`. So while the layer thickness was decreasing due to pyrolysis, the resolution for the remaining layer got finer and finer. Until the thickness of the remaining stuff in combination of the `CELL_SIZE_FACTOR` got to a value below the  `N_LAYER_CELLS_MAX` default. 
It would be quite nice to have more direct control over the solid cell size, instead of juggling `CELL_SIZE_FACTOR`, `STRETCH_FACTOR` and `N_LAYER_CELLS_MAX`.

**Comment by mcgratta** [comment]
I changed the code to all `CELL_SIZE_FACTOR` to be set for each layer. As for `CELL_SIZE`, even if we make this a parameter for each layer, I do not think it will solve your problem. If the layer mass pyrolyzes, the layer is going to shrink regardless if we use `CELL_SIZE` or `CELL_SIZE_FACTOR`. These parameters just set up the initial noding.

As for `N_LAYER_CELLS_MAX`, it is 999 by default. I only use this parameter to force my solid to have only one layer and one cell. In other words, I use this to make the solid thermally-thin, by passing the logic in FDS to choose the number of cells.

But one step at a time -- can you confirm that the new code enables you to control `CELL_SIZE_FACTOR` for each layer?

**Comment by TristanHehnen** [comment]
I'll have a look at it, thank you.

**Comment by TristanHehnen** [comment]
Hi Kevin,

it seems to work. 
Now each layer has a different number of cells, using the following input:

```
&SURF ID               = 'SampleLayers',
      RGB              = 200,100,0,
      STRETCH_FACTOR   = 1, 1, 1,
      THICKNESS        = 0.002, 0.002, 0.002,
      CELL_SIZE_FACTOR = 0.5, 0.25, 0.125,
      MATL_ID          = 'Sample', 'Sample', 'Sample' /

&MATL ID            = 'Sample',
      DENSITY       = 300.,
      CONDUCTIVITY  = 0.5,
      SPECIFIC_HEAT = 1.0 /

```



| Solid Phase Node | Layer | Coordinates(m)|
| --------------------|-------|------------------| 
|            0   |   1    |   0.0000000 |
|            1   |   1    |   0.0005000 |
|            2   |   1    |   0.0010000 |
|            3   |   1    |   0.0015000 |
|            4   |   1    |   0.0020000 |
|            5   |   2    |   0.0022857 |
|            6   |   2    |   0.0025714 |
|            7   |   2    |   0.0028571 |
|            8   |   2    |   0.0031429 |
|            9   |   2    |   0.0034286 |
|            10  |    2   |    0.0037143 |
|            11  |    2   |    0.0040000 |
|            12  |    3   |    0.0041538 |
|            13  |    3   |    0.0043077 |
|            14  |    3   |    0.0044615 |
|            15  |    3   |    0.0046154 |
|            16  |    3   |    0.0047692 |
|            17  |    3   |    0.0049231 |
|            18  |    3   |    0.0050769 |
|            19  |    3   |    0.0052308 |
|            20  |    3   |    0.0053846 |
|            21  |    3   |    0.0055385 |
|            22  |    3   |    0.0056923 |
|            23  |    3   |    0.0058462 |
|            24  |    3   |    0.0060000 |



Thank you!

**Comment by TristanHehnen** [comment]
Using: `FDS-6.8.0-328-g6a323c5-master`
