### ISSUE TITLE
fds verification / screen drag / ctrl function subtract - error

### ISSUE THREAD

**Issue by ShehabGamrah** [firemodels/fds#11944]
Hey when using the below code to obtain and store the subtraction result between two gas phase devices the caluclated results from the software are different from the manual calculations 

&DEVC XYZ = 0.50,0.5,0.50,QUANTITY='PRESSURE',ID='p_up 0.1'/
&DEVC XYZ = 0.50,0.5,1.55,QUANTITY='PRESSURE',ID='p_up 0.4'/
&DEVC XYZ = 0.50,0.5,2.60,QUANTITY='PRESSURE',ID='p_up 0.8'/
&DEVC XYZ = 1.50,0.5,0.50,QUANTITY='PRESSURE',ID='p_down 0.1'/
&DEVC XYZ = 1.50,0.5,1.55,QUANTITY='PRESSURE',ID='p_down 0.4'/
&DEVC XYZ = 1.50,0.5,2.60,QUANTITY='PRESSURE',ID='p_down 0.8'/

&CTRL ID='FDS 0.1', FUNCTION_TYPE='SUBTRACT', INPUT_ID='p_up 0.1','p_down 0.1' /
&CTRL ID='FDS 0.4', FUNCTION_TYPE='SUBTRACT', INPUT_ID='p_up 0.4','p_down 0.4' /
&CTRL ID='FDS 0.8', FUNCTION_TYPE='SUBTRACT', INPUT_ID='p_up 0.8','p_down 0.8' /

&DEVC ID='FDS 0.1', QUANTITY='CONTROL VALUE', CTRL_ID='FDS 0.1', XYZ=0,0,0, UNITS='Pa' /
&DEVC ID='FDS 0.4', QUANTITY='CONTROL VALUE', CTRL_ID='FDS 0.4', XYZ=0,0,0, UNITS='Pa' /
&DEVC ID='FDS 0.8', QUANTITY='CONTROL VALUE', CTRL_ID='FDS 0.8', XYZ=0,0,0, UNITS='Pa' /

**Comment by drjfloyd** [comment]
I think this was answered in a duplicate post in the forum. DEVC are written as the average value since the last output. CTRL use the smoothed DEVC value where the default is no smoothing (i.e. the instateneous value). You can add TIME_AVERAGED=F to a DEVC to write the instaneous value.
