### ISSUE TITLE
Endianness in Structured SLCF File

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11948]
Many of the binary outputs have an endianness check included in the header. However, this is not included in the structured slice file header. This information was previously included in the (.end) file but was removed in https://github.com/firemodels/fds/pull/11804. How is SMV determining the endianness of the structured slice files now?

**Comment by johodges** [comment]
An oddity in the endianness of the binary slice files generated in the attached case (run with 6.8 nightly build 332) is what prompted me to look into this. In the file "case001_1_1.sf", the header sextuplet describing the dimensions of the slice are stored in the file as:

0000000f0000000f000000000000000a0000000000000018

This corresponds to 15, 15, 0, 10, 0, 24 in a big endian representation and gibberish in a little endian representation. However, later on in the same file, the temperature values are stored as:

0000a0410000a0410000a0410000a041

which corresponds to 20.0 in a float32 little endian representation and gibberish in a big endian representation. This is the first time I have observed the endianness being swapped within a binary file in FDS. Is this an intentional swap? Such as the header always being big endian and then the data being output in the machine format? I was using the site below for the binary conversion in the different representations:

https://www.scadacore.com/tools/programming-calculators/online-hex-converter/
[case001.zip](https://github.com/firemodels/fds/files/11938583/case001.zip)

**Comment by mcgratta** [comment]
Just from random searching, I see
```
For example, Intel processors have traditionally been little-endian. Motorola processors have always been big-endian. Big-endian is an order in which the "big end" (the most-significant byte) is stored first. Little-endian is an order in which the "little end" (the least-significant byte) is stored first.
```

**Comment by mcgratta** [comment]
Neither FDS nor Smokeview does anything intentionally to reverse the default byte order.

**Comment by drjfloyd** [comment]
@johodges 

We have lines like this in dump.f90 which lets smokeview figure things out.

      WRITE(LU_PART(NM)) INTEGER_ONE                ! The number ONE, to indicate file Endian-ness

**Comment by mcgratta** [comment]
Yes, but I think we got rid of the `.end` file which had been used for the same purpose.

**Comment by gforney** [comment]
the only time in the past when endianness has been an issue was when we had silicon graphics computers and previous generation of macs.  in other words we no longer have  the case where data is generated on one endian type and viewed on another.  smokeview no longer accounts for this case

**Comment by johodges** [comment]
Currently the write(integer) is included in geom data outputs, bndfs, s3ds,
and prt5 but not included in 2d structured slices. We can grab the endian
info from any of those outputs but not the 2d slices.

I don't think the swap between big in the header and little in the data is
new. I have had pyfdstools hard code the header as big and use native for
the data for years. I noticed this discrepancy while chasing down another
bug fix and wanted to get feedback from the team on it.

**Comment by gforney** [comment]
when fds outputs this "endian" field it is writing out a 1.  when smokeview was checking this field, it checked to see if it was a 1.  if it wasn't then it assumed the the case was run on computer that had the opposite endian convention from the one that it (smokeview) was running on and then would swap bytes.   are you saying that you are not seeing a 1 for this endian field?

**Comment by johodges** [comment]
Thanks for the feedback. The case I have been troubleshooting had 300 cells along a single axis in a single mesh and the header was not being read correctly. I have a hypothesis of what is going on which I am going to look into now. Fortran adds zeros at the end of each write statement. I believe in pyfdstools I am currently reading the padded zeros to the right of the data which is why hard coding the header to big endian was being read correctly. This was generally working out ok as long as the number of cells in each direction within a mesh did not exceed 256 which would require another byte. I'll report back once I have tested this hypothesis.

**Comment by gforney** [comment]
it also writes out 4 bytes at the beginning.  so for each fds write: 
4 bytes at the beginning, data that that fds outputs, 4 bytes at the end
I don't know what is in those 4 bytes - probably different for each compiler.  smokeview uses this format to read all the data fds ouputs in C .  smokeview just skips of the beginning and ending 4 bytes.  the endian field would then be bytes 5 through 8

**Comment by gforney** [comment]
fds outputs in fortran - smokeview inputs in C

**Comment by johodges** [comment]
That was the issue. I am now able to correctly import the full file with little endian. I think it would be helpful to re-introduce the .end file so that other data formats have that information available rather than having it embedded in the header of each file. For example, plot3d does not have an endian check in the header and you have to select little or big when viewing it in another software package.

From a design perspective, my understanding from Glenn's prior message is we no longer support big endian OS. That's probably fine for most use cases, but I am unsure if all supercomputers are using little endian. Do we know if other partner computing resources are all little endian as well?

**Comment by uporersith** [comment]
> it also writes out 4 bytes at the beginning. so for each fds write: 4 bytes at the beginning, data that that fds outputs, 4 bytes at the end I don't know what is in those 4 bytes - probably different for each compiler. smokeview uses this format to read all the data fds ouputs in C . smokeview just skips of the beginning and ending 4 bytes. the endian field would then be bytes 5 through 8

the 4 bytes at the beginning and end of each that data write statement is a 4 byte integer that contains the length in bytes, of the data. 

https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnc4/index.html

**Comment by johodges** [comment]
No error in the output here, closing out the issue.
