### ISSUE TITLE
Pressure issue in the corridor

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#11951]
I am having a pressure problem in a corridor. 

The status at the end of the calculation:
The first compartment is open to -15Pa boundary
The second and third compartments are sealed but they are connected to adjacent compartments via leak VENTs. 
The fourth compartment is open to OPEN

The issue is the pressure in the third compartment. It is unrealistically high. 

Is there any user error? What can I do prevent this issue?
Thank you.

I attach the run files. 

Apologies that I could not simplify the case any further (this is how far I could get from the most complex model to here in half day)

**Runfiles:**   [v1.zip](https://github.com/firemodels/fds/files/11956924/v1.zip)

![image](https://github.com/firemodels/fds/assets/26166281/deaba741-672d-43cf-b51e-feb619e624e7)

**Comment by Er9y714** [comment]
Thank you for looking into it.  Although the average value of the P05 seems reasonable, I can't prevent the fluctuations. Regardless of the validation, could you recommend any solution to prevent this fluctuation?

**Comment by drjfloyd** [comment]
This VENT is covered by an OBST:
&VENT ID='OPEN-15Pa', SURF_ID='OPEN', XB=2.9,3.5,18.9,18.9,20.8,21.8, IOR=-2, DYNAMIC_PRESSURE=-15.0/

I would recommend you don't attached HVAC VENTs to OBST that disappear. HVAC relies on VENTs being present throughout the simulation. Shifting the VENT to be on the wall just above the door should have little impact on the results.

All your leakage VENTs are a single leakage path. A real door will leak around its perimeter. With just one leak path per door, you can only have flow in one direction. It might help to split the leakage flow top and bottom which would allow for possiblity of bi-directional flow.

You only have leakage via the doors and no bulk leakage for the walls. Your total leakage area is 0.039 m2.  4 m3/s through 0.039 m2 is over 100 m/s flow speed which is going to need very large pressure differences.

Your exhaust fan ramps up over 2 s, ramps down over 0.1 s, and then ramps back up again over 2 s. For a fan pushing 4 m3/s those are fast times to spin up and spin down the fan. It is highly unlikely that a real fan would be able to maintain that flow with negative pressures in the 100s of Pa.

**Comment by Er9y714** [comment]
Thank you very much for the response. 

The VENT is covered by obstruction so the OPEN is connected to the compartment when the obstruction is deactivated. 

I understand. It is attached to OBST because it is convenient to activate the leak when the door is closed. When the door is open the leak is disabled. 

The original model has the leak VENTs all around the door, I left only one to simplify the demonstration case. 

Original model has many more doors in the corridors and all doors have multiple leakage VENTs (i.e. 6). Usually this setup worked well. 

I agree the insitu case can be represented in FDS in a better way. 



My main take is finding a way to activate and deactivate the VENTs through HVAC without removing them. Thank you for the recommendation.

**Comment by sbenkorichi** [comment]
Besides what was already mentioned above, I'm not sure how the system is expected to operate in real life scenario, it doesn't seem you have any dedicated air inlet for the mech shaft vent in that lobby and it appears the only means of air is via the stairwell. If that's the case, I wouldn't have confident in such design system and is likely have issues on site. I note there the fan speed is ramping up/down (and I agree with the above, that seems quite sharp, you should be allowing for at least 10s ramp-up, depending on the product supplier) but in reality is likely to be achieved via a pressure sensor which will be linked to the stairwell door and you still have multiple cross-corridor doors in the way of the air intake. 4m3/s seems excessive too. I think if you reword it from design side, you shouldn't expect any pressure fluctuations as shown in your case.

**Comment by Er9y714** [comment]
I eliminated the extract fan and moved the VENTs outside of the doors. Model is further simplified. Leak areas are increased to 1 m2, VENT areas are increased as well. 

I see still a pressure fluctuation and this is why I reopened the case. You can find the runfiles download link below. Thanks. 

 
![image](https://github.com/firemodels/fds/assets/26166281/06eeaa70-05fd-44bd-ac22-0815720e4175)

 
[v4.zip](https://github.com/firemodels/fds/files/11967446/v4.zip)

**Comment by drjfloyd** [comment]
When you close the doors, this happens instantly.  The leakage paths now in a single timestep have to try establish flow to match the -15 Pa boundary condition. Pressure plummets upstream , the low jumps but overshoots, now pressure spikes, etc. You have a system that is not well damped. Closing thedoors more slowly might help (multiple OBST with delays between them). You could aslo try relaxing the pressure in the HVAC solver. (set HVAC_PRES_RELAX=0.5 on MISC)

**Comment by sbenkorichi** [comment]
Which version you're using? 
I just ran your case v4 with latest release and I don't see what you're seeing. 
![image](https://github.com/firemodels/fds/assets/20113030/29e8e01f-ea99-42b7-a291-0462ffab2366)

the flow around the exhaust opening is still a bit high but not as before when you had mech extract. 
![image](https://github.com/firemodels/fds/assets/20113030/2bd29208-b83a-4e22-a103-528da3dc4fbe)

**Comment by Er9y714** [comment]
I use FDS-6.8.0-0-g886e009-release. Since you mentioned, I tried v4  case with v6.7.9 as well. That was it! Seeing the difference, now I am more curious about the cause. 


![image](https://github.com/firemodels/fds/assets/26166281/8cba9419-ed76-46be-8b23-3640371011e9)
![image](https://github.com/firemodels/fds/assets/26166281/b1984109-716b-4031-b81d-d7dbda6394be)

**Comment by sbenkorichi** [comment]
Ok, I think I can see the same issue here. In my above case, I run it too with latest 6.8.0 but that was with a single mpi process. Looking into your v4 case which was with 10 mpi processes. I've tested it with just 4 mpi processes and I can see the same results as the one you shared above. 
Using a single mpi process it runs fine, but using mpi I notice it hangs close to 270s which is around those door time closure.

- Kevin, can you test this on your end too? 
```
&MESH ID='Mesh04', IJK=38,17,24, XB=4.0,7.8,17.2,18.9,19.5,21.9, MPI_PROCESS=0/
&MESH ID='Mesh05', IJK=38,17,24, XB=0.2,4.0,17.2,18.9,19.5,21.9, MPI_PROCESS=0/
&MESH ID='Mesh06', IJK=20,33,24, XB=6.7,8.7,13.9,17.2,19.5,21.9, MPI_PROCESS=0/
&MESH ID='Mesh07', IJK=20,33,24, XB=6.7,8.7,10.6,13.9,19.5,21.9, MPI_PROCESS=1/
&MESH ID='Mesh08', IJK=20,33,24, XB=6.7,8.7,7.3,10.6,19.5,21.9, MPI_PROCESS=1/
&MESH ID='Mesh09', IJK=41,17,24, XB=7.8,11.9,17.2,18.9,19.5,21.9, MPI_PROCESS=1/
&MESH ID='Mesh10', IJK=20,33,24, XB=8.7,10.7,11.8,15.1,19.5,21.9, MPI_PROCESS=2/
&MESH ID='Mesh11', IJK=20,35,24, XB=8.7,10.7,8.3,11.8,19.5,21.9, MPI_PROCESS=2/
&MESH ID='Mesh14', IJK=24,30,31, XB=10.7,13.1,7.3,10.3,18.8,21.9, MPI_PROCESS=3/
&MESH ID='Mesh15', IJK=24,30,31, XB=10.7,13.1,7.3,10.3,21.9,25.0, MPI_PROCESS=3/
```
![image](https://github.com/firemodels/fds/assets/20113030/b581ca1f-e95b-45fd-897c-d83459eea8bb)

**Comment by Er9y714** [comment]
> * n you test this on your end too?

I tried with ULMAT and 0.5 HVAC_PRES_RELAX, it helped but during door closing the number of iterations were extremely high. It maxed even 900 iterations, I did not try to increase it any further.

**Comment by mcgratta** [comment]
A leak area of 0.1 m² is still large. I think Jason is right -- you have to damp the oscillation or use a smaller leak area.

**Comment by Er9y714** [comment]
Setting lower leakage area solves the issue in v4 but not in v1. However some recommendation were made for v1, so we can ignore v1 results. 

Before applying the recommendation of gradually closing the doors and moving the leakages outside of the door (more complexity), I would like to try a few settings (solver, relaxation or another boundary setting for the -15Pa etc.). 

At the moment I have nothing more to report except the difference in pressure with running with MPI vs without MPI (as mentioned above). If you do not wish to investigate this, you might close the issue. 

Thank you for your time and suggestions.

**Comment by mcgratta** [comment]
OK, I will close. If further issues arise, start a new issue.
