### ISSUE TITLE
Numerical instability when using Temperature and velocity profiles

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#11954]
Hi, 

I have a FDS input file, which ran perfectly. Then I introduced the velocity and temperature profile. And it has been crashing at the first time step (Numerical instablity), ever since. This is the FDS file
[input_fds.txt](https://github.com/firemodels/fds/files/11999872/input_fds.txt)

Could you help me run the simulation ?

Thanks in advance

Rakesh

**Comment by rakyuv** [comment]
Thank you @mcgratta for your answer. I run FDS 6.7.9 in a supercomputer running Linux.  I never reserved any memory for the job. And I see that my job only used 1.14GB of RAM. I found this using 
sacct -a -j <jobid> --format=user%10,jobname%10,elapsed%10,MaxRS.

This is the answer to the above command 
hydra_bst+  00:00:37   1148060K

I am not sure if it is the problem of RAM. I used exclusive node to check if it runs, and the job still crashes.

**Comment by mcgratta** [comment]
You're right. I was mistaken in how much memory the job uses. It does not use that much memory.

**Comment by rakyuv** [comment]
I added the quotes around OPEN and GROUND. 

This the output of the FDS from the supercomputer
``` Starting FDS ...

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : July 10, 2023  16:02:26
 Revision         : FDS6.7.9-0-gec52dee42-release
 Revision Date    : Sun Jun 26 14:36:40 2022 -0400
 Compiler         : ifort version 2021.6.0
 Compilation Date : Jun 28, 2022 23:02:23

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Linux* OS


 Job TITLE        : To simulate methane plume with surface roughness
 Job ID string    : methane_emissions_surfaceRoughness

 Time Step:      1, Simulation Time:      1.67 s

ERROR: Numerical Instability - FDS stopped (CHID: methane_emissions_surfaceRoughness)
```

I removed the SLCF commands and I still see the same numerical instability error. I am not sure why it doesn't run

**Comment by rmcdermo** [comment]
Please try with 6.8.0.  The case works fine for me in debug mode.  With the MO profile you are getting -7 C temperatures at 3000 m elevation.

**Comment by mcgratta** [comment]
![image](https://github.com/firemodels/fds/assets/11333911/9cc93210-3e33-4556-93bc-b51451bf4e24)

**Comment by rakyuv** [comment]
Thank you @mcgratta for your answer. I didn't pay attention to the temperature ratio. I will correct it run, and will keep you posted on how it goes.
