### ISSUE TITLE
WUI Terrain shows up in setup only but not in run

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#11950]
I see different behavior in smokeview when I run the same input file with T_END=0 and with T_END > 0 in FDS (see attached). The left image below is the default view when T_END > 0, and the right image is the default view when T_END=0. As far as I can tell the settings on visualizing the immersed geometry should be the same. Both cases were run on windows using FDS-SMV 6.8-334.

Two questions:
1. Is there a setting I am missing which would allow me to visualize the bingeom in the case with T_END > 0?
2. Is the difference in default behavior intentional?

![image](https://github.com/firemodels/fds/assets/17127980/fb463198-1984-4076-9919-f73bc4145dae)
[las_conchas_fire.zip](https://github.com/firemodels/fds/files/11950956/las_conchas_fire.zip)

**Comment by marcosvanella** [comment]
You should see it in both cases. We'll run the case here.

**Comment by gforney** [comment]
I added some code recently to not display terrain in meshes that are not in the view frustum.  maybe there is a bug in this logic.  I'll check

**Comment by marcosvanella** [comment]
Glenn, I run the case with latest smv compiled in the Mac. Seems related to an issue we had before where the terrain would not show up for CFACEs (.gcf) but does for the input geometry (.ge). Hit "q" and the input terrain appears.

**Comment by gforney** [comment]
Are cfaces created for t=0 case?

**Comment by gforney** [comment]
Ok, ill change 'q' logic to display using non-cfaces if cfaces do not exist

**Comment by gforney** [comment]
try smokeview posted here or from a nightly build when firebot passes next
https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST
