### ISSUE TITLE
Level 4 Geom Crash on stop

### ISSUE THREAD

**Issue by tague-carlyon** [firemodels/fds#11965]
After I simulated 306185.4 seconds of the simulation, I created a CHID.stop file to initiate a stop and a segmentation fault occurred.
[L3GeomCrash.zip](https://github.com/firemodels/fds/files/12042914/L3GeomCrash.zip)

**Comment by marcosvanella** [comment]
Thanks Tague I'll take a look when I get back.On Jul 13, 2023 2:08 PM, Tague Carlyon ***@***.***> wrote:
After I simulated 306185.4 seconds of the simulation, I created a CHID.stop file to initiate a stop and a segmentation fault occurred.
L3GeomCrash.zip

**Comment by mcgratta** [comment]
I work on this.

**Comment by mcgratta** [comment]
I cannot reproduce the error. I did the following:

1. I started the job.
2. I waited about 10 minutes and then I issued the command `touch XXX.stop` where `XXX` is the job name.
3. I waited for the job to end.
4. I added `RESTART=T` to the `MISC` line.
5. I started the job again.
