### ISSUE TITLE
HVAC_MASS_TRANSPORT is not a MISC parameter

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#11976]
![image](https://github.com/firemodels/fds/assets/11333911/0eb5b5dc-08f5-4021-bdef-4272ce4d62b6)

**Comment by drjfloyd** [comment]
Missed that when editing guides.  Removed it. It wasn't needed since we
could just tie it to defining cells for a duct. Someone at FSRI noticed
this just before I left for vacation. I was fixed unless I missed it in
another place.

**Comment by mcgratta** [comment]
I noticed it because someone sent in a case in the Discussion Forum.

**Comment by drjfloyd** [comment]
Fixed. Missed a couple of spots where that was used.

**Comment by mcgratta** [comment]
Thanks
