### ISSUE TITLE
FDS Validation Guide: Legends missing from UL/NFPRF Series I Experiments temperature plots

### ISSUE THREAD

**Issue by joktimo** [firemodels/fds#12018]
The temperature plots from UL/NFPRF Series I Experiments seem to be missing their legends. I assume dashed lines are from FDS and solid lines are from experiments like elsewhere in the guide, but which color is which measurement point? Based on the temperatures I would suspect that black is thermocouple 56, red is 68, green is 86 and blue is 98?

![kuva](https://github.com/firemodels/fds/assets/91564126/ae06aa14-41c2-4bd5-a30a-97c271db9811)
![kuva](https://github.com/firemodels/fds/assets/91564126/a6f1b79d-08c7-4e92-bcb2-2cfd9c8cb529)
![kuva](https://github.com/firemodels/fds/assets/91564126/b5e2c03e-e5ed-479a-8fd6-0502221412e7)

**Comment by mcgratta** [comment]
I'll fix

**Comment by mcgratta** [comment]
I could not fit the legends on the plots, but I added the text. Thanks.

![image](https://github.com/firemodels/fds/assets/11333911/e33d3f81-3897-4d2c-bd46-e41932155bae)
