### ISSUE TITLE
Particle cloud at mesh boundary

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#12026]
In the attached file there are several particle clouds. All of them introduces particle in to the volume as prescribed but one. 

As it can be seen the particle cloud on the bottom which is adjacent to a coarser mesh causes particle to appear on the coarse mesh. This only occurs when the particle cloud is placed at the boundary of a finer mesh which is adjacent to a coarser mesh (opposite situation does not create this issue). 
This issue does not occur when the XB location of the cloud is slightly reduced which avoids touching the cell corners. 

Could you please have a look?

Thank you.

**Model**
![image](https://github.com/firemodels/fds/assets/26166281/20ec8506-c57c-4bb6-87df-b4cb7f1065ff)

**Post**
![image](https://github.com/firemodels/fds/assets/26166281/9bdbbd28-643b-4cb7-a0b9-2aa5484bee2b)

&HEAD CHID='particle'/
&TIME T_END=10.0/
&DUMP DT_PART=1.0, /
&RADI RADIATION=.FALSE./

&MESH ID='Mesh01', IJK=6,7,16, XB=0.0,1.2,0.0,1.4,0.0,3.2/
&MESH ID='Mesh02', IJK=6,22,16, XB=1.2,2.4,0.0,4.4,0.0,3.2/
&MESH ID='Mesh03', IJK=3,11,8, XB=2.4,3.6,0.0,4.4,0.0,3.2/

&PART ID='Tracer',
      MASSLESS=.TRUE.,
      MONODISPERSE=.TRUE.,
      AGE=60.0/

&INIT ID='Particle Cloud01', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.2,0.4,0.0,0.6,0.0,1.0/ 
&INIT ID='Particle Cloud02', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.61,0.781873,0.01,0.586282,0.01,0.99/ 
&INIT ID='Particle Cloud03', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.2,1.4,0.0,0.6,0.0,1.0/ 
&INIT ID='Particle Cloud04', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.21,1.381873,0.81,1.386282,0.01,0.99/ 
&INIT ID='Particle Cloud05', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=2.2,2.4,0.0,0.6,0.0,1.0/ 
&INIT ID='Particle Cloud06', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=2.21,2.381873,0.81,1.386282,1.0E-2,0.99/ 
&INIT ID='Particle Cloud07', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=2.4,2.8,1.6,2.4,0.0,1.0/ 
&INIT ID='Particle Cloud08', PART_ID='Tracer', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=2.42158,2.781873,2.817481,3.986282,1.0E-2,0.99/ 

&TAIL /

**Comment by mcgratta** [comment]
This looks like one of these "less than" vs "less than or equal to" issues. I will fix.

**Comment by mcgratta** [comment]
Should be fixed. As a work-around, use volume bounds that are slightly smaller than the actual volume to avoid mesh boundaries.
