### ISSUE TITLE
Seeking help regarding FDS RESTART.

### ISSUE THREAD

**Issue by MrAhriman** [firemodels/fds#12045]
![image](https://github.com/firemodels/fds/assets/97651495/1e666822-e2fb-4531-9961-93cf9b0a9ef7)
[tunnelfire.txt](https://github.com/firemodels/fds/files/12321912/tunnelfire.txt)

**Comment by drjfloyd** [comment]
Try this with a very small non-zero VEL at the start. It may be that setting VEL=0 means some necessary array for a fixed flow boundary condition isn't being set up initially which means it isn't present for the RESTART to change it.

**Comment by MrAhriman** [comment]
> 在开始时尝试使用非常小的非零 VEL。设置 VEL=0 可能意味着最初没有为固定流边界条件设置一些必要的数组，这意味着 RESTART 无法更改它。

Thank you for your reply, I will try your method next (since it is nearly 12 PM in my place, it may be a few hours before I can give you feedback again, not to ignore your suggestion). Whether it is successful or not, thank you again

**Comment by MrAhriman** [comment]
> 在开始时尝试使用非常小的非零 VEL。设置 VEL=0 可能意味着最初没有为固定流边界条件设置一些必要的数组，这意味着 RESTART 无法更改它。

Unfortunately, this approach still doesn’t work. I modified the first simulation in pyrosim from 0s to 25s with VEL=-0.1. Then I stopped the simulation and changed VEL to -10. I resumed the simulation from 25s to 50s. From the simulation results, it can be seen that the modifications did not take effect.

**Comment by MrAhriman** [comment]
I believe that RESTART does not work only when “adding or removing vents” as stated in the Fire Dynamics Simulator User’s Guide, but it should also not work when changing certain surface parameters, such as the default “VEL=XX” in the “SUPPLY” option in Pyrosim.
![image](https://github.com/firemodels/fds/assets/97651495/68104173-fef5-4beb-9353-28bcb46fcc09)

**Comment by drjfloyd** [comment]
Thanks for trying that out.  I would expect that RESTART should let VEL change as long as there was a VEL in the original file.  I'll look into this.

**Comment by drjfloyd** [comment]
We did some variable reorganization for how we stored data related to wall cells. This was needed in part to ensure consistent data structures for wall cells due to OBST and GEOM as well as PART with a SURF_ID assigned. As a result we are writing the initial wall normal velocity to the restart file. So when doing a restart, FDS reads in the new vel but doesn't use it as it uses the boundary cell value stored in the restart.  As a workaround, try having a RAMP_V.  In the intial file just have two RAMP lines at different times with the value 1 for F and in the restart change it to 2.  We don't write RAMP data to the restart.

**Comment by MrAhriman** [comment]
> We did some variable reorganization for how we stored data related to wall cells. This was needed in part to ensure consistent data structures for wall cells due to OBST and GEOM as well as PART with a SURF_ID assigned. As a result we are writing the initial wall normal velocity to the restart file. So when doing a restart, FDS reads in the new vel but doesn't use it as it uses the boundary cell value stored in the restart. As a workaround, try having a RAMP_V. In the intial file just have two RAMP lines at different times with the value 1 for F and in the restart change it to 2. We don't write RAMP data to the restart.

Thank you for your reply again. I will try the method you provided.
