### ISSUE TITLE
PMMA ambient specific heat different in macfp cases

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12079]
The ambient temperature specific heat of PMMA is different in the UMD_SBI and the NIST_NRC_Parallel_Panels cases in the validation directory. Should these be the same?

https://github.com/firemodels/fds/blob/master/Validation/UMD_SBI/FDS_Input_Files/UMD_SBI_5_mm.fds

https://github.com/firemodels/fds/blob/master/Validation/NIST_NRC_Parallel_Panels/FDS_Input_Files/PMMA_60_kW_5_mm.fds

**Comment by mcgratta** [comment]
Jason -- am I using the most recent UMD parameters in the parallel panel cases?

**Comment by drjfloyd** [comment]
@mcgratta  Yes.

**Comment by drjfloyd** [comment]
SBI and UMD now using the same properties.
