### ISSUE TITLE
ht3d-network example does not show heat transfer across mesh boundary.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#12074]
Using: https://github.com/firemodels/fds/blob/master/Verification/Heat_Transfer/ht3d_network.fds

See the screenshot below, where the heat flows well from the source through the network, until it reaches the mesh boundary and then stops transferring in the middle of the solids.

![image](https://github.com/firemodels/fds/assets/12104446/cdfcf179-1585-41bf-a5ea-479d16d4b166)

This was visualized in PyroSim Results (shown above) and in Smokeview with the same result.

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
![ht3d_network_28800](https://github.com/firemodels/fds/assets/11333911/1e3339e3-d1a0-4fc5-9c60-761cd20089c0)
This image was made by last night's firebot run. Did you run the case with one MPI process or two? Windows or linux?

**Comment by mcgratta** [comment]
Is this still an issue for you?

**Comment by bwklein** [comment]
Running on Windows 11 with the following command.

`"C:\Program Files\PyroSim 2023\fds\runfds.exe" mpiexec.exe -localonly -n 1 fds_openmp.exe ht3d_network.fds`

 Revision         : FDS-6.8.0-0-g886e009-release
 Revision Date    : Tue Apr 18 07:06:40 2023 -0400
 Compiler         : Intel ifort 2021.7.0
 Compilation Date : Tue 04/18/2023  03:28 PM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Windows* OS

**Comment by bwklein** [comment]
I am rerunning the case in parallel to see if there is any difference.

**Comment by mcgratta** [comment]
OK, I can replicate the problem when I run with 1 MPI process. I'm on it.

**Comment by mcgratta** [comment]
I usually run multi-mesh simulations using the same number of MPI processes, so I missed this bug. Should be fixed -- give it a try when you have a chance.
