### ISSUE TITLE
Seeking Guidance on Path Length settings

### ISSUE THREAD

**Issue by Tbuttts21** [firemodels/fds#12085]
Hi all, 

Historically I have been using the following setting for my FDS runs: 

&RADI NUMBER_RADIATION_ANGLES=600, PATH_LENGTH=30.0 /

where the path length is equal to the distance between my target and the burner fire. 

My question is whether using the distance between the target and the fire base is a valid choice for the path length. I have seen some literature that suggests that this is a decent approximation for far-field targets. My secondary question is whether the path_length should change when wind is introduced. For example, if I add a 5 m/s wind in the direction of the target, the flame will be much closer to the target... should the path length change to account for this reduced distance between the flame and the target. 

Thanks!

**Comment by rmcdermo** [comment]
This is not a code issue.  Let's transfer this to a Discussion.  I will answer there.
