### ISSUE TITLE
Simulation explodes without apparent reason

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#12087]
I have this simulation which is currently exploding without any apparent reason. After 1800s the simulation explodes without any apparent reason (results seems smooth, RAM is not saturated nor is the hard drive).

FDS version: 6.8.0
ncore: 8
multi-thread: disabled

Below some screenshot of the error message I am getting:

![image](https://github.com/firemodels/fds/assets/7260681/412a2168-5fbb-4ef0-89b6-78d27e5b4ff3)
![image](https://github.com/firemodels/fds/assets/7260681/f13bb97e-4672-4b0e-9b19-f3266b387bf0)

Download simulations here: https://we.tl/t-ZvMvk3BNu0

**Comment by mcgratta** [comment]
Was this case restarted?

**Comment by rupole1185** [comment]
No, no restart..

Il lun 28 ago 2023, 20:32 Kevin McGrattan ***@***.***> ha
scritto:

**Comment by mcgratta** [comment]
I see several devices with SETPOINTS of 1800 s, which is when the failure occurs. My guess is that this might be due to some action that takes place at 1800 s. Can you try to change the case so that this action happens earlier. I would have to run this case 90+ hours just to confirm what you see. It would be easier to create a case that fails sooner.

**Comment by rupole1185** [comment]
Ok,

I can try that!

Il lun 28 ago 2023, 20:38 Kevin McGrattan ***@***.***> ha
scritto:

**Comment by drjfloyd** [comment]
FDS User's Guide 10.2.3
Note that a VENT being used for an HVAC system should not have a CTRL_ID or DEVC_ID.

You are removing the OBST that the HVAC system vents are attached to. Do not do this. If you want the fan to turn off, turn off the fan with the DEVC.  You also have not specifed any losses for the HVAC system but you are specifying a fan curve which relies upon a meaningful pressure drop to pick the fan operation poit.

**Comment by mcgratta** [comment]
Jason -- are any of these potential pitfalls easy to detect at start up?

**Comment by drjfloyd** [comment]
If it is a VENT with a CTRL or DEVC, that is easy to detect and we do throw an error for that. OBST is trickier as you could remove the OBST the VENT is attached to (this case), overlay another OBST that covers the VENT, add a HOLE, could have multiple OBST defining the same wall cell where only one is removed, etc.

**Comment by drjfloyd** [comment]
Some checking is done for losses.  Difficult to trap everything but we do try and trap some errors.  May need to take a second look at that logic.

**Comment by rupole1185** [comment]
It took about 4 days using 8 cores .. a bit long!

*Ruggero Poletto*
*Managing director*

*VideoCall*: calendly.com/ruggero-poletto | *Mobile*: +39 378 30 33 133

________________________________________

CFD FEA SERVICE SRL P.IVA 04545570238 - via Borgo Grande 19, 37044 Cologna
Veneta VR

*ATTENTION:*

All information in this e-mail message, as well as any files included, are
intended for the exclusive use of the recipient (s) indicated above /
indicated, and therefore subject to protection pursuant to law no. 675 and
of the Legislative Decree of 30 June 2003 n. 196. Anyone who receives this
message by mistake, is requested to notify the writer of the incorrect
receipt, and proceed with the immediate cancellation of the same from the
system. Your cooperation is appreciated.

*PRIVACY:*

All personal data, including e-mail addresses, are collected and stored
with the sole purpose of carrying out our professional activity towards
you. The privacy law D.Lgs. N. 196 of 30/06/2003 provides in article 7 the
right of the interested party to access their personal data, to request
their correction, updating and deletion, therefore we invite you to report
us in the way you deem most appropriate as provided by Article 7.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
29/08/23,
15:25:42

**Comment by mcgratta** [comment]
Any progress on this issue?

**Comment by rupole1185** [comment]
No progress at the moment ...

**Comment by rupole1185** [comment]
I modified the FDS file, this time I used the DEVC to control/delete the HVAC and not the OBST where the HVAC is connected and this time everything works ok!

I guess this was the issue with the file.

**Comment by mcgratta** [comment]
Great. Thanks for letting us know. So the lesson learned is not to remove an OBST that has an HVAC VENT connected to it.
