### ISSUE TITLE
Wildfire spreading fire on trees

### ISSUE THREAD

**Issue by taskall** [firemodels/fds#12080]
This simple case is to ignite one tree with an initial energy source (e.g. a hot surface) and then turn it off and simulate the fire spreading from tree to tree. But, when the hot surface turns off, the fire on the tree stops eventually.
Is it a need for constant hot surface supply to maintain the fire in the tree? Or what am I missing?

[pine_tree_new.txt](https://github.com/firemodels/fds/files/12421673/pine_tree_new.txt)

**Comment by mcgratta** [comment]
You're not missing anything obvious. I cannot tell just by looking at your parameters whether the fire will spread. Have you tried using the NIST Douglass Fire test cases? That is, take a case in which a single tree burns, and then add more trees.

**Comment by taskall** [comment]
I have done similar approach with other example of WFDS in WUI. Where can i find the Douglass Fire test case fds file?
