### ISSUE TITLE
Smokeview hangs in github actions for qgis2fds verification in OBST terrain cases

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12094]
I am running into an odd issue with smokeview in the qgis2fds verification. The general approach right now is:
- run qgis2fds to generate the FDS files
- generate a smokeview file by running the FDS nightly build
- generate the images by running smokeview with the -runscript option

The issue right now is that I am seeing different behavior with smokeview between my local machine and the remote machine for the github actions workflow. Both systems are using Ubuntu with the latest nightly build of FDS and SMV. Currently, the cases representing the terrain as GEOM work correctly on my local machine as well as the github actions workflow. However, the two cases representing the terrain as OBST work correctly on my local machine but hang on the github actions workflow.  When I copy all the files generated by the github workflow to my local ubuntu machine, smokeview runs correctly without hanging.

The generated files are available as a release on my fork of qgis2fds:

https://github.com/johodges/qgis2fds/releases/download/verify-dev/ubuntu.tar.gz

Are there any thoughts on what could be causing the hanging behavior?

**Comment by gforney** [comment]
don't know.  I'll take a look at your files

**Comment by gforney** [comment]
the terrain texture was not in the tar file, was it present when you ran the obst cases that hung?

**Comment by johodges** [comment]
It was not present in either the case that runs or hangs. I've attached a log of the console out from when it runs successfully on my local machine. On the remote machine in hangs after the "Startup time: 0.x s"
[log.txt](https://github.com/firemodels/fds/files/12488274/log.txt)

**Comment by gforney** [comment]
try now with revision SMV-6.8.0-813-gac6058ba9 or later.  smokeview performs some blockage intialization work in the background to speed up the startup.  I forced now it to peform this in the foreground if a script is being run. that was the only difference I could think of between a case with OBSTs and one without OBSTs

**Comment by johodges** [comment]
I can confirm that this change fixed the hanging issue in GH actions workflow for qgis2fds verification.Thanks!

**Comment by gforney** [comment]
Great! What is odd is that i originally added code to examine obsts in the
background a long time ago haven't had any problems until now
