### ISSUE TITLE
Minimum density, FDS stopped

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12092]
I am running a FDS in an outdoor flow. Previously I had run the simulation with 9 MPI_PROCESS. I wanted to scale it up to 36 MPI_PROCESS. However, I get the following error:

_WARNING: Minimum density,    0.105 kg/m3, clipped in Mesh 14_
 _Time Step:   1782, Simulation Time:    159.83 s_

_ERROR: Numerical Instability - FDS stopped (CHID: dfsync0Lidar)_
 
I am attaching my FDS input file here
[inputFds.txt](https://github.com/firemodels/fds/files/12483955/inputFds.txt)

Could you please help me finding the error ?

Thanks in advance

**Comment by mcgratta** [comment]
I am running the case, but why are you doing this:
![image](https://github.com/firemodels/fds/assets/11333911/3f4fa666-5c7e-45c1-a2aa-89c4e16ef9d5)
This odd configuration of meshes might be the problem.

**Comment by rakyuv** [comment]
I just realised that I had added wrong values in those two meshes by mistake. I have corrected it, and submitted the job.
My apologies for not checking the mesh before with Smokeview. I will take care from the next time. 

Thank you for your time @mcgratta
