### ISSUE TITLE
Numerical instability - FDS stopped

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12106]
Hi, 

I am having a "Numerical instability - FDS stopped" error. The meshes are correct. Could you please check what the problem is, with the simulation ?
[test_fds.txt](https://github.com/firemodels/fds/files/12574049/test_fds.txt)

Thanks in advance

Best,
Rakesh

**Comment by rmcdermo** [comment]
I have not had time to run this on our cluster yet.  But just in looking at your input file, I see some things that concern me.

1. Your mesh extents go up to 4 kilometers (already pushing the limits of anything FDS has ever done).  But your z RAMPS are not consistent with this, and go up to 50 kilometers.  Is that just a typo?   If you are really interested in domains this large, FDS is not the right code.  You need a code that models Planetary Boundary Layers (PBL).
2. You are specifying a large convective heat flux and then not using `CHECK_HT=T`.  This is a recipe for numerical instability with an explicit code.  Specifying the mean heat flux in FDS is rarely a good idea.  The real boundary over kilometers is not a constant and uniform heat flux.  You are asking FDS to generate heat transfer coefficients to satisfy a boundary temperature of 20 C and whatever the local gas phase temperature is to be consistent with 120 kW/m2.  So, you are specifying unphysical conditions, and this quite often leads to numerical instabilities.
3. This is probably nothing, but when a namelist parameter wants a string, please add quotes to your parameter.  For exmaple, `DB='XMIN'` and `SURF_ID='OPEN'`.

I suggest you start with a much simpler case with a reasonable domain size and then start building complexity.  Then you will be able to pin point what causes the problem.  Jumping from a code that is validated on laboratory scale wind tunnels and pushing that up to regional meteorological scales is too much of a leap.
