### ISSUE TITLE
Problem with SPATIAL_STATISTIC and QUANTITY='CHAMBER OBSCURATION'

### ISSUE THREAD

**Issue by mst-parkhachev** [firemodels/fds#12104]
Dear colleagues!

I encountered a problem when using a DEVC with SPATIAL_STATISTIC='MIN' and QUANTITY='CHAMBER OBSCURATION'.
[test.txt](https://github.com/firemodels/fds/files/12570534/test.txt)

DEVC_1 lies entirely inside the area of DEVC_2. And DEVC_2 lies entirely inside the area of DEVC_3.
So I expected the devices to activate in the following order: 
1.DEVC_1 
2.DEVC_2
3.DEVC_3

I decided this because the minimum value of the parameter in a large square cannot exceed the threshold earlier than in a small square inside a large square.

But they activated in reverse order
 9.46377E+00, DEVC, DEVC_3                                                      ,T, 9.39938E+00,%/m
 1.12070E+01, DEVC, DEVC_2                                                      ,T, 6.28305E+00,%/m
 1.18586E+01, DEVC, DEVC_1                                                      ,T, 6.56758E+00,%/m

Then I assumed that SPATIAL_STATISTIC property does not work together with QUANTITY='CHAMBER OBSCURATION'. I assumed that parameter SPATIAL_STATISTIC is ignored and the device operates at a central point of specified XB.
And added DEVC_4 with the same central point as DEVC_2.

But DEVC_4 and DEVC_2 didn't work at the same time. Moreover, for some reason DEVC_4 was activated simultaneously with DEVC_3.
 9.46377E+00, DEVC, DEVC_3                                                      ,T, 9.39938E+00,%/m
 9.46377E+00, DEVC, DEVC_4                                                      ,T, 7.80181E+00,%/m
 1.12070E+01, DEVC, DEVC_2                                                      ,T, 6.28305E+00,%/m
 1.18586E+01, DEVC, DEVC_1                                                      ,T, 6.56758E+00,%/m

Could you explain to me why this result occurs?

I've got one more question. Is it possible to use flat devices like mine, in which two coordinates of XB are equal?

When I used QUANTITY='TEMPERATURE' instead of a smoke detector, the order of activation of the sensors turned out to be correct.

**Comment by mcgratta** [comment]
Make sure XB is an actual volume, not a plane. This may not solve the problem, but it would rule out one possible cause.

**Comment by mst-parkhachev** [comment]
Added volume to devices:
&DEVC ID='DEVC_1'      XB=1,2,-2,-1, 2.75,3  SPATIAL_STATISTIC='MIN' PROP_ID='PROP_1'/
&DEVC ID='DEVC_2'      XB=0,2,-2,0, 2.75,3  SPATIAL_STATISTIC='MIN' PROP_ID='PROP_1'/
&DEVC ID='DEVC_3'      XB=-1,2,-2,1, 2.75,3  SPATIAL_STATISTIC='MIN' PROP_ID='PROP_1'/
&DEVC ID='DEVC_4'      XB=0.5,1.5,-1.5,-0.5, 2.75,3  SPATIAL_STATISTIC='MIN' PROP_ID='PROP_1'/

The time and order of activation have not changed.

**Comment by drjfloyd** [comment]
I don't think you can use CHAMBER OBSCURATION with a spatial statistic.
This device has an output that evolves over time. It is not an instantneous
device like TEMPERATURE. The device has only on set of variables for
tracking the evolving output and not a set for every grid cell in the XB.

**Comment by mst-parkhachev** [comment]
Thank you very much for the explanation!
In this case, I need a different QUANTITY.
Is QUANTITY = 'EXTINCTION_COEFFICIENT' compatible with spatial statistics? I think so, but want to clarify now)

**Comment by drjfloyd** [comment]
Any QUANTITY in the tables of outputs labeled as good for DEVC and SLCF (or BNDF for a solid phase QUANTITY) should be able to use a SPATIAL_STATISTIC.

**Comment by drjfloyd** [comment]
Added a note to Section 22.2.3 on SPATIAL_STATISTIC needing S for gas phase file type or B for solid phase file type in the tables of outputs.

**Comment by mst-parkhachev** [comment]
Thank you very much!
