### ISSUE TITLE
Unexpected wind field using PRESSURE_GRADIENT_FORCE

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12109]
I was investigating the different wind approaches we have yesterday. I am seeing odd behavior when using the PRESSURE_GRADIENT_FORCE. In the attached case I applied a positive pressure gradient force mostly to the x-axis. I was expecting this to generate a westerly wind field (nominally positive U-Velocity throughout). However, the resulting U-VELOCITY field has flow going out of the domain at both X-MIN and X-MAX, with most of the flow coming into the domain through the top. The attached has the input and a subset of the outputs (3-D slices of U, V, W).

![image](https://github.com/firemodels/fds/assets/17127980/971a01c7-068f-4287-b820-f0328fbb13ec)
[Chimney_Tops_2_no_initialization.zip](https://github.com/firemodels/fds/files/12585723/Chimney_Tops_2_no_initialization.zip)

**Comment by rmcdermo** [comment]
The OPEN bc was never designed for flow parallel to it and may give odd behavior in such cases.  It is probably necessary to set INITIAL_SPEED to something so that OPEN_WIND_BOUNDARY is implemented instead of OPEN.

We make is sound like this is optional in the user guide, but that may not be true.  Just keep in mind that this is all brand new.  Once we actually get a working case we can provide better guidance.

**Comment by rmcdermo** [comment]
What should the velocity at elevation be?  5 m/s seems low.  If you have a poor physical assumption then an initial value problem may end up with a poor result.  The actual stratification and heat transfer at the surface may also matter.  Was this case stably stratified, neutral, or unstable?  If you do not have any amount of stable stratification, I would expect flow from the top down.

**Comment by mcgratta** [comment]
You've set the LAPSE_RATE to -0.02 C/m. The adiabatic lapse rate of the atmosphere is -0.0098 C/m (9.8 C/km).  Thus, you have a very unstable atmosphere and a coarse grid. FDS seems to be giving you what you asked for. Set the LAPSE_RATE to 0 and the wind field is as you would expect for a stable atmosphere.

**Comment by rmcdermo** [comment]
I think you mean "stable"... temperature decreasing too fast, right?  This is what causes a downwash from the top... then yes an "unstable" numerical result follows.

**Comment by mcgratta** [comment]
No, I believe that when the temperature decreases faster than the ALR, the atmosphere is unstable.

**Comment by rmcdermo** [comment]
Please explain.  Stable just means that drho/dz>0.  I would think that temperature decreasing more than ALR makes the density higher aloft.

**Comment by rmcdermo** [comment]
Sorry, yes, I'm off.  Brain freeze

**Comment by mcgratta** [comment]
I think this is where the concept of potential temperature comes from. When the change in T* decreases with height, atmosphere is unstable. Increasing, stable. Kind of like subtracting off the ALR.

**Comment by johodges** [comment]
Thanks for the info. I think it makes sense in that case that the unstable boundary layer was applying a greater pressure than the domain pressure I was prescribing at the boundaries. I was basing the LAPSE_RATE on a different WRF-SFIRE simulation from which I had previously extracted. Taking a look now at the data specific to the Chimney_Tops_2 case.

**Comment by johodges** [comment]
I am getting a LAPSE_RATE of -0.0047 for the Chimney_Tops_2 case which should be a stable condition. Re-running with this boundary condition.
![image](https://github.com/firemodels/fds/assets/17127980/30d022b4-4113-4ce7-9349-91dc2b6bf18b)
