### ISSUE TITLE
Update PROF

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#12114]
Add PROF_APPROPRIATE to OUTPUT_QUANTITY so that any solid phase output that is in-depth could be used on PROF. 

Rather than the current special PROF logic for TEMPERATURE and DENSITY we could then just call the normal SOLID_PHASE_OUTPUT for the in-depth values at each node location and store in a temporary array (maybe PROF_ARRAY?)) allocated to the number of wall points. To stay backwards compatible and make life easier for the user, in READ_PROF could let TEMPERATURE or WALL TEMPERATURE be used and set both to the INSIDE WALL TEMPERATURE QUANTITY after reading same for DENSITY set to SOLID DENSITY. Then the only special logic for PROF would be for a tempertature profile we would use TMP_F and TMP_B rather than set PROF_ARRAY(0)=PROF_ARRAY(1) and PROF_ARRAY(NWP)=PROF_ARRAY(NWP-1) like is done now for RHO.

**Comment by mcgratta** [comment]
It is not documented, but one can do this
```
&PROF XYZ=...,, IOR=..., QUANTITY='MATL name' /
```
What other quantities do you want to include?

**Comment by drjfloyd** [comment]
Every QUANTITY that can use a DEPTH now and in the future. 

Right now that would also include SOLID CONDUCTIVITY and SOLID SPECIFIC HEAT but as we get more and more into modeling the solid phase I could also see people wanting an output for the mass fraction of a material as a point quantity or a profile, or heat flow at a depth, or if we some kind of gas diffusion model for char any outputs for that.

**Comment by mcgratta** [comment]
How about if we stick to whatever we store in `BOUNDARY_ONE_D` ?

**Comment by drjfloyd** [comment]
We don't store CP or K in B_O_D but we have logic in SOLID_PHASE_OUTPUT to process this. I think if we can get something with a DEPTH we should also be able to make a PROF of it. We can add OPT_NODE_INDEX to SOLID_PHASE_OUTPUT and those quantities that use a DEPTH would then compute for that OPT_NODE_INDEX rather than processing DEPTH to get an INDEX.

**Comment by drjfloyd** [comment]
Correction we do store K but not CP just RHO*CP.

**Comment by mcgratta** [comment]
Besides temperature, what else do we get with DEPTH?

**Comment by drjfloyd** [comment]
SOLID CONDUCTIVITY and SOLID SPECIFIC HEAT but as I noted above, I can see that as we have more people doing solid phase modeling that they may want more outputs that we don't currently have at which point if we add anything new that can take a DEPTH we should also be able to use it for &PROF.

**Comment by mcgratta** [comment]
I would rather just make `DUMP_PROF` simpler and streamlined, and then just list all relevant `ONE_D` parameters in a case statement.  I like to know that when I look at a .prof that I am getting the exact contents of the `ONE_D` arrays.  Calling `SOLID_PHASE_OUTPUT` seems inefficient and might complicate that routine even more than it already is.

**Comment by drjfloyd** [comment]
It seems more inefficient and riskier to have two sets of code that do the same thing. Also there are current (like CP) and future outputs not in ONE_D that you can get with DEPTH why would we not want to support user's in getting a profile of anything that has a DEPTH.  

I'll find time to do this.
