### ISSUE TITLE
radf.txt interface file does not print results at t = 0

### ISSUE THREAD

**Issue by tgernay** [firemodels/fds#12122]
Hello,

This issue is related to the interface file "radf.txt" created with the &RADF command (application is for FDS-SAFIR interface).

The results at time = 0 are not printed in the interface file "radf.txt". Results are printed (NSTEPS-1) times starting with the second value of TIME.

Would it be possible to print the results at time=0 in "radf.txt"?
(thus print the results NSTEPS time, once at each time step)
This would be useful so it is not necessary to make an assumption in the FE code on the initial conditions in FDS.

Thanks a lot
Thomas 

(attached is an example of file with the command &RADF)
[column.txt](https://github.com/firemodels/fds/files/12666288/column.txt)

**Comment by mcgratta** [comment]
This is a bug. The file `_radf.txt` has not been opened when the first call to the radiation solver is made. The initial group of `INTENSITIES`  is being written to a file called `fort.xx` which is the default name of an output file. I will fix. In the meantime, look for a file that starts with `fort`

**Comment by tgernay** [comment]
Thank you!

**Comment by mcgratta** [comment]
Should be fixed. You can recompile or wait for the next daily test release.
