### ISSUE TITLE
HRRPUA not working with N_SIMPLE_CHEMISTRY_REACTIONS=2

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12148]
I did a bisect and [this commit](https://github.com/firemodels/fds/commit/b43b96e1993b131f87a32fdc35c3352a3c6ef971) broke the 2 step scheme.   The case below is a simple 15 kW burner (1 m2 surface area).  If `N_SIMPLE_CHEMISTRY_REACTIONS=2` I get about twice the hrr.

[test.fds.txt](https://github.com/firemodels/fds/files/12719464/test.fds.txt)

@drjfloyd Please see if you can get this sorted asap.  I am in the middle of trying to get cases working for MaCFP.

@mcgratta This should have had a verification case.  Please add one.

**Comment by rmcdermo** [comment]
My guess is that [1_step_2_step_compare.fds](https://github.com/firemodels/fds/blob/master/Verification/Species/1_step_2_step_compare.fds) passed because it uses MLRPUA.

**Comment by drjfloyd** [comment]
Was just about to make the same comment. I'll sort this out this evening.

**Comment by drjfloyd** [comment]
I think I see my mistake. When I reworked the logic, in the branch for HRRPUA I used RN%HEAT_OF_COMBUSTION which for two-step would be just the first step rather than RN%HOC_COMPLETE

**Comment by rmcdermo** [comment]
For tonight, I'm just going to dial back.  I'll test any new changes tomorrow.  Thanks

**Comment by drjfloyd** [comment]
compiling and testing now should be up in a few if it works.

**Comment by drjfloyd** [comment]
fixed

**Comment by drjfloyd** [comment]
I'll make a verification case for HRRPUA.

**Comment by drjfloyd** [comment]
Added two meshes using HRRPUA to the existing 1_step_2_step case.

**Comment by rmcdermo** [comment]
Test case is working with latest change.  Thanks!
