### ISSUE TITLE
Error statement related to pressure solver

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12146]
```
ULMAT_H_MATRIX_LUDCMP PARDISO Num Factor: The following ERROR was detected:    -2

ERROR: FDS was improperly set-up - FDS stopped (CHID: plate_view_factor_ibm_30)
```
What does this mean? I got this error when running this case on a branch.

**Comment by marcosvanella** [comment]
Somehow the node run out of memory when this care was factorizing the Poisson matrix. I added a more detailed message for error -2 (insufficient memory) in PR #12186.
