### ISSUE TITLE
-273 C showing up inside slice through OBST

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12144]
In this case the lower bound of the temperature slice is coming up as -273 C.  Glenn figured out this is coming from inside the OBST.  I suspect this is just an initialization issue and perhaps tied to recent work on solid heat transfer(?).

/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Validation/FM_Burner/Test_SC/FM_15cm_Burner_C2H4_15p2_2cm.smv

<img width="400" alt="Screenshot 2023-09-22 at 6 52 20 PM" src="https://github.com/firemodels/fds/assets/4418497/d94d9cfa-c313-4e42-92f2-15f141e98694">

**Comment by mcgratta** [comment]
It's the row just under the cylinder. I'll find it.

**Comment by mcgratta** [comment]
This commit fixes the immediate problem. In short, the temperature output from the cells just below the GEOM cylinder was being changed from ambient (20) to -273. I added a check to stop CC_IBM from tampering with the output from a SOLID cell. 

Marcos -- check this and see if there are other issues with DUMP_SLCF.
