### ISSUE TITLE
Problem with heat transfer in an i-shaped column with HT3D=.T.

### ISSUE THREAD

**Issue by ASpallek** [firemodels/fds#12163]
Hello there,
I'm simulating a fire near to a i-shape column with multiply meshes (168) and I use the 3D heat transfer by setting HT3D=.T.
I also set NEIGHBOR_SEPARATION_DISTANCE=3 but as you can see in the picture, there is no heat transfer beyond the different meshes.
Does anyone have an idea what I'm doing wrong?
Thank you

Greetings
Alex
![Screenshot 2023-10-02 101624](https://github.com/firemodels/fds/assets/106251977/537844d1-5431-4657-b196-b419e4878068)

**Comment by drjfloyd** [comment]
You may not be doing anything. Kevin did recently fix a bug dealing with mesh boudaries and HT3D. Try the current test version of FDS (https://github.com/firemodels/test_bundles), and see if that solves the problem.

**Comment by ASpallek** [comment]
Thank you! I've downloaded the test version and restarted the simulation. I'll give a feed back if it works.

**Comment by mcgratta** [comment]
I need an input file.

**Comment by ASpallek** [comment]
Here is my input file.
[ht3d_168.zip](https://github.com/firemodels/fds/files/12784183/ht3d_168.zip)

**Comment by mcgratta** [comment]
I am running the case.

**Comment by ASpallek** [comment]
The screenshot was taken at a time of around 100s, so it's not necessary to simulate the whole 30 minutes to check whether the problem occurs.

**Comment by mcgratta** [comment]
Yes, I am looking at the internal temperatures.

**Comment by mcgratta** [comment]
This is a bug. The heat flux from the fire is not being transfer to the web. I'll work on a fix.

**Comment by ASpallek** [comment]
Okay, thank you. I'll wait for the fix but meanwhile I have found a little workaround for my problem. I don't use several meshes in the area of ​​the column cross section and now I can at least see the temperature distribution on the web for the different meshes along the z-axis.

**Comment by mcgratta** [comment]
It is not a mesh issue. It has to do with the boundary condition at the forward pointing edge of the web.

**Comment by ASpallek** [comment]
Hello again, is the fix still in progress or already done?
Thank You.

**Comment by mcgratta** [comment]
It is fixed in a branch that has not been merged into the master. The fix is on this [branch](https://github.com/mcgratta/fds/tree/ht3d).

**Comment by ASpallek** [comment]
Maybe I'm overlooking something, but is there a way to download the installer for Linux somewhere?

**Comment by mcgratta** [comment]
You would have to clone my branch of the fds git repository and then compile yourself. If you cannot do this, you'll have to wait until we merge my fix into the master branch and release a test bundle.

**Comment by ASpallek** [comment]
Hi, I've been trying to compile your branch for the past two days, but I keep running into issues at the "Configure and install Open MPI" step (I've been trying it on WSL2). Is there an estimate for when the ht3d-fix will be available as a test bundle?
Thank you.

**Comment by marcosvanella** [comment]
Do you have a linux or windows OS? In either case you don't need to compile openmpi. Just download and install Intel OneApi Base and HPC toolkits. That will give you all libraries you need to compile fds. Given you are doing research it is a good skill to be able to compile the code from source.

**Comment by mcgratta** [comment]
I committed fixes to the 3D heat transfer routine that should address your problem. Clone the master branch and recompile.

**Comment by mcgratta** [comment]
A new nightly build of FDS can be found [here](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST). Give it a try and let me know if it solves your problem.

**Comment by ASpallek** [comment]
Thank you for your responses and tips. Today I managed to compile FDS with the help of your guide using Intel OneAPI ... and it seemed like it was no longer necessary :D, but still a good exercise.
@mcgratta I will let you know

**Comment by mcgratta** [comment]
It is a useful exercise. If you plan to do any research in CFD, you should learn how to compile code.

**Comment by ASpallek** [comment]
I have submitted the simulation to the cluster, but there are still many simulations in the queue ahead of mine. I will reach out as soon as I have first results.

**Comment by ASpallek** [comment]
The nightly build doesn't solve the Problem. For me, it looks even worse.
![Fire_at_Column_0166](https://github.com/firemodels/fds/assets/106251977/5a6546a4-6e63-4481-8bb1-8db2fbfc8238)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I have been considering this simpler case
```
&HEAD CHID='column3', TITLE='Fire_Column' /

&MESH IJK=5,12,30, XB=-2.30, -2.05, -0.90, -0.30, +0.00, +1.50, MULT_ID='mesh' /
&MULT ID='mesh', DX=0.25, DY=0.60, DZ=1.50, I_UPPER=5, J_UPPER=2, K_UPPER=1 /

&TIME T_END=1800. /
&DUMP NFRAMES=1800. /
&MISC NEIGHBOR_SEPARATION_DISTANCE=3 /
&SURF ID='HOT', TMP_FRONT=500, COLOR='RED', HEAT_TRANSFER_COEFFICIENT=0 /
&OBST XB=-1.40, -1.20, -0.10, 0.10, 00.40, 01.00, COLOR='RED', SURF_ID6='HOT','INERT','INERT','INERT','INERT','INERT' /

&OBST XB=-02.000, -01.982, -00.150, 00.150, 00.05, 02.50, SURF_ID='F_Stahl' /
&OBST XB=-02.000, -01.500, -00.005, 00.005, 00.05, 02.50, SURF_ID='F_Stahl' /
&OBST XB=-01.518, -01.500, -00.150, 00.150, 00.05, 02.50, SURF_ID='F_Stahl' /

&SURF ID='F_Stahl', MATL_ID='STEEL', HT3D=T, CELL_SIZE=0.025, COLOR='BLACK', HEAT_TRANSFER_COEFFICIENT=0 /
&MATL ID='STEEL', SPECIFIC_HEAT=0.45, CONDUCTIVITY=50, DENSITY=7850, EMISSIVITY=0.7 /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&SLCF PBY=0, QUANTITY='TEMPERATURE', CELL_CENTERED=T /

&BNDF QUANTITY='WALL_TEMPERATURE', CELL_CENTERED=T /
&BNDF QUANTITY='ADIABATIC SURFACE TEMPERATURE', CELL_CENTERED=T /

&TAIL /
```
whose output is 

![image](https://github.com/firemodels/fds/assets/11333911/bc3d76ba-0f3b-4b8c-87f8-0c1fac17badd)

The problem with all these cases is that the Smokeview image only shows one temperature value per solidi face cell, which in your case is 5 cm by 5 cm. This sometimes produces a odd-looking result. I am running your bigger case now. Is there some value of temperature that is expected? It is difficult to know if the simulation is right or wrong just by appearance.

**Comment by mcgratta** [comment]
I added a [test case](https://github.com/firemodels/fds/blob/master/Verification/Heat_Transfer/ht3d_energy_conservation_8.fds) that demonstrates that the increase in the enthalpy of the solid column is equal to the net heat flux at the surface.
