### ISSUE TITLE
Geometric or aerodynamic free area in FDS?

### ISSUE THREAD

**Issue by jameschampion20** [firemodels/fds#12161]
Hi All,

I run and review a lot of FDS models that use automatic opening vents (AOVs) for smoke clearance purposes. 

A questions I’ve been getting asked a lot lately is whether the free area of the AOV that I’ve modeled is a geometric or aerodynamic free area? I typically model a head of stair AOV in FDS as a 1m2 hole as this is the UK geometric free area requirement - see here for example: https://sertus.uk/blog/roof-vent-areas#:~:text=Geometric%20Area%20%2D%20the%20hole%20in,by%20the%20Coefficient%20of%20Discharge.

However, am I right in saying that FDS assumes that the vent is 100% efficient and effectively assumes that the coefficient of discharge = 1? For example, are frictional losses accounted for or not in FDS? 

Therefore, would a more accurate modeling approach in FDS be to model a 0.7m2 hole (which is the minimum UK aerodynamic free area requirement for a head of stair AOV)?

Thanks in advance,

James

**Comment by jameschampion20** [comment]
Thanks Kevin for the response,

Would another option be to reduce the free area of the vent (to say 0.7m2) and effectively model the aerodynamic free area from the start?

**Comment by drjfloyd** [comment]
The C_d=0.7 results from the flow stream expending energy as it necks down entering the orifce and expands leaving. In a hand caclulation or a model like CFAST where you are not modeling the 3D flow field, the way you account for that effect is with a discharge coefficient. In a CFD model, you are modeliing the flow field with equations that conserve mass, momentum, and energy. With sufficient grid resolution you will appromixate the correct discharge coefficient.

**Comment by jameschampion20** [comment]
Thanks Jason, so modelling the vent as a 1m2 hole, having a fine enough mesh, and not explicitly specifying a discharge coefficient would suffice in FDS?

Thanks,

James

**Comment by drjfloyd** [comment]
The Validation Guide has metrics on flows through openings from simulations of 11 test series. The over all model statistics are a bias of 1.02 with an 8 % uncertainty. C_d=0.7 is an approximate value. C_d can be lower or higher depending on factors like size of the opening vs. the wall area.

You can always run a simple test case of a compartment with an orifice in the wall where you add or remove air inside the compartment and then look at the pressure field.

**Comment by jameschampion20** [comment]
Thanks Jason, based on the bias and uncertainty results, and given that FDS is a 3D solver, it would appear that it is sufficient to retain the 1m2 hole size and not prescribe a discharge coefficient as long as the mesh used to resolve the hole is sufficiently fine. The wall solvers in FDS will factor in things like friction into their calculations, provided a high enough grid resolution. 

Please let me know if my interpretation is correct and if you have any additional comments. 

Thanks,

James
