### ISSUE TITLE
github-actions: `setup apt repository` step fails

### ISSUE THREAD

**Issue by marcfehling** [firemodels/fds#12162]
The GPG keys for the Intel oneAPI repository expired on 09/30. See also https://github.com/oneapi-src/oneapi-ci/issues/77.

I'll work on a fix.

**Comment by rmcdermo** [comment]
Hi @marcfehling Thanks for the heads up.  Firebot seemed to pass last night.  Is that because we have OneAPI compiled and cached?

**Comment by marcfehling** [comment]
The github workflow retrieves the oneAPI packages from a Intel repository, for which the GPG key/certificate ran out on 09/30. The ubuntu VM complained about that and refused to download the packages.
