### ISSUE TITLE
Different solutions in ompi_gnu_linux and impi_intel_linux

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12198]
I noticed an issue with the ompi_gnu_linux compilation while working on a branch. The same case compiled with the latest fds source has different results for ompi_gnu_linux and impi_intel_linux. The difference occurs early in the simulation where the time step in ompi_gnu_linux drops rapidly. This eventually leads to a numerical instability after around 3 seconds of simulation time. I see the same issue with the FFT and ULMAT solvers. Have the compilation arguments for the impi_intel_linux version changed lately? Other thoughts on the root cause?

![image](https://github.com/firemodels/fds/assets/17127980/2cf4df45-1b1e-4521-a15c-cb17bba33f36)
[PMMA_60_kW_2_cm_spyro.txt](https://github.com/firemodels/fds/files/13064205/PMMA_60_kW_2_cm_spyro.txt)

**Comment by mcgratta** [comment]
First question is why the git hash says 6.7.9. Have you tried compiling in
debug mode?

**Comment by drjfloyd** [comment]
May need to update the git tags. Run git tags and see if you are current.

**Comment by mcgratta** [comment]
Glenn, could you check this when the cluster is back. We may need to
install the latest gnu compiler.

**Comment by johodges** [comment]
Jason was right, I had not pushed the tags I had synced to my fork. However, that does not affect the commit level of the master repo so I expect the results to be the same. Re-compiling the two versions and checking now.

**Comment by johodges** [comment]
Same issue with the tags fixed.

![image](https://github.com/firemodels/fds/assets/17127980/e88c225b-a748-4b14-8e03-f2da44230d93)

**Comment by marcosvanella** [comment]
I'll see if I can compile the code with gnu in the loaner Mac

**Comment by marcosvanella** [comment]
Looks like some initialization issue with the optimized gnu target:
- ompi_gnu_osx_db works:
Fire Dynamics Simulator

 Current Date     : October 22, 2023  21:03:00
 Revision         : FDS-6.8.0-788-gb74d7c2-master
 Revision Date    : Thu Oct 19 16:39:31 2023 -0400
 Compiler         : Gnu gfortran GCC
 Compilation Date : Oct 22, 2023  20:57:30

 MPI Enabled;    Number of MPI Processes:       4
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Open MPI v4.1.6, package: Open MPI brew@Ventura Distribution, ident: 4.1.6, repo rev: v4.1.6, Sep 30, 2023

 Job TITLE        : Parallel Panel Test, Black PMMA, Propane, 60 kW
 Job ID string    : PMMA_60_kW_2_cm_spyro

 Time Step:      1, Simulation Time:      0.01 s
 Time Step:      2, Simulation Time:      0.03 s
 Time Step:      3, Simulation Time:      0.04 s
 Time Step:      4, Simulation Time:      0.06 s
 Time Step:      5, Simulation Time:      0.07 s
 Time Step:      6, Simulation Time:      0.09 s
 Time Step:      7, Simulation Time:      0.10 s
 Time Step:      8, Simulation Time:      0.12 s
 Time Step:      9, Simulation Time:      0.13 s
 Time Step:     10, Simulation Time:      0.15 s

- ompi_gnu_osx gives an init issue here:

 Fire Dynamics Simulator

 Current Date     : October 22, 2023  21:08:41
 Revision         : FDS-6.8.0-788-gb74d7c2-master
 Revision Date    : Thu Oct 19 16:39:31 2023 -0400
 Compiler         : Gnu gfortran GCC
 Compilation Date : Oct 22, 2023  21:05:53

 MPI Enabled;    Number of MPI Processes:       4
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Open MPI v4.1.6, package: Open MPI brew@Ventura Distribution, ident: 4.1.6, repo rev: v4.1.6, Sep 30, 2023

 Job TITLE        : Parallel Panel Test, Black PMMA, Propane, 60 kW
 Job ID string    : PMMA_60_kW_2_cm_spyro

WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 3
WARNING: Maximum density,  174.296 kg/m3, clipped in Mesh 3
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 4
WARNING: Maximum density,  174.296 kg/m3, clipped in Mesh 4
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
WARNING: Maximum density,  174.296 kg/m3, clipped in Mesh 1
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 2
WARNING: Maximum density,  174.296 kg/m3, clipped in Mesh 2
 Time Step:      1, Simulation Time:     0.009 s
 Time Step:      2, Simulation Time:      0.02 s
 Time Step:      3, Simulation Time:      0.03 s
 Time Step:      4, Simulation Time:      0.04 s
 Time Step:      5, Simulation Time:      0.05 s
 Time Step:      6, Simulation Time:      0.07 s
 Time Step:      7, Simulation Time:      0.08 s
 Time Step:      8, Simulation Time:      0.10 s
 Time Step:      9, Simulation Time:      0.11 s

note I sued gcc 13.2 and openmpi 4.1.6. Will look more into the source of this.

**Comment by marcosvanella** [comment]
With -O1 optimization case also runs fine. So the issue is related to -O2 optimization.

**Comment by johodges** [comment]
![image](https://github.com/firemodels/fds/assets/17127980/1e73cd46-896b-4fff-a19b-7bd7e153dba5)
Looks like changing to -O1 fixes it in the earliest time steps, but we are still seeing some divergence after 100 timestamps. Note the impi case here is a couple commits behind since I am using the nightly build.

**Comment by gforney** [comment]
I'm checking with jeremiah to see if we can install a more recent version of the gnu compilers

**Comment by marcosvanella** [comment]
This is a simpler case that shows the problem. When uncommenting the &CTRL line the time step goes down considerably after 30 steps (gcc 13.2 and openmppi). Note the CTRL is not being used in the calculation. High velocities are seen close to the top open boundary. This might be a compiler bug, I tried several debug compilations flags but did not pickup anything. I'll dig more to see where vars values diverge.

```
&HEAD CHID='PMMA_60_kW_2_cm_spyro', TITLE='Parallel Panel Test, Black PMMA, Propane, 60 kW' /

&MESH IJK=60,40,60, XB=-0.60,0.60,-0.40,0.40,-0.30,0.90 /

&TIME T_END=10.0 /

&REAC ID='PROPANE', FUEL='PROPANE', SOOT_YIELD=0.024, RADIATIVE_FRACTION=0.29 /
&MISC NOISE=F, STRATIFICATION=F/

&MATL ID = 'MINERAL WOOL'
      CONDUCTIVITY = 0.035
      SPECIFIC_HEAT = 0.8
      DENSITY = 70. /

&SURF ID='BURNER', SPEC_ID(1)='PROPANE', MASS_FRACTION(1)=1., HRRPUA=333.3, COLOR='RED', RAMP_Q='fire', MATL_ID='MINERAL WOOL', THICKNESS=0.05, RAMP_Q='fire'/
&RAMP ID='fire', T=  0., F=0.00 /
&RAMP ID='fire', T= 20., F=0.37 /
&RAMP ID='fire', T= 40., F=0.83 /
&RAMP ID='fire', T= 60., F=0.98 /
&RAMP ID='fire', T= 80., F=1.05 /
&RAMP ID='fire', T=120., F=1.05 /
&RAMP ID='fire', T=130., F=0.00 /


&MATL ID            = 'STEEL'
      EMISSIVITY    = 0.9
      DENSITY       = 7800.
      SPECIFIC_HEAT = 0.465
      CONDUCTIVITY  = 43. /

&SURF ID            = 'STEEL'
      MATL_ID       = 'STEEL'
      THICKNESS     = 0.003
      COLOR         = 'BLACK' /

&OBST XB = -0.30,  0.30, -0.14,  0.16, -0.30,-0.00, SURF_IDS = 'BURNER','STEEL','STEEL' /

&VENT MB='ZMAX', SURF_ID='OPEN' /

&DEVC ID='t', QUANTITY='TIME', XYZ=0,0,0 /
#&CTRL ID='2pitdiv10', FUNCTION_TYPE='MULTIPLY', INPUT_ID='CONSTANT','t', CONSTANT=0.62831853 /

&BNDF QUANTITY='GAUGE HEAT FLUX', CELL_CENTERED=T  /
&BNDF QUANTITY='BURNING RATE', CELL_CENTERED=T  /
&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=T  /
&BNDF QUANTITY='RADIATIVE HEAT FLUX', CELL_CENTERED=T  /
&BNDF QUANTITY='CONVECTIVE HEAT FLUX', CELL_CENTERED=T  /
&BNDF QUANTITY='HEAT TRANSFER COEFFICIENT', CELL_CENTERED=T  /

&SLCF PBX=0.00 QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBY=0.00 QUANTITY='VELOCITY', VECTOR=.TRUE. /


&TAIL /
```

**Comment by marcosvanella** [comment]
Jon, do a repo update and try your case again with gnu compilers. Thanks.

**Comment by johodges** [comment]
Moving back to -O2 optimization?

**Comment by marcosvanella** [comment]
Yes, try it with -O2. We have been fixing several uninit variables that were giving issues with gnu and were not picked up by any of the compilers in debug mode.
________________________________

**Comment by marcosvanella** [comment]
ok thanks.
