### ISSUE TITLE
unable to obtain the right layer height

### ISSUE THREAD

**Issue by MrAhriman** [firemodels/fds#12207]
Hello respected colleagues! As a novice in FDS, I am having trouble with the “layer height” function. It seems that the detector is not working properly as it detects the smoke layer height as half the height of the cell in my data. I have tried adjusting the cell size, from 1m to 0.2m, and the problem persists. Any help or suggestions would be greatly appreciated. Thank you for your reply in advance.
[jzwshort.txt](https://github.com/firemodels/fds/files/13211421/jzwshort.txt)

**Comment by drjfloyd** [comment]
The layer height fuction looks for the layer height in the z-direction.  You have redefined gravity and your DEVC XB only has the point z=155 in the z-direction.

**Comment by MrAhriman** [comment]
> The layer height fuction looks for the layer height in the z-direction. You have redefined gravity and your DEVC XB only has the point z=155 in the z-direction.

This is so interesting! Thank you so much for helping me solve this problem. It has been bothering me for a long time.
