### ISSUE TITLE
Issue object disappears at time = 0 [unphysical pressure]

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#12200]
This issue is actually made of two problems.

**PROBLEM 1. Update the FDS file to FDS 6.8.0**
I run the following file with FDS 6.7.6 and 6.7.7 but I did not manage to execute it with a newer version of FDS. So first point is: why is that?

[510562-KRP-P3-CC-L1-Scenario_01-Run_04_ff_680.fds.txt](https://github.com/firemodels/fds/files/13177378/510562-KRP-P3-CC-L1-Scenario_01-Run_04_ff_680.fds.txt)

**PROBLEM 2. Unphysical pressure in corridor**
I have found that when running I generated some unphysical pressure in the corridor (like -800 Pa)

![image](https://github.com/firemodels/fds/assets/7260681/00f832bb-6166-4c0f-a3dd-9dfbeeb3508b)

The reason for that is in the two OBST that are disappearing right at time 0.0s.

![image](https://github.com/firemodels/fds/assets/7260681/fd29f72e-75ef-4d1e-ac63-d98ced0f810d)

If I comment these two OBST in the FDS file I obtain a realistic pressure distribution in the corridor [in the range of -30/-40 Pa]

![image](https://github.com/firemodels/fds/assets/7260681/f6d54c60-3303-4ee5-b082-87addcae9c56)

I do not understand why using the CTRL to make these two OBST disappear is leading to incorrect results.

**Comment by mcgratta** [comment]
Problem 1: The case runs for me, using a single process. What was the error message when you tried to run the case?

**Comment by mcgratta** [comment]
Problem 2: I cannot debug this case because it is too complicated. Simplify the case so that it is clear that there is a problem. You have an HVAC system and when you remove obstructions you may change the pressure in a way that you did not expect. That does not necessarily mean it is an error.

**Comment by drjfloyd** [comment]
10.2.3 in the User's Guide says to not remove VENTs attached to HVAC components.  

&VENT ID='Vent_01_Apartment', SURF_ID='GYPSUM PLASTER', XB=11.0,11.0,-33.0,-32.2,0.0,0.1/ 
&OBST ID='Apartment External Wall', XB=11.0,11.2,-33.0,-32.2,0.0,2.0, SURF_ID='GYPSUM PLASTER', CTRL_ID='invert-2'/

**Comment by rupole1185** [comment]
Allright. So this could be the issue, I have to check it. But is it
possible to add a warning when by mistake the user does this?

Ruggero Poletto
Managing director

VideoCall: calendly.com/ruggero-poletto | Mobile: +39 378 30 33 133

Il dom 29 ott 2023, 19:15 Jason Floyd ***@***.***> ha scritto:

**Comment by rupole1185** [comment]
Hi, 

sorry during the weekend I just quickly read the comments.

For PROBLEM 1.
If I execute the run on FDS 6.8.0 using the normal "fds 510562-KRP-P3-CC-L1-Scenario_01-Run_04_ff_680.fds" the simulation stops after 0.3s of computed time.
If I instead execute it using "fds_openmp 510562-KRP-P3-CC-L1-Scenario_01-Run_04_ff_680.fds" I get the same behaviour.
Not sure why in your case you have a different behaviour

PROBLEM 2.
I though what @drjfloyd said could be the problem. But in my analysis I am having ussue with OBST which are controlled by the DEVC "invert" while the one you mentioned is controlled by "invert-2".

**Comment by mcgratta** [comment]
I started the case on our linux cluster using the official release. It runs. What does your .err file look like?
```

 Starting FDS ...

 MPI Process      0 started on burn010.backend

 Reading FDS input file ...

WARNING: SPEC REAC_FUEL is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.

 Fire Dynamics Simulator

 Current Date     : October 30, 2023  11:40:35
 Revision         : FDS-6.8.0-0-g886e009-HEAD
 Revision Date    : Tue Apr 18 07:06:40 2023 -0400
 Compiler         : ifort version 2021.7.1
 Compilation Date : Oct 30, 2023 11:34:42

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS


 Job TITLE        :
 Job ID string    : 510562-KRP-P3-CC-L1-Scenario_01-Run_04_ff

 Time Step:      1, Simulation Time:      0.03 s
 Time Step:      2, Simulation Time:      0.06 s
 Time Step:      3, Simulation Time:      0.08 s
 Time Step:      4, Simulation Time:      0.11 s
 Time Step:      5, Simulation Time:      0.14 s
 Time Step:      6, Simulation Time:      0.17 s
 Time Step:      7, Simulation Time:      0.20 s
 Time Step:      8, Simulation Time:      0.22 s
 Time Step:      9, Simulation Time:      0.25 s
 Time Step:     10, Simulation Time:      0.28 s
 Time Step:     20, Simulation Time:      0.56 s
 Time Step:     30, Simulation Time:      0.84 s
 Time Step:     40, Simulation Time:      1.12 s
 Time Step:     50, Simulation Time:      1.39 s
```

**Comment by rupole1185** [comment]
This is what I get in my case with 6.8.0 

![image](https://github.com/firemodels/fds/assets/7260681/97281cd2-af1e-45ea-84ed-7b07c981a79b)

**Comment by mcgratta** [comment]
I downloaded the release bundle and installed the modules FDS6 and SMV6 according to the installation instructions. Then I logged into one node on our cluster and ran the case as follows:

![image](https://github.com/firemodels/fds/assets/11333911/7665f439-baaf-483e-b503-5613c5e228fe)
