### ISSUE TITLE
FDS does not create a "_devc_ctrl_log.csv" file; smoke detectors do not trigger

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12202]
### Discussed in https://github.com/firemodels/fds/discussions/12201

<div type='discussions-op-text'>

<sup>Originally posted by **FireResearch-BK** October 27, 2023</sup>
I have a case with smoke detectors which record data, but never trigger. There is also no "[Casename]_devc_ctrl_log.csv" file.

[Case.txt](https://github.com/firemodels/fds/files/13186658/Case.txt)

This is for a fire on a particular floor of a building. The exact same setup with fire, smoke detectors and temperature sensors works just fine on another floor of said building.
Geometry obscuration does not appear to be an issue as the smoke detectors record plausible data and eventually do exceed the obscuration threshold (and should therefore trigger) after around 26 seconds (as per _devc.csv). HRR also develops as intended and there is more than enough smoke around. The detectors also show up in Smokeview.

I let the case run for around 250 seconds, but the detectors still do not trigger while logging > 90 % obscuration.

I have compared the .fds files of the working case for the other floor with this one, but can not spot anything amiss.

FDS version is 6.8.0.

As I am unsure if I'm looking at a bug or [PEBKAC](https://en.wiktionary.org/wiki/PEBKAC) error after all, I'm asking here first.

Note: The "out of mesh" devices are semi-intentional/accepted and a product of Pyrosim's handling regarding scenarios and control logic (too complex to explain here), but should not cause any issue. Deactivating or removing them does not improve things.

&nbsp;

- Edit: 

If I simulate the entire building, not just a single floor, I get a "[Casename]_devc_ctrl_log.csv" file and the detectors trigger just fine.

Could it be that FDS does not like meshes that do not start at or near z = 0, at least for devices with a trigger?
</div>

**Comment by drjfloyd** [comment]
The check for writing the log file was being done before processing the PROP where the SETPOINT for CHAMBER OBSCURATION is defined. There is now a log and running the case shows activation times for all the detectors.

Time (s),Type,ID,State,Value,Units
 2.37769E+01,DEVC,E4_SmokeDetector_4                                          ,T, 3.61502E+00,%/m
 2.46300E+01,DEVC,E4_SmokeDetector_1                                          ,T, 3.36282E+00,%/m
 2.72244E+01,DEVC,E4_SmokeDetector_2                                          ,T, 3.36896E+00,%/m
 2.77854E+01,DEVC,E4_SmokeDetector_3                                          ,T, 3.28715E+00,%/m

**Comment by FireResearch-BK** [comment]
Thanks for fixing this. The trigger times are about what I get when simulating the entire building, too.

Looked at the commit as well. If all fixes were as simple as moving a single line... 😁
