### ISSUE TITLE
Discrepancy in global HRR and O2 consumption calorimetry HRR - Difference with Extinction On and Off

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12229]
I started manually calculating the HRR from FDS simulations of our railcar experiments using O2 consumption calorimetry to investigate the impact of time lag in the hood in our experiments. During this analysis I ran into a discrepancy between the global HRR calculation and the calorimetry measurements. The two attached cases are the exact same except one has an autoignition temperature set for the reaction. The first plot shows the global HRR, the target HRR (MLR x HoC), and the calorimetry HRR. The results are as expected where the global and calorimetry HRR are similar at a lower value than the target due to extinction. The second plot compares the same quantities in the case where no auto ignition temperature is set. The results for the global HRR are as expected where it matches the target since there is no extinction. However, the calorimetry HRR is lower. What are your thoughts?

FYI for the calorimetry calculation I am using the simplified formulation from ASTM 1354:

Q = 13,100 x 1.1 x mdot x (o2_baseline-o2)/(1.105 - 1.5 x o2)

I am calculating mdot from the 'HOOD-VOLUME-FLOW' and 'HOOD-DENSITY' devices. The o2 concentrations are all in mol/mol.

[propane_simple_1reac_noext.txt](https://github.com/firemodels/fds/files/13358204/propane_simple_1reac_noext.txt)
[propane_simple_1reac_ext1.txt](https://github.com/firemodels/fds/files/13358205/propane_simple_1reac_ext1.txt)
![propane_simple_1reac_ext1](https://github.com/firemodels/fds/assets/17127980/310ce572-8b77-46d4-aefd-c93b398c215f)
![propane_simple_1reac_noext](https://github.com/firemodels/fds/assets/17127980/df56bbdb-58a5-490b-bd86-5c4f77f22e92)

**Comment by drjfloyd** [comment]
Could be something with averaging.  You don't have an extraction surface at the top. You are taking the mean volume fraction over the entire top and integrating the volume flow over the entire top.  Some of the mean volume fraction will be ambient air entering from the top in areas with negative w-velocity.   You could put a hood at the top with an HVAC vent with constant volume flow for extraction and in the duct measure the volume fraction and mass flow in the duct. That would eliminate any artifacts from averaging.

The simple hood equation will have some error for propane. The no extinction case won't identically match the actual HRR.  The empirical constants (13100, 1.1, 1.105) will vary fuel-to-fuel.

**Comment by johodges** [comment]
If the averaging was the only source of the difference I would have expected the global and calorimetry results to have a similar offset with and without extinction. I agree that the results won't match exactly, but I would expect them to be a bit closer. The constants for propane are pretty close to what is used in the standard equation (12800, 1.1, 1.084). E and alpha together should account for ~5% variability. 

I'll swap to using the HVAC model with a fixed volume flow and let you know how the results look.

**Comment by johodges** [comment]
I think I figured out what is going on. It looks like there were 3 sources of differences:

1. Time averaging effects which were fixed by swapping to the HVAC model.
2. The ambient species for AIR in the user guide are slightly different than what FDS is actually using. The user guide specifies MASS_FRACTION of O2, H2O, and CO2 as 0.23054, 0.0626, and 0.00046, respectively. The .out file shows 0.23099, 0.00594, and 0.00059 for the lumped AIR species.
3. I was using 29 g/mol MW for air. While it is not explicitly in the equation, I was using it to convert the baseline mass fractions from FDS into volume fractions. FDS uses a value of 28.75 g/mol for air. This actually ended up having a large impact on the results.

The results look reasonable to me after those changes.
![propane_simple_1reac_hvac_noext](https://github.com/firemodels/fds/assets/17127980/35009c47-086b-4d9b-96a6-c046e025636f)
![propane_simple_1reac_hvac_ext1](https://github.com/firemodels/fds/assets/17127980/bc17b15f-6f10-48a9-8f0a-ffb657d604c0)
[propane_simple_1reac_hvac_noext.txt](https://github.com/firemodels/fds/files/13359153/propane_simple_1reac_hvac_noext.txt)
[propane_simple_1reac_hvac_ext1.txt](https://github.com/firemodels/fds/files/13359154/propane_simple_1reac_hvac_ext1.txt)

**Comment by drjfloyd** [comment]
What is in the User's Guide in 12.2  Example 1 and 2 is just an example. It doesn't say that those values are the FDS defaults.  At one point those values were, but we haven't chased them as minor tweaks to species routines do wind up shifting those values slightly.  Those values also change depending on TMPA and HUMIDITY in the input file. Best practice is to use the ambient O2 value that is output at t=0.

What verification case do you think is needed? I don't think we need a verifcation case for calorimetry. That woud put us in the position of having people interpret that as the official NIST method for doing calorimetry with FDS.

**Comment by johodges** [comment]
I was thinking a verification case on calorimetry would be helpful for users who are interested in doing calorimetry through control functions, and a good way to have another check that there is not an unintentional change in default parameters. You bring up a good concern that people may take the implementation as a recommended best practice which we may not want to provide. To avoid that, we could set up the case to perform the calculation using a few of the approaches in standards to not bias the users. If we don't want an example we can close out this issue.

**Comment by mcgratta** [comment]
I agree with Jason. We should definitely make sure that the stoichiometry of `AIR + FUEL -> PRODUCTS` is correct, but how one would make a hood measurement of HRR is another matter. Values like 13,100 are approximate whereas the combustion in FDS is based on fairly precise gas properties.
