### ISSUE TITLE
box_burn_away9

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#12231]
Getting this error with a build this morning on my PC with debug:

C:\github\fds\Verification\Fires>\github\fds\Build\impi_intel_win_db\fds_impi_intel_win_db.exe box_burn_away9.fds

 Starting FDS ...

 MPI Process      0 started on L-PW078R66

 Reading FDS input file ...

 Fire Dynamics Simulator

 Current Date     : November 15, 2023  05:44:32
 Revision         : FDS-6.8.0-952-gdef4f2f-master
 Revision Date    : Tue Nov 14 17:16:56 2023 -0500
 Compiler         : Intel ifort 2021.10.0
 Compilation Date : Wed 11/15/2023  05:42 AM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.10 for Windows* OS

 Job TITLE        : Test BURN_AWAY feature
 Job ID string    : box_burn_away9

forrtl: severe (408): fort: (10): Subscript #1 of the array MATERIAL has value 5111840 which is greater than the upper bound of 3

Image              PC                Routine            Line        Source
fds_impi_intel_wi  00007FF7F265180D  INIT_mp_ADD_MATER        4136  init.f90
fds_impi_intel_wi  00007FF7F2641D32  INIT_mp_FIND_WALL        3874  init.f90
fds_impi_intel_wi  00007FF7F2631DCC  INIT_mp_FIND_WALL        3613  init.f90
fds_impi_intel_wi  00007FF7F2FC653D  FDS_ip_INITIALIZE        2131  main.f90
fds_impi_intel_wi  00007FF7F2F52E34  MAIN__                    276  main.f90
fds_impi_intel_wi  00007FF7FA38B19B  Unknown               Unknown  Unknown
fds_impi_intel_wi  00007FF7FA3FE4A4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFACAF87344  Unknown               Unknown  Unknown
ntdll.dll          00007FFACC7626B1  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
That's a case I added. I'll fix.

**Comment by mcgratta** [comment]
Try it now. I could not reproduce the error on our linux cluster, but I think I know what the problem is.

**Comment by drjfloyd** [comment]
9 is working now.  I am getting an error with 1 on windows.

 Time Step:   1000, Simulation Time:     10.00 s
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds_impi_intel_wi  00007FF6EE17AE46  INITREASSIGN_WALL        4816  init.f90
fds_impi_intel_wi  00007FF6EE179BBD  INIT_mp_REASSIGN_        4624  init.f90
fds_impi_intel_wi  00007FF6EE3120E4  FDS_ip_CREATE_OR_        1590  main.f90
fds_impi_intel_wi  00007FF6EE2F53E7  MAIN__                    785  main.f90
fds_impi_intel_wi  00007FF6F55F9C9B  Unknown               Unknown  Unknown
fds_impi_intel_wi  00007FF6F566CE14  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFACAF87344  Unknown               Unknown  Unknown
ntdll.dll          00007FFACC7626B1  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
Are you running with one MPI process or 4?

**Comment by mcgratta** [comment]
Similar problem to previous. I did not test a burn away case for multiple mesh--single process.

**Comment by drjfloyd** [comment]
both fixes are working
