### ISSUE TITLE
Unexpected mass flux for MMA in a validation case PMMA_60_kW_2_cm_spyro

### ISSUE THREAD

**Issue by ManuelOsburg** [firemodels/fds#12230]
As I am currently working on the new approach "Scaling the Burning Rate by the Heat Flux" (SPyro), I became aware of the validation case _Validation/NIST_NRC_Parallel_Panels/Test_

Two reactions were specified in this case: Propane for the burner and MMA for the PMMA panels.
The attached out-file lists the calculated heat of combustion for these two fuels: 45548.3058 kJ/kg for propane (line 345) and 28820.7346 kJ/kg for MMA (line 379). So far so good.

The respective mass flow of the fuel was calculated for the surfaces as a function of the specified HRRPUA (lines 477 and following):

Propane:
HRR Per Unit Area (kW/m2)    333.3
PROPANE Mass Flux (kg/s/m2)    7.318E-03

MMA:
HRR Per Unit Area (kW/m2)    1.0
MMA Mass Flux (kg/s/m2)    5.484E-05

**I wonder about the calculated mass flux of MMA.** I would have expected the following value:

MMA Mass Flux (kg/s/m2) = HRR Per Unit Area (kW/m2) / Heat of Combustion (kJ/kg) = 1 / 28820.7346 = 3.47-05

[PMMA_60_kW_2_cm_spyro.txt](https://github.com/firemodels/fds/files/13363505/PMMA_60_kW_2_cm_spyro.txt)

**Comment by drjfloyd** [comment]
We found a bug recently (https://github.com/firemodels/fds/issues/12131) for cases with multiple REAC and using the scaling method (actually the bug was found when we were working with modeling this same case).  Try the latest test bundle. https://github.com/firemodels/fds/issues/12131

**Comment by ManuelOsburg** [comment]
Thank you very much! The latest FDS test version calculates the mass flux for MMA correctly.

MMA Mass Flux (kg/s/m2)   3.470E-05
