### ISSUE TITLE
Total mass flux wall

### ISSUE THREAD

**Issue by solenick** [firemodels/fds#12239]
I was working on a model and I added in some devices for mass flux, mass flux wall, and total mass flux wall just to verify the mass flux injection of species on a wall (vent is flat on a vertical wall, not a floor or ceiling).  When I examined the output, I noticed that, consistent with the User's Guide, mass flux and mass flux wall were similar, but total mass flux wall was quite different.  Different enough that I didn't think it was the just not having the diffusive contribution included.  
I went to the mass_flux_comparison example and ran it and found good agreement between all of these values, as is shown in Figure 22.6 of the User's Guide.  But the species injection vent in this example is flat in the Z direction.  I then altered the example so that species are flowing both from a horizontal vent and a vertical vent.  The horizontal vent (flat in Z) still looks fine, but the vertical vent (flat in X) again shows the mass flux and mass flux wall as similar, with the total mass flux wall being very different, even negative at times.  The altered example case is attached.
I don't think this is a high priority issue, as this is likely not an often used output, but can you see if this is a bug? Or if the behavior is expected, can you explain why?  Thank you.

[mass_flux_comparison_totalmassfluxwalltest.txt](https://github.com/firemodels/fds/files/13393407/mass_flux_comparison_totalmassfluxwalltest.txt)

**Comment by mcgratta** [comment]
I ran the case. Which of the devices should I be looking at?

**Comment by drjfloyd** [comment]
I think the issue is the triplet of 1-3 shows good agreement (top of OBST) but the triplet of 8-10 (side of OBST) does not.

![image](https://github.com/firemodels/fds/assets/12799217/3b0bef9c-f291-4bd2-a740-53400925ee10)

**Comment by solenick** [comment]
Sorry.  Was in a meeting.  Jason hit it on the nose.  Triplet 1-3 show good agreement, while 8-10 do not.  Thanks.

**Comment by mcgratta** [comment]
OK, this is a puzzler. Thanks.

**Comment by mcgratta** [comment]
I think I got it. This looks to be a problem of adding the advective and diffusive mass flux terms. The sign of the diffusive term at the solid boundary is based on the outward facing normal direction. In calculating the `TOTAL MASS FLUX`, we did not take that sign convention into account. That's why `IOR=3` is right and `IOR=-1` is wrong. Luckily, this only affects the output quantity. The actual machinery within the code is correct.

**Comment by solenick** [comment]
Thank you for taking a look.  I appreciate it.

**Comment by mcgratta** [comment]
Thanks for reporting it. This output quantity is not commonly used which is why this bug eluded us.

**Comment by solenick** [comment]
My pleasure.  I was agonizing over what I was doing wrong!

**Comment by mcgratta** [comment]
Well, the big hint you gave me was the fact that it worked for `IOR=3`. These sign issues are always tricky when dealing with solid surfaces.
