### ISSUE TITLE
Different outputs with and without restart with lagrangian particles

### ISSUE THREAD

**Issue by ImmyR** [firemodels/fds#12251]
I have been modelling the burning of pine needles, using Lagrangian particles to represent the fuel. I use my organisation's cluster to run the simulations, and the jobs get timed out after 24hrs - I use DT_RESTART=5 to put in periodic save points, and then restart from there after it times out of the cluster. 

In my simulations I am getting to around 12s before it times out, so when I restart it goes again from 10s - but I am seeing noticeably different results from the restarted simulation in that overlap time (see graph of hrr vs time)

![hrr_comparison](https://github.com/firemodels/fds/assets/5166642/1ba264cc-e27d-499b-997f-0b793cd8636a)

I tried the same situation but modelling the fuel with a solid OBST line, instead of particles and got the same outputs with the original run and on the restart, so I think the issue must be related to the Lagrangian particles.

I've simplified my input file so shouldn't take 24 hours to run any more, but the issue can still be seen if you kill the job before its end
[restart-problems.txt](https://github.com/firemodels/fds/files/13499812/restart-problems.txt)

**Comment by ericvmueller** [comment]
what FDS version are you using? There was a change with particles that introduced an issue with restart ([#12073](https://github.com/firemodels/fds/pull/12073)) but this was caught and fixed ([#12194](https://github.com/firemodels/fds/pull/12194)). So if you happen to be using a version between these commits then try a more recent nightly build.

**Comment by ericvmueller** [comment]
Testing your example with the most recent code, I compared a full run to 10s agains a run that was stopped and restarted from data saved at 5s. There are some small differences in the fluctuations but the results look consistent to me.

![image](https://github.com/firemodels/fds/assets/13366803/fa6bd20d-273a-4291-a848-6e9ccdbee6cd)

**Comment by ericvmueller** [comment]
Closing this since we haven't heard anything. Reopen if you still have an issue, @ImmyR
