### ISSUE TITLE
PLOT3D files naming convention from version 6.7.7 to 6.7.8

### ISSUE THREAD

**Issue by SamuelAPASO** [firemodels/fds#12265]
Hello,

I noticed a difference in the fds/Source/dump.f90 file concerning the writing of PL3D files:
In the version 7.7.7 file, _ (lines 5660 and 5661) is used instead of p in version 7.7.8 (lines 5347 and 5348) between ITM and ITM1.
Is there a reason for this change? (I use scripts that use the names of PL3D output files)

Thank you in advance.

**Comment by mcgratta** [comment]
No particular reason other than to clean things up and reduce the number of extra zeros. Is there a problem with the new way of writing the files?

**Comment by SamuelAPASO** [comment]
No, the files write fine, but I convert them into VTK files for display on Paraview. This name change seems to prevent VTK files from being generated correctly over time.
