### ISSUE TITLE
profile csv not properly initialized with INIT_ID

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#12272]
Following 22.3 in the User Guide I tried using a profile quantity on a particle. For example, adding the following line to `char_oxidation_2.fds`:

`&PROF ID='rho_char', INIT_ID='dry needle init', QUANTITY='DENSITY', MATL_ID='CHAR' /`

However, it looks like a profile tied to an `INIT_ID` wont find the appropriate `PROFILE(N)%MESH` number in `READ_PROF`, so then this loop is always cycled:
https://github.com/firemodels/fds/blob/bb142eb46aefebe98393a00cedebfa18c3e50c50/Source/dump.f90#L1349-L1368

The result is that the file name and header are never set and the data are written to a `fort.x` file.

**Comment by mcgratta** [comment]
This looks like a case where the initialization of the PROFile file was done before the particle and PROFile were properly set up. Should be fixed. Test it and close if it's working.

**Comment by ericvmueller** [comment]
Looks good now - thanks!
