### ISSUE TITLE
Problem with REAC 1

### ISSUE THREAD

**Issue by PavloNike** [firemodels/fds#12271]
Hi all,

I am trying to model a building with a mineral oil fire reaction. I also need to measure CO and HCN concentrations so added gas phase devices. I took all the data from SFPE as usual but am stuck with an issue I receive: "Problem with REAC 1" and can't find a solution to it at all. Standard reactions work so there is some issue with my reaction input. I would much appreciate if someone can check my fds file (I coipied it to the attached doc file here). Thanks a lot in advance.

[Copy of fds file.docx](https://github.com/firemodels/fds/files/13610697/Copy.of.fds.file.docx)

**Comment by mcgratta** [comment]
Have you checked the table of REAC parameters at the end of the User's Guide to see if all those parameters are still used?
