### ISSUE TITLE
fds2ascii outputfile is incomplete

### ISSUE THREAD

**Issue by zhang-zhen-project** [firemodels/fds#12283]
I'm very sorry to bother you, but this issue confuze me a while, that is, when I used fds2ascii to output SLCF file to csv, I input the min/max y were 0 and 200 , but I just got the data between 0 to 85, I am sure my model and SCLF setting include the whole 0-200.

  Thank you very much! And following is  more detail about this probelm:

                    Enter Job ID string (CHID):
                    SZtunnel0m
                     What type of file to parse?
                     PL3D file? Enter 1
                     SLCF file? Enter 2
                     BNDF file? Enter 3
                    2
                     Enter Sampling Factor for Data?
                     (1 for all data, 2 for every other point, etc.)
                    1
                     Domain selection:
                       y - domain size is limited
                       n - domain size is not limited
                       z - domain size is not limited and z levels are offset
                       ya, na or za - slice files are selected based on type and location.
                           The y, n, z prefix are defined as before.
                    y
                     Enter min/max x, y and z
                    0 20 0 200 3.1 3.1
                     Enter starting and ending time for averaging (s)
                    201 202
                    How many variables to read:
                    3
                    Enter index for variable 1
                    1
                    Integral of  CARBON MONOXIDE VOLUME FRACTION =   2.1408E-06
                    Enter index for variable 2
                    2
                    Integral of  SOOT VOLUME FRACTION =   1.3740E-05
                    Enter index for variable 3
                    3
                    Integral of  TEMPERATURE =   3.4133E+04
                    Enter output file name:
                    y201201.csv
                     Writing to file...      y201201.csv
                    Stop - Program terminated.

**Comment by zhang-zhen-project** [comment]
Is an fds2ascii that does not support parallel computing? Thank you^_^

**Comment by drjfloyd** [comment]
After entering the start and end time you will see a list of all the slice files available. Look closely at those names. For each &SLCF input, there will be one slice file for each mesh that slice passes through.  You will need to process the slice data for each mesh.
