### ISSUE TITLE
Numerical Instability FSD 6.7.9

### ISSUE THREAD

**Issue by JSCOLTUK** [firemodels/fds#12281]
Good afternoon

I have a rather large model that seems to crash at 330s into the simulation due to a numerical instability. 
I have had previous versions of this model run through without issue however the problem seems to have come about when I added in a supply surface to the head of the stairwell.
I have been through and ensured that there are no single cell open surfaces and replaced them with HVAC leaks. 
The extract/supply surface are not active until all doors in the simulation are open so this should not be the cause

I have attached my most recent revision of this model, which we have run in FDS 6.7.9 to no success

Any help on this would be greatly appreciated

Regards, 

James
[R10.zip](https://github.com/firemodels/fds/files/13663097/R10.zip)

**Comment by mcgratta** [comment]
First, run this with the latest version of FDS, 6.8.0. If it still fails, try to simplify the case. Then submit the .fds file, not the psm file.

**Comment by JSCOLTUK** [comment]
Hi Kevin

Unfortunately at the moment I do not have access to 6.8.0 - have asked our IT Dept to download for me
Please see attached .fds file in the meantime
[R10.zip](https://github.com/firemodels/fds/files/13670576/R10.zip)

**Comment by mcgratta** [comment]
How long did this take to run? I started the case and it will probably take a week. Are you trying to run the case on a single computer?

In any event, add this line to the file

&PRES MAX_PRESSURE_ITERATIONS=50 /

**Comment by mcgratta** [comment]
The original case failed with the latest source code. I am going to try
with a tighter pressure tolerance.

**Comment by mcgratta** [comment]
The tighter pressure tolerance failed too. Both cases fail at 320, when
there is a very rapid change in ventilation conditions. My next suggestion
is to make the transition over, say, 10 s instead of 1.

==> COLT2.err <==
 Time Step:  29500, Simulation Time:    318.86 s
 Time Step:  29600, Simulation Time:    319.70 s
 Time Step:  29658, Simulation Time:    320.08 s

ERROR: Numerical Instability - FDS stopped (CHID: COLT2)

==> COLT.err <==
 Time Step:  29500, Simulation Time:    318.74 s
 Time Step:  29600, Simulation Time:    319.58 s
 Time Step:  29679, Simulation Time:    320.10 s

ERROR: Numerical Instability - FDS stopped (CHID: COLT)

**Comment by mcgratta** [comment]
I have run the case beyond the point of failure by combining the stairwell into one mesh.  These cases with long shafts can often have trouble related to the pressure solver. I will leave the case running and report if it succeeds.

**Comment by JSCOLTUK** [comment]
Hi Kevin,

Unfortunately we are still having issues with this model, we have made the staircase mesh whole, also max pressure iterations are 50. Is there anything else that was changed that we could try?
Is it possible for you to send the output files over please?

Kind regards,

James

Please note my working hours are 8am-4.30pm Monday to Thursday and 8am-1pm Friday


James Speke, Mechanical Engineering BEng Hons
Sales Engineer
Colt International Limited | Ridgeway Office Park - Bedford Rd | GU32 3QF Petersfield | United Kingdom
 Tel: +44 23 9249 1898
 ***@***.*** | www.coltinfo.co.uk

Keep up to date on hot industry topics with the Colt blog. Click to subscribe.


For Colt's email confidentiality and monitoring policy, usage restrictions, or for company registration and regulatory status information, please visit www.coltinfo.co.uk/legal-notice.html

v1237231
From: Kevin McGrattan ***@***.***>
Sent: 02 January 2024 19:27
To: firemodels/fds ***@***.***>
Cc: James Speke ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [firemodels/fds] Numerical Instability FSD 6.7.9 (Issue #12281)

[EXTERNAL EMAIL] This email is from an external sender. Do not click links or open attachments unless you recognise the sender and know the content is safe.
________________________________
Closed #12281<https://github.com/firemodels/fds/issues/12281> as completed.

**Comment by mcgratta** [comment]
[COLT3.txt](https://github.com/firemodels/fds/files/13904358/COLT3.txt)
Try this input file, and use the latest FDS nightly build.

**Comment by mcgratta** [comment]
Did this solve your problem?

**Comment by JSCOLTUK** [comment]
Hi Kevin

Yes thank you very much for your help

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

James Speke, Mechanical Engineering BEng Hons
Sales Engineer
Colt International Limited | Ridgeway Office Park - Bedford Rd | GU32 3QF Petersfield | United Kingdom
 Tel: +44 23 9249 1898
 ***@***.*** | www.coltinfo.co.uk

Keep up to date on hot industry topics with the Colt blog. Click to subscribe.


For Colt's email confidentiality and monitoring policy, usage restrictions, or for company registration and regulatory status information, please visit www.coltinfo.co.uk/legal-notice.html

v1237231
________________________________
From: Kevin McGrattan ***@***.***>
Sent: Monday, February 12, 2024 8:23:03 PM
To: firemodels/fds ***@***.***>
Cc: James Speke ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [firemodels/fds] Numerical Instability FSD 6.7.9 (Issue #12281)


[EXTERNAL EMAIL] This email is from an external sender. Do not click links or open attachments unless you recognise the sender and know the content is safe.
________________________________
Did this solve your problem?

**Comment by mcgratta** [comment]
```
However I’m now running an iteration of one of the floors above and I’m having similar issues even with the fixes that we made last time. Is there something I am doing wrong?
```
I'll say. Your mistake is thinking that I have some mystical power to not only recall the details of this issue, but also to guess what might be the next problem. 

Start a new issue. Explain the new problem, and submit a simplified input file.
