### ISSUE TITLE
Inconsistency in HVAC_PRES_RELAX default in user guide

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12287]
The source code sets the default for HVAC_PRES_RELAX to 1 (cons.f90 line 704), which is aligned with the user guide in Section 10.2. However, table 23.17 in the user guide lists the default value of 0.5. My assumption is the intended default is 1 and the fix is just to update the table. I wanted to verify the intended default is 1 before committing the change.

**Comment by drjfloyd** [comment]
Thanks for catching that oversight. Source is correct if you want to do the change. Changed the default when I modified how I dealt with pressure at VENTs connected to HVAC.

**Comment by johodges** [comment]
Fixed in https://github.com/firemodels/fds/pull/12288
