### ISSUE TITLE
Redundant variables within boundary derived types

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12304]
Why are there entries for `TMP_G` etc in `CFACE_TYPE` and `BOUNDARY_PROP1_TYPE`?

```
   REAL(EB) :: RSUM_G=0._EB              !< \f$ R_0 \sum_\alpha Z_\alpha/W_\alpha \f$ in first gas phase cell
   REAL(EB) :: TMP_G                     !< Temperature (K) in adjacent gas phase cell
   REAL(EB) :: RHO_G                     !< Gas density (kg/m3) in adjacent gas phase cell
   REAL(EB) :: MU_G=0.1_EB               !< Viscosity, \f$ \mu \f$, in adjacent gas phase cell
```

**Comment by marcosvanella** [comment]
In THERMAL_BC (first call in WALL_BC) in wall.f90 we have a loop on CFACES where TMPG,RHO_G,ZZ_G etc, are computed in the CFA entry in a call to CFACE_THERMAL_GASVARS and then just loaded to the B1 Prop data structure. We should be able to load them directly into B1 and get rid of the redundant arrays in CFACE. 

I noted that: Later, some of the TMP_G, RHO_G and ZZ_G variables get loaded into B1 for particles, wall cells and cfaces in SPECIES_BC, SOLID_HEAT_TRANSFER_1D, and  HVAC_BC. This seems unnecessary, provided these vars were loaded into B1 in THERMAL_BC and not changed afterwards.

**Comment by marcosvanella** [comment]
In PR #12330 I dropped TMP_G, RHO_G, ZZ_G from CFA and we use the B1 entries for these now. I kept RSUM_G, MU_G in CFA as there are no B1 counterparts. We'll let firebot chew on this tonight.

**Comment by marcosvanella** [comment]
These seem to be working correctly.
