### ISSUE TITLE
Sprinklers Stop Operating

### ISSUE THREAD

**Issue by dmmcmahon-lanl** [firemodels/fds#12305]
Are there any issues with sprinklers being near an obstruction? 

I am modeling a fire next to a wall with a sprinkler located one meter from the wall. The sprinkler actuates but stops spraying water about 230 seconds into a 1000 second simulation. If I move the fire and sprinkler to the center of the room, the sprinkler works fine and mitigates the HRR.

**Comment by drjfloyd** [comment]
We did fix a bug related to sprinkler variables a short while back that could cause those symptoms (it was an error in resetting pointers when particles were culled). Try your case with the latest test bundle.

https://github.com/firemodels/test_bundles/releases

**Comment by dmmcmahon-lanl** [comment]
Thanks will try that.

**Comment by drjfloyd** [comment]
Did the test bundle work?
