### ISSUE TITLE
Run_all.sh does not stop cases with concatenated input files

### ISSUE THREAD

**Issue by shostikk** [firemodels/fds#12309]
Concatenated input files are named CHID_cat. 
Run_all.sh script under the validation folders does not recognize that and creates CHID.stop files instead. 

How to create CHID_cat.stop files?

**Comment by mcgratta** [comment]
I'll fix.

**Comment by mcgratta** [comment]
Glenn -- can you modify `qfds.sh` so that if the argument `-m N` is given, then the script will write both `CHID.stop` and `CHID_cat.stop`.  I cannot figure out exactly how to do this.

**Comment by rmcdermo** [comment]
Why don't we just stop the code on either?  That is, let's "inquire" on:
```
INQUIRE(FILE=TRIM(CHID)//'.stop',EXIST=EX)
```
and
```
INQUIRE(FILE=TRIM(CHID)//'_cat.stop',EXIST=EX)
```

**Comment by mcgratta** [comment]
We could do that too. That is probably easier.

**Comment by mcgratta** [comment]
Actually, after looking at it some more, it would be easier for `qfds.sh` to create the two versions of the stop file.

**Comment by shostikk** [comment]
Sounds good to me!

**Comment by mcgratta** [comment]
update your fds repo.  Glenn made the change in qfds.sh to touch casename_cat.stop files .  wasn't sure how to test.  give it a try and let me know if you see any problems

**Comment by mcgratta** [comment]
Did this fix the problem?

**Comment by shostikk** [comment]
Yes it did. Thank you!
