### ISSUE TITLE
Wind velocity is not right at reference elevation

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12300]
In this case, the specified wind speed is not achieved at the reference elevation
```
&HEAD CHID='Case_6_new' TITLE='Description of flt1fuel1mps' /

&TIME T_END=360. /

&MULT ID='Meshes' DX=200. I_UPPER=3 DY=200 J_UPPER=3 /
&MESH IJK=50,50,50 MULT_ID='Meshes' XB=-400.,-200.,-400.,-200.,0.00,200. /

&VENT MB='XMIN' SURF_ID='OPEN' /
&VENT MB='XMAX' SURF_ID='OPEN' /
&VENT MB='YMIN' SURF_ID='OPEN' /
&VENT MB='YMAX' SURF_ID='OPEN' /
&VENT MB='ZMAX' SURF_ID='OPEN' /

&DEVC ID='u', XB=10,10,10,10,1,199, POINTS=50 QUANTITY='U-VELOCITY' /
&DEVC ID='T', XB=10,10,10,10,1,199, POINTS=50 QUANTITY='TEMPERATURE' /

&SLCF PBY=0.00 QUANTITY='VELOCITY' /
&SLCF PBY=0.00 QUANTITY='TEMPERATURE' VECTOR=T /

&WIND SPEED=1., DIRECTION=270, L=-100., Z_0=0.03, Z_REF=20 /

&TAIL /
```

**Comment by mcgratta** [comment]
![image](https://github.com/firemodels/fds/assets/11333911/0fc09d87-a030-4f1b-ba37-8c3421968d21)

**Comment by mcgratta** [comment]
The reference temperature and velocity were not exactly achieved at the reference elevation. They should now be.

**Comment by mcgratta** [comment]
You can download a [test version](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST) of FDS that fixes the issue of reference velocity, temperature and height. Check that things work and then we can address other issues if they still exist.

**Comment by shahabck3** [comment]
Thanks, Kevin,
I will give it a go!

**Comment by mcgratta** [comment]
Did this fix the problem?

**Comment by shahabck3** [comment]
I think the problem is fixed Kevin.
Cheers

**Comment by mcgratta** [comment]
Thanks for checking.

**Comment by shahabck3** [comment]
Dear Kevin,
I have to say that I don't know how, but still I get incorrect results in some cases.

I ran two cases with a stable stratification, and the wind readings were lower than specified at the reference height.

**Comment by mcgratta** [comment]
Are you saying you don't know how to install a nightly build? The nightly builds are [here](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST).

**Comment by shahabck3** [comment]
No, I'm saying that I ran some tests with the nightly build, but the windspeed was lower than specified at reference elevation.

**Comment by mcgratta** [comment]
Could you post a case that has a lower than specified wind speed.

**Comment by shahabck3** [comment]
Sure, here is the case for 2m/s wind @ 6m reference height.
But the readings at 6m is around 1.6m/s
[flt1fuel2mps_line.csv
[flt1fuel2mps.txt](https://github.com/firemodels/fds/files/13952608/flt1fuel2mps.txt)
](https://github.com/firemodels/fds/files/13952597/flt1fuel2mps_line.csv)

**Comment by mcgratta** [comment]
You  need to establish the `GROUND_LEVEL` on the `WIND` line.

**Comment by mcgratta** [comment]
It is difficult to debug your case because the vertical grid resolution is 2 m. Look at this case
```
&HEAD CHID='wind' /
&TIME T_END=300. /
&MESH IJK=100,100,20, XB=-50.,50.,-50.,50.,1.,21. /
&VENT DB='XMIN' SURF_ID='OPEN' /
&VENT DB='XMAX' SURF_ID='OPEN' /
&VENT DB='YMIN' SURF_ID='OPEN' /
&VENT DB='YMAX' SURF_ID='OPEN' /
&VENT DB='ZMAX' SURF_ID='OPEN' /
&DEVC ID='u', XB=0,0,0,0,1.5,20.5, POINTS=20, QUANTITY='U-VELOCITY' /
&SLCF PBY=0.00 QUANTITY='TEMPERATURE' VECTOR=T /
&WIND SPEED=2., DIRECTION=270., L=1000000 , Z_0=0.03, Z_REF= 6, GROUND_LEVEL=1 /
&TAIL /
```

**Comment by mcgratta** [comment]
Anything further on this issue? Are you still having trouble?

**Comment by shahabck3** [comment]
I am running a simulation with a smaller mesh size, but it's taking a bit of time.
I will let you know as soon as it finishes.

**Comment by mcgratta** [comment]
I'm going to close the issue. Start a new issue if there are still problems, or reopen this one.
