### ISSUE TITLE
How to measure Inside wall temperature

### ISSUE THREAD

**Issue by Elephant01XLY** [firemodels/fds#12328]
Hi there, I try to get the inside wall temperature when running the FDS program. However, the temperature of "solid02","solid03","solid04","solid05" remained unchanged throughout the whole simulation, which keep at room temperature. My codes are attached blow:

layersolidphase.fds
Generated by PyroSim - Version 2019.1.0515
2024-1-2 11:13:34

&HEAD CHID='layersolidphase'/
&TIME T_END=1800.0/
&DUMP RENDER_FILE='layersolidphase.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='Mesh01', IJK=20,20,20, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1,
      RADIATIVE_FRACTION=0.35/

&DEVC ID='THCP', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.4/
&DEVC ID='THCP01', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.34/
&DEVC ID='THCP02', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.32/
&DEVC ID='THCP03', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.22/
&DEVC ID='THCP04', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.12/
&DEVC ID='THCP05', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.1/
&DEVC ID='THCP06', QUANTITY='THERMOCOUPLE', XYZ=0.5,0.5,0.04/
&DEVC ID='SOLID', QUANTITY='INSIDE WALL TEMPERATURE', XYZ=0.5,0.5,0.34, IOR=3/
&DEVC ID='SOLID01', QUANTITY='INSIDE WALL TEMPERATURE', XYZ=0.5,0.5,0.32, IOR=3/
&DEVC ID='SOLID02', QUANTITY='INSIDE WALL TEMPERATURE', XYZ=0.5,0.5,0.22, IOR=3/
&DEVC ID='SOLID03', QUANTITY='INSIDE WALL TEMPERATURE', XYZ=0.5,0.5,0.12, IOR=3/
&DEVC ID='SOLID04', QUANTITY='INSIDE WALL TEMPERATURE', XYZ=0.5,0.5,0.1, IOR=3/
&DEVC ID='SOLID05', DEPTH=0.12, QUANTITY='INSIDE WALL TEMPERATURE', XYZ=0.5,0.5,0.22, IOR=-3/

&MATL ID='STEEL',
      FYI='Drysdale, Intro to Fire Dynamics - ATF NIST Multi-Floor Validation',
      SPECIFIC_HEAT=0.46,
      CONDUCTIVITY=45.8,
      DENSITY=7850.0,
      EMISSIVITY=0.95/
&MATL ID='YELLOW PINE',
      FYI='Quintiere, Fire Behavior - NIST NRC Validation',
      SPECIFIC_HEAT=2.85,
      CONDUCTIVITY=0.14,
      DENSITY=640.0,
      HEAT_OF_COMBUSTION=2.0E4,
      N_REACTIONS=1,
      REFERENCE_TEMPERATURE=100.0/

&SURF ID='steel',
      RGB=146,202,166,
      TEXTURE_MAP='psm_metal.jpg',
      TEXTURE_WIDTH=3.0,
      TEXTURE_HEIGHT=2.0,
      BURN_AWAY=.TRUE.,
      BACKING='VOID',
      MATL_ID(1,1)='STEEL',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.02/
&SURF ID='pine',
      RGB=146,202,166,
      TEXTURE_MAP='psm_spruce.jpg',
      TEXTURE_WIDTH=0.67056,
      TEXTURE_HEIGHT=2.4384,
      BURN_AWAY=.TRUE.,
      BACKING='VOID',
      MATL_ID(1,1)='YELLOW PINE',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.2/
&SURF ID='burner',
      COLOR='RED',
      TEXTURE_MAP='psm_fire.jpg',
      HRRPUA=5000.0,
      TMP_FRONT=300.0/

&OBST ID='steel1', XB=0.25,0.75,0.25,0.75,0.1,0.12, THICKEN=.TRUE., SURF_ID='steel'/ 
&OBST ID='pine', XB=0.25,0.75,0.25,0.75,0.12,0.32, THICKEN=.TRUE., SURF_ID='pine'/ 
&OBST ID='steel2', XB=0.25,0.75,0.25,0.75,0.32,0.34, THICKEN=.TRUE., SURF_ID='steel'/ 

&VENT ID='Mesh Vent: Mesh01 [XMAX]', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 
&VENT ID='Mesh Vent: Mesh01 [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,1.0,0.0,1.0/ 
&VENT ID='Mesh Vent: Mesh01 [YMAX]', SURF_ID='OPEN', XB=0.0,1.0,1.0,1.0,0.0,1.0/ 
&VENT ID='Mesh Vent: Mesh01 [YMIN]', SURF_ID='OPEN', XB=0.0,1.0,0.0,0.0,0.0,1.0/ 
&VENT ID='Mesh Vent: Mesh01 [ZMAX]', SURF_ID='OPEN', XB=0.0,1.0,0.0,1.0,1.0,1.0/ 
&VENT ID='burner', SURF_ID='burner', XB=0.2,0.8,0.2,0.8,1.0E-3,1.0E-3/ 

&BNDF QUANTITY='WALL TEMPERATURE'/

&SLCF QUANTITY='TEMPERATURE', PBY=0.5/
&SLCF QUANTITY='TEMPERATURE', PBZ=0.22/

&TAIL /

Thanks a lot!

**Comment by drjfloyd** [comment]
XYZ for a solid phase device defines the wall cell the device is applied to. They do not define the depth into the material. That is done with the DEPTH parameter. Your devices do not have DEPTH.

For 1D heat transfer FDS only uses the SURF that is applied to the exposed wall cell. In your case, the SURF for the exposed wall cells on the top and bottom is 2 cm of steel.  If you want heat transfer from top to bottom to be steel, wood, steel then you need to apply that as a SURF.

**Comment by Elephant01XLY** [comment]
Thanks a lot. But I don't understand about the SURF. I have defined different SURF—— "steel and yellow pine" for three parts, respectively. What should I do further?

**Comment by drjfloyd** [comment]
With 1D heat transfer, FDS only uses the SURF assigned to the exposed wall cell. It does not assemble a new SURF based on SURF assigned to a collection of OBST. Your heat transfer top to bottom is only be computed as a 2 cm piece of steel.  You need to make the top and bottom a layered SURF that defines the materials from top to bottom. See the FDS User's Guide chapter on Heat Conduction for details and examples.

**Comment by Elephant01XLY** [comment]
Thank you! I look through the FDS User's Guide but I can find a chapter of Heat Conduction, can you give me the chapter number or pages.
Do you mean I should create one OBST and then define three different surface layer?
If so, I have another question. Is there any way I can calculate a collection of OBSTs with different SURF?

**Comment by drjfloyd** [comment]
Yes, you need a SURF with 3-layers to apply to the top and bottom.

To havve OBST with different SURF connected for heat transfer you would need to use the 3D heat transfer, however, (@mcgratta please correct me if I am wrong) I don't think the current FDS test version for that fully supports pyrolysis in 3D with burnaway.

![image](https://github.com/firemodels/fds/assets/12799217/0bb920c4-0619-47c3-9048-20e5d99ff7a3)

**Comment by Elephant01XLY** [comment]
Thanks a lot!
