### ISSUE TITLE
Numerical instabilities in Catchpole cases

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12326]
I am re-running the `USFS/Catchpole` cases and I've had a few numerical instabilities:
```
USFS_Catchpole/Current_Results/EXSC19.err:ERROR: Numerical Instability - FDS stopped (CHID: EXSC19)
USFS_Catchpole/Current_Results/EXSC35.err:ERROR: Numerical Instability - FDS stopped (CHID: EXSC35)
USFS_Catchpole/Current_Results/EXSC50.err:ERROR: Numerical Instability - FDS stopped (CHID: EXSC50)
USFS_Catchpole/Current_Results/EXSC72.err:ERROR: Numerical Instability - FDS stopped (CHID: EXSC72)
USFS_Catchpole/Current_Results/EXSC74.err:ERROR: Numerical Instability - FDS stopped (CHID: EXSC74)
USFS_Catchpole/Current_Results/EXSC9.err:ERROR: Numerical Instability - FDS stopped (CHID: EXSC9)
```
Note that hundreds of these cases have run successfully, and in the cases that did not, the instability occurs late in the run. Some are related to the downstream boundary condition, and some are related to high temperatures near the surface. Can you look at the input files for these cases and tell me if any of the parameters are "stale". The output files are at 
```
/home/mcgratta/firemodels/fds/Validation/USFS_Catchpole/Current_Results
```

**Comment by ericvmueller** [comment]
Taking a look now. I've had instabilities with fire spread where the flame front reaches an open `WIND` boundary. I'll have to refresh my memory of these cases, but that may be something to investigate in general.

**Comment by ericvmueller** [comment]
Were these the only instabilities? To me they all look related to the downstream boundary. 

I'm testing EXSC19 with more of a 'wind tunnel' approach of an inlet and a typical open boundary downstream. If that works we can run them all this way (until/unless we make `WIND` boundaries more stable with combustion at the boundary). I have updated the template and regenerated the files so I can push them if the test works and you're happy to take that approach.

**Comment by mcgratta** [comment]
OK, only 6 cases failed. I'll let the rest finish and then rerun with the alternate BC.

**Comment by ericvmueller** [comment]
The test of `EXSC19` with the different boundary conditions finished fine. 

It looks like this change slows the spread rate a bit because the flow isn't being driven at the downstream boundary in the same way. I'm not sure how we're doing against the whole dataset, but this would take us further from the experiment in this case ...but to me these boundary conditions seem more representative of the wind tunnel. Anyhow, I can push the files with the alternate BC if you want to do the full comparison.

**Comment by mcgratta** [comment]
Thanks. I'm testing a few things too. Let's hold off on changing the input files until we're sure things are working better.

**Comment by mcgratta** [comment]
I ran the case EXSC35.fds on burn with the same git hash and compiler version. It ran without the instability. The results on the two  computers diverged after about 10 s. In any event, this suggests that these instabilities are hard to "trap". I'm going to try one thing on blaze to see if I can get the six cases to run.

**Comment by mcgratta** [comment]
I made some progress on the wind boundary condition. I am now testing whether we only need to apply special wind BCs on upwind-facing external boundaries where the flow is incoming. In test cases, this has eliminated having to apply wind-related pressure conditions at the downwind boundary. Upwind and lateral boundaries remain unaffected. I'm going to test the six Catchpole cases that failed.

**Comment by ericvmueller** [comment]
Sounds good. I also tested making the ignition line 1 cell wider to be sure that the first row of particles is ignited in no/low wind cases. It looks to allow spread in some cases that did not before (eg. EXSC42), but the cases with large sticks are still problematic. 
We may also want to update the specific heat ramp to match what we do for other vegetation in Utilities/Input_Libraries/MATL unless there is a specific reason to go up to 5 KJ/kg/K here.

**Comment by mcgratta** [comment]
The latest PR fixed the Catchpole instabilities and does not adversely affect the CSIRO cases.
