### ISSUE TITLE
Liquid fuel cannot be ignited

### ISSUE THREAD

**Issue by MeloQuan** [firemodels/fds#12338]
Dear all,

I am trying to simulate a finite rate liquid combustion. I set up a round pool and a small igniter. The model runs but the fuel does not ignite. And there is a warning: SPEC MYFUEL is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.

My input is below:

&HEAD CHID='COMB_test5'/
&TIME T_END=25/
&DUMP MASS_FILE=.TRUE./
&MISC SIMULATION_MODE='DNS'/

&MESH ID='Mesh01-01', IJK=40,40,40, XB=0.08,0.2,2.48,2.6,0.0,0.12/
.....
&MESH ID='Mesh04-04', IJK=40,40,40, XB=0.2,0.32,2.6,2.72,0.36,0.48/

&SPEC ID='NITROGEN', BACKGROUND=.TRUE./
&SPEC ID='OXYGEN'/
&SPEC ID='WATER VAPOR'/
&SPEC ID='CARBON DIOXIDE'/
&SPEC ID='MYFUEL', 
      FORMULA = 'C2H6O'
      DENSITY_LIQUID=789.3, 
      SPECIFIC_HEAT_LIQUID=2.42, 
      VAPORIZATION_TEMPERATURE=78.0, 
      MELTING_TEMPERATURE=-114.1, 
      ENTHALPY_OF_FORMATION=-234.01,
      HEAT_OF_VAPORIZATION=1.794,
      H_V_REFERENCE_TEMPERATURE=78.0,
      VISCOSITY_LIQUID=0.5945,
      CONDUCTIVITY_LIQUID=0.1800,
      BETA_LIQUID=0.00108/

&REAC ID = 'Fire', 
      FUEL = 'MYFUEL',
      A = 8.6E11,
      E = 177000,
      SPEC_ID_NU = 'MYFUEL', 'OXYGEN','CARBON DIOXIDE','WATER VAPOR',
      NU =-1,-3,2,3,
      SPEC_ID_N_S = 'MYFUEL','OXYGEN',
      N_S = 1, 1,
      HEAT_OF_COMBUSTION=29700/
      
&MATL ID='LIQUID',
      SPECIFIC_HEAT=2.45,
      CONDUCTIVITY=0.17,
      DENSITY=787.0,
      ABSORPTION_COEFFICIENT=1500.0,
      EMISSIVITY=1.0,
      SPEC_ID='MYFUEL',
      HEAT_OF_REACTION=880.0,
      NU_SPEC=1,
      BOILING_TEMPERATURE=78.0/

&MATL ID='STEEL',
      SPECIFIC_HEAT=0.465,
      CONDUCTIVITY=54.0,
      DENSITY=7800.0,
      EMISSIVITY=0.8/

&SURF ID='POOL',
      COLOR='BLUE',
      MATL_ID='LIQUID',
      MATL_MASS_FRACTION=1.0,
      THICKNESS=0.005/

&SURF ID='PAN',
      RGB=200,200,200,
      MATL_ID='STEEL',
      MATL_MASS_FRACTION=1.0,
      THICKNESS=3.0E-3/

&SURF ID='IGNITER',
      COLOR='RED',
      TMP_FRONT=1300.,
      EMISSIVITY=0.0,
      RAMP_T='IGNITER_RAMP_T'/
&RAMP ID='IGNITER_RAMP_T', T=0.0, F=0.0/
&RAMP ID='IGNITER_RAMP_T', T=5.0, F=0.0/
&RAMP ID='IGNITER_RAMP_T', T=5.1, F=1.0/
&RAMP ID='IGNITER_RAMP_T', T=10.0, F=1.0/
&RAMP ID='IGNITER_RAMP_T', T=10.1, F=0.0/

&OBST XB=0.198,0.202,2.598,2.602,0.014,0.015, SURF_ID='IGNITER'/ 

&OBST ID='Obstruction #1', XB=0.1,0.104,2.586,2.614,0.0,0.01, SURF_IDS='POOL','PAN','PAN'/ 
......
&OBST ID='Obstruction #52', XB=0.196,0.2,2.5,2.7,0.0,0.01, SURF_IDS='POOL','PAN','PAN'/ 

&VENT ID='Mesh Vent: Mesh01 [ZMIN]', SURF_ID='OPEN', XB=0.08,0.32,2.48,2.72,0.0,0.0/ 
.......
&VENT ID='Mesh Vent: Mesh03 [XMAX]', SURF_ID='OPEN', XB=0.32,0.32,2.48,2.72,0.24,0.36/ 

&SLCF QUANTITY='TEMPERATURE', ID='X = 0.2 m: Temperature', PBX=0.2/
&SLCF QUANTITY='DENSITY', ID='X = 0.2 m: DENSITY', PBX=0.2/

&TAIL /

**Comment by drjfloyd** [comment]
Converting this to a discussion.  You are doing finite rate chemistry.  You need to have a grid cell contaning sufficent fuel, oxygen, and heat for the reaction to go foward. I suggeset you output fuel, oxygen, and temperature data over your pool and calculate by hand what reaction rate you would expect to see given the values of those quantities present. I suspect you do not have conditions present where this reaction will take off.  3 mm is a large grid cell for DNS finite rate. 

You appear to be using ethanol as the gas species. You could make your life easier and just use the predefined ETHANOL species.

&SPEC ID='ETHANOL'/
