### ISSUE TITLE
Segfault with Activated Sprinkler

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12341]
I have been using the attached case to test VTK outputs. The case has a large fire below an unconfined ceiling with sprinklers. There are a few GEOM objects throughout the domain including one above the fire on which sprinkler droplets will fall. The case segfaults on master a bit after sprinklers activate, but runs to completion if the sprinkler lines are commented out.

[case002.txt](https://github.com/firemodels/fds/files/13863916/case002.txt)

**Comment by marcosvanella** [comment]
Thanks Jon, we'll take a look.

**Comment by johodges** [comment]
That is interesting. I have been using impi_intel_linux. Were you working on OSX?

**Comment by marcosvanella** [comment]
Jon, whenever you have time do a repo update and run the case. Thanks.

**Comment by johodges** [comment]
Thanks Marcos, I can confirm this issue is fixed.

**Comment by marcosvanella** [comment]
Thanks Jon.
