### ISSUE TITLE
Divergence depending on CHID (!?)

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#12375]
Here is a surprise:
I had a model that diverged. To investigate what was causing the trouble, I removed lots of features from it. Eventually, I found that the solution behavior was significantly different if I changed the CHID in the &HEAD line. Please see the two files attached (and strip off the .txt suffix): longer.fds and shorter.fds. These differ only in CHID, but the longer one diverges and the shorter one does not.

These are large cases in terms of cell count and FDS input -- I kept finding that the divergence disappeared when I removed things, even far from the problem. Luckily, the start of divergence can be seen right from the start: if you look at the "max-vmag-stairwell" DEVC, the results start around 0.02m/s (presumably the random initialisation) and either decline (good) or rise rapidly to a few m/s (bad). There is no reason for any flow in the stairwell, which is separated from the fire compartment by a wall. You can see some velocity vectors on the slices in the stairwell ("flight_far" and "flight_near"). In some models, these disturbances cause real trouble - they last indefinitely, and limit the timestep, and even crash the simulation. I have not checked in the current examples. The disturbances always seem to occur on the boundary between the 0.1m-resolution mesh block and one of its 0.2m-resolution neighbors, above or below.

I have to admit I am baffled by this difference. As far as I know the CHID has no effect on (for example) random seeds. In the FDS source code, CHID is declared with length 50, so the current examples are not overstepping. (Also, as far as I am aware, Fortran is fairly robust in string handling -- you can copy a longer string into a shorter string and it just gets truncated.) So, I am not sure that it is relevant that the longer CHID fails and the other one appears (for a short simulation) to succeed. However, I have seen various long names fail and various short names succeed.  I could try a larger sample of names, if it helps, but I would like to know that I'm not going mad before I devote more time to this.

This is running FDS6.8.0 on Ubuntu: revision FDS-6.8.0-0-g886e009-release. I have seen it both on Ubuntu machines and running Ubuntu on Windows Subsystem for Linux 2.

Can anyone explain this behavior? and recommend a way to avoid the spurious velocities? Thanks.

One last-minute thought: the CHID does affect some output filenames. Could there be some OS-based limitation, or glitch, for long output files?

Another last-minute observation: If I reorder some of the lines of the longer.fds input file (moving &MESH and the vmag &DEVC nearer to the start), the divergence goes away, though the CHID is still long. I'm very confused. This is the file rearranged.fds[.txt].

[longer.fds.txt](https://github.com/firemodels/fds/files/13941397/longer.fds.txt)
[shorter.fds.txt](https://github.com/firemodels/fds/files/13941398/shorter.fds.txt)
[rearranged.fds.txt](https://github.com/firemodels/fds/files/13941650/rearranged.fds.txt)

**Comment by mcgratta** [comment]
Well, this sure seems obscure, Ed. I'll take a look.

**Comment by mcgratta** [comment]
I just ran the two cases (longer and shorter) on my linux cluster with the latest source code. The runs both finished, and the .out files are identical except for a slight difference in time and time stamp. 

Jason, can you run both cases on your system when you have a chance. Each run only takes a minute.

**Comment by drjfloyd** [comment]
Our linux system is down. We had a boot issue when adding new blades that the tech wasn't able to work out and are going to need to pull in some support from RedHat to get us back up.   I can try on my PC and see what happens.

**Comment by obscureed** [comment]
When I see the bad behavior from longer.fds, it is noticeable in the .out file -- the run to T_END=3.0 takes 200 time steps instead of 58. I haven't checked the current cases in detail, but I've been seeing the timestep limited by CFL in the stairwell.

**Comment by drjfloyd** [comment]
On my PC the hrr and devc file are identical. The .out is identical other than clock time being slightly different.

**Comment by mcgratta** [comment]
For me, both cases ran in 58 time steps. How many cores does each node on your cluster have? Could this be a memory issue?

**Comment by obscureed** [comment]
I have 32GB on each of the machines I've tried, and the current case doesn't make a big dent in that.  I've tried running it in serial and with MPI -- I chopped out the MPI_PROCESS assignments for simplicity, but I'll attach a partitioned version.

Actually, on WSL2 I'm allowed to run the original longer.fds with "mpiexec -n 25 fds longer.fds" -- and that runs the good way (58 timesteps; declining max-vmag-stairwell). There does seem to be randomness in whether a case runs well or badly. (This is inconvenient, because any fix that doesn't find the cause can't be absolutely trusted.) 

[longer_mpi8.fds.txt](https://github.com/firemodels/fds/files/13942118/longer_mpi8.fds.txt)

**Comment by mcgratta** [comment]
I ran the "longer" case in debug mode (which would hopefully trap errors the release version might ignore), but the results are still the same.

**Comment by obscureed** [comment]
Normally, I make the CHID match the .fds name, but the bad behavior occurs even with a short .fds filename such as longer.fds. It is consistently the long CHIDs that fail. (I set going 10 each of various CHID lengths overnight -- the lengths 20 and 25 finished in a couple of minutes each in serial, but length 30 was still going because each one takes 3446 steps instead of 58.) An obvious possible workaround is to use short CHID names -- I have tried that with a full case, and it diverged again. (That may be unrelated to CHID. I would normally be convinced that CHID is irrelevant, except that I have direct evidence that it is relevant on two different computers.) Right now, in the middle of a large project, I don't see much choice apart from reverting to FDS6.7.9.

**Comment by obscureed** [comment]
Are there any further tests I can do? For example, I could save RESTART files and send them to you? I could compile a debugging version of FDS6.8.0 -- this will have to wait until I get my project back on track -- and what would I be looking for?

**Comment by mcgratta** [comment]
I suggest you download the latest [nightly build](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST) and try that. This is what we are using to test your case.

**Comment by obscureed** [comment]
OK, I've run various cases with FDS6.8.0 nightly build. The results are just as confusing as before, but different:
-- at the first attempt, longer.fds diverged in 2 timesteps, both in serial and in mpiexec -n 8
-- at the first attempt, shorter.fds ran with very small timesteps (which is a symptom of bad behavior, but a different one from longer.fds).
-- Some cases that ran long enough to store DEVC results showed that the vmag monitor was hitting 100m/s.
-- I say "at the first attempt", because I can get different results running the same .fds input file with the same command in a different directory.
