### ISSUE TITLE
The flawed test case resulted in a execution block

### ISSUE THREAD

**Issue by Bravnewor** [firemodels/fds#12372]
I used a test case in the VENT line that contained an error. It incorrectly set the SURF_ID of the boundary to 'PERIODIC'. I initially thought it would throw a program exception like previous test cases I wrote, but instead it caused the execution to block. The same program block occurred when running this test case on another computer.

Both computers were running FDS 6.8.0 version on Windows 11. I have attached a scaled-down version of the input case.
[blockedCase.txt](https://github.com/firemodels/fds/files/13937238/blockedCase.txt)

**Comment by mcgratta** [comment]
You need to declare both sides of the domain as `PERIODIC`:
```
&VENT MB='YMIN', SURF_ID='PERIODIC' /
&VENT MB='YMAX', SURF_ID='PERIODIC' /
&VENT MB='ZMIN', SURF_ID='PERIODIC' /
&VENT MB='ZMAX', SURF_ID='PERIODIC' /
```
I don't think there's any logic in the code to catch this. I'll see what I can do.

**Comment by Bravnewor** [comment]
Thank you for your response. Perhaps we could add a validity check before executing the calculation? Such a freeze can be unfriendly for someone like me who is a beginner, and I didn't know what caused this situation when I was using it.

**Comment by mcgratta** [comment]
I added logic to allow only one boundary of the domain to be declared `PERIODIC`. I cannot think of a reason one would do this, but at least it will not fail.

**Comment by Bravnewor** [comment]
Thx again for your patient response, it was helpful
