### ISSUE TITLE
All components of ORIENTATION are zero

### ISSUE THREAD

**Issue by kihila** [firemodels/fds#12382]
can u please can fix this error?

![image](https://github.com/firemodels/fds/assets/127167622/fa4b2910-f393-443b-898e-3bea8c499ff5)

**Comment by rmcdermo** [comment]
Please look at the FDS user guide for the specific output quantity and make sure you have assigned a viable ORIENTATION.  Also, it is helpful if you upload your input file (with extension .txt).

**Comment by kihila** [comment]
i already read the user guide about smoke detector, in this chapter they say **orientation not use**, but my fds model want to setting the orientation. i dont know what my error simulation mean

![image](https://github.com/firemodels/fds/assets/127167622/1c8ac033-115b-4e7b-9611-fcf1450bfafb)

**Comment by drjfloyd** [comment]
We need an input file so we can see what your inputs are.

**Comment by kihila** [comment]
thats the properties
![image](https://github.com/firemodels/fds/assets/127167622/49cf89f4-1cd3-473a-a4ed-446cef0eb801)

and this the file. nb: please ignore mesh boundaries, because i'm still fiddling it
https://drive.google.com/drive/folders/1Egrp3iSOj0sKiI-5n-cB_mZPo6kRgPum?usp=sharing

**Comment by drjfloyd** [comment]
This appears to be a Pyrosim issue an not an FDS issue. A workaround would be to set any of the x,y,z to a non-zero value.

**Comment by kihila** [comment]
okaaay...  i will try it first, thanks f u time
