### ISSUE TITLE
ERROR: Problem with SURF

### ISSUE THREAD

**Issue by AsinShaoQing** [firemodels/fds#12387]
I found an example of FDS in the _Simulation of the Dynamics of a Wind Driven Fire in a Ranch Style House Texas_ paper at NIST, and I want to try running it on my computer. However, after I tried to run it, FDS reported an error:
`ERROR: Problem with SURF number 12, line number 224 (CHID: WF16slow)`
I found that this error points to this SURF：
```
&SURF ID='Wood Joists02',
 RGB=168,96,0,
 HRRPUA=181.39,
 RAMP_Q='Wood Joists02_RAMP_Q',
 IGNITION_TEMPERATURE=384.00,
 BACKING='EXPOSED',
 MATL_ID(1,1)='DougFir',
 MATL_MASS_FRACTION(1,1)=1.00,
 THICKNESS(1)=0.0380/
```
But I haven't figured out which attribute is missing or what the problem is. Please help!
![image](https://github.com/firemodels/fds/assets/127843780/b3493a7b-ba81-499b-9131-8c5ec07ed35b)

**Comment by rmcdermo** [comment]
The fact that MATL_MASS_FRACTION is not correctly syntax highlighted is a clue that you have something wrong with this parameter.  Please make sure you are using the latest code and check the namelist syntax for the SURF line for that version of the code.  There is a good list at the back of the user guide that will show you what is correct.

**Comment by AsinShaoQing** [comment]
> The fact that MATL_MASS_FRACTION is not correctly syntax highlighted is a clue that you have something wrong with this parameter. Please make sure you are using the latest code and check the namelist syntax for the SURF line for that version of the code. There is a good list at the back of the user guide that will show you what is correct.

I looked into the user guide and it gives an example like this:
**For example, if the mass fraction of the second material of the third layer is 0.5, then write**
`MATL_MASS_FRACTION(3,2)=0.5`
I think it's probably not where the question is. However, I tried FDS 5.0 and it worked. Perhaps it's just that the version of this code is outdated. Thx!
