### ISSUE TITLE
move fed computation from smokeview to fds

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#12398]
for various reasons, mainly because of memory requirements, an fed computation was put into smokeview rather than fds a long time ago. I think it makes more sense now for the computation to be done in fds. I'm trying to speed up smokeview and simplify some coding.  taking out fed from smokeview would help a lot.  if fed is performed in fds then the resulting slices could be passed to smokeview and smokeview could view them as before.

**Comment by gforney** [comment]
ok, I'll it out of smokeview

**Comment by agearing** [comment]
This is really useful for Fire Engineering consulting in NZ! Please keep this feature for smokeview.

**Comment by gforney** [comment]
I moved these computations from smokeview to a program named fds2fed .
fds2fed casename
Will generate files smokevies uses to show fed slices

Glenn Forney

**Comment by agearing** [comment]
> I moved these computations from smokeview to a program named fds2fed .
> fds2fed casename
> Will generate files smokevies uses to show fed slices
> 
> Glenn Forney
> […](#)

Hi Glenn, thank you, where can I download this?

**Comment by gforney** [comment]
It is installed along with fds and smokeview .

Glenn Forney
