### ISSUE TITLE
Error on simulation start with FDS-SAFIR coupling

### ISSUE THREAD

**Issue by a-respighi** [firemodels/fds#12400]
Hi there, 
when launching a simulation with code to export radf files for SAFIR I get this error:

forrtl: severe (47): write to READONLY file, unit 48, file d:\41235\41235-R2-04\fort.48
Image              PC                Routine            Line        Source            
fds.exe            00007FF6151D55A7  Unknown               Unknown  Unknown
fds.exe            00007FF615192897  Unknown               Unknown  Unknown
fds.exe            00007FF61BFF5AAE  Unknown               Unknown  Unknown
fds.exe            00007FF61BFD81D9  Unknown               Unknown  Unknown
fds.exe            00007FF61BD27864  Unknown               Unknown  Unknown
fds.exe            00007FF61BCF19FE  Unknown               Unknown  Unknown
fds.exe            00007FF61C673370  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF954DE7344  Unknown               Unknown  Unknown
ntdll.dll          00007FF9550026B1  Unknown               Unknown  Unknown

If I remove the lines

&RADF XB=49.2, 50.6, 6.0, 14.0, 0.0, 7.0, I_STEP=1, J_STEP=1, K_STEP=1/
&DUMP DT_RADF=20/

the simulation starts.

I tried removing the entire directory and even rebooting the pc but nothing changed.
Any ideas?

The fds file is a bit long, so for the moment I didn't attach it, please let me know if you need it.

Also, in other small tests that can be started, when radf files are created they are missing the information for time=0, which I found in fort.xx files (I discovered this by looking into the above mentioned fort.48 file).

Thank you

**Comment by mcgratta** [comment]
I fixed a problem related to SAFIR files within the past 6 months. What version of FDS are you using? You may need to use the nightly build.

**Comment by a-respighi** [comment]
Hi Kevin, thank you for your quick reply.
I'm using v6.8.0, I'll try with the nightly build.

**Comment by a-respighi** [comment]
I downloaded the nightly build I could find here [https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST)
This is the content of the FDS_INFO.txt file:
FDS_HASH     21dd4292d
FDS_REVISION FDS-6.8.0-1297
SMV_HASH     ca744e1f4
SMV_REVISION SMV-6.8.0-1931

The content of te .out file confirms that it's using this version:
 Current Date     : January 29, 2024  17:26:55
 Revision         : FDS-6.8.0-1297-g21dd429-nightly
 Revision Date    : Wed Jan 24 15:39:42 2024 -0500
 Compiler         : Intel ifort 2021.9.0
 Compilation Date : Mon 01/29/2024  08:37 AM

I executed a simple test case containing these two lines
RADF XB=0.8, 4.4, 0.8, 4.4, 0, 3.4, I_STEP=1, J_STEP=1, K_STEP=1/
DUMP DT_RADF=20/
but no radf files have been written.
Maybe I downloaded the wrong version? If this is the case, how can I get other versions?
Thank you

**Comment by mcgratta** [comment]
Post your input file.

**Comment by a-respighi** [comment]
My mistake, I just noticed I had removed the "&" at the beginning of the two lines for a test but forgot to put them back on.
Doing so, it works.
Thank you for your help.
