### ISSUE TITLE
Pressure zones in the solids

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#12453]
While I was reading the source code about pressure zone assignment, I noticed even the solids are assigned to a pressure zone. 
Then I looked at a recent simulation that I had a pressure problem and noticed indeed the solids contain pressure zone information. However some are uniform with the zone they are within, some are not (they are assigned to 0= outside). 

See below two examples:
The first one shows a wall, the second one stair slab. 

Do you see any issue here? Thanks.

FDS file:
[a.txt](https://github.com/firemodels/fds/files/14219842/a.txt)

Run with FDS 6.8.0 on Linux

- Here the zone is not consistent in the obstruction. Some parts of the obstruction have a zone of the left hand side, some outside (zero).

1. obstructions hidden
![image](https://github.com/firemodels/fds/assets/26166281/6a0aa44c-4870-47d6-9179-002925624c60)
2.Obstructions visible
![image](https://github.com/firemodels/fds/assets/26166281/c9b67df1-1b28-40a8-b78a-120c463c5243)

- Here the zone is consistent and all the same as the zone the obstruction is within. 

1. obstructions hidden
![image](https://github.com/firemodels/fds/assets/26166281/c8fb129e-b81d-484e-8e81-bb39e04270a0)
2.Obstructions visible
![image](https://github.com/firemodels/fds/assets/26166281/2da78641-2ad1-401d-85a5-7115210d1ae8)

**Comment by mcgratta** [comment]
The reason for assigning pressure zones to the interior of obstructions is to account for the possibility of OBST removal or creation. When a wall that separates two pressure zones is removed, FDS merges these two pressure zones into one. It does this when it finds two cells with different zone assignments and no wall in between. 

Have you had a problem with pressure zones lately?

**Comment by Er9y714** [comment]
I understand. Thank you for the explanation. Then I assume the first case is also normal; half of the obstruction is yellow, the other half is green ( I ignore the blue part (zero=outside)).

I have had some numerical errors due to large pressures in recent projects but I do not report becuase

-  the problems are sporadic 
- remeshing fixes them 
- I can't simplify the cases or
- I do not follow all the good practices (HVAC vent on disappearing OBST)

If the zone assignment on the obstruction in the first case is normal and is how it should be, then I do not have any other question at the moment. I will close the issue. Thank you for your time.
