### ISSUE TITLE
Inconsistent behaviour between FDS6.7.1 and FDS6.8.0

### ISSUE THREAD

**Issue by HarryPommier** [firemodels/fds#12454]
**Describe the bug**
The VENT should disappear when the MEAN_DIOXYGEN level crosses the SETPOINT (decreasing curve). The behaviour seems correct in FDS6.8.0 but not in FDS6.7.1.

**To Reproduce**
The fire source is defined like this :
```
&SURF ID='FIRE', HRRPUA=2025, SPREAD_RATE=0.006246020274735251, XYZ=0.95, 1.85, 0.15, RAMP_Q='FIRE_RAMP' / 
&OBST XB=0.10, 1.80, 1.00, 2.70, 0.00, 0.13, COLOR='BLUE' /
&VENT XB=0.10, 1.80, 1.00, 2.70, 0.13, 0.13, SURF_ID='FIRE', COLOR='RED', DEVC_ID='MEAN_DIOXYGEN' /

&RAMP ID='FIRE_RAMP', T=0.11, F=0, DEVC_ID='MEAN_DIOXYGEN' /
&RAMP ID='FIRE_RAMP', T=0.21, F=1.0 /

&DEVC ID='MEAN_DIOXYGEN', XB=-0.20, 2.10, 0.70, 3.00, -0.17, 0.43, QUANTITY='VOLUME FRACTION', SPEC_ID='OXYGEN', STATISTICS='MEAN', SETPOINT=0.13, INITIAL_STATE=.TRUE., TRIP_DIRECTION=-1, LATCH=.TRUE. /
```

**Expected behavior**
Same results between FDS6.7.1 and FDS 6.8.0

**Screenshots**
Correct behaviour (FDS6.8.0)
![image](https://github.com/firemodels/fds/assets/50177956/280b8dc2-246b-482f-983e-e72891014e50)

Incorrect behaviour (FDS6.7.1)
![image](https://github.com/firemodels/fds/assets/50177956/afd1130e-772a-4fcd-9a21-5d08f5144be5)

**Comment by drjfloyd** [comment]
If the behavior is correct in FDS 6.8, then there is nothing for us to fix.
