### ISSUE TITLE
Crash when OBST is removed with layered surfaces

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12450]
Ran into an issue working on a validation case from one of our railcar experiments with prescribed window failure times. The attached model has an OBST which is removed at t=1s which fails in the ompi release target but not in impi. The case fails in both debug targets:

1. impi_intel_linux - no crash
2. impi_intel_linux_db - crashes at t=1.02 s with an index out of bounds error in wall.f90:1955
3. ompi_gnu_linux - crashes at t=1.09 s with a seg fault
4. ompi_gnu_linux_db - crashes at t=1.02 s with an index out of bounds error in wall.f90:1955

[simple2.txt](https://github.com/firemodels/fds/files/14203172/simple2.txt)

**Comment by mcgratta** [comment]
This should be fixed. Try it to make sure, then close.

**Comment by johodges** [comment]
I can confirm the fix works on my test case.
