### ISSUE TITLE
Corner wall fire cases take ~8-10 longer to run recently on Blaze

### ISSUE THREAD

**Issue by leventon** [firemodels/fds#12457]
It takes significantly longer (>10x ) to run coupled flame spread simulations (room corner test) than ~1 year ago. I explored what I thought might be causing the issues (differences between cases) but similarly long run times arise with different material property sets (~4x larger fires / fire growth rate) and with different versions of FDS (6.7.9 and 6.8.0). Step size is about the same between cases with/without long run times. Maybe Blaze is just tired of running these cases over and over again for me.
Most of the time is spent on COMM / Main (images below, for the FDS 6.7.9 case - much higher COMM costs - total simulation time was also even longer still)

Run case: [CW_PMMA_Average_value-FDSinput.txt](https://github.com/firemodels/fds/files/14226061/CW_PMMA_Average_value-FDSinput.txt)

**Screenshots**
SLOWER CASES ~(100-300 hours)
![image](https://github.com/firemodels/fds/assets/12798233/f0059b97-3ad5-46ca-b1fe-8342e6e9cad1)
![image](https://github.com/firemodels/fds/assets/12798233/2cedeef3-8163-4488-ba1a-427f01be9e38)

EXAMPLE ORIGIGINAL CASE (~10 hours)
![image](https://github.com/firemodels/fds/assets/12798233/8fbd6fb5-8203-49d6-ba60-b70ebe06f20b)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 10.0.19045
Not sure you actually want my desktop info, running these cases on Blaze

Reference case from April 2023, ~14 hours
 Revision         : FDS6.7.9-1552-g69f80caea-master
 Compiler         : ifort version 2021.7.1

June 2024, 300 hours
 Revision         : FDS6.7.9-1552-g69f80caea-master
 Compiler         : ifort version 2021.7.1

Feb. 2024 ~100 hours
 Revision         : FDS-6.8.0-1297-g21dd429-master
 Compiler         : ifort version 2021.7.1

**Comment by rmcdermo** [comment]
Could just be the particular queue you are using on blaze.  Try batch4 and report back.

**Comment by mcgratta** [comment]
I'll run the cases on burn for 60 s instead of 600 s and compare timings. We can try batch4 later if burn does not identify a problem.

**Comment by leventon** [comment]
@rmcdermo trying now, thanks

**Comment by mcgratta** [comment]
![image](https://github.com/firemodels/fds/assets/11333911/4e20cf9a-c9a1-49c1-8b5f-46d0af3dfc70)

I ran the case for 60 s on burn. The latest code took 30375 time steps for a total of 2240 s; the code from last February took 29687 time steps and 2133 s. I used the exact same input file and compiler version.

**Comment by mcgratta** [comment]
BTW, I am comparing the timings of MPI process 0, the root process. The total time is the wall clock time.

**Comment by leventon** [comment]
10 hours on batch4 of blaze

**Comment by rmcdermo** [comment]
OK, back to reasonable and we can close?

**Comment by leventon** [comment]
yes, thanks

**Comment by ericvmueller** [comment]
To clarify, as I've seen similar slowdowns of older cases - the solution is just run on batch4 from now on? 
Was your April 2023 case on batch4, @leventon?
