### ISSUE TITLE
ASSUMED GAS TEMPERATURE

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#12464]
ASSUMED GAS TEMPERATURE used to be a gas phase output back when AGT was specified on MISC.  Now AGT is on SURF. In data.f90 the output is still there as a gas phase quantity but in dump there is no CASE for it; however, it is still in the User's Guide.  This should now be a solid phase output since it is attached to SURF. We have GAS TEMPERATURE which seems like it should give the assumed but in dump we have GAS TEMPERATURE = TMP(I,J,K). We store TMP_G in B1%TMP_G.  Should we just be using this in dump?

should we just change:

   CASE( 4) ! GAS TEMPERATURE
      SOLID_PHASE_OUTPUT = TMP(BC%IIG,BC%JJG,BC%KKG) - TMPM

to

   CASE( 4) ! GAS TEMPERATURE
      SOLID_PHASE_OUTPUT = B1%TMP_G - TMPM

and remove ASSUMED GAS TEMPERATURE from the guide?

**Comment by mcgratta** [comment]
Yup, check that I removed everything then close

**Comment by drjfloyd** [comment]
That got rid of the old code.  One new problem.

In THERMAL_BC we set B1%TMP_G = TMP. Then we go into the solid heat transfer if needed and there we set B1%TMP_G to AGT if specified. Then later we set B1%TMP_G = TMP in SPECIES_BC.  I don't think we need to do it again there.   We also set RHOG and ZZG in both THERMAL_BC and in SPECIES_BC and I think we only need the first.

**Comment by mcgratta** [comment]
I removed the redundant assignments form SPECIES_BC, HVAC, SOLID_1D. Could you double check.

**Comment by drjfloyd** [comment]
You still have it in THIN_WALL. Is that a special case?

**Comment by mcgratta** [comment]
I'll double check, but yes, I think it is special.

**Comment by mcgratta** [comment]
Yes -- a thin wall is the edge of a thin plate and only relevant in 3D heat transfer. In THERMAL_BC we don't cycle through those cells.

**Comment by drjfloyd** [comment]
We only solve 1DHT every other timestep by default. So every other timestep B1%TMP_G in THERMAL_BC gets reset to TMP() so  DEVC gets the wrong average value over the output internval. I'm going to move the ramp evaluation into THERMAL_BC and into the special case for a thin wall

**Comment by mcgratta** [comment]
What's the ramp evaluation?

**Comment by drjfloyd** [comment]
The assumed gas temperature ramp

**Comment by mcgratta** [comment]
Ah, yes, good idea.

**Comment by drjfloyd** [comment]
Moved the ramp.  The case I was working with seems to be OK now.
