### ISSUE TITLE
FDS 6.7.7 simulation stuck on 'Reading FDS input file ...'

### ISSUE THREAD

**Issue by r-broek** [firemodels/fds#12488]
**Describe the bug**
An FDS 6.7.7 simulation containing 27 meshes becomes stuck at 'Reading FDS input file ...'. The simulation is scheduled to the Linux cluster using PBS and is allocated 27 MPI processes. Previous simulations with fewer meshes set up with similar input files and PBS scripts run without issues. 

I have read previous threads that discuss this issue, which both suggest that I'm allocating more processes than the number of meshes. These responses seem to be for an older FDS version, as version 6.7.7 will throw an error saying the number of processes does not match the number of meshes for both a higher or lower number. I've tested this by allocating 26 or 28 processes instead of 27. Furthermore, I have tested spreading these processes over multiple nodes to make sure I am not overloading a node with too many processes. None of this resolved the issue.

https://groups.google.com/g/fds-smv/c/8WiQLpVBUHg/m/TL9pbjJICAAJ
https://groups.google.com/g/fds-smv/c/_Ld4AzUdRHc/m/4sN9xZbhBQAJ 

Additionally, I have tried running the simulation with 'CHECK_MESH_ALIGNMENT=T' and  &TIME T_END = 0/. This produced the .smv file as expected.

**To Reproduce**
1. Run the attached FDS input file and vegetation model by allocating 27 MPI processes via a PBS script.
Input files:
[2m_M14.fds.txt](https://github.com/firemodels/fds/files/14298782/2m_M14.fds.txt)
[2m_M14_veg.txt](https://github.com/firemodels/fds/files/14298783/2m_M14_veg.txt)

**Expected behavior**
I would have expected the log file to look similar to:
![image](https://github.com/firemodels/fds/assets/137812007/5178228d-eaa6-495c-b578-cb7252b42186)

**Screenshots**
The log file of the simulation that becomes stuck:
![image](https://github.com/firemodels/fds/assets/137812007/6332c360-e886-4662-9edd-51fcb7018f81)
The set-up of the meshes:
![image](https://github.com/firemodels/fds/assets/137812007/fba518fe-227d-4945-b028-2f56f5fe135d)

Any help is much appreciated.

**Comment by mcgratta** [comment]
Two problems. First, the CHAR model you are using is outdated and no longer used in the current version of FDS. Second, your meshes overlap in a very complex way. It will take me a long time to fix, and even then it will be for the latest version. I suggest you set up your meshes so that they do not overlap.
