### ISSUE TITLE
Numerical instability in water spray cooling case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12481]
I added a new validation case called `Validation/LEMTA_Spray/FDS_Input_Files/LEMTA_Spray_Cooling_SU42_Horizontal.fds`. It consists of a radiant panel below a steel plate that is cooled by a water spray at about 385 s after the heating starts. This case had a numerical instability at the surface of the radiant panel due to droplets hitting it. The panel is turned off when the spray starts. To make the case run, I just removed the panel completely when the spray starts, but I'd like to figure out what is wrong.

The case runs fast (15 or 20 min) to the point of instability. To make that happen, remove the `timer` that removes the radiant panel.

**Comment by drjfloyd** [comment]
If the panel has a specified flux, we should be disabling evaporation as there is no cooling that can be done to a fixed flux.

**Comment by drjfloyd** [comment]
Are the drops penetrating the solid steel sheet or just wicking along the bottom?  Doesn't seem very physical that they would travel so far along the bottom before dripping off.  At the edge because of surface tension but not 50 cm

![LEMTA_Spray_Cooling_SU42_Horizontal_0081](https://github.com/firemodels/fds/assets/12799217/4b60abcf-1be8-40d0-ba02-3ba23e8f3a09)

The no water cooling logic is working. The issue is in wall. The temperature search isn't converging and at 20 iterations it is exiting with a bad wall temperature and once that happens things start going off the rails.  Should we just implement the quartic solution here to get an exact solution then iterate since HTC will change?

IF (ABS(QEXTRA) < 1.E-10_EB .OR. ADCOUNT > 20) THEN
Do we need this stringent of a check?  This is 0.1 nanoWatt accuracy.  Would mW or uW be better?

**Comment by rmcdermo** [comment]
Well, the tolerance may be too tight.  But if the temperature is not converging (residual decreasing on each iteration) then the tolerance may not matter.  For the sake of debugging, I would turn on CHECK_HT for a case like this.  If the heat flux is not resolved in time, I don't know how we expect to get a physical solution.  If that ends up being the problem, then we need to think about ways to overcome the stability (some level of implicit solution).

**Comment by drjfloyd** [comment]
There is a sudden large drop in the adjacent gas cell temperature. The gas is hot since the radiant panel is 1200 K and the drop evaporates quickly. Newton's method isn't converging fast enough.

I can try Ferrari's method for the quartic to get an analytic solution for temperature.

**Comment by mcgratta** [comment]
Yes, I forgot about the logic in part.f90 that distinguishes a fixed flux surface.

Also, the "wicking" is a bit unreal here. The logic says that when a droplet flies off a horizontal surface, it is given a new velocity that is just the old velocity in the other direction. The droplet velocity in this case is 2 m/s on the surface, a guess made by the student who originally did this calc. 

The radiant panel was turned off before the water spray in the actual experiment.

**Comment by drjfloyd** [comment]
Pushed up a fix. Did two things. 
-Did an exact solution for TMP_F with a slightly relaxed iteration on the HTC.
-Realized that how we corrected Q_RAD_IN for droplets on a surface wasn't quite correct. Fixed that. This was the trigger for the  iteration failing but still think doing the exact solution for TMP_F is good to stave off any future issue if the iteration as it was had convergence problems.

I had discarded my changes to the case before pushing up (I had left the plate on the entire time) and realize I should commit it with changes the leave the plate present but off after the spray. I'll do that.

**Comment by mcgratta** [comment]
[LEMTA_Spray_Cooling_PSD3_Horizontal.fds.txt](https://github.com/firemodels/fds/files/14314753/LEMTA_Spray_Cooling_PSD3_Horizontal.fds.txt)
This case seg faults at 461 s due to a temperature going out of bounds in a call to `GET VISCOSITY`. I'm going to run it in debug mode to get more info.

**Comment by drjfloyd** [comment]
It is something in the new wall stuff.

**Comment by drjfloyd** [comment]
I think I know what the issue is. Testing a fix.

**Comment by drjfloyd** [comment]
got past 461 s. I'll let it run and look at results to see if things look OK and then push up the fix.

**Comment by drjfloyd** [comment]
seems to be fixed

**Comment by mcgratta** [comment]
Works! Thanks.
