### ISSUE TITLE
Inconsistent mass for SCREEN_DRAG and POROUS_DRAG

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#12486]
**Describe the bug**
As I was going through particle initialization routines, I've noticed an issue with `SCREEN_DRAG` and `POROUS_DRAG` (which I'm pretty sure predates my recent changes). 

Basically, `LPC%LENGTH` can change on a particle-by-particle basis when we initialize it, when really it needs to be a value appropriate for all particles in the class. For example, `LP%DX*LP%DY*LP%DZ` below can be variable so the class-wide property of LENGTH is changing:

https://github.com/firemodels/fds/blob/515d6e5c2ee0a87b719777f355da82ac33ce086e/Source/part.f90#L1601-L1609

Then later when we compute mass and area we only have the value of `LPC%LENGTH` relevant to the most recent `LP` initialized:

https://github.com/firemodels/fds/blob/515d6e5c2ee0a87b719777f355da82ac33ce086e/Source/wall.f90#L1020-L1029 

This is particularly evident in cases with different mesh resolutions because resolution affects `LPC%LENGTH` but LPC variables are shared across meshes.

**To Reproduce**
add `PARTICLE MASS` as an output quantity to the `porous_media.fds` verification case. You will see the particles are set up properly but when stepping begins the mass changes based on the `LPC%LENGTH` value that was last set for the last particle initialized (in the high-resolution mesh).

I can also reproduce this with the last official release because my changes yesterday copied the previous logic when it comes to `LPC%LENGTH`. I think we aren't catching it because mass doesn't affect the drag calculation when using these drag laws. 

**Screenshots**
![image](https://github.com/firemodels/fds/assets/13366803/f66770fc-e28b-4513-b9f9-5e2025206f97)
![image](https://github.com/firemodels/fds/assets/13366803/e76537eb-447f-4e6a-a7bb-2feeaad704cc)

**Fix?**
We could do something like make `LPC%LENGTH` a non-dimensional length that only depends on `FREE_AREA_FRACTION` or `POROUS_VOLUME_FRACTION` and then scale it for each particle with `LP%PWT`... but that might muddy the typical interpretation of `LP%PWT`.

**Comment by drjfloyd** [comment]
Could just make it a particle value.

**Comment by ericvmueller** [comment]
Fair point, I was just wondering if we could avoid another particle-level variable. But that maybe introduces more headaches than its worth.

**Comment by mcgratta** [comment]
If you create `LP%LENGTH`, see if you no longer need `LPC%LENGTH` and make changes to func.f90 and type.f90 appropriately.

**Comment by ericvmueller** [comment]
Yup, I think that should be doable. I can take a crack at it

**Comment by ericvmueller** [comment]
addressed with PR #12489 and PR #12490

The mass does not change now.
![image](https://github.com/firemodels/fds/assets/13366803/3b999e80-f59f-4112-a06c-14197608a8fc)
