### ISSUE TITLE
Divergence depending on mpi? or random?

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#12498]
I have a large case that diverges quickly (in the first 10 timesteps) in FDS6.8.0.

I've reduced the complexity repeatedly -- a lengthy process, because the divergence behavior sometimes changed when removing irrelevant-looking input lines, such as &SLCF. I've come to accept that this divergence is somewhat random.

I'll attach 3 cases -- strip off the .txt suffix to reach .fds files. They are all fairly large in mesh count, but the bad behavior shows up very quickly when it does. I run each one either with MPI or without:
```mpiexec -n 8 fds caseX.fds |& tee caseX.log```
```             fds caseX.fds |& tee caseX_noMPI.log```

On one machine (running Ubuntu 22.04.3) I get the following results:

```
___Case 1, with MPI: slow.
Case 1, without MPI: slow.
___Case 2, with MPI: fast.
Case 2, without MPI: fast.
___Case 3, with MPI: diverges.
Case 3, without MPI: fast.
```

"Slow" means >1000 timesteps to reach 1.0s.
"Fast" means <20 timesteps to reach 1.0s.
"Diverges" means "```ERROR: Numerical Instability - FDS stopped```" on second timestep.

Case 3 came before the others, so I thought this was an MPI issue. (I could even fix case3 by moving the second mesh with ```MPI_PROCESS=5``` to  ```MPI_PROCESS=6```.) Case 2 differs from Case 1 in a single &OBST line, so I now think it's unpredictable.

Also, on a different machine (running Ubuntu 22.04.3 on Windows Subsystem for Linux 2 on Windows 11 Pro):
```
___Case 3, with MPI: fast.
```
This is exactly the same version of FDS (FDS-6.8.0-0-g886e009-release, ifort version 2021.7.1, compiled Apr 18, 2023 15:20:17), even the same md5sum (5cc56a470efb13219f44c4ab1f6d8a95  /home/ubuntu/FDS680/bin/fds). So now I'm confused again.

So:
• Please could you see if you can reproduce non-fast solving of any of these cases, with or without MPI?
• How do I troubleshoot this divergence or tiny timestep?
• If I see very small timesteps at the start of a run, but eventually it settles down, can I trust the results? (This has happened on related cases.)

Thanks,
Ed

**Comment by obscureed** [comment]
case1
[case1.fds.txt](https://github.com/firemodels/fds/files/14315714/case1.fds.txt)

case2
[case2.fds.txt](https://github.com/firemodels/fds/files/14315718/case2.fds.txt)

case3
[case3.fds.txt](https://github.com/firemodels/fds/files/14315720/case3.fds.txt)

**Comment by mcgratta** [comment]
I just ran case3
```
 Fire Dynamics Simulator

 Current Date     : February 16, 2024  16:05:52
 Revision         : FDS-6.8.0-1455-g0f98cf9-master
 Revision Date    : Mon Feb 12 13:45:21 2024 -0500
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
 Compilation Date : Feb 12, 2024 14:54:23

 Number of MPI Processes:  8

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS


 Job TITLE        : case3
 Job ID string    : case3

 Time Step:      1, Simulation Time:      0.03 s
 Time Step:      2, Simulation Time:      0.05 s
 Time Step:      3, Simulation Time:      0.09 s
 Time Step:      4, Simulation Time:      0.12 s
 Time Step:      5, Simulation Time:      0.16 s
 Time Step:      6, Simulation Time:      0.20 s
 Time Step:      7, Simulation Time:      0.25 s
 Time Step:      8, Simulation Time:      0.30 s
 Time Step:      9, Simulation Time:      0.35 s
 Time Step:     10, Simulation Time:      0.41 s
 Time Step:     17, Simulation Time:      1.00 s

STOP: FDS completed successfully (CHID: case3)
```

**Comment by obscureed** [comment]
Thanks for trying that. That's the "quick" solution.

It's frustrating that the issue doesn't reproduce on your system -- I know that you can't troubleshoot what you can't see, but it's still a problem for me. Please could you try case1 as well, maybe through ```mpiexec -n 8```? -- this showed "slow" solution on two different machines for me.

**Comment by mcgratta** [comment]
```
 Fire Dynamics Simulator

 Current Date     : February 19, 2024  13:26:27
 Revision         : FDS-6.8.0-1522-gf593119-master
 Revision Date    : Fri Feb 16 17:25:33 2024 -0500
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
 Compilation Date : Feb 16, 2024 17:29:22

 Number of MPI Processes:  8

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.7 for Linux* OS


 Job TITLE        : case1
 Job ID string    : case1

 Time Step:      1, Simulation Time:      0.03 s
 Time Step:      2, Simulation Time:      0.05 s
 Time Step:      3, Simulation Time:      0.09 s
 Time Step:      4, Simulation Time:      0.12 s
 Time Step:      5, Simulation Time:      0.16 s
 Time Step:      6, Simulation Time:      0.20 s
 Time Step:      7, Simulation Time:      0.25 s
 Time Step:      8, Simulation Time:      0.30 s
 Time Step:      9, Simulation Time:      0.35 s
 Time Step:     10, Simulation Time:      0.41 s
 Time Step:     17, Simulation Time:      1.00 s

STOP: FDS completed successfully (CHID: case1)
```

**Comment by obscureed** [comment]
Thanks again, but still frustrating.

One last try: please could you try case1 without mpiexec?

The reason I ask is that I've gone back to a slightly older setup and now I get better results:
```
___Case 1, with MPI: fast.
Case 1, without MPI: slow.
___Case 2, with MPI: fast.
Case 2, without MPI: fast.
___Case 3, with MPI: fast.
Case 3, without MPI: fast.
```
The "slow" behavior in case1 (only without mpiexec) sees the first timestep at a healthy 0.03s, then very small timesteps.
(If it's still at t=0.03s after 9 timesteps, you might as well CTRL-C -- that's the "slow".) The odd thing is that this older setup has exactly the same fds and mpiexec executables as the newer setup where case3 diverged -- here are the md5sum results:
```
5cc56a470efb13219f44c4ab1f6d8a95  /home/ubuntu/FDS680/bin/fds
d045197b0558fedd6adbd0086d4da71c  /home/ubuntu/FDS680/bin/INTEL/bin/mpiexec
```
The newer setup derives from the older setup, upgrading from Ubuntu 22.04.2 LTS to Ubuntu 22.04.3 LTS. I'm sure to have changed various settings, but nothing very fundamental.

Currently, I regard the older setup as "lucky" and the newer setup as "unlucky", though with random behavior this could be an illusion. I'm going to revert to the older setup on some full-scale runs and see how that goes. I'm happy to troubleshoot the "unlucky" setup, if it's of any interest, but I don't know where to start. What is involved in an fds simulation other than the fds and mpiexec executables?

**Comment by johodges** [comment]
This sounds a lot like the bug that Marcos and I were tracking down and fixed in https://github.com/firemodels/fds/issues/12473.
Try building from the latest source or installing the nightly build on your machine and re-running your cases. You can get the latest nightly build here:

https://github.com/firemodels/test_bundles/releases

**Comment by johodges** [comment]
Sorry for the double post. The issue I referenced was related the intel compiler rather than the initialization. This is the issue I was thinking of where we were troubleshooting initialization and fixed a bug https://github.com/firemodels/fds/issues/12437. Regardless, try with the latest version of the code and lets see if the issue persists.

**Comment by obscureed** [comment]
Thanks, that's interesting, @johodges. I've tried the latest build (6.9.0 -- I couldn't see a 6.8.x build), and it gets a clean bill of health in all the above cases (case1-case3; with & without mpiexec; lucky and unlucky Ubuntu).

The 6.9.0 test build also shows good behavior with an intermittent divergence I reported earlier (https://github.com/firemodels/fds/issues/12375).  In that case, the problem seemed to be present from the start, but it also lasted throughout some runs. Would that be consistent with the bug you fixed, or would the bug only apply to initial transients? (I suppose initialization could include something like momentum sources that would cause long-lasting disturbances if they were not updated.)

I'll close this issue, but I am still intrigued to know how identical executables can have different convergence -- how do runtime libraries etc get involved?

**Comment by johodges** [comment]
I have not looked too much at the initialization, so others may be able to better answer. When a variable is not initialized correctly, FDS will pull numbers from the allocated location in memory which can cause stability issues. Different compilers handle uninitialized variables differently so you can get different behavior. While the compilers all have some checks for variable initialization errors, they are not perfect and these errors often have to be tracked down manually. One of my goals for this year is to take the large commercial cases that we run as a company that crash and try to identify why it is the case to help root out these bugs.

In terms of different results for the same build on different machines, my understanding is the random noise introduced in the flow field initially by FDS is not necessarily the exact same random noise when you move to different machines. This will depend on what is being used as the random seed.
