### ISSUE TITLE
DSC output for tga_analysis case is broken

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12525]
The DSC plot for `tga_analysis` in the User's Guide is out of range.

```
[mcgratta@burn fds]$ git bisect bad
f28cbaa86a1bb179efc2823490d14b69b0605934 is the first bad commit
commit f28cbaa86a1bb179efc2823490d14b69b0605934
Author: Jason Floyd <drjfloyd@users.noreply.github.com>
Date:   Mon Feb 12 15:42:49 2024 -0500

    FDS Source: Move assumed gas temp ramp, edit NIST 25 cone case

 Source/ccib.f90                                    |   16 +-
 Source/wall.f90                                    |   40 +-
 .../FDS_Input_Files/NIST_Cone_Test_25kW.fds        | 1324 +++++++++++++++++++-
 .../FDS_Input_Files/pmma_properties.txt            |    2 +-
 Validation/NIST_Polymers/Run_All.sh                |    2 +-
 .../Sprinklers_and_Sprays/water_evaporation_6a.fds |   51 -
 6 files changed, 1318 insertions(+), 117 deletions(-)
 delete mode 100644 Verification/Sprinklers_and_Sprays/water_evaporation_6a.fds
```

**Comment by drjfloyd** [comment]
pushed up the fix. can work on getting an analytic tga result for firebot.

**Comment by rmcdermo** [comment]
A simple interim hack for the "analytic result" could be to store the "correct" result from this run for comparison.  Not ideal, but it would at least catch a change.

**Comment by drjfloyd** [comment]
I'll do that now.

**Comment by mcgratta** [comment]
An alternative is to see if the area under the curve has a physical meaning that we can check against.

**Comment by drjfloyd** [comment]
MLR should integrate to the intial mass * (1-char fraction) and MCC should integrate to initial mass * (1 - char fraction) * heat of combustion. DSC has a physical meaning but not one that is easily analytic. A goodly portion of the DSC is just the mass participating in each reaction time the heat of reaction but there is also the contribution of the specific heat over time and peak width impacts that.

**Comment by mcgratta** [comment]
DSC integrated over time comes to 1867 J/g. I can get close to this by summing the contributions of reaction energy and specific heat. But, yes, it's hard to pin down exactly.
