### ISSUE TITLE
User Manual: Hardware and OS Requirements

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12537]
Are there any issues with the m2 chip which should be discussed here?

![image](https://github.com/firemodels/fds/assets/17127980/9faa015d-f51b-499a-bf79-84c8ed4d5b63)

**Comment by rmcdermo** [comment]
Yes, I'll add something, but will be a few hours.

**Comment by rmcdermo** [comment]
Should be addressed with PR #12545
