### ISSUE TITLE
Input tables no column headings

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#12533]
@mcgratta @rmcdermo 

Should we add column headings to the tables of inputs?  

Keyword & Type & Description & Units & Default \\hline \hline

**Comment by rmcdermo** [comment]
I'm neutral.  To be honest, I never noticed they were not there and I've never been confused by the columns.  But I don't see how it could hurt, unless is becomes a PITA to deal with tables that span more than one page.  If that is a hassle, I would not mess with it.

**Comment by drjfloyd** [comment]
Not a hassle. Just have to put the headings in twice for each table. Once for the first page and once for the continuation header

continued page would look like this:

![image](https://github.com/firemodels/fds/assets/12799217/fe121cc4-36f9-46f8-885a-c5d93b417e90)

**Comment by mcgratta** [comment]
I assume you're just copying the extra header line into each table entry? If so, then yes, might as well.

**Comment by drjfloyd** [comment]
yes just pasting the line into each of the table definitions.
