### ISSUE TITLE
User Guide Fig 21.6 and 21.7

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#12532]
Should the axes for 21.6 be adjusted to zoom in more on the results?

21.7 1600 m pressure drop lower right doesn't show any curves.

**Comment by rmcdermo** [comment]
For 21.6, I think the point is to the show the scale and how the different solvers compare, hence one result being very small on that scale is a good thing.

For 21.7, this is what I am seeing in the latest FDS User Guide that got pushed to the test bundles release.  I also was able to build this locally with Matlab and get the same.  You might need to update your firemodels/out repo if you are not reproducing this.

<img width="365" alt="Screenshot 2024-02-24 at 9 35 07 AM" src="https://github.com/firemodels/fds/assets/4418497/4b440485-85a0-4b73-bf59-5c1a40683f47">

**Comment by drjfloyd** [comment]
OK make sense.  I thought I was looking at the test bundle version. I redownloaded and open and see what you see so I must have been looking at something else. Thanks!
