### ISSUE TITLE
Abnormal step size leads to unstable OUT file

### ISSUE THREAD

**Issue by Bravnewor** [firemodels/fds#12547]
An abnormal step size issue occurred in the case I provided. In the out file, when the time step is small, the output is normal. However, when the time step reaches around 70, the step size unpredictably changes. Each time I run this use case, the step size is different. For example, in the first run:

   Time Step      70   February  5, 2024  17:17:13
   Step Size:    0.893E-02 s, Total Time:       2.63 s
   Pressure Iterations: 1
   Maximum Velocity Error:  0.00E+00 on Mesh 1 at (11,12,14)
   Maximum Pressure Error:  0.25E+02 on Mesh 1 at (6,13,14)
   ---------------------------------------------------------------
   Max CFL number:  0.37E-01 at (6,13,14)
   Max divergence:  0.35E+01 at (6,13,14)
   Min divergence: -0.69E-01 at (6,13,15)
   Max VN number:   0.20E+00 at (6,13,14)
   Radiation Loss to Boundaries:         0.001 kW

However, in a subsequent run, it becomes:

   Time Step      70   February  5, 2024  17:17:16
   Step Size:    0.890E-02 s, Total Time:       2.63 s
   Pressure Iterations: 1
   Maximum Velocity Error:  0.00E+00 on Mesh 1 at (11,12,14)
   Maximum Pressure Error:  0.26E+02 on Mesh 1 at (6,13,14)
   ---------------------------------------------------------------
   Max CFL number:  0.37E-01 at (6,13,14)
   Max divergence:  0.35E+01 at (6,13,14)
   Min divergence: -0.70E-01 at (6,13,15)
   Max VN number:   0.20E+00 at (6,13,14)
   Radiation Loss to Boundaries:         0.001 kW

I am using FDS 6.8.0 on Windows 11. I have no clue why there is instability in the step size.
[case.txt](https://github.com/firemodels/fds/files/14395899/case.txt)

**Comment by johodges** [comment]
We have fixed several bugs related to initialization since FDS 6.8.0 was released. This issue might be fixed if you try the nightly build.

www.github.com/firemodels/test_bundles

**Comment by mcgratta** [comment]
I ran the test case.fds twice and diffed the out files. The are identical except for the time stamps. We get reports of this sort of thing occurring, but it is difficult to reproduce. My only advice is to compare the results of the calculations to see if they are significantly different. If yes, report the case. Small changes in time steps might just be due to the way your computer handles round-off or other numerical considerations.

**Comment by Bravnewor** [comment]
Sorry for not replying to you in time.

I re-ran case.txt and got some findings.

In version 6.8.0, there is indeed a significant numerical difference, taking Q_TOTAL as an example.
![Q_TOTAL](https://github.com/firemodels/fds/assets/93115139/ec9419cb-5784-4a3c-ad1c-b188df8437e2)


However in version 6.9.1 I ran it multiple times and now it can be considered a rounding error.
![Q_TOTAL_6 9 1](https://github.com/firemodels/fds/assets/93115139/e7c58d6f-3249-4de7-90de-a873dd27d135)

Thank you for your continued maintenance.
