### ISSUE TITLE
User Manual: Numerical Instability, Pressure Zones, and Imported Geometry

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12540]
Do we want to add a small section to the user support/troubleshooting section discussing pressure zones in imported geometry? I am imagining something like:

- large number of automatically generated pressure zones. FDS input files generated by a pre-processor from CAD geometry often include many parts of the model which are fully enclosed sections of air that are in reality solid. For example, a column may be imported as 4 thin obstructions in a box enclosing air. FDS will automatically identify these areas and assign them to separate pressure zones (see Section~\ref{info:ZONE}). These regions can lead to numerical instability over time. The total number of pressure zones identified by FDS can be determined by reviewing the \ct{casename.out} file. Telling FDS to automatically fill these zones (see Section~\ref{info:filling_zones}) or manually fixing the geometry in the FDS file can reduce these issues.

![image](https://github.com/firemodels/fds/assets/17127980/65ae71a5-e1d8-4e02-8f13-f4561c0c2953)

**Comment by drjfloyd** [comment]
Maybe this?:

large number of automatically generated pressure zones. This can happen when a pre-processor simply converts CAD geometry stored as faces to thin obstructions. For example, on a 10~cm grid, a typical interior gypsum board wall will appear in an FDS input file as two thin obstructions representing the gypsum board enclosing a single grid cell wide volume of air. FDS will automatically identify these regions as pressure zones; however, they can sometimes result in instabilities developing. The pressure zones identified by FDS can be determined by reviewing the \ct{casename.out} file. Telling FDS to automatically fill these zones (see Section~\ref{info:filling_zones}) or manually fixing the geometry to fill the regions can reduce these issues.

**Comment by johodges** [comment]
Works for me, I will get it added. Do you want me to add it to this PR https://github.com/firemodels/fds/pull/12539 or wait until that one is merged in?

**Comment by drjfloyd** [comment]
yeah just add it to that one and will merge them in

**Comment by johodges** [comment]
added
