### ISSUE TITLE
Instability of Max div. error at the OUT file

### ISSUE THREAD

**Issue by Bravnewor** [firemodels/fds#12546]
During the process of writing cases, it was discovered that the output files of some cases are not always consistent. In the scale-down case I provided, the grids where the Max div. error occurs at the same time step are not always the same, even though their values are consistent. For instance:

   Time Step       6   February  4, 2024  17:05:27
   Step Size:    0.952E+00 s, Total Time:      36.61 s
   Pressure Iterations: 1
   Maximum Velocity Error:  0.00E+00 on Mesh 1 at (2,17,18)
   Maximum Pressure Error:  0.12E-06 on Mesh 1 at (3,5,17)
   ---------------------------------------------------------------
   Max CFL number:  0.54E-01 at (4,23,3)
   Max divergence:  0.19E-05 at (3,4,17)
   Min divergence: -0.12E-05 at (5,22,37)
   Max div. error:  0.57E-07 at (2,18,13)
   Max VN number:   0.78E-01 at (1,23,3)
   Radiation Loss to Boundaries:         0.090 kW

However, when running the same case again, it becomes:

   Time Step       6   February  4, 2024  17:05:19
   Step Size:    0.952E+00 s, Total Time:      36.61 s
   Pressure Iterations: 1
   Maximum Velocity Error:  0.00E+00 on Mesh 1 at (2,17,18)
   Maximum Pressure Error:  0.12E-06 on Mesh 1 at (3,5,17)
   ---------------------------------------------------------------
   Max CFL number:  0.54E-01 at (4,23,3)
   Max divergence:  0.19E-05 at (3,4,17)
   Min divergence: -0.12E-05 at (5,22,37)
   Max div. error:  0.57E-07 at (1,2,22)
   Max VN number:   0.78E-01 at (1,23,3)
   Radiation Loss to Boundaries:         0.090 kW

This case was running FDS 6.8.0 version on Windows 11.I am not certain if there is randomness involved in selecting these peak values. How can I overcome this inconsistency?
[case.txt](https://github.com/firemodels/fds/files/14395877/case.txt)

**Comment by marcosvanella** [comment]
Try setting NOISE=F in the &MISC line. That will preclude FDS from making a random initial velocity field.On Feb 25, 2024 4:38 AM, Bravnewor ***@***.***> wrote:
During the process of writing cases, it was discovered that the output files of some cases are not always consistent. In the scale-down case I provided, the grids where the Max div. error occurs at the same time step are not always the same, even though their values are consistent. For instance:
Time Step       6   February  4, 2024  17:05:27
Step Size:    0.952E+00 s, Total Time:      36.61 s
Pressure Iterations: 1
Maximum Velocity Error:  0.00E+00 on Mesh 1 at (2,17,18)
Maximum Pressure Error:  0.12E-06 on Mesh 1 at (3,5,17)
Max CFL number:  0.54E-01 at (4,23,3)
Max divergence:  0.19E-05 at (3,4,17)
Min divergence: -0.12E-05 at (5,22,37)
Max div. error:  0.57E-07 at (2,18,13)
Max VN number:   0.78E-01 at (1,23,3)
Radiation Loss to Boundaries:         0.090 kW
However, when running the same case again, it becomes:
Time Step       6   February  4, 2024  17:05:19
Step Size:    0.952E+00 s, Total Time:      36.61 s
Pressure Iterations: 1
Maximum Velocity Error:  0.00E+00 on Mesh 1 at (2,17,18)
Maximum Pressure Error:  0.12E-06 on Mesh 1 at (3,5,17)
Max CFL number:  0.54E-01 at (4,23,3)
Max divergence:  0.19E-05 at (3,4,17)
Min divergence: -0.12E-05 at (5,22,37)
Max div. error:  0.57E-07 at (1,2,22)
Max VN number:   0.78E-01 at (1,23,3)
Radiation Loss to Boundaries:         0.090 kW
This case was running FDS 6.8.0 version on Windows 11.I am not certain if there is randomness involved in selecting these peak values. How can I overcome this inconsistency?
case.txt

**Comment by Bravnewor** [comment]
Thx for your prompt reply. I will give it a try.

**Comment by Bravnewor** [comment]
I apologize for not replying in time.
Your suggestion doesn't seem to be working.
I set 'NOISE=.false.' in the MISC line, but the inconsistency persisted, even when I used the latest version 6.9.1.

**Comment by marcosvanella** [comment]
Hi @Bravnewor, I tried the case on the Mac target and did not see the inconsistency you are seeing. It might be that numbers over the mesh are the same (see the next comment). 
Most important is why you see this Divergence Error. This means that in your case you are not matching the target divg in the projection due to having NO_PRESSURE_ZONES=T in a closed compartment. This is not allowing the background pressure to increase as it should and giving you a projection error. 
My suggestion is : Take that out of the misc line, it is used for diagnostics in special cases. You always want to have pressure zones. Also, do not fix the timestep (with DT=.. in the &TIME line), you are overruling the CFL constraint here (note it will take twice the number of time steps to run to completion if you take the DT out).

Please run the case with 6.9.1 a couple of times and let me know if you see divergence or other data locations randomly changing. To see the new divergence error in the .out file add a:
&PRES CHECK_POISSON=T/ 
line. Thanks.

**Comment by Bravnewor** [comment]
Thanks again for your reply! Your help is always so timely.

As you mentioned, I removed NO_PRESSURE_ZONES=T and DT and added &PRES CHECK_POISSON=T/.

I ran them three times on 6.9.1 and compared their out files. The inconsistency now only appears in the Poisson Error section.

I don't know what to do with these outputs, so I'm attaching these output files as an attachment.
[case_a.txt](https://github.com/firemodels/fds/files/15196574/case_a.txt)

[case_b.txt](https://github.com/firemodels/fds/files/15196576/case_b.txt)

[case_c.txt](https://github.com/firemodels/fds/files/15196578/case_c.txt)

**Comment by marcosvanella** [comment]
Hi @Bravnewor, your Poisson errors are of the order of 10^-17. For all intents and purposes this means they are zero. The difference you see might be due to floating point accuracy errors. I would not worry about this.

**Comment by Bravnewor** [comment]
Ok, I'm going to close this issue
