### ISSUE TITLE
User Manual: HVAC & GEOM

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12541]
Is this statement in the user guide true regarding implementation of HVAC for a GEOM surface being planned soon? The same statement was there in the 6.8.0 release.

![image](https://github.com/firemodels/fds/assets/17127980/452947a4-c4f5-4ee2-8b83-fc08937e8739)

**Comment by drjfloyd** [comment]
I don't think Marcos has anything to support this yet.

**Comment by johodges** [comment]
Makes sense. It would be a nice feature, but not sure if it is that level of priority with everything else going on. I was mainly thinking we should remove the "planned for next maintenance release" part unless that is true.

**Comment by marcosvanella** [comment]
No, vents are not supported. IT's in the list of things to do. I'll reword this.

**Comment by marcosvanella** [comment]
I changed this section. I'll close this as we already have issue #11769 on vents.

**Comment by johodges** [comment]
Thanks Marcos
