### ISSUE TITLE
Check unstructured mass transport equations in tech guide

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12553]
@marcosvanella Please have a look at Eq. (12.10).  This looks to be a remnant of doing implicit mass transport in GEOM.  Do we still need the "mass matrix"?

**Comment by marcosvanella** [comment]
I'll check it out.On Feb 26, 2024 10:56 AM, Randy McDermott ***@***.***> wrote:
Assigned #12553 to @marcosvanella.
