### ISSUE TITLE
Check FDS Tech Guide discussion of solid discretization for heat flux

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12552]
Please have a look at the tech guide discussion surrounding Fig 7.1, where we show discretization of heat flux in a solid with deformation.  It looks to me like this figure is a hold over from the old HT3D approach.  But it might still be correct.  If it is we can leave it.  If not, then let's remove and also the section with Eq. (7.33).

**Comment by mcgratta** [comment]
The 3D solver is described in the Appendix where the 1D solver is described. I'll see what can be moved where.

**Comment by mcgratta** [comment]
I removed the write up in Chapter 7. The new HT3D model uses all the same assumptions as the 1D except for the lateral heat transfer, which is described in App L.
