### ISSUE TITLE
Something broken with OpenMP cases

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12555]
Maybe just a cluster hiccup, but this can't go out with the bundle.

<img width="622" alt="Screenshot 2024-02-26 at 11 20 35 AM" src="https://github.com/firemodels/fds/assets/4418497/447c6974-0ceb-45bd-a706-ff70efa6b89b">

**Comment by mcgratta** [comment]
I'll take a look at this.

**Comment by mcgratta** [comment]
[openmp_timing_benchmarks.pdf](https://github.com/firemodels/fds/files/14407932/openmp_timing_benchmarks.pdf)

This was just run on burn.

**Comment by rmcdermo** [comment]
The blaze run from last night is better, but still the burn run looks more like what I expect out of a clean openmp run.

I suggest we set up these cases in validation and commit the burn runs to the `firemodels/out` repo.  Then the FDS user guide plot will look better.  We can keep the nightly runs as is to flag any threading errors.

**Comment by rmcdermo** [comment]
Next firebot run should use the burn results PR #12570

**Comment by rmcdermo** [comment]
Looks like this worked.  Will reopen if necessary.
