### ISSUE TITLE
Wind Study 

### ISSUE THREAD

**Issue by antoniomaze** [firemodels/fds#12550]
Hi ,
I have run the beow test wind file. The wind intensity varies with Z. 
Is there a way to vary the wind along the X and Y axes as well? This would be useful in my study where I have a building with different roof heights, and the attached wind model would force unwanted wind within the building
Thanks

&HEAD CHID='test_wind'/
&TIME T_END=10.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25/
&WIND SPEED=5.0, DIRECTION=290.0, RAMP_SPEED_Z='zed'/

&RAMP ID='zed', Z=0.0, F=0.0/
&RAMP ID='zed', Z=4.9, F=0.0/
&RAMP ID='zed', Z=5.1, F=1.0/

&MESH ID='MESH', IJK=30,18,10, XB=-8.0,22.0,-15.0,3.0,0.0,10.0/

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=22.0,22.0,-15.0,3.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=-8.0,-8.0,-15.0,3.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [YMAX]', SURF_ID='OPEN', XB=-8.0,22.0,3.0,3.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=-8.0,22.0,-15.0,-15.0,0.0,10.0/ 
&VENT ID='Mesh Vent: MESH [ZMAX]', SURF_ID='OPEN', XB=-8.0,22.0,-15.0,3.0,10.0,10.0/ 

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice', PBZ=2.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice01', PBZ=5.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice02', PBZ=8.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice03', PBY=0.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice04', PBY=-6.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice05', PBY=-12.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice06', PBX=-4.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice07', PBX=7.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='Slice08', PBX=18.0/

&TAIL /

**Comment by rmcdermo** [comment]
Not at the moment, but we are working on it.  Please follow this Issue #12399 for developments.
