### ISSUE TITLE
SPyro issues in verification guide

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12560]
@johodges Please have a look at all your sections in the verification guide.

1. Figure labels in TOC and list of figures should be only one line.
2. Case names have changed to "spyro_cone_demo", etc.  This needs to be fixed throughout, including in section titles and Matlab plot names.

**Comment by johodges** [comment]
Should be fixed in https://github.com/firemodels/fds/pull/12563. Updates:

- Short and long names were previously switched, fixed.
- Fixed renaming of "cone_demo" to "spyro_cone_demo" in section titles and matlab plot names.
