### ISSUE TITLE
Precision error giving unexpected wind boundary

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#12574]
Looking at the CSIRO cases, I noticed an unexpected asymmetry in the background wind field, which should be constant and aligned directly with the x-axis. 

Doing some digging, it looks like the V_WIND has a very small non-zero value ...I guess due to some precision error when converting from SPEED and DIRECTION to U_WIND and V_WIND? Because of this, boundaries with IOR=-2 (left boundary in screenshot) are being treated differently than IOR=2 (right boundary in screenshot) when computing the dot product in this part of the code:

https://github.com/firemodels/fds/blob/bc9da78900b2fb3a61ea13171a12e1d696f30573/Source/pres.f90#L192-L194

I'm not sure if this is something we need to clean up in terms of computing the wind components or changing this check in pres.f90.

I tested both Case_C064_fine and Case_C064_crude on blaze and also as single mesh of the crude case on my mac and all show this behavior.

![image](https://github.com/firemodels/fds/assets/13366803/fa34299c-43b6-4383-902f-c206607a608c)

**Comment by mcgratta** [comment]
I think the lines of interest are these in `velo.f90`
```
               IF ((IOR==1.AND.U_WIND(KK)>=0._EB) .OR. (IOR==-1.AND.U_WIND(KK)<=0._EB)) UPWIND_BOUNDARY = .TRUE.
               IF ((IOR==2.AND.V_WIND(KK)>=0._EB) .OR. (IOR==-2.AND.V_WIND(KK)<=0._EB)) UPWIND_BOUNDARY = .TRUE.
               IF ((IOR==3.AND.W_WIND(KK)>=0._EB) .OR. (IOR==-3.AND.W_WIND(KK)<=0._EB)) UPWIND_BOUNDARY = .TRUE.
```
I think what we want to do is something like this
```
               IF ((IOR==2.AND.V_WIND(KK)>=-TWO_EPSILON_EB) .OR. (IOR==-2.AND.V_WIND(KK)<=TWO_EPSILON_EB)) UPWIND_BOUNDARY = .TRUE.
```
but I need to think about ramifications. The idea is to say that if the wind velocity is inward or zero at an external boundary, we consider it an "upwind" boundary.

**Comment by ericvmueller** [comment]
True that may also be an issue, but the upper and lower y-boundaries are definitely being treated differently in pres.f90 when I run this case, which does not seem like what we want here.

**Comment by rmcdermo** [comment]
I think we are going to be playing whackamole here.  At one point, the way we were treating the wind boundaries seemed pretty solid.  I'd like to revisit the case that led to using UPWIND_BOUNDARY.  @mcgratta do you remember which issue led to this change?

**Comment by mcgratta** [comment]
That's a bigger issue. It is difficult to transition seamlessly from inflow to outflow boundary conditions. Ideally, this tiny velocity should not matter, but the way we handle the BC for tangential velocity at the lateral mesh boundary depends on whether the v component of wind velocity is positive or negative. In this case, it is 8.45e-16, meaning positive.

**Comment by ericvmueller** [comment]
@rmcdermo I think this came from https://github.com/firemodels/fds/issues/12326 ...and generally just getting instabilities in any case with fire spreading into a downwind boundary with the old logic

**Comment by mcgratta** [comment]
We apply the WIND as the tangential velocity on mesh boundaries at which (1) the background WIND is incoming, and (2) the actual flow velocity is incoming. This prevented the noise that we used to see at the downwind mesh boundary.

**Comment by rmcdermo** [comment]
An update on this.
1. The case runs fine with 6.8.0.
2. With current master, if I take out all the UPWIND_BOUNDARY logic, the case still has an issue with asymmetry, unless I comment the MO parameters.  This leads me to believe that something else is causing the problem.  I'm bisecting now to see if I find an obvious change.

**Comment by rmcdermo** [comment]
Not surprisingly, the first bad commit on my bisect was [6ddb8a](https://github.com/mcgratta/fds/commit/6ddb8afa7e0621c2e451b17b3614f244811e71e4).

I realize that this was implemented to avert instabilities.  However, when I revert this change with the latest code, I cannot get the Catchpole case to fail.

@ericvmueller Please send me another WUI case that was failing previously and I'll test that with my changes.  Thanks

**Comment by rmcdermo** [comment]
Here I'm storing the test case I was using, then I will clean my repo and rerun the validation cases for Catchpole.
[EXSC19_coarse.fds.txt](https://github.com/firemodels/fds/files/14487008/EXSC19_coarse.fds.txt)

**Comment by rmcdermo** [comment]
Bummer... back to the drawing board.
```
rmcdermo@burn Current_Results (master) $ grep Numerical ./*.out
./EXSC17.out:ERROR: Numerical Instability - FDS stopped (CHID: EXSC17)
./EXSC19.out:ERROR: Numerical Instability - FDS stopped (CHID: EXSC19)
```

**Comment by ericvmueller** [comment]
Ah okay, I was going to report that my test case with the downwind instability in the original implementation appeared to be working with your fix of reverting [6ddb8a](https://github.com/mcgratta/fds/commit/6ddb8afa7e0621c2e451b17b3614f244811e71e4) ...but I guess there's still something off here

**Comment by mcgratta** [comment]
I can maintain symmetry in a simple wind case (with or without MO parameters) by modifying IF statements in both `velo.f90` and `pres.f90` pertaining to the lateral mesh boundaries. Like comparing V or V_WIND to small numbers rather than 0 because the value of both are small positive values on both the left and right boundaries. This doesn't address anything other than symmetry.

**Comment by rmcdermo** [comment]
@ericvmueller I think I have this sorted with PR #12598 .  It is passing all my tests.  Let me know if you see any issues.  I'll rerun the Catchpole validation cases that were unstable.

**Comment by ericvmueller** [comment]
Nice work tracking that down to the fluxes! This change cover the CSIRO asymmetry, too? As in, it was related to the very small error in the dot-product calculation in pres.f90 and not the one velo.f90?

**Comment by rmcdermo** [comment]
That seems to be the case.

**Comment by rmcdermo** [comment]
Good news, the Catchpole cases ( from the instability report #12326 ) I started last night finished fine.  I had forgotten to include `EXSC9.fds`, so running that now.

**Comment by rmcdermo** [comment]
All unstable cases now seem fine.  I'll close this and let's keep our eye on the downwind boundary cases.
