### ISSUE TITLE
The issue of certain values being discontinuous during continuation calculations in FDS version 6.7.0.

### ISSUE THREAD

**Issue by goodman249** [firemodels/fds#12575]
Hello, I encountered an issue while simulating with FDS 6.7.0. After resuming the calculation, I noticed that the PID output values are discontinuous and deviate significantly from the expected values. I would like to know how to resolve this situation and if there are any good solutions.

**Comment by Er9y714** [comment]
Is running the latest version not an option?

**Comment by drjfloyd** [comment]
Try running with the latest test release. If it still happens, then please submit a simple case that demonstrates the issue. 

If there is some issue with the restart file data and the PID control function, the work around would be to not use RESTART.

**Comment by drjfloyd** [comment]
https://github.com/firemodels/test_bundles
