### ISSUE TITLE
Bugs of case geom_bad_inconsistent_normals.fds

### ISSUE THREAD

**Issue by lihy213** [firemodels/fds#12580]
**Describe the bug**
Some bugs occur in file .\Verification\Complex_Geometry\geom_bad_inconsistent_normals.fds for the parameter `FACES` of command `GEOM`.

**To Reproduce**
1. Go to file .\Verification\Complex_Geometry\geom_bad_inconsistent_normals.fds
2. See error: _ERROR: GEOM ID=Cube_inconsistent_normals. Check &GEOM input line. (CHID: geom_bad_inconsistent_normals)_
before correction, the `FACES` indices are as follows:
![image](https://github.com/firemodels/fds/assets/96673442/69fd5a8e-ce4d-4712-817e-671d3b98af94)
after correction, the `FACES` indices should be:
![image](https://github.com/firemodels/fds/assets/96673442/ee361f49-b501-4095-9a7a-9eb8800b5ae4)
the indices in the red frame represent the opposite direction from the others, so it should be the same direction, see from FDS_User_Guide, Page 47.

**Additional Information**
after correction, Smokeview shows the right sight,
![image](https://github.com/firemodels/fds/assets/96673442/2ae995fb-bdfd-4cb3-97a2-03d0a59b23d6)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Comment by lihy213** [comment]
It should be noted that the same error occurred when I ran other .fds files prefixed with geom_bad_xxx.

**Comment by emanuelegissi** [comment]
Well, all the geom_bad cases are intentionally broken. The goal is testing FDS capability to catch malformed geometries.

**Comment by rmcdermo** [comment]
Thanks for checking, but as Emaunele said, this is intentional.
