### ISSUE TITLE
Error in HRR when specifying HRRPUA with multiple reactions defined

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12586]
**Describe the bug**
Something seems to be amiss with using HRRPUA on SURF and specifying the SPEC_ID for the fuel, if my read of the user guide is correct.

**To Reproduce**
Run the attached input file and you should get 100 kW HRR.  As is, the HRR is almost twice that high.

[test.fds.txt](https://github.com/firemodels/fds/files/14500363/test.fds.txt)

**Expected behavior**
If you comment the HRRPUA SURF and use the MASS_FLUX SURF with ETHYLENE then the HRR is correct

**Comment by rmcdermo** [comment]
I suspect what is happening is that the HRRPUA is being based on the partial reaction, R1.  I can't think of a simple way to do this in general unless we tabulated complete reaction chemistry for each pre-defined "fuel".  I'll close... I don't think there is anything to do here but use MASS_FLUX.

**Comment by drjfloyd** [comment]
Your assessment is correct. WIth multiple REAC inputs there is no simple way for FDS to be able to know what the true H_o_C is.

**Comment by ShiChenglong-0423** [comment]
How I want to simulate the combustion of two different materials is unrealistic, because the FDS has no way to determine the distinction between multiple REACs.

**Comment by rmcdermo** [comment]
You can do this, there is a gas phase output called 'HRRPUV REAC', which takes 'REAC_ID' as a parameter.  See the `hrrpuv_reac` series in the FDS Verification Guide.  For example,

https://github.com/firemodels/fds/blob/master/Verification/Species/hrrpuv_reac_parallel.fds
