### ISSUE TITLE
Modelling a gas leak from a cylinder

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12607]
**The bug**
I am interested to model a gas leak from a small hole (of the order of 8 mm), in a 1 m resolution grid. So this is a localised leakage which must be resolved in the subgrid scale. I checked the Section 12.3.2, and I tried to perform localised leakage, with a defined mass flux throught that hole. When I check the results, I see that the gas coming out of the entire surface where the hole is defined, instead of the just from the hole. 

**To Reproduce**
I am attaching my FDS input file here
[testLeak.txt](https://github.com/firemodels/fds/files/14560565/testLeak.txt)

**Expected behavior**
I wanted to see Methane gas leaked out of the hole at the specified mass flow rate

**Desktop:**
 - OS: MacOS Sonoma. But I would like to implement in HPC, so it would be Linux

**Comment by drjfloyd** [comment]
You can't do HVAC that way.  The LEAK model can only be used with VENTs
that have no specified flow.  The HVAC leakage model is calculating the
flow. You can't have a surface with both prescribed and calculated flow.
In your case you just need the SURF. The HVAC line isn't doing anything.

Keep in mind that FDS is a low mach number code.  A leak from a pressurized
line is likely a compressible flow.

**Comment by mcgratta** [comment]
I doubt you will be able to do that and still simulate a large domain. Decide what is important -- near-field or far-field phenomena.

**Comment by rakyuv** [comment]
You are right @mcgratta. It does get complicated to model the leak with 8 mm mesh resolution and increase it till 1 m resolution for the far-field. I ran into a problem already at the first step, as you can see in https://github.com/firemodels/fds/issues/12611#issue-2181397160

My objective is to study the gas emission at 40 - 50 m from the source. This requires a 100 m^2 domain with methane source in the center to capture this dynamics at 1 m resoluton. The only problem being that the methane source has 8 - 10 mm radius. So I am trying the implement multiple meshes with different resolutions to find a way with it.

**Comment by mcgratta** [comment]
Do the details of the leak really matter 50 m away? You might want a finer mesh than 1 m near the source, but 8 mm is probably not going to help you very much.

**Comment by rakyuv** [comment]
@mcgratta, The details of the leak matters although I do the analysis at 50 m away from the source, because for the same mass flow rate, the leak radius determines the altitude at which the gas is released. I have already tried to place the source as cylinder with 1m^2 radius. Since the 1 m^2 area is much higher than original release radius of 8 mm^2, the plume was released at a lower altitude in FDS due to its lower velocity. Therefore I have no other way than to use a higher resolution near the source to resolve the source itself, and then decrease the resolution away from it to simulate a large domain.

**Comment by mcgratta** [comment]
OK, then inject rapidly evaporating particles from a single point with high velocity and tune the evaporation rate to mimic the leak.

**Comment by rakyuv** [comment]
Thank you @mcgratta. Your idea seems like the optimised choice for my purpose. I will check the FDS_User_Guide for its implementation.

**Comment by drjfloyd** [comment]
The leak will entrain air as you move away from the origin of the leak. Another option is to determine the air entrainment at some distance downstream from the leak where you can afford to resolve the jet and at that location inject a mixture of air and leak and also remove air (so the net mass is just the leak flow).  This will preserve the momentum of the leak which is not done if you simply put the leak mass over a larger area.

**Comment by rakyuv** [comment]
Thank you @drjfloyd for your suggestion. I can clearly understand releasing the mixture of air+gas at a downstream location where the leak is sufficiently diffused to be resolved by my grid resolution. I am not entirely sure how to remove air from the simulation. Could you please tell me how to remove air from the simulation ?

**Comment by drjfloyd** [comment]
FDS User's Guide Chapter 10: Ventilation

**Comment by rakyuv** [comment]
Hi @drjfloyd. The solution you proposed is to inject air+gas at a downstream location where the plume is big enough to be sufficiently resolved with 1 m resolution grid. For this reason, I am presently running a simulation with 0.2 m resolution, and with a 2.25 m^2 methane source, to see the evolution of the plume with distance. With these results, I will be able to determine the convenient location downstream for the methane+air release. My question is about how to remove air from the simulation, without affecting the dynamics of the methane plume ? Do I remove air from upstream of the methane release ? or can it be from the side boundaries perpendicular to the plume motion ?

**Comment by drjfloyd** [comment]
If your leak source is compressible, then reducing the grid size isn't going to let you correctly model the compressible portion of the jet. You can search the relevant literature for data on the expansion of jets.

As far as removing air goes, you may want to try different methods and see what works best for your specific case,

**Comment by rakyuv** [comment]
To test the mixture of air and methane, I have the following input file for FDS
[testfds.txt](https://github.com/firemodels/fds/files/15379983/testfds.txt)

I am trying to release 50% Methane and 50% Air from the VENT 7. However the mass of methane in the simulation is as if, it is 100% Methane. Could you please tell me how to release the mixture of Methane + Air ?

**Comment by rmcdermo** [comment]
Try this.  You don't need to define the lumped SPEC 'METHANE AIR'.
```
&SPEC ID='METHANE'/     
&SURF ID='BLOWER', MASS_FLUX(1)=6.9000e-06, SPEC_ID(1)='METHANE',
                   MASS_FLUX(2)=6.9000e-06, SPEC_ID(2)='AIR',
                   COLOR='RED'/
```

**Comment by rakyuv** [comment]
Thanks @rmcdermo for the answer. It works correctly as expected
