### ISSUE TITLE
Level Set not reinitialized properly on RESTART

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12608]
Trying to debug something else, I had set a DT_RESTART on the topo_demo case and got an instability at around 90 s.  When I restarted, it appears that the LS model now thinks that all the burnt area is available to burn again.

![Screenshot 2024-03-11 at 6 15 21 PM](https://github.com/firemodels/fds/assets/4418497/1903c88f-ed2b-4101-9d6c-f094c6f4fcd6)

I will try to simplify this tomorrow.  But for now, the case in question is here: `/home4/rmcdermo/Issues/Eric_M/save_topo_demo.fds`

**Comment by rmcdermo** [comment]
Essentially, I think we need to add a level set restart verification case to address this issue.

**Comment by rmcdermo** [comment]
This seems to be a geom issue.  At least, at this point I have not reproduced it without a geom or obst (just letting the LS be on the bottom boundary).

**Comment by marcosvanella** [comment]
I'm running a db firebot to test my changes addressing this issue. Main problem was the BOUNDARY_PROP1 variables for boundary CFACEs were getting overwritten after being read from the restart file.

**Comment by rmcdermo** [comment]
I think things are ok now.  Let me get the verification case buttoned up tomorrow and if that is all good, then I'll close.  Thanks!

**Comment by rmcdermo** [comment]
Here is what the HRR looks like now on RESTART.  You cannot tell from this scale on the y axis, but the tail is not exact.  The restart case is off by 10s of kW on the tail.

It is strange to me that we could have a hiccup at 20 s and still be to tight later in the calculation.  Open to suggestions as to what this might be.  Right now I have the error tolerance set to 0.1 % relative error on "area" under the curve.  The case is not passing with this tolerance, the error is about 0.3 %.

[geom_ls_restart.pdf](https://github.com/firemodels/fds/files/14591631/geom_ls_restart.pdf)

**Comment by marcosvanella** [comment]
From that hiccup plot it looks to me like we are still missing something.
Does the first (and 2nd) timestep change after the restart from what they are without restarting?
________________________________

**Comment by rmcdermo** [comment]
I agree, but this may be hard to pin down.  The cases are running in the verification suite `fds/Verification/Restart/geom_ls_restart` and "passing" in that I set the relative error tolerance to 1 % and this works.  Let's leave this open as a reminder that we need to investigate when we have time.

**Comment by mcgratta** [comment]
I looked at the discrepancy in HRR at the time of the restart. The largest discrepancy comes from the summing of `CUT_CELL(ICC)%Q(JCC)`. This quantity is computed in `fire.f90`, but I cannot pinpoint what is wrong. There must be some variable that is not being passed in the restart file, or perhaps there is some summation over time that is being disrupted by the restart.

To see the error, run the cases in the `Restart` verification directory:

`geom_restart_base_case.fds`
`geom_restart_a.fds`

and then run

`geom_restart_b.fds`

and then plot the HRR from the base case and the restarted case.

**Comment by marcosvanella** [comment]
I made the geom_ls_restart cases run for a shorter time, restarting at 10 sec and fixing DT to 0.1s. The restart file is written at 10.5sec (I assume to finish the radi cycle). I see the jump you refer to in HRR. For some reason the 10.5 HRR value is missing in the geom_ls_restart_hrr.csv file. I'll look in fire.f90 next.

<img width="1280" alt="Screenshot 2024-05-01 at 2 52 53 PM" src="https://github.com/firemodels/fds/assets/7450069/9b856c81-3f91-4c5c-9d4d-5bce0548421b">

**Comment by marcosvanella** [comment]
Do an update and try the case again. Still not perfect but close.
