### ISSUE TITLE
Smokeview-CFAST-Temperature Options Missing

### ISSUE THREAD

**Issue by firemist** [firemodels/fds#12614]
**Describe the bug**
These models that I'm working on now are in CFAST. This issue relates to the display temperature options of the CFAST case in smokeview. I found this because I was working on multiple machines and one machine had the temperature options while the other did not. I would like to be able to present these results with displays in Fahrenheit for this work.

**To Reproduce**
The Smokeview nightly for 16-Feb-2024 has the temperature options while the build for 12-Mar-2024 does not have the options.

![image](https://github.com/firemodels/fds/assets/25644607/7feaaad4-6ddd-4b23-b518-c98b575ac591)

versus

![image](https://github.com/firemodels/fds/assets/25644607/c0b5b067-8db4-4782-9326-ca87a8919979)

In both cases, they are looking at the results of CFAST mod_01. (I apologize for cutting that off in one of the clips.)

Thank you for your assistance.

**Comment by gforney** [comment]
I don't recall taking out this option - maybe a side effect of something else I did.  I"ll take a look

**Comment by firemist** [comment]
I have downloaded smokeview test executables many times in the past without difficulty.

Google Chrome is reporting that the 2150 status as "virus detected" and has deleted the download.

I want to check with you regarding this because I am not sure whether this is possible or not. I think you know, as I said above, that I have done these downloads many times without issue, which is why this message gives me pause to try and figure out how to proceed. 

I wanted to also check with you and the rest of the group to see if this has been detected by others.

So far, I have not been able to determine what "virus" the system thinks has been detected.

**Comment by gforney** [comment]
I deleted the installs.  I will check for virus in the bundles.  thanks for reporting

**Comment by gforney** [comment]
I scanned the installers and the files the installers were made from for all three platforms using SentinelOne the virus scanner we use at NIST. It did not find any malicious files.  Let me know if you are able to identify any particular files your scanner is identifying as a problem. I put the installers back .

**Comment by drjfloyd** [comment]
I just tried downloading 2150 on a windows PC using Chrome and the only warning I got was about downloading an unknown exe and did i want to continue.

**Comment by firemist** [comment]
This is strange (and frustrating with the system) -- it is specifically the smv 2150 download that I'm getting this error and I'm not getting it on any other download from the platform. I will have to fetch it through some other process so it doesn't get automatically deleted and then scan it independently and see what gets report. Unfortunately, I can't do that immediately as I need to concentrate on some other things right now.

I appreciate your assistance. I'll try to get this done asap and let you know what I find out. Thanks!

**Comment by firemist** [comment]
OK, I found the error that's being put forward from Windows Security:

![image](https://github.com/firemodels/fds/assets/25644607/93f04571-4cfd-4d4c-b2c5-39b24e540925)

**Comment by gforney** [comment]
I uploaded another set of bundles - 2154 (very minor difference from 2150) . also put it at the google drive directory
https://drive.google.com/drive/folders/0B_wB1pJL2bFQcURod1UyZTJUaEE?resourcekey=0-CW_02fKmi4jxSqW_n9_G7w&usp=sharing

**Comment by firemist** [comment]
I downloaded smv 2154 both from the Google Drive link and as well from the test website. Neither of those reported a virus and both appear to work the same. They both have the temperature selection that I wanted.

Thanks very much!

I don't know if you want me to close this or not because I'm concerned about the potential virus issue. I've done no updates or made any changes to the virus scanning program and yet 2150 reported the virus (detailed above) and 2154 did not report a virus and went straight through.

If you want to tick it closed, I certainly understand as this issue is resolved. If you'd like me to do more testing, please let me know.

**Comment by rmcdermo** [comment]
I vote to keep digging.  I'd like to understand what happened, if that is possible.  I think we need to look more into a formal signing process for the code.

**Comment by drjfloyd** [comment]
I searched that virus and it has a number of reports of false positives. Anti virus programs are like medical screening tests in that they bias towards false positives rather than false negatives. They just look for small blocks of code matching known viruses. That can happen if you have software that performs a virus like action intentionally or if you just get unlucky in compilation. We have had many smokeview test releases, and this is the first time I am aware of this problem cropping up.

**Comment by firemist** [comment]
But I guess that's my concern. While I agree with you that virus scanning programs are biased towards false positives, I've never had this happen before on any other download nor on the 2154 download. So, I'm not sure I would think that the incremental changes occurring with smokeview at this time, would have suddenly caused the 2150 version to be detected as having a viral segment onboard and the ones around it do not. Also, in my experience, if the detection is based on heuristics, it gives a different message and does not identify it as a specific, named virus.

**Comment by drjfloyd** [comment]
I had a false positive giving a named virus last year.

**Comment by gforney** [comment]
if you still see a problem reopen the issue
