### ISSUE TITLE
run fds6.7.5 version problem

### ISSUE THREAD

**Issue by goodman249** [firemodels/fds#12617]
When running fds, it prompts that impi.dll cannot be found. What should be done to resolve this issue.
When using cmdFDS, it can only be used on the C drive. How should I operate when I want to calculate on the D drive. Looking forward to an answer. Thank you.

**Comment by gforney** [comment]
Type fdsinit then try running your case. That is all the command shell CMDfds does before it opens

**Comment by goodman249** [comment]
When using restart to calculate the file, the system prompts that the fds file does not exist, but fds is in the file.

**Comment by mcgratta** [comment]
I do not understand what you are saying. What is the exact wording of the error message and what command have you issued to run the job?

**Comment by goodman249** [comment]
> I do not understand what you are saying. What is the exact wording of the error message and what command have you issued to run the job?



> I do not understand what you are saying. What is the exact wording of the error message and what command have you issued to run the job?
Thank you for your reply，Error occurred when restarting the job.

C:\Users\15327\Desktop\ceshi\ceshi>fds_local -p 24 -o 1 hrr2_5_ex1_6_acv3_p_zn_2.fds
***error: The input file hrr2_5_ex1_6_acv3_p_zn_2.fds does not exist

**Comment by mcgratta** [comment]
My only guess is that there is some issue with the working directory. Is the directory remote? Try running the case within a directory that you know is on the hard drive of that computer.
