### ISSUE TITLE
Mesh out of alignment

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12611]
**The bug**
I get Mesh out of alignment error, despite having integral number of cells between meshes with different resolutions

**To Reproduce**
I am attaching my FDS input file here
[testMesh.txt](https://github.com/firemodels/fds/files/14571498/testMesh.txt)

**Screenshots**
This is the screenshot of the meshes
![Capture d’écran 2024-03-12 à 12 34 20](https://github.com/firemodels/fds/assets/38204789/c146ceca-4a6e-478f-8f68-b169cc2b8972)

**Desktop:**
 - OS: MacOS
 - Version: Sonoma

**Comment by rmcdermo** [comment]
This is not allowed.  You have two meshes touching one cell.

<img width="993" alt="Screenshot 2024-03-12 at 8 22 35 AM" src="https://github.com/firemodels/fds/assets/4418497/b388c855-7287-48ad-a250-31a7ec7df3cc">

This violates this rule in the user guide.

<img width="784" alt="Screenshot 2024-03-12 at 8 27 42 AM" src="https://github.com/firemodels/fds/assets/4418497/f03db495-9795-4ab6-a928-426a48b9b032">

**Comment by rakyuv** [comment]
Thank you @rmcdermo for the clarity
