### ISSUE TITLE
An error occurred in MPI_Testall

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12620]
**The bug**
This is an extension of my approach from this bug https://github.com/firemodels/fds/issues/12607#issue-2179396200, where I was wondering how to incorporate multiple resolutions (8 mm to 1 m)in a simulation. Before testing the approaches from @rmcdermo, @mcgratta and @drjfloyd to solve my problem, I wanted to give a try to do the simulation with the basic method of incorporating multiple meshes with different resolutions. I understand that my approach is memory intensive computationally. I was interested to test multiple version of this approach like (2cm -> 1 m), (10 cm -> 1 m), (50 cm -> 1m), and to see what I gain by increasing the resolution. 

**To Reproduce**
I am attaching the FDS input file here
[testMesh.txt](https://github.com/firemodels/fds/files/14590636/testMesh.txt)

**Expected behavior**
The simulation either runs or it is expected to throw some memory error. This is the error message I get
[error.txt](https://github.com/firemodels/fds/files/14590666/error.txt)

**Desktop:**
 - OS: Linux

**Comment by mcgratta** [comment]
```
&MESH IJK= 9, 9, 50, XB= -0.09,  0.09,  -0.09,  0.09, 24.0, 27.0, MPI_PROCESS=0, CHECK_MESH_ALIGNMENT=T/
&MESH IJK= 9, 9, 50, XB= -0.09,  0.09,  -0.09,  0.09, 24.0, 27.0, MPI_PROCESS=0, CHECK_MESH_ALIGNMENT=T/
```
You are running out of mulligans.

**Comment by rakyuv** [comment]
My apologies @mcgratta , for not paying attention to the repeating meshes. After removing any repeating meshes, I still end up having the numerical instability. This ([testMesh.txt](https://github.com/firemodels/fds/files/14613471/testMesh.txt)) is my latest FDS input file. Could you please help me resolve the issue ?

**Comment by rakyuv** [comment]
My apologies @mcgratta. I ran the FDS part by part. I have managed to run it fully. The problem I found was that FDS didn't like the aspect ratio to be 3:1 between z:xy axes, when the resolution is 2 cm. I reduced it 2.7:1, and it ran without any problem. So I am closing the issue. 
Thanks everyone
