### ISSUE TITLE
race_test case out of tolerance in debug mode

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#12642]
If I run the `race_test` cases in `Verification/Thread_Check`, the results are out of tolerance. The cases work in release mode. Note that I ran the cases on burn in db mode with the Intel compiler. Note also that this case involves MPI, which means that could be part of the issue too.

**Comment by marcosvanella** [comment]
Running with gnu db now on linux. Is there a reason we have DT_DEVC=0.1 in race_test_1 and DT_DEVC=0.5 in race_test_4?
________________________________

**Comment by marcosvanella** [comment]
I'm done up to 1.5 sec simulation time. devc numbers are exactly the same.

**Comment by marcosvanella** [comment]
I don't see differences using gnu compiler and openmpi. I still see the issue with oneapi 2024.0.0. 
We have:
- Between impi_intel_linux_db and impi_intel_linux_opemp_db + OMP_NUM_THREADS=1 => No difference.
- Between any of the previous and impi_intel_linux_opemp_db + OMP_NUM_THREADS=4 => Difference in devc already at 0.1 sec simulation time.
I'll look more in detail where things go off the rails.

**Comment by marcosvanella** [comment]
Looks like from the setup stage the MESHES(X)%D divergence array does not come with same values. That gives initial FVX, FVY, FVZ forces that are not the same between 1 and 4 threads.
I'll try to figure out why.

**Comment by marcosvanella** [comment]
Ok, when RADIATION=F things match exactly. It's got to be something on the openmp loops in radi.f90

**Comment by drjfloyd** [comment]
line 3766: Think we need to add ALPHA_CC to the PRIVATE

**Comment by marcosvanella** [comment]
Thanks Jason, I'll check them out with the case I'm running. I'm going one by one on these loops.

**Comment by marcosvanella** [comment]
So line 3985, we need IC, TSI, TMP_EXTERIOR as private.
BC in private 4174 (good call I wouldn't have found this with the case I'm running). ALPHA_CC was defined on the opening OMP parallel of that block.

Kevin try the race_tests in db mode in burn whenever you have time. Thanks.

**Comment by mcgratta** [comment]
```
5.0043791E-001, 9.1417070E+002, 8.9008105E-001
5.0043791E-001, 9.1417070E+002, 8.9008105E-001
```
So far, so good.

**Comment by mcgratta** [comment]
```
 1.0056212E+000, 9.2899179E+002, 8.5572592E-001
 1.0056212E+000, 9.2899179E+002, 8.5572592E-001
```
I think we're good.

**Comment by marcosvanella** [comment]
Closing this. Test runs correctly now.
