### ISSUE TITLE
QUANTITY 'RTE SOURCE CORRECTION FACTOR' not documented in user guide

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12671]
We have a device parameter 'RTE SOURCE CORRECTION FACTOR' which can be used to output C from the RTE equation. The quantity is available and seems to be working. I thought this was documented in an old version of the user guide but I do not see it in the 6.9.0 documentation. Am I missing it somewhere or do we need to add it?

**Comment by mcgratta** [comment]
Yes, add it and point to 

14.1.3 Radiation Option 3. Optically-Thick; Specified Radiative Fraction (LES Default)

**Comment by johodges** [comment]
Fixed in https://github.com/firemodels/fds/pull/12672. The other edit in the PR was a fix for a build error in the guide from a commit earlier today.
