### ISSUE TITLE
SIMULATION ERROR MPI

### ISSUE THREAD

**Issue by CarloPollo** [firemodels/fds#12683]
Good morning,

I have a problem with a new PC purchased for simulations.
I have a workstation, where i installed FDS with two computers's access. if i start the simulation with more than 7 meshes, FDS gives me an error (Log file attached). I don't understand if it is an error from FDS or from pyrosim (which I have already requested assistance from thundehead but they are unable to help me).

Do you kindly know how I could solve it?
Thank you in advance as always for the availability
 
original discussion on google groups:  
[log.txt](https://github.com/firemodels/fds/files/14755201/log.txt)
https://groups.google.com/u/2/g/fds-smv/c/NtMEFgKUmMU

Regards
Carlo

**Comment by mcgratta** [comment]
Can you run a job that requires, say, 5 meshes?

**Comment by CarloPollo** [comment]
I can run simulations up to 7 meshes. 

Beyond seven meshes the simulation does not work

I attach the details of the CPU
![cpu](https://github.com/firemodels/fds/assets/164619172/3d1fea53-f80d-4786-b9f9-2acaad50c745)

**Comment by mcgratta** [comment]
What happens if you open up a command prompt and type
```
mpiexec -n 10 hostname
```

**Comment by CarloPollo** [comment]
Hi Kevin, thanks for responding. 

I tried to execute the command you suggested but without success.  

The Hostname I believe is PC-VVF so I entered the following command `mpiexec -n 10 PC-VVF`
I got the attached error message 
![CMDfds](https://github.com/firemodels/fds/assets/164619172/56f95444-e6a7-412d-abb0-376fbd53de0d)

Maybe the hostname is wrong?
How can I be sure that it is PC-VVF?

**Comment by mcgratta** [comment]
No, I literally mean for you to enter this command
```
mpiexec -n 10 hostname
```

**Comment by mcgratta** [comment]
![image](https://github.com/firemodels/fds/assets/11333911/2228e1c7-d445-4ddf-8ed4-de9125bdc5a6)

**Comment by CarloPollo** [comment]
I tried again following your last advice, the command is accepted only that I still cannot run simulation with more than 7 meshes...
![CMDfds-10 cores](https://github.com/firemodels/fds/assets/164619172/f8c31dd2-3129-4935-89c7-49889fabc6ce)

I attach the new log file if it would be helpful
[log-10cores.txt](https://github.com/firemodels/fds/files/14801393/log-10cores.txt)

**Comment by CarloPollo** [comment]
yes, not whether to say unfortunately or fortunately but on other PCs I can run the case correctly. 
The problem is related to the PC I am using, I was hoping though that it was a "known" problem with a solution already indicated.  

I thank you anyway for the assistance, if I can use all the meshes I will post the solution here so that it will be of support to other users. 

Thank you

**Comment by mcgratta** [comment]
The known problem is that Windows is not designed for high performance computing. Is the problem computer running a different version of Windows?

**Comment by CarloPollo** [comment]
At the moment, unfortunately, I do not have access to the PC to verify the actual windows version. However, it should be a windows server license, in fact the softwares, such as FDS, is installed on the PC-server and is visible from all PCs accessing remotely. 

As soon as I have access to the PC I will be sure to update the post.

**Comment by mcgratta** [comment]
What would happen if you installed FDS directly on the computer with 48 cores?

**Comment by CarloPollo** [comment]
All programs, including FDS and Pyrosim which I use as a pre-processor, are installed on the "mother" machine called PC-VVF. I don't have physical access to the machine except remotely through my PC. All programs however are installed on the PC with 48 cores

**Comment by mcgratta** [comment]
You say that all programs are installed on the server (mother) machine and also that all programs are installed on the PC. Is it possible that there is a conflict with the libraries. Do you know which version of FDS you are running --- the one on the mother machine or the one on the PC?

**Comment by AbdelMoumene01** [comment]
Hii 
I have this problem 

MPI Enabled; Number of MPI Processes;1
openMP Disabled

**Comment by AbdelMoumene01** [comment]
![20240405_113441](https://github.com/firemodels/fds/assets/157164956/1dd61a35-bf63-4230-af26-ade7b16f2f0f)

**Comment by rmcdermo** [comment]
This is not a problem.  If you want OpenMP enabled, you need to run the OpenMP executable.  See the user guide.

**Comment by AbdelMoumene01** [comment]
Does FDS automatically determine the number of processes, or should I select the number? 
I have one PC with an i5 8th generation processor (4 threads) and 20GB of RAM. 
How can I confirm the program is running properly? I noticed that to view the Smokeview model, I have to open a new command window and enter "smokeview" not "smv" to select the SMV file. Is this an issue?

**Comment by AbdelMoumene01** [comment]
How can i run MPI and openMP

**Comment by mcgratta** [comment]
That's why we wrote a User's Guide. If you have questions about the instructions, you can ask them here.

**Comment by AbdelMoumene01** [comment]
I don't understand where to put the instructions about MPI or OpenMP. Also, could you please give me the steps to install FDS correctly because I didn't change any files

**Comment by drjfloyd** [comment]
![image](https://github.com/firemodels/fds/assets/12799217/7ba88fea-ad83-4b93-97c3-9a095abda039)

**Comment by CarloPollo** [comment]
@mcgratta Thanks for the support Kevin. I will try to solve it on my self. You have been kind in helping me. Thank you again.

**Comment by AbdelMoumene01** [comment]
im trying to simulate a fire on top of a cylindrical obstacle with HRRPUA=200,
ineed some help pls
&SURF ID='TK_Gasoline_01', COLOR='SKY BLUE'/
&MULT ID='cube array_1', DX=1,DY=1,DZ=1, I_UPPER=16,J_UPPER=16,K_UPPER=8/
&OBST XB= 8,9,12,13,0,8,SURF_ID='HOT',
MULT_ID='cube array_1'
SURF_ID='TK_Gasoline_01'
SHAPE='CYLINDER'
RADIUS=8
HEIGHT=8
XYZ=16,20,0
ORIENTATION=0,0,1/

**Comment by drjfloyd** [comment]
@AbdelMoumene01  It is not appropriate to spam every open discussion with your post. If you continue you will be blocked. read the effective posting thread. ()https://github.com/firemodels/fds/discussions/12448). Also read the users manual.  You were told in your orignal post that the answee you seek is in the user's manual. The hint was even given to you that it is an input for obstructions.  This forum is not an online user's.  You need to take the time to read the manuals and learn FDS.

**Comment by AbdelMoumene01** [comment]
I hope this message finds you well. I apologize for any inconvenience, but I am encountering an issue while attempting to create multiple cylinders within a single domain for simulation purposes. I have referred to the example of a circular burner in the user manual and attempted to replicate a similar scenario by placing the fire at the top of the cylinder. Despite carefully specifying all required parameters, I am unable to observe the red surface indicating the fire, even after trying a rectangular surface on top of the cylinder. I understand that this forum is not an online user manual, and I apologize for any inconvenience caused. I am simply seeking assistance in identifying the last parameter necessary to initiate a simulation. I have deleted all previous messages and would appreciate guidance on pinpointing the issue within my input. Unfortunately, I am pressed for time and unable to thoroughly review all sections of the user manual. Could you please provide insight into what might be wrong with my input? Below is the input I am using: 
&SURF ID='TK_Gasoline_01', COLOR='SKY BLUE'/
&MULT ID='cube array_1', DX=1,DY=1,DZ=1, I_UPPER=16,J_UPPER=16,K_UPPER=8/
&OBST XB= 8,9,12,13,0,8,SURF_ID='HOT', 
      MULT_ID='cube array_1'
      SURF_ID='TK_Gasoline_01'
      SHAPE='CYLINDER'
      RADIUS=8
      HEIGHT=8    
      XYZ=16,20,0
      ORIENTATION=0,0,1/                                                    /bac essence sans plamb 01 /                                                                                                     &SURF ID='BURNER',COLOR='RED', HRRPUA=200 /
&REAC FUEL='Gasoline', C=8, H=18, O=0, N=0, CO_YIELD=0.01, SOOT_YIELD=0.01 /
&VENT XB=8,24,12,28,8,8, XYZ=16,20,8, RADIUS=8, COLOR='RED', SURF_ID='BURNER' /
Thank you very much for your valuable assistance.
