### ISSUE TITLE
Ghost cells not filled for kappa

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12680]
**Describe the bug**
Node slices show a kappa of zero at mesh boundaries. See attached input file.
[wasson_test1_jet_025mm.txt](https://github.com/firemodels/fds/files/14745797/wasson_test1_jet_025mm.txt)

**To Reproduce**
1. Run attached case
2. Load 3-D slice of kappa
3. Move slice to centerline

**Expected behavior**
Expect to see continuous values at the mesh boundaries

**Screenshots**
![image](https://github.com/firemodels/fds/assets/17127980/0d0220ea-82be-4cbf-8547-9f074b45689a)

**Desktop (please complete the following information):**
 - OS: centos6 (fds run) windows10 (smv visualization)
 - Version: FDS-6.9.0-0-g6339569-release

**Comment by rmcdermo** [comment]
Thanks, we'll take a look.

**Comment by rmcdermo** [comment]
Should be fixed with PR #12681

**Comment by johodges** [comment]
I can confirm that the ghost cells are filled now. I am seeing some pretty significant mesh artifacts. This may be related to the kappa hack that we were trying out earlier today, but it would be odd to me that it would affect the mesh boundaries like this. I can try without the hack on latest master tomorrow to check.

![image](https://github.com/firemodels/fds/assets/17127980/fb4c1388-c973-442e-963b-aa1c20ab9e3e)

**Comment by rmcdermo** [comment]
We do not exchange the ghost values, so this is just how it is when using the interpolated data.  Use CELL_CENTERED if you want to see the raw data.
