### ISSUE TITLE
Crash in particle injection with multiple meshes on latest master

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12714]
**Describe the bug**
I have been using a simple modification of the Sprinklers_and_Sprays/cascade verification case where I split the mesh into 4 parts to test the vtk functionality. The case now crashes after I sync'd my fork this morning, and I verified that the crash also occurs on the latest master. The crash occurs with the multiple meshes whether or not the case is run with mpi. The error I am seeing with openmp_gnu_linux_db is:

At line 1703 of file ../../Source/part.f90
Fortran runtime error: Index '-1' of dimension 1 of array 'rdx' below lower bound of 0

**To Reproduce**
1. Download attached input file
2. Run case
3. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: [e.g. 22]

**Additional context**
[cascadempi.txt](https://github.com/firemodels/fds/files/14812108/cascadempi.txt)

**Comment by rmcdermo** [comment]
OK, the case fails with 6.9.0 as well, but works with 6.8.0.  I'll bisect.

**Comment by ericvmueller** [comment]
If I had to guess, looks like when I added 
https://github.com/firemodels/fds/blob/c506bd1e02243088e19093017e26110e513f4207/Source/part.f90#L1702-L1707
I didnt account for sprinkler particles which can be added immediately into a different mesh and therefore the call to `INITIALIZE_SINGLE_PARTICLE` is done without knowing the grid location of the new particle on the other mesh:
https://github.com/firemodels/fds/blob/c506bd1e02243088e19093017e26110e513f4207/Source/part.f90#L523-L541

I cant really look into this today but the fix may be to skip the initialization of `LP%RVC` for particles outside the current mesh, and then make sure it is set at the _beginning_ of `MOVE_PARTICLES` as well as/instead of the end. Unless maybe @drjfloyd or someone has a better idea

**Comment by rmcdermo** [comment]
Yep... good guess.
```
69cf69cda31be7e9bc2717126f678e3fb75c2722 is the first bad commit
commit 69cf69cda31be7e9bc2717126f678e3fb75c2722
Author: ericvmueller <ericvmueller@gmail.com>
Date:   Tue Aug 15 11:26:10 2023 -0400

    FDS Source: replace RVC with LP%RVC for particles and update in MOVE_PARTICLES. Scale initial LP%PWT according to XB-cutcell intersection volume where needed.
```

**Comment by johodges** [comment]
Thanks guys. It is not holding me up right now since I am focused on other parts of the analysis, but I wanted to get the issue in the queue.

**Comment by ericvmueller** [comment]
Okay - thanks for catching it @johodges. Other than skipping the initialization of LP%RVC outside of the mesh, the better fix might actually be to update the value as soon as the particle is unpacked in the new mesh. I will test some things out as soon as I can.

**Comment by ericvmueller** [comment]
Right, I think I have a fix. But I want to check with Marcos about making sure the cut cell implementation is robust. If you want something to try before then, I put it here https://github.com/ericvmueller/fds/tree/lprvc.

**Comment by rmcdermo** [comment]
@johodges How niche is this case?  Is this something we need to issue a maintenance release for asap?  If so, we all need to focus on getting this sorted and get bundles ready before the end of the week.  Thanks

**Comment by johodges** [comment]
I do not think it is very niche. It looks to me like any sprinkler case with GEOM and multiple meshes will fail, but @ericvmueller may know better since he was working on the fix. I can try a few of the other sprinkler cases to see if they crash in a similar way.

**Comment by ericvmueller** [comment]
Certainly worth getting a fix out there, in my opinion. Firebot is running now. If you have other cases for me to test, let me know.

**Comment by johodges** [comment]
I can confirm the latest master now works with my test case. I will get it added as a verification case for the future and close out this issue once the PR is in.

**Comment by johodges** [comment]
This works with Eric's changes and the verification case passed firebot on master last night. Closing the issue out.
