### ISSUE TITLE
Different particle movement along solid surfaces between OBST and GEOM

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12729]
**Describe the bug**
I am adding a verification case for multiple meshes with particles crossing mesh boundaries in the gas phase and solid phase. The case is based on Sprinklers_and_Sprays\cascade.fds. The boxes are reproduced into 4 separate mesh regions. The first meshed region uses OBST definitions for the boxes with a single mesh. The second region replaces the OBST definition with a GEOM definition. The third and fourth region use the same geometry but separate the region into 2 meshes. The particles in the OBST cases remain attached to the box and slide down the sides once they reach the edge. However, the particles in the GEOM case do not remain attached to the box and are ejected into the gas phase. This leads to a different profile in the accumulated mass at the base of the mesh with time.

**To Reproduce**
1. Run attached case
2. See error

**Expected behavior**
Similar behavior between GEOM and OBST configurations.

**Screenshots**
![image](https://github.com/firemodels/fds/assets/17127980/3efe1f28-43aa-4df0-857b-5a16374129dc)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: [e.g. 22]

**Additional context**

[cascadempi.txt](https://github.com/firemodels/fds/files/14841071/cascadempi.txt)

**Comment by johodges** [comment]
Is this issue showing up for the team now?

**Comment by marcosvanella** [comment]
I can see it, had to go back to github and then to firemodels. I'll look into this. Seems to be that droplets become detached from solid instead of going around the corner and maintaining the vertical velocity specified for the solid.

**Comment by ericvmueller** [comment]
In addition to the solid adhesion, there's also an issue of `BC%IOR` for some of the particles not starting at zero, causing them to fly off, which @mcgratta is looking into

![image](https://github.com/firemodels/fds/assets/13366803/f13eb4b4-4ae0-465a-8042-65d4e4e6a33e)

**Comment by johodges** [comment]
Thanks for the update. I have firebot running on our cluster with the new verification case added (mainly to check and make sure I didn't forget to commit anything). I'll plan to put in a PR on it in the morning unless you guys want it to run through your firebot tonight at 10.

**Comment by rmcdermo** [comment]
@johodges we need to get the bugs worked out before we commit the verification case.  Hang on and we'll let you know.  Thanks

**Comment by mcgratta** [comment]
I have not fixed the bug related to the spurious particles.

**Comment by marcosvanella** [comment]
Same here
________________________________

**Comment by mcgratta** [comment]
I hopefully fixed the spurious behavior of the droplets at the sprinkler head. The parameter `BC%IOR` was not being reset to zero when a new droplet occupied a previously used slot in `BOUNDARY_COORD`.

**Comment by ericvmueller** [comment]
Is this something that could be an issue for solid particles also (as in, we should set it in `INITIALIZE_SINGLE_PARTICLE` or somewhere that gets used for all particle types)?

**Comment by mcgratta** [comment]
My change only affects spray droplets. I'll check others types of inserts.

**Comment by johodges** [comment]
I was thinking a bit about the verification case earlier. Currently, the GEOM case still passes firebot because the only points which are compared in the cascade "ideal" are the two points near the end at ~90-100 seconds. I can add a few points along the spline based on what is predicted in the OBST case. This would cause the case to fail if there is an unintentional change affecting droplet movement, but the added points are not really an ideal or ground truth values. This would be similar in concept to Section 8.7 "Spurious Obstruction Effects (hole)". Thoughts?

**Comment by mcgratta** [comment]
That's fine. Just call it "Expected" or something like that to indicate that it is not an analytical solution.

**Comment by johodges** [comment]
Sounds good. I have it checking the area under the 4 curves now.

![image](https://github.com/firemodels/fds/assets/17127980/17d39012-5d31-4eb0-9190-5d17b8490c1c)

![image](https://github.com/firemodels/fds/assets/17127980/a1fcd842-57aa-4460-a842-23c8f5aef66f)

**Comment by johodges** [comment]
The fix Marcos just pushed in https://github.com/firemodels/fds/pull/12742 fixed the issue for single mesh GEOM and reduced the issue with multi-mesh GEOM. However, still some difference between multi-mesh GEOM and the other 3 cases.

![image](https://github.com/firemodels/fds/assets/17127980/9f125ed0-75c7-4187-a2a8-9b685b2866fa)

**Comment by marcosvanella** [comment]
Yep, need to work on exchanging info for particles attached to cfaces among meshes. Right now attached particles moving under boxes are set free when crossing meshes and fall. On Apr 3, 2024 8:50 PM, johodges ***@***.***> wrote:
The fix Marcos just pushed in #12742 fixed the issue for single mesh GEOM and reduced the issue with multi-mesh GEOM. However, still some difference between multi-mesh GEOM and the other 3 cases.
image.png (view on web)

**Comment by johodges** [comment]
Looks good with Marcos' most recent change.

![image](https://github.com/firemodels/fds/assets/17127980/c1d2c712-2fb9-49c9-830d-cec062aa2d0b)

**Comment by marcosvanella** [comment]
Nice, let's see what firebot says tonight. Do you want to add the case to the repo?On Apr 4, 2024 5:56 PM, johodges ***@***.***> wrote:
Looks good with Marcos' most recent change.
image.png (view on web)

**Comment by johodges** [comment]
The verification case passed last night with the 4 permutations of single/multi mesh and OBST/GEOM. Are there any outstanding issues on this before we close it out?

**Comment by marcosvanella** [comment]
Things for the case look correct in the guides?If so go ahead and close it.On Apr 5, 2024 7:14 AM, johodges ***@***.***> wrote:
The verification case passed last night with the 4 permutations of single/multi mesh and OBST/GEOM. Are there any outstanding issues on this before we close it out?
