### ISSUE TITLE
Ingition via heat flux

### ISSUE THREAD

**Issue by Jostorrr** [firemodels/fds#12735]
Hello,

The commun way to simulate the spread of a fire is via the ignition temperature. However, I am currently working on an ignition via heat flux : when an OBST is exposed to a certain heat flux, it starts to burn. I managed to make it work with a small model however the simulation is always stopping because of a pressure-iteration problem.
Has anyone already done this type of fire spread and has some kind of way to simulate it ?

Thanks

**Comment by rmcdermo** [comment]
If there is a simple input file that demonstrates the issue, please post it.

**Comment by mcgratta** [comment]
Closing because there is no response.
