### ISSUE TITLE
Spark ignition error using AUTO_IGNITION_TEMPERATURE

### ISSUE THREAD

**Issue by xixiuqi** [firemodels/fds#12747]
**Describe the bug**
When I use a spark ignition configuration with AUTO_IGNITION_TEMPERATURE as described in 13.1.7 in User guide, the simulation is terminated with the error **forrtl: severe (157): Program Exception - access violation**. 

**To Reproduce**
I attach the input file. The simulation has a cylinder, and a fixed mass loss rate is applied on the surface of the cylinder. The spark is activated at 1 s. As long as the spark is activated, the simulation is terminated. 

**Expected behavior**
From 13.1.7 in User guide, as the spark is activated, the AUTO_IGNITION_TEMPERATURE at the cell where spark locates will change to 0 K and chemical reactions happen, and then flame propagates like pilot ignition. 

**Screenshots**
Here is the error that I got. 

![image](https://github.com/firemodels/fds/assets/162371714/0e3438b6-ceef-4f56-8ea6-8f6539187960)

**Desktop (please complete the following information):**
 - OS: Windows*
 - Version: FDS-6.8.0-0-g886e009-release

**Additional context**
Here is the input file. I also change the mesh sizes as double and triple as listed below and the error still exist.

&HEAD CHID='auto_ignition', TITLE='auto ignition pool fire' /

&MESH IJK=160,160,96, XB=-0.25,0.25,-0.25,0.25,0.2,0.5 /

&TIME T_END=100 / 

&REAC ID ='R1', 
	FUEL='METHANOL', 
	AUTO_IGNITION_TEMPERATURE=540/

&PROP ID='spark', SPARK=T /
&DEVC ID='spark-1', XYZ=0,0,0.26, QUANTITY='TIME', SETPOINT=1, PROP_ID='spark' /

&DUMP HRR_GAS_ONLY = T/

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='OPEN' /

&SURF ID='burner',
       MLRPUA=0.005/

&GEOM ID='cylinder', SURF_IDS='burner','INERT','INERT',
              CYLINDER_LENGTH=0.1,
              CYLINDER_RADIUS=0.073,
              CYLINDER_ORIGIN=0,0,0.2,
              CYLINDER_AXIS=0.,0.,1.,
              CYLINDER_NSEG_AXIS=6,
              CYLINDER_NSEG_THETA=48 /

&SLCF PBY=0., QUANTITY='RADIATION LOSS', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='INTEGRATED INTENSITY', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='MASS FRACTION',SPEC_ID = 'METHANOL', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='MASS FRACTION',SPEC_ID = 'OXYGEN', CELL_CENTERED=.TRUE. /
&SLCF PBY=0., QUANTITY='HRRPUV', CELL_CENTERED=.TRUE. /

**Comment by mcgratta** [comment]
I will run the case with the latest version of FDS, 6.9.0. I suggest you do the same.

**Comment by marcosvanella** [comment]
@xixiuqi I suggest you split your domain in several meshes. You have a single mesh with 2.5 million cells now.
When you invoke &GEOM a direct LU solver (ULMAT) is used in the unstructured grid resulting in a lot of memory being used in this case. Think of having ~50^3 cells per mesh.

**Comment by xixiuqi** [comment]
@mcgratta I just finished running the case with a larger mesh size with FDS 6.9.0 and the error still exists.

**Comment by xixiuqi** [comment]
@marcosvanella Thanks for your suggestions! I will split the domain and change the cylinder to a cube and see what will happen. Also I tried different mesh sizes for mesh independency and the error still exists.

**Comment by marcosvanella** [comment]
Here is a smaller case that shows the segfault with latest code. It has to do with the spark and geom. Not clear why, the spark is well placed in the gasphase.

[auto_ignitionb.txt](https://github.com/firemodels/fds/files/14878586/auto_ignitionb.txt)

**Comment by marcosvanella** [comment]
@mcgratta looks like IIC,JJC,KKC (cells indexes) are defined as optional in COMBUSTION_MODEL, then in there when testing for SUPPRESSION a call to 
CALL CHECK_AUTO_IGNITION(EXTINCT,TMP_IN,RN%AUTO_IGNITION_TEMPERATURE,IIC,JJC,KKC,NR)

Is done. IIC,JJC,KKC are not set to optional in CHECK_AUTO_IGNITION and used in a position test. For cut-cells we are not currently sending in the I,J,K of the Cartesian cell we have (probably the reason for the OPTIONAL in the call to COMBUSTION_MODEL). This leads to the error seen here it seems.
I suggest to send these vars in for cut-cells as we have a single cut-cell per cartesian cell. Testing this now.

Regardless, if we keep the optional argument for IIC,JJC,KKC, I think we should do some kind of test before calling CHECK_AUTO_IGNITION.

**Comment by marcosvanella** [comment]
@xixiuqi thanks for reporting this. The bug fix for this issue will be in the next maintenance release to come out early next week.

**Comment by xixiuqi** [comment]
@marcosvanella @mcgratta Thanks so much for your suggestions. They are very helpful!
