### ISSUE TITLE
Averaging SLCF contour data 

### ISSUE THREAD

**Issue by AlanZandie** [firemodels/fds#12751]
Good day,

I need to get the average velocity contour at a particular height across a car park from 200s to 300s, meaning I need to output averaged values rather than instantaneous data. Normally you can do that with DEVC using the STATISTICS_START/STATISTICS_END option, but it does not work on SLCF which makes sense because they are an array of floating points. Could you please help me if you know a way to do so?
P.S: I need the SLCF to be averaged because I need the cell-centred values, so I cannot go for other options like using DEVC. 
thank you

**Comment by Er9y714** [comment]
You can do this in smokeview. But I do not know if you can output the date to csv like you do with regular slice files. 

Load the slice file you want. Set the value you see in the box below to 100s, click reload and move the timeline to 300s. This will give you the averaged values between 200s and 300s. 

![image](https://github.com/firemodels/fds/assets/26166281/09ceff3a-292a-4be0-9802-ac4d918cffeb)

**Comment by drjfloyd** [comment]
Also:
there is the fds2ascii tool installed with FDS.
In the fds repo under Utilities there are matlab and python scripts (slread) for reading slice files.
There is also this repo of tools: https://github.com/johodges/pyfdstools

**Comment by AlanZandie** [comment]
Thank you both,
I tried it @Er9y714 but it seems it does not output the data. plus, I am currently using 'fdsreader' which helps post-process the outputs, but while I save the SLCF for each second, I don't know how to average the data of all the saved SLCF. I've attached of there codes I'm using to retrieve the contours at t=300s. Could you please let me know if you have any ideas?
![Screenshot (3227)](https://github.com/firemodels/fds/assets/93418696/59e0c974-d665-4486-95be-94459967bf0a)

**Comment by Er9y714** [comment]
@AlanZandie sorry I do not have experience with _fdsreader_.

**Comment by gforney** [comment]
If you want to use smokeview to output averaged slice data.
1. open the Average data panel of the Slice dialog box.  Click on Average slice data, select the time interval you want and reload the data
![slice_average](https://github.com/firemodels/fds/assets/12403014/144e2117-356b-4ee3-ab72-eda74e5e74db)
2.  to output the average slice data.  click on the Settings panel of the Slice dialog box and click on the Output data checkbox.  Then select the desired time and press the r key.  smokeview will then output a png image of the current scene and a csv file of the slice data.  smokeview outputs one csv file for each mesh that the slice intersects with.  If you think the data is not averaged then post a simple test case and what time step you output the data for and what data you were expecting
![output_slice_data](https://github.com/firemodels/fds/assets/12403014/607d4e89-2159-4e95-bb9b-e65760ed87f2)

**Comment by johodges** [comment]
You can use the scripting option in smokeview to render the average outputs. You could then use smokeview within your wrapper rather than fdsreader.

**Comment by gforney** [comment]
the latest smokeview, version 6.9.1, has script keywords for averaging slice data and output slice data to a spreadsheet file.  update your smv repo and look at smv/Verification/Visualization/plume_average.ssf for an example script (along with the plume_average.fds input file)
