### ISSUE TITLE
Bug in particle movement along solid surfaces 

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#12752]
**Describe the bug**
The attached case has some odd behavior with GEOM and particles. Some of the particles are moving horizontally after passing off the tilted box.

**Screenshots**

![image](https://github.com/firemodels/fds/assets/17127980/f714fe9e-8dcb-4e98-9ab1-015302debc0f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: [e.g. 22]

**Additional context**
[cascadesingle.txt](https://github.com/firemodels/fds/files/14886462/cascadesingle.txt)

**Comment by marcosvanella** [comment]
Thanks Jon! I'll look into it.

**Comment by marcosvanella** [comment]
Jon, do a repo update and try the case again. Thanks.

**Comment by marcosvanella** [comment]
Closing.
