### ISSUE TITLE
External control  Volume Flow

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#12780]
**Which new feature are you testing?**
External control of volume flow rate ramp. I followed the User Guide Section 18.8 External Control. 

**Describe your experience**

I modelled a supply vent. I expect it to start with 5 m3/s, then at 5 s, the external file should be read and the volume flow rate should go up to 10 m3/s. 

I observe the volume flow rate stays at 5 m3/s and it ignores the external input file. 

Could you please have a look at the case? Thanks.

```

&HEAD CHID='External_control'/
&TIME T_END=10.0, DT_EXTERNAL=5.0/
&DUMP DT_DEVC=.5  /

&MISC EXTERNAL_FILENAME='external_test_input.csv'/


&MESH ID='Mesh', IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0/
&VENT ID='supply', SURF_ID='supply', XB=0.0,0.0,0.0,1.0,0.0,1.0/ 
&SURF ID='supply',      RGB=26,204,26,	  VOLUME_FLOW=1.0 RAMP_V='Ramp_supply' /
&RAMP ID='Ramp_supply' EXTERNAL_FILE=T, INITIAL_VALUE=5.0/


&VENT ID='OpenVent', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 



&DEVC ID='FLOW', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=0.0,0.0,0.0,1.0,0.0,1.0/

&SLCF QUANTITY='VELOCITY', ID='Slice', PBZ=0.5/

&TAIL /

```

External input file
[external_test_input.csv](https://github.com/firemodels/fds/files/14958870/external_test_input.csv)

**Comment by drjfloyd** [comment]
You have some strange formatting in your csv file. There is a couple of bytes of nonsense at the start which is getting read as part of the RAMP keyword.

C:\Projects\FDS_test>type external_test_input.csv
∩╗┐RAMP,"Ramp_supply",10.0

**Comment by drjfloyd** [comment]
If you are using Excel to make the csv file you want to save as just plain csv:

![image](https://github.com/firemodels/fds/assets/12799217/a63adef0-5427-45d4-b895-7b544bd8fa5d)

**Comment by Er9y714** [comment]
That is a good point. Thank you for pointing this out. I fixed it and it worked on my end too. 
I have a followup case, therefore i did not create a new issue but continue from here. Could you please have a look?


I added a RAMP_SLCF input to the Dump line and did corresponding edits, as well as the input to the csv file. However I do not see any slicefile output on smokeview. 

Also please note that the yellow box and misaligned purple line look unusual to me.

[external_test_input.csv](https://github.com/firemodels/fds/files/14962843/external_test_input.csv)

```
&HEAD CHID='External_control'/
&TIME T_END=10.0, DT_EXTERNAL=5.0/
&DUMP DT_DEVC=.5 RAMP_SLCF='Ramp_slcf' /

&MISC EXTERNAL_FILENAME='external_test_input.csv'/


&MESH ID='Mesh', IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0/
&VENT ID='supply', SURF_ID='supply', XB=0.0,0.0,0.0,1.0,0.0,1.0/ 
&SURF ID='supply',      RGB=26,204,26,	  VOLUME_FLOW=1.0 RAMP_V='Ramp_supply' /
&RAMP ID='Ramp_supply' EXTERNAL_FILE=T, INITIAL_VALUE=5.0/
&RAMP ID='Ramp_slcf' EXTERNAL_FILE=T, INITIAL_VALUE=1.0/


&VENT ID='OpenVent', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 



&DEVC ID='FLOW', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=0.0,0.0,0.0,1.0,0.0,1.0/

&SLCF QUANTITY='VELOCITY', ID='Slice', PBZ=0.5/

&TAIL /
```


![image](https://github.com/firemodels/fds/assets/26166281/8be2d3e3-bc09-4281-a37d-8c4eb685bc30)

**Comment by drjfloyd** [comment]
can you open this as a new issue since this is something with slice files and not external control.
