### ISSUE TITLE
failure of zone check

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#12781]
This case fails with a zone check error message. If I move the XYZ for the zone off the mesh boundary it works. This was a case which was at a lower resolution and halved the resolution which inadvertently put the XYZ at a mesh boundary. If I move to Z=1.4 it passes.  

&HEAD CHID='zone_fail'/
&TIME T_END=1/

&MESH ID='Mesh_large1', IJK=30,32,30, XB=1.8,3.3,3.5,5.1,0.0,1.5,MULT_ID='M1'/
&MULT ID='M1',DX=1.5,I_UPPER=5,DY=1.6,J_UPPER=1,DZ=1.5,K_UPPER=1/
&MESH ID='Mesh_large4', IJK=30,31,30, XB=1.8,3.3,6.7,8.25,0.0,1.5,MULT_ID='M2'/
&MULT ID='M2',DX=1.5,I_UPPER=5,DY=1.55,J_UPPER=1,DZ=1.5,K_UPPER=1/

&ZONE ID='Zone-large_room', XYZ=5.0,6.0,1.5, LEAK_AREA(0)=5.42E-03, LEAK_REFERENCE_PRESSURE=50, LEAK_PRESSURE_EXPONENT=0.749/

**Comment by mcgratta** [comment]
The case as written works for me. Is this the good case or bad case?

**Comment by drjfloyd** [comment]
bad case.  This didn't work for me either with linux or windows.  I'll rebuild and make sure I didn't have a bad build.

**Comment by drjfloyd** [comment]
compiled with current in debug and get:

 Starting FDS ...

 MPI Process      0 started on pele-01

 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : April 12, 2024  16:17:07
 Revision         : FDS-6.9.0-128-gf8ab9f4-master
 Revision Date    : Fri Apr 12 15:33:36 2024 -0400
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for applicatio                                                                                                     ns running on Intel(R) 64, Version 2021.11.1 Build 20231117_000000
 Compilation Date : Apr 12, 2024 15:57:31

 Number of MPI Processes:  1

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.11 for Linux* OS


 Job TITLE        :
 Job ID string    : zone_fail

forrtl: severe (408): fort: (2): Subscript #3 of the array CELL_INDEX has value                                                                                                      32 which is greater than the upper bound of 31

Image              PC                Routine            Line        Source                                                                                                           
fds_impi_intel_li  000000000062B53A  geometry_function        2625  func.f90
fds_impi_intel_li  000000000425436D  fds_IP_initialize        2358  main.f90
fds_impi_intel_li  00000000041CB7DF  MAIN__                    241  main.f90
fds_impi_intel_li  0000000000407B1D  Unknown               Unknown  Unknown
libc.so.6          000014D71263FEB0  Unknown               Unknown  Unknown
libc.so.6          000014D71263FF60  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000407A35  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
This is a less than / less than or equal thing where the wrong cell is chosen for a point sitting on the fence. I'll fix.

**Comment by drjfloyd** [comment]
Works.
