### ISSUE TITLE
Simple chem treated as finite rate

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#12788]
@drjfloyd Looks like we need to clean up some logic in read after the chem commit.  I picked one of the simple cases to run, `fds/Verification/Fires/fire_const_gamma.fds` and I get this:

```
ERROR(XXX): REAC 1. Tracked species AIR used in a finite rate reaction without N_S defined is not a primitive species. (CHID: fire_const_gamma)
```

**Comment by drjfloyd** [comment]
I have for now just commented out the error check.

**Comment by drjfloyd** [comment]
I think I have fixed this. We only need to go into that block of code for finite rate reactions. We also only only need to do the error check if the lumped species is a reactant (which includes products when REVERSE is TRUE).
