### ISSUE TITLE
External control  RAMP_SLCF

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#12785]
**Which new feature are you testing?**
External control and RAMP_SLCF

**Describe your experience**

I tried using external control function on the RAMP_SLCF feature. Although the case runs, I do not get the expected outcome.

I added a RAMP_SLCF input to the Dump line and did corresponding edits, as well as the input to the csv file. However I do not see any slicefile output on smokeview.  

Also please note that the yellow box and misaligned purple line look unusual to me.

Thank you for checking.
 
[external_test_input.csv](https://github.com/firemodels/fds/files/14963343/external_test_input.csv)

```
&HEAD CHID='External_control'/
&TIME T_END=10.0, DT_EXTERNAL=5.0/
&DUMP DT_DEVC=.5 RAMP_SLCF='Ramp_slcf' /

&MISC EXTERNAL_FILENAME='external_test_input.csv'/


&MESH ID='Mesh', IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0/
&VENT ID='supply', SURF_ID='supply', XB=0.0,0.0,0.0,1.0,0.0,1.0/ 
&SURF ID='supply',      RGB=26,204,26,	  VOLUME_FLOW=1.0  / 
&RAMP ID='Ramp_slcf' EXTERNAL_FILE=T, INITIAL_VALUE=1.0/


&VENT ID='OpenVent', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0/ 



&DEVC ID='FLOW', QUANTITY='NORMAL VELOCITY', SPATIAL_STATISTIC='SURFACE INTEGRAL', XB=0.0,0.0,0.0,1.0,0.0,1.0/

&SLCF QUANTITY='VELOCITY', ID='Slice', PBZ=0.5/

&TAIL /

```

![image](https://github.com/firemodels/fds/assets/26166281/8be2d3e3-bc09-4281-a37d-8c4eb685bc30)

**Comment by drjfloyd** [comment]
@mcgratta 
The various output ramps don't use the normal ramp logic. They are only evaluated using the T,F inputs, and the clocks are setup before timestepping begins. There isn't a means for an external ramp to control these outputs. Do we want to rework this logic?

**Comment by Er9y714** [comment]
For information, this issue report did not originate from a need. I simply posted this because I found a case which would not work in a beta feature.

**Comment by drjfloyd** [comment]
@Er9y714 we appreciate you testing this feature.

**Comment by mcgratta** [comment]
I would not want to add this functionality unless there is a compelling need. Let's flag it with an error for now.

**Comment by drjfloyd** [comment]
OK. Can do that and edit the Guide to note this.

**Comment by drjfloyd** [comment]
Added an error message for this.
