### ISSUE TITLE
Numerical Instability/segemntation error with Burn-Away Features in FDS

### ISSUE THREAD

**Issue by BastianStahra** [firemodels/fds#12795]
**Describe the bug**
I modelled a balcony with burnable objects.

Objects start to burn at an ignition temperature. After the fuel is exhausted the object burns away.

Numerical instability and segmentation errors appear after about 220s.

This happens when the objects are modelled through all meshes. 

When you apply a hole at the boundary of a mesh, so that the burnable objects don't go through the meshes the numerical instablity and segmentation errors don't appear. 

The balconies burn as they should. 

**To Reproduce**

1. Take the model "BurnAway-BA0016" and run it until around 250s --> error should occur
2.  Take the model "BurnAway-BA0020" and run it until 3600. --> nor error occurs and objects burn away completely

**Expected behavior**
I expect the balcony to burn away completely without errors even though objects are modelled through many meshes.

**Screenshots**
see FDS-Files

**Desktop (please complete the following information):**

FDS/6.8.0_IntelComp_IntelMPI.2021.2_mkl

Linux Cluster PLEIADES Uni-Wuppertal

**Additional context**

Please see the FDS-Files.
[02-FDS.zip](https://github.com/firemodels/fds/files/14968459/02-FDS.zip)

**Comment by mcgratta** [comment]
Run your case with the latest version of FDS, 6.9.1.

**Comment by mcgratta** [comment]
You should also make sure that all obstructions with a `BULK_DENSITY` should have a non-zero volume.

**Comment by mcgratta** [comment]
Good. I'll close the issue.
