### ISSUE TITLE
Restarting a simulation after adding OBST and VENT

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12817]
**Is your feature request related to a problem? Please describe.**
I would like to run a simulation without any obstacle for 4 hours. I would like to restart the simulation after adding a OBST and VENT. Would it be possible ?

**Describe the solution you'd like**
I would like to use the 4 hours simulation as input to a series of simulations with different OBST and VENT

**Describe alternatives you've considered**
The alternative would be to start each simulation with its own 4 hour simulation, which proves to expensive for both computation and storage

**Additional context**
When I tried to do run the first simulation, and tried to restart the simulation with OBST and VENT, I get the following error:
_forrtl:severe (67): input statement requires too much data, unit 121, file chid.restart_

**Comment by drjfloyd** [comment]
You cannot make changes to the input file that changes the size of arrays being used during runtime.  If you want at some time in the future you want to add different OBST for different runs, you need to have each of those options defined in the initial input file. You can assign each OBST its own DEVC measuring time and in the first run have the setpoint be beyond  the end of the run. Then in each restart you can change the setpoint for the desired OBST to be the restart time. This way the OBST is accounted for in the restart file but won't appear until the DEVC activates. See the User's Guide for how to create or remove OBST with DEVC.
