### ISSUE TITLE
TGA Analysis mode underpredicts Char creation

### ISSUE THREAD

**Issue by r-broek** [firemodels/fds#12847]
**Describe the bug**
The TGA Analysis of the NIST Douglas fir validation vegetation model seems to underpredict the Char creation and therefore the Char Oxidation reaction. 

**To Reproduce**
1. Run the attached input file.
2. Plot *CHAR MLR* and *vegetation MLR*.

**Expected behavior**
Since the char yield is 0.26, we expect roughly a quarter of the peak *vegetation MLR* to be the peak *CHAR MLR* creation.

**Screenshots**
As can be seen below, the creation of char is orders of magnitude lower than expected.
![image](https://github.com/firemodels/fds/assets/137812007/400534ca-4fc5-4add-8b4b-e3ee39750918)
![image](https://github.com/firemodels/fds/assets/137812007/f9173baf-bdb7-47a6-860e-4c65936640d7)
![image](https://github.com/firemodels/fds/assets/137812007/0b3331fe-23c8-4a43-ab63-14c39582adf5)

**Additional context**
- I noticed that the predicted kinetic parameters for the Char oxidation reaction were inconsistent since the *SURFACE_OXIDATION_MODEL* uses different units than the standard complex pyrolysis model. Could this also influence the Char creation?

- Note that the Char creation is underpredicted only when the TGA Analysis is used, not if the actual simulation is run.

[char.txt](https://github.com/firemodels/fds/files/15109079/char.txt)

**Comment by mcgratta** [comment]
I understand what you are saying. It appears that the char reaction occurs at nearly the same temperature as the main pyrolysis reaction, in which case the char is quickly converted to ash and does not show a sizeable mass fraction at any point in the process.

**Comment by ericvmueller** [comment]
The `SURFACE_OXIDATION_MODEL` is kind of a 'macro' scale model that assumes a for a small particle in a large volume the oxidation is strongly tied to the available surface area of the particle and a mass transfer coefficient of oxygen to the surface. Check out section 17.1 of the User's Guide. I don't know that it is directly applicable to TGA data ...what surface area do you use to represent your sample in the TGA? What mass transfer coefficient is appropriate? 

I believe TGA data are typically used to parameterize something like Equation 9.2 in the User's Guide. But then you need your model to have a good representation of oxygen concentration at/in the solid. This is typically done with detailed solid phase models with oxygen transport. The `SURFACE_OXIDATION_MODEL` is one approximation to avoid this level of detail, but these are open questions for research and you can explore either approach.

**Comment by r-broek** [comment]
According to the FDS User Guide, if `TGA_ANALYSIS = T` is used the other `SURF`  inputs like `THICKNESS` are ignored. The surface area may thus not be representative and perhaps this could explain the underprediction. 

In any case, if it is expected that the TGA analysis of the `SURFACE_OXIDATION_MODEL` is inaccurate, then we can resolve this issue.

**Comment by mcgratta** [comment]
When `TGA_ANALYSIS=T`, FDS assumes a very very thin sample with insulated backing such that conduction is negligible and the heat transfer is thermally-thin. This must explain why the char oxidation occurs so rapidly in this case. I suggest you not use the `TGA_ANALYSIS` option, but rather just model a single pine needle as is.

**Comment by r-broek** [comment]
For what it is worth, I followed your advice and used the `tga_sample.fds` input file from the `Pyrolysis` verification directory to simulate the TGA experiment using a correct `THICKNESS` for the sample. Although this also affects the drying and pyrolysis reactions, thus making a direct comparison to TGA experiments impossible, the char oxidation behaviour looks promising. It still overlaps with the vegetation pyrolysis, but I think the corresponding MLR makes sense.

Thank you both for your help.

No char oxidation:
![image](https://github.com/firemodels/fds/assets/137812007/a42c0722-bf75-4c6d-8c50-18f1f994f31a)

Char oxidation (w/ `SURFACE_OXIDATION_MODEL`):
![image](https://github.com/firemodels/fds/assets/137812007/dca6cdd3-1fc4-47d1-8b36-0905e16d4c79)

**Comment by mcgratta** [comment]
OK, welcome to our world. The take-away from all this is that there is no such thing as "zero-order" pyrolysis. All bench and micro-scale measurements have some geometric considerations.

**Comment by ericvmueller** [comment]
The surface oxidation model is probably also over-predicting near-surface O2 mass fraction during pyrolysis because it doesn't really account for that gradient of fuel vapor or blowing effects ...certainly something we could look into as it would help limit oxidation until after pyrolysis. But the suggested kinetic coefficients may also need some improvement. 

Something we're discussing with Randy and others is how we might use a very detailed and well-resolved model to improve a simple model like this ...so hopefully we can make some progress on these questions.

**Comment by r-broek** [comment]
@ericvmueller Would you happen to know if the `surface_oxidation_model` is compatible with the `BLOWING = T` argument for the `SURF` line (Sec. 8.2.2 User's Guide)?

If I understand correctly, `BLOWING=T` adjusts the heat transfer coefficient according to Eq. 8.9, which should be equivalent to combining Eqs. 9.34 and 9.35:
$h_\mathrm{blowing}=\frac{ln(1+B)}{B} h$. 
Could you tell me if this is correct? If it is, would that mean that finding $Y_\mathrm{O_2,surf}$ from Eq. 17.9 is no longer appropriate?

(All referenced equations are from the User's Guide.)

I appreciate your help.

**Comment by ericvmueller** [comment]
Yes, it is compatible in that any modification to the heat transfer coefficient with the `BLOWING` model will be reflected in the mass transfer coefficient in equation 17.9.

**Comment by r-broek** [comment]
Thank you!

**Comment by r-broek** [comment]
For the old thermal degradation model, which uses kinetic parameters from Porterie et al., I have also tried to replicate a TGA experiment within FDS 6.7.7. I am particularly interested in the *char oxidation* behaviour ($A_{oxid} = 430\ \mathrm{m/s}$ & $E_{oxid} = 74800 \ \mathrm{J/mol}$). The first graph is obtained through the `TGA_ANALYSIS = T` mode, and the second is obtained from a setup similar to the one I described above. I additionally set `ALLOW_SHRINKING` and `ALLOW_SWELLING` to `FALSE` as I read that those may influence non-unity order reactions.

The results from the replicated experiment are wrong. I, therefore, cannot conclude if the behaviour of the `TGA_ANALYSIS = T` mode is correct. The temperature at which the oxidation starts seems high. 

Do you have some suggestions on what I could do to verify if the *char oxidation* in the first plot is accurate?

<img src="https://github.com/firemodels/fds/assets/137812007/6623b238-249b-4e77-86ee-a18c2bf5ee09" width="450">

<img src="https://github.com/firemodels/fds/assets/137812007/d9d53ab7-4527-4340-944d-4e231f6b3f6c" width="450">

**Comment by ericvmueller** [comment]
As with the surface oxidation model, the old char oxidation model is based on the idea that surface area (surface-to-volume ratio) and the surrounding flow conditions (Reynolds correction factor) are key parameters in the reaction rate. In `TGA_ANALYSIS=T` the object geometry is fixed as a cartesian element with a thickness of 1 um, and there is no model of the surrounding flow, as far as I know. How these relate to particle size and the purge gas velocity in a real TGA, I don't know. Also, I'm not even sure the surface-to-volume ratio was properly calculated in that model for cartesian elements.

**Comment by r-broek** [comment]
Ah, I see. I will make sure to disable the char oxidation for any TGA simulation I run. Thanks again for all your help, I really appreciate it.

**Comment by ericvmueller** [comment]
There are still cases which fit char oxidation parameters based on TGA results ...for example, the pine material here: 
https://github.com/firemodels/fds/tree/master/Utilities/Input_Libraries/MATL
which have been exploring recently based on this reference:
https://www.sciencedirect.com/science/article/pii/S0010218011003890

But those models are fit using an assumption that kinetics are the main driver in the TGA and the mass transfer details are not so important. Which is kind of the same assumption for the simulated TGA in FDS. I don't claim to have the answer but its more just something to be aware of and why you might see this inconsistencies (especially when comparing to the simplified models that have these extra parameters related to mass transfer that we don't know how to account for in the TGA).

**Comment by r-broek** [comment]
An interesting read, thank you for the paper! 

Regarding char oxidation, I found this paper that discusses and compares the different char oxidation models for firebrands, which has helped me understand better their differences. (https://doi.org/10.1016/j.combustflame.2021.111619) 
If I am not mistaken, the FDS model comes closest to their *combined convection and kinetics* model. But as you say, for a TGA experiment with an abundance of oxygen such a model should reduce to kinetics controlled. 

If you do not mind, I have one more question. The way I understand it, one would not want any combustion to occur during TGA experiments. Therefore, nitrogen is often used. But as a result char oxidation does not occur either. Then, if I want to mimic a TGA experiment for air with char oxidation and adjusted `THICKNESS` (like `Verification/WUI/Needle_TGA_x.fds`) , would it be more appropriate for me to include or exclude fuel combustion?

**Comment by ericvmueller** [comment]
Interpretation of TGA results is based on the idea that the sample temperature matches the prescribed heating rate, so possible deviations from this temperature from an exothermic oxidation reaction, for example, are assumed negligible. 

In the Needle_TGA cases you can see the fixed gas-phse temperature ramp, high heat transfer coefficient, and small thickness mean the solid-phase temperature should track the prescribed ramp regardless of the effect of reactions. So it shouldn't actually matter if you have fuel combustion but you can try it out. As for weather the gaseous fuel in a real TGA actually ignites ...I don't think you will get the right combination of temperature and flammable mixture to have combustion.
