### ISSUE TITLE
Temperature effects in gas release

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12843]
**The bug**
I am interested in studying the effect of temperature of gas leaks into atmosphere. I have changed the TMP_FRONT of 'METHANE BLOWER' surface from -300°C (which is below 0K) to 100°C, to see if the methane plume dynamics changes. However for such ranges of temperature, I observed negligible changes in the plume dynamics. On the other hand, I can see quite some difference in the interaction of plume and thermal eddy dynamics for when I change TMPA or ground surface temperature. 

**To Reproduce**
I am attaching the FDS input file here
[testTemperature.txt](https://github.com/firemodels/fds/files/15074266/testTemperature.txt)

**Expected behavior**
I would expect the plume to behave differently for different ranges of temperatures

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Sonoma

**Comment by drjfloyd** [comment]
-300 C doesn't exist as a temperature. You cannot have a temperature below absolute zero.  

With the Namelist input format, FDS doesn't know what inputs have been specified. Whatever inputs are specified will overwrite the current values of the input variables. In this case TMP_FRONT is initialized to -1 K, and FDS checks (after converting the input to K) if the value is >= 0 after reading the input. In your case it would not pass this check, and the default ambient temperature would still be applied. You have a bouyant plume and the change in bouyancy from 20 C to 100 C is not that large compared to the overall magnitude of the bouyancy driven by the low molecular weight of methane compared to air.

A good practice is to review the .out file to verify that FDS has interpreted your inputs as you intend. Had you done this you would have seen that your methane surface had no user defined TMP_FRONT (i.e. it would have stayed at ambient).

**Comment by drjfloyd** [comment]
The temperature of the gas leaving the surface is the temperature of the surface.  At -80 C, methane is still buoyant compared to air at 20 C. It is less buoyant than it is at 100 C.  If you were to carefully examine the velocity and temperature fields for the two cases, I would expect that you would see differences.  

Also consider your grid resolution. You only have one grid cell across the methane release.  How well do you think you are resolving the plume with one grid cell?

**Comment by rakyuv** [comment]
As such, I don't observe much difference between -80°C and 100°C. However I would run the same with a good resolution near the source, and I will keep you posted. I will close the issue for the moment, and I will re-open if I still don't any change after the mesh refinement near the source

Thanks
