### ISSUE TITLE
Need help to simulation oil storage

### ISSUE THREAD

**Issue by Rezamallaki** [firemodels/fds#12887]
Do you have an example of oil or ... storage in pyrosim?

**Comment by drjfloyd** [comment]
For fds files (which can be imported into Pyrosim), all of the inputs for examples shown in the User's Guide, Verification Guide, and Validation Guide are available in the FDS github repository. You can review those documents to see if you see relevant scenarios.

For Pyrosim specific needs contact Thunderhead Engineering or use their online forums for Pyrosim users.
