### ISSUE TITLE
FDS User Guide Equation 17.9 typo

### ISSUE THREAD

**Issue by r-broek** [firemodels/fds#12884]
Dear FDS developers,

If I am not mistaken, Equation 17.9 (User guide) should not contain the surface-to-volume ratio $\sigma$. The units do not match otherwise, and the `LENGTH_SCALE` is not used in line 3158 from `wall.f90` either.

**Comment by mcgratta** [comment]
You may be right. $h_m$ has units of kg/s/m2 and $A_{\rm char}$ has units of kg/s/m3. $\sigma$ has units of 1/m. Or maybe $A_{\rm char}$ has some other units?

**Comment by ericvmueller** [comment]
Yup it is a typo in the Guide. A_char and H_m have the same units. I will correct it - thanks!
