### ISSUE TITLE
Issues with Controlling the frequency of output with RAMP_SLCF

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12896]
**Describe the bug**
I am having problems in controlling the frequency of output. I tried this feature with a small test file (), where I save SLCF files at discrete time intervals and it works correctly as expected. When I try the same with a file with multiple MPI_PROCESSES, I see that the time resolution is always 6, which is equally divided between 0 and T_END. 

**To Reproduce**
This is my current input file 
[testfds.txt](https://github.com/firemodels/fds/files/15237638/testfds.txt)

**Expected behavior**
I expected it to save SLCF only at 40 s and 250 s. However it saves at 0, 120, 240, 360, 480, 600 s

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: HPC version

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
You are using a 3D slice, in which case you should be using `RAMP_SL3D`, not `RAMP_SLCF`.

**Comment by rakyuv** [comment]
Thanks @mcgratta. It works as expected.
