### ISSUE TITLE
WSGG and WIDE BAND radiation models result in numerical instability

### ISSUE THREAD

**Issue by r-broek** [firemodels/fds#12908]
**Describe the error**
Running the NIST Douglas Fir fds file (`https://github.com/firemodels/fds/tree/master/Validation/NIST_Douglas_Firs`) with the WSGG or WIDE BAND radiation model results in minimum density clipping after ~1 second. I have read the FDS User Guide and Technical Reference Guide sections on Thermal Radiation but unfortunately could not think of an explanation.

**To Reproduce**
1. Run the attached input file (grid size is slightly different compared to the default input file)

```
 Job TITLE        : (Concatenated) 2 m Douglas Fir with 14% moisture content
 Job ID string    : tree_2_m_14_pc_cat

 Time Step:       1, Simulation Time:      0.05 s
 Time Step:       2, Simulation Time:      0.10 s
 Time Step:       3, Simulation Time:      0.15 s
 Time Step:       4, Simulation Time:      0.21 s
 Time Step:       5, Simulation Time:      0.26 s
 Time Step:       6, Simulation Time:      0.31 s
 Time Step:       7, Simulation Time:      0.36 s
 Time Step:       8, Simulation Time:      0.39 s
 Time Step:       9, Simulation Time:      0.42 s
 Time Step:      10, Simulation Time:      0.45 s
 Time Step:      20, Simulation Time:      0.60 s
 Time Step:      30, Simulation Time:      0.73 s
 Time Step:      40, Simulation Time:      0.89 s
 Time Step:      50, Simulation Time:      1.03 s
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
 Time Step:      60, Simulation Time:      1.14 s
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
WARNING: Minimum density,    0.120 kg/m3, clipped in Mesh 1
 Time Step:      63, Simulation Time:      1.14 s

ERROR: Numerical Instability - FDS stopped (CHID: tree_2_m_14_pc_cat)
```

[tree_2_m_14_pc.txt](https://github.com/firemodels/fds/files/15260850/tree_2_m_14_pc.txt)
[vegetation_model.txt](https://github.com/firemodels/fds/files/15260851/vegetation_model.txt)

**Comment by mcgratta** [comment]
I'll take a look at the case.

**Comment by mcgratta** [comment]
I replicated your result with the latest version of the source code. I suggest you not use the WSGG model. There are no verification or validation cases in our guides that demonstrate that it works and/or improves the simulation results. It was added based on some student research, but I'm sorry that a disclaimer was not added to the User's Guide. I'll add that, or if this model cannot be shown to work effectively, I'll remove it.

**Comment by r-broek** [comment]
Thank you for looking into it! It is good to know that the WSGG model has not been verified, I was not aware. However, the wide-band model resulted in similar numerical instabilities. Has this model been verified? 

If possible, I would like to determine the effect of using a more complex radiation model instead of the one-band gray gas default.

**Comment by mcgratta** [comment]
These more complex models might matter if we know exactly what the fuel gas is, and its combustion properties. Burning pine needles? We don't even know the molecular weight nor the predominant species. So we don't know what wavelength bands to focus on. For vegetation, I would stick with the default model.

**Comment by drjfloyd** [comment]
If it was just WSSG that failed, I would suspect that maybe WSSG is returning a crazy kappa value. But since it also dies with WIDE_BAND_MODEL, it may bed something outside the routine for getting kappa. WIDE_BAND_MODEL still uses RADCAL absorptivities only one band at a time rather than averaged over all fequencies and I wouldn't expect crazy kappa values anywhere.

**Comment by mcgratta** [comment]
These experimental models don't make use of the various checks that have been implemented for gray gas. I'm not sure about radiative fraction and things like that. Also, particle absorption.

**Comment by r-broek** [comment]
> These more complex models might matter if we know exactly what the fuel gas is, and its combustion properties. Burning pine needles? We don't even know the molecular weight nor the predominant species. So we don't know what wavelength bands to focus on. For vegetation, I would stick with the default model.

Okay, thanks for your input!

**Comment by mcgratta** [comment]
I just discovered the problem that caused the jobs to fail. We were not assigning the solid particle source term in the radiative transport equations  an appropriate Black Body Fraction. Thus, we were over-counting radiative emission. Up to now, we have only used the single-band grey model for solid particle absorption and emission.
