### ISSUE TITLE
CO2 release from Forest

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#12923]
**Is your feature request related to a problem? Please describe.**
I have generated a forest, and I would like to simulate the gas release from trees in the forest. These gas releases happens right from the soil till the top of the tree. However I don't have an OBST, and therefore I cannot make vent at different altitudes to simulate the CO2 release from the trees. 

**Describe the solution you'd like**
I would like to know if there is a possiblity to release the gas at different altitudes from the trees

**Describe alternatives you've considered**
If it is not possible, how about the possiblilty of releasing the gas at various heights, without creating an OBST or VENT ?

**Comment by drjfloyd** [comment]
See 7.2.2 and 7.2.3 in the verification guide.
