### ISSUE TITLE
Slice interpolation to nodes at mesh intersections

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#12987]
When interpolating velocity from faces to nodes for smokeview, low values appear at mesh interfaces.

If you run the attached example, essentially a wind tunnel with 4 meshes, and load the u-velocity slice you will see the issue. The u-velocity should appear uniform along the plane of the inlet, as it is prescribed.

Looking at the code, it seems like in the `FACE_VALUE` routine we are picking up zero values from corner ghost cells which brings down the average at the nodes
https://github.com/firemodels/fds/blob/af51fceb44c0b9f2cffc9f92791b0f6379189a48/Source/dump.f90#L5980-L5997

![image](https://github.com/firemodels/fds/assets/13366803/ac3f6574-d54b-40d8-9c86-d67ff0fc1cb3)

(run on intel macOS with the latest master)

[slice_test.txt](https://github.com/firemodels/fds/files/15438702/slice_test.txt)

**Comment by mcgratta** [comment]
Should work now. Give it a try.

**Comment by ericvmueller** [comment]
Yup, looks better now - thanks!

![image](https://github.com/firemodels/fds/assets/13366803/1d387e2b-abc7-4ddf-aa9c-a701c70340f1)
