### ISSUE TITLE
Unit error for FDS 6.9.1

### ISSUE THREAD

**Issue by lihy213** [firemodels/fds#12997]
**Describe the bug**
In the source file of FDS 6.9.1, there is a unit error for `REFERENCE_ENTHALPY_TEMPERATURE` in the LINE 733 of the `type.f90` file. The original unit is `(J/kg)` representing *Temperature for the reference enthalpy*, it should be the unit of `K`.

**Comment by drjfloyd** [comment]
Thanks for catching this.
