### ISSUE TITLE
Correction for User's Guide

### ISSUE THREAD

**Issue by lihy213** [firemodels/fds#13056]
**Describe the bug**
On page 178 of FDS User's Guide 6.9.1, the following `REAC` line should be corrected.
```fortran
&REAC FUEL='PVC', HEAT_OF_COMBUSTION=16400, SPEC_ID_NU='PVC','AIR','PRODUCTS',
NU=-1,-1,1, FIXED_MIX_TIME=0.1 / 
```
Since in the new version of FDS, the keyword `FIXED_MIX_TIME` belongs to the namelist `COMB` rather than `REAC`.

**Comment by drjfloyd** [comment]
Thanks.
