### ISSUE TITLE
WARNING: Maximum density,    2.662 kg/m3, clipped in Mesh 1

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#13081]
**Describe the bug**
I have been trying to import terrain data with GEOM using qgis2fds. I had some errors when I increase the complexity. 

**To Reproduce**
I'm attaching the FDS input file and the terrain GEOM file
[fdsFiles.zip](https://github.com/user-attachments/files/15916742/fdsFiles.zip)

**Expected behavior**
I expected it to run without any problem

**Screenshots**
![Capture d’écran 2024-06-20 à 17 53 42](https://github.com/firemodels/fds/assets/38204789/426f318a-6fec-4feb-9915-08b6591b32a6)

**FDS version**
FDS version : FDS6.7.9_SMV6.7.21

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: HPC

**Comment by marcosvanella** [comment]
Hi Rakes, try the latest bundle here https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST
And let us know if you still see the issue.

**Comment by rakyuv** [comment]
Hi @marcosvanella . Thank you for your help. I don't see that error anymore
