### ISSUE TITLE
Errors with and without individual HOC with burn away feature

### ISSUE THREAD

**Issue by BastianStahra** [firemodels/fds#13121]
**Describe the bug**
I am using the Burn-Away feature. 
When I use heat of combustions for every material indivídually, simulations don't work
When I use only one heat of combustion in the reaction line, simulation works 

**To Reproduce**
Simulate both given scenarios

**Expected behavior**
BurnAway-BA0061 --> segm error after 367s 
BurnAway-BA0062 --> no error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: supercomputer PLEIADES in Wuppertal, Germany
 - Version: [e.g. 22]
 

[05-Burnaway.zip](https://github.com/user-attachments/files/16090180/05-Burnaway.zip)

**Additional context**

**Comment by mcgratta** [comment]
The HoC might be a "red herring", as we say in English. It may have nothing to do with it. I ran your cases with the latest source code and 61 ran to completion and 62 failed. My guess this has to do with `BURN_AWAY`. I will try to pinpoint the exact  cause, but if you do not really need `BURN_AWAY`, I would remove it and try again.

**Comment by BastianStahra** [comment]
Thank you for checking this for me. I have encountered several other issues with the burn-away feature that I haven't reported yet. I am currently examining a scenario where fire develops freely over a balcony structure, and the burn-away feature is quite crucial for this. The fire behaves differently when obstructions are present, and without these obstructions ceasing to burn, the total Heat Release Rate (HRR) becomes extremely high. I could potentially add a ramp to the burning items to respect that the fuel is consumed, but this would depend on how many sides of an obstruction are burning, which I can only estimate. Without ramping the burning, the fire continues indefinitely.

**Comment by mcgratta** [comment]
I fixed a bug and reran your two cases successfully. Try the [test version here](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST). Let me know if it works for you.

**Comment by BastianStahra** [comment]
> I fixed a bug and reran your two cases successfully. Try the [test version here](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST). Let me know if it works for you.

Oh, great, thank you.
I started both cases with the new nightly build. I will let you know wheather it worked or not.

**Comment by BastianStahra** [comment]
Both cases completed successfully. Great job, Kevin!

But again these blocks at the mesh boundary which won't burn at all or won't burn away.

![image](https://github.com/user-attachments/assets/544c63db-d1ec-4549-b1aa-6c771d67d582)


Just FYI: The case with individual HoCs for each material (37h) took about 18h longer (or almost twice as long) than the case with only one HoC over the reac line (19h).

**Comment by mcgratta** [comment]
I think this problem of burning obstructions at mesh boundaries is covered in Issue #13181. I will close this issue.
