### ISSUE TITLE
Error with BULK_DENSITY at mesh boundaries

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#13134]
**Describe the bug**
The check for zero volume OBST with BULK_DENSITY > 0 fails in some cases with these OBST on mesh boundaries. The attached case has a single obstruction which crosses several mesh boundaries. The OBST has several cells within each mesh so I would not expect it to crash in this manner.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Latest master (d5686e6)

[simple.txt](https://github.com/user-attachments/files/16128310/simple.txt)

**Comment by mcgratta** [comment]
I just saw this same problem with another issue. I have not yet posted the fix but will today.

**Comment by mcgratta** [comment]
Try it now.

**Comment by johodges** [comment]
Thanks for jumping on this. I can confirm the fix works on the simple case posted here as well as the more complex case on which it was based.
