### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by JinwenDong** [firemodels/fds#13131]
When I run the FDS file on the EDDIE server, the program process file returns:
forrtl: severe (174): SIGSEGV, segmentation fault occurred

Here is the Screenshots of return: 
![image](https://github.com/firemodels/fds/assets/174874623/7d4ac329-639b-4365-b513-72769b2c1df2)

Here is my jobscripts codes: 
![image](https://github.com/firemodels/fds/assets/174874623/742ecfbd-f95b-40b2-867f-2eb224b284fb)

**Desktop (please complete the following information):**
 - OS: Rocky Linux 9
[CaseB1.txt](https://github.com/user-attachments/files/16119769/CaseB1.txt)

Thank you

**Comment by mcgratta** [comment]
This line seems to be causing the trouble:
```
&OBST ID='side sheet1', XB=1.1995,1.2,-1.6995,1.6995,0.0,2.3235, COLOR='INVISIBLE',  SURF_ID='steel'/
```
It is on a mesh boundary and there is another obstruction that overlaps it. The code logic is confused because it does not know which obstruction to apply, which leads to a array out of bounds error. I will try to see if I can flag this with an error or fix the code to work in this case.

**Comment by JinwenDong** [comment]
Dear Kevin,


Thank you for your reply.


I follow you suggestions and modify my codes, and the fads file running successfully.&nbsp;


Thank you so much.


Best wishes,
Jinwen



发自我的iPhone


------------------ Original ------------------
From: Kevin McGrattan ***@***.***&gt;
Date: Sun,Jul 7,2024 6:57 PM
To: firemodels/fds ***@***.***&gt;
Cc: JinwenDong ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [firemodels/fds] forrtl: severe (174): SIGSEGV, segmentationfault occurred (Issue #13131)





 
This line seems to be causing the trouble:
 &amp;OBST ID='side sheet1', XB=1.1995,1.2,-1.6995,1.6995,0.0,2.3235, COLOR='INVISIBLE',  SURF_ID='steel'/  
It is on a mesh boundary and there is another obstruction that overlaps it. The code logic is confused because it does not know which obstruction to apply, which leads to a array out of bounds error. I will try to see if I can flag this with an error or fix the code to work in this case.
