### ISSUE TITLE
Ramping INTERNAL_HEAT_SOURCE on SURF and OBST

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#13138]
**Is your feature request related to a problem? Please describe.**
I have another feature request related to modeling batteries. At a high level, the process for thermal runaway in a cell is:
1. Some initiating event at ambient (electrical, thermal, or mechanical abuse) resulting in the onset of thermal runaway
2. Internal heat generation from the chemical reaction until rupture
3. Release of battery gas after rupture

I was trying to model the heating between 1 and 3 using the INTERNAL_HEAT_SOURCE term; however, we do not have the ability to ramp this term right now. We currently have INTERNAL_HEAT_SOURCE for a SURF allocated to individual layers, but I do not see any other SURF RAMPs which are indexed off the layer. It should be straightforward to add an INTERNAL_HEAT_SOURCE_RAMP that applies evenly to all layers, but having a separate RAMP for each layer might be an issue with the current data structures in BOUNDARY_ONE_D_TYPE and SURFACE_TYPE. I think a global RAMP for INTERNAL_HEAT_SOURCE on a SURF line would be fine. Thoughts?

The HT3D implementation allows for INTERNAL_HEAT_SOURCE to be added on an OBST line as well, which it would be helpful to be able to RAMP. However, I did not see any other RAMPs in the code for OBST.
 
**Describe the solution you'd like**
Could we add a RAMP for INTERNAL_HEAT_SOURCE to SURF and OBST?

**Comment by drjfloyd** [comment]
This can be done but it will mean adding to the B1D type structure for wall cells and particles with 1D heat transfer.

The INTERNAL_HEAT_SORUCE gets stored as a B1D real array over the wall layers when a wall cell is initialized. To get a RAMP would mean we would also need a B1D integer array over the wall layers to hold the ramp indices.

**Comment by rmcdermo** [comment]
I think it is a good idea to have the RAMP, we need control over heat sources.

Let's think about how to make it efficient, might need to rework some things.  Maybe the heat sources should be moved to B2 array, for example.

**Comment by drjfloyd** [comment]
Added RAMP_IHS to SURF and OBST.  IHS for Internal Heat Source. Since we allow for a surface to have both heat conduction and a specified HRRPUA, we needed another ramp since RAMP_Q could be used for HRRPUA.

**Comment by johodges** [comment]
Thanks, working with it a bit now. So far the results look like I would expect. Here is a solid-phase only simulation of the Larsson case with timed ramps for RAMP_IHS defined for the different batteries. I am still exploring the interactions with HT3D and will follow up if I run into issues. Do you want to close this out for now?

![image](https://github.com/user-attachments/assets/59fa7534-c508-4319-ad42-379cede4cbf3)

**Comment by drjfloyd** [comment]
Thanks for confirming.  I'll close this out.

**Comment by hahaha666123-arch** [comment]
> 谢谢，现在使用它了一点。到目前为止，结果看起来就像我所期望的那样。这是 Larsson 情况的纯固相仿真，其中为不同电池定义了RAMP_IHS定时斜坡。我仍在探索与 HT3D 的交互，如果遇到问题，我会跟进。是否要暂时关闭此内容？
> 
> ![image](https://private-user-images.githubusercontent.com/17127980/347962016-59fa7534-c508-4319-ad42-379cede4cbf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNjAxMzEsIm5iZiI6MTczNjA1OTgzMSwicGF0aCI6Ii8xNzEyNzk4MC8zNDc5NjIwMTYtNTlmYTc1MzQtYzUwOC00MzE5LWFkNDItMzc5Y2VkZTRjYmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDA2NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ODNkNWJkMmU0ZDAzMDYyMmRjYTczNjMwODE4YzBiNThmNWRhZWY4ZDI2MDU5MTZjYzE3Y2UyOTJiYWMzYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yeVHHO2sIA1coNawAygmOkLBW7eoyAlCaiA9HKTzfew)
Hello Sir, I am a beginner in FDS and I would like to ask how to use RAMP_IHS and INTERNAL_HEAT_SOURCE together in FDS? I didn't find any relevant case study . Thanks .
