### ISSUE TITLE
Smokeview visualization Error when results are bounded

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#13156]
Dear,

I am facing an issue with the visualization of some results in smokeview  (version 6.9.1) running on a azure windows VDI.

When I plot the results and I don't set the maximum and minimum bounds for the colorbar I visualize all colors correctly in the contour. But if I set the maximum bound all values exceeding the limit instead of turning red are plotted as blue.

![image](https://github.com/firemodels/fds/assets/15084725/ed7767e3-3e9a-41b3-86ce-e1a0b520b53f)

The figure above shows the issue. The zone near the fire (black square) should appear red because it's filled with smoke but this is not properly displayed. I tried to change the limits in the ini file and not in the smokeview GUI, but this doesn't solve the problem. I also tried to plot other quantities, but I see the same issue. 

Thank you in advance for the support.

Kind regards,

Matteo

**Comment by gforney** [comment]
see if you can reproduce the problem with smokeview 6.9.3 https://github.com/firemodels/smv/releases/tag/SMV-6.9.3

if you can upload your test case and I'll take a look (change .fds extenstion to .txt)

**Comment by gforney** [comment]
I'm closing the issue.  if you still see a problem with the latest nightly build you can reopen it
