### ISSUE TITLE
Failed to open reconstruction smv. file on PyroSim Result

### ISSUE THREAD

**Issue by JinwenDong** [firemodels/fds#13170]
Hi, 

I used this line of code in the fds file code: 
&MISC RESTART = .FALSE., SHARED_FILE_SYSTEM=F/

13 sub-smv files and one main smv file were generated. I reconstruction them into a new smv file. The new smv file works fine. However, I try to open this new smv file in PyroSim Result and it flashes back. I've successfully imported smv files before that didn't use the SHARED codes, so this shouldn't be a compatibility issue.

Here's my reconstruction code (Windows):

@echo off
setlocal enabledelayedexpansion
set files=CaseS10_000001.smv CaseS10_000002.smv CaseS10_000003.smv CaseS10_000004.smv CaseS10_000005.smv CaseS10_000006.smv CaseS10_000007.smv CaseS10_000008.smv CaseS10_000009.smv CaseS10_000010.smv CaseS10_000011.smv CaseS10_000012.smv CaseS10_000013.smv
type nul > CaseS10_combined.smv
type CaseS10.smv >> CaseS10_combined.smv
for %%f in (%files%) do (
    type %%f >> CaseS10_combined.smv
)

Attached is my fds file (CaseS10fds), and the 13 sub smv files and a main smv file (CaseS10.smv) generated. CaseS10_combined.smv is the reconstruction smv file. 

[CaseS10.txt](https://github.com/user-attachments/files/16202476/CaseS10.txt)
[CaseS10_000001.txt](https://github.com/user-attachments/files/16202477/CaseS10_000001.txt)
[CaseS10_000002.txt](https://github.com/user-attachments/files/16202478/CaseS10_000002.txt)
[CaseS10_000003.txt](https://github.com/user-attachments/files/16202479/CaseS10_000003.txt)
[CaseS10_000004.txt](https://github.com/user-attachments/files/16202480/CaseS10_000004.txt)
[CaseS10_000005.txt](https://github.com/user-attachments/files/16202481/CaseS10_000005.txt)
[CaseS10_000006.txt](https://github.com/user-attachments/files/16202482/CaseS10_000006.txt)
[CaseS10_000007.txt](https://github.com/user-attachments/files/16202483/CaseS10_000007.txt)
[CaseS10_000008.txt](https://github.com/user-attachments/files/16202484/CaseS10_000008.txt)
[CaseS10_000009.txt](https://github.com/user-attachments/files/16202485/CaseS10_000009.txt)
[CaseS10_000010.txt](https://github.com/user-attachments/files/16202486/CaseS10_000010.txt)
[CaseS10_000011.txt](https://github.com/user-attachments/files/16202487/CaseS10_000011.txt)
[CaseS10_000012.txt](https://github.com/user-attachments/files/16202488/CaseS10_000012.txt)
[CaseS10_000013.txt](https://github.com/user-attachments/files/16202489/CaseS10_000013.txt)
[CaseS10_combined.txt](https://github.com/user-attachments/files/16202490/CaseS10_combined.txt)
[CaseS10fds.txt](https://github.com/user-attachments/files/16202491/CaseS10fds.txt)

FDS version：6.9.1
SMV  version：6.9.1
PyroSim version: 6.8.0

Thank you for your help.

**Comment by drjfloyd** [comment]
This forum does not provide Pyrosim support. Please contact Thunderhead Engineering for Pyrosim issues.

**Comment by JinwenDong** [comment]
Thank you, I will connect Thunderhead Engineering for support.
