### ISSUE TITLE
Different behaviour between fds and fds_openmp

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#13207]
**Describe the bug**
SEGMENTATION FAULT

`forrtl: severe (174): SIGSEGV, segmentation fault occurred`
`Image              PC                Routine            Line        Source`
`libpthread-2.31.s  000014909224D420  Unknown               Unknown  Unknown`
`fds                000000000738DED9  Unknown               Unknown  Unknown`
`fds                000000000738D170  Unknown               Unknown  Unknown`
`fds                0000000006AF79E7  Unknown               Unknown  Unknown`
`fds                0000000006AB6BCE  Unknown               Unknown  Unknown`
`fds                000000000040A71D  Unknown               Unknown  Unknown`
`libc-2.31.so       000014909030E083  __libc_start_main     Unknown  Unknown`
`fds                000000000040A636  Unknown               Unknown  Unknown`

`=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES`
`=   RANK 0 PID 11757 RUNNING AT hpc-server49403`
`=   KILLED BY SIGNAL: 9 (Killed)`

**To Reproduce**
Use the attached file [42122-sc6-A-02.fds]
Run FDS6.9.1 on 60 cores single thread ( mpiexec -np 60 fds file_name.fds )
The issue seems to be related to the high number of files opened by FDS. I have also tried to increase the limit of files using the following: `ulimit -n 99999`

But I still got the error.

If instead you execute the very same case using 2 threads ( mpiexec -np 60 fds_openmp file_name.fds  ) the simulation works ok.

**Expected behavior**
Simulation should work both when single and when multi-threads.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 2004

[42122-sc6-A-02.fds.txt](https://github.com/user-attachments/files/16347200/42122-sc6-A-02.fds.txt)

**Comment by drjfloyd** [comment]
Fortran limits the number of open files per process but I don't think your case is coming close to that limit as the open files would be the error, out, and csv files which are just a handful of files. SLCF is opened and closed per write.  When does your case fail? I am running now with 6.9.1 and it is out to over 2 s.

**Comment by rupole1185** [comment]
Hi,

the failure is right at the beginning. And I only got it when running with
the configurations I said, so when running without hyperthread
Ruggero Poletto
Managing director

VideoCall: calendly.com/ruggero-poletto | Mobile: +39 378 30 33 133

Il mar 23 lug 2024, 13:07 Jason Floyd ***@***.***> ha scritto:

**Comment by drjfloyd** [comment]
Are you running the precompiled binaries or have you compiled on your own?

**Comment by rupole1185** [comment]
The precompiled binaries
Ruggero Poletto
Managing director

VideoCall: calendly.com/ruggero-poletto | Mobile: +39 378 30 33 133

Il mar 23 lug 2024, 13:23 Jason Floyd ***@***.***> ha scritto:

**Comment by drjfloyd** [comment]
This is running without issues for me. What does the start of the .out file say for the case that fails?

 Fire Dynamics Simulator

 Current Date     : July 23, 2024  07:04:18
 Revision         : FDS-6.9.1-0-g9743202-release
 Revision Date    : Fri Apr 5 16:53:17 2024 -0400
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
 Compilation Date : Apr 06, 2024 04:35:02

 Number of MPI Processes:  60

**Comment by rupole1185** [comment]
Fire Dynamics Simulator

 Current Date     : July 23, 2024  08:01:45
 Revision         : FDS-6.9.1-0-g889da6a-release
 Revision Date    : Sun Apr 7 17:05:06 2024 -0400
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for
applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
 Compilation Date : Apr 09, 2024 13:24:51

 Number of MPI Processes:  60

*Ruggero Poletto - **Managing director*

*VideoCall*: calendly.com/ruggero-poletto | *Mobile*: +39 378 30 33 133

*NEXT EVENTS we are attending:*

FEMTC <https://www.femtc.com/events/2024> - 18-20 Sept. 2024 | OPENFOAM ITA
- 7-8 Sept. 2024

________________________________________

CFD FEA SERVICE SRL P.IVA 04545570238 - via Borgo Grande 19, 37044 Cologna
Veneta VR

*ATTENTION:*

All information in this e-mail message, as well as any files included, are
intended for the exclusive use of the recipient (s) indicated above /
indicated, and therefore subject to protection pursuant to law no. 675 and
of the Legislative Decree of 30 June 2003 n. 196. Anyone who receives this
message by mistake, is requested to notify the writer of the incorrect
receipt, and proceed with the immediate cancellation of the same from the
system. Your cooperation is appreciated.

*PRIVACY:*

All personal data, including e-mail addresses, are collected and stored
with the sole purpose of carrying out our professional activity towards
you. The privacy law D.Lgs. N. 196 of 30/06/2003 provides in article 7 the
right of the interested party to access their personal data, to request
their correction, updating and deletion, therefore we invite you to report
us in the way you deem most appropriate as provided by Article 7.

**Comment by drjfloyd** [comment]
@mcgratta @rmcdermo @gforney Does this case run for you? I can't reproduce the error on our system. It is running for mew with release and the current source.

**Comment by rmcdermo** [comment]
The latest compiled source ran fine for me.  But the 6.9.1 release failed, see `test.err.txt` below.
[test.err.txt](https://github.com/user-attachments/files/16349237/test.err.txt)
[test.fds.txt](https://github.com/user-attachments/files/16349238/test.fds.txt)

**Comment by rupole1185** [comment]
Yeah. I'll try it tomorrow if it is not an issue. Thanks
Ruggero Poletto
Managing director

VideoCall: calendly.com/ruggero-poletto | Mobile: +39 378 30 33 133

Il mar 23 lug 2024, 15:15 Jason Floyd ***@***.***> ha scritto:

**Comment by rupole1185** [comment]
Hi there,

I confirm that when using the most recent version of FDS
(FDS-6.9.1-594-gdec1605 2024-Jul-26 15:35) the problem has been solved.
Thanks,

*Ruggero Poletto - **Managing director*

*VideoCall*: calendly.com/ruggero-poletto | *Mobile*: +39 378 30 33 133

*NEXT EVENTS we are attending:*

FEMTC <https://www.femtc.com/events/2024> - 18-20 Sept. 2024 | OPENFOAM ITA
- 7-8 Sept. 2024

________________________________________

CFD FEA SERVICE SRL P.IVA 04545570238 - via Borgo Grande 19, 37044 Cologna
Veneta VR

*ATTENTION:*

All information in this e-mail message, as well as any files included, are
intended for the exclusive use of the recipient (s) indicated above /
indicated, and therefore subject to protection pursuant to law no. 675 and
of the Legislative Decree of 30 June 2003 n. 196. Anyone who receives this
message by mistake, is requested to notify the writer of the incorrect
receipt, and proceed with the immediate cancellation of the same from the
system. Your cooperation is appreciated.

*PRIVACY:*

All personal data, including e-mail addresses, are collected and stored
with the sole purpose of carrying out our professional activity towards
you. The privacy law D.Lgs. N. 196 of 30/06/2003 provides in article 7 the
right of the interested party to access their personal data, to request
their correction, updating and deletion, therefore we invite you to report
us in the way you deem most appropriate as provided by Article 7.

**Comment by rmcdermo** [comment]
Thanks for letting us know.
