### ISSUE TITLE
Louvered vent blows at the wrong angle

### ISSUE THREAD

**Issue by Rbemi** [firemodels/fds#13213]
When using a louvered vent, the actual airflow does not match the expected angle. The validation case does work, but when using a smaller vent, the angle tends to be larger than the input with respect to the vent normal.

Here is the FDS case (Pyrosim and FDS 6.9 on Windows 10):

`
&HEAD CHID='case2'/
&TIME T_END=20.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='MESH', IJK=69,64,22, XB=0.0,6.9,-2.4,4.0,0.6,2.8/

&SURF ID='louvered_vent',
      COLOR='RED',
      HEAT_TRANSFER_COEFFICIENT=0.0,
      VEL=-3.0,
      TAU_V=-1.0,
      VEL_T=-3.0,0.0/

&OBST ID='Obstruction', XB=0.0,0.2,2.0,4.0,0.05,2.8/ 

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=6.9,6.9,-2.4,4.0,0.6,2.8/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,-2.4,4.0,0.6,2.8/ 
&VENT ID='Mesh Vent: MESH [YMAX]', SURF_ID='OPEN', XB=0.0,6.9,4.0,4.0,0.6,2.8/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=0.0,6.9,-2.4,-2.4,0.6,2.8/ 
&VENT ID='Vent02', SURF_ID='louvered_vent', XB=0.2,0.2,2.0,4.0,1.681824,2.290319/ 

&SLCF QUANTITY='VELOCITY', ID='velocity', XB=0.0,6.9,-2.4,4.0,0.0,3.0/
&SLCF QUANTITY='U-VELOCITY', ID='velocityX', XB=0.0,6.9,-2.4,4.0,0.0,3.0/
&SLCF QUANTITY='V-VELOCITY', ID='velocityY', XB=0.0,6.9,-2.4,4.0,0.0,3.0/

&TAIL /
`

The inflow should follow a 45° line from the vent.

Here is the velocity field when using a small vent:
![image](https://github.com/user-attachments/assets/9e6909b1-abd9-4b4d-8835-f7fd592fa462)

Here is the velocity when the whole XMIN boundary is set to use the louvered vent SURF:
![image](https://github.com/user-attachments/assets/92541593-eb82-4e67-b4c3-448acb604546)

I cannot explain why there is such a difference between the two cases. I believe the mesh is fine enough to resolve the vent properly.

Thanks for the help!

**Comment by rmcdermo** [comment]
Please attach an input file.  These vent cases are tricky and the downstream bcs affect the global flow field more than you might think.

**Comment by rmcdermo** [comment]
This is typical of OPEN boundaries.  The flow is exiting the vent at the correct angle.  But OPEN bcs like flow to be normal to the boundary.  They are not good at maintaining flows that are at an angle.  If you know this angle on the boundary, then you need to set it with with parameters on the WIND line.

But I assume this is a subdomain of a real case, there you can move your boundaries far enough away that they do not affect the local vent, or if there are walls this would be a more well defined boundary for the flow problem.

**Comment by Rbemi** [comment]
Hey, thanks for your help!

I am not sure I understand your explanation. To be clear, the correct behavior is the one with the whole boundary acting as a louvered vent (the angle is correct on the attached picture of the original post). My real case has small vents in an enclosed space, so OPEN boundaries are not interfering, and even then the angle was wrong, which prompted me to do a small test case.

I ran another test case with OPEN boundaries only at the opposite sides of the vent, and walls near the vent:
![image](https://github.com/user-attachments/assets/5ac61ed9-08a8-454c-aaa7-59b3bd8ce3cd)

The angle is still wrong, despite removing the near OPEN boundaries. Is this what you suggested by saying that OPEN boundaries did not like non-perpendicular flow?

**Comment by mcgratta** [comment]
Look at the flow vectors in the vicinity of your vent. Add `VECTOR=T` to the `SLCF` line.

**Comment by mcgratta** [comment]
![image](https://github.com/user-attachments/assets/c9c27d93-e4cd-49c5-8214-4f3ff8256900)

Your vent entrains air from the adjacent OPEN boundary, which shifts the trajectory of the jet. You cannot expect a perfect 45 degree angle because you have to consider the overall flow pattern.

**Comment by Rbemi** [comment]
Hello!

I agree that asking for a perfect 45° is maybe too much, although the current angle is way off in my opinion.

I ran another case, with a vent more distant from the boundaries to try and get rid of undesired side effects from the boundaries, and I get a similar behavior:
![image](https://github.com/user-attachments/assets/c096bd49-a387-4405-829c-cdd352174480)

Here is the code:

`
&HEAD CHID='case2'/
&TIME T_END=20.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='MESH', IJK=117,115,22, XB=0.0,11.7,-7.5,4.0,0.6,2.8/

&SURF ID='louvered_vent',
      COLOR='RED',
      HEAT_TRANSFER_COEFFICIENT=0.0,
      VEL=-2.0,
      TAU_V=-1.0,
      VEL_T=-2.0,0.0/

&OBST ID='Obstruction', XB=2.15,2.35,0.65,2.65,0.05,2.8/ 

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=11.7,11.7,-7.5,4.0,0.6,2.8/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=0.0,11.7,-7.5,-7.5,0.6,2.8/ 
&VENT ID='Vent02', SURF_ID='louvered_vent', XB=2.35,2.35,1.348519,2.014571,1.681824,2.290319/ 

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='velocity_vectors', PBZ=2.0/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., ID='velocity', XB=0.0,11.65,-7.5,4.0,0.0,3.0/
&SLCF QUANTITY='U-VELOCITY', ID='velocityX', XB=0.0,6.9,-2.4,4.0,0.0,3.0/
&SLCF QUANTITY='V-VELOCITY', ID='velocityY', XB=0.0,6.9,-2.4,4.0,0.0,3.0/


&TAIL /
`

Could it be some kind of Coanda effect at play? In other CFD codes, a fixed 45° velocity vector in a similar fashion will produce a 45° airflow, so I am probably misunderstanding something in FDS.

Thanks for your help!

**Comment by drjfloyd** [comment]
Resolution also matters. 10 x 10 x 5 m domain with a 1 m wide wall segment 2 m from the -x and +y boudaries. The wall has a 1 m wide vent that is 0.6 m high at the mid-height of the domain.  Images show the results for 2.5, 5, and 10 cm. As resolution improves, the angle improves. 10 cm case shown below.

&HEAD CHID='45-10'/

&TIME T_END=20/

&MESH XB=0,5,0,5,0,5,IJK=50,50,50,MULT_ID='M'/
&MULT ID='M',DX=5,DY=5,I_UPPER=1,J_UPPER=1/

&RADI RADIATION=F/
&SPEC ID='NITROGEN',BACKGROUND=T/

&VENT PBX=0,SURF_ID='OPEN'/
&VENT PBX=10,SURF_ID='OPEN'/
&VENT PBY=0,SURF_ID='OPEN'/
&VENT PBY=10,SURF_ID='OPEN'/
&VENT PBZ=0,SURF_ID='OPEN'/
&VENT PBZ=5,SURF_ID='OPEN'/

&SURF ID='LOUVER',VEL=-2,VEL_T=-2,0,COLOR='BLUE'/

&OBST XB=2.0,2.1,7.0,8.0,0.0,5.0/
&VENT XB=2.1,2.1,7.0,8.0,2.2,2.8,SURF_ID='LOUVER'/

&SLCF QUANTITY='VELOCITY',VECTOR=T,PBZ=2.5/

![image](https://github.com/user-attachments/assets/8efbe9dc-f132-458c-9c58-7eca326f02ef)

**Comment by Rbemi** [comment]
Hello, thanks for your reply and taking the time to test things out on your side.

I didn't expect the mesh to need such a fine resolution! Sadly, it does not bode well for my real case (over 150 thin vents in quite a big domain) and the cell count.

For now, I will reduce VEL_T to approximatively match the 45° for a given flowrate and that will have to do!

Thanks everybody for the guidance, much appreciated (and I shall be more exhaustive with convergence studies in the future)!

**Comment by mcgratta** [comment]
Our of curiosity, have you mapped out the velocity profile in the vicinity of an actual louvered vent?

**Comment by Rbemi** [comment]
If you mean with respect to a real physical vent, I have not.

I must add that I need louvered vents not because they are actually louvered vents, but because the vents themselves are located at regular intervals over a circle and blowing at different angles than the cartesian directions. I was hoping I could cheat my way with this feature! HVAC vents can also be louvered, maybe they are less sensitive to the cellsize?

**Comment by mcgratta** [comment]
If you add `NO_SLIP=T` to the `SURF` line, you will see something like this:
![image](https://github.com/user-attachments/assets/fb701146-387d-439f-af00-867413f2ad99)
This option forces FDS to rigidly enforce `T_VEL` at the boundary. Note that this only applies to the interior cell edges. That is, at the external boundary of your `VENT`, FDS is going to average the velocity boundary conditions for the `VENT` and the inert solid surrounding it. This is why there was a remark above about grid resolution. The finer the grid, the less this external edge should matter. In any event, all FDS can do is spit the gas out of the vent at your desired angle. After that, the jet is influenced by the surrounding induced air flow.

**Comment by Rbemi** [comment]
I was definitively confused by the interaction between poor resolution and induced flow motion, thanks for the clear explanation abount the edges!
