### ISSUE TITLE
Issue with corrupt prt5 files

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13216]
**Describe the bug**
In running some cases with the latest source I am getting errors loading and rendering particle data.

**To Reproduce**
Run a case such as the `particle_colors` verification case. With the latest source I get only one frame when the simulation is finished, with an incorrect rendering of the particles (also loading particles while the case is running can lead to segfaults etc)
![image](https://github.com/user-attachments/assets/06066840-a62a-4807-bae7-8faaef1d7851)

Whereas rolling back to a4d640b6a I get the full animation of particles

![image](https://github.com/user-attachments/assets/f7c9e978-3a35-4c4b-8feb-ff09115ffb4a)

My guess is this modification around the logic for writing prt5 files:
99d094b

**Comment by drjfloyd** [comment]
I see the error. Copied the wrong pair of OPEN statements (copied the REPLACE rather than APPEND).  Post a fix shortly.

**Comment by ericvmueller** [comment]
Works for me now. Thanks!
