### ISSUE TITLE
Error in Askervein Hill case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13220]
The Askervein Hill case was added to the validation suite. It stopped with an error.
```
Askervein_Hill/Current_Results/Askervein_TU03A_16m.err:ERROR(888): DEVC AVGu CP FRG 17 m tower 1.6m TEMPORAL_STATISTIC is not recognized. (CHID: Askervein_TU03A_16m)

```

**Comment by marcosvanella** [comment]
Kevin do an update ant run the case again. There were some devices that had AVAREGE instead of AVERAGE.

**Comment by mcgratta** [comment]
Seems to work, thanks.
