### ISSUE TITLE
Unnecessary call to WALL_MODEL?

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13235]
I need to clean up the use of `T_IGN` and in the process I ran into this call in `velo.f90` around line 385
```
         CALL WALL_MODEL(SLIP_COEF,B2%U_TAU,B2%Y_PLUS,MU_DNS(IIG,JJG,KKG)/RHO(IIG,JJG,KKG),SF%ROUGHNESS,&
                         0.5_EB/B1%RDN,VEL_GAS-VEL_T)
```
Is this call necessary given that we also call the `WALL_MODEL` in `VELOCITY_BC`. It seems that its only purpose is to provide values for `B2%U_TAU` and `B2%Y_PLUS` which raises two questions:

1. Are these parameters needed in all simulations? They seem to only be used in very special circumstances.
2. Could these parameters be calculated in the call to `WALL_MODEL` in `VELOCITY_BC`?

**Comment by rmcdermo** [comment]
Yes, I suspect this is there to provide U_TAU and Y_PLUS.  And I suspect it was put there because something else broke because it was not there, but I can't recall what.  We would probably just have to remove it and see what firebot complains about.

**Comment by drjfloyd** [comment]
Looking at the log for velo.f90, it looks like this call was added on 4/02/2012 in dd91f6d7   add Van Driest damping to near wall turbulent viscosity.

**Comment by mcgratta** [comment]
Could we have our cake and eat it too by adding `B2%` to the `U_TAU` and `Y_PLUS` in the call we have to make to `WALL_MODEL`?
```
CALL WALL_MODEL(SLIP_COEF,U_TAU,Y_PLUS,MU_WALL/RHO_WALL,SF%ROUGHNESS,0.5_EB*DXX(ICD),VEL_GAS-VEL_T)
```

**Comment by mcgratta** [comment]
I moved the call to `WALL_MODEL` into `WALL_BC` where it will only be called when needed by condensation, deposition or whatever.

Marcos -- see me about doing the same for GEOM.

**Comment by marcosvanella** [comment]
Ok, I'll look into this. Thanks,

**Comment by mcgratta** [comment]
OK, I think that this is just a printout thing. That is, we were making this call to `WALL_MODEL` just to support the printout. I'll fix.

**Comment by marcosvanella** [comment]
My bad, looks like this works in wall.f90:

```
IF (WC%BOUNDARY_TYPE==SOLID_BOUNDARY) THEN 
      CALL WALL_MODEL(SLIP_COEF,B2%U_TAU,B2%Y_PLUS,MU_DNS(BC%IIG,BC%JJG,BC%KKG)/RHO(BC%IIG,BC%JJG,BC%KKG),SF%ROUGHNESS,&
                      0.5_EB/B1%RDN,B1%U_TANG)
ENDIF
```

**Comment by mcgratta** [comment]
Try it now.

**Comment by marcosvanella** [comment]
Completed.
