### ISSUE TITLE
Link device to specific LP_TAG

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13245]
Maybe something like this is already possible... but sometimes it would be helpful to be able to connect a device to a specific particle in a collection using `LP_TAG`. For example, in troubleshooting a case I can pull up smokeview and use the interactive feature to click on a particle and get its tag. I'd then like to add outputs for various quantities, including in-depth profiles, related to that specific particle. 
In this case, something like:
```
&DEVC LP_TAG=72, QUANTITY='WALL TEMPERATURE'/
```

![image](https://github.com/user-attachments/assets/d22931aa-cd07-41c1-b6ba-dd1ec2e6429a)

In some sense I don't think it would be too bad because it looks like devices already get assigned an `LP_TAG` for some uses, but its not an input parameter. On the other hand I'm not sure if it would become problematic if a particle moved across meshes.

**Comment by drjfloyd** [comment]
As a note, particles are tagged so that on mesh NM,  MOD(TAG,NMESHES)=NM. So the numbers are unique and preserved when a particle crosses a mesh boundary.

**Comment by mcgratta** [comment]
I added `LP_TAG` as an input parameter on the `DEVC` line.  I tested it for a case where I used `LP_TAG` instead of `INIT_ID` for a solid particle. I also tested it for a water droplet with the `QUANTITY='PARTICLE TEMPERATURE'`.  I have not tested on all quantities, multiple meshes, and various other things. Let's first ensure that it works for you, then we can write up a description in the User's Guide. A verification test might be tricky because you need to know the `LP_TAG` from Smokeiew.

**Comment by ericvmueller** [comment]
Thanks! It works for my example for both `PARTICLE TEMPERATURE` and `WALL TEMPERATURE` (giving the same). 

I'm okay if we start without handling transport between meshes ...I guess that's also problematic for `INIT_ID` currently? I don't know if we mention that in the guide but maybe we need to.
The one thing that would be nice in the short term though, is adding this to `PROF` which also has `LP_TAG` in the derived type.

For verification we could have n particles in separated meshes with different TMPA or something, and just pick one from each to output. Based on what Jason said we should be able to infer the tag of n successive particles in a mesh.

**Comment by mcgratta** [comment]
It might work across meshes since `LP_TAG` goes with the particle and is transferred across mesh boundaries. I'll check, and get `PROF` working too.

**Comment by mcgratta** [comment]
I just added the `PROF` functionality.

**Comment by ericvmueller** [comment]
When I try to add a `PROF` to my example particle, I get an error:

```
forrtl: severe (408): fort: (2): Subscript #1 of the array LAGRANGIAN_PARTICLE_CLASS has value 71 which is greater than the upper bound of 1

Image              PC                Routine            Line        Source
fds_impi_intel_li  0000000003CD95CA  dump_mp_dump_prof        9727  dump.f90
fds_impi_intel_li  00000000038B0285  dump_mp_dump_mesh         153  dump.f90
fds_impi_intel_li  00000000041CE3DD  MAIN__                    519  main.f90
fds_impi_intel_li  0000000000407A2D  Unknown               Unknown  Unknown
libc.so.6          000014CD5A23FEB0  Unknown               Unknown  Unknown
libc.so.6          000014CD5A23FF60  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000407945  Unknown               Unknown  Unknown
```

coming from here:
https://github.com/firemodels/fds/blob/1f4db59a494eea8d71b50f925a2310dd93d0275f/Source/dump.f90#L9722-L9727

Seems like 9727 should be:
`LAGRANGIAN_PARTICLE_CLASS(LP%PARTICLE_CLASS)%SURF_INDEX`

**Comment by mcgratta** [comment]
That looks like an older bug. If you fix it, does your case work?

**Comment by ericvmueller** [comment]
It works if I fix it there and also a few places below in calls to `SOLID_PHASE_OUTPUT` ..for example:
https://github.com/firemodels/fds/blob/1f4db59a494eea8d71b50f925a2310dd93d0275f/Source/dump.f90#L9768-L9771

Basically we are assuming LP_INDEX refers to the LPC following the arguments of SOLID_PHASE_OUTPUT when here we have also assigned it to the actual particle index

**Comment by mcgratta** [comment]
I fixed the bug related to particle index and class. Could you make sure things are working properly.

**Comment by ericvmueller** [comment]
One question.. all uses of `SOLID_PHASE_OUTPUT` are given `LP%CLASS_INDEX` because its a required argument ...even if we are not dealing with a particle. For example:
https://github.com/firemodels/fds/blob/1f4db59a494eea8d71b50f925a2310dd93d0275f/Source/dump.f90#L9753-L9755

But if we are not dealing with a particle (`LP%WALL_INDEX>0`) then the `LP` pointer is never assigned. Maybe its okay if the argument isn't actually used in `SOLID_PHASE_OUTPUT` ...but seems like it could cause issues

**Comment by mcgratta** [comment]
We could hardwire 0. I'll check.

**Comment by ericvmueller** [comment]
Okay. Might be why `LP_INDEX = -1` is initialized at the top (based on the old usage). Could also do something like `LPC_INDEX = -1` and then assign `LPC_INDEX = LP%CLASS_INDEX` as needed

**Comment by ericvmueller** [comment]
Looks good - can confirm the profile is writing out properly using `LP_TAG` in my test case now

**Comment by mcgratta** [comment]
This last commit will allow you to assign a PROF to a particle that crosses mesh boundaries.

**Comment by mcgratta** [comment]
I'll close. Reopen if you see any problems. I added a description of `LP_TAG` to the User's Guide.
