### ISSUE TITLE
MAX and MIN for OBST that dissappear

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#13247]
We have this pair of lines in dump.f90

   IF (DV%SPATIAL_STATISTIC(1:3)=='MAX') SDV%VALUE_1 = -HUGE(0.0_EB) + 1.0_EB
   IF (DV%SPATIAL_STATISTIC(1:3)=='MIN') SDV%VALUE_1 =  HUGE(0.0_EB) - 1.0_EB

Have a case where I am monitoring the MAX WALL TEMPERATURE over an OBST and using that to remove the OBST when a SETPOINT is reached. When this happens, there is no longer a device value for the MAX to compare against. The result is the the output becomes +/- HUGE. This means one cannot quickly plot devc data as the automatic axis range becomes HUGE. I think it would be good in the case where no current device value is returned to return something else - the last valid value of the device, the intial value of the device, or 0.

**Comment by mcgratta** [comment]
I'm wondering why this isn't trapped within the call to `SOLID_PHASE_OUTPUT`. These lines at the start:
```
! Assign default value to output

SOLID_PHASE_OUTPUT = OUTPUT_QUANTITY(-INDX)%AMBIENT_VALUE

IF (PRESENT(OPT_DEVC_INDEX)) DV => DEVICE(OPT_DEVC_INDEX)

IF (PRESENT(OPT_WALL_INDEX)) THEN

   IF (OPT_WALL_INDEX==0) RETURN
   IWX = OPT_WALL_INDEX
   WC=>WALL(IWX)
   IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) RETURN
   SURF_INDEX = WC%SURF_INDEX
```
Why wouldn't we get the `AMBIENT_VALUE`? Is there a simple test case for this?

**Comment by drjfloyd** [comment]
&HEAD CHID='max'/
&TIME T_END=10/
&MESH IJK=10,10,10,XB=0,1,0,1,0,1/
&OBST XB=0.4,0.6,0.4,0.6,0.4,0.6,DEVC_ID='FLUX'/
&SURF ID='HOT',TMP_FRONT=1000,TAU_T=-5,COLOR='RED'/
&DEVC XB=0.4,0.4,0.4,0.6,0.4,0.6,QUANTITY='INCIDENT HEAT FLUX',SPATIAL_STATISTIC='MAX',SETPOINT=5,INITIAL_STATE=T,ID='FLUX'/
&VENT PBX=0,SURF_ID='HOT'/

![image](https://github.com/user-attachments/assets/115f2ba6-04a7-474f-8095-37bef4b6ed22)

**Comment by mcgratta** [comment]
Take a look at this commit. Disregard the `LU_SMV` write statements -- that's just something Glenn needed. I set the unknown value of the device to 0 because for a `SPATIAL_STATISTIC`, it's not clear what the value ought to be. Change it if there is some better value to spit out.
