### ISSUE TITLE
ALLOW_UNDERSIDE_PARTICLES moved from MISC to SURF line

### ISSUE THREAD

**Issue by IFAB-AS** [firemodels/fds#13276]
Hello,
We have a rack where we want to allow droplets to drop from some boxes. This was done in older versions of FDS with `ALLOW_UNDERSIDE_PARTICLES=T` on the &MISC line, e.g. in example _Sprinklers_and_Sprays/cascade.fds_.

If we start our file or the example with the latest version FDS 6.9.1-634, we get an `ERROR(101): Problem with MISC line`. In FDS 6.9.1 we get a `forrtl: severe(157)` error without any additional info about the problem. If we use the &SURF line, everything works fine (see also [https://github.com/firemodels/fds/discussions/12959](url)).

The user guide ch. 15.7.1 still refers to the &MISC line and needs to be updated, also the example needs an update.

**Comment by mcgratta** [comment]
Thanks, I'll fix this. This parameter was moved from the `MISC` line because some users wanted to set difference values for different surface types. I must have missed a few old references to it.

**Comment by mcgratta** [comment]
It appears that `ALLOW_UNDERSIDE_PARTICLES` is properly referenced and used in the current version of fds GitHub repository. Could you point to where we are still using it under `MISC`?

**Comment by IFAB-AS** [comment]
You are right, in the repository it is updated and in 6.9.1 the test case runs with ALLOW_UNDERSIDE_PARTICLES on the &MISC line. Maybe our case was not starting with 6.9.1 due to some other issue which was fixed in the meantime, but it works with 6.9.1-634.
