### ISSUE TITLE
Missing input files?

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13274]
I cannot find this file in the FDS repo:
```
dataplot 315...
dataplot 316...
dataplot 317...
Error: File ../../Verification/Chemistry/cantera_ignition_delay.csv, does not exist. Skipping case.
Error: File ../../Verification/Chemistry/cantera_ignition_delay.csv, does not exist. Skipping case.
Error: File ../../Verification/Chemistry/cantera_ignition_delay.csv, does not exist. Skipping case.
Error: File ../../Verification/Chemistry/cantera_ignition_delay.csv, does not exist. Skipping case.
Error: File ../../Verification/Chemistry/cantera_ignition_delay.csv, does not exist. Skipping case.
```

**Comment by cxp484** [comment]
This file supposed to be generated by the python script. I will look into
it.

**Comment by mcgratta** [comment]
I was not running firebot. I ran the verification cases for a test version of the code, and then I ran the Matlab process script. I would prefer that all files needed for making the FDS User's and Verification Guides be available in the FDS repo except for the output of the FDS cases themselves.

**Comment by cxp484** [comment]
I get it now. In that case, we should discuss this with Randy tomorrow. For
ignition delay cases, the FDS output is compared with Cantera's. Randy has
created a Python script to run Cantera and generate its output as a first
Python test case. Therefore, we need to run this Python script before using
Matlab to generate the verification guide.

Another option is to use Cantera’s Matlab interface until the Python script
is fully developed.

Let's discuss this with Randy tomorrow.

If you need the file urgently, you can temporarily copy it from Firebot’s
directory.

**Comment by rmcdermo** [comment]
I would like Cantera to generate this file.  If you want to keep an extra
copy we can discuss.

**Comment by drjfloyd** [comment]
I see Kevin's point here. If you use the run all script outside of firebot and then the Matlab verification plot script, it would be good to not also have to remember to run some collection of python scripts. If this can't be somehow added to the Matlab scrpt, then need to edit the Verification readme.md file to provide instructions on what to do as right now it only mentions running Matlab.

**Comment by mcgratta** [comment]
Is the missing file very large? Most verification cases have a small .csv file with the exact or expected result. These files live within the same directory as the FDS input files. If the file was created with a unique python script, you can commit that as well.

**Comment by mcgratta** [comment]
FYI, [this is the page that Jason is referring to, with advice on running the verification cases](https://github.com/firemodels/fds/tree/master/Verification). Our goal is to make this process as simple as possible to encourage all of us to check code changes that might make firebot angry. It takes about an hour to run most of the verification cases and process the matlab FDS_verification_script.m. Doing this catches most problems. I do a full firebot on branches after substantial work is done potentially affecting all aspects of the code and processing scripts.

**Comment by cxp484** [comment]
The file fds/Verification/Chemistry/cantera_ignition_delay.csv is 1.4 MB. I am fine having this file in the repository for the time being, and Randy pointed out  python script can overwrite a tracked version of this file. We already have the python script that generate this file at fds/Utilities/Python/scripts/cantera_ignition_delay.py . But you need to have Cantera installed in your system to run it.

**Comment by drjfloyd** [comment]
If I am in the python scripts folder and try to run this script it fails.  The path it generates in that case does not point to the correct folders for the files. Where is it I am supposed to be to run this?

**Comment by cxp484** [comment]
You need to run it from the Python folder: python scripts/cantera_ignition_delay.py

**Comment by drjfloyd** [comment]
There are up to  3171 rows of data in the csv file. I think this could be culled down to make it much smaller for plotting purposes. The cantera data is plotted with hollow circles, but there are so many that they overlap and obscure the FDS line.  I get that for doing a detailed time step to time step comparison of FDS with Cantera you would want all the time points, but that level of detail is lost in the plots.

<img width="601" alt="image" src="https://github.com/user-attachments/assets/b2a83e2d-3d7c-4069-b4ef-61a855e4e954">

**Comment by rmcdermo** [comment]
Yes, the file was not culled because we were generating it.  I will fix
when I get back in tomorrow.

**Comment by drjfloyd** [comment]
Chandan when I run from that folder I get:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/67db16dc-4d42-4633-9e43-3bd26e9f9acf">

**Comment by cxp484** [comment]
Jason, you have to run from the Python folder with command "python scripts/cantera_ignition_delay.py".  That's how firebot is setup.  I am manged to reduce the filesize to ~100 Kb with writing after every 20 timesteps. The plots look reasonable with it. I am creating a pull request for cantera_ignition_delay.py. However, I can't upoad the fds/Verification/Chemistry/cantera_ignition_delay.csv as the Verification folder has *.csv in .gitignore. I let Randy and you decide what would be the best place to put the csv.
[FDS_Verification_Guide.pdf](https://github.com/user-attachments/files/16500404/FDS_Verification_Guide.pdf)

**Comment by rmcdermo** [comment]
You put it there, just use add -f

**Comment by cxp484** [comment]
Ok done. Added. :)
