### ISSUE TITLE
Receiving an error: malloc(): invalid size (unsorted)

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13283]
### Discussed in https://github.com/firemodels/fds/discussions/13275

<div type='discussions-op-text'>

<sup>Originally posted by **jfpe37** August  5, 2024</sup>
Good Morning
I received the attached error "**malloc(): invalid size (unsorted)**", After 214.8 seconds.
(SPRK start to work in 76.2 sec, and Blowers start to work in 91.25 sec)
I am attaching the FDS file after I removed the objects of the structure due to the need to maintain confidentiality.
I run on a **linux** with 256 cores and 1 terabyte of memory.
(Attaches the data).
I have similar run on (a different simulation) on windows computer with 20 cores, that didn't crash.
I allso run the simulation using the command "mpiexec -np 8 fds sav88-2b_002.fds", and actually want to use 8 processors when I have 8 mesh
Is the command correct?
In addition, because I am a new user of Linux and since we installed the software on the new computer, we have errors of this type in different runs in different projects.
Is it related to the linux computer? Maybe for the installation of FDS and the software settings?

I would appreciate your help in understanding the error.
thanks
Mor
[fds file.txt](https://github.com/user-attachments/files/16492903/fds.file.txt)

</div>

**Comment by mcgratta** [comment]
When I run this case with the latest version of the source code, I get the following errors:
```
ERROR(820): VENT outlet SXF-H56000CFM has no solid backing or an orientation index (IOR) is needed. (MPI Process: 6, CHID: sav88)

ERROR(820): VENT outlet SXF-G7.9 has no solid backing or an orientation index (IOR) is needed. (MPI Process: 5, CHID: sav88)
ERROR(820): VENT outlet SUF B1.8 has no solid backing or an orientation index (IOR) is needed. (MPI Process: 2, CHID: sav88)
ERROR(820): VENT outlet SUF B1.6 has no solid backing or an orientation index (IOR) is needed. (MPI Process: 0, CHID: sav88)
```
I suspect that these error messages may be related to your errors. Even if you are running the latest official release, these error messages might have been introduced lately in response to a similar user bug report. I suggest you install the latest [nightly build](https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST), fix the errors, run the case again, and report back if you still get an error.

**Comment by jfpe37** [comment]
Hi
Can you please explain to me what a **nightly build** is?
How do I install it on Linux?
Does it require a full install like a new version?
Thanks

**Comment by drjfloyd** [comment]
NIghtly builds are available each day if the previous day's Firebot run was successful..  They are found here and yes it means a full install using the same process as for an official release:
https://github.com/firemodels/test_bundles
