### ISSUE TITLE
issue with upper_skip and lower_skip

### ISSUE THREAD

**Issue by max-mig** [firemodels/fds#13296]
**Describe the bug**
I want to use the MULT feature in order to create an array of objects (in my eample cardboard box). The array will be not completely full, jumping a single place, where I would like to put a different box. So, I coded something like:

&MULT ID='BOXES',  DX=1.2,  I_LOWER=1, I_LOWER_SKIP=6, I_UPPER_SKIP=6, I_UPPER=10, 
                   DY=1.2,  J_LOWER=1, J_LOWER_SKIP=1, J_UPPER_SKIP=1, J_UPPER=5  /
Well, this solution sometime works, sometime, the same file, doesn't work.

I have solved subdividing my array in three parts and using simpler MULT lines (see "itworks.fds" file).

**To Reproduce**
You can try to launch the two attached files "works.fds" and "doesntwork.fds".

**Expected behavior**
FDS gets me a runtime error: forrtl: severe (157): Program Exception - access violation.....

**Screenshots**
![when_it_works](https://github.com/user-attachments/assets/10625e9e-0696-4726-ab76-645fb4639717)

**Desktop (please complete the following information):**
 - OS: WIDOWS 10
 - Version: FDS-6.9.1-0-g889da6a-release

**Additional context**
[Cardboard_boxes.zip](https://github.com/user-attachments/files/16548197/Cardboard_boxes.zip)

**Comment by mcgratta** [comment]
I found a bug that caused this. For the moment, do not use the `SKIP` feature.

**Comment by mcgratta** [comment]
Your case should work now if you download and install a nightly build. Otherwise, just avoid the SKIP feature.
