### ISSUE TITLE
Help with boundary condition setup to allow wall conduction

### ISSUE THREAD

**Issue by elangsz** [firemodels/fds#13291]
Hello

i am very new to FDS, and currently im using it to simulate the airflow distribution inside an electrical panel that contains a soft starter that emits heat, along with 3 exhaust fan to circulate air so the the panel doesnt overheat. As you can see from the results that are shown via smokeview, conduction didnt happen through the panel walls, as the air temperature near the outer side of the panel walls are still the same as the initial condition, which is set to 35 C. Can anybody help me with this? ill share my FDS file along with some screenshots. Ive read about SURF and MATL from the user guide but i havent quite figured it out yet. I really appreciate it.

**Smokeview results**
![image](https://github.com/user-attachments/assets/f60b8b40-1375-4180-aa3a-684343b1e813)

**Actual item**
![image](https://github.com/user-attachments/assets/45c9c77a-707c-42cd-b22d-b26796d0ba43)

**FDS Screenshots**
![image](https://github.com/user-attachments/assets/996f4ab0-4419-42d7-be0b-1563e5fa5168)
![image](https://github.com/user-attachments/assets/fc7d3f97-9188-4812-8cba-02f81326ab05)
![image](https://github.com/user-attachments/assets/1d941119-71e2-4958-b2e2-b114acc21ecb)
![image](https://github.com/user-attachments/assets/d36b7c2e-17be-4b1c-a5bd-df14e3956b50)
![image](https://github.com/user-attachments/assets/078bb563-2798-4bba-b9a7-bb4439428c89)

**FDS File**
[LCP.zip](https://github.com/user-attachments/files/16523412/LCP.zip)

**Comment by drjfloyd** [comment]
When using any numerical model, when you get results that don't make sense, it often helps to think about is there a simple hand calculation that you could do to estimate what results you should expect. 

In your case you could take the wall properties and do a lumped mass heat transfer calculation to estimate the steel wall temperature after 1000 s given that your slice file shows ~40 C to 45 C gas temperatures adjacent to the wall

&MATL ID = 'AISI 302 STEEL', CONDUCTIVITY=15.1, SPECIFIC_HEAT=0.48, DENSITY=8060/
&SURF ID='PANEL WALL', MATL_ID='AISI 302 STEEL', TMP_FRONT_INITIAL=35, THICKNESS=0.02, BACKING='EXPOSED'/

Ignoring the cold side, the steel temperature after 1000 s will be:
(q_dot''_conduction + q_dot''_radation)*1000 / (8060*0.48/0.02)

conduction = h (Tg-Tw) which is 50 to 100 W/m2 for h=10 W/m2/K and Tg = 40 to 50 C
radiation = e sigma (Tg^4 -Tw^4) which is 31 to 62 W/m2 with the defatul FDS e of 0.9 for the same temperatures.

This means the heating after 1000 s is only 1 - 2 C. 

Are you sure your electrical cabinet is 2 cm thick? Eletrical panales are typicall thin gauge sheet metal (1 to 3 mm thick).

**Comment by elangsz** [comment]
> When using any numerical model, when you get results that don't make sense, it often helps to think about is there a simple hand calculation that you could do to estimate what results you should expect.
> 
> In your case you could take the wall properties and do a lumped mass heat transfer calculation to estimate the steel wall temperature after 1000 s given that your slice file shows ~40 C to 45 C gas temperatures adjacent to the wall
> 
> &MATL ID = 'AISI 302 STEEL', CONDUCTIVITY=15.1, SPECIFIC_HEAT=0.48, DENSITY=8060/ &SURF ID='PANEL WALL', MATL_ID='AISI 302 STEEL', TMP_FRONT_INITIAL=35, THICKNESS=0.02, BACKING='EXPOSED'/
> 
> Ignoring the cold side, the steel temperature after 1000 s will be: (q_dot''_conduction + q_dot''_radation)*1000 / (8060 x 0.48 x 0.02)
> 
> conduction = h (Tg-Tw) which is 50 to 100 W/m2 for h=10 W/m2/K and Tg = 40 to 50 C radiation = e sigma (Tg^4 -Tw^4) which is 31 to 62 W/m2 with the defatul FDS e of 0.9 for the same temperatures.
> 
> This means the heating after 1000 s is only 1 - 2 C.
> 
> Are you sure your electrical cabinet is 2 cm thick? Eletrical panales are typicall thin gauge sheet metal (1 to 3 mm thick).

ah ok thankyou for the heads up, ill make sure to also use hand calc for simulations. Regarding the FDS command, dont we need to specify the SURF ID to a certain OBST? and it still didnt work for me

**Comment by elangsz** [comment]
thankyou very much sir

**Comment by mcgratta** [comment]
I am closing this issue to clear the deck for others related to this case.
