### ISSUE TITLE
Weird temperature contour due to mesh intersection in smokeview

### ISSUE THREAD

**Issue by elangsz** [firemodels/fds#13290]
Hello

i am very new to FDS, and currently im using it to simulate the airflow distribution inside an electrical panel that contains a softstarter that emits heat. I used 10 mesh (0.02 m x 0.02 m x 0.02 m per cell) by utilizing the openMP and MPI altogether to make the simulation run faster. When i view the results in smokeview, there are dots along the temperature contour on the surface in which i think that it is the intersection of the meshes. How can i get rid of this dots to make the results smoother? ill make sure to share the FDS file along with some screencapture of the actual item and geometry. Thanks in advance!

Smokeview Results
![SMOKE VIEW RESULTS](https://github.com/user-attachments/assets/48f0e065-b79b-4e4d-85e2-97c8b9e7f358)

Actual item
![image](https://github.com/user-attachments/assets/b26dc92c-acd9-4613-86d3-0de5d9edfc2c)

FDS screenshots
![image](https://github.com/user-attachments/assets/2513947d-cd80-4d4a-bf54-ac431e9ffb15)
![image](https://github.com/user-attachments/assets/9f5b1648-209e-4212-b97d-f7b2048a4c82)

FDS file
[LCP.zip](https://github.com/user-attachments/files/16521372/LCP.zip)

**Comment by drjfloyd** [comment]
I am running your case. At what time do you start seeing the visual artifacts?

**Comment by elangsz** [comment]
If im not mistaken, even in the first 10 seconds it can already be seen

**Comment by elangsz** [comment]
> I am running your case. At what time do you start seeing the visual artifacts?

If im not mistaken, even in the first 10 seconds it can already be seen

**Comment by drjfloyd** [comment]
I see this with the current source and smokeview.  It is where a mesh boundary intersects an OBST. You have a non-uniform mesh (0.01 x 0.02 x 0.02) which might be part of the issue.  As a general note on meshes, the cost of multiple meshes is data exchange so meshes that are more cube like are more efficient than meshes that are more like a sheet of paper.  

@gforney you can start seeing the artificats at about 6 s in the Y=0.3 slice.

**Comment by elangsz** [comment]
> I see this with the current source and smokeview. It is where a mesh boundary intersects an OBST. You have a non-uniform mesh (0.01 x 0.02 x 0.02) which might be part of the issue. As a general note on meshes, the cost of multiple meshes is data exchange so meshes that are more cube like are more efficient than meshes that are more like a sheet of paper.
> 
> @gforney you can start seeing the artificats at about 6 s in the Y=0.3 slice.

Thankyou very much for analyzing my FDS files, i realy appreciate it truly. Ive tried changing back the cell size into 0.02 m x 0.02 m x 0.02 m (ill also provide the screenshots), but the "dots" are still there for some reason.

Results screenshot
![image](https://github.com/user-attachments/assets/891ba7e1-6153-43e7-9c8b-b93163bef2f5)

FDS code screenshot (mesh)
![image](https://github.com/user-attachments/assets/b743ffdc-be4b-49e0-b6aa-fa38a1cdece6)

**Comment by elangsz** [comment]
i also wanted to ask how i can make the panel wall (steel) to conduct heat, because so far the heat that comes in and out are only from the soft starter (main heat source) and the exhaust fan, no heat coming out of the panel through the walls. should i make it a separate issue/discussion?

**Comment by gforney** [comment]
i'll take a look

**Comment by gforney** [comment]
attached image shows slice values at node locations read from the slice file (you can see these by setting the "values" checkbox in the slice bounds dialog box .  think the low value may be the result of interpolation on the fds side.  I ran your case with an equivalent cell centered slice and I don't see "low" values.  

![lcp_slice](https://github.com/user-attachments/assets/bd8a5bbb-49b0-4bc5-80aa-de6f41a8a393)

**Comment by gforney** [comment]
note, I am drawing the grid over the slice by pressing g and moving the grid lines until they coincide with the slice

**Comment by mcgratta** [comment]
If you are interested in seeing what FDS is calculating for temperature in each grid cell, use the cell-centered option:
```
&SLCF QUANTITY='TEMPERATURE', PBY=..., CELL_CENTERED=T /
```
The contours you are looking at are based on corner-averaged values, which might be off at the corners of multiple meshes.

**Comment by elangsz** [comment]
> attached image shows slice values at node locations read from the slice file (you can see these by setting the "values" checkbox in the slice bounds dialog box . think the low value may be the result of interpolation on the fds side. I ran your case with an equivalent cell centered slice and I don't see "low" values.
> 
> ![lcp_slice](https://private-user-images.githubusercontent.com/12403014/355861464-bd8a5bbb-49b0-4bc5-80aa-de6f41a8a393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDE4MzIsIm5iZiI6MTcyMzA0MTUzMiwicGF0aCI6Ii8xMjQwMzAxNC8zNTU4NjE0NjQtYmQ4YTViYmItNDliMC00YmM1LTgwYWEtZGU2ZjQxYThhMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE0Mzg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjFiMmNlNTQxYTZiYTQ5YjQ4YzY5OTRjNjU5ODdmOWYyZmZmYTc5ZmFmMWVlNGViMzk5YTQ0YjBkZWQ5OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wY03TsuYXUbyj4Jnxbq-1gljMtCdpzgOAUi20Twfy5I)

wow this is new information for me. I have a couple of questions

1. where can i access this "values" checkbox in the dialog menu?
2. as you mentioned before, its the result of FDS interpolation, hence can we do anything about it to make those short temperature regions "disappear"? maybe in terms of meshes size? im curious to know
3. when you said "ran my case with equivalent cell centered slice", what does it actually means?

i apologize if my questions are very basic, i really appreciate your help!

**Comment by elangsz** [comment]
> If you are interested in seeing what FDS is calculating for temperature in each grid cell, use the cell-centered option:
> 
> ```
> &SLCF QUANTITY='TEMPERATURE', PBY=..., CELL_CENTERED=T /
> ```
> 
> The contours you are looking at are based on corner-averaged values, which might be off at the corners of multiple meshes.

ah ok thankyou very much. so are there any solution to minimize this low temperature regions due to corner avg values from multiple mesh?

**Comment by mcgratta** [comment]
Yes, there is a way to improve the way the corner averaging is done for multiple mesh cases. But in your case, use the `CELL_CENTERED` option and you do not have to worry about it.

**Comment by mcgratta** [comment]
This is not a Smokeview issue. It is an FDS issue related to solid boundaries, slice files, and multiple meshes. I'll fix.

**Comment by mcgratta** [comment]
The unphysical artifacts at solid boundaries should be gone. Download and install a nightly build. Reopen the issue if things are not working properly.
