### ISSUE TITLE
Gas phase conductivity output off

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#13306]
**Describe the bug**
I was using the gas phase property outputs to do some manual calculations and noticed that the conductivity value was giving me odd results. In the simplified case (one of Validation/Convection/impinging_jet with the impinging jet correlation removed and a coarser grid) I see the behavior below. The far left image shows what I get with master. In master, DUMP uses a different call for DNS versus other SIM_MODE. In non-DNS cases the call is:

        GAS_PHASE_OUTPUT_RES = MU(II,JJ,KK)*CPOPR

In the middle and right image I changed all the SIM_MODE to use the same call as DNS (see below). The middle includes the &SPEC line for air where CONDUCTIVITY is manually specified by the user. The right does not include that line.

         ZZ_GET(1:N_TRACKED_SPECIES) = ZZ(II,JJ,KK,1:N_TRACKED_SPECIES)
         CALL GET_CONDUCTIVITY(ZZ_GET,GAS_PHASE_OUTPUT_RES,TMP(II,JJ,KK))

Is there a reason we are calculating conductivity differently between the sim modes? Is there a big performance impact in ZZ_GET and GET_CONDUCTIVITY for LES calculations?

**Screenshots**

![image](https://github.com/user-attachments/assets/6b915dd5-6947-4bef-ba46-bece3f3bb641)

**Desktop (please complete the following information):**
 - OS: windows
 - Version: 6.9.1 release

**Additional context**

[impinging_jet_Re_1e5_coarse.txt](https://github.com/user-attachments/files/16570126/impinging_jet_Re_1e5_coarse.txt)

**Comment by drjfloyd** [comment]
Subgrid turbulence makes the conductivity effectively larger than the molecular level value.

**Comment by johodges** [comment]
That makes sense. The reason I was using the output was to get the molecular level value used in the Nu calculations so I could do  my own approximate calculations to a fictitious surface throughout the domain. I should be able to do the same thing calculating a MOLECULAR CONDUCTIVITY using MOLECULAR VISCOSITY. Would it be beneficial to add an output for MOLECULAR CONDUCTIVITY or is this too much of an edge case?

**Comment by drjfloyd** [comment]
I thnk having that output makes sense.  Would just be a call to GET_CONDUCTIVITY.

**Comment by mcgratta** [comment]
I added `MOLECULAR CONDUCTIVITY`. Test it and make sure it works.
