### ISSUE TITLE
UL/NFPRF rack storage cases fail with Numerical Instability

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13336]
During the most recent round of validation runs, `UL_NFPRF_P-3.fds`, `UL_NFPRF_P-4.fds`, and `UL_NFPRF_P-5.fds`  failed with numerical instabilities. Over the past few weeks, I've done a manual bisect and it appears that the problem started in February. 

This [version](https://github.com/firemodels/fds/commit/f221115dae5551bfccbb1e773e475c71db82ff5b) runs successfully, and this [version](https://github.com/firemodels/fds/commit/2e34eafb895d7b43bfd061689869cc609dd65b8a) does not. I suspect it is this line

![image](https://github.com/user-attachments/assets/740df7d2-ec48-4c86-9a16-000f091b906d)

Given the sensitivity of these cases, let's do anything immediately. I just want to start the issue and investigate more the potential problems.

BTW, the problem starts with the version I posted above, and there were changes to the suspect line of code in the days following, but these changes did not stop the instabilities from occurring.

**Comment by drjfloyd** [comment]
The reason for that change is that the particle Q_DOT_RAD is absorption from all directions; therefore, that some of that particle Q_DOT_RAD is radiation emitted by the wall that gets absorbed by the particle. In cases were the wall is very hot but the incomming radiation is very low, then most of the radiation being absorbed by the particle is from the wall and isn't incident radiation. Without the weighting for B1%Q_RAD_OUT you could get a negative B1%Q_RAD_IN.  The later change to that line was just to prevent a div by zero.

**Comment by mcgratta** [comment]
For a liquid droplet stuck to a wall, we assume that it either is some fraction of the film layer or a semi-spherical droplet whose radius is cube root 3 times the original radius. This droplet absorbs radiation form the gas over the area adjacent to the gas. Currently that area for the non-film droplet is pi*(cr(3)*r)^2, which is the cross-sectional area. This should probably be doubled to account for the curved surface absorbing radation over 2*pi solid angles. In any event, the old code before Feb 16 was just subtracting the radiation that the solid surface receives by that which is absorbed over the half-droplet area.

**Comment by drjfloyd** [comment]
Maybe I am not remembering correctly why I made that change or I erred. I guess we could just revert that change.

Should we also be including B1%Q_RAD_OUT in the calc for Q_DOT_RAD? If the drop is abosrping incident, it will also absorb outgoing. If we do this we would need to adjust OUT at the end of the drop update like we do for IN (at the current line in question).

Also based on the film thickness, should we be doing the 1D ABSORPTION_COEFFICIENT calculation for the film? In the water evaporation verificaiton case we have 140 for the A_C so a 1 mm film would only absorb 13 %.

**Comment by mcgratta** [comment]
We've always made the assumption that water absorbs all radiation, at least at the wall. Yes, we could do a simple absorption calcs. I'll also look at Q_RAD_OUT. Whatever we do, we should ensure that the loss by gas is equal to gain by water.

**Comment by mcgratta** [comment]
I modified how radiation absorption is handled. Putting aside for the moment the issue of whether to absorb only some fraction of the radiation, I coded things so that we sum all the radiation absorbed by the water droplets on the surface and then subtract it from `Q_RAD_IN` after we have looped over all particles. In this way, `Q_RAD_IN` does not get decreased with each droplet; that is, all the surface droplets see the same amount of incoming radiation, and then we subtract at the end.

The `UL/NFPRF` cases ran past the point of failure with this change. I'm going to run them over the weekend with the master branch.

**Comment by mcgratta** [comment]
These cases now run to completion.

**Comment by drjfloyd** [comment]
For my two questions:

1) Surfaces emit radation and with a film on that surface the water will absorb some of that.  
2) The ASTM_E2058_Water_Evap case in Validation\Pool_Fires has an abosrbption coefficient of 140. For a 1 mm film most radiation would make it through to be absorbed by the surface.

Should we do this as well? I can do it when I get back.

**Comment by mcgratta** [comment]
I assume you mean 

$\dot{q}\prime\prime= \dot{q}_0\prime\prime \ {\rm e}^{-140 \ \delta} $

If so, I think we can add this in one place. We can discuss when you get back

**Comment by drjfloyd** [comment]
yes something like:

$\dot q = (\dot q_{out} + \dot q_{in}) e^{-140 \delta}$

 and then adjust the out and in accordingly

**Comment by drjfloyd** [comment]
agreed we can discuss next week
