### ISSUE TITLE
measured AST (DEVC) unequal to AST(statistic) unequal to boundary quantities (picture)

### ISSUE THREAD

**Issue by BastianStahra** [firemodels/fds#13357]
**Describe the bug**

Easy testcase for measuring the AST.

AST_DEVC (points) gives lower values than AST_STATISTIC_DEVC gives lower values than visual of boundary quantities.

after about 30 minutes:
AST_DEVC (points) = 198°C <  AST_STATISTIC_DEVC = 232°C < BQ = 243°C

**To Reproduce**

You find the testcase below. 
Compare point_devc with statistic devc and picture in results.

**Expected behavior**

Values should be more or less the same. Deviation of some degrees (<10°C) are expected due to "higher resolution" of statistic device.

**Screenshots**

![image](https://github.com/user-attachments/assets/3aff2b37-3c55-4bf1-8ea4-71ce285c1920)

![image](https://github.com/user-attachments/assets/34688f77-4567-4633-a77b-fd4961b6748a)

**Desktop (please complete the following information):**
 - Windows 10
 - simulated with the latest nightly build

**Additional context**

The higher the temperature the higher the deviation (known from other testcases)

[Flame_FH0010.txt](https://github.com/user-attachments/files/16750670/Flame_FH0010.txt)

**Comment by mcgratta** [comment]
$\max_i  \frac{1}{\Delta t} \int_t^{t+\Delta t} T_i  \  dt' \le  \frac{1}{\Delta t} \int_t^{t+\Delta t} \max_i(T_i )  \  dt' $

I think this explains it. In your case, FDS is averaging your AST values at each location over a 3.6 s interval (by default, FDS time averages the device output over an interval of `T_END/1000`). `SPATIAL_STATISITC='MAX'` takes the maximum value at every time step, and then averages that over the 3.6 s.

**Comment by mcgratta** [comment]
I assume this answers the question. If not, reopen the issue.
