### ISSUE TITLE
CFL output fails in impi_intel_linux_db build

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#13358]
**Describe the bug**
I am tracking down a numerical instability in a DNS calculation. I noticed that the SLCF quantity CFL causes a crash due to an out of bound error when running in debug mode. 

The error is:

fds_impi_intel_li  0000000003BA0760  dump_mp_gas_phase        7345  dump.f90

The line causing the issue is:

UODX = MAXVAL(ABS(US(II-1:II,JJ,KK)))*RDX(II)

I've attached the input file which fails.

**Desktop (please complete the following information):**
 - OS: frontera
 - Version: master

**Additional context**

[cfl_issue.txt](https://github.com/user-attachments/files/16752782/cfl_issue.txt)

**Comment by rmcdermo** [comment]
Thanks, I'll take a look.

**Comment by rmcdermo** [comment]
Should be fixed with PR #13360

**Comment by johodges** [comment]
Thanks, I can confirm that the file no longer crashes in debug with the change.
