### ISSUE TITLE
Question related to FDS Aircoil Parameters

### ISSUE THREAD

**Issue by elangsz** [firemodels/fds#13362]
Hi, i would like to know whether we can set an on/off parameter on an air coil based on a certain inlet air temperature set point on a return grille. For example, I have a 5 x 5 room, and i placed 1 supply grille and 1 return grille, with an air coil having a cooling capacity of 9000 BTU/hr (2.64 kW). The initial temperature will be 28 C, and once the air coming in the return grille reached 19 C (average), i want the aircoil to turn off. And once the return temperature is above 19 C, i want the air coil to turn on again, is that possible in FDS?

**Comment by mcgratta** [comment]
![image](https://github.com/user-attachments/assets/7464c543-8f5b-482b-b8bd-e82e347c923b)

**Comment by drjfloyd** [comment]
Read the User Guide chapter on control functions.

**Comment by mcgratta** [comment]
If you need further help, reopen the issue.
