### ISSUE TITLE
Controlling Ember Flux for Wildfire Simulation

### ISSUE THREAD

**Issue by matt-s-distefano** [firemodels/fds#13379]
I am creating a simulation where I model embers from wildfires as particles that are carried by wind. When they land, they act as heaters. However, something I'm running into is that the particles clump and accumulate in crevices on or near structures (see picture attached). As a result, the net heat flux from the particles is far higher in these areas (in a non-physical manner) while the net heat flux from the particles in flat areas (low lying brush) is acceptable and required to ignite these finer fuels. The overall result is that the structure is receiving far more heat than is realistic from the embers adjacent to it, rather than from the vegetation nearby burning.

Ideally I would like to design my simulation so that the particles are able to "know" when they are in a very-high-flux region – essentially sensing the surrounding particles in close proximity – and turn their NET_HEAT_FLUX parameter down, but I am struggling to find the requisite control logic for this (if any exists). I would appreciate any advice on how this could be done or how control logic could be implemented in this way

Some routes I've considered:

- Creating a "shield" over components that have crevices to ensure that embers don't land on them in high concentration, however this has proven clunky and results in still-high ember accumulations, just slightly offset from the area-of-interest
- Use particle concentration metric, e.g. Mass Per Unit Volume, to try to extract a localized control-logic function to limit the particle flux, but I'm having trouble finding literature or references supporting this type of operation.

Image attached showing the extreme gradient in heat flux away from the corners near the structure.
![image](https://github.com/user-attachments/assets/3f35e162-c8a4-45df-8d16-4b2753e68249)

Thank you!

**Comment by drjfloyd** [comment]
I think TMP_FRONT would wind up equivalent to NET_HEAT_FLUX.  TMP_FRONT is largrly just another way of defining a fixed heat flux.  In the real world, at some point you would add enough particles to a volume that particles close to the surface would shield the surface from particles further away, In the limit the surface could only see a view factor of 1's worth of the total particle area. If you had two layers of particles on a surface where each layer completely filled the area of the surface, the surface would only see the bottom layer. We don't currently account for that.

**Comment by mcgratta** [comment]
Run this case, and then run it again using more or less particles. Smokeview will allow you visualize the particles to scale. The heat flux to the ground should approach about $\sigma \ T_{\rm f}^4=75$ kW/ ${\rm m}^2$ . That neglects a small amount of reradiation and some numerical error related to shape and radiative emission.
```
&HEAD CHID='hot_embers' /

&MESH IJK=10,10,4, XB=0.0,1.0,0.0,1.0,0.0,0.4 /

&TIME T_END=10 /

&DUMP NFRAMES=10 /

&SURF ID='hot', GEOMETRY='SPHERICAL', HEAT_TRANSFER_COEFFICIENT=0., EMISSIVITY=1., TMP_FRONT=800, RADIUS=0.005 /

&PART ID='embers', SURF_ID='hot', SAMPLING_FACTOR=1, STATIC=T, QUANTITIES='PARTICLE TEMPERATURE', PROP_ID='ball shape' /

&PROP ID='ball shape', SMOKEVIEW_ID='SPHERE', SMOKEVIEW_PARAMETERS(1)='D=0.01' /

&INIT PART_ID='embers', N_PARTICLES=20000, XB=0.0,1.0,0.0,1.0,0.0,0.02 /

&VENT MB='ZMAX', SURF_ID='OPEN' /

&BNDF QUANTITY='GAUGE HEAT FLUX', CELL_CENTERED=T /
&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=T /

&SLCF PBY=0.5, QUANTITY='RADIATION LOSS', CELL_CENTERED=T /
&SLCF PBY=0.5, QUANTITY='INTEGRATED INTENSITY', CELL_CENTERED=T /

&TAIL /
```

**Comment by matt-s-distefano** [comment]
Thank you for the help! The fix of assigning TMP_FRONT did the trick for me here!
