### ISSUE TITLE
&VENT XB, MB DB

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#13391]
the attached 3 cases are the same except how the open boundary conditions are defined. for the xmin surface
vent_db.fds.txt uses &VENT DB='XMIN', SURF_ID='OPEN' /
vent_mb.fds.txt uses &VENT MB='XMIN', SURF_ID='OPEN' /
vent_xb.fds.txt uses &VENT XB=0.0,0.0,0.0,1.6,0.0,3.2, SURF_ID='OPEN' /

when run the db and xb cases output purple outlines for the open boundary conditions the mb case does not.  think it makes sense to not output the purple outlines for the exterior scene boundary as is with mb .  thought db should be consistent with mb.  let me know if this is a smokeview problem or if I am missing something

[vent_db.fds.txt](https://github.com/user-attachments/files/16873973/vent_db.fds.txt)
[vent_mb.fds.txt](https://github.com/user-attachments/files/16873974/vent_mb.fds.txt)
[vent_xb.fds.txt](https://github.com/user-attachments/files/16873975/vent_xb.fds.txt)
.

**Comment by mcgratta** [comment]
This is what I see

![image](https://github.com/user-attachments/assets/5f3c19eb-fb7a-459a-b5a4-45cdc2319755)

**Comment by gforney** [comment]
well that is  a mystery, this is what I get.  what version of smokeview are you using - smokeview -v
![vent_db_s0000](https://github.com/user-attachments/assets/f258682e-fcb1-4f07-b580-11c65e716826)

**Comment by mcgratta** [comment]
![image](https://github.com/user-attachments/assets/06312514-6011-4f65-afbf-2b023489449e)

**Comment by mcgratta** [comment]
Should be fixed in the sense that `MB` and `DB` should produce the same behavior in Smokeview.
