### ISSUE TITLE
two mesh solid phase only case fails in debug

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#13426]
This case fails in debug but not in release.  If you comment out one of the MESH lines or remove the SOLID_PHASE_ONLY it runs

It fails in EXCHANGE_DIVERGENCE_INFO.  PSUM keeps growing over time and hits 1.4E308 and overflows. With SOLID_PHASE_ONLY should we just not bother calling this routine?

&HEAD CHID='test', /
&TIME DT=1., T_END=3000.0 /
&DUMP NFRAMES=3000/
&MISC SOLID_PHASE_ONLY=.TRUE., TMPA=27., /
&MESH ID='MESH', IJK=3,3,3, XB=0.,0.3,0.,0.3,0.,0.3, /
&MESH ID='MESH', IJK=3,3,3, XB=0.6,0.9,0.,0.3,0.,0.3, /

**Comment by mcgratta** [comment]
Probably not, but I should fix this nonetheless.

**Comment by mcgratta** [comment]
Should be fixed. We don't need to call this routine, but I cleaned it up anyway.
