### ISSUE TITLE
MAXIMUM PRESSURE AND VELOCITY ERRORS

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13421]
### Discussed in https://github.com/firemodels/fds/discussions/13420

<div type='discussions-op-text'>

<sup>Originally posted by **MarioCruzM** September 10, 2024</sup>
So,  I'm trying to establish a reaction for heavy fuel oil (HFO) pyrolisis. I'm working on Pyrosim and so far I have all the inputs for the reaction, Nonetheless, when I try to run the simple simulation, I get the error **forrtl: severe (157): Program Exception - access violation**. In the model I'm uploading I do have sprinklers and I know this error can come from a bad input on the sprinklers, but I've tried running the simulation without the sprinklers and I get the same error. I even copied the formula only into an old model that I know works without any problem but I got the same error, so I'm pretty confident that something is going on with the reaction inputs, so far I haven't been able to find this error.

FYI: for this simulation, I'm assuming a formula of C20H2.30 this formula came from an elemental analysis, which established the proportions of carbon to be 88.98 and H 10.25, I then simplified this formula to C20 because that's the average length of hydrocarbons on HFO. I've also tried simplifying the formula to C1H0.1152 (I read that using a heavy molecular weight can cause problems) but I did get the same error.

I know it's a very specific case so I really appreciate anyone's help.
[TEST_HFO.zip](https://github.com/user-attachments/files/16950441/TEST_HFO.zip)
</div>

**Comment by mcgratta** [comment]
Jason, this has something to do with aerosols. First, I don't know if `WATER VAPOR` can be an aerosol, but second, the code fails evaluating the Cunningham expression.

**Comment by drjfloyd** [comment]
The chemical formula of C20H2 is non-sensical.  Fuel oils have chemical formulas where C:H is ~1:2.  Carbon atoms have four bonding sites and in a carbon-carbon single bond chain that leaves two bond sites per carbon for hydrogen. I suspect your elemental analysis was reported on a mass basis.  88/12 = 7.3 atoms of C to 10.25 atoms of H or C:H of 1:1.4 (so you have some double bonded and/or aromatic compounds).


The file attached is not an FDS input file.

**Comment by drjfloyd** [comment]
never mind I see in the discussion a second file was given.

**Comment by drjfloyd** [comment]
Setting WATER VAPOR as an aerosol invokes the vapor condensation model. In this case though the ambient conditions are such that you are probably not going to have significant water vapor condenstation.

**Comment by drjfloyd** [comment]
The error is there is no MEAN_DIAMETER specfified. We are missing an error trap for this. I'll add one.

**Comment by MarioCruzM** [comment]
Ok, so I remade the stoichiometry of the formula considering the elemental analysis was indeed in mass basis and entered the mean diameter of the soot, and the simulation ran without any problem. Thank you for the help.
