### ISSUE TITLE
Simulation results for 'NIST NRC Transient Combustibles' Obstruction defined wood crib

### ISSUE THREAD

**Issue by donish-getstand** [firemodels/fds#13430]
Hi All,

I am trying to follow along the validation of pine cribs (FDS 6.9.1) using two modalities to construct the crib: [Particles](https://github.com/firemodels/fds/blob/8d17db8206cb2308a3e5629fd7ffb4f7a88c4d98/Validation/NIST_NRC_Transient_Combustibles/FDS_Input_Files/crib_1x1x1_2cm.fds) or [Obstructions](https://github.com/firemodels/fds/blob/8d17db8206cb2308a3e5629fd7ffb4f7a88c4d98/Validation/NIST_NRC_Transient_Combustibles/FDS_Input_Files/crib_1x1x1_2cm_obst.fds). I am noticing that the particle-defined model tends to underestimate the HRR when compared to the [NIST experimental results](https://www.nist.gov/el/fcd/multiple-item-transient-combustion-calorimetry/test13woodcribr1):
<img width="514" alt="image" src="https://github.com/user-attachments/assets/556baf47-c6df-40dc-a46e-989829bb568e">

I was wondering if you guys had the full s2e simulation results for the "Obstructions" defined wood crib? I amcurious to see how the HRR will evolve with time e.g. if it will under or over estimate the experimental results. I know the particle defined data is displayed in the FDS Validation Guide:
<img width="471" alt="image" src="https://github.com/user-attachments/assets/3d11198f-c860-4a4b-9b66-816e2dcde5ff">

**Comment by mcgratta** [comment]
What is `s2e`? In any event, the FDS GitHub repository has the input files that we use for this validation case. Note that we show results at different grid resolutions to emphasize that these results are mesh dependent and can only produce a very approximate estimate of the burning rate of a real crib. If you are interested in pursuing this subject, I would prefer that you clone the GitHub fds repository and compile the code yourself. These types of simulations are an area of active research and both the code and input files are evolving.

**Comment by donish-getstand** [comment]
My apologies, s2e = start-to-end. But yes, I have compiled the code and I am running the input files (see plot above). A limitating factor on my side is computing power so I was curious if you had the results for the 2cm-obstruction case so that I may begin to model any future studies based on how the behavior of the particle vs obstruction definitions affect the fire dynamics (over/under estimates of the experimental results). Very interesting work!

**Comment by mcgratta** [comment]
We did not do the cribs with obstructions.

**Comment by donish-getstand** [comment]
Thanks for the feedback Kevin, I'll close out this ticket!
