### ISSUE TITLE
forrtl: severe (168): Program Exception - illegal instruction

### ISSUE THREAD

**Issue by Erique87** [firemodels/fds#13445]
Hey there

i just installed FDS 6.9.1-0 on Ubuntu 24.04.01 Server, including editing .bashrc.

When i type fds i get:

>  Fire Dynamics Simulator
>
> Current Date     : September 19, 2024  10:24:28
 Revision         : FDS-6.9.1-0-g889da6a-release
 Revision Date    : Sun Apr 7 17:05:06 2024 -0400
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
 Compilation Date : Apr 09, 2024 13:24:51
>
>
 >MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Linux* OS
>
 >Consult FDS Users Guide Chapter, Running FDS, for further instructions.

but when i try to start a simple fds File:

![image](https://github.com/user-attachments/assets/fa0888e0-2c7b-43dd-8cb9-287f16c1731d)

Do you have any idea why this happens? Thanks a lot in Advance!

Eric

**Comment by Felipe-Rafael-Rosa** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by marcosvanella** [comment]
Did you logout and back in to source the fds and smv startup files?

**Comment by marcosvanella** [comment]
Ok, can you post your test.fds file?

**Comment by Erique87** [comment]
`&HEAD CHID='job1', TITLE='job1' /

&MESH XB= 0, 3, 0, 4, 0, 3, IJK= 30, 40, 30 /

&TIME T_END=60. /
&DUMP NFRAMES=60 /

&VENT XB= 1, 2, 4, 4, 0, 2, SURF_ID='OPEN' / door
&VENT XB= 3, 3, 2, 3, 1, 2, SURF_ID='OPEN' / window

&REAC FUEL = 'PROPANE'
&OBST XB= 1, 2, 1.5, 2.5, 0, 0.5, COLOR='RED', SURF_ID='fire1' /
&SURF ID='fire1', HRRPUA=250 /

&DEVC ID='T air 1', XYZ=1, 2, 2.8, QUANTITY='TEMPERATURE' /
&SLCF PBY = 2, QUANTITY='TEMPERATURE'/

&TAIL /`

**Comment by Erique87** [comment]
I appreciate your help :) this happend:

![image](https://github.com/user-attachments/assets/28d6b2c8-4bed-4f0d-95ae-11b3f70acd1a)

looks fine to me

**Comment by marcosvanella** [comment]
Ok, try the mpi test program (it is also located in XX/INTEL/bin):

$mpirun -n 4 test_mpi

**Comment by Erique87** [comment]
![image](https://github.com/user-attachments/assets/01e2df71-6bac-4fe4-b8ca-d6a50ad318d6)

**Comment by marcosvanella** [comment]
Seems there is an issue with the intel mpi library and your system. Try the nightly bundle here that uses a newer impi lib:

https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST

**Comment by Erique87** [comment]
sadly, same result....this time Debian as OS
![image](https://github.com/user-attachments/assets/d5de3070-f9af-4d69-9e02-9ac52ee114a0)

but i found the solution. I did use virtualized Linux (Promox Host). If i use virtualized CPUs the error occured. If i use "Host" as CPU Type i runs perfectly smooth. 

Im really sorry for the time you've spend. Thanks a lot for your help!

**Comment by marcosvanella** [comment]
Ok Eric, good to hear. I'll close this now.
