### ISSUE TITLE
AST (devc vs. statistic vs boundary quantity)  ((#13357))

### ISSUE THREAD

**Issue by BastianStahra** [firemodels/fds#13453]
**Describe the bug**
Dear Kevin, please see issue #13357. I don't know how to reopen the old issue so I opened a new one with the same topic. We simulated some testcases in the meantime. I posted them below.

I think I got your point. I understand the different "behaviour" of the AST due to different T_END because of T_END/1000. I also get that you deal with devc, statistic_devc and BC in a different way.

But when I look at the different ways of measuring the AST with point devices, statistic devices and boundary quantity; I see differences in the results of up to 80°C. Is that really in an acceptable range for you? When looking at the same quantity of the same simulation? 

In addition to that there is the T_End/1000 point. In sum this could lead to differences of up to more than 100°C in the testcase when looking at the point devices for very long T_END   

FH0011 - T_END = 300
FH0013 - T-END = 10.000

FH0011 - T_END = 300
![Flame_FH0011_AST](https://github.com/user-attachments/assets/a9110689-9c61-4261-933b-997b8713ab90)

![AST_SOLID_AST_01_MAX 2](https://github.com/user-attachments/assets/ca5717ce-a91f-4fa4-8b33-713385ce2507)

FH0013 - T-END = 10.000
![Flame_FH0013_AST01](https://github.com/user-attachments/assets/1f4a2f16-bd0d-44d3-86d4-7263a2b8a587)

FH0013 - T-END = 10.000
[Flame_FH0013.txt](https://github.com/user-attachments/files/17089481/Flame_FH0013.txt)

FH0011 - T_END = 300
[Flame_FH0011.txt](https://github.com/user-attachments/files/17089482/Flame_FH0011.txt)

**Comment by drjfloyd** [comment]
These are not equivalent outputs.

DT_DEVC defaults to (T_END-T_BEGIN)/1000.  
DT_BNDF defaults to (T_END-T_BEGIN)/500
 
You are not comparing the same output intervals. Set the same DT_DEVC and DT_BNDF for both cases and you should see the same results.
