### ISSUE TITLE
MINIMUM_ZONE_VOLUME sets some wall temperatures to ambient temperature

### ISSUE THREAD

**Issue by IFAB-AS** [firemodels/fds#13469]
Hello,
we have a bus model with PRESSURE ZONES. In this model (and many others in the last years) we used the MINIMUM_ZONE_VOLUME feature to get around filling each zone individually.
To my knowledge, this features uses the surrounding materials to fill in the void spaces. My simplified bus has basically three materials (aluminium and two combustible materials), each of them will heat up individually if exposed to heat. If I use the MINIMUM_ZONE_VOLUME, some of the walls will stay at the ambient temperature (20 °C) as can be seen in this image:

Ceiling of the bus:
![grafik](https://github.com/user-attachments/assets/df6ce310-e364-4b36-ad07-6d6af30b6513)
Temperatures at the ceiling after 300 s:
![grafik](https://github.com/user-attachments/assets/7a41e200-cca5-480e-8639-5b77429984d2)

(Tested with FDS 6.9.1)

**Comment by mcgratta** [comment]
I need a simplified case to diagnose the problem. The filling algorithm blocks the interior cells that make up the ZONE. It should not reassign a boundary condition for the exterior of the ZONE.

**Comment by IFAB-AS** [comment]
In my 2nd post there is a simplified fds file for the roof of the bus, or do you need an even simpler file? The image in the first post shows the wall temperatures with no transparency, if I allow some transparency I can see heat up the material at the same positions as the ambient materials. So FDS creates two blocks there, one for a material that heats up and one that stays at ambient temperature.

**Comment by mcgratta** [comment]
This is what I see

![image](https://github.com/user-attachments/assets/246c5d91-cc55-4c87-83a8-fe4c7305f3e3)

**Comment by IFAB-AS** [comment]
Smokeview does look correct. The issue might not be with FDS/Smokeview but with the Pyrosim Results view than. I will send the example to Thunderhead.

**Comment by bwklein** [comment]
We are taking a look at this issue in our Results Viewer.

**Comment by mcgratta** [comment]
I'll take it! Thanks, Charlie.
