### ISSUE TITLE
Evaporation rates at simulation start

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#13464]
At simulation start if we have a pool and are not DNS, then in wall.f90 we have:

      SELECT CASE(SF%GEOMETRY)
         CASE DEFAULT         ; SHERWOOD = 0.037_EB*SC_FILM**ONTH*RE_L**0.8_EB
         CASE(SURF_SPHERICAL) ; SHERWOOD = 2._EB + 0.6_EB*SC_FILM**ONTH*SQRT(RE_L)
      END SELECT
      H_MASS   = SHERWOOD*D_FILM/LENGTH_SCALE

With velocities ~1 mm/s or so for the random noise the flat plate H_MASS winds up an order of magnitude or more below the resolvable H_MASS just using 2._EB*D_FILM*RDX.  For a sphere we can't drop below 2 (which would basically give back the DNS value). Should H_MASS be:

H_MASS = MAX(H_MASS_DNS,SHERWOOD*D_FILM/LENGTH_SCALE)

This would keep the evaporation rates from going to zero when the velocity is near zero and may help with getting pool fires to heat up in manner more like we see in experiments.  For a spherical surface, as long as the length scale (which is set to the diameter) is less than the grid size we would still have the correlation value as that would give 1/length scale > RDX. 

This could be done as:

      SELECT CASE(SF%GEOMETRY)
         CASE DEFAULT         ; SHERWOOD = 0.037_EB*SC_FILM**ONTH*RE_L**0.8_EB
         CASE(SURF_SPHERICAL) ; SHERWOOD = 2._EB + 0.6_EB*SC_FILM**ONTH*SQRT(RE_L)
      END SELECT
      SELECT CASE(ABS(IOR))
         CASE(1); H_MASS = 2._EB*D_FILM*RDX(IIG)
         CASE(2); H_MASS = 2._EB*D_FILM*RDY(JJG)
         CASE(3); H_MASS = 2._EB*D_FILM*RDZ(KKG)
      END SELECT
      H_MASS   = MAX(H_MASS,SHERWOOD*D_FILM/LENGTH_SCALE)

**Comment by mcgratta** [comment]
Good idea, and just like what we do for heat. I suggest we call it `H_MASS_DNS`. Even though that is another variable, it helps us better understand what is going on.
