### ISSUE TITLE
thouse5 seg faulting when run with debug fds

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#13478]
running debug fds on spark using revision FDS-6.9.1-880-g51a28850b on the smv/Verification/Visualization/thouse5.fds results in this crash near the first time step.  Other cases except for one similiar to thouse5 did not crash

 Time Step:       1, Simulation Time:   0.16042 s
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
libc.so.6          0000149566854DB0  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000003177B1B  wall_routines_mp_        2775  wall.f90
fds_impi_intel_li  0000000003050F8A  wall_routines_mp_         107  wall.f90
fds_impi_intel_li  00000000041FAEB3  MAIN__                    847  main.f90

**Comment by drjfloyd** [comment]
Might be me. I'll take a look.

**Comment by drjfloyd** [comment]
Moved a variable initialization.  Case is running for me now.  Glad you caught this before firebot started again.

**Comment by gforney** [comment]
that was quick.  thanks.  thank smokebot :-)
