### ISSUE TITLE
Saving numerical CTRL results to CSV

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#13501]
According to the FDS User Guide (section 18.5 in version 6.9.1), the status of `CTRL` calculations is saved to the CHID_ctrl.csv output file, except for a `CTRL` of type `CUSTOM`, where the value of the `RAMP` function is saved.

As an enhancement request, would it not make sense to save numerical results for all the other `CTRL` types that have numerical results? For example, `EXP`, `LOG`, `COS`, etc. (There are some types that are clearly intended to have logical-type inputs and logical-type output: `ALL`, `ANY`, etc.)

As far as I can tell, even `CUSTOM` types are not saved as numerical values. When I run @mcgratta 's example here: https://github.com/firemodels/fds/issues/13234#issuecomment-2379964349 with
```
[...]
&RAMP ID='HRRPUA RAMP', T=0, F=0, CTRL_ID_DEP='HRRPUA CTRL' /
&DEVC ID='TIMER', XYZ=1,1,1, QUANTITY='TIME' /
&CTRL ID='HRR', FUNCTION_TYPE='CUSTOM', INPUT_ID='TIMER', RAMP_ID='HRR' /
&DEVC ID='Fire Area', QUANTITY='HRRPUA', QUANTITY_RANGE=0.01,100000.0, XB=0,8,0,8,0,1, SURF_ID='FIRE', SPATIAL_STATISTIC='SURFACE AREA' /
&CTRL ID='HRRPUA CTRL', FUNCTION_TYPE='DIVIDE', INPUT_ID='HRR','Fire Area' /

&RAMP ID='HRR', T=  0., F=    0.0 /
&RAMP ID='HRR', T= 10., F=  100.0 /
[...]
```
then the resulting file `spread_ctrl.csv` starts like this:
```
s,status,status
Time,"HRR","HRRPUA CTRL"
 0.0000000E+000,-1,-1
 3.1932995E-001, 1,-1
 4.7899494E-001, 1,-1
```

I can see that saving numerical results for a simple ramp evaluation might not always be desirable -- it takes more disk space that a simple status calculation. Is there a way to force saving of numerical results? -- I tried to find a way to convert the `CTRL` output into a `DEVC`, but I couldn't work it out.

While I'm thinking about it, why does the status of `HRR` equal -1 at the first record? And what does it mean for the status of `HRRPUA CTRL` to equal -1 throughout the simulation? It is possible that `HRRPUA CTRL` has a division-by-zero error in the first few seconds of simulation, then starts to be reasonable.

**Comment by drjfloyd** [comment]
The text in 18.5 says:

The output value of a numerical control function is defined by a DEVC line with QUANTITY=’CONTROL VALUE’ and CTRL_ID set equal to the ID of the control function....For CUSTOM the output will be the value of the RAMP function, and for TIME_DELAY the value will be the evaluated delay.

The above text is just referring to the DEVC with QUANTITY='CONTROL VALUE'. It does not state anyting about the ctrl.csv output file.  The description of that file is in Section 27.4 and it states that the outputs are just the logical state.

**Comment by obscureed** [comment]
Ah, thanks, you're right.
So how can I request the numerical value of a `CTRL` to be saved somewhere? It feels like I should just set up a `&DEVC` to equal it, but a `&DEVC` seems to need coordinates and spatial/temporal values.

**Comment by obscureed** [comment]
Sorry, it's probably explained immediately before the lines of the User Guide we were discussing. I'll try
```
&DEVC QUANTITY='CONTROL VALUE', CTRL_ID='HRRPUA CTRL', XYZ=1,1,1 ID='devc_hrrpua' /
```
and report back.

**Comment by drjfloyd** [comment]
Yes, that line should output the evaluated value of the ramp.  You have pointed out; however, that we should be a more complete here in discussing outputs and refer to the sections discussing ctrl.csv and devc_ctrl_log csv files here.

**Comment by obscureed** [comment]
Yes, that line works. However, it seems to have temporal averaging (for example, see below, with a comparison to 
```
&DEVC XB=1.0,7.0,1.0,7.0,0.0,0.0, QUANTITY='HRRPUA', SPATIAL_STATISTIC='MAX', ID='hrrpua_max' /
```
The output is identical if I try:
```
&DEVC QUANTITY='CONTROL VALUE', CTRL_ID='HRRPUA CTRL', XYZ=1,1,1 ID='devc_hrrpua_instant' TEMPORAL_STATISTIC='INSTANT VALUE' /
```
Is there a way to disable the averaging?

I'm not sure whether there is anything badly wrong with the User Guide here -- I just wasn't reading it very well.

![g__latest](https://github.com/user-attachments/assets/a19ee1f9-f285-467f-b2ff-499e8bad0554)

**Comment by drjfloyd** [comment]
CONTROL VALUE and CONTROL have a default TEMPORAL_STATISIC of 'INSTANT VALUE'.
