### ISSUE TITLE
HRR incorrect when RAMP with scientific notation times

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#13507]
[S3_17_S3_17.fds.txt](https://github.com/user-attachments/files/17216379/S3_17_S3_17.fds.txt)

**HRR IS ZERO UP TO 100s**
When performed the simulation the the HRR remains to zero until approximately 140s.
If in the RAMP I remove the times specified with the scientific notation, the HRR becomes correct.

**To reproduce**
Run the simulation. I used also the nightly to verify on Linux.

**Expected behavior**
HRR is reproduced correctly if times in the RAMP are replaced with float numbers instead of scientific notation

**Comment by mcgratta** [comment]
I'll run it overnight.

**Comment by drjfloyd** [comment]
Do you have the correct scientific values?  The T and F values in a RAMP are interpolated to a table of 5000 values (this number can be changed) where the time increment is the maximum T/5000 which in your case is 1.4E6/5000 or 280 s.  You maximum time is only 1400 s, is you maximum T supposed to be 1.4E3 instead of 1.3E6?

**Comment by rupole1185** [comment]
Yeah, I confirm this is the case I performed. I haven't tried with T=1.4E3 to be honest.
What is misleading is the fact that with this RAMP the simulation performed smoothly, without warnings, but the HRR was constantly 0 up to 140s approximately.
Maybe a solution could be having a warning about the RAMP behaviour?

**Comment by drjfloyd** [comment]
As discussed in 11.1 of the User Guide, FDS converts the RAMP inputs to a table of values.  The RAMP is interpolated to NUMBER_OF_INTERPOLATION_POINTS entries in a lookup table. With 1.43 million seconds as your end point, the first two table values for your ramp are 0,0 and 285,1.  FDS does not do a linear interpolation between table points. It picks the closet table value. This saves simulation time by not having to constantly compute an interpolation. In your case that means for 285/2 s or 142 s, the closest table value is 0,0. 

If 1.4 million seconds is the correct end point for your ramp, then increase NUMBER_OF_INTERPOLATION_POINTS for the ramp.

**Comment by rupole1185** [comment]
Allright, is it possible to have a warning or something else about it?

*Ruggero Poletto - **Managing director*

*VideoCall*: calendly.com/ruggero-poletto | *Mobile*: +39 378 30 33 133

*NEXT EVENTS we are attending:*

FEMTC <https://www.femtc.com/events/2024> - 18-20 Sept. 2024 | OPENFOAM ITA
- 7-8 Sept. 2024

________________________________________

CFD FEA SERVICE SRL P.IVA 04545570238 - via Borgo Grande 19, 37044 Cologna
Veneta VR

*ATTENTION:*

All information in this e-mail message, as well as any files included, are
intended for the exclusive use of the recipient (s) indicated above /
indicated, and therefore subject to protection pursuant to law no. 675 and
of the Legislative Decree of 30 June 2003 n. 196. Anyone who receives this
message by mistake, is requested to notify the writer of the incorrect
receipt, and proceed with the immediate cancellation of the same from the
system. Your cooperation is appreciated.

*PRIVACY:*

All personal data, including e-mail addresses, are collected and stored
with the sole purpose of carrying out our professional activity towards
you. The privacy law D.Lgs. N. 196 of 30/06/2003 provides in article 7 the
right of the interested party to access their personal data, to request
their correction, updating and deletion, therefore we invite you to report
us in the way you deem most appropriate as provided by Article 7.

**Comment by drjfloyd** [comment]
Added a WARNING for when the spacing between T values is less than [MAX(T)-MIN(T)]/NUMBER_INTERPOLATION_POINTS
