### ISSUE TITLE
Level Set Method Arrival Time output

### ISSUE THREAD

**Issue by nikosuser** [firemodels/fds#13531]
When using the Level Set Method for wildfire spread modelling, I would like to create an arrival time raster to then plot in GIS. This would essentially be a raster with each cell value being the timestep when phi becomes 0. 

I saw that there is a method to convert the Fortran outputs to ASCII for slice files, can that be extended to the level set value outputs? Then it would be easier to write a script to find the arrival time results and convert them to a geospatial raster.

**Comment by ericvmueller** [comment]
Hi Nik,

There general approach would be to use the `TIME OF ARRIVAL` quantity to create an AGL slice. You could then either:

1. extract the values yourself using a Fortran, Matlab, Python, whatever your prefer ... for example, Jonathans [pyfdstools](https://github.com/johodges/pyfdstools) might help you in Python, or... 

2. try out a QGIS plugin I have been developing. It is intended to provide fireline contours (so vector format geospatial data) but you could also convert the values to a raster format using a bit of manipulation. It is [installed](https://github.com/ericvmueller/fds_isochrones/wiki/Installation) similar to qgis2fds and there is a simple [getting started guide](https://github.com/ericvmueller/fds_isochrones/wiki/Getting-Started). 
It's still far from perfect but if you run into issues or have requests just let me know (for example if you really want an option for raster output, either at FDS or some interpolated resolution)

**Comment by nikosuser** [comment]
Thank you greatly, I used the code you referred to to create an asc file based on the outputs (and a sample .asc file for the projection). I can share the code but it is nothing to marvel in terms of elegance or completeness. I will note that it seems the output of the code that makes the contours removes one of the raster columns (input was 126 x 126, output was 125 x 126). I do not know if this is a bug with FDS or the python code but it is not very significant so I will close this issue and if need be I can start another issue on this.
