### ISSUE TITLE
Seemingly incorrect number of heating particles

### ISSUE THREAD

**Issue by matt-s-distefano** [firemodels/fds#13553]
**Describe the bug**
I am creating a fire represented by burning particles, but my total heat release rate has been off from what I was expecting. To simplify the problem, I've reduced the number of particles to 1 (setting N_PARTICLES = 1). However, when I visually inspect, I see two particles in the post-processing view (I am using PyroSim Results Viewer, but I assume the same can be seen in SmokeView). 

I thought this was a glitch, but I checked the HRR for the file and found the value is = 5.32 kW. The particles I define (RADIUS=0.00141), have a spherical surface area of 2.5E-3 m2. Given a HRRPUA of 1.06481E+5 kW/m2, I would expect a total output per particle of 2.662025 kW. Since I am only specifying one particle, I would expect ~2.66 kW of HRR. However, the output 5.32 kW is double that, confirming that there are 2x the number of particles set.

See my code here:

````
! --- Fire Particles ---

&SURF ID='fire_burner', HRRPUA=1.06481E+5, NET_HEAT_FLUX=1.06481E+5, EMISSIVITY=1.0, GEOMETRY='SPHERICAL', RADIUS=0.00141, RAMP_Q = 'fire_HRRPUA_ramp' /
&RAMP ID='fire_HRRPUA_ramp', T=0.0, F=0.0 /  ! No heat release at time 0
&RAMP ID='fire_HRRPUA_ramp', T=5.0, F=0.0 /  
&RAMP ID='fire_HRRPUA_ramp', T=5.1, F=1.0 / ! Full HRRPUA at 5.1 seconds
&RAMP ID='fire_HRRPUA_ramp', T=10, F=1.0 /

&PART ID='fire_burner_particles', MASSLESS=FALSE, STATIC=TRUE, SURF_ID='fire_burner', SAMPLING_FACTOR=1, DRAG_LAW='SPHERE', COLOR='ORANGE', AGE = 600, ADHERE_TO_SOLID = 1 /

! Center Fire particles over Y = 0
&INIT PART_ID='fire_burner_particles',XB=-2, 14,0, 0, 0.01, 0.01, N_PARTICLES=1, PARTICLE_WEIGHT_FACTOR=1 /
````

**To Reproduce**
1. Run the attached FDS file
2. View the output, and you will see 2 of the "fire_burner_particles" even though only one is specified

**Expected behavior**
My expectation was that the number of particles would be = 1, since I set N_PARTICLES = 1, but perhaps I am mistaken in my setup or expectations on the commands here? Any help here is really appreciated!

**Screenshots**
![Screenshot 2024-10-09 at 6 13 37 PM](https://github.com/user-attachments/assets/76644704-dfbe-4190-a239-3c811bda187c)

**Desktop (please complete the following information):**
 - Version: 6.9.1

**Additional context**
[OUT_FILE.txt](https://github.com/user-attachments/files/17318900/OUT_FILE.txt)
[Fire_HRR_Test_Stripped.fds.txt](https://github.com/user-attachments/files/17318932/Fire_HRR_Test_Stripped.fds.txt)

**Comment by drjfloyd** [comment]
Some issue with your INIT line spanning multiple meshes. FDS should apportion N_PARTICLES based on the fraction of the XB in each MESH. As a work around till this is fixed, just set your XB so it is in one mesh.

**Comment by matt-s-distefano** [comment]
Hi, thank you for your response!

Just to make sure I understand, this is a bug that is currently being addressed? Or did I setup the INIT line incorrectly? 

From the User's guide, it seems to imply that the number of particles is automatically refactored per mesh:
![Screenshot 2024-10-09 at 6 45 50 PM](https://github.com/user-attachments/assets/f6c638ae-f4cd-4c0f-b6ed-add2c52bd311)

**Comment by drjfloyd** [comment]
The logic for apportioning N_PARTICLES broke down when the XB volume was zero; however, your input has an issue of sorts as well. Your domain is X=(-2,6) but your XB was -2,14.  The apportioning mulitplies N_PARTICLES by the fraction of the XB volume in the MESH and then takes the nearest integer (i.e. rounding up or down). Just fixing the apportioning to treat XB as a line or plane would mean that with your N_PARTICLES=1 and the XB you defined that there would be 4/14 particles in two meshes and 8/14 particles outside the domain.  No mesh would get a particle in this case if we just took the nearest integer; however, we force one particle to appear in any mesh touched by XB when N_PARTICLES is used. So even fixing the apportionment for the zero volumem your input would still get 2 particles 

In terms of a fix, I think all we want to do is make sure the apportionment calc can deal with lines and planes. I don't think we want to limit our apportioning to the XB volume in the MESH divided by the XB volume in the overall domain. That would mean someone couldn't look to debug an input set by limiting the domain size while still keeping the same particle apportionment in the remaining meshes.  I also don't think we want to not put at least one particle in a mesh to ensure that particles are placed. The guide could use a little expanded discussion to caution against small values of N_PARTICLES when XB extends over multiple meshes. 

For your full case, if you are just looking to get some uniform distribution of heat release in a volume you could use N_PARTICLES_PER cell and just adjust the SURF for the number of cells in your XB.

**Comment by drjfloyd** [comment]
Added some logic to write some WARNING messages for INIT with N_PARTICLES and adjusted the logic for XB to handle line or planes with N_PARTICLES. This will be in the next test bundle which assuming all goes well with nightly build tests will be available tomorrow at https://github.com/firemodels/test_bundles

**Comment by matt-s-distefano** [comment]
Thank you! And I can confirm, adjusting the volume to a nonzero value resulted in correct HRR yield. Appreciate your assistance!
