### ISSUE TITLE
error: INIT 1 XB contains more MESHes than N_PARTICLES

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#13559]
on both linux (spark) and windows running with the latest fds am getting this error
INIT 1 XB contains more MESHes than N_PARTICLES
for smv/WUI/pine_tree.fds and smv/WUI/tree_test2.fds

pine_tree.fds is a 4 mesh case and specifies 2000 particles on the &INIT line
tree_test2.fds is a 1 mesh case and specifies 10 particles on the &INIT line.

ie number of meshes is less than number of particles in both cases.

I haven't' changed either of these cases in a long time. Let me know if I need to make some change in my input files or if I am missing something

**Comment by drjfloyd** [comment]
It is a WARNING not an ERROR I added for a user issue this morning. Seems like I need to adjust the logic some.

**Comment by drjfloyd** [comment]
Used < instead of > in an IF statement.

**Comment by gforney** [comment]
fds is crashing - think initializing mpi .  getting error message (and a traceback)

[unset]: write_line error, fd=-1 buf="cme=abort exitcode=1090959

crashed in MPI_INIT_THREAD_F line 21 init_thread_f08ts.f90

was running tree_test.fds on windows

**Comment by drjfloyd** [comment]
Not sure if that is me. I don't think I touched anything MPI.  I'll take a look.

**Comment by drjfloyd** [comment]
Did you mean tree_test2.fds in smv/Verification/WUI?

I ran it with clean builds of both debug and release with windows and both started time stepping.

**Comment by gforney** [comment]
yes.  maybe I built fds wrong.  I'll clean the fds build directory and try again

**Comment by gforney** [comment]
I was running the case in a different CMD shell than the one where I built fds.  The mpi environment was not set up.  once I initialized the mpi environment with fdsinit.bat (same script run by fds_local.bat) everything worked .  Also the original warning message about number of particles is gone - So I'm closing the issue. thanks.
