### ISSUE TITLE
Duct loss

### ISSUE THREAD

**Issue by AlanZandie** [firemodels/fds#13555]
hello,

I was wondering if there is a way to apply duct loss in FD. Say there is a shaft with a fan on top, I want to simulate a case where the inlet of the fan is defined at the top of the shaft (e.g. 23rd floor) with a flowrate of 8m3/s, with a damper at 1st floor that can only experience 5m3/s due to loss in the duct because of pressure drop. I want to know how to create this condition.
I have tried the HVAC Fan but it seems the loss does not change the flow rate I get at the end of the shaft and it matches exactly to the value at the top shaft.    
Could you please help me with this
thank you

**Comment by drjfloyd** [comment]
If you specify a fixed flow rate, then you will always get that flow rate. If you want the flow rate to change with the loss you need to use a quadratic or user specified fan curve. If you are using something other than a fixed flow rate and not seeing a change with loss, we would need to see a simple input file demonstrating your issue.

**Comment by AlanZandie** [comment]
thank you for your feedback. I think i can see the flow loss now across the shaft.
