### ISSUE TITLE
Inconsistency of a solid evaporating into liquid droplet

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13562]
I'm reworking some input parameters, shifting some `SURFACE` variables to `ONE_D` . When running the debug verification cases, the case `Pyrolysis/ice_cube.fds` failed with an array out-of-bounds error. In a nutshell, We have a `MATL` that generates a liquid droplet
```
&PART ID='WATER DROP',SPEC_ID='WATER VAPOR',DIAMETER=1000/

&MATL ID='ICE',
      PART_ID='WATER DROP',
      DENSITY = 1000.,
      SPECIFIC_HEAT = 4.186,
      CONDUCTIVITY=0.2,
      NU_PART = 1,
      REFERENCE_TEMPERATURE = 0,
      PYROLYSIS_RANGE = 5,
      HEAT_OF_REACTION = 334/
```
But in `read.f90`, there is code that says to create a `ONE_D` data type for these droplets:
```
      DO NN=1,MAX_LPC
         IF (PART_ID(NN,NR)/='null') THEN
            ML%N_LPC(NR) = ML%N_LPC(NR) + 1
            LAGRANGIAN_PARTICLE_CLASS(NN)%INCLUDE_BOUNDARY_ONE_D_TYPE = .TRUE.
         ENDIF
      ENDDO
```
When the `ONE_D` datatype was being initialized, there was no `MATL` but somehow `N_MATL` was 1 for the `SURFACE` assigned to the droplet. Was this logic of assigning a `ONE_D` type intended for solid particles only?

**Comment by mcgratta** [comment]
I made this change
```
      DO NN=1,N_LAGRANGIAN_CLASSES
         LPC => LAGRANGIAN_PARTICLE_CLASS(NN)
         IF (PART_ID(NN,NR)/='null' .AND. LPC%SOLID_PARTICLE) THEN
            ML%N_LPC(NR) = ML%N_LPC(NR) + 1
            LPC%INCLUDE_BOUNDARY_ONE_D_TYPE = .TRUE.
         ENDIF
      ENDDO
```
and I am testing it. Do you foresee any issues?

**Comment by drjfloyd** [comment]
I"ll have to take a look. Been a long time since I coded that up.

**Comment by drjfloyd** [comment]
Is this something that is just failing with your version of the source?

**Comment by mcgratta** [comment]
OK, I have to run the verification cases anyway. My fix passed the debug round.

Yes, this is failing because I am shifting `INTERNAL_RADIATION` from `SF` to `ONE_D`. This is related to the issue where we are getting different results in `HT3D` because `SURF` parameters are not being passed to internal obstructions. I just happened to notice that in the `ice_cube` case, a `ONE_D` data structure was being created with no `MATL`s at all.

**Comment by drjfloyd** [comment]
Looking into how we init particles in part and how we setup the LPC%INCLUDE flags in read, I think your fix is correct.

**Comment by mcgratta** [comment]
I think so too because we cannot do `ONE_D` heat transfer on a particle that has no `MATL_ID`.

**Comment by mcgratta** [comment]
OK, things are working. In the `ice_cube` case, we were creating a `ONE_D` data structure but it did no harm. We now do not, so there is less of a risk of having a problem.
