### ISSUE TITLE
configuration running on windows but not on linux

### ISSUE THREAD

**Issue by 3dfirelab** [firemodels/fds#13576]
**Describe the bug**
The attached configuration is running on the 6.8.0 version on a windows machine 
but failed on a linux machine with version FDS-6.8.0-0-g886e009-release
On windows the simulation require 95GB that are also made available on the linux machine.

The confid file is here: [Road_section1_no_treatment_mpi.fds](https://github.com/user-attachments/files/17362611/Road_section1_no_treatment_mpi.fds.txt)
It is empty. 

**error message**:  
The error message is the following
```
 Reading FDS input file ...


 Fire Dynamics Simulator

 Current Date     : October 14, 2024  12:26:18
 Revision         : FDS-6.8.0-0-g886e009-release
 Revision Date    : Tue Apr 18 07:06:40 2023 -0400
 Compiler         : ifort version 2021.7.1
 Compilation Date : Apr 18, 2023 15:20:17

 MPI Enabled;    Number of MPI Processes:      44
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.12 for Linux* OS


 Job TITLE        : 
 Job ID string    : Road_section1_no_treatment

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libc.so.6          00007F564565B050  Unknown               Unknown  Unknown
fds                0000000006D848A6  Unknown               Unknown  Unknown
fds                0000000006D70077  Unknown               Unknown  Unknown
fds                0000000006AB7C99  Unknown               Unknown  Unknown
fds                000000000040A71D  Unknown               Unknown  Unknown
libc.so.6          00007F564564624A  Unknown               Unknown  Unknown
libc.so.6          00007F5645646305  __libc_start_main     Unknown  Unknown
fds                000000000040A636  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 1987066 RUNNING AT andromeda
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
...

```

**Comment by drjfloyd** [comment]
Have you set your stacksize to unlimited?

ulimit -s unlimited

**Comment by 3dfirelab** [comment]
and of course no...
thanks a lot

**Comment by 3dfirelab** [comment]
`ulimit -s unlimited` solved the problem for the very light configuration of the first attached file

In the full configuration the problem came back. 
[Road_section1_no_treatment.fds.txt](https://github.com/user-attachments/files/17375041/Road_section1_no_treatment.fds.txt)
The simulation started but never get to the first time step. 

This same configuration file work on a windows machine with same available RAM.

below is my submission file if somehow I do a mistake here
```
#!/bin/bash
#
#SBATCH --job-name=test
#SBATCH --ntasks=44
#SBATCH --cpus-per-task=1
#SBATCH -p prod
#SBATCH --time 1440
#SBATCH --mem 120G

ulimit -s unlimited

source /opt/intel/oneapi/setvars.sh 
export OMP_NUM_THREADS=1
cd $SLURM_SUBMIT_DIR
mpirun -np $SLURM_NTASKS /opt/FDS/FDS6.8/bin/fds Road_section1_no_treatment.fds
```

**Comment by drjfloyd** [comment]
try without the --mem or with more mem.  This case runs for me when I don't put in a memory limit.

**Comment by 3dfirelab** [comment]
with 200G it is running. 
I was told it was running with 95G on windows.
Does FDS need more memory when loading the domain then when the integration?
anyway, problem solved on my side
thanks , especially that this was a very "environment related" question

**Comment by drjfloyd** [comment]
If you were just using windows task manager, I don't know how well that reflects transient stack needs vs. fixed allocation memory requirements.
