### ISSUE TITLE
Add direction of tunnel for TUNNEL_PRECONDITIONER to User Guide

### ISSUE THREAD

**Issue by IFAB-AS** [firemodels/fds#13588]
Hello,

according to [this Google group discussion,](https://groups.google.com/g/fds-smv/c/42TWgtnU6gQ/m/nhp3XHNIDQAJ) the TUNNEL_PRECONDITIONER needs a tunnel that spans into the x direction. Can you add this info to the user guide into the "Pressure Considerations in Long Tunnels" chapter?

**Comment by drjfloyd** [comment]
Good suggestion.
