### ISSUE TITLE
FDS ERROR 

### ISSUE THREAD

**Issue by glimentin** [firemodels/fds#13586]
Hi, I'm making the code according to the instructions (https://firedynamics.github.io/LectureFireSimulation/content/modelling/06_heat_transfer/04_ht3d_example.html#setup ) for heat transfer. the error appeared after adding HT3D=.TRUE. FDS  version  6.9.1

code: 

&HEAD CHID='Example', TITLE='Example' /
&TIME T_END=3600, DT=5 /
&MISC SOLID_PHASE_ONLY=.TRUE., BNDF_DEFAULT=.FALSE. /
&DUMP DT_DEVC=10 /
&RADI RADIATION=.FALSE. /

&MESH IJK=60,10,25, XB=-0.6,0.6, -0.1,0.1, 0.0,0.5 /

&VENT MB='ZMAX',SURF_ID='OPEN' /
&VENT MB='YMIN',SURF_ID='OPEN' /
&VENT MB='YMAX',SURF_ID='OPEN' /
&VENT MB='XMIN',SURF_ID='OPEN' /
&VENT MB='XMAX',SURF_ID='OPEN' /

&OBST XB=-0.60,-0.60, -0.10,-0.08, 0.18,0.20, SURF_ID='ADIABATIC', HT3D=.TRUE., MATL_ID='STEEL' /
&OBST XB=-0.60,-0.60, 0.08, 0.10, 0.18,0.20, SURF_ID='ADIABATIC', HT3D=.TRUE., MATL_ID='STEEL' /
&OBST XB=-0.60,-0.58, -0.10, 0.10, 0.18,0.20, SURF_ID='ADIABATIC', HT3D=.TRUE., MATL_ID='STEEL' /
&OBST XB=0.58, 0.60, -0.10, 0.10, 0.18,0.20, SURF_ID='ADIABATIC', HT3D=.TRUE., MATL_ID='STEEL' /
&OBST XB=-0.58,-0.20, -0.08,0.08, 0.18,0.46, SURF_ID='STEEL BEAM', HT3D=.TRUE., MATL_ID='STEEL' /
&OBST XB=-0.20, 0.20, -0.08,0.08, 0.18,0.46, SURF_ID='COPPER BEAM', HT3D=.TRUE., MATL_ID='COPPER' /
&OBST XB=0.20, 0.58, -0.08,0.08, 0.18,0.46, SURF_ID='CONCRETE BEAM', HT3D=.TRUE., MATL_ID='CONCRETE' /

## Heater surface
&SURF ID='HOT STEEL', COLOR='RED', TMP_FRONT=800/

&VENT XB = -0.44,-0.36, -0.04,0.04, 0.18,0.18, SURF_ID='HOT STEEL' /
&VENT XB = -0.04, 0.04, -0.04,0.04, 0.18,0.18, SURF_ID='HOT STEEL' /
&VENT XB =  0.44, 0.36, -0.04,0.04, 0.18,0.18, SURF_ID='HOT STEEL' /

&SURF ID='ADIABATIC', COLOR='BLACK', ADIABATIC=.TRUE.,  HT3D=.TRUE. /

&MATL ID='STEEL', SPECIFIC_HEAT= 0.45, CONDUCTIVITY= 45.8, DENSITY= 7850.0 /
&MATL ID='COPPER', SPECIFIC_HEAT=0.385, CONDUCTIVITY=401.0, DENSITY=8960.0 /
&MATL ID='CONCRETE', SPECIFIC_HEAT=0.75, CONDUCTIVITY=1.6, DENSITY=2400.0 /

&SURF ID= 'STEEL BEAM', RGB= 68,68,68 TRANSPARENCY= 0.5,  HT3D=.TRUE., ADIABATIC= .TRUE./
&SURF ID= 'COPPER BEAM', RGB= 190,100,0 TRANSPARENCY= 0.5,  HT3D=.TRUE., ADIABATIC= .TRUE./
&SURF ID= 'CONCRETE BEAM', COLOR= 'GRAY', TRANSPARENCY= 0.5,  HT3D=.TRUE., ADIABATIC= .TRUE./

&TAIL

ERROR(101): Problem with OBST number 1, line number 17 (MPI Process: 0, CHID: Example)

ERROR: FDS was improperly set-up - FDS stopped (CHID: Example)

**Comment by drjfloyd** [comment]
From the document overview chapter of that webpage:  

The lecture notes and exercises are designed for FDS version 6.7.5, and thus may not be valid / reproducible for other versions.

You need to consult the FDS 6.9.1 User's Guide and make sure you are using inputs appropriate for that version of FDS.
