### ISSUE TITLE
Solid HT3D cells after complete decomposition

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13597]
### Discussed in https://github.com/firemodels/fds/discussions/13587

<div type='discussions-op-text'>

<sup>Originally posted by **Vojta-Salek** October 17, 2024</sup>
Dear FDS community,

Do you have any insights into what happens to a solid non-charring pyrolyzing cell in `HT3D='T'` mode after all the material has decomposed? Assume `BURN_AWAY` is not specified, as it is currently unavailable for `HT3D`.

For the default 1D heat conduction: "_If `BURN_AWAY` is not prescribed, the surface temperature is set to `TMP_GAS_BACK`, convective heat flux to zero and burning rate to zero_" (User’s Guide Sec. 8.3.8).  Does the same happen in `HT3D` that `TMP_GAS_BACK` is assigned to all surfaces? If so, I assume the correct `BACKING` is applied for all surfaces (each surface being either exposed to gas phase or to a neighboring `HT3D` solid cell according to the limitations in Sec. 8.4.2).

In the very simple FDS case provided below, we can observe, for instance, negative surface temperatures (how?) or extremely high surface temperatures (which seems expected for an object of nearly zero density). However, these surface temperatures in technically "dead" cells might significantly influence other parts of the computational domain (due to radiation), even if convective heat flux is artificially set to zero. It has also caught my attention, that although the proposed model is symmetrical, surface temperatures of “dead” cells seem random (see [Smokeview screen](https://github.com/Vojta-Salek/Pictures/blob/main/1_Symmetrical_surface.PNG)).

[Negative_temperature.txt](https://github.com/user-attachments/files/17405429/Negative_temperature.txt)
[Negative_temperature_devc.csv](https://github.com/user-attachments/files/17405330/Negative_temperature_devc.csv)
[Display_plot.py.txt](https://github.com/user-attachments/files/17405915/Display_plot.py.txt) (Python for quick data plotting)

![1_Negative_tempearature](https://github.com/user-attachments/assets/b0de4d3b-e60b-4b60-87b3-fece54fc9e8a)

Could someone please explain a bit more about what is actually happening? What effect does this have on neighboring solid cells? Does this behavior compromise calculations once “dead” cells occur in domain, or is it more of an issue with the visualization of surface temperatures? I am aware that `HT3D` is still in development, therefore I'm not submitting an issue, but rather seeking clarification on the current behavior of "dead" material.

Thank you in advance for any insights into this topic!

Sincerely,

Vojtěch
</div>

**Comment by mcgratta** [comment]
This case should not be allowed. The `HT3D` routine does not work with shrinking, swelling, or disappearing obstructions. The 3D heat transfer is based on the initial topology of the group of obstructions. This topology cannot conform to the shrinking object. If you want to do pyrolysis and 3D heat conduction, you must limit yourself to a solid with a residue that maintains the original shape and size.  For example, if the initial density is 500 kg/m3 (like wood) and the char yield is 25%, make the char density 125 kg/m3. If you want to model PMMA and similar for a shape that is more complicated than a simple rectilinear solid with a single `THICKNESS`, use the `VARIABLE_THICKNESS` option.

**Comment by Vojta-Salek** [comment]
Thank you for the reply. If needed, I think I can provide a simple case, where the temperature drop below zero will be more significant and permanent.

Wouldn't it make sense to use `ALLOW_SHRINKING=F` as an default flag in `HT3D`? 

Also, for very little charring materials like PMMA, does it make sense to prescribe char yield for instance 2 % and density equal to 0.02 * initial density? It seems like it solves the problem for the test case in this issue. This may even work for non-charring materials, to give them artificially 1 % char yield with the corresponding char density and other thermal properties equal to the virgin material.

**Comment by mcgratta** [comment]
In your case, the temperature drop is caused by the re-noding of the interior grid as the material burns. The 3D algorithm can only work if the internal "mesh" of 1D conduction paths is maintained. If I were to set `ALLOW_SHRINKING=F` in your case, the internal cells still decrease to zero mass and eventually the case will produce nonsense results and/or crash. The artificial char idea has problems because as the material burns, a fictitious insulation layer forms that shields the pyrolysis front from the external heat.

**Comment by Vojta-Salek** [comment]
Thank you for the explanation of `ALLOW_SHRINKING` .

I am aware of the issues related to artificial char formation. However, I assume the impact of the insulating layer will not be too significant for ~1 cm solid boxes, especially if the boxes are either individual or grouped in small numbers, without forming a thick, continuous layer of material. While I don't see a better solution at the moment, it is something that still needs to be considered when evaluating the results. On first glance, the simulations appear much more stable.

**Comment by Vojta-Salek** [comment]
I apologize for the late response. I’d like to suggest adding a note to Section 8.4.2 (Limitations) of the User's Guide, such as: "_The `HT3D` routine does not work with shrinking, swelling, or disappearing obstructions._" This seems like a very significant limitation—perhaps even the most critical one. It could be merged with point 5, which already mentions the unavailability of `BURN_AWAY`.

**Comment by mcgratta** [comment]
I added [this text](https://github.com/firemodels/fds/pull/13911/files).
