### ISSUE TITLE
Problem with SURF 

### ISSUE THREAD

**Issue by glimentin** [firemodels/fds#13599]
hello, the error appears for every SURF except &SURF ID='HOT STEEL'

Problem with SURF number 2, line number 29 (CHID: Example)

ERROR: FDS was improperly set-up - FDS stopped (CHID: Example)

&HEAD CHID='Example', TITLE='Example' /
&TIME T_END=1000, DT=10 /
&MISC SOLID_PHASE_ONLY=.TRUE. /
&DUMP DT_DEVC=10 /
&RADI RADIATION=.FALSE. /

&MESH IJK=60,10,25, XB=-0.6,0.6, -0.1,0.1, 0.0,0.5 /

&VENT MB='ZMAX',SURF_ID='OPEN' /
&VENT MB='YMIN',SURF_ID='OPEN' /
&VENT MB='YMAX',SURF_ID='OPEN' /
&VENT MB='XMIN',SURF_ID='OPEN' /
&VENT MB='XMAX',SURF_ID='OPEN' /

&OBST XB= -0.60, 0.60, -0.10,-0.08, 0.18,0.20, HT3D=T, SURF_ID='ADIABATIC' /
&OBST XB= -0.60, 0.60,  0.08, 0.10, 0.18,0.20, HT3D=T, SURF_ID='ADIABATIC' /
&OBST XB= -0.60,-0.58, -0.10, 0.10, 0.18,0.20, HT3D=T, SURF_ID='ADIABATIC' /
&OBST XB=  0.58, 0.60, -0.10, 0.10, 0.18,0.20, HT3D=T, SURF_ID='ADIABATIC' /
&OBST XB=-0.58,-0.20, -0.08,0.08, 0.18,0.46, SURF_ID='STEEL BEAM', HT3D=T, MATL_ID='STEEL' /
&OBST XB=-0.20, 0.20, -0.08,0.08, 0.18,0.46, SURF_ID='COPPER BEAM', HT3D=T, MATL_ID='COPPER' /
&OBST XB=0.20, 0.58, -0.08,0.08, 0.18,0.46, SURF_ID='CONCRETE BEAM', HT3D=T, MATL_ID='CONCRETE' /

&SURF ID='HOT STEEL', HT3D=T, COLOR='RED', TMP_FRONT=100/

&VENT XB = -0.44,-0.36, -0.04,0.04, 0.18,0.18, SURF_ID='HOT STEEL' /
&VENT XB = -0.04, 0.04, -0.04,0.04, 0.18,0.18, SURF_ID='HOT STEEL' /
&VENT XB = 0.44, 0.36, -0.04,0.04, 0.18,0.18, SURF_ID='HOT STEEL' /

&MATL ID='STEEL', SPECIFIC_HEAT= 0.45, CONDUCTIVITY= 45.8, DENSITY= 7850.0 /
&MATL ID='COPPER', SPECIFIC_HEAT=0.385, CONDUCTIVITY=401.0, DENSITY=8960.0 /
&MATL ID='CONCRETE', SPECIFIC_HEAT=0.75, CONDUCTIVITY=1.6, DENSITY=2400.0 /

&SURF ID='STEEL BEAM', RGB=68,68,68, HT3D=T, TRANSPARENCY=0.5, MATL ID='STEEL', ADIABATIC=.TRUE./
&SURF ID='COPPER BEAM', RGB=190,100,0, HT3D=T, TRANSPARENCY=0.5, MATL ID='COPPER', ADIABATIC=.TRUE./
&SURF ID='CONCRETE BEAM', RGB=68,68,68, HT3D=T, TRANSPARENCY=0.5, MATL ID='CONCRETE', ADIABATIC=.TRUE./

&BNDF QUANTITY='WALL TEMPERATURE' /
&SLCF PBY=0.0, QUANTITY='TEMPERATURE'/

&DEV ID='STEEL_DEV', SURF_ID='STEEL BEAM', XYZ=-0.39,0.0,0.46, OUTPUT='ALL', TIME=10.0, QUANTITY='TEMPERATURE', VAR='T' /
&DEV ID='COPPER_DEV', SURF_ID='COPPER BEAM', XYZ=0.0,0.0,0.46, OUTPUT='ALL', TIME=10.0, QUANTITY='TEMPERATURE', VAR='T' /
&DEV ID='CONCRETE_DEV', SURF_ID='CONCRETE BEAM', XYZ=0.39,0.0,0.46, OUTPUT='ALL', TIME=10.0, QUANTITY='TEMPERATURE', VAR='T' /

 
&TAIL

**Comment by drjfloyd** [comment]
You have a misspelled or incorrect input on the surf line.  

A quick way to find it if you are not seeing the error is move the / to the middle of the input line and run the input again. If you no longer get an error on that line, you know the error is now after the slash.  Keep moving the / and running fds until you find the error.

**Comment by glimentin** [comment]
I found an error, removed MATL, but now there is another error for the same materials.  

 SURF COPPER BEAM cannot have a specified flux and a MATL_ID. (CHID: Example)

**Comment by glimentin** [comment]
> I suspect you will continue to get ERRORs with these inputs. They don't make sense. You have mixed up HT3D, ADIABATIC, TMP_FRONT, etc. These inputs are not compatible. I suggest you start with a simple verification case and work your up.

what should I remove for the heat transfer model? Thanks for the explanation

**Comment by mcgratta** [comment]
I don't know what you are trying to do. First of all, never use `ADIABTIC`. That is only something we use for testing, because it provides for a perfectly insulated boundary, one that does not exist in reality. Second, do you really need `HT3D`? If so, look at the examples in the User's Guide and Verification Guide, and make sure you are using the latest release.
