### ISSUE TITLE
Error: MKL Library compile flag was not defined for ULMAT as pressure solver.

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#13609]
**Describe the bug**
Hi, I am running FDS in a HPC cluster. I have compiled FDS from the source file in impi_linux_openmp folder, and it works perfectly most cases. Recently, I started working with GEOM instead of OBST to build terrains. In this scenario with GEOM, the simulation crashes every time the LEVEL_SET_MODE>1. I personally would like to run the simulation where the wind field is either established and follow the terrain. 

**To Reproduce**
I have attached the FDS file and the bingeom files here. 
[run.zip](https://github.com/user-attachments/files/17488930/run.zip)

**Expected behavior**
This is the error I get:
Error: MKL Library compile flag was not defined for ULMAT as pressure solver.

ERROR: FDS was improperly set-up - FDS stopped (CHID: terrain)

**Desktop:**
 - OS: Linux

Thank you for your help

**Comment by rmcdermo** [comment]
The error message means you did not correctly link the MKL library during your build of FDS.  Did you follow the instructions here for the linux target?

https://github.com/firemodels/fds/wiki/Compiling-FDS-with-Intel-oneAPI

**Comment by rakyuv** [comment]
Hi @rmcdermo. Thank you for your answer. 

Yes, I followed these instructions from that link, when I built the FDS from source. The only variant is that I used "mpiifortran" while I compiled, instead of the default "ifort" in the makeFile. At the end, I ran the "duct_flow_uglmat.fds" example to verify it. I remember it worked as intented. 

I'm re-running the duct_flow_uglmat.fds presently, to see if it runs correctly. The job is in the queue. I'll keep you posted once I have the result.

**Comment by marcosvanella** [comment]
Do you have intel MPI + intel compilers in your cluster? You should be using the impi_intel_linux build target. Make sure you have the environment variable MKLROOT set to the location of MKL in OneAPI, and when compiling you are seeing the flag -DWITH_MKL flag in the compilation lines.
