### ISSUE TITLE
separate HRR from solid oxidation

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13664]
Right now the HRR column in the *_hrr.csv combines both gas phase and solid phase oxidation reactions. The solid phase can be neglected with `HRR_GAS_ONLY` but you need to run a case twice to have the split. We could create a new column for the hrr file and just always separate the contributions. And then `HRR_GAS_ONLY` can be deprecated. 

I'm also going to add an `OXIDATIVE HRRPUA` solid phase quantity because we don't currently have a local output for B1%Q_DOT_O2_PP

**Comment by mcgratta** [comment]
`HRR_OX` is now the second quantity in `CHID_hrr.csv`  and it is `Q_DOT(2)` in the code. I have only checked that debug runs don't fail. Could you make sure this works properly.

**Comment by ericvmueller** [comment]
Running `char_oxidation_1.fds` with your changes I see the split in the hrr file and the surface oxidation component agrees with what I get from the surface-integrated `OXIDATIVE HRRPUA` quantity. So it looks to be working properly.

![image](https://github.com/user-attachments/assets/195bc133-8068-4061-bb72-bd40d30adbd0)

I will look for verification cases that make use of `N_O2` reactions and use HRR as a metric so we can switch to using the sum of the two columns.

**Comment by ericvmueller** [comment]
Okay - only a couple of places that needed the switch. I think we're good but lets leave it open for now and give firebot the final say.
