### ISSUE TITLE
No success metric for verification case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13687]
The case `Verification/Pressure_Solver/obst_activation_ulmat.fds` does not appear to have a success/failure test. I ran the verification cases with no errors, but inadvertently broke this case. The only way to know it fails is to grep on `forrtl`.

**Comment by marcosvanella** [comment]
I'll add the test for the case, thanks.

**Comment by marcosvanella** [comment]
I pushed cases with a loose tolerance on Temperature. I'll close the issue if these pass firebot tonight.

**Comment by marcosvanella** [comment]
Metrics for obst_activation cases look fine with your latest changes. Closing.
