### ISSUE TITLE
implementation of U0/V0/W0

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13696]
Reading the guide I believe the intent of `U0`,`V0`,`W0` on `WIND` is to initialize the flow field to reach a steady state faster when using a `VENT` to drive the flow:

![image](https://github.com/user-attachments/assets/56f8c22e-12b2-4941-b8d5-06918afad5f9)

However, it seem like if this is used in combination with a vent there is an additive effect on the `VENT` velocity and the flow still takes time to establish. For example, run the `lee_waves.fds` case. The input is 
```
&WIND U0=5.0,LAPSE_RATE=0.005 /
&SURF ID='WIND',VEL=-5.0,PROFILE='ATMOSPHERIC',PLE=0. /
```
The inlet flow starts at 5 m/s but then accelerates to 10 m/s

![image](https://github.com/user-attachments/assets/6f163017-ecba-4fd9-a8dc-a465fe660483)
![image](https://github.com/user-attachments/assets/0c517e69-c12a-42e9-bd08-2a154ff7ab96)

**Comment by mcgratta** [comment]
I think that this advice is outdated. I suggest you remove it from the User's Guide.

**Comment by ericvmueller** [comment]
Is there an accepted way to start with a flow field that is matched to a vent velocity - which I think the intent is with that `lee_waves.fds` case?

**Comment by rmcdermo** [comment]
Could you use `RAMP_UZ`?  Have a look at the user guide.

**Comment by ericvmueller** [comment]
I still get an additive effect. In my case I have
```
&MISC RAMP_UZ='u'/
&RAMP ID='u', X= 0, F=2 /
&RAMP ID='u', X= 1, F=2 /
&SURF ID='INLET', VEL=-2/
```
I start out with 2 m/s like I want but then things accelerate to 4 m/s

![image](https://github.com/user-attachments/assets/8035110a-e4ea-402c-bec8-c9be17705485)
![image](https://github.com/user-attachments/assets/487ae0fa-ff15-44b3-9ece-c57e43f6d477)

**Comment by mcgratta** [comment]
Have you looked at `INITIAL_SPEED`?

**Comment by ericvmueller** [comment]
I get the same as above. Iooks like `INITIAL_SPEED` is just another way to define the `U0` and `V0` global variables

**Comment by mcgratta** [comment]
I changed the code so that now, `INITIAL_SPEED` and `INITIAL_DIRECTION` (new parameter) do nothing except set `U` and `V` at `T_BEGIN`.

**Comment by ericvmueller** [comment]
Try with this input - I still see the same issue. Unless I'm just not understanding the expected behavior.

[initial_speed.txt](https://github.com/user-attachments/files/17666828/initial_speed.txt)

**Comment by mcgratta** [comment]
I remember now the problem with initial velocity. In the past, we would have to subtract off the initial velocity components from calculations of $\partial{u}/\partial{t}$ etc. This became a burden, as this was done throughout the code. It seems that `INITIAL_SPEED` is no longer working and not used much. To make it work would involve going back to all these subtractions. I don't think it is worth it. I removed it completely.
