### ISSUE TITLE
GitHub Actions fails due to change in Intel compiler

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13715]
I pushed a minor FDS source code change to GitHub, and I received an error from GitHub Actions complaining that `ifort` is not recognized. I suspect that the latest oneAPI package has been installed, and the Intel "classic" Fortran compiler (ifort) is no longer recognized. Can we use an earlier version?

**Comment by rmcdermo** [comment]
I'll try to fix

**Comment by marcfehling** [comment]
The github-action `setup-onapi` has been updated, but it can't find `ifort` anymore. This is not a problem of FDS, but of the github-action.

I am in touch with the developer of the github-action to get it resolved. I'll let you know once we find a solution. Feel free to ignore the failing CI for now.

**Comment by marcfehling** [comment]
I just saw that you updated from ifort to ifx. Has this solved the problem for you?

**Comment by marcfehling** [comment]
FYI, `ifort` has been discontinued in October 2024. We _need_ to switch to `ifx`.
https://www.intel.com/content/www/us/en/docs/fortran-compiler/get-started-guide/2024-0/overview.html

**Comment by mcgratta** [comment]
Yes, we fixed the problem. We now compile with mpiifx in GitHub actions, but we can still use the older compiler for our own use.
