### ISSUE TITLE
fractional effective dose (FED) shows different results in smoke view 

### ISSUE THREAD

**Issue by ThijsH24** [firemodels/fds#13724]
I have simulated a tunnel fire of 100MW for 500 seconds, with constant inflow of fresh air (Vin = 1.8 m/s).
After 500 seconds this is what the FED-slice in smokeview looks like:
![image](https://github.com/user-attachments/assets/772479d9-2640-4f36-8fee-371735b63b1b)
Which is extremely low, considering there is a lot of smoke inside the tunnel.
When I reproduce the FED calculations myself by using the CO,O2 and CO2 concentrations I get the following result after 500 seconds.
[FED.pdf](https://github.com/user-attachments/files/17680375/FED.pdf)
Which looks more realistic (goes up way higher than 8 in the fire). In the technical reference guide I see that the units of CO needs to be in ppm while the others are in percentages. So I used that in my calculations. What goes wrong? 

calculations 
all the concentrations are in volume fractions (one concentration value each time step).
integral_CO = 2.764*10**-5*(CO*1000000)**1.036      #ppm
FED_CO = np.trapz(integral_CO,time,axis=0)

integral_O2 = 1/(np.exp(8.13-0.54*(20.9-O2*100)))    #%
FED_O2 = np.trapz(integral_O2,time,axis=0)

HV_CO2 = np.exp(0.1903*CO2[-1]*100+2.0004)/7.1  #%

FED_tot = FED_CO * HV_CO2 + FED_O2
FDS_file:
[V_1_8.txt](https://github.com/user-attachments/files/17680413/V_1_8.txt)

**Comment by gforney** [comment]
I'll take a look.  

rerun your case adding devices for FED as in
&DEVC ID='F-00', XYZ=0.00,8.0,2.0, QUANTITY='FED' /

**Comment by ThijsH24** [comment]
I rerun an other case with the DEVCs.
[FED_check.txt](https://github.com/user-attachments/files/17700226/FED_check.txt)
I compared the devc data with my calculations: where i used the CO,O2,CO2 concentrations from the slices files.

```
def FED_int(CO,O2,CO2,time):
    integral_CO = 2.764*10**-5*(CO*1000000)**1.036 #ppm
    FED_CO = cumtrapz(integral_CO,time,initial=0)
    
    integral_O2 = 1/(np.exp(8.13-0.54*(20.9-O2*100)))#%
    FED_O2 = cumtrapz(integral_O2,time,initial=0)
    
    HV_CO2 = np.exp(0.1903*CO2[-1]*100+2.0004)/7.1 #%
    
    FED_tot = FED_CO * HV_CO2 + FED_O2
    return FED_tot
```

 This is the comparison at X = 210, Y=8, Z=5.6.     
![FED_time](https://github.com/user-attachments/assets/0706662b-1b5e-41e2-a7ed-ca7d027583a7)
It is weird that the FED calculated by FDS is so low, as you would expect to see a big difference between the FED in the smoke and the FED in the ambient air.
This is the results in the smoke vieuw at t=54 s. 
![FED_slc](https://github.com/user-attachments/assets/85de0a67-a32f-4644-867e-ab9558f4318d)

Looks like also grid resolution plays a significant role, I use a grid size of 0.4m here instead of 0.2m (as in the previous one).

**Comment by ThijsH24** [comment]
![image](https://github.com/user-attachments/assets/1c71b386-72b7-4360-8bd4-86ddceb56513)
Is the CO-concentration not in percent? When I use percent instead of ppm, the results correspond better with the DEVC data.

**Comment by gforney** [comment]
smokeview (and fds) performs an integration to compute the fed values.  smokeview uses co, co2 and o2 values in slice files.  It looked like to me that the time step integration time interval) you defined for slice file output was 2 s.  I suggest you decrease it to say 0.1 s.

the fed computation has been removed in recent versions of smokeview and moved to a standalone program named fds2fed.  try installing the nightly bundle  at link below.  you don't need to rerun your case (except if you reduce the slice time interval) .  just type
fds2fed casename 
where casename is the name of your case then view your case in smokeview

https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST

**Comment by ThijsH24** [comment]
Thanks a lot for your reply. What would be the difference if I reduce my timestep? The integration is over the entire time of the simulation right? Not for each timestep.

**Comment by gforney** [comment]
Intgral from a to b of f(t) dt  can be approximated by splitting the
interval  a to b into N parts . Compute f(t_i) in each part and sum
f(t_i)*deltat where deltat=(b-a)/N and t_i=a+(i+0.5)deltat for i  from 0 to
N-1. Large N ( small deltat) will approximate the integral better than
small N. The fed is an integral which both fds and smokeview approximates
similar to a procedure like this.  I was just guessing that a reason for
poor fed values in your earlier post was that your N was too small (
equivalently deltat=2.0 was too big)

**Comment by ThijsH24** [comment]
Yes that makes sense. It would definitely make it more accurate. 
Two remaining questions:
What formulas/units do I need to use to calculate the FED myself?
How do I install the nightly bundle?
