### ISSUE TITLE
Numerical Instability in HVAC simulation using pyrosim/FDS

### ISSUE THREAD

**Issue by elangsz** [firemodels/fds#13768]
Hello, im currently trying to do a HVAC simulation with the geometry being a 37 m x 40 m x 6 m area that are cooled in order to the understand the airflow pattern and temperature distribution of the room. The model are attached below (the green surf is the supply side, purple is the return side), along with the pyrosim file and FDS code.

Model screenshot
![GEOM](https://github.com/user-attachments/assets/08e04341-8381-433a-b4db-b7d90b5ac24f)

Pyrosim/FDS file
https://drive.google.com/drive/folders/1Wyw5-T69APmAmzn9BhXN2diQrVz24VI0?usp=sharing

However i got a notification that shows numerical instability error
![WhatsApp Image 2024-11-17 at 20 29 00_2b8d26fa](https://github.com/user-attachments/assets/992f139f-2e81-443f-b1b1-d99616a3f61d)

Hoping for a solution to overcome this issue, thankyou!

**Comment by drjfloyd** [comment]
You HVAC system is non-physical.  

The flow in these ducts all go into Node 43. First, 4.7 m3/s in a 0.3048 m diamter duct is 64 m/s.  That is extremely high flow for an HVAC system.  Then the combined total of those flows of 45 m3/s go into duct 53 which is also a 0.3048 m diameter duct which is something close to Mach 2.   The same happens for Node 44. Then for Node 41 you get something close to Mach 4.

&HVAC ID='Duct46', TYPE_ID='DUCT', DIAMETER=0.3048, VOLUME_FLOW=4.724653, NODE_ID='Node43','NS1', ROUGHNESS=1.0E-3, LENGTH=12.113542/
&HVAC ID='Duct47', TYPE_ID='DUCT', DIAMETER=0.3048, VOLUME_FLOW=4.724653, NODE_ID='Node43','NS2', ROUGHNESS=1.0E-3, LENGTH=16.358022/
&HVAC ID='Duct48', TYPE_ID='DUCT', DIAMETER=0.3048, VOLUME_FLOW=4.724653, NODE_ID='Node43','NS3', ROUGHNESS=1.0E-3, LENGTH=21.308023/
&HVAC ID='Duct49', TYPE_ID='DUCT', DIAMETER=0.3048, VOLUME_FLOW=4.724653, NODE_ID='Node43','NS4', ROUGHNESS=1.0E-3, LENGTH=27.290752/
&HVAC ID='Duct50', TYPE_ID='DUCT', DIAMETER=0.3048, VOLUME_FLOW=4.724653, NODE_ID='Node43','NS5', ROUGHNESS=1.0E-3, LENGTH=32.89784/
&HVAC ID='Duct51', TYPE_ID='DUCT', DIAMETER=0.3048, VOLUME_FLOW=2.362326, NODE_ID='Node43','NS6', ROUGHNESS=1.0E-3, LENGTH=38.319954/

Beyond the unphysically high speeds you haven't defined reasonable losses for those portions of the duct system that are being predicted. Inlets, tees, elbows, etc. all add flow loss.  See 10.2.9 in the Guide.


I suggest you ensure that you inputs decsribed a physcially plausible HVAC systems.

**Comment by elangsz** [comment]
i see. For this particular case, i only want to model the airflow of the room, not the airflow inside the ducts. any way i can achieve that?

**Comment by drjfloyd** [comment]
If you don't need to model the HVAC system, then just specify the flows right at the VENTs.  See the User's Guide for details.

**Comment by elangsz** [comment]
No i cant set the airflow at the vents because ive set both the supply and return vent surface as HVAC, so the airflow rate is set at each duct that connects directly to each vent. There are a total of 32 return vent each with each vent airflow at 1.62 cfm, and 11 supply vent with each vent airflow at 4.713 cfm, and theres a cooling coil that connects the supply side and the return side. ive updated the FDS/Pyrosim file where i changed the ducts into no friction ducts. Ive done this previously, but this time theres this numerical instability notification

**Comment by drjfloyd** [comment]
Did you read the Users Guide on how to directly specify flows?

**Comment by drjfloyd** [comment]
You still have hypersonic flow in your ducts. FDS is not a compressible flow code.

**Comment by elangsz** [comment]
yes ive read it. If i only were to model a ventilation inlet/outlet i can specify the airflow directly at the VENT itself, however im modelling an air conditioning system that involves an aircoil, so i input the airflow at the ducts. Ive done this in FDS a couple of times but this is my first time modeling in pyrosim. Regarding the hypersonic flow of the ducts, ill try and resize the ducts and ill get back to you, thankyou.

**Comment by elangsz** [comment]
hello, sorry i havent followed up with this issue, i solved the problem by enlarging the ducts to make it a subsonic flow, hence ill close the issue, thankyou!
