### ISSUE TITLE
Effect of temperature of gas release

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#13771]
**Objective**
To see the influence of temperature of gas release in the dynamics of the plume thereafter. In this regard, I have the following 
[temperature.txt](https://github.com/user-attachments/files/17801281/temperature.txt)

**Expected behaviour**
I expected the temperature at the source to be the one defined by TMP_FRONT for that surface. In this case, I expected the METHANE BLOWER to be -80 °C. However, the lowest temperature I found that from this simulation is of the order of 0 °C, when I checked by different slcf2d in Smokeview. If I increase the temperature to 80 °C, the highest temperature I can observe is of the order of 25 °C.

Could you please explain, why I'm not able to see anything closer to the input temperatures on the METHANE BLOWER ?

Thanks in advance

**Comment by drjfloyd** [comment]
You have 1 m^3 grid cells. So each grid cell has a mass of 1 kg.  You methane flow is 0.015 kg/s/m2. This is not a well resolved calculation.

**Comment by rakyuv** [comment]
Thank you @drjfloyd for the answer. I am assuming that I need to have a methane flow of greater than 1 kg/s/m^2 to have a reasonable distribution of temperature. 

Could you please tell me if that would result in a well resolved calculation ?

Thank you in advance

**Comment by drjfloyd** [comment]
You are the one doing the modeling. It is up to you to decide what error you can tolerate for your specific scenario.

**Comment by drjfloyd** [comment]
The methane flux should be whatever is the appropriate flux for your specific scenario. 1 kg/s/m2 might be appropriate for a leak in pipe but probably not appropriate for evaporation from a liquid pool. This is a decision that you as the modeler need to make and justify. Once you have established the appropriate flux, then you can consider what grid size (maybe perform a grid study) provides you with suitable results for the quantities of interest.
