### ISSUE TITLE
ULMAT/UGLMAT not working for indefinite matrices with latest oneAPI 2025 MKL

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#13784]
In spark load the latest compiler, mpi and mkl modules, compile the impi_intel_linux_db target and run this case:

```
&HEAD CHID='test_indefinite', TITLE='Test ULMAT/UGLMAT on indefinite Poisson problem.' /
# Mesh:
&MESH IJK=9,8,8, XB=0.0,9.0,-4.0,4.0,0.0,8.0 /
# Simulation Paremeters:
&TIME T_END=.02, DT=0.01/
&MISC SIMULATION_MODE='DNS', STRATIFICATION=.FALSE., NOISE_VELOCITY=0.5 /
&RADI RADIATION=.FALSE. /
&PRES SOLVER='ULMAT', CHECK_POISSON=T  /

# OBST just to trigger PARDISO solve with ULMAT:
&OBST XB=8.,9.,-4.,4.,0.,8. /
# Boundaries:
&VENT MB='XMIN', SURF_ID='MIRROR' /
&VENT MB='XMAX', SURF_ID='MIRROR' /
&VENT MB='YMIN', SURF_ID='MIRROR' /
&VENT MB='YMAX', SURF_ID='MIRROR' /
&VENT MB='ZMIN', SURF_ID='MIRROR' /
&VENT MB='ZMAX', SURF_ID='MIRROR' / 
# Output:
&SLCF PBY=0., QUANTITY='VELOCITY',      VECTOR=.TRUE.        /
&SLCF PBY=0., QUANTITY='H' /
&TAIL /

```

The Poisson matrix for this problem is symmetric indefinite. Both with ULMAT and UGLMAT we are getting H=0 as solution regardless of what the Poisson RHS is.
![Screenshot 2024-11-20 at 3 32 03 PM](https://github.com/user-attachments/assets/1170aaf7-b342-47da-88a1-c80e8335b93b)

Now unload mkl/latest and load mkl/2024.2, recompile the impi_intel_linux_db target and run the case. The solution for H is correct.
![Screenshot 2024-11-20 at 3 36 45 PM](https://github.com/user-attachments/assets/6d1be85f-1860-4c2c-8f3b-a9443b6ccbc4)

Interfaces to PARDISO or SPARSE_CLUSTER_SOLVER have not changed, and VERBOSE metrics for matrix factorization are identical.
I opened a thread in the Intel MKL forum asking about any parameter changes that might be related to this (https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Change-in-behavior-of-Pardiso-and-Sparse-Cluster-Solver-for/m-p/1644570#M36659).

Next I'll setup a standalone test of the solver.

**Comment by mcgratta** [comment]
I ran the test case with the latest ifx (2025.0.1) and MKL (2025.0.1) on Windows, and the results are the same. It still does not work.

**Comment by marcosvanella** [comment]
Ok, turns out the issue is related to small matrices. If you switch the size of the grid to 18,16,16 is should run fine.

**Comment by marcosvanella** [comment]
[test_cpardiso.tar.txt](https://github.com/user-attachments/files/17850224/test_cpardiso.tar.txt)

This is a standalone code to reproduce the issue. The issue was posted in the intel MKL Forum here:

https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Change-in-behavior-of-Pardiso-and-Sparse-Cluster-Solver-for/m-p/1644570/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufE0zUUFGNVMyMlRYWUY4fDE2NDQ1NzB8U1VCU0NSSVBUSU9OU3xoSw#M36659

**Comment by marcosvanella** [comment]
From the response from Fengrui in the Intel forum, seems a change in default parameter took place when moving from mkl 2024.2 to 2025. I changed the code accordingly in PR #13810. I also changed the startup file of firebot in spark to load mkl/latest. We'll see tonight if this issue is sorted.

**Comment by marcosvanella** [comment]
closing this, the verification tests are working correctly.
