### ISSUE TITLE
Block burn away, but burning rate is zero

### ISSUE THREAD

**Issue by IFAB-AS** [firemodels/fds#13798]
Hello,

we are simulating some boxes in a storage and use the BURN_AWAY feature. Mostly, it seems to work as intended but we get some surfaces that have a burning rate of zero. After some time, the blocks burn away nevertheless (shown in Pyrosim, but SMV is the same):
  
![grafik](https://github.com/user-attachments/assets/ebce3cd6-e455-42b5-9bff-4dec5bd84348)

(simulated with FDS/SMV is 6.9.1-634, image shows pallet and underside of the box)

These blocks are not burning "at one of the other sides", which would explain the effect. The images are from a larger model, but this smaller example might generate the same behavior (still running, needs to reach 500-1000s):
[Kevin_burn_away_test-Scenario04.txt](https://github.com/user-attachments/files/17901980/Kevin_burn_away_test-Scenario04.txt)

**Comment by mcgratta** [comment]
My guess here is that you have specified the burning rate and thickness of the wall of the obstruction. It is possible that the wall runs out of fuel on a particular side before the fuel for the entire box is exhausted. The time to burnout a side of the obstruction is given by `THICKNESS*DENSITY*HEAT_OF_COMBUSTION/HRRPUA`. In your case, `HRRPUA` varies with time, but you can make a quick estimate to check if the side of the obstruction has stopped burning in a certain amount of time.

**Comment by IFAB-AS** [comment]
I have run the test case in FDS 6.9.1-634, and the error does not occur in the small example ;-) (it is the same section as in the full scale model where it happens). In the image from the full scale model, one line of blocks is removed without increase in burning rate. It looks like it never ignites, but is removed after some time:
![grafik](https://github.com/user-attachments/assets/1a1f09e1-e3d2-4504-bb3e-e92563569353)
In SMV (6.9.1-0 with FDS calculations from 6.9.1-634), this looks like this (burning rate is shown, area below box):
![grafik](https://github.com/user-attachments/assets/1a7de820-d138-4da0-9d95-089914721650)
380 s: box is burning at underside
550 s: row is removed due to burn out, next row stays black which means burning rate=0
830 s: row is removed (in some weird way, grid is missing), stays black
1000 s: now the new faces start to burn

in SMV 6.9.4-21 (nightly from yesterday, but calculations with FDS 6.9.1-634):
![grafik](https://github.com/user-attachments/assets/c8252d82-5a25-417c-a574-b4d241e3d983)

So there are also differences between the SMV versions. Both of them do not look correct. I can try to calculate this case with the latest nightly build and check again in SMV 6.9.4-21, but I might be not allowed to send the full model.

The thickness is the same as the grid size, and the BULK_DENSITY is the real combustible mass that should be consumed. To my understanding, the THICKNESS and DENSITY is only used for the surface temperature calculation and the BULK_DENSITY and grid size is used for the burning rate.

**Comment by IFAB-AS** [comment]
I used the holidays to let this case run for some time. This is the full scale model file I did show above:
[Sz4_241122-Scenario04.txt](https://github.com/user-attachments/files/18058716/Sz4_241122-Scenario04.txt)

Results:
- In the nightly (FDS 6.9.1-1352), there was no removal of blocks without having a burning rate at the surfaces first. This works in Pyrosim and SMV (6.9.1-1352).
- The other FDS version FDS 6.9.1-634 shows removal of blocks without visible burning rate at some blocks (in SMV and Pyrosim).

The HRR looks like this:
![grafik](https://github.com/user-attachments/assets/323fc76b-7a6b-469f-97af-b6aff7c4d0d2)

During the first minutes, the HRR is the same as only the sides of the boxes are burning and everything works fine there. After some time, the effect with the removal of blocks without burning rate occurs (600 s - 1800 s).

My question is:
- Is this difference in HRR only related to random effects (sprinkler activation, changes in the code that influence droplets or other things) which means all burning of the locks was calculated correctly and only shown wrong or
- might it be related to blocks having no burning rate in older versions of FDS (were there relevant changes during the last year)? Maybe these blocks did get removed instead of getting the assignment of a burning rate, which would explain the lower HRR?

**Comment by mcgratta** [comment]
We have made several changes to improve the creation and removal of burning obstructions. As you can imagine, making an obstruction instantly disappear can lead to "butterfly effects". Can you tell me whether the latest version is qualitatively working correctly? In other words, do you see blockage faces that do not appear to burn properly?

**Comment by IFAB-AS** [comment]
In FDS 6.9.1-1352 the blocks seem to get the burning rate when the ignition temperature is reached. I did not notice any block that was removed before the face was ignited.

**Comment by mcgratta** [comment]
Is there now a problem? I am not surprised that the HRR curves are different. Even a small change in the way obstructions are removed can cause this kind of issue, especially when sprinklers are involved.

**Comment by IFAB-AS** [comment]
The current version seems to be correct, but I am not sure if the other one (FDS 6.9.1-634) did calculate everything correct or if it was only displayed wrong and the HRR is different because of small differences during the simulation.

**Comment by mcgratta** [comment]
OK, I think we must have fixed this problem in the last few months. I'll close the issue.
