### ISSUE TITLE
Smokeview 3D slice

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#13797]
I want a slice that goes from corner to corner using 3D slice, but smokeview draws two slices (see attached picture). How can I remove what's unwanted?

FDS 6.9.1-1347-SMV 6.9.4-21
![Slice](https://github.com/user-attachments/assets/e623a3a0-d282-43bc-9778-194ea00ea764)
[Avfall.txt](https://github.com/user-attachments/files/17893675/Avfall.txt)

**Comment by gforney** [comment]
x, y , z show/hide slices  along x, y, z axese respectfully . Press one of
these keys to remove unwanted slice. The w key toggles visibility of the
arbitrarily oriented slice
