### ISSUE TITLE
Storage counters for LAGRANGIAN_PARTICLE(1)

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13805]
When there are multiple classes of particles, the values for `LP%N_REALS`, `LP%N_INTEGERS`, and `LP%N_LOGICALS` are wrong for the first particle in the `LAGRANGIAN_PARTICLE` array.

Basically, when `INITIALIZE_MESH_EXCHANGE_1` is run, every time `ALLOCATE_STORAGE` is called on `LP_INDEX=1` (treated as a kind of dummy particle) it adds to the previous values for the storage counters, because they are not reset in `NULLIFY_PARTICLE`

https://github.com/firemodels/fds/blob/6e9300ce781069c166dea78b9b0011cd187d19c5/Source/main.f90#L2035-L2046

You can see that this persists into stepping if you run my example and print out `LP%N_REALS` for each particle at some point. The first particle has a value which is too large by an extra factor of `N_LAGRANGIAN_CLASSES`.

Heres what I get for the 4 particles, putting a print statement at the top of `MOVE_PARTICLES`
 ```
 Time Step:       6, Simulation Time:   0.95799 s
 LP%N_REALS         470
 LP%N_REALS          94
 LP%N_REALS          94
 LP%N_REALS          94
```

I'm actually not sure how much these variables are needed, or if this is causing any real issue, because they seem somewhat redundant to the information stored in `LPC%N_STORAGE_REALS` etc. Is there a case where these would have different values? Still, seems best to clean this up.
[LP_REALS.txt](https://github.com/user-attachments/files/17922712/LP_REALS.txt)

**Comment by mcgratta** [comment]
Try adding the first of these two lines to `func.f90` line 1060 or thereabouts
```   
LP%N_REALS=0,LP%N_INTEGERS=0,LP%N_LOGICALS=0    <------- 
CALL PACK_PARTICLE(NM,OS_DUMMY,LP,LPC_INDEX,LP%N_REALS,LP%N_INTEGERS,LP%N_LOGICALS,UNPACK_IT=.FALSE.,COUNT_ONLY=.TRUE.)
```

**Comment by ericvmueller** [comment]
This fixes the `LP` values for the first particle, but not the other issue with the `LPC` values and multiple meshes. But you can push this if you want and we can close this issue at least.

**Comment by mcgratta** [comment]
Try it now.

**Comment by ericvmueller** [comment]
This works (actually somewhat moot now with the removal of LP%N_REALS etc). Thanks!
