### ISSUE TITLE
Storage counters for lagrangian particles with multiple meshes

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#13806]
This is related to #13805, but instead of an error on LP%N_REALS etc., it has to do with LPC%N_STORAGE_REALS etc.

The case is the same as the previous one, but I divided it into 4 meshes. If I run this on 4 processes (mpirun -n 4) I get the expected storage counts:
```
 Lagrangian Particle Classes

   1 class 1
     SURFace ID: wood
     # Reals: 94
     # Integers: 38
     # Logicals: 8

   2 class 2
     SURFace ID: wood
     # Reals: 94
     # Integers: 38
     # Logicals: 8

   3 class 3
     SURFace ID: wood
     # Reals: 94
     # Integers: 38
     # Logicals: 8

   4 class 4
     SURFace ID: wood
     # Reals: 94
     # Integers: 38
     # Logicals: 8
```

If I run it on only one process (mpirun -n 1) I get 4x the storage:
```
 Lagrangian Particle Classes

   1 class 1
     SURFace ID: wood
     # Reals: 376
     # Integers: 152
     # Logicals: 32

   2 class 2
     SURFace ID: wood
     # Reals: 376
     # Integers: 152
     # Logicals: 32

   3 class 3
     SURFace ID: wood
     # Reals: 376
     # Integers: 152
     # Logicals: 32

   4 class 4
     SURFace ID: wood
     # Reals: 376
     # Integers: 152
     # Logicals: 32
```

This seems like it may be more impactful in terms of overhead than the previous issue.
[LPC_REALS.txt](https://github.com/user-attachments/files/17922891/LPC_REALS.txt)

**Comment by mcgratta** [comment]
See if the recommended solution to #13805 helps with this.

**Comment by mcgratta** [comment]
Try your case now.

**Comment by ericvmueller** [comment]
The test case also looks to work with the change. I'm going to try on the original large calculation before closing it out.

**Comment by ericvmueller** [comment]
Seems okay - thanks!
