### ISSUE TITLE
Verification cases fail in debug mode

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13815]
I ran the verification cases in debug mode the other night, and two cases failed on the same line in `wall.f90`, around line 2381:
```
            IF (.NOT. TMP_CHECK(NL) .AND. ONE_D%LAYER_THICKNESS_OLD(NL)-ONE_D%LAYER_THICKNESS(NL) > &
               1.5_EB*MINVAL(ONE_D%DX_OLD(I+1:I+ONE_D%N_LAYER_CELLS(NL)))) THEN
```
The problem is that `ONE_D%N_LAYER_CELLS(NL)` is zero and the `MINVAL` returns nonsense. I added a check at the start of the loop to just exit the loop in the case that this happens, but this just leads to more errors further on. I cannot find a good way to completely exit out of the routine in this event, nor prevent it from happening in the first place. The cases that fail are 
```
Fires/couch.fds
Pyrolysis/liquid_mixture.fds
```
I am running with the latest Intel ifx compiler, 2025.0.1.

**Comment by drjfloyd** [comment]
should be fixed

**Comment by drjfloyd** [comment]
I got the error before fixing. After fixing, I did not get the error.  I didn't get any git action errors after doing the pull request and I am able to compile on my PC and pele.

PC:

>ifx
Intel(R) Fortran Compiler for applications running on Intel(R) 64, Version 2024.2.1 Build 20240711
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.

Pele:

$ ifx -v
ifx version 2025.0.0

**Comment by mcgratta** [comment]
OK. On our cluster, I get errors elsewhere, but then when I add write statements, the errors go away. I usually see this type of behavior with optimized code, not debug. 

I'll keep the issue open until I sort things out on our end. I think the bug is fixed.

**Comment by marcosvanella** [comment]
Just got this floating invalid issue in debug mode. I wonder why firebot is not complaining about this.


________________________________

**Comment by marcosvanella** [comment]
Well, turns out the computer does what you tell it to do! The debug cases in firebot run for 1 time step. The issue appears at the second step.

**Comment by mcgratta** [comment]
Yes, I have seen this too. I added debug statements and the problem went away. I'm waiting to have 2025.0.01 installed. I think the compiler is buggy.
