### ISSUE TITLE
WARNING: Minimum density, 0.119 kg/m3, clipped in Mesh 3

### ISSUE THREAD

**Issue by rakyuv** [firemodels/fds#13836]
**Describe the bug**
I am running FDS with multiple resolutions (from 20 cm to 5,4m). I start with an innermost meshes with a grid resolution of 20 cm, and then progressively build the outer meshes with coarser domains. So I continued with 60 cm, 1,8 m resolutions and the simulation ran without any problem. Now, when I added the 5,4 m resolution meshes, the simulation crashes in two ways:
- when I used "PERIODIC FLOW ONLY" for lateral boundaries, this is the error:
  Time Step:     600, Simulation Time:   8.69106 s
  WARNING: Minimum density,    0.119 kg/m3, clipped in Mesh 3
- when I used "OPEN" for lateral boundaries, this is the error:
   Time Step:     100, Simulation Time:   1.44851 s
   WARNING: Maximum density,   12.785 kg/m3, clipped in Mesh 3

**To Reproduce**
This is the FDS input file used for the simulation
[test.txt](https://github.com/user-attachments/files/18012033/test.txt)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: HPC

Thanks in advance

**Comment by mcgratta** [comment]
I do not understand what you are trying to do. It appears that your wind is blowing against a vent that is blowing methane in the opposite direction.

**Comment by rakyuv** [comment]
Thanks @mcgratta for your answer. My apologies for not verifying the wind direction was totally wrong. 

The simuation runs without crashing. 

I'm closing the issue.
