### ISSUE TITLE
How do I compile the Sundials on linux

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#13842]
I have tried compiling the Sundials library on a Linux machine. First, following the instructions for Windows written on the FDS Wiki. Then using the two scripts for sundials in fds/Build/Scripts/SUNDIALS/, but I could not get them to work. 
Would it be possible to put some short instructions on the fds wiki on how to run the build script for Sundials?

**Comment by drjfloyd** [comment]
There has been work to get the third party libraries to build as part of the normal FDS build process.  This wiki page has some newer instructions:

https://github.com/firemodels/fds/wiki/Compiling-FDS-with-Third%E2%80%90Party-Libraries

If you run into problems if you could give the exact error or issue you are having.

**Comment by bphusted** [comment]
Thanks. In the meantime, I got it to work so the issue can be closed now. However, I fully support getting the third-party libraries to build as part of the normal FDS build process.

**Comment by drjfloyd** [comment]
The current FDS makefile should build everything as long as files are in the correct relative location as discussed on that wiki page.
