### ISSUE TITLE
Problem with M-O verification cases

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#13885]
Have look at last night's user guide, you will see that there is a problem with the temperatures in the M-O cases.

![Screenshot 2024-12-13 at 1 54 53 PM](https://github.com/user-attachments/assets/b7f258f4-e438-4e77-a1c1-d932faf16e20)

If you comment out the axis limits for TMP, you see something like this,

![Screenshot 2024-12-13 at 1 55 17 PM](https://github.com/user-attachments/assets/2c9cb35f-d721-4ea5-adc9-64e0acc2aca9)

**Comment by mcgratta** [comment]
I introduced this bug in commit #13303 when I was overhauling the boundary routines. I moved a chunk of code and then left a mistake behind. I'll add a success metric to the script. I'll hold this open to remind myself.

**Comment by mcgratta** [comment]
Added an accuracy check to the Matlab script `atmospheric_boundary_layers.m`
