### ISSUE TITLE
Dynamic Smagorinsky model and varying Cs with multimesh

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#13888]
Running a model of a plume, 5 MW, fire base is 1.6 m by 1.6 m, dynamic Smagorinsky model.

If I run on several meshes and look at the contour of Cs it is quite irregular/discontinuous (see "SimpleMM_0000.png") versus more regular/continuous on a single mesh (see "SimpleOneM_0000.png"). (The single mesh case only ran for a short time, due to computation limits on this end, but it gives the general idea)

I would have expected some irregularity on multimesh but the discontinuity does not look right.

Input files attached (SimpleMM = multimesh version, SimpleOneM = single mesh version).

FDS-6.9.1-0-g889da6a-release

![SimpleMM_0000](https://github.com/user-attachments/assets/f1bbe9a0-4d9a-4823-89bf-9bd7e4bc55a7)
![SimpleOneM_0000](https://github.com/user-attachments/assets/cf7697f2-522d-46ec-8deb-cae1e2c5ee9b)
[SimpleMM.fds.txt](https://github.com/user-attachments/files/18131596/SimpleMM.fds.txt)
[SimpleOneM.fds.txt](https://github.com/user-attachments/files/18131601/SimpleOneM.fds.txt)

**Comment by mcgratta** [comment]
I suggest you add `CELL__CENTERED==T` to the `SLCF` line. That  will produce the actual value used for the particular cell. The default slice uses an 8 point average which might be wonky at mesh boundaries. I'll take a look at the case in the meantime.

**Comment by mattbilson76** [comment]
Thank you - that looks a lot better with CELL_CENTERED=T
See attached - this looks more continuous
That's all it was I think

![SimpleMM_0000](https://github.com/user-attachments/assets/9e2f372c-8e56-4c11-8bcf-127b982a3ec7)

**Comment by mcgratta** [comment]
There are some quantities that we choose not to extend across mesh boundaries because any exchange of information across MPI processes costs CPU time/network traffic. I would guess that C_SMAG is one of them. I generally prefer to use the `CELL_CENTERED` option when analyzing cases because it is a truer reflection of what is actually being calculated. It's not as smooth, but it's good for understanding.
