### ISSUE TITLE
Issues generating images with firebot

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#13902]
Tried running firebot over the weekend. Haven't run it on our cluster since before Thanksgiving. I got error messages trying to build the manuals for all the png files that they were not found.  While on a NoMachine login I went to the Verification/scripts folder and tried running Make_FDS_Pictures.sh  and I get an error like below for every line in FDS_Pictures.sh:

--- generating images for: Bova_1a.smv
GLUT: Fatal Error in smokeview_linux_64: could not open display: :1003

If I go to one of the Verification folders and try running the smokeview version that firebot would have ran with runscript, that works without issue.

**Comment by mcgratta** [comment]
There is some command or routine that allows Smokeview to render the png file without actually rendering it on the screen. I wonder if this is related to that.

**Comment by gforney** [comment]
you need to have the Xvfb package installed.  but did you say you've been able to run firebot before on your cluster?

this is what I get on spark
gforney@spark-login ~ $ rpm -qa | grep Xvfb
xorg-x11-server-Xvfb-1.20.11-26.el9.x86_64

**Comment by drjfloyd** [comment]
It is installed. I've run firebot many times without an issue.
