### ISSUE TITLE
Juelich_SETCOM validation cases fail with seg fault

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#13913]
Run the case `setcom_0p8.fds`. It fails in the first time step.
```
 Job TITLE        : SETCOM 0.8 m/s
 Job ID string    : setcom_0p8

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libc.so.6          000014BC47A3E730  Unknown               Unknown  Unknown
fds_impi_intel_li  00000000004811A1  interpolate1d_uni        3895  func.f90
fds_impi_intel_li  0000000000768DC4  condensation_evap        1712  fire.f90
fds_impi_intel_li  0000000000958A16  fds                       805  main.f90
```
Something to do with `EVAPORATION_CONDENSATION`

**Comment by drjfloyd** [comment]
I tried adding some debug and the error moved to the SWORK1 assignment with SWORK1 having a differnet allocation than ZZ. May be from this https://github.com/firemodels/fds/commit/8ac5ae65a95e9f3543441fcbe8f537968908324d for the flux stuff that @rmcdermo.  I'll look into some more to see what needs to be fixed.

**Comment by rmcdermo** [comment]
There is probably a problem with N_TOTAL_SCALARS vs. N_TRACKED_SCALARS.  I'll look at it tomorrow.

**Comment by drjfloyd** [comment]
With the new flux stuff SWORK1 is now being allocated to 0:N_TOTAL_SCALARS but ZZ is 1:N_TOTAL_SCALARS so assigning SWORK1 = ZZ in fire.f90 broke.  Changing to add (:,:,:,1:) get the case to start time stepping.

I checked the rest of the usage of SWORK and found one more instance in part.f90.

**Comment by mcgratta** [comment]
These cases are now running.
