### ISSUE TITLE
3d-1d coupled multi-scale tunnel model

### ISSUE THREAD

**Issue by zhang-wenling** [firemodels/fds#13954]
Hello, I'm doing some attempts to simulate an ultra-long tunnel fire using HVAC right now. I set up a symmetrical fire located at the midpoint of the tunnel, modeled with HVAC at both ends of the tunnel, but the HRR of multi-scale modeling will decrease, I guess it is due to the lack of oxygen at the location of the fire source due to the one-dimensional modeling on both sides, but the HRR is still decreasing as the oxygen rises, how can I ensure that the problem of HRR reduction is solved when using one-dimensional modeling?Attach the FDS codes for both models.

![image](https://github.com/user-attachments/assets/660c9ba8-b678-4b85-8e07-93de10fc475b)
![image](https://github.com/user-attachments/assets/b8cda1b5-d34a-4efb-9318-6ebe0c100eff)

[3d.txt](https://github.com/user-attachments/files/18271741/3d.txt)

[multiscale.txt](https://github.com/user-attachments/files/18271742/multiscale.txt)

**Comment by Er9y714** [comment]
I think this is not an issue but shortcoming of simplified HVAC model. The underventilation depends on the smoke layer height and stratification is not possible to model in HVAC (1D). Therefore the results are different. If the tunnel had a ventilation, the difference would be smaller.

**Comment by zhang-wenling** [comment]
> I think this is not an issue but shortcoming of simplified HVAC model. The underventilation depends on the smoke layer height and stratification is not possible to model in HVAC (1D). Therefore the results are different. If the tunnel had a ventilation, the difference would be smaller.

I took into account the limitations of one dimension, so I used two layers of HVAC to simulate the stratification movement of the flue gas. However, this does not stabilize the HRR.

**Comment by Er9y714** [comment]
Smoke layer height varies over the length of the tunnel. Therefore even applying a separate HVAC duct to each cell over height might not be sufficient.

**Comment by zhang-wenling** [comment]
> Smoke layer height varies over the length of the tunnel. Therefore even applying a separate HVAC duct to each cell over height might not be sufficient.
Thank you for the suggestion, I'll try to see what the different results are when I add ventilation.

**Comment by drjfloyd** [comment]
I am running your case.

**Comment by zhang-wenling** [comment]
> I am running your case.

Thank you for your interest and look forward to your suggestions.

**Comment by drjfloyd** [comment]
It will take a little time to run out to where you saw the HRR decrease. What version of FDS are you using?  You may be seeing extinction issues due to how you defined the fuel. Heptane is a predefined species as N-HEPTANE. You could just have:

&REAC FUEL='N-HEPTANE',
      CO_YIELD=6.0E-3,
      SOOT_YIELD=0.015,
      RADIATIVE_FRACTION=0.35/

and not need a &SPEC input.  You did not define a SPECIFIC_HEAT on SPEC and the values when assuming gamma=1.4 for a 100 g/mol fuel are not going to be good values. 

User's Guide 
12.1.3 User-Defined Gas and Liquid Properties
Enthalpy
For high molecular weight species, use of the default gamma will result in very low values of the specific heat which can cause issues with the default extinction model.

**Comment by zhang-wenling** [comment]
> It will take a little time to run out to where you saw the HRR decrease. What version of FDS are you using? You may be seeing extinction issues due to how you defined the fuel. Heptane is a predefined species as N-HEPTANE. You could just have:
> 
> &REAC FUEL='N-HEPTANE', CO_YIELD=6.0E-3, SOOT_YIELD=0.015, RADIATIVE_FRACTION=0.35/
> 
> and not need a &SPEC input. You did not define a SPECIFIC_HEAT on SPEC and the values when assuming gamma=1.4 for a 100 g/mol fuel are not going to be good values.
> 
> User's Guide 12.1.3 User-Defined Gas and Liquid Properties Enthalpy For high molecular weight species, use of the default gamma will result in very low values of the specific heat which can cause issues with the default extinction model.

I'm using FDS6.7.4 and the ignition settings are carried over from version 6.6, thank you for your suggestion, I'll redefine the ignition and see the results.

**Comment by drjfloyd** [comment]
Unless there is some specific reason to use an old version like your local authority requires a specific version, then I suggest you use the latest release. There have been a number of bug fixes to HVAC, pressure in tunnels, etc. since 6.7.4 was released (almost 5 yrs ago).

**Comment by zhang-wenling** [comment]
> Unless there is some specific reason to use an old version like your local authority requires a specific version, then I suggest you use the latest release. There have been a number of bug fixes to HVAC, pressure in tunnels, etc. since 6.7.4 was released (almost 5 yrs ago).

Thanks for the reminder, but currently the compute server I am using cannot install versions after 6.7.4 because it cannot install Fortran9 and above compilers, so it cannot install higher FDS versions.
