### ISSUE TITLE
FED calculation 

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#1471]
```
In the resent version of FDS 5.5.3 FED calculations does not take heat/radiation effects
into consideration.
Can FED be calculated as the combination of both toxicity and heat effects.
Please go through the attached document in which FED is calculated for both toxicity
and heat/radiation.


```

Original issue reported on code.google.com by `akulachaturvedi` on 2011-10-10 07:07:48

<hr>
- _Attachment: [FED calculation.pdf](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-1502/comment-0/FED calculation.pdf)_

**Comment by gforney** [comment]
```
Ok, I will add the temperature and radiation parts to
the FED. One should also see, if the "K" and "D" parameters
fo the activity type could be given as an input to the
FDS FED device and for the different agents. So that
the K and D could be given on the DEVC FED namelist and
same for PERS namelist. The present values are, probably,
the light work values.

Values of constants K and D for different activity levels

Activity K D
At Rest 2.81945*10(-4) 40
Light Work 8.29250*10(-4) 30
Heavy Work 1.65850*10(-4) 20

The problem with the heat-FED is:

A methodology based on additive FED similar to that used with toxic gases
may be applied and, provided that the temperature in the fire is stable or
increasing,

The agents move and they might go from hot air to cool air and
once again to hot air etc. Well, to be conservative, on could
just keep adding the heat-FED value.

Attached is a copy of the present FED calculation
in FDS and FDS+Evac (DEVC FED output and the agents
use the same FED subroutine).

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2011-10-10 10:00:22
- **Labels added**: Type-Enhancement, Milestone-FDS_6.0, Application-FDS
- **Labels removed**: Type-Defect

<hr>
- _Attachment: [FDS+EVAC_Guide_FEDpart.pdf](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-1502/comment-1/FDS+EVAC_Guide_FEDpart.pdf)_

**Comment by gforney** [comment]
```
Timo, I need to visualize FED in a slice file, so that one can more easily see spatial
regions where conditions are bad or to compare hazardous regions for two different
scenarios.  I was going to create a separate issue but thought it fit in well here
- can you do this? (I'll trade you a person smokeview object of your choice for it!!)
```

Original issue reported on code.google.com by `gforney` on 2011-10-11 20:27:25

**Comment by gforney** [comment]
```
Hi Glenn,

The problem with FED is that it is a dose. It is a
time integral. As such, you can not plot it easily 
as  a slice file, because you do not have an array
that saves that information, nor you can calculate
it using some algebra  from the arrays in FDS at a
given time step.

Well, what could I do? Make an "instaneous FED",
take the gas concentrations etc and say that they
are constants and integrate 60 seconds (no need 
for numerical integration, you can do it analytically).
The ouptut slice would then show, what would happen,
if you would be there one minute. Well, of course,
you starts "fresh", no previous dose. But this should
give a nice idea how lethal the conditions are. One
could add also an another slice ouptut, 1/FED_instaneous,
so this would say how long it would take to incapacitate
a person at that position if the conditions would be
constant after that.

So, we should add the two slice outputs:

 FED_inst: One should define a nice name for this
 1/FED_inst: And this needs also a nice name

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2011-10-12 08:00:20

**Comment by gforney** [comment]
```
Hi Glenn,

FED is directly related to human incapability, i.e; if there is a location which contains
high toxic/heat effects and if there are no agent mobility in that particular region
then FED cannot be calculated simpily based on that particular location. I think FED
is not location dependent, it depends on agent path.  

I fell FED has to be calculated as the time integral of Toxicity and Heat effect in
the path traveled by the agent. FED has to be shown as agent attribute in Smokeview
for visualization.

And one more suggestion to Timo, in the present version if an agent FED level exceeds
unity, his velocity will be become zero. Can the same shown like agent collapse and
falls on the floor. 


```

Original issue reported on code.google.com by `akulachaturvedi` on 2011-10-15 07:29:51

**Comment by gforney** [comment]
```
Hi!

I looked the evac.f90 and dump.f90 source codes, first evac.f90:

    ZZ_GET(1:N_TRACKED_SPECIES) = MESHES(nom)%ZZ(I,J,K,1:N_TRACKED_SPECIES)
    fed_indx = FED(ZZ_GET,MESHES(nom)%RSUM(I,J,K))

and  in the agent part there is (fed_co_co2_o2 is the above fed_indx value):

             HR%INTDOSE = DTSP*HUMAN_GRID(II,JJ)%FED_CO_CO2_O2 + HR%INTDOSE

Dump.f90:

   CASE(109)  ! FED
      ZZ_GET(1:N_TRACKED_SPECIES) = ZZ(II,JJ,KK,1:N_TRACKED_SPECIES)
      GAS_PHASE_OUTPUT = FED(ZZ_GET,RSUM(II,JJ,KK))

The FED-device has the "time integral" flag, so the time
integral is done in dump.f90.

         ELSEIF (DV%STATISTICS=='TIME INTEGRAL') THEN GAS_STATS

So, if a SLCF output, we do not do any time  integral, just write
out the fed_indx, which is the stuff inside the time integral.
The FED-function in func.f90 probably has seconds as time units,
whereas in the litterature minutes are usually used. One should
check this. The output could  be fed/minute, that could be
a nice output slice. 

So, I should perhaps do this, but for the next two weeks I'm
too busy...

How to test this? I have already FDS+Evac verification test
cases for the FED, so these could be used. There might also
be FED verification case at the FDS test cases. There the
different toxic gas DEVC output together with FED DEVC output
are written to a file and then these are checked. I use Excel
for the FDS+Evac checks. My test cases are such that there is
constant toxig gas concentrations (no x,y,x dependence), so
the SLCF and DEVC output could be compared (DEVC output for
species => calculate FED integrand by Excel etc, compare the
number at the SLCF file).

Glenn, how are the units, can the user give the units for
Smokeview? And can one set the desired units at the
SLCF lines? I have not read the FDS users guide so well...

The units: (1/s, 1/min (default), 1/hour) could be nice.

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2012-05-23 08:35:59

**Comment by gforney** [comment]
```
This addition will probably be done within the next month or so, because we have here
at VTT a project that would  need this output quantity. So I change the status of this
Issue to "Started". The output would be both DEVC and SLCF output and the units would
be minutes. So an "instantaneous fed" would mean: If an agent would be placed at this
time point to this x,y,z location and the gas concentrations would be thosa at the
present time and stay constant afterwards, how long would an average human be alive
there? So, the value would be one over the integrand in the FED time integral.

I will use minutes, because a minute is a good time unit for humans. So the answers
to the questions of Fire Brigade would be "Well, the humans would survive in the staircase
of an appartment house about 20 minutes, if they would enter the staircase at this
time point". So, one could use this value in addition to the visibility distance (how
many metres) to make the results of the calculations more easily understood by FB etc
bodies. So, visibility is good for firemen and their operations. They would like to
see well. And 1/fed output for estimating the conditions for rescue of persons or if
some person has decided to rescue himself, what would happen?

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2012-08-15 08:00:54

**Comment by gforney** [comment]
```
One question:

How does the resting/light work/heavy work affect other FED equations
than the CO part? The present version of the FED routine calculates
also HCN, NO etc. How are these equations affected with the RVM
(litres per minute)? Chapter 2-6 SFPE 4th ed does not seem to
say anything about this, at least at a glance. 

So, should I use the RVM values given for the CO, so assume that the
other data is for "light work" and and have factors like:

  resting = 8.5/25 "less fed for HCN"
  heavy work: 50/25 "more fed for HCN"?

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2012-08-21 13:22:50

**Comment by gforney** [comment]
```
Heat/radiation FED to be done.

A Question to the Issue starter:

  Problem: CO and at rest/light work/heavy work ok, but how others?
           Should I use same factor (RMV/D) for other FED components:
           NO, NO2, Cyanide, CO2 hyperventilation factor, low O2?

          FED_LCO = (3.317E-5 * (C_CO)^1.036 * RMV * (dt/60)) / D

! Nitrogen oxides (NOx, here NO + NO2)
! FED_LNOx = C_NOx/1500 * (dt/60);
!   with C_NOx = C_NO + C_NO2, all in ppm

! Cyanide
! FED_LCN = (exp(C_CN/43)/220 - 0.0045) * (dt/60);
!   with C_CN = C_HCN - C_NOx, all in ppm

! Carbon dioxide (CO2) induced hyperventilation:
! FED_VCO2 = exp(0.1903*C_CO2/1E4 + 2.0004)/7.1;

! Low oxygen (O2)
! FED_LO2 = 1/exp(8.13 - 0.54*(0.209 - C_O2/1E6)) * (dt/60);


! Carbon monoxide (CO)
!          at rest    light work heavy work
! RMV_FED /8.5_EB,    25.0_EB,   50.0_EB /
! D_FED   /40.0_EB,   30.0_EB,   20.0_EB /
! RMV/D   /0.2125_EB, 0.8333_EB, 2.5_EB/ 


Done: FED_ACTIVITY 1: at rest, 2: light work,  3: heavy work
Todo: Add to the manual and test. (DEVC/PROP inputs, PERS input for evac)

So, at the (some) PERS namelist give: FED_ACTIVITY=1 for "at rest"
CO FED values (Purser in 4th Ed. SFPE Handbook). Default is 2, i.e.,
light work like it used to be in FDS+Evac.

The DEVC FED-output (QUANTITY='FED') can have also PROP_ID='whatever',
and the PROP-namelist have input FED_ACTIVITY, default here also 2,
so if "light work" output is wanted, then no need to give PROP_ID on
the DEVC namelist.

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2012-08-24 12:14:42

**Comment by gforney** [comment]
```
I should add: Source code FDS 6.0.0 SVN number 12260 have these things.

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2012-08-24 12:18:36

**Comment by Er9y714** [comment]
Is heat and radiation effect going to be incorporated to FED calculation in the future?

**Comment by tkorhon1** [comment]
Well, these are on my ToDo list. They will be added, when I have a need for that. The heat should be very easy one. Radiation might need more programming effort.

Do you have some nice reference to a formula that can be used for the heat FED? SFPE Handbook has some information, of course. But is there any recent "new" formulas/criteria/etc published? What is the most common "heat FED criterion"?

Programming the heat FED is fast, but to do the "literature review" for the "best model" is not so fast...

TimoK

**Comment by Er9y714** [comment]
Thanks for the reply. Unfortunately, it is not my expertise and I have not come across with recent studies.

**Comment by evac46** [comment]
Is the integration of heat and radiation effects in FED calculation progress ? When do you think that a version considering a thermal FED could come out?

**Comment by godisreal** [comment]
I think FED usually refers to the toxic gas inhaled by a person, and thus it is an integral on time axis, characterizing the cumulative effect of the toxic gas.  Heat and radiation are not gas inhalable.  So is there any effective dose for heat radiation?  I suppose not.

**Comment by tkorhon1** [comment]
Well, it would be very easy to implement "thermal-FED", I should check the latest SFPE Handbook, if there is formulas how to calculate this. There is the gas temperature at the head level of the agents known in the evac.f90, so one just need to add the formulas to calculate it.

SFPE Handbook, 5th ed:
63 Assessment of Hazards to Occupants from Smoke, Toxic Gases, and Heat  p. 2373
The Exposure of Fire Victims to Heat

Well, there seems that there is not a very good and simple equation to put in the source code. One should know the radiation flux (kW/m2) and the gas temperature. One does not know the radiation flux generally, but the integrated radiation intensity could be used, as a first approximation. So, using these two, one could calculate something. But the equation for "heat FED" in SFPE HB says, that it holds when the temperature (or exposure) is constant or rising. But what happens, if the agent goes to a cooler place and then once again to a hotter space? Well, a conservative approach would be jus to continue to sum the heat-FED.

So, I could program the equations in the source code, if someone will give the algorithm in a simple form, that could be programmed easily. I.e., write a heat-FED calculation in a "pseudo programming language".

TimoK

**Comment by godisreal** [comment]
Hi, Timo.  I notice that you have a verification suite for FED.  
fed_CO2_verification.fds  
fed_CO_verification.fds   
fed_O2_verification.fds
I read Evac User Guide Section 4 (Testing and Verification).  If I understand your work correctly, you compare Evac FED with FDS FED and verify that two results coincide.  However, is there anything to be verified for FED effect on agents?   Based on your Fortran code, it seems that if HR%INTDOSE >= 1.0_EB, then the agent falls down.  Is it the only FED effect on agents?  Many thanks.

**Comment by tkorhon1** [comment]
I also check the FED using the DEVC output for O2, CO, and CO2 and do the FED calculation in an Excel workbook.

The FED does not affect the agents much. Typically, just the HR%INTDOSE >= 1.0_EB has some effect on the agents. The default thing in the door selection algorithm is to use the smoke density (visibility) to change the behaviour of the agents. There is an user input, that the FED values could be used to consider if a door is usable or not. That used to be the defaylt, say, ten years ago.

TimoK

**Comment by godisreal** [comment]
Yes.  I observe my test result and I agree with you that FED does not affect the agents much compared with smoke effect.  When I add smoke force in #1417, the smoke force is predominant.  Then I compare FED with smoke spread in smokeview, and I find that smoke spreads very fast and FED does not.  I think the result looks a little strange.  If FED model is based on Purser's paper, what is the model for smoke spread (SOOT) in FDS?  Is there any theoritical justification for smoke spread model?  
Anyway, this is not directly related to evac module, but the consistency of FED and smoke spread model in FDS module, and it does affact evacuation simulation result.

**Comment by drjfloyd** [comment]
The theoretical justification for the smoke spread is the Navier Stokes equations, the fundamental equations of fluid flow. Keep in mind that it takes very little soot to show a visible change in Smokeview. A soot density of 3E-5 kg/m^3 gives a 10 m visibility to unlit objects and will be easily noticeable in Smokeview. Since CO yields are typically similar to soot yields (same order of magnitude), a 3E-5 kg/m^3 CO density would only change the FED at a rate of 0.001/min.

**Comment by welsouki** [comment]
> Well, it would be very easy to implement "thermal-FED", I should check the latest SFPE Handbook, if there is formulas how to calculate this. There is the gas temperature at the head level of the agents known in the evac.f90, so one just need to add the formulas to calculate it.
> 
> SFPE Handbook, 5th ed:
> 63 Assessment of Hazards to Occupants from Smoke, Toxic Gases, and Heat p. 2373
> The Exposure of Fire Victims to Heat
> 
> Well, there seems that there is not a very good and simple equation to put in the source code. One should know the radiation flux (kW/m2) and the gas temperature. One does not know the radiation flux generally, but the integrated radiation intensity could be used, as a first approximation. So, using these two, one could calculate something. But the equation for "heat FED" in SFPE HB says, that it holds when the temperature (or exposure) is constant or rising. But what happens, if the agent goes to a cooler place and then once again to a hotter space? Well, a conservative approach would be jus to continue to sum the heat-FED.
> 
> So, I could program the equations in the source code, if someone will give the algorithm in a simple form, that could be programmed easily. I.e., write a heat-FED calculation in a "pseudo programming language".
> 
> TimoK

Hi Timo,
Any update on this? Probably the best formulae to use are those in the SFPE Guide 
to Human Behavior in Fire, Second Edition - Section 7.1.1.7. I've attached that section for your reference. 
[Thermal FED.pdf](https://github.com/firemodels/fds/files/4474515/Thermal.FED.pdf)

**Comment by tkorhon1** [comment]
Yes, I could try to add these SFPE based formulas somehow. But right now I do not have time. I was planning to do some FDS+Evac stuff during this spring, but I was too busy at home and at work. Now I have a couple of hours before summer holiday to go through these Issues. So, I'll postpone this enhancement to later time.

**Comment by Er9y714** [comment]
@tkorhon1 Good point with thermal FED about " `if the agent goes to a cooler place and then once again to a hotter space? "`. In most simple scenarios I think there is only one fire source in the model. If an agent chooses the right path, they should not come back to the fire compartment. Therefore I think being exposed to heat for a second time is an exception. 

I propose having toxic and thermal FED combined not by default. Thermal should be an option or separate output column/slcf etc. 

Regarding using integrated intensity, Is filtering only the top half of the sphere more realistic for hot smoke layer? Or is it not conservative enough since it will miss the radiation from the flames (radiation coming from the bottom half of the sphere) if the agent is close to the fire?

Bytheway, is there any option for filtering radiation received at the top half of the sphere (2 pi angle) on integrated intensity slicefile?

**Comment by gjaeger** [comment]
@tkorhon1 What about this issue? Is this also a thing of the past with PR #10089 and can it be closed?

**Comment by mcgratta** [comment]
If this is still a problem, and not necessarily tied to Evac, start a new issue.

**Comment by welsouki** [comment]
This feature could be very handy in fire engineering in assessing occupant tenability against a more comprehensive criterion than the usually used simplistic and independent criteria for conv & rad.
Could it be untied to Evac if FDS user can input the "path" along which the FED is integrated?

**Comment by drjfloyd** [comment]
A while back we added PATH_RAMP to a particle inserted via INIT which defines an x,y,z path for a particle. I haven't tried this but I think you could insert a particle with a PATH_RAMP and use INIT_ID on a DEVC with QUANTITY='FED' to do the FED as the particle moves around.

**Comment by gjaeger** [comment]
@welsouki Did you read [this](https://groups.google.com/g/fds-smv/c/0nh_v6gt4II) (_FDS & SMV Discussions - FDS 6.7.7 Maintenance Release_)? 

> We are in touch with Timo and the Pathfinder developers at Thunderhead Engineering (the makers of PyroSim) to ensure that FDS outputs whatever information that an evacuation model would need, in particular, the spatially and temporally resolved smoke concentration from which any number of toxic gases can be inferred.

This could be interesting for you (and all readers) for future versions.

**Comment by gjaeger** [comment]
@mcgratta I think we can close this old issue.

**Comment by mcgratta** [comment]
Great, thanks.
