### ISSUE TITLE
SMV 6.1.5 - HUMAN_SPEED - wrong colorbar?

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2021]
```
FDS Version: 6.0.1 Serial OpenMP Disabled
FDS SVN Revision No. : 17534
Compilation Date : Tue, 26 Nov 2013
Smokeview Version: 6.1.5
Smokeview SVN Revision No.: 17492
FDS+Evac Version: 2.5.0
FDS+Evac SVN Revision No.: 17481
Operating System: Mac OSX 10.9

details: 
Is there a bug to show the human speed colorbar in smokeview? human_speed and human_altered_with_data
are activate. I attached the input file and a screenshot to show the "wrong" colorbar.

Gregor
```

Original issue reported on code.google.com by `gregor.jaeger` on 2013-12-11 21:13:04

<hr>
- _Attachment: [example.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2056/comment-0/example.fds)_
- _Attachment: example.png<br>![example.png](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2056/comment-0/example.png)_

**Comment by gforney** [comment]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `randy.mcdermott` on 2013-12-12 21:11:04

**Comment by gforney** [comment]
```
I'll take a look at it.
```

Original issue reported on code.google.com by `gforney` on 2013-12-12 22:03:02

**Comment by gforney** [comment]
```
COLOR_METHOD = 0.0
This might not work, better is an integer, i.e.,
COLOR_METHOD = 0
But this is not the issue here.

I ran an example case, see the attached input file and the stdout/stderr
output. Here the coloring seems to work as it should.

And I ran the above example.fds file and there the coloring is not
working. Strange.

I'll check this out.

TimoK


TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2013-12-13 11:09:28

<hr>
- _Attachment: [evac_example1c.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2056/comment-3/evac_example1c.fds)_
- _Attachment: [evac_example1c.err](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2056/comment-3/evac_example1c.err)_

**Comment by gforney** [comment]
```
Well, this might be due to the fact that there are no initial
agents present in the .prt5 files. The agents are introduced
in the calculation using ENTR namelists, they are not 
generated before time < T_BEGIN like the EVAC namelist
agents.

Adding the EVAC line below to example.fds helps a little bit, we get
some colors, e.g., density colorbar seems to be reasonable as well as
the total_force colorbar. The contact_force colorbar is not looking nice,
because here all data is zero (probably, the agents are not touching
each others => no contact forces). But the speed is not nice, the
uppermost floor coloring is not good and the colorbar has values
starting from 1.0 and ending at 1.0. And I could not find where
to change min/max settings for evacuation coloring.

&EVAC ID= 'HumanNoDoorKnown', 
      NUMBER_INITIAL_PERSONS= 2,
      XB=  3.00, 4.00, 0.00, 2.00, 6.8, 7.6 ,
      AVATAR_COLOR= 'BLACK', AGENT_TYPE=2,
      PERS_ID= 'PERSONEN' / 

TimoK

```

Original issue reported on code.google.com by `tkorhon1` on 2013-12-13 11:28:23

**Comment by gforney** [comment]
```
> Well, this might be due to the fact that there are 
> no Initial agents present in the .prt5 files.

I added some initial agents and then the colorbars for density, speed and forces are
good.

> And I could not find where to change min/max 
> settings for evacuation coloring.
I've the same problem.

Thanks for the information about the Color_Method,
```

Original issue reported on code.google.com by `gregor.jaeger` on 2013-12-14 11:18:56

**Comment by gforney** [comment]
```
timo, I changed the owner to you.  If you think there are smokeview problems that need
to be adderssed, let me know. glenn
```

Original issue reported on code.google.com by `gforney` on 2013-12-16 14:04:55

**Comment by tkorhon1** [comment]
Well, I checked this today. It seems that the avatar coloring as colorbar is not working in Smokeview.
The colorbar scale is constant (10^20 is the scale). I tried agent speed and density, both gave the same colorbar "range".

This seems to be Smokeview feature, evacuation dump writes the same old stuff to the hard disk
(.prt5 files of evacuation meshes).

TimoK

**Comment by gforney** [comment]
Fixed - see issue 165
