### ISSUE TITLE
Entr line _ problem with probability

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2206]
```
FDS Version:6.0.1
SVN Revision Number:17534
Compile Date:26 November 2013
Smokeview Version/Revision: 6.1.5
Operating System: Windows 7

Hi, I'm using FDS+Evac to simulate emergency egress from a tunnel. What I want to model
is a scenario where agents are inside their cars, then agents exit from their cars
(at a specific time defined by me) and finally they move towards the emergency exits
and the portal of the tunnel.
I'm using the ENTR line, to simulate the doors of the car, so I insert agents inside
the tunnel in this way, by specifying the TIME_START of the entrance. This for all
the cars (that are modeled as OBST): each door is a different ENTR. My problem is that
I want to define a different probability of familiarity with the exits: some agents
will have prob = 1, some prob = 0.9, etc.. But FDS gives me the following error:
ERROR: ENTR line CAR 1 problem with probability, 0.9000 it should be zero or one.
I read in the Guide that ENTR works only with KNOWN_DOOR_PROBS equal to zero or one,
while by using the function EVAC different probabilities of familiarity can be defined.
So if I want to do this kind of study I have to change the model and use EVAC insted
of ENTR? I'm missing something or the ENTR line really works only with 1 or 0 ?
Thank you !
Giordana
```

Original issue reported on code.google.com by `gai.giordana` on 2014-09-12 11:00:37

**Comment by gforney** [comment]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `mcgratta` on 2014-09-12 11:55:55

**Comment by gforney** [comment]
```
Well, you can only use zero or one on the ENTR lines. The probability of known doors
is not "probability" even on the EVAC lines. It is mainly a shorthand for many EVAC
lines that have different list of known doors. Well, best way to explain is to give
a simple example:

&EVAC .... Known_door_names="doorA","doorB", known_door_probs=1.0,0.5,
      NUMBER_OF_AGENTS=100 /

Is a shorhand for (well almost equal, in the limit where the number of agents goes
to the infinity it is exactly equal):

&EVAC .... Known_door_names="doorA","doorB", known_door_probs=1.0,1.0,
      NUMBER_OF_AGENTS=50 /

&EVAC .... Known_door_names="doorA","doorB", known_door_probs=1.0,0.0,
      NUMBER_OF_AGENTS=50 /

For ENTRies could work similarly, but there was some programming difficulties (no memory
in the ENTR routine, or something else. Well, the known_door_names list was not saved,
it was there just in the initialization phase of the calculation, or something similar).


If you want to have random known doors for each car, then you should use EVAC
lines. The agent generated by an EVAC in the initialization phase will have definite
(not random) known doors during the whole simulation. The randomness is at the initialization
routine: If known_door_prob=1.0 for some door => this door will be known to this agent.
If known_door_prob=0.9, then there is 90% chance that this door is known for this specific
agent.

NOTE: If all known_door_probs < 1.0 then it might be that some agent does not have
any known doors. All doors are drawn as unknown at the initialization phase.

So, you could draw some random numbers yourself and make the input file according to
these random numbers for the known_door_names. But this means that you should manually
edit very many input files, not convenient. So, the EVAC would be the choice. This
means a little bit more work for the cars, if you want the agents be "inside the car"
before the evacuation. If it is enough that they stand still bisides the car, then
the input file is easier to make. But in this case the agents might move before the
given Tdet+Tpre, if the other agents are pushing them. So, put the agents (EVAC XB)
in such positions that the other agents are not pushing.

I'll set this issue "OnHold" and change its type to "Enhancement". So, if I sometimes
find time to program the ENTR so that it finds the known door information during the
simulation, then this is easily fixed. I just need to create a new variable that saves
the input information of the known_door_probabilities. Now I can not get this information
easily at times T > T_BEGIN. There is no good reason why this is so. I just wrote the
program so. I first wrote the EVAC stuff, i.e., to generate the initial agents. Later
the possibility to add agents during the simulation was added.

Wbr,
Timo

PS. I was on a two week holiday without internet. I do not like internet on my holidays.

```

Original issue reported on code.google.com by `tkorhon1` on 2014-09-30 14:48:01
- **Labels added**: Type-Enhancement, Priority-Low, Usability
- **Labels removed**: Type-Defect, Priority-Medium

**Comment by godisreal** [comment]
NOTE: If all known_door_probs < 1.0 then it might be that some agents do not have
any known doors. All doors are drawn as unknown at the initialization phase.  

My Comments: 
This is a little confusing.  I think there are two different concepts.  
The first thing is whehter an agent knows a door or not, and it is boolean logic (know it or not know it), and it is characterized by known_door_names in the current program (evac.f90).  The second issue is how an agent is familiar with a known door, and it should be measured by a real number from 0 to 1 (Just like a probality).  An agent can only be familiar with a known door.  If one does not know the door, there is no issue of being familiar to it.  Thus, the familiarity measure is specified by known_door_probs, and it is only effective for the known doors.  That is, known_door_probs=1.0 means being fully familiar with a door while known_door_probs=0.0 means unfamilarity.  

In EXIT namelist Users are also allowed to give a value in between like 0.6 or 0.3 (0.0<=known_door_probs<=1.0). This is very similar to probablity, and familiarity to an exit is thus understood as the frequence of using the exit in the historical data (prior information).  From there one can infer the probablity of how agents select the doors and exits in the simulation run.  

However, exiting program (evac.f90) only provides a good user interface, but the inner algorithm of exit selection is far from perfect.  The algorithm generates a random number and compare it with known_door_probs to assign the exit either familiar or unfamiliar (boolean logic).  A better method is integrating the real familiary measure in the preference order in the door selection algorithm (User Guide pp. 29, Table3).  As a result, the familarity is not a yes/no logic, but with the real number given by known_door_probs.  

So my question is how to change the preference order of the door selection algorithm in evac.f90.  That provides a solution to this important problem.

**Comment by mcgratta** [comment]
Closing. This issue is stale. If this is still a problem, open a new issue.
