### ISSUE TITLE
FDS crashes if an HVAC damper is used without a valid control / device attached

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2213]
```
Please complete the following lines...

FDS Version: 6.1.1
SVN Revision Number: 19882
Compile Date: Thu, 10 Jul 2014
Operating System: Windows 8 x64

Describe details of the issue below:

Running the attached model causes FDS to crash with no feedback. Presumably the issue
is that a damper should only be defined if there is an associated control.
```

Original issue reported on code.google.com by `albrecht@thunderheadeng.com` on 2014-09-23 19:40:50

<hr>
- _Attachment: [test fan vent.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2255/comment-0/test fan vent.fds)_

**Comment by gforney** [comment]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `mcgratta` on 2014-09-23 19:56:33

**Comment by gforney** [comment]
```
I'll take a look.  You are probably right that we need to trap that as an error.
```

Original issue reported on code.google.com by `drjfloyd` on 2014-09-23 20:06:35
- **Labels added**: Application-FDS

**Comment by gforney** [comment]
```
Fixed.  If no device or control is specified, the damper will be assumed open in the
same way that a fan is assumed on and an aircoil is assumed on.  I'll also add a note
to the guide about this.
```

Original issue reported on code.google.com by `drjfloyd` on 2014-09-23 20:14:11

**Comment by gforney** [comment]
```
changing status

```

Original issue reported on code.google.com by `drjfloyd` on 2014-09-23 20:18:36

**Comment by gforney** [comment]
```
Seems like a good solution to me. This is how I had expected it to work. Thanks!
```

Original issue reported on code.google.com by `albrecht@thunderheadeng.com` on 2014-09-23 20:59:40

**Comment by drjfloyd** [comment]
This can be closed.  Have edited the guide to clear up other entries for HVAC (AIRCOIL and FAN)
