### ISSUE TITLE
Add a "hole" feature to MEAN_FORCING

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2245]
```
It seems it would be useful to prescribe regions of the domain where MEAN_FORCING affects
the flow and regions where it does not.  For example, if you have a mean wind but want
a structure--which may have various ZONES or other complications--applying MEAN_FORCING
inside the structure is likely to be problematic.

The goal of this enhancement is to first simply create a HOLE-type feature that will
CYCLE a certain region prescribed by the user with an XB.  This should handle the vast
majority of the cases we are interested in in the near term.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2014-11-12 19:34:16

**Comment by gforney** [comment]
```
Prescribing regions of the domain where MEAN_FORCING affects the flow could be very
useful.

Alternatively, if you have multiple meshes then it could be nice to specify a mesh
 number where MEAN_FORCING is applicable.
```

Original issue reported on code.google.com by `prasad.kuldeep` on 2014-11-12 19:40:14

**Comment by gforney** [comment]
```
Following and will comment as necessary.  Thanks Randy!
```

Original issue reported on code.google.com by `Stephen.Olenick` on 2014-11-12 19:40:55

**Comment by gforney** [comment]
```
Prescribing regions of the domain where MEAN_FORCING affects the flow could be very
useful.
http://wdfshare.blogspot.com
```

Original issue reported on code.google.com by `the961beast` on 2015-03-17 07:37:52

**Comment by gforney** [comment]
```
Thanks for the comment.  It is good to be reminded of this Issue as we get ready for
6.2.0 release.  I think I can get the HOLE stuff working for MEAN_FORCING.

@the961beast: Are you aware that you can use a 'VELOCITY PATCH' to prescribe the velocity
field (using an immersed boundary technique) in a certain region of the flow?  See
Sec. 15.3.3 of the user guide.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-03-17 12:32:24

**Comment by gforney** [comment]
```
All:

This should be fixed with the latest code.  So, this will be available with FDS 6.2.0,
which is undergoing validation runs right now.

The way it works is to simply by-pass forcing for any region where a HOLE has been
specified.  There is a verification case to use as an example in

FDS-SMV/Verification/Flowfields/mean_forcing_hole.fds

Note that I changed the forcing function so that the user must specify the forcing
time scale using DT_MEAN_FORCING.  It just does not make sense to tie this parameter
to the LES DT.

@Kuldeep: There was a bug in the way the RAMPS were implemented for the Z component
of the forcing.  So, if that is used in your ABL simulations, you should rerun those.

Let me know if you have any questions or problems.

@Glenn: SMV 21827 was throwing a seg fault if you add back the 'V-VELOCITY' DEVC in
the above verification case.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-03-21 17:16:09

**Comment by gforney** [comment]
```
@Craig: There were a lot of things wrong with how the forcing was working around OBST.
 So, if you were using this in your reconstructions, check out the latest.

@Kevin: I added a comment in divg.f90 Line 1103 for you.  Why do we have U0, etc.,
set on a solid wall?  I think this should be removed.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-03-21 17:18:36

**Comment by gforney** [comment]
```
I'll check U0, but this might be needed. In divg.f90, we calculate DU/DT to achieve
a desired U at the wall. The U0 might be the ambient value that we are moving away
from.
```

Original issue reported on code.google.com by `mcgratta` on 2015-03-21 19:20:05

**Comment by gforney** [comment]
```
No, U0 is the value from MISC.  Usually it is U0=0.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-03-21 19:46:17

**Comment by gforney** [comment]
```
OK, I think I understand this better now.  I can do what I want to do by setting TAU_V=0.
and PROJECTION=T.  So I will leave as is (was).

My problem was the time ramp.  The point behind this "hole" in mean forcing is for,
say, a fire reconstruction where the flow inside the house should not be affected by
the forcing.  Nor do you want all the flow inside to be 10 m/s for first few seconds
while the ramp catches up.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-03-21 21:21:04

**Comment by kuramesh22** [comment]
Thanks for sharing. I hope it will be helpful for too many people that are searching for this topic.
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>

**Comment by kuramesh22** [comment]
Thanks for post this helpful post - Please visit for More information about -

<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>

**Comment by snileshsingh** [comment]
Online Birthday Cake Delivery @ http://www.cakengift.in/by-occasion/birthday-cakes-339.html , 
Order Cake in Delhi @ http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html , 
Order Cake in Noida @ http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html , 
Order Cake in Gurgaon @ http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html , 
Order Cake in Ghaziabad @ http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html , 
Order Cake in Faridabad @ http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html  ,

**Comment by snileshsingh** [comment]
Cake Delivery in Gurgaon @ http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html , 
Cake Delivery in Ghaziabad @ http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html , 
Cake Delivery in Faridabad @ http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html , 
Online Birthday Cake @ http://www.cakengift.in/by-occasion/birthday-cakes-339.html

**Comment by snileshsingh** [comment]
Online Cake Delivery @ http://www.cakengift.in/ , 
Cake Delivery in Delhi @ http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html , 
Cake Delivery in Noida @ http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html

**Comment by akashseo964** [comment]
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-pune/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-bangalore/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-hyderabad/

**Comment by akashseo964** [comment]
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-delhi/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-gurgaon/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by akashseo964** [comment]
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-chennai/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-faridabad/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-noida/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-ghaziabad/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-thane/
To get best Packing and Shifting service at affordable price. Visit:-
http://www.expert5th.in/packers-and-movers-navimumbai/

**Comment by akashseo964** [comment]
http://www.expert5th.in/packers-and-movers-pune/

**Comment by CakeDelivery** [comment]
[Online Cake Delivery](http://www.cakengift.in/)
[Cake Delivery in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Cake Delivery in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)

**Comment by CakeDelivery** [comment]
[Cake Delivery in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Cake Delivery in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Cake Delivery in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)
[Online Birthday Cake](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)

**Comment by CakeDelivery** [comment]
[Online Birthday Cake Delivery](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)
[Order Cake in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Order Cake in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)
[Order Cake in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Order Cake in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Order Cake in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)

**Comment by mcgratta** [comment]
This is done
