### ISSUE TITLE
Numerical Instability from HVAC Leakage

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2299]
```
Please complete the following lines...

FDS Version: 6.1.2
SVN Revision Number: 20564
Compile Date: 1/26/14
Smokeview Version/Revision: 20769
Operating System: Windows 7 x64

Describe details of the issue below:
I've been running this model and it continues to crash from numerical instability within
the first 30 seconds. I believe the issue is with the leakage through the door. Your
assistance with this is greatly appreciated.
```

Original issue reported on code.google.com by `geri.martin2` on 2015-01-30 18:54:40

<hr>
- _Attachment: [Leaky_Rooms.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-0/Leaky_Rooms.fds)_

**Comment by gforney** [comment]
```
This file is too complicated. Eliminate as much of the geometry and other things (RAMPS,
etc) so that the problem is easier to pin down. Try to reduce the grid size.
```

Original issue reported on code.google.com by `mcgratta` on 2015-01-30 20:00:06

**Comment by gforney** [comment]
```
Open your case and smoke and type g a couple of times to get the grid to show with coordinates.
 Use the arrow keys to move the grids to the edges of your zone inputs.  It looks like
your zones overlap the walls due to how the obstructions snapped to the grids.  If
you concur, redefine to make sure each zone is independent of the other (just shrink
the extent of XB for each ZONE some and FDS will find any other connected cells). 
See if that solves your problem.

If not post the corrected case and in the process it would help if you make the obstructions
for leakage different simple colors to make it easier for me to compare the inputs
to the smokeview image (i.e. rather than all the same RGB on the SURF inputs make one
leak path COLOR='RED' one 'GREEN' etc).
```

Original issue reported on code.google.com by `drjfloyd` on 2015-01-30 20:14:34

**Comment by gforney** [comment]
```
correction: "Open your case in smokeview"

```

Original issue reported on code.google.com by `drjfloyd` on 2015-01-30 20:33:55

**Comment by gforney** [comment]
```
I reduced the coordinates defining the pressure zones, eliminated some of the other
things complicating the file, and added colors to identify the flow paths. The file
is still crashing. I haven't reduced the grid size yet, I'm going to try that now.
```

Original issue reported on code.google.com by `geri.martin2` on 2015-02-02 19:29:00

<hr>
- _Attachment: [Leaky_Rooms1.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-4/Leaky_Rooms1.fds)_

**Comment by gforney** [comment]
```
Thanks for helping to simplify the file.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-02 19:35:03

**Comment by gforney** [comment]
```
Fails at half resolution.  I wondered if perhaps the open boundaries with one live gas
cell were an issue, so I reduced the domain so to be only the room and it still fails.
 Putting in some debug, the HVAC mass flows and zone pressures never go off the rails.
 Same for the wall boundary condition.  The plot3d file shows that whatever is happening
is by a leakage VENT, but the boundary conditions are fine. I am not sure the root
cause lies within the HVAC model.  I will continue digging to see if I can figure anything
out.  I've attached my version.  It fails at about 16 s.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-02 20:33:28

**Comment by gforney** [comment]
```
tried again after the fix for Issue 2346 and still failing near 16 so the two issues
are not linked.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-09 20:30:53

<hr>
- _Attachment: [Leaky_Rooms2.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-7/Leaky_Rooms2.fds)_

**Comment by gforney** [comment]
```
Kevin and Randy, 

Any thoughts on this one?  The plot3d and .out file indicate the problem is happening
at ~56,41,1.  If I print the wall bc values coming out of HVAC BC, everything looks
fine.  Temperatures, velocities, and species values are not substantially different
than in the time prior to the instability.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-10 21:29:53

**Comment by gforney** [comment]
```
I'm running Leaky_Rooms_2 now.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-10 21:32:51

**Comment by gforney** [comment]
```
I tried to clean up the case a bit more to rule out some features like THICKEN. But
in the attached, I seem to have lost leakage on the left and right walls, but don't
understand why.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-11 16:55:52

<hr>
- _Attachment: [Leaky_Rooms_Clean.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-10/Leaky_Rooms_Clean.fds)_

**Comment by gforney** [comment]
```
I'll look into it once I get my compiler working again.  I just updated and now nothing
works.  The HVAC BC routine looks at SF%LEAK_PATH and WC%PRESSURE_ZONE to determine
whether or not to include a wall cell in the averaging process for a duct node for
a leak.  Probably either the surface or the pressure zone is not getting set right
for those cells.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 19:13:07

**Comment by gforney** [comment]
```
I got it to work by making those boundaries one cell thick. They now take up one cell
of the domain.

I have continued to simplify the case, but still get the instability. Good news is
that I have eliminated alot of extra stuff.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-11 19:15:30

**Comment by gforney** [comment]
```
It should work on the exterior of the domain.  We aren't setting something in the wall
array correctly in init.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 19:23:22

**Comment by gforney** [comment]
```
SF%LEAK_PATH isn't set for those cells for some reason. 
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 20:10:57

**Comment by gforney** [comment]
```
It appears to work in the Leaky_Rooms2 case. I just cleaned up the XB's a bit to make
things easier to understand. Not sure what I changed.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-11 20:12:59

**Comment by gforney** [comment]
```
After the 4th OBST (the -x boundary) the wall is set correctly.  Partway through the
6th OBST it gets reset.  Still digging.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 20:35:49

**Comment by gforney** [comment]
```
When I reduce the HRRPUA and increase the vent size, so keeping the same overall HRR,
the simulation will run. My more complex configuration ran to completion and the file
I've attached below is currently at 150 seconds and still running. 

Continuing to adjust the vent area brings the file back to crashing around 24 seconds.
```

Original issue reported on code.google.com by `geri.martin2` on 2015-02-11 20:48:58

<hr>
- _Attachment: [Leaky_Rooms_Clean1.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-17/Leaky_Rooms_Clean1.fds)_

**Comment by gforney** [comment]
```
something is going wrong in ALLOCATE_STORAGE in the case in comment 10. 
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 20:57:38

**Comment by gforney** [comment]
```
and it appears to go back quite a ways as it is not working in 6.1.1
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 21:02:46

**Comment by gforney** [comment]
```
OK, I might split that off as a separate issue. I haven't made much progress on the
original case other than to create a very clean case that still fails at about 23 s.
See attached.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-11 21:37:51

<hr>
- _Attachment: [Leaky_Rooms_3.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-20/Leaky_Rooms_3.fds)_

**Comment by gforney** [comment]
```
I'll open and put in what I've found so far.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-11 21:39:30

**Comment by gforney** [comment]
```
Did this problem get solved? I no longer see the instability in Leaky_2 or 3, unless
I've changed some critical parameter. Could you check?
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-12 21:18:10

**Comment by gforney** [comment]
```
It appears to be working. I'm running the original case to see if it finishes.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-12 22:19:00

**Comment by gforney** [comment]
```
Did you make any changes to make this happen?
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-13 13:36:05

**Comment by gforney** [comment]
```
I think maybe the wall init issue may have done it. I haven't made any changes to the
source that would have done anything.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-13 20:29:24

**Comment by gforney** [comment]
```
Could you explain to me how this issue was resolved? I'm a bit confused.
```

Original issue reported on code.google.com by `geri.martin2` on 2015-02-13 21:29:12

**Comment by gforney** [comment]
```
In trying to fix this bug, we found another. We fixed the other bug, and now it seems
that the original bug is fixed too.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-13 21:41:01

**Comment by gforney** [comment]
```
The original case (with the ZONE statements corrected to not overlap) in comment #1
still fails at about 37 s. 

```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-16 12:16:15

**Comment by gforney** [comment]
```
Did this case work after the fix that we discussed in Comment #23?
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-16 14:26:46

**Comment by gforney** [comment]
```
The cases in comments 7 and 20 worked with SVN 21752. The original case in comment 1
(with the zone overlap fixed) fails with SVN 21752.
```

Original issue reported on code.google.com by `drjfloyd` on 2015-02-16 14:47:38

**Comment by gforney** [comment]
```
I have a few simpler versions of the original that fail, but I haven't yet put my finger
on why. I'll continue tomorrow.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-17 22:36:07

**Comment by gforney** [comment]
```
Some progress. Look at the two input files attached. Leaky_Rooms_1j fails and Leaky_Rooms_1k
succeeds. The only difference between the two is the material properties of the green
doors. Look at the cell-centered slices of H and DIVERGENCE and you will see alot of
noise in the 1j case. I haven't had a chance to dig into this, but this seems like
a good clue.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-20 22:07:25

<hr>
- _Attachment: [Leaky_Rooms_1j.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-32/Leaky_Rooms_1j.fds)_
- _Attachment: [Leaky_Rooms_1k.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-32/Leaky_Rooms_1k.fds)_

**Comment by gforney** [comment]
```
I think I know what the problem is. The only difference between cases 1j and 1k is that
the "leaky" door is a thermally-thick solid in 1j, and it is INERT, or specified temperature
in 1k. For the latter, the wall temperature takes on the gas temperature whenever there
is normal flow going into the solid. In this case, it's about 0.3 m/s. For the 1j case,
the door does not take on the gas temperature, and there appears to be trouble vis
a vis divergences in the adjacent gas phase cells. I haven't figured out a way to fix.
In most leak cases, the leak velocity is mm/s. In this case, it's 0.3 m/s, which is
substantial and probably leading to an inconsistency at the boundary.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-23 19:04:38

**Comment by gforney** [comment]
```
There is another wrinkle in this. Case 1ff runs, and 1gg fails. The only difference
is whether obstructions at the boundary are declared as OBST or VENT. This leads me
to believe that there is still something wrong with the boundary cell initialization.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-24 22:14:10

<hr>
- _Attachment: [Leaky_Rooms_1ff.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-34/Leaky_Rooms_1ff.fds)_
- _Attachment: [Leaky_Rooms_1gg.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-34/Leaky_Rooms_1gg.fds)_

**Comment by gforney** [comment]
```
It appears to me that the vents are not on a solid obstruction in case Leaky_Rooms_1gg,
which can only occur because it's the boundary of the mesh. Correct? Is the vent able
to accurately resolve the flow between the pressure zones if there are not any exterior
cells included in the mesh?

I'm currently in the middle of a couple simulations that have my FDS CPUs preoccupied,
but I'm curious if the case would run with the vents specified on a solid obstruction.
```

Original issue reported on code.google.com by `geri.martin2` on 2015-02-24 23:12:21

**Comment by gforney** [comment]
```
Cases 1ff and 1gg should be identical. That is, one could apply a thin solid obstruction
or a vent to an exterior boundary and the results should be the same. I believe that
this is a bug in the routine that processes boundary cells.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-25 13:19:22

**Comment by gforney** [comment]
```
I fixed the bug mentioned in #36. Now Leaky_Rooms_1ff.fds and Leaky_Rooms_1gg.fds produce
the same results (SVN 21820). That's the good news. The bad news is that now all cases
fail. So I think we are back to Comment #33. The numerical instabilities occur when
the obstruction with a LEAK_PATH applied to it is thermally thick. In these cases,
the flow induced by the leak is substantial, like 0.3 m/s, and there is a problem when
the flow encounters a hot obstruction.
```

Original issue reported on code.google.com by `mcgratta` on 2015-02-26 20:02:30

**Comment by gforney** [comment]
```
The attached case is 2d and fails in a few seconds. The problems arises when a surface
that can heat up has a strong leak through it. The problem seems to be related to the
divergence term related to the advection of enthalpy. I tried to "turn off" this term
at the boundary but this did not work, but I might not have done it right. Will try
again today. But at least we have a very simple case that fails quickly.
```

Original issue reported on code.google.com by `mcgratta` on 2015-03-02 14:24:00

<hr>
- _Attachment: [Leaky_Rooms_2d_b.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2341/comment-38/Leaky_Rooms_2d_b.fds)_

**Comment by gforney** [comment]
```
I committed code (SVN 21839) that fixes the simple cases. I am running the original
case now. The fix is to use a different surface temperature in the enthalpy advection
routine in divg.f90. The cases run fine if TMP_F, RHO_F, and ZZ_F are set to the nearest
gas cell value when UW>0. But we don't necessarily want TMP_F to be dictated by the
gas value in cases where it could be very different. So we create two values to hold
"near wall temperature". For now, WALL(IW)%ONE_D%TMP_F is the actual solid surface
temperature. WALL(IW)%TMP_F_GAS is the value we send to divg if UW>0. We might want
to rethink these names to make them more consistent. For example, TMP_F, RHO_F and
ZZ_F should be WALL attributes, and we can call ONE_D%TMP_F something else to indicate
that it is a true surface temperature. Another thing to consider is where to put this
logic. We want to put it in one place, so that we don't have a bunch of IF statements
scattered all over the code. As a placeholder, I have it just after the call to HVAC_BC
in wall.f90. That is, we just overwrite TMP_F_GAS, RHO_F and ZZ_F for the special case
of UW>0 after all the BCs are done. We could put this into its own subroutine and only
call it if we detect BOUNDARY_TYPE==SOLID_BOUNDARY and UW>0. It is not a common BC.


For now, I just want to make sure that nothing breaks.
```

Original issue reported on code.google.com by `mcgratta` on 2015-03-02 22:01:52

**Comment by gforney** [comment]
```
I suggest we leave _F as the "face" value of the gas phase cell and use something line
_S or _W as the "solid" or "surface" or "wall" value.  This will make it easy to write
up in the guides.
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-03-02 22:15:07

**Comment by chulann** [comment]
I wonder if this is linked to a problem I've been having. I have a case with pressure zones and leakage. After about 50 seconds, time steps would get smaller and smaller and then it would fail with numerical instability. After a lot of tracking down, I moved one wall from one pressure zone to the other and it solved fine. I have run this with FDS 6.2 and 6.3 with the same results. I've simplified as much as I can for bug reporting (the final 130 lines are just monitoring).

Can't attach the sample scripts so they are at:
http://killminus9.net/pressure_investigation_success.fds
http://killminus9.net/pressure_investigation_failure.fds

**Comment by mcgratta** [comment]
We can help you if you simplify the case. It will take us several hours just to figure out what you are trying to do.

**Comment by drjfloyd** [comment]
I would start by adding losses to your HVAC system. Having no loss is not physical and can cause stability issues.

**Comment by drjfloyd** [comment]
By coincidence, early today, prior to the new post to this thread, I had started running the original case and it now seems to be working ok. Given that we had found some wall cell initialization errors that we fixed, I doubt the newest post is the same root cause. If all are agreeable, I'd like to close the old issue and have the most recent one opened as a new issue.

**Comment by chulann** [comment]
mcgratta: Will do. The original case was a notional apartment opening to a corridor, which connects to the stair - a fire starts in the apartment, person escapes, smoke detector activates extract fan in corridor with the replacement air coming down the stair. If the stair door closes, the fan maintains a pressure of -50Pa in the corridor.

drfloyd: No objection from me about opening a new case. Apologies about the flow losses - I know you've helped me on this before (though I can't put my finger on the e-mail). I regularly forget them as all I care about is the necessary flow rate - I'll leave it to the M&E designer to worry about system losses and even position of fan! In addition, I've had difficulty finding good reference text and when the simulations don't go as expected, I regularly remove the loss parameter as a debugging step to "simplify" the case - though from what you're saying, it's exacerbating the situation.

I'll read back through the mailing list and get some loss parameters to use.

**Comment by chulann** [comment]
Just for the record, the "broken" case solved correctly when losses were added.

**Comment by drjfloyd** [comment]
Closing this issue.
