### ISSUE TITLE
Add ability for SMV to show boundary data on circular vents

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2309]
```
Glenn,

In the attached case, I would like to see the normal velocity as boundary data on the
circular vent.

Thanks,

Randy
```

Original issue reported on code.google.com by `randy.mcdermott` on 2015-02-10 16:19:25

<hr>
- _Attachment: [Sandia_CH4_1m_Test17_dx6cm.fds](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2351/comment-0/Sandia_CH4_1m_Test17_dx6cm.fds)_

**Comment by mcgratta** [comment]
This issue will be resolved with IBM. I am closing it.
