### ISSUE TITLE
Smokeview crashes loading zone fire file with ceiling vent

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2391]
```
Please complete the following lines...

CFAST Version: 7.0.0
SVN Revision Number: 2194
Compile Date: 5/3/2015
Smokeview Version/Revision: 22603
Operating System: Windows 7 64 bit

Describe details of the issue below:
Two CFAST files attached.  One without ceiling vent loads zone fire file fine.  Adding
a ceiling vent leads to a smokeview crash loading zone fire file.
```

Original issue reported on code.google.com by `rpeacoc` on 2015-05-04 14:09:58

<hr>
- _Attachment: [3R.in](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2433/comment-0/3R.in)_
- _Attachment: [3R_Ceiling_Vent.in](https://storage.googleapis.com/google-code-attachments/fds-smv/issue-2433/comment-0/3R_Ceiling_Vent.in)_

**Comment by gforney** [comment]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `mcgratta` on 2015-05-04 16:21:12

**Comment by gforney** [comment]
is this still a problem?

**Comment by rpeacoc** [comment]
This does not crash smokeview with SMV 6.3.1

**Comment by gforney** [comment]
thanks - will close issue
