### ISSUE TITLE
Initial values affect solution

### ISSUE THREAD

**Issue by SimonDrake-zz** [firemodels/fds#2440]
Fire Dynamics Simulator, Compilation Date: Fri, 26 Sep 2014, Version: FDS 6.1.2, SVN Revision No.: 20564, MPI Enabled; Number of MPI Processes: 8, OpenMP Disabled

I have produced a scaled-down tunnel simplification of a new build, in order to demonstrate an apparent problem in which the prescribed initial value of longitudinal velocity, is influencing the resulting air flow through the tunnel. The tunnel is 100m (100 cells) long, 12m (12 sells) wide, and 2m (4 cells) high. An open boundary with a dynamic pressure is specified at each portal, 0Pa at the left hand portal where x=0m, and 20Pa at the right hand portal where x=100m. The case is prescribed thus, in which the initial longitudinal velocity value U0=XX is the only parameter that is varied:

&HEAD CHID='simple_dp_test001a'  /
&MISC P_INF=84300.0, TMPA=38.0, U0=XX, V0=0.0, W0=0.0, ISOTHERMAL=.TRUE., BAROCLINIC=.TRUE.  /
&DUMP DT_RESTART=15.0 /
&TIME T_END=1200.0 /
&MESH ID='Mesh000', FYI='1mx1mx0.5m'   , IJK= 100,12,4, XB=0.0,100.0,-6.0,6.0,0.0,2.0 / count =4800
*\* Left hand portal:
&VENT SURF_ID='OPEN', DYNAMIC_PRESSURE=0.0, XB=  0.0,  0.0,-6.0,6.0,0.0,2.0  / [XMIN]
*\* Right hand portal:
&VENT SURF_ID='OPEN', DYNAMIC_PRESSURE=20.0, XB=100.0,100.0,-6.0,6.0,0.0,2.0 /  [XMAX] 
*\* On vertical centreline:
&SLCF PBY=0.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBY=0.0, QUANTITY='U-VELOCITY' /
&SLCF PBY=0.0, QUANTITY='PRESSURE' /
*\* Left hand portal:
&SLCF PBX=0.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBX=0.0, QUANTITY='U-VELOCITY' /
&SLCF PBX=0.0, QUANTITY='PRESSURE' /
*\* Right hand portal:
&SLCF PBX=100.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBX=100.0, QUANTITY='U-VELOCITY' /
&SLCF PBX=100.0, QUANTITY='PRESSURE' /
*\* 1m above road:
&SLCF PBZ=1.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBZ=1.0, QUANTITY='U-VELOCITY' /
&SLCF PBZ=1.0, QUANTITY='PRESSURE' /
*\* Flow into domain:
&DEVC ID='FLOW-LH-IN' , QUANTITY='VOLUME FLOW +', XB=  0.0,   0.0,-6.0 , 6.0, 0.0, 2.0  /
&DEVC ID='FLOW-RH-IN'   , QUANTITY='VOLUME FLOW -', XB=100.0, 100.0,-6.0, 6.0, 0.0, 2.0 /
*\* Flow out of domain:
&DEVC ID='FLOW-LH-OUT', QUANTITY='VOLUME FLOW -', XB=  0.0,   0.0,-6.0 , 6.0, 0.0, 2.0  /
&DEVC ID='FLOW-LH-OUT'  , QUANTITY='VOLUME FLOW +', XB=100.0, 100.0,-6.0, 6.0, 0.0, 2.0 /
&TAIL /

The tunnel has an adverse pressure gradient in the positive x (longitudinal) direction, so that for positive initial velocities the flow should reverse, and likewise for negative initial velocities the flow direction should be unchanged. The following parameter runs have been made for a 1200s duration in order to reach as near steady conditions as possible:

test001a  U0=  +1.0 resulting volume flux from right to left 135.91m3/s
test002a  U0=  0.0 resulting volume flux from right to left 134.32m3/s
test003a  U0=  -1.0 resulting volume flux from right to left 135.94m3/s
test004a  U0=  +2.0 resulting volume flux from right to left 140.61m3/s
test005a  U0= +10.0 resulting volume flux from left to right 155.15m3/s **changed direction!
test006a  U0= -10.0 resulting volume flux from right to left 192.64m3/s

Link goes to image of volume flow rate vs time (limited to 100s on horizontal scale) and described below.
![test](https://cloud.githubusercontent.com/assets/13106725/8417194/b630d348-1ea2-11e5-8ae3-35a39e0f452a.png)

All the results were compared by way of volume flow rates at the portals, written to a device file. In the first instance, a small difference in the resulting flows of the first two tests (U0=+1.0 and U0=0.0) raised my curiosity. So I decided to reverse the initial flow (U0=-1.0) and replicated the final result of (U0=+1.0) which is what I expected, it didn't however explain why when (U0=0.0) the solution differed. So I increased the initial flow a bit more (U0=+2.0) creating yet another solution, and then a lot more (U0=+10.0) which resulted this time in a reversal of the final solution, which was clearly wrong as flow took place against the pressure gradient. A final test with (U0=-10,0) provided yet another large deviation in the final solution, albeit in the right direction.

In the actual tunnel model I have been starting with U0=+10.0 and I think this is the reason I have not been able to reach a sensible isothermal solution, prior to later adding a fire. Hence the need to investigate using the simplified model. In all probability I have made some simple error in setting up my model but it is far from obvious to me. Would you kindly investigate what is an apparent influence of initial values on the final solution. Many thanks, in advance.

**Comment by rmcdermo** [comment]
U0 should not be thought of as the "initial" velocity, but rather the "far field" velocity.  It is discussed in the FDS Tech Guide, Eq. (4.80), and can be seen in pres.f90 near line 246.  It is not surprising that the results vary with different values of U0.

If the dynamic pressures you are setting represent reservoir pressures, then set U0 = 0.  Else, if you know the volume flow in the tunnel, just set it.

**Comment by SimonDrake-zz** [comment]
Thanks for the quick feedback. My error.
The purpose for modelling the full size tunnel is to initially set up an isothermal solution in FDS that matches an isothermal 1D solution. I then use the same impulse imparted by specified jet fans close to the entry portal, in a specific fire analysis for which the 1D solution has already predicted that critical velocity will be provided/exceeded. The FDS analysis will confirm or disprove that the prescribed impulse is enough to prevent smoke back-layering. Given that the tunnel is particularly wide relative to its height, this is far from a forgone conclusion. The main difficulty I am having is that with a very limited workstation, and limited time, the slow calculation of the isothermal solution is proving inhibitive. Additionally, the vent is pushing downhill, and there is a specified adverse pressure gradient. I currently have U0 set to 0m/s but from your last comment I got the impression that setting it to the tunnel bulk velocity might be more appropriate. Is that the case?

**Comment by rmcdermo** [comment]
That should work, if you know what the bulk velocity is.  But, in that case, I would think a prescribed volume flow or velocity bc would be a more robust boundary condition to use.

**Comment by SimonDrake-zz** [comment]
Since I will be allowing the smoke to back-layer first, and then activate the jet fans to reverse the smoke layer, I will need to maintain a pressure boundary at the entry portal as well as the exit portal, in order for the model to permit smoke to leave at the entry portal if the conditions dictate before the jet fans are activated.

I would also like to point out that I think the User Guide is misleading in this instance, see section 6.4.1 describing U0: 

"U0, V0, W0 Initial values of the gas velocity in each of the coordinate directions. Normally, these are all 0 m/s, but there are a few applications where it is convenient to start the flow immediately, like in an outdoor simulation involving wind."

I had earlier used U0=10m/s in the isothermal simulation, in order to accelerate the computation that had been painfully slow, my logic being that it might have been quicker to solve if the tunnel air slowed from a high momentum condition, rather than the jet fans having to overcome the inertia of the initially still tunnel air. However, I am on the right path now, and thank you for pointing me to the U0 definition.

**Comment by rmcdermo** [comment]
Thanks for pointing out the problem with the user guide.  I'll fix this.

What I wonder, though, is---if you do not have reservoirs at constant
pressure---how will you know what the pressure boundary condition are?
They will change as the flow volume and direction changes (unless they are
a large volume reservoir).  You may need to consider using the HVAC model
to link the long parts of the tunnel you can't afford to model with the
known reservoir pressures on either end of the tunnel.  The CFD part of the
domain then needs to be large enough so that you do not have two-way flow
at either boundary.

**Comment by rmcdermo** [comment]
Not sure why this part of my message was treated as if it came from you...

What I wonder, though, is---if you do not have reservoirs at constant pressure---how will you know what the pressure boundary condition are?  They will change as the flow volume and direction changes (unless they are a large volume reservoir).  You may need to consider using the HVAC model to link the long parts of the tunnel you can't afford to model with the known reservoir pressures on either end of the tunnel.  The CFD part of the domain then needs to be large enough so that you do not have two-way flow at either boundary.

**Comment by SimonDrake-zz** [comment]
Many thanks for your help.
