### ISSUE TITLE
jet_fan.fds wrong velocity on smokeview

### ISSUE THREAD

**Issue by studiozir** [firemodels/fds#2442]
I'm sorry. Maybe It's a trivial question. But I really don't understand.
If I run (FDS 6.2.0) jet_fan.fds (in the examples library) I see on Smokeview 4.5 m/s as the maximum velocity value.
![jet_fan_0993](https://cloud.githubusercontent.com/assets/13119067/8431687/6deae7c4-1f3b-11e5-9ce9-83a94dc6db7b.png)
It seems to be not appropriate with the code statements:
&HVAC ID='JET FAN',TYPE_ID='DUCT',NODE_ID='IN','OUT',VOLUME_FLOW=0.8,AREA=0.04/
0.8 m3/s and
0.04 m2
means 20 m/s of velocity.
Or I'm in wrong?

**Comment by rmcdermo** [comment]
Hit Alt-r to toggle the color bar limits in Smokeview.  Or use the dialog box.

**Comment by studiozir** [comment]
Thank you.
I don't want to waste your time because, for sure, I'm not a "expert user".
If I toggle the color bar limits in SV the situation doesn't change in the substance.
I expect an higher velocity in absolute value (near to 20 m/s).
Thank you again
![jet_fan_0993](https://cloud.githubusercontent.com/assets/13119067/8432273/5e8773c0-1f3f-11e5-8df9-8f1224e108cd.png)

**Comment by rmcdermo** [comment]
Jason,
Can you take a look at this?

**Comment by drjfloyd** [comment]
The DUCT containing the FAN is 0.04 m^2; however, the VENTs connecting the duct to the FDS domain are 0.16 m^2.  0.8/0.16=5 which is the velocity seen in the figure.

**Comment by studiozir** [comment]
Real time.
Great.
Thank you.

**Comment by studiozir** [comment]
I'm sorry, I don't want to be boring (I alredy was) but in the following file I can't find the mistake.
This is the tipical "jet fan" definition:
&OBST  XB=13.000,13.500,128.000,130.000,2.375,2.625,COLOR='BLUE', / JET.A01 body
&VENT  ID='JET.A01.IN', XB=13.000,13.500,130.000,130.000,2.375,2.625, SURF_ID='HVAC', COLOR='RED', /
&VENT  ID='JET.A01.OUT', XB=13.500,13.000,128.000,128.000,2.625,2.375, SURF_ID='HVAC', COLOR='GREEN', /
&HVAC ID='JET.A01.IN', TYPE_ID='NODE', DUCT_ID='JET.A01.DUCT', VENT_ID='JET.A01.IN',/
&HVAC ID='JET.A01.OUT', TYPE_ID='NODE', DUCT_ID='JET.A01.DUCT', VENT_ID='JET.A01.OUT',/
&HVAC ID='JET.A01.DUCT', TYPE_ID='DUCT', NODE_ID='JET.A01.IN','JET.A01.OUT', VOLUME_FLOW=2.300, AREA=0.125, DAMPER=.TRUE. ,CTRL_ID='SPRINKLER', /

So we have (&VENT named JET.A01.OUT) Dx_Dz=0.5_0.25=0.125 m^2
VOLUME FLOW is 2.3 m/s. FAN AREA is the same of the described above VENT.
2.3/0.125=18.4 m/s

![autorimessa_liv-1_0220](https://cloud.githubusercontent.com/assets/13119067/8492971/109b6796-2153-11e5-8c84-da7e15cce76a.png) (jet fan start)
![autorimessa_liv-1_0245](https://cloud.githubusercontent.com/assets/13119067/8492974/1c092f1e-2153-11e5-9e72-0a81d3766a47.png)
![autorimessa_liv-1_0298](https://cloud.githubusercontent.com/assets/13119067/8492975/202ff99c-2153-11e5-9eb3-50aa45f3a3d8.png)

In SV the higher velocity value shown is 8.06 m/s.
That is 18.4/8.06=2.3 times less than what I expected (2.3 ... just like the volume flow ... strange concurrence).

Another singularity ... I've tried to measure fan outflow velocity (on the whole VENT JET.A01.OUT area, with a XB DEVC STATISTIC MEAN) ... and the CSV results are around 18.4 m/s.

What is wrong?
SV visualization or FDS calculation?
Or, another time, my poor brain?

Best

**Comment by mcgratta** [comment]
There may not be a problem. From the appearance of your images, you probably only have one or two grid cells spanning your fan. Smokeview averages the velocity components at cell corners, and it does not scale the color bar from min to max values. Thus, one often sees lower than expected color values in Smokeview. If you want to check your input, use a single DEVC that is not spatially averaged in the grid cell that is immediately next to the fan. That is the true indicator of the flow speed in that particular grid cell.
