### ISSUE TITLE
back wall search for refined meshes

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#2449]
This was issue 2439 on google code, but it didn't seem to port over.  The issue is when a one cell thick obstruction lies between two meshes where one mesh is a higher resolution.  Then there is no longer a one-to-one mapping from lower resolution to higher for the back wall.

In general I think it is unlikely that any of the refined mesh cells on the backside will vary all that greatly from each other. I suggest that when we do the search for the backwall we just pick the first cell we find in the refined mesh and use that for the back of the low resolution mesh. Make this clear in the user's guide that this is what we are doing. Having to try and figure out which OBST this is happening to in a very complex input is not easy.

**Comment by drjfloyd** [comment]
This is a related bug.  The case below is two meshes with 1:2 grid ratio.  An obstruction spans the meshes and is two cells thick (one cell in one mesh and four cells in the other mesh).  The case dies with the error that there is a back wall cell mismatch, but this should not be the case since the obstruction is more than one cell thick.

&HEAD CHID='backwall'/

&MESH XB=0,1,0,1,0,1,IJK=5,5,5/
&MESH XB=1,2,0,1,0,1,IJK=10,10,10/
&MATL ID='foo',SPECIFIC_HEAT=1.,CONDUCTIVITY=100.,DENSITY=1000./
&SURF ID='foo',MATL_ID='foo',THICKNESS=0.01/
&OBST XB=0.8,1.1,0.4,0.6,0.4,0.6,SURF_ID='foo'/

&TIME T_END=1./

**Comment by mcgratta** [comment]
Agreed. This should be a simple fix.

**Comment by mcgratta** [comment]
I found a bug in the algorithm that searches for back wall cells of obstructions that are zero or one cell thick. Fixed it. The simple test case works now.

**Comment by mcgratta** [comment]
It is now possible to have a thin obstruction at a mesh boundary where the mesh resolution changes.
