### ISSUE TITLE
Atom balance error

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#2458]
Jason,

The following lumped species reaction (reaction 2) gives an atom balance error.  I put reaction 1 in so you would trust the other bits of the input file.  R2 should be balanced by construction.  It is

A1 + B = A2 + B

where A1 and A2 are the same.

Here is a link to the [input file](https://drive.google.com/file/d/0B4528gcI9D3HdEJpTWxyV2xxNlk/view?usp=sharing).

Randy

**Comment by drjfloyd** [comment]
what version of FDS are you using?

With both 6.2.0 release and current source I get this error:

ERROR: The default EXTINCTION MODEL is designed for 1 reaction. See Tech Guide

and if I delete the first reaction I get this error:

ERROR: Dissociation reactions must use finite rate chemistry.

**Comment by rmcdermo** [comment]
Sorry, I'm in my development code.  I've got both those errors commented out.

If I set A1 = A2 it works fine.  I suspect there is something that does not like having B as a reactant and a product, the null reaction.

**Comment by drjfloyd** [comment]
The issue is there can only be one nu for a tracked species in the current code.  We just have one array RN%NU with NU + or - depending on product or reactant.  Changing to a product array and a reactant array could be done but it will be an overhaul of the combustion routine.

**Comment by rmcdermo** [comment]
I am playing with ideas for extinction and reignition models and some of the ideas involve these null reactions.  I can see this sort of thing being useful.  I'd like to be able to do

A1 + B => A2 + B

where A1 and A2 are the same molecule and obviously B is the same on both sides.  The reason is that this can affect the amount of A1 that gets converted to A2 based on stoichometry with B.

How much of an overhaul are we talking about?

**Comment by drjfloyd** [comment]
not too big of an effort.  Mostly the reaction rate routine and input processing.

We do have the abiltiy to specify a collision species that appears on both sides.  Does that do what you need?

**Comment by rmcdermo** [comment]
I have not played with the collision species yet.  But in looking at the manual I do not think it would work for me.  I need there to be a stoichiometric relationship between A1 and B such that excess A1 will not be converted to A2.

**Comment by drjfloyd** [comment]
Right, OK. I see what you mean now. I don't think this would be very hard to do.  User inputs could stay the same and we would just change bookkeeping

**Comment by drjfloyd** [comment]
Randy,

What about using two reactions and another species:

(1) A1 + B => A1B
(2) A1B => A2 + B

(2) under the current logic would be a dissociation reaction and would have to be arrehnius. But you could set the rate to be effectively infinitely fast.  This should give you essentially the same as A1 + B => A2 + B

**Comment by rmcdermo** [comment]
If it is Arrhenius, does that mean I am stuck using the ODE solver instead
of "fast chemistry"?

**Comment by drjfloyd** [comment]
Anything other than simple chemistry uses the ODE solver:

   INTEGRATOR_SELECT: SELECT CASE (COMBUSTION_ODE_SOLVER)

```
  CASE (EXPLICIT_EULER) ! Simple chemistry
```

...
      CASE (RK2_RICHARDSON) ! Finite-rate (or mixed finite-rate/fast) chemistry
...
   END SELECT INTEGRATOR_SELECT

**Comment by rmcdermo** [comment]
Right, but each reaction is either FAST_CHEMISTRY or not.  If
FAST_CHEMISTRY then we by-pass the RK stuff.

**Comment by drjfloyd** [comment]
In the case of using Arrhenius you would be using RK2 and not the explicit euler.  I realize this adds cost and is not ideal, but does it get you moving forward without having to wait for an overhauled combustion routine?

**Comment by rmcdermo** [comment]
I'll give it a try.  I think that either you or Craig at some point added
FAST_CHEMISTRY=T on REAC or else set FAST_CHEMISTRY=T if A > big number.
If that is the case, I should be ok.

**Comment by rmcdermo** [comment]
I asked Craig but he did not remember---is there a good reason why we do
not allow dissociation reactions to be "fast"?

**Comment by drjfloyd** [comment]
I didn't code that bit up but my guess is:

For a fast reaction, the reaction rate is given by how quickly fuel and air mix.  In a dissociation reaction there is only fuel and the mixing routine will not have meaning.  I think we would have to add a special case that a fast dissociation reaction is always mixed.

**Comment by rmcdermo** [comment]
Good point.  But, come to think of it, this problem is true for Arrhenius
chem too.  I say we get rid of this limitation for now.

**Comment by rmcdermo** [comment]
OK, when I let dissociation reactions be fast, then your idea works great.  Unless you disagree, tomorrow I'll remove the dissociation trap and close this issue.  Next, I have to make some modifications to how we process suppression for multiple reactions, but that I another issue, which I'll start tomorrow.

**Comment by drjfloyd** [comment]
Removing trap sounds good to me.
