### ISSUE TITLE
SMV problems

### ISSUE THREAD

**Issue by SimonDrake-zz** [firemodels/fds#2480]
Smokeview: version 6.1.10, build date: May 28th 2014
(64 bit) Revision Number: 19418

I have results from a simulation that went initially to 93.2s, which was later restarted from 90s, and run on to 154.8s so far. When I use smokeview to look at the results at 154.8s, the following happens:
(1) Slices are plotted correctly, with the full 154.8s time slider at the foot of the screen; (2) Particles plot to 93.2s only, and the time slider at the foot of the screen only goes up to 93.2s; (3) 3D smoke plots correctly to 93.2s, then the smoke fragments by apparently moving results from one mesh block into another, appearing nonsensical, and the time slider at the foot of the screen goes up to 154.8s; (4) Attempting to plot some isosurfaces causes smokeview to stop responding, and other isosurfaces causes smokeview to fail completely, responding with a 'smokeview.exe has stopped working' dialogue box, followed by 'close program'.

I have no idea what is causing this, can you help.

**Comment by gforney** [comment]
download the latest smokview, version 6.2.4, and see if you can reproduce the problem with it.

**Comment by MeenakshySundaresan** [comment]
but gforney, 6.2.4 is not available, current Version is 6.2.2. if you have 6.2.4, can you send me the link?

**Comment by SimonDrake-zz** [comment]
Apologies for taking so long to reply. I was able to access SMV 6.2.3 (April 28th 2015) but it suffered the same problem trying to visualise the results. I came to the conclusion that as a result of 'killing' the simulation instead of using a 'soft' stop, then restarting from a restart file that was younger than the latest slice/particle/smoke result files, there would have been an inconsistency in time-stamp between these files. I think that is what has caused the problem. I have since re-run the model, un-interrupted from beginning to end, and there is no problem with the plotting in SMV. Thank you for your assistance.

**Comment by gforney** [comment]
smokeview 6.2.4 is available at the FDS download page

http://firemodels.github.io/fds-smv/

On Fri, Jul 24, 2015 at 5:59 AM, MeenakshySundaresan <
notifications@github.com> wrote:

> but gforney, 6.2.4 is not available, current Version is 6.2.2. if you have
> 6.2.4, can you send me the link?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2480#issuecomment-124460256
> .

## 

Glenn Forney
