### ISSUE TITLE
Smokeview, "Customize colorbar" menu item missing

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#2481]
Hi Glenn,

The Smokeview manual indicates there should be a Dialogs -> Customize Colorbar menu item, which I'm not seeing. (This is Smokeview 6.2.3.)

Thanks

Dave
![customize colorbar](https://cloud.githubusercontent.com/assets/13259079/8601798/85a1fb5c-263c-11e5-9738-2af98fe6048c.png)

**Comment by gforney** [comment]
Hi Dave,
I reorganized the dialog menus and did not update the manual page.  The
dialog entry you are looking for is now at
Dialogs>View>Edit colorbar
Thanks for pointing out the problem in the manual.  Let me know if you see
anything else.
glenn

On Thu, Jul 9, 2015 at 1:15 PM, Dave-McGill notifications@github.com
wrote:

> Hi Glenn,
> 
> The Smokeview manual indicates there should be a Dialogs -> Customize
> Colorbar menu item, which I'm not seeing.
> 
> Thanks
> 
> Dave
> [image: customize colorbar]
> https://cloud.githubusercontent.com/assets/13259079/8601798/85a1fb5c-263c-11e5-9738-2af98fe6048c.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2481.

## 

Glenn Forney

**Comment by Dave-McGill** [comment]
Found it.

Thanks
