### ISSUE TITLE
Smokeview, relative measurement with user settable ticks

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#2487]
Hi Glenn,

It would be handy to be able to place user settable ticks within the model to provide a relative measurement. The attached image is of an upper  floor of a muti-floor building; in absolute terms, the floor  height is 10.5 m. I want to show the relative height of the visibility iso-surface above the floor. I "Photoshopped" the image to place the scale in the model as shown.

Please add it to the wishlist.

Thanks Dave

![relative distance](https://cloud.githubusercontent.com/assets/13259079/8619416/e6cbcb9e-26e4-11e5-95eb-ebffc2069323.png)

**Comment by gforney** [comment]
I'll take a look at it.

**Comment by gforney** [comment]
try smokeview at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

to add user settable ticks open the Diagalogs>Windows>Labels dialog box.  smokeview now lets you define a line next to the label.

**Comment by Dave-McGill** [comment]
Hi Glenn,

That is more or less what I had in mind. See the attached image. The scale
on the left was created with the User ticks dialog, and the scale on the
right with the Labels and ticks dialog.

What is the purpose of the Min and Max text boxes for the User Ticks? Is
there anyway to sub-divide the line on the right?

Thanks

Dave

**Comment by Dave-McGill** [comment]
Hi Glenn,

I'm revisiting this. My intent is to have a line on the second floor of a building that I can use to show the relative height of an isosurface above the second level floor. 

See the attached image. I have manually added a 2 m vertical line in the middle of a room. I am now trying to add labels at 0, 1 and 2 m. My assumption is that the Position x,y, and z values for the labels are independent of the position of the tick (vertical line). However, when I put in coordinates for the label (which I want to place beside the line) the vertical line moves by those values.

Thanks

Dave

![nfpa_firepower_house ini](https://cloud.githubusercontent.com/assets/13259079/10821217/9cb9144a-7e27-11e5-842b-3e17e39802cc.png)
![nfpa_firepower_house smv](https://cloud.githubusercontent.com/assets/13259079/10821218/9cbbbc5e-7e27-11e5-88ec-f7a4cbb12f41.png)
![smokeview ini](https://cloud.githubusercontent.com/assets/13259079/10821219/9cc36f30-7e27-11e5-9f20-81c7a1d21f52.png)

![manual labels and ticks](https://cloud.githubusercontent.com/assets/13259079/10820924/110e191e-7e26-11e5-8c51-84415b8b23c5.png)

**Comment by gforney** [comment]
I'll take a look at it.

**Comment by gforney** [comment]
can you attach nfpa_firepower_house.ini, nfpa_firepower_house.smv and smokeview.ini .  All that got attached are png image files. thanksw.

**Comment by Dave-McGill** [comment]
Hi Glenn,

I've mailed them to you directly.

Dave

**Comment by gforney** [comment]
the "Labels+Ticks" dialog box lets you define a series of tick/label pairs.  Normally one would have one label for each tick (e.g. for a coordinate axis).  In your case, you want to do is define one tick (with no label) and several labels (with no ticks).  So, when you define your labels you need to deselect the "show tick" checkbox in the panel where defined your one tick

**Comment by Dave-McGill** [comment]
Thanks Glenn

**Comment by rmcdermo** [comment]
Hi Dave,

I just got a note from GitHub saying that non-members of a project should now have the ability to add txt files.  Can you please test this by trying to post an FDS input file to this thread? (append .txt to the extension)

Thanks!

**Comment by Dave-McGill** [comment]
Hi Randy,

Here you go. This file has nothing to do with the topic, but it's one I've been struggling with tonight. I was able to run 2 separate reactions in ver 6 RC3, but it won't run now. I gather there is some new syntax required to allow two reactions to run.

Dave
[reactions_wood_polyurethane.fds.txt](https://github.com/firemodels/fds-smv/files/31489/reactions_wood_polyurethane.fds.txt)

**Comment by rmcdermo** [comment]
Dave, thanks for the quick reply.  I'll have a look at the case.

**Comment by Dave-McGill** [comment]
I've clocked out for the night; you probably should too.☺

**Comment by rmcdermo** [comment]
Don't worry... Glenn is still up working for the both of us!

**Comment by rmcdermo** [comment]
Couple of issues:
1. Change extinction model to 'EXTINCTION 3'

&MISC EXTINCTION_MODEL='EXTINCTION 3' /
1. There have been subtle changes to the default composition of AIR (because we have corrected precision in the mole weight of N2) and this creates problems for stoichiometry.  So, you need to rework the stoich.  Run a simple case with simple chemistry and look at the .out file to get the default AIR composition.

Hope this helps.

**Comment by Dave-McGill** [comment]
Thanks

**Comment by gforney** [comment]
Actually I'm in Harrisonburg eating at chik filet!
