### ISSUE TITLE
HVAC Aircoil, problem with T_out

### ISSUE THREAD

**Issue by cfaurie** [firemodels/fds#2500]
Hi all,

I've got an issue with a simple HVAC Aircoil simulation. Typically, I've set up my coolant and duct properties to have T_out=12 degC for 100% efficiency using formula (9.4) p103 of UG. It works fine if I define manually the specific heat of the background gas, as follows:

&SPEC ID='SPECIES1',SPECIFIC_HEAT=1.01,BACKGROUND=.TRUE./

However, without this line, I obtain a lower temperature compared to the UG. It gets worse when the ambient temperature is high.

With input file as follows, I obtain T_out=7.48 degC and Q=-1.51 kW without SPEC_ID, and T_out=12.02 degC and Q=-0.97 kW with SPEC_ID (as per UG).

Did I miss something?

Thanks for your help, 

Coraline 

Input file:

&HEAD CHID='HVAC'/
&TIME T_END=10.0/

SPEC ID='SPECIES1',SPECIFIC_HEAT=1.01,BACKGROUND=.TRUE./

&MESH ID='Mesh01', IJK=100,20,20, XB=0.0,50.0,0.0,10.0,0.0,10.0/

&VENT SURF_ID='OPEN', XB=0.0,50.0,0.0,10.0,10.0,10.0/ 

&VENT ID='HVAC', SURF_ID='HVAC', XB=1.0,1.5,0.5,1.0,0.0,0.0/

&HVAC ID='Node', TYPE_ID='NODE', DUCT_ID='Duct', VENT_ID='HVAC'/
&HVAC ID='Ambient', TYPE_ID='NODE', DUCT_ID='Duct', AMBIENT=.TRUE., XYZ=1.25,0.75,-1.0/
&HVAC ID='Duct', TYPE_ID='DUCT', DIAMETER=0.2, AIRCOIL_ID='AHU-T-15', NODE_ID='Ambient','Node', VOLUME_FLOW=0.1, LENGTH=1.5/

&HVAC ID='AHU-T-15', TYPE_ID='AIRCOIL', COOLANT_SPECIFIC_HEAT=4.2, COOLANT_MASS_FLOW=15.0, COOLANT_TEMPERATURE=12.0, EFFICIENCY=1/

&DEVC ID='HVAC temp out', QUANTITY='NODE TEMPERATURE', NODE_ID='Node'/
&DEVC ID='HVAC temp in', QUANTITY='NODE TEMPERATURE', NODE_ID='Ambient'/
&DEVC ID='HVAC kW', QUANTITY='AIRCOIL HEAT EXCHANGE',DUCT_ID='Duct'/
&DEVC ID='Specific heat', QUANTITY='SPECIFIC HEAT', XYZ=1.5,0.5,0.5/

&TAIL /

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
Good find.  I am using the wrong cp in the aircoil routine.  I am using cp_bar (used to get total enthalpy) rather than cp (used to get temperature change).  In the case where you specify cp without given a non-zero reference enthalpy cp = cp_bar so it works. Our test case uses a specified cp so this wasn't caught. In the case of the default background cpbar ~1.6 vs. cp~1.  As a work around you can set the efficiency to 63 % (1/1.5). I'll fix this.

**Comment by cfaurie** [comment]
Great, thanks! Happy to help.

**Comment by drjfloyd** [comment]
Fixed.
