### ISSUE TITLE
Combustion with one Fuel and two different atmospheres doenst work

### ISSUE THREAD

**Issue by DerTobi17** [firemodels/fds#2503]
Hello,

i tried to build the controlled atmosphere cone calorimeter.The Geometry only shows a part of the cone calorimeter. First the fuel should reacts under an controlled atmosphere in the box. After the combustion in the box the products should be able to react with the second atmosphere outside the box. I defined to different reactions.One for the combustion in the box and one for the combustion outside the box. The problem is when i use two reactions at the same time only one atmosphere react with the fuel. If i start the simulation with only one of these two reactions it works well(Post Combustion_Yields_Zuluft.fds). Im unable to upload the FDS Files on the forum.
![supplied air 43sec](https://cloud.githubusercontent.com/assets/13256529/8653513/079c20ce-2985-11e5-8b20-7b4ff2d9f57a.JPG)
There is no combustion because filling with AIR starts at 65sec
![supplied air 67sec](https://cloud.githubusercontent.com/assets/13256529/8653514/079c21d2-2985-11e5-85db-aa5977d14fdb.JPG)
After 65s u can see a combustion.

 For example i fill the box with a defined species the fuel reacts with this species. When it should reacts with supplied species and the background it doenst work. There only the supplied species reacts with the fuel (Post Combustion_Yields_BACK_Zuluft.fds). 

![background supplied air 43sec](https://cloud.githubusercontent.com/assets/13256529/8653511/0798ab7e-2985-11e5-897d-4e831a3cbeba.JPG)
There i activated the reaction for the background atmosphere but nothing happens.

![background supplied air 67sec](https://cloud.githubusercontent.com/assets/13256529/8653512/079bf504-2985-11e5-9f84-b6707f7c73b0.JPG)
After 67s the filled species reacts with the fuel.

Post Combustion_Yields_Zuluft.fds(one reaction is activated):

&HEAD CHID='Post_Combustion_Yields'/
&TIME T_END=300, DT=0.01/
&DUMP RENDER_FILE='Post_Combustion_Yields.ge1', MASS_FILE=.TRUE./

&MESH ID='MESH', IJK=12,12,12, XB=-0.6,0.6,-0.6,0.6,0.0,1.2/

&MISC SUPPRESSION=.FALSE. /

&SPEC ID='NITROGEN', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='OXYGEN', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='WATER VAPOR', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='CARBON DIOXIDE', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='CARBON MONOXIDE', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='SOOT', MASS_EXTINCTION_COEFFICIENT=10000  , LUMPED_COMPONENT_ONLY=.TRUE., FORMULA='C0.9H0.1'/     

&SPEC ID='Holz', FORMULA ='C1H1.7O0.74N0.002'/              

&SPEC ID='AIR1', BACKGROUND=.TRUE.,  
SPEC_ID(1)='OXYGEN', VOLUME_FRACTION(1)=                    0.21    ,  
SPEC_ID(2)='NITROGEN', VOLUME_FRACTION(2)=                  0.79    /                           

&SPEC ID='PRODUCTS1',  
SPEC_ID(1)='CARBON MONOXIDE', VOLUME_FRACTION(1)=                   0.0129965,  
SPEC_ID(2)='CARBON DIOXIDE', VOLUME_FRACTION(2)=                    0.1622222,  
SPEC_ID(3)='WATER VAPOR', VOLUME_FRACTION(3)=                   0.1507970   ,  
SPEC_ID(4)='NITROGEN', VOLUME_FRACTION(4)=                  0.6713813       ,  
SPEC_ID(5)='SOOT', VOLUME_FRACTION(5)=                  0.0026030   /               

REAC FUEL='Holz', HEAT_OF_COMBUSTION=   16400   , SPEC_ID_NU='Holz', 'AIR1', 'PRODUCTS1', NU=-1, -4.7849642 ,5.6318547  , /  21%

&SPEC ID='AIR2',  
SPEC_ID(1)='OXYGEN', VOLUME_FRACTION(1)=                    0.18    ,  
SPEC_ID(2)='NITROGEN', VOLUME_FRACTION(2)=                  0.82    /                                       

&SPEC ID='PRODUCTS2',  
SPEC_ID(1)='CARBON MONOXIDE', VOLUME_FRACTION(1)=                   0.0113845   ,  
SPEC_ID(2)='CARBON DIOXIDE', VOLUME_FRACTION(2)=                    0.1421002   ,  
SPEC_ID(3)='WATER VAPOR', VOLUME_FRACTION(3)=                       0.1320922   ,  
SPEC_ID(4)='NITROGEN', VOLUME_FRACTION(4)=                          0.7121430   ,  
SPEC_ID(5)='SOOT', VOLUME_FRACTION(5)=                              0.0022801   /                               

&REAC FUEL='Holz', HEAT_OF_COMBUSTION=  16400   , SPEC_ID_NU='Holz', 'AIR2', 'PRODUCTS2', NU=-1, -5.5824582,6.4293487 /  18%

&SURF ID='Feuer',
      COLOR='RED',
      MASS_FLUX=0.017995732,
      SPEC_ID='Holz',/

&SURF ID='LEAK',
      MASS_FLUX=0.019097561,
      SPEC_ID='AIR2',
      RAMP_MF='LEAK_RAMP_MF'/
&RAMP ID='LEAK_RAMP_MF', T=0.0, F=0/
&RAMP ID='LEAK_RAMP_MF', T=20.0, F=0 /
&RAMP ID='LEAK_RAMP_MF', T=40.0, F=0 /
&RAMP ID='LEAK_RAMP_MF', T=64.0, F=0 /
&RAMP ID='LEAK_RAMP_MF', T=65.0, F=1 /
&RAMP ID='LEAK_RAMP_MF', T=340.0, F=1.0/

&OBST XB=-0.2,0.2,-0.2,0.2,0.1,0.2, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=-0.3,0.3,0.2,0.3,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=-0.3,0.3,-0.3,-0.2,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=-0.3,-0.2,-0.2,0.2,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=0.2,0.3,-0.2,0.2,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=0.1,0.3,-0.3,0.3,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.3,-0.1,-0.3,0.3,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,-0.3,-0.1,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,0.1,0.3,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,-0.2,-0.1,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=0.1,0.2,-0.2,0.2,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,0.1,0.2,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.2,-0.1,-0.2,0.2,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=0.0,0.1,0.0,0.1,0.4,0.5, COLOR='GRAY', SURF_ID='INERT'/ Feuer

&VENT SURF_ID='Feuer', XB=0.0,0.1,0.0,0.1,0.5,0.5/ Feuer
&VENT SURF_ID='LEAK', XB=-0.2,0.2,-0.2,0.2,0.2,0.2/ Zuluft

---

Post_Combustion_Yields_BACK_Zuluft.fds(both reactions are activated)

&HEAD CHID='Post_Combustion_Yields_BACK_Zuluft'/
&TIME T_END=300, DT=0.01/
&DUMP RENDER_FILE='Post_Combustion_Yields.ge1', MASS_FILE=.TRUE./

&MESH ID='MESH', IJK=12,12,12, XB=-0.6,0.6,-0.6,0.6,0.0,1.2/

&MISC SUPPRESSION=.FALSE. /

&SPEC ID='NITROGEN', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='OXYGEN', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='WATER VAPOR', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='CARBON DIOXIDE', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='CARBON MONOXIDE', LUMPED_COMPONENT_ONLY=.TRUE. /  
&SPEC ID='SOOT', MASS_EXTINCTION_COEFFICIENT=10000  , LUMPED_COMPONENT_ONLY=.TRUE., FORMULA='C0.9H0.1'/     

&SPEC ID='Holz', FORMULA ='C1H1.7O0.74N0.002'/              

&SPEC ID='AIR1', BACKGROUND=.TRUE.,  
SPEC_ID(1)='OXYGEN', VOLUME_FRACTION(1)=                    0.21    ,  
SPEC_ID(2)='NITROGEN', VOLUME_FRACTION(2)=                  0.79    /  
&SPEC ID='PRODUCTS1',  
SPEC_ID(1)='CARBON MONOXIDE', VOLUME_FRACTION(1)=                   0.0129965,  
SPEC_ID(2)='CARBON DIOXIDE', VOLUME_FRACTION(2)=                    0.1622222,  
SPEC_ID(3)='WATER VAPOR', VOLUME_FRACTION(3)=                   0.1507970   ,  
SPEC_ID(4)='NITROGEN', VOLUME_FRACTION(4)=                  0.6713813       ,  
SPEC_ID(5)='SOOT', VOLUME_FRACTION(5)=                  0.0026030   /               

&REAC FUEL='Holz', HEAT_OF_COMBUSTION=  16400   , SPEC_ID_NU='Holz', 'AIR1', 'PRODUCTS1', NU=-1, -4.7849642 ,5.6318547  , /  21%

&SPEC ID='AIR2',  
SPEC_ID(1)='OXYGEN', VOLUME_FRACTION(1)=                    0.18    ,  
SPEC_ID(2)='NITROGEN', VOLUME_FRACTION(2)=                  0.82    /                                       

&SPEC ID='PRODUCTS2',  
SPEC_ID(1)='CARBON MONOXIDE', VOLUME_FRACTION(1)=                   0.0113845   ,  
SPEC_ID(2)='CARBON DIOXIDE', VOLUME_FRACTION(2)=                    0.1421002   ,  
SPEC_ID(3)='WATER VAPOR', VOLUME_FRACTION(3)=                       0.1320922   ,  
SPEC_ID(4)='NITROGEN', VOLUME_FRACTION(4)=                          0.7121430   ,  
SPEC_ID(5)='SOOT', VOLUME_FRACTION(5)=                              0.0022801   /                               

&REAC FUEL='Holz', HEAT_OF_COMBUSTION=  16400   , SPEC_ID_NU='Holz', 'AIR2', 'PRODUCTS2', NU=-1, -5.5824582,6.4293487 /  18%

&SURF ID='Feuer',
      COLOR='RED',
      MASS_FLUX=0.017995732,
      SPEC_ID='Holz',/

&SURF ID='LEAK',
      MASS_FLUX=0.019097561,
      SPEC_ID='AIR2',
      RAMP_MF='LEAK_RAMP_MF'/
&RAMP ID='LEAK_RAMP_MF', T=0.0, F=0/
&RAMP ID='LEAK_RAMP_MF', T=20.0, F=0 /
&RAMP ID='LEAK_RAMP_MF', T=40.0, F=0 /
&RAMP ID='LEAK_RAMP_MF', T=64.0, F=0 /
&RAMP ID='LEAK_RAMP_MF', T=65.0, F=1 /
&RAMP ID='LEAK_RAMP_MF', T=340.0, F=1.0/

&OBST XB=-0.2,0.2,-0.2,0.2,0.1,0.2, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=-0.3,0.3,0.2,0.3,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=-0.3,0.3,-0.3,-0.2,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=-0.3,-0.2,-0.2,0.2,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=0.2,0.3,-0.2,0.2,0.1,0.6, COLOR='GRAY', SURF_ID='INERT'/ Box side
&OBST XB=0.1,0.3,-0.3,0.3,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.3,-0.1,-0.3,0.3,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,-0.3,-0.1,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,0.1,0.3,0.6,0.7, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,-0.2,-0.1,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=0.1,0.2,-0.2,0.2,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.1,0.1,0.1,0.2,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=-0.2,-0.1,-0.2,0.2,0.7,1.0, COLOR='GRAY', SURF_ID='INERT'/ Box top
&OBST XB=0.0,0.1,0.0,0.1,0.4,0.5, COLOR='GRAY', SURF_ID='INERT'/ Feuer

&VENT SURF_ID='Feuer', XB=0.0,0.1,0.0,0.1,0.5,0.5/ Feuer
&VENT SURF_ID='LEAK', XB=-0.2,0.2,-0.2,0.2,0.2,0.2/ Zuluft

Thank You!
Regards
Tobias

**Comment by rmcdermo** [comment]
We'll have a look.

**Comment by rmcdermo** [comment]
Tobias,
I have set up and run the cases.  But I really do not understand what you think should be happening.  Please try again to describe your problem, this time without relying on the SMV images---I am confused by these.
Thanks,
Randy

**Comment by DerTobi17** [comment]
Im now talking about the Post_Combustion_Yields_BACK_Zuluft.fds file. 

I want a combustion with one fuel(Holz) which reacts with 2 different atmospheres. First it should react with the controlled atmosphere in the box and then it should react with the atmosphere outside the box. For example the fuel reacts with air in the box which composed of 18% oxygen and 82% nitrogen and then it should reacts with the atmosphere outside the box which is composed of 21 % oxygen, 79% nitrogen. 

The two different reactions that i defined dont work together if i use them in one simulation. If i activate both only the reaction with fuel and the supplied air works
(&REAC FUEL='Holz', HEAT_OF_COMBUSTION= 16400 , SPEC_ID_NU='Holz', 'AIR2', 'PRODUCTS2', NU=-1, -5.5824582,6.4293487 / 18%). You cannot see any reactions with AIR1.
I dont understand why only one of these reaction works if i activate both.

**Comment by rmcdermo** [comment]
Why do you assert that only one reaction is proceeding?  What output
quantity shows this?

**Comment by DerTobi17** [comment]
These two pictures shows that there is no combustion until 65 seconds. After 65 seconds the combustion begins when AIR2 flows into the box.
![hrr](https://cloud.githubusercontent.com/assets/13256529/8658719/dc1c5b3c-29a5-11e5-8f6a-5413df47f45b.png)
![vol](https://cloud.githubusercontent.com/assets/13256529/8658718/dc1918b4-29a5-11e5-9c44-f578216869c1.png)

**Comment by rmcdermo** [comment]
Tobias,
Sorry I was so dense.  This is actually a bug in the boundedness correction routine.  Craig will have a look at this when he gets back.  In the mean time, the easiest work-around is to just use AIR1 + N2 on the leak line.  Here is a sample input file:

https://drive.google.com/file/d/0B4528gcI9D3HSVJLcVlFd1d6cVk/view?usp=sharing

I specified the mass fluxes on the LEAK to give the same volume fractions as your AIR2. Let me know if you have any problems with it.

**Comment by rmcdermo** [comment]
Craig,
The issue here is that you have a single fuel and competing "AIR"s with fast chem.  This is very similar to your reactionrate_lumped_two_air.fds case.  Except in your case you have initial values for all the AIRs.  Here you have a value of Z(AIR2)=0 and so the BCOR is guaranteed to be 0, hence no reaction.  Let's discuss this when you get back.  It's a fundamental problem with how we handle the boundedness for multiple reactions.

**Comment by rmcdermo** [comment]
Tobias,
I was thinking last night that I forgot to set the ramp on both the AIR1 and N2 for LEAK.  So, double check this and make sure the ramp is set for both species.

**Comment by DerTobi17** [comment]
Hi Randy, 
thank you for your help. I will try it and give you feedback about my results.

**Comment by DerTobi17** [comment]
Hi Randy, 

im sorry for my late feedback. It works.

**Comment by rmcdermo** [comment]
Craig,
We should tackle this before 6.3.0 release.  Let's talk today.
Thanks!

**Comment by rmcdermo** [comment]
I've working on this Issue.  Turns out to be a fundamental problem with the bcor routine that really prevents us from doing things correctly for multiple fast reactions.  Attached is a simple case with two independent fast reactions.  In R1 there is excess "fuel".  In R2 there is excess "air".  So, all the fuel in R2 should be consumed, but it isn't because we indiscriminately apply BCOR to all the species.

[bcor_test_1.txt](https://github.com/firemodels/fds-smv/files/145609/bcor_test_1.txt)

**Comment by rmcdermo** [comment]
I believe this issue is solved with pull request #3557.

Tobias, you should be able to use your two AIR streams now.  This will be available in next minor release due out very soon.

**Comment by rmcdermo** [comment]
This issue is not resolved in general.  But we have a way to fix it now.  I'm going to be working in fire.f90 for the next couple of days overhauling a few things.  So, please try not to make any significant changes there.  Thanks.

**Comment by mcgratta** [comment]
This issue has grown stale. Many things have changed in the combustion routines since this post. I am going to close it. Open up a new one if you see new problems.
