### ISSUE TITLE
Atom balance error with simple chemistry

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#2504]
Jason,

This is not urgent.  But more and more I find myself trying to set up simple cases to mimic the "SIMPLE_CHEMISTRY" and it becomes really difficult to get the stoichiometry correct.  Here is a test case for N-HEPTANE:

https://drive.google.com/file/d/0B4528gcI9D3HbGlySEFGLXluVHc/view?usp=sharing

(you can ignore this and setup your own simple case if you want, there's nothing special about this one).

If I set T_END=0 to get "setup only" and then copy the output of the .out file into my own set up of a "simple chemistry" reaction (that is, I define my own PRODUCTS, etc. by copying the volume fractions from the .out file) then I get atom balance errors.  I assume this is an output precision issue.  But just increasing the precision of the NU output did not help.  There are too many possibilities.

I don't know what the immediate answer is, but I think we need to ponder this a bit.  The basic machinery in read works great.  I am very happy with the flexibility.  And I can generally get things to work by writing my own matlab scripts for each individual case.  But this takes too much time.  Now that we know the machinery is solid, we need to start working on usability.

Randy

**Comment by drjfloyd** [comment]
12.1.1 Simple Chemistry Parameters

SOOT_H_FRACTION The fraction of the atoms in the soot that are hydrogen. For all other types of REAC inputs the species SOOT is assumed to be pure carbon unless a FORMULA is provided (Section 11.1.2). Note that this parameter is only appropriate when the simple chemistry model is applied. (Default 0.1 -equivalent to the input FORMULA=’C0.9H0.1’ for other REAC types)

So your volume fraction inputs are based on C0.9H0.1, but your SPEC is now C1.  Hence the atom balance problem

Two options:

1) define SOOT_H_FRACTION=0 in your simple chemistry case to get the correct values for non-simple chemistry
2) define a soot species with the formula C0.9H0.1 then you can use the default simple chemistry.  Option 1 is easier as you don't have to define SPECIFIC_HEAT etc.

**Comment by rmcdermo** [comment]
OK, that explains it.  Still want to revisit usability for setting up schemes other than simple chem, but I'll close this for now.
