### ISSUE TITLE
Version / Revision numbering

### ISSUE THREAD

**Issue by lu-kas** [firemodels/fds#2511]
Hey!

There have been some people around, that miss an incremental number to indicate the status of the code. For example, in forum discussions and in environments with multiple FDS versions for a multitude of users. In SVN this has been the revision number.

Obviously git can not provide something like that, however there might be an approximative way: 
$ git describe --tags --long

It tells you the following:
LAST_TAG-XXX-COMMIT
with
LAST_TAG: the most recent tag name
XXX: number of commits since the tag
COMMIT: git commit hash

With this and an way of consistent tagging, it would be easier for humans to easily refer to a source code status. And there would be two human readable increasing numbers: the tag (like a stable software version) and the number of commits after that (here XXX).

Currently, the command produces

$ git describe --tags --long
Git_v0-144-g2f2164e

Which means, that there have been 144 commits after the tag 'Git_v0'.

Choosing a 'propper' tag, like '6.2.0' for now might already do a reasonable job in communication.

What do you think?

Best,
Lukas

**Comment by rmcdermo** [comment]
Lukas,
This is already implemented :).  Compile latest version and you will see this under Revision.  We also stamp all our verification plots with it.

**Comment by lu-kas** [comment]
Well, somehow I have missed it.

This is because you do the preprocessing (setting the according git info) only for some selected make targets -- gnu compiler is not among them.

So, adding the preprocessor flags (for gnu its '-cpp' instead of '-fpp' for Intel) I do also see the proposed git "revision number".

Best,
Lukas

**Comment by gforney** [comment]
want to make the change to the makefile and submit a pull request!
glenn

On Tue, Jul 14, 2015 at 3:30 PM, Lukas notifications@github.com wrote:

> Well, somehow I have missed it.
> 
> This is because you do the preprocessing (setting the according git info)
> only for some selected make targets -- gnu compiler is not among them.
> 
> So, adding the preprocessor flags (for gnu its '-cpp' instead of '-fpp'
> for Intel) I do also see the proposed git "revision number".
> 
> Best,
> Lukas
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2511#issuecomment-121349558
> .

## 

Glenn Forney

**Comment by rmcdermo** [comment]
OK, thanks.

Glenn, want to have a look at this?

**Comment by rmcdermo** [comment]
Or that :)

**Comment by gforney** [comment]
didn't see the previous comment.  I'll take a look at it

**Comment by lu-kas** [comment]
Ok, I was too slow. 

Anyway, thanks for fixing!
