### ISSUE TITLE
I am begginer 

### ISSUE THREAD

**Issue by hussain4x** [firemodels/fds#2526]
hello everybody. I am IT engineer and beginner on FDS systems. i read about it and i would like learn it from 0 to professional.  kindly can you guide me on that ? and from where i can start ? please encourage me on this matter.

hussein

**Comment by hussain4x** [comment]
now i got user guide of FDS v5 , and i start reading it , is it a good first step to learn FDS ?

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs or requesting enhancements to the code. General questions on use  should  be posted to the discussion forum:

https://groups.google.com/forum/?fromgroups=&nomobile=true#!forum/fds-smv

The current version of the code is v6.2. I recommend you learn to use that version. v5 is many years old at this point. Starting by reading all the code documentation (Tech Reference, Users Guide, Validation Report, and Verification Report) is a good start along with studying the various examples provided when you install FDS. Becoming proficient in FDS is not a quick process and in addition to just learning the inputs you should have knowledge of computational fluid dynamics, fire science, heat transfer, etc.
