### ISSUE TITLE
Embed metadata in Smokeview rendered images

### ISSUE THREAD

**Issue by saschagottfried** [firemodels/fds#2529]
Image metadata is widely used for automation workflows and to manage large collections. Professional FDS users create large collections of images rendered by Smokeview. A typical relationship to a FDS working directory is to use subdirectories for images (RENDERDIR). Including CHID as part of image file naming convention could lead to rather long file names. May be image metadata can help to separate images from working directories while keeping references. 

Rationale for implementation
Having metadata in images rendered by Smokeview could support automation workflow as well as supporting fds-smv issue tracker, since users always have to tell details about operating system, FDS version, Smokeview version. Supplied images attached to issues regarding Smokeview rendering results would contain metadata about the version. 

Why this is not a weird idea?
There are a lot of people who just use the software on their machines, others may have installed these. Questions about the runtime environment are hard to answer for a lot of people. Fixing issues usually requires these sorts of information.  

Why this idea may be nothing new to the developers?
Recent FDS versions create a file chid_svn.txt to support identification of the FDS version used to  create files in a working directory. The motivation behind this is similar to my intention.

Suggestion for required metadata
- CHID
- Smokeview version string
- Platform - one of OSX/Linux/Win64 (provided by the platform itself - like `uname -a` on Linux)

**Comment by gforney** [comment]
unfortunately, don't think the png format supports meta data .  the
graphics library smokview uses to convert opengl screen images to png/jpeg
images doesn't support it either.

On Tue, Jul 21, 2015 at 12:02 PM, Sascha Gottfried <notifications@github.com

> wrote:
> 
> Image metadata is widely used for automation workflows and to manage large
> collections. Professional FDS users create large collections of images
> rendered by Smokeview. A typical relationship to a FDS working directory is
> to use subdirectories for images (RENDERDIR). Including CHID as part of
> image file naming convention could lead to rather long file names
> 
> Rationale for implementation
> Having metadata in images rendered by Smokeview could support automation
> workflow as well as supporting fds-smv issue tracker, since users always
> have to tell details about operating system, FDS version, Smokeview
> version. Supplied images attached to issues regarding Smokeview rendering
> results would contain metadata about the version.
> 
> Why this is not a weird idea?
> There are a lot of people who just use the software on their machines,
> others may have installed these. Questions about the runtime environment
> are hard to answer for a lot of people. Fixing issues usually requires
> these sorts of information.
> 
> Why this idea may be nothing new to the developers?
> Recent FDS versions create a file chid_svn.txt to support identification
> of the FDS version used to create files in a working directory. The
> motivation behind this is similar to my intention.
> 
> Suggestion for required metadata
> - CHID
> - Smokeview version string
> - Platform - one of OSX/Linux/Win64 (provided by the platform itself -
>   like uname -a on Linux)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2529.

## 

Glenn Forney

**Comment by gforney** [comment]
I would suggest you use a 3rd part tool to write a script that would add
the meta tag data you wish to the images

On Tue, Jul 21, 2015 at 12:02 PM, Sascha Gottfried <notifications@github.com

> wrote:
> 
> Image metadata is widely used for automation workflows and to manage large
> collections. Professional FDS users create large collections of images
> rendered by Smokeview. A typical relationship to a FDS working directory is
> to use subdirectories for images (RENDERDIR). Including CHID as part of
> image file naming convention could lead to rather long file names
> 
> Rationale for implementation
> Having metadata in images rendered by Smokeview could support automation
> workflow as well as supporting fds-smv issue tracker, since users always
> have to tell details about operating system, FDS version, Smokeview
> version. Supplied images attached to issues regarding Smokeview rendering
> results would contain metadata about the version.
> 
> Why this is not a weird idea?
> There are a lot of people who just use the software on their machines,
> others may have installed these. Questions about the runtime environment
> are hard to answer for a lot of people. Fixing issues usually requires
> these sorts of information.
> 
> Why this idea may be nothing new to the developers?
> Recent FDS versions create a file chid_svn.txt to support identification
> of the FDS version used to create files in a working directory. The
> motivation behind this is similar to my intention.
> 
> Suggestion for required metadata
> - CHID
> - Smokeview version string
> - Platform - one of OSX/Linux/Win64 (provided by the platform itself -
>   like uname -a on Linux)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2529.

## 

Glenn Forney

**Comment by saschagottfried** [comment]
The intention of my request is to delegate creation of common metadata to the image producing application already equipped with everything necessary to do the job. Of course you need to see value in this to invest your time. That is why I emphasized that this could help you managing issues with attached rendered images.

Until today I did not know anything about PNG specs, but may be it will help you to estimate implementation efforts. Of course this is a low priority request.

[PNG spec](http://www.w3.org/TR/PNG/#11textinfo) gives a list of pre-defined meta tags.
You can add as many other meta tags/fields as you would like.

Smokeview uses libpng 1.2.5 
I found libpng documentation on how to save meta tags/fields. [Chapter 4.3 "Setting the content of info for output"](http://www.libpng.org/pub/png/libpng-1.2.5-manual.html#section-4.3) contains detailed information referencing information from the PNG spec at the end of this chapter. Watch out for `text_ptr` and `num_text`.

**Comment by saschagottfried** [comment]
Hi Glenn,
I finally found you are using libgd 2.0.15 for rendering PNG. I found [this comment on text annotation in libgd source code](https://github.com/libgd/libgd/blob/master/src/gd_png.c#L39). Is that the showstopper you mentioned?

`Gamma is ignored, and there is no support for text annotations.`

**Comment by saschagottfried** [comment]
Just for reference: [LodePNG](http://lodev.org/lodepng/) could a nice replacement for libgd for rendering PNG. It does not support JPEG.

If Smokeview would stop supporting JPEG as rendering output format I expect nobody to complain. I always used PNG since its the default and never intended to change. Since PNG uses lossless compression it is much better for documentation purposes which required image quality. Given usual storage prices/speed today the increased size compared to JPEG is not important anymore.  Most image editors do compress JPEG images while saving, most people even realize this behaviour. PNG keeps quality even within image editing workflows.

http://lodev.org/lodepng/

**Comment by gforney** [comment]
I did not come across that particular statement but could not find any
routines in the GD library for outputting exif or meta data to an image
file. If you can find such a routine then I'll take a look

**Comment by gforney** [comment]
Not supporting jpeg would be a show stopper

**Comment by saschagottfried** [comment]
Apparently even the current master of libgd is not supporting PNG meta data. Open issues are not about this topic, I could not find any hint about it. Thanks for your feedback.
