### ISSUE TITLE
DUMP restart files to disk without stopping the simulation (graceful shutdown)

### ISSUE THREAD

**Issue by saschagottfried** [firemodels/fds#2530]
FDS offers a graceful shutdown. Restarting the simulation may not always work or aborts because of "numerical instability". AFAIK this feature is not considered for production workflows.

In a (cloud/cluster) environment with regular scheduled maintenance, saving application state of long-running tasks (several weeks) is a key requirement to stop a workload for any maintenance and to continue a workload after maintenance. Moving a running workload to different computing resources could provide some kind of backup solution. This backup should not affect the original simulation running on hardware having maintenance applied before simulation finishes.

When maintenance is announced, you snapshot the simulation to disk, move the working directory to another environment, trigger a RESTART and watch it. Comparing results from both simulations is required to consider a restart/resume operation as successful.

Possible implementation
After adding a file called `chid.snapshot` to working directory `*.restart` files are written to disk, but simulation continues. It is not allowed to run or restart a simulation having a file `chid.snapshot` in working directory - similar to `chid.stop`

**Comment by mcgratta** [comment]
If there is a large show of support for a feature like this, I'll do it. But the restart feature has become very complicated, so I don't want risk breaking unless there is a lot of need.

**Comment by drjfloyd** [comment]
You can set DT_RESTART which dumps restart files every DT_RESTART s. If your system crashes, then you only loose the time since the last dump. If you are on a system with random shutdowns, then maybe set DR_RESTART so you don't loose more than half a day or a day of time.

**Comment by saschagottfried** [comment]
Brilliant idea.

**Comment by saschagottfried** [comment]
Summary: Using DT_RESTART so that snapshots are created regularly (once or twice a day) enables similar dump/resume operations without any additional implementation effort.
