### ISSUE TITLE
smokeview simulation image problem

### ISSUE THREAD

**Issue by MeenakshySundaresan** [firemodels/fds#2536]
Hello,
I installed the fds file and done everything as giving. while executing the .smv file, I coudn't able to get the 3d view of the Image
for example in activate_vents.smv i have created and tried to execute the smokeview Image, but I coudnt able to see the Image of that file in that.
advance Thanks.. 
looking Forward for your reply.

**Comment by rmcdermo** [comment]
The issues page is for reporting bugs or requesting enhanced functionality.  You need to post [a much clearer] question to the discussion forum:

https://groups.google.com/forum/?fromgroups#!forum/fds-smv
