### ISSUE TITLE
Revision info on Windows build

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#2537]
Hello, 

I am building the most recent version of the source from the master branch (commit 59755d6c) and have been getting revision information that looks like:

```
...
 Current Date     : July 20, 2015  15:38:24
 Version          : FDS 6.2.0
 Revision         : Revisio
```

In order to correct this issue I have had to modify _main.f90_ on line 3670 so that the %Revision keyword is formatted to match the other two keywords (i.e. '$Revision: unknown $'), otherwise it is not found by the sed command in the substitution scripts.

I have also had to modify the scripts _expand_keyword.bat_ and _contract_keyword.bat_, as these were adding an extra carriage return for each substitution, and _main.f90_ after the build did not match the original - so that git flagged the file as changed after each build. 
Removing the second sed command in each script fixed this for me:  

```
sed -e "s/$%keyword%:.*\$/$%keyword%: %newvalue% $/g" %file% | sed "s/$/\r/" > %temp%\temp.txt
```

...becomes:

```
sed -e "s/$%keyword%:.*\$/$%keyword%: %newvalue% $/g" %file% > %temp%\temp.txt
```

which gives me the following:

```
 Revision Date    : Jul 3, 2015  01:26:03
 Compilation Date : Jul 24, 2015  13:05:24
 Current Date     : July 24, 2015  13:23:42
 Version          : FDS 6.2.0
 Revision         : SMV6.2.4-4-g59755d6-dirty
```

I guess this isn't the most pressing issue, but it can be nice information to have when jumping between revisions. I'm wondering if this is an issue with configurations on my end (i.e. others have got this working just fine on Windows), or if I have stick with the above modifications.

Thanks!
-Eric

**Comment by gforney** [comment]
use the development branch.  we've come up with a better scheme for doing keyword substitution which is in the development branch not the master branch.

**Comment by rmcdermo** [comment]
Another good reason not to maintain multiple branches.  [Firebot Build Status](http://firemodels.github.io/fds-smv/firebot_status) and [FDS Release Notes](https://github.com/firemodels/fds-smv/wiki/FDS-Release-Notes) are enough for anyone to checkout a specific revision.
