### ISSUE TITLE
no_slip

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#2549]
Noticed this while running the water_evaporation test cases.  Run case4 and load the u-velocity slice. The velocity is zero at the wall but NO_SLIP=.TRUE. is set for the surf.

**Comment by rmcdermo** [comment]
I'm confused.  Do you want the flow to slip at the wall?  Then set FREE_SLIP=.TRUE.  Else, everything is consistent.

**Comment by drjfloyd** [comment]
argghh... I was confused.  Since NO_SLIP is the default, should we even have it in the input file?

**Comment by rmcdermo** [comment]
Is this an LES case?  Then NO_SLIP is not the default.  NO_SLIP is default
for DNS.  For LES, the default is a loglaw wall model.  FREE_SLIP means
zero stress at the wall.

**Comment by drjfloyd** [comment]
This is water_evaporation_4. LES. I saw the NO_SLIP and read FREE_SLIP.

I'm not sure why we are setting NO_SLIP in this case. It doesn't add anything to the case and we aren't doing anything with the wall velocity checking to see if it is being implemented correctly. But I guess since it doesn't matter no point in worrying about it.

**Comment by rmcdermo** [comment]
Yeah, I am fine if you want to remove it.  If I added it, I can't remember why.
