### ISSUE TITLE
Nice Git Workflow Explanation

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#2558]
Not an issue, more of a tip for others getting used to gitting.

https://www.atlassian.com/git/tutorials/comparing-workflows

**Comment by rmcdermo** [comment]
Thanks Bryan.  We have a bit of a mix, but we basically following the Forking Workflow.  So far so good.  I think we are all slowly getting used to Git.  Today I used git bisect to track down a bug for the first time and it worked great.

**Comment by bwklein** [comment]
That is really cool.  Personally I think Git is more difficult than it needs to be, but once you figure out how to use it, it can be very useful in many use cases.  I am going to close this issue out, I just wanted to share it in case you wanted to add it to any of the docs or wiki content.

Have a great day.
