### ISSUE TITLE
set default FDS repo for qfds.sh in .bashrc

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#2577]
Glenn,

Since the migration to Git, it is not longer convenient for me to always use FDS-SMV as my repo name.  But is also sort of a pain to always set -f fds_repo when invoking qfds.sh.  I'd like to set this once in my .bashrc and have qfds.sh use that.

So, could we set up qfds.sh to use $FDSSMV (or something) as the default (user sets this in their bash), and if that is not available (user has not set it up) use the current default FDS-SMV, and still keep the -f option as well :).  No good deed goes unpunished!

Thanks!

**Comment by gforney** [comment]
I'll make the change

**Comment by gforney** [comment]
try using qfdsnew.sh on either burn or blaze .  If they work ok I'll copy them over to qfds.sh .  Define a variable named FDSSMV in your .bashrc file.  Type qfdsnew.sh without any arguments and look to see what default option is listed for the -f option.  If it is what you expect then you should be good to go

**Comment by mcgratta** [comment]
This appears to be working. Move it into the repo. If we don't need qfdsBAK.sh and qfds_test.sh, remove them. Thanks

**Comment by mcgratta** [comment]
Just FYI, if you type

qfds.sh -v whatever

you will see what executable is being invoked.

**Comment by rmcdermo** [comment]
Glenn,
Thanks!  Works great.
