### ISSUE TITLE
problem with pyrolysis in FDS 6.2.0

### ISSUE THREAD

**Issue by AndrzejKrauze** [firemodels/fds#2587]
Hello,
I have prepared files to simulate the spread of polyurethane foam fire in a warehouse in FDS 5.3.0...
It was submitted to the Discusion Group:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/T6144HN4cLM/wZDQeoRMCAAJ

Now I’m trying to simulate the same scenario in FDS 6.2.0. When I add to the input file: REFERENCE_TEMPERATURE=200 and REFERENCE_RATE=0.1,  the PUR foam disappears at the beginning of the simulation. But the PUR foam doesn’t burn down…

Below is more simple case with just a single mesh and a block of foam that demonstrates the problem:

&HEAD CHID='sym22_test', TITLE='sym22_test' /
&TIME T_BEGIN=0.0, T_END=900.0 /
&DUMP DT_RESTART=200.0, NFRAMES=90 /

&SPEC ID='WATER VAPOR' /

//// SIATKI /////

&MESH IJK=14, 14, 32 XB=-0.25, 1.5, -0.25, 1.5, 0, 4 /

//// OTWARTE /////

&VENT MB='XMIN', SURF_ID='OPEN' / 
&VENT MB='XMAX', SURF_ID='OPEN' / 
&VENT MB='YMIN', SURF_ID='OPEN' / 
&VENT MB='YMAX', SURF_ID='OPEN' / 
&VENT MB='ZMAX', SURF_ID='OPEN' / 

//// POZAR /////

&RADI RADIATIVE_FRACTION=0.40 /

&REAC FUEL='pianka_poliuretan' 
CO_YIELD=0.015 
SOOT_YIELD=0.019
N=1.0 
C=11.6 
H=18.4 
O=3.2 /

&SURF ID='pozar0', HRRPUA=800.0, COLOR='RED' /
&VENT XB=0.0, 0.25, 0.5, 0.75, 0.0, 0.0, SURF_ID='pozar0' /

//// MATERIALY /////

&MATL ID='MAT_WALL' 
DENSITY=2300.0
SPECIFIC_HEAT=1.0 
CONDUCTIVITY_RAMP='c_ramp' /

&RAMP ID='c_ramp', T=20.0, F=1.951 /
&RAMP ID='c_ramp', T=120.0, F=1.721 /
&RAMP ID='c_ramp', T=360.0, F=1.256 /
&RAMP ID='c_ramp', T=600.0, F=0.915 /

&MATL ID='MAT_PUR125' 
DENSITY=25.0 
CONDUCTIVITY=0.7 
SPECIFIC_HEAT=2.0
HEAT_OF_COMBUSTION=23830.
HEAT_OF_REACTION=2500.
REFERENCE_TEMPERATURE=200.
REFERENCE_RATE=0.1
N_REACTIONS=1
NU_SPEC=1.0
SPEC_ID='pianka_poliuretan' /

//// POWIERZCHNIE /////

&SURF ID='FDS_wall' 
COLOR='CORNSILK 3' 
TRANSPARENCY=1 
MATL_ID='MAT_WALL' 
BACKING='VOID'
THICKNESS=0.16 /

&SURF ID='FDS_pur125' 
COLOR='BURLY WOOD 2' 
TRANSPARENCY=1 
MATL_ID='MAT_PUR125' 
BACKING='EXPOSED'
THICKNESS=0.116
BURN_AWAY=.TRUE. /

//// GEOMETRIA /////

&OBST XB=0.25, 1.0, 0.25, 1.0, 0, 0.75, SURF_ID='FDS_pur125' /
&OBST XB=-0.25, 1.5, -0.25, -0.125 , 0,2, SURF_ID='FDS_wall' /
&OBST XB=1.375, 1.5, -0.125, 1.375 , 0,2, SURF_ID='FDS_wall' /
&OBST XB=-0.25, 1.5, 1.375, 1.5 , 0,2, SURF_ID='FDS_wall' /

&TAIL /

**Comment by mcgratta** [comment]
Do not use REFERENCE_RATE. This parameter is only to be used if you have specific TGA or MCC data that describes the thermal degradation of the sample. I assume you are just making a guess about the REFERENCE_TEMPERATURE. Just use that.
