### ISSUE TITLE
POROUS_FLOOR command not working in FDS 6.2.0

### ISSUE THREAD

**Issue by rdwadhwani** [firemodels/fds#2590]
Hi all,
I am running following simple code in FDS to study the transport of langrangian particles in a channel. This is just a modified simple case just to check before applying it on our case.

The problem I am facing when I am running this code on FDS 6.2.0 the particles when falling on the surface are not bouncing off in random direction and are just behaving as paint ball type of particles.
When, I am using this same code in FDS 6.1.12/6.1.0 there is a numerical instability around 0.6-0.8 s but in those versions particles are bouncing off successfully. So, it will be a great help you if you provide me an insight what I am missing in my code.

The code is

&HEAD CHID='testing'/
&TIME T_END=10.0/

&MISC NOISE=.FALSE., W0=0., GVEC=0.,0.,-9.81, FREEZE_VELOCITY=.FALSE., STRATIFICATION=.FALSE., SECOND_ORDER_PARTICLE_TRANSPORT=.TRUE. /
&MISC POROUS_FLOOR=.FALSE./
&MESH ID='Mesh01-', IJK=20,20,20, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&MATL ID='STUFF', DENSITY=760., CONDUCTIVITY=0.1, SPECIFIC_HEAT=1. /
&SURF ID='cube', THICKNESS=0.01, MATL_ID='STUFF',  GEOMETRY='CARTESIAN', LENGTH=0.01, WIDTH=0.01/
&PART ID='particles', SURF_ID='cube', DRAG_COEFFICIENT=4, QUANTITIES(1)='W-VELOCITY' /
&INIT XB=0.1,0.1,0.35,0.35,0.5,0.5, UVW=0.,0.,0., N_PARTICLES=1, PART_ID='particles', DT_INSERT=0.1 /

&SURF ID='Surface01',
      RGB=255,102,0,
      VEL=-10.0,/
&SURF ID='GROUND'/

&OBST XB=0.0,0.05,0.25,0.5,0.3,0.6, RGB=255,84,84, THICKEN=.TRUE., SURF_ID='Surface01'/
&OBST XB=0.0,0.2,0.25,0.5,0.3,0.3, RGB=255,84,84, SURF_ID='INERT', /
&OBST XB=0.0,0.2,0.5,0.5,0.3,0.6, RGB=255,84,84, SURF_ID='INERT'/
&OBST XB=0.0,0.2,0.25,0.5,0.6,0.6, RGB=255,84,84, SURF_ID='INERT'/
&OBST XB=0.0,0.2,0.25,0.25,0.3,0.6, RGB=255,84,84, SURF_ID='INERT'/ 

&VENT SURF_ID='OPEN', XB=0,0,0,1,0,1, COLOR='GRAY 94', OUTLINE=.TRUE./ Mesh Vent: Mesh [XMIN]
&VENT SURF_ID='OPEN', XB=1,1,0,1,0,1, COLOR='GRAY 94', OUTLINE=.TRUE./ Mesh Vent: Mesh [XMAX]
&VENT SURF_ID='OPEN', XB=0,1,0,0,0,1, RGB=240,245,244, OUTLINE=.TRUE./ Mesh Vent: Mesh [YMIN]
&VENT SURF_ID='OPEN', XB=0,1,1,1,0,1, COLOR='GRAY 94', OUTLINE=.TRUE./ Mesh Vent: Mesh [YMAX]
&VENT SURF_ID='GROUND', XB=0,1,0,1,0,0, RGB=240,245,23/ Mesh Vent: Mesh [ZMIN]
&VENT SURF_ID='OPEN', XB=0,1,0,1,1,1, COLOR='GRAY 94', OUTLINE=.TRUE./ Mesh Vent: Mesh [ZMAX]

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=0.3/

&TAIL /

**Comment by mcgratta** [comment]
We changed the behavior of solid (non-liquid) particles in 6.2.0. They now should just hit the floor and be swept along by the flow, assuming they are light enough to be swept by the flow. Otherwise, they just remain where they are. For liquid droplets, there is some justification the random walk. For solid particles, there is not.

**Comment by rdwadhwani** [comment]
Hi Kevin Sir,
Oh okay.! So, is there a possibility of adding a random walk to the solid particles which was by default available in previous version in FDS 6.2.0? Further, can you help me to get the reason why this code shows numerical instability in FDS 6.1.0?
Thanks!

**Comment by mcgratta** [comment]
I am only interested in numerical instabilities in FDS 6.2.0, the current release. I would prefer not to add a random walk for solid particles because there is no physical justification for it. For liquids droplets, we know that the liquid will spread to fill the space. Thus, there is some justification for the random walk.
