### ISSUE TITLE
Matlab verification scripts not up to date

### ISSUE THREAD

**Issue by ecolombo** [firemodels/fds#2595]
Hello,
to run the Matlab scripts for postpro of the verification cases (FDS_verification_script.m), I had to make some adaptations. How comes? Details below. 
Thanks x great work & Greetings.

1) turb_model.m cases:
    the output files (e.g. csmag_32_uvw_001.csv) from fds 6.2.0 didn't have a header line
    to read them anyway I adapted "plotspec_uvw.m" by replacing
    M = importdata(filename,',',1);
    s = str2num(M.textdata{:});
    n = s(2);
   with 
    M.data = importdata(filename,',',0);  
    nt = regexp(filename,'\d+', 'match');  
    n = str2num(nt{1});                     

2) The definition of the variables SVN_Scale_X and SVN_Scale_Y was missing in the scripts ribbed_channel.m, pyrolysis.m, pulsating.m, rms_cov_corr.m . I added them after the statement "clear all".

**Comment by rmcdermo** [comment]
If you are using the current version of the code (latest Git version) then everything should work. 

On turb_models.m I have been working on adding DNS cases, which required me to use MPI, which required an overhaul of the output, etc.  So, what you experienced is just a bi-product of that overhaul.

Regarding SVN_Scale_X, etc., when we migrated from SVN to Git we changed some of the Matlab scripts and one thing we added was addverstr.m to tag the plots with the Git revision.  The position of the tag is given in that script.
