### ISSUE TITLE
OpenMP bug in radi.f90

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#2609]
This input file fails in debug mode but not in release mode (Git-441-g47d7ff3). It fails only when the number of OpenMP threads is greater than 1. I have been testing with 4 and 6.

&HEAD CHID = 'openmp_bug' /

&MULT ID='m1', DX=0.4, DY=0.5, I_UPPER=1, J_UPPER=1 /
&MESH IJK=40,50,50, XB=-0.4,0.0,-0.5,0.0,0.0,0.5, MULT_ID='m1' /

&TIME T_END=0.1 /

&TAIL /

To test, just compile the code, set the OMP_NUM_THREADS to greater than one, then just run the case at the command line with either the debug or release version.

**Comment by lu-kas** [comment]
It works for me on gcc 5.1.0, Git-442-gfb93068

**Comment by mcgratta** [comment]
This might be a bug with the Intel Fortran compiler. The bug occurs at line 974 of radi.f90. Could you look at the OpenMP directives surrounding the loop. I cannot see anything wrong with it, but when I added some debug statements, I could see that the OpenMP threads were not behaving properly.

**Comment by mcgratta** [comment]
Not a bug with the compiler. I added some local variables to PRIVATE and things appear to be working.

**Comment by rmcdermo** [comment]
The test case you posted fails for me with Git-456-g8b235f7.  Here is the output.  Notice that this seems to be running on only 1 thread, even though I have 4 enabled.  I think there is something wrong with Lukas's commit.

[rmcdermo@burn Test]$ fds_db test.fds
 OpenMP thread   0 of   0 is running
 OpenMP thread   3 of   0 is running
 OpenMP thread   1 of   0 is running
 OpenMP thread   2 of   0 is running

 Fire Dynamics Simulator

 Current Date     : August 12, 2015  09:13:37
 Version          : FDS 6.2.0
 Revision         : Git-456-g8b235f7
 Revision Date    : Tue Aug 11 17:16:46 2015 -0400
 Compilation Date : Aug 11, 2015  17:32:02

 MPI Disabled
 OpenMP Enabled; Number of OpenMP Threads:   4

 Job TITLE        : 
 Job ID string    : openmp_bug

forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source  
fds_intel_linux_6  0000000002AF63E1  Unknown               Unknown  Unknown
fds_intel_linux_6  0000000002AF4B37  Unknown               Unknown  Unknown
fds_intel_linux_6  0000000002AA6464  Unknown               Unknown  Unknown
fds_intel_linux_6  0000000002AA6276  Unknown               Unknown  Unknown
fds_intel_linux_6  0000000002A332B4  Unknown               Unknown  Unknown
fds_intel_linux_6  0000000002A3A874  Unknown               Unknown  Unknown
libpthread.so.0    00000035EC00F710  Unknown               Unknown  Unknown
fds_intel_linux_6  000000000268D4CF  pres_mp_compute_v         690  pres.f90
fds_intel_linux_6  00000000028781F4  fds_IP_pressure_i        1389  main.f90
fds_intel_linux_6  0000000002843DE3  MAIN__                    660  main.f90
fds_intel_linux_6  000000000040410E  Unknown               Unknown  Unknown
libc.so.6          00000035EB41ED5D  Unknown               Unknown  Unknown
fds_intel_linux_6  0000000000404019  Unknown               Unknown  Unknown
Aborted

**Comment by rmcdermo** [comment]
Note: this is the SERIAL version of fds_db.  I have 4 OMP threads set in my env.  But it looks to me like only 1 is being used (timing-wise this seems to be the case as well, it is slow).

**Comment by lu-kas** [comment]
the output of total thread had a bug, which is corrected in a pending pull request from yesterday evening

**Comment by lu-kas** [comment]
the commit will not fix the numerical issue, but only the misleading output of total threads

**Comment by mcgratta** [comment]
This is an odd behavior. I get the crash only with the non-MPI version of the code. Let me investigate this before we make any other changes.

**Comment by mcgratta** [comment]
I think this bug is related to the MPI vs non-MPI version of the code. I get the floating invalid error with 1 OpenMP thread.

**Comment by rmcdermo** [comment]
Bueno.  Git-469-g9db975a works!  Thanks.
