### ISSUE TITLE
 H_F on subroutines READ_REAC, GAS_PROPS

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#2627]
Hello firemodels team, 

I'm testing the Verification/Visualization/plume5c.fds case, compiling the code with intel and gfortran in fire76.

It seems there is an uninitialized variable H_F for the case of FORMULA="null" in subroutine READ_REAC. I pick this up with valgrind, gnu compiler, for the case of SIMPLE_CHEMISTRY=.true., around line ~3235 in read.f90.
The subsequent call to GAS_PROPS (line ~3240) feeds into this routine H_F uninitialized. In GAS_PROPS (line ~2770 of data.f90) this uninitialized value is dumped in H_FIN, which is used in the conditional (line ~3085 of data.f90):

IF (H_FIN > -2E21) H_F = H_FIN

After that, all hell breaks loose with for the debug version of gnu. Setting H_F=0._EB in the declaration of line ~3165

REAL(EB) :: E_TMP=0._EB,S_TMP=0._EB,ATOM_COUNTS(118),MW_FUEL=0._EB,H_F=0._EB,PR_TMP

seems to fix the problem. Is that a good initial value for H_F? How about PR_TMP?

Also, I don't see a zero initialize flag on the compilers options (on makefile). I assume this is done on purpose?

I also compiled the intel_linux_64_db version and running plume5c.fds, does not stop on this uninitialized variable. 

Thank you,

Marcos

**Comment by mcgratta** [comment]
I'll fix this.

**Comment by mcgratta** [comment]
I committed the change you suggested. I set H_F to zero. As far as I can tell, H_F is just a dummy variable in this subroutine. I'm going to reassign the issue to Jason so that he can just double check what I did.

**Comment by marcosvanella** [comment]
Hi Kevin, just to let you know, I see another uninitialized variable:
SF%LAYER_MATL_FRAC(NL,N) (with NL =1, N=2) for this test case, in line ~6640 of read.f90, subroutine PROC_WALL. It is fed as argument of:
DENSITY_MAX = MAX(DENSITY_MAX,SF%LAYER_MATL_FRAC(NL,N)*SF%LAYER_DENSITY(NL))
again around line 6640 of read.f90. This is giving a complaint on valgrind instrumented gnu_linux_db.
I will try to dig out why is this field value not initialized. 
Marcos

**Comment by mcgratta** [comment]
This material stuff is tricky. Post the case and I'll debug it.

**Comment by marcosvanella** [comment]
I compile the code with gfortran and debug flags, on fire76, and run the case Verification/Visualization/plume5c.fds. 
I put a couple of print statements on the subroutine PROC_WALL, within the DO loops for indexes NL=1,SF%N_LAYERS, N=1,SF%N_MATL (line ~6633 of read.f90). The SF%N_MATL=2 for this case. SURF_INDEX=1 and N_SURF=13. For this SURFACE SF%N_LAYERS=2.
When NL=1 and N=2, the SURFACE field SF%LAYER_MATL_FRAC(NL,N) seems undefined, as a Valgrind instrumentation of the run gives:

==25182== Conditional jump or move depends on uninitialised value(s)
==25182==    at 0x4F1B176: ??? (in /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0)
==25182==    by 0x4F1D9A4: ??? (in /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0)
==25182==    by 0x4F1E46E: ??? (in /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0)
==25182==    by 0xCF0707: **read_input_MOD_proc_wall (read.f90:6649)
==25182==    by 0xD880C0: __read_input_MOD_read_data (read.f90:124)
==25182==    by 0xFBF520: MAIN** (main.f90:108)
==25182==    by 0x10774A7: main (main.f90:5)
==25182==  Uninitialised value was created by a stack allocation
==25182==    at 0xCFEA7C: __read_input_MOD_read_surf (read.f90:5208)

The complaint is probably because the uninitialized variable is being used in line ~6645 of read.f90, within a max intrinsic:
DENSITY_MAX = MAX(DENSITY_MAX,SF%LAYER_MATL_FRAC(NL,N)*SF%LAYER_DENSITY(NL))

So I guess we need to figure out why for this problem, SURFACE(1)%LAYER_MATL_FRAC(1,2) is not initialized? When I print out the value for this variable I get 0.00000.., which makes the problem hard to see. I can dig a bit more on this.

**Comment by mcgratta** [comment]
This is a bug. I'll fix it. Briefly, a SURFace can have multiple layers, and multiple material components per layer. SF%N_MATL is the total number of different materials for the entire SURF. For the SURF ULHOLSTERY_LOWER, there are two materials, but only 1 per layer. The 2 is being used in the slot that should be 1.

**Comment by mcgratta** [comment]
I just committed a fix for the uninitialized variable. Let me know if it fixes the bug, then close the issue. If another uninitialized variable pops up, open a new issue.

**Comment by marcosvanella** [comment]
Hi Kevin, this fixed the bug. Thank you.

**Comment by drjfloyd** [comment]
H_F=0 should be fine.
