### ISSUE TITLE
FDS does not compile cleanly without OpenMP flag

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#2635]
The function OMP_SET_NUM_THREADS is unresolved if FDS is compiled without the OpenMP flag. Could we (1) hide the call behind a compiler directive like !$, and (2) ensure that all OpenMP NUM_THREADS variables are set to 1 in the event that no OpenMP compiler flags have been set. We want to make sure that FDS can always be compiled without MPI and OpenMP features.

**Comment by lu-kas** [comment]
ok, shall I put that in?

**Comment by mcgratta** [comment]
Should I just put !$ in front of the call to OMP_SET_NUM_THREADS ? If so, I will just do it.

**Comment by lu-kas** [comment]
see pull request
all relevant variables are either initialised to meaningful default values, or are by purpose set to invalid values

**Comment by mcgratta** [comment]
Great. I tested it and the code now compiles without the OpenMP options. Thanks.
