### ISSUE TITLE
pyrolysis model (MCC recreation) returns to ambient/stops midway through simulation when low density in MATL is used

### ISSUE THREAD

**Issue by konradwilkens** [firemodels/fds#2640]
Fire Dynamics Simulator
 Compilation Date : Sat, 11 Apr 2015
 Current Date     : August 20, 2015  13:11:34
 Version          : FDS 6.2.0
 SVN Revision No. : 22343
Operating System: OSX Yosemite 

I have noticed that when I input a low density for one of the MATL IDs in this case ‘TDI’ the calculation does something strange. It stops the temperature ramp (heating rate) and it returns to ambient  and the calculation of other DEVCs I have in there e.g. normalised HRR, also go to zero.

I have confirmed its not just this input file, I tested it with some of the other example files (cable_11_mcc), and they run fine with their ‘normal’ densities, but as soon as i change to a lower one, e.g. 26kg/m3 the calculations also halt. 

Maybe this is an issue regarding number of sig figs, as I also tried changing the THICKNESS value, and when this is larger e.g. 0.01, the calculation seems to get further along in the run.

See file below:

&HEAD CHID='FPUF_mcc_kraemer_1', TITLE='Micro-Calorimetry Test of fpuf' / 

&MESH IJK=3,1,4, XB=-2,2,-0.5,0.5,0,1 /  

&TIME T_END=600., WALL_INCREMENT=1, DT=0.01 /  

&MISC SOLID_PHASE_ONLY=.TRUE., Y_O2_INFTY=0.01, ASSUMED_GAS_TEMPERATURE=820., ASSUMED_GAS_TEMPERATURE_RAMP='T_RAMP'  /
&RAMP ID='T_RAMP', T=  0., F = 0.0 /
&RAMP ID='T_RAMP', T=600., F = 1.0 /

&RADI RADIATION=.FALSE. /
&REAC FUEL='METHANE', CRITICAL_FLAME_TEMPERATURE=2000. /  No gas phase reaction

&VENT XB=-1, 1,-0.5,0.5,0.0,0.0, SURF_ID='fpuf' /

&SURF ID = 'fpuf'
      RGB =200,100,0
      BACKING = 'INSULATED' 
      THICKNESS = 0.00001
      HEAT_TRANSFER_COEFFICIENT = 1000.
      MATL_ID(1,1) = 'TDI',
      MATL_ID(1,2) = 'polyol'
      MATL_MASS_FRACTION(1,1:2) = 0.322,0.678 /  

&MATL ID                    = 'TDI'
      EMISSIVITY            = 1.0
      DENSITY               = 26.
      CONDUCTIVITY          = 0.05
      SPECIFIC_HEAT         = 1.0
      N_REACTIONS           = 1
      REFERENCE_TEMPERATURE = 311.
      REFERENCE_RATE        = 0.4764 
      HEATING_RATE          = 176.
      NU_MATL               = 0.06
      MATL_ID               = 'char'  
      NU_SPEC               = 0.94
      SPEC_ID               = 'METHANE'
      HEAT_OF_COMBUSTION    = 24.
      HEAT_OF_REACTION      = 1000. /

&MATL ID                    = 'polyol'
      EMISSIVITY            = 1.0
      DENSITY               = 1000.
      CONDUCTIVITY          = 0.2
      SPECIFIC_HEAT         = 1.5
      N_REACTIONS           = 1
      REFERENCE_TEMPERATURE = 427.
      REFERENCE_RATE        = 0.2690
      HEATING_RATE          = 176.
      NU_MATL               = 0.06
      MATL_ID               = 'char'
      NU_SPEC               = 0.94
      SPEC_ID               = 'METHANE'
      HEAT_OF_COMBUSTION    = 28.
      HEAT_OF_REACTION      = 1000. /

&MATL ID                    = 'char'
      EMISSIVITY            = 1.0
      DENSITY               =  60.
      CONDUCTIVITY          = 0.1
      SPECIFIC_HEAT         = 1.0 /

&DEVC XYZ=0.0,0.0,0.0, IOR= 3, QUANTITY='WALL TEMPERATURE', ID='heater temp' /
&DEVC XYZ=0.0,0.0,0.0, IOR= 3, QUANTITY='WALL TEMPERATURE', ID='sample temp' /
&DEVC XYZ=0.0,0.0,0.0, IOR= 3, QUANTITY='NORMALIZED HEAT RELEASE RATE', ID='hrrpum' /
&DEVC XYZ=0.0,0.0,0.0, IOR= 3, QUANTITY='SURFACE DENSITY', ID='mpua' /

&TAIL /

**Comment by mcgratta** [comment]
Thanks, I'll take a look at this. I'm teaching a class this week, but should be able to look at it next week.

**Comment by konradwilkens** [comment]
No problem, have fun teaching!

**Comment by mcgratta** [comment]
Add this to the SURF line for ‘fpuf’

MINIMUM_LAYER_THICKNESS = 0.000000001

I forgot about this – in FDS, we have a minimum layer thickness for solids of 1.E-6 m (1 micrometer). We do this just so that the calculations do not develop numerical problems. However, for these MCC and TGA calculations, we sometimes use very thin layers to mimic the heat transfer in the test apparatus. 

Let me know if this fixes the problem.

**Comment by konradwilkens** [comment]
Hi Kevin,

Yes this worked! Thank you for that.

Konrad

**Comment by mcgratta** [comment]
Great. Thanks for letting us know.
