### ISSUE TITLE
program error 157

### ISSUE THREAD

**Issue by WATANABEKUNN** [firemodels/fds#2643]
I am using the FDS version 6.1.2.

I am trying to do a simulation with liquid fuel. But when it was 51st second, there was program error which told me like this:forrtl: severe (157): Program Exception - access violation.

I think there are some mistakes in the source files. Please check it.
The following is my inputfile.

&HEAD CHID='20',TITLE='oil' /
&MESH ID='1', IJK=50,50,10, XB=-5,5,-5,5,0,1,MPI_PROCESS=0/
&MESH ID='2', IJK=50,50,10,  XB=-5,5,-5,5,1,2,MPI_PROCESS=1/
&MESH ID='3', IJK=50,50,10, XB=-5,5,-5,5,2,3,MPI_PROCESS=2/
&MESH ID='4', IJK=50,50,10, XB=-5,5,-5,5,3,4,MPI_PROCESS=3/
&MESH ID='5', IJK=50,50,10, XB=-5,5,-5,5,4,5,MPI_PROCESS=4/
&MESH ID='6', IJK=50,50,10, XB=-5,5,-5,5,5,6,MPI_PROCESS=5/
&MESH ID='7', IJK=50,50,10, XB=-5,5,-5,5,6,7,MPI_PROCESS=6/
&MESH ID='8', IJK=50,50,10, XB=-5,5,-5,5,7,8,MPI_PROCESS=7/
&MESH ID='9', IJK=50,50,10, XB=-5,5,-5,5,8,9,MPI_PROCESS=8/
&MESH ID='10', IJK=50,50,10, XB=-5,5,-5,5,9,10,MPI_PROCESS=9/
&MESH ID='11', IJK=50,50,10, XB=-5,5,-5,5,10,11,MPI_PROCESS=10/
&MESH ID='12', IJK=50,50,10, XB=-5,5,-5,5,11,12,MPI_PROCESS=11/
&TIME T_END=100/
&MISC TMPA=20/
&DUMP NFRAMES=3000, DT_HRR=1,DT_DEVC=1,DT_RESTART=5/
&VENT MB='ZMIN',SURF_ID='OPEN'/
&VENT MB='ZMAX',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/

&MATL ID = 'STEEL-S', EMISSIVITY = 0.22, DENSITY = 8027.,CONDUCTIVITY = 17,SPECIFIC_HEAT = 0.502 / 
&SURF ID = 'STEEL-S SHEET', COLOR = 'GRAY 50',  MATL_ID = 'STEEL', THICKNESS = 0.001, BACKING   = 'EXPOSED'/
&MATL ID = 'CONCRETE', EMISSIVITY = 0.6,DENSITY = 2200., CONDUCTIVITY = 1.2,  SPECIFIC_HEAT = 0.88 /
&SURF ID = 'CONCRETE',COLOR ='SLATE GRAY',MATL_ID = 'CONCRETE',THICKNESS=0.1,BACKING ='INSULATED'/, 
&MATL ID = 'WATER', DENSITY = 1000., EMISSIVITY = 0.98, CONDUCTIVITY = 0.1, SPECIFIC_HEAT = 4.184, ABSORPTION_COEFFICIENT= 1578 / 
&MATL ID  = 'STEEL',  EMISSIVITY = 1.0, DENSITY = 7850.,  CONDUCTIVITY  = 45.8, SPECIFIC_HEAT = 0.46 /
&SURF ID  = 'STEEL SHEET', COLOR= 'SILVER', MATL_ID ='STEEL',  BACKING  = 'EXPOSED',  THICKNESS = 0.003 /
&SURF ID  = 'Adiabatic Wall', COLOR= 'SILVER', ADIABATIC=.TRUE., DEFAULT = .TRUE.  /  
&REAC FUEL ='OIL',FYI = 'CAS8042-47-5,C_25 H_43 N_1 O_3',     HEAT_OF_COMBUSTION =45400.,O = 3., C = 25., H  = 43., N=1, CO_YIELD=.008, SOOT_YIELD = 0.015 /
&MATL ID   = 'M OIL', EMISSIVITY = 1.,NU_SPEC= 1.,SPEC_ID  = 'OIL', HEAT_OF_REACTION = 110, CONDUCTIVITY  = 0.17, SPECIFIC_HEAT  = 0.95, BOILING_TEMPERATURE = 400, DENSITY= 884., ABSORPTION_COEFFICIENT= 160.5 / 
&SURF ID='BURNER1',COLOR='RED',HRRPUA=2200, RAMP_Q='fireramp' /
&RAMP ID='fireramp', T= 0.0, F=0.0 /
&RAMP ID='fireramp', T= 1.0, F=0.2/
&RAMP ID='fireramp', T= 2.0, F=0.4/
&RAMP ID='fireramp', T=4.0, F=0.6/
&RAMP ID='fireramp', T=10.0, F=0.8/
&RAMP ID='fireramp', T=15.0, F=1.0/
&RAMP ID='fireramp', T=20.0, F=1.0/
&RAMP ID='fireramp', T=25.0, F=0.5/
&RAMP ID='fireramp', T=26.0, F=0/
&VENT XB=-0.3,0.3,-0.3,0.3,0.05,0.05, SURF_ID='BURNER1'/ 
&SURF ID='BURNER2',COLOR='YELLOW',MATL_ID='M OIL','WATER','STEEL-S', THICKNESS=0.03,0.08,0.0002/
&OBST XB=-1,1,-1,1,0.0,0.05, SURF_IDS='BURNER2', 'STEEL-S SHEET','STEEL-S SHEET' /
&OBST XB=-5,5,-5,5,0,0,SURF_ID='CONCRETE'/
&OBST XB=-5,5,-5,-5,0.2,11.3,SURF_ID='Adiabatic Wall',COLOR='INVISIBLE'/
&OBST XB=-5,5,5,5,0.2,11.3,SURF_ID='Adiabatic Wall'/
&OBST XB=-5,-5,-5,5,0.2,11.3,SURF_ID='Adiabatic Wall'/
&OBST XB=5,5,-5,5,0.2,11.3,SURF_ID='Adiabatic Wall', COLOR='INVISIBLE'/
&OBST XB=-5,5,-5,5,11.5,11.5,SURF_ID='CONCRETE'/
&TAIL /

**Comment by mcgratta** [comment]
Run it with 6.2.0, and let me know how it goes. Simplify the case as much as possible.

**Comment by WATANABEKUNN** [comment]
It worked. Thank you so much.
