### ISSUE TITLE
Control INITIAL_STATE not initialized to default FALSE

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#2654]
Version : FDS 6.2.0
SVN Revision No. : 22343

It appears that in the current release of FDS the INITIAL_STATE is not initialized to default FALSE. In the attached example, a TIMER control is used to create an obstruction at t=10.0 seconds. However, the FDS solution appears to include the obstruction at t=0. I tested FDS 6.1.1 with the same input and the behavior is as expected.

Even if I explicitly set INITIAL_STATE=.FALSE. in the DEVC definition, the obstruction still is active in the model.

We did test vents and they seem to work ok.

Here is the input file. Is there a way to attach other files not just images?

Thanks,
Daniel Swenson
Thunderhead Engineering

Obstacle_simple.fds
Generated by PyroSim - Version 2015.3.0810
Aug 27, 2015 8:58:18 AM

&HEAD CHID='Obstacle_simple'/
&TIME T_END=20.0/
&DUMP RENDER_FILE='Obstacle_simple.ge1', COLUMN_DUMP_LIMIT=.TRUE./

&MESH ID='Mesh01', IJK=25,25,25, XB=0.0,5.0,0.0,5.0,0.0,5.0/

&REAC ID='POLYURETHANE_REAC',
      FYI='SFPE Handbook, GM27',
      FUEL='REAC_FUEL',
      C=1.0,
      H=1.7,
      O=0.3,
      N=0.08,
      CO_YIELD=0.042,
      SOOT_YIELD=0.198/

&DEVC ID='TIMER', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=10.0/
&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=1000.0/

&OBST XB=3.6,4.0,3.6,4.0,0.0,0.4, SURF_IDS='Fire','INERT','INERT'/ Fire Box
&OBST XB=0.0,5.0,2.4,2.6,2.4,5.0, SURF_ID='INERT', DEVC_ID='TIMER'/ Obstruction

&VENT SURF_ID='OPEN', XB=0.0,5.0,0.0,0.0,0.0,5.0/ Open Side

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBX=3.8/

&TAIL /

![model](https://cloud.githubusercontent.com/assets/13338306/9528151/c0bba4c0-4cb8-11e5-8b81-dc7b28f41fc2.png)
![smokeview at t 9 9](https://cloud.githubusercontent.com/assets/13338306/9528155/c6065772-4cb8-11e5-9838-a6c7fa87a8aa.png)
![smokeview at t 10 1](https://cloud.githubusercontent.com/assets/13338306/9528157/c927951a-4cb8-11e5-83da-abe2b4ff0d1a.png)

**Comment by drjfloyd** [comment]
Unfortunately, Github is limited in types of files you can attach.  

Your case is working with the current source. I recall there was a recent issue where someone had a room with a door that Kevin had worked on.  Probably the same bug.

**Comment by mcgratta** [comment]
Dan, can you guys compile from source?

**Comment by dvswenson** [comment]
Jason,

Thanks.

Also, I did find an error in my NZ derivation. I have a conference call
now, but would you be free in about one hour? I promise a short call.

Here are the corrected and expanded spreadsheets. The NZ calc now matches
what you had expected.

The post is down for now.

Thanks,
Dan

On Thu, Aug 27, 2015 at 12:49 PM, Jason Floyd notifications@github.com
wrote:

> Unfortunately, Github is limited in types of files you can attach.
> 
> Your case is working with the current source. I recall there was a recent
> issue where someone had a room with a door that Kevin had worked on.
> Probably the same bug.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2654#issuecomment-135505392
> .

## 

Daniel Swenson
Thunderhead Engineering
www.thunderheadeng.com
swenson@thunderheadeng.com
+1.785.770.8511 x103

**Comment by rmcdermo** [comment]
The trick to attaching other types of files is to simply append ".png" to
the file name.  For example, test.fds.png for an input file.  You can then
download the file and change the extension and voila!

**Comment by ManuelFDS** [comment]
Hello, 
Thanks for solving this important problem so fast. Is it possible to distribute a binary version?

Thanks Manuel

**Comment by rmcdermo** [comment]
We are working on a new release.  Could be a month away, though.
