### ISSUE TITLE
Smokeview shows some kinds of artifacts in Plot3d 2d speed

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#2663]
Smokeview 6.2.5
Mac OS X 10.10
The latest version aof SMV seems to show some artifacts (a ray across the visualised slice, please compare the attached picture) in Plot3d, 15 s, 2d, speed.

&HEAD CHID='VEL_Temp', TITLE='VEL T +'  / 
&MESH IJK=30,30,30, XB=0.0,3.0, 0.0,3.0, 0.0,3.0 / 
&TIME T_END=15.0 / 

&SURF ID='BLACK', VEL=-2.0, TMP_FRONT=60., RGB=128,128,128/

&VENT XB=0.0,0.0, 1.1,1.9, 0.2,1.0, XYZ=0.0, 1.5, 0.6, RADIUS=0.4, SPREAD_RATE=1., SURF_ID='BLACK' /

&VENT MB='XMAX', SURF_ID='OPEN'/
&VENT MB='ZMAX', SURF_ID='OPEN'/
&VENT MB='ZMIN', SURF_ID='OPEN'/
&VENT MB='YMIN', SURF_ID='OPEN'/
&VENT MB='YMAX', SURF_ID='OPEN'/

&SLCF PBY=1.5, QUANTITY='VELOCITY', VECTOR=.TRUE./
&SLCF PBY=1.5, QUANTITY='TEMPERATURE', VECTOR=.TRUE./

&DUMP DT_PL3D=5., PLOT3D_QUANTITY(1:5)='TEMPERATURE', 'U-VELOCITY','V-VELOCITY','W-VELOCITY','HRRPUV' /
&TAIL /

![vel_temp_s0001](https://cloud.githubusercontent.com/assets/14057187/9582448/b21fbe06-5005-11e5-8cc8-24ac380dae42.png)

Perhaps someone can confirm the problem?

**Comment by rmcdermo** [comment]
Thanks, Boris.  We will have a look.

**Comment by gforney** [comment]
I'm not able to reproduce the problem - even on the mac.   I assume you are using the latest released version of FDS (shouldn't make a difference).  Try erasing all files except input file and rerunning the case.

**Comment by boris-stock** [comment]
Glenn,

thanks for your fast response. Yes, latest FDS version. The artifact appears reproducable, but not in every 2d-slice of Plot3D. Could you please give it a try to move the 2d slice of Plot3 forward and backward in the scene?

**Comment by boris-stock** [comment]
Can't be reproduced at other computers.

Thanks for your help.

Boris
