### ISSUE TITLE
Smokeview transparency of ISOSURFACE

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#2667]
Smokeview 6.2.5
Mac OS X 10.10

The .ini file of smokeview contains the following subsection: 

ISOCOLORS
 10.000000 0.900000 : shininess, transparency
 0.700000 0.700000 0.700000 : specular

As far as I understand, the second number (0.900000) should define the transparency of the Isosurfaces shown in SMV with values between 0 and 1. This seems not to work.

I am attaching 2 screenshots with transparency = 0.0 and 0.8 where no difference in transparency is shown.

&HEAD CHID='VEL_Temp', TITLE='VEL T +'  / 
&MESH IJK=30,30,30, XB=0.0,3.0, 0.0,3.0, 0.0,3.0 / 
&TIME T_END=15.0 / 
&SURF ID='BLACK', VEL=-2.0, TMP_FRONT=60., RGB=128,128,128/
&VENT XB=0.0,0.0, 1.1,1.9, 0.2,1.0, XYZ=0.0, 1.5, 0.6, RADIUS=0.4, SPREAD_RATE=1., SURF_ID='BLACK' /
&VENT MB='XMAX', SURF_ID='OPEN'/
&VENT MB='ZMAX', SURF_ID='OPEN'/
&VENT MB='ZMIN', SURF_ID='OPEN'/
&VENT MB='YMIN', SURF_ID='OPEN'/
&VENT MB='YMAX', SURF_ID='OPEN'/
&ISOF QUANTITY='TEMPERATURE', VALUE(1)=40., VALUE(2)=30. /
&TAIL /

![vel_temp_0642_transp0_0](https://cloud.githubusercontent.com/assets/14057187/9588143/e1ce3756-5026-11e5-923a-309d11915d46.png)
![vel_temp_0642_transp0_8](https://cloud.githubusercontent.com/assets/14057187/9588142/e1cd318a-5026-11e5-9d51-03b1df92d703.png)

**Comment by gforney** [comment]
this field is used to control the default transparency value for all isosurface levels (if the 4th color component below is not present).  The transparency of a particular isosurface level is controlled by the 4th color component (0.80 below).  You can set the isosurface transparency levels in smokeview using Isosurface File/Bounds dialog box.  I'll update the manual to make this clearer

ISOCOLORS
 10.000000 0.800000 : shininess, transparency
 0.700000 0.700000 0.700000 : specular
 10
 0.960000 0.000000 0.960000 0.800000
 0.750000 0.800000 0.800000 0.800000
 0.000000 0.960000 0.280000 0.800000
 0.000000 0.000000 1.000000 0.800000
 0.000000 0.718750 1.000000 0.800000
 0.000000 1.000000 0.562500 0.800000
 0.171850 1.000000 0.000000 0.800000
 0.890625 1.000000 0.000000 0.800000
 1.000000 0.380952 0.000000 0.800000
 1.000000 0.000000 0.000000 0.800000

**Comment by boris-stock** [comment]
Thanks a lot again, for your fast help.

Boris

**Comment by boris-stock** [comment]
Works as it should.

Thanks...
