### ISSUE TITLE
Russian language version of Smokeview

### ISSUE THREAD

**Issue by Nadezhda-Kontar** [firemodels/fds#2691]
Texts in menus are displayed well (see menu.png), but texts in dialogs not well (dialog.png).
I add example translation of smokeview_ru.po in forum https://groups.google.com/forum/#!topic/fds-smv/0Q4lQJYec24
![dialog](https://cloud.githubusercontent.com/assets/14135186/9697828/50452fa8-53b7-11e5-966f-9f29052fc3f8.png)
![menu](https://cloud.githubusercontent.com/assets/14135186/9697830/55c0f886-53b7-11e5-917f-7aa0ea90915d.png)

**Comment by saschagottfried** [comment]
Translation files usually should use UTF-8 encoding. I examined your file smokeview_ru.po, probably edited on a Windows machine and encoded with charset Windows 1251. 
I saved the file using UTF-8 but a recent Smokeview version garbles the russian message strings. Available translation files (de/fr) use ANSI charset. Both translations lack typical special characters of each language.  

I investigated this topic a couple of months ago and could offer my experience with i18n/l10n translation using GETTEXT infrastructure. Glenn Forney, Smokeview developer, probably needs to support this in the application as well to support UTF-8 encoded message catalogs. I think this may be a requirement to address global translations efforts - with emphasis on cyrillic, arabian, japanese etc. languages.

**Comment by gforney** [comment]
unfortunately, the libraries smokeview uses (the dialog box library anyway) do not support 8 bit encoded text files.  So, translation for languages that need these types of files won't be possible now.

**Comment by saschagottfried** [comment]
Please summarize known technical limitations in your [translations wiki page](https://github.com/firemodels/fds-smv/wiki/International-Resources-and-Translators). Thank you!

Any ideas which 7-bit encoding/charset could enable russian translation in Smokeview?

**Comment by gforney** [comment]
You are pointing to the wrong page.  The wiki on translating smokeview text is found here
https://github.com/firemodels/fds-smv/wiki/Smokeview-Other-Languages where I do discuss the limitations.  I did add a link to the "overall" translation page to poing to the smokeview tranlsation page.

To the original poster, Nadezhda-Kontar, try sending me your 8 bit encoded translation file again.

**Comment by saschagottfried** [comment]
Glenn, I am sorry. I just skimmed the wiki pages top to bottom. 

Nevertheless I tried to save the translation file `smokeview_ru.po` using encodings UTF-8, Windows Codepage 1251, ISO 8859-5, Windows 866 Codepage since these are possible charsets to address cyrillic languages. 

On my machine smokeview 6.1.1 did not render menus in russian. I may need to install different locales.  

I would recommend to russian contributors to save smokeview translation file using the encodings mentioned above.

``` shell
$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by Nadezhda-Kontar** [comment]
Russian translation file here https://drive.google.com/open?id=0B3x9rrgAeM1XRGRDQjlvUllQUnBYODRwRTdHakhPendNWjcw

**Comment by gforney** [comment]
you need to change the sharing status for this file.  Think it is private
now .  I was not able to access the link.

On Thu, Sep 17, 2015 at 9:55 AM, Nadezhda-Kontar notifications@github.com
wrote:

> Russian translation file here
> https://drive.google.com/open?id=0B3x9rrgAeM1XRGRDQjlvUllQUnBYODRwRTdHakhPendNWjcw
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2691#issuecomment-141094223
> .

## 

Glenn Forney

**Comment by Nadezhda-Kontar** [comment]
sorry, please try again
https://drive.google.com/file/d/0B3x9rrgAeM1XRGRDQjlvUllQUnBYODRwRTdHakhPendNWjcw/view?usp=sharing

**Comment by gforney** [comment]
no problem. thanks - that worked

On Thu, Sep 17, 2015 at 10:00 AM, Nadezhda-Kontar notifications@github.com
wrote:

> sorry, please try again
> 
> https://drive.google.com/file/d/0B3x9rrgAeM1XRGRDQjlvUllQUnBYODRwRTdHakhPendNWjcw/view?usp=sharing
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2691#issuecomment-141095643
> .

## 

Glenn Forney

**Comment by foolstone** [comment]
The limitation of showing multi-bytes language in dialogbox is because the openGL libraries (GLUT and GLUI) used in smokeview can't display multi-bytes characters. Few years back I modified some functions to make smokeview show the Chinese. Unfortunately I lost the source code now.
