### ISSUE TITLE
Segmentation Fault in FDS 6.2.0 on Linux, not Windows

### ISSUE THREAD

**Issue by jrsellers09** [firemodels/fds#2711]
Hello!

I am receiving a sementation fault in FDS 6.2.0 when running on a Linux Cluster, however when I run the same file on Windows through PyroSim (using FDS 6.2.0) I do not get the same error.  The error occurs immediately after running.

What would cause this error or how could I best give you more information to determine the cause?

Thanks!

J.R.

**Comment by mcgratta** [comment]
We need the input file.

**Comment by mcgratta** [comment]
Closed, no response.
