### ISSUE TITLE
Opening smokeview after pyrosim FDS simulation goes wrong

### ISSUE THREAD

**Issue by rednasss** [firemodels/fds#2725]
Hello,

I am using PyroSim. When I run an FDS Simulation it automatically opens smokeview.
However, nothing is shown in this new window. It is just white, but I can add the slices etc.
But my geometry is hidden. It says it is shown but it isn't and it should show the geometry immediately after opening the window, which it doesn't.
How is this possible?

Thanks in advance.

**Comment by gforney** [comment]
Sounds like a problem with how you set up your case in pyrosim.  I would
contact them for help.

Hello,

I am using PyroSim. When I run an FDS Simulation it automatically opens
smokeview.
However, nothing is shown in this new window. It is just white, but I can
add the slices etc.
But my geometry is hidden. It says it is shown but it isn't and it should
show the geometry immediately after opening the window, which it doesn't.
How is this possible?

Thanks in advance.

—
Reply to this email directly or view it on GitHub
https://github.com/firemodels/fds-smv/issues/2725.

**Comment by kyleperkuhn** [comment]
This issue has been resolved by [Thunderhead Enginnering Support](mailto:support@thunderheadeng.com)

> Thank you for reporting this issue. The problem you encountered is made up of two parts. The first part of the problem is that in PyroSim 2015.0810, we made a change to how we write the Smokeview INI file. This means that by default, when you launch Smokeview from PyroSim, your model is displayed based on the GE1 file (Smokeview refers to this as "CAD Mode"). 
> 
> The other part of the problem is that we were failing to write the GE1 file correctly for international versions. We were incorrectly handling the use of the ',' character and the '.' character to show the decimal point. So, your model will not display correctly under Smokeview's CAD Mode.
> 
> The fix for this involves pressing the 'q' key when looking at your Smokeview results. This will toggle which display mode is being used. We have fixed the issue in our internal versions, but hopefully this workaround will be sufficient in the meantime.
