### ISSUE TITLE
What does the QUANTITY='CHEMISTRY SUBITERATIONS' do?

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#2744]
I see QUANTITY='CHEMISTRY SUBITERATIONS' in V&V cases, but not mentioned in the manual.  What exactly does this quantity output?

**Comment by rmcdermo** [comment]
It is a diagnostic that Crag Weinschenk put in to make sure his ODE integrator for Arrhenius chemistry is behaving properly.  He should write it up.

**Comment by rmcdermo** [comment]
...with all his free time (in other words, Craig is buried, so don't expect this soon).

**Comment by bwklein** [comment]
I understand, and no hurry on the write up.  I just needed a bit more context for translation to other languages.

**Comment by bwklein** [comment]
Sorry, I realized that you had assigned this to Craig for a write up.  I reopened it.

**Comment by cweinschenk** [comment]
I had an error with my notification on git and just now seeing this. I put together a brief writeup shortly.

**Comment by cweinschenk** [comment]
@rmcdermo Do you want this in the Users Guide or Tech Guide?

**Comment by rmcdermo** [comment]
If you think it is solid, then sure.

**Comment by cweinschenk** [comment]
@bwklein A discussion is added to the latest User Guide.
