### ISSUE TITLE
problem with device dialog box

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2777]
Some of the device dialog box is missing.  See case below

&HEAD CHID='devices'/
&TIME T_END=60.0/
&DUMP RENDER_FILE='devices.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0/

&MESH ID='Mesh01', IJK=20,20,6, XB=0.0,10.0,0.0,10.0,0.0,3.0/

&REAC ID='POLYURETHANE_REAC',
      FYI='SFPE Handbook, GM27',
      FUEL='REAC_FUEL',
      C=1.0,
      H=1.7,
      O=0.3,
      N=0.08,
      CO_YIELD=0.042,
      SOOT_YIELD=0.198/

&DEVC ID='velocity', QUANTITY='VELOCITY', XYZ=0.25,1.75,1.75, ORIENTATION=-1.0,0.0,0.0/
&SURF ID='supply 5 m/s',
      RGB=26,204,26,
      VEL=-5.0/

&VENT SURF_ID='OPEN', XB=10.0,10.0,0.0,10.0,0.0,3.0/ Mesh Vent: Mesh01 [XMAX]
&VENT SURF_ID='OPEN', XB=0.0,10.0,10.0,10.0,0.0,3.0/ Mesh Vent: Mesh01 [YMAX]
&VENT SURF_ID='OPEN', XB=0.0,10.0,0.0,0.0,0.0,3.0/ Mesh Vent: Mesh01 [YMIN]
&VENT SURF_ID='OPEN', XB=0.0,10.0,0.0,10.0,3.0,3.0/ Mesh Vent: Mesh01 [ZMAX]
&VENT SURF_ID='supply 5 m/s', XB=0.0,0.0,1.5,2.0,1.5,2.0/ supply vent, 5 m/s

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=1.75/

&TAIL /

**Comment by gforney** [comment]
try smokeview posted at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

**Comment by Dave-McGill** [comment]
That fixed it. (A very cool feature.)

Thanks
