### ISSUE TITLE
Smokeview: Flip Colorbar

### ISSUE THREAD

**Issue by guipesa** [firemodels/fds#2808]
I think it will be useful to have a keyboard shortcut to flip the colorbar. It would save time when you are looking temperatures and visibility, to flip the colorbar more easily.

Thanks in advance,
Guillem Peris,

**Comment by gforney** [comment]
try smokeview posted at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

use the ';' key to flip the colorbar

**Comment by guipesa** [comment]
It works perfectly,
Thanks!

**Comment by gforney** [comment]
great.  thanks for reporting back.
