### ISSUE TITLE
How to get 6.2.0 FDS version from GitHub?

### ISSUE THREAD

**Issue by LeTEXIER** [firemodels/fds#2828]
I apologize me to ask a so basic question, but I only find branch/tag "master", "Git", ...
on the GitHub repository, no "V6.2.0" for example.
Have I miss something to get the source files?
Up to now, I usually get some TAR.GZ file with the version number in the file name.
Thank you for your attention.

**Comment by rmcdermo** [comment]
We are still working out issues with our tagging system.  V6.2.0 is 6fc9308eaf197366208cf4ec005743fa5f61c8c6

You need to clone the repo and checkout that commit.

**Comment by LeTEXIER** [comment]
Thank you very much.
Same question for 6.3.0. That's all!

**Comment by drjfloyd** [comment]
There is no 6.3.  The latest release is 6.2.  The latest developmental source (which will ultimately become 6.3) is the current state of the development branch.
