### ISSUE TITLE
Label name of SOOT in Smokeview

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#2831]
It appears that the SHORT_NAME for the output quantity DENSITY, with SPEC_ID='SOOT' is now rho*C0.9H0.1 because of

```
   CASE('SOOT')
      SIGMA = 3.798_EB
      EPSOK = 71.4_EB
      FORMULA = 'C0.9H0.1'
      H_F = 0._EB
      IF (RADCAL_NAME=='null') RADCAL_NAME='SOOT'
```

Is there a way to by-pass this so that Smokeview only sees rho*soot or something similar that will not change?

**Comment by gforney** [comment]
fyi:  this change broke volume rendered smoke/fire in smokeview

**Comment by drjfloyd** [comment]
we can add logic after species have been processed to scan species names, locate soot, and override

**Comment by drjfloyd** [comment]
What exactly is broken?  Is is the generation of SMOKEVIEW_BAR_LABEL and if so does this mean any non-integer FORMLUA won't work?

**Comment by mcgratta** [comment]
When Smokeview creates a rendering of smoke and fire using TMP and RHO_SOOT, it looks for the SHORT_NAMEs "temp" and "rho_soot". The latter has become "rho*C0.9H0.1" or whatever. Smokeview needs these names to be fixed.

**Comment by gforney** [comment]
what kevin said - (actually rho_Soot).  here is an input line for soot that I use

&SLCF XB=0.0,1.6,0.0,1.6,0.0,3.2, QUANTITY='DENSITY',SPEC_ID='SOOT',CELL_CENTERED=.TRUE.  / 3D slice

what if we flag the slice file as soot when we read it in then output soot somewhere else in the SLCF entry in the .smv file  (if you are using the short label for something else)

**Comment by drjfloyd** [comment]
So what I need to change is SMOKE3D_SMOKEVIEW_BAR_LABEL?  Or do you want a generic change to the routine GET_QUANTITY_INDEX so all SMOKEVIEW_BAR_LABELs being output by the routine are not based on FORMULA for SOOT but just say soot?

**Comment by gforney** [comment]
actually maybe there is a simpler solution involving only smokeview.  right now fds is outputting SOOT DENSITY for the "long label" in the .smv file .  as long as that stays that way, I can  look for that string .when I'm looking for volume rendered smoke files.  someone would have to use a new version of smokeview to look at these files  genereratd by new versions of fds - but we say that all the time as we add new features to fds that are visualized in smokeview

**Comment by gforney** [comment]
my work around works so no need to do anything in FDS
