### ISSUE TITLE
SEGMENTATION FAULT occurs with pressure zone and HVAC

### ISSUE THREAD

**Issue by cunconbkhp** [firemodels/fds#2903]
Hi! I'm trying to simulate an apartment fire. I run the FDS file on a cluster (parallel mode with 36 meshed). 
In my first case, the window is opened, no pressure zone, no HVAC system, the simulation runs successfully  
In my second case, the window is closed, so the apartment is totally closed. The whole apartment is declared as a pressure zone (zone 1). The leak surface is apply to all exterior walls. A HVAC system is applied to prevent the overpressure in the apartment which can caused numerical instability. Very early, just after the beginning of the simulation, the SEGMENTATION FAULT occurs. 

I attach the input  file. Can you please help me to diagnose the problem. I run the same parallel case (with pressure zone and HVAC) on a linux computer and it works (but not on the cluster) .

**Comment by mcgratta** [comment]
I don't see the input file.

**Comment by cunconbkhp** [comment]
i have some problem, every time i attach the file txt, an error occurs: Something went really wrong, and we can’t process that file. try again.

**Comment by mcgratta** [comment]
change the .fds to a .txt and try it. I think GitHub only accepts certain file types.

**Comment by cunconbkhp** [comment]
I've changed the file .fds to .txt but still the same error

**Comment by rmcdermo** [comment]
Also try adding .png extension.  I've been able to trick GitHub into accepting files like this.

**Comment by cunconbkhp** [comment]
![appt_t1_test52 txt](https://cloud.githubusercontent.com/assets/14924739/10221464/e3ddcb52-684e-11e5-99dd-d614039592b8.png)

**Comment by cunconbkhp** [comment]
that's great! thanks you very much , rmcdermo!

**Comment by mcgratta** [comment]
[tangential_velocity_svn.txt](https://github.com/firemodels/fds-smv/files/5958/tangential_velocity_svn.txt)

This is just a test.

**Comment by cunconbkhp** [comment]
here is the input file 
![appt_t1_test52 txt](https://cloud.githubusercontent.com/assets/14924739/10221510/295796a4-684f-11e5-9995-ee4dc94890de.png)

**Comment by cunconbkhp** [comment]
mcgratta, can you open it?

**Comment by rmcdermo** [comment]
I was able to, Kevin is working on it.

**Comment by mcgratta** [comment]
I got it.

**Comment by mcgratta** [comment]
I am running your case on our linux cluster. It appears to be running OK, at least at the start. What did you mean when you said:

```
 I run the same parallel case (with pressure zone and HVAC) on a linux computer and it works (but not on the cluster) .
```

**Comment by cunconbkhp** [comment]
first of fall, I run this input file on a cluster and the segmentation fault occur. Then i test it on another linux computer and it run normally. I don't understand why?

**Comment by mcgratta** [comment]
If the case runs on my machine, what can I do to help you? This sounds to me like the problem is with your machine. We are releasing FDS 6.3.0 this week. My only suggestion is to upgrade to this when it comes out and your problem may resolve itself.

**Comment by cunconbkhp** [comment]
thank you, macgratta!
