### ISSUE TITLE
I have downloaded FDS 6.3.0 for windows (windows 10) what now?

### ISSUE THREAD

**Issue by DamienMason92** [firemodels/fds#2917]
Hello,

I need FDS-SMV for my university individual project but I am unsure what I need to do after downloading it, I tried this youtube video https://www.youtube.com/watch?v=MXuuSBJAkLA  but I couldn't get past the 'cmd' stage, I really need this to be downloaded on my computer for my project please help!

Damien Mason

**Comment by mcgratta** [comment]
That video is out of date. Describe to me step by step what you have done.

**Comment by DamienMason92** [comment]
Hello,

Thank you for your prompt response, I have followed this video up until 7:15, when I typed 'cd desktop' in the command window I got a message stating "the system cannot find the path specified." so I stopped there.

**Comment by mcgratta** [comment]
I said that the video is out of date. Don't watch it. Tell me what you did from the point at which you clicked on the download button.

**Comment by DamienMason92** [comment]
I went to downloads and clicked the the FDS download and then another window popped up to which I clicked unzip and I have restarted my computer, that's all.

**Comment by mcgratta** [comment]
OK, the program installed. Type

fds

at the command prompt to make sure. If you see the version number and other info, it's time to read the manual. It should be under FDS on the program menu.

**Comment by DamienMason92** [comment]
Hello , when I type FDS in the cmd window I get:

Fire Dynamic Simulator

Current date: ...
Version: ...
Revision: ...
Revision date: ...
Compilation date: ...

and some other information, it now says consult FDS user guide chapter running FDS, for further instructions which I will now do. thank you for your help on this.

**Comment by mcgratta** [comment]
OK, the program installed properly. Now read the users guide about how to write an input file. Once you do that, you run FDS by typing

fds input_file.fds
