### ISSUE TITLE
HVAC, LEAK feature

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#2928]
Hi,

I'm trying to model a leak through a vertical gap in a door. I've modified the door_crack example. I can do it using a conventional VENT<->NODE<->DUCT<->NODE<->VENT. I've also tried using the new HVAC LEAK feature as described in the section on Localized Leakage, using the following lines, which are found at the bottom of page 108.

&VENT XB=...,SURF_ID='SURF 1',ID='VENT 1'/
&VENT XB=...,SURF_ID='SURF 2',ID='VENT 2'/
&HVAC ID='LEAK1',TYPE_ID='LEAK',VENT_ID='VENT 1',VENT2_ID='VENT 2',AREA=0.001/ 

I get the following error message.

ERROR: SURF_ID SURF 1 not found for VENT 8, ........

That suggest that lines defining the SURF are required. 

See the attached file, the section, "Leakage path through vertical gap". Both methods are shown, but the traditional HVAC method is commented out.

Thanks

Dave

P.S I've tried attaching the file as both a PNG and TXT, and neither worked.

**Comment by drjfloyd** [comment]
Dave,

There wasn't any attachment.  Based on your comments, you do need to define a the SURFs being used for the VENT definitions.  FDS uses the SURF for the local heat transfer and the HVAC for the mass flow. We should probably make that clear in the Guide.

**Comment by Dave-McGill** [comment]
Jason,

That was anticlimactic. I figured there was some special SURF characteristic. All I did was add,

&SURF ID='SURF 1'  /
&SURF ID='SURF 2'  /

and it worked.

Thanks

**Comment by drjfloyd** [comment]
Made some manual updates to make this more clear. Thanks for reporting.

**Comment by Dave-McGill** [comment]
Hi Jason,

Is there a location on the new site to see the daily/nightly builds of the manuals?

Thanks

**Comment by rmcdermo** [comment]
We have not added this yet.  I'll try to do this today.  In the mean time,
here is a link to latest docs, though we did not get a clean build last
night so not sure if Jason's changes are in this version.

http://goo.gl/n1Q3WH

**Comment by Dave-McGill** [comment]
Thanks Randy. On a related note, I tried several times to upload both png and txt files to this issue, without any luck.

**Comment by drjfloyd** [comment]
Dave, my changes won't be in the overnight build as I made them just a few minutes ago.

You can see the changes to the tex file here:

https://github.com/firemodels/fds-smv/commit/6ac4b42fb4ad7c9f642397877b52c97cf0d84f7a

**Comment by rmcdermo** [comment]
Testing upload of files.
[test.txt](https://github.com/firemodels/fds-smv/files/8433/test.txt)

**Comment by drjfloyd** [comment]
Randy, I see and can download your test.txt.

**Comment by rmcdermo** [comment]
Dave,
How are you creating your text file?  I just tested one, but I was careful to create a plain text file from my vim editor.  Are you doing something like saving as... from a .docx?  GitHub just introduced this feature, so I am not surprise there are problems.  We will have to be patient until this is sorted out.

**Comment by Dave-McGill** [comment]
Randy,

I'm using Textpad to create an fds file, and then renaming it.

It's something unique to the txt files, as I am able to upload a png.

![velocity cell centered](https://cloud.githubusercontent.com/assets/13259079/10309429/88e947ca-6c0a-11e5-95c5-87419c631ebe.png)

**Comment by rmcdermo** [comment]
Can you confirm that the file is plain text?  That is, not "rich text
format".  I am just guessing that rtf might be a problem.

**Comment by Dave-McGill** [comment]
I can run the files in fds from the command prompt, so I'm inferring it is plain text. I'll mail you the file, and you try and add it.

**Comment by rmcdermo** [comment]
Test upload of Dave's document.
[leak_gap.txt](https://github.com/firemodels/fds-smv/files/8495/leak_gap.txt)

**Comment by rmcdermo** [comment]
Testing drag and drop.
[leak_gap.txt](https://github.com/firemodels/fds-smv/files/8498/leak_gap.txt)

Both seem to work.

**Comment by rmcdermo** [comment]
Dave,
Do you have a GitHub account?  And are you logged into it?  I am just brainstorming possibilities.

**Comment by Dave-McGill** [comment]
It's something at my end. I downloaded the file and tried to drag it into this box to upload it, and got the error message.

I'm using Win8, and Chrome , for what it's worth.

I do have a github account. My name is appearing beside these posts, so I think I'm logged in. As I recall, I had to get an account to post an issue.

**Comment by rmcdermo** [comment]
Good point.  Sorry for the stupid question.

**Comment by Dave-McGill** [comment]
That's OK young fella.   :-)

I'm logged into IE, and still can't upload a text file.

**Comment by rmcdermo** [comment]
Dave,

I would send a message to the GitHub support team.  See the "Contact a
Human" button at the bottom of this page:

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

They have been very good about helping us with problems.

Randy

**Comment by Dave-McGill** [comment]
OK, I'll give it a try.
