### ISSUE TITLE
Numerical Instability HRR for Fuel Species

### ISSUE THREAD

**Issue by jamesfletch** [firemodels/fds#2941]
We have used the following input for FDS about the combustion

A)
&REAC ID='Reaction1',
      FUEL='REAC_FUEL',
      FORMULA='C10H20',
     SOOT_YIELD=0.14,
      HEAT_OF_COMBUSTION=2.4201E4/

which is supposed to reflect the properties of a Diesel fire. 

Our model is a subway station with exhaust dampers at high level, running tunnels at either side of the station and an open entrance that leads to two paths (stairwells that enter the island platform). Usually, with a previous combustion species

B)
&REAC ID='Reaction1',
      FUEL='REAC_FUEL',
      FORMULA='C3H8O3N4',
      SOOT_YIELD=0.14,
      HEAT_OF_COMBUSTION=2.4201E4/

we had no issues with flow rates or HRR. When we replace the original species B with A, the HRR is very unstable and fluctuates around an average value and for some reason the flow rates from the open entrance begin to gradually reduce to a point where we get flow reversal and then the entrance actually starts to exhaust air rather than naturally supply it as the exhaust fans are running whilst the running tunnels increase in supply steadily. 

![species_flow_rates](https://cloud.githubusercontent.com/assets/15012508/10334685/b6d20a58-6ce3-11e5-88e1-1a35cb842082.png)
![hrr_issue](https://cloud.githubusercontent.com/assets/15012508/10334716/e662e544-6ce3-11e5-97fa-afd1336df074.png)

**Comment by drjfloyd** [comment]
24 kJ/kg of fuel is a very low value for a hydrocarbon fuel.

Fuel A has an EPUMO2 of 8000 kJ/kgO2, this is a bit low, one would expect something closer to 13000.
Fuel B has an EPUMO2 of 64000 kJ/kgO2, this is extremely high.

Fuel B will require very little air entrainment to burn completely.  Fuel A will require 8 times as much entrainment.  It is not surprising that you see different behavior in the flow field.  Is your run actually failing from a numerical instability?

**Comment by jamesfletch** [comment]
No, there was no failure due to numerical instability. I see that this is more of a physics issue now that you have explained it, rather than an issue with the program and it makes sense now.

Thanks for your time, it was a great help!
