### ISSUE TITLE
Bulk density and heat output

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#2949]
Note - input file with a results summary follows this text.

I am using the BULK_DENSITY feature now, and getting some mixed results.

It appears that once the value of BULK_DENSITY goes above some threshold that the total heat release is capped.

I have an object 0.1 m \* 0.1 m \* 0.2 m, with a density of 100 kg/m3, total mass is 0.2 kg.  The object occupies one grid cell.  I initially thought that BULK_DENSITY = 100 kg/m3 would be a sensible limit.  Heat of combustion of my material is 30000 kJ/kg.  So this should have given about 6000 kJ of heat.    

When I run this model I observe the following:
- Total heat released at BULK_DENSITY varying from 100 kg/m3 to (about) 25 kg/m3 is around 1200 kJ (i.e. the number does not change at different values of BULK_DENSITY).
- Total heat released is less than what I expected (around 6000 kJ).
- The above result was based on the top face igniting (0.1 m \* 0.2 m).  If I change the face to the side of the object (0.1 m \* 0.1 m) the heat realeased halves.
- The volume of the domain is 2.4 m by 2.4 m by 1.0 m, and therefore I don't believe I am getting near to consuming all the oxygen.
- When I decrease the BULK_DENSITY to 1.0 kg/m3 I start to see the behavior I expected.

It appears to me that FDS is limiting the total heat released in some way.

My hypothesis is that it is doing the following to limit the total heat available:

1) Maximum total mass of combustible fuel = area of face burning \* thickness of material \* density of material = A (kg).
2) Maximum energy release is then capped as follows: If OBST volume \* BULK_DENSITY exceeds A (see above), then the heat release is capped.

This seems too complex but it does reflect the behavior I am seeing when I run simple test cases.  I was applying BULK_DENSITY simply to compute the mass of combustible material as OBST volume \* BULK_DENSITY, but something seems to be different to this if the BULK_DENSITY goes above some limit?

****_INPUT FILE - RESULTS SUMMARY AT END**_**

&HEAD CHID='WBP-04-32', TITLE='test' /

&MESH IJK=24,5,24, XB=0.0,2.4,0.0,1.0,0.0,2.4 /

&TIME T_END=900.0 /

&MISC INITIAL_UNMIXED_FRACTION=0.0 /

&REAC FUEL='MYFUEL',FORMULA='C8H8',HEAT_OF_COMBUSTION=40000.0,SOOT_YIELD=0.01 /

---

Material density is set here, it is 100 kg/m3

---

&MATL ID                    = 'FABRIC'
      FYI                   = 'Properties completely fabricated'
      SPECIFIC_HEAT         = 1.0
      CONDUCTIVITY          = 0.1
      DENSITY               = 100.0
      N_REACTIONS           = 1
      NU_SPEC               = 1.0
      SPEC_ID               = 'MYFUEL'
      REFERENCE_TEMPERATURE = 200.0
      HEAT_OF_REACTION      = 500.0 
      HEAT_OF_COMBUSTION    = 30000.0 /

&MATL ID            = 'GYPSUM PLASTER'
      FYI           = 'Quintiere, Fire Behavior'
      CONDUCTIVITY  = 0.48
      SPECIFIC_HEAT = 0.84
      DENSITY       = 1440.0 /

---

Material thickness is set here, it is 0.02 m

---

&SURF ID             = 'UPHOLSTERY'
      FYI            = 'Properties completely fabricated'
      COLOR          = 'PURPLE'
      BURN_AWAY      = .TRUE.
      MATL_ID        = 'FABRIC'
      BACKING        = 'EXPOSED'
      THICKNESS      = 0.02 /

&SURF ID             = 'WALL'
      DEFAULT        = .TRUE.
      RGB            = 200,200,200
      MATL_ID        = 'GYPSUM PLASTER'
      THICKNESS      = 0.012 /

---

Obstruction, 0.1 m \* 0.2 m \* 0.1 m (one grid cell) = 0.002 m3
Density = 100 kg/m3 (unless BULK DENSITY is set)
Heat of combustion = 30000 kJ/kg
Integrated heat output obtained from the HRR file sum of (dt \* HRR)
Results from several tests at the end of this file

---

&OBST XB=0.8,0.9,0.2,0.4,0.4,0.5,SURF_ID='UPHOLSTERY',BULK_DENSITY=5.0 /

---

This is the ignition particle, coordinates are:
Side: XYZ=0.85,0.19,0.45
Top:  XYZ=0.85,0.30,0.51

---

&SURF ID='ignitor',TMP_FRONT=1000.0,GEOMETRY='CYLINDRICAL',LENGTH=0.1,RADIUS=0.01 /
&PART ID='ignitor particle',SURF_ID='ignitor',STATIC=.TRUE.,AGE=10000 /
&INIT XYZ=0.85,0.30,0.51,DX=0.1,PART_ID='ignitor particle',N_PARTICLES=1 /

&BNDF QUANTITY='BURNING RATE' /

&TAIL /

---

RESULTS

If the particle ignites the side of the obstacle and bulk density is not set:
Heat = 0.1 \* 0.1 \* 0.02 \* 100 \* 30000 = 600 kJ (594 kJ - ok)

If the particle ignites the top of the obstacle and bulk density is not set:
Heat = 0.1 \* 0.2 \* 0.02 \* 100 \* 30000 = 1200 kJ (1179 kJ - ok)

If the particle ignites the top of the obstacle and bulk density is set to 100 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 100 \* 30000 = 6000 kJ
Heat actually is = 1174 kJ

If the particle ignites the top of the obstacle and bulk density is set to 20 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 20 \* 30000 = 1200 kJ (1179 kJ - ok)

If the particle ignites the top of the obstacle and bulk density is set to 15 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 15 \* 30000 = 900 kJ (893 kJ - ok)

If the particle ignites the side of the obstacle and bulk density is set to 15 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 15 \* 30000 = 900 kJ
Heat actually is = 594 kJ

If the particle ignites the side of the obstacle and bulk density is set to 5 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 5 \* 30000 = 300 kJ (300 kJ - ok)

If the particle ignites the top of the obstacle and bulk density is set to 5 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 5 \* 30000 = 300 kJ (300 kJ - ok)

---

**Comment by mcgratta** [comment]
First, get rid of this

&MISC INITIAL_UNMIXED_FRACTION=0.0 /

It is not appropriate for the simple chemistry combustion model that you are using. Second, change the THICKNESS of the UPHOLSTERY. FDS is burning it away. When I use BULK_DENSITY, I still give the obstruction a THICKNESS comparable to a grid cell for the purpose of doing the heat transfer calculation. In your case, I set THICKNESS=0.1, then I set BULK_DENSITY to 50 and the amount of fuel generated was 0.1 kg = 0.002 m3 x 50 kg/m3. When I set the B_D to 100, the obstruction did not disappear in 900 s.

**Comment by mcgratta** [comment]
Did this advice help?

**Comment by mattbilson76** [comment]
Sorry I was slow in replying.  Busy week last week.

Yes, the advice helped.  Thank you. 

I had initially thought that bulk density would cause thickness to be ignored, but it is not the case.  I looked again at the two cases that were causing "problems" and as you suggested changed the thickness setting and the INITIAL UNMIXED FRACTION.

Generally it worked well.  However, the case with the larger bulk density (100 kg/m3) gave a different result when the INITIAL UNMIXED FRACTION was not set (5900 kJ versus 4560 kJ), which is puzzling.  You can see the specific results below.

BEFORE:
If the particle ignites the top of the obstacle and bulk density is set to 100 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 100 \* 30000 = 6000 kJ
Heat actually is = 1174 kJ

AFTER:
With thickness set to 0.1 m the FHRR was around 6000 kJ (>5900 kJ, but if INITIAL_UNMIXED_FRACTION was not set then the result was 4560 kJ).

BEFORE:

If the particle ignites the side of the obstacle and bulk density is set to 15 kg/m3:
Heat should equal = 0.1 \* 0.2 \* 0.1 \* 15 \* 30000 = 900 kJ
Heat actually is = 594 kJ
AFTER:
With thickness set to 0.1 m the FHRR was around 898 kJ (either setting of INITIAL_UNMIXED_FRACTION).

**Comment by mcgratta** [comment]
Getting confusing. Is there a case without INITIAL_UNMIXED_FRACTION that is producing an expected result? If so, post the case, and just the case that fails.

**Comment by mcgratta** [comment]
Correction: Is there a case without INITIAL_UNMIXED_FRACTION that is producing an UNexpected result? If so, post the case, and just the case that fails.

**Comment by mattbilson76** [comment]
Ok, below is the cut down case file.

&HEAD CHID='test', TITLE='test' /
&MESH IJK=24,5,24, XB=0.0,2.4,0.0,1.0,0.0,2.4 /
&TIME T_END=900.0 /
&REAC FUEL='MYFUEL', FORMULA='C8H8', HEAT_OF_COMBUSTION=40000.0, SOOT_YIELD=0.01 /

&MATL ID = 'FABRIC', SPECIFIC_HEAT = 1.0, CONDUCTIVITY = 0.1, DENSITY = 100.0, N_REACTIONS = 1, NU_SPEC = 1.0, SPEC_ID = 'MYFUEL', REFERENCE_TEMPERATURE = 200.0, HEAT_OF_REACTION = 500.0, HEAT_OF_COMBUSTION = 30000.0 /

&SURF ID = 'UPHOLSTERY', COLOR = 'PURPLE', BURN_AWAY = .TRUE., MATL_ID = 'FABRIC', BACKING = 'EXPOSED', THICKNESS = 0.1 /

&OBST XB=0.8,0.9,0.2,0.4,0.4,0.5,SURF_ID='UPHOLSTERY',BULK_DENSITY=100.0 /

&SURF ID='ignitor',TMP_FRONT=1000.0,GEOMETRY='CYLINDRICAL',LENGTH=0.1,RADIUS=0.01 /
&PART ID='ignitor particle',SURF_ID='ignitor',STATIC=.TRUE.,AGE=10000 /
&INIT XYZ=0.85,0.30,0.51,DX=0.1,PART_ID='ignitor particle',N_PARTICLES=1 /

&BNDF QUANTITY='BURNING RATE' /

&TAIL /

**Comment by mcgratta** [comment]
After 900 s, the item is still burning. Plot time vs Mass Loss Rate (MLR).

**Comment by mattbilson76** [comment]
Ran it for 1800 s.  Success.  Thanks.
