### ISSUE TITLE
Smokeview, showing values for different devices 

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#2951]
Hi Glenn,

Currently, Dialog -> Data -> Devices/Objects allows the display of the data from one type of device. It would be a nice enhancement if different types of devices could be displayed at the same time. For example, temperature and velocity.

Thanks

Dave

**Comment by gforney** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
This is possible in more recent versions of Smokeview.
