### ISSUE TITLE
Smokeview - do not show quantity name on each device

### ISSUE THREAD

**Issue by saschagottfried** [firemodels/fds#2954]
Hi Glenn,

Currently, in Dialog -> Data -> Devices/Objects users choose from the given device quantities. Every point is labelled with the selected quantity. If I use this nice feature in a given model with hundreds of devices tracking `Adiabatic Surface Temperature` a large portion of the screen is filled with text. There is no space left for device output values. This screen area is pretty black.

It would be a nice enhancement if you choose something else for labelling the device points. Personally I would prefer only to see device output values to reduce visual clutter. Users could rely on 3D perception. What do you think about optionally labelling the points with its coordinates as a distinct information within a collection of devices with same quantity ? 

Thanks

Sascha

**Comment by gforney** [comment]
I'll take a look at this.

**Comment by gforney** [comment]
Take a look at an updated smokeview located at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

I added checkboxes to the objects/devices dialog box for hiding the device type (ie U-Velocity, Tempeature etc) and units.

**Comment by saschagottfried** [comment]
Hi Glenn,

this is useful for me. I attached a rendered image where you can see how
this enhancement supports my use case. Thank you.

Best regards,
Sascha

On Fri, Oct 16, 2015 at 8:12 AM, Glenn Forney notifications@github.com
wrote:

> Take a look at an updated smokeview located at
> 
> https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing
> 
> I added checkboxes to the objects/devices dialog box for hiding the device
> type (ie U-Velocity, Tempeature etc) and units.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2954#issuecomment-148619360
> .

## 

Mit freundlichen Grüßen
Sascha Gottfried

Gryphiusstr. 16
10245 Berlin
Mobil: 0177/3017020
Fon: 030/23464807
Email: sascha.gottfried@googlemail.com

**Comment by gforney** [comment]
thanks for the feedback
