### ISSUE TITLE
Manual is unclear on HVAC TYPE_ID='LEAK'

### ISSUE THREAD

**Issue by chulann** [firemodels/fds#2955]
In Section 9.2 of the FDS manual, it states "TYPE_ID can be DUCT, NODE, FAN, FILTER, or AIRCOIL"

In Section 9.3.2 under "Localized leakage", it states "To use this approach two VENT inputs are linked via an HVAC input with TYPE_ID=’LEAK’."

This suggests there is an additional HVAC type to those listed in 9.2.

Additionally, under localized leakage, it would be useful to give a bit more information on the SURF requirements - is the XB defined in the VENT or the SURF?

**Comment by drjfloyd** [comment]
I am out till Monday. I've made some changes a few days ago for a similar
issue and will check to see what else I might need to add to clarify things.

**Comment by drjfloyd** [comment]
Added LEAK to the list and added more discussion of SURF in the Local Leakage section.   https://github.com/firemodels/fds-smv/commit/4b45d329f96aa451dec22b9792112efdb35026d5

**Comment by chulann** [comment]
Thanks Dr. Floyd,
That makes it much clearer. I'm assuming that the SURF doesn't have to
be unique since it's only used for heat transfer properties?

A nit-pick if I may. The sentence "The input must correspond to either
a {\ct SURF} input" is incomplete - since it states "either" and
doesn't give an alternative.

Regards
Cian

**Comment by drjfloyd** [comment]
Good nit pick, I will fix that.

Yes, the SURF doesn't have to be unique.
