### ISSUE TITLE
HVAC paralel problem

### ISSUE THREAD

**Issue by cunconbkhp** [firemodels/fds#2956]
Hi all!

I simulating an apartment fire. The initial pressure of the appartment is -50 Pa. To obtain this negative pressure, a HVAC system is apply (two outlet with fan and two inlet). I test some inert cases to verify the HVAC (no fire)
- at first i tried a coarse mesh (10 cm) with 2 meshes blocks for the room. The simulation runs well. The negative pressure is  obtaines (afetr 10 s) and remain stable till the end of the simulation (500 s)
- then i used a finer mesh (5 cm) with 18 meshes blocks for the room. This time, the simulation result is very strange. The room pressure decreases very slowly. After 150 s of simulation the pressure is only -25 Pa.  

Did any one experience this problem. My input file is attached. 
![appt_t1_hvac_test2 txt](https://cloud.githubusercontent.com/assets/14924739/10516191/56e571e6-7357-11e5-992f-f86b4f9a590c.png)

**Comment by mcgratta** [comment]
What version of FDS are you using?

**Comment by cunconbkhp** [comment]
I'm using version 6.0.2

**Comment by mcgratta** [comment]
Can you guess what I am going to say?

**Comment by cunconbkhp** [comment]
so i have to update to the latest version of FDS (6.2)?

**Comment by mcgratta** [comment]
6..3

I simplified your case a bit and it worked. You can try the full case. One thing -- in FDS 6.3, the RADIATIVE_FRACTION goes on the REAC line. Also, get rid of options like BAROCLINIC=.FALSE. These are no longer needed. Get rid of any options that you do not understand. Some of just left over from old versions.

**Comment by cunconbkhp** [comment]
In fact , i've verified my calcul with 5cm mesh and the room depression (-50 Pa) is obtained at t=1000 s.  What do you think about that? and when you run it with FDS 6.3, how long does it take (for the finer mesh) ?

**Comment by mcgratta** [comment]
The pressure dropped down to -50 Pa within about 10 simulated seconds. Turn off all reactions. Only model the HVAC system. You should see the pressure go to your desired value fairly quickly.

**Comment by cunconbkhp** [comment]
so the FDS 6.0 HVAC doesn't work well in multi meshes mode. Thanks you mcgratta!

**Comment by mcgratta** [comment]
That is most likely the problem. This is why we release updates -- we fix things.
