### ISSUE TITLE
problem in DUMP_GLOBAL_OUTPUTS

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#2965]
For the case geom_azim.fds, ICYC=0 and EVAC_TIME_ITERATIONS=50 so this IF statement in DUMP_GLOBAL_OUTPUTS returns control the calling routine resulting in all code following it to be skipped.  Don't think this should happen.  

IF (ICYC>-EVAC_TIME_ITERATIONS .AND. ICYC < 1) RETURN ! No dumps at the evacuation initialization phase

**Comment by tkorhon1** [comment]
I have corrected this sometimes at the beginning of year 2016. Now the DUMP_GLOBAL_OUTPUTS
has a line:

IF (ANY(EVACUATION_ONLY) .AND. (ICYC<1 .AND. T>T_BEGIN)) RETURN ! No dumps at the evacuation initialization phase

So, I'll close this one. I managed to make the evacuation work nicely with the main.f90
(Kevin's MPI modifications, same DT in all fire meshes, etc) at the beginning of Feb 2016.

Timo
