### ISSUE TITLE
Function_type Power with incorrect results

### ISSUE THREAD

**Issue by fab6** [firemodels/fds#2973]
Hello,

the results for power1 and power4 are not 'correct'.

&CTRL ID='Power4',FUNCTION_TYPE='POWER',INPUT_ID='temp','CONSTANT',CONSTANT=4.0/
&DEVC ID='CF TempPower4',QUANTITY='CONTROL VALUE',CTRL_ID='Power4',XYZ=0,0,0, TIME_AVERAGED=.FALSE./

&CTRL ID='Power2',FUNCTION_TYPE='POWER',INPUT_ID='temp','CONSTANT',CONSTANT=2.0/
&DEVC ID='CF TempPower2',QUANTITY='CONTROL VALUE',CTRL_ID='Power2',XYZ=0,0,0, TIME_AVERAGED=.FALSE./

&CTRL ID='Power1',FUNCTION_TYPE='POWER',INPUT_ID='temp','CONSTANT',CONSTANT=1.0/
&DEVC ID='CF TempPower1',QUANTITY='CONTROL VALUE',CTRL_ID='Power1',XYZ=0,0,0, TIME_AVERAGED=.FALSE./

unfortunately I am not able to attach any files.
Please see the file from Randy and my attached csv file in the forum.

**Comment by drjfloyd** [comment]
The order of operations in FDS is at the end of each time step we evaluate devices.  During the timestep we evaluate control functions. So at timestep n, the device input for a control function comes from timestep n-1.  If you square power1 values in the devc you will see they match the power2 values, the slight difference in the power1 control function from the time device is the order of operations.  

Something though isn't right with power4.

**Comment by rmcdermo** [comment]
[test_power.fds.txt](https://github.com/firemodels/fds-smv/files/17095/test_power.fds.txt)

Sorry... I was playing with uploading the file and hit the wrong button.

**Comment by drjfloyd** [comment]
I see the problem.  CTRL functions default to SETPOINT=1000000 with LATCH = TRUE.  So when the 4th power goes over that value the CTRL function is no longer evaluated.  We picked 1000000 way back when we were first just doing temperature and time based control functions and that seemed like a very large number to use as a default. Just add SETPOINT=1E30. I'll make this a much larger number in the source.

**Comment by fab6** [comment]
Thanks for the help!

**Comment by fab6** [comment]
Hello Jason, hello Randy,

I did just run the file with time averaged for temp and adjusting the
setpoint, but my values are still slightly different!?

Thanks!
Fabian

On Tue, Oct 20, 2015 at 9:50 PM, Jason Floyd notifications@github.com
wrote:

> Closed #2973 https://github.com/firemodels/fds-smv/issues/2973.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/2973#event-440759143.

## 

Regards!
Fabian

**Comment by drjfloyd** [comment]
If I run the attached file at T=0.8 s in the output power1=45.13068.  power2=2036.778=45.13068^2. power4=4148465.8=power2^2=power1^4.  What are you seeing that is different (recall my prior comment that control functions use values from the prior timestep so the control functions at 0.8 s are using data from 0.79 s).

[test_power.txt](https://github.com/firemodels/fds-smv/files/17589/test_power.txt)

**Comment by fab6** [comment]
Yes, I missed this with the time shift.
I got slightly different numbers in the 0.8-time-row with your file:
Time,temp,CF TempPower4,CF TempPower4a,CF TempPower2,CF TempPower1,Power1^4 LibreOffice
0.79,45.133251,oldP4,oldP3,oldP2,oldP1,oldP1LibreOffice
0.8,newTemp,4149411.8,91936.914,2037.0105,45.133251,4149411.14901439
