### ISSUE TITLE
Command prompt not working

### ISSUE THREAD

**Issue by rednasss** [firemodels/fds#2976]
Hello,

I have a complete simulation from pyrosim. When I run this from pyrosim there are no errors and it starts the simulation.
However, I need to add some extra things to the .fds file. But I always try the exact same file as pyrosim uses within command prompt to check if the same simulation works without the edits. I installed the new version of fds & smv from the website, but it seems to be different than previous versions. I had a .bat script to start simulations on 2 other computers and there I had to start them with fds6 <filename>.fds. And with the new installation it is fds <filename>.fds, however I am getting errors when doing this (which I don't get in pyrosim): ERROR: Problem with REAC 1.
How can I solve this problem? I guess it is related to the newer version of fds?

Thanks in advance.

Edit: And the exact same simulation does run on the other computers, with the command prompt and 'fds6 xxxxxx.fds'.

**Comment by drjfloyd** [comment]
Without an input file there is not way we can definitively say what the cause is. Compare the inputs on your current REAC line to those in the user's manual of the version of fds installed on the machine where the run fails. Make sure all the inputs are available and correct for that version.

**Comment by rednasss** [comment]
I guess there is a mismatch between the fds versions currently used by Pyrosim and the FDS version I installed from here. Some changes need to be done to the .fds file when exporting it from Pyrosim. How can I fix this?

**Comment by drjfloyd** [comment]
Compare your inputs to the manual for the version you are using outside of Pyrosim. If you cannot determine the error after doing that, the only way we can help is for you to provide the simplest possible input file that still reproduces your error.

**Comment by rednasss** [comment]
I guess I found out already and it is caused because of the difference in versions. So I have to manually edit the .fds file because Pyrosim uses an older version of FDS. I guess I have to wait until the new Pyrosim update...
