### ISSUE TITLE
Discrepancy in pressure coefficient for Backward-facing step verification case

### ISSUE THREAD

**Issue by Evan-Tzanidis** [firemodels/fds#2983]
Hello all,

First things first: Version: FDS 6.1.2, SVN Revision No.: 20564

I have been trying to replicate the backward-facing step verification case and have tried a few different meshing strategies, which appear to predict noticeably different pressure coefficients.
My runs are the following:
1. Single uniform mesh, h/dx=5 - Included in Verification guide
   ![image](https://cloud.githubusercontent.com/assets/13354269/10663880/eb522fc2-78b6-11e5-8d41-4cb2f4b008e2.png)
2. Single stretched mesh, h/dx=5 to 10
   ![image](https://cloud.githubusercontent.com/assets/13354269/10663786/0b46570a-78b6-11e5-94f5-322c3b3b43aa.png)
3. Single uniform mesh, h/dx=10
   ![image](https://cloud.githubusercontent.com/assets/13354269/10663756/bca42f78-78b5-11e5-973b-527a8e9b0d27.png)
4. Multiple uniform meshes (12), h/dx=10 - Included in the Verification Guide
   ![image](https://cloud.githubusercontent.com/assets/13354269/10663778/ef2a7984-78b5-11e5-830d-08fc5175a166.png)
5. Multiple uniform meshes (6), h/dx=10
   ![image](https://cloud.githubusercontent.com/assets/13354269/10663800/255406e2-78b6-11e5-87e6-627b3da3e10d.png)
6. Multiple uniform meshes (12), h/dx=20 - Included in the Verification Guide
   ![image](https://cloud.githubusercontent.com/assets/13354269/10663902/0f86eeb4-78b7-11e5-9a76-d9319605bf53.png)

So, the cases above predict the following pressure coefficients:
![image](https://cloud.githubusercontent.com/assets/13354269/10664212/4d844a16-78b9-11e5-8bd9-6b1009b20bbf.png)

The graph basically indicates the following: 
- I succesfully replicated the predictions from the verification study (cases 1, 4 and 6)
- Cases 2, 3 and 5 appear to predict a greater pressure drop, which manifests itself as a lower pressure coefficient at the inlet.

I understand that the meshing strategy for 5 is not ideal, but I find it very odd that 2 and 3 do not produce similar results to 4. I cannot explain this discrepancy. Any suggestions?

Cheers,
Evan

**Comment by rmcdermo** [comment]
What kind of velocity errors are you seeing at the mesh and inlet
boundaries?

**Comment by rmcdermo** [comment]
By the way, these errors are given in the .out file.

**Comment by Evan-Tzanidis** [comment]
I reviewed the last few thousand timesteps and found the following max velocity errors:
1. 0.02m/s
2. 0.04m/s
3. 0.05m/s
4. 0.03m/s
5. 0.05m/s
6. 0.07m/s

They seem quite sensible considering that the freestream velocity is 7.72m/s.

**Comment by Evan-Tzanidis** [comment]
I have saved copies of the fds and out files here:
https://www.dropbox.com/sh/sqo393irjx1npdc/AADdvGrFJmOVbYRS91IuhWvOa?dl=0

I have renamed the files so that they align with the list above (the CHIDs are not the same though)

Thanks!
Evan

**Comment by rmcdermo** [comment]
Unfortunately, we cannot access Dropbox.  Please just append .txt to the
filenames and post to GitHub.

But I am not sure what we can do for now.  Crank down on the velocity
tolerance and up the max pressure iterations to see if that makes a
difference.  I think it will.

In the longer term, we have plans to implement a PFFT global pressure
solver that will solve this problem.  So, I don't expect us to be able to
do anything in the mean time.

**Comment by Evan-Tzanidis** [comment]
I have already tried changing the velocity tolerance and iteration limit for Case 3, but didn't make any noticeable difference in the bulk flow and pressure coefficient (other than lower velocity error and more iterations). I could try for the other ones, but the errors are already low and of similar magnitude to case 3. 

What worries me is that the input files of cases 3 and 4 are exactly the same, except for the fact that 4 is broken into multiple meshes. That makes me think that there is something wrong in the pressure solver. Furthermore, case 5 is in good agreement with case 3, possibly because velocity inlet and outlet are not separated by mesh interfaces.

I do not have write permission to this repository, so I created one of my own:
https://github.com/Evan-Tzanidis/Backward-Facing-Step/issues/1

(Not sure if this is the right way)

**Comment by rmcdermo** [comment]
Well, the write permissions on the GitHub repo is interesting.  That would explain a lot of problems we have been having with others trying post files and us not being able to reproduce the problem.  I will contact GitHub to see if there is a way around this.

I'll have a look to see if we can get cases 3 and 4 to match up.

**Comment by rmcdermo** [comment]
Evan,
I just made a change to the settings for the repo.  See if it now lets you add a file.  Thanks.

**Comment by Evan-Tzanidis** [comment]
Still doesn't let me.
The following message pops up:

Attaching documents requires write permission to this repository.  Try again with a PNG, GIF, or JPG.

I think it only allows contributors.

**Comment by rmcdermo** [comment]
Try just appending .png to your text file.

**Comment by Evan-Tzanidis** [comment]
It works, just right click on any of the following and save as XXXX.fds or XXXX.out

Case 1 FDS: ![backward_facing_step_1 fds](https://cloud.githubusercontent.com/assets/13354269/10673034/9c37ab80-78eb-11e5-8ae0-d461efc8a055.png)
Case 1 OUT: ![backward_facing_step_1 out](https://cloud.githubusercontent.com/assets/13354269/10673035/9c3aad26-78eb-11e5-9ece-a613b0b967ea.png)
Case 2 FDS: ![backward_facing_step_2 fds](https://cloud.githubusercontent.com/assets/13354269/10673036/9c3aeff2-78eb-11e5-94df-24c599541781.png)
Case 2 OUT: ![backward_facing_step_2 out](https://cloud.githubusercontent.com/assets/13354269/10673039/9c3dce7a-78eb-11e5-9d3b-9946aba35101.png)
Case 3 FDS: ![backward_facing_step_3 fds](https://cloud.githubusercontent.com/assets/13354269/10673037/9c3ba8d4-78eb-11e5-8894-43730d103518.png)
Case 3 OUT: ![backward_facing_step_3 out](https://cloud.githubusercontent.com/assets/13354269/10673038/9c3c0482-78eb-11e5-9faf-587f3c289c4e.png)
Case 4 FDS: ![backward_facing_step_4 fds](https://cloud.githubusercontent.com/assets/13354269/10673041/9c525e30-78eb-11e5-9390-9b57afae4f58.png)
Case 4 OUT: ![backward_facing_step_4 out](https://cloud.githubusercontent.com/assets/13354269/10673044/9c5abe0e-78eb-11e5-9f9b-a742011508f1.png)
Case 5 FDS: ![backward_facing_step_5 fds](https://cloud.githubusercontent.com/assets/13354269/10673042/9c5762b8-78eb-11e5-8389-6d8f570052b6.png)
Case 5 OUT: ![backward_facing_step_5 out](https://cloud.githubusercontent.com/assets/13354269/10673040/9c5173da-78eb-11e5-8186-9fe99f45c626.png)
Case 6 FDS: ![backward_facing_step_6 fds](https://cloud.githubusercontent.com/assets/13354269/10673043/9c591568-78eb-11e5-8ead-f88e08662fa1.png)

I only noticed two issues, it is not possible to upload files over 10MB and the names are corrupted when I add the files.

**Comment by rmcdermo** [comment]
OK, thanks for testing this.  You are 2 on my to-do list.  Hopefully get to this today.

**Comment by Evan-Tzanidis** [comment]
ok, thank you!

**Comment by lu-kas** [comment]
Randy,

that's interesting:

"In the longer term, we have plans to implement a PFFT global pressure
solver that will solve this problem."

I thought that external libraries are not meant to be used by FDS. Did this philosophy changed or is changing? 

Best,
Lukas

**Comment by rmcdermo** [comment]
Lukas,

If we cannot get permission to compile the PFFT source together with FDS,
then we will develop our own (at least that is the current plan).

Best,

Randy

**Comment by Evan-Tzanidis** [comment]
Hello Randy,

Did you have a chance to look at the above?

It seems like changing multi-mesh strategy significantly affects the predicted pressure drop.
Despite case 4 being a better meshing approach (reduced mesh boundaries, almost square grids etc.), case 5 is in better agreement with the single-mesh scenario having the same cell size (case 3).

So, I am wondering, are current meshing practices ideal for simulations with highly one-directional flows (i.e. tunnels)?

Does the introduction of multiple mesh boundaries between the inlet and outlet cause a discrepancy in the pressure field?

Regards,
Evan

**Comment by mcgratta** [comment]
I have not been following this thread closely, but I would not recommend that you put a mesh interface right at the trailing edge of the step. Tangential velocity boundary conditions are tricky at sharp edges, and it is worse when there is a mesh boundary there.

**Comment by rmcdermo** [comment]
The official answer is always to monitor the velocity error in the .out
file.  As mentioned in previous comments, we are planning to implement the
PFFT this year.  This will solve these problems to a large degree.
