### ISSUE TITLE
Smooth Normals in Smokeview

### ISSUE THREAD

**Issue by RIO4FDS** [firemodels/fds#2994]
Recently, I lost the ability of turn off smooth normals for IBM in smokeview.
I use to find it at Show/Hide>Geometry>Immersed Solids>Smooth normal, but I can't find it anymore.
I tried different cases and different machines. I am using the version 6.3.0 of smokeview from the bundle downloaded from github (http://firemodels.github.io/fds-smv/downloads.html - Win64)
In the attached pictures, I am visualizing tetra_1 case (\Verification\Immersed_Boundary_Method).

Thanks, Julio

![smooth_issue_1](https://cloud.githubusercontent.com/assets/12700159/10730668/7dbcce16-7bd8-11e5-9e53-c28501bce4f2.jpg)
![smooth_issue_2](https://cloud.githubusercontent.com/assets/12700159/10730667/7dbbd1e6-7bd8-11e5-9483-5f90b87f3be5.jpg)

**Comment by gforney** [comment]
I'll take a look at it.

**Comment by gforney** [comment]
the smooth normal option was only in "test" versions of smokeview.  I added it and some other geometry visualization options back to all versions.  Try windows smokeview located here
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

**Comment by RIO4FDS** [comment]
It is working! Thanks
