### ISSUE TITLE
Pressure fluctuation caused by fire in seperate ZONE/room

### ISSUE THREAD

**Issue by chulann** [firemodels/fds#3002]
Hi,
I've noticed a large pressure fluctuation in a small, DUCT ventilated pressure zone which only occurs when there is a fire in a separate "room" or  ZONE. The ZONE with the fire is separated from the ventilated ZONE with a 2-cell thick OBST.

I have created a simplified test case. The small lobby has 2 fans - 1 at low level supplying 0.25m^3/sec in and one at high level extracting 0.5m^3/sec with a MAX_PRESSURE of 25 Pa. A fire is placed in a separate mesh adjacent to this lobby. Originaly there was doors opening between them but they have been removed to simplify. If the case is run without the fire, the pressure in the lobby remains constant. With the fire, it fluctuates +/- 1,000Pa after between 60 and 80 seconds of runtime. The PRES line was added in an attempt to smooth out the pressure solver and it has also been run previously with the inlet air to the fire being supplied by a DUCT rather than a SURF_ID='OPEN'

The test case is available here: http://killminus9.net/pressure_zone_problem.fds

Everything from line 43 on is monitoring.

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
Jason, I simplified the case:

```
&HEAD CHID='pressure_zone_problem', TITLE='Test model to demonstrate large pressure in Lobby pressure zone (which does not occur if there is no fire in Room fire zone)' /
&TIME T_END=100.0 /

&MESH IJK=42,15,24, XB=3.6,7.8,2.8,4.3,3.4,5.8/

&ZONE XB=3.6,5.8,2.8,4.3,3.4,5.8 /

&REAC FUEL='METHANE' /

&OBST XB=5.6,5.8,2.8,4.3,3.4,5.8 /

&SURF ID='Fire', COLOR='RED', HRRPUA=250.0, TAU_Q=-150.0/
&VENT ID='VT_Apart_In', SURF_ID='OPEN', XB=7.8,7.8,2.9,4.2,3.6,4.1/
&VENT SURF_ID='Fire', XB=6.0,7.0,3.0,4.0,3.4,3.4/    <------ If you comment this line, the case will run, at least to T_END.

&HVAC ID='Duct_LobbyLow', TYPE_ID='DUCT', AREA=0.5, PERIMETER=3.0, VOLUME_FLOW=0.25, LOSS=6.0,6.0, NODE_ID='Node_LobbyLowX','Node_LobbyLow', ROUGHNESS=0.001, LENGTH=10.0 /
&HVAC ID='Node_LobbyLow', TYPE_ID='NODE', DUCT_ID='Duct_LobbyLow', VENT_ID='VT_Lobby_Low' /
&HVAC ID='Node_LobbyLowX', TYPE_ID='NODE', DUCT_ID='Duct_LobbyLow', AMBIENT=.TRUE., XYZ=4.8,0.5,3.6 /
&VENT ID='VT_Lobby_Low', SURF_ID='HVAC', XB=3.9,5.4,2.8,2.8,3.6,4.1, COLOR='GREEN' /

&HVAC ID='Duct_LobbyHigh', TYPE_ID='DUCT', AREA=0.5, PERIMETER=3.0, FAN_ID='Fan_LobbyExtract', LOSS=5.0,5.0, NODE_ID='Node_LobbyHigh','Node_LobbyHighX', ROUGHNESS=0.001, LENGTH=10.0 /
&HVAC ID='Fan_LobbyExtract', TYPE_ID='FAN', MAX_FLOW=0.5, MAX_PRESSURE=25.0 /
&HVAC ID='Node_LobbyHigh', TYPE_ID='NODE', DUCT_ID='Duct_LobbyHigh', VENT_ID='VT_Lobby_High' /
&HVAC ID='Node_LobbyHighX', TYPE_ID='NODE', DUCT_ID='Duct_LobbyHigh', AMBIENT=.TRUE., XYZ=4.8,0.5,5.1 /
&VENT ID='VT_Lobby_High', SURF_ID='HVAC', XB=3.9,5.4,2.8,2.8,5.1,5.7, COLOR='BLUE' /

&SLCF QUANTITY='PRESSURE', PBY=3.5, VECTOR=.TRUE. /
&SLCF QUANTITY='PRESSURE', PBX=5.0, VECTOR=.TRUE. /

&DEVC QUANTITY='DUCT VOLUME FLOW',DUCT_ID='Duct_LobbyLow',ID='Q_DLL'/
&DEVC QUANTITY='DUCT VOLUME FLOW',DUCT_ID='Duct_LobbyHigh',ID='Q_DLH'/
&DEVC QUANTITY='PRESSURE', XYZ=4.7,3.5,5.5, ID='P_LH' /

&TAIL /
```

The fire room and the pressurized space are not connected. At first, I thought this might be something related to the multi-meshes, but that is not the case. In the ODE solver, what would "connect" these two spaces?

**Comment by drjfloyd** [comment]
The HVAC solver shouldn't be seeing the fire at all. Something is in error somewhere. I'll look into it.

**Comment by drjfloyd** [comment]
I split the mesh into two meshes on either side of the wall (e.g. meshes have a gap between them where there used to be the two cell thick wall). As far as I can tell the HVAC solver is picking up data from the correct mesh and zone.

There is a difference, however, between the two cases -- the timestep. With no fire, the time step is driven by the HVAC flow which is ~0.25 m/s.  With the fire, the time step is driven by the fire plume which is >> 0.25 m/s. If I hack HVAC.F90 and fix the timestep to 1 s both with and without fire give the same stable results. I may need to rethink how I am handling the time integration in the hvac routine.

**Comment by mcgratta** [comment]
The original case was two meshes, with the two cell thick wall completely within the smaller room. Time step makes sense -- I thought the fire was a red herring. Should we make the HVAC time step independent of the FDS time step? Seems like the two need not be correlated at all.

**Comment by drjfloyd** [comment]
That might be one solution. Have to see what makes sense and what works.

**Comment by rmcdermo** [comment]
Jason,

Is the update equation in question Eq. (10.4) in the tech guide?

**Comment by drjfloyd** [comment]
Randy,

Yes, but 10.6 has some of the terms expanded

**Comment by chulann** [comment]
That's quite unusual isn't it - that you introduce instability with smaller time-steps? Any suggestions on a workaround? I suppose increasing the cell size would also increase the time-step. Jason, if you still have the compiled binaries with the hacked HVAC.F90, I wouldn't mind giving them a try here.

Thanks for your help,
Cian

**Comment by drjfloyd** [comment]
Cian,

Try decreasing the duct length. Since you were using ROUGHNESS, increase that by the factor you reduce the length to preserve total loss (loss is proportional to roughness*length).

**Comment by drjfloyd** [comment]
I've added the keyword HVAC_DT to MISC. If set, it will use the value specified in the HVAC solver rather than the FDS timestep. This can dampen oscillations in flow/pressure resulting from the fact that the HVAC pressure solution and the FDS pressure solution are not fully coupled. The downside is one will lose some time resolution for actual transient flows in ducts (the larger the value, the closer the solver will be to computing a steady-state solution at each timestep).
