### ISSUE TITLE
Error in firebot, Git-r1-234-g4bf44c4

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3006]
Not sure if this is you or Randy. I am running firebot locally.

```
Species/methane_flame_simple_2.err:forrtl: severe (408): fort: (3): Subscript #1 of the array SPECIES has value 0 which is less than the lower bound of 1
Species/methane_flame_simple_2.err-
Species/methane_flame_simple_2.err-Image              PC                Routine            Line        Source
Species/methane_flame_simple_2.err-fds_mpi_intel_lin  000000000265BD66  Unknown               Unknown  Unknown
Species/methane_flame_simple_2.err-fds_mpi_intel_lin  0000000001A9B901  read_input_mp_pro        3868  read.f90
Species/methane_flame_simple_2.err-fds_mpi_intel_lin  00000000019E550C  read_input_mp_rea         124  read.f90
Species/methane_flame_simple_2.err-fds_mpi_intel_lin  0000000002206B1A  MAIN__                    107  main.f90
Species/methane_flame_simple_2.err-fds_mpi_intel_lin  000000000040931E  Unknown               Unknown  Unknown
Species/methane_flame_simple_2.err-libc.so.6          000000306421D994  Unknown               Unknown  Unknown
Species/methane_flame_simple_2.err-fds_mpi_intel_lin  0000000000409239  Unknown               Unknown  Unknown
```

**Comment by drjfloyd** [comment]
While fixing this I think we have a hole in our logic.

We generate kappa using the species%radcal_id weighted by the species mixture mass fractions. For simple chemistry if the the fuel doesn't have a default radcal_id we set species(fuel_index)%radcal_id=fuel_radcal_id. However, fuel_index is only defined if there fuel is a single species. If with simple chemistry the user specifies more than subspecies in the fuel mixture (like in methane_flame_simple_2, fuel index is not defined. If the fuel component(s) have no predefined radcal_id, then none would be set for the fuel.

Do we want to change this and instead check to see if each of the fuel subspecies is listed and if unlisted assign FUEL_RADCAL_ID to RADCAL_ID where it is currently null?

**Comment by mcgratta** [comment]
Do we have any choice? Seems to me the only thing to do.

**Comment by drjfloyd** [comment]
Fixed in https://github.com/firemodels/fds-smv/commit/3ff209ec2ed790958bfdf2e9189df9abb26a97ae
