### ISSUE TITLE
problem with levelset cases

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#3020]
I've noticed for a while that smokebot is taking 2 hours instead of 30 minutes to complete.  This is occurring because two levelset cases are taking an hour instead of 30 seconds to finish. One of these cases is Verification/WUI/BT10m_2x2km_LS.fds .  I used 'git bisect' to find that the problem started on 10/5 with revision hash f84b848a "FDS source: Major change to simplify time step procedure".  My hunch is that FDS is running a full cfd computationrather than only a levelset (ie ode) computation.

**Comment by gforney** [comment]
think I found the problem.  In main.f90 don't think IF(WFDS_BNDRYFUEL) should surround the code below.  These computations need to be done if VEG_LEVEL_SET_UNCOUPLED  and/or VEG_LEVEL_SET_COUPLED are .TRUE.  and this is where the levelset computations in the BT... case are being done.  Removing it fixed the problem - don't think there are any side effects.  I'll commit the change.  Let me know if you think it should be fixed in a different way.

IF (WFDS_BNDRYFUEL) THEN
   IF (VEG_LEVEL_SET_UNCOUPLED .OR. VEG_LEVEL_SET_COUPLED) CALL INITIALIZE_LEVEL_SET_FIRESPREAD(1)
   IF (VEG_LEVEL_SET_UNCOUPLED) THEN
      CALL LEVEL_SET_FIRESPREAD(T,DT,1)
      STOP_STATUS = LEVELSET_STOP
      CALL STOP_CHECK(1)
   ENDIF
ENDIF

**Comment by mcgratta** [comment]
I am not familiar with this feature. Ruddy or Randy?

**Comment by gforney** [comment]
think I fixed it.  There was an IF statement surrounding the levelset code
that I think shouldn't have been there - causing it not to be executed.

got a weird message form gmail in the message you just sent:

"Be careful with this message.  It contains content that is typically used
to steal personal information"

On Sun, Nov 1, 2015 at 12:55 PM, Kevin McGrattan notifications@github.com
wrote:

> I am not familiar with this feature. Ruddy or Randy?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Glenn Forney

**Comment by gforney** [comment]
think this is fixed.  am closing issue
