### ISSUE TITLE
Install issue about Mac OS

### ISSUE THREAD

**Issue by JimJimlin** [firemodels/fds#3049]
Hello,

When I install FDS first time, after installation complete terminal cannot find FDS.

The reason why is I use the z shell to replace bash. Therefore, maybe can  write this reminder message in Mac Installation notes.

**Comment by gforney** [comment]
the linux and osx installers assume you are using the bash shell.  if you
are using some other shell you will need to define the path variable

On Tue, Nov 3, 2015 at 10:32 PM, JimJimlin notifications@github.com wrote:

> Hello,
> 
> When I install FDS first time, after installation complete terminal cannot
> find FDS.
> 
> The reason why is I use the z shell to replace bash. Therefore, maybe can
> write this reminder message in Mac Installation notes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3049.

## 

Glenn Forney
