### ISSUE TITLE
documentation: missing figures in FDS_User_Guide.tex

### ISSUE THREAD

**Issue by mimooh** [firemodels/fds#3066]
Hi, I am trying to compile the FDS_User_Guide.tex into html. But the
SCRIPT_FIGURES directory is empty. Is there a chance to have the figures
in the github repo?

! LaTeX Error: File `SCRIPT_FIGURES/openmp_timing_benchmarks' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.486 ...{SCRIPT_FIGURES/openmp_timing_benchmarks}

**Comment by drjfloyd** [comment]
We do not archive figures from the Verification suite as they are generated in the nightly builds, you can make the figures yourself following the directions in the wiki:

https://github.com/firemodels/fds-smv/wiki/FDS-Verification-Process

**Comment by mcgratta** [comment]
It's bad practice to commit binary files to a version control repository. The figures for the guides are generated with Matlab scripts after the verification cases have been run. The verification process is described here

https://github.com/firemodels/fds-smv/wiki/FDS-Verification-Process

**Comment by mcgratta** [comment]
Ah, you beat me to it, Dr Floyd!

**Comment by mimooh** [comment]
Wow, quick two replies. Thank you very much! I'll try to generate the figures as you suggest.

**Comment by mcgratta** [comment]
I would be very interested if you can do it. This is a very important part of our verification process, and we have tried to emphasize to students working with FDS that running these cases is a vital part of working with the source code. However, for many, it is too difficult to follow. So let us know if you can do it.

**Comment by mimooh** [comment]
Sounds scary :) I will have a look and let you know if/where there were
difficulties. 

## 

Karol Kreński

**Comment by rmcdermo** [comment]
Note I just made a minor edit to the wiki that will help... the run scripts
have been moved to the Verification/scripts/ folder.

**Comment by mimooh** [comment]
> I would be very interested if you can do it. This is a very important part
> of our verification process, and we have tried to emphasize to students
> This is my progress and the difficulties:
1. Cannot compile smv on modern ubuntu:
   /usr/bin/ld: cannot find -lglui
   /usr/bin/ld: cannot find -lgd

seems like libglui-dev is not available anymore in ubuntu repos. I
succesfully compiled fds with gcc and intel compiler, but installed the
smv.deb since I didn't manage to compile the smv.
1. This qsub subsystem is new to me. I installed torque client/server on
   ubutnu, but it seems very complicated so I preffered no queueing, which
   resulted in:
   $ ./Run_FDS_Cases.sh -q none
   ../../Utilities/Scripts/qfds.sh: line 437:
   /home/mimooh/fds-smv/Verification/scripts/../../Utilities/background/intel_linux_32/background:
   No such file or directory
   ../../Utilities/Scripts/qfds.sh: line 437:
   /home/mimooh/fds-smv/Verification/scripts/../../Utilities/background/intel_linux_32/background:
   No such file or directory
   ../../Utilities/Scripts/qfds.sh: line 437:
   /home/mimooh/fds-smv/Verification/scripts/../../Utilities/background/intel_linux_32/background:
   No such file or directory

Maybe it's just me, but based on
https://github.com/firemodels/fds-smv/wiki/FDS-Verification-Process
I first time read:
./Run_FDS_Cases.sh -q
instead of
./Run_FDS_Cases.sh -q none

Resuming, can I have some suggestion on how to complete point 2.?

Regards,
Karol

**Comment by gforney** [comment]
There are scripts in the repo for building libraries used by smokeview.
Look in SMV/Build/LIBS

**Comment by gforney** [comment]
You need to build background. There is a script . look in
Utilities/background/intel_linux_32

**Comment by mimooh** [comment]
> You need to build background. There is a script . look in
> Utilities/background/intel_linux_32
> Works :) I suggest you add it to the wiki. 

The wiki says:
(Linux/Unix) Open the text file called Run_FDS_Cases.sh and make sure
that the various folders and scripts exist.

I suggest mentioning the variables also (intel vs gnu compiler). 

# 

Just make sure the 32-bit vs 64-bit for compiling background is really
correct in Run_FDS_Cases.sh:

size=_64
PLATFORM=linux$size
PLATFORM2=linux_32
export BACKGROUND=$SVNROOT/Utilities/background/intel_$PLATFORM2/background

For me the 32-bit had issues and this change helped:
PLATFORM2=linux_64

## 

Karol Kreński

**Comment by mcgratta** [comment]
Thanks for debugging this process. Did you manage to compile the User's Guide?

**Comment by mimooh** [comment]
> Thanks for debugging this process. Did you manage to compile the User's Guide?
> Not yet. I will let you know. Thanks for your support.

## 

Karol Kreński

**Comment by mcgratta** [comment]
What is the problem?

**Comment by gforney** [comment]
Fyi: I added a note to the fds verification wiki that says if you use the
"none" queue you need to install the fds/smokeview bundle. This bundle
includes the utility "background" used by the Run_FDS verification script (
you don't need to build background if you install FDS)

**Comment by mimooh** [comment]
> What is the problem?
> I just need some more time, because I've got other things to do. But
> within a week or a few I should be done. My final goal is to build html
> from FDS latex manual.

## 

Karol Kreński

**Comment by mcgratta** [comment]
OK, no hurry. We're just trying to make this process easier.

**Comment by mimooh** [comment]
A couple of new comments:
1. https://github.com/firemodels/fds-smv/wiki/FDS-Verification-Process
   > Running the Cases
   Unless something was changed in the build process I would still not
   figure it out from the docs that there's utilities/background that I
   need to take care of.

# 
1. Wrong:
   cd to the Verification folder of the Repository.
   Type ./Make_FDS_Pictures.sh (Linux/Unix)

it should read:
cd to the Verification/scripts folder of the Repository.

or just not change the folder at all, since I was in that folder
already (Run_FDS_Cases.sh).

# 
1. Seems like you expect me to have built the smokeview? Which
   contradicts: "If you cannot compile Smokeview because you lack a C
   compiler, install the latest version of Smokeview onto your machine."

duch:scripts$ ./Make_FDS_Pictures.sh
erasing SCRIPT_FIGURES png files
setting up graphics environment

--- generating images for: random_meshes.smv
/home/mimooh/fds-smv/Verification/scripts/../../SMV/Build/intel_linux_64/smokeview_linux_64
-bindir /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/
-runscript random_meshes
/home/mimooh/fds-smv/Verification/scripts/../../Utilities/Scripts/runsmv.sh:
line 70: /home/mimooh/fds-smv/Verification/scripts/../../SMV/Build/intel_linux_64/smokeview_linux_64:
No such file or directory

BTW, in my case the reason for not building SMV is not lacking the C
compiler, but openGL devel environment. Perhaps the previous comment
from our discussion:

"There are scripts in the repo for building libraries used by smokeview.
Look in SMV/Build/LIBS"

would be appropriate in the wiki.

Regards,
Karol

**Comment by rmcdermo** [comment]
OK, I fixed Point 2 above.

**Comment by mimooh** [comment]
Any suggestion for my ./Make_FDS_Pictures.sh problem? On one hand the
wiki says I don't need to build smv, but on the other
./Make_FDS_Pictures.sh tries to use the compiled
/home/mimooh/fds-smv/Verification/scripts/../../SMV/Build/intel_linux_64/smokeview_linux_64.
I have smokeview installed as a .deb file.

I tried settting
SMV=smokeview
but the result is:

# 

--- generating images for: ribbed_channel_80.smv
smokeview -bindir /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/ -runscript ribbed_channel_80
GLUT: Fatal Error in smokeview: could not open display: :1000

--- generating images for: objects_static.smv
smokeview -bindir /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/ -runscript objects_static
GLUT: Fatal Error in smokeview: could not open display: :1000

--- generating images for: objects_dynamic.smv
smokeview -bindir /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/ -runscript objects_dynamic
GLUT: Fatal Error in smokeview: could not open display: :1000
shutting down graphics environment
FDS pictures created.

# 
- I have no idea how fatal is the GLUT error for producing the pictures.
- I have X11 fowarding to this host, can start x11 apps, so don't \* understand the display: :1000 problem
- find -cmin -2 proves no FDS pictures are created in my fds-smv tree, which contradicts the "FDS pictures created" message

Any suggestion for my next move?

**Comment by gforney** [comment]
X11 forwarding is not enough because smokeview uses opengl.  you need to be
at a "graphics" console.  Assuming you are using a PC to login in to your
Linux computer, you could use something like NX client to put a graphics
console onto your local computer

On Tue, Nov 24, 2015 at 10:09 AM, mimooh notifications@github.com wrote:

> Any suggestion for my ./Make_FDS_Pictures.sh problem? On one hand the
> wiki says I don't need to build smv, but on the other
> ./Make_FDS_Pictures.sh tries to use the compiled
> 
> /home/mimooh/fds-smv/Verification/scripts/../../SMV/Build/intel_linux_64/smokeview_linux_64.
> I have smokeview installed as a .deb file.
> 
> I tried settting
> SMV=smokeview
> but the result is:
> 
> --- generating images for: ribbed_channel_80.smv
> smokeview -bindir
> /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/ -runscript
> ribbed_channel_80
> GLUT: Fatal Error in smokeview: could not open display: :1000
> 
> --- generating images for: objects_static.smv
> smokeview -bindir
> /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/ -runscript
> objects_static
> GLUT: Fatal Error in smokeview: could not open display: :1000
> 
> --- generating images for: objects_dynamic.smv
> smokeview -bindir
> /home/mimooh/fds-smv/Verification/scripts/../../SMV/for_bundle/ -runscript
> objects_dynamic
> GLUT: Fatal Error in smokeview: could not open display: :1000
> shutting down graphics environment
> FDS pictures created.
> - I have no idea how fatal is the GLUT error for producing the
>   pictures.
> - I have X11 fowarding to this host, can start x11 apps, so don't *
>   understand the display: :1000 problem
> - find -cmin -2 proves no FDS pictures are created in my fds-smv tree,
>   which contradicts the "FDS pictures created" message
> 
> Any suggestion for my next move?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3066#issuecomment-159296230
> .

## 

Glenn Forney

**Comment by gforney** [comment]
try the following
1.  cd into Utilities/Scripts
2.  copy smokeview.sh, startXserver.sh and stopXserver.sh to a directory in your path
3. cd to Verification/Visualization
4.  run the case plume5c.fds
5.  type: smokeview.sh plume5c

if everything is working you should see output from smokeview.

the Make_FDS_Pictures.sh script uses startXserver.sh and stopXserver.sh to start and stop a virtual X environment.  In order for this to work you need to have Xvfb and glut installed.  To see if you do, at a command line type (this is assuming you have a redhat based linux installed )

rpm -qa | grep Xvfb
rpm -aq | grep glut

On our system I see

[gforney@blaze Scripts]$ rpm -qa | grep Xvfb
xorg-x11-server-Xvfb-1.1.1-48.76.el5

[gforney@blaze Scripts]$ rpm -qa | grep glut
freeglut-devel-2.4.0-7.1.el5
freeglut-2.4.0-7.1.el5
freeglut-2.4.0-7.1.el5
freeglut-devel-2.4.0-7.1.el5

**Comment by mimooh** [comment]
I bet I saw my friend launching smokeview window over x11 forwarding. I
am familiar with NX (in fact the opensource fork named x2go), but seems
like my ubuntu is too old to install x2go. Long way I need to go to have
these figures for the manual... But I am still not giving up :)

## 

Karol Kreński

> X11 forwarding is not enough because smokeview uses opengl.  you need to be
> at a "graphics" console.  Assuming you are using a PC to login in to your
> Linux computer, you could use something like NX client to put a graphics
> console onto your local computer
>

**Comment by mimooh** [comment]
apt-get install xvfb 
solves the issue.

NX / x2go proves to be not different from ssh -X server, when it comes
to smokeview openGL remote display.

find . -cmin -3
reports that I have new files now:
(...)
./Manuals/SMV_User_Guide/SCRIPT_FIGURES/sensor.png
./Manuals/SMV_User_Guide/SCRIPT_FIGURES/heatdetector_inact.png
./Manuals/SMV_User_Guide/SCRIPT_FIGURES/sensorplain.png
(...)

What your scripts lack in my opinion is a place for defining the basic
variables. You assume and hardcode some x64-intel-variant-builds,
but there should be place for:

SMV=/usr/bin/smokeview
FDS=FDS_Compilation/${OPENMP}intel_$PLATFORM$DEBUG/fds_${OPENMP}intel_$PLATFORM$DEBUG

## 

Karol Kreński

**Comment by gforney** [comment]
Thanks. I'll add some variables as you suggest.

**Comment by mimooh** [comment]
I succesfully compiled FDS user manual from latex to pdf.
- When there's no latex environment at all within a second
  I get the happy, but totally untrue message: FDS User Guide built
  successfully! (cd to Manuals/FDS_Verification_Guide and at the command
  prompt type: ./make_guide.sh)
- May be of use for people trying to compile: the latex environment
  should include: 
  texlive-latex-base texlive-latex-extra texlive-science texlive-fonts-*
- Common guys, just include these few images in git repo. They are just
  few MegaBytes, not that much. There are projects, like games, which
  include plenty of graphics, so it's not that unusual to store graphics.
  For the users, creating these graphics themselves is not trivial.

Thanks for all your help and support guys! :) Now I can finally get to
my work: compile html from latex.

**Comment by gforney** [comment]
There are over 3000 images generated by matlab and smokeview contained in the various FDS guides.  These images take up about 30MB (15MB after compression).  Because they are generated every night by our v&v scripting process, it is not practical to include them in the repository.

See if you can build the FDS user guide using the FDS figures contained in the tar.gz file found here:
https://drive.google.com/folderview?id=0B_wB1pJL2bFQUlJwMmNfaHlqME0&usp=sharing

untar this file within the Manuals/FDS_User_Guide/SCRIPT_FIGURES directory

**Comment by mimooh** [comment]
> See if you can build the FDS user guide using the FDS figures contained in the tar.gz file found here:
> https://drive.google.com/folderview?id=0B_wB1pJL2bFQUlJwMmNfaHlqME0&usp=sharing
> FDS User Guide built successfully!

Thanks a lot! :)

## 

Karol Kreński

**Comment by mcgratta** [comment]
The reason for generating the pictures is not just to save space in the repository. In fact, that is the least important reason. The most important reason is that what you have just done (with some difficulty, sorry) is essentially our QA (Quality Assurance) process. We make changes to FDS and Smokeview everyday, and without this process, bugs that we might create are not detected for days or weeks, at which point it becomes a nightmare to debug.
