### ISSUE TITLE
write to READONLY for _cpu

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#3076]
Running an MPI case on windows using the current source.  At the end of time stepping I get the error below.

forrtl: severe (47): write to READONLY file, unit 8, file C:\Projects\FDS_Devel\
6.0a\test\base_station_cpu.csv
Image              PC                Routine            Line        Source

fds_mpi_win_64.ex  000000013FCED7D2  Unknown               Unknown  Unknown
fds_mpi_win_64.ex  000000013FCB6C47  Unknown               Unknown  Unknown
fds_mpi_win_64.ex  0000000140464BB2  Unknown               Unknown  Unknown
fds_mpi_win_64.ex  000000013FD7AC27  MAIN__                    787  main.f90
fds_mpi_win_64.ex  000000013FD7061E  Unknown               Unknown  Unknown
fds_mpi_win_64.ex  000000013FD4A6DF  Unknown               Unknown  Unknown
kernel32.dll       0000000077925A4D  Unknown               Unknown  Unknown
ntdll.dll          0000000077A5B831  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
Is this a multiple mesh case? And multiple MPI processes?

**Comment by drjfloyd** [comment]
Yes.  Attached is the case (just the meshes and a short run time)

[multi.fds.txt](https://github.com/firemodels/fds-smv/files/29121/multi.fds.txt)

**Comment by mcgratta** [comment]
I think I fixed it. Try it now. Each MPI process is to open the file in sequence. Trouble was, I was not closing the file after each process wrote to it. Linux doesn't care if the file is opened by multiple processes, but Windows does.

**Comment by drjfloyd** [comment]
works.
