### ISSUE TITLE
Run FDS 6.3 in parallel 

### ISSUE THREAD

**Issue by kaveh1381** [firemodels/fds#3093]
Hi There,

I have a PC for modeling (with 12 CPUs\* core i7), but when we run any FDS modelings, all meshes are assigned in only one single processor(#0). Recently I am running a 6 meshes model which takes much days!

As it is on a single computer, we can not cluster it. it is FDS 6.3, how can I run this in parallel? do I need any other software?what shall I type on command prompt exactly?

Thanks

**Comment by rmcdermo** [comment]
By CPUs I assume you mean cores.  In this case, you can only run OpenMP (shared memory) parallel jobs.  For this you need to set your number of threads (I think this is done automatically in Windows).  In your screen output, does it not say how many OpenMP threads are enabled?

In short, if you do not have a cluster of some kind you cannot run a distributed memory (MPI) parallel job.  If you have access to a cluster, follow the wiki instructions here:

https://github.com/firemodels/fds-smv/wiki/Installing-and-Running-FDS-on-a-Windows-PC

**Comment by drjfloyd** [comment]
If you have a multi-core PC you can run an mpi job.  You must run using mpiexec per the instructions in the user's guide.

**Comment by kaveh1381** [comment]
In the user's guide, only the mpiexec instruction used for a network and two hosts PC! Should I only chamge hosts number, or sth else?

**Comment by drjfloyd** [comment]
We need to modify the discussion in the guide.  On a single machine with multiple cores you can do:

mpiexec -n #cores fds job_name.fds

**Comment by drjfloyd** [comment]
It should be added that as a default each MPI process will use 4 OpenMP threads. So you should set OMP_NUM_THREADS so that # MPI processes x OMP_NUM_THREADS <= number of cores on your machine.

**Comment by drjfloyd** [comment]
Made some changes to the User's Guide to reflect my last two comments.
