### ISSUE TITLE
MPI environment clash with other software

### ISSUE THREAD

**Issue by cfaurie** [firemodels/fds#3114]
Hi there, 

Some while ago, there were a conversation about clashes between MPI services used by different software on a single computer, which stopped mpiexec to run properly and created the error attached. At the time, I had the issue with Pyrosim old SMPD and FDS new HYDRA communicator. Disabling the SMPD service that Pyrosim install did the trick for me. 

https://groups.google.com/forum/#!topic/fds-smv/4xJqYiFjkSQ

I recently ran into the same issue when I installed a trial version of a commercial CFD software (Starccm not to mention it). I didn't see any obvious services or environment variables that I could modify/disable, so I was wondering if anyone had the same issue and/or any idea on how to solve the problem. 

Thanks,
Coraline

![untitled](https://cloud.githubusercontent.com/assets/13315351/11126473/173aee92-8967-11e5-8b52-32c6d2783b7d.png)

**Comment by rmcdermo** [comment]
Caroline,
Did you mean to submit this to the [Discussion Forum](https://groups.google.com/forum/?fromgroups#!forum/fds-smv)?  Does not seem like an FDS issue, though I am sure Kevin and Jason would be happy to provide advice.  You may get more hits on the forum.

**Comment by mcgratta** [comment]
Mixing different versions of the MPI scheduler is a problem. I do not know how to solve it. Maybe try reinstalling FDS (no need to reboot), so that the FDS MPI scheduler regains precedence.

**Comment by cfaurie** [comment]
Hi Randy, 

I actually hesitated. I don’t really know whose ‘issue’ it is, Star or FDS. Since I know Pyrosim/FDS was an issue, and I also had an issue between ANSYS CFX and FDS (I had to change the environment variable MPI_ROOT according to which software I was using), I was wondering if anyone else had the problem. Windows is a big mess. But you’re right, I’ll post this on the google group. 

Hi Kevin, 

I tried every combination on uninstall/reinstall of FDS, star and pyrosim, mpiexec only worked again when I uninstalled star completely and reboot my computer.

**Comment by mcgratta** [comment]
Windows may not be the best OS for all these MPI implementations. We use Intel MPI to compile FDS for Windows, and we include 3 or 4 redistributable files in the same bin directory as FDS. You can do a 

```
where fds
```

and 

```
where mpiexec
```

to make sure that you are using the executables that we distribute. Then do a

```
hydra_service -status
```

to make sure that the hydra daemon is running. I cannot think of anything else that you can do to check on the FDS installation.

**Comment by gforney** [comment]
its a hack, but one thing you could do to make sure you are running the right mpiexec is to rename the mpiexe located in the FDS bin directory it to say mpiexec_fds .  then when you run a parallel version of fds use mpiexec_fds.  try this and see if it works for you.  let us know what happens

**Comment by cfaurie** [comment]
Alright, sorry it took me a while to come back to this, and thank you all for your help!

'where fds' and 'where mpiexec' both link to FDS6\bin, so that's good. I changed mpiexec to mpifds to be 100% sure. Still, it doesn't work.

However, 'hydra_service -status' gives 'no hydra service running on xx'. Unable to connect etc, that's obviously the source of my problem! any suggestion?

Thanks again!
Coraline

**Comment by gforney** [comment]
Open a command windows - make sure you open it as administrator.  Type the
following command

hydra_service -install

This command should have been run during the fds installation. Then type
hydra_service -status
It should say something like
hydra service running on xxx.yyy.zzz
where xxx.yyy.zzz is the hostname of your computer

On Wed, Nov 18, 2015 at 6:17 AM, cfaurie notifications@github.com wrote:

> Alright, sorry it took me a while to come back to this, and thank you all
> for your help!
> 
> 'where fds' and 'where mpiexec' both link to FDS6\bin, so that's good. I
> changed mpiexec to mpifds to be 100% sure. Still, it doesn't work.
> 
> However, 'hydra_service -status' gives 'no hydra service running on xx'.
> Unable to connect etc, that's obviously the source of my problem! any
> suggestion?
> 
> Thanks again!
> Coraline
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3114#issuecomment-157682102
> .

## 

Glenn Forney

**Comment by cfaurie** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13315351/11242643/ecd4dd3c-8dfa-11e5-9b25-c335d43975c8.png)

Still the same error!

**Comment by gforney** [comment]
for what it is worth, this error is different.  Earlier you said hydra service was not running
"However, 'hydra_service -status' gives 'no hydra service running on xx'.  "
but output from last hydra_service -status indicates that it is now.

I would suggest you reinstall FDS.  Looks like the firewall rules were not setup (this is done during the FDS installation)

**Comment by cfaurie** [comment]
that's right, the hydra_service didnt work previously. hydra_service -install solved this, but the original error remains.

**Comment by cfaurie** [comment]
I think I have the start of a solution. I changed both environment variables 'MPICH_PORT_RANGE' and 'MPIEXEC_PORT_RANGE' to 670:690 (completely randomly) and it seems to work. Let me run a few more checks and I'll let you know, I tried a lot of different things so I'm not 100% sure yet.

**Comment by mcgratta** [comment]
OK, maybe you are using the ports that we have chosen.

**Comment by mcgratta** [comment]
Are you sure that smpd is not running:

smpd -status

**Comment by mcgratta** [comment]
Any progress on this issue?

**Comment by cfaurie** [comment]
Hi there, 

Sorry it took me a little while to get back to you. I don't think changing the ports solved my issue in the end. I removed the Intel MPI directory from Star installation directory, I had to stop the hydra services first to be able to do this. Then re-install FDS, reboot, and both works fine. I'm using the default IBM Platform MPI distribution for Star. 

Hope it helps.

Coraline

**Comment by mcgratta** [comment]
Yes, that does help. I don't really know what we can do to avoid this problem, but at least we have a record of one possible solution. Thanks.
