### ISSUE TITLE
Smokview not working

### ISSUE THREAD

**Issue by max36795** [firemodels/fds#3115]
Hi,

my Smokeview isn't working anymore. It only shows some outlines and maybe one
particular surface but that's all. I have attached a screenshot. I updated pyrosim/fds/
smokeview today so might be some incompatibility?

Regards

![smokeview](https://cloud.githubusercontent.com/assets/15821782/11127449/b164d62e-8974-11e5-9ce5-4a3aed0ab24c.jpg)

**Comment by rmcdermo** [comment]
Glenn is out for a couple days.  We will get to this asap.

**Comment by rmcdermo** [comment]
Here is a thought.  I just had an issue with the latest SMV related to starting a case with a .ini file.  Had you previously saved a .ini file for that case?  If so, try removing it and reloading SMV.  If this works, that will at least give us a place to start.  Thanks.

**Comment by max36795** [comment]
Thanks for the quick response! I reinstalled the programs and will give it another try tomorrow

**Comment by gforney** [comment]
I'm not able to reproduce the problem.  create a simple test case that illustrates the problem and post it.  I'll take a look at it.

**Comment by max36795** [comment]
Turns out it's working quite well right now. Also pressing the q button shows/hides the geometry

**Comment by rmcdermo** [comment]
This always happens once Glenn gets "close" to the problem.

**Comment by gforney** [comment]
I'm going to close the issue.  If the problem reoccurs, reopen it.
