### ISSUE TITLE
Below ambient temps for simple chemistry calcs

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3118]
Jason,
I noticed in a recent case I was working on that I was getting negative temps (with alt-r in SMV).  The attached simple case illustrates the problem.

[tmp_simple.txt](https://github.com/firemodels/fds-smv/files/34030/tmp_simple.txt)

I did a bisect and found that commit 7ab4eee FDS Source: Improve computation of mu and k for gas mixtures caused most of the problem.  Before this commit we see min temps of 17 C and after -4 C.  I'd still like to get this back to 20 C.  But we need to solve the bigger problem first.

**Comment by drjfloyd** [comment]
I'll look at it.

**Comment by rmcdermo** [comment]
Thanks.

**Comment by rmcdermo** [comment]
Case works fine for 7ab4eee with FLUX_LIMITER=1.  I'll take it from here.

**Comment by drjfloyd** [comment]
What are you seeing for temps.  I am just seeing occasional drops below ambient at the edge of the burner. 

![tmp_simple_0640](https://cloud.githubusercontent.com/assets/12799217/11149171/23518d02-89ef-11e5-9898-81e4dc09778a.png)

**Comment by rmcdermo** [comment]
When you load Smokeview slice it will show you the max and min values of the field both in space and time.  I see -4 C at the commit I mentioned above.

**Comment by rmcdermo** [comment]
No reacting cases seem fine, even with default flux limiter.  I wonder if I messed up something in fire with all my changes there.

**Comment by rmcdermo** [comment]
Jason,
What is the theory behind using sqrt(MW) in the function calls to K and MU?

**Comment by drjfloyd** [comment]
Actual computation of K and MU for mixtures is a very complicated function of MW and pretty computationally costly. See the image below. The reference given in the guide is a paper that notes that simple MW weighting is OK if MW is similar but can have large errors as MW differences get larger.  The paper notes that the square root weighting is computationally cheap and keeps errors much lower than the simple MW weighting.  

![image](https://cloud.githubusercontent.com/assets/12799217/11153640/2e6bd8be-8a08-11e5-9d48-1166a1834358.png)

**Comment by rmcdermo** [comment]
Kevin,
Here is the latest.
[tmp_simple.txt](https://github.com/firemodels/fds-smv/files/34323/tmp_simple.txt)

**Comment by mcgratta** [comment]
First, MASS_FLUX=0.2 is equivalent to HRRPUA=0.2*50000=10000 kW/m<sup>2</sup>. When I make this change, I see the same behavior regardless of whether I use HRRPUA or MASS_FLUX. 

Next, the only EVALUATE_RAMP call that matters is in `wall.f90`

```
ONE_D%MASSFLUX(N) = EVALUATE_RAMP(TSI,SF%TAU(N),SF%RAMP_INDEX(N))*SF%MASS_FLUX(N)
```

If you manually remove the `EVALUATE_RAMP` function and replace with 1, you get what you get when you set TAU_Q (or TAU_MF) to 0. 

When I set  `CONSTANT_SPECIFIC_HEAT_RATIO=.TRUE., STRATIFICATION=.FALSE.`, things work. This leads me to think that the problem is in either `ENTHALPY_ADVECTION` or `SPECIES_ADVECTION' in`divg.f90`. Both take`UWS`or`UW`from`SPECIES_BC`in`wall.f90`and both are turned off by`CONSTANT_SPECIFIC_HEAT_RATIO`. 

But why do things work when `TAU_Q=0`? I suspect that `UWS=MFT/RHO_F=constant` when you set `TAU_Q=0`. Things also work when you dial back the `HRRPUA`. As evidenced by the temporary noise in `minT` at the start of the run, the numerics aren't perfect. The advection routines use the predicted value of `RHOS`, but the non-predicted value of `U`, `V`, and `W`. 

I don't know whether or not this is just to be expected in this extreme case, or whether the numerics in the advection routines can be cleaned up a bit.

**Comment by rmcdermo** [comment]
Revisiting this issue with a new test case.  The attached give -10 C temps with latest code.

[tmp_issue.txt](https://github.com/firemodels/fds-smv/files/49019/tmp_issue.txt)

**Comment by mcgratta** [comment]
Here is a case that takes the boundary out of it:

```
&HEAD CHID = 'tmp_issue' TITLE = 'Test lower temperature limit remains at 20 C' /

&MESH IJK = 80,1,100, XB = -0.40,0.40, -0.005,0.005, 0.00,1.00 /

&TIME T_END = 1.0, DT=0.005 /

&REAC FUEL = 'PROPANE' /

&PART ID='ignitor', SAMPLING_FACTOR=1, SURF_ID='burner', STATIC=.TRUE. /
&SURF ID='burner', MASS_FLUX(1)=0.8, SPEC_ID(1)='PROPANE', TAU_MF(1)=0.0, RADIUS=0.001, GEOMETRY='SPHERICAL' /
&INIT PART_ID='ignitor', XB=0.0,0.01,0.0,0.0,0.3,0.31, N_PARTICLES=1  /

&VENT MB = 'XMIN', SURF_ID = 'OPEN' /
&VENT MB = 'XMAX', SURF_ID = 'OPEN' /
&VENT MB = 'ZMAX', SURF_ID = 'OPEN' /

&SLCF PBY = 0, QUANTITY = 'TEMPERATURE', CELL_CENTERED = .TRUE. /
&SLCF PBY = 0, QUANTITY = 'DIVERGENCE', CELL_CENTERED = .TRUE. /
&SLCF PBY = 0, QUANTITY = 'HRRPUV', CELL_CENTERED = .TRUE. /
&DEVC XB=-0.40,0.40, -0.005,0.005, 0.0,1.00, QUANTITY='TEMPERATURE', STATISTICS='MIN' /

&TAIL /
```

**Comment by rmcdermo** [comment]
I started looking back in history to see if this problem has always been this bad.  For the attached input file, the current code gives a min TMP of -10 C (I think this is just the TMPMIN cutoff).

[tmp_simple.txt](https://github.com/firemodels/fds-smv/files/54459/tmp_simple.txt)

If I got back to 6.2.0, the min TMP is 14.97 C.  Not perfect, but clearly better.  A bisect reveals

7ab4eee 
"FDS Source: Improve computation of mu and k for gas mixtures."

shows a marked change in the behavior.  Jason, I feel like we already looked at this for something, no?

**Comment by rmcdermo** [comment]
I'm banging my head against a brick wall on this one.  I've simplified and simplified; I've tried 2D and 3D; the attached case
- works perfectly for FLUX_LIMITER = 1, with combustion
- works perfectly for FLUX_LIMITER = 2, no combustion, just transport of methane
- fails miserably for FL=2, with combustion

[tmp_simple.txt](https://github.com/firemodels/fds-smv/files/58165/tmp_simple.txt)

**Comment by rmcdermo** [comment]
Going way back, I found that round about the time we were converting over to "full transport" things started to get shaky.  This is the commit where things go from being pretty much perfect to not so perfect.

https://github.com/firemodels/fds-smv/commit/688950afebfb856d713cba8e189a55e5392d684f

However, I'm not saying this commit is at fault.  Just that we need to hone our search around this general area.  Gotta go for now.

**Comment by rmcdermo** [comment]
More bisecting.  The commit from my previous note showed only a minor change, which may have been expected when we flipped the FULL_TRANSPORT switch.  Min temps went from 19.9999... to 19.991....

Where things really went south was when we got rid of the "0th" species.

https://github.com/firemodels/fds-smv/commit/27de115

Min temps go from 19.99 to 10... in this commit.  In a way, this is good, because theoretically all should be the same as what we were doing.  But I suspect we have some assumption related to BACKROUND causing problems.

When you go to the above link in GitHub, notice that it also shows you the parent of that commit, which is

7bb7299

Test both with this input file.

[tmp_simple.txt](https://github.com/firemodels/fds-smv/files/66832/tmp_simple.txt)

**Comment by rmcdermo** [comment]
The gods are good.  The recent changes have at least fixed the tmp_simple case.  This input file gives me perfect results with latest code.

[tmp_simple.txt](https://github.com/firemodels/fds-smv/files/75126/tmp_simple.txt)

Unfortunately, the original issue still has problems.  Here is that input file again:

[tmp_issue.txt](https://github.com/firemodels/fds-smv/files/75128/tmp_issue.txt)

**Comment by drjfloyd** [comment]
If I get rid of RADIATIVE_FRACTION and the chi_r ramp, then all is well.
If I specify RADIATIVE_FRACTION without a RAMP, as I get closer to 1 I see
more temperature issues. I think there may be something wrong with the RAMP.

**Comment by drjfloyd** [comment]
The case is missing RAMP_CHI_R on REAC.

**Comment by rmcdermo** [comment]
OMG.

**Comment by rmcdermo** [comment]
OK, that worked.  Thanks.

Next problem is that if we leave RADIATION=T on RADI then we get 14 C temps.

**Comment by drjfloyd** [comment]
So take temp_issue.fds with RAMP_CHI_R added and then add
&RADI RADIATION=.TRUE./  

?

**Comment by rmcdermo** [comment]
The attached seems to work.  Leading us to believe the problem may be with the RTE source correction factor.  The problem seem to be confined to the beginning of the calculation.  But I would like to get this worked out so that we can have some really practical verification cases.

[tmp_issue.txt](https://github.com/firemodels/fds-smv/files/75182/tmp_issue.txt)

**Comment by rmcdermo** [comment]
I pushed up a limiter 10.0 on RTE_SOURCE_CORRECTION_FACTOR.  Print outs of this value at the beginning of the calculation were 1300, which is way too high.

**Comment by rmcdermo** [comment]
I added a few verification cases in Fire/tmp_lower_limit*.  I will close for now.
