### ISSUE TITLE
.ini file problem

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3119]
Glenn,
I put a case in /home4/rmcdermo/Issues/James/smv_issue/tmp_simple\* that has some kind of problem with .ini.  With this case, if you load a slice of temperature the colorbar goes from 0 at the top to a positive 18 at the bottom.  The .ini was saved with 0 top and something line -10 C at the bottom.

**Comment by gforney** [comment]
the ini file had the following line for the temperature slices
V_SLICE
 2 -10.000000 1 0.000000 temp : 0.000000 1.000000 1

The first 2 tells smokeview to use a global min (which was 18.xx) .  

I changed the 2 to a 1 and the temperature slice loaded ok.  Start with a clean slate (erase the present .ini file), set the bounds the way you want and save the .ini file again to see if the problem occurs.  Also you could try setting the global bound setting for some other quantity then saving the .ini file to see if this confuses smokeview.

**Comment by gforney** [comment]
I see you don't have any other slice file quantities so the experiment I suggested won't be possible.  I would guess that some how the min bound seting got set to 'global min' rather than 'user min'

**Comment by rmcdermo** [comment]
Seems to work when Glenn is standing over me!
