### ISSUE TITLE
Open Vent and Sprinkler

### ISSUE THREAD

**Issue by max36795** [firemodels/fds#3121]
Hi,

when I ran my latest model I stumbled upon another issue which I am sure there is a very simple explanation for. So I'm running my simulation for about 30min and most of the time there is smoke occuring and beeing exhausted through openings in a roof. After a while though the entire mesh is filled with smoke eventually filling everything. I suppose one could just extend the size of the mesh, but I was wondering if you could place an open vent through which the smoke exhausts?

Secondly my simulation sometimes stopps when I' modeling sprinklers. Does anyone else had that problem? And are sprinklers actually influencing the process of the fire hence controlling the hrrpua at one point? 

Thanks in advance. 
Max

**Comment by mcgratta** [comment]
I do not understand the first question. 

FDS sometimes has trouble with sprinklers. Create a very simple test case that demonstrates the problem. Strip everything out of the file except a few sprinklers. Make sure the flow pattern looks reasonable. Maybe the droplets are too small, or the FLOW_RATE too large.

**Comment by max36795** [comment]
Okay thanks I will try working on that sprinkler problem.

My first question is long story short that my open vent on the mesh boundary is not open. Smoke doesn't exhaust through it.

**Comment by max36795** [comment]
Ah nevermind the vent problem I managed to fix it. 

I will try figuring out the sprinkler problem.
