### ISSUE TITLE
some questions about fds2ftmi

### ISSUE THREAD

**Issue by ChaoyiXu** [firemodels/fds#3129]
Hi,
I don't know how to use the macros “ansys2ftmi.geom” or “ansys2ftmi_shell.geom” to export the mesh information. It looks like “.geom” is not a correct file name extension for the marcos in ANSYS. I use the ANSYS 16.0, is it a version problem? If anyone has successful experience with fds2ftmi?

Thanks,
Chaoyi Xu

**Comment by mcgratta** [comment]
This is better posted to the FDS Discussion Group. The Issue Tracker is for bug reports.
