### ISSUE TITLE
Raising the VN_MAX to 1 causes a few HVAC cases to go out of tolerance

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3130]
I've noticed that the time step in some FDS calcs are bound by the VN constraint, not the CFL. In particular for coarse grids involving vents. The VN_MAX is currently 0.5, but in theory could be 1. We held it at 0.5 to prevent instabilities, but I am now looking to revisit this. 

I ran the verification cases and saw no instabilities, but I did see a few HVAC cases fall out of tolerance. A case in point is HVAC_flow_loss.fds, in which the flow through a T-jointed duct gets a bit "noisier" when VN_MAX=1. I put together a simpler test case:

```
&HEAD CHID='junk',TITLE='Test of duct flow loss' /

&MESH IJK=20,20,20, XB=0.,1.,0.,1.,0.,1./

&MISC VN_MAX=1.0, VN_MIN=0.8, STRATIFICATION=.FALSE./

&TIME T_END=10. /
&RADI RADIATION=.FALSE./

&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/

&SURF ID='HVAC-OUT', VEL=-2.5 /
&SURF ID='HVAC-IN', VEL=7.5 /
&VENT XB=0.1,0.3,0.4,0.6,0.00,0.00,ID='OUTLETA',SURF_ID='HVAC-OUT',COLOR='RED'/
&VENT XB=0.6,1.0,0.4,0.6,0.00,0.00,ID='OUTLETB',SURF_ID='HVAC-OUT',COLOR='ORANGE'/
&VENT XB=0.4,0.6,0.4,0.6,1.00,1.00,ID='INLET',SURF_ID='HVAC-IN',COLOR='GREEN'/

 HVAC TYPE_ID='NODE',VENT_ID='OUTLETA',DUCT_ID='DUCT2B',ID='OUTLETA'/
 HVAC TYPE_ID='NODE',VENT_ID='OUTLETB',DUCT_ID='DUCT2C',ID='OUTLETB'/
 HVAC TYPE_ID='NODE',VENT_ID='INLET',DUCT_ID='DUCT2',ID='INLET'/
 HVAC TYPE_ID='NODE',DUCT_ID='DUCT2','DUCT2B','DUCT2C',ID='TEE',XYZ=0.5,0.5,0.0/
 HVAC TYPE_ID='DUCT',NODE_ID='INLET','TEE',ID='DUCT2',VOLUME_FLOW=0.3,LENGTH=1.,AREA=0.1/
 HVAC TYPE_ID='DUCT',NODE_ID='TEE','OUTLETA',ID='DUCT2B',AREA=0.1,LOSS=16,16/
 HVAC TYPE_ID='DUCT',NODE_ID='TEE','OUTLETB',ID='DUCT2C',AREA=0.1,LOSS=4,4/

&SLCF PBY=0.5, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBY=0.5, QUANTITY='DIVERGENCE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.5, QUANTITY='VISCOSITY', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.5, QUANTITY='STRAIN RATE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.5, QUANTITY='VN', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.5, QUANTITY='CFL', CELL_CENTERED=.TRUE. /

&TAIL /
```

As written here, the case is divergence free. If I put back the HVAC functionality, I get non-zero divergence near the GREEN vent. To try to determine what was going on, I went into HVAC_BC in wall.f90 and just forced it to return the appropriate UN (UW, UWS) for the various vents. But I could not get rid of the divergence error. 

Can you think of a reason for this? I don't think that the HVAC solver is broken. Rather, I think that when we raise VM_MAX to 1, we run with a larger time step, and we start seeing classic oscillations in temperature due to a time step that approaches the explicit limit. It's just that I don't see this when I just set SURF VELs for the boundary conditions. Perhaps the HVAC stuff can provide a clue to what is happening when we increase the time step. 

Let's not fix anything that is not broken. Let's just see if there is some reason why the HVAC solver might trigger an VN-esque instability more readily than a fixed velocity BC.

**Comment by rmcdermo** [comment]
What gets me a lot of times when the DT seems to fix a problem is that something becomes inconsistent in the CHANGE_TIME_STEP loop.  This loop gets triggered for larger DT but not for smaller DT.

Is there anything in HVAC that only makes sense for FIRST_PASS?  This happens in DENSITY for example.  Maybe HVAC is actually trying to overwrite a diffusive flux when it should not be.

**Comment by mcgratta** [comment]
Not in this case -- the time step changes when VN_MAX=0.5 too. I think that we are pushing towards the stability limit, and there is something about the HVAC routine that "triggers" the instability more readily than when we just fix the BC.

**Comment by rmcdermo** [comment]
Presumably the value of H in the gas phase cell near the bc is used in the
HVAC solver.  Upon solution of the Poisson equation that H changes.  Is the
HVAC solution still valid or does it need to be adjusted right then and
there to be consistent with the H field?

**Comment by mcgratta** [comment]
I've noticed that the VISCOSITY and STRAIN_RATE are greater near the HVAC inlet than the VENT with fixed VEL. Can you think of any reason for this? How are the velocity BCs handled differently at an HVAC VENT?

**Comment by drjfloyd** [comment]
The HVAC BC should be handled in the exact same manner as as MASSFLUX BC.  If you run the case using fixed mass flux rather than fixed velocity, does the problem go away?  If it does, then somewhere we aren't doing something for HVAC that we are for mass flux.

**Comment by rmcdermo** [comment]
Right, but we are obviously missing something.  Is there any prayer of actually using the same routine if it is supposed to do the same thing?

**Comment by drjfloyd** [comment]
Possibly?

**Comment by rmcdermo** [comment]
I think it made sense to have separate routines while HVAC was young and in
development.  But this is probably just a good excuse to finally merge the
bcs so we don't get into a "WFDS" situation.

**Comment by mcgratta** [comment]
I think I found the problem. The HVAC inlet vent uses the WALL_MODEL velocity BC. The regular old vent with fixed MASS_FLUX or VEL uses free slip because in read.f90

```
IF (SUCKING) SF%FREE_SLIP = .TRUE.
```

Who says the code is opaque? If I set the HVAC velocity BC the same way, things work, that is, with VN_MAX=1, the flow is divergence free. Trouble is, in general we don't know if an HVAC vent is blowing or sucking. Maybe we can check this on the fly.

**Comment by drjfloyd** [comment]
Fixed the velbc. I wonder if this was behind some of the other HVAC issues with stability?

**Comment by rmcdermo** [comment]
Would not be surprised.

My prediction for the result of the validation runs with VN=1 is that we
are going to start seeing checker boarding now caused by CFL since we
really should be using CFL_VELOCITY_NORM=1.  I think the VN=.5 was
preventing us from needing NORM=1.  The danger here is that things won't go
unstable, but that if you actually scrutinized all the cases you would see
temperatures below ambient in lots of places.  But we never really check
this unless it is a verification case.  I guess we cross that bridge when
we get to it.

**Comment by mcgratta** [comment]
I ran the entire verification suite with VN_MAX=1, VN_MIN=0.8. Everything looks OK. There was only one case out of tolerance, soot_graviational_settling, but it appears that this is not directly related to VN but rather just an overly tight tolerance. I'm going to run the serial validation cases over the weekend to see if anything else looks amiss. I have not committed this change.

**Comment by rmcdermo** [comment]
I expect this.  Because anywhere this might be a problem, for example, the
mwtest_cfl.fds case in Flowfields, we have set the CFL_VELOCITY_NORM=1 and
CFL_MAX=0.5.  Then we are perfect.

If you use your new default parameters, this case (granted it is a tough
case) has temperatures ranging from 12 C to 112 C (it should be isothermal).

**Comment by rmcdermo** [comment]
I recommend grepping the verification cases and removing CFL stuff from all
cases, then rerun.

**Comment by drjfloyd** [comment]
Pushed up changes that moved the species and velocity bc in with the normal wall handling.  temperature is still done in HVAC_BC. HVAC_BC now determines if the wall cell is BLOWING (sets SPECIFICED_MASS_FLUX and ONE_D%MASSFLUX)  or SUCKING (sets SPECIFIED_MASS_FRACTION and ONE_D%UW). If it passes firebot do we close this or leave it open while we figure out what to set VN_XXX to?

**Comment by mcgratta** [comment]
Let's leave it open. We're going to revisit VN next week.

**Comment by mcgratta** [comment]
I ran the entire validation suite with VN_MAX=1 and VN_MIN=0.8 and there were no instabilities. I committed these new values. I'll close this issue and reopen if VN becomes a problem again.
