### ISSUE TITLE
NIST/NRC smoke concentration predictions used smoke deposition feature

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#3143]
In the Validation Guide, figure 9.19 and table 15.1 report quite large values for both the relative model uncertainty and bias of smoke concentration predictions. I think it would be helpful to indicate in section 9.2.2 that these predictions were done with the smoke deposition model in place. 

I don't think many FPEs are using the smoke deposition model, and may not realize that their predicted values will probably have an even greater uncertainty and bias than the NIST/NRC studies.

Thanks

Dave

**Comment by mcgratta** [comment]
For that particular data set, the results are more or less the same with or without the smoke model. Unfortunately, that is our only data set for point smoke concentration.

**Comment by drjfloyd** [comment]
Dave,

I am working on a paper for Interflam looking at how various soot behaviors
(size distribution, deposition, settling, agglomeration, and oxidation)
impact the soot density at the measurement point in the NIST/NRC tests.
Kevin is correct, right now we have set the default soot particle size to 1
micron and the  deposition / settling that results doesn't have a large
impact.

**Comment by Dave-McGill** [comment]
Thanks Guys.
