### ISSUE TITLE
Mesh and result problems

### ISSUE THREAD

**Issue by Sertec-to** [firemodels/fds#3155]
Good morning,
I have problems with the mesh of my project,
In particular in the boundaries of the mesh there are discontinuities in temperature, heat flux and etc.
Maybe the problem is that I have created 5 meshes, with different mesh size. 
I created different size meshes because I think that near the fire the mesh must be thickest, in contrast I think that far the fire the mesh must be less dense.
What do you think about these assumptions?

The program display me that meshes are aligned, but in smokeview I can see discontinuities near boundaries of different meshes.

This is the list of my meshes:
Mesh 05 (the further away from fire) have cell size: 1,5 x 1,5 x 1,5 [m]  X cells: 31 , Y cells: 12, Z cells: 4
Mesh 04 have cell size: 1,5 x 1,5 x 1,5 [m]  X: 18 , Y: 12, Z: 4
Mesh 03 have cell size: 0,7576 x 0,75 x 0,75 [m]   X: 33 , Y: 24, Z: 8
Mesh 02 have cell size: 0,7778 x 0,75 x 0,75 [m]   X: 18 , Y: 32, Z: 8 
Mesh  (the closest to fire) have cell size: 0,3784 x 0,3750 x 0,3750 [m]  X: 37 , Y: 64, Z: 16

The main problem is in correspondence of Mesh number 03. I can see discontinuities between Mesh 03 respect to Mesh 04 and Mesh. 

Do you suggest to build different meshes with the same cell size ? Like equal to 1 x 1 x 1 or 1,5 x 1,5 x 1,5 m?

I attach my project in txt format.
Anyone could help me ? 

Thanks.
Best regards,

Simona 

[Iren_Pyrosim_TXT.txt](https://github.com/firemodels/fds-smv/files/41484/Iren_Pyrosim_TXT.txt)

**Comment by mcgratta** [comment]
What version of FDS are you using, and what kind of output are you looking at?

**Comment by mcgratta** [comment]
I cannot help you if you do not answer my questions. Closing the issue.
