### ISSUE TITLE
A bug in liquid fuel burning？

### ISSUE THREAD

**Issue by doctorzcx** [firemodels/fds#3164]
I have built a model  using liquid methanol as fuel and it could burnout. The fire was suffocated by sealing the open and the fuel had not been exhausted. when the open was unsealed again in few minutes, the unburned fuel gas in room should burn again if the temperature in room is still higher than the ignition point of the fuel gas. On the contrary, it should not. However, no matter how low the temperature in room is (even lower than normal atmospheric temperature) when unsealing the open, the fuel gas could burn again. That is  unreasonable obviously. The fuel gas should not burn again when the temperature is lower than its ignition point. I want to find the critical temperature for the fuel gas burn again when unsealing the open. Can you help me ? Thanks  very much!

**Comment by mcgratta** [comment]
This is a topic of research. Re-ignition is difficult to predict with a numerical model. If you are using the default simple chemistry combustion model, it is assumed that oxygen and fuel burn on contact. There is a parameter called AUTO_IGNITION_TEMPERATURE, but it is difficult to say what this ought to be for a given fuel. Post a simple test case and we'll take a look at it.

**Comment by rmcdermo** [comment]
If you need to do this today you have to use DNS with detailed Arrhenius chemistry and a detailed heat transfer model.  We are working on some ad hoc ways to handle reignition problems with the EDC combustion model.  Stay tuned to new release notes.  If and when we get this working robustly, the release notes will mention it.

**Comment by doctorzcx** [comment]
Thanks very much for your great help. It seems that the problem can not be solved now. We look forward to the new FDS version. Thanks very much again!

**Comment by doctorzcx** [comment]
Thanks very much for your great help. It seems that the problem can not be solved now. We look forward to the new FDS version. Thanks very much again!
