### ISSUE TITLE
Running two simulations simultaneously using mpiexec in Windows 7

### ISSUE THREAD

**Issue by fdsuser** [firemodels/fds#3196]
I'm running FDS 6.3.2 and I'm having an issue with running two simulations simultaneously in one machine with multiprocessors using mpiexec in Windows 7. While I'm running a simulation with mpiexec using multiprocessor, I'm trying to launch another simulation with mpiexec. But, the second simulation doesn't run. Previously, I was able to do this with FDS 6.2. Please advise.

**Comment by mcgratta** [comment]
I can only run 1 MPI job on my Windows machine. We did not change the functionality from 6.2 to 6.3. I don't know how it would have worked previously.

**Comment by fdsuser** [comment]
I was able to do that in FDS 6.2 on my machine. Is there anyway I can run two simulations in FDS 6.3.2?

**Comment by drjfloyd** [comment]
I haven't tried running multiple mpi runs on my laptop in a while, but I will confirm that I was previously able to run more than one concurrent MPI run and and now can't.  Perhaps some default compiler option has changed?

**Comment by mcgratta** [comment]
I was never able to do it on my machine, regardless of version.

**Comment by gforney** [comment]
were we using hydra with 6.2?

**Comment by fdsuser** [comment]
I was always able to do it up to FDS 6.2 on my machine using MPI parallel processing method shown on user manual. Sorry, I'm not sure what you mean by "hydra". I only use standard mpiexec command and define the host name of computer and number of processors.

**Comment by mcgratta** [comment]
I forget when we switched. In any case, we do not have control over this kind of thing. Most MPI apps run via a job scheduler.

**Comment by ChanJJB** [comment]
I just started to use FDS6 and am still on version 6.2.0. I'm also having similar problem where the 2nd MPI job does not start.

**Comment by mcgratta** [comment]
I cannot control this behavior. If you want to run multiple MPI jobs under Windows, I suggest you look into Windows HPC (High Performance Computing).
