### ISSUE TITLE
No Obstruction seen in smokeview

### ISSUE THREAD

**Issue by Nitin-Bhaskar** [firemodels/fds#3211]
HI,

I am running a model in FDS 6.3.0. When i look at the smv file, it appears as a blank box with no OBSTs, VENTs etc. However, if i load the smoke file, I can see the smoke movement around the obstructions, which means the everything is there but I can't see it. Has anyone faced this issue before? I have attached the file and two screen shots of smoke.

![the_one_151209-test1_0002](https://cloud.githubusercontent.com/assets/16235874/11708745/0b5cec2c-9f2b-11e5-89a7-264b6b4f3454.png)
![the_one_151209-test1_0008](https://cloud.githubusercontent.com/assets/16235874/11708747/0f9a066c-9f2b-11e5-8f62-88d09a67b2dd.png)

Thanks in advamce.

**Comment by gforney** [comment]
See if you can go to the Show/Hide>Geometry menu and select menu option to
make obstructions visible.

**Comment by Nitin-Bhaskar** [comment]
Got it, show/hide>Geometry>Obstacles>Locations:*Actual was missing. 
Thanks.

**Comment by gforney** [comment]
upload your case and I'll take a look at it

**Comment by gforney** [comment]
can you upload your case

**Comment by Nitin-Bhaskar** [comment]
Hi Glenn,

Attached is the case. The issue is resolved though.

Regards,
Nitin

**Comment by gforney** [comment]
OK thanks, I misunderstood. I'll close the issue.
Glenn
