### ISSUE TITLE
INIT does not overlap XB

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3220]
Kevin,

The attached case is meant to init Q in a small region but init Z_METHANE = 1 everywhere.  It seems the XBs cannot overlap.  The last INIT line trumping the ones before.  If I specify HRRPUV first, it gets overwritten by MASS FRACTION.  If the quantities are different shouldn't it be okay if the XB overlap?

**Comment by mcgratta** [comment]
The last INIT line takes precedence over the first. I'll add some text to the User's Guide.

**Comment by mcgratta** [comment]
Done
