### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by dkkkji** [firemodels/fds#3229]
(1)It is found that the fire plume will not appear in smokeview when the height  of fire source less than 1/2 of grid  size in FDS 6 (it seems no comnbustion occured during the simulation). 

(2)And I want to know how to simulated a slope bulingdings just like that in FDS5? 

(3)The inclination of the buliding  was composed by many small "OBST" whose size also less than 1/2 of grid  size  .THE question is : Does the inclination work ?

**Comment by rmcdermo** [comment]
These questions are for the discussion forum.  Issues is for reporting bugs.

https://groups.google.com/forum/#!forum/fds-smv
