### ISSUE TITLE
Relationship between inclination and grid size

### ISSUE THREAD

**Issue by Brooklyn0007** [firemodels/fds#3231]
(1)It is found that the fire plume will not appear in smokeview when the height of fire source less than 1/2 of grid size in FDS 6 (it seems no comnbustion occured during the simulation).

(2)And I want to know how to simulated a slope bulingdings just like that in FDS5?

(3)The inclination of the buliding was composed by many small "OBST" whose size also less than 1/2 of grid size .THE question is : Does the inclination work ?

**Comment by rmcdermo** [comment]
This is not an "issue".  Please post your questions to the discussion forum and I will answer there.  Else, only the people with GitHub accounts see the reply, and they may have the same question as you.

https://groups.google.com/forum/#!forum/fds-smv

**Comment by Brooklyn0007** [comment]
Thank you for your advice ,i can not find the place to post my question  in  in https://groups.google.com/forum/#!forum/fds-smv,I'd like you to give me some detailed advice

**Comment by rmcdermo** [comment]
You have to join the discussion group.  Please give a detailed description when you join of how you use the code, else the join request will be rejected.
