### ISSUE TITLE
Smokeview: Visualization problem with HRR

### ISSUE THREAD

**Issue by guipesa** [firemodels/fds#3238]
Hi,

In the last version of smokeview I found a problem in the visualization of the HRR when it is loaded with the smoke. When hrr is shown alone it works fine. 

When smoke and hrr are loaded and GPU visualization is activated the problem doesn't appear.
I attach some images and also de .ini file of this case.

Thanks, 
Guillem,

[Mercado.txt](https://github.com/firemodels/fds-smv/files/62867/Mercado.txt)

Only HRR and GPU deactivated:
![nogpu_onlyhrr](https://cloud.githubusercontent.com/assets/14068673/11816685/d376020a-a351-11e5-8e1a-fa6ce7a1e63c.png)
HRR and smoke and GPU deactivated:
![nogpu_smoke and hrr](https://cloud.githubusercontent.com/assets/14068673/11816683/d36f430c-a351-11e5-8750-53787084faf1.png)
HRR and smoke and GPU activated:
![gpu_smoke and hrr](https://cloud.githubusercontent.com/assets/14068673/11816684/d37385c0-a351-11e5-95f4-3470bb30a77f.png)

**Comment by gforney** [comment]
upload a simplified input file that exhibits the problem and I'll take a look at it

**Comment by guipesa** [comment]
I attach a simple example where it happens the same.
[pruebasoot.ini.txt](https://github.com/firemodels/fds-smv/files/63915/pruebasoot.ini.txt)
[pruebasoot.fds.txt](https://github.com/firemodels/fds-smv/files/63916/pruebasoot.fds.txt)

**Comment by gforney** [comment]
fixed a problem with how hrr maps to color.  try smokeview located here
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

the GPU and non-GPU views of smoke and fire should now be consistent

**Comment by guipesa** [comment]
Thanks Glenn!

**Comment by gforney** [comment]
thanks for reporting back.
