### ISSUE TITLE
tunnel fires modelling

### ISSUE THREAD

**Issue by mrvlty** [firemodels/fds#3242]
Hi,
I want to simulate tunnel fires . At First,  I am using some data from the literature as an example to learn how ı can use FDS, then I will pass my own study.
I am using a study which was A horseshoe cross-sectioned, short tunnel and jet fans was used to ventilate the system. Fluent was used to simulate the system. I want to ask that whether fluent was preferred  instead of FDS because of  the geometry of tunnel and jet fans or not . And  Can I  use FDS for this study’s simulation?

**Comment by mcgratta** [comment]
The Issue Tracker is for reporting specific bugs. For general discussions and questions, use the FDS-SMV Discussion Group.

https://groups.google.com/forum/#!forum/fds-smv
