### ISSUE TITLE
forrtl: severe (67): input statement requires too much data

### ISSUE THREAD

**Issue by kubikus** [firemodels/fds#3254]
![error](https://cloud.githubusercontent.com/assets/5666103/11890430/95617800-a554-11e5-943c-17aa4ddd8063.png)
Hello 
I am in trouble with resuming in parallel simulation after restarting computer.
I am using PyroSim preprocessor for run FDS simulation.
I simulated my project for a very long time, then I stoped it and restarted computer. Then I wanted to resume in simulation (FDS -> Resume Parallel Simulation), but it recieves me error mesage (in attachment) in a while.
It is strange, because I have done this procedure with restarting computer many times earlier and resuming worked correctly, but not this time.
I am saving already calculated data to backup file (.restart) for every 5 seconds of calculated simulation. Pyrosim's support team told me that the error message originate from FDS and they are not pretty sure what it means.
Please can you help me solve this problem?

Is it able to resume in simulation  not from last saved point, but from some previous point (for example 5 minutes before end of previous simulation) ?

Error message:

Starting FDS: C:\Program Files\PyroSim 2015\fds\fds.exe...

 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4
forrtl: severe (67): input statement requires too much data, unit 26, file \P0Cat\download\MARTIN 2\garageSHZ_E0,07\garageSHZ_E0,07_0002.restart
Image              PC                Routine            Line        Source  
fds.exe            00007FF604023958  Unknown               Unknown  Unknown
fds.exe            00007FF603FD50BA  Unknown               Unknown  Unknown
fds.exe            00007FF603FD29DA  Unknown               Unknown  Unknown
fds.exe            00007FF604738E2D  Unknown               Unknown  Unknown
fds.exe            00007FF6040A2D02  MAIN__                    315  main.f90
fds.exe            00007FF60409D91E  Unknown               Unknown  Unknown
fds.exe            00007FF6047B3A1C  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFD8BDE13D2  Unknown               Unknown  Unknown
ntdll.dll          00007FFD8E3B5454  Unknown               Unknown  Unknown

PyroSim version 6.3.2
OS: Windows 7

Best Regards
Jakub

**Comment by mcgratta** [comment]
The message means that the file (or one of its records) has more data than the computer can handle. This is a recurring problem under Windows. We do not see it on linux/unix OS. There's not much we can do about it, since I am not an expert in Windows filing handling. My only advice would be to not rely on restarts, or use linux.

**Comment by Satcomx00-x00** [comment]
Error found under Linux Ubuntu 18.04 for FDS 6.7.1 Docker based
