### ISSUE TITLE
Fuel gives a HHR of zero in FDS 6.3.2

### ISSUE THREAD

**Issue by togersen** [firemodels/fds#3256]
I am trying to model a fire in FDS where I have used Pyrosim for the modelling part. It is the newest version of Pyrosim and it supports FDS 6.3.2

I have made a simple test of box by 10 m x 10 m x 5 m with code below:

C3H6Test.fds
Generated by PyroSim - Version 2015.4.1214
18-12-2015 14:25:19

&HEAD CHID='C3H6Test'/
&TIME T_END=300.0/
&DUMP RENDER_FILE='C3H6Test.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_HRR=1.0, DT_RESTART=300.0, DT_SLCF=20.0/

&MESH ID='Mesh01', IJK=50,50,25, XB=0.0,10.0,0.0,10.0,0.0,5.0/

&REAC ID='C3H6',
      FUEL='REAC_FUEL',
      FORMULA='C3H6',
      SOOT_H_FRACTION=0.0,
      SOOT_YIELD=0.06,
      HEAT_OF_COMBUSTION=2.0E4/

&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=1000.0,
      TAU_Q=-206.284/

&OBST XB=4.4,5.4,4.6,5.6,0.2,0.4, SURF_IDS='Fire','INERT','INERT'/ Obstruction

&VENT SURF_ID='OPEN', XB=0.0,10.0,10.0,10.0,0.0,5.0/ Vent
&VENT SURF_ID='OPEN', XB=0.0,10.0,0.0,0.0,0.0,5.0/ Vent01
&VENT SURF_ID='OPEN', XB=0.0,10.0,3.55271E-15,10.0,5.0,5.0/ Vent02

&SLCF QUANTITY='TEMPERATURE', PBX=4.8/
&SLCF QUANTITY='VISIBILITY', PBX=4.8/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBX=4.8/

&TAIL /

When I run my model the HRR output is zero at all time steps. I can't figure out why this is the case

**Comment by mcgratta** [comment]
Didn't we just address this in the Discussion Group?

**Comment by rmcdermo** [comment]
I am checking to see how this works with latest code.  There is no reason it should not work.

**Comment by togersen** [comment]
If i change the reaction code with the one below it works. But if I change C = 3 and H = 6 it dosen't work.

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=0,
      N=0,
      SOOT_H_FRACTION=0.0,
      SOOT_YIELD=0.06,
      HEAT_OF_COMBUSTION=2.0E4/

**Comment by rmcdermo** [comment]
Use your fix for now.  Double check the .out file to make sure your reaction is giving the right HoC.

**Comment by drjfloyd** [comment]
This is not a bug.  C3H6 with HoC=20 MJ/kg means an EPUMO2 ~ 6 MJ/kg.  This is insufficient to reach the critical flame temperature.  Extinction is occurring.
