### ISSUE TITLE
HVAC aircoil heating with negative FIXED_Q

### ISSUE THREAD

**Issue by plut0nium** [firemodels/fds#3269]
Hi,
Currently playing with FDS HVAC model, and got some strange behaviour with aircoil cooling in a HVAC network.

See attached file for a working example: a HVAC network with three NODE and two DUCT connecting them: [hvac_cooling_test.fds.txt](https://github.com/firemodels/fds-smv/files/69004/hvac_cooling_test.fds.txt)

Sections V1 and V2 illustrate this issue:
If the AIRCOIL with a negative FIXED_Q is in the first DUCT segment (V1), the air at the outlet is hotter than the inlet...
Otherwise if the AIRCOIL in in the second DUCT segment (V2), the air at the outlet is cooler, as expected with a FIXED_Q < 0.

I encounter this problem with the latest FDS version (6.3.2) on Linux x86_64, but not with a previous version (6.2).

Thanks.

**Comment by drjfloyd** [comment]
I'll take a look at it,

**Comment by drjfloyd** [comment]
Fixed.  

Note that these two cases are close but not identical.  With the fan first you move 1 m^3/s of room temperature air.  With the fan second you move 1 m^3/s of cold air (more mass as density is higher).  The result is the exit temperatures will not be exactly the same.

**Comment by plut0nium** [comment]
Thank you very much.

Regarding your note, I was completely aware that the two cases were not strictly identical... their purpose was just to illustrate and reproduce the bug.
