### ISSUE TITLE
Periodic writing of _cpu.csv file

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#3285]
Would it be possible to add a feature to the DUMP namelist that would print out the _cpu.csv file at periodic intervals? 

Thanks

Dave

**Comment by mcgratta** [comment]
I added the ability to dump the _cpu.csv file every DT_CPU s, a new parameter on the DUMP line. This value is very large by default, meaning that the CPU info is dumped only at the end of the simulation unless the user asks for more.

**Comment by Dave-McGill** [comment]
Thanks Kevin
