### ISSUE TITLE
Smyth Burner validation case produces too much CO

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3302]
[Pages from FDS_Validation_Guide.pdf](https://github.com/firemodels/fds-smv/files/74989/Pages.from.FDS_Validation_Guide.pdf)
This case was run over the Christmas break with the latest code as of Dec 23. It appears that there is too much CO and not enough CO<sub>2</sub> formed.

**Comment by rmcdermo** [comment]
Craig,
I suspect this is due to our fixing the bug in the mixing step of the ODE solver.  If the gods are good, the Westbrook-Dryer kinetics parameters will now do a proper job of matching data.  Note that you can also set WD_PROPS=T somewhere, which should tighten this up.

**Comment by mcgratta** [comment]
This case took 33.5 h to run. FIRE and MPI COMMunications dominated the CPU usage.

**Comment by cweinschenk** [comment]
I will explore these issues.

**Comment by mcgratta** [comment]
Closing, this issue has gone cold. If there's still trouble with Smyth burner, we'll start a new issue.

**Comment by sbenkorichi** [comment]
Haha Thanks Kevin, this is what I was talking about when we were at Julich, it's really good to close some of these dead threads are there is nothing to be done and focus on the current release.
