### ISSUE TITLE
No restart file written when T_END and DT_RESTART are equal 

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3318]
In the attached file, T_END and DT_RESTART are both equal to 2. When I run the model, no restart file is written. If I change T_END = 2.2 and leave DT_RESTART=2, then a file is written.

It would be nice to write the restart when both T_END and DT_RESTART are equal to 2.

Thanks and Happy New Year,
Dan

---

burner.fds
Generated by PyroSim - Version 2015.4.1214
Jan 4, 2016 2:16:56 PM

&HEAD CHID='burner'/
&TIME T_END=2.0/
&DUMP RENDER_FILE='burner.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=2.0/

&MESH ID='Mesh01', IJK=20,20,30, XB=-1.0,1.0,-1.0,1.0,0.0,3.0/

&REAC ID='POLYURETHANE_GM27',
      FYI='SFPE Handbook, GM27',
      FUEL='REAC_FUEL',
      C=1.0,
      H=1.7,
      O=0.3,
      N=0.08,
      CO_YIELD=0.042,
      SOOT_YIELD=0.198/

&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=1000.0/

&OBST XB=-0.5,0.5,-0.5,0.5,0.0,0.2, SURF_ID='INERT'/ Fire Obstruction

&VENT SURF_ID='Fire', XB=-0.5,0.5,-0.5,0.5,0.2,0.2/ Fire Vent

&TAIL /

![burner fds](https://cloud.githubusercontent.com/assets/13338306/12099472/5984117e-b2ee-11e5-82b7-770334f318e8.png)

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
At some point, we added a feature whereby the simulation would not be stopped until the radiation routine (which takes place over a number of time steps) was completely updated. I added some logic to override this constraint if T is greater or equal to T_END.
