### ISSUE TITLE
Smoke Exhaust Fans

### ISSUE THREAD

**Issue by rod170597** [firemodels/fds#3343]
I was wondering if someone could give me a hand on the smoke exhaust fans.
I have specified 12,000 L/s (12 m3/s) for the fans however they are running only at 4 m3/s max, not sure what went wrong?
It is also the case for the make up air - specifying 3 m3/s each but running slightly less than what was expected.
I didn't ramp the fans as they are activated by smoke detectors.

Thank you.

[Fire.pdf](https://github.com/firemodels/fds-smv/files/84045/Fire.pdf)

**Comment by mcgratta** [comment]
Your input file is too complicated for me to diagnose the problem. I need you to remove all lines of input that do not demonstrate the problem. You know the case better than I. If I were to do this, it would take me hours to do what you can do in minutes. Once you have the input file reduced to the smallest possible size that still shows the problem, re-post it and I will take a look at it.
