### ISSUE TITLE
DUMP restart files to harddisk without overwriting previous restart files

### ISSUE THREAD

**Issue by saschagottfried** [firemodels/fds#3346]
If you dig deeper into the use cases that require to stop/resume/restart a simulation you quickly come across the question what happens when restarting the latest snapshot (chid.restart files) is not possible for whatever reasons.
#3254 may serve as an example where this obviously somehow happened.

Since storage is cheap nowadays and storage subsystems reach sequential write rates of 100MB per second, keeping previous RESTART snapshots instead of overwriting them could be considered useful.

Since the RESTART feature as a whole is currently not considered for production environments it may be disabled by default in future. If users or third party applications (like Pyrosim) make use of this feature, multiple snapshots could serve as a mitigation for corrupted files. 

Third-party application could ask users for the number of snapshots. Given the time (T_END) the application translates the restart configuration into DT_RESTART values. Resuming usually would mean to load the most recent RESTART snapshot. If desired by user the application could load one of the other snapshots to resume simulation.

**Comment by mcgratta** [comment]
RESTART is a somewhat fragile feature. I am hesitant to make the RESTART logic more complicated unless there is a significant user need. Is this something that is critical to your use of FDS, or something that might be useful to someone? How many times has a restart failed for you because of a corruption of the file?

**Comment by lu-kas** [comment]
a) if your restart files get corrupted then you have a bigger problem then restart, as all your other data files are in jeopardy as well; you should then check / repair / etc. your file system

b) you can implement your request by having a process watching the created restart files and react on the creation -- this would not need any adoption of fds. i.e. whenever a restart file is created your watch process renames it to a unique name. therefore all following restart dumps will not overwrite anything. to start from a snapshot you rename the chosen file to the default and run fds. 
note: there might be a whole set of files that need to be put aside, not only the *.restart files

**Comment by saschagottfried** [comment]
This issue is not a call for action but some quick notes on important aspects (from my point of view). I know Kevin's position regarding changes to RESTART logic. Just label this issue as 'low priority'.

Kevin, you asked for a use case: A production environment with regular scheduled maintenance will affect long-running FDS cases. Environments like these require an application that is able to save its state and to resume at later time. A mature ability to restart/snapshot application state is a crucial requirement to shift workloads to cloud environments like AWS or Azure where the cloud provider will schedule maintenance windows.

Lukas, my use of "corrupt" seems to be misleading. I basically meant the state of data that happened to the guy in issue #3254

**Comment by rmcdermo** [comment]
I would point out that a user forum question today

https://groups.google.com/forum/#!topic/fds-smv/qJa5CzHqNqA

basically echoed the need for this feature.  I don't think it would be too intrusive to optionally add a time stamp or index to a restart file.  The user could then rename it to CHID.restart if they ever needed to use it.

**Comment by drjfloyd** [comment]
I think this should be an option and not the default. restart files are massive and on a cluster using common disk storage, keeping all restart files would quickly consume massive quantities of space.

**Comment by rmcdermo** [comment]
Absolutely agree.  That's why I said "optionally add a time stamp"  :)

**Comment by mcgratta** [comment]
I'm going to close this issue. Restarting is simply too fragile to add more complexity to it. I'd rather just ensure that restart works, and not complicate it by adding time stamps.
