### ISSUE TITLE
FDS for EPS melt problem 

### ISSUE THREAD

**Issue by zhoubiao1088** [firemodels/fds#3358]
Dear everyone, the latest FDS has added the viscosity vs temperature by RAMP_MU, however, I failed in simulating EPS thermoplastic melt-drip process. Is it impossible to use FDS conduct this melt-drip process ?

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs. I see you cross-posted this question to the forum. There is a reply to your question there.
