### ISSUE TITLE
Performance Problems 6.3.2 vs. 6.1.0

### ISSUE THREAD

**Issue by Bernd-Boiting** [firemodels/fds#3376]
We setup a Dual Opteron with two 6380 CPU's, 128 GB Ram.
We installed FDS 6.1.0 and FDS 6.3.2 in parallel. Both version together with Open MPI v1.8.4.
FDS 6.1.0 runs fine. In direct comparison the same case is up to 8 times slower under 6.3.2. Same encountered with version 6.2.
Any ideas what went wrong, or what to change?

Bernd

**Comment by mcgratta** [comment]
Post the input file. Also, tell me how many time steps each calculation used. The number is near the end of the .out file.

**Comment by Bernd-Boiting** [comment]
Hello,

thanks for your fast reply!

During my tests, I tried to prepare a sample for you, to show up the
problem.

To my surprise 6.3 was always faster than 6.1 …  :0

After some additional tests I deleted all my comments from the original
fds-test-script…..after than 6.3 was as fast as 6.1.

Obviously my comments confused fds…… 6.1 processes the case a bit slower
now….

Best regards,

Bernd

2016-01-17 17:50 GMT+01:00 Kevin McGrattan notifications@github.com:

**Comment by mcgratta** [comment]
Good to hear, thanks for letting me know.

**Comment by Bernd-Boiting** [comment]
Hello,

I must come back to my former mail.

As we say, I am at the end of my Latin……

Simple cases show up performance advantages of Version 6.3 vs 6.1. If it
comes to more complex files, it shows differences in performance.

I just attached the fds-script I processed parallel on the same machine,
but with different fds versions.

6.3 is much slower than 6.1. I first had the idea that this depends on the
turbulence model: 'DYNAMIC SMAGORINSKY'. But it remains if deleted back to
the standard model.

Any Idea?

Best regards,

Bernd

---

&HEAD CHID='halle', TITLE='Beheizung einer Industriehalle'
&TIME T_END=1200.0 /
&MISC TURBULENCE_MODEL='DYNAMIC SMAGORINSKY' /, RESTART=.TRUE.
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,0.0,2.0 /
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,2.0,4.0 /
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,4.0,6.0 /
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,6.0,8.0 /
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,8.0,10.0 /
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,10.0,11.0 /
&MESH IJK=80,80,4,    XB=0.0,20.0,0.0,20.0,11.0,12.0 /
&SURF ID='Abluft', VEL=0.056 /
&VENT XB=00.0,20.0,00.0,00.0,11.5,12.0, SURF_ID='OPEN'/
&VENT XB=00.0,20.0,20.0,20.0,11.5,12.0, SURF_ID='OPEN'/
&VENT XB=00.0,00.0,00.0,20.0,11.5,12.0, SURF_ID='Abluft'/
&VENT XB=20.0,20.0,00.0,20.0,11.5,12.0, SURF_ID='Abluft'/
&SURF ID='Boden', COLOR='GRAY 50' ,NET_HEAT_FLUX  = -0.005 /
&SURF ID='Dach', COLOR='INVISIBLE',NET_HEAT_FLUX  = -0.010 /
&SURF ID='Wand', COLOR='INVISIBLE',NET_HEAT_FLUX  = -0.0125 /
&SURF ID='AK', COLOR='BLUE' /
&OBST XB= 9.75,10.25,9.75,10.0,11.0,11.5, SURF_ID='AK'/
&SURF ID='draller_innen', TMP_FRONT=35, VEL=-9 /
&VENT XB= 9.75,10.0,9.75,10.0,11.0,11.0, SURF_ID='draller_innen'  /
&VENT XB= 10.0,10.25,9.75,10.0,11.0,11.0, SURF_ID='draller_innen'  /
&OBST XB=0.0,20.0,0.0,20.0,0.0,0.1, SURF_ID='Boden'/
&OBST XB=0.0,20.0,0.0,20.0,12.0,12.0, SURF_ID='Dach'/
&OBST XB=00.0,20.0,00.0,00.0,00.0,12.0, SURF_ID='Wand'/
&HOLE XB=00.0,20.0,-0.5,01.0,11.5,12.0 /
&OBST XB=00.0,20.0,20.0,20.0,00.0,12.0, SURF_ID='Wand'/
&HOLE XB=00.0,20.0,19.5,20.5,11.5,12.0,/
&OBST XB=00.0,00.0,00.0,20.0,00.0,12.0, SURF_ID='Wand'/
&OBST XB=20.0,20.0,00.0,20.0,00.0,12.0, SURF_ID='Wand'/
&ISOF QUANTITY='TEMPERATURE', VALUE(1)=20.0 /
&SLCF PBX=10.0, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBX=10.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBX=10.0, QUANTITY='PRESSURE', VECTOR=.TRUE. /
&SLCF PBY=10.0, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBY=10.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBZ=2.0, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBZ=2.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBZ=4.0, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBZ=4.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBZ=8.0, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBZ=8.0, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&BNDF QUANTITY='WALL TEMPERATURE'/
&BNDF QUANTITY='NET HEAT FLUX'/
&TAIL /

2016-01-18 16:23 GMT+01:00 Kevin McGrattan notifications@github.com:

**Comment by mcgratta** [comment]
Why do you choose this way to create the meshes? It is the worst possible choice. You essentially maximize the amount of information that must be communicated between processes. Also, you need to look at the number of time steps -- this might be the cause of the difference in timings. If for some reason the flow field is slightly different, the maximum velocity might be too, and this will change the time step, and hence the number of iterations. 

But before doing this, I suggest you divide the domain in a way that minimizes rather than maximizes MPI communication.

**Comment by mcgratta** [comment]
I ran your case last night. I suggest you completely change the way you have created the meshes. Do not layer the meshes as you have done -- this will only increase numerical error.

**Comment by Bernd-Boiting** [comment]
I share your opinion on the problems concerning the amount of data's which
have to be transferred between the meshes.

The idea was to distribute the whole domain on several CPU's to increase
the performance. Not without taking the mesh boundaries out of sight…..

Building only one mesh forces only one CPU……

What kind of sub meshes would you prefer?

More cubic forms?

Best regards,
Bernd

2016-01-27 14:50 GMT+01:00 Kevin McGrattan notifications@github.com:

**Comment by mcgratta** [comment]
Yes, we typically divide a large rectangular domain by dividing each coordinate direction by 2, 4 and so on. Since in a fire, the vertical direction is important for plume development, we tend to divide the vertical direction only when the number of cells in the vertical is much greater than the number of cells in the x and y sub-divided meshes. Look at the USN_NIST validation cases, for example.
