### ISSUE TITLE
Problem with pressure zone leak to exterior 

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3401]
I am testing the pressure zone leak to exterior. My model has a supply vent and I intended to have a leak of 0.1 m^2 to the exterior. However, when I run the model, the pressure does not reach a steady state, it just keeps increasing.

leak_to_exterior.fds
Generated by PyroSim - Version 2015.4.1214
Jan 26, 2016 4:19:57 PM

&HEAD CHID='leak_to_exterior'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='leak_to_exterior.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0/

&MESH ID='Mesh01', IJK=40,40,40, XB=0.0,10.0,0.0,10.0,0.0,10.0/

&ZONE XB=0.0,10.0,0.0,10.0,0.0,10.0, LEAK_AREA(0)=0.1/

&DEVC ID='Pressure Inner', QUANTITY='PRESSURE', XYZ=5.0,5.0,5.0/
&SURF ID='Supply',
      RGB=26.0,204.0,26.0,
      MASS_FLUX_TOTAL=-1.0/

&VENT SURF_ID='Supply', XB=0.0,0.0,4.5,5.5,4.5,5.5/ Supply Vent

&TAIL /

![leak_to_exterior fds](https://cloud.githubusercontent.com/assets/13338306/12597908/e7fe7088-c44c-11e5-8456-3f605ae1f7db.png)

If I define a SURF with a LEAK_PATH and then an OBST on the zone boundary using that leak surface, the pressure reaches a steady state value of 41.8 Pa, with a flow rate of 1 kg/s (or 0.83 m^3/s) through the leak, as I would expect based on equation 9.6 in the manual.

![leak_example_1000cm2_leak fds](https://cloud.githubusercontent.com/assets/13338306/12598031/86dcf896-c44d-11e5-9899-bf3f107ec3d7.png)

Thanks and hope this is not just an input error,
Dan Swenson

**Comment by mcgratta** [comment]
The location of the leak must be specified. LEAK_AREA is not enough. Is there an example of where LEAK_PATH is not used?

**Comment by dvswenson** [comment]
Kevin,

My interpretation came from reading the User Manual section on Pressure
Zone Leakage. I read the sentence "In this example, a leak exists between
Zone 1 and the exterior Zone 0, and the area of the leak is 0.0001 m2 (1 cm
by 1 cm hole, ..." as meaning that all you needed was the one input line
"&ZONE XB=..., LEAK_AREA(0)=0.0001 /" to define the leak with the
exterior.  I do now see that it says "The first step in this approach...".

It would have helped me if the manual said explicitly that a LEAK_PATH is
required, but it was just my misreading that caused the problem.

All FDS V&V examples I looked at included a LEAK_PATH.

Thanks for your help,

Dan

On Tue, Jan 26, 2016 at 5:05 PM, Kevin McGrattan notifications@github.com
wrote:

> The location of the leak must be specified. LEAK_AREA is not enough. Is
> there an example of where LEAK_PATH is not used?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3401#issuecomment-175285087
> .

## 

Daniel Swenson
Thunderhead Engineering
www.thunderheadeng.com
swenson@thunderheadeng.com
+1.785.770.8511 x103

**Comment by mcgratta** [comment]
Could you reword the manual and submit a pull request.

**Comment by dvswenson** [comment]
I will try.

**Comment by dvswenson** [comment]
Kevin,
I don't like to leave unresolved issues hanging. 

I am sorry, but we do not use LaTeX, so realistically, I will not get this task done. 

Can we just close this case? It is not critical.

Thanks,
Dan Swenson

**Comment by mcgratta** [comment]
I'll just add the text.

**Comment by mcgratta** [comment]
Done
