### ISSUE TITLE
expand POINT keyword on &DEVC to output data for multiple devices

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#3408]
smokeview can visualize velocity profiles using data from &DEVC output if devices are aligned along the x, y or z axes.  Presently an input file would contain a series of &DEVC lines like

&DEVC XYZ=10,0,0,QUANTITY='U-VELOCITY' /
&DEVC XYZ=10,0,0,QUANTITY='V-VELOCITY' /
&DEVC XYZ=10,0,0,QUANTITY='W-VELOCITY' /
&DEVC XYZ=10,0,0,QUANTITY='TEMPERATURE' /

......
......
.....

&DEVC XYZ=10,0,10,QUANTITY='U-VELOCITY' /
&DEVC XYZ=10,0,10,QUANTITY='V-VELOCITY' /
&DEVC XYZ=10,0,10,QUANTITY='W-VELOCITY' /
&DEVC XYZ=10,0,10,QUANTITY='TEMPERATURE' /

where only one of the XYZ coordinates varies in this case the z coordinate.  Four detector trees with ten U, V, W and temperature device lines sensors each  would require 160 &DEVC lines. 

The POINTS keyword could be used to reduce the number of input lines making it easier to make changes as in

&DEVC XYZ=10,10,0,0,0,10,POINTS=3QUANTITY='U-VELOCITY' /
&DEVC XYZ=10,10,0,0,0,10,POINTS=3QUANTITY='V-VELOCITY' /
&DEVC XYZ=10,10,0,0,0,10,POINTS=3QUANTITY='W-VELOCITY' /
&DEVC XYZ=10,10,0,0,0,10,POINTS=3QUANTITY='TEMPERATURE' /

Verification/WUI/velocity_profile.fds is a simple test case showing just 1 vertical detector tree.  WUI/Verification/wind_test3.fds is a more complicated test case showing 4 vertical and 1 horizontal (along the y axis) detector tree

**Comment by gforney** [comment]
smokeview that implements velocity profile visualization for devices is located at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

**Comment by rmcdermo** [comment]
Glenn,
So, if I understand you correctly, you are just asking that we have an option that POINTS write out to the _devc file at DT_DEVC instead of a time averaged _line file, correct?

**Comment by gforney** [comment]
yes. I'll leave it to you whether your write out to one or the other or both

On Thu, Jan 28, 2016 at 11:55 AM, Randy McDermott notifications@github.com
wrote:

> Glenn,
> So, if I understand you correctly, you are just asking that we have an
> option that POINTS write out to the _devc file at DT_DEVC instead of a time
> averaged _line file, correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3408#issuecomment-176281061
> .

## 

Glenn Forney

**Comment by mcgratta** [comment]
I can do this -- I will add a flag that directs a DEVC line with POINTS to be a time history or time-averaged "line" file.

**Comment by mcgratta** [comment]
Done -- try it. Just add TIME_HISTORY=.TRUE. to the DEVC line that has POINTS>1.
