### ISSUE TITLE
Segmentation error on OSX

### ISSUE THREAD

**Issue by andrewPod** [firemodels/fds#3423]
A segmentation fault occurred when running FDS file on OSX. What does it means? Thanks

Mesh      1 is assigned to MPI Process      0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source  
FDS                000000010DA1846A  Unknown               Unknown  Unknown
FDS                000000010DA16861  Unknown               Unknown  Unknown
FDS                000000010D93A981  Unknown               Unknown  Unknown
FDS                000000010D93A7B6  Unknown               Unknown  Unknown
FDS                000000010D8BB010  Unknown               Unknown  Unknown
FDS                000000010D8C786E  Unknown               Unknown  Unknown
libsystem_platfor  00007FFF9DEA4EAA  Unknown               Unknown  Unknown
FDS                000000010D54DD1B  Unknown               Unknown  Unknown
FDS                000000010D562089  Unknown               Unknown  Unknown
FDS                000000010CEDF3AE  Unknown               Unknown  Unknown

**Comment by drjfloyd** [comment]
Most likely this means some input error that we are not trapping while
reading and processing the input file. Greatly simplify your input until
the error no longer exists then slowly add back until the error occurs. See
if you can determine what line causes the error.

**Comment by andrewPod** [comment]
Ok now it works, too much mesh cells (5 million), now reduced to 75,000. Thanks a lot

**Comment by mcgratta** [comment]
How much memory (RAM) do you have? The 64 bit version of FDS will work with 5 million cells, as long as you have enough memory.

**Comment by andrewPod** [comment]
8 GB RAM

**Comment by drjfloyd** [comment]
Depending on the details of the simulation you need somewhat more than 1 Gb / million cells of available RAM.  With 8 Gb and 5 million cells, it is likely you ran out of memory.

**Comment by drjfloyd** [comment]
closing
