### ISSUE TITLE
High temperatures of water drops

### ISSUE THREAD

**Issue by shostikk** [firemodels/fds#3434]
Simplified version of the case discussed in thread 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/DkiUmfI08AU/RCvQBM_uBAAJ

Some droplets are high temperature.

[mist.fds.txt](https://github.com/firemodels/fds-smv/files/116284/mist.fds.txt)

**Comment by drjfloyd** [comment]
I have been playing with this a little as well. It appears to be an overshoot issue from the very small drop size. Slightly larger drops and everything seems to behave fine. The issue looks like it is related to the assumption that TMP_G is fixed when we compute TMP_DROP_NEW allowing TMP_DROP_NEW to overshoot the gas temperature.  Probably need to dust off (again) the equilibrium evap method Randy wrote some notes on.

**Comment by rmcdermo** [comment]
Jason,

First step would be to get T_EQ and Y_EQ as gas phase output quantities
(thought you had worked on that, but do not see it).  Then we could see if
GET_EQUILIBRIUM is behaving.

**Comment by mcgratta** [comment]
Don't we let the temperature change as we process droplets? Search on `TMP_INTERIM` in `part.f90`. This variable is set to `TMP` (the gas temperature from the EoS) at the start of the processing loop, and it is updated with each droplet. Before I made some changes to how we handle the divergence term, we just used `TMP` to hold the interim gas temperature.

**Comment by drjfloyd** [comment]
Randy, We did have it at one point but it was stripped at your or Kevin's
request in one of the recent releases in a purge of code not actively being
used. I will need to add it back.

Kevin,

If the drop subtimesteps we update the gas temperature. We don't check to
see how far the drop has overshot the current gas temp. In this case in the
first time step after injection the drop cools by evaporation and becomes
very small. In the next time step as it is now cooler than the gas, it is
heating up and over shoots the gas temp. If I add a line to prohibit this
(a hack just for testing) the problem goes away.

**Comment by mcgratta** [comment]
[This commit](https://github.com/firemodels/fds-smv/pull/3525) adds a new wrinkle to this issue. Let's talk about it when you have a chance.

**Comment by drjfloyd** [comment]
I have pushed up the equilibrium routine discussed above under the flag EQUILIBRIUM_MODEL on mist (note at the moment the routine cannot handle drops on walls). The new evaporation routine avoids the problem in Simo's example (the case injects 10 C mist into 30 C air).

Below are two images with and without the routine. Without we see temperatures increasing over the background temperature of 30 C.  With the new routine, we only see temperatures that are colder .

![mist_a_0010](https://cloud.githubusercontent.com/assets/12799217/13927881/e8b48a88-ef69-11e5-81e6-8c9c5257b9d5.png)
![mist_0010](https://cloud.githubusercontent.com/assets/12799217/13927880/e8b34baa-ef69-11e5-87b2-7a734df63c96.png)

**Comment by Thibauddu** [comment]
Hello everyone,
Following drjfloyd suggestion, here are two examples of simple simulation models with fuel spray ignition that return "Numerical Instability" for 7_2 and "Numerical instability for Particle Energy transport" for 7_3.
It is about two concentric solids with inlet/outlet, and a fuel spray projecting small (50 microns) N-DECANE droplets with high speed towards the inlet. 

I put comments in 7_2, so it should be the easiest one to begin with. 

[7_2.txt](https://github.com/firemodels/fds-smv/files/261462/7_2.txt)
[7_3.txt](https://github.com/firemodels/fds-smv/files/261471/7_3.txt)

 Thanks a lot for your work!
Thibaud

**Comment by rmcdermo** [comment]
Jason,
Have you tried these test cases with latest code?

**Comment by drjfloyd** [comment]
I am pretty sure I did.  I can run them again.

**Comment by mcgratta** [comment]
Simo -- can you check to see if the original issue is resolved?

**Comment by shostikk** [comment]
Yes, the original issue is solved. I cannot find files for cases 7.2 and 7.3.

 Current Date     : September  8, 2017  13:54:00
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-2398-g1aa88f9-dirty
 Revision Date    : Sun Sep 3 13:05:09 2017 -0400
 Compilation Date : to 07.09.2017  08:23
