### ISSUE TITLE
duplicate slice files 

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#3441]
discovered an interesting problem that has probably been around for years.  I have been making a lot of cleanup type changes in smokeview's menu'ing code.  One of my tests was to load a multi-slice (collection of slice files in on plane treated as one item by smokeview) and then go back and unload individual slice files.  When I did this, the file I unloaded seemingly did not go away - I thought I screwed up my menu'ing changes.

To see what I am talking about
1. run the case Verification/Visualization/mplume5c8.fds  .  This is an 8 mesh case.  
2. Load a temperature multi-slice at y=0.8 .
3. now unload a slice by going to Load/Unload>Slice File>Unload>pick a slice

The unload at first glance doesn't do anything.  However, if you look more closely at the scene you'll see that the color in the slice you removed changed slightly - becomes more transparent compared to slices in other meshes.

Here is what is going on.  The location y=0.8 is on  mesh boundary.  FDS is generating two sets of duplicate slices -  4 slices for meshes where ymin=0.8 and another 4 slices for meshes with ymax=0.8.  I've fixed smokeview.  It now removes duplicate slices if present when displaying multi-slices.  It will now only display 4 slices for the example above.

Question is how do you want to handle this in FDS.  You could just do nothing and let smokeview deal with the duplicate slices.  For large cases though say 8192 meshes FDS would generate a lot of extra slice files resulting in a lot of extra work.  (I estimate for a 8192 mesh case configured as 16 meshes x 16 meshes x 32 meshes would generate 1024 slice files for a given vertical plane when it would only need to generate 512 ).

No need to do anything for me/smokeview - just an fyi for you when you are modifying FDS to make it more efficient for large cases.

**Comment by drjfloyd** [comment]
For a slice at and parallel to a mesh boundary, do we want FDS to check for an adjacent mesh and then do the slice for the finer mesh (if one exists) and if no finer mesh is present just do a slice for the lower numbered mesh?

**Comment by rmcdermo** [comment]
This is something I've wanted to fix in FDS for a long time, but have just been lazy about doing it.  Since I tend to use CC slices the hack I usually put the slice through the cell center and this avoids duplicates.

**Comment by mcgratta** [comment]
Trouble is -- there's no guarantee that the two meshes span the same area. We could inadvertently remove some coverage. An easy fix on the input side would just be to choose your PBY or whatever to be a mm inside the mesh you want. Currently FDS uses >= or <= to choose slices for each mesh. That gives us two sets.

**Comment by rmcdermo** [comment]
If the mesh interface is a refinement interface, then having 2 slices is actually a "feature" in some ways.  I could imagine wanting to check that the average of the refined region matches the coarse.

But most of the time I run into the problem that I am doing a MULT for and MPI job and the PBY=0 plane is also a uniform mesh interface.  In that case, we do not need the extra slice files.

**Comment by gforney** [comment]
in smokeview I tag a slice as a duplicate only if the "bounding box " of
the two slices match, so don't I'll lose any coverage - I'm not giving any
preference to grid coarseness though on which slice to keep

On Fri, Feb 5, 2016 at 9:50 AM, Kevin McGrattan notifications@github.com
wrote:

> Trouble is -- there's no guarantee that the two meshes span the same area.
> We could inadvertently remove some coverage. An easy fix on the input side
> would just be to choose your PBY or whatever to be a mm inside the mesh you
> want. Currently FDS uses >= or <= to choose slices for each mesh. That
> gives us two sets.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3441#issuecomment-180387083
> .

## 

Glenn Forney

**Comment by mcgratta** [comment]
I have used this "bug" as a feature. When testing the integrity of the flow field at mesh boundaries, I load both vector slices and see if the two sets of arrows are perfectly aligned. I wouldn't want to lose this diagnostic. How about an option in Show/Hide to show all slices, right after the option to show slices within obstructions?

**Comment by gforney** [comment]
I had forgotten about that.  I'll make the remove remove duplicate option in smokeview configurable so that we don't lose what we had

**Comment by gforney** [comment]
you can now specify in smokeview under the Multi-Slice and Multi vector slice menus how smokeview deals with duplicate slices.  options are keep all, keep slice on coarse mesh, keep slice on fine mesh.  The default for vector slice files is to keep all (so you can continue to debug).  The default for regular slice files are to keep only slices on the fine mesh. smokeview's implementing this are located at

https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

The case Verification/Visualization/mplume5c2fds can be used to test this (two meshes, one mesh twice as refined as the other)
