### ISSUE TITLE
Possible instability in HVAC routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3443]
We're running the validation cases for a minor release. One case failed with a numerical instability:

```
Validation/PRISME/FDS_Input_Files/PRS_SI_D2.fds
```

The case fails after about 18 h of run time, or about 1000 s out of 3300 s. The failure occurred at the incoming air vent, which is connected to an HVAC network. I ran the case again, saving the `DUCT VOLUME FLOW` and `DUCT MASS FLOW` at the inlet and outlet. There is a single sealed room with a single inlet and outlet. I saved the data at each time step:
[PRS_SI_D2_devc.xlsx](https://github.com/firemodels/fds-smv/files/119313/PRS_SI_D2_devc.xlsx)
The second time I ran the case, with a slightly different version, I got a seg fault at the line

```
IF (HVAC_SOLVE) THEN
   IF (FIRST_PASS .AND. N_MPI_PROCESSES>1) CALL EXCHANGE_HVAC_BC
   IF (PROCESS(1)==MYID) CALL HVAC_CALC(T,DT,FIRST_PASS)    <----- this line
   IF (N_MPI_PROCESSES>1) CALL EXCHANGE_HVAC_SOLUTION
ENDIF
```

I only have that line number, no other details.

I'll keep banging away at it, but if you see something that is off, or can suggest something, let me know. Thanks.

**Comment by drjfloyd** [comment]
That line isn't particularly helpful. That is just the call to the HVAC solver.  Probably something is going off the rails in the solver and we are trying to access some thermophysical property outside of its bounds.

One options is to take a look at the .out file and see what the typical timestep is at that point in time. Try setting DT_HVAC to be larger than that (say a factor of 10).  See if that helps.

A second options is looking at the input file, the duct network is more complicated than it needs to be. For example from node R2_I (inlet) to N7 to N6 to N5 to N4 is all just one single duct run with some of those ducts having zero loss (can make the solver unhappy when the flow is being computed rather than specified).  These could be replaced by a single length of duct with the losses scaled to account for area changes.

**Comment by mcgratta** [comment]
OK, I'll try DT_HVAC=0.1, and then look at the ducts. The network was specified as part of a validation exercise.

**Comment by mcgratta** [comment]
I've been playing with a few things on this. One concern is that this case involves a single compartment that has no OPEN boundaries. It has a leak, and the inlet and outlet. We are using `H(I,J,K)` or `HS(I,J,K)` to establish the pressure at the inlet and outlet nodes of the HVAC routine. But I don't know how `H` is "grounded". In cases with OPEN boundaries, `H` is zero at the OPEN boundary. Without an OPEN boundary, `H` is accurate up to an additive constant. I'm going to try this case using only `P0(z)` at the inlet and outlet to see if that matters.

**Comment by drjfloyd** [comment]
I don't just use P0(Z) for HVAC since that won't account for stagnation pressure at the vent (for example an HVAC inlet with a ceiling jet impinging on it) or in the case of multiple rooms with an OPEN boundary it won't account for local pressure rises in individual compartments. I have found that just using P0 does make the HVAC a lot more stable, but at the price of greatly limiting the types of cases it can be used for.

**Comment by rmcdermo** [comment]
Have you considered volume averaging H within a compartment.  That would
solve the multiple rooms problem.

**Comment by drjfloyd** [comment]
How is FDS to know what subvolume constitutes a compartment?

**Comment by mcgratta** [comment]
H is averaged over the face of the vent. It's being done right -- my only question is whether H floats according to an arbitrary constant.

**Comment by rmcdermo** [comment]
I guess this would have to be an XB parameter on HVAC.

**Comment by drjfloyd** [comment]
XB only works if all compartments are rectangular parallelepipeds. I would consider that too severe a limitation.

**Comment by rmcdermo** [comment]
Another option is time averaging over the VENT face.

**Comment by drjfloyd** [comment]
Time averaging is already done via HVAC_PRES_RELAX (which is another parameter that could be tried for this case).

**Comment by rmcdermo** [comment]
Is this another of those cases with a very small L of duct which shows up
the denominator of the matrix system, perhaps making it ill-conditioned?

**Comment by mcgratta** [comment]
Possibly -- even the noisy HRR makes the pressure field noisy, and I don't know to what extent this is real or a ramification of the low Mach number assumption. But let's wait and see if changing things has an impact on the stability of this particular case.

**Comment by drjfloyd** [comment]
The L is why I added DT_HVAC.  Making that larger in effect makes L bigger for all ducts.

**Comment by mcgratta** [comment]
I reran the original case that had a numerical instability. In one, I set DT_HVAC=0.1. This ran successfully, even though there were a few wild swings in the inlet flow rate. For the other case, I modified `hvac.f90` to only use `P0(Z)` rather than `P0(Z)+...` This case failed with a numerical instability. Next, I'll try simplifying the HVAC definition.

**Comment by CakeDelivery** [comment]
[Online Cake Delivery](http://www.cakengift.in/)
[Cake Delivery in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Cake Delivery in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)

**Comment by CakeDelivery** [comment]
[Cake Delivery in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Cake Delivery in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Cake Delivery in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)
[Online Birthday Cake](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)

**Comment by CakeDelivery** [comment]
[Online Birthday Cake Delivery](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)
[Order Cake in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Order Cake in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)
[Order Cake in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Order Cake in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Order Cake in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)

**Comment by mcgratta** [comment]
This case appears to have been solved.
