### ISSUE TITLE
-noblank breaks vector slice

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3444]
Glenn,
No good deed goes unpunished.  The attached case fails with -noblank with SMV 6.3.3

dante:Pyrosim rmcdermo$ smv Sandia_FLAME -noblank

Smokeview 6.3.3 - Jan  5 2016

Version: 6.3.3
Smokeview (64 bit) Build: Git-r6-0-g9379bf1
Platform: OSX64
Build Date: Jan  5 2016

I put the case in the following directory on burn

/home4/rmcdermo/GitHub/fds-smv_rmcdermo/Validation/Sandia_Plumes/Save_for_Glenn/Sandia_FLAME.smv

**Comment by gforney** [comment]
missed trapping for a couple of NULL pointers - try smokeview posted here
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

**Comment by gforney** [comment]
it is blowing up for me also in release mode - works in debug mode.  bugs are easier to fix when this is reversed!

**Comment by rmcdermo** [comment]
Nothing is ever easy!

**Comment by gforney** [comment]
think the problem we were seeing was related to the duplicate slice remove code I put in recently (again no good deed goes unpunished!).  I've rewritten this code making it simpler.  Try smokeview's here
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

**Comment by rmcdermo** [comment]
Glenn,
This seems to work.  Thanks!

**Comment by gforney** [comment]
fyi:  I've updated the code some more - I'm about to put in another pull
request.  Hopefully we won't go backwards

On Mon, Feb 8, 2016 at 3:41 PM, Randy McDermott notifications@github.com
wrote:

> Glenn,
> This seems to work. Thanks!
> 
> On Sat, Feb 6, 2016 at 11:02 AM, Glenn Forney notifications@github.com
> wrote:
> 
> > think the problem we were seeing was related to the duplicate slice
> > remove
> > code I put in recently (again no good deed goes unpunished!). I've
> > rewritten this code making it simpler. Try smokeview's here
> > 
> > https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/firemodels/fds-smv/issues/3444#issuecomment-180798087>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3444#issuecomment-181525276
> .

## 

Glenn Forney

**Comment by gforney** [comment]
smokeview's that implement new FDS keyword mentioned in pull request 3450
are located at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

note:  you don't have to rerun your cases to take advantage of this new smokeview feature .  Just add the following to your .smv file (this will let you double click on the .smv file without needing to type -noblank at the command line)

IBLANK
  0

**Comment by CakeDelivery** [comment]
[Online Cake Delivery](http://www.cakengift.in/)
[Cake Delivery in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Cake Delivery in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)

**Comment by CakeDelivery** [comment]
[Cake Delivery in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Cake Delivery in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Cake Delivery in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)
[Online Birthday Cake](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)

**Comment by CakeDelivery** [comment]
[Online Birthday Cake Delivery](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)
[Order Cake in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Order Cake in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)
[Order Cake in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Order Cake in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Order Cake in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)

**Comment by rmcdermo** [comment]
I think this is fixed.
