### ISSUE TITLE
Multi-mesh head flux gauge

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3483]
Kevin,

Here is an email I got from James White at UMD.  Can you please have a look?

---

Hi Randy,

I’m having trouble getting heat flux diagnostics to work in the latest FDS builds. If I use the surrogate target input lines (pg 215 of the user guide), the devc.csv output only prints a single row at the initial time step and then doesn’t print any more results (including for all other devices that may be in the input file). The RADIATIVE HEAT FLUX GAS shortcut seems to work fine. Maybe I’m missing something, but can you check this on your end, let me know if it works for you?

Thanks,

James White

[HEAT_FLUX_GAUGE.fds.txt](https://github.com/firemodels/fds-smv/files/128626/HEAT_FLUX_GAUGE.fds.txt)

**Comment by mcgratta** [comment]
The particle for the surrogate target is sitting on the boundary between two meshes. There's a bug related to this. For the moment, just move the particle a tiny bit one way or the other.

**Comment by jameswhite255** [comment]
Thanks Kevin, great catch. I can confirm that adjusting the Y coordinate on the INIT line resolves this issue.

**Comment by CakeDelivery** [comment]
[Online Cake Delivery](http://www.cakengift.in/)
[Cake Delivery in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Cake Delivery in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)

**Comment by CakeDelivery** [comment]
[Cake Delivery in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Cake Delivery in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Cake Delivery in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)
[Online Birthday Cake](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)

**Comment by CakeDelivery** [comment]
[Online Birthday Cake Delivery](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)
[Order Cake in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Order Cake in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)
[Order Cake in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Order Cake in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Order Cake in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)

**Comment by mcgratta** [comment]
Pull request #3606.
