### ISSUE TITLE
Ramp up for mass flux not working properly

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3484]
In this case, if you set TAU_MF to anything but zero, things work properly.

```
&HEAD CHID='scalar' /
&MESH IJK=48,48,48, XB=-2,2,-2,2,0,4 /
&TIME T_END=10. /
&RADI RADIATION=.FALSE. /
&VENT XB=-1,1,-1,1,0,0, SURF_ID='INLET' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&SPEC ID='METHANE' /
&SURF ID='INLET', SPEC_ID(1)='METHANE', MASS_FLUX(1)=10.0, COLOR='RED', TAU_MF(1)=0.0 /
&SLCF PBY=0, QUANTITY='MASS FRACTION', VECTOR=.TRUE., SPEC_ID='METHANE' /
&DEVC XB=-2,2,-2,2,4,4, QUANTITY='MASS FLOW', SPEC_ID='METHANE', ID='MASSFLOWS2' /
&TAIL /
```

**Comment by CakeDelivery** [comment]
[Online Cake Delivery](http://www.cakengift.in/)
[Cake Delivery in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Cake Delivery in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)

**Comment by CakeDelivery** [comment]
[Cake Delivery in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Cake Delivery in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Cake Delivery in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)
[Online Birthday Cake](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)

**Comment by CakeDelivery** [comment]
[Online Birthday Cake Delivery](http://www.cakengift.in/by-occasion/birthday-cakes-339.html)
[Order Cake in Delhi](http://www.cakengift.in/by-city/cake-delivery-in-delhi-333.html)
[Order Cake in Noida](http://www.cakengift.in/by-city/cake-delivery-in-noida-335.html)
[Order Cake in Gurgaon](http://www.cakengift.in/by-city/cake-delivery-in-gurgaon-334.html)
[Order Cake in Ghaziabad](http://www.cakengift.in/by-city/cake-delivery-in-ghaziabad-336.html)
[Order Cake in Faridabad](http://www.cakengift.in/by-city/cake-delivery-in-faridabad-337.html)

**Comment by mcgratta** [comment]
Fixed by not allowing `ONE_D%UW` to be set in `wall.f90` during the `INITIALIZATION_PHASE`.
