### ISSUE TITLE
BNDF and Q_ENTH/Q_TOTAL issue

### ISSUE THREAD

**Issue by dushyant-fire** [firemodels/fds#3490]
[BNDF and Q_TOTAL issue.txt](https://github.com/firemodels/fds-smv/files/133169/BNDF.issue.txt)

Hello,
I had the issue of Q_TOTAL falling 10 to 15 kw below Q_ENTH and not able to understand why this would be happening. I would be glad to have assistance on this.

Although this is not of utmost importance, the smokeview on remote desktop shows a negative incident heat flux even though it never falls so low. the physical machine shows the actual calculated and verified values.

Thank you,
Dushyant.

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
The reason is the calculation of `Q_CONV`, the convective heat flow. This term is u_n_rho_h*A summed over all external boundaries, where u_n is the normal component of velocity, rho is the density, h is the enthalpy, and A the area of a grid cell. In the mass and divergence routines, the actual mass flux is calculated using a recipe known as a flux limiter. These values are not saved so as to save on memory. In the output file, we approximate its value. This would explain why `Q_ENTH` and `Q_TOTAL` are not exactly the same. The actual calculation is energy conserving, but we do not want to save the exact terms for output.

**Comment by dushyant-fire** [comment]
So, The Q_TOTAL is the approximation in the output file which causes this minor difference and Q_ENTH is actively calculated  value which explains the conservation of energy. Thus, approximately Q_CONV (-500)+Q_COND (+450)+Q_RADI(+50) = Q_ENTH (which is around zero)

Thank you for the prompt answer!

**Comment by mcgratta** [comment]
Yes, and Q_CONV cannot be calculated at the end of the time step exactly as it is calculated in the divergence routine because there is alot of extra code we'd have to write to do that, or we'd have to allocate additional memory.

**Comment by dushyant-fire** [comment]
Hello,
I am facing some weird problem when I increase the heat flux from 5 kW/m2 (in the original file) to 100 kW/m2. The BNDF incident heat flux on the walls increase to more than 150-200 kW/m2 with time. Even the Radiative Heat Flux BNDF increase higher than given 100kW/m2 net heat flux. 

I removed the pressure zone so as to allow any leak from doors/walls and see if that would have been the problem, but it doesn't help either. Please advice.

Thank you,
Dushyant.

**Comment by mcgratta** [comment]
Submit a very simple test case that demonstrates the problem.

**Comment by dushyant-fire** [comment]
[Room_100_KW_issue tracker.txt](https://github.com/firemodels/fds-smv/files/155379/Room_100_KW_issue.tracker.txt)

Hi,
Please find attached a simplified case for the issue. The pressure increase inside the room also seems a bit too high. Please advice.

Thank you,
Dushyant.

**Comment by mcgratta** [comment]
No, this is simple:

```
&HEAD CHID='flux' /
&TIME T_END=30 /
&MESH IJK=5,50,50, XB=0.0,0.2,0.0,2.0,0.0,2.0/
&SPEC ID='NITROGEN', BACKGROUND=.TRUE. /
&SURF ID='Source', COLOR='RED',  NET_HEAT_FLUX=100.0, EMISSIVITY=1.0, HEAT_TRANSFER_COEFFICIENT=0. /
&SURF ID='Target', COLOR='BLUE', NET_HEAT_FLUX=0.,    EMISSIVITY=1.0, HEAT_TRANSFER_COEFFICIENT=0., DEFAULT=.TRUE. /
&VENT MB='XMIN', SURF_ID='Source' /
&DEVC ID='q1', QUANTITY='INCIDENT HEAT FLUX', XYZ=0.0,1.0,1.0, IOR= 1 /
&DEVC ID='q2', QUANTITY='INCIDENT HEAT FLUX', XYZ=0.2,1.0,1.0, IOR=-1 /
&TAIL /
```

Another way of specifying an adiabatic boundary is to set `NET_HEAT_FLUX=0`. In this simple case, we have two walls facing each other, one with `NET_HEAT_FLUX=100` and the other 0. I don't think that this is a well-posed problem. FDS is trying to set the temperature on each wall to achieve the desired results. I don't think that is possible. 

Radiation experts weigh in on this.
