### ISSUE TITLE
Pyrosim: Urgent Help, couldn't find a solution severe (157) program exception access violation

### ISSUE THREAD

**Issue by hasanadel88** [firemodels/fds#3522]
Dear Support team and members,
Greetings
Wish you can help me getting this simulation to run. I don't know anything related to programming, I use PYROSIM GUI for that purpose. I did spend more than 40 hours trying to solve what causing severe (157) program exception access violation but without any luck. Really, i'm upset of those endless error messages we face when we are about to deliver the project to client. Don't make my life any harder. I'm eagerly waiting your reply on this.

Attachments
1. The pyrosim PSM file (Uploaded on dropbox)
https://www.dropbox.com/s/d0iu6iz8kjgmzmn/Rev2%20Basements%20B2%20On%20Fire%20Fire%20Scenario%202.psm?dl=0
2. FDS (Uploaded on dropbox)
https://www.dropbox.com/s/m8sp6yi9ksi6p5p/Rev2%20Basements%20B2%20On%20Fire%20Fire%20Scenario%202.fds?dl=0
3. Error Log (Uploaded on dropbox)
https://www.dropbox.com/s/58ojaxj3qqffkiw/Error%20Hassan.log?dl=0

Cluster configurations
2 Identical PCs joined a domain with same exact hardware
Core i7-4790 @3.60 GHZ
Ram: 16 GB
OS: Windows 7 Enterprise 64 bit
Graphic: GeForce GT 740

**Comment by mcgratta** [comment]
This is not a good way to ask for help. You pay nothing for this software and you pay nothing for the support. You should act accordingly.

I cannot access Dropbox. Post a simple version of your input file that clearly demonstrates the problem. Tell me what version of FDS you are using. Do not post the PyroSim file. I will not need it.

**Comment by hasanadel88** [comment]
What is meant by a simple version of the input file? Can I spotlight which part of code has an issue? 

 The error log
Starting FDS: fds.exe...

 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 Mesh      3 is assigned to MPI Process      2
 Mesh      4 is assigned to MPI Process      3
 Mesh      5 is assigned to MPI Process      4
 Mesh      6 is assigned to MPI Process      5
 Mesh      7 is assigned to MPI Process      6
 Mesh      8 is assigned to MPI Process      7
 OpenMP thread   1 of   3 assigned to MPI process      0 of      7
 OpenMP thread   2 of   3 assigned to MPI process      0 of      7
 OpenMP thread   3 of   3 assigned to MPI process      0 of      7
 OpenMP thread   0 of   3 assigned to MPI process      0 of      7
 OpenMP thread   3 of   3 assigned to MPI process      6 of      7
 OpenMP thread   0 of   3 assigned to MPI process      4 of      7
 OpenMP thread   1 of   3 assigned to MPI process      4 of      7
 OpenMP thread   3 of   3 assigned to MPI process      4 of      7
 OpenMP thread   2 of   3 assigned to MPI process      4 of      7
 OpenMP thread   2 of   3 assigned to MPI process      6 of      7
 OpenMP thread   1 of   3 assigned to MPI process      6 of      7
 OpenMP thread   0 of   3 assigned to MPI process      6 of      7
 OpenMP thread   3 of   3 assigned to MPI process      7 of      7
 OpenMP thread   3 of   3 assigned to MPI process      2 of      7
 OpenMP thread   1 of   3 assigned to MPI process      1 of      7
 OpenMP thread   2 of   3 assigned to MPI process      1 of      7
 OpenMP thread   3 of   3 assigned to MPI process      1 of      7
 OpenMP thread   0 of   3 assigned to MPI process      1 of      7
 OpenMP thread   3 of   3 assigned to MPI process      3 of      7
 OpenMP thread   1 of   3 assigned to MPI process      2 of      7
 OpenMP thread   0 of   3 assigned to MPI process      2 of      7
 OpenMP thread   1 of   3 assigned to MPI process      3 of      7
 OpenMP thread   0 of   3 assigned to MPI process      3 of      7
 OpenMP thread   2 of   3 assigned to MPI process      3 of      7
 OpenMP thread   2 of   3 assigned to MPI process      2 of      7
 OpenMP thread   3 of   3 assigned to MPI process      5 of      7
 OpenMP thread   2 of   3 assigned to MPI process      5 of      7
 OpenMP thread   0 of   3 assigned to MPI process      5 of      7
 OpenMP thread   1 of   3 assigned to MPI process      5 of      7
 OpenMP thread   2 of   3 assigned to MPI process      7 of      7
 OpenMP thread   1 of   3 assigned to MPI process      7 of      7
 OpenMP thread   0 of   3 assigned to MPI process      7 of      7
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : February 19, 2016  15:44:08
 Version          : FDS 6.3.2
 Revision         : Git-r5-0-gf5004c4
 Revision Date    : Tue Nov 17 17:14:41 2015 -0500
 Compilation Date : Wed 11/18/2015  01:16 PM

 MPI Enabled; Number of MPI Processes:     8
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.1 for Windows\* OS

 Job TITLE        : 
 Job ID string    : Rev2_Basements_B2_On_Fire_Fire

forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source  
fds.exe            000000013FD31588  Unknown               Unknown  Unknown
fds.exe            000000013FAA1205  MAIN__                    518  main.f90
fds.exe            000000013FA9D91E  Unknown               Unknown  Unknown
fds.exe            00000001401B3A1C  Unknown               Unknown  Unknown
kernel32.dll       00000000774C59ED  Unknown               Unknown  Unknown
ntdll.dll          00000000776FC541  Unknown               Unknown  Unknown
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source  
fds.exe            000000013FD31588  Unknown               Unknown  Unknown
fds.exe            000000013FAA1205  MAIN__                    518  main.f90
fds.exe            000000013FA9D91E  Unknown               Unknown  Unknown
fds.exe            00000001401B3A1C  Unknown               Unknown  Unknown
kernel32.dll       00000000774C59ED  Unknown               Unknown  Unknown
ntdll.dll          00000000776FC541  Unknown               Unknown  Unknown
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source  
fds.exe            000000013FD31588  Unknown               Unknown  Unknown
fds.exe            000000013FAA1205  MAIN__                    518  main.f90
fds.exe            000000013FA9D91E  Unknown               Unknown  Unknown
fds.exe            00000001401B3A1C  Unknown               Unknown  Unknown
kernel32.dll       00000000774C59ED  Unknown               Unknown  Unknown
ntdll.dll          00000000776FC541  Unknown               Unknown  Unknown

Starting Smokeview: C:\Program Files\PyroSim 2015\fds\smokeview.exe...

**Comment by mcgratta** [comment]
This only tells me that the problem is related to line 518 of main.f90. This is a call to a subroutine, which means the problem is somewhere in there. I need the input file to properly diagnose the problem. Post it as a .txt file.

**Comment by hasanadel88** [comment]
[Rev2 Basements B2 On Fire Fire Scenario 2.txt](https://github.com/firemodels/fds-smv/files/138690/Rev2.Basements.B2.On.Fire.Fire.Scenario.2.txt)

Thanks in advance bro

**Comment by mcgratta** [comment]
It will take weeks for me to figure out what is wrong. This input file is very long and complicated. We teach users to start with a simple case and test all the features that you intend to use in the more complicated case. Have you done this? Have you ever run this HVAC network successfully?

**Comment by mcgratta** [comment]
You cannot attach an HVAC VENT to a thin (zero cell thick) OBSTruction.

**Comment by hasanadel88** [comment]
Does you pinpoint vent number 100, I found it splited between two mesh and solved this. Back to main issue, I reconstructed this particular model 2 times and it either not initializing or giving back same errror again. I will try something out and get back to you.

**Comment by mcgratta** [comment]
I spent an entire day finding the problem, and I told you what the problem is. You have attached an HVAC VENT to an OBSTruction that is zero cells thick. I added an error statement to FDS that will trap this error in the next release. In the meantime, go through your input file and eliminate all input lines where HVAC VENTs are attached to thin obstructions.

**Comment by hasanadel88** [comment]
Ok, I did not understand this the first time. I am naive with programming language. I use the pyrosim GUI. can you please explain further how I can find this zero cell thick obstruction or refer to me a specific paragraph where i can understand this matter.  

Sorry for my English bro, I didn't mean to insult you. I may be a culture differences. 

Thanks for your patience

**Comment by hasanadel88** [comment]
Thanks brother. You saved my life. The simulation is now up and running
