### ISSUE TITLE
SCRIPT_FIGURES repo

### ISSUE THREAD

**Issue by szakalboss** [firemodels/fds#3523]
How can I get the SCRIPT_FIGURES needed to compile verification report?

the repository blaze.el.nist.gov [129.6.160.230] is not accessible/responding therefore copy_fds_figs.sh script fails

**Comment by gforney** [comment]
short answer: https://drive.google.com/folderview?id=0B_wB1pJL2bFQUlJwMmNfaHlqME0&usp=sharing

long answer: got the FDS-SMV github page https://github.com/firemodels/fds-smv
click on Firebot build status link
click on Manuals link

figures are in FIGURES directory

**Comment by szakalboss** [comment]
many thx
