### ISSUE TITLE
Radiation discretization

### ISSUE THREAD

**Issue by JWWilliamson** [firemodels/fds#3533]
I have noticed that there is a greater discretization fluctuation of the "INTEGRATED INTENSITY" from a steady fire source along the normal grid directions. See the first image below.
It appears as though the radiation traveling normal to a rectilinear grid is focused or radially collimated when the solid angle is close to a normal direction. The effect is less as the angle deviates from normal (say between 10 and 80 degrees in the plane) or if you increase the resolution substantially. My thoughts on this is that the normal directions pass through single rectilinear cell faces, and never really interact with an adjacent cell very often. However, the off-normal directions pass diagonally through grid cells and thus interact with multiple grid cells, spreading the radiation into a more uniform pattern. 

My suggestion is to increase the resolution near the normal angles (0, +/-pi/2, +/-pi) to minimize the near normal angle focusing. This approach can be defined to maintain the symmetric discretization, and the factor of 4 in angles as described in Section 6.2 of the Technical Reference Guide. I have no idea if this will work with the existing numerical scheme which seems to use equal solid angle increments in the discretization. The current solution to this appears to be using more "NUMBER_RADIATION_ANGLES" up to about 600 from the default 100. I feel that this could be optimized a little better, and a "good" solution could be achieved with 200-300 angles if the normal directions are improved in the discretization. Perhaps a factor of 2 to 3 in the near normal directions, or something fancy like a continuously variable discretization based on trigonometric functions of the planar angles.

The following fires are 1MW with 1m by 1m square fire vent on the floor, adjacent to a wall. Only the floor and a single wall are included and the other boundaries are open. 

The following image is a steady fire adjacent to a wall with NUMBER_RADIATION_ANGLES=200 (5 kW/m^2 highlighted for emphasis)
![wnc_test_0145](https://cloud.githubusercontent.com/assets/17410570/13223792/bac50840-d953-11e5-88cf-c00629c8580c.png)

The following image is the same fire adjacent to a wall with NUMBER_RADIATION_ANGLES=600 (5 kW/m^2 highlighted for emphasis)
![wnc_test_0145](https://cloud.githubusercontent.com/assets/17410570/13223800/c254b542-d953-11e5-81f9-50d7afe1c437.png)

The pattern is persistent over time, and averaged quantities. I consider this to be a low priority, since there is a reasonable workaround.

**Comment by mcgratta** [comment]
Simo Hostikka wrote the radiation solver. I don't know how easy or difficult it is to do what you are suggesting, so I will let SImo comment.

**Comment by shostikk** [comment]
This should be fairly easy to do. 
Can you suggest an analytical scaling function that could control the level of no uniformity with a single parameter?

**Comment by JWWilliamson** [comment]
That was more of a pie in the sky suggestion, but thinking about it for a second you could do something like:

dtheta = dtheta_uniform \* (1.5 - (cos(theta))^2)
same for phi

That should give approximately the same number of discretizations (mean of 1), while making the angle increment approximately half near the cell normal directions and approximately double near 45 degrees from the normals.

**Comment by rmcdermo** [comment]
We've known about the star patter for a long time.  This should not be done
cavalierly.  What is being described is a numerical diffusion effect.  The
effect should be quantified as a function of the numerical parameters: grid
size (each direction), solid angle size, solid angle direction.  We also
need non-trivial analytical solutions to test against or very high
resolution numerical solutions.  If our goal is a smooth, diffuse radiation
solution, this can be accomplished with a simpler model.  Our goal should
also include an accuracy criterion, again, for a non-trivial problem.

**Comment by JWWilliamson** [comment]
I agree, be careful about implementing this. Nothing is currently broken, and the results are pretty reasonable for high fluxes. 

My thought about this is if you can achieve the same accuracy with a non-regular angular grid at 200 angles, as you can with a regular grid with 600 angles, then it makes sense. Provided it doesn't break something. I simply observed that the numerical diffusion is most significant in the cell normal directions, so maybe put more resolution there to make the total distribution of radiation more uniform. The cell normal direction is very important for most engineering level applications.

FYI, the simulation I provided is a 4 cm grid (D*/dx = 24) so it is pretty well-resolved. I have no idea what would happen at a coarser grid.

**Comment by rmcdermo** [comment]
I think we all agree on the goal.  But there is a not-so-obvious pitfall.
Achieving accuracy for a trivial problem can lead us in the wrong
direction.  In the case you presented (which I commend you for looking at!)
you have spherical symmetry.  If we really wanted a scheme to achieve good
spherical symmetry only, there are other methods besides discrete ordinates
(spherical harmonics).  Attached is a thesis claiming to combine the two.
I have not read it, just a quick Google search.  The point is there is a
lot of involved, but we have options.  I'd like to think about this
carefully before we jump into any modifications.

https://etd.ohiolink.edu/rws_etd/document/get/osu1308244319/inline

**Comment by shostikk** [comment]
I think FDS' radiation solver has stronger ray effect than it should. Some time ago someone showed a calculation of our radiation-in-box case with another code and their result was smoother. 

Tricks like this can point us towards the possible issue with our FVM numerics. 

SHDOM and things like that need much bigger effort and would probably have high value for scattering media.

**Comment by rmcdermo** [comment]
There may be nothing at all wrong with your numerics.  Someone else may
have played a trick to get a smoother solution for a trivial problem.  I am
arguing that is not a good thing.  If we want a smooth solution for a point
source in a box, we would just use p1.

**Comment by rmcdermo** [comment]
Please do not misunderstand me: I am all in favor of thinking about this.
But their is danger in solving one problem to the detriment of others.  In
scalar transport, for example, if we applied Godunov to all fluxes just
because it fixed the problem at a jump discontinuity, we would have a
terrible transport solver.  We need intelligent schemes that achieve the
accuracy we need, plus obey certain limiting constraints.

**Comment by JWWilliamson** [comment]
I have been looking at this a little more, and I think this is a minor issue that mostly impacts visualization. There is no problem with numerics that I can see, and the ray effect is similar to what others report (reading Randy's reference). I have done some quantitative comparisons of the results, and they are remarkably similar, despite the appearance of the images in my original request and below. Still, the pattern seems persistent to me, so there may be a small value to changing the discretization of the angles of the rays. 

Here are two more examples, same fire, same basic geometry, but I added another wall and placed the fire in the corner. Also added some reference grid lines. The results look great in the off-normal directions, but there is still a persistent ray effect in the near cell-normal directions. From an engineering application perspective, I would prefer that there is greater accuracy in the near cell-normal directions because that is where most applications will place their targets/devices. Overall, the difference is small.

The following image is a steady fire adjacent to a wall with NUMBER_RADIATION_ANGLES=200 (5 kW/m^2 highlighted for emphasis)
![wnc_test_1000](https://cloud.githubusercontent.com/assets/17410570/13428869/2c924540-df8b-11e5-9f86-db5701651bb2.png)

The following image is a steady fire adjacent to a wall with NUMBER_RADIATION_ANGLES=600 (5 kW/m^2 highlighted for emphasis)
![wnc_test_1000](https://cloud.githubusercontent.com/assets/17410570/13428878/378b429e-df8b-11e5-918a-657106e9a519.png)

**Comment by mcgratta** [comment]
We can try clustering the solid angles at 0, pi/2, pi, and 3*pi/2. Currently, the number of angles in the longitudinal direction is a multiple of 4. Can you provide a formula for the lower and upper bound of each solid angle, at least in the longitudinal direction? We'll continue, for now, to divide the vertical angle (pole to pole) uniformly.
