### ISSUE TITLE
After 666 Seconds / severe (157) program exception access violation

### ISSUE THREAD

**Issue by hasanadel88** [firemodels/fds#3570]
Before I was having a issue causing the simulation not to start [(Case#3522)](https://github.com/firemodels/fds-smv/issues/3522#issuecomment-186235676) and giving the following error message severe (157) program exception access violation. Mr. mcgratta guided me to solve this issue, it was due to attachin an HVAC VENT to a thin (zero cell thick) OBSTruction. I eliminated all input lines where HVAC VENTs are attached to thin obstructions as he suggest. Simulation started with no problem until reached 549/1200 Sec

Same error showed up again and simulation stopped. I tried resuming the cluster simulation and it continued until 602 Seconds and stopped again showing same error message. For second time tried resuming the simulation and it continued until 666 seconds and stopped again.

I also noticed remaining time was tripled before stopping

Here is the updated fds file 
[Model15.txt](https://github.com/firemodels/fds-smv/files/150523/Model15.txt)

Cluster configurations
2 Identical PCs joined a domain with same exact hardware
Core i7-4790 @3.60 GHZ
Ram: 16 GB
OS: Windows 7 Enterprise 64 bit
Graphic: GeForce GT 740

Thanks in advance

Error message

Starting FDS: fds.exe...

 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 Mesh      3 is assigned to MPI Process      2
 Mesh      4 is assigned to MPI Process      3
 Mesh      5 is assigned to MPI Process      4
 Mesh      6 is assigned to MPI Process      5
 Mesh      7 is assigned to MPI Process      6
 Mesh      8 is assigned to MPI Process      7
 OpenMP thread   3 of   3 assigned to MPI process      0 of      7
 OpenMP thread   0 of   3 assigned to MPI process      0 of      7
 OpenMP thread   1 of   3 assigned to MPI process      0 of      7
 OpenMP thread   2 of   3 assigned to MPI process      0 of      7
 OpenMP thread   2 of   3 assigned to MPI process      2 of      7
 OpenMP thread   1 of   3 assigned to MPI process      2 of      7
 OpenMP thread   3 of   3 assigned to MPI process      2 of      7
 OpenMP thread   0 of   3 assigned to MPI process      2 of      7
 OpenMP thread   2 of   3 assigned to MPI process      6 of      7
 OpenMP thread   1 of   3 assigned to MPI process      4 of      7
 OpenMP thread   3 of   3 assigned to MPI process      7 of      7
 OpenMP thread   2 of   3 assigned to MPI process      7 of      7
 OpenMP thread   1 of   3 assigned to MPI process      7 of      7
 OpenMP thread   0 of   3 assigned to MPI process      7 of      7
 OpenMP thread   0 of   3 assigned to MPI process      5 of      7
 OpenMP thread   1 of   3 assigned to MPI process      5 of      7
 OpenMP thread   3 of   3 assigned to MPI process      5 of      7
 OpenMP thread   2 of   3 assigned to MPI process      5 of      7
 OpenMP thread   3 of   3 assigned to MPI process      6 of      7
 OpenMP thread   0 of   3 assigned to MPI process      6 of      7
 OpenMP thread   1 of   3 assigned to MPI process      6 of      7
 OpenMP thread   2 of   3 assigned to MPI process      4 of      7
 OpenMP thread   2 of   3 assigned to MPI process      1 of      7
 OpenMP thread   0 of   3 assigned to MPI process      4 of      7
 OpenMP thread   3 of   3 assigned to MPI process      4 of      7
 OpenMP thread   1 of   3 assigned to MPI process      1 of      7
 OpenMP thread   0 of   3 assigned to MPI process      1 of      7
 OpenMP thread   2 of   3 assigned to MPI process      3 of      7
 OpenMP thread   1 of   3 assigned to MPI process      3 of      7
 OpenMP thread   3 of   3 assigned to MPI process      3 of      7
 OpenMP thread   0 of   3 assigned to MPI process      3 of      7
 OpenMP thread   3 of   3 assigned to MPI process      1 of      7
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : February 28, 2016  22:42:08
 Version          : FDS 6.3.2
 Revision         : Git-r5-0-gf5004c4
 Revision Date    : Tue Nov 17 17:14:41 2015 -0500
 Compilation Date : Wed 11/18/2015  01:16 PM

 MPI Enabled; Number of MPI Processes:     8
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.1 for Windows\* OS

 Job TITLE        : 
 Job ID string    : Model15

 Time Step:  65600, Simulation Time:    600.25 s
 Time Step:  65700, Simulation Time:    601.24 s
 Time Step:  65800, Simulation Time:    602.63 s
 Time Step:  65900, Simulation Time:    604.55 s
 Time Step:  66000, Simulation Time:    606.74 s
 Time Step:  66100, Simulation Time:    608.42 s
 Time Step:  66200, Simulation Time:    610.65 s
 Time Step:  66300, Simulation Time:    612.95 s
 Time Step:  66400, Simulation Time:    615.27 s
 Time Step:  66500, Simulation Time:    617.57 s
 Time Step:  66600, Simulation Time:    620.07 s
 Time Step:  66700, Simulation Time:    622.34 s
 Time Step:  66800, Simulation Time:    624.61 s
 Time Step:  66900, Simulation Time:    626.73 s
 Time Step:  67000, Simulation Time:    628.62 s
 Time Step:  67100, Simulation Time:    630.57 s
 Time Step:  67200, Simulation Time:    632.33 s
 Time Step:  67300, Simulation Time:    634.08 s
 Time Step:  67400, Simulation Time:    635.65 s
 Time Step:  67500, Simulation Time:    637.08 s
 Time Step:  67600, Simulation Time:    638.38 s
 Time Step:  67700, Simulation Time:    639.59 s
 Time Step:  67800, Simulation Time:    640.74 s
 Time Step:  67900, Simulation Time:    641.77 s
 Time Step:  68000, Simulation Time:    642.78 s
 Time Step:  68100, Simulation Time:    643.72 s
 Time Step:  68200, Simulation Time:    644.63 s
 Time Step:  68300, Simulation Time:    645.47 s
 Time Step:  68400, Simulation Time:    646.31 s
 Time Step:  68500, Simulation Time:    647.08 s
 Time Step:  68600, Simulation Time:    647.83 s
 Time Step:  68700, Simulation Time:    648.59 s
 Time Step:  68800, Simulation Time:    649.27 s
 Time Step:  68900, Simulation Time:    649.95 s
 Time Step:  69000, Simulation Time:    650.63 s
 Time Step:  69100, Simulation Time:    651.27 s
 Time Step:  69200, Simulation Time:    651.88 s
 Time Step:  69300, Simulation Time:    652.50 s
 Time Step:  69400, Simulation Time:    653.11 s
 Time Step:  69500, Simulation Time:    653.69 s
 Time Step:  69600, Simulation Time:    654.24 s
 Time Step:  69700, Simulation Time:    654.79 s
 Time Step:  69800, Simulation Time:    655.34 s
 Time Step:  69900, Simulation Time:    655.89 s
 Time Step:  70000, Simulation Time:    656.44 s
 Time Step:  70100, Simulation Time:    656.95 s
 Time Step:  70200, Simulation Time:    657.44 s
 Time Step:  70300, Simulation Time:    657.94 s
 Time Step:  70400, Simulation Time:    658.43 s
 Time Step:  70500, Simulation Time:    658.93 s
 Time Step:  70600, Simulation Time:    659.42 s
 Time Step:  70700, Simulation Time:    659.92 s
 Time Step:  70800, Simulation Time:    660.41 s
 Time Step:  70900, Simulation Time:    660.86 s
 Time Step:  71000, Simulation Time:    661.30 s
 Time Step:  71100, Simulation Time:    661.75 s
 Time Step:  71200, Simulation Time:    662.19 s
 Time Step:  71300, Simulation Time:    662.64 s
 Time Step:  71400, Simulation Time:    663.08 s
 Time Step:  71500, Simulation Time:    663.53 s
 Time Step:  71600, Simulation Time:    663.98 s
 Time Step:  71700, Simulation Time:    664.41 s
 Time Step:  71800, Simulation Time:    664.81 s
 Time Step:  71900, Simulation Time:    665.21 s
 Time Step:  72000, Simulation Time:    665.61 s
 Time Step:  72100, Simulation Time:    666.01 s
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source  
fds.exe            000000014027AAAD  Unknown               Unknown  Unknown
fds.exe            0000000140303EFE  Unknown               Unknown  Unknown
fds.exe            00000001400708BA  MAIN__                    525  main.f90
fds.exe            000000014006D91E  Unknown               Unknown  Unknown
fds.exe            0000000140783A1C  Unknown               Unknown  Unknown
kernel32.dll       0000000076EA59ED  Unknown               Unknown  Unknown
ntdll.dll          00000000770DC541  Unknown               Unknown  Unknown

Starting Smokeview: C:\Program Files\PyroSim 2015\fds\smokeview.exe...

**Comment by mcgratta** [comment]
I will run the case, but I doubt I will be able to solve this problem. Have you run the case without a fire? That might be the first thing to try to see if the HVAC solution looks reasonable.

**Comment by mcgratta** [comment]
The case is still running on my machine, but I am using a newer test version of FDS. I found some more mistakes in the input file. Do not do this

```
&HVAC ID='ExF-B1-01', TYPE_ID='FAN', MAX_FLOW=0.0, MAX_PRESSURE=0.0/
&HVAC ID='EXF-B1-02', TYPE_ID='FAN', MAX_FLOW=0.0, MAX_PRESSURE=0.0/
```

It causes a divide by zero error. We have added error checking for this. 

```
WALL_INCREMENT=25
```

Why?

```
RADIATION=.FALSE.
```

Why? These parameters may save you time, but they may also cause problems.

**Comment by hasanadel88** [comment]
I will run it without the fire and tell you what is going on

**Comment by mcgratta** [comment]
It appears as if your building is sealed. I do not see any openings to the outside. I do not see any ZONE line, or LEAKs specified. With such high flow rates (23 m3/s), this is going to cause problems.

**Comment by hasanadel88** [comment]
All meshes are opened, Can that substitute for leak?. There is also holes on slaps which makes air able to enter or exit thought it from/to outside the building

**Comment by mcgratta** [comment]
The fact that the meshes are OPEN is not relevant in your case. How large are the openings to the actual building interior? I think the word you are looking for is "slat", which is a narrow opening. It is possible that these slats are closed up due to FDS aligning obstructions with the mesh, or it is possible that the total area of the slats is small compared to the very large amount of air you are forcing into the building. The air might be rushing out of your slats so quickly that a numerical instability results. You might want to use a LEAK rather than an actual physical opening. You should also check the pressure of the interior. Most common building construction cannot maintain pressures beyond about 1 kPa.

**Comment by hasanadel88** [comment]
Ok, I will try introducing LEAK. However, I do have a concern about pressure inside building. To give you and idea about what i'm trying to simulate

hereunder the sequence of operation to be followed through CFD calculation and to be taken into consideration

The sequence of operation in case of fire will be as following:

A.      Fire at 1st basement:
·         Exhaust fans in 1st basement to run @ the high speed.
·         Supply fans in 1st basement to run @ the low speed.
·         Exhaust fans in 2nd basement to run @ the low speed.
·         Supply fans in 2nd basement to run @ the high speed.

B.      Fire at 2nd basement:
·         Exhaust fans in 2nd basement to run @ the high speed.
·         Supply fans in 2nd basement to run @ the low speed.
·         Exhaust fans in 1st basement to run @ the low speed.
·         Supply fans in 1st basement to run @ the high speed.

**Comment by mcgratta** [comment]
You should try all of the HVAC configurations without a fire. Check the pressure inside the building, and make sure that you have either enough openings or LEAKs to maintain realistic pressure.
