### ISSUE TITLE
Render both sides of obstruction faces when clipping is enabled

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3580]
When clipping a scene, the back sides of obstruction faces should be shown, to help better understand the cut away view. Could two-way rendering of obstruction faces be turned on when clipping is turned on?

**Comment by gforney** [comment]
try smokeview at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

**Comment by mcgratta** [comment]
It works! Thanks.
