### ISSUE TITLE
Trap bad FAN input

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3584]
I ran across an input file with

```
&HVAC ID='ExF-B1-01', TYPE_ID='FAN', MAX_FLOW=0.0, MAX_PRESSURE=0.0/
```

which caused a divide by zero in `hvac.f90`

```
DEL_P = FA%MAX_PRES - FA%MAX_PRES*(VDOT/FA%MAX_FLOW)**2
```

I can see where we need to trap this error, but I don't know what is allowed and what is not. There is also this

```
&HVAC ID='ExF05', TYPE_ID='FAN', VOLUME_FLOW=0.0/
```

that did not seem to cause problems. Could you add the necessary error traps to prevent (or allow) these fan inputs.

**Comment by drjfloyd** [comment]
The first case should probably be trapped.

The second is odd, but I can see that it might be useful to be able to force flow in a duct to be zero for testing/debugging a complex HVAC network (volume flow just gets converted to a fixed velocity based on the duct area). I think that should remain OK.

**Comment by mcgratta** [comment]
Is the error when both are set to zero, or either set to zero?

**Comment by drjfloyd** [comment]
I don't think it makes sense for a quadratic fan to allow MAX_FLOW<=0 or MAX_PRESSURE<=0. I am adding traps for those.

**Comment by drjfloyd** [comment]
fixed
https://github.com/firemodels/fds-smv/commit/2f35f1275926c83db521b3fa31f8321038f53e73

**Comment by mcgratta** [comment]
Is there any reason not to include the `HVAC ID` in the `ERROR` message? In the case I am looking at, there are hundreds of `HVAC` lines.

**Comment by drjfloyd** [comment]
Good thought. I'll rework the error messages to include the ID.

**Comment by drjfloyd** [comment]
Added HVAC ID to the error messages.

https://github.com/firemodels/fds-smv/commit/adf930929444b492f2960e93b829aa3dbd0c3b14

**Comment by drjfloyd** [comment]
Was this fixed?

**Comment by mcgratta** [comment]
Yup:

```
ERROR: MAX_PRESSURE must be > 0. Fan ID:ExF-B1-01, HVAC line number:  480 (CHID: Model17)
```

Thanks
