### ISSUE TITLE
Synthetic eddies with HVAC fans

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#3592]
Morning All,

I've been playing with jet fans and synthetic eddies. Dan Swenson has posted examples on the Thunderhead site, and there is an example in the V & V files. In both of these situations a simple fan was used. I've been unable to demonstrate synthetic eddies when using an HVAC fan. (The ultimate goal is to  generate turbulence in jet fans in parking garages with cells on the order of 0.125 m.)

Is this a bug, or an undocumented feature?

See the attached comparison. It comprises a, 
-     simple fan without eddies
-     simple fan with eddies
-     HVAC fan without eddies
-     HVAC fan with eddies.

They are in separate meshes, so there is no interaction, and all surfaces are open. At best, I can imagine a slight increase in the turbulence of the HVAC fan with eddies when compared to the HVAC fan without, but that may just be wishful thinking.

Thanks

Dave

[jet_fan_comparison_0998.zip](https://github.com/firemodels/fds-smv/files/154928/jet_fan_comparison_0998.zip)

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by Dave-McGill** [comment]
Thanks Kevin

**Comment by rmcdermo** [comment]
I would not be surprised if SEM does not work with HVAC vent.  I can
document that.  Assign to me.

**Comment by rmcdermo** [comment]
Added error trap and user guide discussion in pull request #3596.

**Comment by Dave-McGill** [comment]
There are a lot of people modelling underground car parks with jet fans. 

Is it possible to make synthetic eddies work with HVAC fans?

**Comment by rmcdermo** [comment]
This would take some work.  I'll have a look today and see what we can do.

But please answer this question.  Do we not agree that with sufficient
resolution SEM is not necessary?  And with low resolution (1 or 2 cells
across a fan) the SEM parameters are just knobs to turn; they have no
physical significance.  Hence you need data for calibration.  Where does
that come from?

I am all for making things as easy as possible.  But put yourself in my
shoes.  Our critics love to say that we enable poor CFD practice.  How
would this be good CFD practice?

**Comment by Dave-McGill** [comment]
Randy,

Yes, with sufficient resolution SEM is not necessary. 

Dan has built a small car park example that he used to demonstrate Dynamic Smagorisky. The overall cell size is 0.25 m, and the cell size in the region of the 4 fans is 0.125m, for a total of ~ 1/2 million cells. In his earlier tests using Deardorff, he found a cell size of ~ 0.01 m was necessary to resolve the jet fan turbulence. If I drop the cell size around the fans to ~ 0.0156 the overall cell count is ~68 million cells, which is  not doable.

I'm not qualified to judge what is good or bad CFD practice. I'm trying to find a solution that is practicable for the average FPE, who has limited computing power. Car parks with jet fans are being run all the time, and that's not going to change; the the challenge is to find the best, or if you prefer, least bad, way of doing it.

Dave

**Comment by rmcdermo** [comment]
Dave,

I will go on record to say I think what Dan is doing is bad CFD practice.
There is no reason he could not make Pryrosim relatively easily resolve the
fan regions but leave the rest of the car park at .25 cm resolution.  I
also take exception to use of the phrase, "resolve the jet fan
turbulence".  It is more like he "witnesses fluctuations".

Are you going to use DSMAG for the fire?  I have said repeatedly that DSMAG
is not a good model for the fire, especially at coarse resolutions.

Randy

**Comment by Dave-McGill** [comment]
Randy,

I can't speak for Dan, and I don't want to put words in his mouth.

I'm not using DSMAG. In the tests using Deardorff do  ~1 cm cells with not qualify as resolving the turbulence?

What about using a screen to create turbulence? I've never used screens before. I've cut and pasted from one the example files and and generating turbulence at 0.125 m resolution. (see attached)

Dave

![with and without scree](https://cloud.githubusercontent.com/assets/13259079/13497658/95a9f3d0-e124-11e5-9ad6-2764e691d7bc.png)

**Comment by rmcdermo** [comment]
The question is why do you think one solution is better than any other?
The only comparison with data or theory that I've seen is in our
verification guide.  It seems to me that this is the best guidance.

If jet fans in car parks are a critical need in FDS, we should undertake a
serious effort to do this right.  I get very frustrated by all the knob
turning.  Inevitably, I am the one who has to answer for it.

**Comment by rmcdermo** [comment]
By the way, any "serious effort" would start with actual data from a car
park or tunnel.  Can you point me to anything along those lines?

**Comment by Dave-McGill** [comment]
Nope

**Comment by rmcdermo** [comment]
Dave,
Have you tried a "velocity patch"? See if the attached works for you.  At this resolution, the core does not quite break down fast enough to give exponential decay of the centerline velocity component.  But I suspect that one more level of refinement would do it.

![vel_decay](https://cloud.githubusercontent.com/assets/4418497/13502778/6739d6e4-e13a-11e5-920b-9eabffd925ca.png)

[jet_fan_patch.txt](https://github.com/firemodels/fds-smv/files/157284/jet_fan_patch.txt)

![jet_fan_patch_0991](https://cloud.githubusercontent.com/assets/4418497/13502729/3243b2a2-e13a-11e5-8fe3-bd46db78b019.png)

**Comment by rmcdermo** [comment]
Here is some further analysis, which follows the centerline decay equation in the verification guide.  While the decay is not a pretty exponential, it is within the uncertainty bounds on the experiments that we have available.  So, even though it would be possible to dial in the patch decay more accurately, I see no reason to go beyond this level of complexity.  Attached are the input files, scripts, and results for this simple case.

[jet_fan_patch.fds.txt](https://github.com/firemodels/fds-smv/files/157369/jet_fan_patch.fds.txt)

[plot_vel.py.txt](https://github.com/firemodels/fds-smv/files/157370/plot_vel.py.txt)

![vel_decay](https://cloud.githubusercontent.com/assets/4418497/13504092/e44ef1e0-e140-11e5-8ec6-e90713f431c4.png)

**Comment by Dave-McGill** [comment]
Randy,

I cut the cell size in 1/2 for jet_fan_patch.fds, and am running it now.

I'd never heard of a velocity patch until an hour ago, and I still have a pretty vague idea of what it is. Are suggesting that a patch with a cell size of 0.125 m is a practical solution?

Dave

**Comment by rmcdermo** [comment]
Yes.  It seems to do the trick.

**Comment by Dave-McGill** [comment]
It appears that the most important parameter is the face velocity at the fan. Would it make sense to add it to the section in the manual on jet fans? The explanation would have to be simplified considerably. 

Do you want me to make an initial attempt?

**Comment by rmcdermo** [comment]
I guess I don't understand what you are saying.  Isn't velocity the usual
parameter for a fan?  What other parameters do you use?

If you want a louver, you would add a second small patch just at the exit
and apply the velocity components there.  I think it is best if we first
put together a series of examples.

**Comment by Dave-McGill** [comment]
The point I was trying to make was that it would be pretty much a cut 'n paste sort of operation for a user. All he/she would have to do is put in the face velocity of the specific fan that was being modelled, and get it lined up on the right axis, and at the right height.

**Comment by rmcdermo** [comment]
Yes, that's true.  With this approach you can also have non-grid aligned
fans (if you don't care about the aesthetics of the shroud).

**Comment by Dave-McGill** [comment]
Morning Randy,

Using velocity patches with cell sizes of 0.125 and 0.0625, here is a comparison of the centerline velocities. 
![velocity patch centerine velocities at different cell sizes](https://cloud.githubusercontent.com/assets/13259079/13526486/2a4a8778-e1d6-11e5-88ac-591807515dd2.PNG)

**Comment by rmcdermo** [comment]
Please email me the _line file for .0625 and I'll plot with data.

**Comment by Dave-McGill** [comment]
You've got mail

**Comment by Dave-McGill** [comment]
In Dan's original sensitivity study he compared the simulations to experimental work by Geisen (which also cites earlier work by van Oerle). I've plotted their experimental data witht the two velocity patches. It's convenient, as they both used fans with a face velocity of 18 m/s. Their measurements extended out to 16 m, so I'm going to re-run the velocity patches to that distance.

I've also attached Geisen's paper. See figure 8, it has a collection of experimental observations, including wall jets.
![velocity patch centerine velocities at different cell sizes and experimental data](https://cloud.githubusercontent.com/assets/13259079/13528119/14eb3786-e1e2-11e5-8ebe-420d61cfb94e.PNG)

[11_envsoft_giesen.pdf](https://github.com/firemodels/fds-smv/files/158700/11_envsoft_giesen.pdf)

**Comment by rmcdermo** [comment]
Thanks for the paper.  Let's set up a series of verification cases and
non-dimensionalize in the same way we do the case in the verification guide
now.

**Comment by Dave-McGill** [comment]
Here's the comparison with measurements from the velocity patch  (0.125 m cells) extended out to 16 m. The simulation with 0.0625 m cells is going to take all day to complete.
![velocity patch centerine velocities at different cell sizes and experimental data](https://cloud.githubusercontent.com/assets/13259079/13532372/3448b4d4-e1f9-11e5-9206-2f929a7cf937.PNG)

**Comment by rmcdermo** [comment]
Dave,
This data is not behaving like a typical turbulent free jet.  Probably
boundary effects in the garage.  Also, the plots I gave above have errors
because my "origin" was not correctly specified.  I am fixing this.

**Comment by rmcdermo** [comment]
I specified the velocity in the core region as part of the patch and corrected my exp data plot.  I get the following.  So, my conclusion is that this is a viable (in my opinion preferable) approach to modeling the fans (as opposed to using DSMAG).  I do not think you can compare the data from the papers you sent with the FDS configuration we are testing.  These papers should be treated like validation cases and a careful study of the full geometry should be done.  I would appreciate it if someone else would take this on.  If I put it in my queue, it will likely not see the light of day.

![vel_decay](https://cloud.githubusercontent.com/assets/4418497/13539899/583dfe30-e221-11e5-9de0-35d7a9106a77.png)

**Comment by rmcdermo** [comment]
Here is the low resolution input file.

[jet_fan_patch.fds.txt](https://github.com/firemodels/fds-smv/files/159374/jet_fan_patch.fds.txt)

**Comment by Dave-McGill** [comment]
Randy,

Fig. 3 of Geisen's paper shows the test set-up for the free jet case; the walls aren't very close. Besides, Figure 8 shows the same behaviour for both the free jet and wall tests. This reminds me of the quote, “In theory, theory and practice are the same. In practice, they are not.”.

We've got 5 examples of jet fans exhibiting the same behaviour, which is a good thing in my mind.

Here's the graph updated with the 0.0625 cells and measurements taken out to 16 m. I'll mail you the _line.csv file.

Dave
![velocity patch centerine velocities at different cell sizes and experimental data](https://cloud.githubusercontent.com/assets/13259079/13540004/0d2706ac-e222-11e5-9ef8-a3118cde5e93.PNG)

**Comment by Dave-McGill** [comment]
OK, I'll do the validation study, although it might be the summer before I can get to it. I'll need some guidance as to how you want it done.

**Comment by dvswenson** [comment]
Randy,

The velocity patch looks like a fruitful approach to jet fans.

Could you comment on why using a velocity patch with a uniform velocity specified over a shrouded volume results in different downstream behavior than a vent with a uniform specified velocity? What was your thinking that lead to suggesting this approach?

Thanks,
Dan

**Comment by dvswenson** [comment]
"led" not "lead"

**Comment by rmcdermo** [comment]
The only reason DSMAG appears to work better for some of your cases is that
it lets the jet core break down sooner.  With sufficient resolution one
could apply Jarrin's SEM method to achieve the same result (see FDS
Verification Guide).  But apparently everyone insists on low resolution (2
cells across the fan), so SEM is out (you need grid cells to generate
coherent eddies).  The reason the patch works is that it sucks in random
fluctuations from the inlet.  Since the immersed boundary method used in
the patch is not perfect and since we are not forcing the V and W
components (in this case) then it seems that we persist enough fluctuations
in the jet to allow the core to break down with 2 cells with Deardorff.  I
am much more comfortable with this because, as I've said before, DSMAG is a
really bad idea for coarse LES calculations of fire.

**Comment by dvswenson** [comment]
Thanks.

**Comment by Monika-Samy** [comment]
how to model jet fan by velocity patch
