### ISSUE TITLE
N_O2 to simulate oxidation reaction

### ISSUE THREAD

**Issue by guoxiangzhao** [firemodels/fds#3614]
When I add N_O2=1.5  to the MATL line, a error message is given.
Anybody else has some similar experience?

&MATL ID='MDF1',
      N_REACTIONS=1,
      A(1) = 90300,
      E(1) = 80200,
      N_S(1) = 1.04,
      N_O2  = 1.5
      THRESHOLD_TEMPERATURE(1)=226.85,
      EMISSIVITY=0.70,
      DENSITY=809.4598,
      MATL_ID='CHAR',
      NU_MATL=0.175388574,
      SPEC_ID='PROPANE',
      NU_SPEC=0.824611426,
      HEAT_OF_REACTION=-10.2,
      HEAT_OF_COMBUSTION=17711,
      CONDUCTIVITY = 0.18,
      SPECIFIC_HEAT = 1.576 /

**Comment by mcgratta** [comment]
Post the input file, preferably in a simple form.

**Comment by guoxiangzhao** [comment]
[SS19_1.txt](https://github.com/firemodels/fds-smv/files/159871/SS19_1.txt)

**Comment by guoxiangzhao** [comment]
Thanks for your reply, and here it is.

[SS19_1.txt](https://github.com/firemodels/fds-smv/files/159872/SS19_1.txt)

**Comment by mcgratta** [comment]
Works for me. What version of FDS are you using?

**Comment by guoxiangzhao** [comment]
it is FDS 6.0 beta.

**Comment by drjfloyd** [comment]
Upgrade your version of FDS.  FDS 6 beta is three years old, we are now at 6.3.2 with 6.4 imminent. Either N_O2 wasn't an input in the version you are using or there was a bug which has since been fixed.
