### ISSUE TITLE
Limit in porous media? 

### ISSUE THREAD

**Issue by cfaurie** [firemodels/fds#3634]
Hello,

I'm using FDS 6.3.2 and I want to model a porous screen with a free area around 20%. I'm using DRAG_LAW='POROUS MEDIA' and was wondering what are the limits for the definition of K and Y, if there is any. 

With Y=0.8, my test case (see input file below, res 0.1 m in every directions) works fine for K up to 1.0E-3, pressure starts to show instabilities at 1E-4 and I obtain a numerical instability error straight away for K = 1E-5. Same thing happen if you fix K and increase Y. Therefore my question. 

From what I understood, 20% seems somehow small for the porous media/screen application, but I wouldn't consider it as extreme? At 20 degC, DP predicted from eq. (14.4) is around 30 Pa.

Thanks for your help,
Coraline

FDS Input file example:

&HEAD CHID='2'/
&TIME T_END=100.0/
&MISC TMPA=100.0/

&MESH ID='MESH', IJK=50,20,20, XB=0.0,5.0,0.0,2.0,0.0,2.0/

&PART ID='SCREEN',
      STATIC=.TRUE.,
      SURF_ID='SCREEN',
      DRAG_LAW='POROUS MEDIA',
      PERMEABILITY = 1.0E-5,1.0E-5,1.0E-5,
      DRAG_COEFFICIENT=0.8,0.8,0.8,
      POROUS_VOLUME_FRACTION=0.2 /

&DEVC ID='PRESSURE in', QUANTITY='PRESSURE', XYZ=1.25,1.0,1.0, ORIENTATION=1.0,0.0,0.0/

&MATL ID='ALUMINUM',
      SPECIFIC_HEAT=0.9,
      CONDUCTIVITY=200.0,
      DENSITY=2700.0/

&SURF ID='SCREEN',
      MATL_ID(1,1)='ALUMINUM',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.05/

&SURF ID='VELOCITY',
      COLOR='GREEN',
      VEL=-1.0/

&SURF ID='FreeSlip',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE.,
      FREE_SLIP=.TRUE./

&INIT ID='SCREEN', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=2.5,2.51,0.0,2.0,0.0,2.0/

&VENT SURF_ID='VELOCITY', XB=0.0,0.0,0.0,2.0,0.0,2.0/ 
&VENT SURF_ID='FreeSlip', XB=0.0,5.0,0.0,2.0,2.0,2.0/ 
&VENT SURF_ID='FreeSlip', XB=0.0,5.01,0.0,2.0,0.0,0.0/ 
&VENT SURF_ID='FreeSlip', XB=0.0,5.0,0.0,0.0,0.0,2.0/ 
&VENT SURF_ID='FreeSlip', XB=0.0,5.0,2.0,2.0,0.0,2.0/ 
&VENT SURF_ID='OPEN', XB=5.0,5.0,0.0,2.0,0.0,2.0/ 

&TAIL /

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
This appears to be a time step size issue. If I set DT=0.005 the case runs fine with PERMEABILITY = 1E-5 but not 1E-6; for 1E-6 it runs with DT=0.002. What appears to be happening is if too large of a timestep is taken for the amount of drag that flow reversal occurs and once that happens things go unstable pretty quickly. I think I need to come up with some kind of stability criteria for when we impose large amounts of drag using particles.

**Comment by drjfloyd** [comment]
Fixed.  I have added a stability check for screen and porous drag controlled by DRAG_CFL_MAX on MISC (currently it is set to 1.25). Running your case with PERMEABILITY=1E-6 and it runs fine. FDS settles on a timestep pretty close to the DT=0.002 in my prior comment.

https://github.com/firemodels/fds-smv/commit/aedb395b658eb1f29b71c263dafbd6af13295714

**Comment by mcgratta** [comment]
Did you check the verification case called "porous media"? It might run better now.

**Comment by rmcdermo** [comment]
This is why we used an analytical solution in the previous drag model.
Rather than impose a time step restriction, I think we can rework our
solution for the screen drag case with pressure drop.  The problem before
was that we did not consider the DP term in the momentum solution.  This
idea got dropped when Ben Trettel moved on to other issues at UT.

**Comment by rmcdermo** [comment]
Why would we set a CFL above 1?

**Comment by drjfloyd** [comment]
Maybe CFL isn't the best term for the input.  Values over 1 work.

**Comment by drjfloyd** [comment]
I ran porous_media.fds. The highest resolution mesh in porous_media.fds is less noisy with the new version. The other two meshes remain pretty much the same.

**Comment by mcgratta** [comment]
OK, good. Thanks.

**Comment by rmcdermo** [comment]
Any reason to keep this open?

**Comment by mcgratta** [comment]
None from me.
