### ISSUE TITLE
Increase in simulation time/computation cost du

### ISSUE THREAD

**Issue by leventon** [firemodels/fds#3643]
Hi there,

I have been running a number of DNS simulations in FDS 6.3.2 to look at ignition, vertical burning, and flame behavior (particularly flame to surface heat transfer) of 5 cm tall PMMA slabs. In an effort to better understand model sensitivity to properties of the fuel, I am running several simulations that are otherwise identical except for the prescription of gas phase fuel properties (e.g. using a predefined FUEL species, such as PROPANE, or defining a new FUEL & SPEC ID for MMA with a user-defined HEAT OF COMBUSTION, FORMULA, and RAMPS for thermal conductivity, diffusivity, specific heat, and viscosity) 

Simulations in which fuel properties are user-defined require approximately 5-6 x the time to run as those in which an FDS-defined species is used as the fuel. This is a surprisingly significant increase in computational cost for such a small change. Do you have any idea what may be causing this issue or what I can try to resolve it?

Attached here I have provided two files. In the first, PMMA_5cm_Propane.txt, the system is defined such that the FUEL generated possesses the properties of PROPANE as defined by FDS. In the second, PMMA_5cm_Propane_MMAmonomer.txt, I have defined a fuel that possesses the same thermal conductivity, diffusivity, specific heat, and viscosity of PROPANE (determined and defined based on the .out file of the first simulation) but the FORMULA and HEAT OF COMBUSTION of MMA vapor.  Effectively, these should produce very similar results and I wouldn't expect a large change in simulations results or the time required for these calculations; unfortunately that is not the case.

Any suggestions on what to do from here? Thanks,
Isaac

[PMMA_5cm_Propane.txt](https://github.com/firemodels/fds-smv/files/164072/PMMA_5cm_Propane.txt)
[PMMA_5cm_Propane_MMAmonomer.txt](https://github.com/firemodels/fds-smv/files/164073/PMMA_5cm_Propane_MMAmonomer.txt)

**Comment by rmcdermo** [comment]
Are the time steps the same in both cases?  Or has the cpu/time step increased in the second case?

You can compile and run the case with the profiler code to see where all your time is being wasted.  Go to FDS_Compilation and compile the intel_linux_64_profile version.  Instructions for how to profile are in the makefile.

Intel Compiler for Linux

to profile FDS:
1.  build FDS using intel_linux_64_profile target
2.  run case as usual
3.  type: gprof fds_linux_64_profile > results.out

**Comment by mcgratta** [comment]
I'll take a look at the cases.

**Comment by mcgratta** [comment]
Check the HRR in the _hrr.csv file for both cases. Is the HRR comparable?

**Comment by leventon** [comment]
They're identical in the early stages of the simulation (which is all that we have modeled so far in these two) until sample ignition, t ~15 s.

**Comment by mcgratta** [comment]
The first 600 time steps of `PMMA_5cm_Propane` used 419 s. The first 600 time steps of `PMMA_5cm_PropaneMMAmonomer` used 438 s. So there appears to be about a 5% increase due to using fuel property `RAMP`s in this case. I'll check again later.

**Comment by drjfloyd** [comment]
The RAMPs are only used in read.f90 to create the arrays D_Z, MU_Z, etc. With the predefined species the thermophysical properties arrays are filled with calls to the polynomial fits in data.f90.  With user defined RAMPs, the thermophysical properties arrays are filled with calls to the ramp interpolation function in func.f90.  After exiting read.f90 the rest of the simulation doesn't know how the user defined the properties. 

In read.f90, the property arrays are populated at integer temperatures from 0 to 5000 K. The input file with the RAMPs only defines values from 293 K to 1500 K. Outside that range the values will be kept constant. My guess is at some point in the simulation this fact combined with the fact the two fuels have a factor of two difference in both HoC and MW results in different timesteps.

**Comment by rmcdermo** [comment]
Jason,

Might be good to add a note in the user guide to specify props from 0 to
5000 K using RAMP_K, for example.  If this is discussed somewhere, I did
not see it.  Maybe just in the paragraph called Option 2: User-Specified
Properties.

R

**Comment by drjfloyd** [comment]
Good idea. I'll add a note that explains one should define the ramp to encompass the range of temperatures expected in simulation.

**Comment by mcgratta** [comment]
The calcs have been running for over 3 hours, and I don't see a significant difference in the run time or performance. Perhaps these cases will begin to develop differently, in which case the time step may not remain the same for both, which would then explain the difference in time to finish. I'm going to stop the jobs -- I'm convinced that the user-specified props are not the cause of significant difference. Take a look at your cases and see if the time step is very different.

**Comment by leventon** [comment]
That's fair, thanks. Happy to see that the definition of matl properties doesn't seem to be affecting things too much.

I'm working my way through each of the simulations that I have running now - writing down how long they've been running, time simulated, and time step - hopefully some trend becomes clear. Hopefully you're right and it's just how conditions develop as the simulation goes on. Previously, after checking on ~6 of these that had been running for at least a week, there were some significant differences between a few of them.

Thanks again,
Isaac

**Comment by drjfloyd** [comment]
Added text to the user's guide per Randy's request.

https://github.com/firemodels/fds-smv/commit/c28ba14c0a5761486daf23ad19923ef6ab96152b
