### ISSUE TITLE
&devc 'cpu time' FDS not Work

### ISSUE THREAD

**Issue by MartinFDS2016** [firemodels/fds#3654]
Good Morning all. I found this site by accident , while trying to solve my problem found . I would like to measure the time that my PC to calculate the FDS model requires . If that works I want to change various parameters and see whether this fast was in order to find the optimum.
When use of FDS I'm a beginner .
So far I have found that with the command & DEVC QUANTITY = ' CPU TIME / should work . But I did not get it to run .

Also, I tried fiolgenden File: & DEVC IJK = 16,16,16 , QUANTITY = ' CPU TIME /
But even that did not work .

On the web and in the USER GUIDE , I am not come on.
Can anyone possibly help and tell me how the file is correct and location at which it has to me ?

Thanks in advance.

Martin

**Comment by rmcdermo** [comment]
This page is for reporting bugs.  You want the discussion forum.  There is a link from the FDS website:

http://firemodels.github.io/fds-smv/

**Comment by rmcdermo** [comment]
Post your question there and we will answer it so that all users can benefit from the discussion.  Thanks.

**Comment by MartinFDS2016** [comment]
Sorry. that was not intentional . Thank you for the tip.
