### ISSUE TITLE
The HRR difference between two versions

### ISSUE THREAD

**Issue by guoxiangzhao** [firemodels/fds#3655]
The difference between version 'FDS 6.0.1 Parallel' and FDS 6, FDS 6 Release Candidate 3 Parallel.
I run two simulations using these two version (one is on a Linux Server and another is on HPC), it is surprise that the total HRR is so different.
I try to compare the difference from the user guide of these two version, but I can not find the user guide for version: FDS 6 Release Candidate 3 Parallel .
![unnamed qq screenshot20160310104254](https://cloud.githubusercontent.com/assets/13900156/13665453/e0d5858a-e6ac-11e5-95db-161ef32994fb.jpg)

**Comment by rmcdermo** [comment]
Most of the differences are documented in the release notes.  But there is no way to know what is going on from your post.  If I had to take a wild guess, I would say the extinction model changed.

https://github.com/firemodels/fds-smv/wiki/FDS-Release-Notes

**Comment by guoxiangzhao** [comment]
so the FDS 6 Release Candidate 3 Parallel = FDS 6.0.0?
If it is, then as I checked the release notes, but I didn't notice there are any noticeable difference between version 6.0.0 and 6.0.1.

**Comment by guoxiangzhao** [comment]
so FDS 6 Release Candidate 3 Parallel is FDS 6.0.0?

**Comment by guoxiangzhao** [comment]
Do you have the user guide or the technical guide of FDS (version: FDS 6 Release Candidate 3 Parallel)?

**Comment by rmcdermo** [comment]
The documentation is bundled with the release.  Old releases are found here:

https://bintray.com/nist-fire-research/releases/FDS-SMV/view
