### ISSUE TITLE
CNF_CUTOFF is not an input parameter

### ISSUE THREAD

**Issue by jmvaari** [firemodels/fds#3662]
The User Guide (6.3.2, Git-r5), page 154, implies that the user is able to specify a value for CNF_CUTOFF on the &PART line. This is not the case, but it would be a desirable feature especially with fine water sprays in mind where the use of the default value of 0.005 may result in a disconnect between a specified and measured particle size distribution.

**Comment by rmcdermo** [comment]
CNF_CUTOFF is specified on MISC.  Is this sufficient?

**Comment by jmvaari** [comment]
Well I missed that one. It is sufficient, thanks. Maybe the UG should point to &MISC on p 154.

**Comment by rmcdermo** [comment]
Done.  Thanks for the help!
