### ISSUE TITLE
Documentation of PDPA_HISTOGRAM

### ISSUE THREAD

**Issue by jmvaari** [firemodels/fds#3663]
The User Guide (6.3.2, Git-r5), top of page 217 says volume and area based histograms can be output by setting PDPA_M to 3 and 2 respectively. This is not so. The correct settings appear to be PDPA_M=1 and additionally PDPA_N=3 (2) for volume (area). There is a mismatch between the UG and the ./Verification/Sprinklers_and_Sprays/droplet_distributions.fds case.

**Comment by shostikk** [comment]
Thanks for the report Jukka. UG seems to be in error. I'll fix.

**Comment by shostikk** [comment]
Fixed.
