### ISSUE TITLE
 FDS 6.3.2 - Changing Velocity Boundary Condition after Restart

### ISSUE THREAD

**Issue by DineshMyilsamy** [firemodels/fds#3667]
I am using FDS v.6.3.2 for my research.

> My research topic is “Dispersion of Hydrogen Fluoride in the atmosphere”
> 
> Total size of my geometry is 1400 m x 1400 m x 195 m. Here by picture as follows

![kmw](https://cloud.githubusercontent.com/assets/16892714/13809564/a8060642-ebae-11e5-817b-9b6e5277ec1f.jpg)

> I carried out this simulation using restart command (Physical Time = 701 s, DT_Restart = 700 s)
> 
> Up to 700 s, the atmospheric air flows only in West Direction (VEL = 1.33 m/s, VEL_T = 0.0001 m/s, inlet direction).
> 
> After 700 s I have changed the atmospheric air flow direction to North West, using VET: 0.81 and VET: 0.81 as an Inlet direction.
> 
> The restarted calculation velocity  was not a reasonable prediction.
> 
> And when I scaled down my Geometry size to 50 m x 50m x 50 m, I observed a reasonable velocity prediction using the same second boundary condition to the previous one (VET: 0.81 and VET: 0.81).
> 
> I don’t have any idea, why I could not predict a reasonable velocity for the geometry of 1400 m x 1400 m x 195 m.

For your more detailed information I am submitting my simplified input file Before Restart (filename - Br) and after restart (file name -Ar) also for further information I have attached my scaled down Geometry input file (filename - scaleddown)

[Ar.txt](https://github.com/firemodels/fds-smv/files/175760/Ar.txt)
[Br.txt](https://github.com/firemodels/fds-smv/files/175762/Br.txt)
[Scaleddown.txt](https://github.com/firemodels/fds-smv/files/175761/Scaleddown.txt)

**Comment by mcgratta** [comment]
I will take a look at it. However, your meshing strategy is very poor. Do no stack 4 cell high meshes on top of each other. This leads to the maximum amount of error at the mesh boundaries.

**Comment by mcgratta** [comment]
I do not understand what you are trying to do. What does the Scaledown case demonstrate?

**Comment by DineshMyilsamy** [comment]
Thank you very much for your response Mr. Kevin.

   First I will explain what I am trying to do and what is my problem and
later I will discuss regarding scale down case.

_Actually my Problem is:_

   I am trying to simulate a chemical accident (Sep 27, 2012. at Kumi,
South Korea)  dispersion of hydrogen fluoride in the atmospheric air.

  Based on the meteorological  data, for the wind flows in the "West"
direction at velocity of 1.33 m/s from 0 to 700 s . After, 700 seconds,
direction of the wind changes to North West direction at a velocity of
 0.81 m/s.

  In order to simulate that condition, I have used restart option  for
changing the wind direction and velocity after 700 s.

  My actual geometry of size 1400 x 1400 x 95 meters. First 700 s (Before
restart) has reasonable velocity  prediction.  After restarting the
calculation from 700 s, velocity prediction was unreasonable.

[image: Inline image 1]

So I would like to know what cause this problem.

Best Regards,

Dinesh Myilsamy.

**Comment by rmcdermo** [comment]
For this problem it is better to use MEAN_FORCING with a RAMP on the wind direction.  See the examples in Verification/WRF/

https://github.com/firemodels/fds-smv/blob/development/Verification/WRF/wrf_time_ramp.fds

**Comment by mcgratta** [comment]
I created this little test case

```
&HEAD CHID='flow_restart'/
&TIME T_END=60. / <--- increase end time for restarted case
 MISC RESTART=.TRUE. / <--- add this line to restart the case
&DUMP DT_RESTART=60. / <--- comment out this line after restart
&MESH IJK=140,140,20, XB=0.,1400.,0.,1400.,-5.,195. /
&VENT MB='XMIN', SURF_ID='Left side' /
&VENT MB='YMAX', SURF_ID='Back side' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&SURF ID='Left side', COLOR='MINT', VEL=-0.8, VEL_T=-0.8,0.0 /
&SURF ID='Back side', COLOR='MINT', VEL=-0.8, VEL_T= 0.8,0.0 / <--- change VEL_T to -0.8,0.0 after restart
&SLCF PBZ=100, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&TAIL /
```

and it works fine. I cannot reproduce the error with your larger case. It is too complicated, and the mesh structure is not appropriate for this kind of calculation. If the problem persists, create a simple test case like the one I have created to clearly demonstrate the problem.

**Comment by DineshMyilsamy** [comment]
Thank you Mr.Kevin & Mr. Randy.

```
        I have referred and tried your like the given sample file.

        I agree your point regarding my mesh quality.

       When I specify T_END & DT_RESTART with same value of time,
```

restart file was not generated in FDS v6.3.2 (example T_END = 60
&  DT_RESTART = 60)

[image: Inline image 2]

[image: Inline image 4]

 Restart file was generated only when the T_END > DT_RESTART (example T_END
= 60.01 &  DT_RESTART = 60) .

```
      Regarding this I have searched FDS user guide but exactly I could
```

not find the answer for my doubt.

```
       I would like to know your comments.
```

**Comment by mcgratta** [comment]
That is probably a bug that fixed in the latest working version.
