### ISSUE TITLE
60 mesh case failing on burn

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3671]
Glenn, Kevin:
I've been trying to get the case in
/home4/rmcdermo/GitHub/fds-smv_rmcdermo/Validation/UMD_Line_Burner/EXP_M2/EXP_M2.fds

to run for many days now.  It keeps giving me REQ time outs.  I have even run on 5 dedicated nodes with 

qfds.sh -p 60 -n 12 -t EXP_M2.fds

Also, the original case used 314 radiation angles.  I commented that line out and seemed to have marginally better luck.  But hard to tell.  Ultimately, it still failed.

I'm out of ideas.  But I see no reason why we should not be able to get this case to work.  In fact, it did at one point.  But now I need to rerun.  If you have any suggestions, let me know.

**Comment by gforney** [comment]
do you think it is timing out because of a cluster setting or something in
FDS?  have you tried running on blaze?

On Thu, Mar 17, 2016 at 1:23 PM, Randy McDermott notifications@github.com
wrote:

> Glenn, Kevin:
> I've been trying to get the case in
> 
> /home4/rmcdermo/GitHub/fds-smv_rmcdermo/Validation/UMD_Line_Burner/EXP_M2/EXP_M2.fds
> 
> to run for many days now. It keeps giving me REQ time outs. I have even
> run on 5 dedicated nodes with
> 
> qfds.sh -p 60 -n 12 -t EXP_M2.fds
> 
> Also, the original case used 314 radiation angles. I commented that line
> out and seemed to have marginally better luck. But hard to tell.
> Ultimately, it still failed.
> 
> I'm out of ideas. But I see no reason why we should not be able to get
> this case to work. In fact, it did at one point. But now I need to rerun.
> If you have any suggestions, let me know.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3671

## 

Glenn Forney

**Comment by rmcdermo** [comment]
Haven't tried blaze yet.  That's a good idea.

**Comment by gforney** [comment]
refresh my memory.  exactly what is a REQ time out?  what are you seeing when it stops working?

**Comment by rmcdermo** [comment]
Kevin has timers on the loops that pass MPI information.  If they take too
long the code shuts down and gives a message saying which loop it was in
when it gave up.  The hope was to see if certain variables were more prone
than others to communication problems.

**Comment by mcgratta** [comment]
I'd like to try the case again when burn gets less busy.

**Comment by rmcdermo** [comment]
I will try on blaze as soon as I can.  Burn was not busy earlier today when
I was trying to run the case.

**Comment by mcgratta** [comment]
Are you still having trouble with this case?

**Comment by rmcdermo** [comment]
I quit trying to run it.  So, yes.  You can close this if you want.  But I
think it is worth keep this input file around to test burn.

**Comment by mcgratta** [comment]
I'm testing it now, using

```
qfds.sh -p 60 -n 4 EXP_M2.fds
```

**Comment by mcgratta** [comment]
This case timed out exchanging HS, US, VS, WS. I'm going to try

```
qfds.sh -p 60 EXP_MP.fds
```

**Comment by mcgratta** [comment]
This case ran successfully in 64 h, using the `qfds` command above. By default, this command launched 2 MPI processes on each node. This cluster (`burn`) seems to be sensitive to the number of MPI processes assigned to each node. I looked at the wall clock usage by the major subroutines, and there appear to be imbalances which I suspect are due to the fact that other jobs were running on the 30 nodes that were used for this job. The pattern of time usage in the `_cpu.csv` file does not indicate that it is related to the way that the meshes are arranged.

**Comment by rmcdermo** [comment]
Next time we have a clear cluster let's try

`qfds.sh -p 60 -n 12 -t EXP_M2.fds`

I think it would be good to get the bottom of why burn gives us trouble like this.

**Comment by mcgratta** [comment]
I'm running this case again to see if improvements in MPI help.

**Comment by mcgratta** [comment]
This case seems to be behaving itself. I'm closing the case and we'll reopen another if another case fails.
