### ISSUE TITLE
Adding new droplet evaporation routines undoes some older changes

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3706]
In commit

```
https://github.com/firemodels/fds-smv/commit/c4c17c2b27e765c38ffa747f3c24a442bb7f8ee9
```

it appears that some changes that I had made were written over. For example, I added RETURN statements to prevent the part routine from going into endless loops when numerical instabilities arise.

**Comment by drjfloyd** [comment]
Fixed (also added another RETURN that was not there previously for another call to shutdown in part.f90)

https://github.com/firemodels/fds-smv/commit/ad839006f2c8cc064623335cdfaf5c5ad47f87af
