### ISSUE TITLE
Orange smoke

### ISSUE THREAD

**Issue by FireCP** [firemodels/fds#3724]
Here are two snapshots, one showing the HRRPUV only and the other showing the HRRPUV plus the soot. When the soot is included, some of it is orange, making it look like the flames are larger. Is this intentional (i.e., showing hot soot continuing to glow) or is it a bug?
![fire_and_smoke](https://cloud.githubusercontent.com/assets/18124647/14088439/6b754b2c-f4e4-11e5-8f9b-1124dc5fedf3.jpg)
![fire_only](https://cloud.githubusercontent.com/assets/18124647/14088440/6b7f7aa2-f4e4-11e5-8387-5d7fa166a9dd.jpg)

[Example1.fds.txt](https://github.com/firemodels/fds-smv/files/192391/Example1.fds.txt)

**Comment by gforney** [comment]
the flame appearance should be consistent between the two views.  I'll take
a look.

On Mon, Mar 28, 2016 at 3:57 PM, FireCP notifications@github.com wrote:

> Here are two snapshots, one showing the HRRPUV only and the other showing
> the HRRPUV plus the soot. When the soot is included, some of it is orange,
> making it look like the flames are larger. Is this intentional (i.e.,
> showing hot soot continuing to glow) or is it a bug?
> [image: fire_and_smoke]
> https://cloud.githubusercontent.com/assets/18124647/14088439/6b754b2c-f4e4-11e5-8f9b-1124dc5fedf3.jpg
> [image: fire_only]
> https://cloud.githubusercontent.com/assets/18124647/14088440/6b7f7aa2-f4e4-11e5-8387-5d7fa166a9dd.jpg
> 
> Example1.fds.txt
> https://github.com/firemodels/fds-smv/files/192391/Example1.fds.txt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3724

## 

Glenn Forney

**Comment by gforney** [comment]
I'm not seeing what you are seeing. Use the Show/Hide>Labels menu to turn on the titles.  Let's make sure you are using the latest smokeview, (version 6.3.5).

I made the smoke a little thinner to make the fire a little more obvious.

![example1_thinsmokefire](https://cloud.githubusercontent.com/assets/12403014/14109169/d067096c-f58e-11e5-930d-902bba7b3a4b.png)

![example1_fire](https://cloud.githubusercontent.com/assets/12403014/14109156/c3a90018-f58e-11e5-9851-0529164416d5.png)

**Comment by gforney** [comment]
also when you generate the two images, generate them at the same time step

**Comment by gforney** [comment]
any update?

**Comment by gforney** [comment]
Haven't heard any feedback on this.  I'm assuming you've solved the problem by loading the latest smokeview.  If you are still having the problem with the latest smokeview , reopen the issue.
