### ISSUE TITLE
Better explanation of wall cell DEVC in FDS User Guide

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3754]
Add discussion about placement of XYZ for wall devices to be slightly on the +IOR side of the OBST.

**Comment by mcgratta** [comment]
I added the text

There are still instances where FDS cannot determine which solid surface is being designated, in which case an error message appears in the diagnostic output file. Re-position the probe and try again. It is best to position the device, via the real triplet XYZ, such that the device location is either at or within a cell width outside of the solid surface. The search algorithm in FDS will look for the nearest solid surface in the direction opposite to that indicated by IOR.
