### ISSUE TITLE
Segmentation Fault with EQUIBRIUM_MODEL

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3765]
I've been working on a case to test strong scaling of the particle routine. A smaller version of the case (below) fails with 

```
Numerical instability in particle energy transport, TMP_G
```

when I run it without the `EQUILIBRIUM_MODEL`. If I set the model to true, I get a seg fault in the call to `GET_VISCOSITY` when we do the convective heat transfer calculation for a droplet. It's a nasty case because of way the mesh boundaries cut through everything, but that's unavoidable when we chop up this sprinkler/mist cases. I'd rather purse the case where `EQUILIBRIUM_MODEL=.TRUE.` because the other old evaporation model is not worth pursuing. See if you can get this to fail and then we'll sort out a solution.

```
&HEAD CHID='spray_test2' /
&MESH IJK=18,12,32, XB=0.0,0.875,0.0,0.625,0.0,1.50, MULT_ID='mesh' /
&MULT ID='mesh', DX=0.875, DY=0.625, DZ=1.50, I_LOWER=3, I_UPPER=4, J_LOWER=2, J_UPPER=5, K_UPPER=1 /  16 meshes
&MISC EQUILIBRIUM_MODEL=.TRUE. /
&TIME T_BEGIN=-5., T_END=0., DT=0.005 /
&REAC FUEL='N-HEPTANE', CO_YIELD=0.006, SOOT_YIELD=0.015, CRITICAL_FLAME_TEMPERATURE=1560. /
&PART ID='heptane droplets', SAMPLING_FACTOR=1, INITIAL_TEMPERATURE=95., SPEC_ID='N-HEPTANE', DIAMETER=200., HEAT_OF_COMBUSTION=45000., QUANTITIES='PARTICLE TEMPERATURE','PARTICLE DIAMETER' /
&PROP ID='Bete P40', PART_ID='heptane droplets', FLOW_RATE=1.143, FLOW_TAU=3., PARTICLE_VELOCITY=8., SPRAY_ANGLE=0.,15. /
&SLCF PBX=3.6,QUANTITY='TEMPERATURE',CELL_CENTERED=.TRUE. /
&SLCF PBX=3.6,QUANTITY='INTEGRATED INTENSITY',CELL_CENTERED=.TRUE. /
&DEVC XYZ=3.60,1.80,1.00, PROP_ID='Bete P40', QUANTITY='TIME', SETPOINT=-60., ORIENTATION=0.,1.,0., ID='fuel_nozzle' /
TAIL /
```

**Comment by drjfloyd** [comment]
I'll take a look

**Comment by drjfloyd** [comment]
In general I feel we should avoid using HEAT_OF_COMBUSTION on PART. This is a bit of a hack. In this case there is only one fuel and that fuel has an HOC defined already based on the SPEC. There is no need to give a different HOC on the PART and force the fictitious creation or destruction of mass. Specify that fuel mass flow rate to be what it needs to be and let FDS determine the HOC to satisfy the REAC specification.

In this particular case I am seeing droplets reaching temperature of over 1000 C. At this point I have not determined what is causing that. 

I do not expect this to be a quick fix.

**Comment by mcgratta** [comment]
OK  -- this file is based on one of the USCG_HAI cases, so we have some legacy inputs there. I also saw droplet temps greater than 1000 C at the point of numerical instability when using the old evaporation routine. I cannot see these droplets in Smokeview, however, which leads me to think that the iteration is running away from us.

**Comment by drjfloyd** [comment]
I found one bug where I wasn't recomputing a variable when I needed to. It didn't crop up in the water_evaporation_1 and similar test cases since all the cells with particles in those are identical.  Fixing that there was still the high drop temp issue.

The drop mass and temperature are relaxed to equilibrium. In cells where there are both large and very small particles, the small particle may not evaporate fully with the relaxed solution. As a result the temperature update for the particle can have a lot of heat transfer from the hot gas to the small drop and a high temperature results. For the case where the equilibrium solution is all the mass evaporates fully, I have added logic to evaporate enough additional liquid from the particle to limit its temperature to the local vaporization temperature.

Running with that now and it has gone much further than before and still going; however, debug is showing I might have a logic flaw in the get_equilibrium function.  Guess it is whack-a-mole time (I figured this would happen once we started exercising the new routine in earnest).

**Comment by mcgratta** [comment]
No doubt, but it's good to do this now. I don't want to bother trying to debug the older stuff. The next possible problem, and maybe you have whacked it already, is where droplets land on a hot plate, as in the full version of this case. There I was getting an actual velocity instability (not the kind in the part routines) that appeared to originate near the plate surface. Let me know if you push up new code and I'll continue testing the cases.

**Comment by drjfloyd** [comment]
At this point the new routine only deals with the gas phase interactions. The wall adds a lot of potential complications, so I figured I would try and get gas working well then worry about the walls.

**Comment by mcgratta** [comment]
The assumption of the wall droplet is that its surface area is half that of an airborne droplet. Then there was some other assumption made when the surface droplet forms a film, but that assumption could use an overhaul. It has not been carefully looked at in 20 years.

**Comment by drjfloyd** [comment]
I pushed up some changes (https://github.com/firemodels/fds-smv/commit/376c443c83177f4c3f9b5a932f9d25a681769e70). The case now runs to completion. Over the time period run for there was a single timestep where one particle slightly exceeded the boiling temperature (by 0.8 C) when the equilibrium condition was for less than full evaporation.

**Comment by mcgratta** [comment]
Thanks. I'll try my cases again. I'm trying to put together a strong scaling test for a droplet application.

**Comment by drjfloyd** [comment]
I ran this case using the new evaporation routine and it completed. Can this issue be closed?

**Comment by mcgratta** [comment]
Let's leave it open until the old routine is deleted for good (unless there's another issue related to the new scheme). This will just remind us to do it.

**Comment by rmcdermo** [comment]
Where stands the old routine?  I think the version used in 6.5.3 is going to be Jason's implicit scheme, yes?  Let's close this one then.

**Comment by drjfloyd** [comment]
The old routine is currently disabled with a logical flag for the new scheme (set to TRUE to turn it on).  If we decide to use this in the next release, should that then be a minor release?  Have the various sprinkler validation cases been run successfully by validationbot since this was implement?

**Comment by rmcdermo** [comment]
OK, my misunderstanding.  Let's not purge old routine just yet.  You are correct, that would need a minor release.  I'm presently trying to get things cleaned up to get 6.5.3 out the door.

**Comment by drjfloyd** [comment]
In that case, when compiling for 6.5.3 release we should set the EVAP_2 flag to false.

**Comment by rmcdermo** [comment]
Well, let's set it to F then.  Will anything break in firebot do you think?  Is so, then we might as well plan for minor release instead.

**Comment by drjfloyd** [comment]
Shouldn't break firebot. The cases were all working with the old routine.
one case was changed slightly for new but old should still work (bigger
domain for more time for evaporation for new routine)

**Comment by mcgratta** [comment]
This issue is resolved.
