### ISSUE TITLE
Consistency of Smokeview HRR contours 

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3768]
The attached images show a simulation with a 1000 kW fire and open boundaries. My question is related to the display of the HRR contours:
1. When I display only the HRR contours, the volume with HRRPUV > 200 kW/m3 is relatively small.
2. When I display only soot, the volume is large.
3. When I display soot and HRR, then the volume with HRRPUV > 200 kW/m3 is also large. 
4. Finally, a slice plane of HRR indicates a volume somewhat smaller than the display of HRR and soot.

My concern is the large difference between the displayed HRR volume with and without soot (cases 1 and 3). Should I just rely on slice planes as the most accurate?

Thanks,
Dan

![model](https://cloud.githubusercontent.com/assets/13338306/14324590/ff92f4fa-fbea-11e5-9947-0b60e713c31e.png)

![display hrr only](https://cloud.githubusercontent.com/assets/13338306/14324603/0851c878-fbeb-11e5-8ab9-3691e904d71e.png)

![display soot only](https://cloud.githubusercontent.com/assets/13338306/14324605/0e44b68c-fbeb-11e5-9d29-079250393466.png)

![display hrr and soot](https://cloud.githubusercontent.com/assets/13338306/14324614/192eeb08-fbeb-11e5-96dc-75f24275e3f9.png)

![display slice of hrrpuv](https://cloud.githubusercontent.com/assets/13338306/14324617/1cbf64b4-fbeb-11e5-8d5b-d84fd48112c6.png)

[burner.txt](https://github.com/firemodels/fds-smv/files/206860/burner.txt)

**Comment by gforney** [comment]
the display of hrr with or without soot should be the same.  what version of smokeview are you using.  can you upload your input file

**Comment by dvswenson** [comment]
I am running Smokeview 6.3.2. The FDS file is attached, it does not take long to run.

[burner.fds.txt](https://github.com/firemodels/fds-smv/files/207035/burner.fds.txt)

**Comment by gforney** [comment]
I'm not able to reproduce the problem but I fixed some bugs with smoke and fire display a while back.  Try the latest smokeview, 6.3.6 .
https://pages.nist.gov/fds-smv/downloads.html

**Comment by dvswenson** [comment]
I also tested with Smokeview 6.3.6 and did not see the problem. So it is fixed.
Thanks.

**Comment by gforney** [comment]
good to hear.  thanks,
glenn

On Mon, Apr 11, 2016 at 9:36 AM, dvswenson notifications@github.com wrote:

> I also tested with Smokeview 6.3.6 and did not see the problem. So it is
> fixed.
> Thanks.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3768#issuecomment-208346611

## 

Glenn Forney
