### ISSUE TITLE
Restart file not written when T_END and DT_RESTART are equal

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3769]
In the attached simulation T_END and DT_RESTART are equal but no restart file is written at the end of the simulation. Writing the restart file when the times are equal is a nice feature when setting up long jobs. I am running FDS 6.3.2.

Thanks,
Dan
[burner.txt](https://github.com/firemodels/fds-smv/files/206886/burner.txt)

**Comment by drjfloyd** [comment]
Dan, 

You already reported this as https://github.com/firemodels/fds-smv/issues/3318

We just released 6.4.  Check to see if it is fixed there. If not, please reply back to the original issue

**Comment by dvswenson** [comment]
Jason,

Thanks.

I will test.

Dan

On Wed, Apr 6, 2016 at 12:05 PM, Jason Floyd notifications@github.com
wrote:

> Dan,
> 
> You already reported this as #3318
> https://github.com/firemodels/fds-smv/issues/3318
> 
> We just released 6.4. Check to see if it is fixed there. If not, please
> reply back to the original issue
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3769#issuecomment-206467324

## 

Daniel Swenson
Thunderhead Engineering
www.thunderheadeng.com
swenson@thunderheadeng.com
+1.785.770.8511 x103

**Comment by dvswenson** [comment]
I tested with FDS 6.4.0 and the problem is fixed.

**Comment by dvswenson** [comment]
Jason,

I tested with FDS 6.4.0 and the problem is fixed.

Thanks,
Dan

On Wed, Apr 6, 2016 at 1:29 PM, Daniel Swenson swenson@thunderheadeng.com
wrote:

> Jason,
> 
> Thanks.
> 
> I will test.
> 
> Dan
> 
> On Wed, Apr 6, 2016 at 12:05 PM, Jason Floyd notifications@github.com
> wrote:
> 
> > Dan,
> > 
> > You already reported this as #3318
> > https://github.com/firemodels/fds-smv/issues/3318
> > 
> > We just released 6.4. Check to see if it is fixed there. If not, please
> > reply back to the original issue
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/firemodels/fds-smv/issues/3769#issuecomment-206467324
> 
> ## 
> 
> Daniel Swenson
> Thunderhead Engineering
> www.thunderheadeng.com
> swenson@thunderheadeng.com
> +1.785.770.8511 x103

## 

Daniel Swenson
Thunderhead Engineering
www.thunderheadeng.com
swenson@thunderheadeng.com
+1.785.770.8511 x103
