### ISSUE TITLE
Uninstall script is empty

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#3776]
The uninstall script for FDS 6.4 does not contain any commands to uninstall:

@echo off

echo.
echo **\* Uninstalling FDS and Smokeview
echo.
echo Press any key to proceed or CTRL C to abort
pause>NUL

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
that file is built on the fly by the wrapup batch file during the installation process using the installation location you choose.  It should contain something like the following.  Look in your uninstall directory.  It should contain something like the attached image.  I"ll have to think about why your file did not get setup.  The fds install runs as administrator.  do you remember having to type an admin password?

![uninstall_dir](https://cloud.githubusercontent.com/assets/12403014/14396504/e98080d0-fda5-11e5-87e1-ecdd2906526b.png)

@echo off

echo.
echo **\* Uninstalling FDS and Smokeview
echo.
echo Press any key to proceed or CTRL C to abort
pause>NUL
"c:\Program Files\firemodels\FDS6\Uninstall\uninstall.vbs"  
echo Uninstall complete  
pause

**Comment by drjfloyd** [comment]
I have all those files in my directory. I did not get asked to type an admin password

**Comment by drjfloyd** [comment]
I tried installing again and now the uninstall bat file is what you show.  So just some glitch I guess?

**Comment by gforney** [comment]
I guess.  makes me nervous!  let me know if it happens again.

On Fri, Apr 8, 2016 at 4:34 PM, Jason Floyd notifications@github.com
wrote:

> I tried installing again and now the uninstall bat file is what you show.
> So just some glitch I guess?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3776#issuecomment-207592463

## 

Glenn Forney
