### ISSUE TITLE
Smokeview: incorrect device values displayed

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#3777]
Hi Glenn,

Please see the attached file and image. The sprinkler link has an activation temperature of 74 C, and it activates at that point according to the device file. However, the device value is  that is displayed is much lower.

Thanks

Dave
[hrr_freeze_multiple_sprinklers_com.fds.txt](https://github.com/firemodels/fds-smv/files/210463/hrr_freeze_multiple_sprinklers_com.fds.txt)
![link temp](https://cloud.githubusercontent.com/assets/13259079/14389882/95079d2c-fd82-11e5-9204-8eab0933954b.PNG)

**Comment by gforney** [comment]
I used the fds and smokeview from the latest windows bundle at github to run and view your case. I'm not able to reproduce the problem.  see the attached image.  What versions of fds and smokeview are you using?

![hrr_freeze_multiple_sprinklers_com_0442](https://cloud.githubusercontent.com/assets/12403014/14391213/bcd3d63a-fd88-11e5-880c-99e04dd3d3ed.png)

**Comment by Dave-McGill** [comment]
Hi Glenn,

I installed the latest version this morning, before I ran this case. When I reload it, I'm getting the proper results. That is very odd. It's working fine now, so I won't worry about it.

Thanks

**Comment by gforney** [comment]
weird - report back if you get any more clues as to what was going on.
