### ISSUE TITLE
FDS-SMV Verification Guide

### ISSUE THREAD

**Issue by spoole12** [firemodels/fds#3782]
For a project I am running the Pressure_Solver Hallways fds input simulation and noticed that it does not have a section in the Verification Guide. I was wondering if there was a portion of the Pressure_Solver Hallways that could be added to the Verification Guide.

Thank you!

**Comment by mcgratta** [comment]
I'll add a verification case. It was originally just a qualitative example, but I can probably think of something to check, like mass conservation.

**Comment by spoole12** [comment]
Thank you! I appreciate that!

**Comment by mcgratta** [comment]
I used the hallways example to test conservation of energy and added this to the User's Guide section on Heat Release Rate.#3841
