### ISSUE TITLE
Connectivity MPI issue Linux 

### ISSUE THREAD

**Issue by szakalboss** [firemodels/fds#3786]
I guess you should improve a bit error handling for MPI connectivity between the grids. It is currently allowed to allocate 30 neighbouring meshes. I was running a case where I have actually more neighbours (grid is refined in one building compartment, and is coarse on top of the roof - environment side). It was running perfectly on Windows since it was using OpenMP, however on Linux cluster it was just crashing with invalid memory reference but no more explicit error was given such as "you have too many grids connected to grid no. X"

affected line 
ALLOCATE(M%NEIGHBORING_MESH(30)) in read.f90

**Comment by rmcdermo** [comment]
Kevin,
Please have a look.

**Comment by mcgratta** [comment]
This is by design. Could you post your case so that I can debug it.

**Comment by szakalboss** [comment]
Not really, I cannot post my files...
I have given you the problem description and the line in the code that is reponsible of that.

You can create two meshes connected to each other. Then you can split one of them so that it will contain more than 30 faces at the connecting surface with other mesh. Then the code will crash with MPI for sure.

**Comment by mcgratta** [comment]
I have removed the limit on the number of neighboring meshes. If you can compile the latest test version of the code, let me know it it works for you. Otherwise, this will come out in the next release.

**Comment by szakalboss** [comment]
I just increased this limit to 300 for me... Thx for info

**Comment by mcgratta** [comment]
Did you recompile the code?

**Comment by szakalboss** [comment]
Yes

**Comment by mcgratta** [comment]
In the latest version of the code, I increased the limit to 10000. I allocate and deallocate an array to count the neighboring meshes. Can you compile and test this code?

**Comment by szakalboss** [comment]
this is currently impossible to recompile the code since I modified it in more places and I am using it all the time; 
however I reviewed your implementation and it seems to be fine, except line 717: I would create DO loop instead of using 1:M%NEIGHBOURING_MESHES which can create temporary array. And it is I guess more save when there is not neighbour btw.

DO i_neighbours = 1, M%N_NEIGHBORING_MESHES
   M%NEIGHBORING_MESH(i_neighbours) = NEIGHBOR_LIST(i_neighbours)
END DO

**Comment by mcgratta** [comment]
Good idea, thanks.

**Comment by szakalboss** [comment]
Don't mention it 😀
