### ISSUE TITLE
grid lines Smokeview

### ISSUE THREAD

**Issue by szakalboss** [firemodels/fds#3791]
I have a technical question: is it possible to remove grid lines from Smokeview? I have lot of meshes created and could not find any method to remove these lines...

Thx in advance

**Comment by gforney** [comment]
pressing the 'g' key cycle through various methods for viewing the grid

**Comment by szakalboss** [comment]
But this is not removing them completely. The lines between meshes are always there... Smokeview 6.3.5 btw.

**Comment by gforney** [comment]
upload a sample case to show what you are talking about

On Mon, Apr 18, 2016 at 2:18 PM, Karol Swiderski notifications@github.com
wrote:

> But this is not removing them completely. The lines between meshes are
> always there... Smokeview 6.3.5 btw.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3791#issuecomment-211510445

## 

Glenn Forney

**Comment by rmcdermo** [comment]
Also, try hitting "o"

**Comment by szakalboss** [comment]
o - removes/changes view for obstacles
g - removes/changes view for grid

none of them is removing the lines between separate grids, see attached example
Btw, I found this discussion (guess it's unresolved): https://groups.google.com/forum/#!topic/fds-smv/hQZ4JchC9KA
![1](https://cloud.githubusercontent.com/assets/17323621/14615882/21cd9aea-05a8-11e6-8760-4b9ef512eeb3.png)

**Comment by gforney** [comment]
upload your input file and I"ll take a look at it

On Mon, Apr 18, 2016 at 2:57 PM, Karol Swiderski notifications@github.com
wrote:

> o - removes/changes view for obstacles
> g - removes/changes view for grid
> 
> none of them is removing the lines between separate grids, see attached
> example
> [image: 1]
> https://cloud.githubusercontent.com/assets/17323621/14615882/21cd9aea-05a8-11e6-8760-4b9ef512eeb3.png
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3791#issuecomment-211528302

## 

Glenn Forney

**Comment by szakalboss** [comment]
cannot, confidential...

**Comment by gforney** [comment]
then reproduce the problem in a case that is not confidential

On Mon, Apr 18, 2016 at 3:33 PM, Karol Swiderski notifications@github.com
wrote:

> cannot, confidential...
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3791#issuecomment-211542729

## 

Glenn Forney

**Comment by szakalboss** [comment]
well the issue is with obstacles and their outlines, but these outlines correspond to mesh blocks; when I want to hide an obstacle I can still see these outlines where the obstacles are hidden and cannot figure out how to get rid of them; attached example

[case.zip](https://github.com/firemodels/fds-smv/files/224689/case.zip)

**Comment by szakalboss** [comment]
I just figured it out, I used outline=true in the fds file... and that was the reason ;
however this should show only 8 outlines for each obstacle, whereas it is showing them everywhere where the grid is split; so there is an issue: how to completely hide an obstacle from being displayed as the multiple mesh outlines?

**Comment by gforney** [comment]
fds splits each blockage by mesh - corresponding to how the computation is performed (by mesh).  presently, smokeview views blockages as they are computed which is why you don't see 8 outlines but see 8 outlines for each mesh in which the blockage resides.  If you want to completely hide the blockages chose the Show/Hide>Geometry>Obstacles>Hidden menu item
