### ISSUE TITLE
Numerical Instability in FDS v. 6.4 - Particle Screen

### ISSUE THREAD

**Issue by JBSidhi** [firemodels/fds#3795]
Hi,

This model is a case where I am filling an empty room with methane gas. One wall contains a door with a particle screen to represent a louvered vent. I am getting a numerical instability at 9.55 seconds in FDS version 6.4, where there were no instabilities in FDS version 6.3.2. I was able to narrow down the error to the particle screen. If I comment out the particle screen, the file runs through to completion. I am running this file on an Intel i7, Windows 7 Pro pc. Thanks in advance for any input.

&HEAD CHID='TESTCH4', TITLE='Fill an empty room with methane' /
&MESH IJK=50,50,30, XB=0.0,5.0,0.0,5.0,0.0,3.0 /
&TIME T_END=1800.0 /
&SPEC ID='METHANE' /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&OBST XB=1.0,1.6,2.3,2.4,0.3,0.4, SURF_ID6='INERT','LEAK','INERT','INERT','INERT','INERT'/
&SURF ID='LEAK', SPEC_ID='METHANE',VOLUME_FLOW=-0.0021, COLOR='RED', MASS_FRACTION(1)=1.0/

&OBST XB=1.0,4.3,0.9,1.0,0.0,2.7/
&OBST XB=1.0,4.3,3.7,3.8,0.0,2.7/
&OBST XB=0.9,1.0,0.9,3.8,0.0,2.7/
&OBST XB=4.3,4.4,0.9,3.8,0.0,2.7/
&OBST XB=0.9,4.4,0.9,3.8,2.7,2.8,COLOR='INVISIBLE'/
&HOLE XB=1.1,1.3,3.2,3.4,2.6,2.9/VENT
&HOLE XB=2.0,3.0,0.8,1.1,0.0,2.0/DOOR
&OBST XB=2.0,2.3,0.9,0.91,0.0,2.0,COLOR='GRAY',PERMIT_HOLE=.FALSE./
&OBST XB=2.7,3.0,0.9,0.91,0.0,2.0,COLOR='GRAY',PERMIT_HOLE=.FALSE./

&INIT XB=2.3,2.7,0.9,0.91,0.0,2.0, N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., PART_ID='SCREEN'/
&PART ID='SCREEN', DRAG_LAW='SCREEN', FREE_AREA_FRACTION=0.4, STATIC=.TRUE., SURF_ID='SCREEN', ORIENTATION(1:3,1)=0,1,0 /
&SURF ID='SCREEN', THICKNESS=0.00015, GEOMETRY='CYLINDRICAL', MATL_ID='ALUMINUM' /
&MATL ID='ALUMINUM', DENSITY=2700., CONDUCTIVITY=200., SPECIFIC_HEAT=0.9 /

&SLCF PBY=2.4, QUANTITY='VOLUME FRACTION',SPEC_ID='METHANE'/
&SLCF PBX=2.5, QUANTITY='VOLUME FRACTION',SPEC_ID='METHANE'/
&SLCF PBY=2.9, QUANTITY='VELOCITY', VECTOR=.TRUE./
&SLCF PBX=2.5, QUANTITY='VELOCITY', VECTOR=.TRUE./
&TAIL /

**Comment by drjfloyd** [comment]
I'll try to figure out why, but the drag cfl limit I added to fix a porous media issue isn't working for your case.  You can disable it by setting DRAG_CFL_MAX on MISC to a very large number (I set it to 1e5).

**Comment by JBSidhi** [comment]
Adding DRAG_CFL_MAX to the MISC line with a large number seems to have worked. The model is progressing past the point of the instability. I will keep you posted if anything else arises. Thank you.

**Comment by tstopi** [comment]
So i tried to use the particle screen model and ran in to problems. No instabilities (this time) but very slow execution times. 

I did a little digging and I think I have a clue as to what the problem is:

The particle momentum source terms (and DRAG_CFL) are calculated at the beginning of the CORRECTOR step using velocities from PREDICTOR. The CFL stability condition is only checked after  PREDICTOR, so even thought the DRAG_CFL only applies at the beginning of the next time step.

Simplest fix would  be to simply evolve the parcels at the beginning of PREDICTOR. This seems to solve stability issues with the stationary  particles. If there is a good reason to keep the evaluation where it is, then perhaps  the stability check could also be performed after CORRECTOR.

**Comment by drjfloyd** [comment]
If you have proposed code changes, can you do a pull request for them?

**Comment by tstopi** [comment]
Well, my first idea was to simply change the line

IF (CORRECTOR) CALL MOVE_PARTICLES(T,DT,NM)

to

IF (PREDICTOR) CALL MOVE_PARTICLES(T,DT,NM)

This works fine for stationary particles but not for sprays/moving particles.  The reason being that if time step changes after the PREDICTOR we should rewind the particles before rerunning the step. But old particle positions and velocities are not saved. The error shouldn't be big, but it breaks fluid_part_mom_\* verification cases. I'll do pull request if I can figure out how to do this without breaking anything.

**Comment by mcgratta** [comment]
The order in which momentum terms are added to the momentum equation via FVX, FVY, and FVZ is very important. Jason is currently working with the particle routines, so I would not want to make a change like this now.

**Comment by mcgratta** [comment]
This case is working with the latest working version, which will be FDS 6.6.0. If this problem arises again, start a new issue.
