### ISSUE TITLE
Segmentation Fault due to Different Mesh Sizes

### ISSUE THREAD

**Issue by DennisPau** [firemodels/fds#3800]
[Segmentation Fault.zip](https://github.com/firemodels/fds-smv/files/231085/Segmentation.Fault.zip)

Hi Kevin, please find attached Segmentation.zip containing two files, CF1 and CF1_400.

We continue to do some troubleshooting ourselves, and believe the issue might be due to different cell sizes of the multi meshes specified.

'CF1_400' contains multi meshes with same cell size of 0.4 m and this runs fine on the server.
'CF1' contains multi meshes with cell size of 0.4 m except for MESH 4 with finer 0.2 m and this causes the segmentation fault. However, this is completed on standalone laptop.

Much appreciate your help and feedback, thanks.
Dennis

**Comment by mcgratta** [comment]
At what point in the simulation does the seg fault occur? What is the operating system and version of FDS?

**Comment by DennisPau** [comment]
For CF1, this occurs right from the start.
- Intel i7 - 3770, 3.4 GHz, 4 cores, 8 threads, 32 GB RAM Linux system.
- FDS is invoked with OpenMP.
- The version of FDS is 6.2.3.

**Comment by mcgratta** [comment]
Do something like the following on your head node. The location of your mpirun might be different than mine.

```
[mcgratta@burn Test]$ export OMP_NUM_THREADS=1
[mcgratta@burn Test]$ /shared/openmpi_64ib/bin/mpirun -np 8 ~/FDS/FDS6/bin/fds CF1.fds
 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 Mesh      3 is assigned to MPI Process      2
 Mesh      4 is assigned to MPI Process      3
 Mesh      5 is assigned to MPI Process      4
 Mesh      6 is assigned to MPI Process      5
 Mesh      7 is assigned to MPI Process      6
 Mesh      8 is assigned to MPI Process      7
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : April 28, 2016  09:00:07
 Version          : FDS 6.4.0
 Revision         : Git-r10-48-g5996289
 Revision Date    : Thu Apr 7 11:24:39 2016 -0400
 Compilation Date : Apr 07, 2016  11:43:03

 MPI Enabled; Number of MPI Processes:     8
 OpenMP Enabled; Number of OpenMP Threads:   1

 MPI version: 3.0
 MPI library version: Open MPI v1.8.4, package: Open MPI gforney@blaze Distribution, ident: 1.8.4, repo rev: v1.8.3-330-g0344f04, Dec 19, 2014

 Job TITLE        :
 Job ID string    : CF1

 Time Step:      1, Simulation Time:      0.06 s
 Time Step:      2, Simulation Time:      0.12 s
 Time Step:      3, Simulation Time:      0.17 s
 Time Step:      4, Simulation Time:      0.23 s
 Time Step:      5, Simulation Time:      0.29 s
```

Post what happens (to enter screen text, use three backward quotes (```) at the start and end of the text and then use Preview to see it). I want to know what version of Open MPI is installed on your computer. If it's not version 1.8.x, it probably won't work.

**Comment by DennisPau** [comment]
Hi Kevin, this is what we get from running CF1 with the added command.

fire@leviathan:~/FDS/local/Test1$ export OMP_NUM_THREADS=1
fire@leviathan:~/FDS/local/Test1$ fds_openmp CF1.fds
-bash: fds_openmp: command not found
fire@leviathan:~/FDS/local/Test1$ fds6_openmp CF1.fds
 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      0
 Mesh      3 is assigned to MPI Process      0
 Mesh      4 is assigned to MPI Process      0
 Mesh      5 is assigned to MPI Process      0
 Mesh      6 is assigned to MPI Process      0
 Mesh      7 is assigned to MPI Process      0
 Mesh      8 is assigned to MPI Process      0
 OpenMP thread   7 of   7 assigned to MPI process      0 of      0
 OpenMP thread   0 of   7 assigned to MPI process      0 of      0
 OpenMP thread   6 of   7 assigned to MPI process      0 of      0
 OpenMP thread   3 of   7 assigned to MPI process      0 of      0
 OpenMP thread   1 of   7 assigned to MPI process      0 of      0
 OpenMP thread   2 of   7 assigned to MPI process      0 of      0
 OpenMP thread   4 of   7 assigned to MPI process      0 of      0
 OpenMP thread   5 of   7 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source  
fds6               00000000007E2C55  Unknown               Unknown  Unknown
fds6               00000000007E0A17  Unknown               Unknown  Unknown
fds6               0000000000791FF4  Unknown               Unknown  Unknown
fds6               0000000000791E06  Unknown               Unknown  Unknown
fds6               000000000070D429  Unknown               Unknown  Unknown
fds6               00000000007142A0  Unknown               Unknown  Unknown
libpthread.so.0    00007F763B1C1880  Unknown               Unknown  Unknown
fds6               0000000000B1BF86  Unknown               Unknown  Unknown
fds6               0000000000B0E4E4  Unknown               Unknown  Unknown
fds6               00000000007F6DA6  Unknown               Unknown  Unknown
fds6               000000000040869E  Unknown               Unknown  Unknown
libc.so.6          00007F763AE2AB45  Unknown               Unknown  Unknown
fds6               00000000004085B9  Unknown               Unknown  Unknown

Our Open MPI version is older, I believe 1.6.X and that has been updated to latest, 1.10.X but this still wouldn't work. IT guys are digging for 1.8.X but they remain doubtful that this will make a difference. Does it absolutely need to be version 1.8.X? Any feedbacks would be appreciated, thanks.

**Comment by mcgratta** [comment]
Upgrade to the latest version (6.4.0). This conversation is pointless if I cannot test your case with the latest version.

**Comment by mcgratta** [comment]
I suggest that you compile the code yourself using whatever version of Open MPI you have installed. We have to choose a specific version to build against, and if you do not have this version, the code may not run.

**Comment by DennisPau** [comment]
Thanks for the advice, Kevin. I believe the IT team has compile the code again but the problem still remains. I've attached correspondence I received from IT and also the error message received.

Any advice would be appreciated, thanks.
Dennis
[Correspondence from IT.pdf](https://github.com/firemodels/fds-smv/files/285533/Correspondence.from.IT.pdf)
[Segmentation Error Message 24.05.2016.pdf](https://github.com/firemodels/fds-smv/files/285534/Segmentation.Error.Message.24.05.2016.pdf)

**Comment by drjfloyd** [comment]
Run the case that fails as a single-process job just to see if starts time stepping.  If it still fails during initialization then MPI might be a red herring and the issue could be some other error either in FDS or in the input file.

**Comment by DennisPau** [comment]
Hi Jason, yes we successfully completed the failed job (CF1.fds) on a single processor before hence this is quite puzzling.

**Comment by mcgratta** [comment]
Are you using FDS 6.4.0? What is the Git hash?

**Comment by DennisPau** [comment]
Yes Kevin, I believe we are using FDS 6.4.0. Info below:

Current Date     : May 16, 2016  09:27:14
 Version          : FDS 6.4.0
 Revision         : Git-r10-48-g5996289
 Revision Date    : Thu Apr 7 11:24:39 2016 -0400
 Compilation Date : Apr 07, 2016  11:43:03

**Comment by foolstone** [comment]
I can get the case (CF1.fds) running with either FDS 6.4.0 or very early version FDS 6.1.1.  
I can't produce the same error.  
Dennis, could you show the output of 'ulimited -a'?

**_FDS 6.4.0**_
 Fire Dynamics Simulator

 Current Date     : June  2, 2016  11:53:09
 Version          : FDS 6.4.0
 Revision         : Git-r10-450-g9809181
 Revision Date    : Wed May 18 00:30:15 2016 +0800
 Compilation Date : May 18, 2016  00:47:38

 MPI Enabled; Number of MPI Processes:     1
 OpenMP Enabled; Number of OpenMP Threads:   2

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Linux\* OS

**_FDS 6.1.1**_
Fire Dynamics Simulator

 Compilation Date : Wed, 2014-08-27
 Current Date     : June  2, 2016  11:51:35
 Version          : FDS 6.1.1
 SVN Revision No. : 20338

 MPI Enabled; Number of MPI Processes:     1
 OpenMP Enabled; Number of OpenMP Threads:   2

**Comment by mcgratta** [comment]
Any progress on this issue?

**Comment by DennisPau** [comment]
Thanks for the input 'foolstone' - sorry I've been busy last fortnight. I'll talk to IT first and get back to the forum, thanks. Dennis.

**Comment by DennisPau** [comment]
[Correspondence from IT - ulimit.pdf](https://github.com/firemodels/fds-smv/files/315418/Correspondence.from.IT.-.ulimit.pdf)

Hi All, please find attached correspondence I received from our IT person. Let me know if you need more info on this, thanks Dennis.

**Comment by mcgratta** [comment]
I can only suggest that you compile both FDS and Open MPI. I see that you are using the OpenMPI library that we (Glenn Forney) compiled. The reason why MPI codes sometimes do not run is that there are inconsistent libraries used to compile the various parts.

**Comment by gforney** [comment]
we built the openmpi library using the Intel compilers.  if you built fds
using the gnu compilers then I would build the openmpi using the gnu
compilers also.

On Wed, Jun 15, 2016 at 8:25 AM, Kevin McGrattan notifications@github.com
wrote:

> I can only suggest that you compile both FDS and Open MPI. I see that you
> are using the OpenMPI library that we (Glenn Forney) compiled. The reason
> why MPI codes sometimes do not run is that there are inconsistent libraries
> used to compile the various parts.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3800#issuecomment-226171625,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRgrwX16PJ8CH_TgO0gBE2KehigdBks5qL-8ngaJpZM4INR1B
> .

## 

Glenn Forney

**Comment by DennisPau** [comment]
Hi All, I've corresponded with IT and we're looking to recompile both FDS and Open MPI. I'll report back whether this solve the issue or not, hopefully is the former. Thanks for all the help and suggestion thus far.

Dennis

**Comment by mcgratta** [comment]
Any progress?
