### ISSUE TITLE
FDS graphs

### ISSUE THREAD

**Issue by mrvlty** [firemodels/fds#3805]
Hi everyone, 
When a simulation finishes, SMW opens and we can easily visualize the temprature, velocity...etc. profiles depend on the time. But in same papers including numerical analysis used fds, there is Temperature(C)- Height (m)  or Velocity(m/s)-L longitudinal lenght (m) ... etc graphics as attached below.
 I want to know that can I plot this graphics in FDS in a one step or is it required additional process using other softwares (excell...etc)?

![t c - z m graphic](https://cloud.githubusercontent.com/assets/16001133/14776804/72f5090c-0ad1-11e6-949a-039e34fa7f4b.png)

![velocity-x m](https://cloud.githubusercontent.com/assets/16001133/14777257/99e18074-0ad4-11e6-866d-77aa841f62f5.png)

**Comment by drjfloyd** [comment]
Questions on using FDS should be posted to the discussion forum. The issue tracker is for reporting bugs and requesting model enhancements.
