### ISSUE TITLE
Baroclinic torque in tunnel geometries

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3807]
This is a simple case that fails unless `BAROCLINIC` is set to `.FALSE.`

```
&HEAD CHID='tunnel_2d' /
&TIME T_END=10. /
 MISC BAROCLINIC=.FALSE. /  <-- This line needed to prevent numerical instability
&MESH IJK=768,1,16, XB=0.0,12.0,-0.01,0.01,0.0,0.25 /
&REAC FUEL='PROPANE' /
&SURF ID='fire.source', COLOR='RED', HRRPUA=2126.0 /
&SURF ID='entrance', VEL=-0.3 /
&VENT SURF_ID='fire.source', XB=5.955,6.044,-0.01,0.01,0.0,0.0, COLOR='RED'/
&VENT SURF_ID='entrance', PBX=0.0, COLOR='BLUE' /
&VENT SURF_ID='OPEN', PBX=12.0 /
&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBY=0.0/
&SLCF QUANTITY='DIVERGENCE', CELL_CENTERED=.TRUE., PBY=0. /
&SLCF QUANTITY='H',          CELL_CENTERED=.TRUE., PBY=0. /
&SLCF QUANTITY='HRRPUV',     CELL_CENTERED=.TRUE., PBY=0. /
&TAIL /
```

**Comment by mcgratta** [comment]
I can run the above case successfully if I call `BAROCLINIC_CORRECTION` from inside the `PRESSURE_ITERATION` loop in `main.f90`, just before I call `NO_FLUX`. The purpose is to more tightly couple `H` and `KRES` when computing the pressure in the baroclinic torque term. 

There are still things to work out, like what to do in cases where we do not have to iterate the pressure solver.

**Comment by mrvlty** [comment]
Mr. Mc Grattan ,
I can't understand your last advice exactly. Could you please clarify it? 
Now I am installing the older version of fds as Daniel Swenson advised. However I want to implement your advice too to compare the results of them. This study will be a part of my master thesis so finding a best solution method is really important for me. 
Thank you for your support.

**Comment by mcgratta** [comment]
It's a bit complicated, but I'll try. Look at the FDS Technical Reference Guide, 2.5 Momentum Transport. Eq. 2.11 is the form of the momentum equation that we use. Notice the terms grad H and p grad (1/rho). Ideally, these terms could be combined as (1/rho) grad p. However, if we did this, we would have to solve (in Eq. 2.13) a non-separable elliptic PDE for the pressure:

grad (1/rho) grad p = ...

But we do not have a fast solver for this equation. Instead, we break up this term and solve for H. But we have to use an older value of p in the term p grad (1/rho). p is extracted from H as

p = rho (H-0.5 |u|^2)

and my concern is that the old value of p is inconsistent with the updated value of u. This has not been a problem in most geometries, but I think it is a problem in your case of a long tunnel.

**Comment by mrvlty** [comment]
Ok,Mr.McGrattan ,
I will follow your instructions. Thank you for your explanations.

**Comment by mcgratta** [comment]
One way to better understand the problem is to take the case above and move the fire near the opening of the tunnel, and then move the fire near the closed end of the tunnel. If the fire is near the opening, the case runs. If it is near the closed end, it fails readily with an instability. The difference is the relative value of p that is extracted from H and |u|^2/2. I need to see if there is a better way to extract p from H.

**Comment by mrvlty** [comment]
I couldn't releate all these equations to  a physical study after your first massage however your second massege is quite clear. So i got it now.

**Comment by mcgratta** [comment]
I believe that I have fixed the instability problem in tunnels. I have committed new code to the FDS repository, but we do not want to issue a new official release until the code is run through the validation cases, which takes a few weeks. In the meantime, does anyone who is monitoring this thread have the ability to compile code from the repo?

**Comment by dvswenson** [comment]
I have tested your fix on the problem originally submitted by mrvlty as issue 3794. It now runs successfully to the end.

Big thanks for working on this so promptly and getting it fixed.

**Comment by mcgratta** [comment]
Big thanks for compiling and testing it. We're running the validation cases now and hope to do a maintenance release this week or next.

**Comment by mrvlty** [comment]
Hi Mr. @mcgratta  ,

I can model my tunnel with no obstruction with your and @dvswenson helps I really apreciate your hard working. I run my simulation with no obtruction but other step of my study is running the same case with an obstruction.For that reason in the experimental study a model train with 0,15_0,2_8 m3 dimensions was used and ı decided to use a similar model vehicle with  0,15_0,2_4 m3 dimensions. when i try to run it with that obtruction, Program gave the numerical instability error again. I can guess what cause that error but I don't know how i can solve it? Some files attached below. Couldyou please share your opinion about it and help me to solve it ?

Best Regards 
Merve

![error](https://cloud.githubusercontent.com/assets/16001133/15432977/02366354-1eb9-11e6-99d6-e31b5a48d839.png)

![model](https://cloud.githubusercontent.com/assets/16001133/15432502/242f1cc8-1eb7-11e6-8ab4-4ff3af0ef6e7.png)

[fds input file.txt](https://github.com/firemodels/fds-smv/files/274893/fds.input.file.txt)

**Comment by mcgratta** [comment]
The input file is corrupted.

**Comment by mcgratta** [comment]
Try changing the 8's to 16's on the MESH lines.

**Comment by mrvlty** [comment]
Yes you are right, I didn't realized that the file was corrupted in the previous one.

I send you input file and a screen shot of the numerical instability error log.

 [tu.txt](https://github.com/firemodels/fds-smv/files/275525/tu.txt)

![numericl instability](https://cloud.githubusercontent.com/assets/16001133/15443874/3804c602-1ef4-11e6-938f-f9745b04d719.png)

**Comment by mrvlty** [comment]
Do you mean to design the model using a single mesh structure sir to solve that kind of error ?

Merve

**Comment by mcgratta** [comment]
No, I mean exactly what I said. Three meshes, but the lateral grid spacing does not change from mesh to mesh.

**Comment by mcgratta** [comment]
We just released a new version of FDS that should improve tunnel fire simulations. Please try this version on your case and report the results here.

**Comment by mcgratta** [comment]
Does the new release solve the original problem?

**Comment by guipesa** [comment]
Now It works fine for us. The problem is solved.

**Comment by mrvlty** [comment]
Yes  I try to solve it using new release of FDS and the problem is fixed.
Thank you so much sir.

**Comment by mcgratta** [comment]
You're welcome.
