### ISSUE TITLE
Unexpected Behavior with OPEN boundary

### ISSUE THREAD

**Issue by JezOck** [firemodels/fds#3810]
Could anyone please explain the observed behaviour on this very simple model looking at the behaviour of OPEN vents.

The model is very simple a 7.5mx5mx5m volume meshed at 0.25m in each co--ordinate direction. At one end is a 2mx2m OPEN vent, and at the other a 5x5 extract vent with a velocity extract of 2m/s.

The achieved pressure profiles achieve are not at all what we would have expected. Please see below:

![image](https://cloud.githubusercontent.com/assets/18698791/14850187/427bedf0-0c6f-11e6-892b-87c41efec411.png)

This image appears to indicate that the pressure directly adjacent to the OPEN boundary is in the order of -150Pa, i.e. significantly lower than the pressure adjacent to the extract vent. I'd broadly expect that on average the pressure adjacent to the open boundary is close to 0Pa (i.e. Rho_ext), and certainly wouldn't have expected a lower pressure at the open boundary than the extract boundary.

Is there a problem here, or is there a rational explanation for this which I'm missing?

---

&HEAD CHID='OPENBoundTest'/
&TIME T_END=100.0/
&DUMP RENDER_FILE='OPENBoundTest.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0/

&MESH ID='MESH', IJK=30,20,20, XB=0.0,7.5,0.0,5.0,0.0,5.0/

&SURF ID='Extract',
      RGB=102.0,204.0,255.0,
      VEL=2.0/

&VENT SURF_ID='OPEN', XB=0.0,0.0,1.5,3.5,1.5,3.5/ Vent
&VENT SURF_ID='Extract', XB=7.5,7.5,0.0,5.0,0.0,5.0/ Vent01

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=2.5/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBY=2.5/
&SLCF QUANTITY='VISCOSITY', VECTOR=.TRUE., PBY=2.5/
&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBZ=2.5/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBZ=2.5/
&SLCF QUANTITY='VISCOSITY', VECTOR=.TRUE., PBZ=2.5/

**Comment by drjfloyd** [comment]
The velocity at the door is 25/4*2=12.5 m/s.  The orifice pressure drop for
this would be approximately 2 (loss) /2/1.2 (density) \* 12.5^2 = 130.

**Comment by JezOck** [comment]
Yes, but that still doesn't explain the pressure profile being nearly the reverse of what would be expected.

As a comparison here is the same model set-up as an oriface plate:

![image](https://cloud.githubusercontent.com/assets/18698791/14851201/426fb3a8-0c76-11e6-9949-a3b1876a39cc.png)

This simulation shows what I would have expected in regards to both pressure and velocity profiles.

This gets to the point of why I was looking at this in the first place, is it acceptable to use an OPEN boundary to simulate a window?

**Comment by mcgratta** [comment]
I think you've answered your own question -- in this case, no. An OPEN vent sits at the external boundary of the computational domain where it is assumed that the pressure outside is exactly ambient. In some scenarios, this might be OK, others not. You are right to test it like you have done.

**Comment by JezOck** [comment]
Many thanks for your feedback so far and sorry to keep pushing on this, I'm still somewhat confused as to how the results are actually achieved on the 1st simulation.

I expected difference between using the OPEN boundary as a window, and setting it up as an oriface plate as the simulation is missing the 'downstream' information, and I was looking into how big an impact this might have. My understanding is that with the OPEN boundary that the downstream condition is taken at ambient relative pressure (i.e. 0). 

I don't see how this could end up with situation where the 1st cell pressure is then recorded as being lower than for the domain generally. As I said in the 1st email if anything I'd expect the pressure to be closer to 0, not further away.

I'd like to get the mechanics of what is occurring here sorted out in my mind so that I don't need to run a sensitivity every time I use an OPEN boundary.

**Comment by rmcdermo** [comment]
The behavior of an OPEN bc is clearly described in the Tech Guide.

On Wednesday, April 27, 2016, JezOck notifications@github.com wrote:

> Many thanks for your feedback so far and sorry to keep pushing on this,
> I'm still somewhat confused as to how the results are actually achieved on
> the 1st simulation.
> 
> I expected difference between using the OPEN boundary as a window, and
> setting it up as an oriface plate as the simulation is missing the
> 'downstream' information, and I was looking into how big an impact this
> might have. My understanding is that with the OPEN boundary that the
> downstream condition is taken at ambient relative pressure (i.e. 0).
> 
> I don't see how this could end up with situation where the 1st cell
> pressure is then recorded as being lower than for the domain generally. As
> I said in the 1st email if anything I'd expect the pressure to be closer to
> 0, not further away.
> 
> I'd like to get the mechanics of what is occurring here sorted out in my
> mind so that I don't need to run a sensitivity every time I use an OPEN
> boundary.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3810#issuecomment-215077104

## 

Sent from my iPhone

**Comment by mcgratta** [comment]
More precisely, it is assumed that p/rho+0.5*v^2=0 along the streamlines entering the OPEN boundary.

**Comment by JezOck** [comment]
Thank you, I've already read this prior to posting.

This doesn't answer the fundamental question being asked, or if it does I don't understand. 

I'd read eq. 4.80 as giving the incoming value of H at the boundary H_1/2.jk as being always 0 in the default case, given that ambient pressure is 0 and the far field and velocity are also 0. So how can it be that the pressure at the boundary is lower than the domain generally, rather than closer to 0.

**Comment by mcgratta** [comment]
H=p/rho+v^2/2

At the OPEN boundary, v^2 is a large positive number and therefore p is a large negative number. Inside the room, the velocity is much less because of the greater cross-sectional area.

**Comment by JezOck** [comment]
I have it now, many thanks for your assistance.

**Comment by mcgratta** [comment]
No problem.
