### ISSUE TITLE
Runtime error: index above upper bound

### ISSUE THREAD

**Issue by jbect** [firemodels/fds#3811]
Hello,

I'm seeing the following runtime error with a "gnu_linux_64_db" build (on Debian stretch, 64-bits, with gfortran 4.9, with or without -fopenmp, at [git 3142520](https://github.com/firemodels/fds-smv/commit/31425201951ceb706413bc8b6f1d4ddadf1dd95c)) :

```
>>> fds_linux_64_db exampleScript_100cm_1.fds

 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : April 28, 2016  13:24:16
 Version          : FDS 6.4.0
 Revision         : Git-r10-286-g9e8a58e-dirty
 Revision Date    : Tue Apr 26 16:53:14 2016 -0400
 Compilation Date : avril 28, 2016  13:23:16

 MPI Disabled
 OpenMP Disabled

 Job TITLE        : exampleScript_100cm_1
 Job ID string    : exampleScript_100cm_1

At line 6229 of file ../../FDS_Source/dump.f90
Fortran runtime error: Index '20480' of dimension 1 of array 'wall' above upper bound of 4000
```

Any idea what that might be ?

@++
Julien

**Comment by drjfloyd** [comment]
It could be a bug, it could be an input error we aren't providing error trapping for. Please submit the simplest version of your input file that still results in the error message.

**Comment by jbect** [comment]
Here is the full example script:
[exampleScript_100cm_1.fds.txt](https://github.com/firemodels/fds-smv/files/240642/exampleScript_100cm_1.fds.txt)

**Comment by jbect** [comment]
One more thing: if I build "gnu_linux_64" instead of "gnu_linux_64_db", I get a segmentation fault instead.

**Comment by jbect** [comment]
Some more debugging info:
- the problem occurs when subroutine `SOLID_PHASE_OUTPUT` is called (for the first time) with `OPT_WALL_INDEX` equal to 20480, whereas `UBOUND(WALL,1)` returns 4000.
- the call comes from subroutine `UPDATE_DEVICES`, more precisely in `SELECT CASE(DV%STATISTICS)` with `DV%STATISTICS` equal to `null`.

**Comment by drjfloyd** [comment]
Your case runs fine with the release version of FDS 6.4 and the current source. This suggests the issue is with your compiler.  I suggest upgrading your compiler to the latest version of gfortran.

**Comment by jbect** [comment]
The problem occurs with gfortran 4.9.3, which a recent release ([June 2015](https://gcc.gnu.org/releases.html))...

**Comment by mcgratta** [comment]
It is not unusual to get a segmentation fault when compiling with optimizations. If the seg faults do not occur with the debug (non-optimized) version, this usually means that there is a bug in the compiler optimization. I report such bugs to Intel on a regular basis, and these bugs get fixed. This is why Intel does a major compiler release roughly every year. This is also why the Intel compiler is not cheap.

**Comment by jbect** [comment]
Please forget about the segfault with the optimized version.

In the _non optimized_ debug version, I get an index-out-of-bound error. Don't you think that this could be a bug in FDS ?

**Comment by drjfloyd** [comment]
The latest release of gfortran is 5.3 (December 2015).  If upgrading to the latest release does not work, then you will need to either use the official version of FDS or acquire a different compiler.

**Comment by mcgratta** [comment]
I ran the case with the debug version of FDS 6.4.0 and it works.

**Comment by jbect** [comment]
Well, obviously it's a compiler-related issue.  But that doesn't automatically mean that gfortran is the one to blame...

**Comment by mcgratta** [comment]
There's always a chance that a bit of source code is written in some less than optimal way. But we cannot fix anything in the code if we don't know what is wrong.

**Comment by mcgratta** [comment]
We compiled the code with gfortran and found the problem. Could the original poster update your source code and try again.

**Comment by jbect** [comment]
Yes, this was indeed a problem of uninitialized `DV%WALL_INDEX`.

Problem solved.  Thank you.

**Comment by mcgratta** [comment]
Thanks, Marcos.
