### ISSUE TITLE
Normalized PNF not working

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3814]
From Elizabeth Blanchard:

When we want to plot the histogram of diameter (i.e. PNF  probability number function) without normalizing it, it does not work. There is no difference with normalized data. I think in the code line

```
WRITE(LU_HISTOGRAM,TCFORM,ADVANCE="NO") DI*1E6_EB,CUMSUM(NN)/CONST(NN)/DD
```

it should not be divided by `CONST(NN)/DD` or it should be equal to 1.

**Comment by shostikk** [comment]
I'll try to fix soon.

**Comment by ElizabethBlanchard** [comment]
Hi Kevin, Hi Simo,
It works by adding the following if condition 
IF (PROPERTY(DV%PROP_INDEX)%PDPA_NORMALIZE) WRITE(LU_HISTOGRAM,TCFORM,ADVANCE="NO") DI_1E6_EB,CUMSUM(NN)/CONST(NN)/DD
IF (.NOT. PROPERTY(DV%PROP_INDEX)%PDPA_NORMALIZE) WRITE(LU_HISTOGRAM,TCFORM,ADVANCE="NO") DI_1E6_EB,REAL(CUMSUM(NN),EB)
It has been verified by 
 (1) comparing the Sauter Diameter (d32) given by the PDPA instruction, calculated from the normalized histogram and calculated from the unnormalized.
 (2) comparing the two histograms and normalizing the unnormalized histogram.
Elizabeth

**Comment by shostikk** [comment]
Hi Elizabeth, 
I just started to work on this issue before you wrote. The PDPA_NORMALIZE was never intended for use with histograms (only for mean quantity calculation), but now it will. I have done the changes to the code already, and need to update the guide. Then I will commit this to github.

First, the code needs to consider four different combinations of cumlative/non-cumulative, normalized/non-normalized. For that, the code will look like:
               IF (PROPERTY(DV%PROP_INDEX)%PDPA_HISTOGRAM_CUMULATIVE) THEN
                  IF (PROPERTY(DV%PROP_INDEX)%PDPA_NORMALIZE) THEN
                     CUMSUM(NN)=CUMSUM(NN)+DV%PDPA_HISTOGRAM_COUNTS(I)_DD
                  ELSE
                     CUMSUM(NN)=CUMSUM(NN)+DV%PDPA_HISTOGRAM_COUNTS(I)
                  ENDIF
               ELSE
                  CUMSUM(NN)=DV%PDPA_HISTOGRAM_COUNTS(I)
               ENDIF
               IF (PROPERTY(DV%PROP_INDEX)%PDPA_NORMALIZE) THEN
                  WRITE(LU_HISTOGRAM,TCFORM,ADVANCE="NO") DI_1E6_EB,CUMSUM(NN)/CONST(NN)/DD
               ELSE
                  WRITE(LU_HISTOGRAM,TCFORM,ADVANCE="NO") DI*1E6_EB,CUMSUM(NN)
               ENDIF

Additionally, the numbers you get in the hist.csv file will not be integers showing the number actual computational droplets, but the weights of the super-drops. To get the actual number of numerical droplets, you should define N_STRATA = 1 on the PART line. But the shape of the distribution should be fine in any case.

**Comment by shostikk** [comment]
Closing the issue. Thanks Elizabeth for help!
