### ISSUE TITLE
Pressure iteration in CHID.out

### ISSUE THREAD

**Issue by cfaurie** [firemodels/fds#3819]
Hello, 

I noticed that the maximum velocity error and pressure iteration aren't written in the CHID.out file anymore, see example attached. Is it a feature of FDS 6.4.0 (The UG hasn't changed)? How do I access this information now?

Thanks,
Coraline

[Mall_EastAtrium_08.txt](https://github.com/firemodels/fds-smv/files/250872/Mall_EastAtrium_08.txt)

**Comment by mcgratta** [comment]
`SUPPRESS_DIAGNOSTICS=.FALSE.` on the `DUMP` line.

**Comment by cfaurie** [comment]
Great, thanks! 

Coraline

**Comment by mcgratta** [comment]
Let me know if it works.

**Comment by cfaurie** [comment]
Yes, it works fine. Thanks.

Coraline
