### ISSUE TITLE
Energy Budget case requires that BAROCLINIC be false

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3820]
In testing my iterative scheme for the baroclinic torque term, I found that `energy_budget_tmix.fds` needs `BAROCLINIC=.FALSE.` to work properly. All other cases from which I removed the `BAROCLINIC=.FALSE.` seem OK. You can test this with the release version of 6.4.0.

**Comment by rmcdermo** [comment]
Need to set velocity tolerance.  This has been done and committed.
