### ISSUE TITLE
Error in soot routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3828]
```
Species/soot_gravitational_settling_2.err:forrtl: severe (408): fort: (7): Attempt to use pointer D_SOURCE when it is not associated with a target
Species/soot_gravitational_settling.err:forrtl: severe (408): fort: (7): Attempt to use pointer D_SOURCE when it is not associated with a target
```

**Comment by drjfloyd** [comment]
I tested my changes with a case that had a reaction and  we were only allocating when there was a reaction or  an evaporating particle.  Also added a check for a DEPOSITING species.

https://github.com/firemodels/fds-smv/commit/14611ab5a09a5487b93c26e63f3c3200db7a12bb

**Comment by mcgratta** [comment]
Works, thanks.
