### ISSUE TITLE
Three small typos in the FDS user guide on page 260

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#3837]
On page 260 in the FDS user guide (April 7, 2016, FDS Version 6.4.0, Revision: Git-r10-21-g7335b05) there are three small typos:
SPRAY_PATTERN_BETA  should be of type Real (currently integer), no unit (currently it is deg.)
SPRAY_PATTERN_MU should be of type Real (currently integer)

I checked both variables in the source code (read.f90) that they indeed are real value, and the no unit on  SPRAY_PATTERN_BETA I got confirmed by Topi.

**Comment by mcgratta** [comment]
Thanks -- Simo or Topi, could you check this?

**Comment by rmcdermo** [comment]
I concur with Bjarne.  This should be fixed now.
