### ISSUE TITLE
CHID.out File

### ISSUE THREAD

**Issue by mrvlty** [firemodels/fds#3842]
Hi everyone ,

I want to draw "Time steps and computational convergence for FDS simulation" within the scope of a study as attached below. I searched about **How I can obtain the CFL values depend on time steps to draw that kind of figure** and I found some information in Chapter 20.1 output file formats part of the FDS  user's guide(sixth adition). As it is mentioned in the user's guide, the **file CHID.out** contains diagnostic output. 
But I don't know how to obtain that  CHID.out file. Could you please help me to get that file.

NOTE:  The link of FDS  user's guide and the screenshot of the relevant part of that user's guide is attached .

Thanks for your time.

Merve 

![screenshot 2016-05-12 12 19 57](https://cloud.githubusercontent.com/assets/16001133/15209866/277ac23c-183c-11e6-971c-3b58fb0540ad.png)

![screenshot 2016-05-12 12 25 01](https://cloud.githubusercontent.com/assets/16001133/15209999/cd2b4e72-183c-11e6-906b-c00be34999b0.png)

http://www.thunderheadeng.com/wp-content/uploads/2013/08/FDS_User_Guide.pdf

**Comment by mcgratta** [comment]
The .out file is printed automatically during an FDS calc. It would be in the working directory.

**Comment by mrvlty** [comment]
How can i get the working directory of the simulaton. Is there any
extention of it?

Thank you.

2016-05-12 15:50 GMT+03:00 Kevin McGrattan notifications@github.com:

**Comment by drjfloyd** [comment]
The working directory is the directory you are in when you type "fds inputfile" at the prompt.  If you are running via Pyrosim then it is where you saved the pyrosim file (if you are having difficulties using pyrosim contact Thunderhead as we do not provide support for Pyrosim only FDS and Smokeview).
