### ISSUE TITLE
40 Device Inputs to a Control result in FDS Error with corrupted string text.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#3854]
Please see the attached input file to reproduce the error.
[40_inputs.fds.txt](https://github.com/firemodels/fds-smv/files/264647/40_inputs.fds.txt)

**Comment by drjfloyd** [comment]
Had some bad logic in the loop counting how many INPUT_IDs were given.

Fixed in:
https://github.com/firemodels/fds-smv/commit/556057f1084e3ed52ff15319544cdd26f3b22fb1

**Comment by drjfloyd** [comment]
Can you verify this is fixed with the latest release?

**Comment by drjfloyd** [comment]
Tested with current release and the input file runs successfully.
