### ISSUE TITLE
Problem with water particles

### ISSUE THREAD

**Issue by andreacerutti** [firemodels/fds#3859]
Hi to everybody, 
We've modeled a watermist system using nozzle installed close to roof.
Now we are having problem with particles distribution. 
I attach some images to explain better our problem.
In the attached images you can see that water flow doesn't reach floor and our fuel solid neither. Fuel solid is circled in image number 02.
Minutes after watermist start HRR is getting higher and higher as if watermist system doesn't work.
We've tried to set "&MISC  POROUS_FLOOR=.FALSE./" on the advice of software-house witch developed our graphical interface but we haven't fix this problem.
I post our .fds file.

---

![01](https://cloud.githubusercontent.com/assets/19390104/15291683/78d22670-1b7f-11e6-82a6-75ec0dd805a6.jpg)
![02](https://cloud.githubusercontent.com/assets/19390104/15291684/78d5f390-1b7f-11e6-9427-561a87446d07.jpg)
## ![03](https://cloud.githubusercontent.com/assets/19390104/15291685/78d71fcc-1b7f-11e6-9e14-447755775271.jpg)

Thank you so much.

[CAPANNONE_VVF_WM_RIDOTTO.fds.txt](https://github.com/firemodels/fds-smv/files/266212/CAPANNONE_VVF_WM_RIDOTTO.fds.txt)

**Comment by mcgratta** [comment]
After 6 iterations I already have over 600,000 droplets. You have run out of droplets. You need to increase `MAXIMUM PARTICLES` or use multiple meshes or both.

```
       Time Step       6   May 16, 2016  10:30:30
       Step Size:    0.666E-01 s, Total Time:       0.57 s
       Pressure Iterations:      1
       Maximum Velocity Error:  0.00E+00 on Mesh   1 at (   0   0   0)
       ---------------------------------------------------------------
       Max CFL number:  0.80E+00 at (  74,  31,  32)
       Max divergence:  0.64E-01 at (  67,  47,  35)
       Min divergence: -0.47E-01 at (  64,  76,  34)
       Max VN number:   0.31E+00 at (  27,  15,  34)
       No. of Lagrangian Particles:        644000
```

**Comment by andreacerutti** [comment]
We'll try to set MAXIUM PARTICLES and multiple mesh.
Thank you so much for your help.
Have a nice day.
