### ISSUE TITLE
Numerical Instability in NIST FSE cases

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3864]
Two cases failed with a numerical instability, `Git-r10-420-gdb225ce`

```
ISONylon10.fds
ISOStyrene16.fds
```

The nylon case fails in about 1.5 h. I ran a test case with a fuel molecule having half the molecular weight, and it failed too. The cases can be found

```
/home4/mcgratta/Git_Repositories/FDS-SMV/Validation/NIST_FSE_2008/Current_Results
```

**Comment by rmcdermo** [comment]
No luck on these so far.  The Nylon case died with 1 press iteration as well.

**Comment by sbenkorichi** [comment]
Do you still have issues with these cases?

**Comment by rmcdermo** [comment]
Not sure.  We need to run all validation cases soon anyway.  We'll see then.

**Comment by sbenkorichi** [comment]
Ok. I would also to see if you could get sometime to check  the old issues  to get em closed if nothing needed to be done. It's better to get some cleaning.

**Comment by mcgratta** [comment]
This issue is resolved, for now. Only one of these cases failed with a numerical instability, which occurred near the exterior `OPEN` boundary. I increased the size of the domain a little bit and it finished successfully.
