### ISSUE TITLE
HRR drops on restart

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#3866]
I have been running problems using restart, both using a *.stop file and by setting the end time and restart output time. The attached burner.fds file runs for 1 second and writes restart data at 1 second.
[burner.txt](https://github.com/firemodels/fds-smv/files/268901/burner.txt)

If I restart and run to 2 seconds, the HRR data in the csv ouput file drops to near zero at the restart time. This behavior has been consistent in the problems I have restarted. It does not seem to be a significant problem, but it does lead to some difference later in the simulation.
![hrr_restart](https://cloud.githubusercontent.com/assets/13338306/15335400/c4308482-1c37-11e6-9b86-8c6c98f6df2d.png)

**Comment by mcgratta** [comment]
Fixed. Commit #3872. Please test and confirm.

**Comment by dvswenson** [comment]
Tested and it works. Thanks.

**Comment by mcgratta** [comment]
Thanks for checking it.

**Comment by dvswenson** [comment]
I was running using a more complex model and still did see some drop in HRR on restarts. Not as severe as before, but a drop. 

Unfortunately, I cannot replicate the behavior using a simple model. The complex model is going to take me a week to run. I will monitor what happens and report to you at the end.
![hrr drop with jet fan model](https://cloud.githubusercontent.com/assets/13338306/15690359/c845d420-2748-11e6-8f0d-6d0fcb54a215.png)

**Comment by Er9y714** [comment]
I have observed a similar problem on this simple case. I stopped around 5.69 s, after restart, HRR seems to dropped.

Thank you for your support.

FDS 6.7.1


![image](https://user-images.githubusercontent.com/26166281/56718205-a11a4f00-673e-11e9-86e7-0b5da76812d4.png)


` 
&HEAD CHID='a'/
&TIME  T_END=900.0/
&DUMP DT_HRR=1/
   MISC  RESTART=.TRUE./

&MESH ID='Tube3', IJK=60,28,33, XB=148.0,160,0.2,5.8,0.0,6.6/  

&REAC ID='FRP Polyester',
      FUEL='REAC_FUEL',
      C=5.77,
      H=6.25,
      O=1.63,
      AUTO_IGNITION_TEMPERATURE=0.0,
      CO_YIELD=0.0705,
      SOOT_YIELD=0.0581,
      HEAT_OF_COMBUSTION=2.1926E4/
&SURF ID='Burner1',
      RGB=255,204,204,
      HRRPUA=500.0/
&VENT ID='Mesh Vent ', SURF_ID='OPEN', MB= 'XMIN'/   
&VENT ID='Vent2', SURF_ID='Burner1', XB=150.2,152.2,2.4,4.2,1.605,1.605/  
&OBST ID='a', XB=150.2,152.2,2.4,4.2,1.605,1.405/  
&TAIL /
`

**Comment by mcgratta** [comment]
#7309 

This was a bug related to the time-averaging. The bug only affects the print-out, not the actual calculation. I fixed it.

**Comment by Er9y714** [comment]
Great! Thank you.
