### ISSUE TITLE
clean up pointers in init.f90

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3871]
Kevin,
When you get time, can you take a look at some of the pointers in init.f90?  I ran across this issue when trying to find my recent bug.  The issue is that several pointers like OB and SF are declared at the top of the module, but then sometimes they are declared again within a specific subroutine (see, e.g., SF in INITIALIZE_MESH_VARIABLES_1).  Then later you see OBX declared to point to an OBSTRUCTION_TYPE, but I think the OB at the top should be fine.  So, I would like us to either only use the pointers at the top or to eliminate them from the top (my choice) and declare them within local routines (I think this is safer).

**Comment by mcgratta** [comment]
Done. I ran the verification cases and everything seems OK.
