### ISSUE TITLE
More than one cycle time gives wrong boundary conditions on obstruction

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#3873]
Switching a radiation panel on and off gives works fine with one cycle timer, but adding an extra panel and a timer produces a different output.

The obstruction are created correctly (can be seen in smokeview) and the timing sequence in the ctrl.csv file is also correct.
but the output in the device file does not match

case with single cycle timer
Time    R025mm  R050mm  Temp close to wall
0.00         3.24           3.49            20.00
0.01             3.24   3.50            21.78
0.02             2.32   2.29            25.47
0.03             3.23   3.46    29.04

case with 2 cycle timers
Time    R025mm  R050mm  Temp close to wall
0.00            3.39            3.64             20.00
0.01          0.95  1.26             20.05
0.02             0.03   0.05             20.07
0.03             0.93   1.22          20.10

The second column should read the same values for both cases. I have attached the input files for both cases, takes 3 minutes to run the cleaned case.
This was run in FDS 6.4.0  and also verified in the lasted development version as of today,
Git-r10-483-g37e3448

It seems that the boundary conditions of 700 degrees for the radiation panel is not applied on the first panel, when having two panels. Later on activation of the second panel, - the correct boundary conditions is applied to that panel. 

[fds_input_files.zip](https://github.com/firemodels/fds-smv/files/271092/fds_input_files.zip)

**Comment by rmcdermo** [comment]
Thanks Bjarne.  We'll have a look.

**Comment by drjfloyd** [comment]
&OBST   XB=-0.42,-0.40, -0.20,0.20,     **1.84,2.30**
&OBST   XB=-0.42,-0.40, -0.20,0.20,     **1.82,2.28** 

Your  OBST overlap for almost their entire extent. This may be the root cause of the problem -- that you are trying to have FDS do two different things with the same grid cells. I'll see what I can figure out.

As a work around rather than using two OBST with different cycling ramps, you could keep the OBST their and apply VENTs whose SURF use RAMP_T (e.g. temperature=TMPA for off and 700 for on).

**Comment by bphusted** [comment]
Thanks for your reply.
If I avoid the overlap by using an extra OBST for the overlap then the error disappear 
&OBST   XB=-0.42,-0.40, -0.20,0.20,     2.28,2.30, 
&OBST   XB=-0.42,-0.40, -0.20,0.20,     1.84,2.28, 
&OBST   XB=-0.42,-0.40, -0.20,0.20,     1.82,1.84, 

But as I have more radiation panels than just those 2. I would be nice, if I could avoid this extra subdivision. Would I not have the same problem if I used VENT, - they would also overlap.

**Comment by drjfloyd** [comment]
Yes with over lapping vents the first vent would take precedence. Fds can
only apply one boundary condition at a time. It is not possible for fds to
apply two. You will need to either define three vents or obstructions (the
two non-overlapping and the overlapping) or ensure the vents or
obstructions are separate.

**Comment by rmcdermo** [comment]
I assume no more action is being taken on this issue.  Reopen if necessary.
