### ISSUE TITLE
TIME_SHRINK_FACTOR in PYROLYSIS

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3877]
Please have look at Line 2103-2107 in wall.f90.  When we get C_S out of EVALUATE_RAMP we apply C_S_ADJUST_UNITS = 1000._EB/TIME_SHRINK_FACTOR.

This is very confusing.
1. Should we not be applying TIME_SHRINK_FACTOR for case without a ramp?
2. Why would we apply the unit conversion here only for ramps?

**Comment by mcgratta** [comment]
Probably so. I'd like to apply TSF in as few places as possible to avoid doubly applying it.

**Comment by rmcdermo** [comment]
My suggestion is to just remove C_S_ADJUST_UNITS in PYROLYSIS and use it only in read.  I think that by the time we get to wall ML%C_S should have the right value and units (which it apparently does have sans ramp).  But the ramp logic is opaque here.

**Comment by mcgratta** [comment]
Done, #3884

**Comment by mcgratta** [comment]
I'll close this issue after successfully passing a firebot run.
