### ISSUE TITLE
global max and min for slcf in obst

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3879]
Glenn,
When we choose to view slices inside obstructions, it would be nice if the global max and min for data bounds reflects also the values that are inside the obstruction.  It looks to me now like this is not the case.  Thanks.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
can you point me to one of your 3d heat conduction test cases or some other case that has meaningful slice values inside blockages

**Comment by rmcdermo** [comment]
https://github.com/firemodels/fds-smv/blob/development/Verification/Heat_Transfer/ht3d_test_1.fds

**Comment by gforney** [comment]
try test smokeview (for now only windows and mac) at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

note: to show a slice, smokeview does the following
1.  loads data
2.  computes bounds
3.  converts data values to color indices

so, if you change what data is used to compute bounds (ie select or deselect "show slice in blockage" menu item) you need to perform the above 3 steps (by reloading the slice file or clicking on the Update button in the slice bounds dialog box) .

I added a "show slice in blockage" menu item to the "Load slice" menu.  So now you can set this option  before you load the data.  (This menu item was in the Show/Hide Slice menu so before you couldn't set it until after you loaded the slice data)

also note, now "show slice in blockage" option is global.  It is either ON for all slices or OFF for all slices.  do we want to make this a slice option?  ie ON for one slice but OFF for other slices.   We originally hid slice data in blockages to make it easier to visulize slice data when viewing complicated geometries in outline mode. So, for most slices we'll want to continue to hide slice data within blockages

**Comment by rmcdermo** [comment]
Glenn,
All seems to work great.  Thanks!  I think the global toggle is fine for now.  Let's see if we come across the other case.
