### ISSUE TITLE
Smokeview doesn't use full range of colormaps when visualizing fire

### ISSUE THREAD

**Issue by thejalbrecht** [firemodels/fds#3882]
I've recently come across an issue working with Smokeview. I'll try to illustrate the problem with images, and then comment on what I've observed through looking at the Smokeview source. Attached is a simple model of an ethanol fire, but any example with a fire should be sufficient.

[burner_fire.zip](https://github.com/firemodels/fds-smv/files/277830/burner_fire.zip)

To begin, run the model and load the results in Smokeview. Show both SOOT_MASS_FRACTION, and HRRPUV. I've attached in image from the final timestep as a reference. I will use the same viewing angle for subsequent images.

![image](https://cloud.githubusercontent.com/assets/16089826/15477491/755e4ae0-20da-11e6-840b-d922ea2fec63.png)

Next, open the data bounds dialog, set the color to "Use colormap with constraints", expand the colormap subtree, and select "fire 2" for the colormap. The fire should now look like this:

![image](https://cloud.githubusercontent.com/assets/16089826/15477591/fc85fff4-20da-11e6-99af-a084e0bb6609.png)

Clearly only a small section of the defined range is being utilized. However, if we select "Use GPU"...

![image](https://cloud.githubusercontent.com/assets/16089826/15477623/2bdca424-20db-11e6-840d-9c7860278b0b.png)

...we see that the full range of the colormap is now being utilized. 
## 

I can shed some light on why this issue occurs. If we take a look at getdatacolors::Update_Smokecolormap(int option) and start with the assumption that...
valmax = 1200
valmin = 0
valcut = 200
...we can interpret that for case FIRECOLORMAP_CONSTRAINT, at n=170, val=199.4. Thus, the hrrpuv cutoff for fire visualization is between 170 and 171, and rgb_colormap is an array size 4x1024 where all indices above ix=4x170 correspond to fire, and all indices below correspond to smoke.

The problem seems to occur because of how the rgb_colormap is indexed during the mergesmoke3dcolors(smoke3ddata *smoke3dset) method in IOSmoke.c. Here, we use...

```
    if(firecolor!=NULL && firecolor[j]>i_hrrpuv_cutoff)
{
      firesmoke=rgb_slicesmokecolormap+4*firecolor[j];
      *mergecolor++ = 255*firesmoke[0];
      *mergecolor++ = 255*firesmoke[1];
      *mergecolor++ = 255*firesmoke[2];
      *mergealpha++=fire_alpha;
    }
```

...to assign the fire color. This piece of code can only ever index into the first 4x255 entries of the rgb_colormap. Since n=170 is the threshold for visualizing fire, 170/255 or 2/3 of all radiance values correspond to smoke.

If we map those 0-255 values back to hrrpuv floats, and continue to assume valmax=1200 and valmin=0, then our valcut=200 actually behaves more like valcut=800. I hope this wasn't too long winded.
## 

Jon

**Comment by rmcdermo** [comment]
Jon,
Thanks for the post and discussion!  Glenn is in and out while he is on leave for a couple weeks.  Looks like something he may need some dedicated time to sort out (maybe not).  I just wanted to let you know in case it seems like he not jumping on it as fast as usual.  Cheers.

**Comment by gforney** [comment]
try smokeview (only osx and windows for now) located at
https://drive.google.com/folderview?id=0B_wB1pJL2bFQc1F4cjJWY2duWTA&usp=sharing

As you noted the smoke colormap had length 1024 which was fine for GPU smoke/fire.  This doesn't work for the "non-GPU" smoke/fire since I'm using unsigned chars to hold the colormap indices (can only hold 256 indices).  I reduced the size of the smoke/fire colormap to 256 for both GPU and non-GPU options.  To test fix, I used the rainbow colormap to display smoke/fire to make differences between GPU and non-GPU options more obvious.  They appeared to be the same (before I made the fix they were markedly different).  Let me know if you notice any side effects from this change.

**Comment by thejalbrecht** [comment]
Glenn,

Thanks for the speedy update! It does appear that there are some consequences of the change. Whether they are good or bad is another question that I would like to know your thoughts on.

Now, if you look at my submitted model with "Use specified color, opacity", the default RGB=255,128,0 for fire, we see this for the old version:

![image](https://cloud.githubusercontent.com/assets/16089826/15509111/f2abbc54-2197-11e6-9b8c-859f4e82edb1.png)

And this for the dev version:

![image](https://cloud.githubusercontent.com/assets/16089826/15509132/0b92585e-2198-11e6-9a49-abacbb945394.png)

## 

I also have a general question about the different visualization techniques implemented throughout Smokeview. Is any one combination of settings more valid than another? For instance, do you trust the shader implementations as the most accurate representation of smoke? Or the volume rendering approach?

## 

Jon

**Comment by sbenkorichi** [comment]
Glenn, is there an update on this post?

**Comment by gforney** [comment]
I'm going to close the issue.  If this is still a problem it can be reopened.
