### ISSUE TITLE
Multiple meshes slow progression of incident radiation

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3889]
I've started working a reported issue on burning rates of liquid pool fires where the users claim they get different MLR with different mesh configurations (I will post this separately).  To start, I was curious about the effect multiple meshes would have on the radiation field.  My preliminary findings suggest that multiple meshes affect the transient, but not the steady state behavior.  However, I think we should eliminate this transient dependence, since, after all, flame spread is a transient phenomenon and we cannot have a convergent code that scales if we get different radiation solutions with different numbers of meshes.

To analysis this effect I created three input files (1 mesh, 4 mesh, 64 mesh) with a hot (1000 C) OBST in the center of the box.  Below I show an image with the short term and steady boundary profiles of incident radiation.  It seems that adding meshes slows the progress of the radiation intensity.  The input files are also attached.

![start_pattern_multimesh](https://cloud.githubusercontent.com/assets/4418497/15557448/080eeb52-22a1-11e6-9643-8067d8c93853.png)

[test_star_pattern.fds.txt](https://github.com/firemodels/fds-smv/files/283060/test_star_pattern.fds.txt)
[test_star_4_mesh.fds.txt](https://github.com/firemodels/fds-smv/files/283061/test_star_4_mesh.fds.txt)
[test_star_64_mesh.fds.txt](https://github.com/firemodels/fds-smv/files/283063/test_star_64_mesh.fds.txt)

**Comment by drjfloyd** [comment]
To do this would (I think) require a radiation solver equivalent to the
pressure correction where we iterate until the the outgoing radiation on
one mesh converges to the incoming on the adjacent.

I think you are correct that this is something we should do. Though as a
default maybe we let the tolerance be large since a lot of engineering uses
would not care about this.

**Comment by rmcdermo** [comment]
Here are my findings for the heptane_1_m.fds case for single, stacked, and blocked mesh configuration.  It may be that the transient is not critical.  It may be good to go ahead and add the iteration (as an option) that you we thinking about, though, before we close.

[heptane_1_m_hrr.pdf](https://github.com/firemodels/fds-smv/files/286683/heptane_1_m_hrr.pdf)

**Comment by mcgratta** [comment]
I implemented an iteration scheme and it works. I have not committed code yet because I need to test more. One question for Simo -- do you think we need to update the angles over multiple time steps? The radiation solver could get quite complicated now that we would have multiple iterations of the solver and MPI exchanges in a given time step.

**Comment by shostikk** [comment]
Of course we can do without the multiple-time steps. To update all angles every - say 15th time step. The transient heat fluxes just will look more 'steppy', if you print them with a resolution less than 15 time steps.

Removing the the multiple time step would indeed simplify the code. But the same data structures are used for the multiple-band mode. I assume that removing the multiple bands may in the beginnng remove that capability as well. (But that is something I would like to overhaul anyway. There are much better ways to hand the spectral bands than what we are doing.)

**Comment by shostikk** [comment]
But what do we gain by iterating? For each direction, the radiation intensity on an upwind mesh is not affected the intensity on the downwind mesh, unless there are reflective boundaries or scattering particles.

**Comment by mcgratta** [comment]
I added the ability to iterate the radiation solver, but I did not change the current functionality.
