### ISSUE TITLE
Run_FDS_Parallel(credentials error)

### ISSUE THREAD

**Issue by mrvlty** [firemodels/fds#3891]
Hello,

I want to run my simulation buy using "run FDS parallel" option. But when I click it I saw 

"Credentials for MERVE/merve rejected connecting to merve"

I entered into the Command Prompt of Windows the following steps to reset my MPI account credentials.

First, I remove the existing account information.

C:> cd “\Program Files\PyroSim 2016\fds”
C:\Program Files\PyroSim 2016\fds> mpiexec -remove

Then, register the correct username and password.

C:\Program Files\PyroSim 2016\fds>mpiexec -register
Account (domain\user) [MERVE\merve] : MERVE\merve
password: ....
Confirm password:...... 
Pasword encrypted into the registery

C:\Program Files\PyroSim 2016\fds> mpiexec -validate
SUCCESS

As it is seen the screen captures attached above I registered successfully .But When I reopen the program I click run parallel option it gives the same credentials error again in every time.  When I try to type my password It seems as blanks in the prompt ( i  am sure it is not blank.To understand it i typed a password and in the conform password line I typed different password it warned me about no agreement between them, besides I typed the blanks as password in the other test, It warned me about not use blanks as a password)  Nevertheless I doubt It may cause that error. 

1) Do you have any advice about the alternative solution methods of this error?

2) I search that issue on the net and I become confuse about downloading MPICH2. Can it be an alternative solution to that error.

Best regards,
Merve.

![cmd_prompt1](https://cloud.githubusercontent.com/assets/16001133/15602564/a7aad19a-23fe-11e6-9414-04ba23b1f533.png)
![cmd_prompt2](https://cloud.githubusercontent.com/assets/16001133/15602568/abe9bc12-23fe-11e6-8516-8d63f7862111.png)

**Comment by drjfloyd** [comment]
FDS does not use MPICH2.  Installing it will only make your problems worse.  If you wish to run the version of FDS installed with Pyrosim you are best off doing that via Pyrosim as they install a different scheduler than the official release installation package that you get on Github. Problems with Pyrosim should be reported to Pyrosim technical support. We do not provide support for Pyrosim.

Further discussions on this should be done via the forum as this is not a bug report.
