### ISSUE TITLE
Slow calculation of tunnel fire

### ISSUE THREAD

**Issue by rednasss** [firemodels/fds#3897]
Hello,

I am currently performing a CFD simulation of a tunnel fire. However I am struggling with the speed of the simulation, as it is taking way too long.
The simulation is actually a generic representation of a fire in a tunnel. So a large number of cells in x-direction and a small number of cells in y- and z-direction.
I made up the domain out of 1 mesh, by using stretching of the cells. I found out that information is lost at mesh intersections and for example smoke seems to stack up before it enters the next domain.
Below I will give some information about the model and the PC on which the simulation runs.

FDS input:
OpenMP is used with 12 threads
The domain is 1250x36x40 cells (1.800.000 cells) which is stretched to make refinements at for example the fire location
The flow speed is imposed on the inflowing surface based on a 1D flow model
The simulation starts at -10s (to resolve the starting domain at t=0s), the fire starts at t=0s and some fans start to work at t=120s. I can see the step size changing during the simulations with the first 10s (-10 to 0s) at ~0.5E-01 s, then up to 120s at ~0.6E-01 s and then it drops to ~0.5E-02 s.

PC specs:
CPU: Intel Xeon E5-2630 v2 @ 2.60GHz (12CPUs)
Memory: 16GB

Currently it is running and it takes a day to complete almost 50s of the simulation and I need to simulate up to 30 minutes. So it would take over a month to complete this simulation...

I've also read some articles which stated FDS5 would be faster than FDS6, however I never used FDS5 as I assume FDS6 would be better. But I would also like to hear some explanations about those articles.

I would be really thankful for all the help I receive!

Thanks in advance!

**Comment by drjfloyd** [comment]
closing as cross-posted to discussion forum.
