### ISSUE TITLE
FDS 6.4.0 don't work in windows 10

### ISSUE THREAD

**Issue by Gloriana83** [firemodels/fds#3899]
I had installed FDS and Smokeview latest version 6.4 and 6.3.6 for my Windows 10.
After unzip, installing the programs, and restart my computer; FDS isn't listed as like attached program with my windows.

I tried run cmd few times but everytime I typed fds at the command, there is a sentence stating that it is not recognized program.

I also tried out test_mpi at cmd. Only get message write that the program was not compatible with my current Windows.

Please help me solving this problem. Thx

**Comment by rmcdermo** [comment]
Glenn,
Can you please have a look?  Thanks.

**Comment by gforney** [comment]
when you install fds and smokeview make sure you install it as administrator.  Do you see anything at c:\program files\firemodels ?

**Comment by Gloriana83** [comment]
I have installed it as administrator. In firemodels folder, I see both FDS6 and SMV6 folder. Still can't run the program

**Comment by gforney** [comment]
type the following in a command shell: 
echo %PATH% > path.txt

and upload path.txt

**Comment by Gloriana83** [comment]
Done it. The notepad write as follow

C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Skype\Phone\

What's else after upload?

**Comment by gforney** [comment]
![screen1](https://cloud.githubusercontent.com/assets/12403014/15728948/eab0f342-282d-11e6-8ef6-23a551eff77f.png)
you should see the dialog box in the above image.  You should have clicked on the  unzip button.

![screen2](https://cloud.githubusercontent.com/assets/12403014/15728956/fa21b014-282d-11e6-9ef1-4274bc17dbb9.png)

after the extraction/file copy completes you should see the above image.  What did you see?

I see that you have powershell in your path.  Note, the FDS/Smokeview installation are designed to work with the windows command shell.

**Comment by Gloriana83** [comment]
![fds](https://cloud.githubusercontent.com/assets/19673923/15743285/89478c12-28ee-11e6-934f-9bcc2c22e08f.jpg)

That's very different from yours. I don't know why it is not compatible.

**Comment by foolstone** [comment]
If you had a 32-bit versions of Windows  installed on your PC and upgraded to Windows 10, Microsoft gave you the 32-bit version of Windows 10. You need to switch it to 64-bit version. 
All new FDS 6 version are released in 64-bit now.

**Comment by gforney** [comment]
my hunch would be that you are using a 32 bit version of windows.  FDS and
smokeview only support 64 bit.  To find out which version of windows you
are using either 1) go to your control panel and open the System and
Security item then open System. or 2) do a google search on something like
"windows 10 determine 64 bit "

On Thu, Jun 2, 2016 at 7:20 AM, Gloriana83 notifications@github.com wrote:

> [image: fds]
> https://cloud.githubusercontent.com/assets/19673923/15743285/89478c12-28ee-11e6-934f-9bcc2c22e08f.jpg
> 
> That's very different from yours. I don't know why it is not compatible.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3899#issuecomment-223263751,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRjTE_1D5x0Icdf2wVOmhpZR2QBhCks5qHrx2gaJpZM4Iq5A1
> .

## 

Glenn Forney

**Comment by gforney** [comment]
run this command from a command shell and report back what it says

systeminfo | findstr /C:"System type"

on my system it reports
System Type:               x64-based PC

On Thu, Jun 2, 2016 at 7:20 AM, Gloriana83 notifications@github.com wrote:

> [image: fds]
> https://cloud.githubusercontent.com/assets/19673923/15743285/89478c12-28ee-11e6-934f-9bcc2c22e08f.jpg
> 
> That's very different from yours. I don't know why it is not compatible.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/issues/3899#issuecomment-223263751,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRjTE_1D5x0Icdf2wVOmhpZR2QBhCks5qHrx2gaJpZM4Iq5A1
> .

## 

Glenn Forney

**Comment by Gloriana83** [comment]
I had checked mine. My system type is 32 bit, x64-based processor.
Need to upgrade it into 64 bit then.

Thx all

**Comment by gforney** [comment]
can you run this command
systeminfo | findstr /C:"System Type"

I want to check for system size in the installer so the next user with a 32 bit system will have an easier time.
thanks

**Comment by Gloriana83** [comment]
Yes, I can run the program.

My system type : x86-based PC.

**Comment by gforney** [comment]
Thanks for the info and for starting this issue. I've updated our bundle
generating scripts so that users such as yourself will be warned when
installing fds on 32 bit systems.
