### ISSUE TITLE
Wiki: dead link on Two Factor Authentication page

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#3911]
@gforney 
[https://github.com/firemodels/fds-smv/wiki/Two-Factor-Authentication](url) entry: "1. Download and install the windows credential store software" contains a link to a dead project (git-credential-winstore).

New maintained replacement software is at [https://github.com/Microsoft/Git-Credential-Manager-for-Windows](url)

**Comment by rmcdermo** [comment]
OK, I fixed.
