### ISSUE TITLE
Matlab plots with multiple dependent variables need a fix

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3916]
[Smyth_Slot_Burner_7mm_Oxygen.pdf](https://github.com/firemodels/fds-smv/files/301106/Smyth_Slot_Burner_7mm_Oxygen.pdf)
In the attached plot, the legend is not quite right. This seems to be related to the double line functionality in dataplot.m, but I can't figure out exactly what it is.

**Comment by rmcdermo** [comment]
More concerning is the value of O2 in the fine resolution case.  I will
look at it.

**Comment by rmcdermo** [comment]
I have not way to test this because Matlab 2011 (which is what we use on blaze) will not run on my mac.  With the version of Matlab I have (r2015), the plots look fine.  We need to get the version of Matlab upgraded on our clusters.
