### ISSUE TITLE
HRRPUA for wood- NIST Tech Note 1838

### ISSUE THREAD

**Issue by Chauddiere** [firemodels/fds#3926]
Hello experts,

While reviewing NIST Technical Note 1838, the FDS code line on page 10 of the report (&SURF ID='FIRE', HRRPUA=2250., COLOR='ORANGE', TAU_Q=10 /) is unclear to me as it was also stated that HRRPUA for wood is 50 kW/m2.

Before I am posting this I did search and sadly, the link I found is "broken".  the link is:
[TeX]response.tex nist-fire.googlecode.com/svn/trunk/Studies/2012_Chicago/Report/response.tex

"The authors then go on and use a HRRPUA=2250kW/m2. Why did not use the original 50kW/m2 and expand the area burning? Additional explanation would be ..."

It seems that the question I have has been already addressed but due to the broken link, I am unable to appreciate what the answer is.  I hope that either someone has a way to go back to the old nist-fire-googlecode or can offer an explanation.

**Comment by mcgratta** [comment]
The authors of this report no longer work at NIST. I will assign the case to one of the authors.

**Comment by cweinschenk** [comment]
Hi @Chauddiere,

The repository is now on github and the document can be found here: https://github.com/NISTFire/nist-fire/blob/master/Studies/2012_Chicago/Report/response.tex

For this analysis we certainly could have applied a 50 kW/m^2 HRRPUA over all the area that was burning. Instead, what we did was sum the burning area multiply it 50 kW/m^2 to find a total HRR. Then we applied that to a smaller area within the attic with a larger HRRPU to have an equivalent HRR. While this process would result in some local differences within the attic in terms of fire development, the fire became underventilated (as seen by external burning in model and on-scene photos) and we were concerned with large scale effects.

Another issue was with grid resolution. We did not model the joists and other construction components so we would have had to come up with several different equivalent HRRPUA for those elements. We would have also run into some issues with D\* and Q*. Therefore we went with a HRRPUA over a specified area.

Hope this helps answer your questions. Let me know if there is anything else.

**Comment by Chauddiere** [comment]
Thanks for the quick reply!

Even though it helps and it makes sense.  I did figure out how the 12,150 kW/m2 was obtained.

What I am puzzled with is the HRRPUA of 2250 in the SURF line.  Why is it 2250 kW/m2 in lieu of 50 kW/m2?  Is it your "interpretation" of the heat release over time as a strait line, starting at 0 sec, 0 HRRPUA to 2250 kW/m2 at 10 sec?  Are the code lines on page 10 addressing the porch fire only?  

Am I correct to say that you considered 2 vents of 0.5 m x 4.0 m =2.0 m2 each giving us 200 kW (4.0 x 50)?  By the way, what HRRPU?

I appreciate your assistance understanding this fire problem.

Cheers, Chauddiere

**Comment by Chauddiere** [comment]
Kevin,

I appreciate your help!

**Comment by cweinschenk** [comment]
HRRPU was just a typo, HRRPUA is what I meant, sorry. 

In the attic there are two fires each one is .5m x 4m = 2m^2. 
2m^2 \* 2250 kW/m^2 = 4500 kW
2 fires \* 4500 kW = 9000 kW or 9 MW

Then there is a fire in porch that that 1 m x 1.5 m = 1.5 m^2
1.5  \* 2250 kW/m^2 = 3375 kW or 3.375 MW

We could have applied 50 kW/m^2 HRRPUA over the 247 m^2 of area that was estimated to be fuel but it was not reasonable based on the reasons I discussed above. Therefore, the area was simplified and an adjusted HRRPUA was used. 

In total this is 12.375 MW. There is a 10 s ramp to max applied to all the fires to minimize any abrupt changes in mass flow at a boundary condition. Yes, the HRR is assumed to be constant. We were not trying to model the growth of the fire and all of our known information of the fire starts after it had grown sufficiently large to be seen by a passer-by.  It was estimated that there was sufficient fuel to sustain this over the duration of the simulation. This is of course a simplification of the fire  but it is the best we could do with the information that was known. We do know that fire was still ventilation controlled (plenty of fuel) until the fire was extinguished by the fire service.

**Comment by Chauddiere** [comment]
Again, thank you for the quick reply.  I still do no see how a value of 2250 kW/m2 was derived.  I do appreciate that most of the time one needs to simplify actual complex events to simpler and more manageable fire scenarios.  The key is often how reasonable those simplifications are.  In a practical sense, one would expect that the 2250 kW/m2 value be compared to another known value to build a platform of reasonableness.  

Could you please share the reasoning and support to arrive at an HRRPUA of 2250 kW/m2?  I am sure that you appreciate my inquiry given it is well established that the HRRPUA for wood is 50 kW/m2.

**Comment by cweinschenk** [comment]
50 kW/m^2 \* 247.5 m^2 = 12360 kW. We simplified the burning area down to three areas of 2x2m^2 + 1.5 m^2 = 5.5 m^2. 12360/5.5 = 2247.27 kW/m^2 ~ 2250 kW/m^2. We released the equivalent amount of energy as wood spread over 245.7 m^2 in 5.5 m^2. This was done to simplify the simulation. We were not concerned with small scale effects of it being wood that was burning. We used the 50 kW/m^2 as tool to estimate the amount of energy that would have been in the attic.

**Comment by Chauddiere** [comment]
Thank you very much for taking the time to explain how you arrived at the value of 2250 kW/m2.  I would assume that you have used many iterations (simulations) to arrive at a number that reflected what was captured in photographs and videos of the fire.  Do you know (approximately) how many iterations you performed before you were satisfied with the fire scenarios?

Again, thanks a million!

**Comment by cweinschenk** [comment]
I do not remember an exact number. It also varies by case. We spend a lot of time upfront to start with a well justified design fire for the scenario based on all the information we have. There are some iterations involved when coupling the timeline to ensure all aspects come together to match what happened physically. 

Since this isn't an issue with FDS though, I am going to go ahead and close this thread.

**Comment by Chauddiere** [comment]
Thank you very much for your effort.  I do appreciate it!
