### ISSUE TITLE
Control circular vents

### ISSUE THREAD

**Issue by zrui** [firemodels/fds#3929]
Hello, 

When associate activation and deactivation control to a circular vent,  it doesn't show corresponding results in smokeview.  It states 'Mirror' or 'Open' vents should not be activated or deactivated in FDS user guide section 15.4.2, but doesn't explicitly mention 'circular' vent,  however investigating the smokeview source reveals that parsed OPEN_VENT and CLOST_VENT information all stored into meshi->ventinfo (circular vent information is stored in meshi->cventinfo).   

Does that mean circular vent should not be associated with controls(like activation or deactivation) or at this least FDS doesn't support it at this point?

**Comment by mcgratta** [comment]
Could you post a very simple example case. I do not understand exactly what you are asking.

**Comment by zrui** [comment]
Hi mcgratta, 

I have attached two examples, one with circular vent always on, the other one associated an control with it, which activate or deactivate the circular vent at specified times. 

The example with circular vent always on can see fire, smoke, isosurface in smokeview,  while the one with control on doesn't. 

Thanks for your help,

[cvent-nocontrol.zip](https://github.com/firemodels/fds-smv/files/307724/cvent-nocontrol.zip)
[cvent-withcontrol.zip](https://github.com/firemodels/fds-smv/files/307728/cvent-withcontrol.zip)

**Comment by gforney** [comment]
thanks for the test cases.  we've identified issues in both FDS and smokeview.  we are taking a look at them.

**Comment by gforney** [comment]
smokeview needs FDS needs to :
1.  add OPEN_CVENT and CLOSE_CVENT .smv keywords analogous to OPEN_VENT and CLOSE_VENT for specifying when circular vents open and close
1.  indices passed to OPEN_VENT, CLOSE_VENT and the new OPEN_CVENT, CLOSE_CVENT keywords need to be tracked separately  .  ie if 6 regular and 3 circular vents are specified in the input file and the 3rd circular vent is closed at some time, FDS would need to pass a 3 to CLOSE_CVENT not 9 .  Analogous for regular vents

**Comment by zrui** [comment]
Hi gforney, 

Thanks for the quick response. That matches my assumed solutions.

**Comment by mcgratta** [comment]
I believe I have fixed the problems in FDS, PR #3933. 

Glenn, could you check your case and confirm.

**Comment by gforney** [comment]
I updated FDS source to use OPEN_CVENT and CLOSE_CVENT for circular vents.   My test case is working (vcirctest3.fds in repo) 

There may be problems if the circular vent size is exactly zero.  Don't think the IF tests for testing whether a vent is circular or regular are consistent throughout the code

To OP, these changes will show up in a new bundle which we will be posting soon.
