### ISSUE TITLE
HVAC 'Leak' FDS 6.3.4/6.4.0

### ISSUE THREAD

**Issue by cfaurie** [firemodels/fds#3930]
Hello, 

In the FDS 6.4.0 Release Note, there is a point about the HVAC 'Leak' submodel, "Fixed bug in HVAC bc for leakage vents. Inflow and outflow boundaries are handled with slightly different logic and the HVAC model was not appropriately selecting the correct set of logic.". Can you explain a bit more what this is referring to? Couldn't find anything in the UG or TG. 

The exact same very simple input file (fire in a room with sufficient ventilation + door with a small leakage area at the top) run with FDS 6.3.4 and FDS 6.4.0 gives quite different results, see visibility slices below:
![image](https://cloud.githubusercontent.com/assets/13315351/15938316/986be428-2e6a-11e6-8b60-8e41718a9889.png)

Thanks for your help, 
Coraline

**Comment by drjfloyd** [comment]
This was a bug fix. The description of the model in the Tech Guide and the inputs to the model in the User's Guide did not change. The model as described was not correctly implemented. There was an error in how the connection from an HVAC duct to the FDS domain was being handled. That error was fixed.  

Since I don't know your model inputs, I don't know what I should expect to see to able to draw any conclusions from your images. If you believe that 6.4.0 is incorrect please add an input file and describe what you expect to see.

**Comment by cfaurie** [comment]
The temperature in the fire room exceeds 300 degC rapidly (my fire is instantaneous just for verification purpose), so I'd expect the smoke leaking from the top of the door to be hot, and therefore to rise as FDS 6.3.4 predicts. 

The smoke out of the door is indeed hot at the beginning of the simulation, but seems to suddenly snap back to 20 degC after around 25 s with FDS 6.4.0. I'm not sure why. The NODE TEMPERATURE device that I set up says the contrary, with an outflow temperature at around 300 degC, as expected, for both versions of FDS. 
[Defect.txt](https://github.com/firemodels/fds-smv/files/307565/Defect.txt)

I've attached the input file.

Thanks, 
Coraline

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
I am seeing the same behavior. Something definitely seems to be wrong.

**Comment by cfaurie** [comment]
You probably already noticed it, but I of course meant FDS version 6.3.2, sorry. Let me know if I can help!

**Comment by drjfloyd** [comment]
Fixed. The issue was computing the leak enthalpy as T_DUCT_CP(T_DUCT,ZZ_DUCT)-T_GAS_CP(T_GAS,ZZ_GAS) instead of T_DUCT_CP(T_DUCT,ZZ_DUCT)-T_GAS_CP(T_GAS,ZZ_DUCT). 

https://github.com/firemodels/fds-smv/commit/a05e5aa1073c7e60b06337fc31ead15fd57dde38

**Comment by cfaurie** [comment]
Great thanks. I suppose the fix will be available in the next release? 

Do both versions of FDS show the same results now?

**Comment by drjfloyd** [comment]
Yes it will be in the next release. With the fix, the smoke remains hot.

**Comment by mcgratta** [comment]
The new release is out. Can you test your case.

**Comment by drjfloyd** [comment]
Tested with the release and fix is still working. Closing the issue.
