### ISSUE TITLE
Error codes should be traceable to user input parameters

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3939]
The recent [post by Daniel Bak](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/c7z-7gBltkE/XM8OLdYCBQAJ) highlights an example where the error message give by FDS (input TMP_V) points to a source code variable and not to the user input variable (VAPORIZATION_TEMPERATURE).  Need to go through and clean this up.

**Comment by mcgratta** [comment]
I just fixed this. Will post.

**Comment by mcgratta** [comment]
Merge #3940. Fixed.

**Comment by rmcdermo** [comment]
Thanks!
