### ISSUE TITLE
YZ plane vent control impacted by another circular vent

### ISSUE THREAD

**Issue by zrui** [firemodels/fds#3955]
Hello, 

When put vents on the surface of an obstruction(XZ plane, YZ plane, XY plane) and associate control with these vents,  the YZ plane vent does not show and hide as the control specified.

Here are two models demonstrate the issue, 
[yz-plane-vent-1.zip](https://github.com/firemodels/fds-smv/files/312539/yz-plane-vent-1.zip)
[yz-plane-vent-2.zip](https://github.com/firemodels/fds-smv/files/312540/yz-plane-vent-2.zip)

yz-plane-vent-1 has a circular vent, yz-plane-vent-2 take out of this circular vent, in the smoke view results, yz-plane-vent-1 model has the YZ plane vent on the obstruction always on,  but yz-plane-vent-2 model displays the YZ plane vent on and off correctly.

**Comment by mcgratta** [comment]
Did you compile and run the source code from GitHub? If not, we have not yet released a version of FDS that fixes these circular vent problems.

**Comment by zrui** [comment]
no, I still use the same version and I felt like this is a different issue than the previous one. Please ignore this issue if these are caused by the same circular vent problem.

**Comment by mcgratta** [comment]
My guess is that it is. Let's wait for the new version.

**Comment by zrui** [comment]
Sounds good.

**Comment by mcgratta** [comment]
We just released a new version of FDS, 6.5.0. Please check to see if your case works now.

**Comment by zrui** [comment]
Thank you, Kevin. I'll test it once I got some time to work on this.

**Comment by mcgratta** [comment]
Does the latest FDS release solve the problem?

**Comment by zrui** [comment]
Haven't got a time to test it yet, will let you know how it goes when we perform the testing.

**Comment by zrui** [comment]
Hi Kevin, 

Testing with the latest FDS release solved the problem. Good work!

**Comment by mcgratta** [comment]
Thanks for letting me know.
