### ISSUE TITLE
Spatial convergence for H in Shunn MMS

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3961]
With latest baroclinic iteration scheme the H convergence for Shunn MMS is not smooth and first order.  We are still accurate, but making this smooth should help the behavior of the iteration scheme.

**Comment by mcgratta** [comment]
The last verification run I did a few days ago looks good:
[shunn_mms_convergence.pdf](https://github.com/firemodels/fds-smv/files/314495/shunn_mms_convergence.pdf)
whereas the latest firebot figure does not
[shunn_mms_convergence.pdf](https://github.com/firemodels/fds-smv/files/314496/shunn_mms_convergence.pdf)
Could this be as issue related to when the data gets dumped:

```
         IF (T>=MMS_TIMER .AND. NM==1) THEN
            WRITE(FN_MMS,'(A,A)') TRIM(CHID),'_mms.csv'
            CALL DUMP_MMS(NM,FN_MMS,T)
            MMS_TIMER=1.E10_EB
         ENDIF
```

**Comment by rmcdermo** [comment]
Figures...  Thanks for the clue.  I'll have a look.

**Comment by rmcdermo** [comment]
This should be fixed with latest code.
