### ISSUE TITLE
Reduce frequency of symbols in HVAC plot

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3965]
Ben,
Please revamp this plot in the verification guide to
1. Make FDS results lines; and hence make ideal values symbols.
2. Reduce frequency of symbols.
![screen shot 2016-06-14 at 10 31 15 am](https://cloud.githubusercontent.com/assets/4418497/16046678/575ca4e0-321b-11e6-997d-87a05500f2fb.png)

**Comment by bmralph** [comment]
Looking at now.

**Comment by bmralph** [comment]
Pull request #3974 addresses this and other misc items with HVAC verification section.

**Comment by rmcdermo** [comment]
Ben,
These look good.  Thanks!

**Comment by bmralph** [comment]
@rmcdermo believe this can be closed (I can't).
