### ISSUE TITLE
Specie Mass is not balanced

### ISSUE THREAD

**Issue by Edward101** [firemodels/fds#3975]
I introduce a methane gas flow rate of 0.01 m3/s.
The outlet area is 100 m2, and the wind speed is 2 m/s, so the wind flow rate is 200 m3/s.
The methane concentration (averaged) at the outlet is supposed to be 0.00005.
However, the measured volume fraction (averaged) is 0.0008, which is 16 times larger than expected.

[MassBalance.txt](https://github.com/firemodels/fds-smv/files/315265/MassBalance.txt)

**Comment by mcgratta** [comment]
You can only have one DUMP line.
Use MASS_FLUX, not MASS_FRACTION on SURF line. Do not use VEL.
