### ISSUE TITLE
HVAC_aircoil verification case has mismatched labels

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#3990]
The file HVAC_aircoil.csv uses the term "Exact" whereas the dataplot input file uses the term "Ideal". This caused an error in firebot.

**Comment by bmralph** [comment]
Sorry - my error. Fixing now.

**Comment by bmralph** [comment]
Pull request #3991 addresses this.

**Comment by bmralph** [comment]
This can be closed @mcgratta (I can't).
