### ISSUE TITLE
Styrene H_F incorrect in *.out file

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#3994]
Jason,
I'm trying to debug an instability in the NIST_FSE_2008 case with ISOStyrene.  Input file is attached.  The heat of formation for styrene is given in two places in the .out file.  In the first location (primitive) the value is

```
   STYRENE
   Gas Species
   Molecular Weight (g/mol)           104.14912
   Ambient Density (kg/m^3)            4.330
   Enthalpy of Formation (J/kg)       -9.60E+36
```

Later (lumped) it is given as 

```
   STYRENE
   Molecular Weight (g/mol)           104.14912
   Ambient Density (kg/m^3)            4.330
   Initial Mass Fraction               0.000
   Enthalpy of Formation (J/kg)      8.33E+04
```

which seems more reasonable.

I suspect that the primitive value is just some default low number.  But I think it would be better say something like "not specified" or whatever, so that it does not look like a random bug.

[ISOStyrene16.fds.txt](https://github.com/firemodels/fds-smv/files/319025/ISOStyrene16.fds.txt)

**Comment by drjfloyd** [comment]
Fixed. Sorry for taking so long, I overlooked the email stating you had assigned it.

**Comment by rmcdermo** [comment]
No problem.  Thanks!
