### ISSUE TITLE
Multi-Slice files not showing QUANTITY

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4000]
Glenn,
In the case running at
/home4/rmcdermo/GitHub/fds-smv_rmcdermo/Validation/NIST_FSE_2008/Test/ISOStyrene16.fds

I am not seeing one of the slice quantities showing up in the "Multi-Slice" window.  In the input file

[ISOStyrene16.fds.txt](https://github.com/firemodels/fds-smv/files/320911/ISOStyrene16.fds.txt)

I have

&SLCF PBX=1.2, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE./
&SLCF PBX=1.2, QUANTITY='HRRPUV REAC', CELL_CENTERED=.TRUE./

But only HRRPUV REAC shows up in Multi-Slice

![screen shot 2016-06-17 at 12 39 42 pm](https://cloud.githubusercontent.com/assets/4418497/16157904/9e2d1444-3488-11e6-9bee-b1dc9b775e27.png)

In the Slice file dialog they both show up

![screen shot 2016-06-17 at 12 33 38 pm](https://cloud.githubusercontent.com/assets/4418497/16157790/1e5ba65e-3488-11e6-9fd6-68765f62340a.png)

It may very well be that HRRPUV only has non-zero values in one mesh, but I would expect to see zero values in the other in a Multi-Slice.

Here is SMV info

 Smokeview 6.3.7 - Jun 13 2016

 Version          : 6.3.7
 Revision         : Git-r12-0-g1273fac
 Revision Date    : Mon Jun 13 13:18:47 2016 -0400
 Compilation Date : Jun 13 2016 16:44:22
 Platform         : OSX64

**Comment by gforney** [comment]
my hunch is the problem is because "HRRPUV" is a subset of "HRRPUV REAC" .
As a test (ie not a fix - I will fix smokeview if my hunch is correct), try
changing the HRRPUV REAC keyword in FDS to something else say HRPUV REAC .
If this works then this tells me my hunch is right.  If it still doesn't
work I need to look elsewhere for the problem.

On Fri, Jun 17, 2016 at 12:38 PM, Randy McDermott notifications@github.com
wrote:

> Glenn,
> In the case running at
> 
> /home4/rmcdermo/GitHub/fds-smv_rmcdermo/Validation/NIST_FSE_2008/Test/ISOStyrene16.fds
> 
> I am not seeing one of the slice quantities showing up in the
> "Multi-Slice" window. In the input file
> 
> ISOStyrene16.fds.txt
> https://github.com/firemodels/fds-smv/files/320911/ISOStyrene16.fds.txt
> 
> I have
> 
> &SLCF PBX=1.2, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE./
> &SLCF PBX=1.2, QUANTITY='HRRPUV REAC', CELL_CENTERED=.TRUE./
> 
> But only HRRPUV shows up in Multi-Slice
> 
> [image: screen shot 2016-06-17 at 12 33 06 pm]
> https://cloud.githubusercontent.com/assets/4418497/16157775/10214d3c-3488-11e6-9b73-25196dd5506a.png
> 
> In the Slice file dialog they both show up
> 
> [image: screen shot 2016-06-17 at 12 33 38 pm]
> https://cloud.githubusercontent.com/assets/4418497/16157790/1e5ba65e-3488-11e6-9fd6-68765f62340a.png
> 
> It may very well be that HRRPUV REAC only has non-zero values in one mesh,
> but I would expect to see zero values in the other in a Multi-Slice.
> 
> Here is SMV info
> 
> Smokeview 6.3.7 - Jun 13 2016
> 
> Version : 6.3.7
> Revision : Git-r12-0-g1273fac
> Revision Date : Mon Jun 13 13:18:47 2016 -0400
> Compilation Date : Jun 13 2016 16:44:22
> Platform : OSX64
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/issues/4000, or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRhEYd_xgU1Tz4HB2lUV58Qlx27bIks5qMs10gaJpZM4I4h37
> .

## 

Glenn Forney

**Comment by gforney** [comment]
my hunch was wrong.  

This is what FDS outputs to the .smv file for each HRRPUV slice

SLCC     1 &    13    13     0    36     0    24
 ISOStyrene16_0001_01.sf
 HRRPUV
 hrrpuv
 kW/m3

This is what FDS outputs for each HRRPUV REAC slice

SLCC     1 &    13    13     0    36     0    24
 ISOStyrene16_0001_02.sf
 HRRPUV REAC
 hrrpuv
 kW/m3

If you change the second hrrpuv (the 'short label') to hrrpuv reac, smokeview should display the multi slices correctly

**Comment by rmcdermo** [comment]
I think this fixed by adding REAC_ID to the SLCF line.  I also added a trap in FDS to catch this.
