### ISSUE TITLE
FDS 6.5.0 Windows 7 Minor Install Issue

### ISSUE THREAD

**Issue by tgob** [firemodels/fds#4042]
I have a Win 7 x64 platform as adminstrator.  FDS 6.5.0 install failed wrapup_fds_install.bat at line systeminfo | findstr /C:"System Type" | findstr /C:"x64" | find /V /C "^"> %is64bitfile%.
systeminfo piped findstr's return System Type and x64, however find seems to be causing an issue with the command prompt warnings:

find: /C/hiberfil.sys Permission denied
find: /C/pagefile.sys Permission denied

Other command prompt output is overwritten so fast that I can't read it.

These files both exist on the root (and therefor probably do have access issues under Win 7).

On the find script command: can you run it with both the /C and /V options?, and should the ^ character be treated as a special character with the appropriate prefix?

My platform is x64 so I commented out the wrapup_fds_install lines from systeminfo to the end of the following if then else conscript (forcing the x64 path).

The install then completed just fine.

fyi

**Comment by gforney** [comment]
Start an issue and I'll take a look at it.

This is the first report we've gotten about a Windows 7 install failure.
Can you think of anything that would be different about your PC?

**Comment by tgob** [comment]
Thank you for your reply Glenn.  I thought I had posted this as a New Issue (Issue # 4041).

There have been no hardware changes to the environment since FDS 6.2.0 was released.  I am not aware of any OS changes (but this is a Windows System so goodness knows what Windows Updates may have been applied).

FDS 6.4.0 was loaded within the last week through a PyroSim 2016 update without incident.

Do let me know if I can provide any other information.

**Comment by gforney** [comment]
you did.  I was replying from gmail and was fooled into thinking your post was to the FDS user forum.

I was thinking more about whether your hard drives were configured differently.  I assume you installed as Administrator? I'm guessing the problem is that your installation didn't like where I was storing the temporary file used to store whether you have a 64 bit windows system or not.

**Comment by tgob** [comment]
Yes, I have administrator privileges (but my login name is not 'administrator', 'admin' or a variant - refer to first sentence of original post).  I have full privileges across the platform.

I'm not the sharpest knife in the block when it comes to script files but I'll try and modify the location for the temporary file used to store the x64 variable tomorrow and see if this makes for a clean install.  (It is kinda late here in Gods Own (NZ) just now).  I'll get back to you after this experiment.

I'm still confused about the -C and -V parameters for 'find' and the "^" target string.  While I don't believe everything I read on the  inter-web the parameters appear to be exclusive (use either -C or -V but not both) and the caret is a special character and must be preceded by a hash (just as " must be preceded by " in a literal search).  If you have sufficient patience to train the ignorant perhaps you can explain this.

There is nothing special about my drives on this platform.  Everything associated with FDS is on a 2 TB C: drive with an NTFS format.  The directory structure for FDS and SMV is default.  The drive is regularly backed up, defragmented and cleaned.

The only potential hiccough that I am aware of is Nortons 360.  However this usually reports when it is blocking (potentially) malicious activity.  The Nortons log is clean.   

As an aside I have also started on my Linux Beowulf cluster upgrade.  I am installing a new Mellanox 40 Gbs Infiniband LAN and it is timely (between commercial jobs) to upgrade FDS to the latest version.  The FDS upgrade was incredibly straight forward on all nodes although the text output reference to MPI 3.0 is a bit confusing when your complied version remains at OpenMPI 1.8.4.  FDS 6.5.0 is working just fine but I do anticipate problems with native Infiniband (SSH is already working).  I'll be taking this a step at a time.

With kindest regards,

t.

**Comment by tgob** [comment]
Problem found and fixed!

The wrapup_install_fds.bat file was executing find.exe from WinAVR as opposed to Windows\System32.

I have changed the directory order in the %PATH% environment variable (System32 now preceeds WinAVR) and the systeminfo line is now returning the line count for the "System Type" and "x64" filter.

There are no issues with the location of the is64bit file.

With kindest regards,

Tim

**Comment by gforney** [comment]
good detective work and thanks for reporting back!
glenn
