### ISSUE TITLE
Problem with FDS 6.5.0 Installation

### ISSUE THREAD

**Issue by guipesa** [firemodels/fds#4051]
Hi,

We are having some troubles with the FDS 6.5.0 installation. I attach an image with the error.

My windows machine is 64 bit. I don't know if someone is having the some trouble...

Kind regards,

Guillem,

![installation problem](https://cloud.githubusercontent.com/assets/14068673/16522272/0cebe2d8-3f9d-11e6-87c0-d9d80bd41396.png)

**Comment by gforney** [comment]
open up a command window and type:

systeminfo

look for the heading "System Type:"

what does it say?

On Fri, Jul 1, 2016 at 9:04 AM, guipesa notifications@github.com wrote:

> Hi,
> 
> We are having some troubles with the FDS 6.5.0 installation. I attach an
> image with the error.
> 
> Kind regards,
> 
> Guillem,
> 
> [image: installation problem]
> https://cloud.githubusercontent.com/assets/14068673/16522272/0cebe2d8-3f9d-11e6-87c0-d9d80bd41396.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/issues/4051, or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRlUuyGdd1ixgPnnw6dlxmHKM93hYks5qRRBfgaJpZM4JDIBl
> .

## 

Glenn Forney

**Comment by gforney** [comment]
also, note that FDS and Smokview only run on 64 bit systems.  The wrapup
script thinks you are not running on a 64 bit system so aborted the install.

The output of the systeminfo command will indicate what size system you
have .  Either you are running on 32 bit system or the wrapup script needs
to test for something different.

On Fri, Jul 1, 2016 at 9:04 AM, guipesa notifications@github.com wrote:

> Hi,
> 
> We are having some troubles with the FDS 6.5.0 installation. I attach an
> image with the error.
> 
> Kind regards,
> 
> Guillem,
> 
> [image: installation problem]
> https://cloud.githubusercontent.com/assets/14068673/16522272/0cebe2d8-3f9d-11e6-87c0-d9d80bd41396.png
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/firemodels/fds-smv/issues/4051, or mute the thread
> https://github.com/notifications/unsubscribe/AL1BRlUuyGdd1ixgPnnw6dlxmHKM93hYks5qRRBfgaJpZM4JDIBl
> .

## 

Glenn Forney

**Comment by guipesa** [comment]
Hi Glenn,

In system type it indicates x64-based PC

Thanks,
Guillem,

**Comment by gforney** [comment]
type 
where find

at a command line

**Comment by guipesa** [comment]
Hi Glenn, after type where find:

c:\Windows\system32\find.exe

**Comment by gforney** [comment]
type
systeminfo > output.txt
and upload the output.txt file

**Comment by guipesa** [comment]
Here you have,

Thanks,

[output.txt](https://github.com/firemodels/fds-smv/files/347747/output.txt)

**Comment by gforney** [comment]
found the problem.  I was searching for a string that would only be present in English versions of Windows ie not the version of Windows you are using.  I've changed the test for 64 bit windows that does not involve "language".  Try the bundle test located here
https://drive.google.com/folderview?id=0B-W-dkXwdHWNaG9keHVkQk9xNU0&usp=sharing

and let me know how it works.  Note, this bundle contains FDS 6.5.1 and Smokeview 6.3.9 .  This bundle is not "official"  .  Assuming the above bundle test works for you, we do plan on releasing an "official" bundle in the next few days.

**Comment by guipesa** [comment]
Hi Glenn,

Right now it works fine. Thank you very much!

Guillem,

**Comment by gforney** [comment]
we just posted a new bundle - fds 6.5.1 and smokeview 6.3.9 .  you should install and work with this rather than the test bundle you installed yesterday.  thanks for reporting the problem.

**Comment by guipesa** [comment]
Perfect, Thank you for solve it!

**Comment by mcgratta** [comment]
You're welcome.
