### ISSUE TITLE
Velocity problem when moving between coarse and fine mesh

### ISSUE THREAD

**Issue by TopiR** [firemodels/fds#4056]
**FDS:**
 Version          : FDS 6.5.0
 Revision         : Git-r14-0-gec73757
 Revision Date    : Wed Jun 22 17:26:26 2016 -0400

 **SMW:**
 Version          : 6.3.8
 Revision         : Git-r14-25-g67210f5
 Platform         : WIN64  (Intel C/C++)
 Revision Date    : Thu Jun 23 10:23:55 2016 -0400

**Geometry:**
I have a "box" (30x50x36m) which faces all but two are 'open'. One mesh face (z-) is set to inert and the second one (y-) have a boundary condition of atmospheric wind (etc. 2m/s and ple=0.3, at z=10m). Meshes are following: lower a finer 0.4x0.4x0.4m mesh and higer we have 2x2x2m mesh.

**Describe details of the issue below:**
This kind of geometry causes high flow velocity peaks on the iterface of these two meshes. This problem only occur with the current version of FDS (6.5) but the earlier v6.4 don't cause this kind of behavior. So the question is which of the updates causes this and is there work around?

![fig1](https://cloud.githubusercontent.com/assets/20284038/16563494/16336fc6-420b-11e6-9729-0772d6c9334b.PNG)
Fig1. Illustrated problem (red=4.5m/s and blue 0.0m/s).

[Wind.zip](https://github.com/firemodels/fds-smv/files/346475/Wind.zip)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
We made a small change in the way mesh to mesh boundary conditions are handled. These do not work well for cases like yours where the mesh resolution changes significantly. I posted new code if you want to compile it, or else wait for a maintenance release or keep using 6.4.

**Comment by TopiR** [comment]
Ty v6.4 suits my needs for now.

**Comment by mcgratta** [comment]
We just posted a maintenance release (6.5.1). Try it and report if it fixes the problem.

**Comment by TopiR** [comment]
New release fixed the problem.
