### ISSUE TITLE
Issue with Ramping in FDS

### ISSUE THREAD

**Issue by BradyElls** [firemodels/fds#4091]
I am trying to run my FDS model with a very basic ramping function. In my attached ramp.fds file, located before my obstruction code and after my Sites code, I have placed 2 groupings of 3 lines labeled RAMPVEL1 and RAMPVEL2. I then assigned RAMPVEL1 to 3 surface IDs, 2 of which are used on vents in my domain, while RAMPVEL2 is unused. When I run the code with the .fds file as is in the attachment, my code runs fine (1st screenshot). However, when I take out the RAMPVEL2 grouping, the code does not run (2nd screenshot), even though I am not actually using RAMPVEL2 anywhere in my code. The error I receive in the 2nd screenshot says there is an error with RAMPVEL1. I am unsure of what to do to fix my problem.

![ramp fds working](https://cloud.githubusercontent.com/assets/20443657/16812728/4b928a06-48e3-11e6-8d96-7b21c696c577.png)

![ramp fds not working](https://cloud.githubusercontent.com/assets/20443657/16812710/31309356-48e3-11e6-9789-bba7970b445c.png)

[ramp.txt](https://github.com/firemodels/fds-smv/files/362011/ramp.txt)

**Comment by drjfloyd** [comment]
You have no / at the end of your RAMP inputs.
