### ISSUE TITLE
mesh  division and automatic save

### ISSUE THREAD

**Issue by dy944533118** [firemodels/fds#4095]
Hello, I want to ask whether I can set up the mesh like this picture?
![mesh](https://cloud.githubusercontent.com/assets/19992906/16906611/14b31722-4ced-11e6-8388-0467e0f71911.png)

One side of the mesh is intensive, the adjacent side is sparse. I drew the mesh in PyroSim and the export code of PyroSim is like this picture.
![code](https://cloud.githubusercontent.com/assets/19992906/16906620/3d9762c4-4ced-11e6-8126-954fc07a1676.png)

 Then,I write the program “&MESH IJK=760,20,27,XB=-80,300,0.5,9.5,0,6.765/ 
 &MESH IJK=760,4,27,XB=-80,300,-0.5,0.5,0,6.765/” in FDS. But the software can't run. Why?
In addition, I have another small problem.The program “&DUMP DT_RESTART=100.0” in FDS can not achieve the function of automatic save. 
Could You answer me these two questions? Looking forward to your reply, thank you very much sincerely.

**Comment by mcgratta** [comment]
Is there an ERROR message? What do you mean that the software won't run?

**Comment by dy944533118** [comment]
Yes,the software won't run with the program “&MESH IJK=760,18,27,XB=-80,300,0.5,9.5,0,6.765/ 
 &MESH IJK=760,4,27,XB=-80,300,-0.5,0.5,0,6.765/” in FDS. But it is ok with the program “&MESH IJK=760,20,27,XB=-80,300,-0.5,9.5,0,6.765/ 
 &MESH IJK=760,4,27,XB=-80,300,-0.5,0.5,0,6.765/”

**Comment by rmcdermo** [comment]
Send us the error message or a screen shot of whatever Pyrosim is showing
you.

**Comment by mcgratta** [comment]
This file:

```
&HEAD CHID='grid' /
&MESH IJK=760,20,27,XB=-80,300,0.5,9.5,0,6.765/
&MESH IJK=760,4,27,XB=-80,300,-0.5,0.5,0,6.765/
&TIME T_END=1. /
&TAIL /
```

runs for me with 2 MPI processes. FDS 6.4.0. What version are you using?

**Comment by dy944533118** [comment]
FDS6.5

**Comment by mcgratta** [comment]
OK, let me install the latest release version on my computer.

**Comment by mcgratta** [comment]
```
[mcgratta@burn Test]$ mpirun -np 2 fds grid.fds
 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 OpenMP thread   3 of   3 assigned to MPI process      0 of      1
 OpenMP thread   2 of   3 assigned to MPI process      0 of      1
 OpenMP thread   1 of   3 assigned to MPI process      0 of      1
 OpenMP thread   0 of   3 assigned to MPI process      0 of      1
 OpenMP thread   3 of   3 assigned to MPI process      1 of      1
 OpenMP thread   2 of   3 assigned to MPI process      1 of      1
 OpenMP thread   1 of   3 assigned to MPI process      1 of      1
 OpenMP thread   0 of   3 assigned to MPI process      1 of      1
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : July 18, 2016  09:21:48
 Version          : FDS 6.5.1
 Revision         : Git-r16-0-g9ea0a92
 Revision Date    : Tue Jul 5 21:19:11 2016 -0400
 Compilation Date : Jul 06, 2016  08:57:57

 MPI Enabled; Number of MPI Processes:          2
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Open MPI v1.8.4, package: Open MPI gforney@blaze Distribution, ident: 1.8.4, repo rev: v1.8.3-330-g0344f04, Dec 19, 2014

 Job TITLE        :
 Job ID string    : grid

 Time Step:      1, Simulation Time:      0.19 s
 Time Step:      2, Simulation Time:      0.38 s
 Time Step:      3, Simulation Time:      0.57 s
 Time Step:      4, Simulation Time:      0.77 s
 Time Step:      5, Simulation Time:      0.96 s
 Time Step:      6, Simulation Time:      1.00 s
MPI process      1 has completed
MPI process      0 has completed

STOP: FDS completed successfully (CHID: grid)
```

**Comment by dy944533118** [comment]
1: Hello, the program “&DUMP DT_RESTART=100.0” in FDS can not achieve the function of automatic save, why?
2: the problem is as shown in the figure below.
![file](https://cloud.githubusercontent.com/assets/19992906/16953904/653f1e38-4e01-11e6-972d-f7637e3b1dee.png)
[file.zip](https://github.com/firemodels/fds-smv/files/371689/file.zip)

**Comment by mcgratta** [comment]
This case does not run with FDS 6.5.1

```
ERROR: XB for DEVC fireleft_flow must be completely within a mesh. (CHID: SZ7)
```
