### ISSUE TITLE
Feature request: show geometry in smokeview, but do not calculate

### ISSUE THREAD

**Issue by crogsch** [firemodels/fds#4096]
All,

during the modelling of industrial buildings, a question came up, and I don't know how to deal with in a simple way: In the industrial building, we have some footbridges and decks made of grating, like the picture from wikipedia shows: https://en.wikipedia.org/wiki/Grating#/media/File:Stahlbau_mit_Gitterrosten.JPG

Now these footbridges and decks should be visible in smokeview to show the "real" building, but they should not considered in the calculation, because they should have no influence on the smoke movement.

Using an evacuation mesh was possible, and I got the result, but this is very difficult to handle, because an additional evacuation calculation (with 0 pedestrians) is necessary, which I would like to avoid. Some models are so "difficult", that I would like to have only a fire calculation to keep things simple.

So, my feature request is as follows (if it is possible): Add a parameter to an the &OBST keyword, which allows only Smokeview to show the OBST, but FDS would not consider it for calculation. So, it would be helpful if I could use all the parameters for an OBST, like TRANSPARENCY or SURF_ID, or whatever, to model an OBST and only add an additional parameter, like "SMOKEVIEW_ONLY", so that the OBST is written to the SMV-file, but not considered in the calculation (this means smoke, heat, velocity, radiation, ... will move through this OBST, and it has no influence of the calucated result). This means I do not need any "EVACUATION" commands in the file.

It would be great, if this would be possible. If you have some other ideas to realize this, feel free to post...

Regards from Germany
Christian

**Comment by rmcdermo** [comment]
Christian,
Have you thought about using Lagrangian particles to represent the grates?  These can be added to the model with INIT lines.  Various properties can be assigned to the particles for flow interaction and visualization.  Actually, the grates you show should affect flow in some way.
Regards, Randy

**Comment by mcgratta** [comment]
But if the object is purely Smokeview-only, there are ways to create custom objects within Smokeview. See the Smokeview User's Guide.

**Comment by crogsch** [comment]
Randy, Kevin,
thanks for your reply.

@rmcdermo The picture from wikipedia was just an example to show the elements I mean. Translating from German to English is sometimes not as easy, because I found 9 different words in the online dictionary for the German word "Gitterrost". So I decided to link to this picture to be sure, that you understand the type of element I want to model. In reality I have a simple footbridge or anything like this, which is inside the room. This "element" is normally so small, that it can be neglected in a very big industrial building, but it should be there to show the customer "here is your footbridge", so that the visual representation of the building is more "realistic". But I will try your hint based on the Lagrangian particles.

@mcgratta I think you want to point to Chapter 6 of the Smokeview User's Guide ("Creating Custom Objects"). I have thought about that, but for a simple geometry like a footbridge, it seems to be a little bit "oversized". I just thought about a very simple solution, which can be easily realized with a gui like Pyrosim or whatever, which means I just draw this simple object (e.g. a rectangle from A to B) and add this additional paramter to the OBST line, and that's all. 

But I will try both of your suggestions, maybe they are more simple than I thought.

Regards,
Christian

**Comment by rmcdermo** [comment]
Christian,
Please know that we are not ignoring your request.  But I do think that
touching OBST would not be as simple as you imagine in FDS.  I would prefer
to use available features if at all possible.  Thanks.
Randy

**Comment by mcgratta** [comment]
This is tricky because FDS cannot just ignore an `OBST`. It must read and process the OBST along with all the others and then pass the information about the `OBST` to the .smv file. Then we would have to put `CYCLE` commands in all the loops that work with `OBST`. But here's a hack, and let me know if it works. You can create the `OBST` that you want to ignore, and give each one a `DEVC_ID` like this:

```
&OBST XB=..., DEVC_ID='timer' /
&DEVC ID='timer', QUANTITY='TIME', SETPOINT=0., INITAL_STATE=.TRUE. /
```

You can use the same `DEVC_ID` for all `OBST` lines you want to ignore. The obstruction should disappear at the start of the simulation and never return. Now, edit the `.smv` file. Look for the string `HIDE_OBST` and change the time to a large value. Now Smokeview should draw the obstruction even though FDS ignored it. 

Let me know if this works.

**Comment by rmcdermo** [comment]
If this works, we are going to have to come up with a new award: The McGrattan "Hack of the Year" Award!

**Comment by gforney** [comment]
would that be a McGrattHack ?

**Comment by crogsch** [comment]
Excellent! 
This is the "Hack of the Year"! 
All works as expected, and it is very simple. And visualization in Smokeview is also perfect. I attached some pictures with transparent (green and gray) and a non-transparent (blue) OBSTs, you can see that Particles, Streaks and Slicefiles are visualized perfectly, as if these three OBSTs do never appear.

I never thought about that! Thank you very much for this "hack". Maybe you should add this to the UserGuide to document this possibility, if other people have the same issue.

Feel free to close this issue or mark as solved! Thanks again (and happy "hacking")!

Kind Regards
Christian
![obst-test_0159](https://cloud.githubusercontent.com/assets/10404779/17014704/37989d26-4f26-11e6-9e3e-a6077af9fdea.png)
![obst-test_0164](https://cloud.githubusercontent.com/assets/10404779/17014702/379713b6-4f26-11e6-9fdc-69de8ea8c6ab.png)
![obst-test_0293](https://cloud.githubusercontent.com/assets/10404779/17014701/37969238-4f26-11e6-8360-f305f3a498e6.png)
![obst-test_0297](https://cloud.githubusercontent.com/assets/10404779/17014703/37986694-4f26-11e6-9c14-0b94a79b5c34.png)

**Comment by mcgratta** [comment]
It's not a hack; it's an "undocumented feature"!

**Comment by gforney** [comment]
how about if you add a SMV_ONLY keyword to the &DEVC line.  If false FDS would act as usual.  If true FDS would not output any HIDE_OBST or SHOW_OBST lines to the .smv file.   FDS could then process OBST lines as usual but then smokeview would not be told to hide them .  I tried to do this in smokeview but smokeview does not have info it needs to associate a given device with a blockage, it is only told to show or hide a blockage

**Comment by mcgratta** [comment]
I worry that these namelist parameters are already over-loaded.
