### ISSUE TITLE
Get rid of 'AIR' as a primitive species

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4108]
Jason,
Maybe we've talked about this before, but I propose we get rid of 'AIR' as a primitive species.  The reason is if you have a case like this

&HEAD CHID='test_spec' /
&MESH IJK=10,10,10, XB=0,1,0,1,0,1 /
&TIME T_END=0. /
&SPEC ID='MY AIR' /

You get the following lumped species:

![screen shot 2016-07-21 at 4 51 56 pm](https://cloud.githubusercontent.com/assets/4418497/17038382/76463988-4f63-11e6-9784-76efdfe2bdaa.png)

My expectation would be that my new tracked species would have _identical_ properties as the default 'AIR' species.  But they are very slightly different, densities are 1.196 kg/m3 for 'AIR' and 1.199 kg/m3 for 'MY AIR'.

I would say that instead of hardwiring the properties for 'AIR', make it a function call that grabs the default mass fractions of N2, O2, etc.

**Comment by drjfloyd** [comment]
The current primitive species for AIR uses Lennard-Jones parameters for air whereas the default lumped species does not (it averages over the subcomponent species). Lumped air also contains a variable amount of WATER VAPOR depending on TMPA. For primitive AIR to be the exact same as lumped AIR that entire logic would have to be replicated outside of the normal species handling.   

Rather than replicating a lot of code in another location: We can make clearer in the User's guide the primitive AIR is a single species that only approximates the default background species or we could have AIR always invoke the lumped species and then have new species use NITROGEN properties as a default.

**Comment by rmcdermo** [comment]
OK, this is not a high priority.  I don't want it to be a lot of work.  I would have thought all the data for the primitive spec AIR could have been turned into function calls to a look up table to lumped AIR (provided lumped air was already built, which would probably require some rearrangement in read).

**Comment by drjfloyd** [comment]
We only build lumped AIR if it is the default background species.  If a USER were to do 
&SPEC ID='MY AIR',DEFAULT=.TRUE./  then there would be no default lumped AIR.  

If we always want AIR utilize all the same properties as the default background lumped species, the easiest route may be to go with option 2 above and always have AIR be lumped (e.g. AIR can't be a primitive species) and have new species use NITROGEN properties as a default.

**Comment by rmcdermo** [comment]
In that case, we could have

&SPEC ID='my air', SPEC_ID='AIR', MASS_FRACTION=1 /

correct?

Another option would be to create a primitive 'LJ AIR' (or something) that would be our current primitive air and the default for new primitive species properties.  Though... I would personally rather use NITROGEN.  I think it is a clearer story to say AIR is always a lumped species and species like O2, N2, etc., are primitive.

**Comment by drjfloyd** [comment]
I concur with your last statement and will make changes.

**Comment by drjfloyd** [comment]
On further thought I think I will make an LJ AIR that is primitive and have AIR be lumped.  AIR has four subspecies which adds some cost in the various GET_property routines; LJ AIR is one species. For cases like a dispersion analysis with no combustion having LJ AIR available would have a slight reduction in cost.  I'll make sure what LJ AIR is clear in the Guide.

You input statement above
&SPEC ID='my air', SPEC_ID='AIR',MASS_FRACTION=1/

is not allowed.  We do not have the ability to use a lumped species as a primitive species (i.e. you can only define a lumped species using primitive species).

**Comment by rmcdermo** [comment]
Problem is that this sort of defeats the goal of easily specifying a tracer
with identical properties of lumped AIR.

How hard would it be to have a new SPEC parameter like
COPY_LUMPED_SPEC_ID='AIR' ?

**Comment by drjfloyd** [comment]
I think that won't be hard to do.

**Comment by drjfloyd** [comment]
I added the logical flag COPY_LUMPED to SPEC.  So now you can have:

&SPEC ID='MY AIR',SPEC_ID='AIR',COPY_LUMPED=.TRUE./

**Comment by rmcdermo** [comment]
Great.  Thanks.  I'll test once I get the particle stuff done.

**Comment by rmcdermo** [comment]
Tested.  Works great.  Thanks.
