### ISSUE TITLE
Textures for device

### ISSUE THREAD

**Issue by zrui** [firemodels/fds#4111]
Does latest release of Smokeview support device textures? Tried to put texture information by follow keyword=value pattern under PROP keyword in smv file, but didn't see texture got rendered.

Also tried to give :tfile a value in objects.svo file, got :
**\* Error : the label $tfile in device tsphere is not defined

Any advice for how to apply textures to device in Smokeview?

**Comment by gforney** [comment]
Sorry, textures in devices is not supported.

**Comment by zrui** [comment]
Thanks for the reply. Good to know.
