### ISSUE TITLE
MLR and Yeilds

### ISSUE THREAD

**Issue by Nitin-Bhaskar** [firemodels/fds#4113]
Hi all, 

I have two slightly different options for the chemical formula of fuel, i.e. C=1, H=2, O=0.5 or C=1, H=2.2, O=0.62., with a Heat of combustion of 20,000 kJ/kg. 

Along with each of the above I use a CO_YIELD of 0.04 and SOOT_YIELD of 0.07.

My understanding is that with the same HEAT_OF COMBUSTION value the MLR calculated will be same in both cases and will produce the same amount of SOOT (visibility slices). However, I notice that there is a slight difference in the visibility slice files produced in both the cases. 

Can someone please point to what could be the reason behind this ?

I understand that if I do not define a HEAT_OF COMBUSTION value a default of 13.1kJ/kg of Oxygen will be used to calculate the MLR, which in that case would be slightly different for both cases, producing slightly different visibility slice files. 

However, by defining the same value for HEAT_OF COMBUSTION in both cases (slightly different chemical formula) I was expecting to see identical visibility slice files. That did not happen !

Also, I have noticed that though by defining the same HEAT_OF COMBUSTION value in both cases I have the same MLR in both but the amount of oxygen consumed and CO2 and H2O produced are slightly different. Can this be the reason behind difference in visibility slices ? If so, How? Is it because the solution of mass transport equation for lumped 'fuel' species will vary ? or something else ? details, references welcome.

Regards,
Nitin

**Comment by rmcdermo** [comment]
This should be posted to the discussion forum.  It is not a bug.

MLR will be different for fuels of different MW.  Look at your .out files to see the specific differences in the two fuels you specified.

**Comment by rmcdermo** [comment]
Sorry, I was not thinking.  MLR will be the same for given HRR and HOC.  But other properties, for example, density of the fuel, will be different, and can easily cause changes in the solution.  The advice to examine the .out file for difference still holds.
