### ISSUE TITLE
Radiative Fraction - Output

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#4114]
The parameter RADIATIVE_FRACTION allows to specify explicitly the fraction of the total combustion energy that is released in the form of thermal radiation. By default, the RADIATIVE_FRACTION is based on the FUEL. 

I know that the $\chi$ (fraction) vary in space and time. Is it possible to implement the default-$\chi$ in the diagnostic output file or as min/max/mean $\chi_t$?

**Comment by rmcdermo** [comment]
Output QUANTITY='CHI_R'

Jason, please add to user guide.

**Comment by drjfloyd** [comment]
Done.

**Comment by gjaeger** [comment]
Thanks.
