### ISSUE TITLE
Modelling Flame Spread using SURF burners, the issue with the number of SURF / DEVC / CTRL / RAMP

### ISSUE THREAD

**Issue by adamxiaoli** [firemodels/fds#4129]
Hi Kevin,

I have attached two input files, Car-coarse.fds is running OK with FDS6.5.1 OpenMPI 1.8.4 on a Linux 32 Core computer.  But the Car-fine.fds showed up the following 

```
[shafire@Ls-dyna9 car_fine]$ mpirun -np 7 fds Car.fds
 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 Mesh      3 is assigned to MPI Process      2
 Mesh      4 is assigned to MPI Process      3
 Mesh      5 is assigned to MPI Process      4
 Mesh      6 is assigned to MPI Process      5
 Mesh      7 is assigned to MPI Process      6
forrtl: severe (174): SIGSEGV, segmentation fault occurred
forrtl: severe (174): SIGSEGV, segmentation fault occurred
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
```

(some more)

The two inputs are basically using the same 3D model except the number of VENT/CTRL/DEVC. I think if Car-coarse.fds could run then it means Car-fine.fds has no technical issue but limited by the computer capacity.  I tried OMP_NUM_THREADS=1 and 4, and also tried 'ulimit -s unlimited', all of them did not work and showed the same error. 

Please help me debug it if possible. 

Thank you!

Xiao 
[Car-coarse.txt](https://github.com/firemodels/fds-smv/files/387923/Car-coarse.txt)
[Car-fine.txt](https://github.com/firemodels/fds-smv/files/387930/Car-fine.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
There is a hard limit of 1000 for the number of `RAMP`s. I will add an ERROR statement to stop the code in a case like this.

**Comment by drjfloyd** [comment]
Do we need a hard limit?

**Comment by mcgratta** [comment]
`RAMP`s are counted as the various `RAMP_ID`s are processed. They are both counted and their `ID`s are stored in an array. We never really need hard limits for anything, but the code logic becomes more complicated.

**Comment by drjfloyd** [comment]
All we would need to do is have a reallocate function called before we set a RAMP_ID.  I can add this.

**Comment by mcgratta** [comment]
I will do it.

**Comment by adamxiaoli** [comment]
So I have to wait for the next release to fix this issue?

**Comment by mcgratta** [comment]
Yes, but I think you should reconsider your entire approach. Your input file has over 200,000 lines. That's more than the lines of code in FDS. Even when I fixed the limit on the number of `RAMP`s, your case still took over an hour (and I killed the job at that point) just to read and process the input file. The reason is that each `RAMP` line this is read requires a rewind of the input file. That is , each `RAMP` line. You have over 9000 `RAMP` `ID`s, and many more individual `RAMP` lines. I cannot imagine what would necessitate this number of `RAMP`s and controls. I am not going to change the logic of reading in these `RAMP` lines. I suggest you rethink your approach.

**Comment by adamxiaoli** [comment]
Hi Kevin and Dr.Floyd,

I am wondering when the next release will be done? 
Thanks for your suggestion. The FDS input I created is for a research project, and we tried to perform kind-of programming within FDS. I know FDS is not built as a programming language thus that is why so many RAMPs CTRLs DEVCs are used for some actually simple math operations, for instance,

```
&SURF ID='BURNER1',HRRPUA=266,COLOR='ORANGE',RAMP_Q='BURNER_FLUX1', TMP_FRONT=1000.0,RAMP_T='BURNER_TEMP1'/ 
&RAMP ID='BURNER_FLUX1', T= 0.0, F=0.0 , DEVC_ID='HRR_Scale1' /  
&RAMP ID='BURNER_FLUX1', T= 4.0, F=4.0 /
&RAMP ID='BURNER_TEMP1', T= 0.0, F=0.0 , DEVC_ID='Surf_Temp_Scale1' / 
&RAMP ID='BURNER_TEMP1', T= 4.0, F=4.0 /
```

The above two RAMP IDs are just used to pass two variables HRR_Scale1 and Surf_Temp_Scale1. It would be great if HRRPUA could be assigned directly by a variable. 

In another case we found difficulties was when we tried to get a return of a CTRL function, the states of CTRL values are -1 and 1,  but we failed to get the integer value of -1 and 1, by doing that we wanted to multiply this value with another in order to change its sign, just like the example below, 

```
&DEVC ID='NETHF',QUANTITY='NET HEAT FLUX', SETPOINT=0.0, XYZ=0.0,0.0,0.05, IOR=3, LATCH=.FALSE./
&CTRL ID='Sign of NETHF',FUNCTION_TYPE='ANY',INPUT_ID='NETHF',SETPOINT=0.0,LATCH=.FALSE./ it returns state value -1 and 1 
&CTRL ID='Power',FUNCTION_TYPE='POWER',INPUT_ID='NETHF','CONSTANT',CONSTANT=2.0/ get NETHF^2
&DEVC ID='sign_value', QUANTITY='CONTROL', CTRL_ID='Sign of NETHF',XYZ=0.0,0.0,0.05/ I hoped to get -1 or 1 in numerical integer.  
&CTRL ID='Sign_Power', FUNCTION_TYPE='MULTIPLY', INPUT_ID='Power', 'sign_value'/ this is intended to assign signs to NETHF^2
```

In particular, do you have solutions for the latter problem?

Through the above examples, I am wondering whether future FDS would be expanded to accommodate functions like those?

Thank you very much. 

Xiao

**Comment by mcgratta** [comment]
I do not understand exactly what you want to do. Could you create a very very short test case (like 10 lines) that demonstrates the problem or the enhancement that you want.

**Comment by drjfloyd** [comment]
Case 1:

See the example in 15.6.2 in the User's Guide. You could make a RAMP like the following:

&RAMP ID='fire',T=-100000,F=-100000,CTRL_ID='your function name'/
&RAMP ID='fire',T=100000,F=100000/

In this case the fire uses a linear ramp of F=T whose input rather than time is now the output of your math ctrl function.

Case 2:
You need to have a DEVC that measures the output of the CTRL function.  See 15.5 in the User's Guide.

**Comment by adamxiaoli** [comment]
Thanks for your reply. I am describing the case in detail: I want to measure NET HEAT FLUX (q_net), and get its sign based on if it is a positive or negative value (Sign), and then calculate (Sign)x(q_net)^2. 
I found a way to get this today, unfortunately I have to use a RAMP, as follows:

```
&DEVC ID='NETHF',QUANTITY='NET HEAT FLUX',XYZ=0.0,0.0,0.05,IOR=3/
&CTRL ID='Sign of NETHF', FUNCTION_TYPE='CUSTOM', INPUT_ID='NETHF', RAMP_ID='Sign' /
&RAMP ID='Sign', T= -100000, F=-1 /
&RAMP ID='Sign', T= -0.00001, F=-1 /
&RAMP ID='Sign', T= 0.00001, F=1 /
&RAMP ID='Sign', T= 100000, F= 1 /

&DEVC ID='NETHF_Sign', QUANTITY='CONTROL VALUE', CTRL_ID='Sign of NETHF', XYZ=0.0,0.0,0.05/ 

&CTRL ID='Power',FUNCTION_TYPE='POWER',INPUT_ID='NETHF','CONSTANT',CONSTANT=2.0/ 

&CTRL ID='Sign_Power', FUNCTION_TYPE='MULTIPLY', INPUT_ID='Power', 'NETHF_Sign'/ 

&DEVC ID='Power_Sign', QUANTITY='CONTROL VALUE', CTRL_ID='Sign_Power', XYZ=0.0,0.0,0.05/ 
```

Before this solution I have actually tried three different ways, none of them can give (Sign)x(q_net)^2.

[test1.txt](https://github.com/firemodels/fds-smv/files/395250/test1.txt)
[test2.txt](https://github.com/firemodels/fds-smv/files/395249/test2.txt)
[test.txt](https://github.com/firemodels/fds-smv/files/395248/test.txt)

test.fds:

```
&DEVC ID='NETHF',QUANTITY='NET HEAT FLUX',SETPOINT=0.0,XYZ=0.0,0.0,0.05,IOR=3,LATCH=.FALSE./
&CTRL ID='Sign of NETHF',FUNCTION_TYPE='ANY',INPUT_ID='NETHF',SETPOINT=0.0,LATCH=.FALSE./ it returns state value -1 and 1 

&CTRL ID='Power',FUNCTION_TYPE='POWER',INPUT_ID='NETHF','CONSTANT',CONSTANT=2.0/ 

&DEVC ID='sign_value', QUANTITY='CONTROL', CTRL_ID='Sign of NETHF',XYZ=0.0,0.0,0.05/ it generates 0 for -1 and 1 for 1 

&CTRL ID='Sign_Power', FUNCTION_TYPE='MULTIPLY', INPUT_ID='Power', 'sign_value'/ this cause the negtive NET HEAT FLUX removed

&DEVC ID='Power_Sign', QUANTITY='CONTROL VALUE', CTRL_ID='Sign_Power', XYZ=0.0,0.0,0.05/ this returns the value of q_net^2 only for postive q_net
```

test1.fds

```
&DEVC ID='NETHF',QUANTITY='NET HEAT FLUX',SETPOINT=0.0,XYZ=0.0,0.0,0.05,IOR=3,LATCH=.FALSE./
&CTRL ID='Sign of NETHF',FUNCTION_TYPE='ANY',INPUT_ID='NETHF',SETPOINT=0.0,LATCH=.FALSE./ it returns state value -1 and 1 

&CTRL ID='Power',FUNCTION_TYPE='POWER',INPUT_ID='NETHF','CONSTANT',CONSTANT=2.0/ 

&DEVC ID='sign_value', QUANTITY='CONTROL VALUE', CTRL_ID='Sign of NETHF',XYZ=0.0,0.0,0.05/ it generates 0 for -1 and 1 for 1 

&CTRL ID='Sign_Power', FUNCTION_TYPE='MULTIPLY', INPUT_ID='Power', 'sign_value'/ this cause the negtive NET HEAT FLUX removed

&DEVC ID='Power_Sign', QUANTITY='CONTROL VALUE', CTRL_ID='Sign_Power', XYZ=0.0,0.0,0.05/ this returns the value of q_net^2 only for postive q_net
```

test2.fds

```
&DEVC ID='NETHF',QUANTITY='NET HEAT FLUX',SETPOINT=0.0,XYZ=0.0,0.0,0.05,IOR=3,LATCH=.FALSE./
&CTRL ID='Sign of NETHF',FUNCTION_TYPE='ANY',INPUT_ID='NETHF',SETPOINT=0.0,LATCH=.FALSE./ it returns state value -1 and 1 

&CTRL ID='Power',FUNCTION_TYPE='POWER',INPUT_ID='NETHF','CONSTANT',CONSTANT=2.0/ 

&CTRL ID='Sign_Power', FUNCTION_TYPE='MULTIPLY', INPUT_ID='Power', 'Sign of NETHF'/ 

&DEVC ID='Power_Sign', QUANTITY='CONTROL VALUE', CTRL_ID='Sign_Power', XYZ=0.0,0.0,0.05/ this returns the value of q_net^2 only for postive q_net
```

As you know I already have the problem with too many RAMPs. I am waiting for the next release. 

Thanks for you help. 

Xiao

**Comment by drjfloyd** [comment]
Do control functions to compute: Sqrt(x^2)/x

**Comment by adamxiaoli** [comment]
thanks. I hope I won't see "dividing by zero" issue.

**Comment by drjfloyd** [comment]
Add a very small number to the denominator.

**Comment by adamxiaoli** [comment]
thanks for you reply.

The number of RAMPs in my input codes exceed the hard limit 1000, due to I used two RAMPs for each SURF, see example as below,

```
&SURF ID='BURNER',HRRPUA=266,COLOR='ORANGE',RAMP_Q='BURNER_FLUX', TMP_FRONT=1000.0,RAMP_T='BURNER_TEMP'/ 

&RAMP ID='BURNER_FLUX', T= 0.0, F=0.0 , DEVC_ID='HRR_Scale' /  it passes the value to the SURF 
&RAMP ID='BURNER_FLUX', T= 4.0, F=4.0 /

&RAMP ID='BURNER_TEMP', T= 0.0, F=0.0 , DEVC_ID='Surf_Temp_Scale' /  it also passes the value to the SURF
&RAMP ID='BURNER_TEMP', T= 4.0, F=4.0 /
```

In order to simulate flame spread I could use 1000 SURF burners or more, the dilemma is the hard limit of RAMPs. 
So my question is: besides the above way to use two RAMPs to pass the values to the SURF, is there any other way? so I can avoid the issue caused by the over-limit of RAMPs. 

Thanks in advance. 

Xiao

**Comment by drjfloyd** [comment]
The same RAMP can be used more than once.  In your example BURNER_FLUX and BURNER_TEMP are the same RAMP.  Get rid of one of them and use the other twice.

**Comment by adamxiaoli** [comment]
thanks, Dr. Floyd, but could you explain more? 
in that example I pass the RAMP_Q and RAMP_T at the same time to a SURF burner. the two RAMPs are actually applied as dummy routine just to pass the values of the two DEVC measurements to the SURF.

**Comment by drjfloyd** [comment]
Sorry, I didn't read carefully enough. I see now that you are using two different DEVC for input, so you are correct that you can't use the same RAMP twice.

Have you considered combining your combustible objects into large OBST so that you need less RAMPs?

**Comment by mcgratta** [comment]
I committed a change to FDS to allow an infinite number of `RAMP`s. You can either compile the code yourself or wait for the next release.

**Comment by mcgratta** [comment]
A new release is out. Try it and see if this fixes the original problem. If not, reopen this case or start a new one.

**Comment by adamxiaoli** [comment]
Thank you very much. I will try out the FDS version 6.5.2. 

Xiao
