### ISSUE TITLE
STOP: FDS completed successfully (CHID: 1)

### ISSUE THREAD

**Issue by FPSSPF** [firemodels/fds#4133]
This is the output:
## s214028@valiant [273] 02:20 PM [test] mpirun -np 2 fds 1.fds

Executable: /apps/FDS/6.3.2/bin/fds_impi_intel_linux_64
Licence: Not applicable
## Licence contact: TBD

---

Executable: /apps/FDS/6.3.2/bin/fds_impi_intel_linux_64
Licence: Not applicable
## Licence contact: TBD

 Mesh      1 is assigned to MPI Process      0
 Mesh      2 is assigned to MPI Process      1
 OpenMP thread   0 of  15 assigned to MPI process      0 of      1
 OpenMP thread  15 of  15 assigned to MPI process      0 of      1
 OpenMP thread  11 of  15 assigned to MPI process      0 of      1
 OpenMP thread  10 of  15 assigned to MPI process      0 of      1
 OpenMP thread  11 of  15 assigned to MPI process      1 of      1
 OpenMP thread   4 of  15 assigned to MPI process      0 of      1
 OpenMP thread   9 of  15 assigned to MPI process      0 of      1
 OpenMP thread  12 of  15 assigned to MPI process      0 of      1
 OpenMP thread   1 of  15 assigned to MPI process      0 of      1
 OpenMP thread  14 of  15 assigned to MPI process      0 of      1
 OpenMP thread   2 of  15 assigned to MPI process      0 of      1
 OpenMP thread   3 of  15 assigned to MPI process      0 of      1
 OpenMP thread   5 of  15 assigned to MPI process      0 of      1
 OpenMP thread   8 of  15 assigned to MPI process      0 of      1
 OpenMP thread  13 of  15 assigned to MPI process      0 of      1
 OpenMP thread   7 of  15 assigned to MPI process      0 of      1
 OpenMP thread   6 of  15 assigned to MPI process      0 of      1
 OpenMP thread   0 of  15 assigned to MPI process      1 of      1
 OpenMP thread  15 of  15 assigned to MPI process      1 of      1
 OpenMP thread   3 of  15 assigned to MPI process      1 of      1
 OpenMP thread   2 of  15 assigned to MPI process      1 of      1
 OpenMP thread   8 of  15 assigned to MPI process      1 of      1
 OpenMP thread  13 of  15 assigned to MPI process      1 of      1
 OpenMP thread   1 of  15 assigned to MPI process      1 of      1
 OpenMP thread  12 of  15 assigned to MPI process      1 of      1
 OpenMP thread   4 of  15 assigned to MPI process      1 of      1
 OpenMP thread  14 of  15 assigned to MPI process      1 of      1
 OpenMP thread   7 of  15 assigned to MPI process      1 of      1
 OpenMP thread   6 of  15 assigned to MPI process      1 of      1
 OpenMP thread   9 of  15 assigned to MPI process      1 of      1
 OpenMP thread  10 of  15 assigned to MPI process      1 of      1
 OpenMP thread   5 of  15 assigned to MPI process      1 of      1
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : July 28, 2016  14:23:45
 Version          : FDS 6.3.2
 Revision         :
 Revision Date    :
 Compilation Date : Jan 19, 2016  11:04:12

 MPI Enabled; Number of MPI Processes:     2
 OpenMP Enabled; Number of OpenMP Threads:  16

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.0 Update 3 for Linux\* OS

 Job TITLE        : 1
 Job ID string    : 3

 Time Step:      1, Simulation Time:      0.02 s
 Time Step:      2, Simulation Time:      0.04 s
 Time Step:      3, Simulation Time:      0.06 s
 Time Step:      4, Simulation Time:      0.08 s
 Time Step:      5, Simulation Time:      0.10 s
 Time Step:      6, Simulation Time:      0.12 s
 Time Step:      7, Simulation Time:      0.14 s
 Time Step:      8, Simulation Time:      0.16 s
 Time Step:      9, Simulation Time:      0.18 s
 Time Step:     10, Simulation Time:      0.20 s
 Time Step:     20, Simulation Time:      0.40 s
 Time Step:     30, Simulation Time:      0.50 s
 Time Step:     40, Simulation Time:      0.54 s
 Time Step:     50, Simulation Time:      0.58 s
 Time Step:     60, Simulation Time:      0.61 s
 Time Step:     70, Simulation Time:      0.66 s
 Time Step:     80, Simulation Time:      0.74 s
 Time Step:     90, Simulation Time:      0.80 s
 Time Step:    100, Simulation Time:      0.87 s
/apps/bin/fds: line 23: 56098 Killed                  $APP_DIR/$APP_EXE $@

The file 1.fds runs perfectly in another machine. Any idea??

**Comment by mcgratta** [comment]
Not really. Install the latest version of FDS and try that. Even if I could figure out what is wrong, I cannot fix an old version.

**Comment by drjfloyd** [comment]
Fixed.  TAU_V remains the parameter to use since outflow is treated as a VEL input and inflow is now trapped.
