### ISSUE TITLE
Please check spray_burner case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4140]
Jason,
I was scanning the user guide and saw this plot.  Please have a look at this case in light of your recent changes to evap.  Sometimes the dataplot tests do not catch all problems.

![screen shot 2016-08-01 at 3 07 53 pm](https://cloud.githubusercontent.com/assets/4418497/17305740/fc6ebcb2-57f9-11e6-8242-0218f0f0f70d.png)

**Comment by rmcdermo** [comment]
Jason,
Here is another case that looks suspicious.

![screen shot 2016-08-01 at 3 38 36 pm](https://cloud.githubusercontent.com/assets/4418497/17306442/16a46a4c-57fe-11e6-8b9b-86be19487df6.png)

**Comment by mcgratta** [comment]
Looks like bucket_test_2 is like this in the latest User's Guide.

**Comment by drjfloyd** [comment]
I ran the bucket case with the new EVAP turned off and with the release version of 6.5.1.  The results are the same.   

![image](https://cloud.githubusercontent.com/assets/12799217/17306975/c1e7758c-5800-11e6-9d20-28559eb9de4b.png)

**Comment by rmcdermo** [comment]
OK, this got by me in the last release.  I'll work on it.

**Comment by drjfloyd** [comment]
For the spray burner case it looks like I have an error handling the evaporation when the drops are on the floor.

**Comment by mcgratta** [comment]
Kevin will look at the bucket test. Jason will look at the spray_burner.

**Comment by mcgratta** [comment]
For the bucket_test_2 case, I think that the final accumulated water mass is the only measure of success. I'll just change the "expected" result so that we expect 5 kg of water on the floor after 7 s. There's no reason to expect a perfectly linear ramp up to 5.

**Comment by rmcdermo** [comment]
This is bucket_test_2 from 6.4.0.  We should bisect.

![screen shot 2016-08-02 at 8 34 54 am](https://cloud.githubusercontent.com/assets/4418497/17328500/0d2d73bc-588c-11e6-8d8c-299b3335d563.png)

While we are at it, something off with expected results for e_coefficient.

![screen shot 2016-08-02 at 8 30 35 am](https://cloud.githubusercontent.com/assets/4418497/17328522/2d45bf74-588c-11e6-9b04-5802f6406e52.png)

**Comment by rmcdermo** [comment]
Kevin,
Please revert your "expected" results for bucket_test_2.

**Comment by drjfloyd** [comment]
What is wrong with the expected results for e_coefficient?

**Comment by drjfloyd** [comment]
Found an error in the new routine. After fixing it, I now get the results below. The ideal curve is just the fuel mass flow rate times the heat of combustion. The FDS results now show that we match that with a couple of second delay which does not seem unreasonable since that heat can't be realized until the fuel evaporates and then mixes with air.  At the very start not all the liquid immediately flashes and some lands on the cold steel pan. The cold pan limits evaporation for a short bit until it starts to heat up. 

![image](https://cloud.githubusercontent.com/assets/12799217/17328830/c3074aea-588d-11e6-8b3b-fccfd3cb9eeb.png)

**Comment by rmcdermo** [comment]
I did not see the expected results.   I was looking for symbols near the top of the HRR curve.  This is a pretty weak verification.  If we expect some sort of exponential decay this should be part of the metric.  The HRR could do almost anything and end up at zero.

**Comment by drjfloyd** [comment]
The actual effect in FDS depends on the integrated delivered density over each burning grid cell.  We can compute the ideal behavior based on the spray flow rate and the total fire area; however: there will be a delay for the spray to hit the fire, not all of the spray will hit the fire, and not all burning cells will see the same integrated delivered density. Better time resolution of the ideal solution results in the chart below. For an example in the User's Guide, I think this case demonstrates what it needs to. If you want a case that allows us to test that the decay is correct, I think we would need to construct a new case where we do something like place a grid of nozzles directly over the fire with 0 spray angle (each nozzle just injects a downward stream).

![image](https://cloud.githubusercontent.com/assets/12799217/17329888/a200ad14-5892-11e6-85fa-23fbf1a64473.png)

**Comment by rmcdermo** [comment]
I think adding Series 1 as the "expected" behavior with a sentence discussing the time delay as you have above would be a huge improvement.

**Comment by drjfloyd** [comment]
I will do that.

**Comment by drjfloyd** [comment]
Added more points for e_coefficient plus a sentence discussing the expected behavior to the guide.

https://github.com/firemodels/fds-smv/commit/4fe6516a10154197a78afb3d7e15bb9e5377a9d1

**Comment by mcgratta** [comment]
Commit #4191 fixes the problem with bucket_test_2. It was related to the time step iteration within the move particle routine.

**Comment by mcgratta** [comment]
Everything looks OK in the 6.5.2 release.
