### ISSUE TITLE
Numerical instability with open DUCT

### ISSUE THREAD

**Issue by chulann** [firemodels/fds#4152]
Test case is a 10m long corridor, VENT at either end. One is an open DUCT, the other is a DUCT with a fan, set to activate at 120 seconds, MAX_FLOW of 6 m^3/s, MAX_PRESSURE of 50 Pa and a TAU_FAN of -10 (Added as code below as I can't attach a .fds)

I get a numerical instability about 4 seconds after the fan activates.

If I increase the DT_HVAC to 1, I get a numerical instability after 1 second. If I reduce it to 0.1 (or remove it), the case seems to run fine (or, at least is currently running fine).

Incidentally, this problem only arose after I changed my "inlet" duct from forced to natural.

On the "full" models where I use this, increasing the length of the inlet duct to 4m brings stability, but not on my small models.

This may be related to issue 3443.

```
&HEAD CHID='hvactest_1md_npz_ls', TITLE='Testing of HVAC only - Short corridor, 1m long inlet duct, pressure zones not explicitly specified' / 

&TIME T_END=900.0 /
&MISC DT_HVAC=0.5 /

&MESH ID='Corridor', IJK=100,15,25, XB=-5.0,5.0,0.0,1.5,0.0,2.5 /

&ZONE ID='corridor' /

&HVAC ID='Duct_MainInlet',      TYPE_ID='DUCT', AREA=1.0, LOSS=1.0,1.0, PERIMETER=4.0, NODE_ID='Node_MainInlet_Ambient','Node_MainInlet_Corridor', ROUGHNESS=0.001, LENGTH=1.0 / 
&HVAC ID='Node_MainInlet_Corridor', TYPE_ID='NODE', DUCT_ID='Duct_MainInlet', VENT_ID='VT_MainInlet_Corridor' /
&HVAC ID='Node_MainInlet_Ambient',  TYPE_ID='NODE', DUCT_ID='Duct_MainInlet', AMBIENT=.TRUE., XYZ=-6.0,0.8,3.5 /
&VENT ID='VT_MainInlet_Corridor',   SURF_ID='HVAC', XB=-5.0,-5.0,0.3,1.3,1.4,2.4 / 

&HVAC ID='Duct_MainExtract_Fan',      TYPE_ID='DUCT', AREA=1.0, LOSS=1.0,1.0, PERIMETER=4.0, FAN_ID='Fan_MainExtract', NODE_ID='Node_MainExtract_Corridor','Node_MainExtract_Ambient', ROUGHNESS=0.001, DEVC_ID='outlet timer', LENGTH=2.0 /
&HVAC ID='Node_MainExtract_Corridor', TYPE_ID='NODE', DUCT_ID='Duct_MainExtract_Fan', VENT_ID='VT_MainExtract_Corridor' /
&HVAC ID='Node_MainExtract_Ambient',  TYPE_ID='NODE', DUCT_ID='Duct_MainExtract_Fan', AMBIENT=.TRUE., XYZ=6.0,0.8,3.5 /
&HVAC ID='Fan_MainExtract',           TYPE_ID='FAN',  MAX_FLOW=6.0, MAX_PRESSURE=50.0, TAU_FAN=-10 /
&VENT ID='VT_MainExtract_Corridor',   SURF_ID='HVAC', XB=5.0,5.0,0.3,1.3,1.4,2.4 / 

&DEVC ID='outlet timer', XYZ=0.0,0.0,0.0, QUANTITY='TIME', SETPOINT=120.0, INITIAL_STATE=.FALSE. / 

&TAIL /
```

**Comment by bmralph** [comment]
What version of the code are you using?

I've added in a pressure zone, removed DT_HVAC and run your input file on the latest release and yet to get a NI up to 140 seconds (still running).

**Comment by chulann** [comment]
I have done most of the testing with 6.4.0 but I have also tried one with 6.5.1 and got the same result.

As I mentioned in my initial comments, if I remove DT_HVAC, the case runs successfully. Also, note that I already had a pressure zone.

**Comment by bmralph** [comment]
DT_HVAC should only be specified if you're having stability problems initially using default parameters (default: time step for HVAC = FDS time step).

Confused as to why you want to vary DT_HVAC if your case is running successfully with default values?

**Comment by drjfloyd** [comment]
@chulann thanks for opening an issue. 
@bmralph this case has a longer history on the discussion forum: https://groups.google.com/forum/?fromgroups=&nomobile=true#!topic/fds-smv/yl1chfQR4gQ

**Comment by bmralph** [comment]
Thanks for heads up Jason. I'll take a look at the discussion board.

**Comment by mcgratta** [comment]
Has this issue been solved?

**Comment by drjfloyd** [comment]
If I set HVAC_LOCAL_PRESSURE = .FALSE. (new in 6.7.0) the case seems to run OK. I set the fan DEVC to 20 s instead of 120 and It is now over 10 s beyond fan activation. I put in a velocity slice along the centerline and I don't see any signs that there are instabilities developing.  I think this issue is solved.
