### ISSUE TITLE
Altered small droplet weighting in droplet_distributions

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4164]
Jason,
As you know, I've been working on droplet distribution stuff lately.  In going through the verification cases, I recently noticed a blip in the weighting for the Sprinklers_and_Sprays/droplet_distributions.fds case.  Below you will see the current and past plots for Rosin-Rammler-Lognormal, but other distributions have similar problems.  After a bisect, something seems to have changed in the code for the new implicit solver:

9d670d70eaa0a4a7101dd310fd33445b3e74ea3c is the first bad commit
commit 9d670d70eaa0a4a7101dd310fd33445b3e74ea3c
Author: jfloyd jfloyd@jensenhughes.com
Date:   Wed Jul 27 13:24:14 2016 -0400

```
FDS Source: New implicit solver for evaporation behind EVAP_2
```

Keep in mind that the init for these cases is the VOLUME_PARTICLE_INSERT, which I have not touched.

Here is the plot just after your commit above:

![screen shot 2016-08-08 at 8 39 30 am](https://cloud.githubusercontent.com/assets/4418497/17480003/bec194da-5d43-11e6-9d49-3873c70d453e.png)

Here is the plot from v6.5.0 user guide:

![screen shot 2016-08-08 at 8 40 00 am](https://cloud.githubusercontent.com/assets/4418497/17480007/c48d8fc2-5d43-11e6-8e3f-04fb21b8bcf5.png)

**Comment by rmcdermo** [comment]
I speculated that the problem might be you are getting some evaporation of the drops due to the new implicit scheme.  But setting HUMIDITY=100 did not help.

**Comment by drjfloyd** [comment]
I'll see what I can figure out.

**Comment by drjfloyd** [comment]
Setting RADIATION=.FALSE. fixes it.  That limits where my error can be. Hopefully shouldn't take long to fix.

**Comment by rmcdermo** [comment]
Also simply not going into mass and energy transfer works.  I added a logical for debugging this more easily.

**Comment by drjfloyd** [comment]
Should be fixed. Hopefully doesn't break something else in tonight's Firebot.

**Comment by rmcdermo** [comment]
The droplet_distributions case looks much better.  Thanks!

**Comment by rmcdermo** [comment]
This seems to be fixed.  Closing.
