### ISSUE TITLE
&MISC RESTART=.TRUE./  

### ISSUE THREAD

**Issue by dy944533118** [firemodels/fds#4187]
My program has the function of automatically save when the time reaches 300 seconds. &DUMP DT_RESTART=300.0/ The examples shut down due to power outages at the time of 370 seconds and the restart files have been generated. So I want to restart it, &MISC RESTART=.TRUE./  but I cannot recalculate from 300 seconds. What's the problem? Thank you very much.
![qq 20160811222828](https://cloud.githubusercontent.com/assets/19992906/17593209/aeef3824-6017-11e6-8fd4-ad108688be7d.png)
![qq 20160811222852](https://cloud.githubusercontent.com/assets/19992906/17593215/b571b14a-6017-11e6-93ce-2e068975b176.png)
[2.zip](https://github.com/firemodels/fds-smv/files/413507/2.zip)

**Comment by dy944533118** [comment]
The code can not run, please have a try .

**Comment by dy944533118** [comment]
I don't know what is the problem of my code, please teach me.Thank you very much .

**Comment by mcgratta** [comment]
I do not understand what you are asking me to do. Does the attached input file run with the latest version of FDS?

**Comment by dy944533118** [comment]
The version of FDS I used is latest FDS6.5.1. I want to ask you :  Whether the code in the attached picture(input file) is wrong or not? It can not achieve the function of  automatical save. The program has run  370  seconds, but I can not restart it from the 300 seconds.

**Comment by mcgratta** [comment]
The restart files were saved at 300 s. If you restart the calculation, the simulation will proceed from 300 s. What exactly happens when you try to restart?

**Comment by dy944533118** [comment]
It can't restart. It will broke down directly. And there is not any reminder.

**Comment by dy944533118** [comment]
That is to say,my settings are no problem, but I can not restart the file from 300 seconds. Is this the BUG of FDS?

**Comment by mcgratta** [comment]
I took your input file and ran it with `T_END=1.1` and `DT_RESTART=1`. I then reran the case with `T_END=2.0` and `RESTART=.TRUE.`  The case seemed to run fine. Can you try doing this and tell me if the job restarts properly.

**Comment by mcgratta** [comment]
Closing due to lack of response.
