### ISSUE TITLE
A problem about VENT

### ISSUE THREAD

**Issue by dy944533118** [firemodels/fds#4196]
I build a vent in a thin obstruction(wall) which is inside of my mesh, but the file can not run. When I move the vent to the surface of mesh, it can run. I know that the surface of mesh is also solid wall by default. So I want to ask what is the reason. Why the first case files can't run?

**Comment by mcgratta** [comment]
You cannot put a VENT on a thin obstruction if the VENT has a velocity associated with it. The obstruction must be at least one cell thick.

**Comment by dy944533118** [comment]
Yes, my obstruction is two cell thick. My speech is wrong just now.

**Comment by dy944533118** [comment]
So what is the reason?

**Comment by mcgratta** [comment]
Post a simple file that demonstrates the problem.

**Comment by dy944533118** [comment]
[1.zip](https://github.com/firemodels/fds-smv/files/416682/1.zip)

**Comment by dy944533118** [comment]
This file can run. You can try to move the vent to any one OBST, then it will not run.

**Comment by mcgratta** [comment]
I cannot debug such a large case. Reduce this input file so that it is 10-20 lines and still shows the problem.

**Comment by mcgratta** [comment]
No response, closing
