### ISSUE TITLE
Verification Issues and Suggestions

### ISSUE THREAD

**Issue by tgob** [firemodels/fds#4198]
Verification Issues

I have worked through the minimal Installation Testing at Appendix B of the NIST Special Publication 1018-2 6th Ed. Fire Dynamics Simulator Technical Reference Guide Volume 2: Verification (the Verification Guide) on a new FDS 6.5.0 OpenMPI install.

The installation is on a Linux cluster with Intel processors and Infiniband.  FDS and OpenMPI were compiled with the gnu compiler suite.

The FDS models in Table B.1: FDS Installation Test Suite were run individually (not using a bash script or scheduler).  While I have a licensed copy of MatLab I figure that many of your users don’t (this makes the Intel Compiler suite look cheap). I would prefer to be able to evaluate the  verification cases for FDS using OS bundled software or typical spreadsheet packages with graph capability (Excel, LibreOffice, …).

The following issues were noted.
1.  Please consider rearrange the Summary of Verification Results at Appendix A into alphabetical order.   Maybe you could go to landscape format and increase the font size to facilitate reading without the aid of a magnifying glass.
2.  Please incorporate the test parameters and units in Appendix A.  A number of the tests have multiple verification Expected Values that cannot be specifically identified without this information.  For example:
   
   Case Name   Parameter   Units   Expected    Predicted   …
                       Value       Value
   
   test_case   HRR     kW  2.00 E3 2.20 E3 …
3.  Please include the simulation time at which test parameters should be  evaluated in Appendix A, or state whether this should be the maximum/minimum parameter value, or at the end of the simulation.  Note that Radiation, radiation_shield.fds appears to be evaluated after approximately 400 s while the simulation runs to 500 s.
4.  Appendix A describes that Predicted Values have been calculated by FDS.  It would be useful to understand how the Expected Values have been derived with a brief description in the body of the Verification Guide associated with each test.
5.  Please consider incorporating a copy of the relevant Verification Results from Appendix A into Appendix B, essentially making Appendix B a stand alone minimal test suite.
6.  When running the following multiple mesh verification models under OpenMPI with multiple processes the models failed to run due to fork warnings and segmentation errors related to invalid memory references at the beginning of the simulation.   The errors were all repeatable and consistent depending on the number of allocated processes (-np x).

Pressure_Effects, isentropic2.fds

Pressure_Solver, duct_flow.fds, and

Pyrolysis, shrink_swell

With some process allocations the models would run to completion using multiple nodes.  The models all ran with a single process (-np 1).

I suspect this is either a compiler or openmpi issue.  I am investigating further.
1.  Refer to Appendix B, Table B1, Fires.

There is no spray_burner_device.csv file generated from the Fires, spray_burner.fds model with FDS6.5.0.

The metric is clearly the total heat released over the 90 s simulation time output in spray_burner_device_hrr.csv.

This can be calculated from the spray_burner_device_hrr.csv  file using the trapezoidal rule for numerical integration (appropriate for piece-wise linear functions) as:

```
Predicted Value = ∑(i=0 to 89) ∆t.((T(i+1) + Ti))/2

    which simplifies with ∆t = 1 to:

           = ∑(i=0 to 90) Ti   -  (T90 +T0)/2
```
1.  There are no Summary of Verification Results in Appendix A for the following Appendix B verification models:

Sprinklers_and _Sprays, particle_drag_U50_N16.fds

HVAC, ashrae7_table.fds
1.  Refer to Appendix B, Table B1, Species

The input files for both of the Species models should be .fds, not .csv.
10. Refer to Appendix B, Table B1, Species, reactionrate_arrhenius_2order_1step.fds

The GitHub model, reactionrate_arrhenius_2order_1step.fds,  has an FDS syntax error.  FDS reports: “FDS not properly set up.  Problem with INIT number 1…’.  The problem is that line 18, INIT number 1 is missing an end of line terminator (/).  The model will not run without this.

While this is easily fixed it does lead to the question, how could the model have been run to produce the validation in Appendix A?
1. Refer to Appendix B, Table B1, Sprinklers_and_Sprays, water_evaporation_1.fds

This was the only test model with an Appendix A listing that I could not reconcile the Predicted and Expected values.

There are two listings for this model in Appendix A with an expected value of 1.00e-2.  There is only one DEVICE parameter in the water_evaporation_1_device.csv file that matches the expected value (dens in kg/m3 after 10 seconds).  I figure that this is a double up unless the second parameter is based on post-model processing of the H2O mass fraction.

The numbers work out fine.

At the start of the simulation we have 1 m3 of air with a density of about 0.746 kg/m3 at 200 C.  The final mass fraction of H2O as water vapour is 0.0132 kg/kg.  The model is run at constant volume.  So the actual mass of water vapour after 10 seconds is:

```
0.746 kg/m3 * 1 m3 * 0.0133 kg/kg = 0.0099 kg
```

Please advise if this is simply a double-up in the Appendix A listing, or whether you are post-processing the …device.csv H2O mass fraction at 10 seconds.

Ideally Predicted Values would be directly output in the models …device.csv file.    
1. Suggestion.  I know there are a lot of FDS verification models but it would be extremely helpful if the specific listings in Appendix A were incorporated in the relevant model headers.

**Comment by mcgratta** [comment]
Some of these are just typos, others could require some time to fix. Some are just the result of how the various scripts run. Let's prioritize -- is there a case that fails to run or has the wrong output, let's deal with those first. Which cases do not run?

**Comment by tgob** [comment]
Thanks for the prompt reply Kevin.  I agree that most of this is relatively minor stuff (if not somewhat time consuming).  These suggestions should make it easier for users to validate FDS installation.

I see that my original format and numbering has auto-screwed-up in the copy and paste into GitHub.  Sorry about that.
1.  This is a local installation issue (probably with the gnu compiler).  I am working on this.

My suggested priority order is:
1.  Only one model doesn’t run:  Species, reactionrate_arrhenius_2order_1step.fds.

This is clearly due to an EOL typo. on Line 18, &INIT.  An easy fix.
1.  Publish the Predicted, Type of Error, and Error Tolerance for Appendix B models:

Sprinklers_and _Sprays, particle_drag_U50_N16.fds
HVAC, ashrae7_table.fds

These test cases can’t be used for validation without the Appendix A information.

3, 7, 11.  Clarify the post-processing/output for Expected Values from:

Sprinklers_and_Sprays, water_evaporation_1.fds
Fires, spray_burner.fds
Radiation, radiation_shield.fds  (a maximum or timed measurement?)

2, 3, 5.  Provide Test Parameters, Units and Time for Appendix B.  

The remaining issues are very much suggestions for your consideration.

**Comment by mcgratta** [comment]
Fixed `reactionrate_arrhenius_2order_1step.fds`

Added `particle_drag_U50_N16` and `ashrae7_table` to Appendix A verification output table.

Added Reference column to Appendix B table showing where in the Guides the verification cases are discussed.

**Comment by mcgratta** [comment]
BTW, can you compile the Verification Guide?

**Comment by tgob** [comment]
Thank you for attending to these issues Kevin.

I haven't tried to compile the Verification Guide yet (although I have spent some time looking through the associated make files and scripts).

I am experimenting with compiler options (and compilers) to overcome the initialization (early) SIGSEGV errors associated with fork() for some combinations of multiple processes with the multi-mesh Appendix B verification models.

As an aside, I should have the Scaling Studies completed on the NeSI platform this week.

**Comment by mcgratta** [comment]
Take a look at the most recent release of FDS-SMV (6.5.2). I added a column to the table in the Appendix of the Verification Guide that provides a link to the section in the V Guide or the User's Guide where the case is discussed. It would be very difficult to include a comprehensive description of the cases within this table. I'd rather provide a link and a more thorough discussion elsewhere. Let me know if the link works for you -- it's a new trick we're using to link multiple guides together.

**Comment by tgob** [comment]
Thank you Kevin.  Yes this certainly helped.

I have attached a verification report that has the Table I am using for the Appendix B verification suite.   It is copied it directly from a Microsoft Excel spreadsheet.  I haven't automated parsing of the various .csv output metrics - maybe a task for a future rainy day?

My investigations into the issues I have experienced with Infiniband are continuing.  The NeSI Pan cluster has similar problems.  In the interim I have reverted to an Ethernet install with FDS 6.5.2.  This works fine with OpenMPI compiled under gcc and with the precompiled Intel FDS binaries.

t.

**Comment by mcgratta** [comment]
I don't see an attachment with your previous post.

**Comment by tgob** [comment]
That's weird.  It was there.  I'll try again.

t.

**Comment by mcgratta** [comment]
[FDS_Verification_Guide.pdf](https://github.com/firemodels/fds/files/466049/FDS_Verification_Guide.pdf)
[FDS_User_Guide.pdf](https://github.com/firemodels/fds/files/466050/FDS_User_Guide.pdf)

Take a look at the appendices of the FDS Verification Guide. I have addressed most of your comments, but let me know if there are others. Download both documents onto your computer and put them in the same folder because the V Guide has links to the U Guide.

**Comment by tgob** [comment]
Excellent Kevin.  For format consistency you might like to rotate Verification Guide Table B1 180°.

Please close the issue.

t.

**Comment by mcgratta** [comment]
I rotated the table in a consistent way. Thanks for your help.

**Comment by Pkwahou** [comment]
hello,
I'm now proceed to the testing of FDS installation. The tested release is FDS 6.6.0 for Windows 64-bit.
I have compared the predicted metric to the value in the Appendix A of the verification guide.

I observe a difference between the expected Metric and the predicted metric for folowing tests cases:
-spray_burner
-reactionrate_arrhenius_2order_1step (O2, C3H8, CO2, H2O)
-particle_drag_U50_N16

is this are due to the changes in the latest release?

Patrick.

**Comment by mcgratta** [comment]
Is there a relatively large difference? The verification cases for release are run on a linux machine, which might produce some difference in results from Windows due to subtle differences in precision, rounding, etc.

**Comment by Pkwahou** [comment]
Hell,
Thank you for your answer.
The difference is not too much.



Expected Metric

Predicted Metric

reactionrate_arrhenius_2order_1step_O2

1.30E-02

8.73E-02

reactionrate_arrhenius_2order_1step_C3H8

3.36E-03

2.37E-02

reactionrate_arrhenius_2order_1step_CO2

1.70E-01

1.09E-01

reactionrate_arrhenius_2order_1step_H2O

9.27E-02

5.93E-02

**Comment by mcgratta** [comment]
These are the results from calculations I ran last night with `FDS6.6.0-1849-gf1aae20-master`. I ran these on our linux cluster. What exact version of FDS are you running?

|Dataplot Line   Number | Verification Group | Case Name | Type of Metric | Expected Quantity | Expected Value | Predicted Quantity | Predicted Value | Dependent Variable | Type of Error | Error | Error Tolerance | Within Specified Error Tolerance | Plot Filename|
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|265 | Species | reactionrate_arrhenius_2order_1step | end | O2 | 0.013028 | O2 | 0.013233 | Mass Fraction | Absolute Error | 2.05E-04 | 1.00E-03 | Yes | FDS_Verification_Guide/SCRIPT_FIGURES/reactionrate_arrhenius_2order_1step|
|265 | Species | reactionrate_arrhenius_2order_1step | end | C3H8 | 0.0033577 | C3H8 | 0.0032891 | Mass Fraction | Absolute Error | 6.86E-05 | 1.00E-03 | Yes | FDS_Verification_Guide/SCRIPT_FIGURES/reactionrate_arrhenius_2order_1step|
|265 | Species | reactionrate_arrhenius_2order_1step | end | CO2 | 0.16993 | CO2 | 0.1698 | Mass Fraction | Absolute Error | 1.30E-04 | 1.00E-03 | Yes | FDS_Verification_Guide/SCRIPT_FIGURES/reactionrate_arrhenius_2order_1step|
|265 | Species | reactionrate_arrhenius_2order_1step | end | H2O | 0.092687 | H2O | 0.092677 | Mass Fraction | Absolute Error | 9.99E-06 | 1.00E-03 | Yes | FDS_Verification_Guide/SCRIPT_FIGURES/reactionrate_arrhenius_2order_1step|

**Comment by Pkwahou** [comment]
The version of FDS is FDS 6.6.0 for Windows 64-bit

**Comment by mcgratta** [comment]
I just confirmed that the latest FDS source code runs the reactionrate verification case properly. We made some changes to defaults in the combustion routine since the last release. Always run verification cases using the latest build and the latest verification input files in the FDS repository.
