### ISSUE TITLE
Smokeview not working for models with more than 4 million cells

### ISSUE THREAD

**Issue by michael-j-k** [firemodels/fds#4199]
Hello,

When I am trying to use smokeview 6.3.x (on windows) to visualize the results from a model with 4 million cells, smokeview hangs during the initial load. Attached find a simplified input file to generate the .smv that exemplifies the problem. However, and as Glenn suggested, moving the .smv file to another directory and loading it solves the loading problem (the geometry will show), but with no results. 

Thank you for your help.

MJ

[SV_Failure_32Meshes.txt](https://github.com/firemodels/fds-smv/files/416897/SV_Failure_32Meshes.txt)

**Comment by gforney** [comment]
its  working for me with windows smokeview 6.3.10 downloaded from github.  exactly which version of smokview are you using.  how much memory does your computer have ? exactly how is it failing - what is the last message that smokeview displays in console window?

![test_0040](https://cloud.githubusercontent.com/assets/12403014/17712166/d9b94d48-63c2-11e6-801a-1c23209d978d.png)

**Comment by michael-j-k** [comment]
Hi Glenn,

Thanks for looking into this, it is much appreciated. 

I downloaded the latest version of SV to Server #1 and the test file loads! Not sure why it didn’t before (embarrassing). I also tested SV 6.3.6 on this server #1, it also works! But Server #2 still does not work with same test file, see screenshots below.

Here are answers to your questions:

Smokeview: Version 6.3.10, July 13 2016, both servers, see screenshot below:

DELL Server #1: Dual Xeon E5, 2GHz, 64 GB ECC RAM, SSD hardisk, NVIDIA Quadro 600 on Windows 7 Pro, 64 bit

DELL Server #2: Quad Xeon E5, 2.5GHZ, 128 GB ECC RAM, RAID, AMD G200eR on Windows Server 2008 Enterprise 64 bit

 Last message displayed by SV on Server #2 (Win Srv 2008): “clipping off”, see Screenshot below:

And the window that opens displays: “not responding” (waiting)

Could it be due to the differences in Graphics Cards i.e., Nvidia vs AMD? The Nvidia is much higher powered, designed for ACAD and similar (memory 1 GB), whereas the server #2 cards memory spec is 32 MB (only)…? 

The Nvidia based server works with the latest SV, which makes me very happy!! We can close the ticket if you are ok with it.

 Thanks for your help.

Regards,

Michael

**Comment by gforney** [comment]
If it is the  graphics card it would likely be because of the version of opengl supported.  type 
smokeview -ini
in a command shell on both servers.  then look at the bottom of the smokview.ini file that is created. and report back the Graphics environment that is output  My guess is you may be right - 32MB is not much memory for a graphics card.

This is what shows up on my PC (I took out the "pound" characters)

 Graphics Environment

---

 OpenGL Version: 4.4.0
       Red bits:8
     Green bits:8
      Blue bits:8
     Alpha bits:0
     Depth bits:24

I didn't see the files you attached

**Comment by michael-j-k** [comment]
Here are the configuration settings:

 Server #1, w/ Nvidia 600:

# Graphics Environment

# OpenGL Version: 4.4.0

# Red bits:8

# Green bits:8

# Blue bits:8

# Alpha bits:0

# Depth bits:24

Typing 'smokeview -ini' on Server #2, w/ AMD G200eR:
"Smokeview is running on a system using OpenGL 1.1.0
 Open GL 2.0 or later is required to use GPU..."

the configuration file for SV on Server #2:

# Graphics Environment

# OpenGL Version: 1.1.0

# Red bits:5

# Green bits:6

# Blue bits:5

# Alpha bits:0

# Depth bits:32

I attached the screenshots again for Server #2 (terminal, smokeview window, OpenGL message).

It is the OpenGL!
![screenshot_server2_svopengl](https://cloud.githubusercontent.com/assets/3195123/17714815/44d4c86c-63b6-11e6-8f20-edd117f6397a.jpg)

However, it still seems to work for models with 2 million cells. Would you expect that?

Thank you.

MJ
![screenshot_server2_cmd](https://cloud.githubusercontent.com/assets/3195123/17714516/0186ed66-63b5-11e6-9dbd-bc0a89e3751a.jpg)
![screenshot_server2_sv](https://cloud.githubusercontent.com/assets/3195123/17714517/018c5512-63b5-11e6-843f-f93803457557.jpg)

**Comment by michael-j-k** [comment]
The smokeview issue was resolved and it will be closed.
