### ISSUE TITLE
ERROR: Problem with SURF number  1

### ISSUE THREAD

**Issue by sanmita** [firemodels/fds#4201]
Am

![file](https://cloud.githubusercontent.com/assets/21056662/17695206/1664d200-63da-11e6-8cfb-952daa8c7a66.JPG)

 trying to run a co simulation. the file is created in FDS6 and am running with FDS5. am getting the following error. 
ERROR: Problem with SURF number  1
i have attached the file. Can suggest a solution. Thanks

**Comment by drjfloyd** [comment]
We would recommend that unless there is some specific need for you to use FDS 5 that you use the current release.

FDS 6 input files are not backwards compatible with FDS 5. Consult the FDS 5 documentation for valid inputs for &SURF.

**Comment by sanmita** [comment]
Thanks for your reply . i experienced that while running using FDS6 it takes longer time to finish . That's the reason i tried to run using FDS5. Anyway thanks for your reply.
