### ISSUE TITLE
Parabolic Vent Profile Incorrect with Multiple Meshes

### ISSUE THREAD

**Issue by dstacy121** [firemodels/fds#4209]
I know “parabolic” is not the best approach to model wind, but I ran a model with this profile as a comparison to “atmospheric” and “top hat”.  I had split my domain into 8 meshes (z direction).  Should the parabolic profile be applying a condition to each of the meshes?  The wind “vent” spans the interior y-min (right side of figure), yet the velocity profile appears broken up.  I know if I merge all of the meshed on that side into 1 mesh, this would not be the case.  
[parabolic_issue.txt](https://github.com/firemodels/fds-smv/files/422745/parabolic_issue.txt)

![parabolic_ss](https://cloud.githubusercontent.com/assets/21082029/17739254/72cec220-6462-11e6-9846-6a93a484e169.jpg)

**Comment by mcgratta** [comment]
FDS breaks up the large `VENT` into 8. I'll see if there's an easy way to make it recognize the exterior dimensions of the actual `VENT`.

**Comment by mcgratta** [comment]
Obviously, the meantime, don't use `PARABOLIC` profile in this way.

**Comment by dstacy121** [comment]
Understood, I know it’s not the best profile for a wind anyways, was just fooling around and realized this didn’t seem right.  I can make a single mesh over there in the meantime.

At SFPE this year I am going to be showing how the different applications, or misapplications of wind profiles affect conditions in a tenability analysis.

David Stacy | Associate

JENSEN HUGHES
Advancing the Science of Safety

5520 Dillard Dr | Suite 130 | Cary, NC 27518
O: +1 919-424-3858 | C: +1 919-356-6689
dstacy@jensenhughes.commailto:dstacy@jensenhughes.com | www.jensenhughes.comhttp://www.jensenhughes.com/

**Comment by mcgratta** [comment]
I fixed this problem. Commit #4293. There's also a test case called parabolic_profile. Should be out in the next release.
