### ISSUE TITLE
Case write-ups needed for Verification Guide and User's Guide

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4218]
In cleaning up the Verification and User's Guide examples, I found some cases that have not been documented. I added all to the V and U Guides with the plots, but little or no discussion. I think the originators are:

Randy -- ht3d_slab, bound_test, helium_air_jet_floor, mwtest_cfl, tmp_lower_limit

Jason -- ramp_chi_r (User's Guide) I did not add anything for this case. I assume it should go where this parameter is discussed.

Craig -- reactionrate_lumped_two_air, reactionrate_series_reaction

If the cases are not ready yet, comment them out of the Guide and "s" them in the FDS_verification_dataplot_input sheet. They all look OK, so just add something to what I have already added.

**Comment by mcgratta** [comment]
One more 

Jason -- mass_heat_wall_device_test

**Comment by cweinschenk** [comment]
@mcgratta my updated discussion is added in #4222

**Comment by mcgratta** [comment]
Craig, thanks.

**Comment by rmcdermo** [comment]
I think I have the cases in my list done.  I am not yet committing to changing the way we do fast chemistry.  I'm going to put this on Taylor Myer's plate if gets here.

mass_heat_wall_device_test might be mine.  I'll take a look.

**Comment by drjfloyd** [comment]
added ramp_chi_r to User's Guide

**Comment by rmcdermo** [comment]
OK, I think these are fixed.  I'll close.
