### ISSUE TITLE
Atmospheric Profile Origin of 0.0 results in erorr as well

### ISSUE THREAD

**Issue by dstacy121** [firemodels/fds#4219]
I am analyzing changes in the atmospheric profile origin, besides that of the default 10 meters.  When I assign it to 0.0, I get an access violation run error.  If I assign it 0.1, the model runs.  The User Manual Section 9.5 states "Be careful not to apply an atmospheric velocity proﬁle below GROUND_LEVEL or FDS will stop with an error."   It appears that it needs to be **above** ground level?

**Comment by drjfloyd** [comment]
The atmospheric profile is u = u0 \* ((z-ground level)/z0)^P where z- is the height above ground level.  If z0=0, then you are dividing by zero which will give an error.  The user's manual statement is referring to the numerator as taking a negative number to positive real exponent does not always result in a real number.

I'll update the guide to make this clearer.

**Comment by drjfloyd** [comment]
Updated guide: https://github.com/firemodels/fds-smv/commit/4bd53a878f5b9760d35b5cae243c04551df4570b
