### ISSUE TITLE
Frame size is zero in Slice File

### ISSUE THREAD

**Issue by KateLM** [firemodels/fds#4241]
Hi All, 
I'm having trouble loading slice files in Smokeview. When I run the simulation and load the slice file in SMV it says the frame size is zero in slice file. I'm not sure what is going on here. The code is below (minus OBST's as there are far too many to post here). Please help! Thanks in advance

&HEAD CHID='scrubberHF',TITLE='Scrubber Tower Gas Release'/

&VENT XB=0,180,0,0,0,12.83, SURF_ID='INERT'/
&VENT XB=0,180,-28,-28,0,12.83, SURF_ID='INERT'/
&VENT XB=0,0,0,-28,0,12.83, SURF_ID='INERT'/
&VENT XB=180,180,0,-28,0,12.83, SURF_ID='INERT'/
&VENT XB=0,180,0,-28,0,0, SURF_ID='INERT'/
&VENT XB=0,180,0,-28,12.83,12.83, SURF_ID='INERT'/

&MESH ID='mesh 1', IJK=100,100,40, XB=0,36,0,-28,0,12.83, MPI_PROCESS=0 /
&MESH ID='mesh 2', IJK=100,200,80, XB=36,45,0,-28,0,12.83, MPI_PROCESS=1 /
&MESH ID='mesh 3', IJK=100,200,80, XB=45,54,0,-28,0,12.83, MPI_PROCESS=2 /
&MESH ID='mesh 4', IJK=100,200,80, XB=54,63,0,-28,0,12.83, MPI_PROCESS=3 /
&MESH ID='mesh 5', IJK=100,200,80, XB=63,72,0,-28,0,12.83, MPI_PROCESS=4 /
&MESH ID='mesh 6', IJK=100,100,40, XB=72,180,0,-28,0,12.83, MPI_PROCESS=4 /

&TIME T_END=70560. /
&MISC TMPA=25. /
&MISC HUMIDITY=40. /

&SPEC ID='HYDROFLUORIC ACID', LUMPED_COMPONENT_ONLY=.TRUE./
&SPEC ID='WATER VAPOUR', LUMPED_COMPONENT_ONLY=.TRUE./

&SPEC ID='FUMES', 
SPEC_ID(1)='HYDROFLUORIC ACID', VOLUME_FRACTION(1)=0.7,
SPEC_ID(2)='WATER VAPOUR', VOLUME_FRACTION(2)=0.3 /

&SURF ID='SUPPLY', SPEC_ID='FUMES', MASS_FLUX_TOTAL=0.2104, RAMP_V='SUPPLY RAMP' /
&RAMP ID='SUPPLY RAMP', T=0., F=1.0/
&RAMP ID='SUPPLY RAMP', T=3600., F=0.95/
&RAMP ID='SUPPLY RAMP', T=7200., F=0.896/
&RAMP ID='SUPPLY RAMP', T=10800., F=0.843/
&RAMP ID='SUPPLY RAMP', T=14400., F=0.79/
&RAMP ID='SUPPLY RAMP', T=18000., F=0.737/
&RAMP ID='SUPPLY RAMP', T=21600., F=0.685/
&RAMP ID='SUPPLY RAMP', T=25200., F=0.634/
&RAMP ID='SUPPLY RAMP', T=28800., F=0.582/
&RAMP ID='SUPPLY RAMP', T=32400., F=0.531/
&RAMP ID='SUPPLY RAMP', T=36000., F=0.48/
&RAMP ID='SUPPLY RAMP', T=54000., F=0.229/
&RAMP ID='SUPPLY RAMP', T=70560., F=0.0/

&VENT XB= 44.3724, 44.4224, -4.394,-3.027, 0.801, 0.801, SURF_ID='SUPPLY', COLOR='RED' /
&VENT XB= 44.925, 44.975, -4.394,-3.027, 0.801, 0.801, SURF_ID='SUPPLY', COLOR='RED' /
&VENT XB= 45.475, 45.525, -4.394,-3.027, 0.801, 0.801, SURF_ID='SUPPLY', COLOR='RED' /
&VENT XB= 46.025, 46.075, -4.394,-3.027, 0.801, 0.801, SURF_ID='SUPPLY', COLOR='RED' /

&PLOT3D_SPEC_ID = 'FUMES'
&SLCF XB=0,180,0,-28,0,12.83, QUANTITY='VELOCITY', VECTOR=.TRUE./

&SLCF XB=0,180,0,-28,0,12.83, QUANTITY='MASS FRACTION', SPEC_ID = 'FUMES'/

&DUMP PLOT3D_QUANTITY(1:5)='VOLUME FRACTION','U-VELOCITY','V-VELOCITY','W-VELOCITY','HRRPUV', PLOT3D_SPEC_ID = 'FUMES', DT_PL3D = 1, DT_SL3D = 1/ 

&TAIL/

**Comment by gforney** [comment]
you put ymax before ymin in your &SLCF namelists.  Put -28 before 0 as in

&SLCF XB=0,180,-28,0,0,12.83

and it should work.  

Note, I had to add blockages for the vents to attach to .   If anyone runs the case, use the file I attached.
[test.fds.txt](https://github.com/firemodels/fds-smv/files/435032/test.fds.txt)

**Comment by mcgratta** [comment]
I added a check on the bounds of XB for SLCF.

**Comment by KateLM** [comment]
When I try to load the SCLF file now SMV crashes ('Smokeview.exe has stopped working'). ?

**Comment by gforney** [comment]
Have you tried with the latest smokeview - version 6.3.12.  If  you have and it still crashes, change the name of you input file from casename.fds to casename.fds.txt and upload. to this issue .  (do not copy input file within a comment).  I"ll take a  look at it.

**Comment by KateLM** [comment]
Yes, I have the latest version of smokeview.

**Comment by KateLM** [comment]
How do I upload the file outside a comment?

**Comment by drjfloyd** [comment]
![image](https://cloud.githubusercontent.com/assets/12799217/17969617/f66cd79a-6aa0-11e6-9e73-62a19f7f9d11.png)

**Comment by KateLM** [comment]
Ok, I thought "do not copy input file within a comment"  meant not this function. 
[scrubberHF.fds.txt](https://github.com/firemodels/fds-smv/files/437041/scrubberHF.fds.txt)

**Comment by drjfloyd** [comment]
Glenn meant don't paste the text of the file. It is a lot easier for us to be able to save a file directly rather than having to open an editor, copy and paste the text, and then save.

**Comment by gforney** [comment]
you case has ~7 million grid cells and all of your slice files are 3D which require a lot of memory.  I suggest you put in some 2D slice files in regions of interest.  report back whether these slice files fail

**Comment by KateLM** [comment]
Yes, 2D slice files will load. I will have to rely on these then. The 2nd and 3rd mesh is fine because of complexity of the obstructions (lots of cylinderical objects/pipelines). I have minimised this to 2 of 5 meshes (running on separate cores) and increased the grid size in the remainder of the room but there are still a lot of cells as you say. I will keep trying to reduce the computing time. Thank-you for your help!

**Comment by gforney** [comment]
there is also an option in smokeview to skip time steps.  this would reduce the memory requirement for viewing slice files.  Take a look at the Dialog>Data bounds dialog box (Time tab)

thanks for reporting back.

**Comment by KateLM** [comment]
Great, I'll try that. Thank-you
