### ISSUE TITLE
Vent overlapping error

### ISSUE THREAD

**Issue by KateLM** [firemodels/fds#4265]
Does anyone know why I might be getting error messages saying I have vent overlapping? They are open vents on the boundary of the simulation and I;ve checked the co-ordinates and cell size and they are not overlapping. I have applied a SURF_ID ='INERT' to all the boundary walls but even when I turn this off I still get the error (there are no other SURFs applied at the position of the vents). I have also colored them red but they don't appear in smokeview.

[scrubberHF.fds (2).txt](https://github.com/firemodels/fds-smv/files/447746/scrubberHF.fds.2.txt)

**Comment by mcgratta** [comment]
Open up the case in Smokeview. Hit the "q" key. See all of your obstructions shift to align with the mesh. This will lead to multiple VENTs or OBST faces sharing the same surface.

**Comment by drjfloyd** [comment]
From your file:

&VENT XB=0,180,0,-20.15,12.83,12.83, SURF_ID='INERT'/
...
&VENT XB=13.5, 14.3,-2.8,-2, 12.83, 12.83, SURF_ID='FANS', COLOR='RED'/
&VENT XB=76.5,77.3,-2.8,-2, 12.83, 12.83, SURF_ID='FANS', COLOR='RED'/
&VENT XB=103.5,104.3,-2.8,-2, 12.83, 12.83, SURF_ID='FANS', COLOR='RED'/ vent 29
&VENT XB=157.5,158.3,-2.8,-2, 12.83, 12.83, SURF_ID='FANS', COLOR='RED'/

The first vent over the entire top of the domain is followed later on by four vents also at the top of the domain.
