### ISSUE TITLE
Can FDS5 and FDS6 be installed onto the same Linux computer?

### ISSUE THREAD

**Issue by adamxiaoli** [firemodels/fds#4280]
Dear all,

We need to install FDS5 and FDS6.5.2 onto a Linux computer. 
As I know FDS5 uses LMP MPI and FDS6.5.2 uses OpenMPI.
My question is: can we install two different MPI onto a same Linux computer and then install two versions of FDS, respectively?

Any tips or instructions are appreciated.

Xiao

**Comment by mcgratta** [comment]
We don't support FDS 5, and we do not recommend you use it because FDS 6 fixes some serious problems in FDS 5. Why would you want to run code that you know may be incorrect? If you have run calculations with FDS 5, then re-run them with FDS 6.

**Comment by drjfloyd** [comment]
While we certainly advocate running with the most recent versions, you can have both FDS 5 and FDS 6 on the same machine.  You need to make sure you set the appropriate environmental variables and library paths for the version of FDS you are running. Consult your local sysadmin for assistance in doing this on your particular machine.
