### ISSUE TITLE
HRR greater than prescribed

### ISSUE THREAD

**Issue by GL-fire** [firemodels/fds#4315]
Hi everybody,

first of all, excuse my english please, because I didn't practice it for a long time !

I've runned calculcations with a model including several fires (which can be classified in 4 main categories), with a prescribed HRR for each one using HRRPUA and ramps.
But the HRR files indicate a global HRR greater than expected.
So I run three simplified calculations in order to find the problem.
I joined the fds and HRR files of those three tests to be clear.

All tests are run with cells of 0.1 x 0.1 x 0.1 m.

In the test 1, the fire consists of a single horizontal plate. The dimensions are 3.2 m x 0.4 m, with a prescribed HRRPUA of 1060 kW/m2, and a max ramp factor of 1. According my hand calculations, a HRR max of 1356 should be expected.
However, the HRR max indicated on HRR files is about 1800-1850 kW (roughly factor 1.35 greater).
But when multiplying the mass loss rate indicated on HRR files by the Heat of combustion (25 MJ/kg), the prescribed value of HRR max is obtained (1356 kW).

The same results are globally obtained in test 2.
The fire consists of a single horizontal plate. The dimensions are 3.2 m x 0.5 m, with a prescribed HRRPUA of 1206 kW/m2, and a max ramp factor of 1. According my hand calculations, a HRR max of 1930 kW should be expected.
However, the HRR max indicated on HRR files is about 2600-2850 kW (roughly factor 1.4 greater).
But when multiplying the mass loss rate indicated on HRR files by the Heat of combustion (25 MJ/kg), the prescribed value of HRR max is obtained (1930 kW).

In the test 3, two kinds of fire (fire 3 and fire 4) are expected.
"Fire 3" consists of 3 vertical plates (1 of dimensions 1.2 m x 0.6 m, 2 of dimensions 1.2 x 0.8 m), with a prescribed HRRPUA of 1.041 kW/m2, and a max ramp factor of 325.
"Fire 4" consists of 3 vertical plates (1 of dimensions 0.8 m x 0.6 m, 2 of dimensions 0.4 x 0.5 m), with a prescribed HRRPUA of 5 kW/m2, and a max ramp factor of 55.
According my hand calculations, a HRR max of 1136 kW should be expected.
And in this case, the HRR max indicated on HRR files corresponds to the expected HRR max, and to the product of mass loss rate by heat of combustion.

So what could be the reasons of such an HRR max in the first two tests ?

EDIT : I don't know why, but the joined .ZIP file isn't added ("unfortunately, we don't support that file type)
So below a link to get the file.
http://dl.free.fr/r17ItKpdj

**Comment by drjfloyd** [comment]
Are you seeing an average heat release rate that exceeds your input or just
a brief transient that does?  In a CFD model fuel and air must mix to burn.
FDS is an LES model so that process is not uniform over time. At times the
rate of mixing of fuel and air will be higher (more heat release) or lower
(less heat release).

**Comment by GL-fire** [comment]
It's the average which is greater. 
The HRR max is roughly steady during the plate of the HRR curve.
Could you download the files with the link (I joined the fds and HRR files)?

**Comment by GL-fire** [comment]
It's the average which is greater. 
The HRR max is roughly steady during the plate of the HRR curve.
Could you download the files with the link (I joined the fds and HRR files)?

**Comment by drjfloyd** [comment]
Please simplify as much as possible and attach one of your FDS files to the
issue tracker.

**Comment by GL-fire** [comment]
[FDS_test.ZIP](https://github.com/firemodels/fds/files/469652/FDS_test.ZIP)

The uploading has succeeded this time.

Here are the 3 fds and associated hrr files.

**Comment by GL-fire** [comment]
[FDS_test.zip](https://github.com/firemodels/fds/files/469673/FDS_test.zip)
The uploading succeeds this time.
Here are the 3 fds and hrr files.

**Comment by drjfloyd** [comment]
Your input file is for FDS 5, update to the latest version and see if that solves your problem.

**Comment by GL-fire** [comment]
I'm running several tests, I let you know the results as soon as available.

**Comment by GL-fire** [comment]
Test made.
The bug exists on versions 5.5.1 and 5.5.2, but is fixed on versions 5.5.3 (consequently in FDS 6 too).

Thanks for your help and interests.

Best regards
