### ISSUE TITLE
FDS enhancement request, add clock time to _hrr.csv or _cpu.csv

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4331]
Morning,

I think it would be useful to be able to view the progress and rate of a simulation graphically. That would allow users to anticipate problems, for example seeing a simulation slow down before a numerical instability. 

As the _hrr-cvs file is always created, I'm suggesting either adding wall clock time as a new column, or it could be put in the _cpu.cvs file, and the user would have to explicitly ask that file to be written periodically.

Thanks

Dave

**Comment by mcgratta** [comment]
These sound like good suggestions for PyroSim or similar GUI. I hesitate to add new default columns to output files because we store some of the .csv files in the fds repository and we have a limit on total space. These files are not that big, but we commit them again and again as we do integration testing. The history of the files is preserved by the repo whether we like it or not. Our recent overhaul of the FDS-SMV repo was due to an accumulation of 3 GB's worth of history of our output files.

**Comment by rmcdermo** [comment]
I think Dave is thinking this column would only be added if specified by the user, such as

&DUMP HRR_WALL_CLOCK_COLUMN=T/

As [koverholt.com](http://www.koverholt.com/calculators/) does not seem to have his time estimator still available, I vote we add this.

**Comment by lu-kas** [comment]
Or you could just parse the CHID.out file, which contains all requested information, but only in a 100-step-intervall.

**Comment by rmcdermo** [comment]
Yes, that is what Kris Overholt used to do.  Now, though, the .out file behavior changes depending on the number of MPI processes being used.  I suspect that is when he got rid of his calculator.

**Comment by drjfloyd** [comment]
Could this just be done as a new type of DEVC?

**Comment by mcgratta** [comment]
One can always do this

```
&DEVC XYZ=..., QUANTITY='WALL CLOCK TIME', ID='time' /
```

It's not the output option that I'm concerned about -- I just don't want to add it as a default.

**Comment by Dave-McGill** [comment]
Hi guys,

I wasn't aware you could add a device for wall clock time. I think it is
the most benign solution.

I've put in an enhancement request to Thunderhead to generate the graph in
their simulation progress window. They already have an estimate of the time
remaining, which is also handy.

Dave

**Comment by mcgratta** [comment]
I rarely use this output, so let me know if you have trouble with it.
