### ISSUE TITLE
PDPA : requires massless particle

### ISSUE THREAD

**Issue by kprasad64** [firemodels/fds#4332]
Input file x4.fds executes correctly and predicts the number concentration using a PDPA device. 

However when PART_ID information is added to &PROP line (input file x5.fds), FDS gives an error

ERROR: PART_ID for PROP 1 cannot refer to MASSLESS particles (CHID: x5)
 STOP: FDS was improperly set-up (CHID: x5)

I am interested in computing the number of particles that reach a device (sensor / tower) from two different locations (emitters) in the domain. Need to add PART_ID information to differentiate between the particles reaching a sensor.

**Comment by kprasad64** [comment]
&HEAD CHID='x4',  TITLE='simple test of turbulent dispersion model, D=0.01' /

&MESH IJK=20,10,10, XB=0,20,-5,5,0,10/

&TIME T_END=60. /

&DUMP DT_DEVC_LINE=30. /

&MISC U0=1, FREEZE_VELOCITY=.TRUE., NOISE=.FALSE., SC=1,
      GVEC=0.0,0.0,0.0, /

&SPEC ID='AIR', VISCOSITY=.1, BACKGROUND=.TRUE. /

&PART ID='tracer1',
      MASSLESS=.TRUE.,
      TURBULENT_DISPERSION=.TRUE./

&PART ID='tracer2',
      MASSLESS=.TRUE.,
      TURBULENT_DISPERSION=.TRUE./

&INIT XYZ=5,-1,5,
      PART_ID='tracer1',
      N_PARTICLES=20,
      DT_INSERT=1 /

&INIT XYZ=5,1,5,
      PART_ID='tracer2',
      N_PARTICLES=20,
      DT_INSERT=1 /

&VENT MB = 'XMIN', SURF_ID = 'OPEN' /
&VENT MB = 'XMAX', SURF_ID = 'OPEN' /

&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=.TRUE. /

&PROP ID='pdpa_1',
      QUANTITY='NUMBER CONCENTRATION',
      PDPA_RADIUS=1.0,
      PDPA_NORMALIZE=.FALSE.,
      PDPA_INTEGRATE=.FALSE. /

&DEVC XYZ=19,0,5, QUANTITY='PDPA', PROP_ID='pdpa_1', ID='npv1' /

&TAIL /

**Comment by kprasad64** [comment]
&HEAD CHID='x5',  TITLE='simple test of turbulent dispersion model, D=0.01' /

&MESH IJK=20,10,10, XB=0,20,-5,5,0,10/

&TIME T_END=60. /

&DUMP DT_DEVC_LINE=30. /

&MISC U0=1, FREEZE_VELOCITY=.TRUE., NOISE=.FALSE., SC=1,
      GVEC=0.0,0.0,0.0, /

&SPEC ID='AIR', VISCOSITY=.1, BACKGROUND=.TRUE. /

&PART ID='tracer1',
      MASSLESS=.TRUE.,
      TURBULENT_DISPERSION=.TRUE./

&PART ID='tracer2',
      MASSLESS=.TRUE.,
      TURBULENT_DISPERSION=.TRUE./

&INIT XYZ=5,-1,5,
      PART_ID='tracer1',
      N_PARTICLES=20,
      DT_INSERT=1 /

&INIT XYZ=5,1,5,
      PART_ID='tracer2',
      N_PARTICLES=20,
      DT_INSERT=1 /

&VENT MB = 'XMIN', SURF_ID = 'OPEN' /
&VENT MB = 'XMAX', SURF_ID = 'OPEN' /

&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=.TRUE. /

&PROP ID='pdpa_1',
      PART_ID='tracer1',
      QUANTITY='NUMBER CONCENTRATION',
      PDPA_RADIUS=1.0,
      PDPA_NORMALIZE=.FALSE.,
      PDPA_INTEGRATE=.FALSE. /

&PROP ID='pdpa_2',
      PART_ID='tracer2',
      QUANTITY='NUMBER CONCENTRATION',
      PDPA_RADIUS=1.0,
      PDPA_NORMALIZE=.FALSE.,
      PDPA_INTEGRATE=.FALSE. /

&DEVC XYZ=19,0,5, QUANTITY='PDPA', PROP_ID='pdpa_1', ID='npv1' /
&DEVC XYZ=19,0,5, QUANTITY='PDPA', PROP_ID='pdpa_2', ID='npv2' /

&TAIL /

**Comment by rmcdermo** [comment]
Kuldeep,
Try the latest code.  The x5.fds case should work now.

**Comment by rmcdermo** [comment]
No comment from user.  Closing.
