### ISSUE TITLE
BURN_AWAY in medium sized warehouse - Numerical Instability 

### ISSUE THREAD

**Issue by Giovannifds** [firemodels/fds#4335]
Dear All, 

while there are several examples of the fact that BURN_AWAY feature works well and in the past we have been able to use it quite successfully in small to medium scale models, now we are experiencing hard numerical instability issue when applying the feature to a warehouse model. 

Please find attached a comprehensive description of the problem and of our troubleshooting activity that has led us to formulate the hypothesis that in the present case numerical instability is due to the BURN_AWAY feature. 

We attach also the .fds files. 

[Description of the problem.pdf](https://github.com/firemodels/fds/files/481857/Description.of.the.problem.pdf)

Thank in advance for any help that could be provided.

Best regards

Giovanni Cocchi. P.E.,Ph.D.

**Comment by mcgratta** [comment]
I'll take a look at the case.

**Comment by mcgratta** [comment]
Have you run the cases with the latest version of FDS, 6.5.2?
Have you determined, by looking at the Plot3D output, where the instability is occurring?

**Comment by Giovannifds** [comment]
Thank You very much for the fast reply. 

We will try to run the file on FDS 6.5.2 .

Looking at the Plot3D output we have not found any hint on where the instability is occurring. Could You please suggest me a specific parameter to look for?

Thank You in advance. I await to hear something more from You and I will let You known what happens with 6.5.2.

Best regards

Giovanni Cocchi. P.E.,Ph.D.

**Comment by mcgratta** [comment]
I am running cases 2, 4, and 5 -- the ones that failed for you. All three cases have run successfully beyond the point where the combustibles have been consumed.

**Comment by Giovannifds** [comment]
Great to hear! I understand You are running them on 6.5.2, correct?

Best regards

Giovanni Cocchi. P.E.,Ph.D.

**Comment by mcgratta** [comment]
Correct

**Comment by mcgratta** [comment]
All cases completed successfully.

**Comment by Giovannifds** [comment]
Thank You Very Much for the feedback. Our simulations completed successfully too.

While it seems that using the last version of the code solved the issue (our fault not keeping up to date :-)), we are still curios to learn why it crashed.

We read the release note about the time lag between hydrodynamic pressure in the baroclinic term and the output from the pressure Poisson equation causing numerical instability in long sealed tunnel and we wonder if the same was happening in our case.

May it be that with large disappearance rate of solid obstruction the same time lag problem develops?

I would appreciate if You could provide some insight about this, Anyway, it seems that the problem is solved and I greatly appreciate the help! 

Best regards

Giovanni Cocchi. P.E.,Ph.D.

**Comment by mcgratta** [comment]
When a solid object is removed, it disappears instantly, leaving a grid cell that is empty of all mass. We fill it with ambient temperature air, but that then creates large gradients in temperature and species mass. If we fill the void with hot gas species to lessen the gradient, we have then created mass of fuel, energy, and so on. Pick your poison. Real items don't magically disappear like this, but what is the alternative in a numerical model where everything must be approximated in terms of a single grid cell?

**Comment by Giovannifds** [comment]
Hi!

I want to report that when we switched back to our original material definition, we experienced a crash even with 6.5.2 version.

Best regards

Giovanni Cocchi. P.E.,Ph.D.

**Comment by mcgratta** [comment]
Submit the input file.

**Comment by Giovannifds** [comment]
Hi!

I attach the original input file that is still crashing
[FDS_INPUT.zip](https://github.com/firemodels/fds/files/501342/FDS_INPUT.zip)
.

Best regards

Giovanni Cocchi. P.E.,Ph.D.

**Comment by mcgratta** [comment]
At what time in the simulation does the job fail?

**Comment by Giovannifds** [comment]
Something like 400 seconds. Please note that crash happens even if all control logics are shut down.

Best regards,

Giovanni Cocchi P.E., Ph.D.

**Comment by mcgratta** [comment]
The case ran successfully for me with the linux version of FDS 6.5.2. Compare the version numbers with those in the attached `.out` file.

[PJ27_15.out.zip](https://github.com/firemodels/fds/files/502943/PJ27_15.out.zip)

What is the operating system that you are using?

**Comment by Giovannifds** [comment]
Hi!
Version number is the same of Your .out file.

Operating system is Linux - Ubuntu 14.04 LTS

Best regards,

Giovanni Cocchi P.E., Ph.D.

**Comment by mcgratta** [comment]
I cannot replicate the problem. Does the simulation fail with a Numerical Instability (check the end of the .out file)? Does the simulation fail at the exact same time each time you run it? If it is a Numerical Instability, can you find where the problem is occurring, by looking at the slice vectors of the Plot3D file that is output?

**Comment by mcgratta** [comment]
Any more news on this issue?

**Comment by tgob** [comment]
I was most interested in the treatment of the empty cells created by burn away.  It is clearly unreasonable to generate additional mass to fill the void (although according to the big bang theory this is possible).  An alternative might be to average the surrounding connected gas phase cells and deduct (pro-rata) the mass, energy, momentum and species from these surrounding cells.  This will reduce the transient while retaining the models integrity.  The local loss should rapidly propagate through the model.

Giovanni, in regard to the reported numerical instability you might try increasing the resolution of the mesh in the vicinity of the burning object.

t.

**Comment by mcgratta** [comment]
This will lead to more numerical instability. I have tried many different ways to fill the hole, and the most robust way is to just fill it with ambient temperature air. The mass inaccuracy is very small in large scale simulations.
