### ISSUE TITLE
Fuel quantity of pool fire [reported by Berkan Kayadan]

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4337]
This issue was reported to the discussion forum.  I have reproduced the problem on a slightly smaller case.

The density of the MATL is specified as 675 kg/m3.  The pan liquid volume is 0.1 m3.  The pan thickness and grid spacing are 0.1 m in this case.   The MLR is set to 0.1 kg/s.  Thus, the pan should "burn away" at 675 s.  But it burns out too quickly, at around 237 s.

[test.fds.txt](https://github.com/firemodels/fds/files/483567/test.fds.txt)

**Comment by mcgratta** [comment]
It appears that a specified mass flux (`MLRPUA`) and the evaporation model (`BOILING_TEMPERATURE`) are being used simultaneously. FDS should have thrown an error. I'll fix that. In the mean time, do not use these two modes of pyrolysis simultaneously.

**Comment by mcgratta** [comment]
I added an ERROR statement to stop the program if multiple pyrolysis models are invoked. If you remove the liquid fuel burning parameters, you still need to specify the obstruction that represents the fuel as follows:

```
&OBST XB=-0.5,0.5,-0.5,0.5,0.0,0.1, SURF_ID='N-HEPTANE POOL', BULK_DENSITY=675., OVERLAY=.FALSE. /
```

The `BULK_DENSITY` indicates how much mass is contained in the obstruction, and `OVERLAY=.FALSE.` means that the surface of the fuel `OBST` should not overlay the steel pan surface.

**Comment by bkayadan** [comment]
Hi Kevin, 

Thank you for the explanation of reason of the problem. As you said i deleted boiling temperature section and defined the obstruction that represents the fuel as you explained above. I reanalyzed the case with MLR 0,1 kg/s  and fuel burned out around 675 seconds as i expected. 

If im wrong please correct me but according to my understand, setup of the liquid pool fire same as solid fuels if i want to use MLR. I mean bulk density must be assigned to obstruction that represents the fuel even if liquid fuel.

**Comment by mcgratta** [comment]
Yes
