### ISSUE TITLE
 DEVICE Activation Times

### ISSUE THREAD

**Issue by Alshroof** [firemodels/fds#4345]
Hi.

I did updated my FDS to 6.5.2 recently, and I noticed that if a stop order is send before the model completes the run, the DEVICE Activation Times list will not be included in the out file. However this was not the case for the older FDS.

So if I added a few devices to my model and I need to know the activation time for the devices, then I can't interrupt he run and I have to wait for the run to complete.

Kind regards
Dr Alshroof

**Comment by mcgratta** [comment]
This can probably be restored. I'll check on it.

**Comment by mcgratta** [comment]
I added back the functionality. Will be in the next release.

**Comment by Alshroof** [comment]
Many thanks Kevin
