### ISSUE TITLE
numerical instability

### ISSUE THREAD

**Issue by mrvlty** [firemodels/fds#4348]
I model a tunnel fire with a fan as you can see from attached input data. 
After 1.65 s. simulation time, it gave numerical instability. I checked the model again and again but I don't understand what can cause it?  Please help me.

![error](https://cloud.githubusercontent.com/assets/16001133/18777994/ba6755a4-817a-11e6-97b0-dd56d3d23727.png)

[50mwfirefan5.txt](https://github.com/firemodels/fds/files/489116/50mwfirefan5.txt)

Thank you for your interest.

Sincerely yours,

**Comment by mcgratta** [comment]
Do not submit your issue to both the Discussion Group and Issue Tracker. This can cause multiple people to waste time working on the same issue. I have deleted your Discussion Group post. 

As for the case, have you run it with the latest version of FDS, 6.5.2?

**Comment by rmcdermo** [comment]
Both serial and mpi versions (I highly recommend you run this with 10 or more meshes) are running fine with latest code.

**Comment by rmcdermo** [comment]
Attached case finished with latest code.

[mrvlty_mpi.fds.txt](https://github.com/firemodels/fds/files/490148/mrvlty_mpi.fds.txt)

**Comment by mrvlty** [comment]
Thank you Mr. McDermott
Do you mean I should run paralel your attached case?
If it is so, It is a good news, because previous version couldn't solve
that case properly.

2016-09-23 19:13 GMT+03:00 Randy McDermott notifications@github.com:

**Comment by rmcdermo** [comment]
If you have capability to run mpi, definitely.

**Comment by mrvlty** [comment]
ok, Mr. Mcdermott
I will try.
Thank you

**Comment by mcgratta** [comment]
Here is something else you should do. The interior of your tunnel is separated from the exterior of the computational domain by at least one grid cell. This means that there is a gap or void space between the tunnel arch and exterior boundary. The exterior boundary is solid by default, which means that there is a sealed space that has not been declared a pressure `ZONE`. I suggest you open up this space with the lines

```
&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
```
