### ISSUE TITLE
Localised Leakage - temperature issue

### ISSUE THREAD

**Issue by FireMatt** [firemodels/fds#4355]
Hi there, I am attempting to model a simple door leakage case.  However the attached is yielding odd results.  As the smoke leaks into the next pressure zone, it cools...  

I can't figure this one out!

It may be associated with the heat transfer calculations through the leak using, LEAK_ENTHALPY=.TRUE.

Any advice would be very much appreciated.

Kind regards

Matt.  
[Local Pressure - Smoke Cooling.txt](https://github.com/firemodels/fds/files/498857/Local.Pressure.-.Smoke.Cooling.txt)

**Comment by mcgratta** [comment]
We'll take a look at it.

**Comment by bmralph** [comment]
What version of the code are you using? There was a problem in 6.4.0 which could lead to very cold flow exiting a leak (issue #3930).

Try the latest code as this bug has been fixed.

**Comment by FireMatt** [comment]
I'm using 6.4.... my fault!  Many thanks for the quick response!  Cheers

Matt.
