### ISSUE TITLE
Mpiexec freezes on start

### ISSUE THREAD

**Issue by Rantzer** [firemodels/fds#4358]
I am trying to run a simulation with parallel processing on one computer with 8 cores (Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10 Ghz). When I try to run parallel processing directly from pyrosim the dialog box opens and freezes.

I have also tried running FDS from the command prompt as administrator. Running the command mpiexec - n 4 fds "my_job".fds freezes the command prompt (no error message). ctrl+C twice unfreezes it again.

I have tried stopping the service Pyrosim MPI Hydra Service. This results in following Error:

\rokluckorparallel>mpiexec -n 4 fds rokluckorparallel.fds
Error connecting to the Service
[mpiexec@DESKTOP-L3HGPCB] ..\hydra\utils\sock\sock.c (270): unable to connect from "DESKTOP-L3HGPCB" to "DESKTOP-L3HGPCB" (No error)

I also have tried to re-install and start the Intel Hydra service resulting in the command prompt freezing again when running a mpiexec job 

...\rokluckorparallel>hydra_service -install
Intel(R) MPI Library Hydra Process Manager removed.
Intel(R) MPI Library Hydra Process Manager installed.

...\rokluckorparallel>hydra_service -start
Intel(R) MPI Library Hydra Process Manager failed to start.
Det finns redan en aktiv session av tjõnsten. (error 1056).

...\rokluckorparallel>mpiexec -n 4 fds rokluckorparallel.fds
^C
...\rokluckorparallel>

Where do I go from here?

---

Info on version:

 Fire Dynamics Simulator

 Current Date     : September 29, 2016  15:26:35
 Version          : FDS 6.5.2
 Revision         : Git-r21-0-g4e9103f
 Revision Date    : Wed Aug 24 16:29:46 2016 -0400
 Compilation Date : Wed 08/24/2016  10:28 PM

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Windows\* OS

 Consult FDS Users Guide Chapter, Running FDS, for further instructions.

 Hit Enter to Escape...

Regards
/Jesper

**Comment by mcgratta** [comment]
You need to report this to Thunderhead Engineering. We do not know the details of how they bundled the MPI libraries.

**Comment by Rantzer** [comment]
At first I also thought that it had something to do with the FDS-bundle from Pyrosim. However since I also downloaded the latest FDS/smokeview-bundle from NIST and ran it with the Intel hydra service with the same result I'm not so sure it's the Pyrosim bundle that is the problem.

I have also sent a question to T.E.

29 sep. 2016 kl. 17:22 skrev Kevin McGrattan <notifications@github.com<mailto:notifications@github.com>>:

You need to report this to Thunderhead Engineering. We do not know the details of how they bundled the MPI libraries.

##

**Comment by mcgratta** [comment]
I wonder if Thunderhead is still bundling with MPICH. There was a problem several months back where the MPI schedulers provided by us (NIST) and TE were different. We use Intel MPI, and we distribute the hydra service scheduler. MPICH uses another scheduler. So the mpiexec command was not working well with these multiple schedulers.

**Comment by Rantzer** [comment]
Ok. I'll uninstall Pyrosim and reinstall the latest bundle from NIST and se if the problem persist. Thanks for the help!

**Comment by mcgratta** [comment]
I'll leave this issue open. Make sure that you're working on a Windows Domain Network, that is, one where you have a common username and password and can login to any machine. Install FDS on each machine.

**Comment by Rantzer** [comment]
Do I have to be working on a Windows Domain Network even though I'm only using the cores on one processor on the local machine?

**Comment by mcgratta** [comment]
I would guess no, but I've never tried that since I am on a Windows Domain network.

**Comment by Rantzer** [comment]
Ok. So I have uninstalled all Pyrosim services on the computer, uninstalled FDS and reinstalled the bundle FDS_6.5.2-SMV_6.3.12_win64.exe. The command prompt still freezes when I run the command mpiexec -n 4 fds "my_job".fds.

In services I can see that Intel(R) MPI Library Hydra Process Manager is running. No other "Hydra-related" services are running.

If I force Intel(R) MPI Library Hydra Process Manager to stop and try to run the command mpiexec -n 4 fds "my_job".fds. again I get the error message 
Error connecting to the Service
[mpiexec@DESKTOP-L3HGPCB] ..\hydra\utils\sock\sock.c (270): unable to connect from "DESKTOP-L3HGPCB" to "DESKTOP-L3HGPCB" (No error)

This is probably because I have stopped the service and it may (or may not) be a clue to where the error lies.

The computer is not connected to a Windows domain network but I am only trying to use the cores on the local computer.

I am a bit lost here. Can i troubleshoot somehow?

**Comment by mcgratta** [comment]
Type

```
mpiexec hostname
```

What do you see?

**Comment by Rantzer** [comment]
It freezes.

If i try to run mpiexec -hosts it crashes.

**Comment by mcgratta** [comment]
How about 

```
where mpiexec
```

**Comment by Rantzer** [comment]
It returns the path to where mpiexec.exe is located.

I have to break for the night. 

Thank you for your help so far. I will try some different mpiexec-commands tomorrow and se what crashes the program and not.

**Comment by mcgratta** [comment]
Yes, where is it located? Is it the mpiexec that is bundled with FDS?

**Comment by Rantzer** [comment]
Sorry for the delay.

It returns 
c:\Program Files\firemodels\FDS6\bin\mpiexec.exe

**Comment by Rantzer** [comment]
Ok, I think I cracked it! Should be one of two things:

I had a space in the username that I used when trying to run mpiexec (windows log in username).
I'm from Sweden so I had an ä (pronounced aeh) in the username.

I created a new user (administrator) without space or special characters and now its running fine it seams.

Thank you for your help. You can close the thread.

**Comment by mcgratta** [comment]
I wonder if this is related to the presence of the Windows Domain Network. When I type

```
mpiexec -hosts 1 my_computer_name 3 test_mpi
```

I am first challenged for my account credentials <domain\user> and I respond with NIST\mcgratta and then my domain password. After that, I see "Hello world" written 3 times. This might indicate that mpiexec is not going to work unless you are on a Windows Domain Network, even if you are only on one machine. I have no non-WDN machines to test this guess, however. Do you have access to a computer that is on a Windows Domain Network?

**Comment by Rantzer** [comment]
Bad timing :)

I don´t think it was related to WDN. I think the problem was my user name.

**Comment by mcgratta** [comment]
It's always something like this.
