### ISSUE TITLE
Skip Smoke3D load if Q=0 in mesh

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4365]
Glenn,

I'm running a 144 mesh case with a burner localized on a few meshes.  Would it be possible to speed up the load and reload of 3D smoke and hrrpuv by having some threshold value for Q in the mesh?  I could imagine doing the calculation in FDS and add this info to the s3d file (if that is where it would go).

Let me know what you think.

**Comment by gforney** [comment]
randy,
should be pretty easy.

for each .s3d file (where 3d smokeand hrrpuv are found), FDS now outputs a "sizing" info into a corresponding .s3d.sz file.  This file has 3 columns.  The first column is time, the next two columns contain the number of uncompressed and compressed data elements respectively (smokeview uses this info to allocate memory without having to read the entire .s3d file).  I suggest you add a fourth column which would contains the maxium HRRPUV for time in column one . Smokeview would then use this info to decide whether to load the s3d file or not.  

So if your loading cutoff is 5 and the fourth column is always less than 5 smokeview would not load the file.  But if it started out being less than 5 but became later than 5 at some point, smokeview would load the file.

If you can add the fourth column, I'll make the changes to smokeview. (not tonight though!  maybe)

**Comment by rmcdermo** [comment]
Sounds perfect.  Let's talk more next week.

**Comment by rmcdermo** [comment]
Glenn,
Something I just thought of... sort of an obvious cutoff to use for when to load an s3d file is the HRRPUV cutoff value we show in the scene.  It looks like right now you use a value of 0.0000 as the default.  Might as well make it the HRR cutoff default of 200 kW/m3.  I think the 0 cutoff is causing many more loads than necessary in my scene and I am not getting the optimal speedup when the case runs to completion.

**Comment by gforney** [comment]
I'll do that. In the mean time you can set it by hand in the 3d smoke
dialog box

**Comment by gforney** [comment]
default is now as you suggested.  try smokeview at
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gforney** [comment]
should be implemented now - more importantly should work for cases run with fds without this feature - if not repopen the issue.
