### ISSUE TITLE
FDS crashing with subscript out of bounds error

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#4366]
I built FDS on Windows using the mpi_intel_windows_64_db target using source from the latest revision in the central fds repo.  I ran the case mplume5c8.fds from the smv central repo in Verification/Visualization .  I get the following result.  

 Time Step:     40, Simulation Time:      0.73 s
forrtl: severe (408): fort: (10): Subscript #2 of the array INTEGERS has value 1005 which is greater than the upper bound of 1000

Image              PC                Routine            Line        Source  
fds_mpi_win_64_db  00007FF6CC2E5309  Unknown               Unknown  Unknown
fds_mpi_win_64_db  00007FF6CC2A4178  FDS_ip_MESH_EXCHA        2678  main.f90
fds_mpi_win_64_db  00007FF6CC1A6C9C  MAIN__                    719  main.f90
fds_mpi_win_64_db  00007FF6CC40D50E  Unknown               Unknown  Unknown
fds_mpi_win_64_db  00007FF6CC40E144  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFC2C638364  Unknown               Unknown  Unknown
ntdll.dll          00007FFC2DF15E91  Unknown               Unknown  Unknown

Don't know why I'm getting the unknowns, as an aside we need to improve the command line compiler options for this target.  When I run the same case from Visual studio, I see that the code crashes in main.f90 in the following  loop at the line I've highlighted.  I am not seeing this crash when I run the case on a mac so maybe the problem is with windows compiler options. I do see the crash when I build with the mpi_intel_windows_64 target.  I will try to reproduce the problem on my windows pc at NIST.

```
     DO IPC=1,N_LAGRANGIAN_CLASSES
        IF (M2%N_PART_ADOPT(IPC)==0) CYCLE
        CNT = 0
        DO N=M4%NLP+1,M4%NLP+M2%N_PART_ADOPT(IPC)
           CNT = CNT + 1
           IBC = LAGRANGIAN_PARTICLE_CLASS(IPC)%SURF_INDEX
           CALL ALLOCATE_STORAGE(NOM,IBC,LPC_INDEX=IPC,LP_INDEX=N,TAG=-1)
           LP=>M4%LAGRANGIAN_PARTICLE(N)
           STORAGE_INDEX_SAVE = LP%STORAGE_INDEX

           M4%PARTICLE_STORAGE(IPC)%REALS(:,LP%STORAGE_INDEX)    = M2%ADOPT_PARTICLE_STORAGE(IPC)%REALS(:,CNT)
```

  ***crashes here-->            M4%PARTICLE_STORAGE(IPC)%INTEGERS(:,LP%STORAGE_INDEX) = M2%ADOPT_PARTICLE_STORAGE(IPC)%INTEGERS(:,CNT)

```
           LP%ARRAY_INDEX = N
           LP%STORAGE_INDEX = STORAGE_INDEX_SAVE

           M4%PARTICLE_STORAGE(IPC)%LOGICALS(:,LP%STORAGE_INDEX) = M2%ADOPT_PARTICLE_STORAGE(IPC)%LOGICALS(:,CNT)
        ENDDO
        M4%NLP = M4%NLP + M2%N_PART_ADOPT(IPC)
     ENDDO

  ENDIF IF_RECEIVE_PARTICLES
```

**Comment by gforney** [comment]
seeing the same problem on my windows PC at work.  Both PCs are using the latest Intel compilers.

like the mac am not seeing the  problem on blaze.  both the mac and the PC are not using  the latest compilers

**Comment by mcgratta** [comment]
This appears to be a compiler bug. I also have the latest Intel compiler for Windows and I get the same error. However, when I print out the size of the array just before the error, I see that the array is dimensioned (16,2000) which is large enough. Do you get the error with the older Intel compiler?

**Comment by gforney** [comment]
built fds with and older compiler, version 2016.0.110 on another PC.  The case runs fine.  THink you are right, it is a compiler bug.

**Comment by mcgratta** [comment]
Turns out that this was bad programming on my part. I think the compiler is fine. I fixed the bad lines of code.
