### ISSUE TITLE
HVAC Fan stopped in the middle of simulation without any cause

### ISSUE THREAD

**Issue by jumarko-haryanto** [firemodels/fds#4372]
Dear Sir/Mdm,

I have HVAC fan activated by delay timer at 184 seconds without any de-activation.
But in the simulation result, it turned out that the fans are deactivated at 238 seconds.
FDS version used is FDS 6.4.0. Do you know any solution to this issue?

Thanks a lot for your assistance

**Comment by jumarko-haryanto** [comment]
![3rd76prf6_0200](https://cloud.githubusercontent.com/assets/22585715/19029418/9f3bba76-8978-11e6-8aaa-8b724b4c8863.png)
![3rd76prf6_0199](https://cloud.githubusercontent.com/assets/22585715/19029419/9f3f8836-8978-11e6-945a-ab4bc24dc289.png)

**Comment by mcgratta** [comment]
There is no input file. Post a very simple input file that just demonstrates the error. Your images above show a case that is complicated and would be hard to debug. Just create a very simple test case, and post the input file.

**Comment by jumarko-haryanto** [comment]
Hi Sir,

Thanks for your help.
I tried to create a very simple scenario demonstrating fire withing a room, with exhaust fan for smoke extraction.

The said problem however, does not occur in the simplified version.
There is, however a descripancies that i noticed for the FDS file generated by pyrosim that i didn't notice earlier. The descripancies is posted alongside the reduced original input file below, alongside with the simplified case that i have run.

It's about these line of HVAC fan declaration
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=2.6, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/
&HVAC ID='ESCS fan', TYPE_ID='FAN', VOLUME_FLOW=5.0, DEVC_ID='TIMER->OUT'/

The one with volume_flow=5 was not intended

Do you think that might be the source of the perculiar things happened in the orignal run?

Thanks for your support

[debug.txt](https://github.com/firemodels/fds/files/507704/debug.txt)
[3RD76PRF6debug.txt](https://github.com/firemodels/fds/files/507705/3RD76PRF6debug.txt)

**Comment by drjfloyd** [comment]
You have all your FAN inputs named with the same ID.  You should not do this. You can use the same fan definition for more than one duct. FAN defines a class of fans like SURF defines a class of surfaces. If all your fans are identical, then you only need one FAN definition. See if that resolves your problem.

**Comment by jumarko-haryanto** [comment]
Dear Sir,

Thanks a lot for your input and assistance, it indeed resolves the problem.
post can be closed.
