### ISSUE TITLE
MPI error

### ISSUE THREAD

**Issue by jumarko-haryanto** [firemodels/fds#4378]
Dear Sir,

I'm currently running fds using mpi, but after a certain time, this error msg as attached below will appear.
I have tried it repeatedly, and every time it reaches about 100+ seconds, that error msg will appear.
Do you happen to know what the problem is?

Thanks for your assistance
![error msg](https://cloud.githubusercontent.com/assets/22585715/19100542/56bc2486-8af2-11e6-985b-8fa02d1c6b54.png)

**Comment by mcgratta** [comment]
Is anything happening in the simulation at about this time, like a door opening or sprinkler activating? What version of FDS are you using? If not the latest, have you tried the latest? 

Post the input file and I can try the case here on my small Windows cluster.

**Comment by jumarko-haryanto** [comment]
Dear Sir,

The FDS version used is FDS 6.4.0 at the moment, i have not tried using FDS 6.5.1 to run the numerical solution.

For this scenario, HVAC fan is supposed to be activated at 184 second, but nothing is set to happen at 174 seconds as when the error occurred.

Attached file is the complete input file, let me know if you need a reduced input file.
At the same time, do you happen to know the root cause of that error? Is it a network issue, or the program issue itself? I'm trying to debug this at the moment.

I have another mpi case running at another cluster using FDS 6.4.0, same geometry with the case i attached, same HVAC fan exhaust rate and activation time, just with different fire location and size, and they are working fine up to 1200 seconds.

Thanks for your assistance,

[3RD76PRF6.txt](https://github.com/firemodels/fds/files/513142/3RD76PRF6.txt)

**Comment by mcgratta** [comment]
The latest version of FDS is 6.5.2. Run the case with that version. It is pointless to try to debug an older version of FDS. We do not make fixes to old versions.

**Comment by jumarko-haryanto** [comment]
Dear Sir,

Oke, i will try with FDS 6.5.2, and report further if there is still any bug within.
Thank you for your assistance.

**Comment by jumarko-haryanto** [comment]
Dear Sir,

This is the error msg when i run in on FDS 6.5.2, using the same input file with what i have attached previously.

Do you know any root cause that i can investigate further?

Thanks for your assistance.
![error msg](https://cloud.githubusercontent.com/assets/22585715/19182303/12a082e2-8ca5-11e6-940f-b9371555c52e.png)

**Comment by mcgratta** [comment]
I started your case yesterday on our linux cluster, and it is still running after 575 s of simulated time. I will next try the case on a small cluster of Windows computers. I'll let you know next week if the case runs. 

Is this job running on multiple computers? If not, perhaps 17 MPI processes is overloading your cores. Regardless, when MPI jobs fail, it is very difficult to know what happened. We use linux clusters because they are more reliable. They have dedicated nodes/cores that do nothing else but compute. The message about network names no longer available suggests that your job is competing with other applications, or there is some temporary loss of connectivity that is common on a typical office network.

**Comment by jumarko-haryanto** [comment]
Dear Sir,

Thanks a lot for your assistance.
Yes, they are running on multiple computers, I'm using 2 computers for this case at the moment.
Indeed it is really difficult to know what really happened. I have tried to debug and came out with the following information without any conclusion:
-currently, I have a cluster of 6 windows PCs dedicated for FDS solver. 1,2,3,4,5,6 under one network
-when the MPI case runs on PC 1,4,5,6, they work fine (currently running at about 250 seconds).
-when the MPI case runs on PC 1,2,3,4,5,6 the error will appear
-when the MPI case runs on PC 2,3 (the current situation), the error will appear as well

Basing on your information regarding the error msg, most likely it's not about a temporary loss of connectivity since there are some PCs that will work well with the MPI case under the same network.

I will look to the possible case of any other applications that's competing with the FDS MPI job.

I will post it here if there is any conclusion regarding this situation.

Thanks for your support

**Comment by mcgratta** [comment]
Your case is running over 4 computers, all running Windows 7. It has gone 2400 time steps and is still running. These 4 computers are identical and they work well. However, I cannot get FDS jobs to run on my own Windows 7 computer and other computers on the network. I do not know why. When I complain to MS, or Intel, or our network admins, they all blame the other parties. That is the problem with MPI -- you are relying on different software and hardware vendors to coordinate.

**Comment by jumarko-haryanto** [comment]
Dear Sir,

Well, yeah, I think it's time for me to get Linux cluster for FDS MPI. 
On my case, all PCs currently running windows 10, PC 2 and 3 has identical specs, PC 5 and 6 has identical specs, while PC 1 and 4 is different from each other and different from the rest.

Even when i tried to run on PC 2 and 3 with identical specs, they do not run. And I don't know why as well.

I guess I just have to be content with this at the moment and work with a slower phase. I won't do further debugging for now.

Thanks for your assistance once again.

**Comment by mcgratta** [comment]
Your case is still running on my Windows cluster. It has run all weekend. I cannot reproduce your error. I wish I understood better how Windows and MPI interact, but I don't.
