### ISSUE TITLE
Open Vent Problem

### ISSUE THREAD

**Issue by bkayadan** [firemodels/fds#4379]
Hi FDS users,

I have 2m x 3m open vent and i placed an obstruction in front of open vent as described in FDS user guide section 15.4.2. This obstruction represents a door and shall be deactivated in 200 seconds. At first i tried with open vent without obstruction and simulation is succesfully completed. Following i tried with different surfaces such as exhaust and supply with obstruction and simulations are completed successfully however when i wanted to try with open vent with obstruction i always get numerical instability around 80 seconds. Any suggestions?

Thanks in advance
[With_door_obstruction_cont.txt](https://github.com/firemodels/fds/files/511257/With_door_obstruction_cont.txt)

**Comment by mcgratta** [comment]
Add

```
&ZONE /
```

to the input file. This tells FDS that the compartment is a sealed pressure zone. When FDS reads the `OPEN` vent line, it assumes that the compartment is open to the outside and not sealed.

**Comment by bkayadan** [comment]
Thank you for the explanation Kevin, i understand what the problem is and it works. 
Best Regards,
