### ISSUE TITLE
SETTIMEVAL in ssf not loading correct frame

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4385]
Glenn,

Per our discussion, if you look at the FDS verification case

fds/Verification/Heat_Transfer/ht3d_ibeam.fds

Run smv with ssf script and you should get the time frame with 3600 s, but currently it gives 3595.  As you saw, setting the FDS T_END to something larger allows ssf to give the correct frame.

All the necessary files are committed to the fds repo, but you could also look at my repo on burn:

/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Heat_Transfer

Thanks!

**Comment by gforney** [comment]
should be fixed now.  smokeview was searching all frames except the last one when determining which frame matched a given time.  I'll build a smokeview for you to test tomorrow

**Comment by rmcdermo** [comment]
Looks like you got it fixed before the firebot run!  Thanks!
