### ISSUE TITLE
O2-CO2 mismatch?

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4386]
Run the following case:

```
&HEAD CHID='RSE_01_test' /
&MESH XB= 0.00,1.42,0.00,0.95,0.00,0.98, IJK=24,16,16 /
&TIME T_END=60. /
&MISC Y_CO2_INFTY=0., HUMIDITY=0. /
&REAC FUEL='METHANE' /
&SURF ID='fire', HRRPUA=1000., COLOR='ORANGE' /
&VENT XB=0.66,0.78,0.41,0.54,0.00,0.00, SURF_ID='fire' /
&VENT XB=0.0, 0.0, 0.24, 0.72, 0.00,0.81, SURF_ID='OPEN' /
&DEVC XYZ=1.1,0.3,0.9, QUANTITY='VOLUME FRACTION', SPEC_ID='OXYGEN',         ID='X_O2'  /
&DEVC XYZ=1.1,0.3,0.9, QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON DIOXIDE', ID='X_CO2' /
&TAIL /
```

Then plot `X_CO2` vs `(X_O2_ambient-X_O2)*0.5`. I would expect the curves to be the same, but I see that they're about 10% different. Am I missing something obvious?

**Comment by drjfloyd** [comment]
You have diluted the air with fuel so prior to combustion there is not 0.21 moles of O2 present.  What you have to do is look at the ratio of X_N2 to the moles of X_N2 at the start and use that for the amount of O2 present prior to combustion.  e.g at t=0 X_N2 is 0.79 and X_O2 is 21.  At some time later X_N2=0.78 then the X_O2 present prior to combustion is 0.78/0.79_0.21 and not 0.21.  If you take 0.78/0.79_0.21 - X_O2_DEVC it will match the X_O2 the way you compute it with X_CO2 and X_H2O.

**Comment by mcgratta** [comment]
Now I get it.

I must multiply (X_O2_ambient-X_O2) by 0.5 and by nu_O2/(nu_F*X_O2_amb+nu_O2), the latter factor being the moles of O2 and N2 divided by the moles O2+N2+F. 

Thanks
