### ISSUE TITLE
Wiki: Git Notes Getting Started

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#4390]
Think I worked out why many people have "=" as their user name and email. When setting these parameters the correct syntax is:

```
$ git config --global user.name "John Doe"
$ git config --global user.email john.doe@example.com
```

and not (as is in wiki page):

```
$ git config --global user.name = "John Doe"
$ git config --global user.email = "john.doe@example.com"
```

**Comment by rmcdermo** [comment]
Should be fixed now.  Thanks.

**Comment by bmralph** [comment]
There should be no quotes on the email address.

**Comment by rmcdermo** [comment]
Sorry.  Hopefully fixed now.
