### ISSUE TITLE
Heat of formation of unknown fuel

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4405]
Run this little case

```
&HEAD CHID='test' /
&MESH XB=0,1,0,1,0,1, IJK=10,10,10 /
&TIME T_END=0.1 /
&REAC FUEL = 'STYRENE', FORMULA='C8H8' /
&TAIL /
```

and look at the `test.out` file. The Heat of Combustion is 39514 kJ/kg, fairly close to the handbook value of 39400 kJ/kg. But the Enthalpy of Formation for STYRENE is reported as 0 in the .out file. I thought that an effective value was calculated based on the assumption that complete combustion generates 13100 kJ/kg oxygen consumed.

**Comment by drjfloyd** [comment]
When we went to make N2 the default for an unlisted species we wound up breaking the H_F calc for the case where EPUMO2 is used.   Fixed in commit https://github.com/firemodels/fds/commit/03f83a81f15330a6b99a67c9c5296631b8640cba

**Comment by mcgratta** [comment]
Thanks, it works.
