### ISSUE TITLE
FDS Validation Guide, Table of Git Stats has wrong date

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4411]
The most recent FDS Validation Guide shows today's date in Table 15.2 under "FDS Revision Date". It should show the date when that version was compiled.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed now.  Also, figured out how to get correct date for all entries in Table 15.2 .  This will be tested in tonights firebot run.

**Comment by mcgratta** [comment]
Great, I'll hope the issue open and check tomorrow. Thanks.

**Comment by mcgratta** [comment]
Looks good, thanks.
