### ISSUE TITLE
OpenMP Notes, minor edit

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4412]
The wiki states,

"With P as the number of MPI processes launched per machine, T as the number of threads per MPI process and C as the number of physical cores of your machine you want to hit: N*T=C."

Should that formula be P*T=C ?

**Comment by mcgratta** [comment]
I'll check.

**Comment by mcgratta** [comment]
Done, thanks.

**Comment by Dave-McGill** [comment]
I'm sure that this is the one and only time I'll be correcting the math on this site.    :-)

**Comment by mcgratta** [comment]
I doubt that. Cores, nodes, sockets, processes, threads -- everyone uses slightly different notation, so the math is simple, but the symbols get confused. Even mpiexec and mpirun use almost the same syntax, but not quite, especially -n and -np, and sometimes the two are the same, sometimes not.
