### ISSUE TITLE
Different fluxes in target test.

### ISSUE THREAD

**Issue by rkj15** [firemodels/fds#4416]
Hello,

I am using the target test (from the examples) to compare the particle and obstruction model. The default file works fine.

I added a MATL_ID to the surf and specified the material properties.
After doing this I see that the flux on the particle and obstruction is different but the temperature(surface) of the particle and obstruction are similar. The flux decreases for the obstruction but remains constant for the particle. Can someone tell me the reason for this ? I have attached the input file.

FDS version: 6.5.2.

Thank you !!
Rahul.
[Target_test.pdf](https://github.com/firemodels/fds/files/524326/Target_test.pdf)

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
This is a bug. FDS is not storing the outgoing radiation loss for the particle for use with the `'RADIATIVE HEAT FLUX'`. However, it is calculating the particle temperature properly. Until the next release, do not use the output quantity `'RADIATIVE HEAT FLUX'` for a particle.

**Comment by rkj15** [comment]
Alright, thank you. I'll remember that.
