### ISSUE TITLE
Spurious spikes of temperature in isothermal test case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4428]
The following case exhibits spikes in temperature at about 4 s. It is supposed to be isothermal, but if you look at the slice of `TEMPERATURE` near the ceiling of the compartment, you can see a short burst of checkerboarding that eventually goes away. VN  bound doesn't seem to matter. Not sure if we want to "fix" this, or use this to sort out near wall viscosity issues. For now, it just might be a good test case for general transport stuff. A different CFL criteria will probably fix it, but could it be related to the nature of the turbulence model in the near-wall cell?

```
&HEAD CHID='iso_test2', TITLE='Test isothermal condition with thin obstructions' /

&MESH XB=0.00,1.44,0.00,0.96,0.00,0.96, IJK = 48,32,32 /

&TIME T_END=20. /

&SPEC ID='HELIUM' /

&MISC NOISE=.FALSE., VN_MAX=0.5, VN_MIN=0.4 /

&RADI RADIATION=.FALSE. /

&PRES VELOCITY_TOLERANCE=0.00001, MAX_PRESSURE_ITERATIONS=100, ITERATION_SUSPEND_FACTOR=1. /

&SURF ID='gas', SPEC_ID(1)='HELIUM', MASS_FLUX(1)=0.01, COLOR='ORANGE'  /

&VENT XB=0.54,0.90,0.30,0.66,0.00,0.00, SURF_ID='gas' /
&OBST XB=0.51,0.54,0.30,0.66,0.00,0.12 /
&OBST XB=0.90,0.93,0.30,0.66,0.00,0.12 /
&OBST XB=0.51,0.93,0.27,0.30,0.00,0.12 /
&OBST XB=0.51,0.93,0.66,0.69,0.00,0.12 /

&VENT XB=0.00,0.00,0.24,0.72,0.00,0.81, SURF_ID='OPEN' /

&SLCF PBZ=0.955, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBX=0.975, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBX=0.72, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.48, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBX=0.72, QUANTITY='DENSITY',     CELL_CENTERED=.TRUE. /
&SLCF PBY=0.48, QUANTITY='DENSITY',     CELL_CENTERED=.TRUE. /
&SLCF PBY=0.48, QUANTITY='VISCOSITY',   CELL_CENTERED=.TRUE. /
&SLCF PBZ=0.95, QUANTITY='VISCOSITY',   CELL_CENTERED=.TRUE. /

&DUMP DT_DEVC=0.0000000001 /
&DEVC ID='T_max', XB=0.00,1.44,0.00,0.96,0.00,0.96, QUANTITY='TEMPERATURE', STATISTICS='MAX' /
&DEVC ID='T_min', XB=0.00,1.44,0.00,0.96,0.00,0.96, QUANTITY='TEMPERATURE', STATISTICS='MIN' /
&DEVC ID='VN', XYZ=0,0,0, QUANTITY='VN MAX' /
&DEVC ID='CFL', XYZ=0,0,0, QUANTITY='CFL MAX' /


&TAIL /
```

**Comment by rmcdermo** [comment]
This case runs ok if you add either CFL_VELOCITY_NORM=1 or FLUX_LIMITER=4 to MISC.

I have been wanted to migrate toward using FL4 as a default anyway.  This just adds to the list of reasons why this would be a good move.

I suggest we do a maintenance release and then move toward FL4 as default in the next minor release.

If you want this case to be tested, add it to the verification suite.  I'll close for now.
