### ISSUE TITLE
Device timer does not work for only pool fire vent

### ISSUE THREAD

**Issue by shinnosukenishiki** [firemodels/fds#4430]
Dear All, 

Please look an attached fds file.
Device timer does not work for only pool fire vent. 
Fire begins simultaneously with the start of calculation.
Is this something a bug or my misunderstanding?
I want to set pool fires on the ground level with different time fire start. 

Thank in advance for any help.

FDS version information:
 Current Date     : October 14, 2016  18:35:04
 Version          : FDS 6.5.2
 Revision         : Git-r21-0-g4e9103f
 Revision Date    : Wed Aug 24 16:29:46 2016 -0400
 Compilation Date : Wed 08/24/2016  10:28 PM

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Windows\* OS

[Device.fds.txt](https://github.com/firemodels/fds/files/529284/Device.fds.txt)

**Comment by mcgratta** [comment]
Devices are meant to be used with features one can control, like the opening of a door or the ignition of a gas burner. A liquid pool of fuel is not something you can control. FDS automatically evaporates the fuel and burns it. It is not controllable with a device.

**Comment by drjfloyd** [comment]
Do we need to note this in the guide?  My first thought on this was that the logic for OPEN/CLOSE of vents would have kept the SURF where the pool VENT was to INERT until the DEVC activated.

**Comment by shinnosukenishiki** [comment]
Thanks your comment.
I will use HRRPUA with RAMP to mimic experiment.
