### ISSUE TITLE
WIND boundary development

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4435]
Kevin,
We are not out of the woods on the wind bc.  For the case we currently have in the guide, wind_example, the outflow at the end of the simulation is non-physical, even though the plots look fine.  See attached image.
![wind_example_0554](https://cloud.githubusercontent.com/assets/4418497/19456344/f317a8c8-948e-11e6-8fc9-f970f5be1b31.png)

I suggest we include into the verification guide this case:
Verification/Atmospheric_Effects/rotate_wind.fds

This case works fine for PERIODIC boundaries, but not for OPEN.  I can live with things not being perfect.  But the behavior we see in rotate_wind is the same that we see at the end of wind_example and it is not something we can live with.  Must fine a solution.

**Comment by mcgratta** [comment]
Yes, this was there all along. Couldn't come up with a way to get rid of it. I'll take another look, but I don't think it will be easy.

**Comment by rmcdermo** [comment]
Good news is that it seems to be just a time step issue.  If I set CFL_MAX=0.5 for the rotate_wind case it works with the WIND boundary conditions.  I'm rerunning wind_example now to see if that helps.

**Comment by rmcdermo** [comment]
Bad news... Same result with CFL_MAX=0.5 on wind_example.
![screen shot 2016-10-17 at 6 24 29 pm](https://cloud.githubusercontent.com/assets/4418497/19457966/101e2e94-9497-11e6-9b52-6d84ac967e91.png)

**Comment by mcgratta** [comment]
Merge with #4986

**Comment by mcgratta** [comment]
This problem is largely resolved. If something else pops up, let's start a new issue.
