### ISSUE TITLE
Questions about solid temperature.

### ISSUE THREAD

**Issue by jiminryu** [firemodels/fds#4437]
&HEAD CHID='insulated', TITLE='Hollow, insulated steel column gets hot'/
&TIME T_END=80.0/
&DUMP RENDER_FILE='insulated.ge1', DT_PL3D=10.0, WRITE_XYZ=.TRUE./
&MESH ID='Mesh', IJK=10,10,20, XB=2.3,3.3,0.0,1.0,0.0,2.0/
&DEVC ID='Temp', QUANTITY='TEMPERATURE', XYZ=2.29,0.5,1 ORIENTATION=0.01,0,0 /

&SURF ID='HOT',           TMP_FRONT=200.0,  /
&OBST ID='Obstruction #1', XB=2.3,2.3,0.0,1.0,0.0,2.0, SURF_ID='HOT',  / 

&VENT ID='Mesh Vent: Mesh [XMAX]', SURF_ID='OPEN', XB=3.3,3.3,0.0,1.0,0.0,2.0/ 
&VENT ID='Mesh Vent: Mesh [YMIN]', SURF_ID='OPEN', XB=2.3,3.3,0.0,0.0,0.0,2.0/ 
&VENT ID='Mesh Vent: Mesh [YMAX]', SURF_ID='OPEN', XB=2.3,3.3,1.0,1.0,0.0,2.0/ 
&VENT ID='Mesh Vent: Mesh [ZMIN]', SURF_ID='OPEN', XB=2.3,3.3,0.0,1.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh [ZMAX]', SURF_ID='OPEN', XB=2.3,3.3,0.0,1.0,2.0,2.0/ 

&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBX=2.3/
&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBX=3.0/
&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBY=0.5/

&TAIL /

Left wall was set up 200 degree. But left wall changes over time.  I want only left wall to 200 degree at 0s. This input file 20 degree at 0s.  Plz tell me how to set.

at 0s
![image](https://cloud.githubusercontent.com/assets/22901804/19464612/c5d0a3c4-9538-11e6-951c-56880536f900.png)

at 80s
![image](https://cloud.githubusercontent.com/assets/22901804/19464625/d93b04f4-9538-11e6-947c-2e173beb40c4.png)

Look!! left wall degree changes.

**Comment by drjfloyd** [comment]
See the User's Guide Section 10.1.  

You need to set TAU_T=0.

**Comment by jiminryu** [comment]
I did that.  Unfortunately, I have not solved the problem. There is no change.

&SURF ID='HOT',     TMP_FRONT=200.0 , TAU_T=0.0  /

**Comment by drjfloyd** [comment]
Try Making the OBST a VENT or changing the OBST XB so it is slightly inside
the MESH.

**Comment by jiminryu** [comment]
Not yet....
Left wall should be 200 degree at 0s. But it is default(20 degree) at 0s.

**Comment by rmcdermo** [comment]
If you are trying to get output for the wall temperature use

&DEVC ..., QUANTITY='WALL TEMPERATURE', IOR=1/

or

&BNDF QUANTITY='WALL TEMPERATURE' /

**Comment by jiminryu** [comment]
Thank you!! I confirmed 200 degree at devc of excel file. But left wall not be seen 200 degree at smokeview. Why is that??

**Comment by jiminryu** [comment]
oh!oh! I see!!!! I should click BNDF WALL TEMPERATURE. Thank you!!
