### ISSUE TITLE
users Guide, section 8.4.3, minor edit suggestion

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4438]
Morning,

The example is section 8.4.3 has a density and a thickness and a ramp. 

&MATL ID = 'stuff'
CONDUCTIVITY = 0.1
SPECIFIC_HEAT = 1.0
**DENSITY = 900.0 /**
&SURF ID = 'my surface'
COLOR = 'GREEN'
MATL_ID = 'stuff'
HRRPUA = 1000.
IGNITION_TEMPERATURE = 500.
RAMP_Q = 'fire_ramp'
**THICKNESS = 0.01 /**
**&RAMP ID='fire_ramp', T= 0.0, F=0.0 /
&RAMP ID='fire_ramp', T= 10.0, F=1.0 /
&RAMP ID='fire_ramp', T=310.0, F=1.0 /**

I think there are two competing things that will influence when the fire goes out on a cell by cell basis. The density and thickness will determine the amount of fuel which might have the fire going out due to a lack of fuel before the ramp runs its course. I think the example would be made clearer by  removing the thickness so that the only thing controlling the fire is the ramp.

Dave

**Comment by rmcdermo** [comment]
Hi Dave,
We'll take a look.

**Comment by mcgratta** [comment]
Yes, but we need the `THICKNESS` to perform the 1-D heat conduction calculation. I would guess that FDS will stop burning when the mass runs out. Have you seen this to be true?

**Comment by Dave-McGill** [comment]
No, but I also assume it to be true. There is a lot going on in that little bit of code.

The alternative would be to remove the ramp, so that the length of burning is clearly determined by the thickness.

On the other hand, I may just be overthinking this way too much. I think that example has been there for years, so it may not be a burning issue. (pun intended)

**Comment by mcgratta** [comment]
There might be a reason to want a non-linear ramp -- it's just that it will cut off when the fuel runs out. I think the example is OK because there is no ramp down in HRR, so the user is burning until the fuel runs out.

**Comment by Dave-McGill** [comment]
I was thinking you wanted to demonstrate the ramp, and thickness my short-circuit that. It's no big deal. I'll defer to your judgement.   :-)
