### ISSUE TITLE
TMP wave for isothermal HELIUM flow and CONSTANT_SPECIFIC_HEAT_RATIO=T

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4440]
Jason,
Marcos noticed that with the current code we do not get isothermal flow if we set CONSTANT_SPECIFIC_HEAT_RATIO=T for a simple HELIUM flow case (attached).  A bisect shows the culprit as

4a457e53d68f6e4f294bfc6eff32ecbba9ca02ca is the first bad commit
commit 4a457e53d68f6e4f294bfc6eff32ecbba9ca02ca
Author: drjfloyd drjfloyd@gmail.com
Date:   Tue Dec 29 14:03:41 2015 -0500

```
FDS Source: Make H_S,alpha array consistent with notes.
```

Note that this will put you back into the old repo structure (pre-reorg).  The commit hash is the one from the new repo.

See if you can spot anything obvious.  I'll look too.  Thanks.
[tube_helium.fds.txt](https://github.com/firemodels/fds/files/541898/tube_helium.fds.txt)

**Comment by drjfloyd** [comment]
Making sure we are seeing the same thing. You are getting the following which follows the helium wave front from the inlet to the outlet and then goes back to 20 C.

![tube_helium_0040](https://cloud.githubusercontent.com/assets/12799217/19563989/067fc602-96b0-11e6-92f3-48438b4c02b2.png)

**Comment by rmcdermo** [comment]
Correct.  If you set CONST_GAMMA=F (our default) then you see no error.

**Comment by rmcdermo** [comment]
My memory is fuzzy as to why you had to make the change you made.  I do remember that it was to fix some other problem, though.  Whack-a-mole.  I will add this case to verification guide so at least we will not get bitten again.

**Comment by drjfloyd** [comment]
I think this was in the midst of getting fire.f90 to reproduce Canterra results and you observed we weren't consistent with what was in FDS vs. the definition in the divergence derivation in the tech guide.

**Comment by rmcdermo** [comment]
One curious thing is that it seems that the slice of ENTHALPY is perfectly constant and uniform, as it should be for CONST_GAMMA.

**Comment by drjfloyd** [comment]
The values being computed in read.f90 for specific heat, average specific heat, and sensible enthalpy agree with values I compute by hand. 

If I change the gas to PROPANE the error gets much smaller and to HYDROGEN it gets larger (MW closer and further from air compared to HELIUM).

**Comment by rmcdermo** [comment]
OK, getting warmer... Have a look at Eq. (B.27) in Tech Guide.  The "correction" terms are not computed if CONST_GAMMA=T.  These terms are the u dot grad (rho h_s) term in the second line and ALL of the third line.

I can isolate the problem to the third line by computing those terms with CG=T.  This means that the culprit is the group of terms in parens.  We need to check that the h_s,a over cp T term adheres to the discussion in Sec. B.5

**Comment by drjfloyd** [comment]
I am not sure what you did.  Did you force one of the CG=T checks in divg.f90 to be true?

**Comment by drjfloyd** [comment]
In 3.3.5 we define

h_s = Integral(cp(T)dT,T0,T).

In B.5 we state
rho h_s = rho cp T where cp is constant.

However consider the case where T= T_ref and h_s by definition is 0. We get:  rho 0 = rho cp Tref

**Comment by rmcdermo** [comment]
Yes, I did this:

!CONST_GAMMA_IF_2: IF (.NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN

with corresponding comment on ENDIF.

**Comment by rmcdermo** [comment]
I think you are right that B.30 should be

rho h_s = rho cp (T-T0) = ...

But this just leads to (pbar - pbar0) (gamma/(gamma-1)), right?  This should be ok.

**Comment by drjfloyd** [comment]
The rho is the rho for the current temperature, that rho times T0 will not result in pbar0. It will be something like:

pbar (1-T0/T) gamma/(gamma-1)

**Comment by rmcdermo** [comment]
Yep.  I see the problem now.  I think we simply must compute this term with CG=T.

I will modify the code and correct the Tech Guide.  Thanks for the help!

**Comment by rmcdermo** [comment]
Wait... something is still wrong.  The key is eq. B.11.  We should not need to compute the (rho h_s) terms in B.11.  And I think ultimately the terms in the third line of B.27 come from the time derivative of (rho h_s).  I'll keep at it.

**Comment by drjfloyd** [comment]
rho h_s isn't constant as a function of temperature.

**Comment by marcosvanella** [comment]
Randy, are we missing the hs drho/dt term from B.21 in the time derivative d(rho hs)/dt of the divergence expression? That would be zero only at Tref.

**Comment by rmcdermo** [comment]
Jason,
I don't understand what you are saying.  Based on the discussion in Appendix B.5 (rho h_s) is constant and uniform if pbar is constant and uniform and c_p,a is given by B.29.  I agree that something is amiss with regard to the { h_s,a / cp T } term related to T0.  Also, even with a temperature variation, ENTHALPY slice is constant and uniform with CONST_GAMMA=T.

**Comment by drjfloyd** [comment]
Say we have two species. S1 has MW=10 and S2 has MW = 100.  We can determine the cp for each and then compute rho h and rho h_s for two different temperatures as shown below.  Note that rho h does not change with species or temperature but rho h_s changes with temperature.

![image](https://cloud.githubusercontent.com/assets/12799217/19574249/6f084a10-96d7-11e6-89dd-d4b3de177eec.png)

The output of ENTHALPY is h not h_s

**Comment by marcosvanella** [comment]
Hi Jason, so at constant pressure for a given mixture, the total enthalpy per unit volume does not change, regardless of temp or composition, when cp is constant?

**Comment by rmcdermo** [comment]
Yep.  I forgot that B.5 is just flat out wrong because you end up with the { rho(T) \* T0 } term.

**Comment by rmcdermo** [comment]
So, the next question is whether we want to keep CONSTANT_GAMMA around at all.  If we have to compute the third line in B.27 I do not see the point.

The only option would be to reference everything to zero, but it seems we've been down that road before and all kinds of problems crop up with regard to droplets, etc.

**Comment by drjfloyd** [comment]
Marcos, 

Yes for an ideal gas where the cp is determined using the specific heat ratio the total enthalpy does not change with temperature or composition.

**Comment by mcgratta** [comment]
Just weighing in -- let's keep CONSTANT_GAMMA because it's sometimes a handy diagnostic. It makes the enthalpy transport terms disappear in the divergence expression. Although we don't publicize it, for lots of smoke transport calcs, CONSTANT_GAMMA is a time saver.

**Comment by drjfloyd** [comment]
Kevin,  the issue is that we have discovered that some terms we thought disappeared do not when the reference temperature is not 0 K (we use the standard ref of 298.15 K).

I think as long as we indeed now have all the properties self consistent, it shouldn't matter what we do in terms of the internal reference temperature for h_sens. We just need to make sure that we correctly propagate it throughout the source as that reference temperature also impacts the computation of H_F for combustion.

**Comment by mcgratta** [comment]
Gotcha -- I think we once just assumed that h = cp*T. That makes the terms drop out.

**Comment by rmcdermo** [comment]
Jason,
If you feel reasonably confident you could set T_REF to 0 for CONSTANT_GAMMA and not break other things, then let's go ahead and do that.

**Comment by drjfloyd** [comment]
I can give it a shot.

**Comment by drjfloyd** [comment]
I think I have fixed this. The helium test case works and I did a case of a fire in a closed box and had the correct overall change in total enthalpy and pressure.

**Comment by rmcdermo** [comment]
Thanks.  I'll add the helium case to the verification guide.  I also want to add one with combustion and one with evaporation.

**Comment by rmcdermo** [comment]
Kevin,
The point behind my question is that CONSTANT_GAMMA, as currently
implemented, is not correct.  It does not make the terms in the sensible
enthalpy equation disappear.  You need a special hook to reference all the
SPEC H_S to T_REF=0 in order for the terms to go away.  That is not how H_S
is computed right now.

**Comment by rmcdermo** [comment]
That term cancels when you sub in B.22

**Comment by rmcdermo** [comment]
This seems to be working.  Reopen if something else needs to be done.
