### ISSUE TITLE
Different results between FDS 6.4.0 and FDS 6.5.1  

### ISSUE THREAD

**Issue by gsztar** [firemodels/fds#4444]
I have received totally different results for the same case file.  The FDS version is different only.
I have carried out calculations on Linux with OpenMPI 1.8.4. (4 cores) at one PC.
In my opinion there is a problem in FDS 6.5.1. with communication between meshes.  
[scen_1_1.txt](https://github.com/firemodels/fds/files/548009/scen_1_1.txt)

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
```
ERROR: SURF_ID Pozar not found for VENT 14, line number 236 (CHID: scene)
ERROR: SURF_ID Door does not exist (CHID: scene)
ERROR: SURF_ID Pozar not found for VENT 14, line number 236 (CHID: scene)
ERROR: SURF_ID Pozar not found for VENT 14, line number 236 (CHID: scene)
```

**Comment by gsztar** [comment]
Sorry, it is my mistake when I prepare file for issue tracker.
I have attached corrected file.
[scen_1_1.txt](https://github.com/firemodels/fds/files/548043/scen_1_1.txt)

**Comment by mcgratta** [comment]
I have run the case 300 s and it is still  running. I do not see anything that is obviously wrong. It appears that you have smoke and heat from a fire flowing into a hallway, and at the other end of the hallway you have cool air being pushed towards the fire room. The cool and hot gases meet somewhere in the middle. Much like two weather fronts colliding, I would think that the flow scenario is physically unstable, and it's hard to predict exactly what is going to happen. There are always going to be small differences in two different versions of the model, and these small differences may be enough to noticeably change the outcome of a case like this. 

Can you point to something specific that you think is not functioning properly? The flows from mesh to mesh appear to be good. I see no obvious discontinuities.

**Comment by gsztar** [comment]
OK. It will be easy to understand when the velocity of both flows will be enough high. 
Please look on pictures below. The border between light green and blue is a meshes border also.

This temperature from 6.5.1
![scen_1_1_0075](https://cloud.githubusercontent.com/assets/16048248/19660777/73b72da8-9a31-11e6-86b7-3d24daacb56c.png)
and this from 6.4.0
![scen_1_1_0075](https://cloud.githubusercontent.com/assets/16048248/19659810/a0701dae-9a2d-11e6-8d4c-6b9a280105b8.png)
In my opinion totally different temperature distributions.
The same for visibility (see below)
![visibility](https://cloud.githubusercontent.com/assets/16048248/19660211/27cff3e0-9a2f-11e6-8a46-87af1805b249.jpg).
And smoke
![smoke](https://cloud.githubusercontent.com/assets/16048248/19660487/510b97c2-9a30-11e6-9116-15737c619508.jpg)

And velocity vectors from 6.5.1
![scen_1_1_0041](https://cloud.githubusercontent.com/assets/16048248/19660937/07630766-9a32-11e6-8a51-237083eae44f.png)

**Comment by mcgratta** [comment]
I see the same results as you do with the latest version, 6.5.2, but I cannot explain it, other than it is related to the interface between two meshes. I suggest that you combine these two meshes into one, and use a large OBST to blank off the volume that is now outside of the computational domain. If this new combined mesh is substantially larger than the other three, perhaps break up this large mesh halfway down the hallway.

**Comment by gsztar** [comment]
Will this problem be solved in FDS 6.5.3?

**Comment by dy944533118** [comment]
Hello, I want to ask you that these time nodes are defined by yourself? Thank you.

&RAMP ID='Door_room_1_RAMP', T=59.75, F=1.0/
&RAMP ID='Door_room_1_RAMP', T=60.25, F=-1.0/
&RAMP ID='Door_room_1_RAMP', T=209.75, F=-1.0/
&RAMP ID='Door_room_1_RAMP', T=210.25, F=1.0/
&RAMP ID='Door_room_1_RAMP', T=299.75, F=1.0/
&RAMP ID='Door_room_1_RAMP', T=300.25, F=-1.0/
&RAMP ID='Door_room_1_RAMP', T=309.75, F=-1.0/
&RAMP ID='Door_room_1_RAMP', T=310.25, F=1.0/
&RAMP ID='Door_room_2_RAMP', T=59.75, F=1.0/
&RAMP ID='Door_room_2_RAMP', T=60.25, F=-1.0/
&RAMP ID='Door_room_2_RAMP', T=209.75, F=-1.0/
&RAMP ID='Door_room_2_RAMP', T=210.25, F=1.0/
&RAMP ID='Door_room_2_RAMP', T=299.75, F=1.0/
&RAMP ID='Door_room_2_RAMP', T=300.25, F=-1.0/
&RAMP ID='Transfer_RAMP', T=44.75, F=1.0/
&RAMP ID='Transfer_RAMP', T=45.25, F=-1.0/
&RAMP ID='Transfer_RAMP', T=59.25, F=-1.0/
&RAMP ID='Transfer_RAMP', T=59.75, F=1.0/
&RAMP ID='Transfer_RAMP', T=209.75, F=1.0/
&RAMP ID='Transfer_RAMP', T=210.25, F=-1.0/
&RAMP ID='Transfer_RAMP', T=314.75, F=-1.0/
&RAMP ID='Transfer_RAMP', T=315.25, F=1.0/
&RAMP ID='Transfer_RAMP', T=319.75, F=1.0/
&RAMP ID='Transfer_RAMP', T=320.25, F=-1.0/
&RAMP ID='Door_RAMP', T=59.25, F=1.0/
&RAMP ID='Door_RAMP', T=59.75, F=-1.0/
&RAMP ID='Door_RAMP', T=209.75, F=-1.0/
&RAMP ID='Door_RAMP', T=210.25, F=1.0/
&RAMP ID='Door_RAMP', T=314.75, F=1.0/
&RAMP ID='Door_RAMP', T=315.25, F=-1.0/
&RAMP ID='Door_RAMP', T=319.75, F=-1.0/
&RAMP ID='Door_RAMP', T=320.25, F=1.0/

**Comment by mcgratta** [comment]
I do not understand this question.

In answer to the question about whether the original problem will be fixed, the answer is no. The abnormality you are seeing appears to be due to inaccuracy at the interpolated boundary. In such cases, it is best to just use a different meshing scheme.
