### ISSUE TITLE
Overlapping holes with controls behave unusually.

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/fds#4451]
This may be a bug or my misunderstanding, but the way overlapping holes with CTRLs operate seems unintuitive.

When HOLEs overlap they remove the sum of the volume as you would expect. However, if you apply CTRLs to these holes, their behaviour inconsistent.

Attached is a test case which demonstrates this. It is a wall with two overlapping holes in it, each of which are controlled with time-based CTRLs. The two holes are arranged as shown in the image below. **A** and **C** are the areas unique to each hole, and **B** is where they overlap. Critically, Hole 1 is the first hole defined and Hole 2 is the second.

![holes](https://cloud.githubusercontent.com/assets/1982652/19714246/5122b1d2-9b98-11e6-83f3-58b2e8bdd921.png)

The behaviour is as follows:
- **P**: Both holes are deactivated, however, there is a hole cut through the wall where they overlap. That is, area **B** is cut away when there should be no hole at all.
- **Q**: Hole 1 is activated, Hole 2 is not. Hole 1 cuts through the wall, but only where it does not overlap with Hole 2. That is, area **A** is cut away only, rather than all of Hole 1 (**A**+**B**).
- **R**: Both holes are activated. Both holes cut through as expected.
- **S**: Hole 2 is activated, Hole 1 is not. Hole 2 cuts through as expected.

![timeline](https://cloud.githubusercontent.com/assets/1982652/19714493/762fa3a2-9b9a-11e6-97ab-af507c2a0de8.png)

This is dependant on the order in which the holes are defined (hence Q and S being different). Looking at the _ctrl.csv file it seems both CTRLs are activating correctly, but perhaps there is an error in the way it was specified.

I tested it with the following version of FDS:

```
 Fire Dynamics Simulator

 Current Date     : October 26, 2016  16:40:53
 Version          : FDS 6.5.0
 Revision         : Git-r14-0-gec73757
 Revision Date    : Wed Jun 22 17:26:26 2016 -0400
 Compilation Date : Wed 06/22/2016  09:31 PM

 MPI Enabled; Number of MPI Processes:     1
 OpenMP Enabled; Number of OpenMP Threads:   2

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Windows* OS
```

[OverlappingHOLEsWithCTRLS.fds.txt](https://github.com/firemodels/fds/files/552379/OverlappingHOLEsWithCTRLS.fds.txt)

**Comment by JakeOShannessy** [comment]
Note that this is not just a display issue with Smokeview. The attached test model includes a flow through the holes which is affected.

**Comment by rmcdermo** [comment]
Thanks, Jake.  We'll take a look.

**Comment by mcgratta** [comment]
I fixed the case. There was some problem regarding the control logic of the obstruction created in the overlap volume of the two HOLEs. 

Jason -- take a look at commit #4452 . I don't recognize some of the code in the region that I changed, in particular the logic behind "parent" control functions.

**Comment by drjfloyd** [comment]
If I take an OBST and put a HOLE through the center of it, FDS creates five OBST to replace the original OBST. One OBST to each side of the HOLE and one for the HOLE. If the HOLE is controlled, the OBST for the HOLE gets assigned the control function. 

If I now add a second HOLE that overlaps the first, FDS creates additional OBST lines to account for the new HOLE. That includes a new OBST for the overlap which will get assigned the control function for the second HOLE.  

An OBST can only have one control function assigned to it, so we will always have in the case of the overlap OBST having only one control (either for HOLE 1 or HOLE 2, right now we do HOLE 2).  

Regarding the initial report:

The reported behavior for P is not the correct behavior, the overlap should be solid. 
Behavior Q,R, and S are as I would expect.  
Q - Removing HOLE 1 should take out all of HOLE 1 except the overlap as that OBST is controlled by HOLE 2.  
R - Removing both HOLEs should remove all areas
S - Removing HOLE2 should remove all of HOLE 1 including the overlap as that OBST is controlled by HOLE 2.  

Regarding the logic. That bit was added 8/28/12 to fix a case where there was an OBST that was hidden that had a HOLE that was off.  With your fix a case similar to the one that spawned the change (below) no longer works.  The HOLE now appears when the OBST does, whereas before it appeared when the HOLE timer activated.  Trying to account for all possible permutations of overlapping holes and obstructions could get tricky. Is this a case where we should just prevent an overlap?

&HEAD CHID='simple', TITLE='simple test' /
&MESH IJK=16,16,16, XB=-2,2,-2,2,-2,2 /
&TIME T_END=6./
&RADI RADIATION=.FALSE. /
&OBST XB = -1.5,1.5,-1.5,1.5,-0.5,0.5,DEVC_ID='TIMER1'/
&HOLE XB = -0.5,0.5,-0.5,0.5,-0.5,0.5,DEVC_ID='TIMER2'/
&DEVC XYZ=0,0,0,QUANTITY='TIME',SETPOINT=2,ID='TIMER1'/
&DEVC XYZ=0,0,0,QUANTITY='TIME',SETPOINT=4,ID='TIMER2'/
&SLCF QUANTITY='TEMPERATURE',PBZ=2/
&TAIL /

**Comment by mcgratta** [comment]
Do you mean that we should eliminate cases where there is a "parent" controller? Or in other words, if two holes overlap, they cannot have individual controllers.

**Comment by drjfloyd** [comment]
Should we allow two HOLEs were at least one is controlled to overlap?  The parent case of an OBST and a HOLE worked with the prior source.

**Comment by mcgratta** [comment]
Yes, if that helps the logic. The problem case posted here should cause an error because it is not well defined.

**Comment by drjfloyd** [comment]
I added a check for overlapping and controlled holes.

**Comment by mcgratta** [comment]
OK, thanks. I see that this case is now flagged with an error.
