### ISSUE TITLE
Flue gas leak

### ISSUE THREAD

**Issue by dy944533118** [firemodels/fds#4461]
I model a tunnel fire as you can see from attached input datum and pictures. Fire occurred in the middle of the tunnel. From 230 seconds, the smoke spread through the walls into the external of the tunnel. I check the the model again and again and I am sure that the model is airtight except for both ends of the tunnel, so I do not understand what can cause it? Please help me. I use the version FDS6.5.2
![111](https://cloud.githubusercontent.com/assets/19992906/19807769/3af7911c-9d54-11e6-8cc7-c649fc12b0d6.png)
![222](https://cloud.githubusercontent.com/assets/19992906/19807880/b374da82-9d54-11e6-83f0-323c2d87787b.png)

**Comment by rmcdermo** [comment]
You are seeing a well-known problem with immersed boundary methods called velocity penetration error.  To minimize this error, it is better if you at least have one cell for an obstruction (add THICKEN=T to OBST).  You can also decrease your velocity tolerance on the PRES line, VELOCITY_TOLERANCE=...  This is discussed in the user guide.

**Comment by dy944533118** [comment]
You mean I build two layers for the tunnel then the problem can be solved?

**Comment by rmcdermo** [comment]
Read Sec. 6.6.1 of the user guide.  As I said before, if you add THICKEN=T to your OBST, it will force FDS to use at least one grid cell.  This will _help_, not _fix_, the problem.

**Comment by dy944533118** [comment]
OK, thank you
