### ISSUE TITLE
CFAST vs FDS handling of N in the fuel

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#4463]
CFAST assumes N in the fuel becomes HCN.
In FDS, we have assumed (going back to v2) that the N becomes N2.

For user's doing work were one starts with CFAST for screening and then moves to FDS as needed this creates a possible inconsistency in how one would specify a fuel in order to obtain both the correct HoC and a plausible set of products and EPUMO2.  

For example:
C1H2N with a 10 % soot yield would be an invalid fuel in CFAST as the 1 C would go with the 1 N to HCN leaving no C for soot.
In FDS the N goes to N2 leaving all of the C available to make 10 % soot.

Should we (CFAST and FDS) decide upon a common approach for how N in the fuel is handled and then follow that approach in both codes?

**Comment by mcgratta** [comment]
Yes -- whichever way you think best. Work with Rick P.

**Comment by drjfloyd** [comment]
@rpeacoc please review the initial post

Is there a technical basis for the assumption the all nitrogen in the fuel goes to HCN?  I found this paper (http://www.iafss.org/publications/fss/9/1117/view) which suggests that very little N goes to HCN for well ventilated fires.

**Comment by rpeacoc** [comment]
There is no technical basis.  It's just an assumption that all the N goes to HCN and all Cl goes to HCl (that makes the stoichometry algebra work out easily).  If the conversion isn't 100 %, you'd just specify a smaller number for either the N or Cl in the fuel. Either way, it's using up some H and C for HCN and some H for HCl.  

How does FDS handle generation of HCN since the N is assumed to go to N2? If we teak things in CFAST, we do want to be as consistent as possible with FDS. At a minimum, we need to check for a consistent fuel specification.

**Comment by drjfloyd** [comment]
FDS assumes it all goes to N2 which is what the referenced paper indicates happens. It shows conversion yields (atom fraction of fuel N going to HCN) for well ventilated fires are very small.

A typical FPE using CFAST or FDS, goes to the SFPE handbook or similar reference to get fuel chemistry. If that says C2H1N, then that is what the user will put in along with the handbook HoC. Assuming all the N goes to HCN for a well ventilated fire does not seem justified as a base assumption.  Additionally, changing the fuel chemistry to remove N means the HoC might get significantly out of whack with the fact that EPUMO2 for most fuels sits near 13000 kJ/kg O2 consumed.  If the EPUMO2 based on HoC and fuel chemistry is very different, then one can get strange temperature behavior.

If HCN formation is to be kept, I think it should be via a species yield like CO and soot and probably should default it to zero (e.g. if the user wants to use HCN for a tenability calculation then they need to justify the production amounts).

**Comment by rpeacoc** [comment]
So, IF we keep the ability in CFAST to produce HCN and HCl, perhaps a way forward that is somewhat consistent with FDS would be to separate the yield of HCN and HCl from the fuel molecule.  To produce HCN, say, you'd need some nitrogen in the fuel and a user-input for the yield of HCN from the fuel We'd have to check to make sure there's enough carbon for soot and HCN and that there's enough nitrogen in the fuel to produce the requested yield.  Any leftover nitrogen would go to N2.  

We could use a similar scheme for HCl that might end up creating Cl2, but unlike N2, CL2 is highly reactive and would like go to HCl anyway.  

Thoughts?  

At this point, perhaps this should be a CFAST topic.

**Comment by mcgratta** [comment]
Sounds good to me. I think FDS will stay as is, since this is what the user has to do now, i.e. decide what to do with everything. I think this is a CFAST issue.

**Comment by drjfloyd** [comment]
If CFAST moves to an HCN yield input, is this something we should add as an option for simple chemistry (Y_HCN), or at that point do we just leave it up to the user to specify the full reaction?

**Comment by mcgratta** [comment]
Slippery slope - we'd have to do this with Cl too.

**Comment by drjfloyd** [comment]
True.  I'll close this issue then with the conclusion that nothing needs to be done in FDS.
