### ISSUE TITLE
Changing gravity vectors turns model in smokeview upside down

### ISSUE THREAD

**Issue by Jonnawest** [firemodels/fds#4478]
Hello!

I followed the method for changing the gravity vectors in the FDS userguide, by giving the values of each of the gravity component vectors a value of 1,1,1, and then assigning a ramp for each of them, where the fraction is defined by the actual velocity value. 

However, it seems that doing this will turn the model in smokeview upside-down. I assume this is because I set a positive value of 1 for the Z-axis gravity component, and then it does not reckognize that I give a fraction of negative 9,81 from t=0 in the ramp. 

Might be an easy way to turn the model in smokeview back in the right orientation, but just rotating the model does not seem to work, and it is a bit annoying, so I thought I would report it in.

Best regards

Jonnawest

**Comment by mcgratta** [comment]
Open the `.smv` file with a text editor, and look for `GVEC`

```
GVEC
      0.00000      0.00000     -9.80665
```

The lines here are what are normally written by FDS when the user has not set `GVEC`. If you don't want Smokeview to rotate the scene, just change the values appropriately.

**Comment by Jonnawest** [comment]
K thanks, that is a nice quick-fix to the problem!

**Comment by mcgratta** [comment]
Wish they were all that easy!

**Comment by gforney** [comment]
Think there is an option in smokeview to ignore gvec option ( or there will
be) . I'll check when I get back.

**Comment by hrmechengr** [comment]
Hello!

If I have an angled situation just like how it is shown by the template in FDS manual,

&MISC GVEC=1.,0.,1., RAMP_GX='x-ramp', RAMP_GZ='z-ramp' /
&RAMP ID='x-ramp', X= 0., F=0.0 /
&RAMP ID='x-ramp', X= 50., F=0.0 /
&RAMP ID='x-ramp', X= 51., F=-0.49 /
&RAMP ID='x-ramp', X=100., F=-0.49 /
&RAMP ID='z-ramp', X= 0., F=-9.81 /
&RAMP ID='z-ramp', X= 50., F=-9.81 /
&RAMP ID='z-ramp', X= 51., F=-9.80 /
&RAMP ID='z-ramp', X=100., F=-9.80 /

How should I update the SMV file to reflect this scenario?

Best regards,
HR

**Comment by mcgratta** [comment]
The line above tells one how to manually change the .smv file.
