### ISSUE TITLE
Add RAMP functionality for FORCE_VECTOR

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4497]
Currently, RAMP may be applied to MEAN_FORCING, but not to FORCE_VECTOR.  The FORCE_VECTOR is often used in conjunction with the CORIOLIS_FORCE to generate geostrophic winds in outdoor flows.  Adding RAMP to FORCE_VECTOR will enable assimilation of pressure gradient data into FDS wind simulations.

**Comment by rmcdermo** [comment]
I have the RAMP implemented in my fork.  Please send me a simple test case (obviously sans ramp) that I can modify.  I do not have a feel for what the CORIOLIS_VECTOR, etc., should be off the top of my head.  Thanks.

**Comment by BradyElls** [comment]
Here is a simple case I have been running recently. Let me know if you need anything else. It would not let me upload a .fds file to .txt was the best option.

[forceflat.txt](https://github.com/firemodels/fds/files/593092/forceflat.txt)

**Comment by rmcdermo** [comment]
The code has been updated to include time ramp functionality for FORCE_VECTOR.  Here is an example, based on your test case:
[ramp_force.fds.txt](https://github.com/firemodels/fds/files/595985/ramp_force.fds.txt)

If you can compile the code, let me know if you have any problems.

**Comment by BradyElls** [comment]
Thank you very much, Randy. I am going on break soon, but I will try this code when I get back and let you know if there are any problems.

**Comment by rmcdermo** [comment]
Just added discussion to user guide.  Is this working ok for you?  I'd like to close the issue.  Thanks.

**Comment by BradyElls** [comment]
Sorry Randy, I was gone all of last week. I can try a quick case now, but I need to update my fds-smv folder first in order to update my computer's version of FDS to include your new ramping code, correct? I have done the process before but not in quite a while, do you mind refreshing my memory? I have already opened up my fds-smv folder using the Git Bash and run git remote update, but I feel like there is another command that I am forgetting. I thought it was git merge origin development but it says that's already up-to-date. Once I am up-to-date with FDS I will run a quick test with your .fds file and let you know. Thanks.

**Comment by mcgratta** [comment]
```
git remote update
git merge firemodels/master
```

**Comment by BradyElls** [comment]
git merge firemodels/master returns the message "not something we can merge".

**Comment by mcgratta** [comment]
This is what I typically see:
```
$ git remote update
Fetching origin
Fetching firemodels
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
From github.com:firemodels/fds
   ca85357..41f4bc8  master     -> firemodels/master

$ git merge firemodels/master
Updating ca85357..41f4bc8
Fast-forward
 Manuals/FDS_User_Guide/FDS_User_Guide.tex |   17 +++++++++++------
 1 files changed, 11 insertions(+), 6 deletions(-)
 mode change 100644 => 100755 Manuals/FDS_User_Guide/FDS_User_Guide.tex
```

**Comment by BradyElls** [comment]
git remote update shows me what you see. git merge firemodels/master shows me the message "not something we can merge". git merge origin/development and git merge firemodels/development (both of which were in my batch command history, so I assumed they were the commands I was supposed to use after git remote update was finished) tell me everything is up to date already.

**Comment by BradyElls** [comment]
My fds-smv folder is forked from firemodels/fds. is that the correct folder to fork?

**Comment by mcgratta** [comment]
We reorganized our repo a few months ago. We do not use fds-smv anymore. Instead, we have repos for each program, like fds, smv, etc. firemodels/fds is the correct folder to fork. Note that we no longer use `development` as the branch name. We now just use `master`.

**Comment by BradyElls** [comment]
fds-smv is just what I called my forked folder. Since my folder is the correct one to fork, then I have no idea why git merge firemodels/master is not working.

**Comment by BradyElls** [comment]
Does the branch I am in matter in this process? When I open up GitHub, is defaults to a "development" branch. Development also shows up in blue next to my current directory path in the Git Bash. Should I be somewhere else?

**Comment by mcgratta** [comment]
Since our reorganization, my branches all say `master`. Maybe this is why you cannot merge. Worse comes to worse, just blotto your forked repo and local clones, and fork and clone the repo again.

**Comment by BradyElls** [comment]
Probably best if I just redo it all. What do you mean by blotto?

**Comment by mcgratta** [comment]
Redo it all. We had to reorganize our single FDS-SMV repository because it got very large and there's a limit that GitHub imposes. The new fds repo can be cloned very quickly, unlike the old that required about 10 minutes.

**Comment by BradyElls** [comment]
Ok. I deleted my old fds-smv repository and forked and downloaded firemodels/fds again. Now, it shows me as being in the master branch and when I try git remote update then git merge firemodels/master and it shows everything as up-to-date. I will try Randy's code again now. Thank you for your help.

**Comment by BradyElls** [comment]
I tried Randy's code again with no luck. I re-downloaded FDS and SMV from the website prior to redoing my GitHub repo. The files in the FDS and SMV folders still shows as last being updated back in late August as opposed to much more recently when Randy updated FORCE_VECTOR. I am guessing that my FDS code is not updated correctly. Is this a problem with my GitHub repo? How do I update my FDS and SMV files to reflect Randy's update? Thank you.

**Comment by mcgratta** [comment]
What do you mean "re-downloaded FDS"? Aren't you compiling the latest code in your cloned fds GitHub repository?

**Comment by BradyElls** [comment]
I had never actually compiled the code before on my own computer. I had been using the repo for a different reason a few months ago. I will compile it, then try the code. Thank you.

**Comment by mcgratta** [comment]
OK, anything Randy added recently to the code will not show up in the released version for several months.

**Comment by BradyElls** [comment]
Randy, would it be too inconvenient of me to ask you to test ramp_force.fds? I do not have the code compiled, nor have I ever done it before with FDS. It seems like it would take too long for me to check your code on my end. The makefile suggests there are a few prerequisites that need to be fulfilled before I can run the make file, and between my other research tasks and my schoolwork this late in the semester, I do not know when I can get to the point of actually testing your code. Sorry and thank you.

**Comment by rmcdermo** [comment]
Brady,
That's fine.  Of course, I tested the code and it works for me.  The RAMP_FVX_T, etc., will be available with the next maintenance release.  Hopefully this will be out soon.  We had planned it to be out several weeks ago.  I will close this issue.  When the new code comes out test it and let me know if you see any problems.
