### ISSUE TITLE
Issue with output HRR in the circular vent

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#4500]
Using Third party such as Blender to create circular burner  is hard to control its HRR output, since it consists of group of seperate vents. I tried to work using the example provided within the examples of FDS, but however it doesn't seems to work ( or it's me whose missing something).
Could you please verify the simple file inserted here. 
Many thanks.

Kind regards,
Salah
[circular_burner.zip](https://github.com/firemodels/fds/files/602255/circular_burner.zip)

**Comment by mcgratta** [comment]
I'll take a look at the case tomorrow.

**Comment by sbenkorichi** [comment]
Kevin,
Many thanks.

Best regards,
Salah

**Comment by drjfloyd** [comment]
I started running the case you attached. When I plot the mass loss rate of the fuel I get the results below for the first 8 s. This seems to be following the RAMP you gave.  Are you seeing something different?


![image](https://cloud.githubusercontent.com/assets/12799217/20495274/65aad426-afee-11e6-99d1-64b8421f83bb.png)

**Comment by sbenkorichi** [comment]
Jason, 
Many thanks for the reply.
The HRRPUA I inserted was 1000 kw/m2 , which gives around 785 kw of HRR in that surface. However, in the output file, the maximum was only around 760 kw. Except that the vent is not perfectly equal to a circular surface. 

Kind Regards,
Salah

**Comment by mcgratta** [comment]
[circular_burner_hrr.pdf](https://github.com/firemodels/fds/files/604880/circular_burner_hrr.pdf)

This is the HRR I see. I would expect it might be a bit low, on average, because some of the flame escapes the computational domain. But the MLR plot above seems OK to me.

**Comment by sbenkorichi** [comment]
Kevin, thanks for the reply.
I tried to reduce the HRRPUA to 200 instead of 1000. I've got HRR=135 kw as maximum in the output file. If the burner is truly taken as a circular shape, then the surface would be r**2*pi . This would theoretically give around 157 kw. But the output is only 135 kw. Maybe it's because the time was short which didn't allow it to develop fully? Or just maybe me missing something.

Kind regards,
Salah

**Comment by mcgratta** [comment]
What output file are you referring to? If you plot the HRR vs Time in the _hrr.csv file from your original 1000 kW/m2 calculation, do you see the same plot as I have posted above? Do you see the same mass loss rate that Jason posted?

**Comment by sbenkorichi** [comment]
Yes absolutely, I've got similar curve of HRR vs time in the outputfile hrr.csv to yours. However, I reduced the  HRRPUA in the second case to 200 kw/m2 instead of 1000 kw/m2, so the flame wont escape the domain. By doing so, I couldnt get HRR in the output as I wanted it, there is always around 20-25 kw is missing, similar to 1000 kw/m2 case. So, I was wondering about whether does FDS count for that surface as truly circular, or just an approximation.  I hope the issue is clear now. 
Kind regards,
Salah

**Comment by mcgratta** [comment]
Integrate the HRR vs Time curve (i.e. compute the area under the curve), which will give you the total energy released in kJ. Then calculate the area under the MLR vs Time curve (resulting in kg) and multiply by the Heat of Combustion (kJ/kg) listed in the .out file. Are these two numbers the same?

**Comment by sbenkorichi** [comment]
Kevin,
Sorry for the lat reply, I've checked what you've just mentioned right now, and had roughly the same results. 667 vs 670.

**Comment by mcgratta** [comment]
OK, sounds like things are working OK.
