### ISSUE TITLE
WARNING: MPI_PROCESS set for MESH 2 and only one MPI process exists

### ISSUE THREAD

**Issue by mahdiehghazi** [firemodels/fds#4505]
Hi all,

I am a new FDS user and I intent to run FDS in parallel using MPI (MVAPICH2.2.0). I followed the instructions in FDS user's guide. So I run the installer script using a bash shell:
$ bash FDS_6.5.2-SMV_6.3.12_linux64.sh
and then
$source .bashrc_fds my_mpi_path
I run the fds file using the command:
$ mpirun -n 2 fds ./circular_burner.fds

I expect to run the program using two processes since I have two mesh in my fds file but I get the following error:
 WARNING: MPI_PROCESS set for MESH 3 and only one MPI process exists

Would you please let me know how can I solve this issue?

here is my fds file:

/**********************************/
&HEAD CHID='circular_burner', TITLE='Test the mass flow rate from a circular burner' /

&MESH IJK=6,3,6, XB= 1.1, 1.7, 3.9, 4.2, 1.2, 1.8, MPI_PROCESS=0 /
&MESH IJK=6,3,6, XB= 1.1 , 1.7, 3.9, 4.2, 1.8, 2.4, MPI_PROCESS=0 /
&MESH IJK=6,3,6, XB= 1.1 , 1.7, 4.2, 4.5, 0, 0.6, MPI_PROCESS=1 /
&MESH IJK=6,3,6, XB= 1.1, 1.7, 4.2, 4.5, 0.6, 1.2, MPI_PROCESS=1 /

&TIME T_END=20. /

&REAC FUEL='PROPANE', SOOT_YIELD=0.015 /

&SURF ID='BURNER', MASS_FLUX(1)=0.02, SPEC_ID(1)='PROPANE', TAU_MF(1)=0.01 /

&VENT XB=-0.6,0.6,-0.6,0.6,0,0, XYZ=0,0,0, RADIUS=0.5, SPREAD_RATE=0.05, COLOR='BLUE', SURF_ID='BURNER' /

&VENT MB='ZMAX',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/

&DUMP DT_HRR=0.1 /

&SLCF PBY=0.0, QUANTITY='TEMPERATURE' /

&TAIL /
/*******************************************/

Thanks,
Madia

**Comment by mcgratta** [comment]
We compiled the FDS linux executable using the Open MPI 1.8.4 libraries. I do not know if your flavor of MPI is appropriate. The error message 
```
WARNING: MPI_PROCESS set for MESH 3 and only one MPI process exists
```
is written by FDS and it indicates that it does not recognize your mpirun command. That is, it does not create 2 MPI processes. When FDS sees that there is only one MPI process, it issues the warning.

**Comment by mahdiehghazi** [comment]
Thanks for your reply. I ran the code with Open MPI 1.8.4 and it runs with no warnings/errors. 

The issue is that I have to run the code using MPICH or MVAPICH since I'm getting some profiling information from these MPI implementations. Do you know if there is any version of MPICH that can be used for running FDS?

Thanks,
Madia

**Comment by mcgratta** [comment]
If you want to use another kind of MPI, you should compile FDS and bind in the libraries accordingly. FDS is Fortran 2008 compliant, and we use MPI 1 and 2 routines. In short, build everything yourself. You can clone the FDS repository and use the makefiles that we have created for the different builds.

**Comment by mahdiehghazi** [comment]
I compiled FDS and it is working fine on multiple processes now. Thanks a lot for your help :)

Madia

**Comment by mcgratta** [comment]
Good, thanks for letting us know.
