### ISSUE TITLE
.out file properties

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#4511]
In the .out file we write properties at TMPA but label it 293 K.   This should be fixed.  Should we write at 293 K and not write TMPA, write both, or just write TMPA?  If we do write TMPA should we insure that it is writing in the proper numerical order with respect to the other values?

**Comment by mcgratta** [comment]
I think we should just write it out at TMPA. There's nothing particularly meaningful about 293 K.  I wouldn't worry about the order -- that would just add a lot of code for something very minor.

**Comment by drjfloyd** [comment]
OK. I'll get this done. Thanks for the input.

**Comment by drjfloyd** [comment]
done
