### ISSUE TITLE
Pressure zone leakage

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4513]
In section 9.3.2, the Users Guide states,

"The pressure zone leakage approach is intended to capture the bulk leakage that occurs through walls. This approach assumes that the amount of leaking gas is very small and that it will exchange sufficient heat as it moves through a wall to be at the same temperature as the wall surface."

I've always assumed this to be the case. With inert walls and using a default temperature slice file,  the temperature of the leaking gas appears to be 20C or the TMPA. I just noticed that if the upper range of the scale is reduced from 1000 C to 200 C, then the leaking gas is above ambient. See the attached files.

This isn't something that is going to keep me awake at night, but I'm a bit puzzled; Is this a bug, or an undocumented feature?

Thanks

Dave 

[leakage_zone.fds.txt](https://github.com/firemodels/fds/files/616551/leakage_zone.fds.txt)
![leakage_zone temp slice reduced scale](https://cloud.githubusercontent.com/assets/13259079/20671751/a0d6ed9c-b54c-11e6-8c74-22c8284efd4a.png)
![leakage_zone_ temp slice default scale](https://cloud.githubusercontent.com/assets/13259079/20671752/a0d99e0c-b54c-11e6-81b3-550abd0e9de8.png)

**Comment by mcgratta** [comment]
I think that passage from the User's Guide is dated. In FDS 6, leakage is done via a special kind of HVAC duct, one that is probably adiabatic. Jason, can you confirm?

**Comment by drjfloyd** [comment]
I will look into it.  The text in the Guide that Dave refers to is correct for the intent of the two types of leakage. It may be that there is an implementation error.

-The intent for bulk leakage (LEAK_PATH) was to have flow exiting the wall at the wall's temperature with the assumption that the flowrate is very small and heat will be transferred to bring it to the wall temperature.

-For localized leakage (using HVAC LEAK), the intent was to represent a specific small gap like a cracked open door not resolvable on the grid.  We allow the user to specify whether or not this happens, but default to the temperature being the wall temperature (e.g. be consistent with bulk leakage).

**Comment by drjfloyd** [comment]
The logic in HVAC_BC appears to be correct on this one.   We compute the species mass flux from the virtual duct for the leakage and then use the existing wall temperature to get density to compute the velocity from the total mass flux.  The Q_LEAK term is zero in divg.90.  I am not sure right now what is causing the temperature increase.

**Comment by drjfloyd** [comment]
Dave,  Sorry for taking so long to get to this.  bulk leakage averages all the species over the leak area and discharges it on the leakage side. At about 3 s the plume hits the ceiling and there is a tiny amount of unburned fuel. That fuel then leaks, is distributed all around the compartment, and burns raising the temperature slightly. One solution to this is to use INIT to set a different ignition temperature outside the leaking space.

**Comment by Dave-McGill** [comment]
Hi Jason,

That makes sense. thanks.
