### ISSUE TITLE
Autostop and temperature mutation

### ISSUE THREAD

**Issue by dy944533118** [firemodels/fds#4520]
Hello, I have two questions. 1: My case always break down automatically. Tip:STOP: Numerical Instability (as shown in picture 1). What's the reason? Or what can I do to improve this situation. 2: as shown in image 238.5s to 243s, I think the simulation of FDS is wrong because the temperature is unlikely to occur such a big mutation within 4.5 seconds. Please explain it. Thank you very much in advance.

![1](https://cloud.githubusercontent.com/assets/19992906/20796550/92882b08-b811-11e6-9549-4fda4b30ea7f.png)
![238 5s](https://cloud.githubusercontent.com/assets/19992906/20796548/92693b08-b811-11e6-85b3-df443d495d9e.png)
![240s](https://cloud.githubusercontent.com/assets/19992906/20796549/92751932-b811-11e6-85e8-b1c27cd8fec6.png)
![241 5](https://cloud.githubusercontent.com/assets/19992906/20796551/92a171c6-b811-11e6-9a1a-6b6656428d28.png)
![243](https://cloud.githubusercontent.com/assets/19992906/20796552/92abfef2-b811-11e6-9885-09d41c391a73.png)

**Comment by mcgratta** [comment]
My car would not start this morning. Can you tell me why?

Think about it -- your inquiry is just like mine. It is impossible for me to answer your question. So here is what I want you to do:

1. If you are not using the latest version of FDS, use it. We're not going to debug some older version.
2. Run another calculation that involves only one or two meshes where the instability occurs. 
3. If you still get an instability, check the FDS User's Guide for tips on what to do.

**Comment by dy944533118** [comment]
Hello McGratta, my case always break down during the 200 seconds to 250 seconds. I know the reason is that there is a big change of velocity or temperature. I calculated many examples, in which some will automatically collapse, and others will be no problems all the time. Generally speaking, problematic cases occupied a larger proportion. So I want to ask you whether the settings of my example are correct or suitable. How should I do to improve the situation? And you did not answer me the second question. Comparing four back images, I hold the view that the results of this simulation are very strange, may be wrong.

**Comment by mcgratta** [comment]
How can I know what your settings are? Even if you post your input file, it will be too large to debug. I gave you three suggestions. Have you followed them? Have you run your cases with the latest version? Have you run a calculation with a smaller number of meshes? Have you read the User's Guide?

**Comment by dy944533118** [comment]
Hello McGratta, thank you for your reply. I have followed your advice, but I still didn't find out the reason. What do you think that my case sometimes break down automatically? And you always avoid to answer me the second question. Can you explain it? Thanks.

**Comment by mcgratta** [comment]
No, I cannot explain it.

**Comment by dy944533118** [comment]
Ok, anyway, thank you.
