### ISSUE TITLE
Sprinkler activation causes forrtl: error (78): process killed (SIGTERM)

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4524]
Hi,

I've run a number of models over the years where sprinklers activate and freeze the HRR. The last was with FDS 6.1.1. I've been trying with 6.5.2 and the models crash shortly after activation of the sprinklers. 

I've attached a simple file. The controls have been removed. The HRR is big enough to activate the sprinklers, and it crashes with a _forrtl: error (78): process killed (SIGTERM)_ error.

Any ideas?

Thanks

Dave
[corner_minimal.fds.txt](https://github.com/firemodels/fds/files/628525/corner_minimal.fds.txt)

**Comment by drjfloyd** [comment]
I'll take a look

**Comment by Dave-McGill** [comment]
Hi Jason,

I've been trying various permutations of this. It appears to be related to the flow rate. With a flow rate of 1 l/min and 10 l/min it works. However some of the time the sprinklers activate around 35 s and the particles discharge for  only about 50 s, even though the simulation continues running for several hundred seconds until manually stopped.

I'm going to keep increasing the flow rate to see if there is a point at which it will crash when the sprinklers activate.

Dave

**Comment by drjfloyd** [comment]
Dave,. I tried your input with the last release on my PC and it died with
no error.  With the current source it ran, and I stopped it after 120 s. I
wasn't seeing any problems. The current source has a major overhaul to the
droplet evaporation so maybe that fixed it. Was there a flow rate that died
quickly that I can try?

**Comment by Dave-McGill** [comment]
Jason,

I'm running 6.5.2.

The original flow rate of 473 L/min. I assume that is why it died with the original input. The attached file has a flow rate of 473 L/min,  a 5 MW instant-on HRR, and the 4 closest sprinklers activate at 5 s. This should die quickly, but hasn't by 15 s. I'll leave it running. (I'm off to Home Depot.)





[corner_minimal.fds.txt](https://github.com/firemodels/fds/files/629540/corner_minimal.fds.txt)

**Comment by Dave-McGill** [comment]
It's up to 153 s, and hasn't crashed, which is surprising.

**Comment by Dave-McGill** [comment]
Jason,

I went back to the original 2.3 MW linear fire. It runs with a flowrate of 25 L/min, and crashes with a flowrate of 37.5 L/min. If there has been a major re-write of the droplet evapouration routine, then I think this qualifies as old news. As long as the new routine can handle the flowrate of multiple ESFR sprinklers (~473 L/min) then I don't think this warrants any more attention.

Dave

**Comment by Dave-McGill** [comment]
Jason,

I came across a job I'd worked on earlier this year with high volume sprinklers. It was run with FDS 6.4, and ran without a problem. I made a new test case and it ran fine with versions 6.4, 6.5, and 6.5.1. However, with 6.5.2 it crashes a few seconds after the sprinklers discharge. So something relevant changed between 6.5.1 and 6.5.2.

Can you run the new test case with the version under development (6.5.3 ?) to see if the problem is still there?

Thanks

Dave

[sprinkler_discharge_test.fds.txt](https://github.com/firemodels/fds/files/706634/sprinkler_discharge_test.fds.txt)

**Comment by Dave-McGill** [comment]
The test case runs with 6.5.3, so I'm closing this issue.

Thanks

**Comment by mcgratta** [comment]
Thanks, Dave.
