### ISSUE TITLE
Radiative heat flux gas

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#4525]
Hi,
I would really be thankful if you can help me with this issue.

I'm running pool fire with Karosene as a main fuel.
The problem that I'm having is that during the experiment, from around 2 min ( where the HRR got almost into the steady plato) untill 15 min, the heat flux measured at 1 m distance from the center of the pool. At height 1 m, the measured Heat flux was between 10 and 16 kw/m2 in general during that period of time. Whereas at height 2 m, the measured heat flux was around 4-6 kw/m2.
While using the last version, in all the run cases I tried, always, the heat flux at 2 m is higher than at 1 m, which were around 7 and 6 kw/m2 respectively.
I tried to increase the Number of Radiative Angles, however no big improvement was shown.
When I specify on the RADI line, RADIATIVE_FRACTION = 0.4, I receive the following error saying:
RADIATIVE_FRACTION is now specified on REAC. STOP: FDS was improperly set-up
( I changed the fuel type, similar error received. Not sure where am I getting wrong).
PS: In the sample case attached, the meshing is 0.1 m. I did also 0.05 m. But similar results were obtained.

The issues I'm having here are : 
1. Heat flux at 2 m is always higher than at 1 m height (which is the opposite case with the experiment).
2. In both cases (1m and 2 m height), I did not reach heat flux between 10-16 kw/m2.
3.  Error in using Radiative fraction.

Many thanks.

Kind regards,
Salah

[radiative heat flux gas.zip](https://github.com/firemodels/fds/files/628917/radiative.heat.flux.gas.zip)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
You are specifying two different modes of pyrolysis:
```
&MATL ID ='KEROSENE LIQUID',
	EMISSIVITY = 1.0,
	CONDUCTIVITY = .1150,
	DENSITY = 823,
	SPEC_ID = 'KEROSENE'
	NU_SPEC = .97,
	HEAT_OF_REACTION = 310,
	SPECIFIC_HEAT = 1.95,
	BOILING_TEMPERATURE = 225,
	COLOR = 'RED'/

&SURF ID = 'KEROSINE POOL',
	COLOR = 'RED',
	MATL_ID = 'KEROSENE LIQUID',
	THICKNESS = .1 ,
	HRRPUA=2080.0, /
```
You provide the burning rate explicitly using `HRRPUA` and implicitly using `BOILING_TEMPERATURE`. In the latter case, you are trying to PREDICT the burning rate. The next release of FDS will flag this as an error. I suggest you use `HRRPUA` first, using a measured burning rate. Then you can try predicting the burning rate using the `BOILING_TEMPERATURE`. Read the FDS User's Guide chapter on Simple and Complex Pyrolysis Models.

**Comment by sbenkorichi** [comment]
Hi Kevin,

Thanks alot for the correction.
I've just kept the simple pyrolysis model with the specified HRR. I just run the sample for around 5 minutes, in order to check the results. From the output file, the recorded radiative heat flux gas at the two location still giving the same discrepency with the experiments. I would at least expect the heat flux at 1 m be higher than 2 m height. I've attached the sample input file, and the output file of the devices. As for the heat release in the output it's matching with what I've indicated.
I would like to know if it's possible to improve the model prediction of the heat flux accordinly with the experiment.

Kind regards,
Salah
[radiative heat flux gas results.zip](https://github.com/firemodels/fds/files/629042/radiative.heat.flux.gas.results.zip)


![experiment of heat flux](https://cloud.githubusercontent.com/assets/20113030/20861502/c5213ebe-b989-11e6-8372-513be998c0ea.PNG)

**Comment by mcgratta** [comment]
You have an 800 kW fire. I would estimate its flame height to be 2.6 m. The fire in FDS is not going to lean in any direction, whereas the real fire might have. I don't know the details of the experiment, so I cannot comment further. One piece of advice -- when doing a validation study, don't just consider one experiment. Look at a range of test conditions and see if there are any noticeable trends. We get comments like this all the time -- "I run a fire experiments, why isn't FDS matching it exactly?"

**Comment by sbenkorichi** [comment]
Hi Kevin,

Well, in all the conducted experiments, similar results were obtained. i.e. always the heat flux at 1m is higher than 2 m. Yes, sometimes the flame might tilt, however the tests were conducted in a lab where there is no big influence of the wind speed. Whether, the distance from the source is 0.5m, 1m or even 1.5m always heat flux recorded at 1m height is higher than 2m. I dont know how it would be possible to calibrate the model, would it be fair to introduce the wind speed as an influential parameter in your opinion?

Kind regards,
Salah

**Comment by drjfloyd** [comment]
Made a simple test case with wall and gas rad gauges at symmetric locations.The wall is showing much higher than the gas. 

[rad.fds.txt](https://github.com/firemodels/fds/files/629216/rad.fds.txt)

**Comment by sbenkorichi** [comment]
Dr Jason,
Truely many thanks. That's it. I've run your sample, and I believe you were right. I've thought of this in the beginning but I said since the device of radiative heat flux gas is inserted, then I should go with it. But, it doesnt give the accurate results accordinly with the tests. On the other hand, using that small blocks helps also in reversing what radiative heat flux gas gave, which is at least going with the experiments (i.e. at 1m is heigher than 2m). And this should be the case anyway, because in the test, (check the joined image), a small wall was added to backup these exp devices.
Kevin, Jason, many thanks for your help and assitance.
I'm glad you made this place, so people like me could reach you easily.

Kind regards,
Salah
![device](https://cloud.githubusercontent.com/assets/20113030/20863434/ff7c47ce-b9c1-11e6-8901-5b7456ebded6.PNG)

**Comment by sbenkorichi** [comment]
Just for confirmation purposes, I've ramped the HRR, a very close results to the experiments was obtained, as shown in the attached image.
Many thanks for helping me to solve this issue.

Kind regards,
Salah
![rad](https://cloud.githubusercontent.com/assets/20113030/20863756/a6fecf34-b9cd-11e6-846b-e5cf3ac0a510.PNG)

**Comment by mcgratta** [comment]
Thanks for letting us know.

**Comment by drjfloyd** [comment]
The gas and wall don't agree. Shouldn't they?  They should be the same I
think.

**Comment by sbenkorichi** [comment]
I agree with Jason,
The radiative heat flux gas is not recording the heat properly. I just took the case of Jason and added devices at 0 , 3 , 3.5 m height. As you can seen in the attached results, total differences between the two devices. The device at the wall surface seems to be more reasonable. Notice how at 0 and 2 m height using the wall, the results are quite matching, conversily with gas device where at 0m height is very low compared to 2m which is taken as the peak. Let alone to differences in the intensity between the two devices.

Kind regards,
Salah 
[rad.fds.txt](https://github.com/firemodels/fds/files/629903/rad.fds.txt)

![wal vs gas devices](https://cloud.githubusercontent.com/assets/20113030/20869938/b4af20ea-ba75-11e6-9b3f-30761a1d3314.PNG)

**Comment by mcgratta** [comment]
I'll look into this.

**Comment by mcgratta** [comment]
Just figured it out. The device with `QUANTITY='RADIATIVE HEAT FLUX'` applies to a solid wall, which has one of six orientations indicated by `IOR`. The device with `QUANTITY='RADIATIVE HEAT FLUX GAS'` can have any orientation, as indicated by the real triplet `ORIENTATION=...` For example, instead of specifying `IOR=2` for the gas devices, you should use `ORIENTATION=0,1,0`. 

This will fix the problem, but I will add logic to the code to convert `IOR` to `ORIENTATION` in this situation.

**Comment by drjfloyd** [comment]
Good catch.  I had forgotten that detail.

**Comment by sbenkorichi** [comment]
Well spot Kevin,
Many thanks,

Kind regards,
Salah

**Comment by kamialiawan** [comment]
Hello Sir,
I'm working on code development of radiative heat flux in gas turbine engine.
If anyone of you already work on this kindly guide me.
Regards Kamran Ali

**Comment by rmcdermo** [comment]
I would just Google Gas Turbine LES.  The literature is vast.  I don't think FDS is the tool for this application.

**Comment by kamialiawan** [comment]
Thanks Sir
Can you guide me where I can find codes for my project

**Comment by rmcdermo** [comment]
Try [OpenFOAM](https://www.openfoam.com/).
