### ISSUE TITLE
jet fan source location and discharge velocity

### ISSUE THREAD

**Issue by fdsuser** [firemodels/fds#4530]
I have three cases with different jet fan source locations.
Each case has jet fan with 1 m^3/s volume flow and 0.04 m^2 of area.

case1: 0.2 m long jet fan source at the end of 1.0 m long shroud
case2: 1.0 m long jet fan source throughout 1.0 m long shroud
case3: 0.2 m long jet fan source in the middle of 1.0 m long shroud

I noticed the following problems with the runs:
-airflow rates at tunnel portals and intake air velocity of jet fan inlet section change with regards to the jet fan source location.
-jet fan discharge velocity indicates zero.
-jet fan intake velocity is a lot lower than the expected velocity which is 25 m/s.

**Comment by fdsuser** [comment]
[jet_fan_cases.zip](https://github.com/firemodels/fds/files/634745/jet_fan_cases.zip)

**Comment by rmcdermo** [comment]
Jason,
These are setup with HVAC.  Can you take a look?

**Comment by drjfloyd** [comment]
taking a look now.

**Comment by drjfloyd** [comment]
You have defined a jet fan consisting of two 0.4 m x 0.4 m VENTs connected by an 0.04 m duct with a volume flow of 1 m^3/s.  1 m^3/s / (0.4 m x 0.4 m) = 6.25 m/s at the VENTs and not 25 m/s (this speed is in the HVAC duct not in the FDS domain where your DEVC are).

DEVC snap to the nearest grid cell center. You have placed your DEVCs on the cell faces and both are snapping in the same direction which means one DEVC winds up in the jet fan OBST and one is in the gas. The one in the OBST sees 0 m/s.  The one in the gas is showing 6.25 m/s. Move the DEVCs slightly to be in the gas and they should both show similar results. Note with the low grid resolution, fan placement in the shroud will  have some effect as flow at the shroud face can diverge whereas flow within the shroud cannot.

The flow fields in the cases are not exactly identical.  The inlet and out flows for the jet fan vary slightly for an open shroud end vs. a closed shroud end.  Case 3 with open shroud both before and after the fan results in a slightly more collimated flow than cases 1 and 2.
