### ISSUE TITLE
Some SLCF files have stopped updating during the simulation

### ISSUE THREAD

**Issue by KateLM** [firemodels/fds#4537]
Hi, I'm running a fairly large model with a lot of slice files. The simulation is still running (at 12900secs), but I've noticed that some of the output slice files in the directory have stopped updating (at 10900secs). I've instructed output SL3D files to be dumped every 100secs. The largest file is 5.3GB but there are 33MB SLCF files not updating as well. I have 16GB of RAM on my computer and the files are being run off a 2TB external hard drive. Can anyone suggest what is happening here and how to fix it (without starting again)?

Thanks in advance!
Kate

**Comment by mcgratta** [comment]
This is just too much output.
