### ISSUE TITLE
Unknown Instability at 160s

### ISSUE THREAD

**Issue by kyleperkuhn** [firemodels/fds#4539]
We are still troubleshooting this case. It's a simple and quick simulation. With the mesh boundaries closed, we saw smoke filling the entire domain. With mesh boundaries opened, the smoke blows out through a side wall (see screenshot). In both models the walls have been thickened, but were not in the user's original file.

[2016-12-08_1151_001.zip](https://github.com/firemodels/fds/files/640200/2016-12-08_1151_001.zip)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I don't see the smoke, running FDS 6.5.2. What version are you using?

**Comment by drjfloyd** [comment]
The fire takes a while to get going.  TAU_Q~-300

I deleted that and get an program exception with both the release and the current version.

**Comment by mcgratta** [comment]
To the original poster -- why are you setting this?
```
LOCK_TIME_STEP=.TRUE.
```

**Comment by drjfloyd** [comment]
Missed that.  Remove that and everything seems to run fine.

**Comment by bwklein** [comment]
Missed the lock time step setting on initial review.   Thank you for noticing that, we will get back to the customer and find out the reason for that setting.

**Comment by mcgratta** [comment]
`LOCK_TIME_STEP` should never be used except for special diagnostic exercises. Locking the time step allows the CFL number to exceed 1, which will readily cause numerical instabilities. I will close this issue -- reopen if something else pops up.
