### ISSUE TITLE
Reading a *.prt5-file stops writing particles in the following time steps until simulation is finished

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#4547]
FDS 6.5.2
Git-r21-0-g4e9103f
SMV 6.2.5
OS WIN 7

Reading a *.prt5-file while the simulation is still running stops writing particles in the following time steps until simulation is finished (which can be a long time in bigger simulations). 

Loading the SLCF after FDS continued some more timesteps shows that the SLCF is written continously, but the particles are not updated until the simulation finished.

This should be no big problem, but the behaviour is unusal for FDS/SMV.

Please rename the attached file test_particles.txt to test_particles.fds 
[test_particles.txt](https://github.com/firemodels/fds/files/646281/test_particles.txt)

**Comment by mcgratta** [comment]
Glenn has addressed a few issues related to particle loading. This might be part of it. He'll take a look.

**Comment by boris-stock** [comment]
Kevin,

thanks for your fast response.

Boris

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
are you saying that if you read in a particle file with smokeview that from then on fds stops writing it out?  if so, does this still happen if you exit smokeview?

**Comment by boris-stock** [comment]
Glenn,

at least from the moment SMV reads the particle-file while FDS is still calculating, particles after the timestep are not loaded (nor viewed). Closing SMV, reopening and loading it again does not help. The timestep SMV opened particles is the last timestep particles move.
FDS has to finish the whole calculation to make particles after the timestep they were opened viewable again.

**Comment by gforney** [comment]
try erasing all files of the form casename.prt5.sz files.  see if that fixes the problem.  if it does that gives me  a clue of what to fix in smokeview.

**Comment by gforney** [comment]
also erase files of the form casename.prt5.hist

**Comment by boris-stock** [comment]
Erasing *.prt5.sz solves the problem.

**Comment by gforney** [comment]
OK, thanks. Need to re-examine logic for when to create .prt5.sz files

**Comment by gforney** [comment]
think this is a buffer flushing problem.
do whatever you do to reproduce the problem ie run a case then load a particle file in smokeview
now on the command line type
copy casename.prt5 xxx

where xxx can be any file name.  on my pc the .prt5 file is not updated until I trick windows into thinking the file needs to be updated.  hopefully this is a work around until we figure out how to fix this in the code.

**Comment by gforney** [comment]
we were not flushing particle files properly in fds.  should be fixed after you update your repo and rebuild fds.  otherwise you can apply the work around (copy .prt5 files to a dummy file) in the previous comment

**Comment by boris-stock** [comment]
Glenn,

thanks for your fast help.
I really appreciate.

Boris

**Comment by gforney** [comment]
thanks for getting back to us.  This was one of those cases where we wonder why the code ever worked!
glenn
