### ISSUE TITLE
Simulation stops when sprinklers activate

### ISSUE THREAD

**Issue by a-respighi** [firemodels/fds#4562]
Hi all, I'm trying to run a simulation with some trucks burning and some sprinklers above them, but when the simulation reaches the time when the sprinklers activate it stops with no error messages, and nothing is written to the .out file.
I already tried to activate only one sprinkler at a time, with no success (I didn't try to activate individually all the sprinkler because they are many).
So I tried to set up a smaller case, containing one only truck and with the mesh reduced to contain just that one truck and the 3 sprinklers above it, and I saw the problem remained.
I tried to run the simulation on different computers with both Windows and Linux and the result is the same.
The fds version is 6.5.2, revision Git-r21-0-g4e9103f, and openMPI is enabled.
I post here the simplified version with one truck, I hope it's not too complex.

&HEAD CHID='test_sprk_stop'/
&TIME T_END=3600.0/
&DUMP RENDER_FILE='test_sprk_stop.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=50.0/

&MESH ID='Mesh', IJK=112,20,41, XB=116.75,133.55,-0.05,2.95,0.0,5.9792/

&SPEC ID='WATER VAPOR'/

&PART ID='Water01',
      SPEC_ID='WATER VAPOR',
      DIAMETER=500.0,
      MONODISPERSE=.TRUE.,
      AGE=30.0,
      SAMPLING_FACTOR=1/

&REAC ID='POLYURETHANE_REAC',
      FYI='SFPE Handbook, GM27',
      FUEL='REAC_FUEL',
      C=1.0,
      H=1.7,
      O=0.3,
      N=0.08,
      CO_YIELD=0.042,
      SOOT_YIELD=0.198/

&PROP ID='Water Spray M15',
      PART_ID='Water01',
      PARTICLES_PER_SECOND=7000,
      FLOW_RATE=90.0,
      PARTICLE_VELOCITY=5.0,
      SPRAY_ANGLE=60.0,75.0/
&DEVC ID='SPRK_A4', PROP_ID='Water Spray M15', XYZ=119.7,1.65,5.0, QUANTITY='TIME', SETPOINT=120.0/
&DEVC ID='SPRK_B4', PROP_ID='Water Spray M15', XYZ=123.1,1.65,5.0, QUANTITY='TIME', SETPOINT=120.0/
&DEVC ID='SPRK_C4', PROP_ID='Water Spray M15', XYZ=126.6,1.65,5.0, QUANTITY='TIME', SETPOINT=120.0/
&DEVC ID='TIMER->OUT->OUT', QUANTITY='TIME', XYZ=116.75,-0.05,0.0, SETPOINT=20.0, INITIAL_STATE=.TRUE./

&MATL ID='Solid comb',
      SPECIFIC_HEAT=1.0,
      CONDUCTIVITY=0.1,
      DENSITY=110.0,
      HEAT_OF_COMBUSTION=8000.0/

&SURF ID='Comb surface',
      RGB=255.0,102.0,0.0,
      HRRPUA=1000.0,
      TAU_Q=-60.0,
      IGNITION_TEMPERATURE=380.0,
      BURN_AWAY=.TRUE.,
      BACKING='VOID',
      MATL_ID(1,1)='Solid comb',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=1.0/
&SURF ID='Burner02',
      COLOR='RED',
      HRRPUA=600.0/

&OBST ID='obst1', XB=117.05,123.05,0.25,2.65,0.0,1.02084, COLOR='BLACK', SURF_ID='Comb surface'/ 
&OBST ID='obst2', XB=117.05,119.45,0.25,2.65,1.02084,3.93752, RGB=0.0,10.0,204.0, SURF_ID='Comb surface'/ 
&OBST ID='obst3', XB=120.95,133.25,0.25,2.65,1.02084,3.93752, RGB=0.0,190.0,204.0, SURF_ID='Comb surface'/ 
&OBST ID='obst4', XB=128.6,131.6,0.25,2.65,0.0,1.02084, COLOR='BLACK', SURF_ID='Comb surface'/ 
&OBST ID='obst5', XB=120.5,120.95,0.4,2.5,3.06252,3.93752, COLOR='WHITE', SURF_ID='Comb surface'/ 
&OBST ID='Igniter', XB=120.95,121.4,1.15,1.6,0.437502,1.02084, PERMIT_HOLE=.FALSE., SURF_IDS='Burner02','INERT','INERT', DEVC_ID='TIMER->OUT->OUT'/ 

&HOLE ID='Hole', XB=120.95,121.4,0.85,2.05,0.437502,1.45834/ 

&VENT ID='Mesh Vent: Mesh [XMAX]', SURF_ID='OPEN', XB=133.55,133.55,-0.05,2.95,0.0,5.9792/ 
&VENT ID='Mesh Vent: Mesh [XMIN]', SURF_ID='OPEN', XB=116.75,116.75,-0.05,2.95,0.0,5.9792/ 
&VENT ID='Mesh Vent: Mesh [YMAX]', SURF_ID='OPEN', XB=116.75,133.55,2.95,2.95,0.0,5.9792/ 
&VENT ID='Mesh Vent: Mesh [YMIN]', SURF_ID='OPEN', XB=116.75,133.55,-0.05,-0.05,0.0,5.9792/ 

&BNDF QUANTITY='WALL TEMPERATURE'/

&SLCF QUANTITY='TEMPERATURE', PBX=127.0/

&TAIL /

Thank you in advance.

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
When does the calculation stop?

**Comment by a-respighi** [comment]
At 119 s and something. It takes about 4 hours to arrive there on our
workstations.

Il 19 Dic 2016 17:22, "Kevin McGrattan" <notifications@github.com> ha
scritto:

**Comment by mcgratta** [comment]
If you set the activation time to 10 s, does the calculation still stop?

**Comment by a-respighi** [comment]
First, the activation time was 420 and it stopped at 419 and something, so
I tried 120 and it stopped at 119.
I made also a try setting it to 20 and it stopped at 83.

Il 19 Dic 2016 17:51, "Kevin McGrattan" <notifications@github.com> ha
scritto:

**Comment by mcgratta** [comment]
I'm going to run the case with the latest working version of FDS.

**Comment by a-respighi** [comment]
Thank you

Il 19 Dic 2016 19:30, "Kevin McGrattan" <notifications@github.com> ha
scritto:

**Comment by drjfloyd** [comment]
Kevin,

It may be worth running with the new evaporation model (which we disabled in prep for the upcoming maintenance release). Set EVAP2=.TRUE. on MISC.

**Comment by mcgratta** [comment]
Will do

**Comment by mcgratta** [comment]
The case posted above runs with the latest source code (with and without the new evaporation routine), at least well beyond where it stops with the official 6.5.2 release. We are currently testing the new release and hope to have it out just past the holidays. I will keep the issue open until then.

**Comment by a-respighi** [comment]
Ok, thank you very much.
I will restart it with the new release as soon as you publish it.

2016-12-20 15:05 GMT+01:00 Kevin McGrattan <notifications@github.com>:

**Comment by Dave-McGill** [comment]
Gentlemen,

I just noticed this issue. I suspect it is the same problem as issue 4524.

Dave

**Comment by a-respighi** [comment]
Dave, I don't know if it's the same problem, because I tried reducing the
flow rate to very low levels and the problem remained.
Thank you anyway for your suggestion.

Andrea

2017-01-15 16:35 GMT+01:00 Dave-McGill <notifications@github.com>:

**Comment by Dave-McGill** [comment]
Hi Andrea,

I've started your small test case with FDS 6.5.1 to see what happens.

Dave

**Comment by Dave-McGill** [comment]
Andrea,

Your small case runs with 6.5.1. The sprinklers went off at 120, and it's now at ~250 s.

Dave

**Comment by a-respighi** [comment]
Thank you very much Dave.
We'll consider launching the whole scenario with version 6.5.1 while we
wait for the 6.5.3 ti be released.
Bye

Il 16 Gen 2017 14:11, "Dave-McGill" <notifications@github.com> ha scritto:

**Comment by mcgratta** [comment]
FDS 6.5.3 is released -- could you check this case again.

**Comment by a-respighi** [comment]
Thank you. I'll start the job with the new release tomorrow.

Il 23 Gen 2017 21:47, "Kevin McGrattan" <notifications@github.com> ha
scritto:

**Comment by mcgratta** [comment]
Any progress?

**Comment by a-respighi** [comment]
The complete simulation is running but it will take several days to reach
420 s when the sprinklers activate.
I'll inform you as soon as it gets there.
Thank you.


Il 01 Feb 2017 20:44, "Kevin McGrattan" <notifications@github.com> ha
scritto:

**Comment by mcgratta** [comment]
Any progress on this issue?

**Comment by a-respighi** [comment]
We're currently at 292 s.
Since the sprinklers should activate at 420 and we're advancing about 15
s/day, we should arrive at 420 in about 8.5 days.
I'll inform you as soon as we reach 420 s.
Thank you.

2017-02-15 17:49 GMT+01:00 Kevin McGrattan <notifications@github.com>:

**Comment by a-respighi** [comment]
The simulation is running, we reached 428 s now and the sprinklers activated regularly at 420 s.
I think the issue has been solved.
Thank you again for your support.

**Comment by mcgratta** [comment]
Thanks for letting me know.
