### ISSUE TITLE
PATH OBSCURATION over multiple meshes?

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#4571]
Hi guys. I have a large single enclosure domain which is split into multiple equally sized meshes. I want to output path obscuration to model beam detectors at various locations/orientations through the space. However PATH OBSCURATION devices cannot span meshes.

I know that there is mesh looping in dump.f90 (e.g. for Plot3D, iso surfaces, 3D smoke, slices, HRR, etc.) but none in the device output IND_SELECT select case. Is there a reason for this? Could we put a device in a mesh loop?

Failing this I can always post-process the output from multiple devices.

**Comment by drjfloyd** [comment]
Plot 3D, iso, slice, 3D smoke all have files that are written by each MPI process. No specific set of MPI calls is needed to share information before they can be written.

The HRR data is aggregated of the entirety of each mesh. No special processing is needed to determine how to split up the summation, it is done for the entire mesh. Coding this is trivial.

For DEVC like PATH OBSCURATION or integrated devices (e.g. STATISTICS='VOLUME INTEGRAL') there would be a good deal of effort on our part to figure out how to split the single DEVC into virtual devices over multiple processes and then we would need to add additional MPI calls to share that information. Our view is that we don't need to do this. The ability to have these devices over multiple meshes can be done with control functions. For example see Eq 15.7 in the User's Guide. You could use the MULTIPLY and SUBTRACT control functions to combine outputs from multiple DEVC and then output the value of that control function. No offline post processing would be needed.

**Comment by bmralph** [comment]
Thanks Jason. Cheers for the explanation. Good idea re control functions,
I'll go with that.

On 22 Dec 2016 12:44, "Jason Floyd" <notifications@github.com> wrote:

Plot 3D, iso, slice, 3D smoke all have files that are written by each MPI
process. No specific set of MPI calls is needed to share information before
they can be written.

The HRR data is aggregated of the entirety of each mesh. No special
processing is needed to determine how to split up the summation, it is done
for the entire mesh. Coding this is trivial.

For DEVC like PATH OBSCURATION or integrated devices (e.g.
STATISTICS='VOLUME INTEGRAL') there would be a good deal of effort on our
part to figure out how to split the single DEVC into virtual devices over
multiple processes and then we would need to add additional MPI calls to
share that information. Our view is that we don't need to do this. The
ability to have these devices over multiple meshes can be done with control
functions. For example see Eq 15.7 in the User's Guide. You could use the
MULTIPLY and SUBTRACT control functions to combine outputs from multiple
DEVC and then output the value of that control function. No offline post
processing would be needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/firemodels/fds/issues/4571#issuecomment-268792393>, or mute
the thread
