### ISSUE TITLE
Droplets Introduced within a Volume

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#4592]
Hi all,
Now i'm trying to run a simulation, in which droplets introduced within a Volume. And i want to see how will the liquid be distributed after hitting the wall.
But in my case, Liquid hits the wall and then stick to the wall. It is wrong. I can't find the error.
if someone can help me,I will be every thankful.
Her is the code.

&HEAD CHID='versuch3'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='versuch.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0/

&MESH ID='Mesh01', FYI='Computatinal Domain', IJK=120,90,120, XB=0.0,120.0,-10,80.0,0.0,120.0/

&MATL ID='Material01',
      SPECIFIC_HEAT=1.0,
      CONDUCTIVITY=0.1,
      DENSITY=500.0/

&SURF ID='Surface01',
      COLOR='GRAY 80',
      BACKING='VOID',
      MATL_ID(1,1)='Material01',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=1.0/

&OBST ID='Obstruction', XB=0.0,120.0,-10,80.0,0.0,2.0, SURF_ID='Surface01'/ 
&OBST ID='Target Wall', XB=30.0,90.0,0.0,20.0,2.0,42.0, PERMIT_HOLE=.FALSE., ALLOW_VENT=.FALSE., BNDF_OBST=.FALSE., REMOVABLE=.FALSE., BULK_DENSITY=500.0, SURF_ID='Surface01'/ 

&MISC PARTICLE_CFL=.TRUE. /

&RADI RADIATION=.FALSE./

&SPEC ID='WATER VAPOR'/
&PART ID='water drops', SPEC_ID='WATER VAPOR', DIAMETER=100., SAMPLING_FACTOR=1 /

&INIT PART_ID='water drops', XB=45,75,23,29,18,22,,UVW=0,-125,0,N_PARTICLES_PER_CELL=5,MASS_PER_VOLUME=1000/

&TAIL /

**Comment by mcgratta** [comment]
This is the expected behavior of FDS -- droplets stick to the wall.
