### ISSUE TITLE
queations about restart file

### ISSUE THREAD

**Issue by niki005** [firemodels/fds#4599]
Hi,everyone,
I tried to connect FDS with a data assimilation software.And I need to change the data of the restart file while I am doing the data assimilation.I was wandering what information is stored in a restart file and what should I do to change the data in the restart file.Besides,the restart file is written in  hexadecimal number and I found there are data of temperature and velocity and other varibles,however there is no data about location of the temperature or velocity.How could I know the location(x,y,z) of specific temperature since I want to change the temperature of some locations?Thank you very much.

**Comment by rmcdermo** [comment]
You would have to look at the FDS source code and see where we write out the LU_RESTART file.  All data is basically core dumped to the restart file.

This question would be better suited for the discussion forum.  At present a major overhaul of restart capabilities is not planned.  If someone finds specific bugs, we will address them here.
