### ISSUE TITLE
symmetry_test_2 Smokeview image not rendering

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4608]
Kevin,

Have a look at the latest verification guide on blaze.  Fig 7.2 has something wrong.  Maybe a change in Smokeview rendering script?

**Comment by gforney** [comment]
Can you attach an image and give more details of what is wrong

**Comment by gforney** [comment]
Oh, you mean there is no image at all?

**Comment by rmcdermo** [comment]
The image is created.  But it is all blue.  I do not think that is the intended image.   Not sure it is a Smokeview issue.

**Comment by mcgratta** [comment]
I think this is me. I set this up recently. I am trying to show a particular slice of temperature, but I think I am getting the t=0 slice. I'll fix.

**Comment by mcgratta** [comment]
The case runs 5 s. I set `SETTIMEVAL` to 5 in `Verification/Flow_Fields/symmetry_test_2.ssf`. I guess SMV didn't process it correctly. I reset it to 4.99 and things worked. Maybe 5 is beyond the actual FDS end time. I'll leave the case open for Glenn to look at when he returns.

**Comment by rmcdermo** [comment]
This was a problem in the past.  But I thought Glenn had fixed it.  Whack-a-mole.

**Comment by gforney** [comment]
If last time in dataset is T. Then smokeview should render out to T+DT
where DT is some small "grace" time interval. I would want though smokeview
to report an error if you ask for output at say T=60 s but data is only
available to say 10 s. I'll see what is going on when I get back. Flight
leaves at 4, snow arrives at 6!

**Comment by sbenkorichi** [comment]
Is this still considered as an issue or one has to just set the value with small number back.

**Comment by gforney** [comment]
smokeview outputs an error message if data is not available at the time of the requested render frame.  It renders the frame however.
