### ISSUE TITLE
Allow radiant flux gauge outside computational domain

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4622]
I am doing a validation study where the radiometer is well outside the fluid domain.  It is going to be a real pain in the neck to make the domain large enough to encompass the radiation gauge when I just need radiation flux.  Would it not be possible to do a view factor calculation from the nearest plane of the domain boundary to the radiation gauge?

**Comment by drjfloyd** [comment]
A simple view factor only works for a uniform radiator. To do this correctly for FDS, for every wall cell you would have to figure out which FDS radiation angle(s) would go the radiometer and sum those contributions.  This may not take as many mesh cells as you think.  Draw lines from the radiometer to the corners of the FDS mesh.  It is only cells within that pyramid which could transport radiation to the device. With multiple meshes you could quickly eliminate a lot of cells.

**Comment by rmcdermo** [comment]
Maybe this would be a good job for Andy Tam.  But I think it is worth doing.  For the UMD line burner case, I want to focus computer power on the flame, not the space to the radiometer.

**Comment by mcgratta** [comment]
Simo, do you think that there is a way to easily calculate the heat flux to a point outside the computational domain, based on ILW at OPEN boundaries?

**Comment by shostikk** [comment]
Something like this?
[distant_gauge.pdf](https://github.com/firemodels/fds/files/734727/distant_gauge.pdf)

**Comment by rmcdermo** [comment]
Simo,
This looks like what I am after!

**Comment by shostikk** [comment]
[distant_gauge.pdf](https://github.com/firemodels/fds/files/735439/distant_gauge.pdf)
I saw some mistakes already. Must check:
- q-vector on RHS should be n-vector (typo)
- I am not sure if we need D^l's at all. They are related to wall-normal dot-products, and here we could think each OPEN wall element as a point source with angular intensity distribution given by I^l's.

**Comment by mcgratta** [comment]
I think we do need D, or something like it. The dot product of n and p account for the orientation of the heat flux gauge. But what would account for the dot product of s and p?

Also, are you assuming that for each wall cell on the OPEN boundary, there is one vector that is within 1-2/N? That is, there is one ray that would intercept the heat flux gauge?

**Comment by shostikk** [comment]
Well, we'll see. 

But imagine each gas cell next to the OPEN boundary contains a point source that radiates at certain intensity in each direction. We must give weights based on the cells sizes (A's) but the orientation of the cell face should not matter. I can be wrong, of course.

Correct about the assumption. Delta function should just find the one angle within which our device happens to be. I do not know what could be a fast way of doing this. This way, the algorithm is going to be really slow.

**Comment by rmcdermo** [comment]
I would imagine the algorithm is to shoot a ray FROM the device TO the wall
cell.  That tells you immediately which solid angle you are interested in
for each cell face.  Then sum up each intensity dotted with the orientation
of the detector.  Maybe I am missing something.

**Comment by mcgratta** [comment]
I'm going to close this issue. The best course of action is to just add a fairly large, coarse grid to capture heat flux to distant targets. I don't have a better solution.
