### ISSUE TITLE
MULT does not work correctlt for VENTs

### ISSUE THREAD

**Issue by tstopi** [firemodels/fds#4624]
When the MESH line of a case contains MULT_ID (or perhaps when there are multiuple meshes, I didn't test) using MULT_ID on VENT line does not work as expected.  When there is only one mesh the MULT_ID on VENT line works correctly. Using MULT_ID on OBST line works correctly in all cases.

The followig input file demonstrates the problem: 
```
&HEAD CHID="TEST"/

&TIME T_END=0/

With this mesh everything works
c&MESH IJK=20,20,10,XB=-10,10,-10,10,0,10/

With this mesh setup some vents defined with MULT disappear. OBSTs defined with
either MESH setup work just fine.

&MESH IJK=10,10,5,XB=-10,0,-10,0,0,5,MULT_ID="MESH"/
&MULT ID="MESH",I_UPPER=1,J_UPPER=1,K_UPPER=1,DX=10,DY=10,DZ=5/

&VENT MB="XMAX",SURF_ID="OPEN"/
&VENT MB="XMIN",SURF_ID="OPEN"/
&VENT MB="YMAX",SURF_ID="OPEN"/
&VENT MB="YMIN",SURF_ID="OPEN"/


&SURF ID="BLOW", VEL=-4,COLOR="BLUE"/

This works with one mesh
c&VENT XB= -9,-7,-9,-7,10,10, IOR=-3,SURF_ID='BLOW',MULT_ID="MULT"/
This works also with mesh MULT
&OBST XB= -9,-7,-9,-7,10,10,SURF_ID='BLOW',MULT_ID="MULT"/

&MULT ID="MULT",DX=3,DY=3,I_UPPER=6,J_UPPER=6/
```
Using MULT_ID on MESH line and MULT_ID on OBST line
![obst_mult](https://cloud.githubusercontent.com/assets/6385107/21888410/dfd562be-d8cc-11e6-8b01-371477ea979b.png)
Using MULT_ID on VENT line:
![vent_mult](https://cloud.githubusercontent.com/assets/6385107/21888417/e249f0e6-d8cc-11e6-9bd9-75afd2121804.png)

```

 Fire Dynamics Simulator

 Current Date     : January 12, 2017  13:40:33
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-437-g0876746
 Revision Date    : Wed Jan 11 09:21:40 2017 -0500
 Compilation Date : Jan 12, 2017  13:32:34

 MPI Disabled
 OpenMP Enabled; Number of OpenMP Threads:  16

 Job TITLE        :
 Job ID string    : TEST

```

**Comment by rmcdermo** [comment]
Thanks, Topi.  We'll have a look asap.

**Comment by mcgratta** [comment]
I fixed this and committed to my forked repo. I will commit to the central repo once we release 6.5.3.

**Comment by mcgratta** [comment]
Topi -- this should be fixed in the latest official release. Could you check and then close the issue if fixed.
