### ISSUE TITLE
Evaporation Source Code

### ISSUE THREAD

**Issue by FPSSPF** [firemodels/fds#4639]
Dear all,

I would like to understand better how the evaporation model works to model the mass loss rate of liquid fuels. The model is used for droplets as well and is described in the section "7.2.4 Liquid Fuels " of the Technical reference guide. Could anyone indicate me where I can find the source code for that boundary condition??

Thank you in advance :) :) :)

**Comment by drjfloyd** [comment]
General discussions on FDS should be posted in the forum. The issue tracker is intended for bug reports or enhancements.  

Evaporation of liquid pools (e.g. defined with SURF and MATL) is with all the other wall boundary conditions in wall.f90
Evaporation of liquid droplets (e.g. defined with SPEC and PART) is with all the other particle phenomena in part.f90
