### ISSUE TITLE
HVAC mass transport conservation: make image filename consistent with case name

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4640]
Ben,
If you look at the cases HVAC_mass_transport_conservation in the verification guide, there are four images for three sections in the guide.  The figure label an case name become inconsistent for Fig. 13.16.  Can you please change these so that we have as image names:

HVAC_mass_transport_conservation_1a.png
HVAC_mass_transport_conservation_1b.png
HVAC_mass_transport_conservation_2.png (old 3)
HVAC_mass_transport_conservation_3.png (old 4)

Thanks!

**Comment by bmralph** [comment]
Should be address by pull request https://github.com/firemodels/fds/pull/4645. Cheers :gb:

**Comment by rmcdermo** [comment]
Looks good, thanks!
