### ISSUE TITLE
Temperature drop in tunnel

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#4661]
I'm trying to model a tunnel in cold flow with a multiscale approach as proposed in (https://groups.google.com/d/msg/fds-smv/GXRJYwbaUQA/PRsw47UizCgJ). The model is rather simple: a main tunnel's body with a jet fan which pushes the air and two portals, the different parts of the domain are linked with HVAC ducts (figure: model.png; input file: input_tunnel.fds.txt). 
The simulation runs smoothly without huge fluctuations (figure: vol_flow.png), but the temperature decreases in time , while I would expect it to be isothermal. I plot the temperature at the interface of the 3d and 1d models (figure: temperature.png). I tried to model the same case using a node at ambient conditions instead of an additional domain at the portals, but the simulation undergoes to large volume and pressure fluctuations (figure: vol_flow2.png). As well I tried to model the case without using the HVAC model and using some simple open at the portals of the tunnel and there is no temperature change. All the cases ran with FDS 6.5.2.
If you have any suggestion on how to solve the problem I will be pleased to listen to you advises.
Thanks for your help,
Matteo
![model](https://cloud.githubusercontent.com/assets/15084725/22146965/ded40f24-df06-11e6-99c4-23be72e7fe9c.png)
![vol_flow2](https://cloud.githubusercontent.com/assets/15084725/22147013/169eafea-df07-11e6-8fbe-43f9ff3e4981.png)
![vol_flow](https://cloud.githubusercontent.com/assets/15084725/22146809/4181ee12-df06-11e6-8849-f75d5c28a49d.png)
![temperature](https://cloud.githubusercontent.com/assets/15084725/22146810/418258d4-df06-11e6-970d-7247e29e98a8.png)
[input_tunnel.fds.txt](https://github.com/firemodels/fds/files/719126/input_tunnel.fds.txt)

**Comment by mcgratta** [comment]
We'll take a look at it.

**Comment by drjfloyd** [comment]
Your jet fan isn't going to act like a jet fan if you add a fire.  You will only inject air and not entrain smoke through the jet fan the way you have it defined now. Look at the jet_fan example for how to do this with HVAC components.

With HVAC_PRES_RELAX=1.0 on MISC your case seems to run fine with the current source.

**Comment by mpachera** [comment]
I tried to rerun the case changing the fan model and adding the option you suggested in the MISC line. The results unfortunately didn't improve and I still see the temperature drop, did you change some other parameters of the simulation?
I attach here the input file and the file.out with a picture of the temperature field.
[input_tunnel.fds.txt](https://github.com/firemodels/fds/files/721146/input_tunnel.fds.txt)
[multiscale_simple.out.txt](https://github.com/firemodels/fds/files/721143/multiscale_simple.out.txt)
![temperature_field](https://cloud.githubusercontent.com/assets/15084725/22174471/aaa0e8e2-dfdf-11e6-9025-11359051b2b8.png)

**Comment by drjfloyd** [comment]
Oops forgot to mention you also need to define a ZONE for the sealed
portion of the tunnel.
