### ISSUE TITLE
Color clash when drawing a boundary file

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4668]
I think this issue has come up before. Run this case and look at the boundary file. You will see the contour color clash with the obstruction color because the obstruction abuts the side of a mesh. If you move the obstruction, the problem goes away.  This is fairly low priority -- don't fuss too much with it because an easy workaround is to draw the boundary as outline.
```
&HEAD CHID='bndf' /
&MESH IJK=10,10,10, XB=-0.1,0.0,-0.05,0.05,0,0.1 /
&MESH IJK=10,10,10, XB= 0.0,0.1,-0.05,0.05,0,0.1 /
&TIME T_END=5. /
&SURF ID='HOT', TMP_FRONT=500 /
&OBST XB=-0.02,0.0,-0.05,0.05,0,0.1 /
&OBST XB= 0.02,0.04,-0.01,0.01,0.02,0.04, SURF_ID='HOT' /
&VENT PBX=-0.1, SURF_ID='OPEN' /
&VENT PBX= 0.1, SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /
&BNDF QUANTITY='NET HEAT FLUX', CELL_CENTERED=T /
&TAIL /
```

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
I've made some progress outputting boundary files on blockage surfaces that are adjacent to interior mesh boundaries.  Smokeview is now drawing everywhere it is supposed to (all blockage surfaces are now covered with boundary files) but smokeview is also now drawing in regions where it shouldn't ( region where two meshes are adjacent).   My guess is that fds is passing in the entire mesh face to the boundary file for two meshes that are adjacent.  How hard would it be to only pass in the region we are interested in?  I'll also look in smokeview to see how hard it would be to ignore this region.  If the attached images isn't clear, drop by and I"ll show you on my computer
![bndf_0032](https://cloud.githubusercontent.com/assets/12403014/22277260/23d7901c-e288-11e6-8e60-4fc623aada94.png)

**Comment by gforney** [comment]
think I fixed the problem.  I'll upload a smokeview for you to test tomorrow

![bndf_0043](https://cloud.githubusercontent.com/assets/12403014/22278487/d7735292-e291-11e6-863e-db365d523d78.png)

**Comment by mcgratta** [comment]
The new Smokeview works for me, thanks.

**Comment by gforney** [comment]
I assume you didn't you have trouble installing it (from any security settings)?

**Comment by mcgratta** [comment]
Nope, I just clicked on the file and it installed.
