### ISSUE TITLE
Implement Divergence Free Synthetic Eddy Method of Poletto

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4672]
To aid WUI modeling, Eric Mueller suggests adding the divergence free constraint to the SEM method.  Here is the reference.

Poletto R (2014) Divergence Free Development Of The Synthetic Eddy Method In Order To Improve Synthetic Turbulence For Embedded Les Simulations. PhD Thesis, The University of Manchester, School of Mechanical, Aerospace and Civil Engineering, Manchester, UK.

**Comment by rmcdermo** [comment]
@ericvmueller Do you still feel this is something we need?

**Comment by ericvmueller** [comment]
My feeling is no, at least not a high priority. I don't know how many people are using the SEM capability for the large scale simulations, and I'm not aware of any specific complaints with the current implementation. I can have a quick look at what I attempted before, but I'd be fine with closing this for now.

**Comment by rmcdermo** [comment]
Ok, thanks!
