### ISSUE TITLE
Variegation parameters definition  

### ISSUE THREAD

**Issue by AAbouali** [firemodels/fds#4677]
Hello 

I am having difficulties to define the meaning of the variegation parameters that are within the vege.f90 module, like VEGETATION_CDRAG and VEGETATION_SVRATIO, and many other 
I looked all over the documentation but didn't find clear enough information about it
any help please where I can find such a thing?

**Comment by mcgratta** [comment]
There is no documentation for the vegetation parameters in the current FDS manuals. We are currently working on this.

**Comment by drjfloyd** [comment]
Does Ruddy have access to this?  He is the one who wrote vege.f90.

**Comment by AAbouali** [comment]
Ok thank you, I looked actually to the source files and figured out most of it 
I still need just these: 
VEG_LSET_ROS_HEAD
TGA_ANALYSIS
VEGETATION_ARRHENIUS_DEGRAD
FIRELINE_MLR_MAX

**Comment by mcgratta** [comment]
Vegetation Level Set Rate of Spread, Head
Thermogravimetric Analysis
???
Fire Line Mass Loss Rate, max

I don't know if this helps. I am not familiar with those routines either.

**Comment by AAbouali** [comment]
Okay, thank you anyway for help
