### ISSUE TITLE
need to pass device before control in initialization

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#4680]
It looks like we aren't doing a device exchange before doing the first control function update in the initialization.  

The attached case is a beam detector split over meshes and it does not correctly compute the final control as it gets LATCHed out in the initialization. Controls operate on Mesh 1 and only the the device in Mesh 1 has its SMOOTHED_VALUE updated when the control routine is called the first time. The other devices still have their SMOOTHED_VALUE at -1E10 (we init to this so we can test to force SMOOTH_VALUE = INSTANT_VALUE on the first call to devices).

**Comment by mcgratta** [comment]
I don't see the case.

**Comment by drjfloyd** [comment]
[beamtest.fds.txt](https://github.com/firemodels/fds/files/733047/beamtest.fds.txt)

Sorry forgot to attach.

**Comment by mcgratta** [comment]
In both initialization and in each time step, we do

UPDATE_GLOBAL_OUTPUTS (which includes UPDATE_DEVICES)
UPDATE_CONTROLS
DUMP_GLOBAL_OUTPUTS (where DEVC quantities are exchanged)

So it appears that we do not exchange DEVC info before updating controls. Are you suggesting that we should in both initialization and during regular time steps?

**Comment by drjfloyd** [comment]
Yes.  Controls can be used to define flows through vents, etc and with devices not exchanged a control using devices not in mesh 1 can have a bad initial value.

**Comment by mcgratta** [comment]
OK, I think I need to break up `DUMP_GLOBAL_OUTPUTS` into 2 subroutines -- one that does the exchanges, and one that calls the dump routines. Then we can exchange between updating devices and updating controls.

**Comment by mcgratta** [comment]
Can you tell me what you expect the devc values to be, especially at t=0.

**Comment by drjfloyd** [comment]
At t=0
PAx should all be 0 (this is the percent obscuration per device)
PAxso are the result of the controls doing 100-PAx and should be 100 (this is the percent transmitted per device) 
PAmo is the output of a control that multiplies all the PAxs together along with 1E-10 and should be 1. (this is total transmitted fraction)
PAfo converts PAmo to the obscured fraction and should be 0

Once the calculation starts PAx will start to increase as smoke builds up from the fire, PAso and PAmo will start to decrease, and PAfo will increase until it exceeds 0.35 at which point the control function will trip and will stop being evaluated

**Comment by mcgratta** [comment]
I made changes to main.f90 so that device values are exchanged before controls are updated, but there still still seems to be a problem at t=0, possibly due to smoothing. But I can't figure out exactly what is happenings as I'm not familiar with the control routine. Could you grab this version of [main.f90](https://github.com/mcgratta/fds/commit/a4892b063e91c32877cbfdfd8d651b3c6e4754b8#diff-95a33688c1a638c4df3439f788eef300) and try it. I have not committed this to the central repo, only my fork. But I have run all the verification cases and it did not cause any errors.

**Comment by drjfloyd** [comment]
I see what the problem is.  PA1 - PA5 are the obscuration devices.  The rest of the items in devc.csv are control functions.  
We update the DEVC at t=0
We exchange the DEVC
We dump DEVC
We update the CTRL at t=0
We dump CTRL

So the DEVC that measure control would need another update cycle to reflect the value of the control function.   I guess if we wanted DEVC  that output controls to have the right value we would need another DEVC update and exchange before dumping the outputs.

**Comment by mcgratta** [comment]
Is there a way to know if this additional exchange is necessary?

**Comment by drjfloyd** [comment]
The extra exchange is only needed if there is a DEVC with quantity = CONTROL or CONTROL VALUE   We could set a flag in read if one is present.

**Comment by mcgratta** [comment]
I added the extra device exchange, but that does not solve the problem. First off, I'd like to see PAxso equal to 100 at t=0.  What needs to be done to make this happen? Wouldn't these controls see that the obscurations are all 0 at t=0?

**Comment by drjfloyd** [comment]
I'll look into it some more.  I had added debug to the control routine and verified that it was getting called with the 0 values which is what lead me to suggest another exchange.

**Comment by mcgratta** [comment]
I can commit my changes to main.f90 -- or can you work with it in my forked repo?

**Comment by drjfloyd** [comment]
I can get the file from your forked repo.

**Comment by drjfloyd** [comment]
Right now we:
update devices
exchange
do controls
dump devices

This means devices that measure controls aren't updated after we do controls.  We need another device update to do this.

**Comment by mcgratta** [comment]
Are you suggesting we do this?

update devices
exchange
do controls
exchange
dump devices

**Comment by drjfloyd** [comment]
Devices only see the value of a control function when they are updated. so I think we need two updates+exchanges.  We need to update devices and exchange so control functions see the correct device values. Then we need to exchange and update devices so devices see the correct control values. then we can write t=0

**Comment by mcgratta** [comment]
Is this what we want?

update device values
exchange device values
update control values
update device values only if there are devices with `QUANTITY='CONTROL VALUE'` ?? 
exchange device values only if there are devices with `CONTROL VALUE` ??
dump devices

**Comment by drjfloyd** [comment]
I think that is correct only both 'CONTROL VALUE' (numerical value of the function) and 'CONTROL' (logical state as -1 or 1)

**Comment by mcgratta** [comment]
Still working this. Turns out that what we need is this
update device values
exchange device values
update control values and at the end of this subroutine, update devices with `QUANTITY='CONTROL VALUE' or 'CONTROL'`
dump devices including the gathering of all device values to node 0

I noticed a line of code in `DUMP DEVICES` that had a similar effect of updating the `CONTROL VALUE` devices. But that is not needed now. 

I've only committed this to my forked repo. I'm testing it.

**Comment by mcgratta** [comment]
I committed my fix for this issue (#4707) . There are numerous minor changes I made to clean things up, but the key things are:
1. Break up DUMP_GLOBAL_OUTPUT into two pieces -- one that exchanges device values, and one that dumps.
2. At the end of the subroutine `UPDATE_CONTROLS`, we pass the control values to devices with `QUANTITY='CONTROL VALUE` or `CONTROL`.
Could you take a look at the changes to see if you see any potential trouble. I ran the verification cases and they all worked.

**Comment by drjfloyd** [comment]
Looks OK and the original case is now working correctly.
