### ISSUE TITLE
simulation of fire in motion

### ISSUE THREAD

**Issue by CHPA323** [firemodels/fds#4681]
Good day! wanted to clarify on the modelling of fire in motion as in the video - https://www.youtube.com/watch?v=8D3jhwas7tI ! how to implement this calculation? perhaps there is some sort of manual or Handbook?

**Comment by drjfloyd** [comment]
Questions on using FDS should be posted in the discussion forum.  We did
not do this work. If you want to know how it was done ask the person who
did it. That video was posted by its creator on the LinkedIn FDS-SMV group
(note that is not the official group that most users participate in).
