### ISSUE TITLE
Strange behavior of smoke in a multimesh tunnel

### ISSUE THREAD

**Issue by MrSiss** [firemodels/fds#4693]
Hello,

I modeled a multi mesh tunnel with a fire. When I run the simulation with smokeview I notice a strange behavior between meshes as you can see on these pictures 
![test_1_0405](https://cloud.githubusercontent.com/assets/24435527/22499402/df76b1b4-e85e-11e6-9114-7b0de0c59160.png)
![test_1_0412](https://cloud.githubusercontent.com/assets/24435527/22499403/df7a4e6e-e85e-11e6-8439-0fddc01d219d.png)
![test_1_0429](https://cloud.githubusercontent.com/assets/24435527/22499404/df7a982e-e85e-11e6-835f-0e604b58e991.png)
![test_1_0445](https://cloud.githubusercontent.com/assets/24435527/22499405/df7be170-e85e-11e6-959d-8add9f1a3030.png)

Please help me to understant this behavior and to solve this problem.

Thank you.

Version of FDS 6.5.2 (Revision : Git-r21-0-g4e9103f)

**Comment by mcgratta** [comment]
This is probably the result of the mesh interface. Does your mesh change resolution? Can you post a simple version of the case that demonstrates this effect.

**Comment by MrSiss** [comment]
Thanks Kevin !
Here is a simple version of the case and as you will see, there are another strange behavior around obstruction at the level of the ceiling (far from boundaries meshs, see picture below).
![picture](https://cloud.githubusercontent.com/assets/24435527/22515175/e94abbb6-e8a1-11e6-8902-ec211433af3a.jpg)

[Test3.txt](https://github.com/firemodels/fds/files/745394/Test3.txt)

Thank you.

**Comment by gforney** [comment]
looks like your blockages have gaps.  this could explain what you are seeing.  note, I used the scaling dialog box (menu: Dialogs>Window>Scaling ) to exaggerate the vertical direction by a factor of 10

![test3_0036](https://cloud.githubusercontent.com/assets/12403014/22515789/bac83e92-e871-11e6-8673-68d2c2a431dd.png)

**Comment by gforney** [comment]
also note I added the following lines to your test case

&DUMP NFRAMES=1800 DT_PL3D=360.0, DT_SL3D=1.0/
&SLCF XB=0.0,660.0,0.0,9.0,0.0,6.0, QUANTITY='TEMPERATURE',CELL_CENTERED=.TRUE. / 
&SLCF XB=0.0,660.0,0.0,9.0,0.0,6.0, QUANTITY='DENSITY',SPEC_ID='SOOT',CELL_CENTERED=.TRUE. / 
&SLCF XB=0.0,660.0,0.0,9.0,0.0,6.0, QUANTITY='TEMPERATURE',VECTOR=.TRUE. /

**Comment by gforney** [comment]
looked at it some more.  though your blockage gaps may cause some flow anomalies, what you are seeing is an artifact of how smokeview draws smoke near blockages.  by default it sets the opacity of the smoke to zero where the smoke is adjacent to a blockage (because the path length is zero).  You can change this behavior by changing the "Absorption adjusments" in the 3D Smoke dialog box to "None".

**Comment by mcgratta** [comment]
The tunnel is open only on one end:
```
&VENT XB=0.0,0.0,0.0,9,0.0,6 SURF_ID='OPEN' /
&VENT XB=1140,1140,0.0,8,0.0,5 SURF_ID='OPEN' /
```

```
&MESH IJK=180,9,6, XB=0,180,0,9,0,6 /
&MESH IJK=480,9,6, XB=180,660,0,9,0,6 /
```

Also, your grid is very coarse. Fix the input file, and use more cells in the span wise direction.

**Comment by MrSiss** [comment]
Indeed, my input file contained an error. Thank you Glenn for your advice.
