### ISSUE TITLE
Jet Fans angle

### ISSUE THREAD

**Issue by KellerJR** [firemodels/fds#4694]
Hi,

Is it possible to give an angle to the stream of the Jet Fans in FDS 6?
I know this was possible in FDS 5.
But that method doesn’t seem to work in FDS 6.

This is the method we used in FD5

![jet fan with angles](https://cloud.githubusercontent.com/assets/25477569/22501525/6bab9366-e869-11e6-9575-b8db26cce448.jpg)

**Comment by drjfloyd** [comment]
Please post questions on using FDS to the discussion forum (https://groups.google.com/forum/?fromgroups=&nomobile=true#!forum/fds-smv)

See the Louvered Vents section in the HVAC discussion in the User's Guide
