### ISSUE TITLE
FDS Crash with simple test model.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#4701]
Please see the attached FDS file for the test model.
[untitled.fds.txt](https://github.com/firemodels/fds/files/749036/untitled.fds.txt)

 Fire Dynamics Simulator
 Current Date     : February  2, 2017  13:54:00
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Fri 01/20/2017  09:11 PM
 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4
 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Windows* OS

**Error**
D:\Downloads\untitled>fds untitled.fds
 Mesh      1 is assigned to MPI Process      0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds.exe            00007FF63A8B12BE  MATH_FUNCTIONS_mp        1758  func.f90
fds.exe            00007FF63ACAB367  Unknown               Unknown  Unknown
fds.exe            00007FF63A66C1F5  MAIN__                    167  main.f90
fds.exe            00007FF63A66A8BE  Unknown               Unknown  Unknown
fds.exe            00007FF63ADBA840  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF85B438364  Unknown               Unknown  Unknown
ntdll.dll          00007FF85BB470D1  Unknown               Unknown  Unknown

![crash1](https://cloud.githubusercontent.com/assets/12104446/22570027/925343ac-e94e-11e6-8885-92f77c4d30a5.png)

**Comment by marcosvanella** [comment]
Hi Bryan, just to add to the discussion. I run your case with the latest repo version and debug mode, and find a divide by zero issue on the RAMPS data structure:

![screen shot 2017-02-02 at 5 08 15 pm](https://cloud.githubusercontent.com/assets/7450069/22570682/5f81d51c-e96a-11e6-82bc-5b7b4cb2dd06.png)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
This is a bug. In the last release, we had to add an intrinsic RAMP to deal with pressure and temperature stratification in the atmosphere. Because your z values on MESH are at or below zero, the ramp is not getting set up properly. This is something done internally -- the user doesn't specify the ramp. Add
```
&MISC STRATIFICATION=.FALSE. /
```
as a work-around.

**Comment by mcgratta** [comment]
I fixed this bug in the working code.
