### ISSUE TITLE
smallest domain size and grid size

### ISSUE THREAD

**Issue by QiangjunZhang** [firemodels/fds#4708]
Hi,

As I am dealing with tiny sample combustion modelling, the problem I faced is that the FDS will show error information 'Numerical Instability' when I use very small domain and grid size.

I have tried different combination of domain size and grid size, and found that:

The minimum grid size is 0.00001 m . 

I am wondering is this because the modelling fail to dealing with too small numbers, and caused computation error due to precision settings?

If that is the case, is there any chance that I can change the default unit from m to mm? or Precision?

Regards,
John

FDS 6.3.2
input

&HEAD CHID='Medium_PMMA50', TITLE='PMMA2d' /

&MESH IJK=10,1,10, XB=0,0.0001,0,1,0,0.0001, CYLINDRICAL=.TRUE./  

&TIME T_END=600. / 

&TAIL /

**Comment by rmcdermo** [comment]
https://github.com/MaCFP/macfp-db

**Comment by rmcdermo** [comment]
Oops... sorry, I was replying to the wrong email!

**Comment by mcgratta** [comment]
This test case runs for me with the latest version of FDS (6.5.3) on my linux machine.

**Comment by QiangjunZhang** [comment]
Hi, can you try this one with smaller grid size.
Thanks

&HEAD CHID='Medium_PMMA50', TITLE='PMMA2d' /

&MESH IJK=100,1,100, XB=0,0.0001,0,1,0,0.0001, CYLINDRICAL=.TRUE./  

&TIME T_END=600. / 

&TAIL /

**Comment by mcgratta** [comment]
Yes, this case fails. The smallest grid cells we have worked with are approximately 0.1 mm. FDS uses an explicit time marching scheme, and as the grid cells become smaller, the Von Neumann constraint

dt < dx^2/(6*nu)

makes the time step very very small. For this reason, we have not spent much time trying to get FDS to run for such small grids. You probably need to use some kind of implicit CFD scheme.

**Comment by QiangjunZhang** [comment]
Many thanks for your explain, Kevin.
I will study this.
Regards,
John
