### ISSUE TITLE
Added parameter for MULT?

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#4710]
I've been using `MULT` to define multiple meshes. When I define multiple meshes manually I typically set a `COLOR` for each mesh so I can quickly see where mesh interfaces are. This isn't possible when using `MULT`.

How about adding `DX_COLOR`, `DY_COLOR` and `DZ_COLOR` as parameters for `MULT` which would be net RGB values?

**Comment by mcgratta** [comment]
I'll see what can be done.

**Comment by mcgratta** [comment]
Here's an idea. We can designate `COLOR='RAINBOW'` to direct FDS to randomly generate RGB values for each mesh. You would not control the values, but you would get differently colored meshes. Is that OK?

**Comment by bmralph** [comment]
Good lateral thinking. Yes that meets my requirement. Thanks Kevin!

**Comment by mcgratta** [comment]
Commit #4715. Set `COLOR='RAINBOW'` to get random colors.

**Comment by mcgratta** [comment]
![junk_s0000](https://cloud.githubusercontent.com/assets/11333911/22796470/6af2cd8a-eec8-11e6-8538-6384597ce499.png)

Groovy!

**Comment by bwklein** [comment]
Looks like some old C64 graphics. :)

**Comment by bmralph** [comment]
I might use this in all my models from now on...
