### ISSUE TITLE
mpirun fails np > 2

### ISSUE THREAD

**Issue by firemist** [firemodels/fds#4714]
I have simplified this case to the minimum. It is just a repeating mesh to make 20 meshes. The time goes for 1 second, but without anything happening. Here are the conditions and what happens:

- If I run fds without mpirun [fds mid_mesh.fds], it does setup and runs, no problems
- If I run mpirun with np < 3 [mpirun -np 2 fds mid_mesh.fds], it does setup and runs, no problems
- If I run mpirun with np > 2 [mpirun -np 20 fds mid_mesh.fds], it gets through the first two parts of setup, but then has a segmentation fault [SIGSEGV 174] (fails after  Completed Initialization Step  2) 

I believe I'm running the latest version of fds (6.5.3) and a stable version of mpi (1.8.4) on a very large machine with plenty of resources, see attached info files. I would think that if I have enough resources to run -np 2, I should have enough resources to run -np 20 [I recognize that's not a strictly true statement, but I don't see any resource limits on this machine for this problem]. I have run similar and larger sized problems in the past without difficulty, but can't seem to resolve this issue. ulimits have been set to unlimited, see file. I can't seem to find anything that would indicate why I can't go above 2 processes and can't find any environment variable or other limit that would be causing a problem.

As you'll see in the file, it's very simple. I appreciate any insight you may be able to render in this problem. Thanks. I am running the directly downloaded binary for linux.

I have provided files about my environment. There are also .out files from successful runs. I've included .log files, which captures the output to STDERR/STDOUT from the runs. I have also included the base .fds file.

>Input file is just a few lines (it's also attached as a file):
&HEAD CHID='mid_mesh',TITLE='Middle sized domain, 20 meshes' /
&TIME T_BEGIN=0., T_END=1. / 
&MULT ID='REP_MESH_A', DXB=5.4075,5.4075,5.884,5.884,7.3152,7.3152,I_LOWER=0,I_UPPER=3,J_LOWER=0,J_UPPER=4,K_LOWER=0,K_UPPER=0 / REP_MESH_A
&MESH XB=-0.3,5.1075,-0.3,5.584,0,7.3152,IJK=59,54,75,MULT_ID='REP_MESH_A' / Mesh 1

>Failure output (obviously, a lot of lines omitted, but included in the attached file):
 Completed Initialization Step  1
 Completed Initialization Step  2
forrtl: severe (174): SIGSEGV, segmentation fault occurred

>Indication of using the current version and successful run output:
 Fire Dynamics Simulator

 Current Date     : February  8, 2017  18:23:33
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Jan 22, 2017  18:04:30

 MPI Enabled; Number of MPI Processes:          2
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Open MPI v1.8.4, package: Open MPI gforney@burn Distribution, ident: 1.8.4, repo rev: v1.8.3-330-g0344f04, Dec 19, 2014

 Job TITLE        : Middle sized domain, 20 meshes
 Job ID string    : mid_mesh

>Note on filenames: I appended .txt to everything in order to upload it. mpi00 means I just ran fds mid_mesh.fds and the other ones were mpirun with the number as the -np argument.

[ulimit.txt](https://github.com/firemodels/fds/files/761614/ulimit.txt)
[cpuinfo.txt](https://github.com/firemodels/fds/files/761616/cpuinfo.txt)
[envinfo.txt](https://github.com/firemodels/fds/files/761615/envinfo.txt)
[meminfo.txt](https://github.com/firemodels/fds/files/761617/meminfo.txt)
[mid_mesh.fds.txt](https://github.com/firemodels/fds/files/761636/mid_mesh.fds.txt)
[mid_mesh_mpi00.log.txt](https://github.com/firemodels/fds/files/761634/mid_mesh_mpi00.log.txt)
[mid_mesh_mpi00.out.txt](https://github.com/firemodels/fds/files/761635/mid_mesh_mpi00.out.txt)
[mid_mesh_mpi02.log.txt](https://github.com/firemodels/fds/files/761638/mid_mesh_mpi02.log.txt)
[mid_mesh_mpi02.out.txt](https://github.com/firemodels/fds/files/761639/mid_mesh_mpi02.out.txt)
[mid_mesh_mpi03.log.txt](https://github.com/firemodels/fds/files/761637/mid_mesh_mpi03.log.txt)
[mid_mesh_mpi20.log.txt](https://github.com/firemodels/fds/files/761640/mid_mesh_mpi20.log.txt)

**Comment by rmcdermo** [comment]
Thanks for the report.  We will see if we can figure something out.

**Comment by firemist** [comment]
It would be very helpful to me if you could let me know as soon as you're able to reproduce it or if you're having difficulty reproducing the reported observations. Thanks again.

**Comment by mcgratta** [comment]
I can reproduce it. Do the following -- add `PROCESS_ALL_MESHES=.TRUE.` to the `&MISC` line. Let me know if this fixes it.

**Comment by firemist** [comment]
Yes, that appears to have resolved the problem. I will now try it with my full geometry.

That option is in the section regarding periodic boundaries in the manual and the file does not specify periodic boundaries. I don't understand the connection here. I also don't think I understand what the option does in the code/problem setup.

Thanks very much for your quick response and assistance.

**Comment by mcgratta** [comment]
This is a bug and I have given you a work-around. The problem is that
```
-0.3 + 5.884 > 5.584
```
when written in binary representation. In short, FDS thinks that the meshes are not connected because of this round-off issue. Setting `PROCESS_ALL_MESHES=.TRUE.` forces FDS to store information about all the meshes, even if it thinks they are not connected.

**Comment by firemist** [comment]
Thanks very much for your explanation and assistance.

It's sad when we can't even trust numbers to behave. Maybe you can add this to the code ...
![image](https://cloud.githubusercontent.com/assets/25644607/22759871/0ad7c85c-ee22-11e6-921b-5e47bbf965f6.png)

**Comment by mcgratta** [comment]
Yup -- for us the rounding problems start at 10^-16. I think in your case the values -0.3 and 5.884 just happened to create a larger error than we had anticipated.

**Comment by mcgratta** [comment]
I fixed the problem of round-off by using a larger number to separate meshes. Commit #4715.
