### ISSUE TITLE
MPI in Linux - Segmentation fault

### ISSUE THREAD

**Issue by MFrag** [firemodels/fds#4718]
Hello,

I want to run an FDS case with MPI.
I followed the recommended steps and the mpi worked for this case with FDS 6.5.3 version:

- A simulation with 8 meshes with cells of the same size (0.5*0.5*0.5) in a machine with 16 processors and -np=8 and OMP_NUM_THREADS=1 (Linux)

- However, I altered the same case and I created 16 meshes (8 meshes with a grid size of 0.25*0.25*0.25 m and 8 meshes with 2.0*1.0*1.0 m in two rows the one on top of the other). Then in a machine with 16 processors (and 100GB memory) I tried to run it with -np=16 and OMP_NUM_THREADS=1 (Linux).
In the qsub file that I use to start the simulation in the cluster, I added the commands (based on previous posts):
ulimit -s unlimited
ulimit -v unlimited

Then, I always receive a segmentation error.

Could you give me an idea of what is going wrong?
Thank you!

[GN_testrun.txt](https://github.com/firemodels/fds/files/766835/GN_testrun.txt)

**Comment by mcgratta** [comment]
Add `PROCESS_ALL_MESHES=.TRUE.` to the `MISC` line and tell me if that solves the problem.

**Comment by rmcdermo** [comment]
If it does, I feel a maintenance release coming soon!

**Comment by MFrag** [comment]
Thank you! I started the simulation and it didn't give an error yet. However no output files where written yet also. As soon as it progresses, I will let you know!

**Comment by MFrag** [comment]
It is running!

It is writing all the output files (.sf, .xyz etc). I will keep an eye on it to see if it will continue running without problems and I will give you again feedback.

Thank you very much for your help!

**Comment by mcgratta** [comment]
I found your problem:
```
&MESH ID='Mesh14' IJK=40,36,21 XB=8115.710,8195.712,-1.000,35.000,15.450,36.450 /
&MESH ID='Mesh15' IJK=40,36,21 XB=8195.713,8275.710,-1.000,35.000,15.450,36.450 /
```
These two meshes are next to each other, but Mesh14 ends at x=8195.712 and Mesh15 starts at 8195.713. FDS is confused about whether these meshes are neighbors or not. If the meshes are meant to connect, make the boundaries exactly the same. If they are not meant to touch, separate them by more than 1 mm.
