### ISSUE TITLE
Solid temperature profile at EXTERNAL_FLUX boundary

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4728]
If I set EXTERNAL_FLUX with HTC=0 for a surface and monitor the solid temperature profile, I find that ONE_D%TMP(0) = ONE_D%TMP(1) = ONE_D%TMP_F.  But the heat flux INTO the solid should be consistent with -k dT/dx = -K_S * 2 * ( ONE_D%TMP_F - ONE_D%TMP(1) ) / ONE_D%X(1)

When the TMP_F is low, re-radiation should be small and -k dT/dx should be very close to the imposed EXTERNAL_FLUX.  Try the attached case.  The profile can be plotted using the Matlab script.

[external_flux.fds.txt](https://github.com/firemodels/fds/files/775145/external_flux.fds.txt)

[plot_eflux_prof.m.txt](https://github.com/firemodels/fds/files/775150/plot_eflux_prof.m.txt)

Go into dump.f90 and near LU_PROF print out the values of ONE_D%TMP(0:1) and TMP_F.

**Comment by mcgratta** [comment]
The inclusion of `ABSORPTION_COEFFICIENT` on the `MATL` line forces FDS to do an in depth radiation calculation in the solid, which includes setting the heat flux to zero at the surface. When I remove this parameter and remove the reactions, I verify that the `NET HEAT FLUX` is the same as -k dT/dx.

**Comment by rmcdermo** [comment]
Thanks... I've lots to learn about the solid phase.
