### ISSUE TITLE
Further beam visualisation in smw

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#4732]
@gforney as requested a test case for visual representation of beam obscuration and activation. There are two beams, `beam1` should increase in obscuration and activate prior to `beam2`.

[beamActivationTest.fds.txt](https://github.com/firemodels/fds/files/776781/beamActivationTest.fds.txt)

**Comment by gforney** [comment]
should be fixed in test smokeviews posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

to display values check the "values" checkbox in the device dialog box.  I'm now drawing a green sphere at center of beam which turns red when the beam device activates

**Comment by bmralph** [comment]
Great - thanks Glenn works nicely.
