### ISSUE TITLE
Weird flame blowout with EXTERNAL_FLUX and PRYOLYSIS

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4736]
In the attached case, the flame mysteriously goes out periodically (around 2 s and 4 s) even though the EXTERNAL_FLUX is constant.

[weird_blowout.fds.txt](https://github.com/firemodels/fds/files/778577/weird_blowout.fds.txt)

Here flame is established...

![weird_blowout_0344](https://cloud.githubusercontent.com/assets/4418497/22999042/8c375d9c-f3a7-11e6-9ad6-eb993b9cf84f.png)

Here is blows out...

![weird_blowout_0398](https://cloud.githubusercontent.com/assets/4418497/22999054/912b4732-f3a7-11e6-8b7f-a282588bf64c.png)

**Comment by rmcdermo** [comment]
This appears to be related to grid resolution in the solid phase.  At CELL_SIZE_FACTOR=0.1 the burning is reasonably smooth in time.

Question for @shostikk , why are we forced into STRETCH_FACTOR=1 for PYROLYSIS_MATERIAL?

**Comment by rmcdermo** [comment]
If I allow stretching with reactions via commenting this line:

IF (ML%PYROLYSIS_MODEL/=PYROLYSIS_NONE) THEN
            SF%PYROLYSIS_MODEL = PYROLYSIS_MATERIAL
            !SF%STRETCH_FACTOR(NL) = 1._EB

everything seems to look OK, qualitatively.  Is there anything I should be on the look out for?

**Comment by mcgratta** [comment]
Setting the `STRETCH_FACTOR` to 1 for surfaces that use the complex pyrolysis model was intended to lessen the impact of shrinking layers and removing solid phase grid cells. I'll look to see if this is really needed.

**Comment by rmcdermo** [comment]
I'm seeing really weird behavior in my new routines if I use stretching.  It looks like there might be some assumption about symmetry front to back and maybe there is some numerical efficiency being implemented for heat transfer only that does not apply when reactions are present.  Please see if something like that makes sense.  I have assumed that X(I+1) > X(I) for I = 0:NWP, but I wonder if this is true with stretching implemented.

**Comment by rmcdermo** [comment]
I think things are OK.  Probably just a learning curve for me in setting up these solid phase calculations.
