### ISSUE TITLE
U Guide Figure 15.3

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#4737]
A co worker observed the Figure 15.3 (particle ORIENTATION) was a bit confusing as all the examples used ORIENTATION(1:3,x) but the figure for all but the plate geometry uses ORIENTATION(:,x).  Granted in Fortran (1:3,x) is equivalent to (:,x) since the array is dimmed (3,10), but that may be something a typical user might not realize immediately.  I think it would be better for the Figure to be consistent with our examples which use 1:3.

**Comment by mcgratta** [comment]
Done. BTW, those figures are in the repo, under FDS_User_Guide/FIGURES. They are .tex files that use tikz. You can edit the .tex file and pdflatex it to make the .pdf. The pdf's are committed to the repo.
