### ISSUE TITLE
Exchange TMP for 3D heat transfer

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4745]
Kevin,
I guess I had never thought about this before, but looks like we do not ever exchange TMP.  We fill ghost cells for INTERPOLATED_BOUNDARIES after exchanging RHO, etc., as if we are always only concerned with an ideal gas (because up to now that is true).  However, for me to do conduction heat transfer in 3D inside a blockage, I need the TMP to be exchanged.  Flame spread calcs need pretty high resolution and this will require multi-mesh calculations.  We do not need to do this all the time, just when the HT3D flag is on.  Let's talk as soon as you have time.  Thanks.
R

**Comment by rmcdermo** [comment]
The flag to use to trigger the exchange is SOLID_HT3D=T.

**Comment by mcgratta** [comment]
Commit #4746

**Comment by mcgratta** [comment]
This is done.
