### ISSUE TITLE
pathfinderID not initialized in evac.f90

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4749]
I'm doing some code clean-up and the Gnu debugger is telling me that `pathfinderID` may not be initialized in `evac.f90`.

**Comment by mcgratta** [comment]
[warnings.txt](https://github.com/firemodels/fds/files/791691/warnings.txt)

Search the attached file for `evac` and `ieva`. Remove unused variables.

**Comment by tkorhon1** [comment]
I have changed (and committed) the evac.f90 and ieva.f90 accorging to warnings.txt. I did not see any warnings using Intel Linux compiler (and debug options, including -warn all). I was not able to compile using gfortran, because we have a quite old gfortran in our Linux cluster.

**Comment by mcgratta** [comment]
Thanks. I will rerun the gfortran compiler when I clean up some other routines and let you know if there are more.
