### ISSUE TITLE
Propose to change naming of variable in HVAC

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#4759]
@drjfloyd mainly:
I propose to change `LOSS` to `K_MINOR` or `KMINOR` to make the code more readable and in line with the user guide and tech guide.

Let me know and I'm happy to make the changes.

**Comment by mcgratta** [comment]
I would not eliminate `LOSS` as in input parameter since it is currently listed in the User's Guide. If you want, you can use an `EQUIVALENCE` statement to make the two mean the same thing. But is `K_MINOR` a readily recognized term in the HVAC community?

**Comment by drjfloyd** [comment]
I am OK with this for the type structures and stand alone variables in the computations, but I think we should leave the variable name as is on &HVAC.

**Comment by bmralph** [comment]
The reason for my thoughts is that `LOSS` initially confused me as I was reading the guides, looking at the code and creating input files - I was unclear what was wall loss and what was minor losses.

`LOSS` is minor losses (i.e. K<sub> minor </sub> ) and has no bearing on wall losses (unless a user choses to model wall losses as minor losses).

**Comment by bmralph** [comment]
Although as I'm writing this I'm thinking - developmentally it's a big deal to change input parameters for legacy reasons...
