### ISSUE TITLE
Verification case porous_media out of tolerance

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4764]
The case `Sprinklers_and_Sprays/porous_media.fds` is out of tolerance for the finest grid. We just upgraded compilers, and I suspect that a slight change in the arithmetic threw this case. I don't even know if it's a bug -- the expected pressure drop is related to the speed of the flow going through a porous slab. In the finest case, the flow is not perfectly straight and smooth, leading to oscillations in the pressure drop which may not be unreasonable. 

There is a possibility that the change may also be related to 
https://github.com/firemodels/fds/commit/c4f14e3676a64872fe045958979af31876b0a72a
where I fixed some uninitialized variables in the set up for POROUS particles.

**Comment by drjfloyd** [comment]
The changes you mention in part.f90 were for plate and sphere and this case uses cylindrical.  I compiled with the current and prior windows compilers and got the same results (both of which are slightly different than 6.5.3 results). I show that results are just slightly over tolerance and the 6.5.3. verification guide shows that before they were just slightly below. I don't think we introduced a bug. I'll keep digging a little.

**Comment by mcgratta** [comment]
OK, I'm OK with just loosening the tolerance. I don't think we can expect the pressure drop to be exact and non-changing.

**Comment by drjfloyd** [comment]
If I drop DT on &MISC to 0.002 from 0.01 then all of the cases wind up nice and smooth and within ~0.4 % of the ideal value. It seems that the finer resolution case which has multiple layers of particles just needs tighter criteria for the timestep size.  Is this something we want to do for verification purposes?

**Comment by rmcdermo** [comment]
If the case runs in a reasonable amount of time, I'd say yes.  I assume it is 5 times slower.  Does that keep it under 30 min?

**Comment by drjfloyd** [comment]
At DT=0.002 all get the same results and it took ~14 min. We could cut that down further as it doesn't really need to run to 10 s.  Running to 6 s would now work since we are no longer getting the pressure oscillations for the highest resolution that was forcing us to average over a long period of time. We can also I guess cut back on the tolerance to ~1 %.

**Comment by drjfloyd** [comment]
Done.

**Comment by mcgratta** [comment]
Thanks. I'll close the issue but reopen if something else pops up.
