### ISSUE TITLE
Error message has reffered OBST number hidden

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#4766]
I have an input file made of around 300000 command lines.
In case of an error, the OBST number is hidden in the error message:
`ERROR: SURF A15 cannot be applied to a thin obstruction, OBST #****`

It should be a simple formatting problem.

**Comment by rmcdermo** [comment]
Thanks Emanuel.  I'll fix.  What do you see as a good max number of OBST in the kinds of complex geometry you handle?

**Comment by drjfloyd** [comment]
Since we don't care about about having columns line up for this type of
output, rather than use I5 in the format we could just use I0. This will
automatically size the output for the size of the integer.

**Comment by rmcdermo** [comment]
Should be fixed.  Thanks for the idea to use I0.

**Comment by emanuelegissi** [comment]
Thanks Randy!
Emanuele

Il 28 feb 2017 4:33 PM, "Randy McDermott" <notifications@github.com> ha
scritto:
