### ISSUE TITLE
HRRPUA not being accepted

### ISSUE THREAD

**Issue by RakeshRanga** [firemodels/fds#4776]
I was facing problems while giving HRRPUA to my actual model for simulation. Then I tried out the same for  a simple sample. I am still having the same problem, i.e. the HRRPUA that is being given to the model is not being accepted by the software.

Here is the code for the same:
&HEAD CHID='PMMA',TITLE='PMMA BURNING STUDY' /

&MESH IJK=10,10,5 XB=0,0.010,0,0.010,0,0.005 /

&MISC RESTART=.FALSE. /
&TIME T_END = 15.0 /

&SPEC ID ='PMMA FUEL',FORMULA='C5.0H8.0O2.0'/
&SPEC ID ='OXYGEN',MASS_FRACTION_0=0.232/
&SPEC ID ='NITROGEN',MASS_FRACTION_0=0.768/
&SPEC ID ='CARBON DIOXIDE'/
&SPEC ID ='WATER VAPOR'/

&REAC FUEL='PMMA FUEL' 
      HEAT_OF_COMBUSTION=28750./

&MATL ID               ='PMMA'
      CONDUCTIVITY     = 0.20
      SPECIFIC_HEAT    = 2.2
      DENSITY          = 1100.0
      EMISSIVITY       = 0.95 
      N_REACTIONS      = 1.0
      NU_SPEC          = 1.0
      SPEC_ID          = 'PMMA FUEL'
      A                = 8.5E12
      E                = 1.8E5
      HEAT_OF_REACTION = 870./

&MATL ID            = 'ALUMINIUM'
      EMISSIVITY    = 0.09
      DENSITY       = 7850.
      CONDUCTIVITY  = 237
      SPECIFIC_HEAT = 0.91  /

&SURF ID        = 'VERTICAL_PMMA'
      COLOR     = 'BURNT UMBER'
      BURN_AWAY = .TRUE.
      MATL_ID   = 'PMMA'  
      THICKNESS = 0.005 /

#Creating the PMMA block
&OBST XB=0.003,0.007,0.003,0.007,0,0.0015,SURF_ID='VERTICAL_PMMA' /

&SURF ID='IGNITION',RAMP_Q='BURN',HRRPUA=2000.,COLOR='GREEN' /
&RAMP ID='BURN',T=0,F=0 /
&RAMP ID='BURN',T=2,F=1 /

&VENT XB=0.003,0.004,0.003,0.007,0.0015,0.0015,SURF_ID='IGNITION' /

&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/

&SLCF XB=0,0.010,0,0.010,0,0.01,QUANTITY='TEMPERATURE' /
&SLCF XB=0,0.010,0,0.010,0,0.01,QUANTITY='TEMPERATURE',VECTOR=.TRUE. /

&DUMP DT_RESTART=1/

&TAIL /

Please note that I just gave a very coarse mesh to get faster run times.

Thank you.
Regards
Rakesh

**Comment by RakeshRanga** [comment]
There are two mistakes.
1) There should be a comma before XB in the &MESH line which I have corrected in my code but did not write here.
2)Vertical PMMA came because my actual problem is vertical and same nomenclature I continued...

Thank you.

**Comment by rmcdermo** [comment]
When you are trying to specify the HRR you want to follow this example:
https://github.com/firemodels/fds/blob/master/Verification/Pyrolysis/specified_hrr.fds

I think your model is confused between specifying HRR and having a pyrolyzing material with kinetics parameters.  Look at the user guide section 8.4.3.
