### ISSUE TITLE
PDPA histogram issues

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#4785]
Hi, it all started to try to find particle density(particle volume/total volume of measured sphere) in a location within the particle stream. The more I went into it, the more I got lost with confusing values. Some of the remarks might be invalid but I would appreciate if you could lead me into right direction.

Thank you,

The attached file has a water spray and PDPA device. Issues I need help with:

- It is not clear which PDPA_M and PDPA_N values are needed for which measurement (temperature, diameter, flux etc) in the user guide. 

- Units in histogram output csv file are different from devc output file. Temperature is also multiplied with 10^6.

- If I change the min value of PDPA_HISTOGRAM_LIMITS to anything but 0, the result in histogram changes to unreasonable values. 

- If I do not include PDPA_M=1 to the DIAMETER measurement with PDPA, I cannot get the correct results in histogram output file. 

- PDPA_INTEGRATE=.FALSE.  only changes the values in histogram output file but not devc output file. That might be confusing. Also when it is FALSE, does PDPA_END have any effect?

-  NUMBER CONCENTRATION gives excessive numbers. There is not enough information about this function in the user guide. 

- I could not find any way to verify if the MASS CONCENTRATION calculation is correct.   Because despite I change the location of the device and PDPA_RADIUS, it gives the same results in the devc file. 

- PARTICLE FLUX Z has the unit kg/m2s. If the area in the unit is area of particles, then why do I get different values depending on location of device? And how do I correlate it with my flow rate?

 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1

[pdpa.txt](https://github.com/firemodels/fds/files/816892/pdpa.txt)

**Comment by rmcdermo** [comment]
Thanks for posting. We'll take a look.

**Comment by rmcdermo** [comment]
Hi Topi,
Please have a look at this issue.  Also please let me know that you are receiving this thread.  Thanks.

**Comment by tstopi** [comment]
I'm receiving this thread. I'll take a look ASAP.

**Comment by Er9y714** [comment]
In order to improve the definitions of the parameters  in the user guide, do you think adding Table 4.1 in the link below a good idea? 
Two input parameters, m,n, are listed based on type and application area. 

https://books.google.nl/books?id=XwFUCm0N2ksC&lpg=PP1&dq=Science%20and%20Engineering%20of%20Droplets%3A%3A%20Fundamentals%20and%20Applications&pg=PA250#v=onepage&q&f=false

Edit: updated the link

**Comment by gforney** [comment]
This link didn't work for me.

**Comment by Ersin9y714** [comment]
I updated it. Can you access now?

**Comment by Er9y714** [comment]
I updated the link. Can you access it now?

In case it does not work:
![image](https://user-images.githubusercontent.com/26166281/28878785-9e1162ec-77a0-11e7-8635-85f702b19856.png)
Science and Engineering of Droplets:: Fundamentals and Applications
By Huimin Liu

**Comment by mcgratta** [comment]
Any progress? If not, reassign this issue to someone else.

**Comment by tstopi** [comment]
I did create a verification case and everything seemed to be working. However, I got side tracked after this. 

I' think the output routines would need to be rewritten. I'll check where I left off and report back soon.

**Comment by tstopi** [comment]
Sorry for being so late with this. If the original reporter is still interested in the subject below are responses to the original points.  I have attached an FDS file that perhaps could be included in the verification guide.   I will try make changes to the output routines this week. Otherwise I will reassign to someone else.

> It is not clear which PDPA_M and PDPA_N values are needed for which measurement (temperature, 
 diameter, flux etc) in the user guide.

The meanings of d10, d30 and d43 are found in many books and articles discussing particles. A table such as the one linked above could be helpful. But I think this is Kevin's call.

> Units in histogram output csv file are different from devc output file. Temperature is also multiplied with 10^6.

The PDPA histogram output routine would need to be rewritten to account for different output variable besides DIAMETER.  I think the easiest fix would be to remove the 1e6 multiplier from the output routine.  This would break some verification cases (CHECK_CDF=.TRUE. dumps diameters in microns I think).

> If I change the min value of PDPA_HISTOGRAM_LIMITS to anything but 0, the result in histogram changes to unreasonable values.

 I'm not entirely sure what "unreasonable" means, but it seems that the "D" output for the histogram is wrong. If the histogram has limits 100-200, the first value in the _hist file is 0.  This is a bug in the output routine. 

> If I do not include PDPA_M=1 to the DIAMETER measurement with PDPA, I cannot get the correct results in histogram output file.

 I think this is the expected behavior but perhaps the documentation could be clearer. 

> PDPA_INTEGRATE=.FALSE. only changes the values in histogram output file but not devc output file. That might be confusing. Also when it is FALSE, does PDPA_END have any effect?

 If  PDPA_INTEGRATE=.FALSE., then PDPA_START and PDPA_END do not have an effect. This will change the histogram outputs as more particles will be used.  This should have an effect on the devc file as well since  PDP_INTEGRATE=.FALSE. will cause the output in the _devc file to be instantaneous values. Perhaps the documentation could be clearer on this subject.   

> NUMBER CONCENTRATION gives excessive numbers. There is not enough information about this function in the user guide.
>
>  I could not find any way to verify if the MASS CONCENTRATION calculation is correct. Because despite I change the location of the device and PDPA_RADIUS, it gives the same results in the devc file.
>
>PARTICLE FLUX Z has the unit kg/m2s. If the area in the unit is area of particles, then why do I get different values depending on location of device? And how do I correlate it with my flow rate?

Flux is rate of flow of a property per unit area. If you integrate PARTICLE FLUX_Z over the entire XY-plane you should get something close to your flow rate. 

As far as  I can tell the MASS CONCENTRATION , FLUX and NUMBER CONCENTRATION are correctly calculated.  I have used the  following fds file to verify the calculation:

```
&HEAD CHID="pdpa_test", TITLE="Test PDPA functionality"/

&TIME T_END=10.0,DT=0.01/
&RADI RADIATION=.FALSE./

&MISC GVEC=0,0,0,NOISE=.FALSE.,PARTICLE_CFL=.TRUE. /
&DUMP DT_PART=0.1,DT_DEVC=1.0/
&MESH IJK=10,10,10,XB=0,1,0,1,0,1/
&MESH IJK=10,10,10,XB=2,3,0,1,0,1/
&MESH IJK=10,10,10,XB=4,5,0,1,0,1/
&MESH IJK=10,10,10,XB=6,7,0,1,0,1/
&MESH IJK=10,10,10,XB=8,9,0,1,0,1/

&MESH IJK=10,10,20,XB=0,1,0,1,2,3/
&MESH IJK=10,10,20,XB=2,3,0,1,2,3/
&MESH IJK=10,10,20,XB=4,5,0,1,2,3/
&MESH IJK=10,10,20,XB=6,7,0,1,2,3/
&MESH IJK=10,10,20,XB=8,9,0,1,2,3/

&VENT PBZ=2.0,SURF_ID='OPEN'/

&VENT PBZ=0.0,SURF_ID='OPEN'/
&VENT PBZ=1.0,SURF_ID='OPEN'/


&SURF ID="WALL", FREE_SLIP=.TRUE., DEFAULT=.TRUE./

&PART ID='droplets', SPEC_ID='WATER VAPOR', QUANTITIES(1)='PARTICLE DIAMETER', DIAMETER=1000. , MONODISPERSE=.TRUE.,DRAG_COEFFICIENT=0/
&SPEC ID='WATER VAPOR',VAPORIZATION_TEMPERATURE=10000/

&PROP ID='pdpa_n'
      PART_ID='droplets'
      QUANTITY="NUMBER CONCENTRATION"
      PDPA_RADIUS=0.5
      PDPA_START=5.0
      PDPA_END=50.0 /

&PROP ID='pdpa_m'
      PART_ID='droplets'
      QUANTITY="MASS CONCENTRATION"
      PDPA_RADIUS=0.5
      PDPA_START=5.0
      PDPA_END=50.0 /

Number concentration as a function of Mass concentration (MC): NC= MC/(rho*4/3*pi*r^3)  

MC   NC

0.1 190985.93171
0.2 381971.863421
0.3 572957.795131
0.4 763943.726841
0.5 954929.658551

&DEVC XYZ=0.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_n'  ,ID="N1"/
&DEVC XYZ=2.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_n'  ,ID="N2"/
&DEVC XYZ=4.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_n'  ,ID="N3"/
&DEVC XYZ=6.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_n'  ,ID="N4"/
&DEVC XYZ=8.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_n'  ,ID="N5"/

&DEVC XYZ=0.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_m'  ,ID="M1"/
&DEVC XYZ=2.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_m'  ,ID="M2"/
&DEVC XYZ=4.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_m'  ,ID="M3"/
&DEVC XYZ=6.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_m'  ,ID="M4"/
&DEVC XYZ=8.5,0.5,0.5, QUANTITY='PDPA',PROP_ID='pdpa_m'  ,ID="M5"/

&INIT PART_ID='droplets', XB=0,1,0,1,0,1, N_PARTICLES_PER_CELL=10, MASS_PER_VOLUME=0.1/
&INIT PART_ID='droplets', XB=2,3,0,1,0,1, N_PARTICLES_PER_CELL=10, MASS_PER_VOLUME=0.2/
&INIT PART_ID='droplets', XB=4,5,0,1,0,1, N_PARTICLES_PER_CELL=10, MASS_PER_VOLUME=0.3/
&INIT PART_ID='droplets', XB=6,7,0,1,0,1, N_PARTICLES_PER_CELL=10, MASS_PER_VOLUME=0.4/
&INIT PART_ID='droplets', XB=8,9,0,1,0,1, N_PARTICLES_PER_CELL=10, MASS_PER_VOLUME=0.5/

&PROP ID='pdpa_f'
      PART_ID='droplets'
      QUANTITY="PARTICLE FLUX Z"
      PDPA_RADIUS=0.5
      PDPA_START=5.0
      PDPA_END=50.0 /

&SURF ID='SPRAY1', PART_ID='droplets', VEL=-1.0, PARTICLE_MASS_FLUX=0.1, COLOR='BLUE', NPPC=1, DT_INSERT=0.01,TAU_V=0 /
&SURF ID='SPRAY2', PART_ID='droplets', VEL=-1.0, PARTICLE_MASS_FLUX=0.2, COLOR='BLUE', NPPC=1, DT_INSERT=0.01,TAU_V=0 /
&SURF ID='SPRAY3', PART_ID='droplets', VEL=-1.0, PARTICLE_MASS_FLUX=0.3, COLOR='BLUE', NPPC=1, DT_INSERT=0.01,TAU_V=0 /
&SURF ID='SPRAY4', PART_ID='droplets', VEL=-1.0, PARTICLE_MASS_FLUX=0.4, COLOR='BLUE', NPPC=1, DT_INSERT=0.01,TAU_V=0 /
&SURF ID='SPRAY5', PART_ID='droplets', VEL=-1.0, PARTICLE_MASS_FLUX=0.5, COLOR='BLUE', NPPC=1, DT_INSERT=0.01,TAU_V=0 /

&VENT XB=0,1,0,1,3,3, SURF_ID='SPRAY1'/
&VENT XB=2,3,0,1,3,3, SURF_ID='SPRAY2'/
&VENT XB=4,5,0,1,3,3, SURF_ID='SPRAY3'/
&VENT XB=6,7,0,1,3,3, SURF_ID='SPRAY4'/
&VENT XB=8,9,0,1,3,3, SURF_ID='SPRAY5'/
    

&DEVC XYZ=0.5,0.5,2.5, QUANTITY='PDPA',PROP_ID='pdpa_f'  ,ID="MF1"/
&DEVC XYZ=2.5,0.5,2.5, QUANTITY='PDPA',PROP_ID='pdpa_f'  ,ID="MF2"/
&DEVC XYZ=4.5,0.5,2.5, QUANTITY='PDPA',PROP_ID='pdpa_f'  ,ID="MF3"/
&DEVC XYZ=6.5,0.5,2.5, QUANTITY='PDPA',PROP_ID='pdpa_f'  ,ID="MF4"/
&DEVC XYZ=8.5,0.5,2.5, QUANTITY='PDPA',PROP_ID='pdpa_f'  ,ID="MF5"/

&SLCF PBY=0.5,QUANTITY='MPUV',PART_ID='droplets'/
&SLCF PBY=0.5,QUANTITY='VELOCITY',VECTOR=.TRUE./
&SLCF PBZ=2.5,QUANTITY='PARTICLE FLUX Z',PART_ID='droplets'/
````

**Comment by mcgratta** [comment]
Topi, do whatever needs to be done to address these issues. Add the table to the User's Guide.
