### ISSUE TITLE
FDS 6.5.3 cannot overlap HOLEs with a DEVC_ID or CTRL_ID

### ISSUE THREAD

**Issue by eugarcia** [firemodels/fds#4793]
Hi all,

Just sharing an issue I noticed upon testing a recent install of FDS version 6.5.3, The HOLE function has become a bit patchy in the last update. It seems that HOLEs cannot be overlapped any longer with a DEVC_ID or CTRL_ID. This feature seems to be working fine with FDS versions 6.5.2 and earlier; this is proving a bit inconvenient as it is not possible to run a series of files created for earlier FDS versions using this feature. See snapshot below:

[https://image.ibb.co/n6RErF/FDS_holes_issue.png](url)

As it was not commented in the latest release notes, just want to know if there is any logic behind this change? Keeping an old version of FDS is not ideal, and no help when using Pyrosim, etc. I think it is possible to go round by defining failing glazing pains, doors etc. as an ensemble of obstructions rather than a hole in a single obstruction, but it is a more time-consuming process overall.

Hoping we all can shed some light over this.

Thanks a lot for your help.

Eugenio Garcia
AECOM Fire
Madrid, Spain

**Comment by eugarcia** [comment]
![fds_holes_issue](https://cloud.githubusercontent.com/assets/26221424/23608407/75def0de-0269-11e7-9663-4e279dc85f89.png)

**Comment by mcgratta** [comment]
I cannot view the image. Create a very simple test case to demonstrate what you want to do. We did restrict some functionality of HOLEs and CTRLs because it was leading to spurious results.

**Comment by eugarcia** [comment]
Hi mcgratta, thanks for your prompt reply.

While preparing a test case for demonstration I noticed what the problem was. It was an English misunderstanding on my side and I have managed to resolve it.

It is not that HOLEs cannot be 'coupled' with DEVCs / CTRLs, but rather that multiple HOLEs cannot be 'overlapped' with themselves, should one of them have  DEVC / CTRL assigned. So it is simply a matter of redefining the hole geometries, and not that a feature was removed of FDS 6.5.3 as I first interpreted.

I have uploaded a simple input file with faulty overlapped holes to demonstrate what my problem was.
[test_DEVCs.txt](https://github.com/firemodels/fds/files/824367/test_DEVCs.txt)

Thanks for your attention anyway, hope this could be useful should anyone else find the same fault.

**Comment by mcgratta** [comment]
Thanks for the info. Yes, the problem with overlapping HOLEs was that there was a logic problem in how to assign the control to the blockage used to fill the HOLE. I'll take a look at your case, but hopefully you can set up your case without too much trouble.

**Comment by eugarcia** [comment]
It's resolved now, no need for you to spend time on it. I could easily fix the old files I needed to run with FDS 6.5.3, so all is fine. I'll bear this in mind in any future work. Thanks a lot for your time.

**Comment by mcgratta** [comment]
OK, thanks for looking into it.

**Comment by tkorhon1** [comment]
Could text like "multiple HOLEs cannot be 'overlapped' with themselves, should one of them have DEVC / CTRL assigned. " to be added in the User's Guide? It is useful to document features of the  program.
This way the source code does not need modifications. And users can manage their input files, if they know this feature.

Well, the text could also be added to release notes, because users are using (hopefully) release notes, when they are updating their old input files.

Wbr,
Timo

**Comment by mcgratta** [comment]
I'll add some text.

**Comment by mcgratta** [comment]
Done
