### ISSUE TITLE
HRR FREE

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#4795]
I've been running a model where the HRR freezes when any sprinkler activates. If I stop and restart the model after the sprinkler triggers the HRR freeze, then the freeze time becomes -1.E+10. This causes the HRR to drop to zero. 

A simple example is attached.

Thanks

[HRR_freeze_and_restart.fds.txt](https://github.com/firemodels/fds/files/824789/HRR_freeze_and_restart.fds.txt)

**Comment by rmcdermo** [comment]
Dave?

**Comment by Dave-McGill** [comment]
Sorry Randy, I somehow posted the issue with only a title. The body text is there now.

**Comment by rmcdermo** [comment]
Thanks, we'll have a look.

**Comment by rmcdermo** [comment]
Dave it is not clear to me what you are trying to do.  Also, the case takes awhile to run.  Can you please simplify this further and recreate the problematic behavior in a case that runs

**Comment by rmcdermo** [comment]
Sorry, I did not finish my previous comment.

**Comment by rmcdermo** [comment]
Kevin or Jason,
Please have a look at this.  It does not seem like a "simple" case to me.  But then again I am not very familiar with the CTRL logic.

**Comment by Dave-McGill** [comment]
Further to Randy's questions, the sprinklers trigger and the HRR freezes at 42 s. I stopped and restarted the simulation at 60 s, and let it run to 100s. The attached file _devc.csv file shows the change in the freeze time  after having been restarted.  The above can all be demonstrated in about 5 minutes of clock time.


[HRR_freeze_and_restart_devc.csv.txt](https://github.com/firemodels/fds/files/825313/HRR_freeze_and_restart_devc.csv.txt)


Dave

**Comment by drjfloyd** [comment]
We weren't writing the DV%SMOOTHED_VALUE to the restart file.  
fixed in:
https://github.com/firemodels/fds/commit/8f843fce5c0519e5c5b3ff86c53f34b64a2ce0aa
