### ISSUE TITLE
Fill edges and corner ghost cells for viscosity

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4803]
Attached test case demonstrates that MU ghost cell values at corners and edges are not correct.
[match_molecular_viscosity.fds.txt](https://github.com/firemodels/fds/files/828416/match_molecular_viscosity.fds.txt)

**Comment by mcgratta** [comment]
I think I have a way forward on this, but it means changing the way we exchange info. Currently, we exchange info at external wall boundaries. I think we should exchange info at all ghost cells -- that is, wherever a ghost cell overlaps another mesh, exchange that info. This will ensure that even corners and edges get populated, although it also means that there will be more neighboring mesh exchanges. I don't want to do this right now -- I want to get another minor release and fix MPI issues on burn.

**Comment by mcgratta** [comment]
I am going to close this issue. I think that a change in mesh exchanges like this will slow the code by increasing the number of mesh to mesh communications. I say we wait until we find that such a change is critical.
