### ISSUE TITLE
Heat flux Problem

### ISSUE THREAD

**Issue by RakeshRanga** [firemodels/fds#4808]
Hello !
I want to try to make the solid disappear, similar to the box_burn_away2 example, but with only heat flux to the top of the surface. This I want to give as EXTERNAL_FLUX through a vent. So I created SURF ID with EXTERNAL_FLUX assigned to it and used SURF_IDS to assign it to the top surface of the obstruction. All the MATL data are taken from the example.
If I check for the INCIDENT HEAT FLUX through the BNDF output, it is showing 350 but the box is not burning.
Is the procedure that I have used to give the heat flux only to the top surface correct?
[boc_burn_away.txt](https://github.com/firemodels/fds/files/829968/boc_burn_away.txt)

**Comment by mcgratta** [comment]
When you want an `OBST` to burn away, give it only one `SURF_ID`. Put the external flux on the `SURF` line that applies to the entire obstruction:
```&SURF ID                   = 'FOAM SLAB'
      COLOR                = 'TOMATO 3'
      MATL_ID              = 'FOAM'
      THICKNESS            = 0.1
      EXTERNAL_FLUX = 50.
      BURN_AWAY            = .TRUE./
```

**Comment by RakeshRanga** [comment]
Respected sir,

If I try to do that, the solid is receiving the heat flux from all the 6
surfaces. But I require it to receive it from only the top surface as I am
trying to simulate an experiment where only the top surface is heated till
it begins to give out fuel vapors and thus pyrolyse.
How do I accomplish this task?

Thank you.
Rakesh

**Comment by mcgratta** [comment]
At the moment, you cannot do this. FDS only has a one-dimensional heat conduction algorithm. If you want the obstruction to burn away, you must assign the same BC to each face.

**Comment by RakeshRanga** [comment]
Respected Sir,

Are you planning to incorporate this feature in the next version?
If yes, when is the next version being released ?

Thank you.
Regards,
Rakesh

**Comment by mcgratta** [comment]
I cannot predict when this feature will become available.
