### ISSUE TITLE
Flow separation at tunnel's portal

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#4818]
Dears,
I'm trying to simulate the flow field at the inlet portal of a tunnel (figure 1) but when I compare the results obtained with different grid's resolution I found some unexpected results. I used grids with cubic elements with size 0.5 m (mesh 1), 0.25 m (mesh 2), 0.125 m (mesh 3) and 0.0625 m (mesh 4), later, I further refined the mesh 4 near the portal, from -1.25 m to 10 m, with finer elements with size 0.03125 m (mesh 5). When I compare the average pressure along the tunnel I see that the pressure I doesn't reach an asymptotic value using finer grids, but the pressure profile continues to change (figure 2). I checked the pressures at the portals and these don't show strange fluctuations, so I expect the case doesn't have convergence problems (figures 3, portal, and 4, exhaust). I think the different results can be consequence of the flow separation at the inlet portal, where the pressure and velocity distributions are strongly affected by the grid's resolution. 
I would like to ask if someone has already faced similar problems in case of flow separation.

Together with the figures I made I attach the input file for mesh 1 from which I deleted the device lines for sake of brevity.
The case was run with FDS 6.5.1, but looking at https://github.com/firemodels/fds/wiki/FDS-Release-Notes there should't be any substantial changes between the two versions for the case I'm studying.
I'm sorry I'm posting this case on the issue tracker but on the group I couldn't attach my files to the post.

Thanks for your help,
Regards
Matteo

![figure 1](https://cloud.githubusercontent.com/assets/15084725/23859024/a5757874-0802-11e7-875a-0bb08d342b93.png)
![figure 2](https://cloud.githubusercontent.com/assets/15084725/23859026/a576779c-0802-11e7-997c-ab9f8dfe81b1.png)
![figure 3](https://cloud.githubusercontent.com/assets/15084725/23859025/a575e1f6-0802-11e7-953b-3303a5136712.png)
![figure 4](https://cloud.githubusercontent.com/assets/15084725/23859023/a5739306-0802-11e7-9d72-b627dbec9ac0.png)
![inlet_mi_pres_cont_m1](https://cloud.githubusercontent.com/assets/15084725/23859022/a572e334-0802-11e7-8546-bd9c13805966.png)
![inlet_mi_pres_cont_m2](https://cloud.githubusercontent.com/assets/15084725/23859027/a57f2fc2-0802-11e7-9c6c-49ef0876b1eb.png)
![inlet_mi_pres_cont_m3](https://cloud.githubusercontent.com/assets/15084725/23859028/a58b0306-0802-11e7-8398-afb42b6abb6b.png)
![inlet_mi_pres_cont_m4](https://cloud.githubusercontent.com/assets/15084725/23859029/a58c3258-0802-11e7-81a1-d92339f625a8.png)
![inlet_mi_pres_cont_m5](https://cloud.githubusercontent.com/assets/15084725/23859030/a58ed10c-0802-11e7-827e-b24926507bde.png)
![inlet_mi_vel_cont_m1](https://cloud.githubusercontent.com/assets/15084725/23859033/a59d525e-0802-11e7-8b63-21826d9fe273.png)
![inlet_mi_vel_cont_m2](https://cloud.githubusercontent.com/assets/15084725/23859031/a5925b9c-0802-11e7-882f-f76fda95936a.png)
![inlet_mi_vel_cont_m3](https://cloud.githubusercontent.com/assets/15084725/23859032/a59abf1c-0802-11e7-8ef9-dd3ed9ec786e.png)
![inlet_mi_vel_cont_m4](https://cloud.githubusercontent.com/assets/15084725/23859034/a5a301b8-0802-11e7-9879-bd7333fa8bba.png)
![inlet_mi_vel_cont_m5](https://cloud.githubusercontent.com/assets/15084725/23859035/a5af8a3c-0802-11e7-9c39-875f374d5181.png)
[input_tunnel_m1.fds.txt](https://github.com/firemodels/fds/files/838493/input_tunnel_m1.fds.txt)

**Comment by rmcdermo** [comment]
Matteo,
Couple of things:
1. Try using a Dirichlet pressure boundary condition at the exhaust.  Specified velocity is a Neumann pressure bc.  You will have to experiment with the value of pressure you need to get the velocity you need.  Start with something like this:

&VENT XB= -20.0,-20.0,-2.5,+2.5,+00,5.0 ,SURF_ID='OPEN',COLOR='RED', DYNAMIC_PRESSURE=-18./

You can put a PRESSSURE_RAMP is you need (see user guide).  You may find that you need different outlet dynamic pressures to get 6 m/s, and that will explain why you do not get convergence.
2. You may need to set a tighter VELOCITY_TOLERANCE on PRES line.  See user guide.  If the velocity tolerance is tight enough things will eventually converge.  I can't tell you what that tolerance is without doing the problem myself.  Note that if 6 m/s with an OPEN bc is desired in the tunnel, you could use a VELOCITY PATCH (see user guide).  This would give you the right volume flow and also give a Dirichlet pressure bc at the outlet (OPEN).

I don't see this as an Issue over and above what we know as problems in the pressure solver, so I am going to close this ticket.

**Comment by mpachera** [comment]
Thanks Randy for the answer, I'm facing a similar problem in case of fire,
if I impose the velocity blowing on a fire in a tunnel I have large
pressure errors. I tried to tight the convergence criteria on the pressure
error and the fluctuations are smaller, but also increasing the number of
iterations the solution doesn't converge and the pressure error is always
higher than the tolerance value I set. Do you think that imposing a
pressure boundary condition can be the solution also for this problem?

**Comment by rmcdermo** [comment]
Unfortunately, the pressure solver converges very slowly.  It can take 1000s of iterations to get to convergence in tough cases.  Tunnels continue to plague us.  One of the main reasons for this is that we have actually no tunnel validation cases, despite this being a primary area of use for FDS.  We are hoping to collaborate with Edinburgh in the near future to add a tunnel chapter to the validation guide.  In the mean time, we have to work with our current setup.  I can tell you that time variation of the boundary condition is a primary culprit in cases that do not converge.

Also, in the near future we will have the option to use the Pardiso cluster solver, which is slow, but nevertheless better than nothing if you cannot get convergence with the FFT solver. @marcosvanella is working on this.

**Comment by mpachera** [comment]
Thanks, I'm also really interested in the tunnels' validation topic, so
this is a great news. From my experience I have seen that the pressure
error is quite small with no fire and I can have convergences below 10E-3,
but with fires the pressure error remains much higher despite the
iterations. By the way now I'm running my fire case with pressure imposed
instead of velocity and the simulation doesn't show anymore strange
pressure fluctuations.
