### ISSUE TITLE
fds2ascii cleanup

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4821]
Couple of things:
1. Per the forum discussion, the 1D SLICE with ya option needs to be documented.  Probably other stuff needs to be documented as well.  There is only one example in the guide, which does not seem to catch all the possibilities.
2. Why is the fds2ascii source in Data_Processing instead of the fds2ascii folder in Utilities?  If there is not a good reason to keep it there, to me it makes more sense to have it under fds2ascii/

**Comment by mcgratta** [comment]
I moved fds2ascii.f90 and modified Makefile accordingly. I deleted the rest of a Data_Processing. I think that coupling_emulator has its own folder now. The program coupling_emulator.f90 in Data_Processing appeared to be redundant.

**Comment by gforney** [comment]
I was looking through old issues and just noticed that I was assigned this issue.  Not sure why I didn't see it before.  Is there anything I need to do?

**Comment by mcgratta** [comment]
I added some more explanation of fds2ascii to User's Guide.
