### ISSUE TITLE
Numerical Instability with HVAC

### ISSUE THREAD

**Issue by Josepazhur** [firemodels/fds#4830]
[Cenario_6_Milke_2 .txt](https://github.com/firemodels/fds/files/844794/Cenario_6_Milke_2.txt)

**Comment by Josepazhur** [comment]
I'm having trouble with this numerical instability error simulation at 30 seconds

**Comment by drjfloyd** [comment]
Your HVAC vents at the bottom have essentially no flow losses and are very large in area. When the fan is off they become very sensitive to the initial pressure pulse of the fire starting to grow.   Try adding HVAC_PRES_RELAX=0.9 to the &MISC line.

**Comment by sbenkorichi** [comment]
Jason,
Under windows with 6.5.3 version, at the beginning stopped around 6 s. Now after adding : `&MISC HVAC_PRES_RELAX=0.9 / `
It's at 46 s without any numerical instability.

Regards,
Salah

**Comment by sbenkorichi** [comment]
I had to stop it after 120 s. No error is noticed.
José, if you still facing numerical instability after adding what Jason has recommended, please let us know.
Kind regards,
Salah

**Comment by Josepazhur** [comment]
Dear Jason and Salah,

I already added the one recommended by Jason and at the moment the
simulation is in 81 seconds without any errors.

Jose

2017-03-15 16:49 GMT-03:00 Salah Benkorichi <notifications@github.com>:

**Comment by emanuelegissi** [comment]
What is the effect of HVAC_PRES_RELAX on the model?
I could not find it in the manual.
Emanuele

**Comment by drjfloyd** [comment]
Emanuel,

Randy noticed this and opened it as an issue, see the discussion in https://github.com/firemodels/fds/issues/4832

**Comment by emanuelegissi** [comment]
Ok, I got it. This could be my problem as well...

**Comment by drjfloyd** [comment]
Add HVAC_PRES_RELAX in https://github.com/firemodels/fds/commit/817b3958656b6e0c145cdc00b8c63cce9c7b339f

**Comment by dvswenson** [comment]
We have also seen this instability. The attached model ran satisfactorily in FDS 6.5.1, but was unstable in FDS 6.5.3. Changing the HVAC fan to VOLUME_FLOW fixed the problem.

![instability fds 6 5 3](https://cloud.githubusercontent.com/assets/13338306/24931351/90498396-1ed2-11e7-8e52-5a3a829cb93f.png)

[Go_Jet_always_on_reduced_1b1.txt](https://github.com/firemodels/fds/files/914705/Go_Jet_always_on_reduced_1b1.txt)
