### ISSUE TITLE
Add some details to Wind speed section example

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#4834]
Hi Randy,
In the example provided in section 10.2 concerning the wind speed.
&MISC ..., MEAN_FORCING(1:2)=.TRUE., **U0**=7.07, **V0**=7.07,
Wouldn't be possible to include how the U0 and V0 have been calculated?
In the example you have 10m/s (magnitude), direction : northest = 45 degrees. 
Something like this might be added to that section to just explain briefly where these two values come from, so the users will find it easy to generate new values based on their own interest.
**U0 = 10 * cos (45) = 7.07
V0 = 10 * sin (45) = 7.07**

Regards,
Salah

**Comment by rmcdermo** [comment]
Done.

**Comment by sbenkorichi** [comment]
Thanks,
That was quick !
