### ISSUE TITLE
Add LOCAL variable input to RAMP

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4850]
Jason,

I'm using the DEVC_ID trick (sec. 17.6.1 of user guide) to vary CHI_R with the DEVC inlet XO2 for the UMD line burner cases.  This is a great feature!  And it makes me wonder how hard it would be to make this trick a bit more general.  Suppose, instead of using the XYZ of a DEVC, we add some flag such as LOCAL to RAMP, for example,

&RAMP ID='R1', T=0, F=..., LOCAL=.TRUE., QUANTITY='MIXTURE FRACTION'/
&RAMP ID='R1', T=1, F=..., LOCAL=.TRUE., QUANTITY='MIXTURE FRACTION'/

When evaluating the ramp, we would call GAS_PHASE_OUTPUT for QUANTITY at I,J,K.

As a start, this might be used to test ideas for local models of CHI_R.  But I could see it being used for may other purposes---maybe helpful for extinction/reignition.  It would be very close to a user-defined function if it could be combined with the CTRL math functions.

Not high priority, but let me know what you think.

**Comment by drjfloyd** [comment]
I think that would be somewhat easy. We'd have to make GAS_PHASE_OUTPUT visible outside of the module. Then it would just be a matter of figuring out the right location to put a routine that would evaluate local ramps and do the appropriate replacement of FDS computed variables.  We might want to have a second RAMPS array (RAMPS_LOCAL?) using RAMP_TYPE so we could just cycle over local ramps without the expense of checking to see if it is local or not.

**Comment by rmcdermo** [comment]
My initial brute force thinking was that we would add I,J,K as inputs to EVALUATE_RAMP.  But this would mean a ton of DUMMY_INTEGER passes.   Second thought was that we could have a new function EVALUATE_RAMP_LOCAL(...,II,JJ,KK).  And, at first, only apply this to, say, CHI_R for testing purposes.  I'm not sure I follow how we would utilize the second RAMPS array to save cycles.

**Comment by drjfloyd** [comment]
I think I understand now.  I was interpreting this as a desire for a general ability for a user to redefine any arbitrary variable. In which case, for example for MU, we would have to add logic in divg.f90 to check to see if there was a ramp that redefined MU, etc.  You just want the existing locations where we have RAMP evaluations to be able to use some local parameter?

We wouldn't need dummy integer passes, we could have OPTIONAL arguments for EVALUATE_RAMP.  I,J,K,, and IW (in case a user wanted solid phase quantity). 

I think we would just need a few things:
1) add quantity lookups to the ramp processing
2) another case in EVALUATE_RAMP to process LOCAL RAMPs
3) expose the GET_OUTPUT routines in dump

**Comment by rmcdermo** [comment]
Yep.  That's it.

**Comment by rmcdermo** [comment]
Let's close this...
