### ISSUE TITLE
Difference in validation results for new droplet routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4852]
I just ran the following validation cases with the new droplet evaporation routine

BRE Spray
LEMTA Spray
VTT Spray
USCG_HAI
UL_NFPRF

I see noticeable differences in the "Spray" cases. Compare the results from the release version of the FDS Validation Guide and the last nightly build.

**Comment by drjfloyd** [comment]
UL and USCG are very similar. Slight differences. 
BRE spray the mean diameters look the same and there are differences in droplet speeds. With the new version the profile slope with pressure is matched better but the offset is different.  
LEMTA the attentuation points have shifted down an on average it looks like predictions are improved.
VTT spray the flux and diameter look the same but the velocity is a little larger.
Evaporation rates are slightly different in the two versions, so I would expected some minor differences in results.  With the exception of the VTT velocities, I am not sure if there is anything wrong so much as different. I'll take a closer look at those cases to see if I find anything.

**Comment by mcgratta** [comment]
Yes, I just want to make sure the differences are understood.

**Comment by drjfloyd** [comment]
If run VTT case 1 with EVAP_2=TRUE with 6.5.3, I  get results very close to the release. If I run with the current source I see the larger vertical velocities. I'll look to see what the cause was.

**Comment by drjfloyd** [comment]
If I run the current source with EVAP_2 = .FALSE., I am seeing the same velocities as with it .TRUE. This suggests the difference isn't the evaporation model but something else that has changed.

**Comment by mcgratta** [comment]
How fast are the runs? Is it practical to do a git bisect?

**Comment by drjfloyd** [comment]
Takes a couple of hours to get far enough along so it is possible.

**Comment by mcgratta** [comment]
Then I suggest looking back through the git logs of part.f90. We released 6.5.3 mid January. I see a number of minor changes to various evap routines, but not sure what could be the culprit.

**Comment by rmcdermo** [comment]
I'm scanning my commits and came across this one.  Might be part of the issue.

https://github.com/firemodels/fds/commit/cd254ef9a27488a32fc0830ba029e2e7794c0ce2

**Comment by rmcdermo** [comment]
Also, around that time, we worked hard to get all the EVAP routines using the same code for fluid props, K_AIR, D_AIR, etc.  This tightened up the results of old EVAP and new EVAP for IAFSS paper.  Before, the results were completely different.

**Comment by drjfloyd** [comment]
The culprit appears to be https://github.com/firemodels/fds/commit/e1d8c19b80261538235f9a7bacfea5783b86d251#diff-a551607d30f801c77105e19081cb4235

**Comment by drjfloyd** [comment]
In that commit one of the changes was DT => DT_P in the LP%ACCEL calculations at line 1882. If I go into the current source and change DT_P back to DT, the results then go back to what we saw in 6.5.3.

**Comment by drjfloyd** [comment]
Attached are three files.  first is the 6.5.3 results, second is the current source, and third is the current source with the input file time step set to 0.015 m / (60 m/s) which prevents sub-time steps for the droplet movement.  

The results for the third to me look much more like the first than the second.  Should we be using DT instead of DT_P?

![ln02_1c_0015](https://cloud.githubusercontent.com/assets/12799217/24311721/c1ed7d92-10ab-11e7-881e-d1ae8a81aefb.png)
![ln02_1a_0015](https://cloud.githubusercontent.com/assets/12799217/24311722/c1f23274-10ab-11e7-8bc0-2f0457269baf.png)
![ln02_1b_0015](https://cloud.githubusercontent.com/assets/12799217/24311723/c1f23f3a-10ab-11e7-8068-a67d17193ed5.png)

**Comment by mcgratta** [comment]
But I think that using DT is erroneous. I think that changing DT to DT_P in this commit was to correct a bug that I introduced when I neglected to add DT_P to the momentum calc. DT_P is a sub-timestep when the particle is moving beyond a grid size in a single time step.

**Comment by drjfloyd** [comment]
If DT_P is correct, I would expect that forcing the FDS timestep to be small enough to avoid sub-timestepping would result in something that looked like the DT_P results. Instead it looks like the DT results.  Are we sure DT is correct to use in LP%ACCEL?

**Comment by mcgratta** [comment]
Randy and I looked it over, and we think that DT is right, not DT_P. If you sum (U_OLD-LP%U) over the sub-steps, you should get the total change in U over the entire step, which then should be divided by DT, not DT_P. Restore DT and we'll see if firebot accepts it.

**Comment by rmcdermo** [comment]
Sorry, Jason.  I owe you one.

**Comment by drjfloyd** [comment]
I made similar errors with the D_VAP term when dealing with sub-timesteps for droplets :-)

**Comment by mcgratta** [comment]
This case is resolved.
