### ISSUE TITLE
Numerical Instability

### ISSUE THREAD

**Issue by cantuelo** [firemodels/fds#4855]
Hi.

since my last post in FDS and Smokeview Discussions I have tried several changes to my model and I have not gotten past the 600-second simulation. the problem persists.

my programs are updated to the latest version available and have revised the model several times.

the model set again, I need help, thanks
[tunel_base-PRUEBA5.zip](https://github.com/firemodels/fds/files/860696/tunel_base-PRUEBA5.zip)

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
Your case is still running. But already I can see that there might be problems. I suggest you do the following:
   1. Run the case with no fire and just test the HVAC system.
   2. Add leaks or openings in the tunnel. Most tunnels are not perfectly sealed, and in FDS, a big fire in a perfectly sealed tunnel can cause large changes in pressure that then cause stability problems for the HVAC solver. By adding leaks or holes to the tunnel, you reduce the size of the pressure fluctuations.
   3. Tighten the tolerance of the pressure solver:
   ```
   &PRES VELOCITY_TOLERANCE=0.1, MAX_PRESSURE_ITERATIONS=50 /
   ```
Read more in the User's Guide.
   4. Try breaking up the tunnel into multiple meshes, and combine the two meshes at the end into one mesh. I do not understand why you divide the small compartment in two, and then have a very large mesh over the whole tunnel.

**Comment by drjfloyd** [comment]
You have defined a fan curve for your fans but have not defined an HVAC system with real world losses.  You have no fitting losses or exit/entry losses defined.  Without specifying actual losses, there isn't much point to defining a fan curve and you are probably better off just defining exhaust vents as fixed flow without using HVAC.

**Comment by mcgratta** [comment]
Thanks, Jason. Yes, if you simply define exhaust vents with a fixed volume flow, you reduce the likelihood of creating a bad feedback loop between the gas phase pressure solver and the HVAC pressure solver.

**Comment by cantuelo** [comment]
Ok, but this is a tunnel that is working and the system of extraction is like this. Only has these two jet fans for the extraction in case of fire.
I review what you have indicated and I communicate the result.
Thank you

**Comment by mcgratta** [comment]
OK, but if you can just define a specific extraction rate and not use the HVAC routines, that might help with instability problems. Only use the HVAC routines if you need to better understand how the fire in the tunnel affects the HVAC system. If you only want to test the impact of a specified extraction rate, do not use the HVAC routines.

**Comment by cantuelo** [comment]
I like what you say, but how can I simulate a jet fan without using HVAC?

**Comment by drjfloyd** [comment]
Don't use a FAN with a fan curve. Just specify VOLUME_FLOW for the DUCT
using the design flow rate of the system.

**Comment by cantuelo** [comment]
OK.

**Comment by mcgratta** [comment]
Or consider `VELOCITY PATCH`.
