### ISSUE TITLE
Allow dropped MPI packets without shutdown

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4864]
@mcgratta Another REQ9 on coarse case.  I will try increasing time increment.  But would be nice to have this feature enabled.  I am gone all next week.  Would like to get cases launched today.  Thanks.

**Comment by mcgratta** [comment]
Commit #4865. I have not tested this because it is difficult to create a case that consistently times out. However, I added an MPI_CANCEL call instead of MPI_ABORT when a particular request times out. The error message is still written, so that we can see if we successfully bypass a time out.

**Comment by mcgratta** [comment]
This appears to be a problem with the burn cluster at NIST. I added synchronous sends
```
MPI_SSEND_INIT
```
which forces receives to be posted before sends, but this does not solve everything.

**Comment by mcgratta** [comment]
This is done. It doesn't completely solve the dropped packet problem, but it does allow runs to continue.
