### ISSUE TITLE
MPI problem and FDS file

### ISSUE THREAD

**Issue by ferucar** [firemodels/fds#4875]
Hello,
 I've been working on a cluster for my project. I'm preparing my model on Pyrosim on Windows in my laptop and  then exporting it as a fds file to use on a linux cluster.  I installed FDS 6.5.2 on linux cluster.  System uses LSF files. Could anyone please help me with an example LSF file? Here's the one I've prepared. But it seems not valid. 

>#!/bin/bash
>#BSUB -q long
>#BSUB -m ege
>#BSUB -o %J.out
>#BSUB -P syayo1
>#BSUB -n 4
>#BSUB -a intelmpi
>
>mpirun --report-bindings --bind-to socket --map-by socket -np 20
>/RS/users/ferucar/FDS/FDS6/bin/fds couch.fds
>
Also when I try to run fds normally on server, (without using parallel mpi) I get an error. (I'm using the classic command "fds fdsfile.fds") I'm sending it's screenshot. Could anyone also help me about how can I fix that. 
I will be grateful for your help,
Best wishes, 
Furkan.
![screenshot](https://cloud.githubusercontent.com/assets/26714091/24356988/b275bcb6-1304-11e7-8d1e-1de7846fe187.PNG)

**Comment by mcgratta** [comment]
I do not know LSF. We use PBS at NIST. You can only run couch.fds with 1 MPI process.

Your single mesh is starting normally. How big is the mesh?

**Comment by gforney** [comment]
What error? I do not see an error in your screen shot
