### ISSUE TITLE
Fix a link in a wiki page

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#4908]
In the page of validation process here : 
https://github.com/firemodels/fds/wiki/FDS-Validation-Process 
Under **Initial Tasks** section: 
The link of **firemodels** repo is referring to the fds repo.
It should be changed to : 
https://github.com/firemodels

**EDIT:** 
Another thing noticed, should be changed : 
https://github.com/firemodels/fds/wiki/Installing-Open-MPI-on-a-Linux-Cluster
**5**. Build the FDS Linux version from the `FDS-SMV `repository: (now the FDS-SMV) has changed to firemodels/fds 
cd FDS_Compilation/mpi_intel_linux_64
./make_fds.sh
Simiarly with **FDS_Compilation** to **Build**

**Comment by rmcdermo** [comment]
Fixed.  Thanks, Salah!  Keep'm coming.

**Comment by sbenkorichi** [comment]
Sure Randy, 
Welcome back btw :)
