### ISSUE TITLE
read part files

### ISSUE THREAD

**Issue by AAbouali** [firemodels/fds#4965]
Is there is away to convert the *.prt5 files to ASCII file provided within the FDS package please ? 
if not, can some one help me with a direct way to do it please, either on Linux or windows

**Comment by rmcdermo** [comment]
Hi.  This question would be better for the discussion forum.  This issue tracker is mainly to report bugs.  Also, others may be interested in your question.  For now, I'll go ahead and respond here:

The easiest way to get the part file into ASCII is using the read_prt5.m script in our Utilities/Matlab/scripts/ directory.

https://github.com/firemodels/fds/blob/master/Utilities/Matlab/scripts/read_prt5.m
