### ISSUE TITLE
error in dump file when restart simulation 

### ISSUE THREAD

**Issue by AAbouali** [firemodels/fds#4966]
Hello, I have stopped a simulation using the dummy file *.stop, then when I restarted the simulation I received this error: 
######
At line 7373 of file ../Source/dump.f90 (unit = 12, file = 'needles_plot_devc.csv')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE
######
I had the same error before many times also, I don't know if it's bug or am I doing something wrong 
Regards

**Comment by rmcdermo** [comment]
Please submit a simple input file that demonstrates the issue.  Note that you need to append .txt in order to upload the file here.  Thanks.

**Comment by mcgratta** [comment]
This is most likely caused by a bug in the current version involving restarting a simulation involving particles. Do not restart jobs with particles until we release a new version.

**Comment by AAbouali** [comment]
Yes I am using Lagrangian particles, alright, thank you

**Comment by AAbouali** [comment]
Hello Kevin 
Is this bug has been fixed ? If I forked the FDS now and complied it, is it going to work ? 
thanks

**Comment by mcgratta** [comment]
Try it. We fixed the bug,  but you should confirm.

**Comment by sbenkorichi** [comment]
We'll try it.
I tested it on weekends and restart seems working fine.

**Comment by AAbouali** [comment]
very nice, I will compile it on our cluster again and will let you know if there is still something wrong then 
thanks
