### ISSUE TITLE
Add discussion of MLR_FUEL and MLR_TOTAL to user guide

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4980]
Per the thread below, unless I am missing it, it does not appear that this is clearly spelled out in the user guide.  You have a section on the Q columns, but I don't see anything related to MLR_FUEL or MLR_TOTAL.

-------------------

I do not know whole list but I can say that MLR_TOTAL includes particles (not fuel, such as water from nozzle)  injected into the domain. 

-------------------

Dear All,

Could anybody help me out with the difference between MLR_FUEL and MLR_TOTAL in the file of CHID_hrr.csv?
What does Total comprise over the fuel? 
Where is it measured? - In my understanding the fuel mass loss rate is measured when it has been released. How is it with the Total mass loss rate?

Thank you for your help in advance,

Kind regards,
Csaba

**Comment by mcgratta** [comment]
Added text to the User's Guide. Short answer -- MLR_FUEL is the rate at which fuel gas is generated at solid surfaces (or from evaporating droplets). MLR_TOTAL is the generation rate of all gases, including fuel, at surfaces or droplets. These quantities are "measured" at the surface.
