### ISSUE TITLE
Assess NEW_MOMENTUM_NUDGING for MEAN_FORCING

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4986]
Kevin,

I'd like to get NEW_MOMENTUM_NUDGING in shape for the next release.  Can you please go through your LNG_Dispersion and CSIRO_Grassland_Fires cases and try it out.  You will need to set NEW_MOMENTUM_NUDGING=T on MISC and you will have to tune DT_MEAN_FORCING, which will need to be significantly larger than present.  I would start with 10 s and go from there.

**Comment by rmcdermo** [comment]
Note that you probably also want to play with setting SPONGE_LAYER_DISTANCE on MISC.  This is the distance over which the DT_MEAN_FORCING linearly changes from DT on the boundary to DT_MEAN_FORCING at the SPONGE_LAYER_DISTANCE away from the boundary.  The effect is to wipe out spurious fluctuations on the boundary.  For a 1 km domain, you might want to set SLD to 100 m, for example.

**Comment by rmcdermo** [comment]
I was wrong before, SPONGE_LAYER_DISTANCE is not independent of the nudging method (as currently implemented).  The TAU changes locally and thus changes the forcing locally.   We can modify this, but I want to see what is wrong with the new forcing scheme first.

**Comment by mcgratta** [comment]
I am going to create a new `NAMELIST` group called `WIND`. I'll take a look at this issue in the context of this new group and its default parameters.

**Comment by drjfloyd** [comment]
I think a WIND group is a great idea.  Besides speed, profile, and direction do you intend to also include SEM and time varying conditions (speed and direction)?

**Comment by mcgratta** [comment]
Yes, everything. `MISC` is becoming overloaded with wind-related stuff. I also want to generate automatically wind profiles based on Monin-Obukhov similarity theory. Currently, the user has to do this using `RAMP`s, but I think it would be better to have parameters typically used by the meso-scale meteorology community. Lots of this will default, so a user would only be expected at a minimum to specify wind speed/direction at 2 m height or whatever.

**Comment by mcgratta** [comment]
Now, the strategy for `OPEN` boundaries and wind is to aggressively force the normal and tangential components of velocity near the external boundary. The interior of the domain uses mean forcing where a constant forcing term is added to the momentum equation, rather than forcing each individual vector towards the wind average. This is written up in the User's Guide.
