### ISSUE TITLE
Check consistency of K_TMP and MU_TMP

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#4991]
This issue is related to a complaint from Isaac Leventon who has seen markedly different results for upward flame spread on PMMA from version 6.1.2 to 6.5.3.  The original case is a monster, takes months to run, and is impossible to debug.  After long effort on Isaac's part, he got a case that runs fairly quickly (10 min) and demonstrates the difference in MLR.  The case is attached.

[test.fds.txt](https://github.com/firemodels/fds/files/944100/test.fds.txt)

It took some time, but I bisected the problem and found this commit made the marked difference.

https://github.com/firemodels/fds-smv_deprecated/commit/33db9c1bef1668704194abd2e9869d8be3e2a9ac

Here is a plot of the results for several versions of the code.  The last line is the first "bad" commit.

![pmma_mlr](https://cloud.githubusercontent.com/assets/4418497/25238746/382cffb2-25bc-11e7-92b7-4bfa68a76cce.png)

There is also a subsequent commit in which Jason removes the MW from K_TMP.

https://github.com/firemodels/fds/commit/1ca4d715ba3ce102cdc69cf1dcdd8dcff469bbfe

...which is where the current code stands.

The dilemma is that Isaac sees much better validation results with the old code.  We might say that the new code is better because it passes our current set of verification tests.  But I would not be surprised if there is something amiss somewhere that we are not catching with our verification tests, none of which are squarely focussed on gas phase / solid phase coupling.

It is confusing to me why K_USER would need to be divided by MW but the other K would not when MU has the correct units.

**Comment by drjfloyd** [comment]
Both are divided by MW. The MU_TMP has  /SQRT(SS%MW) in it.

IF (SS%K_USER>=0._EB) THEN
   K_TMP = SS%K_USER / SQRT(SS%MW)
ELSE
   K_TMP = MU_TMP*CP_TMP/SS%PR_GAS !MU_TMP divided by SQRT(SS%MW)
ENDIF

I'll take a look at the case and check to see if bad K or MU values result from the way species are defined.

**Comment by drjfloyd** [comment]
I ran the attached test case which is a 2D domain that use INIT to make regions with different initial mass fractions of AIR, MMA, and PRODUCTS.  I don't see anything that looks incorrect with the thermophysical properties that result.
[species.fds.txt](https://github.com/firemodels/fds/files/944385/species.fds.txt)

**Comment by rmcdermo** [comment]
I can see this now, but I think the comments could be improved.  They made sense to me a year ago, but now they are confusing.

It also scares me when I see the division done differently in different places.  After the call to CALC_GAS_PROPS, from which K_TMP and MU_TMP emerge divided by MW, if there is a ramp we again divide by MW.

```
      IF (SS%RAMP_K_INDEX>0)   K_TMP(N)   = EVALUATE_RAMP(REAL(J,EB),1._EB,SS%RAMP_K_INDEX)/SQRT(SS%MW)
      IF (SS%RAMP_MU_INDEX>0)  MU_TMP(N)  = EVALUATE_RAMP(REAL(J,EB),1._EB,SS%RAMP_MU_INDEX)/SQRT(SS%MW)
```

Any chance this was not changed a year ago when it should have been?

**Comment by drjfloyd** [comment]
We aren't dividing again.  If there is a RAMP we are setting K_TMP or MU_TMP anew.  I agree though, it is confusing.  I can clean it up and just get one location after all the various ways of defining K and MU where we do the SQRT division.

**Comment by rmcdermo** [comment]
If it's correct, right now I'm ok.  I'm more worried about the pyrolysis case.  Isaac just published a paper in FSJ with his results.  Plus he's about to talk at FM again saying that old results are correct and the new results have a problem.

**Comment by drjfloyd** [comment]
How were the &MATL A and E for these cases developed?  Were they tuned for that version of FDS the case was first created for?

**Comment by rmcdermo** [comment]
This is a PMMA that Stas and Isaac worked with at UMD (I think).  But I can ask.  Should the MU and K in gas phase change these parameters?  One of the problems is that all the "validation" we have, for example, FAA_Polymers, rely on EXTERNAL_HEAT flux for the heat transfer.  So, we never catch major changes to gas phase feedback to the surface.

**Comment by rmcdermo** [comment]
It is curious to me that we never saw problems with the pool fire cases (liquid evap).

**Comment by drjfloyd** [comment]
I ran my test case with FDS 6.3.0.  I get the following values of CONDUCTIVITY for regions initialized with 100 % of the species.

Species, 6.3.0, 6.5.3
Air,0.0288,0.0254
MMA,0.0288,0.046
PRODUCTS,0.0288,0.023

Something was not right in earlier versions as all the conductivity values are the same. I get similar results for VISCOSITY, but SPECIFIC HEAT is OK. 

When I run your test case with 6.3.0, I see much higher temperatures. It is also much slower as the initial time step is two orders of magnitude lower.

**Comment by rmcdermo** [comment]
Yes, I too noticed the very slow time steps, though did not seem to be the case with version 6.1.2 (still pondering that difference as well).

I could probably be convinced that problem may be one of time resolution for latest code.  I'll try a case with very small time steps and see if that does anything different.

**Comment by drjfloyd** [comment]
I added the lines below and ran with both 6.3.1 and 6.5.3.   The early values of MU and K are pretty close, minor differences but not unexpected since there is the change to how we did species weighting so AIR is slightly different.  The Q is different by orders of magnitude between the cases.  At 3E-5 s 6.3.1 has Q=680 kW/m^3 and 6.5.2 has Q=0.104 kW/m^3.  Whatever the root cause is (pyrolysis and/or combustion routine) this difference is far larger than I would expect to happen due to a slight change in K and MU. 

&TIME T_END=0.001,DT=0.00001  /
&DEVC XYZ=0.001,0.005,0.0048,QUANTITY='HRRPUV',ID='Q1'/
&DEVC XYZ=0.001,0.005,0.0048,QUANTITY='TEMPERATURE',ID='T1'/
&DEVC XYZ=0.001,0.005,0.0048,QUANTITY='CONDUCTIVITY',ID='K1'/
&DEVC XYZ=0.001,0.005,0.0048,QUANTITY='VISCOSITY',ID='MU1'/
&DEVC XYZ=0.001,0.005,0.0048,QUANTITY='MASS FRACTION',SPEC_ID='MMA',ID='MMA1'/
&DEVC XYZ=0.001,0.005,0.0048,QUANTITY='MASS FRACTION',SPEC_ID='PRODUCTS',ID='PROD1'/

**Comment by rmcdermo** [comment]
Smaller DT does not change 6.5.3.  I ran at DT=1E-5 s, same result.

**Comment by rmcdermo** [comment]
I would have thought this was due to removing the HRR limiter, but we did that in 6.3.0.   So, I'm still scratching my head.

**Comment by leventon** [comment]
Could you check the MMA diffusivity (D, Diff. Coeff.), in the output file of your 6.3.0 simulation? It may not match the desired input value.

If I remember correctly, I ran simulations in 6.3.2 that produced incorrect values of D (but only when you explicitly defined diffusivity on the SPEC ID line). That is, in FDS 6.3.2 diffusivity appeared to be multiplied by the species' molecular weight, MW:

D(from .out file) = [MW] * [D(from .fds file)]

**Comment by drjfloyd** [comment]
6.3.1 is D=4.36E-3 which is MW_MMA * the specified value.  6.5.3 has the correct value of 4.35E-5.  So we'd have a much smaller TAU_D for 6.3.1 and more Q as a result.

**Comment by rmcdermo** [comment]
Well, that sounds like the culprit to me.

@leventon Where do you want to do from here?

**Comment by leventon** [comment]
That explains the odd behavior in 6.3.1 (small time step, different Q) but that unexpected scaling of diffusivity (D*MW) no longer exists in 6.5.3. Thus, I remain unsure as to what continues to give us the divergence in total mass loss rate (and heat transfer at the base of the flame) in 6.5.3 simulations of different grid resolution and vs. those performed in 6.1.2.

**Comment by rmcdermo** [comment]
@drjfloyd Wouldn't the D*MW error have been present in 6.1.2 also?  My interpretation of this is that TAU_D was too small before 6.3.2.  This error was fixed in commit discussed above.

**Comment by rmcdermo** [comment]
This is what happens when D*MW is used in latest version of FDS.  I can't immediately explain why it even overshoots the 6.1-6.3 results.  Maybe something to do with K as well.

![screen shot 2017-04-21 at 12 19 52 pm](https://cloud.githubusercontent.com/assets/4418497/25286758/db4e7f7e-268c-11e7-995a-2e3c2037ba8b.png)

**Comment by mcgratta** [comment]
K as in Kevin, or K as in thermal conductivity?

**Comment by rmcdermo** [comment]
Haha... it's not all about you.  But if you have any ideas feel free to chime in.  We need to get this buttoned up.

**Comment by rmcdermo** [comment]
It would also be nice to have some closure on this before the next release.

This actually affects pyrolysis more than normal design calculations.

**Comment by drjfloyd** [comment]
FDS 6.1 used a mass weighting for viscosity.  6.3 added the new weighting based on the mole fraction and square root of MW.  That initially had an error in it (the extra MW factor) which resulted in a mixing time issue.  I would suggest running a case with 6.1.2 and the current release and looking at a slice of mixing time and viscosity values. Up until the point where a significant amount of combustion products are present, these values should be close.  Between 6.1.2 and the current source I think we also made a number of changes to the integrator in the combustion model.

**Comment by rmcdermo** [comment]
Is this not as simple as proving that the fluid properties we are using are correct?  I suggest a verification case or set of cases that compares FDS output with the NASA tables or whatever.  There is no reason to do code to code comparisons.  Nothings says the old code was right.  That is what Isaac is arguing for.

**Comment by drjfloyd** [comment]
I guess that depends on what is meant by closure. If closure is does the current code give the correct viscosity, I am pretty sure now it does. The viscosity values noted in the comments above (which we compute with the Lennard-Jones model) compare well with values you see in handbooks.  If closure is answering why 6.1.2 had a "good" results and 6.5.3 has a "bad" result, just knowing the viscosity is good in 6.5.3 doesn't give closure. If 6.1.2 has similar viscosity and mixing time values to 6.5.3 then the reason for the difference lies elsewhere in the code.

**Comment by rmcdermo** [comment]
For the purposes of this Issue, I'd like to have closure on the physical properties through a verification case(s) over the range of temps, etc. that we will encounter.  The reason this is related to the inconsistent pyrolysis results is that it is the aforementioned commit--which touches the transport props--that makes the marked difference in the results.

Now, as usual, if we had two wrongs making a right, then we just have to fix the problem we know about and keep searching for the other.

What makes me nervous is that when I look into the output of the values in dump, they are not taken from GET_VISCOSITY, etc., they are taken from the initial tables that are used in GET_VISCOSITY.  It is not outside the realm of possibility that the weighting in the GET_VISCOSITY function has a bug.  (I don't suspect it does, but I want to button this up.)

Here is what I suggest: Let's change the dump routine to use GET_VISCOSITY, GET_CONDUCTIVITY with ZZ_GET set to pure N.  Then add a verification case for the props.

**Comment by drjfloyd** [comment]
Forgot about this one. Changed all the calls for the .out file to use the func.90 routines rather than the arrays and created species/species_props,fds to test mixtures of mu, k, and cp.
