### ISSUE TITLE
RAMP_CP_L does not appear to have a function

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#4993]
I cannot see if `RAMP_CP_L` is ever used. If not, I wouldn't mind dropping it.

**Comment by mcgratta** [comment]
Also, check changes I made in  #4992.

**Comment by drjfloyd** [comment]
We allow users to specify temperature dependent properties for pretty much everything else.  If it isn't used it is either an oversight or got mistakenly deleted at some point.  I'll add it in so it is available.

**Comment by mcgratta** [comment]
OK, and add it back into the User's Guide. I commented it out for the moment.

**Comment by drjfloyd** [comment]
Thanks for the rewrite, I think it is a lot clearer.  I made a couple of minor edits and added back RAMP_CP_L (also edited read.f90 to get it enabled)
