### ISSUE TITLE
Unstable pressure when only a HVAC DUCT used

### ISSUE THREAD

**Issue by chulann** [firemodels/fds#4997]
Hi,
We've noticed some strange fluctuations in a mesh which only has an open DUCT. We've cut down the case to a simple mesh, with a single DUCT and the corresponding VENT at high level in the mesh. The pressure should be 0, since nothing is happening, but fluctuates wildly (+/- ~100 Pa).

Interestingly, we had FDS 6.2.0 available and ran it with that and the results are what we would expect - ~0 Pa.

Attached is the FDS file used and DEVC results of a pressure monitor for both (I thought Github now allowed attaching FDS files? It wouldn't let me, hence the .zip)

[shaft.zip](https://github.com/firemodels/fds/files/951593/shaft.zip)

**Comment by rmcdermo** [comment]
Jason,
Can you have a look?  Or I can bisect.  Let me know.

**Comment by sbenkorichi** [comment]
Fyi:
Github doesn't support .fds for future submissions change .fds to .txt

**Comment by drjfloyd** [comment]
I'll find some time this week to look at it.

**Comment by drjfloyd** [comment]
Setting HVAC_PRES_RELAX=1 gets this case to run fine.  Not a very satisfactory answer as I don't know of specific guidance that can be provided in advance as to if HVAC_PRES_RELAX needs to be increased or decreased from its default of 0.5. This parameter was added just after the release of FDS 6.2.0.

Ultimately I think I need to revisit how HVAC is coupled to FDS.
