### ISSUE TITLE
Select SLICE on single plane across several meshes.

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#5001]
This is for Glenn, switching from email to issue tracker.
It would be nice if we can select in Smokeview a _particular SLICE_ among several meshes for boundary slices. Check this picture on our Vettori Sloped case:
![screen shot 2017-04-24 at 3 17 22 pm](https://cloud.githubusercontent.com/assets/7450069/25354725/188b92d8-2902-11e7-8191-4d38e588c764.png)
In the menu, instead of having TEMPERATURE SLICES on all Meshes or a particular single mesh, I would like an option to give me the SLICE across all meshes through x=3.68 for example. I might have several SLICES and meshes and its cumbersome to build the slice at x=3.68, selecting it single mesh by single mesh.
Let me know what you think.

**Comment by gforney** [comment]
marcos, can you point me to the full path to the .smv file for the case you were showing me in your office.

**Comment by marcosvanella** [comment]
Hi Glenn, you can run this input file in fds compiled from my fork. The smv files are on my mac.

[Vettori_Sloped_13OFD.fds.txt](https://github.com/firemodels/fds/files/953172/Vettori_Sloped_13OFD.fds.txt)

**Comment by gforney** [comment]
marcos,
lost track of this issue - where do we stand?
glenn

**Comment by gforney** [comment]
I'm going to close the issue.  reopen if it is still a problem.
