### ISSUE TITLE
Revive Lattimer Tilted Wall validation case for CC IBM

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5006]
Marcos,
There is a case in Validation called Lattimer_Tilted_Wall.  Along with Vettori Sloped Ceiling, this would be a good validation case for CC_IBM.

**Comment by marcosvanella** [comment]
I'll check it out.

**Comment by rmcdermo** [comment]
It's not a super high priority.  Just wanted to get it in the queue.

**Comment by marcosvanella** [comment]
Ok. 

Looks like this case is not currently being added on the Validation Guide. I can't find a description of the problem setup.

**Comment by rmcdermo** [comment]
I'm not sure if Brian Lattimer ever published the work.  The data I have is on blaze here:

/home/rmcdermo/FDS-SMV/Validation/Lattimer_Tilted_Wall/Experimental_Data/

There are a host of Excel files and a few .csv I created to start to get things in shape.

There is also a talk that has the most up-to-date information (aside from the input files) here:

/home/rmcdermo/Talks/FM_2013/FM_2013_beamer.pdf

Past that we will likely have to contact Brian.  But let's see what we can cobble together.  Again, don't let this derail you.

**Comment by rmcdermo** [comment]
Closing this for now.  We may revisit once CC-IBM is working.
