### ISSUE TITLE
Update Wiki page: Installing openmpi on a linux cluster

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5009]
Reading the page instruction, one could find only how to do it using intel compiler. As we know, not most of the user might afford it.
I therefore, would request to include how one can compile it with gnu compiler as well.
I'm happy to provide simple steps for its process if you would like to include it.

Regards,
Salah

**Comment by gforney** [comment]
go ahead.  thanks.
glenn

**Comment by sbenkorichi** [comment]
Thanks Glenn, I will comment it here later.
Cheers
Salah

**Comment by sbenkorichi** [comment]
Please do review it, and see if there is anything wrong or something needed to added or changed.

I would suggest to split them into two categories, one for intel and the other for gnu.
**1.Compiling Open MPI and FDS with intel compiler**
....
....
**2 Compiling Open MPI and FDS With Gnu Compiler**

1.Install the gfortran compiler.
In case you have other than 4.8 or 4.7 , you should uninstall it:
To know which version you have installed type : 
`$gfortran --version`
in case you find it different, then type: 
`sudo apt-get remove gfortran`
To install gfortran type : 
`sudo apt-get install gfortran-4.8`

create symbolic link to gfortran : 
`sudo ln -sfn /usr/bin/gfortran-4.8 /usr/bin/gfortran`
This would make gfortran in the same version being installed i.e. 4.8

2. Download and extract the latest version of [Open MPI](https://www.open-mpi.org/).

3. cd to the directory that you extracted Open MPI to.

4.Install Open MPI using the gnu compiler; configure and install using:

`./configure CC=icc CC=gcc --enable-mpi-fortran --enable-static --disable-shared -disable-dlopen --prefix=/shared/openmpi_64`

then type

```
make
sudo make install
```
5. export some paths to your .bashrc file in your home directory: 
```
export MPIDIST_ETH=/shared/openmpi_64
export LD_LIBRARY_PATH=$MPIDIST_ETH/lib
source ~/.bashrc_fds $MPIDIST_FDS
```
save it and log off and log in again.

6. Build the FDS Linux version from the firemodels/fds repository:

cd Build/mpi_gnu_linux_64
./make_fds.sh

**Comment by gforney** [comment]
is your conclusion that openmpi only works with gfortran 4.7 or 4.8? Do we need to refer to a specific versoin of the gnu compiler?

comments:
1.  MPIDIST_ETH was set up in our repo to refer to the ethernet Intel build of openmpi for use by the ethernet openmpi build of fds.  So is not needed here (or if needed by the gnu build should be renamed to reflect that it is referring to an gnu openmpi library
2.  CC=icc shouldn't be in configure script, it refers to the Intel C compiler
3.  would rather not use /shared/openmpi_64 , we've been using that for the ethernet openmpi build

**Comment by sbenkorichi** [comment]
Yes Glenn, the user has to use either of these, I didn't test 4.6 though. However, from 4.9 up to 6, all would result in error.
I would also point out that it's crucial for the user to create that symbolic link after installing fortran-4.8 or 4.7
So, when testing gfortran --version, would give these same versions, otherwise, gfortran might be 5 or 6 even though 4.8 is installed, so before configuration, the user has to make sure that gfortran --version would give 4.8.5 or 4.7 if not the configuration for openmpi wont succeed. 

1. Umm, Yes, it can be changed to libraries or other naming, I've just took it as an example from the intel setup. What's important is that one has to make sure there is a target after ~/bashrc_fds, otherwise, it would halt in the initialisation process for around 18 minutes to get it running.
source ~/.bashrc_fds $MPIDIST_FDS

2. Yes, no need for CC=icc.

3. For the /shared/openmpi_64, is just was following the standard with intel. It can be done at the home directory (as I was testing them), say for example  ~/openmpi 

Right now, I can run both the intel and gnu compiled version, all what I have to do is to change the exported path when switching from one to another and they work fine.

**Comment by sbenkorichi** [comment]
Glenn, 
Feel free to close it if you have nothing to add or modify.

Cheers,
Salah
