### ISSUE TITLE
Problem with devices

### ISSUE THREAD

**Issue by RakeshRanga** [firemodels/fds#5011]
Hello Sir !!
I am trying to study the downward flame spread over a 1.6 mm thick PMMA sample. I have used symmetric case here (using MIRROR). I first ran a case to check if is working properly. Later I started another case where I added a lot of devices (about 900 of them) to monitor various parameters.
What had run successfully without devices, when I put the devices the flame put off.
Please find attached the txt files of both with devices and without devices. 
May I please know the reason for the flame to put off if I put devices ?
Thank you.
Regards,
RakeshRanga
[Pmma_withDevices.txt](https://github.com/firemodels/fds/files/957477/Pmma_withDevices.txt)
[Pmma_withoutDevices.txt](https://github.com/firemodels/fds/files/957476/Pmma_withoutDevices.txt)

**Comment by sbenkorichi** [comment]
I wonder why you are still using restart with igniter particles. Didn't Kevin, explain to you last time that this would result in an error in this current version?
One simple way I would suggest for you, is to start putting devices bit by bit untill the issue occurs, then it would be helpful for the members to look at it. Sending 1200 lines codes won't be much helpful. We encourage for users to simplify their input files as much as possible.

**Comment by sbenkorichi** [comment]
I've tested for few seconds, both cases do have flame in them.
Can you explain what do you mean by "the flame put off" ? If this happens at specific timing please do specify it.

**Comment by RakeshRanga** [comment]
I am so sorry for the absurdity of my question. 
The code I have attached was an old one. After Kevin told me, I am not using the restart feature. I am running it on a cluster in my university.
So is there a possibility that the number of devices used might affect the result? If yes how do I monitor the various parameters?
I apologize again for wasting your time with the previous question.
Thank you.
Regards,
RakeshRanga

**Comment by sbenkorichi** [comment]
Did you see my previous question?
I've tested both cases and I see flame in them. Including devices does the flame appear in smokeview or not? If it appears and then turns off due to adding these devices, can you specify at what time did you experienced this?

**Comment by RakeshRanga** [comment]
Sorry Sir !!
In both the cases, the igniter particles are active till around 34 seconds, after which I have ramped down their temperature to 0 using RAMP_T by 36 seconds. Now, in the case where there are no devices, after 36 seconds, the flame is sustained and the PMMA continues to get consumed till the end. Whereas in the case where there are monitors, after 36 seconds the flame begins to die out and is completely off by 38 seconds i.e. there is no sustained flame (like I had obtained in the previous case).
I wanted to know whether or not the addition of devices is causing this?
Thank you.
Regards,
RakeshRanga

**Comment by mcgratta** [comment]
These cases are not the same:
```
< &INIT XYZ=0.001,0.001,0.148, DY=0.005, PART_ID='ignitor particle', N_PARTICLES=5 /
< &INIT XYZ=0.00075,0.001,0.151, DY=0.005, PART_ID='ignitor particle', N_PARTICLES=5 /
---
> &INIT XYZ=0.001,0.002,0.148, DY=0.005, PART_ID='ignitor particle', N_PARTICLES=4 /
> &INIT XYZ=0.0025,0.002,0.148, DY=0.005, PART_ID='ignitor particle', N_PARTICLES=4 /
> &INIT XYZ=0.00075,0.002,0.151, DY=0.005, PART_ID='ignitor particle', N_PARTICLES=4 /
```
