### ISSUE TITLE
HT3D Numerical Instability

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5021]
Hi everyone!

I am testing the HT3D Beta feature using some materials and a kind of furnace, derived from the example "ht3d_slab.fds". I performed this exercise to see the capabilities of this new feature on stationary regime. 

- I performed a first exercise, using a high conducting material (300 W/m K) and the results can be compared with a Fourier-Law simple calculus. 

- Then I've tried to use a material similar to bricks, with a lowest thermal conductivity (0.336 W/m K), but I had numerical instability, also trying to simplify the exercise or removing a piece of hot vent surrounding the hot face. There is an oscillating temperature on the solid hot face, that goes over the temperature of the furnace... (I can win a Nobel prize for this research result! :) )

- In third exercise, I tried to use a bigger thermal conductivity, but with lower specific heat (not real, just to speed up the stationary regime..): there wasn't strange temperature behaviour on the solid hot face and the results can be compared with Fourier-Law calculations.

- In fourth exercise, I changed only the specific heat (as the real material one) and there is another different strange behaviour of the temperature on hot solid face... In a first time the temperature goes up to 450°C then jump down to 270°C and also NET_HEAT_FLUX on that face has a strange behaviour.... This does not drive to a numerical instability, but it is not real..

Please, can you verify if there is any strange bug in this new HT3D Beta Feature with low thermal conductivities?

Thanks for your support!

Vincenzo Cascioli, PhD

[fdssmvht3dnumericalinstability.zip](https://github.com/firemodels/fds/files/966101/fdssmvht3dnumericalinstability.zip)

**Comment by sbenkorichi** [comment]
I'm looking up to this case.
First, your are putting two INIT lines at same time. Remove one, ( usual one will be ignored by default).
To fix the issue of numerical instability, remove DT from the time line. This should fix it. 
I will try to look up the 4th case.

**Comment by sbenkorichi** [comment]
Case 4:
Just take out the DT again, and leave the case run for a while, because the file will be re-uploaded again. 
I don't see any jumping for temp. You can check the attached image.
PS: I'm running the cases with the latest code. 

![front_tmp](https://user-images.githubusercontent.com/20113030/29470408-3e795ac8-8444-11e7-84e0-f54e85c7e21e.png)

@rmcdermo  When, you're back, review this, and might close it afterword.

**Comment by rmcdermo** [comment]
@sbenkorichi What is status of this issue?

**Comment by sbenkorichi** [comment]
I don't think there is an issue with the code. The user has to take off DT from timeline and all are good. I haven't get any numerical instabilities with the different cases.

**Comment by rmcdermo** [comment]
OK, user can reopen if necessary.
