### ISSUE TITLE
Ignition issue

### ISSUE THREAD

**Issue by RakeshRanga** [firemodels/fds#5022]
Hello !
I am trying to ignite PMMA for a downward flame spread study. I am doing a symmetric case, considering only half thickness and half width. For ignition I have used igniter particles like in couch.fds. 
In this case I have RAMPed down the temperature of the particles to 0 at 36 seconds. 
When the particle is there, already around 5-6 mm had burnt away. So I thought the PMMA would have been ignited and removed the particles. But later it was extinguished within 3 seconds.
The igniter particles I gave were 2 mm diameter spheres.
Please find attached the txt file of the code for the same.
I also wanted to know, for the location of the igniter particles, the XYZ values we specify for the sphere, does it correspond to the center of the sphere?

Thank you.
Regards,
RakeshRanga
[PMMA.txt](https://github.com/firemodels/fds/files/966744/PMMA.txt)

**Comment by sbenkorichi** [comment]
So, I presume the other issue of adding devices is fixed with Kevin's suggestion? If so then you might close it.

**Comment by RakeshRanga** [comment]
Oh yes !! I will definitely do that.. Sorry !!!

**Comment by sbenkorichi** [comment]
REFERENCE_TEMPERATURE=250.
Where did you get this value from? Have you conducted experiment on it or you have a reference?
Check section 8.5.2.
Your material needs sufficient emery to burn. No wonder when you remove that igniter it would stop.

**Comment by RakeshRanga** [comment]
In the formula for the reaction rate, equation 8.10, there is a mention of
'Pyrolysis Range'. Therefore I used the pyrolysis temperature as the
reference temperature. The pyrolysis temperature was obtained from
literature.
It is wrong to use pyrolysis temperature in place on reference temperature?

Thank you.
Regards,
RakeshRanga

**Comment by sbenkorichi** [comment]
Since you are depending on literature, why dont you then specify the activation of energy and the exponential factor without the reference temperature. Verify the value of the heat of reaction.

**Comment by RakeshRanga** [comment]
In the literature the kinetic parameters are specified in the the form the
equation for mass flux. So the pre-exponential factor in the equation for
mass flux has kg/m^2 s. From this how do I get the units of (1/s) that has
to entered in FDS?

Thank you.
Regards,
RakeshRanga

On Sun, Apr 30, 2017 at 10:59 PM, Salah Benkorichi <notifications@github.com

**Comment by sbenkorichi** [comment]
You might check the Cone calorimeter or TGA data.

**Comment by RakeshRanga** [comment]
Ok. Will look into it.

Thank you.

On Sun, Apr 30, 2017 at 11:25 PM, Salah Benkorichi <notifications@github.com

**Comment by sbenkorichi** [comment]
Check Nicolas Bal's Thesis. I think this should be asked in the discussion group rather than submitting an issue.

https://www.era.lib.ed.ac.uk/bitstream/handle/1842/6511/Bal2012.pdf?sequence=6&isAllowed=y
