### ISSUE TITLE
Remove orientation (IOR) from PYROLYSIS subroutine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5025]
I'm cleaning up the `PYROLYSIS` subroutine in `wall.f90` to make way for cut-cell processing. In particular, I want to eliminate references to orientation, since this routine should not depend on this as particles and cut-cells do not have rectilinear orientation. I removed all references to `IOR` except for here:
```
! If 3D heat transfer coupling, store solid cell mean chemical source term

PYRO_HT3D_IF: IF (PYROLYSIS_HT3D) THEN

   IF (IOR==1) THEN
```
Is there a way to eliminate orientation from this part?

**Comment by rmcdermo** [comment]
At the moment this would be hard---HT3D is not meant to be compatible with CC IBM in the short term.    But leave this open and I'll work on it.

**Comment by mcgratta** [comment]
What probably needs to be done is to break up the subroutine `PYROLYSIS` into two parts -- one that computes the solid reaction source term and one that computes the 1-D heat conduction, using that source term. The `HT3D` heat conduction would be done in another routine, which would call the reaction source term routine too.

**Comment by rmcdermo** [comment]
I think this is done.
