### ISSUE TITLE
NET_HEAT_FLUX (etc.) options with a heat conducting (layered) solid surface

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#5032]
I have been running some test problems related to heat conduction and have a question about intended behavior for the NET_HEAT_FLUX, CONVECTIVE_HEAT_FLUX, TMP_FRONT, and EMISSIVITY options when applied to a heat conducting solid surface.

If you apply the ADIABATIC keyword to a heat conducting solid surface, FDS generates an error message. This makes sense.

FDS does not generate an error message when one specifies the NET_HEAT_FLUX, CONVECTIVE_HEAT_FLUX, TMP_FRONT, or EMISSIVITY keywords on a heat conducting solid surface. I did test, and these keywords appear to be ignored even if they are defined. See the file with NET_HEAT_FLUX defined.

Is the intended behavior to ignore the NET_HEAT_FLUX, CONVECTIVE_HEAT_FLUX, TMP_FRONT, and EMISSIVITY keywords on a heat conducting solid surface? I can certainly understand that approach. If so, it would be nice to issue an error similar to that for ADIABATIC.

Thanks,
Dan Swenson

[layered_net_heat_flux_1.txt](https://github.com/firemodels/fds/files/971037/layered_net_heat_flux_1.txt)

**Comment by rmcdermo** [comment]
I don't think these boundary conditions should be ignored.  If the surf conducts heat, those are all valid parameters.  We'll look at the case.  Thanks.

**Comment by dvswenson** [comment]
Thanks. Here are some more test cases.

Case "layered_Tcalc_mate_7_surfe_3.txt" shows that the radiation calc uses the emissivity defined by the material, even if you define a different emissivity for the surface. The material emissivity is 0.7, the surface emissivity is 0.3.

Case "layered_total_heat_flux.txt" uses TMP_FRONT, EMISSIVITY, and CONVECTIVE_HEAT_FLUX, but they are not recognized.

I am running:
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Fri 01/20/2017  09:11 PM

[layered_Tcalc_mate_7_surfe_3.txt](https://github.com/firemodels/fds/files/971110/layered_Tcalc_mate_7_surfe_3.txt)

[layered_total_heat_flux.txt](https://github.com/firemodels/fds/files/971117/layered_total_heat_flux.txt)

**Comment by rmcdermo** [comment]
@mcgratta Kevin, can you look at this until I get back from FM.  I can take over then if it is still open.  Thanks.

**Comment by drjfloyd** [comment]
Kevin+Randy,

For NET_HEAT_FLUX, CONVECTIVE_HEAT_FLUX, and TMP_FRONT we are forcing the front surface temperature to obtain the desired input. There isn't any reason we couldn't then conduct into the surface based on that temperature, but does that have any meaning for a real problem?

Dan,

EMISSIVITY on SURF was defined so that when one is using one of the surface temperature/flux inputs that you could get the correct radiative heat flux based without having to specify material properties on another input.  I think we always intended that if you defined material layers, that the material would take precedence.  If this isn't called out in the User'S Guide, we should probably add it.

**Comment by rmcdermo** [comment]
Well, we use these boundary conditions for conduction verification tests.  Off the top of my head, I'm using TMP_FRONT for Verification/Heat_Transfer/ht3d_ibeam.fds  These might be used in 1D verification as well.

**Comment by mcgratta** [comment]
This is the error message that you will see for case 1 and 3:
```
ERROR: SURF Layered Total Heat Flux cannot have a specified flux or temperature and a MATL_ID
```
For the case of multiple `EMISSIVITY` inputs, the `MATL` takes precedence.

Let me know if you can find any other obvious input errors and I'll add them.

**Comment by dvswenson** [comment]
Thank you, we will update the PyroSim user interface to match this.
