### ISSUE TITLE
Smokeview - Averaging slicefile

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5039]
Here are the steps to reproduce the error:

1.
> Calculate the fds file
> Run the .smv file. 
> Menu>Load/Unload>Slice file>Temperature>Load all

It loads velocity slice file instead of temperature

2.
> Calculate the fds file
> Run the .smv file. 
> Menu>Load/Unload>Slice file>Temperature>X=5.9
> Menu>Load/Unload>Slice file>Temperature>Y=1.6
> Menu>Dialog>data bounds>slice>average > 3 seconds

Only Y slice is averaged, but not X. 

 [Nozzle-test.fds.txt](https://github.com/firemodels/fds/files/975623/Nozzle-test.fds.txt)
 
Smokeview:6.4.4-46-g1a60197
FDS: 6.5.3-598-geb56ed1

Thank you!

**Comment by sbenkorichi** [comment]
Thanks for reporting it.
Apparently there is an issue with somekview when you use load all for temperature. Single profile works, as for all doesn't. One of the members will take a look.
PS: Even this happens under my previous compiled smokeview (April 29).

**Comment by gforney** [comment]
I'll take a look

**Comment by sbenkorichi** [comment]
Glenn,
I've simplified the file. See the attached copy.
I've tested previous versions. I dont think it's coming from smokeview itself. 
Tested other files with using both Temperature and Velocity, this issue doesn't appear.
Commenting the velocity vector line, doesn't produce this issue. 
I don't know why somehow, by checking all temperatures, you get velocity instead.

[Nozzle-test.fds.txt](https://github.com/firemodels/fds/files/975779/Nozzle-test.fds.txt)

**Comment by Er9y714** [comment]
Thank you for simplifying. It is useful for first issue. In order to see the second issue, there needs to be some value.  So I suppose the original will be necessary for the second one.

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Well done Glenn,
That has fixed it.

**Comment by Er9y714** [comment]
Thank you Glenn! Both errors are gone.

**Comment by gforney** [comment]
thanks for reporting the problem .  The bug goes back at least 2 years.

**Comment by sbenkorichi** [comment]
That's interesting. I went back up to 6.2 or stg and all failed so I doubt it. Another reason I found I works with other situations but fails to run with this file. Is it possible to share what was the root cause for this conflict between temp and velocity ?

**Comment by gforney** [comment]
Just a bug in how I was constructing the slice menus for temperature vs
velocity slice bug. For average bug I was only averaging last loaded slice
instead of all loaded slices

**Comment by sbenkorichi** [comment]
Thanks Glenn.
