### ISSUE TITLE
Low CO results with EXTINCTION 5

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5040]
@drjfloyd 

Attached are results for NIST_FSE_2008 for current default (SUPPRESSION_FALSE) and EXTINCTION 5 (EXT5).  When you unzip the folder you should see two sets of results.  I'm focussing on a single case, ISOHep9, because it has a reasonable amount of CO and the correlation between CO and O2 is obvious.

You can see in this case that CO is too low and O2 is too high, while CO2 is good.  Though this is for a single case, in each folder I include the scatterplot for CO.  The trend is clearly that EXT5 is not generating enough CO.

Pease have a look at the input file for ISOHep9 with EXT5 and see if I've made any obvious mistakes.  Any other thoughts on where to go next are welcome.

[NIST_FSE_CO_Results.zip](https://github.com/firemodels/fds/files/976747/NIST_FSE_CO_Results.zip)

**Comment by drjfloyd** [comment]
In extinction 5 either we let both steps go or just the second step. In the case of just the second step, I think one could argue that you would need the local temperatures to be hot (you would only have CO as a product of the first step).  What if we set the AIT for the CO step (I had found 610 C)?  Would that keep us from burning out the CO?

**Comment by rmcdermo** [comment]
OK, I will try adding AIT to CO.  Where did you find 610 C?  I did not see a value listed in Table 2.7-1 of the SFPE Handbook.

**Comment by drjfloyd** [comment]
https://en.wikipedia.org/wiki/Carbon_monoxide

**Comment by rmcdermo** [comment]
OK, just launched the cases again.  Fingers crossed.  If you have any other thoughts let me, I can run in parallel.

**Comment by rmcdermo** [comment]
Unfortunately, no improvement with adding AIT.

[Archive.zip](https://github.com/firemodels/fds/files/979405/Archive.zip)

Kevin and I were just talking about the approach.  It is not clear how we would produce CO at all.  In the first evaluation, if EXTINCTION=F, then would we not have both reactions go forward?  In what situation would R1 take place, but R2 not?

**Comment by rmcdermo** [comment]
@mcgratta 

Have you had a chance to look at NIST FSE 2008 results?

**Comment by mcgratta** [comment]
They look fine.

**Comment by rmcdermo** [comment]
OK, thanks.

**Comment by rmcdermo** [comment]
Actually, this should stay open.  The input files for release have SUPPRESSION=F.  I now remember that the point of this Issue to make the 2-step CO extinction model give reasonable results for these canonical cases.

**Comment by mcgratta** [comment]
We no longer set SUPP=F for the 2 step combustion cases. Now, 'EXTINCTION 1' is recommended for grid cells larger than 1 cm, and 'EXTINCTION 2' for less. LES and VLES still get 'EXTINCTION 2', and SVLES gets 'EXTINCTION 1'. When we do the next minor or major release, we can rethink this.
