### ISSUE TITLE
PARTICLES_PER_SECOND and TIME STEP

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5041]
Hi,

I have run a set of calculations to see the effect of PARTICLE_PER_SECOND on the cooling effect on air. I have varied the number from 250 to 10000. For this particular case it shows good convergence for average temperature at measurement plane. 

Meanwhile, I have noticed that the less number of particle I defined, the smaller size of TIME STEP it resulted. Therefore calculation took longer in the low number of particles. 

So I would like to know what is the reason behind of this. Is this a bad sign for calculation?

Thank you.

The base file can be found attached. Only PARTICLES_PER_SECOND was changed for each case.

Average outputs for steady state is seen below.

 PARTICLES_PER_SECOND 	 TIME STEP [s] 	 CFL MAX 	 VN MAX 	 WALL CLOCK TIME [s] 
250	0.0046818	0.69	0.31	1382
500	0.0055614	0.72	0.32	1126
1000	0.0069225	0.74	0.32	852
10000	0.0157502	0.87	0.27	383

[Particle number.fds.txt](https://github.com/firemodels/fds/files/976966/Particle.number.fds.txt)

**Comment by rmcdermo** [comment]
Jason,

Can you take a look at this when you get time.  I'm buried getting ready for FM.  Thanks.

**Comment by drjfloyd** [comment]
6.5.3 has the old evaporation model which sometimes had issues with evaporating lots of small particles.  That may be playing a role.  I 'll  take a look.

**Comment by drjfloyd** [comment]
I think this may just be spray resolution issue with the time step stability limits.  At 250 particles per second about 1 particle per time step is being inserted, so each timestep whatever cell gets the 80 micron particle sees all that momentum and all the evaporation.  Even at 1000 particles per second it is only about 10 particles per time step.   I ran the case for 4 s and got the following for the timings:

![image](https://cloud.githubusercontent.com/assets/12799217/25722810/77d63c46-30e3-11e7-8903-a14418e9ad0f.png)

If I make the droplets 800 microns, so evaporation and momentum transfer is slower, then the 250 particle per second case takes 284 timesteps vs. 625 for 80 micron.

**Comment by rmcdermo** [comment]
I'll have to think about this more---not time now.  But it would certainly be nice if we could give some guidance on how to optimize the particle insertion rate.  There must be a minimum for TOTAL TIME.

**Comment by drjfloyd** [comment]
There may be some dependence on the droplet size, thermal conditions, initial particle velocity, and overall fds time step size. For this particular case 10000 to 40000 yields similar times (within about 10 %) with the minimum time near 30000

**Comment by Er9y714** [comment]
Thank you for investing time on this. I hope it leads to some fruitful result. 

Speaking on guidance to use this feature, I have been thinking about that perhaps a guide can be created also for different geometries. For example, we know that tunnels are long compartments and usually it is favorable to divide it into few meshes. Then new problems arises. There are already many tips in the userguide regarding tunnels or multiple meshes but it would be much easier to collect them into one section as if a checklist before a project. Such as, high rise, tunnels, near wall interest, compartments without ceiling etc. 

It would be nice to have these guides for faster computation, higher accuracy...
If we as users can help (even in the initial phase), please let us know. 

Thank you.

**Comment by rmcdermo** [comment]
Providing guidance is certainly one of our goals.  But it is often hard when we do not have cases in our validation guide for a given type of problem.  Tunnels are the perfect example.  Because of this, we are hoping to work with @bmralph and others at U. Edinburgh to develop a tunnels chapter for the validation guide.  One could well imaging other examples as well---as you said, high rise buildings would also be a good contribution.  What we find it that the availability of validation-quality data is not as ubiquitous as one might think.  And without the data to validate the result, we have no business citing the example as good guidance.

**Comment by Er9y714** [comment]
I understand your situation and agree on being cautious giving guidance only with reliable validation. I look forward to seeing the work about the tunnels and wish you good luck.
