### ISSUE TITLE
Version mismatch for libiomp5md.dll?

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#5057]
Hi guys.
I compiled using Intel Fortan compiler version 17.0.2.187 (2017 update 2). Compiled successfully, but upon running I get an error fds:

"The ordinal 747 could not be located in the dynamic link library libiomp5mp.dll"

I used Dependency Walker and I think the error is related to a version mismatch (FDS shipped is 5.0... and my OS has 5.2...).

Any more information you need, or if I'm missing something obvious - let me know.

**Comment by sbenkorichi** [comment]
Is it Ubuntu which you are using ?

**Comment by bmralph** [comment]
Windows. Sorry; should have said.

**Comment by sbenkorichi** [comment]
I have'nt tried it under windows. I think I do have update 2. But now they have update 3. I will try to run under w10 if I can reproduce the issue I will let u know.
Salah

**Comment by drjfloyd** [comment]
I saw this error once before, and it turned out I had a dated version of that library in my FDS compilation directory.  Make sure the version corresponding to the one shipped with the compiler is being seen first be the exectutable.

**Comment by bmralph** [comment]
Thanks guys - the fds bundled binary directory was ahead of my compiler directory in my path environmental variables. I've moved them and the compiled .exe are now running.
