### ISSUE TITLE
Visualization of Human Density in smoke view

### ISSUE THREAD

**Issue by Akulachaturvedi** [firemodels/fds#5058]
Can we plot human density contour plot for any given evac mesh in Somkeview.

**Comment by tkorhon1** [comment]
Well, the only thing that is related to a human density is the OUTPUT_DENSITY (.TRUE. or .FALSE., false is the default) keyword on PERS namelist. The last value read in is used, if this keyword is given on many PERS namelists. The human density is then calculated around all agents. This is not a very exact calculation, if there is walls close by. In "open field" the density should be more or less a good number. You should not use this density to do any specific calculations or draw conclusions. It is just meant to illustrate the density. I.e., to produce nice pictures for the documents that a designer needs. Well, actually it was designed for me to see the density, when I was developing the counterflow model and the aiming towards the target doors. Both have some kind of density dependence.

Setting this keyword, you can colour the agents in Smokeview as density colorbar. You should select an avatar type that supports colouring, like "disk", "ellipsoid", "human_altered_with_data". The default avatar type does not support agent colouring.

TimoK

**Comment by Akulachaturvedi** [comment]
Thanks Timo. It was really helped me
I was trying to identify congestion areas i.e., according to latest IMO criteria "Congestion regions is identified by local population densities exceeding 4 p/m2 for significant duration".

Thanks again.
Regards,
Akula

**Comment by gjaeger** [comment]
@Akulachaturvedi You can use the prt5-file and JPSreport. [JPSreport](http://www.jupedsim.org/jpsreport/) implements different measurement methods to analyze pedestrian movement in different aspects and scales. You have only convert the prt5-file to a trajectory file for JPSreport.
