### ISSUE TITLE
Screen element 

### ISSUE THREAD

**Issue by shimjc** [firemodels/fds#5059]
Hi there,
I recently came across the screen element in FDS and noticed that as you vary the velocity in the model, the pressure loss coefficient of the screen varies as well. This should not be the case and that the pressure loss coefficient should be constant. 

I believe the issue lies with the defining equation shown attached. 
![screen_equations](https://cloud.githubusercontent.com/assets/28561874/25847153/d20005d6-34ac-11e7-8168-054506c8c934.png).

I believe a solution is to rewrite the equation described below.
![revised eq](https://cloud.githubusercontent.com/assets/28561874/25849510/b34b7cb0-34b6-11e7-994f-42b85dce8804.png)

Would be grateful if you could confirm this. Many thanks.

Regards,
Shim

**Comment by sbenkorichi** [comment]
Did you check section 8.6.1 from the technical manual?

**Comment by shimjc** [comment]
Hi there, thanks for the reply. 
I had read through section 8.6.1 of the technical manual but found nothing to explain the varying pressure loss coefficient with varying velocity.

Please see below an example of the calculation I have set up to assess this occurrence. 
<img width="292" alt="example1" src="https://cloud.githubusercontent.com/assets/28561874/25854312/768c6b16-34c7-11e7-95bf-5027365f54ec.png">
Zeta = pressure loss coefficient
F = free area fraction
The example first determine an appropriate F for an assumed zeta of 3 based on a constant velocity of 2m/s. F was calculated using excel goal seek to be 0.63.

The screen with this setting was then modelled using FDS to obtain the pressure loss at three respective velocities of 2m/s, 10m/s and 20m/s with the pressure loss summarised in the table.
The equation was then used to calculate the theoretical pressure loss. The later was in turn used to determine the zeta value - zeta = delta P/ (0.5*density*velocity*velocity).
The pressure loss predicted by the simulation and by the equation was comparable. However zeta was not. 

I have also added the input file I used for your reference.
[example input file.zip](https://github.com/firemodels/fds/files/986896/example.input.file.zip)

Thanks again for reviewing this.
Shim

**Comment by mcgratta** [comment]
How do you explain the fact that your proposed equation does not have the units right?

**Comment by shimjc** [comment]
Can you please be specific? units does match.

**Comment by mcgratta** [comment]
![image](https://cloud.githubusercontent.com/assets/11333911/25855644/c7ce2b0c-34a1-11e7-8902-8bccca857609.png)

What are the units that you assume for these variables?

**Comment by shimjc** [comment]
I apologies. my suggestion was wrong.

**Comment by shimjc** [comment]
Is there an explanation for the varying pressure loss coefficient?

**Comment by mcgratta** [comment]
If you are asking about the model we have chosen to implement in FDS, I suggest that you consult the references. If you think that the formula is not being implemented correctly in FDS, then I will check.

**Comment by shimjc** [comment]
Oh. the formula has been perfectly implemented in FDS. Allow me to review the references then. Thanks.
