### ISSUE TITLE
Smokeview - Boundary file between meshes

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5066]
When an &OBST spreads across meshes, additional surfaces appear while checking boundary file in smokeview. The additional boundaries appear only in the meshes where &OBST exists. 
To reproduce the situation:

> Run the fds file
> open smv file
> load any boundary file
> you will see the additional slices between meshes. 

smokeview: SMV6.4.4-490-g93f1fac
[test.fds.txt](https://github.com/firemodels/fds/files/989376/test.fds.txt)

Thank you for your support.

**Comment by Er9y714** [comment]
The issue is present in SMV 6.5.0 but not in SMV 6.4.4-46-g1a60197

**Comment by sbenkorichi** [comment]
Thanks for reporting it. 
This might be a bug appeared after Glenn fixed the previous one. 
Glenn will take a look once he's available.

**Comment by gforney** [comment]
Thanks, I will take a look at it.

**Comment by Er9y714** [comment]
I spotted something similar.  When there are two slicefiles (VECTOR=.TRUE.) at the same coordinates, 
the components of velocity (u,v,w) are shown separate for different meshes in Multi-slice menu.  

> Load/Unload
> Multi-slices
> U-velocity (or v or w)
[A.fds.txt](https://github.com/firemodels/fds/files/995448/A.fds.txt)
You will see three options, where there should be one. 
Smv-6.4.4-46-g1a60197
=================

Is it possible to have a dialog, where we can select and activate any slice file or boundary file by clicking ticks? I believe it would be helpful for activating or looking for specific one, slices could be selected by ticking instead of "right click>load/unload>slices" sequence. Also when there are high number of slices, it does not fit to screen and it takes time to scroll down.

Thank you.

**Comment by gforney** [comment]
I don't see the problem you are referring too.  Install smokeview 6.5.0 and let me know if you see the problem with it.

You can avoid the problem by using only one VECTOR statement per slice plane i.e.

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=2.4/ 
&SLCF QUANTITY='TEMPERATURE', PBY=2.4/  

not

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=2.4/ 
&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., PBY=2.4/  

The U, V, W slice planes generated for 'VELOCITY' can also be used for temperature

**Comment by Er9y714** [comment]
Hi, I checked with 6.5.0 and I still see the problem (of boundary file). The second issue with vectors, it works well with 6.5.0.

I did not know that temperature can use velocity vectors. 

Thanks for the reply and the info!

**Comment by gforney** [comment]
Do you see the problem if you only use one VECTOR=.true.?

**Comment by Er9y714** [comment]
That vector problem is gone with 6.5.0. 

I still have the problem with boundary view. (first post)
![image](https://cloud.githubusercontent.com/assets/26166281/26145388/908e6b74-3aec-11e7-8891-d4916fb61545.png)

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if you see any problems.

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
This to confirm, it's been solved under linux.

**Comment by Er9y714** [comment]
Works great! Thanks for the prompt fix!

**Comment by gforney** [comment]
Thanks for reporting back

**Comment by Er9y714** [comment]
I noticed that every time I run the smokeview (the version you shared), a file is created with a long name  that has random letters. What is the function of that?

Bytheway I quote my question once again in case it is missed through convo. 
Thank you.

`Is it possible to have a dialog, where we can select and activate any slice file or boundary file by clicking ticks? I believe it would be helpful for activating or looking for specific one, slices could be selected by ticking instead of "right click>load/unload>slices" sequence. Also when there are high number of slices, it does not fit to screen and it takes time to scroll down.`

**Comment by gforney** [comment]
This is a temporary file I used to test whether I could write to a
directory . I should have removed it. ( I will). I could create a dialog
for selecting files as you suggest but this would not solve the problem of
having many files. A dialog of files would be just as long as a menu.

**Comment by Er9y714** [comment]
Thanks for the info. 

You are right about the size of the menu.  I guess it is not direct a solution. 

Thanks!
