### ISSUE TITLE
Blank pages

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5083]
I've noticed between some chapters some blank pages. Would you prefer to leave them as they are (in case that's what you want), or would like to remove them?

**Comment by rmcdermo** [comment]
Let's leave for now.  We try to scan the docs before a release to clean up formatting.  It is not very efficient to do this between releases.  Thanks though.

**Comment by sbenkorichi** [comment]
Ok, thanks for letting me know.

**Comment by gforney** [comment]
Don't know if this is the case here but there is a formatting style that
adds a blank page at end of chapter to ensure next chapter begins on an odd
page ( maybe even don't remember which)

**Comment by sbenkorichi** [comment]
I think by default, it adds a blank page between chapters, but what I saw is that some chapters have blank between them, whereas others don't. By adding "oneside" to \documentclass[11pt,oneside]{book}
would remove these blank pages between chapters.

**Comment by rmcdermo** [comment]
I'd be fine with that.  I thought you were suggesting we scan the documents for \newpage or \clearpage and try to stay on top of the various page breaks.

**Comment by sbenkorichi** [comment]
Ok, I will make pull request, we can make double check before the coming release.

**Comment by mcgratta** [comment]
We want chapters to start on odd numbered pages. That's typical report or book style. Obviously, some chapters will end on even pages; some odd. Thus, not all chapters will have a blank page.

**Comment by sbenkorichi** [comment]
So, you recommend taking out "oneside" ?

**Comment by mcgratta** [comment]
Yes, best to let the LaTeX style determine pagination.

**Comment by sbenkorichi** [comment]
Alright, I've rest it back.
