### ISSUE TITLE
Numerical Instability with Sandia H2 case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5103]
Kevin,
We now have a numerical instability with the high resolution H2 case:

/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Validation/Sandia_Plumes/Current_Results/Sandia_H2_1m_Test35_dx1p5cm*

This might be connected with your other issues and the change to TMP_F_GAS.  The error happens on an OPEN boundary.  Maybe that is a clue.  The failure happens at 1.8 sec sim time, which does not take to long to reach.

![screen shot 2017-05-18 at 11 18 47 am](https://cloud.githubusercontent.com/assets/4418497/26209799/cd481ef0-3bbb-11e7-86e8-e292b00f3f3a.png)

**Comment by rmcdermo** [comment]
Good news is that at least RTR_SOURCE_CORRECTION=F is working properly.

**Comment by sbenkorichi** [comment]
I've experienced around 0.42 sec. Beside, the numerical instability, most of the Sandia tests, the vents are overlapping, and some are rejected.
```
WARNING: Two VENTs overlap in MESH 1, Cell 51 69 0 . VENT 3 rejected for that cell
WARNING: Two VENTs overlap in MESH 1, Cell 52 69 0 . VENT 3 rejected for that cell
WARNING: Two VENTs overlap in MESH 1, Cell 53 69 0 . VENT 3 rejected for that cell
```
I've experienced this before when you set a circular vent in quite some large numbers, and this was due to two things: 
1. Either the resolution (of Blender) is not appropriate, or 
2. The mesh is not fine enough that causes this issue.

**Comment by drjfloyd** [comment]
This is just a warning so that you can ensure that the correct VENT has been applied. FDS will apply the first VENT defined in the input file.  If the warning is due to two VENTs with the same SURF_ID overlapping, then there is nothing to be concerned with.

**Comment by rmcdermo** [comment]
I added CFL_VELOCITY_NORM=1 back to the H2 cases and this seems to be helping the instability.

The VENT rejection is nothing to worry about; I just use one line for the OPEN bc.

**Comment by sbenkorichi** [comment]
Thanks for the info.

**Comment by sbenkorichi** [comment]
I've left it yesterday running by assigning all process (8). It's taking quite so much time, it's at 1.87 sec now without crashing yet. I wonder why under one single process crashed at 42 sec, whereas with multiple process it's still running but a bit slow.

**Comment by rmcdermo** [comment]
The solutions are not identical.  The instabilities are semi-random.

**Comment by rmcdermo** [comment]
My high res case had another instability last night at 7 sec.

Kevin, we need to sit down and diff the code for TMP_F_GAS.

**Comment by mcgratta** [comment]
See commit #5113. I reverted a change that I made when cleaning up wall.f90 to accommodate cut faces. This changed caused my wall fire cases to seg fault. I do not understand why this change caused a problem. As I see it, the change is correct, but it causes a problem, so I am changing it back for now. Test your cases again and see if it helps.

**Comment by sbenkorichi** [comment]
At 0.60 no crash yet, last time happened at 0.42. Will leave it till the end just in case.

**Comment by sbenkorichi** [comment]
6 sec and still running. Randy, have you experienced any instability?

**Comment by rmcdermo** [comment]
Latest finished fine.

**Comment by sbenkorichi** [comment]
Yes, looks like Kevin's commit fixed it.

**Comment by sbenkorichi** [comment]
@mcgratta This is the sandia issue that I told you about. Have you managed to get it working with the new changes for the cut faces?

**Comment by mcgratta** [comment]
Try it and let me know if it works with the latest code base.

**Comment by sbenkorichi** [comment]
I will give it a try, but might take sometime to finish.

**Comment by sbenkorichi** [comment]
Kevin,
Still running, a bit slow, but haven't any issues so far. Looks like everything is good.

**Comment by mcgratta** [comment]
Thanks.
