### ISSUE TITLE
Different temperature evolution with similar HRRPUV on the INIT line

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5115]
I'm facing this issue below: 
Trying to work out the temperature distribution using the HRRPUV as a source term. When I change the XB coordinates, I find different temperature distributions (using the device recording temp as an output). Normally, with the same heat source, one would expect at least similar value at the center, which I'm not getting. 
I submit two simplified cases, where different results can be found with the same of HRRPUV. 

Please let me know if you spot something wrong that I'm doing.

[test1.fds.txt](https://github.com/firemodels/fds/files/1020063/test1.fds.txt)
[test2.fds.txt](https://github.com/firemodels/fds/files/1020064/test2.fds.txt)

**Comment by drjfloyd** [comment]
If the HRRPUV is the same, but the volume is not, then the total heat input is not the same and the solid with the higher heat input will have higher temperatures at its center in order to support conduction heat transfer to the surface of the solid.

**Comment by sbenkorichi** [comment]
Thanks Jason for the feedback.
Quote from **section 6.5.** 
**Heat Release Rate Per Unit Volume (HRRPUV)**
The INIT line may also be used to specify a volumetric heat source term. For example,
&INIT XB=0.0,0.1,0.0,0.025,0.0,0.1, HRRPUV=1000. /
indicates that the **region bounded by XB** shall generate 1000 kW/m 3 . This feature is mainly useful for diagnostics, or to model a fire in a very simple way.
From my understanding of this statement is that with any volume with similar HRRPUV would be the same. Then, I would expect similar temperature in that case. Unless, I'm mistaken it.

**Comment by rmcdermo** [comment]
Salah,
Do things behave as you expect in the gas phase?

I don't understand what the confusion is: Q [kW] = VOLUME_XB * HRRPUV.

**Comment by sbenkorichi** [comment]
Thanks Randy, now it makes sense. I somehow was neglecting the volume from consideration. That clarifies it. But, I would love to keep it open for now just in case something pop up.

Cheers,
Salah

**Comment by rmcdermo** [comment]
No problem.  I made you the owner.  So, close whenever you like :).

**Comment by sbenkorichi** [comment]
haha
