### ISSUE TITLE
Numerical Instability because of a sudden hrr increasing

### ISSUE THREAD

**Issue by zladicolor** [firemodels/fds#5130]
Hello sirs,
I've tested the hvac system without fire and solved the error severe (174). Then i set the new hvac system in my simulation but at t=600s is Numerical Instability because of a sudden hrr's increasing. I've set then MAX_PRESSURE_ITERATIONS, the problem is solved but the jump is still there. The hrr curve which i hoped should be fast constant after t=200s. Can you check the new codes and maybe give me some advices? Thank you :)
[test8.docx](https://github.com/firemodels/fds/files/1040923/test8.docx)
[test8.xlsx](https://github.com/firemodels/fds/files/1040935/test8.xlsx)
![snip20170531_5](https://cloud.githubusercontent.com/assets/28928013/26625991/0b7fed44-45f6-11e7-927e-a1627524a660.png)

**Comment by sbenkorichi** [comment]
I guess this should be closed by now.
