### ISSUE TITLE
Problem with Sprinkler

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#5131]
Hello sirs,
With this Simulation i have two Problems. The first, how can i do, so the water don’t through the wall. The second, i don’t know, why the speed of water droplets is so low.
What should i do to solve the problems.

Thanks
Zhixin Zhang

&HEAD CHID='versuch2'/
&TIME T_END=10.0/

&MESH ID='Mesh01', FYI='Computatinal Domain', IJK=100,60,50, XB=0.0,10.0,0.0,6.0,0.0,5.0/

&MATL ID='Material01',
      SPECIFIC_HEAT=1.0,
      CONDUCTIVITY=0.1,
      DENSITY=500.0/

&MISC ALLOW_UNDERSIDE_PARTICLES=.TRUE. /

&OBST ID='Target Wall', XB=4.0,6,3.5,4.0,0.0,2.0,COLOR='GRAY 80',PERMIT_HOLE=.FALSE./ 

&VENT ID='Vent01', SURF_ID='OPEN', XB=0.0,10.0,0.0,6.0,0.0,0.0/ 
&VENT ID='Vent02', SURF_ID='OPEN', XB=0.0,10.0,0.0,6.0,5.0,5.0/ 
&VENT ID='Vent03', SURF_ID='OPEN', XB=0.0,0.0,0.0,6.0,0.0,5.0/ 
&VENT ID='Vent04', SURF_ID='OPEN', XB=10.0,10.0,0.0,6.0,0.0,5.0/ 
&VENT ID='Vent05', SURF_ID='OPEN', XB=0.0,10.0,0.0,0.0,0.0,5.0/ 
&VENT ID='Vent06', SURF_ID='OPEN', XB=0.0,10.0,6.0,6.0,0.0,5.0/ 

&SPEC ID='WATER VAPOR' /

&PART ID='water_drops', N_STRATA=20, SPEC_ID='WATER VAPOR',DIAMETER=100, SIGMA_D=0.4,GAMMA_D=2.875,INITIAL_TEMPERATURE =18/
 
&PROP ID='K-11', OFFSET=0.125, PART_ID='water_drops',OPERATING_PRESSURE=4., FLOW_RATE=3.2, PARTICLE_VELOCITY=250, SMOKEVIEW_ID='sprinkler_pendent',SPRAY_ANGLE(1:2,1)=0,9.25, SPRAY_ANGLE(1:2,2)=0,24/
 
&DEVC XYZ=5 4.5 1, PROP_ID='K-11',ID='Spr_1',QUANTITY='TIME',SETPOINT=0.,ORIENTATION=0,-1,0/

&SLCF QUANTITY='VELOCITY', PBZ=1/

&SLCF QUANTITY='VELOCITY', PBY=4.5/

&SLCF QUANTITY='VELOCITY', PBX=5/

&TAIL /

**Comment by sbenkorichi** [comment]
1. I think this should be asked in the discussion group, so others could benefit as it's not a bug.
2. What do you mean by so slow? Do you have any experimental data for your comparison? On what basis you think it's slow?

**Comment by rmcdermo** [comment]
Yes, please move to discussion forum.

**Comment by ghost** [comment]
Hallo Salah,
Thank you for your answer.
For the speed. I set 250m/s. But in the Simulation it is only 5m/s.

thanks
Zhixin

2017-06-01 20:06 GMT+02:00 Salah Benkorichi <notifications@github.com>:

**Comment by rmcdermo** [comment]
Again, please move the discussion to the forum.  Thanks.

**Comment by sbenkorichi** [comment]
If you haven't figured it out, follow the link to the FDS-SMV discussion group to ask your question there. Questions are supposed to be asked there, whereas bugs should be reported here: 
**FDS-SMV group discussion**
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv

Check the **group policies** and **effective posting**: 

https://github.com/firemodels/fds/wiki/FDS-SMV-Group-Policies

https://github.com/firemodels/fds/wiki/Effective-Posting
