### ISSUE TITLE
Visualization of Solid Particle Objects in Smokeview

### ISSUE THREAD

**Issue by mckinn1** [firemodels/fds#5132]
I am attempting to model cables in a simulation using the Lagrangian particle approach outlined in Secs 8.3.7 and 14.4.9 of the User Guide and I have been running into the issue that the cables appear as discrete particles in SMV instead of as cylinders. I mainly want to visualize the cables to ensure that they are in the correct position and orientation relative to the other objects modeled in my domain. 

I have attached a simple FDS input file that was taken from my larger and more complicated model as well as the visualization of this model in SMV. Please let me know if there is anything that I can do on my end to ensure I am properly visualizing the particles as the objects that I have defined.

Thanks,

Mark

![test_5 1s](https://cloud.githubusercontent.com/assets/29129519/26695770/1395f2dc-46da-11e7-8526-f86d7df08a64.jpg)

[test.txt](https://github.com/firemodels/fds/files/1045748/test.txt)

**Comment by mcgratta** [comment]
Show/Hide --> Particles --> Draw --> Cable Segment --> Tube

**Comment by mckinn1** [comment]
Thank you so much. I figured there was a really easy solution that I was missing. 

Thanks again,
Mark
