### ISSUE TITLE
MW_RATIO used before it is defined in part.f90

### ISSUE THREAD

**Issue by tkorhon1** [firemodels/fds#5136]
Hi!

I got an error, when running the debug version of the executable. The error message is below.
The problem is line 2227:

               D_SOURCE(II,JJ,KK) = D_SOURCE(II,JJ,KK) + (MW_RATIO*M_VAP/M_GAS + (M_VAP*DELTA_H_G)/H_S_G_OLD) * WGT / DT

There you have "MW_RATIO" and it is not defined before. Searching backwards,
you find the string in the beginning of the subprogram:

REAL(EB) :: R_DROP,NUSSELT,K_AIR,H_V,H_V_REF, H_L,H_V2,&
            RVC,WGT,Q_CON_GAS,Q_CON_WALL,Q_RAD,H_HEAT,H_MASS,SH_FAC_GAS,SH_FAC_WALL,NU_FAC_GAS,NU_FAC_WALL,&
            PR_AIR,M_VAP,M_VAP_MAX,MU_AIR,H_SOLID,Q_DOT_RAD,DEN_ADD,AREA_ADD,&
            Y_DROP,Y_GAS,Y_GAS_NEW,LENGTH,U2,V2,W2,VEL,TMP_DROP_NEW,TMP_WALL,H_WALL,&
            SC_AIR,D_AIR,DHOR,SHERWOOD,X_DROP,M_DROP,RHO_G,MW_RATIO,MW_DROP,FTPR,&
            C_DROP,M_GAS,A_DROP,TMP_G,TMP_DROP,TMP_MELT,TMP_BOIL,MINIMUM_FILM_THICKNESS,RE_L,OMRAF,Q_FRAC,Q_TOT,DT_SUBSTEP,&
            CP,H_NEW,ZZ_GET(1:N_TRACKED_SPECIES),ZZ_GET2(1:N_TRACKED_SPECIES),&
            M_GAS_NEW,MW_GAS,DELTA_H_G,TMP_G_I,H_G_OLD,H_S_G_OLD,H_D_OLD,&
            TMP_G_NEW,DT_SUM,DCPDT,X_EQUIL,Y_EQUIL,Y_ALL(1:N_SPECIES),H_S_B,H_S,C_DROP2,&
            T_BOIL_EFF,P_RATIO,RAYLEIGH,GR,RHOCBAR,MCBAR,&
            M_GAS_OLD,TMP_G_OLD,NU_LIQUID,H1,H2,TMP_FILM,CP_BAR_2

NOTE: The GIT string might not be quite correct. But the part.f90 I used (and other source also)
was some last week version. I do not compile at my GIT directory (it is in my laptop). I copy
the source to Linux cluster and manually add the GIT date and string to the makefile. Usually
I remember to do this, sometimes not.

Wbr,
Timo

Fire Dynamics Simulator

Current Date     : June  2, 2017  21:01:00
Version          : FDS 6.5.3
Revision         : FDS6.5.3-1666-g80f6bd2
Revision Date    : Fri May 5 17:38:13 2017 -0400
Compilation Date : Jun 02, 2017  14:49:50

MPI Enabled; Number of MPI Processes:          1
OpenMP Enabled; Number of OpenMP Threads:   1

MPI version: 3.0
MPI library version: Open MPI v1.8.3, package: Open MPI tstopi@espvm5m030.ad.vt
.fi Distribution, ident: 1.8.3, Sep 25, 2014

Job TITLE        : UL/NFPRF Heptane Spray Burner under 4 sprinklers
Job ID string    : water_fuel_sprays

 Time Step:   6400, Simulation Time:     96.86 s
forrtl: severe (194): Run-Time Check Failure. The variable 'part_mp_particle_mas
s_energy_transfer_$MW_RATIO' is being used in 'part.f90(2227,16)' without being
defined
Image              PC                Routine            Line        Source

fds_mpi_intel_lin  0000000002AC296E  part_mp_particle_        2227  part.f90
fds_mpi_intel_lin  0000000002A737AD  part_mp_update_pa        1221  part.f90
fds_mpi_intel_lin  000000000334A4CE  MAIN__                    685  main.f90
fds_mpi_intel_lin  000000000040C35E  Unknown               Unknown  Unknown
libc-2.12.so       0000003CE941ED1D  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040C269  Unknown               Unknown  Unknown

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I just updated my repo and compiled the debug version and it runs without a problem
```
Version          : FDS 6.5.3
Revision         : FDS6.5.3-1836-gfa85133
Revision Date    : Fri Jun 2 16:13:18 2017 -0400
```

**Comment by tkorhon1** [comment]
Well, I just did "remote update": FDS6.5.3-1836-gfa85133
And I see the file part.f90 and there line 2227. It is in the
routine PARTICLE_MASS_ENERGY_TRANSFER and there in
the BOIL_ALL if. This if is inside the 
      TIME_ITERATION_LOOP: DO WHILE (DT_SUM < DT)
loop. Later in the loop one has:
               MW_RATIO = MW_GAS/MW_DROP
But this is in the "ELSE boil_all" branch of the if.

So, if the droplet is such a small, that it goes directly in the first
time step (time_iteration_loop) to the "boil all" branch, then the
mw_ratio is not defined (at least for this droplet, it might be previous
droplet, if the present droplet is not the first one in the droplet loop
and species loop).

It might be that you do not usually have the first droplet such a small that
it goes to the boil all branch. I do not now, why I got the error message.
Now I compiled debug version of the "latest git" and now some CPU is 
working on it. But I should leave the office about now, so I leave it running. Tomorrow
I'm out of the office (meeting in Kuopio, so driving a car most of the day).

Timo

**Comment by mcgratta** [comment]
Yes, you are correct. `MW_RATIO` is not defined. I'll fix.

**Comment by tkorhon1** [comment]
FYI: The above run did crash. See below. The source code version was some 
GIT version from last week. The GIT tag is not correct, because I did not
remember to update that in the makefile. IT might be that in some other
GIT version you do not find this bug, even if the part.f90 is the same one.
Some other part is changed and there is small changes in the results =>
it might be that the first droplet in the species&droplet loop is not 
evaporating totally in the first droplet sub-time step. It is just the first
droplet, that has undefined mw_ratio. The others use the mw_ratio of
the previous droplet. 

So, I was quite lucky to find this bug. 

 Time Step:   5600, Simulation Time:     87.36 s
forrtl: severe (194): Run-Time Check Failure. The variable 'part_mp_particle_mas
s_energy_transfer_$MW_RATIO' is being used in 'part.f90(2227,16)' without being
defined
Image              PC                Routine            Line        Source

fds_mpi_intel_lin  0000000002AC1256  part_mp_particle_        2227  part.f90
fds_mpi_intel_lin  0000000002A72095  part_mp_update_pa        1221  part.f90
fds_mpi_intel_lin  0000000003348E52  MAIN__                    684  main.f90
fds_mpi_intel_lin  000000000040C35E  Unknown               Unknown  Unknown
libc-2.12.so       0000003ABD01ED5D  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040C269  Unknown               Unknown  Unknown

Timo

**Comment by mcgratta** [comment]
Commit #5204. 

Jason, could you check what I did. It passed the verification tests, but it's worth a second look.

**Comment by drjfloyd** [comment]
Looks OK.
