### ISSUE TITLE
Numerical Instability in Long Tunnel

### ISSUE THREAD

**Issue by GorkemGuclu** [firemodels/fds#5137]
Hello everyone,

I am using FDS version of 6.5.1. When I modeled long tunnels, some of them reaches numerical instability while some of them goes well. Why I am getting error about numerical instability at some models?  Similar tunnel models, similar fire locations but I can not find a meaningful explanation why I am not facing numerical instability at all cases if there is a problem at long tunnel modelings. I am attaching numerical instability model(Tunel 1-1) and normally running model(Tunel 5-1) as an example below. Is there any exact solution to solve this problem? I took a look at case numbers 3794 and 3807 when I got numerical instability problem. Is it going to be solved when I change BAROCLINIC PRESSURE as .FALSE or could you solved this problem for FDS 6.5.3 latest version? I am waiting for your helps.
              
![1](https://cloud.githubusercontent.com/assets/29224406/26820095/4b03732e-4aaa-11e7-9296-64c1b8419340.JPG)
                                                       
![2](https://cloud.githubusercontent.com/assets/29224406/26820103/5355e728-4aaa-11e7-9423-fc8a4a5a2b5b.JPG)

[Example tunnel models.zip](https://github.com/firemodels/fds/files/1054249/Example.tunnel.models.zip)

**Comment by sbenkorichi** [comment]
Thanks for reporting it , however It would be pointless going back to 6.5.1. we are currently with 6.5.3. please run your cases and if you notice a bug then report it.

**Comment by rmcdermo** [comment]
Thanks for the report.  This should have been fixed with 6.5.0.  We will take a look.
However, we will be at the IAFSS meeting for all next week, so it could be some time before we get to this.

**Comment by Er9y714** [comment]
Could you share the CHID.out files as well please?

Have you tried reducing VELOCITY_TOLERANCE ?

**Comment by mcgratta** [comment]
Install FDS 6.5.3. In the User's Guide, read section 6.6, in particular 6.6.2.

**Comment by GorkemGuclu** [comment]
Thank you all for supportings. I realised that I am facing with numarical instability only t-squared fire ramped models. I think I am doing something wrong while modeling t-squared fire ramp. Could you guys take a look at and tell me if there is a problem modeling t-squared fire ramp?

[FDS fire profile.xlsx](https://github.com/firemodels/fds/files/1055424/FDS.fire.profile.xlsx)

**Comment by mcgratta** [comment]
The ramp is fine. That is not the problem. Load the latest version of FDS and rerun your case.

**Comment by GorkemGuclu** [comment]
Thank you @mcgratta . I am going to rerun my case and going to write results here.

**Comment by mcgratta** [comment]
Any progress on this issue?

**Comment by GorkemGuclu** [comment]
Actually FDS did not give any numerical instability error but the temperature and the velocity values oscillate too much and the analytical calculation of the temperature values that we did for the same tunnel does not match with the FDS output. I am sharing the temperature output from FDS and our analytical calculation for steady state condition.

**Comment by mcgratta** [comment]
Post the input (.fds) file.

**Comment by GorkemGuclu** [comment]
It is attached.

 

Regards,

 


Görkem GÜÇLÜ


Proje ve Ar-Ge Mühendisi


Project and R&D Engineer


 



logo

AIRONN HAVALANDIRMA ve KLİMA SİSTEMLERİ SAN.DIŞ.TİC.LTD.ŞTİ.
Tatlısu Mah. Şenol Güneş Blv. Mira Tower K:3 D:16 
Şerifali, Ataşehir - İstanbul - Turkey 

Tel: +90 216 594 56 96
Fax: +90 216 594 57 17


 


 <mailto:gorkem.guclu@aironn.com.tr> gorkem.guclu@aironn.com.tr

 <http://www.aironn.com.tr/> www.aironn.com.tr

**Comment by mcgratta** [comment]
I do not see an attachment.

**Comment by GorkemGuclu** [comment]
Please check the input .fds file.

[Tunel1-1.zip](https://github.com/firemodels/fds/files/1132799/Tunel1-1.zip)

**Comment by mcgratta** [comment]
I said to post the .fds file, not the .psm file.

**Comment by sbenkorichi** [comment]
Fyi
The fds input file is a file with .fds extension for example job.fds that's the file Kevin is asking to be uploaded. 
You need also to know that you can't uploaded it on github directly so you either select the file and hit F2 key to rename it to .txt instead of .fds PS: IF you can not see any file with .fds that means you need check the view option so you can see the extension of the files.
Another option is to compress it in rar file and uploaded.

**Comment by GorkemGuclu** [comment]
[Tunel1-1.zip](https://github.com/firemodels/fds/files/1133781/Tunel1-1.zip)

**Comment by mcgratta** [comment]
I am running the case.

**Comment by mcgratta** [comment]
This is the result of the case Tunel1-1 using the latest working version of FDS. I think some of the HVAC pressure coupling issues have been improved, although there are still some spurious fluctuations. I suggest you either build the latest source of FDS or if using 6.5.3, add leakage to the tunnel to provide pressure relief. If you have a perfectly sealed tunnel in the model, pressure perturbations from the fire are propagated instantaneously throughout the tunnel. Of course, in reality, pressure perturbations travel at the speed of sound and are dampened by leakage and other natural openings in the tunnel. Thus, FDS exaggerates these pressure pulses.

![image](https://user-images.githubusercontent.com/11333911/28211864-d202c2be-686c-11e7-916a-67ab4891ae19.png)
