### ISSUE TITLE
EVAC and EVSS speeds

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#5138]
I have run a series of test cases using the EVSS name group to adjust position of occupants and their speed, essentially to simulate stairs.  From what I can tell:

EVAC computes the movement "time" (it is really adjusting the agent speed) on an incline when moving up as:

time = sqrt( dx^2 + dz^2 ) / ( Vo * FAC_V0_UP )

Where dx and dz are based on the XB values of the EVSS and the HEIGHT and HEIGHT0 differences.  That is, dx = xmax - xmin (of the EVSS) and dz = HEIGHT - HEIGHT0.

I have run several test cases, it seems to work reliably and I achieve a good correlation to a hand sum, for the incline.  

However, when looking at a horizontal surface alone, EVAC seems to ignore any value of FAC_V0_HORI.

I have attached a simple file.  

Is it the case that EVAC ignores any speed factoring when HEIGHT0 = HEIGHT?  This would mean that it effectively never changes movement speed on a horizontal surface (FAC_V0_HORI).

Cut down input file pasted below.

Regards
Matt

&HEAD CHID='EVACtest',TITLE='EVAC test cases' /
    
&TIME T_BEGIN=0.0,T_END=900.0 / 

&MISC EVACUATION_DRILL=.TRUE. /

# MESH ELEMENTS

# MESH LAYOUT...
#
# CAR8 ==> WWA (horizontal EVSS) ==> WWB (sloped EVSS, stairs) ==> WWC ==> EXIT

# CAR8

&MESH IJK=74,10,1,XB=179.4,201.6,-4.05,-1.05,1.2,3.3,EVAC_Z_OFFSET=1.05,EVACUATION=.TRUE.,EVAC_HUMANS=.TRUE.,ID='CAR8' / 

# PEOPLE CHARACTERISTICS AND PLACEMENT IN CAR 8

&PERS  ID = 'Male',
       FYI = 'Typical adult male, defaults from EVAC',
       DEFAULT_PROPERTIES = 'Male',
       PRE_EVAC_DIST=3,PRE_LOW=5.0, PRE_MEAN=25.0, PRE_HIGH=60.0, PRE_PARA=10.0,
       DET_EVAC_DIST=1,DET_LOW=5.0, DET_MEAN=5.0, DET_HIGH=5.0,
       VEL_MEAN=1.00,VEL_LOW=0.99,VEL_HIGH=1.01,VELOCITY_DIST=1,       
       TDET_SMOKE_DENS=17.24, 
       HUMAN_SMOKE_HEIGHT = 2.1,
       DENS_INIT = 4.0,
       OUTPUT_SPEED = .TRUE.,
       OUTPUT_FED = .TRUE.,
       COLOR_METHOD = 0 /
    
&EVAC ID='CAR8m' 
NUMBER_INITIAL_PERSONS=1.0 
XB=179.4,201.6,-4.05,-1.05,1.2,3.3 
AVATAR_RGB=0,0,255 
KNOWN_DOOR_NAMES='EXITE1a','CAR8D1' 
PERS_ID = 'Male' /

# DOOR AND ENTRY TO WWA

&DOOR ID='CAR8D1', XB=181.8,183,-1.05,-1.05,1.2,3.3, IOR=+2, XYZ=182.4,-1.35,2.25, TO_NODE='ENTRYCORRC8D1', SHOW=.TRUE. /
&CORR ID='ENTRYCORRC8D1', TO_NODE='ENTRYC8D1', EFF_LENGTH=0.5,FAC_SPEED=0.5,MAX_HUMANS_INSIDE=2 /
&ENTR ID='ENTRYC8D1', XB=181.8,183,-0.75,-0.75,1.2,3.3, IOR=+2, SHOW=.TRUE. /

# Walkways (WWA, WWB, WWC)

# Mid-plane of mesh = 0.5 * (z1+z2).
# Set EVAC_Z_OFFSET to 0.0 to place the agents' midpoint at the same plane as a mesh mid-plane.
# To place the agents' feet on the floor, use this equation: HEIGHTAGENTFEET = 0.5 * (z1+z2) - EVAC_Z_OFFSET.
# If EVAC_Z_OFFSET is not set, note that when using EVSS that HEIGHT will be relative to the lower z coordinate of the MESH.
# If EVAC_Z_OFFSET is set, then HEIGHT will be relative to the following:
# HEIGHT OF AGENT FEET = Z1 (lower XB of mesh) - EVAC_Z_OFFSET + HEIGHT

&MESH IJK=2395,15,1,XB=0.0,718.5,-0.75,0.75,1.2,3.3,EVAC_Z_OFFSET=1.05,EVACUATION=.TRUE.,EVAC_HUMANS=.TRUE.,ID='WWA' /
&MESH IJK=70,15,1,XB=718.8,739.8,-0.75,0.75,1.2,3.3,EVAC_Z_OFFSET=1.05,EVACUATION=.TRUE.,EVAC_HUMANS=.TRUE.,ID='WWB' /
&MESH IJK=70,15,1,XB=740.1,761.1,-0.75,0.75,25.2,27.3,EVAC_Z_OFFSET=1.05,EVACUATION=.TRUE.,EVAC_HUMANS=.TRUE.,ID='WWC' /

# EVSS GROUPS

&EVSS XB=0.0,718.5,-0.75,0.75,1.2,1.2,IOR=-1,ID='TRAMP01s',HEIGHT0=0.05,HEIGHT=0.05,FAC_V0_UP=0.2,FAC_V0_DOWN=1.0,FAC_V0_HORI=0.5,MESH_ID='WWA',COLOR='GRAY' / walkway
&EVSS XB=718.8,739.8,-0.75,0.75,1.2,1.2,IOR=-1,ID='TRAMP02s',HEIGHT0=0.05,HEIGHT=25.05,FAC_V0_UP=0.2,FAC_V0_DOWN=1.0,FAC_V0_HORI=0.5,MESH_ID='WWB',COLOR='GRAY' / ramp
&EVSS XB=740.1,761.1,-0.75,0.75,25.2,25.2,IOR=-1,ID='TRAMP03s',HEIGHT0=1.05,HEIGHT=1.05,FAC_V0_UP=1.0,FAC_V0_DOWN=1.0,FAC_V0_HORI=1.0,MESH_ID='WWC',COLOR='GRAY' / walkway

# DOORS BETWEEN WALKWAY MESHES AND EXIT

&DOOR ID='DOOR1',XB=718.5,718.5,-0.75,0.75,1.2,3.3,IOR=+1,TO_NODE='ENTRY1' /
&ENTR ID='ENTRY1',XB=718.8,718.8,-0.75,0.75,1.2,3.3,IOR=+1 /

&DOOR ID='DOOR2',XB=739.8,739.8,-0.75,0.75,1.2,3.3,IOR=+1,TO_NODE='ENTRY2' /
&ENTR ID='ENTRY2',XB=740.1,740.1,-0.75,0.75,25.2,27.3,IOR=+1 /

&EXIT ID='EXITE1a',XB=761.1,761.1,-0.75,0.75,25.2,27.3,IOR=+1 / 

&TAIL /

**Comment by tkorhon1** [comment]
> However, when looking at a horizontal surface alone, EVAC seems to ignore any value of FAC_V0_HORI.

Well, I test this first. Your report was quite long,  I test this with my IMO stairs example cases.
There I set the EVSS representing stairs to be just a horizontal plane.

TimoK

**Comment by mattbilson76** [comment]
I simplified the model a little, and tested a few things.  Seems that when the EVSS is horizontal that I need to change all three speed factors to get the change in agent movement speed.  Lines from input file below.
Matt


&HEAD CHID='EVACtest',TITLE='EVAC test cases' /
&TIME T_BEGIN=0.0,T_END=900.0 /
&MISC EVACUATION_DRILL=.TRUE. /

# CAR
&MESH IJK=74,10,1,XB=179.4,201.6,-4.05,-1.05,1.2,3.3,EVAC_Z_OFFSET=1.05,EVACUATION=.TRUE.,EVAC_HUMANS=.TRUE.,ID='CAR8' /

# PEOPLE CHARACTERISTICS AND PLACEMENT IN CAR 8
&PERS ID = 'Male',
  FYI = 'Typical adult male, defaults from EVAC',
  DEFAULT_PROPERTIES = 'Male',
  PRE_EVAC_DIST=3,PRE_LOW=5.0, PRE_MEAN=25.0, PRE_HIGH=60.0, PRE_PARA=10.0,
  DET_EVAC_DIST=1,DET_LOW=5.0, DET_MEAN=5.0, DET_HIGH=5.0,
  VEL_MEAN=1.00,VEL_LOW=0.99,VEL_HIGH=1.01,VELOCITY_DIST=1 /

&EVAC ID='CAR8m'
NUMBER_INITIAL_PERSONS=1.0
XB=179.4,201.6,-4.05,-1.05,1.2,3.3
KNOWN_DOOR_NAMES='EXITE1a','CAR8D1'
PERS_ID = 'Male' /

# DOOR AND ENTRY TO WWA
&DOOR ID='CAR8D1', XB=181.8,183,-1.05,-1.05,1.2,3.3, IOR=+2, XYZ=182.4,-1.35,2.25, TO_NODE='ENTRYC8D1', SHOW=.TRUE. /
&ENTR ID='ENTRYC8D1', XB=181.8,183,-0.75,-0.75,1.2,3.3, IOR=+2, SHOW=.TRUE. /

# Walkways (WWA, WWB, WWC)
&MESH IJK=2395,15,1,XB=0.0,718.5,-0.75,0.75,1.2,3.3,EVAC_Z_OFFSET=1.05,EVACUATION=.TRUE.,EVAC_HUMANS=.TRUE.,ID='WWA' /

# EVSS GROUPS
&EVSS XB=0.0,718.5,-0.75,0.75,1.2,3.3,IOR=-1,ID='TRAMP01s',HEIGHT0=0.0,HEIGHT=0.0,FAC_V0_UP=1.0,FAC_V0_DOWN=1.0,FAC_V0_HORI=1.0,MESH_ID='WWA',COLOR='GRAY' / walkway

# EXITS
&EXIT ID='EXITE1a',XB=718.5,718.5,-0.75,0.75,1.2,3.3,IOR=+1 /

&TAIL /

**Comment by tkorhon1** [comment]
Thanks, I have been a little bit busy, so I have not yet checked this issue. But your finding that you need set all three speed factors to run it correctly, is a good one.

The problem may be, that "horizontal" plane is not easy to detect. You compare is something is exactly equal to zero using floating point numbers. 

What I should do:

1) Change the manual: Say, that for horizontal planes one should set all three parameters to be equal. This is a fast fix (or "go around").

2) If HEIGHT = HEIGHT0 (for some precision, say if ABS(HEIGHT-HEIGHT0) less than 10cm, then this is a horizontal plane ==> set all speed factors to be same as the horizontal plane (no need to change anything else in the source code). 

TimoK

**Comment by gjaeger** [comment]
@tkorhon1 With PR #10089 we should/can close this issue.
