### ISSUE TITLE
Defining control logic and pressure difference

### ISSUE THREAD

**Issue by GorkemGuclu** [firemodels/fds#5140]
Hello everyone,

I have two quick questions. First of all, I would like to give control logic to a jet fan. I need to close my jet fan, permenantly when the MEAN TEMPERATURE comes a desired value. How can I do that w/o thermocouple?

My second question is, I am trying to create pressure difference between the exit of the tunnel and outside of the tunnel. I am defining pressure difference at the end of the long tunnel via an opening vent. When I run the smokeview, I do not see any velocity vector due to pressure difference at the end of the tunnel. How can I create a pressure difference at the end of the tunnel?

I am waiting for your helps. Thanks.

**Comment by mcgratta** [comment]
The Issue Tracker is for submitting bug reports. General questions like these should be posted to the FDS Discussion Group.

**Comment by sbenkorichi** [comment]
Please submit your questions in the discussion group in the link below. This platform is reserved only for bugs or adding new features. 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv
