### ISSUE TITLE
Activation and Deactivation of Exhaust/Supply surface at same location

### ISSUE THREAD

**Issue by alvinloo** [firemodels/fds#5145]
I am trying to simulate a situation where the activation of a heat detector increases the speed of the exhaust/supply flowrate by using one CTRL to deactivate the initial exhaust/supply surface and another CTRL to activate a new exhaust/supply surface that has a higher flowrate at the same location.

Results show that FDS ignores the initial surface and will only activate the new surface. The initial surface is shown in Smokeview but no air flow is going in/out on this surface.

I ran this on FDS versions 6.5.3 and 6.5.1. Both versions can’t make it work as intended. Some of my colleagues advised that this would work in older versions of FDS. Could this be a bug? 

Attached below is a FDS input file with a simple case to illustrate my point. 

The current solution I have for this issue is to run FDS twice: first time to determine the activation time of the heat detector, second time using a timer to increase the exhaust/supply via RAMP.

&HEAD CHID='Act_Deact_Surf'/
&TIME T_END=100.0/

&MESH ID='MESH', IJK=7,12,8, XB=0.0,1.75,0.0,3.0,0.0,2.0/

&REAC ID='polyurethane',
      FUEL='POLYURETHANE',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0/

&PROP ID='Heat Detector', QUANTITY='LINK TEMPERATURE', ACTIVATION_TEMPERATURE=40.0/
&DEVC ID='HD',  PROP_ID='Heat Detector', XYZ=0.75,2.25,1.75/

&CTRL ID='Deactivate Normal Mode', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='HD'/
&CTRL ID='Activate Fire Mode', FUNCTION_TYPE='ALL', LATCH=.TRUE., INPUT_ID='HD'/

&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=500.0/

&SURF ID='Exhaust Normal Mode',
      VOLUME_FLOW=5.0,
      COLOR='YELLOW'/
&SURF ID='Exhaust Fire Mode',
      VOLUME_FLOW=10.0,
      COLOR='GREEN',
      RAMP_V='Ramp'/

&SURF ID='Supply Normal Mode',
      VOLUME_FLOW=-2.5,
      COLOR='BLUE'/
&SURF ID='Supply Fire Mode',
      VOLUME_FLOW=-5.0,
      COLOR='PURPLE',
      RAMP_V='Ramp'/

&RAMP ID='Ramp', T=0.0, F=0.5/
&RAMP ID='Ramp', T=10.0, F=1.0/

&OBST ID='Fire', XB=0.75,1.0,2.5,2.75,0.0,0.25, SURF_IDS='Fire','INERT','INERT'/ 
&OBST ID='Obstruction', XB=0.0,1.75,1.5,1.75,0.0,2.0, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=0.75,1.0,-1.4803E-16,1.5,0.0,2.0, SURF_ID='INERT'/ 

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=1.75,1.75,0.0,3.0,0.0,2.0/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,3.0,0.0,2.0/ 

&VENT ID='Exhaust Normal', SURF_ID='Exhaust Normal Mode', XB=1.0,1.0,0.5,1.0,1.5,2.0, CTRL_ID='Deactivate Normal Mode'/ 
&VENT ID='Exhaust Fire', SURF_ID='Exhaust Fire Mode', XB=1.0,1.0,0.5,1.0,1.5,2.0, CTRL_ID='Activate Fire Mode'/ 
&VENT ID='Supply Normal', SURF_ID='Supply Normal Mode', XB=0.75,0.75,0.5,1.0,0.0,0.5, CTRL_ID='Deactivate Normal Mode'/ 
&VENT ID='Supply Fire', SURF_ID='Supply Fire Mode', XB=0.75,0.75,0.5,1.0,0.0,0.5, CTRL_ID='Activate Fire Mode'/ 

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=0.75/

&TAIL /

**Comment by alvinloo** [comment]
Apologies, please read 'exhaust/supply vent', not 'exhaust/supply surface'.

**Comment by sbenkorichi** [comment]
Most of the members at the IAFSS conference in Lund, so you might be patient until next week when someone will look into your issue.

Salah

**Comment by alvinloo** [comment]
Sure and thanks, Salah. It's not really an issue to me anymore. Just wanna do my part as a user to report a possible bug.

**Comment by sbenkorichi** [comment]
Thanks for reporting it. We will look into it when we are back next week from IAFSS conference.

**Comment by drjfloyd** [comment]
We can take an OBST and add or remove a VENT from it, but I am not sure we have the ability in the current open and close routine to take an OBST and add or remove multiple  VENTs.  I'll have to dig into the code. 

As an alternative I think you could do this with HVAC.  Connect an HVAC VENT to the room.  Use a duct to connect that VENT to a tee.  Have each branch of the tee connect to ambient and contain a fixed volume flow fan and a damper.  Then use control functions to open and close the dampers and turn on and off the fans.  You would start off with one duct damper closed and its fan (the high flow fan) off and the other duct would have an open damper and the low flow fan.  Control functions could be used to switch the ducts and operating fans.
