### ISSUE TITLE
Simple fds file with negative z value crashes fds execution

### ISSUE THREAD

**Issue by zrui** [firemodels/fds#5146]
Hi, 
If you run the err.fds in attached zip file, the fds will crash. 
But if you change the minimum and maximum z value in MESH line from -4.0, -0.25 to 0.25, 4.0,  then it runs without problem. 

Looks like fds doesn't handle negative value properly. 

[err.zip](https://github.com/firemodels/fds/files/1072111/err.zip)

**Comment by drjfloyd** [comment]
I can repeat your error with 6.5.3, but not with the current source. It appears whatever the error was that it isn't happening in the latest source. For now just adjust your z values as you have done and the next release should work OK.

**Comment by sbenkorichi** [comment]
Yes we had this problem reported few weeks ago. Kevin had fixed this bug which will be available in next maintenance release. This issues appeared with  negative values of Z axis.

Sent from my phone
