### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#5147]
**FDS 6.5.3 01/20/2017
Win7 x64**

I have a question concerning the velocities at a boundary.

I am simulation a channel, inflow and VENT OPEN at the other side, 20 m x 1 m x 1 m.
I am measuring the velocity in the channel at x = 15 m, from one side to the other side (x = 0 to 1 and y = 0 to 1).

1. CHANNEL_FLOW.fds builds the channel with 1 MESH.
2. CHANNEL_FLOW_02.fds builds the same channel with 1 MESH (4 times +1 cell) and 4 OBSTs at the boundaries.

I would have suspected a parabolic curve, Vel = 0 m/s directly at the boundaries, max vel in the middle, symmetric.

The simulations of CHANNEL_FLOW.fds and CHANNEL_FLOW_02.fds show different outcomes:

1. **CHANNEL_FLOW.fds** (without OBSTs)
Vel at boundaries does not equal 0 and is not symmmetric (mind the horizontal ending at the +side).

2. **CHANNEL_FLOW_02.fds** (with OBSTs)
Vel at boundaries does equal 0 at the -side but does not equal 0 at the +side.

Any help is appreciated.

_Boris_

Please rename *.fds.txt -> *.fds

[CHANNEL_FLOW_02_line.pdf](https://github.com/firemodels/fds/files/1074159/CHANNEL_FLOW_02_line.pdf)
[CHANNEL_FLOW_line.pdf](https://github.com/firemodels/fds/files/1074160/CHANNEL_FLOW_line.pdf)
[CHANNEL_FLOW.fds.txt](https://github.com/firemodels/fds/files/1074161/CHANNEL_FLOW.fds.txt)
[CHANNEL_FLOW_02.fds.txt](https://github.com/firemodels/fds/files/1074162/CHANNEL_FLOW_02.fds.txt)

**Comment by sbenkorichi** [comment]
The team developers are at IAFSS conference this week. Next week one member will look at your files.

Regards
Salah

Sent from my phone

________________________________

**Comment by boris-stock** [comment]
Thank you very much for your quick answer.

Boris

**Comment by Er9y714** [comment]
CHANNEL_FLOW.fds
30 sec run
CELL_CENTERED=.TRUE.
GVAC=0,0,0

It seems that the velocity fluctuates but on average it seems okay.

 last 4 sec averege
![image](https://user-images.githubusercontent.com/26166281/27139498-7d2599f2-5123-11e7-835a-584c714db1e3.png)

last 30 sec average
 
![image](https://user-images.githubusercontent.com/26166281/27139753-1f7f6ebc-5124-11e7-9368-82220959d3e1.png)

**Comment by boris-stock** [comment]
Thanks for your reply.

Please mind the attached *.PDFs.

As far as I know
&DEVC XB=15.0,15.0,0.0,1.0,0.5,0.5, QUANTITY='VELOCITY', ID='Vel-15-y', POINTS=11, TIME_HISTORY=.FALSE./
is averaged (Chapter 17.2.2) over half the time (in this case 30 s) and to me this
https://github.com/firemodels/fds/files/1074159/CHANNEL_FLOW_02_line.pdf
as an average is questionable.

**Comment by drjfloyd** [comment]
In LES mode FDS uses a wall model.  The flow at the wall will not be zero unless you force it to be by setting NO_SLIP. 

We do not interpolate device outputs; therefore, each of the locations for your line DEVC will snap to the center of the nearest grid cell. This means the last two points in your line device are snapping to the center of the same grid cell which is why there is a plateau.  Instead of doing 0 to 1 with 11 points, since your grid size is 10 cm, do 0.05 to 0.95 with 10 points. This will put devices at the center of each grid cell.  If you do that and average for a long enough period of  time you should get a symmetric profile.

**Comment by boris-stock** [comment]
Dr. Floyd,

thank you very much for your help. Shame on me, that was to simple...
Shifting the DEVCs works great.

[CHANNEL_FLOW_03.fds.txt](https://github.com/firemodels/fds/files/1075938/CHANNEL_FLOW_03.fds.txt)
[CHANNEL_FLOW_03_line.pdf](https://github.com/firemodels/fds/files/1075939/CHANNEL_FLOW_03_line.pdf)

One last question:
Using NO_SLIP=.TRUE. works great in the case **with OBST**s at the boundaries. I think the velocities at the boundary will tend to 0 with smaller cell size.

[CHANNEL_FLOW_05_line.pdf](https://github.com/firemodels/fds/files/1075950/CHANNEL_FLOW_05_line.pdf)
[CHANNEL_FLOW_05.fds.txt](https://github.com/firemodels/fds/files/1075949/CHANNEL_FLOW_05.fds.txt)

Surprising to me, the case **without OBST**s shows a constant line. I would have suspected that with FREE_SLIP=.TRUE., but it is set .FALSE.?

[CHANNEL_FLOW_06.fds.txt](https://github.com/firemodels/fds/files/1075961/CHANNEL_FLOW_06.fds.txt)
[CHANNEL_FLOW_06_line.pdf](https://github.com/firemodels/fds/files/1075962/CHANNEL_FLOW_06_line.pdf)

Any advice is appreciated.

_Boris_

**Comment by drjfloyd** [comment]
@rmcdermo can you take a look at the last case in the Boris's previous comment.

**Comment by rmcdermo** [comment]
This is indeed a bug.  For some reason I have not sorted out yet, the DEFAULT SURF is not applying the NO_SLIP bc.  NO_SLIP works if you apply it to specific surfaces, though.  That is, first line does not work, second one does (once applied to each wall).

&SURF DEFAULT=.TRUE., NO_SLIP=T/
&SURF ID='no-slip wall', NO_SLIP=T/

**Comment by mcgratta** [comment]
What happens if you give the `SURF` an `ID`, like
```
&SURF ID='wall', DEFAULT=.TRUE., NO_SLIP=T/
```

**Comment by rmcdermo** [comment]
Yep.  That works.

**Comment by mcgratta** [comment]
Should we stop with an `ERROR` if `SURF` line has no `ID`?

**Comment by drjfloyd** [comment]
I think we should throw an error.  Good catch, I missed that there wasn't an ID on that line.

**Comment by rmcdermo** [comment]
Jason,

What about naming it internally?  I was about to do this:
```
IF (DEFAULT) THEN
      IF (TRIM(ID)='null') ID = 'DEFAULT SURF'
      SURF_DEFAULT = TRIM(ID)
ENDIF
```
I can see Boris's logic that if the SURF has been declared as default you would not need to apply it specifically to any VENT or OBST.

**Comment by drjfloyd** [comment]
This makes sense for DEFAULT but we should have an error of not.

**Comment by rmcdermo** [comment]
OK, I'll add one.

**Comment by rmcdermo** [comment]
Kevin,

The attached runs very fast.  It is low Reynolds number, so you should quickly see a parabolic profile develop.  Just add a SURF ID.

[test.fds.txt](https://github.com/firemodels/fds/files/1086424/test.fds.txt)

As we discussed, it looks to me like we are already checking for an ID for default surf.  At line 5685 we have

```
! Check if SURF_DEFAULT exists

CALL CHECK_SURF_NAME(SURF_DEFAULT,EX)
IF (.NOT.EX) THEN
   WRITE(MESSAGE,'(A)') 'ERROR: SURF_DEFAULT not found'
   CALL SHUTDOWN(MESSAGE) ; RETURN
ENDIF
```

There are other things to clean up, like redundant calls to SET_SURF_DEFAULTS, etc.

**Comment by mcgratta** [comment]
Cleaned up DEFAULT logic, #5155.

**Comment by mcgratta** [comment]
Looks like the changes passed firebot last night. I will close this issue.
