### ISSUE TITLE
Zero Hydrogen in the Fuel and non-zero soot yield 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5148]
If I set;
the number of H atom in fuel to zero
and
soot yield bigger than zero,

In CHID.out
Products section shows negative values for H20 mole fraction and a positive number for Soot(C0.9H0.1).

**Comment by drjfloyd** [comment]
Set SOOT_H_FRACTION = 0.  We assume a small portion of the soot is hydrogen. We need to add some logic to not do that if there is no hydrogen in the fuel.

**Comment by Er9y714** [comment]
Thank you for the reply!
