### ISSUE TITLE
Visibility verification and validation

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5159]
A [recent post](http://www.thunderheadeng.com/2017/06/smoke-visibility-and-obscuration-in-pyrosim/) on the Thunderhead Engineering site discusses verification and validation of smoke visibility using FDS.

Jason recently added VISIBILITY DEVCs to the OBST in the [beam_detector](https://github.com/firemodels/fds/blob/master/Verification/Detectors/beam_detector.fds) case.  This case is shown in the FDS User Guide and has previously served only as qualitative visual verification of the smoke obscuration.

Glenn recently added the capability to quantify the visibility in Smokeview and has created his own verification case for Smokeview.  This case follows similarly to the Thunderhead verification case.  But the quantitative information is only available on the image within Smokeview.  So, Glenn is now working to write this information to a file so it can be processed by firebot.

The goals of this issue are:

1. to get both verification cases (beam_detector and Glenn's) into quantitative shape for firebot to check,

2. to add a validation case (to be discussed, possibly the 2007 VTT paper) to the current validation guide for smoke visibility.

**Comment by gforney** [comment]
added SHOWSMOKESENSORS script keyword to the smokeview scripting language.  This keyword will cause smokesensor values to be output to a file named casename_ss.csv  (at the current time as defined by the smokeview script keyword SETTIMEVAL ) .  You can have multiple SETTIMEVAL/SHOWSMOKESENSORS pairs to output smokesensor values at multiple times.

A smokesensor in this context is a regular FDS device where the SMOKEVIEW_ID on the &PROP line has value smokesensor as in:

&PROP ID='smoketest' SMOKEVIEW_ID='smokesensor' /
&DEVC XYZ=1.8,0.55,2.00, QUANTITY='VISIBILITY', ID='vis1' PROP_ID='smoketest' /

The smokesensor values are output in the same order as the &DEVC lines are defined in the fds input file.

**Comment by mcgratta** [comment]
Found a bug in `beam_detector.fds`. The line
```
&DEVC XB=1.0,1.0,0.0,0.9,0.0,2.0, QUANTITY='PATH OBSCURATION', ID='obst0p9' /
```
should be
```
&DEVC XB=1.0,1.0,0.0,0.9,2.0,2.0, QUANTITY='PATH OBSCURATION', ID='obst0p9' /
```
I fixed and committed. How the FDS results and Glenn's spreadsheet calcs are consistent.

**Comment by drjfloyd** [comment]
Thanks

**Comment by gforney** [comment]
added a bash script to smv repo that compares corresponding numbers at the bottom of two csv files (to check whether expected opacity matches actual opacity as reported by smokeview).  am testing in smokebot now.  so smokebot will report an error if smoke is drawn two light or too dark in the smoke_test.fds test case

**Comment by gforney** [comment]
firebot now outputs opacity values (that smokeview sees) for the case beam_detector  to the file beam_detector_ss.csv .  let me know if you want me to check these values in firebot the same way I am checking a similar case in smokebot
