### ISSUE TITLE
Smokeview - colorbar

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5160]
When CO, CO2 and O2 slices are on the same plane, a 'fractional effective dose' slice appears. 
While viewing smokeview, first I load this FED slice > color bar changes to FED > then if I load another slice (e.g. velocity), color bar does not switch back to default (rainbow). 

Can this be adjusted so that color bar returns to one which was previously selected?

Thank you.

```
&HEAD CHID='A'/
&TIME T_END=2.0/
 

&MESH ID='1', IJK=10,10,10	, XB=0,1,	0,1,	0,1 / 
 
&REAC ID='S',
      C=6,
      H=7,
      O=2,
      HEAT_OF_COMBUSTION=2.6E4,      CO_YIELD=0.1, /
 
&SLCF QUANTITY='VELOCITY',    PBZ=.8/  
&SLCF QUANTITY='VOLUME FRACTION',   SPEC_ID='CARBON MONOXIDE',  PBZ=.8/  
&SLCF QUANTITY='VOLUME FRACTION',   SPEC_ID='CARBON DIOXIDE',  PBZ=.8/ 
&SLCF QUANTITY='VOLUME FRACTION',   SPEC_ID='OXYGEN',  PBZ=.8/
&TAIL /
```

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
should be fixed in smokeview posted here

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
If I pick the color bar first, then do the sequence (ex: Temperature>FED>Temperature) then it works. But if I run smokeview, without choosing any color bar (i.e. using default = rainbow) then do the sequence (temp > FED> Temp), it fails to change back to rainbow.

**Comment by gforney** [comment]
ok, I'll look at this some more

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
It works! Thanks Glenn!
