### ISSUE TITLE
Different DEVC time histories from same input file

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5161]
Users are reporting different results for two different runs using the attached input file.  The discussion forum thread is given [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/TFPtZAq7CV0/hK4NLOmnAwAJ).

I want to make sure this is not the result of arrays that are not initialized.

[teste.fds.txt](https://github.com/firemodels/fds/files/1094228/teste.fds.txt)

**Comment by mcgratta** [comment]
I ran this case with the Intel Thread Checker and it produced no errors, or at least I did not see evidence of any. However, when I run the case with 1 MPI process and 1 OpenMP thread, I get different results than if I run the case with 1 MPI process and 2 OpenMP threads. So it does not appear to be a problem with MPI. However, I cannot yet pinpoint what is causing the problem in OpenMP.

**Comment by lu-kas** [comment]
sry for the shortness, i'm on the move

there is a potential openmp bug with intel fortran 2017, could you please check with intel 2017 and gcc?

http://www.fz-juelich.de/ias/jsc/EN/Expertise/Supercomputers/JURECA/UserInfo/KnownIssues.html

intel is looking into this already

best, lukas

**Comment by mcgratta** [comment]
I ran the case with the Gnu Fortran compiler, with 1 OpenMP thread and then with 6. I get similar divergent results after about 5 s. So I think we have a flaw in some OpenMP directive in FDS, but so far the Intel Thread Checker has not found it.

**Comment by mcgratta** [comment]
More news. I ran the case with Intel Fortran 17 using `-O1` optimization. The divergence in results does not appear. Using `-O2`, it does. The Intel Thread Checker runs with `-O0`, and it did not detect a problem. 

Sigh, these are the worst kinds of bugs.

**Comment by mcgratta** [comment]
I think I found and fixed the problem, #5192. I'll leave this case open until it passes firebot and I add the case to the verification suite.
