### ISSUE TITLE
Move scatterplot_outputs.csv files to Manuals directory

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5167]
Kevin,

I've noticed that the scatterplot outputs are being written to the Utilities/Matlab directory.  I am trying to keep this clean.  Can you please move the outputs to the respective Manuals directories.

Thanks,
R

**Comment by mcgratta** [comment]
I'll see if firebot still works. I just moved the output files to the `SCRIPT_FIGURES` folders holding output of the Matlab scripts.

**Comment by mcgratta** [comment]
This is all working fine.
