### ISSUE TITLE
RAMP_Q associated with circular vent

### ISSUE THREAD

**Issue by Carlo31** [firemodels/fds#5179]
Hello,

I am using FDS to represent a circular fire. 
Following the user guide, radius and center coordinates are specified on the vent line of the fire, I intend to start a fire at T=0s after an initialization time of 40s. 
FDS represented correctly the trend of the HRR implemented in the RAMP_Q lines but started at the very beginning of calculation at T= - 40s.
It seems that FDS for circular vent with a RAMP_Q and fire uses T_BEGIN instead of T=0 as origin for starting the burning.
How can we use a circular vent associated with a fire without changing the RAMP_Q times by adding the time T we want and the duration of initialization ?

Thank you,
Carlo

**Comment by rmcdermo** [comment]
Please submit a very simple input file (use .txt as extension).  Thanks.

**Comment by Carlo31** [comment]
There is the simple file.
There are two fire surfaces with the original RAMP_Q : one square and one circular, and another circular fire with the RAMP_Q time  including the initialization duration.
[Test_Debut_HRR.txt](https://github.com/firemodels/fds/files/1109156/Test_Debut_HRR.txt)

**Comment by rmcdermo** [comment]
Both fires using POOLFIRE start at T=0.  What version of the code are you using?

**Comment by Carlo31** [comment]
I am using the 6.4.0 FDS version. Is this problem solved in most recent version ?

**Comment by rmcdermo** [comment]
If I understand your description correctly, then yes.  I did not understand the point of the 3rd fire in your example.  POOLFIRE2 starts at 40 s and the simulation ends there.  Here are screenshots with latest code.  Note time stamps.

![screen shot 2017-06-28 at 11 18 02 am](https://user-images.githubusercontent.com/4418497/27645249-a22395c6-5bf3-11e7-9dd5-ddc4f2e2a77d.png)

![screen shot 2017-06-28 at 11 18 33 am](https://user-images.githubusercontent.com/4418497/27645260-a4a8e026-5bf3-11e7-8033-a24d6d11034e.png)

![screen shot 2017-06-28 at 11 18 44 am](https://user-images.githubusercontent.com/4418497/27645268-a7ed53e8-5bf3-11e7-8b56-4a234214ec10.png)

**Comment by Carlo31** [comment]
Thank you, I will download the new version and work with it.
The third fire was an adaptation to obtain a similar time as the square fire because the second starts immediately in the 6.4.0 version I use.
![capture1](https://user-images.githubusercontent.com/29755280/27646071-030ec1b0-5c28-11e7-880b-23b18fc0d726.PNG)
![capture2](https://user-images.githubusercontent.com/29755280/27646082-088299dc-5c28-11e7-8a95-e6ce7d25a647.PNG)

**Comment by rmcdermo** [comment]
OK, I'll close for now, but let me know if 6.5.3 does not work for you.
