### ISSUE TITLE
debug case seg faults with mpi

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5241]
[rmcdermo@burn Species]$ /home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Build/mpi_intel_linux_64ib_db/fds_mpi_intel_linux_64ib_db hrrpuv_reac_soot.fds 
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fds_mpi_intel_lin  0000000008E4AB74  Unknown               Unknown  Unknown
libpthread-2.12.s  0000003F2660F7E0  Unknown               Unknown  Unknown
libipathverbs-rdm  00002AD4C48168E3  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008C6E522  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008CB75FB  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008C6B027  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008C69DA3  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008CA5D5F  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008C608F6  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008C431CF  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008B28DD1  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008B31F2D  Unknown               Unknown  Unknown
fds_mpi_intel_lin  0000000008B0663C  Unknown               Unknown  Unknown
fds_mpi_intel_lin  00000000034286ED  MAIN__                     80  main.f90
fds_mpi_intel_lin  000000000040A64E  Unknown               Unknown  Unknown
libc-2.12.so       0000003F25A1ED1D  __libc_start_main     Unknown  Unknown
fds_mpi_intel_lin  000000000040A529  Unknown               Unknown  Unknown

**Comment by sbenkorichi** [comment]
Randy,
Have you had the same error with fds_mpi_intel_linux_64 ?

**Comment by rmcdermo** [comment]
Have not tried.  If _db fails, not point in moving forward.

**Comment by sbenkorichi** [comment]
If you send me the file I will take a look.

**Comment by rmcdermo** [comment]
It is in the repo.  Verification/Species/hrrpuv_reac_soot.fds

**Comment by sbenkorichi** [comment]
Randy, 
Ive checked the db one and it finished with no errors. 
```
[salah@jbk27s092 Debug]$ ./fds_mpi_intel_linux_64_db hrrpuv_reac_soot.fds 
 Mesh 1 is assigned to MPI Process 0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : July 17, 2017  18:38:34
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-2077-ged49b1e-dirty
 Revision Date    : Sat Jul 15 16:57:14 2017 -0400
 Compilation Date : Jul 17, 2017  18:34:13

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.1
 MPI library version: Open MPI v2.0.2, package: Open MPI salah@jbk27s092.dhcp.ulster.ac.uk Distribution, ident: 2.0.2, repo rev: v2.0.1-348-ge291d0e, Jan 31, 2017

 Job TITLE        : Test of HRRPUV REAC output for soot oxidation
 Job ID string    : hrrpuv_reac_soot

 Time Step:      1, Simulation Time:      0.11 s
 Time Step:      2, Simulation Time:      0.22 s
 Time Step:      3, Simulation Time:      0.34 s
 Time Step:      4, Simulation Time:      0.45 s
 Time Step:      5, Simulation Time:      0.56 s
 Time Step:      6, Simulation Time:      0.63 s
 Time Step:      7, Simulation Time:      0.69 s
 Time Step:      8, Simulation Time:      0.74 s
 Time Step:      9, Simulation Time:      0.78 s
 Time Step:     10, Simulation Time:      0.82 s
 Time Step:     20, Simulation Time:      1.36 s
 Time Step:     30, Simulation Time:      1.97 s
 Time Step:     40, Simulation Time:      2.63 s
 Time Step:     50, Simulation Time:      3.10 s
 Time Step:     60, Simulation Time:      4.02 s
 Time Step:     70, Simulation Time:      4.67 s
 Time Step:     80, Simulation Time:      5.24 s
 Time Step:     90, Simulation Time:      5.69 s
 Time Step:    100, Simulation Time:      6.16 s
 Time Step:    173, Simulation Time:     10.00 s
MPI process      0 has completed

STOP: FDS completed successfully (CHID: hrrpuv_reac_soot)
```

**Comment by rmcdermo** [comment]
Yeah, we are having mpi problems.  Not sure what is going on.

**Comment by sbenkorichi** [comment]
Maybe it's related to Infiniband, I don't have it on my machine. 
When I see the bug, it looks an issue of memory, but the file doesn't much cells at all. I dunno.

**Comment by sbenkorichi** [comment]
Randy, 
Have you tried the mpi with gnu? 
Does it result in the same error or it works?

**Comment by mcgratta** [comment]
I can't reproduce the error.

**Comment by sbenkorichi** [comment]
Maybe a good way, is to install the latest mpi version (if you're not doing so), and test if it solves it.

**Comment by rmcdermo** [comment]
This is somehow related to the openmpi woes.  If I go back to the non-"b" version of the openmpi build it works.

Fire Dynamics Simulator

 Current Date     : July 19, 2017  09:27:23
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-2096-g5e48019-dirty
 Revision Date    : Tue Jul 18 16:40:19 2017 -0400
 Compilation Date : Jul 19, 2017  09:22:45

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.1
 MPI library version: Open MPI v2.1.0, package: Open MPI gforney@burn Distribution, ident: 2.1.0, repo rev: v2.0.1-696-g1cd1edf, Mar 20, 2017
