### ISSUE TITLE
Problem with simulation of fire coupled to HVAC network.

### ISSUE THREAD

**Issue by ndroesbeke** [firemodels/fds#5290]
Hi,

I'm writing my master thesis about the interaction of a single room fire with a ventilation network. I have set up a complex ventilation network and its simulation without fire is fine. When I include a fire with a constant MLRPUA, the simulation gets stuck at about 44s. I do not have this problem when the HVAC network is much more simple... 

I hope anyone can help me with this?

Kind regards,

Nicholas
[VentilationNetwork.txt](https://github.com/firemodels/fds/files/1188429/VentilationNetwork.txt)

**Comment by mcgratta** [comment]
OK, we'll take a look at it.

**Comment by drjfloyd** [comment]
Your duct system is pretty complex and not something I am going to visualize just by looking at the inputs.  Please provide a drawing of the system with nodes and ducts labeled and some discussion of what the system is meant to represent

Where are you getting your loss data from?
Duct 2_23 has a loss of 1.93 in one direction but 500,000 in the other.

Where is your fan curve data from?
Max pressures of 8000 and 10400 Pa are quite high for a fan.  Also with a duct area of 0.16 m^2 the full flow for the two fans is ~40 m/s and ~100 m/s.  These are very high flow rates in an HVAC system and 100 m/s is no longer low speed flow.

**Comment by ndroesbeke** [comment]
Thank you for your reply, 

The ventilation system is based on an actual ventilation network of a research facility. They did measurements of the flow rates and pressure at different points. The loss data for each duct is calculated by  K=2*p/(rho* v^2), with p the pressure, rho the density and v the velocity. Duct 2_23 is a non-return valve, that's why I set the loss in one direction very high. 

The conditions of the room without fire are a pressure of -90Pa and an admission volume flow rate of 0.4m^3/s. No data about the fans were given, so I iterated until the fans gave the correct conditions for the room. 

You made a good point about the small duct area at the fans. These high flowrates occur only up until node 3 and node 18. The ventilation system will likely have a larger duct area in those parts. I'll have a look at it.
![ventilationnetwork](https://user-images.githubusercontent.com/30594360/28795209-4f525002-7639-11e7-8899-f0388d1650a1.png)

**Comment by drjfloyd** [comment]
I assume that the very high losses for 6_11, 7_14, 5_10, 4_9, and 9_19 are closed dampers?   

I'd combine 0_1 and 1_2 into one duct (add the losses together) and same for the exhaust side.  Remove the cross-ducts with no flow.  Get rid of all the cross connections with very high losses.  They will have almost no flow in them and the very high K values might be leading to numerical precision issues in the flow matrix.  Looks like you would just keep the 3-8-18 connection (and I'd collapse that into one duct).   You should include node losses for 3 and 18 for the tee. A tee will add a good deal of loss.  Same for each tee you remove, add the appropriate forward and reverse loss for the path through the tee to the duct.  For example for node 7 get rid of the duct to 14 and then you can combine 6-7 and 7-12 and add losses to the new duct to represent main-branch to side-branch flow from 6-12 and side-branch to main-branch flow for 12-6.  Similar elsewhere. For any removed cross connections, combine ducts and add the tee loss to the duct loss.

**Comment by drjfloyd** [comment]
![image](https://user-images.githubusercontent.com/12799217/28796440-82de76e0-760b-11e7-8b8a-898ebaf9a340.png)

**Comment by drjfloyd** [comment]
![image](https://user-images.githubusercontent.com/12799217/28796456-9a4456a6-760b-11e7-9c85-dffb472fbe2c.png)

**Comment by mcgratta** [comment]
Is this the IRSN facility in France?

**Comment by ndroesbeke** [comment]
I was planning to simplify it as you showed. But I wanted to compare the simplified version with the complex one. I will follow your advice, thank you for your help.

Yes, it is the IRSN facility.

**Comment by mcgratta** [comment]
There is a model of the HVAC included in the [PRISME validation simulations](https://github.com/firemodels/fds/tree/master/Validation/PRISME/FDS_Input_Files)

**Comment by ndroesbeke** [comment]
Ok, thank you. I'll take a look.
