### ISSUE TITLE
Update acad2fds plugin link in wiki on the third party tools page.

### ISSUE THREAD

**Issue by shkleinik** [firemodels/fds#5292]
Due to upcoming Codeplex shut down acad2fds plugin was moved to github. Github doesn't allow pull requests to project's wiki. So, can you please update the link?

Wiki page: https://github.com/firemodels/fds/wiki/Third-Party-Tools
Old link: http://acad2fds.codeplex.com/
New Link: https://github.com/shkleinik/acad2fds

Thanks!

**Comment by mcgratta** [comment]
Try it now.

**Comment by shkleinik** [comment]
It works great, thanks!
