### ISSUE TITLE
Do not output _cpu file if there is a setup error

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5304]
Kevin,
If I make a mistake in setup and the code stops with an error message, the only file that gets written out is the _cpu.csv file.  I think that for consistency it make sense to postpone creating that file until we actually have a run.  Here is an example that throws an error:

[chlorine_example.fds.txt](https://github.com/firemodels/fds/files/1194574/chlorine_example.fds.txt)

**Comment by mcgratta** [comment]
Try it now.

**Comment by rmcdermo** [comment]
Sorry.  Still does not work.  Try attached.  It produces test_cpu.csv but also throws an error.

[test.fds.txt](https://github.com/firemodels/fds/files/1195452/test.fds.txt)

**Comment by mcgratta** [comment]
It worked for me. I ran the case, it stopped with an error, and no output files were produced.

**Comment by rmcdermo** [comment]
OK, sorry, I was bouncing back and forth between mac and linux exes and got confused.  It works.
