### ISSUE TITLE
Atom balance check done before normalization of volume fractions

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5305]
Jason,
The attached case works if the volume fractions for the natural gas fuel are entered as decimals that are already normalized.  But this example comes from the user guide p. 148 where we imply that it is OK to enter volume % and FDS will normalize internally.

[chlorine_example.fds.txt](https://github.com/firemodels/fds/files/1195323/chlorine_example.fds.txt)

**Comment by drjfloyd** [comment]
Right now we assume that the NU inputs on REAC are based upon the the User inputs for SPEC.  So if the user were to define:

&SPEC ID='OXIDIZER',SPEC_ID='OXYGEN',VOLUME_FRACTION=100./
&SPEC ID='FUEL',SPEC_ID='METHANE',VOLUME_FRACTION=1./
&SPEC ID='PRODUCTS',SPEC_ID=....,VOLUME_FRACTION=..../

Then the REAC would need to be
SPEC_ID='OXIDIZER','FUEL','PRODUCTS'
NU=-0,02,-1,...

The METHANE example on page 148 uses simple chemistry where we figure out the NUs based on the species mixtures after input processing.

The CHLORINE example starting on page 148 uses complex chemistry and there the NUs reflects the SPEC input.

I think we should keep it that the NUs are based on the SPEC input, but need to edit the guide to make sure this is clear.  Do you agree?

**Comment by rmcdermo** [comment]
Well, I'm trying to wrap my head around a case where I would not want the NU for the FUEL in a REAC to be anything other than -1.  This is the basis I always use.  I think it makes more sense to assume the user wants the VOLUME_ or MASS_FRACTIONS normalized internally, and then to do the atom balance check on that lumped species composition.

But this is just my subjective opinion I guess.  Yes, at least we need to make the guide clear.

**Comment by drjfloyd** [comment]
The motivation for how it is coded now is the current chlorine example.  This input defines the volume fractions using the NUs from Eq 13.7.  Then the REAC NUs are simply -1, -1, 1.  This is pretty easy for the user to do, there is no need for them to take the time to normalize the species and compute the NUs based on a normalized species.  Your inputs are a strange case of some SPEC being normalized and others not. I'll edit the guide to make it clearer how we handle the REAC NUs

**Comment by rmcdermo** [comment]
I see how that looks simpler.  But I don't really like it.  It reads as "1 mole of Fuel + 1 mole of Air goes to 1 mole of Products".  This sounds like you are cutting the molar volume in half with each reaction.  That's my only complaint---what is shown to be "Air" is not.  "Air" is what we show in column of the Z2Y table, correctly normalized.  If that is not the case, then the molar weight for Air does not follow from the usual formulas involving mass fractions.

**Comment by drjfloyd** [comment]
In that case we need to disallow the input of non-normalized species. Then there can be no misinterpretation.  Otherwise when trying to do an atom balance we must assume that either the NUs are correct and the SPEC are incorrect or vice versa.

**Comment by drjfloyd** [comment]
My thought was to add this to the guide after in the chlorine example:

Also note that the values for {\ct NU} reflect the composition of the species as defined on the {\ct SPEC} lines. If, for example, the PVC {\ct SPEC} was defined as {\ct C0.5H1.5Cl1.5}, then the {\ct REAC} would require {\ct NU=-2,-1,1}.

**Comment by rmcdermo** [comment]
It's fine.  We have bigger fish to fry.  Every time I revisit this stuff I forget why everything was done.

Your clarification looks great.  Thanks.
