### ISSUE TITLE
Vent exhaust into domain with 45 deg direction problem

### ISSUE THREAD

**Issue by Tavacska** [firemodels/fds#5310]
Problem description:
In an all-open domain, a vent is open and has gas exhaust and dispersion to the X+ direction. Now, if the vent is open towards X-Y 45 degree, what is the dispersion result.

Assumption:
&MESH IJK=100,100,100, XB=0.0,50.0,0.0,50.0,0.0,50.0 /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMIN', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&SURF ID='NITROGEN PURE', TMP_FRONT= 100,MASS_FRACTION(1)=1.0, SPEC_ID(1)='PURE NITROGEN',VEL=-15.5975, RGB=0,255,255 /

&OBST XB=	0	,	10	,	25	,	26	,	25	,	26	, COLOR='RED'/	Exhaust 1 Location 2
&VENT XB=	10	,	10	,	25	,	26	,	25	,	26	, SURF_ID='NITROGEN PURE',	COLOR= 'GREEN' /

My Solution:
Now, I change the vent velocity to 45 deg and match the overall velocity:
&SURF ID='NITROGEN PURE', TMP_FRONT= 100,MASS_FRACTION(1)=1.0, SPEC_ID(1)='PURE NITROGEN',VEL=-11.029, VEL_T=11.029, RGB=0,255,255 /

But the Mass Flow (kg/s) detected is 1.4 times less than the original speed. My guess is that the mass flow calculation is just using the VEL not the VEL_T.
How to solve this problem, thanks.

**Comment by rmcdermo** [comment]
VEL is the normal component of velocity, which controls the mass flux into the domain. This is not a bug and should be asked in the forum.
