### ISSUE TITLE
Problem with FDS on Apple

### ISSUE THREAD

**Issue by DavidShep** [firemodels/fds#5314]
I cannot get even simple input files to run on the mac.  The problem seems to occur when the domain gets to be on the order of 300,000 cells and a reac line is added.  It occurs whether or not there is a fire.

I am using the pre-compiled version of FDS.  I have tried it on multiple computers.  I have sent it to a colleague at a different company, and he also got the same error. 

[model01a.txt](https://github.com/firemodels/fds/files/1204747/model01a.txt)

**Comment by rmcdermo** [comment]
Dave,
Sorry, we'll take a look.

**Comment by rmcdermo** [comment]
Marcos,
I'm putting you on this if you have time since I'll be in Germany for the next week.  But I may have time to look at it today.

**Comment by rmcdermo** [comment]
Glenn,
Could you also take a look?  I confirmed that the error still occurs with latest code and looks to be a 3D array issue:

https://stackoverflow.com/questions/23130045/fortran-90-segmentation-fault-invalid-memory-reference-with-scalable-3d-ar

**Comment by marcosvanella** [comment]
I'll take a look.

**Comment by marcosvanella** [comment]
David do you have this line defined in your ~/.bash_profile file?:

```
# increase the stack space:
ulimit -s 65532
```

This will increase the size of memory assigned to temporary arrays declared in FDS routines.
Thank you,
Marcos

**Comment by gforney** [comment]
it works for me if ulimit -s 65532 is in one of my startup files and fails if it is not.

I added it to the FDS/SMV installer script for the mac install

**Comment by DavidShep** [comment]
The test file works with the ulimit change.  I am now trying with my real input file.

**Comment by marcosvanella** [comment]
Indeed, the Mac OS default for stack memory is 8KB. 
BTW, I just figured 64KB is 1024*64 = 65536 bytes (binary), we can keep the 4 byte deficit I have on my computer, or make it even in the installer script.
Regards,
Marcos

**Comment by DavidShep** [comment]
The real model, which has 6 meshes in the 300k size range, now works.

Thank you for your quick response.  I should have reached out to you all sooner.

**Comment by rmcdermo** [comment]
Dave,
Thanks for letting us know.
