### ISSUE TITLE
Bug with fds2ascii under linux

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5325]
@mcgratta 
I'm creating this issue here, so you might look it up, or Glenn.
The issue appears to be under linux while under windows it's working. 
[test.txt](https://github.com/firemodels/fds/files/1228595/test.txt)

**Comment by sbenkorichi** [comment]
When I compiled it, it works under linux. There might be an issue with the bundle one.

**Comment by mcgratta** [comment]
I also see the error (NaNs) when running the fds2ascii that comes with the FDS linux release. If I compile fds2ascii myself, the case works.

Glenn -- can you check the build script for linux and determine where fds2ascii comes from. I assume it is the intel_linux_64 version. If I build using the makefile, everything is fine. Somehow, the fds2ascii that is bundled is not working properly.

**Comment by gforney** [comment]
I"ll take a look

**Comment by gforney** [comment]
I just built fds2ascii for all 3 platforms and put them here
https://github.com/firemodels/fds/releases/
give this a try and report back whether it works.   There haven't been any changes since we built the bundle except for updating our compilers so not sure what the problem is (or if this work, why it works)

**Comment by sbenkorichi** [comment]
Glenn,
Can you verify the link?

**Comment by sbenkorichi** [comment]
I've got it from the releases. It's working yes. Same as the one in the repo now. Thus, I'm closing it.

**Comment by gforney** [comment]
The link in my previous comment should be correct now
