### ISSUE TITLE
Output QUANTITY='Reaction Rate'  

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5332]
Kevin,
Is it possible to include reaction rate quantity as an output feature to track the different reactions of the components.

**Comment by drjfloyd** [comment]
In the current source you can get the total reaction rate of a species with REAC SOURCE TERM or the heat release rate contribution of a reaction with HRRPUV REAC (then using the HoC for the reaction you can back out the reaction rate).

**Comment by sbenkorichi** [comment]
Jason, besides that Kevin recently has added an output to track the mass component's evolution, where you can trace each one. However, I would like to see for each one instead of the total. 
My point is this: I would like to monitor the effects of each component on the total results.  Check the attached example ( the overall is the MLR), whereas for each component, you can see its effect on the total results. This is important, to verify that your components have an actual effect rather than just adding multiple of them while they have no effect.

![example](https://user-images.githubusercontent.com/20113030/29425803-74decbfc-837c-11e7-95ee-ad8379c40993.png)

**Comment by drjfloyd** [comment]
Ah, you wanted solid phase.  Yes, having an output to look at the specific solid reactions might be useful.

**Comment by sbenkorichi** [comment]
Yes, exactly.

**Comment by mcgratta** [comment]
It is now possible to output the mass of each component divided by the initial mass. I need to add the derivative too.

**Comment by sbenkorichi** [comment]
That would be a good step. I opened this issue as a reminder.

**Comment by mcgratta** [comment]
You can now put a `MATL_ID` along with `'NORMALIZED MASS LOSS RATE'` (but leave off the `SPEC_ID`). Try it and let me know if it works.

**Comment by sbenkorichi** [comment]
Perfect I just saw your pull. I'm out now. I will test it when I'm back and let u know. 
Cheers
Salah

**Comment by sbenkorichi** [comment]
Thanks Kevin, works perfectly great. Good job !

![ml-mlr](https://user-images.githubusercontent.com/20113030/29863864-ce390424-8d68-11e7-96c6-c542d8662930.png)
