### ISSUE TITLE
Errors on HVAC Verification cases

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#5333]
Running the Verification suite in burn with:
./Run_FDS_Cases.sh -m 10

I'm getting the following HVAC errors:

`[mnv@burn Verification]$ grep forrtl */*.err
HVAC/HVAC_mass_transport_combine.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
HVAC/HVAC_mass_transport_conv_0020.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
HVAC/HVAC_mass_transport_conv_0040.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
HVAC/HVAC_mass_transport_conv_0080.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
HVAC/HVAC_mass_transport_conv_0160.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
HVAC/HVAC_mass_transport_conv_0320.err:forrtl: severe (174): SIGSEGV, segmentation fault occurred
[mnv@burn Verification]$ grep Numerical */*.out
HVAC/HVAC_mass_transport_1.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_1)
HVAC/HVAC_mass_transport_2.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_2)
HVAC/HVAC_mass_transport_3.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_3)
HVAC/HVAC_mass_transport_4.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_4)
HVAC/HVAC_mass_transport_branch.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_branch)
HVAC/HVAC_mass_transport_conservation_1.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_conservation_1)
HVAC/HVAC_mass_transport_conservation_2.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_conservation_2)
HVAC/HVAC_mass_transport_conservation_3.out:STOP: Numerical Instability (CHID: HVAC_mass_transport_conservation_3)
HVAC/HVAC_mass_transport.out:STOP: Numerical Instability (CHID: HVAC_mass_transport)
`

Not sure what to make out of this.

**Comment by mcgratta** [comment]
Probably something I broke. I'll fix.

**Comment by mcgratta** [comment]
Try it now.
