### ISSUE TITLE
SLCF > INTEGRATED INTENSITY 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5337]
I have encountered few viewing issues. 
1.
Load/Unload
Load All z **or** Load All
>No reaction except **Show slice** switches from **gas** to **solid**.

2.
After loading ISO file, 
Dialogue
Data Bounds
Iso Surface
Tick only **outline** or **points**
>Point size and line width do not affect the rendering. 

Thank you.
SMV 6.5.4
[untitled.txt](https://github.com/firemodels/fds/files/1234035/untitled.txt)

**Comment by Er9y714** [comment]
Since I saw this on II slice, I would like to post this here as well. This is a different mesh configuration.  The domain is separated in half. There is this distinction in between meshes. Both flame and slice file have this gap. Is that known and as designed?

![image](https://user-images.githubusercontent.com/26166281/29457612-5694457e-841b-11e7-99d2-a89bf1cd57cd.png)

**Comment by gforney** [comment]
I"ll take a look at it

**Comment by mcgratta** [comment]
Put `CELL_CENTERED=.TRUE.` on the `SLCF` line. This will show the values in each grid cell without smoothing by the contour routine. This is probably an artifact of the angular discretization of the radiation transport routine.

**Comment by Er9y714** [comment]
Yes, this prevents the artifact. 

> Put CELL_CENTERED=.TRUE. on the SLCF line. This will show the values in each grid cell without smoothing by the contour routine. This is probably an artifact of the angular discretization of the radiation transport routine.

**Comment by mcgratta** [comment]
The artifact is due to the fact that we probably are not applying "ghost cell" values of this quantity at the boundary between the meshes. This only affects the visualization, not the calculation itself.
