### ISSUE TITLE
INIT VOLUME_FRACTION causing issue 

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#5338]
I have encountered an issue related to the recent addition of the VOLUME_FRACTION option for the INIT namelist.
Using the simple case attached (just initializing an array of solid particles), I get the following: 
ERROR: INIT line 1. Do not specify both MASS_FRACTION and VOLUME_FRACTION. (CHID
: particle_test)

I think this is related to a check for these two quantities (neither of which I am specifying) occurring before the initialization to their default zero values (line 9884 in read.f90)

version details are:
Current Date     : August 18, 2017  11:49:25
Version          : FDS 6.5.3
Revision         : FDS6.5.3-2281-g8f5712d
Revision Date    : Thu Aug 17 17:47:11 2017 -0400

[Input_particle_test.txt](https://github.com/firemodels/fds/files/1234219/Input_particle_test.txt)

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
Yes, I put the input check in the loop for reading INIT. Thanks for locating and reporting the bug,

**Comment by drjfloyd** [comment]
Fixed https://github.com/firemodels/fds/commit/d6617946a294e9803fd250bf495018beb407ee4f
