### ISSUE TITLE
Problem with a simulation of cable tunnel fire

### ISSUE THREAD

**Issue by Kaiye1994** [firemodels/fds#5340]
Hello everyone!
I am now working on a simulation of cable tunnel fire. The tunnel size was 3.7m (H)*2.8m (W), the length was 50 meters. The outside were 0.3m walls and a 0.4m thick floor. At the two ends of the tunnel, two holes were set as open doors (1m wide and 2m tall). All the mesh boundaries were open. Two groups of cable trays were set near the walls longitudinally along the tunnel. Each group has 8 layers of 3 cables. The fire origin was modeled as a burner under the lowest layer of cables in the middle of the tunnel. The burner was set for 60s, with a peak HRR of 500kW for 30s, a heat up period for 20s and 10s decay period. Then the burner was moved away. The ignition temperature of cable is 200℃ and its HRRPUA is 222 kW/m2. 
The model has been run on FDS 6.5.3, FDS 6.3.2 and FDS 6.1.2 separately for comparison. In all three cases, instability was observed. The stable fire spread along the cable tray in the upper layer will be disturbed, and pressure will also get really unstable. In addition, the similar phenomena was observed when the two ends were set as open portals. 
![240s](https://user-images.githubusercontent.com/31210262/29520727-e9b98ed6-86b4-11e7-97d1-94e68059731d.PNG)
HRR 240s
![354s](https://user-images.githubusercontent.com/31210262/29520737-f325d7a4-86b4-11e7-957c-6d02d66b9a02.PNG)
HRR 354s
![300s](https://user-images.githubusercontent.com/31210262/29520740-f7645e3a-86b4-11e7-8cfa-45471ca071eb.PNG)
Pressure 300s
![356s](https://user-images.githubusercontent.com/31210262/29520746-fabefdd8-86b4-11e7-9118-61ab4acc2feb.PNG)
Pressure 356s
Is this phenomena normal? Since the oxygen maybe consumed? But the HRR curve can also fluctuate over 10MW after 300s. Is the numerical result credible?
This is the FDS code of the cable tunnel fire model.

[cable tunnel fire.txt](https://github.com/firemodels/fds/files/1238885/cable.tunnel.fire.txt)

I appreciate it very much.

**Comment by mcgratta** [comment]
200 C is a very low ignition temperature, and you have no mechanisms for the cables to run out of fuel. So you create an oxygen limited upper layer and the HRR fluctuates because of the FDS extinction model. Where did you obtain your cable properties?

**Comment by Kaiye1994** [comment]
Thank you so much Kevin.
The cable properties are obtained from the literature：

Shen, T. S. (2006). Will the second cable tray be ignited in a nuclear power plant?. Journal of fire sciences, 24(4), 265-274.

So how can I avoid this unstable phenomena and get closer to the real situation? By raising the temperature and setting that the cables can be run out of ? How can I set the fuel can be run out of? @mcgratta

**Comment by mcgratta** [comment]
You are creating a fire scenario with little basis in reality and expecting to get sensible results. I cannot help you there. Easiest way to get the cables to burn out is to ramp the HRR up and down.
