### ISSUE TITLE
Setting local AUTO_IGNITION_TEMPERATURE problematic, feature request

### ISSUE THREAD

**Issue by klaakkon** [firemodels/fds#5341]
I've been working with a test case of enclosure with heptane pool and water mist fire protection. The case is based on IMO or FM 500 m3 machinery space fire test cases. I've tried to make attached cases generic with generic water mist properties and scale them down to make them faster to run. I've run them with FDS 6.5.3 from Jan 22 2017.

I first simulated the case without AUTO_IGNITION_TEMPERATURE set. In this case the pool fire gets extinguished some time after water mist has been activated, but the fuel burns then when it goes out of the domain. There are instructions for this kind of case in 6.4.0 release notes, telling to set a a realistic AUTO_IGNITION_TEMPERATURE in most of the domain and zero close to fuel outlet with INIT line. I have problems using this approach. The fire gets extinguished, but if I let the case run, it may re-ignite. The test case shows the re-ignition (the problem seems academic in the test case, as I could easily select the first time the HRR goes to zero as extinguishing time, but in real cases it's much less obvious where the first extinguishment happens). 

I've also tried to ignite the fire with a hot wall that exists a few seconds in the beginning of the simulation. Re-ignitions do not happen, but the temperatures that have to be used are huge, non-realistic. Also the pool rims get very hot. The problem, I suppose, is due to the large cell sizes that cannot capture the temperature boundary layer, but unfortunately I cannot use cells that would resolve it. I don't think it's an realistic option with structured mesh of FDS. I'm wondering whether it would be possible to hack the code so that instead of only gas temperature, it would also check attached wall temperature if it exceeds the auto ignition temperature? That wouldn't be correct either but in my opinion better.

The problem is not only ignition of the fire. Also in reality, hot surfaces near a pool fire maintain the fire with water mist fire suppression. So the simulations would be a bit more realistic if wall temperatures were better taken into account.
![hrr](https://user-images.githubusercontent.com/31214171/29526398-4825016a-869e-11e7-88e0-1fb733bbfdd8.png) 

[inputAitRegion.fds.txt](https://github.com/firemodels/fds/files/1239288/inputAitRegion.fds.txt)
[inputIgniter.fds.txt](https://github.com/firemodels/fds/files/1239289/inputIgniter.fds.txt)

**Comment by mcgratta** [comment]
This is current research activity. We don't have all the answers, but appreciate your feedback. I'll assign to Randy McDermott who will return from vacation this week.

**Comment by rmcdermo** [comment]
Sorry, I just happened upon this Issue.  There is nothing wrong with your ignitor temperature hack.  AIT is just a different kind of hack.  But I don't see how including wall cells helps.  Ultimately, the extinction model checks the gas temp against AIT of the cell.  Short of modeling the entire ignition process with finite-rate chemistry and resolved heat transfer, anything we do is a huge hack.  If you do not like the temperature approach to the ignitor, then try to use a convective heat flux from an ignitor particle.  It is the same thing---ultimately, you need to transfer a certain amount of heat to the gas, and given the other particle properties, this requires a huge temperature.  So, just short-circuit the temp with the heat flux.
