### ISSUE TITLE
Why HEAT_OF_REACTION is not required with IGNITION_TEMPERATURE and HRRPUA

### ISSUE THREAD

**Issue by khalidmoinuddin** [firemodels/fds#5344]
In my understanding, in the attached case file, the parameters HRRPUA, IGNITION_TEMPERATURE, and HEAT_OF_REACTION all are required when one wants to simulate the heating up and “ignition” of the fuel in a simplistic way. IGNITION_TEMPERATURE delays burning until the specified temperature is reached and HEAT_OF_REACTION is needed to account for the energy used to vaporize the fuel for the calculation of heat transfer at the solid surface. However, error message is coming up that “FDS was improperly set up”. Once I remove HEAT_OF_REACTION, the case runs. If HEAT_OF_REACTION is not needed, what equation is solved for the calculation of heat transfer at the solid surface?

[room.docx](https://github.com/firemodels/fds/files/1247255/room.docx)

**Comment by sbenkorichi** [comment]
Plz close the issue and submit this question in the discussion group. This place is for reporting bugs or requesting new features.
Thanks.

**Comment by rmcdermo** [comment]
Hi Khalid,

Salah is correct.  This should start as a discussion thread.  Thanks.

**Comment by khalidmoinuddin** [comment]
Hi Randy, I submitted it here as I remember we discussed at IAFSS conference to submit it in the issue tracker. In FDS4, there was an option of  combination of HRRPUA/MLRPUA, IGNITION_TEMPERATURE, and HEAT_OF_VAPORISATION. It worked there and why it is now different with FDS6?

**Comment by mcgratta** [comment]
`HEAT_OF_VAPORIZATION`

**Comment by rmcdermo** [comment]
I don't recall exactly what was discussed in Lund.  From your post above, it looks like this is something that the community could answer for you.  Please post to the forum.

**Comment by khalidmoinuddin** [comment]
I got the answer from Kevin's response. The case runs with HEAT_OF_VAPORIZATION. As HEAT_OF_VAPORIZATION is defined as latent heat of vaporization of liquid droplet (kJ/kg) - I expected that by now HEAT_OF_VAPORIZATION (from fds4) is changed to HEAT_OF_REACTION (in fds6). I guess for the solid fuel, if I know HEAT_OF_REACTION, I should use them as HEAT_OF_VAPORIZATION for this kind of modelling.
