### ISSUE TITLE
Conflict between initial velocity profile and vent

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#5345]
I have encountered an issue with setting an initial velocity profile in the domain and a matching profile on a vent (acting as an 'inlet'). 
As you can see in the attached case, an entirely different velocity profile is eventually established.

I haven't fully identified the cause of this, but it appears to be related to the specification of UWS/UW in the INIT_WALL_CELL routine, and results in the pressure iterations initially maxing out. 
Setting these to match the prescribed local values along height, instead of the global U0 vaule, seems to fix the issue.

I realize this may be a somewhat unusual case, as you might typically specify the vent profile, a zero initial velocity, and let it establish in the domain over time. Figured it was still worth pointing out that this inconsistent result can occur.

version details:
 Current Date     : August 24, 2017  11:36:53
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-2283-gd661794
 Revision Date    : Fri Aug 18 07:57:13 2017 -0400
 Compilation Date : 24/08/2017  11:04

[Input_vent_prof.txt](https://github.com/firemodels/fds/files/1249001/Input_vent_prof.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I see now. You've caught me right in the middle of overhauling the WIND routines. Give me a few more days to sort things out. My objective is to use the WIND line to fully specify a wind field and no longer rely on the SURF line as a "wall of wind". In the next release, if you specify U0, mean forcing will be turned on automatically which will continue forcing the mean flow velocity to U0. Hence, you won't need to specify a wall of wind in addition to U0, I'll let you know when things are ready for testing.

**Comment by ericvmueller** [comment]
Okay, thanks!

**Comment by mcgratta** [comment]
I just committed new code that changes the wind functionality. Your input file should now look like this:
```
&HEAD CHID='vent_prof',  TITLE='testing of inlet vent profile' /

&MESH IJK=50,50,50, XB=0,5,0,5,0,5./
&TIME T_END=10. /

&WIND U0=1, RAMP_U0_Z='i_prof'/

&VENT PBX=0, SURF_ID='OPEN' /
&VENT PBX=5, SURF_ID='OPEN'/
&VENT PBY= 0, SURF_ID='MIRROR'/
&VENT PBY= 5, SURF_ID='MIRROR'/
&VENT PBZ= 0, SURF_ID='MIRROR'/
&VENT PBZ= 5, SURF_ID='MIRROR'/

&RAMP ID='i_prof', Z= 0, F= 0 /
&RAMP ID='i_prof', Z= 0.2, F= 0.833 /
&RAMP ID='i_prof', Z= 0.4, F= 0.956 /
&RAMP ID='i_prof', Z= 0.6, F= 1.037 /
&RAMP ID='i_prof', Z= 0.8, F= 1.099 /
&RAMP ID='i_prof', Z= 1.0, F= 1.149 /
&RAMP ID='i_prof', Z= 1.2, F= 1.191 /
&RAMP ID='i_prof', Z= 1.4, F= 1.229 /
&RAMP ID='i_prof', Z= 1.6, F= 1.262 /
&RAMP ID='i_prof', Z= 1.8, F= 1.292 /
&RAMP ID='i_prof', Z= 2.0, F= 1.320 /
&RAMP ID='i_prof', Z= 2.2, F= 1.345 /
&RAMP ID='i_prof', Z= 2.4, F= 1.369 /
&RAMP ID='i_prof', Z= 2.6, F= 1.391 /
&RAMP ID='i_prof', Z= 2.8, F= 1.411 /
&RAMP ID='i_prof', Z= 3.0, F= 1.431 /
&RAMP ID='i_prof', Z= 3.2, F= 1.450 /
&RAMP ID='i_prof', Z= 3.4, F= 1.467 /
&RAMP ID='i_prof', Z= 3.6, F= 1.484 /
&RAMP ID='i_prof', Z= 3.8, F= 1.500 /
&RAMP ID='i_prof', Z= 4.0, F= 1.516 /
&RAMP ID='i_prof', Z= 4.2, F= 1.531 /
&RAMP ID='i_prof', Z= 4.4, F= 1.545 /
&RAMP ID='i_prof', Z= 4.6, F= 1.559 /
&RAMP ID='i_prof', Z= 4.8, F= 1.572 /
&RAMP ID='i_prof', Z= 5.0, F= 1.585 /

&SLCF PBY=2.5,QUANTITY='VELOCITY',VECTOR=.TRUE. /
&DEVC XB=0,0,2.5,2.5,0,5, POINTS=50, QUANTITY='VELOCITY', Z_ID='z', ID='u'/

&TAIL /
```
There is no longer a need for you to specify both U0 and a SURF VEL. You just specify U0 and open the left the right boundary. Give it a try and let me know if things work. Compile the latest working version of the code.

**Comment by ericvmueller** [comment]
I have successfully run the most recent source with the above input file.

The reason I posted this issue is that I had been attempting to compare differences in fire-induced flow fields between the vent, or 'wall of wind', approach and that of applying mean forcing within the domain.
However, as the former approach is no longer supported, this issue can be considered closed.

Thanks!
