### ISSUE TITLE
Segmentation fault on Linux due to mesh resolution

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/fds#5355]
I'm getting a strange segmentation fault that only occurs on Linux machines with the two inputs below (these are the reduced forms of a much larger model). The only thing that changes between the two is the mesh resolution. They both run fine under Windows, so there is some chance it is due to my particular setup.

Can anybody else reproduce this?

I'm using revision FDS6.5.3-598-geb56ed1 (on both platforms).

```fortran
&HEAD CHID='SegFault' /
&MESH ID='Mesh01', IJK=80,80,80, XB=0,4,0,4,0,4 /
&MESH ID='Mesh02', IJK=80,80,80, XB=4,8,0,4,0,4 /
````
```fortran
&HEAD CHID='NoSegFault' /
&MESH ID='Mesh01', IJK=40,40,40, XB=0,4,0,4,0,4 /
&MESH ID='Mesh02', IJK=40,40,40, XB=4,8,0,4,0,4 /
```

**Comment by sbenkorichi** [comment]
Hi Jake,

It looks to me your stack size is limited from your description. How to find out?
On terminal type: `ulimit -a`
Check stack size, it would be set a number of kbytes. That number is limit your machine to get fds run with large meshes. How to fix it?
On terminal type: `ulimit -s unlimited`
Now, test the cases that fails. If it works, that's great if not let me know what it says.
Now, if it works, this will be active only temporary on that terminal, if you close it, you will need to redo it each time. So, to make it last, you need one more thing to do.
Add that line ( I mean: `ulimit -s unlimited` ) to your `.bashrc` file on your home directory just do `vi ~/.bashrc` 
Then, log off and log in again. Test it to see if it's permanent or not by typing `ulimit -a` if it's set to unlimited then, you won't have an issue of this kind again.

Test it and let me know how it goes.

Salah

**Comment by JakeOShannessy** [comment]
Hmm, I already have `ulimit` set to unlimited, and the number of cells is much lower than what I usually run, but I'll take a look.

**Comment by JakeOShannessy** [comment]
You're right Salah, for some reason the `ulimit -s unlimited` line wasn't running properly on system startup. Solved.

**Comment by sbenkorichi** [comment]
Ok. Great !
