### ISSUE TITLE
Jet fan with and without shroud

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#5358]
When modeling a jet fan, one option is to place a shroud downstream of the obstruction used to model the fan (see Section 9.2.4 HVAC Fan Parameters in the FDS User Guide).

The attached image shows jet fans with and without the downstream shroud. For the standard HVAC model, the fan obstruction is 1 m long. For the model with a shroud, the fan obstruction is 0.875 m long and the downstream shroud is 0.125 m long. The shroud is defined by thin obstructions. The grid size is 0.125 m. All other HVAC parameters in the two models are identical.

When I plot velocities, the downstream results are quite different. If we look at the cells at X=0, which is the location of the HVAC outlet vent and the end of the shroud, there is a radial velocity component in the standard HVAC model, but with the shroud, there is essentially zero radial velocity. As a result, the velocity contours further downstream are very different in the two models.

Can you help me understand this? It seems to me that velocities on the -X face of the cells at X=0 should both have the same value and that downstream the results should be similar. Why does adding a short shroud change the downstream velocity so much?

Thanks,
Daniel Swenson

[hvac_shroud_question.txt](https://github.com/firemodels/fds/files/1258410/hvac_shroud_question.txt)
![hvac_shroud_question_model](https://user-images.githubusercontent.com/13338306/29794321-20b7ae92-8c0d-11e7-88f6-51ca9e9d08b6.png)
![hvac_shroud_question_vel_vectors](https://user-images.githubusercontent.com/13338306/29794324-26d0c246-8c0d-11e7-997f-abc48093bb48.png)
![hvac_shroud_question_vel_contours](https://user-images.githubusercontent.com/13338306/29794330-29992fc2-8c0d-11e7-9376-ac7bd59d9cac.png)

**Comment by rmcdermo** [comment]
To start to analyze this, you might add slice files of everything you can think of:

F_X,F_Y,F_Z
VORTICITY X, VORTICITY Y, VOTICITY Z
STRAIN RATE X, ...
VISCOSITY
DIVERGENCE
H

Maybe something will pop out that makes the result obvious.  It looks to me like there is room for expansion from the OBST.  We see the same effect in a VENT on the floor versus a VENT that is suppressed into the floor.  Bart Merci's group actually published a paper on this in FSJ this year.

**Comment by drjfloyd** [comment]
HVAC, like VEL or MASSFLUX only specifies the normal velocity.Tangential is
allowed to evolve from the over all flow solution unless a tangential
velocity is given.  The shroud stops this flow.

**Comment by rmcdermo** [comment]
Right, but it is a legitimate question as to why the same expansion does not happen at the exit of the shroud.  There is something interesting about getting the flow moving in the correct direction first that prevents the expansion.  As I said, the same effect is seen at a VENT entrance.  I'll create an example shortly.

**Comment by dvswenson** [comment]
Here is a model with a recessed vent. The same behavior is observed.

Did the Bart Merci group's paper reach a conclusion?

I have added plots of the additional quantities, but honestly, I do not have enough CFD background to understand the implications.

![flush and recessed vent](https://user-images.githubusercontent.com/13338306/29825594-82ebdbc8-8c9a-11e7-95f9-0c4ec3e18662.png)
![flush and recessed vent velocity](https://user-images.githubusercontent.com/13338306/29825604-860e7e28-8c9a-11e7-8998-86d8607823bd.png)
[recessed_vent.txt](https://github.com/firemodels/fds/files/1260571/recessed_vent.txt)

**Comment by dvswenson** [comment]
Here is the original HVAC model with the additional plot quantities.
[hvac_shroud_question.txt](https://github.com/firemodels/fds/files/1260603/hvac_shroud_question.txt)

**Comment by rmcdermo** [comment]
Dan,
Their paper is still in review, so I can't quote directly, but essentially they concluded that the recessed (or shroud) configuration is needed to get the correct downstream velocity decay.  I expect the paper will appear in Fire Safety Journal soon.  I'll try to remember to point you to it.

In the mean time, I'll play with your test case.  Thanks.

**Comment by drjfloyd** [comment]
Here is an image of y-vorticity at shortly after the start. Top is with the shroud and the black line is the exit plane (obstacles are hidden).  There is very quickly a noticeable difference in this quantity.  Pressure, divergence, velocity, and velocity fluxes still look fairly similar at this point in time.

![hvac_shroud_question_0104](https://user-images.githubusercontent.com/12799217/29830150-6ed657c0-8caf-11e7-8ae9-24deeda12c8f.png)

**Comment by sbenkorichi** [comment]
Randy,
I reckon this work you were talking about, If it's the one that was presented before Jason's presentation. Then, this is the paper of that work. 

http://www.sciencedirect.com/science/article/pii/S0379711217300486

**Comment by rmcdermo** [comment]
Well, this does not show the velocity inlet characterization.  There is another paper somewhere that I thought was independent of the IAFSS symposium.

**Comment by sbenkorichi** [comment]
This is the other work, it was regarding the high rise building. 
Maybe it's in different work.

http://www.sciencedirect.com/science/article/pii/S0379711217300279

**Comment by sbenkorichi** [comment]
I think this is the work you were referring to 
https://biblio.ugent.be/publication/7051383/file/7051384

**Comment by rmcdermo** [comment]
This is the precursor to the paper I'm referring to.  But there is a new one coming out that has almost exactly the recessed_vents.fds case that Dan posted.

**Comment by sbenkorichi** [comment]
Ok. I got ya

**Comment by rmcdermo** [comment]
Here is the velocity when FREE_SLIP=T for all surfaces (including VENTs).  Kevin let's talk about this when you get time.  I suspect there is something being done differently when an edge has two WALL_CELLS adjacent.  If one of these wall cells is a VENT we might have to treat it differently.

![recessed_vent_0449](https://user-images.githubusercontent.com/4418497/29832115-1ecba5f4-8cb5-11e7-88c4-362db82becd1.png)

Here is my simplified input file.
[recessed_vent.fds.txt](https://github.com/firemodels/fds/files/1260980/recessed_vent.fds.txt)

**Comment by rmcdermo** [comment]
I am not sure we are going to be able to make these two cases equivalent.  Below I am showing a cell centered vector slice of velocity (i.e., the velocity components on a face) for a slice through the first set of cells.  For the flush case, these components are obviously zero; but for the recessed you can see that a secondary component exists inside the cavity.  I do not see how we can include secondary components in the flush case.

![screen shot 2017-08-29 at 1 02 11 pm](https://user-images.githubusercontent.com/4418497/29833880-eb678ede-8cba-11e7-8a38-e598664ab1a4.png)

![screen shot 2017-08-29 at 1 01 37 pm](https://user-images.githubusercontent.com/4418497/29833903-06660d46-8cbb-11e7-80a5-4780f42d6fd9.png)

**Comment by rmcdermo** [comment]
In the previous comment, the top is the side view and the bottom-right is the recessed supply.

**Comment by rmcdermo** [comment]
I think this is something like a vorticity cannon: you cannot get the correct downstream profiles unless you have some wall effect at the entrance.  See the vorticity z slice below.  In the recessed version (top), the vorticity persists much further down the streamwise direction.

![screen shot 2017-08-29 at 1 13 15 pm](https://user-images.githubusercontent.com/4418497/29834125-da323bae-8cbb-11e7-89b5-df91672f317a.png)

**Comment by dvswenson** [comment]
Randy,

Here are two posts that looked at convergence of the downstream velocity profiles.

The first study (http://www.thunderheadeng.com/2015/02/modeling-jet-fans-part-1/) used a simple vent. It is similar to the FDS validation problem and good results were obtained for a model with 20 cells along the vent edge. Unfortunately that is a mesh size that is not realistic for real simulations.

The second study (http://www.thunderheadeng.com/2016/04/modeling-jet-fans-part-2-updated/) used coarser meshes and tested the velocity patch and HVAC options, both with and without a shroud. See Figure 8 for results. I was not particularly happy with any approach. If I had to choose, at this point I would recommend no shroud and the finer mesh.

Dan

**Comment by rmcdermo** [comment]
I would like to separate the discussion about how best to model a jet fan and whether or not there is a bug in FDS.  This issue relates to whether there is a bug.  Based on what I have seen with this test case, I am not sure we can make the two scenarios, with and without shroud, equivalent.  It might be possible to implement a profile across the VENT.  But this would not be easy in 3D for tangential components.

**Comment by dvswenson** [comment]
Yes, no need to talk about jet fans.

I only added that to illustrate downstream velocity profiles, since you had mentioned that the Bart Merci paper concluded that the recessed (or shroud) configuration is needed to get the correct downstream velocity decay.

**Comment by dvswenson** [comment]
Here are comparisons of velocity for two grid resolutions: duct side/cell size = 4 and 20. The first image is during the initial transient and the second after 10 seconds.
[fine_mesh.txt](https://github.com/firemodels/fds/files/1311288/fine_mesh.txt)
![with and without shroud initial](https://user-images.githubusercontent.com/13338306/30551422-fcb52e4e-9c5f-11e7-9ecf-049eb1e69c96.png)
![with and without shroud steady](https://user-images.githubusercontent.com/13338306/30551426-0134fc38-9c60-11e7-9cc0-a5a1a50583e9.png)

**Comment by dvswenson** [comment]
Here is the Z Vorticity.
![with and without shroud vorticity](https://user-images.githubusercontent.com/13338306/30551652-bf4661f8-9c60-11e7-91ed-8a0aab46dcd3.png)

**Comment by rmcdermo** [comment]
Dan,
I said above, that I do not expect these cases to be equivalent.  Is there something else to learn based on the new runs?  Else, I'd like to close this as an Issue.  Again, I think discussion on best practices for modeling a jet fans is separate.
Thanks,

**Comment by dvswenson** [comment]
It was useful to me to see that the flush vent results approached the recessed vent results as the mesh was refined. The downstream profiles become similar.

What I learned from this is to use caution when using vents with low resolution meshes. I guess that is true of everything.

Feel free to close the case.

**Comment by rmcdermo** [comment]
Ok, thanks.
