### ISSUE TITLE
EMISSIVITY: Material and Surface Properties

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#5391]
I investigated the definition of emissivity over the MATL and SURF namelist on the example of the test case _adiabatic_surface_temperature.fds_ with FDS 6.5.3 (FDS6.5.3-598-geb56ed1). The default value for emissivity is 0.9 at both namelists.

My cases:
- case 1: $\epsilon_{SURF} = 0.7$ and $\epsilon_{MATL} = 0.7$
- case 2: $\epsilon_{MATL} = 0.7$, $\epsilon_{SURF}$ DEFAULT (0.9)
- case 3: $\epsilon_{SURF} = 0.7$, $\epsilon_{MATL}$ DEFAULT (0.9)

## case 1
```
&SURF ID='plate'
      MATL_ID='STEEL'
      HEAT_TRANSFER_COEFFICIENT=10.
      THICKNESS = 0.0001
      BACKING = 'INSULATED',
      EMISSIVITY = 0.7 /

&MATL ID='STEEL'
      CONDUCTIVITY=50.
      SPECIFIC_HEAT=0.5
      DENSITY=6000.,
      EMISSIVITY = 0.7 /
```

## case 2
```
&SURF ID='plate'
      MATL_ID='STEEL'
      HEAT_TRANSFER_COEFFICIENT=10.
      THICKNESS = 0.0001
      BACKING = 'INSULATED' /

&MATL ID='STEEL'
      CONDUCTIVITY=50.
      SPECIFIC_HEAT=0.5
      DENSITY=6000.,
      EMISSIVITY = 0.7 /
```

## case 3
```
&SURF ID='plate'
      MATL_ID='STEEL'
      HEAT_TRANSFER_COEFFICIENT=10.
      THICKNESS = 0.0001
      BACKING = 'INSULATED',
      EMISSIVITY = 0.7 /

&MATL ID='STEEL'
      CONDUCTIVITY=50.
      SPECIFIC_HEAT=0.5
      DENSITY=6000. /
```
![emissivity_issue](https://user-images.githubusercontent.com/7759675/30020244-80ee4ba8-9163-11e7-98cf-a41139e9db73.png)

The MATL default value seems to override the SURF value in case 3. To my understanding, the SURF definition should override the MATL definition, or a warning should be displayed.

**Comment by rmcdermo** [comment]
Thanks, Gregor.  We'll take a lot.

**Comment by drjfloyd** [comment]
Can you post your  Case 3 so I am running the same case?

**Comment by gjaeger** [comment]
that's mit file: [AST_003.txt](https://github.com/firemodels/fds/files/1275389/AST_003.txt)

For the analysis I used the quantity with the ID _E_ on line 38:
`&DEVC ID='E', QUANTITY='EMISSIVITY', XYZ=0.52,0.52,0.45, IOR=-3 /`

**Comment by drjfloyd** [comment]
I see the issue problem now.  Inputs are being processed ok in read.f90; however, in wall.f90  we have a flag E_FOUND. If that flag is FALSE, we recompute emissivity based on the MATL components that exist in the first wall node.  E_FOUND is set to FALSE at the start of the pyrolysis routine and there is no logic to change it to true.  It looks like whomever added this bit of code didn't complete it.   I guess we could add a flag to the surface type that we set in read.f90 if EMISSIVITY is set on SURF and use that flag in the pyrolysis routine.

**Comment by mcgratta** [comment]
I think the `E_FOUND` logic is OK. It does get set to true once an emissivity is established. The way the code works is that the `MATL` emissivity always takes precedence, even its default value. The `SURF` emissivity only has precedence when there is no `MATL_ID`. I will make this clear in the User's Guide.

**Comment by mcgratta** [comment]
https://github.com/firemodels/fds/pull/5418
