### ISSUE TITLE
AST GAS: output quantities for emissivity and heat transfer coefficient

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#5392]
Version                : FDS 6.5.3
Revision               : FDS6.5.3-598-geb56ed1
FDS User's Guide : FDS6.5.3-569-ge3d0d6c

According to UG chapter 17.10.6, you can output the adiabatic surface temperatrue even when there is no acutual solid surface using the quantity _ADIABATIC SURFACE TEMPERATURE GAS_.

I would like to print out  the PROP parameters _EMISSIVITY_ and _HEAT TRANSFER COEFFICIENT_  as a device. My tests based on the test case _adiabatic_surface_temperature.fds_:
```
&DEVC ID='HTC-Gas', 
            QUANTITY='HEAT TRANSFER COEFFICIENT', 
            XYZ=0.52,0.52,0.45, 
            IOR=-3, 
            PROP_ID='props' /
```
When I use the parameter _ORIENTATION_, i get the error: 

> Specify orientation of DEVC using the parameter IOR.

My cases for device property "props":

## case 1
```
&PROP ID='props', 
             EMISSIVITY=0.9, 
              HEAT_TRANSFER_COEFFICIENT=10. /
```

## case 2
```
&PROP ID='props', 
             EMISSIVITY=0.9, 
              HEAT_TRANSFER_COEFFICIENT=35. /
```

## issue

![prop_quantity_output_issue](https://user-images.githubusercontent.com/7759675/30022444-a296a86a-916b-11e7-9a64-64f81431e217.png)

The measurement point _HTC-Gas_ for case 2 doesn't give the expected values (HEAT_TRANSFER_COEFFICIENT=35. W/(m^2 K)).

**Comment by sbenkorichi** [comment]
1. You should use the IOR for the HEAT_TRANSFER_COEFFICIENT quantity, as the warning is indicating.

2. You forget to set HEAT_TRANSFER_COEFFICIENT=35. On your SURF. That's why you still getting 10.

**Comment by gjaeger** [comment]
to 1:
I use the IOR. I tested the parameter _ORIENTATION_, because the quantity _ADIABATIC SURFACE TEMPERATURE GAS_ use it for a surface, facing in any direction.

to 2:
Why? Should the parameters of SURF/MATL and PROP not be independent?

**Comment by rmcdermo** [comment]
Gregor,
Thanks.  We'll either correct the bug or clarify the documentation.

**Comment by sbenkorichi** [comment]
From read.90, line 11510 , it looks like the AST GAS is not accounted for here: 

      IF (QUANTITY_INDEX<0 .AND. DV%IOR==0 .AND. (DV%STATISTICS=='null'.OR.DV%LINE>0) .AND. DV%INIT_ID=='null') THEN
         WRITE(MESSAGE,'(A,A,A)') 'ERROR: Specify orientation of DEVC ',TRIM(DV%ID),' using the parameter IOR'
         CALL SHUTDOWN(MESSAGE) ; RETURN
      ENDIF

**Comment by mcgratta** [comment]
Post a very simple input file that demonstrates the problem.

**Comment by gjaeger** [comment]
# case 1:
[AST_device_case_1.txt](https://github.com/firemodels/fds/files/1276162/AST_device_case_1.txt)

with
```
&DEVC ID='HTC-Gas', 
            QUANTITY='HEAT TRANSFER COEFFICIENT', 
            XYZ=0.52,0.52,0.44, 
            IOR=-3, 
            PROP_ID='props' /
```
and
```
&PROP ID='props', 
             EMISSIVITY=0.9, 
              HEAT_TRANSFER_COEFFICIENT=10. /
```
# case 2:
[AST_device_case_2.txt](https://github.com/firemodels/fds/files/1276161/AST_device_case_2.txt)

with
```
&DEVC ID='HTC-Gas', 
            QUANTITY='HEAT TRANSFER COEFFICIENT', 
            XYZ=0.52,0.52,0.44, 
            IOR=-3, 
            PROP_ID='props' /
```
and
```
&PROP ID='props', 
             EMISSIVITY=0.9, 
              HEAT_TRANSFER_COEFFICIENT=35. /

**Comment by gjaeger** [comment]
In both cases,  I used the quantity ID _HTC-Gas_ on line 41 for the analysis:
```
&DEVC ID='HTC-Gas', 
            QUANTITY='HEAT TRANSFER COEFFICIENT', 
            XYZ=0.52,0.52,0.44, 
            IOR=-3, 
            PROP_ID='props' /
```
![prop_quantity_output_issue](https://user-images.githubusercontent.com/7759675/30046912-6ad4cddc-920e-11e7-8fd0-872ad11e5db3.png)

**Comment by mcgratta** [comment]
The way `AST GAS` works is that it creates a Lagrangian particle that records the AST at a particular point with a particular `ORIENTATION`. FDS does this by internally creating an `INIT` line to position the particular. The `ID` of the `INIT` line is the same `ID` as the `DEVC` line that has the `QUANTITY='AST GAS'`. So do this. change your `DEVC` lines like this:
```
&DEVC ID='HTC-Gas', QUANTITY='HEAT TRANSFER COEFFICIENT', XYZ=0.52,0.52,0.44, INIT_ID='AST-Gas' /
&DEVC ID='E-Gas', QUANTITY='EMISSIVITY', XYZ=0.52,0.52,0.44, INIT_ID='AST-Gas' /
```
and tell me if that works. Not that you do not need, nor should you add, an `IOR`.

**Comment by gjaeger** [comment]
What a solution ... I would never have thought of that.

![prop_quantity_output_issue](https://user-images.githubusercontent.com/7759675/30070760-c5152a70-9264-11e7-89c8-4b974b42c62d.png)

test case: 
[AST_device_case_2.txt](https://github.com/firemodels/fds/files/1278088/AST_device_case_2.txt)

Many thanks. My question is answered. You can close the issue.

**Comment by mcgratta** [comment]
I did not either. I just noticed that I assigned the same `ID` to the `INIT` line because there seemed no better name for it.

**Comment by mcgratta** [comment]
OK, I'll close this issue. Thanks.
