### ISSUE TITLE
Problem with PRISME HVAC

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5408]
I just ran the PRISME validation cases and noticed strange behavior with the HVAC that affects all the results. This image sums it up. Has there been a major change to the HVAC stuff in the last few months?
[PRS_D3_Room_1_Pressure.pdf](https://github.com/firemodels/fds/files/1282563/PRS_D3_Room_1_Pressure.pdf)

**Comment by mcgratta** [comment]
The NIST_NRC closed door cases are also affected by this problem. Something related to leakage?

**Comment by drjfloyd** [comment]
I haven't touched HVAC since April.  The last changes to the HVAC routines were made by you in May when you added CFACE. How long has it been since the PRISME cases were run?

**Comment by mcgratta** [comment]
Dec 8, 2016

**Comment by drjfloyd** [comment]
The April change kept FDS from trying to solve for flow in a particular leakage path if there were no wall cells for leaking (e.g. someone defined LEAK_AREA on ZONE but no active surfaces with a corresponding LEAK_PATH).  I can check to see if change introduced some other issue.

**Comment by mcgratta** [comment]
OK, I vaguely remember that the original leakage functionality would assume the entire zone leaked to ambient, and these input files might have been designed based on that assumption.

**Comment by drjfloyd** [comment]
The original leakage model always required that some SURF have a LEAK_PATH for FDS to define what walls cells to apply a leakage velocity to.  Prior to using HVAC for leakage, if no LEAK_PATH was defined, then the velocity was not applied to anything.  With leakage computed by HVAC the ZONE leak area is used to define a duct and two duct node; however, if there are no wall cells to assign to the node then the HVAC model needs to be told to not solve for that duct.  NIST_NRC_01 (closed door) has a LEAK_PATH defined for the marinite surfaces, so the leak area change may not be the problem.

**Comment by mcgratta** [comment]
This short input file appears to give the correct peak pressure of about 900 Pa. Not sure why this works and the actual cases do not:
```
&HEAD CHID='NIST_NRC_test' /

&MESH IJK=50,32,16, XB=0.0,21.7,0.0,7.04,0.0,3.82 /
&TRNX IDERIV=0,CC=10.8,PC=10.8 /
&TRNX IDERIV=1,CC=10.8,PC=0.5  /

&TIME T_END=300. /

&ZONE LEAK_AREA(0)=0.058 /

&REAC FUEL='METHANE' /
&SURF ID='FIRE', HRRPUA=1000.0, COLOR='BLUE' /
&VENT XB=10,11,3,4,0,0, SURF_ID='FIRE' /

&SURF ID='WALL', DEFAULT=.TRUE., LEAK_PATH = 1,0, HEAT_TRANSFER_COEFFICIENT=0. /

&RADI RADIATION=.FALSE. /

&DEVC XYZ=10.85,0.10,0.10, QUANTITY='PRESSURE', ID='Pressure'/

&TAIL /
```

**Comment by mcgratta** [comment]
I ran versions of FDS from April 1, April 20, and May 20. It appears that the problem starts between April 20 and May 20, which means my change on May 9 might be the trouble. I'll let you know if I find otherwise.

**Comment by mcgratta** [comment]
I think I figured this out, and it does not involve HVAC. It involves cases where the default surface is leaking, like PRISME and NIST/NRC. In `divg.f90`, we need to calculate specific enthalpy at solid boundaries, and for those that leak, the gas temperature is used at the solid boundary. However, I mistakenly set the surface temperature to the gas temperature in these cases. I'm rerunning the verification cases tonight and will restart NIST/NRC and PRISME tomorrow if things work.

**Comment by mcgratta** [comment]
This case is resolved.
