### ISSUE TITLE
2 step extinction model error

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5411]
Jason,

I'm happy to work this, but wanted to give you a heads up in case you think of something.  Something has happened to the 2 step CO extinction scheme---it no longer matches the 1 step reaction results for UMD line burner.  See below.  I actually think this may have happened before MaCFP, but I did not show the coarse cases there.  In the plots, focus on the 1.25 cm results (the finer cases have not been rerun).

My first step will be to bisect the code and see if I can figure out where things when off.  If you have any thoughts, let me know.

[methane_eta_new.pdf](https://github.com/firemodels/fds/files/1282704/methane_eta_new.pdf)
[methane_eta_old.pdf](https://github.com/firemodels/fds/files/1282703/methane_eta_old.pdf)
[propane_eta_new.pdf](https://github.com/firemodels/fds/files/1282702/propane_eta_new.pdf)
[propane_eta_old.pdf](https://github.com/firemodels/fds/files/1282705/propane_eta_old.pdf)

**Comment by drjfloyd** [comment]
The old cases were 4/25 source.  If it was something in fire.f90 my guess is https://github.com/firemodels/fds/commit/704a025e2ba223e5103ae5cff2d8641ee9784242#diff-f44fc1cac74f2b00107607131ecbb726 or https://github.com/firemodels/fds/commit/5662001e4c237fc8b6d5cd42d086ccaa625c7c20#diff-f44fc1cac74f2b00107607131ecbb726

**Comment by rmcdermo** [comment]
Your guess was correct:

```
704a025e2ba223e5103ae5cff2d8641ee9784242 is the first bad commit
commit 704a025e2ba223e5103ae5cff2d8641ee9784242
Author: dr_jfloyd <jfloyd@jensenhughes.com>
Date:   Fri May 5 13:09:41 2017 -0400

    FDS Source: Fix AIT check for Extinction 5
```

**Comment by drjfloyd** [comment]
Looking at those changes again, I now think they were not correct.  Try the source I just pushed up and see if it is working again.

**Comment by drjfloyd** [comment]
Why is the 2nd (CO) step AIT set to 20 to in the UMD cases? In the testing I had done back in April I was using 610.  Any CO made at the burner surface in the low AIT INIT zone would not have any AIT restriction further up.

**Comment by rmcdermo** [comment]
Ugh!  Good catch.  I don't know.  I must have overwritten the input files.

**Comment by rmcdermo** [comment]
Making some progress.  Here are the coarse propane extinction cases, 1 step and 2 step.
![screen shot 2017-09-21 at 5 33 19 pm](https://user-images.githubusercontent.com/4418497/30719888-6176f14c-9ef3-11e7-81c6-4f11e4b50fba.png)
![screen shot 2017-09-21 at 5 33 05 pm](https://user-images.githubusercontent.com/4418497/30719890-63cca432-9ef3-11e7-9dbc-911cdbaed7f2.png)

**Comment by rmcdermo** [comment]
This appears to be working.
