### ISSUE TITLE
Smokeview only shows smoke in mesh with fire

### ISSUE THREAD

**Issue by DavidShep** [firemodels/fds#5420]
I have a 6 mesh model.  Fires are in two meshes.  Smoke stops at the mesh boundaries.  The issue occurs in smokeview in both Windows and Mac.  Temperature slices show that there is flow across the mesh boundaries. The attached file is the input file from my model.  I removed all obstructions except for the two with fires.

.

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I am running the case on a linux machine and viewing the output with my Windows Smokeview. All appears to be working OK. I'll ask someone with a Mac to try.

**Comment by mcgratta** [comment]
What versions of FDS and Smokeview are you running?

**Comment by DavidShep** [comment]
Apple.  I downloaded it fthis week.

Fire Dynamics Simulator

 Current Date     : September  7, 2017  11:41:51
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Jan 20, 2017  20:53:02

**Comment by DavidShep** [comment]
By Apple. I meant it is the apple version from the download site.

**Comment by DavidShep** [comment]
The smoke started to show up in the other meshes.  In the last couple of hours the simulation went from 40s to 60s and suddenly the smoke showed up in all of the meshes even at the beginning of the run.

Thanks for looking into this.  Have a great weekend.

**Comment by mcgratta** [comment]
Wonder if this is a buffering thing. FDS periodically forces the output buffers to flush so that Smokeview renders a fairly recently updated set of data. Different OS deal with this differently, because a Fortran program only has so much control over I/O. Maybe what happened is that after some period of time the program decided to dump the contents of its buffers. 

Or else this is just black magic.

**Comment by rmcdermo** [comment]
Dave,
If you have not already, make sure you have an unlimited stack in your .bash_profile.  On the mac it is a bit weird.  You use
```
ulimit -s 65532
```
Lots of odd behavior can show up if this is not set.
