### ISSUE TITLE
Mesh out of alignment not flagged on setup only

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5434]
Kevin,
The attach case has meshes out of alignment, but the error is not shown if I set T_END=0, that is, "setup only" mode.  I think we need to have the alignment check encompassed with setup only.  Thanks.

[McCaffrey_14_kW_45.fds.txt](https://github.com/firemodels/fds/files/1293826/McCaffrey_14_kW_45.fds.txt)

![screen shot 2017-09-11 at 3 41 44 pm](https://user-images.githubusercontent.com/4418497/30293695-696cf0d8-9708-11e7-9bac-7d4cfcdefc7b.png)

```
ERROR: MESH 126 is out of alignment with MESH 146
ERROR: MESH 127 is out of alignment with MESH 146
...
```

**Comment by mcgratta** [comment]
I think this can be done, but I'm going to wait until after the release of 6.6.0.

**Comment by sbenkorichi** [comment]
Randy, 
Can you post the original IJK and XB for this case.

**Comment by rmcdermo** [comment]
See input file above.

**Comment by sbenkorichi** [comment]
Yes, I saw it Randy, but it's already divided with the Mult, I was looking for the whole IJK with the its original domain, so I can try to extrude its meshes with the Mult line

**Comment by rmcdermo** [comment]
That's all I have.

**Comment by mcgratta** [comment]
A few things -- first, it takes a bit longer to do a setup only because there's more to do when checking mesh alignment. Second, I set `VERBOSE` to false to prevent too many messages from crowding the screen. Check to see if this is OK, then close.

**Comment by rmcdermo** [comment]
Latest code works.  If it is too expensive, in general, then an option would be to only perform this check if T_END=0 (setup only).

**Comment by mcgratta** [comment]
The check is always performed, but after lots of arrays have been allocated. So the only downside is that one has to wait a bit when doing a T_END=0 set-up. Previously, it was more or less instantaneous.
