### ISSUE TITLE
numerical instability

### ISSUE THREAD

**Issue by cantuelo71** [firemodels/fds#5478]
Hi. I'm working on a model that simulates a fire situation in a 4.5 km tunnel.
the smoke extraction is performed with two pairs of fans, one at each end of the tunnel.
fans start in 60 seconds and reach maximum performance in 150 seconds. but there are numerical instability in the second 75.

Attached below is the .fds file.

Thank you

[MODELO_V01.zip](https://github.com/firemodels/fds/files/1313300/MODELO_V01.zip)

**Comment by sbenkorichi** [comment]
Which version of FDS are you using? 6.5.3?

**Comment by cantuelo71** [comment]
Yes, 6.5.3

**Comment by sbenkorichi** [comment]
Ok someone will take a look asap

**Comment by sbenkorichi** [comment]
In the main while, it would be a lot easier to debug it if you simplify your input file. Try to reproduce the same issue with getting rid of all devices and OBST that is unnecessary, then reuploaded here. Also, I would recommend you reduce your 2nd Mesh, it's too big, which will take long time to run it `(&MESH ID='Mesh01-b-a-a-a', IJK=9247,24,20, XB=22.22,4645.72,0.0,12.0,-1.2355,8.7645/)` 
Try to reduce the 9247 to 100 or less. 
Thanks.

**Comment by cantuelo71** [comment]
Ok, I'll try to reduce the mesh.
but when reducing the mesh lose accuracy in the final result?

**Comment by sbenkorichi** [comment]
Doesn't matter, first, we're trying to debug the error you're receiving, after the error is fixed then you can test the real mesh. But, it isn't possible from our end to run a calculation for 1-2 weeks to try to reproduce the issue. It would be very easy to debug the problem when the case is simplified and demonstrate that there is a bug in the code that needs to be fixed. Hope this clarifies it.

**Comment by cantuelo71** [comment]
OK understood

**Comment by rmcdermo** [comment]
I suspect I know what Kevin would say about this case: The tunnel is four
kilometers long and it is unrealistic that there is not pressure relief
(leaks) in the system over that distance. Yet, that is how the mathematics
of FDS treats the tunnel---as a perfectly sealed tube.  Try placing an
"OPEN" vent first every kilometer, then every half kilometer, to mimic some
leakage.  See if this helps.

**Comment by cantuelo71** [comment]
the tunnel has a ventilation building at each end. each ventilation building is equipped with two fans. each building is open to the outside to expel the smoke generated by the simulated fire.

**Comment by rmcdermo** [comment]
OK, but does the tunnel go under water or something?  (I'm honestly asking to be educated here.)  Take the "Chunnel" that goes from London to Paris.  I found an article that says it has multiple main tunnels, connected by pressure ducting every 250 m.  So, it would be impossible to correctly analyze the flow in the main tunnel without also considering the pressure relief to the other.

**Comment by cantuelo71** [comment]
excuse me if I said something wrong
I am translating on my pc and may make some mistake.
This is a real road tunnel. this tunnel is 4.5km and the only entrances / exits are in the ventilation buildings and in the mouths of the tunnel. there are no others.

**Comment by rmcdermo** [comment]
You did not say anything wrong or impolite.  We are not experts on tunnel engineering, but we find it hard to imagine that the tunnels are perfectly sealed except for the inlet and exits.  The pressure relief ducting system can significantly impact the pressure fluctuations in the tunnel and hence stability of the model.

**Comment by mcgratta** [comment]
Randy -- I forget now, but is there a way to force the code to use Dirichlet BCs all around? This might be enough to lessen the effect.

**Comment by cantuelo71** [comment]
ok I understand.
well, I will try to explain in more detail how this tunnel is.
this tunnel has a length of 4.5km as I already mentioned and a slope of 2.3%. the tunnel has a vehicle circulation zone and a conduit over the circulation zone to extract and propel as necessary. this duct is filled with grid openings.

**Comment by rmcdermo** [comment]
If I wanted Dirichlet all around, I'd put OPEN bcs and then cover them with an OBST.

**Comment by cantuelo71** [comment]
I am attaching the .fds file again. I have changed the size of the meshes.
[MODELO_V01.zip](https://github.com/firemodels/fds/files/1313990/MODELO_V01.zip)

**Comment by sbenkorichi** [comment]
The Mesh hasn't changed 
`&MESH ID='Mesh01-b-a-a-a', IJK=4623,12,10, XB=22.22,4645.72,0.0,12.0,-1.2355,8.7645/`
Try to reduce that 4623 to number close to 100.

**Comment by cantuelo71** [comment]
I tried to reduce the mesh to the maximum, but if I define a division of mesh less than 1x1x1 the model shows an error and does not start the simulation. directly shows the numerical instability.

**Comment by cantuelo71** [comment]
Randy. I do not understand very well what you are talking about with mcgratta.

**Comment by rmcdermo** [comment]
Well, this may not help, but it's something to try... Along the walls of your tunnel specify VENTS with SURF_ID='OPEN'.  Then go along each wall and add an OBST along the entire wall to manually create the walls of the tunnel.  Make them at least 1 cell thick (use THICKEN=T).

What this will do is force the pressure solver to use a solution value for the pressure boundary condition (Dirichlet) as opposed to the derivative of the solution (Neumann).  In the former, there is velocity error that acts like leakage through the walls.  Maybe this will help stability.

**Comment by rmcdermo** [comment]
@cantuelo71 did you try what I suggested?  Did it help?

**Comment by Er9y714** [comment]
@rmcdermo  To understand better, do you suggest to have a model as below (cross section):
```

###########
#I-------I#
#I-------I#
#I-------I#
###########

# > OBST
- > VOID
I  > VENT with OPEN surface
```

**Comment by rmcdermo** [comment]
No.  Try something like this.
[test.fds.txt](https://github.com/firemodels/fds/files/1349347/test.fds.txt)

**Comment by Er9y714** [comment]
@rmcdermo 

Do you also imply that a velocity error is being produced when we apply an OPEN Vent to a boundary and it overlaps some part of an OBST?

**Comment by rmcdermo** [comment]
Yes.  The way the pressure solver works, the domain boundaries are either Dirichlet (specified pressure) or Neumann (specified pressure gradient).  Neumann is exact for velocity and, if possible, that is what we use on a exterior domain boundary if it is a default INERT wall for the ENTIRE surface.  However, if you add an OPEN bc ANYWHERE on that surface, then we are forced to change the ENTIRE wall to Dirichlet, which admits a velocity error.  The only perfect velocity bcs are when the entire wall is a specified normal velocity.

**Comment by sbenkorichi** [comment]
@cantuelo71 
Any progress on this?
