### ISSUE TITLE
DOI of the guides

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5508]
Tracking the DOI in the guides (http://dx.doi.org/10.6028/NIST.SP.1018-2), it leads to an error page now. I would suggest we just link it to the manual page 
https://pages.nist.gov/fds-smv/manuals.html

This way, it will be linked with the up to date release.

**Comment by mcgratta** [comment]
If we drop the -2 from the end, we link to the old version 4 guide, which has a link back (circuitously) to our most recent. I'll have to see what it takes to restore the link as is. At best, this link is going to be a redirect.
