### ISSUE TITLE
Smokeview issue: Gpu/OpenGL failed to load

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#5513]
When I try to run a .smv file (even one from the example files), I've noticed thet I don't see any smoke, just the fire. I've noticed that in the terminal that opens up when starting smokeview there are these failure messages:

Initializing OpenGL
   *** GPU smoke volume shader failed to load.
   *** GPU 3d slice shader failed to load.
   GPU shader initialization failed
OpenGL initialization completed

The only thread ? I've found online is this one, but it doesnt resolve the problem:
https://github.com/firemodels/fds/issues/4671

Does anybody know how to solve the problem?

thanks

**Comment by rmcdermo** [comment]
Does the example your are running have a SOOT_YIELD?  SOOT_YIELD is zero by default.  Hence, you will not have any smoke.

Glenn, please let us know if you think this is a bug with Smokeview (GPU).  Else, this this discussion should be in the forum, not the issue tracker.

**Comment by ghost** [comment]
thank you for your quick answer. No, the files doesn't have SOOT_YIELD, but the couch file has some lines related to SOOT (I've installed fds and smokeview only yesterday, I'm pretty ingorant). Now i can see the smoke in the couch file (don't know if it was always there and I didn't saw it cause it was very few or what else). the room file does't show any SOOT file and it doesn't show smoke , but I understand that it's how it should work. Now i'm just wondering ehat the failure messages mean.

Thanks for your help

**Comment by gforney** [comment]
The warning message is just saying that either you don't have a GPU (not likely) or smokeview was not able to use it ie not the reason smoke is not visible.  If smokeview can't load GPU shaders for any reason it just reverts to the non-gpu version for viewing smoke.  You could try loading the latest video drivers .

**Comment by ghost** [comment]
thank you for your answer. 
I don't have a dedicated GPU, I have the integrated one. I guess that the only limitation of my condition is the rendering part, is it right? i will not be able to expert the best quality animation, is it right?

**Comment by gforney** [comment]
the GPU only shows up for visualizing smoke.  It  can be faster but you should be ok for most cases

**Comment by ghost** [comment]
ok.
Thanks a lot for the help :)
