### ISSUE TITLE
HVAC leak vents appear to generate excess fuel gas

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5516]
I've been simulating fires within steel cabinets, and I've noticed that when I model a grill opening with an HVAC leak vent, the HRR goes above its specified value. This only happens when the flames go through the vent, as if somehow the HVAC leak duct is creating more fuel. Could this be possible? Here's the case, and I'll try to create a simpler version. This cases runs in a few 10s of minutes.
```
&HEAD CHID='cabinet_3ft', TITLE='400 kW burner in a 3 ft by 3 ft cabinet' /

&MESH IJK=24,24,48, XB=-0.6,0.6,-0.6,0.6,0.0,2.4 /

&TIME T_END=60. /

&MATL ID            = 'STEEL'
      SPECIFIC_HEAT = 0.465
      CONDUCTIVITY  = 54.
      DENSITY       = 7833. /

&SURF ID            = 'STEEL PLATE'
      MATL_ID       = 'STEEL'
      DEFAULT       = .TRUE.
      THICKNESS     = 0.003
      COLOR         = 'GRAY 40' /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&REAC FUEL='METHANE', SOOT_YIELD=0.001 /

&SURF ID='FIRE', HRRPUA=2222.2, COLOR='ORANGE', TMP_FRONT=300. /

&OBST XB=-0.3,0.3,-0.15,0.15,0.4,0.5, SURF_IDS='FIRE','STEEL PLATE','STEEL PLATE' /

&OBST XB=-0.45, 0.45,-0.45,-0.45,0.0,2.1 / Cabinet walls
&OBST XB=-0.45, 0.45, 0.45, 0.45,0.0,2.1 /
&OBST XB=-0.45,-0.45,-0.45, 0.45,0.0,2.1 /
&OBST XB= 0.45, 0.45,-0.45, 0.45,0.0,2.1 /
&OBST XB=-0.45, 0.45,-0.45, 0.45,2.1,2.1 / Cabinet top

&HOLE XB=-0.35, 0.35,-0.46,-0.44,0.1,0.2 / Cut out for gas line at bottom

&OBST XB=-0.35, 0.35,-0.45,-0.40,1.9,2.0 / Support blocks for leak vents
&OBST XB=-0.35, 0.35, 0.40, 0.45,1.9,2.0 /
&OBST XB=-0.45,-0.40,-0.35, 0.35,1.9,2.0 /
&OBST XB= 0.40, 0.45,-0.35, 0.35,1.9,2.0 /

&SURF ID='GRILL', MATL_ID='STEEL', THICKNESS=0.003, COLOR='GRAY 70' /

&VENT ID='FRONT EXTERIOR GRILL', XB=-0.35, 0.35,-0.45,-0.45,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='BACK EXTERIOR GRILL',  XB=-0.35, 0.35, 0.45, 0.45,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='LEFT EXTERIOR GRILL',  XB=-0.45,-0.45,-0.35, 0.35,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='RIGHT EXTERIOR GRILL', XB= 0.45, 0.45,-0.35, 0.35,1.9,2.0, SURF_ID='GRILL' /

&VENT ID='FRONT INTERIOR GRILL', XB=-0.35, 0.35,-0.40,-0.40,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='BACK INTERIOR GRILL',  XB=-0.35, 0.35, 0.40, 0.40,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='LEFT INTERIOR GRILL',  XB=-0.40,-0.40,-0.35, 0.35,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='RIGHT INTERIOR GRILL', XB= 0.40, 0.40,-0.35, 0.35,1.9,2.0, SURF_ID='GRILL' /

&HVAC ID='FRONT GRILL LEAK', TYPE_ID='LEAK', VENT_ID='FRONT INTERIOR GRILL', VENT2_ID='FRONT EXTERIOR GRILL', AREA=0.02 /
&HVAC ID='BACK GRILL LEAK',  TYPE_ID='LEAK', VENT_ID='BACK INTERIOR GRILL',  VENT2_ID='BACK EXTERIOR GRILL',  AREA=0.02 /
&HVAC ID='LEFT GRILL LEAK',  TYPE_ID='LEAK', VENT_ID='LEFT INTERIOR GRILL',  VENT2_ID='LEFT EXTERIOR GRILL',  AREA=0.02 /
&HVAC ID='RIGHT GRILL LEAK', TYPE_ID='LEAK', VENT_ID='RIGHT INTERIOR GRILL', VENT2_ID='RIGHT EXTERIOR GRILL', AREA=0.02 /

&SLCF PBX=0., QUANTITY='TEMPERATURE', VECTOR=.TRUE. /
&SLCF PBX=0., QUANTITY='PRESSURE' /

&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=.TRUE. /

&TAIL/
```

**Comment by drjfloyd** [comment]
I've been running cabinet cases for some NUREG-2178 follow-on work and haven't noticed any HRR issues nor I have I noticed issues with species being created spuriously at HVAC vents (leak vents use all the same logic for species as a mechanical vent and just add some extra logic for dealing with leakage enthalpy). I'll take a look.

**Comment by drjfloyd** [comment]
Something is amiss with the localized leakage.  If I change the leakage to standard ducts with a typical leakage loss, then the fire size stays OK. I'll keep digging.

**Comment by mcgratta** [comment]
Could it be something like a change in density but no change in mass fraction? The vent `SURF` is a steel plate.

**Comment by drjfloyd** [comment]
The leak outflow is consistent with the predicted duct massflow and the
species present at the inlet.  So the issue seems to be with the inflow bc.

**Comment by drjfloyd** [comment]
This should be fixed.   You need to add LEAK_ENTHALPY = .TRUE. to your input files for each leakage HVAC line.

**Comment by mcgratta** [comment]
Thanks. Isn't `LEAK_ENTHALPY=T` by default?

**Comment by drjfloyd** [comment]
We had this discussion a while back on some other issue.  The normal bulk surface leakage using ZONE and LEAK_PATH can't include a meaningful leak_enthalpy term.  So we have the choice of having localized leakage behave like bulk leakage as a default or have it behave differently. We chose to have it behave like bulk leakage. The User's Guide does indicate that this is the case.

**Comment by mcgratta** [comment]
Definitely better. But this case is still about 10% high in HRR. It is very coarse -- could this be an error in mass flux calculation for a coarse grid? BTW, this is an interesting case from a fire extinction point of view. Watch the video.
```
&HEAD CHID='cabinet_07', TITLE='Medium cabinet, Test 7' /

&MESH IJK=16,16,32, XB=4.0,5.6,1.4,3.0,0.0,3.2 /

&TIME T_END=600. /

&MATL ID            = 'STEEL'
      SPECIFIC_HEAT = 0.465
      CONDUCTIVITY  = 54.
      DENSITY       = 7833. /

&SURF ID            = 'STEEL PLATE'
      MATL_ID       = 'STEEL'
      THICKNESS     = 0.0028
      COLOR         = 'GRAY 50' /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&REAC FUEL='METHANE', SOOT_YIELD=0.001, RADIATIVE_FRACTION=0.25 /

&SURF ID='FIRE', HRRPUA=1111.1, COLOR='ORANGE', TMP_FRONT=300. /

&OBST XB= 4.60, 4.90, 2.00, 2.30,0.4,0.5, SURF_IDS='FIRE','STEEL PLATE','STEEL PLATE' /

&OBST XB= 4.50, 5.10, 1.90, 1.90,0.0,2.1, SURF_ID='STEEL PLATE' /
&OBST XB= 4.50, 5.10, 2.50, 2.50,0.0,2.1, SURF_ID='STEEL PLATE' /
&OBST XB= 4.50, 4.50, 1.90, 2.50,0.0,2.1, SURF_ID='STEEL PLATE' /
&OBST XB= 5.10, 5.10, 1.90, 2.50,0.0,2.1, SURF_ID='STEEL PLATE' /
&OBST XB= 4.50, 5.10, 1.90, 2.50,2.1,2.1, SURF_ID='STEEL PLATE' /

&HOLE XB= 5.05, 5.15, 2.00, 2.40,0.1,0.2 / lower front vent
&OBST XB= 5.00, 5.10, 2.00, 2.40,1.9,2.0 / upper front vent

&SURF ID='GRILL', MATL_ID='STEEL', THICKNESS=0.0028, COLOR='GRAY 70' /

&VENT ID='FRONT EXTERIOR GRILL', XB= 5.10, 5.10, 2.00, 2.40,1.9,2.0, SURF_ID='GRILL' /
&VENT ID='FRONT INTERIOR GRILL', XB= 5.00, 5.00, 2.00, 2.40,1.9,2.0, SURF_ID='GRILL' /

&HVAC ID='FRONT GRILL LEAK', TYPE_ID='LEAK', VENT_ID='FRONT INTERIOR GRILL', VENT2_ID='FRONT EXTERIOR GRILL', AREA=0.01, LEAK_ENTHALPY=.TRUE. /

&SLCF PBY=2.20, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=2.20, QUANTITY='TEMPERATURE', VECTOR=.TRUE. /

&TAIL/
```

**Comment by drjfloyd** [comment]
Does tightening velocity tolerance or making the walls thick help?

**Comment by mcgratta** [comment]
I'll try.

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/31030880-e6822794-a524-11e7-8fa3-c3bf67d72c1e.png)

This is the HRR of that same cabinet in a simulation with 25, 50, 100, and 200 kW.

**Comment by mcgratta** [comment]
This is the 100 kW simple test case with thick cabinet walls:
![image](https://user-images.githubusercontent.com/11333911/31032140-e9418da4-a528-11e7-8d93-8b90a847bb8d.png)
So I wonder if some fuel was penetrating the thin walls? In the case where the grill is removed, the HRR is good up to 200 kW, at which point it oscillates quite a bit. That case has no HVAC, just a hole. In reality, the cabinet had sizable gaps open up at the seams.

**Comment by mcgratta** [comment]
Tightening the velocity tolerance also helps. So this issue might not be strictly the HVAC, but also leakage through the thin cabinet walls.

**Comment by drjfloyd** [comment]
If I run the attached case (your input above with the walls thick and the domain shifted a little to make sure combustion happens at the highest hrr) and average for 100 s starting 50 s after the start of each step (to give the cabinet time to reach steady-state) I get average HRR of 25.0, 50.0, 100.3, and 201.9.  The heat release gets quite noisy at 200 kW.  

If I tighten the velocity tolerance (0,001 with 100 iterations) the average is 199.5.

I am running a case now with 2xgrid resolution and solid walls.

[cabinet_07.txt](https://github.com/firemodels/fds/files/1345481/cabinet_07.txt)

**Comment by drjfloyd** [comment]
at 2 x resolution it is 199.9.

**Comment by mcgratta** [comment]
OK, I think the HVAC is working. There are issues with under-ventilation and so on, but that's another issue.
