### ISSUE TITLE
User settable ticks

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5532]
Glenn,
Can you have a look please.
My domain is -0.5 to 0.5. Using the User settable ticks, it starts from -0.4 instead of -0.5. Is this a bug, or I'm not getting how it's used? Thanks !

[test.fds.txt](https://github.com/firemodels/fds/files/1345368/test.fds.txt)

![test_s0000](https://user-images.githubusercontent.com/20113030/31031367-3e0fec3c-a550-11e7-94b8-b3a3dff8d8be.png)

**Comment by rmcdermo** [comment]
Did you hit "q" to make sure your grid did not snap to something other than what you input?

**Comment by rmcdermo** [comment]
Wait... that should only happen with OBST...  yeah, I don't know.

**Comment by sbenkorichi** [comment]
Yeah, q doesn't have any impact, it's to do with the OBST. I think the starting value isn't set appropriately. As you can see, the number of the cells are 10, thus -0.4 should be -0.5 instead.

**Comment by sbenkorichi** [comment]
Ok, more update,
This issue occurs only when the domain in the negative coordinates, with the positive it's working well. 
![test_s0000](https://user-images.githubusercontent.com/20113030/31032359-9cb483d0-a553-11e7-9ec7-9fb957ea0943.png)
[test.fds.txt](https://github.com/firemodels/fds/files/1345434/test.fds.txt)

**Comment by gforney** [comment]
I wasn't rounding correctly when the numbers were negative.  should be fixed in smokeview posted here. thanks for the catch
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by sbenkorichi** [comment]
Perfect !
It's fixed, LOL Randy, this deserves Boris Award Bahahaha !
