### ISSUE TITLE
mesh tips

### ISSUE THREAD

**Issue by emiliofi87** [firemodels/fds#5537]
Good luck to everyone i am creating my first fds file, and i would like to know if you think there is some error in the list. because the duration of the simulation is 48 hours. do you have any advice? Also I would like to know some advice to speed up the calculation, even at mesh level. thank you

[definitivo_con_estrazione_320.txt](https://github.com/firemodels/fds/files/1347453/definitivo_con_estrazione_320.txt)

**Comment by sbenkorichi** [comment]
Ok, first of all, welcome to the community.
Things you should know.
1. Any questions, should be posted in the discussion group here : https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv

2. For any bugs, you can report here, or request for new features. 

3. Please, take a look at the group policies here: https://github.com/firemodels/fds/wiki/FDS-SMV-Group-Policies

4. Close this issue, and post your question to the Discussion group here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv

Thanks !
