### ISSUE TITLE
Minor typo in FDS user guide?

### ISSUE THREAD

**Issue by Matmat13** [firemodels/fds#5540]
Hi,

In "Measure of Turbulence resolution" :

&DEVC ..., QUANTITY='U-VELOCITY' | /
&DEVC ..., QUANTITY='U-VELOCITY', STATISTICS='MEAN' | /
&DEVC ..., QUANTITY='V-VELOCITY' | /
&DEVC ..., QUANTITY='V-VELOCITY', STATISTICS='MEAN' | /
&DEVC ..., QUANTITY='W-VELOCITY' | /
&DEVC ..., QUANTITY='V-VELOCITY', STATISTICS='MEAN' | /

I assume that **V**-VELOCITY in last DEVC should be **W**-VELOCITY instead.

best regards,

Mat

**Comment by rmcdermo** [comment]
Thanks!  This will be fixed in the next release.
