### ISSUE TITLE
Issues arising from `POINTER` attribute in `smvv.f90`

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5553]
With ifort18, I've encountered a run time fault from subroutine `RLE` in `smvv.f90` not raised when compiled with ifort17. In a nutshell, the `INTENT(OUT)` declaration for `BUFFER_OUT` in `RLE`  *deallocates* `BUFFER_OUT` on entry to `RLE`.  This raises the fault
```
forrtl: severe (408): fort: (7): Attempt to use pointer BUFFER_OUT when it is not associated with a target
```
and FDS crashes.  Changing to `INTENT(INOUT)` (or omitting; it is the default) corrects the error.

This feature of `INTENT(OUT)` appears not to be well known. See, however, [John's comment](https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/290415). From my limited understanding, you probably want to change this altogether to use `ALLOCATABLE` arrays instead of `POINTER`.

**Comment by mcgratta** [comment]
There are probably more `POINTER` issues in this routine. I will keep the issue open.

**Comment by sbenkorichi** [comment]
I've just downloaded intel 18 thinking to upgrade.

**Comment by mcgratta** [comment]
I cleaned up this routine. Waiting for smokebot and firebot to test.

**Comment by mcgratta** [comment]
This problem appears to be solved.
