### ISSUE TITLE
Droplet Injection not adhering to FLOW_RAMP

### ISSUE THREAD

**Issue by mckinn1** [firemodels/fds#5555]
I am attempting to inject fuel droplets in a model to simulate a gasoline spill fire. I tried to construct my model to be similar to the spray_burner.fds example, which worked as expected for me. The actual injection of the particles is working well and I am happy with the MLR and HRR results while the droplets are being injected into the model, but it appears that the simulated spill is not following the FLOW_RAMP that I have defined. Instead, the defined nozzle continually injects particles starting at 0 s 

The particle injection parameters that I have defined are the following and I have attached my input file:

&PART ID='gasoline droplets',
SPEC_ID = 'N-OCTANE', 
QUANTITIES(1:2)='PARTICLE DIAMETER','PARTICLE TEMPERATURE', 
DIAMETER=500.,
HORIZONTAL_VELOCITY = 0.01, 
HEAT_OF_COMBUSTION=44500., 
SAMPLING_FACTOR=10. /

&PROP ID='nozzle', 
PART_ID='gasoline droplets', 
FLOW_RATE=25.2, 
FLOW_RAMP = 'gasoline', 
PARTICLE_VELOCITY=1.0, 
SPRAY_ANGLE=0.,30. /

&RAMP ID='gasoline', T = 0., F=0.0,
&RAMP ID='gasoline', T = 2., F=1.0,
&RAMP ID='gasoline', T = 6., F=1.0,
&RAMP ID='gasoline', T = 8., F=0.0,

&DEVC ID='SPILL', XYZ=13.0,1.0,0.5, ORIENTATION = 0,0,-1, PROP_ID='nozzle', QUANTITY='TIME', SETPOINT=0.0  /

Is there something wrong with the way I have defined this or is this an issue caused by using multiple meshes and the non-standard combustion model?

Any advice or information is greatly appreciated.

Thanks,
Mark
[GAS.txt](https://github.com/firemodels/fds/files/1363334/GAS.txt)

**Comment by drjfloyd** [comment]
we'll take a look.

**Comment by sbenkorichi** [comment]
I think this is due to the ctrl you have, SETPOINT=0, so it will be switch automatically from 0, you should change this number to more reaalistic number 
&DEVC ID='SPILL', XYZ=13.0,1.0,0.5, ORIENTATION = 0,0,-1, PROP_ID='nozzle', QUANTITY='TIME', SETPOINT=0.0 /

**Comment by drjfloyd** [comment]
Salah,  that input should be fine. It is just saying to start the nozzle flow at T=0.

**Comment by sbenkorichi** [comment]
I think you're missing this: `/ `with your ramp, That's why the ramp isn't following up
&RAMP ID='gasoline', T = 0., F=0.0,
&RAMP ID='gasoline', T = 2., F=1.0,
&RAMP ID='gasoline', T = 6., F=1.0,
&RAMP ID='gasoline', T = 8., F=0.0,

**Comment by drjfloyd** [comment]
You are missing a / on your last &RAMP line for the flow rate.

**Comment by drjfloyd** [comment]
Rather on each ramp

**Comment by sbenkorichi** [comment]
Yes, it should be at the end of each line 
```
&RAMP ID='gasoline', T = 0., F=0.0, /
&RAMP ID='gasoline', T = 2., F=1.0, /
&RAMP ID='gasoline', T = 6., F=1.0, /
&RAMP ID='gasoline', T = 8., F=0.0, /
```
See if this now solves your issue.

**Comment by mckinn1** [comment]
I can't believe I missed that. 

Thanks so much,

Mark
