### ISSUE TITLE
Add description to ASSUMED_GAS_TEMPERATURE

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5578]
@rmcdermo 
Can you add more description in section 8.6 for ASSUMED_GAS_TEMPERATURE. So, users can utilize its functionality for diagnostics purposes. It is already in the code, bu lacks some descriptions.

**Comment by rmcdermo** [comment]
@mcgratta please have a look.

**Comment by sbenkorichi** [comment]
Thanks !
