### ISSUE TITLE
Temperature variations for isothermal helium plume.

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#5584]
As part of some debugging I have been doing on geom.f90, I came across this peculiar case.
See input file:
[helium_plume_3meshes.fds.txt](https://github.com/firemodels/fds/files/1391655/helium_plume_3meshes.fds.txt)
It's a helium plume case over a domain composed of three meshes. The problem is isothermal, but we see some temperature variations around interpolated boundaries.
After looking where in the history this started happening, I did a:

>> git reset --hard a3869ea

and run the case -> Temperature looks fine.
![screen shot 2017-10-17 at 11 46 17 am](https://user-images.githubusercontent.com/7450069/31675328-470e09be-b332-11e7-871b-1e0e30510f74.png)

doing a:
>> git reset —hard 82e8ba3

and running the case -> Slight temperature variations around Mesh (interpolated) boundaries.
![screen shot 2017-10-17 at 11 51 04 am](https://user-images.githubusercontent.com/7450069/31675360-66eb3842-b332-11e7-9361-dd43d6751cf0.png)

the culprit seems to be in changes we were doing on CFACE back at the beginning of the summer.

* master 82e8ba3 [behind 1319] FDS Source: More work to add CFACE to wall routines.

Kevin if you have a moment please take a look, I'm having trouble finding why we have this change in a case with no geoms.

**Comment by mcgratta** [comment]
I think that the issue here is whether `PROJECTION` is true or false. If I set it to false, I get small temperature changes even in the older versions.

**Comment by marcosvanella** [comment]
Interesting, I wonder what related to the changes in `CFACE, WC, ONE_D` et al. would be interacting with `PROJECTION`. 
The other issue with large `HEAT_TRANS_COEF` being computed on CFACEs is probably due to using the default FORCED and NATURAL convection model routines on cut-faces. I'll look more into this.
For now I'll switch to `ADIABATIC=.TRUE.` and` HEAT_TRANSFER_COEFFICIENT=0.` in the SURF line for isothermal cases.

**Comment by mcgratta** [comment]
I do not think that the changes broke anything. Before the change, `PROJECTION=T` caused zero change in temperature. But `PROJECTION=F` did cause a small change in temperature.

**Comment by marcosvanella** [comment]
Let me do a code (my fork today) to code (version a3869ea) comparison on some variables to see if something stands out. I reduced the size of the test problem to 8^3 cells.

**Comment by marcosvanella** [comment]
Hi Kevin, check pull request #5589. I rerun the case after this change and got the problem back to isothermal.
