### ISSUE TITLE
Typo in UG

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5592]
In the latest releases;

Technical guide:
As an example, the critical adiabatic flame temperature can be assumed to have a constant value of
approximately **1600** K for hydrocarbon diffusion flames, as suggested by Beyler2.
User guide:
The default value is 1427 C (**1700K**). This value represents combustion of typical hydrocarbon fuels.

The temperature value is updated in the user guide to 1700K from 1600K. Is there a reason for this update? I could not find any comment in the user guide LateX version (if there was any).
 
Thank you

**Comment by rmcdermo** [comment]
I updated the tech guide.

The default extinction model changed to use PRODUCTS CP.  This is more in line with the discussion in Beyler's chapter with T_OI (oxygen index).
