### ISSUE TITLE
Activation GLMAT Solver

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5593]
In the User guide 6.6.1 Optional pressure solver:
There are two lines that are said to enable the GLMAT solver. Only the former is listed in 19.18 PRES section. Which one is the actual and correct?
I could not check because I believe they will be available in the next release of FDS. (?)

- SOLVER=’GLMAT’
- GLMAT_SOLVER=.TRUE.

Thank you.

**Comment by marcosvanella** [comment]
Hi, thank you. It should be SOLVER='GLMAT'. We've been going back and forth with the naming of input parameters. 
I'll make the change on the guide.
