### ISSUE TITLE
Unexpected results in pressure zone breakage

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/fds#5598]
I've been having issues where adding a gap between pressure zones (as described in Section 9.3.1 of the Users' Guide) does not allow the pressures to equalise (with background pressures remaining wildly different). I've attached variations on a simple case with two compartments, one with air being injected to increase pressure and one with air being extracted. On adding a hole in the dividing wall the pressures should equalise somewhat.

In Order 1, this works as expected. However, if I reverse the order of definition of zones and meshes, the pressures do not equalise, as in Order 2. I've tested these on Windows and Linux with FDS 6.5.3.

I've attached a third variant based on Order 2 (which had the unexpected behaviour) but where the the zones are only defined up to the edge of the dividing wall. This means the zones are not defined to be touching and do not include the dividing wall obstruction in either zone, against the advice of the Users' Guide. Does anyone know if following this advice is still necessary? The results from Order2_WithGap seem to be identical to Order1.

I think for this to occur it needs both the particular arrangement of meshes and zones, as well as a particular order of definition. The remaining variant (MatchingMesh) makes the zones and meshes exactly align (within the obstruction), and doesn't result in the unexpected behaviour.

The charts below show the two different outcomes from the attached simulations.

![pressures - pressurezonetest_order1](https://user-images.githubusercontent.com/1982652/31789115-b9e10c00-b519-11e7-96f3-973e4ae65625.png)

![pressures - pressurezonetest_order2](https://user-images.githubusercontent.com/1982652/31789123-c2a87d0a-b519-11e7-9656-2897dbec5ef5.png)

These are the four input files used:

[PressureZoneTest_Order1.fds.txt](https://github.com/firemodels/fds/files/1399725/PressureZoneTest_Order1.fds.txt)
[PressureZoneTest_Order2.fds.txt](https://github.com/firemodels/fds/files/1399726/PressureZoneTest_Order2.fds.txt)
[PressureZoneTest_Order2_MatchingMesh.fds.txt](https://github.com/firemodels/fds/files/1399727/PressureZoneTest_Order2_MatchingMesh.fds.txt)
[PressureZoneTest_Order2_WithGap.fds.txt](https://github.com/firemodels/fds/files/1399728/PressureZoneTest_Order2_WithGap.fds.txt)

**Comment by drjfloyd** [comment]
We'll took a look.

**Comment by drjfloyd** [comment]
I can reproduce the error with the latest source.  

@mcgratta  , the PressureZoneTest_Order1.fds and Order2.fds are the two critical cases. In Order1, when MERGE_PRESSURE_ZONES checks the zone for the now missing wall and the gas cell have two different zone numbers and the the merge happens. In Order2, all the change that matters is the order that the meshes are defined. Now MERGE_PRESSURE_ZONE does its check and the now missing wall and gas cell have the same zone so no merge happens.  The error is somewhere in setting PRESSURE_ZONE during initialization where there is some MESH order dependence.  Any thoughts jump out?

**Comment by mcgratta** [comment]
Change 7.1 to 7.0. Each pressure zone must "see" the other mesh.

**Comment by JakeOShannessy** [comment]
That's the solution used in the third case listed above (actually moving 7.0 to 7.1). The same output can be produced by keeping each zone completely within their respective meshes (the fourth simulation).

If there's not an apparent code fix solution, what's the best way to characterise this to avoid it in the future (more generally)? Is it that by one zone spilling over into the next mesh it somehow blocks the the other zone from seeing both meshes?

**Comment by mcgratta** [comment]
Yes, that is the problem. If one zone straddles two meshes, the &ZONE XB coordinates must include both meshes. The reason for this is that we have not yet created MPI exchanges to enable the zone-determining algorithm to cross mesh boundaries.

**Comment by drjfloyd** [comment]
Thanks Kevin.   Jake, if Kevin's response has resolved your issue you can close it.

**Comment by JakeOShannessy** [comment]
I've been trying to narrow down my issue, Kevin's response hasn't quite answered my question. In both Order1 and Order2 the downstream zone straddles two meshes and the XB coordinates cross into both meshes, and I still get problems on Order2. Also in the WithGap example neither XB straddles both meshes yet it works perfectly. If it is not necessary to make pressure zones meet within an obstruction that might disappear than that would be a good solution, however, the guide recommends against that. Do you know if this is still a requirement?

From the tests I've run it seems that the zone-determining algorithm puts the zone boundary on either side of the obstruction, except in the specific example of Order2, even when the XBs of each zone have the same 'coverage' of meshes.

Here is the original Order2, as well as one with the mesh boundaries moved back to y = 5. These images show cell centred pressure zones. In both of these cases, the zones overlap with the same meshes (just to different extents). Also note that the realised zone boundary is different in the second case.

In my mind both of these cases satisfy the requirement you've stipulated. Perhaps there is something in the requirement I'm not understanding.

![pressurezonetest_order2_0020](https://user-images.githubusercontent.com/1982652/32018438-8670c4a6-b9d2-11e7-8737-55b7ddeb3935.png)


![pressurezonetest_order2_cmesh_0020](https://user-images.githubusercontent.com/1982652/32018417-76b10efe-b9d2-11e7-92de-102fdcbfc442.png)

**Comment by mcgratta** [comment]
Here's what's happening in the Order 2 case. When the door opens, the downstream mesh goes to its external boundary at y=7.0 and looks at the first cell inside the wall and sees that it is the same pressure zone and does nothing. The upstream sees that the wall is gone and checks to see if the PZ just inside the wall is different. It's not. Then it goes to the y=7.0 (mesh) boundary and again does not see any change in the PZ across the interface. The change in PZ occurs across the y=7.1 interface, but neither mesh 1 nor mesh 2 is checking there because this is not a boundary for either. It's inside in obstruction, so it's never considered a gas-solid interface. 

It would be hard to fix the logic on this, without breaking something else. This is why we suggest that when dealing with creation and removal logic, always test first.

**Comment by JakeOShannessy** [comment]
Thanks Kevin, much appreciated, that explains it perfectly. That was the information I was missing. I'll take the approach that placing pressure zone boundaries inside obstruction can result in this edge case. I'll close this as it's unlikely to be fixed, and I'm not sure exactly what advice you could put in the guide to avoid it.
