### ISSUE TITLE
UG Typo

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5621]
I believe the following section should be as below:

> §6.5.4
> To check your math, the sum of the squares of the gravity components ought to equal 9.81.
> 

> To check your math, **_the square root of_** the sum of the squares of the gravity components ought to equal 9.81.

Thank you.

**Comment by sbenkorichi** [comment]
Correct, 
Thanks !

**Comment by Er9y714** [comment]
Thanks, Salah.
