### ISSUE TITLE
Wiki : Compiling FDS with GNU,OpenmPI,MKL.

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#5633]
Salah, lets comment here on the wiki. 
Yes, switch the Modules.md markdown link I added to modules to the Modules wiki URL, as you described.

**Comment by sbenkorichi** [comment]
Yes, that's better. In the wiki your explanation looks clean and clear, rather than just plain text.

**Comment by sbenkorichi** [comment]
Marcos,
Don't forget to refer to this wiki page in the main one. Maybe you should put it under **Compiling FDS** section

**Comment by marcosvanella** [comment]
Salah, I'm done with the wiki. I installed MKL 17 and generated the figures, tested the compilation, etc. 
I added a link to this wiki from the FDS Compilation wiki (i.e. ALL Platforms link in the main one).
Take a look and if looks fine close the issue.

**Comment by sbenkorichi** [comment]
Ok looks good. I can't edit the wikis, as it require some adminship, 
Still one statement isn't clear. 
Finally source the startup file and check you are locating these executables:
Users may not understand source the startup, as also it may not be safe. It would be easy to ask them to log off and log in again for the changes to take effect.
You can also close this issue, as I can't do it myself.

**Comment by marcosvanella** [comment]
All right, closing.

**Comment by sbenkorichi** [comment]
I wasn't able to compile fds, I found that installing MKL libraries separately has effected my intel installation since they were both in the same directory. Now, since I've already downloaded intel 18. I'm just going for it.
