### ISSUE TITLE
Clean up uninitialized variables

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5634]
I ran the Gnu Fortran compiler (7.2.0) on the latest FDS source code
[warnings.txt](https://github.com/firemodels/fds/files/1423208/warnings.txt)

Timo -- please clean up `ieva.f90` and `evac.f90`

Susan -- please clean up `scrc.f90`

Marcos -- `geom.f90`

**Comment by marcosvanella** [comment]
I pushed changes in geom.f90 on pull request #5635.

**Comment by tkorhon1** [comment]
I pushed changes in ieva.f90.

Timo

**Comment by mcgratta** [comment]
Seems like we're getting a clean build except for `scrc.f90`. Susan is looking into it.

**Comment by mcgratta** [comment]
Susan -- are you having trouble with these changes, or trouble with the pull request?

**Comment by mcgratta** [comment]
Done, thanks all.
