### ISSUE TITLE
Problem with visualization of results

### ISSUE THREAD

**Issue by gsztar** [firemodels/fds#5639]
Hi All,
the results of my calculation look a little bit strange. Please look at slices of temperature and smoke density close to wall (red circle). The distance from border of temperature to wall is 2 cells. The border between two meshes is also 2 cells away from wall in direction left. This is visible on smoke visualization also. In my opinion there is a problem with exchanging of information between meshes.  We used different configuration of meshes, and a problem still exists.
Very similar problem was reported by us on 24 Oct 2016; Issue tracker #4444
How I can solve this problem? I use FDS 6.5.3 and Smokeview 6.5.5.
   
[SD1.txt](https://github.com/firemodels/fds/files/1424311/SD1.txt)

**Comment by sbenkorichi** [comment]
Thanks.
We'll take a look

**Comment by gforney** [comment]
If you haven't already, look at cell centered slice files and see if you
are seeing same problem.

**Comment by gforney** [comment]
Ignore my message. Didn't see your other posting

On Oct 28, 2017 10:49 AM, "Glenn Forney" <gforney@gmail.com> wrote:

If you haven't already, look at cell centered slice files and see if you
are seeing same problem.

**Comment by sbenkorichi** [comment]
Have you tried without specifying MPI_PROCESS ?

**Comment by gsztar** [comment]
No, not yet.

**Comment by sbenkorichi** [comment]
Not sure yet about it, but it could be due to that.
Your mesh02 (on the left) is running on different process different than Mesh05. Which might be causing this issue. I will try to see if I can reproduce the issue to understand what's going on.
Try from your end to run the case without specifying MPI_PROCESS on the mesh lines, and report if you still receive this issue.

![mesh](https://user-images.githubusercontent.com/20113030/32135791-992a1710-bbfc-11e7-95e2-a983e565eb7b.png)

&MESH ID='Mesh02-merged', IJK=45,174,13, XB=12.6,21.6,0.2,35.0,0.0,2.6, MPI_PROCESS=3,  COLOR='CYAN'/
&MESH ID='Mesh05', IJK=44,162,13, XB=21.6,30.4,0.2,32.6,0.0,2.6, MPI_PROCESS=0, COLOR='GREEN'/

**Comment by gsztar** [comment]
You are right but we will have this kind of problem when more than one procesor is needed.

**Comment by sbenkorichi** [comment]
I can't see a problem of exchange between meshes. At 3s, 
your picts are taken at 136s, it's not possible for me to leave it run it till that time as I'm working on other stuff. 
I will let my colleagues maybe to run it on their cluster.
![meshes](https://user-images.githubusercontent.com/20113030/32136233-41a87e72-bc02-11e7-8efa-43dc2040fcda.png)

**Comment by gsztar** [comment]
OK. But the problem occur close to concrete wall. 
![sd1_0136](https://user-images.githubusercontent.com/16048248/32136366-d92e738c-bc0c-11e7-925b-166014c6c784.png)

**Comment by sbenkorichi** [comment]
Ok do me a screenshot at 3s.

**Comment by gsztar** [comment]
![sd1_0003](https://user-images.githubusercontent.com/16048248/32136529-5e83ae74-bc0f-11e7-8579-056681246e51.png)

**Comment by drjfloyd** [comment]
The fds file you attached does not match the image you attached.  It is missing the rightmost portion of the geometry.  Does the file you attach replicate the problem or is it only with the entire file?

**Comment by sbenkorichi** [comment]
Even at 3s of your image, I don't see an issue of communication between the two meshes.  The black flesh appointing to the interface between the two meshes. As you can see form the picture, temperature is changes close to the wall. Even in your case at 3s, I can see it's changing. Maybe the behaviour you're talking about happens after certain time of run time --as you showed at 136s.

![sd1_0003](https://user-images.githubusercontent.com/20113030/32137187-e04a2444-bc12-11e7-9433-6fd804a2d1c5.png)


Jason,
No, it's not the full file, some mesh on the right side is missing.

**Comment by gsztar** [comment]
The attached file is part of whole problem only.

**Comment by gsztar** [comment]
It my mistake. Issue is still open.

**Comment by gsztar** [comment]
How to open again? :)

**Comment by sbenkorichi** [comment]
Get on github, and click open issue, down next to when you hit on comment. 
![reopen](https://user-images.githubusercontent.com/20113030/32137805-b93e61c4-bc1e-11e7-8ca1-f18e1f6c3851.png)

**Comment by gsztar** [comment]
Thank you!

**Comment by gsztar** [comment]
I made one test more. I moved the border between meshes to the right (3 cells). Now, border is on the wall. And results look more realistic. 
![comparison](https://user-images.githubusercontent.com/16048248/32143356-6adcd530-bca8-11e7-84f3-fdb2e7374126.png)
After more seconds of calculation the temperature in region close to wall is different than it should be.
![sd1_0576](https://user-images.githubusercontent.com/16048248/32143696-c1bfdb40-bcad-11e7-8013-89d8c925439c.png)
I found also problem with an old case, concerned with Maximum Pressure Error in my opinion
  **Time Step    1600   October 28, 2017  22:42:03**
       Step Size:    0.128E-01 s, Total Time:     114.49 s
       Pressure Iterations:      5
       Maximum Velocity Error:  0.70E-01 on Mesh   1 at (  12  59  14)
       Maximum Pressure Error:  0.15E+03 on Mesh   1 at (  27 154   5)
       ---------------------------------------------------------------
       Mesh    1
       Max CFL number:  0.93E+00 at (  12,  58,  12)
       Max divergence:  0.15E+00 at (  25, 162,   5)
       Min divergence: -0.72E-01 at (  31, 159,   7)
       Max VN number:   0.39E+00 at (  16,  56,  13)
       Total Heat Release Rate:            128.958 kW
       Radiation Loss to Boundaries:       -16.328 kW

**Time Step    2100   October 28, 2017  22:52:26**
       Step Size:    0.104E-01 s, Total Time:     120.04 s
       Pressure Iterations:      5
       Maximum Velocity Error:  0.77E-01 on Mesh   1 at (  12  59  14)
       Maximum Pressure Error:  0.26E+03 on Mesh   1 at (  27 158   5)
       ---------------------------------------------------------------
       Mesh    1
       Max CFL number:  0.87E+00 at (  13,  58,  12)
       Max divergence:  0.18E+00 at (  26, 158,   5)
       Min divergence: -0.97E-01 at (  29, 157,   7)
       Max VN number:   0.37E+00 at (   6,  51,  12)
       Total Heat Release Rate:            141.786 kW
       Radiation Loss to Boundaries:       -18.362 kW

  **Time Step   47500   October 29, 2017  13:01:05**
       Step Size:    0.972E-02 s, Total Time:     575.23 s
       Pressure Iterations:      5
       Maximum Velocity Error:  0.91E-01 on Mesh   1 at (  13  61  14)
       Maximum Pressure Error:  0.54E+02 on Mesh   1 at (  26 164   9)
       ---------------------------------------------------------------
       Mesh    1
       Max CFL number:  0.93E+00 at (   7,  57,  12)
       Max divergence:  0.34E+01 at (  36, 155,   5)
       Min divergence: -0.25E+01 at (  27, 165,   6)
       Max div. error:  0.14E-07 at (   1,  94,  13)
       Max VN number:   0.37E+00 at (   6,  66,   8)
       Total Heat Release Rate:           3249.137 kW
       Radiation Loss to Boundaries:     -1128.970 kW

Mesh 1 is a mesh with fire and exhaust ventilation shaft.  The fire vent cells are in region [xmin=32,  xmax=52; ymin=149; ymax=169, z=4]. What is going on? Why the error is so big?

**Comment by drjfloyd** [comment]
Are you referring to the pressure error? That error isn't large. 

Try running your first case with a tighter velocity tolerance and more pressure iterations and see if that helps. You may have a velocity error in the pressure solution from having a wall important to your flow field just a couple of cells away from the mesh boundary.

**Comment by gsztar** [comment]
Mr Floyd,
I didnot referring to the pressure error but my first impression was that error 260 Pa is large. The main problem is a problem in border of meshes.
Mr Floyd could you please in short way, explain me how to understand the maximum pressure error and maximum velocity error or please refer me to literature. When are the errors large?

**Comment by sbenkorichi** [comment]
@gsztar 
With the old case, can you do me a screenshot at 150s.

**Comment by gsztar** [comment]
@sbenkorichi Here you are
![sd1_0150](https://user-images.githubusercontent.com/16048248/32147559-cd09a8fa-bce9-11e7-896c-c284efc60a9d.png)

**Comment by sbenkorichi** [comment]
Thanks,
Hmm, weird, even at 150s it's not propagating towards the wall. There must be something going on. I just can't run this long case for the time being. But, Jason will take care of this.

**Comment by Er9y714** [comment]
@gsztar could you please try running .smv file after removing .info file in the directory of calculation?

**Comment by gsztar** [comment]
Unfortunately, It did not work.

**Comment by drjfloyd** [comment]
The current pressure solver solves for pressure on each MESH independently and then the solutions are stitched together. Depending on the convergence criteria given on PRES (VELOCITY_TOLERANCE and MAX_PRESSURE_ITERATION), multiple iterations might be done. In your case, having a wall running the length of the MESH that is just a couple of cells is causing difficulties for this process.  Tightening down the convergence criteria will probably help, but will cost extra time. The other option, as you have discovered, is to adjust the mesh boundaries so you don't have this gap of a couple of cells right before the wall. There is a new pressure solver in the works that should be released in 6.6.0 which might help with cases like this.  Since remeshing resolved the problem, I'd recommend just running with the new meshing scheme.
