### ISSUE TITLE
Gnu: Evacuation error: Verification/Evacuation/evac_memory_test*

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5641]
@tkorhon1 
Timo, more work for you.
Gnu compiler is complaining about the cases of evac_memory_test*. 
```
$ /home/salah/firemodels/fds/Build/mpi_gnu_linux_64/fds_mpi_gnu_linux_64 evac_memory_test0.fds 
 Mesh 1 is assigned to MPI Process 0

ERROR: Problem with OBST number1, line number75 (CHID: evac_memory_test0)
MPI process      0 has completed

STOP: FDS was improperly set-up (CHID: evac_memory_test0)

STOP: FDS was improperly set-up (CHID: evac_memory_test0)
```

Intel 17 has no issue.

**Comment by sbenkorichi** [comment]
I know why it's complaining about the &OBST, somehow gnu is not liking RGB color type you have on these OBSTs.
I've tested it RGB in other input files such as RGB=51,51,0, , it has no issue with it. Weird.

**Comment by sbenkorichi** [comment]
Alright, I think I've cornered the issue. Apparently, Gnu doesn't like floating numbers in the RGB definition, it only accepts integer numbers. If you have RGB=51.2,51,0, then it will throw an error. Why? I still don't know the real cause for this.

**Comment by mcgratta** [comment]
This is not surprising. I've seen it with other compilers.

**Comment by drjfloyd** [comment]
Intel performs an implicit INT() when reading a real number specified for an integer namelist input. This is not required by the ISO standard and GNU does not does this.  You should not use real numbers for integer inputs.

**Comment by sbenkorichi** [comment]
Interesting, thanks for the info Jason.

**Comment by tkorhon1** [comment]
https://github.com/firemodels/fds/pull/5658

Timo

**Comment by sbenkorichi** [comment]
Thanks,
Fixed !
