### ISSUE TITLE
some agents don't move

### ISSUE THREAD

**Issue by huanghai253** [firemodels/fds#5664]
I made a module has a exit，some agents don't move, others move to the exit

this is my code :
FDS+Evac version FDS 6.0.0, Evac 2.4.1.All material properties are completely fabricated.For Office Evacuation Only./
&HEAD CHID='Office3v1_Evacuation', TITLE='Office3v1_Evacuation'/ 
&TIME T_END= 100.0, DT=0.1 /

&OBST XB = -11.32574, 107.2425, -662.624, -658.8724, 0, 0.2, COLOR ='YELLOW' / Obst_1_Floor_0
&OBST XB = 88.56486, 106.6649, -657.1251, -642.2252, 0, 0.2, COLOR ='YELLOW' / Obst_2_Floor_0
&OBST XB = 88.81486, 106.6649, -637.3251, -629.3251, 0, 0.2, COLOR ='YELLOW' / Obst_3_Floor_0
&OBST XB = 99.86883, 106.6649, -629.3251, -619.5251, 0, 0.2, COLOR ='YELLOW' / Obst_4_Floor_0
&OBST XB = 62.31958, 83.41486, -637.5751, -629.7764, 0, 0.2, COLOR ='YELLOW' / Obst_5_Floor_0
&OBST XB = 62.46486, 69.31486, -629.7764, -616.9251, 0, 0.2, COLOR ='YELLOW' / Obst_6_Floor_0
&OBST XB = 69.31486, 77.06486, -624.6751, -616.9251, 0, 0.2, COLOR ='YELLOW' / Obst_7_Floor_0
&OBST XB = 61.86486, 83.66486, -657.1251, -642.2252, 0, 0.2, COLOR ='YELLOW' / Obst_8_Floor_0
&OBST XB = 35.41486, 56.96486, -656.8751, -642.4752, 0, 0.2, COLOR ='YELLOW' / Obst_9_Floor_0
&OBST XB = 8.464856, 30.01486, -656.8751, -642.2252, 0, 0.2, COLOR ='YELLOW' / Obst_10_Floor_0
&OBST XB = 8.464856, 30.01486, -637.0751, -629.3251, 0, 0.2, COLOR ='YELLOW' / Obst_11_Floor_0
&OBST XB = 21.96486, 30.01486, -629.3251, -616.6751, 0, 0.2, COLOR ='YELLOW' / Obst_12_Floor_0
&OBST XB = 15.06486, 21.96486, -624.6751, -616.6751, 0, 0.2, COLOR ='YELLOW' / Obst_13_Floor_0
&OBST XB = 35.91486, 56.96486, -637.3251, -629.7252, 0, 0.2, COLOR ='YELLOW' / Obst_14_Floor_0
&OBST XB = 35.61958, 42.61486, -629.7764, -616.9251, 0, 0.2, COLOR ='YELLOW' / Obst_15_Floor_0
&OBST XB = 42.61486, 50.36486, -624.6751, -616.9251, 0, 0.2, COLOR ='YELLOW' / Obst_16_Floor_0
&OBST XB = -14.53514, 3.564857, -657.1251, -642.2252, 0, 0.2, COLOR ='YELLOW' / Obst_17_Floor_0
&OBST XB = -14.21014, 3.564857, -637.8751, -629.5205, 0, 0.2, COLOR ='YELLOW' / Obst_18_Floor_0
&OBST XB = -14.18514, -7.360144, -629.5452, -619.2252, 0, 0.2, COLOR ='YELLOW' / Obst_19_Floor_0
&OBST XB = -14.53514, -6.810143, -606.4751, -588.1251, 0, 0.2, COLOR ='YELLOW' / Obst_20_Floor_0
&OBST XB = -6.810143, 3.314857, -595.5751, -588.1251, 0, 0.2, COLOR ='YELLOW' / Obst_21_Floor_0
&OBST XB = 8.464856, 30.01486, -596.1251, -588.1251, 0, 0.2, COLOR ='YELLOW' / Obst_22_Floor_0
&OBST XB = 22.83986, 30.01486, -608.7751, -596.1251, 0, 0.2, COLOR ='YELLOW' / Obst_23_Floor_0
&OBST XB = 15.06486, 22.83986, -608.7751, -600.7751, 0, 0.2, COLOR ='YELLOW' / Obst_24_Floor_0
&OBST XB = 35.41486, 42.78986, -606.2251, -587.5751, 0, 0.2, COLOR ='YELLOW' / Obst_25_Floor_0
&OBST XB = 42.78986, 56.96486, -596.1251, -587.5751, 0, 0.2, COLOR ='YELLOW' / Obst_26_Floor_0
&OBST XB = 61.31486, 77.06486, -608.7751, -600.7751, 0, 0.2, COLOR ='YELLOW' / Obst_27_Floor_0
&OBST XB = 61.31486, 69.31486, -600.7751, -588.1251, 0, 0.2, COLOR ='YELLOW' / Obst_28_Floor_0
&OBST XB = 69.31486, 83.66486, -596.1251, -588.1251, 0, 0.2, COLOR ='YELLOW' / Obst_29_Floor_0
&OBST XB = 99.46486, 106.6649, -606.4751, -587.8251, 0, 0.2, COLOR ='YELLOW' / Obst_30_Floor_0
&OBST XB = 88.56486, 99.46486, -596.1251, -587.8251, 0, 0.2, COLOR ='YELLOW' / Obst_31_Floor_0
&OBST XB = 88.56486, 106.6649, -583.2251, -568.5751, 0, 0.2, COLOR ='YELLOW' / Obst_32_Floor_0
&OBST XB = 61.86486, 83.41486, -582.9751, -568.5751, 0, 0.2, COLOR ='YELLOW' / Obst_33_Floor_0
&OBST XB = 34.71486, 56.96486, -583.7251, -575.2251, 0, 0.2, COLOR ='YELLOW' / Obst_34_Floor_0
&OBST XB = 34.71486, 43.13986, -575.2251, -572.0251, 0, 0.2, COLOR ='YELLOW' / Obst_35_Floor_0
&OBST XB = 8.464856, 30.24402, -583.2251, -568.5751, 0, 0.2, COLOR ='YELLOW' / Obst_36_Floor_0
&OBST XB = -14.53514, 3.564857, -583.2251, -568.5751, 0, 0.2, COLOR ='YELLOW' / Obst_37_Floor_0
&OBST XB = 9.348453, 30.89845, -552.2501, -537.8502, 0, 0.2, COLOR ='YELLOW' / Obst_38_Floor_0
&OBST XB = -13.65155, 4.448453, -552.2501, -537.6002, 0, 0.2, COLOR ='YELLOW' / Obst_39_Floor_0
&OBST XB = 10.16945, 30.89845, -532.7001, -524.3051, 0, 0.2, COLOR ='YELLOW' / Obst_40_Floor_0
&OBST XB = 22.59845, 30.89845, -524.3051, -512.3001, 0, 0.2, COLOR ='YELLOW' / Obst_41_Floor_0
&OBST XB = 15.94845, 22.59845, -520.0501, -512.3001, 0, 0.2, COLOR ='YELLOW' / Obst_42_Floor_0
&OBST XB = -13.65155, 4.448453, -533.2501, -524.1696, 0, 0.2, COLOR ='YELLOW' / Obst_43_Floor_0
&OBST XB = -13.65155, -6.476547, -524.1696, -514.6002, 0, 0.2, COLOR ='YELLOW' / Obst_44_Floor_0
&OBST XB = 15.94845, 30.89845, -504.1501, -496.1501, 0, 0.2, COLOR ='YELLOW' / Obst_45_Floor_0
&OBST XB = 22.54845, 30.89845, -496.1501, -483.2501, 0, 0.2, COLOR ='YELLOW' / Obst_46_Floor_0
&OBST XB = 9.598453, 22.54845, -491.5001, -483.2501, 0, 0.2, COLOR ='YELLOW' / Obst_47_Floor_0
&OBST XB = -13.65155, -5.926547, -501.8501, -483.5001, 0, 0.2, COLOR ='YELLOW' / Obst_48_Floor_0
&OBST XB = -5.926547, 4.448453, -491.5001, -483.5001, 0, 0.2, COLOR ='YELLOW' / Obst_49_Floor_0
&OBST XB = 61.81486, 83.36485, -552.5001, -537.8502, 0, 0.2, COLOR ='YELLOW' / Obst_50_Floor_0
&OBST XB = 88.26485, 106.3649, -552.5001, -537.8502, 0, 0.2, COLOR ='YELLOW' / Obst_51_Floor_0
&OBST XB = 88.26485, 106.3649, -532.7001, -524.7001, 0, 0.2, COLOR ='YELLOW' / Obst_52_Floor_0
&OBST XB = 99.18986, 106.3649, -524.7001, -514.6002, 0, 0.2, COLOR ='YELLOW' / Obst_53_Floor_0
&OBST XB = 62.01958, 83.36485, -532.7001, -524.7196, 0, 0.2, COLOR ='YELLOW' / Obst_54_Floor_0
&OBST XB = 62.01958, 69.06786, -524.7196, -512.3001, 0, 0.2, COLOR ='YELLOW' / Obst_55_Floor_0
&OBST XB = 69.06786, 73.21612, -520.0501, -512.3001, 0, 0.2, COLOR ='YELLOW' / Obst_56_Floor_0
&OBST XB = 61.81486, 76.76485, -503.9001, -496.1501, 0, 0.2, COLOR ='YELLOW' / Obst_57_Floor_0
&OBST XB = 61.81486, 69.86485, -496.1501, -483.5001, 0, 0.2, COLOR ='YELLOW' / Obst_58_Floor_0
&OBST XB = 69.86485, 83.36485, -491.5001, -483.5001, 0, 0.2, COLOR ='YELLOW' / Obst_59_Floor_0
&OBST XB = 88.26485, 106.3649, -491.5001, -483.5001, 0, 0.2, COLOR ='YELLOW' / Obst_60_Floor_0
&OBST XB = 98.63985, 106.3649, -501.8501, -491.5001, 0, 0.2, COLOR ='YELLOW' / Obst_61_Floor_0
&OBST XB = 61.81486, 83.36485, -478.6001, -463.9501, 0, 0.2, COLOR ='YELLOW' / Obst_62_Floor_0
&OBST XB = 88.26485, 106.3649, -478.6001, -463.9501, 0, 0.2, COLOR ='YELLOW' / Obst_63_Floor_0
&OBST XB = 9.348453, 30.89845, -478.6001, -463.9501, 0, 0.2, COLOR ='YELLOW' / Obst_64_Floor_0
&OBST XB = -13.65155, 4.448453, -478.6001, -463.9501, 0, 0.2, COLOR ='YELLOW' / Obst_65_Floor_0
&OBST XB = 88.01485, 103.4149, -455.8001, -434.2501, 0, 0.2, COLOR ='YELLOW' / Obst_66_Floor_0
&OBST XB = 75.76785, 83.91486, -456.0501, -434.0001, 0, 0.2, COLOR ='YELLOW' / Obst_67_Floor_0
&OBST XB = 65.26485, 75.76785, -456.0501, -447.8251, 0, 0.2, COLOR ='YELLOW' / Obst_68_Floor_0
&OBST XB = 16.79845, 27.44845, -456.3501, -447.8251, 0, 0.2, COLOR ='YELLOW' / Obst_69_Floor_0
&OBST XB = 8.798453, 16.79845, -456.3501, -434.0001, 0, 0.2, COLOR ='YELLOW' / Obst_70_Floor_0
&OBST XB = -10.70155, 4.998453, -455.8001, -434.2501, 0, 0.2, COLOR ='YELLOW' / Obst_71_Floor_0
&OBST XB = -1.940544, 11.05946, -503.7115, -497.1615, 0, 0.2, COLOR ='GREEN' / Obst_72_Floor_0
&OBST XB = 82.64207, 95.64207, -503.8939, -497.3439, 0, 0.2, COLOR ='GREEN' / Obst_73_Floor_0
&OBST XB = -2.829179, 10.17082, -608.1909, -601.6409, 0, 0.2, COLOR ='GREEN' / Obst_74_Floor_0
&OBST XB = 81.87222, 94.87222, -608.4746, -601.9246, 0, 0.2, COLOR ='GREEN' / Obst_75_Floor_0
&OBST XB = 41.59845, 51.11486, -500.5001, -498.5001, 0, 0.2, COLOR ='GREEN' / Obst_76_Floor_0
&OBST XB = 41.59845, 51.11486, -479.3001, -458.2501, 0, 0.2, COLOR ='GREEN' / Obst_77_Floor_0
&OBST XB = -11.32574, 107.2425, -662.624, -658.8724, 0, 0.2, COLOR ='BLUE' / Obst_78_Floor_0

&OBST XB = 73.21612, 73.26785, -520.0501, -512.3001, 0, 0.2, COLOR ='RED' / Obst_80_Floor_0
&OBST XB = 73.26785, 75.86485, -520.0501, -519.9976, 0, 0.2, COLOR ='RED' / Obst_81_Floor_0
&OBST XB = 76.76485, 76.81659, -520.0501, -512.3001, 0, 0.2, COLOR ='RED' / Obst_82_Floor_0
&OBST XB = 73.21612, 76.81659, -512.3001, -512.2476, 0, 0.2, COLOR ='RED' / Obst_83_Floor_0

DOOR XB = 49.1902, 49.93, -516.704, -515.8427, 0, 2, COLOR ='YELLOW' / Obst_840_Floor_0
&HOLE XB = 45.9, 61.7,-427.7445, -427.238, 0, 3, COLOR ='RED', EVACUATION=.TRUE. / HOLE_1_Floor_0
&EXIT XB = 45.9, 61.7, -427.74445, -427.74445,0,2, COLOR ='RED', IOR = +2, ID ='EXIT_1_Floor_0' / EXIT_1_Floor_0

&MESH IJK =1240,1240,1, XB = -20.30706, 112.9649, -666.7501, -427.238, 0, 3,EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0,ID = 'MESH_1_Floor_0' / MESH_1_Floor_0

&EVAC ID = '0EVAC_P05', NUMBER_INITIAL_PERSONS = 300,XB = -20.30706, 112.9649, -666.7501, -427.238, 0, 3, MESH_ID = 'MESH_1_Floor_0',AVATAR_COLOR = 'RED',PERS_ID = 'Adult' / 

&PERS ID='Adult',FYI='Male+Female diameter and velocity', DEFAULT_PROPERTIES='Adult', PRE_EVAC_DIST=1,PRE_LOW=1.0,PRE_HIGH=2.0,DET_EVAC_DIST=0, DET_MEAN=0.0, TDET_SMOKE_DENS=0.1 , HUMAN_SMOKE_HEIGHT=1.60, DENS_INIT= 4.0, NOT_RANDOM=.TRUE., OUTPUT_SPEED=.TRUE.,OUTPUT_FED=.TRUE., COLOR_METHOD = 0 //
&Tail/

thank you very much!!!

**Comment by huanghai253** [comment]
Whether it needs to be created a lot of mesh、door、evac mesh？？  H E L P !!

**Comment by sbenkorichi** [comment]
I've run it with the latest version, I had no problems. I had to reduce the nbr of cells in order to run it on my machine.
1. Use the latest release of FDS.
2. Your agents needs more time to evacuate, increase 100s to at least 400s.
3. Here is the case that I run.
[Office3v1_Evacuation .fds.txt](https://github.com/firemodels/fds/files/1437372/Office3v1_Evacuation.fds.txt)

3. This question should be asked in the discussion group first as it doesn't demonstrate any bug in the code.
4. Close this issue if this has solved it.

**Comment by tkorhon1** [comment]
Hi!

 MESH IJK =1240,1240,1, XB = -20.30706, 112.9649, -666.7501, -427.238, 0, 3,
&MESH IJK =335,600,1, XB = -20.30706, 112.9649, -666.7501, -427.238, 0, 3,
      EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0,
      ID = 'MESH_1_Floor_0' / MESH_1_Floor_0

I did not find this problem, the agents were moving nicely. Now I have your
original mesh running, but it takes some time in the computer. You have
quite many grid points (1240*1240 is over  one million). Your building is
quite large, how fine mesh do you need? Typically, you do not need 10 cm
resolution. Something like 25cm, 30cm, 40cm, 50cm are nice resolutions.
You could modify your XB so that the number are "raund numbers, like:

XB = -20.30706, 112.9649, -666.7501, -427.238, ==>
XB = -20.25, 113.0, -666.75, -427.25,

And, use, for example 0.25cm mesh spacing

TimoK

**Comment by huanghai253** [comment]
thank you very much!!!!!
