### ISSUE TITLE
GLMAT error (-2)

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5668]
As mentioned in the [thread](https://groups.google.com/forum/#!topic/fds-smv/Af052--IP8E), I receive an error when trying to run the attached file. 
It is running on Win 10, with Intel cpu. 

Thank you for checking.

Note: As much as it was requested to receive it wholly, I could not leave details because it belongs to an ongoing project. While I was removing objects, I saw it was still giving error, therefore I left only meshes, which still gives the same error.

[GLMAT.fds.txt](https://github.com/firemodels/fds/files/1440901/GLMAT.fds.txt)

**Comment by rmcdermo** [comment]
@marcosvanella Your first customer!

**Comment by marcosvanella** [comment]
Hi, I'll take a look. 
So you run this on a windows cluster? Also, are you using the bundle or you compile your code?
Thank you.

**Comment by Er9y714** [comment]
I run this on a single computer (Intel E5 2670x2). I do not compile, it is the exe that I downloaded from website.

**Comment by marcosvanella** [comment]
The error (-2) for the cluster sparse solver means there is not enough memory on the system to store the LU decomposition matrix. This solver is very memory intensive. 
Besides that, I see you are using two different levels of refinement (two different cell sizes on the same domain) in your problem (in the tunnel entrance?), which currently GLMAT does not support. Check the write up in the new User Guide that comes with the bundle (pg. 51).

I'll make more explicit the memory problem on the write out for GLMAT, and we'll include a check on the single refinement, non overlapping meshes requirement for this solver option. That will come up on the next minor release.

For the time being, I'd use the default solver on this case.

**Comment by Er9y714** [comment]
The system has 64GByte memory, during the initialization of calculation the level of memory did not come close to the max. 
There are 4 different mesh sizes in the domain.  I guess this is the main issue here. 
I do not see any overlapping, maybe I miss it. Could you give the location so I can check?

Thank you.

**Comment by marcosvanella** [comment]
Interesting, it's possible the MKL solver during its symbolic factorization does a count of memory required before hand and throws this error. I'll have to look at that. You have a mesh with around 4.8 million cells which is probably large for your 64GB. This number defines the size of the pressure discretization matrix. 
I haven't seen overlapping meshes in your model, just two different cell sizes at one of the entrances of the tunnel. I haven't looked at it thoroughly though.

**Comment by sbenkorichi** [comment]
Marcos,
Some update for you. I've tried to use my new so called cluster for this case. I have : 
comp1: 8 cores, 32GB
comp2: 2cpus each has 2 cores. 8GB 
Running the case as is without specifying the solver, it runs. When I use the solver I get this error: 
[glmat.fds.txt](https://github.com/firemodels/fds/files/1454587/glmat.fds.txt)
```
$ mpiexec -np 12 -f machinefile fds GLMAT.fds 
 Mesh 1 is assigned to MPI Process 0
 Mesh 2 is assigned to MPI Process 0
 Mesh 3 is assigned to MPI Process 0
 Mesh 4 is assigned to MPI Process 0
 Mesh 5 is assigned to MPI Process 1
 Mesh 6 is assigned to MPI Process 1
 Mesh 7 is assigned to MPI Process 1
 Mesh 8 is assigned to MPI Process 1
 Mesh 9 is assigned to MPI Process 2
 Mesh 10 is assigned to MPI Process 2
 Mesh 11 is assigned to MPI Process 2
 Mesh 12 is assigned to MPI Process 2
 Mesh 13 is assigned to MPI Process 2
 Mesh 14 is assigned to MPI Process 3
 Mesh 15 is assigned to MPI Process 3
 Mesh 16 is assigned to MPI Process 3
 Mesh 17 is assigned to MPI Process 3
 Mesh 18 is assigned to MPI Process 4
 Mesh 19 is assigned to MPI Process 4
 Mesh 20 is assigned to MPI Process 4
 Mesh 21 is assigned to MPI Process 4
 Mesh 22 is assigned to MPI Process 4
 Mesh 23 is assigned to MPI Process 5
 Mesh 24 is assigned to MPI Process 5
 Mesh 25 is assigned to MPI Process 5
 Mesh 26 is assigned to MPI Process 5
 Mesh 27 is assigned to MPI Process 5
 Mesh 28 is assigned to MPI Process 6
 Mesh 29 is assigned to MPI Process 6
 Mesh 30 is assigned to MPI Process 6
 Mesh 31 is assigned to MPI Process 6
 Mesh 32 is assigned to MPI Process 6
 Mesh 33 is assigned to MPI Process 7
 Mesh 34 is assigned to MPI Process 7
 Mesh 35 is assigned to MPI Process 7
 Mesh 36 is assigned to MPI Process 7
 Mesh 37 is assigned to MPI Process 7
 Mesh 38 is assigned to MPI Process 8
 Mesh 39 is assigned to MPI Process 9
 Mesh 40 is assigned to MPI Process 10
 Mesh 41 is assigned to MPI Process 11
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4
  
 Using GLMAT as pressure solver. List of H unknown numbers per proc:
 MYID=       0, NUNKH_LOCAL=  223968
 MYID=       1, NUNKH_LOCAL=  283232
 MYID=       2, NUNKH_LOCAL=  799584
 MYID=       3, NUNKH_LOCAL=  639744
 MYID=       4, NUNKH_LOCAL=  789888
 MYID=       5, NUNKH_LOCAL=  341730
 MYID=       6, NUNKH_LOCAL=  783360
 MYID=       8, NUNKH_LOCAL=   50592
 MYID=       7, NUNKH_LOCAL=  775680
 MYID=       9, NUNKH_LOCAL=   43750
 MYID=      10, NUNKH_LOCAL=   45792
 MYID=      11, NUNKH_LOCAL=   37536
rank = 5, revents = 25, state = 8
Assertion failed in file ../../src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c at line 2988: (it_plfd->revents & POLLERR) == 0
internal ABORT - process 3
```
The reason for this is somehow at comp2 mpi stops and cpus gets to 0 % , then comp1 keeps at 99 -100% and then it breaks and send this error.

**Comment by marcosvanella** [comment]
Is this the same mesh as the original one? 
This mesh uses meshes at different refinement levels, which cannot be handled by the GLMAT solver. I have left the case open to remind me to add a check at setup time for this, as well as the case of having separate domains (also unsupported at this time). 
I will close it when I've added these.

**Comment by sbenkorichi** [comment]
Ok 
Sounds good plan.

**Comment by Er9y714** [comment]
Is GLMAT going to be available near future for models that have different mesh refinements ?

**Comment by rmcdermo** [comment]
No. There is a different pressure solver in the works for this situation.  So, in the future, yes, but not the "near" future.

**Comment by marcosvanella** [comment]
Closing, added tests for unsupported meshes on PR #5705.
