### ISSUE TITLE
Ghost BNDF in SMV

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5679]
I experience a visual problem in the attached file. It was a tunnel, I believe these two meshes (in fds file) in combination cause this problem. You can see a boundary surface is happening away from the surface (on both +x and -x side). Could you please take a look at it? Thank you.

Tried with:
SMV 6.6.0
FDS 6.5.3 and 6.6.0 

[BNDF.fds.txt](https://github.com/firemodels/fds/files/1449752/BNDF.fds.txt)

![image](https://user-images.githubusercontent.com/26166281/32491171-01ea8684-c3b6-11e7-848b-f01a466c2d6d.png)

**Comment by rmcdermo** [comment]
Thanks.  We'll have a look.

**Comment by gforney** [comment]
this should be fixed in smokeview posted here.  report back if it fixes your problem.  thanks.
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
Thank you, it is solved!
