### ISSUE TITLE
BNDF not displayed on thin OBST at MESH boundary

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5680]
In the attached case, the first OBST is at a MESH boundary, the second is not.  Both are set to a SURF temperature of 200 C.  When loading BNDF for All Meshes only the second is displayed.

[test.fds.txt](https://github.com/firemodels/fds/files/1449764/test.fds.txt)

![test_0080](https://user-images.githubusercontent.com/4418497/32491363-6cd58660-c384-11e7-99c6-792884e40823.png)

**Comment by gforney** [comment]
don't think smokview sees any data for the first OBST

**Comment by rmcdermo** [comment]
Right.  I'm working on it.

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by mcgratta** [comment]
Voila! It works. Thanks.
