### ISSUE TITLE
Orientation in SMV when clipped with scaled model

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5681]
I m having problems navigating while the model is clipped and model is centered. It occurs when scaling is in use. It acts as if the center of the orientation is shifted away (or center is still fixed but the model does not keep the same center when scaled). Could you please take a look?
Thank you. 

SMV 6.6.0

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if it is still not working . thanks.
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if it is still not working . thanks.
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if it is still not working . thanks.
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if it works for your case. thanks.
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
Thanks Glenn. It is solved!
