### ISSUE TITLE
Mesh coloring after job restart

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5682]
Would it possible to add this option.
Suppose you run a job, in the middle of the job run, you decided to stop it, color the meshes then restart the job at the stopped point. However, the meshes are still black. Is there anyway to this added into the code?

Cheers,
Salah

**Comment by rmcdermo** [comment]
I suspect you could hack the smv file for this.

**Comment by sbenkorichi** [comment]
Hmm, interesting, 
I didn't think of this. Let me check

**Comment by sbenkorichi** [comment]
I doubt it,
I couldn't find the meshes color defined there as RGB or by names.

**Comment by rmcdermo** [comment]
Run a simple case in which you add mesh names and colors.  Look at the smv file to see where these end up.  Apply the same format and syntax to your other case of interest.

**Comment by sbenkorichi** [comment]
Lemme try it

**Comment by sbenkorichi** [comment]
Ok, it is possible, I still didn't figure out at which specific function this is done, but after copying the smv infos, I could get it colored, I will report later in the day. I just need to finish some of the installations and setup of my machine after I broke some stuff yesterday.

**Comment by sbenkorichi** [comment]
Got it, it's controlled in the last three values of the PDIM. 

 Would it be possible to make smv update these values when we do a restart? 
If it's no, then please just close this issue.

**Comment by rmcdermo** [comment]
Anything is possible.  But this is not a high priority.  Keep it in mind for when things settle down.

**Comment by sbenkorichi** [comment]
Ok !

**Comment by sbenkorichi** [comment]
Well, we definitely need to get back to this later on. 
After changing the smokeview file, I got it working, then when I closed it, and tried to open it now. I no longer able to do so, 
```
initializing Glut
complete
initializing OpenGL
complete

processing object file: /home/salah/FDS/FDS6/bin/objects.svo
Segmentation fault
```

It would be better to let smokeview make the update itself instead of doing it manually.

**Comment by rmcdermo** [comment]
Salah,
This would be an FDS change, since FDS writes the .smv file.  For now, I'd like you to think about just coloring the meshes correctly from the start.

**Comment by sbenkorichi** [comment]
Yeah, but I've just missed 500s long running case. I wonder how I can fix this now. I will try to set the setting to the default as it was before and see if it helps.

**Comment by sbenkorichi** [comment]
Nope setting it back didn't help. Looks like after it updated after few time steps, it got messed up.

**Comment by sbenkorichi** [comment]
Wow, looks like I'm lucky, after few times of trying I got it working and set it to the default display. phew !
