### ISSUE TITLE
Color DIMGRAY isn't defined in the read file

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5683]
In table 7.1, we have these range of colors, I was trying to use DIMGRAY, but looks like it's not defined in the read file as the other colors. Although, its RGB can be used.
Can someone take a look. Thanks !

**Comment by Er9y714** [comment]
https://github.com/firemodels/fds/blob/48df14d7d3df0eb3c8eb496a0acd1d21a23358b9/Source/data.f90#L1513

I guess it should be with a blank ; DIM GRAY

**Comment by sbenkorichi** [comment]
Nice spot.
I will make the correction. Thanks !

**Comment by sbenkorichi** [comment]
Done !
