### ISSUE TITLE
Feature request: Use Devices with Mult function

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5685]
We're getting users interested in making devices specified with mult function. 
I myself don't see a big priority in this or benefit, as Points can do the job pretty much. However, adding it might help users who are interested in using it.

**Comment by Er9y714** [comment]
I guess this is a wrong link

**Comment by sbenkorichi** [comment]
Dummy me, I've copied it from my gmail account.

**Comment by mcgratta** [comment]
One can already specify a linear array of devices using `POINTS` and `TIME_HISTORY=.TRUE.`  I would rather not add `MULT` to an already complicated construct.

**Comment by sbenkorichi** [comment]
Looks like we agree here.
