### ISSUE TITLE
Problem with STATISTICS='MEAN' in CHID_DEVC file 

### ISSUE THREAD

**Issue by elmadrab** [firemodels/fds#5689]
Hello guys,

Hope you're doing well.

I faced a problem with a device that use STATISTICS='MEAN' when I run my case with T_BEGIN = -300 (negative).

FDS start writing the outputs from t=0s not t=-300s.

I'm using FDS 6.5.3.
[8MW_DP_8-7_devc.xlsx](https://github.com/firemodels/fds/files/1456932/8MW_DP_8-7_devc.xlsx)
[8MW_tunnel.txt](https://github.com/firemodels/fds/files/1456943/8MW_tunnel.txt)

Thank you for your support.

**Comment by sbenkorichi** [comment]
@elmadrab 
Did you try with FDS 6.6?
download the latest release and see if it fxes your issue.
Report back.

**Comment by sbenkorichi** [comment]
I've tested FDS6.6 and it's starting from -300s.
Upgrade and let me know.

**Comment by sbenkorichi** [comment]
Now, I see your issue,
Values after p Column aren't dumped until t=0s.
We'll take a look.

**Comment by sbenkorichi** [comment]
Running it with FDS6.6, the quantities are dumped with -300s.
See the example in the file.
[8MW_DP_8-7_devc.xlsx](https://github.com/firemodels/fds/files/1457541/8MW_DP_8-7_devc.xlsx)

**Comment by sbenkorichi** [comment]
@elmadrab 
Well, any update on this? Have you tried using FDS6.6
We encourage users to be responsive once they submit an issue.

**Comment by elmadrab** [comment]
Sorry Salah,

I didn't have time to tested it.

I'll try it tomorrow and let you know.

Thank you.



Le 13 nov. 2017 6:36 PM, "Salah Benkorichi" <notifications@github.com> a
écrit :

**Comment by sbenkorichi** [comment]
Ok,
Thanks !

**Comment by sbenkorichi** [comment]
Well, looks like we have 22 days so far. Hope you didn't forget.

**Comment by elmadrab** [comment]
Hello,

I'm really sorry for the delay, I have been busy for a while.

I run an other case with T_BEGIN=-300, with the FDS 6.5.3 and 6.6.0, and got the same problem.

**Comment by sbenkorichi** [comment]
Upload the original case to check it. What you have uploaded, it works fine.

**Comment by elmadrab** [comment]
[DEF_confort.txt](https://github.com/firemodels/fds/files/1561993/DEF_confort.txt)

Thank you Salah !

**Comment by elmadrab** [comment]
PS : When I have less then 15 devices it's work fine, but starting from the 16th device the quantities are not dumped from -300 but from 0.

**Comment by sbenkorichi** [comment]
Well, again it's working from my end. You have 18 Devices, all of them are being dumped from -300 s.

The file you uploaded isn't the same case as you shared in the first post. I saw you had pressure devices and velocity, but not in this last file. 

Also, I want to know what's your operating system you're using. Is it Windows or which one? 
Also, I want to know which version, is it 32bit or 64bit. 
Lastly, try to run the case in a new folder. --copy the input file there and run fds and see if it helps.

[DEF_confort_devc.xlsx](https://github.com/firemodels/fds/files/1562294/DEF_confort_devc.xlsx)

**Comment by elmadrab** [comment]
I'm run it on Windowds 7 and 10. both on 64 bit.

**Comment by sbenkorichi** [comment]
I'm using Linux.
@mcgratta  could you please try it on your Windows system. Thanks

**Comment by sbenkorichi** [comment]
@elmadrab 
Try running this and see if it still giving you the same issue.  I've just simplified the case and run it under windows 8. It's working with FDS 6.6.0
[8MW_tunnel.fds.txt](https://github.com/firemodels/fds/files/1563568/8MW_tunnel.fds.txt)
[8MW_DP_8-7_devc.xlsx](https://github.com/firemodels/fds/files/1563569/8MW_DP_8-7_devc.xlsx)
