### ISSUE TITLE
Invisible OBST's outline is visible when OUTLINE=.TRUE.

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5690]
I noticed the outlines are visible of hidden OBST when OUTLINE is .TRUE. 
I think invisible OBST should be completely hidden. Because there is an option to show outlines of OBST in SMV already. 

Thank you.
 
&OBST ID='walls', XB=..., COLOR='INVISIBLE', OUTLINE=.TRUE./

**Comment by gforney** [comment]
You've specified two mutually exclusive options on your OBST line.  In this ambiguous situation, Smokeview breaks the tie by displaying as outlines.  If you don't want Smokeview to display OBSTs as outlines then remove the OUTLINE=.TRUE. option from your OBST line
