### ISSUE TITLE
Diffusion flame

### ISSUE THREAD

**Issue by maurizioasaro** [firemodels/fds#5691]
Do anyone know how to specify a diffusion flame by the codes?
because if i don't specify for default i have pre mixed flame.
thank you in advance

**Comment by Er9y714** [comment]
You should ask questions in discussion forum. This page is for issues and bugs. 
As for diffusion flame, you can find examples in Verification guide. Search "diffusion flame" and you will see for ex: §3.8.5, §7.1.3.

**Comment by maurizioasaro** [comment]
thank you , I just registered and i dont understand where is it, can you send the link for this discussion forum?
thank you

**Comment by sbenkorichi** [comment]
Questions are asked here: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv

Take a look at effective posting. 
https://github.com/firemodels/fds/wiki/Effective-Posting
Also the policy of the group: 
https://github.com/firemodels/fds/wiki/FDS-SMV-Group-Policies

Reporting bugs or asking for new features done here on the github platform.
Check in the Fire files that comes in the examples of FDS, see input files as tmp_lower_limit* for diffusion flame.
This issue should be closed.

**Comment by Er9y714** [comment]
Forum:
https://groups.google.com/forum/#!forum/fds-smv

Verification guide:
https://drive.google.com/drive/folders/0B_wB1pJL2bFQUlJwMmNfaHlqME0

**Comment by maurizioasaro** [comment]
thank you

**Comment by sbenkorichi** [comment]
Let's see if we can get you close the issue yourself.
Get on github, and hit **close issue** as shown in the attached image.
![close](https://user-images.githubusercontent.com/20113030/32601529-dc643b22-c53a-11e7-89dc-8712beacb99c.png)
