### ISSUE TITLE
VERBOSE=.TRUE. not functions for >29 meshes

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5694]
I would like to see the details of each time step group but FDS does not output them when mesh number exceeds 29, despite VERBOSE=.TRUE.

Thank you.
Tried with:
FDS 6.5.3
FDS 6.6.0

[verbose.fds.txt](https://github.com/firemodels/fds/files/1461515/verbose.fds.txt)

**Comment by mcgratta** [comment]
There appears to be two competing parameters added to FDS. The parameter you should use is called `SUPPRESS_DIAGNOSTICS=.FALSE.`, which you add to the `&DUMP` line. I'll fix this, and make these parameters internally consistent.

**Comment by Er9y714** [comment]
Glad it was spotted promptly. I will leave you to close the issue. 
Thank you.

**Comment by Er9y714** [comment]
SUPPRESS_DIAGNOSTICS is by default .FALSE.
Do you think should I add it to DUMP even in this case?

**Comment by mcgratta** [comment]
In `read.f90`, these lines are executed before the `&DUMP` line is read:
```
IF (NMESHES>32) THEN
   SUPPRESS_DIAGNOSTICS = .TRUE.
ELSE
   SUPPRESS_DIAGNOSTICS = .FALSE.
ENDIF
```
So you need to add `SUPPRESS_DIAGNOSTICS = .FALSE.` to the `&DUMP` line to get the full diagnostic output.

**Comment by sbenkorichi** [comment]
Check section 3.3 of UG.
