### ISSUE TITLE
Mesh related error when running WIND scenario - PROCESS_ALL_MESHES=.TRUE.

### ISSUE THREAD

**Issue by Erik-Carlsson** [firemodels/fds#5696]
When running a multi mesh MPI simulation using &WIND and PERIODIC vents, the following error is received:
forrtl: severe <157>: Program Exception - access violation

Three simplified FDS input files attached. Everything is identical in these except the number + division of meshes:
Working.fds: 4 meshes
AlsoWorking.fds: 8 meshes
NotWorking.fds: 5 meshes

The error does not occur when PROCESS_ALL_MESHES=.TRUE. is added to the MISC line.

(First reported here: https://groups.google.com/forum/?fromgroups#!topic/fds-smv/_B2wkPixsXU)

[Wind and Periodic vent error.zip](https://github.com/firemodels/fds/files/1462033/Wind.and.Periodic.vent.error.zip)

Thanks.

**Comment by mcgratta** [comment]
Randy -- I have an easy fix for this problem if we can assume that a `PERIODIC` boundary is restricted to rectangular block domains. Can you think of a case where we might want to use `PERIODIC` when the domain is not a large block?

**Comment by rmcdermo** [comment]
Though theoretically possible, I do not want to consider that case.  You
can assume (1) a PERIODIC bc covers an entire domain boundary and (2) it
has a corresponding boundary on the opposite side.

**Comment by mcgratta** [comment]
Randy, when you have a chance, could you remove `PROCESS_ALL_MESHES` from your natural convection cases and test. You should no longer need this.

**Comment by rmcdermo** [comment]
Seemed to work fine.
