### ISSUE TITLE
Possible typo in FDS Validation Guide

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5703]
I'm using FDS 6.5.3 for validation study, and have a question about a figure in the following FDS validation document. "Fire Dynamics Simulator Technical Reference Guide Volume 3: Validation" In the Figure 9.21 (page 318) of the section 9.2.1 "FM/FPRF Datacenter Experiments", there are 2 legends with the same title of "C3H6 High SF". I think one of them, maybe lower, should be "C3H6 High HA". Is that correct? Thank you,

**Comment by sbenkorichi** [comment]
I've traced the issue. It's corrected it should be HA instead of SF.
Jason would you like me send PR to fix this?

**Comment by drjfloyd** [comment]
Salah, please send a PR if you have already figured out the fix.  thanks.

**Comment by sbenkorichi** [comment]
Done !

**Comment by drjfloyd** [comment]
Thanks.

**Comment by sbenkorichi** [comment]
@drjfloyd 
I think this is done. Can you get it closed. Thanks !

**Comment by sbenkorichi** [comment]
Thanks Randy !
