### ISSUE TITLE
HT3D: Add multiple layers feature. 

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5731]
@rmcdermo 
Randy, 
I'm leaving this as a milestone reminder. We should be able to get multi layers works with HT3D to avoid creating multiple OBSTs for one SURF.

**Comment by rmcdermo** [comment]
Anything is possible -- but this is not a trivial change.  How would @sbenkorichi  propose to make this work?

**Comment by drjfloyd** [comment]
@sbenkorichi 

Something to consider is how do you handle an OBST where multiple layers (possibly different sets of multiple layers) are assigned to adjacent faces?  To properly handle this you would need to develop meshing scheme to handle the edges and corners.  I agree with Randy that this isn't trivial.

**Comment by sbenkorichi** [comment]
I was thinking it would be possible to work it out as we have now for 1D. 
It's not 1st priority, but we can try to come with some solution --If it's gonna take that much --Then just close it.
