### ISSUE TITLE
Objects Repository

### ISSUE THREAD

**Issue by linomassarani** [firemodels/fds#5732]
Is there a repository with construction's objects already made by the community?  I mean, if I simulate a fire in a bedroom and write a bed code in fds, I could share it with all the community so  anybody else can get this code and just set some peculiarity instead of recreate it all from the beginning .

**Comment by sbenkorichi** [comment]
First of all, questions are asked in the discussion group. This platform is reserved for bugs or feature requests.
Secondly, the answer is no. You should create your own bed and set it's properties accordingly. This doesn't need much efforts to create a database for it. Read user guide for more info.

**Comment by linomassarani** [comment]
Thanks for your patience!

I'm firefighter and I'm learning about FDS, your work saves lifes!

Congratulations!


On Nov 22, 2017 11:32 AM, "Salah Benkorichi" <notifications@github.com<mailto:notifications@github.com>> wrote:

First of all, questions are asked in the discussion group. This platform is reserved for bugs or feature requests.
Secondly, the answer is no. You should create your own bed and set it's properties accordingly. This doesn't need much efforts to create a database for it. Read user guide for more info.
