### ISSUE TITLE
Scratch directory SMV

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5736]
Command line screen shows missing letters in the scratch directory of SMV

![image](https://user-images.githubusercontent.com/26166281/33175726-e9545a2e-d05c-11e7-8b7e-66eb37299c0b.png)

Thank you
SMV 6.6.0

**Comment by gforney** [comment]
This is fixed.  I will post a test smokeview next week.

**Comment by gforney** [comment]
This should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing
(go ahead and close if this fixes your problem)
