### ISSUE TITLE
Default view point in SMV - GRAVity

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5737]
By default I see the models from front view, horizontal in SMV. But when I introduce gravity vectors, it is shown tilted, that makes it hard to navigate orientation when it was already challenging to see a very long and narrow tunnel model. 

Instead of aligning according to gravity vectors, is it possible to make it shown horizontal according to mesh ground?

Thank you.

[1.fds.txt](https://github.com/firemodels/fds/files/1500927/1.fds.txt)

**Comment by gforney** [comment]
download test smokeview here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

Open motion dialog at Dialogs>Motion... .  Then select "Specify Orientation" tab.  Unselect "Gravity vector down" checkbox.   Click on "Save settings" button so smokeview will remember this setting next time you open your case.  (note you should also be able to get what you want in the existing smokeview by selecting 90 in elevation spinner after unselecting gravity vector down checkbox)

**Comment by Er9y714** [comment]
That solves the problem which was not there. :)
Thank you.
