### ISSUE TITLE
Graph plots units: Improvement 

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5746]
I've noticed in some graph plots in different Manuals unnecessary gap between units. This might be due to the excel how it handles this, especially when it comes to Temp in °C. It's better to fix this. I will post if I have a fix. 
Any suggestion is welcomed. 
![units](https://user-images.githubusercontent.com/20113030/33315464-b38ee36c-d428-11e7-9c61-6fcb922aae15.png)

**Comment by rmcdermo** [comment]
This is a bug in the linux version of Matlab.  The temporary fix is that we have to build the plots on a Windows or Mac machine for the bundle.  This time around, we opted not to do that, given all the other things we were juggling at the time.  The problem will also go away once we give Matlab the boot, whenever that might be.

**Comment by sbenkorichi** [comment]
I see. Interesting.
