### ISSUE TITLE
Velocity on the OBST boundary

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5750]
A supply surface with 1m/s velocity is placed on the left side (green), Right side of the boundary is OPEN. Three DEVCs measure MEAN Velocity over a surface. First one measures (U-velocity) 1 m/s, second 2m/s, third one is 1 m/s. 

Visually, the first two locations I measure have the same open area in cross-section. However, they output different results. 

If there is no problem with the measurements, could you please explain the logic here? So next time I would anticipate what I will measure based on the location of a DEVC.

Thank you. 

![vel](https://user-images.githubusercontent.com/26166281/33385427-e1c44816-d528-11e7-88a1-3d031b36fcdb.PNG)
[velocity2.fds.txt](https://github.com/firemodels/fds/files/1514497/velocity2.fds.txt)

**Comment by mcgratta** [comment]
I'll see if we can throw an error if this function is used improperly.

**Comment by Er9y714** [comment]
I would still like to be able to use this function when the DEVC is partly in the OBST. Such as measuring a flow at a cross-section of a tunnel. When a tunnel bore profile is not a rectangle,  then using a DEVC to span over whole mesh would be easy to use. 

Example:
![image](https://user-images.githubusercontent.com/26166281/33386619-a38aca90-d52b-11e7-99d7-d37d3a414ccd.png)

**Comment by Er9y714** [comment]
An addition, 
Copying the same input that I posted on the message board;

Having different outputs from these two DEVCs is counterintuitive.  Would there be a solution for that as well?

![vel](https://user-images.githubusercontent.com/26166281/33387535-d4c7d3a8-d52d-11e7-8dd7-19e05b06a783.PNG)

**Comment by drjfloyd** [comment]
For an averaging output FDS locates each grid cell that is within the XB. To avoid double counting cells when the XB is exactly at a cell edge, we check cell i as  X_i-1 < XB =< X_i.  If that grid cell is solid, it doesn't include the cell in the average.  In the first device the XB range is on the -x side of the OBST; therefore, the cells that fall into the XB are all gas cells.  In the second device the XB range is on the +x side of the OBST; therefore, some of the cells in the XB range are solid. I don't think there is any easy solution for this.

**Comment by mcgratta** [comment]
The best advice I can give is true for all devices, point or planar. Put the XB or XYZ coordinates inside a cell. Do not put the point or plane on a cell edge. You can do this by just adding some extra digits:
```
&DEVC XB=0.41,0.41,0,1,0,1, QUANTITY=...
```
Can you check to see that this strategy produces reasonable output?

**Comment by Er9y714** [comment]
@drjfloyd ; I remember this check routine from point DEVCs. So this works the same way. Thank you.
@mcgratta ; adding digit did not help: OBST ends at 0.5m. Device #2 gives 2m/s until the X location is 0.55m (half of adjacent gas cell).

**Comment by mcgratta** [comment]
Yes, you are right. The `XB` coordinates are snapped to the nearest grid cell. Then, FDS determines if a cell is blocked based on the coordinates to which the `XB` is snapped. So it is best to move your specified measurement plane more than 1/2 a cell away from an obstruction.
