### ISSUE TITLE
Typo in FDS User Guide - CRITICAL_FLAME_TEMPERATURE

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#5751]
In the FDS User Guide there is a typo on Table 18.23 for the default value of the CRITICAL_FLAME_TEMPERATURE. The table should read 1427 C. The value is correctly given on page 153 of the guide.

Images of the source code and table are attached. 

Sorry that I cannot correct myself and then submit as a change.

Dan
![critical_flame_temperature_source](https://user-images.githubusercontent.com/13338306/33390072-75749982-d4fa-11e7-82df-c463a042529e.png)

![critical_flame_temperature_table 18 23](https://user-images.githubusercontent.com/13338306/33390077-79dcb0a4-d4fa-11e7-907a-ea0cb234274d.png)

**Comment by rmcdermo** [comment]
Thanks, Dan.  Should be fixed now.
