### ISSUE TITLE
Error opening smv file

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5767]
Could you please have a look at this file? SMV gives error and does not open it. 
Thank you

SMV 6.6.0
[a.fds.txt](https://github.com/firemodels/fds/files/1542224/a.fds.txt)

**Comment by sbenkorichi** [comment]
Well, it reads it from my end. 
You need to give us more info, paste the error you get of smokeview. Also specify which version of smokeview, you can get it by typing smokeview in terminal. 
![a_0001](https://user-images.githubusercontent.com/20113030/33764650-3cb465b8-dc0d-11e7-87bf-933cbbf35fd2.png)

**Comment by Er9y714** [comment]
FDS6.6.0-131-g88ae75a-HEAD
SMV 6.6.0-7-g28a3d96

I do not get any message, It just crashes

![image](https://user-images.githubusercontent.com/26166281/33764807-66c348ac-dc16-11e7-80f0-936a874e46c1.png)

**Comment by sbenkorichi** [comment]
You might have an issue with GPU. Not sure yet, 

1. Try also this: in terminal do : smokeview a.smv 
see if it works. 
2. try with the latest version here: 
get 6.6.1. Install smokeview and see if it gives the error or not. 
https://pages.nist.gov/fds-smv/downloads.html

**Comment by Er9y714** [comment]
1- It did not help. The same error. 

2. I did not know 6.6.1 exists. Downloaded and tried. It works!

Thank you!

**Comment by sbenkorichi** [comment]
Ok, great !
