### ISSUE TITLE
Mesh/Obst definition

### ISSUE THREAD

**Issue by reino33** [firemodels/fds#5770]
I'm having a very weird issue with defining an obstruction: 

I have defined 3 meshes. Mesh1 has a resolution of 1cm in each direction. Mesh2 is stacked on top of Mesh1 (in the Z direction) and has a resolution of 1cm in both the X and Y direction, the remaining resolution (in the Z direction) is 1mm. Finally, Mesh3 is stacked on top of Mesh2 and has a 1cm resolution in all directions.

I specify a plate obstacle that is entirely contained in Mesh2 but when I checked the geometry in Smokeview I noticed that, in addition to the defined plate, 2 thin plates were present at the interface of Mesh2 with the other 2 meshes (cf attached image).
```
&HEAD CHID='10mmL'/
&TIME T_END=0/

&MESH ID='MESH1',
      IJK=54,54,42,
      XB=-0.270,0.270,-0.270,0.270,0.000,0.420/

&MESH ID='MESH2',
      IJK=54,54,10,
      XB=-0.270,0.270,-0.270,0.270,0.420,0.430/

&MESH ID='MESH3',
      IJK=54,54,10,
      XB=-0.270,0.270,-0.270,0.270,0.430,0.530/

&SURF ID='surf',COLOR='RED'/
&OBST ID='Plate',XB=-0.1,0.1,-0.1,0.1,0.424,0.425, SURF_ID='surf'/

&TAIL /
```
![capture](https://user-images.githubusercontent.com/34452229/33840182-79ba6b5e-de94-11e7-8386-faa80cdf8828.PNG)
[10mmL.fds.txt](https://github.com/firemodels/fds/files/1548415/10mmL.fds.txt)

**Comment by rmcdermo** [comment]
Glenn,
Can you please take a look?

**Comment by gforney** [comment]
obst info is being output to the .smv file for both meshes.  so think this is an fds issue

**Comment by reino33** [comment]
I just wanted to add that using the modified input file attached below, the thin plate at the interface of mesh2 with  mesh3 is not present anymore.
```
&HEAD CHID='10mmL'/
&TIME T_END=0/

&MESH ID='MESH1',
      IJK=54,54,42,
      XB=-0.270,0.270,-0.270,0.270,0.000,0.420/

&MESH ID='MESH2',
      IJK=54,54,11,
      XB=-0.270,0.270,-0.270,0.270,0.420,0.431/

&MESH ID='MESH3',
      IJK=54,54,10,
      XB=-0.270,0.270,-0.270,0.270,0.431,0.531/

&SURF ID='surf',COLOR='RED'/
&OBST ID='Plate',XB=-0.1,0.1,-0.1,0.1,0.424,0.425, SURF_ID='surf'/

&TAIL /
```

![capture](https://user-images.githubusercontent.com/34452229/33840722-0448b0f4-de96-11e7-8bed-c63f1cd0e030.PNG)
[10mmL.fds.txt](https://github.com/firemodels/fds/files/1548436/10mmL.fds.txt)

**Comment by mcgratta** [comment]
For multiple mesh calculations, FDS looks for `OBST`s that are within 1/2 grid cell of the exterior boundary of a mesh. Thus, Mesh 1 sees an `OBST` within half a grid cell and snaps it to the boundary. It's seen as a wall that is not exactly aligned with the grid. Add `MESH_ID='MESH2'`  to the `OBST` line and that should make the other meshes ignore it.

Let me know if it works.

**Comment by sbenkorichi** [comment]
Wow, Interesting, it did help indeed. Haven't had seen this issue before.

**Comment by mcgratta** [comment]
I've never used that trick. It's intended for evacuation.

**Comment by reino33** [comment]
I confirm, it's working correctly. Thank you.

**Comment by sbenkorichi** [comment]
Good, then you can close this issue.
