### ISSUE TITLE
Add verification for HT3D in 2D CYLINDRICAL coordinates

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5773]
@sbenkorichi I have a task for you if you are up for it.  I've just implemented 2D CYLINDRICAL for HT3D.  It needs a verification case.  Can you select one from C&J and set it up?  I've attached here a demo input file that works with the latest code.

[ht3d_2d_cyl.fds.txt](https://github.com/firemodels/fds/files/1552154/ht3d_2d_cyl.fds.txt)

Another thing that has been added is the ability to set the solid boundary for HT3D on the boundary of the computational domain.  This makes it easier to do pure conduction problems, but also just more general.  Could you try to play with this and see if you can break it.  That is, try all manner of different boundary conditions on an outer boundary (specified temperature, specified heat flux, no heat flux, etc.) and see if either the code seg faults or gives nonsensical results.

**Comment by sbenkorichi** [comment]
Sure, will take a look.

**Comment by mcgratta** [comment]
Do you plan to do this? If not, close the issue.
