### ISSUE TITLE
SOLID_HT3D in SMV

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5780]
Glenn,

You have a feature in SMV to show SLCF in Solid and Gas (default is Gas only).  That feature is working well.  Now I'd like to move forward and pass the logical SOLID_HT3D to the .smv file.  If TRUE, I'd like SMV to default to showing SLCF in Solid and Gas (not solid only).

Thanks!

**Comment by gforney** [comment]
I updated dump.f90 to output SOLID_HT3D to the .smv file (1 for .true., 0 for .false. - easier for smokeview to parse)

can you point me to a test case that implements 3d heat transfer

**Comment by gforney** [comment]
never mind, I found a bunch of ht3d input files in Verification/Heat_Transfer

**Comment by gforney** [comment]
try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

you need to also update your fds repo and rebuild fds and rerun your case.

note:  smokeview now defaults slice views to gas and solid if SOLID_HT3D is set to 1 in the .smv file unless you decided you wanted something different during a previsous smokeview session and saved the different state to the .ini file.  

Let me know if you see any problems

**Comment by rmcdermo** [comment]
Works great.  Thanks!
