### ISSUE TITLE
Num Instability when using &TRNY 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5795]
I tried the mesh stretching for the first time and I noticed I receive an error when I use TRNY.

Could you please point out what do I model wrong?

Thank you
 
[error.fds.txt](https://github.com/firemodels/fds/files/1565250/error.fds.txt)

**Comment by sbenkorichi** [comment]
The issue has been reported previously here #5709

**Comment by Er9y714** [comment]
Thank you for the reference. Glad to see it was spotted already. 

However this mesh is not over 1000000 cells.  So is  this problem related to only the first mesh?

Should I close the issue or leave it open?

**Comment by sbenkorichi** [comment]
Leave it open, I haven't had time to check your input file. I will take a look at it later.

**Comment by sbenkorichi** [comment]
Ok, your problem lies with the first line. The function must be monotonically increasing,while you have it the opposite way.  Try now with: 
`&TRNY CC=1.6, PC=2.844444, MESH_NUMBER=1/  `

**Comment by Er9y714** [comment]
That works but it changed the geometry.
I use Pyrosim, therefore it generates these lines. To be honest, I can't understand the logic. Also, there is only one line, what is it meant by monotonic increase? The increase of which parameter?


The geometry I aimed to generate in the beginning:
![image](https://user-images.githubusercontent.com/26166281/34082868-e3cd4da0-e366-11e7-8960-6a3e15ac9d38.png)

**Comment by sbenkorichi** [comment]
check Fig. 6.3 of User Guide.

**Comment by Er9y714** [comment]
I already did. I am sorry still do not understand how it is constructed.

**Comment by sbenkorichi** [comment]
I don't know the mesh you have or what you want to achieve, but let's suppose you want to stretch it in the Y direction. 
```
&MESH IJK=20,20,30, XB=0,2,0,2,0,3 /

!&TRNX CC=0, PC=0, MESH_NUMBER=1 /
&TRNX CC=0.1, PC=0.2, MESH_NUMBER=1 /
&TRNX CC=1.3, PC=1, MESH_NUMBER=1 /
!&TRNX CC=2, PC=2, MESH_NUMBER=1 / 
```
This is an example, it starts from 0 to 2. However, both starting and ending needs not to be specified.

**Comment by Er9y714** [comment]
I understand the example you give. (below) But it has two points in the function. I only had one in Y direction. So since there is not a second one, why do we mention about monotonic increase? 
 
![image](https://user-images.githubusercontent.com/26166281/34083190-5c864a08-e36c-11e7-94ab-1fa07a6f545c.png)

**Comment by sbenkorichi** [comment]
My understanding is that you need at least two lines. Because, what you've done is you've shrink your mesh, then you need to stretch it as elsewhere, you also have to be careful with stretching and shrinking in the other directions as well. That's why you might be getting this type of error. Also, couldn't you find better mesh grid spacing than using 1,0.7111,0.564.

**Comment by Er9y714** [comment]
It is interesting that one line for Z direction is enough while for Y, it is not, then. 

I do not know how you found these grid spacing lengths but I wanted to build this one:
Y length of mesh is 12.8m
4 cells with 0.4m, 14 cells with 0.8m
![image](https://user-images.githubusercontent.com/26166281/34083564-3325c3ee-e373-11e7-813f-6ad3d95fe7d1.png)

**Comment by sbenkorichi** [comment]
I see now what you want to do from the last image.
Well, the only reason (I think you're having this numerical instability is coming from the aspect ratio between x and y or z, i.e. 1m against 0.4 m). Try to either reduce the x cells to 0.8 or increase the 0.4 to 0.5. See if it helps.

**Comment by sbenkorichi** [comment]
Ok, this should fix the issue. Apparently Pyrosim goes up to 6 decimal digits only. There was a need to go beyond that for accuracy. 
Try this now. 
`&TRNY CC=2.8444444444, PC=1.6, MESH_NUMBER=1/ `

**Comment by Er9y714** [comment]
It works!  Thank you @sbenkorichi . 

But what happened here that made the FDS run? There is only one mesh, so misalignment is not the issue. Are there certain grid sizes that FDS does not calculate?  I wonder why did adding two digits matter?

You say accuracy but we are not trying to match some number, so what accuracy can we talk about?

**Comment by sbenkorichi** [comment]
Well, it did matter here. You want 4 cells of this type.
4x12.8/18 =2.4444444..
I previously said it would be better to choose other mesh cell other than 0.711111... . I have noticed similar issue before while working on the Mult as well.

**Comment by Er9y714** [comment]
Update,
combined with TRNZ, it does not work again. 

```
&HEAD CHID='a'/
&TIME T_END=10.0/
 &MESH ID='Entrance01', IJK=100,18,17, XB=0.0,100.0,0.0,12.8,0.0,9.6 /
&TRNZ CC=3.952941, PC=5.6, MESH_NUMBER=1/  
&TRNY CC=2.8444444444444444, PC=1.6, MESH_NUMBER=1/  
&VENT ID='Entrance Dynamic Pressure', SURF_ID='OPEN', XB=0.0,0.0,1.2,9.6,0.0,5.6, COLOR='INVISIBLE', DYNAMIC_PRESSURE=100.0 / 
&RAMP ID='Entrance Dynamic Pressure_PRESSURE_RAMP', T=0.0, F=200.0/ 
&VENT ID='Vent01', SURF_ID='OPEN', XB=100.0,100.0,0.0,12.8,0.0,4.0/ 

&TAIL /
```

**Comment by sbenkorichi** [comment]
This should fix it. 
```
&TRNZ CC=3.952941176, PC=5.6, MESH_NUMBER=1/  
&TRNY CC=2.844444444, PC=1.6, MESH_NUMBER=1/ 
```

**Comment by Er9y714** [comment]
This concludes that digit number should be increased. 

Thanks for your time @sbenkorichi 
I will close the issue.

**Comment by sbenkorichi** [comment]
Yes, because precision with numbers matter for Fortran.

**Comment by bwklein** [comment]
You can increase Max Precision on the first tab of the PyroSim Preferences dialog.

**Comment by bwklein** [comment]
PyroSim Preferences https://imgur.com/gallery/1LaUM

**Comment by sbenkorichi** [comment]
Thanks Bryan for the feedback.
