### ISSUE TITLE
numerical instability error (FDS 6.6.0)

### ISSUE THREAD

**Issue by skfong812** [firemodels/fds#5797]
hi guys
im using FDS 6.6.0 for simulating the steady state fire inside a tunnel. But when time step reached 0.47s, simulation terminated due to numerical instability error. I tried to disable the screen, it works so it maybe related to the screen. The code was attached below. Please have a look.

[TUNNEL.txt](https://github.com/firemodels/fds/files/1568212/TUNNEL.txt)

**Comment by mcgratta** [comment]
I'll take a look at it. I suggest that you also try to diagnose the problem by doing the following:
1. Look at the Plot3D file that is produced at the end of the run. Hit "v" for velocity and see where the trouble is occurring.
2. Remove gradually details from the input file, like the grill. Try to make the input file as simple as possible.
3. Add slices of "PRESSURE" and other diagnostics. You do not seem to have any.

**Comment by skfong812** [comment]
thanks mcgratta
i will try to do these

**Comment by mcgratta** [comment]
I removed the INIT lines, and the particles. These are fragile. If you want to use them, you ought to create simple verification cases first to make sure they work as intended. They are not commonly used this way. The case is now running past the point of failure.
