### ISSUE TITLE
Questions about technical issues

### ISSUE THREAD

**Issue by sea2003** [firemodels/fds#5798]
Hello-
I am a graduate student researcher at Yonsei University in South Korea.

I am currently developing an application that can simulate FDS for educational purposes.

For accessibility, this is a situation where I have to make a web application, but I'm having problems with how to visualize Smokeview on the web.

Is there a way to show Smokeview on the web like ParaViewWeb or any  similar program?

I would like to hear your suggestion. 

Thanks ahead before your help.

**Comment by rmcdermo** [comment]
There is currently not a way to do this that I know of.

Other technical questions should be asked to the [discussion forum](https://groups.google.com/forum/#!forum/fds-smv), unless there is a bug in the code.  Thanks.
