### ISSUE TITLE
New version of qfds.sh is missing -f option

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5811]
I tried to run some validation cases, and got the error
```
qfds.sh: illegal option -- f
```
In `Validation/Common_Run_All.sh`, there is a `-f` option for the `qfds.sh` command. I assume this was removed when the script was overhauled. What did this option do?

**Comment by gforney** [comment]
The -f option was used to specify the repository root.  I had removed several options that I thought were not used or not commonly used and replaced them with environment variables (environment variables qfds uses are documented at the top of the script.

It probably makes more sense to specify the repository root as I did before with -f  .  I added it back so the Validation scripts should work now.

**Comment by gforney** [comment]
think this is fixed now.  if you see other problems let me know
