### ISSUE TITLE
FDS Verification Guide - Error in Appendix A Table A.1

### ISSUE THREAD

**Issue by djbranson** [firemodels/fds#5821]
Appendix A, Table A.1 (page 196), Case Name duct_flow contains two records with Predicted Quantity of flow_in and flow_in, and Predicted Value of 9.81e-01 and 1.00e-00, respectively.  My run results yielded those same Predicted Values, but they were for the Predicted Quantities flow_out and flow_in.

Please verify that the FDS Verification Guide contains a mislabeled Predicted Quantity for the first of these two data records.

**Comment by sbenkorichi** [comment]
Ok thanks for reporting it. We'll talk a look.

**Comment by mcgratta** [comment]
This should be fixed. I'll verify with our nightly testing results.

**Comment by mcgratta** [comment]
This is fixed.
