### ISSUE TITLE
HT3D Multi-mesh Gas/Solid Heat Exchange Problem

### ISSUE THREAD

**Issue by tgob** [firemodels/fds#5822]
I’ve been experimenting with the HT3D beta release in FDS 6.6.0, and in particular application over multiple meshes.

I am experiencing an issue with the multiple mesh implementation when gas/solid heat transfer is invoked at an obstruction boundary.  The problem occurs during initialisation of the associated MPI HT3D processes.

The computer environment is a four node Linux Ubuntu 16.04 cluster, each with a four core i7 and 16 GB RAM.  The nodes are networked with a Mellanox 40 Gbps Infiniband running under Mellanox OFED 3.4-2.0.0.0.

I’m using Intel MPI and Intel compilers (Intel Parallel Studio XE, 2018 Cluster Edition).  FDS is version 6.6.0.

The IB, Intel MPI and SSH over nfs have been extensively tested and are working just fine.

/etc/security/limits.conf includes  * soft memlock unlimited and * hard memlock unlimited, and .bashrc includes both ulimit -s unlimited and I_MPI_SHM_LMT=shm on all nodes.

I have searched the Intel documentation but cannot find a related known issue (but this is not to say that there isn’t one). 

FDS passes verification and runs large multi-process models (up to 16 meshes with 8,000,000 total cells) over Infiniband just fine.  This issue only relates to HT3D over multiple meshes where the model uses gas/solid heat exchange.

The platform runs the FDS verification HT3D models including ht3d_ibeam.fds, and ht3d_2mesh_x(y,z).fds from Examples, Heat_Transfer just fine (the later three under two MPI processes).  However these models use hot surface patches while I’m interested in radiation and convective heat exchange to the solid.

I have made my own very simple test model (hd3d_test.txt, attached).

This model runs fine as a single process (1 node) under MPI both with and without assigned OMP threads.  However if the model is invoked over 2 or more MPI processes it hangs on initialization and eventually reports a time-out associated with ‘error  stack’ on one or more nodes (sometimes including the Master Node) from the MPI_Startall (see attached terminal log ht3d_test.log).

The allocated nodes (Master, Slave0, Slave1 and/or Slave2) make no difference.

I figure that the MPI_Startall is associated with HT3D MPI initialization in main.f90.  If the ‘req_array=0x2ab64ea4a220’ is actually the requested stack size then I’m not surprised that the initialization call is failing!

If I remove HT3D=.TRUE. from the object line the model runs fine over 2 or more MPI processes (even with HT3D=.TRUE. remaining on the associated surface line) but of course I don’t get to simulate 3D conduction.

I have tested the same model with HT3D under 1 MPI process with ramped conductivity, specific heat and hot surface temperature.  These work fine under 1 MPI process.

Turning off the radiation solver, forcing another network transport, or switching from LES to DNS makes no difference to the multiple MPI process initialization fault.

I do recognise that this is a beta release of HT3D but perhaps you can help with this.  Do let me know if there is any other information that I can provide or experiments that you would like me try.

Perhaps you would consider including a multi-mesh gas/solid ht3d heat exchange model in the Examples. 

[ht3d_test.log](https://github.com/firemodels/fds/files/1585751/ht3d_test.log)

[ht3d_test.txt](https://github.com/firemodels/fds/files/1585752/ht3d_test.txt)

**Comment by sbenkorichi** [comment]
Tim, 
I haven't looked deep into this, but Randy, currently is working on this. It's expected not to work in the current code. If you want to make it work, then you need to compile prior to today s code.  Go back to 5th November for example, and download the source code and then compile it, it should work.

**Comment by sbenkorichi** [comment]
Try with this.
https://github.com/firemodels/fds/tree/3837b4a79f07538f74cf3c5bdc6aa86a93d9cc9e

**Comment by tgob** [comment]
Whoot!  Now we're cooking with gas.  Thank you.

 

You might want to amend the 31 Oct 17 release notes for HT3D to reflect the actual status of this feature.

 

t.

**Comment by sbenkorichi** [comment]
The official release was on 1st November. Now, there's an ongoing work to improve and upgrade the HT3D. The multi mesh works fine in the official release, as for those who are compiling it themselves, then they need to be aware that there's some maintenance taking place. Later the multi meshes will be set back again.

**Comment by rmcdermo** [comment]
This seems to be running with the latest source.  Please confirm.  Thanks.

**Comment by sbenkorichi** [comment]
Works on my end.

**Comment by tgob** [comment]
Thanks for the update Randy.  I see that Salah has already confirmed the MPI operation.  My cluster is busy for a few days on a commercial job, but when it's finished I'll compile the current image and let you know how it performs under mpi on my platform.

 

t.
