### ISSUE TITLE
INTEL 18: Compilation failures

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5827]
It's been around 2 weeks I haven't compiled with intel. Now, for somehow I get weirdo messages. I haven't found yet what is  the reason behind it, either from my end or is to do with the code. I use Gnu and it works fine.
I can't figure out why it's misbehaving, with one commit it works and with another it doesn't. 
I've just reinstalled intel 18 fresh -- might be due to the lack of 32 libraries -- can't tell yet. 
Latest commit doesn't work, while the one before or the previous than it, it compile fine. Then 3-4 commits it doesn't. It's high likely to do with the compiler.  An example from the latest commit:
```
mpifort -c -m64 -check -warn all -O0 -auto -WB -traceback -g -fpe0 -fltconsistency -no-wrap-margin -fpp -DGITHASH_PP=\"FDS6.6.0-495-ga96a4bc-master\" -DGITDATE_PP=\""Thu Dec 28 11:13:43 2017 -0500\"" -DBUILDDATE_PP=\""Dec 28, 2017  23:26:32\"" -DCOMPVER_PP=\""Intel ifort 18.0.0"\" -DWITH_MKL -I/opt/intel/compilers_and_libraries_2018.0.128/linux/mkl/include ../../Source/init.f90
../../Source/read.f90: catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for ../../Source/read.f90 (code 1)
../makefile:118: recipe for target 'read.o' failed
make: *** [read.o] Error 1
make: *** Waiting for unfinished jobs....
```
 I will try to work on this and see why it's misbehaving this way.

**Comment by sbenkorichi** [comment]
@rmcdermo 
Review the changes done to the read file here https://github.com/firemodels/fds/commit/454781fb0b24b0c4ed324fe0041db1089601fd94

**Comment by rmcdermo** [comment]
What are you asking?  Most of this code has since been modified.  Firebot passed last night, but we have not moved on to Intel 18.

I recommend you stay with 17 until we decide to move forward.  This is taking time away from other important issues.

**Comment by sbenkorichi** [comment]
Ok, fair enough. I've downgraded to 17, it works now. But, the 18th starts complaining from that commit. Maybe later we need to get back to it once you decide to upgrade on the cluster form your end.
