### ISSUE TITLE
Only allocate M%N_OBST for obstructions within mesh boundaries

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5835]
Currently M%N_OBST is the same for all meshes and equal to the number of valid OBSTs in the domain.  We should first count, then assign properties to the OBSTs.  This will help with memory allocation for cases with a large number of OBST, such as BURN_AWAY and OBST with RADIUS.

A good example to test is the Verification/Heat_Transfer/ht3d_sphere_100.fds case (8 mesh).

**Comment by mcgratta** [comment]
Check to make sure this solves the memory problem.

**Comment by rmcdermo** [comment]
Something is weird on my end---the 8 mesh case does not work.  No heat transfer in MPI and no OBST in serial.

Did you successfully run the case?

**Comment by rmcdermo** [comment]
Actually, what I'm getting is that single mesh works fine.  Multi-mesh I get no OBST, whether serial or MPI.

**Comment by rmcdermo** [comment]
Try this case.

[ht3d_sphere_50.fds.txt](https://github.com/firemodels/fds/files/1600790/ht3d_sphere_50.fds.txt)
