### ISSUE TITLE
[request] SMV time offset

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5841]
I was wondering if time offset is possible to add to SMV. 

_Adding and deducting_ capabilities would be useful. My aim is to see the resulting time on the time bar as an adjusted value. 

Thank you.

**Comment by rmcdermo** [comment]
Does it not just work for you to set T_BEGIN to something other than 0?

**Comment by Er9y714** [comment]
I know this is not an excuse but I do not prefer using T_BEGIN<0 in complex runs just as a precaution.

**Comment by rmcdermo** [comment]
Well, please understand that we would prefer to fix a problem with negative T_BEGIN, if one exists, than add more code to do the same thing (which itself will end up with problems).

**Comment by Er9y714** [comment]
I understand your reason. But this feature would be regarded as a postprocessing tool like video editing. Because when needed, I would not run the simulation once again because of time needed. 
In any case, thank you for your reply. I will look for an alternative solution.

**Comment by rmcdermo** [comment]
I thought there might be a way to hack the Smokeview file, but doesn't look like it.  I'll let Glenn decide if he wants to add this to Smokeview.

The other option would be to hack the .sf files.  Not too hard if you know Matlab, just use Simo's slread.m script and rewrite the time lines.

**Comment by gforney** [comment]
I will take a look at it

**Comment by gforney** [comment]
there is a TIMEOFFSET keyword already in the .ini file.  so,
1.  save an ini file
2.  alter the TIMEOFFSET value in this .ini file to the offset you want

I'll look at adding a widget to smokeview to let you set this value within smokeview

**Comment by gforney** [comment]
try smokeview posted here.  widget for specifying time offset is in Time tab of bounds dialog box - Dialogs>Data bounds
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
@gforney  the trick in .ini file would be more than enough. Yet, thank you for sparing time to add it to the SMV. It works great!
