### ISSUE TITLE
Problem with Port-Replicator

### ISSUE THREAD

**Issue by BrianK12** [firemodels/fds#5848]
A colleague have a laptop with Port-Replicator, but when he start up Smokeview he get a error "Smokeview.exe has stopped working".
 When he unplugg the Port-Replicator and remove the drivers, Smokeview will run without any problem.
 The Laptop don't have a connector for a dockstation, is there any other solution to fix it?

Kind Regards,

Brian

**Comment by gforney** [comment]
What error

**Comment by BrianK12** [comment]
When he runs a .smv file the programm stops with working.
When I deleted the drivers of the port replicator it runs without any problem.
Or do you need a error code?
