### ISSUE TITLE
naccesspolicy=singlejob not working

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#5862]
The -t option of qfds.sh uses naccesspolicy=singlejob in the PBS script it generates to require the job to run on a node by itself.   This is not working on blaze.  To see this do the following on blaze.  Note the bench queue only has two nodes .  So if this queue is empty, the first two jobs will start running but the third job is assigned a Q state.  What actually happens is that all three jobs run. 

qfds.sh -t -q bench job1.fds
qfds.sh -t -q bench job2.fds
qfds.sh -t -q bench job3.fds

I've implemented a temporary fix until we figure out what is going on.  If you add the following environment variable to your .bashrc , export NCORES_COMPUTENODE=8, then qfds.sh will revert to the way that the -t option used to be implemented by assigning in this case 8 cores to the job (so no other jobs can run)

kevin - I think you added naccesspolicy=singlejob to qfds.sh .  can you take a look at this.  I've done some googling but didn't get any hits on issues that may prevent naccesspolicy from working.  I'll look at this too. Either we've been lucky for a long time or this just stopped working in which case I'm not sure why.

**Comment by gforney** [comment]
I'm seeing the same behavior on burn.  To test on burn use -q test2  (like bench on blaze, test2 has only two nodes - burn023 and burn032 ) .

**Comment by mcgratta** [comment]
Is this still an issue?

**Comment by gforney** [comment]
sorry, I didn't see your question.  It is not an issue - I changed qfds to use a different method more running a job alone on a node
