### ISSUE TITLE
Add machinery to link HT3D SOLID cells to WALL_CELLs for 3D pyrolysis

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5866]
We need to add the data structures to know which IW to add mass to when a solid cell pyrolyzes with HT3D.  I'm thinking we should connect IWs in all 6 directions from the solid cell.  Imagine a SOLID cell in the center of a large cube that pushes mass in all 6 directions evenly.  We would, in general, weight the mass distribution depending on distance from the SOLID cell to the WALL_CELL.

**Comment by mcgratta** [comment]
See PR above. I added a stand-alone routine to `func.f90` which at the moment is called once during the initialization. Explanation of the routine is in the code.
