### ISSUE TITLE
HT3D Multimesh Causes Zero Volume Obstructions

### ISSUE THREAD

**Issue by tgob** [firemodels/fds#5870]
Hi folks.  I'm having some issues with HT3D on multimesh models.  The attached Mesh2.txt file is a simple FDS setup case that demonstrates the problem.  I have included the terminal output in the attached log.txt file.

The two meshes in this simple example follow the FDS User's Guide mesh alignment rules.  The single obstruction is contained entirely within Mesh00.

The model is running under Windows using the NIST fds compiled bundle.

Any assistance appreciated.

[Mesh2.txt](https://github.com/firemodels/fds/files/1617390/Mesh2.txt)
[log.txt](https://github.com/firemodels/fds/files/1617391/log.txt)

**Comment by sbenkorichi** [comment]
This is a warning that Randy has added before the release. However, he's planning to come up with a better way. 
You can ignore it for now.
Also, the start up only might take sometime until the meshes are initialised in order to verify if there is misalignment or not.

Warning: If you are compiling fds yourself, then you need to be aware of the constant changes to it -- So, you should keep updated with the nightly built manuals. -- can be found here: https://drive.google.com/drive/folders/0B_wB1pJL2bFQUlJwMmNfaHlqME0

**Comment by tgob** [comment]
Thank you for your reply Salah, but now I am confused.

 

The warning is telling me that HT3D is disabled on the &OBST line.   If this is actually happening then my model (which is a highly simplified version of HT3D on a structural column) won't actually do what I want and hence the warning cannot be ignored.

 

Why is the warning be generated at all?  The mesh and the obstruction are fully compliant with the mesh intersection rules in the User Guide, the object is entirely mesh aligned, and the obstruction clearly does not have zero volume.

 

Interestingly, if I remove Mesh01, or remove HT3D=.TRUE. from the &OBST line, or align the obstruction so its +ve Y dimension is a non-zero integer multiple of the Mesh02 Y dimension from the Mesh00 and Mesh01 boundary then the warning message disappears.

 

This particular application is not being run on my Linux cluster.  It is run using the NIST FDS 6.6.0 compiled bundle for Windows.   t.

**Comment by rmcdermo** [comment]
@tgob Thanks for reporting.  This is a known issue that I needed a kick to address.  Right now, we cannot do lateral heat transfer for zero thickness OBST, which is what the WARNING is telling you.  However, this is planned, which is what I think Salah is referring to.

One would expect, then that THICKEN=T would solve the WARNING problem, and it does on a single MESH.  But the way FDS handles OBST on neighboring meshes is a bit strange: If you have MESH 1 neighboring MESH 2 and an OBST straddles the MESH interface, then MESH 1 sees a zero thickness OBST from MESH 2, which it uses as a boundary condition, so to speak.  This is what generates the WARNING in your case.  But it should not cause problems with your results---the 3D OBST still exists on its respective MESH, the duplicate zero thickness OBST is what is set to HT3D=F.

**Comment by rmcdermo** [comment]
I've hacked in a fix.  Please confirm that this solves your current problem.  Thanks.

**Comment by tgob** [comment]
Thank you for this clear explanation Randy.  Yes, I can see the zero thickness obstruction projected to the mesh interface in SmokeView, and the number of warnings is consistent with the number of mesh/mesh boundaries.

 

A supplemental question.  If a zero thickness obstruction with HT3D=F actually exists at the mesh/mesh interface will this obstruct radiation and mass flow between the meshes?

 

To give this some context I am experimenting with universal columns for determining structural limit states (temporal and temperature domains) when subjected to compartment post-flashover fires.  The meshes containing the column need to have a relatively fine cell resolution (say 1 mm) perpendicular to the surface of the flanges and webs, but can be relatively course in the plane of the obstruction surface.  Clearly the resolution in the gas phase away from the column can be relatively large.  This problem requires multiple meshes in order to reduce the computational burden.  My initial sensitivity studies are progressing slowly...  

 

I'll go looking for your fix (reported in a subsequent email) and report back.

 

t.

**Comment by rmcdermo** [comment]
Tim,
If I understand your question correctly, yes, a zero thickness obstruction will block mass flow and radiation.  This can be a problem at coarse-fine mesh interfaces if the OBST conforms only to the fine mesh.  There still needs to be some representation of the solid on the coarse mesh and one of the limitations of the Cartesian cell method in FDS is that the face of a given cell is either blocked or not.  On the coarse mesh, that face will be blocked.  Hope this helps.

**Comment by tgob** [comment]
Thank you again Randy.  While I haven't tried your code patch fix , my column model is now working with HTD3 without warnings by placing the obstructions a non-zero integer of the adjoining course mesh resolution from the mesh/mesh boundary.   Setting THICKEN=.TRUE. didn't solve the problem.  The model takes a while to run so it'll be a few days before I can try the code patch fix.  t.

**Comment by sbenkorichi** [comment]
Checking it from my end.

```
salah@sbenkorichi ~/1_issues $ mpirun -np 2 /home/salah/firemodels/fds/Build/mpi_intel_linux_64/fds_mpi_intel_linux_64 Mesh2.fds 

 Fire Dynamics Simulator

 Current Date     : January 11, 2018  09:42:23
 Version          : FDS 6.6.0
 Revision         : FDS6.6.0-583-g05162e3-master
 Revision Date    : Wed Jan 10 16:38:05 2018 -0500
 Compiler         : Intel ifort 17.0.3
 Compilation Date : Jan 11, 2018  09:31:38

 MPI Enabled;    Number of MPI Processes:       2
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI salah@benkorichi Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Job TITLE        : 
 Job ID string    : Mesh2

 Checking mesh alignment. This could take a few tens of seconds...

STOP: Set-up only (CHID: Mesh2)
```
10s run.
```

salah@sbenkorichi ~/1_issues $ mpirun -np 2 /home/salah/firemodels/fds/Build/mpi_intel_linux_64/fds_mpi_intel_linux_64 Mesh2.fds 

 Fire Dynamics Simulator

 Current Date     : January 11, 2018  09:42:37
 Version          : FDS 6.6.0
 Revision         : FDS6.6.0-583-g05162e3-master
 Revision Date    : Wed Jan 10 16:38:05 2018 -0500
 Compiler         : Intel ifort 17.0.3
 Compilation Date : Jan 11, 2018  09:31:38

 MPI Enabled;    Number of MPI Processes:       2
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI salah@benkorichi Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Job TITLE        : 
 Job ID string    : Mesh2

 Time Step:      1, Simulation Time:      0.16 s
 Time Step:      2, Simulation Time:      0.32 s
 Time Step:      3, Simulation Time:      0.47 s
 Time Step:      4, Simulation Time:      0.63 s
 Time Step:      5, Simulation Time:      0.79 s
 Time Step:      6, Simulation Time:      0.95 s
 Time Step:      7, Simulation Time:      1.11 s
 Time Step:      8, Simulation Time:      1.26 s
 Time Step:      9, Simulation Time:      1.42 s
 Time Step:     10, Simulation Time:      1.58 s
 Time Step:     20, Simulation Time:      3.16 s
 Time Step:     30, Simulation Time:      4.74 s
 Time Step:     40, Simulation Time:      6.32 s
 Time Step:     50, Simulation Time:      7.91 s
 Time Step:     60, Simulation Time:      9.49 s
 Time Step:     64, Simulation Time:     10.00 s

STOP: FDS completed successfully (CHID: Mesh2)

```

**Comment by tgob** [comment]
Thank you Salah.  I see that the warning message has disappeared.  However this model does not test mass and radiant heat exchange across a mesh/mesh boundary.  I'll modify the model so you can examine this.

Would you please provide me with a link to a NIST compiled Windows FDS bundle with Randy's patch?  My Intel compilers are Linux.

For the benefit of other users that might be following this thread:  The attached 
![drawing1](https://user-images.githubusercontent.com/20181668/34821553-07402b60-f729-11e7-91cd-d5efe392b682.jpg)
diagram shows how to make the current FDS -HEAD release work when using HT3D with multi course and fine meshes.  The rule extends to other adjoining meshes and the third Cartesian dimension.  If you don't follow this rule then an infinitely thin obstruction (a projection of the actual obstruction) will be made at the mesh boundary, you will get a warning about zero volume obstructions,  and (subject to the properties of the obstruction) this will prevent heat and mass transfer across the boundary. 

 t.

**Comment by sbenkorichi** [comment]
Tim, we don't compile bundles regularly. They're compiled only close to the release date. So, you either need to compile it on your Linux or wait until the coming release --which might take quite some time. 
I myself compile on Linux.

**Comment by rmcdermo** [comment]
Tim,
Just to clarify, HT3D has nothing to do with the fact that zero volume OBST are created at mesh boundaries.  It is just that this was never flagged as a warning and HT3D caught it.

I'm closing this specific issue.  If something else pops up, let us know.  Thanks.
