### ISSUE TITLE
subscript error

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#5875]
fds is crashing with a subscript error:

[gforney@burn TEST]$ fds_db trails.fds
forrtl: severe (408): fort: (2): Subscript #1 of the array OBSTRUCTION has value 9703 which is greater than the upper bound of 9702

Image              PC                Routine            Line        Source
fds_impi_intel_li  0000000008DEB3B6  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000002DC4969  read_input_mp_rea        8195  read.f90
fds_impi_intel_li  0000000002C4679E  read_input_mp_rea         112  read.f90
fds_impi_intel_li  00000000036F371A  MAIN__                    104  main.f90

This case was generated by my program dem2fds (for generating terrain cases from USGS elevation data).  This case has 9801=99x99 obstacles - one obst for each cell in the xy plane.  Note that 9702 = 99*98 so I bet you have a "off by 1" error somewhere.  I can generate a smaller case if you think that would help.

Did a git bisect and got

[gforney@burn fds]$ git bisect bad
9b3a65266c99196250550e38f7e11db81c6986c6 is the first bad commit
commit 9b3a65266c99196250550e38f7e11db81c6986c6
Author: mcgratta <mcgratta@gmail.com>
Date:   Wed Jan 3 11:00:55 2018 -0500

    FDS Source: Issue #5835. Fix bug related to counting OBSTs

[trails.fds.txt](https://github.com/firemodels/fds/files/1620465/trails.fds.txt)

**Comment by mcgratta** [comment]
You must be doing a lat-long conversion. Your y coords were backwards. We have a check for that, but I wasn't checking within the dimensioning loop. Should work now. Check it and close if it works.

**Comment by gforney** [comment]
it works now.  thanks.

you're right, I am converting from lat/long to cartesian coordinates .  didn't notice the reversal - fds forgave me before.  I'll fix.

**Comment by mcgratta** [comment]
No need to fix. FDS still forgives you. We're just getting stingier in how we allocate space for obstructions, and in this case, too stingy.
