### ISSUE TITLE
Typo in guides

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#5893]
I came across few while reading guides.

**Tech ref guide**

- 10.2.4 Heating and **`coiling`** coils
- 4.5.6 ...adjusted to maintain VN between **`0.4 `and `0.5`.**  (I think these were updated to 0.8 and 1.0)

**Verification guide**
- 9.5 Extinction model;   If a criticalflame temperature is not specified, the default value is **`1600`** K.
I also remember this was updated to 1700K. Figure 9.21 might need an updated due to change. 

Thank you.

**Comment by rmcdermo** [comment]
Thanks.  This is fixed.  Note that VN is still set to .5 for DNS.  So the guide is correct.
