### ISSUE TITLE
Clarification on difference in results with different version of FDS (6.2 and 6.6) for the EXTINCTION model

### ISSUE THREAD

**Issue by LahnaACH** [firemodels/fds#5897]
Hello,
I used the 'EXTINCTION_MODEL='EXTINCTION 1' and a model with 'SUPPRESSION=.FALSE./'. In the version 6.2 of FDS, I get different results for both of these models, which is reasonable!
Now if I use the similar conditions in version 6.6 of FDS, my results are similar (no obvious difference observed as it was for the case of version 6.2) irrespective of the models selected (for example see the BLACK and BLUE curve in the image below and compare it with the results of version 6.2). 
I suspect that there may be an error in the version 6.6 that does not take into account the condition SUPPRESSION=.FALSE. or the other way around. 
Could you kindly help me solve this issue.  
Thank you.

![image](https://user-images.githubusercontent.com/34684425/35044298-22f45776-fb90-11e7-9a10-f5302248fb07.png)

**Comment by rmcdermo** [comment]
Thanks for reporting.  Can you send us your simple input file (.txt extension)?  We will take a look.

**Comment by drjfloyd** [comment]
Looking at the source we have SUPPRESSION in an IF block calling auto ignition and in another if block for calling extinction. The two FDS 6 .6 curves in the figure aren't identical (very close however). Combined these suggest we are accounting for SUPPRESSION.  We did get rid of the heat release limiter in 6.3, that might be a factor in the difference between 6.2 and 6.6.  If a file gets uploaded I'll look at that in case there is something else going on that a quick scan of the source isn't revealing.

**Comment by drjfloyd** [comment]
No case uploaded or further feedback from OP. Closing issue.
