### ISSUE TITLE
EVACUATION_ONLY=T for WIND case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5905]
The attached case fails because EVACUATION_ONLY(NM)=T for a given MESH, which does not ALLOCATE MEAN_FORCING_CELL per lines 2129 in read.f90 (READ_WIND).  The code fails when MEAN_FORCING_CELL tries to initialize in init.f90
```
molly:alexi rmcdermo$ fds_db wind_example.fds 
 EVAC: Emesh 1 PF has 1 door flow fields
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable MEAN_FORCING_CELL when it is not allocated

Image              PC                Routine            Line        Source             
fds_mpi_intel_osx  0000000112DD8446  Unknown               Unknown  Unknown
fds_mpi_intel_osx  0000000112778171  _init_mp_initiali         370  init.f90
fds_mpi_intel_osx  000000011292264E  _MAIN__                   163  main.f90
fds_mpi_intel_osx  000000010EA542FE  Unknown               Unknown  Unknown
```
[wind_example.fds.txt](https://github.com/firemodels/fds/files/1642723/wind_example.fds.txt)

**Comment by rmcdermo** [comment]
@tkorhon1 please use this to generate a WIND / EVAC verification test.  Thanks.

**Comment by mcgratta** [comment]
PR #5907 cleans up obvious bugs with EVAC and MEAN_FORCING. However, I still get the errors:
```
ERROR: Memory allocation failed for Evac ZZ in the routine MAIN (CHID: wind_example)

ERROR: Memory allocation failed for Evac RHO in the routine MAIN (CHID: wind_example)

ERROR: Memory allocation failed for Evac RSUM in the routine MAIN (CHID: wind_example)

ERROR: Memory allocation failed for Evac TMP in the routine MAIN (CHID: wind_example)

ERROR: Memory allocation failed for Evac UII in the routine MAIN (CHID: wind_example)
```

**Comment by tkorhon1** [comment]
Well, I just did git remote update and also downloaded the wind_example. So, I'll try to see this also.

TimoK

**Comment by tkorhon1** [comment]
Well, I did not get an error message, when using debug mode (mpi_intel_linux_64_db).

Fire Dynamics Simulator

Current Date     : January 26, 2018  16:29:57
Version          : FDS 6.6.0
Revision         : FDS6.6.0-792-gf72ca19
Revision Date    : Thu Jan 25 20:36:38 2018 -0500
Compiler         : Intel ifort 17.0.0
Compilation Date : Jan 26, 2018  16:27:25

MPI Enabled;    Number of MPI Processes:       9
OpenMP Enabled; Number of OpenMP Threads:      4

MPI version: 3.0
MPI library version: Open MPI v1.8.3, package: Open MPI tstopi@espvm5m030.ad.vt
.fi Distribution, ident: 1.8.3, Sep 25, 2014

Job TITLE        : Test of z-profile mean velocity ramp for one-way WRF couplin
 with FDS
Job ID string    : wind_example_new

 Time Step:    -49,    Evacuation Initialization Time:    -0.490 s
 Time Step:      1, Simulation Time:      0.54 s
 Time Step:      2, Simulation Time:      1.08 s
 Time Step:      3, Simulation Time:      1.62 s
 Time Step:      4, Simulation Time:      2.16 s
 Time Step:      5, Simulation Time:      2.70 s
 Time Step:      6, Simulation Time:      3.24 s
 Time Step:      7, Simulation Time:      3.78 s
 Time Step:      8, Simulation Time:      4.33 s
 Time Step:      9, Simulation Time:      4.87 s

And still running. I did compile and run 4 days ago and I got the same thing, i.e., no error messages.
(I ran it for the total 60s = T_END)

Timo

**Comment by mcgratta** [comment]
My mistake. The case posted above works when I designate 9 MPI processes, but fails with the memory allocation error if I designate 8 MPI process. There are 8 fire meshes and 1 evac mesh. I assume that this is the way Evac cases are to be run. If not, open up the issue again.
