### ISSUE TITLE
Specifying 180 degree Elevated Sprinkler Spray

### ISSUE THREAD

**Issue by smustafa3** [firemodels/fds#5909]
Issues with creating uniform trajectory in horizontal plane (180 degree rotation) with a single 2.25 degree band in the vertical direction. I ran a test case previously checking the trajectory with a one-degree band (89 to 90 degrees) and verified that the FDS inputs for specifying the elevation angle and horizontal angle are correct (results showed the desired trajectory):

<img width="1373" alt="screen shot 2018-01-16 at 2 59 02 pm" src="https://user-images.githubusercontent.com/35572495/35109726-29ea1b82-fc45-11e7-9961-2c550a5ba3d0.png">

Test case is attached where 5 one-degree bands at equal spacing in the 180 degree span are checked. 

<img width="871" alt="screen shot 2018-01-18 at 11 51 48 am" src="https://user-images.githubusercontent.com/35572495/35110087-01e771ce-fc46-11e7-8114-bf1685e599dd.png">

<img width="1348" alt="screen shot 2018-01-18 at 11 53 17 am" src="https://user-images.githubusercontent.com/35572495/35110194-3644d678-fc46-11e7-8cc4-d98e73f92f9d.png">

At 0-1 degree and 179-180 degrees, there is no change in elevation found in the results (the particles run along a straight line on z_min). 
Similarly for bands tested that are located at less than 45 degrees along the 180 degree span, the desired elevation is not reached, droplets seem to be discharged to lower than the specified 2.25 degrees (this is from testing 9 bands instead of just 5, all equally spaced along the 180 degree horizontal plane). 
The 2.25 degree elevation seems to be reached perfectly at the 89-90 degree band.

The test case file that is attached has gravity turned off and uses a low flow rate and velocity to reduce entrainment effects.

The spray objective is shown in the following image. 
<img width="1034" alt="screen shot 2018-01-18 at 9 11 10 am" src="https://user-images.githubusercontent.com/35572495/35109309-fa015544-fc43-11e7-900b-662264071b22.png">

[Sprinkler Test 38.txt](https://github.com/firemodels/fds/files/1643640/Sprinkler.Test.38.txt)

**Comment by drjfloyd** [comment]
I see your issue now.  The TABL entries are for a coordinate system centered on the ORIENTATION. 

&TABL ID='Low flowrate test, 5 rows_SPRAY_PATTERN_TABLE', TABLE_DATA=0.0,1.0,266.75,267.75,1.524,0.2/

This entry says inject a particle at a latitude of 0 to 1 degree from the normal vector of the orientation with a longitude of 267 degrees. Since a latitude of 0 to 1 degree is essentially the axis of the sprinkler, the longitude isn't going to have any noticeable effect.  Instead keep your sprinkler pointed downward (0,0,-1).  Make the latitude 92 to 92.5. and then the longitude the 1 degree increments over 180 degrees.

**Comment by smustafa3** [comment]
Thanks for the explanation and recommendations. 

I understand how the latitude and orientation work in the different orientations, but still don't understand why there wouldn't be any noticeable effect when the (1,0,0) orientation is used for the lat slice of 0 to 1 and long at 267. Shouldn't there still be particles filling space in the vertical direction on the 0 to 1 band, even though it's in line with the normal of the sprinkler orientation?

**Comment by drjfloyd** [comment]
Picture that the axis of your sprinkler is from the north pole to the south pole on a globe.

Go to 0.5 degrees of latitude up from the south pole and 267 degrees of longitude. You are still just shooting the particle very close to the axis.  

Go to 90 degrees of latitude up from the south pole and 267 degrees of longitude. Now you are shooting the particle 2.5 degrees out of plane.

**Comment by smustafa3** [comment]
Ok, this makes much more sense. Thank you!
