### ISSUE TITLE
Evacuation: Weird behaviour after adding OBSTs

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#5916]
@tkorhon1 

Find a simplified case from an issue reported by a user in discussion group, can be found[ here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/DCklM8zLrVA/_ZzHoTnPEwAJ): 

[cuarto.fds.txt](https://github.com/firemodels/fds/files/1644863/cuarto.fds.txt)

The problem is coming from the added OBST. Z is only 0.1m. But, it's taken as it's the Z of the mesh.

**Comment by tkorhon1** [comment]
This is not a bug. This is a feature of FDS+Evac. It is written (or at least is should be) in the FDS+Evac guide, that every OBST that has z coordinate (or part of its z coordinates) within the z range of evacuation mesh XB will end up in the evacuation mesh. This means that the whole z range of an evacuation mesh will be filled with that OBST. The evacuation mesh has just one cell in the z direction. So, if there is an OBST there, it fills this one grid cell in the z direction. This is even true, if the OBST only touched the z boundary of the evacuation mesh. 

You can add EVACUATION=.FALSE. on  the OBST namelist so this OBST is not read in by the evacuation meshes, if you want. But a better way would be change the XB of the evacuation mesh. The XB z level should be such that everything with this z range will prevent walking. A good choice would be, say, something like z_min=20 cm above the floor, and z_max about 180 cm above the floor. If you are 2m tall, you can bend a little bit and go under the obsts at 1.8 height from the floor. 

See the figure 34 (page 74) in the FDS+Evac guide:
![image](https://user-images.githubusercontent.com/13029521/35211592-ca2cda04-ff5f-11e7-9e1c-8b3b1293ee3c.png)

TimoK

**Comment by sbenkorichi** [comment]
Thanks Timo, that makes sense.
