### ISSUE TITLE
Numerical Instability in 1D pyrolysis case with MIRROR boundaries

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5920]
This is a quadrant of the FAA polymers case.

[FAA_Polymers_PMMA_1D_mirror.fds.txt](https://github.com/firemodels/fds/files/1647423/FAA_Polymers_PMMA_1D_mirror.fds.txt)

This is a 16 mesh case.  Instability occurs around 48 s in the simulation.

![faa_polymers_pmma_1d_mirror_s0000](https://user-images.githubusercontent.com/4418497/35163551-26250d6a-fd15-11e7-9b08-a06f0d5f9994.png)

**Comment by mcgratta** [comment]
In this case, the mirror boundary was specified via
```
&VENT MB='XMIN', SURF_ID='MIRROR' /
```
For a multi-mesh case, this BC is applied to the left face of all meshes. The instability occurs where an obstruction abuts a mesh boundary, and the MIRROR boundary is applied to it. Not good. I added some code to prevent this from happening. A MIRROR cannot be applied to an interpolated mesh boundary.

**Comment by rmcdermo** [comment]
Thanks for looking at it!
