### ISSUE TITLE
Docs refer to score-p filter file but does not currently exist

### ISSUE THREAD

**Issue by deleeke** [firemodels/fds#5921]
Feel free to close if you like, but I came upon your repo when in search of an example score-p filter file.

I did find the file [referred to in your wiki](https://github.com/firemodels/fds/wiki/FDS-Profiling-and-Tracing), but had to search pretty far back in the history (I just went back until about the time the article was published). [This is the file I'm referrering to](https://github.com/firemodels/fds/blob/99eae5efb5502950916dbb80bc3519a5b913fb65/Utilities/Profiling/scorep_include.filt)

Might want to link to it in the wiki, it was instantly helpful for me, so I'm glad it existed at some point!

**Comment by mcgratta** [comment]
I have not had a chance to do more with score-p. I appended the wiki with the filter file. Thanks for finding it. I would be interested if you can find a nice viewer for the trace files. I used a test license for vampir, but I have not had time to figure out how to get a full license for it. The vampir developers were not particularly helpful in that regard. If you can find a good trace viewer, let me know.

**Comment by deleeke** [comment]
I will follow up if I do, I just started working with it after spending the last couple months working with HPCToolkit, which provides similar functionality but I hit enough usability bumps in the road that I wanted to at least try score-p out. 

So far I'm pretty pleased with the profile viewer, cube, but have not tried looking at the trace yet.

**Comment by mcgratta** [comment]
I used score-p and vampir to trace a 16 process case, but my trial license was limited to 16 processes. I liked the interface, but could not figure out how to buy a license for vampir. It's as if they only deal with institutions instead of individuals. The trace viewer is really important to show where our MPI bottlenecks and wasteful calls are. I just have not had time  to pursue all the different packages that are out there, and none that I looked at seemed user friendly.

**Comment by deleeke** [comment]
All of HPCTookit's tooling is free, though has some fundemental differences as it is "samping" based instead of instrumented like score-p. Perfectly capable of consuming traces of 300+ MPI ranks but it lacks much in the way of "labels", but they are responsive on the mailing list.

One thing that was confusing for me is it also shows traces of the MPI helper threads, I'm not sure if that is normal. You can filter out what threads/ranks you want to see.

The trace viewer is free and they thankfully distribute pre-built binaries of it.

**Comment by deleeke** [comment]
Looks like a free alternative that can read the OTF2 files is [scalasca](http://www.scalasca.org/software/scalasca-2.x/download.html), by the same people that make the cube profile viewer. And, like cube, it is available to the Fedora package manager. 

I'll let you know how it goes.

**Comment by mcgratta** [comment]
Any additional info on this issue?
