### ISSUE TITLE
BURN_AWAY for PYRO3D

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5925]
Burn away cases for 3D pyrolysis routines.  Each of these cases have problems to work out.  One hangs in HT3D and one does not burn away after the top layer burns out.  I expect these problems are related.

[box_burn_away1_pyro3d.fds.txt](https://github.com/firemodels/fds/files/1648107/box_burn_away1_pyro3d.fds.txt)

[FAA_Polymers_PMMA_3D_burnaway.fds.txt](https://github.com/firemodels/fds/files/1648108/FAA_Polymers_PMMA_3D_burnaway.fds.txt)

**Comment by rmcdermo** [comment]
Kevin,
We were able to get an extension of the paper.  But this puts us in a position that we need to get past this hump of burn_away with pyro3d.  I'm anticipating needing your help on this.  Again, the issue that newly created WALL CELLS seem to have a NULL_BOUNDARY assignment after the first layer burns away.

**Comment by mcgratta** [comment]
I got it. We overwrite `WALL_INDEX` in the blockages, and hence there's no memory of the wall index of the newly exposed wall cells. Will fix.

**Comment by mcgratta** [comment]
Fixed the PMMA example. Will try other one too.

**Comment by mcgratta** [comment]
Yes, the simple box case works too.
