### ISSUE TITLE
Suppressed Fire - low HRR

### ISSUE THREAD

**Issue by StudentGermany** [firemodels/fds#5929]
Hey everyone. 
I have a problem with my natural fire simulation. I have calculated a heat release rate function for my fire according to German standards. However I get a reduced HRR from the one I put into my .fds-file. I have posted this problem in the google forum before and checked everyones ideas, so I know that the reason for this problem is NOT: 
- too little O2. The amount present is constant throughout the simulation. If you check the model, it has big openings on each side, so it's really NOT O2 deficiency.
- too little fire load. I have checked that as well. The amount present assumes the function of the HRR
- The problem can't not be solved by using SUPPRESSION=.FLASE. in &MISC as well.

I'm really out of ideas, why my fire has a reduced heat release and therefore temperature. Has anyone of you maybe an other idea. I'm relive new to FDS so I'm still inexperienced.

THANKS for your help. 

PS I have attached my input. The HRR is supposed to reach 60 MW after 184 s. Could, maybe, the problem be, that it's too quick for FDS to develop?
[60MW.txt](https://github.com/firemodels/fds/files/1650289/60MW.txt)

**Comment by drjfloyd** [comment]
You have unburned fuel leaving the domain:

Your 60 MW fire has a flame height on the order of 18 m
Your domain is 8 m tall
Your fire is 2 m from the edge of the domain
2 m + 8 m = 10 m.  10 m < 18 m.  
You do not have enough distance for all the fuel to mix with air before it leaves the domain.
