### ISSUE TITLE
Error OpenGl

### ISSUE THREAD

**Issue by sofikou** [firemodels/fds#5931]
I started using Pyrosim about 6 months ago to use it for my master thesis.
I manage to finish a complex geometry and skip the first error messages
that some holes were detected on the boundary mesh. But after fixed all
the following error appeared:

*** GUP smoke volume shader failed to load.
*** GUP 3d slice shader failed to load.
GUP shader initialization failed.

Could you please explain what these messages mean?
Also find attached the .psm file

Thank you very much in advanced.

**Comment by gforney** [comment]
Just a warning from smokeview saying that either you do not have a GPU or
that the GPU you do have is not supported . Smokeview will still work using
CPU algorithms.

**Comment by bwklein** [comment]
@sofikou If you scroll up in the simulation output dialog, where you saw that message about GUP, you will see that before that message it gave you the following FDS error messages.
` Mesh 1 is assigned to MPI Process 0
WARNING: MATL FOAM, REAC 1. No product yields (NUs) set
ERROR: OPEN, MIRROR, OR PERIODIC VENT 3 must be an exterior boundary. (CHID: drawing_try)
MPI process      0 has completedSTOP: FDS was improperly set-up (CHID: drawing_try)
STOP: FDS was improperly set-up (CHID: drawing_try)
`
1) Make sure you are using the most recent release of PyroSim
2) Fix the issues with the Reaction and the Vent boundary condition.
