### ISSUE TITLE
Synthetic turbulence with HVAC

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#5934]
At the FDS workshop in November, I mentioned that models with HVAC vents with synthetic turbulence would run, but to no effect. (That was with FDS 6.3). In FDS 6.6 an error message appears indicating, "Synthetic Eddy Method not permitted with HVAC".

Please add that to the wish list.

Thanks

Dave

**Comment by rmcdermo** [comment]
Dave,
We will look at this.  But I recall having a discussion with Jason about this some time ago and I thought there was a good reason we did not add SEM to HVAC at the time.  Maybe Jason remembers.

**Comment by drjfloyd** [comment]
My recollection was a few of things.

HVAC vents are generally louvered or covered with a perforated mesh that is likely to have a much smaller length scale than the computational grid. The large scale structures that might exist in the duct (and potentially be somewhat resolved on the computational grid) are going to be effected by this.  
In a typical engineering simulation, there is not going to be many grid cells over the length/width of an HVAC vent. The SEM model may not give much benefit in that case. 
We didn't have any guidance to give on how to specify inputs.
It wasn't a high priority item.

**Comment by Dave-McGill** [comment]
Jason and Randy,

That's fair enough. There's no point in you spending time if you think it will be of little value.

Thanks

Dave
