### ISSUE TITLE
synchronization issue with smokeview or fds?

### ISSUE THREAD

**Issue by brannman** [firemodels/fds#5938]
![fdssmvmpi](https://user-images.githubusercontent.com/35769939/35335689-26752e4c-010e-11e8-92ac-c905572ec22a.JPG)
[circular_burner2.fds.txt](https://github.com/firemodels/fds/files/1660075/circular_burner2.fds.txt)

Is there a synchronization issue with smokeview or FDS? I ran the test problem divided up into 5 vertical meshes stacked on top of one another. Viewing the results in Smokeview appear to show a lack of synchronization at the mesh boundaries (horizontal lines every 5th of the way up).

Running on Intel Xeon CPU, 12 cores, 24 logical processors. Windows 10 Pro version 1709, OS build 16299.192

Strangely enough, all the meshes seem to be assigned to the same process, but it ran 7x faster than with using only a single mesh... Result file and input file attached.

Mesh 1 is assigned to MPI Process 0
 Mesh 2 is assigned to MPI Process 0
 Mesh 3 is assigned to MPI Process 0
 Mesh 4 is assigned to MPI Process 0
 Mesh 5 is assigned to MPI Process 0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : January 24, 2018  15:09:46
 Version          : FDS 6.6.0
 Revision         : FDS6.6.0-131-g88ae75a-HEAD
 Revision Date    : Wed Nov 1 16:03:29 2017 -0400
 Compiler         : Intel ifort 17.0.4.210
 Compilation Date : Wed 11/01/2017  09:03 PM

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.0
 MPI library version: Intel(R) MPI Library 5.1.3 for Windows* OS

 Job TITLE        : Test the mass flow rate from a circular burner
 Job ID string    : circular_burner

 Time Step:      1, Simulation Time:      0.08 s
 Time Step:      2, Simulation Time:      0.16 s
 Time Step:      3, Simulation Time:      0.24 s
 Time Step:      4, Simulation Time:      0.32 s

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
This appears to be caused by the averaging of the data at cell corners from the eight adjacent cells. When at the edge of the computational domain, one or two of the eight adjacent values is not calculated because they are outside the domain. I'll see if there is a way to exclude these values from the average. In the meantime, put your slice at y=-0.1, away from the edge of the domain.

**Comment by brannman** [comment]
Thank you Kevin. I will note that there appears to be a mismatch in the 3D view of smoke and HRR as well.

**Comment by mcgratta** [comment]
This should be better in the next release.
