### ISSUE TITLE
Possible bug in combustion routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#5939]
In the following case, shouldn't the METHANOL mole fraction drop to zero in the first time step (0.0001 s)? I am trying to better understand the role of time step and `N_FIXED_CHEMISTRY_SUBSTEPS`. This is a variation of the verification case `reactionrate_fast_slow.fds`.
```
&HEAD CHID='junk', TITLE='Trial CO reaction scheme' /

&TIME T_END=0.001, DT=0.0001 /

&MESH XB=-0.5, 0.5,-0.5,0.5,-0.5, 0.5, IJK=20,20,20 /

&MISC N_FIXED_CHEMISTRY_SUBSTEPS=10, INITIAL_UNMIXED_FRACTION=0., SUPPRESSION=.FALSE. /

&SPEC ID='NITROGEN', BACKGROUND=.TRUE./
&SPEC ID='METHANOL', MASS_FRACTION_0=0.0563 /
&SPEC ID='OXYGEN', MASS_FRACTION_0 = 0.0675 /
&SPEC ID='CARBON MONOXIDE', MASS_FRACTION_0 = 0.0 /
&SPEC ID='WATER VAPOR', MASS_FRACTION_0=0.0/
&SPEC ID='CARBON DIOXIDE', MASS_FRACTION_0 = 0.0 /

&REAC ID = 'R1', ODE_SOLVER = 'EXPLICIT EULER'
      FUEL = 'METHANOL'
      SPEC_ID_NU='METHANOL','OXYGEN','CARBON MONOXIDE','WATER VAPOR'
      NU= -1.,-1.,1.,2. /

&REAC ID = 'R2'
      FUEL = 'CARBON MONOXIDE'
      SPEC_ID_NU='CARBON MONOXIDE','OXYGEN','CARBON DIOXIDE'
      NU= -1,-0.5,1
      A = 10000000000
      E = 0.
      SPEC_ID_N_S = 'CARBON MONOXIDE','OXYGEN'
      N_S = 1.0, 1.0 /

&SLCF PBY=0.001, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.001, QUANTITY='VOLUME FRACTION', SPEC_ID='OXYGEN', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.001, QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON DIOXIDE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.001, QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON MONOXIDE', CELL_CENTERED=.TRUE. /
&SLCF PBY=0.001, QUANTITY='VOLUME FRACTION', SPEC_ID='METHANOL', CELL_CENTERED=.TRUE. /

&SURF ID='WALL', DEFAULT=.TRUE., ADIABATIC=.TRUE., COLOR='GRAY 20' /

&DEVC ID='O2',    XYZ=0.,0.,0., QUANTITY='VOLUME FRACTION', SPEC_ID='OXYGEN', TIME_AVERAGED=.FALSE. /
&DEVC ID='CO2',   XYZ=0.,0.,0., QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON DIOXIDE', TIME_AVERAGED=.FALSE. /
&DEVC ID='CO',    XYZ=0.,0.,0., QUANTITY='VOLUME FRACTION', SPEC_ID='CARBON MONOXIDE', TIME_AVERAGED=.FALSE. /
&DEVC ID='CH3OH', XYZ=0.,0.,0., QUANTITY='VOLUME FRACTION', SPEC_ID='METHANOL', TIME_AVERAGED=.FALSE. /

&TAIL /
```

**Comment by drjfloyd** [comment]
While looking into this I discovered that in read.f90 we are setting ODE_SOLVER = 'null' in the read_reac loop. So it is getting reset to 'null' which then causes it to shift to the Richardson solver.  We should only be setting it once before we start reading reactions. 

The reaction routine is fully consuming the mass in a single timestep. However, in the combustion routine we set M_DOT_PPP to the mass production for the reaction.  This value is used in the DENSITY predictor step which happens after we output the global devices.  So the result of the reaction is being delayed one timestep.

**Comment by mcgratta** [comment]
OK, but why does fuel and oxygen decrease a bit at 0.001 s, but CO and CO2 remain at zero?

**Comment by drjfloyd** [comment]
The mass fraction hasn't changed.  But at the end of the combustion routine where we set M_DOT_PPP we are also updating RSUM which is used in converting mass fraction to volume fraction. CO and CO2 don't change since 0 mass fraction times a conversion factor is still zero.  I guess we probably shouldn't be updating rsum here? We aren't doing it in the particle routines when we update M_DOT_PPP. I think that RSUM is left over from when we used to set ZZ in the combustion routine before we changed it to setting M_DOT_PPP.

**Comment by drjfloyd** [comment]
I  think the fixes are move the ODE_SOLVER ='null' in read,f90 and change the RSUM(I,J,K) in the main combustion loop to an RSUM_TEMP.  I'll try this and run some of the verification cases.

**Comment by rmcdermo** [comment]
Sounds good.  Let's use RSUM_LOC for consistency with other local variables.

**Comment by rmcdermo** [comment]
I always get TMP, TEMP, temporary, temperature, etc., confused.

**Comment by drjfloyd** [comment]
Good point. I will use RSUM_LOC.

**Comment by drjfloyd** [comment]
Should be fixed. I tested a number of the reaction cases in species.

The only one that didn't seem to work was the jones_lindset, but that also doesn't seem to work for the current release.

**Comment by rmcdermo** [comment]
That case is more just saving the mechanism for future development.  I'd say that level of mechanism needs much more testing.

**Comment by mcgratta** [comment]
Appears to be working. Thanks.

**Comment by mcgratta** [comment]
I discovered something else that is curious, and maybe it's my misinterpretation. Take the test case I posted above and run it with 0, 10, 100, and 1000 `N_FIXED_CHEMISTRY_SUBSTEPS`. I do not see the time histories of the volume fractions converging. I assume that all this does is break up the time step into smaller and smaller intervals.

**Comment by drjfloyd** [comment]
If I up A for the second reaction by a factor of 1000, then the 1000 case matches the 1 case.  Offhand, I'm not sure if this is something we expect or not.

**Comment by mcgratta** [comment]
I don't think so. The number of sub-steps ought to improve accuracy, but not change the analytical solution.

**Comment by drjfloyd** [comment]
I see the issue. There are two variables that control the integration: N_FIXED_* and MAX_*.  MAX_*=20. So when we increase N_FIXED_* > 20 we use a smaller timestep, but stop integrating after 20 steps.   I think what we want when we fix the iterations is for the max permissible to be the same as the fixed value.  If I fix that then after the first timestep the CO2 values are:
Iteration, CO2
1,0.0310
2,0.0222
10,0.0189
100,0.0183
1000,0.0183

So they are converging.  I'll push this up.

**Comment by mcgratta** [comment]
Works! Thanks.
