### ISSUE TITLE
FDS don't output data in CHID_devc.csv and don't creat CHID_line.cvs

### ISSUE THREAD

**Issue by elmadrab** [firemodels/fds#5953]
[radiation_test_1.txt](https://github.com/firemodels/fds/files/1667746/radiation_test_1.txt)
[radiation_test_devc.xlsx](https://github.com/firemodels/fds/files/1667747/radiation_test_devc.xlsx)
[radiation_test_hrr.xlsx](https://github.com/firemodels/fds/files/1667748/radiation_test_hrr.xlsx)

Hello,

the use of RADIATIVE HEAT FLUX GAS with POINTS is causing the problem.

Here's the link to the discussion in the group : [https://groups.google.com/forum/#!topic/fds-smv/9bWK0BSASxc](url)
@drjfloyd why we can't use POINTS with RADIATIVE HEAT FLUX GAS ?

Thank you

**Comment by drjfloyd** [comment]
Kevin,

In the guide writeup, it implies that POINTS should work with RADIATIVE HEAT FLUX GAS.  It isn't.  Not sure if this is just poor wording in the guide or a bug.

**Comment by mcgratta** [comment]
I think it does. This is how we do the `Fleury_Heat_Flux` validation cases. I'll take a look at this.

**Comment by mcgratta** [comment]
Do this:
```
&DEVC ID='Tot_Flux_HFG', QUANTITY='RADIATIVE HEAT FLUX GAS', XB=1.95,1.95,0.5,0.5,0.05,0.95, POINTS=18, ORIENTATION=-1,0,0 /
```
Do not embed a `GAS` heat flux gauge in a solid wall, and use `ORIENTATION`, not `IOR`.

**Comment by sbenkorichi** [comment]
Kevin,
I thought has been fixed. Please review the response of this thread. 
https://github.com/firemodels/fds/issues/4525

**Comment by mcgratta** [comment]
I think it is. Check it. The problem was really the embedding of gas phase devices.

**Comment by sbenkorichi** [comment]
Yes, I have checked and it's working.
I didn't notice it was attached to the solid. Good catch. 
Even for the IOR it should work with it now.

**Comment by elmadrab** [comment]
Thank you guys ! 

it's worked with ORIENTATION  and It's also worked with IOR.

**Comment by elmadrab** [comment]
You should clarified it in the user guide that it possible to use RADIATIVE HEAT FLUX GAS with POINTS ?

**Comment by mcgratta** [comment]
Done
