### ISSUE TITLE
Mass conservation in PYRO3D with BURN_AWAY

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5954]
Attached case does not conserve MATL mass.

[box_burn_away1_pyro3d.fds.txt](https://github.com/firemodels/fds/files/1667947/box_burn_away1_pyro3d.fds.txt)

This is the script I use to integrate under the curve.

[plot_mlr.m.txt](https://github.com/firemodels/fds/files/1667950/plot_mlr.m.txt)

**Comment by mcgratta** [comment]
Is this still an issue?

**Comment by rmcdermo** [comment]
I'm pretty sure not.  Let me rerun that case quickly.

**Comment by rmcdermo** [comment]
Kevin,
The output for M_DOT_S_PPP seems fine for residuals, true.  But I was expecting the following two expressions to be equivalent coming out of the PYROLYSIS routine, but they are not.  The second one does not give me the right mass.  If that is expected from you, then I will simply use the first expression, and you can close this issue.

```
! debug: these two expressions should be the same
OB%RHO(I,J,K,1:MS%N_MATL) = MAX(0._EB, OB%RHO(I,J,K,1:MS%N_MATL) &
                                                   + (RHO_OUT(1:MS%N_MATL)-RHO_IN(1:MS%N_MATL)) * RVSP(I,J,K) )

! OB%RHO(I,J,K,1:MS%N_MATL) = MAX(0._EB, OB%RHO(I,J,K,1:MS%N_MATL) &
!                                        - DT_SUB * M_DOT_S_PPP(1:MS%N_MATL) * RVSP(I,J,K) )
```

**Comment by mcgratta** [comment]
The sign in your commented line should be positive. If component A reacts to form B, its `M_DOT_S_PPP` will be negative. A positive `M_DOT_S_PPP` indicates an increase in the mass of component alpha, like if it is a residual.

**Comment by rmcdermo** [comment]
OK, that works.  This problem is not perfect yet.  But I think we have more subtle things to work out in the 3d case.
