### ISSUE TITLE
COMM for HT3D seems very high

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5962]
Checkout this case and see if you can reproduce what we saw in my office.

[FAA_Polymers_PMMA_3D_40.fds.txt](https://github.com/firemodels/fds/files/1673838/FAA_Polymers_PMMA_3D_40.fds.txt)

![comm](https://user-images.githubusercontent.com/4418497/35514859-8c20f95e-04d5-11e8-9789-19fb80d72cc9.png)

**Comment by mcgratta** [comment]
My mistake. The bar chart shows the CPU time of MPI process 0, the process controlling the mesh in the corner of the domain. This mesh has no surface or solid boundaries, so while all the other processes work on conduction and pyrolysis, this process sits in the communication routine just waiting. Hence, it appears like it's spending alot of time communicating when it is just idle.
