### ISSUE TITLE
Is thermophoretic transport accounted for in the bulk?

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#5974]
Jason,

Amy Mensch is using the deposition model to for an experiment with a linear temperature gradient across a channel.  In looking at the guides (tech and user) it appears that the model is only applied for wall cells.  Is that correct?  If so, how hard would it be to include in the bulk?

Thanks,
Randy

**Comment by drjfloyd** [comment]
Yes it is only applied for the walls.

I think we could just extend the existing drift flux approach for gravitational settling in the bulk to include a thermophoretic term. I think the added expense would be marginal.

**Comment by rmcdermo** [comment]
Could you put this on your to-do?  Amy is using the model for smoke detection, which I think is a good example of using FDS.  She has 10 cells across a channel that is slow laminar flow, so turbulent transport does not dominate as it normally would.  There is a slow drift due to diffusion, but it not matching data well.

**Comment by drjfloyd** [comment]
will do. I don't think this is a huge effort.

**Comment by drjfloyd** [comment]
I modified the gravitational routine to include settling. The images below are for a case with 0.5 micron particles in a 1 m^3 box with a 500 C top and 0 C bottom (sides adiabatic).  Top = gravity only, middle -both, bottom = thermophoretic only.  Behavior seems right. In gravitational only, everything uniformly starts to settle. The image shows a fairly constant settling gradient. In thermophoretic only, it takes time for a temperature gradient to form over the full height, so initially it only happens at the top. The image shows soot has mostly just been pushed down from the top.  Both shows both behaviors.  

I want to do a little more testing (make sure I have it working for x and y gradients as well), but think I'll have the source pushed up soon.

![settling_g_1000](https://user-images.githubusercontent.com/12799217/35748547-5fa197ea-081c-11e8-8bc3-b5f3645df271.png)
![settling_b_1000](https://user-images.githubusercontent.com/12799217/35748548-5fb36cae-081c-11e8-8885-6901da9057ff.png)
![settling_t_1000](https://user-images.githubusercontent.com/12799217/35748549-5fc34700-081c-11e8-9700-2718b5875a7c.png)

**Comment by drjfloyd** [comment]
New source pushed up.

**Comment by drjfloyd** [comment]
In emails outside of git, this is being used by the OP. Closing the issue.
