### ISSUE TITLE
AST-RANGE-COLORBAR

### ISSUE THREAD

**Issue by mirtaninil** [firemodels/fds#5982]
[AST-RANGE-COLORBAR.txt](https://github.com/firemodels/fds/files/1692100/AST-RANGE-COLORBAR.txt)
![problem ast colorbar](https://user-images.githubusercontent.com/36108565/35770703-6a7676ae-0920-11e8-980e-ed6b2be8c534.PNG)

Hi all,
I have a problem in the visualization of the colorbar in smokeview. As you can see in the figure attached if I visualize the AST BNDF the colorbar values start from -270 °C. It seems that fds is sending to smokeview the value  -270°C. This problem disappears if I run just the mesh where is placed the burner. Instead if I run more than one mesh this problem in the colorbar starts again. 

I have attached a shorter version of my file where I can still see the problem.

Thank you in advance for your help

**Comment by mcgratta** [comment]
This should be fixed in the next release. Thanks for submitting it. The problem was that FDS was sending in AST values for the boundary between the two meshes when it has no meaning there.
