### ISSUE TITLE
Vertical temperature profile

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#5998]
The figure 10.1 in FDS_User_Guide.pdf (10.1 Wind method 1: Monin-Obukhov Similarity) shows sample for the vertical wind and temperature profile.

![sample](https://user-images.githubusercontent.com/27724706/35964293-980f8ca0-0cb7-11e8-9e79-6f8c3e14f8f1.png)

As seen in the attached files I did a run for this situation:
u,ref (2m) = 5m/s
L = -350 m
z0 = 0.005 m

**Fig. 1:**
![t1](https://user-images.githubusercontent.com/27724706/35964361-d49b017c-0cb7-11e8-8693-d315b2279504.png)

In Fig. 1 the height of the mesh is 30 m. The temperature profile varies with the height of about 0.2°C. 

**Fig. 2:**
![t2](https://user-images.githubusercontent.com/27724706/35964821-2c29ea92-0cb9-11e8-9d8d-0498faa13e81.png)
 
In Fig. 2 the heigth of the mesh is 300 m. Fig. 2 shows, that the temperature difference is near the same as in Fig. 1

In both cases the temperature profile vary with the height of about 0.2°C. At 300 m heigth I would expect a temperature of about 17-18°C.  Is there an error in the input file ?

[wind_fds.txt](https://github.com/firemodels/fds/files/1706400/wind_fds.txt)

Thanks
Herbert

**Comment by mcgratta** [comment]
[wind.PDF](https://github.com/firemodels/fds/files/1707600/wind.PDF)

Do not use Smokeview for this. Your color bars are not consistent. Add a line like this
```
&DEVC ID='T(z)',QUANTITY='TEMPERATURE', POINTS=30, XB=25,25,0,0,0.5,29.5 /
```
and you'll see results like those I've reported in the figure.
