### ISSUE TITLE
HVAC REVERSE not working

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6003]
I noticed that setting `REVERSE `parameter `.TRUE.` or` .FALSE.` does not change the direction. Could you please take a look?

Thank you. 

### 

&HEAD CHID='REVERSE'/
&TIME T_END=600.0/
&DUMP DT_SLCF=1.0/

&MESH ID='Mesh01-a-a04', IJK=38,6,30, XB=92.0,107.2000000000002,9.0,12.0,7.166667,13.166666979984/
&TRNZ CC=8.3666669959968, PC=9.16666698, MESH_NUMBER=1/ 

&OBST ID='Jetfan-body', XB=99.2000000000002,100.8000000000002,10.5,11.5000000000001,9.500000640004,10.16666697/ 

&VENT ID='Vent1_zuid', SURF_ID='HVAC', XB=100.8000000000002,100.8000000000002,10.5,11.5,9.50000100001,10.16666700001/ 
&VENT ID='Vent1_noord', SURF_ID='HVAC', XB=99.2000000000002,99.2000000000002,10.5,11.5,9.50000100001,10.16666700001/ 
&VENT ID='OPEN', SURF_ID='OPEN', XB=107.2000000000002,107.2000000000002,-2.003731E-12,12.0,6.833334,12.833334/ 
&VENT ID='OPEN2', SURF_ID='OPEN', XB=92.0,92.0,3.552714E-15,12.0,8.166667,14.166667/ 

&HVAC ID='Fan1_noord', TYPE_ID='NODE', DUCT_ID='Fan1', VENT_ID='Vent1_noord'/
&HVAC ID='Fan1_zuid', TYPE_ID='NODE', DUCT_ID='Fan1', VENT_ID='Vent1_zuid'/
&HVAC ID='Fan1', TYPE_ID='DUCT', DIAMETER=0.92, VOLUME_FLOW=2.0,  NODE_ID='Fan1_noord','Fan1_zuid',  ROUGHNESS=1.0E-3, LENGTH=1.6, **REVERSE=.TRUE.**/

&SLCF QUANTITY='VELOCITY', VECTOR=.TRUE., PBY=11.0/

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
The issue is the description in the User's Guide.  REVERSE is only meant to apply to a FAN in a duct and I did not correctly define that input when I wrote the guide.  This way one fan type could be used in multiple ducts and still get the correct flow direction.  In your case just make the VOLUME_FLOW negative.  I'll update the guide to have the correct definition.

**Comment by Er9y714** [comment]
Thank you.

Maybe it would be safe to have an error in FDS when REVERSE is used with DUCT.

**Comment by drjfloyd** [comment]
I modified the definition of REVERSE in the guide to note that it only applies when a FAN is being used and not if it is just a duct with VOLUME_FLOW or MASS_FLOW.  https://github.com/firemodels/fds/commit/65c12d8f16e9636d9f4e3561341ddb17981596f4
