### ISSUE TITLE
memlock can't be set to unlimited in torque script

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6023]
Glenn,

one problem that I couldn't pass is getting memlock to unlimited inside the job scheduler.
I've already made the necessary changes in the /etc/security/limits.conf
on terminal, either user or root, it would return `$ unlimited`
But, for some reason when I put ulimit -a or ulimit -l inside the script to check what it throws in the .log,
it would return 64 instead of unlimited.

```
[0] DAPL startup: RLIMIT_MEMLOCK too small
[1] DAPL startup: RLIMIT_MEMLOCK too small
```

Something is  wrong somewhere and I can't seem to find it. I will keep looking though.

**Comment by sbenkorichi** [comment]
It seems to be there is a way to modify the pbs_mom to set it to unlimited. 
`# vim /etc/rc.d/init.d/pbs_mom`
and add : 

```
ulimit -l unlimited
ulimit -s unlimited
```
However, my OS distribution is a bit different. I will find where it's located to modify it to see if it helps.

**Comment by gforney** [comment]
this is what we have in our /etc/init/pbs_mom startup script . Note, if you change this file you'll need to run
/etc/init.d/pbs_mom restart

ulimit -n 32768
# max locked memory, soft and hard limits for all PBS children
ulimit -H -l unlimited
ulimit -S -l unlimited
# stack size, soft and hard limits for all PBS children
ulimit -H -s unlimited
ulimit -S -s unlimited

**Comment by sbenkorichi** [comment]
Yeah, but I don't have that one.
I have in /etc/init.d/torque-mom 
in torque-mom there is a PIDFILE=/var/spool/torque/mom_priv/mom.lock 
it's set to 1412, if I change it, and then reboot it would reset again. 
I tried putting ulimit -l unlimited into the torque-mom file, but nothing changed.

**Comment by sbenkorichi** [comment]
Great, 
I got it solved by just putting them into the /etc/init.d/torque-mom
on the starting of the script. Then, I had to restart it
`# /etc/init.d/torque-mom restart `

Thanks Glenn.

**Comment by sbenkorichi** [comment]
One thing that I have noticed is that setting the soft line before the hard one, would not fix it.
It has to be set exactly as you have shared above otherwise, it would still complain about it. 
```
ulimit -H -l unlimited
ulimit -S -l unlimited
```
