### ISSUE TITLE
FDS: Freeze Time not freezing radial fire

### ISSUE THREAD

**Issue by p-horne** [firemodels/fds#6029]
When a freeze time is attached to a ramp, which is for a radial fire, the radial fire continues to grow after the freeze time.

Attached is example case and output devc and hrr files demonstrating HRR continues to grow,

note csv's have been renamed to allow upload.

[radial_hrr_freeze.fds.txt](https://github.com/firemodels/fds/files/1725825/radial_hrr_freeze.fds.txt)
[hrr_freeze_devc.csv.txt](https://github.com/firemodels/fds/files/1725826/hrr_freeze_devc.csv.txt)
[hrr_freeze_hrr.csv.txt](https://github.com/firemodels/fds/files/1725827/hrr_freeze_hrr.csv.txt)

**Comment by sbenkorichi** [comment]
Thanks !

--Jason, could you please check if it's possible to be done? Thanks !

**Comment by drjfloyd** [comment]
The SPREAD_RATE causes cells within the VENT to ignite once their distance
from the XYZ is greater than the spread time for that distance. Once
ignited those cells then burn based upon the HRRPUA times the RAMP value.
You have linked the RAMP to a timer that can be frozen.  The RAMP is 0 at 0
s and 1 at 1 s.  Whatever time is frozen, becomes the RAMP value for all
future cells that are ignited by the SPREAD_RATE.  This approach isn't
going to do what you want.  We don't have any means to stop the SPREAD_RATE
from spreading.

**Comment by sbenkorichi** [comment]
Well,
since the spread rate isn't possible to be controlled, you might check this dummy example.
[test.fds.txt](https://github.com/firemodels/fds/files/1726892/test.fds.txt)

**Comment by drjfloyd** [comment]
Break up your VENT into rings of VENTs.  With a 5 cm mesh and VENT that is 40 cm you could have 4 rings of radius  0-5 cm, 5-10 cm, 10-15 cm, and 15-20 cm.  Assign each ring its own RAMP that turns  the fire and grows it at the appropriate time based on your spread rate. Link each of the RAMPs to the FREEZE TIME device.  When the device freezes time, any RAMPs that haven't yet ignited their ring, will remain that way.

**Comment by sbenkorichi** [comment]
Jason, I think this should be closed now as there is nothing to add into it. 
If user still has some question, he still can post them in the discussion group. Thanks !

**Comment by p-horne** [comment]
Hi All,

I wondered if it wouldn't be possible. I currently use the approach Jason explained, but thought there might be an easier way to achieve this using a radially growing fire. However, it seems quite hard so I'll stick with the current method. Thanks for all you help.
