### ISSUE TITLE
SMV upper bound color

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6030]
Example: When I set the bounds as 10-50, all above 50 shown as red. When I switch it to stepped colored scale, then the upper limit color fades a bit. On the third figure you may see the difference. 

Is there any way to work around that? 

Thank you

![image](https://user-images.githubusercontent.com/26166281/36262309-5ad9a6ee-1267-11e8-9fa1-b8caddc68cb7.png)
![image](https://user-images.githubusercontent.com/26166281/36262343-759fad0c-1267-11e8-8930-c2e2a664d352.png)
![image](https://user-images.githubusercontent.com/26166281/36262398-99c556f0-1267-11e8-8606-a3161239b92f.png)

**Comment by mcgratta** [comment]
Do the colors accurately represent the values? If so, this is not really a problem. Obviously, there is some kind of decision made by SMV to choose the 10 distinct color bands. The choice of red shade is somewhat arbitrary, so long is the data values are properly represented.

**Comment by Er9y714** [comment]
Yes, colors match in the view and the scale. 
Thank you for the reply. I will close the issue in that case.

**Comment by gforney** [comment]
fyi: the color red in the the stepped colorbar corresponds to the red for value 48 in the continuous colorbar ie midway between 46 and 50. 

 If you wish to see the red color from the continuous color bar for values > 50, (or any other color) open the Dialog>Data>Coloring dialog box , then open the Color tab.  Open "Highlight extren data" then check the "Color above max" checkbox and select 255,0,0 for the red,green and blue colors
