### ISSUE TITLE
Possible bug in two-step lumped species reaction scheme

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6032]
I am trying to formulate the Smyth burner case using lumped species. I've worked out the atom balances OK, and the case runs. The first reactions works, but the second does not happen. The case is here
[junk.fds.txt](https://github.com/firemodels/fds/files/1728436/junk.fds.txt)
`SUPPRESSION` does not seem to matter. The ODE solver does not matter. I think it probably has to do with the use of a lumped species as the `FUEL` of the second reaction. All the basic diagnostics in the .out file seem OK.

**Comment by drjfloyd** [comment]
I'll take a look.  Typically our two step approaches have formulated this as:

FUEL + AIR -> Products1 + CO
CO + Air -> Products2

but with fast reactions and no suppression I would have expected your approach to work.

**Comment by drjfloyd** [comment]
In your second reaction you have METHANE for SPEC_ID_NS.  This should be CO.

**Comment by mcgratta** [comment]
Doh! Thought I had converted everything. Sorry. One other question though -- does a `REAC` line always need a `FUEL`? I ask because I had forgotten to list it and the code ran, but there were lots of array out of bounds and other bad things. I wonder if we should just flag a lack of `FUEL` right at the start.

**Comment by drjfloyd** [comment]
I am pretty sure reactions universally require a FUEL. It is used in reaction rates, extinction, checking the HoC in input processing, and other locations.  Right now we check for FUEL in read_reac and if it is null we set it to ID (backwards compatibility) and then throw an error if it is still null,  but in the loop were we assign the fuel index we don't throw an error if then FUEL isn't found.

**Comment by mcgratta** [comment]
I just took the junk.fds test case above and removed the `FUEL` from the second reaction. The calculation started and then failed after 5 time steps with a numerical instability. In debug mode, errors pop up related to array bounds of fuel arrays. Could you add an `ERROR` at the appropriate point in the read routine. I don't want to risk adding it in the wrong place. Alternatively, would it make sense to assume that the first listed reactant on the `SPEC_ID_NU` is the fuel? If not, let's just stop with an error. Thanks.

**Comment by drjfloyd** [comment]
To be safe, I added an error for FUEL.

**Comment by mcgratta** [comment]
Great, thanks.
