### ISSUE TITLE
segmentation fault with single processor FDS

### ISSUE THREAD

**Issue by Aditya62** [firemodels/fds#6041]
Segmentation fault with single processor using the attached input file.

[wind_example_no_obst.txt](https://github.com/firemodels/fds/files/1732428/wind_example_no_obst.txt)
![segmentation_error](https://user-images.githubusercontent.com/36547341/36323279-00733f80-1316-11e8-982d-c8f13ea5c8f4.png)

**Comment by sbenkorichi** [comment]
Ok,
this is because of lack of memory.
Do this:

in your .bashrc file, you find it in your home directory. Add this line close to where you put your fds env

`ulimit -s unlimited`

This should fix it.

**Comment by sbenkorichi** [comment]
I forgot to mention that you have to log off and login again, so the change can take affect.

**Comment by sbenkorichi** [comment]
@Aditya62 

Did it fixing your issue?

**Comment by Aditya62** [comment]
Yes, I was able to remove the segmentation error by increasing the stack
size. I ran into this error later

symbol lookup error: /home/uahapm/FDS/FDS6/bin/LIB64/libmpifort.so.12:
undefined symbol: MPI_UNWEIGHTED

Do I need to add a bash file to resolve the issue.

**Comment by sbenkorichi** [comment]
Show exactly what you have done.
You shouldn't receive this error. Something not right.

**Comment by sbenkorichi** [comment]
How did you increase it?
Please post exactly what you have done.
You shouldn't be having this issue. Post also how you are defining the fds environment in . bashrc file. Post what you have put in it.


Sent from my phone

________________________________

**Comment by Aditya62** [comment]
I just used the " ulimit -s unlimited" in the command line. and then I ran
the code.

thats how I define fds in the bashrc file

export PATH=/home/uahapm/FDS/FDS6/bin:$PATH
export
LD_LIBRARY_PATH=/usr/lib64:/home/uahapm/FDS/FDS6/bin/LIB64:$LD_LIBRARY_PATH

export MODULEPATH=/home/uahapm/FDS/FDS6/bin/modules:$MODULEPATH

**Comment by sbenkorichi** [comment]
Well, I asked you to put it in your .bashrc, same where you put those lines of fds environment. 
If you just use terminal, then it only will be effective on that terminal session you are on. Once you close it, it won't work.
So, first put it as 

```
export PATH=/home/uahapm/FDS/FDS6/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib64:/home/uahapm/FDS/FDS6/bin/LIB64:$LD_LIBRARY_PATH
ulimit -s unlimited
I_MPI_SHM_LMT=shm
```
The last line will fix another issue if you decide to use MPI.

**Comment by sbenkorichi** [comment]
The error you were having probably coming from a conflict between module and the fds environment. 
You should only use either of them. Don't use both at the same time. This is probably why your LD_LIBRARY_PATH wasn't set appropriately, and start complaining about libmpifort.so.12

**Comment by sbenkorichi** [comment]
```
export PATH=/home/salah/FDS/FDS6/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib64:/home/salah/FDS/FDS6/bin/LIB64:$LD_LIBRARY_PATH
export OMP_NUM_THREADS=4
ulimit -s unlimited
I_MPI_SHM_LMT=shm
```

This is what I have on my laptop.

**Comment by Aditya62** [comment]
I update my bash rc file as per yours

export PATH=/home/uahapm/FDS/FDS6/bin:$PATH
export
LD_LIBRARY_PATH=/usr/lib64:/home/uahapm/FDS/FDS6/bin/LIB64:$LD_LIBRARY_PATH

ulimit -s unlimited
I_MPI_SHM_LMT=shm

i am still facing the same issue

symbol lookup error: /home/uahapm/FDS/FDS6/bin/LIB64/libmpifort.so.12:
undefined symbol: MPI_UNWEIGHTED

**Comment by sbenkorichi** [comment]
Please take a screen shot. I can't tell from what you are posting. 
export
LD_LIBRARY_PATH=/usr/lib64:/home/uahapm/FDS/FDS6/bin/LIB64:$LD_LIBRARY_PATH
Does this mean, you have two lines or you put them in one line?

**Comment by Aditya62** [comment]
[image: Inline image 1]

**Comment by sbenkorichi** [comment]
get on github, and reply from there. Don't send it from your email as I can't see it.

**Comment by Aditya62** [comment]
![selection_003](https://user-images.githubusercontent.com/36547341/36399848-60dc882a-1593-11e8-9303-4b844ae6333e.png)

**Comment by sbenkorichi** [comment]
Ok.
Try one more thing, just to confirm.
Reinstall fds again, and then make sure the same same lines that show up at the end of installation matches the above two in your .bashrc. 
Log off and then login again. 
run any of the examples that come with the installation package. Do you still receive the same error or not?

**Comment by sbenkorichi** [comment]
Also,
Make sure to comment the two modules of intel/15.0.1 and openmpi.
Keep only fds environment.

**Comment by Aditya62** [comment]
I reinstalled FDS and copied same lines you had mentioned in the .bashrc files. but, i still get the MPI_Unweighted error

**Comment by sbenkorichi** [comment]
Try to comment the lines of the modules you are loading as I mentioned above.
Also, do this:
```
$ echo $LD_LIBRARY_PATH 
$ which fds
$ which mpiexec
```

Also, post an image of how you run fds, and the error you receive, I want to see that.

**Comment by Aditya62** [comment]
![screenshot from 2018-02-19 17-38-27](https://user-images.githubusercontent.com/36547341/36401338-8bc146c6-159c-11e8-9926-8e96055ca33f.png)
![screenshot from 2018-02-19 17-38-20](https://user-images.githubusercontent.com/36547341/36401341-8f1efe8a-159c-11e8-819e-ce6f831db4b1.png)
![screenshot from 2018-02-19 16-24-47](https://user-images.githubusercontent.com/36547341/36401342-913dc516-159c-11e8-987c-43e8eb1187b7.png)

**Comment by sbenkorichi** [comment]
Well,
if you want to solve your issue. You have to show what you are doing. We're just wasting our time here.
Please do describe your issue in details. Don't just say I have an issue with fds and that's it.
I requested to run a simple case from the fds examples,
All of the sudden it turned out you are using scheduler job.
Please don't assume that we know what you are doing. 
Run the example below as : 

`$ fds activate_vents.fds `

Show what it gives.
Please don't do anything else. Just run this example (make sure to remove the .txt.

[activate_vents.fds.txt](https://github.com/firemodels/fds/files/1738530/activate_vents.fds.txt)

**Comment by Aditya62** [comment]
Sorry about not being very clear previously.
So here's what I did:
1. Used the activate_vents.fds without making any changes and works fine. (Attached screenshot "File_1.png")
![file_1](https://user-images.githubusercontent.com/36547341/36402097-9f807eb6-15a1-11e8-8267-54390fdaa40c.png)
2. Submitted the same file (activate_vents.fds) through the queue system. (Attached screenshot "File_2.png")
![file_2](https://user-images.githubusercontent.com/36547341/36402208-67f0b35c-15a2-11e8-8dd8-6ea3670ca3a4.png)

3. I get the MPI_UNWEIGHTED error here, (Attached screenshot "File_3.png")
![file_3](https://user-images.githubusercontent.com/36547341/36402211-6c0f81b6-15a2-11e8-8152-fa9b804dbfab.png)

**Comment by sbenkorichi** [comment]
ok I consider the issue is solved.
What I suggest now is you close this issue,
Open up new one explain how you set the bash script for job schedule, what module are you using, how did you compile it etc, 
the line how you run FDS inside, etc, not providing sufficient information will only get us into another circle again.

**Comment by sbenkorichi** [comment]
Thanks !
Open up a new issue so  we can work on it.
I have a feeling that there is a conflict in your job scheduler, it's somehow (possibly) using openmpi, whereas we have moved to INTEL MPI, but I can't diagnose it without seeing what you are doing.

**Comment by Aditya62** [comment]
I have created a new issue "MPI_UNWEIGHTED error" #6052
Thanks for your help.
