### ISSUE TITLE
Problem with multiple meshes in atmosphere

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#6047]
In this simple test case I want to see the thermal effect in the atmosphere when the ground has a temperature of 60°C. When I do the run with one mesh the result is correct. When I do the run with two meshes you can see that the higher air temperature caused by the ground temperature of 60°C is calculated on the bottom of the finer mesh (at 0 m) and on the bottom of the coarser mesh (at 800 m).

Fig. 1:  Air temperature
![temperature](https://user-images.githubusercontent.com/27724706/36416362-280721f4-1629-11e8-8764-8722d4f86b55.jpg)

Fig. 2:  Grid
![mesh](https://user-images.githubusercontent.com/27724706/36416364-28499624-1629-11e8-8bec-d6f716499813.jpg)

[atmosphere.fds.txt](https://github.com/firemodels/fds/files/1739521/atmosphere.fds.txt)

Kind regards, Herbert

**Comment by rmcdermo** [comment]
Thanks.  We will take a look.

**Comment by rmcdermo** [comment]
The problem is tied to STRATIFICATION.  If P_0(K) is set to P_INF in init, even when exercising all other terms associated with STRAT, then the problem goes away.  We checked P_0(ZC) and it looks correct.  We will keep working on this.  Thanks for the very clean test case!

**Comment by mcgratta** [comment]
When I scale the domain down by a factor of 100, I do not see the problem. This probably indicates that some small error in extrapolation is being magnified by the cell size of 100 m. I'll keep digging. 

`NOISE=.FALSE.` helps a little, but does not solve the problem.

**Comment by rmcdermo** [comment]
Another clue is that if you run with central differencing on density (FLUX_LIMITER=0) then the problem is much less.  I think this means that P_0 is being central differenced whereas RHO is not, perhaps leading to an inconsistency.

**Comment by herbertTau** [comment]
The same effect you get when there are for example three meshes. (see Fig. 3)

Fig. 3: Air temperature with 3 meshes
![3meshes](https://user-images.githubusercontent.com/27724706/36469840-ea5d0d62-16e8-11e8-9ab3-10c60ab4595d.jpg)

I have detected another abnormality. This concerns the relative humidity. Fig. 4 shows the relative humidity at the start. Every mesh has difference values although the temperature is the same at the start.

Fig. 4: Relative humidity
![humidity](https://user-images.githubusercontent.com/27724706/36470508-5dd1fc38-16eb-11e8-976c-265383da4a16.jpg)

[atmosphere2.fds.txt](https://github.com/firemodels/fds/files/1743321/atmosphere2.fds.txt)

**Comment by rmcdermo** [comment]
Thanks. Keep'm coming...

**Comment by rmcdermo** [comment]
Humidity output is fixed in commit #6049.

![screen shot 2018-02-21 at 10 01 00 am](https://user-images.githubusercontent.com/4418497/36487300-8d96ccac-16ee-11e8-9829-d1bfb2977c87.png)

**Comment by rmcdermo** [comment]
Note: I recommend using CELL_CENTERED slice outputs as much as possible, else you may see interpolation effects at mesh boundaries where ghost node values have not been filled (which would require expensive mesh exchanges on output).

**Comment by rmcdermo** [comment]
@mcgratta 

Add the following lines to divg.f90 just after we compute the heat flux.

```
!$OMP PARALLEL DO PRIVATE(DTDX, DTDY, DTDZ) SCHEDULE(STATIC)
DO K=0,KBAR
   DO J=0,JBAR
      DO I=0,IBAR
         DTDX = (TMP(I+1,J,K)-TMP(I,J,K))*RDXN(I)
         KDTDX(I,J,K) = .5_EB*(KP(I+1,J,K)+KP(I,J,K))*DTDX
         DTDY = (TMP(I,J+1,K)-TMP(I,J,K))*RDYN(J)
         KDTDY(I,J,K) = .5_EB*(KP(I,J+1,K)+KP(I,J,K))*DTDY
         DTDZ = (TMP(I,J,K+1)-TMP(I,J,K))*RDZN(K)
         KDTDZ(I,J,K) = .5_EB*(KP(I,J,K+1)+KP(I,J,K))*DTDZ
      ENDDO
   ENDDO
ENDDO
!$OMP END PARALLEL DO

if (nm==1) print *, 'top: ',KDTDZ(25,1,0)
if (nm==2) print *, 'bot: ',KDTDZ(25,1,KBAR)
```

Now, run the attached case with K=8 on mesh 2 (equal resolution in Z) and K=16 on mesh 2.  With equal resolution, the heat flux is the same.  When the resolution is half then the heat fluxes are not even the same sign.  I think that consistent heat flux is something we need to ensure for interpolated boundaries.

[atmosphere_test.fds.txt](https://github.com/firemodels/fds/files/1745092/atmosphere_test.fds.txt)

**Comment by mcgratta** [comment]
`KP=MU*CPOPR` and `MU` is exchanged mesh to mesh. But `MU` is grid dependent, which suggests that we not exchange or use neighboring mesh values of `MU` when the grid cells are different sizes.  Or perhaps do some kind of adjustment to account for scale.

**Comment by mcgratta** [comment]
In `VISCOSITY_BC` in `velo.f90`, the values of the viscosity `MU` in the ghost cells of a given mesh are taken from the neighboring mesh:
```
   N_INT_CELLS = (EWC%IIO_MAX-EWC%IIO_MIN+1) * (EWC%JJO_MAX-EWC%JJO_MIN+1) * (EWC%KKO_MAX-EWC%KKO_MIN+1)
   MU_OTHER = MU_OTHER/REAL(N_INT_CELLS,EB)
   KRES_OTHER = KRES_OTHER/REAL(N_INT_CELLS,EB)
   DP_OTHER = DP_OTHER/REAL(N_INT_CELLS,EB)
   MU(II,JJ,KK) = MU_OTHER
   KRES(II,JJ,KK) = KRES_OTHER
```
We could do this:
```
IF (N_INT_CELLS==1) THEN
   MU(II,JJ,KK) = MU_OTHER
ELSE
   MU(II,JJ,KK) = MU(IIG,JJG,KKG)
ENDIF
```

**Comment by rmcdermo** [comment]
@herbertTau Can you compile the latest source?  If so, try this input file.

```
&HEAD CHID='atmosphere', TITLE='Two mesh test in atmosphere' /

&MESH IJK =  50, 1,  22, XB = 0, 5000,  0, 100, 800, 3000 /
&MESH IJK = 100, 1,  16, XB = 0, 5000,  0, 100,   0,  800 /

&TIME T_END=3600/

&WIND USE_ATMOSPHERIC_INTERPOLATION=T/

&VENT PBX=0, SURF_ID='PERIODIC' /
&VENT PBX=5000, SURF_ID='PERIODIC' /
&VENT PBZ=3000, SURF_ID='OPEN' /
&VENT PBZ=0, SURF_ID='ground' /

&SURF ID='ground', TMP_FRONT=60, COLOR='BROWN' /

&SLCF PBY=0, QUANTITY='DIVERGENCE', CELL_CENTERED=T /
&SLCF PBY=0, QUANTITY='DENSITY', CELL_CENTERED=T /
&SLCF PBY=0, QUANTITY='TEMPERATURE', CELL_CENTERED=T /
&SLCF PBY=0, QUANTITY='RELATIVE HUMIDITY', CELL_CENTERED=T /
&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=T /

&TAIL /
```

Here is the result with the latest code.

![screen shot 2018-02-22 at 5 10 49 pm](https://user-images.githubusercontent.com/4418497/36567350-1a502f66-17f4-11e8-99c4-1bff4bb6632a.png)

**Comment by rmcdermo** [comment]
I'm interested to test a case with WATER VAPOR transport.  Can you set up a realistic scenario and see if things look as expected?

**Comment by herbertTau** [comment]
Sorry, at the moment I'm not able to compile the latest source. It is some time ago since I was busy with FORTRAN but I want to refresh it. Are Eclipse and Photran a good choice zu start again ?

**Comment by rmcdermo** [comment]
Unless you want to buy the Intel compiler, you can use gfortran.  I don't use a developer environment like Eclipse.  I just use Sublime Text as an editor, which can gather and search the source code very well.

**Comment by sbenkorichi** [comment]
There is already a step by step to get fds compiled with gfortran. 
https://github.com/firemodels/fds/wiki/Compiling-FDS-with-GNU-Fortran,-OpenMPI-and-Intel-Performance-Libraries-in-Ubuntu-Linux
you might give this a try, as I believe it's a straight forward.

**Comment by herbertTau** [comment]
That's not so easy, I think I'll wait for the new version.

**Comment by sbenkorichi** [comment]
Which step isn't easy or clear?

**Comment by herbertTau** [comment]
You're right, with the step by step instruction I could install the necessary programs. GNU Fortran, OpenMPI and Intel Performance Libraries are installed. At "Compiling and running the code:" there is a demand to go to my updated repo for FDS. Where do I find the updated repo for FDS? Do I have to do some additional work before?

**Comment by sbenkorichi** [comment]
Ok,
On this web, click on the green button (either you choose clone (if you have git installed) or just say download as zip) after downloading, unzip the file, and go to `fds/Build/mpi_gnu_linux_64`), and do
`$ ./make_fds.sh`

Let me know if you need further infos, or face other issues.

**Comment by sbenkorichi** [comment]
Forget to attach the link: 
https://github.com/firemodels/fds

**Comment by herbertTau** [comment]
Thank you very much, everything is going splendid.
Now I will test the case with the latest compiled source.

**Comment by herbertTau** [comment]
I tried out the input file with the latest source and get the same result as seen in the output above.
It works very well. Thank you.

**Comment by sbenkorichi** [comment]
Ok, thanks for reporting back.
If this issue has been solved, then, feel free to close it.
Unless, Randy still want to do more work on it.

**Comment by rmcdermo** [comment]
Let's leave it open.  I want to get this to the point where we do not need a special input parameter.

**Comment by mcgratta** [comment]
Should this issue be closed?

**Comment by rmcdermo** [comment]
The issue has been fixed.  But I wanted to add a verification case.  I'm struggling to figure out how to make this a verification case.

**Comment by mcgratta** [comment]
What is the status of this issue?

**Comment by rmcdermo** [comment]
Status quo.  I am not sure how to make verification case for this.  I could just add an image to the guide.

**Comment by mcgratta** [comment]
I'm going to close this issue. No doubt it will pop up again later, hopefully with a more obvious verification case.
