### ISSUE TITLE
typo in UG

### ISSUE THREAD

**Issue by springcb** [firemodels/fds#6055]
1.
FDS UG 277 page
SURFACE_TENSION Real Section 14.3.4 N/m 7.28×10^4
->
SURFACE_TENSION Real Section 14.3.4 N/m 7.28×10^-2

(reason)
read.f90 source code
SURFACE_TENSION          = 72.8E-3_EB  ! N/m, applies for water

2.
SMV UG 85 page
7.2 Key frame Settings

A tour is created from a series of key frames. One may specify the time, position and view direction at
each key frame. Smokeview then obtains positions and view directions between key frames by interpolating
using cubic Hermite cubic splines.
->
using cubic Hermite splines.

3.
SMV UG 95 page

4. Generate the center image
(d) Set the render suffix to right_10 and press the Render button
=> 
(d) Set the render suffix to center_10 and press the Render button

4.
SMV UG 97 page

vector_length_index, is an integer index from 0 to 6 pointing to an internal Smokeview
array used to determine vector length.
->
vector_length_index - is an integer index from 0 to 6 pointing to an internal Smokeview ....

5.
SMV UG 98 page

CBARNORMAL Usage: Display the colorbar in the same orientation as it was defined.
->
CBARNORMAL Display the colorbar in the same orientation as it was defined. Usage: 

6.
SMV UG 99 page

KEYBOARD Passes a keyboard character to Smokeview Usage:
->
KEYBOARD Passes a keyboard character to Smokeview. Usage:

7.
SMV UG 99 page

UNLOADTOUR Unload a tour.
->
UNLOADTOUR Unload a tour. Usage:

8.
SMV UG 101 page

one to create volume rendered movies for data sets too large to be viewed within Smokeview.

VOLRENDERALL
skip first
file name base (char) (or blank to use the Smokeview default)
=>
one to create volume rendered movies for data sets too large to be viewed within Smokeview. Usage:
.........

9.
SMV UG 101 page

VOLSMOKERENDERALL Render a sequence of volume rendered frames. As with RENDERALL,
this command by default command renders every frame starting with the first.
=>
.......
this command by default renders every frame starting with the first.

**Comment by sbenkorichi** [comment]
@springcb 
Nice, thanks we'll take a look.

**Comment by gforney** [comment]
Thanks, I'll take a look

**Comment by rmcdermo** [comment]
Surface tension fixed in commit #6063

**Comment by Er9y714** [comment]
10. page 156: **Flow Over a Backward Facing Step** in Ver. Guide is referenced but I cannot find it.

11. Chapter 15: (the default _backgroun**X**)_
(as defined on REAC **_X_.**

12. 16.1.2 ...species will be appropriately **adjsuted** for...

13. 17.2.1 Path length. Release notes say it is fixed to 0.1 m. 
Also Table 21.22 may be updated with fixed default value.

14. 18.3.3 Is this sentence okay?:
“droplet distribution is divided...”

15. They represent the heat absorbed by the particles via convection, radiation, and conduction from the wall.
c,r and w are underlined. Does it refer to some abbreviation?

16. p263 GAUGE_EMISSIVITY is 0.9 for GHF, 1.0 for radiometer. If that is true, is default value 0.9 in Table 21.21 correct?


Thank you.

**Comment by mcgratta** [comment]
I fixed these typos, thanks.

**Comment by mcgratta** [comment]
I'm going to close this issue. If you find more typos, just start a new issue.
