### ISSUE TITLE
Printout of CONTROL functions

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6087]
For these lines in `ctrl.f90`, do we really need the lines I have pointed to
```
! Update devices that are used to print out control function results

IF (UPDATE_DEVICES_AGAIN) THEN
   DO N=1,N_DEVC
      DV => DEVICE(N)
      SELECT CASE(DV%QUANTITY)
         CASE('CONTROL VALUE')
           DV%VALUE = CONTROL(DV%CTRL_INDEX)%INSTANT_VALUE  <------
           DV%TIME_INTERVAL = 1._EB  <-----
         CASE('CONTROL')
            DV%VALUE = 0._EB
            IF (CONTROL(DV%CTRL_INDEX)%CURRENT_STATE) DV%VALUE = 1._EB
            DV%TIME_INTERVAL = 1._EB
      END SELECT
   ENDDO
ENDIF
```
I ask because I created a function using math controls, and I want to run `STATISTICS` on it
```
&DEVC ID='Urms', QUANTITY='CONTROL VALUE', CTRL_ID='sum', XYZ=0,0,1, UNITS='m/s', STATISTICS='RMS', STATISTICS_START=2. /
```
`sum` is a just a time series for which I want to calculate its rms. But the lines in `ctrl.f90` overwrite my rms calculation and just restore the original value of `sum`. It seems that `CONTROL VALUE` is by default not time-averaged, so do we need these lines in `ctrl.f90` anymore?

**Comment by drjfloyd** [comment]
Multiple users complained that control outputs weren't synched with devices. We update controls after devices, so for a device that points to a control it might show a long delay depending on DT_DUMP before it shows that update to a control.  This logic was added to fix that.  I think it is a legitimate complaint to have addressed. 

Also by default we don't want these device types to normally be averaged over DT_DUMP as a number of things are tied to those values being instantaneous (especially for CONTROL).

One solution is I think you could just program the RMS using more control functions.

**Comment by mcgratta** [comment]
When we call `UPDATE_DEVICES` and we process a device with `QUANTITY='CONTROL VALUE'`, aren't we doing what we are doing again when we call `UPDATE_CONTROLS`? We now set the default value of `TIME_AVERAGED` to false for this quantity. Could it be that when this chunk of code was put in that these values were being time-averaged by default?

**Comment by drjfloyd** [comment]
You added this chunk of code as part of us addressing issue 4680.

**Comment by drjfloyd** [comment]
Somehow we need a second pass through devices to capture those devices that are computed by controls that use devices as inputs

**Comment by mcgratta** [comment]
OK, I see it now. Thanks.
