### ISSUE TITLE
ramp_speed is not working

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#6092]
According to the attached test case the wind speed should decrease from 0 to 5 m/s over a period of 30 seconds. But the result shows that the wind speed stays constant at 5 m/s.

[wind.fds.txt](https://github.com/firemodels/fds/files/1770534/wind.fds.txt)

**Comment by rmcdermo** [comment]
@mcgratta I see in the code where you are reading in RAMP_SPEED and then getting the ramp index I_RAMP_SPEED.  But I do not see that you then use it anywhere.

**Comment by mcgratta** [comment]
OK, I'll take a look.

**Comment by mcgratta** [comment]
Update your repo and recompile. Let me know if it works.

**Comment by herbertTau** [comment]
Thank you, it works.

Concerning the RAMP function I sometimes wished that it would be possible to specify the dependent variable F by a mathematical function.
For example:
&RAMP ID='ramp1', F=SIN(0.1*T) /
&RAMP ID='ramp2', F=0.2*T^2+5*T-3.3 /
Is there a possibility for implementation ?

**Comment by Er9y714** [comment]
@herbertTau , Yes you can implement this calculation, see Userguide Table 16.2: Control function types. in 16.5 Advanced Control Functions: The CTRL Namelist Group.

**Comment by rmcdermo** [comment]
Thanks for reporting back.  I believe the CTRL functions address your request.

**Comment by mcgratta** [comment]
Or, just set up a simple Excel sheet to automatically create the RAMP lines. Takes a few minutes. Not slick, but it works.
