### ISSUE TITLE
Is internal radiation available for spherical or cylindrical geometries?

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6098]
Page 72 of the tech guide says, "The two-flux model has not been adapted for cylindrical or spherical geometry."  But in wall.f90 it looks like this has been accounted for.  Can someone take a look and correct the guide if necessary?  Thanks.

**Comment by shostikk** [comment]
The version in source code for cylindrical geometry is a left-over from a workaround approximative model. It is not correct, and should be removed. It seems to me, that two-flux model cannot be derived for cylindrical or spherical co-ordinates. The math becomes way too complex.

**Comment by mcgratta** [comment]
OK, I will add an ERROR if a user tries to set an `ABSORPTION_COEFFICIENT` for a non-Cartesian surface. I'll also remove the r*dr terms from the calc.

**Comment by mcgratta** [comment]
The code will now stop if someone tries to apply an `ABS_COEF` to a sphere or cylinder.
