### ISSUE TITLE
Atmospheric wind profile over an obstacle

### ISSUE THREAD

**Issue by Aditya62** [firemodels/fds#6101]
I am trying to simulate a case imposing the atmospheric wind profile as an inlet to simulate flow over an obstacle . The domain size is 30x15x15 m and grid resolution is 360x90x90.

So far I have run test cases on single and 4 processors with the same specifications(domain size and grid resolution). I encountered the following issues:

1. Here at initial times(t = 1s) I see some discontinuity at the mesh interface in the velocity magnitude profile in the 4 processor test case however this is lacking in the single processor version.(Attached: Velocity_magnitude_time_1s_proc_4.png & Velocity_magnitude_time_1s_proc_1.png)
![velocity_magnitude_time_1s_proc_4](https://user-images.githubusercontent.com/36547341/36864651-e0cc3622-1d52-11e8-8ba2-b7eba10984dc.png)
![velocity_magnitude_time_1s_proc_1](https://user-images.githubusercontent.com/36547341/36864779-462bbe7a-1d53-11e8-9bd8-3e7e72889990.png)

2.At later times(time = 9s) the discontinuity disappears in the 4 processor version. However, in both the test cases I see wave like disturbances in the flow field. (Attached: Velocity_magnitude_time_9s_proc_4.png &Velocity_magnitude_time_9s_proc_1.png)
![velocity_magnitude_time_9s_proc_4](https://user-images.githubusercontent.com/36547341/36864826-5f3144ee-1d53-11e8-801d-82b4b12e8ee2.png)
![velocity_magnitude_time_9s_proc_1](https://user-images.githubusercontent.com/36547341/36864829-6151dce8-1d53-11e8-8dba-51b2cda93b79.png)

I would like to know the reason for the discontinuity at mesh interface at initial times and whats the best solution to avoid the disturbances at later times.

Thank you.

**Comment by Aditya62** [comment]
Attached below are the respective input files

[test_case_obst_1proc.txt](https://github.com/firemodels/fds/files/1772487/test_case_obst_1proc.txt)
[test_case_obst_4proc.txt](https://github.com/firemodels/fds/files/1772488/test_case_obst_4proc.txt)

**Comment by mcgratta** [comment]
The discontinuity in velocity is the result of solving the pressure equation in each of the four grids. FDS uses an iterative method to force continuity. It is common in cases where you are pushing air through a tunnel that you see these discontinuities initially. You can tighten up the tolerance if you want. Search the User's Guide for VELOCITY_TOLERANCE.

However, I do not recommend that you simulate wind this way. Starting with FDS 6.6.0, we use Monin-Obhukov theory and mean forcing to generate wind fields in a way that is more consistent with the atmospheric boundary layer community. What you are doing here is what we call the "wall of wind" and we do not recommend it anymore . 

The "disturbances" in the flow are numerical artifacts resulting from the way the momentum equations are differenced. It is akin to central differencing, so you see some spurious fluctuations. These should not affect the overall results.
