### ISSUE TITLE
Numerical Instability with Tunnel

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6112]
This issue was reported by a Khai, it can be found [here ](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/fds-smv)

The input case file is attached below. 

I believe we should try to work on this case to try to come up with some regid fix, at least for the long run.

@rmcdermo 
Any suggestions to start with?
Thanks !

Salah
[vent_100MW.fds.txt](https://github.com/firemodels/fds/files/1775567/vent_100MW.fds.txt)
[vent_100MW.out.txt](https://github.com/firemodels/fds/files/1775571/vent_100MW.out.txt)

**Comment by mcgratta** [comment]
You are starting a 100 MW fire, turning on a sprinkler system, and activating an HVAC system, all within a few seconds in a tunnel with no leakage. The fact that your other cases ran is a miracle. I suggest that you create a 1 cell wide OPEN boundary running on the floor the length of the tunnel. This will provide pressure relief. I did this and the case is running past the point of instability. Also, I suggest that you do not change mesh size so close to the fire and mist system. These boundaries are typically where these instabilities occur.

**Comment by rmcdermo** [comment]
Is there any possible way to make this OPEN VENT trick a TUNNEL feature?  Is there a single piece of literature on ventilation in tunnels that would give us a starting point for what is "reasonable" in terms of leakage rates?

**Comment by mcgratta** [comment]
I'd like ultimately to specify leakage using the HVAC routines, but I've not done that successfully. Opening up an OPEN vent is crude but usually effective because it creates an H=0 BC in all meshes which keeps things stable, like a giant pressure relief. Leakage rates for tunnels are going to vary alot. Tunnels bored through rocks are tight, but most modern tunnels have HVAC systems and lots of openings throughout.

**Comment by rmcdermo** [comment]
Can you add something to the user guide in Sec. 6.6.2 Pressure Considerations in Long Tunnels.

Let's not close this just yet.  I'd like to play with some examples of real cases that are breaking.

**Comment by khailooi** [comment]
Thanks Kevin and rmcdermo for your reply. I will try using the OPEN vent trick and change the mesh size farther away from the fire and mist system. Let you know how it goes soon.

**Comment by sbenkorichi** [comment]
I agree with Randy, I prefer we keep it open, and we try to test it more. Now and then, we get users having similar issues, this is what's been reported. It would be better to get some good fix for the coming releases, that would stabilize this instability problem.

**Comment by Er9y714** [comment]
@mcgratta , regarding placing an OPEN vent all along the tunnel, I am curious about the difference of pressure profile and the resulting effect of ventilation on the smoke layer development and air velocity.

**Comment by mcgratta** [comment]
If you have a better estimate of leakage, you can create a series of smaller OPEN vents along the bottom with an area comparable to the leakage area.

**Comment by khailooi** [comment]
Just an update to my simulation.

1) Increasing iteration for pressure did not help the issue, as the model kept hitting the maximum iteration and eventually reached numerical instability.
2) Adding a cell of 'leakage' worked, and it also reduced the simulation time by quite a bit, thanks Kevin. I have tested a run without the hole and the result did not change so much, so the level of confidence for this method is high for me.

Cheers,
Khai

**Comment by Er9y714** [comment]
@khailooi , did you locate this OPEN vent along the tunnel, i.e. one long narrow vent along the tunnel? could you give the size to have an idea?

**Comment by khailooi** [comment]
Hi, I only put a 0.25m x 0.25m OPEN vent (which is one cell) 3m upstream of the fire, as I reckon the pressure will be very high near the fire, and putting it upstream will not let smoke escaping from the vent.
