### ISSUE TITLE
Verification/scripts/Run_FDS_Cases.sh assumes one is using Intel compilers

### ISSUE THREAD

**Issue by btrettel** [firemodels/fds#6115]
Lines 170 and 171 of Run_FDS_Cases.sh in Verification/scripts/ assumes that Intel compilers are used. Since I'm using GNU compilers I had to change the lines.

It would be enough to add a note to the Wiki page on the FDS Verification Process about editing this file if you use GNU compilers, but you all might have something else in mind. The solution was pretty obvious to me, so changing nothing would make sense too.

**Comment by mcgratta** [comment]
If you want to run the whole verification suite, we can generalize this script. But if you only need to run your cases, we'll leave as is.

**Comment by gforney** [comment]
fyi:  I added a -e option to the verification and validation run scripts that lets you speify a particular version of fds (same as with qfds.sh ).  Note, you need to make sure your environment is set up to run with the versino of fds you specify
