### ISSUE TITLE
FDS exit codes

### ISSUE THREAD

**Issue by dkosovic** [firemodels/fds#6129]
I'm wondering is there a list of FDS exit codes somewhere?

I have a user running FDS 6.6.0 on our Slurm based cluster and after 6 days gets an exit code of 28 :

```
SLURM Job_id=68527 Name=Compartment_Run_100_1.5 Ended, Run time 6-00:33:39, FAILED, ExitCode 28
```

**Comment by sbenkorichi** [comment]
Well,
Can you post what the .err file showed at the end?

It might be the default of the job scheduler wall-time is limited to 6 days.

Can you share a simple script that you used to run it with.

**Comment by mcgratta** [comment]
This is not an FDS error statement.

**Comment by dkosovic** [comment]
I'll have more details hopefully Monday and have to get a confirmation from the research group if I can make available the input and output files.

But I can provide the Slurm submission script :

```sh
#! /bin/sh

#SBATCH --nodes=1
#SBATCH --cpus-per-task=4

module load fds/6.6.0
ulimit -s unlimited

fds Compartment_Run_40_1_0.fds
```

the module environment file for the module load is :

```tcl
#%Module 1.0
set version "6.6.0"

module-whatis "FDS $version"

prepend-path            PATH                    /opt/local/stow/fds-$version/bin
prepend-path            PATH                    /opt/local/stow/openmpi-1.10.6-intel/bin
prepend-path            LD_LIBRARY_PATH         /opt/intel/compilers_and_libraries_2016.2.181/linux/compiler/lib/intel64
prepend-path            LD_LIBRARY_PATH         /opt/local/stow/openmpi-1.10.6-intel/lib

if { [info exists ::env(SLURM_JOB_CPUS_PER_NODE)] } {
    setenv              OMP_NUM_THREADS         $::env(SLURM_JOB_CPUS_PER_NODE)
} elseif { [info exists env(SLURM_NTASKS)] } {
    setenv              OMP_NUM_THREADS         1
} else {
    setenv              OMP_NUM_THREADS         4
}
```

That `FAILED, ExitCode 28` error message is from a Slurm email notification to indicated the submission script has ended. As with other shell scripts, I would think the exit status of the Slurm submission script would be the exit status from the last command that runs in the script, in this case `fds`.

Slurm doesn't have a separate .err file (unless explicitly specified), but does have a combined output file. I don't see any errors. But will have more details Monday.

**Comment by dkosovic** [comment]
Forgot to mention, jobs are using the Slurm default wall time of infinite and 'ulimit -t' is unlimited.

The jobs seem to be exiting early before the specified simulation time of 750 seconds

**Comment by sbenkorichi** [comment]
What I recommend you in the future, is to start specify them in (i.e. the .err and .log files)
.err will dump the fds run time screen that you usually have on terminal, whereas .log one will output some command lines that you issue in your script for debugging purposes. 

with a simple fds test example,  check the .log file and see what it gives you.

```
#! /bin/sh

#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --error =/path/to/desired/output/directory/test.err
#SBATCH --output =/path/to/desired/output/directory/test.log

module load fds/6.6.0
ulimit -s unlimited

ulimit -a
which fds
cd /to/fds/input/file/
fds test.fds
```

You should verify the above command are correct as I'm not slum user, but more or less should be close to torque.

**Comment by dkosovic** [comment]
sorry, think it was a false alarm, turns out the user exceeded their disk quota, hence no error message was written out.

**Comment by sbenkorichi** [comment]
But, I would still expect to see a seg fault in the .err file , theoretically speaking.
Anyhow, glad you found out the reason.
