### ISSUE TITLE
Using Number of Particle To Measure Water Droplets and MINIMUM_DIAMETER

### ISSUE THREAD

**Issue by khailooi** [firemodels/fds#6146]
Hi all,

I am using the DEVC function 'Number of Particle' to measure the number of Lagrangian droplets in my tunnel model. I am keen to know the relative number of droplet among different variations of simulation, not the actual number (for instance my nozzle injects millions of droplets but this function only gives result in the scale of 1E5) therefore this function should be suitable for me.

On the other hand, as I am simulating water mist system, I realised most of the particles did not evaporate, as seen when I loaded the .particle file. I changed the parameter MINIMUM_DIAMETER to half of the median diameter (200micro meter) to see if more particles will evaporate as expected. As a result, visually, from .particle file, it seems that there are lesser particles in the model. However when I check the 'Number of Particle' devices, the value remains similar to the previous run which I did not alter the minimum diameter. Any clue what's going on here?

Also is there anyone who used MINIMUM DIAMETER in their water mist simulation before?

I have attached both .fds files. 
[fds codes.zip](https://github.com/firemodels/fds/files/1803801/fds.codes.zip)

Thank you.
Khai

**Comment by mcgratta** [comment]
I cannot comment on your case. It is too long and complicated. Your simulation ought to just have a single mesh, a single nozzle, and appropriate diagnostics. You should work with this simple input file until you have all the parameters set properly.

**Comment by khailooi** [comment]
Sorry for the over complication. To simplify, how can we track how much water mass has evaporated in the hot smoke layer and how much has dropped on the floor?

**Comment by Er9y714** [comment]
@khailooi see Userguide 12.1.5 Two Gas Species with the Same Properties. It explains tracking the water evaporated from sprinklers. I assume if you subtract the water evaporated from the total released, you can find the water dropped on the floor.
