### ISSUE TITLE
Pyrolysis polymers - PMMA 

### ISSUE THREAD

**Issue by marcinzak55** [firemodels/fds#6148]
I have small problem with my fds code. 
I examined the value of energy activation and pre exp. factor in TGA. When I apply my values to FDS, the end of pyrolysis takes place in 160 C. In TGA the final temperature for pyrolysis is about 420 C. The values A and E were calculeted by Ozawa, Wall method. I defined rest of parameters PMMA based on Validation Guide. Please for any suggestions to improve my pyrolysis code.  

&HEAD CHID='PMMA_10st', TITLE='tga_analiza_PMMA_10st' / 

&TIME T_END=9600 WALL_INCREMENT=1, DT=0.01 /
&MESH IJK=3,3,3, XB=-0.003,0.003,-0.003,0.003,0.0,0.003 /

&MISC Y_O2_INFTY=0.01, SOLID_PHASE_ONLY=.TRUE., TMPA=39.66 / 

&SPEC ID='METHANE' /

&SURF ID='slab_PMMA'
TGA_ANALYSIS=.TRUE.
TGA_HEATING_RATE=10.
TGA_FINAL_TEMPERATURE=500.
COLOR='BLACK'
BACKING='INSULATED'
MATL_ID(1,1)='BLACKPMMA'
THICKNESS=0.006
HEAT_TRANSFER_COEFFICIENT=0. / 

&MATL ID='BLACKPMMA'
ABSORPTION_COEFFICIENT=2700.
N_REACTIONS=1
A(1) = 8.86E14
E(1) = 130572 
EMISSIVITY=0.85
DENSITY=1100.
SPEC_ID='METHANE'
NU_SPEC=1 
HEAT_OF_REACTION=870.
HEAT_OF_COMBUSTION=25200.
CONDUCTIVITY = 0.20
SPECIFIC_HEAT= 2.2 /

&VENT XB=-0.002,0.002,-0.002,0.002,0.0,0.0, SURF_ID='slab_PMMA'/

DEVC ID='mpua',     XYZ = 0.0,0.0,0.0, IOR=3, QUANTITY='NORMALIZED MASS' /
DEVC ID='mlrpua',   XYZ = 0.0,0.0,0.0, IOR=3, QUANTITY='NORMALIZED MASS LOSS RATE', SPEC_ID='METHANE' /
DEVC ID='TGA temp', XYZ = 0.0,0.0,0.0, IOR=3, QUANTITY='WALL TEMPERATURE' /

&TAIL /

**Comment by sbenkorichi** [comment]
This should be discussed in the discussion group as it's not a bug in the code.
You are disabling the gas phase, try adding the ASSUMED_GAS_TEMPERATURE 
and RAMP it up based on  your TGA heating  rate.
See the examples in tga in the verification.

**Comment by mcgratta** [comment]
Check the units. Other than that, try the Discussion Forum. This does not appear to be a bug.
