### ISSUE TITLE
TGA temperature

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6151]
Kevin,
Take a look at this.

[test.fds.txt](https://github.com/firemodels/fds/files/1813504/test.fds.txt)

From my understanding, the temperature should be kept mounting steady up to 500 C. Whereas, in this case it shift to 0 once the total mass is consumed. I believe mimicking the TGA Temperature should be independent than the material. Even if it's consumed, it should be kept.

![image](https://user-images.githubusercontent.com/20113030/37436703-1e091576-27e1-11e8-992c-843d97464905.png)

**Comment by rmcdermo** [comment]
I don't understand why you would think that.  WALL TEMPERATURE is a SOLID_PHASE_OUTPUT quantity (read the code).  If there is no SOLID there is nothing for this temperature to output.

**Comment by sbenkorichi** [comment]
I understand that part Randy,my point is that TGA temperature shouldn't be represented by wall temperature (i.e. being dependent on the matl) it should be independent.

**Comment by rmcdermo** [comment]
You set ID='TGA temp', QUANTITY='WALL TEMPERATURE'.  What QUANTITY do you suggest to use?

**Comment by sbenkorichi** [comment]
I suggest something that would work similar to the assumed gas temperature. But, it should also work with the gas phase as well. Maybe you can find a way to hack this.
Just to dump the read assumed temperature with its RAMP. 
This will make get you similar dumped temperature to the TGA. So, you can use it to plot mass loss or mlr or other quantities vs temperature instead of time.

Because, in the case above, once the mass is consumed, you will see fishy plots.

Hope this makes sense.

**Comment by rmcdermo** [comment]
See PR #6152.  Please test and let me know if it works for you.

**Comment by sbenkorichi** [comment]
I will compile later and report back.

**Comment by sbenkorichi** [comment]
Thanks Randy,
But, I think you still need to substract from it 273.15
![image](https://user-images.githubusercontent.com/20113030/37466269-3bf99df2-2855-11e8-82c7-27259bfc39e3.png)

**Comment by rmcdermo** [comment]
Should be fixed in #6153 .

**Comment by sbenkorichi** [comment]
Thanks Randy,
it works as charm !
now user can plot mlr as a function of temperature (c). 

![image](https://user-images.githubusercontent.com/20113030/37472016-efe6be5a-2862-11e8-9312-f814a9647880.png)
