### ISSUE TITLE
New to FDS. Error running input file

### ISSUE THREAD

**Issue by JohnSweden123** [firemodels/fds#6173]
I'm a student (very limited code or programming knowledge) trying to understand why FDS has this error message...

FDS-SMV Launcher for OSX
 **** Version: 6.0.0 ****

 *** Input archive file: couch.zip 
 *** Running Input File: couch.fds
[Johans-MacBook-Pro.local:04412] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 388
[Johans-MacBook-Pro.local:04412] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 166
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /shared/openmpi300_i17u4notorque_64/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /shared/openmpi300_i17u4notorque_64/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[Johans-MacBook-Pro.local:4412] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

I followed this guide. https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-under-Mac-OS-X

Mac OS High Sierra
10.13.3

/Johan
Lund
Sweden

**Comment by marcosvanella** [comment]
Hi John, did you add the paths to openmpi/FDS in your start up file? I.e. did you add these lines to your ~/.bash_profile file? (I assume you installed the bundle in /Applications)

```
export PATH=/Applications/FDS/FDS6/bin:$PATH
export PATH=/Applications/FDS/FDS6/bin/openmpi_64/bin:$PATH
export OPAL_PREFIX=/Applications/FDS/FDS6/bin/openmpi_64
#  set OMP_NUM_THREADS to max of 4 and "Total Number of Cores" obtained from running
#  system_profiler SPHardwareDataType
export OMP_NUM_THREADS=4
```

Set the number of threads to the number of cores on your Mac. The OPAL_PREFIX environment variable is important, because it allows openmpi to work with relative paths.

**Comment by JohnSweden123** [comment]
Yes I installed the bundle in /Applications however I'm afraid I didn't quite know how to do the step:

 "At the end of the installation you will be given suggestions (based where you installed FDS) on how to update your startup file so that the fds command may be run from the command line. For example:

export PATH=/Applications/FDS/FDS6/bin:$PATH
export PATH=/Applications/FDS/FDS6/bin/openmpi_64/bin:$PATH
export OPAL_PREFIX=/Applications/FDS/FDS6/bin/openmpi_64
#  set OMP_NUM_THREADS to max of 4 and "Total Number of Cores" obtained from running
#  system_profiler SPHardwareDataType
export OMP_NUM_THREADS=4   "

The guide was a bit vague for my inexperience with "these" things ... 
Could you give me a step by step (more specific)? 

Thank you and sry..

**Comment by marcosvanella** [comment]
- Use a text editor to open in the directory of your user the file .bash_profile
- Copy the text lines I included in my previous post, at the end of this text file.
- Open a Terminal and type fds. You should get the default header from the fds executable.

**Comment by JohnSweden123** [comment]
I did the following:

<img width="637" alt="skarmavbild 2018-03-21 kl 23 56 07" src="https://user-images.githubusercontent.com/37638875/37741876-7ce12d04-2d63-11e8-83e6-b75d41aa3d1c.png">


<img width="1021" alt="skarmavbild 2018-03-21 kl 23 53 46" src="https://user-images.githubusercontent.com/37638875/37741811-356226ea-2d63-11e8-80be-5f799500e398.png">


When i try to run an example .fds in the launcher i get the same error as before..
<img width="1236" alt="skarmavbild 2018-03-21 kl 23 58 21" src="https://user-images.githubusercontent.com/37638875/37741944-c8f746f6-2d63-11e8-9a82-6fc865838085.png">

**Comment by marcosvanella** [comment]
Navigate in the terminal to one of the example directories and type:
$fds example.fds
where example.fds is one of the example fds input files you find there.
How are you submitting a job with this launcher?

**Comment by sbenkorichi** [comment]
We don't have desktop icon for fds to start using it from a launcher. You will need to use your terminal.
See this video, it might be a bit old, but it shows you how to run fds on mac.
https://www.youtube.com/watch?v=ZzptCR1HBb4

**Comment by gforney** [comment]
we no longer support the launcher .  you need to run fds from the command line.

**Comment by marcosvanella** [comment]
John, could you run fds from the command line? If so, please close the issue. Thank you.
