### ISSUE TITLE
HVAC Numerical Instability Error

### ISSUE THREAD

**Issue by alexismano** [firemodels/fds#6175]
I have a problem with my model.During my simulation i get a numerical instability error and i am pretty sure it is because of my HVAC  system.It is a system for 8 ship cabins.
This is the code:
[ship1.txt](https://github.com/firemodels/fds/files/1838431/ship1.txt)

**Comment by sbenkorichi** [comment]
Could you please edit this ticket, by uploading those lines in a .txt file than pasting this long lines on github. It's painful scrolling down, and torture the person who's working on it.
Check, other issues who others used to submit an issue.
See this example here 
https://github.com/firemodels/fds/issues/6134

**Comment by alexismano** [comment]
Yes I am sorry.Here it is
[ship1.txt](https://github.com/firemodels/fds/files/1838415/ship1.txt)

**Comment by rmcdermo** [comment]
@emanuelegissi Given your experience with this type of issue, could you please have a quick look?  If this looks like something that @drjfloyd needs to address, then move it on to him.  Thanks.

**Comment by drjfloyd** [comment]
You don't have realistic losses specified in your inputs. You only have roughness set but no losses for fittings (inlets, exits, tees, elbows, etc.). Unless you have very long lengths of duct, fitting losses drive the show. Without them you will not be modeling the actual behavior of the HVAC system as it responds to a fire. Additionally with all the rooms open to each other, you won't see much variance in pressure from compartment to compartment. Given that you may be better off just prescribing the design HVAC flows for the ducts connecting to each compartment.

**Comment by alexismano** [comment]
Ok i got it thank you very much!
