### ISSUE TITLE
SCARC timings not showing up in cpu file

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6191]
@SusanKilian ,
I'm running the scaling tests [here](https://github.com/firemodels/fds/tree/master/Validation/MPI_Scaling_Tests/FDS_Input_Files).  They are not finished, but when I look at the _cpu.csv file for the 1 mesh case for the three solvers (FFT or "test", GLMAT, and SCARC), it appears SCARC is taking practically zero time.  This is obviously not correct.  The timings for SCARC need to be added ASAP.  Do not put extraneous output to STD_ERR.  In the SCARC .err file I saw it looked like you were going to put the times there for SCARC.  It is time to get SCARC working like the rest of the code.  We cannot evaluate it otherwise.

**Comment by SusanKilian** [comment]
I'll have a look and add the timings asap ...

**Comment by SusanKilian** [comment]
Should all be done, please have a look if it works correctly.

**Comment by mcgratta** [comment]
I can see the timings for SCARC.
