### ISSUE TITLE
problem with level set case

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#6213]
ruddy,
the case, BT10m_2x2km_LS.fds, in the smv repo located at smv/Verification/WUI used to take 10 or so minutes to run.  Now it take a couple of hours.  This happened within the last couple of days.  I will double check tomorrow that it is not a compiler problem (also changed compilers recently but no other case is similarly affected).  Could you take a look at this.
thanks,
glenn

**Comment by mcgratta** [comment]
I noticed that the pressure was being unnecessarily iterated. Fixed that. Should help.

**Comment by gforney** [comment]
still taking a long time, couple of hours for smokebot which usually takes 30 minutes.  I"ll do a git bisect to see if I can narrow down when it started happening

I thought the level set method solved a set of ODEs and not the regular fds/cfd equations.  if my is memory correct, maybe the pdes are getting solved by mistake?

**Comment by mcgratta** [comment]
Ah, that's it. So now the level set is running with the FDS calculation. There is no non-CFD level set, at least not now. So maybe just reduce the time.

**Comment by rmcdermo** [comment]
Level set in this case solves a PDE, 2 space, 1 time dimension.

phi_t + a phi_x + b phi_y = 0

a and b are components of the spread rate.

**Comment by mcgratta** [comment]
It's not the level set, but rather the fact that the LS is being run with the CFD, as opposed to stand-alone which was done previously.

**Comment by rmcdermo** [comment]
Ah.  Well, if LS wants a wind field to work with, I guess it will need the CFD.

In FDS, you can set FREEZE_VELOCITY=T on MISC to turn off CFD with a specified velocity field.

**Comment by gforney** [comment]
I updated the leveset cases using randy's suggestion, adding 
SOLID_PHASE_ONLY=.TRUE.,FREEZE_VELOCITY=.TRUE.
to the &MISC line.  The run times of BT10m_2x2km_LS.fds was 8 minutes instead of 2 hours.
