### ISSUE TITLE
Problem with running FDS6 in Mac OS X

### ISSUE THREAD

**Issue by Hongyu002** [firemodels/fds#6219]
I am having a problem running the FDS and SmokeView programs on my Mac
It can not even run the example files.
When I try to run the example files i get the following error message

<img width="511" alt="wx20180401-164306 2x" src="https://user-images.githubusercontent.com/37987003/38177923-ba0e0644-35cd-11e8-8f2e-004fbfb52b93.png">

I think there must be an operation error or simple step I have missed causing this problem.

I would be appreciate that someone can point me what should I do to solve the problem.

**Comment by sbenkorichi** [comment]
Run fds from command line. Don't use the launcher.
Read this thread. 
https://github.com/firemodels/fds/issues/6173

**Comment by Hongyu002** [comment]
I am following the steps to add the paths to openmpi/FDS in my start up file.
but I can't find any file which name is  "~/.bash_profile file"

**Comment by sbenkorichi** [comment]
.bash_profile should be in your home directory, try this: 
`$ cat ~/.bash_profile `
if it returns some lines, then it exists, and you can then open it with your text editors. (note: . files are by default hidden. Either open them by terminal, or enable it read this[ post ](https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/) 
If it doesn't exists, then you can create one. Check this [post](https://stackoverflow.com/questions/30461201/how-do-i-edit-path-bash-profile-on-osx)
Once, you create it, then add the fds env lines.

**Comment by Hongyu002** [comment]
Thank you so much.
After creating the ".bash_profile" , I run FDS from the command line now!!!!

**Comment by sbenkorichi** [comment]
Ok, thanks for letting me know.
