### ISSUE TITLE
Possible discrepancy in Beyler Hood input files

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6237]
I noticed that the `TITLE` and the file name for Beyler Hood cases 318 and 389 are not consistent. The files are 
```
Beyler_Hood_propane_318_lr.fds
Beyler_Hood_propane_389_lr.fds
```
Could you confirm what the test parameters are. I added a test matrix to the [latest version of the FDS Validation Guide](https://drive.google.com/drive/folders/0B_wB1pJL2bFQUlJwMmNfaHlqME0)

**Comment by drjfloyd** [comment]
Checked all the files. Fixed a couple minor things and updated the table in the guide.

**Comment by mcgratta** [comment]
Thanks. Do you think it would be worth it to add to the table the mass exhaust rate and/or equivalence ratio? Are those tabulated in Beyler's thesis?

**Comment by drjfloyd** [comment]
Probably worth adding the exhaust flow rate.  I don't recall if he had a table of all the tests in the thesis (I used his folders of individual test data).
