### ISSUE TITLE
Typo in FDS user guide

### ISSUE THREAD

**Issue by Matmat13** [firemodels/fds#6238]
Hello,

I think that there is a typo at page 50 of the FDS user guide.
 
The following text is written both in temperature and density sections : 

&INIT XB=0.0,0.1,0.0,0.025,0.0,0.1,
MASS_FRACTION(1)=0.21, SPEC_ID(1)='OXYGEN',
MASS_FRACTION(2)=0.06, SPEC_ID(2)='PROPANE',
TEMPERATURE=60. /

Best regards,

Mat

**Comment by rmcdermo** [comment]
As mentioned just before those lines, the background species makes up the difference.  So, I think we are ok.

Species concentrations can be initialized using pairs of SPEC_ID(N) and MASS_FRACTION(N) where N is an ordinal index starting from 1. Note that N is not necessarily indicative of the order in which the species are listed in the input file. Also note that the background species cannot be specified when using MASS_FRACTION. The mass fraction of the background species will be set to account for any mass fraction not specified with other species. Make sure that you specify all species (components of MASS_FRACTION(N)) on the same INIT line for example,
&INIT XB=0.0,0.1,0.0,0.025,0.0,0.1,
      MASS_FRACTION(1)=0.21, SPEC_ID(1)='OXYGEN',
      MASS_FRACTION(2)=0.06, SPEC_ID(2)='PROPANE' /

**Comment by pdaley9** [comment]
Hello,

I think there is a typo on page 254 of the FDS User's Guide (Sixth Edition).

I believe the example
&SLCF PBY=0, QUANTITY='VELOCITY', VELOCITY=.TRUE., CELL_CENTERED=.TRUE. /

should read
&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=.TRUE., CELL_CENTERED=.TRUE. /

Thank you ,
Peter

**Comment by sbenkorichi** [comment]
Thanks for catching it.
Will be fixed in this pull request. 
https://github.com/firemodels/fds/pull/6952 

In the future, feel free to send PR
Thanks
