### ISSUE TITLE
cluster node setting

### ISSUE THREAD

**Issue by PershingWadlow** [firemodels/fds#6257]
Hi,
I installed linux version of FDS in my cluster. when I run my simulation its always running only in my head node. I followed the same procedure in website. 
 can anyone please guide me with what I am missing.

thanks.

**Comment by sbenkorichi** [comment]
Which procedure? 
I don't recall that we have documented on how to set a cluster. It's vague what you are asking for.
First of all, do you have an existing one or trying to build one? If it's already built, are you sure it's running other applications successfully before trying to run fds.

**Comment by mcgratta** [comment]
If this is a linux cluster, do the following.

Create a file containing the names of the nodes you want to use. You can call this file anything you want. Let's say it's `hostfile.txt`. It would look like this
```
node002
node005
node007
```
where `nodexxx` is the name of a node of your cluster.

Now run the job like this:
```
mpiexec -n 8 -ppn 3 -f hostfile.txt /home/username/FDS/FDS6/bin/fds jobname.fds
```
This will run an 8 mesh case putting 3 meshes on each node (node007 would get 2). If you want, you can put your mpiexec command in the background if you don't want to see the diagnostic output, or redirect to a `.err` file.

To check that things are working, login to a node and do a top command.

More on how to run Intel MPI jobs can be found by just searching on "Intel MPI linux" or similar. Let me know if this works.

**Comment by mcgratta** [comment]
Did my advice solve the problem?
