### ISSUE TITLE
Nozzle

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6259]
1. Is it possible to throw an error when this parameter is written wrong:

SPRAY_ANGLE(1,1:2) 

Instead of 
SPRAY_ANGLE(1:2,1)

To me, orientations of a nozzle spray is not clear enough in user guide. A figure showing the angles would be great to have. 

2. To confirm, is this figure correct?
The generated cone has a centerline which is coaxial with vector of orientation of the nozzle.
![image](https://user-images.githubusercontent.com/26166281/38683824-a194c68a-3e6e-11e8-8164-5c2044ae8a36.png)

3. I played with numbers and I ve got these results. 
The difference between first two are the places of the angles, 45 and 90. But I do not understand how it works. The third one is a mistery. I may understand it once I figure out the basic ones. 
![image](https://user-images.githubusercontent.com/26166281/38684662-7d90130a-3e70-11e8-90ac-b87341edd12c.png)

4. This nozzle flow pattern is being cut possibly due to nozzle's location with regard to mesh boundaries.  Could you please advice about the location of the nozzles? What should we avoid when placing nozzles?
[half is cut off.fds.txt](https://github.com/firemodels/fds/files/1903643/half.is.cut.off.fds.txt)
![image](https://user-images.githubusercontent.com/26166281/38685571-7fbe1ba2-3e72-11e8-95fb-84c701aa541e.png)

5. This one has a missing gap in flow pattern. I suspect again nozzle's location with regard to meshes. I hope I can avoid this by following your advice concerns also point # 4 .
[pacman.fds.txt](https://github.com/firemodels/fds/files/1903661/pacman.fds.txt)
![image](https://user-images.githubusercontent.com/26166281/38685517-672b0500-3e72-11e8-922d-1331250fdde3.png)

Thank you.

**Comment by mcgratta** [comment]
1. `SPRAY_ANGLE` is a 2-D array with dimension (2,2). There is no way to detect an error on input. The user must know what the two dimensions mean. Most users just use the first dimension to specify the spray angle that applies to all lateral directions.
2. Your sketch is correct, and I added something similar to the User's Guide. See the commit #6260.
3. The elliptical spray pattern that is achieved via the second dimension of `SPRAY_ANGLE` was intended to create spray curtains. A good example is to set `SPRAY_ANGLE(1:2,1)=0,90` and `SPRAY_ANGLE(1:2,2)=0,5`. 
4. Do not put the nozzle within `OFFSET` of the mesh boundary. See commit #6260 for text I added to the User's Guide.
5. See 4.

**Comment by Er9y714** [comment]
Thank you for your reply.  # 2, 4 and 5 are clear.  Thanks for adding the figure as well. 

Regarding # 1, I am not sure if I explained it well.  FDS does not model the ellipse when I write ...(1,1:2)... instead of ...(1:2,1)... The calculation starts without error but modelling is faulty.  It do not see the relevance of knowing what two dimension is. Instead, it seems to me only as a typo in user input.

As for # 3, Does the first value have to be 0 in the array? Also I do not see any difference in spray pattern between two inputs below. Why?:

      SPRAY_ANGLE(1:2,1)=0.0,10.0,
      SPRAY_ANGLE(1:2,2)=80.0,90.0/

      SPRAY_ANGLE(1:2,1)=0.0,10.0,
      SPRAY_ANGLE(1:2,2)=0.0,90.0/

What is the allowed range of these parameters A and B?  SPRAY_ANGLE(1:2,1)=A,B,

**Comment by mcgratta** [comment]
Does the code work properly when the guidance in the User's Guide is followed? If so, I prefer to leave things alone. Trying to do error checking on this will probably result in more error and confusion. 

The first value does not have to be zero.

Check the spray pattern on the floor using boundary quantity ``AMPUA'`.
```
&BNDF QUANTITY = 'AMPUA' PART_ID = 'water drops'/
```
A and B can range from 0 to 180.

**Comment by Er9y714** [comment]
- Yes,  FDS works properly when User guide is followed. 

- They seem to be identical. 

SPRAY_ANGLE(1:2,1)=0.0,10.0,  SPRAY_ANGLE(1:2,2)=80.0,90.0
![image](https://user-images.githubusercontent.com/26166281/38736602-dd0c958a-3f2c-11e8-987e-7830cb7d626b.png)

SPRAY_ANGLE(1:2,1)=0.0,10.0,  SPRAY_ANGLE(1:2,2)=00.0,90.0/
![image](https://user-images.githubusercontent.com/26166281/38736717-3964ff0c-3f2d-11e8-81a1-2c929bf35fe9.png)

**Comment by mcgratta** [comment]
Perhaps, but the desired effect is to make a water curtain, so it appears to work regardless of the inner angle y axis spray.

**Comment by d21102653** [comment]
Hello
I would like to know please, how to define a diffusion anlgle according to a 360° disc knowing that my nozzle is oriented along the x axis on fds .

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs, this question should be submitted to the discussion forum.

**Comment by d21102653** [comment]
thank you drjfloyd.
