### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by Hongyu002** [firemodels/fds#6265]
Hello,

I am trying to run a simulation  and I receive the error message "forrtl: severe (174): SIGSEGV, segmentation fault occurred" as soon as the simulation starts. 

Hope anyone can give me some advise. THANKS

My input file is:

&HEAD CHID='0_02jetfire', TLTLE='jet fire test/
&TIME T_END=20.0/
&DUMP RENDER_FILE='0_02jetfire.ge1', DT_RESTART=300.0/
&MISC TMPA=30.0/

&MESH ID='MESH', IJK=35,220,230, XB=3.0,10.0,2.0,8.0,0.0,7.0/
&TRNY CC=2.27273, PC=3.0, MESH_NUMBER=1/ MESH
&TRNY CC=7.72727, PC=7.0, MESH_NUMBER=1/ MESH
&TRNZ CC=0.304348, PC=1.0, MESH_NUMBER=1/ MESH
&TRNZ CC=6.3913, PC=5.0, MESH_NUMBER=1/ MESH

&PART ID='Fuel',
      SPEC_ID='PROPANE'
      DIAMETER=500/

&REAC ID='getfire',
      FUEL='PROPANE'/

&SURF ID='supply',
      RGB=26,204,26,
      VEL=-101,
      PART_ID='Fuel',
      NPPC=10000,
      PARTICLE_MASS_FLUX=275.0/

&SURF ID='burner',
      COLOR='RED',
      HRRPUA=1000.0/

&VENT SURF_ID='OPEN', XB=3.0,3.0,2.0,8.0,0.0,7.0/ Mesh Vent: MESH [XMIN]
&VENT SURF_ID='OPEN', XB=3.0,10.0,8.0,8.0,0.0,7.0/ Mesh Vent: MESH [YMAX]
&VENT SURF_ID='OPEN', XB=3.0,10.0,2.0,2.0,0.0,7.0/ Mesh Vent: MESH [YMIN]
&VENT SURF_ID='OPEN', XB=3.0,10.0,2.0,8.0,7.0,7.0/ Mesh Vent: MESH [ZMAX]
&VENT SURF_ID='supply', XB=9.99,9.99,5.0,5.02,1.3,1.32/ fule
&VENT SURF_ID='burner', XB=9.99,9.99,5.0,5.02,1.26,1.28/ burner

&ISOF QUANTITY='HRRPUV', VALUE=6.5/
&ISOF QUANTITY='TEMPERATURE', VALUE=537.0/

&SLCF QUANTITY='TEMPERATURE', PBZ=1.3/
&SLCF QUANTITY='TEMPERATURE', PBY=5.0/

&TAIL /

<img width="569" alt="qq20180414-114615 2x" src="https://user-images.githubusercontent.com/37987003/38770506-a4834ba2-3fd9-11e8-9357-0732b1ba9e21.png">

**Comment by sbenkorichi** [comment]
This is know issue. Do this on same terminal before you run the job.` $ulimit -s unlimited `
Then run the job. If it works, then add that line in your .bashrc file, you find it in your home directory (i.e. /home/username/.bashrc )

**Comment by Hongyu002** [comment]
I tried this but it didnt work.
It returned
-bash:unlimit: stack size: cannot modify limit:operation not permitted

**Comment by sbenkorichi** [comment]
You seems to be having a Mac, it might be slightly different than unix. @marcosvanella  or @rmcdermo can give more feedback on this.
try the following to know the sys limits first:` $ ulimit -a` , post what it says,
your startup file should be bashrc_profile instead of bashrc, I just recall your previous post here https://github.com/firemodels/fds/issues/6219. So, just put it in that file.
Try this as well 
```
$ ulimit -Hs unlimited
$ ulimit -Ss unlimited
```
If it doesn't work, then we need to change the default ulimits on the system, that might involve changes in the lanuchd.conf -- @gforney  will have a better suggestion on this as I'm not Mac user.

**Comment by rmcdermo** [comment]
I added the startup line here:

https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-under-Mac-OS-X

Glenn, can you see that the bundle script for OSX adds this unlimit command to the "lines to add to startup".  Thanks.

**Comment by Hongyu002** [comment]
when I use ulimit -a，it says ：

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

**Comment by Hongyu002** [comment]
hi
it works with $ ulimit -Ss unlimited
:)thank you so much

**Comment by yauz3** [comment]
Hi, I have the same problem. I am trying to use GalaxyDock3 program. It works sometimes, however, it gives the same error.
I have already tried:
ulimit -s unlimited
ulimit -d unlimited
ulimit -f unlimited
ulimit -m unlimited
ulimit -n 7168
ulimit -Hs unlimited
ulimit -Ss unlimited
in order to solve problem. Unfortunately, I am taking same error. I am using ubuntu side by windows. Is it the reason?
thanks.

**Comment by rmcdermo** [comment]
On macOS, I have to increase both stack and maxfiles like this:
```
# unlimit stack and increase maxfiles for OSX
ulimit -s 65532 -n 2048
```

**Comment by sbenkorichi** [comment]
Sorry, I'm not following here; are you trying to use FDS or a different program?

**Comment by yauz3** [comment]
Galaxydock3 is a molecular docking program. Sometimes it works, but sometimes gives forrtl: severe(174) error.
my options are:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63430
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 7168
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63430
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited


I have already ready all over the Internet. Everyone says about stack size. Even if I changed it, the same error appears.

**Comment by sbenkorichi** [comment]
I can't tell much without knowing exactly how you're running it and how your machine is set. The only thing that pops up is that you might be running the application with scheduler which is different, although it shows its unlimited in the terminal but when it runs with scripts it's not. You need to provide more details so someone can help.

**Comment by yauz3** [comment]
this is the program link:
http://galaxy.seoklab.org/softwares/galaxydock.html

It allows us to use in terminal:
python GalaxyDock3/script/run_GalaxyDock3.py -d /home/yavuz/yavuz_proje/docking/proteins/GalaxyDock3/ -p 2gl0_receptor.pdb -l 2gl0_ligand.mol2 -x 14 -y 20 -z 11 -size_x 5 -size_y 5 -size_z 5

The code is perfectly working. When I changed 2gl0_ligand.mol2 to Erythromycin.mol2, which is a big drug and have some wrong values, it gives the error. Even if I prepared file manually, it did not work.  

Thank you for your help. I am really new starter; therefore, I cannot explain very well sorry.

**Comment by JinwenDong** [comment]
Hi, I having the same problem. I run the FDS file through a script that puts it on the server node.
Here is the return codes: 

Starting FDS ...

 MPI Process      0 started on node2b07.ecdf.ed.ac.uk
 MPI Process      2 started on node2b07.ecdf.ed.ac.uk
 MPI Process      1 started on node2b07.ecdf.ed.ac.uk
 MPI Process     16 started on node2b07.ecdf.ed.ac.uk
 MPI Process     25 started on node2b07.ecdf.ed.ac.uk
 MPI Process      7 started on node2b07.ecdf.ed.ac.uk
 MPI Process     10 started on node2b07.ecdf.ed.ac.uk
 MPI Process     13 started on node2b07.ecdf.ed.ac.uk
 MPI Process     20 started on node2b07.ecdf.ed.ac.uk
 MPI Process      5 started on node2b07.ecdf.ed.ac.uk
 MPI Process      6 started on node2b07.ecdf.ed.ac.uk
 MPI Process     22 started on node2b07.ecdf.ed.ac.uk
 MPI Process     23 started on node2b07.ecdf.ed.ac.uk
 MPI Process      3 started on node2b07.ecdf.ed.ac.uk
 MPI Process      9 started on node2b07.ecdf.ed.ac.uk
 MPI Process     21 started on node2b07.ecdf.ed.ac.uk
 MPI Process     29 started on node2b07.ecdf.ed.ac.uk
 MPI Process     15 started on node2b07.ecdf.ed.ac.uk
 MPI Process     28 started on node2b07.ecdf.ed.ac.uk
 MPI Process      8 started on node2b07.ecdf.ed.ac.uk
 MPI Process     27 started on node2b07.ecdf.ed.ac.uk
 MPI Process     17 started on node2b07.ecdf.ed.ac.uk
 MPI Process     30 started on node2b07.ecdf.ed.ac.uk
 MPI Process     34 started on node2b07.ecdf.ed.ac.uk
 MPI Process     11 started on node2b07.ecdf.ed.ac.uk
 MPI Process     12 started on node2b07.ecdf.ed.ac.uk
 MPI Process     14 started on node2b07.ecdf.ed.ac.uk
 MPI Process     19 started on node2b07.ecdf.ed.ac.uk
 MPI Process     24 started on node2b07.ecdf.ed.ac.uk
 MPI Process     26 started on node2b07.ecdf.ed.ac.uk
 MPI Process     18 started on node2b07.ecdf.ed.ac.uk
 MPI Process      4 started on node2b07.ecdf.ed.ac.uk
 MPI Process     31 started on node2b07.ecdf.ed.ac.uk
 MPI Process     32 started on node2b07.ecdf.ed.ac.uk
 MPI Process     33 started on node2b07.ecdf.ed.ac.uk

 Reading FDS input file ...

WARNING: SPEC wood is not in the table of pre-defined species. Any unassigned SPEC variables in the input were assigned the properties of nitrogen.

 Fire Dynamics Simulator

 Current Date     : July  6, 2024  23:54:18
 Revision         : FDS-6.9.1-0-g889da6a-release
 Revision Date    : Sun Apr 7 17:05:06 2024 -0400
 Compiler         : Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.7.1 Build 20221019_000000
 Compilation Date : Apr 09, 2024 13:24:51

 Number of MPI Processes:  35

 MPI version: 3.1
 MPI library version: Intel(R) MPI Library 2021.6 for Linux* OS


 Job TITLE        : CaseB1
 Job ID string    : CaseB1

 Time Step:       1, Simulation Time:      0.04 s
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libc.so.6          0000150D32C54DB0  Unknown               Unknown  Unknown
fds                0000000006B256E4  Unknown               Unknown  Unknown
fds                0000000006B121A0  Unknown               Unknown  Unknown
fds                0000000006AB8148  Unknown               Unknown  Unknown
fds                000000000040A71D  Unknown               Unknown  Unknown
libc.so.6          0000150D32C3FEB0  Unknown               Unknown  Unknown
libc.so.6          0000150D32C3FF60  __libc_start_main     Unknown  Unknown
fds                000000000040A636  Unknown               Unknown  Unknown

**Comment by marcosvanella** [comment]
Hi @JinwenDong, segfaults can be due to many things. Please open a new issue and attach your input file. Change the file extension to .txt instead of .fds.
