### ISSUE TITLE
BNDF_TIME_INTEGRALS does not work after RESTART??

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6269]
See [this discussion post](https://groups.google.com/forum/#!topic/fds-smv/DqFL794wuW4)

**Comment by rmcdermo** [comment]
Hello FDS-Team,

i have a big problem with the test result of the &BNDF QUANTITY = 'INCIDENT HEAT FLUX', STATISTICS='TIME INTEGRAL'/ after restart 350 s of the calculation. The calculation of the surface integral starts again at zero and not continue with the results last until 350 s. 

The rest of the results i. e.devc or &BNDF QUANTITY = 'WALL TEMPERATURE'/ are complete fine.

Regards Thomas

**Comment by rmcdermo** [comment]
Please simplify your input file and provide an example that runs.  With the current case, I get

```
ERROR: SURF_ID BETON1 not found for VENT 5, line number 38 (CHID: BS8414_VAR3)

ERROR: SURF_ID BETON1 not found for VENT 5, line number 38 (CHID: BS8414_VAR3)

ERROR: SURF_ID BETON1 not found for VENT 5, line number 38 (CHID: BS8414_VAR3)

ERROR: SURF_ID BETON1 not found for VENT 5, line number 38 (CHID: BS8414_VAR3)

ERROR: SURF_ID BETON1 not found for VENT 5, line number 38 (CHID: BS8414_VAR3)

STOP: FDS was improperly set-up (CHID: BS8414_VAR3)
```

**Comment by Thomas1896** [comment]
[ST2_10cm.txt](https://github.com/firemodels/fds/files/1921374/ST2_10cm.txt)
Dear Randy,

an example for a simple input file you can find here.

Regards
Thomas

**Comment by rmcdermo** [comment]
@Thomas1896 I am having a hard time exactly reproducing your problem.  What I find instead is that the .bf images in SMV look correct until the very last time step.  Then their error depends on the ratio of DT_RESTART to the total simulation time.

I also find that at DEVC positioned on the wall gives exactly the same result both with and without restart.  So, that is good, and perhaps you can use that temporarily if you just need numbers.

Here is the simple input file I am playing with:
```
&HEAD CHID='test'/
&MESH IJK=10,10,10, XB=0,1,0,1,0,1/
&TIME T_END=99, DT=0.1, LOCK_TIME_STEP=T /
&DUMP DT_RESTART=10.0/
&MISC RESTART=.FALSE./
&SURF ID='hot', TMP_FRONT=1000/
&VENT MB='XMAX', SURF_ID='hot'/
&BNDF QUANTITY='INCIDENT HEAT FLUX', STATISTICS='TIME INTEGRAL'/
&DEVC XYZ=0.001,.5,.5, IOR=1, QUANTITY='INCIDENT HEAT FLUX', STATISTICS='TIME INTEGRAL', ID='QRAD'/
&TAIL /
```

Using the latest code, please see if you can reproduce the problem as I describe.  Again, what I am seeing is that this case looks correct in SMV between 90 and 98.xx seconds.  Then, on the very last step the boundary image values get small.

**Comment by Thomas1896** [comment]
Thannks for your support. I think, i couldn't descripe the problem exactly enough. I try it again. I calculate on a cluster and the wall time is limited until 199 hours per calculation. After that, i have to restart my calculation from last saving. For the file in the link the time of restart was 380 s after finishing at the cluster. The results in the boundary file for time integral of gauge heat flux in smokeview starts after restart in the 380 s to account from the beginning. 

My problem ist, that the total calculation time of the calibrabtion test is 3000 seconds. So FDS will start at every restart to account the time integral for the boundary file from zero and not from the last time step of accounting (maybe every 380 s) 
[BS3_5cm.txt](https://github.com/firemodels/fds/files/1921520/BS3_5cm.txt)
![bndf-gauge-heat-flux 384 s](https://user-images.githubusercontent.com/38475677/38895549-a5d5a6ee-4290-11e8-8b82-98f598d3c5de.JPG)
![bndf-gauge-heat-flux 372 s](https://user-images.githubusercontent.com/38475677/38895550-a5edea24-4290-11e8-99f4-3cf58a69526f.JPG)

**Comment by Thomas1896** [comment]
Thannks for your support. I think, i couldn't descripe the problem exactly enough. I try it again. I calculate on a cluster and the wall time is limited until 199 hours per calculation. After that, i have to restart my calculation from last saving. For the file in the link the time of restart was 380 s after finishing at the cluster. The results in the boundary file for time integral of gauge heat flux in smokeview starts after restart in the 380 s to account from the beginning.

My problem ist, that the total calculation time of the calibrabtion test is 3000 seconds. So FDS will start at every restart to account the time integral for the boundary file from zero and not from the last time step of accounting (maybe every 380 s)
![bndf-gauge-heat-flux 384 s](https://user-images.githubusercontent.com/38475677/38895666-ecaeefb2-4290-11e8-92ef-45fc86450d3f.JPG)
![bndf-gauge-heat-flux 372 s](https://user-images.githubusercontent.com/38475677/38895667-ecc509fa-4290-11e8-9dd4-6cd7b88d83fa.JPG)

**Comment by rmcdermo** [comment]
@Thomas1896 I understand.  But please see if you can reproduce my test case.  In particular, make sure that you see the correct behavior for a DEVC with STATISTICS='TIME INTEGRAL'.

**Comment by rmcdermo** [comment]
@Thomas1896 I'm trying to see where this issue stands.  Can you reproduce my test?
