### ISSUE TITLE
velocity magnitude inconsistent with components

### ISSUE THREAD

**Issue by ghost** [firemodels/fds#6293]
Hi,

I have a problem that in a slice file, the velocity magnitude output is inconsistent with the vector sum obtained from the components. My simplified case consists of a square inlet vent at a uniform velocity, and I created a slice file at the inlet surface. At (0,0), the x-, y-, and z- components are 2.49e-13, 9.84e-16, 1.8e+00 respectively, but the velocity magnitude is 1.71+00. The same inconsistency occurs for other points with non-zero velocity components. I have attached the fds file and the SLCF output converted with fds2ascii (at t_end = 5 s) for your reference.

Another point I would like to mention is that at the edge of the inlet (e.g. at (-0.004,0)), the velocity is 0.9 instead of 1.8. Judging from 0.9 = 1.8/2, I suppose this is from the interpolation of slice files. Is it possible that I access the values stored in fds directly instead of an interpolated result? I suppose setting as CELL_CENTERED = .TRUE. does not make sense since the velocity components are stored on cell faces in fds, instead of cell centers. In any case, it will be better if the way how slice files interpolate results is known.

Thanks in advance.

Edmond

[case4.zip](https://github.com/firemodels/fds/files/1923748/case4.zip)

**Comment by rmcdermo** [comment]
Interpolation is linear to nodes.  Details are in DUMP_SLCF in [dump.f90](https://github.com/firemodels/fds/blob/master/Source/dump.f90).

It is ok to use CELL_CENTERED=T with VECTOR=T for velocity.  This will give raw vector components in Smokeview.  Alternatively, you can dump a UVWFILE (see user guide) or you can use QUANTITY='VOLUME FLOW WALL' or QUANTITY='NORMAL VELOCITY' to see the velocity assigned to a VENT.
