### ISSUE TITLE
Model stopped

### ISSUE THREAD

**Issue by alexismano** [firemodels/fds#6306]
Hello, i have a problem with my model.Although i have selected a simulation time of 50sec my model simulation stops at 21sec.Can you help me?

[ship.txt](https://github.com/firemodels/fds/files/1931091/ship.txt)

**Comment by rmcdermo** [comment]
What error message are you getting?

**Comment by alexismano** [comment]
I don't think there was an error message or maybe i could not figure it out.I think it has something to do with the hvac system

**Comment by drjfloyd** [comment]
You have fully specified flows in your HVAC system so I do not think that is the cause.   Your HVAC system could be simplified some, but I don't think that is causing you problems. For example:

&VENT ID='Vent22', SURF_ID='HVAC', XB=2.7,3.4,0.25,0.25,2.1,2.3/ 
&HVAC ID='Node22', TYPE_ID='NODE', DUCT_ID='Duct18', VENT_ID='Vent22'/
&HVAC ID='Duct18', TYPE_ID='DUCT', DIAMETER=0.3048, NODE_ID='Node22','Node30', ROUGHNESS=1.0E-3, LENGTH=0.125/
&HVAC ID='Node30', TYPE_ID='NODE', DUCT_ID='Duct18','Duct22', XYZ=3.05,0.125,2.2/
&HVAC ID='Duct22', TYPE_ID='DUCT', DIAMETER=0.3048, FAN_ID='Fan 1', NODE_ID='Node30','HVAC Return Node 1', ROUGHNESS=1.0E-3, LENGTH=6.45/

You could combine these two ducts into one duct of length 6.575 m and do the same elsewhere in the model

The issue might be a combination of a few things
1) Your domain is fully sealed with no leakage and your HVAC system has fixed flows.  There is no way for the pressure increase from the fire to vent anywhere. 
2) Your HVAC system uses a fixed volume flow.  This means as the compartment heats up you will be adding more mass via supply then you remove by exhaust.
3) FYI='NIST – Completely Made Up'   Properties we fabricate for example problems are designed to illustrate specific behaviors or features of FDS. They may or may not have realistic behavior.

**Comment by alexismano** [comment]
Ok thank you!

**Comment by alexismano** [comment]
I ran the simulation again to check what the error was and it stopped again at 21sec and it says there is a numerical instability error.So what could be the reason?Maybe if i don't use controls for the smoke detectors and leave the doors open all the time may help?

**Comment by drjfloyd** [comment]
I gave you three possible causes, two of which were related to your domain
having no means of relieving pressure.  I suggest you add leakage and make
sure that your made up pyrolysis parameters are behaving reasonably.
