### ISSUE TITLE
Source release is wrong version?

### ISSUE THREAD

**Issue by tfrench** [firemodels/fds#6320]
Hi. I'm trying to compile FDS from source (https://github.com/firemodels/fds/archive/FDS6.6.0.tar.gz) for Ubuntu (in Docker), and I just noticed that the version is `6.5.3`, not `6.6.0`.

After compilation, when I run `fds` I get:
```

 Fire Dynamics Simulator

 Current Date     : April 24, 2018  10:21:01
 Version          : FDS 6.5.3
 Revision         : -
 Revision Date    :
 Compiler         : Gnu gfortran 7.2.0-1ubuntu1~14.04)
 Compilation Date : Apr 24, 2018  10:01:20

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: Open MPI v3.0.1, package: Open MPI root@d9e4462ec830 Distribution, ident: 3.0.1, repo rev: v3.0.1, Mar 29, 2018

 Consult FDS Users Guide Chapter, Running FDS, for further instructions.

 Hit Enter to Escape...
```

I also checked the source code:
`Line 103 (main.f90): WRITE(VERSION_STRING,'(A)') 'FDS 6.5.3'`

I've installed FDS on my Mac successfully from the pre-compiled binary: https://github.com/firemodels/fds/releases/download/FDS6.6.0/FDS_6.6.0-SMV_6.6.0_osx64.sh. 

When I run `fds`, I get:
```

 Fire Dynamics Simulator

 Current Date     : April 24, 2018  11:26:26
 Version          : FDS 6.6.0
 Revision         : FDS6.6.0-131-g88ae75a14-HEAD
 Revision Date    : Wed Nov 1 16:03:29 2017 -0400
 Compiler         : Intel ifort 17.0.4
 Compilation Date : Nov 01, 2017  21:03:37

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Open MPI v3.0.0, package: Open MPI gforney@ignis.el.nist.gov Distribution, ident: 3.0.0, repo rev: v3.0.0, Sep 12, 2017

 Consult FDS Users Guide Chapter, Running FDS, for further instructions.

 Hit Enter to Escape...
```

Thanks.

Thomas

**Comment by sbenkorichi** [comment]
Hi Thomas,
That was a mistake and Glenn has fixed it. It won't happen in the coming releases. 
Thanks !

**Comment by tfrench** [comment]
OK, thanks. 

You might want to put a note somewhere? I spent some time trying to get it to work. I'm now compiling off master directly.

**Comment by rmcdermo** [comment]
I added a note to the release.
