### ISSUE TITLE
Replacement of NO_RAMPS with TAU_DEFAULT=0. not working for HVAC cases

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#6321]
Skimming through latest verification guide and see that the HVAC cases with mass transport plots are not correct. Transport times are delayed

After some bisecting drilled down to 7869544b0593214ac67b0ab820f30dd3011d5a29 which was the replacement of NO_RAMPS with TAU_DEFAULT=0 by @mcgratta  - don't know background to change so don't want to fiddle

Attached image gives 7869544b0593214ac67b0ab820f30dd3011d5a29 build and release build respectively
![image](https://user-images.githubusercontent.com/13219265/39202605-4c28aaa6-47ea-11e8-97f1-115b2b9d462a.png)
![image](https://user-images.githubusercontent.com/13219265/39202668-7f0ad99e-47ea-11e8-99c3-880b49dfaf1b.png)

**Comment by mcgratta** [comment]
That's me. I'll fix it. Thanks.

**Comment by mcgratta** [comment]
Should be fixed. Let me know if you see other oddities.

**Comment by bmralph** [comment]
Thanks Kevin - all looks good now
