### ISSUE TITLE
Numerical instability in particle energy transport, TMP_G

### ISSUE THREAD

**Issue by Hongyu002** [firemodels/fds#6324]
Hi
I am trying to simulate a horizontal jet fire by injecting propane from a nozzle.
But each time after running the program, it stops several time steps later and returns 

Numerical instability in particle energy transport, TMP_G

Here is my input file:

&HEAD CHID='Jet_jire', TITLE='Test Simulation of propane jet fire' /

&MESH IJK=64,54,54, XB=0.0,5.0,0.0,2.0,0.0,3 /
&TIME T_END=3./

&MISC TMPA=25.3, HUMIDITY=50.9 /

&REAC ID='Propane_jet_fire'
      FUEL='PROPANE'/

&PART ID='Propane droplets'
      SPEC_ID='PROPANE'
      DIAMETER=500./

&PROP ID='nozzle'
      PART_ID='Propane droplets'
      MASS_FLOW_RATE=0.015
      PARTICLE_VELOCITY=27.5
      SPRAY_ANGLE=45,0
      SMOKEVIEW_ID='nozzle'/

&DEVC ID='nozzle_1'
      XYZ=0.2,1,0.8
      PROP_ID='nozzle'
      QUANTITY='TIME'
      ORIENTATION=1,0,0
      SETPOINT=0./

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&SLCF PBY=1.0,QUANTITY='VELOCITY',VECTOR=.TRUE. /
&SLCF PBY=1.0,QUANTITY='TEMPERATURE',VECTOR=.TRUE. /
&SLCF PBY=1.0,QUANTITY='MASS FRACTION',SPEC_ID='PROPANE' /

&TAIL /

**Comment by mcgratta** [comment]
What version of FDS are you running.

**Comment by drjfloyd** [comment]
Are you running with the latest release of FDS?

**Comment by Hongyu002** [comment]
I am using FDS 6.6.0

 Fire Dynamics Simulator

 Current Date     : April 24, 2018  14:55:22
 Version          : FDS 6.6.0
 Revision         : FDS6.6.0-131-g88ae75a14-HEAD
 Revision Date    : Wed Nov 1 16:03:29 2017 -0400
 Compiler         : Intel ifort 17.0.4
 Compilation Date : Nov 01, 2017  21:03:37

**Comment by drjfloyd** [comment]
Due to a previous issue for FDS 6.6.0 the routine was changed so particle errors will just result in a warning message rather than killing the run. This will leave it up to the user to decide if it is just occasional particles (in which case likely no impact on the answer) or a continuous problem.  In this case with the current source there are ~2000 live particles at any point in time and about one particle has an issue every 25 time steps.

**Comment by mcgratta** [comment]
Try this. Add `PARTICLES_PER_SECOND=50000` to the `PROP` line and `DT=0.005` to the `TIME` line.

**Comment by Hongyu002** [comment]
It seems to be ok now.At least it already calculates 600 time steps with 2.03s results without stopping.
I am not very sure because the simulation becomes quite low right now. 

Thank you so much. If there is still Numerical instability problem, I will contact you again.

**Comment by Hongyu002** [comment]
Hi,sorry to bother you again. @mcgratta 
I try to increase the MASS_FLOW_RATE to 0.025 and PARTICLE_VELOCITY to 46.5 and the program stops again like before.
So I want to know why will this error happen and what should I do in the future to avoid it?

**Comment by mcgratta** [comment]
I do not have a good answer for you. Try using a `RAMP` to increase the mass flow rate more slowly.
