### ISSUE TITLE
Request: &PROF quantities for solid &PARTs

### ISSUE THREAD

**Issue by dblasen** [firemodels/fds#6331]
I am looking at the breakdown of solid particles exposed to flame and trying to track the quantities of materials. For my purposes, it would be ideal to specify a profile output on a solid particle.  
  
I have found that using a profile on an obstruction provides excellent results for tracking solid material components and temperature, but lacks output quantities I need (like total mass of the obstruction) and is limited to Cartesian geometries.  
  
Using devices to track material quantities at certain depths inside of particles does work but introduces another issue since the materials must be allowed to shrink or swell. Devices reporting at specified depths are not very helpful if the depth is changing.  
  
Is this something that can be added?

**Comment by rmcdermo** [comment]
Can you please provide a simple example of what you mean for the OBST and PROF output and then what you would like so see for the PART?

**Comment by dblasen** [comment]
Sure. So if, for example, I want to see the density of the material 'char' across the Z-axis of an obstruction, I can specify it like this:

```
&OBST XB = 1.35,1.65,1.480,1.550,0.6,0.65, SURF_ID='square_stick_surf', ID='stick'/
&PROF XYZ=1.5,1.5,0.600, QUANTITY='CHAR', ID='char_prof', IOR=3 /
```

and I will get a profile output file (CSV) with this structure (truncated for space):

```
char_prof                                                   
Time(s), Npoints, Npoints x Depth (m), Npoints x Value

 0.0000000E+000,  312, 0.0000000E+000, 1.5434084E-004, 3.0868167E-004, 4.6302251E-004, 6.1736334E-004, ...
```

This makes for a simpler input file and it also appears to handle material shrinkage with less distortion of the quantities at the edges where shrinkage is more significant.  
  
I would like to have an analogous treatment for &PART where the user can either specify a &PROF by XYZ and it will move along IOR to find the solid particle (just like it does for &OBST) like this:
```
&PART ID='stick', SAMPLING_FACTOR=1, SURF_ID='stick_surf', STATIC=.TRUE. /
&INIT ID='stick', XYZ=1.5,1.5,0.60, PART_ID='stick' /
&PROF XYZ=1.5,1.5,0.600, QUANTITY='CHAR', ID='char_prof', IOR=3 /
```
or alternatively where the user specifies by INIT_ID or PART_ID (like for &DEVC at depth in a &PART) like this:
```
&PART ID='stick', SAMPLING_FACTOR=1, SURF_ID='stick_surf', STATIC=.TRUE. /
&INIT ID='stick', XYZ=1.5,1.5,0.60, PART_ID='stick' /
&PROF INIT_ID='stick', QUANTITY='CHAR', ID='char_prof', IOR=3/
```

**Comment by mcgratta** [comment]
This can probably be done easily. I just never had the need for it myself.

**Comment by mcgratta** [comment]
I added this capability, which will be available with the next release.

**Comment by dblasen** [comment]
Thanks for addressing this so quickly! However, I found some odd profile behavior related to which surface geometry is applied to the particle. I think this wasn't an issue until now because obstructions are always cartesian in geometry.  
  
In the case of the temperature profile of a cartesian particle in a heated environment, we see both surfaces heat up and produce a gradient towards the center of the particle. In the cases of spherical and cylindrical particles, we see *only one* side heat up. It looks more like a semi-infinite solid.  
  
Here's a simple FDS input file that showcases the behavior. Note how the profile output files for cylinders and spheres show almost no change at the greatest depth of the profile (that is, the other side of the particle).
[surf_prof_issue.txt](https://github.com/firemodels/fds/files/1985102/surf_prof_issue.txt)

**Comment by mcgratta** [comment]
Yes, this is confusing. The parameter `THICKNESS` on the `SURF` line means "half-thickness" when applied to particles. This is a remnant of the fact that `OBST` solids and `PART` solids evolved separately. What you need to do is add `BACKING='INSULATED'` to the `SURF` line for the Cartesian particle. This will effectively force FDS to do the heat conduction calculation on the half-thickness.

I'll add some explanation to the User's Guide.

**Comment by dblasen** [comment]
This is good; it puts everything on even footing for comparison. The last thing to resolve here are the 'depth' values for half-thickness measurements. As seen below (same file as above, but `BACKING='INSULATED'`), the current output suggests that we're measuring all the way through the particle when we're only measuring halfway through. This is also an issue for other geometries on particles. First and last output rows only for brevity; notice the depths range from 0 to 5cm which is the full thickness of the particle.  
  
```
prof_test1                                                  
Time(s), Npoints, Npoints x Depth (m), Npoints x Value
 0.0000000E+000,    9, 0.0000000E+000, 1.6666667E-003, 5.0000000E-003, 1.1666667E-002, 2.5000000E-002, 3.8333333E-002, 4.5000000E-002, 4.8333333E-002, 5.0000000E-002, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001, 2.0000000E+001
  
...  
  
 1.0000000E+001,    9, 0.0000000E+000, 1.6666667E-003, 5.0000000E-003, 1.1666667E-002, 2.5000000E-002, 3.8333333E-002, 4.5000000E-002, 4.8333333E-002, 5.0000000E-002, 2.7477770E+002, 1.7817324E+002, 8.3124884E+001, 3.0969332E+001, 2.0405745E+001, 2.0009497E+001, 2.0000770E+001, 2.0000215E+001, 2.0000166E+001  
```  
  
No rush on this for me-- I can hack around it in my visualization script. Thanks for the changes!

**Comment by mcgratta** [comment]
Unless you set an `ORIENTATION` (which confuses this even more), it is assumed that the particle is heated uniformly on all sides. Your Cartesian particle is actually 10 cm thick. The PROF file just shows you the temperature profile from the surface to the center.

**Comment by dblasen** [comment]
Ah, I mistook the definition for the Cartesian particle. In that case, this is totally addressed. Thanks again!
