### ISSUE TITLE
Plot legend out of bounds

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6334]
I suggest that somehow you indicate that the color represents the fuel and shape represents the extinguishing agent. The legend would probably need to be drawn manually. Also, use log-log.
[FDS_Minimum_Extinguishing_Concentration.pdf](https://github.com/firemodels/fds/files/1951277/FDS_Minimum_Extinguishing_Concentration.pdf)

**Comment by drjfloyd** [comment]
OK, I'll edit the text and caption to indicate that and make a legend by hand.  How do I turn off the plot legend in the script?

**Comment by mcgratta** [comment]
Leave the `Key_Position` column blank. That is, don't write `SouthEast` or whatever.

**Comment by drjfloyd** [comment]
There are more fuels than colors available by using letters (e.g. k r g b etc.).  In the plot now there are a few fuels that are one color for the outline and another color for the fill.  Shapes are the agents.  Is this OK or do I need to somehow give RGB values to get unique colors?

**Comment by mcgratta** [comment]
Sounds good to me.

**Comment by drjfloyd** [comment]
Should be fixed in https://github.com/firemodels/fds/commit/fdec5c861262ff6707892f82ea871ee48749989c

**Comment by mcgratta** [comment]
Verified, thanks.
