### ISSUE TITLE
MPI_Init_thread - ERROR

### ISSUE THREAD

**Issue by brunopolycarpo** [firemodels/fds#6346]
After installing FDS, when I tried to run FDS, an error occurred in MPI_Init_thread:
"
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
.....
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[MacBook-Pro-de-Bruno.local:1439] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
"
Can somebody help me?

**Comment by mcgratta** [comment]
Provide more info about your computer. I assume it's a Mac.

**Comment by brunopolycarpo** [comment]
Yes, it is a Mac.
Please find the info below:
   MacBook Pro - Intel Core i7 - 2,6 GHz - 1 Processor - 4 cores
   Cache L2 (per core):	256 KB
   Cache  L3:	6 MB
   Memory:	16 GB

**Comment by mcgratta** [comment]
What version of Open MPI is installed?

**Comment by marcosvanella** [comment]
Thank you Kevin. Hi Bruno, on your command window type:

`>>ulimit -a`

and 

`>>which mpirun`

and report back. Also, how are you executing fds?

**Comment by brunopolycarpo** [comment]
MacBook-Pro-de-Bruno:~ brunopolycarpodias$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited

**Comment by brunopolycarpo** [comment]
I typed the both commands, bui I found the same error message.

Sorry, but how can I find the Open MPI version installed?

**Comment by marcosvanella** [comment]
Add this in your ~/.bash_profile file:

`ulimit -s 65536`

Source the file and try running again.

**Comment by brunopolycarpo** [comment]
I tried, but I found the same error.

**Comment by marcosvanella** [comment]
Hi Bruno, can you provide the result from typing 

`>>ulimit -a`

again?

**Comment by brunopolycarpo** [comment]
Last login: Mon Apr 30 15:28:55 on ttys000
-bash: ulimit: stack size: cannot modify limit: Operation not permitted
-bash: ulimit: stack size: cannot modify limit: Operation not permitted
MacBook-Pro-de-Bruno:~ brunopolycarpodias$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited

**Comment by marcosvanella** [comment]
Sorry, try opening a new terminal window instead of sourcing ~/.bash_profile. 

You should not see the line:
-bash: ulimit: stack size: cannot modify limit: Operation not permitted

Your stack size is set to 8KB, which is too small for some of the arrays used by FDS and the MPI library. The command ulimit -s 65536 increases this memory parameter to 64KB. 
Interestingly, looks like you cannot increase this size once you have started a session in the Mac.

**Comment by brunopolycarpo** [comment]
I could increase the stack size limit (65536) by changing the command in ~/.bash_profile by  ulimit -s hard.
But, unfortunately the error persists:

 Last login: Mon Apr 30 16:31:29 on ttys000
MacBook-Pro-de-Bruno:~ brunopolycarpodias$ /Applications/FDS/FDS6/bin/fds ; exit;
[MacBook-Pro-de-Bruno.local:01856] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 388
[MacBook-Pro-de-Bruno.local:01856] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 166
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /shared/openmpi300_i17u4notorque_64/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /shared/openmpi300_i17u4notorque_64/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[MacBook-Pro-de-Bruno.local:1856] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by brunopolycarpo** [comment]
I could increase the stack size limit (65536) by changing the command in ~/.bash_profile by ulimit -s hard.
But, unfortunately the error persists:

Last login: Mon Apr 30 16:31:29 on ttys000
MacBook-Pro-de-Bruno:~ brunopolycarpodias$ /Applications/FDS/FDS6/bin/fds ; exit;
[MacBook-Pro-de-Bruno.local:01856] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 388
[MacBook-Pro-de-Bruno.local:01856] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ess_singleton_module.c at line 166
Sorry! You were supposed to get help about:
orte_init:startup:internal-failure
But I couldn't open the help file:
/shared/openmpi300_i17u4notorque_64/share/openmpi/help-orte-runtime: No such file or directory. Sorry!
Sorry! You were supposed to get help about:
mpi_init:startup:internal-failure
But I couldn't open the help file:
/shared/openmpi300_i17u4notorque_64/share/openmpi/help-mpi-runtime.txt: No such file or directory. Sorry!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
*** and potentially your MPI job)
[MacBook-Pro-de-Bruno.local:1856] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by marcosvanella** [comment]
Hi Bruno, can you show us what you added for environment variables in your ~/.bash_profile after installing FDS?

You should have there something like:

```
export PATH=/Applications/FDS/FDS6/bin:$PATH
export PATH=/Applications/FDS/FDS6/bin/openmpi_64/bin:$PATH
export OPAL_PREFIX=/Applications/FDS/FDS6/bin/openmpi_64
export OMP_NUM_THREADS=4
```
Also, after adding these if needed, open a new window and type:
`>> which mpirun`

To see if you get access to the OpenMPI lib from the FDS bundle. 
It should be in /Applications/FDS/FDS6/bin/openmpi_64/bin/mpirun

**Comment by brunopolycarpo** [comment]
Hi Marcos,

Thank you! After changing my  ~/.bash_profile like you recommended, FDS worked!

**Comment by marcosvanella** [comment]
Well, looks like we took care of two problems with one issue. 
The small default stack size in the Mac would have given you grief for medium sized problems. 
Next time you come across an issue like this, send us the complete error message you get.

**Comment by AbdelMoumene01** [comment]
@mcgratta 
Can you help me pls 
Abort (1090959) on node 0 (rank 0 in comm 0): fatal error in pmpi_init_thread: other mpi error, error stack

**Comment by rmcdermo** [comment]
@AbdelMoumene01 This is a closed issue.  Are you saying you still have an issue?  If so, please start a new thread with a coherent description of the problem, including a simple input file, the version of the code, and the commands you are using to run it.

**Comment by AbdelMoumene01** [comment]
@mcgratta 
Do you have a whatsapp pls 
Just to send pics 
Im new

**Comment by rmcdermo** [comment]
This is not appropriate.  You can upload any images here as .png files.

**Comment by AbdelMoumene01** [comment]
![Uploading 20240119_203023.jpg…]()
This is

**Comment by rmcdermo** [comment]
Whatever you just tried to upload gave a link back to this issue.  Just cut and paste the full error message here.  Include your input file and the version of FDS you running.

**Comment by AbdelMoumene01** [comment]
@mcgratta 
C: \Users \ACI GALAXY\Desktop\activate-vents>fds activate-vents
Abort (1898959 ) on node
(rank in comm 0): Fatal error in PMPI_Init, thread: Other MPI error, error stack:
MPIR_Init_ thread(178)........:
MPID_ Init(1s32)....
MPIDI_OFI_mpi init hook(1474):
[(unknown)(): Other MPI error
[unset ]: write_ line error; fd=-1 buf=:cmd-abort exitcode-1090959
Rep(s)
24 907 186 176 octets libres
Démarrer la
sauvegarde
Sauvegarde
Rechercher dans : activa
system msg for write_line failure : No error
Abort (1098959) on node
(rank 0 in comm 0): Fatal error in PMPI_Init_ thread: Other MPI error, error stack:
MPIR_Init_ thread(178)........:
MPID_ Init(1532)..............:
MPIDI OFImpi init hook(1474):
(unknown) (): Other MPI error
[unset ]: write_ line error; fd--1 buf-:cmd-abort exitcode-1898959
system msg for write_line failure : No error
forrtl: severe (157): Program Exception - access violation
Image
Unknown Unknown
0007FFDD32E7884 Unknown
impi.d1l
00007FFDD3AD6300 Unknown
Unknown Unknown
fimpi.dl1
Unknown unknown
00007FF71BEE3786 Unknown
fds.exe
Unknown Unknown
fds.e xe
00007FF71BEB1SFE U nknown
Unknown Unknown
0007FF71C833378 Unknoun
[fds.exe
Unknown U nknown
00O7FFEA6AS7344 Unknown
KERNEL32.DLL
Unknown Unknown
0007FFE489A2681 Unknown
ntdll.d1l

**Comment by mcgratta** [comment]
This is not how you are supposed to run FDS under windows. Read the User's Guide for more details. In brief
```
fds_local activate_vents.fds
```

**Comment by rmcdermo** [comment]
From the FDS user guide:

<img width="910" alt="Screenshot 2024-01-19 at 3 57 45 PM" src="https://github.com/firemodels/fds/assets/4418497/d611ea74-921b-4de4-b415-c57d7aa0c90a">

**Comment by AbdelMoumene01** [comment]
@mcgratta how can i taste it if it workk

**Comment by mcgratta** [comment]
Comment puis-je le goûter si ça marche??

**Comment by mcgratta** [comment]
dégustateur?

**Comment by AbdelMoumene01** [comment]
@rmcdermo 
How can I make sure that the fds is running?
