### ISSUE TITLE
Feature Request: 2 restart file

### ISSUE THREAD

**Issue by kuz1toro** [firemodels/fds#6354]
I recently run FDS with dt_restart=10 in case something happend but i forget to check my hdd space left so when FDS try to create restart file, it fail with error. I though i can just restart it from where it left but I cant because the restart file damage, so im thinking if possible can we have two version of the restart file, the first is backup from the last succesive save and the second is the new one, so if theres something not right in the new save, we can just resume from the other one
regard

**Comment by mcgratta** [comment]
The restart functionality is fragile, and we do not want to complicate it any further.

**Comment by kuz1toro** [comment]
Ok understand, thank you for the reply
