### ISSUE TITLE
Complex_Geometry

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6360]
@marcosvanella Just ran a case in Complex_Geometry `shunn3_64_cc_imp_gdv.fds` and it looks like your verbose output is set to be ON.  Let's keep the verbose flag OFF for the cases in the repo because these get bundled with the code as examples.  If you need the numbers in the LU_ERR then these need to be set up for DEVC output or something like this.  Thanks.

**Comment by marcosvanella** [comment]
All right, I'll move these within the GET_CUTCELLS_VERBOSE flag.

**Comment by marcosvanella** [comment]
This change is done in PR #6372.
