### ISSUE TITLE
installation testing

### ISSUE THREAD

**Issue by Pkwahou** [firemodels/fds#6373]
hello,
I'm now proceed to the testing of FDS installation. The tested release is FDS 6.6.0 for Windows 64-bit.
I have compared the predicted metric to the value in the Appendix A of the verification guide.

I observe a difference between the expected Metric and the predicted metric for folowing test case:

-reactionrate_arrhenius_2order_1step (O2, C3H8, CO2, H2O)

                                                           | expected | predicted
reactionrate_arrhenius_2order_1step | 1.30E-02 | 8.73E-02         O2 
reactionrate_arrhenius_2order_1step | 3.36E-03 | 2.37E-02         C3H8
reactionrate_arrhenius_2order_1step | 1.70E-01 | 1.09E-01         CO2
reactionrate_arrhenius_2order_1step | 9.27E-02 | 5.93E-02         H2O

I also have deviation with folowing test cases:
-spray_burner
-particle_drag_U50_N16

is this are due to the changes in the latest release?

Patrick.

**Comment by rmcdermo** [comment]
It is possible.  Might also be related to a change in input parameters, I have not checked those cases. The latest code is passing on our end.  Please either compile latest source with Windows or wait until 6.7.0 is out if you are testing the input files from this repo.
