### ISSUE TITLE
Remove CC_IBM flag from input file

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6376]
@marcosvanella Let's set this for the user if there are any GEOM lines.

**Comment by marcosvanella** [comment]
On it. I'll keep the flag option on the &MISC line, used on the saad_cc, shunn3d_cc verification cases to define cut-cells with no GEOMS.

**Comment by rmcdermo** [comment]
Ok, but make this a "developer hook".  That is, add it to the MISC user guide table, but comment it out.  This is not something we want users touching.  Thanks

**Comment by marcosvanella** [comment]
This is done in PR #6377.
