### ISSUE TITLE
WIND forcing not working for ribbed channel cases

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6385]
@mcgratta The forcing in the ribbed channel cases dies off toward the end of the simulation, resulting in no velocity.

/fds/Verification/Turbulence/ribbed_channel_20.fds

**Comment by mcgratta** [comment]
When using `U0` you must explicitly indicate `MEAN_FORCING=.TRUE.` or provide some other kind of BC to keep the initial velocity going. This is to maintain backward compatibility. If you use wind `SPEED` and `DIRECTION`, this will be done automatically.
