### ISSUE TITLE
Ventilation inversions with HVAC

### ISSUE THREAD

**Issue by gutierrezemm** [firemodels/fds#6414]
Hello,

I have a project of complex tunnel galleries, with 2 air entries, one open exit, and a HVAC at the very beginning of my project.
On the project (linked), I have two issues : 
- a ventilation inversion after my HVAC is stopped (working from T0 to T150), at the horizontal bottom tunnel : 

![t187](https://user-images.githubusercontent.com/39269881/40002509-4967d290-5791-11e8-8c83-7ae046fbcdcb.png)
![t190](https://user-images.githubusercontent.com/39269881/40002510-49a5a4bc-5791-11e8-8e18-2e625eecd795.png)

- a ventilation inversion in the rightmost vertical tunnel at the end of my simulation :
![t913](https://user-images.githubusercontent.com/39269881/40002511-49fdc16a-5791-11e8-976c-0009472b2339.png)
![t917](https://user-images.githubusercontent.com/39269881/40002513-4a4f1fba-5791-11e8-8538-262c02a12afb.png)
Could someone help me figure out why this is observed ?

Thanks.
[testFDS.txt](https://github.com/firemodels/fds/files/2001075/testFDS.txt)

**Comment by Er9y714** [comment]
I do not know the solution for your problem but you should simplify your model to allow users to identify the problem easier. You can remove elements and rerun to see if the problem reoccurs. 

I tried to import the model into Pyrosim and received few errors such as:

non-dimensional VENTs :
 VENT ID='Open_north_0'
      XB=171.000,171.000,173.250,173.250,5.200,5.200
      TRANSPARENCY=0.5, SURF_ID = 'OPEN',  COLOR = 'BLUE'

There are multiple of these. 

Additionally, some elements are not aligned with mesh. FDS might snap these either of the side of the cell and problems might occur. You should give dimension to elements in accordance with mesh :
![image](https://user-images.githubusercontent.com/26166281/40003174-ed514dae-5792-11e8-926a-cc10aba2363c.png)

**Comment by drjfloyd** [comment]
Since your HVAC system is a specified flow, the issue most likely is not an HVAC solver issue.  It is probably that these type of geometries where you have a long tunnel-like geometry that is OPEN at one end can be tough for the pressure solver.  You may need to add some pressure relief along the tunnels (a handful of small OPEN vents along the tunnels).

**Comment by mcgratta** [comment]
Since there is no simplified input file, I am closing this issue. Reopen if you have a simpler case that we can examine.
