### ISSUE TITLE
Collaborators should now have write access to Wiki repo

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6428]
Thanks to @bwklein showing us a trick with branch protection, we are now able to give write access for the wiki repo to our collaborators.  The way this now works is that all collaborators have write access to the project, but only FDS-Developer team members have push access to the code repository.  As collaborators, you should now see an "edit" button at the top-right when you look at the wiki pages.  In particular, @saschagottfried and @sbenkorichi, please feel free to add instructions for compiling and running FDS on linux clusters and HPC platforms.

Let us know if you run into any problems with write access.  Thanks!

**Comment by saschagottfried** [comment]
Confirm this works for me. Thanks to everybody helped to make this possible.

**Comment by rmcdermo** [comment]
@saschagottfried Well done on the compilation wiki.

**Comment by rmcdermo** [comment]
All Collaborators:  PLEASE ENABLE TWO-FACTOR AUTHENTICATION for your GitHub accounts.

One of the deals we made with our IT security division, that allows our project to remain relatively autonomous and free of bureaucracy, is that all members with write access must have two-factor authentication enabled.  This is actually very painless.  If you have any problems setting it up, let me know.  Those who choose not to use two-factor will have to revert back to read access.  Thanks!

**Comment by marcosvanella** [comment]
Sascha, nice work. I'm adding a Wiki on deploying GNU Fortran 7.2 and openmpi for Debian, which will link to your Wiki for Stretch 9.4.
We are also thinking on adding a wiki with the links to all systems and tool chains we have GNU compilation instructions for so far, such that we can add to this list in the future. 
Eventually, this list can also have the table of supported systems/tool chains within continuous integration.

**Comment by saschagottfried** [comment]
Supported systems should be a first class citizen, Got inspired this week by finding how [Hugo is documenting supported systems](https://github.com/gohugoio/hugo#supported-architectures). Getting it like this creates a roadmap for this topic. 

As we said, we start small with selected platforms. But I keep the larger picture in my mind.

**Comment by marcosvanella** [comment]
I added a wiki with the list of Linux distributions with detailed instructions. 
Go to the Home wiki -> FDS Compilation -> GNU Fortran and open MPI for different Linux distributions ("here" link). From there on the user can check what we have.

Sascha, looks good. They practically added in the repo Readme.md what we have in the Home wiki?

**Comment by rmcdermo** [comment]
@saschagottfried please enable 2FA

**Comment by saschagottfried** [comment]
Enabled 2FA
