### ISSUE TITLE
Setup error messages are sent to stderr only

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#6459]
I prepared some verification cases for malformed GEOMs (eg. non-manifold, inconsistent normals, ...)
When writing the Matlab script to verify that FDS catches the error condition, I discovered that the error conditions is only written to stderr.

I suggest that the SUBROUTINE SHUTDOWN(MESSAGE) in FUNC.F90 should be writing the error condition to a CHID.out file in addition to stderr.

**Comment by mcgratta** [comment]
It often happens that the error and shutdown occur before the .out file is created. For this reason, we use the standard error file for all error messages.
