### ISSUE TITLE
Problems with numerical instability and HRR flactuation in tunnel fires

### ISSUE THREAD

**Issue by HairstyleEason** [firemodels/fds#6460]
Hi everyone
I`m working with a simulation about tunnel fire.The tunnel cross-section is 5 m × 5 m, the length is 600m. In the air intake side, the speed boundary was defined as "VENT", while in the air outlet side, the pressure boundary was defined as "OPEN". The tunnel wall material was set as "CONCRETE".  The fire source was located on the central axis of the tunnel bottom, and 200 meters away from air intake side. The longitudinal velocity is 2.0m/s. HRR is 10 MW. I put a train 1.38 m above the fire, and then numerical instability occurs.
I searched for the reason why there is instability on FDS Guide and Github, finding that may due to no leakage in the tunnel. So I create a 1 cell wide OPEN boundary on the tunnel bottom 80m away from the fire source at both side. The problem with numerical instablity has been solved. But unfortunately, the HRR flactuates sharply.

[2.0.txt](https://github.com/firemodels/fds/files/2061696/2.0.txt)

[tunnel 2.0_hrr.xlsx](https://github.com/firemodels/fds/files/2061699/tunnel.2.0_hrr.xlsx)

Could you please give me some advice
THANKS!!!!

**Comment by mcgratta** [comment]
As long as the fire has sufficient oxygen and the average HRR is what you specified, there is no problem. I have run the case and I do not see a problem. I cannot open your xlsx file.

**Comment by HairstyleEason** [comment]
Thank you for your help @mcgratta 
The case could be run surely, but the average HRR in the case is unstable. Just as shown in the pdf.

[Average HRR unstable.pdf](https://github.com/firemodels/fds/files/2065622/Average.HRR.unstable.pdf)

I wonder if this unstability is caused by the leakages?
If so, how can i correct this problem?

**Comment by mcgratta** [comment]
You do not, and should not, create `OBSTs` at the exterior walls. All exterior boundaries of the computational domain are solid by default. You can assign a boundary condition to these exterior boundaries using a `VENT` line or you can create a `SURF` line with `DEFAULT=.TRUE.` Your floor `OBST` has covered your `OPEN` vent. But even with these problems, your fluctuating HRR curve is not unusual. You have put a big fire 400 m into a perfectly sealed tunnel. Where does the oxygen come from? The end, of course, and it has to move towards the fire and against the exiting exhaust gases. Monitor the oxygen volume fraction, and check via flow vectors if your `OPEN` vents are really open.

**Comment by Er9y714** [comment]
For information, the open VENTS on the floor do not align with the mesh, they might be smaller/bigger than what you aim.
