### ISSUE TITLE
forrtl: severe (174) fds works in Win; fails in Linux

### ISSUE THREAD

**Issue by XiuqiXi** [firemodels/fds#6466]
My fds is fds 6.5.3 in Linux(Deepin System). The models(all for one building) contructed in Window(Win 10) can be simulated correctly in Win 10. However, in Linux system, some cannot be proceeded. The error messafge is "forrtl: severe (174): SIGSEGV, segment fault occurred". I have tried to set the stack unlimited by "ulimit -s unlimited", but the message still exsits. 

The error is below:
`hp@hp-PC:~/fds_simulation/123$ fds lijianxueyuanmoxing\ -\ 4.fds
 Mesh      1 is assigned to MPI Process      0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
 Completed Initialization Step  2
 Completed Initialization Step  3
 Completed Initialization Step  4

 Fire Dynamics Simulator

 Current Date     : June  3, 2018  17:17:23
 Version          : FDS 6.5.3
 Revision         : FDS6.5.3-598-geb56ed1
 Revision Date    : Thu Jan 19 16:12:59 2017 -0500
 Compilation Date : Jan 22, 2017  18:04:30

 MPI Enabled; Number of MPI Processes:          1
 OpenMP Enabled; Number of OpenMP Threads:   4

 MPI version: 3.0
 MPI library version: Open MPI v1.8.4, package: Open MPI gforney@burn Distribution, ident: 1.8.4, repo rev: v1.8.3-330-g0344f04, Dec 19, 2014

 Job TITLE        : 
 Job ID string    : lijianxueyuanmoxing_-_4

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
fds                00000000008042A5  Unknown               Unknown  Unknown
fds                0000000000801EC7  Unknown               Unknown  Unknown
fds                00000000007B31D4  Unknown               Unknown  Unknown
fds                00000000007B2FE6  Unknown               Unknown  Unknown
fds                000000000072D969  Unknown               Unknown  Unknown
fds                0000000000734850  Unknown               Unknown  Unknown
libpthread.so.0    00002B97119DE0C0  Unknown               Unknown  Unknown
fds                00000000009F274D  Unknown               Unknown  Unknown
fds                00000000009EE332  Unknown               Unknown  Unknown
fds                000000000081A2CA  MAIN__                    647  main.f90
fds                000000000040981E  Unknown               Unknown  Unknown
libc.so.6          00002B9711C0A2B1  Unknown               Unknown  Unknown
fds                0000000000409729  Unknown               Unknown  Unknown`

**Comment by sbenkorichi** [comment]
Try this on terminal and paste what it gives you.
 ulimit -a

**Comment by XiuqiXi** [comment]
Benkorichi, Thank you for your reply

This is what I got:

**hp@hp-PC:~/fds_simulation/lj5$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62719
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62719
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited**

**Comment by sbenkorichi** [comment]
Interesting.
Do you know how much memory you have on your machine. Try this 
cat /proc/meminfo

**Comment by XiuqiXi** [comment]
Thank you, Benkorichi

I have solve the problem. The error causing forrtl: severe (174) is that I shrink the mesh from the larger one. And when I get the smaller mesh initially, it works well.

Thank you for your help!

**Comment by sbenkorichi** [comment]
Ok, thanks for letting me know.
