### ISSUE TITLE
Multiple meshes in same MPI process causes unrealistic results

### ISSUE THREAD

**Issue by TopiR** [firemodels/fds#6484]
Version: FDS 6.6.0
Revision: FDS6.6.0-131-g88ae75a-HEAD
Compiler: Intel ifort 17.0.4.210

We noticed that something unrealistic is happening between multiple meshes when they are divided into different processes. I attached here a quite simple case where the domain is divided into five mesh and meshes are distributed to four MPI process so that the two smaller meshes are in same process. Soon after the simulation is started the flow between fire mesh and one of the adjoining meshes starts show unrealistic results. In comparison when the same set up is run in single process with OMP 4, then there is no same kind of phenomena between the meshes. The problem is also gone when running all the meshes in their own process using five MPI processes.

Below is few temperature slice-captures (from 2m height) to show the problem. The problem is visible also eg. in visibility and velocity slices. The domain is 10x10x3m, and cell sizes are around the fire 0.125m and everywhere else 0.25m. In attachement is also the FDS-inputfiles for the cases.

Mesh setup
![image](https://user-images.githubusercontent.com/20284038/41087402-454b0706-6a45-11e8-92b7-3ea2e51f9e85.png)

MPI4
![image](https://user-images.githubusercontent.com/20284038/41087081-69598506-6a44-11e8-83ba-e054dde4d45c.png)

Single process, OMP4
![image](https://user-images.githubusercontent.com/20284038/41087135-8a573ec4-6a44-11e8-97e3-f487e84c919f.png)

MPI5
![image](https://user-images.githubusercontent.com/20284038/41087176-a223e930-6a44-11e8-99ca-dd6d2d318dd4.png)

[MMP_single_opening_MPI1.txt](https://github.com/firemodels/fds/files/2079581/MMP_single_opening_MPI1.txt)
[MMP_single_opening_MPI4.txt](https://github.com/firemodels/fds/files/2079582/MMP_single_opening_MPI4.txt)
[MMP_single_opening_MPI5.txt](https://github.com/firemodels/fds/files/2079583/MMP_single_opening_MPI5.txt)

**Comment by rmcdermo** [comment]
Thanks for reporting.  We will take a look asap.

**Comment by mcgratta** [comment]
Yes, I see what you see. For now, you should assign each mesh exclusively to its own MPI process.

**Comment by mcgratta** [comment]
I have the case simplified to this:
```
&HEAD CHID='test_8' /

&TIME T_END=60.0 /

&MISC NOISE=.FALSE. /

&RADI RADIATION=.FALSE. /

&ZONE XB=1,9,1,9,0,3 /

&MESH IJK=10,10,12, XB=3.75,6.25,3.75,6.25,0.0,3.0/
&MESH IJK=15,15,12, XB=0.00,3.75,0.00,3.75,0.0,3.0/
&MESH IJK=10,15,12, XB=3.75,6.25,0.00,3.75,0.0,3.0/
&MESH IJK=15,15,12, XB=6.25,10.0,0.00,3.75,0.0,3.0/
&MESH IJK=15,15,12, XB=0.00,3.75,6.25,10.0,0.0,3.0/
&MESH IJK=10,15,12, XB=3.75,6.25,6.25,10.0,0.0,3.0/
&MESH IJK=15,15,12, XB=6.25,10.0,6.25,10.0,0.0,3.0/
&MESH IJK=15,10,12, XB=6.25,10.0,3.75,6.25,0.0,3.0/
&MESH IJK=15,10,12, XB=0.00,3.75,3.75,6.25,0.0,3.0/

&SURF ID='HOT', COLOR='RED', TMP_FRONT=500. /

&VENT XB=4.5,5.5,4.5,5.5,0.0,0.0, SURF_ID='HOT'/

&SLCF QUANTITY='TEMPERATURE', PBZ=2.9, VECTOR=.TRUE. /
&SLCF QUANTITY='TEMPERATURE', PBZ=2.9, CELL_CENTERED=.TRUE. /

&TAIL /
```
Run this case with 9 MPI processes, open the results in Smokeview, add the vector slice of temperature, hit Alt-v and then Shift-1, hit the A key about 10 times, and zoom in on the center. You should see a perfectly symmetric pattern. Run the case with 8 MPI processes, and the pattern will be slightly off. I have not figured out why, but this case is easier to debug than the original. And it's fun.

**Comment by mcgratta** [comment]
I found the problem. There was a variable defined for each MPI process which really should have been defined for each mesh. Usually when the number of MPI processes matches the number of meshes, this problem does not appear. 

I've nominated you for the [Boris Stock Award 2018](https://github.com/firemodels/fds/wiki/Boris-Stock-Award-Recipients) for best bug report.

**Comment by sbenkorichi** [comment]
Sweet !
Finally it's fixed. 


![image](https://user-images.githubusercontent.com/20113030/41495360-3af8d222-711d-11e8-9efa-83c6c142d43f.png)

**Comment by Er9y714** [comment]
It is exciting to see a fundamental problem is resolved. 

Regarding the nomination to the award, the appreciation stems from the simple demonstration and conclusive guiding through the problem (according to the award webpage). However considering the past awards, they all seem to be important bugs, rather than small typos or insignificant ones. So I think focus of the award is not only the simplicity of presenting the problem, but also the influence of the bug on the calculation.

**Comment by rmcdermo** [comment]
I would consider this quite important.  Definitely gets a nomination!

**Comment by TopiR** [comment]
Thank you for resolving this, it was quite anoying to realize the problem and wrong results after couple of days in the actual bigger real-life case when the scehedule from the client was also really thight.
