### ISSUE TITLE
Manual: explaining "conversion factor"

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6490]
Can someone please add a line or two explaining the function of conversion factor, I always see it set on the DEVC or the SLCF lines. Another question is what's the rule of thumb to set this value if needed.
Thanks !

**Comment by drjfloyd** [comment]
User's Guide 19.2

What is not clear with the explanation and example given?

**Comment by sbenkorichi** [comment]
Thanks Jason.
Dummy me, I did a grep but couldn't get it as I forgot it's written differently. 
{\ct CONVERSION\_FACTOR}
The example provided in the up to date code is clear.

**Comment by Er9y714** [comment]
Can CONVERSION_FACTOR be used on SLCFs? I do not see it as a parameter on the user guide.

**Comment by mcgratta** [comment]
No, only devices. Smokeview has some ability to convert units.

**Comment by drjfloyd** [comment]
No, only devices.

**Comment by sbenkorichi** [comment]
Some of the validation cases need cleaning probably then. Do a grep and you will see it used --unless it's on purposes.

```
Validation/FM_FPRF_Datacenter/FDS_Input_Files/FM_Datacenter_High_C3H6_HA.fds:1157:&SLCF PBX=0.3048,QUANTITY='MASS FRACTION',SPEC_ID='SOOT', UNITS='mg/m3', CONVERSION_FACTOR=1.E6,/
Validation/FM_FPRF_Datacenter/FDS_Input_Files/FM_Datacenter_High_C3H6_HA.fds:1158:&SLCF PBX=2.4384,QUANTITY='MASS FRACTION',SPEC_ID='SOOT', UNITS='mg/m3', CONVERSION_FACTOR=1.E6,/
```

**Comment by Er9y714** [comment]
`UNITS` is also not included in the user guide for &SLCF.

**Comment by drjfloyd** [comment]
@Er9y714   UNITS and CONVERSION_FACTOR are not on SLCF.  The FM cases that have those are my error in updating cases while adjusting how the data is being plotted for the Validation Guide.  I did a global search and replace to update DEVC lines and did not notice that also updated SLCF inputs.

**Comment by drjfloyd** [comment]
fixed

**Comment by sbenkorichi** [comment]
Cheers,
