### ISSUE TITLE
Mass conservation

### ISSUE THREAD

**Issue by SimonLoosvelt** [firemodels/fds#6496]
Hello,

The main purpose is to analyze the smoke flow in a staircase. First of all, i tried to apply the mass conservation on a simple zone model with in total 4 zones. There is a fire in the first zone with an opening to the ambient to have enough oxygen available for the fire. Between the zones, devices are placed to determine the flow rate. In each zone, the volume of the smoke is measured. The mass conservation used is:

m_zone = m_zonepresent + time*(m_in - m_out)

If I apply this, I get wrong values. Am i doing something wrong or am I measuring the wrong stuff? The code is put beneath.

&HEAD CHID='testcase'/
&TIME T_END=100.0/

&MESH ID='MESH', IJK=40,20,25, XB=-2.0,6.0,0.0,4.0,0.0,5.0/

&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE./
	  
&REAC ID='Fire',
      FUEL='REAC_FUEL',
      FORMULA='C1H4',
      CO_YIELD=0.09,
      SOOT_YIELD=0.09/
	  
&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=1000.0/

&OBST ID='Walls', XB=0,4.0,0.0,4.0,5.0,5.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Top', XB=0,0.2,0.2,3.8,0.0,5.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Top', XB=0,4.0,0.0,0.2,0.0,5.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Top', XB=0,4.0,3.8,4.0,0.0,5.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Top', XB=3.8,4.0,0.2,3.8,0.0,5.0, SURF_ID='ADIABATIC'/ 
&OBST ID='2m', XB=2.0,4.0,0.0,4.0,2.0,2.0, SURF_ID='ADIABATIC'/ 
&OBST ID='3m', XB=0,2.0,0.0,4.0,3.0,3.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=2.0,4.0,0.0,4.0,4.0,5.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=0,2.0,0.0,4.0,0.0,1.0, SURF_ID='ADIABATIC'/ 
&OBST ID='Obstruction', XB=2.8,3.2,1.8,2.8,0.0,0.2, SURF_IDS='Fire','ADIABATIC','ADIABATIC'/ 

&HOLE ID='Opening top', XB=0.0,0.2,1.4,2.4,3.0,4.0/ 
&HOLE ID='Opening bottom', XB=3.8,4.0,1.4,2.4,0,1.0/ 

Topopening ambient
&VENT ID='Vent1', SURF_ID='OPEN', XB=-2.0,0.0,0.0,0.0,0.0,5.0/ 
&VENT ID='Vent2', SURF_ID='OPEN', XB=-2.0,0.0,0.0,4.0,5.0,5.0/ 
&VENT ID='Vent3', SURF_ID='OPEN', XB=-2.0,-2.0,0.0,4.0,0.0,5.0/ 
&VENT ID='Vent4', SURF_ID='OPEN', XB=-2.0,0.0,4.0,4.0,0.0,5.0/ 

Bottomopening ambient
&VENT ID='Vent5', SURF_ID='OPEN', XB=4.0,6.0,0.0,0.0,0.0,5.0/ 
&VENT ID='Vent6', SURF_ID='OPEN', XB=4.0,6.0,0.0,4.0,5.0,5.0/ 
&VENT ID='Vent7', SURF_ID='OPEN', XB=6.0,6.0,0.0,4.0,0.0,5.0/ 
&VENT ID='Vent8', SURF_ID='OPEN', XB=4.0,6.0,4.0,4.0,0.0,5.0/ 

Plane flowrates
&DEVC ID='Massflow1m', QUANTITY='MASS FLOW', SPEC_ID='PRODUCTS', XB=2.0,2.0,0.2,3.8,1.0,2.0, STATISTICS='AREA INTEGRAL'/
&DEVC ID='Massflow2m', QUANTITY='MASS FLOW', SPEC_ID='PRODUCTS', XB=2.0,2.0,0.2,3.8,2.0,3.0, STATISTICS='AREA INTEGRAL'/
&DEVC ID='Massflow3m', QUANTITY='MASS FLOW', SPEC_ID='PRODUCTS', XB=2.0,2.0,0.2,3.8,3.0,4.0, STATISTICS='AREA INTEGRAL'/
&DEVC ID='Out', QUANTITY='MASS FLOW', SPEC_ID='PRODUCTS', XB=0.2,0.2,1.4,2.4,3.0,4.0, STATISTICS='AREA INTEGRAL'/
&DEVC ID='Out', QUANTITY='MASS FLOW', SPEC_ID='PRODUCTS', XB=3.8,3.8,1.4,2.4,0,1.0, STATISTICS='AREA INTEGRAL'/

Zone flowrates
&DEVC ID='Zone1', QUANTITY='VOLUME FRACTION', SPEC_ID='PRODUCTS', XB=2.0,3.8,0.2,3.8,0.0,2.0/
&DEVC ID='Zone2', QUANTITY='VOLUME FRACTION', SPEC_ID='PRODUCTS', XB=0.2,2.0,0.2,3.8,1.0,3.0/
&DEVC ID='Zone3', QUANTITY='VOLUME FRACTION', SPEC_ID='PRODUCTS', XB=2.0,3.8,0.2,3.8,2.0,4.0/
&DEVC ID='Zone4', QUANTITY='VOLUME FRACTION', SPEC_ID='PRODUCTS', XB=0.2,2.0,0.2,3.8,3.0,5.0/

&TAIL /

**Comment by mcgratta** [comment]
Do not use `STATISTICS` with `MASS FLOW`. It is already an integrated quantity. 

`VOLUME FRACTION` is not a "flow rate". These devices are not meaningful.

When I correct the input file, the absolute value of the mass flow rates are comparable.

**Comment by SimonLoosvelt** [comment]
Thanks, how can i measure than the mass inside a certain zone? To see if the conservation of mass is correct

**Comment by drjfloyd** [comment]
Use a device to integrate the density in the zone. If the zone is not rectangular, you can use multiple devices and then sum them together either in post-processing or by the use of control functions.

**Comment by SimonLoosvelt** [comment]
Okay thanks i will try that, and I have a problem with the results.. In each zone, the mass flow of the inlet is higher than the mass flow of the outlet. So following the conservation of mass, the mass inside the zone is negative. Is that also a problem with the density or what should i do?

**Comment by rmcdermo** [comment]
Checkout the this section of the current FDS Verification Guide:

6.1.3 Mass Flux through Domain Boundaries (mass_flux_wall)

It walks you through doing a non-trivial mass balance.  The test cases are available in, for example,

https://github.com/firemodels/fds/blob/master/Verification/Flowfields/mass_flux_wall_yindex.fds

**Comment by SimonLoosvelt** [comment]
Thanks, i will check it! Hope it will help

**Comment by SimonLoosvelt** [comment]
I'm sorry, but i'm a real beginner of FDS. When I use your link, i get following error message:

Problem with units compatibility using STATISTICS of SURFACE INTEGRAL with the QUANTITY SMOKE/WATER

What should i do?

**Comment by drjfloyd** [comment]
Based upon the error message it looks like you have not defined a valid QUANTITY.

**Comment by SimonLoosvelt** [comment]
If i try it with products -> so the smoke, than i get next error:

DEVC QUANTITY MASS FLUX WALL not found

So I can't do a mass flux wall? I just took it from the example..

**Comment by drjfloyd** [comment]
An error on our part.  The output MASS FLUX WALL was added in Dec 2017 which is after the last release of FDS.  You can use MASS FLOW WALL with a SPEC_ID. See the examples in the User's Guide.

**Comment by SimonLoosvelt** [comment]
It works but FDS has problems to assign it to a boundary cell. My plane that i want to investigate is not at a boundary. It is in the middle of the mesh, just an opening. So if i leave the wall out than I have just the same as when i started but this is not right. Anyone has a solution to determine the conservation of mass because now it is negative if i use:

dm/dt = m_in - m_out

**Comment by rmcdermo** [comment]
@SimonLoosvelt I do not think this is a code issue.  It sounds like you need to work on applying the continuity equation on each mesh block with a combination of MASS_FILE=T and the appropriate MASS FLOW WALL quantities on exterior VENTS.  Start simple and work your way up to complicated problems.  If you have further problems, submit questions to the Discussion Forum.  Thanks.

https://groups.google.com/forum/?fromgroups#!forum/fds-smv
