### ISSUE TITLE
GEOM error in cylinder flow case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6504]
@marcosvanella Here are the two files we were playing with today.  One that works and the one with the error.

[cylinder_flow.fds.txt](https://github.com/firemodels/fds/files/2100370/cylinder_flow.fds.txt)

[cylinder_flow_error.fds.txt](https://github.com/firemodels/fds/files/2100371/cylinder_flow_error.fds.txt)

**Comment by marcosvanella** [comment]
Should be taken care of in PR #6515.
