### ISSUE TITLE
Numerical Instability in Multiple Mesh

### ISSUE THREAD

**Issue by FDSANDPYROSIMFAN** [firemodels/fds#6505]
I am facing Numerical Instability issue while modelling with multiple meshes.  There are 5 meshes , 4 with .4m cell size and the 5th one with .2m cell size.  Since there are 20 physical cores, 4 cores are assigned to each mesh by OPEN MP THREAD option selected as 4.  The mesh with .4m mesh size has fire source located within it.  Please share your views as to how to solve this issue.

**Comment by rmcdermo** [comment]
Please read the section on instabilities in the user guide.  This Issues page is for reporting bugs.  Your case might be a bug, but in that case we would need an input file to help solve the problem.  If you want general advice from the community, please post your question here:

https://groups.google.com/forum/?fromgroups#!forum/fds-smv
