### ISSUE TITLE
Vent orientation

### ISSUE THREAD

**Issue by SimonLoosvelt** [firemodels/fds#6506]
I want to use part 9.3.2 of the FDS user guide and more in detail I want to use a localized leakage. I want to introduce the leakage around a closed door in a staircase. The door has to connect the staircase with a lobby

I introduced it on the second floor with the next coding:
&VENT ID='Tweedetrapdeur1', XB=-0.2,-0.2,10.4,11.4,3.0,5.0, SURF_ID='ADIABATIC'/
&VENT ID='Tweedetrapdeur2', XB=0,0,10.4,11.4,3.0,5.0, SURF_ID='ADIABATIC'/
&HVAC ID='Tweede verdieping traplekken',TYPE_ID='LEAK',VENT_ID='Tweedetrapdeur1',VENT2_ID='Tweedetrapdeur2',AREA=0.05/

This works and no problems arise. I want to introduce the doors at other levels. This is done with the same structure of coding:
&VENT ID='Derdetrapdeur1', XB=-0.2,-0.2,10.4,11.4,6.0,8.0, SURF_ID='ADIABATIC'/
&VENT ID='Derdetrapdeur2', XB=0,0,10.4,11.4,6.0,8.0, SURF_ID='ADIABATIC'/
&HVAC ID='Derde verdieping traplekken',TYPE_ID='LEAK',VENT_ID='Derdetrapdeur1',VENT2_ID='Derdetrapdeur2',AREA=0.05/

When doing this, the next error is mentioned: Specify orientation of VENT 5, MESH NUMBER 1
I don't know what to do and the user guide is not really helpful for me.

The obstruction, where I put the leakage on is:
&OBST ID='Obstruction', XB=-0.2,0,10.4,11.4,3.0,6.0, SURF_ID='ADIABATIC'/

**Comment by mcgratta** [comment]
FDS cannot find a solid object to attach VENT 5 to. Check your input coordinates, and keep in mind that the OBST's might shift to fit the grid.
