### ISSUE TITLE
Feature request: SMV: remove VENTs via HOLEs

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6518]
Do you think it would be beneficial to remove the part of the VENT  where corresponds to the OBST surface where HOLE removes? (Also, showing back this omitted VENT part if HOLE is deactivated?)
Because when an OBST is covered with VENTs, HOLE is hidden behind. User cannot observe if the OBST is hollowed (HOLE is working). 

Thank you,

![capture](https://user-images.githubusercontent.com/26166281/41471047-c851e6ba-70b2-11e8-893f-fd2d92457808.JPG)

Secondly, I noticed there is an offset between VENT and the surface of the OBST (although VENT is not offsetted by XB). Is this a new feature? The offset seems to be in the order of the 1/10 of grid size.

![image](https://user-images.githubusercontent.com/26166281/41471474-0edf6bec-70b4-11e8-9da6-24ec27a3fa50.png)

 

```
&HEAD CHID='HOLE'/
&TIME T_END=10.0/

&MESH ID='Mesh01', IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&DEVC ID='TIMER->OUT', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=5.0, INITIAL_STATE=.TRUE./

&SURF ID='Surface01',
      RGB=26,204,26,
      VEL=-1.0/

&OBST ID='Obstruction', XB=0.3,0.7,0.3,0.7,0.0,1.0, SURF_ID='INERT'/ 

&HOLE ID='Hole', XB=0.2,0.8,0.2,0.8,0.4,0.5, DEVC_ID='TIMER->OUT'/ 

&VENT ID='Mesh Vent: Mesh01 [XMAX]', SURF_ID='OPEN', XB=1.0,1.0,0.0,1.0,0.0,1.0, COLOR='INVISIBLE'/ 
&VENT ID='Mesh Vent: Mesh01 [XMIN]', SURF_ID='OPEN', XB=0.0,0.0,0.0,1.0,0.0,1.0, COLOR='INVISIBLE'/ 
&VENT ID='Mesh Vent: Mesh01 [YMAX]', SURF_ID='OPEN', XB=0.0,1.0,1.0,1.0,0.0,1.0, COLOR='INVISIBLE'/ 
&VENT ID='Mesh Vent: Mesh01 [YMIN]', SURF_ID='OPEN', XB=0.0,1.0,0.0,0.0,0.0,1.0, COLOR='INVISIBLE'/ 
&VENT ID='Mesh Vent: Mesh01 [ZMAX]', SURF_ID='OPEN', XB=0.0,1.0,0.0,1.0,1.0,1.0, COLOR='INVISIBLE'/ 
&VENT ID='Mesh Vent: Mesh01 [ZMIN]', SURF_ID='OPEN', XB=0.0,1.0,0.0,1.0,0.0,0.0, COLOR='INVISIBLE'/ 

&VENT ID='Vent', SURF_ID='Surface01',  XB=0.3,0.7,0.7,0.7,0.0,1.0/ 
&VENT ID='Vent2', SURF_ID='Surface01', XB=0.3,0.3,0.3,0.7,0.0,1.0/  
&VENT ID='Vent4', SURF_ID='Surface01', XB=0.3,0.7,0.3,0.3,0.0,1.0/ 

&SLCF QUANTITY='VELOCITY', PBX=0.5/


&TAIL /
```

Air supply vent is added only for verifying VENT stops working on the removed part of the OBST.

**Comment by gforney** [comment]
the logic for drawing blockage holes at various times is pretty complicated already - to not draw the vent would make it more so.  I will take a look at it.

smokeview offsets the vent from the blockage because of the pauli exclusion principle for OpenGL - can't draw two things in the same place

**Comment by mcgratta** [comment]
This enhancement would have to come from FDS. I'll see what would be involved. For now, use a SURF applied to the OBST instead of a VENT.

**Comment by Er9y714** [comment]
I usually avoid HOLEs also use SURF_ID on OBST instead of VENTs. I would not want to ask for a trivial feature at the expense of a time consuming solution. I only wanted to see if it would be a quick fix. But it appears not to be so. 

As for the offsetting the VENT, I did not know about this OpenGL feature. Also I am sure I have seen examples before where VENT and OBST overlapped and some artifacts occured. Maybe it was due to old SMV or FDS. Nevertheless, I like this foul-proof feature.

**Comment by mcgratta** [comment]
VENTs are one of the original FDS/Smokeview features. We would have to extend the HOLE feature to cut VENTs. This would have to be done by FDS, which would then send to Smokeview the remaining patches of the original VENT. The code to do this can be messy.

**Comment by Er9y714** [comment]
I will withdraw the request thus close the issue in this case. 

Thank you for the reply.

**Comment by mcgratta** [comment]
Didn't say it can't be done. I have to look into it.

**Comment by mcgratta** [comment]
Well, I looked into it, and unfortunately it would be very difficult to fix. I suggest that you apply the `SURF` directly to the `OBST` like this
```
&OBST XB=..., SURF_ID6=... /
```
Then when the `OBST` is divided by the `HOLE`, the image in Smokeview should be consistent.
