### ISSUE TITLE
AST output is inconsistent with GAUGE HEAT FLUX output

### ISSUE THREAD

**Issue by mckinn1** [firemodels/fds#6531]
I am attempting to model an experiment with burner adjacent to a vertical wall instrumented with heat flux gauges and plate thermometers. When I define AST and GAUGE HEAT FLUX devices at the same location with the same device properties, the AST output cannot be manipulated to produce the GAUGE HEAT FLUX output. 

The equation that I am using to calculate the gauge heat flux from the AST come from subtracting Eq 17.17 from 17.14 (Revision FDS6.6.0-129-g951268a):

![image](https://user-images.githubusercontent.com/29129519/41618206-7f8ba2e2-73d0-11e8-8fc9-7a2d2be7b038.png)

I have attached a simplified version of my input file and below is a chart with data from the first 40 seconds is displayed below. In the data displayed in chart, I have calculated the equivalent gauge heat flux from the AST output (AST_HF) according to the equation above.

![image](https://user-images.githubusercontent.com/29129519/41618918-79ff9c6e-73d2-11e8-84ba-bd99f03afb9d.png)

The two heat flux values at each time are generally close, but, in some cases, I have seen error between the two up to about 10%. I am curious if there is some additional information that has not been included in the User's Guide that explains why these two values do not agree with each other.

Thanks,

Mark

**Comment by mckinn1** [comment]
Simplified Input file:

[50kW.txt](https://github.com/firemodels/fds/files/2116590/50kW.txt)

**Comment by mcgratta** [comment]
Add `TIME_AVERAGE=.FALSE.` to the `DEVC` lines.

**Comment by mckinn1** [comment]
I tried to add that line to the DEVC lines, but when I try to run the attached input file, I get the following error:

ERROR: Problem with DEVC number 1, line number21 (CHID: 50kW_2)

I removed the TIME_AVERAGE=.FALSE. statement from the first DEVC line but left it on the second DEVC line and got the same error for DEVC number 2.

The FDS revision I am running is FDS6.6.0-131-g88ae75a-HEAD, should I try this input file with the latest release?

[50kW_2.txt](https://github.com/firemodels/fds/files/2116665/50kW_2.txt)

Thanks,

Mark

**Comment by mcgratta** [comment]
`TIME_AVERAGED`

**Comment by mckinn1** [comment]
Thanks Kevin,

Using the TIME_AVERAGED=.FALSE. statement on the DEVC lines certainly improved agreement between the measured gauge heat flux and that calculated from the AST values, but it appears that there is still some variation as seen in the chart of the same 40 second period:

![image](https://user-images.githubusercontent.com/29129519/41622502-c5e646f4-73dd-11e8-9f43-bf6653d4c1be.png)

Can you think of any other way to improve agreement between these two quantities or is this as good as it gets? This also brings up the question of what the default time-averaging window or other is or other parameters for averaging are for AST and GAUGE HEAT FLUX devices.

Thanks,

Mark

**Comment by mcgratta** [comment]
Try setting `WALL_INCREMENT=1` on the `TIME` line. That forces all of the quantities involved in the calc of T_AST and GHF to be evaluated at every time step.

**Comment by mckinn1** [comment]
It looks like defining WALL_INCREMENT=1 rectified the two outputs. 

![image](https://user-images.githubusercontent.com/29129519/41624373-7d626e34-73e3-11e8-810e-9b07fa5d4b71.png)

Thanks again,

Mark

**Comment by mcgratta** [comment]
By default, FDS updates boundary quantities every two time steps. Some of the terms used to compute T_AST and GHF are one time step off.

**Comment by mckinn1** [comment]
I am currently attempting to do a similar comparison between AST and GHF BNDF quantities and I have found that there is a discrepancy similar to the first plot that I posted. I am curious if there is a setting similar to TIME_AVERAGED=.FALSE. for BNDF quantities that is not currently represented in the User's Guide, and if not, if there is any other way to rectify these data.

Thanks,

Mark

**Comment by rmcdermo** [comment]
I would first look at a DEVC for the wall quantities you are interested in, AST and gauge heat flux, with TIME_AVERAGED=.FALSE.

If these give the same results but BNDF does not, then something is wrong.  The same time averaging should be applied to AST and GHF.  You can remove time averaging on boundary files by setting DT_BNDF to something very small (1e-6) on the DUMP line, which forces to dump every time step.  But this can lead to VERY large files.

**Comment by mckinn1** [comment]
Randy,

Thanks for the quick reply. The figures below show the comparison between AST_HF and GHF with TIME_AVERAGED = .FALSE. 

![image](https://user-images.githubusercontent.com/29129519/42903745-d1eff5d8-8aa0-11e8-9858-b8f85a4dc737.png)

![image](https://user-images.githubusercontent.com/29129519/42903754-dc0136ea-8aa0-11e8-94c4-6c64d1a4c51a.png)

Did you mean to say that I should output the two quantities with TIME_AVERAGED=.TRUE. to compare the discrepancy between these quantities when outputted as BNDF and DEVC? How is time averaging handled for the BNDF? Is the quantity averaged between dumps?

Thanks,

Mark

**Comment by rmcdermo** [comment]
I think so.  Set DT_BNDF=1e-6 on DUMP and see if that helps.

**Comment by mcgratta** [comment]
There is no time averaging for `BNDF` output. Are you still setting `WALL_INCREMENT=1` on the `TIME` line? That is important because the calculation of AST and GHF at the time of `BNDF` output will be different if some of the various quantities are a time step off.

**Comment by mckinn1** [comment]
Kevin,

I am still setting WALL_INCREMENT=1 on the TIME line.

Thanks,

Mark

**Comment by mcgratta** [comment]
Are the emissivities and heat transfer coefficients the same for all solids?

**Comment by mckinn1** [comment]
Kevin,

There is one object of interest, a stainless steel sheet that is adjacent to a burner. This sheet has an emissivity of 1 on the exposed and unexposed sides and a constant heat transfer coefficient of 25 W/m2/K on the exposed surface and 10 W/m2/K on the unexposed surface. I have attached the unsimplified version of this input file here. I am using FDS version 6.5.2, but I would be happy to try to replicate this with a simplified input file on the latest release if you think it will help to understand these results.

[50kW_1.txt](https://github.com/firemodels/fds/files/2221125/50kW_1.txt)

Thanks,

Mark

**Comment by drjfloyd** [comment]
On the BNDF lines try setting CELL_CENTERED=.TRUE. to turn off the
interpolation.

**Comment by mcgratta** [comment]
Reduce this file to a single mesh, the burner, the plate, and just the devices needed.

**Comment by mckinn1** [comment]
I have reduced this input file to a simplified version in a single mesh. The input file without CELL_CENTERED=.TRUE. is:
[50kW_1.txt](https://github.com/firemodels/fds/files/2225128/50kW_1.txt)
The data plotted in the chart are GHF and HF calculated from AST from the boundary file at location (0,0,0.25).
![image](https://user-images.githubusercontent.com/29129519/43162621-99dd65c8-8f59-11e8-8b4b-2b38be681139.png)

The input file with CELL_CENTERED=.TRUE. is:
[50kW_1_CC.txt](https://github.com/firemodels/fds/files/2225136/50kW_1_CC.txt)
The data plotted in the chart are GHF and HF calculated from AST from the boundary file at location (0,-0.025,0.225).
![image](https://user-images.githubusercontent.com/29129519/43163133-2849b310-8f5b-11e8-844d-20b170ea8daa.png)

In both cases, the heat flux calculated from the AST and the GHF BNDF quantities are not equal.

Thanks,

Mark

**Comment by mcgratta** [comment]
What happens if you set all heat transfer coefficients to 0?
