### ISSUE TITLE
SMV 6.6.5, FDS+Evac - color of EXIT/DOOR/ENTR

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#6538]
``` 
Smokeview  SMV6.6.5-0-g008cf1da2 - Jun 19 2018

Revision         : SMV6.6.5-0-g008cf1da2
Revision Date    : Tue Jun 19 09:04:44 2018 -0400
Compilation Date : Jun 19 2018 10:11:31
Compiler         : Intel C/C++ 18.0.2
Platform         : OSX64
```

The color of EXITs, DOORs and ENTRs are _RED_ if the exit, door or entry is closed (for example see FDS UG _The ENTR Namelist Group_). 

The color and appearance is not changed in SMV 6.6.5, see [issue_fds.txt](https://github.com/firemodels/fds/files/2120786/issue_fds.txt):

"EXIT" and "DOOR1" are opened after 10 seconds. "DOOR2" is closed after 10 seconds. The color is not changed.

**Comment by gjaeger** [comment]
With FDS 6.7 and SMV 6.7.1, the issue still exist.

**Comment by tkorhon1** [comment]
Well, I try to check this. Yes, I see the problem. The doors are worging as they should in the evacuation calculation, but Smokeview is not updating the status of the doors. So, there is something wrong inside the dump.f90 source code. I should check this when I have some time.

TimoK

**Comment by gjaeger** [comment]
Thank you in advance

**Comment by tkorhon1** [comment]
Just commited a new version that should work. I tested it in a "serial calculation" case. A true MPI test should be made still. But it should work, because things seem to be quite like the ordinary FDS DEVC status changes that are written to the .smv file.

Gregor, please, let me know if it works also for a MPI run, whenever you happen to do a such calculation.

TimoK

**Comment by gjaeger** [comment]
It works with commit 462bbc29dcb0b86a11eb3ae18cf3d659327f2896 for a 1-Mesh and 3-Mesh calculation. A MPI run also seems to work.

Thanks. We can close the issue.

**Comment by tkorhon1** [comment]
Thanks! So, I'll close this issue now.
