### ISSUE TITLE
FDS

### ISSUE THREAD

**Issue by wangxiaosaii** [firemodels/fds#6551]
Our team is doing fire simulation experiments and using SMV to realize the fire visualization interface, but we want to extract data about the speed of smoke particles in the FDS file. How do the smoke particle velocity data of the gods are extracted from the FDS file？

![1529992394 1](https://user-images.githubusercontent.com/34532254/41894447-7983fcc4-7951-11e8-9827-949cdd437a60.jpg)

**Comment by rmcdermo** [comment]
I answered your question in the smv post.

This Issues page is for reporting bugs.  You should post your questions to the community discussion forum:

https://groups.google.com/forum/?fromgroups#!forum/fds-smv
