### ISSUE TITLE
Linux cluster setup

### ISSUE THREAD

**Issue by PershingWadlow** [firemodels/fds#6552]
Hi,

I am using FDS for past few months. So far I ran my simulation in university workstation. now I am planning to run in Linux based cluster because of my larger domain size.

I have no previous experience with Linux cluster. I just followed [https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-on-a-Linux-Cluster](url) for installing and submitting the job.

but my simulation is ending as soon as I summit the job.

please help with what I am missing.

(I attached my .fds file location and cluster screenshots for reference)

Thank you.

![config](https://user-images.githubusercontent.com/38319080/41928887-4998905e-7994-11e8-93db-4c71c4781aa1.JPG)
![fds install](https://user-images.githubusercontent.com/38319080/41928889-49c57254-7994-11e8-8981-bbd4e73c2579.JPG)
![file t1](https://user-images.githubusercontent.com/38319080/41928891-49efebc4-7994-11e8-97b9-11411a6e7fe4.JPG)
![file](https://user-images.githubusercontent.com/38319080/41928893-4a1d3728-7994-11e8-8019-330d3bab56d3.JPG)
![runscript](https://user-images.githubusercontent.com/38319080/41928894-4a4ac0a8-7994-11e8-948b-ea8a8d9fcdaa.JPG)

**Comment by gforney** [comment]
looks like you have a lot of space between your home directory p and the directory containing your case 7.  I would change lines in your script2.pbs script like the following

#PBS -e /UHOME/p/7/example/t1.log

mpiexec -np 4 /UHOME/p/7/FDS/FDS6/bin/fds t1.fds

etc

cd to the directory 7 and type pwd .  It should output a path.  It is is this path that you should be putting in your script

**Comment by PershingWadlow** [comment]
sorry for delay in command.

The space between p and 7 contain my details that why i erased in screen shot.

I uploaded few more images of  corresponding t1.fds (within 'example' folder) file location in my first post. please compare the cd directory and my script.pbs.

I hope I missing something in the #PBS -e or cd line.

Thank you.

**Comment by sbenkorichi** [comment]
add this under the nodes line. 
`#PBS -l walltime=999:99:99`
remove `#PBS -q small`

Test it and report what you get.

**Comment by PershingWadlow** [comment]
same no change.

I used " #PBS -q small " because this was mentioned in sample runscript of our cluster.

I attached my path directory screen shot and  sample run script of our cluster. please take a loot at it.

![university sample runscript](https://user-images.githubusercontent.com/38319080/41972363-4dbd0ade-7a2f-11e8-8385-fbd5b2089878.JPG)
![file](https://user-images.githubusercontent.com/38319080/41971914-b75a65d8-7a2d-11e8-8471-959f5ab31182.JPG)
![t1](https://user-images.githubusercontent.com/38319080/41971917-b7bea200-7a2d-11e8-807f-16453fa16586.JPG)
![screen](https://user-images.githubusercontent.com/38319080/41971916-b7883ecc-7a2d-11e8-954a-509069245a08.JPG)

**Comment by sbenkorichi** [comment]
Can you try to use only one node to see if the queue system is working or not. 

name this script as script.pbs. Copy it to the same fds job folder, and run it from there.
```
#!/bin/bash
#PBS -N  job
#PBS -e /**/job.err
#PBS -o /**/job.log
#PBS -l nodes=1:ppn=1
#PBS -l walltime=999:99:99

export OMP_NUM_THREADS=4
cd /**/
/*/fds job.fds
```
`/**/$ qsub script.pbs`

Report what you get.

**Comment by PershingWadlow** [comment]
Still no change.


![file](https://user-images.githubusercontent.com/38319080/42049227-fcc12382-7b22-11e8-9fbb-5181c6033c5e.JPG)
![script](https://user-images.githubusercontent.com/38319080/42049229-fcf80e6a-7b22-11e8-9651-9c0f88a1be14.JPG)

**Comment by mcgratta** [comment]
Post here the exact PBS script file that you are submitting.

**Comment by PershingWadlow** [comment]
I placed this script.pbs file inside the example (where t1.fds is located) folder and submitted the job from there.
you can see the directory in last command attached image.

#!/bin/bash
#PBS -N t1
#PBS -e /UHOME/p******7/example/t1.err
#PBS -o /UHOME/p******7/example/t1.log
#PBS -l nodes=1:ppn=1
#PBS -l walltime=999:99:99
export OMP_NUM_THREADS=4
cd /UHOME/p******7/example/t1/
mpiexec -np 4 /UHOME/p******7/FDS/FDS6/bin/fds t1.fds

**Comment by mcgratta** [comment]
What happens when you just execute
```
mpiexec -np 4 /UHOME/p******7/FDS/FDS6/bin/fds t1.fds
```
at the command line? Also, what happens when you type 
```
where mpiexec
```

**Comment by PershingWadlow** [comment]
For both cases same scenario is repeating.
job is ending without running.

**Comment by sbenkorichi** [comment]
Please open up a separate terminal and do what Kevin requested. This we'll see if fds and mpi works or not, before going to the torque scheduler.  
On the same folder of the fds input file, click right and choose open in terminal, or simply hit ctrl+alt+T and cd to the input file directory. Then execute the two commands above.

**Comment by PershingWadlow** [comment]
now Its running for

mpiexec -np 4 /UHOME/p******7/FDS/FDS6/bin/fds t1.fds

not for 

where mpiexec

![running](https://user-images.githubusercontent.com/38319080/42136736-d120cd96-7d7e-11e8-8517-93222926e427.JPG)

![where](https://user-images.githubusercontent.com/38319080/42136824-de6d8088-7d7f-11e8-8bbb-3feb43b26675.JPG)

**Comment by mcgratta** [comment]
This means that FDS is working properly. You need to talk to the system administrator about the scheduler. We have no control over that.

**Comment by PershingWadlow** [comment]
Sure, thanks for the response.
I will talk to my system administrator. and report here.
