### ISSUE TITLE
SMV - visualisation - BNDF

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6560]
Ran in fds 6.7.0  and viewed in smv 6.7.1.

Thank you for your time.

1.   
When I load the BNDF file, the face of this OBST has artifacts.  When I change the dimensions of the second mesh, artifact disappears.
 
![image](https://user-images.githubusercontent.com/26166281/42026851-7b27f12a-7ac8-11e8-8e53-cc61ea72caee.png)

```
&HEAD CHID='A' /
&TIME T_END=1/
&DUMP  DT_BNDF=0.1 /
&MESH ID='room1', IJK=28,43,10, XB=0.0,7.0,0.0,10.75,0.0,2.5/
&MESH ID='Corridor', IJK=10,176,10, XB=-2.5,0.0,0.0,44,0.0,2.5/
&OBST ID='Wall', XB=0.0,0.25,5.0,10.75,0.0,2.5, SURF_ID='INERT'/  
&BNDF QUANTITY='GAUGE HEAT FLUX'/
&TAIL /
```

2.
A part of the surface that is seen on the figure below does not have BNDF by default. 
![image](https://user-images.githubusercontent.com/26166281/42025931-1c129368-7ac6-11e8-81d5-8945d17e3b2e.png)

```
&HEAD CHID='B'/
&TIME T_END=10.0/ 
&MESH ID='Mesh01', IJK=10,13,12, XB=0.0,2.5,0.0,3.25,0.0,3.0/
&MESH ID='Mesh02', IJK=10,16,12, XB=-2.5,0.0,0.0,4.0,0.0,3.0/
&BNDF QUANTITY='ADIABATIC SURFACE TEMPERATURE'/
&BNDF QUANTITY='GAUGE HEAT FLUX'/
&TAIL /
```

**Comment by rmcdermo** [comment]
@Er9y714 Thanks for testing.  We'll have a look.

**Comment by mcgratta** [comment]
This is probably an FDS thing.

**Comment by mcgratta** [comment]
Set the range of the boundary quantity to something reasonable and the color artifacts will go away. Also, Show/Hide --> Geometry --> Obstacles --> Outline Only

Reopen the issue of this does not work.

**Comment by Er9y714** [comment]
@mcgratta Thank you for the reply. The suggestion solves the first issue. 

The second one remains.

Bytheway, I cannot reopen the issue.

**Comment by sbenkorichi** [comment]
I don't think it's a problem. Because you have two meshes, by default the boundary will be open, because they're seeing each other. That's why you see that small opening. You can however, specify a vent at that opening to be closed. I have got tricked by this previously, especially when using multi floors, and smoke end up being passed through these gaps. I either use a VENT to close it or an OBST to reflect a slab.
![image](https://user-images.githubusercontent.com/20113030/42043941-91cd0484-7aef-11e8-84cb-2bdb88409bc3.png)

**Comment by Er9y714** [comment]
I checked the flow and the pressure,  it is not OPEN to atmosphere. I would not expect it to be OPEN. Only the cross section where meshes are abut should be, and are, open to each other. 

Bytheway, I did not understand exactly where the smoke leaks in your example.

**Comment by mcgratta** [comment]
Glenn, there appears to be surface data in the .bf file where there is a blank wall in the picture, where the red arrow is pointing.

**Comment by gforney** [comment]
I'll take a look
