### ISSUE TITLE
input statement requires too much data, unit 42, file 

### ISSUE THREAD

**Issue by darkmclown** [firemodels/fds#6561]
Reading input file ...
forrtl: severe (67): input statement requires too much data, unit 42, file /data/RSMTemp/fds/lit_3/Pilot_0006.restart

When trying the run the job we are facing the following error

**Comment by Er9y714** [comment]
This is an error when I occasionally receive when I try to restart complex and large calculations.  Because it is hard to simplify the case, I never could submitted.

**Comment by mcgratta** [comment]
Windows? Linux? If Windows, we have no control over it.

**Comment by darkmclown** [comment]
Its Linux CentOS

**Comment by mcgratta** [comment]
Run your case for a short period of time. Stop it with a .stop file. Try to restart. If it fails, post the case as is. I will try to repeat the error.

**Comment by darkmclown** [comment]
The case already ran upto 850s (out of 3000s). All the files are kept safe. All this was done in FDS 6.6.0 on a Linux CentOS cluster. The cluster was formatted and 6.6.0 was installed again. On the cluster we don't see the files which support the run. We later installed FDS 6.7 version and could see that it says "input statement requires too much data..." as mentioned above. 

In short, for the above case:
1. 6.6.0 doesn't show files that support the run, after re-installing 6.6.0 on the cluster.  
2. 6.7 shows the above mentioned error. 

What is a right solution to this?

**Comment by Er9y714** [comment]
It is maybe unnecessary to ask but just to make sure: Do you run the case in 6.7.0 and restart with 6.7.0?

**Comment by mcgratta** [comment]
Four days ago, I asked you to do this:
```
Run your case for a short period of time. Stop it with a .stop file. Try to restart. If it fails, post the case as is. I will try to repeat the error.
```
but you did not do what I asked you to do. Now you are asking me "What is the right solution to this?" after doing something that i did not ask you to do. I am the person who wrote the restart feature in FDS, and yet you seem to have better ideas than I about how to fix the problem. If you want my help, you have to listen to what I ask you do to.

**Comment by darkmclown** [comment]
Thanks for the support guys,

It is working now, we ran we literations in 6.7 and used the restart file to run with existing data it is going good now.

I am closing this support request.
