### ISSUE TITLE
mpiexec problem FDS 6.7.0

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#6575]
The enclosed file TNL.fds runs with FDS 6.6.0 (mpiexec), but will not run under FDS 
6.7.0. Error code is enclosed (FDS 670 - MPI errors)

[tnl.txt](https://github.com/firemodels/fds/files/2151695/tnl.txt)
[FDS  670 - MPI errors.pdf](https://github.com/firemodels/fds/files/2151696/FDS.670.-.MPI.errors.pdf)

**Comment by mcgratta** [comment]
I would be surprised if this case ran with any version of FDS. Consider the `MESH` lines:
```
&MESH IJK= 100, 20, 16, XB=  0.00,  25.0,   0.00, 5.00,   0.00,  4.00 /
&MESH IJK= 100, 20, 16, XB=  0.00,  50.0,   0.00, 5.00,   0.00,  4.00 /
&MESH IJK= 100, 20, 16, XB=  0.00,  75.0,   0.00, 5.00,   0.00,  4.00 /
&MESH IJK= 100, 20, 16, XB=  0.00, 100.0,   0.00, 5.00,   0.00,  4.00 /
```
Do you really want all meshes to start at x=0?
