### ISSUE TITLE
Overlapping vents

### ISSUE THREAD

**Issue by MasterJLM** [firemodels/fds#6577]
I m trying to simulate an enclosure being blown top to bottom and how this affect the response of sprinkler heads. I just have a cube (one mesh) with the entire top surface (Zmax) as a vent of which the "supply" surface is assigned. Some sprinklers in a typical grid formation a bit lower than the supply vent are in place. Near the bottom I have assigned some exhaust surfaces on corresponding vents.

Here comes the problem. After activation of a sprinkler, an interlock switches off the supply and exhaust fans. I do this through a control. The problem is that I want the top surface (supply) and bottom vents (exhaust) of the enclosure to remain as open surface vents as in real life. I get error that I cannot have two vents overlapping and that only the first assigned will be accounted for in the calculation.

How can I model this really? How to tell I want an open vent after supply is off?

**Comment by rmcdermo** [comment]
This question is better suited for the Discussion Forum.  Issues is for reporting a bug or feature request.  Thanks.

https://groups.google.com/forum/#!forum/fds-smv

**Comment by MasterJLM** [comment]
oops! sorry about that
