### ISSUE TITLE
Render Current Frame dialog resets to All

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6578]
Per discussion forum.  Glenn please have a look.  I tested this simply using the  `fds/Verification/Fires/room_fire.fds` case.

Hi!

I found a malfunction in smokeview. I can't render the current frame. If I choose that option, the setting stays on the prior setting. I can choose "all" or "Every 2nd"... but not "Current".

rgs

Bastian

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here.  let me know if there is still a problem
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rmcdermo** [comment]
Works for me.
