### ISSUE TITLE
Add option for setup only of geometry and not mesh

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6579]
Per discussion forum,

I noticed that the set up of the geometry takes longer in 6.7. In a precise case (750.000 cells in 1 Mesh) FDS 6.6 needs less than 1 second to set up the geometry. In FDS 6.7. the "Checking mesh alignment. ..." needs about 10 seconds although it is just one mesh. In another case (2 Meshes, each 800.000 cells) the "set-up only" procedure need about 15 seconds. Against 1 or 2 seconds in FDS 6.6.

Since i check a lot during building the geometry, it slows down the workflow significantly. Is there a chance to reduce the time of the "set-up only" procedure?

Thank you and best regards,

Bastian

**Comment by drjfloyd** [comment]
Looking at main.f90 we call WRITE_SMOKEVIEW_FILE (where we write the geometry info) before we write the "Checking mesh alignment" message.  I think you should be able to open the smv file and view the geometry as soon you see the "Checking mesh alignment"  message appear.

**Comment by mcgratta** [comment]
That's a good point. You can open up Smokeview and see the geometry while FDS is doing MPI exchanges and array allocations that are necessary for formally checking whether the meshes are aligned properly. This would speed up your work flow, since you and FDS will probably find the error (if there is one) at about the same time. Does this work for you?

**Comment by rmcdermo** [comment]
When I am doing setup checks, I usually do not want to open SMV, but just want to see if FDS throws an error.  I think we should revert the change and add the mesh alignment logical as we discussed.

**Comment by mcgratta** [comment]
The functionality of `T_END=0` is restored. To check the mesh, set `CHECK_MESH_ALIGNMENT=.TRUE.` on any `MESH` line. Check this and then close the issue.

**Comment by rmcdermo** [comment]
On any mesh line or all mesh lines?

**Comment by mcgratta** [comment]
any

**Comment by rmcdermo** [comment]
It works. Thanks.

**Comment by Er9y714** [comment]
> The functionality of `T_END=0` is restored. To check the mesh, set `CHECK_MESH_ALIGNMENT=.TRUE.` on any `MESH` line. Check this and then close the issue.

I think user guide would be clearer if the amendment below is made:

**6.3.4 Mesh Alignment**

> If you would like to check the mesh alignment without running the case, set CHECK_MESH_ALIGNMENT to T on any MESH line **along with setting T_END to zero**.


Thanks

**Comment by rmcdermo** [comment]
Ok, thanks, I just pushed up your suggestion.  See PR #11129
