### ISSUE TITLE
emissivity not properly assigned

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#6581]
In the attached case there is a two layer surface where the emissivity of the two materials varies with the rest of the properties the same. The surface is applied to both sides of an OBST with it appropriately reversed and a radiant exposure set for one side.  WALL TEMPERATURE and BACK WALL TEMPERATURE of the two exposed wall cells diverge (i.e. WALL TEMPERATURE of the top diverges from BACK WALL TEMPERATURE of the bottom). The reason is that one side is getting the correct emissivity values and the other side is not.  The error is in setting ONE_D%EMISSIVITY. E_WALLB is OK. The fix appears to be that the back face is computed only by looking at NWP, but the front face is looping over all wall cells.  I think in POINT_LOOP3 we need to change the two IF statements with IF (.NOT. E_FOUND) to IF(I==1 .AND. .NOT. E_FOUND), i.e. only use the first node.  This fixes the problem with the case but I wanted to double check that this wasn't likely to break anything before committing it.

[e_test.txt](https://github.com/firemodels/fds/files/2156383/e_test.txt)

**Comment by mcgratta** [comment]
I don't recall writing this code. Seems like it would be rare to have an `EMISSIVITY` of zero. Give it a try.

**Comment by drjfloyd** [comment]
The zero was this was started as a quick case to illustrate something for a co-worker.  Zero isn't a real value, but can be useful as can be used to disable radiation for a surface without turning it off completely.

**Comment by Er9y714** [comment]
Speaking of emissivity, I noticed that both MATL and SURF lines can be attributed with EMISSIVITY. 
However could you clarify footnote please?

>  The EMISSIVITY of a MATL component of a SURF takes precedence over the EMISSIVITY specified on the SURFline. This is true even if no EMISSIVITY is explicitly specified on the MATL line. Its default value still takes precedence overwhatever might be specified on the SURF line.


Does it mean, because default emissivity is 0.9, if we do not assign emissivity to MATL line, then SURF by default gets 0.9, despite assigning a different emissivity on SURF line?

**Comment by drjfloyd** [comment]
Yes. EMISSIVITY on SURF is the for when you are specifying the surface temperature or heat flux.  EMISSIVITY on MATL is used any time you are predicting the surface temperature (i.e. have a MATL_ID for your SURF).

**Comment by Er9y714** [comment]
I am surprised to hear that. I had no idea it would be simply overruled. 

If `MATL `does not have `EMISSIVITY`, whereas `SURF `has, does not it implicate that the user wanted to assign an `EMISSIVITY `to the surface? Why is FDS designed to ignore the user's parameter and apply a different parameter without warning?

Also, is it physically possible that a surface has two emissivity properties? (material and surface-wise). For sure this gives flexibility for modelling but on the other hand, it is a vulnerablily for design.

**Comment by drjfloyd** [comment]
It is not without warning; we have explicitly noted this in the User's Guide. Processing inputs is not an easy thing. We attempt to provide flexibility and convenience to the user and allow for a wide range of applications. This often means that it is possible for users to specify a parameter in more than one way (think of all the ways one can specify a gas burner type fire: HRRPUA, MLRPUA, VEL with MASS_FRACTION, or MASS_FLUX). The logic for dealing with this can be quite complex. Sometimes we just have to make a decision on assigning priority to duplicative inputs (like we have to do with OBST and VENT definitions for the same grid cell). When we do this, we do try to make sure it is noted in the User's Guide.

It is not physically possible for a surface to have two emissivities.  Emissivity might change over time due to reactions in the materials making up the surface. FDS allows for this by using the material emissivities when heat transfer is being predicted which means as the type of material at the surface changes that the emissivity will change.

**Comment by Er9y714** [comment]
I understand and I agree with you. Also I acknowledge the wide range of design possibilities. But I also like when FDS warns (such as DEVC out of domain) or does not allow to run (wrong or missing input for thermal parameters). When emissivity is not defined for MATL but defined for SURF, I think a feedback would be useful. 

Nevertheless, I respect your decision on the issue. Because us users only see the one side of the software, I cannot predict what this modification would trigger on the source part.

Thank you for the replies.
