### ISSUE TITLE
PYROLYSIS of rigid PUR foam

### ISSUE THREAD

**Issue by jith178085** [firemodels/fds#6585]
Hi,
Is there any document regarding values of heat of combustion, heat of reaction and reference temperature of rigid polyurethane foam. 

I found only polyurethane pyrolysis values. can I use this same values of (heat of combustion, heat of reaction and reference temperature ) with density of rigid polyurethane foam. will that be a valid results of rigid polyurethane foam. 

please correct me if I am wrong.

**Comment by rmcdermo** [comment]
Please ask this question in the discussion forum.  This Issues page is for bug reports.  Thanks.
