### ISSUE TITLE
cpu optimize problem

### ISSUE THREAD

**Issue by iatalay19** [firemodels/fds#6588]
intel Xeon CPU E5-2650 v3 CPU is working slow too hard how can I optimize how to make hardware settings from where

**Comment by Er9y714** [comment]
Could you explain what you mean by hardware setting? Have you considered using MPI?

In the user guide §3.2, MPI is discussed. You can divide the domain into meshes and speed up the calculation. There are other suggestions in §1.4 Note on Longer Run Times in FDS 6 as well.

**Comment by iatalay19** [comment]
I am using open mp,
I am using version 5

**Comment by mcgratta** [comment]
We cannot help you unless you use the latest version of FDS, 6.7.0.

**Comment by iatalay19** [comment]
I did it, but the same in the new version

**Comment by mcgratta** [comment]
I still do not understand what you are asking. In any case, this is not the appropriate venue for general questions. Use the FDS Discussion Group after reading the FDS User's Guide.
