### ISSUE TITLE
Minor enhancement for dem2fds

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6589]
I ran the program `dem2fds` successfully using the input parameters in the FDS repo `Utilities/Misc/terrain_vegetation`. Two requests:
1. I noticed in this case that the FDS coordinates for the obstructions have y values running from -10 to 990.  The x coordinates run from 1 to 1000. Could the y values do the same?
2. I need to distinguish the `SURF_ID` for terrain obstructions that are close to the `OPEN` boundary. Currently, all obstructions are given the `SURF_ID` `surf1`. Could you label obstructions that are within, say `BUFF_DIST`, something else, `surf2` is fine. I need to assign different BCs. The `BUFF_DIST` can be an input parameter.

**Comment by gforney** [comment]
both should be implemented .  update your smv repo and give it a try.    (probably won't need to but I forgot to check against the zmax boundary am only checking against xmin, ymin, xmax and ymax boundaries)

**Comment by gforney** [comment]
to use 2., add the following lines to a dem2fds input file.  The default value is for BUFF_DIST is 10.0 m

BUFF_DIST
 10.0

**Comment by mcgratta** [comment]
Seems to work. I successfully created an input file and saw the buffer in place. Thanks.
