### ISSUE TITLE
Internal energy conservation for CC-IBM sphere case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6598]
Marcos,
I just pushed up a simple test that pumps 10 kW into a box with adiabatic walls for 10 sec.  The radius of the sphere is 1 m.  So the surface area is 4*pi*(1)**2 = 12.566 m2.  So, the internal energy of the system should rise by 1256.6 kJ.  However, we are only getting about 1000 kJ increase.  The test case is

`fds/Verification/Complex_Geometry/ccibm_sphere_heat_flux.fds`

The good news is that I printed out the value of CFA%ONE_D%QCONF from SOLID_PHASE_OUTPUT and it is correct.  This means that (1) the *input* works and (2) that you are correctly populating CFA%ONE_D%QCONF.  So, this may just be an issue of gathering STATISTICS for DEVC.

**Comment by Er9y714** [comment]
Should you add DEFAULT=.TRUE. to SURF line of WALLS?

**Comment by rmcdermo** [comment]
Ah... great catch!  That might be it.  I'll check when I get in.  Thanks.

**Comment by rmcdermo** [comment]
OK, this helped a little, now up to 1060 kJ, but did not fix things entirely.

**Comment by Er9y714** [comment]
Remark: changing grid size changes the DEVC output. 

btw, for the first time I see SMV output of GEOM objects. I was expecting to see a lego type sphere but it is actually not made of rectilinear blocks.

**Comment by marcosvanella** [comment]
@rmcdermo give it a try now. Note the discrete sphere Area is 12.50 m^2.

**Comment by marcosvanella** [comment]
Randy, try this case, I think we can close the issue. Adjusting for area we get 12.566/12.5*1.2390935E+003=1.2456e+03 KJ (0.8% difference).
PS : Running it in LES mode the difference is also ~0.8%.

**Comment by rmcdermo** [comment]
Yes, things seem to be converging.  Thanks
