### ISSUE TITLE
Problem with MESH alignment

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6609]
@mcgratta ,
I can't figure out what is going on here.  Check out the attached input file.  The current setup gives a mesh alignment error.  Now comment out the 2.5 mm mesh section and uncomment the 5 mm mesh section (at the moment they are both set up to be the same 5 mm, only the "2.5 mm" section is subdivided into more meshes).  The 5 mm case passes.

[FM_15cm_Burner.fds.txt](https://github.com/firemodels/fds/files/2184891/FM_15cm_Burner.fds.txt)

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/42579534-8e82bb32-84f6-11e8-9cd8-a107749d015a.png)

In the picture, you can see a coarse cell that abuts two finer cells, each on separate meshes. That's a no-no. This picture was shot from above using isometric projection.

**Comment by rmcdermo** [comment]
OK, thanks.
