### ISSUE TITLE
Temperature decreases within a small enclosed space

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#6611]
[test.txt](https://github.com/firemodels/fds/files/2188771/test.txt)

This simple compartment contains an insulated box in which the temperature decreases below ambient as the temperature outside increases due to a fire. Tightening the velocity/pressure tolerance helps, but I am wondering if there might be something else of issue here.

**Comment by rmcdermo** [comment]
`&PRES SOLVER='UGLMAT'/` works perfectly.  These are min/max temps.

![test_0081](https://user-images.githubusercontent.com/4418497/42638082-c32ea250-85ba-11e8-846d-acfd89af986b.png)

**Comment by Er9y714** [comment]
I ran both the first input file and with UGLMAT.  They both show smaller temperatures than 20 C.

![image](https://user-images.githubusercontent.com/26166281/42684244-d11226b4-868f-11e8-815c-7cc0f10cac0b.png)

**Comment by mcgratta** [comment]
How much smaller in each case?

**Comment by Er9y714** [comment]
Both have the same range on the scale for 60 s calculation.  Min is -85.6, max is 1381

**Comment by rmcdermo** [comment]
Ersin,
It is fine.  I suspect you are running a release version, which has an inconsistent naming convention for GLMAT.  This has since been fixed.  If you compile the current source, it works with UGLMAT (for Unstructured GLMAT).  Here is my input file.  Yours should work with `&PRES SOLVER='GLMAT'`.  (@marcosvanella please correct me if I am wrong.)

[test.fds.txt](https://github.com/firemodels/fds/files/2192877/test.fds.txt)

![test_0996](https://user-images.githubusercontent.com/4418497/42694809-863e493c-8681-11e8-8380-a0bc1f60e1e5.png)

**Comment by marcosvanella** [comment]
Randy, that is correct. I run the case with latest source and with SOLVER='UGLMAT' the min Temp on this slice stays in 19.9996 C.
Ersin if you are using the 6.7 release you should get the same result as us making SOLVER='GLMAT'. 
Sorry about the confusion, we are trying to make the nomenclature of parameters consistent with the ScaRC solver. 
The new name UGLMAT refers to Unstructured GLMAT, a pressure solver that only wolves on the gas phase. The temperature on the cells inside OBSTS should stay in the value given at setup (ambient).
This is the same solver as GLMAT on release 6.7, you can check by looking at the User guide from that release and the actual guide (nightly build in the FDS Documentation page).

**Comment by Er9y714** [comment]
@rmcdermo, You are right, I run a release version.  GLMAT outputs correct result. 

btw, since you refer to me with my name, is my profile name visible? Not that intend to hide but I did not write it anywhere. 
Similar thing happened in the discussion forum as well. Some user sent me a mail which he accessed by the forum.

**Comment by rmcdermo** [comment]
Sorry, did not know you were incognito.  I just took it from discussion forum posts.

**Comment by Er9y714** [comment]
So it is not visible here github at least. Thanks for the feedback.

**Comment by Er9y714** [comment]
This file runs with GLMAT but has temperatures lower than TMPA on the SMV. Device file shows above TMPA temps. However there is this corner cell which stands out. 

 
![image](https://user-images.githubusercontent.com/26166281/42702992-66f7b758-86cb-11e8-9e9f-6158065914b8.png)

![image](https://user-images.githubusercontent.com/26166281/42702790-cad8b0de-86ca-11e8-836d-e7b176df3cae.png)

```
&HEAD CHID='a'/
&TIME T_END=20.0/
&DUMP DT_DEVC=0.5 DT_SLCF=0.5/
  
&MESH ID='Mesh01', IJK=30,1,5, XB=0.0,0.3,0.0,0.01,0.0,0.05/
 
&DEVC ID='T1', QUANTITY='TEMPERATURE', XYZ= 0.005,0.005,0.002/
&DEVC ID='T2', QUANTITY='TEMPERATURE', XYZ= 0.15,0.005,0.002/
&DEVC ID='T3', QUANTITY='TEMPERATURE', XYZ= 0.295,0.005,0.002/
&PRES SOLVER='GLMAT'/
&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      DEFAULT=.TRUE.,
      ADIABATIC=.TRUE./
&SURF ID='heater',
      RGB=255,102,0,
      HEAT_TRANSFER_COEFFICIENT=1.0E4,
      TMP_FRONT=150.0,
      EMISSIVITY=0.7/ 
 
&OBST ID='Obstruction', XB=0.0,0.3,0.0,0.01,0.0,0.0, SURF_IDS='heater','ADIABATIC','ADIABATIC'/ 

&VENT ID='Vent', SURF_ID='OPEN', XB=0.3,0.3,0.0,0.01,0.0,0.01/ 
&VENT ID='Vent01', SURF_ID='OPEN', XB=0.0,0.0,0.0,0.01,0.0,0.01/ 
&SLCF QUANTITY='TEMPERATURE' PBY=0.005 CELL_CENTERED=T/

&TAIL /
 
```

**Comment by rmcdermo** [comment]
HEAT_TRANSFER_COEFFICIENT=1.0E4 ??

**Comment by rmcdermo** [comment]
You were the one asking about CHECK_HT... well, here you need it.  Add `&MISC CHECK_HT=T/` and it will work, even with the insanely high HTC you are using.

**Comment by Er9y714** [comment]
Yes, CHECK_HT solved it. 

I m trying to model a simple mock furnace for heating a specimen. 1.0E4 came from one of the trials. I guess I should not leave the range of reasonable values.


edit: I do not remember asking, but yes I may have asked.

**Comment by rmcdermo** [comment]
I think 10^4 is the kind of HTC you get for boiling.

**Comment by Er9y714** [comment]
Negative temperature values output at the `PROF` file when `FREEZE_VELOCITY` is enabled. 

Also I noticed that when I assign a `SPECIFIC_HEAT_RAMP`, the number of nodes in the PROF file doubles.


```
 
&HEAD CHID='2'/
&TIME  T_END=7200/ 
&DUMP   DT_DEVC=1.0, DT_SLCF=1.0/
&MISC CHECK_HT=.TRUE. , FREEZE_VELOCITY=T/
&PRES SOLVER='GLMAT'/

&MESH ID='Mesh01', IJK=16,1,8, XB=0.0,0.04,0.0,2.5E-3,0.0,0.02/

&MATL ID='Ins',
      SPECIFIC_HEAT=1,
      CONDUCTIVITY_RAMP='Ins_CONDUCTIVITY_RAMP',
      DENSITY=932.0,
      EMISSIVITY=0.7/

&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=0.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=40.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=80.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=100.0, F=0.6/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=105.0, F=0.6/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=109.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=110.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=115.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=200.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=220.0, F=0.05/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=300.0, F=0.03/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=500.0, F=0.018/
&RAMP ID='Ins_CONDUCTIVITY_RAMP', T=1600.0, F=0.018/
   
&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      DEFAULT=.TRUE.,
      ADIABATIC=.TRUE./
&SURF ID='Ins',
      RGB=146,202,166,
      HEAT_TRANSFER_COEFFICIENT=15.0,
      EMISSIVITY=0.7,
      TAU_T=0.0,
      MATL_ID(1,1)='Ins',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=0.026/
 
&SURF ID='supply_RWS',
      RGB=255,102,0,
      TMP_FRONT=1500.0,
      EMISSIVITY=1.0,
      /
      

&OBST ID='Obstruction', XB=0,0.04,0.0,0.04,0.01,0.01, SURF_IDS='Ins','Ins','supply_RWS'/  
 
&VENT ID='OPEN02', SURF_ID='OPEN', XB=0.04,0.04,0,0.04,0.0,.02, COLOR='INVISIBLE'/  
&PROF ID='Prof', XYZ=0.02,1.25E-3,0.01, IOR=+3, QUANTITY='TEMPERATURE'/
  
&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., CELL_CENTERED=.TRUE., PBX=0.02/
&SLCF QUANTITY='TEMPERATURE', VECTOR=.TRUE., CELL_CENTERED=.TRUE., PBZ=5.015617887709E-3/
 
&TAIL /
```

**Comment by rmcdermo** [comment]
Don't use `FREEZE_VELOCITY`.  It is only applicable when you know a specific analytical solution to your problem with a known velocity field.

The number of nodes in the solid is computed from the thermal diffusivity, see Tech Guide, Appendix L, Eq L.3.

This Issue has veered into discussion forum territory.  I'm going to close.
