### ISSUE TITLE
Use SLCF as VENT boundary condition

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6617]
I have an idea of how to do this.  I will post developments here.

**Comment by Aditya62** [comment]
OK got it.

**Comment by Aditya62** [comment]
I just wanted to ask if there is anything that I am supposed to do?

**Comment by rmcdermo** [comment]
At the moment, no, unless you figure out how to do it yourself.  I've been pulled off onto other things .  Not sure when I will finish this.

**Comment by Aditya62** [comment]
Ok got it and I'am sorry to disturb you.

**Comment by rmcdermo** [comment]
I don't remember where this is or why we needed it.  I know that U. Alabama is still having issues with RMS velocity in their cube case, but it is not clear what the problem is.  I'm closing and will revisit if necessary.
