### ISSUE TITLE
BNDF of BURNING RATE on Circular Vent

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6621]
I ran the example case of `circular_burner` with `BURNING RATE` boundary file. However I cannot see the BOUNDARY in SMV. 

Thank you for checking it,

 

```
&HEAD CHID='circular_burner', TITLE='Test the mass flow rate from a circular burner' /

&MULT ID='mesh array', DX=1.0,DY=1.0,DZ=1.0, I_UPPER=1,J_UPPER=1,K_UPPER=1 /
&MESH IJK=20,20,20, XB=-1.0,0.0,-1.0,0.0,0.0,1.0, MULT_ID='mesh array' /
 
&TIME T_END=20. /
&DUMP DT_BNDF=0.1/
&REAC FUEL='PROPANE', SOOT_YIELD=0.015 /

&SURF ID='BURNER', MASS_FLUX(1)=0.02, SPEC_ID(1)='PROPANE', TAU_MF(1)=0.01 /

&VENT XB=-0.6,0.6,-0.6,0.6,0,0, XYZ=0,0,0, RADIUS=0.5, SPREAD_RATE=0.05, COLOR='BLUE', SURF_ID='BURNER' /

&VENT MB='ZMAX',SURF_ID='OPEN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/



&SLCF PBY=0.0, QUANTITY='TEMPERATURE' /
&BNDF QUANTITY='BURNING RATE' CELL_CENTERED=.TRUE./

&TAIL /
```

**Comment by rmcdermo** [comment]
@gforney I think this may be an SMV issue.  I checked that FDS is properly computing the 'BURNING RATE' in the SOLID_PHASE_OUTPUT routine.  And... if you look at the SMV colorbar you can see that it is getting the limits correct, which tells me it has the data.  But I think this goes back to drawing a CIRCLE over the VENT for visualization purposes.  Probably that is taking precedence over the BNDF.

**Comment by gforney** [comment]
I'll take a look at it

**Comment by gforney** [comment]
when I look at the contents of the .bndf file when smokeview reads it in, I only see one patch for the entire bottom surface (0,20,0,20,0,0 ). I don't see patches corresponding to the circular vent.

**Comment by rmcdermo** [comment]
OK, off the top of my head I am not sure how BNDF are written out.  What happens when you draw that patch?

**Comment by rmcdermo** [comment]
Based on lines circa 8236 of dump, it looks to me like the correct SOLID_PHASE_OUTPUT will be written out for the "patch".  Let's see what happens.

**Comment by gforney** [comment]
In smokeview, I put a write immediately after the read  that reads in the boundary file data ie
  read(file_unit,iostat=error)(pqq(ii),ii=ibeg,iend)
  write(6,*)(pqq(ii),ii=ibeg,iend)

I'm seeing all zeros printed out.

one question though.  I figure there are two issues.  1.  what data is output and 2.  where the data is output.  For 1. I'm seeing all zeros.  For 2. maybe I misunderstood but I was expecting to see the boundary data where the circular vent is located.  Instead I'm seeing the boundary data for the entire "floor" .  Where should I see the boundary file data?

**Comment by rmcdermo** [comment]
I would think for the whole floor.  It is a boundary.  But I did not write the BNDF output stuff, so I will have to study it to figure it out.  All I know right now is that SOLID_PHASE_OUTPUT for the WALL_CELLS in the circle is being computed correctly.  My next stop is to dig into the LU_BNDF, but that may not happen until Monday.

**Comment by gforney** [comment]
a little used smokeview feature may be of help for looking at raw boundary file data.

open up the boundary file tab of the bounds dialog box.  Then open the output data tab.  select the region you want to output (I've fixed the min/max settings so that by default they define the entire domain ).  

check the "Output data to file" checkbox.

The next time you load a boundary file, the data will be output to spreadsheet file for the space/time region you selected.

I tried this option for this test case and the spreadsheet data seems to be consistent with the data I was seeing with the write placed after the read.

I probably won't get much done until tuesday.

**Comment by rmcdermo** [comment]
@gforney 

When outputting the .csv files for the test case, you can see that the values of 0.02 are present in the bndf files.  Here is one of the patches.

[circular_burner_bndf_0001.csv.txt](https://github.com/firemodels/fds/files/2198196/circular_burner_bndf_0001.csv.txt)

Further, if you condition the output on being greater than some small number, you see that the values are getting put into the array that are written out to LU_BNDF.  If I add the following to line 8249 of dump,
```
      ! Evaluate the given boundary quantity at each cell of the current PATCH

      DO K=PA%KG1,PA%KG2
         DO J=PA%JG1,PA%JG2
            DO I=PA%IG1,PA%IG2
               IC = CELL_INDEX(I,J,K)
               IW = WALL_INDEX(IC,-PA%IOR) ; IF (IW==0) CYCLE
               SELECT CASE(ABS(PA%IOR))
                  CASE(1) ; L=J ; N=K
                  CASE(2) ; L=I ; N=K
                  CASE(3) ; L=I ; N=J
               END SELECT
               IF (WALL(IW)%BOUNDARY_TYPE/=NULL_BOUNDARY .AND. &
                   WALL(IW)%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY .AND. .NOT.SOLID(IC)) THEN
                  IBK(L,N) = 1
                  PP(L,N)  = REAL(SOLID_PHASE_OUTPUT(NM,IND,BF%Y_INDEX,BF%Z_INDEX,BF%PART_INDEX,OPT_WALL_INDEX=IW),FB)
                  if (PP(L,N)>0.00001) print *,NF,PP(L,N)  <===== HERE is line 8249 in dump
               ENDIF
            ENDDO
         ENDDO
      ENDDO
```
then I see
```
Time Step:     30, Simulation Time:      1.19 s
           1  2.0000000E-02
           1  2.0000000E-02
           1  2.0000000E-02
           1  2.0000000E-02
           ...
```

**Comment by gforney** [comment]
I wasn't looking far enough down my csv file for non-zero values.  I'll
take another look at what is going on.

**Comment by gforney** [comment]
@rmcdermo was right, the circular vent is hiding the boundary file.  Until I get smokeview to do this automatically use the Show/Hide>Geometry>Surfaces>Hide All to hide the circular vent.  you should now see the burning boundary file

**Comment by gforney** [comment]
I've uploaded a PC version of smokeview that should fix the problem.  I'll upload mac and linux versions tomorrow.  Let me know if it works for you.
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
It is resolved! Thank you all.

**Comment by gforney** [comment]
I uploaded osx and linux smokeview's with this fix
