### ISSUE TITLE
Running FDS 6.7.0 in the cluster (taito.csc.fi)

### ISSUE THREAD

**Issue by dpkPrasadPaudel** [firemodels/fds#6629]
I have been carrying out serial batch jobs in the cluster (taito.csc.fi) using FDS 6.5.3 (the precompiled version which was installed as "bash FDS 6.5.3-SMV5.6.3_linux64.sh") with sh-script:
![screen shot 2018-07-14 at 21 57 36](https://user-images.githubusercontent.com/18634233/42727510-0e166a3a-87b1-11e8-99dc-9afd0dfcf8b9.png)
The tasks would run normally without any issue. 

However, after updating to FDS 6.7.0 ( "bash FDS6.7.0-SMV6.7.1_linux64.sh"), the same tasks would not run in the cluster, returning error:
![screen shot 2018-07-14 at 22 02 21](https://user-images.githubusercontent.com/18634233/42727532-9eb12d00-87b1-11e8-99d3-b3f5c2f86a07.png)

I have modified ".bashrc"  as instructed: 
https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-on-a-Linux-Cluster

A single task in the cluster in the interactive mode >> "fds NFSC2_Room_2.fds" would, however, run without any issue.

It is difficult to understand why the serial batch tasks would not run. I would appreciate any comments!

**Comment by rmcdermo** [comment]
@sbenkorichi Can you please see if you can help.  Thanks.

**Comment by sbenkorichi** [comment]
I will take a look.

**Comment by sbenkorichi** [comment]
@DpakPaudel 
Have you also set the same fds env in the `.profile` script that is found in your /home directory same as `.bashrc`. 
Can you also make a simple job script that you use as above and add these lines before the fds line: 
```
which fds
which mpiexec 
ulimit -a
```

Check the `-o out` file what you your cluster returns.

**Comment by dpkPrasadPaudel** [comment]
@sbenkorichi 
Now I have same fds env at ~/.bash_profile

For a simple sh-script
<img width="462" alt="screen shot 2018-07-15 at 02 05 38" src="https://user-images.githubusercontent.com/18634233/42729028-9dd3b804-87d3-11e8-9f4f-fd79aa1f5016.png">

I get -o out as 
<img width="518" alt="screen shot 2018-07-15 at 02 04 29" src="https://user-images.githubusercontent.com/18634233/42729029-a73ba3ac-87d3-11e8-8704-9b2e9541f418.png">

**Comment by sbenkorichi** [comment]
@DpakPaudel 
Interesting, I'm just learning now about the Taito cluster that you're using. I wonder what's the need for specifying the --Arrays here for a simple single serial job.
Can you try to add the following: 
```
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH -p serial
```
This will just ensure that you're using a same cores of single node. (4 refers to the nbr of cores here).
Can you use a simple batch on one of the fds examples that come with the fds installation.
Can you also try this:
`mpiexec -np 1 fds  job.fds`
and run it in parallel just to see if it works or not.
Also, do you use fds through an installed modules or simply the one you install from the bundle.

Your cluster's computing nodes are based on `Centos 6`. I will try to install it soon on my VM box and check if I can reproduce this.

**Comment by dpkPrasadPaudel** [comment]
@sbenkorichi 
Thank you for the help. 

I was actually not doing parallel computing.  I used --array feature to run several fds models at the same time. With the pre-compiled FDS 6.5.3, this was done using 
`fds job_name_"$slurm_array_id"`.  The same could not be done with pre-compiled FDS 6.7.1. 

With cloned and compiled FDS 6.7.1, I could still do the same task using 
`srun path/fds_mpi_gnu_linux_64 job_name_"$slurm_array_id"` but the computations are slower than pre-compiled FDS 6.5.3.

Now came to realize that each array job can be parallelized into n-tasks:                                                                            
`#SBATCH -N 1 `                                                                                                      
`#SBATCH -n 2  #number of meshes `                                                                                                      
`#SBATCH --array=2,3,4,5,6,7,8,9,11,12,13,15,16,17,18,19,20 `                                                                                             
`#SBATCH --mem-per-cpu=500`                                                                                         
`#SBATCH --cpus-per-task=12`                                                                                         
`export KMP_AFFINITY=compact`
`export OMP_NUM_THREADS=4`
`srun $WRKDIR/fds/Build/mpi_gnu_linux_64/fds_mpi_gnu_linux_64 NFSC2_Room_"$SLURM_ARRAY_TASK_ID".fds`

**Comment by sbenkorichi** [comment]
Glad it's working for you now.
 Yes it will be slower than the bundle, if you want have same speed than you need to compile fds with Intel compiler instead of GNU.
