### ISSUE TITLE
CTRL: Activation happens before SETPOINT is reached 

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6657]
Run the attached simple case. OBST is supposed to get removed after THCP DEVC reaches 300C. 
But, in this case it activates at 232C instead.

```
&HEAD CHID='test'/
&TIME T_END=20.0/
&DUMP NFRAMES=20/
&MISC Y_O2_INFTY=0.23/

&MESH ID='MESH1', IJK=39,38,26, XB=5.4,9.3,2.7,6.5,0.0,2.6/

&REAC ID='POLYURETHANE',
      FYI='NFPA Babrauskas',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      SOOT_YIELD=0.1,
      HEAT_OF_COMBUSTION=2.0E4/

&CTRL ID='Window', FUNCTION_TYPE='ALL', LATCH=.FALSE., INITIAL_STATE=.TRUE., INPUT_ID='latch'/
&CTRL ID='latch', FUNCTION_TYPE='ALL', LATCH=.TRUE., INPUT_ID='THCP'/
&DEVC ID='THCP', QUANTITY='TEMPERATURE', XYZ=8.6,6.15,1.7, SETPOINT=300.0/
&DEVC ID='THCP2', QUANTITY='TEMPERATURE', XYZ=8.6,6.15,1.7/

&SURF ID='Fire-0.6MW',
      COLOR='RED',
      HRRPUA=234.37/

&OBST ID='Window', XB=8.2,9.0,6.2,6.4,1.1,2.3, RGB=0,255,240, TRANSPARENCY=0.54902, SURF_ID='INERT', CTRL_ID='Window'/ 
&OBST ID='Obstruction', XB=8.2,9.0,6.2,6.4,0.0,1.1, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=8.2,9.0,6.2,6.4,2.3,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=5.4,5.6,2.9,6.2,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=5.4,8.2,6.2,6.4,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=5.4,9.3,2.7,2.9,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=9.0,9.3,6.2,6.4,0.0,2.6, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=9.1,9.3,2.9,6.2,0.0,2.6, SURF_ID='INERT'/ 

&VENT ID='0.6MW', SURF_ID='Fire-0.6MW', XB=7.4,9.0,4.1,5.7,0.0,0.0/ 

&SLCF QUANTITY='TEMPERATURE', PBX=8.6/

&TAIL /
```
Thanks !

**Comment by rmcdermo** [comment]
I set DT_DEVC to something very small.  Here is the output around 13 s.  C'mon man.
```
 1.2999040E+001, 2.9599753E+002
 1.3013633E+001, 3.0488353E+002
 1.3028226E+001, 3.1559238E+002
```

**Comment by sbenkorichi** [comment]
Thanks Randy for checking it. 
I haven't thought of that. It did help. 
Cheers,

**Comment by sbenkorichi** [comment]
Another option that helps without setting `DT_DEVC` is `TIME_AVERAGED=F` on `&DEVC `line. 

```
12.005925 | 214.50829 | 217.1338
13.013636 | 304.89095 | 231.88887
14.005592 | 211.08824 | 231.57359
```

**Comment by drjfloyd** [comment]
That writes the value at the timestep when the output is written, it will
not always be the maximum value.

**Comment by sbenkorichi** [comment]
I see, thanks Jason. Just asking, is there any reason why `DT_DVEC` is set to `-1_EB` on the read file,
Is it to simply get values DUMPED for each second, or has a different reason?
I set it to `0.5_EB` (as a default) and I start getting values over 300C without specifying `DT_DEVC` in the input file. What adverse effect could this bring?

**Comment by drjfloyd** [comment]
In the current version of Fortran we don't know what Namelist variables are
given. For some variables we set the default to an invalid value to let us
test if the user has changed it. In this case if after reading the inputs,
DT_DEVC is less than 0, we know to set it using NFRAMES.

**Comment by sbenkorichi** [comment]
Right, thanks for the info. And if it's not given a value then one end up getting into that initialisation of parameters issue.
Cheers,
