### ISSUE TITLE
Feature request: Increase CHID string characters

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6662]
I would like to request increasing the current number of strings of the CHID to more than 40 characters as sometimes I usually I need to put more characters at work for organizing large files in the archive, and end up being limited to 40 characters. Increasing it a bit to 50 or 60, or more would definitely help.

Thanks !

**Comment by rmcdermo** [comment]
We'll run through firebot and see if this causes any trouble.  If not, we'll make the change.

**Comment by mcgratta** [comment]
```
CHARACTER(255) :: CHID,RESTART_CHID
```

**Comment by brianhardeman** [comment]
This increased limit causes crashes with CHID strings more than about 60 characters long.  The crashes occur in opening output files that combine the CHID with a suffix and extension and write the result into an 80-long character variable.

**Comment by mcgratta** [comment]
Moved to #7446
