### ISSUE TITLE
Create uniform random position routine for CFACEs

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6701]
@marcosvanella I've pushed up the code to insert particles at CFACES.  For the time being, I am just injecting them from the CFACE centroid, CFA%X, etc.  The code is in part at around line 610.
```
LP%X = CFA%X + CFA%NVEC(1)*VENT_OFFSET*DX(IIG)
LP%Y = CFA%Y + CFA%NVEC(2)*VENT_OFFSET*DY(JJG)
LP%Z = CFA%Z + CFA%NVEC(3)*VENT_OFFSET*DZ(KKG)
```
Can you create a routine that will give us a uniform random position on the CFACE?  This will make the particle injection routine behave more like the WALL_CELL injection.  Thanks.

**Comment by marcosvanella** [comment]
Will do.

**Comment by marcosvanella** [comment]
@rmcdermo do you have a sample fds input file for this particles ejection from CFACE test? Thanks.

**Comment by rmcdermo** [comment]
@marcosvanella Try this case:

https://github.com/firemodels/fds/blob/master/Verification/Complex_Geometry/geom_particle_flux.fds

**Comment by marcosvanella** [comment]
Update your repo and give it a try.

**Comment by mcgratta** [comment]
I used this feature in a terrain case and it appears to be working.
