### ISSUE TITLE
Correct cross correlation of u and T in Waterloo Methanol

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6714]
![screen shot 2018-07-30 at 11 20 41 am](https://user-images.githubusercontent.com/4418497/43406604-9fb2b4c2-93ea-11e8-99b8-d293b719b2d5.png)

@mcgratta I think the difference between the data and cross correlation with u*T here (left side of r=0) is just a matter of taking an absolute value.

**Comment by drjfloyd** [comment]
TIME_AVERAGED = FALSE writes the instantaneous value of the output, i.e. it is not averaged over DT_DEVC.  ABSOLUTE_VALUE writes the absolute value of the output, i.e. if the DEVC output were -1 it would be written as 1.

**Comment by Er9y714** [comment]
Sorry, I realized that just after posting question.

**Comment by mcgratta** [comment]
Have a look at the latest Validation Guide. I replaced the horizontal velocity u with a `'RADIAL VELOCITY'` such that a positive value points away from the origin.
