### ISSUE TITLE
Conversion of 3D CAD Model to FDS file

### ISSUE THREAD

**Issue by KrishPVS** [firemodels/fds#6726]
Hello all, 

I would like to know if there are any free open sources to build the 3D - CAD Model from 2D drawings and further convert it to a FDS file all in a single tool. 

It would be a great help. 

Thanks in advance.

**Comment by gjaeger** [comment]
You can find some information in the [wiki - Third Party Tools](
https://github.com/firemodels/fds/wiki/Third-Party-Tools#cad-file-conversion-tools).

**Comment by mcgratta** [comment]
In future, use the FDS-SMV Discussion Group for these kinds of questions. The Issue Tracker is for reporting bugs.
