### ISSUE TITLE
Implement MOVE_ON_SOLID for particles on GEOM

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6742]
@mcgratta If you are up for it, I have a challenge for you.  I just pushed up a case [here](https://github.com/firemodels/fds/blob/master/Verification/Complex_Geometry/geom_particle_cascade.fds) that is a variation of the particle_flux case.   But in this one, particles are inserted from a GEOM and then should hit a nearby sphere.  In the current code, the particles just pass right through the sphere, as shown below.  Can you try to add the MOVE_ON_SOLID logic for the CFACES?

![geom_particle_cascade_0559](https://user-images.githubusercontent.com/4418497/43612517-916b6d4a-967a-11e8-811c-7a47b237a8f3.png)

**Comment by mcgratta** [comment]
PR #7519 adds code to block droplets and particles. I still need to add a verification case or two.

**Comment by rmcdermo** [comment]
So particles follow the unstructured geometry?

**Comment by mcgratta** [comment]
Yes

>
