### ISSUE TITLE
SMV Reload Feature

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6744]
SMV 6.7.1

After loading a slicefile or boundary file, 
Click on: **Load/Unload > Reload > When:**

Clicking on "**When:**" puts SMV into a long process. No outcome.

Thank you.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
Thank you  @gforney, it is solved!
