### ISSUE TITLE
Running FDS in parallel in cluster

### ISSUE THREAD

**Issue by ankit171032** [firemodels/fds#6763]
I want to run my case in Linux cluster. When I am using the command "mpiexec -n 4 fds jobname.fds" in job script, Code is running only in series even with this command. No of MPI processes is always 1. It should be 4 for parallel.
Please suggest some solution.

**Comment by sbenkorichi** [comment]
Provide these details
1. Which fds release are you using.
2. on terminal do: `which mpiexec`
3. on terminal do: `nproc --all`
3. Post what you get when you run `mpiexec -np 4 fds jobname.fds`

**Comment by tgob** [comment]
Try adding the following to your command line:

-env OMP_NUM_THREADS 4

If you always want this as the default then have a look at your .bashrc file and make sure that the variable is being defined.

Take a moment to read the --help for mpiexec command line options.

-np defines allocated processes, which have nothing to do with OpenMPI allocations.

Make sure you have sufficient actual cores on each node to actually do what you are requesting.  You are specifying 4 MPI processes and you also want to assign 4 OMP threads per process, all with a single node!  I hope your processor has more than 16 real cores available.

In terms of efficiency, in general press for more MPI (subject to available meshes) with perhaps 2 OMP threads if you have the capacity.  As stated in the FDS users guide (yes, I encourage you to re-read this in its entirety) MPI is almost always more efficient than OMP.

**Comment by sbenkorichi** [comment]
@ankit171032 
Have you tried the above commands?

**Comment by ankit171032** [comment]
Yes @sbenkorichi . 
There was some problem in the runscript. Now it is working fine in parallel.
 Can you tell why the time step is larger in the beginning and as simulation proceeds it decreases due to which simulation time keeps on increasing.

**Comment by sbenkorichi** [comment]
Ok, good.
Well, that's because to due to certain constraints applied in order to maintain accuracy and stability. Look into the user guide for their general discussion (for instance CFL), more detailed information can be found in technical guide. If you have further information on this, a good place to ask is using the Discussion group forum.
