### ISSUE TITLE
Temperature of Supply reducing after 330 s 

### ISSUE THREAD

**Issue by fds-user1** [firemodels/fds#6767]
Hi All,

I am running a simulation to study the temperature profile inside a shaft. The shaft has multiple supply vents of ambient temperature 34.3 Deg C and one Supply vent of 200 Deg C. After 330 s, the temperature from the supply vent (200 Deg C) is reducing below the ambient temperature. 
I used TMP_FRONT for the supply temperature. Attached the images for temperature slices and .txt file. 

(https://github.com/firemodels/fds/files/2288033/Shaft1.txt)

Time 25 s
(https://user-images.githubusercontent.com/42365115/44109830-aa7800b4-a01b-11e8-8ba0-354ec3027ff3.png)

Time 331 s
(https://user-images.githubusercontent.com/42365115/44109874-ccb3d450-a01b-11e8-95ff-1674081438cf.png

Time 420 s

(https://user-images.githubusercontent.com/42365115/44109924-efc85e34-a01b-11e8-93c1-949826994758.png)
)

Can anyone please help me understand the reason for such strange behavior .

Thanks in advance.

**Comment by rmcdermo** [comment]
This question should be posted to the discussion forum.

https://groups.google.com/forum/#!forum/fds-smv
