### ISSUE TITLE
Typo in T.G

### ISSUE THREAD

**Issue by springcb** [firemodels/fds#6772]
5.1.2.
Example Consider....... Note that, by default, Air is primarily composed of oxygen and nitrogen but includes trace amounts of carbon dioxide and water vapor.

(trace -> traced ?)

5.2.5
The concentrations (mol/cm3) and mass fractions (kg α/kg) are related by .......

(kg α/kg -> kg/kg ?)

**Comment by rmcdermo** [comment]
Actually, both are correct.  In Sec. 5.2.5 I made one clarification, the units of concentration should be mol-alpha/cm3.  See PR #6774
