### ISSUE TITLE
Smoke propagation

### ISSUE THREAD

**Issue by alexismano** [firemodels/fds#6796]
Hello! I have completed a case of fire and i have used pictures to demonsrate the smoke propagation in the room but i need to use also a plot to show the propagation in numbers.How can i do it?

**Comment by drjfloyd** [comment]
This issue tracker is for reporting bugs. Questions on using FDS should be posted to the discussion forum.

https://groups.google.com/forum/?fromgroups=&nomobile=true#!forum/fds-smv
