### ISSUE TITLE
Validation Manual Table 14.1: Possible typo

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#6801]
Kevin, 
Could you please review this when you have time
In table 14.1 of Validation guide and its input files, the density of HDPE, HIPS and PMMA materials is not the same as in Ref 173.
Is there any reason for this?

Thanks !

**Comment by mcgratta** [comment]
The density was estimated by taking the mass of the sample and dividing by its volume. This turns out to be slightly different than the reported densities.

**Comment by sbenkorichi** [comment]
Interesting,
If you feel we don't need to update the inputs and table, then please feel free to close this ticket.

Thanks !
