### ISSUE TITLE
Linking Error when running make_fds.bat on Windows 10 64-bit.

### ISSUE THREAD

**Issue by CarlMarcus** [firemodels/fds#6812]
As mentioned, I correctly installed Intel MPI library, Git, Gnu Make, Intel Visual Fortran Composer XE 2013 and its SP1 addon. Set environment variables correctly so that no "system cannot find the specified path " issues occur.
    But when running make_fds.bat in FDS 6.6.0 version/Build/impi_intel_win_64 folder, it raised such errors:
ipo: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_40684.obj
ipo: error #11023: Not all components required for linking are present on command line
ipo: remark #11000: performing multi-file optimizations
ipo-2: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_406842.obj
ipo-2: error #11023: Not all components required for linking are present on command line
ipo-1: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_406841.obj
ipo-1: error #11023: Not all components required for linking are present on command line
ipo-2: remark #11004: starting multi-object compilation
ipo-1: remark #11004: starting multi-object compilation
ipo-2: remark #11006: generating object file C:\Users\asus\AppData\Local\Temp\ipo_406842.obj
ipo-1: remark #11006: generating object file C:\Users\asus\AppData\Local\Temp\ipo_406841.obj
ipo-3: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_406843.obj
ipo-3: error #11023: Not all components required for linking are present on command line
ipo-3: remark #11004: starting multi-object compilation
ipo-3: remark #11006: generating object file C:\Users\asus\AppData\Local\Temp\ipo_406843.obj
Microsoft (R) Incremental Linker Version 11.00.50727.1
Copyright (C) Microsoft Corporation.  All rights reserved.
Briefly speaking : 
error LNK 2019: unresolved external symbol CLUSTER_SPARSE_SOLVER_D referenced in function SCRC_mp_SCARC_METHOD_CLUSTER
error LNK 2001: unresolved external symbol CLUSTER_SPARSE_SOLVER_D 
fatal error LNK1120

Samely running the make_fds.bat of FDS master branch. It raised such errors:
ipo: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_175844.obj
ipo: error #11023: Not all components required for linking are present on command line
ipo: remark #11000: performing multi-file optimizations
ipo-1: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_1758441.obj
ipo-1: error #11023: Not all components required for linking are present on command line
ipo-1: remark #11004: starting multi-object compilation
ipo-2: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_1758442.obj
ipo-2: error #11023: Not all components required for linking are present on command line
ipo-2: remark #11004: starting multi-object compilation
ipo-2: remark #11006: generating object file C:\Users\asus\AppData\Local\Temp\ipo_1758442.obj
ipo-1: remark #11006: generating object file C:\Users\asus\AppData\Local\Temp\ipo_1758441.obj
ipo-3: warning #11021: unresolved CLUSTER_SPARSE_SOLVER_D
        Referenced in C:\Users\asus\AppData\Local\Temp\ipo_1758443.obj
ipo-3: error #11023: Not all components required for linking are present on command line
ipo-3: remark #11004: starting multi-object compilation
ipo-3: remark #11006: generating object file C:\Users\asus\AppData\Local\Temp\ipo_1758443.obj
Microsoft (R) Incremental Linker Version 11.00.50727.1
Copyright (C) Microsoft Corporation.  All rights reserved.
[result of fds6.6.0.txt](https://github.com/firemodels/fds/files/2365453/result.of.fds6.6.0.txt)
[result of fds  master.txt](https://github.com/firemodels/fds/files/2365454/result.of.fds.master.txt)

error LNK2019: unresolved external symbol MAIN__ referenced in function main
fatal error LNK1120

**Comment by mcgratta** [comment]
Why are you not using Intel Fortran 2018?

**Comment by marcosvanella** [comment]
Hi Carl, check the version of your intel MKL library. Some modules of FDS use the cluster sparse solver from this library, first released on MKL 11.2. See this documentation:

https://software.intel.com/en-us/articles/intel-math-kernel-library-parallel-direct-sparse-solver-for-clusters

If you have an older version you should be able to download for free and install the latest intel performance libs here:

https://software.seek.intel.com/performance-libraries

**Comment by CarlMarcus** [comment]
I tried the solutions offered by contributors above, they worked well, thank you.
