### ISSUE TITLE
Feature request: TGA output to include rates of each solid phase reaction

### ISSUE THREAD

**Issue by arinta-paavola** [firemodels/fds#6831]
I am requesting that the TGA output file (when TGA_ANALYSIS = .TRUE.) would include rates of each individual solid phase reaction in addition to the total MLR, when running a TGA simulation for a multicomponent fuel. This would be helpful as I am now running TGA simulations of a fuel consisting of several components, each decomposing through two competing reactions.

Thanks in advance!

**Comment by mcgratta** [comment]
I added the component output. Please check that it works.

**Comment by sbenkorichi** [comment]
I've checked it on my end and the sum up of individual components match the total of mlr. 

Total | sum of indiv
-- | --
0.0788484999 | 0.078848499



![image](https://user-images.githubusercontent.com/20113030/45929235-8a144400-bf46-11e8-9365-57136b8e5274.png)

![image](https://user-images.githubusercontent.com/20113030/45929440-a4035600-bf49-11e8-9c0d-02ac63d22e3d.png)
