### ISSUE TITLE
Mass Balance issue

### ISSUE THREAD

**Issue by delcours** [firemodels/fds#6841]
Hi,

We ran into a possible mass balance error , we reduced the case to the most simple example linked in attachement.
[Mass.txt](https://github.com/firemodels/fds/files/2410301/Mass.txt)

In this example, two identical rooms are separated by an inert OBST. In one room, we have a hot surface (TMP_front=1000).

Running the case for 100 s on FDS 6.6, the mass balance of AIR shows a deviation between the two rooms, while the sum remains constant. Same results were obtained with FDS 6.7.

Best regards,

Simon Delcour

**Comment by drjfloyd** [comment]
See section 9.1 in the User's Guide.  In this case you likely need to tighten the VELOCITY_TOLERANCE and increase the MAX_PRESSURE_ITERATIONS. Try doing that and report back if that resolves the issue.

**Comment by delcours** [comment]
Hello, I tried VELOCITY_TOLERANCE values of 0.001 and 0.00001, associated with MAX_PRESSURE_ITERATIONS = 1000. No change, except the longer computation time.

**Comment by drjfloyd** [comment]
@mcgratta @rmcdermo 

Any thoughts on this one?  Mass is somehow moving from the hot side to the cold side.  Tightening down the VELOCITY_TOLERANCE a lot doesn't have any appreciable affect on the shift in mass.  NORMAL VELOCITY is showing zero wall normal velocity.

**Comment by rmcdermo** [comment]
I'll look at it.

**Comment by mcgratta** [comment]
No `ZONE`

**Comment by drjfloyd** [comment]
Since they are the same ZONE, they will have the same background pressure so temperature will rise on the unheated size, but why would RHO be changing?

**Comment by mcgratta** [comment]
```
&ZONE   XB = 0,0.4,0,1,0,1 /
&ZONE   XB = 0.6,1,0,1,0,1 /
```

**Comment by mcgratta** [comment]
With no `ZONE` lines, the wall becomes porous and air flows through. Overall mass is conserved.

**Comment by drjfloyd** [comment]
I expected that tightening VELOCITY_TOLERANCE would reduce that flow.

**Comment by mcgratta** [comment]
If the background pressure rises throughout the whole domain, PV=nRT dictates everything. If we were to create small openings and thereby thwart the background pressure rise, then we could tighten things down to achieve the pressure difference, but it would require alot of tightening.

**Comment by delcours** [comment]
With the ZONE lines as Kevin suggested, there is no variation of mass on either side of the wall, and no pressure rise as well.
