### ISSUE TITLE
REQ4 timeout with HT3D at mesh boundary

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6842]
@mcgratta This case used to work.  Can you see if something has changed with MPI exchanges.  When I or Marcos run this we get REQ4 time out.  Here is the input file:
[NFRL-TEST7-DX01.fds.txt](https://github.com/firemodels/fds/files/2412576/NFRL-TEST7-DX01.fds.txt)

The log files I have so far are in
```
/home4/rmcdermo/Work/NFRL_Commissioning/TEST7_RAMP/
```  

The case seems to run with this mesh arrangement:
```
&MULT ID='m1', DX=0.4,DY=0.4,DZ=0.6, I_UPPER=5,J_UPPER=2,K_UPPER=3/ 72 meshes
&MESH IJK=40,40,60, XB=-1.2,-0.8,-0.6,-0.2,0.0,.6, MULT_ID='m1'/
```

The warnings *should* be fine.  This is only meant to alert users if they have thin obstructions with HT3D, which is not yet working.  This shows up when the OBST abuts a mesh boundary.  This may indeed be what is causing the problem here, but again it used to work.  If you have any ideas let us know.

**Comment by rmcdermo** [comment]
There is definitely something amiss at mesh boundaries, but this may be on my side.  The attached simple case does not give the correct solution when the cold SURF is at a mesh boundary.  The temperature slice should decrease linearly from 200 C to 20 C.  The way this input file is set up right now it looks like the cold boundary is treated as adiabatic.

[test_2mesh.fds.txt](https://github.com/firemodels/fds/files/2412704/test_2mesh.fds.txt)

**Comment by rmcdermo** [comment]
I'm going to try latest source to see if that helps anything. PR #6843

**Comment by rmcdermo** [comment]
This input file is coarsened a bit.  It gets off the ground with the serial code (fds_dv) running in the foreground.  If you launch it via qfds with MPI, then it hangs with REQ4 timeout.
[test.fds.txt](https://github.com/firemodels/fds/files/2412951/test.fds.txt)

**Comment by mcgratta** [comment]
Should work now. Try it and then close.

**Comment by rmcdermo** [comment]
Works.  Thanks!
