### ISSUE TITLE
Big difference between results in version 6.6 and 6.7

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/fds#6855]
The case attached in an office floor fire. I ran the same model (with the same mesh settings) in version 6.6 and 6.7 and got completely different results.  The results in version 6.7 looks reasonable.  However, the results in version 6.6 looks unphysical judging by the smoke view and the visibility slice at 2m. 

Any idea what is causing this difference? 

![image](https://user-images.githubusercontent.com/38315126/46215144-86acfe00-c334-11e8-9257-10f2644d2a53.png)

[TEST_CASE.zip](https://github.com/firemodels/fds/files/2428608/TEST_CASE.zip)

**Comment by sbenkorichi** [comment]
here is the reason why 
https://github.com/firemodels/fds/issues/6484

**Comment by adnannweilati** [comment]
So i understand from the post that this bug was fixed in version 6.7. Is that right?

**Comment by sbenkorichi** [comment]
Yes, this has been in previous releases and was fixed in 6.7. That's why it's recommended to use the latest release. 
If this has answered your question, then close this ticket.
Thanks

**Comment by adnannweilati** [comment]
Perfect thanks!
