### ISSUE TITLE
How to Build FDS+EVAC_Guide

### ISSUE THREAD

**Issue by godisreal** [firemodels/fds#6857]
I tried to build the guide and got the PDF file, but all the figures were missing.  
Does anyone know how to solve the problem?  Thank you very much.

**Comment by tkorhon1** [comment]
Sorry for a late answer. No, there is not a way to build the FDS+Evac guide.
And I should update the LaTeX .tex file in the GitHub. I have not remembered to do this.
The latest PDF version is here:
http://virtual.vtt.fi/virtual/proj6/fdsevac/documents/FDS+EVAC_Guide.pdf

I draw most of the figures using Excel and the verification and validation cases
are not in the Github. So, things are not so nicely done as for the FDS guides.
I do not have a fully automated script that runs the V&V cases either.

What I could do that things would be a little bit better (I add these to my TODO list):

1) I should add my verification cases to the Verification/Evacuation directory in Github
and validation cases in Validation/Evacuation directory (the .fds files)

2) I should update the .tex file of the FDS+Evac UG in Github

3) I should put to the Manuals/FDS_Evacuation_Guide/FIGURES those figures
that are not updated too often. Verification figures and most validation figures
are updated every now and then, when I rerun my V&V cases. Some MC-type
figures I do not update frequenty and these I could place in Github (I do not
rerun the parametric studies of the effects of the social force parameters nor
the ones where rank correlation coefficients etc are calculated usually. I have
not changed the default social force parameters, so these are still valid.)

TimoK

**Comment by tkorhon1** [comment]
Now I have updated the .tex file. I added also FIGURES directory, where "static" or "semi-static" figures are. The figures that are changing every time I do my V&V cases are not there. I should add the .fds files to the and validation folders (EVACUATION subdirectories) and also some smv-scripts etc to make the easiest figures. Some figures are hard to make, because I use Excel, do the histograms there etc.

**Comment by mcgratta** [comment]
Is this issue still open?

**Comment by godisreal** [comment]
Probably Timo will take a look when he have time.  Now the major issue is not how to build the guide, but how to fix the problems in the guide, both literally and technically.  
For example, British spelling "**colour**" is used through EVAC UG while the **COLOR_METHOD** is there in namelist of PERS.  So it is better to use a consistent spelling, isn't it?

**Comment by mcgratta** [comment]
I'm going to close this issue. Changes like colour to color can easily be made by git pull requests.
