### ISSUE TITLE
HRR doesn't match with prescribed HRR

### ISSUE THREAD

**Issue by Manuelbarrosd** [firemodels/fds#6858]
After certain time of simulation the HRR doesn't match with the prescribed HRR.  The burning rate is correct, however the HRR  does not reflect the heat of combustion times the burning rate  aperiod of time. Attached my input file. Thanks
[fire31.txt](https://github.com/firemodels/fds/files/2443240/fire31.txt)

**Comment by drjfloyd** [comment]
You have a 1m^2 fire that peaks at 8 MW that is 1 m away from an open vent in a room with a ceiling height of 3 m. Heskestad's flame height correlation gives a 7 m flame height for an 8 MW fire.  Once your fire ramp gets large enough that the flame height is longer than the distance from the fire to the open vent, you will have flames (i.e. unburned fuel) leaving the domain.

**Comment by Manuelbarrosd** [comment]
Thanks very much
