### ISSUE TITLE
Handle HT3D OBST abutting MESH boundary

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#6886]
In this case, the wall temperature device reports 20 C when the mesh boundary is set to coincide with the OBST.  If the mesh boundary is moved, then the surface temperature is reported correctly.  This is a complicated issue related to whether MESH 1 knows about the OB in MESH 2.

[test_bndf.fds.txt](https://github.com/firemodels/fds/files/2473658/test_bndf.fds.txt)

@mcgratta When you get time, let's talk about how we can make this work.  At present, we cannot allow HT3D OBST to abut a mesh boundary, and I think that will be difficult to avoid in practice.

**Comment by mcgratta** [comment]
Test to see that you can get the value of `OBST_INDEX_C` in the neighboring mesh.

**Comment by mcgratta** [comment]
Look at the change to `wall.f90`. It is just a comment showing you how to access the gas temperature and heat flux at the boundary of an HT3D obstruction that abuts a mesh boundary.
