### ISSUE TITLE
Radiative Heat Flux Gas in a slice file

### ISSUE THREAD

**Issue by elmadrab** [firemodels/fds#6892]
Hello,

Is it possible to add a new output of the Radiative Heat Flux Gas in a slice file ?

It would be very helpful for our studies. 

Best regards

Mohamed.

**Comment by mcgratta** [comment]
No, this would overly complicate an already complicated output quantity. `'RADIATIVE HEAT FLUX GAS'` is a special output quantity that uses a Lagrangian particle to integrate all angles of the radiation intensity dotted with the `ORIENTATION` vector. To position a particle for each slice file cell, in particular when the slice crosses mesh boundaries, and then allow arbitrary orientation would just be too much code.

**Comment by elmadrab** [comment]
Dear Kevin,
Thank you for your answer.
I have a doubt about the quantity 'RADIATIVE HEAT FLUX GAS', does it give the incident heat flux in the opposite orientation of the vector ?

Because I use it to calculate the incident heat flux received  by occupants in a buildings, usually the device is located at 2 meter above the ground level : 
&DEVC ID='flux', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=..., ORIENTATION=0,0,1 /

**Comment by mcgratta** [comment]
You do not have a DOUBT; you have a QUESTION.

The `ORIENTATION` vector points towards the source of radiation. In your case, (0,0,1) points upwards.

**Comment by elmadrab** [comment]
I'm sorry I misspoke.

Is this right ?
