### ISSUE TITLE
MLR_Fuel is over-rated 

### ISSUE THREAD

**Issue by LahnaACH** [firemodels/fds#6902]
Hello,

I performed a pool fire simulation on heptane in a container of diameter (d = 23 cm) in an open environment, to get its MLR in comparison with previous documented results.
The results of the values of MLR_feul came of the order (1e100) (FDS 6.6).
I believe there is an error, but I still can't find it.
Could you please advise. 

[Heptane_23cm.zip](https://github.com/firemodels/fds/files/2484057/Heptane_23cm.zip)

**Comment by mcgratta** [comment]
I do not see the very high values of MLR in the latest version of FDS. I suggest you upgrade to the latest version and if the problem persists, start a new issue.
