### ISSUE TITLE
Severe (157) Access Violation

### ISSUE THREAD

**Issue by ewatkins94** [firemodels/fds#6905]
I am running a pyrolysis model in 6.6 and my model keeps crashing with either a numerical instability or "forrtl: severe (157): Program Exception - access violation" 

[belt.fds.txt](https://github.com/firemodels/fds/files/2487534/belt.fds.txt)

**Comment by mcgratta** [comment]
I am trying to run the case but the start-up is taking a long time. I suggest you do the following:

1. Upgrade to 6.7.0
2. Create a smaller case to test your pyrolysis model.
3. Submit the case if you still have trouble.

**Comment by ewatkins94** [comment]
Will do, thanks.

**Comment by mcgratta** [comment]
The case is running for me. When does it fail for you?

**Comment by drjfloyd** [comment]
&REAC ID			= 'RUBBER'
      C				= 88.46
      H				= 10.29
      O				= 0.71 
      SOOT_YIELD		= 0.15
      CO_YIELD			= 0.082
      HEAT_OF_COMBUSTION	= 42400 /

This is a very large molecular weight fuel.  See the discussion in 15.1.3 of the user's guide (under enthalpy). This could be causing a problem.  I suggest normalizing your fuel to keep the molecular weight below 60 or 70.  As a note, this fuel has 1 hydrogen atom for every 8 carbon atoms.  If this is meant to be a rubber polymer, most polymers are something close to 2 hydrogen per carbon.

**Comment by ewatkins94** [comment]
Yes, it is supposed to be a SBR rubber. I will double check the composition, thanks for the assistance. The case failed around 120 seconds into the model run time for me.

**Comment by mcgratta** [comment]
Upgrade to the latest version of FDS and change the composition of rubber. If you still have trouble, start a new issue.
