### ISSUE TITLE
Mpiexec noerror but error

### ISSUE THREAD

**Issue by Behnam-Nouri** [firemodels/fds#6937]
Hi,

the last time i used FDS and MPI was 2016 and there it worked.
I updated to 6.7 and i get some problems. I removed all previous MPI and FDS installation.
However i get this.

> C:\Program Files\firemodels\FDS6\bin>mpiexec -n 2 fds
[unset]: Error reading initack on 444
Error on readline:: No error
[unset]: write_line error; fd=444 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=444 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=444 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=444 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error
[unset]: Error reading initack on 468
Error on readline:: No error
[unset]: write_line error; fd=468 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : No error
[unset]: Unable to write to PMI_fd
[unset]: write_line error; fd=468 buf=:cmd=barrier_in
:
system msg for write_line failure : No error
[unset]: write_line error; fd=468 buf=:cmd=get_ranks2hosts
:
system msg for write_line failure : No error
[unset]: expecting cmd="put_ranks2hosts", got cmd=""
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(805): fail failed
MPID_Init(1743)......: channel initialization failed
MPID_Init(2144)......: PMI_Init returned -1
[unset]: write_line error; fd=468 buf=:cmd=abort exitcode=68204815
:
system msg for write_line failure : No error>

**Comment by Behnam-Nouri** [comment]
It doesnt work with any of my working minimal examples..
I have a windows 8 machine with Xeon CPU.


C:\Program Files\firemodels\FDS6\bin>mpiexec -info
HYDRA build details:
    Version:                                 2018 Update 2
    Release Date:                            20180125
    Process Manager:                         pmi
    Bootstrap servers available:             service ssh fork
    Resource management kernels available:   user slurm pbs hpc
    Checkpointing libraries available:        blcr
    Demux engines available:                 select

C:\Program Files\firemodels\FDS6\bin>mpiexec -validate
SUCCESS

C:\Program Files\firemodels\FDS6\bin>

**Comment by mcgratta** [comment]
Try adding `-localonly` to the `mpiexec` command line.

**Comment by Behnam-Nouri** [comment]
C:\Program Files\firemodels\FDS6\bin>mpiexec -localonly -n 2 test_mpi
[unset]: Error reading initack on 468
Error on readline:: No error
[unset]: write_line error; fd=468 buf=:cmd=init pmi_version=1 pmi_subversion=1
:+1: 
and so on like the other error.

**Comment by sbenkorichi** [comment]
It's been some time now since I've submitted a ticket to Intel regarding this issue, but I haven't heard of them up to date. 
You can follow it [here](https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/784088)

**Comment by mcgratta** [comment]
The only thing I can suggest is to uninstall FDS, check for and kill any hydra services running in the task manager under Services, and then reinstall and try again. We have been having similar problems here as well.

**Comment by Behnam-Nouri** [comment]
Hi, after deleting all mpich entries in regedit. And killing the hydra service and deleting and reinstalling the whole package it works now.
Seems to be an error with an old MPICH installation.  Maybe this should be included in the next version installer. Check old MPICH installations.

**Comment by mcgratta** [comment]
Yes, it seems to be difficult to untangle these various MPI communicators.
