### ISSUE TITLE
Differences between Data from FDS 6.6.0 and FDS 5.5.3

### ISSUE THREAD

**Issue by domme2507** [firemodels/fds#6951]
![c1-hrr_fds_kit-bft](https://user-images.githubusercontent.com/10529633/48055032-ebb70780-e1ae-11e8-816a-89f30498a841.png)
[C1_Extern.zip](https://github.com/firemodels/fds/files/2552454/C1_Extern.zip)

Hello,
I am member in a working group assessing solutions of different calculation models, zone model and field model (FDS) for calculations with focus on industrial buildings. The working group defined a few samples by setting the geometries, the fire load and mass loss rate. We have proceeded many FDS-calculations including Versions 6.6.0 and 5.5.3. The input files are built by different users. 
When comparing the solutions, especially for the heat release rate, we noticed enormous differences concerning the values, but also the fluctuation of the data points in version 6.6.0 (named KIT-HRR) solution. The first thing we did was to take out the extinction model, but the fluctuations were as high as before.
Please find the FDS input files and graph of compared heat release rates attached. Please let me know your ideas about what could cause the differences in the values we obtained.
Thanks in advance
Dominique Max

**Comment by rmcdermo** [comment]
These differences are not unexpected.  You can go through the list of [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes) to see what all the differences in the models.  Further, this question should be posed to the [discussion forum](https://groups.google.com/forum/?fromgroups#!forum/fds-smv).  All FDS releases are tested against a range of verification and validation tests, the latter having experimental data.  We proceed with changes to the model if the model results improve.
