### ISSUE TITLE
MPI command with Intel 18

### ISSUE THREAD

**Issue by sreihani** [firemodels/fds#6960]
Hello there,

I have compiled fds ( FDS6.7.0-801-g1cc73ae2e-master) with Intel 18 and MPI library. Here is what I am getting from the execute file:

WARNING:  This MPI implementation provides insufficient threading support.
 Reading input file ...

 Fire Dynamics Simulator

 Current Date     : November  7, 2018  23:13:58
 Revision         : FDS6.7.0-801-g1cc73ae2e-master
 Revision Date    : Tue Oct 30 13:49:08 2018 +0200
 Compiler         : Intel ifort 18.0.1
 Compilation Date : Nov 07, 2018 22:15:00

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      1

 MPI version: 3.1
 MPI library version: MVAPICH2 Version      :   2.3rc2
MVAPICH2 Release date : Mon Apr 30 22:00:00 EST 2018
MVAPICH2 Device       : ch3:mrail
MVAPICH2 configure    : CC=icc CFLAGS=-fpic CXX=icpc CXXFLAGS=-fpic F77=ifort FFLAGS=-fpic FC=ifort FCFLAGS=-fpic --with-mpe --with-pbs=/usr/local/torque-releases/torque-6.1.2-el7 --with-pbs-include=/usr/local/torque-releases/torque-6.1.2-el7/include --with-pbs-lib=/usr/local/torque-releases/torque-6.1.2-el7/lib --prefix=/usr/local/mpi/mvapich2/2.3rc2/intel/18.0
MVAPICH2 CC           : icc -fpic   -DNDEBUG -DNVALGRIND -O2
MVAPICH2 CXX          : icpc -fpic  -DNDEBUG -DNVALGRIND -O2
MVAPICH2 F77          : ifort -L/lib -L/lib -fpic  -O2
MVAPICH2 FC           : ifort -fpic  -O2

FDS fails to create the number of processes requested in mpirun command. I am wondering if there is potential solution for this issue. Thanks.

SR

**Comment by mcgratta** [comment]
Post the script or the command you used to launch the job.

**Comment by sreihani** [comment]
mpiexec -np 39 fds_impi_intel_linux_64 test_input.fds

**Comment by mcgratta** [comment]
I have never used MVAPICH. You could do simple things like
```
which mpiexec
```
to make sure that you are not using some other version of mpiexec. You could also try writing a simple `Hello World` program to test your implementation.

**Comment by saschagottfried** [comment]
[Run using Hydra (mpiexec) - MVAPICH 2.3 User Guide](http://mvapich.cse.ohio-state.edu/static/media/mvapich/mvapich2-2.3-userguide.html#x1-370005.2.2)

`mpiexec -n 39 fds_impi_intel_linux_64 test_input.fds`

**Comment by saschagottfried** [comment]
@sreihani 
Did you notice that you compiled FDS sources with a `make` build target configured to use Intel MPI? 

Possible implications
- the WARNING indicates no support for multi-threaded execution model (MPI / OpenMP)
- alternative pressure solvers have a dependency to Intel Math Kernel library (MKL) that is statically linked. If your executable is smaller than 100MB in size Intel MKL libraries were not linked.

**Comment by mcgratta** [comment]
I assume this issue is resolved. If not, open up a new issue.
