### ISSUE TITLE
Warning to catch pressure zones connected to OPEN

### ISSUE THREAD

**Issue by bmralph** [firemodels/fds#6966]
Hey team

As I understand it; separate pressure zones cannot be defined if the volume has an `OPEN` boundary condition. Should we be capturing this as a warning or error? Or am I missing something?

e.g. if a user creates two rooms connected by a leak, each as pressure zones but then has an `OPEN` window in each room. The user may be expecting the pressure zones to behave well and control the leak flow - but in fact, they're not

Cheers, BMR

**Comment by mcgratta** [comment]
There are cases where one might cover the OPEN boundary. The pressure zone is still in effect with the OPEN boundary, but the pressure just won't rise above ambient. Is there a case that acts bizarrely for you?

**Comment by bmralph** [comment]
Nothing specific at the moment. Just some simple test cases I'm looking at
whilst working on HVAC

As you've said there are valid cases where this would be usable - I can
close this issue for now until I have more time to look at it and make a
test case if applicable?

**Comment by mcgratta** [comment]
OK, let's close it until something arises.
