### ISSUE TITLE
Feature request: Introducing mm/min as a unit conversion?

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#6983]
Is it possible to add an option of **`mm/min`** unit (as we have for C<>F or ft<>m) ?

This unit is commonly referred in sprinkler studies. 

`MPUA` and `PARTICLE FLUX Z` (or X or Y) in  `SLCF `and `BNDF `files might be examples to use this unit conversion. 

 Thank you.

**Comment by rmcdermo** [comment]
Search for CONVERSION_FACTOR in the user guide.

**Comment by Er9y714** [comment]
I already worked around by using `CONVERSION_FACTOR` indeed.  

Thank you for the response.
