### ISSUE TITLE
GEOM crossing meshes at different refinement levels

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7002]
@marcosvanella Just putting this on the TO-DO list.  I just got this error running a case.  I think this is a typical situation a user will have and so need to have this capability.

```
SET_GC_CUTCELLS_3D Error: GEOM not allowed to cross meshes at different refinement levels.
```

**Comment by marcosvanella** [comment]
This is a test case to develop the capability to have cut-cells at different refinement levels next to a geometry. The main goal here is to define the face information and do the corresponding face averages such that fluxes match on one side and the other. 
Kevin, I add you here as I'll probably need your help with information exchange from omeshes and external cut-face computations. To keep the code similar to what is done with WALL_CELLs we probably need to add the gasphase cut-faces on mesh boundaries and work on them when INTERPOLATED_BC.
[cube_helium_withrefinement.fds.txt](https://github.com/firemodels/fds/files/5575935/cube_helium_withrefinement.fds.txt)

**Comment by mcgratta** [comment]
is this issue still relevant?

**Comment by marcosvanella** [comment]
No, I'll close. We added refinement capability.
