### ISSUE TITLE
Make SLICETYPE='INCLUDE_GEOM' default when GEOM is used

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7004]
@marcosvanella I'm running across things like this that need to get crossed off before we can release.  If we want to leave the possibility of the old version of SLCF around, let's change the flag.  Thanks.

**Comment by marcosvanella** [comment]
Let me look look at this.

**Comment by rmcdermo** [comment]
@marcosvanella Please close this out if it is done.
