### ISSUE TITLE
Failure due to slice ids greater than 17 characters

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/fds#7006]
It's only upon trying to debug this issue that I realised this might be an undocumented, but I frequently give my SLCFs an ID, which I can use from within Smokeview to choose the right slice. With 6.5.1 this works as expected, however, with 6.6.0 and 6.7.0 I get failures on slices with ids greater than 17 characters in length. The error is as follows

```sh
forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write
Image              PC                Routine            Line        Source
fds.exe            00007FF71139E507  Unknown               Unknown  Unknown
fds.exe            00007FF71135E4F6  Unknown               Unknown  Unknown
fds.exe            00007FF719297104  Unknown               Unknown  Unknown
fds.exe            00007FF718A8E21E  MAIN__                    336  main.f90
fds.exe            00007FF718A78632  Unknown               Unknown  Unknown
fds.exe            00007FF719387A80  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFBB1DC3034  Unknown               Unknown  Unknown
ntdll.dll          00007FFBB3071471  Unknown               Unknown  Unknown
```

Here is a test file to illustrate the issue:

```fortran
&HEAD CHID='slengthtest' /
&TIME T_END=10.0 /

&DUMP NFRAMES=100 /

&MESH ID='MainMesh' IJK=10,10,10 XB=0,1,0,1,0,1 /

! Fails - 18 character Id
&SLCF ID='aaaaaaaaaaaaaaaaax', QUANTITY='TEMPERATURE', PBX=0.5 /

! Succeeds - 17 character Id
&SLCF ID='aaaaaaaaaaaaaaaaa', QUANTITY='TEMPERATURE', PBX=0.5 /

&TAIL /
```

It works with 6.5.1, and fails with 6.6.0 and 6.7.0 (both Windows and Linux in all cases).

**Comment by JakeOShannessy** [comment]
It looks like the slice ids were implemented under issue #1415, although that is from the SVN days and doesn't add much info.

**Comment by marcosvanella** [comment]
Jake I could reproduce your error. Looks like we need to increase the size of one of the mesh string arrays used to define smokeview slices and other sms info.

**Comment by marcosvanella** [comment]
Jake, do an update from central repo and test the case.

**Comment by JakeOShannessy** [comment]
I was finally able to test it, and it seems fixed to me.
