### ISSUE TITLE
Issue Simulating Propane Fire

### ISSUE THREAD

**Issue by MrEgress** [firemodels/fds#7020]
Hello Everyone,

I am experiencing difficulty simulating a propane fire. I already defined the propane rection for the fire, the HRR, and the fire's orientation in the enclosure but somehow I cannot see the flames when I run SmokeView and the HRR is zero in the Excel file. Also, in the code, I have two VENT parameters: the first VENT parameter acts as inflow vent and injects fuel into the enclosure, and the second VENT parameter acts as inflow/outflow vent. 

I am not sure if I am missing some parameters in my code, so here is the code below and thanks in advance for helping me.

**Comment by rmcdermo** [comment]
This Issue Tracker is for bug reports.  Please submit your question to the [discussion forum](https://groups.google.com/forum/#!forum/fds-smv) and we will answer there.  Thanks.
