### ISSUE TITLE
Numerical Instability

### ISSUE THREAD

**Issue by mrRaj6** [firemodels/fds#7023]
[circular_burner.docx](https://github.com/firemodels/fds/files/2651743/circular_burner.docx)

when i run it the time step runs till 4 having same simulation time 0.09 sec and then stops
saying Numerical Instability

**Comment by mrRaj6** [comment]
please change .docx to .fds to view file in notepad

**Comment by rmcdermo** [comment]
The issue tracker is for bug reports.  You have not demonstrated a bug with a simple test case.  What is the INIT line supposed to do?  Your understanding of the code should be worked out in the discussion forum.
