### ISSUE TITLE
Remove Error message from GEOM boundary files on "Set-up only"

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7074]
@marcosvanella Just a reminder to not display this message on startup.  Gives the user the feeling something is wrong.  But I think the problem is just that when T_END=0 we do not write these files.

**Comment by rmcdermo** [comment]
Here is an example:

`Error: The file  sphere_propane_deposition_0048_01.gbf does not exist`

**Comment by gforney** [comment]
I removed these messages from smokeview
