### ISSUE TITLE
Sprinkler Link Temperature: INITIAL_TEMPERATURE has no effect

### ISSUE THREAD

**Issue by schroederbenjamin** [firemodels/fds#7076]
Dear developers,

I have encountered an issue when working with sprinkler link temperatures. 

Let's assume a cold room with -25 °C which is placed in regular ambient conditions (TMPA = 20 °C). For monitoring a sprinkler link temperature DEVC inside the cold room, I want to take into account the low  initial temperature of the link. So I definie INITIAL_TEMPERATURE=-25.

However, during the postprocessing, I took notice that the initial link temperature equals TMPA although I have set INITIAL_TEMPERATURE=-25.

I have reduced my problem to a simple base_case which is attached. In order to visualise the problem, I also have prepared a small plot with three devices:

- LINK_DEVC (sprinkler link temperature one cell below the ceiling of the room)
- TEMP_DEVC (gas temperature one cell below the ceiling of the room, for comparison)
- TMPA_DEVC (ambient temperature outside of the room)

**Plot:**
![initial_temp_devc](https://user-images.githubusercontent.com/46043299/50330338-1f4db700-04fb-11e9-8a64-6db35a41a140.png)

**Slice:**
![initial_temp_0021](https://user-images.githubusercontent.com/46043299/50330317-07763300-04fb-11e9-80cb-3f4ccf8af4b9.png)

**FDS-file:**
[initial_temp.zip](https://github.com/firemodels/fds/files/2701905/initial_temp.zip)

Thank you very much and merry Christmas!

Benjamin

**Comment by rmcdermo** [comment]
Thanks for the report.  We will take a look.  Cheers...

**Comment by mcgratta** [comment]
Simple explanation --- we don't allow the link temperature to drop below `TMPA`. This constraint has been around for a long time, and I don't really recall why we have it. Probably to prevent a spurious drop in temperature if the link gets wet. In any case, I'll work on fixing this. In the meantime, you have to reconfigure your case.
