### ISSUE TITLE
Visibility of mesh boundaries rendering HRRPUV

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7079]
I thought at one point we had dealt with this, but in the sphere_propane_deposition example here

`/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Verification/Aerosols/sphere_propane_deposition`

you can clearly see mesh boundaries.  This is probably again related to ghost cell values being sent to Smokeview. Here is a front on view

![screen shot 2018-12-21 at 12 53 09 pm](https://user-images.githubusercontent.com/4418497/50356393-c80e0d80-051f-11e9-8e47-e8fd919a53c3.png)

**Comment by mcgratta** [comment]
Give it a try and let me know.

**Comment by rmcdermo** [comment]
Nice.  Same view...

![screen shot 2018-12-21 at 4 06 44 pm](https://user-images.githubusercontent.com/4418497/50363632-76bf4780-053a-11e9-8060-85e5d2865ed5.png)
