### ISSUE TITLE
FDS page on NIST server

### ISSUE THREAD

**Issue by gsztar** [firemodels/fds#7098]
FDS page on NIST server doesn't work. What is a new correct address?

**Comment by sbenkorichi** [comment]
The web is down at the minute. You can however download the bundle from here 
https://github.com/firemodels/fds/releases/tag/FDS6.7.0

**Comment by drjfloyd** [comment]
NIST is part of the Dept of Commerce which is one of the agencies impacted by the partial US Gov't Shutdown. You can obtain release versions of FDS through the github webpage: https://github.com/firemodels/fds
