### ISSUE TITLE
SMV - orientation is lost when window header is double clicked for fullscreen

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#7100]
Continuing from the discussion topic:
https://groups.google.com/forum/#!topic/fds-smv/VCqdUYHo4Ps

 Screen recording of the issue:
[Screen Recording (03-01-2019 14-50-18).zip](https://github.com/firemodels/fds/files/2723924/Screen.Recording.03-01-2019.14-50-18.zip)

The SMV Window is made fullscreen by clicking on the fullscreen button. > Orientation is saved.
The SMV Window is made fullscreen by double clicking on the window header. > Orientation is lost.

SMV 6.7.1 

Thank you.

**Comment by gforney** [comment]
sorry, I'm not able to reproduce the problem .  on my windows 10 PC both ways of making the smokeview window full screen give the same result.  Upload your input file, iits a long shot but maybe there is something special about aspect ratio or something else about your case

**Comment by Er9y714** [comment]
It occurs regardless of the file in my pc. I tried on Win7 and Win10. Yet  I can share a sample file below:

Note: Did you try moving the window location of SMV after it runs? When you only go full screen, it does not occur. However, after SMV runs, if you change the location of the window on the screen, then go full screen, this occurs.

 
```
&HEAD CHID='a'/
&TIME T_END=60.0/
&MESH ID='MESHF-a-a-merged-a-d', IJK=4,6,26, XB=0.0,0.8,0.0,1.2,0.0,5.2/
&TAIL /
```

**Comment by gforney** [comment]
Let me know if the smokeview located at the link below fixes the problem
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
Thank you Glen. It is solved!

**Comment by gforney** [comment]
glad my fix worked.  this was tricky.  when you double click in the header/frame portion of the smokeview window, windows was sending both an event to smokeview's callback routines to resize the window and an event to move the window .  I added a hack so that smokeview ignores window move events if they occur less than 1 second after a resize event.
