### ISSUE TITLE
Problems with temperature at outlet

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#7106]
When I run the attached file I get areas with high temperatures (up to 2500°C) at the outlet of the suction. This effect is dependent on the tube length.

[suction.fds.txt](https://github.com/firemodels/fds/files/2745789/suction.fds.txt)

![temp](https://user-images.githubusercontent.com/27724706/50976191-a638f280-14ef-11e9-8dd5-447dc26dbc11.jpg)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
It's difficult to explain what is happening, but it is related to ensuring that the normal component of velocity remain zero at the surface of the thin walls. If you make your walls 1 cell thick, and if you remove the OPEN boundary at the ceiling, things work much better. I think that the thin wall bordering the `VENT` that is imposed on the OPEN ceiling is the cause of the problem. However, this is allowed, and if you set a very low `VELOCITY_TOLERANCE` and increase the `MAX_PRESSURE_ITERATIONS`, the problem lessens without having to change your geometry. I'll continue to look into this, but for the moment, you have two work-arounds.

**Comment by herbertTau** [comment]
If I make the wall 1 cell thick, it works without problems. But if I let the thickness of the lower edge of the wall at zero you can see the same effect (see attached file). It looks like the sharp edge of the wall is causing this problem. A change of VELOCITY_TOLERANCE and MAX_PRESSURE_ITERATIONS do not improve it.

![temp2](https://user-images.githubusercontent.com/27724706/51020044-9536c280-157d-11e9-9a4e-519e56ef7858.jpg)
[suction2.fds.txt](https://github.com/firemodels/fds/files/2748581/suction2.fds.txt)

**Comment by rmcdermo** [comment]
This looks like a time step issue.  Set CFL_VELOCITY_NORM=1 and CFL_MAX=.5
and VN_MAX=.5 and see if that helps.

**Comment by herbertTau** [comment]
It helps already if I only set the parameter CFL_VELOCITY_NORM to 1 or 2.

**Comment by herbertTau** [comment]
The problem does not occur even if you set SIMULATION_MODE to 'LES' resp. 'SVLES'

**Comment by rmcdermo** [comment]
Yes, LES sets CFL_VELOCITY_NORM=1 by default.  This is stated in latest
guides, maybe not yet released.
