### ISSUE TITLE
How to consider the auxiliary combustion of materials in Pyrosim model?

### ISSUE THREAD

**Issue by timberzhoujun** [firemodels/fds#7110]
We all know that models can be created by Pyrosim. I have a question that when I create the model which has timber columns, how can I consider the auxiliary combustion of timber. Since the fire happens, wood itself is a combustible material which may increase the speed of combustion.
I hopefully want to get your answer.

**Comment by rmcdermo** [comment]
Please post this question to the discussion forum.  The issue tracker is for bug reports.  Thanks.

https://groups.google.com/forum/#!forum/fds-smv
