### ISSUE TITLE
Local particle weighting on stretched grids

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#7112]
It appears that the particle weighting factor (PWT) is not entirely compatible with stretched meshes.

I am working on a case with fixed particles (simulating vegetation). I am only using one particle per cell, as any more would be redundant thanks to the weighting factor. 
However, this factor is calculated based on a global mass and volume for the group of particles (part.f90 line 926). Thus, it is the same for each individual particle regardless of the size of the containing cell. 

This leads to issues such as the fact that the volumetric drag increases for smaller cells if the weighting factor is not adjusted accordingly (part.f90 line 1890).

This can be seen in the simple example attached.
Toggling on the &TRNY/Z lines results in increased drag (seen as velocity damping) in the compressed regions of the grid, compared to the non-stretched case. I would expect the results of the two simulations to be essentially the same.

-Eric

[Input_PWT_example.txt](https://github.com/firemodels/fds/files/2765407/Input_PWT_example.txt)

**Comment by btrettel** [comment]
I'll take a look at this.

**Comment by mcgratta** [comment]
Good point. The correction is to multiply the particle weight `LP%PWT` by the relative shrinkage of the cell:
```
DX(I)*DY(J)*DZ(K)*RDXI*RDETA*RDZETA
```
where 
```
RDXI = IBAR/(XF-XS)
```
Same for eta and zeta. `IBAR` is the number of cells in the x direction, and `XF`, `XS` are the extents of the mesh in the x direction.

**Comment by mcgratta** [comment]
I committed the fix. Could you try it as soon as possible to make sure it works. I can't do a lot of testing on my laptop.

**Comment by ericvmueller** [comment]
Looks like it works on a few simple test cases I tried out.
Thanks!
-E

**Comment by mcgratta** [comment]
Thanks for checking it out. Let me know if you see any other grid-stretch issues.
