### ISSUE TITLE
Flame escape

### ISSUE THREAD

**Issue by Tes55** [firemodels/fds#7126]
Hello, I have the following issue while using FDS. I have modeled a fire inside a closed room that has a door which lead to a corridor outside the room, and at the end of the corridor there is an open vent. When the model is run, the prescribed HRR does not reach the maximum value as shown in the FDS input. Also in Smokeview, quickly within the first minutes of the simulation, the flames depart from the fire source surface, travel inside the room and escape through the corridors to the open vents. I understand that this is ventilation-controlled fire so a ventilation issue, because all the available oxygen when depleted within the room, comes from the vents. However, the analysis results still look odd, is it possible that the flames can complete leave the source and "travel" so far away from the source? Thank you in advance for your help.

**Comment by rmcdermo** [comment]
Hello,
This is likely not a bug in the code, but rather you seeing the effects of the extinction model.  Please post your question to the discussion forum and we will answer there.

https://groups.google.com/forum/#!forum/fds-smv

**Comment by Tes55** [comment]
Will do, thanks for the quick response!
