### ISSUE TITLE
Different behavior for same geometry

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#7135]
![boundary_inert_testing_0001](https://user-images.githubusercontent.com/12799217/52003561-e4905480-2492-11e9-9629-1f430957f783.png)

The attached case has two meshes. One mesh is 1.2 x 1.2 x 1.2 and the other is 1x1x1.  The 1.2 mesh is lined with 0.1 m INERT OBST.  The 1 m mesh has no OBST or VENT defined. Both are initialized with a temperature of 1000.  The results are very different. If the h BNDF is loaded you can see that one face of the 1.2 mesh has a much different starting value for h. 

[Boundary Inert Testing.txt](https://github.com/firemodels/fds/files/2813929/Boundary.Inert.Testing.txt)

**Comment by MSalisbury** [comment]
I would recommend the first check is that the boundary surface is initialized correctly.   I dont think inert or the default surface is used.  There is 'zero' heat lose.  Oddly the mean temperature is about 50c hotter which is minor but i couldn't understand why.  

The boundary flux on the zmin is maybe another issue too.  Thanks so much for looking into this.

**Comment by drjfloyd** [comment]
There is no bug. A couple of things are happening. 

First you need to set separate pressure zones for each MESH.  Right now FDS is treating all the rooms as having the same pressure zone and one MESH has an OPEN boundary. Adding ZONE lines for the four rooms eliminates most but not all of the discrepancy.

Second is the pressure solver will have slight velocity errors at the OBST.  As a result, the pressure solution isn't identical between the 10x10x10 mesh and the 12x12x12 mesh. If the velocity tolerance is tightened so that there are more pressure iterations, the solutions will get closer.

**Comment by MSalisbury** [comment]
Perfect.  Thanks for clearing this up.

Ta

Matt.

Matt Salisbury
BEng CEng MIFireE MSFPE
fire engineer – director
Salisburyfire Ltd.

m. 07718 646 241
Email: matt@salisburyfire.co.uk<mailto:matt@salisburyfire.co.uk>
www.salisburyfire.co.uk<http://www.salisburyfire.co.uk/>
