### ISSUE TITLE
Typo UG

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#7153]
I remember reporting these but could not find it.

- Technical guide 8.2 notes that bin numbers are 7. Userguide 18.3.3 p205 footnote says 6 bins.
- Userguide p205 paragraph 2, first sentence is cut off.

Thank you.

**Comment by mcgratta** [comment]
I removed the exact value from the Tech Guide. The User's Guide is correct.

I do not see the first sentence which is cut off. Can you post a picture.

**Comment by Er9y714** [comment]
Here the highlighted part:
![image](https://user-images.githubusercontent.com/26166281/52486492-929aad80-2bbb-11e9-9da0-3c6f9e4a8319.png)

**Comment by sbenkorichi** [comment]
@Er9y714 
Refer to 204 
![image](https://user-images.githubusercontent.com/20113030/52486720-ce317980-2bb3-11e9-854b-273636f40494.png)

The droplet ....
It looks ok for me.

**Comment by Er9y714** [comment]
Oh, now I see. The text above belongs to Figure 18.2. 
Thank you.

**Comment by mcgratta** [comment]
Yes, this is one feature of the default LaTeX style that I do not like. There should be a different font or font size used for figure captions.

**Comment by rmcdermo** [comment]
We have the power!  I believe Nature uses Helvetica for captions.

**Comment by sbenkorichi** [comment]
usepackage[font={small,it}]{caption}

You can check its documentation here 
http://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/caption/caption-eng.pdf
