### ISSUE TITLE
Belt Fire

### ISSUE THREAD

**Issue by Manuelbarrosd** [firemodels/fds#7158]
Hi 

I am trying to simulate a fire spreading over a conveyor belt in a tunnel. I am using the kinetic parameters and material properties of SBR (synthetic rubber). Also, I set two virtual heater elements as the ignition source. I evidenced that after 600 s the flame instead of spreading over the belt surface, it increases in size very fast and doesn't look like right (attached the code and pictures before and after 600 s). 

Thanks 
[belt9.txt](https://github.com/firemodels/fds/files/2851399/belt9.txt)
![beltfire2](https://user-images.githubusercontent.com/43825503/52569006-3b285780-2dde-11e9-87de-d2a999bf8c88.PNG)

![beltfire](https://user-images.githubusercontent.com/43825503/52567938-7412fd00-2ddb-11e9-8367-80f5914e679d.PNG)

**Comment by rmcdermo** [comment]
You are in research territory.  This does not look like a bug in the code.  Please submit your question to the discussion forum.  Thanks.

https://pages.nist.gov/fds-smv/
