### ISSUE TITLE
Don’t run SMV 6.7.4 on OSX-Mojave: missing dylib

### ISSUE THREAD

**Issue by parsipal** [firemodels/fds#7161]
Good day to all, 
I’m trying to test FDS and SMV new version, but I have trouble to run Smokeview on macOS-Mojave (10.14.3).
Here the output:
$ smv circular_burner.smv
dyld: Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /Applications/FDS/FDS6/bin/smokeview
  Reason: image not found

Instead, FDS runs. 
Here the outoput:
$ fds
Reading input file ...

 Fire Dynamics Simulator

 Current Date     : February 12, 2019  11:35:45
 Revision         : FDS6.7.1-0-g14cc738f9-master
 Revision Date    : Mon Feb 4 12:26:25 2019 -0500
 Compiler         : Intel ifort 19.0.1.144
 Compilation Date : Feb 04, 2019  13:41:34

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Open MPI v3.1.2, package: Open MPI gforney@floga.el.nist.gov Distribution, ident: 3.1.2, repo rev: v3.1.2, Aug 22, 2018

The previous SMV ver.6.7.2 runs well.
Here the output:
$ smv
Smokeview  SMV6.7.2-0-g27edf2123 - Dec 20 2018

Revision         : SMV6.7.2-0-g27edf2123
Revision Date    : Tue Dec 18 17:22:39 2018 -0500
Compilation Date : Dec 20 2018 14:45:28
Compiler         : Intel C/C++ 19.0.0.117
Platform         : OSX64

 How to install missing dylib?
Thank you for help
Gio

**Comment by rmcdermo** [comment]
None of use have Mojave, so it is hard to test.  @marcosvanella do you have any ideas.  I was thinking that Xcode on his new machine needed upgrade.

**Comment by gforney** [comment]
We're looking into this

**Comment by gforney** [comment]
I may be wrong but didn't think he needed xcode unless he was building
smokeview. Rick has Mojave have asked him to test.

**Comment by parsipal** [comment]
I give you another hint: two days ago i tried to update smv 6.7.2 to 6.7.3 and 6.74 (on fds 6.7.0 directory).
I had the same error message.
I hope it can help you.
Gio.

**Comment by gforney** [comment]
I was linking to some glib libraries when I didn't need to.  I took this out. Try smokeview posted here.

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by parsipal** [comment]
It WORKS!

$ smv
Smokeview  Test(SMV6.7.4-3-g0381dfc51) - Feb 12 2019 - 09:08:02
Version          : Test
Revision         : SMV6.7.4-3-g0381dfc51
Revision Date    : Tue Feb 12 09:03:40 2019 -0500
Compilation Date : Feb 12 2019 09:08:02
Compiler         : Intel C/C++ 19.0.1.144
Platform         : OSX64

Thankyou.
Gio

**Comment by marcosvanella** [comment]
I'm making a VM on my iMac with Mojave to test this problem and for future needs.
Gio, if you see anything else out of the ordinary in Mojave let us know.

**Comment by parsipal** [comment]
I will.
Thank you.

**Comment by gforney** [comment]
good (responding to your message saying it works) - I'll put out a new release.
