### ISSUE TITLE
RADIATIVE HEAT FLUX GAS does not work with POINTS and TIME_HISTORY

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#7163]
This simple case does not run when TIME_HISTORY=.TRUE.

&HEAD CHID='rhf'/
&MESH XB=0,1,0,1,0,1,IJK=10,10,10/

&DEVC XB=0.45,0.45,0.45,0.45,0.05,0.95,POINTS=10,QUANTITY='RADIATIVE HEAT FLUX GAS',ORIENTATION=-1,0,0,ID='HF',TIME_HISTORY=.TRUE./

**Comment by mcgratta** [comment]
Must be something about RAD HEAT FLUX GAS. It is a unique device that implicitly uses INITs.

**Comment by mcgratta** [comment]
I fixed it for the simple case it. Try it for something bigger.

**Comment by drjfloyd** [comment]
Tried it on a case with two DEVC using POINTS and did the four permutations of TIME_HISTORY.  Fix works.
