### ISSUE TITLE
Throw an error when MPI process exceeds the number of Meshes

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#7188]
Hi Kevin,

When you have some time, could you please look at this.

When I run the lines below as :` mpiexec -np 6 fds junk.fds` , I receive this error (which is expected): 
`ERROR: The number of MPI processes, 6, exceeds the number of meshes, 5 (CHID: junk)`
```
&HEAD CHID='junk'/
MESH ID='MESH0', IJK=10,10,10, XB=0,1,0,1,0,1, MPI_PROCESS=0/
&MESH ID='MESH1', IJK=10,10,10, XB=0,1,0,1,1,2, MPI_PROCESS=1/
&MESH ID='MESH2', IJK=10,10,10, XB=0,1,0,1,2,3, MPI_PROCESS=2/
&MESH ID='MESH3', IJK=10,10,10, XB=0,1,0,1,3,4, MPI_PROCESS=3/
&MESH ID='MESH4', IJK=10,10,10, XB=0,1,0,1,4,5, MPI_PROCESS=4/
&TAIL /
```
But, when I try to combine two meshes, like below, in one MPI_PROCESS, it gets stuck forever. 
```
&HEAD CHID='junk'/
&MESH ID='MESH0', IJK=10,10,10, XB=0,1,0,1,0,1, MPI_PROCESS=0/
&MESH ID='MESH1', IJK=10,10,10, XB=0,1,0,1,1,2, MPI_PROCESS=1/
&MESH ID='MESH2', IJK=10,10,10, XB=0,1,0,1,2,3, MPI_PROCESS=2/
&MESH ID='MESH3', IJK=10,10,10, XB=0,1,0,1,3,4, MPI_PROCESS=3/
&MESH ID='MESH4', IJK=10,10,10, XB=0,1,0,1,4,5, MPI_PROCESS=3/
&TAIL /
```
And the output I get is : 
```
 $ mpiexec -np 5 fds junk.fds
 Reading input file ...
```
The problem is when I run this job through a scheduler, when doing `qstat -a` it shows to be running. Smokeview appears, but only as a setup. 

Is there a possibility where you could add an `Error Message` when the number of processes are higher than what's in the input file to throw an error, because sometimes I run some jobs and later I find they actually didn't run due to this.

Thanks !

**Comment by singlewithguitar** [comment]
Would you like to call me and explain in detail 4174256731
Kevin

**Comment by mcgratta** [comment]
OK, will do.

**Comment by mcgratta** [comment]
OK, this should do it. Test it and close the issue if it works.

**Comment by sbenkorichi** [comment]
Thanks, it works now. 
```
Reading input file ...

ERROR: Too many MPI processes have been assigned to this job (CHID: junk)

STOP: FDS was improperly set-up (CHID: junk)
```
