### ISSUE TITLE
Installation problem of FDS 6.7.1 on windows 7

### ISSUE THREAD

**Issue by nowitzz** [firemodels/fds#7191]
After the command console pop out, he ask me to type yes/no/quit.
No matter what I type, " ''tasklist' is not regonized as an internal or external command" is replied.

Can someone help me out plz.

**Comment by gforney** [comment]
type help in a command shell window.  do you see the tasklist appliction (see attached for what is on my computer)  If not, the link below gives info on installing tasklist.  

https://answers.microsoft.com/en-us/windows/forum/windows_xp-performance/how-and-where-do-i-download-and-run-missing/4f11c462-ca6a-4472-8713-b91c107441a5?auth=1 

[help.txt](https://github.com/firemodels/fds/files/2887515/help.txt)
