### ISSUE TITLE
Consistency between Z_0 on WIND and ROUGHNESS on SURF

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7193]
@mcgratta I think we need some machinery to make sure that if a user sets Z_0 on the WIND line then the ROUGHNESS for a terrain surface is set to 30*Z_0.

As a start, we might want to allow Z_0 as an input parameter on SURF.

The tricky part is that I could imagine that users would want to have different roughness parameters for, say, buildings and terrain.  Or different patches of terrain.  So, I don't think the solution is to set roughness for all surfs based on Z_0 on WIND.  But that might be our first step.

**Comment by mcgratta** [comment]
I looked into this, but there are all sorts of pitfalls that I envision. There is currently a section in the U Guide describing these two parameters. I'd like to leave it at that until we find a way to implement nicely.
