### ISSUE TITLE
problem in user's guide in fig 7.1

### ISSUE THREAD

**Issue by sinaparsa75** [firemodels/fds#7204]
we have an error in this code of user's guide book in fig 7.1, page 48 !!!

&HEAD CHID='helium_2d_isothermal',TITLE='Axisymmetric Helium Plume' /
&MESH IJK=72,1,144 XB=0.00,0.08,-0.001,0.001,0.00,0.16, CYLINDRICAL=.TRUE. /
&TIME T_END=5.0 /
&MISC DNS=.TRUE. /
&RADI RADIATION=.FALSE. /
&SPEC ID='HELIUM' /
&SURF ID='HELIUM', VEL=-0.673, MASS_FRACTION(1)=1.0, TAU_MF(1)=0.3 /
&VENT MB='XMAX' ,SURF_ID='OPEN' /
&VENT MB='ZMAX' ,SURF_ID='OPEN' /
&OBST XB= 0.0,0.036,-0.001,0.001,0.00,0.02, SURF_IDS='HELIUM','INERT','INERT' /
&DUMP PLOT3D_QUANTITY(1)='PRESSURE',PLOT3D_QUANTITY(5)='HELIUM' /
&SLCF PBY=0.000,QUANTITY='DENSITY', VECTOR=.TRUE. /
&SLCF PBY=0.000,QUANTITY='VOLUME FRACTION', SPEC_ID='HELIUM' /
&TAIL /

FDS cannot run this code.
Does anyone know what the problem is?

**Comment by drjfloyd** [comment]
The listing in the User's Guide is missing some inputs. See the actual example file in the Examples/Flowfields folder where you installed FDS.

**Comment by drjfloyd** [comment]
fixed guide
