### ISSUE TITLE
Large pressure variations with pressure zones and leakages with variations in height

### ISSUE THREAD

**Issue by AndrewCFD** [firemodels/fds#7206]
Hi
I recently noticed on a case where there appeared to be unusual pressure values within the room of fire origin.  In this case I was getting pressures in excess of 300 Pa at t=1.  After running several simple test cases I think I have a case that illustrates the issue.

The attached case has the following features:
•	A leakage applied to one wall
•	2 pressure zone between the room and external
•	A mesh with a different z value that is lower than the room (~-30m)

As can be seen by looking at the results, at t=1 pressure is ~300 Pa within the room despite there being a leakage rate and a pressure zone.

I have also tested the following combinations on the above case and all give sensible pressures:
•	Leakage rate only
•	Pressure zone only
•	Leakage and pressure zone combined but the lowest mesh cell in z is the same height as the room floor

It appears that when leakage and pressure zone functions are combined, if there is a large variation in z pressure gradients are created.  In addition, the difference in pressure seems to be very similar to P=rho*g*h.

I was also able to create a similarly high pressure if the model was built with z=0 at room level and a mesh protruding below z=0.

**Comment by AndrewCFD** [comment]
&HEAD CHID='case_1'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='case_1.ge1', COLUMN_DUMP_LIMIT=.TRUE., NFRAMES=10/

&MESH ID='fire mesh', IJK=72,120,24, XB=-8.1,-0.9,-12.4,-0.4,30.0,32.4/
&MESH ID='stair-top01', IJK=26,16,167, XB=-3.8,1.4,0.6,3.8,0.0,33.4/
&MESH ID='stair-top', IJK=26,16,233, XB=-3.8,1.4,0.6,3.8,33.4,80.0/

&ZONE ID='fire_unit', XB=-8.0,-1.1,-11.1,-2.3,30.0,32.4, LEAK_AREA(2)=0.1/
&ZONE ID='outer pressure', XB=-8.0,-0.9,-12.4,-11.25,30.0,32.75/

&SURF ID='Surface01',
      COLOR='WHITE',
      DEFAULT=.TRUE./
&SURF ID='leakage',
      RGB=127,221,255,
      LEAK_PATH=1,2/

&OBST ID='Obstruction', XB=-8.15,-7.95,-11.25,-2.1,30.0,32.4, COLOR='GRAY 60', BNDF_OBST=.FALSE., SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-1.1,-0.9,-11.25,-2.1,30.0,32.4, COLOR='GRAY 60', BNDF_OBST=.FALSE., SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-8.0,-1.1,-2.3,-2.1,30.0,32.4, COLOR='GRAY 60', BNDF_OBST=.FALSE., SURF_ID='INERT'/ 
&OBST ID='Glass', XB=-8.0,-1.1,-11.25,-11.0,30.0,32.4, RGB=153,255,255, TRANSPARENCY=0.498039, SURF_ID6='INERT','INERT','INERT','leakage','INERT','INERT'/ 

&SLCF QUANTITY='PRESSURE', PBZ=32.0/
&SLCF QUANTITY='BACKGROUND PRESSURE', PBZ=32.0/
&SLCF QUANTITY='BACKGROUND PRESSURE', PBY=1.8/
&SLCF QUANTITY='PRESSURE ZONE', PBZ=32.0/
&SLCF QUANTITY='PRESSURE', PBY=-1.5/
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBX=-2.5/

**Comment by mcgratta** [comment]
I'll take a look at it.

**Comment by mcgratta** [comment]
You should make sure that ZONE 1 and 2 both have the 'leakage' SURF somewhere within each. You only have it in ZONE 1. Also, your leak area of 0.1 is too big. That's not a leak; it's a hole. Try a smaller leak value, which should reduce spurious behavior.

**Comment by mcgratta** [comment]
Jason. Take a look at this case. The leak area is the size of a grid cell. There is some pressure oscillation between ZONEs 1 and 2. Would you expect that?
```
&HEAD CHID='case_2'/
&TIME T_END=10.0/

&MESH IJK=72,120,24, XB=-8.1,-0.9,-12.4,-0.4,30.0,32.4/
&MESH IJK=26,16,167, XB=-3.8,1.4,0.6,3.8,0.0,33.4/
&MESH IJK=26,16,233, XB=-3.8,1.4,0.6,3.8,33.4,80.0/

&ZONE XB=-8.0,-1.1,-9.0,-2.3,30.0,32.4, LEAK_AREA(2)=0.01/
&ZONE XB=-8.0,-0.9,-12.4,-12.0,30.0,32.4/

&SURF ID='leakage', LEAK_PATH=1,2/

&OBST XB=-8.1,-0.9,-11.25,-11.0,30.0,32.4, SURF_ID='leakage' /

&SLCF QUANTITY='PRESSURE', PBZ=32.0, CELL_CENTERED=.TRUE./
&SLCF QUANTITY='BACKGROUND PRESSURE', PBZ=32.0, CELL_CENTERED=.TRUE./
&SLCF QUANTITY='BACKGROUND PRESSURE', PBY=1.8, CELL_CENTERED=.TRUE./
&SLCF QUANTITY='PRESSURE ZONE', PBZ=32.0, CELL_CENTERED=.TRUE./
&SLCF QUANTITY='PRESSURE', PBY=-1.5, CELL_CENTERED=.TRUE./
&SLCF QUANTITY='PRESSURE', VECTOR=.TRUE., PBX=-2.5/

&TAIL /
```

**Comment by drjfloyd** [comment]
The oscillation is more than I would expect and it goes away if the tall meshes are removed. I'll look into it.

**Comment by AndrewCFD** [comment]
Even if i reduce the leakage size significantly (now 10cm2), there is still a large pressure variation with the tall mesh (~225Pa).  With the tall mesh removed, pressures are back down in the few Pa region.

**Comment by mcgratta** [comment]
Jason, can you write down exactly the equation for u (velocity) in the duct that represents the leak in the case called case_2.fds above. With and without the vertical shaft.

**Comment by drjfloyd** [comment]
The equation is the same in both cases. Eq 10.4 in the Technical Reference Guide with the loss set to 1, the length set to 0.1, the delta p_j term is 0.

Sorry, I've not had much time to dig into this since my last post.

**Comment by mcgratta** [comment]
The time step is different. For the case with the vertical shaft, the time step is about 0.02 s. Without the shaft, the time step is 0.1 s. But that doesn't help because you'd think the smaller time step would be more stable.

**Comment by mcgratta** [comment]
Is Delta z = 0 in both cases?

**Comment by drjfloyd** [comment]
It should be 0 in both. The localized leakage routine sets XYZ for the nodes to the same dummy value for both sides of the like.

**Comment by drjfloyd** [comment]
I've spent some more time with this case. I think this is just how the pressure zones were defined. There are really 4 zones in this geometry but only two were explicitly defined. The two tall stair meshes and a piece of the first mesh were not defined as part of a zone.  If I define four zones (see below), there are no oscillations. Without a zone for the remaining portion of the first mesh it looks like there was just some bad feedback developing with the velocity error at the walls.

&ZONE ID='stair',XB=-3.8,1.4,0.6,3.8,0,80/
&ZONE ID='fireinner',XB=-8.0,-1.1,-12.4,-11.,30.0,32.4/
&ZONE ID='firemiddle',XB=-8.0,-1.1,-10,-3,30.0,32.4,LEAK_AREA(1)=0.1/
&ZONE ID='fireouter',XB=-8.0,-1.1,-2,-1,30.0,32.4/

**Comment by mcgratta** [comment]
AndrewCFD -- does this solve your problem?
