### ISSUE TITLE
Requesting a sample FDS input file for pyrolysis model in a room fire

### ISSUE THREAD

**Issue by basuds0817** [firemodels/fds#7215]
Hello,
I am a new user of FDS.
I am looking for a sample FDS input file for pyrolysis model in a room fire with wall burner.
It would be very helpful if I can get one.
Thanks,
Debashis Basu

**Comment by rmcdermo** [comment]
Issues is for bug reports.

Please post your question to the Discussion Forum.

https://groups.google.com/forum/#!forum/fds-smv
