### ISSUE TITLE
Single mesh is stretched even when TRNZ_ID not defined for it.

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#7227]
@rmcdermo here is the test case that shows this:

&HEAD CHID='test' /
&MESH ID='MyMEsh', IJK=32,32,32, XB=-0.5,0.5,-0.5,.5,1,2, / ! TRNZ_ID='MY TRANSFORM'
&MISC SIMULATION_MODE='LES' /
&TIME T_END=0.01 /
&VENT PBZ=2., SURF_ID='OPEN' /

&TRNZ ID='MY TRANSFORM', CC=    1.055555555556, PC=    1.025000000000 /
&TRNZ ID='MY TRANSFORM', CC=    1.111111111111, PC=    1.050000000000 /
&TRNZ ID='MY TRANSFORM', CC=    1.166666666667, PC=    1.075000000000 /
&TRNZ ID='MY TRANSFORM', CC=    1.222222222222, PC=    1.100000000000 /
&TRNZ ID='MY TRANSFORM', CC=    1.277777777778, PC=    1.127976612234 /
&TRNZ ID='MY TRANSFORM', CC=    1.333333333333, PC=    1.159284245516 /
&TRNZ ID='MY TRANSFORM', CC=    1.388888888889, PC=    1.194319506169 /
&TRNZ ID='MY TRANSFORM', CC=    1.444444444444, PC=    1.233526222239 /
&TRNZ ID='MY TRANSFORM', CC=    1.500000000000, PC=    1.277401065938 /
&TRNZ ID='MY TRANSFORM', CC=    1.555555555556, PC=    1.326499845497 /
&TRNZ ID='MY TRANSFORM', CC=    1.611111111111, PC=    1.381444546171 /
&TRNZ ID='MY TRANSFORM', CC=    1.666666666667, PC=    1.442931209573 /
&TRNZ ID='MY TRANSFORM', CC=    1.722222222222, PC=    1.511738751154 /
&TRNZ ID='MY TRANSFORM', CC=    1.777777777778, PC=    1.588738827537 /
&TRNZ ID='MY TRANSFORM', CC=    1.833333333333, PC=    1.674906878694 /
&TRNZ ID='MY TRANSFORM', CC=    1.888888888889, PC=    1.771334484860 /
&TRNZ ID='MY TRANSFORM', CC=    1.944444444444, PC=    1.879243194713 /

**Comment by rmcdermo** [comment]
@marcosvanella See #7230 .  Please double check and close if so.  Thanks.

**Comment by marcosvanella** [comment]
Works fine, thanks.
