### ISSUE TITLE
Identifying grid transformations

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7234]
I was testing grid transformations, and I added this line
```
&TRNX CC=0.3, PC=0.5 /
```
But the line was ignored until I added an ID tied to a mesh. Can we restore the existing functionality such that if there is no ID on the TRN line, it applies to all meshes.

**Comment by rmcdermo** [comment]
Try #7237

**Comment by mcgratta** [comment]
Works! Thanks.
