### ISSUE TITLE
Verification Guide: dislocated image

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#7245]
Hi,

Checking the overnight built verification guide. I noticed that **Fig 9.14** doesn't look right. The top one should be placed on left.

![image](https://user-images.githubusercontent.com/20113030/54367705-c2314f80-466a-11e9-82d5-ae6d68834798.png)

Thanks

**Comment by mcgratta** [comment]
Should be fixed now.

**Comment by sbenkorichi** [comment]
Cheers
