### ISSUE TITLE
Provide mesh information in IBM set up

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7248]
```
SET_GC_CUTCELLS_3D Error: GEOM not allowed to cross meshes at different refinement levels.
```
Can you print out with this error statement the numbers of the two meshes.

**Comment by marcosvanella** [comment]
Kevin, do an update and try it. I added NM, NOM and guard cell info.
Still needs shutdown command.

**Comment by mcgratta** [comment]
This works, thanks.
