### ISSUE TITLE
DEVC in same location records blank data for RADIATIVE HEAT FLUX GAS but not for TEMPERATURE.

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#7260]
Please see the input below. If you run the file as is, you will see a column of data without any values in the _devc.csv file. If you change the device quantity to TEMPERATURE and leave all other inputs the same, then you will see ambient data in the _devc.csv file.  I'm not sure the best way to handle this difference, but it seems that either the column should not be written at all if the DEVC is not valid (within a solid for a gas phase device), or the default value (ambient or 0.0) should be written to the data column.

```&HEAD CHID='1'/
&TIME T_END=50.0/

&MESH ID='MESH1', IJK=19,24,9, XB=74.0,83.5,76.0,88.0,0.0,4.25/

&DEVC ID='AT-06', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=79.33686,82.482297,1.7/

&OBST ID='Препятствие', XB=76.5,78.5,82.5,83.0,0.0,4.25, SURF_ID='INERT'/ 
&OBST ID='Препятствие', XB=76.5,83.5,82.0,82.5,0.0,4.25, SURF_ID='INERT'/ 
&OBST ID='Препятствие', XB=80.5,83.5,82.5,83.0,0.0,4.25, SURF_ID='INERT'/ 

&TAIL /
```

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
I see this in the `_devc.csv` file:
```
s,kW/m2
Time,"AT-06"
 0.0000000E+000, 0.0000000E+000
 3.7624524E-001, 0.0000000E+000
 7.5249048E-001, 0.0000000E+000
 1.1287357E+000, 0.0000000E+000
 1.5049810E+000, 0.0000000E+000
 1.8812262E+000, 0.0000000E+000
 2.2574714E+000, 0.0000000E+000
 2.6337167E+000, 0.0000000E+000
 3.0099619E+000, 0.0000000E+000
...
```
What do you see?

**Comment by bwklein** [comment]
I see...
```
s,kW/m2
Time,"AT-06"
```

**Comment by bwklein** [comment]
I am running an older version of FDS, so maybe this is a bug that was already fixed.

 Current Date     : March 26, 2019  08:48:42
 Revision         : FDS6.7.0-0-g5ccea76-master
 Revision Date    : Mon Jun 25 13:03:23 2018 -0400
 Compiler         : Intel ifort 18.0.2.185
 Compilation Date : Tue 06/26/2018  10:49 AM

**Comment by bwklein** [comment]
I'll test with a newer build and see if the problem persists.

**Comment by mcgratta** [comment]
I vaguely recall addressing a case like this, where the device was on a wall. What happens when you remove the OBSTs?

**Comment by bwklein** [comment]
If I move the OBST to not overlap, or if I remove the OBST altogether then I have data for that device in the file.  What I found strange is that when the only change was the quantity, there was a difference in what was written to file.

**Comment by mcgratta** [comment]
RAD FLUX GAS is a special device because it requires that FDS create a particle on which to store the data. The particle was being rejected from the wall, or something like that.
