### ISSUE TITLE
Convective heat transfer when SOLID_PHASE_ONLY = .TRUE.

### ISSUE THREAD

**Issue by arinta-paavola** [firemodels/fds#7263]
When the gaseous phase calculation has been turned off (e.g. in a cone calorimeter simulation), seems that the current code enforces the convective heat transfer coefficient to be calculated as in direct numerical simulation, if a constant value is not specified:
(wall.f90, starting from line 3235)

! If this is a DNS calculation at a solid wall, set HTC and return.

IF ( (SIM_MODE==DNS_MODE .OR. SOLID_PHASE_ONLY) .AND. (PRESENT(WALL_INDEX) .OR. PRESENT(CFACE_INDEX)) ) THEN
   HEAT_TRANSFER_COEFFICIENT = 2._EB * ONE_DX%K_G * ONE_DX%RDN
   RETURN
ENDIF

My question is, would it be possible to add an option to calculate the convective heat transfer coefficient by the correlation for natural convection, based on temperature difference between the sample and the assumed gas temperature, also when the gas phase calulation has been turned off?

**Comment by rmcdermo** [comment]
Sorry I am just seeing this.  I would prefer that you simply turn off the other LES models.  For example, set C_DEARDORFF=0 to turn off the turbulent transport.
