### ISSUE TITLE
Dynamic pressure and Wind

### ISSUE THREAD

**Issue by gutierrezemm** [firemodels/fds#7264]
Hello,

I'm struggling to model wind in a tunnel. I tried to reduce the model to a simple one that I'm describing below

I apply at one end of my tunnel an OPEN condition, and at the other an OPEN condition with a DYNAMIC_PRESSURE at P = 16.5 Pa. 
I also have two obstacles (two cars) in the box.

I am expecting a velocity in my tunnel as defined by P = 1/2 * rho * v² (so, around 5.2 m/s) but the velocity FDS models is only at around 3.8 m/s.
Is there anything I'm missing here ? 

Please find attached the simplified case.

**Comment by gutierrezemm** [comment]
&HEAD CHID='CHEN'
      /


&HEAD CHID='CHEN'
      TITLE='CHEN 200MW'
      /

&TIME T_BEGIN=-300, T_END=1800.000, /
&DUMP DT_DEVC = 1.0, DT_SLCF=1., VELOCITY_ERROR_FILE=.TRUE./

&MISC TMPA=12., RESTART=.FALSE.,SURF_DEFAULT='BETON',  /
&PRES MAX_PRESSURE_ITERATIONS=50 /

&MATL 	ID='BETON'
		DENSITY=2400
		SPECIFIC_HEAT=1
		CONDUCTIVITY=1.6
		EMISSIVITY=0.94 /

&SURF ID='BETON'
      RGB=204,204,204
      TRANSPARENCY=0.200
      MATL_ID='BETON'
      THICKNESS=0.400
      /


&REAC ID                 = 'POLYURETHANE'
      C                  = 6.3
      H                  = 7.1
      N                  = 1.
      O                  = 2.1
      SOOT_YIELD         = 0.1
      CO_YIELD           = 0.1 
	  HEAT_OF_COMBUSTION = 24800 /
	
&RAMP ID='pressure1d', T=-300, F=1.0 /
&RAMP ID='pressure1d', T=0.0, F=1.0 /
&RAMP ID='pressure1d', T=60.0, F=0.133 /
&RAMP ID='pressure1d', T=120.0, F=-0.1 /
&RAMP ID='pressure1d', T=180.0, F=0.0 /
&RAMP ID='pressure1d', T=240.0, F=0.255 /
&RAMP ID='pressure1d', T=300.0, F=0.04 /
&RAMP ID='pressure1d', T=360.0, F=0.0 /
&RAMP ID='pressure1d', T=1800.0, F=0.0 /

&OBST ID='Voiture.030'
      XB=10.000,18.000,3.400,5.400,0.001,2.001
      SURF_IDS='INERT','INERT','INERT' 
      /
&OBST ID='Voiture.031'
      XB=10.000,18.000,7.000,9.000,0.001,2.001
      SURF_IDS='INERT','INERT','INERT' 
      /
&MESH ID='Cube'
      IJK=36,60,27
      XB=0.000,18.000,-1.000,11.000,0.000,5.400
 

&VENT ID='CL CONTREPRESSION'
      SURF_ID='OPEN'
      XB=18.000,18.000,0.000,11.000,0.000,5.400
      TMP_EXTERIOR=12
      /
&VENT ID='CL CONTREPRESSION.001'
      SURF_ID='OPEN'
      XB=-0.000,-0.000,0.000,11.000,0.000,5.400
      TMP_EXTERIOR=12, DYNAMIC_PRESSURE=16.5, PRESSURE_RAMP='pressure1d'
      /

&DEVC ID='DEBIT IN'
      QUANTITY='VOLUME FLOW'
      XB=1.000,1.000,0.000,11.000,0.000,5.400
      /

&OBST ID='MUR AJUSTEMENT MAILLAGE'
      XB=0.000,460.000,-1.000,0.000,0.000,7.200
      COLOR='INVISIBLE'
      /

&SLCF ID='VITESSE'
      QUANTITY='VELOCITY'
      VECTOR=.TRUE.
      PBY=5.000
      /
&SLCF ID='VITESSE.001'
      QUANTITY='VELOCITY'
      VECTOR=.TRUE.
      PBY=10.000
      /
&SLCF ID='vitesse'
      QUANTITY='VELOCITY'
      VECTOR=.TRUE.
      PBY=1.000
      /
&SLCF ID='vitesse.001'
      QUANTITY='VELOCITY'
      VECTOR=.TRUE.
      XB=459.000,459.000,0.000,11.000,0.000,5.400
      /
&SLCF ID='vitesse.002'
      QUANTITY='VELOCITY'
      VECTOR=.TRUE.
      XB=1.000,1.000,0.000,11.000,0.000,5.400
      /
&SLCF ID='vitesse.003'
      QUANTITY='VELOCITY'
      VECTOR=.TRUE.
      XB=201.000,201.000,0.000,11.000,0.000,5.400
      /


&TAIL /

**Comment by mcgratta** [comment]
Friction losses play a role. If you stuffed the tunnel with obstructions, why would you expect to draw air at this same ideal velocity?

**Comment by mcgratta** [comment]
This question is better asked in the Discussion Group. I do not believe that this is a bug in the code.
