### ISSUE TITLE
Last frame in Smokeview corrupted

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7266]
I sometimes notice that the last frame (say a slice file animation) of an on-going, multiple mesh FDS case is sometimes corrupted as shown in the figure. Is there a way to easily not print this last frame unless all meshes have been read?
![image](https://user-images.githubusercontent.com/11333911/55260166-04978680-523e-11e9-81cd-aaa50251cf78.png)

**Comment by gforney** [comment]
I'll take a look at it.  It shouldn't matter - but in case it does can you point me to this case.

**Comment by gforney** [comment]
give the smokeview here a try.  I found an array subrscript problem which may have been causing this problem.  Let me know if you still see it
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by mcgratta** [comment]
Seems to have done the trick. Thanks!
