### ISSUE TITLE
Confined fires (FDS6.2 and FDS6.6)

### ISSUE THREAD

**Issue by LahnaACH** [firemodels/fds#7268]
Hello
This is the second time I'm asking this question.
I simulated a fire in a room of  volume V= 8 m3, using the 3 versions of FDS (FDS 6.2, FDS6.5 and FDS6.6)
(Fuel: Dodecane, in container: D= 40 cm, ACPH = 5)
Mesh: Dx = Dy = Dz = 0.5 cm
Extinction model: EXTINCTION 1
TURBULENCE_MODEL = 'CONSTANT SMAGORINSKY'
Combustion Model :
&REAC ID= 'R1'
      FUEL= 'DODECANE'
      SPEC_ID_NU='DODECANE','OXYGEN','CARBON MONOXIDE','HYDROGEN'
      NU= -1,-6,12,13/
&REAC ID = 'R2'
      FUEL= 'CARBON MONOXIDE'
      SPEC_ID_NU= 'CARBON MONOXIDE','OXYGEN','CARBON DIOXIDE'
      NU = -1,-0.5,1/
&REAC ID = 'R3'
      FUEL= 'HYDROGEN'
      SPEC_ID_NU = 'HYDROGEN','OXYGEN','WATER VAPOR'
      NU= -1,-0.5,1/
I want to know why I can't get the same results among the different FDS versions ?
Which version of FDS do you recommend to use in such case?
What has changed in the new version (FDS 6.6): the extinction model (EXT1) or the combustion model ?

PS: The measurements were taken at the exhaust stream 
![image](https://user-images.githubusercontent.com/34684425/55412695-37a48780-5568-11e9-9eac-f365c98ae6c0.png)

![image](https://user-images.githubusercontent.com/34684425/55410249-d084d400-5563-11e9-80ea-9387ff35bf58.png)

**Comment by LahnaACH** [comment]
thank you

**Comment by rmcdermo** [comment]
Please submit your question to the discussion forum.

https://groups.google.com/forum/#!forum/fds-smv
