### ISSUE TITLE
Error in case two surfaces have the same name

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#7269]
Dear developers,

I noticed that if two surfaces have the same name in the input file, FDS runs smoothly without giving any error or warning. In this case it was my mistake, because I didn't change the name of the surfaces. However, I think it would be useful to create a check in the program to see if there are such silly errors. I attach the input file of the simulation, I tested it both under Windows and Linux, but the error was never detected.

[input.fds.txt](https://github.com/firemodels/fds/files/3042249/input.fds.txt)

Thanks in advance for your help,

Regards,

Matteo

**Comment by sbenkorichi** [comment]
If you have more than one NAMELIST under the same name, then the last one will be used.

**Comment by mcgratta** [comment]
I'll see if this can be done easily.

**Comment by mcgratta** [comment]
Done
