### ISSUE TITLE
FDS: using HVAC to recirculate species in a swimming pool Hall

### ISSUE THREAD

**Issue by HelenePX** [firemodels/fds#7273]
Hello, using FDS in research project to study contaminant transport. Attempting to use HVAC network instead of supply and extract vents. Why? To recirculate the emitted species from water surface (chloramines). What is being extracted is coming back (about 77% of air recirculation in the real case). Any tips on what to avoid would be helpfull. Numerous "Access violation" errors. Nevertheless progressing. Using Pyrosim to build the model, amazing and very helpfull. 
So far I have three HVAC network with respectively 6, 10 and 3 outlets. Each has a known flowrate in m3/s. Total flux is 9.3 m3/s divided in these 3 branches. About 4ACH an hour. Reproducing Faithfull ventilation strategy is important. computational time is high, so making network as simple as possible is my goal.
Thanks for any tips.
Helene

**Comment by bmralph** [comment]
Do you have a specific problem or question?

**Comment by drjfloyd** [comment]
General questions on using FDS should be posted in the discussion forum (https://groups.google.com/forum/?fromgroups=&nomobile=true#!forum/fds-smv).

 If you have an input file that is resulting in an error, we cannot help you without the input file. Please post the file that is giving errors after simplifying it as much as possible while still seeing the error.

**Comment by HelenePX** [comment]
Yes: is it preferable to have more nodes and less ducts or the reverse (reverse I think), to diminish computational time.


In a real layout, one would have more nods to avoid multiple ducts running in parallele. It seems to be a reverse logic to simplify the model in FDS.

Thanks,

Helene
________________________________
De : Benjamin Ralph [notifications@github.com]
Envoyé : vendredi 5 avril 2019 11:51
À : firemodels/fds
Cc : Proulx, Hélène; Author
Objet : Re: [firemodels/fds] Using HVAC to recirculate species in a swimming pool Hall (#7273)

Do you have a specific problem or question?

**Comment by HelenePX** [comment]
Noted, thanks!
________________________________
De : Jason Floyd [notifications@github.com]
Envoyé : vendredi 5 avril 2019 11:51
À : firemodels/fds
Cc : Proulx, Hélène; Author
Objet : Re: [firemodels/fds] Using HVAC to recirculate species in a swimming pool Hall (#7273)


General questions on using FDS should be posted in the discussion forum (https://groups.google.com/forum/?fromgroups=&nomobile=true#!forum/fds-smv).

If you have an input file that is resulting in an error, we cannot help you without the input file. Please post the file that is giving errors after simplifying it as much as possible while still seeing the error.

**Comment by drjfloyd** [comment]
closing this issue. A input with an error was provided in a new issue.
