### ISSUE TITLE
HVAC filter - error

### ISSUE THREAD

**Issue by HelenePX** [firemodels/fds#7278]
HVAC filter forrtl: severe (157): Program Exception - access violation.
When including a filter, error happens. 
Without the filter the simulation runs fine.
A basic test simulation with two nodes and one duct: filter works fine, but on the inlet vent only (the air comming in a comptartment.)
I read all guides available. could not figure it out.

Is this an issue or should I post this in the google discussion group?

Thanks!!

**Comment by HelenePX** [comment]
Context of the simulation.

**Comment by drjfloyd** [comment]
The issue is the filter routine is coded for a filter that has a duct on either side and not a filter that is part of a VENT.  This is an oversight on my part when I developed the routine.  As a workaround split Duct11 into two ducts and put the filter in the new node connecting the two ducts.

**Comment by HelenePX** [comment]
Thank you! I'll try this way. Configuration required:
One duct/one node with filter/one duct.
And not this configuration:
One duct/one node/four ducts (more than one duct).

Merci!
Helene

**Comment by HelenePX** [comment]
Working!! Thank you again!

**Comment by drjfloyd** [comment]
I changed the description in the guide to make it clear that a filter must be in a node with two connected ducts. The solution approach in the solver doesn't lend itself to having the filter at a VENT or AMBIENT node.

**Comment by HelenePX** [comment]
Great thank you!
________________________________
De : Jason Floyd [notifications@github.com]
Envoyé : dimanche 7 avril 2019 18:02
À : firemodels/fds
Cc : Proulx, Hélène; Author
Objet : Re: [firemodels/fds] HVAC filter - error (#7278)


I changed the description in the guide to make it clear that a filter must be in a node with two connected ducts. The solution approach in the solver doesn't lend itself to having the filter at a VENT or AMBIENT node.
