### ISSUE TITLE
CTRL: Control deadband through multiple devices

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#7284]
I've tried to simplified the case. The case seems to work now, but not sure if it's taking all devices into account or a single one of them only.
[junk.fds.txt](https://github.com/firemodels/fds/files/3063100/junk.fds.txt)

![image](https://user-images.githubusercontent.com/20113030/55869105-bfe4e700-5b7d-11e9-9925-5311f7b8d87d.png)

Thanks

**Comment by Er9y714** [comment]
ANY function changes its STATE if any of the inputs change their STATE. I do not know how CTRL_ID= Pressure gives a numerical output here. 



I would suggest using a RAMP on the speed of the supply vent dependant on the Pressure as an input.


```
&CTRL ID='Pressure', FUNCTION_TYPE='ANY', LATCH=.FALSE., INPUT_ID='Pressure01','Pressure02','Pressure03','Pressure04','Pressure05','Pressure06'/
&CTRL ID='supply', FUNCTION_TYPE='DEADBAND', SETPOINT=35.0,45.0, ON_BOUND='LOWER', LATCH=.FALSE., INPUT_ID='Pressure'/
&DEVC ID='Pressure01', QUANTITY='PRESSURE', XYZ=9.1,-0.5,4.9, TIME_AVERAGED=F/
&DEVC ID='Pressure02', QUANTITY='PRESSURE', XYZ=9.1,-0.5,7.6, TIME_AVERAGED=F/
&DEVC ID='Pressure03', QUANTITY='PRESSURE', XYZ=9.1,-0.5,10.3, TIME_AVERAGED=F/
&DEVC ID='Pressure04', QUANTITY='PRESSURE', XYZ=9.1,-0.5,13.0, TIME_AVERAGED=F/
&DEVC ID='Pressure05', QUANTITY='PRESSURE', XYZ=9.1,-0.5,16.1, TIME_AVERAGED=F/
&DEVC ID='Pressure06', QUANTITY='PRESSURE', XYZ=9.1,-0.5,18.7, TIME_AVERAGED=F/
```

**Comment by Er9y714** [comment]
This shows the CTRL and DEVC output. It seems like 'supply' is controlled by only the first input; Pressure01 for the deadband of 35 and 45.

![image](https://user-images.githubusercontent.com/26166281/55877567-a736fa00-5b9a-11e9-9a58-52fad7c2a166.png)

**Comment by drjfloyd** [comment]
DEADBAND needs a number as an input.  ANY, ALL, and the other logical control functions only output a logical state. How exactly do you want to use 6 pressure devices to control a deadband.  Do you want to control on the maximum pressure seen by any device, the minimum, the average? First you need to define exactly how you want those 6 devices to result in a single pressure value. Then based on that, use the math control functions to do that process. For example if you decided you wanted to control based on average pressure you would need a SUM function to sum the pressures and a DIVIDE function to divide the sum by 6. Then the result of that would be an average you could use as the input to the DEADBAND.

**Comment by sbenkorichi** [comment]
Thanks Jason for the info.
I usually use only one device that has specific range. However, in this case example, I would need to have a device per each floor level and I want the DEADBAND to be controlled through these devices in a similar way as a single one.  `FUNCTION_TYPE='DEADBAND', SETPOINT=35.0,45.0,` I will need I guess to have the MAX as 45 from all these devices, and the MIN as 35, and then input it into the SETPOINT of the DEADBAND. So, once these values are reached the state of the VENT would change.

**Comment by drjfloyd** [comment]
Think of it as you hired a person to watch the outputs from the 6 pressure devices and turn on or off ventilation based on what they are observing. How would you instruct them to do that? Then write a set of control function and devices to implement those instructions. Since this isn't a bug, I'm going to close the issue.

**Comment by sbenkorichi** [comment]
Yes. Cheers for that.
