### ISSUE TITLE
DEVC on static PARTicles using INIT

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#7285]
Following the topic [here ](https://groups.google.com/forum/#!topic/fds-smv/YjTu3y8qPoE)I report the issue:

Only the first two `DEVC `works, the rest does not.

Thank you.

FDS 6.7.1

`&HEAD CHID='v2'/
&TIME  T_END=90.0/ 
&DUMP DT_DEVC=0.1 / 
 
 

&MESH ID='Mesh4', IJK=143,54,18, XB=4.2,32.8,-5.0,5.8,3.0,6.6   / 
&MESH ID='Mesh5', IJK=384,29,18, XB=32.8,109.6 ,0.0,5.8,3.0,6.6  / 

&PART ID='PartEvacRad',
      STATIC=.TRUE.,
      SURF_ID='EvacRad',
      AGE=900.0,
      SAMPLING_FACTOR=1,
      ORIENTATION(1:3,1)=0,0,1 /

  
 
&SURF ID='EvacRad',
      RGB=0,204,204, 
      EMISSIVITY=1.0,
      GEOMETRY='SPHERICAL',
      RADIUS=0.01 /
	  
	  
&INIT ID='P_1', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=15.0,1.2,4.0/ 
&INIT ID='P_2', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=30.0,1.2,4.0/ 
&INIT ID='P_3', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=45.0,1.2,4.0/ 
&INIT ID='P_4', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=60.0,1.2,4.0/ 
&INIT ID='P_5', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=75.0,1.2,4.0/ 
&INIT ID='P_6', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=90.0,1.2,4.0/ 
&INIT ID='P_7', PART_ID='PartEvacRad', N_PARTICLES=1, XYZ=105.0,1.2,4.0/ 
 
&DEVC ID='Inc_P_1', INIT_ID='P_1', QUANTITY='INCIDENT HEAT FLUX' / 
&DEVC ID='Inc_P_2', INIT_ID='P_2', QUANTITY='INCIDENT HEAT FLUX' / 
&DEVC ID='Inc_P_3', INIT_ID='P_3', QUANTITY='INCIDENT HEAT FLUX' / 
&DEVC ID='Inc_P_4', INIT_ID='P_4', QUANTITY='INCIDENT HEAT FLUX' /  
&DEVC ID='Inc_P_5', INIT_ID='P_5', QUANTITY='INCIDENT HEAT FLUX' / 
&DEVC ID='Inc_P_6', INIT_ID='P_6', QUANTITY='INCIDENT HEAT FLUX' / 
&DEVC ID='Inc_P_7', INIT_ID='P_7', QUANTITY='INCIDENT HEAT FLUX' /   

&SURF ID='HOTs',
      RGB=204,255,255, 
	  TMP_FRONT=400/

&VENT ID='HOT', SURF_ID='HOTs', MB='ZMAX'/ 

&TAIL /`

**Comment by mcgratta** [comment]
This bug has been fixed since the last release.

**Comment by Er9y714** [comment]
Glad to hear. Thank you.

Could you recommend an alternative way to measure incident heat flux for tenability purposes without affecting the air flow in a tunnel?

Thank you.
