### ISSUE TITLE
forrtl(157):program exception access violation error

### ISSUE THREAD

**Issue by linkzkz** [firemodels/fds#7288]
My English is not very good. I am a postgraduate and study fire simulation by FDS.
My FDS version is 6.1.2.
The simulation without sprinkler is working properly.However, the following error occurred after the sprinkler was added.
![forrtl severe(157)截圖](https://user-images.githubusercontent.com/49510743/55936459-f9465100-5c68-11e9-91e6-c874cfc75405.PNG)
[40spr-1000um.txt](https://github.com/firemodels/fds/files/3067290/40spr-1000um.txt)

**Comment by Er9y714** [comment]
Is using the latest version of FDS not an option? This could be not a design error but a bug in FDS and might have been fixed since.

**Comment by mcgratta** [comment]
We only consider bug reports where the latest version of FDS is used. Run your case with the latest version of FDS and report the problem if it still exists.

**Comment by linkzkz** [comment]
I need to compare with the previous study,so I need to maintain version consistency.I will try the latest version.
It is very strange to me that one or two simulations succeed, but when I run the simulation of the same file or just change a parameter (such as water droplet diameter), an error occurs.

**Comment by mcgratta** [comment]
Well, that is why we release new versions -- to fix these things.

**Comment by drjfloyd** [comment]
From the FDS release notes (https://github.com/firemodels/fds/wiki/FDS-Release-Notes):

FDS 6.6.0 (Oct 31, 2017)

-Implementation of new implicit droplet evaporation scheme. Fixes many stability issues with droplet cases

**Comment by linkzkz** [comment]
Ok, I am already running with the  version 6.7.0
I hope there will be no more errors.
Sincerely thanks for your answer.

**Comment by Er9y714** [comment]
@linkzkz for information, the latest version is 6.7.1

**Comment by mcgratta** [comment]
Has your problem been resolved?
