### ISSUE TITLE
Use real TMP in GET_KAPPA argument

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7296]
@mcgratta I'd like to use GET_KAPPA outside radi for the TRI model.  But it's ugly because instead of passing an actual temperature we pass an index to the lookup table.  Let's change this so that we pass TMP in Kelvins.

I'd make this change, but I don't want to make a mistake on this.  It looks like to me that we need to make
```
TYY_FAC = N_KAPPA_T / (RTMPMAX-RTMPMIN)
```
a parameter which will just be known within GET_KAPPA.  But where exactly to put this is where I'm fuzzy.

**Comment by drjfloyd** [comment]
I think you can just move the computation of TYY_FAC calculation into GET_KAPPA, change the call to GET_KAPPA to use TMP, and make GET_KAPPA PUBLIC at the top of the MODULE?

**Comment by mcgratta** [comment]
Jason and Simo know this bit more than I. Jason, can you try your idea.

**Comment by drjfloyd** [comment]
Should be working now as a callable function using TMP rather than TYY.

**Comment by rmcdermo** [comment]
Jason,
I think that is a bit inefficient, as GET_KAPPA is inside a 3D loop and TYY_FAC is constant.  But, yes, it should basically be that simple.

**Comment by drjfloyd** [comment]
Yes you are correct. When I made the change to using TMP, I also moved TYY_FAC to the part of the code where we setup the kappa arrays so not it is only computed once.

**Comment by drjfloyd** [comment]
closing as there doesn't seem to have been any firebot issues from the change.
