### ISSUE TITLE
Smokeview: allow user to specify rotation rate for circular tour

### ISSUE THREAD

**Issue by DavidShep** [firemodels/fds#7307]
Allow the user to change the rotation rate so that the user can adjust how fast the model spins.  When you speed up the frame rate of the model results, the rotation rate of the tour also increases.  Often the rate of spread of smoke and heat through a large structure is slow.  When you increase the frame rate to visualize the smoke spread in a reasonable amount of time the model is often spinning too fast.

**Comment by gforney** [comment]
this issue will be addressed in #7306
