### ISSUE TITLE
SMV clipping scenes 

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#7315]
Hi,

I noticed an issue on SMV 6.7.6. Here are the steps to reproduce:

- Open smv file
- `clip blockages and data` in x (or y) direction, adjust to a level the model is visibly clipped
- resize the SMV window slightly
- Issue: clipping is reset. Complete model is visible again. However, values on the clipping window remain.

 

I tried it in Windows 7 and 10.

Thank you.

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by Er9y714** [comment]
Thank you Glenn. It works.
