### ISSUE TITLE
having problem to install FDS

### ISSUE THREAD

**Issue by pleasegivemeanam** [firemodels/fds#7323]

**Comment by rmcdermo** [comment]
Post your question to the discussion forum.

https://groups.google.com/forum/?fromgroups#!forum/fds-smv

**Comment by pleasegivemeanam** [comment]
I am having problem to install FDS. Please refer to the below pic
![Capture](https://user-images.githubusercontent.com/50265048/57178504-ae081280-6ea3-11e9-97d4-a7f1994883b3.PNG)

**Comment by rmcdermo** [comment]
The Issues page is for bug reports.  There are many threads about this issue on the discussion forum.  Please start there.

**Comment by pleasegivemeanam** [comment]
thank you!
