### ISSUE TITLE
Temperature below zero

### ISSUE THREAD

**Issue by KontarNadezhda** [firemodels/fds#7338]
FDS Version 6.7.1
I simulated big fire in warehouse and I have problem with temperature outside building. It drops under zero.
I tried set VELOCITY_TOLERANCE=0.0001 and change reaction fuel to methan as I was said https://groups.google.com/forum/#!topic/fds-smv/TtbM2T22quk  Temperature now doesn't drop under zero but still go down to 16-17 C.
I tried different MAX_PRESSURE_ITERATIONS, temperature stops decreasing after 600-700 iterations. 
Also I tried change conductivity in MATL and  temperature stops decreasing at 20 W/m/K (see picture). I don't understand why MATL prameters have such effect.
Input file [temperature.zip](https://github.com/firemodels/fds/files/3180877/temperature.zip)

![graf](https://user-images.githubusercontent.com/50649057/57748171-38e1dc00-76f2-11e9-9ade-18ff8b5b17e3.png)

**Comment by mcgratta** [comment]
This is numerical error. You have a very large fire in your building, causing large pressure increases. There is nothing you can do except tighten the VELOCITY_TOLERANCE and increase MAX_PRESSURE_ITERATIONS.
