### ISSUE TITLE
Unable to get the proper Layer Height

### ISSUE THREAD

**Issue by ahmedsalem70** [firemodels/fds#7340]
Dear All,
Currently, I am running the case shown in the attached FDS file and I am facing a problem while trying to estimate the Smoke Layer Height in several compartments within the domain. The layer height starts from a different height than the room height and also shows values in far compartments while it should not.
I hope to help me find where is the mistake in my input file.

 Best Regards,
Ahmed
[NFH_Case-A.zip](https://github.com/firemodels/fds/files/3186703/NFH_Case-A.zip)

**Comment by mcgratta** [comment]
I need a simple case that demonstrates the problem. This one is too complicated. Strip out everything from the input file that is not essential. For example, all those RAMP lines.

**Comment by ahmedsalem70** [comment]
Sorry for the bother. Please find attached a simplified copy of the input file.
[NFH_Case-A_Simple.zip](https://github.com/firemodels/fds/files/3187328/NFH_Case-A_Simple.zip)

**Comment by mcgratta** [comment]
That's not simple. 20 lines or less. It's very possible in doing this that you find a mistake yourself.

**Comment by ahmedsalem70** [comment]
I hope it is fine now.
[NFH_Case-A_Simple (2).zip](https://github.com/firemodels/fds/files/3189347/NFH_Case-A_Simple.2.zip)

**Comment by mcgratta** [comment]
It is not fine, but I'll run it anyway.

First, you are not specifying things properly. 
```
&DEVC ID='LAYER1-Cabin1->HEIGHT', QUANTITY='LAYER HEIGHT', XB=0.0,3.6,0.0,6.6,0.0,2.4/
```
The x and y values for XB should be the same. This then denotes a single location in the room for the layer calculation. Second, you cannot expect the layer algorithm to indicate a layer height when there is no layer. You need to wait until a layer develops before the algorithm will yield a sensible result.

**Comment by ahmedsalem70** [comment]
Thank you, Kevin.
Anyway, an older version of FDS has given reasonable results without changing anything in the input file.

**Comment by mcgratta** [comment]
I recommend that you always include 'UPPER TEMPERATURE' and 'LOWER TEMPERATURE' and make sure that these two are significantly different. If not, the layer formula is meaningless.
