### ISSUE TITLE
beam detector doesn't work

### ISSUE THREAD

**Issue by KontarNadezhda** [firemodels/fds#7345]
FDS 6.7.1: beam detector didn't activated during simulation though accoding to graf it should be activated in 3-4 s. (1.zip)
FDS 6.7.0: the same input file, beam detector is activates as expected. (2.zip)
[1.zip](https://github.com/firemodels/fds/files/3194239/1.zip)
[2.zip](https://github.com/firemodels/fds/files/3194240/2.zip)

**Comment by mcgratta** [comment]
Yes, this was a bug that was unique to BEAM DETECTOR, because it's value is not calculated completely until it is printed. The devc output is OK, but Smokeview was not getting the signal. Thanks for finding this.

**Comment by pjesteve** [comment]
Is this an issue that will be fixed in a future update? When a beam detector does not activate, it's not contributing to a control it may be attached to, rendering the control itself useless. Are there any workarounds in the mean time until a potential future resolution to this?

**Comment by drjfloyd** [comment]
The fix will be in the next release.  As part of 6.7.1 we added the ability to have STATISTICS devices span multiple meshes. Part of that change resulted in introducing a bug to the PATH OBSCURATION device type.  In this case there isn't a work around that I can think of.  If you need to use this device type use FDS 6.7.0 for this particular case.

**Comment by pjesteve** [comment]
Great thank you. Out of curiosity, does this bug also currently affect beam detectors with a quantity of 'TRANSMISSION' opposed to 'PATH OBSCURATION'?

**Comment by mcgratta** [comment]
Yes

**Comment by lupprock** [comment]
Out of curiosity, has the activation of the beam detector been resolved in the latest FDS releases?

**Comment by drjfloyd** [comment]
This should be working now,
