### ISSUE TITLE
How to visualize smoke detectors

### ISSUE THREAD

**Issue by godisreal** [firemodels/fds#7347]
I run a verification case (/detector/smoke_detector.fds) and it works well.  However, when I add the PROP and DEVC in another example, the smoke detector cannot be visualized.  I read Section 19.7 in FDS User Guide, (Visualizing FDS Devices in Smokeview), and then added SMOKEVIEW_ID='smoke_detector', but it does not work.  Is there anything wrong in my input file?  Thanks.  
[smoke_det3.txt](https://github.com/firemodels/fds/files/3195201/smoke_det3.txt)

**Comment by mcgratta** [comment]
It works for me in the latest version of the source code, which has not been released. I think that this is a bug I recently fixed.

**Comment by godisreal** [comment]
So you mean there is no problem in the input file?  I need to confirm whether I write anything wrong in the input file.  I do not have your source code since it is not released.  So I do not have any conclusion here

**Comment by mcgratta** [comment]
The bug is in FDS, not your input file. And you do have the latest source code. It is [https://github.com/firemodels/fds/tree/master/Source](https://github.com/firemodels/fds/tree/master/Source)
