### ISSUE TITLE
Restart error

### ISSUE THREAD

**Issue by caladoa** [firemodels/fds#7348]
I am having issues restarting my FDS run and get an error for access violation
![image](https://user-images.githubusercontent.com/50838087/58032480-ab86f900-7af0-11e9-87cc-4193623716ba.png)

I did include the Restart = TRUE in the misc line. It appears to have no issues once you start it fresh, but I cannot use the restart files

**Comment by mcgratta** [comment]
I need a simple version of the input file that causes the problem. Tell me what version of FDS you are using, your operating system, and how you stopped the calculation, and at what time.

**Comment by caladoa** [comment]
[_16_04.txt](https://github.com/firemodels/fds/files/3199106/_16_04.txt)

FDS 6.6.0 with Windows 7 Pro 64 bit.
Stopped run at 698.62 sec with .STOP file.

The simulation is quite heavy because it has sprinklers. I removed all the slice files for you.

Thanks in advance!

**Comment by mcgratta** [comment]
Run the case for 5 s and then stop it and try to restart. Also, try this
with the latest version.

>

**Comment by caladoa** [comment]
I tried running it for a short period and restarting with latest version and this worked.

I went back to the stopped run and tried running this with the new FDS version and got the error "input statement requires too much data, unit 261".

Is this a problem related to Windows or is there anything else I can try?

Thanks!

**Comment by mcgratta** [comment]
Restarts only work with the same version. All I can say that if the case
works with the latest version, then that is the one to use.

>
