### ISSUE TITLE
AGL_SLICE documentation and use with GEOM

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7356]
AGL_SLICE is not documented in the FDS user guide.  At least I do not see it in the list of namelist parameters for SLCF.  Few things to consider:

1. The name of parameter looks more like a boolean than a real.  Perhaps a better name would be AGL_SLICE_Z_OFFSET?

2. By default, it looks like we smooth the geometry.  I'd prefer this not be the case.  I think it is important for users to know exactly what the geometry is.

3. AGL_SLICE does not seem to work with GEOM.  (see attached input file).  This is needed for soot concentrations in the CERN application using GEOM.

4. If we set a CELL_CENTERED AGL slice, it would be good just draw planes at the Z level above the OBST/GEOM (not high priority).

**Comment by rmcdermo** [comment]
It also seems like the slice image is static.  I cannot figure out how to see time history of the slice as usual.  Input file is attached below.

[agl_slice_test.fds.txt](https://github.com/firemodels/fds/files/3215658/agl_slice_test.fds.txt)

**Comment by rmcdermo** [comment]
OK, time history seems to be working fine in this case.

**Comment by gforney** [comment]
AGL_SLICE has not been implemented for GEOM yet.  I'll talk with marcos about this

**Comment by mcgratta** [comment]
`AGL_SLICE` works for both `OBST` and `GEOM` terrain definitions.
