### ISSUE TITLE
Instability of huge domain model with water mist.

### ISSUE THREAD

**Issue by MisaCZ** [firemodels/fds#7363]
Hello,
I solve a huge domain model where a water mist spray is inserted in space with high temperature (approx. 300 °C). The space is a room 4 x 4 x 2 m, divided into 4 approximately same meshes. There are 8 wooden bonfires symmetrically deployed in the front half of the room (mesh2 and mesh4).  Air can flow in the room through the window, 1.2 m x 2 m, in the front wall. Two nozzles are situated on the side wall of the room in the mesh3 and are oriented to the space of mesh3 and mesh1.
After the water mist instertion the warnings, type DELTA TMP_G Mesh3 Particle 1191, were for some particles. The computing was after aprox. 50 s after the water insertion interrupted. Do you have any idea what does cause the interruption of computing? Could it be because of this warning? I tried the model of single water mist nozzle and the smaller model with just one bonfire and one water mist nozzle. All of these smaller projects ran without any problems.
Thank you.
[mist2_5000.txt](https://github.com/firemodels/fds/files/3222742/mist2_5000.txt)

**Comment by jmvaari** [comment]
For what it's worth: I ran into the same problem yesterday running a water mist case which I unfortunately cannot share. I used FDS6.7.1-444-g5c01496-master, compiler Gnu gfortran 6.3.0. However, the same cases seem to (so far) run smoothly with FDS6.7.0-950-gbcec1bc-master, compiler Intel ifort 18.0.0.

**Comment by drjfloyd** [comment]
With the spray not coming on until 800 s into the calculation this case is going to take too long to try and debug. I'll note that you have an OFFSET of 0.001 with a grid size of 0.05.  All off your spray is being placed into a single grid cell at the nozzle. Try running your case with OFFSET=0.1

**Comment by jmvaari** [comment]
I had OFFSET 0.1 with a grid size 0.1.

**Comment by Er9y714** [comment]
I have run the case starting from 799s. I received the following errors:
```


At 863.99 s
WARNING TMP_G_N < TMP_D_N. Mesh: 3, Particle: 4755

972.66s
WARNING TMP_G_N < TMP_D_N. Mesh: 3, Particle: 11878

900.81s
WARNING Delta TMP_G. Mesh: 3, Particle: 2229

928.48
WARNING Delta TMP_G. Mesh: 1, Particle: 396

957.34s
WARNING Delta TMP_G. Mesh: 3, Particle: 285

975.92s
WARNING Delta TMP_G. Mesh: 2, Particle: 3460

```

However, when I ran the case with MPI, I have not received any errors (1300 s so far).
```

&MESH ID='mesh1', IJK=39,39,40 XB=-3.0,-1.05,1.05,3.0,0.0,2.0 MPI_PROCESS=0/
&MESH ID='mesh2',IJK=39,40,40 XB=-3.0,-1.05,-0.95,1.05,0.0,2.0 MPI_PROCESS=1/
&MESH ID='mesh3',IJK=41,39,40 XB=-1.05,1.0,1.05,3.0,0.0,2.0 MPI_PROCESS=2/
&MESH ID='mesh4',IJK=41,40,40 XB=-1.05,1.0,-0.95,1.05,0.0,2.0 MPI_PROCESS=3/
&MESH ID='mesh5',IJK=160,5,80, XB=-3.0,1.0,-1.075,-0.95,0.0,2.0 MPI_PROCESS=4/
&MESH ID='mesh6',IJK=80,3,40, XB=-3.0,1.0,-1.225,-1.075,0.0,2.0 MPI_PROCESS=5/
```

**Comment by Er9y714** [comment]
Here are the output files:
Default file:
[mist2_5000.txt](https://github.com/firemodels/fds/files/3246084/mist2_5000.txt)

MPI file:
[mist2_5000NT.txt](https://github.com/firemodels/fds/files/3246087/mist2_5000NT.txt)

**Comment by mcgratta** [comment]
Were you able to complete your calculation?

**Comment by Er9y714** [comment]
If the question is to me, no I have not continued after what I had reported.

**Comment by mcgratta** [comment]
I am running the original case to see if things have improved since the original posting.

**Comment by mcgratta** [comment]
I have run the case for several days and I see the same warning message that @MisaCZ describes. I've added the following text to the User's Guide. 
```
17.3.6 Warning Messages Related to Droplets
An important parameter for any simulation involving liquid droplets is PARTICLES_PER_SECOND on the PROP line, which is specified by the DEVC line that includes the sprinkler or nozzle coordinates. The default value is 5000 particles per second. In some cases, this value might be too low, and you may want to raise it. The reason is that each liquid droplet that FDS explicitly tracks represents many, many more actual droplets, and the effect on the simulation of this one “super drop” may be relatively large. For example, a single droplet within a grid cell might decrease the gas temperature rapidly over the duration of just one time step—something that would not happen if there were many more droplets within the cell. You might
even see within the output file named case_name.err warning messages like:
WARNING Delta TMP_G. Mesh: 5 Particle: 3245
This means that during the temperature update of a particular grid cell in Mesh 5, the droplet whose index is 3245 caused the cell gas temperature (TMP_G) to change too rapidly. If you only see a few of these messages, it is not a problem given how many droplets and time steps there are. However, if you see these messages persistently, you might want to increase the PARTICLES_PER_SECOND to reduce the likelihood that a single droplet will make such a dramatic change in a single time step.
```

**Comment by MisaCZ** [comment]
Hello Kevin,
I did not have time to run this file once more unfortunately.

Thank you for clarifying this issue. I think that your describtion of
warnig reason is clear and it will help other users.


pá 10. 4. 2020 v 19:36 odesílatel Kevin McGrattan <notifications@github.com>
napsal:
