### ISSUE TITLE
Why set RADIATIVE_FRACTION=0.0

### ISSUE THREAD

**Issue by cooperrrrr** [firemodels/fds#7394]
Hello, everyone.

I have seen many validation cases with "RADIATIVE_FRACTION=0.0" though the fuel is propane, actually, the radiative fraction should be 0.3.
For example,
> &COMB RADIATIVE_FRACTION=0., N_SIMPLE_CHEMISTRY_REACTIONS=2 /
> &REAC FUEL='PROPANE', AUTO_IGNITION_TEMPERATURE=450. /

I want to know why set RADIATIVE_FRACTION=0.0, Isn't it better to set the real value?

**Comment by rmcdermo** [comment]
This is not a bug in the code or documentation.  Please submit your question to the discussion forum and we will answer there so everyone benefits from the discussion.

https://groups.google.com/forum/#!forum/fds-smv
