### ISSUE TITLE
using SMOKEVIEW_ID with particles SHAPE='CONE'

### ISSUE THREAD

**Issue by brunoguillaume** [firemodels/fds#7420]
Hi Glenn,

here is the 'issue' associated to the same topic on the forum, together with fds file attached.
I use Windows FDS v6.7.1.

Thanks for your help

Bruno
[test_forest.txt](https://github.com/firemodels/fds/files/3296945/test_forest.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
The following line in your input file
&PROP ID='trcanopy' SMOKEVIEW_ID='CANOPY' SMOKEVIEW_PARAMETERS(1:3)='CANOPY_BASE_H=0','CANOPY_D=1.64','CANOPY_H=2.25'/

causes smokeview to replace EACH particle with an object from smokeview's objects.svo file named 'CANOPY' .  It does not draw a cone for the collection of particesl you've defined with various &INIT keywords.  To see this select
Show/Hide>Particles>foliage2>Canopy

To do what you want, you could place one particle in each location you would like a tree then use this PROP line to define a tree.

**Comment by brunoguillaume** [comment]
thanks a lot for your reply.
I understand my mistake. Now trying to place a tree at one particle, I still encounter problems (I am not familiar with the PROP of particles).

I replaced the lines:

&INIT PART_ID='foliage2', XYZ=41.0,7.0,0.0 RADIUS=  0.82, HEIGHT= 2.25, SHAPE='CONE', N_PARTICLES_PER_CELL=1, MASS_PER_VOLUME=2.2 /

&PART ID='foliage2', DRAG_COEFFICIENT=1.0, SURF_ID='needles', SAMPLING_FACTOR=1,
      QUANTITIES='PARTICLE TEMPERATURE','PARTICLE MASS','PARTICLE DIAMETER', STATIC=.TRUE., COLOR='GREEN', PROP_ID='trcanopy' /	  
&PROP ID='trcanopy' SMOKEVIEW_ID='CANOPY' SMOKEVIEW_PARAMETERS(1:3)='CANOPY_BASE_H=0','CANOPY_D=1.64','CANOPY_H=2.25'/

by the lines:

&INIT PART_ID='foliage', XYZ=41.0,7.0,0.0 RADIUS=  0.82, HEIGHT= 2.25, SHAPE='CONE', N_PARTICLES_PER_CELL=1, MASS_PER_VOLUME=2.2 /

&INIT XYZ=41.0,7.0,0.0 N_PARTICLES=1, PART_ID='test_tree' /

&PART ID='test_tree', STATIC=.TRUE.,SURF_ID='ball', PROP_ID='trcanopy' /
&SURF ID='ball', RADIUS=0.001, GEOMETRY='SPHERICAL', EMISSIVITY=1. /
&PROP ID='trcanopy' SMOKEVIEW_ID='CANOPY' SMOKEVIEW_PARAMETERS(1:3)='CANOPY_BASE_H=0','CANOPY_D=1.64','CANOPY_H=2.25'/

but I only see in SMV the particle and not the tree (Show/Hide > Particles > test_tree > test_tree, but no 'CANOPY').

Any idea?

Bruno

**Comment by brunoguillaume** [comment]
Glen, I commented in the same 'issue' in GIT. Any idea?

**Comment by gforney** [comment]
If you want to visualize trees using the cone/canopy objects and model trees using a collection of particles forming a cone, then I would use two sets of &INIT lines.  Your original &INIT line to form the particle cones but don't use the SMOKEVIEW canopy object and a 2nd &INIT line with one particle placed at each location where you want a tree and use the SMOKEVIEW canopy.

**Comment by mcgratta** [comment]
I suggest you visualize the trees as a collection of particles. The Smokeview object is not appropriate in this case.

**Comment by brunoguillaume** [comment]
Hi, thanks, I will do like that.

Le jeu. 20 juin 2019 à 16:11, Kevin McGrattan <notifications@github.com> a
écrit :
