### ISSUE TITLE
Particle Screen - slow run time

### ISSUE THREAD

**Issue by smustafa3** [firemodels/fds#7436]
I created two FDS files that are identical in setup except one has a steel mesh screen (mesh pallet) in the domain above a burner (in the plume region) while the other instead has a solid obstruction (solid pallet) where the mesh would be (solid obstruction model does not have a screen in the input file). 

The FDS file with the mesh screen is taking very long to run, though it has not crashed (running on four processors, progressed to 48s in 122 hours).

The FDS file without the mesh screen completed successfully without errors (four processors, 300s completed in 63 hours).

Is there a way to make the run go faster? A snapshot of the results from a nearly identical set of FDS runs seemed to match the expected physics (plume temperature profile continued through the mesh but was redirected in the case with the obstruction, smv images attached), so I believe the setup of the screen is correct. 

The following lines were used in setting up the screen (note MISC line was added after looking over previous posts in the FDS+SMV support google group):

&MATL ID='STEEL',
      FYI='Drysdale, Intro to Fire Dynamics - ATF NIST Multi-Floor Validation',
      SPECIFIC_HEAT=0.46,
      CONDUCTIVITY=45.8,
      DENSITY=7850.0,
      EMISSIVITY=0.95/

&SURF ID='SCREEN',
      MATL_ID(1,1)='STEEL',
      MATL_MASS_FRACTION(1,1)=1.0,
      THICKNESS(1)=7.5E-4,
      GEOMETRY='CARTESIAN'/

&PART ID='SCREEN',
      STATIC=.TRUE.,
      SURF_ID='SCREEN',
      DRAG_LAW='SCREEN',
      FREE_AREA_FRACTION=0.36,
      ORIENTATION(1,1)=0.0, ORIENTATION(2,1)=0.0, ORIENTATION(3,1)=1.0/

&MISC PARTICLE_CFL=.TRUE., PARTICLE_CFL_MAX=0.9/

&INIT ID='SCREEN - L3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,1.08,1.493333,2.202856,2.227856/ 
&INIT ID='SCREEN - L2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.450036,1.543236,1.956569,2.202856,2.227856/ 
&INIT ID='SCREEN - L1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,2.006663,2.42,2.202856,2.227856/ 
&INIT ID='SCREEN - R1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,2.006663,2.42,2.202856,2.227856/ 
&INIT ID='SCREEN - R3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,1.08,1.493333,2.202856,2.227856/ 
&INIT ID='SCREEN - R2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145036,1.543236,1.956569,2.202856,2.227856/ 
&INIT ID='SCREEN - L3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,1.08,1.493333,2.050456,2.075456/ 
&INIT ID='SCREEN - L2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.450036,1.543236,1.956569,2.050456,2.075456/ 
&INIT ID='SCREEN - L1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,2.006663,2.42,2.050456,2.075456/ 
&INIT ID='SCREEN - R1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,2.006663,2.42,2.050456,2.075456/ 
&INIT ID='SCREEN - R2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145036,1.543236,1.956569,2.050456,2.075456/ 
&INIT ID='SCREEN - R3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,1.08,1.493333,2.050456,2.075456/ 
&INIT ID='SCREEN - L3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,1.08,1.493333,4.2504,4.2754/ 
&INIT ID='SCREEN - L2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.450036,1.543236,1.956569,4.2504,4.2754/ 
&INIT ID='SCREEN - L1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,2.006663,2.42,4.2504,4.2754/ 
&INIT ID='SCREEN - R1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,2.006663,2.42,4.2504,4.2754/ 
&INIT ID='SCREEN - R2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145036,1.543236,1.956569,4.2504,4.2754/ 
&INIT ID='SCREEN - R3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,1.08,1.493333,4.2504,4.2754/ 
&INIT ID='SCREEN - L3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,1.08,1.493333,4.4028,4.4278/ 
&INIT ID='SCREEN - L2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.450036,1.543236,1.956569,4.4028,4.4278/ 
&INIT ID='SCREEN - L1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,2.006663,2.42,4.4028,4.4278/ 
&INIT ID='SCREEN - R1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,2.006663,2.42,4.4028,4.4278/ 
&INIT ID='SCREEN - R3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,1.08,1.493333,4.4028,4.4278/ 
&INIT ID='SCREEN - R2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145036,1.543236,1.956569,4.4028,4.4278/ 
&INIT ID='SCREEN - L3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,1.08,1.493333,6.400456,6.425456/ 
&INIT ID='SCREEN - L2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.450036,1.543236,1.956569,6.400456,6.425456/ 
&INIT ID='SCREEN - L1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,2.006663,2.42,6.400456,6.425456/ 
&INIT ID='SCREEN - R1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,2.006663,2.42,6.400456,6.425456/ 
&INIT ID='SCREEN - R2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145036,1.543236,1.956569,6.400456,6.425456/ 
&INIT ID='SCREEN - R3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,1.08,1.493333,6.400456,6.425456/ 
&INIT ID='SCREEN - L3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,1.08,1.493333,6.552856,6.577856/ 
&INIT ID='SCREEN - L2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.450036,1.543236,1.956569,6.552856,6.577856/ 
&INIT ID='SCREEN - L1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=0.805,1.45,2.006663,2.42,6.552856,6.577856/ 
&INIT ID='SCREEN - R1', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,2.006663,2.42,6.552856,6.577856/ 
&INIT ID='SCREEN - R3', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145,1.08,1.493333,6.552856,6.577856/ 
&INIT ID='SCREEN - R2', PART_ID='SCREEN', N_PARTICLES_PER_CELL=1, CELL_CENTERED=.TRUE., XB=1.5,2.145036,1.543236,1.956569,6.552856,6.577856/ 

<img width="1287" alt="Screen Shot 2019-06-19 at 4 01 42 PM" src="https://user-images.githubusercontent.com/35572495/59796590-dc06b200-92ab-11e9-866a-f74da15cf148.png">

**Comment by mcgratta** [comment]
What version of FDS?

**Comment by smustafa3** [comment]
FDS 6.7.1 

Simulation set up using Pyrosim 2019.1.0515

**Comment by smustafa3** [comment]
?

**Comment by mcgratta** [comment]
You should not open up an issue and discussion thread. One or the other.
