### ISSUE TITLE
Incident Heat Flux and Radiative Heat Flux

### ISSUE THREAD

**Issue by jralbrecht27** [firemodels/fds#7444]
Having an issue with the incident heat flux and radiative heat flux results.  I am getting very different results by running the same file with all of the same text input in the pyrosim 2018.1.0417 version vs. the new version 2019.1.0515.   Resulting heat flux values for the 2018 seem appropiate based off of hand calc and using NRC calculator.  2019 results seem very low and shows a low indicent heat flux in the smokeview viewer.  

Results of the smokeview viewer are attached.
Model shown is a crude pool fire on top of a tank. 

Confirmed with pyrosim that the inputs are all the same, HRR plot is teh same, radiative fraction is the same.  

![2019 Version Incident Heat flux](https://user-images.githubusercontent.com/52085355/59947890-7564ce00-943c-11e9-881f-636f6198ef71.JPG)
![2019 Version Text File](https://user-images.githubusercontent.com/52085355/59947891-7564ce00-943c-11e9-99a0-97c7b113dc52.JPG)
![2018 Version Incident Heat flux](https://user-images.githubusercontent.com/52085355/59947892-7564ce00-943c-11e9-99b1-ee983e98bbaa.JPG)
![2018 Version Text File](https://user-images.githubusercontent.com/52085355/59947893-7564ce00-943c-11e9-8da7-b812cc240f0f.JPG)

**Comment by mcgratta** [comment]
Look in the _hrr.csv file. Are the HRR and Q_RADI columns in both cases similar? What is the -Q_RADI/HRR, approximately?

**Comment by Er9y714** [comment]
If I am not mistaken, the time shows 5 second. At this early stage of the fire (and simulation) the results might not be meaningful to be compared. I would wait at least 30 s or 1 min and check if the Q is the same at given time. Ideal would be the steady state instead of growing fire.

**Comment by mcgratta** [comment]
Do you want to close this issue? Do you still see a significant difference in heat flux?
