### ISSUE TITLE
SMOKEVIEW crashing on startup - Error in plot3d data in .smv file

### ISSUE THREAD

**Issue by SFC-CA** [firemodels/fds#7454]
Hi, 

I had an issue on one of my models where smokeview would not even start. 

I can't share the model input file due to confidentiality and I haven't yet tried replicating the error with a small file, but I have identified the lines in the .smv file that were causing the crash. I am assuming that knowing this should give you a good idea of where to look in the source for what might cause this error, if that is where the problem lies. 

I have pasted at the end an example of the incorrect .smv lines. The new info for a PL3D line was being written before the end of the file, specifically after the second V of the V-VEL line of the last written entry. It would also write the start of the new PL3D data up until the line "temp" and then write the the whole correct new PL3D info. It did this for only about the first 80% of the entries and then began writing correctly again. At the end of the file was the remainder of PL3D line that had been written over.

Some other information: I have been running a various versions of this model, with the only difference being slightly different geometries and this problem has not occurred on any others. I am using FDS v6.7.1 on Sabalcore, a cloud computing service which I think is running CentOS 6.9.

 V-VPL3D   360.01     1
 T80_1_0001_00000360_01.q
 TEMPERATURE
 temp
 PL3D   360.00     1
 T80_1_0001_00000360_00.q
 TEMPERATURE
 temp
 C
 U-VELOCITY
 U-VEL
 m/s
 V-VELOCITY
 V-VEL
 m/s
 W-VELOCITY
 W-VEL
 m/s
 SOOT VISIBILITY
 VIS_C0.9H0.1
 m

***The text below was at the end of the file

EL
 m/s
 W-VELOCITY
 W-VEL
 m/s
 SOOT VISIBILITY
 VIS_C0.9H0.1
 m

**Comment by SFC-CA** [comment]
I should add, that when I corrected the problem lines, smokeview executed as per normal

**Comment by gforney** [comment]
I can fix smokeview so that it doesn't crash (with the side effect it will ignore the PLOT3D entry that was 'malformed') but think the real problem is why incorrect info is showing up in the .smv file

**Comment by gforney** [comment]
try smokeview posted here to see if your case crashes (before editing by hand your .smv file)
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by SFC-CA** [comment]
Hi Glenn,

I tried the win64 version you linked but smokeview still failed to start up for that one particular file. I can't install anything on the cloud computers so I have just run it on my computer, but the original issue occurred on both systems anyway.

Another problem I noticed with the file after I edited it to correct the PL3D lines, one of the SLCF only ran for 50 seconds when there should be data for about 1500s. So I guess there is more to it than just the PLOT3D parts. 

I've attached the unedited smokeview file below, though note that I have changed the TITLE entry for confidentiality. 

I've attached a screen shot of the console output of running smokeview on that file below.

This is the first time that this issue has ever come up for me and it is not doing it with any other of the near identical models I have been working with. Sorry for throwing you a curveball but thought you'd want to know.

[T80_1.zip](https://github.com/firemodels/fds/files/3337408/T80_1.zip)


![Screenshot (15)](https://user-images.githubusercontent.com/52268149/60314345-e48a7700-9994-11e9-93b9-138a73f5301a.png)

**Comment by gforney** [comment]
try smokeview posted here.  it should fix the startup crash.  don't know what the .smv file was corrupted.  either fds is outputting data to the .smv file in the wrong order or there is somethign wrong with the cluster you are using.  Exactly how are you running your case.  Do your compute nodes use one home directory or a home directory for each node?

**Comment by gforney** [comment]
here is the link to smokeview
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharin

**Comment by SFC-CA** [comment]
Hi Glenn,

That version opens the file without crashing.

I am not 100% on what the setup is on Sabalcore. My understanding is that with this particular model it should all be running on one machine. I have 3 meshes and are running 4 threads per mesh, for a total of 12 processes (excuse me if I use the incorrect terminology). The machines that I am running on have at least 12 cores per node so it could run on one machine. There is usually enough available machines with 12 free cores anyway. In this case, it should just be using 1 home directory, I would think. The way Sabalcore works is I just specify the number of threads/mesh and they sort out the rest. There is the possibility that it might have been split between machines, but I don't know how I would check if that were the case. 

Sorry if that is not very helpful. Given that I have never experienced this problem before I would assume it would be a cluster problem.
