### ISSUE TITLE
Ctrl logic issue when spatial statistic is set to mean

### ISSUE THREAD

**Issue by AndrewCFD** [firemodels/fds#7470]
Hello

I have been trying to activate an object based on some spatial statistics, however the function does not appear to work when spatial statistic is set to mean, only max.

I have attached an example fds code (test.txt as that was the only format i could upload)

In this code there are 2 lines on 30 and 31.  The code on line 30 works as the object appears.  If i comment out this line and instead enable line 31 the object does not appear

Thanks

[test.txt](https://github.com/firemodels/fds/files/3367637/test.txt)

**Comment by rmcdermo** [comment]
This looks like it is working with the latest source.  With attached input file, I see the two images below, the OBST appears at the time when the mean temperature reaches 60 C.

[test.fds.txt](https://github.com/firemodels/fds/files/3370255/test.fds.txt)

![Screen Shot 2019-07-08 at 5 11 06 PM](https://user-images.githubusercontent.com/4418497/60843120-c5b18f00-a1a3-11e9-9bb3-e10e254cc9ac.png)

![Screen Shot 2019-07-08 at 5 11 20 PM](https://user-images.githubusercontent.com/4418497/60843125-ca764300-a1a3-11e9-9a29-50a531a8f618.png)

**Comment by AndrewCFD** [comment]
Thanks for taking a look.  Are you using v6.7.1 or a pre-release version to test in as that was the version used to run the case.

**Comment by rmcdermo** [comment]
I was using latest source code, so pre-release.  If you cannot compile, then you will have to wait until the next release, which should be soon.

I'll try a work around with 6.7.1 and report back.

**Comment by drjfloyd** [comment]
Worst case, as a work around you could define a series of DEVC in that volume and then use the CTRL functions for summing and dividing to compute the mean.

**Comment by rmcdermo** [comment]
Jason, I thought this would do the trick, and it does at least give an initial state of F for the OBST, but then does not trip at 60 C.  Can you see if you can come up with a solution from this point that works with 6.7.1?

[test2.fds.txt](https://github.com/firemodels/fds/files/3373310/test2.fds.txt)

**Comment by drjfloyd** [comment]
ANY is logical control function. It only operates on the logical state of its inputs (i.e. the state of the DEVC and not the value of the device).  I think the work around in this case is my previous suggestion of define a series of DEVC in that volume and then use the CTRL functions for summing and dividing to compute the mean. The SETPOINT would then be placed on the dividing CTRL function.  If you wanted to output the value you would need a CONTROL VALUE device.

**Comment by rmcdermo** [comment]
OK, I was playing with other CONTOL VALUE devices, but it seems the bug really is in the way the means are interacting with CTRL.  So, only single point values seem to work.  As Jason suggested, the sum/divide strategy roughly works.  In this input file I've only used 9 points (8 vertices of the box plus one point in the middle).  This does not give exactly the same time as the mean version with latest source, but it is close.  You can try adding more points to see it this helps.  Else, stay tuned for next maintenance release.

[test3.fds.txt](https://github.com/firemodels/fds/files/3373735/test3.fds.txt)

**Comment by AndrewCFD** [comment]
Thanks for your help.  I'm happy to implement a work around until then, but if its already been fixed in a future release then thats great.

**Comment by rmcdermo** [comment]
Please note that I had a mistake in the location of the DEVCs.  Should be this I think:

```
&DEVC ID='T1', XYZ= 8.3,0.2,1.0, QUANTITY='TEMPERATURE'/
&DEVC ID='T2', XYZ= 8.3,0.2,1.2, QUANTITY='TEMPERATURE'/
&DEVC ID='T3', XYZ= 8.3,4.4,1.0, QUANTITY='TEMPERATURE'/
&DEVC ID='T4', XYZ= 8.3,4.4,1.2, QUANTITY='TEMPERATURE'/
&DEVC ID='T5', XYZ=15.1,0.2,1.0, QUANTITY='TEMPERATURE'/
&DEVC ID='T6', XYZ=15.1,0.2,1.2, QUANTITY='TEMPERATURE'/
&DEVC ID='T7', XYZ=15.1,4.4,1.0, QUANTITY='TEMPERATURE'/
&DEVC ID='T8', XYZ=15.1,4.4,1.2, QUANTITY='TEMPERATURE'/
&DEVC ID='T9', XYZ=11.7,2.3,1.1, QUANTITY='TEMPERATURE'/
```
