### ISSUE TITLE
Monin-Obukhov similarity function error

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#7482]
There appears to be an issue with the function to calculate an atmospheric temperature ramp using Monin-Obukhov similarity theory.

Line 3251 of func.f90 references the global constant `RHOA`, but this constant is not initialized until after the call to the Monin-Obukhov function, so it always has a value of zero here, leading to an incorrect temperature ramp.

The issue can be seen in the attached input. A very large M-O length (neutral atmosphere) should tend towards the adiabatic lapse rate (a decrease of ~10 &#176;C per 1000 m of elevation for dry air). This is not true with the current code (but works if `RHOA` is replaced by a constant 1.2, for example)

[Input_obk_test.txt](https://github.com/firemodels/fds/files/3418734/Input_obk_test.txt)

**Comment by rmcdermo** [comment]
Thanks, Eric.  We'll take a look.

**Comment by mcgratta** [comment]
Try it now and see if everything works.

**Comment by ericvmueller** [comment]
Yup - I'm now getting a temperature profile with the trend I would expect.
Thanks!

**Comment by mcgratta** [comment]
Thanks for tracking this down. I forgot that we don't actually compute RHOA until all the species and combustion stuff is processed.
