### ISSUE TITLE
PID DEVC not workingwhen restarting

### ISSUE THREAD

**Issue by oriolrios** [firemodels/fds#7488]
When restarting a simulation that used FUNCTION_TYPE='PID'  options (temporal integration in this case) the integrated value is reseted to zero.

I attach a minimal example. 
To reproduce the case, the simulation must be stopped after 10s and restarted .

********************************************************************************

*******************************  FILE HEADER ***********************************
&HEAD CHID='PID_DEVC_bug', TITLE = 'PID_DEVC_bug'/

****************************** SIMULATION TIME *********************************
&TIME T_END=20/

***************************** OUTPUT PARAMETERS ********************************
&DUMP MASS_FILE=.false., DT_MASS=1, DT_RESTART=5 /

************************** MISCELANEOUS PARAMETERS *****************************
&MISC RESTART=.false./

**************************** MESH PARAMETERS ***********************************
&MESH ID='MESH_01', IJK=20,10,10, XB=0, 2, 0,1, 0,1/
&MESH ID='MESH_02', IJK=10,30,10, XB=0, 1, -3,0, 0,1/

************************** SPECIES PARAMETERS **********************************

&SPEC ID='PE', FORMULA='C2H4' / Only PE

&SPEC ID='NITROGEN',LUMPED_COMPONENT_ONLY=.TRUE./
&SPEC ID='OXYGEN',LUMPED_COMPONENT_ONLY=.TRUE./
&SPEC ID='CARBON DIOXIDE',LUMPED_COMPONENT_ONLY=.TRUE./
&SPEC ID='CARBON MONOXIDE',LUMPED_COMPONENT_ONLY=.TRUE./
&SPEC ID='WATER VAPOR',LUMPED_COMPONENT_ONLY=.TRUE./
&SPEC ID='AIR',SPEC_ID='NITROGEN','OXYGEN',VOLUME_FRACTION=0.789,0.210,BACKGROUND=.TRUE./

&SPEC ID='PRODUCTSCab',
  SPEC_ID='CARBON MONOXIDE','CARBON DIOXIDE','WATER VAPOR',
  VOLUME_FRACTION=0.01004,0.68602,0.030394/

&SPEC ID='SOOT',
        FORMULA='C0.9H0.1',
        AEROSOL=.TRUE.,
        MEAN_DIAMETER=0.3E-6,
        MASS_EXTINCTION_COEFFICIENT=8700/

************************** REACTION PARAMETERS *********************************

&REAC ID='REAC_PE',
  FUEL='PE',SPEC_ID_NU='PE','AIR','PRODUCTSCab','SOOT',
  NU=-1,-3.62012,4.21214,0.12800,
  CHECK_ATOM_BALANCE=F,
  REAC_MASS_ERROR=0.3,
  HEAT_OF_COMBUSTION=46400./
  
 &SURF ID='FIRECable',
      SPEC_ID='PE',
      MASS_FLUX=1/
	  
 
&OBST ID='Fire obstacle', XB=0.3,0.4, 0.3,0.4,0.1,0.2, SURF_IDS='FIRECable','INERT','INERT'/
&OBST ID='FLOOR',XB=0, 2, 0,1, 0,0.1, SURF_ID='INERT'/
&VENT ID='CEIL', XB=0, 2, 0,1, 1,1,  SURF_ID='OPEN'/
&OBST ID='WALL', XB=0, 0.1, 0,1, 0,1, SURF_ID='INERT'/
&OBST ID='WALL', XB=1.9,2.0, 0,1, 0,1,SURF_ID='INERT'/
&OBST ID='WALL', XB=0,2.0, 0.9,1, 0,1,SURF_ID='INERT'/

******************* DEVC OUT OF DOMAIN CHECKS ***********************
&DEVC ID='MF_TOP_SOOT_PID', XB=0, 2, 0,1, 1,1, QUANTITY='MASS FLUX WALL', SPEC_ID='SOOT', IOR=-3, SURF_ID='OPEN', STATISTICS='SURFACE INTEGRAL'/
&CTRL ID='PID_MF_SOOT_TOP', FUNCTION_TYPE='PID', INPUT_ID='MF_TOP_SOOT_PID', PROPORTIONAL_GAIN=0, DIFFERENTIAL_GAIN=0, INTEGRAL_GAIN=1/
&DEVC XYZ=0.5,0.5,0.5, ID='MASS_TOP_SOOT_pint', QUANTITY='CONTROL VALUE', CTRL_ID='PID_MF_SOOT_TOP', UNITS='kg'/

&DEVC XB=0, 2,  0,1, 0,1, QUANTITY='SURFACE DEPOSITION', ID='DEPO_1',  SPATIAL_STATISTIC='SURFACE INTEGRAL', SURF_ID='INERT', SPEC_ID='SOOT' /
&DEVC XB=0, 2,  0,2, 0,1, QUANTITY='SURFACE DEPOSITION', ID='DEPO_2',  SPATIAL_STATISTIC='SURFACE INTEGRAL', SURF_ID='INERT', SPEC_ID='SOOT' /
&DEVC XB=0, 2, -5,5, 0,1, QUANTITY='SURFACE DEPOSITION', ID='DEPO_3',  SPATIAL_STATISTIC='SURFACE INTEGRAL', SURF_ID='INERT', SPEC_ID='SOOT' /

&TAIL /

Here the graph of integrated mass flux.

![MF](https://user-images.githubusercontent.com/9115914/61728454-870bff00-ad75-11e9-827d-d8c0215110f5.png)

Thanks!

Oriol

**Comment by drjfloyd** [comment]
We aren't writing the integration value to the restart file. I'll fix.

**Comment by drjfloyd** [comment]
Just pushed up a fix.

**Comment by oriolrios** [comment]
Thanks!
Fix checked and varified. It works now. 
Thanks Jason!
