### ISSUE TITLE
Completely useless version for Mac OSX mojave

### ISSUE THREAD

**Issue by Stefanomtt** [firemodels/fds#7506]
Completely useless version for latest Mac OSX Mojave.

Impossible to find the location of .bashrc or .bashrc_profile files to edit. A lot of errors collected if you attempt to launch disregarding the "installation instructions" given

Impossible to use ver. 6.7.1 until the installation instructions will be updated considering also latest OSX versions

**Comment by parsipal** [comment]
Hi Stefanomtt,
I use FDS on Mojave (10.14.6) and works well.
1) Try to use manual installation (see at https://github.com/firemodels/fds/wiki/Installing-and-Running-FDS-under-Mac-OS-X )
2) Don't use .bashrc or .bashrc_profile BUT ".bash_profile" in terminal.
3) Update SMV (last is 6.7.7)

Gio

**Comment by Stefanomtt** [comment]
Thanks Gio,
I intended ".bash_profile" (and not .bashrc_profile, it was my mistake).
My problem is that I cannot find the ".bash_profile" file !

**Comment by parsipal** [comment]
Enter in terminal (in home directory) and type: ls -la
.bash_profile is a hidden file ( -la :help you to see hidden files)

Gio

**Comment by Stefanomtt** [comment]
Finally, I succeeded! I have no .bash_profile file, but only the .bashrc file
I would like to share the procedure:

1. From the Finder, find the Macintosh HD or something similar folder (may be the root folder, if I remember well)

2. Make visible the hidden file (by Shift+Cmd+. in my case)

3. You may spot an "etc" folder alias. Double click it. The .bashrc is in that folder. The complete path is: /private/etc/ (see the lowest part of the Finder window)

4. Change the privileges to /private/etc/ folder: from the /private folder select the etc folder and from the FILE menu of the Finder choose "Get Info" (Cmd I). On the Info window change the privileges for Everyone to "read and write" (you can find privileges in the lowest part of the Info window)

5. Go into /private/etc/ and change the privileges in the same way for the file .bashrc
NOW YOU CAN EDIT .bashrc file

6. By TextEdit, Edit the .bashrc file adding the lines needed (for instance: "source /Applications/FDS/FDS6/bin/FDS6VARS.sh" if you have chosen to install FDS in that folder).

7. Save the changes and exit

8. Reset the privileges for .bashrc and etc folder (see previous points 4 and 5)

9. Restart OS X

10. When restarted, open Terminal and type FDS (return)

Now the system should find and run FDS

**Comment by marcosvanella** [comment]
@Stefanomtt, welcome. The issue tracker is to report bugs in the code. OS questions like "where is / why I can't find my startup file" can be posted on the FDS-SMV google forum: 

https://groups.google.com/forum/#!forum/fds-smv

You should not be changing OS files unless you know what you are doing. What you have changed are global settings.
OSX does not create a user startup file by default, some of the programs you install will do that for you. If you don't have one you just create it in /Users/YOURUSERNAME/.bash_profile, and follow the installer instructions. Make sure to close and open another terminal for the startup file to be executed and your FDS environment variables set.
