### ISSUE TITLE
fds2ascii maximum number of files

### ISSUE THREAD

**Issue by YavorPanev** [firemodels/fds#7508]
I am currently working on a project where I transfer FDS data to a Unity engine for the purpose of realistic smoke movement visualization.

For the purpose I am extracting PLot3D data from 12 meshes at low intervals every 5 s. I have successfully created a batch file to automate the process.

However, it seems that the fds2ascii module does not process any data after 210 s. These plot3d files exist and  can be viewed in smokeview but they do not appear in the list of extraction files in the fds2ascii program. Upon closer inspection of the fortran code it seems the reason for this is that FILE_DIM variable is hard coded to 500, i.e the loop that searches for .q files does not continue past the first 500 entries. Can this be increased to perhaps 5000-10000 ?

I tried to do it my self but could not compile the program correctly for Windows (I tried using gfortran).

**Comment by gforney** [comment]
Gfortran on what platform?

**Comment by YavorPanev** [comment]
Windows 10

**Comment by drjfloyd** [comment]
As a work around have your script copy 500 q files to a subfolder, process them, delete them, and repeat.

**Comment by gforney** [comment]
update your repo.   I added a makefile entry and build script for gnu_win_64 .   I'm able to build fds2ascii with gfortran 8.1.0 installed on my windows 10 system (check your version of gfortran , earlier versions  of gfortran may not  support some of the fortran features used in fds2ascii)

**Comment by YavorPanev** [comment]
@gforney Thank you very much for your help. Can you please explain how to use the makefile entry to compile the program? I believe this is where I was getting the things wrong.

@drjfloyd Thank you for your response. I tried it but unfortunately it seems that the counter is connected to the order of the files as indexed in the *smv file. I  copied all timestep files from t=200 to t =300 in a subfolder and then running fds2ascii script. However the script displayed only the files between 200 s to 210 s with the corresponding index identical to the index of the base case where I was looking at all *.q files.

**Comment by gforney** [comment]
1. Cd into directory fds\Utilities\fds2ascii\gnu_win_64
2. Type make_fds2ascii
