### ISSUE TITLE
Numerical instability in Tunnel fire simulation FDS 2012

### ISSUE THREAD

**Issue by usmansh0786** [firemodels/fds#7510]
Hi all experts,
I modelled a simple tunnel with enclosed entrances : a fire is placed at center, but after sometime fds simulation terminates as it shows there is a numerical instability. could you please help me how to solve the problem for enclosed tunnel. i am attaching

[New Text Document.txt](https://github.com/firemodels/fds/files/3466691/New.Text.Document.txt)

 .OUT file

**Comment by rmcdermo** [comment]
Please try your case with the latest code.  Also, there is a section in the user guide on trouble shooting instabilities, best to start there.  Unless you pinpoint a bug, this discussion should take place in the discussion forum, not the Issues page.  Thanks.
