### ISSUE TITLE
Smokeview crashes by loading humans

### ISSUE THREAD

**Issue by bhoepperger** [firemodels/fds#7513]
I learned from the platform that the current version of FDS 6.7.1 comes with SMV 6.7.5 is not showing humans but version SMV 6.7.7 should.
So I installed SMV on my OpenSuse 15.1 and Windows10 system. Both computer give me the same crash. My settings are for Austria so I also tried to change the number format to US standard but didn't work. I can load smoke, slice files etc but not humans.
When I want to analyse my simulation results with the old version on a seperate computer OpenSuse 13.1 and FDS 6.1.2 with SMV 6.1.12 it works.

Does somewhere have an idea why I my new systems crashes?

**Comment by rmcdermo** [comment]
Please submit a very simple test case and we will take a look.

**Comment by gforney** [comment]
Attach a simple test case that illustrates the problem and I'll take a look.

**Comment by bhoepperger** [comment]
That is my case - it starts with no problems and computes the evac files. Everything looks good, but I can't load the humans in SMV

[U6Niederhofstrasse.zip](https://github.com/firemodels/fds/files/3472331/U6Niederhofstrasse.zip)

**Comment by bhoepperger** [comment]
sorry wrong file - the file before works with 6.1.2 - I had to change tab into space for FDS 6.7.1
[U6Niederhofstrasse.zip](https://github.com/firemodels/fds/files/3472345/U6Niederhofstrasse.zip)

**Comment by gforney** [comment]
as a wise one once said - no good deed goes unpunished.  recently I made changes to smokeview to speed up particle loading.  this broke evac file loading .  try smokeview posted at link below and let me know if this fixes the problem.

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by bhoepperger** [comment]
The new release  6.7.7.81 works - thank you!
can you please poste also the linux verion

**Comment by gforney** [comment]
I've posted smokeview 6.7.8 with these corrections at link below
https://pages.nist.gov/fds-smv/downloads.html

**Comment by gforney** [comment]
Is it working for you now?

**Comment by bhoepperger** [comment]
Yes thanks, installed 6.7.8 on windows and linux and Problem is solved
Thanks!

**Comment by gforney** [comment]
Good. I'll close issue
