### ISSUE TITLE
Combined SPATIAL_STATISTIC and TEMPORAL_STATISTIC does not generate output

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7529]
The attached does not generate output for the devices with combined spatial and temporal stats.  This is not the simplest of cases, but it runs on a single mesh in just a couple minutes.

[rbc_test.fds.txt](https://github.com/firemodels/fds/files/3502503/rbc_test.fds.txt)

**Comment by mcgratta** [comment]
Which combo of stats is not working?

**Comment by rmcdermo** [comment]
Per the attached input file:
```
&DEVC XB=-0.5920,0.5920,-0.5920,0.5920,0.000131040182142,0.000133040182142, QUANTITY='TEMPERATURE', QUANTITY2='TEMPERATURE', SPATIAL_STATISTIC='MEAN', TEMPORAL_STATISTIC='COV', STATISTICS_START=2, ID='tt-1' /
```
I first noticed the problem in the larger case where I had not specified the "STATISTICS_START", assuming it should be set to half the (T_END-T_BEGIN) per the _line devices.  The the values remain zero for the output after STATISTICS_START and all the way to the end of the simulation.

**Comment by rmcdermo** [comment]
I played with it a little more, looks like the main issue is `SPATIAL_STATISTIC='MEAN'`.  Both `'VOLUME MEAN'` and `'MASS MEAN'` at least give output.  Note that the volume is small because it is a plane.  I've just added an eps to either side of the cell center for the device XB.

Here is a simplified test case with just a single DEVC.

[rbc_test.fds.txt](https://github.com/firemodels/fds/files/3503226/rbc_test.fds.txt)

**Comment by rmcdermo** [comment]
Couple more observations:
1. Without TEMPORAL_STATISTIC, the SPATIAL_STATISTIC='MEAN' seems to work fine.
2. The user guide gives the impression (as I read it) that the default behavior of STATISTICS_START is (as in a line device) STATISTICS_START=0.5*(T_END-T_BEGIN).  But it seems to be STATISTICS_START=DT_DEVC.

**Comment by rmcdermo** [comment]
I'm pretty convinced that we can't do COV correctly averaged over a plane with the current setup.  To do this right, you need to have the planar means converged before you even start gathering stats for covariance on that plane.
