### ISSUE TITLE
Slice - the temperature above the fire source

### ISSUE THREAD

**Issue by w-tx** [firemodels/fds#7544]
I have a question.Passing through the center of the fire,Why is the slice temperature difference in different directions so large?The two slices are perpendicular to each other and pass through the center of the fire.I hope to get answers, thanks！
![1](https://user-images.githubusercontent.com/54468638/63635237-1d905080-c693-11e9-8155-118adf76aca2.JPG)
![2](https://user-images.githubusercontent.com/54468638/63635238-1ec17d80-c693-11e9-9ea4-a5644d452347.JPG)

**Comment by rmcdermo** [comment]
This belongs on the discussion forum.  It is not a bug.
