### ISSUE TITLE
Layer Height problem FDS 6.7.1

### ISSUE THREAD

**Issue by Spitzelchen** [firemodels/fds#7563]
Hello,

I modelled an easy room with 7,5 m x 7,5 m x 4 m and analysed the layer height in 5 different positions.

I simulated the same FDS-Input File with FDS 6.7.1 and FDS 6.6.x

The results with FDS 6.7.1 show artifacts at the beginning of the Simulation. When there is absolutely no smoke in the room, the layer height runs crazy. With FDS 6.6x it shows fine results.

Where is the Problem?

Find the fds attached. 

untitled.fds
Generated by PyroSim - Version 2019.1.0508
30.08.2019 08:50:35

&HEAD CHID='untitled'/
&TIME T_END=600.0/
&DUMP RENDER_FILE='untitled.ge1', COLUMN_DUMP_LIMIT=.TRUE./

&MESH ID='Mesh01', IJK=75,75,41, XB=0.0,7.5,0.0,7.5,0.0,4.1/

&REAC ID='PROPYLENE',
      FYI='FM SNL FDS5 Validation',
      FUEL='REAC_FUEL',
      FORMULA='C3H6',
      SOOT_YIELD=0.02, /

&DEVC ID='LAYER->HEIGHT', QUANTITY='LAYER HEIGHT', XB=1.0,1.0,1.0,1.0,0.0,4.0/
&DEVC ID='LAYER->LTEMP', QUANTITY='LOWER TEMPERATURE', XB=1.0,1.0,1.0,1.0,0.0,4.0/
&DEVC ID='LAYER->UTEMP', QUANTITY='UPPER TEMPERATURE', XB=1.0,1.0,1.0,1.0,0.0,4.0/
&DEVC ID='LAYER01->HEIGHT', QUANTITY='LAYER HEIGHT', XB=2.0,2.0,2.0,2.0,0.0,4.0/
&DEVC ID='LAYER01->LTEMP', QUANTITY='LOWER TEMPERATURE', XB=2.0,2.0,2.0,2.0,0.0,4.0/
&DEVC ID='LAYER01->UTEMP', QUANTITY='UPPER TEMPERATURE', XB=2.0,2.0,2.0,2.0,0.0,4.0/
&DEVC ID='LAYER02->HEIGHT', QUANTITY='LAYER HEIGHT', XB=3.0,3.0,3.0,3.0,0.0,4.0/
&DEVC ID='LAYER02->LTEMP', QUANTITY='LOWER TEMPERATURE', XB=3.0,3.0,3.0,3.0,0.0,4.0/
&DEVC ID='LAYER02->UTEMP', QUANTITY='UPPER TEMPERATURE', XB=3.0,3.0,3.0,3.0,0.0,4.0/
&DEVC ID='LAYER03->HEIGHT', QUANTITY='LAYER HEIGHT', XB=4.0,4.0,4.0,4.0,0.0,4.0/
&DEVC ID='LAYER03->LTEMP', QUANTITY='LOWER TEMPERATURE', XB=4.0,4.0,4.0,4.0,0.0,4.0/
&DEVC ID='LAYER03->UTEMP', QUANTITY='UPPER TEMPERATURE', XB=4.0,4.0,4.0,4.0,0.0,4.0/
&DEVC ID='LAYER04->HEIGHT', QUANTITY='LAYER HEIGHT', XB=5.0,5.0,5.0,5.0,0.0,4.0/
&DEVC ID='LAYER04->LTEMP', QUANTITY='LOWER TEMPERATURE', XB=5.0,5.0,5.0,5.0,0.0,4.0/
&DEVC ID='LAYER04->UTEMP', QUANTITY='UPPER TEMPERATURE', XB=5.0,5.0,5.0,5.0,0.0,4.0/

&SURF ID='Burner',
      COLOR='RED',
      HRRPUA=300.0,
      TMP_FRONT=300.0/

&OBST ID='Obstruction', XB=0.0,0.1,0.1,7.5,0.0,4.0, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=5.9,6.9,5.9,6.9,0.0,0.1, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=0.0,7.5,0.0,0.1,0.0,4.0, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=0.1,7.5,7.4,7.5,0.0,4.0, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=7.4,7.5,0.1,7.4,0.0,4.0, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=0.0,7.5,0.0,7.5,4.0,4.1, SURF_ID='INERT'/ 

&HOLE ID='Hole', XB=0.2,1.2,-0.1,0.2,-0.01,2.0/ 

&VENT ID='Vent01', SURF_ID='Burner', XB=5.9,6.9,5.9,6.9,0.1,0.1, SPREAD_RATE=7.06E-3, XYZ=6.4,6.4,0.1/ 

&TAIL /

[untitled.txt](https://github.com/firemodels/fds/files/3558926/untitled.txt)

Bastian

**Comment by mcgratta** [comment]
Your input file has no openings to the outside. The HOLE does not cut a hole in the exterior solid wall. Thus, the temperature and pressure in the compartment rise uniformly, causing problems for the determination of the layer height. 

As for the layer calculation, it is always true that the layer is not well-defined early in the simulation. I made a small change to prevent spurious values, but I cannot prevent the algorithm from choosing finding a non-physical height when there is no layer.

The fact that 6.6.x does not show the spurious result is probably just a coincidence. Do not rely on the layer height until there is a clear distinction in the upper and lower temperatures.

**Comment by Spitzelchen** [comment]
Thanks for your reply. Of course I need to open the boundaries, but for this case the same result appears. Please run it with the old and the new Version, with open boundaries. With the new Version the layer height is oscillating in the first 30 seconds between 0,5m and 4,5 m although the room is just 4m high and there is no smoke at all. With the older versions it stays fine at 4m. Until this version this mistake never appeared. And I don't think that this is a coincidence. 

Here is the layer height for the two. 
new FDS Version (oscillating although there is no smoke):
![image](https://user-images.githubusercontent.com/54703632/64256191-374b5680-cf23-11e9-8f37-64cc19a9759c.png)


old FDS Version (perfectly at the Hmax):
![image](https://user-images.githubusercontent.com/54703632/64256239-5518bb80-cf23-11e9-96a5-b5b8f6574edd.png)

Thank you very much!

**Comment by rmcdermo** [comment]
We will have to bisect.  Give us some time.

**Comment by rmcdermo** [comment]
Kevin,
I did a bisect and found this:
```
PN108013:fds rmcdermo$ git bisect bad
7ad5bf4834518a08a05e1735942dbecf38f25d5d is the first bad commit
commit 7ad5bf4834518a08a05e1735942dbecf38f25d5d
Author: mcgratta <mcgratta@gmail.com>
Date:   Tue Nov 6 14:11:18 2018 -0500

    FDS Source: Allow LAYER HEIGHT calculation to cross meshes
```
I'll leave to you to see if there is an obvious fix.  I'd say it's more important that we can handle multiple meshes in the vertical direction.

**Comment by mcgratta** [comment]
I had removed a line of code that would set the layer height to the ceiling height if the difference in layer temperature were less than 5 C. This caused some problems for cases where the layer was not very hot. I restored this constraint, but now the criterion is 1 C.
