### ISSUE TITLE
DEVC reports incomplete flowrate on VENT split between meshes

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#7565]
Suppose a VENT is defined such that it is split between multiple meshes. This works.

Now define a DEVC across the same surface definition, and report QUANTITY='VOLUME FLOW' on it. When I try this (in FDS 6.7.1 on Linux), the reported flowrate is from only one of the meshes. In the case I tried, this applied to both a VENT with specified velocity, and a VENT specifed as 'OPEN'.

One workaround is to locate the DEVC a small distance inside the mesh. Alternatively, create multiple flow monitors, such that each is entirely within a single mesh. These are not convenient.

Here is an example:

```
&HEAD CHID='bug1', TITLE='bug1'  /
// Run this in parallel ("mpiexec -n 2 fds bug1.fds")
// and see whether outflow==outflowNear.
// The DEVC definition for outflow straddles two mesh blocks.
// Actually, parallel is not needed to see the error in FDS 6.7.1.
//   (Revision         : FDS6.7.1-0-g14cc738-master on Ubuntu)

&TIME T_END=10      /
&DUMP NFRAMES = 10 /

&MESH ID='mesh-lo-x' IJK=6,10,40, XB= 0.0,0.6, 0.0,1.0, 0.0,4.0, MPI_PROCESS=0 /
&MESH ID='mesh-hi-x' IJK=4,10,40, XB= 0.6,1.0, 0.0,1.0, 0.0,4.0, MPI_PROCESS=1 /

&VENT XB= 0.0,1.0, 0.0,1.0, 4.0,4.0, SURF_ID='extract' /
&SURF ID='extract', VEL=2.0, COLOR='RED', RAMP_V='Extract-ramp' /
&RAMP ID='Extract-ramp', T=0,     F=0.1 /
&RAMP ID='Extract-ramp', T=1,     F=1.0 /
&RAMP ID='Extract-ramp', T=10000, F=1.0 /
&DEVC XB= 0.0,1.0, 0.0,1.0, 4.0  ,4.0  , QUANTITY='VOLUME FLOW', ID='outflow', /
&DEVC XB= 0.0,1.0, 0.0,1.0, 3.999,3.999, QUANTITY='VOLUME FLOW', ID='outflowNear', /

&VENT XB= 0.0,1.0, 0.0,1.0, 0.0  ,0.0  , SURF_ID='OPEN'  /
&DEVC XB= 0.0,1.0, 0.0,1.0, 0.0  ,0.0  , QUANTITY='VOLUME FLOW', ID='inflow', /
&DEVC XB= 0.0,1.0, 0.0,1.0, 0.001,0.001, QUANTITY='VOLUME FLOW', ID='inflowNear', /
&DEVC XB= 0.0,0.6, 0.0,1.0, 0.0  ,0.0  , QUANTITY='VOLUME FLOW', ID='inflow-lo-x', /
&DEVC XB= 0.6,1.0, 0.0,1.0, 0.0  ,0.0  , QUANTITY='VOLUME FLOW', ID='inflow-hi-x', /

&SLCF PBY=  0.5 ,  QUANTITY='VELOCITY', VECTOR=.TRUE.,   / 

&TAIL /
```

Bug-free results would produce inflow == inflowNear == outflow == outflowNear == 2.0. I currently get inflow == inflow-lo-x == 1.2.

Thanks,
Ed

**Comment by mcgratta** [comment]
This is one of those "less than" vs "less than or equal to" problems. When your XB plane fell exactly on a boundary, it was not read properly. I fixed this, but in the meantime, assign your planes just inside the mesh, as you have done.

**Comment by obscureed** [comment]
OK, thanks for the bugfix and the workaround advice.

It seems to me that the fixed code is still vulnerable to rounding errors. These are probably not a problem for a normal definition of a &MESH, &VENT and &DEVC, because those commands all use the same input format for a coordinate. Rounding errors could show up when &MESH is created as part of a &MULT, for example. One way to deal with this would be diagnostic messages, rather than putting tolerances into the code -- I'll put in an enhancement request.

When I vary the split fraction f between lo-x and hi-x (so, f=0.6 in the example above), the fraction of area that is reported (by outflow and inflow) is consistently max(f,1-f). I don't see how that would happen due to random equality of DEVC's XB to the mesh or cell's coordinate limits -- it makes me suspect that there is something else going wrong as well. But, OK, we can test the current fix when it's released. Thanks again.
