### ISSUE TITLE
Where is simple_test.fds?

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7576]
There is an example case called `firemodels/fds/Verification/Fires/simple_test.fds` in the fds repo, but I cannot find it in the Examples folder of the release bundle.

**Comment by mcgratta** [comment]
What is the criteria for including a verification case in the Examples folder?

**Comment by mcgratta** [comment]
This issue came up today. Could we resolve it? I need to know which cases get included in the bundle.

**Comment by rmcdermo** [comment]
OK, I will add this to FDS_Cases.sh

**Comment by rmcdermo** [comment]
Kevin,

I ran this case to be sure all is ok before adding it back.  The case gives a CLIP warning right away.  I think this is not something we want to have happen for a new user.  I set the minimum density to 0.01*RHOA and still get a warning.

If you set SIMULATION_MODE='LES' and CHECK_HT=T then you do not get the warning.  But these are also not "simple" things for new user.

How do you want to proceed?

**Comment by mcgratta** [comment]
We probably hit the lower density boundary routinely, especially when
initially the time step is relatively large. We should probably look at all
the verification cases to see what's hitting the lower density. My guess is
alot.

>

**Comment by mcgratta** [comment]
I checked last night's firebot output. There are a fair number of cases
where the lower density bound is hit.

>

**Comment by mcgratta** [comment]
This is the current logic to set the time step:
```
IF (DT<=0._EB) THEN
   VEL_CHAR = 0.2_EB*SQRT(10._EB*(ZF_MAX-ZS_MIN))
   ...
   DT = CFL_MAX*CHARACTERISTIC_CELL_SIZE/VEL_CHAR
ENDIF
```
The factor of 10 in `VEL_CHAR` is gravity, 9.81 m/s2. The 0.2 is arbitrary. This is all tied to fire plumes, as I recall. One thing to try is to replace 0.2 with, say, 0.5, which makes the initial time step smaller and reduces the likelihood of hitting the density bound when the time step is being cut back too quickly. But we might want to then revisit the logic that would allow DT to rise above the initial DT for calcs that are not fire or plume related.

**Comment by rmcdermo** [comment]
I have never been a fan of `RESTRICT_TIME_STEP`.  I think our stability criteria work fine for plumes.  I think we can set the initial step to be small and it should adjust correctly.

**Comment by mcgratta** [comment]
I'll try that --- make the initial time step smaller but set `RESTRICT_TIME_STEP=F`

**Comment by drjfloyd** [comment]
I think this can be closed. The case was in the Examples folder for 6.7.9 and it runs OIK.
