### ISSUE TITLE
Running an example - server rejected credentials

### ISSUE THREAD

**Issue by Nelsonice** [firemodels/fds#7582]
Hi,

I fail to run an example with the below messages:

bstrap\service\service_launch.c (298): server rejected credentials
bstrap\src\hydra_bstrap.c (383): error launching bstrap proxy
mpiexec.c (1754): error setting up the boostrap proxies

how can I fix the problem? Thanks!

**Comment by rmcdermo** [comment]
Please submit question to the discussion forum.  Thanks
