### ISSUE TITLE
Thermally thick evaporation of a liquid droplet

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7595]
Jason,
I'm trying an exercise---to replicate water_evaporation_8.fds (Li and Chow) using the thermally thick (pyrolysis) model with a spherical geometry.  I understand there may be some hiccups in outputs, etc.  But Trettel's terminal velocity cases use the MATL approach for a moving sphere and this seems to work.  The problem I'm having is that the droplet seems to evaporate immediately.  I'm going to continue to work this, but I'm attaching the input file in case you have any suggestions.  Maybe I'm doing something dumb.  Thanks.

[Li_Chow_thermally_thick_droplet.fds.txt](https://github.com/firemodels/fds/files/3606281/Li_Chow_thermally_thick_droplet.fds.txt)

**Comment by drjfloyd** [comment]
When I run your case, I don't see the droplet evaporating immediately.  2 seconds in and it is still there (radius is at 89 um).

**Comment by rmcdermo** [comment]
Oops, I pushed up the input file with a specified mass transfer coefficient.  Delete that.

**Comment by drjfloyd** [comment]
I don't see a specified coefficient in the file you attached to your first comment.

&SURF ID           = 'MY DROPLET'
      MATL_ID      = 'WATER'
      COLOR        = 'BLUE'
      BACKING      = 'INSULATED'
      GEOMETRY     = 'SPHERICAL'
      THICKNESS    = 5.E-5
      TMP_INNER    = 10.
      CELL_SIZE_FACTOR = 0.1 /

&MATL ID                     = 'WATER'
      EMISSIVITY             = 0.95
      DENSITY                = 1000.
      SPEC_ID                = 'WATER VAPOR'
      NU_SPEC                = 1
      HEAT_OF_REACTION       = 2260
      CONDUCTIVITY           = 0.58
      SPECIFIC_HEAT          = 4.181
      BOILING_TEMPERATURE    = 100. /

&PART ID='droplet', SURF_ID='MY DROPLET',
      SAMPLING_FACTOR=1,
      QUANTITIES(1)='PARTICLE W'
      SECOND_ORDER_PARTICLE_TRANSPORT=T/

**Comment by rmcdermo** [comment]
OK, perhaps it was the shrinking of the time step that is helping.  In that file, DT is 0.001, which is a tenth that used in water_evap_8

**Comment by drjfloyd** [comment]
OK if I change the time step then it disappears quickly. 

I think the issue is that we compute the mass loss rate at the start of the time step. A small drop can change temperature quickly over a timestep, and that will have a significant effect on the average mass loss rate over the timestep. In the droplet routine we account for this by including a dY/dT term in the dm/dt equation. We don't do this for a "solid".

**Comment by rmcdermo** [comment]
OK, thanks.  If shrinking time step works, I'll be happy.

**Comment by rmcdermo** [comment]
Jason,
There are still some issues.  It looks like the RE_L, SHERWOOD, and H_MASS are way off between the two methods.  In working through this, I noticed this line of code in part.f90
```
SHERWOOD  = 2._EB + NU_FAC_GAS*SQRT(RE_L)*LOG(1._EB+B_NUMBER)/(Y_DROP-Y_GAS)
```
Should this use `SH_FAC_GAS` ?  Or do you want it to be the Nusselt factor in the mass transfer relation?

**Comment by drjfloyd** [comment]
yikes.  I fixed. Thanks.

**Comment by rmcdermo** [comment]
Jason,
I just pushed up code and input files that roughly work.  But as you can see, there are still issues with the thermally thick approach.  You can generate these plots with latest code by running data plot on water_evaporation_8.  The Li and Chow input file has half the time step, but there seems to be another issue.  My guess is that this is related to the heat transfer to the surface, which I am starting to sort out.  Just thought you might be interested.  If you have any suggestions, let me know.  Thanks.
[water_evaporation_8_d.pdf](https://github.com/firemodels/fds/files/3610695/water_evaporation_8_d.pdf)
[water_evaporation_8_z.pdf](https://github.com/firemodels/fds/files/3610696/water_evaporation_8_z.pdf)

**Comment by rmcdermo** [comment]
I went ahead and fixed, as I am in that part of the code right now.

**Comment by rmcdermo** [comment]
Jason,
I just pushed up a heat transfer model that should work with this Li and Chow input file.  I'm stuck trying to figure out why the result changes slope at about 5 s.  It does not seem to be a time step issue (I've run 2 orders of magnitude smaller DT).  I've tried to use the same heat and mass transfer models as for the droplet.  Can you have a look to see if I've missed anything obvious?  Thanks.

[water_evaporation_8.fds.txt](https://github.com/firemodels/fds/files/3623466/water_evaporation_8.fds.txt)
[Li_Chow_thermally_thick_droplet.fds.txt](https://github.com/firemodels/fds/files/3623467/Li_Chow_thermally_thick_droplet.fds.txt)

[water_evaporation_8_d.pdf](https://github.com/firemodels/fds/files/3623469/water_evaporation_8_d.pdf)
[water_evaporation_8_z.pdf](https://github.com/firemodels/fds/files/3623470/water_evaporation_8_z.pdf)

**Comment by drjfloyd** [comment]
FYI, At a conference this week.  

You have multiple temperature points over the radius for your drop vs. the single temperature for the liquid drop model. Have you looked at the time dependent temperature profile in the solid drop vs the liquid drop to see if something odd is happening?

**Comment by rmcdermo** [comment]
Thanks for the idea.  Yes, here is the surface temp vs. time.  Very slight difference make a large difference in the drop diameter.
[water_evaporation_8_t.pdf](https://github.com/firemodels/fds/files/3627784/water_evaporation_8_t.pdf)

**Comment by drjfloyd** [comment]
What happens if you make the conductivity very high so the temperature is always nearly uniform in the drop?

**Comment by rmcdermo** [comment]
In this set of plots, I've set the water conductivity to 100 W/m/K.  The thermally thick droplet has 10 cells along the radial direction.  I've set HEAT_OF_REACTION=2380 J/kg to match the value of HEAT_OF_VAPORIZATION at about 55 C from the water_evap_8.out file.  H_MASS=0.75 and H_HEAT=750 for both cases (constant).  Now it seems we are getting close...

[water_evaporation_8_t.pdf](https://github.com/firemodels/fds/files/3627858/water_evaporation_8_t.pdf)
[water_evaporation_8_d.pdf](https://github.com/firemodels/fds/files/3627859/water_evaporation_8_d.pdf)
[water_evaporation_8_z.pdf](https://github.com/firemodels/fds/files/3627860/water_evaporation_8_z.pdf)

**Comment by drjfloyd** [comment]
It is looking like the differences are due to the slight differences in temperature.

**Comment by rmcdermo** [comment]
One of the things to note is that we do not seem to have a way to RAMP the HEAT_OF_REACTION for LIQUID_PYROLYSIS.  I think the temperature depends mainly on the precise value of H_V used in the evaporation.  For the droplets, this comes from a lookup as a function of temperature.  How would you feel about adding a TMP RAMP for ML%H_R?

**Comment by rmcdermo** [comment]
Here's how things are looking now with computed values of H_MASS and H_HEAT for each model.  Still have CONDUCTIVITY set high on MATL.  Time step on thermally thick model is set to a tenth of the droplet model.

[water_evaporation_8_t.pdf](https://github.com/firemodels/fds/files/3628047/water_evaporation_8_t.pdf)
[water_evaporation_8_d.pdf](https://github.com/firemodels/fds/files/3628048/water_evaporation_8_d.pdf)
[water_evaporation_8_z.pdf](https://github.com/firemodels/fds/files/3628049/water_evaporation_8_z.pdf)

**Comment by drjfloyd** [comment]
I think that is a great idea. We already have a ramp available for specific heat. Having a heat of reaction ramp would good.

**Comment by drjfloyd** [comment]
Add HEAT_OF_REACTION_RAMP.  Works like SPECIFIC_HEAT_RAMP.  In the .out file if a ramp is given, I'm just writing the value at TMPA.

**Comment by rmcdermo** [comment]
Great.  I'll test on the thermally thick droplet case.

**Comment by rmcdermo** [comment]
This is now fixed.  Verification cases Ranz_Marshall_thermally_thick.fds and Li_Chow_thermally_thick.fds are using the ramps.
