### ISSUE TITLE
Issue using fds for a user

### ISSUE THREAD

**Issue by alexB1972** [firemodels/fds#7596]
Hi
I'm contacting u because of an issue that a user is having using fds.

Installation ok.

When launch fds command shell, it shows errors ... 

[fds dos command error.docx](https://github.com/firemodels/fds/files/3609073/fds.dos.command.error.docx)

Is it possible to re-initialize fds profile so the user could put his login / password again ?

How to do that ?

Sincerely,

Alexis Bernadotte

**Comment by sbenkorichi** [comment]
This question should be asked in the discussion group as it doesn't seem to be a bug in the code.
https://groups.google.com/forum/#!forum/fds-smv

Also read the user guide on how to run fds. There is a section dedicated for that.
