### ISSUE TITLE
problems running fds 

### ISSUE THREAD

**Issue by guillermobv1** [firemodels/fds#7605]
hi, i know this has been asked before but the previous anwser didnt help me so let me explain:
i downloaded fds and smokeview ( the latest version) on a windows pc. once the installation was completed and i try to run the application called fds that i find in firemodels/fds6/bin it says that the impi.dll archive is missing and that i need to reinstall the program which i did without results. Also the previous comments said i was meant to get cmdfds window to appear in my desktop which didnt happen.
any ideas what i am doing wrong? 
many thanks
pd: english is not my first language so i aoplogise for any errors that i mght have commited.

**Comment by rmcdermo** [comment]
Please ask this to the discussion forum.  Thanks
https://groups.google.com/forum/#!forum/fds-smv
