### ISSUE TITLE
problem with particle coloring

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#7635]
I have a test case, part_color.fds, located at Verification/Visualization in the smv repo that I use to verify smokeview particle coloring. This is what the case is supposed to look like.  The four meshes have temperatures 100, 200, 300 and 400 C and are colored blue, cyan, yellow and red

![part_color_good](https://user-images.githubusercontent.com/12403014/65890881-a88af780-e371-11e9-8c58-9d7179a6963a.png)

With the latest fds revision I am seeing all blue. 
![part_color_bad](https://user-images.githubusercontent.com/12403014/65890857-9c9f3580-e371-11e9-8228-d819366fb783.png)

I did a git bisect and found the first bad revision to be at 

a2a0676f1b2429269df1da2c54b5bb9d728a0661 is the first bad commit
commit a2a0676f1b2429269df1da2c54b5bb9d728a0661
Author: rmcdermo <randy.mcdermott@gmail.com>
Date:   Fri Sep 13 11:15:25 2019 -0400

    FDS Source: use droplet evap model for thermally thick liquid particle

randy - even though this is your commit, its still possible this is a smokeview problem.  (I fixed one problem for this case earlier - there still may be other problems lurking)

**Comment by rmcdermo** [comment]
I will take a look.

**Comment by rmcdermo** [comment]
Should be fixed with PR #7641

**Comment by gforney** [comment]
my case now works.  thanks
