### ISSUE TITLE
Splitting the mesh in order to run in parallel causes different results than a single mesh domain 

### ISSUE THREAD

**Issue by aymanbayomy** [firemodels/fds#7647]
I am trying to dividing my mesh domain into four sub-mesh for parallel simulation; however, it gives me different results compared with a single mesh, any explanation?

**Comment by mcgratta** [comment]
The results are not intended to be exactly alike, due to some numerical error at mesh boundaries. Are the results significantly different? What version of FDS are you using?

**Comment by aymanbayomy** [comment]
the results are significantly different , I am using FDS 6.7.1.

Is that ok using mesh splitting or should i build each mesh separately?

**Comment by mcgratta** [comment]
Different in what way?

**Comment by aymanbayomy** [comment]
![temperature](https://user-images.githubusercontent.com/56044374/66051159-6e019600-e4fc-11e9-8d84-40f9fbdf052e.JPG)
here is the temperature difference

**Comment by aymanbayomy** [comment]
this results are based on burner fire example ,

**Comment by mcgratta** [comment]
I would not consider these results to be significantly different. If you were to conduct two replicate fire experiments, these results would not be surprising. Look for noticeable differences in time-averaged profiles and report them if they occur.
