### ISSUE TITLE
Negative value for TMP_FRONT (combining with CONVERT_VOLUME_TO_MASS)

### ISSUE THREAD

**Issue by Edward101** [firemodels/fds#7671]
When I specify a negative temperature for TMP_FRONT together with CONVERT_VOLUME_TO_MASS, I will have a problem.
see my code below:

&MESH XB= 0	20	0	10	0	10	IJK=	20	10	10/
&OBST XB= 10,	12,	6,	8,	2,	4/
&VENT XB= 10,	12,	6,	6,	2,	4,	 SURF_ID='Vent' /

&SURF ID='Vent', VEL=-2, TMP_FRONT= 1, CONVERT_VOLUME_TO_MASS=.TRUE.	/
&SURF ID='Vent', VEL=-2, TMP_FRONT=-1, CONVERT_VOLUME_TO_MASS=.TRUE.	/ There is a problem if the temperature is negative degree C.

**Comment by mcgratta** [comment]
This was a bug related to units of C vs K. Fixed in next release.
