### ISSUE TITLE
Numerical Instability Error

### ISSUE THREAD

**Issue by Samuel-Affar** [firemodels/fds#7675]
Hi

I'm using FDS 6.6.0 for simulating fire outbreak in a garage, but when the time step reached 0.03s, the simulation terminated due to instability error. I have no idea on how to troubleshoot this problem. The code is attached below. 
[Garage_Model_C.fds.txt](https://github.com/firemodels/fds/files/3694097/Garage_Model_C.fds.txt)

**Comment by mcgratta** [comment]
265 MW/m2 ??
No openings in the wall. The HOLE does not open the domain.
I'm not surprised the calculation failed. It fails for me too.
