### ISSUE TITLE
FDS works on 6.5.3 but not on latest fds 6.7.1

### ISSUE THREAD

**Issue by joeparel** [firemodels/fds#7676]
Hi,

I have a previous fds model that worked when I used fds 6.5.3 using a .sh script on high performance computing. But recently I have updated to 6.7.1 and this runs the fds ok but the HRR output is 0. This is the same when I run the file using script and when running locally on the machine. I run the same file back in fds6.5.3 and seem to work again. 

Has someone else faced the same issue? Is there any workarounds? Usually we run fds on multiple mpi modules using a script. But the sce

**Comment by mcgratta** [comment]
I see no attached file. Post a simple version of the file that is giving you trouble.

**Comment by joeparel** [comment]
File attached now. Sorry for the delay.
[IF_FS1_04.txt](https://github.com/firemodels/fds/files/3704858/IF_FS1_04.txt)

**Comment by mcgratta** [comment]
What's the rationale behind this:
```
&REAC ID='POLYURETHANE_REAC',
      FYI='SFPE Handbook, GM27',
      FUEL='REAC_FUEL',
      FORMULA='C3H8',
      CO_YIELD=0.025,
      SOOT_YIELD=0.055,
      HEAT_OF_COMBUSTION=2.5E4/
```
You are specifying propane as your fuel, but cutting its heat of combustion roughly in half.
