### ISSUE TITLE
Question #1:  What was the approach used for specifying the frequency of the variable “output file interval”?

### ISSUE THREAD

**Issue by aymanbayomy** [firemodels/fds#7679]
Case study: VTT_1 (Validation Guide)
Variable: output file write intervals
Issue:  Discrepancy in the results with the variation of output file write intervals, Guidance request for selecting the value for write frequency.
Case description: the output file interval for VTT case was set to 30 s. Based on my understanding and the results obtained (see the plot attached), this variable results in “time averaged” output. I observed that that different output file write intervals results in different predictions for the temperature, I have also seen that this variable has been varied from one case study to another, for instance in  the Steckler room case an 10 s frequency was used instead of 30s (for VTT_1 case study).

 
![image](https://user-images.githubusercontent.com/56044374/66318644-b5679800-e8e9-11e9-8b1a-9b62eb535c43.png)

**Comment by mcgratta** [comment]
This question is better asked in the FDS-SMV DIscussion Group.
