### ISSUE TITLE
Issue: Significant differences in predictions with the change of mesh zones. 

### ISSUE THREAD

**Issue by aymanbayomy** [firemodels/fds#7680]
Case study: VTT_1 (Validation Guide)
Variable: number of meshes
Issue: Significant differences in predictions with the change of mesh zones. 
In VTT validation case, five meshes are used in the simulation, I have converted it to a single mesh and I found that there are noticeable different in results up to 40% as shown in figure blow. Any explanation?
Note: both results are evaluated based on 30 sec output time interval.
![image](https://user-images.githubusercontent.com/56044374/66318740-de882880-e8e9-11e9-9baa-eba4a1ca3417.png)

**Comment by mcgratta** [comment]
Did you change the grid resolution in the vicinity of the fire plume?

**Comment by aymanbayomy** [comment]
no, both cases are based on same mesh resolution

**Comment by mcgratta** [comment]
Run all the cases and then I will comment on the results. I would not expect the results to be exactly the same with different meshing.

**Comment by aymanbayomy** [comment]
Thanks for your reply, Could you please be more specific about running all the cases?
I have picked that one because in this validation case, multi mesh zones were used. I have seen a **significant** difference when converted it to a single mesh.

Note: both cases (multi-mesh zones Vs single mesh zone ) are exactly identical, I just merged all meshes to a single mesh

**Comment by mcgratta** [comment]
What I mean is that there may be single points that do not match, but I would expect that overall the difference in the cases would be small. Did you really run the case with a single mesh of approximately 2.4 million cells?
