### ISSUE TITLE
FDS 6.7.2: openMP Disabled

### ISSUE THREAD

**Issue by parsipal** [firemodels/fds#7720]
Good day,
I just installed FDS 6.7.2 on macOS Catalina (10.15)
If i run fds I got "OPENMP DISABLE" message:

> Fire Dynamics Simulator
>  Current Date     : October 24, 2019  11:02:22
>  Revision         : FDS6.7.2-0-g8f51a39fc-HEAD
>  Revision Date    : Mon Oct 21 15:42:05 2019 -0400
>  Compiler         : Intel ifort 19.0.4.233
>  Compilation Date : Oct 23, 2019  11:35:14
> 
>  MPI Enabled;    Number of MPI Processes:       1
>  **OpenMP Disabled**
> 
>  MPI version: 3.1
>  MPI library version: Open MPI v3.1.2, package: Open MPI gforney@floga.el.nist.gov Distribution, ident: 3.1.2, repo rev: v3.1.2, Aug 22, 2018
>  Consult FDS Users Guide Chapter, Running FDS, for further instructions.

**BUT on the same computer and using the same account, if I run FDS 6.7.1 or FDS 6.7.0 the  openMP are enabled**

> Fire Dynamics Simulator
> 
>  Current Date     : October 24, 2019  11:02:46
>  Revision         : FDS6.7.1-0-g14cc738f9-master
>  Revision Date    : Mon Feb 4 12:26:25 2019 -0500
>  Compiler         : Intel ifort 19.0.1.144
>  Compilation Date : Feb 04, 2019  13:41:34
> 
>  MPI Enabled;    Number of MPI Processes:       1
>  **OpenMP Enabled; Number of OpenMP Threads:      4**
> 
>  MPI version: 3.1
>  MPI library version: Open MPI v3.1.2, package: Open MPI gforney@floga.el.nist.gov Distribution, ident: 3.1.2, repo rev: v3.1.2, Aug 22, 2018
> 
>  Consult FDS Users Guide Chapter, Running FDS, for further instructions.
> 

What am I doing wrong?
Thankyou in adv.
Gio

**Comment by sbenkorichi** [comment]
Yes, not sure why, but it's same for Windows 10. 
![image](https://user-images.githubusercontent.com/20113030/67472639-51630480-f649-11e9-8472-dfdcb0eb95f8.png)

**Comment by rmcdermo** [comment]
Thanks for the heads up.  We've noticed this and are working on it.  But,
just to make sure, what happens if you run a case instead of just launching
the code?

**Comment by rmcdermo** [comment]
@mcgratta Let's see if we can get the old behavior back.

**Comment by sbenkorichi** [comment]
Fair enough, 
It's actually enabled, 
![image](https://user-images.githubusercontent.com/20113030/67476403-e5d06580-f64f-11e9-8009-6898ff8a802c.png)

Also changing the threads works.
![image](https://user-images.githubusercontent.com/20113030/67476477-039dca80-f650-11e9-9b60-e24328855808.png)

**Comment by parsipal** [comment]
Working 

<img width="682" alt="Schermata 2019-10-24 alle 12 21 36" src="https://user-images.githubusercontent.com/15999978/67476724-ddc8f380-f658-11e9-9171-7dfa667c6f64.png">

**Comment by rmcdermo** [comment]
I did a bisect and got this:
```
[rmcdermo@burn fds]$ git bisect bad
e06491eed9ef0f9133c03d1052c5fc6d29dd0699 is the first bad commit
commit e06491eed9ef0f9133c03d1052c5fc6d29dd0699
Author: gorney <gforney@gmail.com>
Date:   Tue Jun 18 10:29:12 2019 -0400

    FDS source: output version info before MPI is initialized
```
Glenn, let's find a way to keep the correct OMP state.

**Comment by mcgratta** [comment]
I will fix this.

**Comment by rmcdermo** [comment]
Seems to work.
