### ISSUE TITLE
energy budget cold walls summary question

### ISSUE THREAD

**Issue by gsmithlanl** [firemodels/fds#7726]
![energy budget cold walls 6_2_1 Expected](https://user-images.githubusercontent.com/57019506/67605192-e0037e80-f73a-11e9-8b7e-a608ea82a3a7.jpg)

It seems that the summary data (highlighted in the attached) is not correct?  If I am wrong, can you please help me understand these values as compared to the expected results via the energy_budget_cold_walls.csv file?

thanks Greg

**Comment by mcgratta** [comment]
There should be two comparisons in this case---the total HRR which is 1200 and the net energy, which is zero. It appears that the plotting instructions in this case are not correct, but I think the case itself is OK. I'll fix it.

**Comment by gsmithlanl** [comment]
Thanks for your help Kevin.  Greg
________________________________
