### ISSUE TITLE
Maths Function on spacial stats

### ISSUE THREAD

**Issue by MSalisbury** [firemodels/fds#7727]
Hi there, just a small issue but one which I'd like to raise.

I use the subtraction function quite often.  It works fine with points, but I wanted to use a mean volume pressure function to control a fan (to help reduce noise).  [I have also used the smooth function].

The subtraction function doesn't work correctly across two statistical volumes...see example below.  The difference should be the same for the two methods (more or less) but the volume method is way off suggesting a programming issue.

Many thanks!

Matt. 

&HEAD CHID='PressureSubstract'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='PressureSubstract.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='Mesh', IJK=40,40,12, XB=0.0,10.0,0.0,10.0,0.0,3.0/
&OBST ID='Separation', XB=0.0,10.0,4.0,5.0,0.0,3.0, SURF_ID='INERT'/ 
&HOLE ID='Hole', XB=1.0,2.0,4.0,5.0,1.0,2.0/ 

&SURF ID='Extract',
      RGB=255,51,51,
      VOLUME_FLOW=5.0/

&VENT ID='Extact', SURF_ID='Extract', XB=6.0,7.0,1.0,2.0,0.0,0.0/ 
&VENT ID='Supply', SURF_ID='OPEN', XB=6.0,7.0,6.0,7.0,0.0,0.0/ 

'boxes
&DEVC ID='PressureA_MEAN', QUANTITY='PRESSURE', SPATIAL_STATISTIC='MEAN', XB=0.0,1.0,0.0,1.0,0.0,1.0/
&DEVC ID='PressureB_MEAN', QUANTITY='PRESSURE', SPATIAL_STATISTIC='MEAN', XB=0.0,1.0,9.0,10.0,0.0,1.0/
'points
&DEVC ID='PressurePointA', QUANTITY='PRESSURE', XYZ=0.5,0.5,0.5/
&DEVC ID='PressurePointB', QUANTITY='PRESSURE', XYZ=0.5,9.5,0.5/

'i use this to control a fan or open a door across a lobby...

'Subtract pressure points 
&CTRL ID='Pa_dP_AB_Point',FUNCTION_TYPE='SUBTRACT',INPUT_ID='PressurePointA','PressurePointB', Setpoint = 1000, INITIAL_STATE=.TRUE.,LATCH=.FALSE. /
&DEVC ID='PressureDiffPoint',  QUANTITY='CONTROL VALUE', CTRL_ID='Pa_dP_AB_Point'/

'Subtract pressure in a volume for a control...
&CTRL ID='Pa_dP_AB_Volume',FUNCTION_TYPE='SUBTRACT',INPUT_ID='PressureA_MEAN','PressureB_MEAN', Setpoint = 1000, INITIAL_STATE=.TRUE.,LATCH=.FALSE. /
Graph results
&DEVC ID='PressureDiffVolume',  QUANTITY='CONTROL VALUE', CTRL_ID='Pa_dP_AB_Volume'/

The volume results are way off...

&TAIL /

**Comment by drjfloyd** [comment]
I'll look into it. On travel so it might be a day or so.

As a work around you could try defining multiple points in each volume the
using sum and divide functions to compute your own average and then
subtracting those averages.

**Comment by rmcdermo** [comment]
I believe this was identified and fixed in Issue #7588.  I tested your input file and it seems to work for me with latest source.  We are working on getting a release out, but keep hitting snags.  Should be any day now.

**Comment by MSalisbury** [comment]
Cheers drjfloyd, good work around - I will use that approach.  Many thanks for all your work on FDS!  much appreciated.

Matt.
