### ISSUE TITLE
User Guide update

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#7734]
I believe with [this update](https://groups.google.com/forum/#!topic/fds-smv/m3D_s3vpmNM), single mesh is no longer the limitation.

Thank you for reviewing.

![image](https://user-images.githubusercontent.com/26166281/67953350-39fabd00-fbef-11e9-80db-519ca899c9cb.png)

**Comment by rmcdermo** [comment]
Yes, thanks, we'll fix.

**Comment by Er9y714** [comment]
Thank you. 
I have updated the screenshot. It is mentioned in the following paragraph too.

**Comment by rmcdermo** [comment]
Fixed in PR #7735
