### ISSUE TITLE
Domain/ Cell Pressure & Height

### ISSUE THREAD

**Issue by MSalisbury** [firemodels/fds#7736]
Hi all,

This is only a small issue, but would it be possible to set up individual cell pressures at t0 relative to height?

FDS User Guide Chapter 8 confirms 'density and pressure decrease with height (the z direction)'.  Not sure this occurs at t0...

All of the following works fine at the ‘standard’ ground level (+0m), whereas when the model is lifted to 50m different results occur associated with 'pgh'.  At 50m less pressure exists of course - about 600Pa.  Would be great if FDS could initialize relative cell pressures at t0 based on height... 

If you run the example below and review pressure outputs you'll see what I mean. 

Many thanks for looking into this.  

Cheers

Matt.

1.	No Pressure Zones, no openings = ~-600Pa.
FDS User Guide 12.3.2 
‘Note, for this approach it is not required that one have pressure zones deﬁned; however, it is recommended to do so if different pressure zones do in fact exist in the model.’

The results suggest that that the mesh is resetting to external pressure - but t0 should be -600Pa too...each cell could have its own pressure based on height...

2.	Pressure Zone, no opening = ~0Pa
Not sure why this case doesn't get set to ambient external pressure ~-600Pa but stays at ~0Pa 

3.	Pressure Zone with an opening = similar results to 1.

 ---------  FDS Input File ---------

&HEAD CHID='HeightLeak'/
&TIME T_END=10.0/

&MESH ID='Mesh', IJK=40,40,12, XB=0.0,10.0,0.0,10.0,50.0,53.0/

&VENT ID='Vent', SURF_ID='HVAC', XB=0.0,10.0,0.0,10.0,53.0,53.0/ 

&HVAC ID='Leakage', TYPE_ID='LEAK', VENT_ID='Vent', VENT2_ID='AMBIENT', AREA=1.0/

&SLCF QUANTITY='PRESSURE', PBZ=51.5/

Reference point 2. above
ZONE ID='Zone', XB=0.0,10.0,0.0,10.0,0.0,3.0/

Reference point 3. above
VENT ID='Open', SURF_ID='OPEN', XB=0.0,0.75,8.75,9.5,50.0,50.0/ 
DEVC ID='TIMER->OUT', QUANTITY='TIME', XYZ=0.0,0.0,50.0, SETPOINT=1.0, INITIAL_STATE=.TRUE./
OBST ID='Obstruction', XB=0.0,0.75,8.75,9.5,50.0,51.0, SURF_ID='INERT', DEVC_ID='TIMER->OUT'/ 

&TAIL /

**Comment by rmcdermo** [comment]
@mcgratta Can you see if the init order can be arranged to accommodate this request?  Thanks

**Comment by mcgratta** [comment]
Should be fixed now. The problem was that the HVAC routine assumes `P_INF` at `GROUND_LEVEL`, whereas the overall gas phase solver assumes `P_INF` at `ZS_MIN`. Now both routines assume `P_INF` at `GROUND_LEVEL`.

**Comment by MSalisbury** [comment]
Should GROUND_LEVEL not always = 0m.   

If 10325Pa is ambient pressure, thats 0m at sea level etc etc....  If a basement for example were being modeled GROUND_LEVEL needs to be less than 0m...

I would always consider the heights in FDS as absolute, rather than relative to the lowest zone height...

**Comment by rmcdermo** [comment]
We do not expect ZMIN to be an absolute height relative to sea level.  The user should set P_INF accordingly.

**Comment by drjfloyd** [comment]
GROUND_LEVEL is the reference elevation for P_INF. The actual pressure is based on the delta between GROUND_LEVEL and the mesh Z.  We give you the flexibility to define these however best to suit your needs.

**Comment by MSalisbury** [comment]
Thanks all.  That makes sense.  Basically the ambient pressure is assigned to the lowest floor and everything is relative to that.   

While we are on the pressure issue, the original post above resulted in -600Pa for a case 50m up, which is what I expected.

Should the example below not show the pressure reducing going up?  A guess each cell's OPEN face would need the relative delta p assigned to it.  Will each cell get their own delta p based on height at t0? 

Thanks again for reviewing!

Matt.

&HEAD CHID='Tower'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='Tower.ge1', COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='OpenTower', IJK=4,4,140, XB=0.0,2.0,0.0,2.0,-20.0,50.0/
&VENT ID='Mesh Vent: OpenTower [YMAX]', SURF_ID='OPEN', XB=0.0,2.0,2.0,2.0,-20.0,50.0/ 
&VENT ID='Mesh Vent: OpenTower [YMIN]', SURF_ID='OPEN', XB=0.0,2.0,0.0,0.0,-20.0,50.0/ 

&SLCF QUANTITY='PRESSURE', PBY=1.0/


&TAIL /


![Tower](https://user-images.githubusercontent.com/47190705/67984416-91645180-fc1e-11e9-906c-b1c2c7cf28e1.png)

**Comment by rmcdermo** [comment]
Set NOISE=F and FREEZE_VELOCITY=T to see the gauge pressure.  Or, there is an output for 'BACKGROUND PRESSURE' which may answer your question.

**Comment by MSalisbury** [comment]
Perfect!  the background pressure is exactly what I was after.  I'll be using that from now onward!  Makes much more sense to me.  thanks for the reply.
Matt.

**Comment by mcgratta** [comment]
PRESSURE is the perturbation pressure; that is, it has the vertical
stratification subtracted. BACKGROUND PRESSURE is what you want, but note
that it gives you the pressure in Pa, and ambient is 101325. So you might
have to adjust the color bar.

**Comment by MSalisbury** [comment]
Thanks Kevin.
