### ISSUE TITLE
FDS 6.7.3 with FDS+Evac: Evacuation simulation without fire are not longer possible

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#7744]
Revision         : FDS6.7.3-0-g9a07c366b-release
Revision Date    : Wed Oct 30 13:27:03 2019 -0500
Compiler         : Intel ifort 19.0.4.233
Compilation Date : Oct 30, 2019  22:26:38

**problem:**
For the example [evac_memory_test0.fds](https://github.com/firemodels/fds/blob/master/Verification/Evacuation/evac_memory_test0.fds) with

```
&MISC EVACUATION_MC_MODE=.TRUE., NO_EVACUATION=.FALSE. /
```

instead of ([evac_memory_test0.fds, line 24](https://github.com/firemodels/fds/blob/43221bb324668629b0169ddb39fcf3ae361100e3/Verification/Evacuation/evac_memory_test0.fds#L24)):

```
&MISC EVACUATION_MC_MODE=.FALSE., NO_EVACUATION=.TRUE. /
```

I get the following message:

```zsh
% fds evac_memory_test0.fds

 Starting FDS ...

 MPI Process      0 started on zam433

 Reading FDS input file ...

 EVAC: Emesh 1 FF1stFloor has 4 door flow fields

ERROR: The domain appears sealed. Specify one or more pressure ZONEs. (CHID: evac_memory_test0)

STOP: FDS was improperly set-up (CHID: evac_memory_test0)
```

It looks like _Evac_ simulations without fire are no longer possible.

**Comment by rmcdermo** [comment]
OK, thanks for the report.

@tkorhon1 can you please look at this?

We will have to do another release asap.

**Comment by rmcdermo** [comment]
@gjaeger Did you try specifying a pressure ZONE?

**Comment by gjaeger** [comment]
> Did you try specifying a pressure ZONE?

No. That wasn't necessary until now.

**Comment by rmcdermo** [comment]
Well, given that Timo is not responding, your options are either not use 6.7.3 or try to address the error message FDS is giving.

**Comment by gjaeger** [comment]
As a preliminary solution, the simulation _evac_memory_test0.fds_ runs with the addition:

```
&ZONE XYZ= 25.0,20.0, 1.5 /
```

**Comment by godisreal** [comment]
Below is a quote from a previous issue.  Maybe it is helpful.  
There are different issues that address a relavent problem. 
In brief the coupling of fds and evac is not very good in current mode.  

Timo wrote as below  in https://github.com/firemodels/fds/issues/7115
> I just commited a new source code. It has now "evacuation bug fixes" for the changes:
> 
> Glenn modified the CHID_prt5.bnd file format. And this made the fire+evacuation part to crash, at least in the debug compilation.
> 
> Kevin changed the way the pressure zones are initialized/read in/defined. I just fixed this, hopefully. My simple test case seems to run, but I have no checked that the evacuation results are reasonable for my other V&V cases.

**Comment by tkorhon1** [comment]
Hi!

I noticed this also. I have not yet had time to think the best way to correct it in the
source code. But there is a way around, add one ZONE namelist for each evacuation
mesh that is defined in the input file:

&ZONE XYZ=x,y,z  /, where x,y,z is some point in the evacuation mesh that is not solid.

The previous bug fixes seem to working. So, the prt5 stuff is working and also the DOOR/EXIT TIME_OPEN and TIME_CLOSE are now working once again. My personal verification cases 
were not checking.

So, at the moment (FDS 6.73 source code and later ones) seems just to have this issue
on the ZONE. This is probably just some checks in the read.f90, where the input file
is read in. So, there is some check that checks that you have zones properly defined
for the fire meshes. I should add there something that skips these zone tests for
the evacuation meshes  like IF (EVACUATION_ONLY(NM)) CYCLE.

The evacuation meshes have pressure zones defined inside the source code, so these
are automatically defined for the evacuation meshes. But the read routine does not
know this.

TimoK

**Comment by tkorhon1** [comment]
Just commited a fix for this. Now read.f90 is checking that if there are more than one FIRE mesh and no zones and sealed => print the error message.

**Comment by rmcdermo** [comment]
@tkorhon1 Does this latest source pass all your verification tests?  If so, we will issue another maintenance release.

In the future, we need to figure out how to be more integrated in real time.  I suggest that we add you to the firebot email list, if for no other reason than this is where much of the dialog happens when we are about the do a release.  If you had been on these email threads, I think this could have been avoided.  But I forgot to include you.  It will help remind me if you are on the firebot list.

Furthermore, I'd like you to add a couple of cases to the FDS verification suite (this one, for example) that are used to make sure your code runs.  Thanks

**Comment by tkorhon1** [comment]
I will put the verification cases to our Linux cluster today and check the results tomorrow (Thu 14th). Before that I commit evac.f90. There are some minor additions there. Now firemodels and tkorhon1 evac.f90 should be the same. There were some additions by others than me in tkorhon1 evac.f90 that I merged yesterday. I have still some learning to do with GitHub.

Yes, it might be a good idea to add me to the firebot list.

And, I should add some verification cases. I'll probably add my "example inputs" there. These are simple to run, just run them as see, if FDS was succesfully finished.

**Comment by gforney** [comment]
Timo
You should have gotten a couple of firebot status emails. If not, I used
the wrong address - send an email to me ( not to this forum) using the
email address you would like firebot to use
Thanks
Glenn

**Comment by tkorhon1** [comment]
Hi Glenn,

Yes, I have received the Firebot messages, so the email address is good.

Wbr,
Timo

FYI: My current contact information at VTT, it is the same that has been already about 10 years
(Well, "Ltd" was added a couple of years ago):

Timo Korhonen
Senior Scientist, DTech
Fire and Evacuation Safety
Tel +358 20 722 4945
VTT Technical Research Centre of Finland Ltd
(Kemistintie 3, Espoo)
P.O. Box 1000, FI-02044 VTT, Finland
www.vttresearch.com<http://www.vttresearch.com/>, timo.korhonen@vtt.fi

**Comment by tkorhon1** [comment]
Now I have run my example and V&V cases and analysed the results. Things seem to be running nicely with evacuation. So, one can release a maintenance release. I used the source code version:

Fire Dynamics Simulator

 Current Date     : November 14, 2019  18:13:12
 Revision         : FDS6.7.3-66-g25ec3553c
 Revision Date    : Fri Nov 8 16:59:46 2019 -0500
 Compiler         : Intel ifort 18.0.1
 Compilation Date : Nov 13, 2019  13:43:48

Timo

**Comment by rmcdermo** [comment]
OK, thanks.

Glenn, let's prepare another bundle when you get time.  Thanks!

**Comment by tkorhon1** [comment]
I keep this Issue still open. I should put some FDS+Evac verification files to GitHub (and update the ones that are there already).

**Comment by gjaeger** [comment]
> I should put some FDS+Evac verification files to GitHub (and update the ones that are there already.

@tkorhon1 Can I help you with something?

**Comment by rmcdermo** [comment]
@gjaeger Thanks for your offer.  If you have a vested interest in keeping FDS+Evac updated, then I'm sure Timo could use help.

The reason we do not have Evac cases in our verification suite is that no one here at NIST can support them.  However, this latest incident has convinced me that we need to rethink this.

I'd like to propose that we add a few cases to, perhaps, the fds/Utilities/Training/ directory.  Perhaps create a new subfolder for Evac.  We could then run these cases during our verification testing and check that they completed successfully.

If Gregor can commit to helping maintain Evac, perhaps we need to think about putting the Evac documentation back in the FDS repo?  Thoughts?

**Comment by gjaeger** [comment]
I've been thinking about it for the past few days. I offer to support Timo and you in updating FDS+Evac.

Randy (@rmcdermo), I like your suggestion with the test cases. First I can provide some test cases in the new directory. Then we can integrate them into the verification process.

The documentation is already in the FDS repo (Manual/FDS_Evacuation_Guide). Timo (@tkorhon1), is the documentation version up to date? Where can I support you first? Any suggestions?

**Comment by rmcdermo** [comment]
@gjaeger Thank you!  I think this is a big step in helping to keep FDS+Evac maintained.

@tkorhon1 Please coordinate with Gregor to guide him on next steps.  Thanks!

**Comment by tkorhon1** [comment]
Hi!

I have been a little bit busy here at VTT during the last days of this decade. We got two commercial commissions that were in a hurry. Now those are already delivered and I have still plenty of this decade left :-)

The most(?) up to date version of the manual is here: https://github.com/tkorhon1/FDS-Evac-Guide

Gregor, you can find some example files here:
http://virtual.vtt.fi/virtual/proj6/fdsevac/documents/FDS+Evac_textbased_homepage.txt
Verification Test Cases:
http://virtual.vtt.fi/virtual/proj6/fdsevac/imo_fds6.html

Well, these IMO test cases could all be run. These are simple and fast to calculate.
But they do not test many features, nor fire+evacuation stuff.

==================================================================
Direct links to some files (PDF versions do not have these links):
==================================================================

Just one of each type is enough for testing that FDS+Evac is running. And these test also fire+evacuation a little bit (the soot vs speed cases).

TimoK

**Comment by gjaeger** [comment]
> The most(?) up to date version of the manual is here: https://github.com/tkorhon1/FDS-Evac-Guide

@tkorhon1 The files of the manual are different. The last update in the [official repo](https://github.com/firemodels/fds/tree/master/Manuals/FDS_Evacuation_Guide) was six months ago. The last update in [your repo](https://github.com/tkorhon1/FDS-Evac-Guide/tree/master/Manual) was eleven months ago. How can we merge these versions?

**Comment by godisreal** [comment]
OK.  Let me answer your question.  I gave a pull request to Timo' repo last year, but it was not yet merged to the official repo yet.  
As Randy (@rmcdermo) mentioned, the important thing is how to keep FDS+Evac maintained.  That's actually the key issue.  I have ever tried to help Timo to do something, but I feel so frustrated sometimes.  
If you are interested, I will show you some problems that I have been trying to solve recently or since last year.  Maybe we can help Timo to do something together.

**Comment by gjaeger** [comment]
> I gave a pull request to Timo' repo last year, but it was not yet merged to the official repo yet.

Why didn't you submit the pull request here?

> If you are interested, I will show you some problems that I have been trying to solve recently or since last year. Maybe we can help Timo to do something together.

Can you describe your ideas in one or more issues? This would be helpful.

**Comment by godisreal** [comment]
OK.  I have submitted a pull request.  
Your comments are much appreciated.  

An existing issue is here.  
https://github.com/firemodels/fds/issues/7115
In brief the evac module will overwrite some fire data when it runs without fire (i.e.,  EVACUATION_MC_MODE=.TRUE.)  For example, .smv and ._hrr.csv are overwritten if EVACUATION_MC_MODE=.TRUE.  Because .smv is overwitten, 3D smoke cannot be displayed in smokeview even if the smoke data file is still there.  
I have been trying to keep the fire data unchanged and have 3D smoke displayed when evac module is run independently.  Are you interested in solving this problem?  Your comments are much welcome.

**Comment by gjaeger** [comment]
I tried out the modifications with the example /Verification/Evacuation/evac_memory_test1.fds. For this, I compiled FDS (mpi_gnu_osx_64) with commit fd77834.

```
% fds_gnu_osx_64 evac_memory_test1.fds

 Starting FDS ...

 MPI Process      0 started on zam433

 Reading FDS input file ...

 EVAC: Emesh 1 FF1stFloor has 4 door flow fields
 FDS+Evac pressure method : FFT

 Fire Dynamics Simulator

 Current Date     : January 20, 2020  14:41:50
 Revision         : FDS6.7.3-388-gfd77834e0-master
 Revision Date    : Sun Jan 19 16:28:57 2020 -0500
 Compiler         :
 Compilation Date : Jan 20, 2020  10:05:56

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Disabled

 MPI version: 3.1
 MPI library version: Open MPI v4.0.2, package: Open MPI brew@Catalina.local Distribution, ident: 4.0.2, repo rev: v4.0.2, Oct 07, 2019

 Job TITLE        : test for RAM: fire+evac meshes
 Job ID string    : evac_memory_test1

 Time Step:   -199,    Evacuation Initialization Time:    -1.990 s
 Time Step:   -149,    Evacuation Initialization Time:    -1.490 s
...
```

My problem is solved. I propose to close this issue.

**Comment by gjaeger** [comment]
It works with [FDS 6.7.4](https://github.com/firemodels/fds/tree/FDS6.7.4). So I close this issue now.

**Comment by tkorhon1** [comment]
Thanks Gregor!

I have been too busy to deal with FDS+Evac issues this year: family reasons have kept
me too busy at work to make some income for my employer (= have been doing some
 customer assignments and they have the top priority over any other kind of projects).

TimoK
