### ISSUE TITLE
Problem: Unexpected bumpy regions in Total Emissivity calculated using a stand alone RadCal

### ISSUE THREAD

**Issue by ahsadeghi** [firemodels/fds#7745]
Hello,
The values for total emissivity have some unexpected fluctuations and bumps before the temperature 1000 K with the relative minimums at the temperatures where the experimental data were reported [Wakatsuki, 2005]. This problem is likely rooting from the spectral transmissivities calculated by Radcal. The method in Radcal is interpolating between the experimentally achieved narrow band parameters (S/D and Gamma/D) for the temperatures other than those seven experimental temperatures, and also for the new sorting of wavenumbers. Any comments and support are welcome.

**Comment by rmcdermo** [comment]
@shostikk please have a look.  Thanks.

**Comment by ahsadeghi** [comment]
@rmcdermo  Dear Randy, 
Thanks for your comment. Actually Simo is my supervisor and we are working on this issue. I wanted to know if you have faced this problem before or not. or if you have any suggestions.

**Comment by rmcdermo** [comment]
I seem to recall something like this being raised before, but I cannot remember how it was settled.  Please consult Simo and/or Hadi Bordbar.  Thanks.
