### ISSUE TITLE
How to do parallel compute with  MPI in multimesh?

### ISSUE THREAD

**Issue by hong-yao** [firemodels/fds#7752]
For example:
 If my case have set 4 meshs, and mesh1 and mesh4 is large, but mesh 2 and mesh3 is small.
how can i use ;
     process1 to compute mesh1
     process2 to compute mesh2 and mesh3
     process3 to compute mesh4
?

thanks.

**Comment by rmcdermo** [comment]
The Issue Tracker is for bug reports.  You should post your question to the discussion forum.  But, first, read the user guide.
