### ISSUE TITLE
Math Sum function on FED

### ISSUE THREAD

**Issue by MSalisbury** [firemodels/fds#7758]
Hi All,

I was attempting to provide a mean FED dose across an escape route, using 6 single point devices.  (ideally a spacial box would be great, but FED isn't configured for that so was attempting to use the mean along the route instead). 

See example below.  The SUM function doesn't seem to work for FED.  I tested with temperature and that works fine.  If you get chance to review, much appreciated.

Thanks

Matt.

&HEAD CHID='Sum_Test'/
&TIME T_END=10.0/
&DUMP RENDER_FILE='Sum_Test.ge1'/

&MESH ID='FireMesh', IJK=12,12,12, XB=0.0,3.0,0.0,3.0,0.0,3.0/

&REAC ID='FAT FIRE',
      FYI='FAT FIRE',
      FUEL='REAC_FUEL',
      FORMULA='C56H100',
      AUTO_IGNITION_TEMPERATURE=0.0,
      CO_YIELD=0.0249,
      SOOT_YIELD=0.01,
      RADIATIVE_FRACTION=0.35/

&DEVC ID='FED01', QUANTITY='FED', XYZ=1.5,1.0,2.0/
&DEVC ID='FED02', QUANTITY='FED', XYZ=1.5,2.0,2.0/
&DEVC ID='TEMP01', QUANTITY='TEMPERATURE', XYZ=1.5,1.0,2.0/
&DEVC ID='TEMP02', QUANTITY='TEMPERATURE', XYZ=1.5,2.0,2.0/

&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      DEFAULT=.TRUE.,
      ADIABATIC=.TRUE./
&SURF ID='HobFire',
      COLOR='RED',
      HRRPUA=500.0,
      TMP_FRONT=300.0/

&OBST ID='HobFire', XB=1.25,1.75,1.25,1.75,1.0,1.25, SURF_IDS='HobFire','INERT','INERT'/ 

&VENT ID='Open', SURF_ID='OPEN', XB=0.0,3.0,0.0,3.0,0.0,0.0/ 

This works fine :)
&CTRL ID='TEMP_SUM', FUNCTION_TYPE='SUM', INPUT_ID='TEMP01','TEMP02'/
&DEVC ID='TEMP_SUM_OUT',  QUANTITY='CONTROL VALUE', CTRL_ID='TEMP_SUM'/

&CTRL ID='TEMP_AVERAGE', FUNCTION_TYPE='DIVIDE', INPUT_ID='TEMP_SUM', 'CONSTANT', CONSTANT=2.0/
&DEVC ID='TEMP_AVERAGE_OUT',  QUANTITY='CONTROL VALUE', CTRL_ID='TEMP_AVERAGE'/

This doesn't seem to be working...  
&CTRL ID='FED_SUM', FUNCTION_TYPE='SUM', INPUT_ID='FED01','FED02'/
&DEVC ID='FED_SUM_OUT',  QUANTITY='CONTROL VALUE', CTRL_ID='FED_SUM'/

&CTRL ID='FED_AVERAGE', FUNCTION_TYPE='DIVIDE', INPUT_ID='FED_SUM', 'CONSTANT', CONSTANT=2.0/
&DEVC ID='FED_AVERAGE_OUT',  QUANTITY='CONTROL VALUE', CTRL_ID='FED_AVERAGE'/

&TAIL /

**Comment by drjfloyd** [comment]
I'll take a look.

**Comment by drjfloyd** [comment]
CTRL functions operate in the instantaneous values of devices or other control functions.  An FED device outputs the time integral of the FED to the devc.csv file.  You will need to use a PID function to convert the device instantaneous value to the integral value and use that in the average and sum.

&CTRL ID='FED01 INT',FUNCTION_TYPE='PID',INTEGRAL_GAIN=1,PROPORTIONAL_GAIN=0,DIFFERENTIAL_GAIN=0,INPUT_ID='FED01'/
&DEVC ID='FED01 INT OUT', QUANTITY='CONTROL VALUE', CTRL_ID='FED01 INT'/
&CTRL ID='FED02 INT',FUNCTION_TYPE='PID',INTEGRAL_GAIN=1,PROPORTIONAL_GAIN=0,DIFFERENTIAL_GAIN=0,INPUT_ID='FED02'/
&DEVC ID='FED02 INT OUT', QUANTITY='CONTROL VALUE', CTRL_ID='FED02 INT'/

&CTRL ID='FED_SUM', FUNCTION_TYPE='SUM', INPUT_ID='FED01 INT','FED02 INT'/
&DEVC ID='FED_SUM_OUT', QUANTITY='CONTROL VALUE', CTRL_ID='FED_SUM'/

&CTRL ID='FED_AVERAGE', FUNCTION_TYPE='DIVIDE', INPUT_ID='FED_SUM', 'CONSTANT', CONSTANT=2.0/
&DEVC ID='FED_AVERAGE_OUT', QUANTITY='CONTROL VALUE', CTRL_ID='FED_AVERAGE'/

**Comment by MSalisbury** [comment]
Thanks Jason!  Much appreciated.
