### ISSUE TITLE
GLMAT solver in CYLINDRICAL coordinates

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7759]
@marcosvanella The attached runs fine with FFT but fails with numerical instability in both GLMAT and UGLMAT solvers.  Not sure these have been set up for 2D axisymmetric coordinates yet.  But it would be good to put this on the TO-DO list.  Thanks.
[test.fds.txt](https://github.com/firemodels/fds/files/3820139/test.fds.txt)

**Comment by marcosvanella** [comment]
Randy, correct, matrices built correspond to cartesian meshes and laplacian. I'll take a look at adding cylindrical coordinates.
