### ISSUE TITLE
FED can't be bound lower than 3, causes Smokeview to crash.

### ISSUE THREAD

**Issue by LWilson15** [firemodels/fds#7773]
While trying to determine the bound data for an FED slice in Smokeview it's default values are 0 minimum and 3 maximum. When changing the maximum number to anything lower than 3 it causes Smokeview to crash. 

Is this intentional? Is there a way to make the maximum bound for FED 1 instead of 3?

**Comment by rmcdermo** [comment]
Please submit a simple test case (FDS input file) that demonstrates the problem.

**Comment by LWilson15** [comment]
I don't think I can demonstrate the problem through an FDS input file. Attached is the fds input used, however the issue is within Smokeview.
[FDS input txt.txt](https://github.com/firemodels/fds/files/3836673/FDS.input.txt.txt)

**Comment by rmcdermo** [comment]
Thanks.  Glenn will need the FDS case to be sure he can reproduce the problem.

**Comment by gforney** [comment]
I was able to reproduce the problem with thouse5.fds in the smv repo.  I assume that it would fail the same way for your case.  try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA

a couple of comments .  
1.  I've been working on updating our bundling process (programs used to install our software) .  so after you install the update at the link above verify that it is smokeview 6.7.10-30 (type smokeview -v at a command line or look in the About menu item)
2.  the default colorbar used for FED slice output is customized to have a min of 0.0 and a max of 3.0 .  If you want to use different min/max values you'll need to choose a different colorbar (menu item Show/Hide>Color>Colorbar ).  This was not the problem with your case however - it was a an array index out of bounds error.  This should be fixed.  It could show up somewhere else that I missed. So let me know if you see any other problems

**Comment by LWilson15** [comment]
Yeah the crash occurred after changing the colour bar to Rainbow. It works perfectly fine now thank you very much.
