### ISSUE TITLE
Current version will not compile with the gnu compiler (soot.f90)

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#7779]
The current version of today, FDS6.7.3-92-g457742f-master will not compile with the gnu compiler on linux. The same goes for the release of FDS6.7.3

The problem seems to be a missing declaration in soot.f90, see below.

../Source/soot.f90:579:20:

       NS2 = SUM(INT(FINDLOC(AGGLOMERATION_SPEC_INDEX,SOOT_INDEX)))
                    1
Error: Function ‘findloc’ at (1) has no IMPLICIT type
../Source/soot.f90:640:20:

       NS2 = SUM(INT(FINDLOC(AGGLOMERATION_SPEC_INDEX,SOOT_INDEX)))
                    1
Error: Function ‘findloc’ at (1) has no IMPLICIT type
make: *** [soot.o] Error 1

**Comment by drjfloyd** [comment]
Make sure you have the most recent gnu compiler. This error is suggesting you are trying to use a version without FINDLOC implemented.

**Comment by drjfloyd** [comment]
See https://github.com/firemodels/fds/issues/7413

**Comment by godisreal** [comment]
Excuse me, I got a strange simulation result of soot.  May I ask it here?  Or start a new issue?  In brief the soot is supposed to spread into a room, but it does not.  Your guidance is much appreciated.

**Comment by rmcdermo** [comment]
Start a different issue.  But this has been discussed on the forum.  Search
there first.
