### ISSUE TITLE
Duplicated Information in Two AST devices

### ISSUE THREAD

**Issue by guipesa** [firemodels/fds#7828]
Hello, 

I am running a simulation of a fire under an obstacle. I have placed adiabatic surface temperature devices under it just above the fire, separated 0.2 meters between them. Analyzing the output data of the sensors, we have seen that two sensors (separated 0,2 m) in the simulation have exactly the same temperature each time step. We do not understand why.

The devices which we have detected this problem are the V5_0_51 and the V5_0_52 located at the position (10,11.8,5) and (10.2,11.8,8.5). Attached to the issue you can find the .fds model and the data output of the devices.

If you could help us to understand why this numeric problems is happening, we will really appreciate it.

Best Regards,
Guillem,
[Modelo27.txt](https://github.com/firemodels/fds/files/3897294/Modelo27.txt)
[Devices_Data.xlsx](https://github.com/firemodels/fds/files/3897301/Devices_Data.xlsx)

**Comment by mcgratta** [comment]
I assume that FDS is putting both devices in the same grid cell. To be sure, I would position each device close to a cell center, like x=10.1 instead of x=10.0. Let me know if that helps.
