### ISSUE TITLE
Beam Smoke Detector, untis for Path_Obscuration and Setpoint (example: device_test.fds)

### ISSUE THREAD

**Issue by antony-walker** [firemodels/fds#7844]
I'm trying to use a beam smoke detector to activate obstructions, and believe that I have found some unexpected results.

Within the example file provided (device_test.txt, modified for an obstruction to appear based on the beam detector), the setpoint is set to 50 %, however the setpoint is not triggered even though the output in device_test_devc.csv reaches 50 % at just over 14 seconds.

As per the example code within the FDS User Guide (page 236), the following forum topic confirms that the setpoint and path_obscuration are both in the range from 0 to 100, so it should work as expected:
https://groups.google.com/forum/#!topic/fds-smv/Yowh9TN_HdE

However when changing the setpoint to 0.5 (as per the attached modified example file, device_test2.txt), the beam detector device does operate, but at around 5 seconds, with an obscuration of around 42%.  Does this mean that not only the units for the setpoint and path_obscuration are different, but also that the manner in which they are determined is also different?

Thanks for looking into this.  Regards, Antony.

[device_test.txt](https://github.com/firemodels/fds/files/3924973/device_test.txt)
[device_test2.txt](https://github.com/firemodels/fds/files/3924974/device_test2.txt)

**Comment by drjfloyd** [comment]
This case is working for me with FDS 6.7.3.  There was a bug in one of the 6.7.x versions when a BEAM DETECTOR crossed meshes that has since been fixed.  

Are you using 6.7.3?

**Comment by antony-walker** [comment]
Hi Jason,

Apologies I forgot to include that I was using 6.7.1, as I had a numerical instability in 6.7.3 in my model, but I might be able to resolve that.

In my model in 6.7.1 the beam detector was contained entirely within one mesh, and I was still getting this behaviour.

I'll start one in 6.7.3 and see how it goes, appreciate the response.

Thanks, Antony.

**Comment by antony-walker** [comment]
All sorted, thanks. 6.7.3 is working.
