### ISSUE TITLE
problem with energy conservation - gas phase enthalpy

### ISSUE THREAD

**Issue by MortezaHaghighi** [firemodels/fds#7845]
Hi,
This is Morteza, from Aalto University. I'm working on producing an energy budget verification test case for the HT3D routine. While I was investigating energy conservation for solid pyrolysis inside the solution domain, I encountered a problem regarding the enthalpy change of the gas phase.

Therefore, removing the solid from the domain, I tried to satisfy energy conservation (in "kJ" units) for heat transfer between the exterior hot walls and the interior gas phase. Unfortunately, I couldn't even do that; the inward energy doesn't match the enthalpy increment of the interior gas.

![energy_budget_gas](https://user-images.githubusercontent.com/56713983/70226261-3364e580-1759-11ea-887d-6fc050dd5a82.PNG)

As one can see, FDS transfers my prescribed amount of energy into the domain perfectly, whereas the change of interior's sensible enthalpy behaves weirdly.
I tried many things, like: 1.finer grid, 2.effects of HUMIDITY, 3.comparing ENTHALPY with SENSIBLE ENTHALPY, 4. effects of different NET_HEAT_FLUX introduced on exterior walls, 5. effects of the simulation run-time, 6. playing with the exterior walls EMISSIVITY, 7. playing with SPECIFIC_HEAT of the gas, and so forth.
None of the above-mentioned investigations resulted in matching curves based on the kJ unit. There are always "high" deviations of the enthalpy curve! It is worsened while working with high NET_HEAT_FLUX (or let's say high gas temperature during the simulation, but not higher than 1200-1300C).
In this test case (attached FDS input file), gas' temperature reaches maximumly around 700C, which is a normal thing!
Any ideas about how we can show the energy conservation with this procedure? (kJ-type energy conservation, **NOT** a procedure like kW curves or hand calculations using FDS temperature results)

[energy_budget_gas.zip](https://github.com/firemodels/fds/files/3926217/energy_budget_gas.zip)

**Comment by rmcdermo** [comment]
I should have some time to look at this today.

**Comment by rmcdermo** [comment]
First, when examining conservation of energy in a closed domain you want to compare the INTERNAL ENERGY.

Second, when you specify a flux on a surface you need to add CHECK_HT=T on MISC, else you may not resolve the thermal wave in time and get inaccurate results.

Last, I'd appreciate it if you refrain from yelling (!) at us in posts.  You should spend some time with the other energy conservation tests in the verification guide.  Look at section 7.2.6, energy_conservation_combustion.

This input file works fine with the latest code:
```
&HEAD CHID='energy_budget_gas', TITLE='Test of energy conservation for the gas phase'/

&MESH IJK=9,9,9, XB=-0.09,0.09,-0.09,0.09,0.0,0.18/

&TIME T_END=100.0/

&DUMP DT_DEVC=1, DT_HRR=1/

&MISC HUMIDITY=0., STRATIFICATION=.FALSE., CHECK_HT=T/

&SURF ID='HOT WALL', COLOR='SILVER', NET_HEAT_FLUX=0.2, TAU_Q=0., EMISSIVITY=0.0/

&VENT MB='ZMIN',SURF_ID='HOT WALL'/
&VENT MB='ZMAX',SURF_ID='HOT WALL'/
&VENT MB='XMIN',SURF_ID='HOT WALL'/
&VENT MB='XMAX',SURF_ID='HOT WALL'/
&VENT MB='YMIN',SURF_ID='HOT WALL'/
&VENT MB='YMAX',SURF_ID='HOT WALL'/

&BNDF QUANTITY='INCIDENT HEAT FLUX', CELL_CENTERED=T/
&BNDF QUANTITY='WALL TEMPERATURE', CELL_CENTERED=T/

&SLCF PBY=0, QUANTITY='VELOCITY', VECTOR=T/
&SLCF PBY=0, QUANTITY='DIVERGENCE', CELL_CENTERED=T/
&SLCF PBY=0, QUANTITY='TEMPERATURE', CELL_CENTERED=T/

&DEVC XB=-0.09,0.09,-0.09,0.09,0.0,0.18, ID='U', QUANTITY='INTERNAL ENERGY',
      SPATIAL_STATISTIC='VOLUME INTEGRAL', RELATIVE=T, TIME_AVERAGED=F/

&TAIL/
```

**Comment by MortezaHaghighi** [comment]
@rmcdermo Hi Randy. Thank you for your kind help.
Actually, I was just trying to let contributors know what were the failed things that I tried to solve the issue, and get "new" suggestions instead. Anyway, I apologize if it sounded like an angry outburst.

BTW, I couldn't find the "INTERNAL ENERGY" quantity in FDS guides. Maybe it's a newly added measurement device, but not yet mentioned as an output quantity in the user guide. However, it solved my issue ATM.

**Comment by rmcdermo** [comment]
Thanks for the heads up.  I added INTERNAL ENERGY to the UG list.

You could have constructed it from ( ENTHALPY - BACKGROUND PRESSURE ) in the mean time.

**Comment by mcgratta** [comment]
Just be careful of the units.
