### ISSUE TITLE
Update description of DNS gas properties

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7848]
@drjfloyd I happen to be messing with a DNS case right now using ETHYLENE as the fuel.  I was trying to adjust the thermal conductivity via either PR on MISC or PR_GAS on SPEC but there was no change in the conductivity ramp.  It looks to me like PR_GAS is currently hardcoded:
```
   CASE('ETHYLENE')
      SIGMA = 4.163_EB
      EPSOK = 224.7_EB
      FORMULA = 'C2H4'
      PR_GAS = 0.83 ! airliquide.com
      H_F = 52.47_EB
      IF (RADCAL_NAME=='null') RADCAL_NAME='ETHYLENE'
```
But this does not seem consistent with the current tech guide, which states that the default value is 0.7 but can be set by the user.

I'm glad to see that the database is filled in, but it seems like we should still have a rather simple hook for adjusting k_alpha, say, for pressure (I'm doing microgravity cases) without having to completely define a new species from scratch.

For example, it would be good to be able to say
```
&SPEC ID='ETHYLENE', PR_GAS=0.63/
```
Do you mind updating the guides and adding this capability?  Thanks

**Comment by drjfloyd** [comment]
I can do this.

**Comment by drjfloyd** [comment]
Try the current source.

**Comment by rmcdermo** [comment]
Seems to work.  Thanks!
