### ISSUE TITLE
fds on windows 2019 server datacenter

### ISSUE THREAD

**Issue by isk-27** [firemodels/fds#7849]
Hi,

I have installed the latest version of FDS-SMV on Windows Server 2019 Datacenter.
I have run a few verification cases but I don not get always the same results as on the machine with the older windows. Can you please tell me if you have experienced/ checked such problems?

I have added the screenshot with the results of the spray burner test case. On the left hand side are the results on the machine with the newest windows and on the right hand side are old results.

Thank you for your help!

Regards

![spray_burner](https://user-images.githubusercontent.com/58586668/70304861-256b9f00-1803-11ea-9919-67519ba89d54.png)

**Comment by rmcdermo** [comment]
Please submit your question to the discussion forum.
