### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by brunoguillaume** [firemodels/fds#7886]
Hi Kevin,

Unfortunately I don’t have other datafiles wih shorter time to crash. Here is the data file (see in zip below): it crashes after 3days with version 6.7.0, but it crashes only after less than 1day with version 6.5.2, with the same memory leak problem just at an earlier time step (see the 2 log files in zip below).
[memory_leak_BG.zip](https://github.com/firemodels/fds/files/4030414/memory_leak_BG.zip)

We only use intel compilation, so the compiler version we use in FDS is mpi_intel_linux_64.
We run the case in MPI+OpenMP, on 12meshes x 2 threads.

Cheers

**Comment by mcgratta** [comment]
I do not understand what you mean when you say you run the case in MPI+OpenMP on 12meshes x 2 threads. Does this mean that you launch 12 MPI processes, each running 2 OpenMP threads? If that is correct, then FDS automatically assigns the first 11 meshes to individual cores, and the remaining 13 meshes to a single core.

**Comment by brunoguillaume** [comment]
I run with these elements in my batch file :
- mpirun -np 12 fds
- export OMP_NUM_THREADS=2
And:
- 12 MESHES defined in the data file, of relatively same sizes,

Le mar. 7 janv. 2020 à 16:04, Kevin McGrattan <notifications@github.com> a
écrit :

**Comment by mcgratta** [comment]
There are 24 meshes in the input file.

**Comment by brunoguillaume** [comment]
sorry, I confused with another case:

I run with these elements in my batch file :
- mpirun -np 24 fds
- export OMP_NUM_THREADS=2
And:
- 24 MESHES defined in the data file, of relatively same sizes

Le mar. 7 janv. 2020 à 19:22, Kevin McGrattan <notifications@github.com> a
écrit :

**Comment by mcgratta** [comment]
I started the case a few hours ago. So far, no leak, but I will let it run for several days.

**Comment by brunoguillaume** [comment]
ok thx Kevin

Le mar. 7 janv. 2020 à 20:50, Kevin McGrattan <notifications@github.com> a
écrit :

**Comment by mcgratta** [comment]
The job is still running on two nodes, and each node has 12 cores. The memory usage has not changed since the job started. I will continue to run the case.
```
top - 09:09:27 up 73 days, 14:21,  1 user,  load average: 12.00, 12.00, 12.00
Tasks: 348 total,  13 running, 335 sleeping,   0 stopped,   0 zombie
Cpu(s): 97.3%us,  0.3%sy,  0.0%ni,  2.4%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  66074648k total, 34945912k used, 31128736k free,   169680k buffers
Swap: 16000736k total,        0k used, 16000736k free, 28352608k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
14662 mcgratta  20   0 3293m 510m  43m R 100.0  0.8   2755:03 fds_impi_intel_
14663 mcgratta  20   0 3340m 545m  43m R 99.9  0.8   2756:28 fds_impi_intel_
14665 mcgratta  20   0 3253m 467m  42m R 99.9  0.7   2756:43 fds_impi_intel_
14667 mcgratta  20   0 3255m 466m  41m R 99.9  0.7   2756:41 fds_impi_intel_
14659 mcgratta  20   0 3129m 342m  43m R 97.9  0.5   2698:48 fds_impi_intel_
14664 mcgratta  20   0 3302m 513m  43m R 97.9  0.8   2697:01 fds_impi_intel_
14658 mcgratta  20   0 3274m 477m  40m R 97.6  0.7   2697:53 fds_impi_intel_
14660 mcgratta  20   0 3417m 624m  39m R 95.9  1.0   2631:46 fds_impi_intel_
14656 mcgratta  20   0 3304m 517m  41m R 95.6  0.8   2621:59 fds_impi_intel_
14657 mcgratta  20   0 3204m 415m  37m R 95.3  0.6   2634:27 fds_impi_intel_
14666 mcgratta  20   0 3222m 432m  39m R 94.0  0.7   2620:33 fds_impi_intel_
14661 mcgratta  20   0 3473m 688m  43m R 93.3  1.1   2563:43 fds_impi_intel_
```
```
top - 09:10:58 up 73 days, 14:22,  1 user,  load average: 12.00, 12.00, 12.00
Tasks: 345 total,  13 running, 332 sleeping,   0 stopped,   0 zombie
Cpu(s): 97.0%us,  0.3%sy,  0.0%ni,  2.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  66074648k total, 35759332k used, 30315316k free,   169244k buffers
Swap: 16000736k total,        0k used, 16000736k free, 31442088k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
17508 mcgratta  20   0 3099m 309m  40m R 100.0  0.5   2757:10 fds_impi_intel_
17509 mcgratta  20   0 3091m 301m  40m R 100.0  0.5   2758:43 fds_impi_intel_
17511 mcgratta  20   0 3092m 301m  38m R 100.0  0.5   2758:48 fds_impi_intel_
17513 mcgratta  20   0 3088m 295m  38m R 100.0  0.5   2758:45 fds_impi_intel_
17504 mcgratta  20   0 3104m 314m  40m R 97.6  0.5   2699:55 fds_impi_intel_
17510 mcgratta  20   0 3113m 320m  40m R 97.6  0.5   2699:48 fds_impi_intel_
17506 mcgratta  20   0 3118m 324m  37m R 95.6  0.5   2633:27 fds_impi_intel_
17503 mcgratta  20   0 3106m 310m  36m R 95.3  0.5   2630:34 fds_impi_intel_
17505 mcgratta  20   0 3107m 321m  43m R 95.3  0.5   2642:12 fds_impi_intel_
17507 mcgratta  20   0 3112m 326m  39m R 95.3  0.5   2631:08 fds_impi_intel_
17502 mcgratta  20   0 3108m 317m  39m R 95.0  0.5   2636:56 fds_impi_intel_
17512 mcgratta  20   0 3099m 310m  39m R 95.0  0.5   2637:28 fds_impi_intel_
```

**Comment by mcgratta** [comment]
The job is still running with no leaks.

```
top - 17:06:57 up 74 days, 22:18,  1 user,  load average: 12.00, 12.00, 12.00
Tasks: 348 total,  13 running, 335 sleeping,   0 stopped,   0 zombie
Cpu(s): 96.5%us,  0.2%sy,  0.0%ni,  3.2%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  66074648k total, 36364204k used, 29710444k free,   169680k buffers
Swap: 16000736k total,        0k used, 16000736k free, 29764064k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
14663 mcgratta  20   0 3340m 545m  43m R 100.0  0.8   4673:45 fds_impi_intel_
14665 mcgratta  20   0 3253m 467m  42m R 100.0  0.7   4674:11 fds_impi_intel_
14662 mcgratta  20   0 3293m 510m  43m R 99.6  0.8   4671:20 fds_impi_intel_
14667 mcgratta  20   0 3255m 466m  41m R 99.6  0.7   4674:08 fds_impi_intel_
14659 mcgratta  20   0 3129m 342m  43m R 97.6  0.5   4574:47 fds_impi_intel_
14658 mcgratta  20   0 3274m 477m  40m R 97.3  0.7   4573:20 fds_impi_intel_
14664 mcgratta  20   0 3302m 515m  43m R 97.3  0.8   4571:53 fds_impi_intel_
14657 mcgratta  20   0 3204m 415m  37m R 95.0  0.6   4463:54 fds_impi_intel_
14660 mcgratta  20   0 3417m 624m  39m R 94.7  1.0   4459:33 fds_impi_intel_
14656 mcgratta  20   0 3304m 517m  41m R 93.7  0.8   4445:39 fds_impi_intel_
14666 mcgratta  20   0 3222m 432m  39m R 93.0  0.7   4442:03 fds_impi_intel_
14661 mcgratta  20   0 3473m 688m  43m R 91.0  1.1   4343:36 fds_impi_intel_
```

**Comment by brunoguillaume** [comment]
Thx to your 'print screen', I understand what is going wrong with my run (I
imagine your run is probably finished correctly, or about to): I use the
fds_mpi_intel_linux_64 version instead of the fds_impi_intel_linux_64.
I did the test with the impi version, and it is running with no leak.
Could you tell me why there are these 2 options for MPI-intel on Linux,
fds_mpi_intel_linux_64 and fds_impi_intel_linux_64  ?

Le ven. 10 janv. 2020 à 23:09, Kevin McGrattan <notifications@github.com> a
écrit :

**Comment by mcgratta** [comment]
fds_impi_intel_linux_64 means Intel MPI libraries and Intel Fortran
compiler.

fds_mpi_intel_linux_64 means Open MPI libraries and Intel Fortran compiler.

>
