### ISSUE TITLE
Clarify HVAC output

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7893]
I have a case where I want to output a `NODE PRESSURE` and I accidentally specified both an `XYZ` value and a `NODE_ID` on the `DEVC` line. Is it true that if one specifies a `QUANTITY` from the HVAC output table, there is no need for an `XYZ`? If so, could we add that point to the table preamble. 

Also, it is clear that a `DUCT ...` quantity needs a `DUCT_ID`, and same for nodes, but what about things like `FAN PRESSURE`? 

One last thing. There is no column for File Type because I assume it is always `D`? Is that right? Should we add the column anyway to emphasize that?

**Comment by drjfloyd** [comment]
I am pretty sure I coded this to not require an XYZ.  I'll revisit the table and make sure the required XXX_ID and need for XYZ is clear. 

Do we want to add a column or just point a note for the table that these are DEVC only quantities?

**Comment by mcgratta** [comment]
Add column just to be consistent. There is room for it.

**Comment by drjfloyd** [comment]
Added more notes to the paragraph before the table and the column with D.

**Comment by mcgratta** [comment]
Checked. Thanks.
