### ISSUE TITLE
humidity

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#7896]
According to the User Guide, the humidity is 40% by default. In the simple attached file, the SLCF for "RELATIVE HUMIDITY" shows a value of 29.9%. The value of the mass fraction in "humidity.out - row 57"  of 0.004434 seems a little too low to me (compared to technical tables).

[humidity.out.txt](https://github.com/firemodels/fds/files/4065698/humidity.out.txt)

[humidity.fds.txt](https://github.com/firemodels/fds/files/4065678/humidity.fds.txt)

**Comment by rmcdermo** [comment]
Thanks!  We will take a look.

**Comment by drjfloyd** [comment]
Doing a handcalc

H_V for the clausius clapeyron equation at 293.15 K is 2361.38 kJ/kg.  This gives an equilibrium vapor (mole) fraction of 0.0237 or 0.00948 for 40 % humidty.  This is a mass fraction of ~0.00594.  Something does seem to be wrong.

**Comment by rmcdermo** [comment]
I'm bisecting now.

**Comment by drjfloyd** [comment]
I think I see  the problem.

**Comment by drjfloyd** [comment]
There is an error in computing DHOR_T in WATER_VAPOR_MASS_FRACTION. Testing the fix now.

**Comment by rmcdermo** [comment]
You've probably found this, but ...

0f2ce0b063cd8f142fb8e85897fe656e6796f512 is the first bad commit
commit 0f2ce0b063cd8f142fb8e85897fe656e6796f512
Author: dr_jfloyd <jfloyd@jensenhughes.com>
Date:   Mon Feb 18 11:12:22 2019 -0500

    FDS Source: Add EVAP_MODEL plus changes to humidity calc

**Comment by drjfloyd** [comment]
Fixed.

**Comment by rmcdermo** [comment]
Jason,
Nice work.  Do you have time to add this as a verification case?

**Comment by drjfloyd** [comment]
I can do that.

**Comment by drjfloyd** [comment]
added verification case
