### ISSUE TITLE
FDS+Evac, revision of output quantities

### ISSUE THREAD

**Issue by gjaeger** [firemodels/fds#7918]
comment by [Peng Wang](https://github.com/firemodels/fds/pull/7889#pullrequestreview-345628135) on line 871 in file `/Source/data.f90` in PR #7889 (closed):

```f90
OUTPUT_QUANTITY(245)%NAME       = 'HUMAN_CONTACT_LINEFORCE'
OUTPUT_QUANTITY(245)%UNITS      = 'N/m'
OUTPUT_QUANTITY(245)%SHORT_NAME = 'force_c'
 
OUTPUT_QUANTITY(246)%NAME       = 'HUMAN_TOTAL_LINEFORCE'
OUTPUT_QUANTITY(246)%UNITS      = 'N/m' 
OUTPUT_QUANTITY(246)%SHORT_NAME = 'force_tot'
```

> The pressure term in 2D evacuation flow field is in unit of N/m. The force term in agent movement dynamics (Newton 2nd Law) is in unit of N.
> 
> Please check the `HUMAN_CONTACT_LINEFORCE` and `HUMAN_TOTAL_LINEFORCE` in evac.f90
> `HUMAN_CONTACT_LINEFORCE` -> HR%Sumforces -> CONTACT_F
> `HUMAN_TOTAL_LINEFORCE` -> HR%Sumforces2 -> SOCIAL_F + CONTACT_F

I'll take a look at it.

**Comment by gjaeger** [comment]
For explanation:

Starting from the force on the agent _i_

<img width="1086" alt="Eq_force" src="https://user-images.githubusercontent.com/7759675/72805792-fe064f80-3c53-11ea-8aa3-27afd68df720.png">

For the social term, the formula f_{ij}^{soc} has the unit `N` (Newton):
<img width="833" alt="Eq_socialforce" src="https://user-images.githubusercontent.com/7759675/72805912-41f95480-3c54-11ea-9939-b6fce99ecdf6.png">
with $A_i$ [N], B_i [m]

For the contact force term, the formula f_{ij}{c} has the unit `N` (Newton):
<img width="885" alt="Eq_contactforce" src="https://user-images.githubusercontent.com/7759675/72806128-ccda4f00-3c54-11ea-9640-bc71d58b4cab.png">

The sum is calculated in `evac.f90`. Thus the unit is `N`(Newton).

**Comment by godisreal** [comment]
Thanks for your review.  Would you like to review another model about smoke-and-human interaction?  It is extended from the social force model as above, and a resistence force is added to characterize how smoke impedes one's motion.

**Comment by gjaeger** [comment]
> Thanks for your review. Would you like to review another model about smoke-and-human interaction? It is extended from the social force model as above, and a resistence force is added to characterize how smoke impedes one's motion.

@godisreal I don't read closed issues. Why don't you prepare an appropriate pull request? Alternatively you can implement the change in your fork repository. You can present your proposal in a separate issue. There we can discuss your suggestion.
