### ISSUE TITLE
Get Level Set Method working for stacked meshes

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7920]
LS does not work when terrain crosses a mesh boundary in the x-y plane.  That is, if you stack meshes in z and the terrain crosses this mesh boundary, there is a problem with LS.  This is the case I used to discover the problem.  You may need to reset the boundaries, as I have doubled the height since I first discovered the problem.  You will need to copy the binary geom file as well.
```
/home4/rmcdermo/Work/Campfire/campfire3_bingeom.fds
```

**Comment by mcgratta** [comment]
Commit #7973 allows a level set front to cross a horizontal mesh boundary, but there are still some issues that need to be worked out.

**Comment by mcgratta** [comment]
Things seem to be working well for multi-mesh level set calculations now. I'm still testing, but try it to see if it fixes the original problem.
