### ISSUE TITLE
fds comand not responding (FDS 6.7.3)

### ISSUE THREAD

**Issue by RedLight-swe** [firemodels/fds#7925]
So this one is going to be weird, cause its a none error problem with a clear error. 
While setting up FDS 6.7.3 for windows x64, single computer, I found that the command word 'fds', that CMDfds confirm exist, do not connect to any file, example file or not. It just 'runs' without ever going anywhere nor give any error message. Doesn’t take up any CPU capacity. What’s more weird is it doesn’t care it the file is real or gibberish, still no error, so the files are not the problem its seems. 

The only error lead I had was while trying to connect to ‘fds’ by normal CMD it said that impi.dll was missing. While its clearly there. Made a path to it, impi.dll error no longer shows up while trying to reach ‘fds’, problem remains.
 
Some collages have the same problem, while others works. Only suspicion right now is the hardware problem. I send a screenshot of problem, and current hardware information. 

Have reboot, reinstall several times and tested an older version. 

Processor: AMD A9-9410 RADEON R5, 5 COMPUTE CORES 2C+3G 2.90 GHz
RAM: 8.00 GB (7.47 GB free)
System: 64 bits OS, x64 based processor
 
Apologize for vague instruction, its not much to go on from the beginning.   

![FDS6 no response](https://user-images.githubusercontent.com/60175016/72884367-4ed68080-3d06-11ea-9223-2dcba2ffcb5e.PNG)
![CMDnone-error error](https://user-images.githubusercontent.com/60175016/72885246-cf49b100-3d07-11ea-8737-23bb8b34a923.PNG)

**Comment by drjfloyd** [comment]
You are not following the directions in the User'S Guide for running FDS 6.7.3 on a Windows machine.

From the User's Guide:

Open up the special FDS command prompt, CMDfds, which should appear on your desktop when you install FDS. By opening this special command prompt, a script is run automatically ensuring that the FDS commands and libraries are all consistent. Change directories (“cd”) to where the input ﬁle for the case is located. Decide how many logical processes you want to devote to the simulation. Next, decide if you want to run the job solely on your own computer or on multiple computers on the network. If you decide you want to run the case solely on your own computer, and suppose you have 8 logical processors (cores) available, and you have an FDS job that uses 4 meshes, type the following at the command prompt:

fds_local -p 4 -o 2 job_name.fds

**Comment by RedLight-swe** [comment]
Done that several times, still not the problem. I had other look and try to follow Users guide, problem still remains. 
Once again, its a weird problem. 

![fds_local -p 1 -o 1 not the problem](https://user-images.githubusercontent.com/60175016/72892912-0758f000-3d18-11ea-908d-67c197e36eea.PNG)

**Comment by drjfloyd** [comment]
If you type fds_local without an input file, you will get an error message that you don't have an input file and a help message on how to use fds_local.  The image  you attached is the expected behavior. There is no error shown.

**Comment by RedLight-swe** [comment]
Look at the last line of code, that line of code is activated. It's 'running'. Nothing is happening. No output file, no indikator of file 'running' as it shoud. NO error.  

Once again, **its a weird, none error, problem.**

**Comment by RedLight-swe** [comment]
Okey! started the ‘fds’ code offline, by mistake. It works. Now, I saw that I was offline, went online. ‘fds’ wont start, went offline, it works again. 
Again, weird. It works, but I don’t know how or why.

**Comment by drjfloyd** [comment]
fds_local is just a bat file. When you run it without an input file it doesn't launch fds, it just writes the error message. In the second case with an input file given it is trying to run fds. If for the same file fds starts sometimes but not others, that sounds like some issue with the operating system which is going to be difficult for us to assist with. You may need to add an exception to the firewall for fds or you may have some other program conflicting with the mpi driver.
