### ISSUE TITLE
Tunnel fire simulation and numerical instability

### ISSUE THREAD

**Issue by mattbilson76** [firemodels/fds#7929]
Attached file is a model of the LTA tests in the San Pedro tunnel - free burn case. The model consistently goes unstable at around 520 s. If small openings are placed along the length of the tunnel, the instability issue is overcome.  Used the latest FDS build (FDS6.7.3-0-g9a07c366b-release)
[EVS-09-20.txt](https://github.com/firemodels/fds/files/4105046/EVS-09-20.txt)

**Comment by drjfloyd** [comment]
We discuss this in Chapter 9 of the User's Guide.

Item three for dealing with pressure instabilities in a tunnel case:

3. Create OPEN vents at various points along the length of the tunnel, near or at the ﬂoor. This models
natural leakage in the tunnel, and alleviates wild oscillations in pressure.

**Comment by mcgratta** [comment]
I'll take a look. I'm working on tunnel issues now.

**Comment by mattbilson76** [comment]
FYI - these openings were enough to overcome the stability issue on the same case:

&VENT XB=25.0,25.8,3.6,3.6,0.0,0.4,SURF_ID='OPEN' /
&VENT XB=50.0,50.8,-3.6,-3.6,0.0,0.4,SURF_ID='OPEN' /
&VENT XB=75.0,75.8,3.6,3.6,0.0,0.4,SURF_ID='OPEN' /
&VENT XB=100.0,100.8,-3.6,-3.6,0.0,0.4,SURF_ID='OPEN' /

**Comment by mcgratta** [comment]
Add this line
```
&PRES PRESSURE_TOLERANCE=100., MAX_PRESSURE_ITERATIONS=50 /
```
to the input file. Also, do not use the UGLMAT solver. Just use the default solver, which you do not have to specify.

I will explain more in a general posting to the Discussion Group. Let me know if things work better.

**Comment by mcgratta** [comment]
Did my suggestion help?

**Comment by mcgratta** [comment]
I'm closing this issue for now. Re-open or start a new one if problems in tunnels persist.
