### ISSUE TITLE
Allow path particles to cross mesh boundaries

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7931]
With a single mesh, this case shows the particle zigzag across the domain.  A slice of helium mass fraction shows the particles are acting as mass sources.  By splitting the domain in two, the particle disappears at the mesh boundary.

[test.fds.txt](https://github.com/firemodels/fds/files/4105763/test.fds.txt)

**Comment by mcgratta** [comment]
Commit #7932
