### ISSUE TITLE
Intel Math MKL wrapper make error with Mac OS catalina

### ISSUE THREAD

**Issue by ajl42** [firemodels/fds#7949]
Hi,  
       I've followed the clear and concise instructions on compiling FDS for Mac OS.  I have Catalina 10.15.3 installed.  I successfully installed the prerequisites using homebrew and installed the MKL library from intel.  When I try to create the wrapper ( last step from here (https://github.com/firemodels/fds/wiki/Linking-to-Intel-Math-Kernel-Libraries-in-Linux-and-OSX ) using the make command I obtain the following error:

/Library/Developer/CommandLineTools/usr/bin/make clean mkobjdir wraplib ILP_EXT=_lp64 _IA=intel64
rm -rf ./obj_lp64
rm -f ../../lib//libmkl_blacs_custom_lp64
mkdir -p ./obj_lp64
mkdir -p ../../lib/
mpicc -c -Wall -fPIC     -I../../include mklmpi-impl.c -o obj_lp64/mklmpi-impl.o
mklmpi-impl.c:87:25: error: expected expression
    RETURN_IF(xdatatype,MPI_UB);
                        ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:1112:24: note: expanded from
      macro 'MPI_UB'
#        define MPI_UB THIS_SYMBOL_WAS_REMOVED_IN_MPI30(MPI_UB, MPI_Type...
                       ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:322:57: note: expanded from macro
      'THIS_SYMBOL_WAS_REMOVED_IN_MPI30'
#define THIS_SYMBOL_WAS_REMOVED_IN_MPI30(func, newfunc) _Static_assert(0...
                                                        ^
mklmpi-impl.c:338:12: error: expected expression
        int err = MPI_Address(location, address);
                  ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:2842:27: note: expanded from
      macro 'MPI_Address'
#define MPI_Address(...)  THIS_SYMBOL_WAS_REMOVED_IN_MPI30(MPI_Address, ...
                          ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:322:57: note: expanded from macro
      'THIS_SYMBOL_WAS_REMOVED_IN_MPI30'
#define THIS_SYMBOL_WAS_REMOVED_IN_MPI30(func, newfunc) _Static_assert(0...
                                                        ^
mklmpi-impl.c:397:15: warning: 'MPI_Attr_get' is deprecated: MPI_Attr_get was
      deprecated in MPI-2.0; use MPI_Comm_get_attr instead
      [-Wdeprecated-declarations]
    int res = MPI_Attr_get(X2COMM(comm),X2KEYVAL(keyval),attribute_val,flag);
              ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:2702:13: note: 'MPI_Attr_get' has
      been explicitly marked deprecated here
            __mpi_interface_deprecated__("MPI_Attr_get was deprecated i...
            ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:279:78: note: expanded from macro
      '__mpi_interface_deprecated__'
  ...define __mpi_interface_deprecated__(msg) __attribute__((__deprecated__(m...
                                                             ^
1 warning and 2 errors generated.
make[1]: *** [obj_lp64/mklmpi-impl.o] Error 1
make: *** [libintel64] Error 2

Can anyone shed some light on what's to working?

Many thanks,

Andy.

**Comment by rmcdermo** [comment]
Thanks for the report.  We will take a look.  I just got upgraded to Catalina and have not yet compiled.  I'll try asap.

**Comment by marcosvanella** [comment]
Andy, try following the instructions defined here:

https://github.com/firemodels/fds/wiki/Compiling-FDS-with-GNU-Fortran-in-Mac-OSX

You will compile OpenMPI from source instead of using homebrew (this takes some time). Make sure you uninstall the homebrew openmpi as precaution. 

$ brew uninstall openmpi

The last OpenMPI (4.0) version has removed by default MPI1 variables used by the MKL wrapper (the MPI_address error you see) and we need to configure OpenMPI to be compatible with these.
I sent a feature request to homebrew to see if they would add the configure compatibility flag,  but this might take time. 
Let me know how this goes and if notes are clear.

**Comment by ajl42** [comment]
Thanks, I’ll let you know how it goes.
Andy.

**Comment by ajl42** [comment]
Hi,

       your instructions worked first time.  The wrapper has been created.  Thank you so much for solving this so quickly.  OpenMpi compiled in a reasonable time.  

The older versions of MKL will not work on Mac OS Catalina, from what I can see only the most recent 2020 version works.  Could be worth mentioning this in the wiki and using:

# MKL Environment Variables:
export INTEL_COMPILERS_AND_LIBS=/opt/intel/compilers_and_libraries_2020/mac
source $INTEL_COMPILERS_AND_LIBS/mkl/bin/mklvars.sh intel64
Also, Catalina has also changed the default shell to a zsh.  This means users will need to update there .zprofile and .zshrc files. 

I’ll compile FDS and SMV now and let you know how that goes.

Best wishes,

Andy.

**Comment by marcosvanella** [comment]
Hi Andy, thanks for the feedback. I added notes related to the new OSX Catalina requirements.
If you can compile and run FDS, go ahead and close the issue.

**Comment by ajl42** [comment]
Hi this compiled and ran. 

Thanks,

Andy.
