### ISSUE TITLE
Why should &HOLE be oversized?

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#7962]
When a &HOLE is meant to allow flow through an &OBST, the advice in the User Guide is to "punch more than enough" -- that is, to add a small increment to the thickness, to ensure that it goes through.

Sure enough, I have seen cases where specifying the &OBST and the &HOLE with matching coordinates does not work -- see attachment (copied at end of message). It is important to note that in this case, the OBST and HOLE adjoin a MESH-to-MESH boundary.

My feeling is that the official recommendation to oversize the HOLE is kludgy and inconvenient. It is another thing for the user to think about, and it is the sort of thing that software should deal with. It is also slightly alarming: if the thin dimension needs to be oversized to get a working HOLE, why don't all dimensions need to be oversized to ensure the specified size? -- potentially a much more difficult error to detect.

My analysis of why the given example fails in the current code is as follows:
- The HOLE is produced exactly as specified. It is robust to rounding errors etc.
- The OBST, on the other hand, is extended into the neighboring MESH. An infinitely thin OBST is created there, from x=4.0 to x=4.0 in the given example. This is possibly desirable, to give near-wall behavior in the adjoining fluid in that MESH. 
- The infinitely thin OBST (which can be seen in the *.smv file) is the one that is not punched through, and it stops the flow.

My suggestion would be that this behavior is undesirable. It would be preferable if each HOLE is thickened and extended in exactly the same way as each OBST. This would include extending a HOLE into a neighboring MESH, and allowing an infinitely thin HOLE (but only in an infinitely thin OBST). I think this would remove the need for oversized specifications of HOLEs, and this would be a usability enhancement.

Thanks for considering this.
Ed

`&HEAD CHID='failed_hole', TITLE='failed_hole'  /`
`// A corridor blocked by an OBST, but there is a HOLE in it.`
`// The HOLE is given the exact thickness of the OBST,`
`// contravening recommended practice to outsize it.`
`// If the HOLE fails to punch through the OBST, all the flow`
`// leaves through the side exit (so you can see the result`
`// in *devc*csv without launching Smokeview).`

`&TIME T_END=20 /`
`&DUMP NFRAMES=20 /`

`&MESH ID='mesh00', IJK=20,10,10, XB=0.0,4.0,  0.0,2.0,  0.0,2.0 /`
`&MESH ID='mesh01', IJK=20,10,10, XB=4.0,8.0,  0.0,2.0,  0.0,2.0 /`
`// The HOLE fails to punch through the OBST in this case,`
`// where it aligns with a MESH-to-MESH boundary.`
`// It succeeds for a single MESH:`
`/&MESH ID='mesh00', IJK=40,10,10, XB=0.0,8.0,  0.0,2.0,  0.0,2.0 /`

`&OBST XB= 4.0,4.2, 0.0,2.0, 0.0,2.0, SURF_ID='WALL-SOLID' /`
`&HOLE XB= 4.0,4.2, 0.5,1.5, 0.5,1.5 /`

`&VENT SURF_ID='inlet', XB=0.0,0.0,  0.0,2.0,  0.0,2.0,   /`
`     &SURF ID='inlet', VEL=-1.00, COLOR='GREEN' /`
`// Allow flow to leave at the far end, beyond the pierced walls, and also via a side exit`
`&VENT XB=8.0,8.0,  0.0,2.0,  0.0,2.0,  SURF_ID='OPEN',  /`
`&DEVC XB=8.0,8.0,  0.0,2.0,  0.0,2.0,  QUANTITY='VOLUME FLOW', ID='volflow_end' /`
`&VENT XB=2.0,4.0,  0.0,0.0,  0.0,2.0,  SURF_ID='OPEN',  /`
`&DEVC XB=2.0,4.0,  0.0,0.0,  0.0,2.0,  QUANTITY='VOLUME FLOW', ID='volflow_side' /`

`&SLCF PBZ=1.0, QUANTITY='PRESSURE',  /`
`&SLCF PBZ=1.0, QUANTITY='VELOCITY',  VECTOR=t,  /`
`&SLCF PBY=1.0, QUANTITY='PRESSURE',  /`
`&SLCF PBY=1.0, QUANTITY='VELOCITY',  VECTOR=t,  /`

`&SURF ID='WALL-SOLID', RGB=0,50,130, MATL_ID='BLOCK', THICKNESS=0.15 / `
`&MATL ID='BLOCK', CONDUCTIVITY=0.51, SPECIFIC_HEAT=1, DENSITY=1400 /`

`&TAIL /`
[failed_hole.fds.txt](https://github.com/firemodels/fds/files/4127534/failed_hole.fds.txt)

**Comment by mcgratta** [comment]
I coded this behavior back during the World Trade Center investigation. For the simulation of the Twin Tower fires, I created zero thickness walls, floors, elevator shafts, etc. I then needed to punch holes in the floor slabs but not the adjacent elevator shaft walls. Hence the dilemma of < verses <=. The strategy I chose worked then and has worked, mostly, since then. Changing this now without a clear reason other than a personal preference could cause all sorts of unintended consequences. I also have to consider third party GUIs for FDS, like PyroSim  and BlenderFDS that are based on what we write in the User's Guide. I would rather retain the existing functionality in FDS, and leave it to the GUIs to improve usability, if warranted.
