### ISSUE TITLE
Is there really a requirement for only one &MISC line?

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#7963]
The User Guide (v6.7.3, start of Chapter 7) states: "Only one MISC line should be entered in the data file".

Is this true? I don't see it in practice (but that could be luck), and I can't see it in the source code. A small number of validation/verification examples use more than one &MISC entry. (One example is fds-master/Verification/Species/jones_lindstdt.fds, though this is not the best example of the extra freedom in layout afforded by multiple &MISCs.)

I accept that this is a very minor issue, but please could the User Guide be updated if appropriate? Thanks,
Ed

**Comment by drjfloyd** [comment]
At one point this was true; however, looking at the current source code that is no longer the case. We can read in multiple MISC lines and do not reset default values before additional attempts to read MISC inputs. The guide should be updated.

**Comment by rmcdermo** [comment]
Let's discuss this further before you make changes.

**Comment by drjfloyd** [comment]
READ_MISC now will read in multiple MISC lines and it does not reset default values. There is no reason to say a user can't use multiple MISC lines other than perhaps change to a caution that multiply defined inputs will use the last value read in.

**Comment by rmcdermo** [comment]
I wanted to double check we were not resetting default values.

Personally, I think it is bad practice, as MISC is generally reserved for global parameters.  But we'll see if this becomes a problem.

**Comment by drjfloyd** [comment]
If we don't want users using more than one MISC line then we should either only read MISC once or trap having more than one MISC line as an error (probably the better option).

**Comment by rmcdermo** [comment]
I would trap multiple MISC as an error.  But probably Kevin should weigh in on this.

**Comment by obscureed** [comment]
I would much prefer the freedom to group related commands together, and the &MISC commands cover a range of areas (hence the name, obviously). So, for example:
• &MISC CFL_VELOCITY_NORM can be near &PRES VELOCITY_TOLERANCE (numerical settings).
• &MISC CONSTANT_SPECIFIC_HEAT_RATIO=t belongs near &WIND STRATIFICATION=f and &COMB EXTINCTION_MODEL='EXTINCTION 1'. (The User Guide makes it sound as though these settings are required for CONSTANT_SPECIFIC_HEAT_RATIO to take effect, though I'm not sure this is true.) (Physical model settings)
• &MISC RESTART and RESTART_CHID belong somewhere near &TIME and &HEAD. (Run settings)
... and so on.

**Comment by mcgratta** [comment]
I agree with Randy. Let's trap extra `MISC` lines as an error. I wasn't even aware that two MISC lines could be read, and the fact that they are worries me. At some point in the past, I believe we would read the MISC line twice, but I cannot recall why. I'd rather stick with one MISC line, check as to why we would read it twice, and flag extra MISC lines with an error.

obscureed -- whenever we make seemingly simple changes like this (reading extra MISC lines) we end up creating new bugs and problems for ourselves, plus add new code to already complicated read routines. It is easy enough for you to just organize you MISC parameters on multiple lines of the same NAMELIST record.

**Comment by obscureed** [comment]
MISC lines are read twice: after the first reading, default settings are deduced from SIMULATION_MODE. If the user wants to override some of those default settings, this is done by the second reading.

Please note: the change to allowing multiple &MISC lines has already happened -- it was not my suggestion, and the extra lines of code are already present. I was only suggesting that the User Guide should reflect the code. If you are going to revert to a single &MISC line, then I regret mentioning it and must apologise to other users for breaking their models. I really do disagree that lumping the &MISC commands into one place is a good move.

For example, I have a current model, where I want to see the effect of turning on and off some stricter numerical settings, so the not-strict *.fds file can be made from the strict one like this:
`&HEAD CHID='test_notstrict', TITLE='test_notstrict'  /`
`&TIME T_END=200 /`
`&DUMP NFRAMES=200, DT_RESTART=200. /`

`/// Simpler physical models:`
`&MISC CONSTANT_SPECIFIC_HEAT_RATIO=t , STRATIFICATION=f , BAROCLINIC=f, SUPPRESSION=f /`
`&WIND STRATIFICATION=f /`
`&COMB EXTINCTION_MODEL='EXTINCTION 1', SUPPRESSION=f, /`

`//notstrict  /// Tighter numerical settings:`
`//notstrict  &TIME DT=0.002 /`
`//notstrict  &MISC CFL_VELOCITY_NORM=1 /`
`//notstrict  &PRES PRESSURE_TOLERANCE=1.0, VELOCITY_TOLERANCE=0.01, MAX_PRESSURE_ITERATIONS=20 / `

If I want to alternate between strict and notstrict, it helps to have the lines in one place. If I have to stop and use a restart, I would naturally put &MISC RESTART=t near the top, without going to find the numerical settings.

Equally, there are other entries that are global or once-only settings -- all of &PRES, &DUMP, &COMB, for example.  You could issue warnings when one setting overrides another, but I'm not suggesting that you should. You could be consistent and insist on only one each of those lines, but I'm not suggesting that either (please don't!). All I suggested was one incorrect sentence to be removed from the User Guide,

**Comment by rmcdermo** [comment]
User guide updated #7966
