### ISSUE TITLE
Add SURF_IDS capability to GEOM for cylinder

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#7976]
@marcosvanella There a couple of things we need to add for the attached simple case:

* First, there seems to be a problem with the cylinder origin.  The position does not change if I change the parameter CYLINDER_ORIGIN in the file.

* Next, can we add the SURF_IDS(3) capability to a cylinder on GEOM?  SURF_IDS(1:3)='top surf', 'side surf','bottom surf'.  Here "top" should be the top based on the orientation vector, CYLINDER_ORIENTATION.  I think this will be used a lot for simple GEOM cases.

[test.fds.txt](https://github.com/firemodels/fds/files/4141728/test.fds.txt)

**Comment by marcosvanella** [comment]
Randy, I'll take a look.

**Comment by marcosvanella** [comment]
@rmcdermo try the functionality added in PR #7983.

**Comment by marcosvanella** [comment]
This should be working, Randy try the case and close when you can.

**Comment by rmcdermo** [comment]
Seems to be working.  Thanks!
