### ISSUE TITLE
CYLINDER feature of OBST split across meshes

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#7981]
This input file creates a cylinder that ejects ethylene at a rate of 3.18e-4 kg/s (15 kW fire). Something seems amiss in the creation of the cylinder split over four meshes. On one mesh, things work.
```
&HEAD CHID='junk' /

&MESH IJK=12,12,60, XB=-0.12, 0.00,-0.12, 0.00,-0.070,0.530, MULT_ID='mesh' /
&MULT ID='mesh', DX=0.12, DY=0.12, I_UPPER=1, J_UPPER=1 /

&TIME T_END=10. /

&REAC FUEL='ETHYLENE' /

&SURF ID='wall', COLOR='GRAY'/
&SURF ID='burner', HRRPUA=826.6, COLOR='RED' /

&MULT ID='cube array', DX=0.01,DY=0.01, I_UPPER=19,J_UPPER=19 /

&OBST XB=-0.10,-0.09,-0.10,-0.09,-0.254,0.0000
      MULT_ID='cube array'
      SURF_IDS='burner','wall','wall'
      SHAPE='CYLINDER'
      RADIUS=0.076
      HEIGHT=0.254
      XYZ=0,0,-0.254 /

&VENT MB='ZMIN', SURF_ID='OPEN'/
&VENT MB='ZMAX', SURF_ID='OPEN'/

&TAIL /
```

**Comment by rmcdermo** [comment]
Check latest source and it should work within the precision of the circle approximation of the OBST.

I think for the this case we should use GEOM.  I will create one for you tomorrow.

**Comment by mcgratta** [comment]
There is still a question about how the cylinder is carved from the block.

**Comment by marcosvanella** [comment]
@mcgratta see PR #7984.
