### ISSUE TITLE
libmpi.so.12 not properly linked in precompiled linux 6.7.3

### ISSUE THREAD

**Issue by p-lauer** [firemodels/fds#7988]
I installed the precompiled linux 6.7.3 from FDS6.7.3_SMV6.7.10_linux64.sh and got this error:

```
$ fds
fds: error while loading shared libraries: libmpifort.so.12: cannot open shared object file: No such file or directory
```

I went on to check if I use the proper fds and mpi executables:

```
$ which fds
~/FDS/FDS6/bin/fds
$ which mpiexec
~/FDS/FDS6/bin/INTEL/mpi/intel64/bin/mpiexec
```

Then in `~/FDS/FDS6/bin/INTEL/mpi/intel64/lib` I didn't found any file named `libmpi.so.12` but only `libmpi.so.12.0.0`. I renamed it to `libmpi.so.12` and fds runs as intended.

**Comment by gforney** [comment]
Thanks for feedback. Think this is fixed but will double check

**Comment by plut0nium** [comment]
I had the same error.
Created a symlink instead of renaming `libmpifort.so.12.0.0` also solved the issue...

**Comment by gforney** [comment]
this should already be fixed in the latest nightly bundle.  try the bundle posted here.  let me know if you see the same problem.

https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing

**Comment by mcgratta** [comment]
p-lauer -- is the issue resolved?
