### ISSUE TITLE
Receiving grid transformation endpoints error using new TRNX_ID feature

### ISSUE THREAD

**Issue by rjokonski** [firemodels/fds#8001]
I was trying out the new TRNX_ID feature for stretching meshes and while it ran fine with one mesh, once I added another stretched mesh I received the following error:

> ERROR: Do not specify endpoints in linear grid transformation

Here is the file that caused the error:
```
&HEAD CHID='mesh_transformation_3', TITLE='Test mesh transformation feature'/
&TIME T_END=0.0/

&MESH ID='Mesh01', IJK=50,30,4, XB=0.0,1.5,0.0,1.5,0.0,0.1, TRNX_ID='trnx'/
&TRNX ID='trnx', CC=0.3, PC=0.5/
&TRNX ID='trnx', CC=1.2, PC=1.0/
&MESH ID='Mesh02', IJK=50,30,4, XB=1.5,3.0,0.0,1.5,0.0,0.1, TRNX_ID='trnx01'/
&TRNX ID='trnx01', CC=1.8, PC=2.0/
&TRNX ID='trnx01', CC=2.7, PC=2.5/

&VENT ID='Vent01', SURF_ID='OPEN', XB=0.0,0.2,0.0,0.2,0.0,0.0/ 

&TAIL /
```
This problem only seemed to occur if there are multiple TRNX records with different IDs. If I were to stack these two meshes in Z so that they referenced the same TRNX record, I did not have this problem.

I also verified that these same stretch records work correctly if I use the deprecated MESH_NUMBER field instead of the ID system as demonstrated with this file:
```
&HEAD CHID='mesh_transformation_4', TITLE='Test mesh transformation feature'/
&TIME T_END=0.0/

&MESH ID='Mesh01', IJK=50,30,4, XB=0.0,1.5,0.0,1.5,0.0,0.1/
&TRNX CC=0.3, PC=0.5, MESH_NUMBER=1/
&TRNX CC=1.2, PC=1.0, MESH_NUMBER=1/
&MESH ID='Mesh02', IJK=50,30,4, XB=1.5,3.0,0.0,1.5,0.0,0.1/
&TRNX CC=1.8, PC=2.0, MESH_NUMBER=2/
&TRNX CC=2.7, PC=2.5, MESH_NUMBER=2/

&VENT ID='Vent01', SURF_ID='OPEN', XB=0.0,0.2,-1.110223E-16,0.2,0.0,0.0/ 

&TAIL /
```
Perhaps I'm either misunderstanding how the TRNX_ID feature is supposed to work or maybe the parser is merging all the TRNX records together even if they have different IDs.

NOTE: I also experienced this problem with the TRNY record, but I didn't test TRNZ.

**Comment by rmcdermo** [comment]
Thanks for the report.  I will take a look.

**Comment by rmcdermo** [comment]
@rjokonski Thanks for the nice bug report (Boris Stock nominee!).  Should be fixed now.  It's hard to maintain backward compatibility with this one.  Please confirm this is working for you.

**Comment by rjokonski** [comment]
That's great to hear! Unfortunately I can't personally build it to test right now, but I'll see if somebody in the office can get me a build later in the week.

**Comment by rmcdermo** [comment]
We are not advertising this widely, but this may help you guys out.  We are pushing up test bundles that pass firebot.  See the link in [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes).  If we pass tonight, the bundles should be up in a day or two.

**Comment by rjokonski** [comment]
That's great news. I'll check in a couple days then!

**Comment by rjokonski** [comment]
I just checked and everything seems to work great now. Thank you.

**Comment by rmcdermo** [comment]
Thanks for reporting back.
