### ISSUE TITLE
Validation Study on atmospheric deposition of solid particles

### ISSUE THREAD

**Issue by AlinaLAR** [firemodels/fds#8033]
Hi
I would like to perform a validation study on atmospheric particles deposition based on Zink sulfide deposition experiments conducted at Hanford  in 1983. 
Do you think it is suitable for a validation case? 
Thank you

**Comment by mcgratta** [comment]
This is a question that should be posted to the Discussion Group. You might consider describing these experiments in a bit more detail, and then consult the FDS Technical Reference Guide to determine if the assumptions inherent in the deposition model of FDS are appropriate in your case.
