### ISSUE TITLE
U_MEAN_GLOBAL not applied with Z ramp of WIND

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8055]
@mcgratta Please look at the code in velo.f90

<img width="1115" alt="Screen Shot 2020-02-20 at 12 27 33 PM" src="https://user-images.githubusercontent.com/4418497/74961648-66278d00-53dc-11ea-80e4-b52ef313f389.png">

I believe this will not apply the global mean wind in the case of a Z ramp, which is with MO profiles.

**Comment by mcgratta** [comment]
I overhauled the `MEAN_FORCING` routines (b7ab39c). Global averaging is now applied in cases with and without a vertical velocity profile.
