### ISSUE TITLE
RADF.txt overwritten not appended after restart

### ISSUE THREAD

**Issue by RobLWI** [firemodels/fds#8062]
Hi.

after a restart (clean or not) the RADF.txt files will be overwritten not appended.  I noticed first after an unintentional restart, but trying with a clean stop and start has same effect. 

The new file will print the INTENSITIES once at TIME 0.00 then jump to the TIME where the restart occured.  Also missing from the start of the new file will be:
NI
XYZ_DIRECTIONS
NP
XYZ_INTENSITIES
NSTEPS
TIMES

So that is why I think it is simply overwritten, but it does seem odd that it prints the intensities at TIME 0.00 in the new file.

 Current Date     : February 20, 2020  09:14:04
 Revision         : FDS6.7.1-0-g14cc738-HEAD
 Revision Date    : Mon Feb 4 12:26:25 2019 -0500
 Compiler         : Intel ifort 19.0.1.144
 Compilation Date : Wed 02/13/2019  03:33 PM

Windows 10.

e.g. 

&RADF XB=59.5, 60.5, -1, 75.5, 0.5, 9.5, I_STEP=1, J_STEP=2, K_STEP=1/
&DUMP T_RADF_BEGIN=0., T_RADF_END=5400., DT_RADF=30./

Thanks

**Comment by mcgratta** [comment]
I forgot to add `POSITION='APPEND'` to the `OPEN` statement. This is why the file was overwritten. If you can compile the latest code, test this. If not, we're doing a maintenance release within the next few weeks.
