### ISSUE TITLE
Smokeview

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#8069]
If I specify zoom lager than 4 under Motion/View/Render/Windows properties and save the settings, the zoom is set to 4 when I re-open the file.

In SMV user guide under Files/Bound/3D smoke (page 58 - figure 5.5) it seems that it should be possible to set smoke opacity (?). I can’t find this option in SMV 6.7.10 (the menu in the manual is different from menu in the software)

**Comment by gforney** [comment]
I'm working on zoom issue.

For opacity, are you referring to the "50% opacity at (m) 5.0" dialog item? This is an opacity for HRRPUV not smoke .  It is under the HRRPUV/temperature tab.  

you can adjust the smoke darkness/opacity using the "Thickness" dialog item under "Slice rendered/Visualization options (original)" dialog panel

**Comment by gforney** [comment]
try zoom with windows smokeview posted here (I'll post linux and osx smokeview's tomorrow)
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

let me know if you still see a problem

**Comment by fidran** [comment]
Zoom is ok, but there are some other issues
1.	CMD window (Smokeview) will not shut down when I shut down smokeview window
2.	Timeline is above colorbar if I choose slice and below the colorbar if I choose vector (see attached file). This does not happen on all computers (they have 
![Skjermbilde](https://user-images.githubusercontent.com/40716592/75296263-f62a6400-582c-11ea-8e34-15fa5d4f8b78.JPG)
different graphic cards)

**Comment by gforney** [comment]
Fixed 1. Will post new smv tomorrow. Unable to reproduce 2. with my case.
Can you upload yours .  Also upload your .ini file.

**Comment by fidran** [comment]
OK on this computers
CPU : Intel Core i9 9900, Graphics : Intel UHD Graphics 630 (ASUS Z390 motherboard)
CPU : Intel Core i5 3570S, Graphics  : Intel HD Graphics (HP8300 USFH)

Not OK on computers with  :
ATI AMD Radeon HD 5450 – (ASUS motherboard) 
ATI ADM Radeon HD7400M – (HP Probook 6560b)
(not case specific – shows up on all cases)

**Comment by gforney** [comment]
smokeview posted here should fix the issue with the cmd window.  
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

If you are getting different behavior using the same executable on different computers I would suspect there may be issues with your video card or drivers for the card. Try updating your video card drivers.
