### ISSUE TITLE
Modelling wind with different meshing strategies

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#8082]
Hi,

I going to work on a large wind simulation and I was testing some examples coming from the verification rep. I made some small changes and I ran the same case twice with different meshes. The first one has the original mesh strategy with 8 blocks while the second one has some extra blocks, but I kept the same domain size and resolution. Looking at the results I see some differences and I don't understand if this is something normal or if I should use only the meshing strategy used in the original case with 8 blocks. Thanks in advance for the help I send in attachment the figures and the input files.
[input_8m.fds.txt](https://github.com/firemodels/fds/files/4254750/input_8m.fds.txt)
[input_32m.fds.txt](https://github.com/firemodels/fds/files/4254754/input_32m.fds.txt)
![wind_example_8_meshes](https://user-images.githubusercontent.com/15084725/75332981-98763600-5885-11ea-9ca4-26db810b37b3.png)
Velocity obtained with 8 blocks
![wind_example_32_meshes](https://user-images.githubusercontent.com/15084725/75332936-88f6ed00-5885-11ea-8299-5a1d461282ce.png)
Velocity obtained with 32 blocks

Thanks in advance for your help

Matteo

**Comment by mcgratta** [comment]
Recently we improved the `MEAN_FORCING` algorithm. In past versions, the average velocity was calculated on each mesh individually, and the wind velocity for each mesh was forced to that velocity. Now we calculate a global average and force the wind throughout the domain to that global average. This improves grid sensitivity. Are you able to compile the latest code? If so, could you try your case with the latest?

**Comment by mcgratta** [comment]
I just ran the case `wind_example.fds` and a 32 mesh version of it. The results of both are displayed here. 

![wind_example_32_0481](https://user-images.githubusercontent.com/11333911/75354126-7aef9f00-587a-11ea-9669-1a40eaae75b8.png)
![wind_example_0475](https://user-images.githubusercontent.com/11333911/75354157-85119d80-587a-11ea-9a7e-83ab083dfb34.png)

**Comment by mpachera** [comment]
Thanks Kevin for the quick answer, the results look indeed closer to each other. At the moment I don't have the compiler for fortran to recompile the latest version of the code, when do you expect to release a new version of the code?

**Comment by mcgratta** [comment]
This week or next.
