### ISSUE TITLE
AUTO_IGNITION_TEMPERATURE 6.7.1 through 6.7.4

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/fds#8087]
I'm experiencing problems with the parameters related to `AUTO_IGNITION_TEMPERATURE`. I want to specify a "reasonable/realistic" autoignition temperature for the domain and set a very low autoignition temperature around a fire source to ensure combustion.

This parameter appears in a few different places depending on the version of FDS used. 

- 6.7.1: A default temperature can be set for the domain, then regions with a different AUTO_IGNITION_TEMPERATURE can be defined (using `INIT`).
- 6.7.3: The ability to set `AUTO_IGNITION_TEMPERATURE` via `INIT` regions has been removed. A single `AUTO_IGNITION_TEMPERATURE` for the domain can be set.
- 6.7.4*: (As I understand the code currently on master) A single autoignition temperature can be set for the domain, but an exclusion zone (`AIT_EXCLUSION_ZONE`) can be set, within which spontaneous combustion will occur.

The `AIT_EXCLUSION_ZONE` sounds precisely what we need, but it is a single `XB` region. It sometimes occurs that we have 2 burners or a particular L-shaped geometry which can't be covered by an `XB` region.

*: Or whatever the next release is.

Is it possible to have multiple exclusion zones? Is this just a limit of the configuration format, or is it a more fundamental limitation.

**Comment by rmcdermo** [comment]
@JakeOShannessy  I agree the INIT functionality should be restored.  We will work on it.

**Comment by rmcdermo** [comment]
At one point AIT could be assigned to a SURF.  I think this would also solve the current problem to a degree, but is still less general than INIT.  The problem with INIT was that it relies on user judgement, which we were trying to avoid.  But I think the current implementation also requires the user to make some judgements on their own.  I like the generality the original INIT feature had.

**Comment by JakeOShannessy** [comment]
Thanks Randy. You're right in that using this INIT feature does rely on a lot of user judgement, but it is good to be able to exercise that judgement when you really need to. If it's relevant as a point of feedback: I generally avoid it for that very reason, unless I particularly need it. At least having it in the INIT group makes it very explicitly opt-in rather than something set carelessly.

**Comment by mcgratta** [comment]
Now you can add multiple AIT_EXCLUSION_ZONEs. Please check that this does what you want and report back.

**Comment by JakeOShannessy** [comment]
Sorry for the delay, I had unrelated compilation issues.

I've run a few test and it seems to run exactly as intended. Thank you both.

**Comment by rmcdermo** [comment]
Thanks for reporting back.
