### ISSUE TITLE
fds stalling when computer is idling

### ISSUE THREAD

**Issue by soups2541** [firemodels/fds#8101]
Hi,

I've been having this issue lately where the FDS solver stalls when the computer is idle (0% cpu usage, time steps don't change). Computer screen is always on and does not go into sleep mode.

However, when i select the command window and interact with it a bit it starts running again. This has happened on multiple computers.

I am using FDS6.7.1-0-g14cc738, windows 10. 6 meshes, ~300,000 cells.

When i run through cmdfds, i used the standards fds project.fds instead of specifying MPI and OPEN mp settings , which defaults to 1 MPI process and 4 Open MP threads.

Could you please let me know your thoughts, many thanks.

Kind regards,
Andrew

**Comment by gforney** [comment]
think this is windows not an fds issue.  windows has something called "quick edit" mode.  when set and when you click on a command shell the execution within that window pauses - presumably so you can then make some edits.  To turn this feature off, right click on your command shell and select properties.  Then un check the "quick edit" check box.  The behavior you are seeing should stop.

Here is a link to a thread discussing this
https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10

If someone can contribute how to turn off "quick edit" mode from the command line, I will make this the default for our next bundle.

**Comment by soups2541** [comment]
Thanks for your help! Will close the thread.

Kind regards,
Andrew
