### ISSUE TITLE
Compilation error scrc.f90

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#8102]
With 
ifort (IFORT) 19.0.4.233 20190416
(Open MPI) 3.1.4
I get the following compilation errors
../../Source/scrc.f90(9048): error #6580: Name in only-list does not exist or is not accessible.   [ACS]
USE SCARC_POINTERS, ONLY: L, G, AB, AC, FFT, V1, V2, V1_FB, V2_FB, ACS, MKL
-------------------------------------------------------------------^
../../Source/scrc.f90(9048): error #6580: Name in only-list does not exist or is not accessible.   [MKL]
USE SCARC_POINTERS, ONLY: L, G, AB, AC, FFT, V1, V2, V1_FB, V2_FB, ACS, MKL

**Comment by SusanKilian** [comment]
Hi, Ruddy, I just noticed it, too, and I'm working on it. The new version will be available soon.

**Comment by mcgratta** [comment]
Is this issue resolved?

**Comment by SusanKilian** [comment]
Yes, it should be resolved since https://github.com/firemodels/fds/pull/8103 <https://github.com/firemodels/fds/pull/8103>

**Comment by mcgratta** [comment]
OK, thanks. In a case like this, when you commit, do something like this:
```
git commit -m "FDS Source: Issue #8102. Fix compiler error ..."
```
The inclusion of #8102 in the commit message will automatically add a link to the issue narrative so that the reader can see what was done to fix the problem. 

Also, in a simple case like this, just close the issue.

**Comment by SusanKilian** [comment]
Ok, thanks Kevin, the procedure is clear for next time ...
