### ISSUE TITLE
BLOCKLOCATION option in smokeview .ini file is sometimes ignored

### ISSUE THREAD

**Issue by obscureed** [firemodels/fds#8107]
I have had cases where I wanted OBST geometry to be visualised "as specified" rather than "snapped to grid". These options are toggled by pressing Q in smokeview. "Snap to grid" is the default option. "As specified" is saved in the .ini file as BLOCKLOCATION=6.

Sometimes the presence of BLOCKLOCATION=6 in the .ini file does not reproduce the "as specified" visualisation as required. I'll define a small testcase below.

At first, I thought this might be because the keypress Q and BLOCKLOCATION=6 are treated slightly differently in the source code. (See "blockage_as_input" in callbacks.c.)  However, while preparing a testcase, I found that the behaviour is more confusing: BLOCKLOCATION=6 in the .ini file sometimes works and sometimes doesn't.

I'll supply a testcase as an .fds model, an .ini file and a .ssf script -- all very small. Run
`fds blocklocation.fds`
`smokeview -script testAB.ssf blocklocation.smv`
Note that testAB.ssf forces smokeview to read the same .ini file that it read by default anyway -- but after the second reading, picB.png shows the orange square correctly, unlike the earlier picA.png. (I used FDS6.7.3 and smokeview6.7.10, official builds October 2019, on Windows. I see similar results for FDS6.5.2 on Ubuntu. picA.png has snapped the orange OBST to grid, so its rendering competes with the blue OBST.) So now I'm confused. Something is slightly wrong, but I'm not sure what.

[blocklocation.fds.txt](https://github.com/firemodels/fds/files/4294218/blocklocation.fds.txt)
[blocklocation.ini.txt](https://github.com/firemodels/fds/files/4294219/blocklocation.ini.txt)
[testAB.ssf.txt](https://github.com/firemodels/fds/files/4294220/testAB.ssf.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

smokeview was setting blockage location variable again after reading ini file - thanks for reporting

**Comment by obscureed** [comment]
Yes, that new smokeview works for me on the testcase. Thanks!
