### ISSUE TITLE
Simple convection with GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8115]
Two test cases. Two 1 x 1 x 1 meshes with an ambient temperature of 100 C. Each mesh is sealed, has no initial noise, and has a 0,2 x 0.2 x 0.2 cube at 20 C at its center. One mesh has the cube defined with OBST and one with GEOM.  In both cases there is about a 2 % difference in the total convection heat transfer. The cases are identical except case geom_ht computes the heat transfer coefficient and case geom_ht_2 fixes the heat transfer coefficient to 10 W m^-1 K^-1.  Is 2 % what we expect to be seeing?

[geom_ht.txt](https://github.com/firemodels/fds/files/4314235/geom_ht.txt)
[geom_ht_2.txt](https://github.com/firemodels/fds/files/4314236/geom_ht_2.txt)

**Comment by mcgratta** [comment]
Back to you, Marcos. Run the case below, and look at the flow vectors of `TEMPERATURE`. You will notice a big difference in flow at the top of the block, presumably because the flow around the corners is being treated differently.
[geom_ht_2.txt](https://github.com/firemodels/fds/files/4462786/geom_ht_2.txt)

**Comment by marcosvanella** [comment]
I see it. Probably interpolation stencils + wall model for IBM (next task on my list after POLYs, in line with other wall model issue with Randy). Do you see the top and bottom surfaces blue on the geometry? For some reason I don't.
![Screen Shot 2020-04-10 at 2 37 30 PM](https://user-images.githubusercontent.com/7450069/79014791-a03e2100-7b39-11ea-9083-84f0fdd60d9b.png)

**Comment by mcgratta** [comment]
For me, the right hand block has blue and green triangles on each face.

**Comment by marcosvanella** [comment]
Thanks.

**Comment by marcosvanella** [comment]
Not important for the case as is, but to get same SURF_ID distribution as the obst these are the surf ids.
```
FACES=
4,1,3,1,
4,2,1,1,
4,6,2,2,
4,8,6,2,
8,3,7,1,
8,4,3,1,
1,7,3,2,
1,5,7,2,
1,2,5,1,
2,6,5,1,
5,6,8,1,
5,8,7,1
```

**Comment by drjfloyd** [comment]
I revisited these cases and the difference is now 4 to 5 % rather than 2 %

**Comment by rmcdermo** [comment]
We had to take a few steps back in order to get over other hurdles.  I would hold on with anything related to GEOM until Marcos and I get the stress method sorted out.

**Comment by drjfloyd** [comment]
Results match now. Closing.
