### ISSUE TITLE
Box in cross flow OBST v GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8116]
Two 1 x 1 x 1 meshes with a 0.2 x 0.2 x 0.2 box.  Sides open except for -x which is 1 m/s inflow.  The left side uses OBST and the right uses GEOM.  The velocities differ and the GEOM shows a blue ring of zero velocity in Smokeview.

[geom_drag.txt](https://github.com/firemodels/fds/files/4314414/geom_drag.txt)

**Comment by marcosvanella** [comment]
@drjfloyd thank you. We've seen other cases where geometries do not exhibit flow separation where obstacles do. 
@rmcdermo might be a good time to look at the ribbed square duct flow verification case.

**Comment by rmcdermo** [comment]
@drjfloyd Not sure if you knew this is or not, but you can create GEOMs using OBST line parameters, which, to me, is much easier than using VERTS and FACES when it is applicable.

@marcosvanella We need to make sure that ALL the OBST parameters function for GEOM, otherwise it will be a nightmare to convert existing test cases over to GEOM.  I want to be able to simple tell users to to a find and replace OBST for GEOM and for their case to work.  In the example below, if I try to put COLOR on the GEOM line, the code complains.  But this is a valid way to color the solid, as shown on the OBST example.

```
&OBST XB=0.4,0.6,0.4,0.6,0.4,0.6, COLOR='YELLOW'/

&SURF ID='green', COLOR='GREEN'/
&GEOM XB=2.4,2.6,0.4,0.6,0.4,0.6, SURF_ID='green'/
```

**Comment by rmcdermo** [comment]
The problem here is mainly an output problem.  There is a cutcell analog for GAS_PHASE_OUTPUT, but it is incomplete (in this case it's missing KRES, which is used for velocity magnitude).  We need to add cutcell to GAS_PHASE_OUTPUT.

**Comment by drjfloyd** [comment]
I don't think it is mainly an output problem. Clearly, the glitch around the box is an output issue, but the rest of the velocity field is also different.  The attached image is with 30 s of time averaging.

![geom_drag_0121](https://user-images.githubusercontent.com/12799217/76450321-f2a5e980-63a3-11ea-8dba-f7b3eea38edf.png)
.

**Comment by rmcdermo** [comment]
I agree.  I just meant I was going to fix the output first.

To deal with the forcing functions near the surface for momentum, my first stop is going to be the ribbed channel verification case.  There we have data and it took some tuning of the OBST boundary momentum terms to get that right.  Something similar will have to be done with GEOM.

**Comment by rmcdermo** [comment]
The blue ring around the GEOM should be sort of fixed in PR #8131.

We need to keep our eyes out for output quantities like DIVERGENCE that do not inherit gas phase cell values directly in the cutcell.

**Comment by mcgratta** [comment]
Is this issue resolved?

**Comment by rmcdermo** [comment]
The output problem is fixed.  The difference in flow around an object is what I'm working on right now.  This is just one example.  The forcing routines need tuning to better match what is done with OBST for Cartesian geometries.  I'd leave this open.

**Comment by drjfloyd** [comment]
Update on this given the recent commit with new edge routines.  I modified the case slightly (used XB for GEOM, got rid of &PRES, and cut the time down to 200 s).  Things are looking a lot better but there are still noticeable differences between the OBST and the GEOM.  There also appears to be a potential issue with OBST. The image below is time averaged over 100 s.  On the left side with the OBST the flow field is not very symmetric with the domain. Symmetry is shifted down slightly. The peak velocity at the OBST on the top is in the grid cell diagonally adjacent to the top corner but at the bottom corner it is shifted down one cell. The GEOM is showing better symmetry on the upstream side than the OBST but not as well as the OBST immediately downstream.

![geom_drag_1000](https://user-images.githubusercontent.com/12799217/88177921-95def900-cbf7-11ea-977f-4846e81cbe38.png)

**Comment by rmcdermo** [comment]
Thanks, Jason.  I will look at the symmetry issue with OBST

**Comment by marcosvanella** [comment]
Just to note, we have made changes in the recent past to the velocity forcing, and we are now working on the stress method in edges (not default yet). I'm on it.

**Comment by drjfloyd** [comment]
OK. I tried with CC_VELOBC_FLAG2=T. image attached.
![geom_drag_1000](https://user-images.githubusercontent.com/12799217/88202672-37297780-cc17-11ea-8b17-258130b8cf6d.png)

**Comment by marcosvanella** [comment]
Thanks Jason, I'm checking this.

This seems related to corners. Looking at edges and normals setup.

**Comment by rmcdermo** [comment]
The issue with OBST is only an output problem with using a SCLF of 'VELOCITY'.  For this output, we only grab the II,JJ,KK and these are staggered, so using them in a CC slice does not work.   You can, instead, using the QUANTITY='CELL U', for example, to get a CC slice of the u-component.  Also, below, you see a vector slice is symmetric.

<img width="752" alt="Screen Shot 2020-07-22 at 2 10 20 PM" src="https://user-images.githubusercontent.com/4418497/88212511-61823180-cc25-11ea-871b-de9203d26416.png">
<img width="752" alt="Screen Shot 2020-07-22 at 2 06 53 PM" src="https://user-images.githubusercontent.com/4418497/88212513-61823180-cc25-11ea-91b6-a546c42afcb5.png">

**Comment by rmcdermo** [comment]
Maybe I jumped to a conclusion... VELOCITY is taken from KRES(II,JJ,KK), so this should be symmetric.  I'll keep looking.

**Comment by rmcdermo** [comment]
I think that VELOCITY is also symmetric for OBST.  I think that for longer run times, with STRATIFICATION and not enough room behind the OBST you get a fluidic switch that is asymmetric.  If I run with these inputs, I get symmetry until the wake starts its vortex street and then the fluctuations look reasonably symmetric to me.

```
&HEAD CHID='test'/

&MESH XB=0,2,0,1,0,1,IJK=40,20,20/

&TIME T_END=100/

&MISC NOISE=F, STRATIFICATION=F, GVEC=0,0,0/

&RADI RADIATION=.FALSE./

&OBST XB=0.4,0.6,0.4,0.6,0.4,0.6, COLOR='YELLOW'/

&SURF ID='IN',VEL=-1,COLOR='ORANGE'/

&VENT MB='XMIN',SURF_ID='IN'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='ZMIN',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='ZMAX',SURF_ID='OPEN'/

&DEVC XB=0.025,0.975,0.5,0.5,0.7,0.7,QUANTITY='VELOCITY',POINTS=20,ID='OBST'/
&DEVC XB=2.025,2.975,0.5,0.5,0.7,0.7,QUANTITY='VELOCITY',POINTS=20,ID='GEOM'/

&SLCF QUANTITY='VELOCITY', VECTOR=T, PBY=0.5/
&SLCF QUANTITY='VELOCITY', CELL_CENTERED=T, PBY=0.5/
```

<img width="752" alt="Screen Shot 2020-07-22 at 2 33 57 PM" src="https://user-images.githubusercontent.com/4418497/88214869-d5720900-cc28-11ea-9cfd-a392593eb847.png">

**Comment by marcosvanella** [comment]
First thing for corner ibedges is to address their normal, it is picking up one side now whereas for symmetry we want them on an avg direction.
![Screen Shot 2020-07-22 at 3 14 58 PM](https://user-images.githubusercontent.com/7450069/88218778-85964080-cc2e-11ea-892b-f11fced1350f.png)

**Comment by drjfloyd** [comment]
Thanks Randy. I didn't think about STRATIFICATION but duh of course. I agree OBST is fine once that is accounted for.

**Comment by drjfloyd** [comment]
With the current source results are very close.  This a line of velocity devices above the cube.  The cube starts at 0.4. Over the top and beyond the cube results differ by about 2 % and the wake looks similar as well.  

![image](https://user-images.githubusercontent.com/12799217/231242290-97761b47-be72-40fe-b0a8-19cfab87323b.png)

![geom_drag_0944](https://user-images.githubusercontent.com/12799217/231243005-e2e8f0ce-2e7e-4598-8c23-af953dd3f07e.png)
