### ISSUE TITLE
slice averaging with GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8117]
The time average option for a slice file does not work with GEOM.  If I run the attached and load the slice file with time averaging options set, no averaging occurs. Without the GEOM averaging works.

[geom_drag.txt](https://github.com/firemodels/fds/files/4314418/geom_drag.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by drjfloyd** [comment]
Working. Thanks.
