### ISSUE TITLE
Pressure Zones 

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#8122]
@drjfloyd : The attached case has two meshes. Both are divided in half by a wall with a fire on one side and leakage from the fire side to the non-fire side and from the non-fire side to the ambient.  In one mesh the wall is an OBST. In the other mesh the wall is a GEOM. Very different pressure results happen.

[geom_leak.txt](https://github.com/firemodels/fds/files/4314782/geom_leak.txt)

**Comment by mcgratta** [comment]
I created a simpler test case with an analytical solution and committed it to the Verification Guide. The GEOM wall behaves just like an OBST in this simple case, but we probably want to test in a more complex scenario, like when the wall is not aligned with the grid.

Marcos -- are we at the point where we can create this case using 7 GEOM lines to form walls, ceiling, floor and separation wall? And then rotate it all? I don't know if the VENT's will work with the rotated GEOMs.

**Comment by marcosvanella** [comment]
Let me try making this, we should be able to add a vent intersecting a pan geometry to the floor.

**Comment by marcosvanella** [comment]
Kevin try this case, I created it based on Jasons original case. It still needs the HVAC lines.
To see inside the compartment, set the Immersed geometry to outline and add 3D smoke, slices to see. With BNDFs I haven't found a way other to clip the scene to see inside.
I noted a few things, one of them being that the pressure slice plots the pressure value in all cells that have the zone (including IBM_SOLID). I think I can fix that by looking to make zones extend up to the first solid face line (not using cell type, but face type). This should help us thinning the walls up to a layer of cartesian faces being covered (i.e. being type solid).

[geom_leak_2.txt](https://github.com/firemodels/fds/files/4361677/geom_leak_2.txt)

**Comment by mcgratta** [comment]
How did you get the case to run? My case with abutting GEOM's hung.

**Comment by marcosvanella** [comment]
I have to figure this out, but the wall thickness respect to grid in intersection cells might be the culprit (can't correctly define a linearized surface). See my other comment on the other issue.
