### ISSUE TITLE
simple extruded polygon

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#8123]
@drjfloyd :  It would be nice to have a GEOM option where one defines the vertices of a polygon and an extrusion distance using the right hand rule based on point order. 
Here is a 20 cm thick wall rotated 45 degrees:

&GEOM ID='wall1',XB=1.0,2.0,1.0,1.2,0.0,2.0,MOVE_ID='wall1m'/
&MOVE ID='wall1m',
X0=1.0,Y0=1.0,Z0=0.0
AXIS=0,0,1
ROTATION_ANGLE=45./
 
Here is the same wall as an extruded polygon (suggesting POLY and EXTRUDE):

&GEOM ID=" " , SURF_ID="MySurf"
VERTS = 1.0,1.0,0.0,
               1.0,1.0,2.0,
               1.707,1.707,2.0,
               1.707,1.707,0.0,    ! NV Vertices in Polygon
POLY = 1, 2, 3 ,4                ! List of indexes pointing to list of NV vertices.
EXTRUDE=0.2/

**Comment by marcosvanella** [comment]
Jason, do a repo update and try the new extrude functionality. I added a write up on its use on the geom_notes. The polygons must be simple, non degenerate, no repeated points, no crossings. We still have to define a strategy to test for this last issue, specially if some points are off the average plane due to writing a few significant figures in VERTS (making the polygon essentially a 3D polyline). We can probably test their projections on this plane. 
Also, if a vertex is off by a certain amount of the average plane (more that 5% of the Bounding Box diagonal for the POLY) the code throws an error.
There is a sample input in Verification/Complex_Geometry/geom_extrude_poly.fds.
Thanks!

**Comment by drjfloyd** [comment]
I think crossing is simply a matter of determining the equation for a line for each line segment in the polygon and checking to see if the intersection point of any pair of lines lies within each segment.

**Comment by marcosvanella** [comment]
Yes, that is the way to go as long as all the segments lay on a plane. Thing is, here we might have vertices that are slightly off that plane due to the way VERTS are defined (i.e. numbers rounded at the 3rd decimal). So, line thickening (imagine cylinders) might be a way to pickup these issues, or projecting all vertices into the average plane of the POLY. The second option seems simpler and then we can test for intersection in that plane (up to ~floating point accuracy) as you suggest.

**Comment by marcosvanella** [comment]
Jason, I added the seg-seg intersection in the polygon plane as we discussed. Give the functionality a try and we can close the issue. Thanks!

**Comment by drjfloyd** [comment]
Extrusion and error checking work as expected.
