### ISSUE TITLE
FDS User's Guide

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#8132]
Chapter 19.3.6 Beam Detection Systems

"The two endpoints must lie in the same mesh." and "Note that this case uses 8 meshes to span the computational domain, and the beams are permitted to pass from one mesh to another."

I think the first sentence is a leftover from an old version?

Boris

**Comment by mcgratta** [comment]
Good catch. I'll fix this.

**Comment by boris-stock** [comment]
Thanks for your fast response.

Boris

**Comment by mcgratta** [comment]
I committed a corrected User's Guide to the central repo.
