### ISSUE TITLE
GEOM set up goes into an endless loop

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8140]
[geom_rad_2.txt](https://github.com/firemodels/fds/files/4333080/geom_rad_2.txt)
This case hangs in the initialization of immersed boundaries. Even if the GEOM's are not specified properly, we should exit with an ERROR.

**Comment by mcgratta** [comment]
If I separate the two GEOMs, the case runs and produces qualitatively correct results. I'm going to check the details.

**Comment by marcosvanella** [comment]
I note the issue comes when the two boxes intersect over an edge + rotation. I'm digging more on this with the cut-cell Matlab implementation.

**Comment by marcosvanella** [comment]
I'll check the case. I'm working on dealing with some special cases where cut cells cannot be built.On Mar 14, 2020 1:53 PM, Kevin McGrattan <notifications@github.com> wrote:
If I separate the two GEOMs, the case runs and produces qualitatively correct results. I'm going to check the details.

**Comment by mcgratta** [comment]
I added another case to the Verification Guide called `HVAC/leak_test_4.fds`. The case consists of a box made with 6 abutting `GEOM`s and a small cube `GEOM` inside that blows air and pressurizes the box. The box has leakage and a steady state pressure is reached fairly quickly. This case works now because I have not rotated the box. However, if I try to rotate the box, the code hangs. When you fix this issue, change `leak_test_4.fds` by uncommenting the box rotation. The pressure rise should not change.

**Comment by marcosvanella** [comment]
I think we need thicker walls on the case, s.t. we have at least one solid cell within them to define pressure zones correctly. Either way the issue is the same as previous, code gets stuck in the cut-cell definition infinite loop. I'll work on this.

**Comment by mcgratta** [comment]
OK, I'll try thicker walls.

**Comment by marcosvanella** [comment]
BTW to see cut-cell definition progress on the screen (also on cut cell*.log files) add
&DUMP GET_CUTCELLS_VERBOSE=T/
This still needs to be refined.
________________________________
De: Kevin McGrattan <notifications@github.com>
Enviado: viernes, 20 de marzo de 2020 09:05 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: marcosvanella <marcos_vanella@hotmail.com>; Assign <assign@noreply.github.com>
Asunto: Re: [firemodels/fds] GEOM set up goes into an endless loop (#8140)


OK, I'll try thicker walls.

**Comment by marcosvanella** [comment]
Kevin, do an update and try the case. I also added rotation and increased wall thickness on leak_test_4.fds (for ressure zone definition). This last case runs, we want to check the results are correct. I fixed several issues with the cut cell engine and added a fail safe in case cut-cells can't be built (creates a cut-cell of the size of the cartesian cell).

**Comment by mcgratta** [comment]
OK, I'll try it today.

**Comment by mcgratta** [comment]
Nice, everything works. Thanks.
