### ISSUE TITLE
Accuracy of radiation transport for IBM

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8147]
Take a look at the verification case `Radiation/geom_rad_2.fds` that was committed via PR #8146. This case is similar to `geom_rad.fds`, but now the radiating and receiving surfaces are not aligned with the grid. The integrated heat flux from hot plate to cold plate is now about 15% too low, but I checked to see that the total energy radiating from the hot plate is slightly greater than the exact value. Look at the BNDF of `INCIDENT HEAT FLUX` and you will see triangles near the intersection of the two walls that are lower than surrounding in terms of `INTEGRATED INTENSITY`. It seems to me that everything is working as programmed, but now we have to think about these triangles.

**Comment by marcosvanella** [comment]
I'll check it out.

**Comment by marcosvanella** [comment]
I note that, even closing the gap between geoms these triangles get a lower incident heat flux. We have to see how HOT and COLD faces are placed within these cells (cartesian faces they are assigned to). Still it seems this would give too small of a change to account for a 15% difference. Note the stripes we get on the contour following the cartesian grid planes. Would be interesting if we can reduce the travel (gas absorption) length across the cell for the cfaces given where they are actually placed, instead of cartesian face locations.

**Comment by marcosvanella** [comment]
It seems as if we should interpolate the integrated intensity back to the cut cells underlaying cartesian cells. The fact that some cfaces go to back faces of these cells (i.e. towards the solid) in one direction, while they can block the cell in another direction makes the intensity smaller than in surrounding completely exposed gas cells. 
See this plot for the case where we assign CFACEs to the closest cartesian face in each direction:
![Screen Shot 2020-03-16 at 7 23 10 PM](https://user-images.githubusercontent.com/7450069/76807899-5a04d480-67bc-11ea-84ae-c7fd745fa94f.png)

Adding this **test** snippet of code (makes IL(I,J,K) in cut cells underlaying cartesian cells the average of nearby gas cells) in radi.f90 line ~1388 (after ENDIF GEOMETRY):

```
            IF (CC_IBM) THEN
               DO K=1,KBAR
                  KLO=K-1; KHI=K+1; IF (K==   1) KLO=K; IF (K==KBAR) KHI=K
                  DO J=1,JBAR
                     JLO=J-1; JHI=J+1; IF (J==   1) JLO=J; IF (J==JBAR) JHI=J
                     DO I=1,IBAR
                        IF(CCVAR(I,J,K,IBM_CGSC)/=IBM_CUTCFE) CYCLE
                        ILO=I-1; IHI=I+1; IF (I==   1) ILO=I; IF (I==IBAR) IHI=I
                        IL1 = 0._EB; COUNT=0
                        DO KK=KLO,KHI
                          DO JJ=JLO,JHI
                            DO II=ILO,IHI
                              IF(CCVAR(II,JJ,KK,IBM_CGSC)/=IBM_GASPHASE) CYCLE
                              IL1   = IL1 + IL(II,JJ,KK)
                              COUNT = COUNT + 1
                            ENDDO
                          ENDDO
                        ENDDO
                        IF(COUNT > 0) IL(I,J,K) = MAX(IL(I,J,K),IL1/REAL(COUNT,EB))
                     ENDDO
                  ENDDO
               ENDDO
            ENDIF
```

This is what I see:

![Screen Shot 2020-03-16 at 8 41 20 PM](https://user-images.githubusercontent.com/7450069/76811099-b7058800-67c6-11ea-905e-de68e865a599.png)

We'd need to think how to do this consistently.

**Comment by mcgratta** [comment]
Yes, and we need to make sure that we don't create energy by assigning a radiative intensity to a cell improperly. In this instance, I think we are OK, because these "ghost" cells just serve as the upwind BC for the radiative transport equation.

Also, we need to check the various IF statements to ensure that we do not do excessive work searching for CFACEs.

**Comment by marcosvanella** [comment]
I'll work on this. The external 3D loop + conditional test can be avoided by looping the CUT_CELL array.

**Comment by marcosvanella** [comment]
Kevin, do an update and try the case now, I reworked the scheme to compute the INRAD_F on CFACES from their projected faces on grid planes (which is consistent with what is done on the radi FVM scheme). I also added the assignment of the largest contiguous gas phase IL value to the cut cell cartesian cells. The plots and integral look alright, there is still something going on for the point device, which is located on a mesh boundary (it's reading is 5% lower). If you use a single mesh, the value goes back up to the geom_rad.fds level. 
I think this has something to do with the value of IL in ghost-cells.

**Comment by mcgratta** [comment]
OK, things look good. I added some plots to the Verification Guide. I also moved the point heat flux device out of the mesh corner and/or triangulation of the obstruction. Mesh corners are tricky because we do not do MPI exchanges diagonally. That's an issue for another time.
