### ISSUE TITLE
GEOM obstruction does not block water droplets

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8171]
Run the test case `Sprinklers_and_Sprays/e_coefficient.fds`. Notice that a pan created with 5 GEOMs does not trap water dumped into it. We need some logic to detect that a droplet has entered a vertical obstruction, should be put back to its original position, and then given a new random direction. 

BTW, this case demonstrates that I've added water suppression (`E_COEFFICIENT`) to GEOMs.

**Comment by marcosvanella** [comment]
Kevin, I can see the issue, they look like roaches.. Looks like they go just through the lips of the pan, some of them get pushed up top and fall on the side, others go right through.
This looks like is related to the piece of code we were working on the other day.
________________________________
De: Kevin McGrattan <notifications@github.com>
Enviado: jueves, 19 de marzo de 2020 09:21 p. m.
Para: firemodels/fds <fds@noreply.github.com>
CC: marcosvanella <marcos_vanella@hotmail.com>; Assign <assign@noreply.github.com>
Asunto: Re: [firemodels/fds] GEOM obstruction does not block water droplets (#8171)


Assigned #8171<https://github.com/firemodels/fds/issues/8171> to @marcosvanella<https://github.com/marcosvanella>.

**Comment by marcosvanella** [comment]
Kevin, what s the simplest way to know if the particle on it's initial position was already attached to a CFACE? (something like previous step LP%ONE_D%IOR/=0)
One option I have is testing for vertical velocity, but that would not work in cases where the surface is inclined.

**Comment by mcgratta** [comment]
Probably something like IOR_OLD, like we do it for IIG_OLD, JJG_OLD, KKG_OLD.

**Comment by marcosvanella** [comment]
Kevin, do a repo update and try the case now. I added logic for collision when particles are moving in horizontal planes.

**Comment by mcgratta** [comment]
Nice, works great. I tightened the verification tolerance for this case and I'll close. Thanks.
