### ISSUE TITLE
Peculiar FDS crash running MPI

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#8179]
We are testing MPI and the attached FDS model crashes when I run using MPI with the command:

fds_local -p 4 -o 1 burner_4_meshes.fds

I have attached an image of the output showing the crash.

However, if I run with one processor (fds_local -p 1 -o 2 burner_4_meshes.fds) it runs successfully. 
Other ways that it runs successfully is if I use 8 or 12 meshes or if I delete the
&SLCF QUANTITY='AEROSOL VOLUME FRACTION', SPEC_ID='PRODUCTS', PBX=0.0/
line from the model.

It only crashes for this one specific option, so it is confusing.

Hope this helps. I hesitated submitting, since it seems so specific.

And best wishes to all,

Daniel Swenson
Thunderhead Engineering

[burner_4_meshes.fds.txt](https://github.com/firemodels/fds/files/4376577/burner_4_meshes.fds.txt)

![crash_4_processors](https://user-images.githubusercontent.com/13338306/77454092-1581c600-6dc6-11ea-95d2-ec6a939faab6.png)

![successful_1_processor](https://user-images.githubusercontent.com/13338306/77454684-def87b00-6dc6-11ea-8417-b378865dbe10.png)

![successful_4_processor_no_aerosol_slice](https://user-images.githubusercontent.com/13338306/77454699-e3bd2f00-6dc6-11ea-900b-aae18218584c.png)

**Comment by rmcdermo** [comment]
@drjfloyd would you mind having a look at this?

**Comment by drjfloyd** [comment]
I can take a look. Probably not today though.

**Comment by drjfloyd** [comment]
You don't have any AEROSOL species (A SPEC with AEROSOL=T).  We should be throw an error message for this.

If I add the line:
&SPEC ID='TEST',AEROSOL=.TRUE.,MEAN_DIAMETER=1e-6/

and change your AEROSOL VOLUME FRACTION SLCF to use this species, then it runs.

**Comment by drjfloyd** [comment]
I added error trapping for this.

**Comment by dvswenson** [comment]
Thank you, sorry for the error on input.
