### ISSUE TITLE
Wind and buildings

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8202]
Right now with WIND there isn't an easy way to declare regions where the wind field is not applied (i.e. the inside of a building). For buildings that are simple block shapes the current HOLE approach is workable. For a complicated geometry this is not really viable. One winds up needing to overlap HOLEs  which causes issues with devices and there is a significant effort in trying to define the large number of HOLEs needed. Also we will need to have something that works for GEOM. For WIND, FDS could use some logic similar to ZONE where one could define one or more XYZ locations and have WIND blocked. Perhaps this could just use the ZONE logic with a flag on ZONE to also block wind?

**Comment by rmcdermo** [comment]
Jason,
Try this.  The "HOLE" (that is, the region where forcing is not applied) need not really exactly conform to the building or inside of the building.  It should be actually be sufficiently far away from any obstructions.  This way the flow field around the obstructions and the pressure fields created there are not fighting against the mean forcing.

**Comment by drjfloyd** [comment]
Thanks! I'll pass that along to my co-worker.

**Comment by mcgratta** [comment]
Another thing to keep in mind. The mean forcing algorithm forces the
average velocity in the entire domain towards the user-defined value. This
means that if your building interior is relatively small compared to the
overall domain, the mean forcing may not affect significantly the flow
within the building.

>
