### ISSUE TITLE
Experimental data set?

### ISSUE THREAD

**Issue by gsmithlanl** [firemodels/fds#8205]
I am trying to find the experimental data set for the NIST_NRC Corner Effects validation case.  Can you please help me with where and how to find this data?

thanks,
Greg Smith
LANL - Safety Analyst

**Comment by mcgratta** [comment]
https://data.nist.gov/od/id/6766BF6133ED6A6CE05324570681B08C1897

>

**Comment by mcgratta** [comment]
These kinds of questions are better sent to the FDS-SMV Discussion Group.

**Comment by gsmithlanl** [comment]
Kevin,  I appreciate the quick response.  Stay safe and healthy.


Greg

________________________________
