### ISSUE TITLE
Problems in running validation files

### ISSUE THREAD

**Issue by HaodongSun-cumt** [firemodels/fds#8208]
I try to run the "Steckler_010.fds" that downoaded in the validation file. The`T_END=1800`, but the simulation stops in 180s. But in SMV, I get a 1800s simulation process.

 ` Time Step:  23500, Simulation Time:    178.38 s
 Time Step:  23600, Simulation Time:    179.21 s
 Time Step:  23696, Simulation Time:    180.00 s

STOP: FDS completed successfully (CHID: Steckler_010)`

THANKS! :)

**Comment by mcgratta** [comment]
Search the User's Guide for `TIME_SHRINK_FACTOR`.
