### ISSUE TITLE
MLRPUA adjustment incorrect with HOC on MATL line

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8210]
From Mathieu Suzanne on the [discussion forum post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fds-smv/W3PRNgrH8Xw/tr_kZj-jAgAJ)

Hi,

I have a question regarding HRRPUA and MLRPUA in FDS.

I’ve built two different simple cases TEST_HRR.fds first and TEST_MLR afterwards.

TEST_HRR contains:
- A chemical reaction based on METHANE combustion. It corresponds to a Heat_of_combustion(METHANE)= 52259.3517 kJ/kg.
- A burner defined in a SURF with a HRRPUA=200kW/m² which is then affected to an OBST.
- A material layer (BURNING_MATERIAL) with SPECIFIC_HEAT, CONDUCTIVITY, DENSITY and most important here, a HEAT_OF_COMBUSTION(BURNING_MATERIAL)=1.0E4.
- This MATL is then affected to a SURF (BURNING_SURFACE) and I define for this SURF a HRRPUA=150kW/m². This SURF is also affected to an OBST.

When I run this case, I find in the TEST_HRR.out file the following information:
- Heat of combustion of REAC_FUEL=52259.3517kJ/kg which is OK for METHANE
- For burner: HRR Per Unit Area (kW/m2) = 200 and REAC_FUEL Mass flux (kg/s/m2)=3.83E-03. The mass flux is obtained by dividing the HRRPUA defined for the Burner by the Heat of combustion of REAC_FUEL (i.e. Methane). I’m fine with these data.
- For BURNING_SURFACE: HRR Per Unit Area (kW/m2) = 150 and REAC_FUEL Mass flux (kg/s/m2)=1.50E-2. This mass flux is obtained by dividing the HRRPUA defined for the SURF BURNING_SURFACE by HEAT_OF_COMBUSTION of BURNING_MATERIAL (here 1.0E4). Again, I’m fine with these data.

Now, I modify TEST_HRR in TEST_MLR by specifying for BURNING_SURFACE a MLRPUA=1.50E2 instead of HRRPUA=150. This MLRPUA value is the same as the value found in the TEST_HRR.out. It corresponds to the HRRPUA previously defined for the SURF(BURNING_SURFACE) divided by the  HEAT_OF_COMBUSTION(BURNING_MATERIAL)=1.0E4 specified in the corresponding MATL.

When I run TEST_MLR and check the TEST_MLR.out, I have the following information.
- Heat of combustion of REAC_FUEL=52259.3517kJ/kg which is OK for METHANE
- Nothing change for the SURF(BURNER).
- The only information for BURNING_SURFACE is the REAC_FUEL Mass Flux (kg/s/m2)=7.84E-02. This is this value that I find hard to understand. I would expect to have a smaller value, 2.87E-03 obtained according to the following relationship REAC_FUEL mass flux=MLRPUA(BURNING_SURFACE)*HEAT_OF_COMBUSTION(BURNING_MATERIAL)/HEAT_OF_COMBUSTION(METHANE).
- The actual value considered by FDS in the TEST_MLR.out file is REAC_FUEL mass flux=MLRPUA(BURNING_SURFACE)/HEAT_OF_COMBUSTION(BURNING_MATERIAL)*HEAT_OF_COMBUSTION(METHANE).

Would you mind explaining what I’m missing here regarding the conversion of the MLRPUA defined in the .fds file to what is found in the .out file? As well as the difference when specifying the HRRPUA and MLRPUA?

Best regards,

MS

[TEST_MLR.fds.txt](https://github.com/firemodels/fds/files/4422529/TEST_MLR.fds.txt)

MLR_FUEL for BURNING_SURFACE should be about 0.0019 kg/s.  Instead, FDS is giving 0.048 kg/s.

**Comment by drjfloyd** [comment]
To update the issue. This looks like the calculation is OK, but what we are outputting is not consistent with what we describe in the User's Guide. Unclear variable names may have been a factor in this. A few parts to this: make variable names clearer and ensure they are all being used correctly, make sure output and Guide are clear and consistent, and add another box_burnaway case to test MLRPUA.

**Comment by mcgratta** [comment]
It appears that everything works well. Thanks.

**Comment by drjfloyd** [comment]
There is still the hrr.csv output issue. Do we change the guide to match what we output or change what we output to match the guide. The box_burn_away case use the mass.csv file.

**Comment by mcgratta** [comment]
It's probably most convenient for the hrr.csv to output the "effective" fuel generation rate, such that when multiplied by the "effective" HoC, we get the reported HRR.

**Comment by rmcdermo** [comment]
In the case where HOC_SOLID .NE. HOC_GAS, what if we output both.

**Comment by drjfloyd** [comment]
Randy, you are suggesting we add a third mass loss column to the hrr.csv file which would be MLR_FUEL unadjusted for HoC differences? I think this makes sense and be easiest I think to just always write it.

**Comment by mcgratta** [comment]
Let me look at the _hrr.csv file. The fuel printout is stored in an array
called M_DOT, which appears a number of different places. I have to remind
myself what these are for.

**Comment by mcgratta** [comment]
I'm going to overhaul the User's Guide write up of these box_burn cases.
It's confusing now as to what case does what. After that, I'll look again
at the issue of M_DOT and MASSFLUX names in the code.

>
