### ISSUE TITLE
problems about the adiabatic surface

### ISSUE THREAD

**Issue by Xiaochuan-MATE258** [firemodels/fds#8211]
if `ADIABATIC=.TRUE.` , i think i will get a higher gas temperature compare to `DEFAULT=.TRUE.` in theory

I changed the code in the 'Steckler_010' in the validation files from  `&SURF ID='FIBER BOARD', DEFAULT=.TRUE., MATL_ID='INSULATION' THICKNESS=0.013, COLOR='BEIGE' /`  to  `&SURF ID='FIBER BOARD', ADIABATIC=.TRUE., THICKNESS=0.013, COLOR='BEIGE' /`
but i got an opposite consequence.
![Graph1](https://user-images.githubusercontent.com/63101492/78356201-adab5680-75e1-11ea-8f50-cad20289c703.jpg)

**Comment by rmcdermo** [comment]
There is nothing definitive here we can track down.  I don't know what temperature this is.  I suggest you do a more thorough energy budget before jumping to the conclusion that the code has a bug.  Questions related to setup of a case should be posted to the discussion forum.

**Comment by mcgratta** [comment]
If you did exactly what you said, then no surface would be ADIABATIC because you did not include DEFAULT=T.
