### ISSUE TITLE
2-D cylindrical application of PYRO3D

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8230]
Hi folks,

I was trying to simplify a 3D pyrolysis case (set up by HT3D) to the 2D axisymmetrical model when I faced that I cannot pyrolyze the material in 2D!
It seems that 2D cylindrical codes are developed for the HT3D and PYRO3D routines in the source files (If I'm not misinterpreting the codes!). However, I couldn't apply it to my case. The material heats up but it does not pyrolyze.
I would appreciate it If someone can take a look at the attached input file to see whether I'm missing anything for an axisymmetric simulation (the same arrangement of input file works fine in a 3D cartesian setup).
TEFZEL density slices should show the pyrolyzate gas in case of something happening.

[2D_PYRO3D.fds.txt](https://github.com/firemodels/fds/files/4457257/2D_PYRO3D.fds.txt)

**Comment by JLUrban** [comment]
I added ", PYRO3D_IOR=1" at the end of the "&OBST" line and see pyrolsate production at around 64 seconds. I also tried using PYRO3D_IOR=0 (which I believe is the default: pyrolysate sent to nearest wall surface) and I did not see any pyrolsate in the slice file.

**Comment by rmcdermo** [comment]
I guess as a work around right now you can do this:
```
&OBST XB=0.0,0.1,-0.01,0.01,0.48,0.50, SURF_ID='COMBUSTIBLE_MATL', HT3D=T, PYRO3D_IOR=3/
&OBST XB=0.0,0.1,-0.01,0.01,0.00,0.48, SURF_ID='COMBUSTIBLE_MATL', HT3D=T, PYRO3D_IOR=1/
```

@mcgratta Can you have a look at the `ASSIGN_HT3D_WALL_INDICES` function and see if you can sort out why it would not assign wall cells for `PYRO3D_IOR=0`?  Thanks

Try with the attached input file below and print out `M%WALL_INDEX_HT3D(:,0)` at the end of the routine.  I see all zeros.

[2D_PYRO3D.fds.txt](https://github.com/firemodels/fds/files/4751847/2D_PYRO3D.fds.txt)

**Comment by rmcdermo** [comment]
A similar case has just been posted to the discussion forum:

a case similar to "pyro3d_wood_char" is used to demonstrate my problem. The size of a single OBST is equal to the CFD cell-size.
Specifications of the attached input files are:

1. PYRO3D_OBST_MIDDLE : the OBST is placed in the middle of the CFD domain, surrounded by the gas phase. pyrolysis works as it should.

2. PYRO3D_OBST_FLOOR_IOR0 : the OBST is placed on the inert floor, with the default pyro setting (PYRO3D_IOR=0). No pyro happens.

3. PYRO3D_OBST_FLOOR_IOR3 : previous model (OBST on the floor), but with PYRO3D_IOR=3. works as it should!

Why the second model doesn't work? Tried other materials... Everything which is located on the floor doesn't work with IOR=0.

[PYRO3D_OBST_FLOOR_IOR0.fds.txt](https://github.com/firemodels/fds/files/4758292/PYRO3D_OBST_FLOOR_IOR0.fds.txt)
[PYRO3D_OBST_FLOOR_IOR3.fds.txt](https://github.com/firemodels/fds/files/4758293/PYRO3D_OBST_FLOOR_IOR3.fds.txt)
[PYRO3D_OBST_MIDDLE.fds.txt](https://github.com/firemodels/fds/files/4758294/PYRO3D_OBST_MIDDLE.fds.txt)

**Comment by mcgratta** [comment]
I think I fixed the original problem. I never considered 2D obstructions when writing the algorithm to determine the shortest path for fuel gases to reach the surface. For 2D, the shortest path was always to the MIRROR boundary which is inactive. 

Check that things are working properly. I think the original case is working properly, but double check.

**Comment by MortezaHaghighi** [comment]
Thank you, Kevin and Randy,
I tried cylindrical and cartesian. 2D simulations look fine to me.

Still, the problem with PYRO3D_OBST_FLOOR_IOR0 has remained. that one's bug ought to be somewhere else.

Cheers

**Comment by rmcdermo** [comment]
I am not sure we are out of the woods with 2D either.  The attached 2D case does not give the same results between PYRO3D_IOR=0 and PYRO3D_IOR set explicitly for each OBST (for a problem that should be nominally equivalent).  I'm investigating.

**Comment by mcgratta** [comment]
I forgot to consider CYLINDRICAL. I need to block off the lower x direction from consideration.

**Comment by rmcdermo** [comment]
OK, I think I see how this works now.  I will work on a fix.

**Comment by mcgratta** [comment]
I think you just need to add to the if statement I added
```
IF (TWO_D) THEN  ! Don't search for a fuel path in the y direction
   CELL_COUNT( 2) = 1000000
   CELL_COUNT(-2) = 1000000
   IF (CYLINDRICAL) CELL_COUNT(-1) = 1000000
ENDIF
```

**Comment by rmcdermo** [comment]
I don't know... It looks to me like the current code ought to work for CYLINDRICAL.  You should never hit a gas cell moving in -1 direction.

If you do, it is possible the CYLINDRICAL case has a donut geometry and you want to consider the inside.

**Comment by mcgratta** [comment]
True, so my change should not be made.

>

**Comment by mcgratta** [comment]
I think I can fix the problem with PYRO3D_OBST_FLOOR_IOR0.fds

**Comment by mcgratta** [comment]
I simplified the logic for finding nearest surfaces. Hopefully this should account for 2D and single cell cases.

**Comment by rmcdermo** [comment]
@mcgratta Thanks.  This looks good to me.  I added an output that allows you to show the PYRO3D IOR with a slice.  Now, all four cases look reasonable.  I also tested the PYRO3D_IOR=0 case for 2D with a donut geometry and it worked.  See below.

Note that for the PYRO3D_OBST cases there is only one cell and the IOR that gets chosen depends on the order that things are processed in ASSIGN_HT3D_WALL_INDICES.

@JLUrban @MortezaHaghighi Please test your cases with the latest code and confirm if we can close this issue.  Thanks

<img width="522" alt="Screen Shot 2020-06-12 at 9 01 50 AM" src="https://user-images.githubusercontent.com/4418497/84505230-613c6100-ac8b-11ea-8dba-cf73266f5ae8.png">

<img width="752" alt="Screen Shot 2020-06-12 at 8 42 59 AM" src="https://user-images.githubusercontent.com/4418497/84505245-68636f00-ac8b-11ea-9c1a-025abaf8ca2e.png">

<img width="752" alt="Screen Shot 2020-06-12 at 8 46 47 AM" src="https://user-images.githubusercontent.com/4418497/84505265-6ef1e680-ac8b-11ea-9820-1f517c023f35.png">

<img width="752" alt="Screen Shot 2020-06-12 at 8 48 34 AM" src="https://user-images.githubusercontent.com/4418497/84505274-74e7c780-ac8b-11ea-9f0a-79c590df3fab.png">

**Comment by rmcdermo** [comment]
@mcgratta Should we reorganize ASSIGN_HT3D_WALL_INDICES so that PYRO3D_IOR=3 is chosen on a corner?  In general, I think this would be the preferred direction.

**Comment by mcgratta** [comment]
I don't understand what you mean.

**Comment by rmcdermo** [comment]
Look at the above image for the 2D_PYRO3D case.  Look at the corner cells at the top of the OBST.  The top right and top left corners have selected +1 and -1, respectively.  I am suggesting these should be +3.  This could be achieved by reordering the loops in ASSIGN_HT3D_WALL_INDICES.

**Comment by mcgratta** [comment]
Yes, I understand. +3 takes precedence over the others.

**Comment by mcgratta** [comment]
The Fortran gods smile upon thee.

**Comment by rmcdermo** [comment]
Nice.  Looks good.  I may add a comment to the code to explain the choice.

<img width="752" alt="Screen Shot 2020-06-12 at 10 19 30 AM" src="https://user-images.githubusercontent.com/4418497/84513008-d3667300-ac96-11ea-94b1-56b02748e441.png">

**Comment by MortezaHaghighi** [comment]
Thank you @rmcdermo & @mcgratta for the debug. The development of this 2D pyrolysis would be a jump for my research activities.
Sorry for the late response, I was quite busy with some other stuff. I'll make room for checking out the test cases and will return to you in couple of days hopefully.
PS, Randy, what is the quantity for that IOR you added?

**Comment by rmcdermo** [comment]
Use a slice of 'PYRO3D IOR'

**Comment by MortezaHaghighi** [comment]
Dividing the domain into two meshes in z-direction for the 2D_PYRO3D case:

1. when OBST is partially in each of the meshes, I think pyrolysis works fine:

&MESH ID='MESH1', IJK= 20,1,20, XB = 0.0,0.4,-0.01,0.01,0.0,0.40, CYLINDRICAL=.TRUE. /
&MESH ID='MESH2', IJK= 20,1,30, XB = 0.0,0.4,-0.01,0.01,0.40,1.0, CYLINDRICAL=.TRUE. /
&OBST XB=0.0,0.1,-0.01,0.01,0.00,0.50, SURF_ID='COMBUSTIBLE_MATL', HT3D=T/

------------------------------------------------------------------------------------------------
2. However, when OBST is completely in one mesh, I see no pyrolysis reaction happening:

&MESH ID='MESH1', IJK= 20,1,30, XB = 0.0,0.4,-0.01,0.01,0.0,0.60, CYLINDRICAL=.TRUE. /
&MESH ID='MESH2', IJK= 20,1,20, XB = 0.0,0.4,-0.01,0.01,0.60,1.0, CYLINDRICAL=.TRUE. /
&OBST XB=0.0,0.1,-0.01,0.01,0.00,0.50, SURF_ID='COMBUSTIBLE_MATL', HT3D=T/

**Comment by rmcdermo** [comment]
I have reproduced your problem.  Sorry about this.  Growing pains...

In the first case that works, PYRO3D_IOR is being set correctly, as below:

<img width="752" alt="Screen Shot 2020-06-17 at 8 06 19 AM" src="https://user-images.githubusercontent.com/4418497/84896213-8eb15200-b071-11ea-90e5-1dd2f9dc212a.png">

In the second case that does not work PYRO3D_IOR is still 0.  We'll sort this out.

<img width="752" alt="Screen Shot 2020-06-17 at 8 05 20 AM" src="https://user-images.githubusercontent.com/4418497/84896284-aee11100-b071-11ea-9ca4-996c51a81383.png">

**Comment by rmcdermo** [comment]
Should be fixed with PR #8448

**Comment by MortezaHaghighi** [comment]
I've been using 2D simulations since then, and have not encountered new bugs or problems so far.
You may close the issue though.
Thanks

**Comment by rmcdermo** [comment]
Thanks for testing.  Keep the Issues coming.  But please understand that several things will need a complete overhaul, which is planned, but has not reached top of the to-do list yet.

**Comment by MortezaHaghighi** [comment]
Around line 721 of wall.f90
Shouldn't we have another CASE selection for 2D cases (i.e. VSRVC to the power of 1/2)?
Am I misunderstanding sth?

**Comment by rmcdermo** [comment]
Probably.  Try to create an obvious verification case.  And if your idea is right go ahead and modify the code.  (And push up your verification case). Thanks

**Comment by MortezaHaghighi** [comment]
@rmcdermo 
-Please reopen the issue (if you agree so).
-I'm kinda confused as to what quantity to dump for showing the effects of VSRVC! Any suggestion?
-I'm quite sure that the 2D case is missing. Here's what I propose:

![VSRVC](https://user-images.githubusercontent.com/56713983/107232626-4abcf400-6a2a-11eb-9710-04a6dbedfa8f.JPG)

**Comment by rmcdermo** [comment]
I think you just want to dump `'SOLID CELL VOLUME RATIO'`.

Send a PR with your change.  But use `0.5_EB` in the exponent.

**Comment by mcgratta** [comment]
What is the status of this issue?

**Comment by rmcdermo** [comment]
Looks like someone pushed up the change at some point and forgot to close.
