### ISSUE TITLE
Remove KILL_RADIUS

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8237]
The parameter `LPC%KILL_RADIUS` seems unnecessary given `LPC%MINIMUM_DIAMETER`, but I don't understand its origin or how it is calculated. Let's remove it and just use MIN_DIAM, or some fraction of it, in part.f90. If you don't know where `KILL_RADIUS` comes from, kick it to Simo.

**Comment by drjfloyd** [comment]
They are not the same thing.  One defines the minimum diameter used for the size distribution. The other defines when the particle is removed.  If they were the same you would never get particles at the small end of the distribution as they would be removed in the same timestep they are injected . If you look in read you will see that kill radius is set to be 0.5 % of the mass at the minimum diameter.

**Comment by drjfloyd** [comment]
Looking at the guide I see it doesn't give the correct description after KILL_DIAMETER was added. I'll edit the guide.

**Comment by drjfloyd** [comment]
Edited the guide in Section 17.3.3

**Comment by mcgratta** [comment]
This bit of code is confusing. Radii are being set to diameters, and the comment says remove particle if its mass is less than 0.5% of its diameter.
```
   IF (MINIMUM_DIAMETER<0._EB) THEN
      MINIMUM_DIAMETER                  = 0.005_EB*DIAMETER
   ENDIF
   LPC%MINIMUM_DIAMETER                 = MINIMUM_DIAMETER*1.E-6_EB
   IF (MONODISPERSE) THEN
      LPC%KILL_RADIUS                   = MINIMUM_DIAMETER*1.E-6_EB
   ELSE
      LPC%KILL_RADIUS                   = (MINIMUM_DIAMETER**3*0.005_EB)**ONTH*1.E-6_EB ! Kill if mass <= 0.5 % of MINIMUM_DIAMETER
   ENDIF
```

**Comment by drjfloyd** [comment]
I'll clean it up.

**Comment by drjfloyd** [comment]
Added the input KILL_DIAMETER to let the user set this and cleaned up the logic in read.f90 to hopefully make it easier to follow.

**Comment by drjfloyd** [comment]
Closing the issue.
