### ISSUE TITLE
Add MOVE_ID of a parent MOVE line to &MOVE, apply transforms recursively.

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#8260]
@emanuelegissi : It would be very handy to have the MOVE_ID field in &MOVE such that transformations can be nested up a kinematic tree. Imagine we have two chairs with transformations:

&MOVE ID='chair1', ..... , MOVE_ID='table' /
&MOVE ID='chair2', ..... , MOVE_ID='table' /

to the body reference frame of a table, which in turn is transformed by 

&MOVE ID='table', ... , /

to the FDS Eulerian frame. 

I envision these transforms being applied recursively, i.e. for a VERT position of chair1
{XYZ} = [T_table]  ( [ T_chair1]  {XYZ_chair1})
 
which would involve applying the TRANSFORM_COORDINATES(X,Y,Z,MOVE_INDEX) routine recursively on a MOVE ID and all the parent MOVE IDs up to a 'null' MOVE_ID field. This seems to be the simplest way to do this. Also, transformation matrices can be computed and stored in MOVEMENT(MOVE_INDEX)%M at read time, s.t. we don't need to recompute them for each point involved. 3x3 transformation matrices can be padded to conform to a single 3x4 format. 

This simple functionality enhancement would allow the user to define groups of objects, or object-device sets, and eventually object-vents-devcs sets, etc., without us having to explicitly define new namelists.

Let's think about this.

**Comment by emanuelegissi** [comment]
Yes! Thanks.

**Comment by mcgratta** [comment]
How about if we just allow multiple MOVE_IDs on the GEOM line:
```
&GEOM XB=..., MOVE_IDS='chair_1','table_2',... /
```
This way we could have as many moves as we want.

**Comment by marcosvanella** [comment]
This is also a good option, the application of the move transforms would take the sequence from MOVE_IDS(1) to the last non - 'null'. We could combine one relative position 'chair_1' with several parents 'table_1', 'table_2' etc in different &GEOM lines using the same binary for example. So that is extra flexibility. We would have to add MOVE_IDS to the namelists that have MOVE_ID in the same manner we have SURF_ID, SURF_IDS, etc.

**Comment by rmcdermo** [comment]
I'm not sure that having a list of MOVE_IDs on GEOM is the same as allowing MOVE to have a MOVE_ID and chaining them together.  I think the latter is more flexible.

**Comment by marcosvanella** [comment]
Lets think about this. Imagine you have two sets of tables with two chairs each, in the same arrangement but different positions in a room, given by 'table_1', 'table_2'. The chairs are located relative to the tables (of same type, same arrangement) using transforms 'chair_1', 'chair_2'.

With MOVE_ID of the parent on the MOVE line we would have:

```
&MOVE ID='table_1', ... /
&MOVE_ID='table_2', .../
&MOVE ID='chair_1_t1', ... All params of chair_1 ..., MOVE_ID='table_1' /
&MOVE ID='chair_2_t1', ... All params of chair_2 ..., MOVE_ID='table_1' /
&MOVE ID='chair_1_t2', ... All params of chair_1 ..., MOVE_ID='table_2' /
&MOVE ID='chair_2_t2', ... All params of chair_2 ..., MOVE_ID='table_2' /
```

and the chair geoms:

```
&GEOM ID='CHAIR_1_T1', ... , MOVE_ID='chair_1_t1' /
&GEOM ID='CHAIR_2_T1', ... , MOVE_ID='chair_2_t1' /
&GEOM ID='CHAIR_1_T2', ... , MOVE_ID='chair_1_t2' /
&GEOM ID='CHAIR_2_T2', ... , MOVE_ID='chair_2_t2' /
```

With the MOVE_IDS option we can achieve the same result with:

```
&MOVE ID='table_1', ... /
&MOVE_ID='table_2', .../
&MOVE ID='chair_1', ... All params of chair_1 ... /
&MOVE ID='chair_2', ... All params of chair_2 ... /
```

and geoms:

```
&GEOM ID='CHAIR_1_T1', ... , MOVE_IDS='chair_1','table_1' /
&GEOM ID='CHAIR_2_T1', ... , MOVE_IDS='chair_2','table_1' /
&GEOM ID='CHAIR_1_T2', ... , MOVE_IDS='chair_1','table_2' /
&GEOM ID='CHAIR_2_T2', ... , MOVE_IDS='chair_2',table_2' /
```
Ema feel free to chip in on this.

**Comment by mcgratta** [comment]
Currently, MOVE is a rotation around an axis with a fixed base point, plus a translation. Compounding these might be trouble.

**Comment by rmcdermo** [comment]
I'm not saying you can't ultimately do the same thing.  But suppose you wanted to put 10 chairs around a round table (Knights of the Round Table).  You either have to define 10 different angles (in this can not hard), or you could define one angle and daisy-chain these together 10 times.  For defining groups and rotations of groups of things, I would think the chain approach is much more general.

**Comment by marcosvanella** [comment]
For transformations to be compounded, you always have to think that the parameters you put in your transformation are based on your parents reference frame (it is relative). For the ten chairs in your comment, each of them would be a parent of the next and the parameters would probably be the same for all chair MOVEs, but unless we implement some kind of mult on &MOVE the MOVE lines have to be written. If this is what needs to be done, I don't see much gain respect to defining a different angle on each. On the other hand, if we use MOVE_IDS the most logical thing would be write for each chair the transformation to the table frame and have MOVE_IDS='chair_i','table' for each chair i. Using the chairs chained to each other would lead to up to 11 MOVEs in MOVE_IDS.

**Comment by emanuelegissi** [comment]
I like both of your point of views.

Let's take the example of two round tables t1 and t2 with ten chairs each
c1_1, c2_1, ... and c1_2, c2_2, ...
If I need to change the position/rotation/scale of the table t1, i want its
chairs (c1_1, c2_1, ... ) to change with it.
If I move a chair of table t1, I would probably like the same movement of
the same chair of table t2. Or I would like to break this dependence.

So I suggest the following compact but flexible notation.

The MOVEs with their T34 matrices (or rotation and axis ...). Each of them
represents a transformation: moving, rotating and scaling.

&MOVE ID='table_1', T34=... /
&MOVE_ID='table_2', T34=... /
&MOVE ID='chair_1', T34=... /
&MOVE ID='chair_2', T34=... /

and the GEOMs that represent the objects and their relations:
&GEOM ID='TABLE_T1', ... , MOVE_ID='table_1' /
&GEOM ID='TABLE_T2', ... , MOVE_ID='table_2' /

&GEOM ID='CHAIR_1_T1', ... , PARENT_GEOM_ID='table_1', MOVE_ID='chair_1' /
&GEOM ID='CHAIR_2_T1', ... , PARENT_GEOM_ID='table_1', MOVE_ID='chair_2' /
...
&GEOM ID='CHAIR_1_T2', ... , PARENT_GEOM_ID='table_2', MOVE_ID='chair_1' /
! reuse of the same MOVE line
&GEOM ID='CHAIR_2_T2', ... , PARENT_GEOM_ID='table_2', MOVE_ID='chair_2'
/ ! reuse of the same MOVE line

or, if you do not want the chairs of the second table to inherit the
movement:

&GEOM ID='CHAIR_1_T2', ... , PARENT_GEOM_ID='table_2', MOVE_ID='chair_1_t2'
/ ! a different MOVE line
&GEOM ID='CHAIR_2_T2', ... , PARENT_GEOM_ID='table_2', MOVE_ID='chair_2_t2'
/ ! a different MOVE line

Just my 2 cents...
Emanuele

**Comment by emanuelegissi** [comment]
Forgot to add.

As Randy was asking, you can chain the chairs, adding rotations one after
the other like this:

&GEOM ID='CHAIR_1_T1', ... , PARENT_GEOM_ID='table_1', MOVE_ID='chair_1' /
&GEOM ID='CHAIR_2_T1', ... , PARENT_GEOM_ID='CHAIR_1_T1', MOVE_ID='chair_1'
/ ! reuse the same MOVE line

**Comment by rmcdermo** [comment]
Here is an example to consider, sticking with the round table theme.

You have a ball room for a wedding with 200 chairs arranged around 20 round tables that are randomly arranged in the room.

I have a GEOM line for GEOM_ID='chair' and a GEOM line for GEOM_ID='table'.

What scheme gives the clearest, simplest input file?

**Comment by marcosvanella** [comment]
Ema, I think that whatever we do, we would like to make it general for all namelists that use MOVE_ID, (including DEVCs, eventually VENTS). This is why I liked the original idea where the parent of a MOVE line is another MOVE line.

**Comment by emanuelegissi** [comment]
Yes, you are right. I had forgotten about that.

What about extending PARENT_ID and MOVE_ID to DEVCs and VENTs?

This way you clearly separate the transformations and the chains.

But I still like the simplicity of the chains of MOVEs, even if there is
some redundancy.

**Comment by marcosvanella** [comment]
Ema, so in this option we get rid of the parent MOVE_ID on the &MOVE lines? 
Also, PARENT_ID refers to a MOVE line or the type being worked on (GEOM, DEVC, etc.)?

**Comment by bwklein** [comment]
Or, there is this thing called PyroSim that already does this stuff. :D

Best Regards,
-Bryan Klein
klein@thunderheadeng.com
Product Manager, PyroSim/Pathfinder
Thunderhead Engineering Consultants, Inc.
Website - http://www.thunderheadeng.com

**Comment by marcosvanella** [comment]
Bryan! Is that true? :)

**Comment by emanuelegissi** [comment]
@bryianklein Indeed a good option as well, leaving it to preprocessing...

@marcosvanella Yes, that was the idea. MOVE_ID refers to the local
transformation, and PARENT_ID refers to the parent entity, be it a GEOM, a
DEVC, or a VENT. A problem of this solution is that it doesn't allow groups
of heterogeneous entities, GEOMs and DEVCs for example, unless you let
PARENT_ID refer to any other namelist. I do not think you would like that.
On the other hand both the initial proposal (chain of MOVEs) and Kevin's
(MOVE_IDS vectors) allow groups of heterogeneous entities, so they are
better.

At this point let's make a comparison using Randy's 20 round tables and 200
chairs in total.
I suppose that the chairs around each table are positioned in the same
relative position.
I also add a DEVC at the center of each table to show heterogeneous
grouping.

*1) Chain of MOVEs*
No sharing of MOVEs is possible, each entity has its own MOVE line.

! Table 1, its chairs and a DEVC
&MOVE ID='table_1' T34=... /
&GEOM ID='table_1' MOVE_ID='table_1' READ_BINGEOM=T BINGEOM_FILE='table' /

&MOVE ID='temp_t1' MOVE_ID='table_1' T34=... /
&DEVC ID='temp_t1' MOVE_ID='temp_t1' QUANTITY='TEMPERATURE' /

&MOVE ID='chair_1_t1' MOVE_ID='table_1' T34=... /
&GEOM ID='chair_1_t1' MOVE_ID='chair_1_t1' READ_BINGEOM=T BINGEOM_FILE='chair'
/
&MOVE ID='chair_2_t1' MOVE_ID='table_1' T34=... /
&GEOM ID='chair_2_t1' MOVE_ID='chair_2_t1' READ_BINGEOM=T BINGEOM_FILE='chair'
/
...

*2) MOVE_IDS vector*
Local transformation can have shared MOVEs.

! Local transformations of the chairs (shared)
&MOVE ID='temp' T34=... /
&MOVE ID='chair_1' T34=... /
&MOVE ID='chair_2' T34=... /
...

! Table 1, its chairs and a DEVC
&MOVE ID='table_1' T34=... /
&GEOM ID='table_1' MOVE_IDS='table_1' READ_BINGEOM=T BINGEOM_FILE='table' /

&DEVC ID='temp_t1' MOVE_IDs='temp','table_1' QUANTITY='TEMPERATURE' /

&GEOM ID='chair_1_t1' MOVE_IDS='chair_1','table_1' READ_BINGEOM=T
BINGEOM_FILE='chair'
/
&GEOM ID='chair_2_t1' MOVE_IDS='chair_2','table_1' READ_BINGEOM=T
BINGEOM_FILE='chair'
/
...

**Comment by marcosvanella** [comment]
Ema, I was thinking also MOVE_IDS provides nice flexibility. The cost is that if you have many compounded transforms you might end up with a long MOVE_IDS vector. 
Would we end up with as many move lines if we go with approach 1 in the general case? Are there any savings going with 1? 

Going back to the 20 tables and making a chain between chairs 1 to 10 and linking chair 10 with each table. It seems to me if we go the way of 1 we will have to explicitly write all transformations for each table to have chairs number 10 linked properly to different tables. That was the nice thing of using the PARENT_GEOM_ID. 

Now, circling back to Randys question. For people writing the input file by hand, a mult line on MOVE, defining the final PARENT_ID of the chain and increments in the parameters, and a geom with said MOVE that would span all the chairs for a table for example, would replace 10 MOVE lines and 10 GEOM lines by one &GEOM, one &MOVE and one &MULT. Then, with a &MOVE and &GEOM for the table we would complete one table + chairs set.
This is not to do now, trying to think forward here. Within FDS we can go either way 1 or 2. 

For preprocessors this is not important as each geometry line can be written with the composite transformation on its own &MOVE T34.

As you said, any of the two would work. I think for kinematic trees with a few levels MOVE_IDS looks cleaner.

**Comment by emanuelegissi** [comment]
I fully agree with you, after discussion I also prefer MOVE_IDS.

**Comment by mcgratta** [comment]
I'm going to close this issue. I'd rather maintain a very simple MOVE feature within FDS, and leave more complicated geometry manipulation to third party software.
