### ISSUE TITLE
Allow different I,J,K for DEVC QUANTITY's

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8269]
Now that `FACE_CENTERED` device `QUANTITY`s interpolate differently than `CELL_CENTERED`, we must allows `QUANTITY` and `QUANTITY2` to have separate IJK values.

**Comment by mcgratta** [comment]
These changes passed firebot and appear to be working.

**Comment by RIO4FDS** [comment]
> These changes passed firebot and appear to be working.

Everything working fine with fds2ftmi verification cases either! :)

**Comment by mcgratta** [comment]
Good to hear. The functionality is internal---hopefully it does not alter inputs and outputs.
