### ISSUE TITLE
FDS+EVAC soft stop

### ISSUE THREAD

**Issue by rupole1185** [firemodels/fds#8274]
I recently have worked on FDS+EVAC. I noticed a weird behaviour when I apply the soft stop (generation of the *.stop file to gently stop the simulation).

In version 6.7.0 and 6.7.1 I have confirmed that:
- if the simulation is performed in serial the soft stop works OK
- if the simulation is performend using MPI (_mpiexec_) the soft stop doesn't stop the simulation

The behaviour appears ONLY when using FDS+EVAC [so everything is OK if we just run FDS]. I haven't checked the problem on version 6.7.4, I will do it this week.

Thanks.

**Comment by rmcdermo** [comment]
Is this only EVAC related?  Or are you seeing this behavior in FDS by itself?  Please include a simple input file.

**Comment by rupole1185** [comment]
Attached you can find the FDS file I used to detect the problem. The soft stop appears in FDS itself but only when EVAC module is activated. In such a case, I basically can't stop the simulation with the *.stop file if fds has been launched with MPI. I need to kill FDS execution.
Everything works OK if the simulation is serieal.

[test_oggetto_predefinit.txt](https://github.com/firemodels/fds/files/4506696/test_oggetto_predefinit.txt)

**Comment by rmcdermo** [comment]
@mcgratta The issue here is that the first mesh (MPI_PROCESS 0) is not finishing radiation and getting stuck here:

`IF (STOP_AT_ITER==0 .AND. .NOT.RADIATION_COMPLETED) RETURN`

So, if you turn off radiation, the shutdown works.  I waited to see if maybe we just needed to let radiation finish.  But the case does appear to hang.  I'm not sure of the best solution here.  Do we care that the case finishes radiation angles for an Evac case?

**Comment by rmcdermo** [comment]
@mcgratta The issue here is related to completion of radiation iterations.  Process 0 (first mesh) gets stuck here:

```
      IF (STOP_AT_ITER==0 .AND. .NOT.RADIATION_COMPLETED) RETURN
```

in `CHECK_STOP`.  I'm not sure the best solution.  Do we need cases to finish radiation for Evac?

**Comment by mcgratta** [comment]
I'll take a look at it. I've never considered Evac in the stop logic.

**Comment by mcgratta** [comment]
The code I just committed makes this case work. Basic idea is to make RADIATION_COMPLETED an array from 1 to NMESHES, and check that all meshes are completed.

**Comment by rmcdermo** [comment]
Great job.  Thanks.  I'll test probably tomorrow.

**Comment by rupole1185** [comment]
Perfect guys! Great work of the whole team. I am now looking forward the next version with the fix in place.

Thanks for everything.

**Comment by rmcdermo** [comment]
Works on my end.
