### ISSUE TITLE
FDS 6.7.3 Problem of MPI_PROCESS

### ISSUE THREAD

**Issue by poonyc2003** [firemodels/fds#8275]
Hi, I tried to simulate my FDS input file for 600s by using 4 cores. However, error codes were come out around 270s.
Below is the error code:
connection to proxy 0 at host "my computer name" failed
callback returned error status
error waiting for event
process manager error waiting for completion

After opened up the CMDfds and changed directories, I typed below codes to run my file:
1. set OMP_NUM_THREADS=4
2. mpiexec -n 4 fds job_name.fds

May I know which part is incorrect?
If I used single core to run the file, it spent too much time so I need to speed up the simulation time by running the FDS parallel. Thank you.

**Comment by poonyc2003** [comment]
[Scenario 1.pdf](https://github.com/firemodels/fds/files/4504109/Scenario.1.pdf)

**Comment by mcgratta** [comment]
What is your operating system? How many cores do you have per node?

**Comment by poonyc2003** [comment]
I am using Windows 10 and Intel Core i7-8550U 

![Error Code](https://user-images.githubusercontent.com/47946078/79763656-f17abb80-8356-11ea-96d6-7e17af8e160e.jpeg)

**Comment by poonyc2003** [comment]
This error is occurred again and again.
My colleague said I need to install MPICH for running FDS parallel but the current FDS User's Guide said MPICH is no longer support Windows Version....

![Error Code2](https://user-images.githubusercontent.com/47946078/79763855-2edf4900-8357-11ea-8464-fb2bce657386.jpeg)

**Comment by gforney** [comment]
I see pyrosim in your directory path name.   Are running fds from the
pyrosim installation or from the nist bundle. If from nist are you running
in the CMDfds shell.

**Comment by poonyc2003** [comment]
Yes, I used Pyrosim to build up the model and then export to FDS file. After that, I used CMDfds to run my file.

https://www.thunderheadeng.com/2015/12/assign-fds-meshes-to-specific-processes/

Because I don't understand how to setup the file according to the information from above link to run parallel in Pyrosim...

**Comment by sbenkorichi** [comment]
How many cores you have on your machine? I see you set OMP_NUM_THREADS=4 
You can ask Pyrosim support on their website if you don't know how to set mpi processes, although the link you provided seems straight forward. 
https://forum.thunderheadeng.com/index.php?board=1.0

**Comment by mcgratta** [comment]
This may be a conflict between the libraries installed by PyroSim and those by the FDS installer. Also, I tried to run the case and it used almost all of the 16 GB that I have on my laptop, even before the time stepping started. I had to kill the job. So here are some possibilities:

1. Conflict with PyroSim
2. Job too big for your computer

**Comment by poonyc2003** [comment]
Thanks. I will try to re-write my code without using PyroSim.
However, as this is my research project and I need to simulate a fire occurred in a 500m tunnel, may I know how to reduce the project size? I only know reduce the mesh size is a method...

> This may be a conflict between the libraries installed by PyroSim and those by the FDS installer. Also, I tried to run the case and it used almost all of the 16 GB that I have on my laptop, even before the time stepping started. I had to kill the job. So here are some possibilities:
> 
> 1. Conflict with PyroSim
> 2. Job too big for your computer

**Comment by gforney** [comment]
If there is a conflict it would be that pyrosim is installed not that it
was used to create your case. Assuming it is not hard to uninstall and
reinstall pyrosim i would uninstall pyrosim, reboot then run your case
again to see if you still have a problem.

**Comment by mcgratta** [comment]
You probably need to use a compute cluster to do a calculation like this. Your single computer probably does not have enough cores and memory.
