### ISSUE TITLE
Cluster Simulation problem

### ISSUE THREAD

**Issue by L4HITW** [firemodels/fds#8289]
![screens](https://user-images.githubusercontent.com/53295622/80112584-c966a480-8570-11ea-8d7e-30984c8842fd.jpg)
Hello.
I have installed 1 licensed Pyrosim and 1 not licensed(just installed on another pc). The cluster simulation is running, but no files are created in fds folder. I can see fds processes in both computers. Here is the log of Pyrosim
 
 
ENV:  {PATH=C:\Program Files\PyroSim 2020\fds;C:\Program Files\PyroSim 2020\fds\mpi;C:\WINDOWS;C:\WINDOWS\system32}
CMD:  "C:\Program Files\PyroSim 2020\fds\runfds.exe" "C:\Program Files\PyroSim 2020\fds\mpi\mpiexec.exe" -genvnone -gwdir \\frisk\newfds\test\test -genv PATH "C:\Program Files\PyroSim 2020\fds;C:\Program Files\PyroSim 2020\fds\mpi;C:\WINDOWS;C:\WINDOWS\system32" -genv OMP_NUM_THREADS 1 -genv OMP_STACKSIZE 16M -host fds-pc -n 3 fds.exe test.fds : -host frisk -n 3 fds.exe test.fds
WDIR: \\frisk\newfds\test\test
 
 Starting FDS ...
 
 MPI Process      0 started on FDS-PC
 
All computers have access to shared folder on PC frisk(read write access).
In task manager I noticed that FDS process is not writing on disk
When starting cluster simulation using just 1 any of these computers everything works fine, but when running together no bytes is written on disk.
Please advice me what to do, to solve the problem. My network is built by gigabit switches.
I have tried also to run from fds command line. Works only if I run just one pc in the network no matter from what PC run.

**Comment by drjfloyd** [comment]
This is not a forum for Pyrosim support. Please refer questions on Pyrosim to Thunderhead Engineering.
