### ISSUE TITLE
Jet Fan Simulation in Tunnel

### ISSUE THREAD

**Issue by poonyc2003** [firemodels/fds#8295]
I would like to simulate the activation of jet fan in tunnel.
However, after 600s simulation, the jet fan did not activate.
May I know if there is any error of my input file?

[Scenario 1.txt](https://github.com/firemodels/fds/files/4530169/Scenario.1.txt)

**Comment by rmcdermo** [comment]
Please submit your question to the discussion forum.  The Issue tracker is for bug reports.
