### ISSUE TITLE
Add stochastic inputs and outputs for solid phase particles

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8301]
The motivation for this feature request is to allow solid phase particles to be used as ember particles more easily, both from an input and output perspective.

Inputs:
* Allow for random particle velocity distribution for each component

Outputs:
* Allow PDPA for solid particles
* Allow MPUA for solid particles
* Allow particle histograms for solid particles

Use NIST dragon cases as examples.

https://github.com/firemodels/fds/blob/master/Verification/WUI/dragon_5a.fds

**Comment by drjfloyd** [comment]
- Allow size distributions for solid particles
- Allow for particle spin and angle of attack
- Decrease all dimensions for non-spherical particles due to pyrolysis
-0D pyrolysis model
-Develop more flexible approach for defining where and when to inject particles
-Allow solid particles to transfer heat to walls
-Develop method for surface ignition from solid particles

**Comment by mcgratta** [comment]
I've started to work this issue. It appears that the PDPA function works for all particles, not just liquid. Is there a particular example that is not working.

I'm adding MPUA now, plus other stuff.

**Comment by rmcdermo** [comment]
I may have just assumed PDPA would not work.  I'll ask Kuldeep if he has run into this.

The main case was the dragon case looking at the mass distribution on the floor.  So, MPUA was important there.

**Comment by mcgratta** [comment]
As a work-around, QUANTITY='MPUV' and SPATIAL_STATISTIC='VOLUME INTEGRAL'
works. But MPUA should work soon.

>

**Comment by rmcdermo** [comment]
I believe that is what Kuldeep used in the interim.  He said he had issues with PDPA and that he would post his case.

**Comment by mcgratta** [comment]
I committed a test case called `WUI/hot_rods.fds` that demonstrates that we can have a size distribution of solid particles. This was not well documented. Also, MPUA works for solid and liquid particles.

**Comment by mcgratta** [comment]
I believe that the original issues were all addressed. If not, start a new issue with the specific request.
