### ISSUE TITLE
_steps.csv, feature request

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#8303]
Good morning All,

I've been working on a large building with complicated fire spread and leakage. I've succumbed to feature-creep and the time steps reduce until a numerical instability occurs. I've found the _steps.csv file very useful  in trouble-shooting this by plotting step size against wall time. (see attached)

The wall time quantity comprises the date, time and time zone information. What I'm interested is in plotting the step size against elapsed wall time. Elapsed time can be displayed by stripping off the date and time zone, and adjusting for the clock rolling over at midnight, but it takes some effort to accomplish.

Could you add a column to _steps.csv with elapsed wall time in seconds? That would allow users to set the time scale to elapsed seconds, hours (my preference) or days.

Thanks

Dave

![time steps](https://user-images.githubusercontent.com/13259079/80602272-e54cc900-89fc-11ea-8d31-e621da83aae1.PNG)

**Comment by drjfloyd** [comment]
I think that is a good idea. We could easily do it by writing the intrinsic function CPU_TIME to the file. You should be able to do this now with the device file by defining a TIME STEP and CPU TIME DEVC. You should set TIME_AVERAGED to FALSE for the CPU TIME so you don't get the average time over the output interval.

**Comment by Dave-McGill** [comment]
Thanks Jason; I'll give it a try.

**Comment by drjfloyd** [comment]
I added a column for CPU time to the steps.csv file.

**Comment by Dave-McGill** [comment]
Thanks
