### ISSUE TITLE
Add LEAK_PATH_ID to SURF

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8329]
It would be useful to allow SURF to have either LEAK_PATH(2) or LEAK_PATH_ID(2). For simple geometries with a handful of ZONEs, LEAK_PATH isn't too cumbersome but if you had a lot of ZONEs (say a multi-story building with multiple rooms per floor)  being able to give the ZONE an ID and then use the ID on the SURF would be useful.  Would just need to move the leak path assignment out of READ_SURF and into PROC_SURF_1 so it is done after READ_ZONE.

**Comment by mcgratta** [comment]
I suggest that you convert LEAK_PATH_ID to LEAK_PATH within read.f90 so that you don't have to carry around both identifiers throughout the code.

**Comment by drjfloyd** [comment]
That is the plan.  In READ_SURF error check to make sure both aren't defined. Then in PROC_SURF_1, if  the ID was used  set up a loop to determine the index number.

**Comment by mcgratta** [comment]
Remember to add the parameter to the FDS User's Guide, thanks.

**Comment by drjfloyd** [comment]
I will. Doing two commits so source change is separate from doc change.

**Comment by mcgratta** [comment]
I prefer one commit because then the change you made is self-documenting.
