### ISSUE TITLE
3D pyrolysis model does not work for a special case

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8360]
Hi

In my pyrolysis model, SURF goes to two MATLs: 1. complete evaporation of volatiles 2. a solid ... however, is a charring case (does not burn away at the end)
The case runs fine with the 1D PYRO model.

A) When I activate the 3D PYRO model with HT3D=T, FDS asks for turning on BURN_AWAY (maybe because of MATL 1), which does not represent the charring physics.
what did I do wrong?

B) Let's activate BURN_AWAY to get rid of the error and run sth on 3D PYRO (add BURN_AWAY=T to 3D.fds)... no pyrolysis reaction happens!
any suggestion to fix this problem?

TNX

[3D.fds.txt](https://github.com/firemodels/fds/files/4673449/3D.fds.txt)
[1D.fds.txt](https://github.com/firemodels/fds/files/4673450/1D.fds.txt)

**Comment by MortezaHaghighi** [comment]
Randy,

I think it's enough to change the place of this (commented out) IF statement on the read.f90 and put it outside the DO loop:

DO NR=1,ML%N_REACTIONS
   IF (ABS(SUM(ML%NU_RESIDUE(:,NR)))>TWO_EPSILON_EB) PYRO3D_RESIDUE=.TRUE.
ENDDO
       **!IF (.NOT.PYRO3D_RESIDUE .AND. .NOT.OB%CONSUMABLE) THEN
           !   WRITE(MESSAGE,'(A,A,A)') &
           !      'ERROR: MATL ',TRIM(ML%ID),', PYRO3D requires residue (NU_MATL) or BURN_AWAY'
           !   CALL SHUTDOWN(MESSAGE,PROCESS_0_ONLY=.FALSE.) ; RETURN
        !ENDIF**
ENDIF        
OB%RHO(:,:,:,NNN) = ML%RHO_S ! TEMPORARY -- must be reinitialized after PROC_WALL is called
ENDDO
                     
      **IF (.NOT.PYRO3D_RESIDUE .AND. .NOT.OB%CONSUMABLE) THEN
      WRITE(MESSAGE,'(A,A,A)') &
      'ERROR: MATL ',TRIM(ML%ID),', PYRO3D requires residue (NU_MATL) or BURN_AWAY'
       CALL SHUTDOWN(MESSAGE,PROCESS_0_ONLY=.FALSE.) ; RETURN
       ENDIF**

**Comment by MortezaHaghighi** [comment]
I tried box_burn_away1_pyro3d_vs_pyro1d and pyro3d_wood_char for verification. This change doesn't affect existing examples.
If you agree on the debug I made, let me do the pull request as a learning practice.

**Comment by rmcdermo** [comment]
I would be happy for you to send a PR...  but first, I don't understand why it would work.  PYRO3D_RESIDUE should be T if you have a char species.  And in that case you should not enter the IF.  Please more thoroughly describe your idea for why this change is needed.  It may be some time before I can get to this, even to break away and study code, so it would help if you really spell it out for me.  Thanks

**Comment by MortezaHaghighi** [comment]
For a single SURF, the bellow DO loop checks whether its MATLs have RESIDUE or not. Like 3D.fds example, it may happen that one of the MATLs doesn't have residue, although other MATLs have.
When code goes through "DO NR=1,ML%N_REACTIONS" for that non-char MATL, PYRO3D_RESIDUE still remains FALSE. That's when the code stops for that surface.

We can let the original loop "DO NNN=1,SF%N_MATL" process for all MATLs, and with even one of the MATLs of the surface that has residue, the PYRO3D_RESIDUE become TRUE, and after that loop ends, we check for the condition "IF (.NOT.PYRO3D_RESIDUE .AND. .NOT.OB%CONSUMABLE)" for the corresponding surface.

That's why I think the condition should be relocated after the loop.

DO NNN=1,SF%N_MATL
   ML=>MATERIAL(SF%MATL_INDEX(NNN))
   IF (ML%N_REACTIONS>0) THEN
      OB%PYRO3D=.TRUE.
      OB%PYRO3D_IOR=PYRO3D_IOR      ! tell PYRO3D which direction to send pyrolyzate
      OB%MT3D=PYRO3D_MASS_TRANSPORT ! supercedes PYRO3D_IOR
      PYRO3D_RESIDUE=.FALSE.
      DO NR=1,ML%N_REACTIONS
         IF (ABS(SUM(ML%NU_RESIDUE(:,NR)))>TWO_EPSILON_EB) PYRO3D_RESIDUE=.TRUE.
      ENDDO
      IF (.NOT.PYRO3D_RESIDUE .AND. .NOT.OB%CONSUMABLE) THEN
         WRITE(MESSAGE,'(A,A,A)') &
            'ERROR: MATL ',TRIM(ML%ID),', PYRO3D requires residue (NU_MATL) or BURN_AWAY'
         CALL SHUTDOWN(MESSAGE,PROCESS_0_ONLY=.FALSE.) ; RETURN
      ENDIF
   ENDIF
   OB%RHO(:,:,:,NNN) = ML%RHO_S ! TEMPORARY -- must be reinitialized after PROC_WALL is called
ENDDO

**Comment by MortezaHaghighi** [comment]
And also, in case we do so, we have to correct the error's text since there would not be a memory of ML%ID after the loop.
The simplest idea which comes to my mind is changing the error to SF.

**Comment by rmcdermo** [comment]
Thanks for the explanation.  Let's work toward a PR:

1. Set up the verification case (comparison with 1D and 3D solvers).
2. Add this to dataplot verification and post the plot here.  Include plots for all the HT3D pyrolysis cases.
3. Then send a PR for the source.  We will merge.
4. We will run firebot on the new source and if we get a pass, then
5. Submit a PR for the new verification case and a write up in the verification guide (for which you will get author credit).

Let me know if you have any questions.  Thanks for the contribution.

**Comment by MortezaHaghighi** [comment]
@rmcdermo checkout the attached input file. It is the charring pyrolysis of a wooden sample containing 10% moisture content.

please comment me about the case and results, so I can continue toward guide write-up.

![image](https://user-images.githubusercontent.com/56713983/86004838-87e4f080-ba1c-11ea-9b40-3c3759c88168.png)

![image](https://user-images.githubusercontent.com/56713983/86004903-9e8b4780-ba1c-11ea-9a43-68b22a2c96b0.png)


[pyro3d_vs_pyro1d_wood.fds.txt](https://github.com/firemodels/fds/files/4845426/pyro3d_vs_pyro1d_wood.fds.txt)

**Comment by rmcdermo** [comment]
@MortezaHaghighi Results look quite good to me.  Well done.

**Comment by MortezaHaghighi** [comment]
code stops when there is just 3D heat transfer and no pyrolysis reaction (ie N_REACTION=0).
It will be fixed with my next commit

**Comment by MortezaHaghighi** [comment]
@rmcdermo and @shostikk, please kindly comment on the description text and figures before I commit relevant files.

- case naming convention
- explanations
- aesthetics of the Plots

I think its place could be after "Mass Loss Rate and Thickness (pyro3d_vs_pyro1d)" and before "Mass Transport (pyro3d_transport)" subsections. What would you suggest?

![image](https://user-images.githubusercontent.com/56713983/86391295-3d74a580-bca2-11ea-9adf-31d42f983849.png)

![image](https://user-images.githubusercontent.com/56713983/86391366-62691880-bca2-11ea-8866-2229de083c15.png)

**Comment by rmcdermo** [comment]
@MortezaHaghighi Looks good to me.  Well done.  Yes, I think put it after pyro3d_vs_pyro1d cases.

**Comment by rmcdermo** [comment]
Also, please edit the Acknowledgements section and add your name and affiliation to the section where you put the plots.  Follow other examples in the verification guide for outside contributions.

**Comment by rmcdermo** [comment]
This is complete, yes?  If not, reopen.  Thanks
