### ISSUE TITLE
Two mesh case has cold spot at mesh boundary

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8383]
Below  is a simplified version of a case from the forum.  There are two meshes of different resolution.  At the start of the simulation a region near the top of the common face between the meshes is cold. This isn't just a display artifact as a cold descending flow begins.

&HEAD CHID='test'/
&TIME T_END=2.0  /

&ZONE XYZ=0,0,0.5/

&MESH ID='Mesh.000' IJK=38,32,40 XB=-0.646,0.000,-0.269,0.269,0.000,0.673 /
&MESH ID='Mesh.004' IJK=80,24,60 XB=0.000,0.673,-0.101,0.101,0.101,0.606 /
&VENT ID='Domain_0' XB=-0.646,-0.646,-0.269,0.269,0.000,0.673 SURF_ID='OPEN' XYZ=-0.425,-0.000,0.337 /

&SLCF QUANTITY='TEMPERATURE',PBY=0.0/
&SLCF QUANTITY='TEMPERATURE',PBZ=0.5/

&TAIL /

**Comment by mcgratta** [comment]
![test_s0000](https://user-images.githubusercontent.com/11333911/83270168-18b67b00-a196-11ea-9981-4a635f2dac88.png)
These two meshes are not aligned properly, but the difference is so subtle that FDS did not trap it. When I create a similar case with perfectly aligned meshes, I do not see the drop in temperature.

**Comment by drjfloyd** [comment]
I completely missed that. I assumed that since it ran the meshes were OK. Do we need to tighten the tolerance for meshes?

**Comment by mcgratta** [comment]
Yes, I'm doing that right now. Old criteria was the difference between two
fine cells and one coarse cell was less than 1%. I'm making that 0.1% and
this traps the error. I'm also making this an input parameter in case we
need to fine tune it more.

>

**Comment by mcgratta** [comment]
I added a MISC line parameter called ALIGNMENT_TOLERANCE to allow one to tighten the mesh alignment criterion. The new tolerance is 0.001, meaning that the mesh cells must align to within 0.1 % of the size of the smaller cell.
