### ISSUE TITLE
Seg fault related to HVAC routine

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8393]
[ID_2.txt](https://github.com/firemodels/fds/files/4711418/ID_2.txt)
This case fails with a sef fault after about 18 s simulation time in release mode with the latest code. It fails after about 5 s in debug mode. The line with a floating invalid is in hvac.f90
```
! Outputs number of substeps required to maintain CFL for mass transport
N_SUBSTEPS = 1
DO ND = 1,NE%N_DUCTS
   DU=>DUCT(NE%DUCT_INDEX(ND))
   IF (DU%N_CELLS > 1 .AND. ABS(DU%VEL(NEW)) > 0._EB) THEN
      DT_CFL = DU%LENGTH/ABS(DU%VEL(NEW)) ! relevant CFL is all mass leaving a duct within one DT
      N_SUBSTEPS_DUCT = MAX(1,CEILING(DT/DT_CFL))   <---- Floating Invalid (line 1248)
      IF (N_SUBSTEPS_DUCT > N_SUBSTEPS) THEN
         N_SUBSTEPS = N_SUBSTEPS_DUCT
      ENDIF
   ENDIF
ENDDO
```
This issue is related to [this Discussion Group Post](https://groups.google.com/forum/#!topic/fds-smv/IOOE_uhyul0)

**Comment by drjfloyd** [comment]
The first and last mesh have cell aspect ratios ~ 10.  Does this run with a well formed mesh?

&MESH ID='Mesh01', IJK=128,4,32, XB=-200.0,-175.0,-4.0,4.0,0.0,6.5, MPI_PROCESS=0/
X: 25 m / 128 ~ 0.2 m
Y: 8 m/4 = 2 m
Z: 6.5 m/32 ~ 0.2 m

**Comment by mcgratta** [comment]
I haven't checked. I will. But even if it does, I'd like the code to end gracefully with some kind of stability error.

**Comment by mcgratta** [comment]
If I remove the TRN lines, the case runs past the point of failure. I'll check again tomorrow if the case finishes.

**Comment by mcgratta** [comment]
FYI, the case runs to completion if you remove the TRN lines.
