### ISSUE TITLE
Sprinkler in FDS

### ISSUE THREAD

**Issue by tamhoklai** [firemodels/fds#8399]
Hi everyone, I am completely new in FDS so would be great if I can get some help from you guys!

I have put in sprinklers and fire in the model to understand how long does it take for 1) sprinklers to activate and 2) how long the sprinklers take to reduce the fire to 30% of the max. HRR. Unfortunately the HRR is not reduced during the simulation but it seems the sprinkler temp has gone high enough to activate. 

I created the model in Pyrosim then compile into FDS code.
Appreciate if you guys can point me to the right direction!

&HEAD CHID='Model1'/
&TIME T_END=600.0/
&DUMP DT_RESTART=30.0, DT_SL3D=0.25/

&MESH ID='Mesh02-b-b-b-b-b-b', IJK=9,60,35, XB=2.1,3.0,-3.0,3.0,0.0,3.5/
&MESH ID='Mesh02-b-b-b-b-a', IJK=8,60,35, XB=0.4,1.2,-3.0,3.0,0.0,3.5/
&MESH ID='Mesh02-b-b-b-a', IJK=8,60,35, XB=-0.4,0.4,-3.0,3.0,0.0,3.5/
&MESH ID='Mesh02-b-b-a', IJK=8,60,35, XB=-1.2,-0.4,-3.0,3.0,0.0,3.5/
&MESH ID='Mesh02-b-b-b-b-b-a', IJK=9,60,35, XB=1.2,2.1,-3.0,3.0,0.0,3.5/
&MESH ID='Mesh02-b-a', IJK=9,60,35, XB=-2.1,-1.2,-3.0,3.0,0.0,3.5/
&MESH ID='Mesh02-a', IJK=9,60,35, XB=-3.0,-2.1,-3.0,3.0,0.0,3.5/

&SPEC ID='WATER VAPOR'/

&PART ID='Water',
      SPEC_ID='WATER VAPOR',
      DIAMETER=500.0,
      MONODISPERSE=.TRUE.,
      AGE=60.0,
      SAMPLING_FACTOR=1/

&REAC ID='WOOD_OAK',
      FYI='SFPE Handbook, 3rd Ed',
      FUEL='REAC_FUEL',
      C=1.0,
      H=1.7,
      O=0.72,
      N=1.0E-3,
      CO_YIELD=4.0E-3,
      SOOT_YIELD=0.015,
      RADIATIVE_FRACTION=0.35/

&PROP ID='Model1_Sprinkler ',
      QUANTITY='SPRINKLER LINK TEMPERATURE',
      ACTIVATION_TEMPERATURE=74.0,
      PART_ID='Water',
      FLOW_RATE=60.0,
      FLOW_TAU=1.0,
      PARTICLE_VELOCITY=5.0,
      SPRAY_ANGLE=60.0,75.0/
&DEVC ID='Sprinkler 1', PROP_ID='Model1_Sprinkler ', XYZ=2.0,2.0,2.9/
&DEVC ID='Sprinkler 2', PROP_ID='Model1_Sprinkler ', XYZ=2.0,-2.0,2.9/
&DEVC ID='Sprinkler 3', PROP_ID='Model1_Sprinkler ', XYZ=-2.0,-2.0,2.9/
&DEVC ID='Sprinkler 4', PROP_ID='Model1_Sprinkler ', XYZ=-2.0,2.0,2.9/

&SURF ID='Fire',
      COLOR='RED',
      HRRPUA=6000.0,
      RAMP_Q='Fire_RAMP_Q',
      TMP_FRONT=300.0/
&RAMP ID='Fire_RAMP_Q', T=0.0, F=1.0/
&RAMP ID='Fire_RAMP_Q', T=600.0, F=1.0/

&OBST ID='Floor slab', XB=-3.0,3.0,-3.0,3.0,0.0,0.2, COLOR='GRAY 40', SURF_ID='INERT'/ 
&OBST ID='Floor slab', XB=-3.0,3.0,-3.0,3.0,3.0,3.2, COLOR='WHITE', SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-0.25,0.25,-0.25,0.25,0.2,0.7, SURF_IDS='Fire','INERT','INERT'/ 

&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-b [XMAX]', SURF_ID='OPEN', XB=3.0,3.0,-3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-b [YMAX]', SURF_ID='OPEN', XB=2.1,3.0,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-b [YMIN]', SURF_ID='OPEN', XB=2.1,3.0,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-b [ZMAX]', SURF_ID='OPEN', XB=2.1,3.0,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-b [ZMIN]', SURF_ID='OPEN', XB=2.1,3.0,-3.0,3.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-a [YMAX]', SURF_ID='OPEN', XB=0.4,1.2,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-a [YMIN]', SURF_ID='OPEN', XB=0.4,1.2,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-a [ZMAX]', SURF_ID='OPEN', XB=0.4,1.2,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-a [ZMIN]', SURF_ID='OPEN', XB=0.4,1.2,-3.0,3.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-a [YMAX]', SURF_ID='OPEN', XB=-0.4,0.4,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-a [YMIN]', SURF_ID='OPEN', XB=-0.4,0.4,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-a [ZMAX]', SURF_ID='OPEN', XB=-0.4,0.4,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-a [ZMIN]', SURF_ID='OPEN', XB=-0.4,0.4,-3.0,3.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh02-b-b-a [YMAX]', SURF_ID='OPEN', XB=-1.2,-0.4,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-a [YMIN]', SURF_ID='OPEN', XB=-1.2,-0.4,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-a [ZMAX]', SURF_ID='OPEN', XB=-1.2,-0.4,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-a [ZMIN]', SURF_ID='OPEN', XB=-1.2,-0.4,-3.0,3.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-a [YMAX]', SURF_ID='OPEN', XB=1.2,2.1,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-a [YMIN]', SURF_ID='OPEN', XB=1.2,2.1,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-a [ZMAX]', SURF_ID='OPEN', XB=1.2,2.1,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-b-b-b-b-a [ZMIN]', SURF_ID='OPEN', XB=1.2,2.1,-3.0,3.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh02-b-a [YMAX]', SURF_ID='OPEN', XB=-2.1,-1.2,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-a [YMIN]', SURF_ID='OPEN', XB=-2.1,-1.2,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-a [ZMAX]', SURF_ID='OPEN', XB=-2.1,-1.2,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-b-a [ZMIN]', SURF_ID='OPEN', XB=-2.1,-1.2,-3.0,3.0,0.0,0.0/ 
&VENT ID='Mesh Vent: Mesh02-a [XMIN]', SURF_ID='OPEN', XB=-3.0,-3.0,-3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-a [YMAX]', SURF_ID='OPEN', XB=-3.0,-2.1,3.0,3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-a [YMIN]', SURF_ID='OPEN', XB=-3.0,-2.1,-3.0,-3.0,0.0,3.5/ 
&VENT ID='Mesh Vent: Mesh02-a [ZMAX]', SURF_ID='OPEN', XB=-3.0,-2.1,-3.0,3.0,3.5,3.5/ 
&VENT ID='Mesh Vent: Mesh02-a [ZMIN]', SURF_ID='OPEN', XB=-3.0,-2.1,-3.0,3.0,0.0,0.0/ 

&SLCF QUANTITY='TEMPERATURE', PBX=0.0/
&SLCF QUANTITY='VELOCITY', PBX=0.0/

&TAIL /

**Comment by rmcdermo** [comment]
This issue tracker is for bug reports.  Please submit a question to the [discussion forum](https://groups.google.com/forum/#!forum/fds-smv).
