### ISSUE TITLE
Linear Array of Point Devices

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8412]
FDS version: 6.7.4

Hi, I created a test case to test the linear array of point devices as attached.

I have a domain with 10m(L) x 5m(W) x 5m(H) with a hot ceiling. I record the 'temperature' and 'radiative heat flux gas' using DEVC with linear array function and DEVC with XYZ (reference point).

&MESH IJK=20,10,10, XB=0,10,0,5,0,5 /

&VENT MB='ZMAX', SURF_ID='Ceiling' /

&SURF ID='Ceiling', COLOR='RED', TMP_FRONT=200. /

&DEVC ID='RAD1', QUANTITY='RADIATIVE HEAT FLUX GAS', ORIENTATION=0,0,1, XB=0,10,2,2,2,2, POINTS=21, TIME_HISTORY=.TRUE. /
&DEVC ID='RAD2', QUANTITY='RADIATIVE HEAT FLUX GAS', ORIENTATION=0,0,1, XB=0,10,2,2,2,2, POINTS=11, TIME_HISTORY=.TRUE. /
&DEVC ID='RAD3',  QUANTITY='RADIATIVE HEAT FLUX GAS', ORIENTATION=0,0,1, XYZ=4,2,2 /

The 'temperature' quantity output for ID 'TEMP1' and 'TEMP2' consistent with the reference point 'TEMP3'.

However, the 'radiative heat flux gas' quantity output is strange. 

From the output of ID 'RAD1' and 'RAD2', half of the sensing points using linear array function recorded 0 (RAD1-11 to RAD1-21, RAD2-06 to RAD2-11) in the .csv file. 
From the .out file, it is found that RAD1-XX does not create interval of 0.5m sensing point; while RAD2-XX does not create interval of 1m sensing point.

Any thing goes wrong with my setting?

Best regards,

Antony

[ScenA.fds.txt](https://github.com/firemodels/fds/files/4751643/ScenA.fds.txt)

<img width="752" alt="Screen Shot 2020-06-09 at 6 43 28 AM" src="https://user-images.githubusercontent.com/4418497/84138676-a9098100-aa1c-11ea-9ecd-ac5e55307441.png">

**Comment by mcgratta** [comment]
I found the error. As a work-around, do not use the `POINTS` and `TIME_HISTORY=T` on the same `DEVC` line.

**Comment by mcgratta** [comment]
I fixed the bug, but until the next release, if you want TIME_HISTORY=T for these GAS devices, you create individual DEVC lines without the use of POINTS.
