### ISSUE TITLE
Allow FREEZE_VELOCITY to become T during a simulation

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8415]
We want the ability to "freeze" a wind field in a level set simulation at the time when the fire starts. To do this, we set `FREEZE_VELOCITY=F` and `SOLID_PHASE_ONLY=F` initially, then set both to T when the fire ignites. For `/home4/mcgratta/Case_Studies/Cogoleto_Fire/cogoleto_fire_2019_ls2.fds`, I get
```
CC_TIMEOUT Error: REQ11 timed out for MPI process     59
CC_TIMEOUT Error: REQ12 timed out for MPI process     58
Abort(0) on node 58 (rank 58 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 58
Abort(0) on node 59 (rank 59 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 59
```
at the time of ignition. This looks like an MPI call is disrupted in GEOM. Is there a way to avoid this?

**Comment by marcosvanella** [comment]
Kevin, I'll check it out.

**Comment by marcosvanella** [comment]
I run the case writing out FREEZE_VELOCITY and SOLID_PHASE_ONLY for every processor and time step. Seems the logic only changes these to TRUE for the mesh where ignition is defined at 1800 sec (mesh 60). The other processes never change these logicals values. The switch is done in vege.f90 at line 315.
`! Loop over terrain surface cells and update level set field

DO JJG=1,JBAR
   DO IIG=1,IBAR

      SF => SURFACE(LS_SURF_INDEX(IIG,JJG))

      IF (.NOT. SF%VEG_LSET_SPREAD) CYCLE

      ! Ignite landscape at user specified location and time

      IF (PHI_LS(IIG,JJG)<0._EB .AND. T>SF%VEG_LSET_IGNITE_T) THEN
         PHI_LS(IIG,JJG) = PHI_LS_MAX
         IF (LEVEL_SET_MODE==2) THEN
            FREEZE_VELOCITY = .TRUE.
            SOLID_PHASE_ONLY = .TRUE.
         ENDIF
      ENDIF
` 
One option is to communicate the change to all meshes (an all reduce) or cheaper, just use a conditional to freeze the velocity field for the smallest VEG_LSET_IGNITE_T found in the input file.

**Comment by mcgratta** [comment]
Ah, very good point. My fault. Let me fix it.

**Comment by mcgratta** [comment]
That did it. It's fixed. Thanks.
