### ISSUE TITLE
instability with GEOM

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#8424]
Numerical instability occurs with hood create using GEOM. Input file is attached. Kuldeep is also requesting help. I'm submitting this issue so you have the input file here.
[input_GEOM_numerical_instability.txt](https://github.com/firemodels/fds/files/4766153/input_GEOM_numerical_instability.txt)

**Comment by marcosvanella** [comment]
I'll take a look.

**Comment by marcosvanella** [comment]
Ruddy, something I note on the geometry is that you want to make it at least 2 cells thick to avoid flow penetration. We don't handle zero thickness geometry at this point. That said, the code should not give instability with the geometry and setup you have so I'm looking into it.

**Comment by marcosvanella** [comment]
Ruddy, I fixed the culprit of the instability. It had to do with averaging normals for geometry boundary faces within FDS cells to define a normal distance. In some cases for the hood, area averaged normals were zero. I changed that to get this normal distance on boundary faces using the normal vector to the face. This is used to define heat transfer BCs to the fluid and vice versa. You should be able to run the case without instability. Note again that you need a thickness here to be able to properly reduce flow penetration, as you can see running this input file (4 meshes).

[hood_burner.txt](https://github.com/firemodels/fds/files/4783172/hood_burner.txt)

**Comment by ruddymell** [comment]
thanks Marco

**Comment by marcosvanella** [comment]
I'm going to close this.
