### ISSUE TITLE
AEROSOL VOLUME FRACTION not working

### ISSUE THREAD

**Issue by shostikk** [firemodels/fds#8427]
With  FDS6.7.4-567-g451dcab1c-master, QUANTITY = 'AEROSOL VOLUME FRACTION' gives error message, that the spec must be a tracked one, but I think it is. If I remove the DEVC, .out file indicates that AEROS is also a tracked spec.

2A_V2.fds.txt](https://github.com/firemodels/fds/files/4769237/2A_V2.fds.txt)

**Comment by drjfloyd** [comment]
I see the same thing. Something has been broken since FDS 6.7.4 was released.

**Comment by drjfloyd** [comment]
Should be fixed now.

**Comment by shostikk** [comment]
Confirmed. Thank you Jason!
Closing the issue.
