### ISSUE TITLE
CC and BNDF problem with DT and T_BEGIN

### ISSUE THREAD

**Issue by shostikk** [firemodels/fds#8428]
Enclosed fire gives 'file not found' error for 2A_V2_0001_01.be
Removing T_BEGIN removes the problem.

FDS6.7.4-567-g451dcab1c-master

[CC_BNDF.fds.txt](https://github.com/firemodels/fds/files/4769453/CC_BNDF.fds.txt)

**Comment by rmcdermo** [comment]
Thanks for the report.  Should be working with PR #8430

**Comment by shostikk** [comment]
Confirm. Thank you Randy!
