### ISSUE TITLE
Improper GEOM setup

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8435]
I am running a terrain case and I get the error
```
ERROR: GEOM ID='Terrain':
  Edge length too small at:    1470.774    1881.709      84.000
  Check that Vertices:   32122,      273 are not equal.
```
The case is at /home4/mcgratta/Case_Studies/Cogoleto_Fire/marcos.fds

**Comment by marcosvanella** [comment]
Something is not right with the terrain definition when K_LOWER>0. I'll fix.

**Comment by mcgratta** [comment]
Is there any problem with the fact that I am using 1 m grid cells on a terrain that was originally created using 10 m cells and data? I shouldn't think so, but I wonder if your edge size tolerances are tied to one length scale or the other.

**Comment by marcosvanella** [comment]
No, that should be fine. We can have larger or smaller triangles than cell sizes. It is related to the Z value at the base of the terrain, I'm getting a wrong value of ZMIN from the VERTS being read in (I get 218.0 when it should be 0.). The MINVAL intrinsic is being used for this.

**Comment by marcosvanella** [comment]
The issue was coming form using MINVAL on an array section not correctly defined. I changed that to work on a loop, and the terrain geometry is built as expected now.  I pushed the change.

**Comment by marcosvanella** [comment]
Kevin, did you test this? Please, close if working.

**Comment by mcgratta** [comment]
Yes, thanks.
