### ISSUE TITLE
mass file and GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8453]
The case below defines a 1 m^3 box with a 1 m diameter sphere using GEOM.  The free air volume should be 0.48 m^3.  When the case is run, the mass file shows the total mass of air is 1.2 kg or the entire 1 m^3 of the domain.

&HEAD CHID='geotest2'/
&MESH XB=0,1,0,1,0,1,IJK=40,40,40/
&TIME T_END=0.1/
&DUMP MASS_FILE=.TRUE./
&SURF ID='1',COLOR='RED'/
&GEOM ID='sphere',SURF_ID='1',SPHERE_ORIGIN=0.5,0.5,0.5,SPHERE_RADIUS=0.5/

**Comment by rmcdermo** [comment]
Jason,
Please commit this cas

**Comment by drjfloyd** [comment]
as in push it to Complex_Geometry ?

**Comment by rmcdermo** [comment]
Sorry.  In the middle of my comment, I decided I would deal with it.  I accidentally hit close.  Yes, I'll add it as a verification test.

**Comment by rmcdermo** [comment]
OK, this should be fixed.  @drjfloyd Great job catching this!  Figures crossed that I committed everything and that firebot is happy tonight.

**Comment by drjfloyd** [comment]
It is working for me now.
