### ISSUE TITLE
CATF truncates lines to 200 characters without warning

### ISSUE THREAD

**Issue by JakeOShannessy** [firemodels/fds#8461]
Currently when using the `CATF` namelist to concatenate input files the lines are truncated silently at 200 characters (i.e. `MESSAGE_LENGTH`). This probably isn't a big issue, as 200 characters is probably generous enough for most input files but it might be worth at least throwing an error if the the line is too big for the buffer.

Removing the limit would be even better, but I'm not too familiar with Fortran I/O.

https://github.com/firemodels/fds/blob/75c3d7000190337f606d209211b1a07e72786515/Source/read.f90#L353-L366

**Comment by mcgratta** [comment]
I suppose there might be a way to parse the string and dynamically allocate space, but I'd rather just throw an error. Fortran is not flexible with this kind of I/O, and I guarantee nothing but grief if we try to get fancy reading file names.

**Comment by drjfloyd** [comment]
CHARACTER(MESSAGE_LENGTH) :: BUFFER

I think this is the issue.  Input lines can get lengthy especially if you try to define a custom SPEC with both liquid  and gas properties.  For this one string might make sense to make it more than 200 characters.

**Comment by marcosvanella** [comment]
Let me do some tests. We should be able to throw an error, and also to be safe define a longer string for BUFFER.

**Comment by marcosvanella** [comment]
Jake, do a repo update and try the functionality. You should be able to have lines of up to 2*MESSAGE_LENGTH=400 characters in any of your concatenated files. If this size is exceeded, FDS will throw an error and stop. 
Let me know how it works.

**Comment by JakeOShannessy** [comment]
Thanks Marcos, looks like that's done the trick.
