### ISSUE TITLE
heat transfer through walls and geom

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8463]
The attached case contains three meshes: one using OBST, one using identical GEOM, and one using identical GEOM rotated 45 degrees.  

Each MESH has three OBST: A hot wall, a conductive wall, and a cold wall (Set to ambient in the attached case).

Four issues:

-Neither of the GEOM cases are transferring heat through the wall. I get that this probably isn't a trivial problem and may not even be possible to do in an efficient manner; however, I think it should be stated as a limitation in the notes so that users will know this.

-The face of the middle wall facing the hot side gets different temperatures for GEOM and OBST. I've set HTC front and back to 0 and emissivity to 1 so I would expect these to be nearly identical as the view factors to the hot wall should be nearly identical and the flow solution has no impact. The GEOM gets 26 % hotter at steady-state. Early on the GEOM temp rise is 200 % larger. Is GEOM defaulting to an INSULATED condition rather than a VOID condition?

-The back face of the middle wall in the rotated GEOM changes temperature even though it only sees walls that start at 20 C and remain at 20 C.

-The rotated GEOM is 3 % hotter than the non-rotated GEOM. These should be equal as the view factors should be the same. Note this looks like it might just be numerical error in the view factor when the walls are rotated. If I double the grid resolution the difference drops almost in half. 

[geomtest5.fds.txt](https://github.com/firemodels/fds/files/4800549/geomtest5.fds.txt)

**Comment by rmcdermo** [comment]
@mcgratta Can you take a look at this when you get time?

**Comment by mcgratta** [comment]
Marcos -- what is the back boundary condition for a CFACE? VOID? EXPOSED? INSULATED?

**Comment by marcosvanella** [comment]
Good question. Where is that defined in wall cells? I thought it was a field in ONE_D.

**Comment by mcgratta** [comment]
We were using the same back wall condition for CFACES as we use for PARTICLES. I changed it so that now CFACEs back to ambient void. 

Jason, this fix helps with issues 2 and 3 above. Issue 1 is a much bigger problem, and Issue 4 is probably as you say, a grid issue. Could you check.

**Comment by drjfloyd** [comment]
Issue 2 is now OK. 
Issue 3 is still there for the angled wall. The back face temperature is still changing slightly.
I ran a third grid resolution and Issue 4 is mostly a grid issue; however, since Issue 3 is still present for the angled wall, there seems to be some component that is not just grid related.

For item 1, I can see this getting really complicated for GEOM defined with vertices. For GEOM that uses XB though, we could use the normal vector at the center of a CFACE within a gas cell to determine what backside face intersects that normal and use that gas temperature if it exists. This would let GEOM at least preserve existing OBST capability. Yes, the triangle in a gas cell on one side when projected to the other might intersect more than one gas cell, but I think just using the normal from the center should be good enough.

**Comment by rmcdermo** [comment]
I will let @marcosvanella comment more, but the algorithm to define cutcells uses ray tracing.  I do not think it would be too hard for this to be modified to connect CFACES along a given ray if BACKING=EXPOSED.

**Comment by drjfloyd** [comment]
For a wall for a room we'd only want to do that through the thickness of the wall and not from top to bottom. Right now with OBST we do this by saying we only transfer heat if it is one grid or less thick.  For GEOM we may need to caution the user in the guide to use SURF_IDS (when using XB) or SURF_ID (when using VERTS) to only denote the specific faces to allow for through wall heat transfer, i.e. they will need two SURF one with VOID (or IINSULATED) and one with EXPOSED.

**Comment by rmcdermo** [comment]
Sure.  I'm just pointing out that the machinery to search in the normal direction of a CFACE exists.  And it is probably a matter of adding a new quantity to the type to indicate the connection with the backing CFACE.

**Comment by marcosvanella** [comment]
Ray tracing for cut-cells is simplified for Cartesian grid lines for speed reasons. We'd have to write the 3D algo based on boundary CFACE centroids (shooting the ray in the -n direction and picking an "back" CFACE). This should not be hard. 
Something important is, for a rotated box, the CFACE we hit on the back will not have the same geometry and area of the one in the front. CFACEs geometry depends on the intersection of triangles with the Cartesian mesh. So, do we just need to evaluate a point-wise heat flux on the back to do the exposed back wall? It would seem total fluxes in a surface as seen from one side or the other are not going to match. 

Jason is correct in the sense we can define front-back pairs using SURF_IDs.
In aligned box geoms using the set of CFACES per cartesian cells in front and back will give us same area and centroid as wall cells.

**Comment by drjfloyd** [comment]
In 1D heat transfer we independently do both sides of the wall. When doing side A we just lookup the side B gas temperature to compute the convective heat transfer and get cells radiative flux in. Similarly when we do side B, we lookup the conditions on side A.  That mechanism would still work. But I think Marcos is correct that there could be some error in energy conservation when integrated over the entire domain.  If a calculation is reasonable well resolved though, the change in exposure conditions from triangle to adjacent triangle should generally not be very large.

**Comment by mcgratta** [comment]
Search on IWB in the 1-D heat transfer routine in wall.f90.  It's a matter
of figuring out what the back side CFACE is, and then just storing it.

>

**Comment by mcgratta** [comment]
Marcos, if you can provide CFACE(ICF)%BACK_INDEX, which is the index of the CFACE that is directly opposite the front CFACE, it would be easy to hook in the same way we do for wall cells, at least in the case where front and back surfaces are in the same mesh.

**Comment by marcosvanella** [comment]
Let me think about this. With the ray tracing idea, we might have a situation where one CFACE is the BACK_CFACE of more than one CFACE or some CFACE that is not the back CFACE of anyone. Maybe we can set pairs as for wall cells and if the ray tracing test gives a back cface that is taken we choose some other CFACE in the same cell.

**Comment by drjfloyd** [comment]
I don't think it matters if one CFACE is the back face to more than one.  We are just using the back face to get the backside gas conditions. The front face does its own calculation using the back face gas temperature. When we get to face we used for the back face is does its own fully independent calculation using its own back face. The two solutions don't communicate with one another. I think this means we will have some slight energy conservation issues as projected areas of faces may not always line up, but in general that shouldn't be large. It may be that for now we only do allow this for a GEOM with XB. I think for getting a FDS 7 beta out this would be sufficient. I would think that getting heat transfer really correct across an arbitrary cross section GEOM is not simple.

**Comment by mcgratta** [comment]
Doesn't matter. We do not change the back surface properties when we update
a WALL cell. We just use them. So all we need are the conditions at a
surface that is on the other side of solid.

>

**Comment by marcosvanella** [comment]
I see. Let me cook something up. We can start with single mesh backing as we don't have CFACEs locally on meshes in other procs. then we can move the ray tracing to shoot rays in parallel + exchange back cface info between procs.

**Comment by marcosvanella** [comment]
Actually, we can do the 3D ray tracing on the geometry triangulation, known by all processes. The intersection point location we get can be used to figure out which mesh and cell contains the back CFACE. This can be used eventually to ship the intersection point info to the appropriate mesh handling process and build communication arrays, etc.

**Comment by mcgratta** [comment]
Add BACK_INDEX to the CFACE_TYPE and put the integer there.

**Comment by mcgratta** [comment]
Marcos, any progress on this issue. Something I can do to help?

**Comment by marcosvanella** [comment]
This is on my list. Let me add the basic ray tracing to pick up the cell with potential back CFACEs and we discuss how to plug that in.

**Comment by marcosvanella** [comment]
I added the basic BACK_MESH, BACK_INDEX computing functionality for CFACEs. It looks at an intersection point for a CFACE ray given in the -n (CFACE normal) direction, through its centroid, with triangles of the same geometry of the triangle the CFACE was carved from. Once the intersection point is found the cell and mesh where the point lays is found using SEARCH_OTHER_MESHES and the cell (and neighbor cells) is searched for back CFACEs. The functionality should work for a given mesh and neighboring meshes (including corners). 

- Note in Jasons case (mesh 3) there is a corner of the geometries that lays outside the mesh. Default BACK_MESH=NM and BACK_INDEX=0 are kept in this situation.
-  As things are now, every CFACE is supposed to get a back CFACE index. In Jasons case, the distance between CFACE centroid and back CFACE can be the thickness of the wall or the length. I can provide the distance from CFACE to its back CFACE if needed for the 1D HT calculation. 
- The calculation process can be costly for geometries with many triangles (it is O(N_CFACES*N_FACES) as is). We might need to treat BACKING=EXPOSED in a special manner for geometries (not do it unless explicitly stated).  

Kevin, do an update and check the case. Have a look at the code in PR #8872 and see if you can hook up the 1D HT routines to this. We'd need a framework similar to what is done for WALL_CELLs for multimesh cases.

**Comment by mcgratta** [comment]
I'll check it out.

**Comment by mcgratta** [comment]
[geomtest5.txt](https://github.com/firemodels/fds/files/5440662/geomtest5.txt)
Marcos, update your repo and recompile. Run this case. The heat transfer through GEOMs is now working, at least for GEOMs within a single mesh. However, this case is still not quite right because the front temperature in mesh 2 (F2) is higher than the other cases. I suspect this might have to do with where the source term of the radiation equation is being evaluated.

**Comment by marcosvanella** [comment]
I see it. The mesh distribution is the same between mesh 1 and 2 and the heat transfer coef is 0, so things should be the exact same.

**Comment by mcgratta** [comment]
Yes, but it is possible that the hot or cold surface planes are off by one
grid cell because of the logic in identifying the source location.

>

**Comment by marcosvanella** [comment]
I'll check that.

**Comment by marcosvanella** [comment]
Kevin, do an update and try geomtest5.txt. Both aligned cases of mesh 1 and 2 should have wall temps within 0.5C. The 45 deg rotated case is 25C higher than the other two (3%). Doubling the mesh sizes this difference goes down to 14C.

**Comment by mcgratta** [comment]
I committed a variation of the case posted at the top of this thread into the Verification Guide. There still remains the issue of what to do when the back surface of a GEOM is in another mesh. It will not work at the moment.

**Comment by mcgratta** [comment]
Closing -- this is part of larger issue of non-rectangular surfaces.
