### ISSUE TITLE
NIST_RSE_1994/NIST_RSE_1994_500_RI=5.fds fails due to numerical instability at third time step

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8515]
```
[mcgratta@blaze fds]$ git bisect bad
a438791b5fa75737d9ea1a5f1c3d63047b590ab1 is the first bad commit
commit a438791b5fa75737d9ea1a5f1c3d63047b590ab1
Author: rmcdermo <randy.mcdermott@gmail.com>
Date:   Mon May 11 09:56:44 2020 -0400

    FDS Source: make PROJECTION=T by default

:040000 040000 7f320327a8d100ba042a14af39a9e7af2e69e19b d962b20da1e0be8929177bb827dd1e787f2b4028 M      Source
```

**Comment by mcgratta** [comment]
I'm going to look at this case to see if something else can be done to fix. I think that the PROJ=T change is a red herring. This case was probably borderline stable before the switch to PROJ=T, and only this case has become unstable so far in my validation testing. CHECK_HT does lower the time step and gets us past the instability, but I would prefer that the iteration scheme within the solid phase 1-D conduction routine catch these kinds of rapid changes at pyrolyzing surfaces.

**Comment by rmcdermo** [comment]
This does not have a pyrolyzing surface.  It has a mass flux with TMP_FRONT set to 400 C.  You need CHECK_HT=T.  Frankly, CHECK_HT=T should be a default.  We chase our tail by not obeying CFL constraints in an explicit code.

**Comment by mcgratta** [comment]
I want to better understand what CHECK_HT actually does. Like in this case, what is actually going off the rails. That is what I want to look at.

**Comment by rmcdermo** [comment]
It's documented.  I would question the boundary condition 400 C.

**Comment by mcgratta** [comment]
I think the real problem in this case is that everything is ramped up too quickly. The `TIME_SHRINK_FACTOR=4` means that instead of HRRPUA and TMP_FRONT being ramped up in 1 s, they are now ramped up in 1/4 s. Setting CHECK_HT and SIM_MODE=LES simply reduce the time step during this initial phase and get us past the point of numerical instability. I do not want to convey that these options are necessary in this case. One can either reduce the initial time step, which is what we currently advise when things happen quickly initially, or we can set TAU_T=4 instead of 1, or we can not use TMP_FRONT=400, but rather add a MATL_ID to the SURF line that allows the burner surface to heat up more naturally. I think that I set these cases up, so I'd like to fix these various physical input parameters. I like the validation cases to have the fewest number of numerical parameters as possible.

**Comment by rmcdermo** [comment]
OK, but I do not at all understand your idea that setting DT on the time line is a better solution than CHECK_HT.  DT then becomes a max for the rest of the calculation, whereas CHECK_HT get you through the initial ramp up and then allows the proper CFL close to 1 to be utilized throughout the rest of the simulation.

If you want to remove input parameters, the best way is to make CHECK_HT=T the default.  For the complaints about long run times, we still keep RESTRICT_TIME_STEP=.TRUE.  We would be much better off by using RESTRICT_TIME_STEP=.FALSE.  and setting CHECK_HT=.TRUE. by default.
