### ISSUE TITLE
Build still fails with GCC 10.1.0 on macOS 10.15.5 and Lubuntu Linux 20.04

### ISSUE THREAD

**Issue by rouson** [firemodels/fds#8516]
I pulled the latest version of the `master` branch, including commit 21f9289, but `make mpi_gnu_osx_64` and `make mpi_gnu_linux_64` still fail for me on macOS and Linux, respectively, when building with MPICH.  I verified that the `gnu_compmajorversion.sh` returns `10` when I'm compiling with GCC 10.1.0.  However, `-fallow-argument-mismatch` is still missing from the resulting `gfortran` commands.

I don't mind adding the required argument when building.  I already use MPICH for other projects and would like to stick with one MPI installation because I teach using a virtual machine that course attendees download so I try to keep the virtual machine size to a minimum.  In case anyone wants to reproduce this issue, the virtual machine is available at www.sourceryinstitute.org/store, but that's more hassle than I'm sure it's worth so feel free to close this issue.  I just wanted to let you know.

**Comment by marcosvanella** [comment]
Damian, the fix works for me in Ubuntu 2018. We want to make sure it works for you.  
The url you provide cannot be found in my browser, see if there is a typo and let us know.
Make sure you have the latest code and compile from inside the target mpi_gnu_linux_64 using ./make_fds.sh
the flag should appear just before the source file name in the compilation line.

**Comment by rouson** [comment]
@marcosvanella I just fixed the previously posted link, but there's no need to download it. Your suggestion works.  I'll close this issue.

**Comment by rouson** [comment]
@marcosvanella thanks!
