### ISSUE TITLE
FDS should stop with an error if a simulation contains a mixture of meshes with the CYLINDRICAL flag set and unset

### ISSUE THREAD

**Issue by errant-ctrl** [firemodels/fds#8519]
If FDS has a mixture of meshes with the CYLINDRICAL flag set and unset, it appears to just run as a 2D calculation with translational symmetry in the Y direction, ignoring the CYLINDRICAL flag. However such a calculation definition probably indicates that the user has made an error. It would seem to be a reasonable enhancement to check for inconsistency in how the calculation symmetry is defined and stop calculations with inconsistent mesh symmetries.

**Comment by mcgratta** [comment]
This is working, and firebot found no problems.
