### ISSUE TITLE
Validation case FM_Datacenter_Veltest_High does not run

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8550]
```
ERROR: SURF WALL LEAK_PATH greater than number of ZONEs. (CHID: FM_Datacenter_Veltest_High)
```
All other cases ran. I couldn't figure out how to fix this one. Fix it and I'll rerun it.

**Comment by drjfloyd** [comment]
The only difference between low and high should have been the velocity and the DEVC locations. High had LEAK_PATH defined but low didn't. At one point my input for this was a sealed room with HVAC vents for the inlet, but I changed to the particles with screen drag to better represent in the inlet flow variation over the inlet. There isn't a ZONE anymore, and I've added more HVAC error checking in the past year. I pushed up with LEAK_PATH removed try that.

**Comment by mcgratta** [comment]
Thanks. I noticed this in other datasets too.
