### ISSUE TITLE
Problem running FDS on AMD processors

### ISSUE THREAD

**Issue by FireCP** [firemodels/fds#8557]
I have a couple of students who are having trouble running FDS on their computers with AMD processors (Athlon and A8). The computer with the AMD Athlon processor is a brand new Windows 10 computer and the AMD A8 computer is also fairly recent.

From previous issues that have been closed, I see that others have had trouble running FDS on AMD processors. Chris Lautenberger and I tried to troubleshoot this issue with one of the students yesterday without success. The symptoms are similar to those described in previous closed issues. FDS loads and acts like it is running without any error messages, but it just sits there and does not write any output files; the user has to CNTL C out of it.

The students have run FDS through the cmdFDS command prompt window, have run FDS as the administrator and have moved their input files to the Desktop to run.

The fact that both of these computers have AMD processors and others have previously reported similar issues on AMD processors suggests to me that there might be a connection here. Do you have a summary of potential problems and solutions related to running FDS under Windows 10 with AMD processors?

**Comment by mcgratta** [comment]
We're planning a maintenance release within the new few weeks. I will look through the many compiler options for Intel Fortran to see if there is something specific that applies to non-Intel processors.

**Comment by gforney** [comment]
did you use fds_local ?

**Comment by mcgratta** [comment]
This doesn't look promising...

Intel® Parallel Studio XE 2020 Composer Edition Fortran - Debug Solutions Release Notes
By Ronald W Green, Published: 12/09/2019, Last Updated: 12/09/2019

Product and Performance Information
Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors. These optimizations include SSE2, SSE3, and SSSE3 instruction sets and other optimizations. Intel does not guarantee the availability, functionality, or effectiveness of any optimization on microprocessors not manufactured by Intel. Microprocessor-dependent optimizations in this product are intended for use with Intel microprocessors. Certain optimizations not specific to Intel microarchitecture are reserved for Intel microprocessors. Please refer to the applicable product User and Reference Guides for more information regarding the specific instruction sets covered by this notice. Notice revision #20110804

**Comment by mcgratta** [comment]
Can Chris L compile FDS for Windows using the Intel compiler?

**Comment by FireCP** [comment]
In response to Glenn, the answer is yes, they have tried running fds_local.

In response to Kevin, I have just sent Chris L. an email and copied you to see if he can compile FDS for Windows.

Sorry to hear this may be a problem related to non-Intel processors and hope there will be a workaround. As noted in a previous thread on this issue, the cost/performance ratio of some AMD processors appears to be favorable.

**Comment by mcgratta** [comment]
Apparently, there's a long history between Intel and AMD over this sort of thing. From what I have gleaned from the Internet, Intel Fortran uses the SSE2 instruction set by default. We have not chosen a more aggressive Intel-only instruction set intentionally, but you never know whether one compiler option triggers another.

**Comment by drjfloyd** [comment]
The compiler seems to have options for processor dispatch (Qax). The price is a larger executable but I don't think that is an issue for us since generally memory requirements of the calculation are far larger than the executable.

**Comment by mcgratta** [comment]
Qax allows one to target specific Intel processors. That is not what we want to do.

**Comment by drjfloyd** [comment]
Guide to optimization says that you can use this to target many AMD processors

http://www.scc.kit.edu/scc/docs/HP-XC/intel-compilers/10.1/intel_optimizing_apps.pdf

You can also combine the processor-specific targeting switch with an automatic dispatch switch. The effect of this is to set the
base-level targeting for the generic code path that is generated. For example, specifying “/QaxP /QxW” (-axP –xW) will generate
two code paths: the “generic” code path will be set as “W” and the maximum optimization code path will be “P”. This setting is useful for the majority of applications that will run on both IA-32 and Intel 64 capable systems, including those from **AMD** as described in the recommendations section below.

**Comment by ghost** [comment]
I'll compile FDS with those options that Jason quoted above and distribute new executables to the students that are having trouble and report back.

**Comment by mcgratta** [comment]
Thanks. Could you find out exactly what flavor of Athlon, A8, or whatever these chips are. The issue is whether they support the SSE2 instruction set, which Intel claims as their default.

**Comment by mcgratta** [comment]
Just an update on this issue. We're beginning to think that there is some library missing from our FDS bundle. Up until recently, there was an option when compiling to "statically link," that is, to build all the necessary libraries into the .exe file that we distribute for Windows. The trend in recent years has been not to do this, but to rather rely on libraries that are already part of the operating system or to redistribute the necessary libraries with the distribution. That is what we do---when you install FDS on Windows, several extra files are added to the install directory that are needed to run the code. It appears that we are missing something that is needed by certain AMD processors. We'll put together a test bundle and have you test it.

**Comment by gforney** [comment]
we build bundles nightly whenever our v&v script firebot passes.  here is a link to those bundles
https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing

they are built using the latest intel compiler (version 2020 update 1 ). try out the windows test bundle .

I have seen this same behavior when I try to run fds that was built with one versio of the intel compler when I have a different intel compiler installed on my computer.  do you have the intel compilers installed on the amd computers that are giving you problems?

**Comment by mcgratta** [comment]
Has there been any progress on this issue? Have you tried the new FDS build on your AMD computers?

**Comment by DaleAMD** [comment]
Thanks for your efforts with this issue! I am one of the students with an AMD computer (A8). I used the Windows version of the bundles listed above and fds started working using both the commands, fds and fds_local. However, it appears to be slow and I'm not sure why. For example, I started running an FDS file yesterday (Saturday July 18) at around 12 noon. In the CMDfds window as I'm typing this comment, it shows that its at TIMESTEP 48400,  SIMULATION TIME: 515.56. I believe the simulation itself is about 900 seconds long, so it has about another 10 tp 15 hours before its finished. Do you have any suggestions on how I can speed up the process?
Thanks again for working on this issue.

**Comment by mcgratta** [comment]
FDS calculations can take months to run if you choose a fine enough grid.
The question is---how does this exact case compare with another
computer running the exact same executable.?

>

**Comment by DaleAMD** [comment]
I'm actually not sure if it does run faster on another computer but as long as the new build from the bundle works on my AMD, I'm happy. The simulation changes at 600 seconds which is exactly what I need for now. I will try and let it run until it finishes but I do have the option of stopping it at that time, its currently at 588 seconds.
Thanks Kevin for your help.

**Comment by mcgratta** [comment]
Glenn -- what is done in the new bundle that is not done in the old? Was there a missing library?

**Comment by gforney** [comment]
Fds was built with intel version 20 update 1 in this bundle. Fds was built
with 19 update 4 in the old bundle. That is the nain difference.   Dont
recall adding additional library files in new bundle .

**Comment by DaleAMD** [comment]
Hi guys, one other thing to consider. It looks like I may have installed FDS and/or CFAST on my computer previously during my undergrad. What I did before installing the new bundle was completely uninstall FDS and CFAST and rename the firemodels folder because it did not appear to remove the folder during the uninstall. I had the new bundle install a new copy of the firemodels folder from scratch. I don't know if that was causing the problem but it all works now including CFAST which was working with the old bundle.

**Comment by gforney** [comment]
Smokeview is used by both fds and cfast. So the fds uninstall should only
uninstall smokeview if cfast is absent. Likewise the cfast uninstall should
only uninstall smokeview if fds is absent. Think it doesn't uninstall the
firemodels directory because the uninstall script "lives" below it.

Dont think cfast uses any runtime libraries that would interfere with fds
but i will check

**Comment by DaleAMD** [comment]
Hi Glenn, I should have mentioned that I uninstalled and reinstalled CFAST as well because I wanted to completely start from scratch.

**Comment by gforney** [comment]
Thanks. Ill investigate whether fds and cfast built with different
compilers coukd cause problems. What version if cfast did you install?

**Comment by DaleAMD** [comment]
Thanks Glenn. Its version 7.5. I believe it is the latest version.

**Comment by mcgratta** [comment]
I am going to close this issue. If in future we run into more problems with AMD processors, we'll open a new issue.

**Comment by FireCP** [comment]
Thanks, Kevin. We appreciate the effort you and your colleagues put into resolving this so quickly.


Frederick W. Mowrer

Director

Fire Protection Engineering Programs

Cal Poly - San Luis Obispo


805-756-7834 Office

240-988-8979 Cell (preferred)

________________________________

**Comment by gforney** [comment]
To follow up, I talked with Rick Peacock - he puts together the CFAST bundle.  He told me that the CFAST bundle doesn't need any runtime libraries.  So I wouldn't expect the cfast bundle to interfere with the fds bundle if it was built with a different version of the Intel compiler .
