### ISSUE TITLE
AEROSOL VOLUME FRACTION

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8572]
```
ERROR: SPEC_ID SOOT for AEROSOL VOLUME FRACTION must be a tracked species (CHID: FM_15cm_Burner_C2H4_16p8_2cm)
```
These cases worked in the past by using the solid density of soot. Can we not do that now?

**Comment by drjfloyd** [comment]
That worked at one point? I never intended for AEROSOL VOLUME FRACTION to work unless the SPEC was an aerosol. Treating SOOT as a special type of aerosol species so we get aerosol outputs even when it is part of a lumped species is going to add some complexity to output routines.

**Comment by mcgratta** [comment]
```
   CASE(96)  ! AEROSOL VOLUME FRACTION
      IF (Z_INDEX >0) THEN
         GAS_PHASE_OUTPUT_RES = Y_SPECIES*RHO(II,JJ,KK)/SPECIES(SPECIES_MIXTURE(Z_INDEX)%SINGLE_SPEC_INDEX)%DENSITY_SOLID
      ELSEIF (Y_INDEX>0) THEN
         GAS_PHASE_OUTPUT_RES = Y_SPECIES*RHO(II,JJ,KK)/SPECIES(Y_INDEX)%DENSITY_SOLID
      ENDIF
```
This sounds to me like we allow non-lumped species to be evaluated.

**Comment by drjfloyd** [comment]
SINGLE_SPEC_INDEX, i,e. the SPECIES_MIXTURE can only have one species.

**Comment by drjfloyd** [comment]
Should be working now

**Comment by mcgratta** [comment]
Thanks
