### ISSUE TITLE
GEOM room fails

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8585]
I was trying to make a case to test the pressure rise in a compartment defined with OBST vs. GEOM.  There are two meshes one with five OBST defining 4 walls and a ceiling plus a sixth OBST for an inlet, and second mesh with the same OBST (translated to the second mesh) made into GEOM.  I put a MOVE_ID on the GEOM to rotate the entire room.

If I just run with the OBST mesh it runs and behaves as expected.

If I rotate the GEOM zero degrees (or remove the MOVE_ID), the case dies giving the error:
 Error GET_X2INTERSECTIONS: IS_CRS(LOW_IND,ICRS) ~= LEFT_MEDIA, media continuity problem
 X1AXIS,X1PLN=           2  0.000000000000000E+000 , X2AXIS,X3AXIS=           3           1 , RAY X3 POSITION=   4.05000000000000 

If I rotate 45 degrees I get a lot of warning messages like:
IFLG ~=0, could not close polyline,  T :           20           6          10

then the case runs for a short bit and dies in the GET_VISCOSITY call in wall.f90 at line 3738.

[geom_pres .fds.txt](https://github.com/firemodels/fds/files/4920327/geom_pres.fds.txt)

**Comment by marcosvanella** [comment]
Ok, volume flow is not implemented for GEOM. I'll work on it.
