### ISSUE TITLE
room pressurization and zone bleed through with GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8586]
The attached case has two meshes. In each mesh there is a 1 m x 1 m x 1 m compartment with 3 cell thick walls and ceiling defined with OBST. The default surface is ADIABATIC. On the left side three cell high OBST across the width are used to separate the compartment in two diagonally. The OBST are defined so exactly half the grid cells in the compartment are below the division. On the right side a diagonal GEOM is defined that is the vertical thickness of 3 cells high and has exactly half the volume below it. Four pressure zones are defined (top and bottom of each compartment). On the floor in each is a VENT that for 10 s injects gas.

Within 1 s the upper zone on the GEOM side has increased in pressure by 4 Pa but on the OBST side the increase is only 0.02 Pa. 
The pressure rises slightly faster on the GEOM side even though the volume should be the same and some pressure is bleeding to the other zone.  By 10 s there is a 10 % difference in pressure in the lower zones.  At 11 s the RAMP for the inflow decays to 0.  The pressure keeps rising on the GEOM side, although at a much slower rate, even though there should no longer be any mass addition. The upper GEOM portion winds up with 1/6 the total pressure rise of the lower portion. The upper OBST portion only increases 0.1 Pa or 4E-5 % of the lower pressure rise. If I set the velocity tolerance to 1E-5 m/s and 100 iterations there is essentially no change to bleed through with a 400 % increase in run time.

![image](https://user-images.githubusercontent.com/12799217/87463598-b0094d80-c5df-11ea-9653-7c17e7276b0c.png)

[geom_pres_2.fds.txt](https://github.com/firemodels/fds/files/4920637/geom_pres_2.fds.txt)

**Comment by drjfloyd** [comment]
For comparison I ran the OBST case the dividing OBST as one layer of thin obstructions and two layers of thin obstructions separated by one cell. At the end the single layer showed a pressure rise in the upper portion of 0.02 % of the lower. For the two layer the middle zone between layers had a pressure rise of 3 % of the lower zone and the upper zone 0.001 % of the lower zone.

**Comment by marcosvanella** [comment]
Thank you Jason, I'll take a look.
