### ISSUE TITLE
MW_RATIO in velocity divergence formula

### ISSUE THREAD

**Issue by ruddymell** [firemodels/fds#8589]
In wall.f90 there’s the following code to add to D_SOURCE the mass of gas species generated during a particle's degradation

      MW_RATIO = SPECIES_MIXTURE(NS)%RCON/ONE_D%RSUM_G
      M_DOT_SINGLE = LP%PWT*ONE_D%M_DOT_G_PP_ADJUST(NS)*ONE_D%AREA
      LP%M_DOT = ONE_D%M_DOT_G_PP_ADJUST(NS)*ONE_D%AREA
      D_SOURCE(IIG,JJG,KKG) = D_SOURCE(IIG,JJG,KKG) + M_DOT_SINGLE*(MW_RATIO/M_GAS)

It appears the MW_RATIO computed above is the ratio of the molecular weight of gas species, NS, over the gas mixture's molecular weight (the gas constant R divides out). However, when I derive the velocity divergence and in expressions for the  divergence in the FDS tech guide Appendix B, I find that the inverse of the MW_RATIO, as computed above, should be used in D_SOURCE. Am I missing something? Thanks.

**Comment by mcgratta** [comment]
MW_RATIO = (R/W_alpha) / (R/W_avg) = W_avg/W_alpha

Do you question what is written in the code or what is written in the Tech Guide?

Jason, could you double check me. Thanks

**Comment by drjfloyd** [comment]
I think I trust whatever is in the droplet evaporation. If that is incorrect I don't think we would be getting the water_evaporation cases correct. I'll look at it.

**Comment by ruddymell** [comment]
I think the Tech Guide is correct, or at least consistent with my derivation of the terms in question in the velocity divergence.

**Comment by drjfloyd** [comment]
If flip MW_GAS/MW_DROP in the droplet routine water_evaporation_1 fails. The exact end temperature is 154.3, the current source gives 154.5, and flipping gives 146.6.  Pressure values are -7810, -7780, and -9510 respectively.

**Comment by mcgratta** [comment]
If the Tech Guide is correct, do you agree with my explanation above?

**Comment by drjfloyd** [comment]
@mcgratta Yes, I agree with your explanation above. RCON and RSUM are R/W so MW_RATIO = RCON_ALPHA / RCON_AVG = MW_AVG/MW_ALPHA which is what is in equation 3.25.

**Comment by ruddymell** [comment]
You're correct. I made a mistake in my interpretation of the notation in the code versus the tech guide. Thanks for the quick reply.

**Comment by mcgratta** [comment]
No problem. The divergence is a complicated expression.
