### ISSUE TITLE
HRR and MLR is incorrectly integrated in cylindrical symmetry

### ISSUE THREAD

**Issue by errant-ctrl** [firemodels/fds#8597]
Hi,

When I run an FDS calculation modelling burn away of a small cylinder in cylindrical symmetry, I find that the heat release rate (HRR) and mass loss rate (MLR) as reported in *hrr.csv is about a factor of 1E5 smaller the corresponding value for a similarly dimensioned cube in a 3D simulation domain. This suggests that these quantities are not being correctly integrated with respect to theta. We had a look at dump.f90 and found that there does not appear to be a check for cylindrical symmetry in dump_hrr. This may indicate that it does not match the description of integration in this special case detailed in section 20.10.1 of the manual (although I am receiving that info second-hand).

Please compare the following calculations: **2dcyl** gives tiny HRR compared to **3dbox**. Note that these are moderately expensive calculations, however they can be killed after a few iterations to check the markedly different HRR data.

[2dcyl_hrr_mwe.fds.txt](https://github.com/firemodels/fds/files/4944867/2dcyl_hrr_mwe.fds.txt)
[3dbox_hrr_mwe.fds.txt](https://github.com/firemodels/fds/files/4944868/3dbox_hrr_mwe.fds.txt)

As a stopgap measure, is the HRR and MLR data in the cylindrical case directly proportional to the true value? Because if this is the case normalised values over time are still useful for me to report.

Thanks for your time.

**Comment by mcgratta** [comment]
These values are based on the actual "slice" of the cylinder. The difference in the y values is the dtheta. First check that your results are consistent when integrating over the entire circle.

**Comment by rmcdermo** [comment]
I know it's not visually appealing in Smokeview, but I always tells students to set YMIN=-0.5, YMAX=0.5 and then multiply results by 2*pi.

**Comment by errant-ctrl** [comment]
Ah, my Y-thickness was 0.0002 m, which I take it means that within the cylindrical scheme it represents a slice of radial width 2π ⨉ 0.0002 radians. I appear to get consistent results now. I guess this issue can be closed. Thanks for the advice.

**Comment by mcgratta** [comment]
I'll check to see if we note this in the User's Guide.
