### ISSUE TITLE
different behavior of droplets with GEOM

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8606]
The attached input is four 1 m^3 meshes with an 0.2 m per side box in the center. Mesh 1 is OBST, Mesh 2 is GEOM, Mesh 3 is GEOM rotated 45 degrees about 1,1,1, and Mesh 4 is the GEOM offset by half of a grid cell.  The ceiling of each mesh has a sprinkler with a narrow angle so all the drops hit the box first.. A few things:

1. The behavior of AMPUA is different.  In Mesh 1 with OBST we only see AMPUA when the spray hits the top of the box and none when it drips down to the floor. In the other Meshes we see AMPUA both on the box and as it drips to the floor. Note on this see the related issue #8607  on Smokeview and AMPUA with GEOM.
2. The speed of drops moving down the sides of the GEOM is different than the OBST.  At 1 s Mesh 1 is just about to drip off the bottom of the box, Mesh 2 is only about 1/4 of the way down the side of the box, and Mesh 4 has a drop getting close to the floor.
3. In Mesh 4 with the offset box drops leave the top of the box and appear to enter the gas rather than run down the box. This can be seen at the floor where the ring of drops is noticeably larger.

[geom_noz.fds.txt](https://github.com/firemodels/fds/files/4949886/geom_noz.fds.txt)

**Comment by marcosvanella** [comment]
Hi Jason, thanks. We'll take a look at this.

**Comment by mcgratta** [comment]
AMPUA mimics a "bucket test," that is, it only records the droplet mass when it first strikes the surface. That is why you see the OBST top recording AMPUA. For the sides, we would look at MPUA. Both have units of kg/m2, but AMPUA is accumulated and MPUA is instantaneous.

**Comment by mcgratta** [comment]
Fixed the speed issue. I had been assigning HORIZONTAL_VELOCITY for all droplet velocity components. Now VERTICAL_VELOCITY is assigned to LP%W.

**Comment by drjfloyd** [comment]
That isn't what GEOM did. The spray cone is narrow enough so it only hits the box top. GEOM is showing AMPUA on the floor after all drops have already hit the box.

**Comment by mcgratta** [comment]
Yes, this feature is not working for GEOM yet because there is no clear
vertical.

>

**Comment by mcgratta** [comment]
```
               LP%CFACE_INDEX = ICF
               LP%ONE_D%IOR = 1
            ENDIF CFACE_ATTACH
            CYCLE PARTICLE_LOOP
```
Marcos, why do you `CYCLE` out of `PARTICLE_LOOP` when a droplet finds a `CFACE`?

**Comment by marcosvanella** [comment]
In the ELSE part of the CFACE_ATTACH we have a CFACE that will determine how the particle moves. In there the positions and velocities for the particle are set. On the other hand, when the particle is detached (cface normal in direction of GVEC) it just maintains its X,Y,Z and gravity will move it downwards on the next step. Is there anything else that needs to be set below in the loop?

**Comment by mcgratta** [comment]
I need a droplet that has just struck a solid surface to get processed by this loop:
```
            ! Add PARTICLE mass to accumulated liquid array if it has not already been counted (LP%SPLAT=F)

            IF (ACCUMULATE_WATER .AND. .NOT.LP%SPLAT .AND. LPC%LIQUID_DROPLET) THEN
               IF (LP%WALL_INDEX>0) THEN
                  ONE_D => WALL(LP%WALL_INDEX)%ONE_D
               ELSEIF (LP%CFACE_INDEX>0) THEN
                  ONE_D => CFACE(LP%CFACE_INDEX)%ONE_D
               ENDIF
               IF (LP%WALL_INDEX>0 .OR. LP%CFACE_INDEX>0) THEN
                  ONE_D%A_LP_MPUA(LPC%ARRAY_INDEX) = ONE_D%A_LP_MPUA(LPC%ARRAY_INDEX) + LP%PWT*LPC%FTPR*R_D**3/ONE_D%AREA
                  LP%SPLAT = .TRUE.
               ENDIF
            ENDIF
```
For mesh 2, no droplets can enter this loop because `LP%CFACE_INDEX=0` for all of them.

**Comment by marcosvanella** [comment]
I see, when we get a CFACE attached we want to set HIT_SOLD=T and do that conditional.

**Comment by mcgratta** [comment]
Correct. We just need to do it once, after which SPLAT=T, indicating that
the droplet has hit the solid once.

>

**Comment by marcosvanella** [comment]
Another question. There is an ICOORD loop related to WALL_CELLS just before the ACCUMULATE_WATER conditional. If CFACE_INDEX>0 and HIT_SOLID=T we probably want to avoid avoid going in there.

**Comment by mcgratta** [comment]
Not sure what you are referring to.

>

**Comment by marcosvanella** [comment]
From line 1616 on there is a test on WALL_CELLs that we probably don't need if we are already attached to a CFACE.

**Comment by marcosvanella** [comment]
There is also the DIRECTION: SELECT CASE(LP%ONE_D%IOR) case that is also related to wall cells after the ACCUMULATE_WATER conditional. We might want to move this test for CFACEs to the CFACE search loop. Is this what you are thinking?

**Comment by mcgratta** [comment]
I see what you mean. Let me rework these loops to clearly distinguish OBST
and GEOMs.

>

**Comment by mcgratta** [comment]
I'm going to move chunks of code in part.f90. Do you have any changes you
want to commit now?

>

**Comment by marcosvanella** [comment]
I'm good. Go ahead.

**Comment by mcgratta** [comment]
Marcos, I reworked some loops and IF statements to make it more clear when a block of code is appropriate for a CFACE, WALL, or both. But I still have trouble when I remove the CYCLE PARTICLE_LOOP from the CFACE search loop. Two issues:

1. When a droplet hits a CFACE, I need it to go to where HIT_SOLID=T. There are some things that need to be done to a droplet that hits a solid for the first time. Not only do we ACCUMULATE, but we also change the droplet size and weighting.

2. We need to think about the cube in mesh 4 that is shifted to the right, and no longer snaps to the Cartesian grid. I think that the closest CFACE is still the horizontal top of the cube, in which case the droplets move horizontally until they reach a cell with no CFACEs.

**Comment by marcosvanella** [comment]
Ok, I'll investigate the CYCLE PARTICLE_LOOP issue.

**Comment by mcgratta** [comment]
Yes, and I'll investigate why a droplet case failed last night. Don't
commit changes to part.f90 until I sort out the problem

>

**Comment by mcgratta** [comment]
I'm making gradual improvements for both OBSTs and GEOMs and droplets. I think mesh 4, where the cube is off-set from the Cartesian grid, is the remaining issue.

**Comment by mcgratta** [comment]
Marcos -- it seems to me that when a droplet moves along an immersed boundary, it follows the slope of the nearest CFACE. In mesh 4, I see droplets moving along the top of the cube, and the nearest CFACE is a piece of the horizontal top of the cube. As long as the Cartesian grid cell has a part of the cube within it, the droplet follows that horizontal CFACE. Once the droplet leaves the cell, it no longer finds any CFACEs (or WALL cells) and so it drops via a parabolic trajectory towards the ground. Is there a way that we can project a line from droplet parallel to the normal of the CFACE, and if that line from the droplet does not intersect the CFACE, then it is no longer controlled by it?

**Comment by marcosvanella** [comment]
CFACEs are planar regular polygons. We can do this by noting the projection location on the plane of the CFACE, and doing an inside outside test (i.e. winding number test). 
I saw the situation where the droplets fall on the side of the cube (mesh 4) instead of sticking to the side. Question is how do we assign it to the side CFACE. We can try looking again in the cell w/o considering the horizontal CFACE the particle just left. 
Note that for a particle in the corner of the obstacle it can happen that no normal projection falls within the area of a CFACE. In such a case the closest point lays on an edge or vertex of the polygon mesh.

**Comment by mcgratta** [comment]
The way it works for OBSTs is that when a droplet discovers that it no longer has a solid surface supporting it, it changes direction in the hopes of finding a surface. So for example, if a droplet is moving along a horizontal surface and discovers that there is no longer anything below it, it drops down a small distance and then reverses direction. In the next time step, it hits the side of the box and slides down. If there is no side of the box, it just falls.

**Comment by marcosvanella** [comment]
Ok, we can do that too. I'm looking at the cycle statement. Somehow when I comment it the particles stay in place when they touch the surface. Is this what you found?

**Comment by mcgratta** [comment]
I noticed in mesh 2 that some of the droplets "stuck" to the top of the
cube. Haven't looked at it more closely. One thing to keep in mind is that
I removed a CYCLE statement that appeared just after the line
```
ENDIF CFACE_ATTACH
```
I did this because I want to allow droplets that hit a CFACE to continue
through the PARICLE_LOOP. I added logic to ensure that a droplet that is
stuck to a CFACE does not get confused with a droplet that sticks to a WALL
cell.

>

**Comment by marcosvanella** [comment]
Sorry, was running without your latest commit. I'll try also the e_coefficient.fds test with the latest.

**Comment by marcosvanella** [comment]
e_coefficient looks fine. For geoms Jasons case shows the particles kind of blurred in the top of cubes. Might have to do with them first getting into the solid and then being put back in the surface and assigned a CFACE. I'll look at the method for the sides (mesh 4).

**Comment by drjfloyd** [comment]
The BNDF data for AMPUA looks good now. The DEVC isn't quite right. Drops hit the boxes in about 0.3 s.  All the BNDF files show this. The DEVC however does not. The three GEOM meshes don't show the DEVC changing until 1.3, 0.93, and 0.99 s. Ultimately Meshes 3 and 4 wind up with the same total accumulation as Mesh 1 (expect 10 kg and they all get 9.98 kg which I think is simply the RAMP and DT interacting). Mesh 2 only gets to 8.73. If the data is plotted it does show a slightly slower slope.

**Comment by marcosvanella** [comment]
Kevin, you want to look at the DEVCs? I'm on the droplet flying off the top issue of mesh 4.

**Comment by mcgratta** [comment]
Yes, I only focussed on qualitative behavior, Will look at quants.

>

**Comment by mcgratta** [comment]
Marcos, in mesh 2, one CFACE on the top of the box has droplets stick and not move. This is the likely reason for seeing less droplet mass on the floor. I cannot figure out why one CFACE would act this way.

**Comment by marcosvanella** [comment]
Yes I isolated the behavior to a single stuck part. I'm looking at the logic now.
![Screen Shot 2020-07-24 at 4 39 33 PM](https://user-images.githubusercontent.com/7450069/88433571-59b0c180-cdcc-11ea-9cd3-d011ad5ca18d.png)

**Comment by drjfloyd** [comment]
The AMPUA integration is over the surface of box not the floor of the domain.  It is possible that stuck droplets may not be related.

**Comment by mcgratta** [comment]
I think the integrations are over the floor, except for mesh 1, where it is
over the box top and the floor.

>

**Comment by drjfloyd** [comment]
Ugh, you are right. I forgot what my own test case was.  Changing to box surface only they all match and all show the correct value; however, as AMPUA should they only be counted once or do we reset SPLAT if a particle drips back into the gas ?

**Comment by marcosvanella** [comment]
Are we missing an integral over CFACEs?

**Comment by mcgratta** [comment]
SPLAT gets reset when the particle re-enters the gas phase.

>

**Comment by mcgratta** [comment]
I don't think we are missing an integral. The reason that there is less
water on the floor in mesh 2 is because some of the droplets stick to the
top of the box, in a single CFACE.

>

**Comment by marcosvanella** [comment]
Ok. I'm on it.

**Comment by marcosvanella** [comment]
Is there a way to keep the particles in the domain over the whole simulation? It seems the ones that touch the floor get taken out of the particle list. I don't want the index IP of a particle of interest to change in my test. I used an obst but was wondering if there is a way to keep the water droplets on the floor.

**Comment by drjfloyd** [comment]
By default POROUS_FLOOR=TRUE for ZMIN.  Set it to FALSE and particles will not go through the floor. They will start to move horizontally and leave the sides unless you put a solid wall there.

**Comment by marcosvanella** [comment]
Thank you Jason. 
The last commit should take care of the stuck particles. I had to add an eps when moving particles from the solid back to the CFACE surface. I'm still working on Mesh 4, but you can check again the quants.

**Comment by marcosvanella** [comment]
The case in mesh 4 should work now. Do an update and try it.

**Comment by drjfloyd** [comment]
Mesh 4 looks a lot better. I am not seeing particles in the air around the side of the box; however, after the spray ends I see a line of particles in the 4th mesh that are stuck and then a short time later fall straight through the box.

![geom_noz_0805](https://user-images.githubusercontent.com/12799217/88856864-3e2a2a00-d1c3-11ea-8e46-978feb458aa3.png)

![geom_noz_0827](https://user-images.githubusercontent.com/12799217/88856862-3e2a2a00-d1c3-11ea-9b54-c777b70aa8d1.png)

**Comment by marcosvanella** [comment]
Thank you Jason. I made a change in the logic. Do an update and try it now to see if it behaves better.

**Comment by drjfloyd** [comment]
I changed the BNDF to CELL_CENTERED and reran. I don't see any odd droplet behavior anymore on the tops of the boxes or on the sides of the boxes; however, the floor AMPUA on the floor is not quite as expected. The left two should have identical patterns on the floor but the GEOM is making a ring one cell larger than the OBST.  The angled box is as expected with almost all the flow in one spot in the floor since almost all the spray hits one of the angled to faces. While the box on the far right also has a larger ring than the OBST, it does correctly have a higher density of water in one corner due to the offset of the box.

![geom_noz_0448](https://user-images.githubusercontent.com/12799217/89229283-254cba80-d5af-11ea-9be4-b2c81d8312f8.png)

**Comment by marcosvanella** [comment]
Ok, it seems to me that droplets for the OBST turn around a bit under the box, whereas there is no logic for that in GEOMs. 
Maybe Kevin can give a bit more insight in this part of the model.

**Comment by mcgratta** [comment]
The underside behavior of the droplets was developed with racked storage in
mind. The way it works for rectangular obstructions is that a droplet that
is falling on a vertical surface, when it sees that it no longer has a
surface to stick to, is moved inward a small amount and then shot upwards
so that it will ether stick to the bottom of the box and move about
(ALLOW_UNDERSIDE_DROPLETS=T) or just drop straight down.

Possible action for GEOMs is to push the droplet in the direction opposite
the last normal, so as to make the droplet "round" the lower edge of the
obstruction.

>

**Comment by mcgratta** [comment]
Is the four mesh case just above in the verification suite? If so, what folder?

**Comment by marcosvanella** [comment]
Kevin, it is not in the suite. Feel free to add it.

**Comment by mcgratta** [comment]
I added the case at the start of this thread as a verification test, geom_particle_cascade_2 in Complex_Geometry.

**Comment by drjfloyd** [comment]
Was this resolved? Do GEOM particles now track under an GEOM like they do for OBST?

**Comment by drjfloyd** [comment]
This still appears to not be working quite right.

The OBST is the left and the GEOM is the right. The patterns are quite different and they should look very similar. Also, the GEOM pattern isn't what I would expect. I expected that drops hit the top surface and then get a random direction to move over the surface.  So if we were to draw a circle inside the top the mass flux of water should be the same everywhere. Since the centers of the top edge have a smaller radius than the corners of the top edge the droplet mass flux through the corners should be less. We should see this on the floor. For the OBST we do. On the floor the areas below the center of the edges have more water than drips right at the corner. For the GEOM the pattern looks random.

![geom_particle_cascade_2_0452](https://user-images.githubusercontent.com/12799217/97048285-2bb45800-1548-11eb-9a5d-4901b5223844.png)

**Comment by rmcdermo** [comment]
Is BNDF of AMPUA also not hooked up for GEOM?  Above it appeared to work.

**Comment by marcosvanella** [comment]
So looks like the floor AMPUA pattern is more square under the GEOM than the OBST.  I'll have another look.
AMPUA can be loaded for geometries, has to be done separately now (click AMPUA (GEOMETRY)).

**Comment by drjfloyd** [comment]
Randy,  Smokeview loads GEOM BNDF and OBST BNDF through different menu items and I only loaded the OBST file since I was just interested in the floor.

**Comment by rmcdermo** [comment]
OK, is that what we want?  I think it is time that BNDF, SLCF, etc. are transparent to the user.

**Comment by mcgratta** [comment]
The issue here is that for OBSTs, the droplets drip down the side of the box, and then at the bottom are kicked inward, as if there is some surface tension that draws the droplet around the lower edge. This was done for the box burning cases to allow water droplets to pool up on the box top below in a stack. Currently GEOM droplets do not have this feature.

**Comment by marcosvanella** [comment]
Yes, but there is also an effect related to the default IBM forcing. See this pic using the stress method we are working on (unpushed) which does what OBSTs do for velocities next to the wall. Looks more similar. The particles scheme in geoms has not been changed.
![Screen Shot 2020-10-23 at 5 38 37 PM](https://user-images.githubusercontent.com/7450069/97056384-dd5a8580-1556-11eb-8b6e-434c3e7b485c.png)

**Comment by mcgratta** [comment]
These are water droplets. Once they hit the box, they move in a straight
line at constant speed. It's the dripping off the bottom that is different.

>

**Comment by mcgratta** [comment]
I am going to close this issue for now. There are still subtle differences in the way OBSTs and GEOMs treat water droplets, and we can investigate these as they arise.

**Comment by drjfloyd** [comment]
Mesh 1 and 2 are the same box just GEOM in 2. 4 is GEOM but off centered compared to the grid. 

Mesh 2 results are very different than mesh 1 as no drops are going under the edge of the box. If this is just a current limitation with GEOM it may be good to mention in the Guide.

Mesh 3 looks fine.

Mesh 4 there are two hot spots away from the box. Periodically particles are getting kicked off the box with a higher horizontal velocity resulting in these hot spots.

![geom_noz_0827](https://user-images.githubusercontent.com/12799217/231254849-9c0f3eb7-0c93-4ad7-89e0-4b1fcba6591b.png)

**Comment by mcgratta** [comment]
But these dripping cases have more to do with the specific logic in part.f90 that is used to guide a droplet on a surface.
