### ISSUE TITLE
GEOM with TMP_INNER

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8617]
The attached case is two 1 m^3 with an 0.008 m^3 box at the center. Mesh 1 is OBST, MESH 2 is GEOM. The box has 1 mm thick surface with DENSITY=1000, SPECIFIC_HEAT=1, and TMP_INNER=100. For simplicity the gas is given SPECIFIC_HEAT=1 and an MW to give 1 kg of gas in the box.

A DEVC measuring wall temperature and the BNDF shows that the GEOM is not 100 at t=0 like it should be. It takes ~half a second for the initial condition to be seen.  However a DEVC for wall enthalpy is showing the correct value at t=0 and the SLCF for gas temperature shows convection is happening right away.

Good news is energy conservation appears to be OK for GEOM in this test case.

[geom_solid_h.txt](https://github.com/firemodels/fds/files/4956342/geom_solid_h.txt)

**Comment by marcosvanella** [comment]
Hi Jason, good I'll take a look. Closing in on the wall model defining stresses here. Then I'll get back to all these.

**Comment by mcgratta** [comment]
Marcos, if these cases are not purely GEOM problems, kick them to me.

**Comment by marcosvanella** [comment]
Kevin, sure, you want to check this delay on BNDF and also issue  #8606 on droplets? Take a look and kick them back to me, if needed. Thanks.

**Comment by mcgratta** [comment]
I'll take a look at this issue now.

**Comment by mcgratta** [comment]
Marcos, I changed the initialization of CFA%ONE_D%TMP_F in geom.f90. Double check my change and then close. It works in this case.

**Comment by marcosvanella** [comment]
Change is correct, CFA has the SURF_INDEX from the triangle it's been carved from. Let me move those CFA initializations to a call to INIT_CFACE_CELL. I noted I'm initializing ONE_D%U_NORMAL_0 and T_IGN in a different place.

**Comment by drjfloyd** [comment]
The BNDF and DEVC file are correct now with these changes.

**Comment by marcosvanella** [comment]
Jason, try it again with my last changes. I moved all CFACE ONE_D initializations to the same routine. 
Temp SLCF shows differences between the two meshes, but first thing is to change the IBM treatment for momentum as discussed.

**Comment by drjfloyd** [comment]
I tried it again. The BNDF and DEVC are working correctly. They also all wind up at the same end point, albeit with different rates for the reasons you note. Closing this issue as the IBM is covered under other a few other open issues.
