### ISSUE TITLE
mpiexec issue

### ISSUE THREAD

**Issue by Archithvk** [firemodels/fds#8626]
Hi, when I run this command **mpiexec -n 4 fds filename.fds** in windows 7,  I am getting an error as below. I am using fds 6.7.4
Also when i run just  in series by command **fds filename.fds**  then it is running fine.

![mpiexec error](https://user-images.githubusercontent.com/68684445/88265959-fb141680-cceb-11ea-802f-5ce820242127.PNG)

**Comment by rmcdermo** [comment]
Please post your question to the [discussion forum](https://groups.google.com/g/fds-smv).  This does not appear to be a bug in FDS.

**Comment by mcgratta** [comment]
Add -localonly as an option to your mpiexec command.

>
