### ISSUE TITLE
smokeview dies with allocation error

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8644]
Version          : Test
Revision         : SMV6.7.14-526-g082bfa46e-master
Revision Date    : Fri Jul 17 12:07:37 2020 -0400
Compilation Date : Jul 17 2020 12:49:54
Compiler         : Intel C/C++ 19.0.4.228
Checksum(SHA1)   : 2786b314ca156471cb56b38ca273d79493f06427
Platform         : WIN64  (Intel C/C++)

The attached fds file creates an smv file that won't load in smokeview. it gives the error:

*** Error: memory allocation request of size 18446744073709551492 failed
             variable: (void **)&fds_title
                 size: 4294967172
                 file: ../../../Source//smokeview/readsmv.c
          line number: 5711

[l50-98th-tbl-int_2.fds.txt](https://github.com/firemodels/fds/files/5003397/l50-98th-tbl-int_2.fds.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
smokeview posted here should fix the problem 
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

I'm working on changes to improve the bounds dialog box. (which will also fix some of the other problems you found).  These changes are not quite ready.  The smokeview posted above may still have those problems (was built in a different branch)

if you shorten your title to less than 128 characters your case should work with the smokeview you have.

**Comment by drjfloyd** [comment]
Thanks Glenn. New version loads the file.
