### ISSUE TITLE
GEOM display of face outlines

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8646]
Tried making a GEOM version of the NIST Soot Deposition Gauge input.  When I view the face outlines they don't line up with the solid object (the solid object is correct). 

This geometry has a cylindrical rod as one of the components. I made it by defining a circle with a point every 10 degrees and extruding it. The faces on the ends appear to be drawn as triangles radiating from a single point on the circle. It looks odd. Would this have any impact on the flow field.

When I run the case I appear to only have gravitational deposition onto the rod as there should be a much large spot of deposition where the incoming flow impinges on the rod. This suggests that ONE_D%U_TAU is zero.
 
![NIST_SDG_geom_s0000](https://user-images.githubusercontent.com/12799217/89227716-2c25fe00-d5ac-11ea-89f8-edf8a4b84ec4.png)

[NIST_SDG_geom.fds.txt](https://github.com/firemodels/fds/files/5018601/NIST_SDG_geom.fds.txt)

![NIST_SDG_geom_0163](https://user-images.githubusercontent.com/12799217/89228188-20870700-d5ad-11ea-8043-00022fa3310f.png)

**Comment by rmcdermo** [comment]
Jason,
Getting correct U_TAU for any surface in GEOM is the crux of the stress problem we are working on.  I would expect it to be too low (but not zero).

**Comment by drjfloyd** [comment]
It appears to be zero.  I've attached the OBST and GEOM with the same scale at the same time. 

Note: I just realized I erred and defined the polygon using the diameter as the radius so that is why the rod looks bigger in the geom version. That shouldn't have an impact on the basic observation though.

![NIST_SDG_obst_0163](https://user-images.githubusercontent.com/12799217/89230779-00a61200-d5b2-11ea-917c-b18b228673c9.png)
![NIST_SDG_geom_0163](https://user-images.githubusercontent.com/12799217/89230780-00a61200-d5b2-11ea-8480-91466555ceaf.png)

**Comment by rmcdermo** [comment]
I am trying to get caught up on where the stress model stands after being on leave.  But it looks to me like ONE_D%U_TAU is not being set in a call from WALL_MODEL on a CFACE.  It is possible that this got dropped when going from the the forcing method to using stresses on Cartesian edges.

@marcosvanella let's talk about this when you get time.

**Comment by marcosvanella** [comment]
Jason and Randy,
This was a bug. U_TAU on CFACEs was not being computed in DNS mode. Jason do an update and try again. Seems the U_TURB component of the deposition is one order of magnitude less than U_GRAV here?

About the funky outline behavior. The outline offset has a default value of 1. This is found in Dialogs -> View -> Examine Geometry -> Immersed -> parameters tab. If you set it to zero the outline sticks to the geometry. I think this is related to rendering. @gforney can give a bit more insight on this.

Also, if you want a BNDF of U_TAU in the geometry -> add line : &BNDF QUANTITY='FRICTION VELOCITY' / 

And you can try setting the cylinder with 1 line:
![Screen Shot 2020-08-03 at 9 41 33 PM](https://user-images.githubusercontent.com/7450069/89243569-4a9ef000-d5d2-11ea-9f67-eb4f3013cc27.png)

You can add MOVE_ID to it, etc.

Would be nice to have a soot mass balance on the problem. It's small so UGLMAT can be used to avoid penetration error. It can be used with 2 or 4 OMP threads for speedup.

**Comment by drjfloyd** [comment]
The commit fixes the issue of not having any turbulent deposition. I'll close this issue since there are other open issues already dealing with getting the correct U_TAU.

Using the cylinder keywords works as well.  It does a different triangulation of the end of the cylinder (not surprising) than one gets using poly.  Would this impact results or should it not matter?  

![NIST_SDG_geom_s0000](https://user-images.githubusercontent.com/12799217/89296768-cfb8f200-d630-11ea-86ed-e53ffb73ba38.png)
![NIST_SDG_geom2_s0000](https://user-images.githubusercontent.com/12799217/89296785-d5aed300-d630-11ea-88dc-425ec2442f0e.png)

**Comment by rmcdermo** [comment]
Regarding different triangulations of the surface, the results should be very similar.  What matters is how the near-surface cut cells (unstructured finite volumes) get defined.  These should be reasonably close to the same as long as the triangulation of the surface is accurate.  The flows will not be the same to machine precision, but I would expect differences to be second-order.

**Comment by marcosvanella** [comment]
In this particular case as the cylinder ends are located in domain boundaries (either no slip or mirror walls) no cut faces or cells will be defined there. I'd expect small differences to come from the cylindrical surface if different number of segments are used in the extrusion poly, for the reasons Randy stated.
If the ends are defined within the domain we would get different CFACEs (boundary cut-faces defined when intersecting the triangulation with the FDS mesh), which would get different interpolation stencils when sampling the flow to define U_TAU for example. So that will have a small effect also.
