### ISSUE TITLE
Low radiant fraction in UMD Line Burner cases with v6.7.5

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8703]
Both radiant fraction and suppression seem to have been affected in latest UMD line burner cases, even with temperature profiles looking ok.

FDS 6.7.4 validation guide:

<img width="788" alt="Screen Shot 2020-08-25 at 12 34 06 PM" src="https://user-images.githubusercontent.com/4418497/91205386-785bee00-e6d3-11ea-824d-260da97d05cf.png">

FDS 6.7.5 validation guide:

<img width="779" alt="Screen Shot 2020-08-25 at 12 34 28 PM" src="https://user-images.githubusercontent.com/4418497/91205403-814cbf80-e6d3-11ea-9c96-df377f061e5e.png">

**Comment by rmcdermo** [comment]
This is still an issue.  Below are the plots from last night's guide.  Why has radiation to targets decreased since 6.7.4?

<img width="732" alt="Screen Shot 2021-11-09 at 11 35 42 AM" src="https://user-images.githubusercontent.com/4418497/140965927-75fbc7d9-e127-42e8-ba00-a7ef3a6db22f.png">

**Comment by mcgratta** [comment]
I'll check the NIST Pool Fire cases. The CO/soot split in the first reaction probably changed based on comparison's with Ryan's pool fire measurements.

**Comment by mcgratta** [comment]
[NIST_Propane_34kW_Soot_CL.pdf](https://github.com/firemodels/fds/files/7507012/NIST_Propane_34kW_Soot_CL.pdf)
Notice that the soot concentration for the NIST Pool Fire propane case is also low. I'll run these cases with more C going to soot in the first step.

**Comment by rmcdermo** [comment]
Yep.  Good catch.

**Comment by rmcdermo** [comment]
![Screen Shot 2022-07-21 at 1 12 51 PM](https://user-images.githubusercontent.com/4418497/180273690-1896d2c1-4a87-4559-afed-d5e8fbd7c0bf.png)

Kevin,
Things look the same with UMD line burner as of 6.7.7.  Have you adjusted the C to CO ratio per your previous comment?  Then we can rerun the cases.  Thanks

**Comment by rmcdermo** [comment]
This seems to be tied to the C to CO fraction, which is still in development.  Currently, the resolved cases look reasonable and consistent with 6.7.7, so I'll close this.
