### ISSUE TITLE
Particle falling through floor with POROUS=.FALSE.

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8711]
Running a modified version of NIST_NRC_01.  A particle (in my case IP=9604) is falling from the nozzle and winds up with its last few z locations being:

12 cm
6 cm
just over 0 cm
-12 cm

This results in LP%ONE_D%KKG being to -2147483648 which causes this statement to fail near line 1484 of part
      IF ((IC_OLD==0 .OR. IC_NEW==0) .AND. CC_IBM_GASPHASE) THEN

The particle never has its IOR set to be on the floor and as a result keeps taking the path through MOVE_IN_GAS rather than MOVE_ON_SOLID

Note one change in the input from the repository version is the floor portion of the steel pan is now a VENT, but making this back to an OBST does not change the behavior.

[NIST_NRC_01.txt](https://github.com/firemodels/fds/files/5136920/NIST_NRC_01.txt)

**Comment by rmcdermo** [comment]
Did this work with a previous version, just to help start the bisect?

**Comment by drjfloyd** [comment]
With the release version of 6.7.4 it gives and access violation at a different point in time. Seems likely that is the same error.

**Comment by mcgratta** [comment]
When does the error occur?

**Comment by drjfloyd** [comment]
Just after time step 20 with current source

**Comment by mcgratta** [comment]
I think this sneaky little droplet just barely escaped the domain. I'll catch him.

**Comment by mcgratta** [comment]
The CFL criterion for sub-iteration of the time step of a single particle was 1. That's a bit too tight, and this particle was able to traverse the entire ghost cell without being caught. I changed the criterion to 0.95. That fixes my debug version, but my dv and release versions were not failing. Make sure this works for you.

**Comment by drjfloyd** [comment]
Compliled in dv mode.  It fails at near timestep 90. Particle 36190.  Same problem. z winds up at -11.9 cm and KKG goes to -2147483648. Should I just try cutting CFL a little more?

**Comment by mcgratta** [comment]
Yes, I found this as well in my debug run. It kept going and then failed in
exactly the same way. Yes, try 0.9. Perhaps the conditions at the start of
the time step are changed during the step. We might need a cushion.

>

**Comment by drjfloyd** [comment]
I set it to 0.9 and it is up to 600 time steps. I'll let it go a bit more before pushing up the change .

**Comment by rmcdermo** [comment]
Just so I understand, wouldn't this depend more on how many substep increments you take just as much as the CFL?  The dt to keep the particle above the floor depends on how close it is the floor and the particle velocity.  But the CFL is a cell size quantity.  Kevin, is the algorithm written up in the Tech Guide?  I did not see it on a quick scan.

**Comment by mcgratta** [comment]
The CFL determines how many substep increments to take. Thus, if the CFL is
1.2, you take two steps. Our original problem was that the CFL was 0.99 and
so only one step was taken, and the droplet was able to travel from just
above the floor to just below the ghost cell below the floor. If the
particle crosses completely across a ghost cell, we then get an
error trying to figure out what cell it is in.

I'll add this to the Tech Guide.

>

**Comment by rmcdermo** [comment]
OK, I see.  I thought the problem was simply that it went below the floor.  Passing all the way through the ghost cell based on CFL I get.  But, 0.95 should be plenty to deal with precision issues.  I don't see how 0.9 fixes this unless something else is at play.

**Comment by mcgratta** [comment]
We decide at the start of the time step how many sub-iterations to take.
This is based on the particle velocity at the start. There could be
acceleration that increases the speed. In Jason's case, he has a liquid
fuel nozzle that is spraying downward at 10 m/s at a height of about 0.5 m,
right at the start of the calc when the time step is relatively high.

>

**Comment by mcgratta** [comment]
Assuming 0.9 does the trick, I'll close.
