### ISSUE TITLE
Calculation does not converge

### ISSUE THREAD

**Issue by zhiliu90** [firemodels/fds#8729]
Hello experts,

I have a model with a steady HRR=280 MW. But the HRR output gradually surpasses 280 MW after around 300 s and the calculation becomes very slow.

Here is the fds file:
[test unconvergence.txt](https://github.com/firemodels/fds/files/5168729/test.unconvergence.txt)

Thank you so much for your time.

**Comment by mcgratta** [comment]
You do not link the HRRPUA with a RAMP. FDS is applying the full HRRPUA within one second.
