### ISSUE TITLE
Numerical instability of sealed cavities

### ISSUE THREAD

**Issue by zhiliu90** [firemodels/fds#8732]
Hello,

Sorry for the previous error that separated the HRRPUA curve with the fire source.

Please look at the file here. The HRR went higher and higher than the input curve after about 400 s.

[Unconvergence.txt](https://github.com/firemodels/fds/files/5180501/Unconvergence.txt)

![HRR](https://user-images.githubusercontent.com/48945640/92338338-57879580-f0e2-11ea-87be-f4d09beb21a7.jpg)

**Comment by mcgratta** [comment]
It is not clear whether the HRR will continue to increase. This might just
be an outlier. At the end of the simulation the area under both curves
should be the same.

>

**Comment by zhiliu90** [comment]
> It is not clear whether the HRR will continue to increase. This might just be an outlier. At the end of the simulation, the area under both curves should be the same.
> […](#)

Hello Dr. McGrattan,

Thank you for your reply. The model continues one day, whereas the HRR is greater and the step becomes zero.  Please refer to the excel files from FDS.

Thank you.
[hrr.xlsx](https://github.com/firemodels/fds/files/5185513/hrr.xlsx)
[steps.xlsx](https://github.com/firemodels/fds/files/5185514/steps.xlsx)

**Comment by mcgratta** [comment]
Run the case at lower resolution and report if there is still a problem. The MLR_FUEL in the _hrr.csv indicates that the fuel generation rate is constant.

**Comment by zhiliu90** [comment]
McGrattan,

More information: That model stops with an error of "Numerical Instability".

I also need to make sure, you want **LARGER** grid sizes to run?

**Comment by mcgratta** [comment]
No, I am suggesting two things:

1. Upgrade to the latest version of FDS
2. Run your case with half the resolution. That is, make all the mesh
dimensions one half of their original value. This will allow the case to
run much faster, and you can check the HRR and other things.

After doing both of these things, if you still have a numerical
instability, with the latest release, post the input file here.

>

**Comment by zhiliu90** [comment]
McGrattan,

I tested various sizes from 15 cm to 50 cm. All of them got numerical instability. But the 60-cm size model looks good.

How to deal with my model? Large cell sizes cause bad discretization.

**Comment by mcgratta** [comment]
If you are using the latest version of FDS, post the input file that fails
with the instability in the shortest amount of time.

>

**Comment by zhiliu90** [comment]
This attached model cost no more than 1 day on my PC with 6-core 3.2 GHz, until its instability at the simulation time of about 70 s.

Also, the 60-cm model might be unstable because its time step has reduced to 0.07 s. But the combustion went to 2800 s, which is enough for FE simulation if the FDS results are reliable.

[Seg20by2_Cell50.txt](https://github.com/firemodels/fds/files/5205417/Seg20by2_Cell50.txt)

**Comment by zhiliu90** [comment]
Yes. I'm using the version 6.7.5 released on Aug 20.

**Comment by mcgratta** [comment]
I am running the case now.

>

**Comment by mcgratta** [comment]
It appears that you have sealed cavities within the large solid obstruction over the fire. If so, you need to declare a pressure ZONE for each cavity, like this
```
&ZONE XYZ=... /
```
where XYZ are the coordinates of a point within the cavity.

**Comment by zhiliu90** [comment]
Dear Dr. McGrattan,

There are lots of narrow sealed cavities in my model. The OBSTs are transformed from CAD and PyroSim. For large cavities, it's possible to do that. But for small cavities, I can only identify the coordinates of ZONE POINTS in the geometric domains before the transformation, instead of that after transformation. Do I need to assign ZONEs for all cavities or just large cavities?

Thanks.

**Comment by mcgratta** [comment]
All cavities, or risk numerical instability. FDS needs to know that there
are sealed pockets which heat can penetrate but air cannot. As a sealed
cavity heats up, the air inside expands. FDS needs to track this pressure
rise separately from the other parts of the domain.

>

**Comment by zhiliu90** [comment]
In the real structure, all cavities are not sealed completely and have small holes. But in FDS, these holes are too small to consider so that the OBSTs compose sealed cavities. How to deal with this situation?

**Comment by mcgratta** [comment]
At some point, we might consider automating the process of specifying
ZONEs, but for the moment, it must be done manually or you risk numerical
instability.

>

**Comment by drjfloyd** [comment]
Have Pyrosim automatically thicken the obstructions. I have found that the use of thin obstructions everywhere tends to increase the risk of instabilities since you wind up with lots of small cavities everywhere. A little bit of velocity error through a thin obstruction can induce spurious flow in the cavity that can lead to an instability.

**Comment by mcgratta** [comment]
If you do not care about the interior cavities, block them with
obstructions.

>

**Comment by zhiliu90** [comment]
> Have Pyrosim automatically thicken the obstructions. I have found that the use of thin obstructions everywhere tends to increase the risk of instabilities since you wind up with lots of small cavities everywhere. A little bit of velocity error through a thin obstruction can induce spurious flow in the cavity that can lead to an instability.

Hi Dr. Jason,

Thanks for your attention. Can Pyrosim thicken OBSTs? Could you please give me more details? Thank you.

**Comment by rmcdermo** [comment]
Surely it can.  You simply add THICKEN=T to an OBST line.  It is probably a checkbox in Pyrosim.

**Comment by zhiliu90** [comment]
> At some point, we might consider automating the process of specifying ZONEs, but for the moment, it must be done manually or you risk numerical instability.
> […](#)

Dr. McGrattan,

What I understand from the manual is the ZONE line is to identify the sealed cavities. The structure I am modeling does have cavities, but not completely sealed. Many holes exist for ventilation. But they are not modeled in FDS.

**Comment by rmcdermo** [comment]
See FDS User Guide 12.3.2 Leaks.

**Comment by zhiliu90** [comment]
Dear experts,

The structure is a steel beam and its section is shown below. It has main plates (the outermost long lines) and stiffeners (inner short lines). I tried the following models to 3600 s with time_shrink_factor=10. They have a same 50-cm cell that got instabilities in the 1st model.

1. Real material & sealed thin-walled geometry (small holes are neglected). INSTABILITY.
2. Real material & solid geometry. OK.
3. Real material & sealed thin-walled geometry (small holes are neglected) without stiffeners. OK.
4. INERT material & sealed thin-walled geometry (small holes are neglected). OK.
5. Real material & sealed thicken OBSTS (are obtained by calculating the maximum and minimum coordinates of each area). Under running.

I read the LEAK group and it has many parameters that are too difficult for me at present. Could you please show me example lines having these functions? Also, should I try the HOLE?

Thank you.


![image](https://user-images.githubusercontent.com/48945640/93472809-c4dbc780-f927-11ea-9821-402291dc7076.png)

**Comment by mcgratta** [comment]
This picture indicates that there are three cavities within this
obstruction. If this is the case, have you added a line like this

&ZONE XYZ=... /

for each cavity, where XYZ is a point within the cavity?

>

**Comment by zhiliu90** [comment]
Dr. McGrattan,

These model did not include ZONE because much more than 3 cavities exist due to many diaphragms.

This picture does not show the small holes that used for ventilation. Actually numerous holes exist in it. Does the ZONE group means the cavity pressure than can be elevated?

**Comment by zhiliu90** [comment]
Dear experts,

The structure has many holes that used for ventilation.

**Comment by mcgratta** [comment]
If a sealed cavity heats up, the air inside expands, but unless FDS is told
that this is a sealed cavity, it will use the same background pressure for
the cavity that it uses for the ambient. This causes air to penetrate the
solid wall, which eventually leads to instability.

>

**Comment by mcgratta** [comment]
I believe that I have fixed this problem, and I ran your case to completion. What operating system are you using?

**Comment by zhiliu90** [comment]
Dr. McGrattan,

The system I am using is windows 10 LTSC.

**Comment by mcgratta** [comment]
Install the test version of FDS located at the link at the top of this page:
[https://github.com/firemodels/fds/wiki/FDS-Release-Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes)
Let me know if this fixes the instability problem.

**Comment by zhiliu90** [comment]
Dear Dr. McGrattan,

Thank you for the revision. I will try it ASAP. Would you please make a short explanation on which aspect caused the instability? I have some other models with this scale. Thank you.

**Comment by mcgratta** [comment]
As we discussed, each sealed cavity should have a pressure ZONE specified.
I changed the code so that FDS now automatically defines the ZONEs.

>

**Comment by zhiliu90** [comment]
Dear Dr. McGrattan,

I am not sure I got the correct process.  I installed the "FDS6.7.5-134_SMV6.7.15-58_tst_win" at the drive folder.

I tried a model  I got instability before using the new version, and it ran to the end.

As I have other similar models, I will let you know if I got same problems. By the way, I changed the issue name that might be easier to query.

GREAT THANKS.

**Comment by mcgratta** [comment]
You should see a newer date of compilation when you run FDS with the new version. In any case, good to hear things are working now. I will close this issue, but if there are further problems, start a new issue.
