### ISSUE TITLE
Drops on solids at mesh boundaries

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#8743]
Drops are not properly crossing mesh boundaries while on a solid. The attached case has two domains each with two meshes. Both have a nozzle pointing down at an OBST that crosses the two meshes. In one case the OBST is thin, and the other it is one grid cell thick.  In the thin case when particles reach the MESH edge they fall through the OBST. In the thick case when particles reach the MESH edge they drop slightly inside the OBST but then get culled and don't fall through.

![spray_leak_0034](https://user-images.githubusercontent.com/12799217/93121681-3cdd8f80-f693-11ea-92cb-c5441655588e.png)
[spray_leak.txt](https://github.com/firemodels/fds/files/5220155/spray_leak.txt)

**Comment by mcgratta** [comment]
Should be fixed. We must have messed up the logic when we were sorting out issues with the new GEOM stuff.

**Comment by drjfloyd** [comment]
fix verified.
