### ISSUE TITLE
Numerical instabillity

### ISSUE THREAD

**Issue by MRK-H** [firemodels/fds#8746]
Hello,
this is my first time using fds and I'm trying to simulate a room fire. First everything looks fine but after some time when the fire began to spread I get an error message about a numerical instabillity and the simulation interrupts. I've tried several things/ looked up in the forum but found no solution. It would be great if anyone can help me. 
Attached my code.

Regards

[HansWerner_A_02.txt](https://github.com/firemodels/fds/files/5224373/HansWerner_A_02.txt)

**Comment by mcgratta** [comment]
What version of FDS are you using, and when does the instability occur?

**Comment by MRK-H** [comment]
Version 6.7.4 and it occurs after 643.43s short after the fire begin to spread to the other furniture.

Thank you for your quick response.

**Comment by mcgratta** [comment]
OK, I'm running the case. In the meantime, look at the Plot3D file and see
where the velocity vectors appear to be very large. When you load the
Plot3D file, hit "v"

>

**Comment by MRK-H** [comment]
Ok, thank you. 

This is a screenshot. It looks like this corner of the wall cupboard is the problem. 

![github](https://user-images.githubusercontent.com/71322387/93213301-f310aa00-f763-11ea-9a8f-bc73f845ffed.PNG)

**Comment by mcgratta** [comment]
Are their regions within the domain that are completely sealed? That is, volumes that are surrounded on all sides by obstructions? If so, you need to add a pressure ZONE for each sealed region. For example, if the cabinet has an empty cavity inside, add
```
&ZONE XYZ=... /
```
where `XYZ` is a point inside the cavity. This line tells FDS to treat the pressure build-up within this cavity separately from the pressure build-up elsewhere.

**Comment by MRK-H** [comment]
Ah ok, I'll try that in the meanwhile...

**Comment by mcgratta** [comment]
I also get the numerical instability with the latest working code. Try adding the ZONE lines and let me know if that solves the problem.

**Comment by MRK-H** [comment]
The first run didn't work. I'll try a little change in my model and let you know if my problem is solved. 
But I've a question concerning the &ZONE. What happens if e.g. the front of the cabinet burns away? Then the Volume inside isn't sealed anymore. Does FDS recognises this or what happens to the &ZONE command?

**Comment by mcgratta** [comment]
The ZONEs merge when the wall breaches. What do you mean that the "first
run didn't work"? Does this mean that you added ZONEs and still have an
instability?

>

**Comment by MRK-H** [comment]
Ah ok. Yes the instability occurs at the same location.

**Comment by mcgratta** [comment]
Do you have a more coarse version of this case that fails more quickly.
It's hard to debug when it takes so long to fail.

>

**Comment by MRK-H** [comment]
Unfortunately no, I've testet everything in smaller scaled models without any problems. This case of numerical instability occurs only in this greater model. I'm now running a version where the cabinets where the instabilities occurs are open. The interim results are looking promising.

**Comment by drjfloyd** [comment]
This case appears to use the properties from the pyro3d_wood_char verification case (A=1E20 and E=165000). At 200 C (threshold for wood ignition) we have a reaction rate of 1E20 x exp (-165000/(8.314 * 473)) = 60. Are these fictitious properties?  This could be the issue if we get some location where burning rates spike to a non-physical value.

**Comment by rmcdermo** [comment]
Looks like I pulled those properties from the 'PINE' of `surf_mass_vent_char_cart_fuel.fds`

**Comment by MRK-H** [comment]
Yes I've found several examples in the fds example folder with this values for A and E. Because I've no own experimental data I've assumed them for now.

**Comment by mcgratta** [comment]
I suggest that before doing an entire room fire scenario, just simulate a
single item burning. You can find some typical heat release curves for
various types of furnishings in the SFPE Handbook, Babrauskas chapter.

>

**Comment by mcgratta** [comment]
BTW, the parameters you find in the Verification input files are not to be
trusted. These are typically just made up to test a feature of the code.

>
