### ISSUE TITLE
Possible OpenMP Memory Allocation Issue

### ISSUE THREAD

**Issue by nmthastings** [firemodels/fds#8748]
This is a bit of a strange crashing issue. I am a Support Engineer at Thunderhead Engineering and this came up when troubleshooting a customer's model. I've attached the PyroSim model and the FDS input file in a zip file.

[Fire_Model.zip](https://github.com/firemodels/fds/files/5234743/Fire_Model.zip)

When trying to run this model, we encounter an Access Violation in the FDS process (screenshot below). We can get around this by deleting Mesh number 3, or by moving point number 2 of the present Beam detector to  x85.5 y-28.5 z4.75. With either or both of those changes, the model runs just fine. We also heard from our customer that by refining the mesh, they were able to run the full model as they had it originally set up.

![Capture](https://user-images.githubusercontent.com/58537830/93388802-3e48bc80-f839-11ea-81e9-eda9951fa2f8.PNG)

There doesn't seem to be anything blatantly wrong with the model, certainly nothing that seems like it would be causing this issue. It seems like this may be an issue with the openMP memory allocation process, leading to the access violation.

**Comment by mcgratta** [comment]
I wouldn't assume an OpenMP problem, but rather MPI. I'll take a look.

**Comment by mcgratta** [comment]
Runs for me with the latest source. What version of FDS are you running?

**Comment by rmcdermo** [comment]
I confirm, this input file runs with latest test bundle found from the link in the [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes).  Please make sure that all the Thunderhead support engineers are aware of these compiled bundles.  Thanks

**Comment by nmthastings** [comment]
We're running 6.7.4. We just tried it again and now we're seeing it fail to run through the PyroSim interface, but run fine from CLI. I'll close this and take it up as an internal bug. Thanks for the help!

**Comment by drjfloyd** [comment]
@mmhastings
As a note for future reference, a way to test for issues with Open MP is to set OMP_NUM_THREADS=1. If the jobs runs with one thread and dies with mulitple threads, then that suggests an Open MP issue.
