### ISSUE TITLE
Instability with GLMAT and CYLINDRICAL

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8759]
The attached case gets going with the FFT solver, but crashes immediately with both GLMAT and UGLMAT.

@marcosvanella Can you take a look and just make sure things are correctly hooked up for GLMAT with CYLINDRICAL?  Thanks

[test.fds.txt](https://github.com/firemodels/fds/files/5257700/test.fds.txt)

**Comment by marcosvanella** [comment]
Randy, I'll take a look.

**Comment by marcosvanella** [comment]
@rmcdermo do an update and try it now. You want UGLMAT to get rid of velocity errors in the asymmetric obstacle. Also you probably want to run this OMP threaded for speed.

**Comment by rmcdermo** [comment]
Marcos,

The case is running.  But when I add
```
&PRES SOLVER='UGLMAT', CHECK_POISSON=T/
```
I am seeing Poisson errors in the 1e6 range.  I don't think this has anything to do with the pressure iterations... it should just be testing whether you are solving the specified Poisson equation in cylindrical coordinates correctly.  Please check.  Here is the input file again.

[test.fds.txt](https://github.com/firemodels/fds/files/5279329/test.fds.txt)

**Comment by marcosvanella** [comment]
We have to set the gradients of H to zero in the obsts wall cells when computing the residual. I'll work on that.

**Comment by marcosvanella** [comment]
@rmcdermo do an update and try the case now. Thanks.

**Comment by rmcdermo** [comment]
Works great. Thanks!
