### ISSUE TITLE
Strange solid particle behavior at centerline of CYLINDRICAL flow

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8761]
This is a case I'm working that is looking at using sodium bicarbonate for fire suppression.  So, this is a bit new in terms of using solid particles for suppression where we would normally use the droplet model.  Nevertheless, there seems to be some behavior at the centerline that does not look right.  At about 1.69 s in the simulation, you see the particles on the centerline look like they start falling due to gravity and create a backflow that leads to unstable behavior.  The simulations keeps going, but something is not right.

There also seems to be problems whenever the particles get close to the centerline downstream of the burner.  In this particular case, it is hard to tell if the explosions are the result of problems upstream.  But other variants of this case where the upstream looks ok produce spurious issues downstream, again, whenever the particle gets close to the centerline.

I tried taking CYLINDRICAL out of play, but the OPEN bc does not act correctly for 2D calculations (this is another issue that has never really been solved).

Anyway, at this point, I'm fishing for some suggestions.  I think this is a flow we should be able to count on working without too much fuss.

[test.fds.txt](https://github.com/firemodels/fds/files/5258113/test.fds.txt)

**Comment by rmcdermo** [comment]
Here is an image from a bit later in the sim where things are getting worse.

<img width="752" alt="Screen Shot 2020-09-21 at 5 08 35 PM" src="https://user-images.githubusercontent.com/4418497/93890553-74ae8d80-fcb8-11ea-962a-650c9630ab63.png">

**Comment by mcgratta** [comment]
Yes, I see the problem. Working it.

>

**Comment by mcgratta** [comment]
I don't think this is a CYLINDRICAL problem per se. Consider this simple 2d case, no reactions, MIRROR boundaries. Very simple. The particles fall back against the flow, but I don't have a sense of whether in this case with the particles so small we should expect this.
```
&HEAD CHID='test2'/

&MESH XB=0.00,0.060,0.0,0.001,0.06,0.15, IJK=30,1,45 /

&TIME T_END=10.0 /

&SURF ID='inlet',
      VEL=-0.1,
      TAU_V=0.
      PART_ID='KSA'
      PARTICLE_MASS_FLUX = 0.005 /

&VENT SURF_ID='OPEN', DB='ZMAX'/
&VENT SURF_ID='inlet', DB='ZMIN'/
&VENT SURF_ID='MIRROR', DB='XMAX'/
&VENT SURF_ID='MIRROR', DB='XMIN'/

&MATL ID               = 'Sodium Bicarbonate'
      FYI              = 'NaHCO3'
      DENSITY          = 2200.
      CONDUCTIVITY     = 0.20
      SPECIFIC_HEAT    = 1.4 /

&SURF ID='KSA'
      HEAT_TRANSFER_COEFFICIENT=50
      MATL_ID = 'Sodium Bicarbonate'
      THICKNESS=2e-06
      GEOMETRY='SPHERICAL' /

&PART ID='KSA'
      SURF_ID='KSA'
      COLOR='BLUE'
      SAMPLING_FACTOR=1
      DRAG_LAW ='SPHERE'
      MINIMUM_DIAMETER=1
      QUANTITIES='PARTICLE TEMPERATURE','PARTICLE VELOCITY','PARTICLE DIAMETER','PARTICLE MASS','PARTICLE WEIGHTING FACTOR' /

&SLCF PBY=0.0005,QUANTITY='TEMPERATURE', CELL_CENTERED=T /
&SLCF PBY=0.0005,QUANTITY='VELOCITY', VECTOR=.TRUE. /

&TAIL /
```

**Comment by mcgratta** [comment]
Also, the Re number for these particles is about 0.02, thus the drag coefficient is 24/Re or about 1200. I don't know if the drag law is appropriate for such low Re, and then there is the fact that the particles are clustered. Each particle in the simulation represents about 1300 actual particles.

**Comment by drjfloyd** [comment]
24/Re is Stokes flow drag, it should be appropriate.

**Comment by mcgratta** [comment]
Right, when the sphere is isolated. In our case, we have a cloud of spheres.

>

**Comment by drjfloyd** [comment]
With 0.002 m grid spacing the ratio of cell volume to the volume of 1,300 particles is ~200,000.  That gives about 50 diameters between particles on average. I don't think we would expect much particle-particle interaction.

**Comment by mcgratta** [comment]
Right, so another question is the 0.02 kg/m2/s mass flux of particles. This is about 1/6 the mass flux of air that is injected with the particles (1.2 kg/m3 x 0.1 m/s = 0.12 kg/m2/s). I'm wondering if we're violating some assumption about particles taking up no volume or something similar?

**Comment by drjfloyd** [comment]
The particles are 2000 times more dense than air.  1/6 mass flux will be ~1/12,000 volume flux.

**Comment by rmcdermo** [comment]
For the test2 case, if I set NPPC=10, the instability is much delayed, but eventually does happen after 5 seconds.  With NPPC=20, the instability is pushed out to about 9 s.

I think that with NPPC=1, you easily end up with cells that do not have particles, and this would not happen in reality.  The variation in f_b then creates a velocity fluctuation (one cell with a downward force next to a cell without one creates vorticity) that leads to spurious turbulence in the numerical solution.

Something I have been thinking we will need for embers anyway is to add a random walk based on the local fluid eddy viscosity.  Particles should experience a subgrid force due to unresolved eddies.  This randomizes the position and minimizes the chances of these "channels" forming.  This would then minimize the required NPPC, which is a net speed up.  The random walk is very cheap.

**Comment by mcgratta** [comment]
Hmm -- seemed like there were enough particles. Are you setting
SAMPLING_FACTOR=1 on the PART line?

>

**Comment by rmcdermo** [comment]
I keep SAMPLING_FACTOR=NPPC, so as not to slow SMV.

**Comment by mcgratta** [comment]
Also, another thing to do is set DT_INSERT to a value less than the default
0.01 s on the SURF line. If set low enough, you get particles every time
step. So a mix of NPPC and DT_INSERT should help populate the domain
reasonably well.

>

**Comment by rmcdermo** [comment]
With DT_INSERT=0.005 and NPPC=10 (SAMPLING_FACTOR=100), things look reasonable.

**Comment by mcgratta** [comment]
The number of particles per grid cell will be approximately

DZ*NPPC/(W0*DT_INSERT) = 0.002 m x 10 / (0.1 m/s x 0.005 s) = 40

Your original case had 2 particles per cell, if my math is right.

**Comment by rmcdermo** [comment]
Kevin,
We are not out of the woods.  Take a look at this case (just unzip and run SMV, look at particles and velocity vectors).  It is the original cylindrical test, but now with a few more particles.  I have also added an OBST for the pedestal of the cup, so it takes the centerline issue out of play.  As the particles get very close to the wall, their upward drag is reduced and then eventually settle back toward the inlet.  Once they are falling back through the inlet, things go haywire.  Not sure if there is something we need to do in terms of removing these particles before they cause this havoc.  Thoughts?

[test_save.zip](https://github.com/firemodels/fds/files/5278774/test_save.zip)

**Comment by mcgratta** [comment]
Set SAMPLING_FACTOR=1 and you'll see a distinct problem near the wall,
something that appears to be an interpolation thing. I'll dig in moire.

>

**Comment by mcgratta** [comment]
I understand what is happening at the wall. When a particle is within one
half a grid cell to the vertical wall, it takes the gas phase value of w
instead of interpolating the gas and ghost cell value of w. Thus, we don't
see particles "sticking" to the wall. That being said, there seems to be a
build up of particles within the "boundary layer" which eventually causes
trouble. Not sure why.

>

**Comment by rmcdermo** [comment]
Things are looking pretty good so far using the UGLMAT pressure solver Marcos just pushed up (I am assuming the Poisson errors might be a diagnostic mistake due to the unstructured grid).

**Comment by rmcdermo** [comment]
Doh!  Spoke too soon.

<img width="752" alt="Screen Shot 2020-09-24 at 5 43 21 PM" src="https://user-images.githubusercontent.com/4418497/94203454-71b8c600-fe8d-11ea-8b09-aaa81101c9cc.png">

**Comment by mcgratta** [comment]
I don't think this has to do with the pressure solver. It's something about
the momentum transfer from particles to gas, which is tied in with the ODE
solver for particles.

>

**Comment by rmcdermo** [comment]
My hunch was that any velocity penetration error could be pushing the particles too close to the boundary, or something along those lines.

**Comment by mcgratta** [comment]
Add these lines to your case
```
&SLCF PBY=0.0005,QUANTITY='H', CELL_CENTERED=T /
&SLCF PBY=0.0005,QUANTITY='F_X' /
&SLCF PBY=0.0005,QUANTITY='F_Y' /
&SLCF PBY=0.0005,QUANTITY='F_Z' /
```
At the boundary, these acceleration terms fluctuate due to the fluctuation of H in the solid. I have to check when the particle acceleration (ACCEL_X, etc) is added. This might be a bad feedback loop.

**Comment by mcgratta** [comment]
I checked and made sure that FVX and FVZ at solid boundaries do not have contributions from ACCEL_X, ACCEL_Z. Still, things seem  awfully noisy near these boundaries.

**Comment by mcgratta** [comment]
If you load and view alot of particles, it appears that the instability originates at the separation point of a counter-clockwise vortex that forms in the corner below the burner. I suspect that the del dot F term in the Poisson equation gets very large or small due to the clustering of particles there.

**Comment by rmcdermo** [comment]
Something really seems off with the particle transport.  While investigating another issue, I set up this very simple case.  It should just blow neutrally buoyant particles (DENSITY=1.2 kg/m3) up and out of the domain.  But the case fails almost immediately, just a few time steps, with an instability.

In this case, I would expect everything to be isothermal, but the divergence goes off the rails.  Not sure if that is the chicken or the egg.

```
&HEAD CHID='test'/

&MESH IJK=10,10,10, XB=0,1,0,1,0,1/

&TIME T_END=10/

&MISC PARTICLE_CFL=T, PARTICLE_CFL_MAX=0.5/

&SURF ID='inlet'
      COLOR='RED'
      VEL=-0.1
      PART_ID='spheres'
      PARTICLE_MASS_FLUX=0.02
      NPPC=1
      DT_INSERT=0.01/

&PART ID='spheres', SURF_ID='part surf',
      QUANTITIES='PARTICLE VELOCITY','PARTICLE DIAMETER','PARTICLE WEIGHTING FACTOR'
      SAMPLING_FACTOR=1/
&SURF ID='part surf', RADIUS=2.e-6, GEOMETRY='SPHERICAL', MATL_ID='stuff' /
&MATL ID='stuff',
      DENSITY       = 1.2
      CONDUCTIVITY  = 0.20
      SPECIFIC_HEAT = 1.4/

&VENT DB='ZMIN', SURF_ID='inlet'/
&VENT DB='ZMAX', SURF_ID='OPEN'/

&SLCF PBY=0.5, QUANTITY='VELOCITY', VECTOR=T/
&SLCF PBY=0.5, QUANTITY='TEMPERATURE', CELL_CENTERED=T/
&SLCF PBY=0.5, QUANTITY='DIVERGENCE', CELL_CENTERED=T/

&TAIL/
```

**Comment by drjfloyd** [comment]
We don't have a buoyancy term for particles.  The particles start falling down and it looks like the divergence issue is happening when a lot of particles collect on the air inlet. Is this just an issue with drag?

**Comment by rmcdermo** [comment]
I understand about the buoyancy---I was just trying to make a particle that would more or less act like a tracer.  I agree, something is odd with particles falling a backward at the inlet.  The input parameters here are pretty close to that of `particle_flux.fds` in the verification suite, but there we just push the particles out of a vertical surface and they fall to the ground.

This is interesting... I change the input file as follows:
```
&SURF ID='inlet'
      COLOR='RED'
      VEL=-5
      PART_ID='spheres'
      PARTICLE_MASS_FLUX=0.02
      RAMP_PART='ramp pmf'
      NPPC=1
      DT_INSERT=0.01/

&RAMP ID='ramp pmf', T=0, F=0/
&RAMP ID='ramp pmf', T=5, F=0/
&RAMP ID='ramp pmf', T=10, F=1/
```

Now if you run this case, all is fine for the first 5 sec and Smokeview shows particles being injected, albeit without much randomness.  At 5 sec, when the ramp kicks in, the particles look more random, then the instability occurs.

**Comment by mcgratta** [comment]
Yes, I think this is all about drag. One way to look at it is this -- add
solid particles to a single grid cell and blow on it. At first, you expect
to see a bit of a flow diversion. Add more particles, and you see more.
Eventually, the flow goes unstable. We're just adding momentum without
accounting for wake reduction etc.

>

**Comment by rmcdermo** [comment]
But at a minimum, something is wrong with the RAMP.  There should be no particle mass flux for the first 5 sec.

**Comment by drjfloyd** [comment]
With a particle density of 1.2 kg/m3, a radius of 2 microns, and a flux of 0.02 kg/m2/s you are injecting a projected area of particles of 15,000 m2 each second in a domain that is 1 m2. 

The ramp may just be setting the particle weight to 0.

**Comment by rmcdermo** [comment]
Yes, that is exactly what is happening.  You can see it in Smokeview.  Is this the behavior we want?  I would think that if PWT<TWO_EPSILON_EB, we should not inject the particle.

**Comment by drjfloyd** [comment]
We should not inject particles if the flux is zero.

**Comment by mcgratta** [comment]
I'll fix that.

**Comment by mcgratta** [comment]
I added `T_INSERT` to the `SURF` line parameters to enable one to insert particles starting at a particular time. This same functionality exists for particles introduced within a volume on the `INIT` line. Otherwise, if a ramp is used to control the particle mass per unit time per unit area (`PARTICLE_MASS_FLUX`), and the ramp is zero, the code still works and the particles are massless, essentially. It's a bit tricky to remove the particles entirely if the mass ramp is zero, since the particles have already been initialized by the time the ramp is evaluated. I'd rather just leave things as is, and use `T_INSERT` to delay insertion.

Returning to the issue at hand, these examples fail because the particles create too much drag on the air because we are not currently using any kind of drag reduction algorithm. There is one in the code that was designed for droplets, but we haven't had much experience with it. I'm going to see if we can use a calculated packing ratio to determine if too many particles are being inserted.

**Comment by mcgratta** [comment]
Run this case with a variety of DT from 0.005 to 0.05. I understand why there is a time dependence, but this is really severe and it's complicating this case alot
```
&HEAD CHID='part2'/
&MESH IJK=10,10,10, XB=0,1,0,1,0,1/
&TIME T_END=10, DT=0.05 /
&SURF ID='inlet', COLOR='RED', VEL=-0.1 /
&INIT XB=0.4,0.6,0.4,0.6,0.6,0.7, N_PARTICLES_PER_CELL=1, T_INSERT=3., PART_ID='spheres' /
&PART ID='spheres', SURF_ID='part surf', DRAG_LAW='SPHERE'
      QUANTITIES='PARTICLE VELOCITY','PARTICLE DIAMETER','PARTICLE WEIGHTING FACTOR'
      SAMPLING_FACTOR=1/
&SURF ID='part surf', THICKNESS=2.e-6, GEOMETRY='SPHERICAL', MATL_ID='stuff' /
&MATL ID='stuff', DENSITY=1.2, CONDUCTIVITY=0.20, SPECIFIC_HEAT=1.4 /
&VENT DB='ZMIN', SURF_ID='inlet'/
&VENT DB='ZMAX', SURF_ID='OPEN'/
&SLCF PBY=0.5, QUANTITY='VELOCITY', VECTOR=T/
&TAIL/
```

**Comment by mcgratta** [comment]
`SECOND_ORDER_PARTICLE_TRANSPORT` does not change things.

**Comment by rmcdermo** [comment]
Wow.  It flips sign!  Interesting find.  That does not seem right.

**Comment by mcgratta** [comment]
I'm going to dig into this. Could be that with particles so small, the approximations and truncations of the derivation are not appropriate. Perhaps there is some expression we can use to choose the sub-time step based on the particle diameter, density and relative velocity.

**Comment by rmcdermo** [comment]
This looks to me like we have some kind of time splitting bug.  We should be able to tell right away, by comparing the vertical component of the drag force and the gravity force, whether a particle should move up or down.  We might have to treat these two situations differently.  A truly explicit scheme should not care about the order.  But we sometimes update variables and then use them again in the routine.

**Comment by mcgratta** [comment]
In this case, the particle velocity is more or less the upward flow, w_gas=0.1 m/s. The z particle position more or less is governed by

z_new = z_old + w_gas\*dt_p - 0.5\*g\*dt_p^2

If dt_p>0.01 s, z_new is less than z_old. That is why DT=0.05 has the particles falling and DT=0.005 has them rising.

**Comment by rmcdermo** [comment]
But... particles should not have a gravity term in the position equation.  The position evolves by

dx/dt = u_p

The velocity evolves by

du_p/dt = sum of forces (gravity goes here).  If done this way, the force balance will always point the particle in the right direction, regardless of time stop (I think).

**Comment by mcgratta** [comment]
See the notes. This is not how it's done.

**Comment by rmcdermo** [comment]
I understand.  Blame me if you want.  I'm just suggesting an approach to try to fix the current issue, which was not realized at the time of the fancy derivation.  If we break the 2nd order convergence of the flat fire case, but make the code more stable, that would be fine.

**Comment by rmcdermo** [comment]
Also, at the time those derivations were done, we were not doing the substepping (as I recall).  It is quite possible that the substepping resolves the need for the higher order temporal scheme and the verification cases will all work reasonably well.

**Comment by mcgratta** [comment]
I implemented the old routine we used to use, where we linearize the equation for the particle velocity. The results of the flat fire and terminal velocity cases is below. Note that there is no second order option with this scheme as yet, so both the first and second order cases are the same. The terminal velocity does not "converge" because it is more or less exact by construction. The terminal velocity position is first order because the scheme is at present first order.

[position_convergence.pdf](https://github.com/firemodels/fds/files/5381369/position_convergence.pdf)
[terminal_velocity_convergence.pdf](https://github.com/firemodels/fds/files/5381372/terminal_velocity_convergence.pdf)
[flat_fire_trajectory.pdf](https://github.com/firemodels/fds/files/5381378/flat_fire_trajectory.pdf)
[flat_fire_u.pdf](https://github.com/firemodels/fds/files/5381380/flat_fire_u.pdf)
[flat_fire_w.pdf](https://github.com/firemodels/fds/files/5381381/flat_fire_w.pdf)
[flat_fire_x.pdf](https://github.com/firemodels/fds/files/5381382/flat_fire_x.pdf)
[flat_fire_z.pdf](https://github.com/firemodels/fds/files/5381383/flat_fire_z.pdf)

**Comment by rmcdermo** [comment]
Here are the current flat fire results.  Is there a way through the LES time step or particle sub time step to get this kind of accuracy?  Just curious.

<img width="624" alt="Screen Shot 2020-10-15 at 9 27 36 AM" src="https://user-images.githubusercontent.com/4418497/96133998-1ba5d400-0ec9-11eb-8d4a-16df262fed8d.png">

**Comment by mcgratta** [comment]
I'm looking into it.

**Comment by mcgratta** [comment]
I made a slight adjustment. When we compute an approximate solution of the trajectory equation, we get something like this in the dragless case:

w(t) = w(0) - g\*t

What I was doing was this

z_new = z_old + dt\*w(t)

But what I should have done is 

z_new = z_old + dt\*(w(t)+w(0))/2

That improves things almost to the point where we were before, but with much less baggage:

[position_convergence.pdf](https://github.com/firemodels/fds/files/5385640/position_convergence.pdf)
[flat_fire_trajectory.pdf](https://github.com/firemodels/fds/files/5385643/flat_fire_trajectory.pdf)
[flat_fire_u.pdf](https://github.com/firemodels/fds/files/5385644/flat_fire_u.pdf)
[flat_fire_w.pdf](https://github.com/firemodels/fds/files/5385645/flat_fire_w.pdf)
[flat_fire_x.pdf](https://github.com/firemodels/fds/files/5385646/flat_fire_x.pdf)
[flat_fire_z.pdf](https://github.com/firemodels/fds/files/5385647/flat_fire_z.pdf)

**Comment by rmcdermo** [comment]
Looks good!

**Comment by mcgratta** [comment]
I'm going to write this up and we can look it over before committing. We
can also try your case again to see if things improve. There is still the
issue of having too many particles dragging too much gas, but that was an
issue with the current formulation. We've yet to consider the effect of
drag reduction for clouds of particles.

>

**Comment by mcgratta** [comment]
[Pages from FDS_Technical_Reference_Guide.pdf](https://github.com/firemodels/fds/files/5386264/Pages.from.FDS_Technical_Reference_Guide.pdf)

**Comment by rmcdermo** [comment]
Looks good.  I'd like to try it out.  I'm working on cup burner validation with mist and power.  Thanks

**Comment by mcgratta** [comment]
Do you a sample case I could try before committing everything?

**Comment by rmcdermo** [comment]
Try the test case at the very top of this thread.

**Comment by mcgratta** [comment]
That case is going to fail no matter what trajectory scheme we use. Here's why. For a collection of particles, the "absorption coefficient" kappa is

kappa = C_s \* sigma \* beta

C_s is the shape factor (projected area divided by surface area) which for a sphere is 1/4

sigma is the surface area to volume ratio, which for a sphere is 3/r

beta is the packing ratio, which in your case is mdot''/w/rho_p = 0.02 kg/m2/s  /  0.1 m/s  /  1.2 kg/m3 = 1/6  1/m

kappa = 0.25 \* 3/2e-6  \* 1/6  =  62500  1/m

These particles are so tiny that they form a very optically dense cloud. Jason does a similar analysis above calculating the effective projected area of all these tiny particles. I have found that kappa needs to be on the order of 1 to get sensible results, at least with the current scheme where we just sum up the drag of all the particles and impose it on the gas.

**Comment by mcgratta** [comment]
I think this is why those who do CFD with very fine dense clouds of particles often treat it as a special kind of gas species.

**Comment by rmcdermo** [comment]
I don't really understand this.  I would think that as particles become very small, they should basically become tracers.  If they are evenly distributed in the flow, then they should be ok.  I think that, like tracers, there should be a random walk to make the particle number density uniform.  Anyway, when you push this up, I'll test.

**Comment by mcgratta** [comment]
Think of the particles as a stationary block that is blocking this vertical tunnel. Even though the particles only occupy 1/6 of the volume, they are so dense that light would not be able to penetrate more than a fraction of a millimeter (1/62500 m). But, yes, in reality we should be able to push air through this block, but we'd need a lot of pressure to do it. And in reality, the drag exerted by each particle would be reduced because they are packed close together. What we are doing is summing all the drag and just adding it to the grid cells, forming a massive source term that reverses the flow direction and then starts things oscillating wildly.

**Comment by mcgratta** [comment]
If I increase the density of the particles to 1000, and decrease the mass flux to 0.0002, then kappa is 0.75 and the particles behave as you would expect. As you increase the mass flux from there, you will eventually see spurious behavior.

**Comment by mcgratta** [comment]
I'm still digging into this. Given all I've said, I still think your test case fails too quickly. I'm printing out particle and cell values, and things go bad very fast.

**Comment by rmcdermo** [comment]
I have a solution for this case that I'm testing now---I'm creating an option for a MASSIVE_TRACER.  That is, there is a one-way drag from fluid to particle, but the particle does not exert a drag force on the fluid.  In these cub burner cases, the flame is pretty much laminar and all we want is for the particles to follow the flow and evaporate or decompose.

That said, once I implemented this, the case still went unstable.  So, that is evidence that it is not all drag.  I think the boundaries are too close to the flame, and the pressure solver can be tightened up.  With these changes, things seem to be working.

<img width="642" alt="Screen Shot 2020-10-16 at 10 37 26 AM" src="https://user-images.githubusercontent.com/4418497/96272068-9a6b4180-0f9b-11eb-9870-eda2fd14e268.png">

**Comment by rmcdermo** [comment]
Discovered something interesting.  Run this case with the code I just pushed up.  With AIT set and no exclusion zone, the particles somehow decompose and create low temperatures.  If AIT is not set, the case starts and runs fine.  I have not yet dug into this, but might be a clue to other odd behavior.  The ACCEL_X, etc., terms are all zero.

[test2.fds.txt](https://github.com/firemodels/fds/files/5393233/test2.fds.txt)

**Comment by mcgratta** [comment]
Set `HEAT_TRANSFER_COEFFICIENT=50` on the SURF line for 'KSA'. The HTC is inversely proportional to radius, and it's so large that the convective heating becomes unstable. That is, even with ambient temperature, the particles start to heat up and down spuriously. We should find a reasonable upper bound for HTC.

**Comment by drjfloyd** [comment]
That is an interesting observation. Whatever we decide on for limiting the HTC, we probably need to consider if it should also apply to droplets and possibly even blowing for very fine droplets. Given a particle temperature and an air temperature could this be treated as a semi-infinite solid in spherical coordinates (where the gas is the solid) with a constant temperature (particle temp) boundary condition?

**Comment by mcgratta** [comment]
Not sure what you mean.

**Comment by drjfloyd** [comment]
For these small particles, the particle and the gas are basically at the same velocity, so geometry is multilayer sphere where the outer layer is the air and the inner layer is the particle. Consider the particle to be fixed at its temperature. We now have a spherical coordinates conduction problem with a fixed temperature boundary condition on the inside surface of the larger sphere. The particle densities are such that there are many particle diameters between particles so we can probably treat the outer gas layer as being effectively infinite. This will have a steady state solution that would give a limit on heat transfer form the particle.

**Comment by mcgratta** [comment]
I think I've tripped over this mine several times before. If you limit HTC, the case at the very top of this thread appears to run OK. Other test cases are working too. Just from a numerical stability standpoint, it appears that for a sphere of radius r and density rho and specific heat c, HTC has to be kept below:

h < r \* rho \* c / (3 \* dt)

or else convection can heat the sphere to a temperature higher the gas temperature in the time dt.

**Comment by drjfloyd** [comment]
That is a simpler solution than my idea.

**Comment by rmcdermo** [comment]
Yes, Kevin, I like it.

**Comment by rmcdermo** [comment]
Yes, CHECK_HT=T solves the problem too, but is probably more expensive.  Limiting H is like limiting the viscosity for a given DT to avoid a VN instability.

**Comment by mcgratta** [comment]
Yes, I found that limiting the time step to really low values worked too, but impractical.

**Comment by rmcdermo** [comment]
Actually, CHECK_HT is not so bad.  The reason this only showed up when I implemented AIT is that the combustion divergence is limiting the time step anyway.

**Comment by mcgratta** [comment]
I'm going to create `LP%HTC_LIMIT=RADIUS*ONE_D%RHO_C_S(1)/(3*DT)` which is calculated where particle mass and area are calculated. I'll test it tonight.

**Comment by mcgratta** [comment]
I implemented the upper bound on HTC. Try your various cases and make sure they work now.

**Comment by rmcdermo** [comment]
Kevin,
Your modifications seem to be working well. I ran several cases over the weekend and no problems.  This particular case still might have issues in that we are getting different MEC mass loadings for CYLINDRICAL and 3D calcs.  But that is likely a different issue.  I will close this one and open another if I pin point what is going on.  Thanks for the help.
