### ISSUE TITLE
Spray modelling issue - Nozzle position affects simulation

### ISSUE THREAD

**Issue by rkj15** [firemodels/fds#8774]
Hello,

I am trying to model the a hose spray and the simulation gets stuck right before the activation of the spray starts. In my case the simulation did not proceed beyond 5.55 seconds.  The issue was noticed on both Windows and Linux operating systems. 
I was able to fix the issue by moving the position of the nozzle one cell backwards (7.6 m to 7.4 m). The nozzle is not at a mesh interface so that doesn't seem to be the cause. I have attached a simplified input file. Can somebody take a look at it?

Br,
Rahul

[debug1.txt](https://github.com/firemodels/fds/files/5286298/debug1.txt)

**Comment by mcgratta** [comment]
The calculation was in an endless loop because the droplets are injected into a mesh that is different from the one containing the nozzle. The code will now stop in error if the droplets are injected into a mesh that is different from that of the nozzle.

**Comment by rkj15** [comment]
Okay. But I don't understand why the code worked when I moved the nozzle to 7.4 m ? 
Also, this would make simulations of fire hose sprays difficult especially if the throw of the spray is a few tens of meters.

**Comment by drjfloyd** [comment]
Droplets are inserted using the sprinkler XYZ plus the OFFSET.  In your case the OFFSET meant that FDS was trying to insert drops into a mesh other than the one the sprinkler was in. Once drops are inserted; having the drop move between meshes is not a problem. The only restriction is that the spherical segment defined by XYZ, the spray pattern, and OFFSET needs to be in one mesh.

**Comment by rkj15** [comment]
Ah now I understand what Kevin meant by the nozzle and droplet being in the same mesh. Thank you.
