### ISSUE TITLE
Updating Validation_Guide

### ISSUE THREAD

**Issue by dpkPrasadPaudel** [firemodels/fds#8777]
Dear All,

Needed advice for guide updates. The cloned version do not have plots in SCRIPT_FIGURES. I separately checked my own experiment plots as explained in wiki pages. But for successful guide compilation, it looks as if all experiment plots are required. 
confused about which one among two procedures I should adopt?

create all plots > successfully compile > delete plots > pull request
or 
check individual exp plots > delete plots > compile without plots > pull request

**Comment by mcgratta** [comment]
You need to run the script called FDS_validation_script.m in Utilities/Matlab. This script creates all the plots needed for the FDS Validation Guide.

**Comment by rmcdermo** [comment]
You need to either create the plots yourself, as discussed in the verification and validation wikis.

Or you can download the SCRIPT_FIGURES from the nightly build site [here](https://drive.google.com/drive/u/0/folders/0B_wB1pJL2bFQUlJwMmNfaHlqME0).  See the FIGURES folder, copy the zip from the manual of interest and copy these to the SCRIPT_FIGURES directory.

Last, you do not need to delete your figures in order to send a PR.  The pdfs, etc., in SCRIPT_FIGURES are not tracked files in the FDS Git repo.

**Comment by mcgratta** [comment]
If you are adding new plots to FDS_validation_dataplot_inputs.csv, you should run the entire script to ensure that things are working properly.

**Comment by dpkPrasadPaudel** [comment]
I am adding a new experiment (Insulation Materials) with only surface temperatures as output. Running FDS_validation_script.m for only "Insulation Materials" works, but not for all experiments, I get the following error:

>
Printing plot Flame_Height_check_hrr.pdf ...
Error using import data (line 139)
Unable to open the file.

Error in FM_Burner (line 71)
CHIR = importdata([expdir,'Radiant_fraction.csv'],',',1);

Error in FDS_validation_script (line 46)
FM_Burner
> 

Could it be that the files are missing for FM_Burner?

**Comment by dpkPrasadPaudel** [comment]
The guide successfully builds with nightly build site plots + own experiment plots created using FDS_validation_script.m. This way, the new experiment description, and new data plots are added. For the scatter plot to include our experiment, I guess, the FDS_validation_script.m run is a must for all the experiments, which gave the following error:
>
Error using importdata (line 139)
Unable to open file.

Error in FM_Burner (line 71)
CHIR = importdata([expdir,'Radiant_fraction.csv'],',',1);

Error in FDS_validation_script (line 46)
FM_Burner  
>

**Comment by rmcdermo** [comment]
I think you need to update submodules for your exp repo.  Notes are here: [Git Notes Submodules](https://github.com/firemodels/fds/wiki/Git-Notes-Submodules).  The important bit for you is:

1. `cd` to top level of exp repo
2. do `git submodule foreach git remote update`
3. do `git submodule foreach git merge origin/master`

Now you should be good.
