### ISSUE TITLE
LEVEL_SET_MODE=1 wild fire simulation is not started if WIND is zero

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#8780]
How to reproduce:
Take the `Bova_1a.fds` case and modify `&WIND U0=4.3 /` to `&WIND U0=0. /`.
After running the case, no fire front propagation is shown in smokeview.
Note that, if you set `&WIND U0=0.00001 /` the fire front propagation is shown.

Thank you,
Emanuele

**Comment by ruddymell** [comment]
I can fix this.

**Comment by ruddymell** [comment]
Pull request to fix this has been submitted.

**Comment by rmcdermo** [comment]
Thanks, Ruddy.  Should be merged now #8786

**Comment by emanuelegissi** [comment]
Thanks Ruddy
