### ISSUE TITLE
FDS Output: Time to threshold temperature 

### ISSUE THREAD

**Issue by dpkPrasadPaudel** [firemodels/fds#8789]
**Fire resistance time**(FRT) is the time after which structure cold-side surface temperature crosses a threshold value. Is there a way around to obtain  FRT as a direct FDS output?. 

PS. FRT is inferred using time-temperature plot. But, having it as FDS output ease the FDS validation and uncertainty estimation procedure.

**Comment by drjfloyd** [comment]
You should be able to this with current outputs. Place a device that measures the back side temperature. You can use XB and the MAX statistic to cover an area with one device. Give it a setpoint that is the threshold temperature. The time that a device hits its setpoint is written to the smv and out files. You can also see when that time is by looking at the dev file. You could also have a device that measures time and set it to stop updating when the FRT device trips.
