### ISSUE TITLE
Tunnel Pressure difference among FFT and GLMAT one mesh simulations

### ISSUE THREAD

**Issue by Cactilio07** [firemodels/fds#8806]
![pressTime](https://user-images.githubusercontent.com/33253426/95355417-d4ff1b00-08c5-11eb-982b-b209491a0aa8.png)
![MflowTime](https://user-images.githubusercontent.com/33253426/95355455-e0eadd00-08c5-11eb-8aa7-c0130b47025d.png)
Time graphs of a section 4m away from the tunnel exit.
![pressure](https://user-images.githubusercontent.com/33253426/95355474-e6e0be00-08c5-11eb-86cb-33d3a6184657.png)
![temperature](https://user-images.githubusercontent.com/33253426/95355554-f6f89d80-08c5-11eb-894c-f05719ec393e.png)
Average from 100 to 150 seconds

The pressure comparison is initially made in a model of a tunnel of 214m of length, 6.4m x 6.4m of cross section, a fire of 55MW and 6 pairs of fans along the tunnel, flow and temperature are shown also for completeness. Constant_Specific_Heat_Ratio is true,  suppresion and stratification are false.

Is possible to observe the difference in the solutions provided by FFT and GLMAT, where GLMAT solutions provide more reasonable values to the pressure, and smaller oscillations.

[FFTConst.txt](https://github.com/firemodels/fds/files/5342032/FFTConst.txt)
[GLMATConst.txt](https://github.com/firemodels/fds/files/5342037/GLMATConst.txt)

To simplify this model a smaller tunnel was simulated. 50m of length (plus 5 meters before and after of OPEN boundaries), and a cross section of 5m x 5m. It has free slip, adiabatic walls, no fans, among other simplifications.

Here it is also possible to observe how the pressure solution for both of the models is not the same, with GLMAT providing a more stable solution over time and FFT oscillating more in its solution.

Once again the only difference among the simulations is the pressure solver used.

[test50m50MWGLMAT.txt](https://github.com/firemodels/fds/files/5342156/test50m50MWGLMAT.txt)
[test50m50MWFFT.txt](https://github.com/firemodels/fds/files/5342159/test50m50MWFFT.txt)
[test50m50MWFFThalf.txt](https://github.com/firemodels/fds/files/5342218/test50m50MWFFThalf.txt)
[test50m50MWGLMAThalf.txt](https://github.com/firemodels/fds/files/5342220/test50m50MWGLMAThalf.txt)

![Presstime](https://user-images.githubusercontent.com/33253426/95358741-abe08980-08c9-11eb-8924-d9686c3079f8.png)
![PressureAVG](https://user-images.githubusercontent.com/33253426/95359246-388b4780-08ca-11eb-9372-05a51f2c77bf.png)
![VelocityAVG](https://user-images.githubusercontent.com/33253426/95359362-58bb0680-08ca-11eb-9ddb-9b4972c25ddb.png)
![Mflowtime](https://user-images.githubusercontent.com/33253426/95359562-9c157500-08ca-11eb-897d-71e5da9c35a5.png)

I understand that both the solvers will receive the same RHS information to solve the poisson equation, and that their solutions to this equation should be the same. 

Both of the cases were run in recently compiled (mpi_gnu_linux_64) versions of the code, the simpler cases with today morning source files, the others with last week version.

**Comment by mcgratta** [comment]
Is there a question here?

**Comment by marcosvanella** [comment]
Jesus, are the calculations using the different pressure solvers being iterated the same number of times? Note that if you are iterating the baroclinic term, the solutions will also vary depending on the number of pressure iterations.

**Comment by rmcdermo** [comment]
Jesus,
I said to post a *simple* case.  This is far too complicated.

However, Marcos,
If one just changes the SOLVER, would that change the tolerance for the pressure iterations?

The basic issue is simple: there is a tunnel scenario and the FFT and GLMAT solver, nominally the same, give difference pressure solutions.  I see no reason these should not give identical solutions.

**Comment by marcosvanella** [comment]
I see the first cases posted are single mesh, so GLMAT and FFT should give same solution and run for the same number of iterations. GLMAT is giving a larger error values. I'm investigating.

**Comment by marcosvanella** [comment]
Jesus, do an update and try the code. You have some small OPEN vents in the roof. GLMAT applies Dirichlet BCs in those OPEN regions but Neumann BCs in the rest of the roof which is SOLID boundary. It was not applying Neumann BCs in the solid parts of the roof before going to compute residual. I took care of that.
FFT **changes the whole roof** to a Dirichlet BC for pressure when you have OPEN vents, and tries to force the normal velocity to zero in the solid boundaries. 

Residuals shown with GLMAT (i.e. Poisson error and Pressure Error) were higher leading to more pressure subiterations than FFT. Those numbers should be close now, although the solution will not be exactly the same due to the reason explained before.

**Comment by Cactilio07** [comment]
The first pair of cases is complicated, but they are there just to show the difference, the simplified cases with the 0.5 mesh for me run in less than 90 seconds, but as the fire seems to not be part of the issue maybe even that could be simpler. Still, sorry for the long message.

And Marcos, i will update and rerun, thanks. I will also try turning Baroclinic to false, and see if it helps getting closer results among the two solvers.

**Comment by rmcdermo** [comment]
This is a simple input file.  Compare it to the one you posted.
```
&HEAD CHID='test', TITLE='simple input file'/

&MESH IJK=120,10,10, XB=-30.00,30.00,-2.50,2.50,0.00,5.00/

&TIME T_END=400./

&PRES SOLVER='FFT'/

&REAC FUEL='N-HEPTANE', SOOT_YIELD=0.015/

&SURF ID='fire source', COLOR='RED', HRRPUA=4167/ 50MW
&VENT XB= -3.0, 3.0,-1.0,1.0, 0.0,0.0, SURF_ID='fire source'/

&VENT SURF_ID ='OPEN', DB= 'XMIN', DYNAMIC_PRESSURE=10/
&VENT SURF_ID ='OPEN', DB= 'XMAX'/

&SLCF QUANTITY='PRESSURE', PBY= 0.00, CELL_CENTERED=T/
```

"And Marcos, i will update and rerun, thanks. I will also try turning Baroclinic to false, and see if it helps getting closer results among the two solvers."

Why are you going to set BAROCLINIC=F?  The reason the pressure solver solutions differed was because when you put an OPEN bc on the side boundaries (anywhere) then the FFT solver changes from a Neumann bc to a Dirichlet bc.  You are not solving the same mathematical problem.

**Comment by Cactilio07** [comment]
> Jesus, are the calculations using the different pressure solvers being iterated the same number of times? Note that if you are iterating the baroclinic term, the solutions will also vary depending on the number of pressure iterations.

The baroclinic F was to reduce the difference between the calculation done between the two models. But maybe having the same amount of iterations might be better instead.

And i understand that having parts of the side boundaries as OPEN makes FFT turn everything to a Dirichlet, and instead GLMAT only puts Dirichlet BC's in the OPEN areas and leaves the Solid as Neumann. Still i wanted to test if under more simmilar conditions they get closer results, despite the fact that they do solve different problems.
