### ISSUE TITLE
Reset .bnd files at start of a new FDS run

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8816]
It appears that the data bound files used by Smokeview do not get reset at the start of an FDS run.  Please check this.  It is hard to give you a test case because I have since fixed the problem that allowed me to discover the issue.

**Comment by gforney** [comment]
Ill check.

**Comment by gforney** [comment]
did it happen for just this case or does it happen every time you rerun a case (where there are already .bnd files).  When I added this to fds I intended to open the bnd file using status='replace" (which should erase the old file) or status='append' in the same way that the correspsonding data file was opened.  I may have missed one

**Comment by rmcdermo** [comment]
The case I was working was looking at .prt5 QUANTITY data.  What happened was I have a bug in FDS and ran the case and looked at the results in Smokeview; the output was senseless (because of my bug), smv thought the bounds were 1e25.  Then I fixed my problem in FDS, reran the case, and closed and opened SMV.  The colorbar bounds were still garbage.  Then, I closed everything, deleted all the .bnd files, reran FDS (same code) and again looked at the case in smv.  Now the colorbar limits were correct.  So, my hypothesis is that the .bnd files were not getting replaced for .prt.

If you think this is an anomaly, then go ahead and close the issue.  Sorry but I don't have time to figure out a way to recreate the problem on purpose.  Just keep an eye on this.  It seems odd that we keep having issues with Alt R, etc., and this all is related to the colorbar bounds.

One thought would be---if you have not trashed the old code---is to add an option to compute the colorbar limits based on statistics from the particular file (.prt, .bf, .sf).  That is, reread and compute the limits from the actual data.  Then we could at least double check if something is off, even if that takes longer.

**Comment by gforney** [comment]
Ill keep an eye on it. My guess it is a bug in smokeview.  Do you remember
if you saved an .ini for your case? Smokeview gets bounds from there too.
It could have gotten mixed up. Ive been reworking this code so may have
messed something up. Keep the case open to remind me to be on the lookout

**Comment by rmcdermo** [comment]
I did not have an ini file.  But I must confess, I use an older version of smv (pre X11) because X11 is painful.

**Comment by gforney** [comment]
I'll take another look at getting the non-x11 version working.  I was
almost there.  there is some factor of 2 in screen size lurking somewhere I
didn't figure out before

**Comment by drjfloyd** [comment]
Has this been resolved?

**Comment by gforney** [comment]
think this was an issue when fds was not outputting bounds to .bnd files .  smokeview was generating them so that it did not have to recompute bounds.  apparrently in some situations smokeview was not rengenerating bounds.  but now fds is outputting bounds to .bnd files.  I just reran a case and the .bnd files were regenerated.  think we can close this issue.

**Comment by gforney** [comment]
i'll close.  if problem comes up again I'll look at it
