### ISSUE TITLE
Combine redundant code from DUMP_PART and PARTICLE_OUTPUT

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8819]
While adding outputs in PR #8817 I noticed that we have redundant output lists for the .prt5 file (DUMP_PART) and devices (PARTICLE_OUTPUT).  I think that PARTICLE_OUTPUT could be used by DUMP_PART, but it looked a bit tricky because of the solid phase select case in DUMP_PART.

@mcgratta could you please take a look at this?

**Comment by mcgratta** [comment]
Yup, will do. I don't recall when that redundant list was created.

**Comment by mcgratta** [comment]
But I wouldn't be surprised if it were me.

**Comment by mcgratta** [comment]
I ran the verification cases a few time steps in debug mode and things seem OK. Check firebot tomorrow and then close.
