### ISSUE TITLE
I can't run a smokeview file

### ISSUE THREAD

**Issue by LLLLLLLhy** [firemodels/fds#8822]
HI
I am trying to run an example file using a macbook pro.
After the fds simulation, I can't run the .smv file.

<img width="570" alt="Smokeview" src="https://user-images.githubusercontent.com/72660710/95658011-56ff7600-0b4a-11eb-922d-83932dcca7e0.png">

**Comment by LLLLLLLhy** [comment]
it gives :

$ smokeview circular_burner
dyld: Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Applications/FDS/FDS6/smvbin/smokeview
  Reason: image not found
Abort trap: 6

**Comment by rmcdermo** [comment]
This is not a bug.  Please post your question to the discussion forum.
