### ISSUE TITLE
Generating scatter plots for Hamins burner experiments

### ISSUE THREAD

**Issue by ahsadeghi** [firemodels/fds#8823]
Hi, I need to generate scatter plots for Hamins burner experiments. The plots are generated for some of the validation cases and are stored in the SCRIPT_FIGURES folder but not for Hamins experiments. Thank you for your attention.

**Comment by rmcdermo** [comment]
I do not understand the issue.  I just looked at the validation guide generated last night from the repo and, spot checking the plots, it looks like Hamins cases are in the scatterplots.  Are you sure you understand how to generate the scatterplots?  If not, then that should be posted to the discussion forum.  The Issues page is for demonstrated bugs in the code or documentation.
