### ISSUE TITLE
Error in Attaching Supporting Files

### ISSUE THREAD

**Issue by danish2016** [firemodels/fds#8833]
Dear Team,

I am facing an error in attaching files in the FDS-SMV discussion group
**File size**
FDS file = 9 kb
Png = 28 kb

Please have a look issue

Thanks & Regards

**Comment by drjfloyd** [comment]
When Kevin mentioned starting an issue he meant to try and your attach files here. The group is a service by Google and we don't have any ability to trouble shoot problems with it other than suggest you try again at a later time or report a problem to Google.

Closing as I see you managed to add the information to your forum post.

**Comment by gforney** [comment]
did you change the extension on the .fds input file. to something like .txt ?
