### ISSUE TITLE
Check for repeated SURF ID logic does not work with null DEFAULT SURF

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8836]
The logic to check for repeated SURF IDs gives the wrong error if a DEFAULT SURF is specified before it without an ID.  In read.f90 it appears that we want to give the user a pass if they forget to specify an ID for a DEFAULT SURF.  We do not throw an error, we just rename it "DEFAULT SURF".  However, when this happens, an error does occur---the user is told that the next SURF line has been repeated.  Look at this case:
```
&HEAD CHID='test'/
&MESH IJK=5,5,5, XB=0,1,0,1,0,1/
&TIME T_END=10./
&SURF ADIABATIC=T, DEFAULT=T/
&SURF ID='new surface', VEL=-1/
&TAIL /
```

**Comment by mcgratta** [comment]
Is there a reason why we don't just throw an ERROR if the SURF line has no ID? That seems to be the simplest solution.

**Comment by rmcdermo** [comment]
Not sure.  You put the code in in 2017.  See read.f90 circa line 7048.
```
   ! Check to make sure that a DEFAULT SURF has an ID

   IF (DEFAULT) THEN
      IF (ID=='null') ID = 'DEFAULT SURF'
      SURF_DEFAULT = TRIM(ID)
   ENDIF
```

**Comment by mcgratta** [comment]
No good deed goes unpunished. I'll fix.

>

**Comment by mcgratta** [comment]
This wasn't really about DEFAULT=T, but rather the ID string for SURF 2 was carried over from the previous SURF read.
