### ISSUE TITLE
Please change 2 lines in fds2ascii in order to process large simulations

### ISSUE THREAD

**Issue by bphusted** [firemodels/fds#8839]
Hi
I am using fds2ascii, - and there is a limit on the number of slice files it can process and also how it it displayed.
Currently the limit is 500 and if there is more than 100 slice-files you do not see the first digit.

The solution is (which I have tested to be working on linux)
Line 27:  Change INTEGER, PARAMETER :: FILE_DIM = 500  to
INTEGER, PARAMETER :: FILE_DIM = 2000

Line 412: Change                   write(6,'(I3,1x,A,1x,A)')I,TRIM(SLCF_TEXT(I)),TRIM(SLCF_FILE(I)) to
                  write(6,'(I5,1x,A,1x,A)')I,TRIM(SLCF_TEXT(I)),TRIM(SLCF_FILE(I))

br
Bjarne

**Comment by mcgratta** [comment]
Bjarne -- you can make these kinds of changes directly within the GitHub browser. If you have a fork of the fds repository, you can edit fds2ascii.f90 within your fork and then issue a pull request. I made the change by editing the file directly within the central repo, but I could have also done it in my fork.

**Comment by bphusted** [comment]
Kevin -- thanks.  I was not aware that I had privileges to issue pull request. I updated the repo on another cluster and got the right updated file, which I also could compile and run. So it works and I will close this issue.

**Comment by mcgratta** [comment]
Anyone can submit a pull request. For simple changes like yours, you can
edit the file in your own fork on GitHub, and then issue a PR. For more
extensive changes, you must clone your fork to your local computer, make
changes, commit, push to fork, and then issue PR from the fork.

>
