### ISSUE TITLE
GEOM rotate failed with "could not close polyline" error

### ISSUE THREAD

**Issue by dvswenson** [firemodels/fds#8847]
When I rotated a cube 30 degrees about the Z axis, the solution failed with the error message:

 IFLG ~=0, could not close polyline,  T :            4           6           5
 IFLG ~=0, could not close polyline,  T :            4           6           6

However, if I rotate the cube 40 degrees, the solution proceeds without error, as shown in the image. If I just translate the cube the solution is also successful.

The model and vertex definition is attached.

[move_rotate_x.fds.txt](https://github.com/firemodels/fds/files/5373602/move_rotate_x.fds.txt)
![cube vertices](https://user-images.githubusercontent.com/13338306/95905824-ef6e4400-0d5e-11eb-81d3-491555ad9f4a.png)
![cube rotated 40 deg](https://user-images.githubusercontent.com/13338306/95905854-f72de880-0d5e-11eb-9f6a-d772b4b18a97.png)

.

**Comment by marcosvanella** [comment]
Thank you Dan, I'll have a look.

**Comment by marcosvanella** [comment]
Hi Dan, I'm not being able to reproduce the issue. Did you use this MOVE line?

`&MOVE ID='rot_x', ROTATION_ANGLE=30., AXIS=0.,0.,1./`

Also, are you using latest (as of last week) fds source? Thanks.

**Comment by dvswenson** [comment]
Sorry, I was using an older release - FDS6.7.4-0-gbfaa110f1-release. I will download the nightly and test that.

However, I also work only half-time and am just about finished for this week, so probably will not get things redone until next week.

**Comment by dvswenson** [comment]
The error did not occur when I ran with the nightly build. So please close the case.

 Current Date     : October 19, 2020  13:21:47
 Revision         : FDS6.7.5-332-ga5bac4a8d-nightly
 Revision Date    : Sat Oct 17 15:42:44 2020 -0400
 Compiler         : Intel ifort 19.1.1.216
 Compilation Date : Mon 10/19/2020  06:03 AM
