### ISSUE TITLE
Smokeview Data Bounds

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#8853]
According to "SMV_User_Guide 5.1 Data Bounds" it should be possible to change the data range from global (min,max) to set (min,max).
When pressing the UPDATE button in Slice/Bound Data the radio buttons change from set (min,max) to global (min, max). The new entered values are not changed, but at the next reloading of the files (Shortcut u) the values change again to global (min, max).
The same applies to Boundary/Bound Data. But in this case it is not possible to change the values by pressing the RELOAD button.

**Comment by gforney** [comment]
smokeview is probably in research mode".  when in research mode smokeview onlyi uses global bounds.  look at the console window and look for a message regarding whether research mode is on or off.  If on, press ALT r to turn it off.  Or if not sure press ALT r until you see that research mode is off

it could also a bug that has been fixed.  if you still see a problem you can download the latest test smokeview located here
https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC?usp=sharing
This test smokeview also makes more clear in the bounds dialog box to use ALT r to enable regular bounds use

**Comment by drjfloyd** [comment]
People have many years of experience in being able to open a Smokeview file, go to the bounds dialog, and right away be able to change bounds. This is the behavior I think most practitioners want and expect. Adjusting the bounds to highlight some specific range of interest for a quantity is fairly routine when using FDS for design. WIth the current UI, I have to leave the dialog box and go back to the graphics window to type alt-r. That isn't intuitive and some people may just try Alt-r in the dialog window and not think to go back to the main window.

**Comment by gforney** [comment]
I agree.  this should be fixed in a smokeview not quite ready for testing.  I added a checkbox to the bounds dialog for toggling research mode - you don't have to go back to the graphics window.

**Comment by herbertTau** [comment]
I agree that I would like this behavior going to the bounds dialog, and right away be able to change bounds. Since RESEARCHMODE is set to 1 by default in smokeview.ini, I changed this value to 0.

**Comment by gforney** [comment]
check the latest test smokeview and let me know if there is still an issue
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by lu-kas** [comment]
@gforney we run in the same issue as the OP two days ago and found this open issue. Your build does solve our issue, and probably also the OP's

Thanks! Lukas

**Comment by gforney** [comment]
Glad it is working. Thanks for the report
Glenn
