### ISSUE TITLE
Enhancement: add ORIGIN_ELEV parameter to MISC namelist, update WIND GROUND_LEVEL

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#8869]
When dealing with terrains it is convenient to define the origin elevation, and have all the terrain heights relative to that elevation. This allows to keep the terrain surface closer to the geometric origin.

I suggest adding a new parameter `ORIGIN_ELEV` to the `MISC` namelist:

```
&MISC ORIGIN_ELEV=1564.0
      ORIGIN_LON=14.000000
      ORIGIN_LAT=45.000000
      NORTH_BEARING=20. /
```

The `WIND` namelist should be updated accordingly so that the `GROUND_LEVEL` value is added to the `ORIGIN_ELEV`.

This proposal is backward compatible, because the default for `ORIGIN_ELEV` would be 0.
Thanks.

**Comment by mcgratta** [comment]
This could cause confusion. Currently, the XB coordinates on the MESH line define the coordinate system, and all x, y, and z coordinates for all input parameters conform to this system, including `GROUND_LEVEL`.  It is assumed that `P_INF` occurs at `GROUND_LEVEL`, but even this has caused some confusion among the users and some bugs among the developers. Your proposed `ORIGIN_ELEV` would only affect the terrain data, and could potentially be applied to the data before it is added to the input file. Is this very important for the QGIS2FDS script?

**Comment by emanuelegissi** [comment]
I imagined that it could affect all geometric entities (eg. XB, PB, XYZ,
GEOM, ...) before simulation, a unified place in MISC to set the absolute
positioning of the origin together with ORIGIN_LON, ORIGIN_LAT, and
NORTH_BEARING.

But no, it is not very important for qgis2fds.
Feel free to close it, if you think it is not worth the confusion it may
cause.

**Comment by mcgratta** [comment]
Unfortunately, there is no "unified" place in MISC. Whenever we add a scaling factor like this, we always forget to apply it to some inputs, and of course we get bug reports. If this is not critical, I would rather postpone it until such a time when there is some pressing user demand. Thanks.

**Comment by emanuelegissi** [comment]
Ok
