### ISSUE TITLE
Influence of water mist system code (system inactive) on fire development?

### ISSUE THREAD

**Issue by AnnaStanzel** [firemodels/fds#8893]
HI There,
I am experiencing a strange bug here, Maybe someone had the same experience and can help:

I run a tunnel fire in FDS 5.5.3 
- without water mist System and 
- with water mist System. 

The water mist is set to active after 700 seconds of free burn.
The Code for the fire is the same in both Scenarios.

Nevertheless the HRR of both Scenarios develops in differnt ways (up to 20 MW different!). 
The HRR of the Scenario with the water mist System code in it - even though the System is INACTIVE over the first 700 seconds - somehow infuences the development of the pyrolysis model. The fire develops slower and reaches a lower HRR after the same time.

Does anyone have any clue what could be the reason for that behaviour?
I would be happy to hear your Input!
Cheers, Anna

**Comment by rmcdermo** [comment]
First, please use the latest code.  Second, this question should be posted to the [discussion forum](https://groups.google.com/g/fds-smv).
