### ISSUE TITLE
Duct energy flow

### ISSUE THREAD

**Issue by herbertTau** [firemodels/fds#8904]
The HVAC output quantity "DUCT ENERGY FLOW" of the attached case doesn't produce the expected result,
if I assume that Q = -m'.cp.(T-TMPA).

[hvac_energy.fds.txt](https://github.com/firemodels/fds/files/5475245/hvac_energy.fds.txt)
[hvac_energy_devc.csv.txt](https://github.com/firemodels/fds/files/5475256/hvac_energy_devc.csv.txt)

**Comment by drjfloyd** [comment]
We need to put a better description of what this is in the User's Guide.  This is the enthalpy flow in the duct. Enthalpy is cpbar(T) T and not cp(T) T. This does raise a good point that we could use a DUCT HEAT FLOW that is equivalent to the gas phase quantity HEAT FLOW.

**Comment by drjfloyd** [comment]
Changed this to be consistent in name and function to be like the current FDS gas phase QUANTITY for ENTHALPY FLUX.  The duct quantity is changed to DUCT ENTHALPY FLOW and it outputs the flow of enthalpy using Eq. 21.30 (in the current draft of the guide) applied to the duct. Pull request: https://github.com/firemodels/fds/pull/10155
