### ISSUE TITLE
No longer able to deactivate / activate vents associated with a leak

### ISSUE THREAD

**Issue by cghopkin** [firemodels/fds#8916]
I receive an error when trying to run a case where vents associated with an HVAC (localised) leak are activated or deactivated. This worked in FDS 6.7.4 but produces an error when running in FDS 6.7.5:

```
ERROR: VENT for ductnode has a DEVC_ID or CTRL_ID, VENT ID:LEAK_01 (CHID: leak_test)

ERROR: FDS was improperly set-up - FDS stopped (CHID: leak_test)
```

I’ve tried to break it down into a simple problem below to demonstrate the point. Not sure if this is a new bug or by design. Apologies if this has already been covered in the discussion forums or is on the issue tracker already – I had no luck when trying to find it.

```
&HEAD CHID='leak_test'/

&TIME T_END=10.0/

&MESH ID='MESH', IJK=10,10,10, XB=0.0,1.0,0.0,1.0,0.0,1.0/

&DEVC ID='ACTIVATE', QUANTITY='TIME', XYZ=0.0,0.0,0.0, SETPOINT=5.0/

&OBST ID='Wall', XB=0.4,0.5,0.0,1.0,0.0,1.0, SURF_ID='INERT'/ 

&VENT ID='LEAK_01', SURF_ID='INERT', XB=0.4,0.4,0.3,0.7,0.0,0.5, COLOR='GRAY 94', DEVC_ID='ACTIVATE'/ 
&VENT ID='LEAK_02', SURF_ID='INERT', XB=0.5,0.5,0.3,0.7,0.0,0.5, COLOR='GRAY 94', DEVC_ID='ACTIVATE'/ 

&HVAC ID='LEAK', TYPE_ID='LEAK', VENT_ID='LEAK_01', VENT2_ID='LEAK_02', AREA=0.01, LEAK_ENTHALPY=.TRUE./

&TAIL /
```

**Comment by cghopkin** [comment]
Copied the wrong error code. See below for what I actually get.

ERROR: VENT for ductnode has a DEVC_ID or CTRL_ID, VENT ID:LEAK_01 (CHID: leak_test)

ERROR: FDS was improperly set-up - FDS stopped (CHID: leak_test)

**Comment by drjfloyd** [comment]
If this worked properly before, you were lucky. HVAC isn't set up to have VENTs added or removed during a simulation. We added error trapping for this in 6.7.5. However, I can see that this would be useful to have as a feature. It needs to be done with a damper though rather than turning on or off a VENT.  

As a work around replace the LEAK with a duct and two nodes. 

&HVAC ID='NODE1',TYPE_ID='NODE',VENT_ID='LEAK_01',DUCT_ID='LEAK'/
&HVAC ID='NODE2',TYPE_ID='NODE',VENT_ID='LEAK_02',DUCT_ID='LEAK'/
&HVAC ID='LEAK',TYPE_ID='DUCT',NODE_ID='LEAK_01','LEAK_02', DAMPER=T,DEVC_ID='ACTIVATE',AREA=0.01,LENGTH=0.1,LOSS=1,1/

**Comment by cghopkin** [comment]
Thanks Dr. Floyd. I had a feeling that was the case.

One reason I want to be able to do this is to represent some form of leakage 'through' an obstruction prior to that obstruction being removed from the domain. For example, I may have a door which is initially leaking, represented via the HVAC leak and associated vents, but when the door subsequently opens, I can then deactivate both the door obstruction and the leakage vents. Would the work around you've suggested work for something like this? Or is there a better way to represent it than what I am currently trying to do?

Cheers.

**Comment by drjfloyd** [comment]
You should not add or remove a VENT connected to an HVAC component. For a door where leakage is around the perimeter, you could define the leakage vent just to the side of the door and/or at the floor on either side of the door.  Then when you remove the door the leakage vent will still be there. It will still be acting as a leak but if you have a typical 2 m^2 door and a 1 cm^2 leak it won't have a noticeable impact.

**Comment by cghopkin** [comment]
Noted. Thanks for your help.
