### ISSUE TITLE
GEOM error with OPEN wind simulation

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8929]
Marcos,
If the gods are good, this simple case will fix the larger Askervein errors.  I took the sem_open_wind.fds case that I have been using to develop the SEM OPEN inflow conditions (in Verification/Turbulence/).  I first added an OBST that was just a few cells thick to the floor.  The case runs fine.  Then I simply change OBST to GEOM and the case fails immediately with an error.
[test.fds.txt](https://github.com/firemodels/fds/files/5504855/test.fds.txt)

**Comment by rmcdermo** [comment]
@marcosvanella This case appears to get off the ground if I extend the GEOM to outside the domain.
```
&GEOM XB=-1,21,-7,7,-1,1, SURF_ID='ground'/
```
So, there appears to be a GEOM initialization problem with the original case.

**Comment by marcosvanella** [comment]
Randy, looks like this is related to the periodic boundary in Y. Making those OPEN or making the geometry extend one cell out of the domain in Y gets the case off the setup phase.

**Comment by rmcdermo** [comment]
OK, can this be fixed?

**Comment by marcosvanella** [comment]
I'm looking into it.

**Comment by marcosvanella** [comment]
Randy, do an update and try the case.

**Comment by rmcdermo** [comment]
Yep, works!  Thanks
