### ISSUE TITLE
Energy balance and ruptured pressure zones

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#8939]
This is an energy conservation issue that originated with my HEAF calcs. It's just a sealed box within another sealed box, with an opening between the two that ruptures at 10 s. The inner box is pressurized by a blowing cube.

Run the case below, and then plot `Q_ENTH` and `Q_TOTAL` from the _hrr.csv file as functions of time. They should be close, but diverge dramatically at 20 s. Nothing in particular is happening at the time. Looking at slices of `ENTHALPY` and `TEMPERATURE` suggest that something changes at the boundary of the little blowing box at center.

```
&HEAD CHID='zone_burst', TITLE='Test conservation of energy for a ruptured pressure ZONE' /

&TIME T_END=30., DT=0.01 /

&MESH XB=0.0,1.0,0.0,1.0,0.0,1.0, IJK=20,20,20/

&SURF ID='BLOW', VEL=-0.1 /

&OBST XB=0.10,0.15,0.10,0.90,0.10,0.90, COLOR='BEIGE' /
&OBST XB=0.85,0.90,0.10,0.90,0.10,0.90, COLOR='BEIGE' /
&OBST XB=0.15,0.85,0.10,0.15,0.10,0.90, COLOR='BEIGE' /
&OBST XB=0.15,0.85,0.85,0.90,0.10,0.90, COLOR='BEIGE' /
&OBST XB=0.15,0.85,0.15,0.85,0.10,0.15, COLOR='BEIGE' /
&OBST XB=0.15,0.85,0.15,0.85,0.85,0.90, COLOR='BEIGE' /

&OBST XB=0.40,0.60,0.40,0.60,0.40,0.60, SURF_ID='BLOW' /

&DEVC ID='CLOCK', QUANTITY='TIME', SETPOINT=10, INITIAL_STATE=F, XYZ=0,0,0 /
&HOLE XB=0.80,0.95,0.40,0.60,0.40,0.60, DEVC_ID='CLOCK', COLOR='BLUE' /

&SLCF PBY=0.51, QUANTITY='PRESSURE', CELL_CENTERED=.TRUE./
&SLCF PBY=0.51, QUANTITY='ENTHALPY', CELL_CENTERED=.TRUE./
&SLCF PBY=0.51, QUANTITY='TEMPERATURE', CELL_CENTERED=.TRUE./

&TAIL /
```

**Comment by drjfloyd** [comment]
It may have something to do with suddenly having extra gas present. The solid wall suddenly becomes gas at ambient conditions.

**Comment by mcgratta** [comment]
Perhaps, but the rupture occurs at 10 s, and for the next 10 s or so things are OK. I'm running another variant where I stop blowing air at 30 s and let the excess heat conduct into the walls. We should then just have a box with more air in it.

**Comment by drjfloyd** [comment]
I took the case and changed it to run for 5 s with the opening at 2.5 s, turned off radiation, and made all surfaces adiabatic and ran it. Saw the odd behavior at the vent opening time with enthalpy and total not quite lining up.

Then I set 
&PRES VELOCITY_TOLERANCE=0.00001,MAX_PRESSURE_ITERATIONS=100/

Now there is stlll a big oscillation when the hole opens but now the curves more or less lies on top of one another.
![image](https://user-images.githubusercontent.com/12799217/98857486-19ce2280-242d-11eb-8d61-c7f79d3f752c.png)

**Comment by mcgratta** [comment]
Right, but try the tight pressure in the original case.

**Comment by drjfloyd** [comment]
it is clipping on MAXIMUM_DENSITY at 25 s.

**Comment by mcgratta** [comment]
Doh! I should've known.

>

**Comment by rmcdermo** [comment]
Should we throw a WARNING to the .err file upon CLIPPING?  This seems to get us every time.

**Comment by mcgratta** [comment]
Sounds like a good idea. Like a few integer counters that count each time a
bound is hit. Then we can write out at the end rather than have a ton of
warning messages.

>

**Comment by drjfloyd** [comment]
Should the counter be on a time step basis (i.e. increment for any timestep where a clip happens) or a per cell basis (increment for each cell)?  For a case like this where every cell is clipped a per cell number could get very large if a case had a lot of cells and overflow the default integer type.

**Comment by rmcdermo** [comment]
For me, all that matters is that somewhere in the .err (not .out) we say "WARNING: CLIPPING occurred" or something to that effect.  I don't care how many times or where.  I just want to know whether to add a CLIP line to my input file before going on an energy conservation debug hunt.

**Comment by mcgratta** [comment]
I added a warning whenever `RHOMIN` or `RHOMAX` is clipped. The warning is written out directly by the MPI process where the clipping occurs into the .err file. The check is done within `CHECK_MASS_DENSITY` so there is no added cost or MPI calls. Checking for max and min temperatures would be more complicated, so let's see how this goes. Usually when bad things happen, it's because the density goes off the rails.

**Comment by mcgratta** [comment]
My original problem is solved. The clipping stuff is on-going, but not specific to this issue. I'm closing.
