### ISSUE TITLE
PC assembly for FDS SMV

### ISSUE THREAD

**Issue by gpcreatorstudio** [firemodels/fds#8956]
PC assembly for FDS SMV

Hello, I am a technician in charge of assembling a machine capable of processing the complex calculations of FDS SMV

What requirements must it have?
Harness the power of the CPU or GPU?
Need a lot of RAM?

The client who commissioned me for the job told me about the need for a mining machine, is that correct ???

My idea was to provide a server platform with 2 x 16 core XEONs, for a total of 32 cores

Thanks to those who will answer

**Comment by rmcdermo** [comment]
Please submit your question to the [discussion forum](https://groups.google.com/g/fds-smv).  The issue tracker is for reporting bugs.
