### ISSUE TITLE
Seg fault with geom

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8976]
@marcosvanella This is the Askervein case but simplified to 2 meshes.  The geom is located entirely in the bottom mesh.  But it immediately crashes.

[test.fds.txt](https://github.com/firemodels/fds/files/5575829/test.fds.txt)

I run this from a directory at the level of `fds/Validation/Askervein_Hill/Current_Results/test.fds`  Then the bingeom will be accessed from the `cad` repo.

**Comment by marcosvanella** [comment]
yep I could reproduce it. I'm on it.

**Comment by marcosvanella** [comment]
@rmcdermo do an update and try the case now. 
Note it runs slow due to very fine geometry mesh (500K cfaces, ~70 faces per cut-cell).

**Comment by rmcdermo** [comment]
Yep.  Works great.  Thanks!
