### ISSUE TITLE
Fortran runtime error: Specified UNIT in FLUSH is not connected

### ISSUE THREAD

**Issue by Avinashsingh17** [firemodels/fds#8979]
I am having this error while computing the thermal conductivity of Si using d3_tk.x in quantum espresso
At line 181 of file nanoclock.f90 (unit = 6)
Fortran runtime error: Specified UNIT in FLUSH is not connected

Error termination. Backtrace:
#0  0x43dc63 in __nanoclock_MOD_print_percent_wall
        at /home/rajumenr/espresso+d3q_CHECK/D3Q/thermal2/nanoclock.f90:181
#1  0x460a48 in __variational_tk_MOD_compute_a_out
        at /home/rajumenr/espresso+d3q_CHECK/D3Q/thermal2/variational_tk.f90:98
#2  0x403e26 in __thermalk_program_MOD_tk_cg_prec
        at /home/rajumenr/espresso+d3q_CHECK/D3Q/thermal2/PROGRAM_tk.f90:404
#3  0x40c4e0 in thermalk
        at /home/rajumenr/espresso+d3q_CHECK/D3Q/thermal2/PROGRAM_tk.f90:598
#4  0x4033cc in main
        at /home/rajumenr/espresso+d3q_CHECK/D3Q/thermal2/PROGRAM_tk.f90:561

Can someone help me with this?

**Comment by rmcdermo** [comment]
Is this an FDS issue?  Please write a clear description of your problem.

**Comment by rmcdermo** [comment]
I am going to assume you clicked on the wrong repo.
