### ISSUE TITLE
Random memory allocation error

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8980]
Kevin,
This simple test case fails randomly with an "malloc" error after PR #8955 .

```
&HEAD CHID='test'/

&MESH IJK=10,10,10, XB=0,10,0,10,0,10/

&TIME T_END=1./

&SURF ID='invisible', COLOR='BLUE'/ try COLOR='BLUE'
&OBST XB=4,6,4,6,4,6, SURF_ID='invisible'/

&TAIL/
```

**Comment by mcgratta** [comment]
OK, I'll fix.

**Comment by mcgratta** [comment]
I could not make this fail under linux, even though it should have. In any case, I think it should be fixed. Try it.

**Comment by rmcdermo** [comment]
Yep, works.  Thanks!
