### ISSUE TITLE
COLOR='INVISIBLE' not working with GEOM

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#8981]
In this test case, the GEOM keeps the default brown color.  Need to make INVISIBLE an option.  This comes from the CERN Atlas test case.  Note sure if this is FDS or Smokeview related.

```
&HEAD CHID='test'/

&MESH IJK=10,10,10, XB=0,10,0,10,0,10/

&TIME T_END=1./

&SURF ID='invisible', COLOR='INVISIBLE'/ try COLOR='BLUE'
&GEOM XB=4,6,4,6,4,6, SURF_ID='invisible'/

&TAIL/
```

**Comment by gforney** [comment]
try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by rmcdermo** [comment]
Works great!  Thanks!
