### ISSUE TITLE
Porous Media Inputs, does not accept 0 as a vaild input

### ISSUE THREAD

**Issue by uporersith** [firemodels/fds#8982]
Using Version FDS 6.7.3

I would like to model a custom 'Screen' using my own K and Y parameters, So I used equation 17.6, 17.7 and 17.8 and used those K and Y parameters as "PERMEABILITY" and "DRAG_COEFFICIENT" for Porous Media (Eq 17.5) 

However, FDS does not allow me to enter '0' for orientations that are not normal to the screen. 
`&PART ID='SCREEN', DRAG_LAW='POROUS MEDIA', SURF_ID='LOUVER', STATIC=.TRUE.,
      POROUS_VOLUME_FRACTION=0.59,
      DRAG_COEFFICIENT=1.404E-2,0,0
      PERMEABILITY=1.281E-6,0,0
`

I get the error message:
`ERROR: PART line 1.  For POROUS MEDIA must specify all compoents for DRAG_COEFFI
CIENT and PERMIABILTIY. (CHID: 106ANC1TOP)
`
(NOTE: 'PERMIABILTIY' Is misspelled)

If I enter something very close to zero from the Y,Z directions like 1E-12 or something, I get numerical instability when trying to run it. 

What I would like to do is use the Screen Model, but be able to put in my own K and Y parameters, The user's guide does not appear to allow for this.

**Comment by drjfloyd** [comment]
The porous media drag force is mu/K u+ Y/Sqrt(K) u^2.  K = 0 is undefined, and K very small makes the drag very large. Set K, the PERMEABILITY, to be a very large number and Y, the DRAG_COEFFICIENT, to be a very small number. This will make the drag force be negligible.

Thanks for catching the spelling error, I have fixed that.

**Comment by uporersith** [comment]
Thanks, Setting the PERMEABILITY to 1E10 and the DRAG_COEFFICIENT to 1E-10 for the Y and Z orientations worked perfectly.
