### ISSUE TITLE
Use I0 for integer format with output files

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9043]
@marcosvanella @gforney 

I've noticed (especially for geom cases) that the output files can has some very large format slots for integers.  For example, `sem_open_wind_0001_00000011_61.q` and `sem_open_wind_0001_00000011_61.q.bnd`.  Can't we use the I0 format to avoid hardwiring these slot lengths for integers?

**Comment by gforney** [comment]
kevin didn't you address a similar problem earlier.  what Fortran syntax did you use to limit the integer digits output to a string?

**Comment by mcgratta** [comment]
I used `I0` for integers. Not sure about reals.

**Comment by rmcdermo** [comment]
Can't you format the string with I0 before appending it to the filename?

**Comment by mcgratta** [comment]
This might do the trick:
```
print '(a, i0, a, i0, a, f0.2, a, f0.2)',  'i = ', i, '  j = ', j, '  x = ', x, '  y = ', y
Output: i = 5  j = -6  x = 5.00  y = -6.00
Ruler:  1234567890123456789012345678901234
```

**Comment by mcgratta** [comment]
It's funny how the Fortran language people think exactly like us when extending existing features.

**Comment by gforney** [comment]
didn't realize this string was derived from a real.  I have a similar problem in smokeview.  I deal with it by writing the number to a string then stripping leading and trailing 0's and blanks.   I'll look at it.

**Comment by gforney** [comment]
randy, are you sure your cases were run with a version of fds after kevin's file naming changes (according to git blame for the source below- 28 days ago).  It looks like to me that his changes for .q files should should have output a reduced file name size. if your case was run with the source below can you point me to your input files I'll take  a look  

   TT   = T_BEGIN + (T-T_BEGIN)*TIME_SHRINK_FACTOR
   ITM  = INT(TT)
   ITM1 = INT(ABS(TT-ITM)*100)
   WRITE(FN_PL3D(NM),'(A,A,I0,A,I0,A,I0,A)') TRIM(CHID),'_',NM,'_',ITM,'_',ITM1,'.q'
   WRITE(FN_PL3D(NM+NMESHES),'(A,A,I0,A,I0,A,I0,A)') TRIM(CHID),'_',NM,'_',ITM,'_',ITM1,'.q.bnd'

**Comment by rmcdermo** [comment]
Nope not sure.  I'll clean my directory and try again.

**Comment by rmcdermo** [comment]
Oy.  You were right!  Sorry!  Most everything looks good.  The only thing left is bingeom:
```
sem_open_wind_geom_000001.bingeom
```

**Comment by mcgratta** [comment]
I only went through dump.f90 making changes to file names. Not geom.f90

>

**Comment by marcosvanella** [comment]
I'll have a look.

**Comment by marcosvanella** [comment]
There she is, line 44465 geom.f90:
WRITE(ID,'(A,I6.6)') 'geom_',N

**Comment by marcosvanella** [comment]
Update and try it, should work now.

**Comment by rmcdermo** [comment]
Works great.  Thanks!
