### ISSUE TITLE
Numerical instability in ATF cases

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9062]
So far in running the validation cases, only the ATF cases have stopped with a numerical instability, fairly early on. These are `SVLES` cases, which might be a clue as to what is going wrong.
```
ATF_Corridors/Current_Results/ATF_Corridors_050_kW.out:ERROR: Numerical Instability - FDS stopped (CHID: ATF_Corridors_050_kW)
ATF_Corridors/Current_Results/ATF_Corridors_100_kW.out:ERROR: Numerical Instability - FDS stopped (CHID: ATF_Corridors_100_kW)
ATF_Corridors/Current_Results/ATF_Corridors_240_kW.out:ERROR: Numerical Instability - FDS stopped (CHID: ATF_Corridors_240_kW)
ATF_Corridors/Current_Results/ATF_Corridors_250_kW.out:ERROR: Numerical Instability - FDS stopped (CHID: ATF_Corridors_250_kW)
ATF_Corridors/Current_Results/ATF_Corridors_500_kW.out:ERROR: Numerical Instability - FDS stopped (CHID: ATF_Corridors_500_kW)
ATF_Corridors/Current_Results/ATF_Corridors_Mix_kW.out:ERROR: Numerical Instability - FDS stopped (CHID: ATF_Corridors_Mix_kW)
```

**Comment by rmcdermo** [comment]
I ran the cases with VLES and still get the instabilities.  There is something funky going on at the boundary next to the burner.  Probably need a tighter velocity tolerance.
![Uploading Screen Shot 2020-12-19 at 5.14.15 PM.png…]()

**Comment by mcgratta** [comment]
How about the change in the near wall turbulence model? Maybe in a relatively crude model like this it matters.

**Comment by mcgratta** [comment]
I am running the 50 kW case with NEAR_WALL_TURB_MODEL='CONSMAG' and it has passed the point of instability. I'll leave it running in `/home4/mcgratta/firemodels/fds/Validation/ATF_Corridors/Test`

**Comment by rmcdermo** [comment]
The cases are past the point of instability by using a tighter velocity tolerance.   CONSMAG is a red herring.

**Comment by mcgratta** [comment]
For SVLES, `MAX_PRESSURE_ITERATIONS=3`. This is probably too low. I'm going to test going back to 10 and if that works I think the problem is solved.

**Comment by mcgratta** [comment]
My previous comment may not be right. It was noted above that the instability happens even with VLES, which has 10 pressure iterations by default. Just noticed that the instability occurs at the crack under the closed door at the end of the hallway on the first level. We should probably model this crack as a local leak. I'll try it.

**Comment by rmcdermo** [comment]
I tried VLES without modification and got the instability.  I did not notice the crack.  I thought it was sealed at the end and the vectors were part of the instability.  Tightening the tolerance, at any rate, fixed the problem.

Beyond this, I would question whether SVLES is appropriate for this case.  This case is a typical compartment fire, and I think we want to use default schemes here.

**Comment by mcgratta** [comment]
Well, setting `MAX_PRESSURE_ITERATIONS=10` did not work. The case failed a bit later, but failed nonetheless. In the actual experiment, there was a door at the end of the hallway, and I don't think the crack was sealed, nor was the hallway. This was just general drywall construction. In the model, we have a fire at the end of a sealed tunnel, so I added the small hole to represent the crack. This is the "old" way of doing leakage. I'm going to try a local leak and see if that helps. We do tell users not to model leakage by creating a small hole because that can lead to instabilities, and this seems to be a good example of that.

**Comment by mcgratta** [comment]
I replaced the hole in the wall with these lines and things seem to be working nicely. I'll let the run go all the way through and if it's OK, I'll change the files. This is an example of "localized" leakage, where one does not need to be within a pressure zone for it to work. Now that FDS automatically determines pressure zones, we're gravitating to where a user does not need to differentiate local from zonal leakage. It's not quite there yet, but this is a good example of where things are heading.
```
&VENT XB= 17.00, 17.00, 0.40, 1.45, 0.00, 0.10, SURF_ID='GYPSUM BOARD', ID='DOOR CRACK', COLOR='GRAY 80' /
&HVAC ID='DOOR LEAK', TYPE_ID='LEAK', VENT_ID='DOOR CRACK', VENT2_ID='AMBIENT', AREA=0.01 /
```

**Comment by rpeacoc** [comment]
Once you decide on a solution, let me know if it turns out to be leakage related. I’d like to modify the equivalent CFAST cases to be as similar as possible.

**Comment by mcgratta** [comment]
The original cases have a 0.2 m by 0.1 m hole at the base of the wall at the end of the corridor near the fire. This causes numerical fluctuations that lead to instability. I replaced with a leakage vent that has an area of 0.01 m2 to represent a 1 cm wide by 1 m line crack under a closed door.

**Comment by mcgratta** [comment]
I pushed up new input file with the local leakage. We should do this regardless of any other changes we need to make. So far, my one case is running OK.

**Comment by mcgratta** [comment]
I'm rerunning the ATF cases with a local leak vent rather than just a hole in the wall.

**Comment by mcgratta** [comment]
All the cases ran successfully when I changed the hole in the wall to a leakage vent.

**Comment by rmcdermo** [comment]
Can we change to VLES before wrapping this up?

**Comment by mcgratta** [comment]
I'd rather leave it as SVLES so that we have examples of the various modes in the validation suite. I set this to SVLES because the grid is fairly coarse and the case is fairly simple.

**Comment by rmcdermo** [comment]
OK.  Then let's add "Modeling Notes" to that effect in the guide.  I see this as a pretty typical compartment fire scenario.  And I think users should normally be using our default model for situations like this.  Is the grid coarser than D*/dx=10?

**Comment by mcgratta** [comment]
Of the serial cases I'm running on blaze, there are only three that
clipped---ATF, UL_NIST_Vents, LLNL. All three use SVLES and all three are
relatively coarse, most likely D*/dx<10. What do you think is the
cause---SVLES or the coarse grid? Easy to find out. I'll play with it.

>

**Comment by rmcdermo** [comment]
CFL_VELOCITY_NORM=0 is really living on the edge.  It's hard to correct the dispersion error this causes without clipping.

**Comment by mcgratta** [comment]
Do we use it? 
```
[mcgratta@burn Source]$ grep CFL_VELOCITY_NORM *f90
cons.f90:INTEGER :: I_FLUX_LIMITER=SUPERBEE_LIMITER,CFL_VELOCITY_NORM=2
dump.f90:         SELECT CASE (CFL_VELOCITY_NORM)
dump.f90:         UVW = UODX + VODY + WODZ  + ABS(DS(II,JJ,KK)) ! CFL_VELOCITY_NORM=1
dump.f90:         UVW = MAX(UODX,VODY,WODZ)                     ! CFL_VELOCITY_NORM=3
read.f90:                CFL_MAX,CFL_MIN,CFL_VELOCITY_NORM,CHECK_HT,CHECK_MASS_CONSERVE,CHECK_VN, &
read.f90:   CFL_VELOCITY_NORM = 1
read.f90:   CFL_VELOCITY_NORM = 1
read.f90:   !! CFL_VELOCITY_NORM = 2 ! global default
read.f90:   CFL_VELOCITY_NORM = 3
velo.f90:         SELECT CASE (CFL_VELOCITY_NORM)
```

**Comment by rmcdermo** [comment]
Oy... apparently we are using CFL_VELOCITY_NORM=3 for SVLES.  This is even worse.  We really need the divergence term in there to have any chance to avoid clipping.  CASE(3) is only applicable for cold flow cases really.
```
CASE(0) ; UVW = MAX(UODX,VODY,WODZ) + ABS(DS(I,J,K))
CASE(1) ; UVW = UODX + VODY + WODZ  + ABS(DS(I,J,K))
CASE(2) ; UVW = SQRT(UODX**2+VODY**2+WODZ**2) + ABS(DS(I,J,K))
CASE(3) ; UVW = MAX(UODX,VODY,WODZ)
```

**Comment by rmcdermo** [comment]
I suggest we set SVLES to 0 by default.

**Comment by mcgratta** [comment]
Have we ever considered this:
```
UVW = MAX( SQRT(UODX**2+VODY**2+WODZ**2) , ABS(DS(I,J,K)) )
```
Currently, when we sum max(u,v,w) and div, we could be getting up to 3*u/dx. This seems overly restrictive. Certainly it works, but is it cutting the time step too much.

**Comment by rmcdermo** [comment]
We have not.  The rationale for using the some comes from the derivation in "Realizable Mass Density Constraint" section of the the FDS Tech Guide.

You can create a 4th option based on this for testing SVLES if you like, but I do not want to put this on VLES as the default.  I notice many cases that show checkerboarding of temperature with these loose dt constraints, even though they survive and do not go unstable.

**Comment by mcgratta** [comment]
Just musing. I'm not going to make a change like that just yet. It is helpful to set CFL_FILE=T on the dump line and then you can look at the _cfl.csv and track the time step and other quantities at each time step. I look to see if we keep CFL between 0.8 and 1.0. That's the best indicator of a healthy calc.

**Comment by rmcdermo** [comment]
That CFL depends on how is it defined.  You can have a CFL inside your limits, but the temperature error can be significant.

**Comment by rmcdermo** [comment]
Can this case be closed?

**Comment by mcgratta** [comment]
Yes, thanks.
