### ISSUE TITLE
FDS numerical instability later in simulation

### ISSUE THREAD

**Issue by jamesfletcherCFD** [firemodels/fds#9073]
I have been running several simulations and seems to be getting numerical instabilities at some "steady state" stage in the calculation, long after any ventilation or combustion process has developed. 

The model is a building with two entrances, ceiling ventilation vents and a fire which burns to 5.5 MW in 100s. The simulation runs fine up to about 600 s but then crashes after the time step size is reduced to a point where the simulation is barely progressing in ten hours of wall clock time. 

I attach two screen grabs of graphs which are produced from the out file. Also, it should be worth mentioning that the simulation crashes at different later or earlier times depending on the location of the fire within the skylight of the building (train station). 

We have seen many more simulations increasingly fail using FDS so I am assuming that I am maybe doing something wrong with new updates of the code.

![image](https://user-images.githubusercontent.com/76732913/103280957-885d4480-49c9-11eb-9ce1-170e04006a4a.png)

![image](https://user-images.githubusercontent.com/76732913/103281048-c35f7800-49c9-11eb-87f3-3097fa1372f8.png)

FDS CODE EXCLUDING &OBST LINES:

&TIME T_END=1200.0/
&DUMP COLUMN_DUMP_LIMIT=.TRUE., DT_RESTART=100.0, DT_SL3D=0.25/
&MISC TMPA=27.0/

&MESH ID='WEST ENTRANCE', IJK=47,59,24, XB=52.5,76.0,-65.0,-35.5,-5.0,7.0, MPI_PROCESS=0/
&MESH ID='WEST WALKWAY', IJK=47,73,10, XB=52.5,76.0,-35.5,1.0,2.0,7.0, MPI_PROCESS=0/
&MESH ID='SIDE CONCOURSE', IJK=208,40,8, XB=12.0,116.0,1.0,21.0,3.0,7.0, MPI_PROCESS=1/
&MESH ID='SIDE PLATFORM', IJK=255,23,14, XB=0.5,128.0,1.0,12.5,7.0,14.0, MPI_PROCESS=2/
&MESH ID='SKYLIGHT 2', IJK=191,10,7, XB=16.5,112.0,1.0,6.0,14.0,17.5, MPI_PROCESS=2/
&MESH ID='CENTRAL CONCOURSE', IJK=208,41,8, XB=12.0,116.0,21.0,41.5,3.0,7.0, MPI_PROCESS=3/
&MESH ID='CENTRAL PLATFORMS 01-a', IJK=108,46,28, XB=0.5,27.5,19.5,31.0,7.0,14.0, MPI_PROCESS=4/
&MESH ID='CENTRAL PLATFORMS 01-b', IJK=108,46,28, XB=0.5,27.5,31.0,42.5,7.0,14.0, MPI_PROCESS=5/
&MESH ID='CENTRAL PLATFORMS 02-a', IJK=108,46,28, XB=27.5,54.5,19.5,31.0,7.0,14.0, MPI_PROCESS=6/
&MESH ID='CENTRAL PLATFORMS 02-b', IJK=108,46,28, XB=27.5,54.5,31.0,42.5,7.0,14.0, MPI_PROCESS=7/
&MESH ID='CENTRAL PLATFORMS 03-a', IJK=108,46,28, XB=54.5,81.5,19.5,31.0,7.0,14.0, MPI_PROCESS=8/
&MESH ID='CENTRAL PLATFORMS 03-b', IJK=108,46,28, XB=54.5,81.5,31.0,42.5,7.0,14.0, MPI_PROCESS=9/
&MESH ID='CENTRAL PLATFORMS 04-a', IJK=108,46,28, XB=81.5,108.5,19.5,31.0,7.0,14.0, MPI_PROCESS=10/
&MESH ID='CENTRAL PLATFORMS 04-b', IJK=108,46,28, XB=81.5,108.5,31.0,42.5,7.0,14.0, MPI_PROCESS=11/
&MESH ID='CENTRAL PLATFORMS 05-a', IJK=76,46,28, XB=108.5,127.5,19.5,31.0,7.0,14.0, MPI_PROCESS=12/
&MESH ID='CENTRAL PLATFORMS 05-b', IJK=76,46,28, XB=108.5,127.5,31.0,42.5,7.0,14.0, MPI_PROCESS=13/
&MESH ID='SKYLIGHT-a01', IJK=191,11,9, XB=16.5,64.25,26.25,29.0,14.0,16.25, MPI_PROCESS=14/
&MESH ID='SKYLIGHT-a-merged', IJK=382,21,9, XB=16.5,112.0,29.0,34.25,14.0,16.25, MPI_PROCESS=14/
&MESH ID='SKYLIGHT-a05', IJK=152,11,9, XB=74.0,112.0,26.25,29.0,14.0,16.25, MPI_PROCESS=14/
&MESH ID='SKYLIGHT-a02', IJK=39,11,9, XB=64.25,74.0,26.25,29.0,14.0,16.25, MPI_PROCESS=15/
&MESH ID='SKYLIGHT-a04-merged', IJK=382,8,9, XB=16.5,112.0,34.25,36.25,14.0,16.25, MPI_PROCESS=16/
&MESH ID='WALKWAY EAST', IJK=28,74,8, XB=57.5,71.5,41.5,78.5,3.0,7.0, MPI_PROCESS=17/
&MESH ID='EAST ENTRANCE', IJK=77,28,24, XB=42.0,80.5,78.5,92.5,-5.0,7.0, MPI_PROCESS=17/

&REAC ID='Baggage Fire',
      FUEL='REAC_FUEL',
      C=6.3,
      H=7.1,
      O=2.1,
      N=1.0,
      AUTO_IGNITION_TEMPERATURE=0.0,
      CO_YIELD=0.042,
      SOOT_YIELD=0.075,
      HEAT_OF_COMBUSTION=4.36E4/

&PROP ID='Heskestad Ionization01',
      QUANTITY='CHAMBER OBSCURATION',
      SPEC_ID='SOOT',
      LENGTH=1.8/
&PROP ID='Default',
      QUANTITY='LINK TEMPERATURE',
      INITIAL_TEMPERATURE=20.0,
      ACTIVATION_TEMPERATURE=335.0/
&CTRL ID='Central Platform Fans', FUNCTION_TYPE='TIME_DELAY', DELAY=10.0, LATCH=.FALSE., INPUT_ID='latch'/
&CTRL ID='latch', FUNCTION_TYPE='ALL', LATCH=.TRUE., INPUT_ID='greater'/
&CTRL ID='greater', FUNCTION_TYPE='AT_LEAST', N=2, LATCH=.FALSE., INPUT_ID='SD PLAT_CENTR 01','SD PLAT_CENTR 14','SD PLAT_CENTR 15','SD PLAT_CENTR 16','SD PLAT_CENTR 17','SD PLAT_CENTR 18','SD PLAT_CENTR 19','SD PLAT_CENTR 20','SD PLAT_CENTR 21','SD PLAT_CENTR 22','SD PLAT_CENTR 23','SD PLAT_CENTR 24','SD PLAT_CENTR 25','SD PLAT_CENTR 26','SD PLAT_CENTR 27','SD PLAT_CENTR 28','SD PLAT_CENTR 29','SD PLAT_CENTR 30','SD PLAT_CENTR 31','SD PLAT_CENTR 32','SD PLAT_CENTR 33','SD PLAT_CENTR 34','SD PLAT_CENTR 35','SD PLAT_CENTR 36','SD PLAT_CENTR 37','SD PLAT_CENTR 38','SD PLAT_CENTR 39','SD PLAT_CENTR 42','SD PLAT_CENTR 43','SD PLAT_CENTR 44'/
&DEVC ID='FLOW Entrances East', QUANTITY='VOLUME FLOW', XB=61.0,67.0,78.5,78.5,-5.0,-2.0/
&DEVC ID='FLOW Entrances West', QUANTITY='VOLUME FLOW', XB=62.5,66.5,-35.5,-35.5,-5.0,-2.0/
&DEVC ID='TRD-L01', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=68.75,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L02', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.0,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L03', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.25,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L04', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.5,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L05', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.75,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L06', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=70.0,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L07', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=70.25,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L08', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=70.5,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L09', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=70.75,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L10', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=71.0,27.875,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-R01', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=68.25,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R02', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=68.0,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R03', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=68.0,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R04', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=67.75,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R05', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=67.5,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R06', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=67.25,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R07', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=67.0,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R08', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=66.75,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R09', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=66.5,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='TRD-R10', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=66.25,27.875,15.0, ORIENTATION=-1.0,0.0,0.0/
&DEVC ID='SD PLAT_CENTR 28', PROP_ID='Heskestad Ionization01', XYZ=112.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 26', PROP_ID='Heskestad Ionization01', XYZ=94.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 27', PROP_ID='Heskestad Ionization01', XYZ=103.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 25', PROP_ID='Heskestad Ionization01', XYZ=85.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 24', PROP_ID='Heskestad Ionization01', XYZ=76.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 17', PROP_ID='Heskestad Ionization01', XYZ=13.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 23', PROP_ID='Heskestad Ionization01', XYZ=67.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 18', PROP_ID='Heskestad Ionization01', XYZ=22.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 22', PROP_ID='Heskestad Ionization01', XYZ=58.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 21', PROP_ID='Heskestad Ionization01', XYZ=49.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 19', PROP_ID='Heskestad Ionization01', XYZ=31.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 20', PROP_ID='Heskestad Ionization01', XYZ=40.21,40.83,13.9/
&DEVC ID='SD PLAT_CENTR 42', PROP_ID='Heskestad Ionization01', XYZ=92.71,31.83,13.9/
&DEVC ID='SD PLAT_CENTR 01', PROP_ID='Heskestad Ionization01', XYZ=34.21,31.03,13.9/
&DEVC ID='SD PLAT_CENTR 43', PROP_ID='Heskestad Ionization01', XYZ=112.21,31.83,13.9/
&DEVC ID='SD PLAT_CENTR 44', PROP_ID='Heskestad Ionization01', XYZ=121.21,31.83,13.9/
&DEVC ID='SD PLAT_CENTR 31', PROP_ID='Heskestad Ionization01', XYZ=4.21,31.83,13.9/
&DEVC ID='SD PLAT_CENTR 32', PROP_ID='Heskestad Ionization01', XYZ=13.21,31.83,13.9/
&DEVC ID='SD PLAT_CENTR 14', PROP_ID='Heskestad Ionization01', XYZ=49.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 15', PROP_ID='Heskestad Ionization01', XYZ=31.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 16', PROP_ID='Heskestad Ionization01', XYZ=85.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 29', PROP_ID='Heskestad Ionization01', XYZ=40.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 30', PROP_ID='Heskestad Ionization01', XYZ=94.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 33', PROP_ID='Heskestad Ionization01', XYZ=103.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 34', PROP_ID='Heskestad Ionization01', XYZ=112.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 35', PROP_ID='Heskestad Ionization01', XYZ=76.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 36', PROP_ID='Heskestad Ionization01', XYZ=13.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 37', PROP_ID='Heskestad Ionization01', XYZ=67.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 38', PROP_ID='Heskestad Ionization01', XYZ=22.21,22.83,13.9/
&DEVC ID='SD PLAT_CENTR 39', PROP_ID='Heskestad Ionization01', XYZ=58.21,22.83,13.9/
&DEVC ID='FLOW Platform Exhaust 13', QUANTITY='VOLUME FLOW', XB=91.0,93.0,22.0,24.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 14', QUANTITY='VOLUME FLOW', XB=70.0,72.0,22.0,24.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 15', QUANTITY='VOLUME FLOW', XB=28.0,30.0,22.0,24.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 16', QUANTITY='VOLUME FLOW', XB=110.0,112.0,38.0,40.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 17', QUANTITY='VOLUME FLOW', XB=110.0,112.0,22.0,24.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 18', QUANTITY='VOLUME FLOW', XB=11.0,13.0,38.0,40.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 19', QUANTITY='VOLUME FLOW', XB=11.0,13.0,22.0,24.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 20', QUANTITY='VOLUME FLOW', XB=51.0,53.0,22.0,24.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 21', QUANTITY='VOLUME FLOW', XB=51.0,53.0,38.0,40.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 22', QUANTITY='VOLUME FLOW', XB=70.0,72.0,38.0,40.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 23', QUANTITY='VOLUME FLOW', XB=91.0,93.0,38.0,40.0,14.0,14.0/
&DEVC ID='FLOW Platform Exhaust 24', QUANTITY='VOLUME FLOW', XB=30.0,32.0,38.0,40.0,14.0,14.0/
&DEVC ID='HD-R01', PROP_ID='Default', XYZ=68.25,27.875,15.0/
&DEVC ID='HD-L01', PROP_ID='Default', XYZ=70.75,27.875,15.0/
&DEVC ID='HD-L02', PROP_ID='Default', XYZ=71.0,27.875,15.0/
&DEVC ID='HD-L03', PROP_ID='Default', XYZ=71.25,27.875,15.0/
&DEVC ID='HD-L04', PROP_ID='Default', XYZ=71.5,27.875,15.0/
&DEVC ID='HD-L05', PROP_ID='Default', XYZ=71.75,27.875,15.0/
&DEVC ID='HD-L06', PROP_ID='Default', XYZ=72.0,27.875,15.0/
&DEVC ID='HD-L07', PROP_ID='Default', XYZ=72.25,27.875,15.0/
&DEVC ID='HD-L08', PROP_ID='Default', XYZ=72.5,27.875,15.0/
&DEVC ID='HD-L09', PROP_ID='Default', XYZ=72.75,27.875,15.0/
&DEVC ID='HD-L10', PROP_ID='Default', XYZ=73.0,27.875,15.0/
&DEVC ID='HD-R02', PROP_ID='Default', XYZ=68.0,27.875,15.0/
&DEVC ID='HD-R03', PROP_ID='Default', XYZ=68.0,27.875,15.0/
&DEVC ID='HD-R04', PROP_ID='Default', XYZ=67.75,27.875,15.0/
&DEVC ID='HD-R05', PROP_ID='Default', XYZ=67.5,27.875,15.0/
&DEVC ID='HD-R06', PROP_ID='Default', XYZ=67.25,27.875,15.0/
&DEVC ID='HD-R07', PROP_ID='Default', XYZ=67.0,27.875,15.0/
&DEVC ID='HD-R08', PROP_ID='Default', XYZ=66.75,27.875,15.0/
&DEVC ID='HD-R09', PROP_ID='Default', XYZ=66.5,27.875,15.0/
&DEVC ID='HD-R10', PROP_ID='Default', XYZ=66.25,27.875,15.0/
&DEVC ID='TRD-L11', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,26.75,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L12', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,27.0,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L13', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,27.25,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L14', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,27.5,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L15', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,27.75,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L16', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,28.0,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L17', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,28.25,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L18', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,28.5,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L19', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,28.75,15.0, ORIENTATION=1.0,0.0,0.0/
&DEVC ID='TRD-L20', QUANTITY='RADIATIVE HEAT FLUX GAS', XYZ=69.875,29.0,15.0, ORIENTATION=1.0,0.0,0.0/

&SURF ID='CEILINGS',
      COLOR='YELLOW'/
&SURF ID='INTERNAL GLAZING',
      RGB=51,153,255/
&SURF ID='Global',
      RGB=204,102,102/
&SURF ID='Global03',
      RGB=255,127,127/
&SURF ID='PLATFORM FLOOR',
      RGB=102,0,204/
&SURF ID='Global07',
      RGB=255,191,127/
&SURF ID='ADIABATIC',
      COLOR='GRAY 80',
      ADIABATIC=.TRUE./
&SURF ID='Global08',
      RGB=127,255,127/
&SURF ID='Global12',
      RGB=102,204,153/
&SURF ID='Glass roof',
      RGB=146,202,166,
      TRANSPARENCY=0.294118,
      NET_HEAT_FLUX=0.026/
&SURF ID='Fire 01',
      COLOR='RED',
      HRRPUA=1571.42,
      RAMP_Q='Fire 01_RAMP_Q'/
&RAMP ID='Fire 01_RAMP_Q', T=0.0, F=0.0/
&RAMP ID='Fire 01_RAMP_Q', T=110.0, F=1.0/
&RAMP ID='Fire 01_RAMP_Q', T=2000.0, F=1.0/
&SURF ID='Glass walls',
      RGB=146,202,166,
      TRANSPARENCY=0.203922,
      NET_HEAT_FLUX=0.035/
&SURF ID='Platform Exhaust central',
      RGB=0,82,0,
      VOLUME_FLOW=5.0,
      TAU_V=-30.0/

&VENT ID='OPEN West', SURF_ID='OPEN', XB=62.5,66.5,-35.5,-35.5,-5.0,-2.0, TMP_EXTERIOR=46.0/ 
&VENT ID='Open EAST', SURF_ID='OPEN', XB=61.0,67.0,78.5,78.5,-5.0,-2.0, TMP_EXTERIOR=46.0/ 

&SLCF QUANTITY='TEMPERATURE', PBY=27.0/
&SLCF QUANTITY='VELOCITY', PBY=27.0/
&SLCF QUANTITY='VISIBILITY', PBY=27.0/
&SLCF QUANTITY='MASS FRACTION', SPEC_ID='CARBON MONOXIDE', PBZ=12.0/
&SLCF QUANTITY='MASS FRACTION', SPEC_ID='CARBON MONOXIDE', PBY=4.5/
&SLCF QUANTITY='MASS FRACTION', SPEC_ID='CARBON MONOXIDE', PBZ=5.0/
&SLCF QUANTITY='MASS FRACTION', SPEC_ID='CARBON MONOXIDE', PBX=64.0/
&SLCF QUANTITY='MASS FRACTION', SPEC_ID='CARBON MONOXIDE', PBY=27.0/
&SLCF QUANTITY='VISIBILITY', PBZ=12.0/
&SLCF QUANTITY='VELOCITY', PBZ=12.0/
&SLCF QUANTITY='TEMPERATURE', PBZ=12.0/
&SLCF QUANTITY='VISIBILITY', PBZ=5.0/
&SLCF QUANTITY='VELOCITY', PBZ=5.0/
&SLCF QUANTITY='TEMPERATURE', PBZ=5.0/
&SLCF QUANTITY='VISIBILITY', PBX=64.0/
&SLCF QUANTITY='TEMPERATURE', PBX=64.0/
&SLCF QUANTITY='VELOCITY', PBX=64.0/
&SLCF QUANTITY='TEMPERATURE', PBY=4.5/
&SLCF QUANTITY='VELOCITY', PBY=4.5/
&SLCF QUANTITY='VISIBILITY', PBY=4.5/
&SLCF QUANTITY='TEMPERATURE', PBZ=14.5/
&SLCF QUANTITY='VISIBILITY', PBZ=12.5/

&TAIL /

many thanks in advance!

**Comment by rmcdermo** [comment]
We'll have a look.

**Comment by rmcdermo** [comment]
Please send the input file with OBST lines.

If that is a problem, then try last night's build to see if this helps.  To get the the nightly builds, see the link at the top of [FDS Release Notes](https://github.com/firemodels/fds/wiki/FDS-Release-Notes).

**Comment by jamesfletcherCFD** [comment]
Thank you please see the link, I think maybe the github page only allows a certain number of characters for the comment?

https://we.tl/t-iq57qAGGo6

**Comment by mcgratta** [comment]
How big is this file? Just save it as a text file and attach the text file. Your link is to a site that wants to send me ads and cookies.

**Comment by jamesfletcherCFD** [comment]
[FDS-01-22.txt](https://github.com/firemodels/fds/files/5754452/FDS-01-22.txt)

Attached as a txt file thanks!

**Comment by mcgratta** [comment]
I am running the case now. One thing to consider is that for very large cases like this, instabilities can form in regions of the domain that are sealed, but can still heat up due to conduction of heat through the walls. In older versions of FDS, one would have to designate such regions as ZONEs. The latest version of FDS should automatically detect such regions, but with a case as complex as this, it is hard to say. We'll see.

**Comment by rmcdermo** [comment]
I think there is something amiss here.  The calc is running very slowly with the latest code.  The time step is being driven down to DT= 0.603E-04 s and there are still tons of CLIP warnings on MESH 20.

**Comment by mcgratta** [comment]
The case failed at
```
WARNING: Minimum density,    0.117 kg/m3, clipped in Mesh 20
 Time Step:   2516, Simulation Time:     81.38 s

ERROR: Numerical Instability - FDS stopped (CHID: test)
```
I'll see if I can figure out what the problem is. These are the final stats from Mesh 20
```
       Mesh   20
       Max CFL number:  0.18+309 at (  17,   7,   5)
       Max divergence:  0.13E+02 at (  17,   7,   5)
       Min divergence: -0.69E+01 at (  17,   8,   5)
       Max VN number:   0.22E-03 at (  18,   7,   6)
       No. of Lagrangian Particles:            26
       Total Heat Release Rate:           4331.448 kW
       Radiation Loss to Boundaries:     -1437.506 kW
```

**Comment by mcgratta** [comment]
I haven't figured out what is wrong, but here's a few observations:

1. You have two OPEN boundaries to this complex, both at far ends. This might cause problems for the pressure solver. You might want to consider leakage or other OPEN boundaries. It is hard to believe a space like this would be perfectly sealed.
2. I would not use ADIABATIC=T. It is not realistic and sometimes can cause stability problems because of how it interacts with the radiation solver. There is no such thing as an ADIABATIC wall. We use this feature solely for verification and diagnostics.

**Comment by mcgratta** [comment]
Also, I am running the case with meshes 7-21 only, and an OPEN boundary condition at z=7. I want to see if there is something about the fire and its environs that is causing the problem, or whether this is some sort of global pressure problem.

**Comment by jamesfletcherCFD** [comment]
Thank you for the efforts in looking into this. I have made some changes to the model including ADIABATIC=.FALSE. and modifying the mesh around the fire so the boundaries of the mesh are further away. I have also move the fire away from the wall entirely by shifting it in the y direction. The heat build up seems to occur suddenly behind the fire block in between the obstructions however this is probably just a symptom rather than causation of the numerical problem. I'll respond back with the results of the modelling when it reaches the instability stage.

One thing that I noticed is that this instability occurred much sooner when the entire skylight area was modelled with 0.125 m cells which is to be expected from finer meshing. It may help to determine that the instability source begins there.

In terms of OPEN boundaries, I might try to have a leakage factor and increase the ventilation flow rate to compensate, this is very useful advice going forward as I believe similar issues have happened on such large models as this.

**Comment by jamesfletcherCFD** [comment]
Having ran the simulation with the above changes it seems like the numerical instability has been resolved. The simulation ran up to the full 1200 s and the time step fluctuations as shown in the graph. It is hard to know which change has helped this to run however I can revert those changes individually to pinpoint the cause once I have ran the additional cases I need for the study and will respond back to the thread 
![image](https://user-images.githubusercontent.com/76732913/103459060-4eab7700-4d04-11eb-831f-3457ea44c6a5.png)

**Comment by mcgratta** [comment]
Good to hear. In complicated cases like this, it's a good idea to add
slices of PRESSURE to monitor large swings in pressure due to the small
number of OPEN boundaries. Also, add some BNDF lines of 'WALL TEMPERATURE'
and 'GAUGE HEAT FLUX' to see if the boundary condition ADIABATIC=T is a
problem. But then again, just don't use ADIABATIC as a BC.

>

**Comment by mcgratta** [comment]
One issue I have found in this case after eliminating all meshes except for mesh 20 (where the fire is) is that you have hollow INERT boxes (colored WHITE) just above the fire. These should play no role in the simulation, but because of small numerical errors at the surface of the boxes, the pressure, temperature and density inside do not remain ambient and over time can build up to cause problems like instabilities. You can try two things to fix this:
1. Avoid creating void spaces that play no role in the simulation. Solid OBSTructions are preferred.
2. Add a line like
```
&PRES MAX_PRESSURE_ITERATIONS=50, VELOCITY_TOLERANCE=0.05 /
```
This will lessen the numerical error at the hollow boxes, but will not eliminate it.

**Comment by mcgratta** [comment]
[test_20_7.txt](https://github.com/firemodels/fds/files/5771764/test_20_7.txt)
Take a look at this case. It is a much simplified version of your original case, but it points out at least one of the problems. It is a single mesh case (mesh 20 of the original) and it includes the fire and a small, sealed box colored white above it. After about 600 s, the density inside the box drops to about 0.1 kg/m3, which is the lower limit. This should not happen because the box boundaries are INERT and there should be no mass or heat transfer across the boundary. However, the small error at the thin boundaries build up and cause problems. This is why you should avoid these kinds of void spaces in your set up.

**Comment by jamesfletcherCFD** [comment]
Many thanks for your help
