### ISSUE TITLE
Hook up DEVC for CFACES

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9078]
@marcosvanella It does not look like this is connected yet.  Am I right?

**Comment by marcosvanella** [comment]
Should be hooked. See GET_CFACE_INDEX routine called from INITIALIZE_DEVICES. Looks for the closest CFACE centroid to the DEVC location in a 3x3x3 cell region.

**Comment by rmcdermo** [comment]
OK, thanks.  Do you know of a case that uses it?

**Comment by marcosvanella** [comment]
Randy, look for 'WALL-T1' in the Complex_Geometry/sphere_propane_demo.fds case. Also, in Kevins UWO_Wind_Tunnel cases with geometries.

**Comment by rmcdermo** [comment]
Ok, thanks.  Looks Iike `IOR=0` is used.  Well, we will have to document all this, but that is something under a larger umbrella.  I'll close.
