### ISSUE TITLE
FDS 6.7.5: Delay timer device

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#9079]
I'm trying to upgrade to FDS 6.7.5 and noticed an error when running the simplified version below. The input below works with FDS6.7.0. If you remove the device timer the case runs with FDS 6.7.5. 
Could you please advise? Thanks,

```
&HEAD CHID='test'/
&TIME T_END=10.0/
&DUMP NFRAMES=10/

&MESH ID='MESH0', IJK=32,132,34, XB=-23.8,-20.6,-10.6,2.6,0.0,3.4/


&DEVC ID='TIMER->OUT', QUANTITY='TIME', XYZ=-23.8,-10.6,0.0, SETPOINT=10.0/


&OBST ID='Obstruction', XB=-22.6,-21.8,-4.1,-3.8,3.0,3.2, RGB=255,110,0, SURF_ID='INERT'/ 
&OBST ID='Obstruction', XB=-22.6,-21.8,-3.8,-2.8,3.0,3.3, RGB=255,110,0, SURF_ID='INERT'/

&VENT ID='IN15', SURF_ID='HVAC', XB=-22.3,-22.0,-3.3,-3.0,3.0,3.0, COLOR='GREEN', RADIUS=0.133, XYZ=-22.15,-3.15,3.0, DEVC_ID='TIMER->OUT'/ 
&VENT ID='OUT15', SURF_ID='HVAC', XB=-22.6,-21.8,-4.1,-4.1,3.0,3.2, COLOR='MAGENTA', UVW=-1.760797E-16,-1.4378,-0.253/ 

&HVAC ID='50N', TYPE_ID='DUCT', AREA=0.16, PERIMETER=2.0, FAN_ID='Induction Fan', LOSS=1.0, NODE_ID='IN15','OUT15', ROUGHNESS=1.0E-3, LENGTH=0.956556/
&HVAC ID='IN15', TYPE_ID='NODE', DUCT_ID='50N', VENT_ID='IN15', LOSS=1.0,1.0/
&HVAC ID='OUT15', TYPE_ID='NODE', DUCT_ID='50N', VENT_ID='OUT15', LOSS=1.0,1.0/
&HVAC ID='Induction Fan', TYPE_ID='FAN', VOLUME_FLOW=1.46/
```

**Comment by mcgratta** [comment]
This is probably a new error message saying that you cannot assign a DEVC_ID to a VENT with HVAC.

**Comment by drjfloyd** [comment]
Yes, the HVAC model relies on VENTs always being present. If you need your current HVAC system to not have flow for some period of time, split it into two ducts. In one duct have the fan, in one duct have a damper, and give each a device. You will will need a second device that has the opposite state (a FALSE damper is open and a TRUE fan is on).

**Comment by sbenkorichi** [comment]
Thanks, both,
I've looked in the example HVAC_damper and noticed the devc id is put on the HVAC line. 
It seems working now.  I'm closing.
