### ISSUE TITLE
Wildland fires levelset method gets wrong WIND direction

### ISSUE THREAD

**Issue by emanuelegissi** [firemodels/fds#9080]
I attach a very simple case showing the problem: a flat terrain, with uniform boundary condition, ignition at the center, one mesh, very short running time. The blue spot on the NE corner (water) is only used as a reference for visualization in Smokeview.

If the wind comes from the S-W sector, the levelset method correctly takes it into account: the fire spreads from the center of the terrain towards the opposite bearing. When wind come from any other direction the spread direction of the fire is not correct.

The attached simple case contains commented WIND lines.
[flat_wind.fds.txt](https://github.com/firemodels/fds/files/5760162/flat_wind.fds.txt)

**Comment by emanuelegissi** [comment]
I forgot to add I am using FDS nightly builds.

**Comment by mcgratta** [comment]
This bug was introduced a few months ago. Should be working now.

**Comment by emanuelegissi** [comment]
Ok, I'll check it out soon

**Comment by emanuelegissi** [comment]
Yes, I confirm current git works. Thanks again, closing.
