### ISSUE TITLE
Windows 10 sometimes totally freezes after running a FDS job

### ISSUE THREAD

**Issue by Aymericrag** [firemodels/fds#9083]
Hi everyone.

I use Pyrosim 2020.5.1118 (French version by 1point2) with FDS 6.7.5 and I have an issue that makes computers crashing using "Run FDS Parallel" or “Cluster execution” sometimes immediately sometimes after few minutes or hours.
I use 3 different computers, one is running fine (Windows 10 -2004) the others crash often (Windows 10 – 20H2). If it crash the entire Windows is not respondning I must restart the computer.
After restartint, I ran again the same job and sometimes it works sometimes not... so it's not about the job nor the memory, I have about 40Gb free from 64Gb.

We had some major Windows 10  (20H2) update on the 2 computers on which the issues occur and I did not install it on the 3rd one (Still in Windows 10 - 2004 version).

Is someone has the same issue ? Is it linked to Windows update ? Or Pyrosim update ?

**Comment by mcgratta** [comment]
Can you open up the CMDfds window and type 
```
fds_local -p N -o M jobname.fds
```
where N is the number of meshes and M is the number of OpenMP threads (set to 1 for this experiment).

**Comment by Aymericrag** [comment]
Hi Kevin,

Thanks for answering. I've just run a job witch crashed this night after 491s of completion with OpenMP thread=1. I let you know if it runs well or crashes
Regards
Aymeric

**Comment by Aymericrag** [comment]
Kevin,

The calculation ends without any problem with OpenMP=1

**Comment by mcgratta** [comment]
What happens if you set the number of OpenMP threads to 2? If that is successful, you should contact Thunderhead because there might be a conflict between PyroSim and the installed version of FDS.
