### ISSUE TITLE
WALE vs CONSMAG wall turbulence models

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9084]
[test_20_5.txt](https://github.com/firemodels/fds/files/5765867/test_20_5.txt)

This is a simplified version of the case in Issue #9073, but it is unrelated to that issue because it involves the newly enacted WALE near-wall turbulence model. Run the case with the old and new `NEAR_WALL_TURBULENCE_MODEL` and you'll see that the WALE model produces more hits of the lower density limit.

**Comment by rmcdermo** [comment]
OK, I will look at it.

**Comment by rmcdermo** [comment]
This is one of those cases that needs `CHECK_HT=T`.  Then there are not clip warnings in either case.  When you specify fluxes on boundaries you need to think about adding this check.  Of course, it is a time step hit.  But that is life with an explicit code.  Else, we need to have some kind of means of not obeying the specified flux if DT is too low.

I know you don't like `CHECK_HT`, but it is important that the near wall model is consistent across our simulation modes as we work toward better flame spread models.  When we use `VAN DRIEST` the viscosity in the first layer of wall cells is too high---there is a noticeable jump from the bulk value, and the value at the wall is zero by definition (for turbulent).

**Comment by mcgratta** [comment]
I think there is a bigger issue here, and it may only be partially related
to the wall turb model. If you look at slices of HRRPUV, DENSITY, and
DIVERGENCE, you can see that these downward plunges in density are caused
by large local divergence, which is caused by large local HRRPUV, which is
caused by small tau (mixing time), which is related to the local MU. Yes,
lowering the time step is always going to help because

d rho = dt(-u dot grad rho - rho div)

I think we need to look at div, and/or Q and tau. This used to be solved,
crudely, by just clipping Q. I think there might be a smarter way to do
this, like looking at physically-based limits of tau. 99% of FDS cases have
specified mass fluxes at the boundary, but I don't think that this boundary
condition is the whole story. I think there is something about the
randomness of these spikes that we should be able to deal with rather than
just lowering dt.

>

**Comment by mcgratta** [comment]
As to WALE vs CONSMAG, I guess that the former is less dampening than the
latter, which might affect MU, tau and Q in the first grid cell off the
wall. That's no reason to revert to CONSMAG, but we should understand how
it affects things.

>

**Comment by rmcdermo** [comment]
Small mixing time comes from large MU, which is opposite what WALE gives you (on average) compared to VAN DRIEST/CONSMAG.

In this case, and in others, we get forced into this lowering of DT (if we want to obey a CFL) by trying to give the user what they ask for, namely a specified heat flux boundary.  This heat flux it not constant in reality.  I think the large Q then results from DT being too large, but it's chicken and egg.   The TAU limit for finite rate chemistry is on the order of 1e-4 s.  We currently leave this as 1e-10 s by default.  Perhaps that might help.

**Comment by mcgratta** [comment]
[test_20_6.txt](https://github.com/firemodels/fds/files/5766398/test_20_6.txt)
In this variant of the case, I set HTC=0 at all boundaries, nullifying the effect of `CHECK_HT`. The minimum density clipping still occurs. I think `CHECK_HT` works by reducing the time step when a gas cell with large temperature and low density abuts the cold boundary. But I think that `CHECK_HT` just suppresses the symptoms without curing the disease. I think the real problem is, and it's been around forever, the excessive fluctuation of Q. Like I said, we used to just take a hammer to it, but I'm thinking of ways to be smarter about it.

**Comment by rmcdermo** [comment]
I set TAU_CHEM=1.E-4 s and it did not solve the problem.  But using the default code does, that is, remove your CLIP line.  Sure, this reduces DT here and there, but DT recovers and you will see your CFL is "healthy", as you say, without CHECK_HT.  So, I'm not sure what the problem is.  The CLIP DT routine is not killing the time step.

**Comment by mcgratta** [comment]
I set the CLIP line because the original case contained small pressure zones that had density going to small values permanently. I left the CLIP in place to look more closely at these excursions. I'm thinking of ways to reduce the number of times that the DT_CLIP machinery has to kick in. The small pressure zone problem still exists in that original case, but I took them out of the simplified case.

**Comment by mcgratta** [comment]
The machinery to limit the time step based on undershoots in density appears to be working. One thing to note is that when I monitor the minimum DENSITY every time step, I see that only RHO_S, not RHO, hits the minimum limit. RHO never gets below about 0.2 kg/m3. That suggests that we need to lower the time step to avoid hitting min RHO_S.
