### ISSUE TITLE
Allow sprinklers and nozzles to live near mesh boundaries

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9103]
Currently, a sprinkler's initial spray "footprint" must be contained within one mesh. Remove this restriction.

**Comment by mcgratta** [comment]
Just an update on progress. I added an MPI exchange of particle info just after the particles are inserted so that particles that are inserted into mesh N by a sprinkler in mesh M are properly turned over to mesh N via the ORPHAN-ADOPT framework. That worked fine, but then when I put the sprinkler at the corner of 4 meshes, I noticed that the diagonal meshes do not currently communicate. Only when two meshes have abutting grid cells is there a communication set up. So I have to expand the communication scheme to allow diagonal meshes to communicate. This might come in handy for GEOM and other things.

**Comment by marcosvanella** [comment]
Hi Kevin, here is where the neighboring mesh construct comes handy. Diagonal meshes should be within the neighboring mesh set.

**Comment by mcgratta** [comment]
Exactly. In my working version, that is what I doing -- looping over N_NEIGHBORING_MESHES. But that means that I have to change the logic within MESH_EXCHANGE.

**Comment by SusanKilian** [comment]
Thanks for the update. This sounds very promising to me because the availability of diagonal communication would also be extremely useful for the further development of the McKeeney-Greengard-Mayo method. Please keep me posted here on any new developments.

**Comment by mcgratta** [comment]
Things should work now. Sprinklers and nozzles should be able to sit anywhere. I split the verification case `Sprinklers_and_Sprays/bucket_test_1.fds` into four meshes and it works. I also ran the verification suite and there are no errors.

**Comment by rmcdermo** [comment]
Seems to be working well.  Thanks!
