### ISSUE TITLE
File Access Error when T_BEGIN=-10.0

### ISSUE THREAD

**Issue by bwklein** [firemodels/fds#9108]
Please see the attached example, where I see a .q file access error from FDS when running a model with a negative start time.
This happens when running through PyroSim and when running FDS directly from the terminal.

Revision         : FDS6.7.5-0-g71f025606-release
Revision Date    : Thu Aug 20 16:19:01 2020 -0400

```
forrtl: The process cannot access the file because it is being used by another process.
forrtl: severe (38): error during write, unit 16, file C:\Users\bryan\Downloads\negative_time\negative_time_0001_-0000008_88.q
```

![image](https://user-images.githubusercontent.com/12104446/104631794-99f14e00-5651-11eb-8e31-ea5505f643ec.png)

[negative_time.zip](https://github.com/firemodels/fds/files/5816231/negative_time.zip)

**Comment by drjfloyd** [comment]
This is working with the current source. There was a recent commit that reformatted file names to reduce the length (getting rid of leading zeroes). My guess is that fixed this issue.

**Comment by sbenkorichi** [comment]
Hi Bryan, I just tested this in the latest bundle release (Windows). Doing some checks, and I think this is due to the WRITE_XYZ =T parameter you've included. If you remove it or turn it to F, it should run. 
`&DUMP DT_PL3D=1.0, DT_RESTART=300.0, DT_SL3D=0.25,/`
