### ISSUE TITLE
Bug: inner energy reset with GEOM on restart

### ISSUE THREAD

**Issue by jet5678** [firemodels/fds#9112]
Hello, 

FDS Version: 6.7.5
MPI Version: 5.4.7
Reproduceable: yes
Functionally critical: yes

I have noticed that there is a problem with the restart when GEOMs are used. It seems to me that the inner energy is not saved during a restart. I have attached an example with plots of the temperatures inside and outside of the sample. This does not concern OBST objects.
As the plots clearly show, the restart was at 774s.

[test_geom.txt](https://github.com/firemodels/fds/files/5820863/test_geom.txt)
[Temperaturverlauf_geom_no_restart-subplots.pdf](https://github.com/firemodels/fds/files/5820864/Temperaturverlauf_geom_no_restart-subplots.pdf)
[Temperaturverlauf_geom_restart-subplots.pdf](https://github.com/firemodels/fds/files/5820865/Temperaturverlauf_geom_restart-subplots.pdf)

With best regards

**Comment by rmcdermo** [comment]
@jet5678 Appreciate the report!  We will get right on it.

**Comment by marcosvanella** [comment]
Thank you jet, we'll have a look.

**Comment by rmcdermo** [comment]
Should be fixed with PR #9113 .  Please confirm.

**Comment by jet5678** [comment]
Hello, 
I have now also been able to check the fix, it now seems to work as it should. Thank you for the quick intervention.

With best regards
