### ISSUE TITLE
fds command shell is missing

### ISSUE THREAD

**Issue by studenttubs** [firemodels/fds#9151]
Hey guys

I'm having some issues installing fds. I am using an asus tuf gaming, with an AMD ryzen7 and nividia GEFORCE GTx.
For a course in my study i have to use fds and cfast. the last time I installed everything worked. 
I downloaded the latest version and installed them as admin, I controlled the installation and got no erros. the programs installed correctly at first sign. The only thing missing is my command shell for fds. (cmdfds) 
hope someone can help me. Its urgend
stay safe and best regards
Johanna

**Comment by rmcdermo** [comment]
Can you click "Start >> Run" and find cmdfds?

**Comment by studenttubs** [comment]
> 
> 
> Can you click "Start >> Run" and find cmdfds?
thanks for your answer :) 
tried, but it wasn't found.

**Comment by rmcdermo** [comment]
Please give a few screen shots of your installation process.  We are really stabbing in the dark here.

**Comment by mcgratta** [comment]
Does this computer come with Windows installed, or did you install it?

>

**Comment by studenttubs** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/78085211/106002622-a5149700-60b1-11eb-99ae-680420f29051.png)
![Screenshot (4)](https://user-images.githubusercontent.com/78085211/106002657-ae056880-60b1-11eb-9a1a-5236fc610b05.png)
![Screenshot (5)](https://user-images.githubusercontent.com/78085211/106002687-b65da380-60b1-11eb-9371-de5fdb51e7b7.png)
![Screenshot (6)](https://user-images.githubusercontent.com/78085211/106002729-c1b0cf00-60b1-11eb-8a67-e3d04ad460b7.png)
![Screenshot (7)](https://user-images.githubusercontent.com/78085211/106002763-caa1a080-60b1-11eb-8667-b236d6400345.png)
![Screenshot (8)](https://user-images.githubusercontent.com/78085211/106002795-d3927200-60b1-11eb-8478-96e7bd2ea960.png)
![Screenshot (9)](https://user-images.githubusercontent.com/78085211/106002833-df7e3400-60b1-11eb-886d-87adbb878e47.png)
![Screenshot (10)](https://user-images.githubusercontent.com/78085211/106002847-e311bb00-60b1-11eb-8fbe-d2234e60ed17.png)
![Uploading Screenshot (11).png…]()

**Comment by studenttubs** [comment]
> 
> Does this computer come with Windows installed, or did you install it?
> […](#)

come with installed

**Comment by studenttubs** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/78085211/106003059-1e13ee80-60b2-11eb-91f5-31766444f4aa.png)
sorry, seems like the first upload of this picture failed

**Comment by rmcdermo** [comment]
Looks like you are trying 6.7.1.  Does 6.7.5 work?

**Comment by studenttubs** [comment]
no, i tried both. Just in case

**Comment by gforney** [comment]
first try as randy suggested to install the latest version of fds.  a few other things to try
1. in a command shell type:
cmd /k fdsinit

that is all that CMDfds is doing.  


2.  on your desktop try right clicking with the mouse and select the Refresh menu item.  does CMDfds show up
3.  from your home directory ( %userprofile%) cd Desktop and type: 
 dir CMDfds.lnk 
do you see anything

**Comment by gforney** [comment]
also type
where fds
where smokeview

do you see anything

**Comment by studenttubs** [comment]
cmd /k fdsinit so if I use this I can run fds files?
![Screenshot (12)](https://user-images.githubusercontent.com/78085211/106005793-db074a80-60b4-11eb-91ad-5c39665082c0.png)
![Screenshot (13)](https://user-images.githubusercontent.com/78085211/106005796-db9fe100-60b4-11eb-91ce-3c4c0f2f5d66.png)
![Screenshot (14)](https://user-images.githubusercontent.com/78085211/106005800-dc387780-60b4-11eb-9e15-f5ca3dc57855.png)
so the dirCMDfds.lnk said there was nothing found

**Comment by gforney** [comment]
yes since fds, smokeview and fdsinit.bat are in your path you can run fds after first typing
cmd /k fdsinit 
in a command shell

let's make sure you have a home directory.  in your home directory, c:\Users\Johan, type:
dir Desktop

**Comment by studenttubs** [comment]
i can only loist the content if i am changing to onedrive first
![Screenshot (16)](https://user-images.githubusercontent.com/78085211/106017985-5c64da00-60c1-11eb-98bc-e057325c650c.png)
![Screenshot (17)](https://user-images.githubusercontent.com/78085211/106018005-61298e00-60c1-11eb-89d6-77b7d857e94a.png)

**Comment by gforney** [comment]
ok, thanks.  I'll put in some error checking in the bundle script to see what happened to the file.   were you able to run fds using the work around I suggested?

**Comment by studenttubs** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/78085211/106021799-756f8a00-60c5-11eb-852c-bc6646c7f26f.png)
yea it did run successfully. I hope I will fix the problem, but at least I can do my academic achievments now. Thanks a lot, you really helped me :)

**Comment by Fireman114** [comment]
![ScreenShot_20220513220452](https://user-images.githubusercontent.com/105516718/168373411-a45954ad-e721-4afb-af79-7358bd7a63fc.png)
Help me! Please!

**Comment by gforney** [comment]
looks like you are using tthe "power shell" not the command shell .  to make sure you are using the command shell click on the start menu and type com .  you should see "command prompt App" come up.  select this app then cd into directory where you put the fds installer and try again

**Comment by Fireman114** [comment]
Sorry! I don't understand how "then cd..." is supposed to do! Do you use
Ultraviewer? Can you help me install this FDS program? I am in dire need of
it for my PhD thesis. Looking forward to your help!
--
*Best wishes,*
----------------------------------------------
Lê Việt Hải
*Lecturer: *K3 - T34
*Mobile:* (+ 84) 97 833 3988 / (+7) 929 662 8999
*Gmail:* ***@***.*** ***@***.***>;
***@***.***


Vào Th 6, 13 thg 5, 2022 vào lúc 22:36 gforney ***@***.***>
đã viết:
