### ISSUE TITLE
BLOCK_WIND not applied to HOLE in MEAN_FORCING

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#9162]
In this example case, MEAN_FORCING is turned on, but then disabled everywhere in the domain using the HOLE functionality. However, the flow is still forced (the hole is ignored). 
This can be confirmed by the fact that the hole region should have a zero initial velocity, following the code around line 405 of init.f90

I think this can be traced back to the fact that the OBST (and HOLE) lines are evaluated before the WIND lines in read.f90. So the wind-blocked regions are assigned before the MEAN_FORCING_CELL array is actually allocated, and the information is lost.

As a separate issue (I can make a separate feature request), I think it could be useful to make the zero-initialization of wind-blocked regions optional (line 405 in read.f90). 
This way, the wind can be initialized to the same value everywhere, but only forced in certain regions. For example, if you are concerned about the forcing affecting flow features in a key part of the domain.

[mean_forcing_hole.txt](https://github.com/firemodels/fds/files/5894477/mean_forcing_hole.txt)

**Comment by rmcdermo** [comment]
@emuell02 Thanks, we'll take a look.  However, are you aware that MEAN_FORCING is deprecated?  The WIND line now sets up OPEN boundaries that maintain the external wind field, and no forcing internal to the domain takes place.  We are only maintaining MEAN_FORCING as a convenient way to specify a mean pressure gradient in the domain, akin to FORCE_VECTOR.

So, I will work on the hole problem.  But please see if your application can avoid MEAN_FORCING altogether.  Thanks

**Comment by rmcdermo** [comment]
@emuell02 This case is not set up to do what the BLOCK_WIND feature was intended to do.  You need some kind of structure, made of OBST, to actually block the flow.  HOLE with BLOCK_WIND does not force the flow the 0, it simply does not apply mean forcing.  To preserve divergence, the flow field will have a velocity.  Does that make sense?

**Comment by ericvmueller** [comment]
Thanks for taking a look, Randy. I wasn't aware that it needed to be linked to an OBST. However, my aim was not to force the flow to zero, rather to just turn off the mean forcing, as you say.

I wasn't aware that MEAN_FORCING was deprecated. I will look into the alternate approach, but I was having issues with the new OPEN boundaries where the dynamic pressure component was causing spurious velocities when a turbulent plume interacts with an 'outflow' boundary (where you can have switching from inflow to outflow with values quite different from the mean wind).
This may be related to having the MEAN_FORCING trying to correct the perturbations, though. So I can try with the new OPEN boundaries and no MEAN_FORCING.

**Comment by rmcdermo** [comment]
OK, well, you should not have MEAN_FORCING on while using the new open boundaries. Yes, this causes problems.  If you have a case with spurious outflow boundaries, that is what we need to look at.

**Comment by ericvmueller** [comment]
Alright, I can check out the new boundaries without MEAN_FORCING, and open a separate issue if that still causes problems (just so we dont over-complicate this thread).

As far turning off mean forcing within a region of the domain (but not blocking the flow), how would I need to alter the example to achieve that? (I realize the example is nonsensical because aims to disable the mean forcing everywhere, but it was to demonstrate the feature)

**Comment by rmcdermo** [comment]
Have a look at the `fds/Verification/Flowfields/mean_forcine_hole.fds` verification case.

**Comment by ericvmueller** [comment]
Okay, so for that case I'm not seeing a difference in the results if I include or remove the BLOCK_WIND flag for inside the structure. Which I think is related to my initial query about whether the MEAN_FORCING_CELL values are being properly assigned.

But maybe not a big deal if you are moving away from this approach!

**Comment by rmcdermo** [comment]
You are correct, it's not being applied.  I added a slice of MEAN_FORCING_CELL.  Thanks for catching this.
<img width="752" alt="Screen Shot 2021-01-29 at 11 26 20 AM" src="https://user-images.githubusercontent.com/4418497/106300855-f7c29000-6224-11eb-8149-d936836d64b1.png">

**Comment by rmcdermo** [comment]
@mcgratta I think Eric is right about this, but I do not want to reorder READ_WIND and READ_OBST myself.  I pushed up a change to the `mean_forcing_hole.fds` case.  Run this and you will see the problem.

**Comment by mcgratta** [comment]
Do you want to make this change or remove MEAN_FORCING?

**Comment by rmcdermo** [comment]
There is a niche reason to maintain MEAN_FORCING.  If you do `Verification rmcdermo$ grep MEAN_FORCING ./*/*.fds` you will see it gets used in `ribbed_channel`.  This is a periodic flow where all we are really trying to do is impose a mean pressure gradient.  So, we could use `FORCE_VECTOR(1)=...`.  However, this is an opaque way of specifying the flow.  It is, in my opinion, easier to understand at a glance `U0=2`.

That said, if we really want to purge MF then it is doable.  It just means using FORCE_VECTOR in certain situations.

**Comment by mcgratta** [comment]
I'd rather remove it. There's a lot of baggage tied to it, and if it's only
useful for a diagnostic case, it's  not worth saving. My real fear is that
the vast majority of wind cases are going to involve flow around burning
buildings, and not wildfire, in which case the awkward business of cutting
holes is going to come back again and again.

>

**Comment by rmcdermo** [comment]
OK.  I will work on tuning the FORCE_VECTOR for ribbed_channel.  Let me get that done before you purge, else Firebot will complain.
