### ISSUE TITLE
The simulation time increases dramatically after 30 seconds

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#9163]
Attached is a simulation that runs the first 30 seconds fairly quick (a couple of hours). Then the simulation time increases. Around 60 seconds the simulation almost stop. One second of simulation (from 66 to 67 seconds) has taken approximately 17 hours (8670 time steps) with intel 9900, 4 cores and MPI. I have also tried the latest bundle. With this version of FDS, the simulation almost stops after 30 seconds.

[DV.TXT](https://github.com/firemodels/fds/files/5894525/DV.TXT)

Is there anything I can do to speed up the calculations, or is this what I should expect with my case ?

**Comment by rmcdermo** [comment]
I do not yet see this as a demonstrated bug.  Please submit to the discussion forum.

**Comment by mcgratta** [comment]
I'll take a look at it. My guess is the problem is
```
&VENT XB= 5.20, 5.25,   8.60, 8.65,   0.0, 0.0, SURF_ID='OPEN' / (leak)
```
It is not a good idea to use a single OPEN cell to represent the leakage from a large compartment. You should apply leakage as suggested in the FDS User's Guide.

**Comment by mcgratta** [comment]
I ran the case about 30 s. The problem is what I expected. Look at the .out file
```
       Time Step    6400   January 29, 2021  14:52:10
       Step Size:    0.791E-03 s, Total Time:      31.42 s
       Pressure Iterations:      7
       Maximum Velocity Error:  0.21E-01 on Mesh   2 at ( 106  28   2)
       Maximum Pressure Error:  0.19E+04 on Mesh   4 at (  60  90   4)
       ---------------------------------------------------------------
       Mesh    1
       Max CFL number:  0.98E+00 at ( 105, 173,   1)
       Max divergence:  0.11E-01 at (  44,  90,  26)
       Min divergence: -0.21E-01 at (  45,  29,  24)
       Max VN number:   0.50E+00 at ( 105, 173,   1)
```
This tells you that the maximum CFL number occurs in mesh 1 near the single hole leak. The pressure in the simulation is above 1200 Pa, which means that a lot of air is being forced through this little hole. High speed means small time step means long run time.

**Comment by fidran** [comment]
Thank you for helping me out of this. Normally I use SURF_ID='OPEN' to 
describe exhaust grills. This time I did not, so my focus was not at all 
on pressurizing the space. Sorry for bother you with something I should 
have solved myself.

Reards
Finn Drangsholt

Den 2021-01-29 21:00, skrev Kevin McGrattan:
