### ISSUE TITLE
Different results with two fds versions

### ISSUE THREAD

**Issue by yxl1453** [firemodels/fds#9165]
Hi, I ran a FDS case with a simple geometry, a vertical fuel ignited at bottom. That code was ran in FDS 6.2.0 and the results are fine. But recently I used the 6.7.5 the newest version, it did not even ignite. Since the code are exactly same. What might be the reason resulting in this? Is there any change on the default model or solver between the two versions? Thank you in advance for your answers.

**Comment by rmcdermo** [comment]
Post your question to the discussion forum.
