### ISSUE TITLE
&INIT error with HT3D present in nightly but not current release

### ISSUE THREAD

**Issue by johodges** [firemodels/fds#9166]
Hello,

The attached input file results in an error in the nightly build of 6.7.5 (6.7.5-886-g9cdae53e0-nightly) that does not occur in the current release version (FDS6.7.5-0-g71f025606-release). The model initializes a subset of the domain to 500 C. There is a solid block with HT3D enabled that is intended to also be initialized to this temperature. In the current release, the functionality works as expected. In the nightly build the gas temperature outside the solid is initialized correctly, but the temperature inside the solid is at TMPA.

[init_test.txt](https://github.com/firemodels/fds/files/5895987/init_test.txt)

Thanks,

Jonathan

**Comment by rmcdermo** [comment]
Thanks, Jonathan.  I'll take a look

**Comment by rmcdermo** [comment]
Well, this got broken with PR #8804 .  TMP_INNER is historically how people expect to set the initial temperature.  We need to think about what should supersede what.  For the time being, you can set TMP_INNER on the SURF to achieve the internal temperature you want.

**Comment by rmcdermo** [comment]
This should be fixed with PR #9168 .  Please confirm.

**Comment by johodges** [comment]
Thanks for the quick work Randy. I can verify the latest build this issue is fixed. Regarding your comment on which should supersede, my thought would be TMP_INNER should resolve before INIT, with INIT overwriting TMP_INNER. This would provide more flexibility (able to initialize a subset of an obstruction to a different temperature) as well as allow a user to use the same surface for multiple obstructions with different initial conditions.

**Comment by rmcdermo** [comment]
OK, should be fixed now, try PR #9177 .  Now you can init a separate region of the solid.

<img width="752" alt="Screen Shot 2021-02-01 at 11 12 41 AM" src="https://user-images.githubusercontent.com/4418497/106485827-01473480-647f-11eb-92ac-9cca63cdf085.png">

**Comment by rmcdermo** [comment]
Closing this.  Let me know if we need to reopen.
