### ISSUE TITLE
background species not found

### ISSUE THREAD

**Issue by waidelich** [firemodels/fds#9192]
using FDS6.7.5 error is not find background speciiesng
In Dropbox
ng
In Dropbox

**Comment by drjfloyd** [comment]
Please post the simplest version of your input file that you can create that still has the error.

**Comment by waidelich** [comment]
This will not create as when it starts to read the the input file it causes
the error. Did not experience this with the previous version of FDS.

**Comment by drjfloyd** [comment]
You need to either attach an input (.txt) or paste in the lines. Before doing so, please simplify as much as possible while still getting the error.

**Comment by waidelich** [comment]
uploaded text file

**Comment by drjfloyd** [comment]
There is still no file attached to your comment.  

Either copy and paste the lines of input from a simple input file that demonstrates the problem or attach the file. To attach a file make sure it is a .txt file, open a directory window (e.g. Windows Explorer, Apple Finder) and drag the file into your comment.

**Comment by drjfloyd** [comment]
closing. No file was ever attached.
