### ISSUE TITLE
Wrong index for RAMPS in cone_demo, cone_demo_2

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#9199]
Run any of those (Pyrolysis) in db mode. This is what I see:

MPI startup(): Warning: I_MPI_PMI_LIBRARY will be ignored since the hydra process manager was found

 Starting FDS ...

 MPI Process      0 started on blaze.el.nist.gov

 Reading FDS input file ...

forrtl: severe (408): fort: (3): Subscript #1 of the array RAMPS has value 0 which is less than the lower bound of 1

Image              PC                Routine            Line        Source             
fds_impi_intel_li  000000000C346CDF  Unknown               Unknown  Unknown
fds_impi_intel_li  000000000347F234  read_input_mp_pro        8533  read.f90
fds_impi_intel_li  00000000032F0317  read_input_mp_rea         130  read.f90
fds_impi_intel_li  0000000003F0A49B  MAIN__                    119  main.f90
fds_impi_intel_li  000000000040A022  Unknown               Unknown  Unknown
libc-2.17.so       00002AB00DE73505  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  0000000000409F29  Unknown               Unknown  Unknown

**Comment by rmcdermo** [comment]
How is this escaping firebot?

**Comment by marcosvanella** [comment]
No idea. Try it to confirm.

**Comment by rmcdermo** [comment]
Yes, it fails for me in _db.

@gforney Does firebot grep on "forrtl"?

@drjfloyd Please have a look at the RAMPS issue.  Thanks

**Comment by marcosvanella** [comment]
Might be a change after last nights firebot.

**Comment by marcosvanella** [comment]
Dialing back to this PR:
 Merge pull request #9191 from mcgratta/master
 FDS User Guide: Add some guidance for PATH_LENGTH
the case runs.

**Comment by rmcdermo** [comment]
Well, that makes no sense.  No source code changes.

**Comment by rmcdermo** [comment]
Or you are saying, this is the culprit:
`a8cac3409 FDS Source: Added DO_EVACUATION global logial variable`

**Comment by marcosvanella** [comment]
The issue starts after Timos:
    Merge pull request #9193 from tkorhon1/master
    
    FDS Source: Added DO_EVACUATION global logical variable

**Comment by marcosvanella** [comment]
Yes. Something related to changes there it seems. I also noted a Sprinkler case e_coefficient.fds is giving numerical instability. Probably all related now.

**Comment by gforney** [comment]
firebot checks for 
Segmentation, ERROR:, forrrtl, in .err files, 
ERROR: in .out files, 
'BAD TERMINATION' in .log files

**Comment by marcosvanella** [comment]
This is fixed.

**Comment by tkorhon1** [comment]
Yes, this was my mistake. The cone example is not in FDS_Cases_Subset.sh. And, actually, I did not run FDS_Cases_Subset.sh for the last trivial change that I did. I just checked by diff-command that everything was nice and my simple fire+evacuation test was working.

**Comment by marcosvanella** [comment]
Timo, do you run your cases in a cluster? Something I do to make sure the verification cases get off the ground is go to
fds/Verification/scripts and type:
`$ ./Run_FDS_Cases.sh -m 5`
that will run all verification cases for 5 timesteps. Then in the Verification directory grep for issues in the .err or .out files:
`$ grep forrtl */*.err`
`$ grep Numerical */*.out`
