### ISSUE TITLE
Numerical Instability Issues with Cinema Fire - FDS Code

### ISSUE THREAD

**Issue by jameschampion20** [firemodels/fds#9203]
Hi All,

I am having some issues with modelling a cinema fire coupled with a HVAC system in FDS Version 6.7.4. I have attached the code below and any help / suggestions with this would be great. To give a bit more background, the simulation runtime is set at 1200 seconds and it seems to run fine for the first ~300 seconds, before giving some very large pressure values
[622924_Auditorium_03_REV11.txt](https://github.com/firemodels/fds/files/5951342/622924_Auditorium_03_REV11.txt)
![Capture](https://user-images.githubusercontent.com/68464009/107363974-c5d9e500-6ad2-11eb-98f5-057e273e835f.PNG)

. Looking at some of the pressure slice files (also attached), the pressure changes dramatically around the extract ductwork between around 450 and 500 seconds (temperature also changes in this manner), and I believe that the extract ductwork is the problematic area.

Please let me know your thoughts when you get a chance and if you require any further information.

Many thanks for your help,

James

**Comment by drjfloyd** [comment]
Don't do leakage by having a small open VENT. This can lead to stability issues as you can wind up with large flow speeds in that opening. Instead, define a pressure zone in each room with an appropriate leakage area and then use LEAK_PATH on the room walls.

You don't really have enough grid resolution to model the flow inside the ducts. Resolving duct flow is going need at least 8 to 10 cells across the diameter of the duct.  Otherwise you are not going to be accurately solving for the pressure losses inside the supply ducts. I would make the supply ducts in the room solid OBST, put HVAC VENTs at the ends of the supply ducts, and specify the duct network using HVAC with appropriate losses to represent the fittings (e.g. elbows and tees) in the network.  Same for the exhaust. Actually since the exhaust is constant flow you could just specify the exhaust as a VENT with a fixed flow rate at each of the exhaust locations.

**Comment by jameschampion20** [comment]
[622924_Auditorium_03_REV11 - Copy.txt](https://github.com/firemodels/fds/files/5952420/622924_Auditorium_03_REV11.-.Copy.txt)
Hi Jason,

Many thanks for your prompt and useful response. Regarding your message, for leak VENT, I assume you are referring to the VENT on the floor of the cinema auditorium? This is purely in place to oxygenate the fire and to maintain the 4MW fire size. I have uploaded a slightly amended version of the FDS code (model ran in Version 6.7.4). Ideally, I would like to leave the supply and extract ductwork as they are as part of this study is looking at temperature within the ductwork. Do you think if I took the attached FDS file, refined the mesh to around 0.05m, and then ran the simulation, this would work?

Many thanks for your help,
James

**Comment by drjfloyd** [comment]
I suggest you avoid thin OBST for the walls of your ducts or significantly tighten the velocity tolerance (this will increase the run time perhaps substantially). It is more difficult for the pressure solver to maintain zero velocity across a thin boundary. Given the large duct surface areas, even a small velocity error could have a large impact on the duct flow. 

Your hole in the floor is 0.2 m x 2.2 m. Your three supply ducts are 0.3 m x 0.3 m.  These are areas of 0.44 m2 and 0.27 m2. Your floor opening which has no significant flow resistance is almost twice the area in the supply ducts which have a substantial flow resistance. If your goal is to predict flow conditions in the supply duct, I am not sure this accomplishes that. 

Reducing the resolution from 10 cm to 5 cm means that in the smallest diameter portion of the supply ducts will go from 3x3 to 6x6. This is still probably not enough resolution to resolve the pressure drop in the tee, elbows, and exit. It depends on what you need to get out of this simulation. If you didn't have the large hole in the floor, then the main error from the lack of resolution will be in how the supply flow distributes over the three supply locations. If the supply duct was the only substantial means for flow to enter the compartment (i.e. no hole in the floor) then resolution issues would slightly change the time for flow to develop in the supply duct but eventually you would get mass flow in the supply to match the mass flow out the exhaust. If what you mostly care about is the temperature coming from the supply ducts, then in the absence of the hole in the floor you may be OK.

**Comment by jameschampion20** [comment]
[622924_Auditorium_03_REV12_NOFIRE - Copy.txt](https://github.com/firemodels/fds/files/5956925/622924_Auditorium_03_REV12_NOFIRE.-.Copy.txt)
Hi Jason,

Thanks for your additional response. 

I ran a dummy simulation (see FDS code attached) with no fire, just to look at the flow conditions. I have added flow monitors on top of all three supply duct exits, as well on top of the hole in the floor and the door (which opens at 60s). As you will see from the attached Excel file and PNG screenshot, the extract rate of 2.1m^3/s is maintained. However, very little of the inlet air is provided by the supply ducts and most comes from either the hole in the floor or the entrance door (which opens after 60 seconds). This does not appear to be realistic and renders the three supply ducts almost negligible. Based on our discussion so far, it seems like the best approach to solving this would be the following: 

1. Significant mesh refinement (to at least 5cm but ideally lower); 
2. Tighten the velocity tolerance; and
3. Remove the vent on the floor (of area 0.44m^2).

Do you think doing the three steps shown above would work and give a more accurate solution? Hopefully some of the inlet air from the three supply ducts could also be used to maintain the 4MW fire size. I will likely keep the entrance door opening at 60 seconds to allow for a degree of additional air to oxygenate the fire. Do you think this approach is OK? 

Additionally, one of the other aims of this study is to correctly model and monitor the heat transfer across the obstruction labelled "ceiling" in the attached FDS code. It is currently one cell thick and all surfaces are assigned as gypsum plaster. My understanding is that in the current set-up, the heat transfer across the ceiling _is_ being _correctly_ modelled, since FDS will use the surface properties of the gypsum surface and the gas temperature underneath the ceiling to predict the degree of heat transfer through the ceiling. Is this the case? Or is there something more that could be added to the model for heat transfer across the ceiling to be modelled more accurately? Are there devices that could be added which would show the degree of heat transfer taking place across the ceiling?

Thanks again for all your help,
James  


[622924_Auditorium_03_REV12_NOFIRE_devc.xlsx](https://github.com/firemodels/fds/files/5956958/622924_Auditorium_03_REV12_NOFIRE_devc.xlsx)
![VolumetricFlowrates](https://user-images.githubusercontent.com/68464009/107488503-5a018600-6b7f-11eb-97ba-6451801ca317.PNG)

**Comment by jameschampion20** [comment]
Hello,

Following on from the previous conversation above, I have made the following amendments to the FDS model: 

1. Significantly refined the mesh so that it is 0.025m throughout (hence also reducing the velocity tolerance)
2. Changed the backing of both the gypsum and steel to be "exposed" (rather that "air gap") - the aim of this is to accurately model heat transfer through solid surfaces, particularly the obstruction marked as Ceiling
3. Changed the fan material from INERT to steel
4. Removed the vent at floor level
5. All surfaces around the door (which is scheduled to open at 60 seconds) are now VENT surfaces

Please find the updated FDS code attached which relates to the changes listed above. Do you think the changes made will now provide accurate results?

Many thanks for your help,
James

[622924_Auditorium_03_REV11_FinerMesh_Rev01.txt](https://github.com/firemodels/fds/files/5964804/622924_Auditorium_03_REV11_FinerMesh_Rev01.txt)

**Comment by drjfloyd** [comment]
As I stated in my first comment, do not do leakage by having a small hole to ambient. Use ZONE and LEAK_PATH.  By having a tiny, single cell hole, as the gas volume in the compartment looks to expand due to the fire, all of that expansion is going to vent through that small hole. You will have large velocities that are not realistic and can lead to numerical instabilities.

The velocity tolerance has two parts. The magnitude of the tolerance, and the number of pressure iterations allowed before FDS stops attempting to achieve the tolerance.  Changing the grid size only changes the default tolerance, which in your case would still be over 1 cm/s. You may still need to up the pressure iterations to achieve that tolerance, or you could make the duct walls one grid cell thick and greatly reduce the number of pressure iterations needed to achieve a low tolerance. 

If you want to assess the accuracy of your grid for modeling flows in the ducts, build a version where you use the HVAC model specifying appopriate losses for all the duct fittings (elbows, tees, reduction/expansion, etc.) present. Run both versions with the exhaust fan on and no fire and compare the volume flows in the various segments of duct.  You shouldn't need to run these case for very long for steady flow to develop.

**Comment by jameschampion20** [comment]
[622924_Auditorium_03_REV11_FinerMesh_Rev02.txt](https://github.com/firemodels/fds/files/6001773/622924_Auditorium_03_REV11_FinerMesh_Rev02.txt)

Hi Jason,

Many thanks for your response above. Please find attached the latest FDS code (Rev02). Summary of changes I have made: 

1. Removed the small hole at the bottom of the door. The door is still set to be opened after 60 seconds
2. Increased the maximum pressure iterations to 100

Do you think that the attached file will now provide accurate results?

Many thanks for your help,
James

**Comment by jameschampion20** [comment]
[622924_Auditorium_03_REV12_NOFIRE_NEW.txt](https://github.com/firemodels/fds/files/6010793/622924_Auditorium_03_REV12_NOFIRE_NEW.txt)

Hello,

I have ran a simulation with the following changes: 

1. Removing the fire
2. Removing the low-level vent 
3. Removing the leakage under the door
4. Having the door open at 100 seconds

This ensures that for the first 100 seconds, the only source of inlet air for the extract is the three inlet vents (which is physically realistic). Please see the FDS code attached. 

I have monitored the supply rates from all three ducts and the sum of them seem to match that of the extract (i.e. 0.5+0.6+1 = 2.1m3/s extract rate, as expected, please see attached). This shows that close to the expected flow is coming out of the three ducts. However, review of the pressure plot at 2m above floor level (also attached) shows that the pressure is around -250Pa. This is very low and would cause issues with depressurization. Do you know why the pressure is so low? As given the supply rate is matching the extract rate, I am unsure why there appears to be depressurization. Would refining the mesh and increasing the number of pressure iterations help in this instance? 

Many thanks for your help,
James

![PressurePlots](https://user-images.githubusercontent.com/68464009/108521648-db65c080-72c3-11eb-87ff-197c415c6384.PNG)


![Capture](https://user-images.githubusercontent.com/68464009/108521166-5c708800-72c3-11eb-8944-894189c87c36.PNG)

**Comment by drjfloyd** [comment]
You have mechanical exhaust and natural supply. Air is only going to enter the supply ducts if the pressure inside the building is lower than the pressure outside.  Do a hand calculation of the expected pressure drop in the supply duct network. You have an entrance loss, three elbows, and a tee in the main duct. The two outer smaller ducts have an elbow, an expansion loss, and an exit loss. The middle smaller duct has an expansion loss and an exit loss.

**Comment by jameschampion20** [comment]
[622924_Auditorium_03_REV13_doorLeakage.txt](https://github.com/firemodels/fds/files/6081994/622924_Auditorium_03_REV13_doorLeakage.txt)

Hello,

For the cinema fire case (please see latest FDS code attached), prior to the entrance door opening, we currently have the following air inlet paths: the supply ductwork and the leakage either side of the two doors. The entrance door leakage is currently modelled as a hole, but this will likely be changed to a HVAC leak (like the side door). The total amount of air entering the auditorium will equal the extract rate of 1.5m3/s. 

My main query relates to what fire size should be modelled given the amount of air entering the auditorium (via both the supply ductwork and the two leakage paths). Ideally we would like a stable fire heat release rate prior to the entrance door opening so that there is not a large increase in heat and smoke once the door opens. The door is currently set to to open after 60 seconds but this opening time will likely be increased to hopefully allow for a stable fire size to be reached prior to door opening. Do you know of an equation which would allow the fire size to be modelled to be determined based on the inlet air being provided? Also, what growth rate fire do you think should be modelled? 

Many thanks,
James

**Comment by jameschampion20** [comment]
Hello, 

Just to follow up on my previous comment, the FDS file initially sent still contained a vent in the floor. This vent will be removed and the sole ventilation of the fire will be provided by the supply ducts and the door leakage. 
[622924_Auditorium_03_REV14_doorLeakage.txt](https://github.com/firemodels/fds/files/6083506/622924_Auditorium_03_REV14_doorLeakage.txt)

**Comment by drjfloyd** [comment]
This no longer seems to be an actual issue with FDS and further discussion should be moved to the forum.  

I cannot tell you what fire size, growth rate, etc. to use in your analysis. That is a decision you need to make and justify for your specific purposes.  

Prior to the door opening you have some mass of oxygen in the room and some mass of oxygen being continuously supplied by the HVAC system.  You should be able to use this information to determine how big of a fire can be sustained. You may wish to consult some texts on basic fire dynamics if you do not know how to do this.
