### ISSUE TITLE
Inconsistent results with FUNCTION_TYPE='MAX'

### ISSUE THREAD

**Issue by SFC-CA** [firemodels/fds#9204]
There are a couple of things going on and it has been difficult to replicate and isolate the errors.

1) Using MAX with one input being a maths output from a CTRL can give erroneous results. 
For example I have an input file performing MAX on a timer starting in negative territory and a zero value created through a maths CTRL My intention was to provide a non-negative clamped output. 

In this case MAX gives the output as the negative value rather than zero.

2) If one of the inputs to the MAX function is a DEVC with a NO_UPDATE, the MAX function will inconsistently output the value of the DEVC as if the NO_UPDATE has NOT been applied. The NO_UPDATE has clearly been applied if looking at the output of the DEVC. 

MaxTest.fds attached. This demonstrates the problem with three controls, Max0_2, Max1_2 and Max 2_2. These all show incorrect values for the MAX function with a negative input. Max0_2 shows the value as if the NO_UPDATE has not been applied to its input at 15s, where as Max1_2 and Max2_2 show it has having been applied.

[MaxTest.txt](https://github.com/firemodels/fds/files/5953757/MaxTest.txt)

**Comment by drjfloyd** [comment]
This was a bug that I thought we had fixed but turned out didn't fix in all the places it needed to be fixed.  Should be fixed now.  Now when I run I get 0,1,2 for the MAX outputs at the start and 15,15,15 at the end.

**Comment by drjfloyd** [comment]
Initial input file working in 6.7.7. Closing the issue.
