### ISSUE TITLE
Job hangs in multiple meshes when there is an error

### ISSUE THREAD

**Issue by sbenkorichi** [firemodels/fds#9210]
Hi Kevin,

Could you please look at this case. I've noticed that FDS doesn't come to a stop and remains stuck in the terminal, or shown to be running in a scheduler. It should be noted that this doesn't appear in a single mesh case.
This was fine with FDS 6.7.0 though, if this has been fixed in the current code, I can't compile it at the minute to test it.
```
&HEAD CHID='junk'/
&TIME T_END=5.0/
&DUMP WRITE_XYZ=.TRUE., /

&MESH  IJK=17,20,9, XB=1.4,4.8,7.0,11.0,0.0,1.8/
&MESH  IJK=17,20,9, XB=1.4,4.8,7.0,11.0,1.8,3.6/

&SURF ID='Supply',
      RGB=26,204,26,
      VOLUME_FLOW=-0.5/

&VENT ID='Vent', SURF_ID='Supply', XB=2.4,4.0,8.2,9.8,0.2,0.2/ 

&TAIL /
```

**Comment by drjfloyd** [comment]
With the current release a single process returns an error and stops gracefully but two processes hangs with no error. With the current source, two processes returns an error and stops gracefully.

**Comment by sbenkorichi** [comment]
Thanks Jason
