### ISSUE TITLE
ERROR: Numerical Instability - FDS stopped

### ISSUE THREAD

**Issue by Dehan-Dewinda** [firemodels/fds#9230]
Can you please help me to find out the reason which caused this error?
And also at the end, a sudden blow happens near the walls. I think that might be the reason for the error. But I don't understand where's the issue. I have only initiated the fire at the purple objective in the room. ****

Input file:
[FireSimulation.txt](https://github.com/firemodels/fds/files/5982188/FireSimulation.txt)

Smokeview output capture:
![Capture](https://user-images.githubusercontent.com/77019947/107960631-db677700-6fca-11eb-8aea-ca5ed882e473.PNG)

**Comment by mcgratta** [comment]
I ran this case, but nothing happens. You have commented out lines that define the fire. When I add them back, there is an error about defining multiple fuels. I don't know what you are trying to do here, but when I see comments in the input file like 'Properties completely fabricated', it suggests that you have not carefully thought through the simulation. My advice would be to start with a more simple fire scenario until you gain experience.

**Comment by Dehan-Dewinda** [comment]
I am trying to ignite the fire using this part only. This is the purple object at the mid.

&PART ID='ignitor particle', SURF_ID='ignitor', STATIC=.TRUE. /
&SURF ID='ignitor', TMP_FRONT=1000., GEOMETRY='CYLINDRICAL', LENGTH=0.15, RADIUS=0.01 /
&INIT XYZ=2.45,4.35,0.65, DX=0.1, PART_ID='ignitor particle', N_PARTICLES=3 /

 I have commented other fire generation part which is this.
create OBST for fire simulation using Methane reaction (see fig 7)
OBST ID ='methane_source', XB=1.0,1.5,2.5,3.0,0.0,0.1, SURF_ID ='methane_burner'/

create SURF_ID methane_burner using SURF_ID syntax
SURF ID = 'methane_burner', COLOR ='RED', HRRPUA = 1000.0/

create chemical reaction for AIR + METHANE using this SYNTX
REAC ID = 'METHANE', FYI = 'AFT NIST Multi-Floor FDS5 validation', FUEL = 'REAC_FUEL', FORMULA = 'C1H4', CO_YIELD =0.01, SOOT_YIELD = 0.05/

I think that is why it says "Multiple Fuels" after you uncommented that.

**Comment by mcgratta** [comment]
These lines did not ignite the fire. Your grid cells are 0.4 m on a side, and you cannot expect meaningful temperatures to result from this very coarse grid.
