### ISSUE TITLE
Radiative Fraction does not affect the Child_hrr.csv file

### ISSUE THREAD

**Issue by leobardovalera** [firemodels/fds#9239]
I modify the option to Radiative_Fraction to RADIATIVE_FRACTION=0.1 and RADIATIVE_FRACTION=0.9 and the files 
Child_htt.csv does not change. Attached you will find three fds files and their three corresponding Child_hrr.csv files.

You can see that the  Child_hrr.csv are the same

I would like to modify the radiative_fraction to control the third column of the Child_hrr.csv

Thanks in advance

[Region.tar.gz](https://github.com/firemodels/fds/files/5992936/Region.tar.gz)

**Comment by mcgratta** [comment]
Run this little case, and then run it with RADIATIVE_FRACTION=0.1. This should confirm the basic functionality. Note that KAPPA0 sets the absorption of the atmosphere to zero. This is for testing only. Q_RAD in the _hrr.csv file is a measure of the radiative heat loss to the boundary of the domain. When you have a large domain like this, the CO2 and H2O in the atmosphere will absorb a considerable amount of radiation. Setting KAPPA0 to 0 allows you to assess that the INIT line is working.
```
&HEAD CHID='Region2', TITLE='Simulation of Chimney Tops fire' /

&MESH IJK=25,25,21, XB=360,460.0,32,132.0,304,388.0, MULT_ID='mesh' /
&MULT ID='mesh', DX=100.0, DY=100.0, DZ=84.0, I_LOWER=0, I_UPPER=1, J_LOWER=0, J_UPPER=1, K_UPPER=1 /

&RADI KAPPA0=0 /

&TIME T_END=10 /

&INIT XB=456.0,460.0,100.0,104.0,392.0,396.0, HRRPUV=71.6, RADIATIVE_FRACTION=0.9 /

&VENT MB='XMIN', SURF_ID='OPEN' /
&VENT MB='XMAX', SURF_ID='OPEN' /
&VENT MB='YMIN', SURF_ID='OPEN' /
&VENT MB='YMAX', SURF_ID='OPEN' /
&VENT MB='ZMAX', SURF_ID='OPEN' /

&REAC FUEL='CELLULOSE', C=6, H=10, O=5, SOOT_YIELD=0.005 /

&SLCF PBZ=394, QUANTITY='HRRPUV', CELL_CENTERED=T /
&SLCF PBY=102, QUANTITY='HRRPUV', CELL_CENTERED=T /
&SLCF PBZ=394, QUANTITY='RADIATION LOSS', CELL_CENTERED=T /
&SLCF PBZ=394, QUANTITY='INTEGRATED INTENSITY', CELL_CENTERED=T /

&TAIL /
```

**Comment by leobardovalera** [comment]
Thanks a lot,

In my case that I have to simulate a big region. Do I have to worry about
the Radiative_Fraction? will that values will
affect the accuracy of my simulation?

Best regards

- Leo -

**Comment by mcgratta** [comment]
I do not understand the question. I have demonstrated that you can specify
a HRRPUV for a specified volume with a specified radiative loss.

>
