### ISSUE TITLE
Results with combined TEMPORAL_STATISTIC + SPATIAL_STATISTIC

### ISSUE THREAD

**Issue by mpachera** [firemodels/fds#9257]
Hi,

I tried to run a simulation where I coupled TEMPORAL_STATISTIC and SPATIAL_STATISTIC, but the outcome in the devc file is quite strange because the value is always equal to -1.0000000E+020. The TEMPORAL_STATISTIC works fine if I just have a point device, but I would like to measure the temperature on a larger area.
[input.fds.txt](https://github.com/firemodels/fds/files/6021820/input.fds.txt)

Thanks in advance for the support.

Matteo

**Comment by rmcdermo** [comment]
Thanks Matteo.  We'll take a look.

**Comment by mcgratta** [comment]
The setting of TEMP_STAT='MAX' led FDS to set a very low value when calculating the SPATIAL_STAT='MEAN'. This is a holdover from when only one kind of STATISTIC was allowed. Should work now.

**Comment by drjfloyd** [comment]
As a work around you could use a CTRL function.  Something like:

&DEVC ID='L_M5_door_00_C1_W2', QUANTITY='TEMPERATURE', SPATIAL_STATISTIC='MEAN', XB=0.0,0.5,-0.25,0.75,1.0,1.5/
&CTRL ID='Copy DEVC',FUNCTION_TYPE='CUSTOM',RAMP_ID='LinearRAMP',INPUT_ID='L_M5_door_00_C1_W2'/
&RAMP ID='LinearRAMP',T=0,F=0/
&RAMP ID='LinearRAMP',T=1500,F=1500/
&DEVC ID='New Output', QUANTITY='CONTROL VALUE',CTRL_ID='Copy DEVC',TEMPORAL_STATISTIC='MAX', SETPOINT=100.0,UNITS='C'/

The first DEVC gets the mean temperature. The CUSTOM CTRL function takes the input and looks up an output value based on the RAMP. In this case, as a linear ramp, it will just output the inputted temperature. The second DEVC takes the output of the CTRL function and evaluates the max over time.

**Comment by mpachera** [comment]
Thank you all for the support and  to Jason for proposing an alternative solutions.
