### ISSUE TITLE
Particle mass problem

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9264]
[mass.txt](https://github.com/firemodels/fds/files/6031917/mass.txt)

In this case, I single particle weighing 0.00758 kg and composed of copper and plastic is heated until the plastic disappears. The _hrr.csv file indicates that the mass evaporated is correct. But the particle disappears from the domain, even though there are inert solids still there. Is this something related to the latest changes in the 1D HT routines.

**Comment by drjfloyd** [comment]
Looks like it happens when the outer plastic layer drops below SF%MINIMUM_LAYER_THICKNESS. Could be related to the changes. I'll dig deeper.

**Comment by drjfloyd** [comment]
Should be fixed now.

**Comment by mcgratta** [comment]
Nice, thanks.
