### ISSUE TITLE
Show CFACE geometry in Smokeview

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9270]
When GEOMs intersect there is a linearization process that can alter the faces near sharp corners.  This issue highlighted the fact that currently when we view a GEOM in Smokeview what we are actually looking at is exactly what was input via the input file.  By default, we want to see the geometry that FDS uses in the fluids calculation, with the input geometry viewable as an option.

This brought to light a few things that need attention in terms of reorganizing geometry input and output files.

1. The `CHID_GEOM_ID.bingeom` file essentially contains identical information as the `CHID.ge` file, except that there is a bingeom for each GEOM line in the input file.  These need to be consolidated.  Probably best to use a mixture: `CHID_GEOM_ID.ge` for each GEOM in the input file.  The SURF_ID list on each GEOM line needs to be mapped to the list in the `CHID.smv` file.

2. We need to write out the actual geometry used in the fluids calculation.  This is essentially the same format used for geometry BNDF files.  CFACES and SURF_IDs need to be included.  These files will be something like `CHID.cf`.

3. BNDF files for GEOM appear to currently write geometry information to each `CHID_QUANTITY.bf` file.  These files should only need the CFACE values and then Smokeview will utilize one `CHID.cf` file for the geometry.

4. It would be nice to add optional lighting to BNDF in the short term to help visualize the linearization of the CFACES.

Attached here is a test case to play with.
[test_20cm.fds.txt](https://github.com/firemodels/fds/files/6040075/test_20cm.fds.txt)

**Comment by marcosvanella** [comment]
This is implemented. Hit q and SHIFT+o to see CFACEs.
