### ISSUE TITLE
Soot yeild on INIT line

### ISSUE THREAD

**Issue by adnannweilati** [firemodels/fds#9320]
Is it possible to specify a soot yield on a INIT region (not just as an initial condition but constant throughout the simulation)? 

I understand that I can specify a HRRPUV as a source term but Im wondering if its possible to model fire purely as a INIT region (with simple combustion model).

**Comment by mcgratta** [comment]
No. HRRPUV on an INIT line is simply a fixed volumetric heat source term.

**Comment by drjfloyd** [comment]
See the isentropic verification cases for a method of using particles to input a species over time in a region.
