### ISSUE TITLE
Minor issue with drawing triangles in SLCF near GEOM

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9339]
@marcosvanella and @gforney 
Please have a look at this case:
```
/home4/rmcdermo/GitHub/FireModels_rmcdermo/fds/Validation/Sandia_Plumes/Test_2/test_1p25cm
```
There are a few places where it looks like the triangles are being omitted in `SCLF` (here for DENSITY).  Note the white triangles near the gray geom.  This might point to issues with defining cut cells or whatever that should probably be cleaned up.  Thanks
<img width="1552" alt="Screen Shot 2021-03-14 at 2 33 43 PM" src="https://user-images.githubusercontent.com/4418497/111080016-de269080-84d2-11eb-9de2-5fa9cdb99b65.png">

**Comment by marcosvanella** [comment]
Looks like we have some missing triangles for the cut-face triangulation. We'll have a look.

**Comment by drjfloyd** [comment]
@rmcdermo The listed directory in the first post no longer exists. Do you have a newer file that still has the issue?

**Comment by rmcdermo** [comment]
Hmmm... I think we cleaned the repos to make space on burn at some point.  Let's close this and deal with issues as they come in with v7 beta.
