### ISSUE TITLE
forrtl: severe (157): Program Exception - access violation

### ISSUE THREAD

**Issue by FBrinnel** [firemodels/fds#9376]
Hello together,

First of all, im starting out in FDS Simulations and i'm thankful that there is a FDS community on Github that provides helpful information. 

In my geometry you can see several Thermocouples and Burner Surfaces. The HRR per Area [m²] has a smeared value and is distributed to the whole bottom. The Mesh is 20x20 cm distributed to eleven Mesh Zones
The FDS Textfile (Hall_222) shows that there are some Thermocouples, that dont show any Orientation although I clearly assigned Orientation to them (in Pyrosim).

Could this lead to the stated Error? (i typed in some paragraphs to make it more visible)

[Hall_222.txt](https://github.com/firemodels/fds/files/6195261/Hall_222.txt)

![error](https://user-images.githubusercontent.com/81226494/112153557-aced4500-8be3-11eb-88c0-55d669a66552.PNG)

I already simplified the model and avoided possible errors like (Zero thickness Obstructions, Intercepting obstructions, Burner Surface under a wall) although im not even sure if these parameters can cause an error like this or any erros in particular.

I already ran simpler Models with a Burner and Thermocouples which worked flawlessly (but on another Computer)
After like 170 Seconds i get the mentioned "forrtl: severe (157): Program Exception - access violation" Error

Any Help would be much appreciated

**Comment by mcgratta** [comment]
I will take a look at the case. In the meantime, run the case again and tell me if it fails at the exact same point in the calculation. Also, make sure you are using the latest FDS release.

**Comment by mcgratta** [comment]
This might be part of the problem
```
&REAC ID='Mischbrandlast',
      FYI='NFPA Fire Protection Handbook',
      FUEL='REAC_FUEL',
      C=58.656,
      H=93.317,
      O=11.333,
      N=1.535,
      CRITICAL_FLAME_TEMPERATURE=1327.0,
      CO_YIELD=0.0312,
      SOOT_YIELD=0.0824,
      HEAT_OF_COMBUSTION=2.546E4/
```
Your fuel molecule is approximately 300 times the molecular weight of air. In reality, the gas that is produced by whatever solid or liquid material this is will not be so heavy. I suggest you divide C, H, O, and N by, say, 50, and try again. 

Also, an ORIENTATION for a THERMOCOUPLE is meaningless and (probably) ignored, but remove it anyway.

**Comment by FBrinnel** [comment]
Thanks alot for the quick response, I will have a look at it and be back tomorrow.

**Comment by FBrinnel** [comment]
I ran the Simulation again and it stopped at the exact same time again. 
I also tried lowering the density/weight of the gas with no success (other than the simulation running to 181 seconds).

When I take off the roof it seems to work (calculation is running at the moment). Therefore it probably has something to do with underventilation. Although the simulation probably shouldn't just stop in an error.

**Comment by FBrinnel** [comment]
Do you have any suggestions how to simulate the enclosed Building? Or am I forced to implement some Leakage in the Building shell, for the simulation to work?

Thanks in advance

**Comment by sbenkorichi** [comment]
I've tested it on latest bundle on linux; it seems you have a sealed box with a larger fire size. Look into your .out file and check your maximum pressure error. You would be required to have sufficient air for your fire to continue growing as you have at least 10MW or more and require some air inlet to sustain your fire size such as window breakages etc. I don't think this is an issue with the bundle itself and might best to be a subject in the FDS-SMV discussion group.

**Comment by FBrinnel** [comment]
ok thank you. You got me on the right track. The Maximum Pressure Error ist at 0.63 E+06 and probably way too high.
The thought process for the simulation was to test, at which time the fire suffocates. 
I will have a look at the FDS-SMV disscussion group.

**Comment by mcgratta** [comment]
The "Maximum Pressure Error" in the .out file is not in units of Pa. It is related to the pressure iteration scheme. However, include slices of PRESSURE to determine if your over-pressure is too high. Add leaks and OPEN vents. 

Are you using the latest version of FDS? If not, there might be issues with undeclared pressure ZONEs.
