### ISSUE TITLE
DB doesn't work as expected

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/fds#9384]
Based on the User's Guide description, in the simple case below I would expect all of the domain boundaries to be OPEN; however, in the outer two meshes it is only the x faces that are OPEN ,and in the center mesh it is only the z and y faces that are OPEN. 

&HEAD CHID='bus_duct'/

&MESH XB=0.7620,2.2860,0.0000,3.0480,0.0000,3.0480,IJK=60,120,120/
&MESH XB=0.0000,0.7620,0.9144,2.1336,0.9144,2.1336,IJK=30,48,48/
&MESH XB=2.2860,3.0480,0.9144,2.1336,0.9144,2.1336,IJK=30,48,48/

&VENT DB='ZMAX',SURF_ID='OPEN'/
&VENT DB='YMAX',SURF_ID='OPEN'/
&VENT DB='XMAX',SURF_ID='OPEN'/
&VENT DB='YMIN',SURF_ID='OPEN'/
&VENT DB='XMIN',SURF_ID='OPEN'/
&VENT DB='ZMIN',SURF_ID='OPEN'/

&TIME T_END=0./

![bus_duct_s0000](https://user-images.githubusercontent.com/12799217/112482941-f312e780-8d4e-11eb-94b7-7309dc092a57.png)

**Comment by rmcdermo** [comment]
No this is mine.  Use MB.  I will clarity the guide.

**Comment by rmcdermo** [comment]
DB is a shortcut for XS_MIN and XF_MAX, etc.  This is exactly why we did not get rid of MB.

**Comment by drjfloyd** [comment]
It would be useful to have something that did all the external boundaries in a direction so one could assign a non-OPEN SURF_ID to the external boundary. MB will (or at least used to) try to apply it at internal mesh boundaries.

**Comment by rmcdermo** [comment]
MB seems to work.  Please provide an example of what you would like that does not work with the latest code.

**Comment by drjfloyd** [comment]
MB applies SURF_ID='solid' to all the XMAX faces. DB would apply it to only the XF_MAX face. What I thought DB would do is apply it to all XMAX faces that are on the domain boundary (so the face at x=3.048 and the outer ring at x=2.286). 

&HEAD CHID='test'/

&MESH XB=0.7620,2.2860,0.0000,3.0480,0.0000,3.0480,IJK=60,120,120/
&MESH XB=0.0000,0.7620,0.9144,2.1336,0.9144,2.1336,IJK=30,48,48/
&MESH XB=2.2860,3.0480,0.9144,2.1336,0.9144,2.1336,IJK=30,48,48/

&VENT MB='ZMAX',SURF_ID='OPEN'/
&VENT MB='YMAX',SURF_ID='OPEN'/
&VENT MB='XMAX',SURF_ID='solid'/
&VENT MB='YMIN',SURF_ID='OPEN'/
&VENT MB='XMIN',SURF_ID='OPEN'/
&VENT MB='ZMIN',SURF_ID='OPEN'/

&SURF ID='solid',COLOR='GRAY 40'/

&TIME T_END=0./


![test_s0000](https://user-images.githubusercontent.com/12799217/112499090-84895600-8d5d-11eb-92bf-a2867e46fb42.png)

**Comment by rmcdermo** [comment]
Got it.  Ok, I'll work on this.

**Comment by rmcdermo** [comment]
Jason,
I can't really think of an efficient way to do this.  Do you have any ideas?

**Comment by drjfloyd** [comment]
I think you are right. We don't set up OMESH until init so we don't have that data when processing VENT. I think the only way to do it would as we process inputs now would be in read_vent for each MESH to loop over the cells in that face and for each wall cell see if it is also in another MESH.  That could get expensive. I'll close.
