### ISSUE TITLE
Unable to start the program, because impi.dll is lossed from your computer, please try to reinstall to fix  this problem.

### ISSUE THREAD

**Issue by vivien321** [firemodels/fds#9399]
[無法安裝.docx](https://github.com/firemodels/fds/files/6237069/default.docx)

**Comment by rmcdermo** [comment]
Please post your question to the discussion forum.

**Comment by vivien321** [comment]
Unable to start the program, because impi.dll has be loss from your computer, please try to reinstall to fix this problem

**Comment by mcgratta** [comment]
We cannot help you. FDS has been designed to run under a standard Windows 10 installation. We do not know why you are missing this library.
