### ISSUE TITLE
Velocity flow at leak vent

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9400]
[test2d.txt](https://github.com/firemodels/fds/files/6238601/test2d.txt)
In this 2d case, there is a volumetric heat source in the small compartment, which has a leak to the larger compartment. When I look at the normal component of velocity on each VENT that constitute the leak, it is different. I would expect a small difference due to different densities, but this seems larger. Is this to be expected? You can see the difference visually in Smokeview by looking at the vectors of the cell-centered temperature. The devc file has the velocity components at every time step.

**Comment by drjfloyd** [comment]
I'll take look. The face velocity is set using TMP_F of that face. Any delta in TMP_F is addressed with LEAK_ENTHALPY as a heat source/sink in the downstream gas cell.

**Comment by mcgratta** [comment]
Yes, I assume rho*u should be the same, assuming the vent area is the same. But it appears to be much different. I'm wondering if perhaps I've hit a clip bound.

**Comment by drjfloyd** [comment]
I modified your case to just have two chambers, constant cp for the gas, no radiative fraction, and a single vent.  The increase in mass in the one chamber does equal the loss in mass in the other chamber as well as the total mass flow in the leak duct. The energy though is off. Not sure why right now.

[test2da.txt](https://github.com/firemodels/fds/files/6238988/test2da.txt)

**Comment by mcgratta** [comment]
The energy deficit might be related to temperature or density clipping.

**Comment by drjfloyd** [comment]
In my simplified case I cut back the HRRPUV to avoid any clipping

**Comment by drjfloyd** [comment]
Should be fixed.

**Comment by mcgratta** [comment]
Thanks. I'll check how my original case behaves now.

**Comment by mcgratta** [comment]
I modified my case to check the addition of internal energy for a fixed heat source of 40 kW for 1 s. I got 39.8 kJ. Very good, because I didn't go and tighten anything down and I left the 75% radiative fraction in place. These energy conservation cases are often complicated by radiation, but this one seems very good. Thanks.
