### ISSUE TITLE
Unable to start the program, because impi.dll is lossed from your computer, please try to reinstall to fix this problem

### ISSUE THREAD

**Issue by vivien321** [firemodels/fds#9404]
I do download the FDS win 64 bit, but system show that : Unable to start the program, because impi.dll was be loss from your computer, please try to reinstall to fix this problem.

please help me that the method. thank you.

**Comment by mcgratta** [comment]
We cannot help you. We designed FDS to run under a standard Windows 10 environment. We cannot explain why you are missing this library.

**Comment by drjfloyd** [comment]
Are you following the instructions on the User's Guide on how to run FDS? If you are not following the instructions, you will not have the correct environmental variables for FDS to find impi.dll which should be installed in
C:\Program Files\firemodels\FDS6\bin\mpi
