### ISSUE TITLE
PROF device in a pool

### ISSUE THREAD

**Issue by albaagueda** [firemodels/fds#9424]
Hi,
I'm trying to run the following code but I get an error. I asked for help in the Forum and they suggested me to open an issue. See:
https://groups.google.com/g/fds-smv/c/rY-IH90acbg

Thanks in advance.

`&HEAD CHID='acetone_1_m_ronan', TITLE='Single pan of burning acetone' /

&MESH ID='Mesh01', IJK=80,80,50, XB=-0.8,0.8,-0.8,0.8,0.0,1, MPI_PROCESS=0 /
&MESH ID='Mesh02', IJK=80,80,50, XB=-0.8,0.8,-0.8,0.8,1,2, MPI_PROCESS=1/
&MESH ID='Mesh03', IJK=80,80,50, XB=-0.8,0.8,-0.8,0.8,2,3, MPI_PROCESS=2/
&MESH ID='Mesh04', IJK=80,80,90, XB=-0.8,0.8,-0.8,0.8,3,4.8, MPI_PROCESS=3/

MESH ID='Mesh01', IJK=80,80,50, XB=-0.8,0.8,-0.8,0.8,0.0,1, MPI_PROCESS=0 /
MESH ID='Mesh02', IJK=80,80,50, XB=-0.8,0.8,-0.8,0.8,1,2, MPI_PROCESS=1/

TIME T_END=100., WALL_INCREMENT=1 /
&TIME T_END=10., WALL_INCREMENT=1 /

&DUMP DT_SLCF=5., DT_BNDF=5., DT_DEVC=0.5, DT_HRR=5., WRITE_XYZ=.TRUE., SIG_FIGS=4, SIG_FIGS_EXP=2 /

&MISC SIMULATION_MODE='LES', TMPA=24.0, HUMIDITY=30 /

&REAC FUEL               = 'ACETONE'
      FYI                = 'Acetone C_3 H_6 O_1'
      CO_YIELD           = 0.003
      SOOT_YIELD         = 0.014 /

&MATL ID                     = 'ACETONE LIQUID'
      EMISSIVITY             = 1.
      NU_SPEC                = 1.
      SPEC_ID                = 'ACETONE'
      HEAT_OF_REACTION       = 501
      CONDUCTIVITY           = 0.20
      SPECIFIC_HEAT          = 2.13
      DENSITY                = 791
      ABSORPTION_COEFFICIENT = 100
      BOILING_TEMPERATURE    = 56.15 /

&MATL ID            = 'STEEL'
      EMISSIVITY    = 1.0
      DENSITY       = 7850.
      CONDUCTIVITY  = 45.8
      SPECIFIC_HEAT = 0.46 /

&SURF ID        = 'ACETONE POOL'
      COLOR     = 'YELLOW'
      MATL_ID   = 'ACETONE LIQUID'
	  BACKING   = 'EXPOSED'
      THICKNESS = 0.1 /
	  

&SURF ID        = 'STEEL SHEET'
      COLOR     = 'BLACK'
      MATL_ID   = 'STEEL'
      BACKING   = 'EXPOSED'
      THICKNESS = 0.003 /
	  

&SURF ID        = 'ACETONE POOL 2'
      COLOR     = 'YELLOW'
      BACKING   = 'EXPOSED'
	  MATL_ID(1,1)  = 'ACETONE LIQUID'
	  MATL_ID(2,1)  = 'STEEL'
	  MATL_MASS_FRACTION(1,1) = 1.0
	  MATL_MASS_FRACTION(2,1) = 1.0	  
      THICKNESS(1:3) = 0.1,0.003 /	

&SURF ID        = 'STEEL SHEET 2'
      COLOR     = 'BLACK'
      BACKING   = 'INSULATED'
	  MATL_ID(1,1)  = 'STEEL'
	  MATL_ID(2,1)  = 'ACETONE LIQUID'
	  MATL_MASS_FRACTION(1,1) = 1.0
	  MATL_MASS_FRACTION(2,1) = 1.0	    
      THICKNESS(1:3) = 0.003,0.05 /
 
&SURF ID        = 'ACETONE POOL 2 REVERSE'
      COLOR     = 'YELLOW'
      BACKING   = 'EXPOSED'
	  MATL_ID(1,1)  = 'STEEL'
	  MATL_ID(2,1)  = 'ACETONE LIQUID'
	  MATL_MASS_FRACTION(1,1) = 1.0
	  MATL_MASS_FRACTION(2,1) = 1.0	  
      THICKNESS(1:3) = 0.003, 0.1 /
 
	  
&VENT MB='XMIN', SURF_ID = 'OPEN' /
&VENT MB='XMAX', SURF_ID = 'OPEN' /
&VENT MB='YMIN', SURF_ID = 'OPEN' /
&VENT MB='YMAX', SURF_ID = 'OPEN' /
&VENT MB='ZMAX', SURF_ID = 'OPEN' /

OBST XB=-.50,0.50,-.50,0.50,0.00,0.05, SURF_IDS='ACETONE POOL','STEEL SHEET','STEEL SHEET' /
OBST XB=-.50,-.50,-.50,0.50,0.00,0.10, SURF_ID='STEEL SHEET' /
OBST XB=0.50,0.50,-.50,0.50,0.00,0.10, SURF_ID='STEEL SHEET' /
OBST XB=-.50,0.50,-.50,-.50,0.00,0.10, SURF_ID='STEEL SHEET' /
OBST XB=-.50,0.50,0.50,0.50,0.00,0.10, SURF_ID='STEEL SHEET' /

&OBST XB=-.50,0,-.50,0.50,0.00,0.05, SURF_IDS='ACETONE POOL 2','STEEL SHEET 2','ACETONE POOL 2 REVERSE' /
&OBST XB=-.50,-.50,-.50,0.50,0.00,0.10, SURF_ID='STEEL SHEET' /
&OBST XB=0.50,0.50,-.50,0.50,0.00,0.10, SURF_ID='STEEL SHEET' /
&OBST XB=-.50,0.50,-.50,-.50,0.00,0.10, SURF_ID='STEEL SHEET' /
&OBST XB=-.50,0.50,0.50,0.50,0.00,0.10, SURF_ID='STEEL SHEET' /

&DEVC XYZ=-0.8,0,0.9, IOR=+1, QUANTITY='GAUGE HEAT FLUX', ID='qdotgauge'/
&DEVC XYZ=-0.8,0,0.9, IOR=+1, QUANTITY='RADIOMETER', ID='qdotradiometer'/
&DEVC XYZ=-0.8,0,0.9, IOR=+1, QUANTITY='NET HEAT FLUX', ID='qdotn'/
&DEVC XYZ=-0.8,0,0.9, IOR=+1, QUANTITY='RADIATIVE HEAT FLUX', ID='qdotr'/
&DEVC XYZ=-0.8,0,0.9, orientation=1,0,0, QUANTITY='RADIATIVE HEAT FLUX GAS', ID='qdotrgas'/

&PROF ID='T-1', XYZ=-0.50,0,0.05, QUANTITY='TEMPERATURE', IOR=-1 /
&PROF ID='T-2', XYZ=0,0,0.05, QUANTITY='TEMPERATURE', IOR=3 /

&TAIL /`

**Comment by mcgratta** [comment]
```
&PROF ID='T-2', XYZ=-0.0010,0,0.05, QUANTITY='TEMPERATURE', IOR=3 /
```
You put the PROF exactly on the edge of an obstruction. Why? Why not make sure that the PROF is clearly attached to a solid.

**Comment by albaagueda** [comment]
Sorry for the inconvenience, I just noticed my error...

The first obstruction line had a mistake, I defined it as:
XB=-.50,0,-.50,0.50,0.00,0.05

and it was an error, I was convinced that it was defined as the commented first obstruction line:
XB=-.50,0.50,-.50,0.50,0.00,0.05

Many thanks and sorry...
