### ISSUE TITLE
Scatter pressure 

### ISSUE THREAD

**Issue by TiboDC** [firemodels/fds#9425]
Hi

For my master dissertation, I'm simulating fires in a mechanically ventilated airtight compartment. When I increase the HRR, the scatter on the pressure evolution increases tremendously. Is there a specific reason for this and if so, how can I reduce it? 

![image](https://user-images.githubusercontent.com/73659411/114161003-d7e7d080-9927-11eb-84a6-1e28234754e2.png)
![image](https://user-images.githubusercontent.com/73659411/114161046-e59d5600-9927-11eb-8ce4-4de9872a6ffd.png)

Many thanks
Kind regards
Tibo

**Comment by rmcdermo** [comment]
This is not a code issue.  Please submit your question to the [discussion forum](https://groups.google.com/g/fds-smv)
