### ISSUE TITLE
IOR for devices at surface of cutface cylinder?

### ISSUE THREAD

**Issue by asbova17** [firemodels/fds#9429]
Hello - I'm working with a post-doc looking at simulations of a surface fire sweeping past a vertical cylinder (a proxy for a tree bole). There are line devices in vertical columns at the surface of the cylinder around its circumference. We've used both the typical obstruction method and the cutface (GEOM) method to construct the cylinders.  The mean adiabatic surface temperatures (AST) from the devices are more closely matched between the two types of simulation when we do _not_ add IORs to the device lines in the GEOM simulations. Adding IORs seems to reduce the mean ASTs in the GEOM case by more than 100 C compared to the obstruction simulations.

Is that expected behavior? Should we not add IORs to the devices in the GEOM simulations? Apologies in advance if I missed something in the user guide. Thanks!

**Comment by mcgratta** [comment]
Hard to say. Can you post a very simple example.

**Comment by asbova17** [comment]
Thanks for responding so quickly, Kevin. We'll put together a simplified case and get back to you as soon as we can.

**Comment by marcosvanella** [comment]
Kevin, just to note: The search for boundary faces in GEOMs does not depend in IOR, mainly the position of the device and cell it is located in. The search is done in the GET_CFACE_INDEX routine.

**Comment by asbova17** [comment]
We'll still put together simple cases, but that may answer the question. Should I interpret that to mean that IOR may not be needed for the GEOM simulations?

**Comment by mcgratta** [comment]
Yes, IOR only has meaning for rectilinear "lego" blocks---the OBST-style
obstructions.

>

**Comment by marcosvanella** [comment]
It does not depend on IOR for the search of the closest wall patch. Now, is it used in the AST computation?

**Comment by mcgratta** [comment]
IOR would only be used to identify a WALL cell. That is not relevant here.

>

**Comment by asbova17** [comment]
Great! I think that answers my original question. All else being equal, would you expect the device temperatures (AST) in corresponding GEOM & OBST simulations to converge as the mesh is refined? That's something we can check if it hasn't already been done.

**Comment by mcgratta** [comment]
Hopefully. Let us know if not.

>

**Comment by asbova17** [comment]
Sounds good. I'll call this closed, then. I'll open a new issue if there are significant differences in results from the two methods. Thanks!
