### ISSUE TITLE
Strange behaviour  when tying to define HEAT_OF_COMBUSTION on REAC

### ISSUE THREAD

**Issue by tstopi** [firemodels/fds#9432]
I am gettign a very weird behaviour in FDS version 6.7.5 (official release)

I am trying to model a cable trya fire and woud like to have a reaction with 16MJ/kg heat of reaction. However, if I define my reaction like so:

&REAC FUEL = 'PROPANE'
      SOOT_YIELD = 0.01
      CO_YIELD = 0.02
      HEAT_OF_COMBUSTION = 16460. /

There is no combustion (see does_not_work.fds and does not work_hrr.csv in the attached .zip file PROPANE is released into the domain but HRR remains zero.)

If I define the reaction as follows (copied from users guide, same as above except for the heat of combustion)
&REAC FUEL = 'PROPANE'
      SOOT_YIELD = 0.01
      CO_YIELD = 0.02
      HEAT_OF_COMBUSTION = 46460. /

then there is combustion and HRR. 

[cases.zip](https://github.com/firemodels/fds/files/6303854/cases.zip)

The full FDS file as text input below (does_not_work.fds)

----------------------------------------------

testing.fds
Generated by PyroSim - Version 2021.1.0224
13.4.2021 15:28:56

&HEAD CHID='does_not_work'/
&TIME T_END=10.0/
&DUMP DT_RESTART=300.0, DT_SL3D=0.25/

&MESH ID='MESH', IJK=15,9,22, XB=-78.733599,-74.983599,161.454924,163.704924,9.9,15.4/

&REAC FUEL = 'PROPANE'
      SOOT_YIELD = 0.01
      CO_YIELD = 0.02
      HEAT_OF_COMBUSTION = 16460. /

&SURF ID='Cable_fire_4 vertical cable trays',
      FYI='FLASHCAT four vertical cable trays. 4*150kw/m2 ',
      RGB=255,153,153,
      HRRPUA=600,
      TMP_FRONT=300.0/

&OBST ID='Obstruction', XB=-77.233599,-76.437303,163.307488,163.704924,10.05,12.85, SURF_ID='INERT'/ 

&VENT ID='Mesh Vent: MESH [XMAX]', SURF_ID='OPEN', XB=-74.983599,-74.983599,161.454924,163.704924,9.9,15.4/ 
&VENT ID='Mesh Vent: MESH [XMIN]', SURF_ID='OPEN', XB=-78.733599,-78.733599,161.454924,163.704924,9.9,15.4/ 
&VENT ID='Mesh Vent: MESH [YMAX]', SURF_ID='OPEN', XB=-78.733599,-74.983599,163.704924,163.704924,9.9,15.4/ 
&VENT ID='Mesh Vent: MESH [YMIN]', SURF_ID='OPEN', XB=-78.733599,-74.983599,161.454924,161.454924,9.9,15.4/ 
&VENT ID='Mesh Vent: MESH [ZMAX]', SURF_ID='OPEN', XB=-78.733599,-74.983599,161.454924,163.704924,15.4,15.4/ 
&VENT ID='Mesh Vent: MESH [ZMIN]', SURF_ID='OPEN', XB=-78.733599,-74.983599,161.454924,163.704924,9.9,9.9/ 
&VENT ID='Cable_Fire_Vent_04', SURF_ID='Cable_fire_4 vertical cable trays', XB=-77.233599,-76.636599,163.307488,163.307488,10.05,12.85/

&SLCF PBX = -76.935099, QUANTITY="VOLUME FRACTION", SPEC_ID="PROPANE"/
&SLCF PBX = -76.935099, QUANTITY="EXTINCTION"/

&TAIL /

**Comment by rmcdermo** [comment]
I would suspect this is just related to the EXTINCTION model.  You seem to understand this as you have a slice of EXTINCTION.  Have you set SUPPRESSION=F?

**Comment by drjfloyd** [comment]
1 kg of propane needs ~16 kg of air. This HoC means at stoichiometry your flame temperature would be under 1000 C and the default critical flame temperature is 1427 C.

**Comment by tstopi** [comment]
Hello Rand and Jason and thanks for the quick responses.

I did indeed suspect the extinction model but was still wondering if this was expected behavior. Jason pointed out that it is.

What I am trying to do is to simulate a fire source that has a certain effective heat of combustion and associated soot yield.  If the soot yield is 0.05 and effective heat of combustion is 16 MJ/kg, using 44 MJ/kg and 0.05 would lead to lower smoke production. 

I was just surprised since previously defining the heat of combustion on REAC line has worked just fine. However in retrospect, these cases were defined using a formula and therefore the specific heat was probably of and the critical flame temperature was not an issue.  

So I guess I will have to leave the Heat of combustion alone and multiply soot yields or turn suppression off.
