### ISSUE TITLE
Specifications for Dedicated Hardware to Run FDS Simulations

### ISSUE THREAD

**Issue by jameschampion20** [firemodels/fds#9433]
Hi All, 

Not an issue with the code as such, but I am currently researching options for dedicated hardware for running complex FDS simulations and was wondering if you please let me know what are the vendor recommendations relating to this?
It is likely we would opt for either a desktop or a cluster, and the faster the simulations run, the better. 

Many thanks for your help,

James

**Comment by mcgratta** [comment]
This is a question that is better posted to the Discussion Group. We at NIST use dedicated linux clusters for running FDS. If you rely on Windows desktops, you will be severely limited in what you can do.
