### ISSUE TITLE
Possible conflict in constructing divergence array

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9436]
Yesterday I was doing some house cleaning in the code and removed PROJECTION as an option. That is, the current PROJECTION=T is the only option and the logical parameter PROJECTION has been removed. This allowed me to remove some other baggage associated with the old scheme, like D_CORR and DS_CORR which were needed for correcting DDDT, i.e. dD/dt, the time derivative of divergence. 

Anyway, look at the latest divg.f90 and search on DDDT. Notice that in the CORRECTOR phase of the time step we point to DDDT
```
DP => DDDT
```
simply as a way to use its space while we construct D. This goes back to the old way of doing things, where D and DS needed to be saved while a new D was constructed. We no longer need to save D from the PREDICTOR phase, so I thought it would make the code easier to understand to point to D instead of DDDT
```
DP => D
```
in the second phase. However, when I ran the verification cases, a few were out of tolerance, like leak_test_4.fds and leak_test_3.fds. These involve GEOM obstructions. My first thought was that somehow D is being used somewhere during the construction of the new D, but I cannot find it. Could you take a look at the GEOM routines that are called to see if we are "touching" D while we are constructing a new D.

**Comment by marcosvanella** [comment]
I'll have a look.

**Comment by marcosvanella** [comment]
Kevin, did you also change DP to D for the corrector in CCREGION_DIVERGENCE_PART_1, ccib.f90?

**Comment by mcgratta** [comment]
No. Look at the History of changes to ccib.f90 to make sure that I did not
accidentally change something like that.

**Comment by marcosvanella** [comment]
Ok, I think that's missing, we want to push down the divergence computed in cut-cells to the right container. 
Do we also need to make changes to have consistency in divergence_part_2, divg.f90? Looks we need to make DP => D in line 1654, and drop D = DDDT in line 1825.

**Comment by mcgratta** [comment]
Yes, the D=DDDT line is not needed if we DP=>D at the start. That's another
reason to do this, to save a bit of CPU time.

>

**Comment by marcosvanella** [comment]
This should be addressed in PR #9439.
