### ISSUE TITLE
Too much oxygen

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#9443]
Good morning All,

I've been reviewing a file created by someone else. It has various components copied and pasted from other sources. It starts with almost twice as much oxygen in the atmosphere as expected. I've stripped out everything but a simple fire and reaction, and the problem persists (see only_fire.fds). I have a vague memory of running into a problem many years ago where there appeared to be hidden characters in a text file that was the source of a problem. 

Has anyone seen this sort of thing before? Is there an obvious way to prevent it?

Thanks

Dave

[only_fire.fds.txt](https://github.com/firemodels/fds/files/6325334/only_fire.fds.txt)

![only_fire fds O2 volume fraction](https://user-images.githubusercontent.com/13259079/115031001-b04bb780-9e95-11eb-8d0b-1ba932ce63e5.PNG)

**Comment by mcgratta** [comment]
There is no need for that OXYGEN line. The default mode of FDS is to create a BACKGROUND gas called AIR, which has oxygen as one of its components. Here, FDS thinks you want to add an additional amount of OXYGEN.

**Comment by Dave-McGill** [comment]
Thanks Kevin
