### ISSUE TITLE
problem with HRRPUL and XB

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9449]
No good deed goes unpunished.  The Heskestad cases now throw an error, my guess is the new line DEVC and SPATIAL_STATISTIC='INTERPOLATION'.

```
ERROR: DEVC QUANTITY HRRPUL requires coordinates using XB (CHID: Qs=1_RI=05)
```

**Comment by mcgratta** [comment]
OK, I'll fix.

**Comment by mcgratta** [comment]
Should work now. Double check and then close.

**Comment by rmcdermo** [comment]
Thanks.  The cases are off the ground now.
