### ISSUE TITLE
Radiant heat flux obtained from FDS is lower than the published research with the same parameter settings

### ISSUE THREAD

**Issue by StarAlex-Wang** [firemodels/fds#9453]
Hello friends,
I got a question here: I set the radiative heat flux gas devices in FDS at the place L/D=2 (D=20m) on the height of 1.2m as experiment sets. However, the values I obtained in FDS is much lower than the experiments results. May some mistakes I set in my FDS profile is wrong? I would be very grateful if someone helps me. 
Attached is the fds profile, and best regards for you.
[validation.zip](https://github.com/firemodels/fds/files/6365903/validation.zip)

**Comment by mcgratta** [comment]
There are many reasons why your model might be different than the experiment. But we do not have to time to study the experiment and your modeling approach. We would prefer that you try a simple verification example where there is a known exact answer. If there is a problem, post all the details here.

**Comment by TristanHehnen** [comment]
There was a [discussion in the FDS Google Group a while ago](https://groups.google.com/g/fds-smv/c/HnDhHeWHHzM/m/AzZD8v7RBgAJ), maybe you could try to adjust the PATH_LENGTH, as was suggested in the discussion.
