### ISSUE TITLE
Underscores in parameter values

### ISSUE THREAD

**Issue by tgob** [firemodels/fds#9459]
Hi folks.

There seems to be a problem with TEMPORAL_STATISTIC='TIME AVERAGE' and SPATIAL_STATISTIC=’VOLUME INTEGRAL’ in FDS 6.7.5.

The output error is forrtl: severe (157): Program Exception - access violation.

 Starting FDS ...

 MPI Process      0 started on I9

 Reading FDS input file ...

ERROR: Problem with DEVC number 21, line number 224 (CHID: Controls)
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds.exe            00007FF7C52E0686  Unknown               Unknown  Unknown
fds.exe            00007FF7C4A2B633  FDS_ip_END_FDS           1698  main.f90
fds.exe            00007FF7C4A0E03C  MAIN__                    121  main.f90
fds.exe            00007FF7C49CF09E  Unknown               Unknown  Unknown
fds.exe            00007FF7C5366664  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF325A7034  Unknown               Unknown  Unknown
ntdll.dll          00007FFF33BC2651  Unknown               Unknown  Unknown

If I add underscores to the parameter values within the single quotes: 'TIME_AVERAGE' and ’VOLUME_INTEGRAL’ then my model runs, but I have yet to assess the device output to see if the temporal and spatial statistics are actually working as anticipated.

Maybe this has something to do with the the removal for the need for underscores in output quantity names as described in Sect. 21.12 on page 318 of the FDS Users Guide?

With kindest regards,

Tim

**Comment by mcgratta** [comment]
I'm not sure that there were ever underscores in these names. My guess is that FDS is just ignoring character strings it does not recognize. I don't think we added a trap for misspelled stats names. Do you have a simple example of the failed input file?

**Comment by tgob** [comment]
Thank you for your quick reply Kevin.  I don't have a simple example but I'll try writing one for you tomorrow.  On further reflection I may be trying to get FDS to do something non-sensical.

I'm trying to make a reliable measure of the onset of vitiated combustion in a compartment.  I figure there are three options.  The differential between specified HRR (simple ramped HRRUPA combustion model) and measured HRR, O2% in the plume, or EXTINCTION.  Point measurements are proving to be problematic due to relatively high frequency noise from turbulence.  Smoothing (SMOOTHING_FACTOR=x) helps, but as you might expect, this results in typical low pass filter lags.  I was experimenting with volume integrals over the plume and compartment to see if I could reduce the noise.

Any advice that you might care to offer would be appreciated.  I have read several several papers on this issue (e.g. Nelson 1990) but my literature search has not been very thorough.

With kindest regards,  t.

**Comment by mcgratta** [comment]
The problem with oscillations like this is that it is difficult to know if
it results from non-sensical inputs, or numerical issues, or both. I'll
play with it a bit more. In the test cases you sent, where there are two
exhaust ducts open to the atmosphere, where did the various duct parameters
(lengths, loss, node height at exit) come from? I don't have a good feel
for what a typical loss coefficient would be, and if you do a search on the
subject, you find that there are various definitions of loss
coefficient/factor, some dimensional, others not.

>

**Comment by tgob** [comment]
Thank you for your further response but I am somewhat confused by it.  I haven't sent a test case yet and my model doesn't ducts or consideration  of loss coefficients.  I'll get back to you tomorrow after further considerations.

With thanks,

t.

**Comment by mcgratta** [comment]
Whoops -- sorry. I was replying to the wrong thread. Getting old.

>

**Comment by mcgratta** [comment]
You could try

&DEVC ID='local HRR', XB=..., QUANTITY='HRR' /

This will produce the HRR over a volume specified by XB. Put the volume
over the fire and its immediate surroundings. Even if the fire moves
towards the source of incoming O2, you can still see if the fire is no
longer burning in its original location.

>

**Comment by tgob** [comment]
Dear Kevin,

the attached model shows the issues that I'm having.  Maybe I am doing something silly (quite possible) but the point devices show expected behavior and this should be reflected in the spatial statistics.

Your earlier comment about FDS ignoring character strings that it doesn't recognize appears to be correct.  Perhaps it might be useful if this were reported as an initialization error?   


[Stats.txt](https://github.com/firemodels/fds/files/6396582/Stats.txt)

**Comment by mcgratta** [comment]
OK, I'll take a look.

**Comment by mcgratta** [comment]
This might be part of the problem:
```
/****  Stats Devices
&DEVC ID='HRRplume', QUANTITY='HRR', XB=2.6,3.6,1.6,2.6,0.6,2.2/  Volume integral above fire area
&DEVC ID='O2plume', QUANTITY='VOLUME FRACTION', SPEC_ID='OXYGEN', XB=2.6,3.6,1.6,2.6,0.6,2.2, SPATIAL_STATISTIC=â€™MEAN'/
&DEVC ID='EXTplume', QUANTITY='EXTINCTION', XB=2.6,3.6,1.6,2.6,0.6,2.2, SPATIAL_STATISTIC=â€™MAXâ€™/

/Notes:
/SPATIAL_STATISTIC=â€™VOLUME MEAN' fails with forrtl: severe (157): Program Exception - access violation
/SPATIAL_STATISTIC=â€™VOLUME_MEAN' runs but with 0.00 output in the Stats_decv.csv file.
/SPATIAL_STATISTIC=â€™MEAN' or 'MAX' runs, but with 0.00 output in the Stats_decv.csv file.
/****
```
What kind of text editor did you use to write this file?

**Comment by mcgratta** [comment]
This works
```
&DEVC ID='HRRplume', QUANTITY='HRR', XB=2.6,3.6,1.6,2.6,0.6,2.2/  Volume integral above fire area
&DEVC ID='O2plume', QUANTITY='VOLUME FRACTION', SPEC_ID='OXYGEN', XB=2.6,3.6,1.6,2.6,0.6,2.2, SPATIAL_STATISTIC='VOLUME MEAN'/
&DEVC ID='EXTplume', QUANTITY='EXTINCTION', XB=2.6,3.6,1.6,2.6,0.6,2.2, SPATIAL_STATISTIC='MAX'/
```
But 'EXTINCTION' is not a good point quantity. That should be a SLCF file.

**Comment by tgob** [comment]
Thank you Kevin.  Yes, that works.  How on earth did you spot the invisible offending â€?  

My standard FDS text editors are gedit (Linux) and MS Notepad (Windows).  I'm not sure how â€ got into the file, but once it was there I cut and pasted to other lines.  Apparently the character â€™ (Unicode codepoints U+00E2 U+20AC U+2122 ) is encoded in UTF-8 as bytes.  Seems like a double conversion from Windows-1252 to UTF-8 has turned ' into â€™'.

Your comment regarding EXTINCTION as a point quantity is noted.

**Comment by mcgratta** [comment]
On a Windows computer, I use Wordpad. I don't like Notepad because it is
too simple. The bad characters showed up in Wordpad.

On linux, I just use the native vi editor. It catches this sort of thing.

>

**Comment by tgob** [comment]
Looks like I’ll be changing my editing environments!  Thank you again.  t.

**Comment by rmcdermo** [comment]
You can also use [Sublime Text](https://www.sublimetext.com/) and add our [FDS syntax highlighting](https://github.com/rmcdermo/SublimeFDS).  Then you see this and immediately know something is wrong:

<img width="451" alt="Screen Shot 2021-04-29 at 4 47 37 PM" src="https://user-images.githubusercontent.com/4418497/116616580-d861fe80-a90a-11eb-9d62-8d0eb272b096.png">
