### ISSUE TITLE
forrtl 157 crash with zero wind speed

### ISSUE THREAD

**Issue by H-Boehmer** [firemodels/fds#9485]
Not most the most important bug but took me a minute to figure out why it crashed. Running a simulation with &WIND namelist group and setting wind SPEED=0, and L= non-zero will result in a forrtl error after one timestep:
forrtl: severe (157): Program Exception – access violation

Any windspeed above zero works. As does removing L or setting to zero. Attached test case. 
[windtest.fds.txt](https://github.com/firemodels/fds/files/6430164/windtest.fds.txt)

**Comment by rmcdermo** [comment]
Thanks for the report.  We probably need to do a few consistency checks for the WIND parameters.  I'll take a look.

**Comment by rmcdermo** [comment]
This was a simple divide by zero when SPEED=0.  Should be fixed now.  Thanks for the simple bug report---very helpful.  I'm putting this in for a Boris.
