### ISSUE TITLE
GLMAT pressure solver

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#9498]
From @tden033
[fire.txt](https://github.com/firemodels/fds/files/6455077/fire.txt)

Hi,
I am trying to model the pressure drop in a long tunnel, so I selected the GLAMT pressure solver as suggested. The GLMAT solver requires the meshes are at a same refinement level, and I did so. Specifically, I used 6 meshes and tried 4 different refinement levels ( uniform cell with the size of 0.13m, 0.2m, 0.26m, 0.4m). The 0.2m and 0.26m schemes were found running well, however, I was informed of the following error when running with the 0.13m and 0.4m cells.
"GLMAT Setup Error : Meshes at different refinement levels unsupported."

This is weird because I didn't change anything but the cell size and have made sure the cells are of the same size.
Also, when I increased the mesh quantity from 10 to 11, the same error occurs even with the 0.2 m cells.
So anyone had the same issue?
For your convenience, the code is attached below.
Your help will be much appreciated.
fire.txt

Regards
Tao

**Comment by marcosvanella** [comment]
@tden033 what fds version and OS are you running?

**Comment by tden033** [comment]
> @tden033 what fds version and OS are you running?
I tried 6.7.3 and 6.7.5., and both were running on a window 10 desktop.

**Comment by marcosvanella** [comment]
Tao, I can't reproduce the problem with the 11 mesh case you sent. At some point we fixed an issue related to the threshold used for cell size comparison between meshes. Please install the nightly bundle and test on your side:
https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC
There is a maintenance release coming up most probably this week.

**Comment by tden033** [comment]
> Tao, I can't reproduce the problem with the 11 mesh case you sent. At some point we fixed an issue related to the threshold used for cell size comparison between meshes. Please install the nightly bundle and test on your side:
> https://drive.google.com/drive/folders/1X-gRYGPGtcewgnNiNBuho3U8zDFVqFsC
> There is a maintenance release coming up most probably this week.

Many thanks, Marcos.
The version you sent works perfectly and it fixed all the issues :)
