### ISSUE TITLE
Getting the error: -bash:~/FDS/FDS6/bin/fds: cannot execute binary file : Exec format error

### ISSUE THREAD

**Issue by Alina528** [firemodels/fds#9519]
I installed the FDS-SMV for Linux.When I run the command
 `fds`
I get the error the error :
`-bash: /vol7/home/rocket/FDS/FDS6/bin/fds: cannot execute binary file: Exec format error`
When I run `uname -a` I get:
`Linux ln0 3.14.57-20160427.kylin.4.server #18 SMP Wed Jul 27 09:51:55 CST 2016 aarch64 aarch64 aarch64 GNU/Linux`
/proc/cpuinfo shows
`flags	: fp asimd evtstrm aes pmull sha1 sha2 crc32`
How can I run the program

**Comment by gforney** [comment]
Looks like your cpu is a 64 bit arm chip ( aarch64 ).  Fds runs on intel
and amd cpus. If you want to run fds on some other type of hardware you
will have to build it yourself.  T
