### ISSUE TITLE
OBST disappear with BURN_AWAY and SURF_IDS/SURF_ID6, but stay with BULK_DENSITY

### ISSUE THREAD

**Issue by TristanHehnen** [firemodels/fds#9520]
I wanted to set up single cell thick slabs, where the top and bottom face are with a combustible material, while the other faces are INERT, using the SURF_IDS/SURF_ID6 parameters. I forgot to remove the BURN_AWAY parameter and when I ran the simulation the respective obstructions just disappeared. After some debugging it turned out that using BULK_DENSITY in the OBST line and SURF_IDS/SURF_ID6 in the SURF line the obstruction stays and also burns away. 
This behaviour seems a bit inconsistent. 

I've prepared an input file to demonstrate the behaviour, based on the box_burn_away1.fds example. It contains four slabs, two with SURF_IDS and two with SURF_ID6. One of each got a BULK_DENSITY, which stay and seem to be consumed "normally".
[SURF_IDS.fds.txt](https://github.com/firemodels/fds/files/6500283/SURF_IDS.fds.txt)

FDS version:
 Current Date        : May 18, 2021  11:36:52
 Revision               : FDS6.7.5-0-g71f025606-release
 Revision Date       : Thu Aug 20 16:19:01 2020 -0400
 Compiler              : Intel ifort 19.1.1.216
 Compilation Date : Fri 08/21/2020  04:51 PM

**Comment by rmcdermo** [comment]
Thanks Tristan.  We'll take a look.

**Comment by mcgratta** [comment]
The BULK_DENSITY feature was designed for cases where the OBST has a single SURF_ID. The idea is that even though the 1-D heat conduction on each cell face is not quite right, the overall mass loss of the object should be maintained. At start-up, FDS sets boundary properties cell face by cell face on the OBST. If a corner cell of the OBST has multiple SURF_IDs, it either applies the first or last, I forget which. In any case, I suggest only assigning one SURF_ID to a burn-away OBST.

**Comment by rmcdermo** [comment]
I'm confused by this description.  Where do we stand on this issue?  Leave as is?  Throw an ERROR if more than one SURF_ID is used with BURN_AWAY?

**Comment by mcgratta** [comment]
When the mass of a cell decreases to zero, the cell is removed and all 6 faces should be set to NULL. Thus, it should be OK to have different SURF IDs assigned to different faces of an OBST. If any of the SURFs indicate BURNAWAY, the OBST should disappear when its mass goes to zero. Is this what is happening in the example?

**Comment by mcgratta** [comment]
We should probably stop a case like this with an ERROR. The fact that the middle two OBSTs have at least one SURF_ID with BURN_AWAY forces FDS to break these OBSTs into single OBSTs. Then it looks at the exposed side faces and sees the INERT SURF_ID, and it assigns these OBSTs no mass. On the first time step, FDS says that these OBSTs have no mass and they are removed. The BULK_DENSITY and BURN_AWAY attributes are really designed for OBSTs that have the same SURF_ID on all sides.

**Comment by mcgratta** [comment]
BULK_DENSITY isn't consistent with that approach. It is assumed that the burning occurs on all exposed faces and that the mass per unit volume is the same.

**Comment by rmcdermo** [comment]
OK, then can we throw an error for this setup?

**Comment by drjfloyd** [comment]
If my OBST is one cell thick, the top is foam then wood, and the OBST bottom is wood then foam, then I have the exact same mass of both materials from the top as from the bottom. Now I need to make some choice about the sides (recognizing that here I might get some error in terms of the ratio of wood to foam MATL), but I won't exceed the total mass that is actually present as BULK_DENSITY will make sure that happens. As a user I might decide the error in any side burning is acceptable for my specific application. I could also define the sides to have an extremely high ignition temperature such that they never ignite.

**Comment by mcgratta** [comment]
I finally have some time to look at this. The posted input file violates this rule
![image](https://github.com/firemodels/fds/assets/11333911/51512eda-072e-4e6e-8716-c2fcc8e90b95)
so I added an `ERROR` to catch it. If `BURN_AWAY` and multiple `SURF_ID`s are applied to the same `OBST`, there is no way to know when to remove the `OBST`. However, if you add a `BULK_DENSITY`, then it is OK to have multiple `OBST`s.
