### ISSUE TITLE
Restarting FDS jobs in clusture

### ISSUE THREAD

**Issue by ritambhara123** [firemodels/fds#9522]
Hello,
I have a question regarding restarting FDS job in HPC. When I create the CHID.stop file, the case doesn't stop. Am I missing out on something?

Any help would be appreciated.
Thank you!

**Comment by mcgratta** [comment]
The job will not stop instantly. It typically runs through up to 15 more time cycles to completely finish a full radiation update. That being said, older versions of FDS did sometimes fail to stop. So in your current case, wait for 5 or 10 minutes, and also try using the latest code. If it still doesn't stop, post the case.

**Comment by ritambhara123** [comment]
Thank you Kevin! I will try your suggestions.

Regards,
Ritambhara

________________________________
