### ISSUE TITLE
Add source code in FDS

### ISSUE THREAD

**Issue by Evil-Doctor** [firemodels/fds#9524]
Hi ALL,
       
I am having some issues with add source code in FDS Version 6.7.5. I have attached the code below and any help / suggestions with this would be great. I want to add this code to FDS6.7.5, but I have encountered some problems. I have compiled and linked through, but it cannot run. Below is the source code I want to add and some modifications to the main program.cons read mesh module has also been modified

![T_MIN_A](https://user-images.githubusercontent.com/81680065/118746859-8f5af580-b88b-11eb-8098-d1af7cce7945.png)
![T_MIN_A2](https://user-images.githubusercontent.com/81680065/118747150-1314e200-b88c-11eb-95dd-663b238fd0b7.png)
![T_MIN_A3](https://user-images.githubusercontent.com/81680065/118747426-8cacd000-b88c-11eb-9f9e-1601222f9554.png)

My guess is that I have a problem with the avag module, because the member can run before calling avag.But i don't know how to modify.
There are DT and TNOW in the mesh module of fds4, but there is no DT and TNOW in the mesh module of fds6. The correspondence between DT and TNOW is also my problem.

Please let me know your thoughts when you get a chance and if you require any further information.

Many thanks for your help,

**Comment by mcgratta** [comment]
I doubt very much that you will be able to call an FDS 4 routine without changing the names of many variables. You will have to rewrite the subroutine and then call it appropriately. What exactly do you want to do?

**Comment by Evil-Doctor** [comment]
Hi mcgratta, thanks for your answer. I have changed the name, and the following is the rewritten module. What I want to do is to generate a tecplot readable TXT file from the data obtained by FDS, such as average velocity and fluctuation velocity. After my modification yesterday, the program can now be run, but the txt file cannot be generated.

**Comment by mcgratta** [comment]
I suggest that you generate Plot3D files and read them into Tecplot. Or you can write a Python or Matlab script to read the FDS output files. The formats of these files are in the User's Guide. I don't think you understand the data structures used by FDS. For example, POINT_TO_MESH assigns pointer variables to the derived data types contained within MESHES. 

Try reading the Plot3D files first before trying to modify the code.

**Comment by Evil-Doctor** [comment]
First of all, thank you for your suggestions and answers. Yes, I don't know much about the data structure used by fds. But I am a student now, I want to learn FDS and fortran by modifying the code. Because I want to add a turbulent inlet boundary condition for simulation.
I encountered a new error with avag, can you help me answer it? The following is my error message, as shown in the figure.
![error](https://user-images.githubusercontent.com/81680065/119109062-6c7b3d80-ba53-11eb-8feb-0a69bb2d9d86.png)

Thanks again for your help

**Comment by Evil-Doctor** [comment]
First of all, thank you for your suggestions and answers. Yes, I don't know much about the data structure used by fds. But I am a student now, I want to learn FDS and fortran by modifying the code. Because I want to add a turbulent inlet boundary condition for simulation.
I encountered a new error with avag, can you help me answer it？

I added this avag and it can run, but when it is called, there will be an error. The following is my error message, as shown in the figure.
![error](https://user-images.githubusercontent.com/81680065/119110138-689beb00-ba54-11eb-8723-4febb6fa9d2d.png)
Thanks again for your help

**Comment by mcgratta** [comment]
There already is a turbulent inlet boundary condition in FDS. Why do you want to add another one?

As for your coding, you need to add debugging flags during compilation (like -g and/or -traceback) and then (hopefully) the program will produce a line number where the error occurred. The makefile in the Build directory of the fds repository has targets labelled with a `_db` that show the compiler flags for different compilers.

**Comment by Evil-Doctor** [comment]
Because I want to compare the same turbulence inlet boundary conditions between openfoam and FDS. The accuracy of SEM in FDS is limited. My research group has used SEM and other methods on openfoam to conduct simulation and experimental comparisons, but the results are not very satisfactory. Afterwards, the research group proposed An improved RFG method, and the simulation results on openfoam were very successful, and were very close to the experimental values. I want to embed this method into FDS for simulation and compare the advantages and disadvantages of the two softwares.
Thank you for your help and guidance.

**Comment by mcgratta** [comment]
Please post your input file for the FDS simulation that you say was not successful, and cite the experimental data. It is very common that a CFD user obtains "unsatisfactory" results because he/she is not familiar with all the features of a particular code. I read and review many papers in the literature that claim that a particular method "does not work" but a new method developed by the same research group "works very well." Thereafter, this claim becomes truth, and we start to see more and more complex methods developed based on the original misconception.

We can look at your case and tell you  within a few days if there is a need for improvement in the inlet boundary condition. Given your unfamiliarity with Fortran and with FDS, it will take you months to learn how to implement this new method, and if it turns out that this new method yields similar results to the old, then you will have wasted all your time.
