### ISSUE TITLE
Simulation stuck on sprinkler activation

### ISSUE THREAD

**Issue by fseitalia-enrico** [firemodels/fds#9535]
Dear developers,
I set up a simulation in which I inserted sprinklers to verify their activation time.
I accidentally placed some of them exactly on the top surface of a beam so that the "top" of the sprinkler would be invested by the heat, thus increasing its temperature and eventually activating, and the "bottom" would release water inside the solid obstruction.
I was interested in verifying the activation time, so I set an extremely low water flow upon activation. Once the first sprinkler positioned on top of the beam activated, the simulation would not proceed further, nor send any warning or error and stop itself.
I wonder if this is the intended behaviour of the program.
Thank you,
Enrico

**Comment by rmcdermo** [comment]
Please attached an input file.

**Comment by fseitalia-enrico** [comment]
Attached to this message are:
- [sprinkler_loop.fds.txt](https://github.com/firemodels/fds/files/6545394/sprinkler_loop.fds.txt)
- [sprinkler_loop.out.txt](https://github.com/firemodels/fds/files/6545393/sprinkler_loop.out.txt)


Here is an image of the position of the sprinkler:
![sprinkler](https://user-images.githubusercontent.com/84788702/119635962-78308080-be14-11eb-8482-437f0754358f.png)

**Comment by mcgratta** [comment]
Contrary to what you see in Smokeview, a sprinkler is just a point in space. When it activates, it creates water droplets over a semi-spherical surface. In your case, this surface is completely embedded within a solid. FDS is endlessly trying to create gas-phase water droplets and failing. You are in an endless loop. Do not do this.

**Comment by fseitalia-enrico** [comment]
I imagined this was the cause.
What I am wondering is: is this the expected behaviour of the simulation? Should it give the user some kind of warning or is it unable to detect it's stuck in a loop?

**Comment by mcgratta** [comment]
It is difficult to produce a warning because it is possible to have the spray pattern partially blocked, in which case FDS randomly searches for a gas phase cell to inject the droplet. In your case, there is no end to the random search, but it is difficult to determine when to call it off.
