### ISSUE TITLE
FDS User Guide

### ISSUE THREAD

**Issue by boris-stock** [firemodels/fds#9552]
FDS_User_Guide.tex
Line 2911

I think

\caption[Creating an {\ct OBST} **cone using** {\ct MULT} and {\ct SHAPE}]{Creating an {\ct OBST} rotated box using {\ct MULT} and {\ct SHAPE}.}

should be

\caption[Creating an {\ct OBST} **rotated box** using {\ct MULT} and {\ct SHAPE}]{Creating an {\ct OBST} rotated box using {\ct MULT} and {\ct SHAPE}.} ?

**Comment by mcgratta** [comment]
Thanks, Boris.
