### ISSUE TITLE
Use of DT_DEVC

### ISSUE THREAD

**Issue by Dave-McGill** [firemodels/fds#9558]
Good morning All,

I've been playing around with the early detection of a temperature detector. I've noticed a few times that when viewing a temperature slice file, a temperature device appeared to activate well before its setpoint. Plotting the device data showed that a single (outlier) data-point exceeded the threshold and triggered the device. 

I created a simple example (temperature_device_activation_4). With it, there was an outlier temperature value that triggered the detector at 43.6 s. I created another example (temperature_device_activation_5) that had "DT_DEVICE=5" added to the DUMP namelist. This averages the values of devices over 5 s. See the attached graph. However, the smoke detector still activated at 43.6 s, which surprised me. It appears that the detectors see the raw/unaveraged data, which was not what I expected. Is that what is supposed to happen?

Is there another way to make devices respond to smoothed data, rather than the raw/unaveraged data?

Thanks

Dave

[DT_DEVC values.xlsx](https://github.com/firemodels/fds/files/6624130/DT_DEVC.values.xlsx)
[temperature_device_activation_4.fds.txt](https://github.com/firemodels/fds/files/6624131/temperature_device_activation_4.fds.txt)
[temperature_device_activation_5.fds.txt](https://github.com/firemodels/fds/files/6624133/temperature_device_activation_5.fds.txt)

**Comment by rmcdermo** [comment]
Dave,
Thanks for the comments.  This issue is discussed in sec. `20.4 Basic Control Logic` of the latest user guide.  In short, control logic acts on instantaneous values and you need to add `SMOOTHING_FACTOR` if you want an averaged value.  Please let us know if this resolves your issue.

**Comment by Dave-McGill** [comment]
Randy,

That worked. There's always something new to be learned.  :-)

It would be useful if a column were added to _devc.csv showing the smoothed values. That would provide the user with a sense of how much the values were smoothed.

Thanks for the help.

Dave

**Comment by rmcdermo** [comment]
@drjfloyd I will let you comment on this.  I don't use CTRL much, but I understand the need for a user to know when something should have tripped.  Maybe in preparing for v7 it is a good time to think about this.

**Comment by drjfloyd** [comment]
If you want to see the smoothed value you, you should be able to do this now. You can have a CTRL ADD function that just takes the DEVC as input. Then add a CONTROL VALUE DEVC to output the value of that ADD function and set TIME_AVERAGED=F. I agree it could be useful to have this as an option for a smoothed DEVC to output both the smoothed and/or the unsmoothed value.

The normal DEVC output is averaged over DT_DEVC which might be 10s to 100s of timesteps making it already smoothed. The comparison of the two is only going to be a partial picture of how much smoothing is happening.

**Comment by Dave-McGill** [comment]
Thanks Jason

**Comment by drjfloyd** [comment]
Going to leave this open as a reminder to look into the extra ouptut.

**Comment by rmcdermo** [comment]
Would it be useful to output a new file, something like `CHID_ctrl.csv` that had an entry (row) for trip of a DEVC?  The columns could be the CTRL DEVC giving the value at trip.  The first column would be the Time.

**Comment by mcgratta** [comment]
We currently use the ctrl.csv file to plot sprinkler activation times.

**Comment by drjfloyd** [comment]
ctrl.csv does not contain sprinkler activation times for most sprinkler system inputs. Activation times are written to the .out file and to the .smv file. 

ctrl.csv is the logical state of anything CTRL input. It would only be the activation time if the sprinkler was an open head where the control function was the valve.

**Comment by mcgratta** [comment]
Right. I take the time when the control value changes from -1 to 1 or vis
versa.

>

**Comment by drjfloyd** [comment]
ctrl.csv only contains CTRL.  In most cases sprinklers are wet pipe sprinklers which use DEVC and PROP and not CTRL.

**Comment by mcgratta** [comment]
I do this

&DEVC XYZ=28.98,22.81,7.46, PROP_ID='K-11', OUTPUT=.FALSE., ID='Spr_53' /
&CTRL ID='Act53', INPUT_ID='Spr_53', FUNCTION_TYPE='ANY' /

This produces a ctrl.csv file with a column called 'Act53' which has values
of -1 until the sprinkler activates, when the values change to 1.

>

**Comment by Dave-McGill** [comment]
My request was so that I could plot the smoothed values against the _devc.csv values (which are admittedly also smoothed). I'm a visual kinda guy, and I wanted to see how many of the peaks were knocked off with differing values of SMOOTHING_FACTOR.

**Comment by drjfloyd** [comment]
Coming back to this issue. I will add a DEVC option OUPUT_SMOOTHED to write smoothed values. So if  you wanted to see both the smoothed and unsmoothed you would have two DEVC lines one with OUTPUT_SMOOTHED=T and one without. For writing smoothed outputs I think we want to force the TEMPERORAL_STATISTIC to be INSTANT VALUE. I don't think it makes sense to write this as time averaged smoothing.

For capturing the exact time that a DEVC or CTRL changes state, we currently write a summary at the end of the .out file but it only gives the last time a change happened and not what the value was. We could also write an ascii text log file. Anytime a DEVC or CTRL changes state, write the event to the log file and give the name of the DEVC or CTRL, the time, new state, and (for items that use a value) the value it was at when it changed.

**Comment by mcgratta** [comment]
I don't understand why TEMPORAL_STATISTIC can't do this. I'm trying to reduce the number of parameters on the DEVC line that do some sort of statistical averaging.

**Comment by drjfloyd** [comment]
I didn't think of that.  That is a good idea.

**Comment by drjfloyd** [comment]
https://github.com/firemodels/fds/pull/10148

Added TEMPORAL_STATISTIC='SMOOTHED' to DEVC and CHID_devc_ctrl_log.csv.  The first outputs the smoothed value of the device without time averaging over the output interval. The second is a logfile that writes every state change.  Below is an example (activate_vents.fds case). Time is the time of the state change, State is the new state. Value represents the value at the state change and is not written for purely logical control functions (e.g. ANY or ALL). Units is the units for the value and is only written for devices since we don't store units for control functions.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jfloyd/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jfloyd/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Time (s) | Type | ID | State | Value | Units
-- | -- | -- | -- | -- | --
3.00E+00 | CTRL | controller 1 | T | 3.00E+00 |  
5.05E+00 | DEVC | timer 2 | T | 5.05E+00 | s
5.05E+00 | DEVC | timer 5 | T | 5.05E+00 | s
6.00E+00 | CTRL | controller 1 | F | 6.00E+00 |  
6.05E+00 | DEVC | timer 6 | T | 6.05E+00 | s
7.05E+00 | DEVC | timer 7 | T | 7.05E+00 | s
8.10E+00 | CTRL | controller 3 | T |   |  
1.10E+01 | DEVC | timer 7b | T | 1.10E+01 | s
1.20E+01 | CTRL | controller 1 | T | 1.20E+01 |  
1.20E+01 | CTRL | controller 4 | T |   |  



</body>

</html>

**Comment by mcgratta** [comment]
If someone restarts the code after a power outage, say, will this log file have its entries between last saved restart and outage overwritten by the new run?

**Comment by drjfloyd** [comment]
I followed the APPEND logic used in other output files, so it should append in a restart.

**Comment by drjfloyd** [comment]
But now that I look at it I realize I am writing the file header on restart, i'll fix that.

**Comment by mcgratta** [comment]
There's a short subroutine called `APPEND_FILE` that is called after a restart to remove extra lines in, for example, the hrr.csv, devc.csv, and mass.csv files. This prevents having duplicate rows after a restart. Do you need to do with this new log file?

**Comment by drjfloyd** [comment]
Thanks for pointing this out. This would need to be done as there could be a state change between the restart file time and when the job died. I'll add this for the new file.

**Comment by drjfloyd** [comment]
done.

**Comment by mcgratta** [comment]
[This issue](https://github.com/firemodels/fds/issues/9974) points out the problem

**Comment by drjfloyd** [comment]
I am not sure how that issue relates to this new log file feature. The log file didn't exist before so can't have been the cause of that issue.

**Comment by mcgratta** [comment]
No, I was just pointing out that there is still (we think) a bug related to stopping a job and restarting from an earlier time. This new log file might help figure it out.

**Comment by drjfloyd** [comment]
I fixed an error I found where we weren't writing CONTROL%PREVIOUS_VALUE which is needed by PID functions but the case in that issue wasn't using PID. It looks like we are writing the DEVC and CTRL data we need to the restart file.

**Comment by mcgratta** [comment]
Yup, the case in question is so long that we cannot figure out what is wrong. All of our simpler versions work.
