### ISSUE TITLE
FDS Model not Starting with Fire Compartment Leakage Enabled

### ISSUE THREAD

**Issue by jameschampion20** [firemodels/fds#9564]
[66200708_BlockB_CC_FFWC_REV01.fds.txt](https://github.com/firemodels/fds/files/6648423/66200708_BlockB_CC_FFWC_REV01.fds.txt)

Dear All,

I am trying to include fire compartment leakage (via HVAC) into one of my common corridor models (see attached FDS code) and am having some issues with this. In particular, when a deactivate / activate control is added to the two vents, the model does not run and just stays at 0 seconds for a long time. When this control is removed, the model seems to start and run fine. However, the purpose of the control is to be an inverse to the fire compartment door openings as I believe that keeping the vents on throughout the simulation would reduce the amount of smoke that gets into the corridor when the fire compartment door opens.

Do you know why the simulation does not start when the leakage vent has a control assigned to it?
Is there a way of getting round this?

Many thanks for your help,

James

**Comment by mcgratta** [comment]
This file is very long and complicated. Please remove all possible lines except for those that cause the problem. Sometimes doing this is enough to identify the problem.

**Comment by jameschampion20** [comment]
[66200708_BlockB_CC_FFWC_REV01.fds - Reduced.txt](https://github.com/firemodels/fds/files/6648845/66200708_BlockB_CC_FFWC_REV01.fds.-.Reduced.txt)

Hi Kevin,

Please find attached a reduced version of the file. I have also attached the error message that I get: ERROR: VENT for ductnode has a DEVC_ID or CTRL_ID, VENT ID:##Vent17_FireRoom (CHID: 66200708_BlockB_CC_FFWC_REV01)



![Capture_Error](https://user-images.githubusercontent.com/68464009/121904643-46c71880-cd21-11eb-9269-3f74ef2af8f4.PNG)

**Comment by mcgratta** [comment]
Unless there is a typo on the error message, I believe that it is telling you that you should not assign a DEVC or CTRL to the VENT that is part of an HVAC construct. HVAC control logic is not managed by DEVC or CTRL functions.

**Comment by drjfloyd** [comment]
You cannot add or remove a VENT that is connected to an HVAC system. You need to use a DAMPER in a duct (you could also turn on or off a fan, or start or stop the VOLUME_FLOW or MASS_FLOW in a duct).  

FDS User's Guide 

12.2.3 HVAC Node Parameters

Note that a VENT being used for an HVAC system should not have a CTRL_ID or DEVC_ID. If you need
to turn on or off a VENT connected to an HVAC system, use a damper in the duct connected to VENT.

**Comment by jameschampion20** [comment]
Many thanks for your responses - I have now fixed the issue by using a DAMPER in a duct. 

I will continue to use this approach when modelling fire compartment door leakage. Presumably this is the recommended approach for FDS Version 6.7.5 onwards?

Thanks again.

**Comment by mcgratta** [comment]
Yes, glad it worked.
