### ISSUE TITLE
Extract data from slice

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#9577]
I want to extract data from a slice. I change SLICEDATAOUT from 0 to 1 in Smokeview.ini and start rendering the slice. I got the CVS file, but it contains only half of the cells. My case is 2x2x2m with 20 cells in each direction. The CVS file contains data from X=1m to 2m, 0 to 1m is missing. Is this a bug, or am i doing something wrong.

Enclosed : 
Excel file : LAF_2_17_sf_100 .xlsx with data form  &SLCF PBZ=1.0, QUANTITY='TEMPERATURE.
FDS case : LAF-test.txt
[LAF_2_17_sf_100 .xlsx](https://github.com/firemodels/fds/files/6679193/LAF_2_17_sf_100.xlsx)
[laf-test.txt](https://github.com/firemodels/fds/files/6679202/laf-test.txt)

**Comment by gforney** [comment]
not a bug.  smokeview outputs data the same way that fds does by mesh.  so if you loaded the Y=1.0 temperature slice and outputted data at tiime step 76, smokeview would output two csv files LAF_1_1_sf_76.csv for data in mesh 1 and LA_2_1_sf_76.csv or data in mesh 2

**Comment by fidran** [comment]
If I do this for X=1.0, there is only one CSV file, LAF_2 .......
Ok for Y=1.0 and Z=1.0
X=1.0 is the slice between MESH 1 and 2

**Comment by fidran** [comment]
I removed the local LAF.ini files for all my real cases. Now it is OK
