### ISSUE TITLE
Problems with temperature fluctuations in FDS

### ISSUE THREAD

**Issue by StarAlex-Wang** [firemodels/fds#9579]
Hello, I have some problems in explaining the results of temperature fluctuations. Details are shown:
I simulated an oil pool-fire with an area of 63 square meters, HRRPUA=1917kW/m2, the wind speed was set to 10m/s, and the existence of a windshield was considere
![图片1](https://user-images.githubusercontent.com/83077843/122659827-537abf00-d1ae-11eb-946f-3c47d9f3ce97.png)
![图片2](https://user-images.githubusercontent.com/83077843/122659831-57a6dc80-d1ae-11eb-855b-ec32456e541f.png)
d.(The windshield acts as an obstruction to block the wind) The temperature changes at 0.5m, 1m and 1.5m directly above the pool center are obtained. The temperature changes with a windshield are shown in Figure 1, and the temperature without a windshield is shown in Figure 2.
Here are the questions: 1. Why the temperature fluctuations in Figure 1 are so larger than that of Figure 2?
2.Why the temperature change in Figure 2 is so gentle？
Best Wishes and Great Grateful for you！

**Comment by mcgratta** [comment]
I don't believe that this is a problem. Assuming that the simulations both use the same MESH and DT_DEVC (sampling rate of device output), the noisier temperatures result from the turbulent wake downstream of the windshield, perhaps? In any case, look at a VECTOR=T SLCF of TEMPERATURE to assess the nature of the flow field in Smokeview.

**Comment by StarAlex-Wang** [comment]
OK, I will take a look, thank you very much.
