### ISSUE TITLE
Defining oriented velocity in a DEVC

### ISSUE THREAD

**Issue by marcosvanella** [firemodels/fds#9587]
We would like a quantity "NORMAL VELOCITY" or "ORIENTED VELOCITY" that will give the velocity in a given ORIENTATION defined for the device. If the device has a rotation given by MOVE_ID, then the ORIENTATION vector is rotated too, to keep consistency with other moved objects in the model.

- In the case defined below the device would be:

`&DEVC ID='VELN',  XB=1.00,1.00,0.00,0.00,0.05,1.95, QUANTITY='NORMAL-VELOCITY', ORIENTATION=1.,0,0, POINTS=20, MOVE_ID='Rot' /`

And the reported VELN would be:
a. =1 for U0=1, ROTATION_ANGLE=0,  i.e. u-velocity
b. =0 for U0=1, ROTATION_ANGLE=90, i.e. v-velocity
c. =1 for V0=1, ROTATION_ANGLE=90, i.e. v-velocity
d. =sqrt(2) for U0=1, V0=1, ROTATION_ANGLE=45, etc.

- FDS test case:

```
&HEAD CHID='test' TITLE='Test Normal velocity device.' /

&TIME T_END=10./
&MESH IJK=20,20,20, XB=-0.5,1.5,-0.5,1.5,0.,2./

&VENT MB='XMIN', SURF_ID='PERIODIC' /
&VENT MB='XMAX', SURF_ID='PERIODIC' /
&VENT MB='YMIN', SURF_ID='PERIODIC' /
&VENT MB='YMAX', SURF_ID='PERIODIC' /
&VENT MB='ZMIN', SURF_ID='MIRROR' /
&VENT MB='ZMAX', SURF_ID='MIRROR' /

&MISC NOISE=F /
&WIND U0=1., V0=0./

! Line Device:
&MOVE ID='Rot', AXIS=0.,0.,1., ROTATION_ANGLE=0/
&DEVC ID='VELN',  XB=1.00,1.00,0.00,0.00,0.05,1.95, QUANTITY='U-VELOCITY', POINTS=20, MOVE_ID='Rot' /

&TAIL/
```

**Comment by mcgratta** [comment]
Is there already a function in FDS that will rotate an ORIENTATION vector using the MOVE parameters? If not, I think I can use the existing `TRANSFORM_COORDINATES` with a special option for a normal vector.

**Comment by marcosvanella** [comment]
I don't think we have a rotation only version from the MOVE parameters. Yes a special option is reasonable, as we have all the info in TRANSFORM_COORDINATES. I think we just need the transformation matrix multiplication by the incoming vector and renormalization of the result.

**Comment by mcgratta** [comment]
Yes, I'll implement it.

>

**Comment by mcgratta** [comment]
I just implemented `ORIENTED VELOCITY`, and next I will allow the ORIENTATION to rotate. To use this output, you add `ORIENTATION` to the `DEVC` line.

**Comment by mcgratta** [comment]
Now the ORIENTATION vector should rotate according to MOVE_ID

**Comment by mcgratta** [comment]
I added `ORIENTED VELOCITY` to the User's Guide. Check that everything works.

**Comment by marcosvanella** [comment]
Yes, works correctly. Thank you.
