### ISSUE TITLE
Increase Fire velocity using "burner' surface

### ISSUE THREAD

**Issue by NTamoafo** [firemodels/fds#9597]
Hello, I am trying to create a fire at a constant velocity of approximately 18m/s at a constant temperature at 1200C. I am not able to however input such a parameter using the burner surface in FDS. Can I have any assistance on a possible way on going around this? Thanks.

Nigel

**Comment by mcgratta** [comment]
Fires do not have constant temperatures, and fire-induced flows do not have constant velocities. What you want is unphysical. My guess is that you are thinking about some kind of simplistic heat source that mimics a fire. In FDS, you  can blow air out of a vent with a temperature of 1200 C and velocity of 18 m/s, but this is not a fire. It is a hot flow.

**Comment by NTamoafo** [comment]
Okay, I may have to clarify a bit. The idea is based on requirement 49CFR PART 179 Appendix B, to create a torch fire with the torch having a flame temperature of 1200C and flame velocity of 18m/s, which is more physical. Is this possible to simulate in FDS?

**Comment by mcgratta** [comment]
These regulations go back to the days when fires were characterized by a temperature and velocity, which is not a good way to characterize a fire. Modern fire standards use the fire's heat release rate in units of kW or MW. In FDS, you can simulate a pool fire or a blow torch, but you need to know either the mass loss rate of fuel or a heat release rate. One does not input temperatures and velocities into FDS to describe a fire.

**Comment by NTamoafo** [comment]
Thank you, that information helps a lot. Is there a blow torch example in FDS I can reference to try and simulate, or are there any pointers you can give me in regards to doing that?

**Comment by mcgratta** [comment]
Describe what you mean by a blowtorch. Heat release rate? Fuel flow rate? Orifice size? Fuel type? Pre-mixture composition?

**Comment by NTamoafo** [comment]
Heat release rate of 33kw, with diameter of 0.076m. Fuel is propane. Yet to determine flow rate and pre-mixture composition that would translate to the desired velocity and temperature measurements.

**Comment by mcgratta** [comment]
33 kW / 46300 kJ/kg = 0.00071 kg/s propane

Area of orifice: 0.0045 m2

(0.00071 kg/s / 0.0045 m2) / 1.82 kg/m3 = 0.087 m/s

This doesn't seem like a blowtorch to me.

**Comment by NTamoafo** [comment]
So the propane gas flow rate is 3.833*10-4m^3/s

**Comment by drjfloyd** [comment]
@NTamoafo Did you mean 0.0076 m (7.6 mm) rather than 0.076 m (7.6 cm)? For the typical handheld blow torch you would buy in a hardware store, the nozzle is about a cm in diameter.

**Comment by NTamoafo** [comment]
0.076m is correct. Its actually a gas jet burner, but when you mentioned fds could simulate a pool fire and blow torch, my assumption was modelling it as a blow torch would be closest.

**Comment by mcgratta** [comment]
In FDS, you will specify a VENT on an OBSTruction with a specified HRRPUA (Heat Release Rate Per Unit Area). Call that whatever you want.

**Comment by NTamoafo** [comment]
Okay, I tried that but my main issue was getting a desired velocity measurement of the flame.

**Comment by mcgratta** [comment]
What do you mean by "velocity measurement of the flame"?

**Comment by NTamoafo** [comment]
So these are the requirements needed for my torch fire, of which you explained that it is an old way of characterising a fire:

The source of the simulated torch must be a hydrocarbon fuel with a flame temperature of 1,204 °C plus-or-minus 55.6 °C (2,200 °F plus or minus 100 °F), throughout the duration of the test. Furthermore, torch velocities must be 64.4 km/h ±16 km/h (40 mph ±10 mph) (17.9m/s) throughout the duration of the test.

So the latter part about the torch velocity is what I am referring to. In the model I am trying to get a sense of what the torch velocity is during the simulation.

**Comment by drjfloyd** [comment]
If you have 1200 C, 18 m/s, for 33 kW with a 7.6 cm diameter orifice, then you have a premixed flame. Your boundary condition is not fuel, but a fuel/air mixture.

**Comment by NTamoafo** [comment]
Okay so does that imply I can use the surface condition "supply" and use the airflow velocity as well as inputting the mass fractions of fuel/air to achieve this?

**Comment by mcgratta** [comment]
Yes, or you can specify MASS_FLUX (kg/m2/s) of each without specifying a
velocity. FDS would figure out the velocity.

>

**Comment by NTamoafo** [comment]
Okay, thank you.
