### ISSUE TITLE
Hi,I have Numerical Instability Error issue.

### ISSUE THREAD

**Issue by 94-Gabriel-13** [firemodels/fds#9602]
Hello, 
[Numerical Instability Error.txt](https://github.com/firemodels/fds/files/6723549/Numerical.Instability.Error.txt)

I'm making an indoor fire simulation model.
We modeled the interior of a building of size 21 x 15 x 2.4 (m).  And shortly after the fire, a VENT is created through the DEVC Code. And after a while, the door to the fire point opens. 
However, Numeric Instability occurs at about 25s to 30s. 

What part of my code might be wrong?

**Comment by mcgratta** [comment]
You put a 1 MW fire into a relatively small, sealed room. In 15 s, the over-pressure exceeds 1 atm, at which point your turn a fan on that blows air into the room at 5 m3/s. In a few more seconds the pressure exceeds 2 atm. Then objects in the room start to burn. This is not physical. Typical building construction could not handle these kinds of over-pressures. It is difficult to identify exactly what is failing in the code, but suffice it to say that you should make the case more realistic. Monitor the PRESSURE and TEMPERATURE using horizontal slices.

**Comment by 94-Gabriel-13** [comment]
@mcgratta 
Thanks for your help. I can solve that problem.
