### ISSUE TITLE
GEOM error with BNDF output

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9603]
@marcosvanella This is a toy case that seems to have broken sometime in the last month (7.6.7 release does not work, nor does latest source; but slightly pre-release does work).  The problem is somehow related to the BNDF.  If these are commented out, the case runs.

[burning_horn_test.fds.txt](https://github.com/firemodels/fds/files/6727260/burning_horn_test.fds.txt)

**Comment by marcosvanella** [comment]
I'll take a look

**Comment by rmcdermo** [comment]
@noellecrump2023 If you change the OBST to GEOM the case will work.  We are in the process of figuring out how to treat OBST/GEOM intersections.  For now, GEOM/GEOM intersections are allowed.

**Comment by noellecrump2023** [comment]
Aah Interesting, thanks.
I’ll check out how it runs when I tell blender to make the cube a geom
