### ISSUE TITLE
&SLCF anomalies

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#9637]
in the geom_channel.fds case if I replaced all the &SLCF lines with one of the following , the following happens

&SLCF PBX=0.5, QUANTITY='VELOCITY' / produces a geometry slice which is what I expect

&SLCF DB='XMID', QUANTITY='VELOCITY' / produces a cartesian slice (original)

&SLCF PBX=0.5, QUANTITY='VELOCITY', VECTOR=T / produces a cartesian VELOCITY, U_VELOCITY and W-VELOCITY slices (not geometry)

&SLCF DB='XMID', QUANTITY='VELOCITY', VECTOR=T / produces a cartesian VELOCITY, U_VELOCITY and W-VELOCITY slices (not geometry)

**Comment by marcosvanella** [comment]
Thank you Glenn! Let me do Randy the honors here.

**Comment by gforney** [comment]
these problems don't explain smokeview problems (at least some are are still there).  I'm working on it

**Comment by rmcdermo** [comment]
@marcosvanella You've been working this case quite a bit.  Are the SLCF issues sorted out?  Thanks

**Comment by marcosvanella** [comment]
The two sets of slices with and without VECTOR=T are consistent now. VECTOR=T puts the vectors in the nodes using cartesian interpolation, but cut-face velocities. It will maintain means for unstructured grids but is there is a loss of accuracy by using a centered interpolation to points not in the middle of two (or 4 in 3D) collocated face values.
________________________________

**Comment by rmcdermo** [comment]
Reopen if there is still a problem.
