### ISSUE TITLE
wui level set case using geometry for terrain crashes

### ISSUE THREAD

**Issue by gforney** [firemodels/fds#9651]
the case smv/Verification/WUI/BT10m_2x2km_LS.fds crashes with the following dump when I run with a debug fds (latest version)

 Starting FDS ...

 MPI Process      0 started on blaze.el.nist.gov

 Reading FDS input file ...

forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
fds_impi_intel_li  000000000C57D13B  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B8727B675F0  Unknown               Unknown  Unknown
fds_impi_intel_li  00000000005EB78E  physical_function        3640  func.f90
fds_impi_intel_li  0000000001F908B0  cc_scalars_ibm_mp        2177  ccib.f90
fds_impi_intel_li  0000000001F556F5  cc_scalars_ibm_mp        1418  ccib.f90
fds_impi_intel_li  0000000003C0FA89  velo_mp_compute_v         411  velo.f90
fds_impi_intel_li  000000000412E02B  MAIN__                    319  main.f90
fds_impi_intel_li  000000000040B422  Unknown               Unknown  Unknown
libc-2.17.so       00002B8729FE2505  __libc_start_main     Unknown  Unknown
fds_impi_intel_li  000000000040B329  Unknown               Unknown  Unknown
Aborted (core dumped)

**Comment by marcosvanella** [comment]
Glenn, do an update and try the case.

**Comment by gforney** [comment]
works, thanks!
