### ISSUE TITLE
Problem using small particles in a simulation (time steps decrease)

### ISSUE THREAD

**Issue by jsterckm** [firemodels/fds#9675]
Hello all,

I am currently working in my laboratory on burners with flames which are highly charged with particles (magnesium oxide). I tried to model my experimental set up on FDS but I have difficulties to do it, especially because of particles.

Indeed, the particles I am using in my simulation are very small (monodisperse particles with a radius of 2.5 microns). As a consequence, I have time steps which decrease very quickly (sometimes I have time steps of approximately 5E-5s) so the simulation become really too slow to perform. I saw in the file chid.out that the CFL number is close to 1. Thus, I have found the apparition of these little particles generates regularly local high velocity during one increment, which is responsible of the time steps decrease. I tried to do the same simulation but with larger particles (radius of 50 microns) and time steps are more appropriate, but unfortunately the particles size are really important for my works and I need to do simulations with particles of 2.5 microns… Are my particles too small for FDS simulations?

Please find below my file. I simplified the scenario by removing the fuel of the simulation, by changing the size of the domain, and by reducing the time of my simulation.

Thank you very much for your help,

Jean

[test_particles.fds.txt](https://github.com/firemodels/fds/files/6831009/test_particles.fds.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
At first glance, you are injecting these tiny particles with an initial velocity of 10 m/s with a mass flux of 5 kg/m2/s. Is that what you really want? This seems to be way too high of a mass flux of tiny particles, all of which drag the air according to the usual empirical correlation for spheres.

**Comment by jsterckm** [comment]
Thank you for your quick answer.
The mass flux of particles is the mass flux I want but I chose an initial velocity of 10 m/s in order to replace the fire for this test case. I tried to use different drag coefficients for particles but it didn't solve my problem.

For information, I also tried to do a simulation injecting particles directly in the whole domain instead of from the burner but the results about the time steps was exactly the same.

**Comment by mcgratta** [comment]
Check that you have put a / at the end of every input record.

Next, set an initial time step of, say, DT=0.001 s on the TIME line.

Next, try adding DRAG_COEFFICIENT=1 to the PART line. By default, FDS uses a drag law based on the Re number and particle size, which in your case is tiny, leading to high amounts of drag per particle which really isn't physical given that the particles really aren't independent of each other.

Think in terms of the absorption coefficient, kappa, as described in Section 17.4.3 of the latest User's Guide. kappa can be estimated as

kappa = C_s beta sigma

where C_s (shape factor) = 0.25, beta is the packing ratio (5 kg/m2/s) / (10 m/s) / (3580 kg/m3) , and sigma (surface area to volume ratio) is 3/r

I calculate beta to be relatively small, but kappa is about 40 1/m, meaning these tiny particles form something like a highly absorbing aerosol that also drags the flow considerably.

**Comment by mcgratta** [comment]
Also, the initial particle temperature of 1700 C applied to all these millions of particles causes a huge increase in divergence. I don't think that this is a well-posed scenario. Cut back on particle temperature and drag.

**Comment by jsterckm** [comment]
Hello Mr. McGrattan,

I followed your different recommendations about my simulation and it seems that the time step values are now much more appropriate, especially thanks to the "DT" specification on the TIME line.
Now I will be able to perform my simulations really much faster. Many thanks for your help!

**Comment by mcgratta** [comment]
OK, but proceed with caution. The FDS particle routines sometimes have trouble in these extreme cases. Often in the CFD literature, when particles get really tiny, the models begin to treat the collection of particles as an aerosol and solve a set of Eulerian rather than Lagrangian equations. That is, the model no longer treats the individual particle as an independent actor, but rather treats the entire collection. We do have an algorithm for aerosols, but it's a whole separate set of input parameters and assumptions. FDS only tracks a fraction of the actual droplets, and in your case of tiny particles, the ramifications of "zillions" of particles moving at high speed with high temperature may either by unphysical or beyond the FDS set of assumptions.
