### ISSUE TITLE
Wind Simulation - significant oscillations/ringdown

### ISSUE THREAD

**Issue by asbova17** [firemodels/fds#9699]
Hi All- I was running a complex terrain case with complex wind and temperature profiles and noticed that the wind speeds at the boundaries increased at around one hour of _simulated_ time. I massively simplified the case (attached) so that there is no terrain and no profiles, and reduced it to a single mesh with a constant westerly wind throughout the domain. Resolution is reduced so that it runs quickly. What you'll see is that, after a couple of time steps (2nd image is 20s of simulated time after the first), the flow suddenly varies significantly and then takes considerable time (~1.5 hours simulated time) to settle down (looks a bit like ringdown in a multi-mesh sim, but with only one mesh). 

The issue occurs in this release:
Revision         : FDS6.7.6-0-g5064c500c-release
Revision Date    : Thu May 27 12:19:10 2021 -0400
Compiler         : Intel ifort 2021.1
Compilation Date : Jun 01, 2021  13:04:27

as well as in an executable compiled from the most recent updates.

Any insight is appreciated!

[Input_No_terrain_Simple_Wind270_Test.fds.txt](https://github.com/firemodels/fds/files/6871402/Input_No_terrain_Simple_Wind270_Test.fds.txt)

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/60200922/126845288-4577fafe-2a0b-4866-90e3-af3c46d9f1fa.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/60200922/126845362-83a97782-c510-48a7-b8f4-77eafb31ab6f.png">

**Comment by mcgratta** [comment]
Thanks, Tony. I'll take a look.

**Comment by mcgratta** [comment]
There is some simple and fundamental explanation for this, but it escapes me at the moment. Consider this case:
```
&HEAD CHID='terrain_test' /
&MESH IJK=50,50,50, XB=-1488.,3227.,-2695.,1880.,0,4018. /
&TIME T_END=1000. /
&VENT MB='XMIN' SURF_ID='OPEN' /
&VENT MB='XMAX' SURF_ID='OPEN' /
&VENT MB='YMIN' SURF_ID='OPEN' /
&VENT MB='YMAX' SURF_ID='OPEN' /
&VENT MB='ZMAX' SURF_ID='OPEN' /
&SLCF PBY=0., QUANTITY='VELOCITY', VECTOR=T /
&WIND SPEED=2., DIRECTION=270. /
&TAIL /
```
On the MESH and TIME line, move the decimal of the XB and T_END one place to the left. Run it. Then two, run it. Then three. Each time the initial disturbance seems less severe. But I cannot figure out what is going on. I have to dig into the BC routine.

**Comment by asbova17** [comment]
Thanks, Kevin!

**Comment by mcgratta** [comment]
Things should work now. Try it. The problem was that we were not initializing both RHO and RHOS to account for the atmospheric stratification. Thus, on the corrector part of the time step, the RHOS ghost value at the top of the domain was ground ambient (1.2 kg/m3) instead of something like 0.75 kg/m3.  We never noticed this problem for relatively low domain heights.
