### ISSUE TITLE
MPI error issue.

### ISSUE THREAD

**Issue by 94-Gabriel-13** [firemodels/fds#9704]
Hello,
I am conducting an analysis using FDS v7.6 in Window 10.
But I entered it as below to apply MPI to speed up the analysis.

mpiexec -localonly -np 2 fds fds_name.fds

And I ran the fds analysis, and the error as below occurred.

ERROR: The number of MPI processes, 2, exceeds the number of meshes, 1 (CHID: fds_name)

No programs have been installed in the past.

How can we solve this?

**Comment by mcgratta** [comment]
You must divide your MESH into two meshes if you want to use 2 MPI processes. Read more in the User's Guide, chapter "Running FDS".
