### ISSUE TITLE
installer 

### ISSUE THREAD

**Issue by nratali123** [firemodels/fds#9725]
So I am experiencing an issue with installing and accessing the software to my PC - it stating ' access is denied' and that a path cannot be identified.
Fire dynamic simulator - 2016 edition - the link is -https://pages.nist.gov/fds-smv/downloads.html

[software.docx](https://github.com/firemodels/fds/files/6925852/software.docx)

**Comment by gforney** [comment]
do you have admin rights?  you need to have admin rights to install fds.

what version are you installing?  "2016 edition" is confusing me.

**Comment by mcgratta** [comment]
Do you have administrator rights to the computer?

Are you installing in the default location?

**Comment by nratali123** [comment]
so I am downloading the latest release which is:  FDS 6.7.6, SMV 6.7.16 version 

Apparently so, according to IT- I do have admin rights.

**Comment by gforney** [comment]
what version of windows are you using?

assuming windows 10

1. click on windows icon in lower left corner of your screen
2. click on the "gear" icon that that pops up up that has settings to the right 
3. click on Accounts
4. click on Your info that appears to the right of the Accounts window
what does it say below your user name?

also
cd into c: and type dir .  what does it list?

**Comment by nratali123** [comment]
'cd into c: and type dir . what does it list?' - what does this mean ? 

[admin.docx](https://github.com/firemodels/fds/files/6926147/admin.docx)

**Comment by gforney** [comment]
it means what does it show when you type dir

from the contents of admin.docx you posted you are not an administrtor on your PC.  on my PC it lists the text "Administrator" below my user name.

ask someone in your IT dept to make you administrator on your PC or asked them to install the software if that is not allowed

**Comment by nratali123** [comment]
when I type dir into the command- it highlights all the files on the directory. 

I will contact my IT department to allow access; although, I requested it and they confirmed I do

**Comment by mcgratta** [comment]
Any progress?
