### ISSUE TITLE
Problems with fire room settings

### ISSUE THREAD

**Issue by Evil-Doctor** [firemodels/fds#9729]
Hi everyone!
  I am now doing a verification of a standard fire room, but I have encountered some troubles and confusion, I hope everyone can help me answer it.
1. Can I replace the model of the heating plate with the surface of the given heat flux on the vent?
2. I have given three heating plates in the following case. In smokeview, the temperature change is not visible, but the calculation does not report an error, but the temperature can be seen by changing the number of heating plates to 2 or 1. Changed.
[room_fire.fds.txt](https://github.com/firemodels/fds/files/6931139/room_fire.fds.txt)

3. I have some experimental temperatures of discrete points, what method can be input to the temperature boundary conditions of fds.（Data similar to the figure below）
  
![image](https://user-images.githubusercontent.com/81680065/128179205-5d0a1a3d-8917-4a4d-8275-7beef40deb1a.png)

4. The near-wall turbulence model that I defined, is the global near-wall surface used by default after the misc definition?

thanks for your help

**Comment by rmcdermo** [comment]
Do not change all those defaults, turbulence models, etc.  The attached seems to run fine.
[room_fire_new.fds.txt](https://github.com/firemodels/fds/files/6931575/room_fire_new.fds.txt)
<img width="752" alt="Screen Shot 2021-08-04 at 9 23 31 AM" src="https://user-images.githubusercontent.com/4418497/128188623-72d83b66-9eb7-42dd-88ba-b65710bb7ca6.png">

**Comment by Evil-Doctor** [comment]
Thank you, I can run it now.
But I also want to ask the third question, can I add the experimental temperature value to the FDS temperature boundary condition?

**Comment by rmcdermo** [comment]
@Evil-Doctor No.  You cannot specify both a heat flux and a temperature on the boundary.
