### ISSUE TITLE
Error with spatial statistics device

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#9745]
In this example case, the device is intended to give the mass of the single particle at the center of the domain, but it is messed up by the presence of the obstruction within the integral volume. It returns 350 kg (should be ~3.9E-5 kg), despite the fact that the obstruction is made of a different material.

If you don't associate the obstruction with any material (comment out the MATL_ID line on the associated SURF line), it gives the correct result.

I could be wrong, but I think there are two issues:

1) If a device is associated with a PART_ID and only a PART_ID, then there should be a check to exit WALL_CELL_LOOP on line 6153 of dump.f90. In this case, the wall cells are being included in the integral.

2) There is an issue around assignment of the material index around line 8924 of dump.f90. Even if we _did_ want to include both wall cells and particles in the integration, the fact that the obstruction is not made of the material we define for the device should still exclude it. 
There should be some kind of exit condition If MATL_ID is not 'null', but is also not a member of SF%MATL_NAME. In this case, M_INDEX stays as zero, and line 8313 is executed (as if there were no material associated with the device at all).

[particle_bed_output_check.fds.txt](https://github.com/firemodels/fds/files/6940813/particle_bed_output_check.fds.txt)

**Comment by mcgratta** [comment]
I'll take a look.

**Comment by mcgratta** [comment]
&DEVC XB=0,1,0,1,0,1, ID='mass dry foliage', QUANTITY='SURFACE DENSITY', SURF_ID='foliage', SPATIAL_STATISTIC='SURFACE INTEGRAL', PART_ID='pine needle'/

This works. I don't recall what role MATL_ID plays on the DEVC line. My guess is that in this case, the MATL_ID on the DEVC line was ignored, and FDS integrated over all SURFaces. I'll see if we can add an error in this case, or clarify in the guide.

**Comment by mcgratta** [comment]
It appears that `MATL_ID` on the `DEVC` line only matters if `QUANTITY='SOLID DENSITY'`. We could add an error statement if `MATL_ID` is specified without `QUANTITY='SOLID DENSITY'`.

**Comment by ericvmueller** [comment]
This was a simplified example, but in my actual case I'm trying to track the evolution of specific materials associated with the foliage SURF (e.g. virgin material and char separately), hence the use of MATL_ID

**Comment by mcgratta** [comment]
I see. Let me delve in more.

**Comment by ericvmueller** [comment]
Okay - FYI I basically just copied the device definition from the WUI/char_oxidation2.fds verification case (which doesn't have the error since there are no wall cells in the device volume)

**Comment by mcgratta** [comment]
If you include both the MATL_ID and SURF_ID on the DEVC line, does that work?

**Comment by ericvmueller** [comment]
Yup, was about to say that could be a workaround

**Comment by ericvmueller** [comment]
Would it then make sense to have the device automatically inherit the SURF_ID if PART_ID is defined?

**Comment by mcgratta** [comment]
Check out what I just did. This seems fairly safe because it says that if the user specified a MATL_ID and none of that MATL is in the SURFace, return zero.

**Comment by ericvmueller** [comment]
Makes sense to me, and my original example works fine with that change, so I'll close this out. Thanks!
