### ISSUE TITLE
Error using qgis2fds bingeom file in latest fds nightly bundle test file

### ISSUE THREAD

**Issue by asbova17** [firemodels/fds#9765]
Hello all - There's a new error popping up when I try to use a qgis2fds bingeom file with the latest test release of fds (FDS6.7.6-387_SMV6.7.17-128):

"ERROR: problem with GEOM Terrain, number of surfaces in SURF_ID field (      19) not equal to number of surfaces (      18) defined in bingeom"

It also occurs when when I use an fds executable compiled about 2 weeks ago. The same bingeom file works fine when I use the last official release (FDS6.7.6-0-g5064c500c-release).

**Comment by rmcdermo** [comment]
@asbova17 A bug was fixed in bingeom recently.  Possible that qgis2fds is not caught up with this.  Please send me your qgis files.  Thanks

**Comment by emanuelegissi** [comment]
Tomorrow European morning I got some spare time to investigate and possibly
fix the bug. Please, share the qgis file with its data sources, if local.

**Comment by asbova17** [comment]
[Archive.zip](https://github.com/firemodels/fds/files/6964013/Archive.zip)
The zipped file contains the qgz and bingeom file.
Thanks!

**Comment by asbova17** [comment]
Apologies! I should have checked this first. The fuel layer that I used in qgis is older (2014) and does not contain fuel model 13. That's what's causing the problem. The A13 fuel model just has to be removed from the surf ids in the fds input file.
This is unlikely to be a common issue as most people probably won't be using the older landfire fuel data

**Comment by emanuelegissi** [comment]
Ok, anyway I intend to develop a check on boundary conditions to prevent
such error conditions

**Comment by emanuelegissi** [comment]
Added issue: https://github.com/firetools/qgis2fds/issues/32

Il giorno mar 10 ago 2021 alle ore 22:25 Emanuele Gissi <
***@***.***> ha scritto:

> Ok, anyway I intend to develop a check on boundary conditions to prevent
> such error conditions
>
