### ISSUE TITLE
Add experimental values to boundary conditions

### ISSUE THREAD

**Issue by Evil-Doctor** [firemodels/fds#9787]
hello，I want to do a verification of fds. I have given an average temperature temperature boundary condition, but the simulation results are not satisfactory. I want to know whether fds can be given different temperature values under one temperature boundary condition. For example, for the following experimental values, can the temperature boundary conditions be given by interpolation or other methods?

![image](https://user-images.githubusercontent.com/81680065/129319620-d0b0c41e-dcb8-4448-8667-c6e220543133.png)

[room_fire.fds (2).txt](https://github.com/firemodels/fds/files/6980571/room_fire.fds.2.txt)

**Comment by rmcdermo** [comment]
The Issue Tracker is for reporting bugs in the code.  Your queries are better suited for the [discussion forum](https://groups.google.com/g/fds-smv).
