### ISSUE TITLE
Wall flame heat feedback dependence on fuel composition // &REAC FORMULA

### ISSUE THREAD

**Issue by leventon** [firemodels/fds#9818]
We are exploring wall flame heat feedback from a 40 kW propane burner at the base of a corner wall [https://doi.org/10.1002/fam.2524](https://doi.org/10.1002/fam.2524) and have found a sensitivity of FDS predictions of flame length/heat feedback to the fuel composition defined on the REAC line. That is, given a specific heat of combustion, varying the FORMULA definition (e.g., C3H8 vs. C5H8O2) on the REAC line can significantly affect flame heat feedback (profile and peak q” -> unrealistic results).  

This may not strongly affect cases where we can assume the fuel is simply propane with a high heat of combustion but the real focus of this study is to consider flame spread over combustible solids, and so our representative fuel is no longer just ‘Propane’ but the gaseous volatiles released by a pyrolyzing solid with known heat of combustion, Hc = 19 kJ/g (calculated as the avg value of two dozen common charring/non-charring fuels) with ~unknown gaseous fuel composition CxHyOz. In exploring how best to define that fuel composition, I found unrealistic flame shape/heat flux is predicted when using this average (measured) heat of combustion coupled with common fuel compositions (e.g., MMA, propane)

A simplified version of this case is attached. 
[CornerWall_C10H11O3N_Hc19.txt](https://github.com/firemodels/fds/files/7018328/CornerWall_C10H11O3N_Hc19.txt)

--------

In the figure below, wall flame heat flux is plotted as a function of height above a 30 cm tall 40kW burner. FORMULA is defined as either C3H8 (propane, solid symbols) or C5H8O2 (MMA, open symbols); simulations are repeated with each fuel and 4 different heats of combustion. Experimental data is plotted as purple X's. MMA provides reasonable heat flux profiles for just some (higher) values of Hc while propane is unrealistic for any tested here.
 [Burner Heat Flux, MMA and Propane fuel models.pdf](https://github.com/firemodels/fds/files/7018334/Burner.Heat.Flux.various.fuel.models.pdf)

If I treat the fuel as “wood” (FORUMLA= C9H13O6), we get better results (though this lacks strong justification as to why this is the 'correct' species formula)
If I define FORMULA = C10.1H11.4O2.7N0.3 (i.e., the average composition of the base monomer of the surveyed fuels, for which Hc = 19kJ/g), results are slightly _worse_ than what we see for MMA. **I suppose this is key problem**: when using HC=19 kJ/g, our most reasonable first order estimate for the corresponding FORMULA does not provide good results. These results are shown below.
[Burner Heat Flux, MMA and average fuel model.pdf](https://github.com/firemodels/fds/files/7018363/Burner.Heat.Flux.MMA.and.average.fuel.model.pdf)

A back of the envelope calculation suggests this behavior is consistent with a simple energy balance (fuel + air ) --> n(products). Assuming perfect stoichiometry and a fixed heat of combustion, fuels with relatively lower product yields (g products / g fuel) provide higher / more realistic q” 

Defining different RADCAL Species, ‘PROPANE’ or ‘MMA’, has a negligible impact on results 
Reducing grid size from 4 cm to 2 cm only shows minor (~5-10% variations in q” at any given height)

**Comment by drjfloyd** [comment]
Looking at your input file is see a couple of things:

See the section on Enthalpy in 14.1.3 of the User's Guide.  You are using a high molecular weight fuel without defining its specific heat.

The EPUMO2 for C10.1H11.4O2.7N0.3 is 9500 kJ which is somewhat low.

**Comment by leventon** [comment]
Hi Jason. Thanks, I'll look at defining enthalpy as an average value of some representative CH species and see how that affects results. I'll also check each of our individual fuels to see how their Hc_o2 compares to this value, which was just calculated as an average of all measured Hc and respective monomer formulas.

**Comment by drjfloyd** [comment]
You could also try dividing C,H,O,N on REAC by ten to drop the MW below 20. That would give a more reasonable value of ~1 kJ/kg/K for the specific heat.

**Comment by leventon** [comment]
Hmm. That would maintain the CHON ratios but I wouldn't have a physical justification for why that smaller chemical species actually evolves from the sample as a gaseous product of pyrolysis. I think that's my biggest concern - except for simple fuels (liquids, gases, POM, or PMMA..) we don't really know that composition but that species makeup is affecting our results, and even assuming it's just the average base monomer is a significant simplification.

**Comment by drjfloyd** [comment]
I doubt that you see anything as large as a C10 chain in any significant amount as a pyrolyzate especially as a species that survives any significant amount of time in a high temperature gas region.

**Comment by drjfloyd** [comment]
This paper suggest wood goes to mostly low MW gasses: https://www.sciencedirect.com/science/article/pii/S0009250910006809

**Comment by drjfloyd** [comment]
no further activity and no indication of a bug
