### ISSUE TITLE
MPI issue on my MAC

### ISSUE THREAD

**Issue by stanandl22** [firemodels/fds#9822]
Hello! Any help would be amazing as I am very new to this.  I continue to get this error on my mac.  Thank you!

ERROR: The number of MPI processes,      1, exceeds the number of meshes,      0 (CHID: couch)
*** The MPI_Type_f2c() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[(null):881] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by mcgratta** [comment]
Can you post your input file?

**Comment by stanandl22** [comment]
I apologize, as stated this is all very new for me and after hours trying to get this squared away with my professor I decided to do additional research.  When you ask for the input file do you mean the command I put in to receive that message.  Thank you!

**Comment by mcgratta** [comment]
I mean the text file containing the simulation parameters, one of which
defines the MESH.

>

**Comment by stanandl22** [comment]
The case is meant as a teaching tool and to test functionality.

&HEAD CHID='couch', TITLE='Single Couch Test Case'  /

&MESH IJK=24,10,24, XB=1.1,3.5,3.6,4.6,0.0,2.4 /

&TIME T_END=600. /

&REAC SOOT_YIELD=0.01,FUEL='PROPANE'/
&MATL ID                    = 'FABRIC'
      FYI                   = 'Properties completely fabricated'
      SPECIFIC_HEAT         = 1.0
      CONDUCTIVITY          = 0.1
      DENSITY               = 100.0
      N_REACTIONS           = 1
      NU_SPEC               = 1.
      SPEC_ID               = 'PROPANE'
      REFERENCE_TEMPERATURE = 320.
      HEAT_OF_REACTION      = 3000.
      HEAT_OF_COMBUSTION    = 15000. /

&MATL ID                    = 'FOAM'
      FYI                   = 'Properties completely fabricated'
      SPECIFIC_HEAT         = 1.0
      CONDUCTIVITY          = 0.05
      DENSITY               = 40.0
      N_REACTIONS           = 1
      NU_SPEC               = 1.
      SPEC_ID               = 'PROPANE'
      REFERENCE_TEMPERATURE = 320.
      HEAT_OF_REACTION      = 1500.
      HEAT_OF_COMBUSTION    = 30000. /

&MATL ID            = 'GYPSUM PLASTER'
      FYI           = 'Quintiere, Fire Behavior'
      CONDUCTIVITY  = 0.48
      SPECIFIC_HEAT = 0.84
      DENSITY       = 1440. /


&SURF ID             = 'UPHOLSTERY'
      FYI            = 'Properties completely fabricated'
      COLOR          = 'PURPLE'
      BURN_AWAY      = .TRUE.
      MATL_ID(1:2,1) = 'FABRIC','FOAM'
      THICKNESS(1:2) = 0.002,0.1  /

&SURF ID             = 'WALL'
      DEFAULT        = .TRUE.
      RGB            = 200,200,200
      MATL_ID        = 'GYPSUM PLASTER'
      THICKNESS      = 0.012 /

&OBST XB= 1.50, 3.10, 3.80, 4.60, 0.00, 0.40 /
&OBST XB= 1.50, 3.10, 3.80, 4.60, 0.40, 0.60, SURF_ID='UPHOLSTERY', BULK_DENSITY=41.176 /
&OBST XB= 1.30, 1.50, 3.80, 4.60, 0.00, 0.90, SURF_ID='UPHOLSTERY', BULK_DENSITY=41.176 /
&OBST XB= 3.10, 3.30, 3.80, 4.60, 0.00, 0.90, SURF_ID='UPHOLSTERY', BULK_DENSITY=41.176 /
&OBST XB= 1.50, 3.10, 4.40, 4.60, 0.60, 1.20, SURF_ID='UPHOLSTERY', BULK_DENSITY=41.176 /

&PART ID='ignitor particle', SURF_ID='ignitor', STATIC=.TRUE. /
&SURF ID='ignitor', TMP_FRONT=1000., GEOMETRY='CYLINDRICAL', LENGTH=0.15, RADIUS=0.01 /
&INIT XYZ=2.45,4.35,0.65, DX=0.1, PART_ID='ignitor particle', N_PARTICLES=3 /

&VENT MB='XMIN', SURF_ID='OPEN' /  
&VENT MB='XMAX', SURF_ID='OPEN' /  
&VENT MB='YMIN', SURF_ID='OPEN' /  

&BNDF QUANTITY='RADIATIVE HEAT FLUX' /
&BNDF QUANTITY='CONVECTIVE HEAT FLUX' /
&BNDF QUANTITY='NET HEAT FLUX' /
&BNDF QUANTITY='WALL TEMPERATURE' /
&BNDF QUANTITY='BURNING RATE' /

&SLCF PBX=2.50, QUANTITY='TEMPERATURE',VECTOR=.TRUE., CELL_CENTERED=.TRUE. /
&SLCF PBX=2.50, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE. /
&SLCF PBX=2.50, QUANTITY='RADIATION LOSS', CELL_CENTERED=.TRUE. /
&SLCF PBX=2.50, QUANTITY='VISCOSITY', CELL_CENTERED=.TRUE. /
&SLCF PBY=4.40, QUANTITY='TEMPERATURE',VECTOR=.TRUE., CELL_CENTERED=.TRUE. /
&SLCF PBY=4.40, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE. /
&SLCF PBY=4.40, QUANTITY='RADIATION LOSS', CELL_CENTERED=.TRUE. /

&DEVC XYZ=2.55,4.40,0.75, QUANTITY='WALL TEMPERATURE', IOR=-2, ID='temp' /
&DEVC XYZ=2.55,4.40,0.75, QUANTITY='BURNING RATE',     IOR=-2, ID='burn' /
&DEVC XYZ=2.55,4.40,0.75, QUANTITY='RADIATIVE HEAT FLUX',IOR=-2, ID='rad' /
&DEVC XYZ=2.55,4.40,0.75, QUANTITY='GAUGE HEAT FLUX',IOR=-2, ID='gauge' /
&DEVC XYZ=2.55,4.40,0.75, QUANTITY='CONVECTIVE HEAT FLUX',IOR=-2, ID='con' /
&DEVC XYZ=2.55,4.35,0.75, QUANTITY='TEMPERATURE', ID='gas' /
&DEVC XYZ=2.55,4.35,0.75, QUANTITY='HRRPUV', ID='hrrpuv' /
&DEVC XYZ=2.55,4.35,0.75, QUANTITY='RADIATION LOSS', ID='qr' /
&DEVC XYZ=2.55,4.35,0.75, QUANTITY='INTEGRATED INTENSITY', ID='U' /


&TAIL /

**Comment by mcgratta** [comment]
Describe how you tried to run the case.

>

**Comment by stanandl22** [comment]
Below is the command I input for this case I just tried to run and got a new set of errors

Andreas-MacBook-Air:Fires andrea$ fds couch.fds
 Mesh      1 is assigned to MPI Process      0
 OpenMP thread   0 of   3 assigned to MPI process      0 of      0
 OpenMP thread   1 of   3 assigned to MPI process      0 of      0
 OpenMP thread   3 of   3 assigned to MPI process      0 of      0
 OpenMP thread   2 of   3 assigned to MPI process      0 of      0
 Completed Initialization Step  1
forrtl: Permission denied
forrtl: severe (9): permission to access file denied, unit 4, file /Users/andreastanley/FDS/FDS6/Examples/Fires/couch.smv
Image              PC                Routine            Line        Source             
fds                0000000108F6AA44  for__io_return        Unknown  Unknown
fds                0000000108F8A55F  for_open              Unknown  Unknown
fds                00000001089CBCEA  dump_mp_write_smo     Unknown  Unknown
fds                0000000108C0DDB7  MAIN__                Unknown  Unknown
fds                0000000108564F6E  main                  Unknown  Unknown
Andreas-MacBook-Air:Fires andreastanley$

**Comment by mcgratta** [comment]
Do you have permission to write to that directory? If not move the input
file to a directory that you own.

**Comment by mcgratta** [comment]
Any progress?

**Comment by stanandl22** [comment]
I downloaded an emulator and that seemed to help me.  Thank you.
