### ISSUE TITLE
numerical instability error fds6

### ISSUE THREAD

**Issue by elauretti** [firemodels/fds#9825]
Goodmorning everyone,
I modelled a tunnel. For the same section I have to change material according to the king of train passing in the tunnel.
when i try analysing pvc material I have "numerical instability error" that not happens with n-octane.
Can someone help me please?
[prova.txt](https://github.com/firemodels/fds/files/7029743/prova.txt)

**Comment by rmcdermo** [comment]
This should be posted to the [discussion forum](https://groups.google.com/g/fds-smv).

**Comment by mcgratta** [comment]
This line means that you have filled the tunnel with PVC gas, which is assumed to burn when mixed with air. Is this what you really want? If so, FDS is telling you that too much energy is being released too quickly. You have created a bomb.
```
&INIT MASS_FRACTION(1)=0.229,SPEC_ID(1)='PVC' /
```

**Comment by elauretti** [comment]
thank you very much for your help
