### ISSUE TITLE
Output Unit issue

### ISSUE THREAD

**Issue by 94-Gabriel-13** [firemodels/fds#9836]
Hello I always appreciate your help.

I have a question about the units of the result measurement.
We've set the detector for CO, temperature, humidity, and smoke.

Units are output as "mol/mol" for CO and "%/m" for smoke.

How do I print these out by changing **"mol/mol" to "PPM"** and **"%/m" to "kg/m^3"** respectively?

Thank you.

![question image](https://user-images.githubusercontent.com/86586528/130752918-c68db40f-0b85-4f7c-b174-e4860eefcdcd.JPG)
[question file.txt](https://github.com/firemodels/fds/files/7045083/question.file.txt)

**Comment by drjfloyd** [comment]
This is a question for the discussion forum: https://groups.google.com/forum/?fromgroups=&nomobile=true#!forum/fds-smv

Before posting please review the User's Guide.
