### ISSUE TITLE
Hi, Can someone help me with the smoke detector issue?

### ISSUE THREAD

**Issue by 94-Gabriel-13** [firemodels/fds#9847]
According to the FDS user guide, I obtained the data by setting up the smoke detector as follows.

******
_&DEVC ID='SD_Desk', PROP_ID='Smoke Detector', XYZ=16.9,4.9,2.4 /

&PROP ID='Smoke Detector', SMOKEVIEW_ID='smoke_detector', QUANTITY='CHAMBER OBSCURATION', LENGTH=1.8, ACTIVATION_OBSCURATION=3.24 /_
******

I'd like to acquire the data unit by PPM instead of %/m.

Is there any way to acquire PPM units through implementation like the temperature sensor below?

******
_&DEVC ID='TD_Desk', QUANTITY='TEMPERATURE', IOR=1, XYZ=16.9,4.9,2.4 /

&SLCF PBY=11.7, QUANTITY='MASS FRACTION', SPEC_ID='SOOT' /
&SLCF PBY=11.7, QUANTITY='VELOCITY', VECTOR=.TRUE. /
&SLCF PBX=19.5, QUANTITY='TEMPERATURE',VECTOR=.TRUE., CELL_CENTERED=.TRUE. /
&SLCF PBX=19.5, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE. /
&SLCF PBX=19.5, QUANTITY='RADIATION LOSS', CELL_CENTERED=.TRUE. /
&SLCF PBX=19.5, QUANTITY='VISCOSITY', CELL_CENTERED=.TRUE. /
&SLCF PBY=11.7, QUANTITY='TEMPERATURE',VECTOR=.TRUE., CELL_CENTERED=.TRUE. /
&SLCF PBY=11.7, QUANTITY='HRRPUV', CELL_CENTERED=.TRUE. /
&SLCF PBY=11.7, QUANTITY='RADIATION LOSS', CELL_CENTERED=.TRUE. /_
******

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs. For questions on using FDS use the discussion forum: 
https://groups.google.com/g/fds-smv
