### ISSUE TITLE
Fuel FORMULA for SIMPLE_CHEMISTRY 

### ISSUE THREAD

**Issue by lu-kas** [firemodels/fds#9862]
Dear all,

we have currently issues with the values used to specify a fuel mixture. The error arises randomly in our automated pipeline, yet we have found some individual examples to illustrate the behaviour.

The error happens in this definition

```
&SPEC ID='FuelMixture',
      SPEC_ID(1)='METHANE', VOLUME_FRACTION(1)=        7.989056,
      SPEC_ID(2)='ETHYLENE', VOLUME_FRACTION(2)=       0.5266463,
      SPEC_ID(3)='NITROGEN', VOLUME_FRACTION(3)=      16.64556,
      SPEC_ID(4)='CARBON DIOXIDE',VOLUME_FRACTION(4)=  8.656009 / 
```

With the most recent version of FDS 

```
> fds

 Fire Dynamics Simulator

 Current Date     : August 30, 2021  17:00:12
 Revision         : FDS6.7.6-0-g5064c500c-release
 Revision Date    : Thu May 27 12:19:10 2021 -0400
 Compiler         : Intel ifort 2021.1
 Compilation Date : Jun 01, 2021  13:04:27

 MPI Enabled;    Number of MPI Processes:       1
 OpenMP Enabled; Number of OpenMP Threads:      4

 MPI version: 3.1
 MPI library version: Open MPI v4.1.0, package: Open MPI gforney@bevo.el.nist.gov Distribution, ident: 4.1.0, repo rev: v4.1.0, Dec 18, 2020
 Consult FDS Users Guide Chapter, Running FDS, for further instructions.
```

the following error can be reproduced on Linux/Windows/MacOS

```
> fds model_input.file.txt  

 Starting FDS ...

 MPI Process      0 started on [...]

 Reading FDS input file ...

ERROR: Fuel FORMULA for SIMPLE_CHEMISTRY can only contain C,H,O, and N (CHID: SimpleMCC)

ERROR: FDS was improperly set-up - FDS stopped (CHID: SimpleMCC)
```

However, when one removes the last digit (this is not the sole way to 'resolve the error') from the CO line, i.e.:

```
&SPEC ID='FuelMixture',
      SPEC_ID(1)='METHANE', VOLUME_FRACTION(1)=        7.989056,
      SPEC_ID(2)='ETHYLENE', VOLUME_FRACTION(2)=       0.5266463,
      SPEC_ID(3)='NITROGEN', VOLUME_FRACTION(3)=      16.64556,
      SPEC_ID(4)='CARBON DIOXIDE',VOLUME_FRACTION(4)=  8.65600 / <-- last digit removed 
```

then FDS does not throw the above error.

An input file, containing both definitions (starting line 31 and 38) is attached: [model_input.file.txt](https://github.com/firemodels/fds/files/7077625/model_input.file.txt) .

So, does anyone know how to understand and solve this error? Thanks for your support!

With regards,
Lukas

**Comment by mcgratta** [comment]
We'll take a look.

**Comment by TristanHehnen** [comment]
We also tried to change the notation of the numbers from float to exponential; both produce the same error for the same number. 
It is also not soley related to the CO line. Also instead of removing the last digit of any given number, one could also append or just change a digit. However, we also found cases where changing the last digit of a single number, the error appeared only with certain numbers.

In the attached screen shot there are numbers written in the box (0,1,2,7,9), if any of these are added at the location of the cursor (arrow) the simple chemistry error is raised, for the remaining numbers between 0 and 9 the simulation starts as usual.

![grafik](https://user-images.githubusercontent.com/34650649/131364468-592a9efe-53c4-43e3-a94b-eb91fb6f7eee.png)

And as a further note: we have now tried to have a different amount of digits, between 3 and 6, written in to the FDS input file for the different numbers. Within the first about 2k simulations this error didn't show itself.

**Comment by drjfloyd** [comment]
With the current source this works in debug mode but not release mode.

We check the species formula by adding the number of H,C,N, and O atoms and comparing that to the sum over all atoms. We do this in a manner that accounts for the precision at which the numbers are being represented.  We may have an improperly typed or initialized variable somewhere or this could just be an issue with compiler optimization. I'll try to figure it out.

**Comment by drjfloyd** [comment]
It looks like it has to do with optimization. The values of H,C,N, and O in the final formula are identical between debug and release but the atom count sums being checked are just slightly different at the limit of precision for the REAL(EB) type.  I'll change to a different approach for doing the check that should fix this for future releases. 

I don't have a work around to give you for the current release other than what you have found (reducing the number of digits or just fixing the few cases that randomly fail).

**Comment by mcgratta** [comment]
Can't we just loosen the tolerance used in checking the math?

**Comment by drjfloyd** [comment]
Done. The new method is just as simple and just avoids the precision issue altogether.

IF (ABS(SM%ATOMS(1)+SM%ATOMS(6)+SM%ATOMS(7)+SM%ATOMS(8) - SUM(SM%ATOMS)) > SPACING(SUM(SM%ATOMS))) THEN

to

IF (ANY(SM%ATOMS(2:5)>0._EB) .OR. ANY(SM%ATOMS(9:)>0._EB)) THEN

**Comment by lu-kas** [comment]
Great and thanks! I will give it a try with the latest code version.

**Comment by lu-kas** [comment]
I just want to give a first feedback: I works so far. We wait until a full turnover of our cases is finished and will then close the issue. Thanks for your support.

**Comment by TristanHehnen** [comment]
So, we did run a good 300k simulations with automatically generated parameter sets in which this issue did NOT appear again. I'd assume it could be considered "solved" and closed.

**Comment by drjfloyd** [comment]
Thanks for the update. Closing the issue.

**Comment by TristanHehnen** [comment]
Thank you very much!
