### ISSUE TITLE
MPI fatal error

### ISSUE THREAD

**Issue by andrea-paradiso** [firemodels/fds#9871]
Test case file is attached.

By running the following command 
_mpiexec -n 31 fds test.fds_ 
the following error message is displayed:

_Abort(472981263) on node 6 (rank 6 in comm 0): Fatal error in PMPI_Bcast: Other MPI error, error stack:
PMPI_Bcast(431).........................: MPI_Bcast(buf=0x14a1ff541400, count=321671, MPI_INTEGER, root=2, comm=comm=0x84000006) failed
PMPI_Bcast(417).........................: 
MPIDI_Bcast_intra_composition_gamma(397): 
MPIDI_NM_mpi_bcast(149).................: 
MPIR_Bcast_intra_auto(222)..............: 
MPIR_Bcast_intra_binomial(122)..........: message sizes do not match across processes in the collective routine: Received 183812 but expected 1286684
Abort(540090126) on node 27 (rank 27 in comm 0): Fatal error in PMPI_Bcast: Message truncated, error stack:
PMPI_Bcast(431).........................: MPI_Bcast(buf=0x14c4cf0b1d40, count=45953, MPI_INTEGER, root=2, comm=comm=0x84000002) failed
PMPI_Bcast(417).........................: 
MPIDI_Bcast_intra_composition_gamma(397): 
MPIDI_NM_mpi_bcast(149).................: 
MPIR_Bcast_intra_auto(222)..............: 
MPIR_Bcast_intra_binomial(111)..........: 
(unknown)(): Message truncated
Abort(472981263) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Bcast: Other MPI error, error stack:
PMPI_Bcast(431).........................: MPI_Bcast(buf=0x14b3a6dfe740, count=321671, MPI_INTEGER, root=2, comm=comm=0xc4000001) failed
PMPI_Bcast(417).........................: 
MPIDI_Bcast_intra_composition_gamma(397): 
MPIDI_NM_mpi_bcast(149).................: 
MPIR_Bcast_intra_auto(222)..............: 
MPIR_Bcast_intra_binomial(122)..........: message sizes do not match across processes in the collective routine: Received 183812 but expected 1286684_

The test case runs ok with just one processor.
The problem seems to be related to the mesh split of the test case (MPI works fine with other fds input files).

FDS 6.7.6-0
MPI version: 3.1
Intel(R) MPI Library, Version 2021.1 for Linux* OS

[test.fds.txt](https://github.com/firemodels/fds/files/7088624/test.fds.txt)

**Comment by mcgratta** [comment]
There were two problems, one mine and one yours. First, these meshes were identical:
```
&MESH ID='Mesh23b', IJK=64,29,23, XB=312.6,325.4,16.6,22.4,0.0,4.6, MPI_PROCESS=23/
&MESH ID='Mesh24b', IJK=64,29,23, XB=312.6,325.4,-0.2,5.6,0.0,4.6, MPI_PROCESS=24/

&MESH ID='Mesh29', IJK=64,29,23, XB=312.6,325.4,-0.2,5.6,0.0,4.6, MPI_PROCESS=29/
&MESH ID='Mesh30', IJK=64,29,23, XB=312.6,325.4,16.6,22.4,0.0,4.6, MPI_PROCESS=30/
```
Second, there is a small gap separating the row of 7 meshes. That gap is exactly 5 cell widths, which is, by coincidence, the distance we designate as separating two meshes from sending and receiving messages. But because of machine precision, one mesh "saw" the other, but not vice verse. Long story short, I fixed that bug. So if you want the case to run, eliminate the redundant mesh, and define the gap distance to be something like what it is currently plus some small amount like 0.0001.

**Comment by sbenkorichi** [comment]
Kevin,

I think I might get into the same issue as this one. I had on mine FDS6.7.5 and was stuck for a while at initiation and then sends a runout time. Tried now FDS6.7.6 bundle (unfortunately, I can't compile on my machine to test your latest fix). 

I reduced the problem to the below, I couldn't go down more. The error, shown below, appears after including the mesh on the MPI_PROCESS 4.
```
&MESH ID='Mesh-00', IJK=39,79,26, XB=-3.1,0.8,1.4,9.3,23.4,26.0, MPI_PROCESS=0/
&MESH ID='Mesh-01d', IJK=21,12,26, XB=-27.4,-25.3,-2.4,-1.2,23.4,26.0, MPI_PROCESS=1/
&MESH ID='Mesh-02b', IJK=23,18,55, XB=-0.2,4.4,-3.8,-0.2,35.8,46.8, MPI_PROCESS=2/
&MESH ID='Mesh-03', IJK=182,16,26, XB=-11.9,6.3,-0.2,1.4,23.4,26.0, MPI_PROCESS=3/
&MESH ID='Mesh-04', IJK=12,13,466, XB=6.5,7.7,-2.0,-0.7,0.0,46.6, MPI_PROCESS=4/
```
The error message when I run the above I receive 
 Reading FDS input file ...

```
 Reading FDS input file ...

Abort(540090126) on node 4 (rank 4 in comm 0): Fatal error in PMPI_Bcast: Message truncated, error stack:
PMPI_Bcast(431).........................: MPI_Bcast(buf=0x2ae9c522b540, count=32257, MPI_INTEGER, root=1, comm=comm=0x84000002) failed
PMPI_Bcast(417).........................:
MPIDI_Bcast_intra_composition_gamma(397):
MPIDI_NM_mpi_bcast(149).................:
MPIR_Bcast_intra_auto(222)..............:
MPIR_Bcast_intra_binomial(111)..........:
(unknown)(): Message truncated

```
The mesh itself is separate from other meshes, it might have to do with the ratio of the mesh maybe. What I've done is I kept reducing the size of the K number of the mesh down to 228, it runs, anything above this like 229 (i.e. 0,22.9) fails. 
```
&MESH ID='Mesh-00', IJK=39,79,26, XB=-3.1,0.8,1.4,9.3,23.4,26.0, MPI_PROCESS=0/
&MESH ID='Mesh-01d', IJK=21,12,26, XB=-27.4,-25.3,-2.4,-1.2,23.4,26.0, MPI_PROCESS=1/
&MESH ID='Mesh-02b', IJK=23,18,55, XB=-0.2,4.4,-3.8,-0.2,35.8,46.8, MPI_PROCESS=2/
&MESH ID='Mesh-03', IJK=182,16,26, XB=-11.9,6.3,-0.2,1.4,23.4,26.0, MPI_PROCESS=3/
&MESH ID='Mesh-04', IJK=12,13,228, XB=6.5,7.7,-2.0,-0.7,0.0,22.8, MPI_PROCESS=4/
```

Could you please have a look into this?

Thanks

**Comment by mcgratta** [comment]
Salah, your original 5 mesh case runs for me on our linux computer with the latest source  code.

**Comment by sbenkorichi** [comment]
Ok, thanks Kevin for confirming. 
I'll try this week to compile the latest source with at least GNU and test it.

**Comment by sbenkorichi** [comment]
Kevin, I've compiled with intel oneAPI and tested it. It runs now. So, issue will be fixed in the coming updated bundle.
Thanks

**Comment by mcgratta** [comment]
Great, thanks for checking this.
