### ISSUE TITLE
Level_set simulation unexpectedly long runtime...

### ISSUE THREAD

**Issue by brunoguillaume** [firemodels/fds#9881]
I tried to run a forest fire with the level set model on a complex terrain, where I am constrained to use mode=4 and also to run at 25cm resolution, and I am quite surprised of the much longer time it takes in comparison to modeling instead with particle model. The zone is 100mx100m large.
Here attached is the parameter file.
When changing in the file the &SURF to non-reactive (MATL="DIRT") into &SURF with VEG_LSET_ params makes it increase dramatically the runtime, in an unreasonable duration. I run it on 8meshesx4threads and I am not sure that increasing by an additional factor of 2 would strongly reduce the runtime.

Any idea? (maybe I have some parameter wrongly defined)

BG
[levelset_sample.zip](https://github.com/firemodels/fds/files/7107348/levelset_sample.zip)

**Comment by mcgratta** [comment]
Randy -- can you assign Eric to this issue. I can't seem to find him in the list. Does he need to be added to the project?

**Comment by ericvmueller** [comment]
Bruno, 
So I can test this, are you wanting to enable level set parameters on all of the following `SURF` lines:
'route', 'GR0', 'GR1', and 'pelouse'?

And can you let me know the simulation duration and runtime you get with a particle model vs. that of the level set?

**Comment by brunoguillaume** [comment]
Thanks Eric for your help!
Indeed, the simulation file is currently setup for non-reactive surfaces. To switch to level set mode, indeed you need to chnage surface properties of the 4 surfaces that you mention : for a sake of clarity, I restructured a bit the file so that you just need to uncomment the corresponding bloc, and to comment the blocs of other modes.  I added a 3rd bloc to switch to 2D particle mode.

[levelset_sample_v2.zip](https://github.com/firemodels/fds/files/7113561/levelset_sample_v2.zip)

**Comment by ericvmueller** [comment]
Thanks for providing this updated input file!

So I ran a comparison between the three modes on our linux cluster (assigning 1 process per mesh). However, I made two modifications, just to speed up the comparison. First I dropped the wind speed to 1 m/s (with 11 m/s, and your 0.25m grid resolution, the time steps are very small to satisfy the stability condition, so it just takes a very long time to run). Second, I left the radiation solver with the default number of angles.

I get the following, for the 10s of simulation time you specified:
- Inert mode: 1580 s of cpu stepping time
- Levelset 4 mode: 3418 s ...
- Particle mode: 2640 s ...
So I also get a shorter run time with the particles compared with the levelset. 

However, I'm not convinced there is an error here. 
If you compare the energy release in the `*_hrr.csv` file, you will see the levelset approach is much higher (by around an order of magnitude). This greater energy release should mean higher velocities and thus smaller time steps to ensure stability. Looking at the `*.out` and `*_cpu.csv` files, you will notice that the levelset simulation requires more steps, not necessarily more CPU time per step.

We can't necessarily expect the two methods to agree, given the different approaches for calculating spread (and thus HRR). That being said, you should also check out the details in the user guide on setting up the levelset method. You have specified a `HRRPUA` and a `BURN_DURATION`, but this won't work for defining burning behavior for levelset surfaces, so you are basically getting the default behavior.

**Comment by brunoguillaume** [comment]
Eric, thanks a lot for running this comparison, and thanks for your clear interpretation of the infos in hrr.csv, .out and cpu.csv.
I get clear now that the levelset method is much more appropriate to track a fire in the wild at 1-4m resolution than at WUI scale where 0.25m is still correct to match comparison with results at 0.10m or 0.05m resolution on 3D trees fire propagation, but I where coarser resolutions degrade strongly the emitted and received heat fluxes (especially towards building targets).

**Comment by mcgratta** [comment]
There is a validation case called CSIRO_Grassland_Fires that demonstrates
three methods of predicting/prescribing wildland flame spread.

>

**Comment by ericvmueller** [comment]
Bruno, 
As Kevin mentioned, the level set method has been tested somewhat for predicting spread, and you can check out the validation case. However, predicting heat fluxes with level set mode 4, and the effect of coarse resolution, is not something that we have looked at yet (to the best of my knowledge). 
Unless there is a specific problem with the code we can pinpoint as causing unusually long runtimes here, I will close this issue.

**Comment by ruddymell** [comment]
As a bit of a wrap-up, we are currently in the process of testing and developing the level set method in FDS. In WFDS, the level set method is more mature and has produced fire behavior (spread rate, fire depth, heat release rate) that is similar to the "full-physics" (PB) based approach for grassland fire simulations. But this required a formula for the head fire spread rate as a function of the local wind based on PB simulations. One of the key questions is the importance of the fire generated wind to the local fire behavior as modeled in the level set approach. We are  working through different ways of handling this and determining their pros and cons for a given scenario. We have also applied the level set approach to scenarios with over story consumption and obtain qualitative agreement with PB simulations.
