### ISSUE TITLE
Heat Conduction Through Two Different Obstructions with different properties

### ISSUE THREAD

**Issue by NTamoafo** [firemodels/fds#9885]
Hello,

I am trying to simulate heat conduction through two different solid materials with fire being applied on one surface and calculating temperature change at the other end of the second surface. I have them simulated as two different obstructions with different properties and thickness. I use the exposed boundary condition for both however I am not getting the desired temperature as I record temperature. Is FDS able to simulate this accurately and if yes how do I do this?

**Comment by rmcdermo** [comment]
Yes, FDS can do this.  This question is better suited for the discussion forum.  Please read the user guide before posting.
