### ISSUE TITLE
fds_local as a command

### ISSUE THREAD

**Issue by rporowski** [firemodels/fds#9890]
Hey there,
after installing FDS newest version, I run "cmdfds" on the deskop and according to FDS User Manual I typed "fds_local job_name.fds"
Unfortunately, it gave me the following answer: "fds_local is not recognized as an internal or external command, operable program or batch file".
Does anybody could help me to fix that?
--
Best regards,
Rafal.

**Comment by gforney** [comment]
Reboot your computer and try again

**Comment by rporowski** [comment]
OK, thanks! Now it works!

**Comment by gforney** [comment]
Good .  thanks for reporting back.
