### ISSUE TITLE
ERROR statements for CTRL FUNCTIONs

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9891]
This input line
```
&CTRL ID='Act1', INPUT_ID='SPRK_001', FUNCTION_TYPE='ANY' /
```
now throws the ERROR
```
ERROR: CTRL Act1 must have at least two inputs (CHID: BITTERN_10)
```
Is there a problem if there is just input? If there is, what would be the appropriate FUNCTION_TYPE?

**Comment by drjfloyd** [comment]
It isn't incorrect.  In my mind while I was updating that was the use case for ANY was with multiple inputs, but now that you have raised the question there is a use case where it would make sense to have a CTRL for a single DEVC. For example you may need the DEVC to be TRUE for something to happen once the device activates but might have some other action where you would want the DEVC to return a FALSE and ANY could be used to flip that logical state.

**Comment by mcgratta** [comment]
Not sure what you mean. If there is one item in a set, and one specifies ANY, ONLY, AT_LEAST, or ALL, wouldn't this item still be chosen? Grammatically it's a bit awkward, but mathematically isn't it still true?

**Comment by drjfloyd** [comment]
No it is true. If you are just using a TRUE DEVC to make a TRUE CTRL, this is valid but unneeded complexity. I am fixing this so it requires at least on input.

**Comment by drjfloyd** [comment]
Should be fixed now.

**Comment by mcgratta** [comment]
Seems to be working, thanks.
