### ISSUE TITLE
changing bead diameter of thermocouple via PROP ID 

### ISSUE THREAD

**Issue by pimzzff1** [firemodels/fds#9904]
Hi,

I'm setting up a model in which thermocouples are used.  In the experiments which serve as a basis, bead sizes other than the default 1mm are used. When using the PROP ID line to change the BEAD_DIAMETER, FDS returns an error: 

ERROR: Problem with PROP number 1, line number 48 (CHID: v0_14_ventilation_controlled_yields_2)

I tried to simplify the case in a single mesh with just a single thermocouple, the same error is returned (see attached). The FDS-file is located in the appendix to this e-mail. 
[untitled.txt](https://github.com/firemodels/fds/files/7149506/untitled.txt)

Am I overlooking something? 

Thanks in advance for responding.

**Comment by ericvmueller** [comment]
It should be 'DIAMETER' instead of 'BEAD_DIAMETER'. Check out the [verification case for the effect of thermocouple size](https://github.com/firemodels/fds/blob/master/Verification/Radiation/thermocouples.fds).

**Comment by pimzzff1** [comment]
Thanks, that did the trick. Pyrosim outputs it as BEAD_DIAMETER in the .fds file and an older FDS User Guide uses that line as well. Should've been more attentive. Thank you!

**Comment by mcgratta** [comment]
I changed that input parameter so that we could use the more general DIAMETER for different devices. In any event, whenever you get this generic input error, just go to the tables in the back of the User's Guide.
