### ISSUE TITLE
Aerosol: Mean Diameter Particle Default Value

### ISSUE THREAD

**Issue by firemist** [firemodels/fds#9921]
### Problem Description
Table 22.29 in the FDS User Manual states there is a default for Mean Diameter (image attached) on the &SPEC card:
<excerpt_beg>
_Table 22.29: Continued
SPEC (Species Parameters)
MEAN_DIAMETER | Real | Section 15.4 | m | 1.E-6_
<excerpt_end>

However, in attempting to run a case without MEAN_DIAMETER specified, FDS throws a fatal error:
<clip_beg>
  Reading FDS input file ...

ERROR: SPEC 5: No MEAN_DIAMETER given. (CHID: no_mean_diameter)

ERROR: FDS was improperly set-up - FDS stopped (CHID: no_mean_diameter)
[runfds.exe] subprocess exit: 0__
<clip_end>

### User Recommendation
I recommend that the default be implemented as written but if that is not the decided direction of FDS_DEV then the manual should be updated to reflect this.

Thank you for your work. Best wishes, Christopher

### NOTE: .txt extension added to .fds files to allow upload

[no_mean_diameter.fds.txt](https://github.com/firemodels/fds/files/7211178/no_mean_diameter.fds.txt)

[mean_diameter.fds.txt](https://github.com/firemodels/fds/files/7211182/mean_diameter.fds.txt)

### Manual Data
![no_mean_diameter_manual_data](https://user-images.githubusercontent.com/25644607/134355002-239d8419-ce57-4e4a-bc8a-a0a5427c9ff8.JPG)

### Table Clip
![no_mean_diameter_spec_table](https://user-images.githubusercontent.com/25644607/134355035-3efc5beb-5fc8-49c3-9ebb-c313e125d6af.JPG)

**Comment by drjfloyd** [comment]
Thank you for catching this. I'll fix the guide. Having a default diameter became an issue as more aerosol features were added such as agglomeration and condensation.
