### ISSUE TITLE
Scale HRRPUV by exact volume specified by XB on INIT

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/fds#9927]
Right now, the volume for giving Q = HRRPUV * VOLUME takes the volume from snapping the XB to the Cartesian grid.  I think there should be a rescaling of HRRPUV inside read to give the exact Q = HRRPUV (specified) * XB_VOLUME (specified).

**Comment by mcgratta** [comment]
Could you test this. You need not do anything in your input file. If the INIT volume does not exactly conform to the FDS grid, HRRPUV should be adjusted automatically.

**Comment by rmcdermo** [comment]
Will do, thanks

**Comment by rmcdermo** [comment]
Something seems backwards.  Try this little test case:
```
&HEAD CHID='test', TITLE='Verification of HRRPUV recaling on INIT' /

&MESH IJK=10,10,10, XB=0,10,0,10,0,10 /
&MESH IJK=10,10,10, XB=11,21,0,10,0,10 /

&TIME T_END=10/

&INIT XB=3,7,3,7,3,7, HRRPUV=100/
&INIT XB=13.5,18.5,2.5,7.5,2.5,7.5, HRRPUV=100/

&SLCF PBY=5, QUANTITY='HRRPUV', CELL_CENTERED=T/
```

I get this.  But the one on the right is snapping to a larger volume and hence should have a smaller HRRPUV.

<img width="752" alt="Screen Shot 2021-09-28 at 12 00 07 PM" src="https://user-images.githubusercontent.com/4418497/135123513-405b4395-bf89-4018-a108-aa43d3af91fe.png">

**Comment by mcgratta** [comment]
This might be the dreaded less than or equal to problem. I'll fix.

>

**Comment by rmcdermo** [comment]
This case seems to work correctly:
```
&HEAD CHID='test', TITLE='Verification of HRRPUV recaling on INIT' /

&MESH IJK=10,10,10, XB=0,10,0,10,0,10 /
&MESH IJK=9,9,9, XB=11,21,0,10,0,10 /

&TIME T_END=10/

&INIT XB=3,7,3,7,3,7, HRRPUV=100/
&INIT XB=14,18,3,7,3,7, HRRPUV=100/

&SLCF PBY=5, QUANTITY='HRRPUV', CELL_CENTERED=T/

&DEVC XB=0,10,0,10,0,10, QUANTITY='HRRPUV', SPATIAL_STATISTIC='VOLUME INTEGRAL', ID='Q1'/
&DEVC XB=11,21,0,10,0,10, QUANTITY='HRRPUV', SPATIAL_STATISTIC='VOLUME INTEGRAL', ID='Q2'/
```
<img width="752" alt="Screen Shot 2021-09-28 at 12 16 50 PM" src="https://user-images.githubusercontent.com/4418497/135126108-9ca47409-d1ce-4cd1-bf83-79e1cd1414ae.png">

**Comment by mcgratta** [comment]
![image](https://user-images.githubusercontent.com/11333911/135126637-323ddc24-49bd-456e-95e5-edfbb2073051.png)

**Comment by mcgratta** [comment]
I was not using the exact same conditional in creating VOLUME_ADJUST as I was using when applying it.

**Comment by rmcdermo** [comment]
Looks good.  Thanks
