### ISSUE TITLE
Movement of personnel on stairs (EVSS) in EVAC

### ISSUE THREAD

**Issue by StarAlex-Wang** [firemodels/fds#9928]
Hi friends,
       I got a question as the photo shows, that the personnel  do not move normally on the stairs, but disappear at the door(DOOR) on the first floor and appear at the entrance (ENTR) on the second floor. I can't find out what caused this situation, if anyone can help me to solve it, I would be very grateful. Attach is the code of FDS.

![image](https://user-images.githubusercontent.com/83077843/134694077-a6e868e2-1e1b-4eb5-9e16-fbe77d9d0483.png)
 &HEAD CHID='case1', TITLE='Simple example of wide stairs'/
&TIME T_END=120.0, DT=0.05 /
&DUMP RENDER_FILE='case1.ge1', DT_BNDF=1.0E6, DT_HRR=1.0, DT_ISOF=1.0E6, DT_PART=0.5, DT_PL3D=1.0E6, DT_SLCF=1.0E6, NFRAMES=200, SMOKE3D=.FALSE./
&MISC EVACUATION_DRILL=.TRUE., EVAC_TIME_ITERATIONS=50, EVAC_PRESSURE_ITERATIONS=50 /
&RADI RADIATION=.FALSE./
&PERS ID='globals', TDET_SMOKE_DENS=0.1, OUTPUT_SPEED=.TRUE., COLOR_METHOD=0/

&MESH ID='FireMesh', IJK=125,85,137, XB=-34.0,116.0,-42.0,60.0,24.0,188.4/
&MESH ID='workdeck', IJK=130,110,1, XB=2.5,67.5,-15.0,40.0,19.4,19.6, EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0/

&MESH ID='workdeck-', IJK=130,110,1, XB=2.5,67.5,-15.0,40.0,29.4,29.6, EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0/

&OBST XB=7.5,12.6,-11,-10.5,18.0,28.0, EVACUATION=.TRUE., SURF_ID='INERT'/ Obstruction #1
&OBST XB=7.5,12.6,-13,-12.5,18.0,28.0, EVACUATION=.TRUE., SURF_ID='INERT'/ Obstruction #2
&OBST XB=7.5,12.6,-15,-14.5,18.0,28.0, EVACUATION=.TRUE., SURF_ID='INERT'/ Obstruction #3
&OBST XB=12.6,12.8,-15,-13,18.0,28.0, EVACUATION=.TRUE., SURF_ID='INERT'/ Obstruction #3
&OBST XB=7.3,7.5,-13,-11,18.0,28.0, EVACUATION=.TRUE., SURF_ID='INERT'/ Obstruction #3

&DOOR ID='workdeck-1-1', FYI='Comment line', XB=7.5,7.5,-14.5,-13,19.4,19.6, XYZ=7.0,-13.75,19.5, MESH_ID=workdeck, IOR=1, TO_NODE='workdeck-1-11', EXIT_SIGN=.TRUE., KEEP_XY=.TRUE., COLOR='PINK'/
&ENTR ID='workdeck-1-11', FYI='Comment line', XB=7.5,7.5,-12.5,-11,29.4,29.6, MESH_ID=workdeck-, IOR=1/
&EVSS ID='IntLanding', XB=12.6,14.1,-14.5,-11,19.4,19.6, IOR=1, HEIGHT=4.1, HEIGHT0=4.1/
&EVSS ID='workdeck-landing1', XB=7.5,12.6,-14.5,-13.0,19.4,19.6, IOR=1, MESH_ID='workdeck', HEIGHT0=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/
&EVSS ID='landing-workdeck1', XB=7.5,12.6,-12.5,-11.0,19.4,19.6, IOR=-1, MESH_ID='workdeck', HEIGHT0=10, HEIGHT=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/

&PERS ID='Adult', FYI='Male+Female diameter and velocity', DEFAULT_PROPERTIES='Adult', DET_EVAC_DIST=1, DET_LOW=1.0, DET_HIGH=3.0, PRE_EVAC_DIST=1, PRE_LOW=2.0, PRE_HIGH=4.0/

&EXIT ID='Exit-1', FYI='Comment line', XB=2.5,2.5,-12.0,-11.0,29.4,29.6, MESH_ID=workdeck-, COLOR='YELLOW', XYZ=3,-11.5,29.5, IOR=-1/

&EVAC ID='Agents-1', XB=10.0,30.0,10.0,20.0,19.4,19.6, NUMBER_INITIAL_PERSONS=10, PERS_ID='Adult', AVATAR_COLOR='BLUE', KNOWN_DOOR_NAMES='Exit-1', KNOWN_DOOR_PROBS=1.0,0.0/

&TAIL /

**Comment by gjaeger** [comment]
Try this:

Your modelling of the stairs is faulty. The mesh does not have to be so fine. In this modification, I am only concerned with modelling the staircase.

```
&HEAD CHID='case1', TITLE='Simple example of wide stairs'/
&TIME T_END=120.0 /

&DUMP DT_HRR=1.0, SMOKE3D=.FALSE./

&MISC
  EVACUATION_INITIALIZATION=T,
  EVACUATION_MC_MODE= F,
  EVACUATION_DRILL= F /

&PERS ID='globals', TDET_SMOKE_DENS=0.1, OUTPUT_SPEED=.TRUE., COLOR_METHOD=0/

&MESH ID='workdeck',  IJK=650,550,1, XB=2.5,67.5,-15.0,40.0,19.4,19.6, EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0/
&MESH ID='workdeck-', IJK=650,550,1, XB=2.5,67.5,-15.0,40.0,29.4,29.6, EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0/

&OBST XB= 7.3, 7.5,-13.0,-10.5,18.0,20.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,14.1,-15.0,-14.5,18.0,30.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,14.1,-11.0,-10.5,18.0,30.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB=14.1,14.2,-15.0,-10.5,18.0,30.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.5,12.6,-13.0,-12.5,18.0,30.0, EVACUATION=.TRUE., SURF_ID='INERT'/

&DOOR ID='workdeck-1-1',
  FYI='Comment line',
  XB=7.5,7.5,-12.5,-11,19.4,19.6,
  XYZ=7.6,-12.05,19.5,
  MESH_ID=workdeck, IOR=-1,
  TO_NODE='workdeck-1-11',
  EXIT_SIGN=.TRUE.,
  KEEP_XY=.TRUE.,
  COLOR='PINK'/

&ENTR ID='workdeck-1-11',
  FYI='Comment line',
  XB=7.3,7.3,-12.5,-11,29.4,29.6,
  MESH_ID=workdeck-, IOR=-1/


&EVSS ID='IntLanding',
      XB=12.6,14.1,-14.5,-11.0, 19.4,19.6,
      IOR=1,
      HEIGHT=4.1,
      HEIGHT0=4.1/
&EVSS ID='workdeck-landing1',
      XB= 7.5,12.6,-14.5,-13.0,19.4,19.6,
      IOR=1,
      HEIGHT0=4.1,
      FAC_V0_UP=0.4,
      FAC_V0_DOWN=0.7/
&EVSS ID='landing-workdeck1',
      XB= 7.5,12.6,-11.0,-12.5,19.4,19.6,
      IOR=-1,
      HEIGHT0=10,
      HEIGHT=4.1,
      FAC_V0_UP=0.4,
      FAC_V0_DOWN=0.7/

&PERS ID='Adult', FYI='Male+Female diameter and velocity', DEFAULT_PROPERTIES='Adult', DET_EVAC_DIST=1, DET_LOW=1.0, DET_HIGH=3.0, PRE_EVAC_DIST=1, PRE_LOW=2.0, PRE_HIGH=4.0/

&EXIT ID='Exit-1', FYI='Comment line', XB=2.5,2.5,-12.0,-11.0,29.4,29.6, MESH_ID=workdeck-, COLOR='YELLOW', XYZ=3,-11.5,29.5, IOR=-1/

&EVAC ID='Agents-1', XB=10.0,30.0,10.0,20.0,19.4,19.6, NUMBER_INITIAL_PERSONS=10, PERS_ID='Adult', AVATAR_COLOR='BLUE', KNOWN_DOOR_NAMES='Exit-1', KNOWN_DOOR_PROBS=1.0,0.0/

&TAIL /
```

I think, you can close this issue. It is an user problem.
