### ISSUE TITLE
Problem with selecting stairs in EVAC

### ISSUE THREAD

**Issue by StarAlex-Wang** [firemodels/fds#9931]
Hi all,
I got a question here. The personnel in my model only select one stair (four in all) as the figure shows. I can not figure out why. I will be much grateful if anyone who can help me. Best wishes!
![123](https://user-images.githubusercontent.com/83077843/134775583-a51d3dae-424e-484c-8ffb-42c0191663e5.jpg)
Here are the FDS codes.
&HEAD CHID='case1', TITLE='Simple example of wide stairs'/
&TIME T_END=500.0 /

&DUMP DT_HRR=1.0, SMOKE3D=.FALSE./

&MISC EVACUATION_DRILL=.TRUE., EVAC_TIME_ITERATIONS=10, EVAC_PRESSURE_ITERATIONS=10 /

&PERS ID='globals', TDET_SMOKE_DENS=0.1, OUTPUT_SPEED=.TRUE., COLOR_METHOD=0/

&MESH ID='FireMesh', IJK=125,85,137, XB=-34.0,116.0,-42.0,60.0,24.0,188.4/
&MESH ID='workdeck',  IJK=650,550,1, XB=2.5,67.5,-15.0,40.0,19.4,19.6, EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0/
&MESH ID='workdeck-', IJK=650,550,1, XB=2.5,67.5,-15.0,40.0,29.4,29.6, EVACUATION=.TRUE., EVAC_HUMANS=.TRUE., EVAC_Z_OFFSET=1.0/
&OBST XB= 7.3,7.5,-13.0,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,14.1,-15.0,-14.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,14.1,-11.0,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 14.1,14.2,-15.0,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.5,12.6,-13.0,-12.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 49.8,50,-13.0,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 49.8,56.6,-15.0,-14.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 49.8,56.6,-11.0,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 56.6,56.7,-15.0,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 50,55.1,-13.0,-12.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,7.5,35.5,38,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,14.1,39.5,40,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.3,14.1,35.5,36,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 14.1,14.2,35.5,40,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 7.5,12.6,37.5,38,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 49.8,50,35.5,38,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 49.8,56.6,39.5,40,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 49.8,56.6,35.5,36,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 56.6,56.7,35.5,40,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 50,55.1,37.5,38,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 14.1,45,-11,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 56.6,67.5,-11,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 14.1,45,35.5,36,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 56.6,67.5,35.5,36,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 44.8,45,-15,-10.5,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/
&OBST XB= 44.8,45,35.5,40,18.0,40.0, EVACUATION=.TRUE., SURF_ID='INERT'/

&DOOR ID='workdeck-1-1', FYI='Comment line', XB=7.5,7.5,-12.5,-11,19.4,19.6, XYZ=7.6,-12.05,19.5, MESH_ID=workdeck, IOR=-1, TO_NODE='workdeck-1-11', EXIT_SIGN=.TRUE., KEEP_XY=.TRUE., COLOR='PINK'/
&ENTR ID='workdeck-1-11', FYI='Comment line', XB=7.3,7.3,-12.5,-11,29.4,29.6, MESH_ID=workdeck-, IOR=-1/
&EVSS ID='IntLanding', XB=12.6,14.1,-14.5,-11.0, 19.4,19.6, IOR=1, HEIGHT=4.1, HEIGHT0=4.1/
&EVSS ID='workdeck-landing1', XB= 7.5,12.6,-14.5,-13.0,19.4,19.6, IOR=1, HEIGHT0=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/
&EVSS ID='landing-workdeck1', XB= 7.5,12.6,-12.5,-11.0,19.4,19.6, IOR=-1, HEIGHT0=10, HEIGHT=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/

&DOOR ID='workdeck-1-2', FYI='Comment line', XB=50,50,-12.5,-11,19.4,19.6, XYZ=50.1,-12.05,19.5, MESH_ID=workdeck, IOR=-1, TO_NODE='workdeck-1-22', EXIT_SIGN=.TRUE., KEEP_XY=.TRUE., COLOR='PINK'/
&ENTR ID='workdeck-1-22', FYI='Comment line', XB=49.8,49.8,-12.5,-11,29.4,29.6, MESH_ID=workdeck-, IOR=-1/
&EVSS ID='IntLanding-2', XB=55.1,56.6,-14.5,-11.0, 19.4,19.6, IOR=1, HEIGHT=4.1, HEIGHT0=4.1/
&EVSS ID='workdeck-landing2', XB= 50,55.1,-14.5,-13.0,19.4,19.6, IOR=1, HEIGHT0=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/
&EVSS ID='landing-workdeck2', XB= 50,55.1,-12.5,-11.0,19.4,19.6, IOR=-1, HEIGHT0=10, HEIGHT=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/

&DOOR ID='workdeck-1-3', FYI='Comment line', XB=7.5,7.5,36,37.5,19.4,19.6, XYZ=7.6,37.05,19.5, MESH_ID=workdeck, IOR=-1, TO_NODE='workdeck-1-33', EXIT_SIGN=.TRUE., KEEP_XY=.TRUE., COLOR='PINK'/
&ENTR ID='workdeck-1-33', FYI='Comment line', XB=7.3,7.3,36,37.5,29.4,29.6, MESH_ID=workdeck-, IOR=-1/
&EVSS ID='IntLanding-3', XB=12.6,14.1,36,39.5, 19.4,19.6, IOR=1, HEIGHT=4.1, HEIGHT0=4.1/
&EVSS ID='workdeck-landing3', XB= 7.5,12.6,38,39.5,19.4,19.6, IOR=1, HEIGHT0=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/
&EVSS ID='landing-workdeck3', XB= 7.5,12.6,36,37.5,19.4,19.6, IOR=-1, HEIGHT0=10, HEIGHT=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/

&DOOR ID='workdeck-1-4', FYI='Comment line', XB=50,50,36,37.5,19.4,19.6, XYZ=7.6,37.05,19.5, MESH_ID=workdeck, IOR=-1, TO_NODE='workdeck-1-44', EXIT_SIGN=.TRUE., KEEP_XY=.TRUE., COLOR='PINK'/
&ENTR ID='workdeck-1-44', FYI='Comment line', XB=49.8,49.8,36,37.5,29.4,29.6, MESH_ID=workdeck-, IOR=-1/
&EVSS ID='IntLanding-4', XB=55.1,56.6,36,39.5, 19.4,19.6, IOR=1, HEIGHT=4.1, HEIGHT0=4.1/
&EVSS ID='workdeck-landing4', XB= 50,55.1,38,39.5,19.4,19.6, IOR=1, HEIGHT0=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/
&EVSS ID='landing-workdeck4', XB= 50,55.1,36,37.5,19.4,19.6, IOR=-1, HEIGHT0=10, HEIGHT=4.1, FAC_V0_UP=0.4, FAC_V0_DOWN=0.7/

&PERS ID='Adult', FYI='Male+Female diameter and velocity', DEFAULT_PROPERTIES='Adult', DET_EVAC_DIST=1, DET_LOW=1.0, DET_HIGH=3.0, PRE_EVAC_DIST=1, PRE_LOW=2.0, PRE_HIGH=4.0/

&EXIT ID='Exit', FYI='Comment line', XB=67.5,67.5,10.0,15.0,29.4,29.6, MESH_ID=workdeck-, COLOR='YELLOW', XYZ=67,35,29.5, IOR=1/

&EVAC ID='Agents-1', XB=10.0,50.0,0.0,30.0,19.4,19.6, NUMBER_INITIAL_PERSONS=100, PERS_ID='Adult', AVATAR_COLOR='BLUE', /

&TAIL /

**Comment by gjaeger** [comment]
@StarAlex-Wang: In your opinion, is this a bug or an application issue for the [discussion group](https://groups.google.com/g/fds-smv)?
