### ISSUE TITLE
 a issue about fds2ascii

### ISSUE THREAD

**Issue by 429321667** [firemodels/fds#9932]
Disk usage is only 2MB/s while the CPU usage is up to 26% and more when I use fds2ascii. however, disk usage is 130MB/s while the CPU usage is no more than 1% when I use fds2ascii in an other case.
The lower disk usage make the data reading process very long. Does anyone know how to solve this problem?

**Comment by mcgratta** [comment]
I do not understand the problem. Are you running multiple instances of fds2ascii?

**Comment by 429321667** [comment]
![23B3238F-773F-49EA-B175-D14819051B4B](https://user-images.githubusercontent.com/91475209/134931295-254af2d0-4ac6-4770-b669-d5206384caf6.jpeg)
Thank you for reply me. No, I didn't run multiple instances of fds2ascii before. Firstly I run a single instance of fds2ascii, but found out that it's too slow campare with the cases before. For example, now I should pay 2 hours to finish this one  fds2ascii, but for the cases before, I only pay 10 minutes. later, I run multiple instances of fds2ascii for comparison, as shown in the figure

**Comment by drjfloyd** [comment]
Your screenshot shows one of your fds2ascii is being run on drive J and one is being run on drive I. Is one a network drive and one a local drive?

**Comment by 429321667** [comment]
No, they're my mobile hard disks. I tried to copy the result 18 from I to J, and used fds2ascii in 18 from J. Unfortunately, the result is the same. The usage of disk only 2mb/s.

**Comment by mcgratta** [comment]
I suggest that you only run one fds2ascii session at a time, and that you access data that is on your local hard drive. Running multiple copies of fds2ascii and accessing remote data is going to result in a slowdown.

**Comment by 429321667** [comment]
Thanks for your suggestion. I have tried it as you suggestion, but it didn't work. The usage of disk only 2MB/s, and my result up to 15GB. so I pay nearly two hours to finish one fds2ascii process

**Comment by drjfloyd** [comment]
How different are cases 18 and 30?  Are these the same geometry and the same meshing? If they are the same geometry and the same meshing, are the data files similar size? If there are major differences in the size of the data files, this could be the reason.

**Comment by 429321667** [comment]
Thanks for your reply. I think it's no large different. case 18 only has temperature 3d-slice. While case 30 has temperature and velocity 3d-slice. The only difference between them, is that case 18 was not checked 'use vector' while case 30 was checked 'use vector'.

**Comment by mcgratta** [comment]
If you copy all the FDS output files to the hard drive of your computer, is there still a problem reading the data?

**Comment by 429321667** [comment]
Thanks for your reply. Yes, the same problem still in these cases that in my computer. I guess that the setting of FDS cause the problem. such as whether the 'use vector' was checked.

**Comment by mcgratta** [comment]
fds2ascii is more than 20 years old, and probably uses memory inefficiently. There are newer and better scripts to parse output files, so we haven't spent much time working on fds2ascii. One thing to check is whether you set VECTOR=T on more than one SLCF line that defines the same plane, or if you set VECTOR=T for a 3D slice. You may be saving a very large amount of data, and fds2ascii is not optimized for it.

**Comment by 429321667** [comment]
Thanks for your reply. Yes, I set vector＝T for a 3D slice before. The case of lower usage of disk was set vector＝F for 3D-slice. Could you suggest some better script to parse output files for me?

**Comment by mcgratta** [comment]
Post your question to the Discussion Group. I've never parsed a 3D slice
file before. Alternatively, you can obtain the source of fds2ascii.f90 and
compile it yourself and modify the array dimensions.

>
