### ISSUE TITLE
Naming restart files...

### ISSUE THREAD

**Issue by shende11** [firemodels/fds#9933]
Would it be possible to add an optional parameter to the &CTRL line so that when outputting a restart file, it is named as specified by the parameter? For example, 

&CTRL ID='restart', FUNCTION_TYPE='RESTART', RESTART_FILE_NAME='fire1.restart' /

Thanks,
Anil Shende
Roanoke College

**Comment by rmcdermo** [comment]
Is this really necessary?  You can rename restart files to whatever you want using `mv chid.restart fire1.restart` and then use `RESTART_CHID=fire1.restart` on `MISC`.

**Comment by shende11** [comment]
Hello Mr. McDermott,

I am using FDS to render the spread of fire in VR, and then be able to interact with the scene (such as add a fire line to a forest fire, or chop down trees), and have FDS restart to take into account the changed input. Towards this, I would like to save the restart files every so often so that I can revert back to a restart file just prior to the interaction. Unfortunately, since the restart file names do not change, the new restart file is opened by FDS right after the old one is closed, and so I cannot copy the old restart file.

Also, I do not know the binary structure of the restart file, so if I am able to copy a restart file, I cannot tell which restart file was copied, i.e., after what time unit. If I can name the restart files each time I want them, that'll solve my problem.

Hope my explanation is clear enough. Please let me know if you need me to elaborate.

Thanks for any help/advice you can give me.
Anil

Dr. Anil M. Shende
Professor of Computer Science
Math., Comp. Sci. & Physics Department
Roanoke College
221 College Lane, Salem, VA 24153.
Tel: +1-540-375-2341

________________________________

**Comment by mcgratta** [comment]
I suggest that you write a little bash script that periodically reads the CHID.err file, determines the current time, and moves restart files into appropriately labelled subdirectories. In the meantime, we can see if there is an easy to way to tag these restart files.

**Comment by shende11** [comment]
Dear Mr. McGrattan,

The issue is as follows: I am using Unity as the VR engine. I run FDS in a separate thread. I have FDS output a restart file every 20 seconds. At 20 seconds, FDS opens the restart file and starts writing to it. When it finishes, it seems that it closes the file and almost immediately opens it (since the restart files have the same name) to start writing for the 40 second time. Even if I increase the interval, it seems to have the same behaviour. So, when the Unity thread tries to copy the file, the file seems to be locked by FDS, and so cannot be copied. I have this issue on a couple of different machines, so I do not think it is the processor speed that is the issue.

I understand that the restart feature was not quite meant to be used in the way I am trying to use it. Nonetheless, being able to tag the files will resolve the issue.

Thanks for all your help and consideration.
Anil

Dr. Anil M. Shende
Professor of Computer Science
Math., Comp. Sci. & Physics Department
Roanoke College
221 College Lane, Salem, VA 24153.
Tel: +1-540-375-2341

________________________________

**Comment by mcgratta** [comment]
The file is opened at the time of the restart and closed immediately after writing the data. The file is not intentionally locked. Try moving the file(s) at 25 s to another directory. Are you running under linux?
