### ISSUE TITLE
User Guide: VENT applied to GEOM

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#9934]
Section 10.3.3 of the User Guide says it is not possible to apply GEOM boundary conditions via a VENT, but Section 19.5 introduces the GEOM flag for the VENT namelist. 

I guess we want to fix the contradiction by saying (in Section 10.3.3) that the feature is in development, but since I'm not working on this, I didn't want to start editing without checking.

**Comment by rmcdermo** [comment]
Thanks, I'll fix.

**Comment by rmcdermo** [comment]
Should be fixed with #9936
