### ISSUE TITLE
STOP: Numerical Instability

### ISSUE THREAD

**Issue by elauretti** [firemodels/fds#9947]
Goodmorning to everybody,

I don't understand the reason why i had this message errore: can someone help me?

Thank you

STOP: Numerical Instability (CHID: TM)
[unset]: write_line error; fd=632 buf=:cmd=finalize
:
system msg for write_line failure : No such file or directory

[TM.txt](https://github.com/firemodels/fds/files/7264808/TM.txt)

**Comment by drjfloyd** [comment]
Try following the guidance in Section 9.3 of the User's Guide.

**Comment by elauretti** [comment]
Thank you very much
