### ISSUE TITLE
GEOM error when used with nightly build of FDS

### ISSUE THREAD

**Issue by dwstroup205** [firemodels/fds#9952]
Using the GEOM line in an FDS input file with the latest nightly build generates a segmentation error.  The input file that includes the GEOM lines runs without error when using the latest official release.  A sample input file is attached.
[Conduit2in.txt](https://github.com/firemodels/fds/files/7278309/Conduit2in.txt)

**Comment by marcosvanella** [comment]
Thank you for reporting. We'll have a look.

**Comment by marcosvanella** [comment]
@dwstroup205 do an update and try the case. I fixed a bug related to back faces in heat transfer. Also note that GEOMs currently do not support the burn away feature in their surfaces. I added a stop message that should show up in tonights nightly bundle. If you built this model in BlenderFDS and need burn away, I suggest you choose to voxelize the geometries (write as OBST). Thanks.

**Comment by mcgratta** [comment]
Dave, any progress?

**Comment by dwstroup205** [comment]
Thanks!
That fixed the error and I don't need burnaway at this time.
