### ISSUE TITLE
Unbalanced stoichiometry

### ISSUE THREAD

**Issue by elauretti** [firemodels/fds#9956]
Goodmorning,
please can someone help me with this unbalanced stoichiometry?

Thank you very much.

ERROR: Problem with REAC   2. Unbalanced stoichiometry.

 Gas Phase Reaction Information

   Reaction ID:  benzene_combustion

   Stoichiometry

   Primitive Species
   Species ID                                                 Stoich. Coeff.
   OXYGEN                                                         -11.475000
   NITROGEN                                                         0.000000
   WATER VAPOR                                                      3.000000
   CARBON DIOXIDE                                                   6.000000
   BENZENE                                                         -1.000000

   Tracked (Lumped) Species
   Species ID                                                 Stoich. Coeff.
   AIR                                                            -39.675000
   BENZENE                                                         -1.000000
   BENZENE_PRODUCTS                                                37.200000

Atom Balance Details

   Tracked (Lumped) Species:AIR
   Element  nu*Atom Count
   N       -56.400000
   O       -22.950000

   Tracked (Lumped) Species:PVC
   Element  nu*Atom Count

   Tracked (Lumped) Species:PRODUCTS
   Element  nu*Atom Count

   Tracked (Lumped) Species:BENZENE
   Element  nu*Atom Count
   H        -6.000000
   C        -6.000000

   Tracked (Lumped) Species:BENZENE_PRODUCTS
   Element  nu*Atom Count
   H         6.000000
   C         6.000000
   N        56.400000
   O        15.000000

The following elements are unbalanced:

Element  Atom Error
  O      -0.795E+01

 (CHID: Diesel)

STOP: FDS was improperly set-up (CHID: Diesel)

[Diesel_.txt](https://github.com/firemodels/fds/files/7291493/Diesel_.txt)

**Comment by drjfloyd** [comment]
The issue tracker is for reporting bugs. For general questions in how to use FDS please use the discussion forum:
https://groups.google.com/g/fds-smv
