### ISSUE TITLE
User Guide Table 24.1: FDS source code files

### ISSUE THREAD

**Issue by Er9y714** [firemodels/fds#9959]
Table 24.1 lists the file **irad.f90** but current source code files do not have this. Is this file merged into radi.f90?

I will look into the code to understand how RADCAL lookup tables work. 
Thanks.

**Comment by rmcdermo** [comment]
Thanks.  I believe this has been changed to rcal.f90 in the latest source.  I'll update the guide.

**Comment by rmcdermo** [comment]
Should be fixed with #9960
