### ISSUE TITLE
DEVC question

### ISSUE THREAD

**Issue by fidran** [firemodels/fds#9965]
I add these DEVC lines to my case :
A:
&DEVC ID='OX280a', XB=0.3,0.9, 0.465,0.50, 2.78,2.80, QUANTITY='MASS FRACTION',  SPEC_ID='OXYGEN' /

B:
&DEVC ID='OX280b', XB=0.3,0.9, 0.465,0.50, 2.78,2.80, QUANTITY='MASS FRACTION',  SPEC_ID='OXYGEN', STATISTICS = 'MEAN' / 
C:
&DEVC ID='OX280c', XB=0.3,0.9, 0.465,0.50, 2.78,2.80, QUANTITY='MASS FRACTION',  SPEC_ID='OXYGEN', SPATIAL_STATISTIC='MASS MEAN' /

Line A, I thought this should give me a mean value….
Line B, STATISTICS = 'MEAN'  -  I found this line in one of the example cases – I can’t find any explanation in the user guide – what does it output ?
Line C, SPATIAL_STATISTIC=’MASS MEAN’ – this one is explained in the user guide 21.3
![Mass fraction](https://user-images.githubusercontent.com/40716592/136471594-3f7bed6c-90f5-4552-b760-81c9f2a92421.jpg)
0

**Comment by drjfloyd** [comment]
If you use XB with a point device and no SPATIAL_STATISTIC, FDS converts the XB to the midpoint XYZ. This does not appear to be in the guide, and we should add that. 

MEAN is defined with Eq. 21.28 in the User's Guide. It is just the average value over all the grid cells in XB.

**Comment by fidran** [comment]
Does this means that "SPATIAL_STATISTIC" and "STATISICS" are synonyms ?

**Comment by rmcdermo** [comment]
Not completely.  STATISTICS is deprecated.  We've changed to SPATIAL_STATISTC and TEMPORAL_STATISTIC because often you might want to apply both to a single DEVC.

**Comment by drjfloyd** [comment]
STATSITCS was used in older versions of FDS. In the current version it is SPATIAL_STATISTIC and TEMPORAL_STASTISTIC. For backwards compatibility we still allow, for now, the use of STATISTICS.

**Comment by drjfloyd** [comment]
Added a note in the guide that XB is converted to XYZ if no SPATIAL_STATISTIC is given for a point device.
