### ISSUE TITLE
Divide by zero issue in HT3D case

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9967]
Run `Fires/box_burn_away1_pyro3d_transport.fds` in debug mode out to 18 s and you should see a float by zero error. I stumbled across this while debugging my new stuff, but it also fails with the current repo code. I cannot figure out what's going wrong, and I think that maybe something in the HT3D routine might be zeroing out a density. I see this
```
 Time Step:   1700, Simulation Time:     17.00 s
 Time Step:   1800, Simulation Time:     18.00 s
forrtl: error (73): floating divide by zero
Image              PC                Routine            Line        Source
fds_impi_intel_li  00000000042FAF6B  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AB7E17BF630  Unknown               Unknown  Unknown
fds_impi_intel_li  0000000003FFCEF6  divg_mp_divergenc         156  divg.f90
fds_impi_intel_li  0000000004124649  MAIN__                    808  main.f90
fds_impi_intel_li  0000000000408822  Unknown               Unknown  Unknown
```

**Comment by rmcdermo** [comment]
Should be fixed with #9969 .  We can reopen if it pops up again.  But all this could should go away once Simo and Christian get their stuff working.
