### ISSUE TITLE
Segmentation fault occurred

### ISSUE THREAD

**Issue by AlbertoPrevedello** [firemodels/fds#9973]
I am working on a FDS project whit more than 600K cells.

I've test the model that works fine on my machine (Windows, CPU and **16gb** Memory), so I opened an AWS (Amazon Web Service) account to run the project in a EC2 (Amazon Linux 2, C5.2xlarge, 8 virtual CPU and **16gb** Memory).

Problem:
When I've run the code on a single AWS EC2 instance, I get a segmentation fault ("**forrtl: severe (174): SIGSEGV, segmentation fault occurred**"), even though the code worked fine on my machine. I really want to understand this problem, I reduced the cells number of the project, (100k by 100k) for individueted the limit number  below that it don't run, it is 380K aproximately.
Then, I run the code on a single AWS EC2 instance greater (Amazon Linux 2, C5.4xlarge, 16 virtual CPU and **32gb** Memory), the limit remains at 380k cells aproximately.

I don't undestand if the problem is correlated at the EC2 AWS istance limit, Linux OS limit or another.

I'm Sorry for my english.
Thank you in advance.

Alberto

Ps: part of the code below

&HEAD CHID='C3_1_09', TITLE='C3_1_09'/

&TIME T_END=5400

&MISC TMPA=25.0
      BNDF_DEFAULT=.FALSE. /
	  
&DUMP DT_RESTART=300.00, 
	  MASS_FILE=.TRUE.,
	  NFRAMES=540,/

&MESH ID='C1', COLOR='RED',   IJK=190,90,40, XB=04,42,04,22,00,08   FYI='Cell=0.2^3 - 684000 celle' /
&MESH ID='C1', COLOR='BLUE',  IJK=095,10,20, XB=04,42,00,04,00,08   FYI='Cell=0.4^3 - 19000  celle' /
&MESH ID='C1', COLOR='RED',   IJK=095,05,20, XB=04,42,22,24,00,08   FYI='Cell=0.4^3 - 9500   celle' /
&MESH ID='C1', COLOR='RED',   IJK=010,60,20, XB=00,04,00,24,00,08   FYI='Cell=0.4^3 - 12000  celle' /
&MESH ID='C1', COLOR='BLUE',  IJK=005,60,20, XB=42,44,00,24,00,08   FYI='Cell=0.4^3 - 6000   celle' /
&MESH ID='C1', COLOR='RED',   IJK=110,60,05, XB=00,44,00,24,08,10   FYI='Cell=0.4^3 - 33000  celle	TOT=763500' /

...

**Comment by mcgratta** [comment]
There's not much we can do if the case runs on your local computer. I would only suggest that you make sure that you are using the exact same executable on both computers, and the exact same input file, number of cores, etc.

**Comment by ericvmueller** [comment]
Just a thought...
you could try [increasing the stack size](https://github.com/firemodels/fds/wiki/Setting-Stack-Size) on your EC2 instance, using:
`ulimit -s unlimited`

I found this helped with some issues I was having in the past. For this command to work on Amazon Linux 2, you may need to first increase the hard limit, by adding:
`* hard stack unlimited`
to your `/etc/security/limits.conf` file, and then log in to a new shell.

**Comment by AlbertoPrevedello** [comment]
Thank you so much for both answers.

I solved the problem, pubblic the resolution to all the users.

For increase the stack size and avoid the error: "severe (174): SIGSEGV, segmentation fault occurred", is necessary to do:

- the command `ulimit -s unlimited` is not permitted;

- modify the file `/etc/security/limits.conf` with comand `nano`;
- the file `/etc/security/limits.conf` is protected and unwritteble, use `sudo nano` comand to resolve the problem;
- put into the file (`/etc/security/limits.conf`) this lines: `* hard stack unlimited` and `* soft stack unlimited`;
- reebot the session;
- check the result whit `ulimit -s` comand.

Thank you all again.

Alberto

**Comment by mcgratta** [comment]
Thanks for that information. Just to clarify, nano is just a text editor. One should be able to modify the limits.conf file with any text editor. At NIST, our limits.conf file includes the lines:
```
*                hard    core            0
* hard memlock unlimited
* soft memlock unlimited
*               soft    stack           unlimited
*               hard    stack           unlimited
```
