### ISSUE TITLE
Forced tunnel flow: OBST vs GEOM

### ISSUE THREAD

**Issue by ericvmueller** [firemodels/fds#9977]
I'm trying to just force a flow through a tunnel, and I've encountered an issue in the pressure/velocity depending on whether the walls are defined with `OBST` or `GEOM` lines (I'd like the walls resolved within the domain).

 This simplified example shows the error when block `GEOM` lines are used. If the block `GEOM` lines are switched out for `OBST` lines, there is no issue.

Ideally I'd like to keep using the `GEOM` lines so that: 1) I can tweak grid resolution without having to worry about the snapping of the tunnel walls, and 2) I can eventually accommodate more complex geometry further downstream

[tunnel_baseline.txt](https://github.com/firemodels/fds/files/7366917/tunnel_baseline.txt)

**Comment by rmcdermo** [comment]
Eric,
We are aware of these issues.  GEOM is just not ready for this right now.  Please use OBST until we do a beta release.
