### ISSUE TITLE
Mass flow bug

### ISSUE THREAD

**Issue by mcgratta** [firemodels/fds#9978]
Hi - I am trying to monitor mass flow in and out of my domain, see example below. Recent nightly release (FDS6.7.6-776-gea28f1b9f-nightly) giving 0.0 for mass and volume flow at the inlet. Previous versions did not do this. Outlet side flows are ok.
```
&HEAD CHID='Ex',TITLE='Ex' /
&MESH IJK=100,22,20,XB=-20.0,20.0,-4.4,4.4,0.0,8.0 / 
&VENT XB=-20.0,-20.0,-4.4,4.4,0.0,8.0,SURF_ID='INVENT' /
&SURF ID='INVENT',VEL=-3.00,RGB=100,20,20 / 
&VENT XB=20.0,20.0,-4.4,4.4,0.0,8.0,SURF_ID='OPEN' /
&TIME T_END=90.0 /
&DEVC XB=-20.0,-20.0,-4.4,4.4,0.0,8.0,QUANTITY='MASS FLOW WALL', IOR=1, ID='MASS FLOW in' /
&DEVC XB=-20.0,-20.0,-4.4,4.4,0.0,8.0,QUANTITY='VOLUME FLOW WALL', IOR=1, ID='VOLUME FLOW in'/
&DEVC XB=20.0,20.0,-4.4,4.4,0.0,8.0,QUANTITY='MASS FLOW WALL', IOR=-1, ID='MASS FLOW out' /
&DEVC XB=20.0,20.0,-4.4,4.4,0.0,8.0,QUANTITY='VOLUME FLOW WALL', IOR=-1, ID='VOLUME FLOW out' /
&TAIL /
```

**Comment by rmcdermo** [comment]
Want me to bisect, or are you in the middle of it?

**Comment by mcgratta** [comment]
Unless you've changed that output, I'll check out it. Looks like we need `MASS FLOW` at the `OPEN` boundary.

**Comment by mcgratta** [comment]
This is a bug we introduced when finessing different kinds of devices that fall on mesh or cell boundaries. It's the the old less than/less than or equal to problem. For the moment, try this
```
&DEVC XB=-19.99,-20.0,-4.4,4.4,0.0,8.0,QUANTITY='MASS FLOW WALL', IOR=1, ID='MASS FLOW in' /
&DEVC XB=-19.99,-20.0,-4.4,4.4,0.0,8.0,QUANTITY='VOLUME FLOW WALL', IOR=1, ID='VOLUME FLOW in'/
```

**Comment by mcgratta** [comment]
Correction:
```
&DEVC XB=-19.99,-19.99,-4.4,4.4,0.0,8.0,QUANTITY='MASS FLOW WALL', IOR=1, ID='MASS FLOW in' /
&DEVC XB=-19.99,-19.99,-4.4,4.4,0.0,8.0,QUANTITY='VOLUME FLOW WALL', IOR=1, ID='VOLUME FLOW in'/
```
I did some digging and discovered that we use this hack in our test cases too. The problem is that `MASS FLOW WALL` is applied like a gas phase output quantity, but it really is a solid phase output quantity. The gas and solid outputs are handled differently because of orientation issues, grid snapping, etc. 

To the developers -- I propose that we get rid of `VOLUME FLOW WALL`, `MASS FLOW WALL`, and `HEAT FLOW WALL` and replace them with currently established solid phase output plus the `SURFACE INTEGRAL` spatial statistic. There's an increasing amount of redundant output quantities, each subtly different than the other, but confusing.

**Comment by rmcdermo** [comment]
The `'MASS FLOW WALL'`, etc., were established because the "currently established" solid phase outputs, as you call them, do not work to give tight mass balances.  This is discussed in the user guide.

**Comment by mcgratta** [comment]
Because of this issue, I overhauled the "FLOW" outputs, replacing them with SPATIAL_STATISTIC
