### ISSUE TITLE
How to run fds on python?

### ISSUE THREAD

**Issue by Pacifist2503** [firemodels/fds#9979]
Please tell me how to edit this code to run fds on python?

> import os
> from subprocess import Popen, PIPE
> base = (os.getcwd())
> string = f"{base}/1"
> os.chdir(string)
> cmd = 'cmd.exe'
> p = Popen(cmd, stdin=PIPE, stdout=PIPE, bufsize=0, shell=True)
> p.stdin.write(rb"fdsinit\ D:\Python\Project\Repositories\Project_Clicker\Run_FDS\1")
> p.stdin.write(b"fds_local -p 2 -o 1 b_1.fds")
> cc = p.stdin.close()
> vv = p.wait()

File.fds is located in the folder D:\Python\Project\Repositories\Project_Clicker\Run_FDS\1

**Comment by rmcdermo** [comment]
The Issues page is for reporting FDS bugs.  Please post your question to the discussion forum.  Thanks
